### ISSUE TITLE
be able to do conditional things in playbooks

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#10]
example:  if X is in the variables, do this

also should probably include previous command results in those vars

```
- name: blah
action: foo
if: x equal 3

- name: blah
action: foo
if: x like bar
```

ETC ETC ETC

**Comment by mpdehaan** [comment]
possible uses:

if this is the os

if in this subnet or whatever

if the last command returned X

**Comment by mpdehaan** [comment]
also want to be able to do maybe

```
- action: blah
  poll:  timeout=30 check_interval=5
  onfail:   
```

so it's like a "notify" but different

**Comment by mpdehaan** [comment]
Q: does fail mean stop unless there is an onfail?

**Comment by mpdehaan** [comment]
more random thoughts:

```
- name: foo
  switch:
     - var: asdf
         - case: $facter_fqdn 
           then: value
         - case: $facter_fqdn  # this is a Python expression after replacing the dollar signs
           then: bar                  # this too
  action: module param1 param2 $asdf
```

**Comment by mpdehaan** [comment]
Attempting to iterate on this:

<pre>
    - name: foo
      calculate_vars:
         - asdf
             - if: $facter_fqdn.endswith(".rtp.example.org") 
               then: 'foo'
             - elif: $facter_fqdn.startswith(".atl.example.org")  # this is a Python expression after replacing the dollar signs
               then: 'bar'
             - else: 'default'
      action: module param1 param2 $asdf

</pre>


?

**Comment by mpdehaan** [comment]
calculate_vars should not be part of a task because vars should be reusable

```
-  calculate_vars:
     - asdf
         - if: $facter_fqdn.endswith(".rtp.example.org") 
           then: 'foo'
         - elif: $facter_fqdn.startswith(".atl.example.org")  # this is a Python expression after replacing the dollar signs
           then: 'bar'
         - else: 'default'

- tasks:
      - name:  foo
        action: module param1 param2 $asdf
        onlyif:  expression goes here
```

**Comment by mpdehaan** [comment]
```
 -  calculate_vars:
     - if: $facter_fqdn.endswith(".rtp.example.org") 
       then:
           asdf: 'foo'
     - elif: $facter_fqdn.startswith(".atl.example.org")  # this is a Python expression after replacing the dollar signs
       then:
           asdf: 'bar'
     - else:
           asdf: 'default' 

- tasks:
  - name:  foo
    action: module param1 param2 $asdf
    onlyif:  expression goes here
```

**Comment by skvidal** [comment]
So that seems to make simple things harder.

the obvious cases you'd see here are in pseudo-code:

if $distrover == "6":
    install somepkg
    service  someprocess start
elif $distrover == "5":
    install someotherpkg
    service  someotherprocess start
else:
     error_print("$distrover doesn't match anything")

That seems likely to be the most common case - being able to define a task is much like a function - and those are great - but the 'run these two things' seem like a really common case. With most languages it is very important to make the common things trivial and the uncommon things possible.

**Comment by mpdehaan** [comment]
```
 - conditional_vars:
    - apache:
        - [ " $facter_os == 'Debian' " , 'apache' ]
        - [ " $facter_os == 'RedHat' ", 'httpd' ]

- tasks:
    - name:  install apache
      action:  yum blarg $apache
      onlyif: $facter_os == 'RedHat'
   - name: install apache
      action: apt blarg $apache
      onlyif: $facter_os == 'Debian'
```

?

**Comment by skvidal** [comment]
it still feels like everything is defined far away from where you use it. I would expect the tasks section to get larger along  with the conditional_vars, too.

so, conceptually something like this seems more reasonable for day-to-day use:

```
- name:  install apache
- action: 
    if   " $facter_os == 'Debian' ":
        apt ensure=installed pkg=apache
        service httpd start
    elif  $facter_os == 'RedHat':
        yum ensure=installed pkg=httpd
        systemctl enable httpd.service
    else:
        error_msg("Could not action for facter_os = $facter_os")
```

**Comment by mpdehaan** [comment]
Inside of tasks list, a list of both task (name+action) and conditional_set elements:

```
- conditional_set:
    - "$facter_os == 'Debian' ":
        - install_apache: apt ensure=installed pkg=apache
        - restart_apache: service httpd start
    - "$facter_os == 'RedHat' ":
        - install_apache: yum ensure=installed pkg=httpd
        - restart_apache: systemctl enable httpd.service
    # possibly some error syntax  

- name: install apache
  action: $install_apache
- name: restart apache
  action: $restart_apache
  onlyif: $somevar == X   # totally optional to use this
```

possibly some errorif syntax too

and you can interlace conditional_sets and tasks all you want

we could also put in automagic such that if the action line starts with "$" and it wasn't evaluated we just skip the step
