### ISSUE TITLE
Add support for inactive interfaces and bonding to setup module

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1001]
Currently the setup module does not return any information regarding inactive interfaces and bonding.

Since we need e.g. the macaddress for configuring the interface configuration, we cannot do that if the interface is not part of the facts (because it is down). For provisioning this is a must.

The case is different for bonding interfaces, without information about the bonding configuration, we cannot use the template engine to recreate an existing configuration. So it would be nice to have that information as well.

**Comment by mpdehaan** [comment]
patches accepted

**Comment by dagwieers** [comment]
Implementation would look like the below. Feedback welcome:

``` yaml
### Bridge
br0: {
  device: br0,
  macaddress: aa:bb:cc:dd:ee:ff, 
  type: bridge,
  interfaces: [ eth0, eth1, ath0 ],
  stp: true,
  id: some-id
}

### Active interface
eth0: {
  device: eth0,
  macaddress: aa:bb:cc:dd:ee:ff, 
  type: ether,
  active: true,
  ipv4: {
    address: 1.2.3.4, 
    netmask: 255.255.255.0, 
    network: 1.2.3.0
  }, 
  mtu: 1500
} 

### Inactive interface
eth3: {
  device: eth3,
  macaddress: aa:bb:cc:dd:ee:ff, 
  type: ether,
  active: false
}

### Bonding device
bond0: {
  device: bond0,
  macaddress: aa:bb:cc:dd:ee:ff,
  type: bonding,
  mode: active-backup,
  primary: eth0,
  slaves: [ eth0, eth1 ],
  slave_eth0: {
    macaddress: aa:bb:cc:dd:ee:ff,
    status: up,
    active: true
  },
  slave eth1: {
    macaddress: aa:bb:cc:dd:ee:00,
    status: up,
    active: false
  },
  status: up,
  pollinterval: 100
}
```

**Comment by mpdehaan** [comment]
assuming the 'eth0' fact remains 'ansible_eth0', and we don't rename the
facts to just the name of the interface (since that would break existing
playbooks) this looks very good to me.

**Comment by dagwieers** [comment]
Yup, I was describing the facts as they are added. So indeed ansible_ is prepended.

**Comment by dagwieers** [comment]
I currently have this:

``` yaml
[dag@moria ansible]$ ./network.py
{
    "br0": {
        "active": false, 
        "device": "br0", 
        "id": "8000.aabbccddeeff", 
        "interfaces": [
            "eth0"
        ], 
        "macaddress": "aa::bb:cc:dd:ee:ff", 
        "mtu": 1500, 
        "stp": false, 
        "type": "bridge"
    }, 
    "eth0": {
        "active": false, 
        "device": "eth0", 
        "ipv4": {
            "address": "1.2.3.10", 
            "netmask": "255.255.255.0", 
            "network": "1.2.3.0"
        }, 
        "macaddress": "aa:bb:cc:dd:ee:ff", 
        "module": "e1000e", 
        "mtu": 1500, 
        "type": "ether"
    }, 
    "eth0:1": {
        "active": false, 
        "device": "eth0", 
        "ipv4": {
            "address": "1.2.3.6", 
            "netmask": "255.255.255.0", 
            "network": "1.2.3.0"
        }, 
        "macaddress": "aa:bb:cc:dd:ee:ff", 
        "module": "e1000e", 
        "mtu": 1500, 
        "type": "ether"
    }, 
    "eth0:2": {
        "active": false, 
        "device": "eth0", 
        "ipv4": {
            "address": "1.2.3.2", 
            "netmask": "255.255.255.0", 
            "network": "1.2.3.0"
        }, 
        "macaddress": "aa:bb:cc:dd:ee:ff", 
        "module": "e1000e", 
        "mtu": 1500, 
        "type": "ether"
    }, 
    "lo": {
        "active": true, 
        "device": "lo", 
        "ipv4": {
            "address": "127.0.0.1", 
            "netmask": "255.0.0.0", 
            "network": "127.0.0.0"
        }, 
        "mtu": 16436, 
        "type": "loopback"
    }, 
    "pan0": {
        "active": false, 
        "device": "pan0", 
        "id": "8000.000000000000", 
        "interfaces": [], 
        "macaddress": "dd:aa:cc:ee:bb:ff", 
        "mtu": 1500, 
        "stp": false, 
        "type": "bridge"
    }, 
    "wlan0": {
        "active": true, 
        "device": "wlan0", 
        "ipv4": {
            "address": "192.168.1.33", 
            "netmask": "255.255.255.0", 
            "network": "192.168.1.0"
        }, 
        "macaddress": "ff:ee:cc:dd:aa:bb", 
        "module": "iwlwifi", 
        "mtu": 1500, 
        "type": "ether"
    }
}
```

No bonding yet.

**Comment by dagwieers** [comment]
New update with bonding implemented. And yes, it makes no sense to bond eth0 with pan0, amazing that you even can... (bonding eth0 and ppp0/3g crashed my kernel :-/)

``` yaml

[dag@moria ansible]$ ./network.py 
{
    "bond0": {
        "active": true, 
        "all_slaves_active": false, 
        "device": "bond0", 
        "ipv4": {
            "address": "1.2.3.4", 
            "netmask": "255.255.255.0", 
            "network": "1.2.3.0"
        }, 
        "ipv6": {
            "address": "fe80:::0123:aabb:ccdd:eeff:17bf", 
            "prefix": "64", 
            "scope": "link"
        }, 
        "lacp_rate": "slow", 
        "macaddress": "aa:bb:cc:dd:ee:ff", 
        "miimon": "0", 
        "mode": "balance-rr", 
        "mtu": 1500, 
        "slaves": [
            "eth0", 
            "pan0"
        ], 
        "type": "bonding"
    }, 
    "br0": {
        "active": false, 
        "device": "br0", 
        "id": "8000.aabbccddeeff", 
        "interfaces": [
            "eth0"
        ], 
        "macaddress": "aa::bb:cc:dd:ee:ff", 
        "mtu": 1500, 
        "stp": false, 
        "type": "bridge"
    }, 
    "eth0": {
        "active": false, 
        "device": "eth0", 
        "macaddress": "aa::bb:cc:dd:ee:ff", 
        "module": "e1000e", 
        "mtu": 1500, 
        "type": "ether"
    }, 
    "eth0:1": {
        "active": false, 
        "device": "eth0", 
        "ipv4": {
            "address": "1.2.3.6", 
            "netmask": "255.255.255.0", 
            "network": "1.2.3.0"
        }, 
        "macaddress": "aa:bb:cc:dd:ee:ff", 
        "module": "e1000e", 
        "mtu": 1500, 
        "type": "ether"
    }, 
    "eth0:2": {
        "active": false, 
        "device": "eth0", 
        "ipv4": {
            "address": "1.2.3.2", 
            "netmask": "255.255.255.0", 
            "network": "1.2.3.0"
        }, 
        "macaddress": "aa:bb:cc:dd:ee:ff", 
        "module": "e1000e", 
        "mtu": 1500, 
        "type": "ether"
    }, 
    "lo": {
        "active": false, 
        "device": "lo", 
        "mtu": 16436, 
        "type": "loopback"
    }, 
    "pan0": {
        "active": true, 
        "device": "pan0", 
        "id": "8000.ddaacceebbff", 
        "interfaces": [], 
        "macaddress": "dd:aa:cc:ee:bb:ff", 
        "mtu": 1500, 
        "stp": false, 
        "type": "bridge"
    }, 
    "ppp0": {
        "active": true, 
        "device": "ppp0", 
        "ipv4": {
            "address": "2.3.4.5", 
            "netmask": "255.255.255.255", 
            "network": "2.3.4.1"
        }, 
        "mtu": 1500, 
        "type": "ppp"
    }, 
    "wlan0": {
        "active": true, 
        "device": "wlan0", 
        "ipv4": {
            "address": "192.168.1.33", 
            "netmask": "255.255.255.0", 
            "network": "192.168.1.0"
        }, 
        "ipv6": {
            "address": "fe80::0123:ffee:ccdd:aabb", 
            "prefix": "64", 
            "scope": "link"
        }, 
        "macaddress": "ff:ee:cc:dd:aa:bb", 
        "module": "iwlwifi", 
        "mtu": 1500, 
        "type": "ether"
    }
}
```
