### ISSUE TITLE
"uri" module with "failed_when" - "status_code" is ignored

### ISSUE THREAD

**Issue by evgeny-goldin** [ansible/ansible#10017]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

Ubuntu 14.04.1 LTS
##### Summary:

If "uri" module is used together with "failed_when" - "status_code" is ignored, i.e., wrong status code returned does not fail the request.
##### Steps To Reproduce:

Save the following playbook as `"1.yaml"`:

```

---
- name:  uri-test
  hosts: localhost
  tasks:
    - uri:
        url: 'http://ya.ru/'
        status_code: 500
      failed_when: false
```

and run it:

`ansible-playbook 1.yaml -c local`
##### Expected Results:

I expect the request to fail since the response code of requesting `"http://ya.ru/"` is 200 and not 500.
##### Actual Results:

Request succeeds. If "failed_when" is commented out - request fails as expected.

**Comment by sivel** [comment]
`failed_when: false` tells ansible to never fail.  So I believe this is doing exactly what it is intended to do.

**Comment by evgeny-goldin** [comment]
This could be a gray area. I'm aware of the purpose of `failed_when` but the fact that it disabled the `status_code` check of `uri` was unexpected. In my case I counted on this check AND `failed_when` condition, expecting either of them to fail the request. If `failed_when` always overwrites `status_code` then it becomes impossible to check requests's response content AND status code to match expected values. Here's my [original code](https://github.com/evgeny-goldin/playbooks/blob/e82a2828a43ed573e617fe45b374aef8aa159e7c/playbooks/utils/service.yml#L49) and it attempts to do exactly that - match URL's content and status code.

**Comment by sivel** [comment]
The status code, is also included in registered variable, so I would recommend just dropping usage of `status_code` and use something like:  `failed_when: uri_resp.status != 500`

**Comment by sivel** [comment]
In your example, I imagine it would look like:

``` yaml
- name: Verifying {{ title }} HTTP endpoint
  uri:
    url:            "http://{{ common.net.localhost }}:{{ port }}{{ item.path | default('')}}"
    return_content: yes
  register: http_verify_out
  with_items:
    - "{{ verify }}"
  failed_when: "'{{ item.content | default('') }}' not in http_verify_out.content and http_verify_out.status != {{ item.status | default( 200 ) }}"
  when:        ( port is defined ) and ( verify is defined )
```
