### ISSUE TITLE
`with_item` flattens lists of lists – which is what only `with_flattened` should do

### ISSUE THREAD

**Issue by htgoebel** [ansible/ansible#10052]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.1
##### Environment:

does not matter
##### Steps To Reproduce:

Run this playbook on any host:

``` yml

---
- hosts: all
  gather_facts: False
  tasks:
  - debug: msg="{{item.0}} -- {{item.1}} -- {{item.2}}"
    with_items:
     - ['General', 'Verbosity', '0']
     - ['Mapping', 'Nobody-User', 'nobody']
     - ['Mapping', 'Nobody-Group', 'nogroup']
```
##### Actual Results:

The output is (shortened):

```
    "msg": "G -- e -- n"
    "msg": "V -- e -- r"
fatal: [dance] => One or more undefined variables: str object has no element 1
```

Please note: The fatal error is just a follow-up error for the main problem.
##### Expected Results:

I would expect the output to be (shortened):

```
    "msg": "General -- Verbosity -- 0"
    "msg": "Mapping -- Nobody-User  -- nobody"
    "msg": "Mapping -- Nobody-Group -- nogroup"
```
##### Reasonable example

I tries using this pattern for setting options in ini-files like this:

```
- name: Configure idmapd
  ini_file: 
    dest: /etc/idmapd.conf
    section: "{{item.0}}"
    option: "{{item.1}}"
    value: "{{item.2}}"
  with_items:
   - ['General', 'Verbosity', '0']
   - ['Mapping', 'Nobody-User', 'nobody']
   - ['Mapping', 'Nobody-Group', 'nogroup']
```

**Comment by abadger** [comment]
It's unintuitive but this is expected behaviour.  It makes walking over several lists possible: https://groups.google.com/forum/#!msg/ansible-project/SaZDYKr5JqY/FbUrwF8hdQ4J

**Comment by hwmrocker** [comment]
:disappointed:

ok, but why are the with_items and with_flattened? what is the diffrenece?

**Comment by bcoca** [comment]
with items does  a single level of flattening, with_flatten goes all the way down the stack.

**Comment by sumkincpp** [comment]
There might be a quick fix for this with additional wrapping of outer list, e.g. :
```yaml
---
- hosts: all
  gather_facts: False
  vars:
    mapping:
     - ['General', 'Verbosity', '0']
     - ['Mapping', 'Nobody-User', 'nobody']
     - ['Mapping', 'Nobody-Group', 'nogroup']      
  tasks:
  - debug: msg="{{item.0}} -- {{item.1}} -- {{item.2}}"
    with_items: "{{ [mapping] }}"
```
