### ISSUE TITLE
Allow non-string/bool arguments to modules

### ISSUE THREAD

**Issue by bkeroackdsc** [ansible/ansible#10056]
**Issue Type**:

Feature request

**Ansible Version**:

1.8.2

**Environment**:

Ubuntu/OSX

**Summary**:

In the following file we see why Ansible will silently ignore non-string/bool arguments passed to modules:

ansible/lib/ansible/utils/**init**.py:

``` python
def serialize_args(args):
    '''
    Flattens a dictionary args to a k=v string
    '''
    module_args = ""
    for (k,v) in args.iteritems():
        if isinstance(v, basestring):
            module_args = "%s=%s %s" % (k, pipes.quote(v), module_args)
        elif isinstance(v, bool):
            module_args = "%s=%s %s" % (k, str(v), module_args)
    return module_args.strip()
```

This makes tasks using custom modules silently fail if they are written to expect, eg, a list:

``` yaml
  tasks:
    - name: "test"
      local_action:
        module: test_module
        environment: production
        host: asdf
        groups:
          - foo
          - bar
        name: testvar
        state: present
```

The `groups` parameter is silently dropped.

I understand that it is awkward to serialize lists into the shlex format that modules accept--one possibility would be to allow multiple instances of the same key: 
`environment=production host=asdf groups=foo groups=bar`.

Regardless, it's kind of a silly reason to cripple modules. Perhaps 2.x could also support JSON parameter transfer?

**Steps To Reproduce**:

Write a module that supports a list or dict parameter.

**Expected Results**:

Data is passed through to module.

**Actual Results**:

Parameter is silently dropped.
