### ISSUE TITLE
Include 'msg' attribute when all retries have failed

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#10099]
##### Issue Type:

Bug Report (it's a regression)
##### Ansible Version:

1.8.2
##### Environment:

NA
##### Summary:

When a task fails after all retries, the result doesn't include the 'msg' attribute, so the only way to figure out why it fails is to pass two(!) -v flags and see the control message for each retry.
##### Steps To Reproduce:

Playbook using ec2_elb:

```
# ELB add fails because instance fails health checks
- hosts: localhost
  tasks:
    - name: Add machine to elb
      local_action:
          module: ec2_elb
          aws_access_key: "{{lookup('env', 'AWS_ACCESS_KEY')}}"
          aws_secret_key: "{{lookup('env', 'AWS_SECRET_KEY')}}"
          region: "eu-west-1"
          instance_id: "i-xxxxxxx"
          ec2_elbs: "test"
          state: present
      register: elb_add
      until: elb_add|success
      retries: 3
      delay: 1
```
##### Expected Results:

Failure result includes the error message:

```
failed: [localhost -> 127.0.0.1] => {"attempts": 3, "failed": true, msg: "The instance i-xxxxxxx could not be put in service on LoadBalancer:test. Reason: Instance has not passed the configured HealthyThreshold number of health checks consecutively."}
```
##### Actual Results:

no error message:

```
failed: [localhost -> 127.0.0.1] => {"attempts": 3, "failed": true}
```

passing -vv:

```
<127.0.0.1> REMOTE_MODULE ec2_elb ec2_elbs=test state=present instance_id=i-xxxxxx region=eu-west-1 aws_access_key='' aws_secret_key=''
<127.0.0.1> REMOTE_MODULE ec2_elb ec2_elbs=test state=present instance_id=i-xxxxxx region=eu-west-1 aws_access_key='' aws_secret_key=''
Result from run 1 is: {'msg': 'The instance i-xxxxxx could not be put in service on LoadBalancer:test. Reason: Instance has not passed the configured HealthyThreshold number of health checks consecutively.', 'failed': True, 'attempts': 1}
<127.0.0.1> REMOTE_MODULE ec2_elb ec2_elbs=test state=present instance_id=i-xxxxxx region=eu-west-1 aws_access_key='' aws_secret_key=''
Result from run 2 is: {'msg': 'The instance i-xxxxxx could not be put in service on LoadBalancer:test. Reason: Instance has not passed the configured HealthyThreshold number of health checks consecutively.', 'failed': True, 'attempts': 2}
<127.0.0.1> REMOTE_MODULE ec2_elb ec2_elbs=test state=present instance_id=i-xxxxxx region=eu-west-1 aws_access_key='' aws_secret_key=''
Result from run 3 is: {'msg': 'The instance i-xxxxxx could not be put in service on LoadBalancer:test. Reason: Instance has not passed the configured HealthyThreshold number of health checks consecutively.', 'failed': True, 'attempts': 3}
```
