### ISSUE TITLE
Filters after default(omit) filter the omit placeholder

### ISSUE THREAD

**Issue by bcomnes** [ansible/ansible#10164]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.2
##### Environment:

OS X 10.10.2 (14C109)
##### Summary:

Filters following the `default(omit)` filter keep filtering.
##### Steps To Reproduce:

Given `user_info` as an array of user objects, some of which had an array of group names that user should be in, and some that lacked a groups key all together.

``` yml
user_info:
  - name: bob
    uid: 123
    gecos: Bob Smith
    groups: 
      - foo
      - bar
 - name: alice
   uid: 321
   gecos: Alice George
```

I had the following task: 

``` yml
- name: ensure user accounts are created
  user: name="{{ item.name }}"
    uid="{{ item.uid }}"
    comment="{{ item.gecos }}"
    groups="{{ item.groups | default(omit) | join(',') }}"
  with_items: user_info
  sudo: yes
```

I would expect this to omit a `groups=` field that lacked an `item.groups` key, and include a `groups=` filed with a csv list of the items in the array `item.groups`.  

Instead, all `item`s have a `groups=` parameter, some which have `groups=` set to

```
_,_,o,m,i,t,_,p,l,a,c,e,_,h,o,l,d,e,r,_,_,9,4,1,d,f,c,7,6,7,a,e,7,0,e,7,4,1,a,3,d,1,2,c,0,9,a,1,c,1,c,1,6,0,0,c,8,2,1,b,1
```

Setting `default()` fixes the issue, but that results in all users having a blank `groups=` field, which is different that omitting them (what I would prefer in this case).

It seems like filters following an `default(omit)` should not be run (or maybe I'm just not seeing why they would be) which is why this seems like a bug.
##### Expected Results:

I would expect filters following a `default(omit)` filter to not be run against the omit placeholder object.
##### Actual Results:

Filters are run against the omit placeholder object:

```
_,_,o,m,i,t,_,p,l,a,c,e,_,h,o,l,d,e,r,_,_,9,4,1,d,f,c,7,6,7,a,e,7,0,e,7,4,1,a,3,d,1,2,c,0,9,a,1,c,1,c,1,6,0,0,c,8,2,1,b,1
```
