### ISSUE TITLE
apt-key module re-fetches key every time

### ISSUE THREAD

**Issue by tetherit** [ansible/ansible#10160]
Hi there,

I have this task in my playbook:

``` yaml
  - name: "Add RabbitMQ Apt Key"
    apt_key:
      url: 'http://www.rabbitmq.com/rabbitmq-signing-key-public.asc'
      state: present
```

Because I have "state: present", I expect the key to only be fetched once and not to be fetched again every time I run ansible. However:

```
$ time vagrant provision
vagrant provision  1.57s user 0.38s system 21% cpu 9.284 total
```

If I remove the apt-key line from my playbook:

```
$ time vagrant provision
vagrant provision  1.56s user 0.35s system 88% cpu 2.156 total
```

So an extra 7 seconds are added to my ansible runtime trying to re-fetch a key that already exists. Any ideas how to prevent this from happening?
