### ISSUE TITLE
Avoid running pre/post tasks on plays with no roles/tasks

### ISSUE THREAD

**Issue by hkariti** [ansible/ansible#10186]
##### Issue Type:

Feature Idea
##### Ansible Version:

1.8.2
##### Environment:

NA
##### Summary:

If a play won't run any tasks (for exaple because none were selected by --tags), its pre and post tasks shouldn't run. The current behavior can cause problems when using tags to deploy a single application out of several from a larger playbook.
##### Steps To Reproduce:
- A large playbooks describing several clusters of applications with pre/post tasks for load balancers, cleanup, etc:

```
- hosts: tag_role_hostgroup1
  serial: 1
  pre_tasks:
    - name: Remove from lb
       ...
       tags: pre_tasks
  roles:
     - { role: app1, tags: app1 }
     - { role: app2, tags: app2 }
  post_tasks:
    - name: Register to lb
      ...
      tags: post_tasks

- hosts: tag_role_hostgroup2
  serial: 1
  pre_tasks:
    - name: Some preps
       ...
       tags: pre_tasks
  roles:
     - { role: app2, tags: app2 }
     - { role: app3, tags: app3 }
  post_tasks:
    - name: Cleanup
      ...
      tags: post_tasks
```
- Deploying one app using tags:

```
ansible-playbook deploy.yml --tags app3
```
##### Expected Results:

The first playbook's pre/post tasks shouldn't be run, because --tags deselected all of its tasks. 
##### Actual Results:

The current way of using `--tags app3,pre_tasks,post_tasks` causes machines to be removed from the lb and immediately re-added, without any work done on them.
