### ISSUE TITLE
Jinja2 template is failing to render CONTINUE statement

### ISSUE THREAD

**Issue by htgoebel** [ansible/ansible#10187]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.1
##### Environment:

N/A
##### Summary:

jinja2 templates in ansible do not support `continue` in loops.
##### Steps To Reproduce:

Save this template as template-with-continue.j2

```
{%- for elem in my_items %}
-- {{elem}} --
{% continue %}
should not come here
{% endfor %}
```

Then run this playbook:

```

---
- hosts: all
  gather_facts: False
  vars:
    my_items: [ 'item 1', 'item 2', 'item 3' ]
  tasks:
  - template:
      src: template-with-continue.j2
      dest: /tmp/template-with-continue.txt
```
##### Expected Results:

I would expect the playbook to run without errors.
##### Actual Results:

Ansible errors out with (relevant part high-lighted):
  fatal: [test] => {'msg': "AnsibleError: file: template-with-continue.j2, line number: 3, error: **Encountered unknown tag 'continue'.** Jinja was looking for the following tags: 'endfor' or 'else'. The innermost block that needs to be closed is 'for'.", 'failed': True}
##### Possible solution

According to http://stackoverflow.com/questions/16599338/jinja2-template-from-flask-is-failing-to-render-continue-statement you need to add the loop controls extension for Jinja 2 to your app:
`app.jinja_env.add_extension('jinja2.ext.loopcontrols')`
