### ISSUE TITLE
unsupported parameter error when using resource_tags to tag a VPC resource

### ISSUE THREAD

**Issue by rahulmehrotra1** [ansible/ansible#10191]
Getting an error when trying to use resource_tags in ec2_vpc module

```
tasks:
  - name: create vpc
    local_action:
      module: ec2_vpc
      region: "{{ region }}"
      cidr_block: 10.0.0.0/16
      resource_tags: '{ "Name" : "development_vpc"}'
```

The error received is 

> TASK: [Create a VPC in  {{ region }}] ****************************************\* 
> failed: [localhost -> 127.0.0.1] => {"failed": true}
> msg: unsupported parameter for module: resource_tags
> 
> FATAL: all hosts have already failed -- aborting

Also ec2_vpc module is not able to tag the subnets created.

For example running the below code:

```
 - name: Create a VPC in  {{ region }}
      local_action:
         module:  ec2_vpc
         region: "{{ region }}"
         cidr_block: 10.0.0.0/16
         subnets:
          - cidr: 10.0.0.0/24
            az: us-east-1a
            resource_tags: '{  "Environment": "Development", "Name" : "Public Subnet" }'
         - cidr: 10.0.1.0/24
           az: us-east-1b
           resource_tags: '{  "Environment": "Development", "Name" : "Public Subnet" }'
         - cidr: 10.0.2.0/24
           az: us-east-1d
           resource_tags: '{  "Environment": "Development", "Name" : "Public Subnet" }'
```

Executes correctly but the tags are not getting created. 

The above error can be reproduced by executing the code above.
