### ISSUE TITLE
set_fact 'complex argument style' syntax

### ISSUE THREAD

**Issue by dhutty** [ansible/ansible#10206]
- Issue Type: "Bug Report"
- Ansible Version: ansible 1.8.2
- Environment:
  - Host: OSX 10.9
  - Remotes: Ubuntu 12.04, CentOS-7.0
## Summary

The oneliner form of set_fact syntax works using a regexp_replace filter, but the 'complex argument style' referred to in the set_fact docs does not.
## Steps to reproduce

``` yaml
- set_fact: foo="{{ 'foobar' | regex_replace('^f.*o(.*)$', '\\1') }}" bar="{{ 'foobar' | regex_replace('^(f.*o)(.*)$', '\\1') }}"

- set_fact:
    foofail: "{{ 'foobar' | regex_replace('^(f.*o)(.*)$', '\\1') }}"
    barfail: "{{ 'foobar' | regex_replace('^(f.*o)(.*)$', '\\2') }}"
```
## Actual Result

``` shell
       TASK: [common | set_fact foo="foo" bar="bar"] *********************************
       ok: [localhost] => {"ansible_facts": {"bar": "bar", "foo": "foo"}}

       TASK: [common | set_fact ] ****************************************************
       ok: [localhost] => {"ansible_facts": {"barfail": "\u0001", "foofail": "\u0001"}}
```

The expected result should have the variables foofail and barfail containing 'foo' and 'bar' respectively, as in the previous example using singleline syntax.

**Comment by abadger** [comment]
This is due to a difference in quoting and escaping rules between the two types of args.  This should work for you:

```
    - set_fact: foo="{{ 'foobar' | regex_replace('^f.*o(.*)$', '\\1') }}" bar="{{ 'foobar' | regex_replace('^(f.*    o)(.*)$', '\\1') }}"

    - set_fact:
        foofail: "{{ 'foobar' | regex_replace('^f.*o(.*)$', '\\\\1') }}"
        barfail: "{{ 'foobar' | regex_replace('^(f.*o)(.*)$', '\\\\1') }}"
```

I'm going to ask someone here if this is expected behaviour but I have feeling that it has been like this for long enough that even if it's not desired behaviour it is expected

**Comment by abadger** [comment]
Okay, I have another work around for you:
http://pyyaml.org/wiki/PyYAMLDocumentation#Scalars

```
- hosts: localhost
  tasks:
    - set_fact: foo='{{ "foobar" | regex_replace("^f.*o(.*)$", "\\1") }}' bar='{{ "foobar" | regex_replace("^(f.*    o)(.*)$", "\\1") }}'

    - set_fact:
        foofail: '{{ "foobar" | regex_replace("^f.*o(.*)$", "\\1") }}'
        barfail: '{{ "foobar" | regex_replace("^(f.*o)(.*)$", "\\1") }}'

[...]
TASK: [set_fact foo='bar' bar='foo'] ****************************************** 
ok: [localhost] => {"ansible_facts": {"bar": "foo", "foo": "bar"}}

TASK: [set_fact ] ************************************************************* 
ok: [localhost] => {"ansible_facts": {"barfail": "foo", "foofail": "bar"}}
```

Using single quotes at the outermost yaml level leads to the same values being passed to python because yaml only processes a minimal amount of special characters in the single quoted strings.  This is confusing but it is the yaml standard so I don't think there's a bug here per-se, just some non-obvious rules that have to be followed to make yaml happy.
