### ISSUE TITLE
Ansible not pulling images from private Docker repository

### ISSUE THREAD

**Issue by soupdiver** [ansible/ansible#10209]
I've problems with Ansible automatically pulling docker images from my private repository.
I do login first via:

``` yaml
- name: login to registry
  shell: "docker login -e {{ registry_mail }} -p {{ registry_pass }} -u {{ registry_user }} {{ registry_host }}"
```

and then I tried the following instructions:

``` yaml
- name: start foo container
  docker:
    image: registry.foo:8888/app
    name: foo-app
    env: "DB_NAME=foo,APP_HOST=foo.foo,NODE_ENV=docker"
    ports: 127.0.0.1:1337:1337
    state: running

- name: start foo container
  docker:
    image: app
    registry: registry.foo:8888
    name: foo-app
    env: "DB_NAME=foo,APP_HOST=foo.foo,NODE_ENV=docker"
    ports: 127.0.0.1:1337:1337
    state: running

- name: start foo container
  docker:
    image: app
    registry: registry.foo:8888
    username: "{{ registry_user }}"
    password: "{{ registry_pass }}"
    name: foo-app
    env: "DB_NAME=foo,APP_HOST=foo.foo,NODE_ENV=docker"
    ports: 127.0.0.1:1337:1337
    state: running
```

everyone gave me an error: `msg: Docker API error: No such image`

Doing manually `docker run registry.foo:8888/app` did pull and start the image.

I had to manually insert

``` yaml
- name: pull foo container manually
  shell: docker pull registry.foo.com:8888/app
```

Any ideas?
