### ISSUE TITLE
Regression in backrefs matching for lineinfile after 1.7.1

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10240]
I found a regression in lineinfile when backrefs are used. See the following example:

``` yaml

---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: broken test
    lineinfile: dest=/tmp/lineinfile_backref.txt
                backrefs=yes regexp="(^[ ]+'values'.*)\),"
                line="\1 'vn'),"
```

The sample file (/tmp/lineinfile_backref.txt) is:

```
    'values': ('v1', 'v2', 'v3',),

```

The same example used to work until ansible 1.7.1. It does not work with 1.7.2 and 1.8.x.
