### ISSUE TITLE
 Ansible shell module silently "succeeds" with empty command

### ISSUE THREAD

**Issue by bkeroackdsc** [ansible/ansible#10271]
Issue Type:

Bug Report
Ansible Version: 1.8.2

Environment:

CentOS 7 64bit

Summary:

When running playbooks against a CentOS 7 (or RHEL 7) host, tasks using the shell module appear to succeed but do not actually appear to run the specified command. The task returns exit code 0, empty stderr/stdout, and status 'changed' but without actually running the command specified.

Steps To Reproduce:

Create an obviously bad/incorrect task using the shell module:

``` yaml
- name: Test shell command
  shell:
    name: 'invalid_command_does_not_exist --foobar'
  register: test_shell_command
  sudo: yes
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- debug
   msg: "test command: {{ test_shell_command }}"
```

Execute the playbook. Note that "Test shell command" succeeds (marked Changed) and the register output of the command shows empty stderr/stdout and exit code of 0.

Expected Result:

Command executes.

Actual Result:

Command does not execute.

**Comment by bcoca** [comment]
i think you are confusing the parser, which things name: is an extra paramter, which it does not use, shell goes and executes a /bin/sh shell and exits, so it returns ok.

```
shell: /bin/false
    name: 'invalid_command_does_not_exist --foobar'
```

should give you an error

**Comment by bkeroackdsc** [comment]
@bcoca You are correct.

Changing syntax to the following form fixed the issue:

``` yaml
- name: foo
  shell: /bin/true && touch /root/.foo
  args:
     creates: /root/.foo
  sudo: yes
```
