### ISSUE TITLE
Yum module and with_items

### ISSUE THREAD

**Issue by linuskendall** [ansible/ansible#10276]
_Issue Type:_

Bug Report

_Ansible Version:_

Tested on both latest Git version as well as Ansible 1.8.3

_Environment:_

Deploying from Mac OS X (Python 2.7.6)
Deploying to CentOS 6.5 (Python 2.6.6)

_Summary:_

When using the yum module with with_items in the latest version, state="present" seems to be included as part of the package name list. 

_Steps To Reproduce:_

Run the following task

``` yaml
- name: ensure postfix is installed
  yum: name={{ item }} state=present
  with_items:
    - postfix
    - cyrus-sasl
    - cyrus-sasl-lib
    - cyrus-sasl-plain
  when: ansible_os_family == "RedHat"
```

Have tested surrounding {{ item }} with single and double quotes.  The only work around which I've found to work is using the alternative syntax:

``` yaml
   yum: 
     name: "{{ item }}"
     state: present
```

_Expected Results:_

The four packages should be installed without the need for using alternate syntax. 

_Actual Results:_

```
failed: [107.170.116.184] => (item=postfix,cyrus-sasl,cyrus-sasl-lib,cyrus-sasl-plain) => {"changed": false, "failed": true, "item": "postfix,cyrus-sasl,cyrus-sasl-lib,cyrus-sasl-plain", "rc": 0, "results": ["postfix-2.6.6-6.el6_5.x86_64 providing postfix is already installed", "cyrus-sasl-2.1.23-15.el6_6.1.x86_64 providing cyrus-sasl is already installed", "cyrus-sasl-lib-2.1.23-15.el6_6.1.x86_64 providing cyrus-sasl-lib is already installed"]}
msg: No Package matching 'cyrus-sasl-plain state=present' found available, installed or updated
```
