### ISSUE TITLE
file-test doesn't run via su

### ISSUE THREAD

**Issue by Lem** [ansible/ansible#10308]
**Issue Type:**
Bug Report

**Ansible Version:**
ansible 1.8.4

**Environment:**
Local: Gentoo
Remote: Debian 7.8

**Summary:**
I'm running a playbook with --ask-su-pass and -S. 
After copying a file with 

```
template: src=foo dest=/etc/postfix/foo mode=600
```

my ssh_user can't read the created file (as expected).

Running the playbook again will fail because ansible is running some tests to check the given file. Testing if the file is readable will fail because my ssh-user can't read a 0600-file of root.
With -vvv it looks like these tests aren't excuted with su.

Example output:

```
<IP> ConnectTimeout=10 PasswordAuthentication=no KbdInteractiveAuthentication=no User=abc 'rc=flag; [ -r '"'"'/etc/postfix/foo'"'"' ] || rc=2; [ -f '"'"'/etc/postfix/foo'"'"' ] || rc=1; [ -d '"'"'/etc/postfix/foo'"'"' ] && rc=3; [...]
```

I think this tests (defined in lib/ansible/runner/shell_plugins/sh.py in function checksum) should also run with su if -S is given.

**Comment by rootrider** [comment]
I believe I'm seeing the same issue. Ansible 1.8.4 on FreeBSD, using su with ansible-playbook --ask-su-pass .

My playbook runs with this:
    remote_user: joel
    su: yes
    su_user: root

For the template I'm trying to copy over, the destination has 600 permissions and is owned by root. When I do everything manually that Ansible is trying to do, I have no problem. It does look like the hash is running without using su though.

This is an excerpt of what I get with -vvv:
afile = open("/usr/local/etc/apache24/sites-available/_default.conf", "rb")
buf = afile.read(BLOCKSIZE)
while len(buf) > 0:
hasher.update(buf)
buf = afile.read(BLOCKSIZE)
afile.close()
print(hasher.hexdigest())'"'"' 2>/dev/null) || (echo '"'"'0  /usr/local/etc/apache24/sites-available/_default.conf'"'"')' ControlPath=/usr/home/joel/.ansible/cp/ansible-ssh-%h-%p-%r PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey ControlMaster=auto Port=2200 ControlPersist=60s
failed: [nimbostratus] => {"failed": true}
msg: failed to checksum remote file. Checksum error code: 2

If I set permissions to 660 (user 'joel' is in the group that has access to this file), or if I change file ownership to 'joel' then suddenly Ansible works correctly.

This is perfectly reproducible for me.

**Comment by abadger** [comment]
Could you test this with the stable-1.9 branch and/or the devel branch?  It looks like su has never been used with the computation of the checksum in the past (a bug but one that was never noticed).  The sudo/su mechanism has been changed for 1.9 and in our testing here it seems to work.  It would be good to verify that it's working for you in what will become the next release (and if it fails there but works in devel, we'll need to figure out what commits we need to pull over that fixed that.)

**Comment by rootrider** [comment]
I just cloned from github (devel branch) and tried with that. The result was this (I tried several times just to make sure I wasn't getting the password wrong):

[joel@nimbostratus ~/git/ansible]$ ~/git/ansible/bin/ansible-playbook -i ~/ansible/inventory/fakelag/hosts.servers ~/ansible/setup/fakelag.yml -t poudriere-config --ask-su-pass
SU password: 

PLAY [factgathering] *********************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [nimbostratus]

PLAY [poudriere] *************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [nimbostratus]

TASK: [poudriere | update pkg repo / poudriere web server config] ************\* 
fatal: [nimbostratus] => ssh connection closed waiting for a privilege escalation password prompt

FATAL: all hosts have already failed -- aborting

the only task in this play is to copy the template in question over, so that's where it fails above.

**Comment by bcoca** [comment]
so I'm using the following for testing and cannot reproduce the issue you are having:

```
---
- name: Prepare the test
  hosts: localhost
  gather_facts: False
  vars:
    temp: '/tmp/become-test'
  tasks:
    - file: path={{ temp }} state=directory
      changed_when: False

    - file: path={{ temp + "/" + item }} state=touch
      with_items: [ 'file1', 'file2', 'file3' ]
      changed_when: False

    - command: tar czf /tmp/test.tar.gz {{ temp }}
      changed_when: False

- name: Do the passing test
  hosts: nyx
  gather_facts: False
  su: False
  vars:
    temp: '/tmp/become-test'
  tasks:
    - copy: src={{ temp }}/ dest=/tmp/delta/

    - file: path=/tmp/alfa state=directory

    - unarchive: src=/tmp/test.tar.gz dest=/tmp/alfa

    - command: whoami
      su: yes

    - template: src={{temp}}/file2 dest=/tmp/foo1 mode=0600 owner=root
      su: yes

- name: Do the failing test
  hosts: nyx
  gather_facts: False
  su: True
  vars:
    temp: '/tmp/become-test'
  tasks:
    - copy: src={{ temp }}/ dest=/tmp/gamma/

    - file: path=/tmp/beta state=directory

    - template: src={{temp}}/file1 dest=/tmp/beta/file1.template mode=0600
```

**Comment by rootrider** [comment]
here is what I'm running..
Note that I'm on FreeBSD 10.1, using python 2.7

relevant inventory bits:

```
[poudriere]
nimbostratus
```

host_vars/nimbostratus:

```
 ansible_ssh_host: nnn.nnn.nnn.nnn
 ansible_ssh_port: 2200
 ansible_ssh_user: joel
```

playbook:

```
  - hosts: poudriere
    remote_user: joel
    su: yes
    su_user: root
    vars:
      - ansible_python_interpreter: /usr/local/bin/python2
    roles:
      - poudriere
```

role/poudriere/tasks/main.yml:

```
  - name: update pkg repo / poudriere web server config
    template:
      src="../../base/templates/apache24/sites-available/nimbostratus._default.conf.j2"
      dest=/usr/local/etc/apache24/sites-available/_default.conf
    when: apache_version == "apache24"
    tags: poudriere-config
```

the command I'm running is seen above.

the file on the target server is as so:

```
[root@nimbostratus ~]# stat /usr/local/etc/apache24/sites-available/_default.conf 
80 1445314 -rw------- 1 root wheel 2970874 1302 "Mar 17 12:07:34 2015" "Mar 16 14:40:29 2015" "Mar 17 11:57:14 2015" "Mar 16 14:40:29 2015" 32768 8 0 /usr/local/etc/apache24/sites-available/_default.conf
```

so, it's super simple. I'm not doing anything else in the poudriere role yet.
