### ISSUE TITLE
template task fails when dest is a directory

### ISSUE THREAD

**Issue by nickswebsite** [ansible/ansible#10300]
The following playbook will fail:

```
- hosts: all
  sudo: yes
  tasks:
  - template: src=file.txt dest=/opt
```

The error code will be:

```
msg: failed to checksum remote file. Checksum error code: 3
```

/opt/file.txt does not exist after running the playbook.

This worked in ansible 1.8.2, so the issue was probably introduced within the last couple of days.

The 'copy' module doesn't have this problem.

**Comment by bcoca** [comment]
confirmed the issue, a quick workaround is adding a trailing slash to the directory, this works:

```
- hosts: all
  sudo: yes
  tasks:
      - template: src=file.txt dest=/opt/
```
