### ISSUE TITLE
ADD vsphere_guest clone/create in set folder (or create folder if not exists)

### ISSUE THREAD

**Issue by VAdamec** [ansible/ansible#10326]
Solutions already exist look at Seba response in pysphere mail group: https://groups.google.com/d/msg/pysphere/ELtCaFNLScw/abnK87z1hoUJ

**Comment by andreobrown** [comment]
It's not clear what parameter is required in the vsphere_guest task should be used to specify the folder.

**Comment by bcoca** [comment]
you should already be able to do so via:

```
        vm_extra_config:
            folder:  myfolder
```

**Comment by andreobrown** [comment]
I've tried that with the following:

```
vm_extra_config:
            folder: MyDatacenter/beta

vm_extra_config:
            folder: MyDatacenter/vm/beta

vm_extra_config:
            folder: beta
```

None of those worked.

**Comment by bcoca** [comment]
what versions are you using? I can successfully clone from template to a specific folder using current devel, but I believe this was added in 1.8

**Comment by andreobrown** [comment]
I'm using version:

ansible 1.9 (devel ffb281d96c) last updated 2015/03/04 01:13:13 (GMT -500)

Here is my play:

```
- hosts: vsphere
  gather_facts: false

  vars:
    my_env: beta
    vcenter_hostname: 10.0.0.1
    vcenter_username: "myusername"
    vcenter_password: "mypassword"

  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        guest: "test_{{ my_env }}"
        from_template: yes
        template_src: "my_Template"
        resource_pool: /Resources
        cluster: My-HA-DRS
        vm_nic:
          nic1:
            type: vmxnet3
            network: My-OAM
            network_type: dvs
          nic2:
            type: vmxnet3
            network: My-Production
            network_type: dvs
          nic3:
            type: vmxnet3
            network: My-Backup
            network_type: dvs
        vm_extra_config:
            folder: beta
            notes: "Test notes"
        esxi:
            datacenter: MyDC
```

I noticed that the notes do not get created either. I added it to test if vm_extra_config was being applied at all. Is there an error in my config, or should I move this to a bug report?
