### ISSUE TITLE
with_file gets evaluated even when the entire taks is skipped

### ISSUE THREAD

**Issue by sumdog** [ansible/ansible#10337]
Ansible version: ansible 1.8.4
OS: Gentoo and Ubuntu 14.04

First, kudos to Tybstar on #ansible on irc/freenode for finding a workaround. So say I have a role with the following task:

```

---
- include_vars: ../../vsense.yml
- debug: var=security
- debug: var=security.ssh_key_file
- include: enable-ssh.yml
  when: security.ssh_key_file is defined
- include: enable-password.yml
  when: security.pgp_id is defined
```

and here is the vsense.yml

```

---
environments:
- name: build
  type: build
- name: core
  type: infrastructure
- name: ubuntu-nightly-postgres
  type: run
- name: centos-nightly-mysql
  type: run
security:
  pgp_id: 6D0D93B1
boxes:
  ubuntu: ubuntu/trusty64
  debian: zauberpony/wheezy
  centos: hansode/centos-7.0.1406-x86_64
  opensuse: alchemy/opensuse-13.2-64
```

and then this happens:

```
vagrant provision repo
==> repo: Running provisioner: ansible...

PLAY [BigSense Repository Server] ********************************************* 

GATHERING FACTS *************************************************************** 
ok: [repo]

TASK: [security | include_vars ../../vsense.yml] ****************************** 
ok: [repo]

TASK: [security | debug var=security] ***************************************** 
ok: [repo] => {
    "security": {
        "pgp_id": "6D0D93B1"
    }
}

TASK: [security | debug var=security.ssh_key_file] **************************** 
ok: [repo] => {
    "security.ssh_key_file": "{{ security.ssh_key_file }}"
}

TASK: [security | authorized_key user=vagrant key="{{item}}"] ***************** 
fatal: [repo] => /home/sumit/sensespace/vSense/virtual-env/build/ansible/roles/security/files/{{security.ssh_key_file}}.pub does not exist

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/sumit/repo.retry

repo                       : ok=4    changed=0    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

and the reason is that my enable-ssh.yml looks like this

```
- authorized_key: user=vagrant key="{{ item }}"
with_file:
- "{{ security.ssh_key_file }}.pub"
- authorized_key: user=vagrant key="{{ item }}" state=absent
with_file:
- vagrant-insecure.pub
```

The with_file gets evaluated, even though the entire task is marked as skipped! Per Tybstar, after changing it to the following, it works:

```
- authorized_key: user=vagrant key="{{ lookup('file', item) }}"
  with_first_found:
    - "{{ security.ssh_key_file }}.pub"
- authorized_key: user=vagrant key="{{ item }}" state=absent
  with_file:
    - vagrant-insecure.pub
```

So with_first_found doesn't try to eval the lookup, but with_file does.

I'm not entirely sure if this is a bug or the result of with_file's evaluation needed for certain types of conditionals. But I figured I should mark it as an issue just in case anyone else runs into this oddity.
