### ISSUE TITLE
do-until loops fail to evaluate stdout_lines

### ISSUE THREAD

**Issue by dak1n1** [ansible/ansible#10334]
**Issue type:**
Bug report

**Ansible version:**
1.9 (latest development branch)

**Environment:**
Fedora 21

**Summary:**
`until` statements fail to evaluate `stdout_lines|length`. However,`stdout.split()|length` evaluates as expected, and can be used as a workaround.

**Steps to reproduce:**
Run a playbook comparing stdout_lines in an until loop, like the one below.

``` yaml
  tasks: 
    - name: Get some multi-line output
      command: echo -e "line1\nline2"
      register: output

    # view the length of the lines. There are 2, as expected.
    - name: Number of lines
      debug: var=output.stdout_lines|length

    # test evaluating length. It works outside of the until loop.
    - debug: msg="{{ output.stdout_lines|length < 2 }}"

    - name: Evaluate output length in 'until' loop
      command: echo -e "line1\nline2"
      register: output
      # this does not work:
      until: output.stdout_lines|length < 2
      # this works:
      #until: output.stdout.split()|length < 2
      retries: 10
      delay: 60
      ignore_errors: true
```

**Comment by dak1n1** [comment]
Here is the output of the playbook run, in case that helps:

``` yaml
TASK: [Get some multi-line output] ******************************************** 
<ansible-dakinitest.rhcloud.com> 
changed: [ansible-dakinitest.rhcloud.com] => {"changed": true, "cmd": ["echo", "-e", "line1\\nline2"], "delta": "0:00:00.035116", "end": "2015-02-24 14:16:17.808035", "rc": 0, "start": "2015-02-24 14:16:17.772919", "stderr": "", "stdout": "line1\nline2", "warnings": []}

TASK: [Number of lines] ******************************************************* 
ok: [ansible-dakinitest.rhcloud.com] => {
    "var": {
        "output.stdout_lines|length": "2"
    }
}

TASK: [debug msg="{{ output.stdout_lines|length < 2 }}"] ********************** 
ok: [ansible-dakinitest.rhcloud.com] => {
    "msg": "False"
}

TASK: [Evaluate output length in 'until' loop] ******************************** 
<ansible-dakinitest.rhcloud.com> 
fatal: [ansible-dakinitest.rhcloud.com] => error while evaluating conditional: output.stdout_lines|length < 2

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/dakini/test_until.retry

ansible-dakinitest.rhcloud.com : ok=3    changed=1    unreachable=1    failed=0   
```
