### ISSUE TITLE
no_log: true is not applying to skipped items

### ISSUE THREAD

**Issue by ciphernaut** [ansible/ansible#10387]
Issue Type: Bug Report
Ansible Version: ansible 1.8.4
  configured module search path = None

Environment: Fedora release 20 (Heisenbug) Linux <redacted> 3.18.7-100.fc20.x86_64 #1 SMP Wed Feb 11 19:01:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Summary: items marked for no_log do not seem to apply on iterative tasks when it is skipped to to a conditional check.  This allows credentials and other sensitive information to be exposed.

Steps To Reproduce:

```

---
- hosts: localhost
  vars:
    access_list:
      - { hostname: alpha, password: foo, managed: no }
      - { hostname: beta, password: bar, managed: yes }

  tasks:
    - name: create tmp file
      file: path=/tmp/somefile state=touch
      always_run: true

    - name: add credentials to file
      lineinfile: dest=/tmp/somefile line="#Password for host {{ item.hostname }} is {{ item.password }}"
      with_items: access_list
      when: not item.managed
      no_log: True
```

Actual Results:
ansible-playbook -vv playbooks/poc.yml

```
TASK: [add credentials to file] *********************************************** 
<localhost> dest=/tmp/somefile NO_LOG=True line=#Password for host alpha is foo
changed: [localhost] => {"censored": "results hidden due to no_log parameter", "changed": true}
skipping: [localhost] => (item={'password': 'bar', 'managed': True, 'hostname': 'beta'})
```

Expected Results:
ansible-playbook -vv playbooks/poc.yml

```
TASK: [add credentials to file] *********************************************** 
<localhost> dest=/tmp/somefile NO_LOG=True line="censored"
changed: [localhost] => {"censored": "results hidden due to no_log parameter", "changed": true}
skipping: [localhost] => ("censored": "results hidden due to no_log parameter")
```
