### ISSUE TITLE
can't get git clone to work

### ISSUE THREAD

**Issue by d3netxer** [ansible/ansible#10393]
My git clone task seems to run fine:

```
    virtualbox-iso: TASK: [clone repo] ************************************************************
    virtualbox-iso: changed: [127.0.0.1]
```

but after my ubuntu virtual machine get's built and I log in, I can never find the repo anywhere. here is my playbook:

```
hosts: all
  vars_files:
    - vars.yml
  sudo: yes
  tasks:
  - name: Install required system packages.
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items: 
    - "{{ system_packages }}"
  - name: clone repo
    git: clone=yes repo=https://github.com/joto/osmium/ dest=/home/vagrant/osmium
```
