### ISSUE TITLE
to_json fails on inventory

### ISSUE THREAD

**Issue by dch** [ansible/ansible#10394]
``` yaml
# inventory all the things

---
- name: run inventory
  setup:

- name: fails with error
  local_action: debug msg="{{ hostvars[inventory_hostname] | to_json}}"
```

`A variable inserted a new parameter into the module args. Be sure to quote variables if they contain equal signs (for example: "{{var}}").`

there are a large number of other to_json issues noted, but AFAICT this is unique.

NB I'm away until mid April so no response.
