### ISSUE TITLE
'when' statement should be evaluated before anything else to avoid errors in other statements

### ISSUE THREAD

**Issue by maxalbert** [ansible/ansible#10400]
**Issue Type:** Bug Report

**Ansible Version:** 1.8.4

**Environment:** N/A

**Summary:**

The `when` statement should be evaluated before anything else and the task be skipped immediately if it evaluates to False. Otherwise it may cause failures in other statements (e.g. `with_sequence` in the example below).

**Steps To Reproduce:**

Here is a minimal playbook `bug.yml` to illustrate the issue:

``` yaml

---
- hosts: all
  gather_facts: False
  tasks:
    - name: "This task should be skipped but it fails instead."
      command: echo "Hello world"
      when: False
      with_sequence: start=2 end=1
```

It can be run with:

`ansible-playbook -c local -i localhost, bug.yml`

**Expected Results:**

The task should be skipped because the `when` statement evaluates to False. The expected output is:

```
TASK: [This task should be skipped but it fails instead.] *** 
skipping: [localhost]
```

**Actual Results:**

The task fails because the start value in the `with_sequence` statement is larger than the end value.

```
TASK: [This task should be skipped but it fails instead.] *** 
fatal: [localhost] => can't count backwards

FATAL: all hosts have already failed -- aborting
```
