### ISSUE TITLE
'with_sequence' should not fail with 'count=0'

### ISSUE THREAD

**Issue by maxalbert** [ansible/ansible#10401]
**Issue Type:** Bug Report

**Ansible Version:** 1.8.4

**Environment:** N/A

**Summary:**

The `with_sequence` statement should not fail when used with `count=0`. Instead, it should just skip the task.

**Steps To Reproduce:**

Here is a minimal playbook `bug.yml` to illustrate the issue:

``` yaml

---
- hosts: all
  gather_facts: False
  tasks:
    - name: "This task should be skipped because count=0 in the 'with_sequence' statement"
      command: echo "Hello world"
      with_sequence: count=0
```

It can be run with:

`ansible-playbook -c local -i localhost, bug.yml`

**Expected Results:**

The task should be skipped because `count=0`.

**Actual Results:**

The task fails with the error message "can't count backwards" (which is counterintuitive because `count` is zero, not negative).

```
TASK: [command echo "Hello world"] ******************************************** 
fatal: [localhost] => can't count backwards

FATAL: all hosts have already failed -- aborting
```
