### ISSUE TITLE
New keyword for 'with_sequence' in order to skip task if count < 0 or start > end

### ISSUE THREAD

**Issue by maxalbert** [ansible/ansible#10403]
**Issue Type:** Feature request

**Ansible Version:** 1.8.4

**Environment:** N/A

**Summary:**

When using `with_sequence` "programmatically" (i.e., in combination with variables), it would be useful to allow a negative value for the `count` argument, or a `start` value that is larger than `end`. Currently this results in an error ("can't count backwards"), but it could be useful to simply skip the task if the range is empty. This could be achieved by adding an extra keyword, e.g. `skip_with_emtpy_range` (although it should probably be less verbose), which would be `False` by default for backwards compatibility.

Example:

``` yaml

---
- hosts: all
  gather_facts: False
  vars:
    - M: 2
    - N: 1
  tasks:
    - name: This taks should be skipped because 'skip_with_empty_range' is True.
      command: echo "Hello world"
      with_sequence: start={{ M }} end={{ N }} skip_with_empty_range=True
      #with_sequence: count={{ M - N }} skip_with_empty_range=True
```

**Expected Results:**

The task should be skipped because `skip_with_empty_range` is `True`:

```
TASK: [This taks should be skipped because 'skip_with_empty_range' is True.] *** 
skipping: [localhost]
```

**Actual Results:**

Currently the task fails with the error message "can't count backwards" (of course, `skip_with_emtpy_range` needs to be omitted when running the example above because it is not supported yet).

```
TASK: [This taks should be skipped because 'skip_with_empty_range' is True.] *** 
fatal: [localhost] => can't count backwards

FATAL: all hosts have already failed -- aborting
```
