### ISSUE TITLE
Ansible OSX get_service_tools not implemented on target platform

### ISSUE THREAD

**Issue by jeroenseegers** [ansible/ansible#10412]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.8.2
    configured module search path = None
```
##### Environment:

Target: OSX 10.10.2
Host: OSX 10.10.2
##### Summary:

When running a service task or handler such as the following

```

---
# file: site.yml
- host: localhost
  remote_user: jeroenseegers
  tasks:
    - name: Install nginx
      homebrew: name=nginx state=latest
      notify:
        - Start nginx

  handlers:
    - name: Start nginx
      sudo: yes
      service: name=nginx state=started
```

Ansible will report back with an error, saying that it couldn't find an implementation of `get_service_tools`:

```
failed: [localhost] => {"failed": true}
msg: get_service_tools not implemented on target platform

FATAL: all hosts have already failed -- aborting
```
##### Steps To Reproduce:

See Summary.
##### Expected Results:

I would expect Ansible to ensure the specified service is running.
##### Actual Results:

Ansible reports an error saying `get_service_tools` is not implemented on the target platform.
