### ISSUE TITLE
Allow include statements to set vars when including plays

### ISSUE THREAD

**Issue by mildred** [ansible/ansible#10419]
##### Issue Type:

Feature Idea
##### Ansible Version:

ansible 1.8.4
  configured module search path = None
##### Environment:

N/A
##### Summary:

Allow include statements to include full playbooks, not just tasks files
##### Steps To Reproduce:

The include statement is limited because it doesn't allow, on the included file side, to define default values for the variables. It would be great to have an include statement that could process default variables. For example:

```
- include: included.yml
  vars:
    name: test
```

with `included.yml` containing:

```

---
- vars:
  - name: noname
  - user: "{{name}}"
  - var: foo
- tasks:
  - shell: echo "name={{name}}, user={{user}}, var={{var}}"
```

Executing the include statement should result in echo of `name=test user=test var=foo`

This would also allow including of playbooks that could otherwise could be run indemendently.
##### Expected Results:

```
name=test, user=test, var=foo
```
##### Actual Results:

Invalid syntax
