### ISSUE TITLE
Issue with when: and | match()

### ISSUE THREAD

**Issue by hoffoo** [ansible/ansible#10410]
**Issue Type:**
Bug Report

**Ansible Version:**
ansible 1.8.4

**Environment:**
Ubuntu host and managing Ubuntu machines

**Summary:**

When using regex expression it fails when a var is not a string, this makes sense but it also happens if the var is null. To try to avoid this situation I tried this:

```
when: var is defined and "{{var | match("foo")}}"
```

The first part of the condition however cant be checked because match will throw an exception when var is undefined.

**Steps To Reproduce:**

This is an example that will fail:

```
- hosts: all
  vars:
      # var: foo
  tasks: 
    - name: fail
      command: /bin/false
      when: var is defined and "{{var | match('foo')}}"
```

**Expected Results:**

The task should be skipped when var is undefined.

**Actual Results:**

The task is not skipped when var is undefined.
