### ISSUE TITLE
Allow value mapping on task "register"

### ISSUE THREAD

**Issue by robzienert** [ansible/ansible#10423]
**Issue Type**: Feature Idea

**Ansible Version**: 1.8.2

**Environment**: N/A

**Summary**:

In my playbook, I'd like to map the result of a module's output more granular than just assigning the full module result object to the variable, but rather just a property of that result. 

**Steps To Reproduce**: N/A

**Expected Results**

``` yaml
# defaults/main.yml

---
artifact_s3_key: someStaticValue

# tasks/main.yml

---
- name: search for latest artifact in s3
  s3_search: bucket={{ bucket }} path={{ artifact_path }} latest=yes
  register: name=artifact_s3_key map=_.key 
  when: dynamic_artifact_resolution

- name: download from s3
  s3: bucket={{ bucket }} object={{ artifact_path }} dest=/tmp/{{ artifact_path }} mode=get
```

**Actual Results**

Unfortunately, I can't do mapping and Ansible doesn't allow extension in this way to let me override its behavior here, so I'm forced to do something like:

``` yaml
# defaults/main.yml

---
artifact_s3:
  key: someStaticValue

# tasks/main.yml

---
- name: search
  s3_search: ...
  register: artifact_s3

- name: download
  s3: object={{ artifact_path.key }} ...
```

**Comment by jctanner** [comment]
You can create a new fact via set_fact with a property of another fact. For example:

```
- shell: uname -a
  register: test
- set_fact:
    uname: "{{ test.stdout }}"
```
