### ISSUE TITLE
vm_extra_config section of vsphere_guest isn't being applied ansible 1.9 (devel ffb281d)

### ISSUE THREAD

**Issue by andreobrown** [ansible/ansible#10433]
When using the vsphere_guest module, I noticed that this configuration option was not working:

```
vm_extra_config:
            folder: beta
```

I tried using beat, /beta, DataCentreName/beta, DataCentreName/vm/beta. The VM would always end up in the same folder as the template.

To troubleshoot the issue, I added the notes field and it didn't take either. It appears that the vm_extra_config section isn't being applied, which would explain why some of the options I tried didn't generate error messages either.

ansible 1.9 (devel ffb281d) last updated 2015/03/04 01:13:13 (GMT -500)

Here is my play:

```
- hosts: vsphere
  gather_facts: false

  vars:
    my_env: beta
    vcenter_hostname: 10.0.0.1
    vcenter_username: "myusername"
    vcenter_password: "mypassword"

  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        guest: "test_{{ my_env }}"
        from_template: yes
        template_src: "my_Template"
        resource_pool: /Resources
        cluster: My-HA-DRS
        vm_nic:
          nic1:
            type: vmxnet3
            network: My-OAM
            network_type: dvs
          nic2:
            type: vmxnet3
            network: My-Production
            network_type: dvs
          nic3:
            type: vmxnet3
            network: My-Backup
            network_type: dvs
        vm_extra_config:
            folder: beta
            notes: "Test notes"
        esxi:
            datacenter: MyDC
```
