### ISSUE TITLE
include_vars is replacing a hash, even when hash_behaviour=merge

### ISSUE THREAD

**Issue by dhutty** [ansible/ansible#10446]
## Issue Type:

Bug Report
## Ansible Version:

ansible 1.8.4

Environment:

For completeness, this is OSX 10.9 -> Ubuntu 12.04
## Summary:

include_vars is replacing a hash, even when hash_behaviour=merge
## Steps To Reproduce:

with hash_behaviour=merge set in ansible.cfg, or ANSIBLE_HASH_BEHAVIOUR=merge as an environment variable, a trivial command: `ansible-playbook -c local test_plyabook.yml -vv`

test_playbook.yml:

```

---
- name: wrapper for testing testrole
  hosts: localhost
  gather_facts: no
  roles:
    - testrole
```

roles/testrole/tasks/main.yml:

```

---
- include_vars: ../defaults/default.yml
- include_vars: ../defaults/Ubuntu.yml
- name: demo
  debug:
    msg: "{{ foo | to_nice_json }}"
```

roles/testrole/defaults/default.yml:

```

---
foo:
  key_A: value_A
  key_B: value_B
  list_A:
    - list_A_Element_1
    - list_A_Element_2
  dict_A:
    subkey_A: value_A
    subkey_B: value_B
```

roles/testrole/defaults/Ubuntu.yml:

```

---
foo:
  key_A: value_C
  list_A:
    - list_A_Element_3
  dict_A:
    subkey_A: value_C
```
## Expected Results:

If it were only a shallow merge (with replacement of deeper parts of the structure), I would expect to see `key_B: value_B` unchanged in the output :

```
ok: [localhost] => {
    "msg": {
        "dict_A": {
            "subkey_A": "value_C"
        },
        "key_A": "value_C",
        "key_B": "value_B",
        "list_A": [
            "list_A_Element_3"
        ]
    }
}
```

And if it were supposed to be a deep merge, I would expect to see listA with 3 elements, and dictA should have 2 subkeys, one of which has the value from the 2nd file *Ubuntu.yml":

```

---
foo:
  key_A: value_C
  key_B: value_B
  list_A:
    - list_A_Element_1
    - list_A_Element_2
    - list_A_Element_3
  dict_A:
    subkey_A: value_C
    subkey_B: value_B
```
## Actual Results:

The actual results are the same as for hash_behaviour=replace:

```
TASK: [testrole | include_vars ../defaults/default.yml] ***********************
ok: [localhost] => {"ansible_facts": {"foo": {"dict_A": {"subkey_A": "value_A", "subkey_B": "value_B"}, "key_A": "value_A", "key_B": "value_B", "list_A": ["list_A_Element_1", "list_A_Element_2"]}}}

TASK: [testrole | include_vars ../defaults/Ubuntu.yml] ************************
ok: [localhost] => {"ansible_facts": {"foo": {"dict_A": {"subkey_A": "value_C"}, "key_A": "value_C", "list_A": ["list_A_Element_3"]}}}

TASK: [testrole | demo] *******************************************************
ok: [localhost] => {
    "msg": {
        "dict_A": {
            "subkey_A": "value_C"
        },
        "key_A": "value_C",
        "list_A": [
            "list_A_Element_3"
        ]
    }
}
```

**Comment by eviln1** [comment]
Ohai,
I ran into this today; not sure if it's a bug or a feature.
I have done some testing on variable precedency, and concluded the following :  
- extra vars _(`-e` switch in the command line)_. If the switch is specified several times, the last mention wins.
- "connection variables defined in inventory (ansible_ssh_user, etc)"
- variables included in roles through the `include_vars:` directive. If specified several times, the last include wins.
- variables defined within **role/vars/main.yml**  
- variables defined within the executed playbook. If the playbook includes another playbook, variables and their precedency are evaluated per playbook. 
- variables defined in the host inventory
- variables defined in the hostgroup inventory. If the host is member of several groups, the last group wins.
- "facts discovered about a system"
- variables defined within **role/defaults/main.yml**

So whenever a variable is included from multiple sources, but within the same priority level, the last inclusion overwrites the previous ones, no matter what the hash_behaviour is set to.
All this just to say that it's not only a "include_vars" issue, but a global one as far as I can tell.

It would  be great if the merge was implemented on all levels.

:+1:

**Comment by shadjifotis** [comment]
I ran into this problem today even with having the hash_behaviour = merge does not result in the multiple hash definitions being merged.
    ---
    # file: cmservers.yml
    - hosts: cmservers
      pre_tasks:
         - include_vars: /var/cm/local/ansible/vault/cmservers
         - include_vars: /var/cm/local/ansible/vars/appusers.yml
         - include_vars: /var/cm/local/ansible/vars/cmusers.yml
         - local_action: "command openssl passwd -salt '{{ cm_default_password_salt }}' -1 '{{ cm_default_password }}'"
           run_once: True
           register: password_hash
           changed_when: False
         - set_fact: users_default_password="{{ password_hash.stdout }}"
         - debug: var=password_hash
         - debug: var=users_default_password
         - debug: msg="Default hash is {{ users_default_password }}"
         - debug: var=users
      roles:
       - ansible-users-master

users hash in cmusers.yml is replacing the users hash that was previously defined in appusers.yml

ansible 1.9.2

**Comment by feliksik** [comment]
Confirmed for include_vars functionality in 1.9.2: not properly merging, but replacing. 

However, note it **also holds for set_vars**! This does accept complex yaml structures [1], but the merge strategy is not used even if 'hash_behaviour = merge'. 

[1] http://grokbase.com/p/gg/ansible-project/147jx8p0q3/set-fact-support-for-list-of-dictionaries

See also issue #9116 and PR #7700, which are closed. I don't really understand the intents of the project here, but for me it would be useful to create extra, templated values in an existing datastructure with set_fact.

**Comment by mburz** [comment]
Issue still present with "2.0.0.2"

**Comment by bcoca** [comment]
fixed via #14450

**Comment by mburz** [comment]
Great, thanks!

**Comment by ineu** [comment]
The behaviour is now inverted as of 2.1.1. Variables included with `include_vars` are now always merged, no matter what value `hash_behaviour` has.

**Comment by ghost** [comment]
It seems to me that merging is not implemented correctly.

role/defaults/main.yml 
```yaml
---
postgresql:
  version: 9.6
```

role/vars/9.6.yml
```yaml
---
package_name: postgresql96
repo_url: https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm
```

role/tasks.yml
```yaml
---

- debug:
    msg: "Variable 'postgresql' {{ postgresql }}" 

- name: Include version specific variables
  include_vars: 
    file: "{{ postgresql.version }}.yml"
    name: postgresql

- debug:
    msg: "Variable 'postgresql' {{ postgresql }}" 

```

The result is that include_vars leads to overriding the complete hash.

```bash
TASK [postgresql : debug] ******************************************************
ok: [acme-db-int01.acme.de] => {
    "msg": "Variable 'postgresql' {u'version': 9.6}"
}

TASK [postgresql : Include version specific variables] *************************
ok: [acme-db-int01.acme.de]

TASK [postgresql : debug] ******************************************************
ok: [acme-db-int01.acme.de] => {
    "msg": "Variable 'postgresql' {u'package_name': u'postgresql96', u'repo_url': u'https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-redhat96-9.6-3.noarch.rpm'}"
}

```

I'd have expected that the hash is merged (and _defaults_ have a lower precedence).

**Comment by alter** [comment]
Any news here?

**Comment by GroovyCarrot** [comment]
Having the same issue as above on version 2.4.2.0 - this doesn't appear to be resolved @bcoca

**Comment by Dmitry1987** [comment]
Does this mean we can only "merge" hashes when they are declared on different precedence levels?

**Comment by adriaand007** [comment]
Hi It is not merging as expected
I have two files
```
host_vars/server1/rsyslog-2.yml 
rsyslog_apps:
  - name: eed
    priority: 19
  - name: drd
    priority: 19
```
and 
```
host_vars/server1/rsyslog.yml
rsyslog_apps:
  - name: influxd
    priority: 19
  - name: dockerd
    priority: 19
```
I would have thought the end esult would have been

```
rsyslog_apps:
  - name: influxd
    priority: 19
  - name: dockerd
    priority: 19
  - name: eed
    priority: 19
  - name: drd
    priority: 19
```
