### ISSUE TITLE
Conditionals evaluation problem

### ISSUE THREAD

**Issue by beli-sk** [ansible/ansible#10460]
I came across a problem with evaluating expressions in `when` statement, best shown on an example. Let's consider a playbook like this:

```

---
- connection: local
  hosts: localhost
  vars:
    foo: false
    bar: "{{ foo }}"

  tasks:
    - command: echo {{ bar }}
      when: True and bar
```

I would assume that when bar is false (as seen in output from the echo command), the `when` expression should evaluate to false and the task should be skipped. But that's not the case, the task gets executed. Could someone please explain what goes on here? Is this a bug or some side effect? If so, is there a workaround for when I want to set a variable to value of another boolean variable or possibly a more complex expression?

Note: it's enough to say `bar: "{{ false }}"` for the same behavior.
