### ISSUE TITLE
MySQL 5.7.6 issue with mysql_user module

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10482]
##### Summary:

It seems that mysql_user module doesn't play well with new version of MySQL server (5.7.6)
Due to changes in mysql.user table (for instance - lack of PASSWORD column) it's impossible to re-run the playbook that contains mysql_user command. 
##### Steps To Reproduce:

Please run this sample task TWICE:

```
- name: create mysql user
  mysql_user:
      name: "sample_user"
      password: "sample_password"
      priv: "example_com.*:ALL"
      state: present
      host: "example_com"
```
##### Expected Results:

I expect to have sample_user created in the database. It work's during first run but when You run the playbook again there is an error. 
##### Actual Results:

Following error:
File "/home/vagrant/.ansible/tmp/ansible-tmp-1426543220.97-273462604863673/mysql_user", line 462, in main
    changed = user_mod(cursor, user, host, password, priv, append_privs)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1426543220.97-273462604863673/mysql_user", line 176, in user_mod
    cursor.execute("SELECT password FROM user WHERE user = %s AND host = %s", (user,host))
  File "/usr/lib64/python2.6/site-packages/MySQLdb/cursors.py", line 173, in execute
    self.errorhandler(self, exc, value)

**Comment by morgo** [comment]
MySQL has version specific comment syntax, so a workaround for this is to alias authentication_string as password:

```
 select /*!50706 authentication_string as */ password from mysql.user;
```

Note that this will not fix MySQL 5.6 support (due to [this bug](http://www.tocker.ca/2015/03/10/heads-up-mysql-5-7-dmr6-contains-a-small-known-bug.html) also affecting the code), but it should work in 5.7.7 RC+

**Comment by peerst** [comment]
Seems to be still a issue with ansible 1.9.4 and mysql 5.7.10 on FreeBSD

Weirdly it partially works:

So when I run

```
- name: mysql | Update root password for all root accounts
  mysql_user: name=root host={{ item }}  password={{ mysql.root_password }} 
  with_items:
      - "{{ ansible_fqdn }}"
      - 127.0.0.1
      - localhost
```

The first two work but the localhost complains about missing password column

```
TASK: [phabricator | mysql | Update root password for all root accounts] ****** 
changed: [ariel] => (item=myhost.example.com)
changed: [ariel] => (item=127.0.0.1)
failed: [ariel] => (item=localhost) => {"failed": true, "item": "localhost"}
msg: (1054, "Unknown column 'password' in 'field list'")
```

Not sure if this is still the same issue?

Seems to be the same issue ... since the only entry for root in mysql.user is root@localhost and the nonexisting entries are probably ignored
