### ISSUE TITLE
Private property for vars_prompt hangs

### ISSUE THREAD

**Issue by AlexanderAllen-zz** [ansible/ansible#10517]
Whenever I specify the private property on my vars_prompt Ansible takes my input, but after pressing enter it "hangs". If I take the "private" property out, vars_prompt works.

Reference: https://github.com/ansible/ansible/blob/507a1ef0934b9a03c9c76c4faa84b89731f22748/docsite/rst/playbooks_prompts.rst

Hangs:

```
# playbook.yml

hosts: foobar
vars_prompt:

    - name: "release_version"
      prompt: "Product release version"
      private: no
```

Works:

```
    - name: "release_version"
      prompt: "Product release version"
```

Ansible version: ansible 1.8.4
