### ISSUE TITLE
ansible-playbook with --tags failed: One or more undefined variables: 'apt_repository_state' is undefined

### ISSUE THREAD

**Issue by weldpua2008** [ansible/ansible#10568]
Hello,
If I using ansible-playbook with --tags it failing but without --tags all ok.

ansible-playbook -i rde/hosts rde/main.yml --tags=base -e isUndo=True

```
PLAY [Role] ***************************************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [base | Install Base packages] ******************************************
ok: [127.0.0.1] => (item=build-essential,python-pkg-resources,python-jinja2,python-setuptools,python-minimal,python-yaml,python-pip,python-virtualenv,python-software-properties,ansible,uwsgi-plugin-python,uwsgi-core,uwsgi)

TASK: [base | Managing repository] ****************************************
fatal: [127.0.0.1] => One or more undefined variables: 'apt_repository_state' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/main.retry

127.0.0.1                  : ok=2    changed=0    unreachable=1    failed=0
```

/role/main.yml:

```

---
- name: Role
  hosts: 127.0.0.1
  connection: local
  user: root
  vars:
    isUndo: false

  roles:
    - base 
```

/role/roles/base/tasks/main.yml:

```

---
- name: Preparetion
  set_fact:    
    apt_repository_state: "{{ 'absent' if isUndo else 'present' }}"
    apt_state: "{{ 'absent' if isUndo else 'present' }}"
    pip_state: "{{ 'absent' if isUndo else 'present' }}"
    pip_state_latest: "{{ 'absent' if isUndo else 'latest' }}"

- name: "Managing repository"
  apt_repository: repo='deb http://repo precise non-free' state="{{apt_repository_state}}" update_cache=yes
  tags:
    - base
```

/role/roles/base/vars/main.yml:

```
packages:
    - libsdl1.2debian
    - sux
packages_core:
    - build-essential
    - python-pkg-resources
```
