### ISSUE TITLE
Copy module with recursive - empty dirs not copied over

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#10567]
ansible 1.9.0.1 Mac OSX controlling Slackware Linux hosts

The copy module does not copy over empty directories. 
Directories that contain at least one file do get copied.

For ex this copy task:

```
# Copy skel files to skel
- name: aws copy skel files
  copy: >
    src=etc/skel/aws/
    dest={{ conf_skel_dir }}/.aws/
    owner=root group=root 
    mode=0600 directory_mode=0700
    force=yes
```

**Comment by abadger** [comment]
Reproduced with a corrected playbook:

```
---
- hosts: localhost
  tasks:
    - copy:
        src: /var/tmp/roles
        dest: /var/tmp/mine/
```

Note: i would not expect it to work if the src has a trailing slash (as that denotes that the files inside of the directory are supposed to be copied rather than the directory itself.)
