### ISSUE TITLE
Magic `null` to `None` convertation

### ISSUE THREAD

**Issue by igormukhingmailcom** [ansible/ansible#10560]
Hi.

I using ansible to generate `parameters.yml` for symfony2 application.

``` yml
# vars
symfony2_parameters:
  mailer_encryption: null
```

``` yml
# tasks/main.yml
- name: Symfony2 | parameters.yml | Generate from template
  template:
    src: "{{ item }}"
    dest: "{{ symfony2_shared_root }}/app/config/parameters.{{ symfony2_parameters_extension }}"
  with_items:
    - "parameters.{{ symfony2_parameters_extension }}.js2"
```

``` yml
# templates/parameters.yml.js2
parameters:
{% if symfony2_parameters is defined %}
{% for key, value in symfony2_parameters.iteritems() %}
    {{ key }}: {{ value }}
{% endfor %}
{% endif %}
```

I get next result:

``` yml
# app/config/parameters.yml
parameters:
  ...
  mailer_encryption: None
```

So, `mailer_encryption` becomes `None` but must be `null`.
Are this is bug or expected behavior?
If second, how can I workaround this?

Thank you.

Environment information:

```
ubuntu 14.04 x64
ansible 1.9.0.1
```

**Comment by bcoca** [comment]
this is a 'feature' if you describe something in yaml as 'null' it will turn into the equivalent in the language that parses it, in this case it is python and it becomes None.

try:
 var: "null"

**Comment by igormukhingmailcom** [comment]
Yep, that helps.
Thanks a lot.

If anyone has same problem - please, notice that you will give in result `None` even if you use `variable: "null"` with quotes in one case - if you also use quotes around your variable at your template:

``` yml
 {{ key }}: "{{ value }}"
```

**So we have next rule**: Use quotes in variable definition, but _not_ in template:

``` yml
# playbook.yml

var:
  variable: "null"
```

``` yml
# templates/parameters.yml.j2

parameters:
 {{ key }}: {{ value }}
```
