### ISSUE TITLE
Auto converting variable=yes to variable=True

### ISSUE THREAD

**Issue by adrianbanasiak** [ansible/ansible#10583]
When you specify variable as test=yes its value is converted to True. yes and True can mean the same in ansible but i dont think that value should be converted.

``` yaml
- hosts: all
  sudo: no
  gather_facts: no
  vars:
    test1: yes
    test2: True
    test3: no
    test4: false

  tasks:
  - debug: var=test1
  - debug: var=test2
  - debug: var=test3
  - debug: var=test4
```

``` yaml
ansible-playbook -i hosts, test.yml
PLAY [all] ********************************************************************

TASK: [debug var=test1] *******************************************************
ok: [hosts] => {
    "test1": "True"
}

TASK: [debug var=test2] *******************************************************
ok: [hosts] => {
    "test2": "True"
}

TASK: [debug var=test3] *******************************************************
ok: [hosts] => {
    "test3": "False"
}

TASK: [debug var=test4] *******************************************************
ok: [hosts] => {
    "test4": "False"
}

PLAY RECAP ********************************************************************
hosts                      : ok=4    changed=0    unreachable=0    failed=0
```

```
ansible --version
ansible 1.8.4
  configured module search path = None
```
