### ISSUE TITLE
[bug:fireball] cannot execute any modules: authentication or permission failure

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#10599]
#### Summary

When I attempt to use fireball mode, I get an error message when ansible is trying to deploy the module over the fireball connection. I've traced this to fireball basically not interpreting the command in an insecure shell. I'm not sure if this is intentional, but frankly I have no idea how anyone has gotten this to work. So that makes me think I am missing something...
#### Error message:

> Authentication or permission failure.  In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: mkdir -p /tmp/ansible/ansible-tmp-1427936806.99-221640878217542 && chmod a+rx /tmp/ansible/ansible-tmp-1427936806.99-221640878217542 && echo /tmp/ansible/ansible-tmp-1427936806.99-221640878217542, exited with result 127
#### Fix?

I was able to fix (hack?) this by adding `use_unsafe_shell=True` to [utilities/helper/fireball.py](https://github.com/ansible/ansible-modules-core/blob/950fe9ee56efdf84d944301c6d7df5b447331895/utilities/helper/fireball.py#L159)

I am not familiar enough with the context to determine if this is safe or correct. But if I understand the problem correctly, fireball cannot without it.
#### Example

```

---
- hosts:
    - builder
  gather_facts: false
  connection: ssh
  user: me
  sudo: True
  tasks:
    - action: fireball

- hosts:
    - all
  gather_facts: false
  connection: fireball
  user: me
  tasks:
    - command: date
```
#### Versions

Local host: Mac OS 10.10 Yosemite
Local libraries:

```
ansible==1.9.0.1
python-keyczar==0.715
pyzmq==14.5.0
```

Remote host: CentOS 5 x64
Remote libraries (many built by me from the fedora packages, yay centos 5!):

```
python26-2.6.8-2.el5
python26-pyasn1-0.1.7-5
python26-keyczar-0.71c-2
python26-crypto-2.3-5.el5
python26-pyasn1-modules-0.1.7-5
python26-zmq-14.3.1-1.el5
```
