### ISSUE TITLE
Docker module choose random port if we didn't pass a variable. 

### ISSUE THREAD

**Issue by vankhoa011** [ansible/ansible#10592]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

docker module
##### ANSIBLE VERSION

1.8.0
##### SUMMARY

In 1.8.0 version, If I didn't pass "ports" variable, Docker module will not bind any port to the Docker Host. It worked correctly.
However, In 1.9.0.1, Docker module choose a random ports, and bind to Docker Host. I think there is something wrong.
If I remove this line (  ports: "{{ docker_ports|default(omit) }}" ) , the docker module works correctly.

```
  - name: Run docker container
     docker:
       image: "{{ docker_image }}"
       name: "{{ docker_name }}"
       command: "{{ docker_command|default(omit) }}"
       ports: "{{ docker_ports|default(omit) }}"
       env: "{{ docker_env|default(omit) }}"
       volumes: "{{ docker_volumes|default(omit) }}"
```
