### ISSUE TITLE
Need ability to created tagged EBS volumes and have them attached with delete_on_termination = true

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#10631]
I first tried to create my EC2 instances with a volume dictionary, but that method doesn't let me tag the volumes.

I then tried to create the EC2 instances without the EBS volumes, then created and attached the EBS volumes, but that method doesn't let me set them to delete on termination.

One alternative would have been to create the EC2 instances one at a time with a volume dictionary, intending to loop through the volumes and tag them after the fact. But then I ran into the issue where I'm unable to invoke my create-one-instance include in a with_sequential loop.

The ideal scenario for me would be to make ec2 support volume tags in the dictionary but I'd be happy to get any method that works.

**Comment by halberom** [comment]
It would be nice if the tagging were included in ec2 and ec2_vol, but you can do this quite easily regardless

```
- name: create instance
  ec2:
    ...
    volumes:
      ...
      delete_on_termination: yes
  register: ec2_out

- name: get associated vols
  ec2_vol:
    instance: "{{ ec2_out.tagged_instances[0].id }}"
    state: list
    region: "{{ region }}"
  register: ec2_vol_out

- name: tag the volumes
  ec2_tag:
    resource: "{{ item.id }}"
    region:  "{{ region }}"
    tags: 
      Name: foo
  with_items: "{{ ec2_vol_out.volumes | default([]) }}"
```

**Comment by Constantin07** [comment]
May be the good idea would be to include a parameter which will allow to apply the instance tags to volumes too?

**Comment by ghost** [comment]
@Constantin07 I need unique instance tags per volume in order to support the rest of my automation. That said, my tags are constructed from the instance name + device name::

```
  - name: get volume info
    local_action:
      module: ec2_vol
      device_name: "{{item.device_name}}"
      instance: "{{ec2_id}}"
      region: "{{region}}"
      volume_size: "{{item.volume_size}}"
      zone: "{{ec2_placement}}"
    register: volume
    with_items: "{{instance_spec.volumes}}"

  - name: tag the volumes
    local_action: ec2_tag resource="{{item.volume_id}}"
    args:
      tags:
        Name: "{{ec2_tag_Name}}-{{item.item.device_name | basename}}"
        env: "{{env}}"
    with_items: volume.results
    when: instance_spec.volumes | length > 0
```
