### ISSUE TITLE
Two volumes bound to the same dir starts Docker with only one volume properly bound

### ISSUE THREAD

**Issue by scottbrown** [ansible/ansible#10635]
##### Issue Type:

Bug Report
##### Component Name:

docker module
##### Ansible Version:

1.9.0.1
##### Environment:

OSX 10.10.2
Docker 1.5.0, build a8a31ef
##### Summary:

Calling the [docker](http://docs.ansible.com/docker_module.html) module with two volumes bound to the same directory, causes docker to be started with only one valid mount.  The other mount in the docker container is mounted to nothing on the host.
##### Severity

Using the same directory for two different mount points in the docker container is not a common use case, but it does come up.  The docker CLI properly mounts all directories, so this means the Ansible module is not a 1:1 mapping of docker's CLI abilities (extra newlines added for clarity):

```
$ ls /tmp
com.apple.launchd.9tRzZ8MulK
com.apple.launchd.lxyjxxC5Kv

$ docker run -v /tmp:/inbox -v /tmp:/outbox ubuntu:latest /bin/bash

docker $ ls /inbox
com.apple.launchd.9tRzZ8MulK
com.apple.launchd.lxyjxxC5Kv
docker $ ls /outbox
com.apple.launchd.9tRzZ8MulK
com.apple.launchd.lxyjxxC5Kv
```
##### Steps To Reproduce:

This bug is easy to reproduce by calling the Ansible docker module and binding the same directory to two mount points in the docker container.

``` YAML
- docker:
    image: 'ubuntu:latest'
    command: '/bin/bash'
    volumes:
      - "/tmp:/inbox"
      - "/tmp:/outbox"
```
##### Cause

The issue is caused by lines 508 and 515 in `ansible/modules/core/cloud/docker/docker.py` because the `self.binds` hash uses the host's mount point as a key to the hash.  Since the host's mount point can be used multiple times in the `volumes` array, this python code is incorrect.

```
 503             for vol in vols:
 504                 parts = vol.split(":")
 505                 # host mount (e.g. /mnt:/tmp, bind mounts host's /tmp to /mnt in the container)
 506                 if len(parts) == 2:
 507                     self.volumes[parts[1]] = {}
 508                     self.binds[parts[0]] = parts[1]
 509                 # with bind mode
 510                 elif len(parts) == 3:
 511                     if parts[2] not in ['ro', 'rw']:
 512                         self.module.fail_json(msg='bind mode needs to either be "ro" or "rw"')
 513                     ro = parts[2] == 'ro'
 514                     self.volumes[parts[1]] = {}
 515                     self.binds[parts[0]] = {'bind': parts[1], 'ro': ro}
 516                 # docker mount (e.g. /www, mounts a docker volume /www on the container at the same location)
 517                 else:
 518                     self.volumes[parts[0]] = {}
```
##### Expected Results:

Both volumes should be mounted in the docker container.  From within the docker container, you should be able to view both mounted volumes and see the files in the host's `/tmp` directory.

```
host$ ls /tmp
com.apple.launchd.9tRzZ8MulK
com.apple.launchd.lxyjxxC5Kv

docker$ ls /inbox
com.apple.launchd.9tRzZ8MulK
com.apple.launchd.lxyjxxC5Kv

docker$ ls /outbox
com.apple.launchd.9tRzZ8MulK
com.apple.launchd.lxyjxxC5Kv
```
##### Actual Results:

The mount happens on the last entry in the `volumes` array that has the same host bind name.

```
host$ ls /tmp
com.apple.launchd.9tRzZ8MulK
com.apple.launchd.lxyjxxC5Kv

docker$ ls /inbox

docker$ ls /outbox
com.apple.launchd.9tRzZ8MulK
com.apple.launchd.lxyjxxC5Kv
```

**Comment by ansibot** [comment]
@scottbrown: Thanks for taking the time to open this issue, but it was filed under the wrong github repository. Please create a new issue at https://github.com/ansible/ansible-modules-core/issues
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by SpComb** [comment]
This bug is still relevant on Ansible 2.7.4. The issues for the ansible modules have been moved back to this GitHub repo, so should this issue be re-opened, or should I open a new issue?

--- 

Trying to bind-mount the same `/opt/influxdb` host path to `/opt/influxdb` (read-only) and `/var/lib/influxdb` (read-write) fails, and only the second volume actually gets bind-mounted:

```yaml
- name: Deploy influxdb container
  vars:
    influxdb_data_path: /opt/influxdb # this comes from inventory vars, depends on host
  docker_container:
    name: "{{ container_name }}"
    image: "{{ influxdb_docker_image }}"
    state: started
    env:
      INFLUXDB_CONFIG_PATH: /opt/influxdb/influxdb.conf
    volumes:
      - /opt/influxdb:/opt/influxdb:ro # config
      - "{{ influxdb_data_path }}:/var/lib/influxdb:rw" # data
```

InfluxDB fails to start up:

```
run: parse config: open /opt/influxdb/influxdb.conf: no such file or directory
```

This is because the container `host_config` `binds` only contains the later of the two mounts:

```
$ docker inspect -f '{{ .HostConfig.Binds | json }}' influxdb_1
["/opt/influxdb:/var/lib/influxdb:rw"]
```

I'm pretty sure the reason is the same as in the original post, the Ansible module's `TaskParameters._get_volume_binds` returns a dict keyed by the `host` path, so the two volume bind-mounts collide. 

The docker-py library's `create_host_config` also accepts an array of `src:mnt:mode` strings, which would avoid this issue: https://docker-py.readthedocs.io/en/1.8.0/volumes/

This is the same underlying data format that the actual Docker API uses: https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate
