### ISSUE TITLE
Ansible not reading from AWS ENV variables?

### ISSUE THREAD

**Issue by atedja** [ansible/ansible#10638]
I have AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY in my environment variables set, but I got this instead:

```
msg: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials
```

As soon as I did this:

```
      local_action:
        aws_access_key: ACCESS_KEY
        aws_secret_key: SECRET_KEY
        module: ec2_elb
        region: us-west-1
        instance_id: "{{ ansible_ec2_instance_id }}"
        state: 'absent'
```

With the same values, it works.

ansible 1.9.0.1
Ubuntu 14.04

**Comment by ekmerril** [comment]
Hi this as well.

**Comment by windowsrefund** [comment]
I'm still seeing this bug as of today's pull/rebase of 2.0.0

**Comment by windowsrefund** [comment]
Still seeing this

```
ansible 2.1.0 (devel e54bf43cfc) last updated 2015/12/02 12:18:19 (GMT -400)
```

**Comment by yoshiwaan** [comment]
I have credentials in ~/.aws/credentials and just ran into this using the ec2_elb_lb and ec2_elb modules.
I feel like this may have something to do with local_action as in another play which I run against localhost to stand up a stack I used both of these modules successfully without the local_action wrapper (the playbook runs with hosts: localhost)

On the other hand maybe it's because when running against localhost it's the logic of the boto library itself pulling the credentials, not ansible, which fails when local_action is used

This is similar to https://github.com/ansible/ansible/issues/9984

**Comment by mourngrym1969** [comment]
Still seeing this - CentOS 7, Ansible 2.1 (from Github build directly), EC2_KEY module specifically (will test others).

This is a big deal, I don't want the keys and IDs exposed in the playbooks and the credentials files and environment variables are not working but as above, including them in the playbook works fine.

**Comment by yoshiwaan** [comment]
You can use this as a work around instead of hard coding them and it achieves the same thing as setting the ENV variables, although requires more code:

```
- name: "example task"
  local_action:
    module: ec2
    state: absent
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
```

Either way, support for the proper configuration files should be added
