### ISSUE TITLE
with_items is not a legal parameter at this level in an Ansible Playbook

### ISSUE THREAD

**Issue by baxiaoshi** [ansible/ansible#10640]
```

---
- name: add several users
  user: name={{ item }} state=present group=root
  with_items:
     - testuser1
     - testuser2
```

I copy from the official website, but when I perform an error.
My English is not very good, thank you

[root@ansible_master ansible]# ansible-playbook -i httpd/hosts playbooks/add_user.yml  -k 
SSH password: 
ERROR: with_items is not a legal parameter at this level in an Ansible Playbook

[root@ansible_master ansible]# ansible --version
ansible 1.8.4
  configured module search path = None

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

The above is only a task, not a full play, you need something like:

```
- hosts: all
  tasks: 
   - name: add several users
     user: name={{ item }} state=present group=root
     with_items:
       - testuser1
       - testuser2
```
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
