### ISSUE TITLE
RDS module can not set up the maint_window time over midnight.

### ISSUE THREAD

**Issue by kevintsai** [ansible/ansible#10666]
##### Issue Type:

Bug Report
##### Ansible Version:

1.8.0
1.9.0.1
##### Environment:

Target & Host: CentOS 6.6
##### Steps To Reproduce:

```
- name: Setup maintenance window
  rds:                                                                                                         
    instance_name: my-rds
    command: modify
    region: us-west-1
    maint_window: "Mon:23:30-Mon:00:00"
```
##### Summary:

If we put the end time to "00:00", then will shows
"msg: Maintenance window cannot end before it begins."

If we put the end time to "24:00", then will shows
"msg: Invalid day:hour:minute value: mon:24:0"

Is it possible an issue on Ansible?
Can we fix this issue to allow these 2 cases? 
Thanks.
