### ISSUE TITLE
JSON output gets truncated on spaces

### ISSUE THREAD

**Issue by bobrik** [ansible/ansible#10673]
##### Issue Type:

Bug report
##### Ansible Version:

```
λ ansible --version
ansible 2.0.0
  configured module search path = ../library
```

and

```
λ ansible --version
ansible 1.9.0.1
  configured module search path = ../library
```
##### Environment:

N/A
##### Summary:

`copy: content="{{ some_data|to_json }}\n" dest=/tmp/wtf.yaml` results in truncated json.
##### Steps To Reproduce:

Example playbook:

``` yaml
- hosts: web414
  vars:
    some_data:
      something:
        wow: "hey ho"
  tasks:
    - name: write some json
      copy: content="{{ some_data|to_json }}\n" dest=/tmp/wtf.yaml
```

Resulting file:

```
web414 ~ # cat /tmp/wtf.yaml
"{"something": {"wow": "heyweb414 ~ #
```
##### Expected Results:

File should not be truncated.
##### Actual Results:

File gets truncated.
