### ISSUE TITLE
[Bug] Using expanduser with Vagrant take unexpected result

### ISSUE THREAD

**Issue by igormukhingmailcom** [ansible/ansible#10670]
Hi.

My login on my laptop is `igor`.
I use Vagrant for testing purposes.

``` python
# Vagrantfile
$VM_BOX = ENV.has_key?('VM_BOX') ? ENV['VM_BOX'] : 'hashicorp/precise32'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = $VM_BOX

    config.vm.provision :ansible do |ansible|
        ansible.playbook = 'playbook.yml'
        ansible.verbose = 'vv'
    end
end
```

``` yml
# playbook.yml

---
- hosts: all
  vars:
    xxx_home_path: "~/.xxx"
  pre_tasks:
  - fail:
      msg: "{{ xxx_home_path | expanduser }}"
```

(I use `fail` command just for print & exit)

Got result:

``` bash
TASK: [fail ] ***************************************************************** 
failed: [default] => {"failed": true}
msg: /home/igor/.xxx
```

But it must be:

``` bash
TASK: [fail ] ***************************************************************** 
failed: [default] => {"failed": true}
msg: /home/vagrant/.xxx
```

Because user named `igor` even not exists on Vagrant box.

So `| expanduser` expands local user `igor`, not remote `vagrant`.
