### ISSUE TITLE
handlers won't fire other handlers - depending on handler module used

### ISSUE THREAD

**Issue by pearofducks** [ansible/ansible#10735]
##### Summary:

When certain modules are used, a handler won't call the next in the chain.

For tasks...

```
  tasks:
  - command: echo t
    notify: do
```

**Works (both handlers fire):**

```
  handlers:
  - name: do
    command: echo bar
    notify: do1
  - name: do1
    command: echo h2
```

**Fails (only first handler fires):**

```
  handlers:
  - name: do
    set_fact: foo=bar
    notify: do1
  - name: do1
    command: echo h2
```
##### Steps To Reproduce:
- Create a chain of handlers as shown above
- Use either `debug` or `set_fact` module (probably others, but untested)
##### Expected Results:
- Second handler should be fired
##### Actual Results:
- Handler chain dies
