### ISSUE TITLE
'shell' docs don't cover different splitting behavour between 'args' and normal variant

### ISSUE THREAD

**Issue by ringerc** [ansible/ansible#10745]
The `args` and regular forms of the `shell` task behave differently w.r.t to argument splitting and quoting, in ways that're not immediately obvious, do not appear documented, and could cause malfunction and/or even metachar-related security issues.

These two things look the same, but do different things, because one passes the freeform string unquoted/unescaped to the shell, wheras one escapes it:

```
- hosts: localhost
  vars:
    - make_cmd: "make"
  tasks:
  - name: make clean
    shell: "{{make_cmd}} clean"
    args:
      chdir: "somedir"

```

This will emit, as expected:

```
stderr: make: *** No rule to make target 'clean'.  Stop.
```

However:

```
- hosts: localhost
  vars:
    - make_cmd: "make"
  tasks:
    - name: make clean
      shell: chdir=somedir "{{make_cmd}} clean"
```

which looks the same, will emit:

```
stderr: /bin/sh: make clean: command not found
```

because the whole freeform arg is passed quoted to the shell in this form of the task. This is an exceedingly dangerous and subtle behaviour change.

The docs really need to cover this especially for something where quote handling is quite so security-critical as the shell.

The equivalent in non-`args` form is actually:

```
- hosts: localhost
  vars:
    - make_cmd: "make"
  tasks:
    - name: make clean
      shell: chdir=somedir "{{make_cmd}}" clean
```

where each argument is individually quoted.
