### ISSUE TITLE
meta: flush_handlers does not work in roles if --tags is used

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#10758]
##### Issue Type:

Bug Report
##### Ansible Version:
- devel
- 1.9.0.1
- 1.9.1-rc2
##### Environment:

Tested on ArchOS, Ubuntu 14.04 LTS
##### Summary:

`- meta: flush_handlers` does not work in roles if role has a tag and `--tags` is used. with that role tag.
##### Steps To Reproduce:

``` yaml
# playbook test.yml 

---
- hosts: localhost
  gather_facts: no
  roles:
  - { role: test_role, tags: ['test_role'] }
```

``` yaml
# role tasks: test_role/tasks/main.yml 

---
- shell: echo test flush handlers start
  notify: test flush_handlers

- meta: flush_handlers

- shell: echo test flush handlers end
```

``` yaml
# role handler: test_role/handlers/main.yml 

---
- name: test flush_handlers
  debug: msg="should not run at the end"
```

``` bash
ansible-playbook test.yml --tags test_role
```
##### Expected Results:

```
PLAY [localhost] ************************************************************** 

TASK: [test_role | shell echo test flush handlers start] ********************** 
changed: [localhost]

NOTIFIED: [test_role | test flush_handlers] *********************************** 
ok: [localhost] => {
    "msg": "should not run at the end"
}

TASK: [test_role | shell echo test flush handlers end] ************************ 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=2    unreachable=0    failed=0  
```
##### Actual Results:

```
PLAY [localhost] ************************************************************** 

TASK: [test_role | shell echo test flush handlers start] ********************** 
changed: [localhost]

TASK: [test_role | shell echo test flush handlers end] ************************ 
changed: [localhost]

NOTIFIED: [test_role | test flush_handlers] *********************************** 
ok: [localhost] => {
    "msg": "should not run at the end"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=2    unreachable=0    failed=0 
```
