### ISSUE TITLE
copy module creates an empty file named /root/0: with FreeBSD's csh

### ISSUE THREAD

**Issue by olgeni** [ansible/ansible#10772]
I'm using ansible-1.9.0.1 on a FreeBSD 10.1 client, with both Debian 7.8 and FreeBSD 10.1 servers.

On the FreeBSD boxes, the `copy` module always creates an empty `/root/0:` file when `csh` is used as the shell (which is the default for user `root`).

This can be reproduced at will using this tiny playbook:

```

---
- hosts: all
  user: root
  tasks:
    - copy: src=/etc/hosts dest=/tmp/hosts
```

According to DTrace, the file is opened by `/bin/csh`. This does not seem to happen when `/bin/sh` is used.
