### ISSUE TITLE
CloudFormation module requires "template" parameter even when doing state absent.

### ISSUE THREAD

**Issue by plombardi89** [ansible/ansible#10792]
Ansible version = 1.9.0.1

Very simple task to delete a CloudFormation stack is throwing up unless I provide a valid path to a file for 'template' parameter. The documentation says it is not required and the example shows it as missing from the 'absent' example.

Example task:

``` yaml
- name: delete cloudformation stack
  cloudformation:
    region: "{{ stack_region }}"
    stack_name: "{{ stack_name }}"
    state: absent
#    template: "{{ stack_templates_root }}/fake.json"
```

Generates the following:

> TASK: [delete_cloudformation | delete cloudformation stack] ******************\*  
> failed: [localhost] => {"failed": true}  
> msg: missing required arguments: template                                                                                                                                                                 
> 
> FATAL: all hosts have already failed -- aborting

If you uncomment the template parameter and point it to any file (not even a valid CF template) it works fine.
