### ISSUE TITLE
Service module not working properly

### ISSUE THREAD

**Issue by tpaktop77** [ansible/ansible#10809]
Hello,

Ansible version: 1.9.0.1-1ppa~trusty 

Playbook:

```

---
- hosts: nva-appservers
  gather_facts: no
  sudo: yes

  tasks:
  - name: Stop daemon
    command: "/etc/init.d/cw_scaler-init stop"
#    service: name=cw_scaler-init enabled=yes state=stopped
#    service: name=cw_scaler-init state=stopped pattern="/bin/bash /opt/aws/cw_scaler.sh"
```

Tryed to play this simple playbook against remote machine:

Before

```
[root@somemachine log]# service cw_scaler-init status
cw_scaler is running.
```

Playing playbook:

```
ansible-playbook -vv ./stop.yml 

PLAY [nva-appservers] ********************************************************* 

TASK: [Stop daemon] *********************************************************** 
<xxxx> REMOTE_MODULE command /etc/init.d/cw_scaler-init stop
<cccc> REMOTE_MODULE command /etc/init.d/cw_scaler-init stop
changed: [cccc] => {"changed": true, "cmd": ["/etc/init.d/cw_scaler-init", "stop"], "delta": "0:00:00.022862", "end": "2015-04-21 15:55:11.189037", "rc": 0, "start": "2015-04-21 15:55:11.166175", "stderr": "", "stdout": "", "warnings": []}
changed: [xxxx] => {"changed": true, "cmd": ["/etc/init.d/cw_scaler-init", "stop"], "delta": "0:00:00.022716", "end": "2015-04-21 15:55:12.161918", "rc": 0, "start": "2015-04-21 15:55:12.139202", "stderr": "", "stdout": "", "warnings": []}

PLAY RECAP ******************************************************************** 
xxxx                  : ok=1    changed=1    unreachable=0    failed=0   
cccc                 : ok=1    changed=1    unreachable=0    failed=0   
```

But on both remote servers it looks the same.

```
[root@somemachine log]# service cw_scaler-init status
cw_scaler is running.
```
