### ISSUE TITLE
Omit not working as expected

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#10816]
**Issue Type:**

Bug Report

**Ansible Version:**

```
ansible 2.0.0 (devel d590dc35e7) last updated 2015/04/19 00:12:53 (GMT -700)
  lib/ansible/modules/core: (detached HEAD a19fa6ba48) last updated 2015/04/19 00:13:04 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/19 00:13:10 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 34784b7a61) last updated 2015/04/19 00:13:18 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD df7fcc90d9) last updated 2015/04/19 00:13:27 (GMT -700)
  configured module search path = None
```

**Environment:**

Running from OSX

**Summary:**

I want to prevent some module options being set when it meets a condition. I thought `omit` would be what I want, but it doesn't seem to work properly.

**Steps To Reproduce:**

``` yaml
app_envs: production

- docker:
    image: redis:latest
    env:
      DB_TV_HOST: "{{ ('production' not in app_envs) | ternary('mongo-' + item, omit) }}"
  with_items: app_envs
```

**Expected Results:**

DB_TV_HOST is not set

**Actual Results:**

`DB_TV_HOST` being set to `__omit_place_holder__636798eadb717f89740d6247088d3c80af29b649`

Am I misunderstanding how omit is to be used? I saw examples with `{{ item.blah | default(omit) }}`, but that does not fit my needs.
