### ISSUE TITLE
Explicitely set a value to its default raise an exception

### ISSUE THREAD

**Issue by Glandos** [ansible/ansible#10821]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 1.9.0.1
  configured module search path = None
##### Environment:

OpenSuse 13.2
##### Summary:

If I set a value for an argument, which is the default value, but not recognized as a valid value, then an error is raised.
##### Steps To Reproduce:

Create the following task:

```
- name: Enabling cron jobs
  cron:
      name: Cron job
      job: echo 'lol'
      special_time: null
```
##### Expected Results:

The `special_time` parameter is set to its default value. It shouldn't be checked.
##### Actual Results:

```
msg: value of special_time must be one of: reboot,yearly,annually,monthly,weekly,daily,hourly, got: None
```
