### ISSUE TITLE
Support optional and multi-receiver notifications

### ISSUE THREAD

**Issue by ringerc** [ansible/ansible#10839]
I was very surprised to find that if a task fires a notification, a handler for that notification must exist:

```

---

- hosts: localhost
  tasks:
    - name: Fire any handlers that are listening
      shell: echo "firing handler"
      notify: somehandler
```

and that if there's more than one handler declared for a notification, the documentation says nothing about what's done, but it looks like Ansible arbitrarily picks the first handler it sees and fires that one. It doesn't execute all of them, and doesn't report an error.

```

---

- hosts: localhost
  handlers:
    - name: somehandler
      shell: echo "First somehandler run"
    - name: somehandler
      shell: echo "Second somehandler run"
  tasks:
    - name: Fire any handlers that are listening
      shell: echo "firing handler"
      notify: somehandler
```

Both these behaviours make handlers much less useful when writing composeable, re-usable roles. [Neither appears to be documented](http://docs.ansible.com/playbooks_intro.html#handlers-running-operations-on-change). There's no indication of how handler precedence operates when one role depends on another, either.

Related to #10829 which also concerns the utility of handlers.

What I'd like to see is:

```
    - name: Fire any handlers that are listening
      shell: echo "firing handler"
      notify: somehandler
        all: true
        optional: true
```

or something along those lines. A way to make notifications a useful mechanism for extensibility in roles, for hooks at certain stages of roles doing tasks.

**Comment by bcoca** [comment]
Ansible is not and does not want to be a programming language, things like this go against it's purpose of keeping things simple.

**Comment by ringerc** [comment]
Personally I think this is a case of making things so simple that you need complicated workarounds.

Ansible has notifications and handlers, which arguably can just be done with tasks that register variables. But notifications and handlers _make things simpler to express_.

A simple event system would be much the same. Maybe not spelled with notifications and handlers; maybe:

```
tasks:
  - name: Tell everyone we've restarted the server
    event: server_restarted
```

and in another role:

```
event_listeners:
    server_restarted:
      - name: Reconnect and make sure MyApp works
        command: ...blah...
        failed_when: ...blah...
```

(possibly repeated for multiple apps in multiple roles).

The _lack_ of an immediate, many:many way to communicate between roles doesn't make simple things easier, but makes more complex deployments much harder and more complicated.

Working around this involves (ab)use of `meta: fire_handlers`, and/or lots of conditional includes from other roles and poking around in other roles' variables using JINA2 templates to append to lists. I don't see how that's simpler.
