### ISSUE TITLE
[docker] how to put all env variables in one ansible variable 

### ISSUE THREAD

**Issue by allan-simon** [ansible/ansible#10836]
I'm trying to create one repository https://github.com/allan-simon/ansible-docker-symfony2-vagrant generic to deploy any symfony2 application.

for this I use ansible with the docker module. it works great, as long as my applications needs the same environment variables  I have no problem at all,  i define one variables file by project and that's it.

but I'm stucked for application that needs specific variables (like the address of an oauth2 server) of course I always can keep a slightly modified copy, but it kills the idea

I woud like to know if there's a magic way put an array of environment variables and in my ansible playbook to simple do 

```
    - name: nginx load balancer
      docker:
        name: "{{ PROJECT_NAME }}_app_nginx_load_balancer"
        image: allansimon/nginx-load-balancer
        state: started
        ports:
            - "{{ PUBLIC_PORT }}:80"
        env:  {{ ALL_ENV }}   # <=  something like this 

```
