### ISSUE TITLE
copy fails when dest is hardlink

### ISSUE THREAD

**Issue by havlasme** [ansible/ansible#10834]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
1.9.0.1

##### SUMMARY
copy modules fails with message
`msg: absolute paths are required`
when I try to copy file over existing hardlink

task I'm trying to run looks like this:

```
  copy:
    dest: '/path/to/existing/hardlink'
    src: '/path/to/source/file'
    owner: 'root'
    group: 'root'
    mode: '0644'
```

I'm running version 1.9.0.1

**Comment by frntn** [comment]
Similar error with the `template` module.

Below an example to reproduce :

``` yaml
#repro.yaml
- name: create file from template
  template: src=example.txt.j2
            dest=/tmp/example.txt

- name: create hardlink
  file: state=hard
        src=/tmp/example.txt
        dest=/home/user/example.txt
```

First run is OK : two tasks appeared as changed & ok.
Second run is KO : the first task fails with the following error

```
fatal: [ǹodename]: FAILED! => {"changed": false, "failed": true, "msg": "src and dest are required for creating links"}
```

**Comment by LewisW** [comment]
Same is happening for us, when using ansible inside docker. Looks like this bug goes back [since Ansible 1.5](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/ansible-project/Ni6XRbm3_rc/ekOBGCJYexQJ). Anyone have any workarounds?

**Comment by semekh** [comment]
We are facing the same issue. Docker prefers `overlay` storage driver by default which uses hardlinks internally.
A workaround is to use an alternative storage driver, `aufs` seems to be a better alternative.

**Comment by semekh** [comment]
And apparently they (docker) already have a bug report for that: https://github.com/docker/docker/issues/16813

**Comment by gauthierm** [comment]
A workaround for this issue you can use with Ansible is:

### Failing code

``` yaml
 copy:
    dest: '/path/to/existing/hardlink'
    src: '/path/to/source/file'
    owner: 'root'
    group: 'root'
    mode: '0644'
```

### Workaround

``` yaml
 copy:
    dest: '/path/to/existing/hardlink'
    content: "{{ lookup('file',  '/path/to/source/file') }}"
    owner: 'root'
    group: 'root'
    mode: '0644'
```

With a variable for the filename, it looks like `"{{ lookup('file', item) }}"`

**Comment by kepi** [comment]
Same problem here. Workaround is working for us but I dont think that should be long-term solution.

**Comment by garthk** [comment]
Verification: `stat /path/to/target` and look for the `Links:` number. If it's more than 1,

```
  File: ‘/path/to/target’
  Size: 2094        Blocks: 8          IO Block: 4096   regular file
Device: ca01h/51713d    Inode: 32576       Links: 2
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (   50/   staff)
Access: 2016-10-12 10:00:59.362280999 +0000
Modify: 2016-08-16 16:03:55.526806000 +0000
Change: 2016-08-29 16:46:23.963746467 +0000
```

You can find the other directory entries pointing to the same inode with:

```
find / -samefile /path/to/target
```

The easiest solution is probably `rm /path/to/target` and re-run the Ansible play that's trying to `copy` to it. If it keeps happening to you, try the [`lookup` workaround](https://github.com/ansible/ansible/issues/10834#issuecomment-196991109) above.

**Comment by jctanner** [comment]
@tomashavlas @garthk I'm not able to create any errors on 1.9.x or in 2.x based on the description. Here's my testcase ...

```
- hosts: el7host
  user: root
  gather_facts: False
  tasks:

    - name: cleanup old files
      shell: rm -rf /tmp/afile /tmp/ahardlink
      changed_when: false

    - name: create the linked file
      copy:
        content: 'foobar'
        dest: /tmp/afile

    - name: create the hard link(s)
      shell: if [ ! -f {{ item }} ]; then ln /tmp/afile {{ item }} ; fi
      changed_when: false
      with_items:
        - /tmp/ahardlink
        - /tmp/ahardlink2
        - /tmp/ahardlink3

    - name: copy content to the hardlink
      copy:
        dest: /tmp/ahardlink
        content: 'foo2'

    - name: copy a file to the hardlink
      copy:
        src: somedata.txt
        dest: /tmp/ahardlink
        owner: root
        group: root
        mode: 0644
```

Could you help me by pointing out where my testcase doesn't fit the description?

needs_info

**Comment by havlasme** [comment]
@jctanner I can't replicate error using your test case nor with my test, using latest versions of ansible (tried 1.9.6@debian8 and 2.1.2@centos7).

However there is still something odd, after copying content to file I believe that hardlink is broken because running

```
ls -i /tmp/afile /tmp/ahardlink /tmp/ahardlink2 /tmp/ahardlink3
```

displays different inode number for `/tmp/ahardlink`.

I think this might be correct behavior because I found that there is a `follow` option for `copy` module according to docs (http://docs.ansible.com/ansible/copy_module.html). Yet, when I try to add `follow: yes` to both `copy` blocks in your test case the hardlink is still broken. I'm not sure if this might be related?

**Comment by kwerey** [comment]
I just ran into this... I think using copy with `content` behaves differently to copy with a source file, and that might be why @jctanner 's test case doesn't capture the error: 

I can reproduce it with this:

```
- name: minimal reproducible example of hardlink weirdness
  hosts: cobbler-server-vm

  tasks:
  - name: Create an example file locally
    local_action:
      module: copy
      content: "example file!"
      dest: "{{ playbook_dir }}/example"

  - name: Clean up stray files
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /tmp/example
    - /tmp/example.hard-link

  - name: Copy file over once.
    copy:
      src: "{{ playbook_dir }}/example"
      dest: /tmp/example
      mode: "0644"

  - name: Create a hardlink it.
    file:
      src: /tmp/example
      dest: /tmp/example.hard-link
      state: hard

  - name: Attempt to update the original file.
    copy:
      src: "{{ playbook_dir }}/example"
      dest: /tmp/example
      mode: "0644"
```

On devel:

```
(virtualenv-ansible-devel) ukch-ofclt2473:cobbler-test-environment nbailey$ ansible --version
ansible 2.3.0 (devel 35f6fb1383) last updated 2017/01/12 14:53:50 (GMT +100)
  config file = /Users/nbailey/automation/cobbler-test-environment/ansible.cfg
  configured module search path = Default w/o overrides
```

The error occurs when copy calls the file module and passes its parameters over - despite passing an absolute path as the source parameter, file tells us: "absolute paths are required";

By setting `export ANSIBLE_KEEP_REMOTE_FILES=1` and expanding the results, I can see that the source parameter *as seen by the file module on the remote machine* is the same as the original_basename parameter. See `"src": "example"` in the args output below, instead of `"src":"/tmp/example"`?

`{"ANSIBLE_MODULE_ARGS": {"_ansible_version": "2.3.0", "_ansible_selinux_special_fs": ["fuse", "nfs", "vboxsf", "ramfs"], "dest": "/tmp/example", "_ansible_syslog_facility": "LOG_USER", "original_basename": "example", "_ansible_check_mode": false, "src": "example", "_ansible_no_log": false, "_ansible_module_name": "file", "_ansible_verbosity": 4, "_ansible_diff": false, "mode": "0644", "_ansible_debug": false}}`

I can't see why that'd happen - the module-params for the invocation of copy definitely have the full path. But there's a utility function called load_file_common_arguments somewhere in module_utils that might be doing something odd here...
