### ISSUE TITLE
feature request: Allow module defaults to be set in config file

### ISSUE THREAD

**Issue by ceedon** [ansible/ansible#10849]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.0

##### SUMMARY
A user should be able to set defaults for a module in a config file.

EG) 
in ~/.ansible.cfg

```
[apt]
cache_valid_time=360
```

**Comment by bcoca** [comment]
i would go more for

[apt]
cache_valid_time=360 

since it is an ini file and all that ....

**Comment by ceedon** [comment]
Good call.

**Comment by bcoca** [comment]
though  .... ini is not a good format for complex defaults ... now i'm thinking a:
module_defaults:

```
apt:
  cache_valid_time: 360
  name:
     - mysql-server
     - php-fpm
     - lighttpd
```

yes, taken the apt example a bit too far ...
