### ISSUE TITLE
Override of inventory_hostname stopped working

### ISSUE THREAD

**Issue by c0rner** [ansible/ansible#10869]
When doing overrides of `inventory_hostname` and `ansible_ssh_host` the `inventory_hostname` overrides stopped working resulting in a 'host not found' error.

Example inventory file:

``` ini
[test]
1.2.3.4
```

Example playbook demonstrating problem:

``` yaml

---
- hosts: all
  gather_facts: yes

  tasks:
  - set_fact: ansible_ssh_host="{{ ansible_default_ipv4.address }}"
  - set_fact: inventory_hostname="testname"
  - copy: content="test" dest=/tmp/test
```

Running the example playbook will result in the `copy` task failing with 'host not found'.
