### ISSUE TITLE
lineinfile module can not inserting double quotes at the beginning and end of the line

### ISSUE THREAD

**Issue by jaypei** [ansible/ansible#10864]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 1.9.0.1
  configured module search path = None
```
##### Environment:

Running on Arch Linux, managing CentOS 5 or Arch Linux.
##### Summary:

When using the lineinfile module with with double quotes at the beginning and end of the line, double quotes is missing.
Similar problems in #9171 and #8806, has still not been completely solved.
##### Steps To Reproduce:

$ cat site.yml

``` yaml

---
- hosts: localhost
  tasks:
  - name: insert a line into the quoted file with many double quotation strings
    lineinfile: dest=/tmp/myline.txt line="\"quote\" and \"unquote\"" create=yes
```
##### Expected Results:

$ cat /tmp/myline.txt

```
"quote" and "unquote"
```
##### Actual Results:

$ cat /tmp/myline.txt

```
quote" and "unquote
```
