### ISSUE TITLE
Password lookup plugin deletes salt in lookup file

### ISSUE THREAD

**Issue by redrampage** [ansible/ansible#10871]
Password lookup plugin deletes salt in lookup file. This leads to constant changed status when two tasks uses same lookup, one with 'encrypt' parameter, and other without.
For example:

``` yaml
tasks:
  - name: Create user
    user:
      password: "{{ lookup('password', inventory_dir + '/creds/user/pass' ncrypt=sha512_crypt) }}"
      ...
# Lookup file 'creds/user/pass' now contain password with salt
  - name: Create htpasswd
    htpasswd:
      password: "{{ lookup('password', inventory_dir + '/creds/user/pass') }}"
      ...
# Salt gets deleted from lookup file 'creds/user/pass'
# Next run will create it again and "Create user" task will have 'changed' status
```
