### ISSUE TITLE
New SSH connections opened even with ControlPersist=600s and pipelining=True

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible#10886]
Issue Type: Bug Report
Ansible Version: 1.9.1
Environment: CentOS 7.1 x86_64 running on both controller and hosts (openssh-6.6.1p1-11)
Summary: New SSH connection are opened for every task executed (monitored with ps)
Steps to Reproduce:

ansible.cfg:

```
[defaults]
host_key_checking = False
retry_files_enabled = False
fact_caching = redis
fact_caching_timeout = 86400
forks = 50

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=600s
pipelining = True
```

example-playbook.yml

```
- name: test persistent ssh connection
  hosts: all
  sudo: yes
  vars:
    some_list:
      - "a"
      - "b"
      - "c"
  tasks:
    - command: "/bin/echo test"
      with_items: some_list
```

Gather facts and each new command opens a new SSH connection.

Example with -vvvv (each task runs this command, each task opens a new SSH connection):

```
<10.0.0.1> ESTABLISH CONNECTION FOR USER: gtirloni
<10.0.0.1> REMOTE_MODULE command /usr/bin/dd if=/dev/zero of=/dev/sdl bs=512 count=1
<10.0.0.1> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=600s -o ControlPath="/home/gtirloni/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o Port=7022 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 10.0.0.1 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=jathqtpyyfdjwbjyicbdzpargijdauto] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-jathqtpyyfdjwbjyicbdzpargijdauto; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
```
