### ISSUE TITLE
Ansible Ec2 tags in roles being ignored

### ISSUE THREAD

**Issue by steven-quan** [ansible/ansible#10889]
Hi,

I am currently working on an ansible playbook to provision an ec2 instance

it seems that after the ec2 instance has been provisioned the roles specified has been run but the tags associated with the role specified are being ignored:

example playbook:

```

---
- name: launch the ec2 instance
  hosts: localhost
  connection: local
  gather_facts: false

tasks:
    - name: provision ec2 instance
      ec2:
          <ec2 details here>
      sudo: no
      register: ec2

    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groups=groupname ansible_ssh_private_key_file="ec2 ssh key"
      with_items: ec2.instances

    - name: wait for ssh on the ec2 instance
      wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances- name: configuration play

- name: configuration play
   hosts: groupname
   user: username
   gather_facts: true
   sudo: true

  roles:
    - { role: rolename, tags: ["tag1", "tag2"] }
```

ansible version 1.9.1 

regards
Steven
