### ISSUE TITLE
get_url fails to split headers correctly when extra commas are present

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#10902]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.1

##### SUMMARY
Updated, as this is no longer a feature but relates to a bug in the feature as it exists (see below for relevant comments)

**Comment by danpilch** [comment]
created a pull request for this feature here: https://github.com/danpilch/ansible-modules-core/commit/15a432362b6af1b2a781c8555912d8b8b75c3e49

**Comment by danpilch** [comment]
Sorry, I merged to my own branch at first! Here's a pull request: https://github.com/ansible/ansible-modules-core/pull/1261/files

**Comment by ivn86** [comment]
Thank you, @danpilch! Now it is so easy:

```
- name: Download Oracle JRE
  get_url:
    url={{ jre_url }}
    dest=/var/local
    headers='Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
```

**Comment by offlinehoster** [comment]
@ivn86 not working with ansible 2.1.0.0

**Comment by emielmolenaar** [comment]
Running latest version from git here, getting

`The header parameter requires a key:value,key:value syntax to be properly parsed.`

While using the following get_url parameters:

```
- name: Download PhpStorm archive for version "{{ phpstorm_version }}"
  get_url:
    headers: "User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36"
    url: http://download-cf.jetbrains.com/webide/PhpStorm-"{{ phpstorm_version }}".tar.gz
    dest: "{{ phpstorm_archive }}"
  when: phpstorm_exist.stat.exists == False
```

What is going wrong here?

**Comment by chrisdutz** [comment]
Having the same problem ...

**Comment by ivn86** [comment]
@offlinehoster Just now tested with ansible 2.2.0.0:

```
- name: Download Oracle JRE
get_url:
  url=http://download.oracle.com/otn-pub/java/jdk/8u102-b14/jdk-8u102-linux-x64.rpm
  dest=/tmp
  headers='Cookie:gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
```

Archive versions of JRE require to be logged in, so the code above works only with current ones.

**Comment by ivn86** [comment]
@emielmolenaar 

> What is going wrong here?

I think the problem in comma after "KHTML", so "like" becomes new key and needs new value. BTW, you don't need to setup custom headers for downloading PHPStorm.

**Comment by camilosantana** [comment]
this worked for me

```
$ ansible --version
ansible 2.2.0.0
```
```- name: download Oracle JDK rpm (about 160MB) to /tmp
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.rpm
    dest: /tmp
    mode: 0444
    headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
```

**Comment by jimi-c** [comment]
Yes, most likely the issue here is just the comma messing up the splitting of the string. Here is the relevant code:
<pre>
        try:
            headers = dict(item.split(':', 1) for item in module.params['headers'].split(','))
        except:
            module.fail_json(msg="The header parameter requires a key:value,key:value syntax to be properly parsed.")
</pre>
Not sure how we can make that better easily. Really the param type should have been a dict type, thus allowing the full YAML syntax to be used instead of a comma-separated string.

**Comment by jimi-c** [comment]
I've edited the title and description and re-labeled as this is a bug in the feature and no longer a feature request.

**Comment by alikins** [comment]
One (ugly) other way to parse that headers string:

``` python
import itertools
<...>

terms = module.params['headers']
split_terms = [x.rsplit(',', 1) for x in terms]
headers = dict(zip([x for x in itertools.chain(*split_terms)][::2], [x for x in itertools.chain(*split_terms)][1::2]))

```

Example:

``` python
>>> module_params['headers'] = 'X-A: foo, X-B: blip, not_a_header, X-C: the_c_value'
>>> print module_params
{'headers': 'X-A: foo, X-B: blip, not_a_header, X-C: the_c_value'}
>>> terms = module_params['headers'].split(':')
>>> print terms
['X-A', ' foo, X-B', ' blip, not_a_header, X-C', ' the_c_value']
>>> split_terms = [x.rsplit(',', 1) for x in terms]
>>> print split_terms
[['X-A'], [' foo', ' X-B'], [' blip, not_a_header', ' X-C'], [' the_c_value']]
>>> headers = dict(zip([x for x in itertools.chain(*split_terms)][::2], [x for x in itertools.chain(*split_terms)][1::2]))
>>> print headers
{' X-C': ' the_c_value', ' X-B': ' blip, not_a_header', 'X-A': ' foo'}
```

**Comment by ansibot** [comment]
@edrozenberg Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by angystardust** [comment]
Hey guys, any workaround to get this work?
I'm strugging with this simple use-case:

example playbook:

```
- uri:
    url: https://mysite.com/cgi-bin/account_verify.php
    method: POST
    body: username=user&password=mypass
    status_code: 302
    headers:
      Content-Type: "application/x-www-form-urlencoded"
  register: login

- get_url:
    url: https://mysite.com/cgi-bin/download.php
    dest: /tmp/file.tar.gz
   #headers: '"Cookie:{{ login.set_cookie }}"'
```

Output:

```
TASK [myfedora : debug] ********************************************************
ok: [localhost] => {
    "login.set_cookie": "PHPSESSID=78a27ounmr7ik3qnrmj22mhnq2; path=/, ID=51E7553555111F2631D6; expires=Tue, 23-Apr-2019 06:00:00 GMT; Max-Age=63005456; path=/; domain=.example.com"
}
TASK [myfedora : get_url] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The header parameter requires a key:value,key:value syntax to be properly parsed."}

```
As you can notice, both the **ID** and the **expires** cookies have a comma inside the value and that's why the get_url module complains
