### ISSUE TITLE
copy with content doesn't update the file when content changes.

### ISSUE THREAD

**Issue by benallard** [ansible/ansible#10911]
I have a copy task with a content, the content was wrong, I fixed it, re-ran my playbook, and the file was not updated, same with `force: yes`, no changes happened (expected as `yes` is the default).

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by benallard** [comment]
I'm sorry, but either it's a documentation issue, or it's a bug in the module, but it's not a user question !

**Comment by benallard** [comment]
Using ansible 1.7.2 (debian wheezy)

Example:

```
- name: a simple copy with content
  copy:
    dest: /home/ben/myfile
    content: |
      this is the contennnt of my file
```

Run ansible, ansible-playbook whatever ... The file get created with the content as specified in the content attribute, task has state `changed`. Great !

Oh wait ... I realize I made a typo ! let's fix it: (replace the previous task definition with the following one)

```
- name: a simple copy with content
  copy:
    dest: /home/ben/myfile
    content: |
      This is the fixed content of my file.
```

Run ansible again, oh, the task is green (not changed) ! Look at the content of your file ... Gasp ! The file has not been updated ! I bet I found a bug ...
