### ISSUE TITLE
Task in playbook not run with sudo

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#10936]
**Issue Type**
Bug report

**Ansible Version**
`ansible 2.0.0 (devel 374ea10e6f) last updated 2015/05/06 16:00:33 (GMT -700)`

**Environment**
Running from OSX 10.10.1 to ubuntu 14.04

**Summary**
Task in playbook ignores `Sudo: True`

**Steps to Reproduce**

```
- name: Run tasks that require reboot
  hosts: all
  sudo: True
  gather_facts: True
  tasks:
    - name: disable transparent_hugepage settings
      lineinfile:
        dest: "/sys/kernel/mm/transparent_hugepage/{{ item }}"
        regexp: "always"
        line: "never"
      with_items:
        - enabled
        - defrag
```

**Expected Results**
Task runs fine

**Actual Results**
`msg: The destination directory (/sys/kernel/mm/transparent_hugepage) is not writable by the current user.`

Tried with `sudo: yes` in the task as well.
