### ISSUE TITLE
Add support for HTTPS proxies

### ISSUE THREAD

**Issue by aseigneurin** [ansible/ansible#10941]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

1.9

##### SUMMARY
Using Ansible 1.9.0.1, HTTPS proxies are not supported. This is an issue for simple things such as downloading a file with the `get_url` module:

```
- name: Download Elasticsearch.
  get_url: 
    url: "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.5.2.tar.gz"
    dest: "/tmp/elasticsearch-1.5.2.tar.gz"
```

This generates the following error:

```
TASK: [elasticsearch | Download Elasticsearch.] *******************************
failed: [127.0.0.1] => {"failed": true}
msg: Unsupported proxy scheme: https. Currently ansible only supports HTTP proxies.

FATAL: all hosts have already failed -- aborting
```

Looks like the issue lies in https://github.com/ansible/ansible/blob/0951a74ea0f12b7426817ab5a915e2853502bc01/lib/ansible/module_utils/urls.py#L297

**Comment by mightydok** [comment]
@aseigneurin you can download files from https sites via http proxy, ansible support CONNECT method to https sites. But your proxy must allow CONNECT for host to 443 port.
Ther is example of working playbook:

```
---
- hosts: test

  tasks:
  - name: Download Elasticsearch.
    get_url:
      url: "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.5.2.tar.gz"
      dest: "/tmp/elasticsearch-1.5.2.tar.gz"

    environment:
      http_proxy: http://127.0.0.1:8888
      https_proxy: http://127.0.0.1:8888
```

On 8888 port working tinyproxy with settings below:

```
ConnectPort 443
```

**Comment by aseigneurin** [comment]
Thank you @mightydok for this precision. I'm not sure I get it, though. Does that require me being able to configure the proxy? As a matter of fact, I cannot configure it because this is a company-wide proxy.

**Comment by mightydok** [comment]
@aseigneurin nope, you can use your corporate HTTP proxy for https downloads.

**Comment by mightydok** [comment]
@bcoca maybe rewrite http_request with http://requests.readthedocs.org/en/latest/ lib?

**Comment by aseigneurin** [comment]
@mightydok Sorry, I still don't get... If I'm using my corporate proxy, where do I use the "ConnectPort 443" instruction?

**Comment by mightydok** [comment]
@aseigneurin "ConnectPort 443" its for tinyproxy settings, you dont need it. I paste it like example configuration for opensource proxy.

If you need to download file from https you can set HTTP proxy, if your company have it.

Like here:

```
---
- hosts: test

  tasks:
  - name: Download Elasticsearch.
    get_url:
      url: "https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-1.5.2.tar.gz"
      dest: "/tmp/elasticsearch-1.5.2.tar.gz"

    environment:
      http_proxy: http://127.0.0.1:8888
      https_proxy: http://127.0.0.1:8888
```

As you see proxy URL - http://
My native language russian, so i dont know english very well =(, but you can write me email.

**Comment by aseigneurin** [comment]
Well, that's exactly what is not working: the URL is HTTPS, so Ansible is using the HTTPS proxy, but the code is actually not ready to use HTTPS proxies :-/

**Comment by mightydok** [comment]
@aseigneurin it works, ansible can use http proxy for https download, just run my playbook above.

**Comment by aseigneurin** [comment]
Knowing that I'm using a corporate proxy that I cannot re-configure, and that I cannot use another intermediate proxy, I don't see how to make that work.

See this screenshot where I'm using the same playbook as yours except I've changed the proxy settings and the target host:

![proxy](https://cloud.githubusercontent.com/assets/4038960/7681729/c07f1a18-fd72-11e4-815f-52efd8ddcb90.png)

**Comment by mightydok** [comment]
@aseigneurin u can use same HTTP proxy for HTTPS links. Just define https_proxy: http://blabla@srvproxy.blabla:9707 and thats all.

**Comment by aseigneurin** [comment]
I just tried that and, no, that does not work.

![capture d ecran 2015-06-01 15 43 08](https://cloud.githubusercontent.com/assets/4038960/7914090/f5cbbef8-0874-11e5-9f45-3e34a014861a.png)

This really seems to require a change in Ansible's code base.

**Comment by shaleh** [comment]
I ran into this exact problem this morning. I do not need to authenticate to my proxy server. As a test I went to /usr/shared/pyshared/ansible/module_utils/ and edited urls.py.

```
--- urls_orig.py    2015-07-29 10:46:21.632281542 -0700
+++ urls.py 2015-07-29 10:46:34.052347390 -0700
@@ -477,7 +477,7 @@
             if https_proxy:
                 proxy_parts = generic_urlparse(urlparse.urlparse(https_proxy))
                 s.connect((proxy_parts.get('hostname'), proxy_parts.get('port')))
-                if proxy_parts.get('scheme') == 'http':
+                if True:  # proxy_parts.get('scheme') == 'http':
                     s.sendall(self.CONNECT_COMMAND % (self.hostname, self.port))
                     if proxy_parts.get('username'):
                         credentials = "%s:%s" % (proxy_parts.get('username',''),  proxy_parts.get('password',''))
```

This worked for me. Perhaps this check could be relaxed?

If not, maybe it is time to migrate to the Requests module?

**Comment by gouyang** [comment]
+1  I've met the same problem that ansible only supports HTTP proxies. 

> @aseigneurin you can download files from https sites via http proxy, ansible support CONNECT method to https sites. But your proxy must allow CONNECT for host to 443 port.

The proxy is not owned by me and it does not support 443 port, so it's impossible to use this workaround.

Hope this problem get fixed soon!

**Comment by abadger** [comment]
I'm not sure if we are all using the same terminology and describing the same bug here.  For the people who try @shaleh's code sample and that makes the configuration work, what's needed is the ability to connect to a proxy which serves over https.  ie: the connection from the client to the proxy is https.  The connection from the proxy to the actual web server with the content does not matter.

I'm asking @jimi-c if he knows of a reason why we don't currently support that.  It could be that we would need to implement another layer of wrapping around the connection to the proxy so that we verify the proxy's TLS certificate is valid.  That could get messy but at least it would lay out a roadmap for someone to implement.  (Without that wrapping, I'm guessing that the connection between the client and the proxy is subjet to man-in-the-middle attacks.  Not sure if that's a problem for proxies which are only doing CONNECT proxying to remote https serving servers... theoretically, the only public data that a man-in-the-middle proxy would be able to intercept would be which server the client is contacting.  Everything else would be encrypted.)

Now if anyone's issue does not seemingly go away when @shaleh's change is applied, then there's something very different being asked for there.  I'm not sure I know what that is.  i'll need more information about how to configure a proxy to test against in order to figure that out.

Lastly, note that some of the things being said here are misunderstandings of what other people are saying about https proxies.  For instance, an https proxy really must support port 443 otherwise it would be nearly useless.  And unless it's an extremely limited use proxy (most likely only for a few internal web services) it will support CONNECT as well.  However, these are statements about the proxy to web server connection.  I have a feeling that some people are thinking that these are statements about the client to proxy connection which would be the source of the misunderstanding.

The client to proxy connection can be over only http or only https  or over either http or https and on any port.  This is all independent of how the content is served from the third party web server.  Most sites will have a single proxy server that serves on just http or on both http and https.  It will proxy for both web sites that are serving via http and via https.  That's why @mightydok is saying that you can most likely configure the http_proxy and https_proxy environment variables to use the same http://servername:port value.  At most sites that would work.  But any particular site can have separate http and https proxy servers that they configure to only serve for a specific protocol.  If you've tried setting https_proxy to the same value as http_proxy and can get http urls but not https urls then that's likely what your site is doing.  I can't think of how that actually buys a site better security but it doesn't mean those sites don't exist...

**Comment by gouyang** [comment]
it works by specifying both environment and validate_certs=False.

```
---
- hosts: atomic
  sudo: yes
  tasks:
  - name: download file
    get_url:
      url: https://raw.githubusercontent.com/GoogleCloudPlatform/kubernetes/master/cluster/addons/fluentd-elasticsearch/es-controller.yaml
      dest: /tmp
      validate_certs: False

    environment:
      http_proxy: http://squid.example.com:3128
      https_proxy: https://squid.example.com:3128
```
