### ISSUE TITLE
Add ability to control host order

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#10964]
**Issue Type**
Bug report

**Ansible Version**
`ansible 2.0.0 (devel 374ea10e6f) last updated 2015/05/06 16:00:33 (GMT -700)`

**Environment**
OSX 10.10.1 to Ubuntu 14.04

**Summary**
When using `Serial: 1`, Ansible runs on hosts in seemingly random order when there are numbers at the end of the group name (sometimes??)

**Steps To Reproduce**

``` yaml
  hosts: all
  sudo: True
  serial: 1
  gather_facts: True
```

``` yaml
[replica1]
52.4.196.227
52.6.65.189

[arbiter1]
52.5.245.103
```

**Expected Result**
52.4.196.227 then 52.6.65.189 then 52.5.245.103

**Actual Result**

``` yaml
TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.5.245.103] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.4.196.227] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.6.65.189] => {
    "msg": "This is the run order"
}
```

**With no numbers**

``` yaml
[replica]
52.4.196.227
52.6.65.189

[arbiter]
52.5.245.103
```

``` yaml
TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.4.196.227] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.6.65.189] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.5.245.103] => {
    "msg": "This is the run order"
}
```

**With different numbers????**

``` yaml
[replica9]
52.4.196.227
52.6.65.189

[arbiter1]
52.5.245.103
```

``` yaml
TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.5.245.103] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.4.196.227] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.6.65.189] => {
    "msg": "This is the run order"
}
```

**With 6's?!**

``` yaml
[replica6]
52.4.196.227
52.6.65.189

[arbiter6]
52.5.245.103
```

``` yaml
TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.4.196.227] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.6.65.189] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.5.245.103] => {
    "msg": "This is the run order"
}
```

**9's?**

``` yaml
[replica9]
52.4.196.227
52.6.65.189

[arbiter9]
52.5.245.103
```

``` yaml
TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.5.245.103] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.4.196.227] => {
    "msg": "This is the run order"
}

TASK: [csm.mongo | debug msg='This is the run order'] *************************
ok: [52.6.65.189] => {
    "msg": "This is the run order"
}
```

**Am I crazy?**

**Previous "fix":** https://github.com/ansible/ansible/commit/ca6db40cb4f7da7d5a57b951bf99b5782e7a675d

**Comment by bcoca** [comment]
the groups become python dictionaries, these are not guaranteed order so I'm reclassifying this as feature request of something that has been on my list for a while:

host_order: inventory(default)|sorted|revresed|numeric|numeric_reverse|shuffle

**Comment by MrMMorris** [comment]
so this issue was not actually fixed? https://github.com/ansible/ansible/issues/8646

**Comment by bcoca** [comment]
well, if i read it correctly, that gave reproducible order, still not very predictable based on group name merging.

**Comment by MrMMorris** [comment]
alright, well big +1 for the feature!

**Comment by mightydok** [comment]
@bcoca what correct behaviour for numeric and numeric_reverse?

**Comment by bcoca** [comment]
@mightydok not sure what you are asking

**Comment by mightydok** [comment]
@bcoca i mean algoritm, i dont understand what sort algoritm for this sort orders.

**Comment by bcoca** [comment]
lets see if this explains it, given the same list  [120, 1, 13, 10, 11, 2]

normal sort (alphanumeric):
1, 10, 11, 120, 13, 2

numeric sort:
1, 2, 10, 11, 13, 120

## So it depends if you compare characters or numeric values.

Brian Coca

**Comment by samdoran** [comment]
I'd love to see this feature added as well. We need this for very detailed orchestration, e.g., restarting servers in a very specific order.

**Comment by JLofgren** [comment]
How is this new feature actually used?  It's not clear.  Can we have an example?

**Comment by Cougar** [comment]
This is how should it work I guess (if I use wrong `order` value, I get error which mean that this option gets used in `get_hosts()`):

```yaml
#!/usr/bin/env ansible-playbook

- name: Test
  hosts: all
  serial: 1
  order: sorted
  gather_facts: no

  tasks:
    - debug:
        msg: "{{ vars }}"
```

However, I use ansible-playbook 2.7.0 and the play order is still not sorted.
