### ISSUE TITLE
'Host facts' treated as undefined by default filter when passed to parameterized roles

### ISSUE THREAD

**Issue by bobobox** [ansible/ansible#10980]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.1, 2.0.0 (tested with devel ded6e9be67)
##### Ansible Configuration:

Defaults
##### Environment:

N/A (Issue seen on Mac OS X 10.10.3 as well as Ubuntu Linux 14.04 - I don't think it is OS related)
##### Summary:

When a 'discovered host fact' or a variable set using the `set_fact` module gets passed to a parameterized role from a playbook, and a `default` filter is used on it in the playbook, the default filter gets triggered as if the variable was undefined.
##### Steps To Reproduce:
1. Create role that uses a variable (see example below).
2. Invoke the role in a playbook as a 'parameterized role', setting the value of that varaiable to a defined host fact, with a default filter.
3. Observe the value for that variable within the role.

Example playbook and role to demonstrate bug, showing some examples of where it does and does not occur:

`roles/test_role/tasks/main.yml` file content:

```

---

- name: Display variable as received by role
  debug:
    msg: "{{ message }}: {{ var_in_role }}"
```

Playbook to demonstrate behavior with `test_role`:

```
- name: Demonstrate 'parameterized-role/host-fact/default-filter' bug
  hosts: localhost
  gather_facts: yes 
  vars:
    # set my_var_1 as a variable for the play
    my_var_1: apple
  pre_tasks:
    # set 'my_var_2' as a host fact in pre_tasks.
    - set_fact:
        my_var_2: banana
  roles:
    # In none of these cases should the default value be used:
    - role: test_role
      message: Value of my_var_1, set in play vars, passed to role without default() filter
      var_in_role: "{{ my_var_1 }}"
    - role: test_role
      message: Value of my_var_1, set in play vars, passed to role with default() filter
      var_in_role: "{{ my_var_1 | default('DEFAULT VALUE') }}"
    - role: test_role
      message: Value of my_var_2, set as host fact in 'pre_tasks', without default() filter
      var_in_role: "{{ my_var_2 }}"
    - role: test_role
      message: Value of my_var_2, set as host fact in 'pre_tasks', with default() filter
      var_in_role: "{{ my_var_2 | default('DEFAULT VALUE') }}"
    - role: test_role
      message: Value of 'ansible_hostname', discovered automatically, without default() filter
      var_in_role: "{{ ansible_hostname }}"
    - role: test_role
      message: Value of 'ansible_hostname', discovered automatically, with default() filter
      var_in_role: "{{ ansible_hostname | default('DEFAULT VALUE') }}"
```
##### Expected Results:

If the variables are defined, the role should always receive the value in the variables, not the 'default' values. In the example role and playbook, we should never see 'DEFAULT VALUE' printed.
##### Actual Results:

For certain facts (discovered facts or fact set with the 'set_fact'module) the default value in the variable gets erroneously applied, as if the variable had been undefined. The role gets passed 'DEFAULT VALUE' instead of the correct value of the variable.
