### ISSUE TITLE
Error: "No such file or directory" during provision with docker_image

### ISSUE THREAD

**Issue by bocharsky-bw** [ansible/ansible#10987]
When I do `vagrant provision` using `Ansbile` as provisioner, I get next error:

``` bash
failed: [default] => {"changed": false, "failed": true}
msg: ConnectionError(ProtocolError('Connection aborted.', error(2, 'No such file or directory')),)

FATAL: all hosts have already failed -- aborting
```

My ansible playbook file is:

``` yaml

---
-   name: Vagrant provisioning using Ansible Playbook for Ubuntu 14.04
    hosts: all
    sudo: yes
    tasks:
        - name: check or build nginx image
          docker_image: path="/vagrant/docker/nginx" name="my/nginx" state=build
```

The `/vagrant/` dir is mount with vagrant as `nfs`. On VM `Dockerfile` exists by `/vagrant/docker/nginx/Dockerfile` path.

Is this a bug? Or I do something wrong with `docker_image: path` config?
