### ISSUE TITLE
BUG: vars not merged for included playbooks (1.9.1)

### ISSUE THREAD

**Issue by wojtek-oledzki** [ansible/ansible#10992]
Ansible version: 1.9.1
OS: osx 10.10

extra vars are not merged with vars defined in playbooks included from the main playbook. Instead the extra_vars replaces entire dict :(

Expected

```
ansible-playbook ... -e '{ "test": { "a": "A" } }' test.yml

TASK: [debug] *****************************************************************
ok: [default] => {
    "test": {
        "a": "A",
        "b": "B"
    }
}
TASK: [sub-include debug] *****************************************************
ok: [default] => {
    "test": {
        "a": "A",
        "b": "C"
    }
}
```

Actual

```
ansible-playbook ... -e '{ "test": { "a": "A" } }' test.yml

TASK: [debug] *****************************************************************
ok: [default] => {
    "test": {
        "a": "A",
        "b": "B"
    }
}
TASK: [sub-include debug] *****************************************************
ok: [default] => {
    "test": {
        "a": "A",   <== Just "A" - merged behaviour is not used for playbook includes ?
    }
}
```

test.yml

``` YML
- name: test
  hosts: all
  vars:
    test:
      b: B
  tasks:
    - name: debug
      debug: var=test

- name: another include
  include: test_include.yml
```

test_include.yml

``` YML
- name: test
  hosts: all
  vars:
    test:
      b: C
  tasks:
    - name: sub-include debug
      debug: var=test
```
