### ISSUE TITLE
BUG: One or more undefined variables: 'builtin_function_or_method object' has no attribute

### ISSUE THREAD

**Issue by szibis** [ansible/ansible#11008]
##### Issue type:

Bug report
##### Ansible version:

From (maybe even lower) 1.5+ to latest 1.9.1
##### Ansible configuration:

``` bash
[defaults]
host_key_checking = False
jinja2_extensions=jinja2.ext.do,jinja2.ext.loopcontrols
hash_behaviour=merge
sudo_user=root
user=root
sudo_exe=sudo
roles_path=./roles
display_skipped_hosts = False
timeout = 60
nocows = 1
[ssh_connection]
control_path=/tmp/ansible-%%h-%%p-%%r
ssh_args=-o ControlMaster=auto -o ControlPersist=120s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r
pipelining = True
```
##### Environment:

Mac OS X 10.10.3 and Ubuntu Precise 12.04 Server, Ubuntu Trusty 14.04 Server
##### Summary:

 Vars from yaml are failing when using get as key name in yaml structure like bellow.
##### Steps To Reproduce:

We have playbook test.yml:

``` yaml

---
- name: test get
  hosts: localhost
  gather_facts: false
  vars:
    test:
      get:
        size: "1000"
        something: "5000"
  tasks:
    - template: src=test.j2 dest=/tmp/test
```

and template test.j2:

``` jinja
{{ test.get.size }}
{{ test.get.something }}
```
##### Actual results:

``` bash
PLAY [test get] ***************************************************************

TASK: [template src=test.j2 dest=/tmp/test] ***********************************
fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'builtin_function_or_method object' has no attribute 'size'", 'failed': True}
fatal: [localhost] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'builtin_function_or_method object' has no attribute 'size'", 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/slawomirskowron/test.retry

localhost                  : ok=0    changed=0    unreachable=1    failed=0
```
##### Expected results:

When i use this playbook with get key renamed to nget, or something different then get then all is ok.

Playbook:

``` yaml

---
- name: test get
  hosts: localhost
  gather_facts: false
  vars:
    test:
      nget:
        size: "1000"
        something: "5000"
  tasks:
    - template: src=test.j2 dest=/tmp/test
```

template:

``` jinja2
{{ test.nget.size }}
{{ test.nget.something }}
```

Output:

``` bash
PLAY [test get] ****************************************************************

TASK: [template src=test.j2 dest=/tmp/test] ***********************************
--- before
+++ after
@@ -1 +1,2 @@
-test
+1000
+5000

changed: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
well, get is a reserved keyword in python used for retrieving information from data structures, don't use it.

**Comment by szibis** [comment]
Yes, sure and it is different in many situations.

With such yaml and template:

``` yaml
---
- name: test get
  hosts: localhost
  gather_facts: false
  vars:
    get: "10"
    get:
      get: "10"
    test:
      nget:
        size: "1000"
        something: "5000"
  tasks:
    - template: src=test.j2 dest=/tmp/test
```

``` jinja2
{{ get }}
{{ get.get }}
{{ test.nget.size }}
{{ test.nget.something }}
```

``` bash
TASK: [template src=test.j2 dest=/tmp/test] ***********************************
--- before
+++ after
@@ -1,2 +1,4 @@
+{'get': '10'}
+<built-in method get of dict object at 0x7faa2343f880>
 1000
 5000

changed: [localhost]
```

I have write simple test python with jinja2 templates and this is behavior of jinja2 itself. 
Python gets value of get key with no problems, but true this should not be used as variable. 
I think case closed, thanks.
