### ISSUE TITLE
ec2_vol: msg: Found more than one volume in zone (if specified) with name: None

### ISSUE THREAD

**Issue by webslice** [ansible/ansible#11026]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

ec2_vol module
##### ANSIBLE VERSION

ansible-1.9.1
##### SUMMARY

When creating a volume with:

```
- name: Create volume test
  local_action:
     module: ec2_vol
     aws_access_key: '{{ aws_access_key }}'
     aws_secret_key: '{{ aws_secret_key }}'
     region: '{{ region }}'
     zone: '{{ availability_zone }}'
     volume_size: "5"
```

The volume gets created, but the module fails with:

msg: Found more than one volume in zone (if specified) with name: None

reverting back to 1.8.4, and I get no error.

**Comment by bennojoy** [comment]
@webslice the reason this is happening is because the module sees multiple volumes of size 5GB and has no way to know, which volume is being reffered in the module. 
This has been fixed in 1.9 and devek where a 'name' tag can be specified to identify the disk uniquely.
so of you add the parmater 'name: foo' to you above task , things shoudl work as normal.

**Comment by webslice** [comment]
I'm not sure I understand, the above action is to create a new unattached volume, so there is no referral to an existing volume.
Adding a 'name tag' is to attach an existing volume to an instance. "volume Name tag if you wish to attach an existing volume (requires instance) (added in Ansible 1.6)"

**Comment by bennojoy** [comment]
@webslice in 1.8 if we execute that playbook multiple times, it would create the volume each time the playbook gets executed, which would not make the task idempotent, with 1.9 and a latest commit in devel, if name is specified and instance is none , the volume would be created and the task would be idempotent by verifying the name tag

**Comment by webslice** [comment]
Understand the idea, but of course tried that before posting this issue;

msg: Cannot specify volume_size and either one of name or id

```
- name: Create volume test
  local_action:
    module: ec2_vol
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    zone: '{{ availability_zone }}'
    name: 'testvolume of 5GB'
    volume_size: "5"
```

**Comment by webslice** [comment]
and before you come back with the uniqueness of unlabeled volumes with same sizes;

I surely not have any other 123GB volume.

msg: Found more than one volume in zone (if specified) with name: None

```
- name: Create volume test
  local_action:
    module: ec2_vol
    aws_access_key: '{{ aws_access_key }}'
    aws_secret_key: '{{ aws_secret_key }}'
    region: '{{ region }}'
    zone: '{{ availability_zone }}'
    volume_size: "123"
```
