### ISSUE TITLE
flush_handlers not working as expected

### ISSUE THREAD

**Issue by adrienkohlbecker** [ansible/ansible#11025]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.1
##### Ansible Configuration:

```
[defaults]
log_path=/tmp/ansible.log
host_key_checking=False
pipelining=True
ssh_args = -o ControlMaster=auto -o ControlPersist=30m
forks=50
vault_password_file = ***
```
##### Environment:

OSX Yosemite
##### Summary:

Handlers are not being forced to run when I call flush_handlers
##### Steps To Reproduce:

In `site.yml`:

```
- hosts: webservers
  serial: 1
  roles:
    - webserver
```

In `roles/webserver/meta/main.yml`:

```
dependencies:
  - webserver/nginx
```

In `roles/webserver/nginx/tasks/main.yaml`:

```
- name: Generate site configuration
  template: src=nginx-site.j2 dest=/etc/nginx/sites-available/{{item.name}} owner=root group=root mode=0644
  notify: Restart nginx
  with_items: nginx_sites
  sudo: true
  tags:
    - webserver
    - nginx

- name: Force handlers to run now
  meta: flush_handlers
  tags:
    - webserver
    - nginx

- name: Wait for nginx to be available
  wait_for:
    port: 80
    host: localhost
  tags:
    - webserver
    - nginx

- name: ELB Instance Register
  local_action: ec2_elb
  args:
    aws_access_key: "{{ansible_aws_access_key}}"
    aws_secret_key: "{{ansible_aws_secret_key}}"
    instance_id: "{{ ec2_id }}"
    ec2_elbs: webservers-elb
    region: "{{ aws_region }}"
    state: 'present'
  when: deploy_environment != 'development'
  tags:
    - webserver
    - nginx
```

Run the playbook with `--tags=nginx`
##### Expected Results:

```
TASK: [webserver/nginx | Generate site configuration] *************************
changed: [web-1.aws.shr.st] 

NOTIFIED: [webserver/nginx | Restart nginx] ***********************************
changed: [web-1.aws.shr.st]

TASK: [webserver/nginx | Wait for nginx to be available] **********************
ok: [web-1.aws.shr.st]

TASK: [webserver/nginx | ELB Instance Register] *******************************
changed: [web-1.aws.shr.st -> 127.0.0.1]
```
##### Actual Results:

```
TASK: [webserver/nginx | Generate site configuration] *************************
changed: [web-1.aws.shr.st] 

TASK: [webserver/nginx | Wait for nginx to be available] **********************
ok: [web-1.aws.shr.st]

TASK: [webserver/nginx | ELB Instance Register] *******************************
changed: [web-1.aws.shr.st -> 127.0.0.1]

NOTIFIED: [webserver/nginx | Restart nginx] ***********************************
changed: [web-1.aws.shr.st]
```

**Comment by sivel** [comment]
I believe this was recently fixed in https://github.com/ansible/ansible/issues/10758

**Comment by bcoca** [comment]
closing as dupe of #10758

**Comment by adrienkohlbecker** [comment]
I checked before submitting, #10758 was fixed with version 1.9.1, I'm using 1.9.1 and this issue is still present.

**Comment by pete0emerson** [comment]
I, too, am using 1.9.1, and this issue is still present. Here's my steps to reproduce:

```
# test.yml
---
- name: Provision instance
  hosts: localhost
  gather_facts: no
  roles:
    - { role: test_role }
```

```
# roles/test_role/tasks/main.yml

---

- name: first step
  shell: echo 'test flush handlers start'
  notify: test flush_handlers
  tags:
    - mytag

- meta: flush_handlers
  tags:
    - mytag

- name: last step
  shell: echo 'test flush handlers end'
  tags:
    - mytag
```

```
# roles/test_role/handlers/main.yml

---
- name: test flush_handlers
  debug: msg="should not run at the end"
```

Here's the run:

```
$ ansible-playbook test.yml --tags mytag

PLAY [Provision instance] *****************************************************

TASK: [test_role | first step] ************************************************
changed: [localhost]

TASK: [test_role | last step] *************************************************
changed: [localhost]

NOTIFIED: [test_role | test flush_handlers] ***********************************
ok: [localhost] => {
    "msg": "should not run at the end"
}

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0
```

**Comment by galindro** [comment]
I'm using version 2.0.0 and the problem persists on this version too.

**Comment by galindro** [comment]
Any return or a prevision to correct this bug? My job is very affected by this issue... 
I've read the code to try solve this issue, but I don't have sufficient knowledge in Ansible source code. Sorry...

**Comment by bcoca** [comment]
I've tested this in 1.9.1 and I cannot reproduce (on 2.0 the handler does not run at all, but that is different issue).

**Comment by bcoca** [comment]
play.yml

```
- hosts: localhost
  gather_facts: false
  roles:
    - test

  tasks:
    - debug: msg='role is done'
```

cat roles/test/tasks/main.yml 

```
---
# tasks file for /home/bcoca/work/envs/handlers/roles/test
- debug: msg='i changed'
  changed_when: True
  notify:
    - runme

- meta: flush_handlers

- debug: msg="shoud have flused"
```

cat roles/test/handlers/main.yml 

``` ---
# handlers file for /home/bcoca/work/envs/handlers/roles/test
- name: runme
  debug: msg="I RAN"
```

output:

``````

changed: [localhost] => {
    "changed": true,
    "msg": "i changed"
}


ok: [localhost] => {
    "msg": "I RAN"
}


ok: [localhost] => {
    "msg": "shoud have flused"
}


ok: [localhost] => {
    "msg": "role is done"
}


localhost                  : ok=4    changed=1    unreachable=0    failed=0   ```
``````

**Comment by sivel** [comment]
I may be wrong, and haven't tested, but I believe it may be related to tags.  When specifying a tag is when users have had an issue in the past.

**Comment by bcoca** [comment]
added tag to the 'change' task and the handler still runs w/o or with the tag specified on the command line

**Comment by galindro** [comment]
No bcoca, it doesn't works. I'm using now version 1.9.1 installed via apt-get in Ubuntu 14.04. See my example:

``` yaml
---
- hosts: localhost
  tasks:
    - command: echo "restarting SSH"
      notify:
        - restart ssh
      tags:
        - restart_ssh_server

    - meta: flush_handlers

    - command: echo "SSH restarted"
      tags:
        - restart_ssh_server

  handlers:
    - name: restart ssh
      command: service ssh restart
      sudo: yes
      tags:
        - restart_ssh_server
```

``` bash
# WITH TAG
$ ansible-playbook -t restart_ssh_server -k /tmp/play.yml --ask-become-pass
SSH password: 
SUDO password[defaults to SSH password]: 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [command echo "restarting SSH"] ***************************************** 
changed: [localhost]

TASK: [command echo "SSH restarted"] ****************************************** 
changed: [localhost]

NOTIFIED: [restart ssh] ******************************************************* 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=3    unreachable=0    failed=0   
```

``` bash
# WITHOUT TAG
$ ansible-playbook -k /tmp/play.yml --ask-become-pass
SSH password: 
SUDO password[defaults to SSH password]: 

PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [command echo "restarting SSH"] ***************************************** 
changed: [localhost]

NOTIFIED: [restart ssh] ******************************************************* 
changed: [localhost]

TASK: [command echo "SSH restarted"] ****************************************** 
changed: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=3    unreachable=0    failed=0   
```
