### ISSUE TITLE
more flexible users' groups management

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#11024]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
user module

##### ANSIBLE VERSION
2.1

##### SUMMARY
Hi!
**user** module has only _groups_ and _append_ parameters regarding groups, this is very limited model.
I propose adding the following parameters:

_remgroups_ - groups listed in this parameter will be subtracted from _groups_. If append=true, then user will also be removed from these groups.

_ignore_missing_groups_ - do not fail if group listed in _groups_ does not exist on the system.

**Comment by ansibot** [comment]
@Vladimir-csp Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by danielmotaleite** [comment]
almost 3 years later, we can not still remove a user from a group using ansible, but we can add then

as workaround, please use something like this:

```
- name: remove telegraf user from varnish group
  become: true
  shell: "/usr/sbin/delgroup telegraf varnish"
  when: ansible_hostname | lower not in groups['varnish'] | lower
```

at least update the documentation to show the workaround above

**Comment by bcoca** [comment]
what we really need is a `group` module

**Comment by danielmotaleite** [comment]
yep, that probably is the best solution, it will probably solve other group management problems that extending user alone would not solve

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by franciscorobles-e2y** [comment]
I have been checking but did not see any way for doing this without a workaround, not with the user module neither the group one. Is this going to be done?

**Comment by manumeter** [comment]
If someone is looking for a solution until it gets added to e.g. the group module in upstream: I've written a small custom module which should cover most of the cases:
https://github.com/isginf/ansible/blob/master/modules/system/member.py

**Comment by utrumo** [comment]
> If someone is looking for a solution until it gets added to e.g. the group module in upstream: I've written a small custom module which should cover most of the cases:
> https://github.com/isginf/ansible/blob/master/modules/system/member.py

Good plugin. Why you didn't  make a pull request in this repository to this path: https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/system?

**Comment by manumeter** [comment]
> Good plugin. Why you didn't make a pull request in this repository by this path: https://github.com/ansible/ansible/tree/devel/lib/ansible/modules/system?

Okay, good idea, done: https://github.com/ansible/ansible/pull/67128

**Comment by danielporto** [comment]
Any update on this? it this already accepted or how can I use it?

**Comment by kfiresmith** [comment]
Looking forward to this functionality.

**Comment by wolcen** [comment]
### Regarding the merge request:

@danielporto it doesn't look like it - seems the merge request was closed as the target for community modules was shifted.

I think a new merge request will have to be made to send the module over to https://github.com/ansible-collections/community.general instead. @manumeter - are you up for that? (I'll volunteer if you are not - it'd give me something to do on contributor day at AnsibleFest next month).

If/once it is merged there and published, it could be pulled in using galaxy: https://galaxy.ansible.com/community/general

In the meantime, note that the most up to date version appears to be at:
https://github.com/manumeter/ansible/blob/devel/lib/ansible/modules/system/member.py

### Another way...

FWIW, I attempted a command/shell-free method, but failed in my attempt. The idea: do a list difference on the groups returned from the user module. According to docs, return value for groups is: "List of groups of which the user is a member". Then, just call user again with append: no after removing any unwanted entries.

*Removing groups that way does work*, however: the group list returned does not include any groups which were not already passed *into* the user module to begin with. This appears either a bug, or documentation error. I'd guess the documentation - though I haven't looked at the module yet to determine the actual expectations of the code.

Following that idea for a moment though, here is another example:
```
  vars:
    target_user: rick-c-137
    remove_groups: 
      - council-members
      - citadel-admins
  tasks:
  - name: read groups
    command:
      cmd: "id -Gn {{ target_user }}"
    changed_when: false
    register: group_cmd
    failed_when: group_cmd.rc != 0

  - name: setup new group list
    set_fact:
      new_groups: "{{ group_cmd.stdout.split() | difference(remove_groups) }}"

  - name: changes groups, as needed
    user:
      name: "{{ target_user }}"
      state: present
      append: no
      groups: "{{ new_groups }}"
```

No "better" really than just calling a command to begin with, but there's the framework for anyone that might want more information on current groups, or perhaps to filter out multiple groups at once.

### Improving on deluser (delgroup):

If you are using the `deluser <user> <group>` method, to handle your changed_when/failed_when, rc = 0 when the user is removed from the group, and rc = 6 when the user was not in the group (so, change on 0, fail on not in 0,6). e.g. (untested):
```
- name: remove user from group
  command:
    cmd: "/usr/sbin/deluser {{ target_user }} {{ remove_group }}"
  register: grp_change
  failed_when: grp_change.rc not in [0, 6]
  changed_when: grp_change.rc == 0  
```

In closing: another vote for allowing a direct pass in of remove_groups, or else let's help push along that contrib module :smile:
