### ISSUE TITLE
Regression in template interpolation post 1.7.1 with hash merging enabled

### ISSUE THREAD

**Issue by hfinucane** [ansible/ansible#11053]
Minimum test play:

```
- hosts: all
  roles:
  - role: test
    x: "{{adict}}"
```

with hash merging on, and this in the group vars:

```

---

adict:
    foo: bar
```

Resulting error message:

```
fatal: [localhost] => failed to combine variables, expected dicts but got a 'dict' and a 'unicode'
```

I git bisected this back to 9a0f8f0, a fix for #9497. It works with hash merging off.
