### ISSUE TITLE
Add JSON example to set_fact documentation

### ISSUE THREAD

**Issue by joshunger** [ansible/ansible#11059]
##### ISSUE TYPE
Documentation Report

##### COMPONENT NAME
set_fact module

##### ANSIBLE VERSION
N/A

##### SUMMARY

It would be really helpful if we added a JSON example to the set_fact documentation.  I can do this in a pull request if you can point me to the documentation.

Here is one -

```
- name: get aws session token
  command: aws sts get-session-token
  register: aws_session_token

- name: save session token to ansible variable
  set_fact:
        session_token: "{{ aws_session_token.stdout | from_json }}"
```
