### ISSUE TITLE
Fix ec2_ami_find documentation and add additional examples

### ISSUE THREAD

**Issue by joshunger** [ansible/ansible#11057]
I noticed a couple of errors on the http://docs.ansible.com/ec2_ami_find_module.html documentation that I'd be happy to fix however I can't find this file in GitHub when searching under the repository.  Do you want to fix these issues or can you tell me where this file is located and I can submit a pull request?
1. The region parameter is required but all examples do not include the region.  Each example should include a region parameter.
2. The first example is invalid since it is using the "tags" parameter.  The parameter is called "ami_tags".
3. Clean up synopsis text.  Currently - "Returns list of matching AMIs with AMI ID, along with other useful information Can search AMIs with different owners Can search by matching tag(s), by AMI name and/or other criteria Results can be sorted and sliced".  Whatever makes sense here.  Maybe something like "Returns a list of AMIs for a given search criteria of owners, tags, or AMI name that can be sorted and sliced"
4. The last example uses "ami_search" which is the wrong registered variable.  This should be "ami_find" instead.
5. The last example assumes the results length is greater than 0.  To showcase ansible conditionals and help the end user, you could add a condition such as "when: ami_find.results|length > 0"
6. It would be great to include an additional example on how to delete an AMI.  Here is one -

```
    - name: trying to find old jenkins slave ami
      ec2_ami_find:
        region: us-west-2
        name: jenkins-slave
      register: ami_find_output

    - name: delete old jenkins slave ami
      ec2_ami:
        region: us-west-2
        image_id: "{{ ami_find_output.results.0.ami_id }}"
        delete_snapshot: true
        state: absent
      when: ami_find_output.results|length > 0
```
