### ISSUE TITLE
Feature Request: Support host_key_checking as a host/group variable

### ISSUE THREAD

**Issue by bobziuchkovski** [ansible/ansible#11064]
##### ISSUE TYPE
Feature Request

##### COMPONENT NAME
core

##### ANSIBLE VERSION
N/A

##### SUMMARY

Currently host_key_checking is a global option that can be toggled via ansible.cfg or the ANSIBLE_HOST_KEY_CHECKING environment variable.

It would be really handy if this could be set on a host-by-host or group-by-group basis.  I have a group of development VMs that are blown away and recreated on a routine basis.  It would be nice to disable host key checking for these development VMs while leaving it enabled for other hosts.

**Comment by HalisCz** [comment]
I agree

**Comment by haasn** [comment]
I have the same issue, in particular I want a task to to disable host_key_checking based on the results of a previous task.

I tried finding a work-around for this by seeing if I can manually influence the SSH args on a per-host basis, but it doesn't seem to be possible.

Any ideas? For now I'll work around the issue by manually disabling host key checking via the command line when I know I need it. (Which is only whenever I set up a new host for the first time)

**Comment by bcoca** [comment]
you can do this by setting the ansible_ssh_args at host/group level and adding that option.

**Comment by haasn** [comment]
It doesn't seem that this can be set at runtime, or can it?

I'm trying to do something like this:

``` yaml
- name: check if SSH connection is possible
  command: ssh -o BatchMode=yes {{ inventory_hostname }} /bin/true
  register: result
  connection: local
  ignore_errors: yes
  changed_when: false

- name: if not set up, use different authentication and ignore host keys
  connection: local
  set_fact:
    ansible_user: ubuntu
    ansible_become: true # use sudo
    ansible_ssh_args: -o ControlMaster=auto
                      -o ControlPersist=60s
                      -o UserKnownHostsFile=/dev/null
                      -o StrictHostKeyChecking=no
  when: result|failed
```

And even though ansible_user and ansible_become take effect, ansible is still invoking ssh with its default ssh_args.
