### ISSUE TITLE
Feature request: ignore_instances option in ec2_asg

### ISSUE THREAD

**Issue by galindro** [ansible/ansible#11070]
I need to run ASG rolling update from within an ec2 instance of the autoscaling group that is updated. So, I need to inform to ec2_asg module to ignore the instance which is calling ec2_asg because that instance will be replaced by a new one and the SSH connection will be dropped, causing fatal error to ansible playbook execution.

So, I propose a new parameter called  ignore_instances. It will instructs ec2_asg module to replace all instances except the ignored instances:

``` yaml
- ec2_asg:
    name: myasg
    launch_config_name: my_new_lc
    health_check_period: 60
    health_check_type: ELB
    ignore_instances:
    - i-b348879
    - i-24c7895
    min_size: 2
    max_size: 5
    desired_capacity: 2
    region: sa-east-1
```
