### ISSUE TITLE
Bug: copy says ok but file isn't there

### ISSUE THREAD

**Issue by frontierpsycho** [ansible/ansible#11088]
I am running the following task on a bunch of EC2 servers, using the ec2.py script as inventory:

``` yaml
    - name: Copy upstart scripts
      copy:
        dest: /etc/init/{{ item }}
        group: root
        owner: root
        src: files/telemetry/{{ item }}
        mode: "u=rw,g=r,o=r"
      with_items:
        - job.conf
        - job-launcher.conf
```

The `job.conf` file already exists on all servers, but I added the launcher file and want to send that too. Ansible reports:

`ok: [<ec2 host>] => (item=launcher.conf)`

even though I ssh into the machine and see that it isn't there.

I'm running ansible 1.9.1, on debian 8.0 (jessie).
