### ISSUE TITLE
No current variable in Ansible (like $_ in perl)

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#11107]
Sometimes, we need to register a variable in order to check a file or when launching a command but in fact, this kind of variable are not very usefull.

Here's an example of this:

``` yaml
- name: check a directory exist
  stat: path=/path/to/something
  register: p
  failed_when: 'p.stat.isdir is defined and p.stat.isdir'
```

The variable p is registered but will never be used anymore. In perl, we commonly use $_ for this kind of purpose.

After looking a little bit in Ansible, I found a way to reproduce this behaviour by applying the following patch:

``` patch
diff --git a/lib/ansible/modules/extras b/lib/ansible/modules/extras
--- a/lib/ansible/modules/extras
+++ b/lib/ansible/modules/extras
@@ -1 +1 @@
-Subproject commit b2e4f31bebfec49380659b9d65b5828f1c1ed8d9
+Subproject commit b2e4f31bebfec49380659b9d65b5828f1c1ed8d9-dirty
diff --git a/lib/ansible/runner/__init__.py b/lib/ansible/runner/__init__.py
index 8b46683..0828a1f 100644
--- a/lib/ansible/runner/__init__.py
+++ b/lib/ansible/runner/__init__.py
@@ -1089,6 +1089,8 @@ class Runner(object):
                     if 'stdout' in data:
                         data['stdout_lines'] = data['stdout'].splitlines()
                     inject[register] = data
+                # Store result in current variable ('_')
+                inject['_'] = data
                 # only run the final checks if the async_status has finished,
                 # or if we're not running an async_status check at all
                 if (module_name == 'async_status' and "finished" in data) or module_name != 'async_status':
```

Using this patch, test on existing file can be written like this:

``` yaml
- name: check a directory exist
  stat: path=/path/to/something
  failed_when: '_.stat.isdir is defined and _.stat.isdir'
```

What do you think about ?
