### ISSUE TITLE
rax: Building with bootable volume returns "Block Device Mapping is Invalid: Missing device UUID"

### ISSUE THREAD

**Issue by mig5** [ansible/ansible#11116]
I am attempting to build a Rackspace Cloud machine with a Bootable Volume. A gist showing my playbook is at https://gist.github.com/mig5/ae17b71fe96c6a1cd8f4

This is the error I get:

```
TASK: [Server build request] **************************************************
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: Block Device Mapping is Invalid: Missing device UUID.
```

I have tried with both a saved Block Storage volume (the UUID shown in the Gist) as well as with generic image such as debian-7-wheezy-pvhvm

System tested on:

Debian 7.8 (Wheezy)
Python 2.7
ansible 1.9.1
pyrax 1.9.4

**Comment by mig5** [comment]
It works if I don't specify boot_volume (a new boot volume is created from the image). My understanding was that boot_volume was for giving the new volume (which is based on the image defined by 'image'), a label.

The docs could describe the difference between 'boot_volume' and 'image' when boot_from_volume is true.

**Comment by sivel** [comment]
To ensure history, pasting the task directly in this issue:

```
---
- name: Build a Cloud Server
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Server build request
      local_action:
        module: rax
        credentials: /home/jenkins/.raxpub
        name: rax-test1
        flavor: performance1-1
        image: 9d2589a6-e7f5-4390-bf85-2d2f6634acc1
        boot_from_volume: yes
        boot_volume: rax_test1
        boot_volume_size: 120
        key_name: mig5
        region: DFW
        wait: yes
        state: present
        networks:
          - private
          - public
      register: rax
```
