### ISSUE TITLE
Validating roles supported platforms from meta/main.yml

### ISSUE THREAD

**Issue by pschirch** [ansible/ansible#11133]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
1.9.1
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Validating roles supported platforms from `meta/main.yml` and start provisioning only if all applied roles support the current OS without implementing this in any applied role to ensuring a clean host provisioning state.

##### STEPS TO REPRODUCE
``` bash
ansible-playbook -i inventory playbook.yml -vv
```

##### EXPECTED RESULTS
Validating roles supported platforms from `meta/main.yml` and start provisioning only if all applied roles support the current OS.
Ansible should output something like this:
``` bash
failed: [127.0.0.1] => {"failed": true}
msg: This OS is not supported by role: $ROLE_NAME!
```

##### ACTUAL RESULTS
Playbook is executing without checking if the current OS is supported and fails including an unclean host provisioning state. Actually, you have to do that manually in your role like:
``` yaml
# Checking roles OS support
- set_fact:
    role_name_supported_os:
      - { 'ansible_distribution': 'openSUSE', 'ansible_distribution_version': '12.3' }
      - { 'ansible_distribution': 'openSUSE', 'ansible_distribution_version': '13.1' }
      - { 'ansible_distribution': 'openSUSE', 'ansible_distribution_version': '13.2' }
      - { 'ansible_distribution': 'Ubuntu' , 'ansible_distribution_version': '14.04' }
      - { 'ansible_distribution': 'Ubuntu' , 'ansible_distribution_version': '14.10' }
- set_fact: role_name_os_supported=False
- set_fact: role_name_os_supported=True
  with_items: role_name_supported_os
  when: item.ansible_distribution == ansible_distribution
          and item.ansible_distribution_version == ansible_distribution_version
          and role_name_os_supported == False
- fail: msg="This OS is not supported by role: $ROLE_NAME!!"
  when: not role_name_os_supported
```
