### ISSUE TITLE
authorized_keys "exclusive" option fails w/ with_subelements

### ISSUE THREAD

**Issue by cowboy** [ansible/ansible#11152]
When I do the following in ansible 1.9.1, it treats each _individual_ per-user key as exclusive, not the _group_ of per-user keys as exclusive. As a result, only the last specified per-user key is usable.

``` yaml
- name: sync all users keys
  authorized_key: user={{item.0.name}} key='{{item.1}}' state=present exclusive=yes
  with_subelements:
    - users
    - keys
```
