### ISSUE TITLE
default(omit) filter doesn't work with dictionary values

### ISSUE THREAD

**Issue by greylurk** [ansible/ansible#11173]
Given this playbook:
### main.yaml

``` yaml

---
- hosts: oracle_app
  roles: 
    - role: oracle-client
    - role: python-app
      package: my-app-that-requires-oracle==1.0.0
  vars:
    pip_env: 
      ORACLE_HOME: /opt/oracle/instantclient_home_11_2

- hosts: some_other_python_app
  roles: 
    - role: python-app
      package: my-app-that-uses-no-oracle==1.0.0     
```

And this role:
### roles/python-app/tasks/main.yaml

``` yaml

---
- name: Install app via pip
  pip: 
    name: "{{package}}"
  environment: "{{pip_env|default(omit)}}"
```

The playbook fails on the "some_other_python_app" hosts with an error: 
    environment must be a dictionary, received __omit_place_holder__c474fb1160e3edc29166ca21a4eb7aa620a5e2b3
