### ISSUE TITLE
Package manager optimization results in unexpected behaviour with 'complex' package names.

### ISSUE THREAD

**Issue by DenKoren** [ansible/ansible#11184]
I faced the problem when I tried to install several packages with similar names using 'with_items' to generate package names.

Here is the code example

```

---
- hosts: test
  sudo: yes
  vars:
    - repository: 'some-project'
    - branches:
      - 'stable'
      - 'unstable'
  tasks:
    - name: install repository configuration using debian package
      apt: name=repo-{{ repository }}-{{ item }}
           state=latest
      with_items: branches
```

I expected ansible to do the following:

```
get one item value -> generate the command -> execute -> get next item value ...
```

But got the error message:

```
TASK: [install repository configuration using debian package] *****************
failed: [lite-prestable.i-folb.fog.yandex.net] => (item=stable,unstable) => {"failed": true, "item": "stable,unstable"}
msg: No package matching 'unstable' is available
```

I had been confused with this message, some time I spent in checking my syntax and trying different ways to give the variable vlue to 'with_items', e.g. with '{{' - or not, inside ' ' - or not, with '[' - or not. I tried to replace 'with_items' with 'with_flattened' but it has no effect.

I placed 'debug' before real task and saw, that it can recognize the list given in varable.

I became to search for help in google, but it's hard to explain to search engine what are you looking for, when you have no idea :).
So, suddenly I found conversation about bug with 'yum' (year 2013, version 1.0), where one of ansible developers told that he 'switched off optimization for non-string item values'. I suggested, that it can be another (or the same) optimization for 'apt' module, and started to learn and inspect code.

I've found, that 'runner' tries to join items using ',' delimiter and it crashes my playbook.

It seems, that should be done one of things (or both of them, which will be much better, because this is not the first bug with this optimization and nobody knows, when this code will shoot again):
- optimization should be more smart and work only when the 'name' field value does not contain anything except '{{ item }}'.
- documentation should have notes about this optimization: package managers has unique behaviour here and it should be explicitly noted by documentation for package modules and in 'Loops' documentation section.
