### ISSUE TITLE
Hosts setting being ignored when using --connection=local

### ISSUE THREAD

**Issue by F21** [ansible/ansible#11196]
##### Issue Type:

Bug report
##### Ansible Version:

```
ansible 1.9.1
  configured module search path = None
```
##### Ansible Configuration:

Defaults
##### Environment:

Ubuntu 14.10 64-bit running on VirtualBox 4.3.28 on Windows 8.1 64-bit via vagrant.
##### Summary:

I am running Ansible within a Ubuntu VM using `--connection=local`. For some reason, the playbook will play everything, even for ones that do not match the hostname of the machine.
##### Steps To Reproduce:
1. Create inventory file:

```
[mesos-masters]
mesos-master-*

[mesos-slaves]
mesos-slave-*
```
1. Create playbook files:

playbook.yml:

```

---
- include: mesos-master.yml
- include: mesos-slave.yml
```

mesos-master.yml:

```

---
- hosts: mesos-masters
  sudo: yes
  tasks:
    - shell: touch /tmp/is-master
```

mesos-slave.yml:

```

---
- hosts: mesos-slaves
  sudo: yes
  tasks:
    - shell: touch /tmp/is-slave
```
1. Run the playbook: `ansible-playbook playbook.yml --inventory-file=inventory --connection=local`
##### Expected Results:

Assuming that the machine's hostname is `mesos-master-01`, the `mesos-master` playbook should be played and only `/tmp/is-master` should exist.
##### Actual Results:

Both the `mesos-master` and `mesos-slave` playbooks are played. Both `/tmp/is-slave` and `/tmp/is-master` exists.
