### ISSUE TITLE
only_if statements in variables broken

### ISSUE THREAD

**Issue by dhozac** [ansible/ansible#1120]
Since #1091 was merged, playbooks with something like

```
vars:
  is_centos_6: "'$ansible_distribution_version'.startswith('6.')"
tasks:
- name: only if centos 6
  action: ...
  only_if: $is_centos_6
```

no longer work, as it will be expanded to a string containing the entire statement.

I don't see how we could differentiate between this case and when you want to be able to leave off the quotes, since I would expect it to work as

```
  is_centos_6: "$ansible_distribution_version.startswith('6.')"
```

if that works in only_if, but achieving that programmatically seems impossible.

@dagwieers @mpdehaan, any ideas?

**Comment by dagwieers** [comment]
When I used regular expressions it would match \$[\w.]+ surrounded by quotes. In the new syntax the above would still work, but you could not simply leave off the quotes (because .startswith would be part of the variable name) so in cases like these, surrounding by curly brackets would be mandatory.

```
$some_var
$some_var.blah
${some_var['blah']}.foo
${some_var}.startswith('5.')
```

Or if we want to make it ourselves easier, always demand curly brackets.

At some point we may have to drop backward compatibility, but I am not sure it is needed for this. As long as the new syntax is very clear.

Am I missing something ?

**Comment by dhozac** [comment]
A few more problematic cases:

```
vars:
  is_centos: "'$ansible_distribution' == 'CentOS'"
  is_centos_6: "$is_centos and '$ansible_distribution_version'.startswith('6.')"
  is_special_c6: "$my_bool_fact and $is_centos_6"
  my_concat_str: "'${ansible_distribution}${ansible_distribution_version}'"
  is_rhel_6: "$my_concat_str.startswith('RedHat6.')"
```

**Comment by dhozac** [comment]
. is only allowed in complex variable names, i.e. those that have curly braces around them.

The problem is that the outer-most variable in only_if will be repr'd, leaving you with a string of the statement whenever it's not immediately on the only_if: line.

**Comment by mpdehaan** [comment]
You are not going to like this, but the answer is to revert 1091 for now.

It breaks more people than the alternative.

**Comment by mpdehaan** [comment]
Well, 1091 being repr stuff, not the new vars parsing stuff -- sorry
-- ignore that.

Could it be as simple as "If the expression given to only_if
originally starts with a "$" and if you remove the "$" from the string
and the name of the string you have left is now a key in the variable
dictionary (inject, etc), then replace the only_if with the variable?

Seems like that could be a workable fix.

If you can't figure it out, I can probably test and look tonight.

**Comment by dhozac** [comment]
That would only solve the easiest case, the nested variables would have different rules for how you use them. So with for instance,

```
vars:
  is_centos_6: "$ansible_distribution_version.startswith('6.')"
  is_special_c6: "$is_centos_6 and $my_bool_fact"
tasks:
- name: run on centos 6
  action: ...
  only_if: $is_centos_6
- name: run on special centos 6
  action: ...
  only_if: $is_special_c6
```

the first task would work, while the other would result in parse errors from the statement that worked fine for the first task. I think that would be confusing to say the least...
