### ISSUE TITLE
'copy' task fail

### ISSUE THREAD

**Issue by alexd88** [ansible/ansible#11200]
Ansible Version:

ansible 1.9.1

Environment:

Localhost : OSX Yosemite

Summary:

I have run playbook:

```

---
- hosts: all
  name: update php-fpm config
  user: xxx
  become: True
  gather_facts: True

  vars_files:
    - credentials.yml

  pre_tasks:

  - name: Gathering ec2 facts
    action: ec2_facts

  - name: Instance De-register
    local_action:
      module: ec2_elb
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      region: "xx-xxxxx"
      instance_id: "{{ ansible_ec2_instance_id }}"
      state: 'absent'

  - name: Delete old php-fpm.conf
    file: path=/etc/php-fpm.d/php-fpm.conf state=absent

  - name: Copy php-fpm.conf
    copy: src=files/php-fpm_new.conf dest=/etc/php-fpm.d/php-fpm.conf owner=root group=root mode=0644

  - name: Restart php-fpm
    service: name=php-fpm state=restarted

  - name: Instance Register
    local_action:
      module: ec2_elb
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      region: "xx-xxxx"
      instance_id: "{{ ansible_ec2_instance_id }}"
      ec2_elbs: "lb-xxxxx"
      state: 'present'
```

Results:

On task [Copy php-fpm.conf] i have got weird message:

```
TASK: [Copy php-fpm.conf] ******************************************************
<10.0.1.19> ESTABLISH CONNECTION FOR USER: xxx
fatal: [10.0.1.19] => Failed to template buUµ<ézâHÿylÊÓ§[à*»Û5Ë!.°N
Ù²bå{w¾¢                                                             3½|BHÖY0G·ß}#«zfwÝ!wD¦<ì
Ç´Ðç´èðó1+:7Vµóèøç¨P(Ëß0üÁº±±¯5Ç_éeÍ÷Ö²PøpüõÿfM92
bXã§ë¹å]ÏÕÈ,ÅñHxg²È
FY«'Ü®_ÔðÚñ×ê:ºöhívTz¢Ý¯"#,ëj¬^Á£RÁµu+Då/þxwù×b!öWùþ$¼âkýü3ÒL××uCQ?]8P_ï°4SXAì¸| 8>¦\[!ðò:ö¼ÇR}0`,
}Sehú''Ø¯âå®ô>-Rgz_úaäß-                                                                                      îKfÑÝõ¾lyQ¬zQVX$Æª¼6¢¸L_E+ÕUw¾Ë]i¾{]©ÒE1]£jÌ
ÆÆÐÐÏ_Ñ×±a ²ú#_"æëÏt¡°P-g/Ñ_SäXáù÷Å
                                       c òè*Öñ¢¨,ªÆ CÃÐåPt ÈC
                                                                  ôbÖbbÓ@xxàZ`«Fð¢³Tx­æ®kÅãé·Pì£úXDâü0¾*åø+¤©RÈÏ/    EÛ(6\à;½àÇÛdP3>Æ)Vt@°¶Í¹î¯=t
\Ë[Å°!uÃVb<?å/`Â¨Ôýö¢¯èÚµk×õ«½Tsli0ï}NÃÃÿNÂ"ÿGüLÿ+®WX-=Tï³ìð¤ðZ(dKuÚÐLÿyñ<XF9\heæ
                                                                                      Ã\þrþÀïÐÅßèOô×ìKP7^®Sàu±       ÂF²u÷vÃq`ô]°þ6ôµ@ÿDÿ@åe(ô;=øn+ù«ø
T
¾°¼ÒÑÀØDiø¸°01¡¡ê³ ô7Ûå-ü(kA&'°F÷à1¢Ã÷b¾çb
 YTüoâDÿà¼/¾|§Þx7bl°6Á^s«÷~@cîã­z[/V¼ahva­Zñlá³£gé> )ÜbÀ!B,5B4}ØÉÜH:[Â8ygVºJTàq# µ
VÆÃö£«¼?hbRñsèKxBªÐ-c§
 &1¬W¡²eÝpÔ-¢)ô1ûÅÒ«UT?cÖqÀ ©tVþÊÑçÇEç
                                                  pïJõ¶ku{uuÙ3Þüýhøâ²^3Tu°
*Ó?Ä{Iðxw*¬~çrÌ,Ãý½Í        ÀÌåüTÐmHrBU@
                     e¡&î¹ ¯ÓP
                                b?ØéFw²Ö"Æ¿ñlL\Ù§Òß¢ÒåQñìiÐÅ9<¯W9§;à(þ-*éâ«PMWþøLEåÈËã¥Úà3!{ÕOÂY¤x^h;¬NGXyÈõÁÕ"]5\2ü÷±Èà,zâMKÙL$Bg¸$ìÊ¯ôë8*¼|dõ8T
TJã
   :èq,7z-!V¡£Ô▒K┤¬^    Gµ=9WÊF¼
A¥Â_
    óÇ>»ªû×!HÆæÑ¢W<_BU↓
U┤→±ê­Ab:(VÀö Nb◆±çb⎺Dè%Q7cê¿πOÎ≤75A´­àÔ┬Xù├çà▒·ìXHN⎽X@à¾­¬çJπ$ïùBê?öJ↑≠×«]÷⎺)úDcP«b°µ6Ò8MR±×ï¯I7·@Â
õ°ê©¦▮êÖπ³┼Äû"       ÒÅµ⎺ªÖµ☃≤1ÞL¤☃¡ç"ê⎽­≠πè×ÃÄC¥┬│≥└▒ÌÕ⎽äπ☃☃W­Vß[X¹┘d#úü¹≤«d­ùI%πN*¥3Å%ã@:>ø┤π&ÃºI┌©T¡ÍÞË?<⎼ÅÙcCád≥?[®É×ý
GÛ┐≤;←HÆÑ$ª%cûXÆ▒ú↓deÆå¯"®<┘↓¤e
                                     T¼Ýàú┐4ð¯@%≥àdc│²9'%è▒cWIâÑÏ¸äÿ┐ó¯←ÇÁ)õ_ùðÓ>¦/F¤[òAíà;´
                                                                                                        ûî¤↓"çXÅ1¸P_êÊ3S8CD1─ ª┐@^YÖ°└V┘┴±→    =V¼ÿR▒ÊÂ◆
^▮ìHî→T¡5⎽Q½µ£ª°ï¿I©Å°Pý\ÛìQ◆Û½§ûé←ø°û$Ýã¨2À"#à
A@db2óµ=l;ÓÖ{S§!ªz+w$øLÝ¿$Óc$%Ní¼¹"ãÎ÷ô(^åE│*¹→2eT=©çü%±/¼e£/⎼9Í       Êé¬Ôò▮b
                                                                                       ≠DCJ6▒úë¿Q¼Z←®VáÔ(I@ÞÆ±¤H¤
                                                                                                                          │V\\Ö4Ä7"¯C┐°TÔÐG°¤¾Ï½│óV1┬"Zó├Ý
«3¡ç AìÖ¡4ÉT┤G¾é│»┴ÂGÆ;°]↑ýÀ#U↓%┘YÚ→3½⎺6│SË&Ë#øß·cÙ*½çâ®ÒÐOüÛ
π·îÍÅ'øJª¥·☃î¾┘Lâò←½/cøπZG¥#◆_¸_⎻ñ⎽W↓┴8©ÐÀ$*¾bb%UÒSðúâãÚ´ýI#"°¸Ì£ôVû/ÌWb¡Þ
ð'8ëÛå¯À=âH⎻£
             î£É­
                  Úß─ÃåÍ⎻¹e¦Ý⎺├¯Å_e0:°àORZðKõ)2J)jK% #1íAu4~GWé.IÓÄÏ¥$°ì_u©
                                                                                        aý+¦7×ìÏUÈx3^Í\
                                                                                                         /[IN²q1,®f        s´gã¸Íô¿L94A¼(;¹C£]¢ßFâòzfg¤Ì
¤*2;%°9õw\%¢»"--À«b?
¥^Yâäf9Ô¸Ù9xÑ5=#i*¨®ªá¾þ.....
....
....
_·´Qí◆π⎽ï≥³úOØ│±ÜMå±óÐÞ─TÃÜ┼Åú┼b÷┤çÔÒY»└£nn¦
ÝÆ8vÖX7SvûÒ\R½Ïá¦ãÒÁ»-¦f<ÜR6UÌê s
-ì,µ¹å                              o­MaÕh~zx¸åg³®cã¥QÖþp8³Ûá¤9P NnCO±ë[ò}YíW¾}îGs»¡\÷k
ÖÛéçuó´ýÉÄ8zàw× ­Û±']o¾?q7/ëþ¼êß¼0fC »LGl
      «t?=©ñ$éåµ'²ä¡Ê÷Zu¾ÞÀ°X®õV~¥ÂyWhnÄkÃðfø;(øÓäÚqf«÷Ã¢ïÍð>w(WFÒäÂ⎺»®¼7⎺┤¼ß(ùÁ×│«⎻Ê*ýÕ├)ë­d´çÛ7éK¨┤å²×¼°├¸ç´ßKB&Í ôåðÇ¤§\BùQ·┴3¹@Àç¤¾G:π%ô┼ß'¿
°#ïË¹7ÉD¼3ê8HÿQ:Úþ]¹ü▒Ïá
Qöùñ;Pä⎺ìþäèÑÿ­ÜUPD: template error while templating string: unexpected char u'\xf4' at 7436

FATAL: all hosts have already failed -- aborting
```

**Comment by jimi-c** [comment]
e@alexd88 that is very odd, as it looks like your source file for that copy task is getting binary and not text. Can you confirm the contents of that file, and also if you're continuing to see this occur with the most recent version of the devel branch?

**Comment by jctanner** [comment]
I can intermittently reproduce this on 1.9.1 with the following playbook ...

```
- hosts: el6host
  gather_facts: False
  user: root
  vars_files:
    - credentials.yml
  tasks:
    #- shell: whoami
    - file: path=/tmp/php-fpm.conf state=absent
    - shell: echo '\{\{' > /tmp/binfile
    - shell: dd if=/dev/urandom of=/tmp/binfile bs=100 count=100
    - shell: echo '\}\}' >> /tmp/binfile
    - shell: cat /tmp/binfile
      register: x
    - copy:
        src: php-fpm_new.conf
        dest: /tmp/php-fpm.conf
```

The issue is not the copy module or the copied file, it's actually a variable that's been registered somehow with binary data. Right after the line "<10.0.1.19> ESTABLISH CONNECTION FOR USER: xxx", ansible tries to template a bunch of variable names.

I don't suspect the issue in the description was caused by something in the vars file or from inventory because a parsing error occurs at initial loading rather than during the copy task.

If you hit this again, i suggest dumping all hostvars with -debug right before the copy task and figure out what messed up. Might be the ec2 facts or it might be facts from setup.py.
