### ISSUE TITLE
Variable Precedence: vars_prompt to load after vars (post_vars_prompt)

### ISSUE THREAD

**Issue by mwhite14** [ansible/ansible#11239]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.0

##### SUMMARY
Currently var_prompt runs before any variables are set. I feel global vars should be loaded before vars_prompt is initiated. This would allow you to  quickly change the default of a vars_prompt used across many playbooks, by setting it to a global variable. 

In my case I have a specific AMI that i want to us in a var prompt as the default, but I want the ability to specify another when needed. I have this prompt in almost every playbook, and since the default AMI I use is always changing as we upgrade and patch OS's it should be easy to set with one variable across all Playbooks.

I think a better system would be as follows:

Specify variables in global_vars, like:

```
DEFAULT_AMI_UBUNTU: "ami-8fc525e4"
DEFAULT_AMI_UBUNTU_MSG: "What is the Amazon Machine Image (AMI) ID to use (Default is: Ubuntu 14.04, hvm:ebs, amd64, 20150528)"
```

And have this in each playbook have:

```
vars_prompt:
    - name: "image"
      prompt: "{{ DEFAULT_AMI_UBUNTU_MSG }}"
      default: "{{ DEFAULT_AMI_UBUNTU }}"
      private: no
```

What would the reasons not to do this be?
