### ISSUE TITLE
Bug report: dnf module and async tasks fail

### ISSUE THREAD

**Issue by a-nldisr** [ansible/ansible#11235]
Issue Type:
Bug report

error:
fatal: [default] => lookup plugins (with_*) cannot be used with async tasks

Ansible version: 1.9.1 
OS target machine: Fedora 22.

We replaced the yum in our playbooks with dnf and ran into above error. 

Example: 

``` yaml
- name: 'DNF - Install python bindings for SE Linux'   
  dnf: name={{ item }} state=present   
  with_items:   
    - libselinux-python   
    - libsemanage-python   
  async: 1000   
  poll: 0   
  register: dnf_se_sleeper   

- name: 'DNF - install python bindings for SE Linux and check on fire and forget task'   
  async_status: jid={{ dnf_se_sleeper.ansible_job_id }}    
  register: job_result   
  until: job_result.finished    
  retries: 30    
```

Just installed the machine with fedora 21, ran the exact same task with yum and this finishes correctly.

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.
- As the error message states, you cannot use async and with_ loops on the same task.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by abadger** [comment]
As a side note to this -- a few package related modules (yum and apt) have a special optimization pass inside of ansible so that with_\* for package names gets turned into a comma separated string of packages that is passed to the module.  This is probably why yum works and dnf doesn't.  I'll add dnf to that optimization pass now.

As a workaround you can use a comma separated string here instead of with_items like either of these two examples:

```
- name: 'DNF - Install python bindings for SE Linux'   
  dnf: name="libselinux-python,libsemanage-python" state=present   
  async: 1000   
  poll: 0   
  register: dnf_se_sleeper  

[...]
vars:
  packagelist:
    - libselinux-python
    - libsemanage-python
[...]
- name: 'DNF - Install python bindings for SE Linux'   
  dnf: name="{{ packagelist | join(',') }}" state=present   
  async: 1000   
  poll: 0   
  register: dnf_se_sleeper  
```
