### ISSUE TITLE
ec2_group should allow for blank egress rules within a vpc

### ISSUE THREAD

**Issue by lcasey001** [ansible/ansible#11249]
There are use cases where you do not want any egress rules when creating a security group within a vpc. This however forces people to create a bogus (127.0.0.1) egress rule to get rid of the default allow all. 

Use case: A separate security group which contains egress rules you attach to your instances. Then you can have specific ingress only security groups. 

https://github.com/ansible/ansible/issues/7309 prevents this.

**Comment by glnds** [comment]
This is actually an issue for me in order to avoid a chicken or egg problem.When I have two security groups with rules referring to each other i typically solve it like this:
- Create all groups with no rules at all
- After all groups are created start adding rules to them

```
- name: ensure the elastic loadbalancer security group is present
  ec2_group:
    name: ELBSG
    description: ELB security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    purge_rules: False
    purge_rules_egress: False
  register: elb_sg

  - name: ensure the webserver security group is present
  ec2_group:
    name: WebserverSG
    description: Webserver security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    purge_rules: False
    purge_rules_egress: False
  register: webserver_sg

```

The rules are only defined after all groups are created, needed for group referral

```
- name: ensure the elastic loadbalancer securty group rules are configured
  ec2_group:
    name: ELBSG
    description: ELB security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 443
        to_port: 443
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: tcp
        from_port: 443
        to_port: 443
        group_id: "{{ webserver_sg.group_id }}"
      - proto: tcp
        from_port: 8443
        to_port: 8443
        group_id: "{{ webserver_sg.group_id }}"

- name: ensure the webserver securty group rules are configured
  ec2_group:
    name: WebserverSG
    description: Webserver security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        group_id: "{{ bastion_sg.group_id }}"
      - proto: tcp
        from_port: 443
        to_port: 443
        group_id: "{{ elb_sg.group_id }}"
      - proto: tcp
        from_port: 8443
        to_port: 8443
        group_id: "{{ elb_sg.group_id }}"
      - proto: tcp
        from_port: 27017
        to_port: 27017
        group_id: "{{ ci_sg.group_id }}"
    rules_egress:
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: "{{ bastion_sg.group_id }}"
      - proto: tcp
        from_port: 443
        to_port: 443
        group_id: "{{ elb_sg.group_id }}"
      - proto: tcp
        from_port: 443
        to_port: 443
        group_id: "{{ bastion_sg.group_id }}"
      - proto: tcp
        from_port: 3306
        to_port: 3306
        group_id: "{{ rds_sg.group_id }}"
      - proto: tcp
        from_port: 8111
        to_port: 8111
        group_id: "{{ ci_sg.group_id }}"
      - proto: tcp
        from_port: 8443
        to_port: 8443
        group_id: "{{ elb_sg.group_id }}"

```
