### ISSUE TITLE
Problem with 'with_nested' and lineinfile

### ISSUE THREAD

**Issue by sigio** [ansible/ansible#11256]
Given the following play:

```
  - name: Get server ssh-rsa fingerprint
    command: ssh-keyscan -t rsa -H {{server}}
    register: serverrsakey

  - name: Get server ssh-ecdsa fingerprint
    command: ssh-keyscan -t ecdsa -H {{server}}
    register: serverecdsakey

  - name: Add ssh fingerprints to known-hosts
    lineinfile: state=present insertafter=EOF line="{{item[1]}}" regexp="{{item[1]}}" dest="~{{item[0]}}/.ssh/known_hosts" mode=0644 owner="{{item[0]}}" group="{{item[0]}}"
    with_nested:
      - [ "user1", "user2" ]
      - [ "{{serverrsakey.stdout}}", "{{serverecdsakey.stdout}}" ]
```

I would expect the user1 and user2's known_hosts files to both be filled with 2 known-host entries, one each for rsa and ecdsa. However, I'm only getting the ecdsa keys in there.

If I change the line entry to:
line="{{item[1]}}\n"

Then I do get both entries, and an empty line at the end.

This is with ansible 1.9.1 (from pip)
