### ISSUE TITLE
no_log is ignored when using key value args

### ISSUE THREAD

**Issue by klauern** [ansible/ansible#11253]
I was working on a module, and I'm not entirely what is going on between the two forms of argument passing:
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.1
##### Ansible Configuration:

N/A 
##### Environment:

RHEL 6
##### Summary:

When using inline arguments in a module with `no_log` applied to it, output for `no_log` entries are still output if you `register` the result from a previous run.  Switching to a nested dictionary form doesn't output anything (as you would expect).
##### Steps To Reproduce:

As a simple example, the `copy` module sets `no_log` on the `content` argument:
###### Failing Input Case

``` yaml
#!/usr/bin/env ansible-playbook

---
- hosts: localhost
  tasks:
  - name: "don't log the output here"
    copy: content="Don't Output me, please" dest=~/new-file.txt
    register: answer
    with_items:
    - one
  - name: "still don't log the results"
    shell: "echo something else {{ item.item }}"
    with_items: answer.results
```
##### Expected Results:

With the 

``` yaml
- copy:
    content: "Don't Output me, please"
    dest: ~/new-file.txt
```

output will be:

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [don't log the output here] *********************************************
changed: [localhost] => (item=one)

TASK: [still don't log the results] *******************************************
changed: [localhost] => (item={'src': '/home/user/.ansible/tmp/ansible-tmp-1434141808.16-176441222744597/source', 'md5sum': 'f8a6164874202c63f55cb4a9be785188', 'group': 'users', 'uid': 13182, 'dest': '/home/user/new-file.txt', 'checksum': 'ded2954eb439c087e0aec42b9387a999abd4f9c9', 'changed': True, 'item': 'one', 'state': 'file', 'gid': 7000, 'secontext': 'unconfined_u:object_r:user_home_t:s0', 'mode': '0644', 'invocation': {'module_name': u'copy', 'module_args': ''}, 'owner': 'user', 'size': 23})

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0
```
##### Actual Results:

Using inline arguments:

```
- copy:  content="Don't Output me, please" dest=~/new-file.txt
```

```
PLAY [localhost] **************************************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [don't log the output here] *********************************************
changed: [localhost] => (item=one)

TASK: [still don't log the results] *******************************************
changed: [localhost] => (item={'src': '/home/user/.ansible/tmp/ansible-tmp-1434141924.38-204642385448938/source', 'md5sum': 'f8a6164874202c63f55cb4a9be785188', 'group': 'users', 'uid': 13182, 'dest': '/home/user/new-file.txt', 'checksum': 'ded2954eb439c087e0aec42b9387a999abd4f9c9', 'changed': True, 'item': 'one', 'state': 'file', 'gid': 7000, 'secontext': 'unconfined_u:object_r:user_home_t:s0', 'mode': '0644', 'invocation': {'module_name': u'copy', 'module_args': u'content="Don\'t Output me, please" dest=~/new-file.txt'}, 'owner': 'user', 'size': 23})

PLAY RECAP ********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0
```

**Comment by sivel** [comment]
How and where are you setting `no_log`?  You mention creating a module, but your example shows core modules.

If you want to use a registered var that may have sensitive data in it later, you need to set `no_log` on the task that uses it.

**Comment by klauern** [comment]
`no_log` is set by default in the `content` for the [`copy` module](https://github.com/ansible/ansible-modules-core/blob/devel/files/copy.py#L209).  I had my own module that did the same thing, but I've found that reusing the core `copy` module was easier to demo.

**Comment by klauern** [comment]
I suppose if someone wanted to create their own module and try it, it would look a lot like how this turned out:

### no_log_thing.py

``` python
#!/usr/bin/python

import json

def main():
    module = AnsibleModule(
        argument_spec = dict(
            arg = dict(required=True),
            password = dict(required=False, no_log=True)
        ),
    )

    module.exit_json(changed=True)

from ansible.module_utils.basic import *

main()
```

replacing my contrived example above:

### testmodule.yml

``` yaml
#!/usr/bin/env ansible-playbook

---
- hosts: localhost
  tasks:
  - name: "don't log the output here"
    no_log_thing: password="Don't Output me, please" arg="something"
    register: answer
    with_items:
    - one
  - name: "still don't log the results"
    shell: "echo something else {{ item.item }}"
    with_items: answer.results
```

**Comment by bcoca** [comment]
This is not a no_log issue, if the module writer wants to keep data private it should not be returned to register.

**Comment by klauern** [comment]
Then why does it NOT return the argument data if you change from this:

```
- copy: content="Value"
```

to this:

```
- copy:
    content: "Value"
```

Even your [own docs](http://docs.ansible.com/playbooks_intro.html) state that the two are supposedly interchangeable, yet the output isn't the same:

This (args inline):

changed: [localhost] => (item={'src': '/home/user/.ansible/tmp/ansible-tmp-1434141924.38-204642385448938/source', 'md5sum': 'f8a6164874202c63f55cb4a9be785188', 'group': 'users', 'uid': 13182, 'dest': '/home/user/new-file.txt', 'checksum': 'ded2954eb439c087e0aec42b9387a999abd4f9c9', 'changed': True, 'item': 'one', 'state': 'file', 'gid': 7000, 'secontext': 'unconfined_u:object_r:user_home_t:s0', 'mode': '0644', 'invocation': {'module_name': u'copy', 'module_args': **u'content="Don\'t Output me, please" dest=~/new-file.txt'**}, 'owner': 'user', 'size': 23})

Versus This (args nested):

changed: [localhost] => (item={'src': '/home/user/.ansible/tmp/ansible-tmp-1434141808.16-176441222744597/source', 'md5sum': 'f8a6164874202c63f55cb4a9be785188', 'group': 'users', 'uid': 13182, 'dest': '/home/user/new-file.txt', 'checksum': 'ded2954eb439c087e0aec42b9387a999abd4f9c9', 'changed': True, 'item': 'one', 'state': 'file', 'gid': 7000, 'secontext': 'unconfined_u:object_r:user_home_t:s0', 'mode': '0644', 'invocation': {'module_name': u'copy', 'module_args': ''}, 'owner': 'user', 'size': 23})

**Comment by bcoca** [comment]
codding error in the copy module, but that should not be the responsibility of no_log, which just prevents logging of certain input options  to modules.

**Comment by sheldonh** [comment]
This affects the expect module too. I tried setting the responses dict to `no_log=True` in the `AnsibleModule` definition in `lib/ansible/modules/extras/commands/expect.py`, but my sensitive responses are still output, even with `no_log: True` on the task.

**Comment by bcoca** [comment]
no_log controls output to logs, not what goes into the result returned from the module, that is part of the module code

**Comment by vnaum** [comment]
Got into this.
Tested with

```
ansible 2.2.0 (devel 380ed053e8) last updated 2016/07/29 15:39:57 (GMT +600)
  lib/ansible/modules/core: (detached HEAD 24db4de245) last updated 2016/07/29 15:40:06 (GMT +600)
  lib/ansible/modules/extras: (detached HEAD db979dde74) last updated 2016/07/29 15:40:13 (GMT +600)
  config file =
  configured module search path = Default w/o overrides
```

steps to reproduce / minimal playbook:

``` yaml
- hosts: all
  gather_facts: False  # removing this fixes the issue, not sure why.
  tasks:
    - name: put out all the very private keys we have
      no_log: True  # there are private keys in this keys, don't put it on console
      copy:
        content: "{{item}}"
        dest: "/secret_key.txt"
      with_items:
        - "TOP SECRET KEY"   # it's usually {{vaulted_key_1}} or something
        - "BOTTOM SECRET KEY"
```

Run it, get all the "secrets" logged despite no_log: True:
fatal: [vagrant]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": "TOP SECRET KEY", "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}, {"_ansible_item_result": true, "item": "BOTTOM SECRET KEY", "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}]}
