### ISSUE TITLE
to_json does not escape newlines in dict when another key has a bool or null value

### ISSUE THREAD

**Issue by seankelly** [ansible/ansible#11273]
##### Issue Type:

Bug report.
##### Ansible Version:

1.9.1
##### Ansible Configuration:

N/A
##### Environment:

FreeBSD 10.1.
##### Summary:

When using the to_json filter on a dict variable, when one key has a boolean or null value and a second key's value has embedded newlines, the second key's value with the embedded newlines do not get escaped.
##### Steps To Reproduce:

Failing playbook

```

---
- name: Testing playbook
  hosts: all
  vars:
    test_data:
      newlines: |
        one
        two
        three
      boolean: true
  tasks:
    - copy:
        content: "{{ test_data | to_json }}"
        dest: "~/test.json"
```
##### Expected Results:

test.json should have `{"boolean": true, "newlines": "one\ntwo\nthree\n"}`.
##### Actual Results:

test.json contains:

```
{"boolean": true, "newlines": "one
two
three
"}
```

Same thing happens when the `boolean` key is `false` or `null`.
