### ISSUE TITLE
unarchive + sudo + Solaris = broken

### ISSUE THREAD

**Issue by ericcberg** [ansible/ansible#11282]
I am using ansible to run CIS CAT scripts and found that my script was running fine on my Linux hosts but on Solaris I was getting this output: 

fatal: [coeusdev.acsu.buffalo.edu] => ssh connection closed waiting for a privilege escalation password prompt

When running this step:

```
  - name: install the app
    unarchive: src=./ciscat.zip dest={{ install_dir }}
    when: not dir.stat.exists 
    sudo: yes
```

I tried manually copying the file over, to simplify matters, and ran this pared down script:

```
- hosts: solaris-dev
  sudo: yes
  gather_facts: no

  tasks:
  - name: install the app
    unarchive: copy=no src=./ciscat.zip dest=/opt/cis-cat-full
```

I got the same results. For some reason, it seems unarchive doesn't play nice with sudo through ansible with Solaris 10 target machines.
