### ISSUE TITLE
Looping of hosts in a group in a jinja2 template does not work in v2

### ISSUE THREAD

**Issue by linuxbsdfreak** [ansible/ansible#11296]
Hi,

Have the following 
step-10/hosts

```
[web]
host1.example.org ansible_ssh_host=192.168.33.11 ansible_ssh_user=root
host2.example.org ansible_ssh_host=192.168.33.12 ansible_ssh_user=root

[haproxy]
host0.example.org ansible_ssh_host=192.168.33.10 ansible_ssh_user=root
```

step-10/haproxy.yml

```
- hosts: haproxy
  tasks:
    - name: Installs haproxy load balancer
      apt: pkg=haproxy state=installed update_cache=yes

    - name: Pushes configuration
      template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
      notify:
        - restart haproxy

    - name: Sets default starting flag to 1
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
      notify:
        - restart haproxy 

  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted
```

Template 

```
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

listen cluster
    bind {{ ansible_eth1['ipv4']['address'] }}:80
    mode http
    stats enable
    balance roundrobin
{% for backend in groups['web'] %}
    server {{ hostvars[backend]['ansible_hostname'] }} {{ hostvars[backend]['ansible_eth1']['ipv4']['address'] }} check port 80
{% endfor %}
    option httpchk HEAD /index.php HTTP/1.0
```

Invoking the following 

```
ansible-playbook -i step-10/hosts  step-10/haproxy.yml

Error:

TASK [Pushes configuration] *****************************************************
fatal: [host0.example.org]: FAILED! => {"msg": "UndefinedError: 'list object' has no attribute 'web'", "failed": true, "changed": false}
```

Works in v1
