### ISSUE TITLE
unchanged_when

### ISSUE THREAD

**Issue by larry-s** [ansible/ansible#11292]
**Issue Type:** Feature Request

**Ansible Version:**
ansible 1.9.1
  configured module search path = None
No configuration changes

**Environment:**
Ubuntu 14.04.02

**Summary:**
Please add a new task parameter unchanged_when (or similar) to allow the unchanged status to be recorded for a task. This would be similar to failed_when and changed_when.

At present the only way to implement this it either to ignore errors or to enumerate all other conditions. Neither of these is an adequate alternative to the requested tag

**Sample script:**

```
- name: Install Nagios Packages
  apt: pkg={{ item }} state=present
  with_items:
  - libapache2-mod-php5
  - build-essential
  - libgd2-xpm-dev
  - python-passlib
  - nagios3

- name: Fix file owner
  command: dpkg-statoverride --update --add nagios www-data 2710 /var/lib/nagios3/rw
  register: dpkg_result
  unchanged_when: "'already exists; aborting' in dpkg_result.stderr"
```

(There probably needs to be be an extra test for the initial run.)
