### ISSUE TITLE
[Cron module] validate cron_file parameter

### ISSUE THREAD

**Issue by aotd1** [ansible/ansible#11295]
**Issue Type:** Feature Idea
**Component Name:** cron module
**Ansible Version:** 1.9.1
**Managed environment:** Ubuntu 12.04
**Summary:**
We can use invalid file names like "blabla.example.com.conf" for cron files, but based on [documentation](http://manpages.ubuntu.com/manpages/maverick/en/man8/cron.8.html)

> Files must conform to the same naming convention as used by run-parts(8): they must consist solely of upper- and lower-case letters, digits, underscores, and hyphens. 

Maybe need to add validation and throw error/show hint for invalid names?

**Steps To Reproduce:**

``` yaml
  - name: ensure cron config is present
    sudo: yes
    cron:
      cron_file: "example_some.cool.site.com.conf"
      user: root
      state: present
      minute: 0
      hour: 3
      day: "*"
      month: "*"
      weekday: 7
      name: "Send statistics to Zabbix"
      job: "echo run some job"
```

**Expected Results:**
Throw error or show hint about invalid file name

**Actual Results:**
Cron ignores this job
