### ISSUE TITLE
vars_prompt fails to pass along values in 1.9.1

### ISSUE THREAD

**Issue by chris-short** [ansible/ansible#11312]
I don't even know how to describe this but this works in 1.8.4 and does not in 1.9.1.

When using vars_prompt and 1.9.1 a value does not appear to be getting passed along somewhere

PLAYBOOK

```
  vars_prompt:
    - name: "innodb_buffer_pool_ratio"
      prompt: "Percentage of memory to use for innodb_buffer_pool_size as an integer (MAX: 0.80)"
      default: 0.75
      private: no
  vars:
    innodb_buffer_pool_size: "{{ (ansible_memtotal_mb * innodb_buffer_pool_ratio)|int }}M"
```

TEMPLATE:

```
innodb_buffer_pool_size: {{ innodb_buffer_pool_size }}
```

When innodb_buffer_pool_size is called in a template a zero is populated where in 1.8.4 a real number (that's accurate) is populated.
