### ISSUE TITLE
Add default(omit) functionality for sub keys

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#11340]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
omit filter

##### ANSIBLE VERSION
```
1.9.1
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
OS X 10.10.3

##### SUMMARY
[`default(omit)` is very useful but only works for top level keys (arguments of the module) and not sub keys](https://groups.google.com/forum/#!topic/ansible-project/Gz1WYxpqIy0).
Failed workarounds:
- `default('')` passes an empty string
- `default(~)` fails to parse
- `default('~')` passes the tilde

##### STEPS TO REPRODUCE
Run this ec2 module task without the 'build_number' variable.
``` yaml
  - name: provision an instance
    ec2:
      ec2_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      region: "{{ region }}"
      key_name: "{{ key }}"
      group: "{{ security_group_name }}"
      instance_type: "{{instance_type }}"
      monitoring: yes
      image: "{{ instance_store_ami_data.ami }}"
      vpc_subnet_id: "{{ subnet_euw1c }}"
      assign_public_ip: yes
      wait: true
      exact_count: 1
      count_tag:
        role: sid
        env: "{{ environment_name }}"
        build: "{{ build_number | default(omit) }}"
      instance_tags:
        role: sid
        env: "{{ environment_name }}"
        build: "{{ build_number | default(omit) }}"
        status: new
```

##### EXPECTED RESULTS
Build tag is not assigned to the instance.

##### ACTUAL RESULTS
The EC2 machine is created with a build tag of `__omit_place_holder__6248a11ef81332080f31b81d2894e811f905b723`.

**Comment by bborysenko** [comment]
Same issue with omit (ansible 1.9.4)

task:

```
- name: Create the PHP-FPM pool configurations
  template:
    src: php-fpm-pool.conf.j2
    dest: "{{ owox_php_fpm_pool_dir }}/{{ item.name }}.conf"
    owner: root
    group: root
    mode: 0644
    backup: yes
  with_items: owox_php_fpm_pools
  when: owox_php_fpm_enable and owox_php_fpm_pools|length > 0
```

template:

```
...
group = {{ item.group }}
group2 = {{ item.undefined_var|default(omit) }}
...
```

result:

```
 group = apache
+group2 = __omit_place_holder__a16d0c071033dda1d823e5ed156ead67ce13db72
```
