### ISSUE TITLE
authorized_key: exclusive=yes with multiple key files

### ISSUE THREAD

**Issue by crane-denny** [ansible/ansible#11347]
If I `exclusive=yes` is set it is not possible to add multiple keys by looping through a list of files. They has to be in one file (like mentioned in the docs ;)). Otherwise the last keys wins and every update would trigger a change. 

Something like this would be nice if possible:

``` yaml
- name: root public key authentication
  authorized_key:
    user: root
    key: "{{ item }}"
    exclusive: yes
  with_file:
    - key1.pub
    - key2.pub
    - key3.pub
```
