### ISSUE TITLE
enable do/until with async tasks

### ISSUE THREAD

**Issue by ahanwadi** [ansible/ansible#11351]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.0

##### SUMMARY
When a task is marked as async, there is no way to loop until a condition is met.
With poll:0 and async_status you can poll for async task to complete but you cannot repeat the original async task itself until a condition is met.

```
cat /tmp/async-test.yml 

---
# Run through the test of an async command

- hosts: all
  tasks:
    - name: "Check an async command"
      command: /bin/sleep 3
      async: 5
      poll: 1
      register: command_result
      until: command_result.failed
      retries: 5
      delay: 10
```

```
$ansible-playbook -i localhost, /tmp/async-test.yml                                    
 ____________
< PLAY [all] >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


 _________________
< GATHERING FACTS >
 -----------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [localhost]
 ______________________________
< TASK: Check an async command >
 ------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


fatal: [localhost] => error while evaluating conditional: command_result.failed: {% if command_result.failed %} True {% else %} False {% endif %}

FATAL: all hosts have already failed -- aborting
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


           to retry, use: --limit @/opt/ashishkh/async-test.retry

localhost                  : ok=1    changed=0    unreachable=2    failed=0 
```
