### ISSUE TITLE
redis-server not added to startup on Ubuntu 14.04

### ISSUE THREAD

**Issue by olalonde** [ansible/ansible#11354]
I have this task:

``` yaml
- name: install redis package
  apt: "name={{ item }} state=latest update_cache=yes"
  with_items:
    - redis-server
- name: start the redis service
  service: name=redis-server enabled=yes started=yes
```

but when I reboot my server, `redis-server` doesn't auto-start. Am I doing something wrong or is this a bug?

**Comment by bennojoy** [comment]
@olalonde there were a few bugs related to service module, can you please try with latest devel branch or the rc for 1.9.2
$ git checkout v1.9.2-0.2.rc2
$ git submodule update
$ . hacking/env-setup

**Comment by olalonde** [comment]
Well, the following seems to have fixed the issue:

``` yaml
- name: check if Redis is running
  service: name=redis-server state=started

- name: enable redis-server to survive reboot
  service: name=redis-server enabled=yes
```
