### ISSUE TITLE
Force handler throws an error

### ISSUE THREAD

**Issue by ssenaria** [ansible/ansible#11355]
Running stable 1.9.2

Task:

```
- name: Install Perl modules
  command: sudo rpm -Uvh {{ rpm_repository }}/{{ item.key }}-{{ item.value.svn_tag }}123.rpm --force
  with_dict: deploy_modules_perl
  force_handlers: True
  notify: announce_hipchat
```

Command:

```
$ ansible-playbook -i hosts perl.yml --tags 'perl'
ERROR: force_handlers is not a legal parameter in an Ansible task or handler
```

**Comment by TrungLam** [comment]
http://docs.ansible.com/playbooks_error_handling.html#handlers-and-failure

force_handlers should be placed in your plays and not your tasks.

I have yet to explore this feature, but here's how I think it's suppose to be used:

```
---
- hosts: webservers
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  force_handlers: True
  tasks:
  - name: ensure apache is at the latest version
    yum: pkg=httpd state=latest
  - name: write the apache config file
    template: src=/srv/httpd.j2 dest=/etc/httpd.conf
    notify:
    - restart apache
  - name: ensure apache is running (and enable it at boot)
    service: name=httpd state=started enabled=yes
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
```
