### ISSUE TITLE
set_fact skipping

### ISSUE THREAD

**Issue by rncry** [ansible/ansible#11369]
The following code works under ansible 1.9 but fails on the latest devel checkout. It runs the same rules, but skips the set_fact command.

```
- name: Set zookeeper ID facts
  gather_facts: True
  hosts: zookeeper
  user: username
  sudo: True
  tasks:
    - set_fact: zkid={{ item.0 | int + 1 }}
      when: hostvars[item.1]['ansible_hostname'] == ansible_hostname
      with_indexed_items: groups['zookeeper']
```

This assigns a unique id to each zookeeper instance dynamically.

**Comment by rncry** [comment]
Output from 1.9:

```
TASK: [set_fact zkid={{ item.0 | int + 1 }}] ********************************** 
skipping: [172.20.121.14] => (item=(0, u'172.20.121.13'))
skipping: [172.20.121.12] => (item=(0, u'172.20.121.13'))
ok: [172.20.121.13] => (item=(0, u'172.20.121.13'))
skipping: [172.20.121.12] => (item=(1, u'172.20.121.14'))
skipping: [172.20.121.13] => (item=(1, u'172.20.121.14'))
ok: [172.20.121.14] => (item=(1, u'172.20.121.14'))
skipping: [172.20.121.13] => (item=(2, u'172.20.121.12'))
ok: [172.20.121.12] => (item=(2, u'172.20.121.12'))
skipping: [172.20.121.14] => (item=(2, u'172.20.121.12'))
```

**Comment by RXminuS** [comment]
+1 Same issue, working in 1.9 not working latest dev branch.

```
- name: Set facts for api subnet
  set_fact:
    api_subnet_id: "{{item.id}}"
  when: item.resource_tags.tier == "{{pipeline_env}}-api"
  with_items: vpc.subnets
  tags:
    - provision

- debug: var=api_subnet_id
```

expected debug: "subnet-xxxxxxxx"
given debug: "api_subnet_id"

**Comment by bcoca** [comment]
@rncry, looks like a bug in with_indexed_items in v2 

@RXminuS you should not be using {{ }} in when.

**Comment by sheldonh** [comment]
It's not just `with_indexed_items`. Same problem with `with_items`.

This works:

``` yaml
---
-
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    networks:
      v4:
        - ip_address: 10.128.X.X
          type: private
        - ip_address: 104.131.X.X
          type: public
  tasks:
    - file:
        path: ./public_ip_address.txt
        state: absent
    - shell: echo -n "{{ item.ip_address }}" >> ./public_ip_address.txt
      when: item.type == "public"
      with_items: networks.v4
    - shell: cat ./public_ip_address.txt
      register: public_ip_address_cat
    - set_fact:
        public_ip_address: "{{ public_ip_address_cat.stdout }}"
    - debug:
        msg: "{{ public_ip_address }}"
```

And this doesn't:

``` yaml
---
-
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    networks:
      v4:
        - ip_address: 10.128.X.X
          type: private
        - ip_address: 104.131.X.X
          type: public
  tasks:
    - set_fact:
        public_ip_address: "{{ item.ip_address }}"
      when: item.type == "public"
      with_items: networks.v4
    - debug: msg="{{ hostvars.localhost }}"
```

The latter fails with:

```
PLAY: ***************************************************************************

TASK [set_fact public_ip_address={{ item.ip_address }}] *************************
{'skip_reason': 'Conditional check failed', 'item': {u'ip_address': u'10.128.X.X', u'type': u'private'}, 'skipped': True, 'changed': False}
{'item': {u'ip_address': u'104.131.X.X', u'type': u'public'}, 'changed': False, 'ansible_facts': {u'public_ip_address': u'104.131.X.X'}}
skipping: [localhost]

TASK [debug msg={{ public_ip_address }}] ****************************************
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "ERROR! the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'public_ip_address' is undefined"
}

PLAY RECAP **********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by ofpiyush** [comment]
PS: this is generic skip issue, affects all places where when clause skips items.

I just tried removiong my fix for the following code

``` yaml
add_host: name={{ item.ip_address }} groups=digiocean_new_droplet_group
with_items: droplet_presence_response.droplet.networks.v4
when: item.type == 'public'
```

And my result got skipped (it happens because skip tries to follow the same logic as failed/ changed) 

**Current implementation**
If ONE item fails, loop should fail.
If ONE item skips, loop should skip

But they are fundamentally different. So I've left failed etc alone and changed skip logic.

**New implementation**
If ONE item fails, loop should fail.
If ALL items are skipped, loop should skip.
