### ISSUE TITLE
group_vars/all clobbering group_vars/tag_Environment_demo (variable precedence)

### ISSUE THREAD

**Issue by gavD** [ansible/ansible#11379]
I use group_vars and I want is to define defaults in inventory/group_vars/all and override them for different environments, which I differentiate using AWS tags.
## inventory/group_vars/all contents

``` yaml

---
database_user: 'alluser'
```
## inventory/group_vars/tag_Environment_demo contents

``` yaml

---
database_user: 'demouser'
other_value: 'other'
```
## Playbook provision-server.yaml

I am using [EC2 dynamic inventory](http://docs.ansible.com/intro_dynamic_inventory.html). My playbook looks like this:

``` yaml

---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "aws_topology/{{ environment }}.yaml"
  tasks:
    - name: Generate Launch List
      launch_list:
        config="{{ topology | to_json }}"
      register: launch_list

    - name: Launch instance(s) of base box
      ec2: image='ami-a10897d6'
           instance_type="{{ item.1.instance }}"
           keypair='ansible'
           instance_tags='{"Environment":"{{ environment }}","Name":"{{ instance_name }}-ii-{{ item.0 + 1 }}"}'
           region='{{ item.1.region }}'
           aws_zone='{{ item.1.zone }}'
           vpc_subnet_id='{{ item.1.subnet }}'
           wait=true
           assign_public_ip=yes
      register: ec2
      with_indexed_items: launch_list.instances

    - set_fact:
        instances: "{{ ec2.results|map(attribute='instances')|list }}"

    - add_host:
        hostname={{ item.public_ip }}
        groupname="tag_Environment_{{ environment }},ec2hosts"
      with_flattened: instances

    - name: Wait for instances to listen on port 22
      wait_for:
        state=started
        host={{ item.public_ip }}
        port=22
      with_flattened: instances

- hosts: ec2hosts
  gather_facts: true
  user: ec2-user
  sudo: yes
  tasks:
  - debug: msg="database_user is {{ database_user }} other_value is {{ other }}"
```
## Test case

When I run my playbook with `ansible-playbook provision_server -e environment=demo`:

**Expected result**: `database_user is demouser other_value is other`
**Observed result**: `database_user is alluser other_value is other`

It seems that:
1. `inventory/group_vars/tag_Environment_demo` is definitely getting used, because other_value is set
2. `inventory/group_vars/all` clobbers `inventory/group_vars/tag_Environment_demo` because it uses 'alluser' not 'otheruser'

I'm tearing my hair out, can anybody help me?
## Notes

```
$ ansible-playbook --version
ansible-playbook 1.9.0.1
  configured module search path = None
$ python --version
Python 2.7.9
```
