### ISSUE TITLE
Regression between 1.7.2 and 1.8.4 prevents dynamic "cascaded" vars

### ISSUE THREAD

**Issue by russellballestrini** [ansible/ansible#11404]
**Regression**

Functionality regressed between version 1.7.2 and 1.8.4 which prevents a var defined in the first `vars_files` to be used in the lookup of a last `vars_files`. In my example below, the "tier" variable is defined in `~/customers/vars/{{ id }}.yml` and is used to include additional variables in tier'd vars files.

```

---
  # should only run on web nodes in a VPC, like webstg01.
  - name: my_web_app
    vars_prompt:
      id: 'please enter the customer id'
    vars_files:
      - '~/customers/vars/{{ id }}.yml'
      - '~/customers/vars/tier-{{ tier }}.yml'
    sudo: yes
    hosts: '{{id}}:&{{id}}-web'
    roles:
      - { role: 'nginx'  }
      - { role: 'rails_app'  }
      - { role: 'my_web_app'  }
```

**Work arounds:**
1. Prompt or pass the tier var in addition to id.  This is not ideal because the tier is sort of a constant and shouldn't be changed once its defined.
2. Include additional vars dynamically using `pre_tasks` and `include_vars` in each play.
   
   ```
   ---
   # should only run on web nodes in a VPC, like webstg01.
   - name: my_web_app
     vars_prompt:
       id: 'please enter the customer id'
     sudo: yes
     hosts: '{{id}}:&{{id}}-web'
     vars_files:
       - '~/customers/vars/{{ id }}.yml'
     pre_tasks:
       - include_vars: '~/customers/vars/tier-{{ tier }}.yml'
     roles:
       - { role: 'nginx'  }
       - { role: 'rails_app'  }
       - { role: 'my_web_app'  }
   ```
