### ISSUE TITLE
keyword environment not working in v2

### ISSUE THREAD

**Issue by majidaldo** [ansible/ansible#11401]
works in latest 1.9 but not latest v2. error message is: error the field (..) has an invalid value and could not be converted to an dict

```
- hosts: localhost
  gather_facts: false
  vars:
    regularvar: abc
    env:
      var1: asdf

  tasks:
    - name: echoooo
      command: echo $var1
      environment: env
```

**Comment by bcoca** [comment]
well, env looks like a string in this context, try:

environment: "{{env}}"

**Comment by jfpucheu** [comment]
I identify the same issue, environment not working

**Comment by majidaldo** [comment]
yea v2 would complain about the quotes.

**Comment by jfpucheu** [comment]
```
   env:
      http_proxy: http://X.X.X.X:3128
      https_proxy: http://X.X.X.X:3128

     environment: "{{ env }}"
```

Not working with quotes too !
