### ISSUE TITLE
ec2:vpc module does not support Network Interface as a gateway

### ISSUE THREAD

**Issue by rfein-hearst** [ansible/ansible#11427]
The VPC module doesn't seem to support network interface as a gateway. Some topologies use a network interface rather than an instance-id to allow for failover scenarios, but ansible doesn't currently support it.   

```
 route_tables:
           - 172.18.6.128/26
           routes:
             - dest: 0.0.0.0/0
               gw: i-4db9e0ba
               resource_tags: {"Name":"private"}
             - dest: 10.0.0.0/8
               gw: eni-f0693d97
```

`<Response><Errors><Error><Code>InvalidGatewayID.NotFound</Code><Message>The gateway ID 'eni-f0693d97' does not exist</Message></Error></Errors><RequestID>2b47c29b-c867-454d-
8257-15481c1b9f96</RequestID></Response>`
