### ISSUE TITLE
stat, command etc module error when using "name" in tasks

### ISSUE THREAD

**Issue by shrikeh** [ansible/ansible#11466]
Using: devel version of ansible

steps to reproduce:
Create a task as:

```
- name: Check if JumpCloud is already installed
  stat: 
   path: /opt/jc
  register: jc_installed
```

Expected result: information on directory, whether or not the directory actually exists, populated to the variable jc_installed.

Actual result: playbook refuses to run, with the following message:

```

ERROR! this task 'stat' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

The error appears to have been in '[playbook-dir]/roles/jumpcloud/tasks/main.yml': line 2, column 3, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Check if JumpCloud is already installed
  ^ here
```
