### ISSUE TITLE
Tags specified with the role get ignored, but work when specified via cli

### ISSUE THREAD

**Issue by iby** [ansible/ansible#11474]
I want to use tags inside the role to filter tasks that will be run. When I specify them via cli as such, everything works as expected:

``` sh
ansible-playbook tst.yml --tags=tag2
```

If I specify the same inside the `tst.yml` playbook they get ignored.

``` yml
- hosts: application
  gather_facts: false
  roles:
    - { role: tst, tags: [ 'tag2' ] }
    # or - { role: tst, tags: tag2 }
    # or other valid syntax forms
```

This happens with 1.9.2. There are multiple sources with examples that indicate that this must work, including the official [docs](http://docs.ansible.com/playbooks_tags.html#tags) – the example from there fails.
