### ISSUE TITLE
Custom filter failing ("no filter named ..." ) when used with with_items 

### ISSUE THREAD

**Issue by andersbc** [ansible/ansible#11481]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0 (devel 139138c604)

```
ansible 2.0.0 (devel 139138c604) last updated 2015/07/03 12:38:26 (GMT +200)
lib/ansible/modules/core: (detached HEAD ff69ce7912) last updated 2015/07/03 12:38:49 (GMT +200)
lib/ansible/modules/extras: (detached HEAD 4e48ef9eca) last updated 2015/07/03 12:38:49 (GMT +200)
v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/06/11 22:17:01 (GMT +200)
v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/06/11 22:17:04 (GMT +200)
configured module search path = /opt/ansible/library
```
##### Ansible Configuration:

Not sure it has any relevance, but just to be sure: I installed via git to `/opt/ansible`. I didn't change anything in the config. I can't find ansible.cfg i the above path, though (the issue guide lines asks me to compare that with the most recent version on git)
##### Environment:

Local: Ubuntu 15.04. The issues reproduces on local connection and on a Ubuntu 14.04 vagrant VM box.
##### Summary:

A custom filter, which seems to work just fine in other contexts, fails with the error message `"ERROR! template error while templating string: no filter named [name of the filter]"` when used in a **'with_items'** loop. 
##### Steps To Reproduce:

Put the files below in the same folder and run: `$ ansible-playbook testplay.yml -i 127.0.0.1,` (inlucde the trailing comma).  For convenience I have created [a gist with the files](https://gist.github.com/andersbc/1b89dc80a7b33dcdab48).

testplay.yml:

``` YAML

---
- hosts: 127.0.0.1
  connection: local

  vars:
    mylist:
    - bar: first
      foo: a
    - bar: second
      foo: b
    - bar: third
      foo: c

    my_filter: ['first', 'second']

    # Create a new var with my custom filter applied:
    my_filtered_list: "{{ mylist | byattr('bar', my_filter) }}"

  tasks:


  # works fine - only 'first' and 'second' items are shown
  - name: "test 1"
    debug: msg="{{ my_filtered_list }}" 

  # also fine
  - name: "test 2"
    debug: msg="{{ item }}"
    with_items: "{{ mylist }}"

  # fails!? with: ...no filter named 'byattr'
  - name: "test 3"
    debug: msg="{{ item }}"
    with_items: "{{ my_filtered_list }}"
```

core.py:

``` python
def filter_list(inputlist, attrib, lookuplist):
    result = []

    for item in inputlist:
        if item[attrib] in lookuplist:
            result.append(item)

    return result

class FilterModule(object):
    def filters(self):
        return {
            "byattr": filter_list,
        }
```

ansible.cfg:

``` ini
[defaults]
filter_plugins = .
```
##### Expected Results:

```
TASK [test 3] *******************************************************************
{'msg': {u'foo': u'a', u'bar': u'first'}, 'verbose_always': True, 'item': {u'foo': u'a', u'bar': u'first'}}
{'msg': {u'foo': u'b', u'bar': u'second'}, 'verbose_always': True, 'item': {u'foo': u'b', u'bar': u'second'}}
ok: [127.0.0.1]
```
##### Actual Results:

```
TASK [test 3] *******************************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "ERROR! template error while templating string: no filter named 'byattr'", "failed": true}
```

~~(note the extra ' postfixed to "byattr" in the error message.)~~ (correction: I read the message wrong. there is no extra ' )
