### ISSUE TITLE
'with_items' seems to introduce Unicode strings in objects defined inplace

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible#11506]
I am having several cases of unicode strings ( appearing in the output as u'somestring' ) being passed to mysql_db: command and causing problems.

It seem that this occurs whenever a with_items (or with_indexed_items or others) iterates over a list of variables defined in place:

```
- debug:
    msg: "{{ item }}"
  with_items:
    - { f1: "aaaaaaaaaa", f2: "{{ 'aaaaaaaaaa' }}" }
```

the output is as follows

```
ok: [local-vm] => (item={'f1': 'aaaaaaaaaa', 'f2': u'aaaaaaaaaa'}) => {
    "item": {
        "f1": "aaaaaaaaaa",
        "f2": "aaaaaaaaaa"
    },
    "msg": {
        "f1": "aaaaaaaaaa",
        "f2": "aaaaaaaaaa"
    }
}
```

After searching I found this fix in Jinja2 that might help here...
https://github.com/ntrrgc/jinja2/commit/b815d68462392a51c2280a25ff3b484885f9c9f2?diff=split

I am running ansible 1.9.2 on ubuntu 14.04.
Any ideas or workarounds?

**Comment by joaocc** [comment]
I am also noticing this effect (unicode being introduced even when expanding boolean variables).
The impact is huge and unpredictable.

For instance, "git:" doesn't recognize the parameter "update:" when it has been expanded, since it is "u'true'" instead of "True"

**Comment by jimi-c** [comment]
Hi @joaocc, can you give a real-world example of how this is causing problems? Also, can you test this against the current devel branch to see if the same problem is occurring there?

Thanks!

**Comment by joaocc** [comment]
I have a set of scripts where I define if I want git to update and/or force via something like:

```
is_this_dev: true
repo_git_behaviour:
    do_force: "{{ is_this_dev }}"
    do_update: "{{ is_this_dev }}"
...
git:
    ...
    update: "{{ repo_git_behaviour.do_update }}"
    force: "{{ repo_git_behaviour.do_force }}"
```

(this is a simplification, but it gets the point across)
If I run it like this, git will not do anything.
With the next one, it works as intended:
    ...
    git:
        ...
        update: "{{ is_this_dev }}"
        force: "{{ is_this_dev }}"

I am using PPA-based install, so it's not easy for me to change to PIP install at this moment.

Thx
