### ISSUE TITLE
vars_prompt, prompts even when no groups are in the designated environment

### ISSUE THREAD

**Issue by blakedietz** [ansible/ansible#11507]
## Expected :

When running an ansible playbook that includes a role whose group is **not** contained in the given environment, the `vars_prompt` prompt in the role is **not** run.
## Outcome :

When running an ansible playbook that contains a role whose group is **not** contained in the given environment, the `vars_prompt` prompt in the role is run.
## Example blah-environment :

```
[web]
blah

[database-allinone]
blah
```
## Example deploy-blah.yml :

``` yml
- hosts : foo
  vars_prompt :
    - name : "branch_name"
      prompt : "Which branch would you like to deploy from?"
      default : "bar"
  roles:
    - blah-deploy
```
## deploy.yml

``` yml
- hosts: localhost
  tasks:
   ...
- include: deploy-blah.yml
```
## Running the command

`ansible-playbook -i ./environment/blah-environment ./deploy.yml`

So even though a prompt would not be expected since the role which is included in `deploy.yml` is run for hosts in the `foo` group, the prompt is still displayed. This happens even though the environment does not contain the `foo` group.
