### ISSUE TITLE
Roles being ignored when executed against different hosts in different plays

### ISSUE THREAD

**Issue by jamiehannaford** [ansible/ansible#11514]
I have a playbook with two plays in it, each addresses a different host group:

``` yaml
- name: Configure host1
  hosts: host1
  remote_user: root
  roles:
    - { role: nginx }
    - { role: php-fpm }
    - { role: magento, is_admin: True }

- name: Configure host2
  hosts: host2
  remote_user: root
  roles:
    - { role: nginx }
    - { role: php-fpm }
    - { role: magento, is_admin: False }
```

I've omitted the `vars` section, which contain different values for each play. 

I expect the `nginx` and `php-fpm` roles to be executed against the `host2` group, but right now they're being ignored. The `magento` role is run on the second host, though, which leads me to think that it does so because there's a different val passed in for `is_admin`. 

How do I get the second set of roles to run?
