### ISSUE TITLE
Unable to mount multiple swap files

### ISSUE THREAD

**Issue by mcreenan** [ansible/ansible#11529]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2
##### Ansible Configuration:

```
[defaults]
inventory = ec2.py
private_key_file = <private_key_path>
remote_user = <remote_user>
roles_path = ./roles
host_key_checking = False
nocows = 1
vault_password_file = <vault_password_path>
```
##### Environment:

Running Ansible from OSX 10.10.1
OS being managed is Amazon Linux 2015.03
##### Summary:

When using the mount module to create/mount two separate swap files, only the latter swap file gets written to /etc/fstab
##### Steps To Reproduce:

Run a task file with the following (Note that /root/swapfile1 and /root/swapfile2 should already be configured to be used as swap with dd and mkswap)

```
- mount: name=none
         src=/root/swapfile1
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  sudo: true
- mount: name=none
         src=/root/swapfile2
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  sudo: true
```
##### Expected Results:

The following lines in /etc/fstab

```
/root/swapfile1 none swap sw 0 0
/root/swapfile2 none swap sw 0 0
```
##### Actual Results:

```
/root/swapfile2 none swap sw 0 0
```

**Comment by mcreenan** [comment]
Here is a more complete test case.

For testing, I edited my inventory to contain exactly 1 server which I created for this test case.

_configure-swap-files.yml_

``` yaml
---
- hosts: all
  tasks:
  - include: swap.yml path=/swapfile1 size_in_mb=100
  - include: swap.yml path=/swapfile2 size_in_mb=100
```

_swap.yml_

``` yaml
---
- name: Create empty swap files
  command: dd if=/dev/zero of={{ path }} bs=1M count={{ size_in_mb }}
           creates="{{ path }}"
  sudo: true

- name: Change swap file permissions
  file: path="{{ path }}"
        owner=root
        group=root
        mode=0600
  sudo: true

- name: "Check swap file type"
  command: file {{ path }}
  register: swapfile
  changed_when: false
  sudo: true

- name: Make swap file
  command: "sudo mkswap {{ path }}"
  when: swapfile.stdout.find('swap file') == -1
  sudo: true

- name: Write swap entry in fstab
  mount: name=none
         src={{ path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  sudo: true

- name: Enable swap
  command: "swapon {{ path }}"
  when: ansible_swaptotal_mb <= 0
  sudo: true
```

Here's the output when I ran the configure-swap-files.yml playbook:

```
╰→ ansible-playbook configure-swap-files.yml

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [<IP ADDRESS>]

TASK: [Create empty swap files] ***********************************************
changed: [<IP ADDRESS>]

TASK: [Change swap file permissions] ******************************************
changed: [<IP ADDRESS>]

TASK: [Check extra swap file type] ********************************************
ok: [<IP ADDRESS>]

TASK: [Make extra swap file] **************************************************
changed: [<IP ADDRESS>]

TASK: [Write extra swap entry in fstab] ***************************************
changed: [<IP ADDRESS>]

TASK: [Mount extra swap] ******************************************************
changed: [<IP ADDRESS>]

TASK: [Create empty swap files] ***********************************************
changed: [<IP ADDRESS>]

TASK: [Change swap file permissions] ******************************************
changed: [<IP ADDRESS>]

TASK: [Check swap file type] ********************************************
ok: [<IP ADDRESS>]

TASK: [Make swap file] **************************************************
changed: [<IP ADDRESS>]

TASK: [Write swap entry in fstab] ***************************************
changed: [<IP ADDRESS>]

TASK: [Enable swap] ******************************************************
changed: [<IP ADDRESS>]

PLAY RECAP ********************************************************************
<IP ADDRESS>             : ok=13   changed=10   unreachable=0    failed=0
```

Here's the /etc/fstab file:

```
#
LABEL=/     /           ext4    defaults,noatime  1   1
tmpfs       /dev/shm    tmpfs   defaults        0   0
devpts      /dev/pts    devpts  gid=5,mode=620  0   0
sysfs       /sys        sysfs   defaults        0   0
proc        /proc       proc    defaults        0   0
/swapfile2 none swap sw 0 0
```
