### ISSUE TITLE
git module fails to interpret bool parameter (assumes Unicode) - v1.9.2

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible#11524]
#### ISSUE TYPE
Bug Report

#### COMPONENT NAME
git module

#### ANSIBLE VERSION
1.9.2

#### SUMMARY

I'm opening this as a more general case of #11506 and after doing more extensive troubleshooting.
I have been testing with Ansible 1.9.2 on ubuntu 14.04.

I'll try to explain how to reproduce this.
First, the Ansible/Jinja/YAML code:

```
..........................................................
varprefix__git_update: true
..........................................................
varprefix__deploy:
  repo:
    dir: "repo"
    extract:
      - to: "rrrrr"
        git:
          url:     "{{ varprefix__git_repo }}"
          update:  "{{ varprefix__git_update|default(false)|bool }}"
..........................................................
- debug:
    msg: "{{ varprefix__deploy.repo.extract }}"

- name: deploy via git
  git:
    repo:      "{{ item.git.url }}"
    dest:      "/tmp/path/to/repo"
    clone:     yes
    update: true
#!!!update:    "{{ item.git.update }}"
#!!!update:    "{{ item.git.update  |default(true) }}"
#!!!update:    "{{ item.git.update  |default(true) |bool }}"
  with_items: varprefix__deploy.repo.extract
..........................................................
```

Note the lines marked with "#!!!" for later.

1st execution (with hardwired value for "update:") - line breaks added for readability:

```
TASK: [moduleprefix--somemodule | debug ] **************************************** 
ok: [local-vm] => {
    "msg": [
        {
            "git": {
                "update": "True",
                "url": "ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git",
                "version": "master"
            },
            "to": "rrrrr"
        }
    ]
}

TASK: [moduleprefix--somemodule | somemodule (git clone)] ********** 
<local-vm> REMOTE_MODULE git version=master depth=1 repo=ssh:********@bitbucket.org/uuuuu/ggggggggggggggggggggg.git accept_hostkey=True dest=/var/www/site.rrrrr_website/repo/rrrrr 
recursive=False force=False
failed: [local-vm] => (item={'to': 'rrrrr', 'git': {'url': u'ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git', 
'version': u'master', 'update': u'True'}}) => {"failed": true, "item": {"git": 
{"update": "True", "url": "ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git", 
"version": "master"}, "to": "rrrrr"}}
msg: Local modifications exist in repository (force=no).

FATAL: all hosts have already failed -- aborting
```

Nevermind the error at the end. It means git is working as intended (in this case, updating a repo with changes w/o the force paramenter).
The interesting stuff is that the variable appears correct (in the debug), and also on the 2nd part of the debug message, but appears as \* 'version': u'master', 'update': u'True'\* when reported in "item=".
But, in this case all would be ok.

Now, 2nd time, with _update:    "{{ item.git.update }}"_

```
TASK: [moduleprefix--somemodule | debug ] **************************************** 
ok: [local-vm] => {
    "msg": [
        {
            "git": {
                "update": "True",
                "url": "ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git",
                "version": "master"
            },
            "to": "rrrrr"
        }
    ]
}

<local-vm> REMOTE_MODULE git version=master depth=1 repo=ssh:********@bitbucket.org/uuuuu/ggggggggggggggggggggg.git 
update='<built-in method update of dict object at 0x7f11f96fec58>' accept_hostkey=True dest=/var/www/site.rrrrr_website/repo/rrrrr 
recursive=False force=False
failed: [local-vm] => (item={'to': 'rrrrr', 'git': {'url': u'ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git', 
'version': u'master', 'update': u'True'}}) => {"failed": true, "item": {"git": 
{"update": "True", "url": "ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git", "version": "master"}, "to": "rrrrr"}}
msg: Boolean <built-in method update of dict object at 0x7f11f96fec58> not in either boolean list

FATAL: all hosts have already failed -- aborting
```

At this point it seems that expansion of the boolean value causes some kind of problem.

3rd attempt with _update: "{{ item.git.update  |default(true) |bool }}"_

```
TASK: [moduleprefix--somemodule | debug ] **************************************** 
ok: [local-vm] => {
    "msg": [
        {
            "git": {
                "update": "True",
                "url": "ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git",
                "version": "master"
            },
            "to": "rrrrr"
        }
    ]
}

TASK: [moduleprefix--somemodule | somemodule (git clone)] ********** 
<local-vm> REMOTE_MODULE git version=master depth=1 repo=ssh:********@bitbucket.org/uuuuu/ggggggggggggggggggggg.git 
update=False accept_hostkey=True dest=/var/www/site.rrrrr_website/repo/rrrrr 
recursive=False force=False
ok: [local-vm] => (item={'to': 'rrrrr', 'git': {'url': u'ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git', 
'version': u'master', 'update': u'True'}}) => {"after": "1d9b80fd6a5aa4b61d150b10f3923668e61709e1", "before": "1d9b80fd6a5aa4b61d150b10f3923668e61709e1", 
"changed": false, "item": {"git": 
{"update": "True", "url": "ssh://git@bitbucket.org/uuuuu/ggggggggggggggggggggg.git", 
"version": "master"}, "to": "rrrrr"}}
```

Here,  it (incorrectly) finishes, since it skips updating the repository, even though update is set to True.

This behaviour also happens in other modules.
The fact that it "fails" silently is insidious because it doesn't give you any clue on what is happening.
Any help is appreciated.
Thanks

**Comment by joaocc** [comment]
An additional piece of information:

Running with _update:    "{{ ez123__phpfox3__git_update }}"_  behaves the same as with *update: true".

This is consistent with previous observations in that the problem usually occurs in objects and not variables.

**Comment by adamdyson** [comment]
Is there a workaround for this issue?

**Comment by alikins** [comment]
I can't reproduce this exactly with devel branch, but trying a simplified of referencing a 'update' is causing problems. Looks like it could be the issues referenced at http://docs.ansible.com/ansible/playbooks_variables.html#what-makes-a-valid-variable-name

gist of output at https://gist.github.com/alikins/c452f548711c5f7bbb7f8f34953e0062

``` yaml
---
- hosts: localhost
  gather_facts: false
  vars:
      test_update: true
      some_dict:
          update: "{{ test_update }}"
          other_item: "blippy"
      update: "{{ test_update }}"

  tasks:
      - name: debug some_dict var
        debug:
            var: some_dict

      - name: debug some_dict.update
        debug:
            var: some_dict.update

      - name: debug some_dict.update msg
        debug:
            msg: "some_dict.update: {{ some_dict.update }}"

      - name: debug some_dict.update type_debug
        debug:
            msg: "{{ some_dict.update|type_debug }}"

      - name: debug vars update
        debug:
            var: update

      - name: assert some_dict.update is not a method
        assert:
            that:
             - some_dict.update|type_debug != "builtin_function_or_method"
        ignore_errors: true

      - name: assert some_dict.update is true
        assert:
            that:
             - some_dict.update == true
```

output:

```
[fedora-25:ansible (devel % u=)]$ ansible-playbook -vvvvv repro/git_update_boolean_11524/more_simpler.yml 
Using /home/adrian/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin uncensored of type stdout, v2.0 from /home/adrian/src/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: more_simpler.yml *****************************************************************************************************************************************************************************************
1 plays in repro/git_update_boolean_11524/more_simpler.yml

PLAY [localhost] ***************************************************************************************************************************************************************************************************
META: ran handlers

TASK [debug some_dict.update] **************************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/git_update_boolean_11524/more_simpler.yml:11
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "var": "some_dict.update"
        }, 
        "module_name": "debug"
    }, 
    "some_dict.update": "<built-in method update of dict object at 0x7f0d47d20a28>"
}

TASK [debug some_dict.update msg] **********************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/git_update_boolean_11524/more_simpler.yml:15
ok: [localhost] => {
    "_ansible_no_log": false, 
    "_ansible_verbose_always": true, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "msg": "some_dict.update: <built-in method update of dict object at 0x7f0d47d20a28>"
        }, 
        "module_name": "debug"
    }, 
    "msg": "some_dict.update: <built-in method update of dict object at 0x7f0d47d20a28>"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

```
