### ISSUE TITLE
Vault encrypted dictionary values displayed in log output

### ISSUE THREAD

**Issue by AdeMiller** [ansible/ansible#11538]
My vault file contains the following set of values for Python keyrings:

```
python_keyring:
  "myserver.com" : { user: "myuser", password: "mypassword" }
 ...
```

I have a task that sets these keyring values on the target server:

```
- name: Set python keyring password
  tags:
  - app
  command: python -c "import keyring; keyring.set_password('{{item.key}}', '{{item.value.user}}', '{{item.value.password}}')"
  changed_when: False
  with_dict: python_keyring
```

This results in the following output:

```
TASK: [appserver | Set python keyring password] ******************************* 
ok: [theserver.com] => (item={'key': 'myserver.com', 'value': {'password': 'mypassword', 'user': 'myuser'}})

```

This this an issue when running interactively but is far more serious when running on my TeamCity server for automated builds as it means that the password will appear in clear in every build log.
