### ISSUE TITLE
[Suggestion] Ansible retry and timeout at hosts level.

### ISSUE THREAD

**Issue by amiorin** [ansible/ansible#11551]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
N/A

##### SUMMARY
The structure of my playbook is :

``` yml

---
- hosts: zookeeper
  roles:
    - zookeeper

- hosts: kafka
  roles:
    - kafka

- hosts: mesosmaster
  roles:
    - mesos-master
```

The failures are always most of the time operational and they require just a restart of the playbook.
It would be very convenient to have two keys:

``` yml

---
- hosts: zookeeper
  retries: 3
  timeout: 600
  roles:
    - zookeeper
```

It means retry the zookeeper block 3 times in case of failure or timeout (600 secs) and then give up.
