### ISSUE TITLE
[feature request] change|success|failed on plays

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#11571]
# Summary:

If a play has a name, the play should have a `state` which can be used in other plays.
## General work
- If any task in a play has changed --> `play|changed` is true
- If any task in a play has failed --> `play|failed` is true
- if no tasks in a play have failed --> `play|success` is true
- if all tasks have been skipped --> `play|skipped` is true

_Note_: a play can have failed and changed at the same time.
## Pre-Conditions:
- Play must have a name
### Example 1: changed

```
- name: play1
  tasks:
  - shell: /bin/true creates=/bin/true
  - shell: date

- name: play2
  tasks:
  - shell: echo play 1 has changed because >=1 tasks has changed
    when: play1|changed
```
## Example 2: failed

```
- name: play1
  tasks:
  - shell: /bin/true
  - shell: /bin/false

- name: play2
  tasks:
  - shell: echo play 1 has failed because >=1 tasks has failed
    when: play1|failed

  - shell: echo play 1 changed because >=1 tasks has changed
    when: play1|changed
```
## Example 2: success and skipped

```
# a play all tasks are skipped
- name: play1
  tasks:
  - shell: /bin/true creates=/bin/true
  - shell: /bin/false creates=/bin/false

- name: play2
  tasks:
  - shell: echo play 1 has only skipped tasks
    when: play1|success and play1|skipped
```
## Example 3: success and not only skipped, but changed

```
# a play all tasks are skipped
- name: play1
  tasks:
  - shell: /bin/true
  - shell: /bin/false creates=/bin/false

- name: play2
  tasks:
  - shell: echo play 1 has not only skipped tasks
    when: play1|success and not play1|skipped

  - shell: echo play 1 has also changed tasks
    when: play1|changed
```
