### ISSUE TITLE
Handlers are not running in proper order when using tags

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#11574]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2
##### Environment:

Ubuntu 12.04
##### Summary:

According to the ansible documentation

> ... handlers are automatically processed between ‘pre_tasks’, ‘roles’, ‘tasks’, and ‘post_tasks’ sections.

However, when running ansible-playbook with tags, this is not the case. Instead, the handlers are all run at the end of the play.

This issue was observed when running ansible-tower on ubuntu 12.04 when installed with either pip or apt-get. The issue was not present on OSX Yosemite.
##### Steps To Reproduce:

/roles/handler_test/tasks/main.yml

``` yaml
- name: Some task
  debug: msg="Running some task"
  changed_when: True
  notify: some handler
  tags:
    - test
```

/roles/handler_test/handlers/main.yml

``` yaml
- name: some handler
  debug: msg="some handler"
```

/handlers-test.yml

``` yaml
- hosts: local
  connection: local
  gather_facts: false

  roles:
    - role: handler_test

  post_tasks:
    - name: post
      debug: msg="This is a post task"
      tags:
        - test
```

```
ansible-playbook handlers-test.yml -i hosts --tags=test
```
##### Expected Results:

```
PLAY [local] ******************************************************************

TASK: [handler_test | Some task] **********************************************
changed: [127.0.0.1] => {
    "changed": true,
    "msg": "Running some task"
}

NOTIFIED: [handler_test | some handler] ***************************************
ok: [127.0.0.1] => {
    "msg": "some handler"
}

TASK: [post] ******************************************************************
ok: [127.0.0.1] => {
    "msg": "This is a post task"
}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [local] ******************************************************************

TASK: [handler_test | Some task] **********************************************
changed: [127.0.0.1] => {
    "changed": true,
    "msg": "Running some task"
}

TASK: [post] ******************************************************************
ok: [127.0.0.1] => {
    "msg": "This is a post task"
}

NOTIFIED: [handler_test | some handler] ***************************************
ok: [127.0.0.1] => {
    "msg": "some handler"
}

PLAY RECAP ********************************************************************
127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by smcavoy-travelbird** [comment]
I do not believe this is fixed.

Playbook:

```
---
- hosts: localhost
  sudo: no
  user: bob
  gather_facts: no
  vars:
    testme: hereitis
  handlers:
    - name: notifyme
      local_action: debug
      args:
        msg: notifyme
  pre_tasks:
    - name: pre task thing
      local_action: debug
      args:
         msg: Pre task
      tags: testtag
  tasks:
    - name: test local action variables
      local_action: copy
      args:
        content: "{{ testme }}"
        dest: /tmp/file1
      tags: testtag
      notify: notifyme
  post_tasks:
    - name: post task
      local_action: debug
      args:
        msg: post task
      tags: testtag
```

Run command:

```
ansible-playbook -i /tmp/inv tt.yml  --tags testags
```

Output:

```
PLAY [localhost] **************************************************************

TASK: [pre task thing] ********************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "Pre task"
}

TASK: [test local action variables] *******************************************
changed: [localhost -> 127.0.0.1]

TASK: [post task] *************************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "post task"
}

NOTIFIED: [notifyme] **********************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "notifyme"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0
```

Expected output:

```
PLAY [localhost] **************************************************************

TASK: [pre task thing] ********************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "Pre task"
}

TASK: [test local action variables] *******************************************
changed: [localhost -> 127.0.0.1]

NOTIFIED: [notifyme] **********************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "notifyme"
}

TASK: [post task] *************************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "post task"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0
```
