### ISSUE TITLE
Using dynamic inventory, access other hosts' variable where "other hosts" are list of hosts

### ISSUE THREAD

**Issue by boyangwang** [ansible/ansible#11583]
Hi, sorry I posted here instead of googlegroup or stackoverflow. I have researched the doc and internet quite thoroughly and would like to confirm:
1. Is the thing I'm trying to achieve (described below) impossible given the current framework?
2. Is there any plan to add the described functionality? If yes, I would love to contribute the patch.

---

I'm using dynamic inventory to manage my EC2 instances. It has to be dynamic because they are turned on/off frequently. I need to perform a custom task, so I've written my own module in Python. The task needs to be performed _only once, on localhost, and need metadata from EC2 instances_

Here's my playbook:

``` yaml

---
- name: set metadata using set_fact
  hosts: tag_ServiceType_region_server
  remote_user: ubuntu
  tasks:
    - set_fact:
        ec2_private_ip_address: "{{ ec2_private_ip_address }}"
        # other metadata to be used
    - my_module:
        hostvars: "{{ hostvars }}"
      run_once: true
      delegate_to: localhost
```

Here's my module:

``` python
#!/usr/bin/python
# -*- coding: utf-8 -*-

def main():
    ansible_module = AnsibleModule(
        argument_spec = dict(
            hostvars = dict(required=True),
        )
    )
    ansible_module.exit_json(hostvars=ansible_module.params.get('hostvars'))

from ansible.module_utils.basic import *
from ansible.module_utils.ec2 import *

main()
```

It prints

```
ok: [54.169.175.146] => {"invocation": {"module_name": "my_module", "module_args": {"hostvars": {}}}, "changed": false, "hostvars": {}}
```

Indicating that hostvars in my Python module will be empty. I can't access any info.
Now, I understand that I can get facts and vars of a particular host by doing `hostvars['52.74.170.52']`, but this is not feasible for me because 1. I need the information of a list of servers and exact number of servers is unknown 2. I need info of all servers all at once.
