### ISSUE TITLE
File lookup fails in a template when reading binary data, like an image file 

### ISSUE THREAD

**Issue by rodolfojcj** [ansible/ansible#11594]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
file lookup

##### ANSIBLE VERSION
1.9.2

##### SUMMARY

Hello!

Given a variable like this:

```
file_path: 'sample.bmp'
```

And given a Jinja2 template file with some content like this:

```
<image>{{ lookup('file', file_path) }}</image>
```

When a playbook that uses that template is run, a failure like the following occurs:

```
fatal: [my-remote-host] => {'msg': "AnsibleError: Unexpected error in during lookup: 'utf8' codec can't decode byte 0xff in position 57: invalid start byte", 'failed': True}                                                                                                                                                                  
fatal: [my-remote-host] => {'msg': 'One or more items failed.', 'failed': True, 'changed': False, 'results': [{'skipped': True, 'changed': False}, {'msg': "AnsibleError: Unexpected error in during lookup: 'utf8' codec can't decode byte 0xff in position 57: invalid start byte", 'failed': True}]}                                        

FATAL: all hosts have already failed -- aborting                                                                                                                        

PLAY RECAP ********************************************************************                                                                                         
       to retry, use: --limit @/home/osg/main.retry                                                                                                                 

my-remote-host            : ok=0    changed=0    unreachable=1    failed=0 
```

To reproduce it, you can try it with any binary file you have available, like a JPEG, PNG or BMP image.

I tried with some text file and it worked fine, so it seems it's related to the internal content of binary files.

The environment used is:
- Ansible 1.9.2
- Ubuntu 14.04 64 bits
- GNU/Linux kernel 3.19.0-22-generic

Please review it when you have time available and thanks a lot!

**Comment by rodolfojcj** [comment]
For completeness of the given sample, the Jinja2 template really has something like this:

```
<image>{{ lookup('file', file_path) | b64encode }}</image>
```

However, the failure is caused by the lookup part.

**Comment by bcoca** [comment]
the file lookup currently only handles text files, flagging this as a feature request

**Comment by behrangsa** [comment]
Any ETAs? I want to read a binary file, convert it to base 64, and POST it using the uri module.

At the moment I have to use `command` and `curl`:

```
- name: Upload files
  command: >
    curl -u {{ username }}:{{ password }}
         -F contents=@{{ item.src }} -F path="{{ item.target }}"
         {{ api_host }}/upload
    with_items:
      - src: files/1.bin
        target: /target/path/1.bin
      - src: files/2.bin
        target: /target/path/2.bin
```

This is not ideal as sometimes I need to encode the binary file in Base64 and use it as the value of a JSON field.

**Comment by bcoca** [comment]
@behrangsa use a slurp task

**Comment by abadger** [comment]
Going to close this.  lookups will never be able to handle binary data due to being implemented via jinja2.  We could write some module that might be able to handle things like this.  As bcoca points out fetch currently allows you to satisfy the specific use-case.  There's likely other use cases that are not satisfied by fetch but that would be a different feature rather than this one.  (Perhaps reading in a base64  string/file and then turning it into a binary file on the remote machine.... Would like to have a new bug with a use case to decide that, though.)

**Comment by lcarva** [comment]
So what is the recommendation if you do want to read a binary file into a variable, for example?

This, of course, does not work:
```
bin_data: "{{ lookup('file', 'bin-file') }}"
```

**Update**

You could use [slurp](https://docs.ansible.com/ansible/2.4/slurp_module.html) to achieve that:

```
- name: Load binary file into variable             
  local_action:                               
    module: slurp                             
    src: "bin-file"     
  register: bin_file
```
Contents can then be accessed via `bin_file.content` variable. Note that file content is base64 encoded. If that's not desirable, [fetch](https://docs.ansible.com/ansible/2.4/fetch_module.html#fetch) might be a better option.

**Comment by abadger** [comment]
Could you give a little higher level?  What do you want me to do with the
data from the binary file?

**Comment by lcarva** [comment]
Once the content of the binary file is stored in a variable, the template example from https://github.com/ansible/ansible/issues/11594#issuecomment-121652736 could be rewritten as such:
```
<image>{{ bin_file.contet }}</image>
```

The reason I came across this limitation of lookup-file is for a much different use case. I'm reading in file content to create a Secret object in an OpenShift cluster via [oc](https://docs.ansible.com/ansible/2.4/oc_module.html) module, but the general idea is the same.

I'm documenting what I found here to save the next person a couple of hours. However, it would be really nice if there was a lookup explicitly for binary files to avoid having to create a variable as I mentioned earlier.

**Comment by onelapahead** [comment]
Agreed with @lcarva, this is my exact use case as well. I have a keystore I need to make an OpenShift Secret out of and I'm using Ansible's `k8s` plugin:

```yml
- name: "create files secret"
  k8s:
    state: present
    merge_type: merge
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{application}}-{{component}}-{{version}}-files"
        namespace: "{{target_namespace}}"
        labels:
          app: "{{application}}"
          version: "{{version}}"
          component: "{{component}}"
      data:
        keystore.p12: "{{lookup('file', inventory_dir + '/group_vars/all/keystore.p12') | b64encode}}"
```

Which then fails with:

```
 {"msg": "An unhandled exception occurred while running the lookup plugin 'file'. Error was a <type 'exceptions.UnicodeDecodeError'>, original message: 'utf8' codec can't decode byte 0x82 in position 1: invalid start byte"}
```

I'll try the `slurp` work around, but its annoying to have to make a tempfile/var to read a binary file.
