### ISSUE TITLE
Variables from other roles substitute into task names as {{ variable_name }}

### ISSUE THREAD

**Issue by garthk** [ansible/ansible#11605]
Not the usual case of failed substitution you'd expect with this output:

``` plain
TASK: [role2 | {{ source_variable }}] ***************************************** 
ok: [localhost] => {
    "msg": {
        "expected": "value", 
        "expected_if_failed": "{{ variable }}"
    }
}
```

I'd expect this output if `source_variable` didn't exist, or was from `group_vars` and thus couldn't be substituted (#3103, which if as-expected is still a wart), or couldn't be templated for some other reason (e.g. #10347), but that's not quite the case:

`{{ variable }}` is:
- substituting properly in the task itself (at least for `debug`, `command`, and `shell`)
- substituting as the name of the variable it came from in the task name.

If it could be substituted into the name, I'd expect `TASK: [role2 | value]`.

If it couldn't be substituted into the name, I'd expect `TASK: [role2 | {{ variable }}]`.

Instead, the task name incorporates the name of the source variable: `TASK: [role2 | {{ source_variable }}]`.

Demo:

`variable-from-other-role-substitutes-as-its-own-name.yaml`:

``` yaml

---
- name: demonstrate strange variable substitution
  hosts: localhost
  connection: local
  gather_facts: no
  sudo: no

  roles:
  - role1
  -
    role: role2
    variable: "{{ source_variable }}"
```

`roles/role1/defaults/main.yaml`:

``` yaml

---
source_variable: value
```

`roles/role2/tasks/main.yaml`:

``` yaml

---
- name: "{{ variable }}"
  debug:
    msg:
      expected: "{{ variable }}"
      expected_if_failed: "{{ '{{' }} variable {{ '}}' }}"
```

Kick it off with:

```
ansible-playbook -i localhost, variable-from-other-role-substitutes-as-its-own-name.yaml
```
