### ISSUE TITLE
changed_when and flush_handlers can't work together

### ISSUE THREAD

**Issue by deimosfr** [ansible/ansible#11613]
Hi,

I'm having an issue with this code:

```
- name: remove database files when purging graphite-carbon
  debconf: name='graphite-carbon' question='Configuring graphite-carbon' value='no' vtype='string'
  notify:
    - carbon stop
  changed_when: false

- meta: flush_handlers
```

The flush handlers are not called at all if " changed_when: false" is set. As soon as I remove or comment this line, it works.

I don't think it's the normal comportment. Can you please confirm?

Thanks
