### ISSUE TITLE
Items from vault are shown in stdout

### ISSUE THREAD

**Issue by swsnider** [ansible/ansible#11630]
When I use a task like this:

``` yaml
- name: Run config statements
  sudo_user: apache
  shell: "./bin/config set {{item.key}} {{item.value}}"
  args:
    chdir: /opt/phabricator
  with_dict: "{{phabricator_config}}"
```

where {{phabricator_config}} comes from a vault file because it contains a db password, Ansible shouldn't output the text of the item when run.
