### ISSUE TITLE
template module breaks json

### ISSUE THREAD

**Issue by sheldonh** [ansible/ansible#11641]
##### Issue Type:

Bug report
##### Ansible Version:

Devel exhibits this behaviour from commit 301019059272ab0a1b288a20c9772107b592dccd onward.

```
ansible 2.0.0 (devel 2bc9004618) last updated 2015/07/18 18:16:04 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 291fef3b34) last updated 2015/07/18 18:16:32 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD ff2386faf4) last updated 2015/07/18 18:16:32 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/08 17:49:07 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/08 17:49:33 (GMT +200)
  configured module search path = None
```
##### Ansible Configuration:

None.
##### Environment:

Ubuntu 15.04 (x86_64)
Python 2.7.9
Jinja2 (2.7.3)
simplejson (3.6.5)
##### Summary:

JSON files rendered by the template module are invalid.

Whitespace is compressed (undesirable) and double quotes are converted to single quotes (show stopper).
##### Steps To Reproduce:

Create this template, called `array.json.j2`:

``` jinja
[
{% for pubkey_policy in pubkey_policies %}
    {
    "AttributeName": "PublicKeyPolicyName",
    "AttributeValue": "{{ pubkey_policy }}"
    }{% if loop.last %}{% else %},{% endif %}
{% endfor %}
]
```

Feed the template to the template module with this `playbook.yml`:

``` yaml
-
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    pubkey_policies:
      - Vault-1-PubKey-policy
      - Vault-2-PubKey-policy
      - Vault-3-PubKey-policy
  tasks:
    - template:
        src: ./array.json.j2
        dest: ./array.json
```

Apply the playbook and observe the generated `array.json`:

``` shell
ansible-playbook -i /dev/null playbook.yml
```
##### Expected Results:

The generated `array.json` should match what ansible 1.2 produces:

``` json
[
    {
    "AttributeName": "PublicKeyPolicyName",
    "AttributeValue": "Vault-1-PubKey-policy"
    },    {
    "AttributeName": "PublicKeyPolicyName",
    "AttributeValue": "Vault-2-PubKey-policy"
    },    {
    "AttributeName": "PublicKeyPolicyName",
    "AttributeValue": "Vault-3-PubKey-policy"
    }]
```
##### Actual Results:

The generated output is invalid (double quotes converted to single quotes) and less readable (whitespace compressed):

``` json
[{'AttributeName': 'PublicKeyPolicyName', 'AttributeValue': 'Vault-1-PubKey-policy'}, {'AttributeName': 'PublicKeyPolicyName', 'AttributeValue': 'Vault-2-PubKey-policy'}, {'AttributeName': 'PublicKeyPolicyName', 'AttributeValue': 'Vault-3-PubKey-policy'}]
```
