### ISSUE TITLE
Ansible 2.0 Breaks synchronize functionality, and completely changed the behavior.

### ISSUE THREAD

**Issue by xuchen81** [ansible/ansible#11649]
Issue type:
Bug report

Ansible version:
devel

Environment:

Unrelated but
Host: Mac 10.10.3 
Target: Ubuntu 10.4

The first issue is:
In 1.9, when I want to sync two folders on the remote server, I do:

```
- name: Sync app folder
  synchronize:
    src: "/home/ubuntu/test1"
    dest:  "/home/ubuntu/test2"
  delegate_to: "{{ inventory_hostname }}"
  sudo: yes
```

Now, it keeps giving me permission denied error.

The second issue is:
It looks like now it defaults to sync two folder on the remote server even if I don't specify delegate_to, in 1.9.2, without delegate_to, src will be my local, and dest will be my remote.

Thanks

**Comment by abadger** [comment]
Confirmed the second issue.  Here's a small playbook that shows the problems:

```
---
# Localhost is a fedora box
- hosts: rhel6-test
  vars:
    device_host: rhel6-test
    top_dir: /var/tmp
  tasks:
    - name: Push fedora file to rhel host
      synchronize:
        src: "/etc/redhat-release"
        dest: "/var/tmp/fedora-rel"
        mode: push
    - name: Pull redhat file to fedora host
      synchronize:
        src: "/etc/redhat-release"
        dest: "/var/tmp/redhat-rel"
        mode: pull
```

In current devel, both of those plays are copying the remote /etc/redhat-release file to a file on the remote machine.  So the remote machine ends up with /var/tmp/fedora-rel and /var/tmp/redhat-rel and both of those are the /etc/redhat-release from the rhel6 box, _not_ the one from the fedora box that ansible-playbook is being run from.
