### ISSUE TITLE
Git module "hangs" 	although accept_hostkey is set.

### ISSUE THREAD

**Issue by stephanadler** [ansible/ansible#11665]
I have a strange issue I can not really debug very well when using ansible in combination with vagrant. I have a Vagrant VM which is provisioned by ansible, including the checkout of two repos using git. When I run the VM the first time after a `vagrant destroy` by invoking `vagrant up` the following role will just get stuck.

From the playbook:

```
- name: checkout server
  sudo: yes
  hosts: all
  roles:
    - { role: checkout-stash }
  vars:
    git_file_dest:
      - {src: system_i.git, dest: /home/server}
      - {src: sim.git, dest: /home/simulator}
```

Role "checkout-stash"

```

---
- name: Create .ssh directory for root
  sudo: yes
  file: path=/root/.ssh state=directory

- name: Copy the key files
  copy: src=id_repo dest=/root/.ssh/git_key mode=0600

- name: Checking out repository
  git:
    repo: ssh://git@stash.REDACTED_HOST.net:7999/data/{{item.src}}
    dest: "{{item.dest}}"
    accept_hostkey: yes
    key_file: /root/.ssh/git_key
  with_items: git_file_dest
```

Interestingly this only gets stuck when it is called for the first time after the VM goes into provisioning. I can fix this problem by running `vagrant reload --provision`or by running the ansible generated command manually in the VM i.e. `/usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1437461648.61-236693718777259/git` everything will work find. When the VM is in the stuck state, I can take a look at the processes which will show:

```
13659 pts/0    Ss+    0:00 /bin/sh -c sudo -k && sudo -H -S -p "[sudo via ansible, key=aqdaozqdrnmyxqbrixatibcqxngqrqlw] password: "
13665 pts/0    S+     0:00 sudo -H -S -p [sudo via ansible, key=aqdaozqdrnmyxqbrixatibcqxngqrqlw] password:  -u root /bin/sh -c echo
13666 pts/0    S+     0:00 /bin/sh -c echo BECOME-SUCCESS-aqdaozqdrnmyxqbrixatibcqxngqrqlw; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /u
13667 pts/0    S+     0:00 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1437461648.61-236693718777259/git
13669 pts/0    S+     0:00 /bin/git ls-remote ssh://git@stash.REDACTED_HOST.net:7999/data/ld_system_i.git -h refs/heads/HEAD
13670 pts/0    S+     0:00 /bin/sh /home/vagrant/.ansible/tmp/ansible-tmp-1437461648.61-236693718777259/5mS88s -p 7999 git@stash.REDACTED_H
13671 pts/0    S+     0:00 ssh -i /root/.ssh/git_key -p 7999 git@stash.REDACTED_HOST.net git-upload-pack '/data/ld_system_i.git'
```

while on the host system the output is:

```
PLAY [checkout server] ********************************************************

GATHERING FACTS ***************************************************************
ok: [default]

TASK: [checkout-stash | Create .ssh directory for root] *******************
changed: [default]

TASK: [checkout-stash | Copy the key files] *******************************
changed: [default]

TASK: [checkout-stash | Checking out repository] **************************
```

and nothing happens after this line.

I was able to work-arround this problem, by adding `ssh_opts: "-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"` to the role, which leads me to the conclusion that `accept_hostkey: yes`might have some kind of an issue when being run for the very first time.
