### ISSUE TITLE
replace module: TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by Hubbitus** [ansible/ansible#11675]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0
  configured module search path = modules/
```

Master 7124504ccfd837d6a8e4124d619fb605ae92e0b0
##### Ansible Configuration:

I hope nothing related to settings.
##### Environment:

Fedora 22
##### Summary:

```
fatal: [egais.perf.monitor]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "One or more items failed", 
    "results": [
        {
            "ansible_notify": [
                "restart httpd"
            ], 
            "exception": "Traceback (most recent call last):\n  File \"<stdin>\", line 1833, in <module>\n  File \"<stdin>\", line 143, in main\n  File \"/usr/lib64/python2.7/re.py\", line 190, in compile\n    return _compile(pattern, flags)\n  File \"/usr/lib64/python2.7/re.py\", line 229, in _compile\n    p = _cache.get(cachekey)\nTypeError: unhashable type: 'dict'\n", 
            "failed": true, 
            "item": {
                "regexp": "^(LoadModule .+(?<!mod_mpm_prefork)\\.so)", 
                "replace": "#\\1"
            }, 
            "parsed": false
        }, 
        {
            "ansible_notify": [
                "restart httpd"
            ], 
            "exception": "Traceback (most recent call last):\n  File \"<stdin>\", line 1833, in <module>\n  File \"<stdin>\", line 143, in main\n  File \"/usr/lib64/python2.7/re.py\", line 190, in compile\n    return _compile(pattern, flags)\n  File \"/usr/lib64/python2.7/re.py\", line 229, in _compile\n    p = _cache.get(cachekey)\nTypeError: unhashable type: 'dict'\n", 
            "failed": true, 
            "item": {
                "regexp": "^#\\s*(LoadModule .+mod_mpm_prefork\\.so)", 
                "replace": "\\1"
            }, 
            "parsed": false
        }
    ]
}
```
##### Steps To Reproduce:

Task:

```
- name: Ensure non-threaded prefork used
  replace:
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    regexp: "{{item}}"
    replace: "^{{item}}$"
  with_items:
    - { regexp: '^(LoadModule .+(?<!mod_mpm_prefork)\.so)', replace: '#\1' }
    - { regexp: '^#\s*(LoadModule .+mod_mpm_prefork\.so)', replace: '\1' }
```
##### Expected Results:

In file:
http://pkgs.fedoraproject.org/cgit/httpd.git/tree/00-mpm.conf

Commented all LoadModule directives except mod_mpm_prefork.so
##### Actual Results:

Fail in module

**Comment by abadger** [comment]
This looks like you are handing a dictionary to the regexp parameter when you mean to hand over a field in the dictionary.  So you want something more like this in your playbook:

```
- name: Ensure non-threaded prefork used
  replace:
    dest: /etc/httpd/conf.modules.d/00-mpm.conf
    regexp: "{{item['regexp']}}"
    replace: "^{{item['replace']}}$"
  with_items:
    - { regexp: '^(LoadModule .+(?<!mod_mpm_prefork)\.so)', replace: '#\1' }
    - { regexp: '^#\s*(LoadModule .+mod_mpm_prefork\.so)', replace: '\1' }
```

I'll paste the mailing list information below in case you need more help beyond that.

# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
