### ISSUE TITLE
Regression in replace module with Ansible v2

### ISSUE THREAD

**Issue by qwazerty** [ansible/ansible#11673]
When using the replace module, the replace argument need to be double escaped to work properly on Ansible v2. For example with this playbook.

``` yaml
- name: Test replace
  # Using replace='\\1' works on Ansible v2
  replace: dest=/tmp/test regexp='^Hello (World)$' replace='\1'

- name: Test cat
  command: cat /tmp/test
```

This is the output of a cat with :
ansible 2.0.0 (detached HEAD a09ce4bd87) last updated 2015/07/21 15:10:03 (GMT +200)

``` bash
$ cat -e /tmp/test
^A$


TASK [Test replace] ************************************************************
changed: [10.1.7.215] => {"changed": true, "msg": "1 replacements made"}

TASK [Test cat] *********************************************************************
changed: [10.1.7.215] => {"changed": true, "cmd": ["cat", "/tmp/test"], "delta": "0:00:00.002099", "end": "2015-07-21 13:04:08.985338", "rc": 0, "start": "2015-07-21 13:04:08.983239", "stderr": "", "stdout": "\u0001", "stdout_lines": ["\u0001"], "warnings": []}
```

The same playbook is working with Ansible 1.9.2 : 

``` bash
$ cat -e /tmp/test
World$


TASK: [Test replace] ********************************************************* 
changed: [10.1.7.215] => {"changed": true, "msg": "1 replacements made"}

TASK: [Test cat] ****************************************************************** 
changed: [10.1.7.215] => {"changed": true, "cmd": ["cat", "/tmp/test"], "delta": "0:00:00.002175", "end": "2015-07-21 13:12:21.696866", "rc": 0, "start": "2015-07-21 13:12:21.694691", "stderr": "", "stdout": "World", "warnings": []}
```
