### ISSUE TITLE
django_manage: the field 'args' has an invalid value ... The error was: 'virtualenv' is undefined"

### ISSUE THREAD

**Issue by pdhar-tibco** [ansible/ansible#11698]
different issue

**Comment by pdhar-tibco** [comment]
user mistake

**Comment by pdhar-tibco** [comment]
This is happening when executing this initialize database (example 7-9 from Ansible Up & Running )

```
    - name: initialize database
      django_manage:
        command: createdb --noinput --nodata
        app_path: "{{ proj_path }}"
        virtualenv: "{{ venv_home }}"
      register: result
      changed_when: not result.failed and "Creating tables" in result.out
      failed_when: result.failed and "Database already created" not in result.msg
```

Running on latest git development branch 

```
TASK [initialize database] ******************************************************
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o Port=2222 -o IdentityFile="./.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 mkdir -p "$HOME/.ansible/tmp/ansible-tmp-1437606842.19-173331098251825" && chmod a+rx "$HOME/.ansible/tmp/ansible-tmp-1437606842.19-173331098251825" && echo "$HOME/.ansible/tmp/ansible-tmp-1437606842.19-173331098251825"
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> PUT /var/folders/83/hh7gmfkd7ydck1t3mvn8xczw0000gp/T/tmpqbtj7c TO /home/vagrant/.ansible/tmp/ansible-tmp-1437606842.19-173331098251825/django_manage
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o ControlPath="/tmp/ansible-ssh-%h-%p-%r" -o Port=2222 -o IdentityFile="./.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1437606842.19-173331098251825/django_manage; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1437606842.19-173331098251825/" >/dev/null 2>&1
fatal: [web]: FAILED! => {
    "changed": false,
    "cmd": "./manage.py createdb --noinput --nodata",
    "failed": true,
    "failed_when_result": true,
    "msg": "\n:stderr: Traceback (most recent call last):\n  File \"./manage.py\", line 27, in <module>\n    from django.core.management import execute_from_command_line\nImportError: No module named django.core.management\n",
    "path": "/home/vagrant/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games",
    "state": "absent",
    "syspath": [
        "/home/vagrant/.ansible/tmp/ansible-tmp-1437606842.19-173331098251825",
        "/usr/lib/python2.7",
        "/usr/lib/python2.7/plat-linux2",
        "/usr/lib/python2.7/lib-tk",
        "/usr/lib/python2.7/lib-old",
        "/usr/lib/python2.7/lib-dynload",
        "/usr/local/lib/python2.7/dist-packages",
        "/usr/lib/python2.7/dist-packages",
        "/usr/lib/pymodules/python2.7"
    ]
}
```
