### ISSUE TITLE
Strange behaviour when delegating to a host defined in a variable

### ISSUE THREAD

**Issue by elmundio87** [ansible/ansible#11705]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
1.9.1
```

##### CONFIGURATION
SSH connections are routed through a VM via a ProxyCommand

##### OS / ENVIRONMENT
Control Machine OS OSX 10.10.4
Managed OS CentOS 7

##### SUMMARY
When using a variable in a **delegate_to**, the connection hangs.

##### STEPS TO REPRODUCE
This doesn't work - it eventually times out.
```
- name: Wait for the server to come back
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22 
    state: started
  sudo: false
  delegate_to: "{{ ssh_delegate }}"
```
This works (using a hardcoded delegate host)
```
- name: Wait for the server to come back
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22 
    state: started
  sudo: false
  delegate_to: "10.128.0.100"
```
This also works (putting the variable into a with_items loop and referencing it in delegate_to)
```
- name: Wait for the server to come back
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22 
    state: started
  sudo: false
  delegate_to: "{{ item }}"
  with_items:
    - "{{ ssh_delegate }}"
```

##### EXPECTED RESULTS
I would expect all 3 examples to work the same way.

##### ACTUAL RESULTS
The first example fails
