### ISSUE TITLE
ec2_lc spot_price not working

### ISSUE THREAD

**Issue by garlandkr** [ansible/ansible#11712]
This is an example of what I'm doing to create a launch config in AWS, the result does not add a spot price in AWS when creating the launch config.

``` yaml
    image_id: "{{ lc_ami_id | default(ami_image) }}"
    keypair: removed
    security_group: removed
    instance_type: m3.medium
    role: removed
    ebs_optimized: false
    instance_monitoring: true
    assign_public_ip: true
    spot_price: "{{ ec2_spot_prices.m3.medium }}"
```

Tried with both Ansible 1.8.4 and 1.9.2

Variables:

``` yaml
# EC2 Spot price index
ec2_spot_prices:
  m3:
    2xlarge: 0.532
    large: 0.133
    xlarge: 0.266
    medium: 0.067
```
