### ISSUE TITLE
RHEL / Centos 7 and docker-py

### ISSUE THREAD

**Issue by xrow** [ansible/ansible#11717]
Hello,

the following task ...

``` yaml
- name: Build Docker images from Dockerfiles.
  docker_image:
    name: "build"
    tag: "0.1"
    path: "/root/provision"
    state: build
```

throwed  the following error on centos 7 

``` bash
TASK: [docker-image | Build Docker images from Dockerfiles.] ****************** 
failed: [localhost] => {"changed": true, "failed": true}
msg: Docker API error: client and server don't have same version (client : 1.19, server: 1.18)

FATAL: all hosts have already failed -- aborting
```

I fixed this my using an older docker-py.

``` bash
pip install -I docker-py==1.2.3
```

I would repect that this dependancy would be automaticly resovled.

``` bash
[root@172-17-42-1 ~]# docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): ba1f6c3/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): ba1f6c3/1.6.2
OS/Arch (server): linux/amd64
[root@172-17-42-1 ~]# ansible-playbook --version
ansible-playbook 1.9.2
  configured module search path = None
```
