### ISSUE TITLE
AWS profile with S3 module causes  runtime error

### ISSUE THREAD

**Issue by kern3020** [ansible/ansible#11755]
Hello, 

I am using s3. This task works file. 

```
- name: get test data from s3 for US production
  s3:
    bucket: ag-systems
    object: "/pipeline/simple_testset.tar.gz"
    dest: "{{ analysis_dir }}/simple_testset.tar.gz"
    mode: get
  when: "'{{ which_env }}' == 'production_us' and testset_tar.stat.exists == False"
```

I need to use AWS profile. When I add this 

```
- name: get test data from s3 for CN production 
  s3:
    bucket: ag-china-systems
    object: "/pipeline/simple_testset.tar.gz"
    dest: "{{ analysis_dir }}/simple_testset.tar.gz"
    profile: 'mushe'
    mode: get
  when: "'{{ which_env }}' == 'production_china' and testset_tar.stat.exists == False"
```

Ansible 1.9.2 with boto 2.38.0 fails on python 2.7.6 using ubuntu 14.04 lts. 

```
    return hasattr(boto.ec2.EC2Connection, 'profile_name')
AttributeError: 'module' object has no attribute 'ec2'
```

If I add a striaghforward import (i.e., 'import boto.ec2') in
ansible/module_utils/ec2.py, fixes the error.

-jk

**Comment by vascop** [comment]
The same setup except using OS X 10.10.5 and I have the same problem. Updating to ansible 1.9.4 didn't fix.

**Comment by mickael-ange** [comment]
Same problem with `cloudformation` module, Ansible version 1.9.4, Boto 2.38.0, Ubuntu 14.04.
Adding `profile` option gives me same error:

```
- name: Build stack
  cloudformation:
    stack_name: "{{ aws_cf_stack_name }}"
    tags: "{{ aws_cf_tags }}"
    state: present
    region: "{{ aws_region }}"
    profile: "{{ boto_profile }}"
```

The error:

```
    return hasattr(boto.ec2.EC2Connection, 'profile_name')
AttributeError: 'module' object has no attribute 'ec2'
```
