### ISSUE TITLE
Add ansible_connection variable

### ISSUE THREAD

**Issue by adarnimrod** [ansible/ansible#11771]
Hi.
I'd like to have an ansible_connection variable that specifies the connection method used (smart, local, etc.) added. In our infrastructure we have machines that run Ansible playbooks locally for deploying new versions of our applications. However some playbooks have tasks that are delegated to other machines and fail when run locally. It would be nice to include a when clause so that those tasks were skipped if run locally. For example:

```
- name: Create backup destination
  delegate_to: backup.example.com
  when: ansible_connection != 'local'
  file:
    path: /srv/backup
    owner: root
    group: root
    state: directory
    mode: 0777
```

Thanks.
