### ISSUE TITLE
synchronize doesn't work with more than one with_items

### ISSUE THREAD

**Issue by morungos** [ansible/ansible#11782]
Bug Report in Ansible 2.0. 

I've just encountered this weird synchronize issue, which seems to be different to the others but might be relevant. Basically, only one with_items value works, subsequent ones fail with permission issues. The message is:

```
failed: [studies.turalt.com] => (item={u'dest': u'{{webapp_directory}}', u'source': u'package.json'}) => {"cmd": "rsync --delay-updates -F --compress --archive --no-perms --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"package.json\" \"/usr/lib/studies\"", "failed": true, "item": {"dest": "{{webapp_directory}}", "source": "package.json"}, "msg": "rsync: mkstemp \"/usr/lib/.studies.umzWmz\" failed: Permission denied (13)\nrsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]\n", "rc": 23}
```

But because this goes away when split into separate tasks, that's probably some weird connection usage underneath. This includes solutions to the other synchronize issues, and in particular the `delegate_to`, without which the whole task hangs as reported by others. 

The simple version is as follows. This does not work:

```
- name: Webapp | Copy files
  synchronize:
    src: "{{ item.source}}"
    dest: "{{ item.dest }}"
  delegate_to: localhost
  with_items:
    - { source: './.tmp/deploy/service/', dest: '{{webapp_directory}}' }
    - { source: './.tmp/deploy/knex/', dest: '{{webapp_directory}}' }
```

But rewritten as below, all is well. This should obviously not be required. 

```
- name: Webapp | Copy files
  synchronize:
    src: "{{ item.source}}"
    dest: "{{ item.dest }}"
  delegate_to: localhost
  with_items:
    - { source: './.tmp/deploy/service/', dest: '{{webapp_directory}}' }

- name: Webapp | Copy files
  synchronize:
    src: "{{ item.source}}"
    dest: "{{ item.dest }}"
  delegate_to: localhost
  with_items:
    - { source: './.tmp/deploy/knex/', dest: '{{webapp_directory}}' }
```
