### ISSUE TITLE
Pause only executed at first host

### ISSUE THREAD

**Issue by huiyiqun** [ansible/ansible#11793]
This may be desired action for `pause`.

however, following plays do not work

``` yaml
- name: Start VPN(this succeeds immediately but VPN is not ready immediately)
  ...
  register: start_vpn

- name: Wait VPN up
  pause: seconds=20
  when: start_vpn | changed
```

If the VPN has been started on the first host, there will be no pause, and then tasks fail.

Is it possible to fix it gracefully?
