### ISSUE TITLE
support creates= semantics on command/shell module to not execute if file exists

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#118]
This is basically the puppet-hack to make shell scripts work upon reexecution.

**Comment by mpdehaan** [comment]
since command is parsed as a regular string, not a key/value string, we probably have to apply magic to pull this out of the options line.

command /sbin/foo a b c creates=XYZ and just parse the tokens out that include "creates", or require it to end with creates, or maybe even

#creates=XYZ 

Maybe I like that better

**Comment by mpdehaan** [comment]
mdehaan: some playbook wrapper syntax is an option
15:16 mdehaan: creates: ....
15:17 mdehaan: that first does a check to see which hosts have the file existing before running
15:17 mdehaan: and could work with all module types
15:17 mdehaan: a bit harder

**Comment by mpdehaan** [comment]
Decided on this, maybe only_if_remote gets renamed:

```
- tasks:
  - name: foo
    action: command blarg a b c d
    only_if_remote: test ! -f /etc/somefile
```
