### ISSUE TITLE
Overriding variables "include_vars" with "vars_files" doesn't work

### ISSUE THREAD

**Issue by vehovsky** [ansible/ansible#11807]
Bug Report in Ansible 2.0 & 1.9.2

test_playbook.yml:

```

---
- hosts: example
  gather_facts: False
  remote_user: root
  roles:
    - roleA

- hosts: example
  gather_facts: False
  remote_user: root
  vars_files:
    - vars/override.yml
  roles:
    - roleB

- hosts: example
  gather_facts: False
  remote_user: root
  roles:
    - { role: roleA, MY_VARIABLE: two }
```

roles/roleA/task/main.yml

```

---
- include_vars: defaults.yml
- debug: msg='Value is = {{ MY_VARIABLE }}'
```

roles/roleA/vars/defaults.yml

```

---
MY_VARIABLE: one
```

roles/roleB/task/main.yml

```

---
- debug: msg='Value is = {{ MY_VARIABLE }}'
```

vars/override.yml

```

---
MY_VARIABLE: two
```

Expected Result:

```
one
two
two
```

Actual Result (2.0 & 1.9.2):

```
one
one
two
```

ansible --version

```
ansible 2.0.0 (devel 222f04e387) last updated 2015/07/30 21:17:22 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 79f21c6ec9) last updated 2015/07/30 21:17:27 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 50f4b2c3de) last updated 2015/07/30 21:17:32 (GMT +200)
  v1/ansible/modules/core: (detached HEAD f8d8af17cd) last updated 2015/07/30 21:17:36 (GMT +200)
  v1/ansible/modules/extras: (detached HEAD 495ad450e5) last updated 2015/07/30 21:17:40 (GMT +200)
```

```
ansible 1.9.2
  configured module search path = None
```
