### ISSUE TITLE
'default' filter not possible for ansible_ssh_port

### ISSUE THREAD

**Issue by fuzzy-id** [ansible/ansible#11802]
The following fails because ansible doesn't seem to settle the ansible_ssh_port by default:

``` yaml
- name: Allow limited access to default ssh port
  ufw:
    port="{{ ansible_ssh_port }}"
    proto=tcp
    rule=limit
```

So I tried the following:

``` yaml
- name: Allow limited access to default ssh port
  ufw:
    port="{{ ansible_ssh_port|default(22) }}"
    proto=tcp
    rule=limit
```

Which fails:

```
fatal: [host] => One or more undefined variables: 'ansible_ssh_port' is undefined

$ ansible-playbook --version
ansible-playbook 1.9.2
```

In my opinion one of these (probably both) should succeed.

**Comment by fuzzy-id** [comment]
Even the following fails with the message mentioned above:

``` yaml
- name: Allow limited access to default ssh port if ansible_ssh_port not set
  ufw:
    port="22"
    proto=tcp
    rule=limit
  when: ansible_ssh_port is not defined
```
