### ISSUE TITLE
Ansible2 hangs with sudo:yes

### ISSUE THREAD

**Issue by ynnt** [ansible/ansible#11845]
```
ansible-playbook -i hosts base.yml -vv --ask-sudo-pass
SUDO password:

PLAY ****************************************************************************

TASK [setup] ********************************************************************
ok: [logs]

TASK [test] ******************************
ok: [logs]

TASK [test2] *************************
fatal: [logs]: FAILED! => {"failed": true, "msg": "ERROR! Connection closed waiting for privilege escalation password prompt: /home/ynnt/.ansible/tmp/ansible-tmp-1438685213.34-47645153366124\r\n "}
```

ansible version

```
ansible 2.0.0 (devel c3ce140dd2) last updated 2015/08/04 13:36:30 (GMT +300)
```

```
cat base.yml
- hosts: logs
  sudo: yes
  roles:
  - { role: prometheus_master, tags: [ 'prometheus' ] }
```

Also ansible ignores tags...
