### ISSUE TITLE
Fails parallel execution of tasks in playbook in all hosts

### ISSUE THREAD

**Issue by stevewker** [ansible/ansible#11847]
## I have contain following playbook to restart services.

```
hosts: test
tasks: 
 - name: service postfix restart
   command: service postfix restart
 - name: service dovecot restart
   command: service dovecot restart
 - name: service opendkim restart
   command: service opendkim restart
 - name: service apache2 restart
   command: service apache2 restart
 - name: service cron restart
   command: service cron restart
 While executing my playbook in 3 hosts the tasks done in each task are in sequential manner.But i want to execute the tasks in all hosts at a time.That means suppose postfix restart must be done in all hosts at a time. But this is not happening.this task happening one after another.
```

The following is my output:
PLAY [test] ******************************************************************\* 

TASK: [mail | service postfix restart] ***************************************\* 
changed: [srv613]
changed: [srv612]
changed: [dsrv143]

TASK: [mail | service dovecot restart] ***************************************\* 
changed: [srv613]
changed: [dsrv143]
changed: [srv612]

TASK: [mail | service opendkim restart] **************************************\* 
changed: [dsrv143]
changed: [srv613]
changed: [srv612]

TASK: [mail | service apache2 restart] ***************************************\* 
changed: [srv613]
changed: [srv612]
changed: [dsrv143]

TASK: [mail | service cron restart] ******************************************\* 
changed: [srv613]
changed: [dsrv143]
changed: [srv612]

PLAY RECAP *******************************************************************\* 
dsrv143                    : ok=5    changed=5    unreachable=0    failed=0  
srv612                     : ok=5    changed=5    unreachable=0    failed=0  
srv613                     : ok=5    changed=5    unreachable=0    failed=0   

the output getting from this playbook in serial order.That is not my requirement.I have tried different methods like forks and serial parameters.But nothing change i observed.
So please give an idea to execute a particular task in all hosts at a time.
