### ISSUE TITLE
Shell module not always return correct error code

### ISSUE THREAD

**Issue by Hubbitus** [ansible/ansible#11850]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible --version
$ ansible --version
ansible 2.0.0

$ rpm -q ansible
ansible-2.0-0.2.git.7d8afad.fc24.noarch
##### Ansible Configuration:

Irrelevant
##### Environment:

Fedora 22
##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!
##### Steps To Reproduce:

Playbook:

```
- hosts: 127.0.0.1
  connection: local

#    Correct fail with rc=1
#    - name: shell try 0
#      shell: echo "qwerty FAIL" | fgrep 'WHAT NOT EXISTS'

  tasks:
    - name: shell try 1 - exit
      shell: VAR="qwerty FAIL" ; echo "$VAR" | fgrep -q 'FAIL' && ( echo "<failed with data - $VAR>" >&2 ; exit 1 ) || exit 0

    - name: shell try 1 - true/false
      shell: VAR="qwerty FAIL" ; echo "$VAR" | fgrep -q 'FAIL' && ( echo "<failed with data - $VAR>" >&2 ; false ) || true
```
##### Expected Results:

All 3 variant should fail with non-0 return code.
##### Actual Results:

Only first (which is commented) failed as expected
