### ISSUE TITLE
HostVars is not JSON serializable

### ISSUE THREAD

**Issue by leedm777** [ansible/ansible#11877]
For debugging, I've been using `{{ vars | to_nice_json }}` in a template to give a dump of what variables have been defined in a play or role. I've also discovered a similar issue when using `{{ vars | to_yaml }}`.

With Ansible 2 (as of commit e16b24c), this fails with an error.

```
fatal: [XXX]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleError: ERROR! an unexpected type error occurred. Error was <ansible.vars.hostvars.HostVars object at 0x7f88a72ce8d0> is not JSON serializable"}
```

My code:

``` yaml
# roles/debug-vars/tasks/main.yml
- name: Dump all vars (use --diff to see them)
  action: template src=roles/debug-vars/templates/debug-vars.j2 dest=/dev/null
  tags: debug-vars
```

```
# roles/debug-vars/templates/debug-vars.j2
Module Variables ("vars"):
--------------------------------
{{ vars | to_nice_json }}
```
