### ISSUE TITLE
Doing a Registered Var and a conditional based on that registered var in the same task does not error out. 

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible#11892]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.9.2
  configured module search path = None

**Note**: this is not a bug in v2
##### Ansible Configuration:

default
##### Environment:

OSX to localhost and OSX to RHEL 6.5
##### Summary:

If you have a task that registers a var then has a conditional like `when` that references that registered var via `is defined`, the task does not error out. The task is evaluated to false every time.
##### Steps To Reproduce:

Do:

``` yml
    - stat:
        path: /tmp/
      register: temp
      when: temp.stat is defined and temp.stat.exists
```
##### Expected Results:

`error while evaluating conditional: temp.stat.exists`
or an undefined var error
##### Actual Results:

``` json
ok: [localhost] => {
    "var": {
        "temp": {
            "changed": false,
            "skipped": true
        }
    }
}
```
