### ISSUE TITLE
notify should take string or list

### ISSUE THREAD

**Issue by mgwilliams** [ansible/ansible#119]
``` yaml
- name: foo
  action: bar src=biz dest=baz
  notify: the-handler

# *or*

- name: foo
  action: bar src=biz dest=baz
  notify: 
  - third-fifth-handler
  - fifth-third-handler
```
