### ISSUE TITLE
script module no longer honors sudo/sudo_user/become_user

### ISSUE THREAD

**Issue by wincent** [ansible/ansible#11902]
I recently updated the version of Ansible I'm running from ebc8d48d34296fe010096f044e2b7591df37a622 to 29809bb83d6f3bf1f9ed3eb6655eadf9f380a0f3. I noticed that tasks such as the following:

```
- name: git-replicator | set-up bitbucket remotes
  script:
    setup-remote.sh bitbucket {{ item.bitbucket_url }} {{ git_public_repos_path }}/{{ item.name }}.git
  register: result
  changed_when: '"no change" not in result.stdout'
  failed_when: 'result.rc != 0'
  become_user: git
  with_items: git_public_repos
```

Are effectively ignoring the `become_user` declaration (also true if I go with the deprecated `sudo: yes` + `sudo_user: git` declarations).

I can see this in the output of a run with `-vvvvv`:

```
<example.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="~/.ssh/%r@%h:%p" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 example.com LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /home/ec2-user/.ansible/tmp/ansible-tmp-1438989104.97-55938930308685/setup-remote.sh bitbucket git@bitbucket.org:ghurrell/static-react-boilerplate.git /pub/git/public/static-react-boilerplate.git
```

As you can see, the `ssh` command is just running the uploaded script without `sudo`.

I believe this may be a regression, or is it intended behavior?

My workaround in the meantime is to put the relevant `sudo` commands inside the script itself, so this isn't a huge issue, but nevetheless, I thought it was worth bringing to your attention.

**Comment by wincent** [comment]
I should add, this happens even with an explicit:

```
become_method = sudo
```

in my `ansible.cfg`. And also happens for the command module, so this isn't just limited to the script module.

A straight `sudo: yes` task (with no `sudo_user`) appears to still use `sudo` as intended. I can see output like the following in the `-vvvvv` output:

```
<example.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="~/.ssh/%r@%h:%p" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 example.com /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=redacted] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-redacted; LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /home/ec2-user/.ansible/tmp/ansible-tmp-1438996666.11-168387693215200/upgrade-mysql.sh '"'"''
```

**Comment by wincent** [comment]
cc @bcoca, who I think has been doing some refactoring in the privilege-escalation area recently.

**Comment by bcoca** [comment]
I don't see become set, try adding become: true

On Sat, Aug 8, 2015 at 10:11 PM, Greg Hurrell notifications@github.com
wrote:

> cc @bcoca https://github.com/bcoca, who I think has been doing some
> refactoring in the privilege-escalation area recently.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ansible/ansible/issues/11902#issuecomment-129094499.

## 

Brian Coca

**Comment by wincent** [comment]
> I don't see become set, try adding become: true

Sorry, I should have made this clearer in my description. sudo isn't taking effect with that either, nor is it happening with:

```
sudo: yes
sudo_user: git
```

That's what I originally had in these playbooks, and had beeing working for over a year. I only switched to `become` (and `become_user`) to try and unbreak things once I noticed the change in behavior somewhere between c14f072a3ba210f50f5086e10e06b311445828dc and e7b5cb87828a49cfc8771ab3d83fda157d42972f (those are the correct hashes; for some reason, I pasted the wrong ones in my initial report).

**Comment by bcoca** [comment]
can you test with 1.9.2 or current devel? there was an issue with 1.9.0

**Comment by wincent** [comment]
@bcoca, this is with current `devel` (well, `HEAD~` of the `devel` branch; ie: e32d88760906da5ed473570218b5831292e0bfa8).

```
$ git log -1
commit e32d88760906da5ed473570218b5831292e0bfa8 (HEAD)
Merge: dbab703 b5f5404
Author: Brian Coca <bcoca@ansible.com>
Date:   Fri Aug 7 17:55:39 2015 -0400

    Merge pull request #11900 from jensenbox/patch-2

    Tiny typo fix
```

I just retested it to confirm that I am not going crazy:

```
- name: git-replicator | set-up bitbucket remotes
  script:
    setup-remote.sh bitbucket {{ item.bitbucket_url }} {{ git_public_repos_path }}/{{ item.name }}.git
  register: result
  become: true
  become_user: git
  changed_when: '"no change" not in result.stdout'
  failed_when: 'result.rc != 0'
  with_items: git_public_repos
```

Here's the `-vvvv` output:

```
<example.com> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="~/.ssh/%r@%h:%p" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ec2-user -o ConnectTimeout=10 example.com LANG=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /tmp/ansible-tmp-1439225242.86-145468933672039/setup-remote.sh bitbucket git@bitbucket.org:ghurrell/askpass.git /pub/git/public/askpass.git
```

Note the absence of `sudo` in the `ssh` invocation; it's just connecting as the default user (`ec2-user`) and running the script as-is.
