### ISSUE TITLE
mongodb_users module not creating users

### ISSUE THREAD

**Issue by shadyb** [ansible/ansible#11903]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

mongodb_user module
##### SUMMARY

I have the following task:

```
- name: Setup DB users
  mongodb_user: database={{ item.database }} name={{ item.user }} password={{ item.password }} state={{ item.state }} ssl={{ item.ssl }} roles={{ item.roles|default(omit) }}
  with_items:
    - '{{ mongo_users }}'
  when: mongo_users is defined
```

With the following list:

```
mongo_users:
  - database: 'gummy'
    user: 'bearuser'
    password: '123456admin1234567!'
    state: 'present'
    ssl: 'false'
```

When running the playbook, the task is set as 'changed' every time. Going into mongo shell, the db is created but when doing a `show users` for the given db, it does not show the user. I have tried disabling selinux to no avail.

Ansible version: 1.9.2
OS: centos 6.6
mongodb: 2.6.10
