### ISSUE TITLE
need to call os.path.expanduser around creates/removes in command module

### ISSUE THREAD

**Issue by arunthampi** [ansible/ansible#1191]
Tried running this task:

``` yaml
- name: Setup SSH keys for the current user
  shell /usr/bin/ssh-keygen -N '' -b 1024 -f ~/.ssh/id_rsa -t rsa -q creates=~/.ssh/id_rsa
```

and it runs the command even if the file exists (I tested it with /tmp/id_rsa instead of ~/id_rsa and it works as expected)

Have to use this workaround:

``` yaml
- name: Check for existing keypair
  action: shell head -1 ~/.ssh/id_rsa
  register: existing_key_pair

- name: Setup SSH keys for the current user
  action: shell /usr/bin/ssh-keygen -N '' -b 1024 -f ~/.ssh/id_rsa -t rsa -q
  only_if: "len('${existing_key_pair.stdout}') == 0"
```
