### ISSUE TITLE
only_if fails when the string being used in the conditional is multiline

### ISSUE THREAD

**Issue by arunthampi** [ansible/ansible#1192]
Failing Task:

``` yaml
- name: Check for existing keypair
  action: shell cat ~/.ssh/id_rsa
  register: existing_key

- name: Setup SSH keys for the current user
  action: shell /usr/bin/ssh-keygen -N '' -b 1024 -f ~/.ssh/id_rsa -t rsa -q
  only_if: "len('${existing_key.stdout}') == 0"
```

Have to use this workaround:

``` yaml
- name: Check for existing keypair
  action: shell head -1 ~/.ssh/id_rsa
  register: existing_key

- name: Setup SSH keys for the current user
  action: shell /usr/bin/ssh-keygen -N '' -b 1024 -f ~/.ssh/id_rsa -t rsa -q
  only_if: "len('${existing_key.stdout}') == 0"
```
