### ISSUE TITLE
intermittent problem with yum module

### ISSUE THREAD

**Issue by nicolaasuni** [ansible/ansible#1193]
Sometimes the playbooks fails without apparent reason.

When I execute the following task:

```
- name: Web Node Additional Packages
  action: yum pkg=$item state=installed
  with_items:
    - wget
    - ImageMagick
```

sometimes I get this error:

```
failed: [xx.xx.xx.xx] => (item=wget,ImageMagick) => {"changed": false, "failed": true, "item": "wget,ImageMagick", "msg": "No Package matching 'wget' found available, installed or updated", "rc": 0, "results": []}
```
