### ISSUE TITLE
playbook ignoring vars_files entry

### ISSUE THREAD

**Issue by harmw** [ansible/ansible#11959]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.2
##### Ansible Configuration:

none
##### Environment:

OSX
##### Summary:

The 2nd vars_file is not loaded.

```
 vars_files:
   - params/me/params.yml
   - params/me/{{ hostvars[inventory_hostname]['ostype'] }}_params.yml
 roles:
   - {
       role: windows-create-base,
       when: "'windows' in {{ hostvars[inventory_hostname]['ostype'] }}"
     }
```
##### Steps To Reproduce:

Put the above in a playbook and observe.
##### Expected Results:

Loading variables from a dynamic file (by name).
##### Actual Results:

The file is not included and silently ignored instead. When the file doesn't exist it is ignored as well, where normally a decent error is shown.

**Comment by bcoca** [comment]
EDIT: template notification

**Comment by ansibot** [comment]
@harmw closure has been requested for this issue or it has timed out waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
!needs_info

**Comment by bcoca** [comment]
this seems to have been fixed a while back:

play.yml
```yaml
- hosts: localhost
  gather_facts: false
  vars_files:
   - params.yml
   - test/{{hostvars[inventory_hostname]['inventory_hostname']}}_params.yml
  tasks:
    - debug: var=infile

```
test/localhost_params.yml
```yaml
infile: 123
```

results:
```
ok: [localhost] => {
    "infile": 123
}
```
