### ISSUE TITLE
yum module - remove repoquery hard dependency (for speed optimization)

### ISSUE THREAD

**Issue by kiranos** [ansible/ansible#11960]
##### Issue Type:

  Feature Idea
##### Ansible Version:

1.9.2
##### Ansible Configuration:

no modifications
##### Environment:

Debian 8 64bit (jessie)
##### Summary:

In the yum module, remove hard dependency for repoquery. (for speed optimization)
##### Steps To Reproduce:

Run:

```
- name: verify sudo,ntp,iotop is latest
  action: yum name={{ item }} state=latest
  with_items:
   - sudo
   - ntp
   - iotop
  when: ansible_os_family == "RedHat"
```

and then run the same with regular yum install sudo ntp iotop
##### Expected Results:

It would be very nice actually get this task completed much faster.
##### Actual Results:

Yum now takes a very long time and its because of repoquery depenency, there has been various people asking why this is,
- some resolve it by running yum from command: module.
- Others create an alternative module: http://blog.grozak.com/2014/04/04/01-yum2-ansible-module/ (the reason as described in the blogpost, speed)
- http://grokbase.com/t/gg/ansible-project/1486ckhr51/speed-up-yum-related-tasks here Michael suggested he's changed his mind about requiring repoquery, and that its worth revisiting.

For me managing 100 servers all with yum module, a run takes almost 2hours to complete, and 90% of the time spent is with the yum module.
