### ISSUE TITLE
vars_files should allow variables from first vars_file in second and beyond

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1196]
from someone's report on the mailing list

This is my playbook :

```

---
- hosts: ${HOST}
  user: root
  gather_facts: False

  vars_files:

  - vars/globals/vars_globals.yaml <= VARIABLES ARE DEFINED HERE (but some of them are the concatenation of vars defined below)

  - vars/globals/vars_env_${SITE_ENV}.yaml

  - vars/specifics/vars_site_${SITE_TYPE}.yaml

  - ../projects/${SITE_NAME}/${SITE_NAME}-${SITE_ENV}.yaml
```
