### ISSUE TITLE
register value issue when using conditionals

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#11986]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible --version
ansible 1.9.2
  configured module search path = /usr/share/my_modules/
##### Ansible Configuration:

default
##### Environment:

Managing target system CentOS 6.5
running Ansible from  OSX 10.10.4
##### Summary:

register variable issue when getting set from conditionals 
##### Steps To Reproduce:

```
- name: launch ec2 Classic instance
  ec2:
    image: "{{ ami_id }}"
    key_name: "{{ key_name }}"
    group: "{{ group }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    zone: "{{ region }}{{ zone }}"
    wait: true
    instance_tags: "{{ instance_tags }}"
  register: ec2
  when: vpc_subnet is undefined

- name: launch ec2 VPC instance
  ec2:
    image: "{{ ami_id }}"
    key_name: "{{ key_name }}"
    group: "{{ group }}"
    instance_type: "{{ instance_type }}"
    region: "{{ region }}"
    zone: "{{ region }}{{ zone }}"
    wait: true
    instance_tags: "{{ instance_tags }}"
    vpc_subnet_id: "{{ vpc_subnet }}"
    assign_public_ip: "{{ auto_assign_public_ip | default('yes') }}"
  register: ec2
  when: vpc_subnet is defined

- name: Add the new instance to host group
  add_host: hostname={{ item.public_dns_name }} groupname=launched
  with_items: ec2.instances
```
##### Expected Results:

Have the new ec2 instance public DNS added to the host group.
##### Actual Results:

TASK: [Add the new instance to host group] ************************************
fatal: [localhost] => One or more undefined variables: 'None' has no attribute 'public_dns_name'
