### ISSUE TITLE
Unable to use dict for defining scm dependency in meta/main.yml

### ISSUE THREAD

**Issue by johnrengelman** [ansible/ansible#11993]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
roles

##### ANSIBLE VERSION
```
1.9.2-1
```

##### SUMMARY
I want to define a role dependency in meta/main.yml that is a dependency to a role stored in GitHub and I want to provide `tags` for that dependency.
Normally, the dependency would be defined as such:

```

---
  dependencies:
    - git+git@github.com:MyOrg/ansible-foo,0.1.0,foo
```

The code that handles parsing this spec (https://github.com/ansible/ansible/blob/v1.9.2-1/lib/ansible/utils/__init__.py#L417) doesn't provide a means to specifying `tags` within this style.

The next attempt was to convert the above to a style similar to a `requirements.yml` file:

```

---
  dependencies:
    - src: git@github.com:MyOrg/ansible-foo
      scm: git
      version: 0.1.0
      name: foo
      tags:
        - bar
```

Running with this definition results in the following message:
`ERROR: expected a role name in dictionary: {'scm': 'git', 'src': 'git@github.com:MyOrg/ansible-foo.git', 'version': '0.1.0', 'name': 'foo', 'tags': ['bar']}`

This error comes from this line of code: https://github.com/ansible/ansible/blob/v1.9.2-1/lib/ansible/playbook/play.py#L218

However looking at the surrounding code: https://github.com/ansible/ansible/blob/v1.9.2-1/lib/ansible/playbook/play.py#L214-L221 it appears that if you define a dependency as a `dict` than you need to specify the `role` entry:

```

---
  dependencies:
    - role: foo
      src: git@github.com:MyOrg/ansible-foo
      scm: git
      version: 0.1.0
      name: foo
      tags:
        - bar
```

This results in Ansible trying to install `foo` from ansible-galaxy instead of from the scm.

So it appears there is no way to accomplish this construct other than unnecessarily decomposing the dependent role.
My suggestion would be that when defining a dependency using a `dict` that it should not error if either `role` or `name` are specified. (`role` should be priority and if not defined, use `name`).

This is occurring using `1.9.2-1`
