### ISSUE TITLE
msg: [Errno 2] No such file or directory bundle command

### ISSUE THREAD

**Issue by derrickmar** [ansible/ansible#12007]
Hello Ansible community,

I'm new to ansible and can't seem to understand the intuition behind this problem:
This playbook

```
    - name: bundle install
      command: "bundle install"
      args:
        chdir: "~/ai_grading_production/"
```

 throws this error `msg: [Errno 2] No such file or directory`. I'm sure it's not an issue with  chdir: "~/ai_grading_production/" because it exists and other commands like pwd work.

However when I specify the full path 
`command: "/home/ubuntu/.rvm/gems/ruby-2.2.2/wrappers/bundle install"`
It works fine.

When I use the shell command it seems to not find bundle at all. `stderr: /bin/sh: 1: bundle: not found`

Do you know why this is so and if there is a fix to not having to specify the whole path? Thank you!
