### ISSUE TITLE
uri: ansible incorrectly reports all SSLHandshakeError as certificate errors

### ISSUE THREAD

**Issue by shaleh** [ansible/ansible#12013]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
uri module

##### ANSIBLE VERSION
1.9.2

##### SUMMARY
Simple test case:

```
   - name: Some uri op
     uri:
         url: https://some_server:8000/the/rest/here
         method: PUT
         body: some_body
```

As you can see the author specified 8000 for the port but their site is setup for 8443 for SSL. Instead of a helpful error ansible returns 'Unable to validate server's certificate against available CA certs.' which leads to much tail chasing. The real error is:

```
    SSLHandshakeError(SSLError(1, '_ssl.c:510: error:140770FC:SSLroutines:SSL23_GET_SERVER_HELLO:unknown protocol'),)
```

Which if allowed to propagate would have made it much more clear that a fundamental error was made.
