### ISSUE TITLE
[RFC][Template] Be able to inject user values to template

### ISSUE THREAD

**Issue by lyrixx** [ansible/ansible#12029]
Hello.

I come from chef community, and I miss a behaviour in ansible:

I have theses vars:

```
sl_php_fpm_users:
    - site1
    - site2
sl_php_fpm_colors: [blue, green]
```

And I have this task:

```

- name: configure fpm
  template:
    dest: /etc/php5/fpm/php-fpm-{{ item[0] }}-{{ item[1] }}.conf
    src: fpm/php-fpm.conf.j2
  with_nested:
    - sl_php_fpm_users
    - sl_php_fpm_colors
```

And finally my template:

```
[global]
pid = /var/run/php5-fpm-{{ user }}-{{ color }}.pid
error_log = /var/log/php5/php-fpm-{{ user }}-{{ color }}.log
include = /etc/php5/fpm/pool.d/{{ user }}-{{ color }}.conf
log_level = notice
```

If you use this code, it will fail, because `user` and `color` variable are not defined at the template layer.

I would like to be able to do:

```
- name: configure fpm
  template:
    dest: /etc/php5/fpm/php-fpm-{{ item[0] }}-{{ item[1] }}.conf
    src: fpm/php-fpm.conf.j2
    vars: 
       user: {{ item[0] }}
       color: {{ item[1] }}
  with_nested:
    - sl_php_fpm_users
    - sl_php_fpm_colors
```

Why does I want to do that ? Because writing `{{ item[0] }}` in my template make it very hard to maintain and to review.

Reference: https://docs.chef.io/resource_template.html => search `A Hash of variables that are passed into a Ruby template file.`

**Comment by bcoca** [comment]
you need to un indent it a bit, as vars is a task directive and not specific to the template module.

```
- name: configure fpm
  template:
    dest: /etc/php5/fpm/php-fpm-{{ item[0] }}-{{ item[1] }}.conf
    src: fpm/php-fpm.conf.j2
  vars: 
       user: "{{ item[0] }}"
       color: "{{ item[1] }}"
  with_nested:
    - sl_php_fpm_users
    - sl_php_fpm_colors
```

**Comment by lyrixx** [comment]
Ah thanks. I did not know we can do that. I did not find the documentation though.

**Comment by lyrixx** [comment]
Hi.

I tried your solution, but it does not work.

My task:

```
---
- name: set-up nginx color conf
  template:
    src: color.conf.j2
    dest: "/etc/nginx/sites-enabled/{{ item[0] }}-{{ item[1] }}.conf"
  vars:
      user: "{{ item[0] }}"
      color: "{{ item[1] }}"
  with_nested:
    - sl_php_fpm_users
    - sl_php_fpm_colors
```

Command run:

```

AnsibleError('vars is not a legal parameter in an Ansible task or handler',)
ERROR: vars is not a legal parameter in an Ansible task or handler

```
