### ISSUE TITLE
Cant find vars from host_vars/*.me file

### ISSUE THREAD

**Issue by ph0en** [ansible/ansible#12033]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
1.9.2
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
Fedora 22 python 2.7.8

##### SUMMARY
Cant find vars from host_vars/*.me file

##### STEPS TO REPRODUCE
1. Create ansible-playbook role. My examle:
```
- name: Create DB
  mysql_db: name="{{ item.db_name }}" encoding=utf8
  with_items:
  - "{{ mysql_databases }}"
    when: mysql_databases is defined
- name: Create DB users
  mysql_user: name="{{ item.user }}" priv="{{ item.db_name }}".*:ALL password="{{ item.pass }}" host="{{ item.host }}"
  with_items:
  - "{{ mysql_databases }}"
    when: mysql_databases is defined
- Create inventory file or add to the default inventory file record
  mysql.any-site.me
- Create file mysql.any-site.me in your host_vars folder. My example:
  mysql_databases:
  - db_name: some_site_kz
    user: some_site_kz
    pass: "{{ lookup('password', '/home/user/ansible/work/credentials/' + ansible_nodename + '/' + 'mysql/' + 'some_site_kz length=15 chars=ascii_letters,digits' ) }}"
    host: '%'
```
##### EXPECTED RESULTS
 playbook from my example must create a mysql DB

##### ACTUAL RESULTS
 ansible can't see vars from vars file. But when I change host in inventory file from mysql.some-site.me to mysql.some-site.kz and have to change vars file name to mysql.some-site.kz everything works like expected.
Something (ansible or python) ignore .me (readme) files
