### ISSUE TITLE
Jinja filters fail after using set_fact variable definition

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#12040]
Bug Report
##### Ansible Version:

Latest dev branch for 2.0
##### Ansible Configuration:

jinja2_extensions = jinja2.ext.do
##### Environment:

OS X Yosemite
##### Summary:

If you register a variable then use set_fact to define it to another variable, the jinja filters fail on it with the following error:

```
Failed to template {% if testnew|failed %} True {% else %} False {% endif %}: |failed expects a dictionary
```
##### Steps To Reproduce:

```
- hosts: localhost
  tasks:
    - name: set variable
      command: echo /etc/hosts
      register: test

    - set_fact: testnew="{{ test }}"

    - name: hello world
      command: echo "hello world"
      when: testnew|changed
```
##### Expected Results:

Should be able to use jinja filters as before
##### Actual Results:

Error with expected dictionary line. This changed recently, probably in the last couple of weeks.
