### ISSUE TITLE
Copy action plugin strips leading character on recursive copy

### ISSUE THREAD

**Issue by mliszcz** [ansible/ansible#12055]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 2.0.0 (devel 47d9e7ca93) last updated 2015/08/23 10:26:42 (GMT +200)`
##### Ansible Configuration:

`/etc/ansible/ansible.cfg` - clean version from Github, `ansible.cfg` in current directory:

```
[defaults]
action_plugins = ./plugins:/usr/share/ansible_plugins
```
##### Environment:

Ubuntu 14.04, Fedora 22
##### Summary:

Copy action plugin strips leading character when recursive copy is performed. This is caused by the change introduced in 3a4dd523 (#11470).
##### Steps To Reproduce:

I have a role named `bash`. In `roles/bash/files` there is a `home` directory, which contents should be copied to `~` on localhost.

```
(michal3@michal-pc) {master} ~/Documents/dotfiles $ tree -a roles/bash/
roles/bash/
├── files
│   └── home
│       ├── .bashrc
│       └── some_other_file
└── tasks
    └── main.yml
```

```
(michal3@michal-pc) {master} ~/Documents/dotfiles $ cat roles/bash/tasks/main.yml 

---
## Configure bash.
#

- name: copy bash dotfiles
  copy:
    src: home/
    dest: '{{"~" | expanduser}}'
    force: yes
```
##### Expected Results:

```
(michal3@michal-pc) {master} ~/Documents/dotfiles $ ll ~
(...)
-rw-rw-r--   1 michal3 michal3    563 sie 23 10:27 .bashrc
-rw-rw-r--   1 michal3 michal3      0 sie 23 11:37 some_other_file
(...)
```
##### Actual Results:

```
(michal3@michal-pc) {master} ~/Documents/dotfiles $ ll ~
(...)
-rw-rw-r--   1 michal3 michal3    563 sie 23 10:27 bashrc
-rw-rw-r--   1 michal3 michal3      0 sie 23 11:37 ome_other_file
(...)
```

[`source_files`](https://github.com/ansible/ansible/blob/3a4dd523d3649facc6d88d94cb67f5531a51af2a/lib/ansible/plugins/action/copy.py#L87) looks like:

```
"source_files": [
  ["/home/michal3/Documents/dotfiles/roles/bash/files/home/.bashrc", "bashrc"],
  ["/home/michal3/Documents/dotfiles/roles/bash/files/home/some_other_file", "ome_other_file"]
]
```
