### ISSUE TITLE
Local action attempts to establish remote connection

### ISSUE THREAD

**Issue by cchurch** [ansible/ansible#12053]
Running against devel @ 47d9e7ca93808383568c3019ac32de7e7ba05ac5

Given an inventory that specifies `ansible_connection` for a host:

```
example ansible_connection=ssh
```

Running a playbook that executes a local action on behalf of a host attempts to establish an SSH connection to run the local task:

```
- hosts: all
  gather_facts: false
  tasks:
    - local_action: command echo "doing stuff needed to bring up host"
    - action: ping
```

It was broken by e7b2308b66c7930df87d77232d5e48769ab03f58 (as described in #12005) but doesn't appear to have been fixed by 635fa0757b06b560a7812053f8de298fc5fc2c4c.

**Comment by cchurch** [comment]
I would expect that local_action should use the local connection plugin and not try to establish any remote connection.  If the inventory does not explicitly define ansible_connection for a host, it works as expected.

This issue manifests itself slightly differently in #12056, where the use of the winrm connection for local_action changes the suffixes we search for modules, causing the local_action to be unable to find the file module.

**Comment by bcoca** [comment]
I tested on d59caf501c with a slightly modified play:

```
- hosts: testhost
  gather_facts: false
  tasks:
    - local_action: command hostname
    - action: ping
```

and hostname gets executed on the localhost, as expected

**Comment by jimi-c** [comment]
@cchurch can you retest to see if this is still an issue, per @bcoca's comment above?

**Comment by trondhindenes** [comment]
I'm seeing this issue on the latest build. Since I'm using winrm (and ansible isn't able to do localhost connections using winrm) this is now a major and blocking issue for anyone targeting windows nodes and using local actions.

**Comment by bcoca** [comment]
@trondhindenes can you show minimal example to reproduce, my test above still works fine.

**Comment by trondhindenes** [comment]
I started digging into this today and it turned out that switching from "delegate_to: 127.0.0.1" to "delegate_to: localhost" actually did the trick.

**Comment by jimi-c** [comment]
Ok, so this would seem to be the same issue as https://github.com/ansible/ansible/issues/12079?

**Comment by jhawkesworth** [comment]
Changing from local_action: to "delegate_to: localhost" also works around
the problem I described in #12056

**Comment by cchurch** [comment]
`delegate_to: localhost` works for me against 6154ed1dda, but `local_action` still tries to connect.

**Comment by cchurch** [comment]
:+1:

**Comment by Provscbunn** [comment]
delegate_to: localhost, delegate_to: 127.0.0.1, and local_action all produce the same results for me -- it tries to make a WinRM connection to the localhost

```
ansible 2.1.1.0
```

**Comment by hackermd** [comment]
Same for me with

```
ansible 2.1.2.0
```

Always tries to ssh connect despite `local_action`.

The only measure that prevents this behaviour is setting `connection: local` on the play.

**Comment by mazzystr** [comment]
I run ansible 2.2.1.0.  Ansible always attempts a remote execution

prerequisites.yaml:
```
- hosts: cluster_hosts
  gather_facts: yes
  become: yes
  user: ec2-user
  vars_files:
      - vars/main.yaml
  roles:
      - prerequisites
```
~/roles/prerequisites/tasks/main.yaml:
```
- name: Gather facts
  connection: local
  ec2_vol_facts:
    filters:
      "tag:Name": "rhm-ebs-i-abcd1234~data"
    region: "us-east-1"
```

I have tried `connection: local`, `delegate_to: localhost`, `delegate_to: 127.0.0.1` every time the play runs I get errors like this from all the instances
```
fatal: [rhm-oscp-abc-mbaas1-router1.example.com -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV4Handler'] Check your credentials"}
```
