### ISSUE TITLE
Typecast variables are not preserved

### ISSUE THREAD

**Issue by patrickheeney** [ansible/ansible#12071]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 1.9.2
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I have a role like below, that typecasts a variable to an int. However this appears to be converted back to a string by jinaja2. Ansible then throws this error `"msg: value of payment_term must be one of: 1,12,24, got: 1"` because it was not a valid int.

##### STEPS TO REPRODUCE
At the moment this is breaking the linode module or any module that relies on an int with choices.
```
- name: setup linode
  linode:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    #doesn't seem to work
    #payment_term: '{{ item.payment | int | default(1) }}'
    payment_term: '{{ item.payment | int }}'
    api_key: 'test'
  with_items: 
    - name: 'test'
      payment: 1
```
In the linode example, it seems to be caused by https://github.com/ansible/ansible-modules-core/blob/devel/cloud/linode/linode.py#L452 expecting one of the int choices, but jinaja is giving it a string. 
This may or may not be related to https://github.com/ansible/ansible/issues/5463

##### EXPECTED RESULTS
Linode should not error.

##### ACTUAL RESULTS
Errors.
