### ISSUE TITLE
Variable gets overwritten by another role in v2

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12081]
I have a playbook that includes two roles:

``` yaml

---
- hosts: trusty
  roles:
    - { role: app, name: app-test }
    - { role: roundup, name: bugs }
```

My `roles/app/defaults/main.yml` has this:

``` yaml

---
home: "/apps/zopes/{{ name }}"
```

My `roles/roundup/defaults/main.yml` has this:

``` yaml

---
home: "/apps/roundup/{{ name }}"
```

My `roles/app/tasks/main.yml` tries to use the `home` var:

``` yaml

---
- name: user account
  user: name={{ name }} home={{ home }} shell=/bin/sh createhome=no
```

When I run this playbook with Ansible 1, I get a user `app-test` with home directory `/apps/zopes/app-test`.

When I run this playbook with Ansible 2, I get a user `app-test` with home directory `/apps/roundup/bugs`.

I thought Ansible 2 was supposed to be 100% backwards-compatible with playbooks tested with Ansible 1?
