### ISSUE TITLE
v2 doesn't find variables in playbook scope

### ISSUE THREAD

**Issue by jmeickle** [ansible/ansible#12084]
I have a very, very simple playbook located at `./cluster_client.yml`:

```
- hosts: cluster
  remote_user: "{{cluster_user}}"
  roles:
    - role: cluster_client
      tags: cluster_client
```

Running it with this command works in Ansible v1.9, but fails in Ansible v2  with 'ERROR! 'cluster_user' is undefined':

```
ansible-playbook -i environments/nrg_production/inventory cluster_client.yml --limit cluster05

brainstorm:neurotransmitter jmeickle$ ansible-playbook --version
ansible-playbook 2.0.0 (devel 16f3f8e244) last updated 2015/08/24 14:30:36 (GMT -400)
```

(The inventory file is located at `./environments/prod_cluster/inventory`, and there's a `./environments/prod_cluster/group_vars/cluster/cluster_client.yml` file that contains `"cluster_user: admin"`.)

Importantly, variables defined in that file work everywhere else; if I hardcode remote_user to "admin" in the playbook, the initial error is bypassed, and `"cluster_user"` (as well as other vars defined in the same YAML file) work as expected in the `cluster_client` role.

**Comment by jpetrelliswork** [comment]
Even if you define a variable in the playbook it does not work at the playbook level.

```
- hosts: host1
  vars:
    version: "dev"
  tasks:
    - debug: var=version
```

Yields:

```
TASK [debug var=version] *******************************************************
ok: [linuxlab28] => {
    "changed": false, 
    "version": "dev"
}
```

However,

```
- hosts: host1
  vars:
    role_name: "dev"
  roles:
    - role: "content/{{ role_name }}"
```

Yields:

```
ERROR! 'version' is undefined
```
