### ISSUE TITLE
copy does not allow writing to /etc

### ISSUE THREAD

**Issue by kvarga** [ansible/ansible#12115]
I need to update /etc/pacman.conf on a remote server and using the following

``` YAML
- name: push updated pacman conf
  sudo: yes
  sudo_user: infosys
  copy: src=ec2-pacman.conf dest=/etc/pacman.conf mode=0644
```

However, when I run, I get the following error:

``` Shell
TASK: [arch | push updated pacman conf] *************************************** 
failed: [xxx.xxx.xxx.xxx] => {"checksum": "dc2d438019399e728f6af694f22d8dcc2bd08fb0", "failed": true}
msg: Destination /etc not writable
```

However, if I run the following commands from my machine it works:

``` Shell
$ scp roles/arch/files/ec2-pacman.conf infosys@xxx.xxx.xxx.xxx:/tmp/pacman.conf
$ ssh infosys@xxx.xxx.xxx.xxx sudo cp /tmp/pacman.conf /etc/pacman.conf                                                                                              
```

Any thoughts? I'd hate to have to use _command:_ instead of _copy:_
