### ISSUE TITLE
Role dependency task include file respects vars/main.yml vars differently

### ISSUE THREAD

**Issue by ferrants** [ansible/ansible#12128]
Seen with Ansible 1.9.2
This is a very specific case. When a role has a dependency on another role and the dependent role conditionally on a variable set in `vars/main.yml` includes a task file in its `tasks/main.yml`, it does not respect the overwritten variable set in upper role's `vars/meta.yml`.

Here is an example:
test.yml:

```

---
- name: test
  hosts: localhost
  roles:
    - role: test_role
      first_role_var: set in main playbook
      first_role_include: false
```

roles/test_role/tasks/main.yml

```

---
- debug: msg="{{ first_role_var }}"

- include: included.yml
  when: first_role_include
```

roles/test_role/tasks/included.yml

```

---
- debug: msg="first role included file"
```

roles/test_role/vars/main.yml

```

---
first_role_var: 'set in vars'
first_role_include: true
```

roles/test_role/meta/main.yml

```

---
dependencies:
  - role: test_role2
    second_role_var: "set in first role meta"
    second_role_include: false
```

roles/test_role2/vars/main.yml

```

---
second_role_var: 'set in vars'
second_role_include: true
```

roles/test_role2/tasks/main.yml

```

---
- debug: msg="{{ second_role_var }}"

- include: included.yml
  when: second_role_include
```

roles/test_role2/tasks/included.yml

```

---
- debug: msg="second role included file"
```

Output:

```
$ ansible-playbook test.yml 

PLAY [test] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [test_role2 | debug msg="set in vars"] ********************************** 
ok: [localhost] => {
    "msg": "set in first role meta"
}

TASK: [test_role2 | debug msg="second role included file"] ******************** 
ok: [localhost] => {
    "msg": "second role included file"
}

TASK: [test_role | debug msg="set in main playbook"] ************************** 
ok: [localhost] => {
    "msg": "set in main playbook"
}

TASK: [test_role | debug msg="first role included file"] ********************** 
skipping: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```

The `included.yml` in `test_role2` should have never been included because when the outer role defined the dependency, `second_role_include: false`. The variable that was passed in was honored. Note that when the outer role was called in the `test.yml`, `first_role_include` was respected. If the `second_role_include` is defined in `roles/test_role2/defaults/main.yml`, it is respected.
