### ISSUE TITLE
Feature Idea: Extendable Variable Manager

### ISSUE THREAD

**Issue by kontrafiktion** [ansible/ansible#12156]
I would like to be able to extend/replace the Ansible (2.0) VariableManager, so that I would be able to define a custom hierarchy of groups:

group category "stage" contains groups: "dev", "test", "preprod" and "prod"
other groups: "web", "db"

whatever is defined as group vars for "web" or "db" should be overriden by anything in the group category "stage".

This could be mapped to a directory structure:

```
web/
   ...
db/
   ...
dev/
   ...
  db/
      ...
  web/
     .../
test/
...
```

This hierarchy could be defined as:

```
group_categories: 
   - stage: ["dev", "test", "preprod", "prod"]
   - other_groups: ["web", "db"]
hierarchy:
  - {stage}
  - {stage}/{other_groups}
  - {other_groups}
```
