### ISSUE TITLE
include with_items passed last list items multiple times

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#12155]
Given:

```

---
srvio_interfaces:
  - eth0
  - eth1
  - eth2
```

``` yaml
- name: Configure SR-VIO network interfaces
  include: srvio.yml interface={{ item }}
  with_items: srvio_interfaces
  when: srvio_interfaces is defined
  tags: srvio
```

srvio.yml gets called three times but interface is always eth2. Expectation is that each of eth0, eth1, eth2 get passed in order.
