### ISSUE TITLE
/bin/bash: sudo: command not found

### ISSUE THREAD

**Issue by igormukhingmailcom** [ansible/ansible#12196]
Hi.

Have a strange error.
Playbook works fine on vagrant, but when I try to use it on real server - have a strange error.
I'm totally stuck. Google say nothing about this. Can anyone help me?
Target system - Debian 8.1, local - MacOS X, Ansible 1.9.2
Command I run: `sudo ansible-playbook playbook.yml -i inventory -vvvv`
Thanks.

```
<IP> ESTABLISH CONNECTION FOR USER: root
<IP> REMOTE_MODULE setup
<IP> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/igor/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 IP /bin/bash -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1441171863.06-43867030112365 && echo $HOME/.ansible/tmp/ansible-tmp-1441171863.06-43867030112365'
<128.199.224.76> PUT /tmp/tmpjUzMY3 TO /root/.ansible/tmp/ansible-tmp-1441171863.06-43867030112365/setup
<IP> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/igor/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 IP /bin/bash -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=zawfridfqjsdutoonwjbwgzywxsggz] password: " -u root /bin/bash -c '"'"'echo BECOME-SUCCESS-zafrbidfqjsdutoonwjbwgzyxdsggz; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1441171863.06-43867030112365/setup; rm -rf /root/.ansible/tmp/ansible-tmp-1441171863.06-43867030112365/ >/dev/null 2>&1'"'"''
failed: [IP] => {"failed": true, "parsed": false}
/bin/bash: sudo: command not found
```

**Comment by igormukhingmailcom** [comment]
Ah, sorry...
I just have a fresh look and realize that `sudo` not installed by default on Debian, so I run `aptitude install sudo` on target machine before start my playbook.

**Comment by ksylvan** [comment]
I know this issue is closed, but it helped me, so I'm going to leave a snippet of my Debian server playbook here. Added this to the top of my playbook and got around the problem:

``` 
  # bootstrap python onto server
  #
  pre_tasks:
  - name: Install python 2 if not there
    raw: |
      test -e /usr/bin/python || \
      (apt -y update && apt install -y python-simplejson)
    register: output
    changed_when: output.stdout|trim() != ""
  - name: Install sudo if not there
    raw: |
      test -e /usr/bin/sudo || apt install -y sudo
    register: output
    changed_when: output.stdout|trim() != ""
```
