### ISSUE TITLE
boolean interpreted as dict, 2.0

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#12206]
I have a dict:

``` yaml
users:
  - name: matt
    comment: 'Matt Willsher'
    is_admin: True
    ssh_keys:
      - ecdsa-sha2-nistp256 AAAAE2
```

1.9.2 debug:

```
ok: [sam.wilsys.net] => {
    "var": {
        "users": [
            {
                "comment": "Matt Willsher",
                "is_admin": true,
                "name": "matt",
                "ssh_keys": [
                    "ecdsa-sha2-nistp256 AAAAE2"
                ]
            }
        ]
    }
}
```

2.0 output:

```
ok: [sam.wilsys.net] => {
    "changed": false,
    "users": [
        {
            "comment": "Matt Willsher",
            "is_admin": {},
            "name": "matt",
            "ssh_keys": [
                "ecdsa-sha2-nistp256 AAAAE2"
            ]
        }
    ]
}
```

Then:

```
failed: [sam.wilsys.net] => (item={u'comment': u'Matt Willsher', u'is_admin': {}, u'name': u'matt', u'ssh_keys': [u'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOgLXY1vHW5weJpl5XUm7yZ261OJrv3Pq1R743zS2Ssw', u'ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGFdUSXkWRPKbHZtPMexORfQxuav9zVpHwFmifY92sTIE3uy5CbmvaAch3+sf/Qg3oBUCR2mhp729uEyGuaZAZc=']}) => {"failed": true, "item": {"comment": "Matt Willsher", "is_admin": {}, "name": "matt", "ssh_keys": ["ecdsa-sha2-nistp256 AAAAE2"]}, "msg": "argument createhome is of type <type 'dict'> and we were unable to convert to bool"}
```

The  code

``` yaml
- name: Create users
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    uid: '{{ item.uid | default(omit) }}'
    group: '{{ item.group | default(item.name) }}'
    groups: '{{ item.groups | default("") | join(",") }}'
    shell: '{{ item.shell | default(users_default_shell) }}'
    comment: '{{ item.comment | default("Unknown User") }}'
    password: '{{ item.password | default(users_default_password) }}'
    home: '{{ item.home | default("/home/"+item.name) }}'
    createhome: '{{ item.createhome | default(users_create_homedirs) }}'
    system: '{{ item.system | default(omit) }}'
    append: yes
  with_items: users
  when: >
    not ( item.name == ansible_ssh_user and
    item.state|default('present') == 'absent' )
```

users_create_homedirs is set as yes is the defaults/main.yml

The code works as expected in 1.9

```
$ ansible-playbook --version
ansible-playbook 2.0.0 (devel e8d7fafc52) last updated 2015/09/02 09:05:09 (GMT +100)
  lib/ansible/modules/core: (detached HEAD ef1f31c652) last updated 2015/08/31 21:19:36 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 5b39e19387) last updated 2015/08/31 21:19:36 (GMT +100)
  config file = /Users/matt/Development/ansible/ansible.cfg
  configured module search path = None
```
