### ISSUE TITLE
Skipped task changes value of previously registered result - strange behaviour

### ISSUE THREAD

**Issue by morokin** [ansible/ansible#12218]
ansible 1.9.2

Hello, I am stuck with the following strange behavior:

If stages 2 - 3 (inclusive) are skipped (because of some condition), ansible_provisioned changes its value from value on stage 1), to new:

   "var": {
        "ansible_provisioned": {
            "changed": false,
            "skipped": true
        }

Is it supposed to work this way? I expected ansible_provisioned to be unmodified if every task that is able to modify its value is skipped.

Example:

``` yaml
#- include: getmark.yml

#1)
- name: check if already provisioned
  shell: mysql -N -s -r -S {{ sock.stdout }} -e "select state from ansible.facts where fact='provisioned'"
  register: ansible_provisioned
  changed_when: false
  failed_when: false

# first entry
- debug: var=ansible_provisioned.stdout

#2)
- name: create ansible custom facts db
  mysql_db: name=ansible state=present login_unix_socket={{ sock.stdout }}
  register: ansibledb
  when: "'ERROR 1146 (42S02)' in ansible_provisioned.stderr"

#3)
#- include: getmark.yml
- name: check if already provisioned
  shell: mysql -N -s -r -S {{ sock.stdout }} -e "select state from ansible.facts where fact='provisioned'"
  register: ansible_provisioned
  changed_when: false
  failed_when: false
  when: ansibledb.changed

# second entry 
- debug: var=ansible_provisioned.stdout
```
