### ISSUE TITLE
systemd check is slow in 2.0

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#12215]
ansible 2.0.0 (devel 843138e7d9) last updated 2015/09/02 18:58:01 (GMT +100)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/02 19:18:09 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/02 19:18:09 (GMT +100)
  config file = /Users/matt/Development/ansible/ansible.cfg
  configured module search path = None

The following code in 2.0.0 pauses for several seconds whether the service has changed or not. Target OS is CentOS 7.1 (systemd), localhost is Mac OS X.

Under 1.9.2 there is no pause.

``` yaml
- name: Service enabled and running
  service:
    name: "{{ sshd_service }}"
    enabled: true
    state: running
  when: sshd_manage_service
  register: sshd_service_running
  tags:
    - sshd
```
