### ISSUE TITLE
limit callout to roles with tags

### ISSUE THREAD

**Issue by ciphernaut** [ansible/ansible#12224]
Issue Type:

```
Feature Idea
```

Ansible Version:

   Any

Ansible Configuration:

   N/A

Environment:

   ALL

Summary:

Allow calling of other plays and roles limiting play to only those with specified tag.

This would be the inverse of

```
  roles:
    - { role: foo, tags: ["bar", "baz"] }
```

where the the entire role is tagged with some tag as opposed to only running some of the tasks within that role tagged with matching item.

Steps To Reproduce:

The work around is to call the role via a second playbook indirectly:
a.yml

```
- hosts: db
  tasks:
    - name: run the postgres role in a very hack way
      command: "ansible-playbook -vvCD {{ playbook_dir }}/b.yml --tags='core_config_updates'"
      args:
        chdir: "{{ inventory_dir }}/../"
      delegate_to: localhost
```

b.yml

```
- hosts: db
  pre_tasks:
  - include_vars: "{{secret_repo}}/defaults/postgres.yml"
    no_log: True
    tags:
    - always
  roles:
    - postgresql
```

However this is rather messy and all the results from b.yml are merged into a single output into the output from the task in a.yml making error handling very difficult.

Expected Results:

Role 'apache' has tags 'config' and 'upgrade'
Role 'postgres' has tags 'core_config_updates' and 'update_packages'

update_configs.yml:

```
- hosts: db
  roles:
  - { role: postgresql, tags: ["core_config_updates"] }
- hosts: web
  roles:
  - { role: apache, tags: ["config"] }
```

Actual Results:

```
  roles:
    - { role: foo, tags: ["bar", "baz"] }
```

will always run role 'foo' except when the main play is invoked with tags not including bar or baz.  I have not found a use case yet for the current behaviour.
