### ISSUE TITLE
v2: extra new line after a templated var defined in yaml as var: >

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#12237]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 7ece767767) last updated 2015/09/03 19:40:16 (GMT +200)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/03 19:40:19 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/03 19:40:19 (GMT +200)
  config file = /home/serge/src/ginsys/ansible-data/ansible.cfg
  configured module search path = None

git bisect leads to following commit as the culprit:

```
1998eddf8d5213e476973a39a0ee57db020941ec is the first bad commit
commit 1998eddf8d5213e476973a39a0ee57db020941ec
Author: Toshio Kuratomi <toshio@fedoraproject.org>
Date:   Wed Sep 2 11:52:37 2015 -0700

    Keep newlines by default now.

    In v1, a trailing newline was kept if the parameter was passed as key=value.  If
    the parameter was passed as yaml dict the trailing newline was
    discarded.  Since key-value and yaml dict were unified in v2 we have to
    make a choice as to which behaviour we want.  Decided that keeping trailing
    newlines by default made the most sense.

    Fixes #12200
    Fixes #12199

:040000 040000 f889c5eabd880f0252347de9744e670b920a7865 c1375dffa661a545451dfded88e4871f32edfa07 M  lib
```
##### Ansible Configuration:

N/A
##### Environment:

Ubuntu
##### Summary:

When defining a variable with the yaml construct 

```
variable: >
   blah
```

An extra newline is introduced when that variable gets templated.
##### Steps To Reproduce:

Using following parts of a role, original files at https://github.com/ginsys/ansible-role-seafile/tree/4.3

Relevant variables:

``` yaml
SEAFILE_ENVIRONMENT:                                                            
  LD_LIBRARY_PATH: >                                                            
    {{ seafile_latest_dir }}/seafile/lib/:{{ seafile_latest_dir }}/seafile/lib64:${LD_LIBRARY_PATH}
  PYTHONPATH: >                                                                 
    {{ seafile_latest_dir }}/seafile/lib/python2.6/site-packages:{{ seafile_latest_dir }}/seafile/lib64/python2.6/site-packages:{{ seafile_latest_dir }}/seahub/thirdpart:{{ seafile_latest_dir }}/seafile/lib/python2.7/site-packages:{{ seafile_latest_dir }}/seafile/lib64/python2.7/site-packages:{{ ansible_env.PYTHONPATH | default('') }}
  CCNET_CONF_DIR:       '{{ seafile_ccnet_dir }}'                               
  SEAFILE_CONF_DIR:     '{{ seafile_data_dir }}'     
```

Task:

``` yaml
- name:                 provision environment source file                       
  sudo:                 yes                                                     
  sudo_user:            '{{ seafile_user }}'                                    
  template:                                                                     
    src:                    bin/environment                                     
    dest:                   '{{ seafile_latest_dir }}/environment'              
   mode:                   0664    
```

Template file:

```
## {{ansible_managed}}                                                          

{% for var in SEAFILE_ENVIRONMENT|dictsort %}                                   
export {{ var[0] }}="{{ var[1] }}"                                              
{% endfor %}                                                                    

## {{ansible_managed}}    
```
##### Expected Results:

No changes in the templating when the role ran initially fine and made the template in v1.9.x
##### Actual Results:

In said version of v2/devel, a new line is introduced for what seems variables defined with the yaml `var; >` construct:

```
TASK [Ginsys.seafile : provision environment source file] **********************
changed: [hydargos]
--- before: /home/seafile/ginsys/seafile-server-latest/environment
+++ after: dynamically generated
@@ -1,8 +1,10 @@
 ## Ansible managed, do not change manually.

 export CCNET_CONF_DIR="/home/seafile/ginsys/ccnet"
-export LD_LIBRARY_PATH="/home/seafile/ginsys/seafile-server-latest/seafile/lib/:/home/seafile/ginsys/seafile-server-latest/seafile/lib64:${LD_LIBRARY_PATH}"
-export PYTHONPATH="/home/seafile/ginsys/seafile-server-latest/seafile/lib/python2.6/site-packages:/home/seafile/ginsys/seafile-server-latest/seafile/lib64/python2.6/site-packages:/home/seafile/ginsys/seafile-server-latest/seahub/thirdpart:/home/seafile/ginsys/seafile-server-latest/seafile/lib/python2.7/site-packages:/home/seafile/ginsys/seafile-server-latest/seafile/lib64/python2.7/site-packages:"
+export LD_LIBRARY_PATH="/home/seafile/ginsys/seafile-server-latest/seafile/lib/:/home/seafile/ginsys/seafile-server-latest/seafile/lib64:${LD_LIBRARY_PATH}
+"
+export PYTHONPATH="/home/seafile/ginsys/seafile-server-latest/seafile/lib/python2.6/site-packages:/home/seafile/ginsys/seafile-server-latest/seafile/lib64/python2.6/site-packages:/home/seafile/ginsys/seafile-server-latest/seahub/thirdpart:/home/seafile/ginsys/seafile-server-latest/seafile/lib/python2.7/site-packages:/home/seafile/ginsys/seafile-server-latest/seafile/lib64/python2.7/site-packages:
+"
 export SEAFILE_CONF_DIR="/home/seafile/ginsys/seafile-data"

 ## Ansible managed, do not change manually.


```
