### ISSUE TITLE
Play failure blocks subsequent plays (1.9.2 & 2.0)

### ISSUE THREAD

**Issue by mattwillsher** [ansible/ansible#12231]
```
ansible 2.0.0 (devel 9e023fedf2) last updated 2015/09/03 07:57:17 (GMT +100)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/02 19:18:09 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/02 19:18:09 (GMT +100)
  config file = /Users/matt/Development/ansible/ansible.cfg
  configured module search path = None
```

given the following playbook:

``` yaml

---
  - hosts: ceph
    tasks:
      - name: Allow Ceph via public interface
        firewalld:
          port: 6789/tcp
          permanent: True
          immediate: True
          state: enabled
      - name: Set SELinux permissive
        selinux:
          state: permissive
          policy: targetted
      - name: Install yum-plugin-priorities
        yum:
          name: yum-plugin-priorities

  - hosts: ceph_admin
    roles:
      - role: mattwillsher.repositories
        name: ceph
```

and the following inventory:

``` yaml
[ceph]
air.wilsys.net

[ceph_admin]
set.heron.wilsys.net
```

```
ansible-playbook ceph.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [air.wilsys.net]: FAILED! => {"failed": true, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
air.wilsys.net             : ok=0    changed=0    unreachable=0    failed=1
```

Changing the playbook around so that ceph_admin is at the top works as expected:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [set.heron.wilsys.net]

TASK [mattwillsher.repositories : fail msg=Role for yum package management only] ***
skipping: [set.heron.wilsys.net]

TASK [mattwillsher.repositories : Copy ceph repository file into place] ********
ok: [set.heron.wilsys.net] => (item=ceph)

TASK [mattwillsher.repositories : Copy ceph RPM GPG signing key into place] ****
skipping: [set.heron.wilsys.net]

TASK [mattwillsher.repositories : Install ceph RPM GPG signing key into database] ***
skipping: [set.heron.wilsys.net]

TASK [mattwillsher.repositories : Install ceph repository package] *************
skipping: [set.heron.wilsys.net]

PLAY ***************************************************************************

TASK [setup] *******************************************************************
fatal: [air.wilsys.net]: FAILED! => {"failed": true, "msg": "ERROR! SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
air.wilsys.net             : ok=0    changed=0    unreachable=0    failed=1
set.heron.wilsys.net       : ok=2    changed=0    unreachable=0    failed=0
```

I was expecting that the ceph_admin play would proceed regardless of the outcome of the first ceph play. This happens in both 2.0 and 1.9.2.
