### ISSUE TITLE
Low performance

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#12239]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
devel
ansible 2.0.0 (detached HEAD b2cb3153f1) last updated 2015/09/03 230737 (GMT +200)
lib/ansible/modules/core (detached HEAD bbcfb1092a) last updated 2015/09/03 230739 (GMT +200)
lib/ansible/modules/extras (detached HEAD b8803306d1) last updated 2015/09/03 230739 (GMT +200)
config file =
configured module search path = /root/ansible/library
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
Debian 7

##### SUMMARY
Hi, unfortunately version 2.0 seems slow down.
With a real playbook: v2 run within 32 secs, v2, stable-1.9 19 secs.
Same conditions (target machine, control machine), no network congestions (local net), no network downloads.

##### STEPS TO REPRODUCE
time ansible-playbook -i hosts simplespeedtest.yml > /dev/null
```
---
# simplespeedtest.yml
- hosts: localhost
  tasks:
    - command: echo 1
    - command: echo 2
#  and so on
    - command: echo 30
```

##### EXPECTED RESULTS
ansible stable-1.9
ansible 1.9.3 (detached HEAD 066b7079ef) last updated 2015/09/03 23:19:28 (GMT +200)
  lib/ansible/modules/core: (detached HEAD dccef8f89a) last updated 2015/09/03 23:17:15 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 25595b4ecc) last updated 2015/09/03 23:17:15 (GMT +200)
  configured module search path = /root/ansible/library
real    0m2.608s
user    0m1.776s
sys 0m0.464s
real    0m2.476s
user    0m1.656s
sys 0m0.468s
real    0m2.497s
user    0m1.688s
sys 0m0.444s

##### ACTUAL RESULTS
real    0m3.848s
user    0m2.484s
sys 0m0.496s
real    0m3.524s
user    0m2.208s
sys 0m0.376s
real    0m3.926s
user    0m2.396s
sys 0m0.544s

**Comment by geerlingguy** [comment]
I'm seeing the same results, using the following playbook:

``` yaml
---
- hosts: localhost
  connection: local

  tasks:
    - command: echo 1
    - command: echo 2
    - command: echo 3
    - command: echo 4
    - command: echo 5
    - command: echo 6
    - command: echo 7
    - command: echo 8
    - command: echo 9
    - command: echo 10
```

| Ansible 1.9.3 | Ansible 2.0.0 devel | delta |
| --- | --- | --- |
| 1.640s | 2.187s | 29% slower |

With sudo, deltas are about the same for me.

Real-world playbook operating on a local VM with sudo (specifically, [this one](https://github.com/geerlingguy/ansible-for-devops/tree/master/drupal) - ran `vagrant up --no-provision`, then `time vagrant provision`):

| Run | Ansible 1.9.3 | Ansible 2.0.0 devel | delta |
| --- | --- | --- | --- |
| Initial provision | XYZs | XYZs | % slower |
| 2nd provision (no changes) | 11.997s | 884.760s | 195% slower |

All tests were averages of 3 runs.

I didn't complete the initial provision with Ansible 2.0.0 because it was excruciating, and I stopped waiting after about 15 minutes. I let the idempotent provision go after doing the initial provision with 1.9.3, and it was also excruciating. I did it three times, and each time it took more than 14 minutes. CPU was basically idle the entire time.
