### ISSUE TITLE
Unexpected syntax when using multi-line tasks and local_action; local_action should be a task parameter

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#12247]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
I am currently using version 1.9.2 but this is probably true since local_action and the syntax module options (as opposed to action module options as described [here](http//docs.ansible.com/ansible/playbooks_intro.htmltasks-list)) both exist.
```

##### CONFIGURATION
N/A apart from personal coding style of multilining every options.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using multi-line YAML for a module and its options, using `local_action` requires us to explictely type `module: action`.

##### STEPS TO REPRODUCE
For example, consider this non-local action to runs fine:
``` yaml
uri:
  HEADER_Content-Type: application/json
  url: https://api.example.com/
  method: POST
  body: "{}"
  status_code: 201 # Created
```
Considering the local version of:
``` yaml
uri: HEADER_Content-Type=application/json url=https://api.example.com/ method=POST body="{}" status_code=201 # Created
```
is:
``` yaml
local_action: uri HEADER_Content-Type=application/json url=https://api.example.com/ method=POST body="{}" status_code=201 # Created
```
One would expect this to work:
``` yaml
local_action: uri
  HEADER_Content-Type: application/json
  url: https://api.example.com/
  method: POST
  body: "{}"
  status_code: 201 # Created
```
But this results in:
```
ERROR: Syntax Error while loading YAML script, [...]/tasks/main.yml
Note: The error may actually appear before this position: line 5, column 24
  local_action: uri
    HEADER_Content-Type: application/json
                       ^
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
This, however, works:
``` yaml
local_action: uri
  HEADER_Content-Type=application/json
  url=https://api.example.com/
  method=POST
  body="{}"
  status_code=201 # Created
```
But using a single line or that last example is not suitable when all your playbooks are using this first syntax, for consistency across your playbooks.
Another solution that works is:
``` yaml
local_action:
  module: uri
  HEADER_Content-Type: application/json
  url: https://api.example.com/
  method: POST
  body: "{}"
  status_code: 201 # Created
```

##### EXPECTED RESULTS
I am not flagging this as a Bug Report, because it's not a bug, it's merely how YAML works in the first place, however:
- **Documentation Report:** it might be worth documenting the necessary `module: action` statement, in my opinion, maybe in the [YAML Gotchas](http://docs.ansible.com/ansible/YAMLSyntax.html#gotchas), as it's quite confusing when you stumble upon this.
- **Feature Idea:** What would be better though, for user experience but also consistency with pretty much all every module parameter in Ansible (`name`, `sudo`, `with_items`, `tags`, `notify`, ...) would be this:
  
  ``` yaml
  uri:
    HEADER_Content-Type: application/json
    url: https://api.example.com/
    method: POST
    body: "{}"
    status_code: 201 # Created
  local_action: yes
  ```
Very readable and no gotcha (from user perspective, maybe there are gotchas at implementation time...), no surprise when writing your playbooks.

##### ACTUAL RESULTS
N/A

**Comment by bcoca** [comment]
just use `connection: local` or `delegate_to: localhost` instead

**Comment by astorije** [comment]
So there are 3 ways to do run a task locally:
- Use `connection: local` as a param of a task ([doc](http://docs.ansible.com/ansible/playbooks_delegation.html#local-playbooks) but only for the playbooks)
- Use `delegate_to: localhost` as a param of a task ([doc](http://docs.ansible.com/ansible/playbooks_delegation.html#delegation))
- Prefix task with `local_action:` ([doc](http://docs.ansible.com/ansible/playbooks_delegation.html#delegation), lower in the page)

What I understand from the docs is that `local_action:` format is just a shorthand for `delegate_to: localhost`. I didn't find if the doc says that `connection: local` can be applied to a task, just an entire playbook.

What are the differences between those 3, apart from that?

I still believe we need a `local: yes` or `local_action: yes` to uniformize the third case with all other possibilities. And/or edit docs to clarify the confusion described above. Does that make sense?

**Comment by astorije** [comment]
Thanks for your input anyway, @bcoca, I'll use `connection: local` right now.

**Comment by rgm3** [comment]
This confused me today too.  The documentation needs an example of a "multi-line" local task, and perhaps to spell out the differences between these things.  If there are no differences, consider simplifying by removing extraneous things.

**Comment by bcoca** [comment]
So the task format is this:
```
action: module=modulename moduleparam1=value1 moduleparam2=value2
```
or 
```
action:
  module: modulename
  moduleparam1: value1
  ...
```
where action can be substituted for local_action. I'll just use k=v format for rest to keep it shorter.

at one point we added a shorthand:

```
action: modulename moduleparam1=value1 ...
```

but this was still 'too long for some people so we added the condensed method which is what most use today:

```
modulename: moduleparam=value1 ...
```

this is why local_action works as it does, its just putting it back to the 'old action:' way of writing the tasks.  Which was a shortcut to `delegate_to: localhost` which now seems as much work as the original. I doubt we'll add it as a task directive as we already have a way of doing it as such.

**Comment by rgm3** [comment]
Thanks for the historical insight, I can see why you did it this way.  I almost always use more yaml like so:

```
modulename:
  k1: v1
  k2:
    - v2
    - v3
```

I had no idea that task format supported (began with, even) the literal string "action:" with a module parameter.  Coming from this more structured yaml approach, my inclination was to try:

```
local_action:
  modulename:
    k1: v1
    ...
```

Crazy I know.  Using `delegate_to` is perfectly fine for me.  I'll open my heart more to the "k=v" way of doing things (especially when it fits on one line) and be generally less confused and somewhat more compact.  I had skipped right to the "local_action" section of the delegation documentation, but reading it from the beginning makes it more clear.  Sorry for waking up an old thread and thanks for the clarification. :blush:
