### ISSUE TITLE
synchronize with items doesn't work with dev 2.0

### ISSUE THREAD

**Issue by skynet** [ansible/ansible#12253]
Synchronize with_items doesn't work with branch devel 2.0, works with 1.9.3 (stable-1.9 d444ab507e)

```
- hosts: remoteA
  tasks:
  - name: Copy directories from remoteB to remoteA
    delegate_to: remoteB 
    synchronize:
      mode: push 
      delete: yes 
      archive: yes
      src: /var/www/{{item}}
      dest: /var/www/
    with_items:
      - dir1
      - dir2
      - dir3
```

**Comment by chrrrles** [comment]
@skynet - Can you tell the error (verbose preferred) you get with this playbook on v2?  

##### Issue Type:

Can you help us out in labelling this by telling us what kind of ticket this this?  You can say:
- Bug Report
- Feature Idea
- Feature Pull RequestSarah Connor
- New Module Pull Request
- Bugfix Pull Request
- Documentation Report
- Docs Pull Request

##### Ansible Version:

Let us know what version of Ansible you are using.  Please supply the verbatim output from running “ansible --version”.  If you're filing a ticket on a version of Ansible which is not the latest, we'd greatly appreciate it if you could retest on the latest version first.  We don't expect you to test against the development branch most of the time, but we may ask for that if you have cycles.  Thanks!

##### Ansible Configuration:

What have you changed about your Ansible installation?  What configuration settings have you changed/added/removed?  Compare your /etc/ansible/ansible.cfg against a clean version from Github and let us know what's different.

##### Environment:

What OS are you running Ansible from and what OS are you managing?  Examples include RHEL 5/6, Centos 5/6, Ubuntu 12.04/13.10, *BSD, Solaris.  If this is a generic feature request or it doesn’t apply, just say “N/A”.  Not all tickets may be about operating system related things and we understand that.

##### Summary:

Please summarize your request in this space.  You will earn bonus points for being succinct, but please add enough detail so we can understand the request.  Thanks!

##### Steps To Reproduce:

If this is a bug ticket, please enter the steps you use to reproduce the problem in the space below.  If this is a feature request, please enter the steps you would use to use the feature.  If an example playbook is useful, please include a short reproducer inline, indented by four spaces.  If a longer one is necessary, linking to one uploaded to gist.github.com would be great.  Much appreciated!

##### Expected Results:

Please enter your expected results in this space.  When running the steps supplied above in the previous section, what did you expect to happen?  If showing example output, please indent your output by four spaces so it will render correctly in GitHub's viewer thingy.

##### Actual Results:

Please enter your actual results in this space.  When running the steps supplied above, what actually happened?  If you are showing example output, please indent your output by four spaces so it will render correctly in GitHub.  Thanks again!

**Comment by skynet** [comment]
I'll try to but may not be able to get to this. I know for sure that it failed with 2.0. After this I reversed my setup to 1.9.3 and not planning to go back to v2 until I see a new feature that I really need. Thanks!

**Comment by chrrrles** [comment]
Was unable to reproduce this earlier, and tried again using this playbook:

```
- hosts: bar
  tasks:
    - name: ensure directories exist
      file: path=/tmp/{{ item }} state=directory
      with_items:
        - dir1
        - dir2
        - dir3

- hosts: foo
  tasks:
  - name: Copy directories from bar to foo
    delegate_to: bar
    synchronize:
      mode: push
      delete: yes
      archive: yes
      src: /tmp/{{item}}
      dest: /tmp/
    with_items:
      - dir1
      - dir2
      - dir3
```

Running this playbook results in the proper files being created on the "foo" machine:

```
drwxrwxr-x. 2 user user 40 Oct  2 13:05 /tmp/dir1
drwxrwxr-x. 2 user user 40 Oct  2 13:06 /tmp/dir2
drwxrwxr-x. 2 user user 40 Oct  2 13:06 /tmp/dir3
```

Please re-open if you can find more information to reproduce the bug.
