### ISSUE TITLE
Variables in inventory are not available in hostvars[]

### ISSUE THREAD

**Issue by jpmens** [ansible/ansible#1226]
```
ansible 0.8 (devel 761330b125) last updated 2012/10/04 09:19:51 (GMT +200)
```

host variables specified in inventory file aren't stored in _hostvars_:

```
$ cat hosts
[local]
127.0.0.1 person="John.Q" ansible_python_interpreter=/usr/bin/python xxxx="foo"
```

``` yaml

---
- hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - action: template src=templ.in dest=/tmp/t
```

```
$ cat templ.in
{{ hostvars | to_json }}
```

produces no mention of either _person_, _ansible_python_interpreter_ or _xxxx_.
