### ISSUE TITLE
module win_user

### ISSUE THREAD

**Issue by john-404** [ansible/ansible#12279]
Hi.
We have a vm ubuntu 14.04 LTS with ansible 1.9.3 and python 2.7.
I want to create users on a machine with windows.
Using module winrm on windows and win_user module for creating profile. (Testing in o.s.: windows 7, windows 8/8.1)

My playbook:

```

---
- name: Add a user
  hosts: all
  tasks:
   - name: Add user in system
        win_user:
        name: test
        password: "password"
        groups: ["users"]
        state: present
```

run playbook:

```
ansible-playbook -vvvv -i hosts playbooks/users.yml
```

result:

```
changed: [192.168.1.171] => {"account_disabled": false, "account_locked": false, "changed": true, "description": "", "fullname": "test", "groups": [{"name": "users", "path": "WinNT://WORKGROUP/mycomp/users"}], "name": "test", "password_expired": false, "password_never_expires": true, "path": "WinNT://WORKGROUP/mycomp/test", "sid": "S-1-5-21-2925825274-3949947971-3441621627-1016", "state": "present", "user_cannot_change_password": false}
```

In windows system user is created, and I see this in: managing computer >  users. But in logon window user does not appear.
Why ? Help me please
