### ISSUE TITLE
Misleading deprecation message

### ISSUE THREAD

**Issue by jmeickle** [ansible/ansible#12282]
On running a playbook with `ansible 2.0.0 (devel 2d251cba45) last updated 2015/09/04 15:50:24 (GMT -400)`, I got this error message:

```
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task
 is deprecated. Please see:
http://docs.ansible.com/ansible/playbooks_roles.html
#task-include-files-and-encouraging-reuse

for currently supported syntax 
regarding included files and variables. This feature will be removed in a future
 release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```

This was very hard to track down, and should have a line number or task name or something. After a while I was able to pin it down to this section of a role, where I was running several files in an include as root:

```
- include: setup-RedHat.yml
  # become: yes
  sudo: yes
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  # become: yes
  sudo: yes
  when: ansible_os_family == 'Debian'
```

Switching from 'sudo' to 'become' fixes this problem. So I think what's happening here is that because sudo is deprecated, it's not on the acceptable attribute list; that leads to sudo being seen as a variable being passed to the task in a deprecated way, rather than as an attribute of the task.

I'd recommend both improving the error message, and including deprecated attributes in a second check performed before the variable-passing deprecation check.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by arpit-goel** [comment]
Hi @jimi-c ,
The bug doesn't seem to be completely resolved. I'm running `ansible-playbook 2.1.0.0`.
I receive the same error message one Eronarn received. However, he was able to resolve the issue changing **sudo** to **become** but I wasn't as I had already done that change before receiving this error. As far as I understand from the message, there shouldn't be variables defined with the include statement. Going to the link doesn't prove to be much help as the message in the error and content on page doesn't match.
Here are my task file:

```
- include: env.yml
  tag: provision,env
```

And here's my env.yml:

```
- name: Configure environment variables
  template: src=env/.{{ env_name }}.j2 dest="{{ deploy_directory }}/.env" force=yes
  register: environment_vars_check

- name: restart supervisor
  become: yes
  become_user: root
  become_method: sudo
  command: restart supervisor
  when: environment_vars_check.changed

- name: Add env to deployer user bashrc
  blockinfile:
    dest: "/home/{{ deploy_user }}/.bashrc"
    backup: "yes"
    state: "present"
    insertafter: "EOF"
    marker: "# {{ version }} {mark}"
    content: |
        while read line
        do
                export $line
        done < {{ deploy_directory }}/.env
  when: inventory_hostname in groups.appservers
```

Please look into the issue.
