### ISSUE TITLE
Handler not executed when using API

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#12316]
**Issue Type:**

Bug Report?

**Ansible Version:**

```
ansible 1.9.3 (detached HEAD d444ab507e) last updated 2015/09/04 10:41:26 (GMT -700)
  lib/ansible/modules/core: (detached HEAD cf88f27868) last updated 2015/09/04 10:41:35 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 29ef00f897) last updated 2015/09/04 10:41:42 (GMT -700)
  configured module search path = None
```

**Summary:**

Handlers are run with `ansible-playbook` but not with python

**Steps To Reproduce:**

**playbook.yml:**

```
- name: Configure instance(s)
  hosts: ec2
  sudo: True
  gather_facts: True
  roles:
    - test-role
```

**tasks/test.yml:**

```
- name: pull repos
  git:
    ...
  notify: handler1
  register: deployed
  tags:
    - deploy

- meta: flush_handlers
  tags:
    - deploy

- name: create sandbox with docker-compose
  command: "make start PROJECT=graphite{{ item.key }}"
  args:
    chdir: "/opt/graphite/{{ item.key }}"
  with_dict: "{{ graphite_sandbox_devs }}"
  when: deployed.changed
  tags:
    - deploy
```

**handlers/main.ym:**

```
- name: handler1
  debug:
    msg: "Handler run!"
  tags: 
    - deploy
```

**app.py:**

```
    playbook = 'playbook.yml'
    inventory = 'inventory/test'
    tags = ['deploy']

    stats = callbacks.AggregateStats()
    playbook_cb = callbacks.PlaybookCallbacks(verbose=utils.VERBOSITY)
    runner_cb = callbacks.PlaybookRunnerCallbacks(stats,verbose=utils.VERBOSITY)

    os.chdir(workspace)
    pb = ansible.playbook.PlayBook(
        playbook=playbook,
        inventory=inventory,
        only_tags=tags,
        callbacks=playbook_cb,
        runner_callbacks=runner_cb,
        stats=stats
    )

    pb.run()
```

**Expected Results:**
This is what happens when run with `ansible-playbook -i inventory/test playbook.yml --tags "deploy"`

```
TASK: [test-role | pull repos] *********************************************
changed: [52.21.94.60] => Git repo updated

TASK: [test-role | handler1] *********************************************
ok: [52.21.94.60] => {
    "msg": "Handler run!"
}

TASK: [test-role | create sandbox with docker-compose] *********************
changed: [52.21.94.60] => Succeeds because handler run
```

**Actual Results:**
This is what happens when run through python app

```
TASK: [test-role | pull repos] *********************************************
changed: [52.21.94.60] => Git repo updated

TASK: [test-role | create sandbox with docker-compose] *********************
failed: [52.21.94.60] => Fails because requires handlers be run
```
