### ISSUE TITLE
when: .... is defined not protect from undefined var?

### ISSUE THREAD

**Issue by mogadanez** [ansible/ansible#12311]
##### Issue Type:
- Bug Report
##### Ansible Version:

source, rev 6dac8512a1dc92ad9eee892dcd623b3f5825c10b
##### Ansible Configuration:

ec2.py inventory
##### Environment:

Debian Jessie
##### Summary:

follow snippet 

```
- name: copying custom beams
  copy: "src={{ item }} dest={{ riak_patch_dir }}/"
  with_fileglob:
    - "{{riak_custom_beams_dir}}/*.beam"
  when: riak_custom_beams_dir is defined
```

failed with  
`FAILED! => {"failed": true, "msg": "ERROR! 'riak_custom_beams_dir' is undefined"}`
##### Steps To Reproduce:

just run simple playbook 
##### Expected Results:

  `when: riak_custom_beams_dir is defined` guard should protect me from fail in this case
##### Actual Results:

stop working,  was work fine in 1.9.1
