### ISSUE TITLE
False error 'This task 'service' has extra params...'

### ISSUE THREAD

**Issue by skylerbunny** [ansible/ansible#12331]
Consider this task block:

```
- name: restart the workers
  service:
    name: worker_{{ item.nr }}
    state: restarted
    args: -w 60
  with_items: web_workers
```

In Ansible 2.0+, when run, this produces the error 'ERROR! this task 'service' has extra params, which is only allowed in the following modules: ...'
1. According to http://docs.ansible.com/ansible/service_module.html , this is a valid syntax. 'args' is an alias for 'arguments'.
2. If I do use 'arguments' rather than 'args', the error does not occur.

Bottom line: 'args' is not being respected in the service module as an acceptable alias for 'arguments'.
