### ISSUE TITLE
port b723f9a09a91b125b684343815dc23dbd88f52ed to branch stable-1.9

### ISSUE THREAD

**Issue by Dieken** [ansible/ansible#12346]
Could you port commit b723f9a09a91b125b684343815dc23dbd88f52ed to branch stable-1.9?  CentOS 6.x EPEL repository doesn't have 2.0.x.

See https://github.com/ansible/ansible/commit/b723f9a09a91b125b684343815dc23dbd88f52ed

**Comment by Dieken** [comment]
Just got a dirty workaround:

``` yaml
- name: install collectd packages
  yum: name=/opt/{{ item }} state=present
  with_items: "{{ collectd_rpm_files | join(',/opt/') }}"
```
