### ISSUE TITLE
uri module requires HTTP verbs to be upper case

### ISSUE THREAD

**Issue by proffalken** [ansible/ansible#12343]
Issue Type:

Bug Report / Documentation Report

Ansible Version:

ansible 1.9.3

Ansible Configuration:

N/A

Environment:

N/A

Summary:

When trying to "PUT" a file using Ansible's URI module, the HTTP Verb that is being used _must_ be upper case.  This is not clear (IMHO) in the documentation and I do not know whether I should be filing a bug against the code to make it case-insensitive or a bug against the documentation to make it clearer that the module is case sensitive. 

I would argue that given none of the other arguments for modules are case-sensitive, this should be a code change, however it's currently 0120hrs where I am so I may not be thinking straight! :)

Steps To Reproduce:

```
- name: Add the consul service config to disk
  template: src=elasticsearch_consul_service.json dest=/tmp/elasticsearch_consul_service.json

- name: Upload the consul service to the system
  uri: 
    url: http://localhost:8500/v1/agent/service/register
    method: PUT
    body: /tmp/elasticsearch_consul_service.json
    body_format: json
```

Expected Results:

The file should be uploaded using the "PUT" HTTP Verb

Actual Results:

ASK: [elasticsearch | Upload the consul service to the system] **************\* 
failed: [10.128.1.187] => {"failed": true}
msg: value of method must be one of: GET,POST,PUT,HEAD,DELETE,OPTIONS,PATCH, got: put
