### ISSUE TITLE
elasticache : change : false is missing or not working

### ISSUE THREAD

**Issue by jyotirbhandari** [ansible/ansible#12419]
Issue Type:

Bug Report

Ansible Version: 

1.9.2

Ansible Configuration:

elasticache: When adding new cache cluster in the main.yml and re-run the playbook

Environment:

Amazon Linux ( AWS Amazon ).

Summary:

changed: false is missing or not working, like it is there in ec2 and ec2_vpc.

Steps To Reproduce:

main.yml

```

---
- name: Creating first elasticache
  local_action:
    module: elasticache
    name: "test-1"
    cache_security_groups: []
    state: present
    node_type:  cache.m1.small
    region: us-east-1d
    num_nodes: 1
    security_group_ids: sg-xxxx
    cache_subnet_group: test-sub
```

main.yml

```

---
- name: Creating first elasticache
  local_action:
    module: elasticache
    name: "test-2"
    cache_security_groups: []
    state: present
    node_type:  cache.m1.small
    region: us-east-1d
    num_nodes: 1
    security_group_ids: sg-xxxx
    cache_subnet_group: test-sub
```

executing ansible-playbook 

Actual Results:

```
msg: 'test-1' requires destructive modification. 'hard_modify' must be set to true to proceed
```
