### ISSUE TITLE
ansible_ssh_user not available as variable in become expr

### ISSUE THREAD

**Issue by apollo13** [ansible/ansible#12437]
##### Issue Type:

Bug Report
##### Ansible Version:

devel
##### Summary:

ansible_ssh_user cannot be used in become expressions
##### Steps To Reproduce:

This playbook:

```

---
- hosts: all
  gather_facts: no
  tasks:
  - name: whoami
    shell: id -u && echo {{ ansible_ssh_user }}
    become: "{{ ansible_ssh_user != 'root' }}"
```

errors out with:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'ansible_ssh_user' is undefined"}
```

If you remove the become line it properly prints your user…

@jimi-c: The promised issue as followup to the become/sudo discussions from yesterday
