### ISSUE TITLE
v2: synchronize with delegate_to badly broken

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12464]
**Issue Type**: Bug Report
**Ansible Version**:

```
ansible 2.0.0 (devel f563b22446) last updated 2015/09/22 10:14:17 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 59afecace4) last updated 2015/09/19 10:16:59 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD dee690d7f4) last updated 2015/09/19 10:16:59 (GMT +300)
```

**Summary**:
Attempting to synchronize some files between remote hosts A and B actually tries to synchronize from ~~localhost to A~~ B to itself.

(This is all that's remaining from #12347.)

**Steps to Reproduce**
Replace 'fridge' and 'muskatas' with two hosts you can SSH to

``` yml
- hosts: muskatas
  gather_facts: no
  tasks:
    - synchronize: mode=push src=/etc/hostname dest=/tmp/hostname
      delegate_to: fridge

    - command: cat /tmp/hostname
      register: x

    - debug: 'msg="got: {{x.stdout}}"'
```

**Expected Results**:

```

PLAY [muskatas] *************************************************************** 

TASK: [synchronize mode=push src=/etc/hostname dest=/tmp/hostname] ************ 
changed: [muskatas -> fridge]

TASK: [command cat /tmp/hostname] ********************************************* 
changed: [muskatas]

TASK: [debug msg="got: {{x.stdout}}"] ***************************************** 
ok: [muskatas] => {
    "msg": "got: fridge"
}

PLAY RECAP ******************************************************************** 
muskatas                   : ok=3    changed=2    unreachable=0    failed=0   
```

**Actual Results**:

```
PLAY ***************************************************************************

TASK [synchronize dest=/tmp/hostname src=/etc/hostname mode=push] **************
changed: [muskatas]

TASK [command] *****************************************************************
changed: [muskatas]

TASK [debug msg=got: {{x.stdout}}] *********************************************
ok: [muskatas] => {
    "changed": false, 
    "msg": "got: muskatas"
}

PLAY RECAP *********************************************************************
muskatas                   : ok=3    changed=2    unreachable=0    failed=0   
```
