### ISSUE TITLE
Allow running task or play in check_mode from playbook

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible#12498]
Ansible check_mode allows determining if a task _would_ have changed something, but only on the level of an entire play.

But there are obvious cases where idempotency requires being able to change the order of events - i.e. check if a file would be changed, if so, stop a daemon and change the file - otherwise do nothing.

This can be replicated by comparing mtimes locally and remotely, but leads to complicated syntax for something the existing feature can already provide.

Ideally something like this would be possible:

``` yaml
- hosts: webservers
  tasks:
  - copy: src=monitoredfile dest=monitoredfile
    check_mode: true
    register: copy_check

  - service: name=webserver state=stopped
    when: copy_check.changed

  - copy: src=monitoredfile dest=monitoredfile
    when: copy_check.changed

  - service: name=webserver state=started
    when: copy_check.changed
```

This is simple and readable, and helps in dealing with services which may be monitoring config directories for new files but which would might like to try and avert for changes like that (exim with a perl interpreter can be a problem in this regard).
