### ISSUE TITLE
"'item' is undefined" if using delegate_to with with_items

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#12499]
##### Issue Type:
- Bug Report
##### Ansible Version:

2.0.0 devel (master, 89a78ba)
##### Ansible Configuration:

Stock.
##### Environment:

Mac OS X 10.10.4.
##### Summary:

This task:

``` yaml
    - name: Disable the backend server in HAProxy.
      haproxy:
        state: disabled
        host: '{{ inventory_hostname }}'
        socket: /var/lib/haproxy/stats
        backend: habackend
      delegate_to: "{{ item }}"
      with_items: groups.balancer
```

results in the error message:

```
ERROR! 'item' is undefined
```

I run the playbook with the task above using [this inventory file](https://github.com/geerlingguy/ansible-for-devops/blob/master/deployments-balancer/inventory). You can reproduce the scenario exactly by downloading the project linked below and running through the setup in the README.md file.

If run in Ansible 1.9.3, I get a successful 'changed' message during playback runs:

```
TASK: [Disable the backend server in HAProxy.] ******************************** 
changed: [192.168.4.3 -> 192.168.4.2] => (item=192.168.4.2)
```
##### Steps To Reproduce:

I'm testing some of the example playbooks I have in Ansible for DevOps, and one of them, [deployments-balancer](https://github.com/geerlingguy/ansible-for-devops/tree/master/deployments-balancer), which works fine in Ansible <= 1.9.3, fails with the above error on 2.0.0 devel.

This example playbook follows the same style as the official LAMP/HAProxy rolling updates example: https://github.com/ansible/ansible-examples/blob/master/lamp_haproxy/rolling_update.yml.
##### Expected Results:

Task should complete, delegated to each of the items in the inventory list `groups.balancers`
##### Actual Results:

Error message: `ERROR! 'item' is undefined`
