### ISSUE TITLE
win_iis_webapppool: The property 'Value' cannot be found on this object

### ISSUE THREAD

**Issue by rriggs** [ansible/ansible#12494]
This is a new error today, 9/23, that does not exist on 9/15.  The win_iis_webapppool task works in the older version, properly creating the app pool (or detecting that it is created) and fails with today's pull.

``` text
TASK [foo : Create fooservice app pool] **************************************
fatal: [foohost]: FAILED! => {"changed": false, "failed": true, "msg": "The property 'Value' cannot be found on this object. Verify that the property exists."}
```

Here is the task:

``` yml
- name: Create fooservice app pool
  win_iis_webapppool:
    name: "fooservice"
    state: started
    attributes: "enable32BitAppOnWin64:true|managedRuntimeVersion:v4.0|managedPipelineMode:0"
```
