### ISSUE TITLE
Add ansible_version information to the facts

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#12508]
##### Issue Type:

Feature Idea
##### Ansible Version:

Any version after 1.8.0, [in which the `ansible_version` dict was added](https://github.com/ansible/ansible/commit/48a0236ec610f5bf29affb274cecaf77e8ddad57).
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

`ansible_version` exists as a variable. It would be very helpful to make the dict also exist in facts.
##### Steps To Reproduce:

Well, nothing, just run `setup` module or let the fact gathering do its magic.
##### Expected Results:

`ansible_version` would be in the result of `ansible all -i hosts -m setup`.
##### Actual Results:

At the moment, one needs to run:

```
$ ansible all -i hosts -m debug -a "var=ansible_version"
test_node | success >> {
    "var": {
        "ansible_version": {
            "full": "1.9.2",
            "major": 1,
            "minor": 9,
            "revision": 2,
            "string": "1.9.2"
        }
    }
}
```

In a playbook, one must run the additional task to set `ansible_version` in the `hostvars`:

``` yaml
- name: Ensure ansible_version is added to the gathered facts
  set_fact:
    ansible_version: "{{ ansible_version }}"
```
