### ISSUE TITLE
support delegation to docker container

### ISSUE THREAD

**Issue by ibotty** [ansible/ansible#12503]
It would greatly simplify playbooks if there were a way to delegate command to docker containers.

E.g. the following task:

``` yaml
- name: command within my/image
  shell: "docker run --rm my/image command
```

would be

``` yaml
- name: command within my/image
  delegate_to_docker: my/image
  shell: command
```

It would be most useful to support running commands in both
- existing running containers (`docker exec --name`),
- and one-of containers (`docker run --rm`).

It should support the usual docker configuration (i.e. volumes, etc).

I am thinking, it should use the container's python runtime (if there is any). So some containers might only be able to run raw commands.

If there is interest, I might implement that myself, please give me some guidance on where to start in that case.
