### ISSUE TITLE
Variables in dependency role names are not being expanded

### ISSUE THREAD

**Issue by jpetrelliswork** [ansible/ansible#12505]
Issue Type:
Bug Report

Ansible Version:
ansible 2.0.0 (devel 5d3d9cfe0d) last updated 2015/09/24 07:54:36

Ansible Configuration:
Nothing relevant changed here.

Environment:
SLES11SP2

Summary:
Variables in dependency role names are not being expanded.

Steps To Reproduce:
Create role with dependencies in meta/main.yml
Use variable in role name:

```
dependencies:
   - { role: "roles/{{ myrole }}" }
```

Define myrole in playbook.

```
- hosts: all
  vars:
    myrole: "role2"
  roles:
    - role: role_that_calls_role2
```

Expected Results:
Jinja will evaluate and execute the dependency.  This worked pre-2.0.

Actual Results:

```
Role not found.
SSH password: 
ERROR! the role 'roles/{{myrole}}' was not found in
```
