### ISSUE TITLE
Template creation failing when using sudo_user

### ISSUE THREAD

**Issue by genofedanzo** [ansible/ansible#12509]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (devel 5d3d9cfe0d9dd3943245c65b92fd91d33e446f2b)
##### Summary:

We have a task that writes a template file to a remote server as a sudo_user and it has broken in 2.0 because of permission problems.
##### Steps To Reproduce:

```
- name: Test Template
  tasks:
    - name: Test Template | Write File
      template: src=test.txt.j2 dest=/tmp/test.txt force=yes
      sudo_user: "testuser"
```
##### Expected Results:

File will be written to /tmp/ directory.
##### Actual Results:

`fatal: [123.123.123]: FAILED! => {"changed": false, "failed": true, "msg": "Source /tmp/ansible-tmp-1443108503.34-115637427635543/source not readable"}`

The source file was created as the initial ansible user with only read permissions for the user.  The error kicks out after it sudos to the sudo_user and tries to copy the staged file to the final destination.
