### ISSUE TITLE
delegate_to not working correctly in 2.0.0 devel - HAProxy tasks fail

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#12527]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (devel b757798f3e) last updated 2015/09/25 21:12:40 (GMT -500)
##### Ansible Configuration:

Defaults.
##### Environment:

Mac OS X 10.10.4
##### Summary:

This might be related to https://github.com/ansible/ansible/issues/12499, but basically, if I run a particular task with delegate_to and Ansible 2.0.0 devel, the task fails.

If I run the same task standalone in its own playbook, directly on the host (just removing `delegate_to`), it succeeds. If I run the same playbook with the failing task in Ansible <= 1.9.3, it succeeds. Only Ansible 2.0.0 devel is failing.

You can quickly emulate the entire environment and see the problem using the [deployments-balancer](https://github.com/geerlingguy/ansible-for-devops/tree/master/deployments-balancer) example (it's the exact playbook I'm running, using a set of three VirtualBox VMs configured via the Vagrantfile).
##### Steps To Reproduce:

Set up an HAProxy server and at least one server managed by HAProxy as a load balancer (note: this seems like it may be an issue that would affect other delegated tasks, but I've only done testing with HAProxy sockets so far).

Set up a playbook to run on an app server (that's _not_ the HAProxy host), with a task using the `haproxy` module to manage HAProxy on a delegated host:

``` yaml

---
- hosts: app
  sudo: yes

  tasks:
    - name: Disable the backend server in HAProxy.
      haproxy:
        state: disabled
        host: 192.168.4.3
        socket: /var/lib/haproxy/stats
        backend: habackend
      delegate_to: 192.168.4.2
```

Run this playbook.
##### Expected Results:

The playbook should indicate a change occurred, delegated to the HAProxy balancer:

```
TASK: [Disable the backend server in HAProxy.] ******************************** 
changed: [192.168.4.3 -> 192.168.4.2]
```

(This is the output from Ansible 1.9.3).
##### Actual Results:

The playbook errors out, with:

```
TASK [Disable the backend server in HAProxy.] **********************************
fatal: [192.168.4.3 -> 192.168.4.2]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 2074, in <module>\r\n    main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 316, in main\r\n    ansible_haproxy.act()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 287, in act\r\n    self.disabled(self.host, self.backend, self.shutdown_sessions)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 273, in disabled\r\n    self.execute(cmd)\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1443233601.59-214579071947909/haproxy\", line 172, in execute\r\n    self.client.connect(self.socket)\r\n  File \"/usr/lib/python2.7/socket.py\", line 224, in meth\r\n    return getattr(self._sock,name)(*args)\r\nsocket.error: [Errno 2] No such file or directory\r\n", "parsed": false}
```

If I take the exact same task, and put it in a playbook on its own, and run that playbook directly on the balancer HAProxy server in Ansible 2.0.0 devel (without using delgate_to, basically), everything works fine:

``` yaml

---
- hosts: balancer
  sudo: yes

  tasks:
    - name: Disable the backend server in HAProxy.
      haproxy:
        state: enabled
        host: '192.168.4.3'
        socket: /var/lib/haproxy/stats
        backend: habackend
```
