### ISSUE TITLE
connection: local not honored in blocks

### ISSUE THREAD

**Issue by senorsmile** [ansible/ansible#12526]
As discussed here https://groups.google.com/forum/#!topic/ansible-devel/ZhVjG3tP-tA (that appears to be related any way), using connection: local with a block: doesn't work; the connection still ends up sshing and running all tasks in the block on the remote host. 

E.g. 

```
- block: 
    - shell: uptime
    - shell: hostname
  connection: local
```
