### ISSUE TITLE
--list-tags and --list-tasks do not honor --skip-tags parameter

### ISSUE THREAD

**Issue by jschank** [ansible/ansible#12533]
##### ISSUE TYPE
Documentation Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.1

##### SUMMARY
As a playbook writer, wanted to see which tasks would run (without running them) and which would not. 
It seems that --list-tags and --list-tasks might be appropriate for that job.
But when combined with --skip-tags, I still see all tasks. I would expect to see only the tasks that apply when --skip-tags, or --tags is used.

**Comment by ryanpineo** [comment]
I was looking to fix this but it seems to be working fine for me on 1.9.3.  What version of ansible are you using?

**Comment by jschank** [comment]
I am on 1.9.3 also. perhaps the order of the parameters matters?

**Comment by bcoca** [comment]
order does not matter, most --list options bypass/ignore additional options
(we need to document this better)

**Comment by ansibot** [comment]
@jschank Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jsutton** [comment]
ansible 2.8.3
  python version = 3.6.8 (default, Jan 14 2019, 11:02:34) [GCC 8.0.1 20180414 (experimental) 

Considering the following playbook:

```yaml
---
- name: play1
  hosts: localhost
  connection: local
  tasks:
    - name: play1_debug1
      debug:
        msg: "Hello world"
    - name: play1_debug2
      debug:
        msg: "Hello world"
      tags: play1_debug2_tag1
  tags:
    - play1_tag1

- name: play2
  hosts: localhost
  connection: local
  tasks:
    - name: play2_debug1
      debug:
        msg: "Hello world"
  tags:
    - play2_tag1

- name: play3
  hosts: localhost
  connection: local
  tasks:
    - name: play3_debug1
      debug:
        msg: "Hello world"
  tags:
    - play3_tag1
```
If I run `ansible-playbook site.yml --list-tasks` I get the following:
```yaml
playbook: site.yml

  play #1 (localhost): play1    TAGS: [play1_tag1]
    tasks:
      play1_debug1      TAGS: [play1_tag1]
      play1_debug2      TAGS: [play1_debug2_tag1, play1_tag1]

  play #2 (localhost): play2    TAGS: [play2_tag1]
    tasks:
      play2_debug1      TAGS: [play2_tag1]

  play #3 (localhost): play3    TAGS: [play3_tag1]
    tasks:
      play3_debug1      TAGS: [play3_tag1]
```

This is the expected output. If I then run `ansible-playbook site.yml --list-tasks --skip-tags play1_tag1` I get the following:

```yaml
playbook: site.yml

  play #1 (localhost): play1    TAGS: [play1_tag1]
    tasks:

  play #2 (localhost): play2    TAGS: [play2_tag1]
    tasks:
      play2_debug1      TAGS: [play2_tag1]

  play #3 (localhost): play3    TAGS: [play3_tag1]
    tasks:
      play3_debug1      TAGS: [play3_tag1]
```
Notice that the tasks in `play #1` have disappeared. This also appears to be desired behavior.
I can then run `ansible-playbook site.yml --list-tasks --list-tags --skip-tags play1_tag1` and get the following:
```yaml
playbook: site.yml

  play #1 (localhost): play1    TAGS: [play1_tag1]
    tasks:
      TASK TAGS: [play1_tag1]

  play #2 (localhost): play2    TAGS: [play2_tag1]
    tasks:
      play2_debug1      TAGS: [play2_tag1]
      TASK TAGS: [play2_tag1]

  play #3 (localhost): play3    TAGS: [play3_tag1]
    tasks:
      play3_debug1      TAGS: [play3_tag1]
      TASK TAGS: [play3_tag1]
```
This will omit the tasks with `play1_tag1`, but show that the `play1_tag1` tag is applied to items in `play #1`. This shows that `--list-tags` is not affected by `--skip-tags`. Again, this appears to be desired behavior. 

Based on this testing, the original issue appears to no longer be present in devel. It is possible that the documentation is unclear.
