### ISSUE TITLE
git clone failing

### ISSUE THREAD

**Issue by muhammad-ammar** [ansible/ansible#12544]
I am trying to setup a dev environment using ansible and vagrant. Now i am stuck at cloning a git repo from bitbucket.

Below are Vagrantfile and ansible settings and things i have tried.  

ansible version is `1.9.3`

In my Vagrantfile i have `config.ssh.forward_agent = true`

In my deploy.yml i have 

```
- name: ensure bitbucket is a known host
  lineinfile:
    dest: /home/vagrant/.ssh/known_hosts
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -p 443 -t rsa altssh.bitbucket.org') }}"
    regexp: "^altssh\\.bitbucket\\.org"
  sudo_user: "vagrant"
  tags: known_hosts

- name: checkout opentest repo
  git: >
    dest="/home/vagrant/ot/"
    repo="ssh://git@altssh.bitbucket.org:443/muhammadammar/opentest/"
    version="master"
    accept_hostkey=yes
  sudo_user: "vagrant"
  tags: checkout
```

Below is the output when ansible try to checkout the repo

```
<127.0.0.1> ESTABLISH CONNECTION FOR USER: vagrant
<127.0.0.1> REMOTE_MODULE git dest="/home/vagrant/ot/" repo="ssh:********@altssh.bitbucket.org:443/muhammadammar/opentest/" version=master accept_hostkey=yes
<127.0.0.1> EXEC ssh -C -vvv -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/ammar/.ansible/cp/%h-%r" -o StrictHostKeyChecking=no -o Port=2222 -o IdentityFile="/Users/ammar/.vagrant.d/insecure_private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 127.0.0.1 /bin/sh -c 'sudo -k && sudo -HE -S -p "[sudo via ansible, key=vwkfotuvzzmllxvxptkgehjzdlqygoez] password: " -u vagrant /bin/sh -c '"'"'echo BECOME-SUCCESS-vwkfotuvzzmllxvxptkgehjzdlqygoez; LANG=C LC_CTYPE=C /usr/bin/python'"'"''
failed: [default] => {"cmd": "/usr/bin/git ls-remote 'ssh:********@altssh.bitbucket.org:443/muhammadammar/opentest/' -h refs/heads/master", "failed": true, "rc": 128}
stderr: RSA host key for IP address '131.103.20.174' not in list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

msg: RSA host key for IP address '131.103.20.174' not in list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

FATAL: all hosts have already failed -- aborting

           to retry, use: --limit @/Users/ammar/dev.retry

default                    : ok=1    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

On my host i have added my private key to ssh authentication agent. I can see private key identities using `ssh-add -l` on both host and on vagrant box.

In vagrant box i can successfully clone the repo using `git clone ssh://git@altssh.bitbucket.org:443/muhammadammar/opentest ot`

Even the below is not working in ansible
`shell: "git clone ssh://git@altssh.bitbucket.org:443/muhammadammar/opentest/ /home/vagrant/omp/"`

I am not sure what is the issue. Can anyone help to resolve this issue.
