### ISSUE TITLE
unskippable tasks for --start-at-task

### ISSUE THREAD

**Issue by Dawnthorn** [ansible/ansible#12565]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.1

##### SUMMARY
I frequently have a pattern where I have a set of vars that I want to include for a certain machine. So, for example, I'll have a variable like "instance_type" that can be things like "t2.micro" or "t2.small". Then I have a role that wants to set specific instance variables depending on the type, so I'll include the vars at the top of my roles/apache/tasks/main.yml file like this:

``` yaml
- include_vars: roles/apache/vars/{{ instance_type}}.yml

- name: bar
  copy: src=httpd.conf dest=/etc/apache2

- name: foo
  template: src=apache.conf dest=/etc/apache2/conf-available
```

This works great until I do '--start-at-task="foo"' because when I do that, my include_vars doesn't get executed. 

I would like an 'unskippable' tag  for tasks that should get executed even when using '--start-at-task', or maybe we could reuse 'always' for this purpose.

I should also add, that I sort of get around this by adding it to my playbook:

``` yaml
- hosts: webservers
  vars_files:
    - roles/apache/vars/{{ instance_type }}.yml
  roles:
    - apache
```

This gets my the desired behavior, but now you have to do the vars_files includes whenever you include that role. So if there was some way to specify vars_files for a role in the role files somewhere and you can use Jinja2 with them, then that would work as well.
