### ISSUE TITLE
delegate_to on role is ignored

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#12560]
**Issue Type:**

Bug Report

**Ansible Version:**

ansible 2.0.0 (devel 95ede22a1e) last updated 2015/09/29 13:45:01 (GMT +300)
  lib/ansible/modules/core: (detached HEAD a4ac171a07) last updated 2015/09/29 13:45:02 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 3c8c716801) last updated 2015/09/29 13:45:03 (GMT +300)
  config file = /home/albert/ansible/ansible.cfg
  configured module search path = None

**Ansible Configuration:**

**Environment:**

**Summary:**

When adding a 'delegate_to' statement on a whole role, it doesn't work.
In my case I need to run a role completely on localhost (or 127.0.0.1 (same result)), and it just being ignored.
Works fine on 1.9.3

**Steps To Reproduce:**

test.yml

``` yaml

---
- hosts: serbtest
  roles:
    - role: vars
      delegate_to: 127.0.0.1
```

roles/vars/tasks/main.yml

``` yml

---
- file:
    path: /tmp/test
    state: directory
```

The directory is created on remote host (serbtest in my case), instead of on localhost.

**Expected Results:**

The directory should have been created on localhost
