### ISSUE TITLE
Notifies run after post_task when playbook run with tasks, was supposed to be fixed in 11574

### ISSUE THREAD

**Issue by smcavoy-travelbird** [ansible/ansible#12575]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
1.9

##### SUMMARY
I do not believe #11574  is fixed.

Playbook:

```

---
- hosts: localhost
  sudo: no
  user: bob
  gather_facts: no
  vars:
    testme: hereitis
  handlers:
    - name: notifyme
      local_action: debug
      args:
        msg: notifyme
  pre_tasks:
    - name: pre task thing
      local_action: debug
      args:
         msg: Pre task
      tags: testtag
  tasks:
    - name: test local action variables
      local_action: copy
      args:
        content: "{{ testme }}"
        dest: /tmp/file1
      tags: testtag
      notify: notifyme
  post_tasks:
    - name: post task
      local_action: debug
      args:
        msg: post task
      tags: testtag
```

Run command:

```
ansible-playbook -i /tmp/inv tt.yml  --tags testags
```

Output:

```
PLAY [localhost] **************************************************************

TASK: [pre task thing] ********************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "Pre task"
}

TASK: [test local action variables] *******************************************
changed: [localhost -> 127.0.0.1]

TASK: [post task] *************************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "post task"
}

NOTIFIED: [notifyme] **********************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "notifyme"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0
```

Expected output:

```
PLAY [localhost] **************************************************************

TASK: [pre task thing] ********************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "Pre task"
}

TASK: [test local action variables] *******************************************
changed: [localhost -> 127.0.0.1]

NOTIFIED: [notifyme] **********************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "notifyme"
}

TASK: [post task] *************************************************************
ok: [localhost -> 127.0.0.1] => {
    "msg": "post task"
}

PLAY RECAP ********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0
```

**Comment by jimi-c** [comment]
@smcavoy-travelbird are you running against devel or 1.9.x? We fixed this in devel, which shows this output when running your playbook:

<pre>
# ansible-playbook -vv 12575.yml 
Using /etc/ansible/ansible.cfg as config file
1 plays in 12575.yml
PLAY ***************************************************************************
TASK [pre task thing] **********************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "Pre task"
}
TASK [test local action variables] *********************************************
NOTIFIED HANDLER notifyme
changed: [localhost] => {"changed": true, "checksum": "491a622dd732125db250c0c5145af6c59a116c16", "dest": "/tmp/file1", "gid": 0, "group": "root", "md5sum": "26829d554f892cf4e1cc3195488200b1", "mode": "0644", "owner": "root", "secontext": "unconfined_u:object_r:user_tmp_t:s0", "size": 8, "src": "/root/.ansible/tmp/ansible-tmp-1443626688.26-174117288027488/source", "state": "file", "uid": 0}
RUNNING HANDLER [notifyme] *****************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "notifyme"
}
TASK [post task] ***************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "post task"
}
PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
</pre>

Our normal policy is to close issues once they have been resolved in the development branch.

**Comment by smcavoy-travelbird** [comment]
@jimi-c  This is with 1.9.3 and 1.9.2

**Comment by dalmadebreceni** [comment]
@jimi-c it's important to have the "--tags testtag" in the options, without that it is in the right order. With it, it is not. The issue is presented in all versions of 1.9 which is available with pip install.

**Comment by smcavoy-travelbird** [comment]
Any update on this? I mean it seems like a pretty painful bug. 

In a task you restart/reload your app

In your post task you add it back to the load balancer.

The current bug means it is added back to the load balancer and then restarted. not ideal

**Comment by bborysenko** [comment]
Just to confirm that issue is really exist with 1.9.4, but fixed with development version. I suppose the right questions is it going to be back ported to 1.9.x?

**Comment by jimi-c** [comment]
@bborysenko currently there are no plans to backport it, due to a lot of fixes in the devel rewrite not having a direct correlation to the code in the stable-1.9 branch. I have added the `stable-1.9` milestone to this though, so we can consider it in the future.

Thanks for verifying against devel!

**Comment by roderickrandolph** [comment]
@smcavoy-travelbird I agree--this is a painful bug for orchestration

Has anyone found an alternative workaround?

**Comment by roderickrandolph** [comment]
Adding flush_handlers as a first task to post_tasks seems to be an alternative in 1.9.4 as long as the flush is also tagged.

```
  post_tasks:
    - meta: flush_handlers
      tags: testtag
    - name: post task
      local_action: debug
      args:
        msg: post task
      tags: testtag
```
