### ISSUE TITLE
V2 Regression: 'group_vars/group.yml' not loaded for groups created via 'group_by'

### ISSUE THREAD

**Issue by indrajitr** [ansible/ansible#12582]
Issue Type:
Bug Report

Ansible Version:
ansible 2.0.0 (devel 4cfcf5d61b) last updated 2015/09/30 15:14:00 (GMT -500)

Ansible Configuration:
- site.yml

```

---
- name: Create a group of all hosts by operating system
  hosts: all
  pre_tasks:
      group_by: key={{ ansible_os_family | lower }}

- name: Load group variable
  hosts: archlinux
  roles: test
```
- group_vars/all.yml

```

---
group_vars_all: All vars

```
- group_vars/router.yml

```

---
group_vars_router: Router vars

```
- group_vars/archlinux.yml

```

---
group_vars_os_family: OS Family vars

```
- roles/test/tasks/main.yml

```

---
- debug: msg="group_vars_all = {{group_vars_all | default('nope') }}"

- debug: msg="group_vars_router = {{group_vars_router | default('nope') }}"

- debug: msg="group_vars_os_family = {{group_vars_os_family | default('nope') }}"

```

Environment:

N/A

Summary:

Based on above config, I would expect _all of_ `group_vars_all`, `group_vars_router` and `group_vars_os_family` vars to be available. However, `group_vars_all`, `group_vars_router` vars are available as expected. But `group_vars_os_family` is not.
