### ISSUE TITLE
copy and template fail when using become

### ISSUE THREAD

**Issue by Gillingham** [ansible/ansible#12597]
On a solaris 10 target with ansible 1.9.3 using template or copy with become fails with `fatal: [rpm-zone3] => ssh connection closed waiting for a privilege escalation password prompt`

Full log from the failed section:

```
TASK: [web | Create CAM pasword file for agent install] ***********************
<rpm-zone3> ESTABLISH CONNECTION FOR USER: gillingh
<rpm-zone3> EXEC ssh -C -tt -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/Users/gillingh/.ansible/cp/ansible-ssh-%h-%p-%r" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 rpm-zone3 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=rcvzjadfoojvpwltuosfnxkbfmoztdvp] password: " -u app-srv /bin/sh -c '"'"'echo BECOME-SUCCESS-rcvzjadfoojvpwltuosfnxkbfmoztdvp; rc=flag; [ -r /tmp/cam_agent_password ] || rc=2; [ -f /tmp/cam_agent_password ] || rc=1; [ -d /tmp/cam_agent_password ] && rc=3; /tps/bin/python -V 2>/dev/null || rc=4; [ x"$rc" != "xflag" ] && echo "${rc} "/tmp/cam_agent_password && exit 0; (/tps/bin/python -c '"'"'"'"'"'"'"'"'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1(); afile = open("'"'"'"'"'"'"'"'"'/tmp/cam_agent_password'"'"'"'"'"'"'"'"'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0: hasher.update(buf) buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (/tps/bin/python -c '"'"'"'"'"'"'"'"'import sha; BLOCKSIZE = 65536; hasher = sha.sha(); afile = open("'"'"'"'"'"'"'"'"'/tmp/cam_agent_password'"'"'"'"'"'"'"'"'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0: hasher.update(buf) buf = afile.read(BLOCKSIZE) afile.close() print(hasher.hexdigest())'"'"'"'"'"'"'"'"' 2>/dev/null) || (echo '"'"'"'"'"'"'"'"'0 '"'"'"'"'"'"'"'"'/tmp/cam_agent_password)'"'"''
```

A sample copy task is:

``` yaml
- name: Create CAM pasword file for agent install
  become: yes
  become_user: app-srv
  when: agent_list.stdout.find('No configured agents') != -1
  copy: content="{{ CAM_agent_password }}" dest=/tmp/cam_agent_password
          mode=0600 owner=app-srv group=app-adm
  register: cam_password_file
```

The odd thing is, this seems to be specific to the template and copy modules, I use become in the same set of tasks with no issues prior with the command, lineinfile, and user modules.
