### ISSUE TITLE
APT Module Issue using {{ item }} variable

### ISSUE THREAD

**Issue by luisdalves** [ansible/ansible#12599]
I have the following task and I was expecting install both oracle-java packages in the specified version:

``` yaml
- name: installing oracle-java-installer
  apt: state=present name={{ item }}{% if deb.oracle_java.pkgversion is defined %}={{ deb.oracle_java.pkgversion }}{% endif %}
  with_items:
    - oracle-java{{ java.version }}-installer
    - oracle-java{{ java.version }}-set-default
  when: ansible_distribution == "Ubuntu" and java.version is defined
```

but I'm seeing this:

```
<10.0.3.4> REMOTE_MODULE apt state=present name=oracle-java8-installer,oracle-java8-set-default=8u25+...-1
```

After that, only oracle-java8-set-default have the specified version.

This is my workaround:

``` yaml
- name: installing oracle-java-installer
  apt: state=present name={{ item }}
  with_items:
    - oracle-java{{ java.version }}-installer{% if deb.oracle_java.pkgversion is defined %}={{ deb.oracle_java.pkgversion }}{% endif %}
    - oracle-java{{ java.version }}-set-default{% if deb.oracle_java.pkgversion is defined %}={{ deb.oracle_java.pkgversion }}{% endif %}
  when: ansible_distribution == "Ubuntu" and java.version is defined
```

is this an expected behavior?

ansible 1.9.3
  configured module search path = /usr/local/lib/python2.7/dist-packages/ansible/modules
