### ISSUE TITLE
Combine filter can't sum hash values

### ISSUE THREAD

**Issue by shawnsi** [ansible/ansible#12596]
I've created a `merge` filter (https://github.com/shawnsi/ansible-merge-filter) that acts similarly to the `combine` filter but can sum hash leaf values.  For example, take these values:

``` yaml
one:
  a: 1
  b: 2
  c:
    d: [1]
two:
  a: 1
  c:
    d: [1]
    e: 4
```

Then `{{ one | merge(two) }}` would yield:

``` yaml
a: 2
b: 2
c:
  d: [1, 1]
  e: 4
```

Is there any appetite for including this filter in ansible?  Or should it be refactored as optional behavior in the `combine` filter?
