### ISSUE TITLE
Unexpected handling of parametrized roles involving dependencies and variable expansion

### ISSUE THREAD

**Issue by lvillani** [ansible/ansible#12634]
#### Ansible Version: 1.9.3 and 2.0.0 (as of 10a4a4e9)

Output from `ansible --version` is:

```
ansible 2.0.0
  config file = /Users/lvillani/.ansible.cfg
  configured module search path = None
```
#### Ansible Configuration:

```
➤ cat ~/.ansible.cfg 
[defaults]
become = True
become_ask_pass = False
gathering = smart
host_key_checking = False
inventory = hosts.ini
retry_files_enabled = False
roles_path = ./roles

[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=1800s
```
#### Environment:

I ran the provided test case locally on OS X 10.10.5:

```
➤ uname -prsv
Darwin 14.5.0 Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64 i386
```
#### Summary:

Ansible executes roles with dependencies in an unexpected way. Given the following:
- A role called `common` which accepts a parameter.
- A role called `role1` which depends on `common` (the dependency is declared through the role's
  `meta/main.yml` file). It also takes a parameter which it passes down to the `common` role via
  variable expansion.
- A role called `role2` which does the same as above.
- The `site.yml` file which "calls" both `role1` and `role2` passing a parameter with two
  different values.

It seems that Ansible optimizes execution of dependent roles when they are passed the same set of
parameters by running the dependency only once. It seems to do so before variable expansion takes
place, which means that with the following files, Ansible would execute the `common` role only once even though, at runtime, we expect it to be executed twice, since the parameter is expanded to two different values.

I've also created a simple test case that I'm publishing at: https://people.develer.com/~lvillani/testcase/ansible-role-dependency.tar.gz
##### roles/common/tasks/main.yml

``` yaml

---
- debug: msg="{{ role_parameter }}"
```
##### roles/role1/meta/main.yml

``` yaml

---
dependencies:
  - role: common
    role_parameter: "{{ param }}"
```
##### roles/role2/meta/main.yml

``` yaml

---
dependencies:
  - role: common
    role_parameter: "{{ param }}"
```
##### site.yml

``` yaml

---
- hosts: all
  gather_facts: no
  roles:
    - role: role1
      param: 1
    - role: role2
      param: 2
```
#### Steps To Reproduce:

Run the provided test case attached to this issue with:

```
ansible-playbook -i "localhost," -c local site.yml
```
#### Expected Results:

The `common` role should run twice: once outputting "1" and once outputting "2".
#### Actual Results:

The `common` role is run only once even though it should run two times with different parameters.
