### ISSUE TITLE
Skipping hosts after adding the EC2 instances

### ISSUE THREAD

**Issue by lakshmantgld** [ansible/ansible#12677]
### Issue Type:

Bug Report
### Ansible Version:

1.9.3
### Ansible Configuration:

Dynamic inventory is used. No fact-caching. credentials of windows instances are stored in host file for working with winrm
### Environment:

ansible controlling machine OS: ubuntu 14.04, 
### Summary:

Ec2 instances are created in the playbook. Some configurations need to be changed in the newly created instances. But it skips the newly created hosts in the playbook. But on running the same playbook again, it recognises and executes the task in the newly created EC2 instance.
### Steps to Reproduce

instance is created using ec2 module of ansible and ec2n is the registered variable after executing the module.

```
add-host is also used, 
    - name: adding the MASTER instance to privatemaster group
      add_host: hostname={{ item.public_dns_name }} groupname=privatemaster
      with_items: ec2m.tagged_instances
      when: item.public_dns_name is defined     
```

so after adding the hosts, running the tasks for the newly created hosts by 

```
    - name: update config.json in master instance
      gather_facts: True
      hosts: tag_type_privatemaster
      sudo: True
      tasks:
```

This setup skips host for the first run, but by running the playbook again, it recognises the newly created hosts and starts executing the tasks.
### Expected Results:

starts executing the task at the first run itself.
### Actual Results:

![screen shot 2015-10-08 at 1 16 35 pm](https://cloud.githubusercontent.com/assets/6481030/10357556/601b6fa2-6dbe-11e5-9236-f3b28a13b1d5.png)

**Comment by Pallokala** [comment]
You have to use 'add_host' -module to add those hosts to ansible inventory when creating those. This happens because ec2 -module does not add those by itself.

**Comment by lakshmantgld** [comment]
@Pallokala look at the code above, I have added as you said.

**Comment by Pallokala** [comment]
What comes to my mind:
I have always used add_host with {{ item.public_ip }} . Would that work better?
You could also try pasting somewhere -vvv output produced by the ec2 module. It shows the variable values.

**Comment by lakshmantgld** [comment]
@Pallokala will give a try and let you know. BTW i didn't get the second part, I understand that -vvv gives a verbose result but what is your suggestion. "variable values" ? may be much more detail

**Comment by Pallokala** [comment]
Well it shows which variables are populated by the modules and is helpful when you are not sure how f.ex 'when' is evaluated.

**Comment by lakshmantgld** [comment]
@Pallokala Gave a try with **public_ip** but it doesn`t reflect. It works like a charm when the playbook runs again. I just cant figure out why it cant recognize during the run. Moreover, the playbook is very long and will take take a lot of time to execute. I have used **wait_for** module also to check status of ssh of that instance. This gives me that the port 22 is open.

During the run, I run **ansible --list-hosts group-name** , which gives the instance`s ip. I am clueless about add_host. The **add_host** module gets executed each time but the status is not changed. 

I have also specified **gather_facts** while executing plays on that specific host. 

Have a look at all these and let me know your suggestions @Pallokala

**Comment by lakshmantgld** [comment]
The bug was changing the refresh cache limit and  was using EC2 instances so, **tag_type** must be added to the **groupname** attribute of **add_host**.

**Comment by chrchr** [comment]
I am having a similar issue and I don't understand the resolution here.  Could you post the updated code?

**Comment by chrchr** [comment]
Here's some very similar code in the docs for the ec2 module:

```
# Launch instances, runs some tasks
# and then terminate them

- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: my_keypair
    instance_type: m1.small
    security_group: my_securitygroup
    image: my_ami_id
    region: us-east-1
  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-29e63245
         assign_public_ip: yes
      register: ec2
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name: Configure instance(s)
  hosts: launched
  sudo: True
  gather_facts: True
  roles:
    - my_awesome_role
    - my_awesome_test
```
