### ISSUE TITLE
add_host followed by local_action adds 127.0.0.1 to inventory in following plays

### ISSUE THREAD

**Issue by c0rner** [ansible/ansible#12694]
##### Issue Type:
- Bug Report
##### Ansible Version:

1.9.3 from pypi
##### Ansible Configuration:

Using default configuration
##### Environment:

Mac OS X 10.10.5
##### Summary:

I've actively been using a role to add host to new dynamic groups for a while and it has been working fine until today when I added a `local_ action` to the play. Now all following plays have a new host '127.0.0.1' in their inventory.
##### Steps To Reproduce:

I reduced it to being something with `add_host` and `local_action` and made a small playbook without roles to reproduce the issue.

``` yaml

---
- hosts: all
  become: no
  gather_facts: no

  tasks:
  - add_host: name={{ inventory_hostname }} group="new"
  - local_action: ping
  - ping:

- hosts: all
  become: no
  gather_facts: no

  tasks:
  - ping:
```
##### Expected Results:

Host 127.0.0.1 should not be added to inventory of chained plays.
##### Actual Results:

Host 127.0.0.1 is added to inventory list.

Output from playbook

```
$ ansible-playbook playbooks/bug.yml -i "192.168.1.1,"

PLAY [all] ******************************************************************** 

TASK: [add_host name={{ inventory_hostname }} group="new"] ******************** 
ok: [192.168.1.1]

TASK: [ping] ****************************************************************** 
ok: [192.168.1.1 -> 127.0.0.1]

TASK: [ping ] ***************************************************************** 
ok: [192.168.1.1]

PLAY [all] ******************************************************************** 

TASK: [ping ] ***************************************************************** 
ok: [127.0.0.1]
ok: [192.168.1.1]

PLAY RECAP ******************************************************************** 
192.168.1.1                : ok=4    changed=0    unreachable=0    failed=0   
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   
```
