### ISSUE TITLE
support on_failure hook to survive failure

### ISSUE THREAD

**Issue by mgwilliams** [ansible/ansible#127]
Feature idea:

A failure sometimes leaves a system in an undesirable state -- or a state that will prevent a playbook from re-executing properly. In some cases, semi-predictable failures could be recovered from if further action(s) could be taken on failure.

Playbook example:

``` yaml
- name: install foo-package
  action: apt package=foo state=installed
  notify:
  - foo-installed
  notify_failure:
  - foo-failed
```

The foo-failed handler would be called if apt returned a failure, and could ensure the package is removed and reverse any other actions as needed.
