### ISSUE TITLE
Regression: service module 'enabled' always reports as changed

### ISSUE THREAD

**Issue by randombk** [ansible/ansible#12706]
**Issue Type:** Bug Report

**Ansible Version:** ansible 1.9.3

**Environment:** Debian Jessie x64

**Summary:**

Recurrence of issue #9074. The same steps may be used to reproduce this bug.

**Comment by bcoca** [comment]
First this is reported in the wrong repo, the system module is in ansible/ansible-modules-core

Second, this is duplicate of https://github.com/ansible/ansible-modules-core/issues/915
Which shows this is a known debian bug which is fixed for subsequent releases but not Jessie

**Comment by maxgorovenko** [comment]
Got just installed Fedora 26. Run there task
```
- name: Stop and disable cockpit
  service: name=cockpit.service state=stopped enabled=no
  become: true
  with_items:
   - cockpit.service
   - cockpit.socket
```
Always get 
```
TASK [fedora-base : Stop and disable cockpit] 
*******************************************************************
changed: [test09.srv.local] => (item=cockpit.service)
changed: [test09.srv.local] => (item=cockpit.socket)
```
