### ISSUE TITLE
Support ok_when condition for tasks.

### ISSUE THREAD

**Issue by ypid** [ansible/ansible#12710]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 1.9.3
```

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
Debian

##### SUMMARY

Add a `ok_when` condition to tasks. When it evaluates to True, dont run the task and show OK. When it evaluates to False or it is missing and `when` evaluates to True, run the task.
I know I could run the `Install WordPress plugins` task for each plugin but that is time consuming when you have a big list of plugins as the [`wp`](https://github.com/wp-cli/wp-cli) command seems to have a high startup time.

##### STEPS TO REPRODUCE

[Example play](https://github.com/ypid/debops-wordpress/blob/manage-plugins/roles/wordpress/tasks/manage_plugins.yml) which would benefit form this feature.
``` YAML
- name: Get list of installed WordPress plugins
  command: 'wp plugin list --format=json'
  sudo_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
  changed_when: False
  always_run: True
  register: wordpress_plugin_list_installed_cmd
- name: Convert list of installed WordPress plugins from JSON
  set_fact:
    wordpress_plugin_installed_dict: '{{ wordpress_plugin_list_installed_cmd.stdout|from_json }}'
- name: Set list of installed WordPress plugins
  set_fact:
    wordpress_plugin_installed_list: '{{ wordpress_plugin_installed_dict|map(attribute="name")|list }}'
    wordpress_plugin_active_list: '{{ wordpress_plugin_installed_dict|selectattr("status", "equalto", "active")|map(attribute="name")|list }}'
- name: Install WordPress plugins
  command: 'wp plugin install "{{ item.name }}"'
  sudo_user: '{{ wordpress_user }}'
  args:
    chdir: '{{ wordpress_root }}'
  when: item.name|d() and (item.install|d(True) | bool) and item.name not in wordpress_plugin_installed_list
  ok_when: item.name|d() and (item.install|d(True) | bool) and item.name in wordpress_plugin_installed_list
  with_items: wordpress_plugins
```

##### EXPECTED RESULTS

```
TASK: [wordpress | Install WordPress plugins] *********************************
ok: [jessie.testing] => (item={'name': 'akismet'})
```

##### ACTUAL RESULTS

```
TASK: [wordpress | Install WordPress plugins] *********************************
skipping: [jessie.testing] => (item={'name': 'akismet'})
```
