### ISSUE TITLE
[Replace Module] unsupported parameter for module: regex

### ISSUE THREAD

**Issue by kkirsche** [ansible/ansible#12717]
In my playbook I'm running into an unexpected issues with the replace module. I have the following task:

``` yaml
- name: "Set the name of the Elasticsearch Cluster"
  replace:
    dest: /etc/elasticsearch/elasticsearch.yml
    regex: '^.*cluster\.name.*$'
    replace: example
```

Which is supposed to identify the following line in the `.yml` file:

``` yaml
#cluster.name: elasticsearch
```

When running this though, I get the following output:

``` shell
...
TASK: [elasticsearch-base | Enable the Elasticsearch service] *****************
changed: [10.211.55.29]

TASK: [elasticsearch-base | Start the Elasticsearch service] ******************
changed: [10.211.55.29]

TASK: [elasticsearch-base | Set the name of the Elasticsearch Cluster] ********
failed: [10.211.55.29] => {"failed": true}
msg: unsupported parameter for module: regex

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/exampleUser/elasticsearch.retry

10.211.55.29               : ok=9    changed=4    unreachable=0    failed=1
```

Any idea what I'm missing in the regular expression that is causing this issue?
