### ISSUE TITLE
add_host can't add chroot file paths

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible#12728]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.1

##### SUMMARY
When trying to dynamically set a new host for a chroot (i.e. when using a temporary directory as a mount point) the add_host module errors out claiming that the hostname is invalid.

This is inconsistent with hostname specifications in the inventory file (as documented) which do allow file paths to be given as hostnames. It doesn't appear possible to work around this with templates as hosts line parsing does not appear to have any variables from a play in scope.

``` yaml
    - name: Make temporary directory
      command: mktemp -d
      register: tempdir

    - set_fact: mount_dir={{ tempdir.stdout }}

    - name: Add mount dir to inventory
      add_host: name={{mount_dir}} group=debootstrap
```

```
TASK [set_fact mount_dir={{ tempdir.stdout }}] *********************************
ok: [local] => {"ansible_facts": {"mount_dir": "/tmp/tmp.5SXVlxRO8g"}, "changed": false}

TASK [Add mount dir to inventory] **********************************************
fatal: [local]: FAILED! => {"failed": true, "msg": "ERROR! Invalid inventory hostname: /tmp/tmp.5SXVlxRO8g"}
```

My immediate solution to this has been to catch the normal "parse_address" error and check if a filepath matching the given host exists instead. Possibly though a new action is needed instead?

``` python
        name, port = parse_address(new_name, allow_ranges=False)
        if not name:
            # Check if filepath and exists
            if os.path.exists(new_name):
                name = new_name
            else:
                raise AnsibleError("Invalid inventory hostname: %s" % new_name)
        if port:
            self._task.args['ansible_ssh_port'] = port
```
