### ISSUE TITLE
group_vars and host_vars in inventory_dir not considered

### ISSUE THREAD

**Issue by bitmensch** [ansible/ansible#12742]
Commit e6d3c67 introduced a change which leads to group_vars and host_vars directories inside inventory_dir are no longer being incorporated. Prior to this commit it worked as expected.

``` yaml
# /some/path/to/playbook.yml

---
- hosts: guesthostname
  tasks:
    - name: print world
      command: 'echo -n {{ hello }}'
```

``` yaml
# /some/other/path/to/inventory_dir/static
guesthostname
```

``` yaml
# /some/other/path/to/inventory_dir/group_vars/all
hello: world
```

When executing playbook, it errors with:

```
fatal: [guesthostname]: FAILED! => {"failed": true, "msg": "ERROR! 'hello' is undefined"}
```
