### ISSUE TITLE
dnf and package modules fail to install a previously not-present package with "state=latest"

### ISSUE THREAD

**Issue by wirerydr** [ansible/ansible#12756]
(I am running with ansible devel off GitHub, with a targeted test-box provisioned with Fedora 22 (minimal server).)

The first example on the 'dnf' module doc-page ( http://docs.ansible.com/ansible/dnf_module.html#examples ) is:

``` yaml
- name: install the latest version of Apache
  dnf: name=httpd state=latest
```

However when I run a task that uses either the `package` or `dnf` module with `state=latest` to install a not-present package (in this case rsyslog), the task reports success "nothing to do", and fails to install the package.

If I re-run with the task modified to specify `state=present`, then the task properly succeeds and installs the package.

The following playbook illustrates this, by attempting the following tasks:
Install rsyslog using module "dnf" and "state=latest"
Install rsyslog using module "package" and "state=latest"
Install rsyslog using module "dnf" and "state=present"

Here is the playbook:

``` yaml

---
# This task file installs, configures, and enables/activates the rsyslog daemon

- name: Install rsyslog (not installed, module "dnf", state "latest")
  dnf: name=rsyslog state=latest
  tags: rsyslog

- name: Install rsyslog (not installed, module "package", state "latest")
  package: name=rsyslog state=latest
  tags: rsyslog

- name: Install rsyslog (not installed, module "dnf", state "present")
  dnf: name=rsyslog state=present
  tags: rsyslog
```

Here is the actual output:

```
1 plays in /etc/ansible/testdomain/site.yml

PLAY [Common setup] ************************************************************

TASK [setup] *******************************************************************
ok: [testbox-f22.testdomain.com -> localhost]

TASK [include] *****************************************************************
included: common/tasks/rsyslog__install_configure_activate.yml for testbox-f22.testdomain.com

TASK [Install rsyslog (not installed, module "dnf", state "latest")] ***********
ok: [testbox-f22.testdomain.com -> localhost] => {"changed": false, "msg": "Nothing to do"}

TASK [Install rsyslog (not installed, module "package", state "latest")] *******
ok: [testbox-f22.testdomain.com -> localhost] => {"changed": false, "msg": "Nothing to do"}

TASK [Install rsyslog (not installed, module "dnf", state "present")] **********
changed: [testbox-f22.testdomain.com -> localhost] => {"changed": true, "results": ["Installed: rsyslog-8.8.0-3.fc22.x86_64", "Installed: libestr-0.1.9-4.fc22.x86_64", "Installed: logrotate-3.8.8-1.fc22.x86_64", "Installed: liblogging-stdlog-1.0.4-4.fc22.x86_64", "Installed: json-c-0.12-5.fc22.x86_64"]}

PLAY RECAP *********************************************************************
testbox-f22.testdomain.com : ok=5    changed=1    unreachable=0    failed=0
```

I realize that using "state=present" will probably (certainly?) install whatever version is latest if no version was previously installed, but that would seem to break idempotency if you re-run the playbook a month later.
