### ISSUE TITLE
Tags from playbook execution "infect" included tasks in all the inclusion sites

### ISSUE THREAD

**Issue by adragomir** [ansible/ansible#12793]
I want to split out common functionality to a simple task list, which I can call from some roles (file downloading from a remote server)

```
# roles/common/tasks/get.yml
- debug: msg="download {{file}}"
```

Then, in two different roles, I include the task

```
#  roles/getterone/tasks/main.yml
- debug: msg="getter one"
- set_fact:
    fileone: "one"
- include: ../../../tasks/get.yml
  vars:
    file: "{{fileone}}"
```

```
#  roles/gettertwo/tasks/main.yml
- debug: msg="getter one"
- set_fact:
    filetwo: "two"
- include: ../../../tasks/get.yml
  vars:
    file: "{{filetwo}}"
```

The playbook is 

```
- name: role common
  hosts: 127.0.0.1
  connection: local
  roles:
    - common
  tags:
    - common
- name: role getterone
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
    - getterone
  tags:
    - getterone
- name: role gettertwo
  hosts: 127.0.0.1
  connection: local
  gather_facts: no
  roles:
    - gettertwo
  tags:
    - gettertwo
```

When I run everything, it looks ok, but when I run with a single tag (getterone, or gettertwo), I get

```
PLAY [role common] *************************************************************
TASK [setup] *******************************************************************
PLAY [role getterone] **********************************************************
TASK [getterone : debug msg=getter one] ****************************************
TASK [getterone : set_fact fileone=one] ****************************************
TASK [getterone : include] *****************************************************
TASK [getterone : debug msg=download {{file}}] *********************************
ok: [127.0.0.1 -> localhost] => {
    "changed": false, 
    "msg": "download one"
}
PLAY [role gettertwo] **********************************************************
TASK [gettertwo : include] *****************************************************
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! 'filetwo' is undefined"}
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=1   
```

It looks like it executes ONLY the include in gettertwo (I assume because of the tag), which fails because the rest of the role is not executed. 

Is this expected ? The same thing happens even when I move the get.yml out of a role, to a common tasks list. I think that re-using includeable pieces is a common usecase (i.e. have a server role, and then a helper that injects data to it)

This is on 2.0 (well, devel)
