### ISSUE TITLE
No error when illegal variable is used in loops

### ISSUE THREAD

**Issue by cortopy** [ansible/ansible#12829]
I was trying to debug why one of my variables was not being used by `lineinfile`

If I have

``` yaml
- name: my task
  lineinfile: dest=/path/to/file regexp="{{item.regex}}" line="{{item.line}}"
  with_items:
   - { regex: "old-text", line: "{{new-text}}"}
   - { regex: "old-text2", line: "{{new-text2}}"}
```

Ansible passes the variable as a string in the following format

```
(item={'regex': 'old-text', 'line': u'{#new-text#}'})
```

It was only when I tried the variable on its own (i.e.: not using `with_items`) that I got the reason why the variables weren't being used: hyphens are not allowed in variables. 

Would it be possible to create this error when looping too? Otherwise, it's very difficult to debug

**Comment by jimi-c** [comment]
@cortopy with what version are you seeing this?

**Comment by stajkowski** [comment]
Verified broken in:
ansible 1.9.4-1

Playbook:

```
---
- name: Testing
  hosts: localhost
  connection: local
  tasks:

    - name: Testing
      lineinfile: dest=./test regexp="{{item.regex}}" line="{{item.line}}"
      with_items:
        - { regex: "old-text", line: "{{new-text}}"}
```

Ran With:

```
ansible-playbook -i ./inventory/localhost test3.yaml -vv -e "new-text=test"
```

Output:

```
PLAY [Testing] ****************************************************************

GATHERING FACTS ***************************************************************
<localhost> REMOTE_MODULE setup
ok: [localhost]

TASK: [Testing] ***************************************************************
<localhost> REMOTE_MODULE lineinfile dest=./test regexp="old-text" line="{#new-text#}"
changed: [localhost] => (item={'regex': 'old-text', 'line': u'{#new-text#}'}) => {"backup": "", "changed": true, "item": {"line": "{#new-text#}", "regex": "old-text"}, "msg": "line added"}

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

Tested on:
HEAD

Playbook:

```
---
- name: Testing
  hosts: localhost
  connection: local
  tasks:

    - name: Testing
      lineinfile: dest=./test regexp="{{item.regex}}" line="{{item.line}}"
      with_items:
        - { regex: "old-text", line: "{{new-text}}"}
```

Ran With:

```
ansible-playbook -i ./inventory/localhost test3.yaml -vv -e "new-text=test"
```

Output:

```
PLAY [Testing] *****************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Testing] *****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! ERROR! Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like '-'."}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

Appears this is fixed in later versions.
