### ISSUE TITLE
'group_by' does not work with remote hosts on Ansible devel

### ISSUE THREAD

**Issue by drybjed** [ansible/ansible#12825]
##### Issue Type:

Bug Report
##### Ansible Version:

Ansible devel
##### Ansible Configuration:

Default `ansible.cfg`
##### Environment:

Debian, Ubuntu
##### Summary:

`group_by` module doesn't work with remote hosts in inventory. Works on Ansible 1.9.
##### Steps To Reproduce:

Example inventory:

```
localhost ansible_connection=local
<some remote host>
```

Example playbook:

```
- hosts: all
  gather_facts: False
  serial: 1

  tasks:

    - name: Create host groups
      group_by:
        key: '{{ "tag_" + item }}'
      with_items: [ 'one', 'two' ]
      changed_when: False
```
##### Expected Results:

```
PLAY [all] ******************************************************************** 

TASK: [Create host groups] **************************************************** 
ok: [localhost] => (item=one)
ok: [localhost] => (item=two)

TASK: [Create host groups] **************************************************** 
ok: [remote_host] => (item=one)
ok: [remote_host] => (item=two)
```
##### Actual Results:

```
PLAY ***************************************************************************

TASK [Create host groups] ******************************************************
ERROR! 'item' is undefined
```
