### ISSUE TITLE
AWS IAM module - China Region - The security token included in the request is invalid.

### ISSUE THREAD

**Issue by Etherdaemon** [ansible/ansible#12831]
**Issue Type:**

Bug Report

**Ansible Version**
ansible --version
ansible 2.0.0 (detached HEAD 5ae74f7d38) last updated 2015/10/18 19:39:15 (GMT +1000)

Running Ansible from source - v2.0.0-0.3.beta1

*\* Ansible Config Changes:**
inventory      = china_aws_inventory/ec2.py
ansible_python_interpreter = /usr/local/bin/python

**Environment:**
OSX 10.10.5
Running Ansible from source - v2.0.0-0.3.beta1
Running boto (2.38.0) and boto3 (1.1.4)
Python 2.7.10

**Summary:**

Utilising the new Amazon IAM module to create a new role and attach a new policy to a new role results in a security token error.

**Steps To Reproduce:**

```
- name: Create a new IAM role
    iam:
    region: cn-north-1
    aws_access_key: <access>
    aws_secret_key: <secret>
    iam_type: role
    name: test_ec2_role
    path: '/'
    state: present
```

**Expected Results:**

New role created in IAM.

**Actual Results:**

_fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The security token included in the request is invalid."}_
