### ISSUE TITLE
Subnet ID not found, even though it exists

### ISSUE THREAD

**Issue by cdelpinogeo** [ansible/ansible#12905]
I am using Ansible to deploy an autoscale group on aws. I have the following defined to create the asg:

```
- name: Provision autoscaling group
  ec2_asg:
    name: asgtest
    region: "{{ aws_region }}"
    load_balancers: [ 'elbtest' ]
    vpc_zone_identifier:
      - "{{ subnet_maps[ subnet1 ] }}"
      - "{{ subnet_maps[ subnet2 ] }}"
      - "{{ subnet_maps[ subnet3 ] }}"
      - "{{ subnet_maps[ subnet4 ] }}"
    launch_config_name: 'lctest'
    min_size: 2
    max_size: 8
   desired_capacity: 2
   state: present
```

I get the following error when running the playbook:

```
TASK: [aws | Provision autoscaling group] ************************************* 
failed: [127.0.0.1] => {"failed": true}
msg: BotoServerError: 400 Bad Request
<ErrorResponse xmlns="http://autoscaling.amazonaws.com/doc/2011-01-01/">
  <Error>
    <Type>Sender</Type>
    <Code>ValidationError</Code>
    <Message>The subnet ID '['subnet-#########'' does not exist</Message>
  </Error>
  <RequestId>############################</RequestId>
</ErrorResponse>


FATAL: all hosts have already failed -- aborting
```

I've removed original values and placed #'s in there place.

Not sure what I am doing wrong. I've confirmed that the 4 subnets do exist via the aws console. Version of AnsiblIe am using:

```
1.9.4-1ppa~vivid
```

I can provide more info if required. Thanks in advance!

**Comment by cdelpinogeo** [comment]
Update on this:

I changed the asg config to the following:

```
- name: Provision autoscaling group
  ec2_asg:
    name: asgtest
    region: "{{ aws_region }}"
    load_balancers: [ 'elbtest' ]
    vpc_zone_identifier: 'subnet-#########'
    launch_config_name: 'lctest'
    min_size: 2
    max_size: 8
    desired_capacity: 2
    state: present
```

this created the asg, with only one subnet though. I've also tried setting the vpc_zone_identifier to:

```
vpc_zone_identifier: [ 'subnet-######','subnet-######','subnet-######','subnet-######' ]
```

same result.
