### ISSUE TITLE
pipefail for shells

### ISSUE THREAD

**Issue by nschloe** [ansible/ansible#12903]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
shell module

##### ANSIBLE VERSION
N/A

##### SUMMARY
Recently, I experienced a nasty issue that was caused by the following shell pipe:

``` yaml
- name: get remote branches
  shell: git ls-remote -h git@bitbucket.org:orga/repo.git | sed 's_.*refs/heads/__g'
  register: branches_remote
```

The git command fails, but the return code of the entire pipe is 0. This is default bash/sh behavior.

To fix this, in bash, one can `set -o pipefail` (in bash). Is it possible to do that in ansible, preferably globally for all my shell commands?
