### ISSUE TITLE
using linuxbrew with ansible

### ISSUE THREAD

**Issue by lvnilesh** [ansible/ansible#12939]
I am trying to use ansible with https://github.com/Homebrew/linuxbrew

See this https://github.com/ansible/ansible/blob/6292520c45905a01da4de9aaf0c5ce30bbd195a0/lib/ansible/module_utils/facts.py#L129 where homebrew path is set to be `/usr/local/bin/brew` which works for mac but not for `linuxbrew` where the path is `$HOME/.linuxbrew` as indicated by `$(brew --prefix)/bin`

How do I override this when I want to use ansible with linuxbrew?

**Comment by lvnilesh** [comment]
This seems to work. Is this recommended or is there a better practice?

```
---

- name: install python using brew
  hosts: vagrant
  vars:
    home: /home/vagrant
  tasks:
    - homebrew: update_homebrew=yes upgrade_all=yes path={{ home }}/.linuxbrew/bin
    - homebrew: name=python state=present path={{ home }}/.linuxbrew/bin
```
