### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by adamryczkowski** [ansible/ansible#12947]
## Ansible version

`$ansible --version`
`ansible 1.9.4`
`configured module search path = None`
## Ansible Configuration:

Plain installation from repositories
## Environment:

Ubuntu 14.04 64 bit
## Summary:

Module `set_fact` ignores meta parameter `ignore_errors`.
## Steps to reproduce:

Run the following play:

``` yaml
- name: my playbook
  hosts: localhost
  gather_facts: False
  tasks:
    - set_fact: myvar={{ non_existant_value}}
      ignore_errors: yes
    - pause: 
```
## Expected Results:

Execution of the `pause` task. Either undefined variable `myvar` or `myvar` set to some predefined value indicating error.
## Actual Results:

Failed play.

---

This has practical implications for me in the following play, where I want to get a value through non-cannonical  [augeas module](https://github.com/paluh/ansible-augeas) :

``` yaml
    - name: Get internalif, if set "auto" 
      augeas: >
        commands='transform Shellvars incl /etc/default/lxc-net
                  match /files/etc/default/lxc-net/LXC_BRIDGE'
      when: 'internalif == "auto"'
      register: xxx
    #The following task fails when the variable was not present:
    - set_fact: internalif={{ xxx.result[1][1][0].value}}
      ignore_errors: yes
    - set_fact: internalif="lxcbr0"
      when: 'internalif == "auto"'
```
