### ISSUE TITLE
Tags with Includes are broken in v2

### ISSUE THREAD

**Issue by evanccnyc** [ansible/ansible#12940]
# Ansible Version:

```
ansible 2.0.0 (devel e3e2db1119) last updated 2015/10/27 18:48:47 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 06f301b05b) last updated 2015/10/26 11:46:28 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 405c3cb2c7) last updated 2015/10/26 11:46:30 (GMT -400)
  config file = /Users/ecarter/.ansible.cfg
  configured module search path = None
```
# Playbook

```
- name: reproduce tag problem
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
   - include: include.yml tags=test
```

include.yml

```
- name: hello world
  command: echo "Hello World"
```
# Expected Results:

If ansible-playbook is run with -t test, it should run the include playbook.
# Actual Results:

Skipped the playbook

```
ansible-playbook -i hosts tagtest.yml --tags=test                                  

PLAY [reproduce tag problem] **************************************************

TASK [include tags=test] *******************************************************
included: /Users/xxx/work/include.yml for 127.0.0.1

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0
```
