### ISSUE TITLE
Jinja2 default filter doesn't allow for dictionaries

### ISSUE THREAD

**Issue by adamryczkowski** [ansible/ansible#12949]
## Ansible version

`$ansible --version`
`ansible 1.9.4`
`configured module search path = None`
## Ansible Configuration:

Plain installation from repositories
## Environment:

Ubuntu 14.04 64 bit
## Summary:

Module `set_fact` ignores meta parameter `ignore_errors`.
## Steps to reproduce:

Run the following play:

``` yaml
- name: my playbook
  hosts: localhost
  gather_facts: False
  tasks:
    - set_fact: myvar2={{ myvar|default({'key': 'value'}) }}
    - pause: 
```
## Expected Results:

Assignment the 'key' -> 'value' dictionary to the `myvar2`.
## Actual Results:

Failed play. Here is the error message:

```
ERROR: Syntax Error while loading YAML script, lxc.yml
Note: The error may actually appear before this position: line 12, column 47

  tasks:
    - set_fact: myvar2="{{ myvar|default('key': 'value') }}"
                                              ^
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```
