### ISSUE TITLE
Bug Report: debug + with_items is not working properly

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#12952]
**Issue Type:**

Bad var substitution using with_ statement and debug.

**Ansible version:**

```
ansible 2.0.0 (devel 92dd563a75) last updated 2015/10/28 20:05:08 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 211196bdf6) last updated 2015/10/26 09:59:00 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 5d4474a2b2) last updated 2015/10/26 09:59:00 (GMT +200)
```

**Ansible Configuration:**

Nothing special

**Environment:**

Linux Mint 17.2

**Summary:**

Debug + with_items does not work properly

**Steps To Reproduce:**

Use the following playbook:

``` yaml

---
- name: "Lookup test"
  hosts: "localhost"
  connection: "local"
  vars:
    var1: "1"
    var2: "2"
  tasks:
    - debug: var={{item}}
      with_items: [ 'var1', 'var2' ]
    - debug: var=var1
    - debug: var=var2
    - debug: msg={{item}}
      with_items: [ 'var1', 'var2' ]
```

**Expected Results:**

With Ansible 1.9, we get the following result:

``` yaml
TASK: [debug var={{item}}] **************************************************** 
ok: [localhost] => (item=var1) => {
    "item": "var1", 
    "var": {
        "var1": "1"
    }
}
ok: [localhost] => (item=var2) => {
    "item": "var2", 
    "var": {
        "var2": "2"
    }
}
```

**Actual Results:**

With the last version of Ansible, I get the following output:

``` yaml
TASK [debug var={{item}}] ******************************************************
ok: [localhost] => (item=var1) => {
    "item": "var1", 
    "{{item}}": "var1"
}
ok: [localhost] => (item=var2) => {
    "item": "var2", 
    "msg": "here we are"
}
```

**Comment by Yannig** [comment]
I wrote the following patch in order to try to resolve this issue:

``` diff
diff --git a/lib/ansible/executor/task_executor.py b/lib/ansible/executor/task_executor.py
index e8a785a..0d5ca69 100644
--- a/lib/ansible/executor/task_executor.py
+++ b/lib/ansible/executor/task_executor.py
@@ -296,12 +296,6 @@ class TaskExecutor:
             return dict(include=include_file, include_variables=include_variables)

         # Now we do final validation on the task, which sets all fields to their final values.
-        # In the case of debug tasks, we save any 'var' params and restore them after validating
-        # so that variables are not replaced too early.
-        prev_var = None
-        if self._task.action == 'debug' and 'var' in self._task.args:
-            prev_var = self._task.args.pop('var')
-
         self._task.post_validate(templar=templar)
         if '_variable_params' in self._task.args:
             variable_params = self._task.args.pop('_variable_params')
@@ -310,9 +304,6 @@ class TaskExecutor:
                 variable_params.update(self._task.args)
                 self._task.args = variable_params

-        if prev_var is not None:
-            self._task.args['var'] = prev_var
-
         # get the connection and the handler for this execution
         self._connection = self._get_connection(variables=variables, templar=templar)
         self._connection.set_host_overrides(host=self._host)

```

This patch result in the following output:

``` yaml
TASK [debug var={{item}}] ******************************************************
ok: [localhost] => (item=var1) => {
    "item": "var1", 
    "var1": "1"
}
ok: [localhost] => (item=var2) => {
    "item": "var2", 
    "var2": "2"
}
```

The output is now a little bit different but the result is correct.
