### ISSUE TITLE
[v2] broke my custom module tests

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#12980]
**Ansible Version**: 2.0.0
**Summary**:

I've a [custom module to manipulate .ini files](https://gist.github.com/mgedmin/aa629d5a4c5fe143a2ed).  I wrote some tests for it.  The first test checks that the module fails when some arguments are missing.  [This test](https://gist.github.com/mgedmin/aa629d5a4c5fe143a2ed) looks like this:

``` yaml
   - ini_file_ex: dest=/tmp/inifile
     register: out
     failed_when: not out.failed
```

Essentially, I want to invert the normal failure status.

This does not work with Ansible 2.0.0:

```
$ ansible-playbook test-ini-file-ex.yml

PLAY ***************************************************************************

TASK [command] *****************************************************************
changed: [localhost]

TASK [ini_file_ex dest=/tmp/inifile] *******************************************
/home/mg/src/deployments/provisioning/action_plugins/ini_file_ex.py:3: RuntimeWarning: Parent module 'ansible.plugins.action' not found while handling absolute import
  from ansible.plugins.action.normal import ActionModule
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "failed_when_result": true, "msg": "section or option required when state=present"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=1   
```

I've bisected the failure to commit 60c139e482c2084fb631c1cc7b606c8162d068fa.

**Comment by mgedmin** [comment]
Small test.yml that reproduces this:

``` yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - copy:
      register: out
      failed_when: not out.failed
```
