### ISSUE TITLE
Performance regression with Ansible v2 using include + big hash map

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#12997]
##### Issue Type:

This is a bug report about speed regression between Ansible 1.9.4 and current devel version when combining big hash map and include statement.
##### Ansible Version:

```
ansible 2.0.0 (devel f528ad1848) last updated 2015/11/01 09:23:49 (GMT +200)
  lib/ansible/modules/core: (detached HEAD a3a7cdb9aa) last updated 2015/11/01 10:03:19 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD b1db0e893c) last updated 2015/11/01 10:03:19 (GMT +200)
```
##### Ansible Configuration:

Nothing special. The playbook work with  local connection.
##### Environment:

N/A
##### Summary:

I have speed regressions against various playbooks. With Ansible 1.9.4, this playbooks was completed in about 3 to 5s. With last version of Ansible, they take 7 more times.

All my tests use a local virtual machine.
##### Steps To Reproduce:

You can retrieve playbook that reproduce this issue at the following location: https://github.com/Yannig/ansible-issue-low-speed/

This repository have 2 playbooks: one using a big hash map (issue-vars.yml) but not the other (no-vars-mapping.yml).
##### Expected Results:

Actually, using ansible 1.9.4, the playbook take about 3 seconds:

```
time ansible-playbook issue-vars/issue-vars.yml 
```

``` yaml
PLAY [Test] ******************************************************************* 

TASK: [do-include | debug var=application_name] ******************************* 
ok: [localhost] => {
    "var": {
        "application_name": "application1"
    }
}

TASK: [do-include | Répertoire des roles] ************************************ 
ok: [localhost] => (item={'key': 'field1', 'value': {'field': u'NA', 'name': 'field1'}})

TASK: [do-include | template src=test.j2 dest="/tmp/{{item.value.field}}/1-{{item.value.name}}.txt"] *** 
ok: [localhost] => (item={'key': 'field1', 'value': {'field': u'NA', 'name': 'field1'}})

TASK: [do-include | shell export FIELD={{item.item.value.field}} ; echo "$FIELD" ; cat /tmp/{{item.item.value.field}}/{{item.item.value.name}}.txt
] *** 
[...]
TASK: [do-include | shell export FIELD={{item.item.value.field}} ; echo "$FIELD" ; cat /tmp/{{item.item.value.field}}/{{item.item.value.name}}.txt
] *** 
skipping: [localhost] => (item=oracle_element_to_update.results)

PLAY RECAP ******************************************************************** 
localhost                  : ok=10   changed=0    unreachable=0    failed=0   
```

```
real    0m2.760s
user    0m2.052s
sys     0m0.121s
```
##### Actual Results:

Ansible v2 is about 7 times slower:

```
time ansible-playbook issue-vars/issue-vars.yml 
```

``` yaml
PLAY [Test] ********************************************************************

TASK [do-include : debug var=application_name] *********************************
ok: [localhost] => {
    "application_name": "application1",                                                                                                                                                                                                      
    "changed": false                                                                                                                                                                                                                         
}                                                                                                                                                                                                                                            

TASK [do-include : Répertoire des roles] ***************************************
ok: [localhost] => (item={'value': {u'field': u'NA', u'name': u'field1'}, 'key': u'field1'})

TASK [do-include : include] ****************************************************
included: /home/yannig/dev/yannig/ansible-issue-low-speed/issue-vars/roles/do-include/tasks/include1.yml for localhost

TASK [do-include : template dest=/tmp/{{item.value.field}}/1-{{item.value.name}}.txt src=test.j2] ***
ok: [localhost] => (item={'value': {u'field': u'NA', u'name': u'field1'}, 'key': u'field1'})

TASK [do-include : include] ****************************************************
included: /home/yannig/dev/yannig/ansible-issue-low-speed/issue-vars/roles/do-include/tasks/include2.yml for localhost
[...]
TASK [do-include : command] ****************************************************
skipping: [localhost] => (item=oracle_element_to_update.results) 

PLAY RECAP *********************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0   

```

```
real    0m20.879s
user    0m17.448s
sys     0m0.317s
```

If I take the other playbook **no-vars-mapping.yml** (which simply does not call vars-mapper role), Ansible v2 takes 2.2 seconds (vs 0.5 second for Ansible 1.9.4):

```
real    0m2.263s
user    0m1.318s
sys     0m0.178s
```
