### ISSUE TITLE
v2 regression: delegate_to in a loop doesn't show ``[delegater -> delegatee]`` in output

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#13014]
With current ansible devel, the following play:

```
- hosts: localhost
  tasks:
    - command: echo "{{inventory_hostname}}"
      delegate_to: "foo{{item}}"
      with_items: [1,2,3]
```

displays the following output:

```
TASK [command] *****************************************************************
changed: [localhost] => (item=1)
changed: [localhost] => (item=2)
changed: [localhost] => (item=3)
```

whereas with Ansible 1.9, it displays this:

```
TASK: [command echo "{{ inventory_hostname }}"] ******************************* 
changed: [localhost -> foo1] => (item=1)
changed: [localhost -> foo2] => (item=2)
changed: [localhost -> foo3] => (item=3)
```

Because of the incorrect output, I can't be sure if the delegation is actually working as intended/as it did before (because the hosts I'm delegating to all have `ansible_connection=local`).
