### ISSUE TITLE
Getting a with_dict error when reading through dict:

### ISSUE THREAD

**Issue by mirzawaqasahmed** [ansible/ansible#13045]
Hi everyone,
This may not be an issue on the module but certainly for me and I hope I can get an answer from here.
**_I am using CumulusNetworks Modules from here https://github.com/CumulusNetworks/cumulus-linux-ansible-modules/blob/master/library/cl_interface.py**_
I am trying to run a play book with variables defined in group_vars folder. however when I run the playbook Ansible throws an error saying "fatal: [spine111] => with_dict expects a dict".
What am I doing wrong?

This is the play book:

```

---
# This file will take care of building peerlink.4094 on peer1 hosts only
- hosts: peer1
  gather_facts: no
  roles:
    - clag-peer1
```

This is tasks file in the roles/peer1

```
 # tasks file for clag-peer1
    - name: peerlink.4094 configuration for peer1 only
      cl_interface:
        name: "{{ item.key }}"
        ipv4: "{{ item.value.ipv4 }}"
        alias_name: "{{ item.value.alias_name }}"
        clagd_enable: "{{ item.value.clagd_enable }}"
        clagd_peer_ip: "{{ item.value.clagd_peer_ip }}"
        clagd_priority: "{{ item.value.clagd_priority }}"
        clagd_sys_mac: "{{ item.value.clagd_sys_mac }}"
        clagd_args: "{{ item.value.clagd_args }}"
        applyconfig: 'yes'
      with_dict: cl_interfaces[inventory_hostname]
      notify: reload networking
      tags: clagd
```

Variable file named peer1 in group_vars has the following contents:

```
cl_interface:
  - spine111:
        peerlink.4094:
            alias_name: "Clag_PeerLink"
            ipv4: "169.254.1.1/30"
            clagd_enable: "yes"
            clagd_peer_ip: "169.254.1.2"
            clagd_priority: "4096"
            clagd_args: "-vm"
            clagd_sys_mac: "00:00:00:00:00:01"
```
