### ISSUE TITLE
ansible executing every other task.

### ISSUE THREAD

**Issue by jgabriels** [ansible/ansible#13063]
I'm running 
ansible 2.0.0 (devel 5b84bd6b5d) last updated 2015/11/06 08:18:12 (GMT -500)
lib/ansible/modules/core: (detached HEAD 35707bcb3c) last updated 2015/11/06 08:18:15 (GMT -500)
lib/ansible/modules/extras: (detached HEAD f281eb2b30) last updated 2015/11/06 08:18:17 (GMT -500)

when I execute tasks, it appears to be skipping every other task.
I get the following output:

TASK [baseserver-role : apt state=installed pkg=lynx] ***

TASK [baseserver-role : apt state=installed pkg=links] ***
changed: [10.0.0.27]

TASK [baseserver-role : apt state=installed pkg=elinks] ***

TASK [baseserver-role : apt state=installed pkg=curl] ***
changed: [10.0.0.27]

TASK [baseserver-role : apt state=installed pkg=wget] ***

TASK [baseserver-role : apt state=installed pkg=mysql-client] ***
ok: [10.0.0.27]

and when I go to the server, only every other package has been installed.

**Comment by jimi-c** [comment]
Could you please share the playbook/roles you're running here?

**Comment by jgabriels** [comment]
Ok, this is kindof amusing.   Below is a simplified playbook.
The 1st host testserver1 works fine.
The 2nd host testserver2 executes every other task.
The 3rd host testserver3 executes every 3rd task.
The 4th host testserver4 executes every 4th task.

```
- hosts: testserver1
  remote_user: root
  gather_facts: false
  tasks:
    - apt: pkg=lynx state=installed
    - apt: pkg=links state=installed
    - apt: pkg=elinks state=installed
    - apt: pkg=curl state=installed
    - apt: pkg=wget state=installed
    - apt: pkg=lynx state=installed
    - apt: pkg=links state=installed
    - apt: pkg=elinks state=installed
    - apt: pkg=curl state=installed
    - apt: pkg=wget state=installed

- hosts: testserver2
  remote_user: root
  gather_facts: false
  tasks:
    - apt: pkg=lynx state=installed
    - apt: pkg=links state=installed
    - apt: pkg=elinks state=installed
    - apt: pkg=curl state=installed
    - apt: pkg=wget state=installed
    - apt: pkg=lynx state=installed
    - apt: pkg=links state=installed
    - apt: pkg=elinks state=installed
    - apt: pkg=curl state=installed
    - apt: pkg=wget state=installed

- hosts: testserver3
  remote_user: root
  gather_facts: false
  tasks:
    - apt: pkg=lynx state=installed
    - apt: pkg=links state=installed
    - apt: pkg=elinks state=installed
    - apt: pkg=curl state=installed
    - apt: pkg=wget state=installed
    - apt: pkg=lynx state=installed
    - apt: pkg=links state=installed
    - apt: pkg=elinks state=installed
    - apt: pkg=curl state=installed
    - apt: pkg=wget state=installed

- hosts: testserver4
  remote_user: root
  gather_facts: false
  tasks:
    - apt: pkg=lynx state=installed
    - apt: pkg=links state=installed
    - apt: pkg=elinks state=installed
    - apt: pkg=curl state=installed
    - apt: pkg=wget state=installed
    - apt: pkg=lynx state=installed
    - apt: pkg=links state=installed
    - apt: pkg=elinks state=installed
    - apt: pkg=curl state=installed
    - apt: pkg=wget state=installed
```
