### ISSUE TITLE
Ansible Mount module fails because -o remount is an invalid option for mount.nfs

### ISSUE THREAD

**Issue by Rtzq0** [ansible/ansible#13070]
This ticket is opened because #8377 is closed.

This issue is still present as recently as 1.9.4 (cannot test on newer versions).

It looks as though the mount module calls -o remount blindly instead of calling umount followed by mount.

Example:

```
- name: mount a mount
  mount:
    state: "mounted"
    fstype: "nfs"
    name: "/mnt/foo"
    src: "fizz:/buzz"
    opts: "rsize=8192,wsize=8192,timeo=14,intr,nosuid"
```

Will happily mount your mount, but when you run with

```
- name: mount a mount
  mount:
    state: "mounted"
    fstype: "nfs"
    name: "/mnt/foo"
    src: "fizz:/buzz"
    opts: "timeo=14,intr,nosuid"
```

It will fail with an unsupported mount option error, because remount is not a supported mount option for moujnt.nfs
