### ISSUE TITLE
[v2] apt with_items just repeats the 1st item

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#13088]
**Ansible Version** 

```
ansible 2.0.0 (devel da4b4a2a33) last updated 2015/11/09 08:53:14 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 750aa16a06) last updated 2015/11/09 08:53:39 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 62f52d702a) last updated 2015/11/09 08:53:39 (GMT +300)
```

**Summary**

Given a task like this:

``` yaml
    - apt: name="{{ item }}" state=present
      with_items: "{{ packages }}"
```

Ansible v1 processes it correctly, but ansible v2 installs the 1st package N times.

**Steps to Reproduce**
- create a `test.yml`:

``` yaml

---
- hosts: localhost
  gather_facts: no
  vars:
    packages:
      - build-essential
      - python-dev
      - python-virtualenv
      - gettext
  tasks:
    - apt: name="{{ item }}" state=present
      with_items: "{{ packages }}"
```
- run `ansible-playbook test.yml -C`

**Expected Behavior**

```
PLAY [localhost] ************************************************************** 

TASK: [apt name="{{ item }}" state=present] *********************************** 
ok: [localhost] => (item=build-essential,python-dev,python-virtualenv,gettext)

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Actual Behavior**

```
PLAY ***************************************************************************

TASK [apt state=present name={{ item }}] ***************************************
ok: [localhost] => (item=[u'build-essential', u'build-essential', u'build-essential', u'build-essential'])

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Other Comments**

The bug goes away if I use a different module (such as `command: echo {{ item }}`) instead of `apt`.
