### ISSUE TITLE
docker: unsupported parameter for module: docker_api_version with ansible ansible-2.0.0-0.4.beta2

### ISSUE THREAD

**Issue by gangefors** [ansible/ansible#13109]
I'm on Debian Jessie using a virtualenv with the following modules.

```
ansible==1.9.4
ecdsa==0.13
Jinja2==2.8
MarkupSafe==0.23
paramiko==1.16.0
pycrypto==2.6.1
PyYAML==3.11
```

I have a playbook that looks like this:

```
- hosts: webservers
  tasks:
  - name: Create local config file
    template:
      src: "templates/config.py.j2"
      dest: "{{ playbook_dir }}/../flask/config.py"

  - name: Ensure that our application container is running
    docker:
      name: "myapp"
      image: "turrican"
      state: "running"
      links:
      - "mongodb"
      ports:
      - "5000:80"
      volumes:
      - "{{ playbook_dir }}/../flask:/usr/src/app"
```

Running the playbook using ansible v1.9.4 I get:

```
TASK: [Create local config file] ********************************************** 
fatal: [localhost] => Failed to template %m{%S%n%s}%!?# : template error while templating string: Encountered unknown tag 'S'.
```

This is related to https://github.com/ansible/ansible/issues/11366 and it's fixed in the development release.

So I install ansible-2.0.0-0.4.beta2 and get the following output.

```
TASK [Ensure that our application container is running] ************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\r\n  File \"/home/stefanga/.ansible/tmp/ansible-tmp-1447148282.42-57268136308077/docker\", line 2691, in <module>\r\n    main()\r\n  File \"/home/stefanga/.ansible/tmp/ansible-tmp-1447148282.42-57268136308077/docker\", line 724, in main\r\n    containers = manager.create_containers(1)\r\n  File \"/home/stefanga/.ansible/tmp/ansible-tmp-1447148282.42-57268136308077/docker\", line 597, in create_containers\r\n    containers = do_create(count, params)\r\n  File \"/home/stefanga/.ansible/tmp/ansible-tmp-1447148282.42-57268136308077/docker\", line 585, in do_create\r\n    result = self.client.create_container(**params)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/container.py\", line 114, in create_container\r\n    volume_driver\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/container.py\", line 119, in create_container_config\r\n    return utils.create_container_config(self._version, *args, **kwargs)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/utils/utils.py\", line 711, in create_container_config\r\n    'mem_limit has been moved to host_config in API version 1.19'\r\ndocker.errors.InvalidVersion: mem_limit has been moved to host_config in API version 1.19\r\n", "parsed": false}
```

This is related to https://github.com/ansible/ansible-modules-core/issues/1707. There I find a comment https://github.com/ansible/ansible-modules-core/issues/1707#issuecomment-130465890 that recommends using "docker_api_version" to get around this issue.

But when I add that to my playbook I get:

```
TASK [Ensure that our application container is running] ************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: docker_api_version"}
```

I don't know what to do to get this to work.
