### ISSUE TITLE
Variables not interpolated in environment when using block

### ISSUE THREAD

**Issue by aocole** [ansible/ansible#13123]
##### Ansible Version:

```
ansible 2.0.0 (detached HEAD 76ae577519) last updated 2015/11/10 23:38:28 (GMT +000)
  lib/ansible/modules/core: (detached HEAD fde6ee15d6) last updated 2015/11/10 20:05:36 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 6cc43bbd56) last updated 2015/11/10 20:06:02 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No changes
##### Environment:

Ubuntu 14.04.3
##### Summary:

When using an `environment:` section in a block, variables are not interpolated. This broke with commit 76ae5775192b03f390df0fd04b14b9d79324a9c5
##### Steps To Reproduce:

``` yaml

---
- name: Demonstrate variable interpolation in environment
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    foo: bar

  tasks:
  - block:
    - name: Print variable
      shell: "echo $baz"
      register: result
    - debug: var=result.stdout
    environment:
      baz: "{{ foo }}"
```
##### Expected Results:

```
ok: [localhost] => {
    "changed": false,
    "result.stdout": "bar"
}
```
##### Actual Results:

```
ok: [localhost] => {
    "changed": false,
    "result.stdout": "{# foo #}"
}
```
