### ISSUE TITLE
Run task depending on host has changed

### ISSUE THREAD

**Issue by garyrutland** [ansible/ansible#13151]
Hi,

Sorry if this is the wrong place to ask this but I'm not sure where else and this seems like the most likely place that someone might be able to answer my question.

Using AWS to update our Bamboo box if and when a new capability is needed for whatever reason, need to then create an AMI based on these changes so that they aren't lost.
I can create an AMI without issue, but only really want it to be created if something is actually changed on any of the hosts.

This is an example of what I would like to achieve:

```

---

- name: update bamboo nodes
  hosts: security_group_bamboo
  roles:
    - common
    ...

- name: create ami
  connection: local
  hosts: local
  gather_facts: false
  tasks:
    - ec2_ami:
        ...
      when: "something has changed in above roles"
```

Is this even possible?

Thanks,
Gary
