### ISSUE TITLE
File mode gives unpredictable results

### ISSUE THREAD

**Issue by nydr** [ansible/ansible#13159]
When using the yaml syntax for modules "mode" gives weird results unless they are quoted, this opens up for unpredictable errors so it should either give a warning or work the same way no matter if it's quoted or not.

```
- file:
    path: /tmp/t1
    state: directory
    mode: 2775
gives unexpected result:
d-ws-w-rwt   2 root root 4.0K Nov 13 14:59 t1
```

```
- file: > 
    path=/tmp/t2
    state=directory
    mode=2775
gives result:
drwxrwsr-x   2 root root 4.0K Nov 13 14:59 t2
```

```
- file:
    path: /tmp/t3
    state: directory
    mode: "2775"
gives result:
drwxrwsr-x   2 root root 4.0K Nov 13 14:59 t3
```

Tested on ansible 1.9.4 and 2.0.0 (devel b2a9111b22)

**Comment by sivel** [comment]
This is do to how python and pyyaml handle octal and decimal modes.

The equivalents are:

#### Proper Octal

```
mode: 02775
```

#### Octal represented as a string

```
mode: "2775"
```

#### Mode as a decimal

```
mode: 1517
```

The reason that `mode=2775` produces the same results as `mode: "2775"` is due to the fact sure that `key=value` ansible uses shlex to parse the values, effectively casting all values to strings.

**Comment by jimi-c** [comment]
Per @sivel's comment above, we're going to go ahead and close this.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by aleemb** [comment]
@jimi-c 

This tripped me up too and it's sure to trip up others as well.

You think it would be more user-friendly to allow `mode: 2775` to work as expected?

**Comment by morgajel** [comment]
I concur- this is definitely a UI bug and probably shouldn't have been closed.

**Comment by eburgueno** [comment]
I just hit this issue. Directories were being created with the wrong permissions:

```
- name: Create application directories
  file:
    path: '{{ item }}'
    owner: app
    group: app
    mode: 2775
    state: directory
  with_items:
    - "/var/www/html/app"

# pwd
/var/www/html/
# ls -l
total 4
d-ws-w-rwt. 4 app app 4096 Apr 27 14:52 app
```

I am following the examples in the [official documentation](http://docs.ansible.com/ansible/file_module.html), so either this bug needs fixing or the documentation should be updated:

```
# change file ownership, group and mode. When specifying mode using octal numbers, first digit should always be 0.
- file:
    path: /etc/foo.conf
    owner: foo
    group: foo
    mode: 0644
- file:
    src: /file/to/link/to
    dest: /path/to/symlink
    owner: foo
    group: foo
    state: link
- file:
    src: '/tmp/{{ item.src }}'
    dest: '{{ item.dest }}'
    state: link
  with_items:
    - { src: 'x', dest: 'y' }
    - { src: 'z', dest: 'k' }
(...)
# create a directory if it doesn't exist
- file:
    path: /etc/some_directory
    state: directory
    mode: 0755
```
