### ISSUE TITLE
to_json does not seem to handle mixed types properly

### ISSUE THREAD

**Issue by richard-hulm** [ansible/ansible#13180]
Ansible 2.0.0b4 (worked OK on 1.9)

I have a variable defined as 

```
create_user_body:
  active: true
  first_name: "Admin"
  last_name: "admin"
  email_address: "admin@admin.co.uk"
```

I then have a task which does this

```
  - name: Create an admin user
    uri:
      url: http://localhost/admin/users
      method: POST
      body: "{{create_user_body | to_json }}"
      body_format: json
      HEADER_admin-auth: "12345"
    register: access_token_response
```

And I get this error

```
fatal: [localhost]: FAILED! => {"changed": false, "content": "{\"Status\":\"Error\",\"Message\":\"User object validation failed.\",\"Meta\":\"\",\"Errors\":[{\"Context\":{},\"Description\":\"must be of type object\",\"Value\":\"{\\\"active\\\": true, \\\"first_name\\\": \\\"Admin\\\", \\\"last_name\\\": \\\"admin\\\", \\\"email_address\\\": \\\"admin@admin.co.uk\\\"}\"}]}\n", "content_length": "266", "content_type": "text/plain; charset=utf-8", "date": "Mon, 16 Nov 2015 09:46:06 GMT", "failed": true, "msg": "Status code was not [200]", "redirected": false, "status": 400, "x_content_type_options": "nosniff"}
```

It seems to be escaping the strings when it doesn't need to be? If I remove active:true (or turn it into a string) it seems to work OK, but then the API I'm using can't parse the string as a boolean
