### ISSUE TITLE
json content extracted from --extra-vars changed after writing to a file on the remote host

### ISSUE THREAD

**Issue by haozhenxiao** [ansible/ansible#13207]
I want to write a json array extracted from --extra-vars to a remote json file, my yml file called machine-roles.yml is like this:

```

---
- hosts: '{{ hosts }}'
  tasks:
    - name: set machine roles
      shell: echo "{{argument['machine-roles']}}" > /etc/atvhive/machine_roles.json
      sudo: yes
```

this yml file is run with:

```
ansible-playbook --extra-vars '{"hosts":"lowend", "argument":{"machine-roles":["ingest","storage","management"]}}' machine-roles.yml
```

after running, the content of **/etc/atvhive/machine_roles.json** is like this:

```
[u'ingest', u'storage', u'management']
```

why the content is changed? how should I write a json array to a remote file correctly?
