### ISSUE TITLE
Async error with check_mode

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#13205]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 2.0.0 (detached HEAD 9b9fb51d9d) last updated 2015/11/17 22:25:09 (GMT +200)
  lib/ansible/modules/core: (detached HEAD b1c0249045) last updated 2015/11/17 22:25:22 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 7da1f8d4ca) last updated 2015/11/17 22:25:22 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
##### Ansible Configuration:

none
##### Environment:

OSX, Debian 7, Debian 8
##### Steps To Reproduce:

ansible-playbook -i hosts test_async.yml -C

```

---
# test_async.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - name: async tasks
      command: echo
      async: 10
      poll: 1
```
##### Actual Results:

PLAY ***************************************************************************

TASK [async tasks] *************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The async task did not return valid JSON: expected string or buffer"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
