### ISSUE TITLE
Docker connection does not work with non-root user

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13219]
Hi,
i have have started the official jenkins docker container, e.g. named as my-jenkins, and set up my inventory as follows:

```
my-jenkins ansible_connection=docker
```

All tasks of the playbook, which is targeted to `my-jenkins` as host, fail because the default user of the container is not root. Here the error message:

```
fatal: [localhost -> aci_jenkins]: FAILED! => {"changed": false, "failed": true, "msg": "/usr/bin/python: can't open file '/var/jenkins_home/.ansible/tmp/ansible-tmp-1447958715.53-194745014881692/apt': [Errno 13] Permission denied\n", "parsed": false}
```

When I start the container before with `docker_user: root` everything works fine.

**Comment by chromerobv** [comment]
you need to enable the docker group and add user to it in order to have non root run docker commands.
- Add the docker group if it doesn't already exist.
  sudo groupadd docker
- Add users to the docker group.
  sudo gpasswd -a foo docker
- Restart the docker daemon.
  sudo service docker restart
- If the above still doesn't work you need to change the group owner ship of some files.
  chown root:docker /var/run/docker.sock
  chown root:docker /usr/bin/docker

**Comment by ThomasSteinbach** [comment]
The user on the target (local) host is already in the docker group. I talk about the user within the container. Please execute the following tiny, stripped-down Playbook to see the behavior of the docker connection:

```
- name: example of (possible?) bug in docker connector
  hosts: localhost
  tasks:
    - docker: name=myjenkins image=jenkins state=reloaded #docker_user=root
    - add_host: name=myjenkins ansible_connection=docker
    - name: create a directory in jenkins-home
      delegate_to: myjenkins
      file: path="/var/jenkins_home/test" state=directory
```

For running the playbook you need to
- have the latest Ansible 2.0 installed, which supports the docker connection but includes the bug
- have the invetory entry `local ansible_connection=localhost`

Probably you will get the same output for the third task as I postet in the initial bug description. Please run the playbook a second time, but remove the '#' in the first task, such that `docker_user=root` works and the default user within the container is _root_. By default the user within a started jenkins container is _jenkins_.

You should notice, that the playbook would run fine with _root_ within the container. You also can convince yourself that the jenkins user within the container has acces to its home directory by running the following commands:

```
docker run jenkins mkdir /var/jenkins_home/works
docker run jenkins mkdir /usr/bin/shouldnotwork
```
