### ISSUE TITLE
Tasks with include_vars take ages :(

### ISSUE THREAD

**Issue by zentavr** [ansible/ansible#13221]
**Issue Type:** Bug Report
**Ansible Version:** 2.0.0 devel@d75e707
**Ansible Configuration:**

```
[defaults]
host_key_checking = False
forks=20
```

**Environment:** Mac OS X El Capitan 10.11.1

**Summary**
I have a playbook, which starts like this:

```
- name: "Setting up all {{ game_env }} variables"
  hosts: tag_deployment_ansible
  gather_facts: False
  connection: local
  no_log: True
  tasks:
    - name: Including the defaults
      include_vars: "variables/_defaults.yml"
      tags: [ 'always' ]

    - name: Including AWS Specific Variables
      include_vars: "variables/{{ aws_env }}.yml"
      tags: [ 'always' ]

    - name: Including AWS Specific Secret Variables
      include_vars: "variables/{{ aws_env }}-secrets.yml"
      tags: [ 'always' ]

    - name: Including Game+AWS Specific Variables
      include_vars: "{{ item }}"
      with_first_found:
        - "variables/{{ game_env }}-{{ aws_env }}.yml"
        - "variables/_defaults-{{ game }}-{{ aws_env }}.yml"
      tags: [ 'always' ]

    - name: Including Game+AWS Specific Secrets
      include_vars: "{{ item }}"
      with_first_found:
        - "variables/{{ game_env }}-{{ aws_env }}-secrets.yml"
        - "variables/_defaults-{{ game }}-{{ aws_env }}-secrets.yml"
      tags: [ 'always' ]

    - name: Including Game Variables
      include_vars: "variables/game-{{ game }}.yml"
      tags: [ 'always' ]
```

`game_env` and `aws_env` come from a command-line (`-e` parameter).
In order to execute this step i need to wait little less than an hour. Ansible 1.9.4 executes that piece of cake in ~30 seconds. I have up to 70 machines in my inventory.

**Expected Results:** ~30 seconds
