### ISSUE TITLE
Copying files with mode 400 uploads with a mode of 620

### ISSUE THREAD

**Issue by garyrutland** [ansible/ansible#13225]
Hi,

I did post this in the Google forum, but my post never seemed to appear so asking here now instead.

This is probably something that isn't recommended but I'm trying to copy some PEM keys to a destination server so that they can be used by that server at a later time.
I need to make sure that they are set to a mode of 400 as well, so using the following code:

```
- name: add default ssh keys
  become: true
  copy:
    src: ./.ssh/
    dest: ~/.ssh
    mode: 400
    force: true
```

I would hope and expect to see the following when listing the files on the destination server:

```
-r--------
```

But instead I'm seeing the following:

```
-rw--w----
```

Any particular reason why the files being uploaded are actually getting the incorrect permissions?
Or is there a different approach to making sure these files have the correct permissions?

Thanks,
Gary
