### ISSUE TITLE
add vault/main.yml to roles and include by default

### ISSUE THREAD

**Issue by Lowess** [ansible/ansible#13236]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
vault

##### ANSIBLE VERSION
N/A

##### SUMMARY
Hi guys,

We are using Ansible Vault in order to secure our sensible data. In order to keep our roles self-contained, we use the following role structure:

``` yaml
### Extract from myrole/tasks/main.yaml

---
# Include sensible data
- name: Include encrypted vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ aws_account }}/vault.yaml"
    - "vault.yaml"

# Include role's tasks
- include: configure.yaml
```

Given that the `include_vars` statement, we loose the ability to do `--start-at-task "One specific task from configure.yaml"` because we might need a variable defined in the `vault.yaml` file.

It could be great if Ansible by default load a "default" vault file the same way it loads `defaults/main.yaml` or `vars/main.yaml` (Why not a `vault/main.yaml` ?).

Most of the time our use case is to encrypt AWS credentials that are used in our roles (Either to configure a software or to simply download the software from an S3 bucket).

We don't want to have the playbook dealing with vault file includes as it could become really messy:

Example:

``` yaml

---
  host: all
  vars_files:
    ### I do not want to check each role I am using in my playbook to know which one is using a vault file that I need to include!
    - roles/???/vars/vault.yaml
    - roles/???/vars/vault.yaml
    - roles/???/vars/vault.yaml
    ...
  roles: 
    - common
    - aws-cli
    - user
    - java
    - logstash-client
    - ganglia
    - nagios
```

Feel free to comment if you know an other way to solve this problem.

Thanks a lot.
