### ISSUE TITLE
Need to support ansible-playbook with hosts that are "immutable" for proxies

### ISSUE THREAD

**Issue by jsrawan-mobo** [ansible/ansible#13238]
We have a use case were we go through a proxy and want to copy files from local to remote through it.

local->proxy->all_hosts

We do this in 2 steps:

1) Copy to proxy

```
- hosts: proxy
  tasks:
    - name: Copy packages
      copy: src=./pkg dest=/tmp/ owner=ubuntu group=ubuntu mode="0664"
```

2) Distribute

```
- hosts: all
  tasks:
    - name: Distribute Package Pull style
      shell: 'scp -r proxy:/tmp/pkg/ /tmp/'
```

This works great.  However when we want to do this on a subset, we pass in the subset

```
ansible-playbook -l "subset_of_hosts" add_all_pk.yml
```

The intention is to run 1, then run 2 on the subset.
The actual result as expected is 1 is skipped, and run 2 on subset

What be useful, is something to indicate 1 cannot be subset'ed, i.e.
1) Copy to proxy

```
- hosts: proxy
  host_immutable : true
  tasks:
    - name: Copy packages
      copy: src=./pkg dest=/tmp/ owner=ubuntu group=ubuntu mode="0664"

```
