### ISSUE TITLE
Ansible 2.0: interpolate filenames with variables

### ISSUE THREAD

**Issue by yfried** [ansible/ansible#13249]
Copying question from [question](https://groups.google.com/d/msg/ansible-project/a3WzASYsWJA/PX9RVFH3EwAJ) google group.

This include works on 1.9

```
  - name: include another play
    vars:
      var_name_1: var_value_1
      var_name_2: var_value_2
    include: "code/folder/{{ var_name_1 }}.yml"
```

But fails in 2.0

```
ERROR! the file_name 'code/folder/{{ var_name_1 }}.yml' does not exist, or is not readable
```
