### ISSUE TITLE
route53 upsert broken since 782aa9a

### ISSUE THREAD

**Issue by sheldonh** [ansible/ansible#13258]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0 (devel 478c6c756a) last updated 2015/11/23 08:51:32 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 1ff0704c0c) last updated 2015/11/23 14:37:02 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 035ad1d140) last updated 2015/11/23 14:37:02 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

None
##### Environment:

N/A
##### Summary:

Since 782aa9a, route53 UPSERT is broken. Specifying `overwrite: True` with `command: create` fails if the record resource set already exists. The Error message (which comes from AWS) is:

```
Tried to create resource record set [name='example2.auto-h.net.', type='A'] but it already exists
```
##### Steps To Reproduce:

For a Route53 zone that you control, apply this playbook twice in a row:

``` yaml

---
-
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    -
      route53:
        command: create
        overwrite: True
        zone: auto-h.net
        record: example2.auto-h.net
        type: A
        value: "127.0.0.1"
```
##### Expected Results:

The following output comes from 180159b:

```
PLAY ***************************************************************************

TASK [route53 record=example2.auto-h.net command=create overwrite=True zone=auto-h.net type=A value=127.0.0.1] ***
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

This is what you get from 782aa9a and later:

```
PLAY ***************************************************************************

TASK [route53 record=example2.auto-h.net command=create overwrite=True zone=auto-h.net type=A value=127.0.0.1] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Tried to create resource record set [name='example2.auto-h.net.', type='A'] but it already exists"}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```
