### ISSUE TITLE
2.0R C1: list-tasks does not respect tags

### ISSUE THREAD

**Issue by nikut** [ansible/ansible#13260]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0 (detached HEAD f2225395f9) last updated 2015/11/23 17:22:15 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 64147ab795) last updated 2015/11/23 17:22:33 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 1a0ff8a8c8) last updated 2015/11/23 17:22:37 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### Ansible Configuration:

Can be reproduced with default configuration.
##### Environment:

Can be reproduced on CentOS 5.9 as well as Mac OS X.
##### Summary:

In Ansible 2.0 RC1 `ansible-playbook --tags <sometag> --list-tasks` lists all tasks in the playbook even if they would not be run with that tag. It also lists a bunch of "meta" tasks. In 1.9.x this works as expected.
##### Steps To Reproduce:

Playbook:

```
- hosts: localhost
  gather_facts: no
  tasks:
    - debug: msg="tag1"
      tags: tag1

    - debug: msg="tag2"
      tags: tag2
```
##### Expected Results:

Output from Ansible 1.9.4:

```
nikut@dhcp98:~/tmp$ ansible-playbook test-tags.yml --tags tag1 --list-tasks

playbook: /tmp/test-tags.yml

  play #1 (localhost):  TAGS: []
    debug msg="tag1"    TAGS: [tag1]
```
##### Actual Results:

```
nikut@dhcp98:~/tmp$ ansible-playbook test-tags.yml --tags tag1 --list-tasks

playbook: test-tags.yml

  PLAY: #1
    tasks:
      TASK: meta 
      TASK: debug msg=tag1
      TASK: debug msg=tag2
      TASK: meta 
      TASK: meta 
```
