### ISSUE TITLE
Undefined attribute causes Deprecation Warning even if task should be skipped due to failed conditional check

### ISSUE THREAD

**Issue by jnikolich** [ansible/ansible#13274]
### Ansible Version:

`ansible 2.0.0 (devel 96fcfe45d0) last updated 2015/11/23 22:29:53 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 0e043f8c58) last updated 2015/11/23 22:29:53 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/11/23 22:29:54 (GMT -400)
  config file =
  configured module search path = Default w/o overrides`
### Synopsis
- Task A registers a variable (containing, for argument's sake, zero or more filenames).
- Task B loops on 'with_items' referencing the variable registered in Task A.
- Both tasks are expected to skip, either because:
  1. They are inside a block controlled by a 'when:' check that fails to match, or
  2. Each task has an individual 'when:' check that fails to match.
- Task A correctly skips.  Because it skipped, the variable is never registered.
- Task B is expected to skip, but instead throws a deprecation warning complaining about an undefined attribute.

Currently the end result is that the play functions as hoped-for - Task A and B are both skipped and the play continue without interruption.  However, should this ever become a fatal-error as the deprecation warning admonishes, then the outcome (_i.e._ termination of the play) will become unexpected.
### Example Code

``` yaml
- block:

    # The 'failed_when' will never match.  It simply causes this task to not
    # fail if the 'ls' command fails to find any matching files.
  - name:         (webcontent) Get list of any pre-existing tarballs on target webserver
    shell:        ls ~/backups/tarball_allwebcontent*tgz
    register:     path_tarballs_target
    failed_when:  "'FAILED' in path_tarballs_target.stderr"
    changed_when: False
    tags:         webcontent

  - name:         (webcontent) Delete any pre-existing tarballs
    file:         path={{ item }} state=absent
    with_items:
      - "{{ path_tarballs_target.stdout_lines }}"
    tags:         webcontent
  when: migrate_webcontent | bool
```
### Expected Results

```
TASK [webservers : (webcontent) Get list of any pre-existing tarballs on target webserver] ***
skipping: [testbox-f23.example.com] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [webservers : (webcontent) Delete any pre-existing tarballs] **************
skipping: [testbox-f23.example.com] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```
### Actual Results

```
TASK [webservers : (webcontent) Get list of any pre-existing tarballs on target webserver] ***
skipping: [testbox-f23.example.com] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [webservers : (webcontent) Delete any pre-existing tarballs] **************
[DEPRECATION WARNING]: Skipping task due to undefined attribute, in the future this will be a fatal error.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by bcoca** [comment]
when: gets executed INSIDE the with_ loop so it cannot be used to skip undefined vars in it.

```
{{ path_tarballs_target.stdout_lines|default([]) }}"
```

^ use this to skip the task when the previous one was not run

This is not a bug, just how ansible works, otherwise you could not use `item` in conditionals to selectively execute only certain elements of a loop.

**Comment by DVGeoffrey** [comment]
I'm getting this too.. but I'm using the undefined variable in the when clause:

```
  - name: concatenate subtype env files
    shell:  "cat {{TMP}}/{{item}} >> {{EnvFile}}"
    with_items: "{{ds[artifact_name].env_files[artifact_subtype]}}"
    when: artifact_subtype is defined
```

gives

```
TASK [asdf_containers : concatenate subtype env files] **************************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.:
'artifact_subtype' is undefined.
This feature will be removed in a future release. Deprecation warnings
can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [tcal01] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
```

**Comment by candlejack297** [comment]
Also getting this on a task

```
Skipping task due to undefined Error, in the future this will be
 a fatal error.: 'project_config' is undefined.
```

```
- name: Install system dependencies for project
  become: True
  apt: pkg={{ item }} state=installed
  with_items: " {{ project_config.apt|default([]) }}"
  when: project_config is defined and 'apt' in project_config
```

**Comment by matt-byrne** [comment]
I'm getting deprecation warnings when referencing undefined variables in the when: clause also. Is there a way to do what I am trying to here without triggering them?

```
- name: Create S3 buckets for all redirect URLs (www records)
  s3_bucket:
      name: "www.{{ item }}"
      region: ap-southeast-2
      validate_certs: no
  with_items: "{{ static_s3_redirect_urls.split('\n') | default([]) }}"
  when: static_s3_redirect_urls is defined and static_s3_skip_www is not defined
```

Result:

```
TASK [static-s3 : Create S3 buckets for all redirect URLs] *********************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'static_s3_redirect_urls' is undefined.
This feature will be removed in a future release. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost]
```
