### ISSUE TITLE
Embedded string list vars with handlebars bomb in conditionals

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#13270]
Issue Type: Bug Report (2.0 regression)
Ansible Version: 2.0.0 (rc1)
Ansible Configuration: default
Environment: (fails on OSX and CentOS6)
Summary: `when` statements containing embedded templates that resolve to a list of strings fail conditional formatting with "ERROR! The conditional check 'X' failed. The error was: ERROR! template error while templating string: expected token ',', got 'string'"

Steps To Reproduce:
Run the following playbook:

```
    - hosts: localhost
      gather_facts: no
      vars:
        blah: ['1','2']
      tasks:
      - debug: var=group_names
      - shell: whoami
        when: "'1' in {{ blah }}"
```

Expected Results:

successful run 

Actual Results:

```
TASK [command] *****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check ''1' in {{ blah }}' failed. The error was: ERROR! template error while templating string: expected token ',', got 'string'"}
```

This worked in 1.9. Can be worked around by ditching the unnecessary handlebars, but what's weird is that it works fine with non-string lists and scalars. Something odd going on with the templating here, we should either fix it or warn about the extraneous handlebars as we do in other places.

Filed on behalf of Callfire

**Comment by bcoca** [comment]
The templating is more strict in 2.0 and this SHOULD have been an error in 1.x also, but was ignored  and eventually worked due to recursive templating.

**Comment by hloeffler** [comment]
whats the "right" way to do it?

**Comment by bcoca** [comment]
just avoid the mustaches:

 `when: "'1' in blah"`

**Comment by jklaiho** [comment]
My two cents: I ran into this same issue after upgrading from 1.9 to 2.0, and fixed it as @bcoca suggested.

Frankly, Ansible's documentation doesn't do a very good job of explaining when to use handlebars and when not to. In my case, here's a task after fixing it for 2.0:

```
- name: copy apt key files from all current roles to /tmp
  become: no
  copy: src="{{ item.1.path }}/{{ item.1.filename }}" dest="/tmp/{{ item.1.filename }}"
  when: "'{{ item.0.role }}' in role_names and '{{ item.1.pub }}' not in ansible_local.installed_apt_keys.key_list"
  with_subelements:
    - '{{ apt_keys_by_role }}'
    - keyfiles
```

Prior to 2.0, `role_names` was `{{ role_names }}`, which produced the error message reported by @nitzmahone. There seem to be two realms of variables at play here: Jinja2 variables and Ansible variables, and their order and method of resolution remains unclear to me. If someone was to ask me why the various bits of this task have handlebars around them or not, I couldn't really give them a satisfactory explanation. It's almost trial and error.

Documentation improvements related to this issue notwithstanding, I suppose this could be closed?
