### ISSUE TITLE
 "msg": "Failed to set a new url git@hostname:973849/repo.git for origin:  fatal: No such remote 'origin'

### ISSUE THREAD

**Issue by riponbanik** [ansible/ansible#13288]
playbook is like the following -

```yaml
---
- hosts: "{{hosts_group|default('all')}}"
  vars:
  - destination: /var/www/html
    tasks:
  - name: Clone the repo
    git: >
      repo="git@hotname:973849/repo.git"
      dest={{ destination }}
      accept_hostkey=yes
      force=yes
      key_file=~/x.pem
```
