### ISSUE TITLE
Username is ignored when using `delegate_to`

### ISSUE THREAD

**Issue by kewne** [ansible/ansible#13280]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible-playbook 1.9.4
  configured module search path = None
```
##### Ansible Configuration:

Default.
##### Environment:

Control: Ubuntu Vivid
Target: Debian
##### Summary:

When using `delegate_to`, usernames defined in inventory are ignored, which fails authentication when the usernames in the control and target machine don't match.
##### Steps To Reproduce:

``` yaml
# playbook.yml
- hosts: broker
  tasks:
    - name: echo thingy
      shell: echo This is working
      delegate_to: inf-dev01
      run_once: true
```

``` yaml
# host_vars/inf-dev01.yml

---
ansible_ssh_user: my_user
```
##### Expected Results:

Playbook should run correctly.
##### Actual Results:

Playbook fails: 

```
fatal: [localhost -> inf-dev01] => SSH Error: Permission denied (publickey,password).
```

Passwordless login is working.
Replacing `delegate_to: inf-dev01` with `delegate_to: my_user@inf-dev01` makes it work.

Let me know if there is anything else I should add.
