### ISSUE TITLE
Can't render JSON in Ansible and POST via uri module

### ISSUE THREAD

**Issue by greggilbert** [ansible/ansible#13308]
**Issue Type**: Bug Report
**Ansible Version**: 1.9.4
**Environment**: OSX 10.11.1

**Summary**: Using `lookup` to render a template that gets passed into the `uri` module's `body` parameter does not work. It throws an `TypeError: unhashable type` error. I opened a [StackOverflow question](http://stackoverflow.com/questions/33925594/cant-render-json-in-ansible-and-post-via-uri-module) about this, and thought it made sense to post it here as well.

**Steps To Reproduce**:

Run this task:

```
- name: Post
  uri:
    url: https://hooks.slack.com/endpoint
    method: POST
    return_content: no
    HEADER_Content-Type: "application/json"
    body: "{{ lookup('template', '../templates/my.json.j2', convert_data=False) }}"
```

with this in `my.json.j2`:

```
{
  "channel": "chatops",
  "username": "Deploy",
  "text": "TEST Deploy!",
  "icon_emoji": ":ghost:"
}
```

Folding the JSON into a single line within the template has the same effect. Piping the `lookup` response through `to_json` also does not work. Taking the folded JSON and using it _directly_ in the play does work, however.

**Expected result**: proper JSON sent to endpoint

**Actual result**: `TypeError: unhashable type` error; also, in certain circumstances, a `not valid JSON` error is returned by the endpoint, which indicates that the data is not being sent properly.
