### ISSUE TITLE
Ascii codec error with string 

### ISSUE THREAD

**Issue by securitybites** [ansible/ansible#13303]
I am recieving the following error when calling the ec2 module:
`msg: 'ascii' codec can't decode byte 0xe2 in position 40: ordinal not in range(128)`

My task is:

```
- name: Get EC2 VolumeID
    ec2_vol: 
      instance: facts.ansible_facts.ansible_ec2_instance_id
      state: list
      region: us-east-1
    register: volumeData
```

I am running `ansible 1.9.4`
