### ISSUE TITLE
apt_key --check falsely reports change 

### ISSUE THREAD

**Issue by t2d** [ansible/ansible#13326]
Issue Type: Bug Report
Ansible: Version: ansible 1.9.4
Environment: Debian Wheezy
Summary:
Task:

```
- name: download and import tor signing key
  apt_key:
    keyserver: keys.gnupg.net
    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
    state: present
```

If I call it normally, it returns "ok".
If I run it with --check, it always falsely returns "changed".

Expected Results:
It should return "ok" in both cases.
