### ISSUE TITLE
prompt_vars does not work for same variable again

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13363]
It is not possible to prompt a variable twice (or multiple times) accross multiple plays. Maybe the list of 'already prompted for' is being cached across plays.

Here an example playbook, which asks for another become password in each play:

```
- name: setup ansible-ci agents
  hosts: jenkins-agents
  vars_prompt:
    - name: ansible_become_pass
      prompt: "SUDO password for agents machine"
      private: yes

  roles:
    - agent

- name: install ansible-ci server
  hosts: jenkins-server
  vars_prompt:
    - name: ansible_become_pass
      prompt: "SUDO password for server"
      private: yes

  roles:
    - ansible-ci
```

As long as the variable name remains the same in both plays (ansible_become_pass) you will just get asked once for the variables value.

Reference: [Thread on groups.google.com](https://groups.google.com/forum/#!topic/ansible-project/Dnionrivamg)
