### ISSUE TITLE
lineinfile `backrefs` doesn't work when used with `with_items` 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13366]
##### Issue Type:

Bug Report

##### Component Name:
lineinfile module

##### Ansible Version:

ansible 1.9.4
  configured module search path = None
##### Ansible Configuration:

Installed via `pip`, nothing changed
##### Environment:

Control Machine: Ubuntu 14.04.1 x86_64
Managed Node: Ubuntu 14.04.1 x86_64
##### Summary:

I was trying to replace a portion of a line using `lineinfile` module. As you know, the `lineinfile` module was designed to replace the whole line rather than a part of it, so, I thought can use the `backrefs` option to achieve this. This module works fine when I replace a single line, like this:

`````` yaml
- lineinfile: dest=/tmp/test.txt regexp='^#(KEY.*)$' lin```\1' state=present backrefs=yes
``````

> P.S. Trying to remove the `#` from a configuration line here.

Before: #KEY=XXX
After: KEY=XXX

But, there were dozens of lines need to be processed this way, so, for the sake of convenience, let's do this with `with_items`:

``` yaml
- lineinfile: dest=/tmp/test.txt regexp={{item.default}} line={{item.custom}} state=present backrefs=yes
  with_items:
    - {default: '^#(KEY.*)$', custom: '\1'}
```

Before: #KEY=XXX
After: 1

What !?
##### Steps To Reproduce:

To reproduce this scenario, you'll need 3 files: a host file, a playbook, and a plain file contains the line which gonna be processed.

Host file (hosts):

```
[localhost]
127.0.0.1
```

Playbook (replace_string.yml):

``` yaml

---
- hosts: localhost
  remote_user: root

  tasks:
    - lineinfile: dest=/tmp/test.txt regexp={{item.default}} line={{item.custom}} state=present backrefs=yes
      with_items:
        - {default: '^#(KEY.*)$', custom: '\1'}
```

Plain file (/tmp/test.txt):

``` text
#KEY=XXX
```

Run it with the command: `ansible-playbook replace_string.yml -i hosts -u root`
##### Expected Results:

The line in /tmp/test.txt was changed to `KEY=XXX`
##### Actual Results:

The line in /tmp/test.txt was changed to `1`
