### ISSUE TITLE
delegate_to getting ssh errors

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#13365]
Issue Type:

Bug Report

Ansible Version:

Working on 

```
ansible 2.0.0 (detached HEAD e2ddc2f6ab) last updated 2015/11/30 18:18:21 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 0e043f8c58) last updated 2015/11/30 18:17:43 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/11/30 16:37:19 (GMT -700)

```

Doesn't work on:

```
ansible 2.0.0 (stable-2.0 204e27ca66) last updated 2015/11/30 16:38:33 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 273112c56d) last updated 2015/11/30 16:52:55 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/11/30 16:37:19 (GMT -700)
```

and doesn't work on

```
ansible 2.0.0 (devel dc0fae1af7) last updated 2015/11/30 16:37:03 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 0e043f8c58) last updated 2015/11/30 18:17:43 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/11/30 16:37:19 (GMT -700)

```

Ansible Configuration:

```
[defaults]
remote_user=root
transport=ssh
[ssh_connection]
ssh_args=-o StrictHostKeyChecking=true
```

Environment:

Centos 6

Summary:

Delegate to causing ssh key error

Steps To Reproduce:

```

---
- name: testing delegate to
  hosts: host1
  gather_facts: false
  tasks:
     - name: attempting to do a shell ls
       shell: ls
       delegate_to: delhost
```

Expected Results:

ls of home dir of delhost

Actual Results:

ssh error saying key errors looks like it can't connect to delhost but I'm not sure. I know that I can ssh normally to delhost
