### ISSUE TITLE
set user for docker connection

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13388]
I use the Docker connection plugin, introduced in Ansible 2.0, which executes Tasks with `docker exec` inside a Docker container. The command `docker exec` allows the `-u` or `--user` option, to set the user you want to execute the task within the container. It would be nice if Ansibles `remote_user` (or `become_user`?) would be applied to that option.

I already tried my luck to implement that functionality by adding the option flag and value to the Ansible connectors command list like this:

```
local_cmd = [self.docker_cmd, "exec", '-u', self._play_context.remote_user, '-i', self._play_context.remote_addr, executable, '-c', cmd]
```

However, the first task executed hangs. There is no error message, the python scrint is in process inside the container, but nothing happens. Here is the Docker connectors source file:

https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/docker.py

And here are three example tasks hanging, when adding `'-u', self._play_context.remote_user,` to both exec commands in the source file:

```
- name: create jenkins container
  docker:
    name: aci_jenkins
    image: jenkins
    state: running

- name: add aci_jenkins to inventory
  add_host:
    name: aci_jenkins
    ansible_connection: docker
    ansible_user: root

- name: install git
  delegate_to: aci_jenkins
  apt:
    name: git
    state: present
```

You can execute those task on your localhost, if you have Docker installed. Any idea, why the third task is hanging?
