### ISSUE TITLE
When roles are run with tags, dependent roles are only run for the first role in a playbook.

### ISSUE THREAD

**Issue by pajtai** [ansible/ansible#13406]
Using ansible 1.9.4. reconfirmed by @global on 2.2.0.0

##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.2.0.0
```

##### COMPONENT NAME
tags

If I have a role - `example-3` which depends on `example-1` then provisioning using `--tags=example-3` will only run `example-1` if  `example-3` is the first role in the list of roles.

Below are is the output for each case:
### Dependencies do not run for `--tags=example-3`

Playbook:

```

---
- name: Demo with role tagging
  hosts: vagrant
  sudo: yes
  roles:
    - { role: 'example-2', tags: 'example-2' }
    - { role: 'example-3', tags: 'example-3' }
```

Output:

```
PLAY [Demo with role tagging] *************************************************

GATHERING FACTS ***************************************************************
ok: [192.168.12.148]

TASK: [example-3 | Running example 3] *****************************************
ok: [192.168.12.148] => {
    "msg": "Example 3"
 }

PLAY RECAP ********************************************************************
192.168.12.148             : ok=2    changed=0    unreachable=0    failed=0
```
### Dependencies do run for `--tags=example-3`

Playbook:

```

---
- name: Demo with role tagging
  hosts: vagrant
  sudo: yes
  roles:
    - { role: 'example-3', tags: 'example-3' }
```

Output:

```
PLAY [Demo with role tagging] *************************************************

GATHERING FACTS ***************************************************************
ok: [192.168.12.148]

TASK: [example-1 | Running example 1] *****************************************
ok: [192.168.12.148] => {
    "msg": "Example 1"
}

TASK: [example-3 | Running example 3] *****************************************
ok: [192.168.12.148] => {
    "msg": "Example 3"
}

PLAY RECAP ********************************************************************
192.168.12.148             : ok=3    changed=0    unreachable=0    failed=0
```

There is a sample repo [here](https://github.com/pajtai/ansible-tags-example) which runs the `example-3` tag on vagrant provisioning. If you run `vagrant up` or subsequently `vagrant provision` or `ansible-playbook` against the VM box, then you can see the case where the dependencies do not run. To get the dependencies to run comment out [the first role](https://github.com/pajtai/ansible-tags-example/blob/master/ansible/site.yml#L6).

This problem is referenced by @ghostwords [here](https://github.com/ansible/ansible/issues/4339#issuecomment-160677433)
