### ISSUE TITLE
Pull Request #13200 (pipelining + requiretty fix)  breaks other connection plugins

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13409]
I recently opened issue #13388 where I tried to introduce the `--user=<user>` option for Ansibles Docker connection plugin. I concluded within this issue, that my changes made the execution of Ansible tasks on Docker containers really slow.

Today I started a Playbook on another machine (at work), where I also deploy tasks to a container with the Docker connectio plugin and everything went fine, till I updated my Ansible installation. Since then every task executed on a Docker containe takes very long and Python consumes 100% CPU.

After some time of investigation it turns out that this behavior was caused by the pull request https://github.com/ansible/ansible/pull/13200 which was merged yesterday: https://github.com/ansible/ansible/commit/bebd2c5f3422b3c52ca0018d19ea4702c066c3e2.

Here is an example Playbook, which will reproduce the current behavior:

```
- name: this playbook is for testing purposes
  hosts: localhost
  tasks:

    - name: run jenkins container
      docker:
        name: jenkinstest
        image: jenkins
        state: started
        docker_user: root

    - name: add container to inventory
      add_host:
        name: jenkinstest
        ansible_connection: docker

    - name: run a task inside the container
      delegate_to: jenkinstest
      file:
        path: /root/test/me
        state: directory
```

If you reset your local repository to the mentioned pull request, this playbook will hang on the third task and Python consumes 100% CPU for a long time. If you reset your local repository to the commit before, everything works as expected and the playbook should be executed within seconds.

The changes made are too sophisticated for my humble Python knowledge. So @amenonsen please have a look, what could cause the behavior. Maybe @abadger has some good ideas too.

This issue would enable feature request #13388.
