### ISSUE TITLE
Colon-space in lineinfile argument produces syntax error

### ISSUE THREAD

**Issue by brontitall** [ansible/ansible#1341]
Given this play:

``` ---
    - hosts: ${host}
      tasks:
      - name: Create test alias
        action: lineinfile dest=/etc/mail/aliases regexp="^test:" line='test: root' state=present
```

I get this error:

```
ERROR: Syntax Error while loading YAML script, space_bug_case.yml
Note: The error may actually appear before this position: line 5, column 73

  - name: Create test alias
    action: lineinfile dest=/etc/mail/aliases regexp="^test:" line='test: root' state=present
                                                                        ^
```

It seems that it's specifically the ": " sequence that causes the problem, since (thanks to cocoy on IRC) the following all work:

```
action: lineinfile dest=/etc/mail/aliases regexp="^test:" line='test:\t root' state=present
action: lineinfile dest=/etc/mail/aliases regexp="^test:" line='test:root' state=present
action: lineinfile dest=/etc/mail/aliases regexp="^test:" line='test root' state=present
```

(although the last gives a different error, since it no longer matches the regexp.)

I'm running `devel` on MacOS with Python and libyaml from homebrew:

```
$ brew list --versions python libyaml
python 2.7.3
libyaml 0.1.4
$ ansible --version
ansible 0.8 (devel f160502b7b) last updated 2012/10/16 16:15:01 (GMT +1100)
```

**Comment by mpdehaan** [comment]
You need to outer quote stuff like this when you have an extra colon

action: "lineinfile blarg blarg blarg blarg "

**Comment by t2d** [comment]
with your trick i recieved `fatal: [host] => module lineinfile: not found in /usr/share/ansible/:library:/home/user/playbooks/library`
I had to do `lineinfile: 'args args="asdas"'`

**Comment by ghost** [comment]
works for me:

```
- name: updating of status script
  lineinfile: "dest=/opt/script.sh regexp='DIR=' line='        DIR=/var/run'"
```

**Comment by mpdehaan** [comment]
Sure if you start a line with a quote you end the line with a quote, and you're good to go!

**Comment by drewp** [comment]
Still seems broken in 1.3.2. This fails:

```
- lineinfile:
    regexp="^foo:"
    line="foo: \"| /usr/bin/curl http://localhost:9108/newmail -H 'Content-type: message/rfc822' --data-binary @-\""
```

-> Syntax Error while loading YAML script on the first colon in 'line'

This works, and I only have to avoid the colon-space combos:

```
- set_fact: colon=":"
- lineinfile:
    regexp="^foo:"
    line="foo{{colon}} \"| /usr/bin/curl http://localhost:9108/newmail -H 'Content-type{{colon}} message/rfc822' --data-binary @-\""
```

**Comment by drewp** [comment]
Don't need a new fact variable; {{':'}} is enough to avoid the parser problem

**Comment by DaveQB** [comment]
Ver 1.4.1

@drewp  Brilliant solution. I have been going crazy with single and double quotes, nothing will parse. Interesting, I don't have any issues is using the same line on the command line in a -a " " Only in the playbook does it have this issue. Even an YAML parser said I was doing it right.

Thanks again.
PS Hash symbol (#) looks harder to use.

**Comment by brucellino** [comment]
Just wasted 3 hours trying to figure this out, thanks for the tip !

**Comment by vcastellm** [comment]
Annoying stuff

**Comment by udondan** [comment]
@drewp Awesome nice trick, thanks! `{{':'}}`

**Comment by rpocklin** [comment]
Just found this after tearing my hair out.  @drewp thanks :beer:

**Comment by seanburlington** [comment]
ansible 1.9 (devel 2b037400ad) last updated 2015/02/17 22:11:14 (GMT +100)

same bug here 

thanks @drewp 

This works - but I couldn't find any other method of escaping that did

``` YAML
# https://github.com/brutasse/graphite-web/commit/28a426811ac71625fe30f532b9a6221acc55c7bc
- name: fix deprecated CACHE config  
  lineinfile: dest=/usr/lib/python2.6/site-packages/graphite/app_settings.py regexp='^CACHE_BACKEND.*'  line="CACHES = { 'default'{{':'}} {   'BACKEND'{{':'}} 'django.core.cache.backends.dummy.DummyCache', }, }"
```

**Comment by seanburlington** [comment]
I take it back - full line quoting works fine

``` YAML
  lineinfile: "dest=/usr/lib/python2.6/site-packages/graphite/app_settings.py regexp='^CACHE_BACKEND.*'  line=\"CACHES = { 'default': {   'BACKEND': 'django.core.cache.backends.dummy.DummyCache', }, }\""
```

**Comment by stephanadler** [comment]
Wow. I am on 1.9.2 an also just ran against this problem. I doubted myself for hours before finding this.

**Comment by Hirandil** [comment]
Thanks a lot @drewp, your saved me hours of work !

**Comment by msmagnanijr** [comment]
Thanks!

**Comment by J-Zet** [comment]
...just to name a (in my opinion) more readable solution, through using the '>'-mechanism. 
[see here](http://symfony.com/doc/current/components/yaml/yaml_format.html)

``` yaml

  - name: "setting cluster name to: {{ es_cluster_name }}"
    lineinfile: >
      dest=/etc/elasticsearch/elasticsearch.yml
      regexp="cluster.name:"
      line="cluster.name: {{ es_cluster_name }}"
    become: yes

```
