### ISSUE TITLE
[v2] Inconsistent interpretation of backslashes

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#13426]
**Ansible version**

```
ansible 2.0.0 (stable-2.0 f630e140d2) last updated 2015/12/04 08:05:58 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 273112c56d) last updated 2015/11/24 09:00:04 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD e46e2e1d6f) last updated 2015/11/24 09:00:04 (GMT +300)
```

**Summary**

I'm updating a properties file for a Java app.  It needs colons to be escaped with a single backslash, like this:

```
server.url=http\://localhost
```

I'm using the following task:

``` yaml
- name: update config file
  lineinfile:
    dest: /opt/app/conf/context.properties
    regexp: ^{{ item.key.replace('.', '[.]') }}=.*
    line: "{{item.key}}={{ item.value.replace(':', '\\\\:') }}"
  with_dict:
    server.url: "{{ public_url }}"
```

This works fine with Ansible 1.9, but produces `server.url=http\\://localhost` with Ansible 2.0.
