### ISSUE TITLE
ansible_ssh_host is undefined

### ISSUE THREAD

**Issue by geissdoerfer** [ansible/ansible#13430]
I try to wait for ssh port to become available for a special host inside a playbook. This is the excerpt:

```
- name: Waiting  to come back
      local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port|default(22) }} state=started delay=10
      tags:
        - reboot
```

ansible 1.9.4 fails with `fatal: [myhost -> 127.0.0.1] => One or more undefined variables: 'ansible_ssh_host' is undefined` The same goes for `inventory_hostname`

I'm not sure if i'm missing something or this is a bug

**Comment by abadger** [comment]
`inventory_hostname` appears to work here.  Perhaps you're getting an error from ansible_ssh_host in your second example?

Try this:

```
    - wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ hostvars[inventory_hostname].get('ansible_ssh_port', 22) }}"
```

**Comment by abadger** [comment]
Since it's a local_action in your original, try this actually:

```
    - wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ hostvars[inventory_hostname].get('ansible_ssh_port', 22) }}"
      delegate_to: localhost
```
