### ISSUE TITLE
"failed" attribute of a task result works strangely in conditionals

### ISSUE THREAD

**Issue by jan-warchol** [ansible/ansible#13474]
##### Issue Type:

Bug Report and/or Documentation Report
##### Ansible Version:

ansible 1.9.4
##### Ansible Configuration:

default.
##### Environment:

N/A
##### Summary:

Task results (that can be saved to variables using `register:` keyword) contain a `"failed"` key.  However, this key cannot be used in conditionals like another keys.  For example, while

``` yaml
failed_when: result.rc != 0 and "No such file or directory" not in result.stderr
```

works, this:

``` yaml
failed_when: result.failed == true and "No such file or directory" not in result.stderr
```

doesn't work. 
##### Steps To Reproduce:

``` yaml
- hosts: localhost
  tasks:
    - name: test
      shell: ls /some/nonexisting/path
      register: result
      failed_when: result.failed == true
```

doesn't work: "error while evaluating conditional"

``` yaml
- hosts: localhost
  tasks:
    - name: test
      shell: ls /some/nonexisting/path
      register: result
      failed_when: result.failed == "true"
```

doesn't work: "error while evaluating conditional"

``` yaml
- hosts: localhost
  tasks:
    - name: test
      shell: ls /some/nonexisting/path
      register: result
      failed_when: result|failed
```

this works.
##### Expected Results:

Either first or second version produce the same results as the third version.
**OR**
The documentation [here](http://docs.ansible.com/ansible/playbooks_error_handling.html#controlling-what-defines-failure) explain why the first two versions don't work.
##### Actual Results:

See inline.

Here's the debug of the `result` variable:

``` json
ok: [localhost] => {
    "var": {
        "result": {
            "changed": true, 
            "cmd": "ls /some/nonexisting/path", 
            "delta": "0:00:00.002105", 
            "end": "2015-12-08 17:15:06.581510", 
            "failed": false, 
            "failed_when_result": false, 
            "invocation": {
                "module_args": "ls /some/nonexisting/path", 
                "module_complex_args": {}, 
                "module_name": "shell"
            }, 
            "rc": 2, 
            "start": "2015-12-08 17:15:06.579405", 
            "stderr": "ls: cannot access /some/nonexisting/path: No such file or directory", 
            "stdout": "", 
            "stdout_lines": [], 
            "warnings": []
        }
    }
}
```

As you can see, the `"failed"` key is there.  Why it cannot be used in conditional?
