### ISSUE TITLE
Inconsistent variable type preservation

### ISSUE THREAD

**Issue by aboyett** [ansible/ansible#13484]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
ansible 2.0.0-0.7.rc2

```
ansible 2.0.0 (detached HEAD cc98528ecb) last updated 2015/12/08 22:37:26 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 29a83704a8) last updated 2015/12/08 13:22:45 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 2903021943) last updated 2015/12/08 13:22:45 (GMT -700)
  config file = 
  configured module search path = Default w/o overrides
```

also verified on v1.9.4-1

```
ansible 1.9.4 (detached HEAD 5af1cda7c9) last updated 2015/12/08 23:07:50 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 206a1247d9) last updated 2015/12/08 22:53:36 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 882ec41e12) last updated 2015/12/08 22:53:36 (GMT -700)
  configured module search path = None
```

and ansible 1.9.3-edx where @feanil has committed the same changes for the edx build of ansible

```
ansible 1.9.3-edx (detached HEAD 59193ccfd6) last updated 2015/12/08 23:29:37 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 1ceac602bb) last updated 2015/12/08 23:29:44 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 2415f4c163) last updated 2015/12/08 23:29:44 (GMT -700)
  v2/ansible/modules/core: (detached HEAD 85c8a892c8) last updated 2015/12/08 23:29:44 (GMT -700)
  v2/ansible/modules/extras: (detached HEAD 70ea058563) last updated 2015/12/08 23:29:44 (GMT -700)
  configured module search path = None
```
##### CONFIGURATION
No config changes, this is reproducible in a fresh checkout of v2.0.0-0.7.rc2

##### OS / ENVIRONMENT
Verified on:
- Debian 9 (testing/stretch)
- Ubuntu 14.04

##### SUMMARY
In ansible 1.9.4 (and lower) variables of basic type are consistently cast to string when referenced in variables of complex types (list/map.) During the development of 2.0 @feanil from edx has committed several changes(#10465, #10957) to conserve the type of numeric, boolean and null variables. These types are correctly conserved during direct reference of these datatypes, but it does not work in cases of indirect reference like so:

```
num: 5
num_ref: "{{ num }}"            <-- results in a numeric value of 5
map:
    num: "{{ num }}"            <-- results in a numeric value of 5
    num_ref: "{{ num_ref }}"    <-- results in a string value of "5"
```

No level of type conversion using the bool or int jinja filters is able to convert these values to the correct type. As a result I'm seeing errors from systems like MongoDB or this error from an AWS API:

```
Parameter validation failed:
Invalid type for parameter [1].InstanceCount, value: 3, type: <type 'unicode'>, valid types: <type 'int'>, <type 'long'>
```

##### STEPS TO REPRODUCE
The below playbook creates variables of several types (`num_var`, `bool_var`, `null_var`) and additional variables (`<type>_ref`) referencing the original variables. In the case of the numeric variable, `num_cast_ref` also attempts to convert `num_var` during assignment. A map, `var_map`, is created containing all the variables, and in the case of `num_var` several different variations of converting to an int are attempted in the map. Two tasks are present, one to display the map and a second that results in an evaluation failure on ansible 2.0 (I assume due to the same inconsistent typing.)

```yaml

---
- name: type preservation test
  hosts: localhost
  sudo: no
  gather_facts: no

  vars:
    num_var: 5
    num_ref: "{{ num_var }}"
    num_cast_ref: "{{ num_var | int }}"
    bool_var: yes
    bool_ref: "{{ bool_var }}"
    null_var: null
    null_ref: "{{ null_var }}"
    null2: None
    null2_ref: "{{ null }}"

    var_map:
      num_var: "{{ num_var }}"
      num_ref: "{{ num_ref }}"
      num_ref_cast: "{{ num_ref | int }}"
      num_cast_ref: "{{ num_cast_ref }}"
      num_cast_ref_cast: "{{ num_cast_ref | int }}"
      bool_var: "{{ bool_var }}"
      bool_ref: "{{ bool_ref }}"
      null_var: "{{ null_var }}"
      null_ref: "{{ null_ref }}"

    null2_map:
      null2: "{{ null2 }}"
      null2_ref: "{{ null2_ref }}"

  tasks:
  - name: numeric type preservation test
    debug: var=var_map
  - name: "null evaluation failure"
    debug: var=null2_map
```

##### EXPECTED RESULTS
I would expect that in ansible 2.0, with @feanil's patches, that types would be preserved unless an explicit conversion has occurred using a jinja2 filter.

```
PLAY [type preservation test] **************************************************

TASK [numeric type preservation test] ******************************************
ok: [localhost] => {
    "changed": false, 
    "var_map": {
        "bool_ref": true, 
        "bool_var": true, 
        "null_ref": null, 
        "null_var": null, 
        "num_cast_ref": 5, 
        "num_cast_ref_cast": 5, 
        "num_ref": 5, 
        "num_ref_cast": 5, 
        "num_var": 5
    }
}

TASK [null evaluation failure] *************************************************
ok: [localhost] => {
    "changed": false, 
    "null2_map": {
        "null2": null, 
        "null2_ref": null
    }
}
PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```

##### ACTUAL RESULTS
Playbook invoked via `ANSIBLE_NOCOWS=1 ansible-playbook ./test-case.yml -v -i hosts` in all cases.

Ansible 1.9.4-1 stock -- basic types are consistently cast to string

```
PLAY [type preservation test] ************************************************* 

TASK: [numeric type preservation test] **************************************** 
ok: [localhost] => {
    "var": {
        "var_map": {
            "bool_ref": "True",
            "bool_var": "True",
            "null_ref": "",
            "null_var": "",
            "num_cast_ref": "5",
            "num_cast_ref_cast": "5",
            "num_ref": "5",
            "num_ref_cast": "5",
            "num_var": "5"
        }
    }
}

TASK: [null evaluation failure] *********************************************** 
ok: [localhost] => {
    "var": {
        "null2_map": {
            "null2": "None",
            "null2_ref": "{{ null }}"
        }
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

Ansible 1.9.3-edx -- direct basic types retain their type information, indirectly referenced types are cast to string

```
PLAY [type preservation test] ************************************************* 

TASK: [numeric type preservation test] **************************************** 
ok: [localhost] => {
    "var": {
        "var_map": {
            "bool_ref": "True",
            "bool_var": true,
            "null_ref": "",
            "null_var": null,
            "num_cast_ref": "5",
            "num_cast_ref_cast": "5",
            "num_ref": "5",
            "num_ref_cast": "5",
            "num_var": 5
        }
    }
}

TASK: [null evaluation failure] *********************************************** 
ok: [localhost] => {
    "var": {
        "null2_map": {
            "null2": "None",
            "null2_ref": "{{ null }}"
        }
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0 
```

Ansible 2.0.0-0.7rc2 output -- direct basic types retain their type information, indirectly referenced types are cast to string. references to null defined via python's `None` can result in an undefined error.

```
PLAY [type preservation test] **************************************************

TASK [numeric type preservation test] ******************************************
ok: [localhost] => {
    "changed": false, 
    "var_map": {
        "bool_ref": true, 
        "bool_var": true, 
        "null_ref": "", 
        "null_var": null, 
        "num_cast_ref": "5", 
        "num_cast_ref_cast": "5", 
        "num_ref": "5", 
        "num_ref_cast": "5", 
        "num_var": 5
    }
}

TASK [null evaluation failure] *************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! ERROR! ERROR! 'null' is undefined"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```
