### ISSUE TITLE
support a way to easily create a list of tasks

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#135]
proposed:

```
 - name: install $item
   action: yum pkg=$item state=installed
   with_items:
     - cobbler
     - apache
     - stuff
```

This would actually create a list of several tasks when parsed that executed normally as if there were 3 seperate tasks
