### ISSUE TITLE
Regsiter no longer working

### ISSUE THREAD

**Issue by jschank** [ansible/ansible#13504]
this task used to work fine:

``` yaml
- name: ensure git ignores filemode changes (unset)
  shell: "git config --unset-all --global core.filemode"
  register: result
  failed_when: "{{result.rc not in [0, 5]}}"
  tags:
    - prep
```

But now I get a fatal error
`fatal: [machine]: FAILED! => {"failed": true, "msg": "ERROR! 'result' is undefined"}`

I am using this version of ansible-playbook

```
[promking@localhost prom-king]$ ansible-playbook --version
ansible-playbook 2.0.0 (detached HEAD a6de4b86a8) last updated 2015/10/21 14:38:28 (GMT +000)
  lib/ansible/modules/core: (detached HEAD bbcfb1092a) last updated 2015/09/04 12:10:47 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD b8803306d1) last updated 2015/09/04 12:10:50 (GMT +000)
  config file = /vagrant/ansible.cfg
  configured module search path = ./library/**
```
