### ISSUE TITLE
task entry environment: is not autotemplated

### ISSUE THREAD

**Issue by nikulk** [ansible/ansible#13514]
The issue remarked here: https://github.com/ansible/ansible/issues/11912 seems to be back. I'm trying to use a variable in environment: field as follows:

```
- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: django_environment
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django.migrate
```

The variable is defined in vars/main.yml as follows:

```
django_environment:
  DJANGO_SETTINGS_MODULE: "{{ django_settings_file }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  STATIC_ROOT: "{{ nginx_static_dir }}"
  DATABASE_USER: "{{ db_user }}"
  DATABASE_PASSWORD: "{{ db_password }}"
  EMAIL_HOST: "{{ email_host|default(omit) }}"
  EMAIL_HOST_USER: "{{ email_host_user|default(omit) }}"
  EMAIL_HOST_PASSWORD: "{{ email_host_password|default(omit) }}"
  BROKER_URL: "{{ broker_url|default(omit) }}"
```

On reaching this task, I get the following error:

```
fatal: [52.27.20.139]: FAILED! => {"failed": true, "msg": "ERROR! environment must be a dictionary, received django_environment (<class 'ansible.parsing.yaml.objects.AnsibleUnicode'>)"}
```

Even the documentation says this should work: http://docs.ansible.com/ansible/playbooks_environment.html
Look at the code titled "The environment can also be stored in a variable, and accessed like so:"

My ansible version is as follows: (I just did an install from the git repo)

```
ansible 2.1.0 (devel bd0f9a4afc) last updated 2015/12/11 05:46:08 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 0d23b3df52) last updated 2015/12/11 05:46:21 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 51813e0033) last updated 2015/12/11 05:46:30 (GMT +000)
  config file = /vagrant/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Could you please suggest me a workaround for the time being? Thank you! It's great to use Ansible, has saved me so much time I can't imagine. A few hours for a repeatable stack configuration is just beautiful!.
