### ISSUE TITLE
Strange "ERROR! The conditional check ..." in the handler of a role in ansible 2.0.0

### ISSUE THREAD

**Issue by zentavr** [ansible/ansible#13549]
**Issue Type:** Bug Report
**Ansible Version:** 2.0.0 stable-2.0 @b6dac26
**Ansible Configuration:**

```
[defaults]
host_key_checking = False
forks = 10
var_compression_level=9
retries=5
fact_caching = jsonfile
fact_caching_connection = ~/.ansible/tmp
```

**Environment:** Mac OS X El Capitan 10.11.1

**Summary**
I have a playbook, in which I use certain roles:

```
- name: "Setting up all {{ game_env }} machines"
  hosts: tag_deployment_ansible
  gather_facts: True
  sudo: True
  remote_user: "{{ idle_user }}"
  roles:
    - role: memcached
      memcached_memory_chunks_multiplier: 1.05
      memcached_memory_chunk_size: 16
      tags: [ 'memcached' ]
      when: ec2_tag_role == 'memcache' and ec2_tag_environment == game_env
...
...
other roles
...
```

that memcached role was written uses the pieses of @bennojoy [memcached module](https://github.com/bennojoy/memcached)
Here is the structure:

```
(.venv)[EDENV: cashdev] zentavr@zentavr-gsn-mac:~/__repos/ansible/roles/memcached$ tree
.
├── defaults
│   └── main.yml
├── handlers
│   └── main.yml
├── tasks
│   └── main.yml
└── templates
    └── memcached.conf.j2

4 directories, 4 files
```

When I execute a playbook, I face this error:

```
RUNNING HANDLER [memcached : restart memcached] ********************************
fatal: [172.29.36.76]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'ec2_tag_role == 'memcache' and ec2_tag_environment == game_env' failed. The error was: ERROR! error while evaluating conditional: ec2_tag_role == 'memcache' and ec2_tag_environment == game_env ({% if ec2_tag_role == 'memcache' and ec2_tag_environment == game_env %} True {% else %} False {% endif %})"}
```

`ec2_tag_role` and `ec2_tag_environment` come from ec2.py dynamic inventory script

The same playbook works pretty fine with 1.9.4 version.

**Expected Results:** workeable handler
