### ISSUE TITLE
Seems like default() filter does not work with ansible 2.0.0@devel

### ISSUE THREAD

**Issue by zentavr** [ansible/ansible#13547]
**Issue Type:** Bug Report
**Ansible Version:** 2.0.0 devel@8d16638 
**Ansible Configuration:**

```
[defaults]
host_key_checking = False
forks=20
```

**Environment:** Mac OS X El Capitan 10.11.1

**Summary**
I have a task like this:

```
    - name: Spinning up EC2 instances
      ec2:
        key_name: "{{ instances_keypair }}"
        instance_type: "{{ item.0.instance_type }}"
        image: "{{ item.0.image }}"
        instance_tags: "{{ item.0.instance_tags }}"
        exact_count: "{{ item.1.exact_count }}"
        count_tag: "{{ item.0.count_tag }}"
        vpc_subnet_id: "{{ item.1.vpc_subnet_id }}"
        group: "{{ item.0.group }}"
        volumes: "{{ item.0.volumes }}"
        zone: "{{ ec2_region + item.1.az }}"
        region: "{{ ec2_region }}"
        wait: "{{ item.0.wait|default(yes) }}"
        wait_timeout: "{{ item.0.wait_timeout|default(300) }}"
      register: ec2
      with_subelements:
        - ec2_instances
        - azs
```

...where `ec2_instances` is:

```
ec2_instances:
  # Memcache Servers
  - type: memcache
    instance_type: m3.medium
    image: "{{ image_id }}"
    group: ['private']
    instance_tags:
      Name: "memcache-{{ env }}"
      role: memcache
      environment: "{{ env }}"
      memcache_environment: "{{ env }}"
      deployment: ansible
    volumes:
      - device_name: /dev/sdp
        # For any volume, a volume size less than 1 will be interpreted as a request not to create the volume.
        volume_size: 0
        delete_on_termination: true
    count_tag:
      role: memcache
      environment: "{{ env }}"
      memcache_environment: "{{ env }}"
      deployment: ansible
    azs:
      - az: a
        # Private Subnet ID in "a"
        vpc_subnet_id: "{{ subnets['a']['private'] }}"
        exact_count: 0
      - az: b
        # Private Subnet ID in "b"
        vpc_subnet_id: "{{ subnets['b']['private'] }}"
        exact_count: 1
      - az: d
        # Private Subnet ID in "d"
        vpc_subnet_id: "{{ subnets['d']['private'] }}"
        exact_count: 0
      - az: e
        # Private Subnet ID in "e"
        vpc_subnet_id: "{{ subnets['e']['private'] }}"
        exact_count: 0
    wait: yes
    wait_timeout: 360

  #1 redis cluster (2 nodes)
  - type: redis
    instance_type: m3.medium
    image: "{{ image_id }}"
    group: ['private']
    instance_tags:
      Name: "redis-{{ env }}"
      role: redis
      environment: "{{ env }}"
      redis_environment: "{{ env }}"
      deployment: ansible
    count_tag:
      role: redis
      environment: "{{ env }}"
      redis_environment: "{{ env }}"
      deployment: ansible
    volumes:
      - device_name: /dev/sdp
        volume_size: 10
        delete_on_termination: true
    azs:
      - az: a
        # Private Subnet ID in "a"
        vpc_subnet_id: "{{ subnets['a']['private'] }}"
        exact_count: 1
      - az: b
        # Private Subnet ID in "b"
        vpc_subnet_id: "{{ subnets['b']['private'] }}"
        exact_count: 1
      - az: d
        # Private Subnet ID in "d"
        vpc_subnet_id: "{{ subnets['d']['private'] }}"
        exact_count: 0
      - az: e
        # Private Subnet ID in "e"
        vpc_subnet_id: "{{ subnets['e']['private'] }}"
        exact_count: 0
```

When I execute the task - I face an error when we reach the block without defined (that redis cluster in my case):

```
    wait: yes
    wait_timeout: 360
```

The error is:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'yes' is undefined"}
```

**Expected Results:** workeable `default()` filter
