### ISSUE TITLE
Enviroment  provided vars are not properly quoted

### ISSUE THREAD

**Issue by sherlockholmes** [ansible/ansible#13558]
ansible 1.9.4

This is my playbook:

``` yaml

---
- name: Compile something
  hosts: all
  become: yes
  become_user: root
  become_method: su
  tasks:
    - name: Compile Something
      shell: echo $CC
      environment:
                CC: 'gcc -m32'
```

And then ansible FAILS:

```
bin/bash -c 'su root -c "/bin/bash -c '"'"'echo BECOME-SUCCESS-scmdgyaubdelofihozrflttaywwjxaaz; LANG=C CC='"'"'"'"'"'"'"'"'gcc -m32'"'"'"'"'"'"'"'"' LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1450188742.95-103516450292967/command; rm -rf /tmp/ansible-tmp-1450188742.95-103516450292967/ >/dev/null 2>&1'"'"'"'

-m32"' LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1450188742.95-103516450292967/command; rm -rf /tmp/ansible-tmp-1450188742.95-103516450292967/ >/dev/null 2>&1': -c: line 0: unexpected EOF while looking for matching `"'
-m32"' LC_CTYPE=C /usr/bin/python /tmp/ansible-tmp-1450188742.95-103516450292967/command; rm -rf /tmp/ansible-tmp-1450188742.95-103516450292967/ >/dev/null 2>&1': -c: line 1: syntax error: unexpected end of file
```

Erasing ' is the same result.
