### ISSUE TITLE
Directly referenced roles in a play collide if the base name is the same

### ISSUE THREAD

**Issue by lukehoersten** [ansible/ansible#13578]
##### Issue Type:

Bug Report
##### Ansible Version:

`ansible 2.1.0` installed via `pip install git+https://github.com/ansible/ansible.git@devel#egg=ansible --upgrade`
##### Environment:

Local box: OS X 10.11.2, Target box: Ubuntu Wily
##### Summary:

Directly referenced roles in a play collide if the base name is the same.
##### Steps To Reproduce:

Set up a play like this with two roles referenced outside the role search path:

``` yaml
- name: example play
  hosts: all
  roles:
    - "../folder1/myrole"
    - "../folder2/myrole"
```
##### Expected Results:

Since the roles are the same names but different folders, each role should be run distinctly.
##### Actual Results:

The first role runs as the first and second role like it's cached or something.
