### ISSUE TITLE
[2.x] Enhancement: Ability to wrap blocks around other content such as roles (in addition to tasks)

### ISSUE THREAD

**Issue by dmsimard** [ansible/ansible#13587]
The blocks feature from Ansible 2 is great but as the [documentation](http://docs.ansible.com/ansible/playbooks_blocks.html) (and my various attempts) shows, it can only be used in the scope of a tasks list.

It would be awesome if you could use blocks elsewhere as well, such as to wrap around roles. Here's two example playbooks to explain what I mean:

```

---
# playbook1.yml
- name: "Create test environment"
  hosts: localhost
  roles:
    - role: "create-test-environment"

# It is expected that any of these tests can and will fail but laid out
# like this, the testing environment will not be destroyed if there are any
# failures in the tests, unless they are plastered with ignore_errors everywhere.
# I would love to wrap the content of this playbook in a block to ensure
# the test environment would always be destroyed.
- name: "Test things"
  hosts: nodes
  roles:
    - role: "test-one"
    - role: "test-two"
    - role: "test-three"

- name: 'Destroy test environment'
  hosts: localhost
  roles:
    -role: "destroy-test-environment"
```

and

```

---
# playbook2.yml
- name: "Run tests"
  hosts: nodes
  pre_tasks:
    - name: "create test environment"
      roles:
        - role: "create-test-environment"
  roles:
    # It is expected that any of these tests can and will fail but laid out
    # like this, the testing environment will not be destroyed if there are any
    # failures in the tests, unless they are plastered with ignore_errors everywhere.
    # I would love to see post_tasks executed even if there was a failure in
    # the tests.
    - role: "test-one"
    - role: "test-two"
    - role: "test-three"
  post_tasks:
    - name: "destroy test environment"
      roles:
        - role: "destroy-test-environment"
```

**Comment by diefans** [comment]
I think it would be consequent to also have role specific folders like `pre_tasks` and `post_tasks` (see http://docs.ansible.com/ansible/playbooks_roles.html#roles). In that way you could wrap role dependencies (defined in `meta`), which afaik seems only possible with subrole dependencies...

**Comment by mwhite14** [comment]
+1 - Using Ansible to build AMIs, and would love the blocks to wrap a larger scope so an orphaned instance can be cleaned up on failure.

**Comment by pporada-gl** [comment]
That would be a useful feature.

**Comment by dmsimard** [comment]
So I think this has somewhat been addressed, at least as far as roles are concerned, with the release of 2.2 with the new task: include_role.

You can do something like this, I guess:

```
---
# playbook.yml (pseudo-code)
- name: "Test something"
  hosts: localhost
  tasks:
    - name: Create environment
      include_role: create

    - block:
        - name: Test something
          include_role: test
      always:
        - name: Destroy environment
          include_role: destroy
```
