### ISSUE TITLE
handlers should take variables

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#1358]
I'd like to write a generic service restart handler.

so I could do notify:
    - restart svc svc=httpd

and only have a single handler for restarting most services in my handler include. I can't seem to define variables like that.

**Comment by mpdehaan** [comment]
Basically handlers are real objects, so they have to exist.

But I can see being able to parameterize handlers like we can task files, maybe.   

```
- handlers:
    -  include: restart.yml svc=$item
       with_items:
          - httpd
          - ntpd
```

or something like that.

alternatively we could think of some way to dynamically add them on demand to the playbook, which may be useful.

**Comment by sfromm** [comment]
Another example where something like this would be useful:

```
tasks:
    - action: copy src=zones/foo.com dest=/var/named/data/foo.com
      notify: named reload zone named_zone=foo.com

notify:
    - name: named reload zone
      action: command rndc reload $named_zone
```

The above would allow one to trigger reload of a specific zone file as opposed to reloading all zones that named is configured for.
