### ISSUE TITLE
with_items variable name template broken (worked in 1.9.4)

### ISSUE THREAD

**Issue by robinro** [ansible/ansible#13584]
##### Ansible Version:

ansible 2.0.0 (f41dd578b340b76aa706af9540fd8fab2fbb0eb6)
##### Ansible Configuration:

self-packaged version based on above revision
##### Environment:

openSuSE Leap 42.1
##### Summary:

Substituting variable names based on other variables does not work in ansible 2.0.0 but used to work in 1.9.4.

This should either be fixed or stated more prominently in the Changelog as it breaks existing playbooks.
##### Steps To Reproduce:

Example playbook:

```
vars:
  packages_install_42:
    - bash
    - zsh

tasks:
- name: install stuff
  zypper: name={{item}} state=present
  with_items: packages_install_{{ansible_distribution_major_version}}
```
##### Expected Results:

Variable packages_install_42 is used, the packages bash and zsh are installed.
##### Actual Results:

The task fails:
`(item=[u'packages_install_42']) => {"failed": true, "item": ["packages_install_42"], "msg": "No provider of 'packages_install_42' found.\n", "rc": 104}`
