### ISSUE TITLE
ansible 2.0 runs setup for all plays when run with -t

### ISSUE THREAD

**Issue by nirik** [ansible/ansible#13602]
```
% cat master.yml

---
- include: /home/kevin/git/scrye-ansible/playbooks/one.yml
- include: /home/kevin/git/scrye-ansible/playbooks/two.yml
```

```
% cat playbooks/one.yml
- name: one playbook
  hosts: td
  gather_facts: True

  tasks:

  - name: test
    command: uptime
    tags:
    - one
```

```
% cat playbooks/two.yml
- name: two
  hosts: peven
  gather_facts: True

  tasks:

  - name: test
    command: uptime
    tags:
    - two
```

```
% ansible-playbook -u root -i inventory -t two master.yml (with 2.0)

PLAY [one playbook] ************************************************************

TASK [setup] *******************************************************************
ok: [td]

PLAY [two] *********************************************************************

TASK [setup] *******************************************************************
ok: [peven]

TASK [test] ********************************************************************
changed: [peven]

PLAY RECAP *********************************************************************
peven                      : ok=2    changed=1    unreachable=0    failed=0   
td                         : ok=1    changed=0    unreachable=0    failed=0   
```

```
% ansible-playbook -u root -i inventory -t two master.yml (with 1.9.4)

PLAY [two] ******************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [peven]

TASK: [test] ****************************************************************** 
changed: [peven]

PLAY RECAP ******************************************************************** 
test -------------------------------------------------------------------- 0.29s
peven                      : ok=2    changed=1    unreachable=0    failed=0   
```

It would be very nice if 2.0 didn't run setup on all the plays that don't include the tag you are running, this makes large included playbooks very slow.
