### ISSUE TITLE
Ansible 2.0 task variable precedence is lower than in documentation

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13614]
The task variable `remote_user` becomes overridden by the inventory variable `ansible_user`.

**Comment by jimi-c** [comment]
Hi @ThomasSteinbach, this is a case of mis-documentation I think. The difference here is that these variables are considered "magic" variables in the documentation, and as such have a higher precedence than the task despite the fact that they come from inventory. I agree this is a confusing topic, which is not explained well at all in the docs, so we'll look to fix this there rather than changing code.

**Comment by ThomasSteinbach** [comment]
Ah, ok @jimi-c. So these 'magic' variables are just a set of variables with higher precedence in general. But with reference to issue #13388 this leads me to the following problem: The basis is that I create a docker container, add it dynamically to the inventory and define the default user to connect to the container as follows:

```
- name: create jenkins container
  docker:
    name: aci_jenkins
    image: iteratechh/jenkins
    state: running

- name: add aci_jenkins to inventory
  add_host:
    name: aci_jenkins
    ansible_connection: docker
    ansible_user: jenkins
```

But now I have one task I want to execute within the container not as the _jenkins_ user but as _root_ user. I don't want to use become therefore, because setting the docker container user is the better way. So @abadger adviced me in a discussion in the PR #13424 to set the `remote_user` per task level, as follows:

```
- name: install git
  delegate_to: aci_jenkins
  remote_user: root
  apt:
    name: git
    state: present
```

But with the current implementation setting the `remote_user` per task level is not possible. Even if the `remote_user` inside the source code is in the array of variables meant to be changed per task level.

So what is the advantage of the 'magic' state of those variables? And how can I set the remote user for a specific task?

**Comment by bcoca** [comment]
In 2 you can set vars at the task level

```
- name: install git
  delegate_to: aci_jenkins
  vars:
     ansible_user: root
  apt:
    name: git
    state: present
```
