### ISSUE TITLE
[2.0] included task vars and default filter with omit results in 'omit placeholder'

### ISSUE THREAD

**Issue by basz** [ansible/ansible#13619]
Hi,

I have an included task (running stable-2.0 HEAD, but RC2 does the same) for which I would like to omit a variable with 

extra_parameters: "{{ apache_extra_parameters | default(omit) }}"

```
# play
  - include: "{{ playbook_dir }}/roles/provision.apache/tasks/create_vhost.yml"
    vars:
      extra_parameters: "{{ apache_extra_parameters | default(omit) }}"
```

```
# file roles/provision.apache/tasks/create_vhost.yml

 - debug: var=extra_parameters

TASK [debug] *******************************************************************
ok: [s01.xxxx] => {
    "extra_parameters": "__omit_place_holder__0f9e95c782a4eef2027a622d57fcf3a2e5b8e133"
}
```

Is the omit filter ment to be used with include_task vars like this? If so, this must be a bug...

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, note that `omit` is meant for module options, not for general variables.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by basz** [comment]
thanks, will do

**Comment by stevekuznetsov** [comment]
@bcoca 
As long as this issue is one of  the top hits on Google for this query term, might be nice to document what to do in this case (even if the documentation is just a link!)

In my case, I have a role that installs some RPMs that is agnostic to which RPMs it is installing, so I want to be able to call it from playbooks for different RPMs by providing it with the variables it needs to run for each one. 

Some of these variables are optional, and I want a simple `when: myvar is defined` check in my role to see if I need to take other actions depending on if these optional variables are passed in. 

Therefore, what I've come to doing looks like this:

``` yml
---
- name: ensure the call to this playbook is well-formed
  hosts: 'localhost'
  connection: 'local'
  become: 'no'
  gather_facts: 'no'

  pre_tasks:
    - name: ensure all required variables are set
      fail:
        msg: 'This playbook requires {{ item }} to be set.'
      when: item not in hostvars[inventory_hostname]
      with_items:
        - required_variable

- name: run the installer once
  hosts: 'localhost'
  connection: 'local'

  pre_tasks:
    - name: register role_required_variable
      set_fact:
        role_required_variable: '{{ required_variable }}'

    - name: register role_optional_variable
      set_fact:
        role_optional_variable: '{{ optional_variable }}'
      when: optional_variable is defined

  roles:
    - role: parameterized-install # this role uses the role_{required,optional}_variable variables
```

While this works fine, I don't particularly like it since:
- it is not parallel with the simple `| default(omit)` syntax used elsewhere
- it does not make it obvious that the facts being set are used by the particular role below

If there is a better way, I'd be happy to use it.
