### ISSUE TITLE
Ansible 2.x: variables were not passed to role

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13617]
I recognized a somewhat strange behavior (bug), it took me some hours to figure out, what's wrong. Let me explain it by the following example. We have three roles, each role comprising one file as following:

**/rolespath/role1/tasks/main.yml**

```

---
- name: print variable
  debug: msg="{{ role1_variable }}"
```

**/rolespath/role2/meta/main.yml**

```

---
dependencies:
  - role: role1
    role1_variable: "{{ role2_variable }}"
```

**/rolespath/role3/meta/main.yml**

```

---
dependencies:
  - role: role2
    role2_variable: "from role3"
```
## What is working

Now, when I call the **role2** within a playbook, everything works as expected. The playbook...

```
- name: calling role2 works
  hosts: localhost
  gather_facts: no
  roles:
    - role: role2
      role2_variable: "from playbook"
```

... would lead to the following correct output:

```
PLAY [calling role 2 works] ***********************************

TASK [role1 : print variable] *********************************
ok: [localhost] => {
    "changed": false, 
    "msg": "from playbook"
}
```
## What does not work

But when I call the **role3**, the playbook...

```
- name: calling role3 fails
  hosts: localhost
  gather_facts: no
  roles:
    - role: role3
```

... would lead to the following error output:

```
PLAY [calling role3 fails] ***********************************

TASK [role1 : print variable] ********************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! ERROR! 'role2_variable' is undefined"}
```
## Further description

It doesn't matter If you set the _role2_variable_ within the third roles _meta/main.yml_ directly, as shown in the example, or introduce a _role3_variable_. Even when you introduce a further **role4** which calls **role3** and setting the _role3_variable_ (and even further roles in this scheme), the error remains that `'role2_variable' is undefined`.
