### ISSUE TITLE
Ansible 2.x: local connector misbehaves when using with_items

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#13624]
Ansible crashes when creating links with_items and using `ansible_connection=local`. Here an example playbook for reproducing the behavior:

```
- name: the last task will throw an error
  hosts: localhost
  gather_facts: no

  tasks:
    - name: create files - that will work
      copy:
        content: "test"
        dest: "/tmp/{{ item }}"
      with_items:
        - testfile1
        - testfile2

    - name: create links - that will crash
      become: yes
      file:
        src: "/tmp/{{ item }}"
        dest: "/tmp/{{ item }}link"
        state: link
      with_items:
        - testfile1
        - testfile2
```

The output is:

```
PLAY [the last task will throw an error] ***********************************

TASK [create files - that will work] *************************************************************
ok: [localhost] => (item=testfile1)
ok: [localhost] => (item=testfile2)

TASK [create links - that will crash] *************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! privilege output closed while waiting for password prompt:\nBECOME-SUCCESS-smnurvzoeqwqcapbnmmyrhlaautxdumn\n{\"src\": \"/tmp/testfile2\", \"group\": \"root\", \"uid\": 0, \"dest\": \"/tmp/testfile2link\", \"changed\": false, \"owner\": \"root\", \"state\": \"link\", \"gid\": 0, \"mode\": \"0777\", \"invocation\": {\"directory_mode\": null, \"force\": false, \"remote_src\": null, \"path\": \"/tmp/testfile2link\", \"owner\": null, \"follow\": false, \"group\": null, \"state\": \"link\", \"content\": null, \"serole\": null, \"diff_peek\": null, \"setype\": null, \"dest\": \"/tmp/testfile2link\", \"selevel\": null, \"original_basename\": null, \"regexp\": null, \"validate\": null, \"src\": \"/tmp/testfile2\", \"seuser\": null, \"recurse\": false, \"delimiter\": null, \"mode\": null, \"backup\": null}, \"size\": 14}\n"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1 
```

I think the local connector misbehaves with more then just the _file_ module, when using `with_items`. I have another issue open ([pip module does not work with_items in Ansible 2.0 #2552](https://github.com/ansible/ansible-modules-core/issues/2552)) where i suspected the _pip_ module having problems `with_items`. However, the general error remains the same in both issues:

```
ERROR! privilege output closed while waiting for password prompt
```

During the investigation of the other issue, I found out that the error for it was introduced with commit https://github.com/ansible/ansible/commit/53e86f3130145ce40606cec32aef2858756a20ab, which was merged with PR https://github.com/ansible/ansible/pull/13261. I haven't checked if it is the same for this issue, but it could be a first trace.
