### ISSUE TITLE
Add support to create nested groups using group_by

### ISSUE THREAD

**Issue by tersmitten** [ansible/ansible#13635]
For instance using the syntax below:

```
    - name: create dynamic active / passive groups
      group_by:
        key: "tiers-production-app-mysql-replication-master-{{ 'active' if hostvars[inventory_hostname]['ansible_eth1_1'] is defined else 'passive' }}"
        parent: 'tiers-production-app-mysql-replication-master'
```
