### ISSUE TITLE
Deprecation warning with args form

### ISSUE THREAD

**Issue by lberruti** [ansible/ansible#13644]
##### Issue Type:

  Bug Report
##### Ansible Version:

v2.0.0-0.8.rc3 
ansible-playbook 2.0.0 (detached HEAD a2120a3d63) last updated 2015/12/22 23:24:58 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 5777c28f50) last updated 2015/12/22 23:24:58 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 14b81df29c) last updated 2015/12/22 23:24:58 (GMT +200)
  config file = /Users/nemo/Works/siransible/ansible.cfg
  configured module search path = library
##### Ansible Configuration:

none
##### Environment:

Debian 7
##### Steps To Reproduce:

ansible-playbook args3.yml

``` yaml
==> args3.yml <==

---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    my_dirs:
      - { path: /tmp/3a, state: directory, mode: 755 }
      - { path: /tmp/3b, state: directory, mode: 700 }
  tasks:
    - file:
      args: '{{item}}'
      with_items: my_dirs
```
##### Expected Results:

```

PLAY ***************************************************************************

TASK [file] ********************************************************************
changed: [localhost] => (item={u'path': u'/tmp/3a', u'state': u'directory', u'mode': 755})
changed: [localhost] => (item={u'path': u'/tmp/3b', u'state': u'directory', u'mode': 700})

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
##### Actual Results:

```

PLAY ***************************************************************************

TASK [file] ********************************************************************
[DEPRECATION WARNING]: Using variables for task params is unsafe, especially if the variables come from an external source like facts. This
feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [localhost] => (item={u'path': u'/tmp/3a', u'state': u'directory', u'mode': 755})
changed: [localhost] => (item={u'path': u'/tmp/3b', u'state': u'directory', u'mode': 700})

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
