### ISSUE TITLE
Environment variables values are printed in debug mode even when no_log is set 

### ISSUE THREAD

**Issue by akazakov** [ansible/ansible#13664]
How to reproduce:

```

---
- hosts: all
  connection: local
  gather_facts: not

  tasks:
    - shell: echo $PARAM
      environment:
        PARAM: SECRET_LEAKING
      no_log: yes
```

```
➜   ansible-playbook -i localhost, vars.yml -vvvv

PLAY [all] ******************************************************************** 

TASK: [command echo $PARAM] *************************************************** 
.... 
EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 PARAM=SECRET_LEAKING /usr/bin/python /Users/artemkazakov/.ansible/tmp/ansible-tmp-1450975664.13-163129283806168/command; rm -rf /Users/artemkazakov/.ansible/tmp/ansible-tmp-1450975664.13-163129283806168/ >/dev/null 2>&1']
changed: [localhost] => {"censored": "results hidden due to no_log parameter", "changed": true, "rc": 0}

```

See PARAM=SECRET_LEAKING  in the output.
Expected: not printing the env params
