### ISSUE TITLE
Delegate_to & with_items & groups.all fails with "apt" module.

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13666]
# Overview

It seems delegate_to and with_items fails to properly split target hosts when using "apt" module.
The task is not divided between different members but delegated to an unexistent one (FQDN : host1,host2,hostN...) and so the hostname resolution fails.

I'm using Ansible 1.7.2
# Example tasks

This task fails everytime :

``` yaml
- name: Installing NRPE on hosts.
  apt:
      name=nagios-nrpe-server
  delegate_to: "{{ item }}"
  with_items: groups.all
```

This one works: 

``` yaml
- name: Installing NRPE on hosts.
  shell:
      apt-get install -y nagios-nrpe-server
  delegate_to: "{{ item }}"
  with_items: groups.all
```
# Playbook output

```
ansible-playbook -i hosts site.yml -vvvv --start-at-task "Installing NRPE on hosts."
[snip]
TASK: [shinken | Installing NRPE on hosts.] *********************************** 
<HOST1_FQDN,HOST2_FQDN> ESTABLISH CONNECTION FOR USER: root
<HOST1_FQDN,HOST2_FQDN> REMOTE_MODULE apt name=nagios-nrpe-server
<HOST1_FQDN,HOST2_FQDN> EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/home/REDACTED/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'User=root', '-o', 'ConnectTimeout=10', u'HOST1_FQDN,HOST2_FQDN', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1450979972.33-158339587471846 && echo $HOME/.ansible/tmp/ansible-tmp-1450979972.33-158339587471846'"]
fatal: [mon.sk4.nz -> {{ item }}] => SSH encountered an unknown error. The output was:
OpenSSH_6.7p1 Debian-5, OpenSSL 1.0.1k 8 Jan 2015
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/home/sk4nz/.ansible/cp/ansible-ssh-HOST1_FQDN,HOST2_FQDN-22-root" does not exist
ssh: Could not resolve hostname HOST1_FQDN,HOST2_FQDN: Name or service not known
```
