### ISSUE TITLE
Casting to boolean in 'vars' doesn't stick

### ISSUE THREAD

**Issue by dunn** [ansible/ansible#13679]
This might be a limitation of YAML; if so maybe there's nothing to be done.

The following two versions of `main.yml` ought to function identically:

``` yaml

---
- name: test
  hosts: all
  vars:
    suds: "{{ suds | bool }}"
  tasks:
    - name: fails
      become: suds
      command: echo hello
```

``` yaml

---
- name: test
  hosts: all
  tasks:
    - name: fails
      become: "{{ suds | bool }}"
      command: echo hello
```

With the following command, both should fail with `sudo: a password is required`; but on 2.0.0-0.8.rc3 only the latter does:

```
ansible-playbook main.yml --connection=local -i hosts -vv --extra-vars 'suds=True'
```

The hosts file is just this:

``` ini
[test]
test ansible_python_interpreter=/usr/local/bin/python
```

This is on El Capitan 10.11.2
