### ISSUE TITLE
Strange with_items parsing

### ISSUE THREAD

**Issue by Glueon** [ansible/ansible#13672]
I am using ansible 1.9

Using `lineinfile` module with `with_items` loop I faced some errors in parsing these items. By simplifying the string it fails on I came up to this one:

```
    lineinfile: dest=/home/app/.bashrc state=present line="{{ item }}"
    with_items:
    - '" -"'
```

This fails with:

```
failed: [backend1] => (item=" \-") => {"failed": true, "item": "\" \\-\""}
msg: this module requires key=value arguments (['dest=/home/app/.bashrc', 'state=present', 'line=', '-'])
```

If you remove a space before minus sign or replace it with an char it starts working.
The original line I started with was:

```
- 'eval "$(pyenv init -)"'
```

Also it seems that problem could be solved by changing double quote to single ones:

```
    lineinfile: dest=/home/app/.bashrc state=present line='{{ item }}'
```

But still I am not sure if this behavior is not wrong.

**Comment by bcoca** [comment]
can you try?:

```
 - ['" -"']
```

**Comment by Glueon** [comment]
Does not seem to help:

```
failed: [server1] => (item=" -") => {"failed": true, "item": "\" -\""}
msg: this module requires key=value arguments (['dest=/root/.bashrc', 'state=present', 'line=', '-'])
```

Used with:

```
---
- name: Test
  hosts: all
  tasks:
  - name: Foo
    lineinfile: dest=/root/.bashrc state=present line="{{ item }}"
    with_items:
    - ['" -"']
```

**Comment by danlamanna** [comment]
I came across this same issue, running version 2.0.0.2 of Ansible. Wrapping my `{{ item }}` in single quotes seem to have worked.

**Comment by Yannig** [comment]
Try this one:

``` yaml
  - name: Foo
    lineinfile: dest=/tmp/toto state=present line="{{ item }}"
    with_items:
    - ["{{' -'}}"]
```
