### ISSUE TITLE
Problems with variables

### ISSUE THREAD

**Issue by chrisRidgers** [ansible/ansible#13686]
I don't know if I've missed some documentation somewhere or gone against common sense but I've spent some time banging my head against some errors to do with my variables.

I've had `dict has no attribute...` as well as recursive 'templating errors' but the issue seems to have gone away now that I've renamed the variable in my yaml file.

So my setup was:

Inventory with a group called localmachine with my 127.0.0.1 ip address, and group_vars/localmachine.yml file.

Within that variable file I had something like:

```
# file: group_vars/localmachine.yml

---
environment:
    user:
        name: "{{ ansible_env.USER }}"
        group: staff

executables:
    brew: /usr/local/bin/brew
    cask: /usr/local/bin/brew cask
    vim: /usr/local/bin/vim

directories:
    etc: /usr/local/etc
    var: /usr/local/var

ssh_known_hosts:
    - bitbucket.org

ruby:
    version: "{{ ruby.version }}"
rbenv:
    global: "{{ ruby.version }}"
```

And I was accessing environment.user.name for use in the authorized_keys module.  This would then error out complaining that my dict didn't have a user attribute.

Sure enough, sticking a: `debug: var=environment"` into my task showed an environment dict with no contents.

I've not seen any special reservation of the environment variable name anywhere, but I'm fairly new to ansible:  the problem went away when I renamed the variable to env_stored_variables.

Just thought I'd drop this somewhere in case anyone else runs into a similar issue.
