### ISSUE TITLE
Copy module fails in Ansible v2.1.0

### ISSUE THREAD

**Issue by Anonymouslemming** [ansible/ansible#13698]
Copy module is not working as expected in Ansible v2.1.0. The following worked in v1.9.

```
- hosts: dhcp
  become: yes
  tasks:
  - name: Copy files to dhcp hosts
    copy: src=/myconf dest=/etc/dhcp/dhcpd.conf owner=root group root mode="0644"
    notify:
        - restart isc-dhcp-server
```

Expected result: Copy should succeed from control machine to dhcp hosts

Actual result: Playbook fails with the following message:

`ERROR! this task 'copy' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta`

It's possible that I've missed some change in documentation, but the most recent document I can find at http://docs.ansible.com/ansible/copy_module.html still has src and dest values.
