### ISSUE TITLE
Feature: ability to specify custom template for item "label" in output

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#13710]
Currently, when you use `with_items` (or related functions, such as `with_dict`) with a complex data structure (as opposed to a simple list), the entire structure gets displayed in the console output, unless you use `no_log`. This results in output like the following:

```
ok: [raz1] => (item={u'extra_options': u'-o PageSize=Letter', u'model': u'gutenprint.5.2://brother-hl-2060/expert', u'uri': u'socket://192.168.0.242:9100', u'name': u'Brother', u'location': u'Brother printer, office'})
```

Ideally, you should be able to specify a custom template string to use as the "label" for each item. For a var structure and task like the following:

```
cups_printers:
- name: Brother
  uri: "socket://192.168.0.242:9100"
  model: "gutenprint.5.2://brother-hl-2060/expert"
  location: "Brother printer, office"
  extra_options: "-o PageSize=Letter"
```

and

```
- name: check for printer
  shell: lpstat -p '{{ item.name }}'
  register: printer_present
  with_items: "{{ cups_printers }}"
  item_label: "{{ item.name }}"
```

the output would look like:

```
ok: [raz1] => (item=Brother)
```

rather than the output at the beginning of this issue.

The `default.py` stdout callback plugin could easily be modified to check for the `item_label` field in the result before the `item` field to support this.
