### ISSUE TITLE
Unnecessary \n in ansible-playbook run output

### ISSUE THREAD

**Issue by bessarabov** [ansible/ansible#13714]
Here is a simple playbook:

```
#!/usr/bin/env ansible-playbook -i hosts

---
- hosts: sample
  gather_facts: false
  sudo: yes

  tasks:

    - file: >
        path=/tmp/foo
        state=absent

    - file: path=/tmp/bar state=absent
```

When I run It I see:

```
$ ./sample

PLAY [sample] *****************************************************************

TASK: [file path=/tmp/foo state=absent
] **************************************
ok: [host]

TASK: [file path=/tmp/bar state=absent] ***************************************
ok: [host]

PLAY RECAP ********************************************************************
host                       : ok=2    changed=0    unreachable=0    failed=0

$
```

In the first task output there is new line (after the word `absent`) that can be removed to make the output better:

```
TASK: [file path=/tmp/foo state=absent
] **************************************
ok: [host]
```

PS I'm using ansible 1.9.4 installed from brew on my mac.
