### ISSUE TITLE
Ansible docker: error pulling images

### ISSUE THREAD

**Issue by fabriziopandini** [ansible/ansible#13723]
I'm using a playbook with a task that pulls docker registry image:

``` yaml
- name: Docker registry container
  docker:
    name: registry
    image: registry:2
    ports:
    - "5000:5000"
    volumes:
    - /var/lib/docker-registry:/registry:rw
    env:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
    state: started
    restart_policy: always
```

The pull operation completes:

```
{\"status\":\"Status: Downloaded newer image for docker.io/registry:2\"}
```

However the task fails with:

"failed": true, "status": ""
msg: Unrecognized status from pull.

NB. the same happen with other images, like fi. nginx:1.9
