### ISSUE TITLE
Role runs on failed host if second role has include-statement

### ISSUE THREAD

**Issue by chlunde** [ansible/ansible#13749]
##### Issue Type

Bug Report
##### Ansible Version

2.0 from the "stable-2.0" branch, commit fcd074d40f32ef52ed286678293984125ff51008

```
$ ansible --version
ansible 2.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration

No changes
##### Environment

RHEL 7
##### Summary

In a multi-role playbook with include-statements, it seems all that ansible 2.0 fails to preserve the list of failed hosts. The result is that tasks are executed on hosts with failures.

Ansible 1.9.4 does not have this behavior.
##### Steps To Reproduce:

```
$ tree
├── included.yml
├── inventory
├── playbook.yml
└── roles
    ├── r1
    │   └── tasks
    │       └── main.yml
    └── r2
        └── tasks
            └── main.yml

$ cat inventory
app01
app02

$ ansible-playbook -i inventory playbook.yml
```
###### playbook.yml

``` yaml

---
- hosts: all
  serial: 100%

  roles:
      - r1
      - r2
```
###### roles/r1/tasks/main.yml

``` yaml

---
- name: "shell command failing on one node"
  shell: "test $(hostname --short) == app01"
```
###### roles/r2/tasks/main.yml

``` yaml

---
- include: included.yml
- command: echo should not run
```
###### included.yml

``` yaml

---
- command: echo foo
```
##### Expected Results:

As `r1` fails on host app02, I expected it to not run `r2`.  This is the behavior in 1.9.4.
##### Actual Results:

When `r2` has an `include`-statement `r2` runs on both hosts, without it it only runs on app01.
###### With include:

```
TASK [r1 : shell command failing on one node] **********************************
fatal: [app02]: FAILED! ...
changed: [app01]

TASK [r2 : include] ************************************************************
included: /home/scarllun/bug/included.yml for app01

TASK [r2 : command] ************************************************************
changed: [app01]
included: /home/scarllun/bug/included.yml for app02

TASK [r2 : command] ************************************************************
changed: [app02]

TASK [r2 : command] ************************************************************
changed: [app02]
changed: [app01]
```
###### Without include:

```
TASK [r1 : shell command failing on one node] **********************************
fatal: [app02]: FAILED! ...
changed: [app01]

TASK [r2 : command] ************************************************************
changed: [app01]
```
