### ISSUE TITLE
Play continues after a failed task when `any_errors_fatal` is set

### ISSUE THREAD

**Issue by chlunde** [ansible/ansible#13744]
##### Issue Type

Bug Report
##### Ansible Version

2.0 from the "stable-2.0" branch, commit fcd074d40f32ef52ed286678293984125ff51008

```
$ ansible --version
ansible 2.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration

No changes
##### Environment

RHEL 7
##### Summary

Play continues after a failed task when `any_errors_fatal` is set.
##### Steps To Reproduce:

```
$ cat inv
app01
app02

$ ansible-playbook -i inv stop.yml
```

``` yaml

---
- hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  serial: 100%
  tasks:
    - name: "shell command failing on one node"
      shell: "test $(hostname --short) == app01"

    - name: stop before this
      command: echo noooooooo
```
##### Expected Results:

I expected the playbook to stop after the executing the first task on all nodes, before the "stop before this" task, as it does on 1.9.4.  The documentation says:

> The `any_errors_fatal` play option will mark all hosts as failed if any fails, causing an immediate abort"
##### Actual Results:

The second task is executed on the node which completed the first task without error:

```
$ ansible-playbook -i inv stop.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [app02]
ok: [app01]

TASK [shell command failing on one node] ***************************************
fatal: [app02]: FAILED! => {"changed": true, "cmd": "test $(hostname --short) == app01", "delta": "0:00:00.005278", "end": "2016-01-07 01:38:57.751466", "failed": true, "rc": 1, "start": "2016-01-07 01:38:57.746188", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
changed: [app01]

TASK [stop before this] ********************************************************
changed: [app01]

PLAY RECAP *********************************************************************
app01                      : ok=3    changed=2    unreachable=0    failed=0
app02                      : ok=1    changed=0    unreachable=0    failed=1
```
