### ISSUE TITLE
[Filter in YAML] - no filter named 'regex_escape'

### ISSUE THREAD

**Issue by Oliboy50** [ansible/ansible#13759]
``` yml
- name: Add ip/hostname couples to /etc/hosts file
  lineinfile:
    state: present
    dest: /etc/hosts
    regexp: "^(?:[0-9]{1,3}{{ '.' | regex_escape() }}){3}[0-9]{1,3} {{ item.hostname | regex_escape() }}$"
    line: "{{ item.ip }} {{ item.hostname }}"
```

``` bash
TASK: [etc-hosts | Add ip/hostname couples to /etc/hosts file] **************** 
fatal: [web] => Failed to template ^(?:[0-9]{1,3}{{ '.' | regex_escape }}){3}[0-9]{1,3} {{ item.hostname | regex_escape }}$: template error while templating string: no filter named 'regex_escape'
```

Ansible version: 1.9.4

This filter was found in http://docs.ansible.com/ansible/playbooks_filters.html

EDIT:
After deeper researches, I realize that I get this error for every filters, not only `regex_escape`.

My question might be "how to use filter in YAML tasks?"...
