### ISSUE TITLE
Ansible vault: surface keys inside as clear-text

### ISSUE THREAD

**Issue by abourget** [ansible/ansible#13752]
One great aspect of Ansible, I think, is grep-ability of the repo to find all links in applications.

However, when some variables are encrypted through ansible-vault, you can't grep them anymore, to know which files you need to change, that will impact.

It would be cool to have:

```
this_sensitive: "information"
those:
  very: "sensitive"
  informations: "stay in here"
```

be encrypted to something like:

```
$ANSIBLE_VAULT;1.1;AES256
38465432346567876543212345676563666162396264346236567867564639643263432534356362

---
this_sensitive: ~
those:
  very: ~
  informations: ~
...

:boom: ! how awesome would that be ?! :) You could grep the repo, and discover at least that there are such keys in the encrypted file.

```
