### ISSUE TITLE
when conditional is ignored if with_items contains undefined value

### ISSUE THREAD

**Issue by jimmymccrory** [ansible/ansible#13791]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Environment:

Ubuntu 14.04
##### Summary:

A task's `with_items` seem to be evaluated  before its `when` clause.
If a variable used within an item is undefined, the task will fail even if the when clause says it should only run when that same variable is defined.
##### Steps To Reproduce:

```

---
- hosts: localhost
  tasks:
  - name: Copy test file
    copy:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
      owner: "root"
      group: "root"
      mode: "{{ item.mode }}"
    with_items:
      - { src: "{{ test_src }}", dest: "/tmp/test", mode: "0644" }
    when: test_src is defined
```
##### Expected Results:

Task is skipped since `test_src` is undefined

Worked as expected in Ansible 1.9.4

```
ansible 1.9.4
  configured module search path = None

TASK: [Copy test file] ********************************************************
skipping: [localhost] => (item={'dest': '/tmp/test', 'src': u'{# test_src #}', 'mode': '0644'})
```
##### Actual Results:

```
TASK [Copy test file] **********************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'test_src' is undefined"}
```
