### ISSUE TITLE
`copy content={{ binary_blob OR base_64_encoded | b64decode }} dest=file.ext` will always be utf8 encoded on disk

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#13794]
### Meta
- **Issue Type**: Bug Report
- **Ansible Version**: 1.9.4
- **Ansible Configuration**: N/A
- **Environment**: running on OSX 10.11.2 and _brew_ python 2.7.10, managing Centos 6.5
### Summary:

We have to mange secrets which are to be stored in files on the managed machine. The secrets are binary files.

Our approach so far was to use the vault to store all kinds of secrets. Binary secrets are not a particular problem, and could be handled using the _yaml_ `!binary` tag, or using a plain base64 encoded string along with a jinja `b64decode`.

A sample yaml file would look like this:

``` yaml
binary_secret_blob: !!binary "\
  AAAAAQAAAAAEABcAEP7aQKdR8FbzpDyK2pSeeS8="

binary_secret_base64: |
  AAAAAQAAAAAEABcAEP7aQKdR8FbzpDyK2pSeeS8=
```

A typical task to handle the data provided above looks like this:

``` yaml
- name: write binary blob secret
  copy: content={{ binary_secret_blob }} dest=/etc/secret-from-blob.x

- name: write base64 encoded secret
  copy: content={{ binary_secret_base64|b64decode }} dest=/etc/secret-from-base64.x
```

However, when using `copy content={{ ... }} dest=file.ext`, the destination file will not match the source data, as it has been utf-8 encoded.
### Steps To Reproduce

Sorry for not providing a ready-made playbook or script, but I couldn't find an easy way to `ansible init` a new project and go from there.

However, the data provided in the summary can be integrated into any test-playbook.
### Expected Results

``` bash
# on linux, use -d instead of -D
$ echo AAAAAQAAAAAEABcAEP7aQKdR8FbzpDyK2pSeeS8= | base64 -D | md5sum
aa8923e2b8ff959392c803c308d1a56f  -
```

The md5sum of the binary blob is `aa8923e2b8ff959392c803c308d1a56f`, and should be similar for the file produced by ansible. Right now it's not the case.
### Actual Results

I didn't re-run the process with the test-data, so I have nothing for you here. However, I looked into the code and found some interesting bits - see next section.
### Where the problem could be located at

A little bit of digging led me to [`_create_content_tempfile(...)`](https://github.com/ansible/ansible/blob/1b7d3f289816666ba18b25d81fe34d8c956785cc/lib/ansible/plugins/action/copy.py#L295), which seems to convert the content to bytes. However, this seems to enforce the unicode conversion, replacing invalid characters with _something_ (?). This is the reason for the inability to use `{{ base64_content | b64decode}}`, just in case only the yaml `!binary` tag is not handled correctly.

Also it seems that in the moment a binary blob (created with yaml's `!binary` tag) [is queried](https://github.com/ansible/ansible/blob/1b7d3f289816666ba18b25d81fe34d8c956785cc/lib/ansible/plugins/action/copy.py#L43) from the arguments list, in py2.7 you get a `unicode` object right away, which instead should be `str` (or `bytes` in py3).
### Workaround

You can write a temporary file and convert that from base64 to binary using system programs. An example playbook could look like this:

``` yaml
- name: write base64 encoded secret
  copy: content={{ binary_secret_base64 }} dest=/etc/secret-from-base64.x.base64

- name: decode the secret
  shell: /usr/bin/base64 -d /etc/secret-from-base64.x.base64 > /etc/secret-from-base64.x && rm /etc/secret-from-base64.x.base64
  args:
    creates: /etc/secret-from-base64.x
```

Unfortunately, I couldn't find a way to control the standard input of `command` or `shell`, which would have made the workaround less convoluted.
