### ISSUE TITLE
Command "args:creates:" is ignored in async mode

### ISSUE THREAD

**Issue by hxw** [ansible/ansible#13828]
When command is used in async mode the args form of creates appears to be ignored.  However the embedded `creates=file` does work.

In the code below the first two items  (initialise,A) will _always_ report changed and their commands are run.  The third case (B) never runs.  Which shows that async code is only ignoring the args format. 

```
- name: testing initialise
  command: >-
    touch /tmp/testing_file
  args:
    creates: /tmp/testing_file
  async: 200
  poll: 10

- name: testing should not run A
  command: >-
    touch /tmp/testing_file
  args:
    creates: /tmp/testing_file
  async: 200
  poll: 10

- name: testing should not run B
  command: >-
    touch /tmp/testing_file
    creates=/tmp/testing_file
  async: 200
  poll: 10
```
