### ISSUE TITLE
[2.0] Jinja2 comment included in the template output

### ISSUE THREAD

**Issue by bborysenko** [ansible/ansible#13831]
##### Issue Type:

Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0.1
  config file = /Users/bbo/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Blank `ansible.cfg` with default configuration.
##### Environment:

MacOS X 10.11.2 (El Capitan)
##### Summary:

[Jinja2 comments](http://jinja.pocoo.org/docs/dev/templates/#comments) syntax doesn't work in templates.
##### Steps To Reproduce:

playbook:

```

---
- hosts: all
  tasks:
    - template:
        src: template-with-comment.j2
        dest: /tmp/test-jinja2-comment
```

template `template-with-comment.j2`:

```
It should be present on rendered template
{# Jinja2 Comment #}
```
##### Expected Results:

```
$ cat /tmp/test-jinja2-comment
It should be present on rendered template
```
##### Actual Results:

```
$ cat /tmp/test-jinja2-comment
It should be present on rendered template
{# Jinja2 Comment #}
```
