### ISSUE TITLE
[2.0] Homebrew hangs

### ISSUE THREAD

**Issue by SteveEdson** [ansible/ansible#13835]
Since updating to Ansible 2.0, the following task hangs and never completes:

```
- name: Install packages from Homebrew
  homebrew: name={{ item }} state=present update_homebrew=yes
  with_items:
    - caskroom/cask/brew-cask
    - php70
    - speedtest_cli
    - httpie
    - exiftool
    - git-extras
    - ngrok
    - pandoc
    - tree
    - composer
    - node
    - q
    - git-cal
```

The previous task of tapping formulas works fine.

**Comment by SteveEdson** [comment]
Actually, it does eventually pass, its a later task that fails with the error:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! privilege output closed while waiting for password prompt:\nBECOME-SUCCESS-jvtjhihygpkzkrfyzfzolfxyfcauczji\n{\"invocation\": {\"module_args\": {\"executable\": null, \"name\": \"gulp\", \"global\": true, \"ignore_scripts\": false, \"state\": \"present\", \"production\": false, \"registry\": null, \"version\": null, \"path\": null}}, \"changed\": false}\n"}
```

```
- name: Install NPM packages
  npm: name={{ item }} state=present global=yes
  with_items:
    - bower
    - gulp
  become: yes
```
