### ISSUE TITLE
global name 'do_encrypt' is not defined

### ISSUE THREAD

**Issue by andrefernandes** [ansible/ansible#13861]
(Ansible 2.0)
Trying to encrypt an input prompt with Passlib results in an error:

Unexpected Exception: global name 'do_encrypt' is not defined
the full traceback was:

Traceback (most recent call last):
  File "/usr/bin/ansible-playbook", line 85, in <module>
    sys.exit(cli.run())
  File "/usr/lib/python2.7/site-packages/ansible/cli/playbook.py", line 150, in run
    results = pbex.run()
  File "/usr/lib/python2.7/site-packages/ansible/executor/playbook_executor.py", line 117, in run
    play.vars[vname] = display.do_var_prompt(vname, private, prompt, encrypt, confirm, salt_size, salt, default)
  File "/usr/lib/python2.7/site-packages/ansible/utils/display.py", line 310, in do_var_prompt
    result = do_encrypt(result, encrypt, salt_size, salt)
NameError: global name 'do_encrypt' is not defined

My playbook goes like this:

```
vars_prompt:
  - name: "pwd"
    prompt: "Enter password"
    private: yes
    encrypt: "sha512_crypt"
    salt_size: 7
```

Using CentOS 7.2, tried with passlib installed with "yum" and with "pip". Same error.
