### ISSUE TITLE
Bug report: Bad instruction + unicode result in Unexpected Exception

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#13899]
##### Ansible Version:

Devel
##### Ansible Configuration:

empty
##### Environment:

empty
##### Summary:

A bad instruction with unicode result in Unxpected exception.
##### Steps To Reproduce:

Take the following playbook:

``` yaml

---

- name: "error parsing"
  hosts: localhost
  tasks:
    - fail: "Bad parsing héhé"
```
##### Expected Results:

```
ERROR! this task 'fail' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta
```
##### Actual Results:

```
ansible-playbook error-parsing.yml 
Unexpected Exception: 'ascii' codec can't decode byte 0xc3 in position 278: ordinal not in range(128)
```
