### ISSUE TITLE
failed_when directive does not accept lists

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#13905]
##### Issue Type:

Bug Report
##### Ansible Version:

2.0.0.1
##### Environment:

ubuntu 14.04
##### Summary:

The `failed_when` module does not support lists anymore
##### Steps To Reproduce:

```
- hosts: localhost
  tasks:
    - name: hello
      command: "/dev/null"
      register: myresult
      failed_when:
        - "myresult == 1"
        - "myresult == 2"
```
##### Expected Results:

pass
##### Actual Results:

> ERROR! The field 'failed_when' is supposed to be a string type, however the incoming data structure is a <class 'ansible.parsing.yaml.objects.AnsibleSequence'>

**Comment by bcoca** [comment]
need to check all 'when's to make sure they all behave this way

**Comment by rossey** [comment]
@profhase this is a work around I've implemented

```
- hosts: localhost
  tasks:
    - name: hello
      command: "/dev/null"
      register: myresult
  failed_when: "{{ item }}"
  with_items:
    - "myresult == 1"
    - "myresult == 2"
```
