### ISSUE TITLE
ansible 2.0.0.1 does not trigger handlers. ansible 1.9.4 does.

### ISSUE THREAD

**Issue by sammerry** [ansible/ansible#13918]
When pull provisioning a host ansible2 does not run handlers on change. Pip installing ansibe 1.9.4 triggers the same handlers with the exact same command.

`sudo ansible-pull -U git@github.com/mygit/project.git -C master playbook/main.yml --purge --force`

```
- hosts: production
  tasks:

    - apt: name=some_package state=latest
      notify:
        - apt notification

  handlers:
    - include: handlers/main.yml
```
