### ISSUE TITLE
Strange things with first_available_file

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#1391]
When I write a playbook like this:

```
  - name: Deploy process script
    copy: src=process dest=/etc/postfix/process owner=root mode=0750

  - name: Deploy postfix main.cf
    template: src=${item} dest=/etc/postfix/main.cf owner=root mode=0440
    first_available_file:
        - /etc/ansible/play/postfix/main.cf.in=${ansible_hostname}
        - /etc/ansible/play/postfix/main.cf.in
    notify:
        - restart postfix
```

with the copy I do get a file relative to the playbook YAML file.

The part with the first_available_file requires the full path. When I use a relative path here I get an error.

```
TASK: [Deploy postfix main.cf] ********************* 
fatal: [master] => {'msg': 'could not find src in first_available_file list', 'failed': True}
fatal: [master] => {'msg': 'could not find src in first_available_file list', 'failed': True}

FATAL: all hosts have already failed -- aborting
```

Using the absolute path makes things work. 
I can't find any documentation on this difference so it feels like a bug.

I propose to make the relative path possible for the first_available_file part as well (if at all possible in the code).
