### ISSUE TITLE
docker module fails to restart container

### ISSUE THREAD

**Issue by andrenarchy** [ansible/ansible#13926]
Ansible 2.0.0.2 fails to restart a docker container with the error message

```
RUNNING HANDLER [docker-registry : Restart docker registry] ********************
fatal: [dr-frankenstein]: FAILED! => {"changed": true, "failed": true, "msg": "Docker API Error: no such id: effe8c8defc85a041802754453cd5345aa8b0781bed2cd5c6024b2e8b4aeff1c"}
```

I use it in a role `docker-registry` with the following configuration:

``` yaml

---
# roles/docker-registry/tasks/main.yml

- name: Copy config.yml for docker registry
  template: src=config.yml.j2 dest=/etc/docker_registry.yml
  notify: Restart docker registry

- name: Add docker registry container
  docker:
    name: docker-registry
    image: registry:2
    state: started
    ports: 127.0.0.1:5000:5000
    restart_policy: always
    volumes:
    - /etc/docker_registry.yml:/etc/docker/registry/config.yml
```

``` yaml

---
# roles/docker-registry/handlers/main.yml

- name: Restart docker registry
  docker:
    name: docker-registry
    image: registry:2
    state: restarted
```

The target host runs docker 1.9.1 and the ansible machine uses docker-py 1.6.0.

---

Stopping and starting the container in 2 steps works around the issue:

``` yaml

---
- name: Restart docker registry
  docker:
    name: docker-registry
    image: registry:2
    state: stopped
  notify: Start docker registry

- name: Start docker registry
  docker:
    name: docker-registry
    image: registry:2
    state: started
```
