### ISSUE TITLE
Behaviour changed in local_action + set_fact + run_once in 2.0.x targetting multiple servers?

### ISSUE THREAD

**Issue by ricardclau** [ansible/ansible#13921]
**Issue Type:**
Bug report

**Ansible Version:** 
2.x

**Ansible Configuration:**
default homebrew installation, nothing changed

**Environment:**
MacOSX ElCapitan

**Summary:**
Behaviour changed in local_action + set_fact + run_once in 2.0.x when targetting multiple servers?

**Expected Results:** 
It stays working as it was before, set the fact once, variable can be used in all servers

**Actual Results:**
variable is only available in the first server

**Steps To Reproduce:**

We have noticed a change of behaviour when executing once a local_action which sets a fact from 1.9 to 2.0

With this code targetting 2 or more boxes:

```
- name: ANSISTRANO | Get release version
  local_action:
    set_fact ansistrano_release_version="{{ lookup('pipe', 'date -u +%Y%m%d%H%M%SZ') }}"
  run_once: true
  when: ansistrano_release_version is not defined

- name: ANSISTRANO | Get release path
  command: echo "SOME_FOLDER/{{ ansistrano_release_version }}"
  register: ansistrano_release_path
```

In Ansible 1.9 and previous versions, the first task gets executed once but all the servers can use the variable generated in the second task
In Ansible 2.0, the first task executed once but only the first server has access to the variable and the second task errors in every other server as the variable ansistrano_release_version is not defined

We are doing this in Ansistrano (a role which is a capistrano-like implementation in Ansible https://github.com/ansistrano/deploy) in order to set the deployment folder once and use it in all the target server as if we are targetting many servers it can potentially vary from one to the other. 

As you can see, we allow the users to supply this ansistrano_release_version when executing their playbook but we cannot ensure they will and it is just convenient to be generated inside the role

Is this new behaviour to be expected? Have we found a bug? Did it work before as a side effect but it should have never worked?
