### ISSUE TITLE
Synchronize module can't access the remote machine which created by vagrant. just local to local copy

### ISSUE THREAD

**Issue by easyforgood** [ansible/ansible#13947]
##### Issue Type:

Documentation Report
##### Ansible Version:

ansible 2.0.0.2
##### Ansible Configuration:

Default (no ansible.cfg)
part of playbook.xml

```
 ---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
  - name: test
    remote_user: vagrant
    synchronize: src=/home/ec2-user/centos/hosts dest=/home/vagrant/ set_remote_user=yes
```
##### Environment:

RHEL 7.1 in Aws ec2
##### Summary:

I use the ansible as vagrant provision.  vagrant run in local and use ssh port 2222 as default

I have tried to use Synchronize module to copy the file folder quickly. But always failed and copy into itself not in vagrant vbox.

verbose log as followings:( this is a test that copy a file )

>  changed: [127.0.0.1] => {"changed": true, "cmd": "", "msg": ">f..t...... hosts\n", "rc": 0, "stdout_lines": [">f..t...... hosts"]}

I think the wrong thing is the **rsync** command didnt use the remote username and if the **rsync** writing as following ,It will be success to copy to remote vbox that I have test.

> rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=2222'  /home/ec2-user/centos/hosts **vagrant@127.0.0.1**:/home/vagrant/

I have set the _remote_user: vagrant_  and still failed . just copy into local.

**Comment by bcoca** [comment]
# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by easyforgood** [comment]
Thanks for your reminds and help. And Now I have found the solution.

just set **sudo:no**  in the task maybe it used as root before lead it problem.

for example:

```
 ---
- hosts: all
  remote_user: vagrant
  sudo: yes
  tasks:
  - name: test
    sudo: no
    remote_user: vagrant
    synchronize: src=/home/ec2-user/centos/hosts dest=/home/vagrant/ set_remote_user=yes

```

share to everyone
