### ISSUE TITLE
force_handlers does not work with inline handler using roles

### ISSUE THREAD

**Issue by l0neranger** [ansible/ansible#13940]
##### Issue Type:

Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default configuration.
##### Environment:

Control Machine: OS X v10.11.2
Managed Node: Debian Jessie 8.2
##### Summary:

site.yml:

```

---
- hosts: '{{ hosts }}'
  become: yes
  become_user: root
  force_handlers: yes

  roles:
    - test-role

# Ansible 2.0 known issue
# - include doesn't work with runtime execution for handlers.
  handlers:
    - name: restart-nginx
      service:
        name: nginx
        state: restarted
```

roles/test-role/tasks/main.yml:

```

---
- block:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: yes
      notify:
      - restart-nginx
  when: ansible_os_family == "Debian"
```
##### Steps To Reproduce:

```
ansible-playbook -i hosts site.yml -e "hosts=test"
```
##### Expected Results:

The handler restarts nginx on every execution when force_handlers is set to yes.
##### Actual Results:

The handler runs the only once during installation. The force_handlers directive which is meant to run handlers regardless of the task status, does not trigger handler on further executions after installation.
