### ISSUE TITLE
play level tags are being ignored for fact gathering

### ISSUE THREAD

**Issue by offlinehoster** [ansible/ansible#13959]
While running this, the tag is not working.

It will run the whole playbook *§"R%§"%$§"% - that sucks!

I don't know if this is the latest documentaion http://docs.ansible.com/ansible/playbooks_tags.html but this isn't working for me.

I used ansible 2.0.2 on my latest ubuntu 15.10 system. Now i'm back on 1.9.2 and it is running fine again.

Any ideas?

**Comment by bcoca** [comment]
Can You Help Us Out?
====================

Thanks for filing a ticket! I am the friendly GitHub Ansibot.

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!.

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

If You Had A Question To Ask Instead
====================================

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

About Priority Tags
===================

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.

Mailing Lists
=============

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:

  * https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
  * https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by offlinehoster** [comment]
##### Issue Type:
- Bug Report

##### Ansible Version:

2.0.2

##### Ansible Configuration:

default settings not modified

##### Environment:

Ubuntu 15.10 64bit

##### Summary:

The --tags isn't working anymore.

##### Steps To Reproduce:

```
deploy.yml
---
- name: doing something
  hosts: server
  sudo: yes
  roles:
  - bar
  tags:
  - bar
- name: doing some other
  hosts: server
  sudo: yes
  roles:
  - foobar
  tags:
  - foobar
```

##### Expected Results:

Expected was that this will only run the foobar task/role which was tagged by foobar

##### Actual Results:

When running:
ansible-playbook deploy.yml --tags foobar -i hosts
tags are not working, it will execute bar and foobar

**Comment by offlinehoster** [comment]
I wrote an example - check this https://github.com/offlinehoster/ansibleissue

**Comment by bcoca** [comment]
your roles do not have tasks, is the issue that fact gathering runs in both cases?

**Comment by jimi-c** [comment]
Yes, this appears to be a duplicate of https://github.com/ansible/ansible/issues/13602. When using tags, the setup task still runs, however no other tasks in roles or the tasks section of a play run.

As this is a duplicate of the above, we will close it now.

**Comment by offlinehoster** [comment]
@bcoca thats right, i just added 2 empty roles. To show you guys how my setup is working here.

**Comment by offlinehoster** [comment]
#13602 is closed

What was the solution of #13602 ? I don't get it, i mean Ansible is talking for "100% backwards-comp"...not for me right now.

**Comment by bcoca** [comment]
this issue is closed #13602  is still open

**Comment by offlinehoster** [comment]
@bcoca sry, my vault, i saw the closed button next to my issue link ;)

**Comment by offlinehoster** [comment]
Well, in the other issue you guys are talking about "gathering_facts" problems.

I am talking about "tags" are not working in an existing playbook. So for me this issue here is not solved. It is another issue and not the same like #13602

**Comment by jimi-c** [comment]
@offlinehoster can you share another example which reproduces this with tasks in the role? Every test we've done shows that the tags are obeyed with the exception of the `setup` task (which is the gathering_facts bit).

**Comment by vkroz** [comment]
I think this bug is prematurely closed. I have same problem with ansible 2.0 -- my playbooks which works fine with ansible 1.9.\* are now broken with ansible 2.0 
Specifically: ansible-playbook executes all plays and tasks from playbook, regardless of tags provided via  --tag command line option

## playbook

```
---
# Dynamically generates inventory for vagrant-based sandbox and updates /etc/hosts on localhost

- name: "Prepare sandbox inventory and locahost configuration XXX"
  hosts: 127.0.0.1
  connection: local
  tags:
    - build-dynamic-inventory

  tasks:
    - name: "Generate sandbox inventory file"
      template:
        src: "{{ inventory_dir }}/inventory_vagrant.j2"
        dest: "{{ inventory_dir }}/{{ dynamic_inventory_name }}"

    - name: "Update sandbox.cfg with dynamic inventory path"
      lineinfile:
        dest: "{{ sandbox_config_path }}"
        regexp: "^ansible_inventory\\s*="
        line: "ansible_inventory = {{ inventory_dir }}/{{ dynamic_inventory_name }}"
        state: present


- name: "Configure sandbox nodes"
  hosts: all-nodes
  gather_facts: yes
  tags:
    - init_hosts

  tasks:

    - name: Update /etc/hosts
      lineinfile:
        dest: "/etc/hosts"
        regexp: ".*{{ item.public_hostname }}$"
        line: "{{ item.public_ip }} {{ item.public_hostname }}"
        state: present
      with_items: "{{ nodes_list }}"
      become: yes
      become_method: sudo

    - name: "Update hostname"
      hostname: name="{{ host_alias }}"
      become: yes
      become_method: sudo

    - include: "../roles/base/tasks/github.yml"


- name: "Cleanup dynamic inventory on sandbox shutdown"
  hosts: 127.0.0.1
  connection: local
  tags:
    - cleanup_on_shutdown

  tasks:

    - name: "Update sandbox config"
      lineinfile:
        dest: "{{ sandbox_config_path }}"
        regexp: "^ansible_inventory\\s*="
        line: "ansible_inventory = <this value will set automatically on sandbox startup>"
        state: present
```

## command line

```
ansible-playbook -i /etc/ansible/inventory/sandbox/inventory_local /etc/ansible/playbooks/sandbox_vagrant_dynamic_inventory.yml --tags=build-dynamic-inventory --extra-vars='{"nodes_info": {"common": {"IdentityFile": "/etc/sandbox/.vagrant/machines/common.qa0/virtualbox/private_key", "host_alias": "common.qa0", "internal_hostname": "common.qa0", "public_ip": "172.28.128.3", "internal_ip": "172.28.128.3", "User": "vagrant", "public_hostname": "common.qa0"}, "cluster01": {"IdentityFile": "/etc/sandbox/.vagrant/machines/cluster01.qa0/virtualbox/private_key", "host_alias": "cluster01.qa0", "internal_hostname": "cluster01.qa0", "public_ip": "172.28.128.5", "internal_ip": "172.28.128.5", "User": "vagrant", "public_hostname": "cluster01.qa0"}, "cluster02": {"IdentityFile": "/etc/sandbox/.vagrant/machines/cluster02.qa0/virtualbox/private_key", "host_alias": "cluster02.qa0", "internal_hostname": "cluster02.qa0", "public_ip": "172.28.128.6", "internal_ip": "172.28.128.6", "User": "vagrant", "public_hostname": "cluster02.qa0"}}, "dynamic_inventory_name": "inventory_generated_1453864392", "local_ws": "/Users/vkroz/proj/loggly", "nodes_list": [{"IdentityFile": "/etc/sandbox/.vagrant/machines/common.qa0/virtualbox/private_key", "host_alias": "common.qa0", "internal_hostname": "common.qa0", "public_ip": "172.28.128.3", "internal_ip": "172.28.128.3", "User": "vagrant", "public_hostname": "common.qa0"}, {"IdentityFile": "/etc/sandbox/.vagrant/machines/cluster01.qa0/virtualbox/private_key", "host_alias": "cluster01.qa0", "internal_hostname": "cluster01.qa0", "public_ip": "172.28.128.5", "internal_ip": "172.28.128.5", "User": "vagrant", "public_hostname": "cluster01.qa0"}, {"IdentityFile": "/etc/sandbox/.vagrant/machines/cluster02.qa0/virtualbox/private_key", "host_alias": "cluster02.qa0", "internal_hostname": "cluster02.qa0", "public_ip": "172.28.128.6", "internal_ip": "172.28.128.6", "User": "vagrant", "public_hostname": "cluster02.qa0"}], "node_ws": "/home/vagrant/ws", "sandbox_config_path": "/etc/sandbox/sandbox.cfg"}'
```

expected result: only play `"Prepare sandbox inventory and locahost configuration"` must be executed
actual result: all plays from playbook are executed

Note that the same playbook still runs correctly on ansible 1.9.\*
