### ISSUE TITLE
about yum install a rpm for a repo

### ISSUE THREAD

**Issue by zz** [ansible/ansible#13975]
such as zabbix repo RPM package, if install again, will give a error

```
TASK [zabbix_repo : add zabbix repos] ******************************************
fatal: [10.11.2.16]: FAILED! => {"changed": true, "failed": true, "msg": "错误：无须任何处理\n", "rc": 1, "results": ["已加载插件：priorities, update-motd, upgrade-helper\n正在检查 /var/tmp/yum-root-JV1VBv/zabbix-release-2.4-1.el6.noarch.rpm: zabbix-release-2.4-1.el6.noarch\n/var/tmp/yum-root-JV1VBv/zabbix-release-2.4-1.el6.noarch.rpm：不更新已安装的软件包。\n"]}
```

the task is this

``` yaml

---
- name: add zabbix repos
  yum: name=http://repo.zabbix.com/zabbix/2.4/rhel/6/x86_64/zabbix-release-2.4-1.el6.noarch.rpm state=present
  tags:
  - repo
```
