### ISSUE TITLE
Ansible 2.0.0.2 plays all roles even though certain tag is given

### ISSUE THREAD

**Issue by blelump** [ansible/ansible#13984]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0.2
```

installed from Ubuntu PPA [repo](https://launchpad.net/~ansible/+archive/ubuntu/ansible).
##### Ansible Configuration:

```
$ diff github_ansible.cfg /etc/ansible/ansible.cfg
265,275d264
< 
< [colors]
< #verbose = blue
< #warn = bright purple
< #error = red
< #debug = dark gray
< #deprecate = purple
< #skip = cyan
< #unreachable = red
< #ok = green
< #changed = yellow
```
##### Environment:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```
##### Summary:

Ansible plays all roles even though certain tag is given. This is not critical, however make tags quite useless since the execution time grows vastly.
##### Steps To Reproduce:

See **Actual Results**
##### Expected Results:

Ansible plays only certain roles associated with given tag, as it was in 1.9.3. 
##### Actual Results:

See example:

```
$ ansible-playbook  -i local_cluster --tags=monit --vault-password-file=pass site.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [syllabus1]

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [syllabus1]

TASK [ansible-playbook-sensu : include] ****************************************
included: /repo/roles/external/ansible-playbook-sensu/tasks/common.yml for syllabus1

TASK [ansible-playbook-sensu : include] ****************************************
skipping: [syllabus1]

...

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [syllabus1]

TASK [postgresql-role : include] ***********************************************
included: /repo/roles/external/postgresql-role/tasks/install.yml for syllabus1

TASK [postgresql-role : include] ***********************************************
included: /repo/roles/external/postgresql-role/tasks/extensions.yml for syllabus1

TASK [postgresql-role : include] ***********************************************
skipping: [syllabus1]

...

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [syllabus1]

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [syllabus1]

TASK [monit : Install Monit] ***************************************************
ok: [syllabus1]

TASK [monit : Add upstart job] *************************************************
ok: [syllabus1]

TASK [monit : Create base dir] *************************************************
ok: [syllabus1]


...
```

The site.yml:

```

---

- hosts: targets
  roles:
    - {role: ansible-role-dns, sudo: yes, tags: ['dns']  }
    - {role: common, tags: ['init', 'common'] }

- hosts: targets:web
  roles:
    - {role: ansible-playbook-sensu, sudo: yes, tags: ['ansible-playbook-sensu'] }

- hosts: databases
  become: yes
  roles:
    - {role: postgresql, tags: postgresql}

- hosts: web
  tags:
    - web
  roles:
    - {role: monit, become: yes, tags: monit}
```

As you can see Ansible plays all roles that apply for given host, whereas I'd like to run playbook as the docs says: `-t TAGS, --tags=TAGS  only run plays and tasks tagged with these values`.

**Caveat**:

It seems it might be related to the [Dynamic Include Problems](http://www.ansible.com/blog/ansible-2.0-launch), because it only plays roles having `include` statement in their `tasks/main.yml` file. How to avoid that?
