### ISSUE TITLE
default(omit) does not work in dictionaries/hashes

### ISSUE THREAD

**Issue by andrenarchy** [ansible/ansible#13986]
The playbook

``` yaml

---
- hosts: localhost
  vars:
    ec2_tags:
      domains: "{{ host_domains | default(omit) }}"
  tasks:
  - debug: var=ec2_tags
```

yields

```
    "ec2_tags": {
        "domains": "__omit_place_holder__a356c6cb94929bbd95117c5af345bbf78ae51537"
    }
```

instead of an empty `ec2_tags` hash.

**Comment by bcoca** [comment]
omit is only meant to be used in module options, not arbitrary data structures

**Comment by andrenarchy** [comment]
The [documentation](http://docs.ansible.com/ansible/playbooks_filters.html#omitting-undefined-variables-and-parameters) says that it can be used _to omit variables and module parameters_. So this is a mistake in the docs?

If it's not suppose to be used in variables: do you know an alternative way of conditionally setting a key in a dict?

**Comment by bcoca** [comment]
It means 'variables passed to the options' but i can see how that is unclear, the example is not unclear though.

**Comment by andrenarchy** [comment]
Yeah, it's only an example... :smiley: 

Do you know another way to accomplish what I need?

**Comment by rahniwalden** [comment]
@andrenarchy, in regards to use with a variable, I had actually gotten the same suggestion to use (omit) by Ansible support just today:
The literal example I was given back was: 

```
- lineinfile: 
    state: present 
    dest: /path/to/file 
    backup: yes 
    insertafter: EOF 
    line: "{{ item }}" 
  with_items:
    - "{{ var1 }}"
    - "{{ var2 | default(omit) }}"
    - "{{ var3 | default(omit) }}"
```

Whether or not what they suggested was best practice, I cannot say, but I had the same issue with omit not actually omitting and inserting the placeholder text......

What I did instead was this:

```
[...]
 with_items:
    - "{{ var1 }}"
    - "{{ var2 | default() }}" <-- there is no space between the ()
    - "{{ var3 | default() }}"
```

Which worked well enough for what I was trying to do. Hope it helps you.
I'm using ansible v2.1.0.0-1
