### ISSUE TITLE
ec2_vol unable to create volumes from snapshots in v2.0.x

### ISSUE THREAD

**Issue by praddc** [ansible/ansible#14007]
**Issue Type:**
Bug Report

**Ansible Version:** 2.0.0.2

**Ansible Configuration:**
The only thing that changed was upgrading from v 1.9.4 to 2.0.0.2

**Environment:**
Using Ubuntu 14.04 in AWS (ubuntu-trusty-14.04-amd64-server-20150408.1 (ami-495b7079)).  This bug isn't affected by OS.

**Summary:**
The changes made to lines 442/443 in this pull request (https://github.com/ansible/ansible-modules-core/pull/1747/files) break the logic, making it so that the user can no longer create a volume out of a snapshot. Since this merge was never pushed to v1.9.x, it is now showing up in version 2.x. Unfortunately, v1.9 has also been removed from apt, and therefore we can't use an older version that works. Happy to do a pull request to fix this.

Lines from pull request:
ORIGINAL: if volume_size and id:
NEW BROKEN: if volume_size and (id or snapshot):

**Steps To Reproduce:**

Test Playbook:

```
- name: Create volume and attach to this instance
  register: new_volume
  ec2_vol:
    state:  present
    region: us-west-2
    instance: i-d6985a11
    volume_size: 30
    encrypted: true
    snapshot: snap-58a4a004
    device_name: /dev/sdg
```

=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_=_

Comment out the snapshot and it uses the wrong encryption key (the AWS default)

```
- name: Create volume and attach to this instance
  register: new_volume
  ec2_vol:
    state:  present
    region: us-west-2
    instance: i-d6985a11
    volume_size: 30
    encrypted: true
 #   snapshot: snap-58a4a004
    device_name: /dev/sdg
```

Comment out the volume_size and you get a volume the size of the snapshot (1GB) instead of the 30 GB

```
- name: Create volume and attach to this instance
  register: new_volume
  ec2_vol:
    state:  present
    region: us-west-2
    instance: i-d6985a11
 #   volume_size: 30
    encrypted: true
    snapshot: snap-58a4a004
    device_name: /dev/sdg
```

**Expected Results:**

On Ansible v1.9.4:

PLAY [provision the architecture topology] ************************************

GATHERING FACTS ***************************************************************
ok: [localhost]

TASK: [topology | Create volume and attach to this instance] ******************

ok: [localhost]

PLAY RECAP ********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

_Successfully creates the 30 GB volume out of the 1GB snapshot, using the Encryption key of the snapshot_

**Actual Results:**

On Ansible v2.0.0.2

PLAY [provision the architecture topology] *************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [topology : Create volume and attach to this instance] ********************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Cannot specify volume_size together with id or snapshot"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
