### ISSUE TITLE
'search' is not working after upgrade to ansible 2.0

### ISSUE THREAD

**Issue by haocheng** [ansible/ansible#14013]
Issue Type:
Bug Report

Ansible Version: 
master ±  ansible --version
ansible 2.0.0.2
  config file = /home/hclee/develop/vm/ansible.cfg
  configured module search path = Default w/o overrides

Environment:
Ubuntu 14.04

Summary:
'search' is not working' after upgrade to ansible 2.0

Steps To Reproduce:
This is my playbook which is working in ansible 1.9.0.1

``` yaml

---
- include: webupd8.yml

- name: Automatically select the Oracle License
  tags: java
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: Install Oracle Java
  tags: java
  apt: pkg={{ item }} update-cache=yes state=latest
  when: item|search("^oracle")
  with_items: java_versions
```

Expected Results:
It should be running without errors.

Actual Results:

I saw the following error instead:

```
fatal: [10.0.1.118]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'item|search(\"^oracle\")' failed. The error was: ERROR! an unexpected type error occurred. Error was expected string or buffer\n\nThe error appears to have been in '/home/hclee/develop/vm/roles/java/tasks/oracle.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Oracle Java\n  ^ here\n"}
```
