### ISSUE TITLE
ERROR! Connection closed waiting for privilege escalation password prompt

### ISSUE THREAD

**Issue by marek-mazur** [ansible/ansible#14020]
I know that there are few issues like that and they all are closed as solved, but I'm still getting this error with version 2.0.0.2 while using loops and modules: **apt_repository, pip** and **npm**.
Same usage with module **apt** works fine.

For example:

```

---
- hosts: all
  become: yes
  become_method: sudo
...
- apt_repository: repo='{{ item }}' state=present update_cache=yes
  with_items:
    - 'deb http://ftp.pl.debian.org/debian/ jessie main contrib non-free'
    - 'deb-src http://ftp.pl.debian.org/debian/ jessie main contrib non-free'
```

Fails with

```
  virtualbox-iso: TASK [repositories : apt_repository] *******************************************
    virtualbox-iso: fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! timeout waiting for privilege escalation password prompt:\nBECOME-SUCCESS-tsglbidxicsxdsckpbqmoqpjjdscqxci\n"}
    virtualbox-iso:
```

But it works fine when I change it to:

```
- apt_repository: repo='deb http://ftp.pl.debian.org/debian/ jessie main contrib non-free' state=present update_cache=yes
- apt_repository: repo='deb-src http://ftp.pl.debian.org/debian/ jessie main contrib non-free' state=present update_cache=yes
```
