### ISSUE TITLE
"rescue" is not called if the failure of one host with "any_errors_fatal " option on block level

### ISSUE THREAD

**Issue by dcodix** [ansible/ansible#14024]
Hi,

As seen on this thread:
https://groups.google.com/forum/#!topic/ansible-project/pUuPNPtuz9c

On the "devel" branch the option "any_errors_fatal" on a block level should (if a single node fails) have all nodes to fail and then execute "rescue" in all nodes.

In the last "devel" version , yet if the option is accepted (in current 2.0.0 the option is just not accepted on block level) and all nodes are marked as failed the "rescue" part is not executed in any of them. Instead the execution just stops.

```
- name: anyname
  hosts: all
  gather_facts: True
  tasks:
  - block:
      - file: path=/tmp/testfolder1 state=directory
    rescue:
      - file: path=/tmp/testfolder2 state=directory
    any_errors_fatal: yes
```

In the previous example if the "/tmp/testfolder1" fails in any node, "/tmp/testfolder2" will not be created either, as rescue will not be executed.

Without the option "any_errors_fatal" (with a single host) the "rescue" part will be executed.
