### ISSUE TITLE
Ansible Tower: win_feature playbook errors

### ISSUE THREAD

**Issue by wintechdevops** [ansible/ansible#14043]
Hi

If I try run the “Enable IIS” playbook from the Ansible Examples I get the following error below. I am able to run the win_ping playbook fine so I know that I can connect to the servers fine.

I am trying to run a simple job to install IIS using Ansible Tower playbook...

---

```
# This playbook installs and enables IIS on Windows hosts

- name: Install IIS
  hosts: all
  gather_facts: false
  tasks:
    - name: Install IIS
      win_feature:
        name: "Web-Server"
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
```

I am getting the following error:
fatal: [10.10.3.167]: FAILED! => {"changed": false, "exitcode": "Failed", "failed": true, "feature_result": [], "invocation": {"module_name": "win_feature"}, "msg": "Failed to add feature", "restart_needed": false, "success": false}
fatal: [10.10.3.168]: FAILED! => {"changed": false, "exitcode": "Failed", "failed": true, "feature_result": [], "invocation": {"module_name": "win_feature"}, "msg": "Failed to add feature", "restart_needed": false, "success": false}

What could be causing this?
