### ISSUE TITLE
ansible-playbook 2.0.0.2 process hangs when run through packer amazon-chroot builder

### ISSUE THREAD

**Issue by danschaffer** [ansible/ansible#14057]
When updating from ansible 1.9.4 to ansible 2.0.0.2 the ansible-playbook process executed from packer hangs.  I can run the simple ansible playbook fine alone but when packer runs the playbook the ansible-playbook process hangs.  

If I manually kill the ansible-playbook process the packer build continues successfully.  let me know if you have any suggestions for debugging further.  thanks.

workflow is:
- execute a simple packer script on aws using the amazon-chroot builder in packer
- using packer version 0.8.6 in both cases
- when "pip install ansible==2.0.0.2" the packer job is hung and the ansible process never finishes
- when "pip install ansible=1.9.4" the packer job completes successfully

The ansible Is there a change ansible 1.9.4 -> 2.0.0.2 around process control?

I can reproduce the issue on a very simple playbook.

simple.yaml: (simple ansible playbook)

```
- hosts: localhost
  gather_facts: False

  tasks:
    - name: test shell
      shell: echo foo
```

The simple packer script "simple.json" is:

```
{
  "builders": [
    {
      "type": "amazon-chroot",
      "source_ami": "ami-39002553",
      "ami_name": "test-stack",
      "ami_virtualization_type": "hvm",
      "chroot_mounts": [
        ["proc", "proc", "/proc"],
        ["bind", "/dev", "/dev"],
        ["bind", "/tmp/workspace", "/workspace"]
      ],
      "copy_files": [
        "/etc/sudoers.d/packer",
        "/etc/resolv.conf"
      ],
  ],
  "provisioners": [
    {
      "type": "shell",
      "execute_command": "sudo -E sh '{{ .Path }}'",
      "inline": [
        "pip install ansible==2.0.0.2",
        "/usr/local/bin/ansible-playbook --version"
      ]
    },
    {
      "type": "ansible-local",
      "playbook_file": "/tmp/simple.yml",
      "command": "/usr/local/bin/ansible-playbook -i foo, -vvvv"
    }
  ]
}
```

*\* with pip install ansible==1.9.4 the ansible script exits correctly and packer succeeds.  When change to pip install ansible=2.0.0.2 the ansible process is hung and packer hangs.

The output from running "sudo packer build -only=amazon-chroot ./simple.json" is:

```
amazon-chroot: TASK [test shell] **************************************************************
    amazon-chroot: task path: /tmp/packer-provisioner-ansible-local/test.yml:5
    amazon-chroot: ESTABLISH LOCAL CONNECTION FOR USER: root
    amazon-chroot: 127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453401360.22-221460254152869 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453401360.22-221460254152869 )" )
    amazon-chroot: 127.0.0.1 PUT /tmp/tmpfpYj1G TO /root/.ansible/tmp/ansible-tmp-1453401360.22-221460254152869/command
    amazon-chroot: 127.0.0.1 EXEC LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1453401360.22-221460254152869/command; rm -rf "/root/.ansible/tmp/ansible-tmp-1453401360.22-221460254152869/" > /dev/null 2>&1
    amazon-chroot: changed: [127.0.0.1] => {"changed": true, "cmd": ["echo", "foo"], "delta": "0:00:00.002479", "end": "2016-01-21 18:36:00.280877", "invocation": {"module_args": {"_raw_params": "echo foo", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-01-21 18:36:00.278398", "stderr": "", "stdout": "foo", "stdout_lines": ["foo"], "warnings": []}
    amazon-chroot:
    amazon-chroot: PLAY RECAP *********************************************************************
    amazon-chroot: 127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=0
    amazon-chroot:
```

(hangs)

```
$ ps -ef | grep ansible
root      3973  3972  0 18:35 pts/1    00:00:00 /usr/bin/python2.7 /usr/local/bin/ansible-playbook -i foo, -vvvv /tmp/packer-provisioner-ansible-local/test.yml -c local -i /tmp/packer-provisioner-ansible-local/packer-provisioner-ansible-local147735453
root      3976  3973  5 18:35 pts/1    00:00:13 /usr/bin/python2.7 /usr/local/bin/ansible-playbook -i foo, -vvvv /tmp/packer-provisioner-ansible-local/test.yml -c local -i /tmp/packer-provisioner-ansible-local/packer-provisioner-ansible-local147735453
```
