### ISSUE TITLE
Notify (to handlers) does not work when using docker module in ansible 2.0.0.2

### ISSUE THREAD

**Issue by zentavr** [ansible/ansible#14058]
**Issue Type:** Bug Report/Feature Idea
**Ansible Version:** 2.0.0.2
**Ansible Configuration:**

```
[defaults]
host_key_checking = False
forks = 10
var_compression_level=9
retries=5
fact_caching = jsonfile
fact_caching_connection = ~/.ansible/tmp
```

**Environment:**
OS: Mac OS X El Capitan

**Summary:**
docker module does not return `changed: true` as a result, so I cannot use `notify` feature in order to restart dependent containers.

```
- name: Spinning up an arena-fluentd container
  docker:
    registry: "{{ docker_registry_url }}"
    email: "{{ docker_registry_email }}"
    username: "{{ docker_registry_user }}"
    password: "{{ docker_registry_password }}"
    docker_api_version: "{{ docker_api_version }}"
    image: "{{ docker_registry_url }}/arena/{{ docker_images['fluentd'] }}:{{ builds['fluentd'] }}"
    pull: always
    state: reloaded
    restart_policy: always
    restart_policy_retry: 5
    name: "arena-fluentd"
    volumes:
      - "/srv/{{ datadir }}/fluent.conf:/fluentd/etc/fluent.conf:ro"
      - /var/log/syslog:/fluentd/log/host/syslog:ro
      - /var/log/auth.log:/fluentd/log/host/auth.log:ro
      - /var/log/dpkg.log:/fluentd/log/host/dpkg.log:ro
      - /var/log/kern.log:/fluentd/log/host/kern.log:ro
      - /var/log/dmesg:/fluentd/log/host/dmesg:ro
    expose:
      - 24224
      - 5140
    ports:
      - 127.0.0.1:24224:24224
      - 127.0.0.1:15140:5140
    env:
      AWS_REGION: "{{ ec2_region }}"
      AWS_ACCESS_KEY_ID: "{{ aws_cwl_user }}"
      AWS_SECRET_ACCESS_KEY: "{{ aws_cwl_password }}"
  tags:
    - fluentd_spinup
  register: arenaapp_fluent_container_status
  when: builds['fluentd'] not in [ 'Keep', 'None']
  notify:
    - restart admin-platform container
    - restart admin-nginx container
    - restart apps-platform container
    - restart apps-nginx container
    - restart celeryuser-platform container
```

I have this output:

```
changed: [172.29.14.216] => {
    "ansible_facts": {
        "docker_containers": [
            {
                "AppArmorProfile": "", 
                "Args": ["-c", "exec fluentd -c /fluentd/etc/$FLUENTD_CONF -p /fluentd/plugins $FLUENTD_OPT"], 
                "Config": {
                    ---- bla bla bla ----
                }, 
                "Created": "2016-01-21T14:22:46.976705483Z", 
                "Driver": "aufs", 
                "ExecDriver": "native-0.2", 
                "ExecIDs": null, 
                "GraphDriver": {
                    "Data": null, 
                    "Name": "aufs"
                }, 
                "HostConfig": {
                    "Binds": [
                        "/var/log/dpkg.log:/fluentd/log/host/dpkg.log:ro", 
                        "/srv/gsn/fluent.conf:/fluentd/etc/fluent.conf:ro", 
                        "/var/log/kern.log:/fluentd/log/host/kern.log:ro", 
                        "/var/log/auth.log:/fluentd/log/host/auth.log:ro", 
                        "/var/log/syslog:/fluentd/log/host/syslog:ro", 
                        "/var/log/dmesg:/fluentd/log/host/dmesg:ro"
                    ], 
                    ---- bla bla bla ----
                }, 
                "HostnamePath": "/data/docker/containers/f4ad6ae006f70121d100b7a23102aa683a2b3df1a3dd755e363c7f5bf847ea12/hostname", 
                "HostsPath": "/data/docker/containers/f4ad6ae006f70121d100b7a23102aa683a2b3df1a3dd755e363c7f5bf847ea12/hosts", 
                "Id": "f4ad6ae006f70121d100b7a23102aa683a2b3df1a3dd755e363c7f5bf847ea12", 
                "Image": "e04bb29a8e7068c06b70e0fe86beb872a537a798f2c78878468166ed43910b56", 
                "LogPath": "/data/docker/containers/f4ad6ae006f70121d100b7a23102aa683a2b3df1a3dd755e363c7f5bf847ea12/f4ad6ae006f70121d100b7a23102aa683a2b3df1a3dd755e363c7f5bf847ea12-json.log", 
                "MountLabel": "", 
                "Name": "/arena-fluentd", 
                "NetworkSettings": {
                    ---- bla bla bla ---
                }, 
                ---- bla bla bla ----
            }
        ]
    }, 
    "changed": true, 
    "msg": "removed 1 container, stopped 1 container, started 1 container, created 1 container, pulled 1 container.", 
    "reload_reasons": "image (da2b40cb80cd37a3d0485043449aed6ed94246190957b518baf85bf7c7426adc => e04bb29a8e7068c06b70e0fe86beb872a537a798f2c78878468166ed43910b56)", 
    "summary": {"created": 1, "killed": 0, "pulled": 1, "removed": 1, "restarted": 0, "started": 1, "stopped": 1}
}
```

I would like to have `changed: true` not in `ansible_facts` structure, but also as a dedicated variable in the structure, saying, like we have for that `copy` or `template` module:

```
changed: [172.29.36.37] => (item={'dest': u'/etc/bind/zones/', 'src': u'zones/dev/'}) => {"changed": true, "dest": "/etc/bind/zones/", "item": {"dest": "/etc/bind/zones/", "src": "zones/dev/"}, "src": "/Users/zentavr/__repos/arena-platform-dns/zones/dev"}
```
##### Steps To Reproduce:

Try to spinup/update the version of the docker image and see.
##### Expected Results:

To be able to notify the handlers that the container was updated/runned
##### Actual Results:

Seems like I do need to register a var, then parse it. Hate crutches :(

**Comment by zentavr** [comment]
Seems like I am wrong, the notification to the handlers were sent, as I see from `-vvvv` output:

```
NOTIFIED HANDLER restart admin-platform container
NOTIFIED HANDLER restart admin-nginx container
NOTIFIED HANDLER restart apps-platform container
NOTIFIED HANDLER restart apps-nginx container
```

probably we have another problem, that I'm trying to generate the hadlers dynamically, using this YAML inside `handlers/main.yml`:

```
- include: platform_handlers.yml
  with_items:
    - admin
    - apps
```

and `platform_handlers.yml` is the next:

```
- set_fact: platform_loop_item="{{ item }}"

- name: "restart {{ platform_loop_item }}-platform container"
  docker:
    name: "{{ platform_loop_item }}-platform"
    image: "{{ docker_registry_url }}/arena/{{ docker_images[platform_loop_item] }}"
    state: restarted
  when: ec2_tag_role|default('n/a') in [ 'all', platform_loop_item ]

- name: "restart {{ platform_loop_item }}-nginx container"
  docker:
    name: "{{ platform_loop_item }}-nginx"
    image: "{{ docker_registry_url }}/arena/{{ docker_images['nginx'] }}"
    state: restarted
  when: ec2_tag_role|default('n/a') in [ 'all', platform_loop_item ]
```

In order to do so, i read http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes
It says:

```
In 2.0 you are able to use with_ loops and task includes (but not playbook includes), this adds the ability to loop over the set of tasks in one shot.
```

...seems like it does not work for the handlers as well :(
