### ISSUE TITLE
Argument 'creates' from 'shell' not working

### ISSUE THREAD

**Issue by jonatasbaldin** [ansible/ansible#14061]
Hi,

As the title, the argument 'creates' from 'shell' won't work. It does not create any file, anywhere. I've tried some directories, like local, home, relative, full path.
I've tried to remove the filter 'quote' also.

Here is the code:

```
- name: Compile                                                                                                   
  shell: ./configure --prefix="{{ zabbix3server_path | quote }}" --enable-server --enable-agent --with-"{{ zabbix3server_db | quote }}"  --enable-ipv6 --with-net-snmp --with-libcurl --with-libxml2 && make install                  
  args:                                                                                                            
    chdir: /usr/src/zabbix-3.0.0beta1                                                                              
    creates: zabbix3server-compile                                                                                 
```

```
ansible --version
ansible 2.0.0.2                                                       
```

Is it a bug or am I doing something wrong?
