### ISSUE TITLE
[ec2_group] Ansible 2.0.0.2 - "with_items" & "stdout_lines" not iterating

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#14063]
Hi guys,
I'm trying to create a loop to destroy a set of AWS Security Groups.

First I run: 

```
- shell: aws ec2 describe-security-groups --query 'SecurityGroups[*].Tags[?Key==`Name`].Value[]' --filter Name=tag:event,Values={{ event }},Name=tag:Name,Values={{ event }}_sg-*_{{ env }} --output text`
- register: sgroup
```

The stdout_lines of that gives me:

```
"stdout_lines": [ "riff_sg-8a2b69f3_dev\triff_sg-842b69fd_dev\triff_sg-7e286a07_dev\triff_sg-a02b69d9_dev\triff_sg-922b69eb_dev\triff_sg-d6286aaf_dev\triff_sg-dd286aa4_dev" ] 
```

When I try to iterate through stdout_lines it instead treats {{ item }} as the entire output rather than one item per 'line'.

```
- ec2_group:
    name: "{{ item }}"
    region: "{{ region }}"
    state: absent
    description: Security Group
  with_items: "{{ sgroup.stdout_lines }}"
```

I'm using the same logic with "ec2_tag" without issue, but I can't get "ec2_group" to work.
