### ISSUE TITLE
v2.0: ambiguous "skipping" status for command task in check mode

### ISSUE THREAD

**Issue by zarnovican** [ansible/ansible#14075]
##### Issue Type:

Feature Idea
(Bug Report?)
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /home/zarnovic/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

No changes.
##### Environment:

N/A
##### Summary:

In check mode, "skipping" status is ambiguous for command tasks with `when` condition.

One major use-case for running check mode is to find out what would be applied in normal mode. Command tasks always return "skipping" status in check mode (those that don't have "always_run: yes", to be exact). User cannot tell whether the command is really skipped due to `when` condition not being met or skipped because it is in check mode.

It would be nice to distinguish these two states. One possible solution is to return "changed" status on commands that are not skipped by `when` condition. This would align the behavior with other modules.

Changing it from "skipped" to "changed" may cause heart-attack for sysadmins already used to current convention. I don't mind how it is fixed, as long as those two states are distinguishable.

Workaround: print command's `when:` condition with debug task ("Next command would run: true/false").

In Ansible 1.9, it was distinguishable albeit the output was slightly confusing:

```
TASK: [unconditional command] ************************************************* 
skipping: [localhost]

ok: [localhost]

TASK: [conditional command] *************************************************** 
skipping: [localhost]
```
##### Steps To Reproduce:
1. create playbook
   
   ```
   ---
   - name: 'test1'
     hosts: localhost
     gather_facts: no
   
     tasks:
       - name: 'unconditional command'
         command: /bin/echo foo
   
       - name: 'conditional command'
         command: /bin/echo bar
         when: "{{ condition | default('false') }}"
   ```
2. run playbook in check mode
##### Expected Results:

```
PLAY [test1] *******************************************************************

TASK [unconditional command] ***************************************************
changed: [localhost]

TASK [conditional command] *****************************************************
skipping: [localhost]
```
##### Actual Results:

```
PLAY [test1] *******************************************************************

TASK [unconditional command] ***************************************************
skipping: [localhost]

TASK [conditional command] *****************************************************
skipping: [localhost]
```

Notice, first task would run in normal mode, while the second would be skipped due to `when:`. Both have the same output in check mode.
