### ISSUE TITLE
Using with_items with an empty list should skip the task

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1408]
The situation I am in is that I would like to have a list $packages with optional packages to be installed. By default this list is empty, but we would like to be able to set it on a per-group or per-host basis.

However when doing something like:

``` yaml
- name: Install additional packages
  hosts: all
  tasks:
  - action: yum pkg=$item state=installed
    with_items: ${packages}
```

This fails with a yum-module error when ${packages} is an empty list. Since only_if is evaluated per item, it is no option to use it in this case.
