### ISSUE TITLE
Variable specified in role invocation fails to override role default

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#14095]
**Ansible version** 2.0.0.2
**Summary**

I've a playbook that does this:

``` yml
  roles:
    - { role: ivija, name: pdr-staging, port: 8092,
        tags: [ staging ] }
```

The role defines a default value for the port:

``` yml
# roles/ivija/defaults/main.yml
port: 8080
```

and uses it in a template:

``` yml
# roles/ivija/tasks/main.yml
- name: generate a buildout.cfg
  template: src=buildout.cfg.j2 dest="{{ home }}/buildout.cfg"
  tags: config
```

``` ini
# roles/ivija/templates/buildout.cfg.j2
[config]
port = localhost:{{ port }}
```

When I run this playbook with Ansible 1.9.4, I correctly get

```
port = localhost:8092
```

When I try Ansible 2.0.0.2, I see this:

```
TASK [ivija : generate a buildout.cfg] *****************************************
changed: [page]
--- before: /apps/zopes/eversheds-pdr-staging/buildout.cfg
+++ after: dynamically generated
@@ -1,19 +1,19 @@
... 
 [config]
...
-port = localhost:8092
+port = localhost:8080
... 
```
