### ISSUE TITLE
Synchronize module not using remote_user in 2.0

### ISSUE THREAD

**Issue by mrkyle7** [ansible/ansible#14104]
We just upgraded from ansible 1.9.3 to ansible 2.0 and this has broken the synchronize module.

Our config:

```
task:
- name: Copy folder
  synchronize: src=apps
               dest={{dir_binary}}/apps
               delete=yes
               recursive=yes
               checksum=yes archive=no
```

playbook:

```
- name: sync
  hosts: all
  remote_user: "{{remote_user}}"
  roles:
    - sync
```

inventory:

```
[all:vars]
remote_user = remoteuser
```

With -v flags, it's using: {{remote_user}}@remote-host

So it looks like it isn't resolving the variable from task_vars and using the literal string {{remote_user}}.

Changing remote_user: "{{remote_user}}" to remote_user: remoteuser  works ok.

Note other modules are ok

**Comment by mrkyle7** [comment]
FYI, a workaround is: 

```
# synchronize task bug workaround: it uses the ansible_ssh_user variable in its unresolved form i.e. "{{ansible_ssh_user}}".
# Here we just push the resolved value into the variable.
- name: Synchronize task bug workaround
  set_fact:
    ansible_ssh_user: "{{ansible_ssh_user}}"
```

Clearly this is undesirable!

**Comment by abadger** [comment]
I'm not able to reproduce this with a minimal test case.

```
$ cat inven                                                     (12:23:03)
rhel6-test
[all:vars]
remote_user = badger

$ cat 14104.yml                                                 (12:23:38)
---
- name: sync
  hosts: all
  remote_user: "{{remote_user}}"
  roles:
    - sync

$ cat roles/sync/tasks/main.yml                                 (12:23:50)
---
# tasks file for sync

- name: Copy folder
  synchronize: src=/var/tmp/host
               dest=/var/tmp/dest
               delete=yes
               recursive=yes
               checksum=yes
               archive=no
$ ansible-playbook 14104.yml -i inven -vvvv
[...]
ok: [rhel6-test] => {"changed": false, "cmd": "rsync --delay-updates -F --compress --delete-after --checksum --recurs
ive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/var/tmp/host\" \"badger@rhe
l6-test:/var/tmp/dest\"", "invocation": {"module_args": {"_local_rsync_path": "rsync", "archive": false, "checksum": 
true, "compress": true, "copy_links": null, "delete": true, "dest": "badger@rhel6-test:/var/tmp/dest", "dest_port": 2
2, "dirs": false, "existing_only": false, "group": null, "links": null, "mode": "push", "owner": null, "partial": fal
se, "perms": null, "private_key": null, "recursive": true, "rsync_opts": null, "rsync_path": null, "rsync_timeout": 0
, "set_remote_user": true, "src": "/var/tmp/host", "ssh_args": null, "times": null, "verify_host": false}}, "msg": ""
, "rc": 0, "stdout_lines": []}

$ ansible --version                                             (12:24:34)
ansible 2.0.0.2
```

Can you try my test case to see if it works for you or propose changes to it that will show the failure?

**Comment by abadger** [comment]
If we get more information on how to reproduce this we can look at what is happening.  Let us know if you can give us more information on what is different between my test case and yours.

**Comment by mrkyle7** [comment]
Sorry missed this, will replicate your config

**Comment by mrkyle7** [comment]
Fyi, is "badger" a different user to the one you are running the playbook?

**Comment by maludwig** [comment]
I'm experiencing what I think is the same thing. Here's the skinny. The synchronize module, when "become:yes" or "sudo:yes" is on, will run rsync as root locally. So, it's _not _that it's not correctly reading your thing, it's that its reading the root user's thing, and that's unhelpful.
Make yourself a couple servers, which I'll call "SOURCE_SERVER" and "DESTINATION_SERVER". Set up SSH login on them, with a non-root user account, for example, "maludwig". Allow that user to become root with sudo, without requiring a password.
Make a directory, no need to put things in it: 
`mdkir /home/maludwig/boo`

And try to run ansible, first, without sudo. This will fail with a permissions issue, because the remote rsync command isn't run with sudo, but, locally, rsync will run as you:
`ansible -m "synchronize" -a "src=/home/maludwig/boo/ dest=/root/boo/" DESTINATION_SERVER`

Equally unhelpful, try putting in the --sudo, and both the local AND the destination servers attempt to be root. If your ssh keys and config are in the local server's /root/.ssh/ directory, then this command will work, but "rm -rf /root/.ssh" and everything will be ruined again, and you'll be sad:
`ansible --sudo -m "synchronize" -a "src=/home/maludwig/boo/ dest=/root/boo/" DESTINATION_SERVER`

**Comment by maludwig** [comment]
Below is my output:

```

[2016-02-23T00:04:20-0700]: mitchell@SOURCE_SERVER:~/infra
$ ansible -m "synchronize" -a "src=boo/ dest=/root/boo/" DESTINATION_SERVER
DESTINATION_SERVER | FAILED! => {
    "changed": false,
    "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"boo/\" \"DESTINATION_SERVER:/root/boo/\"",
    "failed": true,
    "msg": "rsync: ERROR: cannot stat destination \"/root/boo/\": Permission denied (13)\nrsync error: errors selecting input/output files, dirs (code 3) at main.c(554) [receiver=3.0.6]\nrsync: connection unexpectedly closed (9 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]\n",
    "rc": 12
}
[2016-02-23T00:04:50-0700]: mitchell@SOURCE_SERVER:~/infra
$ ansible -m "synchronize" -a "src=boo/ dest=/root/boo/" DESTINATION_SERVER --sudo
DESTINATION_SERVER | FAILED! => {
    "changed": false,
    "cmd": "rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --rsync-path=\"sudo rsync\" --out-format='<<CHANGED>>%i %n%L' \"boo/\" \"DESTINATION_SERVER:/root/boo/\"",
    "failed": true,
    "msg": "Permission denied (publickey).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(605) [sender=3.0.9]\n",
    "rc": 255
}

```

**Comment by sztupy** [comment]
Have a similar issue, adding the following to the start of the playbook seems to fix it on Ansible 2.0.1.0:

```
    - name: Synchronize task bug workaround
      set_fact:
        ansible_ssh_user: "{{ansible_ssh_user}}"
        ansible_ssh_private_key_file: "{{ansible_ssh_private_key_file}}"
```

**Comment by abadger** [comment]
Sorry about hte false close -- we started using waffle.io and it's apparently easy to get things into the wrong buckets.

**Comment by abadger** [comment]
@mrkyle7 I switched to a local user named testuser and tried again.  Still not able to reproduce the error you're seeing.   Maybe you could paste the output of the task with -vvvv.  Also, there have been some changes to templating since the first 2.0 release so I'm not sure if I'm testing precisely the same version that you are.  If you could also paste ansible --version output along with the task output that would be helpful.

@maludwig Your error involves using sudo and I think it's different.  I know that there was an error in the way synchronize used sudo in 2.0.0.0 that was resolved by 2.0.1 (Not to be confused with the similarly named but earlier release, 2.0.0.1....).   You could try a current release out and if it's still occurring, please create a new bug.

**Comment by tima** [comment]
Recommend closing this issue for lack of activity. Perhaps its been fixed with all the recent work on the synchronize module/action in core? If this is still an issue and can be reproduced in the latest stable version (2.1.1) then please let us know.

**Comment by robertpeteuil** [comment]
UPDATE: I Discovered this occurs if you try to [sync to a folder that doesn't exist] (https://askubuntu.com/questions/625085/rsync-over-ssh-error-in-protocol-data-stream-code-12-ssh-works)

So you cannot use this to create folders, you must manually create a folder with the file module first.

-------

This is still an issue, as I ran into it today.  

Here's my log from -vvvv

```yaml
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/files/synchronize.py
<1node5.local> ESTABLISH LOCAL CONNECTION FOR USER: robertpeteuil
<1node5.local> EXEC /bin/sh -c 'echo ~ && sleep 0'
<1node5.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135033.37-133415067505773 `" && echo ansible-tmp-1504135033.37-133415067505773="` echo /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135033.37-133415067505773 `" ) && sleep 0'
<1node5.local> PUT /var/folders/7y/qcy0fcq92879qm7t_wskz9fm0000gn/T/tmpPGgkkp TO /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135033.37-133415067505773/synchronize.py
<1node5.local> EXEC /bin/sh -c 'chmod u+x /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135033.37-133415067505773/ /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135033.37-133415067505773/synchronize.py && sleep 0'
<1node5.local> EXEC /bin/sh -c '/usr/bin/python /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135033.37-133415067505773/synchronize.py; rm -rf "/Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135033.37-133415067505773/" > /dev/null 2>&1 && sleep 0'
fatal: [1node5]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --checksum --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=15m -o ForwardAgent=yes --out-format=<<CHANGED>>%i %n%L /Users/robertpeteuil/Versioned/ansible-playbooks/my-pi-cluster/roles/leds/files/get-pip.py pi@1node5.local:/home/pi/bin/pip",
    "failed": true,
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync",
            "_substitute_controller": false,
            "archive": true,
            "checksum": true,
            "compress": true,
            "copy_links": false,
            "delete": false,
            "dest": "pi@1node5.local:/home/pi/bin/pip",
            "dest_port": null,
            "dirs": false,
            "existing_only": false,
            "group": null,
            "links": null,
            "mode": "push",
            "owner": null,
            "partial": false,
            "perms": null,
            "private_key": null,
            "recursive": null,
            "rsync_opts": null,
            "rsync_path": null,
            "rsync_timeout": 0,
            "set_remote_user": true,
            "src": "/Users/robertpeteuil/Versioned/ansible-playbooks/my-pi-cluster/roles/leds/files/get-pip.py",
            "ssh_args": "-o ControlMaster=auto -o ControlPersist=15m -o ForwardAgent=yes",
            "times": true,
            "verify_host": false
        }
    },
    "msg": "rsync: connection unexpectedly closed (8 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]\n",
    "rc": 12
}
```

**Comment by robertpeteuil** [comment]
I've narrowed it down to this triggering the error:

```yaml
synchronize:
  src: get-pip.py
  dest: /home/{{newuser}}/bin/pip
```
I've tried formatting 'dest' in different way, and even hard-coded it - it always fails:

```yaml
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/files/synchronize.py
<1node5.local> ESTABLISH LOCAL CONNECTION FOR USER: robertpeteuil
<1node5.local> EXEC /bin/sh -c 'echo ~ && sleep 0'
<1node5.local> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135651.92-103198278354759 `" && echo ansible-tmp-1504135651.92-103198278354759="` echo /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135651.92-103198278354759 `" ) && sleep 0'
<1node5.local> PUT /var/folders/7y/qcy0fcq92879qm7t_wskz9fm0000gn/T/tmpo7S6S6 TO /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135651.92-103198278354759/synchronize.py
<1node5.local> EXEC /bin/sh -c 'chmod u+x /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135651.92-103198278354759/ /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135651.92-103198278354759/synchronize.py && sleep 0'
<1node5.local> EXEC /bin/sh -c '/usr/bin/python /Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135651.92-103198278354759/synchronize.py; rm -rf "/Users/robertpeteuil/.ansible/tmp/ansible-tmp-1504135651.92-103198278354759/" > /dev/null 2>&1 && sleep 0'
fatal: [1node5]: FAILED! => {
    "changed": false,
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no --out-format=<<CHANGED>>%i %n%L /Users/robertpeteuil/Versioned/ansible-playbooks/my-pi-cluster/roles/leds/files/get-pip.py pi@1node5.local:/home/pi/bin/pip",
    "failed": true,
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync",
            "_substitute_controller": false,
            "archive": true,
            "checksum": false,
            "compress": true,
            "copy_links": false,
            "delete": false,
            "dest": "pi@1node5.local:/home/pi/bin/pip",
            "dest_port": null,
            "dirs": false,
            "existing_only": false,
            "group": null,
            "links": null,
            "mode": "push",
            "owner": null,
            "partial": false,
            "perms": null,
            "private_key": null,
            "recursive": null,
            "rsync_opts": null,
            "rsync_path": null,
            "rsync_timeout": 0,
            "set_remote_user": true,
            "src": "/Users/robertpeteuil/Versioned/ansible-playbooks/my-pi-cluster/roles/leds/files/get-pip.py",
            "ssh_args": null,
            "times": null,
            "verify_host": false
        }
    },
    "msg": "rsync: connection unexpectedly closed (8 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at /SourceCache/rsync/rsync-45/rsync/io.c(453) [sender=2.6.9]\n",
    "rc": 12
}
```

I noticed some odd text in the cmd statement, right after StrictHostKeyChecking=no:
`--out-format=<<CHANGED>>%i %n%L`
