### ISSUE TITLE
Feature request: manipulate tags as a play level parameter

### ISSUE THREAD

**Issue by akatch** [ansible/ansible#14117]
Issue Type: Feature request

Ansible Version: 1.9.4 (but to my knowledge this doesn't exist in 2.0 either)

Ansible Configuration: n/a

Environment: n/a

Summary:

I'd love to see a play level parameter that allows the user to specify which tags are to be used (or skipped) in that play. For example:

```

---
- hosts: all
  become: true

  skip_tags:
  - iptables

  roles:
  - common
  - nginx
  - application
```

This play would run only the tasks that _are not_ tagged `iptables`. Alternatively:

```

---
- hosts: all
  become: true

  include_tags:
  - configure

  roles:
  - common
  - nginx
  - application
```

This play would run only tasks that _are_ tagged `configure`.

Steps To Reproduce: See above for desired results. This would be fantastic in particular for using ansible-pull, where altering the command-line parameters on a per-playbook basis is a bit more of a hassle.

**_EDIT:**_ I updated the suggested parameter for including tags since `tags:` is already a play level parameter that exists.

**Comment by renekalff** [comment]
I'd love to see this feature as well. I create playbooks for certain maintenance tasks (and others like rebuilding a slave mysql server). These need to run with a number of tags. As the only way to specify task is at the command line I've to create bash scripts to run the ansible-playbook command with the tasks required.

**Comment by ghost** [comment]
Pretty much a-must-feature to my mind. That would negate necessity to use wrapper scripts around playing the playbooks.

**Comment by MrMMorris** [comment]
This is definitely a must have feature and it's surprising that so few people have mentioned this.

To add, it would also be nice to have role level tagging:

``` yml
roles: 
  - { role: blah, include-tags: ['foo'] }
```

For the longest time, that's what I thought this did in the Tags docs:

``` yml
roles:
  - { role: webserver, port: 5000, tags: [ 'web', 'foo' ] }
```

**Comment by frimdo** [comment]
+1

**Comment by tinproject** [comment]
I also want that something like this would be implemented, it will be good to define the tags to be run inside a playbook. I believe one of the problems of this feature to be implemented is the misleading grammar of the word _tags_ as is used on Ansible. 

Inside an ansible .yml file on a task/role/play definition _tags_ means to put a label 'tag name' on the tasks of that play/role/task. Contrary, on the ansible-playbook command line, _tags_ means run the tasks/roles/plays labeled with this 'tag name'. This leads to use a single word for two different actions. 

To avoid that ambiguity I propose the use of `run_tagged` name for this feature, and for completion: `run_tagged_only` and  `run_tagged_exclude`. Other names could be used, but must avoid the confusion of tag word and transmit clearly the desired action. 

This 'words' could be applied to `include` and `role`, and also to a `play` (inside it). On all this cases we have a _set of tags_ from the parent level (command-line/play/role..).

* **run_tagged**
`run_tagged: [tag_list] ` this modify the 'tag set' for the associate element resulting in the `tag_list` union the 'tag set' from the parent element in an associative way.
This is an equivalent of `include_tags` defined above.

* **run_tagged_only**
`run_tagged_only: [tag_list] ` this modify the 'tag set' for the associate element resulting on the tags defined on `tag_list` only, ignoring the tags of the 'tag set' from the parent element.

* **run_tagged_exclude**
`run_tagged_exclude: [tag_list] ` this modify the 'tag set' for the associate element resulting in the 'tag set' from the parent element with all tags from the defined `tag_list` removed.
This is an equivalent of `skip_tags` defined above.

### Example:

```bash
$ansible-playbook my_playbook.yml --tags=t1,t2
```
```yml
# file: my_playbook.yml
---
- name: play 1
  hosts: all
  run_tagged:
  - t3

  roles:
  - role_one
  - { role: role_two, run_tagged_exclude: ['t2'] }
  - { role: role_three, run_tagged_only: ['t4'] }
---
- name: play 2
  hosts: all
  tasks:
    - include: my_tasks.yml
      run_tagged:
        - t5
```

- Tasks on `play 1` will run if tagged with: t1, t2, or t3
- Tasks on role `role_one` will run if tagged with: t1, t2, or t3
- Tasks on role `role_two` will run if tagged with: t1, or t3
- Tasks on role `role_three` will run if tagged with: t4
- Tasks on `play 2` from `my_tasks.yml` will run if tagged with: t1, t2, or t5

The use of the word _exclude_ in `run_tagged_exclude` could lead to think that the tasks will be excluded if they match one of the tags from the tag_list, but 'exlude' is refereed to the tag from the 'tag set' only. For example, on `role_two` if a task is tagged with t1 and t2, will be executed, as t1 is present on the 'tag set'.
