### ISSUE TITLE
ansible 2.0 can't use + operator to join lists

### ISSUE THREAD

**Issue by tkellen** [ansible/ansible#14118]
**Issue Type:** Bug Report
**Ansible Version:** 2.0.0.2
**Environment:** OSX
**Summary:** Ansible 1x allowed the combination of lists using the `+` operator. Ansible 2x does not. Is this a wontfix?

Here is a playbook that fails in 2x but not 1.9x:

``` yml
- hosts: all
  gather_facts: false
  vars:
    fruit:
      - apple
      - pear
    veggie:
      - carrot
      - onion
  tasks:
    - file: src={{item}} state=touch
      delegate_to: localhost
      with_items: fruit + veggie
```

**Workarounds** (use `with_flattened` or `union` filter):

``` yml
- hosts: all
  gather_facts: false
  vars:
    fruit:
      - apple
      - pear
    veggie:
      - carrot
      - onion
  tasks:
    - file: path={{item}} state=touch
      delegate_to: localhost
      with_flattened:
       - fruit
       - veggie
```

``` yml
- hosts: all
  gather_facts: false
  vars:
    fruit:
      - apple
      - pear
    veggie:
      - carrot
      - onion
  tasks:
    - file: path={{item}} state=touch
      delegate_to: localhost
      with_items: fruit | union(veggie)
```
