### ISSUE TITLE
regression: commit 8647fdc breaks become_method='su'

### ISSUE THREAD

**Issue by lifanov** [ansible/ansible#14116]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.0.2
  config file = /home/lifanov/.ansible.cfg
  configured module search path = /usr/local/share/ansible

Running version 2.0.0.2 with a backport of commit 8647fdc
##### Ansible Configuration:

Regression is evident with clean config.
##### Environment:

N/A
##### Summary:

The above-mentioned commit fixes become_method='sudo' with non-default shells (like /bin/csh on FreeBSD, etc.), so it is important, but it also regresses become_method='su' by incorrectly quoting commands running through "/bin/sh -c".
##### Steps To Reproduce:

Playbook:

```

---
- hosts: ws-leeb.ad.nyingma.org
  become: yes
  become_method: su
  gather_facts: false
  tasks:
  - name: install packages
    pkgng: name={{item}} state=present
    with_items:
      - editors/nano
      - net/x11vnc
      - x11/xscreensaver
```
##### Expected Results:

Playbook works.
##### Actual Results:

```
task path: /usr/local/home/niadmin/packages.yml:7
<ws-leeb.ad.nyingma.org> ESTABLISH CONNECTION FOR USER: None on PORT 22 TO ws-leeb.ad.nyingma.org
<ws-leeb.ad.nyingma.org> EXEC /bin/sh -c '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1453686702.79-221069478550614 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1453686702.79-221069478550614 )" )'
<ws-leeb.ad.nyingma.org> PUT /tmp/tmptorHDN TO /home/niadmin/.ansible/tmp/ansible-tmp-1453686702.79-221069478550614/pkgng
<ws-leeb.ad.nyingma.org> EXEC /bin/sh -c 'su  root -c "/bin/sh -c '"'"'echo BECOME-SUCCESS-euyywawtqzdtpwanwnukrkzmdlyqrtbv; /bin/sh -c '"'"'"'"'"'"'"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/local/bin/python /home/niadmin/.ansible/tmp/ansible-tmp-1453686702.79-221069478550614/pkgng'"'"'"'"'"'"'"'"''"'"'"'
failed: [ws-leeb.ad.nyingma.org] => (item=[u'editors/nano', u'net/x11vnc', u'x11/xscreensaver']) => {"failed": true, "invocation": {"module_name": "pkgng"}, "item": ["editors/nano", "net/x11vnc", "x11/xscreensaver"], "module_stderr": "", "module_stdout": "Unmatched \".\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
