### ISSUE TITLE
mount module problem

### ISSUE THREAD

**Issue by itatabitovski** [ansible/ansible#14123]
**Issue Type:** Bug Report

**Ansible Version:** ansible 2.0.0.2

**Ansible Configuration:**
ansible.cfg

```
[defaults]
ansible_managed = Managed by Ansible

forks=30
hostfile=inventory/hosts
host_key_checking = True
hash_behaviour = merge
error_on_undefined_vars=False

library=library
```

**Environment:** debian jessie

**Summary:**

The mount module does not seem to work properly in ansible 2.0.0.2

**Steps To Reproduce:**

```
- name: create swapfile
  command: dd if=/dev/zero of={{ swapfile }} bs=1M count={{ swapfile_size_mb }}
  args:
    creates: '{{ swapfile }}'
  register: dd

- name: set swapfile permissions
  file:
    path: '{{ swapfile }}'
    mode: 0600
    owner: root
    group: root

- name: create swap
  command: 'mkswap {{ swapfile }}'
  when: dd|changed
  register: mkswap

- name: enable swap
  command: 'swapon {{ swapfile }}'
  when: mkswap|changed

- name: add entry in /etc/fstab
  mount:
    name: none
    src: '{{ swapfile }}'
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
```

**Actual Results:**
Using ansible 2.0.0.2 

```
(ansible20)@u330p ~/Projects/ansible-workspace (master *) $ ansible-playbook -vv -i production/hosts playbooks/bootstrap-server.yml
Using /home//Projects/ansible-workspace/ansible.cfg as config file
1 plays in playbooks/bootstrap-server.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [tisiphone]

TASK [swapfile : create swapfile] **********************************************
ok: [tisiphone] => {"changed": false, "cmd": "dd if=/dev/zero of=/swapfile bs=1M count=512", "rc": 0, "stderr": false, "stdout": "skipped, since /swapfile exists", "stdout_lines": ["skipped, since /swapfile exists"]}

TASK [swapfile : set swapfile permissions] *************************************
ok: [tisiphone] => {"changed": false, "gid": 0, "group": "root", "mode": "0600", "owner": "root", "path": "/swapfile", "size": 536870912, "state": "file", "uid": 0}

TASK [swapfile : create swap] **************************************************
skipping: [tisiphone] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [swapfile : enable swap] **************************************************
skipping: [tisiphone] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [swapfile : add entry in /etc/fstab] **************************************
fatal: [tisiphone]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453796164.77-151636494053627/mount\", line 2321, in <module>\r\n    main()\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453796164.77-151636494053627/mount\", line 354, in main\r\n    name, changed = set_mount(module, **args)\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453796164.77-151636494053627/mount\", line 134, in set_mount\r\n    escaped_args = dict([(k, _escape_fstab(v)) for k, v in args.iteritems()])\r\n  File \"/root/.ansible/tmp/ansible-tmp-1453796164.77-151636494053627/mount\", line 110, in _escape_fstab\r\n    return v.replace('\\\\', '\\\\134').replace(' ', '\\\\040').replace('&', '\\\\046')\r\nAttributeError: 'int' object has no attribute 'replace'\r\n", "msg": "MODULE FAILURE", "parsed": false}

PLAY RECAP *********************************************************************
tisiphone : ok=3    changed=0    unreachable=0    failed=1
```

**Expected results:**
To work the same as ansible 1.9.4

```
(ansible19)@u330p ~/Projects/ansible-workspace (master *) $ ansible-playbook -vv -i production/hosts playbooks/bootstrap-server.yml

GATHERING FACTS ***************************************************************
<tisiphone> REMOTE_MODULE setup
ok: [tisiphone]

TASK: [swapfile | create swapfile] ********************************************
<tisiphone> REMOTE_MODULE command creates=/swapfile dd if=/dev/zero of=/swapfile bs=1M count=512
ok: [tisiphone] => {"changed": false, "cmd": "dd if=/dev/zero of=/swapfile bs=1M count=512", "rc": 0, "stderr": false, "stdout": "skipped, since /swapfile exists"}

TASK: [swapfile | set swapfile permissions] ***********************************
<tisiphone> REMOTE_MODULE file group=root path=/swapfile owner=root
ok: [tisiphone] => {"changed": false, "gid": 0, "group": "root", "mode": "0600", "owner": "root", "path": "/swapfile", "size": 536870912, "state": "file", "uid": 0}

TASK: [swapfile | create swap] ************************************************
skipping: [tisiphone]

TASK: [swapfile | enable swap] ************************************************
skipping: [tisiphone]

TASK: [swapfile | add entry in /etc/fstab] ************************************
<tisiphone> REMOTE_MODULE mount opts=sw state=present fstype=swap name=none src=/swapfile
changed: [tisiphone] => {"changed": true, "dump": 0, "fstab": "/etc/fstab", "fstype": "swap", "name": "none", "opts": "sw", "passno": 0, "src": "/swapfile"}

PLAY RECAP *************************************************
```
