### ISSUE TITLE
Ansible 2.0.0.2 command --list-tags shows no tags

### ISSUE THREAD

**Issue by 196194** [ansible/ansible#14125]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible-playbook 2.0.0.2
##### Ansible Configuration:

nothing special
##### Environment:

Debian 8.2
##### Summary:

Ansible-playbook option --list-tags shows no tags
##### Steps To Reproduce:

ansible-playbook -i inventories/tad-hosts 05-apache.yml -l tadprsc01 --list-tags
##### Expected Results:

playbook: 05-apache.yml

  play #1 (apache-hosts):       TAGS: [tag1,tag2,tag3]
      TASK TAGS: [tag1,tag2,tag3]
##### Actual Results:

playbook: 05-apache.yml

  play #1 (apache-hosts):       TAGS: []
      TASK TAGS: []

**Comment by jimi-c** [comment]
Can you share an example of the playbook(s) causing this? It is a known issue that tags from include files do not show up in --list-tags output, so if your playbooks are comprised of all includes this would be expected.

**Comment by a31amit** [comment]
@jimi-c .. Thanks for the info.. I noticed the same problem in my case, I am using roles and there are multiple include files ...

**Comment by briceburg** [comment]
99% of our tags are defined in "included" tasks -- as we organize our playbooks into boilerplate base playbooks that include tasks from shared/non-boilerplate common tasks. The use of `ansible-playbook --list-tags` is prevelant under this architecture and this bug is preventing us from upgrading to 2.0 (which is something we really want to do for the docker connection driver & exception handling). I read that this would be fixed shortly after the release -- any update here?

Thanks!

**Comment by vallettea** [comment]
I upgraded to 2.0.1.0 and I still have the problem.
Here is my configuration in `all.yml`:

```
---
# This playbook deploys all our services

- name: apply common configuration to all nodes (tooling)
  hosts: all
  remote_user: root
  roles:
    - common
  tags: common

- name: deploy a service called immoviz
  hosts: immoviz
  remote_user: root
  vars:
    service_name: immoviz
  roles:
    - immoviz
  tags: immoviz
```

and when I use `ansible-playbook all.yml -t immoviz` the roles of `common` are also played.
