### ISSUE TITLE
Allow copy module to work with recursive and remote_src

### ISSUE THREAD

**Issue by MGD1981** [ansible/ansible#14131]
In Ansible 2.0, when using:

``` yml
copy: src={{src_dir}} dest={{dest_dir}} remote_src=yes
```

Copy module fails with:
`"msg": "attempted to take checksum of directory: <remote source directory>"`

This happens with and without `/` slashes at the ends of both or either directory name, and also whether or not the destination directory exists or not.  Source directory always present and filled with files and subdirectories.

**Comment by fdutheil** [comment]
Bug confirmed here: same test conditions, same effects.

**Comment by jimi-c** [comment]
Hi all, looking into this bug, however when I test it with the following playbook I get a different error (which I believe is the correct error):
<pre>
# cat test.yml 
- hosts: localhost
  gather_facts: no
  tasks:
  - file: path=/tmp/14131/a state=directory
  - file: path=/tmp/14131/a/foo.txt state=touch
  - file: path=/tmp/14131/b state=absent
  - copy: src=/tmp/14131/a dest=/tmp/14131/b remote_src=yes
</pre>
When run, this fails with the following error:
<pre>
TASK [copy] ********************************************************************
task path: /root/testing/14131/test.yml:7
fatal: [awxlocal]: FAILED! => {"changed": false, "failed": true, "msg": "Remote copy does not support recursive copy of directory: /tmp/14131/a"}
</pre>
^ Which is correct, as the copy module does not support copying directories recursively when using remote_src.

Can someone please provide some additional information to help debug or reproduce this, if you're still seeing the problem?

**Comment by jimi-c** [comment]
Note for others, this is not a bug, but a missing feature of the remote_src option.

**Comment by bcoca** [comment]
since the error message has been corrected to inform the user i changed this into a feature request to add this functionality to copy

**Comment by MGD1981** [comment]
Thanks, all.  Yes, I don't believe the module's documentation originally stated that the parameter did not work with recursive copying, but it does now, and more informative errors as you have mentioned.

Thanks @bcoca for changing the status.

**Comment by fubarhouse** [comment]
+1... I seriously need this.

Ansible 2.2.1.0
````
Remote copy does not support recursive copy of directory
````

**Comment by ansibot** [comment]
@MGD1981 Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rstevens011** [comment]
It would be very nice to see this.  I am forced to use the `command` module with `cp -r`.  Details of the error below:

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "backup": false,
            "content": null,
            "delimiter": null,
            "dest": "/usr/local/include/boost/",
            "directory_mode": null,
            "follow": false,
            "force": true,
            "group": null,
            "mode": null,
            "original_basename": null,
            "owner": null,
            "regexp": null,
            "remote_src": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/tmp/mesos-1.2.0/3rdparty/boost-1.53.0/boost/",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "msg": "Remote copy does not support recursive copy of directory: /tmp/mesos-1.2.0/3rdparty/boost-1.53.0/boost/"
```
```
[vagrant@localhost ~]$ ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by MGD1981** [comment]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy module

##### ANSIBLE VERSION
2.0

##### OS / ENVIRONMENT
This was tested both on Ubuntu 14.10 and also on an AWS ec2 instance, I _may_ have also tested it on CentOS 7, but can't be sure.

I _believe_ the Ansible Version was the first iteration of 2.0 -- I mentioned 2.0 in my original post.  I can't say for sure at this point because Ansible has been upgraded on that VM since then.

**Comment by aklemp** [comment]
I also would like to see this feature implemented.
```
Remote copy does not support recursive copy of directory
```
my version
```
ansible 2.3.0.0 (stable-2.3 4b5553c97f) last updated 2017/04/23 13:15:41 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]
```

**Comment by ptux** [comment]
I'll do it!

**Comment by ptux** [comment]
doing this!

**Comment by sprabhuanand** [comment]
+1 to it. I need to execute the shell commands now to do it. But willbe nice

**Comment by sevagh** [comment]
I suggest you use the [synchronize module](https://docs.ansible.com/ansible/latest/synchronize_module.html) as an alternative if you desire remote/remote copy with recursion. I replaced my `command: cp` with that and it's better.

**Comment by aklemp** [comment]
Thank you very much for your hint with ```synchronize```. I tried it but for me it doesn't work for two reasons.

* ```synchronize``` can keep the owner/group or it can assign the owner/group of the executing user (in this case ansible user or root). However, I'd like to set the owner/group to something else and I cannot simply set it afterwards because the destination directory already contains files that I don't want to change owner/group of. Using
  ```
  rsync_opts:
    - "--chown=myuser:mygroup"
  ```
  I could achive the required result but unfortunately, this option was added in rsync 3.1.0 and I cannot update the target system right now.
* I am using the local system as test environment with local access (no ssh) but this is not working as expected. Although I have the current rsync version locally with the required ```chown``` option and it doesn't complain about anything, the files still get the owner/group of the ansible user. It doesn't matter if I specify the owner/group option with ```no```. I have no idea how to resolve that and if this would be the case on the remote host having the current rsync version.

If these issues wouldn't exist, then this would be the command to use.

```
- name: remote copy recursively
  synchronize:
    src: /remotesource/
    dest: /remotetarget
#    owner: no
#    group: no
    rsync_opts:
      - "--chown=myuser:mygroup"
  delegate_to: "{{ inventory_hostname }}"
```

**Comment by fubarhouse** [comment]
I agree with @aklemp.

Syncronise has kept me out of trouble once or twice, however when dealing with a variety of connections (ssh vs local vs vagrant), things become undesirably unreliable with testing and roll-outs.

I usually end up going back to `cp`.

With that said, recursive copy is a nice to have here - should that exclude it from being able to be officially supported longer-term? If the intent is explicit and the person writing and using the playbooks understand what's happening, it should be an option. It shouldn't be dismissed simply because another module is recommended for the same job which does not perform as reliably.

**Comment by pranaynanda** [comment]
Also with `synchronize` , both the source and destination cannot be remote.

**Comment by aklemp** [comment]
@pranaynanda: I tested this with the ```delegate_to: "{{ inventory_hostname }}"``` option and it was copying from the remote to the remote recursively.

**Comment by ptux** [comment]
@aklemp cloud you share your complete code?

> delegate_to: "{{ inventory_hostname }}"

**Comment by aklemp** [comment]
@ptux: please refer to my comment above: https://github.com/ansible/ansible/issues/14131#issuecomment-363393084

**Comment by ptux** [comment]
@aklemp I see, you succeeded  with module `synchronize `,not `cp`.
Thanks.

**Comment by agrimal** [comment]
Just found a workaround for recursive copy from remote to remote : 

```
# Copy all files and directories from /usr/share/easy-rsa to /etc/easy-rsa

- name: List files in /usr/share/easy-rsa
  find:
    path: /usr/share/easy-rsa
    recurse: yes
    file_type: any
  register: find_result

- name: Create the directories
  file:
    path: "{{ item.path | regex_replace('/usr/share/easy-rsa','/etc/easy-rsa') }}"
    state: directory
    mode: "{{ item.mode }}"
  with_items:
    - "{{ find_result.files }}"
  when:
    - item.isdir

- name: Copy the files
  copy:
    src: "{{ item.path }}"
    dest: "{{ item.path | regex_replace('/usr/share/easy-rsa','/etc/easy-rsa') }}"
    remote_src: yes
    mode: "{{ item.mode }}"
  with_items:
    - "{{ find_result.files }}"
  when:
    - item.isdir == False
```

**Comment by ptux** [comment]
@abadger 
I'm working on it and testing it myself now.
Could you assign this issue to me?

**Comment by ptux** [comment]
@sprabhuanand
@fubarhouse
@aklemp
I have added this feature at #41222
would you guys like to test it?

**Comment by fubarhouse** [comment]
@ptux That is working very nicely.

It should be noted that it only appears to be working **only** when `recursive` isn't specified.

Would it be better to make use of a recurse key/value to ensure the explicit intentions of the play runner with a sensible default? I'm quite happy for this to be used - however I'm not sure if others would unanimously expect the behaviour.

Here's the playbook which was used to test the updated module:
```
- hosts: localhost
  become: false

  tasks:
    - name: create directory
      file:
        state: directory
        path: "/Users/fubarhouse/vagrant/provisioning2"

    - name: Copy the directory
      copy:
        src: "/Users/fubarhouse/vagrant/provisioning/"
        dest: "/Users/fubarhouse/vagrant/provisioning2/"
        remote_src: yes
```

And the result, if it matters:
```
PLAY RECAP **********************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```
