### ISSUE TITLE
user module: ansible-pull issue with user home directory ownership

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#14137]
##### Issue Type:
- Bug Report
##### Environment:

Controller : OSX 10.11.03
Target : CentOS 6.X
Ansible :  2.0.0.2
##### Summary:

We use ansible pull to run our security role as a cronjob every 15 minutes where we create our user accounts and deploy their ssh public keys.

Since we upgrade to Ansible 2 we are having issues to login to new instances, it seems ansible-pull create the user home directories with a different UID/GUID ownership . This is preventing normal users to login since each user public key is located in their home directory and cannot be read.

Testing Ansible in push mode (ansible-playbook) I don't see this issue , it seems to only happening when you run the same through ansible-pull on version 2.
##### Steps To Reproduce:

```
roles/security/tasks/main.yml 

- name: ssh-users | Make sure the users are present
  user:
    name: "{{ item.name }}"
    groups: "{{ ','.join(item.groups) }}"
    uid: "{{ item.uid | default(omit) }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    comment: "{{ item.comment | default('') }}"
    password: "{{ item.password | default('') }}"
    state: present
  with_items: ssh_users
```
# roles/security/vars/main.yml

```
ssh_users:
  - name: "alex"
    groups: ["users"]
    comment: "Alex"
    shell: "/bin/bash"
  - name: "nic"
    groups: ["users"]
    comment: "Nic"
    shell: "/bin/bash"
  - name: "john"
    groups: ["users"]
    comment: "Jon"
    shell: "/bin/bash"
```
##### Expected Results:

ssh nic@54.183.190.197

```
Warning: Permanently added '54.183.190.197' (RSA) to the list of known hosts.
Last login: Tue Jan 26 20:07:59 2016 from 61.73.58.112
```

ls -l /home/

```
drwx------. 3             alex               alex               4096 Jan 26 20:15 alex
drwx------. 3               nic               nic                 4096 Jan 26 20:15 nic
drwx------. 3             john               john               4096 Jan 26 20:15 john
```
##### Actual Results:

ssh nic@54.183.190.197

```
Warning: Permanently added '54.183.190.197' (RSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

ssh root@54.183.190.197
ls -l /home/

```
drwx------. 2            507            507 4096 Jan 26 20:05 alex
drwx------. 2            511            511 4096 Jan 26 20:05 nic
drwx------. 2            520            520 4096 Jan 26 20:05 john
```

**Comment by bcoca** [comment]
my guess here is that Ansible is now correctly respecting the user's umask, which might be set differently for root on the cron job vs your push (sudo/root interactive login?).

**Comment by nicolas-g** [comment]
AFAIK umask is only for file access permissions rwx and nothing to do with ownership , I expect when you create a user and it's home dir using the user module it will also make sure the home dir is owned by the user or else it's kind of pointless.

**Comment by bcoca** [comment]
yes, sorry, misunderstood as i was only looking at access permissions ... what users do the uids listed correspond to?

**Comment by nicolas-g** [comment]
it seems completely random , some time users home dirs are owned by other users  , some users home dirs are set correctly .

**Comment by bcoca** [comment]
So unlike the permissions, the uid is set explicitly in this case, i cannot see how the code would do this unless it is getting different inputs (or the name to uid mapping changes underneath it).

I don't think this is strictly an issue with ansible, can you log the item.uid (you don't show this in your vars) across runs? can you also add a call to the `getent` module to dump the passwd database?

**Comment by nicolas-g** [comment]
the way I overcome this issue was by strictly setting a UID for each user manually which works but when I opened this issue I was using the default omit filter option : 

```
uid: "{{ item.uid | default(omit) }}"
```

As I said this was working fine with Ansible 1.9 for both push and pull mode , it got broken with Ansible 2 for pull mode only.

**Comment by bcoca** [comment]
broken for pull only doesn't make sense as pull just calls ansible-playbook, but I think there might be 2 possible causes for this, either `omit` is not working or the user module has been updated to care about `uid` even when not specified. 

The reason it might be different for pull vs push might be the version of ansible installed on the machine is different than the one used for pushing.

**Comment by nicolas-g** [comment]
I can confirm the ansible version on the controller and target machine was the same for the push and pull .

**Comment by meetmatt** [comment]
Having a variation of mentioned issue.

Controller: Ubuntu 16.04
Target: CentOS 7.2
Ansible: 2.1.1.0

The difference is that in my case users always get ownership of the home dir set to UID 1000. GID is correct however. Also user's mail directory `/var/spool/mail/{user}` has the same wrong UID also.
I suppose that the issue is with `uid: {{ var | default(omit) }}`.

I am using https://galaxy.ansible.com/GROG/management-user which in turns uses https://galaxy.ansible.com/GROG/user/ which calls user module with uid default(omit):

``` yaml
- name: Manage user
  user:
    # ...
    uid: "{{ item.uid | default(omit) }}"
```

Quick and dirty fix which obviously works is to manually change ownership after the role:

``` yaml
- name: Create and remove users
  # ...
  roles:
    - { role: GROG.management-user }
  tasks:
    - name: Fix home directories ownership
      file:
        path: "/home/{{ item }}"
        owner: "{{ item }}"
      with_items:
        - alice
        - bob
    - name: Fix mail ownership
      file:
        path: "/var/spool/mail/{{ item }}"
        owner: "{{ item }}"
      with_items:
        - alice
        - bob
```
