### ISSUE TITLE
Ansible 2.0.0.2: Nested include + with_items does not work properly

### ISSUE THREAD

**Issue by moorglade** [ansible/ansible#14146]
##### Issue Type:

Bug report
##### Ansible Version:

ansible 2.0.0.2
ansible 2.1.0 (devel 7e3963420d)
##### Ansible Configuration:

N/A
##### Environment:

Ubuntu 15.10
##### Summary:

Ansible 2.0 added a feature to use _include_ statements together with _with_items_ loops. When nesting _include_ statements, (i.e. file _A.yml_ includes _B.yml_, which includes _C.yml_) the _item_ variable is not set properly, i.e. the inner _include_ + _with_items_ loop does not override the _item_ value from the outer loop.
##### Steps To Reproduce:

_main.yml_

``` yaml

---
- include: include_outer.yml
  with_items:
    - 1
    - 2
    - 3
```

_include_outer.yml_

``` yaml

---
- debug:
    msg: "Outer include: item={{ item }}"

- include: include_inner.yml
  with_items:
    - A
    - B
    - C
```

_include_inner.yml_

``` yaml

---
- debug:
    msg: "Inner include: item={{ item }}"
```
##### Expected Results:

```
"msg": "Outer include: item=1"
"msg": "Inner include: item=A"
"msg": "Inner include: item=B"
"msg": "Inner include: item=C"
"msg": "Outer include: item=2"
"msg": "Inner include: item=A"
"msg": "Inner include: item=B"
"msg": "Inner include: item=C"
"msg": "Outer include: item=3"
"msg": "Inner include: item=A"
"msg": "Inner include: item=B"
"msg": "Inner include: item=C"
```
##### Actual Results:

```
"msg": "Outer include: item=1"
"msg": "Inner include: item=1"
"msg": "Inner include: item=1"
"msg": "Inner include: item=1"
"msg": "Outer include: item=2"
"msg": "Inner include: item=2"
"msg": "Inner include: item=2"
"msg": "Inner include: item=2"
"msg": "Outer include: item=3"
"msg": "Inner include: item=3"
"msg": "Inner include: item=3"
"msg": "Inner include: item=3"
```

**Comment by jimi-c** [comment]
This is documented in the loops documentation as a limitation (along with suggested work around for different scenarios): http://docs.ansible.com/ansible/playbooks_loops.html#loops-and-includes

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by moorglade** [comment]
The documentation states:
"There are a couple of things that you need to keep in mind, a included task that has it’s own with_ loop will overwrite the value of the special item variable."

This is _not_ the issue I have encountered, as far as I understand. Sorry if my description was unclear.

**Comment by jimi-c** [comment]
This is a bit different, as you have an extra depth of include without looping in the inner-most include. Regardless, if you want to do this, you need to save the item variable from the outside loop, and don't use the variable name `item` as the param to the inner include.

**Comment by moorglade** [comment]
Still, I think it's a different problem. The _item_ variable does **not** get overwritten in the inner include, i.e. instead of the three values from the inner loop (A, B, C), I get the outer loop value repeated three times. There is no way I can pass values to the inner loop. 

I modified my example to better illustrate the case:

_main.yml_

``` yaml
- include: include_outer.yml
  with_items:
    - 1
    - 2
    - 3
```

_include_outer.yml_

``` yaml
---
- debug:
    msg: "Outer include: item={{ item }}"

- set_fact:
    outer_loop: "{{ item }}"

- include: include_inner.yml
  vars:
    inner_item: "{{ item }}"
    outer_item: "{{ outer_loop }}"
  with_items:
    - A
    - B
    - C
```

_include_inner.yml_

``` yaml
---
- debug:
    msg: "Inner include: inner_item={{ inner_item }}, outer_item={{ outer_item }}"
```

The result:

```
"msg": "Outer include: item=1"
"msg": "Inner include: inner_item=1, outer_item=1"
"msg": "Inner include: inner_item=1, outer_item=1"
"msg": "Inner include: inner_item=1, outer_item=1"
"msg": "Outer include: item=2"
"msg": "Inner include: inner_item=2, outer_item=2"
"msg": "Inner include: inner_item=2, outer_item=2"
"msg": "Inner include: inner_item=2, outer_item=2"
"msg": "Outer include: item=3"
"msg": "Inner include: inner_item=3, outer_item=3"
"msg": "Inner include: inner_item=3, outer_item=3"
"msg": "Inner include: inner_item=3, outer_item=3"
```

**Comment by moorglade** [comment]
Another example:

_main.yml_

``` yaml
---
- set_fact:
    item: "some_item_value"

- include: include_with_items.yml
  vars:
    my_item_value: "{{ item }}"

  with_items:
    - loop_item_value_1
    - loop_item_value_2
    - loop_item_value_3
```

_include_with_items.yml_

``` yaml
---
- debug:
    msg: "my_item_value={{ my_item_value }}"
```

Result:

```
"msg": "my_item_value=some_item_value"
"msg": "my_item_value=some_item_value"
"msg": "my_item_value=some_item_value"
```

**Comment by gregsymons** [comment]
I've encountered this issue too, and I'm not even referencing the outer item in the nested include: See [this gist](https://gist.github.com/gregsymons/741cdf7069bffd4221fb) for a working example with expected and actual output.

Can we get this issue reopened so that someone might actually work on it?

**Comment by asorbini** [comment]
+1 for reopening the issue. I'm experiencing the same issue as @moorglade and it is not what the Documentation discusses.

**Comment by stewartm** [comment]
+1 for reopening the issue. Apologies @moorglade, I had not spotted this bug report when I duplicated with my own.

> Regardless, if you want to do this, you need to save the item variable from the outside loop, and don't use the variable name item as the param to the inner include.

This does suggest that the issue has been misinterpreted, as in my own example in #14325, like @gregsymons, my inner include loop is referencing a variable outside the parent loop and is not dependent on 'item' from the parent.

The fundamental issue is that contrary to the docs, the 'item' variable will **not** get overwritten for a nested include passed a loop, where as it **will** for any other nested task passed a loop.

**Comment by alinhle** [comment]
I just ran into this with ansible 2.0.1.0 :-(

**Comment by rcarrillocruz** [comment]
I'm hitting this from devel too :(

**Comment by arthurtsang** [comment]
same here.

**Comment by amather** [comment]
Same here. As a workaround, I've switched to devel with the [`feature_make_loop_variable_settable_per_task`](https://github.com/ansible/ansible/commit/57eb5e1feae3f7c9a3bc52232af3b54674d19407)  feature applied. Having a `loop_var` parameter seems to be the cleaner solution anyway. 

@jimi-c Is the `loop_var` feature going to make it into 2.1? At time of [this comment](https://github.com/ansible/ansible/issues/12736#issuecomment-150557252) the decision was still open.

**Comment by nethershaw** [comment]
+1 for the `loop_var` feature from [feature_make_loop_variable_settable_per_task](https://github.com/ansible/ansible/commit/57eb5e1feae3f7c9a3bc52232af3b54674d19407). This feature branch is working for me. The topology of a network I'm building with Ansible requires include loops two layers deep; otherwise unrolling those loops gets very, very ugly and unwieldy. With this I can loop at arbitrary depths and still inherit variables properly.

**Comment by jimi-c** [comment]
Yes I plan on having it in 2.1.

**Comment by jimi-c** [comment]
@amather / @nethershaw after some internal discussions, I've created the branch `feature_make_loop_variable_settable_per_task2`, which starts implementing something we were going to do in Ansible 2.2. Essentially, we wanted a standardized way to give args to lookup plugins used in loops, so we've introduced the `loop_control` setting for tasks. Right now, for 2.1, this option will only support the `loop_var` setting, as follows:

<pre>
- hosts: localhost
  gather_facts: no
  tasks:
  - command: echo '{{item_foo}}'
    with_items:
    - a
    - b
    - c
    loop_control:
      loop_var: item_foo
</pre>

We felt it was better to go ahead and implement this now rather than 1 version later, in which case everyone would need to update their playbooks (or deal with deprecation messages).

Give it a try and let me know what you think.

**Comment by nethershaw** [comment]
@jimi-c Most excellent. I gave this a spin today on my playbooks that contain nested includes and `with_items` loops, just as your example, and the `loop_control` task attribute worked at all levels. It even worked alongside `with_dict`. Thank you!

**Comment by jimi-c** [comment]
The above loop_control/loop_var branch has been merged into devel, however we're holding this issue open as we are interested in why the bug is occurring.

**Comment by windowsrefund** [comment]
Can someone provide an example of this fix working using with_dict:? My experiments are failing as seen here: https://github.com/ansible/ansible/commit/6eefc11c3954cbdd2f439c0fad0b9527461b4383#commitcomment-17163490

**Comment by nethershaw** [comment]
@windowsrefund In this example, an outer loop in a task playbook called `loop_vpn.yml` includes another playbook called `loop_vpn_instance.yml` using `with_items` like so:

``` yaml
# file: loop_vpn.yml
- name: "{{ stack.name }} {{ region }} : configure VPN endpoint cluster nodes"
  include: loop_vpn_instance.yml
  with_items:
    - "{{ region_map_vpn[region]['EIP1'] }}"
    - "{{ region_map_vpn[region]['EIP2'] }}"
  loop_control:
    loop_var: item_instance
  tags:
    - configure
```

Within the included playbook, this task using `with_dict` must create several configuration files on the delegated machine using a template populated by the contents of a dictionary called `region_map_vpn`, which happens to be the same dictionary from which the two items in the outer loop were selected:

``` yaml
# file: loop_vpn_instance.yml
- name: "{{ stack.name }} {{ region }} : {{ item_instance }} : configure VPN connections"
  template:
    src: regionL-regionR.conf.j2
    dest: /etc/ipsec.d/{{ region | replace('-', '') }}-{{ item_region_remote.key | replace('-', '') }}.conf
    owner: root
    group: root
    mode: 0644
  delegate_to: "{{ item_instance }}"
  with_dict: "{{ region_map_vpn }}"
  loop_control:
    loop_var: item_region_remote
  when: region != item_region_remote.key
```

For context, all of this occurs within a still larger loop that iterates over several Amazon AWS regions within a global stack where `region` is a key set by the outermost loop. Its purpose is to create a VPC in each region and establish a management network of IPSec tunnels between them.

This example has worked flawlessly in all of my testing.

**Comment by windowsrefund** [comment]
@nethershaw Hello, and thanks for the response. I'm not sure your example relates to the problem I've discovered as it appears your use of the iterators is limited to 2 levels. If you look at the example I've posted above, you'll see I'm actually trying to dig into the data I'm iterating over.

**Comment by windowsrefund** [comment]
I'm actually starting to have some success. Either I'm figuring this out or am completely wrong and will update this thread soon with my findings.

**Comment by rcarrillocruz** [comment]
@jimi-c so far so good, thanks a bunch for this!

**Comment by tkinz27** [comment]
So I have a bunch of roles that use dynamic task includes to include a set of tasks based on the platform of the remote host. In this case I do not care at all what the outer loop variable is and would prefer to just overwrite the loop variable. 

I just started using ansible from devel and noticed that my roles are failing with this error now.

```
fatal: [10.64.3.116]: FAILED! => {"failed": true, "msg": "the loop variable 'item' is already in use. You should set the `loop_var` value in the `loop_control` option for the task to something else to avoid variable collisions"}
```

Is it going to be required that `loop_var` be set even if I'm perfectly ok with the `loop_var` being overwritten?

[EDITED]
So just found the Note on http://docs.ansible.com/ansible/playbooks_loops.html#loop-control. Could it be possible to add an ansible.cfg option to disable that check?

**Comment by jimi-c** [comment]
@tkinz27 I agree, so I've gone ahead and changed that error to a warning:

<pre>
TASK [test : include] **********************************************************
task path: /root/testing/14146/roles/test/tasks/include_outer.yml:8
 [WARNING]: The loop variable 'item' is already in use. You should set the `loop_var` value in the `loop_control` option for the task to something else to avoid variable collisions and
unexpected behavior.
</pre>

Since this overall appears to have resolved the stated issue, we're going to go ahead and close this now. If you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by bence-takacs** [comment]
Hi, Guys

The same issue with 'ansible 2.1.0.0'

Inside the internal loop the outer_item seems to be overwritten.
But outside everything is fine

outside.yaml:

```
---
- include: inside.yaml my_inner_item={{item}}
  with_items: 
    - A
    - B
    - C
```

inside.yaml:

```
---
- debug: msg="{{my_inner_item}} with {{ item }} is defined"
  with_items:
    - 1
    - 2
    - 3

- debug: msg="{{my_inner_item}} is defined"
```

output:

> TASK [win-service : debug] *****************************************************
>  [WARNING]: The loop variable 'item' is already in use. You should set the `loop_var` value in the `loop_control` option for the task
> to something else to avoid variable collisions and unexpected behavior.
> 
> ok: [myhost] => (item=1) => {
>     "item": 1,
>     "msg": "1 with 1 is defined"
> }
> ok: [myhost] => (item=2) => {
>     "item": 2,
>     "msg": "2 with 2 is defined"
> }
> ok: [myhost] => (item=3) => {
>     "item": 3,
>     "msg": "3 with 3 is defined"
> }
> 
> TASK [win-service : debug] *****************************************************
> 
> ok: [myhost] => {
>     "msg": "A is defined"
> }

**Comment by tjbenator** [comment]
@bence-takacs,

You need to use loop control:
http://docs.ansible.com/ansible/playbooks_loops.html#loop-control

outside.yaml:

```
---
- include: inside.yaml my_inner_item={{outer_item}}
  with_items: 
    - A
    - B
    - C
  loop_control:
    loop_var: outer_item
```

inside.yaml:

```
---
- debug: msg="{{my_inner_item}} with {{ item }} is defined"
  with_items:
    - 1
    - 2
    - 3

- debug: msg="{{my_inner_item}} is defined"
```
