### ISSUE TITLE
--limit restricts visibility to hostvars not in the catalogue for the current run

### ISSUE THREAD

**Issue by coxley** [ansible/ansible#14141]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9.4
```

Upgraded to v2.0.0.2 with some outcome.
##### Ansible Configuration:

``` ini
[defaults]
ansible_managed = This section managed by Ansible
fact_caching = jsonfile
fact_caching_connection = fact_cache
fact_caching_timeout = 86400
filter_plugins = ./plugins/filter_plugins
inventory = ./scripts/inventory.py
nocows = 1
```
##### Environment:

Doesn't really apply, but:

Ubuntu 10.04, Python 2.7, connection=local to generate fragments and assemble.
##### Summary:

From my research, `hostvars` should contain all YAML defined vars for all hosts even for `ansible-playbook` runs which specify `--limit` - It is what I'd expect also.

This is **not** concerning gathered facts and caching which a different issue (though those don't show either)

I'm trying to access defined variables in templates on other hosts while running `--limit` for faster debugging and targeted executions. 

If we have `host_vars/{hostA,hostB,hostC}.yml` and a template task running on hostA doing `{{ hostvars['hostB'] }}`, it will not contain host-specific YAML vars.

Removing the limit, it acts as you'd expect
##### Steps To Reproduce:

**Command**: `ansible-playbook -v -e set_some_vars=1 playbooks/play.yml --skip-tags=remote --ask-vault-pass --limit=hostname`

**Template** - The rest of the content isn't really relevant, this is what I'm using to test.

``` jinja2
HOSTA
-----
{{ hostvars[inventory_hostname] | to_nice_json }}

HOSTB
-----

{{ hostname['hostB'] | to_nice_json }}


```

**Role Task**:

``` yaml

---
- name: BGP | Configuring BGP
  template: src=bgp.j2 dest={{ fragments_dir }}/{{ inventory_hostname }}/bgp.conf
```

**Playbook**

``` yaml

---
- name: Build BGP Config
  hosts: all
  gather_facts: no
  connection: local
  roles:
  - bgp

```
##### Expected Results:

I would expect to see both group 'all' vars and host specific vars under both returned host dicts
##### Actual Results:

Actual results show all host vars for the --limit host (hostA), but hostB only has the group-level vars and is missing the host-specific (host_vars/hostB.yml) ones.
