### ISSUE TITLE
Hash calculation failed unusually in copy module

### ISSUE THREAD

**Issue by EraYaN** [ansible/ansible#14156]
This happened in my last run, I can't get it to happen again. But it asked to be reported so here it is.

```
 [WARNING]: Calculating checksum failed unusually, please report this to the list so it can be fixed command: rc=flag; [ -r /usr/share/nginx/html/global_error_pages/416.html ] ||
rc=2; [ -f /usr/share/nginx/html/global_error_pages/416.html ] || rc=1; [ -d /usr/share/nginx/html/global_error_pages/416.html ] && rc=3; python -V 2>/dev/null || rc=4; [ x"$rc" !=
"xflag" ] && echo "${rc}  "/usr/share/nginx/html/global_error_pages/416.html && exit 0; (python -c 'import hashlib; BLOCKSIZE = 65536; hasher = hashlib.sha1(); afile =
open("'/usr/share/nginx/html/global_error_pages/416.html'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:         hasher.update(buf)         buf = afile.read(BLOCKSIZE)
afile.close() print(hasher.hexdigest())' 2>/dev/null) || (python -c 'import sha; BLOCKSIZE = 65536; hasher = sha.sha(); afile =
open("'/usr/share/nginx/html/global_error_pages/416.html'", "rb") buf = afile.read(BLOCKSIZE) while len(buf) > 0:         hasher.update(buf)         buf = afile.read(BLOCKSIZE)
afile.close() print(hasher.hexdigest())' 2>/dev/null) || (echo '0  '/usr/share/nginx/html/global_error_pages/416.html) ---- output: {'stdout_lines': [u''], 'stdout': u'\r\n',
'stderr': u'', 'rc': 0} ----

```

**Comment by jimi-c** [comment]
With which version of Ansible did you get this error? If you can find anyway to reproduce it, we'd appreciate it.

**Comment by EraYaN** [comment]
```
ansible 2.1.0 (devel 6b166a1048) last updated 2016/01/24 21:30:11 (GMT +200)
  lib/ansible/modules/core: (devel 76925ef613) last updated 2016/01/24 21:31:38 (GMT +200)
  lib/ansible/modules/extras: (devel d02e26c38f) last updated 2016/01/24 21:31:40 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

It completely took me by surprise, but the fact that the permissions on every file that ansible creates are super weird might be the issue, or related.

Here is the playbook part:

```
  - name: Create error pages directory and set permissions (this is because the next command failed to create the directory, damn you copy)
    file:
      path: /usr/share/nginx/html/
      state: directory
      owner: user
      group: erayan
      recurse: yes
      mode: "u=rw,g=rw,o=rx" # the x for the directory so I can cd to it.

  - name: Synchonize nginx global_error_pages with remote
    copy:
      src: nginx_html/
      dest: /usr/share/nginx/html/
      force: yes
      owner: user
      group: erayan
      mode: "u=rw,g=rw,o=rX" # the X for the directories so I can cd to that directory.
```

Well as you can see I had some problems with the copy module already, weird permission errors or it behaving differently if the destination directory already existed. The rsync module seemed to solve some problems but that did want to connect due to ssh errors after like the 10th run.

```
#>grep 'erayan' /etc/group
erayan:x:1001:root,www-data,user
```
