### ISSUE TITLE
Ansible 2.0.0.2 : "ERROR! file or module does not exist" while running a playbook with script module

### ISSUE THREAD

**Issue by ankitmth** [ansible/ansible#14151]
After installing ansible 2.0.0.2 from rpm:

```
[root@ansibletest setup]# ansible-playbook --version
ansible-playbook 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

I get the below error on running the playbook which uses the script module:

```
[root@ansibletest setup]# ansible-playbook test.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
Enter passphrase for key '/root/.ssh/id_rsa':
ok: [192.168.2.101]

TASK [Run test.sh script] ****************************************************
fatal: [192.168.2.101]: FAILED! => {"failed": true, "msg": "ERROR! file or module does not exist: /path/to/script/test.sh"}

PLAY RECAP *********************************************************************
192.168.2.101              : ok=1    changed=0    unreachable=0    failed=1
```

 The Playbook in question: -

```

---
- hosts: 192.168.2.101
  remote_user: root
  vars:
    var1: data
    param1: 1
  tasks:
    - name: Run test.sh script
      become: yes
      script: /{{ var1 }}/path/to/test.sh {{ param1 }} creates=/{{ var1 }}/{{ param1 }}/executed.txt
```

**Comment by bcatubig** [comment]
```
11:21 # ansible --version
ansible 2.0.0.2
```

Confirming this issue as well. Temporarily using the `command` module to call the script in the meantime.

I am copying a script called `ae_linux_scan.sh` to `/tmp`. It looks like Ansible `script` module is not looking in the `/tmp` directory but rather somewhere else. Here is some included error output.

```
<server1.example.com> PUT /tmp/ae_linux_scan.sh TO /root/.ansible/tmp/ansible-tmp-1454087724.44-4313368474054/ae_linux_scan.sh
fatal: [server1.example.com]: FAILED! => {"failed": true, "msg": "ERROR! file or module does not exist: /tmp/ae_linux_scan.sh"}
```

**Comment by bbyhuy** [comment]
Confirming also I have a python script sitting in roles/myrole/files/script.py and running into same issue. Was not an issue before.

```
fatal: [192.168.200.14]: FAILED! => {"failed": true, "msg": "file or module does not exist: /home/vagrant/project_tutor/tutor/parser.py"}
```

**Comment by dagwieers** [comment]
I cannot reproduce this using Ansible v2.0.0.2.

``` yaml
- hosts: localhost
  gather_facts: no
  remote_user: root                                                                                                                                         
  vars:
    path: dag
    arg: 1
  tasks:
  - script: /home/{{ path }}/home-made/ansible.{{ path }}/test.sh {{ arg }}
    become: yes
```

And this results in:

```
[dag@moria ansible.dag]$ ansible --version
ansible 2.0.0.2
  config file = /home/dag/home-made/ansible.dag/ansible.cfg
  configured module search path = Default w/o overrides

[dag@moria ansible.dag]$ ansible-playbook -vv -K test55.yml
Using /home/dag/home-made/ansible.dag/ansible.cfg as config file
SUDO password: 
1 plays in test55.yml

PLAY ***************************************************************************
changed: [localhost] => {"changed": true, "rc": 0, "stderr": "", "stdout": "Test works !\r\n", "stdout_lines": ["Test works !"]}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```
