### ISSUE TITLE
delegate_to with hosts from with_items not working correctly

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#14166]
Fresh checkout:

```
$ ansible-playbook --version                                    (12:39:21)
ansible-playbook 2.1.0 (devel 6bf2f45ff5) last updated 2016/01/27 11:43:50 (GMT -700)
```

following playbook:

```
- hosts: localhost
  vars:
    mhosts:
      - 192.168.122.160
      - 192.168.122.222
  gather_facts: False
  tasks:
   - command: hostname
     delegate_to: "{{ item }}"
     with_items: "{{ mhosts }}"
```

Following ouptut is generated:

```
$ ansible-playbook -i ',' 2832.yml -v                                  (12:42:50)
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY ***************************************************************************

TASK [command] *****************************************************************
changed: [localhost -> 192.168.122.160] => (item=192.168.122.160) => {"changed": true, "cmd": ["hostname"], "delta": "0:00:00.001582", "end": "2016-01-27 12:43:11.328723", "item": "192.168.122.160", "rc": 0, "start": "2016-01-27 12:43:11.327141", "stderr": "", "stdout": "rhel6.lan", "stdout_lines": ["rhel6.lan"], "warnings": []}
changed: [localhost -> 192.168.122.222] => (item=192.168.122.222) => {"changed": true, "cmd": ["hostname"], "delta": "0:00:00.001696", "end": "2016-01-27 12:43:11.446695", "item": "192.168.122.222", "rc": 0, "start": "2016-01-27 12:43:11.444999", "stderr": "", "stdout": "rhel6.lan", "stdout_lines": ["rhel6.lan"], "warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

The metadata says that the task is being run on each of the hosts listed in the hosts variable.  But the stdout_lines indicate that the task is being run twice on the same host.

This seems related to https://github.com/ansible/ansible/issues/13880 but that issue was fixed.
