### ISSUE TITLE
combine_vars merging on unicode as reported by assert

### ISSUE THREAD

**Issue by retr0h** [ansible/ansible#14167]
We use a custom vars plugin as referenced by a similar issue at #13873.  It looks as though the fix utilizing `combine_vars` at #13902, returns unicode characters as reported by assert.

One must run our callback plugin to replicate our error.  The var `plugin_vars_default_list` referenced below had a dictionary merged into it by the vars plugin.

```
  - hosts: all
    tasks:
      - name: Test appends list
        assert:
          that:
            - "{{ plugin_vars_default_list }} == [{'foo': 'one'}, {'bar': 'two'}, {'baz': 'three'}]"
```

```
TASK [Test appends list] *******************************************************
fatal: [plugin-vars-default]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check '[{'foo': 'one'}, {'bar': 'two'}, {u'baz': u'three'}] == [{'foo': 'one'}, {'bar': 'two'}, {'baz': 'three'}]' failed. The error was: ERROR! template error while templating string: expected token ':', got 'string'"}
```
