### ISSUE TITLE
stdout_lines + sudo

### ISSUE THREAD

**Issue by doertedev** [ansible/ansible#14163]
Installing a certain kernel, removing all the other ones from an ubuntu instance I came across this gem:

``` yaml
- raw: "dpkg -l 'linux*' | egrep '(ii)' | cut -d ' ' -f 3 | grep -v '3.13.0-65' | grep '3.13'"
  sudo: yes
  register: other_kernels

- raw: "apt-get remove --purge -y {{item}}"
  sudo: yes
  with_items: other_kernels.stdout_lines
```

STDOUT:

```
ok: [$ipaddr] => {
    "other_kernels": {
        "changed": false, 
        "rc": 0, 
        "stderr": "", 
        "stdout": "linux-headers-3.13.0-74\r\nlinux-headers-3.13.0-74-generic\r\nlinux-image-3.13.0-74-generic\r\n", 
        "stdout_lines": [
            "BECOME-SUCCESS-grgwsaqfqpjxizctaameruhofsquhcza", 
            "linux-headers-3.13.0-74", 
            "linux-headers-3.13.0-74-generic", 
            "linux-image-3.13.0-74-generic"
        ]
    }
}
```

Which ofc failed because of the BECOME-SUCCESS-part.

I'm running ansible 2.0.0.2: (pip)

```
ansible==2.0.0.2
ansible-lint==2.3.0
awscli==1.9.15
boto==2.38.0
botocore==1.3.15
colorama==0.3.3
docutils==0.12
ecdsa==0.13
flake8==2.5.1
Jinja2==2.8
jmespath==0.9.0
MarkupSafe==0.23
mccabe==0.3.1
netaddr==0.7.18
paramiko==1.16.0
pbr==1.8.1
pep8==1.7.0
pyasn1==0.1.9
pycrypto==2.6.1
pyflakes==1.0.0
python-dateutil==2.4.2
PyYAML==3.11
rsa==3.2.3
simplejson==3.8.1
six==1.10.0
ssh2==1.3
sshtunnel==0.0.6
stevedore==1.10.0
virtualenv==14.0.1
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
wheel==0.24.0
```
