### ISSUE TITLE
failures on ansible_connection=local hosts _stops_ playbook

### ISSUE THREAD

**Issue by DaCookie4u** [ansible/ansible#14162]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Updated from 1.9.4 to 2.0.0.2
##### Environment:

N/A
##### Summary:

We are using ansible to deploy our junos devices. So a big part of our inventory uses `ansible_connection=local`.

When running a playbook with multiple plays on our junos hosts and one of the tasks fails for a host (because of a missing fact or whatever), the host will be left out for all other tasks (as expected). But the next play in the playbook will not start for any host.

Under 1.9.4 the next play would be processed simply skipping previously failed hosts.

I created a very simple example which allows to easily reproduce the problem with a linux host.
###### Inventory

```
[junos]
# via ssh reachable hosts
10.118.194.11 ansible_connection=local
10.118.194.12

# any unused ip
10.118.194.13 ansible_connection=local
```
###### Playbook

```

---
- name: play1
  hosts: junos
  gather_facts: no
  tasks:
    - name: task1
      wait_for: host={{ inventory_hostname }} port=22 timeout=5
    - name: task2
      wait_for: host={{ inventory_hostname }} port=22 timeout=5

- name: play2
  hosts: junos
  gather_facts: no
  tasks:
    - name: task3
      wait_for: host={{ inventory_hostname }} port=22 timeout=5
```
##### Expected Results:

Expected result would be that the playbook fails on `task1` for host `10.118.194.13` thus skipping `task2` and `task3` for this host, while running all tasks for the other two hosts.
##### Actual Results:

As expected `task2` is skipped for `10.118.194.12`, but `play2` is not starting at all (ansible-devel even reports `NO MORE HOSTS LEFT`).

Using ansible-1.9.4 the result is as expected.

Removing the `ansible_connection=local` from host `10.118.194.13` the result is also as expected
