### ISSUE TITLE
Variable Task Params

### ISSUE THREAD

**Issue by identifystation** [ansible/ansible#14187]
It looks like the use of variable task params is deprecated as of 2.0, and scheduled for removal in 2.2. I understand there are security implications, but this removal will break a very useful pattern that allows one to pass list of dictionaries with different key/value combinations to a module, and have them parsed accordingly.  Here's a simple example that would quickly become unruly without variable task params:

``` yaml
- hosts: localhost
  vars:
    percona_dbs_to_create:
      - name: test1
        encoding: utf8
        collation: utf8_general_ci
        login_host: 192.168.222.2

      - name: test2
        encoding: utf8
        collation: utf8_general_ci

  tasks:
    - name: Create databases
      action: mysql_db
      args: "{{ item }}"
      with_items: percona_dbs_to_create
```

We use it very similarly to how dict unpacking is used in Python.

Is there a safe alternative that could be used? Or, perhaps, could this behavior be retained as non-default, and enabled using a config flag? The example provided in the porting guide won't work in this case.
