### ISSUE TITLE
Register strips spaces

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#1421]
When I register a variable from a command the spaces at the beginning of the output are stripped.

Example:

```
tasks:
    - name: Figlet name
      command: /usr/bin/figlet -c -w 80 ${ansible_hostname}
      register: figlethost
```

When I use the `figlethost` variable in a template the first line is mangled.

I do understand that there are times when stripping spaces is needed, but maybe it's a good idea to to make this an option.
