### ISSUE TITLE
delegate_to does not work on synchronize

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#14254]
Continued from #14092, this was suggested as a way to circumvent the deprecation warning when using rsync to synchronize locally on the remote machine...

It doesn't work, since delegate_to is apparently not supported for `synchronize`

**Comment by abadger** [comment]
It sounds like you are doing this:

```
- tasks:
    - synchronize:
          src: /source
          dest: /destination
          delegate_to: "{{ inventory_hostname }}"
```

You need to do this (note the indentation of delegate_to):

```
- tasks:
    - synchronize:
          src: /source
          dest: /destination
      delegate_to: "{{ inventory_hostname }}"
```

delegate_to is not a parameter of the synchronize module; it's an option that can be given to any task: http://docs.ansible.com/ansible/playbooks_delegation.html#delegation  So it belongs at the same indentation level as synchronize itself.

(Sometimes this can be confusing until you get to know all the task options so you can tell the difference between them and the module parameters).
