### ISSUE TITLE
Add support for using blocks as handlers

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#14270]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Core

##### ANSIBLE VERSION
N/A

##### SUMMARY
Currently it's not possible to define multiple tasks for one handler. It is possible to call multiple handlers, or to notify the next handler from the first one, but all of these are more workarounds, than simple solutions. Since Ansbile 2.0 added support for blocks, maybe we could add this support to handlers, so we could write something like this:

```
- name: reload nginx
  block:
    - command: nginx -t
    - service: name=nginx state=reloaded
```

I'm not sure if this would be the correct syntax, but would be really nice to have.

**Comment by bcoca** [comment]
currently you can:

```
- name: reload nginx
  include: nginx_handlers.yml
```

**Comment by kustodian** [comment]
That works with 2.0, but the problem is that by default it searches for the file in the `tasks` directory (and then in the playbook directory), so to have all the handlers in the same directory you need to use something like:

```
- name: reload nginx
  include: ../handlers/nginx_handlers.yml
```

Using a block in this situation would be a lot cleaner.

**Comment by tbenst** [comment]
\+ 1

**Comment by pstch** [comment]
I'd like to add that the workaround suggested by @bcoca also allows you to use blocks in the included file (in Ansible 2.0), meaning that the error handling provided by blocks can be used in handlers, but only through includes.

EDIT: Actually, the functionality described above does not work well at all. The `rescue` and `always` parts of blocks are skipped whenever there is an error in `block`, and the task name is missing from all tasks included in an handler. I'll try to isolate these bugs, look for existing issues and report if I can't them. 

I think that this can perhaps increase the usefulness of this feature request, as currently, if I'm not mistaken, there is no way to do proper error handling in task handlers, and including blocks from handlers seems broken anyway.

**Comment by cosmicscr** [comment]
+1  Allowing handlers to be named blocks instead of just single tasks would be useful

**Comment by nhooey** [comment]
@pstch Could you paste the issue numbers the bugs you're creating or finding in this issue?

**Comment by jamessewell** [comment]
This doesn't seem to work anymore (2.2.0).

I get handler unknown, which stops when I define an actual task instead of an include

TASK [common : command] ********************************************************
ERROR! The requested handler 'reload postgresql' was not found in any of the known handlers

**Comment by sidewinder12s** [comment]
I'd also agree with this, without this it makes it very difficult to deal with failure in handler execution.

**Comment by igormoochnick** [comment]
+1

**Comment by agronchi-nxw** [comment]
+1, would make life easier to the playbook reader

**Comment by ewolinetz** [comment]
+1

**Comment by ghost** [comment]
I'd be nice to have a feature for calling blocks. Think of:

```
block
-> Calls an "acceptance test"
rescue
-> Runs commands to pass the "acceptance test"
always
-> Call the test "acceptance test" again
```

**Comment by mputilin** [comment]
+1

**Comment by meeque** [comment]
+1

**Comment by anosulchik** [comment]
+1

**Comment by slue** [comment]
@bcoca the solution works, but it seems that its `notify` is not compatible to `with_items`, as the handlers in the included file get called each time for every item

**Comment by bitonio** [comment]
To me @bcoca solution doesn't work if you have more than one task notifying the handler.
I managed to reproduce it in something very simple. Using ansible 2.2.1.0

```
- name: Testing notify handler with include
  hosts: blue
  become: True
  tasks:
    - command: id
      notify: restart test
    - command: id
      notify: restart test
    - command: id
      notify: restart test
    - command: id
      notify: restart test
  handlers:
    - name: restart test
      include: tasks/restart_test.yml
```

And the restart_test.yml:

```
- name: Restart test (we use NTP)
  service: name=ntp state=restarted
```

Output
```
ansible-playbook test-restart.yml

PLAY [Testing notify handler with include] *************************************

TASK [setup] *******************************************************************
ok: [host01]

TASK [command] *****************************************************************
changed: [host01]

TASK [command] *****************************************************************
changed: [host01]

TASK [command] *****************************************************************
changed: [host01]

TASK [command] *****************************************************************
changed: [host01]

RUNNING HANDLER [Restart test (we use NTP)] ************************************
changed: [host01]
changed: [host01]
changed: [host01]
changed: [host01]

PLAY RECAP *********************************************************************
host01                     : ok=9    changed=8    unreachable=0    failed=0
```

**Comment by kustodian** [comment]
@bitonio that looks like a bug which I remember having in 2.1.x, not sure if it's fixed in 2.2.x, probably still exists. You should report it as a bug.

**Comment by bitonio** [comment]
@kustodian, gotcha, I reported #21608.

**Comment by ansibot** [comment]
@kustodian Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by christiang830** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by zasca** [comment]
```
$ ansible --version
ansible 2.5.3
...
$ ansible-playbook play.yml

PLAY [test] *****************************************

TASK [Ensure nginx configuration is up to date] *****
changed: [test]
ERROR! The requested handler 'reload nginx' was not found in either the main handlers list nor in the listening handlers list
```
play.yml:
```
- hosts: test
  tasks:
    - name: Ensure nginx configuration is up to date
      template:
        src: nginx.conf.j2
        dst: /etc/nginx/nginx.conf
      notify: [reload nginx]
```
handlers/main.yml:
```
- name: reload nginx
  become: true
  block:
   - command: nginx -t
     changed_when: false
   - service: name=nginx state=reloaded
```
