### ISSUE TITLE
Broken escaping with lookup for JSON template with convert_data=False

### ISSUE THREAD

**Issue by ei-grad** [ansible/ansible#14292]
How to reproduce:

```
- name: install newrelic mysql module
  npi: name=com.newrelic.plugins.mysql.instance config='{{ lookup('template', '../templates/plugin.json.j2', convert_data=False) }}'
  tags:
  - newrelic
```

plugin.json.j2:

```
{
    "agents": [
        {
            "name": "MySQL on {{ inventory_hostname }}",
            "host": "localhost",
            "metrics": "status,newrelic",
            "user": "debian-sys-maint",
            "passwd": "{{ debian_sys_maint_password }}"
        }
    ]
}
```

This generates the following `args` contents:

```
config="'{'"'"'agents'"'"': [{'"'"'metrics'"'"': '"'"'status,newrelic'"'"', '"'"'passwd'"'"': '"'"'XXX'"'"', '"'"'host'"'"': '"'"'localhost'"'"', '"'"'name'"'"': '"'"'MySQL on stage2'"'"', '"'"'user'"'"': '"'"'root'"'"'}]}'" name="com.newrelic.plugins.mysql.instance" 
```

**Comment by dagwieers** [comment]
I cannot confirm this on my system. However I did simplify the example (and may have destroyed evidence in the process).

``` yaml
- hosts: localhost
  tasks:                                                                                                                                                    
  - debug: msg={{ lookup('template', 'templates/plugin.json.j2', convert_data=False) }}
```

This results in:

```
[dag@moria ansible.dag]$ ansible-playbook test52.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "agents": [
            {
                "host": "localhost", 
                "name": "Service on localhost", 
                "vendor": "LENOVO"
            }
        ]
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

Which seems to look fine.

@ei-grad Can you provide me with the most simple version of your issue ? Drop all the ballast and see what is the minimum playbook that is left over that demonstrates the issue.

**Comment by bcoca** [comment]
what data does 'config' on the npi custom module expect? is it a complex structure or a string that gets processed by a JSON parser?

**Comment by ei-grad** [comment]
It expect a string which would be processed by JSON parser.

Actually, I just didn't find how to put a rendered template from local side to remote host in the ansible module written as a shell script. The value of `config=...` would be written into a file, which name should be determined by command execution on the remote side. This module worked with ansible<2.0 :-(.

**Comment by hidekiy** [comment]
@ei-grad 
I've also encountered this problem. Something are modified about `debug: msg={{'{}'}}` style template parsing between ansible 1.9 and 2.1.
And I also found a workaround. Please try:
`{{ lookup('template', '../templates/plugin.json.j2', convert_data=False) |string}}`

**Comment by ei-grad** [comment]
Thank you :-)

**Comment by pierreant-p** [comment]
@hidekiy I tried your workaround it doesn't work for me :(

My policy is

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "SomeId",
            "Action": [
                "s3:GetObject"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::some-bucket/*",
            "Principal": "*"
        }
    ]
}
```

and my task is

```
- name: Create s3 buckets
  s3_bucket:
    name: "{{ item.name }}"
    region: "{{ aws_region }}"
    state: present
    policy: "{{ lookup('file', './bucket-policies/' + item.policy + '.json', convert_data=False) |string}}"
  with_items: "{{ aws_s3_buckets }}"
```

Any idea by any chance?
