### ISSUE TITLE
add_host does not honor 'when'

### ISSUE THREAD

**Issue by codenrhoden** [ansible/ansible#14298]
Issue Type:

Bug Report

Ansible Version:

$ ansible --version
ansible 2.0.0.2
  config file = /Users/travis/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Ansible Configuration:

a custom role path, nothing else

Environment:

OS X 10.11.3.  Managing remote Ubuntu 14.04 servers, but problem is all local.

Summary:

When using the `add_hosts` module, the `when` clause is ignored and the task is always run.

Steps To Reproduce:

Example playbook:

```
- hosts: localhost

  tasks:
    - add_host:
        hostname: testing
        ansible_ssh_host: 127.0.0.1
        when: false
```

Expected Results:

Since `when: false` is set, I would expect the task to be skipped.

Actual Results:

```
$ ansible-playbook -i hosts -v test.yml
Using /Users/travis/ansible/ansible.cfg as config file

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [add_host] ****************************************************************
changed: [localhost] => {"add_host": {"groups": [], "host_name": "testing", "host_vars": {"ansible_ssh_host": "127.0.0.1", "when": false}}, "changed": true}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
the when in this case is not a directive but a variable you are setting for the host.

you need to outdent it for it to be considered a directive.

**Comment by dagwieers** [comment]
Indeed, the correction looks like this:

``` yaml
- hosts: localhost
  tasks:
  - add_host:
      hostname: testing
      ansible_ssh_host: 127.0.0.1
    when: false
```

To understand how YAML is processed, you may want to look at the [YAML Wikipedia](https://en.wikipedia.org/wiki/YAML) entry, or this [YAML Cookbook](http://yaml.org/YAML_for_ruby.html).
