### ISSUE TITLE
Ansible 2.1 overrides default variables by accident

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#14296]
Since I recently updated my Ansible installation repository, Ansible overrides default variables where it should not. If I call a sub role as dependency of a 'parent' role twice, but the last time with overriding a default variable, the variable was also overridden on the first call. Here is a tiny example setup (I omitted the starting `---` in every file):

**sub_role/defaults/main.yml**

```
myvar: "first call"
```

**sub_role/tasks/main.yml**

```
- debug: var=myvar
```

**parent_role/meta/main.yml**

```
dependencies:
  - { role: sub_role }
  - { role: sub_role, myvar: "second call" }
```

Now executing the _parent_role_ leads to following wrong result:

```
TASK [sub_role : debug] ********************************************************
ok: [localhost] => {
    "myval": "second call"
}

TASK [sub_role : debug] ********************************************************
ok: [localhost] => {
    "myval": "second call"
}

```

Can you see the error? On the first call, the output of `myval` should be _first call_ and not _second call_. Because of recent changes Ansible seems to interpret all role variables, starting with the first definition and ignoring omitted definitions.

**Comment by dagwieers** [comment]
I can confirm this behaviour. If you run the `sub_role` twice from a playbook, this behaviour does not occur. But if you run it from another rol (as reported) the exact same thing happens.

``` yaml
- hosts: localhost
  roles:
  - role: sub_role
  - role: sub_role                                                                                                                                          
    myvar: second call
```

Results in:

```
[dag@moria ansible.dag]$ ansible-playbook test50.yml 

PLAY ***************************************************************************

TASK [sub_role : debug] ********************************************************
ok: [localhost] => {
    "myvar": "first call"
}

TASK [sub_role : debug] ********************************************************
ok: [localhost] => {
    "myvar": "second call"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

But if you run the `sub_role` twice from a `parent_role`:

``` yaml
- hosts: localhost
  gather_facts: no                                                                                                                                          
  roles:
  - role: parent_role
```

It fails like this:

```
[dag@moria ansible.dag]$ ansible-playbook test51.yml 

PLAY ***************************************************************************

TASK [sub_role : debug] ********************************************************
ok: [localhost] => {
    "myvar": "second call"
}

TASK [sub_role : debug] ********************************************************
ok: [localhost] => {
    "myvar": "second call"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```
