### ISSUE TITLE
Ansible 2.0.0.2: Booleans in dictionaries cause to_json to fail

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#14291]
Very weird issue that is easy to reproduce.

If a dictionary has a boolean defined, `to_json` returns a `string` rather than a real `dict`.

The following playbook displays the problem:

``` yaml

---
- hosts: localhost
  gather_facts: no
  vars:
    works:
      key1: 'string'
      key2: 1234
    fails:
      key1: 'string'
      key2: 1234
      key3: false
  tasks:
  - debug: msg={{ works | to_json }}
  - debug: msg={{ fails | to_json }}
```

If you run this, you will see that the second dict fails:

```
[dag@moria ansible.dag]$ ansible-playbook test49.yml 

PLAY ***************************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "key1": "string", 
        "key2": 1234
    }
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "{\"key3\": false, \"key2\": 1234, \"key1\": \"string\"}"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

We experience this issue within roles where we assign a dictionary to a role variable.
