### ISSUE TITLE
include_vars not respecting hash_behaviour

### ISSUE THREAD

**Issue by h0nIg** [ansible/ansible#14308]
include_vars is not merging the variables according to hash_behaviour. tested with hash_behaviour = merge

test.yml:

```
  tasks:
   - include_vars: test1.yml
   - include_vars: test2.yml
   - debug: msg="{{ main }}"
```

test1.yml:

```
main:
  varZ: sadasd
  var1:
    lol: fu
    var2: test
```

test2.yml:

```
main:
  varX: lol
  varY: omg
  var1:
    var3: test
```

**result:**

```
var1:
  var3: test
varX: lol
varY: omg
```

**expected result:**

```
varX: lol
varY: omg
varZ: sadasd
var1:
  lol: fu
  var2: test
  var3: test
```
