### ISSUE TITLE
Ansible and Slack MSG Options

### ISSUE THREAD

**Issue by wintechdevops** [ansible/ansible#14303]
I am trying to see what variables I can use to send messages to Slack.
When I job is run I want it to send the results to Slack...if the job completed successfully, failed, changed? Is this possible?

I am currently using the following in my playbook...

```
- name: Send notification message via Slack all options
  local_action:
    module: slack
    token: yyyyyyy/zzzzzzz/token
    msg: "{{ansible_fqdn}} - {{ansible_distribution}}"
    color: good
    parse: full
```

Is there a variable that I can use to get the job result? I tried using "{{ change }}" in the 'msg', but this did not work.

Thanks
