### ISSUE TITLE
ERROR! no action detected in task

### ISSUE THREAD

**Issue by gvenka008c** [ansible/ansible#14316]
I have the below add_repo.ml file

```

---
  - name: Add yum repo
    yumrepo:
      name: test-noarch
      file: test-noarch
      description: Yum No Arch
      gpgcheck: no
      enabled: no
      baseurl: http://yumrepo.sys.xxx.net/ssd/noarch
```

I am getting the below error while running the playbook

```
fatal: [xx.xxx.xxx.xx]: FAILED! => {"failed": true, "reason": "ERROR! no action detected in task\n\nThe error appears to have been in '/ansible/vmsetup/tasks/add_repo.yml': line 2, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n  - name: Add yum repo\n    ^ here\n"}
```

Let me know if any details required. Thanks.

Thanks,
Govind
