### ISSUE TITLE
Problem with tasks on localhost

### ISSUE THREAD

**Issue by jurgenhaas** [ansible/ansible#14331]
Here is a simple playbook:

```
- name: "Test"
  hosts: "localhost"
  gather_facts: false
  become: yes
  tasks:
    - name: "Test"
      lineinfile:
        dest=/etc/hosts
        regexp='{{item}}'
        state=absent
      with_items:
        - '.*abc$'
        - '^1.2.3.4'
```

This fails on localhost with the error message `ERROR! privilege output closed while waiting for password prompt` but only if the list contains 2 items or more. If I remove either of the items from the list, it works just fine.

Also, running the same playbook on a remote host is working just fine and both hosts are configured exactly the same.
