### ISSUE TITLE
RFE: permit passing stdin to commands/shells

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#14380]
I want to be able to provide data to a command via stdin in my ansible playbooks.  For example, I have a playbook that uses `sfdisk` to handle partition manipulation, this:

```
- command: sfdisk -N2
  data: |
    label: dos
    /tmp/archlinux.img1 : start=        2048, size=      204800, type=c
    /tmp/archlinux.img2 : start=      206848, size=     1024000, type=83
```

Seems much more clear than:

```
- shell: >
    sfdisk -N2 < files/partitions
```

The second requires the `shell` module to perform input redirection,
and requires referencing another file just to find a small bit of
input.

We already have a `data` parameter in
`module_utils.basic.run_command`, so really this is just exposing it
via the `command` module.

**Comment by bcoca** [comment]
do we really need more code?

```
vars:
   data:  |
     label: dos
     /tmp/archlinux.img1 : start=        2048, size=      204800, type=c
     /tmp/archlinux.img2 : start=      206848, size=     1024000, type=83
tasks:
  - shell: echo "{{data}}" |sfdisk -N2
```

**Comment by quinot** [comment]
@bcoca this is tricky to get right if data may contain quote characters.

**Comment by drzraf** [comment]
There is an (important) case for this: **passing stdin securely to subsequent command/shell** (what is not possible as of today)

As talked in IRC today, passing stdin as an argument is not an option as soon as private (vault-originated) values are considered (ps faux would list them). Environment variable are sometimes an option, but not always (I'm unsure about their support in Ansible)

Every modules relying on a _freeform_ parameter just ends up doing:
`ssh host /bin/bash -c " < all the free form >"`
So freeform="`command <<< {{secret}}"` , freeform="`echo {{secret}}|command`", & al are **not** a secure way to pass variables.

The only form that I know of would be to pass stdin to the top-level process, ie :
Not: `ssh localhost bash -c "command <<<secret"``
Nor:``ssh localhost "command <<<secret"``(admitting /bin/bash is the default shell)
But rather``ssh localhost command <<<secret``
AFAICT the later is safe and could be run using Python I/O stdin-handling without having to pass stdin as an argument.

Adding a new (eg `stdin`) parameter  to _shell/command/raw_ modules could resolve this, and it would be backward-compatible: the inner-most stdin being always given highest priority:
- `ssh localhost cat <<< ext-stdin`
  vs
- `ssh localhost "/bin/bash -c 'cat<<<int-stdin'" <<< ext-stdin`

**Comment by dspruell** [comment]
To echo what @drzraf noted, there are cases where stdin should be passed to the invoked command to avoid leaking sensitive info e.g. in the process table or a shell history file, another example being MySQL client tools' `-p` option which can prompt for the password from stdin instead of reading it as an argument on the command line. 

Could enable something like this?

```
- name: query tables from database
  command: mysqlshow -h {{ db_host }} -u {{ db_user }} -p {{ db_name }}
  args:
    stdin: "{{ db_password }}"
  register: db
```
