### ISSUE TITLE
Support template variables in register and tags

### ISSUE THREAD

**Issue by xmj** [ansible/ansible#14384]
There's currently no way to use variables in `register` and `tags`.

Adding templating to those two would be helpful for cases where role tasks can be run on dictionaries, so that something like this works:

```
some_dict:
  foo:
    filename: 'first.txt'
    content: '1st'
  bar:
    filename: 'second.txt'
    content: '2nd'
```

```
- name: echo things
  shell: echo "{{ item.value.content }}" > " item.value.filename"
  register: "{{ item.key }}_present"
  tags:
  - baz
  - "{{ item.key }}"
  with_dict: "{{ some_dict }}"

- name: debug variable '{{ item.key }}_present'
  debug: var="{{ item.key}}_present"
  tags:
  - baz
  with_dict: "{{ some_dict }}"
```

and then running `ansible-playbook -t baz` or, alternatively, `ansible-playbook -t foo,bar`

**Comment by jimi-c** [comment]
I could see maybe doing this for tags, but I really don't like the idea of using it for register.

**Comment by sivel** [comment]
-1 on using it for register also.  Variable variables can be super confusing.

In addition to that, it is often a misunderstanding of how results are registered in a loop.

**Comment by xmj** [comment]
I see. The idea behind registering return values with dict variables is the following:
- I have 5 actions that need to be run on values of a dict (again, containing five entries)
- Some of those actions require the registered output of a previous action to be able to perform correctly, e.g. for directory paths and the likes.

Is there a way to do this that doesn't involve registering the variables under "{{ item.key }}_something" ?

**Comment by sivel** [comment]
@xmj when using `register` with a loop such as `with_items`, the results of each iteration are stored in a sub key of the registered var called `results` (See http://docs.ansible.com/ansible/playbooks_loops.html#using-register-with-a-loop)

Here is an example of how to use register, with a loop, without needing to create individual register variables.  This example is a bit contrived, as there are better ways to achieve this with ansible, but it showcases how to use the `results` key, in a subsequent task:

```
---
- name: loopy
  hosts: all
  gather_facts: False
  vars:
    some_files:
      - /tmp/one
      - /tmp/two
  tasks:
    - name: stat some files
      stat:
        path: "{{ item }}"
      with_items: "{{ some_files }}"
      register: some_files_stat

    - name: create files
      file:
        state: touch
        path: "{{ item.0 }}"
      when: item.1.stat.exists == False
      with_together:
        - "{{ some_files }}"
        - "{{ some_files_stat.results }}"
```

The important take away in the above example, is using `with_together` to loop over parallel sets of data, the first array is the original list of files, and the second is the results of the prior task.
