### ISSUE TITLE
get_url fails when moving a file and become: true

### ISSUE THREAD

**Issue by gwagner** [ansible/ansible#14396]
Worked in 1.9.4 broken in 2.0.2

```
- name: Download vagrant default authorized_key file
  get_url: url=https://raw.github.com/mitchellh/vagrant/master/keys/vagrant.pub dest="{{ item }}"
  when: env == "vagrant"
  with_items:
    - /home/vagrant/.ssh/authorized_keys
    - /home/deploy/.ssh/authorized_keys
  tags:
    - keys
```

The block above throws this error:

```
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "ERROR! timeout waiting for privilege escalation password prompt:\n[sudo via ansible, key={REDACTED}] password: "}
```

Other tasks before the code block above run properly and can sudo to root.  Example:

```
- name: Create vagrant .ssh directory
  file: path=/home/vagrant/.ssh state=directory mode=0700 owner=vagrant group=vagrant
  when: env == "vagrant"
  tags:
    - keys
```
