### ISSUE TITLE
Redefining variables from 'meta' (different behavior in 1.9, 2.0-rc and 2.0.0.2)

### ISSUE THREAD

**Issue by mearsten** [ansible/ansible#14411]
Hello,

I've got a bunch of playbooks written initially for ansible 1.9 by my precedessor. Recently I tried to adapt it to ansible 2.0 and discovered the difference in variable hadling when you override defaults in 'meta/main.yml'. I'd like know whether it's a bug or feature :)

I've tried 3 versions of Ansible:

ansible 1.9.4

ansible 2.0.0 (detached HEAD cc98528ecb) last updated 2015/12/19 18:44:56 (GMT +300)
  lib/ansible/modules/core: (detached HEAD fcb3397df7) last updated 2015/12/19 18:44:51 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD c6829752d8) last updated 2015/12/19 18:44:56 (GMT +300)

ansible 2.0.0.2 (detached HEAD 7de237c5a1) last updated 2016/01/21 23:40:54 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 09e2457eb0) last updated 2016/01/21 23:40:48 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD e8427cb32a) last updated 2016/01/21 23:40:54 (GMT +300)

First, I going to show a test code (also here: https://github.com/serge-name/test-override-var):

playbook.yml:

``` yaml
- name: test
  hosts: localhost
  gather_facts: False

  roles:
    - test-override-var1
```

test-override-var1/meta/main.yml:

``` yaml
dependencies:
  - test-override-var3
  - test-override-var2
```

test-override-var1/tasks/main.yml:

``` yaml
- debug: msg=">>{{ the_var }}<<"
```

test-override-var1/meta/main.yml:

``` yaml
dependencies:
  - role: test-override-var3
    the_var: '2'
```

test-override-var3/defaults/main.yml:

``` yaml
the_var: '3'
```

test-override-var3/tasks/main.yml:

``` yaml
- debug: msg=">>{{ the_var }}<<"
```

On ansible-1.9 I get the following sequence (the desired behavior):

``` yaml
TASK: [test-override-var3 | debug msg=">>{{ the_var }}<<"] ******************** 
ok: [localhost] => {
    "msg": ">>3<<"
}

TASK: [test-override-var3 | debug msg=">>2<<"] ******************************** 
ok: [localhost] => {
    "msg": ">>2<<"
}

TASK: [test-override-var1 | debug msg=">>{{ the_var }}<<"] ******************** 
ok: [localhost] => {
    "msg": ">>3<<"
}
```

On ansible-2.0-rc I get the following (and it gives me problems):

``` yaml
TASK [test-override-var3 : debug msg=>>{{ the_var }}<<] ************************
ok: [localhost] => {
    "changed": false, 
    "msg": ">>3<<"
}

TASK [test-override-var3 : debug msg=>>{{ the_var }}<<] ************************
ok: [localhost] => {
    "changed": false, 
    "msg": ">>2<<"
}

TASK [test-override-var1 : debug msg=>>{{ the_var }}<<] ************************
ok: [localhost] => {
    "changed": false, 
    "msg": ">>2<<"
}
```

On ansible-2.0.0.2 I get the following (problems again):

``` yaml
TASK [test-override-var3 : debug] **********************************************
ok: [localhost] => {
    "msg": ">>2<<"
}

TASK [test-override-var3 : debug] **********************************************
ok: [localhost] => {
    "msg": ">>2<<"
}

TASK [test-override-var1 : debug] **********************************************
ok: [localhost] => {
    "msg": ">>2<<"
}
```
