### ISSUE TITLE
v 2.1.0-dev pip module: using both executable and virtualenv params installs to system instead of in virtual environment

### ISSUE THREAD

**Issue by stefano-m** [ansible/ansible#14415]
##### Issue Type:
- Bug Report
##### Ansible Version:

EDIT: I have just installed the latest dev version and still see the issue:

`sudo pip install -U git+https://github.com/ansible/ansible.git@devel#egg=ansible`

```
$ ansible --version
ansible 2.1.0
  config file = /home/vagrant/ansible.cfg
  configured module search path = Default w/o overrides
```

I actually encountered this behavior in ansible 1.9.4 and 2.0.0.2 too.
##### Ansible Configuration:

```
$ cat /home/vagrant/ansible.cfg
[defaults]
hostfile = /home/vagrant/ansible/inventory/development
forks=15
host_key_checking = False
```
##### Environment:

Tested on a `bento/ubuntu-14.04` vagrant box.

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"
```
##### Summary:

In the `pip` module, when _both_ the `executable` and `virtualenv` parameters are used, the named package is installed in the system instead of in the virtual environment.
##### Steps To Reproduce:

Running the following playbook will install `bottle` in the system rather than in the virtual environment.

`executable` points to `/usr/bin/pip` because I have installed the latest version of `pip` (namely 8.0.2) using `get-pip.py`.

``` yaml

---
- name: Pip module bug
  hosts: localhost
  become: yes
  vars:
    ansible_connection: local
  tasks:
    - become_user: root
      pip: name=bottle
             state=latest
             executable=/usr/local/bin/pip
             virtualenv=/home/vagrant/myenv
```

This will create a virtual environment in `/home/vagrant/myenv` _and_ install `bottle` in the system.

If the `executable` parameter is removed, then the named package is installed in the virtual environment.
##### Expected Results:

I would have expected either that the package were installed inside the virtual environment or that ansible returned an error saying that `executable` and `virtualenv` are not compatible (similarly to `name` vs `requirements`).
##### Actual Results:

This will create a virtual environment in `/home/vagrant/myenv` _and_ install `bottle` in the system.
