### ISSUE TITLE
dnf module: "NameError: global name 'util' is not defined"

### ISSUE THREAD

**Issue by plombardi89** [ansible/ansible#14427]
Ansible vomitting while trying to run a dnf task on Fedora 23:

``` text
ansible 2.0.0.2
  config file = /home/plombardi/workspace/dw/REDACTED/ansible.cfg
  configured module search path = Default w/o overrides
```

``` yaml
- hosts: REDACTED_servers
  become: yes
  pre_tasks:
    - name: install essential software
      dnf:
        name: "{{ item }}"
        state: latest
      with_items:
        - java-1.8.0-openjdk
```

Throws this error:

```
TASK [install essential software] *********************************************
failed: [54.213.90.47] => (item=[u'python-dnf', u'java-1.8.0-openjdk']) => {"failed": true, "item": ["python-dnf", "java-1.8.0-openjdk"], "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/fedora/.ansible/tmp/ansible-tmp-1455147718.94-110285313538093/dnf\", line 2284, in <module>\r\n    main()\r\n  File \"/home/fedora/.ansible/tmp/ansible-tmp-1455147718.94-110285313538093/dnf\", line 339, in main\r\n    if not util.am_i_root():\r\nNameError: global name 'util' is not defined\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
