### ISSUE TITLE
"changed_when: True" does not display the task as changed

### ISSUE THREAD

**Issue by J-Griffin** [ansible/ansible#14430]
Ansible version 2.0.0.2
Expected "Test changed_when" to be "changed" and yellow. Was "ok" and green instead.

**changed_when_test.yml:**

``` yaml

---
- name: Test Play
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Test changed_when
      debug: msg="This should be changed"
      changed_when: True
```

**Result:**

```
PLAY [Test Play] *********************************************

TASK [Test changed_when] *******************************************************
ok: [localhost] => {
    "msg": "This should be changed"
}

PLAY RECAP *********************************************************************
localhost        : ok=1    changed=1    unreachable=0    failed=0
```
