### ISSUE TITLE
bug: Skipping task due to undefined attribute with with_item even with default attribute

### ISSUE THREAD

**Issue by deimosfr** [ansible/ansible#14448]
Hi,

I'm trying to resolve an issue on Ansible v2.0.0.2-1. I migrated from v1.9.3 to v2.0.0.2-1 and had issues on testing my roles with Ansible 2. I'm running Debian Jessie. One of the issue is when I'm using a when statement with an undefined value. All vars in a with_items are evaluated. Here is an example:

``` yaml
- template:
    src: fact_list_template.j2
    dest: /etc/ansible/facts.d/all_roles.fact
    owner: root
    group: root
    mode: 0755
  with_items:
    - { name: 'test', value: "{{dict[var]['list']|default([])}}" }
  when: "{{var}} is defined"
```

I've a dict and if var is defined, I know that I can evaluate it in my dict. However, in any case, dict[var]['list'] is evaluated which send a warning message.

I should get a skipping value when var is not defined instead of this message:

```
[DEPRECATION WARNING]: Skipping task due to undefined attribute, in the future this will be a fatal error.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

Even with the default function it doesn't work. Hope my explanations are clear.
