### ISSUE TITLE
with_first_found fails  with ansible 2

### ISSUE THREAD

**Issue by juge2** [ansible/ansible#14454]
Ansible version: 2.0.0.2

After upgrading from ansible 1.9 to 2.0 with_first_found in combination with delegate_to seems to change the base search path from ./role-name/(files / templates) to the path where the playbook is executed from:

```
- name: this works (file is found on ansible server)
  template: src={{ item }}
            dest=/tmp/
  with_first_found:
       - "foo"

- name: this also works (delegating to another host and use playbook-directory as base)
  template: src={{ item }}
            dest=/tmp/
  with_first_found:
       - "roles/testing/templates/foo"
  delegate_to: localhost

- name: but this does not work 
  template: src={{ item }}
            dest=/tmp/
  with_first_found:
       - "foo"
  delegate_to: localhost
```

**Result:**

```
TASK [testing : this works (file is found on ansible server)] ******************
ok: [test-1] => (item=/opt/ansible/roles/testing/templates/foo) => {"changed": false, "gid": 0, "group": "root", "item": "/opt/ansible/roles/testing/templates/foo", "mode": "0644", "owner": "root", "path": "/tmp/foo", "size": 5, "state": "file", "uid": 0}

TASK [testing : this also works (delegating to another host and use playbook-directory as base)] ***
ok: [test-1 -> localhost] => (item=/opt/ansible/roles/testing/templates/foo) => {"changed": false, "gid": 0, "group": "root", "item": "/opt/ansible/roles/testing/templates/foo", "mode": "0644", "owner": "root", "path": "/tmp/foo", "size": 5, "state": "file", "uid": 0}
ERROR! No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found
```

(Note that the error is message appears even before the actual task was started
