### ISSUE TITLE
Add 'follow' option to 'template'

### ISSUE THREAD

**Issue by haasn** [ansible/ansible#14469]
##### Issue Type:

Bug report in Core Module
##### Ansible Version:

ansible --version:

```
ansible 2.1.0 (devel 4b953c4b16) last updated 2016/02/14 15:32:35 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) last updated 2016/02/14 15:32:42 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f) last updated 2016/02/14 15:32:48 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Summary of changes:
- forks increased to 50
- vault_password_file defined
- gathering set to smart
- timeout set to 30
- plugins/actions added to action_plugins
- fact_caching set to jsonfile
- `-o BatchMode=yes -o UserKnownHostsFile=/dev/null` added to ssh_args
- pipelining set to true
##### Environment:

Running Ansible from CentoS 7, managing Ubuntu 14.04 LTS.
##### Summary:

https://docs.ansible.com/ansible/template_module.html suggests the existence of a `follow` option to disable following symlinks when creating files from templates.

Yet, this does not seem to be working as intended.
##### Steps To Reproduce:

e.g.

``` yaml
- name: set up resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    follow: no
```

Then run this on an environment where /etc/resolv.conf is a symlink (e.g. to /run/resolvconf/resolv.conf).
##### Expected Results:

/etc/resolv.conf is replaced by a file containing the evaluated template contents.
##### Actual Results:

e.g.

```
fatal: [example-host]: FAILED! => {"changed": true, "failed": true, "msg": "Destination /run/resolvconf not writable"}
```
##### Further Info:

I can work around this issue like so:

``` yaml
- name: check if resolv.conf is a symlink
  stat: path=/etc/resolv.conf
  register: resolvconf

- name: delete resolv.conf if it's a symlink
  file:
    path: /etc/resolv.conf
    state: absent
  when: resolvconf.stat.islnk

- name: set up resolv.conf
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
```

But this is actually rather bothersome because without a proper resolv.conf set up, it's possible for every task to take a long time to execute on the remote end.
