### ISSUE TITLE
Commit 275728e appears to have broken include

### ISSUE THREAD

**Issue by bradwilson** [ansible/ansible#14460]
**Issue Type:**

Bug Report

**Ansible Version:**

Running from source, commit 275728e (from @jimi-c)

**Ansible Configuration:**

There is no `/etc/ansible/ansible.cfg` file.

**Environment:**

Ubuntu 14.04 (presumably independent of environment)

**Summary:**

We regularly move forward with the source to take advantage of newly committed features, and it appears that `include:` statements have been broken by the referenced commit.

**Steps To Reproduce:**

I have four files in my simple repro.

File: `inventory.ini`

``` ini
[sample_hosts]
SAMPLEHOST1
```

File: `playbook.yml`

``` yml

---
- hosts: sample_hosts
  gather_facts: false
  roles:
  - role: sample_role
```

File: `roles/sample_role/main.yml`

``` yml

---
- include: included_file.yml
```

File: `roles/sample_role/included_file.yml`

``` yml

---
- name: Debug Message
  local_action:
    module: debug
    msg: "Hello! Inventory host is {{ inventory_hostname }}"
```

The repro is run with: `ansible-playbook -i inventory.ini playbook.yml`

**Expected Results:**

```
PLAY ***************************************************************************

TASK [sample_role : include] ***************************************************
included: /vagrant/1/roles/sample_role/tasks/included_file.yml for SAMPLEHOST1

TASK [sample_role : Debug Message] *********************************************
ok: [SAMPLEHOST1 -> localhost] => {
    "msg": "Hello! Inventory host is SAMPLEHOST1"
}

PLAY RECAP *********************************************************************
SAMPLEHOST1                : ok=2    changed=0    unreachable=0    failed=0
```

**Actual Results:**

```
PLAY ***************************************************************************

TASK [sample_role : include] ***************************************************
included: /vagrant/1/roles/sample_role/tasks/included_file.yml for SAMPLEHOST1

PLAY RECAP *********************************************************************
SAMPLEHOST1                : ok=1    changed=0    unreachable=0    failed=0
```
