### ISSUE TITLE
"register" doesn't seem to work well with "failed_when" and "with_fileglob" (2.0.0.2)

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible#14478]
It seems that in 2.0.0.2, register is not behaving as it should, ie, is not having the value of the current iteration to allow for proper testing.
Anyone having the same problem?

```
tasks:
  block:
    - name: expand template
          template:
            src:  "{{ item }}"
            dest: "{{ dir2 }}/_tmp/{{ item |basename |regex_replace('^(.*)\\.j2$', '\\1') }}"
          with_fileglob: "{{ dir1 }}/*.j2"
          register: cvt1_result
          failed_when: (cvt1_result.rc != 0) or ((cvt1_result.stderr |length) > 0)
```

results in

```
fatal: [host1]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check '(cvt1_result.rc != 0) or ((cvt1_result.stderr |length) > 0)' failed. The error was: ERROR! error while evaluating conditional ((cvt1_result.rc != 0) or ((cvt1_result.stderr |length) > 0)): ERROR! 'dict object' has no attribute 'rc'"}
```
