### ISSUE TITLE
Ansible 2.0.0.2 skipped tasks with with_nested does not handle undefined variables

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#14498]
Issue Type : Bug Report
Ansible Version: 2.0.0.2
Environment: Ubuntu 14.04 LTS Python 2.7.10
Summary:

I have a bunch of tasks that are skipped on some condition. One of them set_fact a variable. Even if the task using with_nested is skipped, the with_nested argument tries to "access" the variable and fail.

I tried to create a block and put all tasks with the same when condition into the block but the issue is the same.

On ansible 1.9.4 it works flawless.

Steps To Reproduce:

```
- set_fact: something=[1, 2]
  when: no

- name: Fail because of this issue
  command: echo {{ item[0] }} {{ item[1] }}
  when: no
  with_nested:
    - "{{ something }}"
    - [3, 4]
```

Excepted : all tasks are skipped
Actual:

`fatal: [my-pc]: FAILED! => {"failed": true, "msg": "ERROR! 'something' is undefined"}`

Regards,

David
