### ISSUE TITLE
name of backup_file missing in ini_file

### ISSUE THREAD

**Issue by Senilein** [ansible/ansible#14502]
##### Issue Type:

Bug Report
##### Ansible Version:

1.9.4
##### Summary:

When updating an ini file with appropriate module no information about backup file is returned. Backups are created on remote machine.
##### Steps To Reproduce:

We use following task  for configuring mysql daemon

``` yaml
- name: configure mysql-daemon
  ini_file: dest=/etc/my.cnf section=mysqld option={{ item.key }} value={{ item.value }} backup=yes
  with_dict: "{{ mysqld }}"
  register: new_conf

- name: backup old configuration
  fetch: src={{ new_conf.backup_file }} dest=/etc/ansible/backup
  when: new_conf.backup_file is defined
```
##### Expected Results:

``` json
changed: [172.16.254.14] => (item={'key': 'innodb-file-per-table', 'value': 1}) => {"backup_file": "/etc/my.cnf.2016-02-16@13:01:27~", "changed": true, "dest": "/etc/my.cnf", "gid": 0, "group": "root", "item": {"key": "innodb-file-per-table", "value": 1}, "mode": "0644", "msg": "OK", "owner": "root", "size": 1008, "state": "file", "uid": 0}
```
##### Actual Results:

``` json
changed: [172.16.254.14] => (item={'key': 'innodb-file-per-table', 'value': 1}) => {"changed": true, "dest": "/etc/my.cnf", "gid": 0, "group": "root", "item": {"key": "innodb-file-per-table", "value": 1}, "mode": "0644", "msg": "OK", "owner": "root", "size": 1008, "state": "file", "uid": 0}
```

At the current moment we are not able to create backups on ansible server with given tasks.
