### ISSUE TITLE
with_items doesn't work with variables

### ISSUE THREAD

**Issue by sparanoid** [ansible/ansible#14507]
tasks/main.yml:

``` yml
- name: create site public directories
  file: path=/srv/www/{{ item }}/public_html/ state=directory
  with_items: nginx_sites.{{ inventory_hostname }}
```

vars/main.yml:

``` yml
nginx_sites:
  host_one:
    - site1.tld
    - site2.tld
  host_two:
    - site3.tld
    - site4.tld
```

Run the task and I got:

```
TASK [basic-setup : create site public directories] ****************************
changed: [host_one] => (item=nginx_sites.host_one)
```

Expected:

```
TASK [basic-setup : create site public directories] ****************************
changed: [host_one] => (item=site1.tld)
changed: [host_one] => (item=site2.tld)
```
