### ISSUE TITLE
Ansible 2.0.0.2 doesn't wait for host verification prompt

### ISSUE THREAD

**Issue by gtaylor** [ansible/ansible#14511]
We just upgraded from Ansible 1.9.x to Ansible 2.0.0.2. After the upgrade, the host authenticity SSH prompts fly by without stopping for us to answer, eventually causing failures due to prompt timeouts. Here's the output:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
The authenticity of host 'xxx.xxx.xx.xxx (xxx.xxx.xx.xxx)' can't be established.
ECDSA key fingerprint is SHA256:6fyHxEjW4R7GK73M4h9yILlhNM+JJ+m1IYLGGBwWEFk.
Are you sure you want to continue connecting (yes/no)? ok: [yyy.yyy.yy.yy]
ok: [zzz.zzz.zz.zzz]
ok: [aaa.aaa.aa.aa]
```

I figured others were probably running into this issue, but couldn't find an existing one on here in the pile. If such an issue already exists, feel free to close this one and direct me to where the action is.

**Comment by cero-t** [comment]
+1

**Comment by milad-soufastai** [comment]
+1

**Comment by lalanza808** [comment]
As a temporary solution, set forks to 1....I just hope your inventory file is small

**Comment by davidak** [comment]
@lalanza808 works for beeing able to accept the fingerprints.

but we have about 200 servers and 7 admins. would be nice to not have to type 1400 times "yes" and hit ENTER.

i tried this but it has no effect on the prompt.

```
yes yes | ansible "test" -f 1 -m ping
```

any idea?

**Comment by davidak** [comment]
I created this playbook to solve it:

```
- hosts: all
  gather_facts: False
  tasks:
    - name: remove old ssh key fingerprint
      shell: ssh-keygen -R {{ ansible_host }}
      delegate_to: localhost
    - name: add ssh key fingerprint
      shell: ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts
      delegate_to: localhost
```
