### ISSUE TITLE
skipping: no hosts matched while creating VPC in AWS

### ISSUE THREAD

**Issue by samohri** [ansible/ansible#14517]
##### Issue Type:

Bug Report

We are running ansible 1.9.1. Was creating new script for creating VPC in AWS and stuck with below results:

ansible-playbook -vvv -i /etc/ansible/ec2.py /etc/ansible/aws/virtqa/vpc/site.yml

PLAY [local] ******************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************

My Script is as below:
cat /etc/ansible/aws/virtqa/vpc/site.yml

```

---
- hosts: local
  connection: local
  gather_facts: false
  vars_files:
    - group_vars/tags.yml
    - group_vars/vpc.yml
    - group_vars/ec2_key.yml
    - group_vars/webserver.yml
    - group_vars/elb.yml
  tasks:
    - name: VPC | Creating an AWS VPC inside mentioned Region
      ec2_vpc:
        region: "{{ vpc_region }}"
        state: present
        cidr_block: "{{ vpc_cidr_block }}"
        resource_tags: { "Name":"{{ vpc_name }}-vpc" }
        subnets: "{{ vpc_subnets }}"
        internet_gateway: yes
        route_tables: "{{ public_subnet_rt }}"
      register: vpc

    - name: VPC | Write vpc id to file inside the vars directory
      shell: echo "{{ vpc.vpc_id }}" > "{{ vpc_name }}-vpc-info.yml"
      args:
        chdir: group_vars/

    - name: VPC | Write public and private subnets id to files inside the vars directory
      shell: echo "{{ item.id }}" > "{{ item.resource_tags.Name }}.yml"
      args:
        chdir: group_vars/
      with_items: vpc.subnets

    - name: VPC | Set the public and private subnet id as facts
      set_fact:
        vpc_id: "{{ lookup('file', 'aws/vars/' + vpc_name + '-vpc-info.yml') }}"
        public_subnet_1: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + public_az_1 + '-public-subnet.yml') }}"
        public_subnet_2: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + public_az_2 + '-public-subnet.yml') }}"
        private_subnet_1: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + private_az + '-private-subnet.yml') }}"
        private_subnet_2: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + private_az + '-private-subnet.yml') }}"
        private_subnet_3: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + private_az + '-private-subnet.yml') }}"
        private_subnet_4: "{{ lookup('file', 'aws/vars/' + vpc_name + '-' + private_az + '-private-subnet.yml') }}"
```

I Also got a script for creating EC2 instances on the fly, that seems to work fine but not sure what is wrong with the above script. Appreciate you help.

Cheers
