### ISSUE TITLE
git module fails to clone via ssh from non-standard port

### ISSUE THREAD

**Issue by sk1p** [ansible/ansible#14574]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

Trying to clone a git repository on a non-standard SSH port fails, even though the SSH host key was added to the ssh_known_hosts file.
##### Steps To Reproduce:

1) remove host key of ssh.github.com port 22 from known_hosts, if any exists: `ssh-keygen -R ssh.github.com`
2) add the host key for port 443: ssh -p443 git@ssh.github.com
3) Run the playbook below

```

---

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: try to clone something 1
      git: repo=git+ssh://git@ssh.github.com:443/jimi-c/test_role.git dest=/tmp/test_role_1
      ignore_errors: yes

    - name: try to clone something 2
      git: repo=git@[ssh.github.com:443]:jimi-c/test_role.git dest=/tmp/test_role_2
      ignore_errors: yes
```
##### Expected Results:

`/tmp/test_role_[12]` should exist and contain the cloned repository.
##### Actual Results:

```
 _________________________________
< TASK [try to clone something 1] >
 ---------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "ssh.github.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module"}
...ignoring
 _________________________________
< TASK [try to clone something 2] >
 ---------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "[ssh.github.com:443] has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module"}
...ignoring
```
##### Proposed fix

The `add_git_host_key` function in `ansible.module_utils.known_hosts` should include the port in the `check_hostkey` call. For the above example, `check_hostkey("[ssh.github.com]:443")` should be called instead of `check_hostkey("ssh.github.com")` or `check_hostkey("[ssh.github.com:443]")`
