### ISSUE TITLE
Ansible 2.0 python-api: How to load playbooks or Tasks from file?

### ISSUE THREAD

**Issue by edgecase1** [ansible/ansible#14579]
##### Issue Type:

Please pick one and delete the rest:
- Documentation Report
##### Ansible Version:

```
ansible 2.0.0.2
```
##### Ansible Configuration:

default / not applicable -> python API
##### Environment:

docker python-2.7
##### Summary:

I created a setup using http://docs.ansible.com/ansible/developing_api.html for ansible 2.0 python-api.
I would like to load Tasks or Playbooks from file.
##### Steps To Reproduce:

Currently I have this: https://gist.github.com/catmin/cd51dda473ebeb3e99e8
##### Expected Results:

Load Tasks like from file like this:

```
  tasks:
  - copy: src=files/foo dest=/tmp/foo owner=root group=root mode=0644
  - sysctl: name=net.ipv4.ip_forward value=1 state=present
  - apt: name=wget state=absent
```

and run them via Play() and TaskQueueManager() - as stated in the example

```
f = open('task_file','r')
play_source =  dict(
        name = "Ansible Play",
        hosts = '192.168.56.212',
        gather_facts = 'no',
        tasks = read_tasks_from_file(f.read())
    )
```
##### Actual Results:

Currently I can use the following:

```
play_source =  dict(
        name = "Ansible Play THIS COULD BE YOUR AD!",
        hosts = '192.168.56.212',
        gather_facts = 'no',
        tasks = [ dict(
            action=dict(module='sysctl', args=dict(name='net.ipv4.ip_forward', value=1, state='present'))
        )]
    )
```
