### ISSUE TITLE
regression: duplicate role dependencies

### ISSUE THREAD

**Issue by diefans** [ansible/ansible#14582]
##### Ansible Version:

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

n/a
##### Environment:

python==2.7.10
osx==10.10.5
##### Summary:

Role dependencies are run more than once.
##### Steps To Reproduce:

here are my files:

```
# inventory
localhost
```

```
# play.yml

---
- name: dependency test with role tags
  hosts: localhost
  connection: local

  roles:
    - role: base
      tags:
        - always

    - role: feature
      tags:
        - always
```

```
# roles/base/meta/main.yml

---
allow_duplicates: no
```

```
# roles/base/tasks/main.yml

---
- name: base role
  debug:
    msg: base role
```

```
# roles/feature/meta/main.yml

---
allow_duplicates: no
dependencies:
  - role: base
    tags:
      - always
```

```
# roles/feature/tasks/main.yml

---
- name: feature role
  debug:
    msg: feature role
```

I call it with:

```
ansible-playbook -i inventory play.yml --list-tasks
```
##### Expected Results:

The base role is executed once.

Using ansible==1.9.4 the play works as expected:

```
playbook: play.yml

  play #1 (dependency test with role tags): TAGS: []
    base role   TAGS: [always]
    feature role    TAGS: [always]
```
##### Actual Results:

The base role is executed twice.

```
playbook: play.yml

  play #1 (localhost): dependency test with role tags   TAGS: []
    tasks:
      base : base role  TAGS: [always]
      base : base role  TAGS: [always]
      feature : feature role    TAGS: [always]
```
