### ISSUE TITLE
Registered EC2 variable not behaving as described in the documentation

### ISSUE THREAD

**Issue by colin-byrne-1** [ansible/ansible#14593]
##### Issue Type:

Please pick one and delete the rest: (sorry for leaving two, I am not sure which this is, possibly both)
- Bug Report
- Documentation Report
##### Ansible Version:

```
ansible 2.1.0 (devel 6a62ad6c4b) last updated 2016/02/01 13:04:11 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 93d02189f6) last updated 2016/02/01 13:04:24 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD fff5ae6994) last updated 2016/02/01 13:04:31 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

no significant changes, 
scp_if_ssh=True
##### Environment:

N/A
##### Summary:

After running the ec2 module and registering the ec2 variable, then looping over the ec2.results I am only able to access `item.instances` when creating a new instance. If it the instance is already created, `ec2.results.instances` returns as an empty set, and therefore the task breaks on that iteration. I instead have had to access the instance id by `{{ item.tagged_instances.0.id }}` which consistently holds the instance id wether the instances is being created or wether it already exists, but this isn't entirely reliable either as (I believe) it is only populated if the instance is tagged. 

Additionally, the nesting of these variables is different than what is described in the documentation on [http://docs.ansible.com/ansible/ec2_vol_module.html](url), which states that you should be able to access the instances simply by `ec2.instances`. Did this change with 2.0?
##### Steps To Reproduce:

Here is my list I am iterating over:

```
server_environments:
  - environment: production
    servers: 
      - { type: bastion, name: j-bastion, private_ip: 10.1.1.250 }
      - { type: app, name: j-delete, private_ip: 10.1.1.106 }
```

Here is my playbook:

```

---
- hosts: localhost
  gather_facts: False
  roles:
    - provision_ec2
```

Here is my provision_ec2 role:

```

---
- name: Launch instances based on server list
  ec2:
    key_name: ansible_provisioning.txt
    group_id: 'sg-81398ee4', 'sg-a6398ec3'
    instance_type: t2.medium
    image: ami-06116566
    termination_protection: yes
    wait: true
    region: us-west-2
    instance_tags:
      Type: "{{ item.0.environment }}"
      Name: "{{ item.1.name }}"
    exact_count: 1  
    count_tag:
      Name: "{{ item.1.name }}"
    vpc_subnet_id: subnet-819f7gd2
    assign_public_ip: yes
    private_ip: "{{ item.1.private_ip }}"
  register: ec2
  with_subelements:
     - server_environments
     - servers

# Use this to see what is contained in the ec2 variable
- name: debug...
  debug: var=ec2.results
```

**This DID NOT work (shown as acceptable int the documentation)**

```
- name: Attach volumes to created instances
  ec2_vol:
    instance: "{{ item.id }}"
    device_name: /dev/xvdb
    volume_size: 200
    volume_type: gp2
    iops: 600
  with_items: ec2.instances
  register: ec2_vol
```

**This DID work but is not reliable**

```
- name: Attach volumes to created instances
  ec2_vol:
    instance: "{{ item.tagged_instances.0.id }}"
    device_name: /dev/xvdb
    volume_size: 200
    volume_type: gp2
    iops: 600
  with_items: ec2.results
  register: ec2_vol
```

[Here is a gist with my debug output which shows the abnormal nesting and the instance.id only being populated for the newly created instance ](https://gist.github.com/cobyrne09/ed7f1bee25518129500c)
##### Expected/Actual Results:

I expected there to be an `ec2.instances`property, not an `ec2.results` property and I expected the `ec2.results.instances` property to contain ids for all instances in my server list, not just the newly created ones.

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by colin-byrne-1** [comment]
Hey, [I have asked this in the mailing list](https://groups.google.com/forum/#!topic/Ansible-project/a2AKipJC0NI) and with the help of others, have determined it is nothing on my side. It definitely seems to be a bug report or a documentation report.

**Comment by dsummersl** [comment]
I'm having this problem too.

**Comment by colin-byrne-1** [comment]
@dsummersl glad to hear I'm not alone. I have no idea why this was so quickly disregarded. It is clearly not a user question... @bcoca

**Comment by woohgit** [comment]
Same here.

I'd love to have a consistent result set and not depending on the instances were created or not. instances vs. tagged_instances.

Please reopen and provide a good solution.

**Comment by sw360cab** [comment]
+1

**Comment by vkruoso** [comment]
This is somewhat critical feature. Can this issue be reopened?

**Comment by sw360cab** [comment]
like @vkruoso and me and all others asked. Is there any step forward on this issue?
Someone is caring? Any update (maybe changes at ec2.py)?
Can it be reporduced? Are we wrong on the topic?

I just updated Ansible (Mac OS 10.11) and still get this same old issue when creating EC2 instances.

Can someone at least answer, or the Ansible project is not going forward on the AWS side, so we better move to other project / services rather than Ansible?

**Comment by s-hertel** [comment]
I'm opening this back up in lieu of #25992 as requested, since all the conversation has been going on here. On the latest devel I am able to use the registered ec2 instances as expected.
```
    - name: Attach volumes to created instances
      ec2_vol:
        instance: "{{ item.id }}"
        device_name: /dev/xvdb
        volume_size: 200
        volume_type: gp2
        iops: 600
      with_items: "{{ ec2.instances }}"
      register: ec2_vol
```
But I'll see if I can find corner cases and test the last couple versions of Ansible as well.
