### ISSUE TITLE
Separate force in file for symlink creation in force_dest and force_src

### ISSUE THREAD

**Issue by sedrubal** [ansible/ansible#14600]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```
##### Ansible Configuration:

`N/A`
##### Environment:

`N/A`
##### Summary:

On symlink creation ansible there should be a separate variable for:
- Force overwriting the `dest` if there is already an existing file
- Force the creation of the symlink, even if `src` not exists
##### Steps To Reproduce:

```
- name: create symlink
    file:
      src=/srv/srcfile
      dest=/etc/dstfile
      state=link
      force=yes
```
##### Expected Results:

There should be something like `force_dest` and `force_src` instead of only `force`
##### Actual Results:

One can only force the creation of the symlink in any case. (That's fatal for example when symlinking the ssh host key from a git repo to `/etc/ssh/ssh_host_key`: I want to force to overwrite, if there is already a key in a regular file (because I want to use my key and not the generated one) but ansible mustn't force the symlink creation if there is no `/srv/ssh_host_key`, because then I can't anymore ssh to my server)

**Comment by koenpunt** [comment]
Simply stat'ing the file isn't enough?

``` yml
- stat: path=/srv/srcfile
  register: srcfile
- name: create symlink
    file:
      src=/srv/srcfile
      dest=/etc/dstfile
      state=link
      force=yes
    when: srcfile.stat.exists
```
