### ISSUE TITLE
copy & assemble expand home directory (~) differently

### ISSUE THREAD

**Issue by santhoshsram** [ansible/ansible#14615]
##### Ansible Version:

```
ubuntu@config-server:~$ ansible --version
ansible 2.0.0.2
  config file = /home/ubuntu/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

ubuntu@config-server:~$ cat .ansible.cfg 
[defaults]
inventory = ~/ansible/inventory
host_key_checking = False
##### Environment:

All are ubuntu 14.04.3
##### Summary:

In my playbook I use relative paths beginning with ~/. The default user is ubuntu and I have become=true at the top hosts level. In the copy module ~/ is expanded to /home/user/ubuntu/, but in the assemble module same ~/ is expanded as /root/. I was expecting both modules (or in fact all modules) to expand ~/ the same way. I understand using become=yes (enabling sudo) has some effect on how the ~/ path is translated, but shouldn't that translation be uniform?
##### Steps To Reproduce:

For bugs, please show exactly how to reproduce the problem. For new
features, show how the feature would be used.

```

---
- hosts: masters
  #strategy: free
  remote_user: ubuntu
  become: true
  tasks:
  - name: example for copy module
    copy:
      src: ~/somefile.txt
      dest: /tmp/somefile.txt
  - name: example for assemble module
    assemble:
      src: ~/config-fragments
      dest: /tmp/config.txt

```
##### Expected Results:

What did you expect to happen when running the steps above?
For the above example of the playbook, both the file "somefile.txt" and the directory "config-fragments" are under /home/ubuntu. The copy module correctly finds the file at /home/ubuntu/somefile.txt and copies it over. However the assemble module looks for /root/config-fragments and fails.

The expectation is that both of them look in /home/ubuntu, or both of them look in /root. So the observed result is confusing.
