### ISSUE TITLE
GCE broken in Ansible 2.0

### ISSUE THREAD

**Issue by markkimsal** [ansible/ansible#14624]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Fresh install from ppa
##### Environment:

Unbuntu 14.04 64 in virtualbox
##### Summary:

GCE module dies if "credentials_file" is undefined and also dies if it **is** defined
##### Steps To Reproduce:

apt-get install ansible
apt-get install python-pip
pip install apache-libcloud
ansible-playbook /vagrant/provision-gce.yml

```
- name: Create a sandbox instance
  hosts: localhost
  vars:
    names: foo,bar
    machine_type: f1-micro
    image: debian-7
    zone: us-central1-a
    service_account_email: foo@example.com
    pem_file: "/vagrant/project.p12"
    project_id: 123456
  tasks:
    - name: Launch instances
      local_action: gce instance_names={{names}} machine_type={{machine_type}}
                    image={{image}} zone={{zone}}
                    service_account_email={{ service_account_email }}
                    credentials_file={{ credentials_file }}
                    project_id={{ project_id }}
      register: gce
    - name: Wait for SSH to come up
      local_action: wait_for host={{item.public_ip}} port=22 delay=10
                    timeout=60 state=started
      with_items: "{{gce.instance_data}}"


```
##### Actual Results:

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'credentials_file' is undefined"
```

If you change pem_file to credentials file you get

```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: credentials_file"}
```
