### ISSUE TITLE
clarify that become_user does not imply become: yes

### ISSUE THREAD

**Issue by Heliosmaster** [ansible/ansible#14635]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file =
  configured module search path = Default w/o overrides
```
##### Environment:

OSX Mavericks managing Ubuntu 14.04
##### Summary:

Become user does not seem to be working.
##### Steps To Reproduce:

I have it my playbook

```
- hosts:
  - demo

  roles:
    - role: publishing                                                                                                              |
      become_user: publishing
```

And yet if i debug the `ansible_user_id` is not the user publishing, but rather the user i normally ssh with.
##### Expected Results:

That the commands are executed as the user `publishing`, as if i just did `sudo -u publishing <cmd>`
##### Actual Results:

Command was executed as the default user (which is ofc a sudoer without password)
