### ISSUE TITLE
multiprocess bug report

### ISSUE THREAD

**Issue by yy-chen** [ansible/ansible#14636]
##### Issue Type:

- Bug Report
##### Ansible Version:

devel
##### Environment:

ubuntu
##### Summary:

when i start multiple playbooks, will random error.
##### Steps To Reproduce:

```
fatal: [10.0.0.100]: UNREACHABLE! => {"changed": false, "msg": "SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}

fatal: [10.0.0.100]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

fatal: [10.0.0.100]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
```

```
- hosts: "{{host}}"                                                                                    
  roles:                                                                                               
    - { role: test}                                                                                    


task: test                                                                                               
- name: test                                                                                                                 
  command: echo 1 >> /tmp/test1.txt                                                                                          
```
##### python code:

```
#coding=utf-8                                                                                          
#!/usr/bin/python                                                                                      
import sys                                                                                            
import random, time                                                                                    
import os                                                                                              
from multiprocessing import Pool, Process                                                              


def f(x, t):                                                                                           
    print 1                                                                                            
    cmd = 'test.yml --extra-vars \'{"host":"rel"}\''
    res = os.system(cmd)                                                                               

if __name__ == "__main__":                                                                             
    for i in range(10):                                                                                
        Process(target=f, args=(i, 1)).start()
```
