### ISSUE TITLE
Feature Request: Use of Blocks in Roles

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible#14672]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
2.0.1.0
```
##### Environment:
- Amazon Linux

```
# cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2015.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2015.09"
PRETTY_NAME="Amazon Linux AMI 2015.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2015.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/
```
##### Summary:

Ansible [Blocks](http://docs.ansible.com/ansible/playbooks_blocks.html) works great on tasks. It would be a lot clearer to see in just one file where multiple roles are defined with conditions.
##### Steps To Reproduce:

``` yaml
  pre_tasks:
    - wait_for: host=0.0.0.0 port=7000 timeout=120 delay=2 state=started
      ignore_errors: true
      register: result
  block:
    - role: common
  when: result|failed
```
##### Expected Results:

It would be great if above worked fine along with `rescue` and `always`
##### Actual Results:

``` sh
The offending line appears to be:

    - common
      when: result|failed
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
