### ISSUE TITLE
Passing dict variable defined in roles_defaults to role fails when dict merging is enabled

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#14678]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /home/dag/home-made/ansible.testing/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

``` ini
[defaults]
hash_behaviour = merge
```
##### Environment:

N/A
##### Summary:

The issue we are having is quite similar to an issue we have had on v1.9.4 and older (see  #12915), related to hash_merge().

When we set a dict through _role/defaults_ and we also set the same dict through _role_params_, the merge fails with the error:

```
PLAY ***************************************************************************
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleUnicode': 
{"public": true}
"{{ packages.foo_api }}"
```
##### Steps To Reproduce:

**ansible.cfg**

``` ini
[defaults]
hash_behaviour = merge
```

**group_vars/all**

``` yaml
packages:
  foo_api:
    name: api
    version: 1.2.3
    tomcat: 10
  foo_bar:
    name: bar
    version: 2.3.4
    tomcat: 11
```

**test70.yml**

``` yaml

---
- hosts: localhost
  gather_facts: no
  roles:
    - role: test70
      foo: '{{ packages.foo_api }}'
```

**roles/test70/defaults/main.yml**

``` yaml
foo:
  public: yes
```

**roles/test70/tasks/main.yml**

``` yaml

---
- name: '{{ foo.name }} : Test merging of vars'
  debug:
    var: foo
```
##### Expected Results:

I expect the following output:

```
PLAY ***************************************************************************

TASK [test70 : api : Test merging of vars] *************************************
ok: [localhost] => {
    "foo": {
        "name": "api", 
        "public": true,
        "tomcat": 10, 
        "version": "1.2.3"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### Actual Results:

But I get:

```
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'AnsibleUnicode': 
{"public": true}
"{{ packages.foo_api }}"
```

**Comment by dagwieers** [comment]
The above works fine on stable-1.9:

```
[dag@moria ansible.testing]$ ansible-playbook test70.yml 

PLAY [localhost] ************************************************************** 

TASK: [test70 | {{ foo.name }} : Test merging of vars] ************************ 
ok: [localhost] => {
    "var": {
        "foo": {
            "name": "api", 
            "public": true, 
            "tomcat": 10, 
            "version": "1.2.3"
        }
    }
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by dagwieers** [comment]
With PR #14679 (forward-port from stable-1.9 PR 14565), we no longer get the error, but the resulting dict is not merged as it is with stable-1.9:

```
PLAY ***************************************************************************

TASK [test70 : api : Test merging of vars] *************************************
ok: [localhost] => {
    "foo": {
        "name": "api", 
        "tomcat": 10, 
        "version": "1.2.3"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by mburz** [comment]
Similar problem here.

ansible.cfg contains:
`hash_behaviour = merge`

group_vars/localhost.yml contains:

```
---

dict0:
  k0: "group_value0"
  k1: "group_value1"

dict1:
  k: "{{ dict0 }}"

dict2:
  k:
    k0: "group_value0"
    k1: "group_value1"

```

host_vars/localhost.yml contains:

```
---

dict1:
  k:
    k0: "host_value0"

dict2:
  k:
    k0: "host_value0"

```

playbook file contains:

```
- hosts: localhost
  gather_facts: false
  tasks:
    - debug: var=dict1
    - debug: var=dict2
```

otuput:

```
PLAY ***************************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "dict1": {
        "k": {
            "k0": "host_value0"
        }
    }
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "dict2": {
        "k": {
            "k0": "host_value0", 
            "k1": "group_value1"
        }
    }
}

```
