### ISSUE TITLE
Help: Replace where line starts with

### ISSUE THREAD

**Issue by ivankennethwang** [ansible/ansible#14680]
Hi,

I have the file with content:

```
ExecStartPre=/bin/bash -c '/usr/bin/echo "TEST=%s"
ExecStartPre=/bin/bash -c '/usr/bin/echo "TEST=%s1235%b"
...
-e NVINSTANCE=%i \
```

I'd like to use the `replace` task to replace all lines that starts with `ExecStartPre` which contains `%` to `%%`.

```
tasks:
  - name: Escape %
        replace:
          dest: /tmp/test@.service
          regexp: '%'
          replace: '%%'
```

End file should be:

```
ExecStartPre=/bin/bash -c '/usr/bin/echo "TEST=%%s"
ExecStartPre=/bin/bash -c '/usr/bin/echo "TEST=%%s1235%%b"
...
-e NVINSTANCE=%i \
```

Thanks in advance.
