### ISSUE TITLE
Creating EC2 instance via Launch config

### ISSUE THREAD

**Issue by samohri** [ansible/ansible#14700]
ansible 1.9.1

Need to create a ansible script which will create a launch configuration and security group and will install jboss on newly create instances.

Below is my script to do all this but getting no host found error during roles deployment.

```

---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
     - group_vars/tags.yml
  tasks:
    - name: Create Launch Configuration
      ec2_lc:
        region: "{{ region }}"
        name: "{{ api_lc_name }}"
        image_id: "{{ image_id }}"
        key_name: "{{ keypair }}"
        instance_type: "{{ instance_type }}"
        security_groups: "{{ security_groups }}"
        volumes: "{{ volumes }}"
        instance_monitoring: yes

    - name: Auto Scaling Group for API
      ec2_asg:
        name: myasg
        load_balancers: "{{ api_lb }}"
        availability_zones: [ 'ap-southeast-2a', 'ap-southeast-2b' ]
        launch_config_name: API_LC
        vpc_zone_identifier: [ 'subnet1', 'subnet2' ]
        min_size: 2
        max_size: 4
        desired_capacity: 2
        region: "{{ region }}"
        tags:
          - Name: QAAPI
      register: asg_result

- hosts: tag_Name_QAAPI
  sudo: True
  remote_user: ec2-user
  gather_facts: True
  roles:
    - jboss-standalone
```

When i run this all work good but roles doesn't.
PLAY [tag_Name_QAAPI] *********************************************************
skipping: no hosts matched

Please suggest how can i register the newly created EC2 instances info with ansible hosts.
