### ISSUE TITLE
Potential dangerous behaviour of file module with state=absent

### ISSUE THREAD

**Issue by simonszu** [ansible/ansible#14706]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.0
  config file = /home/simonszu/.ansible.cfg
  configured module search path = Default w/o overrides

```
##### Ansible Configuration:

Default config, but disabled ansible_cowsay
##### Environment:

Master runs from Debian Jessie Stable, orchestrated nodes as well
##### Summary:

The file module has a potential dangerous behaviour when executed with `path: /some/path/{{ variable }}` and `state: absent` and you initialize {{ variable }} but it has no content, e.g. when it is a list, and you are commenting elements out ot this list for debugging purposes. 
In this case, the whole path-directory in `/some/path` is removed.
##### Steps To Reproduce:

Add the following task to a playbook:

```
file:
   path: /some/path/{{ item }}
   state: absent
with_items: some_list
```

and specify `some_list` in a variable scope that is visible to this playbook, but don't put any content to this list, just `some_list:`.
##### Expected Results:

I expected the directory to be unchanged, since there were no items to delete specified. Maybe a warning or error message that i am using an initialized, but content-less variable.
##### Actual Results:

The whole directory is deleted which contains the {{ item }} elements, in this example `/some/path/`

I assume this is because this playbook translates to

```
rm -r /some/path/item1
rm -r /some/path/item2
rm -r /some/path/item3
```

but without any items specified, but the variable initialized, it translates to 

```
rm -r /some/path/
```

actually followed by a string with zero-length. This command is then interpreted by the underlying linux as a command to delete the whole directory. 

It is quite unlikely that someone specifies an empty list, but if you do, maybe because you are commenting some or all elements out to debug a playbook, then you can get into this situation where ansible accidentally deletes the whole directory.

**Comment by bcoca** [comment]
An empty list will force a skip of the task, I cannot reproduce this. please give more detailed example.

```
---
- hosts: localhost
  gather_facts: false
  tasks:
    - file:
        path: /var/tmp/bcs/{{item}}
        state: absent
      with_items: []
```

has no effect, nor does this:

```
---
- hosts: localhost
  gather_facts: false
  vars:
    emptylist: []
  tasks:
    - file:
        path: /var/tmp/bcs/{{item}}
        state: absent
      with_items: "{{emptylist}}"
```

**Comment by bcoca** [comment]
even tried with  `with_items: emptylist` but that is just a deprecation warning

**Comment by bcoca** [comment]
also tried `emptylist: .` but that gives an error and also does not delete anything:

```
failed: [localhost] (item=.) => {"failed": true, "item": ".", "msg": "rmtree failed: [Errno 22] Invalid argument: '/var/tmp/bcs/.'"}
```

**Comment by dagwieers** [comment]
Besides, I would expect that `state=absent` would not remove a directory unless `recurse=true` is set (or maybe when the directory is empty too).

**Comment by simonszu** [comment]
Well, this is strange. 
To make it clear, this is the exact task in the playbook:

```
- name: ensure plugins are absent
  file:
    path: "/etc/munin/plugins/{{ item }}"
    state: absent
  with_items: munin_node_plugins_disabled
  notify: restart munin-node
  become: yes
```

This is the snipped of the according vars file:

```
  - swap
  - threads

munin_node_wildcard_plugins_active:
  - path: "if_"
    name: "if_eth0"

munin_node_plugins_disabled:

munin_plugin_config:
  -
    name: "apt"
    vars: |

```

This is the output of `ansible-playbook -vvvv`:

```
TASK [munin-node : ensure plugins are absent] **********************************
task path: /home/simonszu/ansible/roles/munin-node/tasks/main.yml:77
<estolad> ESTABLISH SSH CONNECTION FOR USER: None
<estolad> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,pub
lickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/simonszu/.ansible/cp/ansible-ssh-%h-%p-%r -tt estolad '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1456827098.7-
201430161645854 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1456827098.7-201430161645854 )" )'
<estolad> PUT /tmp/tmpuZuB74 TO /media/Storage/home/simonszu/.ansible/tmp/ansible-tmp-1456827098.7-201430161645854/file
<estolad> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbas
ed,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/simonszu/.ansible/cp/ansible-ssh-%h-%p-%r '[estolad]'
<estolad> ESTABLISH SSH CONNECTION FOR USER: None
<estolad> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,pub
lickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/simonszu/.ansible/cp/ansible-ssh-%h-%p-%r -tt estolad '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=bpiyyyncoqlblabjmithd
zbhczleowqd] password: " -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-bpiyyyncoqlblabjmithdzbhczleowqd; LANG=de_DE.UTF-8 LC_ALL=de_DE.UTF-8 LC_MESSAGES=de_DE.UTF-8 /usr/bin/python /media/Storage/hom
e/simonszu/.ansible/tmp/ansible-tmp-1456827098.7-201430161645854/file; rm -rf "/media/Storage/home/simonszu/.ansible/tmp/ansible-tmp-1456827098.7-201430161645854/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
changed: [estolad] => (item=None) => {"changed": true, "invocation": {"module_args": {"backup": null, "content": null, "delimiter": null, "diff_peek": null, "directory_mode": null, "follow": false, "force": fa
lse, "group": null, "mode": null, "original_basename": null, "owner": null, "path": "/etc/munin/plugins/", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null,
 "seuser": null, "src": null, "state": "absent", "validate": null}, "module_name": "file"}, "item": null, "path": "/etc/munin/plugins/", "state": "absent"}
```

...and after the playbook run, `/etc/munin/plugins` is indeed absent. 

If you want to have it, i will set the environment variable to keep the python code on the node, and send it to you.
