### ISSUE TITLE
Error on ec2_group module ```Invalid rule parameter '['```

### ISSUE THREAD

**Issue by rochacbruno** [ansible/ansible#14732]
##### Issue Type:
- Bug Report
##### Ansible Version:

Latest from github development

```
git clone git://github.com/ansible/ansible.git --recursive
cd ./ansible
git submodule update --init --recursive
python setup.py install

ansible --version
ansible 2.1.0
```

> NOTE: using version from February 3 the bug did not happen

```
git clone git://github.com/ansible/ansible.git --recursive
cd ./ansible

# CHECKOUT VERSION FROM FEBRUARY, 3
git checkout 699a854bf30784cd7514f4c1b6f8bd742868f7eb
git submodule update --init --recursive
python setup.py install

ansible --version
ansible 2.1.0
```
##### Ansible Configuration:

```
host_key_checking = False
```
##### Environment:

Ubuntu 14.04, Python 2.7
##### Summary:

Security groups is created but error occurred on "rules" steps
##### Steps To Reproduce:

Consider the playbook

```

---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    ansible_ssh_user: ubuntu
    group_name: TEST-ANSIBLE
    aws_region: us-east-1
  tasks:
    - name: Create security groups
      ec2_group:
        name: "{{group_name}}"
        description: an example EC2 group
        vpc_id: vpc-xxxxxxxxx
        region: "{{aws_region}}"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        purge_rules: true
        purge_rules_egress: true
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 10.0.0.0/8
          - proto: tcp
            from_port: 443
            to_port: 443
            group_id: API
          - proto: tcp
            from_port: 3306
            to_port: 3306
            group_id: RECSYS-BACKEND
          - proto: udp
            from_port: 10050
            to_port: 10050
            cidr_ip: 10.0.0.0/8
          - proto: udp
            from_port: 10051
            to_port: 10051
            group_id: API
          - proto: icmp
            from_port: 8 # icmp type, -1 = any type
            to_port:  -1 # icmp subtype, -1 = any subtype
            cidr_ip: 10.0.0.0/8
          - proto: all
            group_name: example
            group_desc: other example EC2 group
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: created_group
    - name: Tag group
      ec2_tag:
        region: "{{aws_region}}"
        aws_access_key: "{{aws_access_key}}"
        aws_secret_key: "{{aws_secret_key}}"
        resource: "{{created_group.group_id}}"
        state: present
        tags:
          Name: "{{group_name}}"
```
##### Expected Results:

> Success: Security created with specified rules

```
(recsys)rochacbruno@vaioubuntu:~/www/recsys/recsys_env/playbooks$ ansible-playbook staging_0_security_groups.yml -i hosts -vvvv
Using /home/rochacbruno/www/recsys/recsys_env/playbooks/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in staging_0_security_groups.yml
 ______
< PLAY >
 ------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _______________________________
< TASK [Create security groups] >
 -------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/rochacbruno/www/recsys/recsys_env/playbooks/staging_0_security_groups.yml:10
ESTABLISH LOCAL CONNECTION FOR USER: rochacbruno
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456859824.15-112093465669107 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456859824.15-112093465669107 `" )'
127.0.0.1 PUT /tmp/tmpSLWSFT TO /home/rochacbruno/.ansible/tmp/ansible-tmp-1456859824.15-112093465669107/ec2_group
127.0.0.1 EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /home/rochacbruno/.virtualenvs/recsys/bin/python /home/rochacbruno/.ansible/tmp/ansible-tmp-1456859824.15-112093465669107/ec2_group; rm -rf "/home/rochacbruno/.ansible/tmp/ansible-tmp-1456859824.15-112093465669107/" > /dev/null 2>&1'
changed: [localhost] => {"changed": true, "group_id": "sg-xxxxxxx", "invocation": {"module_args": {"aws_access_key": "xxxxxxxxxxx", "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "description": "an example EC2 group", "ec2_url": null, "name": "TEST-ANSIBLE", "profile": null, "purge_rules": true, "purge_rules_egress": true, "region": "us-east-1", "rules": [{"cidr_ip": "0.0.0.0/0", "from_port": 80, "proto": "tcp", "to_port": 80}], "rules_egress": null, "security_token": null, "state": "present", "validate_certs": true, "vpc_id": "vpc-xxxxxxxx"}, "module_name": "ec2_group"}}
 __________________
< TASK [Tag group] >
 ------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/rochacbruno/www/recsys/recsys_env/playbooks/staging_0_security_groups.yml:58
ESTABLISH LOCAL CONNECTION FOR USER: rochacbruno
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456859827.42-226866896793854 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456859827.42-226866896793854 `" )'
127.0.0.1 PUT /tmp/tmpdkifdn TO /home/rochacbruno/.ansible/tmp/ansible-tmp-1456859827.42-226866896793854/ec2_tag
127.0.0.1 EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /home/rochacbruno/.virtualenvs/recsys/bin/python /home/rochacbruno/.ansible/tmp/ansible-tmp-1456859827.42-226866896793854/ec2_tag; rm -rf "/home/rochacbruno/.ansible/tmp/ansible-tmp-1456859827.42-226866896793854/" > /dev/null 2>&1'
changed: [localhost] => {"changed": true, "invocation": {"module_args": {"aws_access_key": "xxxxxxxxxxxxxxxxx", "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "ec2_url": null, "profile": null, "region": "us-east-1", "resource": "sg-xxxxxxxxx", "security_token": null, "state": "present", "tags": {"Name": "TEST-ANSIBLE"}, "validate_certs": true}, "module_name": "ec2_tag"}, "msg": "Tags {'Name': 'TEST-ANSIBLE'} created for resource sg-xxxxxxxx."}
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=2    changed=2    unreachable=0    failed=0  
```
##### Actual Results:

> Error: `Invalid rule parameter '['`

```
(recsys)rochacbruno@vaioubuntu:~/www/recsys/recsys_env/playbooks$ ansible-playbook staging_0_security_groups.yml -i hosts -vvvv
Using /home/rochacbruno/www/recsys/recsys_env/playbooks/ansible.cfg as config file
Loaded callback default of type stdout, v2.0
 _________________________________________
< PLAYBOOK: staging_0_security_groups.yml >
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

1 plays in staging_0_security_groups.yml
 __________________
< PLAY [localhost] >
 ------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _______________________________
< TASK [Create security groups] >
 -------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/rochacbruno/www/recsys/recsys_env/playbooks/staging_0_security_groups.yml:10
ESTABLISH LOCAL CONNECTION FOR USER: rochacbruno
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1456859535.19-86505490953685 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1456859535.19-86505490953685 `" )'
127.0.0.1 PUT /tmp/tmpCGo79f TO /home/rochacbruno/.ansible/tmp/ansible-tmp-1456859535.19-86505490953685/ec2_group
127.0.0.1 EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /home/rochacbruno/.virtualenvs/recsys/bin/python /home/rochacbruno/.ansible/tmp/ansible-tmp-1456859535.19-86505490953685/ec2_group; rm -rf "/home/rochacbruno/.ansible/tmp/ansible-tmp-1456859535.19-86505490953685/" > /dev/null 2>&1'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"aws_access_key": "xxxxxxxxxxxxxxxxxxx", "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "description": "an example EC2 group", "ec2_url": null, "name": "TEST-ANSIBLE", "profile": null, "purge_rules": true, "purge_rules_egress": true, "region": "us-east-1", "rules": "[{'to_port': 80, 'from_port': 80, 'cidr_ip': '0.0.0.0/0', 'proto': 'tcp'}]", "rules_egress": null, "security_token": null, "state": "present", "validate_certs": true, "vpc_id": "vpc-xxxxxxx"}, "module_name": "ec2_group"}, "msg": "Invalid rule parameter '['"}
 ____________________
< NO MORE HOSTS LEFT >
 --------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

    to retry, use: --limit @staging_0_security_groups.retry
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```

> NOTE: using version from February 3 the bug did not happen

```
git clone git://github.com/ansible/ansible.git --recursive
cd ./ansible

# CHECKOUT VERSION FROM FEBRUARY, 3
git checkout 699a854bf30784cd7514f4c1b6f8bd742868f7eb
git submodule update --init --recursive
python setup.py install

ansible --version
ansible 2.1.0
```
