### ISSUE TITLE
Use variables in 'register'

### ISSUE THREAD

**Issue by vikas027** [ansible/ansible#14754]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.0.2
  config file = /usr/local/etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Environment:

Ansible Installed on OSX and manage Amazon Linux 
##### Summary:

Ansible is unable to use variables in [register](http://docs.ansible.com/ansible/playbooks_conditionals.html#register-variables)
##### Steps To Reproduce:

``` yaml
    ### WORKS
        - wait_for: host=0.0.0.0 port={{ item.port }}
          ignore_errors: true
          register: nginx
          with_items:
            - { name: 'nginx',    port: '80' }

        - debug: var=nginx


    ### DOES NOT WORKS
        - wait_for: host=0.0.0.0 port={{ item.port }}
          ignore_errors: true
          register: "{{ item.name }}"
          with_items:
            - { name: 'nginx1',    port: '80' }

        - debug: var=nginx1

```
##### Expected Results:

Variable `nginx1` should have been interpolated in `register`
##### Actual Results:

```
    ## Error in play
    TASK [debug] *******************************************************************
    ok: [my_server] => {
        "nginx1": "VARIABLE IS NOT DEFINED!"
    }
```
