### ISSUE TITLE
I got deprecated errors, which doesn't show me where is the error. Can you help to me?

### ISSUE THREAD

**Issue by PumpkinSeed** [ansible/ansible#14781]
##### Issue Type:

Deprecated errror with message
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

```
- name: Ensure auth_basic files created
  template: src=auth_basic.j2 dest={{nginx_conf_dir}}/auth_basic/{{ item }} owner=root group={{nginx_group}} mode=0750
  with_items: "{{nginx_auth_basic_files.keys()}}"
  tags: [configuration,nginx]

- name: Create the configurations for sites
  template: src=site.conf.j2 dest={{nginx_conf_dir}}/sites-available/{{ item }}.conf
  with_items: "{{nginx_sites.keys() | difference(nginx_remove_sites)}}"
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Create links for sites-enabled
  file: state=link src={{nginx_conf_dir}}/sites-available/{{ item }}.conf dest={{nginx_conf_dir}}/sites-enabled/{{ item }}.conf
  with_items: "{{nginx_sites.keys() | difference(nginx_remove_sites)}}"
  notify:
   - reload nginx
  tags: [configuration,nginx]

- name: Create the configurations for independent config file
  template: src=config.conf.j2 dest={{nginx_conf_dir}}/conf.d/{{ item }}.conf
  with_items: "{{nginx_configs.keys()}}"
  notify:
   - reload nginx
  tags: [configuration,nginx]
```

site.conf.j2:

```
#{{ ansible_managed }}
server {
{% for v in nginx_sites[item] %}
{% if v.find('\n') != -1 %}
   {{v.replace("\n","\n   ")}}
{% else %}
   {% if v != "" %}{{ v.replace(";",";\n      ").replace(" {"," {\n      ").replace(" }"," \n   }\n") }}{% if v.find('{') == -1%};
{% endif %}{% endif %}{% endif %}
{% endfor %}
}
```
##### Environment:

CentOS 7 
##### Error message:

```

TASK [jdauphant.nginx : Ensure auth_basic files created] ***********************

TASK [jdauphant.nginx : Create the configurations for sites] *******************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.. This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [jdauphant.nginx : Create links for sites-enabled] ************************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.. This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [jdauphant.nginx : Create the configurations for independent config file] *
```
