### ISSUE TITLE
jinja-syntax errors in playbooks do not result in context printed.

### ISSUE THREAD

**Issue by ari-s** [ansible/ansible#14790]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Summary:

jinja-syntax errors in playbooks do not result in context printed.
##### Steps To Reproduce:

run the following playbook after exchanging host to one you have access to

```

---
- name: test
  hosts: [ playgound.ccczh.ch ]
  vars:
    directory: /tmp
  tasks:
    - command: ls chdir={{ directory }
```

note the missing closing brace.

##### Expected Results:

usually syntax errors result in messages like the following:

```
ERROR! error while splitting arguments, either an unbalanced jinja2 block or quotes

The error appears to have been in '/tmp/test.yml': line n, column m, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
  tasks:
    - command: ls chdir={{ directory }
                                     ^ here
```
##### Actual Results:

```
# ansible-playbook test.yml
ERROR! error while splitting arguments, either an unbalanced jinja2 block or quotes
<!--- Paste verbatim command output here -->
```
