### ISSUE TITLE
regression: IPv4/IPv6 filter broken in ansible 2.x (works with 1.9.x)

### ISSUE THREAD

**Issue by nusenu** [ansible/ansible#14829]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.3.1.0
```
##### Environment:

N/A

##### COMPONENT NAME:
filters

##### Summary:

with_together loop does no longer work with empty member when using ansible 2.0.1.0
##### Steps To Reproduce:

On a target with IPv4 IPs but without IPv6 IPs run this task:

```
- name: setup IP list (1/2)
  set_fact:
    ips:
        ipv4: "{{ item.0 }}"
        ipv6: "{{ item.1 }}"
  with_together:
        - "{{ ansible_all_ipv4_addresses }}"
        - "{{ ansible_all_ipv6_addresses }}"
  register: ipsinterm
```

https://github.com/nusenu/ansible-relayor/blob/61a4057895a1c98e8b895e75bc1df30033af502a/tasks/ip-list.yml#L3
##### Expected Results:

No failure.
##### Actual Results:

```
FAILED! => {"failed": true, "msg": "an unexpected type error occurred.
Error was 'bool' object has no attribute '__getitem__'"}
```

https://groups.google.com/d/msgid/ansible-project/56DAB742.8010705%40openmailbox.org

update (2017-06-06): changed version to 2.3.1
