### ISSUE TITLE
local_action status changed

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#14820]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

default
##### Environment:

OSX
##### Summary:

`local_action shell` is always marked as changed. And when you run with `with_items` there seem to be no way to implement a custom `changed_when` based on stdout or item status.
##### Steps To Reproduce:

``` yml
- name: status check
  local_action: shell true
  run_once: true
  become: no
  tags: test
```
##### Expected Results:

```
ok: [dev01.example.org -> localhost]
```
##### Actual Results:

```
changed: [dev01.example.org -> localhost]
```

```
TASK [internal/go-deploy : status check] ***************************************
task path: /Users/hryamzik/ansible/example-playbooks/roles/internal/go-deploy/tasks/main.yml:40
ESTABLISH LOCAL CONNECTION FOR USER: hryamzik
10.10.10.10 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1457192588.74-127955230280658 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1457192588.74-127955230280658 `" )'
10.10.10.10 PUT /var/folders/79/szcjwt696vj84xrt7n_khg8w0000gn/T/tmpYEtlGO TO /Users/hryamzik/.ansible/tmp/ansible-tmp-1457192588.74-127955230280658/command
10.10.10.10 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/hryamzik/.ansible/tmp/ansible-tmp-1457192588.74-127955230280658/command; rm -rf "/Users/hryamzik/.ansible/tmp/ansible-tmp-1457192588.74-127955230280658/" > /dev/null 2>&1'
changed: [dev01.example.org -> localhost] => {"changed": true, "cmd": "true", "delta": "0:00:00.005203", "end": "2016-03-05 18:43:08.854436", "invocation": {"module_args": {"_raw_params": "true", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-03-05 18:43:08.849233", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by sivel** [comment]
Certain modules such as shell and command, always return `changed=True`. To control this, you can use `changed_when` to add logic as to when you want it to actually be marked as changed.

As for `with_items` you can still use `changed_when`.

Here is an example playbook:

```
---
- hosts: all
  gather_facts: false
  vars:
    iterations:
      - foo
      - bar
      - baz
  tasks:
    - local_action: "shell echo {{ item }}"
      with_items: "{{ iterations }}"
      register: result
      changed_when: result.stdout == "bar"

    - local_action: "shell true"
      changed_when: false
```

Which results in the following output:

```
PLAY [all] *********************************************************************

TASK [command] *****************************************************************
ok: [localhost -> localhost] => (item=foo)
changed: [localhost -> localhost] => (item=bar)
ok: [localhost -> localhost] => (item=baz)

TASK [command] *****************************************************************
ok: [localhost -> localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

If you have further questions please stop by IRC or the mailing list:
- IRC: #ansible on irc.freenode.net
- mailing list: https://groups.google.com/forum/#!forum/ansible-project
