### ISSUE TITLE
[2.x]: inconsistency in action plugins copy, template base path

### ISSUE THREAD

**Issue by resmo** [ansible/ansible#14821]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (devel 45b7fe1590) last updated 2016/03/05 09:15:36 (GMT +200)
ansible 2.0.1.0
```
##### Ansible Configuration:

Default.
##### Environment:

"N/A"
##### Summary:

Playbooks containing copy or template rely on the location where the playbook is stored to find the file in `src=`

This works:

```
ansible-playbooks test-path.yml
```

Copy the same playbook into a subdir and run it again, fails:

```
ansible-playbooks playbooks/test-path.yml
```

if you run tasks related to path as local actions, we get some inconsistent behaviors, most of the modules takes the base path (where your custom ansible.cfg is located) as source:
- shell: with chdir
- stat: path
- file: path

However the modules copy and template takes the relative path in `./playbooks/` as source but as destination the base path, which means if you want to use template locally writing in the very same directory, you have to give a `../`to the `src=`:
##### Steps To Reproduce:

Run this playbook from a subdir

``` yaml

---
- hosts: localhost
  gather_facts: no
  connection: local

  vars:
    my_file_path: files/foo

  tasks:
  - name: create a dir in base dir
    file: path={{ my_file_path }} state=directory

  - name: create a file in base dir
    shell: touch myfile chdir={{ my_file_path }}

  - stat: path={{ my_file_path }}/myfile
    register: result
  - name: chdir path ok
    assert:
      that:
      - "result.stat.exists == true"

# THIS WILL FAIL IF YOU RUN IN A SUBDIR
  - name: copy from base dir to base dir with different file name
    copy: src={{ my_file_path }}/myfile dest={{ my_file_path }}/myfile.copy

  - stat: path={{ my_file_path }}/myfile.copy
    register: result
  - name: copy src and dest path ok
    assert:
      that:
      - "result.stat.exists == true"
```
##### Expected Results:

I would have expected that it does not make any difference where the playbook is located to find the file in src= in copy and template, and it may a bit weird that the base path for src= and dest= is different.
##### Actual Results:

```
TASK [copy src looks for ./files/foo relative to this playbook] ****************

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "could not find src=/home/resmo/tmp/ansible-test-path/playbooks/files/foo/myfile"}
```
