### ISSUE TITLE
Strange notation

### ISSUE THREAD

**Issue by igormukhingmailcom** [ansible/ansible#14844]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 1.9.2
  configured module search path = None
```
##### Environment:

MacOSX
Debian
##### Summary:

Ansible put some variables in place as:

```
'u''variable_value'''
```

It prepend `'u''` and append `'''`, but should be just `variable_value`.
##### Steps To Reproduce:

```
vars:
    variable_with_value: "variable_value"
    variable_name: "{{ variable_with_value }}"
task:
  - template:
      src: /testfile.yml.j2
      dest: /testfile.yml
```

```
# testfile.yml.j2
variable_name: {{ variable_name }}
```

Result is: 

```
# /testfile.yml
variable_name: 'u''variable_value'''
```
##### Expected Results:

```
# /testfile.yml
variable_name: variable_value
```
##### Actual Results:

```
# /testfile.yml
variable_name: 'u''variable_value'''
```

Thanks.
