### ISSUE TITLE
Iterating over multiple includes fails

### ISSUE THREAD

**Issue by windowsrefund** [ansible/ansible#14850]
#### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (fix-ec2-group-rules 283532e11d) last updated 2016/02/22 15:03:06 (GMT -400)
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

item is not overwritten on the second level of include
##### Steps To Reproduce:

test1.yml

```
---                                                                            
- name: Looping with includes test                                              
  hosts: localhost                                                              
  connection: local                                                            
  become: False                                                                
  gather_facts: no                                                              
  tasks:                                                                        
    - include: test2.yml                                                        
      with_items:                                                              
        - foo:                                                                  
          - 1                                                                  
          - 2                                                                  
          - 3                                                                  
        - bar:                                                                  
          - a                                                                  
          - b                                                                  
          - c
```

test2.yml

```
- set_fact:                                                                    
    outer_item: "{{ item }}"

- include: test3.yml
  with_dict: "{{ outer_item }}"
```

test3.yml

```
- set_fact:
  the_key: "{{ item.key }}"

- debug: msg="The key is {{ the_key }}"
```
##### Expected Results:

test3.yml should set the_key to the key of the hash passed as input
##### Actual Results:

```
PLAY [Looping with includes test] **********************************************

TASK [include] *****************************************************************
included: /home/akosmin/sailthru/github/ansible/roles/aws-ec2/tests/test2.yml for localhost
included: /home/akosmin/sailthru/github/ansible/roles/aws-ec2/tests/test2.yml for localhost

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [include] *****************************************************************
included: /home/akosmin/sailthru/github/ansible/roles/aws-ec2/tests/test3.yml for localhost

TASK [set_fact] ****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'key'"}
        to retry, use: --limit @roles/aws-ec2/tests/test1.retry

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1
```
