### ISSUE TITLE
docker: "unsupported parameter for module: labels"

### ISSUE THREAD

**Issue by gtaylor** [ansible/ansible#14869]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

[defaults]
forks=50
poll_interval=7
library=./library
host_key_checking=False
retry_files_save_path = ~/.ansible-retry

[ssh_connection]
pipelining=True
##### Environment:

Ubuntu 15.10
Python 2.7.9
##### Summary:

I'm unable to use the `labels` param to the `docker` module. I get a "`fatal: [xxx.xx.xx.xx]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: labels"}`
##### Steps To Reproduce:

```
- name: make sure ingestor container is running
  docker:
    image: quay.io/myrepo/myimage:{{ ingestor_image_tag }}
    # Number of containers to run with this image.
    count: "{{ container_count }}"
    labels:
      mylabel: labelval
    state: reloaded
    pull: missing
    # Restart repeatedly if crashed.
    restart_policy_retry: "0"
    # Add the host machine's docker0 IP to /etc/hosts within container so we
    # can reach Datadog/fluentd/etc.
    extra_hosts:
      dockerhost: "{{ ansible_docker0['ipv4']['address'] }}"
    volumes:
      - "{{ BACKEND_ENV }}/src/{{ PROJECT_DIR }}/conf:/etc/ingestor/conf"
```
##### Expected Results:

I expect the container to be started with the label above attached.
##### Actual Results:

```
TASK [../site_roles/ingestor_docker : make sure ingestor container is running] *
task path: /home/greg.taylor/workspace/site_roles/ingestor_docker/tasks/main.yml:15
<xxx.xxx.xx.xx> ESTABLISH SSH CONNECTION FOR USER: greg.taylor
<xxx.xxx.xx.xx> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=greg.taylor -o ConnectTimeout=10 -o ControlPath=/home/greg.taylor/.ansible/cp/ansible-ssh-%h-%p-%r xxx.xxx.xx.xx '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-gxajsopgrgjpfubylssbmimcvafgcdps; /bin/sh -c '"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"'"''"'"'"'"'"'"'"'"''"'"''
fatal: [xxx.xxx.xx.xx]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"count": 3, "env": {}, "extra_hosts": {"dockerhost": "172.17.0.1"}, "image": "quay.io/myrepo/myimage:v1.0.6", "labels": {"mylabel": "labelval"}, "pull": "missing", "restart_policy_retry": "0", "state": "reloaded", "volumes": ["/venv/backend/src/ingestor/conf"]}, "module_name": "docker"}, "msg": "unsupported parameter for module: labels"}
```

I mangled some of the paths for privacy's sake.
