### ISSUE TITLE
task not considered changed with changed_when set to rc != 0 and ignore_errors: true

### ISSUE THREAD

**Issue by ari-s** [ansible/ansible#14877]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### Summary:

for a task that has changed_when set to program failure ansible does not consider the task changed. As a consequence handlers are not being run.
this bug is introduced somewhere between 1.7.2 and 2.0.1.0, but most probably with ansible 2
##### Steps To Reproduce:

Consider this playbook

```

---
- name: test
  hosts: playground.ccczh.ch
  tasks:
  - name: test
    shell: "false"
    notify: barbaz
    register: test
    changed_when: "test.rc == 1"
    # failed_when: "test.rc == 0"
    ignore_errors: true
  handlers:
  - name: barbaz
    shell: echo foo
<!--- Paste example playbooks or commands here -->
```

ansible 1.7.4. notifies the barbaz-handler:

```
TASK: [test] ****************************************************************** 
failed: [playground.ccczh.ch] => {"changed": true, "cmd": "false", "delta": "0:00:00.003002", "end": "2016-03-09 08:41:22.027993", "rc": 1, "start": "2016-03-09 08:41:22.024991", "stdout_lines": []}
...ignoring

NOTIFIED: [barbaz] ************************************************************ 
changed: [playground.ccczh.ch]

PLAY RECAP ******************************************************************** 
playground.ccczh.ch        : ok=3    changed=2    unreachable=0    failed=0   
```

while ansible 2.0.1.0 does not, does not count the task as changed, but also not as failed: 

```
TASK [test] ********************************************************************
fatal: [playground.ccczh.ch]: FAILED! => {"changed": true, "cmd": "false", "delta": "0:00:00.002459", "end": "2016-03-09 08:41:56.485175", "failed": true, "rc": 1, "start": "2016-03-09 08:41:56.482716", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
...ignoring

PLAY RECAP *********************************************************************
playground.ccczh.ch        : ok=2    changed=0    unreachable=0    failed=0   
```

with the commented failed_when key ansible 2 considers this task changed.

from the yml I really expect this to be what 1.7.4 does, I mean, the command returns the value that is specified in changed_when and ignore_errors makes it not count as failed.
