### ISSUE TITLE
`with_flattened` erroneously treats strings as variables

### ISSUE THREAD

**Issue by gechr** [ansible/ansible#14900]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /Users/<user>/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
inventory                   =  /usr/local/etc/ansible/hosts

[ssh_connection]
private_key_file            =  ~/.ssh/id_rsa.ansible

[defaults]
inventory                   =  /etc/ansible/hosts
remote_tmp                  =  $HOME/.ansible/tmp
pattern                     =  *
forks                       =  50
poll_interval               =  15
sudo_user                   =  root
transport                   =  smart
module_lang                 =  C
gathering                   =  implicit
host_key_checking           =  False
sudo_exe                    =  sudo
timeout                     =  10
hash_behaviour              =  merge
jinja2_extensions           =  jinja2.ext.do
ansible_managed             =  Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins              =  /usr/share/ansible_plugins/action_plugins
callback_plugins            =  /usr/share/ansible_plugins/callback_plugins
connection_plugins          =  /usr/share/ansible_plugins/connection_plugins
lookup_plugins              =  /usr/share/ansible_plugins/lookup_plugins
vars_plugins                =  /usr/share/ansible_plugins/vars_plugins
filter_plugins              =  /usr/share/ansible_plugins/filter_plugins
fact_caching                =  memory

[accelerate]
accelerate_port             =  5099
accelerate_timeout          =  30
accelerate_connect_timeout  =  5.0
accelerate_daemon_timeout   =  30
```
##### Environment:

N/A
##### Summary:

`with_flattened` erroneously tries to interpolate items which should be treated as strings, as if they were variables.
##### Steps To Reproduce:

Dump the following into a file and run `ansible-playbook <filename>`

```
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    stuff_to_echo:
      - groups
      - users
    more_stuff_to_echo:
      - foo
      - bar
    even_more_stuff_to_echo:
      - hello
      - goodbye
  tasks:
    - name: Echo stuff
      shell: "echo {{ item }}"
      with_flattened:
        - "{{ stuff_to_echo }}"
        - "{{ more_stuff_to_echo }}"
        - "{{ even_more_stuff_to_echo }}"
```
##### Expected Results:

`groups` should not be interpolated

```
[...]
changed: [localhost] => (item=groups)
changed: [localhost] => (item=users)
changed: [localhost] => (item=foo)
changed: [localhost] => (item=bar)
changed: [localhost] => (item=hello)
changed: [localhost] => (item=goodbye)
[...]
```
##### Actual Results:

`groups` is interpolated and a deprecation warning is displayed

```
[...]
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{groups}}'). This feature will be removed in a future release. Deprecation warnings can
 be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [localhost] => (item={'all': [u'localhost', u'host-1.example.com', u'host-2.example.com', u'host-3.example.com']})
changed: [localhost] => (item=users)
changed: [localhost] => (item=foo)
changed: [localhost] => (item=bar)
changed: [localhost] => (item=hello)
changed: [localhost] => (item=goodbye)
[...]
```
