### ISSUE TITLE
notify: with_items

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#14918]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

default
##### Summary:

`notify` and `with_items` do not work as expected
##### Steps To Reproduce:

Run any task with a list of items with notify, in my case I had only the last file changed

```
- name: put runit services files
  template: src={{ item.f }} dest=/etc/sv/{{ runit_service_name }}/{{ item.f }} owner=root group=root mode=0755
  with_items:
    - { f: run        , h: restart, s: "{{ runit_service_name }}" }
    - { f: log/run    , h: restart, s: "{{ runit_service_name }}/log" }
    - { f: log/config , h: hup    , s: "{{ runit_service_name }}/log" }
  notify: runit {{ item.h }} {{ item.s }} 
```
##### Expected Results:

For the last file changed I would expect to see handler `runit hup {{ runit_service_name }}/log` to be notified.
##### Actual Results:

`runit restart {{ runit_service_name }}` is triggered
