### ISSUE TITLE
mysql_db module fails to report some underlying SQL exceptions

### ISSUE THREAD

**Issue by d-lee** [ansible/ansible#14927]
##### Issue Type:
- Bug Report
##### Ansible Version:

`ansible 2.0.1.0`
##### Ansible Configuration:

Default
##### Environment:

N/A
##### Summary:

mysql_db module fails to report underlying SQL exceptions when state is `import`
##### Steps To Reproduce:

execute mysql_db task with state `import`, passing SQL script that contains commands that cause SQL exception, e.g. INSERT into a non-existent table.
##### Playbook Excerpt:

```
- name: Insert record
  run_once: true
  delegate_to: localhost
  mysql_db:
    login_host: "{{ db_host }}"
    login_port: "{{ db_port }}"
    login_user: "{{ db_user }}"
    login_password: "{{ db_pass }}"
    name: "{{ db_name }}"
    state: import
    target: /tmp/insert_record.sql
```
##### Expected Results:

mysql_db task should fail and report underlying SQL exception that caused the failure of the task.
e.g.

```
>[Error] Script lines: 5-15 -------------------------
 Table 'db.test_table' doesn't exist
```
##### Actual Results:

mysql_db reports success even though no records were actually inserted due to a SQL exception

```
TASK [Insert record] ****************************************
ok: [127.0.0.1 -> localhost]
```
##### Note:

Please note that some exceptions are properly detected. For example syntax errors in DML statements
