### ISSUE TITLE
Synchronize does not use playbook directory in 2.1

### ISSUE THREAD

**Issue by iquito** [ansible/ansible#14944]
##### Issue Type:

- Bug Report
##### Ansible Version:

```
ansible 2.1.0
```
##### Summary:

I have been using synchronize the following way (update-config.yml):

```
synchronize:
      src: config/
      dest: /directory/config
      delete: yes
      recursive: yes
```

and called the playbook with

```
ansible-playbook directory/update-config.yml
```

This worked fine in ansible 1.9.2, but in 2.1, it tries to resolve config/ from the directory I am in, not the directory the playbook is in, meaning it looks for `config/` instead of `directory/config/` and does not find anything (or in other scenarios it might just find the wrong stuff).
