### ISSUE TITLE
recursive loop detected in template string

### ISSUE THREAD

**Issue by bessdsv** [ansible/ansible#14946]
##### Issue Type:
- Bug Report
##### Ansible Version:

1.9.4
##### Ansible Configuration:

no changes
##### Environment:

RedHat 6
##### Summary:

get error recursive loop detected in template string
## group_vars/all

subsystems: {
  sc_ucs: {
    name: "sc_ucs",
    usr: {
      version: "",
      arhive_name: "sc_ucs-usr.zip",
      arhive_path: "{{distrib_path}}/{{subsystems.sc_ucs.usr.arhive_name}}",
      template_path: "{{templates_path}}/sc_ucs_usr",
      war_file_name: "sc_ucs.war",
      war_file_path: "Distrib"
    }
  }
}

distrib_path: "../../distrib"
temp_folder_path: "/home/{{ansible_ssh_user}}/temp"
templates_path: "templates"
## playbook
- name: scc_install
  hosts: servers_sc_ucs_usr_tomcat
  roles:
  - { role: tomcat-deploy, tags: ["sc_ucs_usr", "sc_ucs", "scc"], war_file_name: "{{subsystems.sc_ucs.usr.war_file_name}}"}
## tomcat-deploy role
- stat: path={{tomcat_root_path}}/webapps/{{war_file_name}}
  register: app_file
##### Expected Results:

no errors
##### Actual Results:

Failed to template {{distrib_path}}/{{subsystems.sc_ucs.usr.arhive_name}}: recursive loop detected in template string: {{distrib_path}}/{{subsystems.sc_ucs.usr.arhive_name}}

I think that the problem in the use of variables from one directory inside each other

**Comment by nomasprime** [comment]
Any chance of cleaning up the issue so can read the code?

I'm having a problem with https://gist.github.com/habitullence/d4ed3999fb5fbe99a66d11b2ad16190d. Where I get a recursive loop in template string error. As soon as I flatten the vars, i.e, no nginx:, it works.

Is this the same issue?

**Comment by walterdolce** [comment]
This also affects `ansible 2.2.1.0` with the following setup:

```
# roles/some_role/vars/main.yml
---
some_role:
    app:
        base_dir:
            path: "/some/path"
            owner: root
            group: root
            mode: 0755
    config:
        file:
            owner: "{{ some_role.app.base_dir.owner }}"
            group: "{{ some_role.app.base_dir.group }}"
            mode: 0770

# roles/some_role/tasks/main.yml
---
- name: "Create application base directory"
  file:
    path: "{{ some_role.app.base_dir.path }}"
    owner: "{{ some_role.app.base_dir.owner }}"
    group: "{{ some_role.app.base_dir.group }}"
    mode: "{{ some_role.app.base_dir.mode }}"
    state: directory
    recurse: yes

# playbook.yml
---
- hosts: all
  become: yes
  gather_facts: yes

  roles:
    - some_role
```
