### ISSUE TITLE
git update with depth limit creates too big local repo

### ISSUE THREAD

**Issue by ljesmin** [ansible/ansible#14954]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible 1.9.4
  configured module search path = None
```

and 

```
ansible 2.0.1.0
  config file = /home/XXX/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
nocows = 1
```
##### Environment:

Fedora 23, git version 2.5.0
##### Summary:

When running playbook with git statement that has update=yes and depth=1, behaviour has changed with version 2.0. 

Now updated repository will become much bigger.
##### Steps To Reproduce:

Run this playbook with ansible 1.9 and 2.0 twice: 

```

---
- hosts: 127.0.0.1
  connection: local
  become: no
  tasks:
  - name: check out pma from git
    git: dest=./pma depth=1 update=yes repo=https://github.com/phpmyadmin/phpmyadmin.git
```
##### Expected Results:

With Ansible 1.9, in both runs the resulting size of pma directory is 76M. Would expect that in 2.0 result would be same, so updated repo does not grow without any updates.
##### Actual Results:

WIth Ansible 2.0, first run result ./pma dir 76M size but second run 
(updating cloned git repo) is resulting 603M directory.
