### ISSUE TITLE
yumrepo module "params" options doesn't work

### ISSUE THREAD

**Issue by thechile** [ansible/ansible#14970]
This is using ansible 2.1.0 (devel e762095497)

Neither of the below seem to work. The `params` options should allow arbitrary options to be added to the yum repo file that are not exposed via module. I want to add the `priority` option.

```
vars:
  yum:
    priority: 1
tasks:
  - name: add_example_repository
    yumrepo:
      name: example_repository
      description: Example Repository
      baseurl: http://example/
      params: "{{ yum }}"
```

or

```
tasks:
  - name: add_example_repository
    yumrepo:
      name: example_repository
      description: Example Repository
      baseurl: http://example/
      params: { priority: 1 }
```

It never gets added to target machine. Adding some print output to module it seems that `module.params['params']` is `"<type 'str'>` and not `dict` so isn't appended as expected. 

Can someone confirm how the `params` option should be defined in the palybook to make this work ?
