### ISSUE TITLE
Jinja "if" statement doesn't coerce strings to bools

### ISSUE THREAD

**Issue by srkiNZ84** [ansible/ansible#14983]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
  config file = /Users/srdan/code/ansible_play/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
hash_behaviour=merge
```
##### Environment:

OS X 10.11.3, Ubuntu Linux 14.04 LTS
##### Summary:

When passing variables on the command line with the "-e" switch (e.g. "... -e foo=bar"), if the variable values are set to any of:
- True
- False
- true
- false
- yes
- no

They are not interpreted by the Jinja template "if" statement as booleans and are merely checked for whether or not they are defined:

```
{% if foo %}
... [always gets called, even if "foo=False"]
{% else %}
... [never gets called]
```
##### Steps To Reproduce:

Template (called "blah.txt.j2"):

```
{% if sync_node %}
synchronization.enabled=true
{% else %}
synchronization.enabled=false
{% endif %}
```

Playbook (called "template_test.yml"):

```
- hosts: all
  tasks:
    - name: Interpret the template to blah.txt
      connection: local
      template: src=blah.txt.j2 dest=/Users/srdan/code/ansible_play/blah.txt
```

Command:

```
ansible-playbook -i hosts template_test.yml -e sync_node=False
```

Hosts file:

```
localhost ansible_connection=local
```
##### Expected Results:

```
# cat blah.txt
synchronization.enabled=false
```
##### Actual Results:

```
# cat blah.txt
synchronization.enabled=true
```
