### ISSUE TITLE
delegate_facts doesn't return proper list

### ISSUE THREAD

**Issue by Roydon** [ansible/ansible#14981]
##### Issue Type:

- Bug Report

I am trying to create host file with following task following the [doc](http://docs.ansible.com/ansible/playbooks_delegation.html#delegated-facts) . In my task, it will be running on completely different set of machines than the entry of the hosts in hosts file. So I am trying to gather facts first, then use them in the task/template

Task :

```
- name: get facts
  setup:
  delegate_to: "{{item}}"
  delegate_facts: True
  with_items: "{{ groups['hadoop-' + dc] }}"
  tags:
    - etc-hosts

- name: Update /etc/hosts
  template: src=etc-hosts.j2 dest=/etc/hosts
  tags:
    - etc-hosts
```

Template : etc-hosts.j2

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
 ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

{% for host in groups['hadoop-' + dc] %}
{{ hostvars[host]['ansible_eth0']['ipv4']['address'] }} {{ host }}
{% endfor %}`
```

This does create hostfile with desired hosts entry, but put same ip address for all hosts.

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

172.16.16.85 hcm001.dev.abc.cc
172.16.16.85 hnn001.dev.abc.cc
172.16.16.85 hnn002.dev.abc.cc
172.16.16.85 hmn001.dev.abc.cc
172.16.16.85 hmn002.dev.abc.cc
172.16.16.85 hdp001.dev.abc.cc
172.16.16.85 hdp002.dev.abc.cc
172.16.16.85 hdp003.dev.abc.cc`
```

but I want something like this

```
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

172.16.16.85 hcm001.dev.abc.cc
172.16.16.80 hnn001.dev.abc.cc
172.16.16.87 hnn002.dev.abc.cc
172.16.16.80 hmn001.dev.abc.cc
172.16.16.89 hmn002.dev.abc.cc
172.16.16.90 hdp001.dev.abc.cc
172.16.16.91 hdp002.dev.abc.cc
172.16.16.95 hdp003.dev.abc.cc`
```
##### Ansible Version:

```
ansible 2.0.1.0
  config file = ~/ansible/ansible.cfg
  configured module search path = /usr/share/my_modules/
```
##### Environment:

I am on Mac OS X 10.11.3 (15D21)
