### ISSUE TITLE
Using explicit paths with Jinja2 includes in templates

### ISSUE THREAD

**Issue by cmacrae** [ansible/ansible#14992]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /home/cmacrae/git/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

`ansible.cfg`:

``` ini
[defaults]
remote_tmp          = $HOME/.ansible/tmp
pattern             = *
forks               = 16
poll_interval       = 15
sudo_user           = root
remote_user         = root
transport           = smart
remote_port         = 22
module_lang         = C
gathering           = implicit
roles_path          = roles
host_key_checking   = False
sudo_exe            = sudo
timeout             = 10
roles_path      = roles/external:roles/internal
ansible_managed     = Ansible managed: last modified by {uid} on {host}
retry_files_enabled = False

[accelerate]
accelerate_port            = 5099
accelerate_timeout         = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout  = 30
```
##### Environment:

Ansible control node: 

```
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:        15.10
Codename:       wily
```

System being deployed to:

```
Distributor ID: CentOS
Description:    CentOS Linux release 7.2.1511 (Core) 
Release:        7.2.1511
Codename:       Core
```
##### Summary:

When using [the Jinja2 `include` statement](http://jinja.pocoo.org/docs/dev/templates/#include) in templates, paths to partials being included are relative only to either the directory which houses the parent template (using the `include`) or the directory the playbook is being run from.
##### Steps To Reproduce:

Using a template with something similar to the following:

``` jinja2
{% for network in dhcp_subnets %}
{% if dhcp_subnets[network]['extra_config_file'] is defined %}

{% include dhcp_subnets[network]['extra_config_file'] %}
{% endif %}
{% endfor %}

```

Then setting something like the following:

```
dhcp_subnets:
  '10.2.66.0':
    bootfile_name: 'Boot\\x64\\wdsnbp.com'
    broadcast_address: '10.2.67.255'
    default_lease_time: '2592000'
    dns_servers: '10.2.66.42, 10.2.66.43'
    domain_name: 'my.company.domain'
    domain_search: '"my.company.domain"'
    extra_config_file: '../data/dhcp_subnets/10.2.66.0-pools'
    mask: '255.255.254.0'
    max_lease_time: '5184000'
    netbios_servers: 'netbios-name-servers'
    ntp_servers: 'ntp.my.company.domain'
    routers: '10.2.66.1'
    tftp_server: '10.2.66.43'
```

The task will fail with:  
`fatal: [dhcp_server]: FAILED! => {"changed": false, "failed": true, "msg": "TemplateNotFound: ../data/dhcp_subnets/10.2.66.0-pools"}`

If the `extra_config_file` value is changed to use a relative path, like `data/dhcp_subnets/...` and the `data` directory is copied to either the directory the parent template resides in, or the directory the playbook is being run from, this works. But any attempt to use an explicit path (either actually using the full explicit path, or using `../`'s to get the path) makes this fail.
##### Expected Results:

Using the `include` statement in a template should work with explicit or relative paths.
##### Actual Results:

Task fails with `TemplateNotFound` error.
##### Extra information

This is mentioned briefly by @t2d on [PR #1254](https://github.com/ansible/ansible/pull/1254)
