### ISSUE TITLE
cloudformation module fails when state:absent and stack does not exist

### ISSUE THREAD

**Issue by davidmc24** [ansible/ansible#15007]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.1.0
  config file = /Users/dcarr/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

None
##### Environment:

N/A; Mac OS X 10.10.5
##### Summary:

I have a playbook that deletes a CloudFormation stack.  If I run it when the stack is already absent, I expect it to succeed without error, noting that no changes were needed.  What I actually see is that it fails with an error message:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Stack with id STACKNAME does not exist"}
```
##### Steps To Reproduce:

```

---
- name: delete stack play
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: delete stack task
    cloudformation:
      stack_name: "STACKNAME"
      state: "absent"
      region: "us-east-1"
```
##### Expected Results:

Success with no changes
##### Actual Results:

```
$ ansible-playbook bug.yaml -vvvv
Using /Users/dcarr/.ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in bug.yaml

PLAY [delete stack play] *******************************************************

TASK [delete stack task] *******************************************************
task path: /private/var/folders/2c/qd7lcfcs5tsctw7tmvyd61v00000gn/T/bug.s12v4I2i/bug.yaml:7
ESTABLISH LOCAL CONNECTION FOR USER: dcarr
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1458161277.5-250244469102760 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1458161277.5-250244469102760 `" )'
127.0.0.1 PUT /var/folders/2c/qd7lcfcs5tsctw7tmvyd61v00000gn/T/tmp8h9eEU TO /Users/dcarr/.ansible/tmp/ansible-tmp-1458161277.5-250244469102760/cloudformation
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/dcarr/.ansible/tmp/ansible-tmp-1458161277.5-250244469102760/cloudformation; rm -rf "/Users/dcarr/.ansible/tmp/ansible-tmp-1458161277.5-250244469102760/" > /dev/null 2>&1'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "disable_rollback": false, "ec2_url": null, "notification_arns": null, "profile": null, "region": "us-east-1", "security_token": null, "stack_name": "STACKNAME", "stack_policy": null, "state": "absent", "tags": null, "template": null, "template_format": "json", "template_parameters": {}, "template_url": null, "validate_certs": true}, "module_name": "cloudformation"}, "msg": "Stack with id STACKNAME does not exist"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @bug.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by Constantin07** [comment]
@davidmc24 I faced the same problem and agree it would be better to not error in case of stack absence.
Here is the simple workaround that worked for me.

```
- name: Check if stack already exists
  command: aws cloudformation describe-stacks --stack-name "{{ stack_name }}"
  register: stack_status
  ignore_errors: yes

- name: Create stack
  cloudformation:
    ...
  when: 'Stack with id {{ stack_name }} does not exist' in stack_status.stderr)
```
