### ISSUE TITLE
--start-at-task broken sometime after 2.0.0.2

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#15010]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.0 (detached HEAD 61f05c2e8d) last updated 2016/03/16 14:59:29 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 345d9cbca8) last updated 2016/03/16 14:59:37 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD f47b499bb9) last updated 2016/03/16 14:59:37 (GMT -700)
```
##### Environment:

OSX El Capitan
##### Summary:

--start-at-task non-functional since sometime after 2.0.0.2. Currently broken in stable-2.0 and devel. 
##### Steps To Reproduce:

Run the sample playbook below with ansible-playbook playbook.yml --start-at-task "start here". All tasks in the first play will be skipped (except setup), and all tasks in subsequent plays will run (including setup). Suspect this is related to the "when do we run setup" changes w/ tags, but haven't had time to dig into it yet.

```
- hosts: localhost
  tasks:
  - name: skip me
    debug: msg="shouldn't see this"
  - name: start here
    debug: msg="should start here"
  - name: run also
    debug: msg="run me too"

- name: second play
  hosts: localhost
  tasks:
  - name: this should run
    debug: msg="first task new play"
```
##### Expected Results:

First task in first play is skipped, all others run
##### Actual Results:

All tasks in first play skipped, all others run

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

PLAY [second play] *************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [this should run] *********************************************************
ok: [localhost] => {
    "failed": false,
    "msg": "first task new play"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by vnaum** [comment]
For me adding --start-at-task="task2" causes whole playbook being skipped:

```
- hosts: all
  tasks:
    - name: task1
      local_action: command echo "qqq1"

    - name: task2
      local_action: command echo "qqq2"

    - name: task3
      local_action: command echo "qqq3"
```

```
$ ansible-playbook test.yml --start-at-task="task2"

PLAY [all] *********************************************************************

PLAY RECAP *********************************************************************
```

**Comment by nitzmahone** [comment]
@vnaum your sample only has one play though- if you add another play to the end of the playbook (like mine) you should see the same behavior (only the first play is skipped)

**Comment by tyouxa** [comment]
In my case (ansible 2.0.1.0 OS X 10.11.3)

```
---
- hosts: all
  become: yes
  remote_user: vagrant
  gather_facts: no

  tasks:
  - name: "one"
    apt_repository: repo='ppa:nginx/development'

  - name: "two"
    action: apt pkg={{ item }} state=installed
    with_items:
    - nginx-extras
    - php5
    - libapache2-mod-php5
    - libapache2-mod-rpaf
    - php5-cli
    - php5-curl
    - php5-dev
    - php5-gd
    - php-pear
    - php5-gmp
    - php5-imagick
    - php5-mcrypt
    - php5-memcache
    - php5-memcached
    - php5-mysqlnd
    - php5-xcache
    - php5-xmlrpc
    - php5-xsl
    - apache2
    - memcached
    - imagemagick
    - luarocks


  - name: "three"
    file: path=/vagrant/www state=directory

  - name: "four"
    file: path=/var/www state=absent

  - name: "five"
    file: src=/vagrant/www dest=/var/www state=link

  - name: "six"
    file: path=/etc/nginx state=absent

  - name: "seven"
    file: path=/etc/nginx state=directory

  - name: "eight"
    command: luarocks install lua-cjson

```

**ansible-playbook -i hosts front.yml --start-at-task='two' -kK**

```
SSH password:
SUDO password[defaults to SSH password]:

PLAY ***************************************************************************


PLAY RECAP *********************************************************************

```

**ansible-playbook -i hosts front.yml --start-at-task='six' -kK**

```
SSH password:
SUDO password[defaults to SSH password]:

PLAY ***************************************************************************


PLAY RECAP *********************************************************************

```

But, when start play from first task all ok

**ansible-playbook -i hosts front.yml --start-at-task='one' -kK**

```
SSH password:
SUDO password[defaults to SSH password]:

PLAY ***************************************************************************

TASK [one] *********************************************************************
ok: [192.168.111.113]

TASK [two] *********************************************************************
ok: [192.168.111.113] => (item=[u'nginx-extras', u'php5', u'libapache2-mod-php5', u'libapache2-mod-rpaf', u'php5-cli', u'php5-curl', u'php5-dev', u'php5-gd', u'php-pear', u'php5-gmp', u'php5-imagick', u'php5-mcrypt', u'php5-memcache', u'php5-memcached', u'php5-mysqlnd', u'php5-xcache', u'php5-xmlrpc', u'php5-xsl', u'apache2', u'memcached', u'imagemagick', u'luarocks'])

TASK [three] *******************************************************************
ok: [192.168.111.113]

TASK [four] ********************************************************************
changed: [192.168.111.113]

TASK [five] ********************************************************************
changed: [192.168.111.113]

TASK [six] *********************************************************************
changed: [192.168.111.113]

TASK [seven] *******************************************************************
changed: [192.168.111.113]

TASK [eight] *******************************************************************
changed: [192.168.111.113]

PLAY RECAP *********************************************************************
192.168.111.113            : ok=8    changed=5    unreachable=0    failed=0
```
