### ISSUE TITLE
Defined ansible_version variable overshadowed by main ansible_version

### ISSUE THREAD

**Issue by ahawkins** [ansible/ansible#15025]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /Users/ahawkins/slashdeploy/infrastructure/ansible.cfg
  configured module search path = Default w/o overrides
 -->
```
##### Ansible Configuration:

```
[defaults]
host_key_checking = false
```
##### Environment:

N/A
##### Summary:

I defined an `ansible_version` to indicate which version should be running on my machines. I planned to use this variable to install a specific version from PPA or PIP. I randomly considered that `ansible_version` may be a special variable. Turns out that it is! The built in `ansible_version` override my custom setting make it very confusing to debug why it could not find a version in APT.
##### Steps To Reproduce:

Define a playbook:

```
- hosts: tag_role_gitlab_runner
  vars:
    - ansible_version: "2.0.1.0-1ppa~trusty"
  tasks:
    - name: Add Ansible PPA
      apt_repository: repo='ppa:ansible/ansible' update_cache=yes

    - name: Install Ansible
      apt: name=ansible={{ ansible_version }}
```
##### Expected Results:

My defined `ansible_version` variable should be used OR I should get an error saying this variable is already used.
##### Actual Results:

The ansible version on my control machine is used instead of the one defines in the playbook. Hence the confusing message trying to look for a "full 2.0.1.0" package or version.

```
TASK [Install Ansible] *********************************************************
fatal: [52.50.75.184]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching ' 'full': '2.0.1.0'' is available"}
fatal: [52.48.58.62]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching ' 'full': '2.0.1.0'' is available"}
fatal: [52.30.191.214]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching ' 'full': '2.0.1.0'' is available"}

```
