### ISSUE TITLE
Incorrect roles variables environment

### ISSUE THREAD

**Issue by puzan** [ansible/ansible#15020]
##### Issue Type:
- Bug Report
##### Ansible Version:

ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
##### Ansible Configuration:

default
##### Environment:

N/A
##### Summary:

Default role variable is overwritten by other role declaration in `meta/main.yml` file. See `ert` variable in example. This bug was introduced in 2 version. Version 1.9.4 hasn't this issue.
##### Steps To Reproduce:

test.yml:

```

---
- name: Test
  hosts: localhost
  roles:
    - rover
```

host:

```
127.0.0.1 ansible_connection=local
```

roles/rover/meta/main.yml:

```

---
dependencies:
  - role: roter
    bar: test_bar1
    ert: test_ert1
  - role: roter
    bar: test_bar2
```

roles/roter/defaults/main.yml

```

---
bar: default_bar
ert: default_ert
```

roles/roter/tasks/main.yml:

```

---
- debug: var=bar
- debug: var=ert
```

Run ansible:

```
ansible-playbook -i host test.yml
```
##### Expected Results:

```
PLAY [Test] ********************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [roter : debug] ***********************************************************
ok: [127.0.0.1] => {
    "bar": "test_bar1"
}

TASK [roter : debug] ***********************************************************
ok: [127.0.0.1] => {
    "ert": "test_ert1"
}

TASK [roter : debug] ***********************************************************
ok: [127.0.0.1] => {
    "bar": "test_bar2"
}

TASK [roter : debug] ***********************************************************
ok: [127.0.0.1] => {
    "ert": "default_ert"
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0
```
##### Actual Results:

```
PLAY [Test] ********************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [roter : debug] ***********************************************************
ok: [127.0.0.1] => {
    "bar": "test_bar1"
}

TASK [roter : debug] ***********************************************************
ok: [127.0.0.1] => {
    "ert": "test_ert1"
}

TASK [roter : debug] ***********************************************************
ok: [127.0.0.1] => {
    "bar": "test_bar2"
}

TASK [roter : debug] ***********************************************************
ok: [127.0.0.1] => {
    "ert": "test_ert1"
}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=5    changed=0    unreachable=0    failed=0
```

**Comment by sloonz** [comment]
Duplicate of  #14017 ?

**Comment by puzan** [comment]
@sloonz Hi. Yes, I think it is the same issue.

I use following workaround for this case: set whole environment for repeated roles.

``` yaml
---
dependencies:
  - role: roter
    bar: test_bar1
    ert: test_ert1
  - role: roter
    bar: test_bar2
    ert: default_ert
```
