### ISSUE TITLE
playbook output shows yum skips task used with_items

### ISSUE THREAD

**Issue by Rthur** [ansible/ansible#15027]
**Issue Type:**
- Bug Report

**Ansible Version:**

```
ansible 2.1.0 (devel 5aef65edcd) last updated 2016/03/02 10:06:09 (GMT -500)
  lib/ansible/modules/core: (detached HEAD 09e2457eb0) last updated 2016/01/22 14:23:57 (GMT -500)
  lib/ansible/modules/extras: (detached HEAD e8427cb32a) last updated 2016/01/22 14:23:59 (GMT -500)
  config file = 
  configured module search path = Default w/o overrides
```

**Ansible Configuration:**
Default

**Environment:**
N/A

**Summary:**

If yum is invoked using with_items, yum successfully evaluates the package but the output of the play shows it has been skipped.

**Steps To Reproduce:**

```
pkgs:
  - '*'

- name: update installed packages
  yum:
    name: '{{ item }}'
    state: latest
  with_items:
    - '{{ pkgs }}'

```

**Expected Results:**

Output should return ok or changed. In my test environment, I have used '*' or lists of individual packages where an update would occur.

**Actual Results:**

```
TASK [yum_update : update installed packages] **********************************
skipping: [vm04] => (item=[u'*'])
```
