### ISSUE TITLE
Docker module not pulling containers in Swarm

### ISSUE THREAD

**Issue by pgporada** [ansible/ansible#15039]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.0.2
```
##### Ansible Configuration:

```
[defaults]
inventory=hosts
host_key_checking=false
nocows=1
fact_caching=jsonfile
fact_caching_connection=facts/
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d by {uid} on {host}
scp_if_ssh=true
timeout=20

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s
```
##### Environment:

Ubuntu 15.10 trying to run commands against Centos7 vagrants
##### Summary:

I am trying to start, initially one, microservice in a Docker Swarm environment. To do this, I am using the docker module. The docker module does not pull containers for me. It tells me that the containers do not exist. I've successfully logged into my private docker hub via Swarm and have successfully pulled other private containers down via the CLI.
##### Steps To Reproduce:

Playbook

```

---
- hosts: swarm-manager
  gather_facts: smart
  become: true
  become_method: sudo
  remote_user: "{{ user }}"
  vars_files:
    - ../group_vars/all.yml
  roles:
    - ../roles/user-microservice
```

Role

```
- name: Run the user microservice
  docker:
    image: "greenlancer/user:testing"
    state: reloaded
    pull: always
    count: 1
    detach: true
    docker_url: "tcp://{{ansible_hostname}}:3376"
    use_tls: verify
    tls_ca_cert: /etc/docker/ssl/ca.pem
    tls_client_cert: /etc/docker/ssl/cert.pem
    tls_client_key: /etc/docker/ssl/key.pem
    env:
      CONSUL_LOCATION: "http://10.100.199.201:8500"
```
##### Expected Results:

I expect the docker module to download my container on whichever host that the swarm manager decides the container should start on.
##### Actual Results:

```
TASK [../roles/user-microservice : Run the user microservice] ******************
task path: /opt/work-repos/phils-docker-swarm-vagrant-demo/ansible/roles/user-microservice/tasks/main.yml:2
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'IdentityFile="../.vagrant/machines/swarm-node01/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=20 -o ControlPath=/home/phil/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 '( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1458326240.98-22508746477511 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1458326240.98-22508746477511 )" )'
<127.0.0.1> PUT /tmp/tmpUnP_QP TO /home/vagrant/.ansible/tmp/ansible-tmp-1458326240.98-22508746477511/docker
<127.0.0.1> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'IdentityFile="../.vagrant/machines/swarm-node01/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=20 -o ControlPath=/home/phil/.ansible/cp/ansible-ssh-%h-%p-%r '[127.0.0.1]'
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2201 -o 'IdentityFile="../.vagrant/machines/swarm-node01/virtualbox/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=20 -o ControlPath=/home/phil/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-flhtqqgqjaounpaoyuwdguzizotqraol; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1458326240.98-22508746477511/docker; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1458326240.98-22508746477511/" > /dev/null 2>&1'"'"'"'"'"'"'"'"''"'"''
fatal: [swarm-node01]: FAILED! => {"changed": false, "changes": ["{\"id\":\"swarm-node02\",\"status\":\"Pulling greenlancer/user:testing...\",\"progressDetail\":{}}\n", "{\"id\":\"swarm-node03\",\"status\":\"Pulling greenlancer/user:testing...\",\"progressDetail\":{}}\n", "{\"id\":\"swarm-node03\",\"status\":\"Pulling greenlancer/user:testing... : Error: image greenlancer/user not found\",\"progressDetail\":{}}\n", "{\"id\":\"swarm-node02\",\"status\":\"Pulling greenlancer/user:testing... : Error: image greenlancer/user not found\",\"progressDetail\":{}}\n", "{\"error\":\"Error: image greenlancer/user not found\",\"errorDetail\":{\"code\":1,\"message\":\"Error: image greenlancer/user not found\"}}\n"], "failed": true, "invocation": {"module_args": {"cap_add": null, "cap_drop": null, "command": null, "count": 1, "cpu_set": null, "debug": false, "detach": true, "dns": null, "docker_api_version": "1.21", "docker_url": "tcp://swarm-node01:3376", "docker_user": null, "domainname": null, "email": null, "env": {"CONSUL_LOCATION": "http://10.100.199.201:8500"}, "expose": null, "extra_hosts": null, "hostname": null, "image": "greenlancer/user:testing", "insecure_registry": false, "links": null, "log_driver": null, "log_opt": null, "lxc_conf": null, "memory_limit": 0, "memory_swap": 0, "name": null, "net": null, "password": null, "pid": null, "ports": null, "privileged": false, "publish_all_ports": false, "pull": "always", "read_only": null, "registry": null, "restart_policy": null, "restart_policy_retry": 0, "signal": null, "state": "reloaded", "stdin_open": false, "stop_timeout": 10, "tls_ca_cert": "/etc/docker/ssl/ca.pem", "tls_client_cert": "/etc/docker/ssl/cert.pem", "tls_client_key": "/etc/docker/ssl/key.pem", "tls_hostname": null, "tty": false, "use_tls": "verify", "username": null, "volumes": null, "volumes_from": null}, "module_name": "docker"}, "msg": "Unrecognized status from pull.", "status": ""}
...ignoring

TASK [../roles/user-microservice : Debug Output] *******************************
task path: /opt/work-repos/phils-docker-swarm-vagrant-demo/ansible/roles/user-microservice/tasks/main.yml:20
ok: [swarm-node01] => {
    "msg": {
        "changed": false, 
        "changes": [
            "{\"id\":\"swarm-node02\",\"status\":\"Pulling greenlancer/user:testing...\",\"progressDetail\":{}}\n", 
            "{\"id\":\"swarm-node03\",\"status\":\"Pulling greenlancer/user:testing...\",\"progressDetail\":{}}\n", 
            "{\"id\":\"swarm-node03\",\"status\":\"Pulling greenlancer/user:testing... : Error: image greenlancer/user not found\",\"progressDetail\":{}}\n", 
            "{\"id\":\"swarm-node02\",\"status\":\"Pulling greenlancer/user:testing... : Error: image greenlancer/user not found\",\"progressDetail\":{}}\n", 
            "{\"error\":\"Error: image greenlancer/user not found\",\"errorDetail\":{\"code\":1,\"message\":\"Error: image greenlancer/user not found\"}}\n"
        ], 
        "failed": true, 
        "msg": "Unrecognized status from pull.", 
        "status": ""
    }
}
```

**Comment by pgporada** [comment]
I CAN get to work by having a shell task that pulls the containers for me first.

```
---
- name: Pull container
  shell: "docker --tlsverify --tlscacert=/etc/docker/ssl/ca.pem --tlscert=/etc/docker/ssl/cert.pem --tlskey=/etc/docker/ssl/key.pem -H swarm-node01:3376 pull greenlancer/user:testing"

- name: Run the user microservice
  docker:
    image: "greenlancer/user:testing"
    state: started
    count: 1
    detach: true
    docker_url: "tcp://{{ansible_hostname}}:3376"
    use_tls: verify
    tls_ca_cert: /etc/docker/ssl/ca.pem
    tls_client_cert: /etc/docker/ssl/cert.pem
    tls_client_key: /etc/docker/ssl/key.pem
    env:
      CONSUL_LOCATION: "http://10.100.199.201:8500"
```

```
PLAY ***************************************************************************

TASK [../roles/user-microservice : Pull container] *****************************
changed: [swarm-node01]

TASK [../roles/user-microservice : Run the user microservice] ******************
changed: [swarm-node01]

PLAY RECAP *********************************************************************
swarm-node01               : ok=2    changed=2    unreachable=0    failed=0  
```

I think this is related to https://github.com/ansible/ansible-modules-core/pull/3035
