### ISSUE TITLE
ansible and route53 module health_check failed

### ISSUE THREAD

**Issue by pawel-yesware** [ansible/ansible#15041]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Environment:

running on osx
##### Summary:

I'm following this example below: 
http://docs.ansible.com/ansible/route53_health_check_module.html#examples

but it fails with error

```
TASK [ROUTE53 | Create record] *************************************************
task path: /Users/pkilian/yesware/RAW/ansible/redis-cluster.yml:63
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'health_check'"}
```
##### Steps To Reproduce:

```
      - name: ROUTE53 | Create health check
        route53_health_check:
          state: present
          type: TCP
          ip_address: "{{ item.public_ip }}"
          port: 6378
          request_interval: 10
        with_items: 
          eip.results
        register: my_health_check

      - name: ROUTE53 | Create record 
        route53:
          action: create
          zone: "testing.domain.com"
          type: A
          record: pawel.testing.domain.com
          value: "{{ item.public_ip }}"
          ttl: 30
          # routing policy
          failover: yes
          identifier: " {{ ec2_master_server_name }}"
          health_check: "{{ my_health_check.health_check.id }}"
        with_items:
          - eip.results
```
##### Expected Results:

It should run just fine
##### Actual Results:

```
TASK [ROUTE53 | Create health check] *******************************************
[local]
task path: /Users/pkilian/yesware/RAW/ansible/redis-cluster.yml:52
ESTABLISH LOCAL CONNECTION FOR USER: pkilian
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1458323309.66-228676789658388 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1458323309.66-228676789658388 `" )'
localhost PUT /var/folders/b9/qzy719cx7r521llb5bylssx00000gp/T/tmpPCpbez TO /Users/pkilian/.ansible/tmp/ansible-tmp-1458323309.66-228676789658388/route53_health_check
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/pkilian/.ansible/tmp/ansible-tmp-1458323309.66-228676789658388/route53_health_check; rm -rf "/Users/pkilian/.ansible/tmp/ansible-tmp-1458323309.66-228676789658388/" > /dev/null 2>&1'
changed: [localhost] => (item={'invocation': {'module_name': u'ec2_eip', u'module_args': {u'release_on_disassociation': False, u'profile': None, u'aws_access_key': None, u'security_token': None, u'reuse_existing_ip_allowed': True, u'region': u'us-east-1', u'aws_secret_key': None, u'public_ip': None, u'state': u'present', u'in_vpc': True, u'ec2_url': None, u'validate_certs': True, u'wait_timeout': 300, u'device_id': u'i-40f9bcc3'}}, u'public_ip': u'52.200.48.78', u'changed': True, '_ansible_no_log': False, 'item': {u'kernel': None, u'root_device_type': u'ebs', u'private_dns_name': u'ip-10-0-0-27.ec2.internal', u'public_ip': u'54.173.173.105', u'private_ip': u'10.0.0.27', u'id': u'i-40f9bcc3', u'ebs_optimized': False, u'state': u'running', u'virtualization_type': u'hvm', u'architecture': u'x86_64', u'ramdisk': None, u'block_device_mapping': {u'/dev/sda1': {u'status': u'attached', u'delete_on_termination': True, u'volume_id': u'vol-bf75e761'}}, u'key_name': u'pawel-ec2', u'image_id': u'ami-fce3c696', u'tenancy': u'default', u'groups': {u'sg-dff74dba': u'v_ssh'}, u'public_dns_name': u'ec2-54-173-173-105.compute-1.amazonaws.com', u'state_code': 16, u'tags': {u'Group': u'redis', u'Name': u'p-pablo-redis1'}, u'placement': u'us-east-1b', u'ami_launch_index': u'0', u'dns_name': u'ec2-54-173-173-105.compute-1.amazonaws.com', u'region': u'us-east-1', u'launch_time': u'2016-03-18T17:46:55.000Z', u'instance_type': u't2.nano', u'root_device_name': u'/dev/sda1', u'hypervisor': u'xen'}}) => {"action": "create", "changed": true, "health_check": {"id": "30efd420-bf6d-4be8-ac31-4b1b370afa2c"}, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "ec2_url": null, "failure_threshold": 3, "fqdn": null, "ip_address": "52.200.48.78", "port": 6378, "profile": null, "region": null, "request_interval": 10, "resource_path": null, "security_token": null, "state": "present", "string_match": null, "type": "TCP", "validate_certs": true}, "module_name": "route53_health_check"}, "item": {"_ansible_no_log": false, "changed": true, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "device_id": "i-40f9bcc3", "ec2_url": null, "in_vpc": true, "profile": null, "public_ip": null, "region": "us-east-1", "release_on_disassociation": false, "reuse_existing_ip_allowed": true, "security_token": null, "state": "present", "validate_certs": true, "wait_timeout": 300}, "module_name": "ec2_eip"}, "item": {"ami_launch_index": "0", "architecture": "x86_64", "block_device_mapping": {"/dev/sda1": {"delete_on_termination": true, "status": "attached", "volume_id": "vol-bf75e761"}}, "dns_name": "ec2-54-173-173-105.compute-1.amazonaws.com", "ebs_optimized": false, "groups": {"sg-dff74dba": "v_ssh"}, "hypervisor": "xen", "id": "i-40f9bcc3", "image_id": "ami-fce3c696", "instance_type": "t2.nano", "kernel": null, "key_name": "pawel-ec2", "launch_time": "2016-03-18T17:46:55.000Z", "placement": "us-east-1b", "private_dns_name": "ip-10-0-0-27.ec2.internal", "private_ip": "10.0.0.27", "public_dns_name": "ec2-54-173-173-105.compute-1.amazonaws.com", "public_ip": "54.173.173.105", "ramdisk": null, "region": "us-east-1", "root_device_name": "/dev/sda1", "root_device_type": "ebs", "state": "running", "state_code": 16, "tags": {"Group": "redis", "Name": "p-pablo-redis1"}, "tenancy": "default", "virtualization_type": "hvm"}, "public_ip": "52.200.48.78"}}

TASK [ROUTE53 | Create record] *************************************************
task path: /Users/pkilian/yesware/RAW/ansible/redis-cluster.yml:63
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'health_check'"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @redis-cluster.retry

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=1
```
