### ISSUE TITLE
Add backup field to template return values

### ISSUE THREAD

**Issue by Javex** [ansible/ansible#15047]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Environment:

N/A
##### Summary:

Return `backup` key for template module.
##### Steps To Reproduce:

Run a task like this:

```
      template:
        src: provision_files/sudoers.tmpl
        dest: /etc/sudoers.d/ansible
        mode: 0440
        backup: yes
    register: sudoers
```
##### Expected Results:

```
    "sudoers": {
        "changed": false, 
        "gid": 0, 
        "group": "root", 
        "mode": "0440", 
        "owner": "root", 
        "path": "/etc/sudoers.d/ansible", 
        "size": 35, 
        "state": "file", 
        "uid": 0,
       "backup": "/etc/sudoers.d/ansible.2016-03-19@04:36:50~"
    }
```
##### Actual Results:

```
    "sudoers": {
        "changed": false, 
        "gid": 0, 
        "group": "root", 
        "mode": "0440", 
        "owner": "root", 
        "path": "/etc/sudoers.d/ansible", 
        "size": 35, 
        "state": "file", 
        "uid": 0
    }
```
