### ISSUE TITLE
BUG: Amazon ec2 instance is always created, unless instance_id is set

### ISSUE THREAD

**Issue by apolloclark** [ansible/ansible#15082]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.0.1.0
```
##### Environment:

Ubuntu 15.10 Wily Werewolf
##### Summary:

Using the AWS ec2 config "state: present", will always create a new instance, unless "instance_id" is set. Instances should ONLY be created when an instance cannot be found with identical settings.
##### Steps To Reproduce:

```
- name: Ensure  EC2 Instance exists
  ec2:
    key_name: KeyPair
    region: "{{aws_region}}"
    image: "{{ami_id}}"
    group_id: "{{security_group_id}}"
    instance_type: "{{instance_type}}"
    instance_tags: '{"Name":"InstanceName","DeploymentType":"Production","ServerType":"Infrastructure"}'
    monitoring: yes
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    wait: yes
    state: present
```
##### Expected Results:

When I run this script twice, no new EC2 instance should be created.
##### Actual Results:

A new EC2 instance is created.
