### ISSUE TITLE
ansible_distribution fact does not work for CoreOS

### ISSUE THREAD

**Issue by danehans** [ansible/ansible#15096]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
# ansible --version
ansible 1.9.4
  configured module search path = None
```
##### Ansible Configuration:

No changes to default settings.
##### Environment:

OS Running Ansible:

```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

OS Being Managed:

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=983.0.0
VERSION_ID=983.0.0
BUILD_ID=2016-03-10-0808
PRETTY_NAME="CoreOS 983.0.0 (Coeur Rouge)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
##### Summary:

The ansible_distribution fact does not work for CoreOS:

https://gist.github.com/danehans/dc7081b4ac5dfe857cfe#file-coreos_ansible_facts-L99-L102

Even with the development branch, the distribution does not return 'coreos':

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py#L519

Ansible should be checking /etc/os-release to create the ansible_distribution facts:

```
$ cat /etc/os-release
NAME=CoreOS
ID=coreos
VERSION=983.0.0
VERSION_ID=983.0.0
BUILD_ID=2016-03-10-0808
PRETTY_NAME="CoreOS 983.0.0 (Coeur Rouge)"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```
##### Steps To Reproduce:

Install CoreOS on a server/vm that will be managed by Ansible. Make sure to add the SSH public key of the Ansible controller to the CoreOS server/vm. The following examples are bases on this Ansible project:

https://github.com/kubernetes/contrib/tree/master/ansible

Add a CoreOS machine/vm to your Ansible inventory:

```
# cat inventory

[masters]
core-master
```

Here is my playbook (but any simple playbook will due):

```
# cat cluster.yml 

---
# This playbook deploys a kubernetes cluster 
# with the default addons.

- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - pre-ansible
  tags:
    - pre-ansible

# Install etcd
- hosts: etcd
  sudo: yes
  roles:
    - etcd
  tags:
    - etcd

- hosts: all
  sudo: yes
  roles:
    - common
    - docker
  tags:
    - docker

# install flannel
- hosts:
    - etcd
    - masters
    - nodes
  sudo: yes
  roles:
    - { role: flannel, when: networking == 'flannel' }
  tags:
    - network-service-install

# install opencontrail
- hosts: all
  sudo: yes
  roles:
    - { role: opencontrail, when: networking == 'opencontrail'}
  tags:
    - network-service-install

# install kube master services
- hosts: masters
  sudo: yes
  roles:
    - master
  tags:
    - masters

# launch addons, like dns
- hosts: masters
  sudo: yes
  roles:
    - kubernetes-addons
  tags:
    - addons
    - dns

# install kubernetes on the nodes
- hosts: nodes
  sudo: yes
  roles:
    - node
  tags:
    - nodes

# provision opencontrail once the services are operational
- hosts:
    - masters[0]
    - nodes
  sudo: yes
  roles:
    - { role: opencontrail-provision, when: networking == 'opencontrail' }
  tags:
    - network-service-config
```

Run the following command on your Ansible controller:

```
# ansible -i inventory all -m setup | grep distr
        "ansible_distribution": "NA", 
        "ansible_distribution_major_version": "NA", 
        "ansible_distribution_release": "NA", 
        "ansible_distribution_version": "NA", 
```
##### Expected Results:

```
# ansible -i inventory all -m setup | grep distr
        "ansible_distribution": "CoreOS", 
        "ansible_distribution_major_version": "983.0.0", 
        "ansible_distribution_release": "983.0.0", 
        "ansible_distribution_version": "983.0.0", 
```
##### Actual Results:

```
# ansible -i inventory all -m setup | grep distr
        "ansible_distribution": "NA", 
        "ansible_distribution_major_version": "NA", 
        "ansible_distribution_release": "NA", 
        "ansible_distribution_version": "NA", 
```
