### ISSUE TITLE
parsing yaml for arguments incomplete

### ISSUE THREAD

**Issue by chasrmartin** [ansible/ansible#15098]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
$ ansible --version
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### Environment:

Mac OS/X targeting a Vagrant ubuntu/trusty64 box.
##### Summary:

Building a custom module in ruby. The varaibles file created for a slightly complicated YAML isn't as expected.
##### Steps To Reproduce:

```
    - name: try a module
      test:
        path: /path/to/file.ini
        a: value
        b: yes
        c: 42
        array:
          - 0
          - 1
          - 2
          - deep:
              d1: a
              d2: b
```

##### Expected Results:

Resulting variables file:

```
a="value" path="/path/to/file.ini" c="42" b="True" array="'[0, 1, 2, {u'"'"'d2'"'"': u'"'"'b'"'"', u'"'"'deep'"'"': None, u'"'"'d1'"'"': u'"'"'a'"'"'}]'" 
```

##### Actual Results:

Expect array to correspond to:

```
{ array: [0, 1, 2, {deep: {d1: a, d2: b}}]}

<!--- What actually happened? If possible run with high verbosity (-vvvv) -->

```

```
```
