### ISSUE TITLE
1.9.5: cannot use "name" as a role parameter anymore

### ISSUE THREAD

**Issue by cthiemann** [ansible/ansible#15104]
1.9.5 introduced a regression where "name" is now overriding the value of "role" when including roles with parameters:

```

---
- hosts: localhost
  roles:
    - role: test
      name: foobar
```

```
ERROR: cannot find role in /home/[...]/roles/foobar or [...]
```

`git bisect` tells me that it was introduced by commit a05df83 "Merge pull request #14565 from dagwieers/fix-role_params-merge_hash"
