### ISSUE TITLE
allow iam group assignment without wiping out all other groups

### ISSUE THREAD

**Issue by jxn** [ansible/ansible#15109]
##### Issue Type:
- Feature Idea
##### Ansible Version:

```
2.0.1.0
```
##### Ansible Configuration:

NA
##### Environment:

NA
##### Summary:

It's currently impossible to assign an IAM group to a user without wiping out all other groups.  The only way to assign groups is in an iam module task:

```
- iam: iam_type=user name=user_name state=present groups="{{ iam_groups }}"
```

However, this always wipes existing groups, losing data for existing users if you don't already know all of the groups assigned to the user.  Other modules with group assignments use another parameter to allow appending to lists (e.g. mysql_user has "append_privs" and ec2_group has "purge_rules")
##### Steps To Reproduce:

```
vars:
   groups1:
     - groups1_example
   groups2:
     - groups2_example
tasks:
  - iam: iam_type=user name=user_name state=present groups="{{ groups1 }}"
  - iam: iam_type=user name=user_name state=present groups="{{ groups2 }}"
```

user will only have groups2_example group assigned.
##### Expected Results:

user would belong to both groups1_example and groups2_example
##### Actual Results:

user will only have groups2_example group assigned.
