### ISSUE TITLE
Setup module never runs when using variables external roles paths in a playbook

### ISSUE THREAD

**Issue by guhcampos** [ansible/ansible#15128]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /Users/gustavo/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Happens on Mac (10.11) and Linux (RHEL7.1)
##### SUMMARY

If any variable is used while referencing a role, both in a playbook or in a `roles/someroles/meta/main.yml`, an error: `ERROR! 'ansible_env' is undefined` is shown before anything else.
##### STEPS TO REPRODUCE
1. Create a new playbook
2. Create a variable, any variable
3. Reference a role which path uses that variable, like:

``` roles:
  - { role: "/home/{{ somevar }}/roles/somerole" }}
```

A simplified playbook:

```
#!/usr/bin/env ansible-playbook

---

- hosts: localhost

  vars:
    external_roles: ".local/somerolespath"

  roles:
    - { role: "{{ ansible_env.HOME }}/{{ external_roles }}/somerole" }
```

Real life example:
https://gist.github.com/guhcampos/50e46c7d9b6e0f93635e
##### EXPECTED RESULTS

Ansible should run normally
##### ACTUAL RESULTS

ansible-playbook crashes before running anything else, with `ERROR! 'ansible_env' is undefined`. This happens so early in Ansible's bootstrap that it happens before the usual `[WARNING]: provided hosts list is empty, only localhost is available` which normally show for running a playbook without an inventory.

``````
[gustavo@somehost ansible]$ap gustavo.yml
ERROR! 'ansible_env' is undefined```
``````
