### ISSUE TITLE
Unable to remove requiretty from /etc/sudoers on clean Debian machines

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#15127]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
2.4.2

##### SUMMARY

I was trying to take control of a brand new Debian 8.3 machine (AWS, Debian official AMI) via ansible. The default user is `admin`, the ssh key is present but it seems that is impossible to get root access on this machine without manual intervention which really sucks as is against automation and auto-provisioning.

```yaml
- hosts: neon
  tasks:
    - name: Remove require tty
      lineinfile: regexp="^\s+\w+\s+requiretty" dest=/etc/sudoers state=absent
      become_method: sudo
      become_user: root
      become: yes
```

I tried all become methods, no luck.

```
IOError: [Errno 13] Permission denied: '/etc/sudoers`
```

**Comment by dagwieers** [comment]
Just a long shot, is it possible that _/etc/sudoers_ is immutable to force people to use visudo ?
Can you check with `lsattr` to see if this is the case ?

**Comment by ansibot** [comment]
@ssbarnea Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibotdev** [comment]
@ssbarnea You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ssbarnea** [comment]
```
lsattr /etc/sudoers
-------------e-- /etc/sudoers
```

**Comment by ansibot** [comment]
cc @ahtik @dhozac
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
I am unable to duplicate this issue using a Debian 8 AMI `debian-jessie-amd64-hvm-2017-01-15-1221-ebs-39d3917e-ff4e-4597-848e-4d0fdf8529e6-ami-b14ba7a7.4 (ami-cb4b94dd)` with Ansible 2.4.2.0 or `devel`.

```
> ansible --version
ansible 2.4.2.0 (detached HEAD e3a8bf02ac) last updated 2018/06/18 15:24:58 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = ['/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 3.6.4 (default, Mar 19 2018, 12:20:18) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

```
> ansible-config dump --only-changed
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/Users/sdoran/Source/ansible/library']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/sdoran/bin/getvaultkey.sh
```

I had to modify the regexp slightly to get it to match. I also had to add the line to `/etc/sudoers` as it was not present on a newly created instance.

```yaml
- hosts: "{{ target_hosts | default('lab-centos7') }}"
  tasks:
    - name: Remove require tty
      lineinfile: regexp="(\s+)?\w+\s+requiretty" dest=/etc/sudoers state=absent
      become_method: sudo
      become_user: root
      become: yes
```

```
> ansible-playbook test.yml -e target_hosts=54.198.132.44 -i inventory/hosts.yml -v
No config file found; using defaults

PLAY [54.198.132.44] *******************************************************************************

TASK [Gathering Facts] *****************************************************************************
ok: [54.198.132.44]

TASK [Remove require tty] **************************************************************************
changed: [54.198.132.44] => {"backup": "", "changed": true, "found": 1, "msg": "1 line(s) removed"}

PLAY RECAP *****************************************************************************************
54.198.132.44              : ok=2    changed=1    unreachable=0    failed=0
```

needs_info
