### ISSUE TITLE
Openstack inventory script returns nothing for RDO Kilo

### ISSUE THREAD

**Issue by indispeq** [ansible/ansible#15148]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
openstack dynamic inventory script

##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No settings changed
##### OS / ENVIRONMENT

Ubuntu Desktop 14.04, ansible in virtualenv, installed via pip.
##### SUMMARY

The latest `openstack.py` inventory script (as per the link in the dynamic inventory section of the docs) returns no inventory data when run against a deployment of openstack RDO Kilo. The same exact query against an RPC Juno or an RDO Juno deployment returns all the inventory data. This happens when using the `openstack.yml` file or without it.
`nova list` returns a list of servers, there is no authentication problem there.
##### STEPS TO REPRODUCE
- `source openrc`
- `/etc/ansible/hosts --list`
##### EXPECTED RESULTS

A full JSON inventory.
##### ACTUAL RESULTS

Minimal empty output.

```
(ansible) indispeq@indispeq:~/$ /etc/ansible/hosts --list --refresh       
{
  "_meta": {
    "hostvars": {}
  }
}
```

**Comment by jimi-c** [comment]
@emonty / @Shrews any ideas here?

**Comment by emonty** [comment]
It's almost certainly an inability to figure out the interface_ip .Could you run:

shade-inventory --yaml --debug --list

and paste the results?

**Comment by indispeq** [comment]
Thank you, here is the stderr output:

```
Manager envvars:RegionOne running task ServerList
Manager envvars:RegionOne ran task ServerList in 0.284734010696s
Manager envvars:RegionOne running task NetworkList
Manager envvars:RegionOne ran task NetworkList in 0.0261981487274s
Manager envvars:RegionOne running task NetworkList
Manager envvars:RegionOne ran task NetworkList in 0.0202968120575s
Manager envvars:RegionOne running task FlavorList
Manager envvars:RegionOne ran task FlavorList in 0.0244171619415s
Manager envvars:RegionOne running task FlavorGetExtraSpecs
Manager envvars:RegionOne ran task FlavorGetExtraSpecs in 0.0207390785217s
Manager envvars:RegionOne running task FlavorGetExtraSpecs
Manager envvars:RegionOne ran task FlavorGetExtraSpecs in 0.0195989608765s
Manager envvars:RegionOne running task FlavorGetExtraSpecs
Manager envvars:RegionOne ran task FlavorGetExtraSpecs in 0.0190711021423s
Manager envvars:RegionOne running task FlavorGetExtraSpecs
Manager envvars:RegionOne ran task FlavorGetExtraSpecs in 0.0177760124207s
Manager envvars:RegionOne running task FlavorGetExtraSpecs
Manager envvars:RegionOne ran task FlavorGetExtraSpecs in 0.0173301696777s
Manager envvars:RegionOne running task FlavorGetExtraSpecs
Manager envvars:RegionOne ran task FlavorGetExtraSpecs in 0.0212080478668s
Manager envvars:RegionOne running task ServerListSecurityGroups
Manager envvars:RegionOne ran task ServerListSecurityGroups in 0.119898080826s
Manager envvars:RegionOne running task GlanceImageList
Manager envvars:RegionOne ran task GlanceImageList in 0.204379796982s
Manager envvars:RegionOne running task VolumeList
Manager envvars:RegionOne ran task VolumeList in 0.108084917068s
```

and what is more important (redacted in parts):

```
- HUMAN_ID: true
  NAME_ATTR: name
  OS-DCF:diskConfig: MANUAL
  OS-EXT-AZ:availability_zone: nova
  OS-EXT-STS:power_state: 1
  OS-EXT-STS:task_state: null
  OS-EXT-STS:vm_state: active
  OS-SRV-USG:launched_at: '2016-03-24T19:24:11.000000'
  OS-SRV-USG:terminated_at: null
  accessIPv4: ''
  accessIPv6: ''
  addresses:
    xxxxxxxxxx_NETWORK:
    - OS-EXT-IPS-MAC:mac_addr: xx:xx:xx:xx:xx:xx
      OS-EXT-IPS:type: fixed
      addr: xx.xx.xx.xx
      version: 4
  az: nova
  cloud: envvars
  config_drive: ''
  created: '2016-03-24T19:23:59Z'
  flavor:
    id: '3'
    name: m1.medium
  hostId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  human_id: test
  id: 15218bc8-8c92-4d4d-89df-4183721fc9e8
  image:
    id: 26910a75-9a7a-407f-ad69-036b71d76301
    name: trusty
  key_name: xxxxxxxxxxx
  metadata:
    ansible_host_groups: admin_v_infrastructure,apt_repos
    ansible_host_vars: dns_server_for_domains->v.clusterb.centerdevice.local,infrastructure.v.clusterb.centerdevice.local
  name: test
  networks:
    xxxxxx_NETWORK:
    - xx.xx.xx.xx
  os-extended-volumes:volumes_attached: []
  private_v4: xx.xx.xx.xx
  progress: 0
  public_v4: ''
  public_v6: ''
  region: RegionOne
  request_ids: &id001 []
  security_groups:
  - description: Default security group
    id: 591c15c8-c43c-4d97-92a3-842479db2793
    name: default
    security_group_rules:
    - direction: ingress
      ethertype: IPv4
      id: 6a46c65a-7b17-48c8-94e0-3de93a9b5639
      port_range_max: null
      port_range_min: null
      protocol: null
      remote_ip_prefix: null
      security_group_id: 591c15c8-c43c-4d97-92a3-842479db2793
    - direction: ingress
      ethertype: IPv4
      id: c8b924e8-9bab-484d-b99b-08b425fdfd50
      port_range_max: null
      port_range_min: null
      protocol: null
      remote_ip_prefix: null
      security_group_id: 591c15c8-c43c-4d97-92a3-842479db2793
  status: ACTIVE
  tenant_id: xxxxxxxxxxxxxxxxxxx
  updated: '2016-03-24T21:10:16Z'
  user_id: xxxxxxxxxxxxxxxxxxxx
  volumes: []
  x_openstack_request_ids: *id001
```

This is for my one test VM that I added some meta-data to (based on another on-line article by Lukas Pustina, that uses another inventory script. Let me know what else you'd need.

**Comment by emonty** [comment]
Awesome. Thanks! Yes, it's as I thought, openstack inventory cannot figure out which IP to use. (just picking the value from the one network that's there has other issues) HOWEVER - try adding external_network: xxxxxxxxxx_NETWORK to your clouds.yaml / openstack.yml like this:

```
clouds:
  internap:
    profile: internap
    auth:
      password: XXXXXXXXX
      username: api-55f9a00fb2619
      project_name: inap-17037
    external_network: inap-17037-WAN1654
```

(which is a redacted snipped from my clouds.yaml - turns out internap public cloud also is configured in such a way that you have to specify which network to use)

I should probably add some docs on this

**Comment by indispeq** [comment]
Hi @emonty , adding `external_network` to my `openstack.yml` did not help. Here are the contents (i also tried adding password, username, project_name, besides the fact that they are in the sourced env vars, but no dice, same output.

```
clouds:
  indispeq:
    external_network: XXXXXXX_NETWORK
ansible:
  use_hostnames: True
  expand_hostvars: False
```

If this helps, my neutron net-list output is this (XXXX_NETWORK is the internal network, and INTERNET is the one that has the floating IPs and is in fact the external network. I tried both of these in the `external_network` field.

```
+--------------------------------------+------------------+-----------------------------------------------------+
| id                                   | name             | subnets                                             |
+--------------------------------------+------------------+-----------------------------------------------------+
| 113189bc-5e74-4ce8-986e-59547603e173 | XXXXXXXX_NETWORK | adeea3c4-4a33-4550-be53-b18b34057c5f x.x.x.0/24   |
| 4835f38b-8693-43a1-8c57-50b065d0222c | INTERNET         | eb3023d4-ceb2-4036-9c4c-11eb792e7f75 xx.xx.xx.xx/xx |
+--------------------------------------+------------------+-----------------------------------------------------+
```

I tried adding the `profile: internap` part, but no luck.

**Comment by emonty** [comment]
Ah - ok. there are two issues here where I can make the inventory better. However, until I fix those - try one more time with the user/pass/auth_url/project_name in the auth dict. (no need for profile internap - that just tells it to use default values from the internap vendor) ... BUT ... then unset the OS_ env vars from your environment.

Before you do that, try running

/etc/ansible/hosts --list --private

If both of those work, then I know which things I should fix.

**Comment by indispeq** [comment]
The output of `--list --private` gives me all the info, awesome:

```
{
  "RegionOne": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "RegionOne_nova": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "_meta": {
    "hostvars": {
      "15218bc8-8c92-4d4d-89df-4183721fc9e8": {
        "ansible_ssh_host": "xx.xx.xx.xx", 
        "openstack": {
          "HUMAN_ID": true, 
          "NAME_ATTR": "name", 
          "OS-DCF:diskConfig": "MANUAL", 
          "OS-EXT-AZ:availability_zone": "nova", 
          "OS-EXT-STS:power_state": 1, 
          "OS-EXT-STS:task_state": null, 
          "OS-EXT-STS:vm_state": "active", 
          "OS-SRV-USG:launched_at": "2016-03-24T19:24:11.000000", 
          "OS-SRV-USG:terminated_at": null, 
          "accessIPv4": "xx.xx.xx.xx", 
          "accessIPv6": "", 
          "addresses": {
            "INDISPEQ_NETWORK": [
              {
                "OS-EXT-IPS-MAC:mac_addr": "fa:16:3e:6c:b9:59", 
                "OS-EXT-IPS:type": "fixed", 
                "addr": "xx.xx.xx.xx", 
                "version": 4
              }
            ]
          }, 
          "az": "nova", 
          "cloud": "envvars", 
          "config_drive": "", 
          "created": "2016-03-24T19:23:59Z", 
          "flavor": {
            "id": "3", 
            "name": "m1.medium"
          }, 
          "hostId": "e95a6d83c1057c7a3839862ba91ba06dd9e1a942df348119a02fa088", 
          "human_id": "test", 
          "id": "15218bc8-8c92-4d4d-89df-4183721fc9e8", 
          "image": {
            "id": "26910a75-9a7a-407f-ad69-036b71d76301", 
            "name": "trusty"
          }, 
          "interface_ip": "xx.xx.xx.xx", 
          "key_name": "xxxxxxx", 
          "metadata": {
            "ansible_host_groups": "admin_v_infrastructure,apt_repos", 
            "ansible_host_vars": "dns_server_for_domains->v.clusterb.centerdevice.local,infrastructure.v.clusterb.centerdevice.local"
          }, 
          "name": "test", 
          "networks": {
            "xxxxxxxxx_NETWORK": [
              "xx.xx.xx.xx"
            ]
          }, 
          "os-extended-volumes:volumes_attached": [], 
          "private_v4": "xx.xx.xx.xx", 
          "progress": 0, 
          "public_v4": "", 
          "public_v6": "", 
          "region": "RegionOne", 
          "request_ids": [], 
          "security_groups": [
            {
              "description": "Default security group", 
              "id": "591c15c8-c43c-4d97-92a3-842479db2793", 
              "name": "default", 
              "security_group_rules": [
                {
                  "direction": "ingress", 
                  "ethertype": "IPv4", 
                  "id": "6a46c65a-7b17-48c8-94e0-3de93a9b5639", 
                  "port_range_max": null, 
                  "port_range_min": null, 
                  "protocol": null, 
                  "remote_ip_prefix": null, 
                  "security_group_id": "591c15c8-c43c-4d97-92a3-842479db2793"
                }, 
                {
                  "direction": "ingress", 
                  "ethertype": "IPv4", 
                  "id": "c8b924e8-9bab-484d-b99b-08b425fdfd50", 
                  "port_range_max": null, 
                  "port_range_min": null, 
                  "protocol": null, 
                  "remote_ip_prefix": null, 
                  "security_group_id": "591c15c8-c43c-4d97-92a3-842479db2793"
                }
              ]
            }
          ], 
          "status": "ACTIVE", 
          "tenant_id": "b51003047eab49a4b75322ffdc20c5b8", 
          "updated": "2016-03-24T21:10:16Z", 
          "user_id": "6b9d9e3142bd404f8804a62397cd46b1", 
          "volumes": [], 
          "x_openstack_request_ids": []
        }
      }
    }
  }, 
  "envvars": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "envvars_RegionOne": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "envvars_RegionOne_nova": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "flavor-m1.medium": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "image-trusty": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "instance-15218bc8-8c92-4d4d-89df-4183721fc9e8": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "meta-ansible_host_groups_admin_v_infrastructure,apt_repos": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "meta-ansible_host_vars_dns_server_for_domains->v.clusterb.centerdevice.local,infrastructure.v.clusterb.centerdevice.local": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "nova": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ], 
  "test": [
    "15218bc8-8c92-4d4d-89df-4183721fc9e8"
  ]
}
```

How would I make sure that when ansible looks for all my servers it finds all of these machines?
Or is the idea that since ansible goes in via SSH, I cannot access them anyway without a floating IP from the machine where I am doing the querying of the keystone endpoint?

I do not seem to be able to authenticate against my endpoint using just the openstack.yml file:

```
(ansible) aszekely@aszekely:~/$ /etc/ansible/hosts --list --debug
Manager defaults: running task ServerList
Couldn't construct compute object
Traceback (most recent call last):
  File "/home/aszekely/.virtualenvs/ansible/local/lib/python2.7/site-packages/shade/openstackcloud.py", line 276, in _get_client
    **kwargs)
  File "/home/aszekely/.virtualenvs/ansible/local/lib/python2.7/site-packages/os_client_config/cloud_config.py", line 304, in get_legacy_client
    endpoint = self.get_session_endpoint(service_key)
  File "/home/aszekely/.virtualenvs/ansible/local/lib/python2.7/site-packages/os_client_config/cloud_config.py", line 245, in get_session_endpoint
    session = self.get_session()
  File "/home/aszekely/.virtualenvs/ansible/local/lib/python2.7/site-packages/os_client_config/cloud_config.py", line 188, in get_session
    "Problem with auth parameters")
OpenStackConfigException: Problem with auth parameters
Manager defaults: ran task ServerList in 0.000869035720825s
Error fetching server list on defaults::
```

The file is like this:

```
clouds:
  indispeq:
    external_network: XXXX_NETWORK
    auth:
      password: xxxxxxxxxx
      username: xxxxxxxxxx
      project_name: indispeq
      auth_url: "http://xx.xx.xx.xx:5000/v2.0"
    region_name: RegionOne
ansible:
  use_hostnames: True
  expand_hostvars: False
```

What am I missing that cannot authenticate? It fails at the shade-inventory part.
