### ISSUE TITLE
Feature request: mysql --init-command for mysql_db

### ISSUE THREAD

**Issue by igormukhingmailcom** [ansible/ansible#15158]
Hi. 

It would be great if `mysql_db` will have something like `init_command` and pass this command to `mysql --init-command=...` option. 

```
mysql_db:
    name: "{{ app_db_name }}"
    login_host: "{{ app_db_host }}"
    login_user: "{{ app_db_user }}"
    login_password: "{{ app_db_password }}"
    state: import
    target: /tmp/dump.sql
    init_command: "SET SESSION FOREIGN_KEY_CHECKS=0;"
```

See https://docs.oracle.com/cd/E17952_01/refman-5.5-en/mysql-command-options.html#option_mysql_init-command

This will help to import dumps with constraints by passing `SET SESSION FOREIGN_KEY_CHECKS=0;`. 

Right now it failing if something not OK with data in terms of constraints:

```
failed: [staging.xxx.com] => {"failed": true}
msg: ERROR 1452 (23000) at line 317589: Cannot add or update a child row: a foreign key constraint fails (`xxx_staging`.`#sql-31d8_44`, CONSTRAINT `FK_CATALOG_EAV_ATTRIBUTE_ATTRIBUTE_ID_EAV_ATTRIBUTE_ATTRIBUTE_ID` FOREIGN KEY (`attribute_id`) REFERENCES `eav_attribute` (`attribute_id`) ON DELETE C)
```

Thanks :)
