### ISSUE TITLE
ansible-playbook doesn't honor --user

### ISSUE THREAD

**Issue by vossenjp** [ansible/ansible#1518]
Using ansible 0.9 (devel 0faef761cf) on Debian Squeeze (installed via deb built from ...packaging/debian/README.md):

This works: ansible workstations -m ping --user jp --ask-pass
This fails: ansible-playbook --limit workstations --user jp --ask-pass --sudo --ask-sudo-pass /etc/ansible/tasks/ansible-ssh.yml

When I tail '/var/log/auth.log' on a workstation, I get "sshd[29419]: Failed password for root from 192.168.nnn.11 port 44419 ssh2".  Thus, it looks like ansible-playbook doesn't honor --user...

That's pretty ironic since the entire point of that playlist is to set up a root SSH key for Ansible to use henceforth...

**Comment by mpdehaan** [comment]
Let me see your playbook please?

The point of --user is to set the default, if you have it explicitly set, it will use what is in the playbook, so that may be what you are seeing.

**Comment by vossenjp** [comment]
Argh!  You got me!  Duh.  Though I will now argue that this behavior violates "least surprise" because most command line arguments override config file settings!  I'd like to claim that's what I was thinking, but I can't, I just plain forgot I'd put that "user: root" in there.  I will claim "new user" and "first playbook I wrote" excuses though.  :-)

Actually, now that I think about this I really think this violates "least surprise" because other command line arguments such as --limit **do** seem to override config file (well, playbook) settings.  Am I being extra dense today and missing something obvious?

Here is the playbook.  Once I commented out the "user: root" part it worked as expected.  Is this otherwise good or are there better ways?  Once I get this to work on the workstations (that need non-root and sudo, hence my problem), I'll expand it a bit...

```
---
# Ansible playbook to configure SSH

- name: Configure SSH
  hosts: all
  user: root

  tasks:
  - name: Set Ansible Key
    action: authorized_key user=root key="$FILE(/etc/ansible/files/ansible_rsa.pub)" state=present

  - name: Set .ssh dir and file perms
    action: file path=/root/.ssh                 owner=root group=root mode=0700 state=directory
    action: file path=/root/.ssh/authorized_keys owner=root group=root mode=0600 state=file
```
