### ISSUE TITLE
AWS EC2 VPC Module Incorrectly Tagging Subnets

### ISSUE THREAD

**Issue by dmrickert** [ansible/ansible#15197]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
"ansible 2.0.1.0"
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Rerunning ec2_vpc is flipping the names of the subnets.  So, my private subnet (10.0.1.0/24) ends up being named "Public" and my public subnet (10.0.0.0/24) ends up being named "Private".  Running it again flips it back to that.
##### STEPS TO REPRODUCE

Run the following task, each time it will flip the names of your Subnets:

```
    - name: Create the VPC
      ec2_vpc:
        state: present
        region: "us-east-1"
        aws_access_key: "{{ aws_access_key_id }}"
        aws_secret_key: "{{ aws_secret_access_key }}"
        cidr_block: "10.0.0.0/16"
        resource_tags: { "Name": "{{ aws_instance_name }}_vpc" }
        subnets:
          - cidr: "10.0.0.0/24"
            resource_tags: { "Name": "public" }
          - cidr: "10.0.1.0/24"
            resource_tags: { "Name": "private" }
        internet_gateway: True
        wait: true
```
##### EXPECTED RESULTS

Subnet names should match the same subnet ID's and same subnet CIDR blocks on each rerun.
##### ACTUAL RESULTS

Module always reports as changed, and has assigned the opposite names to the subnets.  NOTE: The id and cidr blocks still match.
