### ISSUE TITLE
Skipped tasks register variables.

### ISSUE THREAD

**Issue by killaherz** [ansible/ansible#15195]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version
ansible 1.9.3
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Ansible unsetting variable when used multiple 'when' cases
##### STEPS TO REPRODUCE

```
- stat: path="{{ new_release_path }}/composer.json"
  register: st
  when: ansible_hostname!= "dtests"

- stat: path="{{ current_release_path }}/composer.json"
  register: st
  when: ansible_hostname == "dtests"

- set_fact:
  composer_json_hash: "{{ st.stat.md5 }}"
  when: composer_json_hash == "__auto__"
```
##### EXPECTED RESULTS

```
TASK: [composer | stat path="{{ new_release_path }}/composer.json"] *********** 
<localhost> REMOTE_MODULE stat path="/var/www/myCoolApplication/releases/2016-03-29-15-06/composer.json"
ok: [jenkins] => {"changed": false, "stat": {"atime": 1459253261.8027189, "checksum": "4bf7a96c69098b52b1e03dc5fac9b3e01c5d28a1", "ctime": 1459253261.8027189, "dev": 1797, "exists": true, "gid": 0, "gr_name": "root", "inode": 2678738, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "md5": "eb7ee21c6153e8b364155aa2b2f71593", "mode": "0775", "mtime": 1459252419.0, "nlink": 1, "path": "/var/www/myCoolApplication/releases/2016-03-29-15-06/composer.json", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 1422, "uid": 0, "wgrp": true, "woth": false, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}

TASK: [composer | stat path="{{ current_release_path }}/composer.json"] ******* 
skipping: [jenkins]

TASK: [composer | set_fact ] ************************************************** 
ok: [jenkins] => {"ansible_facts": {"composer_json_hash": "eb7ee21c6153e8b364155aa2b2f71593"}}

```
##### ACTUAL RESULTS

``````
TASK: [composer | stat path="{{ new_release_path }}/composer.json"] *********** 
<localhost> REMOTE_MODULE stat path="/var/www/myCoolApplication/releases/2016-03-29-14-32/composer.json"
ok: [jenkins] => {"changed": false, "stat": {"atime": 1459251197.74612, "checksum": "4bf7a96c69098b52b1e03dc5fac9b3e01c5d28a1", "ctime": 1459251197.74612, "dev": 1797, "exists": true, "gid": 0, "gr_name": "root", "inode": 1617200, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "md5": "eb7ee21c6153e8b364155aa2b2f71593", "mode": "0775", "mtime": 1459179049.0, "nlink": 1, "path": "/var/www/myCoolApplication/releases/2016-03-29-14-32/composer.json", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 1422, "uid": 0, "wgrp": true, "woth": false, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}

TASK: [composer | stat path="{{ current_release_path }}/composer.json"] ******* 
skipping: [jenkins]

TASK: [composer | set_fact ] ************************************************** 
fatal: [jenkins] => One or more undefined variables: 'dict object' has no attribute 'stat'```
``````

**Comment by dagwieers** [comment]
I can reproduce this on Ansible v1.9.5 and Ansible v2.0.1 with the following minimal reproducer:

``` yaml
- hosts: localhost
  gather_facts: no
  tasks:

  - stat: path="/etc/hosts"
    register: st
    when: inventory_hostname == 'localhost'

  - stat: path="/etc/hosts"                                                                                        
    register: st
    when: inventory_hostname != 'localhost'

  - set_fact:
      composer_json_hash: "{{ st.stat.md5 }}"
```

**Output on Ansible v1.9.5**

```
PLAY [localhost] ************************************************************** 

TASK: [stat path="/etc/hosts"] ************************************************ 
ok: [localhost] => {"changed": false, "stat": {"atime": 1459279362.9195344, "checksum": "9876c432a4bb262977308cde0ff1d762f5bc235c", "ctime": 1454811223.854907, "dev": 64768, "exists": true, "gid": 0, "gr_name": "root", "inode": 659231, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "md5": "a250fb235aa07f0e8fddc3078ac8285d", "mode": "0644", "mtime": 1454811223.8449066, "nlink": 1, "path": "/etc/hosts", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 966, "uid": 0, "wgrp": false, "woth": false, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}

TASK: [stat path="/etc/hosts"] ************************************************ 
skipping: [localhost]

TASK: [set_fact ] ************************************************************* 
fatal: [localhost] => One or more undefined variables: 'dict' object has no attribute 'stat'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/dag/test78.retry

localhost                  : ok=1    changed=0    unreachable=1    failed=0   
```

**Output on Ansible v2.0.1.0**

```
Using /home/dag/home-made/ansible.testing/ansible.cfg as config file

PLAY ***************************************************************************

TASK [stat] ********************************************************************
ok: [localhost] => {"changed": false, "stat": {"atime": 1459279362.9195344, "checksum": "9876c432a4bb262977308cde0ff1d762f5bc235c", "ctime": 1454811223.854907, "dev": 64768, "exists": true, "gid": 0, "gr_name": "root", "inode": 659231, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": false, "isreg": true, "issock": false, "isuid": false, "md5": "a250fb235aa07f0e8fddc3078ac8285d", "mode": "0644", "mtime": 1454811223.8449066, "nlink": 1, "path": "/etc/hosts", "pw_name": "root", "rgrp": true, "roth": true, "rusr": true, "size": 966, "uid": 0, "wgrp": false, "woth": false, "wusr": true, "xgrp": false, "xoth": false, "xusr": false}}

TASK [stat] ********************************************************************
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [set_fact] ****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict' object has no attribute 'stat'"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @test78.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

I would rewrite the issue title as **Skipped tasks register variables**.

Although it seems strange to me that a task that is skipped still performs an action. However this might be intended in order to know if a subsequent task was in fact skipped or not. It feels weird, but there might be a rationale.
