### ISSUE TITLE
Run ansible host in playbook when conditional true

### ISSUE THREAD

**Issue by PumpkinSeed** [ansible/ansible#15205]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### CONFIGURATION

```
- hosts: couchbase-db
  remote_user: root
  roles:
    - { role: ia.base, when: "'db' in env" }
    - { role: ia.couchbase, when: "'db' in env" }
```
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

My porpuse to skipping the whole host when "db" not in env. Now I got this error, but I want to skip it:

```
TASK [setup] *******************************************************************
fatal: [staging-app-couchbase]: UNREACHABLE! => {"changed": false, "msg": "SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue", "unreachable": true}
```
