### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by svyatov** [ansible/ansible#1521]
There is an error in documentaion "Advanced Playbooks", "[Getting values from files](http://ansible.cc/docs/playbooks2.html#getting-values-from-files)" chapter:

``` yaml
tasks:
    - authorized_key name=$item key=$FILE(/keys/$user1)
      with_items:
         - pinky
         - brain
         - snowball
```

This example would not work, because keys contain spaces, which leads to error:
`msg: this module requires key=value arguments`

The correct example should be like this (quotes added):

``` yaml
tasks:
    - authorized_key name=$item key="$FILE(/keys/$user1)"
      with_items:
         - pinky
         - brain
         - snowball
```

It's definitely worth checking whole documentation for other alike places.
