### ISSUE TITLE
Unexpected Exception: 'NoneType' object has no attribute 'get_vars'

### ISSUE THREAD

**Issue by Constantin07** [ansible/ansible#15210]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible-2.1.0-0.git201603301441.c09e085.devel.el7.centos.noarch
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

```
CentOS Linux release 7.2.1511 (Core)
```
##### SUMMARY

The task with include statement fails with an error after upgrade to latest devel version (c09e085480d51d5a5fc32ee5321c70cddb69656b).
##### STEPS TO REPRODUCE

```
- name: Loop through type1 alarms
  include: alarm_type1.yml
  vars:
    alarm_defaults: "{{ alarms.alarm_defaults }}"
  with_items: "{{ alarms.alarms }}"
```
##### EXPECTED RESULTS

Playbook should run fine.
##### ACTUAL RESULTS

```
TASK [ Loop through type1 alarms] **********************************
task path: /home/User/Test/roles/cloudwatch/tasks/main.yml:4
ERROR! Unexpected Exception: 'NoneType' object has no attribute 'get_vars'

```
