### ISSUE TITLE
'include' tasks statement with 'when' condition doesn't work with `vars_prompt` variable

### ISSUE THREAD

**Issue by klauern** [ansible/ansible#15212]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /home/klauer/.ansible.cfg
  configured module search path = /home/klauer/deployment/trunk/admin/ansible/library
```
##### CONFIGURATION

`ansible.cfg`

``` ini
[defaults]
inventory   = /home/klauer/InfrastructureSoa-trunk/admin/ansible/all-hosts
roles_path  = /home/klauer/deployment/trunk/admin/ansible/roles
library     = /home/klauer/deployment/trunk/admin/ansible/library
forks       = 50
transport   = smart
log_path    = /home/klauer/.ansible/playbook.log
accelerate_multi_key = yes
gathering   = !all
```
##### OS / ENVIRONMENT

RHEL6
##### SUMMARY

`include` statement with `when` condition doesn't work with `vars_prompt` variable.
##### STEPS TO REPRODUCE

Given a task file like the following:

``` yaml
- name: Echo something
  shell: echo "Hi"
```

And a playbook that uses it:

``` yaml
#!/usr/bin/env ansible-playbook

---
- hosts: localhost
  vars_prompt:
  - name: should_echo
    default: True
    private: no
    prompt: "Should I Echo it?"
  tasks:
  - debug: var=should_echo
  - include: echo-task.yml
    when: should_echo == True
```

The output is the following, even if you leave the default:

``` sh
$ ansible-playbook test-echo.yml
Should I Echo it? [True]:

PLAY ***************************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "should_echo": true
}

TASK [include] *****************************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

However, if you switch the `vars_prompt` with simply `vars`, it will work:

``` yaml
#!/usr/bin/env ansible-playbook

---
- hosts: localhost
  vars:
    should_echo: True
  tasks:
  - debug: var=should_echo
  - include: echo-task.yml
    when: should_echo == True
```

``` sh
$ ansible-playbook test-echo.yml

PLAY ***************************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "should_echo": true
}

TASK [include] *****************************************************************
included: /home/eaihost/deployment/trunk/admin/ansible/control/echo-task.yml for localhost

TASK [Echo something] **********************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```
##### Gist

Here's a gist of the files to test: https://gist.github.com/klauern/393fb2a7890463912147e43aeef2c7b6
##### EXPECTED RESULTS

I expect that being able to set `True` on the `should_echo` variable would include and run the associated task file.
##### ACTUAL RESULTS

```
$ ansible-playbook test-echo.yml -vvvv
Using /home/eaihost/.ansible.cfg as config file
Loaded callback default of type stdout, v2.0
1 plays in test-echo.yml
Should I Echo it? [True]:

PLAY ***************************************************************************

TASK [debug] *******************************************************************
task path: /home/eaihost/deployment/trunk/admin/ansible/control/test-echo.yml:13
ok: [localhost] => {
    "should_echo": true
}

TASK [include] *****************************************************************
task path: /home/eaihost/deployment/trunk/admin/ansible/control/test-echo.yml:14
skipping: [localhost] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
