### ISSUE TITLE
out of memory - yum update fails silently / shows no error

### ISSUE THREAD

**Issue by cmmarslender** [ansible/ansible#15234]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /Users/christophermarslender/Projects/ansible-provisioner/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

```
[defaults]
ansible_managed = This file is managed by Ansible. Any direct edits will be lost!
forks=50

[ssh_connection]
pipelining=True
```
##### OS / ENVIRONMENT

Running from OSX / Managing CentOS 7 `CentOS Linux release 7.1.1503 (Core)`
##### SUMMARY

Trying to update php using "latest" and yum module. Remote server runs out of memory, and local ansible doesn't show any sort of error. I believe pre 2.x it would show an error as part of the output.
##### STEPS TO REPRODUCE

Trying to update php using the yum module of ansible, like so:

```
- name: Install base php requirements
  yum:
    name: "{{ item }}"
    state: latest
    enablerepo: remi,remi-php70
  with_items:
    - php-common
    - php-cli
    - php-mbstring
    - php-xml
    - php-xsl
    - php-pear
    - php-gd
    - php-mcrypt
    - php-pecl-memcached
    - php-mysqlnd
    - php-soap
    - php-opcache
    - php-process
  register: php_base_result
```

This particular server has very little RAM, and runs out of memory because yum pushes it over the limit. (Already running is nginx, php-fpm, mysql, memcached, etc)

/var/log/messages shows this: 

```
Mar 31 21:58:06 chris1 kernel: Out of memory: Kill process 6162 (yum) score 245 or sacrifice child
Mar 31 21:58:06 chris1 kernel: Killed process 6162 (yum) total-vm:465200kB, anon-rss:125316kB, file-rss:636kB
```
##### EXPECTED RESULTS

I would expect to see an error in the output from ansible if yum is killed
##### ACTUAL RESULTS

Ansible shows that everything went fine in the CLI. It _doesn't_ say that anything changed, but it also doesn't say that anything had an error - Output: https://cloudup.com/cbXbc-sjiIr

```
TASK [php : Install base php requirements] *************************************
ok: [chris1] => (item=[u'php-common', u'php-cli', u'php-mbstring', u'php-xml', u'php-xsl', u'php-pear', u'php-gd', u'php-mcrypt', u'php-pecl-memcached', u'php-mysqlnd', u'php-soap', u'php-opcache', u'php-process'])
```
