### ISSUE TITLE
Feature: role scoped variables

### ISSUE THREAD

**Issue by bjne** [ansible/ansible#15243]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.2

##### SUMMARY
variable leakage is a concern when using role dependencies and passing arguments.
One possible (and easy?) solution to this would be to define a variable prefix to make it
scoped to a role, and not leak into parents or into child roles (...and back).

These variables should work the following way:

1) beeing able to be set in defaults and vars within a role, but never passed on outside role
2) beeing able to pass to role dependencies

I would suggest for example __variable_name (twoUnderscoresVariableName)

**Comment by dagwieers** [comment]
Same for role handlers, we have had issues with handlers from different roles replacing each other. Role handlers should run at the end of the role, not replacing whatever was first at the end of the play.

**Comment by tima** [comment]
@bjne: roles can be called multiple times by a play with different params being passed in. A common prefix would not be sufficient enough to solve inadvertent variable overwrites and naming collisions.

**Comment by bjne** [comment]
It the whole point with scoped variables is that they should never "leave" the role, this
would work out just fine. One would have to then store __ variables temporary when leaving
a role, undefining them in the global scope, then redefining from tmp storage when you
return from a child-role.

Never "leave" means not leak down to child roles or up to parent roles, but a parent role
should be able to pass these variables down to a child/dependency role if, and only if,
they are passed explicitly as a variable to the role dependency.

**Comment by tima** [comment]
I understand the point of scoped variables. Roles are not objects though were never advertised as such.

**Comment by bjne** [comment]
For me as a heavy user, its obvious this is the next step.

**Comment by Mikulas** [comment]
I'm very much for the idea. There already were multiple bugs due to this in our setup.

Regarding the `__variable_name`, consider that those variables might be user-facing:
```
- role: org.role
  __variable_name: foo
```

In your use-case, are those variables available here? What happens when the scoped variable is set prior?

Alternative idea: instead of prefix, scoped variables would be defined in `meta.yaml` of the role.

**Comment by ansibot** [comment]
@bjne Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by biomassives** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  acmeideal@gmail.com
    Domain biomassiv.es has exceeded the max emails per hour (124/100 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:52013 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by chi-server32.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.88)
	(envelope-from <noreply@github.com>)
	id 1ctLS5-001uY2-9W
	for greg@biomassiv.es; Wed, 29 Mar 2017 16:48:25 -0500
Date: Wed, 29 Mar 2017 14:47:46 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1490824066;
	bh=jopngiSXUJWsgnSPlahrVauF3iH4igXAsH32AXMFt+8=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=t3FwswUF1NQJGeEzfjP7ZRrJe9iKDt9fgMOt9PbfvTdBiL852FSicAKyNcPGGmmcf
	 K0iBnKmJITAg0OmoWDTAsGWwes2sg96z5I6nmDIsu30LKDSZ2nWd2oBcU6nWLQ1wwX
	 NsPJkky9H1mTNN1p5gdXgHcZXznz6DiwzqohUpYs=

**Comment by matjam** [comment]
So, the use case for me was that I have a role that when passed a certain set of variables, it will go off to ec2 and create a bunch of instances. I wanted it to be declarative, so that I just declare, how many of what type I want, and it would generate hostnames, tags, all that stuff, and create the instances.

The problem I hit (other than being new to ansible) was that I needed to loop over VPC, subnet, and then create the instances in each subnet, and each time I exit a loop any variables I set inside the loop were lost.

My hostnames are configured such that they start at [customer]-[role]-5001a for us-east and [customer]-[role]-6001a for us-west, and I wanted the hostnames to auto-increment as I provision.

For example;

each_subnet.yml:
```yaml
- name: "{{ _aws_role_config.role }} :: Creating instances for VPC {{ _aws_vpc_name }}"
  include_tasks: each_instance.yml
  with_sequence: start="{{ hostvars['AWS_INSTANCE_COUNT_HOLDER']['host_counter']|int }}" end="{{ hostvars['AWS_INSTANCE_COUNT_HOLDER']['host_counter']|int + _aws_role_config.count|int - 1 }}" format="{{ aws_customer + '-' + _aws_role_config.role + '-%04d' + aws_hostname_suffix }}"
  loop_control:
    loop_var: _aws_hostname
```

each_instance.yml:
```yaml
- name: "update host counter"
  add_host:
    name: "AWS_INSTANCE_COUNT_HOLDER"
    host_counter: "{{ hostvars['AWS_INSTANCE_COUNT_HOLDER']['host_counter']|int + 1 }}"
```

this could be greatly simplified if I could have some role scoped variables as suggested:

each_subnet.yml:
```yaml
- name: "{{ _aws_role_config.role }} :: Creating instances for VPC {{ _aws_vpc_name }}"
  include_tasks: each_instance.yml
  with_sequence: start="{{ __host_counter|int }}" end="{{ __host_counter|int + _aws_role_config.count|int - 1 }}" format="{{ aws_customer + '-' + _aws_role_config.role + '-%04d' + aws_hostname_suffix }}"
  loop_control:
    loop_var: _aws_hostname
```

each_instance.yml:
```yaml
- set_fact:
    __host_counter: "{{ __host_counter|int + 1 }}"
```

even better would be something that could just set __vars directly

```yaml
- set_var: __host_counter = "{{ __host_counter|int + 1 }}"
```

or something like that.

**Comment by lucendio** [comment]
is there any update on this or maybe a roadmap for implementing the feature?

**Comment by bcoca** [comment]
you can already kind of do this:

main.yml
```yaml
block: 
  ....

vars:
  thisvar: is only visible to tasks inside the block, which can include all tasks in role exclusively
```
