### ISSUE TITLE
'with_dict' items expanded before conditional evaluation

### ISSUE THREAD

**Issue by bregman-arie** [ansible/ansible#15258]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### CONFIGURATION

Ansible 2.0.1.0 on Red Hat Enterprise Linux 7.2
##### SUMMARY

When specifying 'with_dict: x' + 'when: x is defined' an error occurs, although x isn't defined.
I would expect to see the task being skipped.
##### STEPS TO REPRODUCE

```
- name: Create flavors
  os_nova_flavor:
      name: "{{ item.value.nane | default(flavor_name) }}"
      state: present
  register: flavors
  with_dict: "{{ provisioner.nova.flavors }}"
  when: provisioner.nova.flavors is defined
```
##### EXPECTED RESULTS

Skipping 'Create flavors' task
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "with_dict expects a dict"}
```
