### ISSUE TITLE
ignore_errors ignores undefined variables

### ISSUE THREAD

**Issue by michelleperz** [ansible/ansible#15265]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /home/vagrant/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Only change in ansible.cfg is I'm using a private key for authentication.
##### OS / ENVIRONMENT

```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:    14.04
Codename:   trusty
```
##### SUMMARY

The error handling docs on ignore_errors (http://docs.ansible.com/ansible/playbooks_error_handling.html#ignoring-failed-commands) indicate that undefined variables will still fail out the playbook even with ignore_errors set to yes.  In my environment, however, a task with an undefined variable will not fail out and says ignoring.
##### STEPS TO REPRODUCE

Create a playbook with a task that has an undefined variable

```

---
- name: testing error handling
  hosts: testServer
  remote_user: ec2-user
  become: yes

  tasks:
  - name: testing ignore errors
    user: name=testUser password={{uPassword}}
    ignore_errors: yes

  - name: next task
    shell: echo hello world  
```

Run the playbook 
##### EXPECTED RESULTS

Based on the docs, I expected the task to fail because I did not define the variable.
##### ACTUAL RESULTS

```
TASK [testing ignore errors] ***************************************************
task path: /home/vagrant/myProject/testErrors.yml:8
fatal: [52.36.200.205]: FAILED! => {"failed": true, "msg": "ERROR! 'uPassword' is undefined"}
...ignoring


```
