### ISSUE TITLE
v2 polling behavior inconsistent when poll duration not explicitly set

### ISSUE THREAD

**Issue by drfickle** [ansible/ansible#15288]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /home/sfox/.ansible.cfg
  configured module search path = /home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/library
```
##### CONFIGURATION

```
library = /home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/library
forks          = 20
sudo_flags = -H -i
jinja2_extensions = jinja2.ext.do,jinja2.ext.i18n,jinja2.ext.loopcontrols,jinja2.ext.with_
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = /usr/share/ansible_plugins/action_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/action
callback_plugins   = /usr/share/ansible_plugins/callback_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/callback
connection_plugins = /usr/share/ansible_plugins/connection_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/connection
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/lookup
vars_plugins       = /usr/share/ansible_plugins/vars_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/vars
filter_plugins     = /usr/share/ansible_plugins/filter_plugins:/home/sfox/src/sysops/ops/branches/ansible-2.0/ansible/plugins/filter
nocows = 1
```
##### OS / ENVIRONMENT

From: Fedora 23
Managing: Ubuntu Trusty (14.04)
##### SUMMARY

Marking a step asynchronous without specifying a polling duration results in immediate execution of the next step whereas marking the same step with 'poll: 10' waits 10 seconds, then executes the next step. Given 10 seconds is the documented default, I would expect identical behavior.
##### STEPS TO REPRODUCE

When using pg_basebackup to back up a PostgreSQL cluster, the -write-recovery-conf argument will write out a recovery.conf file to the directory specified by the -D argument. My next step adds a line to that file to specify a trigger file used to cause a database failover.

The second line fails because it's executing before pg_basebackup gets a chance to run.

Obviously I have an easy work-around, but this behavior differs from Ansible 1.9.x and it may affect others.

```
- name: Run pg_basebackup to create a main backup cluster
  command: /usr/bin/ionice -c 3 /usr/bin/pg_basebackup -D /backup/major-release-database/main  --no-password --write-recovery-conf --xlog-method=stream
  become: yes
  become_user: postgres
  async: 99999

- name: Append trigger_file to the backup recovery.conf files
  lineinfile: dest={{ item }} insertafter=EOF state=present line="trigger_file = '/backup/major-release-database/DISABLE_BACKUP_STANDBY'"
  with_items:
    - /backup/major-release-database/main/recovery.conf
```
##### EXPECTED RESULTS

Execute the lineinfile statement without error.
##### ACTUAL RESULTS

```
TASK [Append trigger_file to the backup recovery.conf files] ************
failed: [sd-zt-steve-prod-0] (item=/backup/major-release-database/main/recovery.conf) => {"failed": true, "item": "/backup/major-release-database/main/recovery.conf", "msg": "Destination /backup/major-release-database/main/recovery.conf does not exist !", "rc": 257}
```
