### ISSUE TITLE
Installing a package with "apt" with option "deb" and "with_items" is broken

### ISSUE THREAD

**Issue by daviddq** [ansible/ansible#15285]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### OS / ENVIRONMENT

Linux ubuntu 3.16.0-67-generic #87~14.04.1-Ubuntu SMP Fri Mar 11 00:26:02 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

I've got this simple playbook:

```
- name: test
  hosts: webservers
  gather_facts: no
  tasks:
    - name: install profiling server artifact
      apt: deb={{ item }} state=present force=yes 
      with_items: "/tmp/artifacts-KVnHZZ/my-package-8.42.28-x64-ubuntu14-gcc.deb"
```

Running it gives the following error:

```
failed: [aws_dev_server] => (item=/tmp/artifacts-KVnHZZ/my-package-8.42.28-x64-ubuntu14-gcc.deb) => {"failed": true, "item": "/tmp/artifacts-KVnHZZ/my-package-8.42.28-x64-ubuntu14-gcc.deb", "msg": "parameters are mutually exclusive: ['package', 'upgrade', 'deb']"}
```

With Ansible 2.0.0.1 it works OK.

Also, modifying as follows works on v 2.0.1.0:

```
- name: test
  hosts: webservers
  gather_facts: no
  tasks:
    - name: install profiling server artifact
      apt: deb="/tmp/artifacts-KVnHZZ/my-package-8.42.28-x64-ubuntu14-gcc.deb" state=present force=yes 
```
