### ISSUE TITLE
Cron user parameter ignored

### ISSUE THREAD

**Issue by frenkel** [ansible/ansible#15296]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /home/frank/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

My ansible.cfg

```
[defaults]
inventory = /home/frank/Source/ansible/hosts
retry_files_enabled = False
remote_user = frank

[privilege_escalation]
become = True
become_user = root
become_method = sudo
```

I'm using a group_var `ansible_become_method=doas` on OpenBSD.
##### OS / ENVIRONMENT
- Debian 7
- OpenBSD 5.8 & 5.9
##### SUMMARY

Whenever Ansible 2 needs to create a new cronjob for a certain user, it creates the job in the root crontab of my Debian and OpenBSD based servers. It is difficult to say when this problem was introduced, because when the job already exists in the users cron, it will not be added to the root cron.
##### STEPS TO REPRODUCE

```
  tasks:
      - name: configure mail sending cronjob
        cron:
          name: send-notification-mails
          job: cd current && bin/rails runner Notification.send_mails
          hour: 17
          minute: 0
          user: production
```
- When root crontab and production crontab are empty, running this will add the cronjob to the root crontab. Re-running will not modify anything.
- When production crontab already contains the job, running this will not modify any crontab.
##### EXPECTED RESULTS

Job should always be added to production user's crontab
##### ACTUAL RESULTS

When it was missing, it is added to root's crontab
##### WORK AROUND

Use `become_user: production`
