### ISSUE TITLE
no action detected in task in included playbook

### ISSUE THREAD

**Issue by COLABORATI** [ansible/ansible#15309]
I have seen that there are multiple issues and all are closed, but I have the same error when including a simple playbook and can not see what is wrong: 

```
no action detected in task
```

the playbook that includes: 

```

---
- name: include play test
  hosts: all

  tasks:
    - include: base.yml

```

the included playbook:

```

---
- hosts: all
  sudo: yes

  tasks:
    - name: apt-get dist-upgrade
      apt: upgrade=dist update_cache=yes

    - name: install basic tools 
      apt: name=apt-transport-https state=latest

```

the included playbook works fine when not included but directly executed. 
ansible is installed from the trusty ppa:

```
root@rails:~# ansible --version
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by dagwieers** [comment]
You cannot include a complete playbook inside a play. You can include a "taskbook" (a list of tasks) within a play, but not one or more "plays".

However you can include a playbook inside another playbook, but not at the task-level, you have to do it at the play-level.

``` yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - include: files/taskbook.yml

- include: playbook.yml
```

A "taskbook" consists of a list of tasks and would look like this:

``` yaml
- debug: msg='Example 1 from within a taskbook task'
- debug: msg='Example 2 from within a taskbook task'
```

While a playbook consists of a list of plays and would look like this:

``` yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - debug: msg='Example 1 from within a playbook play'

- hosts: localhost
  gather_facts: no
  tasks:
  - debug: msg='Example 2 from within a playbook play'
```
