### ISSUE TITLE
feature: let fail: not depend on msg:

### ISSUE THREAD

**Issue by bjne** [ansible/ansible#15313]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.2

##### SUMMARY

Currently fail: needs msg:, so task becomes something like this:

```
- when: true
  fail:
    msg: |-
      overcomplicated
```

A nicer syntax afail is:

```
- when: true
  fail: |-
    much better
```

or even:

`- fail: foo`
