### ISSUE TITLE
Link Speed is not gathered by facts

### ISSUE THREAD

**Issue by smalleni** [ansible/ansible#15325]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

--> N/A
##### SUMMARY

Information about the interfaces doesn't include link speed currently, it would be nice to have this feature
##### STEPS TO REPRODUCE

--> Currently, gathered facts include interface information such as mtu, but link speed information is not present in the data gathered for each interface. It would be very useful to have this information. Facts were gathered using,

```
ansible hostname -m setup

```
##### EXPECTED RESULTS

```
ansible_em1": {
        "active": true,
        "device": "em1",
        "macaddress": "d4:be:d9:b3:8f:0b",
        "module": "bnx2",
        "mtu": 1500,
        "pciid": "0000:01:00.0",
        "promisc": true,
        "type": "ether"
         "speed": "1000Mb/s"
    },
```
##### ACTUAL RESULTS

```
ansible_em1": {
        "active": true,
        "device": "em1",
        "macaddress": "d4:be:d9:b3:8f:0b",
        "module": "bnx2",
        "mtu": 1500,
        "pciid": "0000:01:00.0",
        "promisc": true,
        "type": "ether"
    },

```

**Comment by Yannig** [comment]
Here's a simple patch to add link speed detection:

``` patch
diff --git a/lib/ansible/module_utils/facts.py b/lib/ansible/module_utils/facts.py
index 203a729..ddb6607 100644
--- a/lib/ansible/module_utils/facts.py
+++ b/lib/ansible/module_utils/facts.py
@@ -2021,6 +2021,10 @@ class LinuxNetwork(Network):
                         interfaces[device]['all_slaves_active'] = get_file_content(path) == '1'
             if os.path.exists(os.path.join(path,'device')):
                 interfaces[device]['pciid'] = os.path.basename(os.readlink(os.path.join(path,'device')))
+            if os.path.exists(os.path.join(path, 'speed')):
+                speed = get_file_content(os.path.join(path, 'speed'))
+                if speed is not None:
+                    interfaces[device]['speed'] = int(speed)

             # Check whether an interface is in promiscuous mode
             if os.path.exists(os.path.join(path,'flags')):
```

And here the result:

``` yaml
        "ansible_eth0": {
            "active": true, 
            "device": "eth0", 
            "ipv4": {
                "address": "192.168.0.32", 
                "broadcast": "192.168.0.255", 
                "netmask": "255.255.255.0", 
                "network": "192.168.0.0"
            }, 
            "ipv6": [
                {
                    "address": "fe80::f66d:4ff:fe1e:61c3", 
                    "prefix": "64", 
                    "scope": "link"
                }
            ], 
            "macaddress": "f4:6d:04:1e:61:c3", 
            "module": "r8169", 
            "mtu": 1500, 
            "pciid": "0000:01:00.0", 
            "promisc": false, 
            "speed": 1000, 
            "type": "ether"
        }, 
```

I will submit a PR later.
