### ISSUE TITLE
feature: calling handlers/meta: flush_handlers extension

### ISSUE THREAD

**Issue by bjne** [ansible/ansible#15338]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
handlers and meta

##### ANSIBLE VERSION
N/A

##### SUMMARY

Sometimes I deal with complex start/restart procedures, where for example a service
must first start on a master server, and then slaves will start, and perhaps additional
logic and execution order that is allways needed when start/stop/restart, and other
handlers, so I place the handler tasks in the correct order, and they are executed
correctly, for example (handlers/main.yml)

```
- name: restart
  ping:
  changed_when: true
  notify:
  - stop slaves
  - stop master
  - start master
  - start slaves

- name: stop slaves
  command: ...

- name: stop master
  command: ...

 ...
```

So I can then just notify restart, and the correct order or operations is achieved.

A task I think is missing is to be able to use this handler logic in tasks without
triggering a "changed" event unless something is really changed, say for example to ensure
a cluster is started.

at the moment, I have two choices:
- reimplement the logic as tasks/include
- force triggering a notify (will cause a increment in changed)

I dont like either of these approaches, so my proposal is one or both of the following, with
the first one (meta) perhaps preferred

```
- meta: flush_handlers
  notify: start
```

```
- name: add notify event without causing a change event (unless the notify itself changes something)
  handler: start

- meta: flush_handlers 
```

```
- name: notify and flush
  handler:
    - start
    - stop
  flush_handlers: true
```
