### ISSUE TITLE
new file 0: on remote server after calling ansible-playbook

### ISSUE THREAD

**Issue by nbari** [ansible/ansible#15330]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

Remote server: FreeBSD
Client: Mac os X 
##### SUMMARY

In the target host a new file with name `0:` apear after calling a playbook containing the `copy` module
##### STEPS TO REPRODUCE

```

---
- hosts: '{{ target }}'
  remote_user: devops
  become: True
  become_user: root
  become_method: su
  gather_facts: yes

  tasks:
    - name: copy dumy file
      copy: src=/tmp/test dest=/home/devops/test
```

`ansible-playbook test.yml  -e "target=host"`

##### EXPECTED RESULTS

`$ ls /home/devops`  (empty)
##### ACTUAL RESULTS

```
$ ls /home/devops
0:
```
