### ISSUE TITLE
Behavior of include totally changes in 2.1

### ISSUE THREAD

**Issue by windowsrefund** [ansible/ansible#15342]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel 1f82c2c4a8) last updated 2016/04/08 10:55:03 (GMT -400)
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Work flow of include has changed in a drastic way between 2.0 and 2.1
##### STEPS TO REPRODUCE

```
- name: "Build a file of tasks to include"                                         
  template:                                                                        
    src: include_tasks.j2                                                          
    dest: "/tmp/include_tasks.yml"                                                 

- name: Run tasks against reference instances                                      
  include: "/tmp/include_tasks.yml"

```
##### EXPECTED RESULTS

The above work flow (dynamically build a set of tasks to run later) works on 2.0
##### ACTUAL RESULTS

The same code fails on 2.1. It seems the include: is run before any tasks in the play on 2.1.

```
 fatal: [localhost]: FAILED! => {"failed": true, "reason": "the file_name '/tmp/include_tasks.yml' does not exist, or is not readable"}
```

**Comment by dagwieers** [comment]
Hmm, what I see is that you are templating the file (to the remote target), but you are including the file on the master server (running ansible-playbook). I don't think this work with v2.0 or 1.9 either. If you want to make this work, you can do something like:

```yaml
- name: "Build a file of tasks to include"                                         
  template:                                                                        
    src: include_tasks.j2                                                          
    dest: "/tmp/include_tasks.yml"
    transport: local

- name: Run tasks against reference instances
  include: "/tmp/include_tasks.yml"
```
