### ISSUE TITLE
Random MODULE_FAILURE when using lxc_container with DEFAULT_EXECUTABLE

### ISSUE THREAD

**Issue by slash3g** [ansible/ansible#15352]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
lxc_container module

##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default ansible.cfg
##### OS / ENVIRONMENT

openSUSE Tumbleweed (20160407) (x86_64)
##### SUMMARY

lxc_container tasks randomly fail with a MODULE_FAILURE:

```
fatal: [lilikhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

The bug has apparently been introduced in commit 8647fdc7f25ba1c707c5333ca1581a1fa0ffe566 and is somewhat related to DEFAULT_EXECUTABLE beign "/bin/sh". If I set DEFAULT_EXECUTABLE to "/bin/bash" the tasks will run just fine.
##### STEPS TO REPRODUCE

Running the following playbook will fail approximately once every three runs if the container already exists.

```
---    
- hosts: lilikhost     
  tasks:     
    - name: create the lxc container     
      lxc_container:     
        name: container-tmp     
        backing_store: lvm                    
        vg_name: sysvg                        
        lv_name: vm_tmp                       
        fs_type: xfs                
        container_log: true         
        template: debian            
        template_options: --release stretch --packages "ssh python"     
        state: started  
```
##### EXPECTED RESULTS

```
TASK [create the lxc container] ************************************************
ok: [lilikhost]
```
##### ACTUAL RESULTS

```
TASK [create the lxc container] ************************************************
fatal: [lilikhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

Output with '-vvvv':

```
TASK [create the lxc container] ************************************************
task path: /home/slash/Documents/new_lilik/debug.yaml:4
<10.42.0.5> ESTABLISH SSH CONNECTION FOR USER: root
<10.42.0.5> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/slash/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.42.0.5 '/bin/sh -c '"'"'mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1460220280.69-146057275537503 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1460220280.69-146057275537503 `"'"'"''
<10.42.0.5> PUT /tmp/tmplx4Io5 TO /root/.ansible/tmp/ansible-tmp-1460220280.69-146057275537503/lxc_container
<10.42.0.5> SSH: EXEC sftp -b - -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/slash/.ansible/cp/ansible-ssh-%h-%p-%r '[10.42.0.5]'
<10.42.0.5> ESTABLISH SSH CONNECTION FOR USER: root
<10.42.0.5> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/slash/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.42.0.5 '/bin/sh -c '"'"'LANG=en_GB.UTF-8 LC_ALL=en_GB.UTF-8 LC_MESSAGES=en_GB.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1460220280.69-146057275537503/lxc_container; rm -rf "/root/.ansible/tmp/ansible-tmp-1460220280.69-146057275537503/" > /dev/null 2>&1'"'"''
fatal: [lilikhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "lxc_container"}, "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.2g-fips  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18171\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 10.42.0.5 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```
