### ISSUE TITLE
feature: controlling ignore-errors output

### ISSUE THREAD

**Issue by bjne** [ansible/ansible#15350]
#### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ignore_errors

##### ANSIBLE VERSION
N/A

##### SUMMARY

When running with `ignore_errors: true`, ansible by defaults outputs the red-failure and ...ignoring.
This can be a little problematic when running big plays, because the failed/red text is scaring, and
causes scrolling in history to see exactly what went wrong (nothing) ;)

Also, `failed_when: false` is not really usable, since one can not use: `result|failed`

I suggest adding something like the following:

```
- name: check that port is listening
  wait_for: port=80 state=started timeout=10
  register: _listening
  ignore_errors: true
    text: "port 80 is not open"
    text_style: ok
```

..or just similar whatever with similar effect:
- keep the "real" failed/success status in the registered variable
- keep ansible from outputting this as a error (even if ignoring)

**Comment by dagwieers** [comment]
I see your point, but the use-case is very very specific and usually an indication that maybe the approach is wrong. In my experience often if the use of `ignore_errors` is required, the implementation warrants redesigning.

In this specific case you are not simply querying whether the port is listening, you are expecting `state=started`. And since it isn't `started` it clearly is an error. But you only want to query the state of the port (hence the `register` right ?), so maybe `wait_for` is not the correct module to be used. But a more specialized module is in order that returns information/facts of network ports, rather than perform an action or making decision about controlling the process (which the `wait_for` module is actually intended to be used).

**Comment by bjne** [comment]
It might have been wrong to include this spesific test, but please don't let this be about
what approach one uses, but the fact that ignore_errors has a purpose; that sometimes
one can expect "errors" and they are not really errors, it something one can handle later,
and even tho ansible can ignore the errors, my eyes can not. That is the point here, not
the wait_for or whatever task.

**Comment by dagwieers** [comment]
@bjne I am sympathetic to your specific needs, but I disagree here, because I would prefer not adding more flags (and whistles) to influencing how Ansible behaves/outputs for very specific use-cases where the approach could be much better. More complexity means more corner-cases that are hardly tested and/or leads to weird regressions. In my opinion the cost for this is simply too high for the perceived benefit.

**Comment by bcoca** [comment]
@bjne in this case i would recommend you use a custom callback plugin that handles the display the way you want it.

**Comment by dagwieers** [comment]
@bcoca Agreed, I didn't think of this. If specific representation is needed, a custom callback plugin might be an acceptable workaround as well.

But in essence the `wait_for` module is not used for its intended purpose and I would address that instead. I am open to discuss a module that can be used for querying ports or doing netwerk tests. 

For another customer we did connectivity testing using Ansible, doing udp/tcp/ntp/syslog tests, using traceroute-alike functionality one could pin-point to firewall or routing issues, or simply check if expected services were running. This playbook would be run frequently, dump information in a MySQL and a back-end process was scanning for unexpected changes so we could address issues for newly provisioned systems or unexpected failures.

**Comment by bjne** [comment]
@dagwleers: What is used for its intended purpose? The wheel? The computer?

Anyway, I still mean this is a general feature request about the possibility to tone-down
display or ignored errors, and can't be only me that skip a heatbeat over this now and then?

Anyway, for now I will look at using a custom callback, but I try to stay clear of custom's when I can.

Thanks for the tip, @bcoca

**Comment by dagwieers** [comment]
@bjne The intended purpose is to **wait for** a state change.

**wait_for - Waits for a condition before continuing.**
http://docs.ansible.com/ansible/wait_for_module.html

And in my opinion `ignore_errors` is too often band-aid, not a properly designed solution.

**Comment by bjne** [comment]
@dagwieers I dont see either why you are obsessed by wait_for in this issue, which is just an example, or how you can be the judge on howto use wait_for, or ignore_errors for that matter. There is a reason
why ignore_errors are there in the first place.

**Comment by dagwieers** [comment]
@bjne Don't take it personal. If you don't like the advice, just ignore it. Hopefully others might find it useful though.

PS I am not obsessing over `wait_for`, in fact I stated that `ignore_errors` is band-aid. And exists for the wrong reasons IMO.

**Comment by bcoca** [comment]
`failed_when:` is a better alternative, IMHO

**Comment by bjne** [comment]
problem with `failed_when:` is it does not set failed atleast on 2.x, so |failed / |sucess does
not work as "needed"

**Comment by bjne** [comment]
The real point here is ofcorse to allow something to fail, but ignore it, so we can use our
own logic later to decide what to do. We currently have two possibilities for accomplishing this afaik:
1. `ignore_error: true`
2. `error_when: false`

The problem with `error_when:` is it mangles state, so one can not take advantage of for example
`result|failed` and `result|success`

The problem with `ignore_error:` in its current state is, as stated above, that even tho it causes
ansible itself to ignore the error and keep the exit status currectly, it does not let the user ignore
the error when colored ansible output flyes over the screen.

**Comment by dagwieers** [comment]
@bjne Which brings us back to what you are doing. Nothing is in fact failing at all, you want to query the state of a service and act on that. Querying a state is not a failure, shouldn't be considered a failure and shouldn't be ignored as a result. That's why I said the approach is wrong, and why I don't think we need to add more icing on top of that.

**Comment by bjne** [comment]
@dagwieers what is your diagnose?

In my world, a return code is only a error if you act on it. I have no idea why you have such issues
with me checking if a port is in listen state. You dont have the context, and this was just a example
I really regret using as an example here, seeing your OCD kicking in on it.

think 2>/dev/null || echo "not the way I tested for, but hey: still ok!"

Nertheless, remember, this was a plain and easy feature suggestion about in general making
ignore_errors, which is used all over the place, print less "error-like" messages to screen, still
getting my return code and beeing able to use the filters provided.

**Comment by dagwieers** [comment]
It would help if you read what I was saying instead of taking things personally and making it personal.

**Comment by bjne** [comment]
Likewise

**Comment by marciomazza** [comment]
From a UX perspective, it seems reasonable to give visual distinction between **explicitly ignored errors** and **ordinary ones**.

The color **red** used for **ignored errors** (the same as for ordinary ones) catches your eye during output inspection and suggests a call to action... But there is no action to be performed, since the error was anticipated and is usually expected.

The output just distinguishes that by adding a **light blue** `...ignoring` right after the error message... but it is just a tiny word lost at the end of a bunch of **red** lines.

![screenshot from 2016-09-17 16-08-31](https://cloud.githubusercontent.com/assets/579665/18610358/0c76069e-7cf1-11e6-8add-62dcc780dfb2.png)

Please do consider changing the **red** color of the **ignored errors** to ease visual inspection of the output.

**Comment by soumyadipDe** [comment]
+1

**Comment by ansibot** [comment]
@bjne Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sonjz** [comment]
Agreed... in this simple example with wp_cli, when trying to code a user "upsert" I run into this less than desired result.

I followed the pattern of run command to test conditional, register result, use when to execute conditionals, but there is a lot of unnecessary red output for each user processed.

```
# wp_cli.yml
- name: "Wordpress: Users"
  include: wp_cli_users.yml
  static: no
  with_items: "{{ site.users}}"
  loop_control:
    loop_var: user
    label: "{{ user.username }}"

# wp_cli_users.yml
- name: "Wordpress: Users: Check: {{ user.username }}"
  command: wp user get "{{ user.username }} --field=ID" 
    --path="/www/{{ site.name }}"
  ignore_errors: yes
  register: result

- name: "Wordpress: Users: Create {{ user.username }}"
  command: "echo 'create something'"
  when: result|failed

- name: "Wordpress: Users: Update {{ user.username }}"
  command: "echo 'update something'"
  when: result|succeeded

```

![2017-04-19 23_50_56-root ansible_ _www_blogwp-qa](https://cloud.githubusercontent.com/assets/1714763/25213000/dd2d5dce-255b-11e7-8d2a-a32f25117042.png)

**Comment by dagwieers** [comment]
@marciomazza So since your task is testing something, why don't you add `failed_when: no` and test for the `rc`-value in the next task ? Your task is testing something, so a negative return code is not a task-failure, it is data you want to use in a subsequent task. The existence of `ignore_errors:` is not only a misnomer (should have been called "ignore_failed" instead), it is also a left-over of the old Ansible where `failed_when:` or the `block:`-construction did not exist.

So I would advise to never use `ignore_errors` (and would prefer to deprecate it or add a big disclaimer in the documentation).

The intended use for `ignore_errors:` was:
1. To make Ansible continue if the task (unexpectedly) failed
2. To escalate this failure to the user

If you don't want it to fail, and don't want to escalate it to the user (in **red**), use `failed_when:` instead !

**Comment by szhem** [comment]
@dagwieers I'm also interested in this ticket to be resolved.
What I'm doing is just provisioning some servers under the root user and then at the end of play disabling it and creating another user (that is pretty common scenario, I believe)
To make play idempotent I use `wait_for_connection` to check whether the root is able to login to the server. 
Unfortunately as already mentioned in this ticket `failed_when: no` removes `failed` status, `ignore_errors: yes` shows all the ignored errors in red and the only way that remains is to parse `msg` field of the status that depends on the ssh agent in use (and it is error prone)
```yaml
---
- name: Check host connection status
  wait_for_connection:
    connect_timeout: 1
    timeout: 3
  register: host_status
  failed_when: false
  changed_when: false
#  ignore_errors: true

- name: Complete play for already provisioned host
  when: host_status.msg is defined and host_status.msg is search('SSH Error')
#  when: host_status.failed
  meta: end_host
```

**Comment by theque5t** [comment]
@bjne @szhem I recently opened PR #65844 which adds a callback plugin that I believe can assist with this issue. I have included an example below that I believe demonstrates the problem described, and the potential solution using the callback plugin. However, this would require using ansible 2.8.5 or higher.

# Example

## Ansible Version
```
ansible 2.8.5
  config file = None
  configured module search path = ['/home/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/root/py35_ansible28/lib/python3.5/site-packages/ansible
  executable location = /home/root/py35_ansible28/bin/ansible
  python version = 3.5.8 (default, Oct 31 2019, 00:57:08) [GCC 7.4.0]
```

## CONFIGURATION
```

```

## OS / ENVIRONMENT
```
Linux TESTBOX 4.4.0-17134-Microsoft #1130-Microsoft Thu Nov 07 15:21:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## STEPS TO REPRODUCE

1. Create `callback_plugins` directory and add the [diy.py](https://raw.githubusercontent.com/ansible/ansible/781b71e17fc7fa5b3ae09b073c58d5142cceff23/lib/ansible/plugins/callback/diy.py) callback plugin to it

2. Create `playbook.yml`
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: check that port is listening
      debug:
        msg: mock wait for
      failed_when: true
      ignore_errors: true
      vars:
        ansible_callback_diy_runner_on_failed_msg: port 80 is not open
        ansible_callback_diy_runner_on_failed_msg_color: green
```

3. Run the playbook command
```sh
ANSIBLE_STDOUT_CALLBACK=diy ansible-playbook -i localhost, playbook.yml
```

## RESULT
```sh
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************

TASK [check that port is listening] *******************************************************************************************************************************************************************************************************************************************
port 80 is not open

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1

```
The ignored failure message states `port 80 is not open`. Should the message require further adjustment, I believe this example demonstrated how the plugin can be used to adjust the output to the user's preference(also, the plugin itself has documentation, which has additional examples).

**Comment by theque5t** [comment]
@szhem I have included an example below that I believe demonstrates the scenario you described, and the potential solution using the `diy` callback plugin.

# Example

## Ansible Version
```
ansible 2.8.5
  config file = None
  configured module search path = ['/home/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/root/py35_ansible28/lib/python3.5/site-packages/ansible
  executable location = /home/root/py35_ansible28/bin/ansible
  python version = 3.5.8 (default, Oct 31 2019, 00:57:08) [GCC 7.4.0]
```

## CONFIGURATION
```

```

## OS / ENVIRONMENT
```
Linux TESTBOX 4.4.0-17134-Microsoft #1130-Microsoft Thu Nov 07 15:21:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## STEPS TO REPRODUCE

1. Create `callback_plugins` directory and add the [diy.py](https://raw.githubusercontent.com/ansible/ansible/781b71e17fc7fa5b3ae09b073c58d5142cceff23/lib/ansible/plugins/callback/diy.py) callback plugin to it

2. Create `playbook.yml`
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Check host connection status
      wait_for_connection:
        connect_timeout: 1
        timeout: 3
      register: host_status
      ignore_errors: true
      vars:
        ansible_callback_diy_runner_on_failed_msg: ''
        ansible_callback_diy_runner_on_failed_msg_color: green

    - name: Complete play for already provisioned host
      when: host_status.msg is defined and host_status.msg is search('Permission denied')
      meta: end_host

    - name: provision...
      debug:
        msg: mock provision
```

3. Run the playbook command
```sh
ANSIBLE_STDOUT_CALLBACK=diy ansible-playbook -i localhost, playbook.yml
```

## RESULT
```sh
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************

TASK [Check host connection status] *******************************************************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=1
```
The `Check host connection status` task failed, the failure was ignored without printing any errors or red output, the `Complete play for already provisioned host` task ended the play for the host based on the `host_status.msg` content. I believe this example demonstrated how the plugin can be used to adjust the output to the user's preference(also, the plugin itself has documentation, which has additional examples).
