### ISSUE TITLE
lineinfile adds unwanted line break in version 2.0.1.0

### ISSUE THREAD

**Issue by bertramn** [ansible/ansible#15368]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.0.1.0
  config file = /Users/fred/workspaces/bla/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

upgraded ansible from version 1.9.4 to 2.0.1.0
##### OS / ENVIRONMENT

OSX, nothing special 
##### SUMMARY

new version of ansible causes unwanted line breaks to be added in lineinfile replacements 
##### STEPS TO REPRODUCE

Create a task to replace something in a file, e.g.

``` yaml
- name: Configure Karaf Java Home
  lineinfile:
    dest: "{{ karaf_home }}/bin/setenv"
    regexp: '^[#\ ]*export\ JAVA_HOME=.*$'
    line: 'export JAVA_HOME="{{ java_home }}"'
```
##### EXPECTED RESULTS

target file contains a single line as per line declaration of the task, e.g.

```
#
export JAVA_HOME="/usr/java/jdk1.8.0_71"
```
##### ACTUAL RESULTS

Instead ansible adds some weird line break to the end which produces an invalid shell script in my instance.

```
#
export JAVA_HOME="/usr/java/jdk1.8.0_71
"
```

**Comment by dagwieers** [comment]
Just a quick thought.

Is it possible that the original file is a DOS-formatted text file (i.e. the file has carriage return and newline at the end) ?

**Comment by bertramn** [comment]
No but I did find the offender, it was the way I set the `java_home` variable. In 1.9.x the stdout would not carry over a newline when using it to set a fact. For some reason this now does not work anymore. But adding a -n flag to readlink does the trick.

``` yaml
- name: Find Java Development Kit Install Path
  raw: readlink -n -f $(which javac) | sed -e "s#\/bin\/javac##"
  register: java_home_path_check
  failed_when: "'which: no javac in' in java_home_path_check.stdout or 'readlink' in java_home_path_check.stdout"
  changed_when: no
  args:
    executable: /bin/bash

- name: Set Java Home Fact
  set_fact: java_home={{ java_home_path_check.stdout }}

```
