### ISSUE TITLE
group_vars intermittently not applied to launched ec2 nodes (dynamic inventory)

### ISSUE THREAD

**Issue by gavD** [ansible/ansible#15379]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 1.9.5
  configured module search path = None
```

Also tried on our Jenkins server:

```
ansible 1.9.4
  configured module search path = None
```
##### CONFIGURATION

```
[defaults]
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
hostfile = inventory/ec2.py
remote_user = myuser
[ssh_connection]
pipelining = True
ssh_args = -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no
control_path = /tmp/ansible-ssh-%%h-%%p-%%r
```
##### OS / ENVIRONMENT
- My desktop: OSX El Capitan Python `2.7.10`
- Jenkins server: Ubuntu 14.04 LTS Python `2.7.6`
- Nodes being launched: Ubuntu 14.04 LTS
##### SUMMARY

We are using the [dynamic inventory script ec2.py](http://docs.ansible.com/ansible/intro_dynamic_inventory.html).

We are trying to:
1. Grab some topology which describes what we want the cluster to look like
2. Stand up some instances with AWS tag `tag_Environment_{{ our_product_environment }}`
3. Apply the group vars `inventory/group_vars/tag_Environment_{{ our_product_environment }}`
4. Run some roles against those instances

What we are finding is that, intermittently and apparently randomly (about 1/6 of the time), `inventory/group_vars/tag_Environment_{{ our_product_environment }}` is not being applied and we are left with the values from `inventory/group_vars/all`. This results in our cluster being deployed with the wrong values. This manifests on both my laptop and when run from Jenkins.

`add_host` should be loading the correct group_vars file and applying it. In fact, most of the time, it works just fine.
##### STEPS TO REPRODUCE

Here are our group_vars:

```
# inventory/group_vars/all

---
testvar: "This should be overwritten"
```

```
# inventory/group_vars/tag_Environment_demo

---
testvar: "Using demo testvar"
```

Here is a simplified version of our playbook:

``` yaml
# playbook.yaml

---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Launch instance(s) of our base image
      ec2:
        image: 'my-ami-1234567'
        instance_type: "t2.micro"
        keypair: 'ansible-key-pair'
        instance_tags:
          Environment: "{{ our_product_environment }}"
        group_id: 'some-sg'
        region: 'some-region'
        aws_zone: 'some-zone'
        vpc_subnet_id: 'some-subnet'
        wait: true
        assign_public_ip: yes
      register: ec2

    - set_fact:
        instances: "{{ ec2.results|map(attribute='instances')|list }}"
    - add_host:
        hostname={{ item.public_ip }}
        groupname="tag_Environment_{{ our_product_environment }},ec2hosts"
      with_flattened: instances

     # Usually, at this point, the group_vars tag_Environment_demo have been applied.
     # Roughly one time in 6, however, it is not applied!

    - name: Wait for instances to listen on port 22
      wait_for:
        state=started
        host={{ item.public_ip }}
        port=22
      with_flattened: instances

- hosts: ec2hosts
  gather_facts: yes
  user: myuser
  sudo: yes
  tasks:
    - debug: var=testvar
    # The value of testvar SHOULD come out as "Using demo testvar" when
    # our_product_environment is "demo" but about 1 time in 6 it comes out
    # as "This should be overwritten"
```
##### EXPECTED RESULTS

```
TASK: [add_host hostname={{ item.public_ip }} groupname="tag_Environment_{{ our_product_environment }},ec2hosts"] ***
creating host via 'add_host': hostname=54.174.179.124
added host to group via add_host module: tag_Environment_demo
added host to group via add_host module: ec2hosts

... snip ...

TASK: [debug var=testvar] *****************************************************
ok: [54.174.179.124] => {
    "var": {
        "testvar": "Using demo testvar"
    }
}
```

Should show this every time
##### ACTUAL RESULTS

I ran our playbook 22 times.

```testvar` shows as "This should be overwritten" about 1 time in every 6
