### ISSUE TITLE
Resolving relative path does not use the current directory of execution using with_file but 'command' module uses it

### ISSUE THREAD

**Issue by krsacme** [ansible/ansible#15375]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/my_modules/']
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Resolving relative path does not use the current directory of execution using with_file but 'command' module uses it.
##### STEPS TO REPRODUCE

Run below playbook using below command with one directory below the playbook yml file

```
ansible-playbook -i hosts test_path_auth_key/auth_key_path.yml -e key_path='./local_dir/new_key'
```

auth_key_path.yml

```

---
## Run this playbook using below command
# ansible-playbook -i hosts test_path_auth_key/auth_key_path.yml -e key_path='./local_dir/new_key'
- hosts: test
  user: cloud-user
  gather_facts: false
  tasks:
    - name: "Generate ssh key in local host"
      command: >
        ssh-keygen -f {{ key_path }} -N ''
        -t rsa -b 4096
      delegate_to: localhost
      args:
        creates: "{{ key_path }}"

    - name: "Copy the generated key to the host"
      authorized_key:
        user: "cloud-user"
        key: "{{ item }}"
      with_file:
        - "{{ key_path }}.pub"
      become: true
```
##### EXPECTED RESULTS

Created key should be used to authorize the user in the hosts
##### ACTUAL RESULTS

Ansible is unable to locate the created key file. Ansible is looking for the file atlocation _/home/saravanan/KRS/work/ose/ansible-test/**test_path_auth_key**/local_dir/new_key.pub_ where as the command module creates the file at _/home/saravanan/KRS/work/ose/ansible-test/local_dir/new_key.pub_

```
[saravanan@saravanankr ansible-test]$ ansible-playbook -i hosts test_path_auth_key/auth_key_path.yml -e key_path='./local_dir/new_key' -vvvv
Using /etc/ansible/ansible.cfg as config file
Loaded callback default of type stdout, v2.0

PLAYBOOK: auth_key_path.yml ****************************************************
1 plays in test_path_auth_key/auth_key_path.yml

PLAY [test] ********************************************************************

TASK [Generate ssh key in local host] ******************************************
task path: /home/saravanan/KRS/work/ose/ansible-test/test_path_auth_key/auth_key_path.yml:8
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: saravanan
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1460440992.89-180239074505523 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1460440992.89-180239074505523 `" )'
<localhost> PUT /tmp/tmp1gUdgS TO /home/saravanan/.ansible/tmp/ansible-tmp-1460440992.89-180239074505523/command
<localhost> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /bin/python /home/saravanan/.ansible/tmp/ansible-tmp-1460440992.89-180239074505523/command; rm -rf "/home/saravanan/.ansible/tmp/ansible-tmp-1460440992.89-180239074505523/" > /dev/null 2>&1'
ok: [master1.cloud.com -> localhost] => {"changed": false, "cmd": "ssh-keygen -f ./local_dir/new_key -N '' -t rsa -b 4096", "invocation": {"module_args": {"_raw_params": "ssh-keygen -f ./local_dir/new_key -N '' -t rsa -b 4096", "_uses_shell": false, "chdir": null, "creates": "./local_dir/new_key", "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "stderr": false, "stdout": "skipped, since ./local_dir/new_key exists", "stdout_lines": ["skipped, since ./local_dir/new_key exists"]}

TASK [Copy the generated key to the host] **************************************
task path: /home/saravanan/KRS/work/ose/ansible-test/test_path_auth_key/auth_key_path.yml:16
File lookup using /home/saravanan/KRS/work/ose/ansible-test/test_path_auth_key/local_dir/new_key.pub as file
fatal: [master1.cloud.com]: FAILED! => {"failed": true, "msg": "the file_name '/home/saravanan/KRS/work/ose/ansible-test/test_path_auth_key/local_dir/new_key.pub' does not exist, or is not readable"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
master1.cloud.com          : ok=1    changed=0    unreachable=0    failed=1   
```
