### ISSUE TITLE
Filter module to match sections in configuration files

### ISSUE THREAD

**Issue by ogenstad** [ansible/ansible#15403]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.1.0
config file = /Users/patrick/src/ansible-playbooks/network/ansible.cfg
configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### SUMMARY
I talked to @privateip about having a filter to check if a specific configuration exists on a device. The need is to be able to apply access-lists on IOS devices without disrupting the service in any way. In order to do this I want to apply a new access-list instead of changing the old one. However I only want to create a new access-list if it's actually needed. In the below example the {{ acl }} variable would come from a file or template.
So the goal of the playbook is to check if the desired access-list matches the actual one applied to the interface. If not I want to bump the version number with one, then create and apply the new access-list.
##### EXAMPLE PLAYBOOK
```
---
- name: Get info
  ios_command:
   commands:
     - "show ip int vlan 20 | i Inbound"
     - "show running"
   host: '{{ inventory_hostname }}'
   provider: "{{ cli }}"
  register: output
# Output is:  Inbound  access list is ACL_VLAN20_IN_V-12
- name: Set fact - Current ACL
  set_fact:
    acl_vlan_20: "{{ output.stdout[0].split()[-1] }}"
- name: Set fact - Base ACL Name
  set_fact:
    acl_vlan_20_base: "{{ acl_vlan_20.split('-')[0] }}"
- name: Set fact - Next ACL Version
  set_fact:
    acl_vlan_20_next_version: "{{ acl_vlan_20.split('-')[1]|int + 1 }}"
- name: Set fact - Next ACL Name
  set_fact:
    acl_vlan_20_next: "{{ acl_vlan_20_base }}-{{ acl_vlan_20_next_version }}"
- name: Set fact - config
  set_fact:
    config: "{{ output.stdout[1] }}"
- name: Create example ACL
  set_fact:
    acl:
     - "remark # Allow Wireless"
     - permit ip 172.29.52.32 0.0.0.31 any
     - "remark # Allow Management"
     - permit ip 172.29.50.0 0.0.0.31 any
     - "remark # Allow Wired"
     - permit ip 172.29.52.0 0.0.0.31 any
     - "remark # Allow HTTP"
     - permit tcp any any eq www
- name: Check if a new ACL is needed
  set_fact:
    update_acl: "{{ config | section(acl, parents='ip access-list extended {{ acl_vlan_20 }}') }}"
- name: Create new access-list
  ios_config:
   lines: "{{ acl }}"
   parents: ['ip access-list extended {{ acl_vlan_20_next }}']
   before: ['no ip access-list extended {{ acl_vlan_20_next }}']
   replace: block
   host: '{{ inventory_hostname }}'
   provider: "{{ cli }}"
   when: update_acl
- name: Apply new access-list
  ios_config:
   lines: "ip access-group {{ acl_vlan_20_next }} in"
   parents: ['interface Vlan20']
   host: '{{ inventory_hostname }}'
   provider: "{{ cli }}"
   when: update_acl
```
##### MISSING FEATURE
The missing feature at the moment is something this line:
update_acl: "{{ config | section(acl, parents='ip access-list extended {{ acl_vlan_20 }}') }}"
