### ISSUE TITLE
Notify {{ item }} gets called for unchanged items

### ISSUE THREAD

**Issue by bmaupin** [ansible/ansible#15421]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### OS / ENVIRONMENT

Control node: Ubuntu 14.04
Managed nodes: RHEL 6
##### SUMMARY

If I have a task that uses with_items and notify uses the item variable, I expect notify only to get called with the items that have been changed. If no items are changed, notify doesn't get called at all (as expected. However if only one item is changed, notify gets called with all items, changed or not.

May be related to #14918, but it isn't detailed enough for me to be certain.
##### STEPS TO REPRODUCE

main.yml:

```
- name: Copy reloadable IdP configuration files
  copy:
    src: ../files/idp/conf/{{ item }}
    dest: /opt/shibboleth-idp/conf/{{ item }}
  with_items:
    - access-control.xml
    - attribute-filter.xml
    - relying-party.xml
  notify:
    - Reload {{item}}
```

handlers.yml:

```
- name: Reload access-control.xml
  shell: curl -k https://localhost:1443/idp/profile/admin/reload-service?id=shibboleth.ReloadableAccessControlService

- name: Reload attribute-filter.xml
  shell: curl -k https://localhost:1443/idp/profile/admin/reload-service?id=shibboleth.AttributeFilterService

- name: Reload relying-party.xml
  shell: curl -k https://localhost:1443/idp/profile/admin/reload-service?id=shibboleth.RelyingPartyResolverService
```
##### EXPECTED RESULTS

```
TASK [../../roles/shibboleth/idp3 : Copy reloadable IdP configuration files] ***
changed: [test1] => (item=access-control.xml)
ok: [test1] => (item=attribute-filter.xml)
ok: [test1] => (item=relying-party.xml)

RUNNING HANDLER [../../roles/shibboleth/idp3 : Reload access-control.xml] ******
changed: [test1]
```
##### ACTUAL RESULTS

```
TASK [../../roles/shibboleth/idp3 : Copy reloadable IdP configuration files] ***
changed: [test1] => (item=access-control.xml)
ok: [test1] => (item=attribute-filter.xml)
ok: [test1] => (item=relying-party.xml)

RUNNING HANDLER [../../roles/shibboleth/idp3 : Reload access-control.xml] ******
changed: [test1]

RUNNING HANDLER [../../roles/shibboleth/idp3 : Reload attribute-filter.xml] ****
changed: [test1]

RUNNING HANDLER [../../roles/shibboleth/idp3 : Reload relying-party.xml] *******
changed: [test1]
```

**Comment by bcoca** [comment]
notify works on the 'total task state' not on the per item state, if any item is changed the whole task is 'changed'.

**Comment by bmaupin** [comment]
Ah, good to know. I guess in my mind when I used with_items ansible was expanding each item into its own task.

Is there a more elegant way to handle this rather than to just split out each file into separate tasks?

**Comment by bmaupin** [comment]
It took some wrangling, but using a combination of:

http://stackoverflow.com/a/25695363/399105
http://serverfault.com/a/760481/58568

I think I was finally able to get what I wanted:

defaults/main.yml:

```
reloadable_files: {
  access-control.xml: shibboleth.ReloadableAccessControlService,
  attribute-filter.xml: shibboleth.AttributeFilterService,
  attribute-resolver.xml: shibboleth.AttributeResolverService,
  relying-party.xml: shibboleth.RelyingPartyResolverService,
}
```

tasks/main.yml:

```
- name: Copy reloadable IdP configuration files
  copy:
    src: ../files/idp/conf/{{ item }}
    dest: /opt/shibboleth-idp/conf/{{ item }}
  with_items: "{{reloadable_files|list}}"
  register: files_to_reload
  notify:
    - Reload IdP configuration
```

handlers/main.yml:

```
- name: Reload IdP configuration
  shell: curl -k https://localhost:1443/idp/profile/admin/reload-service?id={{ reloadable_files[item] }}
  with_items: "{{files_to_reload.results|selectattr('changed')|map(attribute='item')|list}}"
```

Output:

```
TASK [../../roles/shibboleth/idp3 : Copy reloadable IdP configuration files] ***
changed: [test] => (item=access-control.xml)
changed: [test] => (item=attribute-resolver.xml)
ok: [test] => (item=relying-party.xml)
ok: [test] => (item=attribute-filter.xml)

RUNNING HANDLER [../../roles/shibboleth/idp3 : Reload IdP configuration] 
changed: [test] => (item=access-control.xml)
changed: [test] => (item=attribute-resolver.xml)
```
