### ISSUE TITLE
Network facts are not retrieved on Solaris

### ISSUE THREAD

**Issue by Yannig** [ansible/ansible#15446]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel_network_speed ba1c65230c) last updated 2016/04/09 11:59:29 (GMT +200)
  lib/ansible/modules/core: (detached HEAD c52f475c64) last updated 2016/04/09 11:47:06 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 5abb914315) last updated 2016/04/09 11:47:06 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Nothing special
##### OS / ENVIRONMENT

Solaris 11.3
##### SUMMARY

When launching setup module, ansible does not collect Network fact. The problem might be also the same for all BSD OS.
##### STEPS TO REPRODUCE

```
ansible -m setup -a "filter=ansible_net*" -i solaris.hosts solaris
```
##### EXPECTED RESULTS

``` yaml
solaris | SUCCESS => {
    "ansible_facts": {
        "ansible_net0": {
            "device": "net0", 
            "ipv4": [
                {
                    "address": "10.0.2.15", 
                    "broadcast": "10.0.2.255", 
                    "flags": [
...
                    ], 
                    "mtu": "1500", 
                    "netmask": "255.255.255.0", 
                    "network": "10.0.2.0"
                }
            ], 
...
```
##### ACTUAL RESULTS

```
solaris | SUCCESS => {
    "ansible_facts": { }
```
