### ISSUE TITLE
Can't get a working combination of versions for my ansible-pull workflow

### ISSUE THREAD

**Issue by AaronWilson** [ansible/ansible#15461]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0 (devel 7833b5bec4) last updated 2016/04/18 10:16:04 (GMT -700)
##### OS / ENVIRONMENT

Ubuntu
##### SUMMARY

I'm trying to use ansible-pull, but there are combating errors in the release and devel versions, so I haven't been able to find a working version.
##### STEPS TO REPRODUCE

With the release version (2.0.1.0) there seems to be a problem where running an include task seems to not run the include and also prevent subsequent tasks from running. This seems to be fixed in 2.1.0, but in the latest devel it seems like something broke in the git command run by ansible-pull. Now when I try to specify a branch I get this:

```
localhost | FAILED! => {
    "changed": false, 
    "cmd": [
        "/usr/bin/git", 
        "fetch", 
        "--depth", 
        "1", 
        "origin", 
        "+refs/heads/master:refs/heads/master"
    ], 
    "failed": true, 
    "msg": "Failed to download remote objects and refs:  X11 forwarding request failed on channel 0\r\nfatal: Refusing to fetch into current branch refs/heads/master of non-bare repository\n"
}
```

This error did not exist in 2.0.1.0. I tried versioning the ansible-modules-core back to stable-2.0, but that then gives me this error:

ERROR! invalid host (localhost) specified for playbook iteration

Is there a build that has both of these working? Or if you could point me to a fix for either, I'm happy to modify the source and recompile myself.

Here are my two files - nothing fancy going on:

local.yml:

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:

  - name: First!
    command: touch /tmp/first.txt

  - name: Include Hi
    include: playbooks/say_hi.yml

  - name: Again?
    command: echo "HI!!!!!!"
```

playbooks/say_hi.yml:

```

---
# Default playbook - just touch a file

- name: Saying Hi!
  shell: /usr/bin/touch /tmp/hello_world.txt

```
