### ISSUE TITLE
Run handlers when shutting down from `SIGTERM` or `SIGINT`

### ISSUE THREAD

**Issue by nhooey** [ansible/ansible#15460]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
2.0.1.0
```

##### SUMMARY
Ansible should run handlers when it receives `SIGTERM` or `SIGINT` so it doesn't leave the system in a bad state.
For example: If a configuration file is changed with an Ansible `copy` directive that notifies a handle to restart the process that depends on that configuration, the handler must be run the first time. If Ansible is shut down before this handler runs, since subsequent Ansible runs will notice that the new configuration has already been copied, the handler won't be notified ever again. This leaves the system in a bad state that can't be recovered from unless the service is manually restarted.

##### STEPS TO REPRODUCE
1. Run an Ansible Playbook
2. Press `CTRL+C` to send `SIGINT` or send `SIGTERM` with `kill`
3. Notice that Ansible just terminates without running handlers

##### EXPECTED RESULTS
Ansible should run handlers before shutting down.

##### ACTUAL RESULTS
Ansible shuts down without running handlers.

**Comment by resmo** [comment]
In most use cases and what most users would expect is that ansible stop on any error. However if you want to implement it the way you described, you can use the `block/rescue` paradigm:

```
---
- hosts: localhost
  tasks:
  - block:
    - shell: echo test
      notify: test
    - shell: /bin/false
    rescue:
    - meta: flush_handlers

  handlers:
  - name: test
    shell: echo handler
```

I made a proposal to run the handlers by cli after a failure: https://github.com/ansible/proposals/issues/9

**Comment by nhooey** [comment]
I think it's easier for the user if Ansible just always run handlers on `SIG(INT|TERM)`.

In the case where you don't have time or don't want Ansible to run those handlers, it could abort the re-running of those handlers when it receives a second consecutive `SIG(INT|TERM)`, and print the list of remaining handlers that didn't get a chance to run so the user can easily recover from that bad state if they wish.

However, the feature should by default automatically prevent systems from getting in to a bad state.

**Comment by resmo** [comment]
I got your point and there is   `--force-handlers`   `run handlers even if a task fails` which does pretty what you need but AFAIK it is not configurable on a play nor globally in ansible.cfg.

so it would be a simple improvement to make it configurable as default or in a play

``` yaml
- hosts: all
  force_handlers: yes
  tasks:
  ...
  handlers:
  ... 
```
