### ISSUE TITLE
Using with_indexed_items multiple times with same list causes index out of bounds error

### ISSUE THREAD

**Issue by jmcclell** [ansible/ansible#15486]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
<!--- Paste verbatim output from “ansible --version” between quotes -->
ansible 2.0.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
ansible_managed = Ansibe managed: {file} modified on %Y-%m%d %H:%M:%S
hostfile = inventory
remote_user = root

[ssh_connection]
pipelining = True
private_key_file = private/keys/ansible_key.pem
ssh_args = -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no
control_path = /tmp/ansible-ssh-%%h-%%p-%%r
```
##### OS / ENVIRONMENT

OSX, running locally to execute AWS commands to create AWS resources
##### SUMMARY

When using `with_indexed_items`, if the same variable containing a list is used for multiple tasks, the first will succeed while the second will receive a strange index out of bounds error.
##### STEPS TO REPRODUCE

In my case, I needed to create 3 subnet types, but for each one I needed one for each availability zone defined in a list of desired availability zones. So, for each subnet type, I use `with_indexed_items` on the `availability_zones` variable which is defined as `[a, b, c]`, as an example.

It appears that the internal array pointer, perhaps, is not reset between calls, thus the second task that makes use of this variable fails with an index out of bounds error. As a work around, using a filter such as `availability_zones|unique` to generate a new instance of the list for each usage of `with_indexed_items` fixes the issue.

```
<!--- Paste example playbooks or commands between quotes -->
# .... snipped ....

  vars:
    profile: aws-profile-name
    cluster_id: mesos-1
    region: us-west-2
    availability_zones: [a, b, c]

    ports:
      mesos:
        master: 5050
        slave: 5051
      consul:
        server_rpc: 8300
        serf_lan: 8301
        serf_wan: 8302
        cli_rpc: 8400
        http_api: 8500
        dns: 8600
    desired_subnet_block_mask_bits: 24
    subnet_number: 0 

# .... snipped ....

    - name: Create Consul Server Subnets
      ec2_vpc_subnet:
        # Consul Server (1 for each  AZ)
        profile: "{{profile}}"
        region: "{{region}}"
        vpc_id: "{{vpc.vpc_id}}"
        cidr: "{{ vpc_cidr|ipsubnet(desired_subnet_block_mask_bits, subnet_number | int + item[0]) }}"
        az: "{{region}}{{item[1]}}"
        resource_tags:
          "Name": "{{cluster_id}}-consul-{{ region | regex_replace('^[a-z]{2}-([a-z])[a-z]+-([0-9]{1})', '\\1\\2') }}{{item[1]}}"
          "ClusterId": "{{cluster_id}}"
      with_indexed_items:
        - "{{availability_zones}}" 
    - name: Increment subnet_number
      set_fact:
        subnet_number: "{{subnet_number | int + (availability_zones|length)}}"
    - name: Create Mesos Master Subnets
      ec2_vpc_subnet:
        # Mesos Master (1 for each  AZ)
        profile: "{{profile}}"
        region: "{{region}}"
        vpc_id: "{{vpc.vpc_id}}"
        cidr: "{{ vpc_cidr|ipsubnet(desired_subnet_block_mask_bits, subnet_number | int + item[0]) }}"
        az: "{{region}}{{item[1]}}"
        resource_tags:
          "Name": "{{cluster_id}}-master-{{ region | regex_replace('^[a-z]{2}-([a-z])[a-z]+-([0-9]{1})', '\\1\\2') }}{{item[1]}}"
          "ClusterId": "{{cluster_id}}"
      with_indexed_items:
        - "{{availability_zones}}" 
    - name: Increment subnet_number
      set_fact:
        subnet_number: "{{subnet_number | int + (availability_zones|length)}}"
    - name: Create Mesos Slave Subnets
        # Mesos Slave (1 for each AZ)
      ec2_vpc_subnet:
        profile: "{{profile}}"
        region: "{{region}}"
        vpc_id: "{{vpc.vpc_id}}"
        cidr: "{{ vpc_cidr|ipsubnet(desired_subnet_block_mask_bits, subnet_number | int + item[0]) }}"
        az: "{{region}}{{item[1]}}"
        resource_tags:
          "Name": "{{cluster_id}}-slave-{{ region | regex_replace('^[a-z]{2}-([a-z])[a-z]+-([0-9]{1})', '\\1\\2') }}{{item[1]}}"
          "ClusterId": "{{cluster_id}}"
      with_indexed_items:
        - "{{availability_zones}}" 
    - name: Increment subnet_number
      set_fact:
        subnet_number: "{{subnet_number | int + (availability_zones|length)}}"
```

##### EXPECTED RESULTS

I would expect that each task that makes use of this variable containing the list of availability zones to succeed when using `with_indexed_items` rather than the strange behavior of receiving an index out of bounds error.
##### ACTUAL RESULTS

An index out of bounds error occurs, strangely enough, on the **second** element of the list. The first and third succeed when given a list of three.

```
<!--- Paste verbatim command output between quotes -->
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/Users/jason/.ansible/tmp/ansible-tmp-1461099303.04-142909616527804/ec2_vpc_subnet", line 2456, in <module>
    main()
  File "/Users/jason/.ansible/tmp/ansible-tmp-1461099303.04-142909616527804/ec2_vpc_subnet", line 260, in main
    check_mode=module.check_mode)
  File "/Users/jason/.ansible/tmp/ansible-tmp-1461099303.04-142909616527804/ec2_vpc_subnet", line 188, in ensure_subnet_present
    subnet = create_subnet(vpc_conn, vpc_id, cidr, az, check_mode)
  File "/Users/jason/.ansible/tmp/ansible-tmp-1461099303.04-142909616527804/ec2_vpc_subnet", line 141, in create_subnet
    subnet = subnet_exists(vpc_conn, new_subnet.id)
  File "/Users/jason/.ansible/tmp/ansible-tmp-1461099303.04-142909616527804/ec2_vpc_subnet", line 126, in subnet_exists
    if subnet[0].state == "available":
IndexError: list index out of range

failed: [localhost] => (item=(1, u'b')) => {"failed": true, "invocation": {"module_name": "ec2_vpc_subnet"}, "item": [1, "b"], "parsed": false}
```
