### ISSUE TITLE
callback method playbook_on_task_start()  parameter name contains unresolved variables

### ISSUE THREAD

**Issue by visit1985** [ansible/ansible#15480]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Use of `callback_plugins/profile_tasks.py` from [jlafon/ansible-profile](https://github.com/jlafon/ansible-profile/blob/master/callback_plugins/profile_tasks.py) within playbook directory instead of modifying ansible.cfg. Not sure if this matters.
##### OS / ENVIRONMENT

```
CentOS Linux release 7.2.1511 (Core)
```
##### SUMMARY

The parameter name given to callback method playbook_on_task_start() contains unresolved variables.
This is a regression and worked in Ansible 1.9.4.
##### STEPS TO REPRODUCE

```

---
# file: playbook.yml

- name: play
  gather_facts: False
  hosts: all
  roles:
    - role: sample
```

```

---
# file: roles/sample/tasks/main.yml

- include: taskset.yml
  vars:
    sample: example
```

```

---
# file: roles/sample/tasks/taskset.yml

- name: "{{ sample }} : step1"
  debug: msg="step1"
```
##### EXPECTED RESULTS

```
TASK [sample : include] ********************************************************
[...]
TASK [sample : example : step1] ************************************************
[...]
TASK: sample : include -------------------------------------------------- 0.08s
TASK: sample : example : step1 ------------------------------------------ 0.05s
```
##### ACTUAL RESULTS

```
TASK [sample : include] ********************************************************
[...]
TASK [sample : example : step1] ************************************************
[...]
TASK: sample : include -------------------------------------------------- 0.08s
TASK: sample : {{ sample }} : step1 ------------------------------------- 0.05s
```
