### ISSUE TITLE
Ordering issue in networking modules

### ISSUE THREAD

**Issue by ogenstad** [ansible/ansible#15496]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The networking modules can change the order of the configuration when using the *_config modules. This behaviour only occur when you don't use the parents: argument in the task.
##### STEPS TO REPRODUCE

```

---
-  hosts: all
   connection: local
   gather_facts: false
   vars_files:
     - vars/creds.yml
   tasks:
     - name: Create ACL
       ios_config:
         host: "{{ inventory_hostname }}"
         provider: "{{ cli }}"
         commands:
           - access-list 140 permit ip 192.168.10.0 0.0.0.255 any
           - access-list 140 permit ip 192.168.20.0 0.0.0.255 any
           - access-list 140 permit ip 192.168.30.0 0.0.0.255 any
           - access-list 140 permit ip 192.168.40.0 0.0.0.255 any
```

##### EXPECTED RESULTS

The expected result is that this playbook should create an access-list looking like this:

```
access-list 140 permit ip 192.168.10.0 0.0.0.255 any
access-list 140 permit ip 192.168.20.0 0.0.0.255 any
access-list 140 permit ip 192.168.30.0 0.0.0.255 any
access-list 140 permit ip 192.168.40.0 0.0.0.255 any
```
##### ACTUAL RESULTS

Instead Ansible changes the order of the configuration which results in an access-list looking like this:

```
access-list 140 permit ip 192.168.30.0 0.0.0.255 any
access-list 140 permit ip 192.168.40.0 0.0.0.255 any
access-list 140 permit ip 192.168.10.0 0.0.0.255 any
access-list 140 permit ip 192.168.20.0 0.0.0.255 any
```
#### "SCREENSHOT"

```
 ansible-playbook -i hosts playbook.yml -v
No config file found; using defaults

PLAY [all] *********************************************************************

TASK [Create ACL] **************************************************************
changed: [nap-cmts-2] => {"changed": true, "responses": ["", "", "", ""], "updates": ["access-list 140 permit ip 192.168.30.0 0.0.0.255 any", "access-list 140 permit ip 192.168.40.0 0.0.0.255 any", "access-list 140 permit ip 192.168.10.0 0.0.0.255 any", "access-list 140 permit ip 192.168.20.0 0.0.0.255 any"]}
```
