### ISSUE TITLE
task with include module can't filter by tags

### ISSUE THREAD

**Issue by greyby** [ansible/ansible#15513]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /Users/user/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

`OS X Yosemite 10.10.5`
##### SUMMARY

Tags for the simple role could work.But if I use `include` in the roles, the tags can't apply to the role or `--tag` can't filter the task. I searched and found [issue 9862](https://github.com/ansible/ansible/issues/9862),but that was closed. I use version `2.0.0.2`, but that can't work.
##### STEPS TO REPRODUCE

**playbook defination**

task.yml

```

---
- name: tags test of include
  hosts: serverA
  remote_user: root
  roles:
    - { role: roleA, tags: ["roleA"]}
    - { role: roleB, tags: ["roleB"]}
```

roleA's main.yml

```

---
- name: roleA set fact 
  set_fact:
    a_variable: "test"
```

roleB's main.yml

```

---
- name: set roleB variables
  include: other.yml
```

other.yml

```

---
- name: roleB set fact 
  set_fact:
    a_variable: "test"
```

I run the command to get tasks
`ansible-playbook -i production task.yml --tags "roleA" --list-tasks`
##### EXPECTED RESULTS

```
tasks:
      roleA : roleA set fact    TAGS: [roleA]
```
##### ACTUAL RESULTS

```
tasks:
      roleA : roleA set fact    TAGS: [roleA]
      roleB : set roleB variables   TAGS: [roleB]
```
