### ISSUE TITLE
Bug with environment and `default(omit)` filter

### ISSUE THREAD

**Issue by wojtek-oledzki** [ansible/ansible#15515]
##### ANSIBLE VERSION

```
ansible 2.0.2.0
ansible 2.0.0.2
ansible 1.9.4
```
##### CONFIGURATION

no special config needed
##### OS / ENVIRONMENT

OSx and Ubuntu 14
##### SUMMARY

When using the `default(omit)` filter in `environment` instead of not setting the env when the variable is missing you get `__omit_place_holder__****`
##### STEPS TO REPRODUCE

``` YAML

---

- name: Environment and omit bug
  hosts: all

  tasks:
    - name: should not print test env
      command: env
      environment:
        TEST_SET: lorem ipsum
        TEST_NOT_SET: "{{ not_exisiting_var | default(omit) }}"
      register: result

    - debug: var=result
```
##### EXPECTED RESULTS

`TEST_NOT_SET` should not be present in the output
##### ACTUAL RESULTS

```
...
"TEST_SET=lorem ipsum",
"TEST_NOT_SET=__omit_place_holder__3cb1c4dafd1c210379e6af44973b8913aa171e8c"
...
```
