### ISSUE TITLE
Ansible GCE module: cannot use external_ip feature

### ISSUE THREAD

**Issue by loicmarie** [ansible/ansible#15514]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0 (devel ba74f5f3e5) last updated 2016/04/21 11:19:35 (GMT +200)
  lib/ansible/modules/core: (detached HEAD d83c269b82) last updated 2016/04/21 11:32:03 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 451420b7e8) last updated 2016/04/21 11:32:15 (GMT +200)
  config file = /home/loheek/Documents/workspace/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

I have not changed the ansible.cfg file
##### SUMMARY

When using gce core module, I cannot use the "external_ip" feature to fix an instance external IP. The IP setted is an ephemeral one. I tried with versions 1.9, 2.0 and 2.1 (devel)
##### STEPS TO REPRODUCE

```
- name: Create GitLab CI instance
  hosts: localhost
  connection: local

  vars:
      machine_type: g1-small # default
      image: debian-8
      zone: europe-west1-b
      network: net
      project_id: project-id
      external_ip: 192.158.31.207

  tasks:
    - name: Launch instances
      local_action:
          module: gce
          instance_names: gitlab
          machine_type: "{{ machine_type }}"
          image: "{{ image }}"
          zone: "{{ zone }}"
          network: "{{ network }}"
          disks: "gitlab"
          disk_auto_delete: false
          external_ip:
            - "{{ external_ip }}"
            - "gitlab-ip-ext"
      register: gce
```

##### EXPECTED RESULTS

I expected that the external IP setted in the Google Cloud Console was the one I wrote in my playbook with the "external_ip" key.
##### ACTUAL RESULTS

The IP chosen by Google Compute is the 'public_ip' variable in the output below for task "Launch instances". But we can see that variable external_ip has been created but not used. Where am I doing wrong ?

```
Using /home/loheek/Documents/workspace/ansible/ansible.cfg as config file
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
Loaded callback default of type stdout, v2.0

PLAYBOOK: ci.yml ***************************************************************
2 plays in ci.yml

PLAY [Create GitLab CI instance] ***********************************************

TASK [setup] *******************************************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: loheek
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1461232799.86-134795673373915 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1461232799.86-134795673373915 `" )'
<127.0.0.1> PUT /tmp/tmpQk86fK TO /home/loheek/.ansible/tmp/ansible-tmp-1461232799.86-134795673373915/setup
<127.0.0.1> EXEC /bin/sh -c 'LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python /home/loheek/.ansible/tmp/ansible-tmp-1461232799.86-134795673373915/setup; rm -rf "/home/loheek/.ansible/tmp/ansible-tmp-1461232799.86-134795673373915/" > /dev/null 2>&1'
ok: [localhost]

TASK [Launch instances] ********************************************************
task path: /home/loheek/Documents/workspace/ansible/gitlab.yml:29
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: loheek
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1461232800.49-176143373256031 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1461232800.49-176143373256031 `" )'
<localhost> PUT /tmp/tmp7UW814 TO /home/loheek/.ansible/tmp/ansible-tmp-1461232800.49-176143373256031/gce
<localhost> EXEC /bin/sh -c 'LANG=fr_FR.UTF-8 LC_ALL=fr_FR.UTF-8 LC_MESSAGES=fr_FR.UTF-8 /usr/bin/python /home/loheek/.ansible/tmp/ansible-tmp-1461232800.49-176143373256031/gce; rm -rf "/home/loheek/.ansible/tmp/ansible-tmp-1461232800.49-176143373256031/" > /dev/null 2>&1'
changed: [localhost -> localhost] => {"changed": true, "instance_data": [{"disks": ["gitlab"], "image": "debian-8-jessie-v20160418", "machine_type": "g1-small", "metadata": {}, "name": "gitlab", "network": "ci-net", "private_ip": "10.132.0.2", "public_ip": "130.211.79.216", "status": "RUNNING", "tags": [], "zone": "europe-west1-b"}], "instance_names": ["gitlab"], "invocation": {"module_args": {"credentials_file": null, "disk_auto_delete": false, "disks": ["gitlab"], "external_ip": "['192.158.31.207', 'gitlab-ip-ext']", "image": "debian-8", "instance_names": "gitlab", "ip_forward": false, "machine_type": "g1-small", "metadata": null, "name": null, "network": "ci-net", "pem_file": null, "persistent_boot_disk": false, "preemptible": null, "project_id": null, "service_account_email": null, "service_account_permissions": null, "state": "present", "tags": null, "zone": "europe-west1-b"}, "module_name": "gce"}, "state": "present", "zone": "europe-west1-b"}
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks so that the environment value uses the full variable syntax ('{{gce.instance_data}}').
This feature will be removed in a future release. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
