### ISSUE TITLE
ec2_elb_lb can not be used to create ELB and register instances in one step

### ISSUE THREAD

**Issue by windowsrefund** [ansible/ansible#15531]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible-playbook 2.1.0 (devel 33761efd19) last updated 2016/04/19 10:27:44 (GMT -400)
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

using this module with instance_ids defined will fail unless the task was previously run without the attribute. In other words, the ELB must exist in order for instances to be associated with it.
##### STEPS TO REPRODUCE

Using the documentation as an example (yes, we know the ids are fake, etc):

```
 local_action:
    module: ec2_elb_lb
    name: "test-vpc"
    scheme: internal
    state: present
    instance_ids:
      - i-abcd1234
    purge_instance_ids: true
    subnets:
      - subnet-abcd1234
      - subnet-1a2b3c4d
```
##### EXPECTED RESULTS

The test-vpc ELB will be created and the instance with id i-abcd1234 will be associated
##### ACTUAL RESULTS

The playbook blows up. Running the playbook again with the instance_ids attribute commented out will result in the ELB being created.

Running the playbook again with the uncommented instance_ids attribute will now result in the instances being associated with the ELB.
