### ISSUE TITLE
Applying "when" to roles

### ISSUE THREAD

**Issue by vasilen** [ansible/ansible#15591]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
“ansible 2.0.0.2” 
```

built from source with tag v2.0.2.0-1
##### CONFIGURATION

Default configuration, ansible.cfg untouched 
##### OS / ENVIRONMENT

"N/A"
##### SUMMARY

Using role with the "when" conditional seems to still evaluate each task in the role when the conditional is not true.  This behavior is to be expected based on the documentation "http://docs.ansible.com/ansible/playbooks_conditionals.html#applying-when-to-roles-and-includes"
What is not expected is that it fails with " 'blank' is undefined" on one of the tasks it evaluates within the role it is supposed to skip.
##### STEPS TO REPRODUCE

Run the playbook listed below with this command:
`ansible-playbook -i hosts -c local compute-1 test.yml`

test.yml (TorqueClient is not defined for compute-1)

```

---
# playbook to build an compute node
- hosts: all
  roles:
    - iptables
    - { role: torque-common, when: TorqueClient is defined }
```

role/torque-common/tasks/main.yml

```

---
# tasks file for roles/torque-common
- name: Set OS dependent variables
  include_vars: "{{ item }}"
  with_first_found:
    -  "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml"
    -  main.yml

- name: Install rpm package dependecies
  yum: state=present name="{{ item }}"
  with_items:
   - hwloc
   - hwloc-devel
   - hwloc-libs

- name: Install the torque clients pkg
  command: "{{ torque_pkg_path }}/torque-package-clients-linux-x86_64.sh --install"
  tags:
    - client

- name: Install the torque devel pkg
  command: "{{ torque_pkg_path }}/torque-package-devel-linux-x86_64.sh --install"
  tags:
    - devel

- name: Install the torque doc pkg
  command: "{{ torque_pkg_path }}/torque-package-doc-linux-x86_64.sh --install"
  tags:
    - doc

- name: Deploy trqauthd service script, torque.conf ld file, server_name, and torque.sh profile.d
  template:
    src: "{{ item.name }}"
    dest: "{{ item.destName }}"
    owner: root
    mode: "{{ item.modeState }}"
  with_items:
    - { name: 'torque.conf.j2', destName: '/etc/ld.so.conf.d/torque.conf', modeState: '0644' }
    - { name: "{{ trqauthd_src }}", destName: '{{ service_path }}/{{ trqauthd_dest }}', modeState: '0755' }
    - { name: 'torque.sh.j2' , destName: '/etc/profile.d/torque.sh', modeState: '0755' }
    - { name: 'torque.csh.j2' , destName: '/etc/profile.d/torque.csh', modeState: '0755' }
    - { name: 'server_name.j2' , destName: "{{ torque_path }}/server_name", modeState: '0755' }
```
##### EXPECTED RESULTS

I expect that the torque-common role as listed above would be skipped.  The first task in the torque-common role loads the variable definitions that are used in the rest of the task.  Since the role is supposed to be skipped, it skips the tasks as expected until it reaches the task that uses the "template" module and errors out with "is undefined" .  If it was going to fail do to "is undefined" it should have failed the first time it came across a variable, as in the first task that uses the "command" module with a variable.
##### ACTUAL RESULTS

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [compute-1]

TASK [iptables : Make sure iptables is installed, and remove firewalld] ********
ok: [compute-1] => (item={u'state': u'present', u'name': u'iptables'})
ok: [compute-1] => (item={u'state': u'present', u'name': u'iptables-services'})
ok: [compute-1] => (item={u'state': u'absent', u'name': u'firewalld'})

TASK [iptables : Copy iptables configuration] **********************************
ok: [compute-1]

TASK [iptables : Restart iptables service] *************************************
skipping: [compute-1]

TASK [torque-common : Set OS dependent variables] ******************************
skipping: [compute-1] => (item=/etc/ansible-buildtime/ansible/roles/torque-common/vars/CentOS_7.yml) 

TASK [torque-common : Install rpm package dependecies] *************************
skipping: [compute-1] => (item=[]) 

TASK [torque-common : Install the torque clients pkg] **************************
skipping: [compute-1]

TASK [torque-common : Install the torque devel pkg] ****************************
skipping: [compute-1]

TASK [torque-common : Install the torque doc pkg] ******************************
skipping: [compute-1]

TASK [torque-common : Deploy trqauthd service script, torque.conf ld file, server_name, and torque.sh profile.d] ***
fatal: [compute-1]: FAILED! => {"failed": true, "msg": "ERROR! 'service_path' is undefined"}

PLAY RECAP *********************************************************************
compute-1                    : ok=3    changed=0    unreachable=0    failed=1
```
