### ISSUE TITLE
Faulty parsing of JSON template/file lookups (aka JSON double-quotes to single-quotes conversion problem)

### ISSUE THREAD

**Issue by sgnn7** [ansible/ansible#15603]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
2.1.0
```
##### CONFIGURATION

Default from Git master
##### OS / ENVIRONMENT

Debian Jessie x86_64
##### SUMMARY

JSON `lookup('template', foobar)` content gets returned as variable that gets reparsed as dict (afaik), which somewhere gets serialized to string before it gets to the module and converts valid-JSON double-quotes to single-quotes so services or modules that expect valid JSON will fail with such data.

The problem is that Jinja2 templating is done recursively and I could not find any combination of `convert_*` arguments, Jinja2 filters, nor `#jinja2` overrides that would return the correct JSON from the template to the module and the classic override of putting a space before the string start isn't allowed when contacting AWS services. I believe the same issue exists with `lookup('file')` and any other lookup that would return JSON.

<br />

Problem code:
- https://github.com/ansible/ansible/blob/devel/lib/ansible/template/__init__.py#L333-L335
  - Returned JSON from template ends up being templated again since it starts with `{` and returns a dict.

<br/>
- Bug fix PR that was fixing the symptom in `iam_policy` module with `policy_json` arg: https://github.com/ansible/ansible-modules-core/pull/3019
- Another new (unreported yet) bug caused by this logic breaks `policy` argument in `s3_bucket` module here if you use a lookup: https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/amazon/s3_bucket.py#L211

I'd probably fix this myself but I just don't have the time to do it :(
##### STEPS TO REPRODUCE

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "AddPerm",
      "Effect": "Allow",
      "Principal": "*",
      "Action": "s3:GetObject",
      "Resource": "arn:aws:s3:::{{ item }}"
    }
  ]
}
```

```

---

- hosts: all
  connection: local
  gather_facts: False

  tasks:
    - name: Setup S3 Bucket
      s3_bucket:
        name: "{{ item }}"
        region: "us-west-2"
        policy: "{{ lookup('template','./bucket-public.json.j2', convert_data=False) }}"
        with_item:
          - some_bucket_name
```
##### EXPECTED RESULTS

JSON posted to AWS is valid and bucket is created
##### ACTUAL RESULTS

```
PLAYBOOK: deploy.yml ***********************************************************
1 plays in deploy.yml

PLAY [all] *********************************************************************

TASK [Setup S3 Bucket] *********************************************************
task path: /home/username/checkout/git-repo-name/deploy.yml:12
File lookup using /home/username/checkout/git-repo-name/bucket-public.json.j2 as file
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: username
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1461682432.3-159666311309506 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1461682432.3-159666311309506 `" )'
<localhost> PUT /tmp/tmph4kIsC TO /home/username/.ansible/tmp/ansible-tmp-1461682432.3-159666311309506/s3_bucket
<localhost> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python /home/username/.ansible/tmp/ansible-tmp-1461682432.3-159666311309506/s3_bucket; rm -rf "/home/username/.ansible/tmp/ansible-tmp-1461682432.3-159666311309506/" > /dev/null 2>&1'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"aws_access_key": null, "aws_secret_key": null, "ec2_url": null, "force": false, "name": "some_bucket_name", "policy": "{'Version': '2012-10-17', 'Statement': [{'Action': 's3:GetObject', 'Principal': '*', 'Resource': 'arn:aws:s3:::some_bucket_name', 'Effect': 'Allow', 'Sid': 'AddPerm'}]}", "profile": null, "region": "us-west-2", "requester_pays": false, "s3_url": null, "security_token": null, "state": "present", "tags": {}, "validate_certs": true, "versioning": false}, "module_name": "s3_bucket"}, "msg": "Policies must be valid JSON and the first byte must be '{'"}


NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @deploy.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by sgnn7** [comment]
Also has issues in s3_module where the resulting arg is a string (not a dict) with singlequotes:

```
- hosts: all
  connection: local
  gather_facts: False

  tasks:
    - name: Setup S3 Bucket
      s3_bucket:
        name: "{{ item }}"
        region: "us-west-2"
        policy:
          Version: '2012-10-17'
          Statement:
            - Sid: AddPerm
              Effect: Allow
              Principal: '*'
              Action: s3:GetObject
              Resource: {{ item }}
        with_items:
          - some_bucket_name
```
