### ISSUE TITLE
junos.py - xml_to_json to not convert hyphen into underscore

### ISSUE THREAD

**Issue by dgarros** [ansible/ansible#15611]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
2.1
```
##### CONFIGURATION

Nothing special 
##### OS / ENVIRONMENT

Linux Ubuntu 15.04
##### SUMMARY

While converting XML to JSON using the function `xml_to_json` in `lib/ansible/module_utils/junos.py`, hyphen are not converted to underscore. 
As a result, JSON keys contains hyphen and are not accessible from Python & Ansible

https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/junos.py#L72
##### STEPS TO REPRODUCE

``` yaml
- name: Test junos_command
  hosts: all
  connection: local
  gather_facts: no
  tasks:
    - name: "test command"
      junos_command:
        host: "{{ junos_host }}"
        port: "{{ netconf_port }}"
        commands:
          - "show interfaces terse"
      register: result
    - debug: var=result
```
##### ACTUAL RESULTS

The key `interface-information` contains a `-` and because of that it's not possible to access it in python

```
       "stdout_lines": [
            {
                "interface-information": {
                    "physical-interface": [
                        {
                            "admin-status": "up", 
                            "name": "gr-0/0/0", 
                            "oper-status": "up"
                        }, 
                        {
                            "admin-status": "up", 
                            "logical-interface": {
                                "address-family": [
                                    {
                                        "address-family-name": "inet"
                                    }, 
                                    {
                                        "address-family-name": "inet6"
                                    }
                                ], 
                                "admin-status": "up", 
                                "filter-information": "", 
                                "name": "pfe-0/0/0.16383", 
                                "oper-status": "up"
                            }, 
                            "name": "pfe-0/0/0", 
                            "oper-status": "up"
                        }, 

```

cc @privateip
