### ISSUE TITLE
Incorrect directories for SSH key files. 

### ISSUE THREAD

**Issue by 3goats** [ansible/ansible#15619]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```

I have a local directory that contains both my ssh public and private keys like this:

```
./ssh_keys
./ssh_keys/david
./ssh_keys/david/id_rsa
./ssh_keys/david/id_rsa.pub
./ssh_keys/fred
./ssh_keys/fred/id_rsa
./ssh_keys/fred/id_rsa.pub
./ssh_keys/joe
./ssh_keys/joe/id_rsa
./ssh_keys/joe/id_rsa.pub
./ssh_keys/paul
./ssh_keys/paul/id_rsa
./ssh_keys/paul/id_rsa.pub
./ssh_keys/peter
./ssh_keys/peter/id_rsa
./ssh_keys/peter/id_rsa.pub
./ssh_keys/tom
./ssh_keys/tom/id_rsa
./ssh_keys/tom/id_rsa.pub
```

I need to provision these to a bunch of SSH hosts within my environment. 
##### OS / ENVIRONMENT

Ubuntu 16.04 hosts and master.
##### SUMMARY

I need to create a playbook that can be used to push the above keys to various hosts defined in the playbooks hosts fields.

However, the .ssh key directories are getting created incorrectly. i.e. a directory called tom gets created below an id_rsa and id_rsa.pub directory.

e.g.

 `/home/tom/.ssh/id_rsa/tom/id_rsa`
##### STEPS TO REPRODUCE

```

---
 - name: provision toms keys
    hosts: ssh4.demo.com
    tasks:
     - name: ensure user tom is present
       user: name=tom state=present

     - name: ensure private key and public one are present
       copy: src=ssh_keys/tom dest=/home/tom/.ssh mode=0600
       with_items:
         - id_rsa.pub
         - id_rsa

 - name: provision toms public keys
    hosts: ssh1.demo.com

    sudo: yes
    tasks:

     - user: name=tom comment="Add tom" group=staff
     - name: Placing key
       authorized_key: user=tom key="{{ lookup('file', 'ssh_keys/tom/id_rsa.pub') }}"
```

##### EXPECTED RESULTS

 `/home/tom/.ssh/id_rsa`
 `/home/tom/.ssh/id_rsa.pub`
##### ACTUAL RESULTS

 `/home/tom/.ssh/id_rsa/tom/id_rsa`
 `/home/tom/.ssh/id_rsa/tom/id_rsa.pub`

**Comment by abadger** [comment]
I'm unable to replicate your results but I do note that there's a problem in your playbook that will lead to results that are similar.  I modified your sample playbook to use sudo for both plays.  Then when I ran it I get results on the first host of:

```
$ find .ssh -print
.ssh
.ssh/tom
.ssh/tom/id_rsa
.ssh/tom/id_rsa.pub
```

On the second host, the authorized key is placed in the correct directory:

```
 $ find .ssh -print
.ssh
.ssh/authorized_keys
```

The reason the playbook is going to the wrong place in the first playbook is that you aren't specifying where to utilize your loop variable.  So Ansible thinks that you want to copy the whole directory you've specified twice.  Change the play to look like this to fix things:

```
     - name: ensure private key and public one are present
       copy: src="ssh_keys/tom/{{ item }}" dest=/home/tom/.ssh mode=0600
       with_items:
         - id_rsa.pub
         - id_rsa
```

I'll paste the mailing list and IRC information below in case you run into further things that you're not sure if they're a bug in the code or a bug in the playbook.

# ist Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
