### ISSUE TITLE
2.0.2.0 regression in get_url using file:// urls

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#15627]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

2.0.2.0
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

In 2.0.2.0, using `get_url` with `file://` urls fails because it is
looking for an http respond code.  This worked correctly in 2.0.1.0.
##### STEPS TO REPRODUCE

`touch /tmp/srcfile` and run the following playbook:

```
- hosts: localhost
  gather_facts: false
  vars:
    url: file:///tmp/srcfile
  tasks:

    - get_url:
        url: "{{url}}"
        dest: "./destfile"
        force: true
```
##### EXPECTED RESULTS

```
PLAY ***************************************************************************

TASK [get_url] *****************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [get_url] *****************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "./destfile", "failed": true, "gid": 1000, "group": "lars", "mode": "0664", "msg": "Request failed", "owner": "lars", "response": "OK (12 bytes)", "size": 12, "state": "file", "status_code": null, "uid": 1000, "url": "file:///tmp/srcfile"}

NO MORE HOSTS LEFT *************************************************************
  to retry, use: --limit @file_urls.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```
