### ISSUE TITLE
Support defining a seed for random filter

### ISSUE THREAD

**Issue by do3cc** [ansible/ansible#15621]
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /Users/do3cc/dev/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

It would be nice to be able to provide a seed for random, so that I get a predictible random number
Use case:

```
- name: Periodic restart of workers
  cron:
    name: "restart worker {{item}}"
    minute: "{{60|random(item)}}"
    hour: */4
    job: "restart {{item}}"

```

Given that the item name does not change with each invocation, I would always get the same random number, and my cronjob would not be changed with each invocation.

**Comment by abadger** [comment]
This sounds like a good idea.  Would review a pull request to implement it.

**Comment by zarnovican** [comment]
Hi,

I'm not a Python developer, so this is just PoC implementation on 2.0.2, no tests, no doc update.

```
--- ansible/plugins/filter/core.py.orig 2016-08-25 09:48:45.427709400 +0200
+++ ansible/plugins/filter/core.py  2016-08-25 09:50:21.681681325 +0200
@@ -35,7 +35,7 @@
 import string
 from functools import partial
 import operator as py_operator
-from random import SystemRandom, shuffle
+from random import Random, SystemRandom, shuffle
 import uuid

 import yaml
@@ -178,8 +178,11 @@
     return re.escape(string)

 @environmentfilter
-def rand(environment, end, start=None, step=None):
-    r = SystemRandom()
+def rand(environment, end, start=None, step=None, seed=None):
+    if seed is None:
+        r = SystemRandom()
+    else:
+        r = Random(x=seed)
     if isinstance(end, (int, long)):
         if not start:
             start = 0
```

It is used as follows:

```
- cron:
    name: "check dirs"
    minute: "{{ 59 | random(seed=inventory_hostname) }}"
    hour: "{{ [2,3,4] | random(seed=inventory_hostname) }}"
    job: "ls -alh > /dev/null"
```
