### ISSUE TITLE
no_display: skipped|sucess|True on tasks

### ISSUE THREAD

**Issue by alform** [ansible/ansible#15622]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.1.0 (devel afc82f6beb) last updated 2016/03/25 094926 (GMT +200)
lib/ansible/modules/core (detached HEAD 7efc09ef08) last updated 2016/03/25 095049 (GMT +200)
lib/ansible/modules/extras (detached HEAD 7f9cdc0350) last updated 2016/03/25 095202 (GMT +200)
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
```

##### SUMMARY
The directive:
no_log: True
hides a task output from log.
no_display: skipped|sucess|True
would make a task completely silent. (no output at all) on task skipping, success, or at any time.
Use cases below.

##### STEPS TO REPRODUCE
```
- block:
    - foo: bar=1
    - sna: foo="snafu"
 when: bar == "baz"
 no_display: skipped
- block:
     - shell my_nifty_command
       register: status
     - set_fact: poobah="{{ status.stdout }}"
  no_display: success
```
```
```
