### ISSUE TITLE
APT module ignores when: when used with with_items

### ISSUE THREAD

**Issue by michalmedvecky** [ansible/ansible#15631]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### CONFIGURATION

```
pipelining=True
host_key_checking=False
ask_sudo_pass=False
ssh_args=-o ControlMaster=auto -o ControlPersist=60s -o ControlPath=~/.ssh/cm_socket/%r@%h:%p
inventory=~/Documents/ansible-library/inventory/
[ssh_connection]
control_path = %(directory)s/%%h-%%r
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

apt module ignores `when:` when called with `with_items`
##### STEPS TO REPRODUCE

Create test.yml playbook with this content:

```

---
- hosts: all
  tasks:
    - name: apt test
      apt: name={{item}}={{ some_version }} state=installed update_cache=yes
      with_items: [bash,mc]
      when: some_version is defined
```

run ansible-playbook test.yml -l devel:

```
blalunglaj:test-ansible misko$ ansible-playbook test.yml -l devel

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [devel]

TASK [apt test] ****************************************************************
fatal: [devel]: FAILED! => {"failed": true, "msg": "'some_version' is undefined"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
devel        : ok=1    changed=0    unreachable=0    failed=1
```
##### EXPECTED RESULTS

Task should be skipped
##### ACTUAL RESULTS

```
Ansible is complaining that some_version is undefined
```
