### ISSUE TITLE
Deleting +1 file

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#15634]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /home/ansible/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Trying to delete multiple files
##### STEPS TO REPRODUCE

```
- name: Cleanup install scripts and binaries
        file: path={{ target_path }}/xxx.bin state=absent
        file: path={{ target_path }}/yyy.ksh state=absent
        file: path={{ target_path }}/zzz state=absent


```
##### EXPECTED RESULTS

Able to delete multiple files
##### ACTUAL RESULTS

```
only one of the three files are removed.
```

I have done some deep googling with little success

Thanks

**Comment by rmauc** [comment]
the playbook error is:
[WARNING]: While constructing a mapping from /ansible/playbooks/abc.yml, line 23, column 9,
found a duplicate dict key (file).  Using last defined value only.

**Comment by rmauc** [comment]
I was hoping to delete multiple files without having to name each deletion

**Comment by xox2** [comment]
It is not a bug. It is by design.

this is runnable:

```
- name: Cleanup install scripts and binaries                                                        
  file: path={{ target_path }}/{{ item }} state=absent
  with_items:
    - xxx.bin
    - yyy.ksh
    - zzz
```
