### ISSUE TITLE
yum:  disablerepo behavior changed, skipped also installed the packages

### ISSUE THREAD

**Issue by smalenfant** [ansible/ansible#15648]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION
- default
##### OS / ENVIRONMENT

Centos 6.7
##### SUMMARY

There is a few problems related to yum in Ansible 2.0.

First, when using `disablerepo=repoid enablerepo=cdn*` and the repoid doesn't exist, the installation fails. Used to work in Ansible 1.9. Regression.

Second, when using `disablerepo=* enablerepo=cdn*`, the tasks is skipped (the tasks has a tag) and the packages gets installed. This used to NOT work in Ansible 1.9

Finding myself in a position where Ansible 1.9 and 2.0 can't work with same yum commands.
##### STEPS TO REPRODUCE

Make sure there is no repo with tags `base,updates,extras` in /etc/yum.repos.d. You also need to have a mirror (or simply rename the base tag to cdn-base for example)

```
- name: Install YUM repo package dependancies
  yum: name={{ item }} disablerepo=base,updates,extras enablerepo=cdn* state=present
  with_items:
   - yum-utils
   - libselinux-python
```
##### EXPECTED RESULTS

Expanded packages to be installed like ansible 1.9
##### ACTUAL RESULTS

```
TASK [yum-repo : Install YUM repo package dependancies] ************************
failed: [cdn1cdes0001.coxlab.net] (item=[u'yum-utils', u'libselinux-python']) => {"failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": "base,updates,extras", "enablerepo": "cdn*", "exclude": null, "install_repoquery": true, "list": null, "name": ["yum-utils", "libselinux-python"], "state": "present", "update_cache": false}, "module_name": "yum"}, "item": ["yum-utils", "libselinux-python"], "msg": "Failure talking to yum: Error getting repository data for base, repository not found"}

```

Output from Ansible 1.9.2 :

```
TASK: [yum-repo | Install YUM repo package dependancies] **********************
ok: [cdn1cdes0001.coxlab.net] => (item=yum-utils,libselinux-python
```
##### Additional comments, Skipped when was actually changed.

I'm a bit confused here. I changed disablerepo=\* and it worked. But the task was **skipped** and the **packages** got installed. This actually doesn't work in Ansible 1.9.x. I'm finding myself

```
- name: Install YUM repo package dependancies
  yum: name={{ item }} disablerepo=* enablerepo=cdn* state=present
  with_items:
   - yum-utils
   - libselinux-python
```

```
TASK [yum-repo : Install YUM repo package dependancies] ************************
skipping: [cdn1cdes0001.coxlab.net] => (item=[u'yum-utils', u'libselinux-python'])

/var/log/yum.log :
Apr 28 09:57:28 cdn1cdes0001 ansible-yum: Invoked with name=['yum-utils', 'libselinux-python'] list=None install_repoquery=True conf_file=None disable_gpg_check=False state=present disablerepo=* update_cache=False enablerepo=cdn* exclude=None
Apr 28 09:57:29 cdn1cdes0001 yum[6170]: Installed: libselinux-python-2.0.94-5.8.el6.x86_64
Apr 28 09:57:29 cdn1cdes0001 yum[6170]: Installed: yum-utils-1.1.30-30.el6.noarch
```
