### ISSUE TITLE
The ios_config module does not delete the username from the router

### ISSUE THREAD

**Issue by ubajze** [ansible/ansible#15654]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.0.1.0
```
##### CONFIGURATION

No configuration.
##### OS / ENVIRONMENT

Working on Ubuntu, release trusty. The issue is not platform dependent.
##### SUMMARY

When using command "no username" with ios_config module, the task timeouts. 
##### STEPS TO REPRODUCE

I am using the following task configuration in the playbook. 

```
    - name: Delete users
      ios_config:
        host: "{{ ansible_ssh_host }}"
        username: "{{ username }}"
        password: "{{ password }}"
        lines:
          - no username admin
```

The result of the task is:

```
TASK [Delete users] ************************************************************
fatal: [hub]: FAILED! => {"changed": false, "commands": ["configure terminal", "no username admin"], "failed": true, "msg": "timeout trying to send command"}
```

The reason for this is that Cisco ask for confirmation when deleting the username from the configuration.

```
R2(config)#no username admin
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]
R2(config)#
```

##### EXPECTED RESULTS

It is expected that command should be deleted from the configuration.
##### ACTUAL RESULTS

```
fatal: [wan1]: FAILED! => {"changed": false, "commands": ["configure terminal", "no username admin"], "failed": true, "invocation": {"module_args": {"after": null, "auth_pass": null, "authorize": false, "before": null, "config": null, "force": false, "host": "192.168.35.152", "lines": ["no username admin"], "match": "line", "parents": null, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": 22, "provider": null, "replace": "line", "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"}, "module_name": "ios_config"}, "msg": "timeout trying to send command"}
```
