### ISSUE TITLE
when conditional is ignored  while working with win_get_url

### ISSUE THREAD

**Issue by ZahiCahana** [ansible/ansible#15684]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### SUMMARY

"when" conditional is ignored  while working with win_get_url
i have a generic playbook that runs on linux and windows (using when conditional).
while running it on linux (centos) it runs also a task that should run only on windows with the condition below 

when: "'windows' in group_names "
##### STEPS TO REPRODUCE

```
- name: download artifact from artifactory for windows. ansible 2.0
  win_get_url:
    url: '{{env_all_base_artifactory_url}}/simple/{{env_all_artifact_repo_key}}/{{artifact_group}}/{{artifact_name}}/{{inp_deploy_version}}/{{artifact_name}}-{{inp_deploy_version}}.zip'
    dest: '{{role_base_winpackage_location}}\{{artifact_name}}-{{inp_deploy_version}}.zip'
    username: '{{env_all_env_artifactory_username}}'
    password: '{{env_all_env_artifactory_userpassword}}'
    when: "'windows' in group_names"
```
##### EXPECTED RESULTS

Conditional check failed", "skipped": true
##### ACTUAL RESULTS

it tries to run windows task on linux

TASK [getartifact : download artifact from artifactory for windows. ansible 2.0] ***
task path: /mnt/ansible/builderon/rndv-ci1/deployment/code/roles/getartifact/tasks/main.yml:32
fatal: [rndv-ci1-tel01]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

```
<!--- Paste verbatim command output between quotes -->
```
