### ISSUE TITLE
yum upgrade overly verbose...

### ISSUE THREAD

**Issue by richard-scott** [ansible/ansible#15699]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
[vagrant@recon ~]$ ansible --version
ansible 2.0.2.0
  config file = /home/recon/Vagrant/.ansible.cfg
  configured module search path = Default w/o overrides
[vagrant@recon ~]$ cat /home/recon/Vagrant/.ansible.cfg
[defaults]
host_key_checking = False
roles_path = /etc/ansible/roles
[vagrant@recon ~]$
```
##### OS / ENVIRONMENT

```
[vagrant@recon ~]$ cat /etc/redhat-release
Scientific Linux release 7.2 (Nitrogen)
[vagrant@recon ~]$
```
##### SUMMARY

Running this task:

```
  tasks:
    - name: Distribution Upgrade.
      become: true
      yum: name=* state=latest
```

is extreamly verbose compared to similar on Debian:

```
  tasks:
    - name: Distribution Upgrade.
      become: true
      apt: upgrade=dist update_cache=yes cache_valid_time=3600
```

To keep things consistent does 'apt' on Debian need to get more verbose, or is 'yum' on CentOS too talkative?
