### ISSUE TITLE
Ansible hangs on CentOS but not Debian when activating auto-sudo

### ISSUE THREAD

**Issue by richard-scott** [ansible/ansible#15703]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
[vagrant@recon ~]$ ansible --version
ansible 2.0.2.0
  config file = /home/recon/Vagrant/.ansible.cfg
  configured module search path = Default w/o overrides
[vagrant@recon ~]$ cat /home/recon/Vagrant/.ansible.cfg
[defaults]
host_key_checking = False
roles_path = /etc/ansible/roles
[vagrant@recon ~]$
```
##### OS / ENVIRONMENT

```
Host:
[vagrant@recon ~]$ cat /etc/redhat-release
Scientific Linux release 7.2 (Nitrogen)
[vagrant@recon ~]$

Guest: Centos-7 and Debian 8
```
##### SUMMARY

Running this task:

```
  tasks:
    - name: Update ~vagrant/.bashrc
      lineinfile: dest=~vagrant/.bashrc line="{{ item }}"
      with_items:
        - "sudo su -"
        - "exit"
```

On CentOS this hangs after the initial "sudo" line is added but on Debian it works just fine.
Oh, and "sudo su -" works just fine when running in the guest OS manually.
