### ISSUE TITLE
wait_for will not accept both port and path; should say so in documentation

### ISSUE THREAD

**Issue by setha45** [ansible/ansible#15732]
##### ISSUE TYPE
Documentation Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.0.1.0
config file = /root/.ansible.cfg
configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Running ansible on CentOS Linux release 7.2.1511 (Core)
Managing a system on CentOS release 5.5 (Final)

##### SUMMARY
wait_for will not accept both port and path.  The documentation should note that restriction

##### STEPS TO REPRODUCE
Construct a playbook similar to the following.  seths_46 is one of my test VM systems.  When duplicating this bug, use one of your test systems instead.
```
---
- hosts: seths_46
  gather_facts: false
  strategy: free
  tasks:
  - wait_for: host={{ inventory_hostname }} path="/adp/etc/rc2.d/s099upwrapup" port=22 delay=1 timeout=1800
```

##### EXPECTED RESULTS
I wanted Ansible to wait for the port to be open and then for the filename in the path to exist.  If Ansible cannot do that, then the documentation should say so.

##### ACTUAL RESULTS
```
TASK [wait_for] ****************************************************************
fatal: [<ip address deleted>]: FAILED! => {"changed": false, "failed": true, "msg": "port and path parameter can not both be passed to wait_for"}
```
