### ISSUE TITLE
If managed system reboots, shell module does not return rc value; documentation should say so

### ISSUE THREAD

**Issue by setha45** [ansible/ansible#15741]
##### ISSUE TYPE
Documentation Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.0.1.0
config file = /root/.ansible.cfg
configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Running ansible on CentOS Linux release 7.2.1511 (Core)
Managing a system on CentOS release 5.5 (Final)

##### SUMMARY
If managed system reboots, shell module does not return rc value; documentation should say so

##### STEPS TO REPRODUCE
**Note that Ansible is working as it should in this case.  The documentation should be fixed.  Please don't break Ansible to match the documentation.**
Say you are rebooting a managed system because of an OS upgrade.  You run a playbook which runs a shell script on the system to detect that the upgrade completed successfully, or that the upgrade failed.  There may be zero or more reboots depending on the success or failure of the upgrade.  Your playbook has to rerun the shell script after a reboot to again look for indications that the upgrade succeeded or failed.  You add a register variable to the task which runs the shell script.  When the system reboots, the register variable does not have a .rc dict item.  However, the documentation at http://docs.ansible.com/ansible/shell_module.html says that .rc is always returned.  The documentation is incorrect and should be fixed.  Suggested fix: tell the reader to use the "is undefined" test like in the following block:
```
 - block:
      # Calls the pollit script to wait for either a successful
      # or non-successful upgrade.
    - name: call the pollit shell script
      shell: /tmp/auto_upgrade_files/pollit
      register: pollit_results
      # Necessary in case the remote system rebooted.  Note that
      # this contradicts how Ansible says this should work at
      # http://docs.ansible.com/ansible/shell_module.html.  In
      # the documentation, it says that .rc is always returned.
    - fail: msg="Remote system probably rebooted"
      when: pollit_results.rc is undefined
    - fail: msg="Nonzero return from remote system"
      when:  pollit_results.rc != 0
```

##### EXPECTED RESULTS
I expected the rc value to exist, based on the documentation.  That led me to staring at the code for a time.  I then used debug to output the pollit_results with no .rc suffix.  The way Ansible actually works is the way it **should** work.  The way Ansible works now lets me tell whether the shell script ran to completion or not.  Just fix the documentation so that the next person knows what to look for.

##### ACTUAL RESULTS
```
FAILED! => {"failed": true, "msg": "The conditional check \'pollit_results.rc != 0\' failed. The error was: error while evaluating conditional (pollit_results.rc != 0): \'dict object\' has no attribute \'rc\'"}\x1b[0m\n\n
```
which led me to looking at the code and the manual and saying, "huh?" for a while.
