### ISSUE TITLE
Apt upgrade: "full" not bothering held packages.

### ISSUE THREAD

**Issue by doertedev** [ansible/ansible#15751]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /home/doertedev/Code/saas/ansible.cfg
  configured module search path = modules
```
##### CONFIGURATION

[defaults]
timeout = 120
transport = ssh
sudo_flags = -E -H
host_key_checking=False
private_key_file=~/.ssh/id_ed25519
inventory=hosts/ec2.py
pipelining=False
hash_behaviour=merge
callback_plugins = callback_plugins
filter_plugins = filter_plugins
action_plugins = action_plugins
library = modules
roles_path = roles
retry_files_enabled = False

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=~/.ansible/cp/.%h-%p-%r
-->
##### OS / ENVIRONMENT

Running from a Gentoo platform on Ubuntu Trusty 14.04.
##### SUMMARY

When I mark an apt package on "hold" it shouldn't be touched by upgrade mechanisms. It sadly is being touched by an ansiblish dist-upgrade though.
##### STEPS TO REPRODUCE

``` yaml

---

  - name: "test"
    hosts: ":tag_Name_cassandra*"
    gather_facts: no
    serial: 3
    tasks:
      - raw: apt-mark hold cassandra
        become: yes
      - apt: update_cache=yes
        become: yes
      - name: "ensure installed packages are upgraded"
        apt:
          upgrade: "full"
        become: yes
```
##### EXPECTED RESULTS

`dpkg -l cassandra` == 2.2.5 (what was installed before)
##### ACTUAL RESULTS

`dpkg -l cassandra` == 3.0.5 (what's currently up2date on the repo which can be checked via `apt-cache policy cassandra`.
