### ISSUE TITLE
Ansible fails to delete temporary files when passing --diff

### ISSUE THREAD

**Issue by dbarrosop** [ansible/ansible#15777]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /Users/dbarroso/workspace/ansibly/ansible.cfg
  configured module search path = library
```
##### CONFIGURATION

```
[defaults]
hostfile = inventory/ipamd_list.py
remote_user = ansible
library = library
retry_files_enabled = False
```
##### OS / ENVIRONMENT

Linux
##### SUMMARY

If you pass the `--diff` option and there is a change on the file some temporary files are not deleted.
##### STEPS TO REPRODUCE

Using a playbook like the following:

```

---
- name: Playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/env python"

  tasks:
    - template: src=deleteme.j2 dest=/tmp/deleteme
```

Execute:

```
$ ansible-playbook test.yml --limit a_host --diff

PLAY [Playbook] ***************

TASK [template] ****************************************************************
changed: [a_host]
--- before: /tmp/deleteme
+++ after: dynamically generated
@@ -1 +1,2 @@
 asdsa
+asd


PLAY RECAP *********************************************************************
a_host         : ok=1    changed=1    unreachable=0    failed=0
```

On the host:

```
[ansible@a_host tmp]$ ls -la
total 0
drwxr-xr-x 4 ansible ansible 80 May  9 12:41 .
drwxr-xr-x 3 ansible ansible 60 Apr  7 04:30 ..
drwxr-xr-x 2 ansible ansible  60 May  9 12:41 ansible-tmp-1462797676.15-127764364058026
drwxr-xr-x 2 ansible ansible  60 May  9 12:41 ansible-tmp-1462797679.81-189434426701515
```
##### EXPECTED RESULTS

`tmp` folder should be empty after the execution of the playbook has finished.
##### ACTUAL RESULTS

`tmp` folder is not empty.
