### ISSUE TITLE
Write ansible-pull script (or playbook) for configuring pull based usage

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#158]
Some folks would like a pull architecture if they have a severe amount of nodes.

It would work like this internally but be really simple for people to apply.

Use ansible to install ansible and ansible-pull script on all nodes.   (from package, whatever)

Use ansible to add ansible-pull to crontab with arguments

ansible-pull takes the address of a git repo to suck down and then runs a top level playbook in that repo, logging to a known log file.

Ansible pull invokes the playbook with --connection=local

Periodically, ansible-fetch can be used to suck down logfiles and see how things went.

For bonus points, make a script/playbook/called ansible-fetch-setup that is used to push ansible down to the remote nodes, which takes as parameters the git repo and cron frequency.

This probably lives as a seperate project and does not rely on Python API interfaces and just calls ansible's command line.   It MAY be implementable easy enough as just a playbook to run on the server to set it up, and a script to template out :)

**Comment by sfromm** [comment]
Is _/var/lib/ansible/local_ a sensible location to check out a git repository?

**Comment by mpdehaan** [comment]
Sounds as good as anything I can think of, sure.

Does this mean you want to take this one?  Have at, if you like.

**Comment by sfromm** [comment]
Thinking about it :)

**Comment by sfromm** [comment]
Go ahead and assign this to me.  I'll follow up with some specifics for you to comment on.

**Comment by mpdehaan** [comment]
yours, enjoy!

**Comment by sfromm** [comment]
Posting here for comment before I commit my changes and push to github.

The playbook for deployment is pretty straightforward:

```
---
- hosts: all 
  user: root
  vars:
    # schdule is fed directly to cron
    schedule: '*/15 * * * *'
    # Directory to where repository will be cloned                              
    workdir: /var/lib/ansible/local
    # Repository to check out
    repo_url: git://github.com/sfromm/ansible-playbooks.git
  tasks:
    - name: Install ansible
      action: yum pkg=ansible state=installed
    - name: Create local directory to work from
      action: file path=$workdir state=directory owner=root group=root mode=0755    
    - name: Create crontab entry to clone/pull git repository
      action: template src=templates/ansible-pull.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644
```

And the template:

```
# Cron job to git clone/pull a repo and then run locally
{{ schedule }} root ansible-pull -d {{ workdir }} -U {{ repo_url }}   
```

Lastly, ansible-pull does two things:
1. Create a runner to run the git module for the local checkout.  It massages the _module_args_ as necessary, sets _pattern_ to _localhost_, and sets _transport_ to local.
2. Runs the _local.yml_ playbook in the git checkout with Playbook, with _transport_ set to local.  Right now, I set _host_list_ to a list of names: localhost, the host's fqdn, and its hostname.  This is problematic because it will run a playbook 3 times if it specifies _hosts: all_.  Do you have suggestons?  Setting this to just localhost does not seem practical.  Using the hostname or fqdn may tie in nicely with the recent group_names addition.

If it would help to see the code, let me know.

**Comment by mpdehaan** [comment]
Sounds good except for the 3 hosts part, yeah, let's see the src.  I would think you just want -O?

**Comment by mgwilliams** [comment]
Here's a somewhat different (module based) approach:

``` yaml
- hosts: all
  vars:
    schedule: '*/15 * * * *'
    workdir: /var/lib/ansible/local
    repo_url: git://github.com/sfromm/ansible-playbooks.git
    ansible_egg: http://github.com/ansible/ansible/tarball/master
    playbook: {{ configure_apache.yaml }}

  tasks:
  - name: setup/run ansible remotel
    action: ansible-pull workdir={{ workdir }} repo_url={{ repo_url }} playbook={{ playbook }} [schedule={{ schedule }}] [user=root] [group=root] [ansible={{ ansible_egg }}]
```

ansible-pull is a regular ansible module that is invoked from the overlord, and performs the following tasks:
- Detects OS and uses the native package manager to install git, if needed
- Installs ansible (from the indicated egg), and any dependencies, if needed
- Creates the working directory, if needed
- Clones the repo_url into the working directory (e.g., /var/lib/ansible/local/repo) _or_ does a git pull on an existing clone
- Runs the indicated playbook (configure_apache.yml) by invoking ansible (inside a shell as user/group):

```
        ansible-playbook configure_apache.yaml --connection=local
```
- If schedule is provided, create a cron job to git pull & run

Does this make any sense? Miss anything the other method(s) are providing? I don't think this method would require any changes to ansible proper.
