### ISSUE TITLE
Using lineinfile for a file insert in Ansible  playbook 

### ISSUE THREAD

**Issue by engbalaji** [ansible/ansible#15813]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.0.0.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

"None, not touching anythign in the ansible.cfg file"
##### OS / ENVIRONMENT

"Redhat 2.6.39-400.109.4.el6uek.x86_64"
##### SUMMARY

While using the string for replacement using the lineinfile command getting following error

```
The error appears to have been in '/data/roles/wls1024/vars/main.yml': line 33, column 44, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - regexp: "ADMIN_PORT"
    line: "admin_port=int(os.environ.get( "ADMIN_PORT","{{WEBSERVER_PORT}}" ))"
                                           ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}" "
```
##### STEPS TO REPRODUCE

"values in the vars/main.yml file

```
WLS_PORT_PASSWD:
  - regexp: "ADMIN_PASSWORD"
    line: "admin_pass=os.environ.get("ADMIN_PASSWORD","{{ WEBLOGIC_ADMIN_PASSWORD }}")"
  - regexp: "ADMIN_PORT"
    line: "admin_port=int(os.environ.get("ADMIN_PORT","{{ WEBSERVER_PORT }}"))"
```

values in the tasks/mail.yml file

```
 - name: Configure the weblogic port and passwords
   lineinfile:
    dest: "{{ORACLE_BASE}}/wlsDcreation.py"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
   with_items: "{{ WLS_PORT_PASSWD  }}"
```

files template where actual file is support to change during the playbook run

```
admin_port   = int(os.environ.get("ADMIN_PORT", "8001"))
admin_pass   = os.environ.get("ADMIN_PASSWORD", "welcome1") "
```

"ansible-playbook -i wls_hosts wls1034install.yml -k -vvv"
##### EXPECTED RESULTS

"suppose to change the variable in the config file as below

```
admin_port   = int(os.environ.get("ADMIN_PORT", "8001"))
admin_pass   = os.environ.get("ADMIN_PASSWORD", "welcome1")"
```
##### ACTUAL RESULTS

```
Error while running the playbook:

ERROR! Syntax Error while loading YAML.


The error appears to have been in '/data/roles/wls1024/vars/main.yml': line 33, column 39, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - regexp: "ADMIN_PASSWORD"
    line: "admin_pass=os.environ.get("ADMIN_PASSWORD","{{ WEBLOGIC_ADMIN_PASSWORD }}")"
                                      ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

```

**Comment by ansibot** [comment]
@engbalaji Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
Can be resolved by including single quote instead of double quote or by escaping double quotes 

1. 
```yaml
WLS_PORT_PASSWD:
  - regexp: "ADMIN_PASSWORD"
    line: 'admin_pass=os.environ.get("ADMIN_PASSWORD","{{ WEBLOGIC_ADMIN_PASSWORD }}")'
  - regexp: "ADMIN_PORT"
    line: 'admin_port=int(os.environ.get("ADMIN_PORT","{{ WEBSERVER_PORT }}"))'
```

2. 
```yaml
WLS_PORT_PASSWD:
  - regexp: "ADMIN_PASSWORD"
    line: "admin_pass=os.environ.get(\"ADMIN_PASSWORD\",\"{{ WEBLOGIC_ADMIN_PASSWORD }}\")"
  - regexp: "ADMIN_PORT"
    line: "admin_port=int(os.environ.get(\"ADMIN_PORT\",\"{{ WEBSERVER_PORT }}\"))"
```
