### ISSUE TITLE
role parameters replaced

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#15823]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
 2.0.1.0
```
##### CONFIGURATION

```
[defaults]
retry_files_save_path = ./retry/
roles_path = ./roles:~/ansible/roles
ansible_managed = Ansible managed: file modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
nocows = 1
callback_whitelist = timer
sudo_flags = -E
stdout_callback = skippy
display_skipped_hosts = False
```
##### OS / ENVIRONMENT

Mac OS => Linux
##### SUMMARY

Role gets wrong parameter values
##### STEPS TO REPRODUCE

```
playbook.yml
a
├── defaults
│   └── main.yml
└── tasks
    └── main.yml
b
└── meta
    └── main.yml
```

playbook.yml:

``` yml
- hosts: localhost
  become: no
  gather_facts: no
  roles:
      - role: b
      - role: a
```

a/defaults/main.yml:

``` yml
var: 1
```

a/tasks/main.yml:

``` yml
- debug: msg="var={{ var }}"
```

b/meta/main.yml:

``` yml
dependencies:
    - role: a
      var: 3
```
##### EXPECTED RESULTS

```
TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "msg": "var=3"
}

TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "msg": "var=1"
}
```
##### ACTUAL RESULTS

```
TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "msg": "var=3"
}

TASK [a : debug] ***************************************************************
ok: [localhost] => {
    "msg": "var=3"
}
```
