### ISSUE TITLE
scp_if_ssh not respected in copy and template modules if in a loop

### ISSUE THREAD

**Issue by smiller171** [ansible/ansible#15839]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### SUMMARY

If using the copy or template modules in a loop, `scp_if_ssh = True` is not respected.  
The setting is respected when not using a loop.
##### STEPS TO REPRODUCE
1. Disable SFTP on target host
2. set `scp_if_ssh = True` in .ansible.cfg

```
- Name: Test copy loop
  copy:
      src: "{{item}}"
      dest: "/tmp/{{item}}"
  with_items:
  - foo
  - bar
```

##### EXPECTED RESULTS

Expect Foo and Bar to be copied to remote server with scp
##### ACTUAL RESULTS

Get an error about sftp being disabled. I no longer have access to the system that this was occurring on. Will try to reproduce on a VM and update this issue.

If I create a separate task for each file this works.
