### ISSUE TITLE
Saving content of big variable to local file takes too long time/or maybe is somehow broken

### ISSUE THREAD

**Issue by jhutar** [ansible/ansible#15856]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
# ansible --version
ansible 1.9.4
  configured module search path = None
```
##### CONFIGURATION

Nothing specific besides custom `private_key_file` and `host_key_checking = False`
##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7 on all involved machines
##### SUMMARY

Saving content of big variable to local file takes too long time/or maybe is somehow broken.
##### STEPS TO REPRODUCE

In one task I have delegated to machine B I'm running `lsof` which returns about 20MB big stdout in my case. In next step I want to save it to local file on a system running the playbook. This causes CPU go to 100% for a too long time (I have never waited more than 15 minutes and then Ctrl+C the playbook). When using scp to transport that file it takes less than few seconds as all nodes are on 10GB link.

```
    - name: "Gather lsof on B"
      delegate_to: "{{ b }}"
      command: lsof
      register: lsof_command
      run_once: true
    - name: "Save lsof log from B"
      local_action:
        copy content="{{ lsof_command.stdout }}" dest="/root/lsof-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}-{{ ansible_date_time.tz }}.log"
      run_once: true
```
##### EXPECTED RESULTS

It should be faster to save the content (I believe data are already available locally as I have seen them when running with `-vvv`)
##### ACTUAL RESULTS

Step "Save lsof log from B" hangs for >15 minutes and eats one CPU during that time. I do not know if it would actually finish if I would let it be.

**Comment by sivel** [comment]
I imagine part of this is due to how task arguments are passed to the python script that will actually perform the work.

The arguments to a task get serialized into JSON and then stuffed inside of a python file as a variable.  That python script is then executed, it then has to load that variable, turn the JSON string data into a python object, and then writes the contents of that argument into a file.

It may be more efficient for you to have `gather lsof on B` redirect to a tmp file in the command (which requires the shell module instead of command) such as:

```
    - name: "Gather lsof on B"
      delegate_to: "{{ b }}"
      shell: "lsof > /tmp/{{ ansible_date_time.date }}-{{ ansible_date_time.time }}-{{ ansible_date_time.tz }}.log"
      run_once: true

    - name: "Save lsof log from B"
      local_action:
        copy src="/tmp/{{ ansible_date_time.date }}-{{ ansible_date_time.time }}-{{ ansible_date_time.tz }}.log" dest="/root/lsof-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}-{{ ansible_date_time.tz }}.log"
      run_once: true
```
