### ISSUE TITLE
Variable value in "vars_files" can not be found in "wait_for" task.

### ISSUE THREAD

**Issue by simonschuang** [ansible/ansible#15868]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### CONFIGURATION

no change
##### OS / ENVIRONMENT

Ubuntu 14.04.4 LTS
##### SUMMARY

When executing a playbook with "inventory_hostname" as part of file name of "vars_files". I assume ansible can find the "vars_files" and execute "wait_for" for waiting servers start after a reboot.
##### STEPS TO REPRODUCE

write a playbook with vars_files like below:
reboot.yml

```

---
- name: reboot
  hosts: servers
  remote_user: core
  roles:
    - reboot-wait
  sudo: yes
  vars_files:
    - "vars/env_vars_{{ inventory_hostname }}.yml"
```

write a task file to reboot server and wait for the server start.
tasks/main.yml

```

---
- name: Restart machine
  shell: shutdown -r 1

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} port=22 state=started timeout=300
```

execute ansible playbook 

```
ansible-playbook -i hosts reboot-wait.yml
```

The reboot task success, but error raised for vars_files not found while executing wait_for task.

```
TASK [reboot-wait : Restart machine] ************************************
changed: [192.168.33.47]
ERROR! vars file vars/env_vars_{{ inventory_hostname }}.yml was not found
```
##### EXPECTED RESULTS

ansible should wait for server reboot.
##### ACTUAL RESULTS

The server actually rebooted, but ansible can not wait for server reboot.
