### ISSUE TITLE
sychronize rsync_opts and --private-key= will send two --rsh arguments

### ISSUE THREAD

**Issue by jctanner** [ansible/ansible#15907]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
synchronize module

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0 (TEST_RSYNC_SSHKEY 42f6114b61) last updated 2016/05/17 19:11:57 (GMT -400)
  lib/ansible/modules/core: (devel 67de0675c3) last updated 2016/05/17 19:12:01 (GMT -400)
  lib/ansible/modules/extras: (devel e8391d6985) last updated 2016/05/17 19:12:06 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

fedora 23 controlhost
##### SUMMARY

rsync_opts with "-i keyfile" combined with --private-key= on the ansible cli, will construct two --rsh arguments to the rsync command.
##### STEPS TO REPRODUCE

```
- hosts: foohost
  gather_facts: False
  user: admin
  #connection: local
  tasks:
    - name: push with become to different remote user and delegate to different host
      synchronize:
        mode: push
        src: /tmp/foo
        dest: /tmp/foo_
        rsync_opts: --rsh "ssh -o PasswordAuthentication=no -i /home/admin/.ssh/id_rsa.bak"
/.ssh/id_rsa.bak"
      become: yes
      become_user: admin
      become_method: su  
      delegate_to: barhost

```
##### EXPECTED RESULTS

Only a single --rsh option.

##### ACTUAL RESULTS

Verbose output ...

```
changed: [barhost-> foohost] => {"changed": true, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh -i /home/jtanner/.ssh/id_rsa -S none -o StrictHostKeyChecking=no' --rsh \"ssh -o Pass
wordAuthentication=no -i /home/admin/.ssh/id_rsa.bak\" --out-format='<<CHANGED>>%i %n%L' \"/tmp/foo\" \"foohost:/tmp/foo_\"", "invocation": {"module_args": {"_local_rsync_path": "rsync", "_substitute_controller": false, "archive":
 true, "checksum": false, "compress": true, "copy_links": null, "delete": false, "dest": "foohost:/tmp/foo_", "dest_port": 22, "dirs": false, "existing_only": false, "group": null, "links": null, "mode": "push", "owner": null, "part
ial": false, "perms": null, "private_key": "/home/jtanner/.ssh/id_rsa", "recursive": null, "rsync_opts": ["--rsh \"ssh -o PasswordAuthentication=no -i /home/admin/.ssh/id_rsa.bak\""], "rsync_path": null, "rsync_timeout": 0, "set_remote_user": true, "sr
c": "/tmp/foo", "ssh_args": null, "times": null, "verify_host": false}}, "msg": ".d..t...... foo/\n<f..t...... foo/1\n<f..t...... foo/2\n<f..t...... foo/3\n", "rc": 0, "stdout_lines": [".d..t...... foo/", "<f..t...... foo/1", "<f..t...... foo/2", "<f..t.
..... foo/3"]}
```
