### ISSUE TITLE
cpu_set in ansible docker module does not work as expected

### ISSUE THREAD

**Issue by huikang** [ansible/ansible#15910]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 14.04.4 LTS
##### SUMMARY

The cpu_set parameter in docker module does not impact the cpus execution of the container.
##### STEPS TO REPRODUCE

```
- name: start a container and pin to cpu 0,1,2
  docker:
    name: test-container
    image: ubuntu
    pull: always
    privileged: yes
    net: host
    detach: True
    state: started
    cpu_set: "0,1,2"
```

```
<!--- Paste example playbooks or commands between quotes -->
```

##### EXPECTED RESULTS

docker inspect test-container

The output should cpu cpuset is 0,1,2
##### ACTUAL RESULTS

cpuset: ""

```
<!--- Paste verbatim command output between quotes -->
```
