### ISSUE TITLE
do-until loops broken when used with lookup plugins

### ISSUE THREAD

**Issue by Lowess** [ansible/ansible#15914]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = ~/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Nothing special.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

It looks like lookup statements are not parsed properly when used with do-until loop statement. 

Ansible throws an error like: 

```
[localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'rand_result.stdout.find('3') != -1 or '{{ lookup('pipe'' failed. The error was: template error while templating string: unexpected end of template, expected ','.. String: rand_result.stdout.find('3') != -1 or '{{ lookup('pipe'"}
```

It is working with Ansible 2.0.1.0 but not with Ansible 2.0.2.0, Is there a need to adjust the use of `{{ }}`?
##### STEPS TO REPRODUCE

I am able to run the following playbook with Ansible 2.0.1.0 but not with 2.0.2.0:

``` yaml

---
- hosts: localhost
  become: no
  vars:
    end_time: '12:31-23:59'

  tasks:
    - name: Display current time and the scheduled end time
      debug:
        msg: "Current time: '{{ lookup('pipe','date +%m:%d-%H:%M') }}' - End Time: '{{ end_time }}'"

    - name: Hold on until 3 gets picked up
      shell: >
         python -c 'import random; print random.randint(1,5)'
      register: rand_result
      until: "rand_result.stdout.find('3') != -1 or '{{ lookup('pipe','date +%m:%d-%H:%M') }}' > '{{ end_time }}'"
      retries: 100
      delay: 0
      when: "'{{ lookup('pipe','date +%m:%d-%H:%M') }}' < '{{ end_time }}'"
```
##### EXPECTED RESULTS

Output when run with Ansible 2.0.1.0:

```
06:31:52-florian~/Public/ansible-slides$ ansible-playbook test.yaml -i {}
 [WARNING]: provided hosts list is empty, only localhost is available

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Display current time and the scheduled end time] *************************
ok: [localhost] => {
    "msg": "Current time: '05:18-06:32' - End Time: '12:31-23:59'"
}

TASK [Hold on until 3 gets picked up] ******************************************
FAILED - RETRYING: TASK: Hold on until 3 gets picked up (99 retries left). Result was: {u'changed': True, u'end': u'2016-05-18 06:32:00.309278', u'stdout': u'4', u'cmd': u"python -c 'import random; print random.randint(1,5)'", u'rc': 0, u'start': u'2016-05-18 06:32:00.298888', u'stderr': u'', u'delta': u'0:00:00.010390', 'invocation': {'module_name': u'command', u'module_args': {u'creates': None, u'executable': None, u'chdir': None, u'_raw_params': u"python -c 'import random; print random.randint(1,5)'", u'removes': None, u'warn': True, u'_uses_shell': True}}, 'stdout_lines': [u'4'], u'warnings': []}
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   

```
##### ACTUAL RESULTS

Output when run with Ansible 2.0.2.0:

```
06:33:26-florian~/Public/ansible-slides$ ansible-playbook test.yaml -i {} -vvvv
Using /home/florian/Public/ansible-slides/ansible.cfg as config file
 [WARNING]: Host file not found: {}

 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0

PLAYBOOK: test.yaml ************************************************************
1 plays in test.yaml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ESTABLISH LOCAL CONNECTION FOR USER: florian
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1463578407.76-159479441078276 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1463578407.76-159479441078276 `" )'
127.0.0.1 PUT /tmp/tmp6hEX9u TO /home/florian/.ansible/tmp/ansible-tmp-1463578407.76-159479441078276/setup
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/florian/.ansible/tmp/ansible-tmp-1463578407.76-159479441078276/setup; rm -rf "/home/florian/.ansible/tmp/ansible-tmp-1463578407.76-159479441078276/" > /dev/null 2>&1'
ok: [localhost]

TASK [Display current time and the scheduled end time] *************************
task path: /home/florian/Public/ansible-slides/test.yaml:8
ok: [localhost] => {
    "msg": "Current time: '05:18-06:33' - End Time: '12:31-23:59'"
}

TASK [Hold on until 3 gets picked up] ******************************************
task path: /home/florian/Public/ansible-slides/test.yaml:12
ESTABLISH LOCAL CONNECTION FOR USER: florian
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1463578408.31-769147004718 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1463578408.31-769147004718 `" )'
127.0.0.1 PUT /tmp/tmpedBayu TO /home/florian/.ansible/tmp/ansible-tmp-1463578408.31-769147004718/command
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/florian/.ansible/tmp/ansible-tmp-1463578408.31-769147004718/command; rm -rf "/home/florian/.ansible/tmp/ansible-tmp-1463578408.31-769147004718/" > /dev/null 2>&1'
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'rand_result.stdout.find('3') != -1 or '{{ lookup('pipe'' failed. The error was: template error while templating string: unexpected end of template, expected ','.. String: rand_result.stdout.find('3') != -1 or '{{ lookup('pipe'"}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1   
```
