### ISSUE TITLE
ansible-playbook --tags not working

### ISSUE THREAD

**Issue by enilsonandrade** [ansible/ansible#15927]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### SUMMARY

If I run ansible-playbook with --tags, all roles are still executed, not only the ones with the tag name provided
##### STEPS TO REPRODUCE

1 Run ansible-playbook --tags "copy-windows" site.yml -vvvvv

```
- name: copy file to windows
  hosts: windows
  roles:
    - { role: copy-windows, tags: [ 'copy-windows' ] }

- name: deploy PostgreSQL
  hosts: postgres
  vars:
    mapping_pglog_dir: "/data/mapping-pglog"
  roles:
    - { role: postgres, become: yes, tags: [ 'postgres' ] }
```
##### EXPECTED RESULTS

Only the role copy-windows runs 
##### ACTUAL RESULTS

Both roles are running. PostgreSQL should not run

```
PLAY [deploy PostgreSQL] *******************************************************
skipping: no hosts matched
```
