### ISSUE TITLE
handler order

### ISSUE THREAD

**Issue by h0nIg** [ansible/ansible#15939]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
2.1
```

##### SUMMARY
since we are working with a lot of roles, sometimes it is necessary to reorder handlers that have been added by roles. e.g. we want to umount a share **after** the temp directory on the share has been removed. Currently the handlers are executed within the order of insertion. This behavior should be extended to respect an priority or order attribute.
**example 1**
```
role1:
- file: state=directory dest=/tmp/mount/
  notify:
    - unmount share
role2:
- file: state=directory dest=/tmp/mount/temp/
  notify:
    - remove temporary
- name: unmount share
  mount: state=umount....
  priority: -100
- name: unmount share
  file: state=absent dest=/tmp/mount/temp/
  priority: 0
```
**example 2**
```
role1:
- file: state=directory dest=/tmp/mount/
  notify:
    - name: unmount share
      priority: -100
role2:
- file: state=directory dest=/tmp/mount/temp/
  notify:
    - name: remove temporary
      priority: 0
- name: unmount share
  mount: state=umount....
- name: unmount share
  file: state=absent dest=/tmp/mount/temp/
```
