### ISSUE TITLE
rabbitmq_user broken in devel

### ISSUE THREAD

**Issue by jpic** [ansible/ansible#15971]
##### ANSIBLE VERSION

```

  lib/ansible/modules/core: (detached HEAD 9eb2b557cd) last updated 2016/04/27 15:33:49 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD d9caac037c) last updated 2016/04/27 15:33:54 (GMT +200)
  config file = /home/jpic/.ansible.cfg
  configured module search path = ['/home/jpic/ansible/library', '/usr/share/ansible']
```
##### STEPS TO REPRODUCE

```

  rabbitmq_user:
    user: "{{ item.user }}" 
    password: "{{ item.password }}" 
    configure_priv: "{{ item.configure_priv|default('.*') }}" 
    read_priv: "{{ item.read_priv|default('.*') }}" 
    write_priv: "{{ item.write_priv|default('.*') }}" 
    vhost: "{{ item.vhost|default('/') }}" 
    tags: "{{ item.tags|default('') }}" 
  with_items: rabbitmq_users
  tags: [configuration,rabbitmq]
```
##### ACTUAL RESULTS

First run:

```
failed: [rabbitmq.lxc] (item={u'vhost': u'/', u'tags': u'administrator', u'read_priv': u'.*', u'write_priv': u'.*', u'user': u'admin', u'configure_priv': u'.*', u'password': u'admin'}) => {
    "failed": true,
    "item": {
        "configure_priv": ".*",
        "password": "admin",
        "read_priv": ".*",
        "tags": "administrator",
        "user": "admin",
        "vhost": "/",
        "write_priv": ".*"
    },
    "module_stderr": "",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_DQ0gZG/ansible_module_rabbitmq_user.py\", line 302, in <module>\r\n    main()\r\n  File \"/tmp/ansible_DQ0gZG/ansible_module_rabbitmq_user.py\", line 295, in main\r\n    rabbitmq_user.set_permissions()\r\n  File \"/tmp/ansible_DQ0gZG/ansible_module_rabbitmq_user.py\", line 206, in set_permissions\r\n    for permission in self._permissions:\r\nTypeError: 'NoneType' object is not iterable\r\n",
    "parsed": false
}

MSG:

MODULE FAILURE
```

Subsequent runs:

```
changed: [rabbitmq.lxc] => (item={u'vhost': u'/', u'tags': u'administrator', u'read_priv': u'.*', u'write_priv': u'.*', u'user': u'admin', u'configure_priv': u'.*', u'password': u'admin'}) => {
    "changed": true, 
    "item": {
        "configure_priv": ".*", 
        "password": "admin", 
        "read_priv": ".*", 
        "tags": "administrator", 
        "user": "admin", 
        "vhost": "/", 
        "write_priv": ".*"
    }, 
    "state": "present", 
    "user": "admin"
}
```
