### ISSUE TITLE
Different group_vars with same dictionary

### ISSUE THREAD

**Issue by westsouthnight** [ansible/ansible#16004]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
- Core

##### ANSIBLE VERSION

```
MULTIPLE VERSIONS AFFECTED:

ansible 2.2.0 & ansible 2.0.1
ansible 2.4.0.0 & I thinks its steel going in current dev

```
##### CONFIGURATION

Tryed : hash_behaviour=replace & hash_behaviour=merge
##### OS / ENVIRONMENT

MAC OS X 10.10.5 
MAC OS X 10.13.1 
UBUNTU 14.04
UBUNTU 16.04

##### SUMMARY

I want to install two elasticsearch engines to same hosts with different configuration,

after prepare the env and playbooks for that i'm go testing them.

With ansible structure (without real data, structure when i find that issue):

```
|-- ansible
   |-- inventories
   |    |-- develop
   |    |     |-- group_vars
   |    |     |     |─ elasticsearch-group-1.yml
   |    |     |     |─ elasticsearch-group-2.yml
   |    |     |─ develop
   |    |
   |    |-- stage
   |    |     |-- group_vars
   |    |     |     |─ elasticsearch-group-1.yml
   |    |     |     |─ elasticsearch-group-2.yml
   |    |     |─ stage
   |    |
   |    |-- production
   |          |-- group_vars
   |          |     |─ elasticsearch-group-1.yml
   |          |     |─ elasticsearch-group-2.yml
   |          |─ production
   |
   |-- roles
   |    |-- elasticsearch
   |          |-- defaults
   |          |     |─ main.yml
   |          |-- tasks
   |                |─ main.yml
   |
   |-- playbook-0.yml
   |-- playbook-1.yml
```
##### STEPS TO REPRODUCE

```
/inventory/develop/develop

[elasticsearch-group-1]
''[01:03]-elasticsearch-group.com

[elasticsearch-group-2]
''[01:03]-elasticsearch-group.com
```

```
/inventories/develop/group_vars/elasticsearch-group-1.yml

elasticsearch_settings:
    elasticsearch_memory_heap_size: '30g'
    elasticsearch_memory_heap_newsize: '30g'
    elasticsearch_group_master: elasticsearch-cluster-1
    elasticsearch_version: '1.7'
    elasticsearch_cluster_name: 'elasticsearch-develop-1'
    elasticsearch_service_name: 'elasticsearch'
    elasticsearch_index_shards: 3
    elasticsearch_index_replicas: 2
    elasticsearch_discovery_minimum_master_nodes: 2
    elasticsearch_discovery_multicast_enabled: false
    elasticsearch_discovery_ping_unicast_hosts: '{{ groups["elasticsearch-group-1"] }}'
    elasticsearch_path_home: '/usr/share/elasticsearch'
    elasticsearch_discovery_multicast_port: 54328
    elasticsearch_path_data: '/opt/elastic/develop-1/data'
    elasticsearch_path_work: '/opt/elastic/develop-1/work'
    elasticsearch_path_logs: '/opt/elastic/develop-1/logs'
    elasticsearch_path_conf: '/opt/elastic/develop-1/conf'
    elasticsearch_path_pid: '/opt/elastic/develop-1'
    elasticsearch_node_port: 9300
    elasticsearch_http_port: 9200

```

```
/inventories/develop/group_vars/elasticsearch-group-2.yml

elasticsearch_settings:
    elasticsearch_memory_heap_size: '30g'
    elasticsearch_memory_heap_newsize: '30g'
    elasticsearch_group_master: elasticsearch-cluster-2
    elasticsearch_version: '1.7'
    elasticsearch_cluster_name: 'elasticsearch-develop-2'
    elasticsearch_service_name: 'elasticsearch'
    elasticsearch_index_shards: 3
    elasticsearch_index_replicas: 2
    elasticsearch_discovery_minimum_master_nodes: 2
    elasticsearch_discovery_multicast_enabled: false
    elasticsearch_discovery_ping_unicast_hosts: '{{ groups["elasticsearch-group-2"] }}'
    elasticsearch_path_home: '/usr/share/elasticsearch'
    elasticsearch_discovery_multicast_port: 54328
    elasticsearch_path_data: '/opt/elastic/develop-2/data'
    elasticsearch_path_work: '/opt/elastic/develop-2/work'
    elasticsearch_path_logs: '/opt/elastic/develop-2/logs'
    elasticsearch_path_conf: '/opt/elastic/develop-2/conf'
    elasticsearch_path_pid: '/opt/elastic/develop-2'
    elasticsearch_node_port: 10300
    elasticsearch_http_port: 10200
```

```
playbook-0.yml

---
# elasticsearch cluster for develop-1 data.
- name: install and configure java and elastic
  hosts: elasticsearch-group-1
  become: true
  roles:
    - name: install and configure elasticsearch
      role: elasticsearch

```

```
playbook-1.yml

---
# elasticsearch cluster for develop-1 data.
- name: install and configure java and elastic
  hosts: elasticsearch-group-2
  become: true
  roles:
    - name: install and configure elasticsearch
      role: elasticsearch

```

```
/roles/elasticsearch/defaults/main.yml

elasticsearch_settings_defaults:
    elasticsearch_group_master: 'debops_elasticsearch_master'
    elasticsearch_group_workhorse: 'debops_elasticsearch_workhorse'
    elasticsearch_group_coordinator: 'debops_elasticsearch_coordinator'
    elasticsearch_group_loadbalancer: 'debops_elasticsearch_loadbalancer'
    elasticsearch_repository: 'http://packages.elastic.co/elasticsearch'
    elasticsearch_path_conf: '/etc/elasticsearch'
    elasticsearch_path_data: '/var/lib/elasticsearch'
    elasticsearch_path_pid: '/var/lib/elasticsearch'
    elasticsearch_path_logs: '/var/log/elasticsearch'
    elasticsearch_path_work: '/tmp/elasticsearch'
    elasticsearch_path_home: '/usr/share/elasticsearch'
    elasticsearch_path_plugins: '/usr/share/elasticsearch/plugins'
    elasticsearch_path_lib: '/usr/share/elasticsearch/lib'

```

```
/roles/elasticsearch/tasks/main.yml

- debug: var=elasticsearch_settings

- debug: var=elasticsearch_settings_defaults

- name: Inject defaults for elasticsearch
  set_fact:
    elasticsearch_settings: "{{ elasticsearch_settings_defaults | combine(elasticsearch_settings) }}"

- debug: var=elasticsearch_settings
```

##### EXPECTED RESULTS

Each group_vars for each group hosts merge role/defaults dictionary with dictionary obtained from file with name of the that group 
##### ACTUAL RESULTS

Ansible get last "elasticsearch_settings" dictionary for merge with "elasticsearch_settings_defaults" without see to match group_host name {{ "elasticsearch_settings" }} to name of the group_hosts and that group_vars. 

For each playbooks we see `/inventory/develop/group_vars/elasticsearch-group-2.yml` dictionary.

```

```
