### ISSUE TITLE
Unarchive: Unexpected error when accessing exploded file

### ISSUE THREAD

**Issue by nblock** [ansible/ansible#16041]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/<user>/path/to/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
remote_user = ansibleuser
sudo = True
ansible_managed = Ansible managed: modified on %Y-%m-%d %H:%M:%S by {uid} from {host}.
inventory = inventories/testing.ini
private_key_file = ~/.ssh/id_rsa-ansible
roles_path = roles
```
##### OS / ENVIRONMENT
- Running on Arch Linux inside a virtualenv via `pip install ansible`.
- Managing another Arch Linux instance.
##### SUMMARY

The unarchive module fails when the `creates` option is used and the file does not yet exist. The same code used to work with Ansible 2.0.2.0.
##### STEPS TO REPRODUCE
- Ansible 2.1.0.0

```

---
- name: Download tarball
  get_url:
    url: http://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
    dest: /tmp
    checksum: sha256:98f0868c0cf9fc6664b57f89149fa537b73222bcc010247771e4afc08c8199fd

- name: Unpack tarball
  unarchive:
    src: /tmp/dokuwiki-stable.tgz
    dest: /tmp
    creates: /tmp/dokuwiki-2015-08-10a
    copy: False
    owner: www-data
    group: www-data

```
##### EXPECTED RESULTS
- The unpacked directory: `/tmp/dokuwiki-2015-08-10a`
##### ACTUAL RESULTS
- The following error message on Ansible 2.1.0.0:

```
$ ansible-playbook site.yml
fatal: [example.org]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"backup": null, "content": null, "copy": false, "creates": "/tmp/dokuwiki-2015-08-10a", "delimiter": null, "dest": "/tmp", "directory_mode": null, "exclude": [], "extra_opts": [], "follow": false, "force": null, "group": "www-data", "keep_newer": false, "list_files": false, "mode": null, "original_basename": "dokuwiki-stable.tgz", "owner": "www-data", "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/tmp/dokuwiki-stable.tgz"}}, "msg": "Unexpected error when accessing exploded file: [Errno 2] File oder directory not found: '/tmp/dokuwiki-2015-08-10a'", "stat": {"exists": false}}
```
- The unpacked directory: `/tmp/dokuwiki-2015-08-10a` on Ansible 2.0.2.0.
