### ISSUE TITLE
Describe how to use "postgresql_user" properly with ansible >= 2.1.0.0

### ISSUE THREAD

**Issue by abguy** [ansible/ansible#16048]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION
```
2.1.0.0
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
After upgrading to Ansible 2.1 I can't add PostgreSQL user because of this error
```
FAILED! => {"failed": true, "msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user. For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```

##### STEPS TO REPRODUCE
I have no direct ssh access enabled for root user. I use the default `ubuntu` user to login to my server. It's quite common configuration for Ubuntu.
That's why I have this book:
```
- hosts: dbservers
  remote_user: ubuntu
  become: true
  become_user: postgres
  roles:
    - postgresql
```
and the postgresql role with:
```
- name: Create user for the app
  postgresql_user: user={{ db_user }} password={{ db_pass }}
  tags: postgresql
```

##### EXPECTED RESULTS
Please describe in the documentation how to add PG users properly.

##### ACTUAL RESULTS
I didn't find how to add PG users properly. The only option that works for me is `allow_world_readable_tmpfiles = True` in the `ansible.cfg`.

**Comment by WiNloSt** [comment]
Can you tell me the exact Ansible version before upgrading to 2.1 that didn't have this error. Because I'm getting the same error right now.

**Comment by abguy** [comment]
For instance, the previous one works fine, `ansible 2.0.2.0`.
On Ubuntu you can install it by

```
sudo apt-get install ansible=2.0.2.0-1ppa~trusty
```

**Comment by michaelem** [comment]
I did run into this as well and tried all the solutions on the proposed documentation site (https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user).
None of them worked, had to fall back to `allow_world_readable_tmpfiles = True` and living with warnings for now.

**Comment by abguy** [comment]
Yes, that's it! I don't see any other ways too. It looks like this is a product issue, but not the documentation one.

**Comment by aselshamy** [comment]
I'm having the same issue, with 2.1.0.0-1ppa~trusty. please fix.
- name: postgresql - create user
  become: yes
  become_user: postgres
  postgresql_user:  user={{ db_username }}
                    password={{ db_password }}
                    role_attr_flags=CREATEDB,NOSUPERUSER

**Comment by sgsabbage** [comment]
I managed to get this temporarily working with pipelining per task and becoming postgres user:

```
- name: Create database user
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_user:
    name: user
```

Hopefully this helps anyone in the same boat.

**Comment by richardsmd** [comment]
I'm curious if there is a way to check for superuser privileges on remote_user.

If your remote_user is ubuntu and you have this line in `/etc/sudoers`

`ubuntu ALL=(ALL:ALL) NOPASSWD:ALL`

then shouldn't ansible be able to change permissions in the same way as if you had connected via root?

**Comment by jklaiho** [comment]
To make things slightly worse, #15297 means that I can't even use @sgsabbage's pipelining workaround, and have no choice but to rely on `allow_world_readable_tmpfiles`.

**Comment by geerlingguy** [comment]
@jklaiho - @sgsabbage's hack is currently working for me under Ansible 2.1.1.0 (haven't tested 2.1.2.0 or devel yet).

**Comment by theromis** [comment]
```
✗ ansible --version
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

not works for me

``` yaml
- name: Postgres db
  become: true
  become_user: postgres
  postgresql_db: name={{db.name}}
  vars:
    ansible_ssh_pipelining: true
```

**Comment by audiolion** [comment]
Getting same issue 2.1.2.0, I just went back to 1.9 until issue is resolved

**Comment by sayap** [comment]
We got the same problem, and in our case it was because the `acl` package is not installed by default on GCE ubuntu trusty image. The `set_user_facl` method calls `setfacl -m u:postgres:rx /tmp/xxx`, and the `acl` package provides `/usr/bin/setfacl`.

**Comment by jasimmonsv** [comment]
+1 Same problem

**Comment by jasimmonsv** [comment]
@sgsabbage solution finally worked for me after running the playbook with -vvvv
I had to add edit my sudoers file to include:
`%sudo ALL=(ALL) NOPASSWD: ALL`

so that all my logged in user in the sudo group would not be prompted for a password for any command.
This work for me to allow:
```
- name: configure DB
  become: yes
  become_user: postgres
  vars:
    ansible_ssh_pipelining: true
  postgresql_db:
    name: '{{ db_name }}'
    encoding: UTF-8
    lc_ctype: en_US.UTF-8
    lc_collate: en_US.UTF-8
    template: template0
    state: present
```

**Comment by sgsabbage** [comment]
Coming back to this as I ended up having some problems with it, so I eventually just gave up and let the root user login as the postgres user with the following file changes:

`pg_ident.conf:`
```
# MAPNAME    SYSTEM-USERNAME       PG-USERNAME
root         root                  postgres
# We also need to allow the postgres user to login as itself
root         postgres              postgres 
```
`pg_hba.conf:`
```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
local   all             postgres                                peer map=root
local   all             all                                     peer
...
```
Please bear in mind, this isn't my complete pg_hba.conf file, just an example of the main change. Then you can just use the postgres tasks as:
```
- name: Create database
  become: yes
  postgresql_db:
    name: database_name
```

**Comment by ansibot** [comment]
@abguy Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ur5us** [comment]
@sayap Thanks for your tip. In my case I'm using a box on https://www.scaleway.com/. 

Installing the `acl` package fixes the problem, no extra privilege escalation settings required other than `become_user: postgres`. 

```
ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by Taytay** [comment]
Installing the `acl` package as a first task worked for me to solve this problem.

**Comment by idanshimon** [comment]
@Taytay can you explain ??

I am also trying for sometime to deploy postgresql using a simple play and it gets an error about peer authentication failure for user postgres (9.6)

```
---
- hosts: postgresqls
  become: True

  tasks:
    - name: Install PostgreSQL
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - postgresql
        - python-psycopg2
        - postgresql-contrib
        - libpq-dev

    - name: Create database user
      become: yes
      become_user: postgres
      vars:
        ansible_ssh_pipelining: true
      postgresql_user:
        name: testuser

```
Result Ansible-playbook:
   "msg": "unable to connect to database: FATAL:  Peer authentication failed for user \"postgres\"\n"
