### ISSUE TITLE
Docker module: argument memory_limit is of type <type 'str'> and we were unable to convert to int" on  Ansible 2.0.2.0-1.el7

### ISSUE THREAD

**Issue by michalzubkowicz** [ansible/ansible#16045]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### OS / ENVIRONMENT

Centos 7
##### SUMMARY

After upgrade to ansible 2.0.2.0 it's not possible to enter memory_limit as human readable string (ie. 265MB) only bytes are accepted. 
##### STEPS TO REPRODUCE

try set memory_limit:  256MB

```
- name: sphinx container
  docker:
        name: sphinx
        image: michalzubkowicz/docker-sphinxsearch
        state: started
        restart_policy: always
        memory_limit: 256MB
```

##### EXPECTED RESULTS

Should accept string as early versions 
##### ACTUAL RESULTS

Is showing error
argument memory_limit is of type <type 'str'> and we were unable to convert to int
