### ISSUE TITLE
ansible set global fact

### ISSUE THREAD

**Issue by anshbikram** [ansible/ansible#16049]
##### ISSUE TYPE

- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
log_path = ./ansible.log
gathering = smart
fact_caching = jsonfile
fact_caching_connection = ./facts
fact_caching_timeout = 86400

[ssh_connection]
pipelining = True
scp_if_ssh = True
```
##### SUMMARY

I run ansible on 100+ nodes with around 60-70 "set_facts" entries. The set_fact step is taking the most of the run time (around 15-20 min). However, the "set_facts" is setting variables that are common across all hosts but each set_fact is running for all hosts. 

Is there any way of making the set_facts global for all hosts, so that it sets the fact once and use the same for all hosts? 
or 
Is it possible to cache or create a persistent file of the facts and reuse them in subsequent runs??

**Comment by rgroten** [comment]
If the values are constant could you set them as default (or group) variables?

**Comment by anshbikram** [comment]
the values must be set dynamically as they depend on some other variables value. 
e.g
- set_fact: ADMIN_USER=admin
  when: USE_LDAP == True

USE_LDAP value is be defined beforehand and it is included with include_vars

**Comment by bcoca** [comment]
or do this:

```
vars:
  ADMIN_USER: "{{USE_LDAP|ternary('admin','')}}"
```

**Comment by anshbikram** [comment]
@bcoca thanks

**Comment by dagwieers** [comment]
Just as a reference for others, I prefer this syntax over the use of the ternary filter:

``` yaml
vars:
  ADMIN_USER: '{{ "admin" if USE_LDAP else "" }}'
```

**Comment by nikaro** [comment]
Would still be a nice feature to have. I have to do an ugly hack to achieve something like this :

```yaml
- name: get current database user password
  shell: grep PASSWORD /home/{{ instance_name }}/msinstance/conf/mssettings.py | cut -d \' -f 4
  register: instance_password
  when: inventory_hostname == "old.example.org"

- set_fact:
    instance_password: "{{ instance_password.stdout }}"
  when: inventory_hostname == "old.example.org"
- debug:
    var: hostvars['old.example.org']['instance_password']
  when: inventory_hostname == "new.example.org"

- name: create remote database user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ instance_name }}"
    password: "{{ hostvars['old.example.org']['instance_password'] }}"
    encrypted: yes
  when: inventory_hostname == "new.example.org"
```
