### ISSUE TITLE
Async task fails on 2.1 with WinRMTransportError even when ignore_errors is set to true

### ISSUE THREAD

**Issue by rjosephwright** [ansible/ansible#16077]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No ansible.cfg used. ANSIBLE_ROLES_PATH and ANSIBLE_HOST_KEY_CHECKING environment variables are set.
##### OS / ENVIRONMENT

Running from Ubuntu 15.10
Managing Windows 2008r2 and 2012r2
##### SUMMARY

I have a `win_package` task which reboots the machine when it finishes installing a package. The task uses async with `ignore_errors` set to `true`, then waits for the machine to come back on the next task. On previous Ansible versions, this worked fine, but after upgrading to 2.1, the task fails and the playbook does not continue.
##### STEPS TO REPRODUCE

This is the failing task and the one that follows:

```
- name: Install Trend Micro SecureCloud
  win_package:
    path="C:\SecureCloudAgentSilentSetup_Release_Win32_en_3.7.0_1107.exe"
    product_id="{2301FEB0-7D71-4DB4-A164-A95A7DDBD3B3}"
    arguments="/q"
  async: 0
  poll: 0
  ignore_errors: true
  when: sc_installed | failed

- name: Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300
  when: sc_installed | failed
```
##### EXPECTED RESULTS

I expected any errors that occur during the task `Install Trend Micro SecureCloud` to be ignored, and the task `Waiting for server to come back` to wait. This is the behavior with previous versions of Ansible that I used.
##### ACTUAL RESULTS

Task fails but error is not ignored.

```
TASK [base-windows : Install Trend Micro SecureCloud] **************************
task path: /home/joswright/Workspace/base-windows/tasks/main.yml:221
<10.x.x.x> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 10.x.x.x
<10.x.x.x> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1464737336.12-201371408724451").FullName | Write-Host -Separator '';
<10.x.x.x> PUT "/tmp/tmpjy_Xb5" TO "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1464737336.12-201371408724451\win_package.ps1"
<10.x.x.x> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1464737336.12-201371408724451\win_package.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
Finally { Remove-Item "C:\Users\Administrator\AppData\Local\Temp\ansible-tmp-1464737336.12-201371408724451" -Force -Recurse -ErrorAction SilentlyContinue }
Traceback (most recent call last):
  File "/home/joswright/.pyenv/versions/2.7.11/envs/bossimage/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 271, in exec_command
    result = self._winrm_exec(cmd_parts[0], cmd_parts[1:], from_exec=True)
  File "/home/joswright/.pyenv/versions/2.7.11/envs/bossimage/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 234, in _winrm_exec
    self.protocol.cleanup_command(self.shell_id, command_id)
  File "/home/joswright/.pyenv/versions/2.7.11/envs/bossimage/lib/python2.7/site-packages/winrm/protocol.py", line 290, in cleanup_command
    rs = self.send_message(xmltodict.unparse(rq))
  File "/home/joswright/.pyenv/versions/2.7.11/envs/bossimage/lib/python2.7/site-packages/winrm/protocol.py", line 193, in send_message
    return self.transport.send_message(message)
  File "/home/joswright/.pyenv/versions/2.7.11/envs/bossimage/lib/python2.7/site-packages/winrm/transport.py", line 138, in send_message
    raise WinRMTransportError('http', ex.reason)
WinRMTransportError: 500 WinRMTransport. [Errno 111] Connection refused
fatal: [10.x.x.x]: UNREACHABLE! => {"changed": false, "msg": "failed to exec cmd PowerShell -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -EncodedCommand UwBlAHQALQBTAHQAcgBp<truncated>HQAaQBuAHUAZQAgAH0A", "unreachable": true}
```
