### ISSUE TITLE
Add an "include" parameter to unarchive

### ISSUE THREAD

**Issue by smoyer64** [ansible/ansible#16130]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
unarchive module

##### ANSIBLE VERSION
```
ansible 2.1.0.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
This feature idea is really more geared towards Ansible > 2.1
```

##### CONFIGURATION
export ANSIBLE_NOCOWS=1

##### SUMMARY
A Java JAR file is a ZIP file with a manifest and can be extracted using unarchive.  A Java JAR file can also be executed in place.  It's pretty common to extract specific files from a Java JAR file (such as properties files) so that you can alter the execution environment.  In the case below, I simply want to extract the icon file to add a launcher for Burp Suite to the menu.
In any case, there are many other instances when it would be convenient to unarchive a limited set of files from an archive.  The "exclude" parameter provides a similar function, but wouldn't be convenient in this case as there are thousands of files and a complex directory hierarchy in this archive.  Since I'm not on 2.1 yet (Xubuntu), I don't have the exclude feature yet but used the command module to run unzip instead.  The only annoying aspect to this technique is that Ansible tells me I should be using the unarchive module.
Low priority but potentially very useful ... and thanks for hard work you all put in!

##### STEPS TO REPRODUCE
The following play extracts a single file as needed:
```
- name: extract the application's icon from the archive
  command: unzip {{ burp_installation_directory }}/{{ burp_file }} {{ burp_icon_path }}/{{ burp_icon_file }}
           chdir={{ burp_installation_directory }}
           creates={{ burp_installation_directory }}/{{ burp_icon_path }}/{{ burp_icon_file }}
  tags:
    - burp_suite
    - security
```
But also generates a warning that I'm using the wrong module for the job.
```
TASK [burp_suite : extract the application's icon from the archive] ************
changed: [localhost]
 [WARNING]: Consider using unarchive module rather than running unzip
```
