### ISSUE TITLE
loop_var output is wrong

### ISSUE THREAD

**Issue by nerzhul** [ansible/ansible#16144]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

Not important there
##### OS / ENVIRONMENT

Archlinux / Debian 8
##### SUMMARY

When iterating over multiple with_items loop, we should use loop_control.loop_var variable to iterate over the multiple levels.
Ansible output is wrong on screen
##### STEPS TO REPRODUCE

Create a role including a file using with_items
Do a task with a with_item inside it

main.yml

```
- include: deploy_single.yml app_item="{{ item }}"
  with_items: "{{ php_apps }}"
```

deploy_single.yml

```
- name: "FILE | Apply httpd rights for application"
  file: path="{{ dir_item }}" state=directory recurse=yes owner="{{ app_item.httpd_write_owner | default('www-data') }}"
  with_items: "{{ app_item.httpd_write_dirs }}"
  loop_control:
    loop_var: dir_item
```
##### EXPECTED RESULTS

```
TASK [php_application : TEMPLATE | Deploy templates] ***************************
ok: [test.local] => (tpl_item="/var/www/owncloud/data")
```
##### ACTUAL RESULTS

```
TASK [php_application : TEMPLATE | Deploy templates] ***************************
ok: [test.local] => (item=None)

```
