### ISSUE TITLE
Allow when cause at playbook level.

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#16153]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
roles

##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### SUMMARY

Add when cause to roles at the playbook level.
##### STEPS TO REPRODUCE

Right now Ansible allows conditional roles like this:

```
- hosts: monitoring
  become: true
  roles:
    - role: shinken-install
      when: shinken_disable is not defined 
    - role: shinken-configure
      when: shinken_disable is not defined 
    - role: shinken-ssh-check  
      when: shinken_disable is not defined
```
##### EXPECTED RESULTS

It is more concise to write single 'when' cause for all  roles like this:

```
- hosts: monitoring
  become: true
  roles:
    -  shinken-install
    -  shinken-configure
    -  shinken-ssh-check  
  when: shinken_disable is not defined
```
