### ISSUE TITLE
Lookup password returns password including the salt - regression from 1.9

### ISSUE THREAD

**Issue by stravid** [ansible/ansible#16189]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

(Disclaimer: I already [asked on the mailing list](https://groups.google.com/forum/#!msg/ansible-project/TRttzH0jJ54/7P9dKVmXAQAJ) but nobody seemed to take interest in the problem.)

The password produced by a create user task cannot be used somewhere else since `lookup` returns the password including the salt as suffix. Following workflow to create a user with a random password and using the password later as `ansible_sudo_password` worked in 1.9 but is broken in 2.X.

Task for creating the user:

```
- name: Create user
  user: name=deployer group=deployer password={{item}} state=present
  with_password: "passwords/users/deployer encrypt=sha256_crypt"
```

Using the password later on:

```
- hosts: all 
  remote_user: deployer
  vars: 
  - ansible_sudo_pass: "{{ lookup('password', 'passwords/users/deployer') }}"
```
