### ISSUE TITLE
Inappropriate Deprecation Message

### ISSUE THREAD

**Issue by arpit-goel** [ansible/ansible#16183]
Hi,
I'm running `ansible-playbook 2.1.0.0` and receive following warning every time I run deployment:

```
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:

http://docs.ansible.com/ansible/playbooks_roles.html#task-include-files-and-encouraging-reuse

 for currently supported syntax regarding included 
files and variables.
This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
```

As far as I understand from the message, there shouldn't be variables defined with the include statement. Going to the link doesn't prove to be much help as the message in the error and content on page doesn't match.
Here is my task file:

```
- include: env.yml
  tag: provision,env
```

And here's my env.yml:

```
- name: Configure environment variables
  template: src=env/.{{ env_name }}.j2 dest="{{ deploy_directory }}/.env" force=yes
  register: environment_vars_check

- name: restart supervisor
  become: yes
  become_user: root
  become_method: sudo
  command: restart supervisor
  when: environment_vars_check.changed

- name: Add env to deployer user bashrc
  blockinfile:
    dest: "/home/{{ deploy_user }}/.bashrc"
    backup: "yes"
    state: "present"
    insertafter: "EOF"
    marker: "# {{ version }} {mark}"
    content: |
        while read line
        do
                export $line
        done < {{ deploy_directory }}/.env
  when: inventory_hostname in groups.appservers
```

Please look into the issue.
