### ISSUE TITLE
unarchive module fails with zip files

### ISSUE THREAD

**Issue by capsloth** [ansible/ansible#16197]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/tessio/ansible/next/ansible.cfg
  configured module search path = Default w/o overrides
```
##### UNZIP VERSION

```
caution:  both -n and -o specified; ignoring -o
UnZip 6.00 of 20 April 2009, by Debian. Original by Info-ZIP.

Latest sources and executables are at ftp://ftp.info-zip.org/pub/infozip/ ;
see ftp://ftp.info-zip.org/pub/infozip/UnZip.html for other sites.

Compiled with gcc 5.2.1 20151010 for Unix (Linux ELF).

UnZip special compilation options:
        ACORN_FTYPE_NFS
        COPYRIGHT_CLEAN (PKZIP 0.9x unreducing method not supported)
        SET_DIR_ATTRIB
        SYMLINKS (symbolic links supported, if RTL and file system permit)
        TIMESTAMP
        UNIXBACKUP
        USE_EF_UT_TIME
        USE_UNSHRINK (PKZIP/Zip 1.x unshrinking method supported)
        USE_DEFLATE64 (PKZIP 4.x Deflate64(tm) supported)
        UNICODE_SUPPORT [wide-chars, char coding: UTF-8] (handle UTF-8 paths)
        LARGE_FILE_SUPPORT (large files over 2 GiB supported)
        ZIP64_SUPPORT (archives using Zip64 for large files supported)
        USE_BZIP2 (PKZIP 4.6+, using bzip2 lib version 1.0.6, 6-Sept-2010)
        VMS_TEXT_CONV
        WILD_STOP_AT_DIR
        [decryption, version 2.11 of 05 Jan 2007]

UnZip and ZipInfo environment options:
           UNZIP:  [none]
        UNZIPOPT:  [none]
         ZIPINFO:  [none]
      ZIPINFOOPT:  [none]
```
##### CONFIGURATION

```
[defaults]
hostfile = hosts
```
##### OS / ENVIRONMENT

```
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily
Ansible package from Ansibles Inc's PPA.
```
##### SUMMARY

unarchive module fails to extract zip files that contain files whose name has spaces in it, like the file named "CPL - cpl1.0.txt".
##### STEPS TO REPRODUCE

Download [jboss-5.1.0.GA-jdk6.zip](https://sourceforge.net/projects/jboss/files/JBoss/JBoss-5.1.0.GA/jboss-5.1.0.GA-jdk6.zip/download), then try to copy and extract it to another machine using ansible.
This was how I discovered the bug, but I got the same result when I created _archive.zip_  with a file named "bug - bug.txt" and the command "zip archive bug\ -\ bug.txt".

```

---
- name: install e configure Jboss 5.1
  hosts: sig
  become: yes
  vars:
    java_home: /opt/java/jdk1.6.0_45
    jboss_home: /opt/jboss/jboss-5.1.0.GA
    jboss_package: jboss-5.1.0.GA-jdk6.zip

  tasks:
  - name: install dependencies
    apt: name=unzip state=present update_cache=yes

  - name: send archive
    copy: src=files/{{ jboss_package }} dest=/tmp mode=0664
    register: package

  - name: check copy
    fail: msg="bad copy"
    when: package.checksum != "0906717eec83d57a3fdbdf090555cac036bffc6d"

  - name: create dir
    file: path=/opt/jboss state=directory mode=0755

  - name: extract archive
    unarchive: src=/tmp/{{ jboss_package }} dest=/opt/jboss copy=no

```

##### EXPECTED RESULTS

Files inside the zip archive to be extracted to the remote host.
##### ACTUAL RESULTS

ansible fails while extracting the zip file. It always fail when it's encounters a ziped file whose name has spaces in it. 

```
fatal: [pinky]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"backup": null, "content": null, "copy": false, "creates": null, "delimiter": null, "dest": "/opt/jboss", "directory_mode": null, "exclude": [], "extra_opts": [], "follow": false, "force": null, "group": null, "keep_newer": false, "list_files": false, "mode": null, "original_basename": "jboss-5.1.0.GA-jdk6.zip", "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/tmp/jboss-5.1.0.GA-jdk6.zip"}}, "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/opt/jboss/jboss-5.1.0.GA/docs/licenses/CPL - cpl1.0.txt'"}
```
