### ISSUE TITLE
to_yaml/templates white spaces are stripped from variables when expanded, which breaks yaml generation

### ISSUE THREAD

**Issue by earzur** [ansible/ansible#16207]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /Users/erwan/dev/kronoz/api-deployment/ansible/ansible.cfg
  configured module search path = ./modules
```
##### CONFIGURATION

```
[defaults]
vault_password_file= ~/.vault_password
library=./modules
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s
```
##### SUMMARY

When variables are expanded in templates, leading whitespaces are stripped from the strings, which breaks any attempt at using the `to_yml` filter.

I need to generate a YML file template, and i'm trying to substitute a variable in bulk to a YML block inside the template - this is very handy in my case, where that block is repeated over many different templates.
##### STEPS TO REPRODUCE

run the playbook in the following gist: https://gist.github.com/earzur/dc7dd656519dc15e430275f2441b6390

```
ansible-playbook ./test_to_yaml.yml


PLAY ***************************************************************************

TASK [user as dict - OK] *******************************************************
ok: [localhost] => {
    "<type 'dict'>": "VARIABLE IS NOT DEFINED!"
}

TASK [user as yaml - OK] *******************************************************
ok: [localhost] => {
    "msg": "complex:\n  embed: {1st_name: Doe, name: John}\n  simple: xxx\nlist: [1, 2, 3]\n"
}

TASK [two way dump/parse - OK] *************************************************
ok: [localhost]

TASK [parsed user yaml - OK] ***************************************************
ok: [localhost] => {
    "msg": {
        "complex": {
            "embed": {
                "1st_name": "Doe",
                "name": "John"
            },
            "simple": "xxx"
        },
        "list": [
            1,
            2,
            3
        ]
    }
}

TASK [generate test template in YML - KO] **************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=0

cat output.yml

---
test:
  # i would like my embedded user properly dumped here, as is
  user: ## user is totally broken here...
    complex:
  embed: {1st_name: Doe, name: John}
  simple: xxx
list: [1, 2, 3]

  var1: value1
  var2: value2
```

##### EXPECTED RESULTS

i would expect `output.yml` to look like this:

```

---
test:
  # i would like my embedded user properly dumped here, as is
  user:
    complex:
      embed: {1st_name: Doe, name: John}
      simple: xxx
      list: [1, 2, 3]

  var1: value1
  var2: value2
```
##### ACTUAL RESULTS

`output.yml` is generated like this:

```

---
test:
  # i would like my embedded user properly dumped here, as is
  user:
    complex:
  embed: {1st_name: Doe, name: John}
  simple: xxx
list: [1, 2, 3]

  var1: value1
  var2: value2
```

```

```
