### ISSUE TITLE
Ansible evaluates with_items for tasks in blocks skipped by the block when condition

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#16222]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 10860c50bd) last updated 2016/06/10 10:41:16 (GMT +1000)
  lib/ansible/modules/core: (detached HEAD 138430f116) last updated 2016/06/10 13:15:56 (GMT +1000)
  lib/ansible/modules/extras: (detached HEAD 883ccbefe5) last updated 2016/06/10 13:13:56 (GMT +1000)
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

with_items is evaluated even during a skipped block - if the with_items uses a result from a previous task in the block, a deprecation error is printed:

```
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
##### STEPS TO REPRODUCE

```
- hosts: localhost
  connection: local
  vars:
    run_block: true

  tasks:
  - block:
    - name: say hello
      command: echo hello
      register: hello

    - name: do something with results from say hello task
      command: echo {{ item }}
      with_items: "{{ hello.stdout_lines }}"
    when: run_block
```

ansible-playbook -i localhost, skip_when.yml -e run_block=False
##### EXPECTED RESULTS

All tasks skipped, no error message
##### ACTUAL RESULTS

```
ansible-playbook -i localhost, skip_when.yml -e run_block=False

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [say hello] ***************************************************************
skipping: [localhost]

TASK [do something with results from say hello task] ***************************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'stdout_lines'.
This feature will be removed in a 
future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0  
```

**Comment by bcoca** [comment]
the conditional does not apply to the block but to the tasks within

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by willthames** [comment]
Actually, the block is irrelevant. The problem is that the with_items evaluates before the when. 

```
  tasks:
    - name: say hello
      command: echo hello
      register: hello
      when: run_block

    - name: do something with results from say hello task
      command: echo {{ item }}
      with_items: "{{ hello.stdout_lines }}"
      when: run_block
```

has exactly the same problem.

I can see why this is the case - you might want `when: item != 'x'` which you don't know until loop expansion time.

The reason for putting it in a block is that I might want to skip 20 tasks. I suppose I could use two blocks, one for registering the value, and one for a when condition checking if the registration was skipped. But this really does seem like a horrible workaround.
