### ISSUE TITLE
win_regedit syntax error handling

### ISSUE THREAD

**Issue by whbos** [ansible/ansible#16225]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The win_regedit module fails not quite elegantly when the colon character following the registry hive is not specified ('HKCU\Software' instead of 'HKCU:\Software') 
##### STEPS TO REPRODUCE

```
- win_regedit:
    key: HKCU\Software
    value: test
    data: test
    datatype: string
```
##### EXPECTED RESULTS

Syntax Error.
##### ACTUAL RESULTS

fatal: [windows_server]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_regedit"}, "msg": "Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available."}
