### ISSUE TITLE
Client certificate authentication with WinRM needs documentation

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#16243]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

v2.1
##### CONFIGURATION

``` yaml
ansible_winrm_transport: certificate
ansible_winrm_cert_pem: /home/XXX/ansible/certs/winrm_client_cert.pem
ansible_winrm_cert_key_pem: /home/XXX/ansible/certs/winrm_client_cert.key
```
##### OS / ENVIRONMENT

RHEL 6.8
python-2.6.6
pywinrm-0.2.0
ansible-2.1.0.0
Windows 10
##### SUMMARY

I cannot make certificate authentication work with WinRM and Windows 10.

After generating the right files, adding them to the Certificate store on Windows 10 and providing them to Ansible/pywinrm I get the below error nevertheless:

```
[dag@moria crombeen]$ ansible-playbook -l windows1 certificate.yml 

PLAY [all] *********************************************************************

TASK [win_copy] ****************************************************************
Enter PEM pass phrase:
fatal: [windows1]: UNREACHABLE! => {"changed": false, "msg": "certificate: the specified credentials were rejected by the server", "unreachable": true}
        to retry, use: --limit @certificate.retry

PLAY RECAP *********************************************************************
windows1                   : ok=0    changed=0    unreachable=1    failed=0   
```

According to this page, this only works on Windows 10 when using certificates generated through
ADCS (Active Directory Certificate Services) and not OpenSSL. Since I do not have access to ADCS I cannot verify whether this is exactly the problem, or something else is wrong.
