### ISSUE TITLE
"rescue" block not called on fail

### ISSUE THREAD

**Issue by dcodix** [ansible/ansible#16254]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
blocks

##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 7aca70b4b0) last updated 2016/06/13 13:22:19 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 138430f116) last updated 2016/06/13 13:23:00 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 883ccbefe5) last updated 2016/06/13 13:23:10 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

I had this problem some time ago, and I think it was already solved, but I tested with the last development code and it seems it happens again... So I am not sure if maybe I am doing something wrong.
It seems the "rescue" block is not being executed when there is a fail inside the "block" block.
##### STEPS TO REPRODUCE

cat main.yml

```
- name: testansibleblocks
  hosts: localhost
  become: yes
  gather_facts: True
  tasks:
    - include: src/testansibleblocks/testansibleblocks.yml
```

cat src/testansibleblocks/testansibleblocks.yml

```

---
- block:
  - include: "tasks/dir1.yml"

  - include: "tasks/dir2.yml"

  - include: "tasks/dir3.yml"

  rescue:
  - include: "tasks/dir4.yml"
  always:
  - include: "tasks/dir5.yml"

  any_errors_fatal: yes
```

cat src/testansibleblocks/tasks/dir1.yml (the other "dir" tasks are the same just changing the number)

```
- name: dir1
  file: path=/tmp/testansibledirs/dir1 state=directory
```
##### RESULTS

$ ansible-playbook -i inv main.yml

```
PLAY [testansibleblocks] *******************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [dir1] ********************************************************************
changed: [localhost]

TASK [dir2] ********************************************************************
changed: [localhost]

TASK [dir3] ********************************************************************
changed: [localhost]

TASK [dir5] ********************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=4    unreachable=0    failed=0
```

$ rm /tmp/testansibledirs/dir\* -fr
$ touch /tmp/testansibledirs/dir1
$ ansible-playbook -i inv main.yml

```
PLAY [testansibleblocks] *******************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [dir1] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "gid": 2001, "group": "deployer", "mode": "0664", "msg": "/tmp/testansibledirs/dir1 already exists as a file", "owner": "deployer", "path": "/tmp/testansibledirs/dir1", "size": 0, "state": "file", "uid": 2001}

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'main.retry'.         Unable to create local directories(): [Errno 2] No such file or
directory: ''


PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

As you can see after "dir1" creation fails "dir4" (which is inside the rescue) is not created. I think it is supposed to be created but I am not sure if I hace something wrong with my play or if something is changed.
