### ISSUE TITLE
Rollback roles

### ISSUE THREAD

**Issue by gianrubio** [ansible/ansible#16260]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
roles

##### ANSIBLE VERSION
2.2

##### SUMMARY
I've running ansible playbook to create objects in AWS. When I create objects using roles and their have dependencies such as asg attached to elb, and this playbook fail. So I need to destroy all objects. 
Using tasks I can use [blocks](http://docs.ansible.com/ansible/playbooks_blocks.html) to delete the current task object, but I can't delete other dependent objects created by roles. I'm thinking to develop a configuration on_fail_rollback_roles that will execute all roles in playbook and change their state to absent. Does this make any sense to the community? Why ansible does not have this feature yet?
##### Ansible Configuration:
```
---
- hosts: localhost
  connection: local
  any_errors_fatal: true
  on_fail_rollback_roles: true
  vars_files:
    - group_vars/common.yaml
  roles:
    - role: VivaReal.aws-lc
    - role: VivaReal.aws-elb
    - role: VivaReal.aws-asg
    - role: VivaReal.slack-notify
    - { role: VivaReal.aws-route53, aws_route53_value: "{{ aws_elb_dns_name }}" }
    - role: VivaReal.slack-notify

... rollback
roles:
    - { role: VivaReal.aws-lc, state:absent}
    - { role: VivaReal.aws-elb, state:absent}
    - { role: VivaReal.aws-asg, state:absent}
    - { role: VivaReal.slack-notify, state:absent}
    - { role: VivaReal.aws-route53, aws_route53_value: "{{ aws_elb_dns_name }}" }
    - role: VivaReal.slack-notify
```

**Comment by nitzmahone** [comment]
There are some changes being discussed that might make this easier to do using the existing block infrastructure (roles-as-tasks, role libraries, etc). That said, this is a big enough feature that if you really want community feedback on it, I'd suggest you might want to close this issue and write a [proposal](https://github.com/ansible/proposals/) instead, then come discuss at an IRC meeting.

**Comment by ansibot** [comment]
@gianrubio Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
@gianrubio this should be possible by combining blocks with rescue and include role.

http://docs.ansible.com/ansible/playbooks_blocks.html
https://docs.ansible.com/ansible/include_role_module.html

Contrived example:
```
- hosts: all
  tasks:
     - block: 
           - include_role: 
                name: role1
       rescue:
            - include_role:
                name: role2
                vars:
                   state: absent
```
