### ISSUE TITLE
Feature request: more flexible tags

### ISSUE THREAD

**Issue by soar** [ansible/ansible#16273]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
2.3

##### SUMMARY
Tags feature isn't too flexible now. For example, I want install packages if they aren't installed, but by-default - preserve current versions. And only if I supply tag "upgrade" - packages should be upgraded to latest versions.
Now I should type something like:
``` yaml
---
- name: install/check packages
  package:
    name="{{ item }}"
    state=present
  with_items:
    - package1
    - package2
  tags:
    - packages
- name: upgrade packages
  package:
    name="{{ item }}"
    state=latest
  with_items:
    - package1
    - package2
  tags:
    - upgrade
```
This code looks ugly and will be executed twice: in first task packages will be checked and installed if they aren't installed in system, in second task - they will be upgraded. 
I think, first of all, there should be a feature, to execute some code if tag doesn't supplied: 
`tags: !upgrade` (sorry, if this feature exists, i didn't find it in [Tags documentation](http://docs.ansible.com/ansible/playbooks_tags.html)).
And, better - tags should be accessible as Jinja2 variables, like this:
``` yaml
- name: install/upgrade packages
  package:
    name="{{ item }}"
    state="{{ 'latest' if 'upgrade' in tags else 'present' }}"
  with_items:
    - package1
    - package2
  tags:
    - packages
```
This code will be clean, and you can simple call it like `ansible-playbook test.yml --tags "packages"` or `ansible-playbook test.yml --tags "packages,upgrade"`

**Comment by bcoca** [comment]
Feature aside, i would to this to handle your issue:

```
- name: install/upgrade packages
  package:
    name="{{ item }}"
    state="{{  (upgrade|default(False))|ternary('latest','present') }}"
  with_items:
    - package1
    - package2
  tags:
    - packages
```

and now you can pass `-e 'upgrade=true'` to force upgrading
