### ISSUE TITLE
Task name not templated in free strategy

### ISSUE THREAD

**Issue by riton** [ansible/ansible#16295]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/.../.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Using default configuration.
##### OS / ENVIRONMENT

_N/A_
##### SUMMARY

Variable are not interpreted in task names using new `free` strategy (`linear` strategy was fixed in #10347 by 7bc789ba64583fdb68e8ab9c8336dbb9b8374797)
##### STEPS TO REPRODUCE

- Using `linear` strategy:

``` yaml

---
- hosts: all
  gather_facts: false
  become: false
  strategy: linear

  vars: {
    "variable": "VALUE"
  }

  tasks:
    - name: "Dynamic task name: {{ variable }}"
      debug:
        msg: "hello there"

  handlers: []
```

output is

```
PLAY [all] *********************************************************************

TASK [Dynamic task name: VALUE] ************************************************
ok: [localhost] => {
    "msg": "hello there"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
- Using the `free` strategy:

``` yaml

---
- hosts: all
  gather_facts: false
  become: false
  strategy: free

  vars: {
    "variable": "VALUE"
  }

  tasks:
    - name: "Dynamic task name: {{ variable }}"
      debug:
        msg: "hello there"

  handlers: []
```

output is:

```
PLAY [all] *********************************************************************

TASK [Dynamic task name: {{ variable }}] ***************************************
ok: [localhost] => {
    "msg": "hello there"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

##### EXPECTED RESULTS

Same behavior in task names evaluation whatever strategy I'm using.
##### ACTUAL RESULTS

`free` strategy does not replace variable in tasks names.

This bug was originally reported by @grumpycatt.
