### ISSUE TITLE
unarchive module seems to brake when file name have a space

### ISSUE THREAD

**Issue by serine** [ansible/ansible#16321]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

I haven't touch any of the configurations - used defualt on ubuntu. Installed through ppa
##### OS / ENVIRONMENT

```
Linux biostation 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
```
##### SUMMARY

This is the error that I'm seeing

```
Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/home/kirill/software/source/FastQC/Help/1 Introduction/'
```

When I look for this file on the remote machine, the file is there ! It appears that because it has a space ansible breaks. 

If i rename to remove the space, then `zip`, then use ansible to unzip. It break at the next file with the space. Once I removed all files that had a space ansible worked fine. 
##### STEPS TO REPRODUCE

```
- name: Download FastQC
  get_url:
    url: "http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v{{ version }}.zip"
    dest: "{{ source_dir }}/fastqc_v{{ version }}.zip"

- name: Uncompress FastQC
  unarchive:
    src: "{{ source_dir }}/fastqc_v{{ version }}.zip"
    dest: "{{ source_dir }}"
    copy: no

```

`source_dir` is your preferred location for source files
`version` either 0.11.4 or latest one is 0.11.5, both break

```
ansible-playbook -vvvv -i hosts bio.yml
```

This is my `bio.yml` playbook

```

---

- name: Installing bioinformatics tools
  hosts: home
  remote_user: "{{ main_guy }}"
  roles:
          # make container for all other installation
          - make_dirs
          # installing BigDataScript
          - bds
          # install everyting into one container
          - bio_tools
```

`fastqc.yml` is one of the tasks in `bio_tools` roles
