### ISSUE TITLE
Deleted newlines after {% endif %}

### ISSUE THREAD

**Issue by jpic** [ansible/ansible#16344]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
  lib/ansible/modules/extras: (detached HEAD b0aec50b9a) last updated 2016/06/10 16:15:36 (GMT +200)
  config file = /home/jpic/.ansible.cfg
  configured module search path = ['/home/jpic/ansible/library', '/usr/share/ansible']

```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Newlines after endif are deleted.
##### STEPS TO REPRODUCE

test.yml

```

---
- hosts: localhost
  tasks:
  - template: src=test.template dest=/tmp/test.out
```

test.template

```
foo: {% if false %}bla{% endif %}
other: test
```

Command

```
ansible-playbook test.yml
```
##### EXPECTED RESULTS

```
foo:
other: test
```
##### ACTUAL RESULTS

```
foo: {% if false %}bla{% endif %}
other: test
```

Bug or feature ? PEBKAC perhaps ? ;)

Thanks for your time !
