### ISSUE TITLE
2.1 Execution fails in a play with one host when some hosts before failed

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#16364]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (stable-2.1 4d4bbcbb33) last updated 2016/06/20 08:55:21 (GMT +200)
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Ubuntu
##### SUMMARY

If there is a play with only one host and before that play if one or more hosts failed, execution will stop after that one host play.
##### STEPS TO REPRODUCE

Use this playbook:

``` yml
# test_fail.yml

---
- hosts: host1:host2:host3
  gather_facts: no
  tasks:
    - ping:
    - fail:
      when: inventory_hostname == 'host3'

- hosts: host4:host5
  gather_facts: no
  tasks:
    - ping:

- hosts: host6
  gather_facts: no
  tasks:
    - ping:

- hosts: host7:host8
  gather_facts: no
  tasks:
    - ping:
```

with this inventory:

```
# test_fail_hosts
host1 ansible_host=localhost ansible_connection=local
host2 ansible_host=localhost ansible_connection=local
host3 ansible_host=localhost ansible_connection=local
host4 ansible_host=localhost ansible_connection=local
host5 ansible_host=localhost ansible_connection=local
host6 ansible_host=localhost ansible_connection=local
host7 ansible_host=localhost ansible_connection=local
host8 ansible_host=localhost ansible_connection=local
```
##### EXPECTED RESULTS

Execution should continue to the end with only `host3` failing.
##### ACTUAL RESULTS

Execution stops after the play with a single host (`host6`):

```
$ ansible-playbook -i test_fail_hosts test_fail.yml -CD

PLAY [host1:host2:host3] *******************************************************

TASK [ping] ********************************************************************
ok: [host2]
ok: [host3]
ok: [host1]

TASK [fail] ********************************************************************
skipping: [host1]
skipping: [host2]
fatal: [host3]: FAILED! => {"changed": false, "failed": true, "msg": "Failed as requested from task"}

NO MORE HOSTS LEFT *************************************************************

PLAY [host4:host5] *************************************************************

TASK [ping] ********************************************************************
ok: [host4]
ok: [host5]

NO MORE HOSTS LEFT *************************************************************

PLAY [host6] *******************************************************************

TASK [ping] ********************************************************************
ok: [host6]

NO MORE HOSTS LEFT *************************************************************
 [WARNING]: Could not create retry file 'test_fail.retry'.         [Errno 2] No such file or directory: ''


PLAY RECAP *********************************************************************
host1                      : ok=1    changed=0    unreachable=0    failed=0   
host2                      : ok=1    changed=0    unreachable=0    failed=0   
host3                      : ok=1    changed=0    unreachable=0    failed=1   
host4                      : ok=1    changed=0    unreachable=0    failed=0   
host5                      : ok=1    changed=0    unreachable=0    failed=0   
host6                      : ok=1    changed=0    unreachable=0    failed=0   
```
