### ISSUE TITLE
Missing a with_items/when combination

### ISSUE THREAD

**Issue by ejournet** [ansible/ansible#16366]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

ansible 2.1.0.0
##### CONFIGURATION

configured module search path = Default w/o overrides
##### OS / ENVIRONMENT

CentOS 6
##### SUMMARY

I'm looking for a mean to combine conditions (with when) and list (with with_items). 
Example : I need to copy several files, I'll use the with_items tool. But if now I want to copy one of these files under a condition, I'll have to create a new step. 
##### STEPS TO REPRODUCE

If I want to copy "example2" file on "condition" : 

```
with_items:
  - example1
  - example2
    when : condition
  - example3
```

If I want to copy "example1" on "condition1" and "example2" on "condition2" : 

```
with_items:
 - example1
   when : condition1
 - example2
   when : condition2

```

(sorry for formatting, didnt quite get how to do it)
##### EXPECTED RESULTS

First example : example1 and example3 are normally copied but example2 is only copied when condition is fulfilled.
Second example : example1 is copied when condition1 fulfilled and example2 is copied when condition2 fulfilled
##### ACTUAL RESULTS

Syntax Error

**Comment by kustodian** [comment]
Why not use something like this:

``` yml
- copy: src={{ item }} dest=/some/dest
  when: (item='example1' and condition1) or (item='example2' and condition2)
  with_items:
    - example1
    - example2
```

You better give a concrete example what you want to do, there is probably a way to do it already.

**Comment by ejournet** [comment]
Nice solution, Thanks

Though, the syntax becomes unclear in case of multi iteming 

```
- copy: src={{ item.src }} dest={{ item.dst }}
  with_items:
  - { src: '/home/very/long/path/for/source/file1', dst: '/home/very/long/path/for/dest/file1'}
  - { src: '/home/very/long/path/for/source/file2', dst: '/home/very/long/path/for/dest/file2'}
  - { src: '/home/very/long/path/for/source/file3', dst: '/home/very/long/path/for/dest/file3'}
```

In this case if I pass a variable "number" to my playbook, which can be 1, 2 or 3, and which gives the file who will be actually copied, is there a readable way to do the following ?

```
- copy: src={{ item.src }} dest={{ item.dst }}
  with_items:
  - { src: '/home/very/long/path/for/source/file1', dst: '/home/very/long/path/for/dest/file1'}
     when: number=1
  - { src: '/home/very/long/path/for/source/file2', dst: '/home/very/long/path/for/dest/file2'}
    when: number=2
  - { src: '/home/very/long/path/for/source/file3', dst: '/home/very/long/path/for/dest/file3'}
    when: number=3
```

(I think we can agree that above solution is not clear for such case, even more when the variable becomes more complexe).

My concrete example is : I want to deploy a playbook on 2 different servers which only differs by one configuration file. Amongst many other configuration files which remains the same for any server, I'd like to be able to designate which one of two others specific files should be used for such or such server : 
This : 

```
- copy: src={{ item.src }} dest={{ item.dst }}
  with_items:
  - { src: '/home/very/long/path/for/source/file1', dst: '/home/very/long/path/for/dest/file1'}
  - { src: '/home/very/long/path/for/source/file2', dst: '/home/very/long/path/for/dest/file2'}
  - { src: '/home/very/long/path/for/source/file3', dst: '/home/very/long/path/for/dest/file3'}
  - { src: '/home/very/long/path/for/source/file4', dst: '/home/very/long/path/for/dest/file4'}
  - { src: '/home/very/long/path/for/source/specific/file1', dst: '/home/very/long/path/for/dest/specific/file2'}
    when: number=1
  - { src: '/home/very/long/path/for/source/specific/file2', dst: '/home/very/long/path/for/dest/specific/file2'}
    when: number=2
```

**Comment by kustodian** [comment]
That's very easy to do, but it should be done totally differently.

You should define a variable e.g. `copy_files_specific`, which will be set differently for each server (or server group) in group_vars/host_vars, e.g. if the hosts are called `host1`, `host2` and `host3`, host vars should look like this:

``` yml
# host_vars/host1
copy_files_specific:
  - { src: '/home/very/long/path/for/source/specific/file1', dst: '/home/very/long/path/for/dest/specific/file1'}
```

``` yml
# host_vars/host2
copy_files_specific:
  - { src: '/home/very/long/path/for/source/specific/file2', dst: '/home/very/long/path/for/dest/specific/file2'}
```

``` yml
# host_vars/host3
copy_files_specific:
  - { src: '/home/very/long/path/for/source/specific/file3', dst: '/home/very/long/path/for/dest/specific/file3'}
```

and you can have a variable with common configuration files which will be copied to all hosts, e.g. `copy_files`:

``` yml
copy_files:
  - { src: '/home/very/long/path/for/source/file1', dst: '/home/very/long/path/for/dest/file1'}
  - { src: '/home/very/long/path/for/source/file2', dst: '/home/very/long/path/for/dest/file2'}
  - { src: '/home/very/long/path/for/source/file3', dst: '/home/very/long/path/for/dest/file3'}
  - { src: '/home/very/long/path/for/source/file4', dst: '/home/very/long/path/for/dest/file4'}
```

then you just need one task:

``` yml
- copy: src={{ item.src }} dest={{ item.dst }}
  with_flattened:
    - "{{ copy_files }}"
    - "{{ copy_files_specific }}"
```

Also you don't have to use `with_flattened`, you can always use two tasks, one to loop over `copy_files`, one over `copy_files_specific`.

**Comment by bcoca** [comment]
many ways to do this, here is another:

```
- copy: src={{item.name}} ...
  when: item.condition
  with_items:
   - { name: filename, condition: example3}
```
