### ISSUE TITLE
Help sudoing to a non-privilege User

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#16374]
##### ISSUE TYPE

- Bug Report/Documentation Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/ansible/.ansible.cfg
  configured module search path = Default w/o overrides

```
##### STEPS TO REPRODUCE

```

---
   - hosts: XXXX303
     user: ansible
     become_user: bXX
     vars_files:
     # User defined variables
       - java-vars.yml
     tasks:
      - name: touch file to determine owner
        file: path={{ target_path }}/touched_file_to_get_file_owner state=touch mode="u=rw,g=r,o=r"

```

##### ACTUAL RESULTS

```
This creates/touches a file as follows:
-rw-r--r--    1 ansible  ansible           0 Jun 20 16:21 touched_file_to_get_file_owner 

I would have expect the file to be owned by bXX

Thanks a lot
```
