### ISSUE TITLE
Allow listen on list of keywords

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#16378]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel b7f9037b5b) last updated 2016/06/21 10:17:20 (GMT +200)
```
##### SUMMARY

With https://github.com/ansible/proposals/issues/11 added to the core, handlers can now listen on a keyword, which is a great. The problem is that they can only listen on one keyword, and often different events need to call the same handler. If we use an example from the mentioned proposal, handler `restart httpd` listens on `event_ssl_changed`, but httpd also needs to be restarted when e.g. PHP is updated, or PHP configuration change, which means PHP changes should notify something like `event_php_changed`. Because of this it would be useful that `listen:` allows to specify a list of keywords:

``` yml
# roles/role1/handlers/main.yml
- name: restart httpd
  service: name=httpd state=restarted
  listen:
    - event_ssl_changed
    - event_php_changed
```

Currently the only workaround for this I could think of is to create a new handler which listens on `event_php_changed` and then notifies `restart httpd`, or something like that, but that looks bad.

Also since `notify` supports notifying multiple handlers, why not make `listen` support listening on multiple keywords.
