### ISSUE TITLE
Pipelining and remote_tmp

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#16386]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/ansible/.ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

I have a .ansible.cfg in the working directory with these values set:
pipelining = True
remote_tmp     = /home/ansible/.ansible/tmp
##### OS / ENVIRONMENT

ACS = RHEL7
Target = AIX7.1
##### SUMMARY

Playbook still tries to write modules to /tmp
##### STEPS TO REPRODUCE

```
I have a ansible.cfg in the working directory with these values set:

pipelining = True
remote_tmp     = /home/ansible/.ansible/tmp


---
   - hosts: XXXX303
     user: ansible
     become: true
     become_user: bXX
     #remote_tmp: /home/bea/.ansible/tmp
     vars_files:
     # User defined variables
       - java-vars.yml
     tasks:
      - name: touch file to determine owner
        file: path={{ target_path }}/touched_file_to_get_file_owner state=touch mode="u=rw,g=r,o=r"

```

##### EXPECTED RESULTS

Iwould not expect to see error for sudo unable to write to /tmp
##### ACTUAL RESULTS

```
ansible-playbook sudotest.yml --ask-become-pass -vvvv
Using /ansible/playbooks/WHS/java8/ansible.cfg as config file
SUDO password:
Loaded callback default of type stdout, v2.0

PLAYBOOK: sudotest.yml *********************************************************
1 plays in sudotest.yml

PLAY [XXXXX03] *****************************************************************

TASK [setup] *******************************************************************
<XXXX303> ESTABLISH SSH CONNECTION FOR USER: ansible
<XXXX03> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r sv63303 '/bin/sh -c '"'"'sudo -H -S  -p "[sudo via ansible, key=qizyywqasydgxuvxgxrxkminlusjfeut] password: " -u bea /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-qizyywqasydgxuvxgxrxkminlusjfeut; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [sv63303]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "setup"}, "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 3: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 12297\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nSorry, user ansible is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-qizyywqasydgxuvxgxrxkminlusjfeut; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python' as bea on sv63303.\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @sudotest.retry

PLAY RECAP *********************************************************************
XXXX303                    : ok=0    changed=0    unreachable=0    failed=1

```
