### ISSUE TITLE
lineinfile with wildcards (asterisk/star) within a hash -> failing when there is an regexp like below.

### ISSUE THREAD

**Issue by ReSearchITEng** [ansible/ansible#16399]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/docker/vra/ansible-vra/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I have the below ansible playbook, which fails to insert an asterisk ('*') in a file when the below regexp is defined. The moment I comment out the regexp, it starts working and is able to insert the line as expected (as shown in ACTUAL RESULTS)
##### STEPS TO REPRODUCE

```
    - name: limits.conf
      lineinfile: line='{{item.domain}} {{item.type}} {{item.item}} {{item.value}}' dest={{limits_conf_path}} create=yes regexp='\s*{{item.domain}}\s*{{item.type}}\s*{{item.item}}\s*'
      with_items:
        - domain: '*'
          item: 'nofile'
          type: 'soft'
          value: '8192'
```

##### EXPECTED RESULTS

the file will have a line like: 
`* soft nofile 8192`
##### ACTUAL RESULTS

`<!---  failed: [machine] (item={u'item': u'nofile', u'domain': u'*', u'type': u'soft', u'value': u'8192'}) => {"failed": true, "invocation": {"module_name": "lineinfile"}, "item": {"domain": "*", "item": "nofile", "type": "soft", "value": "8192"}, "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /home/docker/.ssh/config\r\ndebug1: /home/docker/.ssh/config line 6: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18730\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to machine closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_wqnC69/ansible_module_lineinfile.py\", line 415, in <module>\r\n    main()\r\n  File \"/tmp/ansible_wqnC69/ansible_module_lineinfile.py\", line 404, in main\r\n    ins_aft, ins_bef, create, backup, backrefs)\r\n  File \"/tmp/ansible_wqnC69/ansible_module_lineinfile.py\", line 207, in present\r\n    mre = re.compile(regexp)\r\n  File \"/usr/lib64/python2.7/re.py\", line 190, in compile\r\n    return _compile(pattern, flags)\r\n  File \"/usr/lib64/python2.7/re.py\", line 242, in _compile\r\n    raise error, v # invalid expression\r\nsre_constants.error: multiple repeat\r\n", "msg": "MODULE FAILURE", "parsed": false} -->`

```
 failed: [machine] (item={u'item': u'nofile', u'domain': u'*', u'type': u'soft', u'value': u'8192'}) => {"failed": true, "invocation": {"module_name": "lineinfile"}, "item": {"domain": "*", "item": "nofile", "type": "soft", "value": "8192"}, "module_stderr": "OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013\r\ndebug1: Reading configuration data /home/docker/.ssh/config\r\ndebug1: /home/docker/.ssh/config line 6: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18730\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to machine closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_wqnC69/ansible_module_lineinfile.py\", line 415, in <module>\r\n    main()\r\n  File \"/tmp/ansible_wqnC69/ansible_module_lineinfile.py\", line 404, in main\r\n    ins_aft, ins_bef, create, backup, backrefs)\r\n  File \"/tmp/ansible_wqnC69/ansible_module_lineinfile.py\", line 207, in present\r\n    mre = re.compile(regexp)\r\n  File \"/usr/lib64/python2.7/re.py\", line 190, in compile\r\n    return _compile(pattern, flags)\r\n  File \"/usr/lib64/python2.7/re.py\", line 242, in _compile\r\n    raise error, v # invalid expression\r\nsre_constants.error: multiple repeat\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

**Comment by sivel** [comment]
You are likely going to need to escape those inputs to avoid this issue using the `regex_escape` jinja2 filter.

Such as:

```
- name: limits.conf
      lineinfile: line='{{item.domain}} {{item.type}} {{item.item}} {{item.value}}' dest={{limits_conf_path}} create=yes regexp='\s*{{item.domain|regex_escape}}\s*{{item.type}}\s*{{item.item}}\s*'
      with_items:
        - domain: '*'
          item: 'nofile'
          type: 'soft'
          value: '8192'
```
