### ISSUE TITLE
Provide a way to run some tasks after failure, at the playbook level

### ISSUE THREAD

**Issue by rfleschenberg** [ansible/ansible#16437]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Playbooks

##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/rene/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I use Ansible for application deployments. I want to make sure that only one deployment, or only one deployment per project, runs against a given server at a time, to avoid race conditions, problems with apt locking, and so on. So at a certain point in my playbook, I would like to create a lockfile. I would then like to remove that lockfile at the end of the playbook, no matter if there was an error or not. `block:` / `always:` exists, but it is not quite flexible enough to write this in a nice way, because a block needs to be insisde a `tasks:` item. Here is an example of a syntax style I would like to have:

```
- hosts: appservers
  roles:
  - appserver
  - another_role
  pre_tasks:
  - name: Wait for lockfile
    wait_for:
      path: /tmp/deployment.{{ project_name }}.lock
      state: absent
  - name: Write lockfile
    command: lockfile /tmp/deployment.{{ project_name }}.lock
  post_tasks:
  - name: Remove lockfile
    file:
      path: /tmp/deployment.{{ project_name }}.lock
      state: absent
    ***run_always: true***
```

At the moment, I have to remove the lockfile manually after a failure. It would be nice if I could handle this from my playbook.

**Comment by Ehekatl** [comment]
+1, it would be really helpful if ansible could support block in plays level

**Comment by Jorge-Rodriguez** [comment]
A top level playbook of this kind would be really handy:

``` yaml
---
- block:
  - include: do_something.yml
  - include: do_something_else.yml
  rescue:
  - include: cleanup.yml
  always:
  - include: always_run.yml
```

**Comment by ansibot** [comment]
@rfleschenberg Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
So a simple solution for this is running the **playbook** using **flock**, this will hold a lock until the playbook finishes.

A best practice for cron jobs is to run them using flock like this to avoid starting more cron jobs when a previous job is still running/stalls.

**Comment by Jorge-Rodriguez** [comment]
@dagwieers Using flock seems to only address the OP use case, which then again does solve the OP's problem, however, @Ehekatl proposes a much more versatile solution.

**Comment by dagwieers** [comment]
@Jorge-Rodriguez I am not dismissing the original request, just providing one way to do it (which is free from issues, which any in-playbook solution will have on sudden failure or interruption). Otherwise I would have close the issue :-)

**Comment by dagwieers** [comment]
If anyone wants to take this forward, you can create a proposal at: https://github.com/ansible/proposals

The same is already possible from within a play, but doing this on the play-level means the scope could be different for each of the included plays. Remember that tasks run on a per-target basis, and a lock-file is something you would do within the playbook context, not per necessarily target. The example would fail if you have more than one target using the same lockfile.

needs_contributor

**Comment by rfleschenberg** [comment]
As far as I see, flock doesn't solve the problem if there is potentially more than one ansible control machine. This issue is about having a lock file on the target machine.

**Comment by dagwieers** [comment]
A rescue block doesn't solve your problem either, because you can't ensure the lockfile is always released.
Feel free to make that proposal.

**Comment by rfleschenberg** [comment]
Yes, having a way to make sure the lockfile is always released is the point of this issue :)

**Comment by D3DeFi** [comment]
Have you been able to tackle this? I am trying to implement something similar. Would opt to use block/ always, but that doesn't work with `any_errors_fatal` or `max_fail_percentage` (ref: #31543), thus negating the whole point of safe rolling updates, atleast in my use case.

**Comment by roumano** [comment]
Other senario usefull if it's implemented : 
* a way do get deeper information when something is failing
* a use case : 
a handler failed to start a service, like here : 
[Exemple of Travis Test failed without useful information](https://travis-ci.org/sensu/sensu-ansible/jobs/335187092)
```
TASK [role_under_test : Ensure Sensu server service is running] ****************
fatal: [localhost]: FAILED! => {"changed": false, "msg": " * Starting sensu-server\n   ...fail!\n"}
```
i would like to run somethink like `journalctl -e /usr/sbin/sensu-server` or `systemctl status sensu-server`

**Comment by gabrgomes** [comment]
This feature would provide an easy way to implement rollbacks and notifications in case any role of a playbook fails. This is something I have to do for all my roles individually, which is not nice.

**Comment by joefodor** [comment]
This would be great so that if my entire play fails I can use snow_record to update my service now ticket with information that the play failed and other information of maybe why

**Comment by WarpRat** [comment]
I have a playbook in which almost all of the tasks loop, preventing me from using block/rescue syntax. Is there an effective workaround to call the ansible slack module to notify me on failure, or any chance block will support loops in the future?

**Comment by andrefecto** [comment]
Would definitely like to see something like this implemented. I originally used the include_roles option with a rescue block which works great for sending failure notifications. Except when you want to use tags from inside of those roles. From all the digging around I can find, tags applied to tasks in a role that is then imported with any type of include, don't get bubbled up so you can use them when running the playbook. 

Being able to have something like post_tasks execute even if the playbook fails would be super helpful. Could even be a new section called tasks_on_failure or something.

**Comment by tentacode** [comment]
Hello 👋  I have a perfect use case for this : https://stackoverflow.com/questions/68754227/running-a-task-in-ansible-if-there-was-any-error-during-the-playbook?noredirect=1#comment121508438_68754227

if anyone has a workaround do tell me !

**Comment by hasan4791** [comment]
Hello, in mycase, host is locally running some playbooks & externally, I'm waiting for the host to complete its local playbook execution & to perform other tasks on success. When the result is failure, the execution stops right there & ansible-playbook returns non-zero which is perfect. The error handling i require here is, On Failure, i need to display the logs from the host(where the playbooks are executed locally) and then stop the execution & return non-zero from the ansible-playbook. Something like "after_failure:" parameter in .travis file

**Comment by konstruktoid** [comment]
> Other senario usefull if it's implemented :
> 
> * a way do get deeper information when something is failing
> * a use case :
>   a handler failed to start a service, like here :
>   [Exemple of Travis Test failed without useful information](https://travis-ci.org/sensu/sensu-ansible/jobs/335187092)
> 
> ```
> TASK [role_under_test : Ensure Sensu server service is running] ****************
> fatal: [localhost]: FAILED! => {"changed": false, "msg": " * Starting sensu-server\n   ...fail!\n"}
> ```
> 
> i would like to run somethink like `journalctl -e /usr/sbin/sensu-server` or `systemctl status sensu-server`

Why not use `register` and/or `stat` on that `systemctl` and handle the output? 

E.g.:
```yaml
- name: register timesyncd status
  command: systemctl status systemd-timesyncd
  register: timesyncd_status
  
- name: timedatectl set-ntp
  become: 'yes'
  command: timedatectl set-ntp true
  when: timedatectl_show.stdout.find('NTPSynchronized=yes') == -1 and timesyncd_status.rc == 0
```

https://github.com/konstruktoid/ansible-role-hardening/blob/master/tasks/timesyncd.yml#L19-L47
