### ISSUE TITLE
docker_container no works correctly

### ISSUE THREAD

**Issue by revengel** [ansible/ansible#16472]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

```
[defaults]
hostfile = invs
host_key_checking = False
```
##### OS / ENVIRONMENT

Arch linux
##### SUMMARY

I'm trying to run docker swarm container

Using _docker_ module:

```
- name: Start docker swarm agent
  docker:
    image: "{{ docker_swarm_image }}"
    name: "swarm_agent"
    detach: True
    command: "join --addr={{ ansible_host }}:{{ docker_port }} {{ kv_address }}"
    state: restarted
    pull: always
    restart_policy: always
    restart_policy_retry: 3`
```

Swarm works well. But this module is deprecated

Trying to use new module docker_container:

```

---
- name: Installing docker swarm
  docker_container:
    image: '{{ docker_swarm_image }}'
    name: swarm_agent
    detach: yes
    command: "join --advertise={{ ansible_host }}:{{ docker_port }} {{ kv_address }}"
    state: started
    restart: yes
    pull: yes
    restart_policy: always
    restart_retries: 3

---
```

The container exit with error.

```
fc01635c82cb        swarm:latest             "/swarm 'join --adver"   About a minute ago   Restarting (0) 40 seconds ago   2375/tcp                           swarm_agent
```

```
$docker -H 192.168.0.51:2375 logs fc01635c82cb

No help topic for 'join --advertise=192.168.0.51:2375 consul://192.168.0.51:8500/swarm'
No help topic for 'join --advertise=192.168.0.51:2375 consul://192.168.0.51:8500/swarm'
No help topic for 'join --advertise=192.168.0.51:2375 consul://192.168.0.51:8500/swarm'
No help topic for 'join --advertise=192.168.0.51:2375 consul://192.168.0.51:8500/swarm'
No help topic for 'join --advertise=192.168.0.51:2375 consul://192.168.0.51:8500/swarm'
No help topic for 'join --advertise=192.168.0.51:2375 consul://192.168.0.51:8500/swarm'

```

The errors in log looks like I start following command:

```
$swarm 'join --advertise=192.168.0.51:2375 consul://192.168.0.51:8500/swarm' --help
```
