### ISSUE TITLE
Align vars in playbook and inventory

### ISSUE THREAD

**Issue by jhoekx** [ansible/ansible#165]
Currently playbooks define vars like:

```

---
- hosts: all
  vars:
    template: "../templates"
    netconfig_dir: "/etc/sysconfig/network-scripts"
  tasks:
  - name: do this
    action: ...
  - name: do that
    action: ...
```

For the inventory I didn't pay enough attention to this and designed the format as:

```

---
- group: greek
  hosts:
  - zeus
  - hera
  - poseidon
  vars:
  - ansible_ssh_port: 3000
  - ntp_server: olympus.example.com
```

Note the dash. Every other list item in a playbook has a dash (vars_files, notify). I get where it originates (hash vs list) and in that light it makes sense, but I believe it doesn't make sense to the casual observer.

Options:
- Change vars in inventory to match the style in playbooks
- Support 'listed vars' in playbooks too
- Support both syntaxes everywhere.

I can fix it any way you like. I prefer 3 as it gives the most flexibility...
