### ISSUE TITLE
docker_image: tagging without pushing to repository?

### ISSUE THREAD

**Issue by RRAlex** [ansible/ansible#16525]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### COMPONENT NAME

ansible / docker_image / repository
(edited after ansible bot's request)

##### SUMMARY

As per the documentation:

`repository (added in 2.1)  no           Full path to a repository. Use with state 'present' to tag the image into the repository.`
`tag    no  latest  Used to select an image when pulling. Will be added to the image when pushing, tagging or building. Defaults to 'latest' when pulling an image.`

... There doesn't seem to be a way to tag _without_ pushing to the repository? (unless I'm using the wrong options?)
##### STEPS TO REPRODUCE

using name: & repository: together also push.
A "tag_only" or "nopush" option might be a solution?

```
- name: Tag container
  docker_image:
    name: "{{ docker_registry_host }}/container_name"
    registry: "{{ docker_registry_host }}/some_new_name:and_or_new_tag"
```
##### EXPECTED RESULTS

Download the image and also tag it to a new name.
##### ACTUAL RESULTS

Getting an error about pushing to the new tag repo... (or just pushing basically)
