### ISSUE TITLE
Host Filters Not Working with --extra-vars

### ISSUE THREAD

**Issue by bubba-h57** [ansible/ansible#16527]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /usr/lib/ReproConnect/bubba-Deploy/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
ansible_python_interpreter  = /var/lib/ReproConnect/python/bin/python
```
##### OS / ENVIRONMENT

```
Linux prd-citadel-3170 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

When passing in `--extra-vars` on the command line, my host pattern, which uses them gets extra commas inserted into the string, seemingly randomly. However, if I simply use the default vars with no --extra-vars overriding, it works as expected.
##### STEPS TO REPRODUCE

Playbook

```

---
- name: "This is just for testing!"
  vars:
    aws_region: "us-east-1"
    type: WEB
    env: QA
  hosts: '~{{ env | lower }}_{{ type|lower }}_\d\d\d\d:&{{aws_region}}'
  gather_facts: True
```

Command

```
ansible-playbook test.yml -e "type=WEB, env=PRD" --list-hosts 
```

##### EXPECTED RESULTS

```
playbook: test.yml

  play #1 (~prd_web_\d\d\d\d:&us-east-1): This is just for testing!    TAGS: []
    pattern: [u'~prd_web_\\d\\d\\d\\d:&us-east-1']
    hosts (3):
      prd_web_1185_vpc_rc
      prd_web_2213_vpc_rc
      prd_web_3237_vpc_rc
```
##### ACTUAL RESULTS

```
ansible-playbook test.yml -e "type=WEB, env=PRD" --list-hosts -vvvv                                                      

Using /usr/lib/ReproConnect/bubba-Deploy/ansible/ansible.cfg as config file
1 plays in test.yml

playbook: test.yml

  play #1 (~prd_web,_\d\d\d\d:&us-east-1): This is just for testing!    TAGS: []
    pattern: [u'~prd_web,_\\d\\d\\d\\d:&us-east-1']
    hosts (3):
      prd_web_1185_vpc_rc
      prd_web_2213_vpc_rc
      prd_web_3237_vpc_rc
```

**Comment by bubba-h57** [comment]
Sometimes I get:

```
play #1 (~prd,_web,_\d\d\d\d:&us-east-1): This is just for testing!    TAGS: []
    pattern: [u'~prd,_web,_\\d\\d\\d\\d:&us-east-1']
```

or

```
play #1 (~prd,_web_\d\d\d\d:&us-east-1): This is just for testing!    TAGS: []
    pattern: [u'~prd,_web_\\d\\d\\d\\d:&us-east-1']
```

I can't make sense of it. However,

```
- name: "This is just for testing!"
  vars:
    aws_region: "us-east-1"
    type: WEB
    env: QA
    pattern1: '~{{ env | lower }}_{{ type|lower }}_\d\d\d\d:&{{aws_region}}'
    pattern2: '{{ pattern1 | regex_replace(",", "")}}'
  hosts: '{{pattern2}}'
  gather_facts: True
```

Appears to be a workaround?
