### ISSUE TITLE
apt: default_release not checked if the package is already installed

### ISSUE THREAD

**Issue by ludovic-gasc** [ansible/ansible#16536]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION
```
ansible 2.1.0 (devel 9005f91bb0) last updated 2016/03/22 111217 (GMT +200)
lib/ansible/modules/core (detached HEAD d71b9bae89) last updated 2016/03/22 111221 (GMT +200)
lib/ansible/modules/extras (detached HEAD d5030ae555) last updated 2016/03/22 111224 (GMT +200)
config file =
configured module search path = Default w/o overrides
```

##### CONFIGURATION
Standard.

##### OS / ENVIRONMENT
Launch on Ubuntu 14.04
Targets Debian 8

##### SUMMARY
If a deb package is already installed, Ansible doesn't check if the version from default_release.

##### STEPS TO REPRODUCE
- Install redis-server on Debian 8
- Enable jessie-backports repository
- Execute this playbook:
```
- name: Install redis
  tags:
    - redis
  apt: name={{ item }} state=present default_release=jessie-backports
  with_items:
    - redis-server
```

##### EXPECTED RESULTS
Ansible should upgrade redis-server package from jessie-backports

##### ACTUAL RESULTS
Ansible does nothing because it considers that the package is already installed. It's true, but in the wrong version.

**Comment by ludovic-gasc** [comment]
Gentle ping :-)
A sprint code is planned for EuroPython 2016 ?

**Comment by ansibot** [comment]
@GMLudo Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ludovic-gasc** [comment]
Description updated.

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hentismith** [comment]
same problem here. We upgraded to mono-project repo and found an issue and needed to downgrade to stretch version again. 

CLI `apt-get -s install -t 9.4 mono-devel` works perfectly, 
`apt: name="mono-devel" default_release=9.4 state=latest` installs the latest mono-project version.

**Comment by jctanner** [comment]
Used this test playbook on a jessie64 vagrant box

```
- hosts: jessie64
  user: vagrant
  become: True
  #connection: local
  gather_facts: False
  tasks:
    - shell: "{{ item }}"
      failed_when: False
      with_items:
          - killall redis-server
          - apt-get autoremove -y redis-server
          - dkpg -r redis-server
          - dpkg -r redis-tools
          - rm -rf /etc/redis

    - apt_repository:
        repo: 'deb http://http.debian.net/debian jessie-backports main contrib non-free'
        state: absent
        update_cache: yes

    - apt: name=redis-server state=present
      failed_when: False
    - shell: dpkg -l redis-server | tail -n1 | awk '{print $3}'
      register: redis_version1

    - apt_repository:
        repo: 'deb http://http.debian.net/debian jessie-backports main contrib non-free'
        state: present
        update_cache: yes

    - apt: name=redis-server state=present default_release=jessie-backports
      failed_when: False
    - shell: dpkg -l redis-server | tail -n1 | awk '{print $3}'
      register: redis_version2

    - assert:
        that:
            - "redis_version1.stdout == '2:2.8.17-1+deb8u5'"
            - "redis_version2.stdout == '3:3.2.8-2~bpo8+1'"
```

The package version moved from 2:2.8.17-1+deb8u5 to 3:3.2.8-2~bpo8+1 with devel. This is the underlying command it ran on the second apt call...

```
/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"     install 'redis-server' -t 'jessie-backports'
```

I have also run the test through every ansible version since 2.1.0 ...

version | rc
------ | ------
v2.1.0.0-0.1.rc1 |  0
v2.1.0.0-0.2.rc2 |  0
v2.1.0.0-0.3.rc3 |  0
v2.1.0.0-0.4.rc4 |  0
v2.1.0.0-1 |  0
v2.1.1.0-0.1.rc1 |  0
v2.1.1.0-0.2.rc2 |  0
v2.1.1.0-0.3.rc3 |  0
v2.1.1.0-0.4.rc4 |  0
v2.1.1.0-0.5.rc5 |  0
v2.1.1.0-1 |  0
v2.1.2.0-0.1.rc1 |  0
v2.1.2.0-0.2.rc2 |  0
v2.1.2.0-0.3.rc3 |  0
v2.1.2.0-0.4.rc4 |  0
v2.1.2.0-0.5.rc5 |  0
v2.1.2.0-1 |  0
v2.1.3.0-0.1.rc1 |  0
v2.1.3.0-0.2.rc2 |  0
v2.1.3.0-0.3.rc3 |  0
v2.1.3.0-1 |  0
v2.1.3.0-1 |  0
v2.1.4.0-0.1.rc1 |  0
v2.1.4.0-0.2.rc2 |  0
v2.1.4.0-0.3.rc3 |  0
v2.1.4.0-1 |  0
v2.1.5.0-0.1.rc1 |  0
v2.1.5.0-0.2.rc2 |  0
v2.1.5.0-1 |  0
v2.1.6.0-0.1.rc1 |  0
v2.1.6.0-1 |  0
v2.2.0.0-0.1.rc1 |  0
v2.2.0.0-0.2.rc2 |  0
v2.2.0.0-0.3.rc3 |  0
v2.2.0.0-0.4.rc4 |  0
v2.2.0.0-1 |  0
v2.2.1.0-0.1.rc1 |  0
v2.2.1.0-0.2.rc2 |  0
v2.2.1.0-0.3.rc3 |  0
v2.2.1.0-0.4.rc4 |  0
v2.2.1.0-0.5.rc5 |  0
v2.2.1.0-1 |  0
v2.2.2.0-0.1.rc1 |  0
v2.2.2.0-0.2.rc2 |  0
v2.2.2.0-1 |  0
v2.2.3.0-0.1.rc1 |  0
v2.2.3.0-1 |  0
v2.3.0.0-0.1.rc1 |  0
v2.3.0.0-0.2.rc2 |  0
v2.3.0.0-0.3.rc3 |  0
v2.3.0.0-0.4.rc4 |  0
v2.3.0.0-0.5.rc5 |  0
v2.3.0.0-0.6.rc6 |  0
v2.3.0.0-1 |  0
v2.3.1.0-0.1.rc1 |  0
v2.3.1.0-0.2.rc2 |  0
v2.3.1.0-1 |  0
v2.3.2.0-0.1.rc1 |  0
v2.3.2.0-0.2.rc2 |  0
v2.3.2.0-0.3.rc3 |  0
v2.3.2.0-0.4.rc4 |  0
v2.3.2.0-0.5.rc5 |  0
v2.3.2.0-1 |  0
v2.3.3.0-0.1.rc1 |  0
v2.3.3.0-0.2.rc2 |  0
v2.3.3.0-0.3.rc3 |  0
v2.3.3.0-1 |  0
v2.3.4.0-0.1.rc1 |  0
v2.4.0.0-0.1.rc1 |  0
v2.4.0.0-0.2.rc2 |  0
v2.4.0.0-0.3.rc3 |  0
v2.4.0.0-0.4.rc4 |  0
v2.4.0.0-0.5.rc5 |  0
v2.4.0.0-1 |  0
v2.4.1.0-0.3.rc1 |  0
v2.4.1.0-0.4.rc2 |  0
v2.4.1.0-1 |  0
v2.4.2.0-0.5.rc1 |  0
v2.4.2.0-1 |  0
v2.4.3.0-0.4.rc1 |  0
v2.4.3.0-0.5.rc2 |  0
v2.4.3.0-0.6.rc3 |  0
v2.4.3.0-1 |  0
v2.4.4-0.2.rc1 |  0
v2.5.0b1 |  0
v2.5.0b2 |  0
v2.5.0rc1 |  0
v2.5.0rc2 |  0
