### ISSUE TITLE
yum module doesn't install group if 'state=latest' but does if 'state=present'

### ISSUE THREAD

**Issue by hartzell** [ansible/ansible#16549]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No changes.
##### OS / ENVIRONMENT

Running ansible built via homebrew on a Mac running 10.10.5.
Targets are Digital Ocean Droplets (for these tests) running Digital Ocean's CentOS 7 image.
##### SUMMARY

Using state=latest with the yum module to install groups (e.g. the Development Group) does not actually install anything, but using state=present does.

This playbook will install the Development Group

```
- hosts: all
  tasks:
  - name: "install development group"
    yum: name="{{ item }}" state=present
    with_items:
      - '@development'
```

This one does not:

```
- hosts: all
  tasks:
  - name: "install development group"
    yum: name="{{ item }}" state=latest
    with_items:
      - '@development'
```
##### STEPS TO REPRODUCE

Create a "droplet" with Digital Ocean's CentOS 7 x64 image (a 512mb droplet is fine).

Use 

```
ansible-playbook -i <droplet_ip_addr>, -u root --private-key=<path to private key> playbook.yml
```

to run either of the playbooks included above.

Log into the machine, e.g. with

```
ssh -i <path to private key> root@<droplet ip addr>
```

and execute `cc` and you should see this (when state=latest):

```
[root@yumbug ~]# cc
-bash: cc: command not found
```

or this (when state=present):

```
[root@yumbug ~]# cc
cc: fatal error: no input files
compilation terminated.
```
##### EXPECTED RESULTS

See above.
##### ACTUAL RESULTS

See above.
