### ISSUE TITLE
include_vars does not consider ignore_errors

### ISSUE THREAD

**Issue by fuhbar** [ansible/ansible#16581]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
include_vars

##### ANSIBLE VERSION
```
Tested with 2.0 2.1 and 2.2 as below
ansible-playbook 2.2.0 (devel 9e93f1c907) last updated 2016/07/04 130857 (GMT +200)
lib/ansible/modules/core (detached HEAD 1d0d5db97a) last updated 2016/07/04 131029 (GMT +200)
lib/ansible/modules/extras (detached HEAD 00b8b96906) last updated 2016/07/04 131034 (GMT +200)
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using `include_vars` combined with `with_items`  and `ignore_errors` the variables are not being loaded. 
Imagine where you want to load variables from a list of files and some of them are missing. This is known and therefore we let the task know, that errors can be ignored. 
I would assume - without knowing the implementation details of `include_vars` - that the files which could be found, will be properly loaded. But this does not seem to be the case.

##### STEPS TO REPRODUCE
Inventory:
``` ini
localhost ansible_connection=local
```
Writing the following Playbook: `test.yml`
``` yaml
- hosts: all
  become: false
  connection: local
  tasks: 
    - include_vars: "{{ item }}" 
      ignore_errors: True
      with_items:
        - "file1.yml"
        - "file2.yml"
    - debug: var=foobar
```
Only one var file exists: `file1.yml`
``` yaml
foobar: "Hello World"
```
Running the playbook with: `ansible-playbook -i inventory test.yml`

##### EXPECTED RESULTS
```
PLAY [all] *********************************************************************
TASK [setup] *******************************************************************
ok: [localhost]
TASK [include_vars] ************************************************************
ok: [localhost] => (item=file1.yml)
failed: [localhost] (item=file2.yml) => {"failed": true, "item": "file2.yml", "message": "Unable to find 'file2.yml' in expected paths."}
...ignoring
TASK [debug] *******************************************************************
ok: [localhost] => {
    "foobar": "Hello World"
}
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
Unfortunately no variable set: 
```
PLAYBOOK: test.yml *************************************************************
1 plays in test.yml
PLAY [all] *********************************************************************
TASK [setup] *******************************************************************
ok: [localhost]
TASK [include_vars] ************************************************************
task path: /tmp/test/test.yml:7
ok: [localhost] => (item=file1.yml) => {"ansible_facts": {"foobar": "Hello World"}, "item": "file1.yml"}
failed: [localhost] (item=file2.yml) => {"failed": true, "item": "file2.yml", "message": "Unable to find 'file2.yml' in expected paths."}
...ignoring
TASK [debug] *******************************************************************
task path: /tmp/test/test.yml:12
ok: [localhost] => {
    "foobar": "VARIABLE IS NOT DEFINED!"
}
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

ignore_errors only applies to task execution, not vars, not connection nor bad playbook definition, ONLY task execution returning a 'failed'.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by bcoca** [comment]
`ignore_errors` will stop the play from being failed for that host, but that does not guarantee that the task will actually not fail to accomplish it's effect.

**Comment by fuhbar** [comment]
@bcoca sure, thats exactly how I understood `ignore_errors`. And as you can see in the example run above, the iteration with the successful include task run, returned the proper results. But these results does not get propagated through out the play. The subsequent task does not see the included variables.

**Comment by jjshoe** [comment]
Same thing happens for just includes as well in 2.1.0.0

**Comment by jimi-c** [comment]
@jjshoe that's because generally include errors are syntax errors, which is kind of fatal error regardless.

**Comment by jjshoe** [comment]
@jimi-c I've worked around it, but I was hoping to do something like:

```
- name: determine which distro we're trying to support
  set_fact:
    distro: "{{ ((ansible_lsb is defined) and ansible_lsb.id is defined) | ternary('{{ ansible_lsb.id }}', ansible_distribution) }}"

- name: determine which version of the distro we're trying to support
  set_fact:
    distro_version: "{{ ((ansible_lsb is defined) and ansible_lsb.id is defined) | ternary('{{ ansible_lsb.release }}', ansible_distribution_major_version) }}"

- name: determine full path to tasks
  set_fact:
    task_path: "{{ role_path }}/tasks/{{ distro }}/{{ distro_version }}.yml"

- name: include distribution specific tasks
  include: "{{ task_path }}"
  ignore_errors: True
  register: include_failed

- name: fail when no include worked
  fail:
    msg: "We don't support your distro"
  when: include_failed.....
```

I've worked around this, but I don't see why ignore_errors should be "special" for include.
