### ISSUE TITLE
mount module not correctly working in ansible 2.0.0.2

### ISSUE THREAD

**Issue by domcar** [ansible/ansible#16594]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### OS / ENVIRONMENT

---

Control Machine: Ubuntu 16.04
 Target Machine: Ubuntu 16.04
## 
##### SUMMARY

In the mount module I have to quote the options dump and passno otherwise i get an error:
"msg": "MODULE FAILURE", "parsed": false
##### STEPS TO REPRODUCE

With the example playbook below i get no error with Ansible 1.9 while with Ansible 2.0.0.2 i get "msg": "MODULE FAILURE", "parsed": false unless i quote those variables

```
- name: /srv | Mount LVM logical volume
  mount:
    name: /srv
    src: /dev/{{ disk_srv_lvm_vg_name }}/{{ disk_srv_lvm_lv_name }}
    opts: defaults,nodev,noatime
    dump: "0" # HERE I HAVE TO QUOTE
    passno: "2" # HERE I HAVE TO QUOTE
    fstype: "{{ disk_srv_fstype }}"
    state: mounted
  when: not disk_srv_skip_setup
```

##### EXPECTED RESULTS

TASK [role : /srv | Mount LVM logical volume] *************************
ok: [x.x.x.x]
##### ACTUAL RESULTS

```
"msg": "MODULE FAILURE", "parsed"
```
