### ISSUE TITLE
Ansible 2.1.0.0 fails with docker directives.

### ISSUE THREAD

**Issue by onnimonni** [ansible/ansible#16595]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version                                              
ansible 2.1.0.0
  config file = /Users/onnimonni/Projects/CLIENT/infra/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
retry_files_enabled = False
forks = 10
host_key_checking = False

[privilege_escalation]
become=True
```
##### OS / ENVIRONMENT

```
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.5
BuildVersion:   15F34
```

This is MacbookPro 2014.
##### SUMMARY

After updating from `2.0.2.0` ->  `2.1.0.0` `docker` directives stopped working.

I'll use it like this:

``` yaml
docker:
    name: "{{item.name}}_wp_prod"
    image: devgeniem/alpine-wordpress
    state: reloaded
    pull: always
    restart_policy: always

    dns:
      - "{{ ansible_docker0.ipv4.address }}"
    volumes:
      - "/sdata/sites/{{item.name}}/uploads:/data/uploads"
      - "/data/sites/{{item.name}}/code/releases/current/:/data/code/"
      - "/data/sites/{{item.name}}/logs/:/data/log/"
      - "/data/sites/{{item.name}}/db/:/data/db/"
    ports:
      - "{{item.port}}:80"
    env: "{{wp_shared.env|combine(item.env)}}"
  with_items: "{{ wp_sites }}"
```

I have array of all the wordpress sites I'm running with docker:

``` yaml
# These ENV will be installed to all sites
wp_shared:
  env:
    DB_HOST: db.service.consul
    DB_PORT: 3306
    # Use host machine for SMTP
    SMTP_HOST: 172.17.42.1
    SMTP_PORT: 25
    # Send emails from this address
    SMTP_FROM: client.fi

# Array of wordpress sites
wp_sites:
  - name: sitename
    # This is the port which will be binded to all application containers for this site
    port: 10000

    # list of must have env variables for the container
    env:
      WP_ENV: production
      DB_USER: wordpress
      DB_NAME: wordpress
      DB_PASSWORD: wordpress
  - name: secondsite
    # This is the port which will be binded to all application containers for this site
    port: 10001

    # list of must have env variables for the container
    env:
      WP_ENV: production
      DB_USER: wordpress2
      DB_NAME: wordpress2
      DB_PASSWORD: wordpress2
...
```
##### EXPECTED RESULTS

I expected this to setup the docker containers that I have.
##### ACTUAL RESULTS

Ansible removes the docker containers but doesn't create them even when I have `reload` option enabled. The playbook fails with this output:

```
"msg": "Docker API Error: json: cannot unmarshal string into Go value of type []string"
```
