### ISSUE TITLE
Adding apt ppa repository creates file in /etc/sources.d with wrong mode

### ISSUE THREAD

**Issue by frca1958** [ansible/ansible#16626]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

from v1.8, changed pipelining = True
##### OS / ENVIRONMENT

Ubuntu 14.04 kernel 4.4.
##### SUMMARY

Adding apt ppa repository creates file in /etc/sources.d with wrong mode
##### STEPS TO REPRODUCE

It always happens whether setting mode explicitly or allowing the default.

```
- name: add ARM Repo
  apt_repository:
    repo: 'ppa:team-gcc-arm-embedded/ppa'
    mode: 0644
  tags: arm

```
##### EXPECTED RESULTS

There are 3 bugs:
- It is not possible to correct the mode using explicit setting (as shown in example below)
- In my opinion, the default mode should be 644 not 420.
- Also the [documentation](http://docs.ansible.com/ansible/apt_repository_module.html) - default mode 420 - should be corrected
##### ACTUAL RESULTS

Result by inspecting on target:

```
root@V1:/etc/apt/sources.list.d# ls -al ppa_team*
-r---w---- 1 root root 74 Jul  7 16:48 ppa_team_gcc_arm_embedded_ppa_trusty.list

```
