### ISSUE TITLE
Feature request: until for blocks

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#16621]
##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

ansible core

##### SUMMARY

I'm missing the `until` operator for blocks. But can we just have everything available for tasks in blocks?

``` yml
      - block:
          - pause: prompt="Choose archive to restore {% for f in archive_list %}{{ "\n" }}{{ f }}[{{ loop.index - 1 }}]{% endfor %}"
            register: file_index

          - pause: prompt="You have selected {{ archive_list[file_index.user_input] }} [{{ file_index.user_input }}], is this correct? [y/n]"
            register: confirm
            until: confirm.user_input in ["y","n"]

        until: confirm.user_input == "y"
```

**Comment by uriinf** [comment]
+1

**Comment by ansibot** [comment]
@hryamzik Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by krzysztof-magosa** [comment]
This would be extremely useful. +1

**Comment by nerdvegas** [comment]
+1. Until doesn't work with include either, so we're left with no way to repeatedly attempt a list of tasks in ansible - only a single task, which feels like an odd limitation to me.

**Comment by Torrent007** [comment]
+1 !

**Comment by piroux** [comment]
@bcoca @abadger
Does someone have a plan for this **heavily** missing feature?

Has someone started to implement it?

- If yes, what are the hardest tidbits preventing from finishing it?
- If no, what are the blocking points preventing from implementing it?

**Comment by svpudik** [comment]
I am missing this feature also, it will be extremely useful. 
Exist any workaround how to create until loop above more tasks? 
I have f.e. rest API get which respond multi array JSON from which need compare 2 variables for each item in array and sum how many items meet my condition, when it is more than 0 I need wait 1 minute and repeat that API get.
I am not able create it in one step in that rest API get, and this will be really helpful.

**Comment by xulib** [comment]
+1

**Comment by GoneWacko** [comment]
I thought I could use a `block` with `until` to solve the problem of reporting progress for a long-running task. For instance, I have a playbook that uses the AWS CLI to start a Database Migration Service replication task with `aws dms start-replication-task <...>`. I wanted to then poll the progress of the task through another CLI command (`aws dms describe-replication-task <...>`), which spits out some JSON including a progress percentage.

I was hoping to do something like this (simplified the playbook to get my point across):
```yaml
- name: Start the task
  command: cli start-long-running-task

- block:
    - name: Poll task status
      command: cli get-task-status
      register: progress

    - name: Report progress
      debug:
        msg: "Progress is {{ (progress.stdout | from_json).CompletionPercentage}}%"
  until: (progress.stdout | from_json).CompletionPercentage == 100
  retries: 30
  delay: 10
```

Admittedly not a perfect solution (far from it) and it's probably debatable whether you should even want to do any of this, but it's a shame that it's not possible to begin with.
