### ISSUE TITLE
Allow conditions per module/role options

### ISSUE THREAD

**Issue by ThomasSteinbach** [ansible/ansible#16627]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
modules and roles

##### ANSIBLE VERSION
2.2

##### SUMMARY
It should be possible to set options for a module or for calling a role just under specified conditions. Sometimes you have a role consuming a lot of options. But for two cases just one option differs. Currently you have to repeat the whole dependency or role call just differing in one option.

##### STEPS TO REPRODUCE
Here an example: Assume you have an Ansible role starting a httpd Docker container which has a lot of settings. You want to distinguish between two options to set the ssl certificates.
Once by mounting them as volumes:
```
- role: docker_httpd_role
  container_name: apache_service1
  ... (many other options)
  ssl_volumes:
    - "{{ ssl.cacertificate }}:/etc/ssl/ca.pem"
    - "{{ ssl.certificate }}:/etc/ssl/site.pem"
    - "{{ ssl.certificatekey }}:/etc/ssl/site.key"
  when: "{{ ssl_container is not defined }}"
```
Or by gathering certificates from a data volume container:
```
- role: docker_httpd_role
  container_name: apache_service1
  ... (many other options)
  ssl_volumes_from: ssl_container
  when: "{{ ssl_container is defined }}"
```
It would be much nicer if you could write just one task and avoid to repeat the _many other options_ per task. Here an example:
```
- role: docker_httpd_role
  container_name: apache_service1
  ... (many other options)
  ssl_volumes:
    - "{{ ssl.cacertificate }}:/etc/ssl/ca.pem"
    - "{{ ssl.certificate }}:/etc/ssl/site.pem"
    - "{{ ssl.certificatekey }}:/etc/ssl/site.key"
    when: "{{ ssl_container is not defined }}"
  ssl_volumes_from: ssl_container
    when: "{{ ssl_container is defined }}"
```
