### ISSUE TITLE
Using `serial: 1` causes a run to fail when one action for one system fails

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#1663]
Consider the following playbook:

```
- name: Bug to show play fails if one action fails
  hosts: all
  serial: 1
  gather_facts: no

  tasks:
  - action: shell exit $(( $(date +%s) % 2))

- name: Another subsequent play
  hosts: all
  gather_facts: no

  tasks:
  - action: debug msg 'Second action will not run when on of the above fails.'
```

If one of the actions fail (which is likely in this case, because it fails half of the time based on the timestamp), the whole run is being aborted because according to Ansible _all hosts have already failed_:

```
[root@moria ansible]# ansible-playbook -v -l localhost,moria test21.yml 
PLAY [Bug to show play fails if one action fails] ********************* 

TASK: [shell exit $(( $(date +%s) % 2))] ********************* 
changed: [moria] => {"changed": true, "cmd": "exit $(( $(date +%s) % 2)) ", "delta": "0:00:00.005326", "end": "2012-11-23 15:47:56.255086", "rc": 0, "start": "2012-11-23 15:47:56.249760", "stderr": "", "stdout": ""}

TASK: [shell exit $(( $(date +%s) % 2))] ********************* 
failed: [localhost] => {"changed": true, "cmd": "exit $(( $(date +%s) % 2)) ", "delta": "0:00:00.007965", "end": "2012-11-23 15:47:57.079065", "rc": 1, "start": "2012-11-23 15:47:57.071100"}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************* 
localhost                      : ok=0    changed=0    unreachable=0    failed=1    
moria                          : ok=1    changed=1    unreachable=0    failed=0   
```

**Comment by mpdehaan** [comment]
This feels like desired behavior since the rolling update would cause more failures later and you do not want to break every app server, etc.

Not a bug.

-- Michael

**Comment by mpdehaan** [comment]
Message could be better in this case I think though.

-- Michael

**Comment by dagwieers** [comment]
Ok, I am using `serial: 1` because we have to call a script (delegated to another server) that is not written so it can be parallelized. The script takes care of provisioning LDAP and generating keys that we later pick up. Since we cannot run it more than once, however it can fail if some requirement is not met, I was expecting it to only fail the remaining steps for that host, but continue with the rest.

Is there another way to make sure that actions in a play are not run in parallel, but doesn't stop the progress if one fails ?

**Comment by mpdehaan** [comment]
no, there is not.

-- Michael

**Comment by dagwieers** [comment]
Ok, so the work-around I have devised in this case, is to ignore the exact error. And in the next play (which is not serialized) verify the return code and fail if needed. In this example it would look like:

```
- name: Bug to show play fails if one action fails
  hosts: all
  serial: 1
  gather_facts: no

  tasks:
  # Added register and ignore_errors to verify at some point later
  - action: shell exit $(( $(date +%s) % 2))
    register: exit
    ignore_errors: yes

# Added another play to evaluate run
- name: Evaluate the previous run (unserialized)
  hosts: all
  gather-facts: no

  tasks:
  - action: fail msg="Previous action failed with ${exit.rc}"
    only_if: "${exit.rc} != 0"

- name: Another subsequent play
  hosts: all
  gather_facts: no

  tasks:
  - action: debug msg 'Second action will not run when on of the above fails.'
```
