### ISSUE TITLE
synchronize module does not handle become user if delegated

### ISSUE THREAD

**Issue by jkrech17** [ansible/ansible#16643]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/custom_modules']
```
##### CONFIGURATION

```
pipelining = True
```
##### OS / ENVIRONMENT

CentOS Linux release 7.0.1406 (Core) 
##### SUMMARY

When using the synchronize module with become and delegate_to, user that initiated playbook (root) is used when trying to ssh to target host rather than the specified become_user.
##### STEPS TO REPRODUCE
1. Create ansible task as shown below
2. Run playbook

```
--- 
- hosts: hosta:hostb 
  gather_facts: no

  tasks:
    - name: Copy folder from one server to another
      synchronize:
        mode: push
        src: "/tmp/foo/"
        dest: "/tmp/foo"
      delegate_to: "hosta"
      become: yes
      become_user: app_user
      become_method: su
```
##### EXPECTED RESULTS

/tmp/foo is synchronized from hosta to hostb as user app_user
##### ACTUAL RESULTS

As shown below, tries to authenticate on target system as root user rather than app_user

```
Too many authentication failures for root\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(600) [sender=3.0.6]\n", "rc": 255}
```

I tested in 2.0.0.2 and worked ok, in 2.0.2.0 it didn't work, and does not work in latest 2.1.

As a workaround, can add following option to synchronize module

```
rsync_opts: --rsh "ssh -l app_user -i /app/home/app_user/.ssh/id_rs
```

This forces the delegated machine to use the key/user already established when performing the rsync.
