### ISSUE TITLE
sudo_user in task should accept variables.

### ISSUE THREAD

**Issue by skorokithakis** [ansible/ansible#1665]
This isn't working for me on the latest HEAD:

> <staging> EXEC sudo -k && sudo -p "[sudo via ansible, key=x] password: " -u ${project_name} /bin/sh

```

---
- hosts: servers
  vars:
    - project_name: stavros
  gather_facts: false
  sudo: true

  tasks:
  - name: Create the SSH directory.
    file: state=directory path=${project_root}/home/.ssh/
    sudo_user: ${project_name}
```

**Comment by mpdehaan** [comment]
Explain what "it" is

-- Michael

**Comment by mpdehaan** [comment]
Nm, I see your subject.  It is always good to mention both expected and actual behavior though...

-- Michael

**Comment by skorokithakis** [comment]
Nothing, it was a mispaste. I've edited it out.

**Comment by mpdehaan** [comment]
ok, I've also edited your description to indicate it's a problem with the sudo_user in the task.

**Comment by willthames** [comment]
Run into this wanting to use sudo_user with with_items - same problem. 

I'll see if I can make any progress on resolving this.

**Comment by mpdehaan** [comment]
Hmm, wanting to run the same task from different sudo_users with sudo_user: $item set on a task?

Yeah, it's not really intended to work that way.   with_item only templates out the action line.

I fear this could be used for too many different crazy things if we are not careful, but if the patch ends up being clean I'll take it :)

**Comment by cyounkins** [comment]
We're running into this as well:

```
---

- name: install autoref application packages
  hosts:
    - dev
  user: root

  vars_files:
    - vars/shared_vars.yml
    - vars/${ENV_NAME}_vars.yml

  sudo: yes
  sudo_user: ${APP_USER}

  tasks:
     - name: create ${APP_USER} user
       user: name=${APP_USER} system=yes state=present
```

`<127.0.0.1> EXEC /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=notsureifthiskeyissecret] password: " -u ${APP_USER} /bin/sh -c '"'"' /usr/bin/python /tmp/ansible-1362095408.15-165816866783206/setup; rm -rf /tmp/ansible-1362095408.15-165816866783206/ >/dev/null 2>&1'"'"''`

APP_USER is defined in vars/${ENV_NAME}_vars.yml . I would expect that variable to be interpolated in sudo_user, but it is not. The first task works just fine, so the variable is defined.

It works as expected when the var is passed in using --extra-vars , as per fix in issue #998 

I wanted to write here to share our config because there seems to be some confusion on the use case.

**Comment by sfllaw** [comment]
At the very least, `sudo_user` should respect variables defined in the inventory.

**Comment by mpdehaan** [comment]
Absolutely.   This part is in queue and is pretty easy to do.   Somewhat of a busy week for obvious reasons :)

**Comment by mpdehaan** [comment]
closing this per previous pull request

**Comment by leucos** [comment]
Unless I'm doing something wrong, it doesn't work here with dict variables. Is that expected ?

**Comment by sfllaw** [comment]
It doesn't appear to work for variables defined outside of the playbook. #2412 only deals with early variable expansion when parsing the playbook. This allows simple `vars`, `vars_prompt`, and `vars_files` to work, but they don't do recursive expansion of inventory variables or `group_vars`.

For instance, we have an inventory file that looks like this:

``` ini
[web]
servername.example.com

[web:vars]
USER = app_data
```

Then, we have a playbook that uses the `${USER}` variable:

``` yaml
- name: "Playbook"
  sudo: yes
  sudo_user: ${USER}

  tasks:
    - ...
```

This fails because it tries to run: `sudo -i -S -p "[sudo via ansible, key=...] password: " -u ${USER} /bin/sh -c ...` when it should be passing `sudo -u app_data`

Of course, running with `--extra-vars` works, but that was handled in #998.
