### ISSUE TITLE
docker_image: 'latest' is pulled when only tag param is specified

### ISSUE THREAD

**Issue by flamingspaz** [ansible/ansible#16662]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

N/A
##### SUMMARY

With `docker_image`, when using just `tag` to specify a specific tag to pull Ansible still tries to pull the 'latest' tag. Adding the tag to the `name` param along with the `tag` param pulls the correctly tagged image.
##### STEPS TO REPRODUCE

```
- name: pull jenkins image
  docker_image:
    name: partinfra/jenkins
    tag: "{{ jenkins_release }}"
```

##### EXPECTED RESULTS

I expected the task to pull the "partinfra/jenkins" image that has been tagged with "{{ jenkins_release }}.
##### ACTUAL RESULTS

The task pulls the `latest` tag and returns ok. I can provide detailed output if needed.

```

```
