### ISSUE TITLE
jijna2 not working for vars_promt prompt

### ISSUE THREAD

**Issue by CaptainQwark** [ansible/ansible#16675]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### OS / ENVIRONMENT

NA
##### SUMMARY

jijna2 code is not processed for the prompt= argument. 
##### STEPS TO REPRODUCE

run this playbook

```
- hosts: all

  vars_prompt:
  - name: CONFIRM
    prompt: prompt="Please confirm; upgrade all packages {{ 'with' if with_reboot is defined else 'without' }} reboot"
    default: "no"
    private: no
```
##### EXPECTED RESULTS

```
PLAYBOOK: test.yml *************************************************************
prompt="Please confirm; upgrade all packages without reboot" [no]:
```
##### ACTUAL RESULTS

```
PLAYBOOK: test.yml *************************************************************
prompt="Please confirm; upgrade all packages {{ 'with' if with_reboot is defined else 'without' }} reboot" [no]: 
```
