### ISSUE TITLE
Ansible is not proxying SSH connection via bastion server if hosts were added to the group dynamically

### ISSUE THREAD

**Issue by jakubigla** [ansible/ansible#16682]
##### ISSUE TYPE

 Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /vagrant/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
```
##### OS / ENVIRONMENT

Ubuntu via Vagrant on OSX
##### SUMMARY

When I add my freshly launched EC2 instances from private subnet to _app_servers_ host group, then my ssh proxying command is not applied to them. However if I hardcode those private IPs in my inventory for _app_servers_ host group, then everything works like a charm. 
##### STEPS TO REPRODUCE

EC2 Role:

```
...

- name: Add new instances to host group
  add_host:
    name: "{{ item.private_ip }}"
    groups: app_servers
    ec2_id: "{{ item.id }}"
  with_items: "{{ ec2_app_az_1 }}"
```

group_vars/app_servers

```
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q {{ remote_user }}@bastion_server"'
ansible_user: "{{ remote_user }}"
```

##### EXPECTED RESULTS

```
10.0.0.217: ok=24   changed=2    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
fatal: [10.0.0.217]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
        to retry, use: --limit @plays/ec2.retry

PLAY RECAP *********************************************************************
10.0.0.217                 : ok=0    changed=0    unreachable=1    failed=0   
```
