### ISSUE TITLE
check for if var is defined bails

### ISSUE THREAD

**Issue by chromerobv** [ansible/ansible#16703]
this has worked in the past 

```
    - name: check var
....
...
      when: extra_volumes is defined
```

it used to only run that when the var was defined now i get this.

fatal: [c1-compute001]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'extra_volumes' is undefined"}

ansible 2.1.0.0

**Comment by nitzmahone** [comment]
Can you give us an actual playbook that causes this for you? The following works fine for me on 2.1.0 (the task is skipped as expected with no error):

```
- hosts: localhost
  gather_facts: no
  tasks:
  - debug: msg=yo
    when: extra_volumes is defined
```

**Comment by tux-00** [comment]
Similar thing here with: ansible 2.2.0 (devel a9d5bf717c) last updated 2016/08/29 10:42:19 (GMT +200)

Directory and file tree:

```
`.
├── group_vars
│   ├── masters.yml
│   └── satellites.yml
├── roles
│   ├── common
│   │   ├── handlers
│   │   │   └── main.yml
│   │   ├── tasks
│   │   │   ├── main.yml
│   │   │   └── new_user.yml
│   │   └── templates
│   │       └── 50unattended-upgrades.j2
├── hosts
└── site.yml
```

main.yml:

```
- name: create new user
  include: new_user.yml user={{ user_name }} userp={{ user_password }} comment="Digital-Liance admin"
  when: user_name is defined and user_password is defined
```

new_user.yml:

```
- name: create user {{ user }}
  user: name={{ user }} password={{ userp }} comment={{ comment }} createhome=yes shell=/bin/bash group=admin

- name: add config files for user {{ user }}
  copy: src={{ item.src }} dest={{ item.dest }}
  with_items:
  - { src: '.bashrc_user',  dest: '/home/{{ user }}/.bashrc' }
  - { src: '.bash_aliases', dest: '/home/{{ user }}/' }
  - { src: '.vimrc',        dest: '/home/{{ user }}/' }
  - { src: '.tmux.conf',    dest: '/home/{{ user }}/' }
```

_user_name_ and _user_password_ are defined in _group_vars/satellites.yml_.

**Result**:

```
TASK [common : add config files for user {{ user }}] ********************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: {{ user_name }}: 'user_name' is undefined.
This feature will be removed in a future release. Deprecation warnings can be disabled
by setting deprecation_warnings=False in ansible.cfg.
skipping: [debian-master]
ok: [debian-satellite] => (item={u'dest': u'/home/digital/.bashrc', u'src': u'.bashrc_user'})
ok: [debian-satellite] => (item={u'dest': u'/home/digital/', u'src': u'.bash_aliases'})
ok: [debian-satellite] => (item={u'dest': u'/home/digital/', u'src': u'.vimrc'})
ok: [debian-satellite] => (item={u'dest': u'/home/digital/', u'src': u'.tmux.conf'})
```
