### ISSUE TITLE
to_nice_yaml output not as expected

### ISSUE THREAD

**Issue by SeerKan** [ansible/ansible#16707]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

{{ variable | to_nice_yaml }} doesn't reproduce indentation and order from variable
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  vars:
    example:
      host: smtp.example
      port: 587
      user: example
      pass: examplepass
      domain:
        something: email.example
        other: aimail.other.com

  tasks:

    - name: Copy configuration file
      template: src=conf.j2 dest=/path/to/config.yml


conf.j2 content:

example:
  {{ example | to_nice_yaml }}
```

##### EXPECTED RESULTS

config file content:

```
example:
  host: smtp.example
  pass: examplepass
  port: 587
  user: example
  domain:
    other: aimail.other.com
    something: email.example
```
##### ACTUAL RESULTS

config file content:

```
example:
  domain:
    other: aimail.other.com
    something: email.example
host: smtp.example
pass: examplepass
port: 587
user: example
```

```

```
