### ISSUE TITLE
Feature request: allow iterating listeners with with_items inside ec2_elb_lb task

### ISSUE THREAD

**Issue by minac** [ansible/ansible#16722]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
ansible-modules-core/cloud/amazon/ec2_elb.py

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
$ egrep -v "^#|^$" /etc/ansible/ansible.cfg
[defaults]
gathering = explicit
host_key_checking = False
callback_whitelist = profile_tasks
remote_user = ec2-user
private_key_file = /Users/myuser/.ssh/mykey.pem
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
display_skipped_hosts = False
command_warnings = True
retry_files_enabled = False
squash_actions = apk,apt,dnf,package,pacman,pkgng,yum,zypper
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]
```

Env vars:

```
export ANSIBLE_HOST_KEY_CHECKING='false'
export AWS_REGION='eu-central-1'
```

and the obvious AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
##### OS / ENVIRONMENT

From Mac OS X Capitan to N/a (AWS)
##### SUMMARY

I need to create an elastic load balancer which listens on a lot of ports (i.e. 100+). I am aware that AWS ELBs do not allow for port ranges in their ELB module (just on security groups), so I would like to do something like this:

```
- name: Create ELB for sender servers
  local_action:
    module: ec2_elb_lb
    name: "{{ elb_sender }}"
    state: present
    zones: "{{ availability_zones }}"
    tags:
      Name: "{{ elb_sender }}"
    listeners:
      - protocol: tcp
        load_balancer_port: "{{ item }}"
        instance_port: "{{ item }}"
        proxy_protocol: True
    cross_az_load_balancing: "yes"
    security_group_names: "{{ security_group_sender }}"
    wait: yes
  with_items:
    - 80
    - 81
```

 Which does not error out but only creates an ELB listening on the last port on the items list.
##### STEPS TO REPRODUCE

The new feature would be as above.

```
    - name: Create ELB for sender servers
      local_action:
        module: ec2_elb_lb
        name: "{{ elb_sender }}"
        state: present
        zones: "{{ availability_zones }}"
        tags:
          Name: "{{ elb_sender }}"
        listeners:
          - protocol: tcp
            load_balancer_port: "{{ item }}"
            instance_port: "{{ item }}"
            proxy_protocol: True
        cross_az_load_balancing: "yes"
        security_group_names: "{{ security_group_sender }}"
        wait: yes
      with_items:
        - 80
        - 81
```
##### EXPECTED RESULTS

I expected/hoped for a loop of the listeners part of the task.
##### ACTUAL RESULTS

An ELB with a listener on port 81.

Thanks for considering it.

**Comment by jctanner** [comment]
Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a submission about a module, and aside from action_plugins, if you know what those are, the modules
in ansible are now moved to separate repos.  We would appreciate if you can submit this there instead.

If this is about a new module, submit pull requests or ideas to:
- https://github.com/ansible/ansible-modules-extras

If this is about an existing module:
- Find the module at http://docs.ansible.com/list_of_all_modules.html
- Open the documentation page for that module
- If the bottom of the docs say "This is an extras module", submit your ticket to https://github.com/ansible/ansible-modules-extras
- Otherwise, submit your module to https://github.com/ansible/ansible-modules-core

Additionally, should you need more help with this, you can ask questions on:
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

Thanks!

**Comment by jctanner** [comment]
re-opening due to repomerge

**Comment by ansibot** [comment]
@minac Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by minac** [comment]
The component name was not part of the template when I opened this ages ago. I have just added the following in my initial issue description:

##### COMPONENT NAME
ansible-modules-core/cloud/amazon/ec2_elb.py

Thank you.

**Comment by ansibot** [comment]
cc @jsdalton
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Hi, thanks for opening this issue! I'm not sure if I understand the feature you're requesting.
Something different than what this accomplishes?:
```
---
- hosts: localhost
  connection: local
  tasks:
    - name: create two servers with two different ports
      ec2_elb_lb:
        name: "{{ item.name }}"
        state: present
        zones: "us-east-1a"
        listeners:
          - protocol: tcp
            load_balancer_port: "{{ item.port | int }}"
            instance_port: "{{ item.port | int }}"
            proxy_protocol: True
        cross_az_load_balancing: "yes"
        security_group_names: "{{ sg }}"
        wait: yes
      with_items:
        - { name: "name1", port: 80 }
        - { name: "name2", port: 25 }
```
Can you share the error you're getting when you run your playbook? Thanks!

**Comment by s-hertel** [comment]
Does using purge_listeners: False give you the desired behavior?
My playbook below creates a load balancer with all three ports.
```
---
- hosts: localhost
  connection: local
  tasks:
    - name: create server three different ports
      ec2_elb_lb:
        profile: "{{ profile }}"
        region: us-east-1
        name: "{{ lb }}"
        state: present
        zones: "us-east-1a"
        tags:
          ansible: test
        listeners:
          - protocol: tcp
            load_balancer_port: "{{ item | int }}"
            instance_port: "{{ item | int }}"
            proxy_protocol: True
        cross_az_load_balancing: "yes"
        purge_listeners: False
        security_group_names: launch-wizard-1
        wait: yes
      with_items:
        - 80
        - 15
        - 25
```

**Comment by s-hertel** [comment]
needs_info
@minac

**Comment by s-hertel** [comment]
Closing this since I believe using purge_listeners: False will fix your problem (as it defaults to true). Please reopen this if I have made a mistake.

**Comment by bcoca** [comment]
FYI, `with_` executes the task once per item, this is why the 'last one wins' unless you do as @s-hertel suggests and avoid purging existing listeners.

Your other option is to just enumerate the listeners in the task.
```
- name: Create ELB for sender servers
  local_action:
    module: ec2_elb_lb
    name: "{{ elb_sender }}"
    state: present
    zones: "{{ availability_zones }}"
    tags:
      Name: "{{ elb_sender }}"
    listeners:
      - protocol: tcp
        load_balancer_port: "80"
        instance_port: "80"
        proxy_protocol: True
      - protocol: tcp
        load_balancer_port: "81"
        instance_port: "81"
        proxy_protocol: True
    cross_az_load_balancing: "yes"
    security_group_names: "{{ security_group_sender }}"
    wait: yes
```
