### ISSUE TITLE
ec2 module does not create root volume as documented

### ISSUE THREAD

**Issue by AgDude** [ansible/ansible#16746]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

ubuntu 14.04
##### SUMMARY

Launching an EBS backed ec2 instance with a non-default root volume does not work as shown in the documentation example. Instead it launches an instance with a standard 8GB root volume, and an additional volume per the definition.

The following is the task which was used to launch the instance (some keys removed for brevity):

```
    - name: Launch ec2 instance
      ec2:
        instance_type: "t2.small"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 15
      register: ec2
```

This is the example from http://docs.ansible.com/ansible/ec2_module.html, which shows a non-standard root volume:

```
# Single instance with ssd gp2 root volume
- ec2:
    key_name: mykey
    group: webserver
    instance_type: c3.medium
    image: ami-123456
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: yes
    exact_count: 1
```
