### ISSUE TITLE
Recursion almost broken

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#16749]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

Mac OS
##### SUMMARY

Recursion includes gets slower and slower till become useless.
##### STEPS TO REPRODUCE

``` yml
- hosts: localhost
  become: no
  become_method: sudo
  vars:
      i: 0
  tasks:
      - include: include_me.yml

      - debug: msg="Exited, i={{ i }}"
```

include_me.yml:

``` yml
- debug: var=i

- set_fact:
    i: "{{ (i|int) + 1 }}"

- include: include_me.yml
  when: "{{ i|int < 30 }}"
```

Playbook run took 0 days, 1 hours, 38 minutes, 3637 seconds

This simple sequence takes forever to execute on my retina MBP. In my real life scenario hundreds of iterations are used to download a full backup with all the incrementals so this issue breaks the whole idea of searching for previous backup with ansible.
