### ISSUE TITLE
ERROR! this task '...' has extra params, which is only allowed in the following modules...

### ISSUE THREAD

**Issue by ARogovsky** [ansible/ansible#16755]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

Use task from https://github.com/mrlesmithjr/ansible-pacemaker/blob/master/tasks/debian.yml which have this lines:

```
- name: debian | configuring pacemaker cluster properties
  pacemaker: >
    property "{{ item.property }}"="{{ item.value }}"
  with_items: pacemaker_cluster_settings
  notify:
    - pacemaker commit
  when: pacemaker_cluster_settings is defined
```

And produce this error:

```
TASK [ansible-pacemaker : include] *********************************************
fatal: [esupport-VirtualBox]: FAILED! => {"failed": true, "reason": "ERROR! this task 'pacemaker' has extra params, which is only allowed in the following modules: command, shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta\n\nThe error appears to have been in '/root/ansible-pacemaker/tasks/debian.yml': line 93, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: debian | configuring pacemaker cluster properties\n  ^ here\n"}

```

Explained here: https://github.com/mrlesmithjr/ansible-pacemaker/issues/1
