### ISSUE TITLE
unarchive can't handle zip files with files containing [] in the archive

### ISSUE THREAD

**Issue by jberkenbilt** [ansible/ansible#16752]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

nothing special
##### OS / ENVIRONMENT

Ubuntu 16.04 LTS
##### SUMMARY

It seems that the unarchive method is not adequately quoting arguments to the unzip command and is letting the shell expand wildcards. This implementation also seems like it would be prone to problems with zip files containing too many files or zip files with long path names/
##### STEPS TO REPRODUCE

Create file "local":

```
[local]
127.0.0.1       ansible_connection=local
```

Create file a.yml:

```

---
- hosts: local
  tasks:
  - name: create a file with a goofy name
    copy: dest="./a[]" content=''
  - name: make a zip file
    command: "zip a.zip a[]"
    args:
     creates: a.zip
  - name: make directory
    file: path=z state=directory
  - name: extract
    unarchive: src=a.zip dest=z copy=no
```

Run `ansible-playbook -i local a.yml`
##### EXPECTED RESULTS

The file `a[]` should have been created inside the `z` directory
##### ACTUAL RESULTS

```
TASK [extract] *****************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "dest": "z", "extract_results": {"cmd": "/usr/bin/unzip -o \"a.zip\" \"a[]\" -d \"z\"", "err": "caution: filename not matched:  a[]\n", "out": "Archive:  a.zip\n", "rc": 11}, "failed": true, "gid": 417, "group": "ejb", "handler": "ZipArchive", "mode": "0755", "msg": "failed to unpack a.zip to z", "owner": "ejb", "size": 4096, "src": "a.zip", "state": "directory", "uid": 417}
```

You can see that it tried to actually list all the files to extract from the zip and did so without quoting or anything. This opens up all sorts of problems. I wouldn't be surprised if you couldn't cause a security issue here by putting a file with a name like ``modify /etc/shadow`` but I haven't tried it.
