### ISSUE TITLE
ansible_host is undefined when  used inside a with_items list item

### ISSUE THREAD

**Issue by xenithorb** [ansible/ansible#16776]
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME
ansible_host var

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None 
##### OS / ENVIRONMENT

Fedora 24 / CentOS 7
##### SUMMARY

ansible_host is undefined when added to `with_items` as a list. I first noticed this when using a lookup password variable in a list. (see actual results) 
##### STEPS TO REPRODUCE

``` yaml
      - name: ansible_host test
        debug: msg={{item}}
        with_items:
          - "{{ansible_host}}"
```
##### EXPECTED RESULTS

`{{ ansible_host }}` should be defined (always, no?)
##### ACTUAL RESULTS

I first noticed this when using the following lookup variable: `sonar_mysql_password: "{{ lookup('password', 'creds/' + ansible_host + '/mysql_sonar_pw chars=ascii_letters,digits,!@#$&*^') }}"` which was later consumed by an included task that called it during a with_items loop. Specifically: 

``` yaml
- name: Configure SonarQube JDBC settings for MySQL.
  lineinfile:
    dest: /usr/local/sonar/conf/sonar.properties
    regexp: "{{ item['regexp'] }}"
    line: "{{ item['line'] }}"
  notify: restart sonar
  with_items:
   - regexp: "^sonar.jdbc.username"
     line: "sonar.jdbc.username={{ sonar_mysql_username }}"
   - regexp: "^sonar.jdbc.password"
     line: "sonar.jdbc.password={{ sonar_mysql_password }}"
   - regexp: "^sonar.jdbc.url"
     line: "sonar.jdbc.url=jdbc:mysql://{{ sonar_mysql_host }}:{{ sonar_mysql_port }}/{{ sonar_mysql_database }}?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&useConfigs=maxPerformance"
```

The task fails with:

```
TASK [geerlingguy.sonar : Configure SonarQube JDBC settings for MySQL.] ********
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: {{ lookup('password', 'creds/'
 + ansible_host + '/mysql_sonar_pw chars=ascii_letters,digits,!@#$&*^') }}: 'ansible_host' is undefined.
This feature will be removed 
in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
fatal: [54.210.117.211]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/xenith/ansible/sonar/roles/geerlingguy.sonar/tasks/configure.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: Configure SonarQube JDBC settings for MySQL.\n  ^ here\n"}
```

I then did a series of trial and errors to boil it down to the "STEPS TO REPRODUCE" which always fails

**Comment by djowett** [comment]
I see similar when trying to use `ansible_host` in `delegate_to` (inside an include file)
Ubuntu trusty
Ansible 2.0.2.0 / 2.1.1.0

This include file

```
---

- name: Show if ansible_host is available
  debug: var=ansible_host

- block:

    - name: PostgreSQL - Add the Odoo user
      postgresql_user: name={{ odoo_config_db_user }}
                       role_attr_flags={{ odoo_postgresql_user_role_attr }}
      when: odoo_postgresql_set_user

    [...]

  # delegate_to: "{{ odoo_config_db_host if odoo_config_db_host not in [False, 'localhost', '127.0.0.1'] else omit }}"
  delegate_to: "{{ odoo_config_db_host if ((odoo_config_db_host|bool) != False) else ansible_host }}"
  remote_user: "{{ odoo_config_db_host_user if ((odoo_config_db_host|bool) != False) else ansible_user }}"
  become: yes
  become_user: postgres
```

Gives output like this:

```
TASK [ansible-odoo : include] **************************************************
included: /home/travis/build/osiell/ansible-odoo/tasks/postgresql.yml for localhost

TASK [ansible-odoo : Show if ansible_host is available] ************************
ok: [localhost] => {
    "ansible_host": "localhost"
}

TASK [ansible-odoo : PostgreSQL - Add the Odoo user] ***************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'ansible_host' is undefined"}
```

(From https://travis-ci.org/osiell/ansible-odoo/jobs/156480571)

**Comment by bcoca** [comment]
Connection variables that get set on task execution are not normally available for the loop (with_), as the loop really creates N tasks, 1 per loop item and then executes each task, this is when those variables become available.

Setting them at 'loop' time would cause problems with actual changes to those vars and/or delegation:

```
- ping:
  delegate_to: "{{item}}"
  with_items:
    - host1
    - host2
```

In this example you WANT the connection vars to reflect host1 and host2 not `inventory_hostname`, which is why we are not setting them during the looping phase.

**Comment by bcoca** [comment]
Leaving this open as to figure out if it is possible to have it both ways and/or update the documentation to clarify 'when' the variables become available as set by the 'connection resolution'.

**Comment by ansibot** [comment]
@xenithorb Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by avico** [comment]
Not sure if it's related to this bug, but I observed similar behaviour with Ansible 2.2.0.0 and such expression:
```
roles:
  - { role: test_role, app_host: "{{ ansible_host if srv_type == 'APP' else '0.0.0.0' }}" }
```

'ansible_host' is undefined

**Comment by RoUS** [comment]
I am seeing this in 2.6.1.  Given the following playbook,

```yaml
--- 
- name: Demonstrate ansible_host bug
  hosts: localhost
  gather_facts: false
  vars:
    itemlist:
    - item1: value1
    - item2: value2
    - who: '{{ ansible_host }}'
  tasks:
    - name: "Do a `with_items`"
      debug:
        var: item
      with_items: '{{ itemlist }}'

    - name: "Do the same inside a block"
      block:
      - name: "Do a `with_items` inside a block"
        debug:
          var: item
        with_items: '{{ itemlist }}'
```
it will fail with

```
PLAY [Demonstrate ansible_host bug] ******************************************************

TASK [Do a with_items] *******************************************************************
fatal: [localhost]: FAILED! => {"msg": "'ansible_host' is undefined"}
```
The issue appears to be related to `ansible_host` appearing anywhere in the `with_*` data.  I've tried abstracting it out several levels, but Jinja2 interpolation appears to be deferred to on-encounter.

If there were a way to force the `who: '{{ ansible_host }}'` interpolation to be done immediately upon parsing, or at least at some point before it gets encountered in the loop, it'd be a big help, and probably easier to work around. 

I've tried defining another variable like `client_fqdn: '{{ ansible_host }}'` at an outer level, and using only `client_fqdn` in the item list, but it still runs into the JIT interpolation.

**Comment by RoUS** [comment]
I *may* have found a workaround, but I've only tested it with a single-host inventory:

```yaml
- name: Demonstrate possible ansible_host bug workaround
  hosts: localhost
  gather_facts: false
  vars:
    itemlist:
    - item1: value1
    - item2: value2
    - who: "{{ 'ansible_host' | map('extract', hostvars) }}"
  tasks:
    - name: "Do a `with_items`"
      debug:
        var: item
      with_items: '{{ itemlist }}'

    - name: "Do the same inside a block"
      block:
      - name: "Do a `with_items` inside a block"
        debug:
          var: item
        with_items: '{{ itemlist }}'
```
