### ISSUE TITLE
Vars are saved across plays

### ISSUE THREAD

**Issue by dhozac** [ansible/ansible#1677]
So, I'm not sure if this is intentional or not, but a variable defined in one play is available in the next, shadowing e.g. inventory variables. So you can't have a play that overrides an inventory variable and in the same playbook run have a play that uses the inventory variable.

Example:

``` yaml

---
- hosts: all
  vars:
    var: play1
  tasks:
  - action: debug msg="$var"

- hosts: all
  tasks:
  - action: debug msg="$var"
```

will both say play1, even if the host has var set to inventory.

Fix is simple, but I'm not sure if we want to disable this behaviour? (Note, only applies to vars: and vars_prompt: vars. vars_files: works as I'd expect.)
