### ISSUE TITLE
Copy throws "file_name <xxx> does not exist, or is not readable", when it does exist

### ISSUE THREAD

**Issue by smugcloud** [ansible/ansible#16780]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
$ cat /etc/ansible/ansible.cfg
[defaults]
host_key_checking = False
```
##### OS / ENVIRONMENT

Running from OSX 10.11.5 --> Ubuntu 14.04.4 LTS, Trusty Tahr
##### SUMMARY

Trying to copy remote files which exist, keeps throwing an error that they are not found
##### STEPS TO REPRODUCE

Ensure these files exist on the remote host:

```
ubuntu@ip-10-178-152-23:/usr/local/etcd-v3.0.1-linux-amd64$ ls -l
total 37724
drwxrwxr-x 11 ubuntu ubuntu     4096 Jul  1 21:33 Documentation
-rwxrwxr-x  1 ubuntu ubuntu 20177984 Jul  1 21:33 etcd
-rwxrwxr-x  1 ubuntu ubuntu 18395072 Jul  1 21:33 etcdctl
-rw-rw-r--  1 ubuntu ubuntu    29370 Jul  1 21:33 README-etcdctl.md
-rw-rw-r--  1 ubuntu ubuntu     5628 Jul  1 21:33 README.md
-rw-rw-r--  1 ubuntu ubuntu     7935 Jul  1 21:33 READMEv2-etcdctl.md
```

playbook 

```
# Install etcd
- hosts: all
  gather_facts: false
  sudo: yes
  roles:
    - pre-ansible
    - etcd
  tags:
    - pre-ansible
    - etcd
```

```
- name: Copy etcd binaries
  copy: src=/usr/local/etcd-v3.0.1-linux-amd64/{{ item }} dest=/usr/bin/{{ item }}
  with_items:
      - etcd
      - etcdctl
```

##### EXPECTED RESULTS

The files would be copied to their respective destinations
##### ACTUAL RESULTS

```
fatal: [10.178.152.23]: FAILED! => {"failed": true, "msg": "the file_name '/usr/local/etcd-v3.0.1-linux-amd64/etcd' does not exist, or is not readable"}
```
