### ISSUE TITLE
Azure module import error

### ISSUE THREAD

**Issue by bnr-deploy** [ansible/ansible#16786]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
(ansible)➜  ansible-dock-robot git:(feature/telemetry) ✗ ansible --version
ansible 2.1.0.0
  config file = /ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

Ubuntu 14.04.04 LTS

Running in VirtualEnv
##### SUMMARY

 Azure blob commands fail to run due to missing module 
##### STEPS TO REPRODUCE

On Host Running Ansible

mkvirtualenv ansible
pip install ansible
pip install azure==2.0.0rc4

```
- azure_rm_storageblob:
    resource_group: MY_GROUP
    storage_account_name: MY_ACCOUNT
    container: MY_CONTAINER
    blob: MY_BLOB
    dest: /tmp/MY_BLOB
```
##### EXPECTED RESULTS

The blob file to be downloaded 
##### ACTUAL RESULTS

Complaint about missing module

```
TASK [telemetry : azure_rm_storageblob] ****************************************
fatal: [host]: FAILED! => {"changed": false, "failed": true, "msg": "The Azure Python SDK is not installed (try 'pip install azure') - No module named msrest.serialization"}

```
