### ISSUE TITLE
docker_image module can't pull image from v2 registry

### ISSUE THREAD

**Issue by Ehekatl** [ansible/ansible#16791]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
  config file = /etc/ansible_jp.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
inventory = jp
host_key_checking = False
retry_files_enabled = False
pipelining = True
log_path=/var/log/ansible.log

[ssh_connection]
sudo_flags=-HE
scp_if_ssh = True
control_path = ~/.ssh/mux-%%r@%%h:%%p
```
##### OS / ENVIRONMENT

AWS EC2 AMI
##### SUMMARY

```
  tasks:
    - name: Pull app image
      docker_image:
        name: "{{ docker_registry }}/{{ env }}/{{ app_name }}:{{ tag }}"
        state: present
```

This task will fail to pull from v2 registry with image not found error, but run docker pull it works.
Log from registry shows that this module using wrong entry point

```
11.0.5.226 - - [22/Jul/2016:02:51:19 +0000] "GET /v1/repositories/v2/test/bobcat/images HTTP/1.1" 404 19 "" "docker/1.11.1 go/go1.5.3 kernel/4.4.14-24.50.amzn1.x86_64 os/linux arch/amd64 UpstreamClient(Docker-Client/1.11.1 \\(linux\\))"
```
##### STEPS TO REPRODUCE

Using docker_image pull from private v2 registry to reproduce error

##### EXPECTED RESULTS

Image pull should work on v2 registry
##### ACTUAL RESULTS

It still using v1 registry endpoint to pull image
