### ISSUE TITLE
Multiple ansible roles from a single Git repo with ansible-galaxy (doc update)

### ISSUE THREAD

**Issue by aneesh-joseph** [ansible/ansible#16804]
##### ISSUE TYPE
Documentation Report

##### COMPONENT NAME
ansible-galaxy documentation

##### ANSIBLE VERSION
```
2.2.0
```

##### CONFIGURATION
N/A

##### SUMMARY
Documentation update for `ansible-galaxy`

##### STEPS TO REPRODUCE
The ansible-galaxy documentation doesn't suggest that galaxy can pull down multiple roles from a single repo - http://docs.ansible.com/ansible/galaxy.html, but it seems to be possible. For example if I have a git repo with the below structure
```
  meta/main.yml
  role1/tasks/main.yml
  role2/tasks/main.yml
  role3/tasks/main.yml
```
I can pull it down using galaxy using the below  requirements.yml file
```
---
# pull down common roles
- src: https://github.com/aneesh/common-roles
  name: common-roles
  version: master
  scm: git
```
```
ansible-galaxy install -r requirements.yml --force -p roles
```
and then I can use the common roles like
```
---
- name: Install common utils from role1
  hosts: ambari-cluster   
  roles:
  - common-roles/role1
- name: some other common tasks
  hosts: ambari-cluster   
  roles:
  - common-roles/role2
```

Can the documentation be updated to reflect this? :smile:
