### ISSUE TITLE
a module to create Keystone endpoints

### ISSUE THREAD

**Issue by jackivanov** [ansible/ansible#16809]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Debian Jessie
##### SUMMARY

I found `os_user` module and a lot of other OS modules, but I can't find almost the most important module to work with Keystone. 
Is there a way to create Keystone endpoints?
##### EXPECTED RESULTS

I would like to use a native Ansible module to create Keystone endpoints. Something like this:

```
- name: Keystone | Create nova endpoints
  os_keystone_endpoints:
    state: present
    cloud: devstack
    name: nova
    type: compute
    public: http://10.90.180.208:8774/v2.1/%(tenant_id)s
    admin: http://10.90.180.208:8774/v2.1/%(tenant_id)s
    internal: http://10.90.180.208:8774/v2.1/%(tenant_id)s
```

Is that possible?
##### ACTUAL RESULTS

Now I'm using `shell` module and `openstack endpoint` commands, but it is not a good way

Thank you.
