### ISSUE TITLE
Ansible hangs on a yum install with_items for unknown reason

### ISSUE THREAD

**Issue by wildefires** [ansible/ansible#16802]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0 (devel 93c5ec42cf) last updated 2016/07/22 14:58:15 (GMT -400)
  lib/ansible/modules/core: (detached HEAD b3c606047d) last updated 2016/07/22 14:58:24 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD d9b4613941) last updated 2016/07/22 14:58:25 (GMT -400)
  config file = /home/R1/mitchell.usher/.ansible.cfg
  configured module search path = ['/usr/share/ansible']

```
##### CONFIGURATION

https://gist.github.com/anonymous/e3b3ae8ad0ea8d9521ba39c5f1aa8843

This is the .ansible.cfg from above
##### OS / ENVIRONMENT

Host: Linux (Centos 7)
Remote: Linux (Centos 7)
##### SUMMARY

When attempting to run the play below the ansible process will inexplicably hang consistently. This is also the first play in an `include`ed playbook (second code snippet) which is the first include of the top-level playbook, but not its first play

```
- name: Prep and configure for installation | Install yum packages
  yum: name={{ item }} state=present
  with_items:
  - gcc
  - glibc
  - glibc-common
  - gd
  - gd-devel
  - make
  - net-snmp
  - openssl-devel
  - unzip
  - tar
  - gzip
  - xinetd
  - libselinux-python
```

Top-level play:

```
  - name: Run the prep
    include: prep.yml
    tags: ['prep']
```

Not certain that it matters - this is being run from python 2.7.5 within a python virtualenv
##### STEPS TO REPRODUCE

Run the above play(s) against a Centos 7 machine?
##### EXPECTED RESULTS

Yum packages to be installed; playbook progression
##### ACTUAL RESULTS

Ansible hangs on the yum. Output here:

https://gist.github.com/anonymous/d3db7ca76b8b1941218a89e21d9c700f

The part that hangs is the "Install ym packages" play
