### ISSUE TITLE
Ansible Tower exposing password used by vsphere_guest

### ISSUE THREAD

**Issue by gischethans** [ansible/ansible#16811]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 14.04.4 LTS running Ansible Tower 2.4.5
##### SUMMARY

Ansible Tower exposing password
##### STEPS TO REPRODUCE

In one of my Ansible Playbooks, I use the vsphere_guest module to create VMs on vCenter Server. When I run the Playbook on Ansible Tower using a job template and check the host events, I see the password in plain text. 

![image](https://cloud.githubusercontent.com/assets/2355473/17092194/7df2fca4-525e-11e6-8b52-932a9fde06e5.png)

Note: I didn't provide the password in plain text in the Playbook. In fact, it is stored in the 'Credentials' section of Ansible Tower where it is shown to be encrypted. The Job template is set to use this credential under 'Cloud Credentials'.
![image](https://cloud.githubusercontent.com/assets/2355473/17092213/a351299e-525e-11e6-8f47-23beb11ca296.png)

```

---
- name: Create VMs on VMware vCenter Server
  hosts: localhost

  vars:
  - vmname: ['VM1', 'VM2']

  tasks:
  - vsphere_guest:
      vcenter_hostname: "<hostname>"
      guest: "{{ item }}"
      from_template: yes
      template_src: "<template>"
      validate_certs: no
      esxi:
        datacenter: dcname
        hostname: hostname
    with_items: "{{ vmname }}"

```

##### EXPECTED RESULTS

The password should not be shown in host events.
##### ACTUAL RESULTS

The password is shown in plain text.

```

```
