### ISSUE TITLE
how to reload vars_plugins in playbook?

### ISSUE THREAD

**Issue by rainslytherin** [ansible/ansible#16812]
##### ISSUE TYPE

- Question
##### ANSIBLE VERSION

```
[root@192-168-153-81 ~]# ansible --version
ansible 1.9.4
  configured module search path = None
```
##### SUMMARY

I write a vars_plugin,  and in my playbook ,the first step is to add somevars which is got from other system to vars_plugins system.

but the vars_plugins are loaded at the beginning of the playbook running. how to reload the vars_plugins in my playbook so the next step can use the vars got from the vars_plugins?

Any one konws? please help me !
##### STEPS TO REPRODUCE

```

---
- hosts: all
  gather_facts: false
  tasks:
    - name: 1-add the host to one group,so it can get variables from the group in my vars_plugins system.
      local_action: shell python /data/uappo_tools/uappo-api/uvar/add_children_group.py {{ group_name }} {{ inventory_hostname }}

    - name: 2-sync code 
      local_action: shell  python /data/uappo_tools/uappo-udeploy2/sync_code.py {{ group_name }}  {{ base.admin_node }}
      run_once: true
     # the base.admin_node variable is generated in step 1. so because the vars_plugins is loaded at the beginning of the playbook ,so it failed in this step. so i want to reload vars_plugin after step 1.
```

##### ACTUAL RESULTS

```

```
