### ISSUE TITLE
junos modules RPC timeout option

### ISSUE THREAD

**Issue by defo89** [ansible/ansible#16853]
##### ISSUE TYPE
- Feature Idea
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

```
Juniper EX2200 switches (12.3R8.7), some are virtual chassis
```
##### SUMMARY

Default 30sec RPC timeout breaks commits on EX virtual chassis.
Need an explicit timeout option like in [junos_install_config](http://junos-ansible-modules.readthedocs.io/en/1.3.0/junos_install_config.html)
##### STEPS TO REPRODUCE

```
playbook.yml 

---
- name: set config
  hosts: juniper_test
  connection: local
  gather_facts: no

  vars_prompt:
   - name: USERNAME
     prompt: Username
     private: no
   - name: DEVICE_PASSWORD
     prompt: Password
     private: yes

  tasks:
  - name: set config
    junos_config:
      host: "{{ inventory_hostname }}"
      username: "{{ USERNAME }}"
      port: 22
      password: "{{ DEVICE_PASSWORD }}"
      lines:
        - set system login class monitoring permissions secret
        - set system login class monitoring permissions view
        - set system login class monitoring permissions view-configuration
```
##### ACTUAL RESULTS

[playbook run](https://gist.github.com/dmitrijsf/3abe1642f297b81750448c2e4d7b93b1)
