### ISSUE TITLE
loop variables passed to include get lost in handlers

### ISSUE THREAD

**Issue by micw** [ansible/ansible#16872]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

nothing special
##### OS / ENVIRONMENT

Debian jessie, Ansible from ubuntu ppa.
##### SUMMARY

If I use include with vars and the include triggers a handler, vars are not passed to the handler
##### STEPS TO REPRODUCE

tasks/main.yml

```
- include: inc.yml
  vars:
    myvar: "{{ item }}"
  with_items:
  - "a"
  - "b"
```

tasks/inc.yml

```
- shell: echo 1
  notify: myhandler
- meta: flush_handlers
```

handlers/main.yml

```
- debug:  msg="myvar: {{ myvar }}"
  notify: myhandler
- meta: flush_handlers
```
##### EXPECTED RESULTS

Debug output "myvar: a" and "myvar:b" from handler
##### ACTUAL RESULTS

Error from handler, that myvar is undefined
##### WORKAROUND

set fact in tasks/inc.yml

```
- set_fact:
    myvar: "{{ myvar }}"
- shell: echo 1
  notify: myhandler
- meta: flush_handlers
```
