### ISSUE TITLE
2.1.1 no longer works against localhost

### ISSUE THREAD

**Issue by LeeBrown** [ansible/ansible#16886]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrrides
##### SUMMARY

2.1.0 works (see here)
2.1.1 does not (see here)
##### STEPS TO REPRODUCE

upgrade from 2.1.0 to 2.1.1

```
- name: Installation, setup ansible user for remote ssh
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Add user
    user: name=ansible comment="Ansible" state=present shell=/bin/sh

  - name: Configure SSH daemon
    lineinfile: dest=/etc/ssh/sshd_config state=present line={{ item }}
    with_items:
      - AuthorizedKeysFile=/etc/ssh/AuthorizedKeys/%u
      - ChallengeResponseAuthentication=no
      - LoginGraceTime=20
      - UseDNS=no

  - name: Install sudo
    pkgng: state=present name=security/sudo

  - name: Configure sudoers
    lineinfile: >
      dest=/usr/local/etc/sudoers.d/ansible  state=present 
      line={{ item }} create=yes group=wheel owner=root mode=u=rw,g=r
    with_items:
      - "ansible ALL=(root) NOPASSWD: ALL"

```

##### EXPECTED RESULTS

For it to work as before (regression)
##### ACTUAL RESULTS

see screen shots for exact message

Instead of 
TASK [setup]**\* 
ok: [127.0.0.1]

it now says
PLAY [Installation, setup ansible user for remote ssh] **\* 
skipping: no hosts matched

```
![image](https://cloud.githubusercontent.com/assets/5847183/17273171/c3ec4a7a-5660-11e6-9289-3c449e8e3ffe.png)
![image](https://cloud.githubusercontent.com/assets/5847183/17273174/d7ff5b60-5660-11e6-9135-06331ad9216c.png)

```
