### ISSUE TITLE
Ansible should fail in the presence of duplicate keys

### ISSUE THREAD

**Issue by larsks** [ansible/ansible#16903]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.1.1.0
config file =
configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
We recently had a change submitted to the triple-quickstart project
that contained the following code:
```
- name: Rebuild inventory
  hosts: localhost
  roles:
    - rebuild-inventory
  tags:
    - provision
# check the target virthost distro for RHEL or CentOS
  hosts: virthost
  roles:
    - provision/support_check
  tags:
    - provision
```
Note that the second task list is missing the YAML list marker; it
should look like this:
```
- hosts: virthost
  roles:
    - provision/support_check
  tags:
    - provision
```
This is a clear error, but it passes through the YAML parser with only
the following warning:
```
[WARNING]: While constructing a mapping from /home/lars/src/tripleo-
quickstart/playbooks/provision.yml, line 21, column 3, found a
duplicate dict key (roles).  Using last defined value only.
```

##### STEPS TO REPRODUCE
(see above playbook samples)

##### EXPECTED RESULTS
Since duplicate keys are in fact not possible, I would expect Ansible
to abort with an error at this point.

##### ACTUAL RESULTS
Ansible ignores the error and continues on its merry way.
Because this warning comes from deep within the parser, it's not even
possible for something like `ansible-lint` to catch the problem,
either.
##### ADDITIONAL COMMENTARY
This is, oddly enough, the exact opposite of #13603.

**Comment by bcoca** [comment]
The reason ansible does not fail is to allow for certain yaml'isms like anchors, which work by having the last copy of a key 'win'. It is almost impossible to distinguish between this being an error or on purpose.

**Comment by larsks** [comment]
@bcoca And yet, this clearly is also able to completely mask fairly substantial errors in a playbook.  What if there were  an _option_ to make this fatal that could be used by tools like `ansible-lint` to perform stricter validation of the code?

**Comment by ansibot** [comment]
@larsks Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by InfoSec812** [comment]
I am seeing a similar issue in relation to an inventory we use:

```
- object: ci-cd-deployments
  content:
  - name: jenkins-ephemeral
    template: openshift//jenkins-ephemeral
    params: "{{ inventory_dir }}/params/deploy/jenkins"
    namespace: labs-ci-cd
    tags:
    - jenkins
  content:
  - name: mvn-depcheck-cache
    template: "{{ inventory_dir }}/templates/cache_pvc.yml"
    params: "{{ inventory_dir }}/params/deploy/cache_pvc"
    namespace: labs-ci-cd
    tags:
    - jenkins
```

The second `content` key resets the dictionary silently (or silently enough) such that my inventory runs without error and fails to deploy correctly.
