### ISSUE TITLE
Conflicting role versions ignored running ansible-galaxy install

### ISSUE THREAD

**Issue by jagibson** [ansible/ansible#16909]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
ansible-galaxy

##### ANSIBLE VERSION
```
ansible 2.0.2.0
config file = /home/user/ansible/test/testplay/ansible.cfg
configured module search path = Default w/o overrides
```

##### CONFIGURATION
ini
[defaults]
roles_path = roles

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If the same role with two different versions is listed twice in requirements.yml or as dependencies the first role detected wins without error.  This may seem trivial, but...
I have many roles.  Sometimes I may be using two different roles that specify the same dependency role.  However since not all roles are coded at the same time, the dependencies in meta/main.yml may be pinned to different versions.  Only the first dependency role matching the name is installed.  This can cause playbooks runs to fail or run unexpectedly if features that are expected in one version of the role have changed in another version.

##### STEPS TO REPRODUCE
Run ansible-galaxy install -r requirements.yml with a config similar to the following:
requirements.yml
``` yaml
---
- src: file:///home/user/ansible/test/testplay/mainrole1
  path: roles
  name: mainrole1
  scm: git
- src: file:///home/user/ansible/test/testplay/mainrole2
  path: roles
  name: mainrole2
  scm: git
```
mainrole1/meta/main.yml
``` yaml
dependencies:
  - src: file:///home/user/ansible/test/testplay/testrole
    name: testrole
    path: roles
    version: 1.0.1
    scm: git
```
mainrole2/meta/main.yml
``` yaml
dependencies:
  - src: file:///home/user/ansible/test/testplay/testrole
    name: testrole
    path: roles
    version: 1.0.2
    scm: git
```
testrole is versioned
``` bash
$ cd testrole
$ git tag
1.0.0
1.0.1
1.0.2
```

##### EXPECTED RESULTS
An error or warning if two different versions exist for the same galaxy name

##### ACTUAL RESULTS
The command outputs "dependency testrole already pending installation" but makes no note of the version conflict.
``` bash
$ ansible-galaxy install -r requirements.yml -vvv
Using /home/user/ansible/test/testplay/ansible.cfg as config file
Opened /home/user/.ansible_galaxy
Validate TLS certificates: True
Connecting to galaxy_server: https://galaxy.ansible.com
Base API: https://galaxy.ansible.com/api/v1
found role {'scm': 'git', 'src': 'file:///home/user/ansible/test/testplay/mainrole1', 'version': '', 'name': 'mainrole1'} in yaml file
found role {'scm': 'git', 'src': 'file:///home/user/ansible/test/testplay/mainrole2', 'version': '', 'name': 'mainrole2'} in yaml file
Installing role mainrole1 
- extracting mainrole1 to roles/mainrole1
- mainrole1 was installed successfully
- adding dependency: testrole
Installing role mainrole2 
- extracting mainrole2 to roles/mainrole2
- mainrole2 was installed successfully
- dependency testrole already pending installation.
Installing role testrole 
- extracting testrole to roles/testrole
- testrole was installed successfully
```
