### ISSUE TITLE
Delegated task uses the wrong user to connect to target machine

### ISSUE THREAD

**Issue by RokLenarcic** [ansible/ansible#16918]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[ssh_connection]
ssh_args = -o ControlMaster=no -o ControlPersist=60s
##### OS / ENVIRONMENT

Control machine: OSX El Capitan latest
Target Machine: VMWare Debian 3.13.0-91-generic
##### SUMMARY

`delegate_to` causes wrong user to be used to connect to target machine
##### STEPS TO REPRODUCE

I have an inventory file as such:

```
build_machine ansible_host=localhost ansible_connection=local
staging_machine ansible_host=my.staging.host ansible_user=stager
```

I have a playbook running synchronize:

```
- name: Copy build to staging
  hosts: staging_machine
  tasks:
    - synchronize: src=somefolder dest=otherfolder
      delegate_to: staging_machine
      remote_user: stager
```
##### EXPECTED RESULTS

I expected the playbook to synchronize folders between build and staging machine.
##### ACTUAL RESULTS

The task prompts for password of the wrong user:

```
local-mac-user@my-staging-host's password:
```

Playbook works with version `2.0.2.0`.

**Comment by tima** [comment]
This appears to be a duplicate #15405

**Comment by winggundamth** [comment]
@tima @jctanner I got this problem with raw command too. This bug just hit me on 2.1.1.0 but not 2.1.0.0. Please reopen this bug

```
- name: Copy build to staging
  hosts: staging_machine
  tasks:
    - raw: "python --version"
      delegate_to: staging_machine
      remote_user: stager
```

```
<172.16.0.78> ESTABLISH SSH CONNECTION FOR USER: myuser
<172.16.0.78> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=myuser -o ConnectTimeout=10 -o ControlPath=/home/myuser/.ansible/cp/ansible-ssh-%h-%p-%r 172.16.0.78 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1470210490.36-126485663018441 `" && echo ansible-tmp-1470210490.36-126485663018441="` echo $HOME/.ansible/tmp/ansible-tmp-1470210490.36-126485663018441 `" ) && sleep 0'"'"''
```
