### ISSUE TITLE
Variables in handler names aren't being interpolated

### ISSUE THREAD

**Issue by kevinburke** [ansible/ansible#16922]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

nocows=1
##### OS / ENVIRONMENT

Mac, deploying onto a Linux machine
##### SUMMARY

I have a "supervised" role that defines two handlers for calling `supervisor reread {{service}}`, `supervisor update {{ service }}`, and `supervisor restart {{ service }}`. In Ansible 1, these handlers would get restarted. In Ansible 2, no handlers are notified.
##### STEPS TO REPRODUCE

I've reduced this to the minimal possible test case. 
###### roles/supervised/handlers/main.yml

``` yml
- name: "supervisor restart {{supervised_name}}"
  supervisorctl: name={{supervised_name}} state=restarted
```
###### roles/supervised/meta/main.yml

``` yml

---
allow_duplicates: yes
```

The redis role depends on supervised:
###### roles/redis/meta/main.yml

``` yml

---
allow_duplicates: yes
dependencies:
  - role: supervised
    supervised_name: "{{svc_name}}"
```

The evdb.master role depends on redis:
###### roles/evdb.master/meta/main.yml

``` yml

---
dependencies:
  - role: redis
    svc_name: "evdb.master"
```

Finally the evdb.master folder has a dummy task to trigger the handler.
###### roles/evdb.master/tasks/main.yml

``` yml
- name: trigger handler
  command: /bin/true
  notify: "supervisor restart evdb.master"
```
##### EXPECTED RESULTS

I expect the restart handler to fire. I observe that the restart handler gets registered:

```
NOTIFIED HANDLER supervisor restart evdb.master
```
##### ACTUAL RESULTS

The handler does not get registered.

If I call supervised directly from evdb.master - skip redis - the handler does fire. Some print statements included from me trying to debug the issue.

```
NOTIFIED HANDLER supervisor restart evdb.master
changed: [db] => {"changed": true, "cmd": ["/bin/true"], "delta": "0:00:00.002106", "end": "2016-08-02 18:49:53.508597", "invocation": {"module_args": {"_raw_params": "/bin/true", "_uses_shell": false, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 0, "start": "2016-08-02 18:49:53.506491", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
doing handler run:
handler
HANDLER: supervised : supervisor restart {{supervised_name}}
handler_name
supervisor restart evdb.master

RUNNING HANDLER [supervised : supervisor restart evdb.master] ************
```
