### ISSUE TITLE
Variable gets lost in reusable file (when including from task)

### ISSUE THREAD

**Issue by zentavr** [ansible/ansible#16925]
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
forks = 10
var_compression_level=9
retries=5
fact_caching = jsonfile
fact_caching_connection = ~/.ansible/tmp
```
##### SUMMARY

Variable gets lost in reusable file (when including from task)
##### STEPS TO REPRODUCE

I have a code of:

```
- include: docker/persist.yml
  vars:
    persistcomponent: admin
  when: ec2_tag_role|default('n/a') in [ 'all', 'admin' ]

- include: docker/persist.yml
  vars:
    persistcomponent: apps
  when: ec2_tag_role|default('n/a') in [ 'all', 'apps' ]
```

with ansible 2.1.1 it fails with:

```
ERROR! 'persistcomponent' is undefined
```

...with ansible 2.1.0 works great.
