### ISSUE TITLE
Ansible fails when using variable as host target

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#16931]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using a variable as a target for a play, ansible fails
##### STEPS TO REPRODUCE

```

---
- name: set the fact
  hosts: localhost
  gather_facts: no
  tasks:
    - name: set the fact
      set_fact:
        my_group: "datacenter_east_1"

- name: happy_path
  hosts: "datacenter_east_1"
  tasks:
    - name: ping
      ping:

- name: sad_path
  hosts: "{{ my_group }}"
  tasks:
    - name: ping
      ping:
```
##### EXPECTED RESULTS

The two last plays should return the same result, since the "my_group" variable contains "datacenter_east_1"
##### ACTUAL RESULTS

```
ERROR! the field 'hosts' has an invalid value, which appears to include a variable that is undefined. The error was: 'my_group' is undefined
```

**Comment by bcoca** [comment]
plays objects don't have access to hostvars, normally only extra vars can be used in `hosts:`

**Comment by trondhindenes** [comment]
okay, so there's no way for me to dynamically inject a variable to be used with `hosts:` from within a playbook?

**Comment by jctanner** [comment]
@trondhindenes no, not currently. This has always been a situation where extra vars is the only way to populate vars inside the host pattern.

**Comment by tuwid** [comment]
any workarounds ?

**Comment by bcoca** [comment]
use `group_by` module to create a group dynamically which you use in the latter play.

**Comment by tuwid** [comment]
@bcoca any examples ?

**Comment by b-long** [comment]
@bcoca @tuwid @jctanner @likwid 

I also need an example of creating a group dynamically which you use in a latter play.

I've been able to do this with a constant group name (e.g. `to_be_provisioned `), seen in this gist:
https://gist.github.com/likwid/bd1c62c6adbbe6853114#file-ec2-instance__tasks__main-yml-L55-L58

However, now I need the name to be configurable.  My goal is something like: 

```yml
- name: "Configure dynamic group"
  hosts: "{{ dynamic_group_name }}"
  roles:
    - { role: geerlingguy.apache }
```
