### ISSUE TITLE
Ansible is generating different JSON from the YML play definition on different control machines

### ISSUE THREAD

**Issue by jschank** [ansible/ansible#16960]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/promking/prom-king/ansible.cfg
  configured module search path = ['./library/**']
```
##### CONFIGURATION

```
[defaults]
# This is now controlled by environment variables defined in the bash_profile.j2 file
# even though we use environment vars - the jenkins build machine does not define the env var we need
# IF both env var and this cfg file set the inventory location - the environment variable WINS so we can
# set it in both env and cfg. Knowing that the jenkins build machine will rely on the cfg, but local development
# can rely on the env var.
inventory=./promotion 
transport=ssh
force_handlers=True
force_color=1
log_path=~/ansible.log
use_ticket_plugin=true
# Ansible knows how to look in multiple locations if you feed it a colon separated path, and it also will look for modules in the ”./library” directory alongside a playbook
library=./library/**
# enable these for debugging
command_warnings=False
deprecation_warnings=False
system_warngings=False
retry_files_enabled=False

[ssh_connection]
scp_if_ssh=True
ssh_args = -o StrictHostKeyChecking=no -o ServerAliveInterval=10
# -o UserKnownHostsFile=/dev/null  -o ForwardAgent=yes PreferredAuthentications=publickey
```
##### OS / ENVIRONMENT

Running from Centos 6.8
Python 2.6.6
##### SUMMARY

The uri module is generating different json for the request body, on different machines. Same playbooks.
##### STEPS TO REPRODUCE

This is in my play:

```
# Create a new remote repo on gitlab
- name: create a new repo on gitlab
  uri:
    url: "http://ddc-git.ddc.prod/api/v3/projects/"
    HEADER_PRIVATE-TOKEN: "{{ gitlab_promking_token }}"
    body_format: json
    body:
      name: "{{ site }}"
      namespace_id: "{{ group_lookup.json.id }}"
      description: "DDC Web Site, brought to you by Prom King."
      issues_enabled: True
      merge_requests_enabled: True
      wiki_enabled: True
      snippets_enabled: True
      public: False
      visibility_level: 10
    method: POST
    return_content: yes
  register: create_site
  changed_when: create_site.status == 201
  failed_when: create_site.status != 201
  tags:
    - deploy
```
##### EXPECTED RESULTS

I used requestb.in to see what the request body looks like. On machines where this works, the body is:

```
{"namespace_id": "7", "snippets_enabled": true, "name": "createtest", "issues_enabled": true, "merge_requests_enabled": true, "wiki_enabled": true, "visibility_level": 10, "public": false, "description": "DDC Web Site, brought to you by Prom King."}
```
##### ACTUAL RESULTS

But my production machine is generating this JSON, which produces an error response that claims the "name" value is not set.

```
Error message (token sanitized)
fatal: [localhost]: FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "keep-alive", "content": "{\"message\":\"400 (Bad request) \\\"name\\\" not given\"}", "content_length": "50", "content_type": "application/json", "date": "Wed, 03 Aug 2016 18:35:41 GMT", "failed": true, "failed_when_result": true, "invocation": {"module_args": {"HEADER_PRIVATE-TOKEN": "xxxxxxxx", "backup": null, "body": "{'namespace_id': '7', 'snippets_enabled': True, 'name': 'eeiwsfe', 'issues_enabled': True, 'merge_requests_enabled': True, 'wiki_enabled': True, 'visibility_level': 10, 'public': False, 'description': 'DDC Web Site, brought to you by Prom King.'}", "body_format": "json", "content": null, "creates": null, "delimiter": null, "dest": null, "directory_mode": null, "follow": false, "follow_redirects": "safe", "force": null, "force_basic_auth": false, "group": null, "method": "POST", "mode": null, "owner": null, "password": null, "regexp": null, "remote_src": null, "removes": null, "return_content": true, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": null, "status_code": [200], "timeout": 30, "url": "http://ddc-git.ddc.prod/api/v3/projects/", "user": null, "validate_certs": true}, "module_name": "uri"}, "json": {"message": "400 (Bad request) \"name\" not given"}, "msg": "Status code was not [200]", "redirected": false, "server": "nginx", "status": 400, "vary": "Origin", "x_request_id": "2cd8705e-7459-4ae1-a368-1e49fc9f5511", "x_runtime": "0.007323"}
```

I think this is because the json that is being sent, is different. The JSON being sent is this:

```
"{'namespace_id': '7', 'snippets_enabled': True, 'name': 'createtest', 'issues_enabled': True, 'merge_requests_enabled': True, 'wiki_enabled': True, 'visibility_level': 10, 'public': False, 'description': 'DDC Web Site, brought to you by Prom King.'}"
```
##### ADVICE REQUESTED

I think the production machine may have different or conflicting dependencies. I would like to ensure that the yml is converted to json in the same way. Can you advise what dependency is responsible for converting the yml to json.
