### ISSUE TITLE
S3 modules destroys file and fails with 'text file busy'

### ISSUE THREAD

**Issue by haisamido** [ansible/ansible#16975]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.1.0:                                                
  config file = <file>..." to include in what will be committed)
  configured module search path = Default w/o overrides         

```
##### CONFIGURATION

```
[defaults]
pipelining=True

[ssh_connection]
ssh_args = -o StrictHostKeyChecking=no

```
##### OS / ENVIRONMENT

`Linux ip-172-31-5-115 4.4.5-15.26.amzn1.x86_64 #1 SMP Wed Mar 16 17:15:34 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
`
##### SUMMARY

S3 modules destroys file and fails with 'text file busy'
##### STEPS TO REPRODUCE

The below task works if executables,  **mnem_extract_server** is not running

```
- name: "Copy mnemonics extractor executable to {{ taas_user }}'s ./bin directory"
  s3: bucket='<MYBUCKET>' object=/mnemonic_service/{{ item }} dest={{ taas_home }}/{{ taas_user }}/bin/{{ item }} mode=get region={{ env_aws_region }} aws_access_key={{ env_aws_access_key }} aws_secret_key={{ env_aws_secret_key }} 
  ignore_errors: yes
  vars:
    env_aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    env_aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
    env_aws_region: "{{ lookup('env', 'AWS_REGION') }}"
  with_items:
    - **mnem_extract_server**
```

but when it's running and in RAM, we get [**Errno 26] Text file busy** which should not be the case. It also removes  mnem_extract_server from the file system!!!

``failed: [a.retriever.prod.taas] => (item=**mnem_rtrv_mgr_server**) => {"failed": true, "item": "mnem_rtrv_mgr_server", "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/hido/.ansible/tmp/ansible-tmp-1470407355.62-234921640031354/s3\", line 2846, in <module>\r\n    main()\r\n  File \"/home/hido/.ansible/tmp/ansible-tmp-1470407355.62-234921640031354/s3\", line 495, in main\r\n    download_s3file(module, s3, bucket, obj, dest, retries, version=version)\r\n  File \"/home/hido/.ansible/tmp/ansible-tmp-1470407355.62-234921640031354/s3\", line 322, in download_s3file\r\n    key.get_contents_to_filename(dest)\r\n  File \"/usr/lib/python2.7/dist-packages/boto/s3/key.py\", line 1707, in get_contents_to_filename\r\n    with open(filename, 'wb') as fp:\r\nIOError: [**Errno 26] Text file busy**:'/opt/taas/home/taas/bin/mnem_rtrv_mgr_server'\r\n", "msg": "MODULE FAILURE", "parsed": false}`
`
**command line aws s3 cp does not exibit this problem**.
##### EXPECTED RESULTS

for the s3 module to cp the file from s3 to the target host. Also module should not destroy target file if has an error!!!
##### ACTUAL RESULTS

S3 modules destroys file and fails with 'text file busy'

```
failed: [a.retriever.prod.taas] => (item=**mnem_rtrv_mgr_server**) => {"failed": true, "item": "mnem_rtrv_mgr_server", "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/hido/.ansible/tmp/ansible-tmp-1470407355.62-234921640031354/s3\", line 2846, in <module>\r\n    main()\r\n  File \"/home/hido/.ansible/tmp/ansible-tmp-1470407355.62-234921640031354/s3\", line 495, in main\r\n    download_s3file(module, s3, bucket, obj, dest, retries, version=version)\r\n  File \"/home/hido/.ansible/tmp/ansible-tmp-1470407355.62-234921640031354/s3\", line 322, in download_s3file\r\n    key.get_contents_to_filename(dest)\r\n  File \"/usr/lib/python2.7/dist-packages/boto/s3/key.py\", line 1707, in get_contents_to_filename\r\n    with open(filename, 'wb') as fp:\r\nIOError: [**Errno 26] Text file busy**:'/opt/taas/home/taas/bin/mnem_rtrv_mgr_server'\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
