### ISSUE TITLE
ansible-playbook --syntax-check now behaves erratically for two situations

### ISSUE THREAD

**Issue by mschuchard** [ansible/ansible#16988]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### OS / ENVIRONMENT

Ubuntu 15.10
##### SUMMARY

`ansible-playbook --syntax-check` is behaving very erratically for two situations.
##### STEPS TO REPRODUCE

Example one:

```

---
- hosts: whatever
- sudo_user: root

  tasks:
    - name: hello world
      file: path=/hello/world state=directory
```

```
 [WARNING]: provided hosts list is empty, only localhost is available

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method
 is 'sudo' (default).
This feature will be removed in a future release. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! the field 'hosts' is required but was not set
```

```
- hosts: whatever

  tasks:
    - name: hello world
      file: path=/hello/world state=directory
```

```

 [WARNING]: provided hosts list is empty, only localhost is available



```

Example two:

```

---
- hosts: whatever

  tasks:
    #this include has a syntax error
    - include: test.yml

    - name: hello world
      file: path=/hello/world state=directory
```

```
 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/matt/git_repos/linter-ansible-syntax/spec/fixtures/test.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- hosts: webservers
  ^ here


The error appears to have been in '/home/matt/git_repos/linter-ansible-syntax/spec/fixtures/test.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- hosts: webservers
  ^ here
```
##### EXPECTED RESULTS

For `ansible-playbook --syntax-check` to behave non-erratically in the above situations.
##### ACTUAL RESULTS

See above.

**Comment by bcoca** [comment]
Not sure i understand the problems:
- In the first case you are defining 2 plays, the 2nd one does not have 'hosts' defined so you get the appropriate error.
- In the second case, Ansible gives you the best approximation it can to where the error is (normally the 'last good part parsed').

What else were you expecting? can you define 'non-erratically'?

**Comment by mschuchard** [comment]
The first example shows that by inserting the line:

```
- sudo_user: root
```

in a playbook, the following output is triggered:

```
ERROR! the field 'hosts' is required but was not set
```

I don't see this as expected behavior.

---

The second example shows that by including a file with a syntax error, the following error is triggered:

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
```

I don't understand how this can be expected behavior either.

The double guess I already reported in #15948, so I am not including that as part of this issue.

**Comment by bcoca** [comment]
For the first one:

This is ONE play (which is totally valid and will just gather facts on the 'whatever' hosts):

```
- hosts: whatever 
```

This is a SECOND play:

```
- sudo_user: root
```

Which is missing `hosts:`, which is required for every play, hence the error.

On the second, I really don't see how reporting an invalid task list is wrong nor unexpected.

**Comment by bcoca** [comment]
I believe you want one play:

```
- hosts: whatever
  sudo_user: root
  tasks:
    - name: hello world
      file: path=/hello/world state=directory
```
