### ISSUE TITLE
the file_name <filename> does not exist, or is not readable

### ISSUE THREAD

**Issue by pleegor** [ansible/ansible#16984]
##### ISSUE TYPE

- Bug Report
- Feature Idea
- Documentation Report
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

OS X with 3 CentOS vagrant boxes 
##### SUMMARY

When I am trying to move file from directory using copy module I am getting "the file_name <filename> does not exist, or is not readable" error
##### STEPS TO REPRODUCE

```
    - name: Download config files from GitHub
      git: clone=yes repo=git://github.com/pleegor/nrpe_config.git dest=/tmp/nrpe

    - name: Copy config files into correct directory
      copy:
        src: "{{item.src}}"
        dest: "{{item.dest}}"
        owner: nagios
        group: nagios
        mode: 644
      with_items:
        - src: "/tmp/nrpe/nrpe.cfg"
          dest: "/etc/nagios/"
        - src: "/tmp/xinetd-nrpe"
          dest: "/etc/xinetd.d/nrpe"

I am able to see file in /tmp/nrpe/nrpe.cfg on vagrant boxes:

ls -ls /tmp/nrpe/
total 20
4 -rw-r--r--. 1 root root 1522 Aug  6 01:51 check_disk.sh
8 -rw-r--r--. 1 root root 8118 Aug  6 01:51 nrpe.cfg
4 -rw-r--r--. 1 root root    6 Aug  6 01:51 README.md
4 -rw-r--r--. 1 root root  458 Aug  6 01:51 xinetd-nrpe

```

##### EXPECTED RESULTS

I would expect nrpe.cfg file from /tmp/nrpe/nrpe.cfg being moved into /etc/nagios/ directory
##### ACTUAL RESULTS

This is the full error I am getting while running my playbook:

```
task path: /Users/igor/PycharmProjects/cb/ansible1/install_nrpe:44
fatal: [192.168.60.4]: FAILED! => {"failed": true, "msg": "the file_name '/tmp/nrpe/nrpe.cfg' does not exist, or is not readable"}
fatal: [192.168.60.5]: FAILED! => {"failed": true, "msg": "the file_name '/tmp/nrpe/nrpe.cfg' does not exist, or is not readable"}
fatal: [192.168.60.6]: FAILED! => {"failed": true, "msg": "the file_name '/tmp/nrpe/nrpe.cfg' does not exist, or is not readable"}
```
