### ISSUE TITLE
Unneccessary warning when creating archives

### ISSUE THREAD

**Issue by gbirke** [ansible/ansible#16994]
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When creating an archive with the `tar` command, I get a warning that is misleading in this context.
##### STEPS TO REPRODUCE

```

---
- hosts: all
  tasks:
     - name: Create tarball
       shell: tar --exclude=".git" -czf {{ build_dir }}.tar.gz -C {{ build_dir }} .
```
##### EXPECTED RESULTS

Task runs without warnings
##### ACTUAL RESULTS

The command runs as expected, but the output contains the following message:

```
 [WARNING]: Consider using unarchive module rather than running tar
```
##### WORKAROUND

Add `warn=no` to the tar command, but then I fear that other, helpful warnings might be suppressed.
