### ISSUE TITLE
2.1.1.0-1 dict parsing errors

### ISSUE THREAD

**Issue by n2aws** [ansible/ansible#17001]
Edited,  didn't realize I had half of this report listed within comment blocks,  so they didn't appear.  Apologies!
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/jpalmer/source/s2s/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Ubuntu Xenial
##### SUMMARY

I have a group_vars/all/foo dict that has not caused any issues until 2.1.1.0-1.  With this version, the dict seems to be incorrectly parsed, even if the playbook itself isn't utilizing the dict.  I get several errors about missing files (users authorized_keys pubfiles, that are contained as lookups in the dict)
##### STEPS TO REPRODUCE

1) Have a dict in group_vars/all that contains a lookup to a file (in my case, an ssh authorized_keys file) 
2) Make sure one of the files doesn't exist.
3) Have a playbook that doesn't reference the dict
4) Execute the playbook, and look for errors about missing files, even when your playbook doesn't reference them. 

##### EXPECTED RESULTS

dict parsing to continue working the way it used to.  ie, evaluating a lookup only as needed,  rather than lookup all files for every run regardless of if they are needed or not.
##### ACTUAL RESULTS

The dict is parsed fully for every run, regardless if the playbook needs it.

**Comment by alikins** [comment]
Have an example playbook that demonstrates this?

**Comment by n2aws** [comment]
I do,   but it doesn't appear to be playbook specific.

group_vars/all/user,     I have a dict in the form of:

```
---
users:
  ops:
    foouser:
      name: Foo User 
      groups: ops
      ssh_pubkey: "{{ lookup('file', 'foouser.pub') }}"
```

<snipped for brevity, but I have about 4 groups (like ops)  and about 40 users in total in my dict.>

playbook:

```
---
- hosts: [mysql] 
  remote_user: myuser 
  gather_facts: false
  become: True
  tasks:
    - name: Add ops group
      group: name=ops state=present

    - name: Add newdba to machine 
      user: name=newdba groups=ops,mysql append=yes

    - name: ssh key
      authorized_key: user=newdba key="ssh-rsa AAAAB3NzaC1kc3MAAACBAMvS0oHc8O6tBn<...>"
```

And finally,   in the hostgroup:

```
[mysql]
server1-atl
192.168.0.37
server4-chi
192.168.15.38
```
