### ISSUE TITLE
Failed to cast value to int in docker_service > scale parameter while using variable

### ISSUE THREAD

**Issue by inabhi9** [ansible/ansible#17017]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

No special configuration required
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Throws `unsupported operand type(s) for -: 'str' and 'int'"` while using variable in docker_service scale parameter even if variable is casted to int like `{{ num_procs | int }}`
##### STEPS TO REPRODUCE

```
- docker_service:
      project_name: "{{ web_processname }}"
      scale:
        web: "{{ num_procs | int }}"
      project_src: web.yml
```

##### EXPECTED RESULTS

Shouldn't raise error
##### ACTUAL RESULTS

```
Error scaling web - unsupported operand type(s) for -: 'str' and 'int'"
```
