### ISSUE TITLE
random MODULE FAILURE on apt module 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#17043]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

apt - package manager
##### ANSIBLE VERSION

Paste verbatim output from “ansible --version” between quotes below
Host:

```
ansible 2.1.1.0
  config file = /home/lukasbeumer/Checkout/devops/infrastructure/openstack/premiumstore/premiumstore-dev/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
roles_path = ../../../ansible/roles
forks=10
retry_files_enabled = False

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -F ssh_config
```
##### OS / ENVIRONMENT

```
Host: Ubuntu 16.04 LTS
Guest: Ubuntu 14.04 LTS
```
##### SUMMARY

Sometimes the apt-module fails because of an unexpected MODULE FAILURE without any stdout or stderror

```
TASK [php : install php 5.6] ***************************************************
fatal: [lb-dev]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
##### STEPS TO REPRODUCE

It isn't possible to reproduce this error, because it happen not regulary. But when I run the playbook a second or a third time it runs without errors completely. And this failure comes not only on the task (see below)

```
- name: "install php {{ php_version }}"
  become: yes
  apt: name="php{{ php_version }}" state={{ php_installation_state | default("present") }}
  notify:
    - restart php services
```
##### EXPECTED RESULTS

```
TASK [php : install php 5.6] ***************************************************
ok: [lb-dev]
```
##### ACTUAL RESULTS

```
fatal: [lb-dev]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

When I run the playbook with -vvvv there is only coming a long ssh debug output.

**Comment by nitzmahone** [comment]
Once the module has run successfully, are you able to reproduce the failure on the same host? ie, does it only fail when there are changes to be made, or can it fail when the target host is already in the correct state? The ssh debug output _might_ be helpful as well- basically this failure means the module died before returning any JSON (or anything but a CRLF, or so it appears in this case). Also, does it always die on the apt module, or has it failed this way for other things? Just trying to narrow things down... 

(depending on the answer, we may have you move this issue to the ansible-modules-core repo, if we're able to nail it down to a problem with the module and not ansible core engine).

**Comment by ghost** [comment]
Hi @nitzmahone,
we run our automation with jenkins so I can see the history of our builds. It's the lb-dev host mostly which fails with this error, but it happends on the frontend-dev oder backend-dev servers too. Completely random.

Most of the MODULE FAILURE are happen in the tasks:

```
- name: "install default packages"
  become: yes
  apt: name="{{ item.package }}" state="{{ item.state|default('present') }}"
  with_items:
    - { package: "netcat" }
    - { package: "tree" }
    - { package: "openssl", state: "latest" }
    - { package: "vim" }
    - { package: "curl" }
    - { package: "git" }
    - { package: "zip" }
    - { package: "tmux" }
    - { package: "htop" }
    - { package: "logrotate" }
    - { package: "unzip" }
    - { package: "apt-transport-https" }
    - { package: "acl" }
    - { package: "python-passlib" }
    - { package: "mysql-client" }
    - { package: "python-mysqldb" }
```

And in this task:

```
- name: "install php {{ php_version }}"
  become: yes
  apt: name="php{{ php_version }}" state={{ php_installation_state | default("present") }}
  notify:
    - restart php services
```

But the package was installed successfully.. And it only dies on the **apt module**.

Here is the debug output:

```
http://pastebin.com/RGNHDY2S
```
