### ISSUE TITLE
retries documentation and behaviour for 1.9 is inconsistent

### ISSUE THREAD

**Issue by electrofelix** [ansible/ansible#17059]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

runner
##### ANSIBLE VERSION

```
ansible 1.9.6
  configured module search path = None
```
##### CONFIGURATION

none
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Current documentation for `retries` under playbook_loops contains the following text:

> The task returns the results returned by the last task run. The results of individual retries can be viewed by -vv option. The registered variable will also have a new key "attempts" which will have the number of the retries for the task.

This suggests that you would see the same message appearing on failure from the last attempt as you would if retries was not applied to the task. Unfortunately the code replaces the contents of 'msg' in the results returned, thus hiding any information from many executed module as to what the error was that caused the retry to fail. Some modules such as the `shell` and `command` modules will include `stdout` separately, however as the common module boilerplate https://github.com/ansible/ansible/blob/stable-1.9/docsite/rst/developing_modules.rst#id5 encourages many modules to use `msg` for any messages back to the user when calling `exit_json`, those that include useful information via other attributes upon error with retries/until to be displayed are the exception rather than the rule.

While it is possible to print the result from each attempt using '-vv', it's not practical to enable this for long playbooks.
##### STEPS TO REPRODUCE

As the command module uses msg for errors for cases where it detects a problem with the arguments given, it provides a simple example

```
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - command:
      register: _test_retries_shell_result
      until: _test_retries_shell_result.rc == 0
      retries: 3
      delay: 
```

Alternatively, can see better with the pip module

```
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - pip:
        name: pip wheel virtualenv
        virtualenv: ~/tmp/test-virtualenv
        state: present
        extra_args: >
          --upgrade
          --timeout 30
          --invalid-arg
      register: _test_retries_virtualenv_result
      until: _test_retries_virtualenv_result|success
      retries: 3
      delay: 1
```
##### EXPECTED RESULTS

Expected to see the same output from the last iteration of the retry task as would normally appear if retries was not applied to the task, and the additional message about failing due to exceeding the specified number of retries.

command example

```
PLAY [localhost] ************************************************************** 

TASK: [command ] ************************************************************** 
failed: [localhost] => {"attempts": 3, "failed": true, "rc": 256}
msg: no command given
Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
command  ---------------------------------------------------------------- 0.09s
-------------------------------------------------------------------------------
Total: ------------------------------------------------------------------ 0.11s
           to retry, use: --limit @/home/<user>/test-virtualenv.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

pip example

```
failed: [localhost] => {"attempts": 3, "cmd": "/home/baileybd/tmp/test-virtualenv/bin/pip install --upgrade --timeout 30 --invalid-arg\n pip wheel virtualenv", "failed": true}
msg: 
:stderr: 
Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --invalid-arg
Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting
```
##### ACTUAL RESULTS

command example

```
PLAY [localhost] ************************************************************** 

TASK: [command ] ************************************************************** 
failed: [localhost] => {"attempts": 3, "failed": true, "rc": 256}
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
command  ---------------------------------------------------------------- 3.32s
-------------------------------------------------------------------------------
Total: ------------------------------------------------------------------ 3.35s
           to retry, use: --limit @/home/<user>/test-virtualenv.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

pip example

```
PLAY [localhost] ************************************************************** 

TASK: [pip ] ****************************************************************** 
failed: [localhost] => {"attempts": 3, "cmd": "/home/<user>/tmp/test-virtualenv/bin/pip install --upgrade --timeout 30 --invalid-arg\n pip wheel virtualenv", "failed": true}
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
pip  -------------------------------------------------------------------- 4.21s
-------------------------------------------------------------------------------
Total: ------------------------------------------------------------------ 4.24s
           to retry, use: --limit @/home/<user>/test-virtualenv.retry

localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
