### ISSUE TITLE
Variable assignment with conditional breaks facts

### ISSUE THREAD

**Issue by antoineco** [ansible/ansible#17057]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
set_fact and conditionals

##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

```
# Ansible configuration file generated by DebOps, all changes will be lost.
# You can manipulate the contents of this file via `.debops.cfg`.

[ssh_connection]

[paramiko]

[defaults]
filter_plugins = /ansible/ansible/filter_plugins:/root/.local/share/debops/debops-playbooks/playbooks/filter_plugins:/usr/share/ansible/filter_plugins
hostfile = /ansible/ansible/inventory
roles_path = /ansible/roles:/ansible/ansible/roles:/root/.local/share/debops/debops-playbooks/playbooks/../roles:/root/.local/share/debops/debops-playbooks/playbooks/roles:/etc/ansible/roles
connection_plugins = /ansible/ansible/connection_plugins:/root/.local/share/debops/debops-playbooks/playbooks/connection_plugins:/usr/share/ansible/connection_plugins
library = /ansible/ansible/library:/root/.local/share/debops/debops-playbooks/playbooks/library:/usr/share/ansible/library
vars_plugins = /ansible/ansible/vars_plugins:/root/.local/share/debops/debops-playbooks/playbooks/vars_plugins:/usr/share/ansible/vars_plugins
ansible_managed = This file is managed remotely, all changes will be lost
action_plugins = /ansible/ansible/action_plugins:/root/.local/share/debops/debops-playbooks/playbooks/action_plugins:/usr/share/ansible/action_plugins
callback_plugins = /ansible/ansible/callback_plugins:/root/.local/share/debops/debops-playbooks/playbooks/callback_plugins:/usr/share/ansible/callback_plugins
lookup_plugins = /ansible/ansible/lookup_plugins:/root/.local/share/debops/debops-playbooks/playbooks/lookup_plugins:/usr/share/ansible/lookup_plugins
```
##### OS / ENVIRONMENT

All machines: Ubuntu 16.04
##### SUMMARY

A variable assignment containing a conditional leads to unexpected behavior of facts.
##### STEPS TO REPRODUCE

Consider a group `service_etcd` containing 3 machines with the following names and IP addresses:
- nemo 192.168.3.1
- noah 192.168.3.2
- nils 192.168.3.3

I'm composing a list dynamically from the members of this group with the following format:

``` json
[
  "nemo=https://192.168.3.1:2380",
  "noah=https://192.168.3.2:2380",
  "nils=https://192.168.3.3:2380"
]
```

Here is the playbook which achieves that:

`group_vars/all.yml`

``` yaml
etcd__name: '{{ ansible_hostname }}'
etcd_scheme: '{{ "https" if etcd__pki else "http" }}'
etcd__initial_advertise_peer_urls: '{{
          etcd_scheme + "://" + ansible_default_ipv4.address + ":2380"
      }}' 
```

`roles/etcd/defaults/main.yml`

``` yaml
etcd__pki: '{{ (True
                  if (ansible_local|d() and ansible_local.pki|d() and
                      ansible_local.pki.enabled|d() | bool)
                  else False) | bool }}'
```

``` yaml

---

- name: etcd
  hosts: [ 'service_etcd' ]
  become: True

  pre_tasks:

    - name: Gather facts from etcd members
      setup:
      delegate_facts: True
      delegate_to: '{{ item }}'
      with_items: "{{ groups['service_etcd'] }}"

    - name: Collect etcd members list
      local_action:
        module: set_fact
        etcd_members: "{{ (etcd_members | default([])) + [
                             hostvars[item]['etcd__name'] + '='
                             + hostvars[item]['etcd__initial_advertise_peer_urls']
                          ]
                       }}"
      with_items: "{{ groups['service_etcd'] }}"
      run_once: True
      become: False

    - name: DEBUG
      local_action:
        module: debug
        var: etcd_members
      become: False

 roles:

    - role: etcd
```
##### EXPECTED RESULTS

The DEBUG task should output:

``` json
TASK [DEBUG] *******************************************************************
ok: [nemo -> localhost] => {
    "etcd_members": [
        "nemo=https://192.168.3.1:2380", 
        "noah=https://192.168.3.2:2380", 
        "nils=https://192.168.3.3:2380"
    ]
}
ok: [nelson -> localhost] => {
    "etcd_members": [
        "nemo=https://192.168.3.1:2380", 
        "noah=https://192.168.3.2:2380", 
        "nils=https://192.168.3.3:2380"
    ]
}
ok: [noah -> localhost] => {
    "etcd_members": [
        "nemo=https://192.168.3.1:2380", 
        "noah=https://192.168.3.2:2380", 
        "nils=https://192.168.3.3:2380"
    ]
}
```
##### ACTUAL RESULTS

The DEBUG task outputs:

``` json
TASK [DEBUG] *******************************************************************
ok: [nemo -> localhost] => {
    "etcd_members": [
        "nemo=https://192.168.3.1:2380", 
        "noah=https://192.168.3.1:2380", 
        "nils=https://192.168.3.1:2380"
    ]
}
ok: [noah -> localhost] => {
    "etcd_members": [
        "nemo=https://192.168.3.1:2380", 
        "noah=https://192.168.3.1:2380", 
        "nils=https://192.168.3.2:2380"
    ]
}
ok: [nelson -> localhost] => {
    "etcd_members": [
        "nemo=https://192.168.3.1:2380", 
        "noah=https://192.168.3.1:2380", 
        "nils=https://192.168.3.3:2380"
    ]
}
```
##### WORKAROUND

Do the following change in `group_vars/all.yml`

``` diff
-etcd_scheme: '{{ "https" if etcd__pki else "http" }}'
+etcd_scheme: 'https'
```

Without the conditional the value of the `etcd_members` variable is set to its expected value.

**Comment by drybjed** [comment]
@antoineco Does it work if you try setting:

``` yaml
etcd_scheme: '{{ "https" if etcd__pki | bool else "http" }}'
```

ie. explicitly checking the boolean value in the variable that depends on it?

**Comment by bcoca** [comment]
`if` is problematic and not supported, use the `ternary` filter instead.

**Comment by antoineco** [comment]
@drybjed nope, explicitly casting the variable to a boolean doesn't change the situation. Setting it explicitly to a boolean value does, for example with `if etcd__pki | default(false) ...`. 

@bcoca thanks for the suggestion, I ignored this filter. Using a `ternary` still generates the same list though:

``` yaml
etcd__initial_advertise_peer_urls: "{{ (etcd__pki | ternary('https://','http://'))
                                       + ansible_default_ipv4.address + ':2380'
                                    }}"
```

## 

I found something interesting while experimenting with a couple of potential workarounds.

If I set the value of the boolean explicitly in the group_vars mentioned above Ansible generates the expected list:

`group_vars/all.yml`

``` yaml
etcd__name: '{{ ansible_hostname }}'
etcd__pki: True
etcd__initial_advertise_peer_urls: "{{ (etcd__pki | ternary('https://','http://'))
                                       + ansible_default_ipv4.address + ':2380'
                                    }}"
```
