### ISSUE TITLE
[REQUEST] Configuration option to suppress warnings of empty inventory

### ISSUE THREAD

**Issue by akamensky** [ansible/ansible#17086]
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

?
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I am working on a product that can use Ansible (not only it though) to perform some tasks on localhost. In this case it is always ran against localhost. Thus there is never ever inventory or hosts file.

As the result I always see in output:

```
 [WARNING]: Host file not found: /etc/ansible/hosts
 [WARNING]: provided hosts list is empty, only localhost is available
```
##### STEPS TO REPRODUCE

Create playbook `example.yml`:

```
- hosts: localhost
  connection: local
  tasks:
    - name: Ensure package is latest is latest
      yum: name=nano state=latest
```

Execute it with:

```
$ ansible-playbook example.yml
```
##### EXPECTED RESULTS

Don't see warning, because there is no hosts files and no inventory by intention (should be rather obvious from `hosts: localhost`)
##### ACTUAL RESULTS

See two warning as in above.
