### ISSUE TITLE
Python not found on remote host Ubuntu 16.04

### ISSUE THREAD

**Issue by zonca** [ansible/ansible#17081]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 14.04 / Ubuntu 16.06
##### SUMMARY

Python is not found

I have a plain Ubuntu 16.04 remote virtual machine (OpenStack).

By default it doesn't have python installed, so before running ansible I ssh and install `python2.7`.

Even after this I get `/usr/bin/python` not found when I try to run the `ping` module because the Ubuntu `python2.7` package does not set the alias.

The fix is to create a symlink on the remote machine `sudo ln -s /usr/bin/python2.7 /usr/bin/python`, this works but is ugly, is there a better way?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

This is answered in our FAQ http://docs.ansible.com/ansible/faq.html#how-do-i-handle-python-pathing-not-having-a-python-2-x-in-usr-bin-python-on-a-remote-machine
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by ronakjain90** [comment]
Having the same issue. Any better way.?

**Comment by alanwsmith** [comment]
While I realize this is closed, this page comes up high in search results. 

The FAQ link from bcoca is helpful for understanding the issue, but doesn't provide a solution for systems that don't have a python2 interpreter at all (e.g. base Ubuntu 16.04). 

To help anyone else who gets here looking for that, try this Gist: [Get Ansible to work on bare Ubuntu 16.04 without python 2.7](https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f)

And, on the off chance that disappears, here's a copy of a high-level example playbook to get you started. 

```yaml
---
- hosts: all
  become: true
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:
  tasks:
  - name: Install NGINX
    apt: name=nginx state=latest
  - debug: msg="{{ ansible_nodename }} (via Gathered Facts from 'setup')"
```

It works as a standalone playbook with Ansible 2.3.0.0 and a Vagrant "ubuntu/xenial64" box.
