### ISSUE TITLE
Local synchronize on remote host fails when ansible_ssh_host != inventory_hostname

### ISSUE THREAD

**Issue by jbscare** [ansible/ansible#17097]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

synchronize action plugin
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (czen-2.1.1.0-1 7d26459587) last updated 2016/08/11 08:50:20 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 1d59edf228) last updated 2016/08/15 14:56:20 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 45e44f2f10) last updated 2016/08/10 17:49:33 (GMT -400)
  config file = /home/jsmift/ansible/dom/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

transport = ssh
private_key_file = /home/ansible/.ssh/id_rsa
remote_user = ansible
log_path = ../logs/ansible.log
ansible_managed = ansible managed via {host}
legacy_playbook_variables = no
host_key_checking = False
system_warnings = False
vault_password_file = /home/ansible/.vault-passfile
forks=20
retry_files_enabled = False
##### OS / ENVIRONMENT

Amazon Linux AMI release 2015.09 and 2016.03
##### SUMMARY

A synchronize task to copy files from one directory to another, on a single remote host, fails when ansible_ssh_host does not match inventory_hostname.
##### STEPS TO REPRODUCE

This task:

```
- name: synchronize sudoers WIP dir to /etc/sudoers.d
 synchronize:
   dest: /etc/sudoers.d
   src: /tmp/sudoers-wip/
   delete: True 
   checksum: True
   times: False
  delegate_to: "{{ inventory_hostname }}"
```

If ec2.ini says

```
vpc_destination_variable = private_ip_address
hostname_variable = tag_Name
```

then inventory_hostname is the Name tag for the host, ansible_ssh_host is the private IP address, and the task tries to rsync via SSH to the private IP address of the host, which fails. If instead ec2.ini says

```
vpc_destination_variable = Name
```

then inventory_hostname and ansible_ssh_host are both the Name tag for the host, and the task correctly rsyncs locally, not via SSH.
##### EXPECTED RESULTS

The rsync should always be local when synching between two directories on a single host. It shouldn't use SSH at all.
##### ACTUAL RESULTS

The task hangs, apparently because it's trying to use SSH and failing.

**Comment by jbscare** [comment]
It also fails when trying to fetch via anonymous rsync. A task like this:

```
- name: pull content from rsync server 
  synchronize: 
    src: rsync://rsync-server/content/
    dest: /tmp/content
    mode: pull 
  delegate_to: "{{ inventory_hostname }}" 
```

hangs; if you look on the remote host, it has these processes:

```
ansible   4893  4892  0 15:11 pts/0    00:00:00 /usr/bin/rsync --delay-updates -F --compress --dry-run --archive --rsh ssh -i /home/ansible/.ssh/id_rsa -S none -o StrictHostKeyChecking=no --rsync-path=sudo rsync --out-format=<<CHANGED>>%i %n%L rsync://rsync-server/content/ /tmp/content
ansible   4894  4893  0 15:11 pts/0    00:00:00 ssh -i /home/ansible/.ssh/id_rsa -S none -o StrictHostKeyChecking=no rsync-server sudo rsync --server --daemon .
```

It shouldn't be trying to log in to 'rsync-server' via SSH here, it should be using anonymous rsync.

**Comment by danielkza** [comment]
I still observe this issue in 2.2.1.0.

**Comment by boscowitch** [comment]
Just run into this basically the example from the documentation is wrong and not working and not working...
for now the only way is to use command or  shell module and manualy call rsync since it fails horribly when trying to use ssh  :(

So the documentation should be ammended or a note added when this will be available:
```
# Synchronize two directories on one remote host.
- synchronize:
    src: /first/absolute/path
    dest: /second/absolute/path
  delegate_to: "{{ inventory_hostname }}"
```
