### ISSUE TITLE
'unicode object' has no attribute 'Value' / Changes between 2.1.0.0 & 2.1.1.0

### ISSUE THREAD

**Issue by westsouthnight** [ansible/ansible#17120]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
2.1.0.0 all works
2.1.1.0 no works
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Mac OS X
##### SUMMARY

Code which we run on 2.1.0.0 not work in version 2.1.1.0
##### STEPS TO REPRODUCE
1. You need have Consul
2. You need have Swarm Cluster

Part of playbook, run:

```
- name: swarm network playbook
  become: true 
  hosts: swarm-clients
  vars:
    - ansible_ssh_port: "{{ ansible_port }}"
  tasks:
    - name: Consul Create Session
      consul_session: 
          action: create
          host: "{{ ansible_hostname }}"
      delegate_to: "{{ inventory_hostname }}"
    - name: Use new lib for get 
      consul_kv: 
          action: get 
          key: docker/swarm/leader
          host: "{{ ansible_hostname }}"
      register: swarm_leader_temp
      delegate_to: "{{ inventory_hostname }}"
    - name: Creating Nice JSON.
      set_fact: swarm_leader="{{ item["Value"] }}"
      with_items: 
       - "{{ swarm_leader_temp.value | to_nice_json }}"
    - name: Extract IPv4 Address
      set_fact: swarm_leader_fact="{{ swarm_leader | regex_replace('^(?P<host>.+):(?P<port>\\d+)$', '\\g<host>') }}"
    - name: Create Host On Fly  
      add_host: 
         hostname=swarm-current-leader
         ansible_ssh_host={{ swarm_leader_fact }}
         ansible_ssh_port={{ ansible_ssh_port }}
```
##### EXPECTED RESULTS

Ansible create swarm-current-leader host with value getted from Consul KV
##### ACTUAL RESULTS

```
FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'unicode object' has no attribute 'Value'\n\nThe error appears to have been in swarm-network-create.yml': line 25, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n      delegate_to: \"{{ inventory_hostname }}\"\n    - name: Creating Nice JSON.\n      ^ here\n"}
```
