### ISSUE TITLE
{{ item }} scope is too wide + variable declaration in 'include:' executes on each step

### ISSUE THREAD

**Issue by flare-ws** [ansible/ansible#17123]
##### ISSUE TYPE
- Bug Report
##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = /usr/share/ansible
```
##### SUMMARY

I don't know what exactly happens here.
Looks like variable declaration in "include: merge.yml var={{ item.path }}" executes on every step in merge.yml, and at the same time {{ item }}  from merge.yml overwrites {{ item }} in "include:" function.

In this dummy example I didn't use {{ var }} defined in main.yml, but my goal was to pass it to loop in included yml.
##### STEPS TO REPRODUCE

`path_to_directory_to_search: /var # for example`

main.yml

```
- name: Get directory names somewhere
  local_action: find
    file_type=directory
    paths="{{ path_to_directory_to search }}" 
    recurse=no
  register: directory_list

- name: include merge.yml for every directory
  include: merge.yml var="{{ item.path | replace(path_to_directory_to_search + '/', '') }}"
  with_items:
    - "{{ directory_list.files }}"
```

merge.yml

```
- name: dummy withitem, which will fail with "no attribute 'path' in item"
  shell: echo {{ item }}
  with_items:
    - 1
    - 2
    - 3
  register: failed_echo

- debug:
    msg: "{{ failed_echo }}"
```
##### EXPECTED RESULTS

1, 2, 3 or something
##### ACTUAL RESULTS

```
fatal: [thehost.flare.ws]: FAILED! => {"failed": true, "msg": "ERROR! 'int object' has no attribute 'path'"}
```
