### ISSUE TITLE
with_dict incorrectly passing null values as empty strings

### ISSUE THREAD

**Issue by gbolo** [ansible/ansible#17159]
##### ISSUE TYPE
- Feature Idea
- Bug Report

##### COMPONENT NAME

`with_dict`
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Running Ansible from: Arch Linux
Target Host: Centos 7, Arch Linux
##### SUMMARY

When passing a dictionary via `with_dict` in a task and using certain portions of it to create values of another dictionary variable, nulls are not being preserved and incorrectly passed as empty string ""
##### STEPS TO REPRODUCE

```
- hosts: localhost
  gather_facts: no
  vars:
        # defaults (for single nodes)
        param1: "defaultParam1"
        param2: ~
        param3: ""
        param4: []

        # overrides (for multiple nodes)
        nodes:
          node1:
            config_path: /tmp/node1.conf
            config_overrides:
              param1: "node1Param1"
              param2: ~
              param3: ""
              param4: []
          node2:
            config_path: /tmp/node2.conf
            config_overrides:

        # dictionaries to be converted to json in config
        single_node_config:
          Param1: "{{ param1 }}"
          Param2: "{{ param2 }}"
          Param3: "{{ param3 }}"
          Param4: "{{ param4 }}"

        multi_node_config:
          Param1: "{{ item.value.config_overrides.param1 | default(param1) }}"
          Param2: "{{ item.value.config_overrides.param2 | default(param2) }}"
          Param3: "{{ item.value.config_overrides.param3 | default(param3) }}"
          Param4: "{{ item.value.config_overrides.param4 | default(param4) }}"

        # toggle
        enable_multi_nodes: false
  tasks:
        # task for single node
        - name: create config
          copy:
            content: "{{ single_node_config | to_nice_json }}"
            dest: /tmp/single.conf
          when: enable_multi_nodes != true

        # task multi nodes
        - name: create configs
          copy:
            content: "{{ multi_node_config | to_nice_json }}"
            dest: "{{ item.value.config_path }}"
          with_dict: "{{ nodes }}"
          when: enable_multi_nodes == true
```
##### EXPECTED RESULTS

```
cat /tmp/single.conf /tmp/node1.conf  /tmp/node2.conf
{
    "Param1": "defaultParam1",
    "Param2": null,
    "Param3": "",
    "Param4": []
}
{
    "Param1": "node1Param1",
    "Param2": null,
    "Param3": "",
    "Param4": []
}
{
    "Param1": "defaultParam1",
    "Param2": null,
    "Param3": "",
    "Param4": []
}
```
##### ACTUAL RESULTS

```
cat /tmp/single.conf /tmp/node1.conf  /tmp/node2.conf
{
    "Param1": "defaultParam1",
    "Param2": null,
    "Param3": "",
    "Param4": []
}
{
    "Param1": "node1Param1",
    "Param2": "",
    "Param3": "",
    "Param4": []
}
{
    "Param1": "defaultParam1",
    "Param2": "",
    "Param3": "",
    "Param4": []
}
```

**Comment by agaffney** [comment]
FYI, @sivel

**Comment by agaffney** [comment]
Here is a much simpler test case showing the same issue in 2.1.1.0:

```
- hosts: localhost
  gather_facts: no
  vars:
        param2: ~

        foo:
          bar: ~
          baz: "{{ param2 }}"
  tasks:
        - debug: msg="{{ param2 }}"
        - debug: msg="{{ foo }}"
        - debug: msg="{{ foo.bar }}"
```

Result:

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": null
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "bar": null,
        "baz": null
    }
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": ""
}
```

**Comment by gbolo** [comment]
This also seems to happen when you specify a default; the second task in this example loses it's `null`:

```
- hosts: localhost
  gather_facts: no
  vars:
        param2: ~

        foo:
          bar: ~
          baz: "{{ param2 }}"
  tasks:
        - debug: msg="{{ param2 }}"
        - debug: msg="{{ param2 | default('test') }}"
        - debug: msg="{{ foo }}"
        - debug: msg="{{ foo.bar }}"
```

Result:

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": null
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": ""
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "bar": null, 
        "baz": null
    }
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": ""
}
```

**Comment by gbolo** [comment]
This bug also seems to affect integers:

```
- hosts: localhost
  gather_facts: no
  vars:
        param2: 7

        foo:
          bar: "7"
          baz: 7
  tasks:
        - debug: msg="{{ param2 }}"
        - debug: msg="{{ param2 | default('test') }}"
        - debug: msg="{{ foo }}"
        - debug: msg="{{ foo.bar }}"
        - debug: msg="{{ foo.baz }}"
```

Result:

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": 7
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "7"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "bar": "7", 
        "baz": 7
    }
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "7"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "7"
}
```

**Comment by alikins** [comment]
I can reproduce with ~2.2

```
ansible 2.2.0 (devel 3e754086b6) last updated 2016/09/16 15:14:47 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 2e1e3562b9) last updated 2016/09/16 15:14:47 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 9b5c64e240) last updated 2016/09/16 15:14:47 (GMT -400)
  config file = /home/adrian/ansible/ansible.cfg
  configured module search path = ['/home/adrian/src/ansible-modules-core', '/home/adrian/src/ansible-modules-extras']
```

```
[fedora-23:ansible (devel % u=)]$ cat repro/with_dict_none_17159/integers.yml 
- hosts: localhost
  gather_facts: no
  vars:
        param2: 7

        foo:
          bar: "7"
          baz: 7
  tasks:
      - name: debug param2 should be int 7
        debug: msg="{{ param2 }}"
      - name: debug param2 or default
        debug: msg="{{ param2 | default('test') }}"
      - name: debug foo
        debug: msg="{{ foo }}"
      - name: debug foo.bar
        debug: msg="{{ foo.bar }}"
      - name: debug foo.baz should be int 7 not string
        debug: msg="{{ foo.baz }}"

[fedora-23:ansible (devel % u=)]$ ansible-playbook -vvv repro/with_dict_none_17159/integers.yml 
Using /home/adrian/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: vault.VaultLib.is_encrypted is deprecated.  Use vault.is_encrypted instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

PLAYBOOK: integers.yml *********************************************************
1 plays in repro/with_dict_none_17159/integers.yml

PLAY [localhost] ***************************************************************

TASK [debug param2 should be int 7] ********************************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/integers.yml:10
ok: [localhost] => {
    "msg": 7
}

TASK [debug param2 or default] *************************************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/integers.yml:12
ok: [localhost] => {
    "msg": "7"
}

TASK [debug foo] ***************************************************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/integers.yml:14
ok: [localhost] => {
    "msg": {
        "bar": "7", 
        "baz": 7
    }
}

TASK [debug foo.bar] ***********************************************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/integers.yml:16
ok: [localhost] => {
    "msg": "7"
}

TASK [debug foo.baz should be int 7 not string] ********************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/integers.yml:18
ok: [localhost] => {
    "msg": "7"
}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0   
```

```
[fedora-23:ansible (devel % u=)]$ cat repro/with_dict_none_17159/simple.yml
- hosts: localhost
  gather_facts: no
  vars:
        param2: ~

        foo:
          bar: ~
          baz: "{{ param2 }}"
  tasks:
        - debug: msg="{{ param2 }}"
        - debug: msg="{{ foo }}"
        - name: debug foo.bar should be None
          debug: msg="{{ foo.bar }}"
        - name: debug foo.baz should be None
          debug: msg="{{ foo.baz }}"

[fedora-23:ansible (devel % u=)]$ ansible-playbook -vvv repro/with_dict_none_17159/simple.yml 
Using /home/adrian/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: vault.VaultLib.is_encrypted is deprecated.  Use vault.is_encrypted instead.
This feature will be removed in version 2.4. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

PLAYBOOK: simple.yml ***********************************************************
1 plays in repro/with_dict_none_17159/simple.yml

PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/simple.yml:10
ok: [localhost] => {
    "msg": null
}

TASK [debug] *******************************************************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/simple.yml:11
ok: [localhost] => {
    "msg": {
        "bar": null, 
        "baz": null
    }
}

TASK [debug foo.bar should be None] ********************************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/simple.yml:12
ok: [localhost] => {
    "msg": ""
}

TASK [debug foo.baz should be None] ********************************************
task path: /home/adrian/src/ansible/repro/with_dict_none_17159/simple.yml:14
ok: [localhost] => {
    "msg": ""
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   

```

**Comment by gbolo** [comment]
would be nice to get this fixed for 2.2 release

**Comment by alikins** [comment]
More oddity. I'm starting to wonder if this is a bug in 'debug'...

debug seems to show the values as strings, but assert thinks they are none

[fedora-23:ansible (devel % u=)]$ cat repro/with_dict_none_17159/integers.yml 

``` yaml

- hosts: localhost
  gather_facts: no
  vars:
        param2_6_int: 6

        foo:
          bar_7_string: "7"
          baz_8_int: 8
  tasks:
      - name: debug param2 should be int 6
        debug: msg="{{ param2_6_int }}"

      - name: debug param2 or default
        debug: msg="{{ param2_6_int | default('test') }}"

      - name: debug foo
        debug: msg="{{ foo }}"

      - name: debug foo.bar_7_string
        debug: msg="{{ foo.bar_7_string }}"

      - name: assert foo.baz_8_int is an int
        assert:
            that:
                - foo.baz_8_int == 8
                - foo.bar_7_string == "7"
                - foo.bar_7_string != 7
                - foo.baz_8_int != "8"

      - name: debug foo.baz_8_int_i should be int 8 not string
        debug: msg="{{ foo.baz_8_int }}"
```

```
fedora-23:ansible (devel % u=)]$ ansible-playbook repro/with_dict_none_17159/integers.yml 

PLAY [localhost] ***************************************************************

TASK [debug param2 should be int 6] ********************************************
ok: [localhost] => {
    "msg": 6
}

TASK [debug param2 or default] *************************************************
ok: [localhost] => {
    "msg": "6"
}

TASK [debug foo] ***************************************************************
ok: [localhost] => {
    "msg": {
        "bar_7_string": "7", 
        "baz_8_int": 8
    }
}

TASK [debug foo.bar_7_string] **************************************************
ok: [localhost] => {
    "msg": "7"
}

TASK [assert foo.baz_8_int is an int] ******************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [debug foo.baz_8_int_i should be int 8 not string] ************************
ok: [localhost] => {
    "msg": "8"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   
```

[fedora-23:ansible (devel % u=)]$ cat repro/with_dict_none_17159/test.yml 

``` yaml
- hosts: localhost
  gather_facts: no
  vars:
        param2: ~

        foo:
          bar: ~
          baz: "{{ param2 }}"
  tasks:
        - assert:
            that:
                - param2 == none
                - param2 is none
                - param2 is defined
                - param2 != ""

        - debug: msg="{{ param2 }}"
        - debug: msg="{{ foo }}"

# foo.bar should be null, but ends up as empty string
        - debug: msg="foo.bar should be |null| but is |{{ foo.bar }}|"

        - assert:
            that:
                - foo.bar == none
                - foo.bar is none
                - foo.bar is defined
                - foo.bar != ""

        - debug: msg="foo.baz should be |null| but is |{{ foo.baz }}|"

        - assert:
            that:
                - foo.baz == none
                - foo.baz is none
                - foo.baz is defined
                - foo.baz != ""
```

```
[fedora-23:ansible (devel % u=)]$ ansible-playbook repro/with_dict_none_17159/test.yml 

PLAY [localhost] ***************************************************************

TASK [assert] ******************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": null
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "bar": null, 
        "baz": null
    }
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "foo.bar should be |null| but is ||"
}

TASK [assert] ******************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "foo.baz should be |null| but is ||"
}

TASK [assert] ******************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=0   

```
