### ISSUE TITLE
[Ansible 2.2] with_fileglob emits warning, fails to glob

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#17192]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

with_fileglob
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 6f678e36d6) last updated 2016/08/23 09:52:36 (GMT +300)
  lib/ansible/modules/core: (devel 91a839f1e3) last updated 2016/08/18 20:46:51 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 1aeb9f8a8c) last updated 2016/08/23 09:03:03 (GMT +300)
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

My role task that uses `with_fileglob: [ prefix-* ]` fails to match files in role/files/prefix-\* and emits a warning.  Here's the task:

```
# roles/fridge/tasks/triggers.yml
- name: /usr/local/sbin/pov-trigger-* scripts
  copy: src={{ item }} dest=/usr/local/sbin/{{ item|basename }} mode=0755
  tags: triggers
  with_fileglob:
    - pov-trigger-*
```

Here's what in `roles/fridge/files/`:

```
$ ls roles/fridge/files/pov-trigger-*
roles/fridge/files/pov-trigger-root-tasks  roles/fridge/files/pov-trigger-update-fridge.pov.lt
```

Here's the ansible output:

```
TASK [fridge : /usr/local/sbin/pov-trigger-* scripts] **************************
 [WARNING]: Invalid request to find a file that matches an empty string or "null" value

```

This used to work fine in Ansible 2.1.1.0.
##### STEPS TO REPRODUCE

``` yml
# test.yml
- hosts: localhost
  gather_facts: no
  tasks:
    - debug: msg={{ item }}
      with_fileglob:
        - prfx-*
```

```
$ tree
.
├── files
│   ├── prfx-a
│   ├── prfx-b
│   └── unrelated
├── Makefile
└── test.yml
```

```
$ ansible-playbook -i localhost, test.yml
```
##### EXPECTED RESULTS

```
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => (item=/home/mg/src/bugs/ansible-bug-17192/files/prfx-a) => {
    "item": "/home/mg/src/bugs/ansible-bug-17192/files/prfx-a", 
    "msg": "/home/mg/src/bugs/ansible-bug-17192/files/prfx-a"
}
ok: [localhost] => (item=/home/mg/src/bugs/ansible-bug-17192/files/prfx-b) => {
    "item": "/home/mg/src/bugs/ansible-bug-17192/files/prfx-b", 
    "msg": "/home/mg/src/bugs/ansible-bug-17192/files/prfx-b"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
 [WARNING]: Invalid request to find a file that matches an empty string or "null" value


PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```
