### ISSUE TITLE
"with_subelements" has major precedence than "when"

### ISSUE THREAD

**Issue by thiagomgo** [ansible/ansible#17276]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

```
with_subelements / when
```
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

```
nil/defaults
```
##### OS / ENVIRONMENT

Linux Mint 18 Sarah
##### SUMMARY

I'm trying to do a role to create an user, for this role is not mandatory to have an authorized key. So when the authorized_keys is empty get an error, but if I fill out authorized_keys field and set to don't put a authorized_keys, there is no errors.
##### STEPS TO REPRODUCE

This playbook:

```

---

- hosts: [ server ]

  vars:
    configure_key: false
    users:
      - username: foobar
        name: Foo Bar
        group: staff
        home_mode: "0750"
        home_create: yes
        home: /home/foobar
        system: no
        state: present
        sudo: true
        #exclusive_keys: true
        #authorized_keys:
        #  - <SOME RSA KEY>

  roles:
    - thiagomgo.users
```

This task:

```
- name: "users | add user's authorized keys"
  authorized_key:
    manage_dir: yes
    exclusive: "{{ item.0.exclusive_keys }}"
    key: "{{ item.1 }}"
    user: "{{ item.0.username }}"
  when: configure_key is defined and configure_key == true
  with_subelements:
    - "{{ users }}"
    - authorized_keys
```

##### EXPECTED RESULTS

Ansible should ignore the task, once the condition wasn't satisfied.
##### ACTUAL RESULTS

```
fatal: [server]: FAILED! => {"failed": true, "msg": "could not find 'authorized_keys' key in iterated item '{u'username': u'foobar', u'group': u'staff', u'name': u'Foo Bar', u'sudo': True, u'system': False, u'home_mode': u'0750', u'exclusive_keys': True, u'state': u'present', u'home': u'/home/foobar', u'home_create': True}'"}

```
