### ISSUE TITLE
when statement in vars_promt does not work ?

### ISSUE THREAD

**Issue by lnyberg** [ansible/ansible#17283]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vars_promt
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

when row in vars_promt section in my playbook seems to have no effect
##### STEPS TO REPRODUCE

```
# Set static IP address on eth0 (also create interface if needed (reboot involved))
# ip can be give as extra patameter ese it vill ask for it.

- name: Cent7 network eth0 with static IP
  hosts: all
  become: yes

  vars:
    s_tmpl_file: "/etc/ansible/files/ifcfg-eth0.j2"
    ifile: "/etc/sysconfig/network-scripts/ifcfg-eth0"
    ip: "192.168.189.56"
    mac: "{{ansible_default_ipv4.macaddress}}"
    gw: "{{ansible_default_ipv4.gateway}}"
    nm: "{{ansible_default_ipv4.netmask}}"
    oip: "{{ansible_default_ipv4.address}}"
    oif: "{{ansible_default_ipv4.interface}}"
    dns1: "{{ansible_dns.nameservers | min}}"
    dns2: "{{gw}}"
    domain: "localdomain"
    line: 'from="{{limit_ip}}" {{key}}'

  vars_prompt:
    - name: ip
      prompt: "What ip should be given ?"
      default: "192.168.189.55"
      private: no
      when: ip = null

# Did not find a way to prompt for vars when asked to do so
# Seems to always prompt
    - name: gw
      prompt: "Gateway ?"
      default: "192.168.189.1"
      private: no
      when: ask is defined



```

##### EXPECTED RESULTS

I expect the playbook to prompt for the gw variable only id ask varaible is provided as extra-vars on commandline.
##### ACTUAL RESULTS

No it promts even if the ask varaiable is not provided. 

```
ansible-playbook  cent7_network.yml  -l 192.168.189.55  --extra-vars 'ip=192.168.189.55'
Gateway ? [192.168.189.1]:

Seems like when row is ignored, assume it is supported as I found some exmples and does not get an error.
```
