### ISSUE TITLE
Ansible will not find tasks in a playbook with hosts field set to 127.0.0.1

### ISSUE THREAD

**Issue by willowmck** [ansible/ansible#17288]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

TaskQueueManager
##### ANSIBLE VERSION

```
2.1.1.0
```
##### OS / ENVIRONMENT

Mac OS/X 10.11.5
##### SUMMARY

We have a simple one task playbook that waits for port availability on localhost.  If we set the hosts field to 127.0.0.1, the TaskQueueManager will not find any tasks.  Changing this to localhost makes it work.  This used to work in Ansible 1.9.x with 127.0.0.1 and the Ansible documentation specifies using the IP address.
##### STEPS TO REPRODUCE

Create a playbook that will wait for port availability on 127.0.0.1 and execute the playbook with Ansible debug turned on.  You will see num_tasks = 0.

```

---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False

  tasks:
  - name: Check that target host & port are accessible
    wait_for: host={{ target_host }} port={{ target_port }} timeout={{ timeout }}
```

##### EXPECTED RESULTS

Expected there to be task execution.
##### ACTUAL RESULTS

No tasks found.

```

```
