### ISSUE TITLE
Ansible 2.1.1 not getting other extra vars

### ISSUE THREAD

**Issue by pscadiz** [ansible/ansible#17300]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible playbooks
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Centos 6.7 / Centos 7
##### SUMMARY

Variables passed in the command line no longer works with roles and ansible plays
##### STEPS TO REPRODUCE

command:

```
ansible-playbook -i test -e "role=test branch=testbranch" playbook.yaml
```

playbook.yaml:

```
- name: create resources
  hosts: localhost
  gather_facts: no
  connection: local
  vars_files:
    - "{{ env }}/group_vars/{{ role }}"
  roles:
    - { role: create_resources, queue_names: "{{ sqs_queues }}" }
```

role:

```
- name: format sqs queue names
  set_fact:
    formatted_queue_name: "{{ item | regex_replace('$','-{{ branch }}') }}"
  with_items: queue_names
  register: formatted_queue_names
- name: print queues
  set_fact: foo="{{ formatted_queue_names.results | map(attribute='ansible_facts.formatted_queue_name') | list }}"
- debug: var=foo
```
##### EXPECTED RESULTS

Working as expected in ansible 1.9.4

```
ok: [127.0.0.1] => {
    "foo": [
        "testqueue1-testbranch", 
        "testqueue2-testbranch"
    ]
}
ok: [localhost] => {
    "foo": [
        "testqueue1-testbranch", 
        "testqueue2-testbranch"
    ]
}
```
##### ACTUAL RESULTS

```
ok: [127.0.0.1] => {
    "foo": [
        "testqueue1-", 
        "testqueue2-"
    ]
}
ok: [localhost] => {
    "foo": [
        "testqueue1-", 
        "testqueue2-"
    ]
}
```
