### ISSUE TITLE
Register variables don't work across plays with different hosts

### ISSUE THREAD

**Issue by sohel2020** [ansible/ansible#17307]
playbook:

```
- name: Install Kubernete Minions Prerequisites
  hosts: kubernete-minions
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: check kubernetes server status
      stat: path=/opt/bin/flanneld
      register: status 
  roles:
  - host-config
  - kubernete-minion

- name: Install and Configure Kubernete Deployer
  hosts: kubernete-deployer
  remote_user: ubuntu
  sudo: yes
  roles:
  - { role: kubernete-deployer, when: "'{{ status.stat.exists }}' == 'False'" }
```

I'hv register **status** for /opt/bin/flanneld file. My intention is to use **status** variable for hosts **kubernete-deployer**. Base on status output I will add role for  kubernete-deployer. 

playbook hosts file is:

```
[kubernete-deployer]
localhost

[kubernete-deployer:vars]
version=release-1.3
kubernetes_repo=https://github.com/kubernetes/kubernetes.git
validate_yaml=False

ansible_connection=local
ansible_become=true
ansible_become_user=root
ansible_become_method=sudo

[kubernete-minions]
54.152.145.109 

[kubernete-minions:vars]
ansible_user=ubuntu
ansible_become=true
ansible_become_method=sudo
ansible_become_user=root
```

I have used above configuration but no luck. **status** variable is not survive for  another host.

**Comment by sohel2020** [comment]
Got the solution:

```
- name: Install Kubernete Minions Prerequisites
  hosts: kubernete-minions
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: check kubernetes server status
      stat: path=/opt/bin/flanneld
      register: status 
  roles:
  - host-config
  - kubernete-minion

- name: Install and Configure Kubernete Deployer
  hosts: kubernete-deployer
  remote_user: ubuntu
  sudo: yes
  roles:
  - { role: kubernete-deployer, when: "'{{ hostvars[groups['kubernete-minions'][0]]['status']['stat']['exists'] }}' == 'False'" }

```
