### ISSUE TITLE
importing undefined environment variable results in empty string

### ISSUE THREAD

**Issue by FlorinAndrei** [ansible/ansible#17329]
##### ISSUE TYPE

- Feature request
##### COMPONENT NAME

environment variables
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /vagrant/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
retry_files_enabled = False
retry_files_save_path = ~/.ansible-retry
```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

In group_vars/all I am importing environment variables into Ansible variables. If the environment variables are undefined, I still get the Ansible variables, but they are set to the empty string.
##### STEPS TO REPRODUCE

```
# grep package_state group_vars/all 
package_state: "{{ lookup('env','ansible_package_state') }}"
```

```

---
- hosts: all
  become: yes
  tasks:

    - name: stop if variables are undefined
      fail: msg='check comments in group_vars/all and edit ~/.bash_profile'
      when: package_state is undefined or nvidia_driver is undefined or main_user is undefined
```

##### EXPECTED RESULTS

I would expect the playbook to trigger the fail task when the ansible_package_state env var is undefined.
##### ACTUAL RESULTS

The fail task is not triggered. When the ansible_package_state env var is undefined, then group_vars/all actually defines package_state as the empty string.

```

```

**Comment by nitzmahone** [comment]
The explicit empty string behavior is by design and would likely break a lot of stuff if we changed it now- perhaps an enhancement for a new arg to the env lookup to allow for Jinja2 undefined to be returned, eg, something like: `{{ lookup('env', 'MY_BOGUS_ENVVAR', allow_undefined=true) }}`

**Comment by FlorinAndrei** [comment]
The `allow_undefined=true` trick would be enough to support cases such as this.

**Comment by sivel** [comment]
You can also handle this using `default` although you would not check whether the var was undefined or not:

```
package_state: "{{ lookup('env','ansible_package_state')|default(None, true) }}"
```

the 2nd argument of `default` uses a truthiness test on the value, and if false, will use the default, so in this case of the lookup returning an empty string, default would make the value `None`, then you can check on that, or whatever other value you want to use.

**Comment by diefans** [comment]
@sivel If I run this with ansible 2.1.1.0, I still get an empty string...

``` yaml
- hosts: localhost
  connection: local

  vars:
    foo: "{{ '' | default(None, true) }}"

  tasks:
    - debug:
        var: foo
```

result:

```
# ansible-playbook test.yml 

PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "foo": ""
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
