### ISSUE TITLE
No Variable Substitution with dictionary key

### ISSUE THREAD

**Issue by atlante77** [ansible/ansible#17324]
##### ISSUE TYPE

- Feature Idea

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

```
roles/ssh/
├── defaults
│   └── main.yml
├── files
├── handlers
├── meta
├── tasks
│   ├── install.yml
│   └── main.yml
├── templates
│   └── ssh.j2

```
##### OS / ENVIRONMENT

```
Localhost | 4.4.6-gentoo 
```
##### SUMMARY

```
Ansible doesn't replace my variable by the value (only on the dictionary key, because same variable works in value).
```
##### STEPS TO REPRODUCE

defaults/main.yml

```
myvariable: myservername
ssh_root_local_config:
  "{{myvariable}}": 
      - {'name': 'User', 'value': 'toto_user'}
      - {'name': 'IdentityFile', 'value': '/etc/sshkeys/id_x'}
  lol: 
      - {'name': 'User', 'value': "{{ myvariable }}"}
      - {'name': 'IdentityFile', 'value': '/etc/sshkeys/id_y'}
```

templates/ssh.j2

```
{% if ssh_root_local_config %}
{% for key, items in ssh_root_local_config.items() %}
Host {{ key }}
{% for option in items %}
    {{ option.name }} {{ option.value }}
{% endfor%}
{% endfor%}
{% endif %}
```

##### EXPECTED RESULTS

```
Host lol
    User myservername
    IdentityFile /etc/sshkeys/id_y
Host myservername
    User toto_user
    IdentityFile /etc/sshkeys/id_x
```
##### ACTUAL RESULTS

```
Host lol
    User myservername
    IdentityFile /etc/sshkeys/id_y
Host {{myvariable}}
    User toto_user
    IdentityFile /etc/sshkeys/id_x
```

**Comment by atlante77** [comment]
Solution : 

```
myvariable: &myvariable "myservername"

sh_root_local_config:
  *myvariable: 
      - {'name': 'User', 'value': 'toto_user'}
      - {'name': 'IdentityFile', 'value': '/etc/sshkeys/id_x'}
  lol: 
      - {'name': 'User', 'value': "{{ myvariable }}"}
      - {'name': 'IdentityFile', 'value': '/etc/sshkeys/id_y'}
```

Another exemple : 
http://yaml-online-parser.appspot.com/?yaml=key1%3A+%26key1+%22child_value1%22%0A%0Aparent_key%3A%0A++child_key1%3A+*key1%0A++child_key2%3A+%22Resolving%3A+{{+key1+}}%22&type=json

**Comment by michalmedvecky** [comment]
Any chance of getting this fixed? Yes it can be worked around using & but I have no idea how to do this when using `with_items` (sending dict to task with items)

**Comment by cytopia** [comment]
@atlante77 
> Solution :
>
> ```myvariable: &myvariable "myservername"
>
> sh_root_local_config:
>
>  *myvariable: 
>      - {'name': 'User', 'value': 'toto_user'}
>      - {'name': 'IdentityFile', 'value': '/etc/sshkeys/id_x'}
>  lol: 
>      - {'name': 'User', 'value': "{{ myvariable }}"}
>      - {'name': 'IdentityFile', 'value': '/etc/sshkeys/id_y'}
> ```
This **does not work** if the variable itself is dynamic:

I have the following task:
```yml
- set_fact:
    kops_subnet_utility_filters:
      vpc-id: "{{ kops_vpc_id }}"
      "tag:KubernetesCluster": "{{ cluster.name }}"
      "tag:SubnetType": Utility
      "tag:kubernetes.io/cluster/{{ cluster.name }}": "owned"
```
The `cluster.name` is a dynamic value which comes from host vars:
```yml
kops_cluster:
  - name: playground-cluster-shop.k8s.local
    version: v1.10.2
```

The above `set_fact` is called in a loop and references `kops_cluster` items as `cluster`.
```yml
- include_tasks: create_cluster_config.yml
  vars:
    cluster: "{{ item }}"
  with_items:
    - "{{ kops_cluster }}"
```

**Comment by danvaida** [comment]
@cytopia why is it that you need to do essentially `value: key` instead of `key: value` in the first place? it’s a rather strange approach. I assume it’s because of how kops tagged the resources, i.e. `kubernetes: owned`. for example, Terraform by default tags resources with `Owner: Terraform`, which makes more sense, IMHO.

LE: found the reasoning behind the tagging [here](https://github.com/kubernetes/kubernetes/issues/35052). I'm going to think about a potential workaround for this and get back to you.

**Comment by cytopia** [comment]
@danvaida I need to be able to substitute variable values on both sides, because that's what Kops is expecting as you can see here:

```yml
      "tag:KubernetesCluster": "{{ cluster.name }}"
      "tag:kubernetes.io/cluster/{{ cluster.name }}": "owned"
```

Which is basically:
```yml
# var on the right (inside value)
- key: "tag:KubernetesCluster"
  val: "{{ cluster.name }}"

# var on the left (inside key)
- key: "kubernetes.io/cluster/{{ cluster.name }}"
  val: "owned"
```

---

However, this does not only affect kubernetes itself, but also if I want to create a VPC with userdefined tags from host_vars, such as:
```yml
my_vpcs_to_create:
  - cidr: 10.0.0.0/16
    tags:
      - key: Name
        val: my-name
      - key: tier
        val: dev
```
I would first have to loop over the vpcs and then also over the tags to add to that vpc which would give me some variable that I have to add to the left and the right side of a key/value pair

**Comment by pstrzelczak** [comment]
I hit this bug today too.
I simply want to declare a dictionary with a key that is declared earlier as a variable:

```
foo: somekey

bar:
  "{{ foo }}" : somevalue
```

The above code produces {"bar" :  {"{{ foo }}" : "somevalue"}} while I expected {"bar" :  {"somekey" : "somevalue"}}

**Comment by shoelzle** [comment]
I have the same problem

**Comment by cytopia** [comment]
I solved it via the following filter: [cytopia/ansible-filter-get_attr](https://github.com/cytopia/ansible-filter-get_attr)

**Comment by shoelzle** [comment]
I noticed that a string in json format is converted by ansible to the corresponding data types (dict, list, string,.. ) in ansible/python:

Example Playbook
```
- name: Test
  hosts: localhost
  gather_facts: no
  vars:
    myvariable: asdf
    ssh_root_local_config: |
      {
        "{{myvariable}}": [
          {"name": "User", "value": "toto_user"},
          {"name": "IdentityFile", "value": "/etc/sshkeys/id_x"}
        ],
        "lol": [
          {"name": "User", "value": "{{ myvariable }}"},
          {"name": "IdentityFile", "value": "/etc/sshkeys/id_y"}
        ]
      }
  tasks:
    - debug: var=ssh_root_local_config.lol
```

Result:
```
$ ansible-playbook test.yml

PLAY [Test] ***************************************************************************************************************************

TASK [debug] **************************************************************************************************************************
ok: [localhost] => {
    "ssh_root_local_config.lol": [
        {
            "name": "User",
            "value": "asdf"
        },
        {
            "name": "IdentityFile",
            "value": "/etc/sshkeys/id_y"
        }
    ]
}

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by ccollicutt** [comment]
[This](
https://github.com/openshift/openshift-ansible-contrib/blob/470e5fe1ba5e85ab000517bbafb868dda1785cfa/reference-architecture/3.9/playbooks/roles/aws/tasks/elb.yaml#L25) seems to work...not sure how it works.

`tags: "{{ {'kubernetes.io/cluster/' ~ clusterid: clusterid, 'clusterid': clusterid} }}"
`

**Comment by aioue** [comment]
In the same position as @cytopia. Gave up trying to make a dynamic key for the `ec2` module and resorted to separate tasks - now key is applied after object creation.

```
- name: gather updated instance facts (newly created instances as well)
  ec2_instance_facts:
    filters:
      vpc-id: "{{ vpc_facts.vpc.id }}"
      "tag:openshift_role": master
    region: us-west-1
  register: register_infra_facts

- name: add dynamic tags to masters
  ec2_tag:
    resource: "{{ item['instance_id'] }}"
    region: us-west-1
    tags:
      "{'kubernetes.io/cluster/{{aws_vpcs[vpc_key_name].tags.env}}': '{{aws_vpcs[vpc_key_name].tags.env}}'}"
  with_items: "{{ register_infra_facts['instances'] }}"
```

**Comment by rodolfo-gonzalez** [comment]
@aioue you can try using [lookup-plugin](https://docs.ansible.com/ansible/2.5/plugins/lookup/list.html)

i have something like this:

```yaml 
sg:
  "{{ project }}-system-{{ env }}":
        lol: text
    vpc_to_s3:
       lol: text2
    "{{ project }}-{{ app }}-{{ env }}-lb":
        lol: text3
    "{{ project }}-{{ app }}-{{ env }}":
        lol: text4
lc:
    security_groups: "{{ lookup('items', sg | list ).split(',') }}"
```

```yaml
- debug:
    msg: "{{ lc.security_groups }}"
```
```shell
TASK [lc : Test custom filters] ***************************************************************************************************************************************************************************************************************************
ok: [api_1] => {
    "msg": [
        "grapevine-system-dev",
        "vpc_to_s3",
        "grapevine-api-dev-lb",
        "grapevine-api-dev"
    ]
}
```

**Comment by ag0n1k** [comment]
I think that there is a maximum number of links for deeply dependent variables.

This example works correctly for templating:

`group_vars/nginx.yml`
```
nginx_path: /etc/nginx
nginx_configurations:
  "{{ nginx_path }}/nginx.conf": "{{ nginx_config }}"
```
`play`
```
- hosts: nginx
  tasks:
    - debug:
        var: nginx_configurations
  roles:
    - nginx
```
`role task`
```.... 
- name: Generate all nginx configurations
  template:
    src: conf.j2
    dest: "{{ item.key }}"
  loop: "{{ nginx_configurations | dict2items }}"
  register: __nginx_config_state
```
`output`
```
TASK [nginx : Generate all nginx configurations] ******************
ok: [test] => (item={'key': '/etc/nginx/nginx.conf'....
...
TASK [debug] **************
ok: [test] => {
    "nginx_configurations": {
        "{{ nginx_path }}/nginx.conf": ....
```

This example does not work:
`group_vars/oozie/segmentation_job`
```
oozie_segmentation_job_name: segmentation-job
oozie_job_root_path: "/etc/{{ oozie_segmentation_job_name }}"
oozie_segmentation_job_configurations:
  "{{ oozie_job_root_path }}/etc/application.conf": "{{ oozie_segmentation_job_application }}"
```
`play`
```
- hosts: oozie
  tasks:
    - debug:
        var: oozie_segmentation_job_configurations
    - debug:
        var: oozie_job_root_path
    - name: "Install segmentation job"
      include_role:
        name: oozie-job
      vars:
        oozie_job_name: "{{ oozie_segmentation_job_name }}"
        oozie_job_configurations: "{{ oozie_segmentation_job_configurations }}"
```
`role tasks`:
```
- debug:
    var: item.key
  loop: "{{ oozie_job_configurations | dict2items }}"

- name: "Generate all {{ oozie_job_name }} configurations"
  template:
    src: conf.j2
    dest: "{{ item.key }}"
  loop: "{{ oozie_job_configurations | dict2items }}"
```
`output`
```
TASK [debug] ************************
ok: [test] => {
    "oozie_segmentation_job_configurations": "VARIABLE IS NOT DEFINED!"
}
TASK [debug] *****************************
ok: [test] => {
    "oozie_job_root_path": "/etc/segmentation-job"
}

TASK [oozie-job : debug] **************
ok: [test] => (item={'key': '{{ oozie_job_root_path }}/etc/application.conf'

TASK [oozie-job : Generate all segmentation-job configurations] ********
failed: [test] (item={'key': '{{ oozie_job_root_path }}/etc/application.conf',
"Destination directory {{ oozie_job_root_path }}/etc does not exist"
```

UPDATE:
simple workaround for that
```
my_dict_is_list:
  - key: "{{ some_path }}/app.conf"
    value: "{{ my_configuration }}"
task:
- template:
    dest: "{{ item.key }}"
    ...
  loop: "{{ my_dict_is_list }}" ##note: without dict2list
```

**Comment by brandond** [comment]
FWIW, if you build the whole dict list in jinja2, you can template any part of it. It appears that Ansible itself only templates dict values, not keys, by design.
```yaml
- name: "Configure {{node.value.name}} Node Auto-Scaling Group"
  register: eks_asg
  ignore_errors: true
  ec2_asg:
    region: "{{region}}"
    state: present
    name: '{{envn}}-eks-{{node.key}}-asg'
    launch_config_name: "{{new_lc_name}}"
    health_check_period: 900
    health_check_type: 'EC2'
    replace_all_instances: true
    replace_batch_size: 2
    termination_policies: ['OldestInstance']
    availability_zones: "{{ec2_subnets | map(attribute='availability_zone') | list}}"
    vpc_zone_identifier: "{{ec2_subnets | map(attribute='id') | list}}"
    wait_for_instances: true
    wait_timeout: 900
    desired_capacity: "{{node.value.asg.desired}}"
    min_size: "{{node.value.asg.min}}"
    max_size: "{{node.value.asg.max}}"
    tags: |
      {{
        [
        { "Name": envn + "-EKS-" + node.value.name.replace(" ", "_")},
        { "HostType": "EKS"},
        { "TechOwner": tag_owner},
        { "AnsibleRole": "EKSNode" },
        { "Environment": envn },
        { "kubernetes.io/cluster/" + eks_cluster.name: "owned" },
        { "k8s.io/cluster-autoscaler/enabled": "true" }
        ]
      }}
```

**Comment by pilou-** [comment]
AFAIK this isn't an issue, see closed issue #19664.

In order to use a template in a key, the whole dict needs to be a string. There is an example [here](https://github.com/ansible/ansible/pull/19664#issuecomment-271883347):
* using double quoted style:
```
key: key2  
var4: "{  
  '{{ key }}': value2
}"
```
* or using literal style:
```
key: key2  
var4: |
  {  
    '{{ key }}': value2
  }
```

**Comment by brandond** [comment]
@pilou- That's the exact same thing I showed. Since there's no way to get Ansible to template the dict keys - you have to template the whole dict. However, you can't use YAML syntax in the template - it all has to be valid Jinja2, and if you mess any of it up you just get the untemplated string left in place instead of an error like you normally would from bad YAML.

Sure would be nice if that was covered in a FAQ somewhere.

**Comment by pilou-** [comment]
> Sure would be nice if that was covered in a FAQ somewhere.

@brandond could you edit the [FAQ](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/reference_appendices/faq.rst) (using a PR or this [link](https://github.com/ansible/ansible/edit/devel/docs/docsite/rst/reference_appendices/faq.rst?description=%3C!---%20Your%20description%20here%20--%3E%0A%0A%2Blabel:%20docsite_pr)) ?

**Comment by ag0n1k** [comment]
I tried to believe in a miracle for 4 hours and still found a way to tag nested variables in the dictionary and combine them, but the only thing I could do was get rid of errors and create a fairly simple example that does not work. Here is an example: https://gist.github.com/ag0n1k/3ab11ded08ebd4d1cc3694d10dbe13f8

**Comment by neekz0r** [comment]
> @cytopia why is it that you need to do essentially `value: key` instead of `key: value` in the first place? it’s a rather strange approach. I assume it’s because of how kops tagged the resources, i.e. `kubernetes: owned`. for example, Terraform by default tags resources with `Owner: Terraform`, which makes more sense, IMHO.


@danvaida  I know you asked this a while ago, but I'd like to provide insight into why I'm doing it. Specifically, with ubuntu 18, they bundled netplan with it.

netplan (thankfully?) uses YAML to pass configuration of interfaces. Unfortunately, those interfaces must be a key reference, eg:

```network:
    ethernets:
        eth0:
            dhcp4: 'no'
    renderer: networkd
    version: 2
```
So, of course I can generate my own structure but to me it makes much more sense to follow netplans method and then just insert a variable for an interface than come up with my own data structure and is glued together via ansible or another method.

**Comment by dongryphon** [comment]
We ran into this as well. While we could de-keyify the data, it is a real surprise that the `{{foo}}` syntax does not work in keys in `yml` files. +1 for please make this work. Our case is also a self-inflicted injury but a lot of work to refactor and (arguably) less clear in the yml

**Comment by prathameshd9** [comment]
Using combine() worked for me
```
- name: Set Vars
  set_fact:
    kube_json:  {}
    
  kube_json: "{{ kube_json | combine({ 
      ssh_root_local_config: {
        myvariable: {
          'User': toto_user,
          'IdentityFile': '/etc/sshkeys/id_x'
        },
        'lol': {
          'User': myvariable,
          'IdentityFile': '/etc/sshkeys/id_y'
        }
      }
    }) }}"

**Comment by mrgavinconway001** [comment]
Here's an example for Kubernetes tagging that worked for me;

```
vars:
  aws_instance_tag: "kubernetes.io/cluster/MYCLUSTERSNAME"
```

Example ec2_tag command
```
- name: Apply AWS tags
  delegate_to: localhost
  ec2_tag:
    ec2_access_key: "{{ ec2_access_key }}"
    ec2_secret_key: "{{ ec2_secret_key }}"
    region: "{{ ec2_region }}"
    resource: "{{ ec2_metadata.instances.0.instance_id }}"
    state: present
    tags: "{{ { aws_instance_tag: 'owned' } }}"

```

**Comment by tmegow** [comment]
```
- name: Set myDict var containing dynamic key and values
  set_fact:
    myDict: "{{ myDict | default({}) | combine({ myVar1: myDictVar2[myVar1] }) }}"
```

Using @prathameshd9's suggestion I used combine to achieve this.

**Comment by jlegido** [comment]
First of all many thanks to all the people investing a lot of effort in this project.

I also want to use variables in my vars.yml file, so I would like this feature being added.

Thanks.

**Comment by Z9n2JktHlZDmlhSvqc9X2MmL3BwQG7tk** [comment]
Workaround:

```yaml
# create a problem variable
- set_fact:
    variable:
      '{{ some_key }}': value

# process jinja2 in keys
- set_fact:
    variable: '{{ variable | to_json }}'
```
