### ISSUE TITLE
how to print the group in hosts with playbook

### ISSUE THREAD

**Issue by haroldTlan** [ansible/ansible#17362]
ISSUE TYPE
- Feature Idea

ANSIBLE VERSION
version: 2.2.0

CONFIGURATION
python2.7

OS / ENVIRONMENT
Linux Ubuntu 

SUMMARY

I want to use my hosts 's group members ip to be some varible
# 
##### STEPS TO REPRODUCE

`$ cat ansible.cfg`
`[temp]`
`192.168.2.[100:110]`

`$ cat temp.yml`

`- hosts: temp`
`remote_user: root`
`tasks:`
`- name: print ipaddress`
`shell: echo "**XXXX**" >> ~/temp.sh`

what should I do in  "**XXXX**",
so that I can get the variable in temp.sh like:

`temp.sh`
`192.168.2.100`
`192.168.2.101`
`192.168.2.102`
......
`192.168.2.110`

Actually，i want to use the hosts ‘ s each ip to be a variable。

@sivel 
Please forgive my @
I am really do not know how to do that

**Comment by jhawkesworth** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by jhawkesworth** [comment]
I think what you want to do is in the FAQ here: http://docs.ansible.com/ansible/faq.html#how-do-i-loop-over-a-list-of-hosts-in-a-group-inside-of-a-template

**Comment by haroldTlan** [comment]
excuse me,

now, i use `play_hosts` to print all hosts

but, how can i print single hosts?

eg:
`$ cat ansible.cfg`

```
[temp]
192.168.2.[100:110]
```

`$ cat temp.yml`

```
- hosts: "{{ temp}}"
   remote_user: root
   vars_files:
       - vars/server.yml
    tasks:
       - name: print all hosts
         shell: echo ""{{ play_hosts }}"" >> ~/temp.sh
       - name: print single hosts
         shell: echo "?????" >> ~/temp.sh
```

Please help me ,thank you 
@jhawkesworth
