### ISSUE TITLE
Deprecation notice for bare variables

### ISSUE THREAD

**Issue by Yatekii** [ansible/ansible#17389]
##### ISSUE TYPE

Documentation Report
##### COMPONENT NAME

Deprecation notice
##### ANSIBLE VERSION

2.1
##### CONFIGURATION

No added settings
##### OS / ENVIRONMENT

OSX 10.11.5
##### SUMMARY

The deprecation notice for bare variables for me looks like this:

[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{files.stdout_lines}}').

For me as maybe not being 100% aware what bare variables are, this is very vague, even with the hint. Maybe this could be elaborated on.
##### STEPS TO REPRODUCE

Use bare variables in the 'with_items' statement like down below:

```
- name: Keep unwanted files absent
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: absent
  with_items: files.stdout_lines
  when: item not in nginx_conf_dir_allowed_files
```

instead of

```
- name: Keep unwanted files absent
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: absent
  with_items: "{{ files.stdout_lines }}"
  when: item not in nginx_conf_dir_allowed_files
```
##### EXPECTED RESULTS

You will get a notice like this:

[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{files.stdout_lines}}').
This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
