### ISSUE TITLE
unexpected newline in  file name 

### ISSUE THREAD

**Issue by jalbstmeijer** [ansible/ansible#17396]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

template or copy task
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.1.0
```
##### CONFIGURATION

```
[defaults]
inventory = ~/inventory
host_key_checking = False
log_path = ~/ansible.log

retry_files_save_path=~/

[ssh_connection]
pipelining = True
```
##### OS / ENVIRONMENT

Centos 6.8
Python 2.7
##### SUMMARY

We use '>' to  span multiple lines.
In Ansible 1.9.6 this worked fine.
In Ansible 2.1.1.0 we see output files containing a trailing line break, visualized as a '?'
##### STEPS TO REPRODUCE

ansible-playbook bug.yml

```
- name: test
  hosts: localhost
  connection: local

  tasks:
    - name: test1
      template:
        src: in.j2
        dest: /tmp/out1
    - name: test2
      template:
        src: in.j2
        dest: >
          /tmp/out2
    - name: test3
      copy:
        src: in.j2
        dest: >
          /tmp/out3
```
##### EXPECTED RESULTS

```
ls -1 /tmp/out
/tmp/out1
/tmp/out2
/tmp/out3
```
##### ACTUAL RESULTS

```
ls -1 /tmp/out
/tmp/out1
/tmp/out2?
/tmp/out3?
```

The '?" just represents a new line

```
$ rm -i /tmp/out*
rm: remove regular file `/tmp/out1'? y
rm: remove regular file `/tmp/out2\n'? y
rm: remove regular file `/tmp/out3\n'? y
```
