### ISSUE TITLE
Create New Playbook Global Option: require_tag

### ISSUE THREAD

**Issue by copperlight** [ansible/ansible#1740]
Currently, if I want a single playbook to serve as a service controller for many machines, I can write something like this:

```
  tasks:
  - name: stop service
    action: service name=mongodb state=stopped
    only_if: "'${state}' == 'stop'"

  - name: start service
    action: service name=mongodb state=started
    only_if: "'${state}' == 'start'"

  - name: restart service
    action: service name=mongodb state=restarted
    only_if: "'${state}' == 'restart'"

```

Which is then called like so:

```
ansible-playbook -c ssh mongodb_service.yml --extra-vars="state=stop"
```

The functionality of tagging tasks _almost_ achieves the same end goal with a tighter playbook and command line invocation:

```
  tasks:
  - name: stop service
    action: service name=mongodb state=stopped
    tags: stop

  - name: start service
    action: service name=mongodb state=started
    tags: start

  - name: restart service
    action: service name=mongodb state=restarted
    tags: restart
```

```
ansible-playbook -c ssh mongodb_service.yml -t stop
```

The problem with using tags to selectively call tasks is that if you forget to include a tag in your command line execution, then it will run all of the tasks in the playbook. In the case of a playbook that functions as a service controller, this can cause problems.  The variable based method will simply skip everything and take no action.

If a new global option called require_tag (true/false) was added, then it would be possible to use the tag based invocation safely.  This option, when specified in a playbook, would prevent any tasks from executing if no tag is selected on the command line.  It might even report the tags that are available within the playbook, as a reminder of the options.
