### ISSUE TITLE
Prompt for input as a task

### ISSUE THREAD

**Issue by icopp** [ansible/ansible#17446]
##### ISSUE TYPE
- Feature Idea
##### SUMMARY

Adding a simple way to expect input for a role would make small, composable roles for simple tasks much easier. Of course, this has to be weighed against the expectation that many sessions will be run non-interactively.

It seems like there's a fairly straightforward way to do this: add a task that can prompt for a var, with a required default to use in a non-interactive session.

For better user experience, the input could be prompted for ahead of time of this task actually running, so that running a playbook with a large set of roles that each prompt for input would supply each prompt labeled with the target machine and task and then run each role with the prompt value substituted in.

For a potential example of use in a role:

```
ansible-do-a-github-thing/defaults/main.yml

---
github_username: ""
```

```
ansible-do-a-github-thing/tasks/main.yml

---
- name: Enter a Github username
  vars_prompt:
    name: github_username
    default: ""
  when: github_username == ""

- name: Authorize SSH keys from Github
  authorized_key:
    key: https://github.com/{{ github_username }}.keys
    user: "{{ ansible_user_id }}"
  when: github_username != ""
```

And using the role in a playbook would look like...

```
roles:
  - role: galaxy-username.do-a-github-thing
```

(Var prompted for if run interactively, or left blank if run non-interactively.)

```
roles:
  - role: galaxy-username.do-a-github-thing
    github_username: numberwang
```

(Var not prompted for.)
