### ISSUE TITLE
delegation shows -> None instead of hostname

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#17455]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

delegation
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

none
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

When I'm delegating to a host defined in the inventory, Ansible shows `-> None` instead of `-> hostname`.
##### STEPS TO REPRODUCE

```
# test.yml

---
- hosts: localhost
  gather_facts: no
  vars:
    where: alsohere
  tasks:
    - command: hostname
      delegate_to: "{{ where or '' }}"
```

```
# hosts
alsohere ansible_ssh_host=127.0.0.1 ansible_connection=local
```

Run `ansible-playbook -i hosts test.yml`
##### EXPECTED RESULTS

```
PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
changed: [localhost -> alsohere]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [command] *****************************************************************
changed: [localhost -> None]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```
