### ISSUE TITLE
password lookup doesn't always respect chars setting

### ISSUE THREAD

**Issue by cpatry-poly** [ansible/ansible#17461]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

password lookup
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible/']
```
##### CONFIGURATION

Pretty much default configuration
##### OS / ENVIRONMENT

Ansible server : Ubuntu 14.04.3 LTS
Managed Host : Debian 8.5
##### SUMMARY

Password don't respect specified characters and use punctuation when it shouldn't
##### STEPS TO REPRODUCE

It's a bit random. I have that issue frequently, but not each time.
When I try to reproduce the problem with a test playbook, I couldn't reproduce the issue.
May be I am crazy or something

```
- name: Create replication role
  postgresql_user:
    name: replication
    encrypted: yes
    password: "{{ lookup('password', '/etc/psql_credentials/' + ansible_hostname + ':replication chars=ascii_letters,digits') }}"
    role_attr_flags: LOGIN,REPLICATION
  become_user: postgres
```
##### EXPECTED RESULTS

The newly created file should contain a password with only ascii_letters and digits.
Something like that :

```
root@ans01:# cat /etc/psql_credentials/namindpsql01:replication
yn0P43VUTYsP4Q0kuZHz
root@ans01:# cat /etc/psql_credentials/alllndpsql01:replication
fgZpUPQtypsaCXkPmMb7
```
##### ACTUAL RESULTS

Instead I got this :

```
root@ans01:# cat /etc/psql_credentials/namindpsql01:replication
yn0P.3VUTYsP4Q0k.ZHz
root@ans01:# cat /etc/psql_credentials/alllndpsql01:replication
fgZpUPQ:-psaCXkPmMb7
```

Maybe it's not a bug and my password line is bad, but I can't figure out what I do wrong.
A little help will be much appreciated.

Best regards,
