### ISSUE TITLE
'with_items' items expanded before conditional evaluation

### ISSUE THREAD

**Issue by cisarpavel** [ansible/ansible#17484]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

ansible 2.1.1.0
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/pavel/projects/it/ansible_install/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

default ansible install using pip
##### OS / ENVIRONMENT

Ubuntu 16.04
##### STEPS TO REPRODUCE

When trying to iterate over list stored as attribute of loop_var, condition _defined_ is not evaluated before startnig loop.
It's quite close to issue https://github.com/ansible/ansible/issues/15258

vars

```
projects:
  - { name: prj1, users: [ "usr1", "usr2" ]}
  - { name: prj2 }
```

main.yml

```
- name: remote access
  include: include.yml
  with_items:
    - "{{ projects }}"
  loop_control:
    loop_var: project
```

include.yml

```
- name: remote access lookup
  set_fact: klist=true
  register: pkeys
  with_items:
    - "{{ project.users }}"
  when:
    - project.users is defined
```
##### EXPECTED RESULTS

Loop should be normally skipped, because attribute is not defined.
##### ACTUAL RESULTS

Currently is command skipped, but in future it will be fatal error.

```
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 'dict object' has no attribute 'users'.
This feature will be removed in a future release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
```
