### ISSUE TITLE
[FreeBSD] regression on 2.1.1.0 for become_user and ssh connection

### ISSUE THREAD

**Issue by tardyp** [ansible/ansible#17497]
Looks like there is a regression on:
https://github.com/ansible/ansible/issues/700

with ansible 2.1.1.0 and FreeBSD
my playbook runs well for 2.1.0.0 but with following warning:

[WARNING]: Using world-readable permissions for temporary files Ansible needs
to create when becoming an unprivileged user which may be insecure. For
information on securing this, see https://docs.ansible.com/ansible/become.html
# becoming-an-unprivileged-user

It is unclear for me reading this documentation how to actually secure it.

my task looks like the following:

```
- name: clone ansible git repository
  # not that this fails with ansible 2.1.1.0 (working with 2.1.0.0)
  become_user: "{{ service_account }}"
  git:
    repo: "{{ ansible_git_repository }}"
    dest: "/home/{{ service_account }}/repo"
    version: master
    accept_hostkey: yes
```

Note that the worldwritable temporary file is not a problem for me as this part is in the bootstrap of my playbook so there is no attack surface on the machine yet.
