### ISSUE TITLE
String converted to array

### ISSUE THREAD

**Issue by jooadam** [ansible/ansible#17505]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### STEPS TO REPRODUCE

```
- hosts: all
  gather_facts: false

  tasks:
    - action: test name={{item}}

      with_items:
        - "['value']"
```

```
#!/usr/bin/python

# WANT_JSON

import json
import subprocess
import sys

with open(sys.argv[1]) as file:
    arguments = json.load(file)

json.dump({'name': arguments['name']}, sys.stdout)
```

```
ansible-playbook test.yml -c local -i localhost, -v
```

##### EXPECTED RESULTS

```
TASK [test] ********************************************************************
ok: [localhost] => (item=['value']) => {"item": "['value']", "name": "['value']"}
```
##### ACTUAL RESULTS

```
TASK [test] ********************************************************************
ok: [localhost] => (item=['value']) => {"item": "['value']", "name": ["value"]}
```
