### ISSUE TITLE
Support ProxyCommand in module_utils for Network like paramiko connection plugin

### ISSUE THREAD

**Issue by wise0103** [ansible/ansible#17514]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

Support ProxyCommand in module_utils for Network (lib/ansible/module_utils/shell.py) like paramiko connection plugin
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel f57f33a8e7) last updated 2016/08/26 06:24:44 (GMT +000)
  lib/ansible/modules/core: (detached HEAD ef84dbbddd) last updated 2016/08/26 06:24:55 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD f29efb5626) last updated 2016/08/26 06:24:58 (GMT +000)
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

In paramiko connection plugin, I find implementation for supporting ProxyCommand.
In network modules, I find ProxyCommand is not supported. Try to support this, I have modified some code in lib/ansible/module_utils, related files are shell.py, network.py.

Here is the main modification in shell.py:

```
         self.ssh = paramiko.SSHClient()
         if key_policy != "ignore":
@@ -93,11 +93,28 @@ class Shell(object):
         if not look_for_keys:
             look_for_keys = password is None

+        sock_kwarg = {}
+        if proxy_command:
+            replacers = {
+                '%h': host,
+                '%p': port,
+                '%r': username
+            }
+            for find, replace in replacers.items():
+                proxy_command = proxy_command.replace(find, str(replace))
+            try:
+                sock_kwarg = {'sock': paramiko.ProxyCommand(proxy_command)}
+            except AttributeError:
+                raise ShellError('Paramiko ProxyCommand support unavailable. '
+                                 'Please upgrade to Paramiko 1.9.0 or newer. '
+                                 'Not using configured ProxyCommand')
+
         try:
             self.ssh.connect(
                 host, port=port, username=username, password=password,
                 timeout=timeout, look_for_keys=look_for_keys, pkey=pkey,
                 key_filename=key_filename, allow_agent=allow_agent,
+                **sock_kwarg
             )
```
##### STEPS TO REPRODUCE

```
After this implementation, we could define ProxyCommand in host and use it in playbook.
I try in ios_command module.

host:
1025 ansible_host=1025 ansible_host=172.16.16.2 ansible_ssh_proxy_command="sshpass -p xxx ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -W %h:%p xxx@10.126.69.49" ansible_user=test ansible_ssh_pass=test

playbook:
- name: Test Proxy
  hosts: 1025
  gather_facts: no
  connection: local
  vars:
    admin_cli:
      host: "{{ hostvars[inventory_hostname]['ansible_host'] }}"
      username: "{{ hostvars[inventory_hostname]['ansible_user'] }}"
      password: "{{ hostvars[inventory_hostname]['ansible_ssh_pass'] }}"
      transport: cli
      proxy_command: "{{ hostvars[inventory_hostname]['ansible_ssh_proxy_command'] }}"
  tasks:
  - name: run show version on remote devices
    ios_command:
      commands:
      - show version
      - show config
      provider: "{{ admin_cli }}"
```

##### ACTUAL RESULTS

```

```
