### ISSUE TITLE
Debugger strategy broken in develop

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#17520]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`ansible-playbook`
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### SUMMARY

When running the playbook below the Ansible playbook debugger should be invoked.
In version 2.2.0 (the current develop branch) this seems broken. I do get a `retry` file.

```

---
- hosts: localhost
  strategy: debug
  gather_facts: no
  vars:
    var1: value1
  tasks:
    - name: wrong variable
      ping:
          data: "{{ wrong_var }}"
```
##### STEPS TO REPRODUCE
- Running this playbook in Ansible version 2.1 results in debugger running
- Running in version 2.2 and the playbook crashes with a `retry` file
##### EXPECTED RESULTS

Invoking the debugger
##### ACTUAL RESULTS

Debugger not invoked
