### ISSUE TITLE
`ansible_user` seems to be ignored when `copy` is used with `with_items`

### ISSUE THREAD

**Issue by chillum** [ansible/ansible#17561]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

`copy`
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/boo/Repos/vm/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

``` ini
[defaults]
remote_user = user
no_target_syslog = True
retry_files_enabled = False
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

`ansible_user` is not properly set when using the iterator with `copy`. I cannot override it from the command-line as well.
##### STEPS TO REPRODUCE

Inventory like:

``` ini
default ansible_host=127.0.0.1 ansible_port=2222 ansible_user='vagrant'
```

This works OK:

``` yaml
- copy:
    src: vimrc
    dest: /root/.vimrc

- copy:
    src: vimrc
    dest: /home/{{ansible_user}}/.vimrc
```

But this not (on the same host and launched in exactly same way):

``` yaml
- copy:
    src: vimrc
    dest: '{{item}}/.vimrc'
  with_items:
    - /root
    - /home/{{ansible_user}}
```

##### EXPECTED RESULTS

I expected this snippets of code to produce equal results and copy the file to `/root/.vimrc` and `/home/vagrant/.vimrc`.
##### ACTUAL RESULTS

The second version of the code somehow forces `ansible_user` to be "user", not "vagrant" and it bails out with error.

```
TASK [base : copy] ************************************************************
ok: [default] => (item=/root)
failed: [default] (item=/home/user) => {"checksum": "6b0c3fd646f96b41def2c7625e6d371382479a8f", "failed": true, "item": "/home/user", "msg": "Destination directory /home/user does not exist"}
```
