### ISSUE TITLE
Template file location

### ISSUE THREAD

**Issue by francisbesset** [ansible/ansible#1757]
Hello,

I start to use ansible for my server.
I have a litte problem with my architecture to reuse my tasks:
- playbook
  - **main.yml**
  - dotdeb
    - **dotdeb.yml**
    - handlers
      - handlers.yml
    - tasks
      - **setup.yml**
    - templates
      - dotdeb.list.j2

**main.yml**:

``` yaml

---
  - hosts: webservers

    tasks:
      - include: dotdeb/tasks/setup.yml

    handlers:
      - include: dotdeb/handlers/handlers.yml
```

**dotdeb/dotdeb.yml**:

``` yaml

---
  - hosts: webservers

    tasks:
      - include: tasks/setup.yml

    handlers:
      - include: handlers/handlers.yml
```

**dotdeb/tasks/setup.yml**:

``` yaml

---
  - name: Add dotdeb squeeze repo
    action: template src="dotdeb/templates/dotdeb.list.j2" dest=/etc/apt/sources.list.d/dotdeb.list
    notify:
      - Download dotdeb GPG
```

In this case I can launch `ansible-playbook main.yml -uroot` without problem but `ansible-playbook dotdeb/dotdeb.yml -uroot` not works:

``` bash
TASK: [Add dotdeb squeeze repo] ********************* 
fatal: [localhost] => {'msg': 'unable to read dotdeb/dotdeb/templates/dotdeb.list.j2', 'failed': True}
fatal: [localhost] => {'msg': 'unable to read dotdeb/dotdeb/templates/dotdeb.list.j2', 'failed': True}

FATAL: all hosts have already failed -- aborting
```

Is it possible to run the both commands `ansible-playbook main.yml -uroot` and `ansible-playbook dotdeb/dotdeb.yml -uroot`?

**Comment by francisbesset** [comment]
I specify that I want share the dotdeb directory, and the main.yml file will be many includes playbook to install a LAMP stack : https://github.com/francisbesset/ansible

**Comment by francisbesset** [comment]
The problem is fixed.
The solution:
**main.yml**:

``` yaml
---
  - hosts: webservers

  - include: dotdeb/dotdeb.yml
```

**dotdeb/tasks/setup.yml**:

``` yaml
---
  - name: Add dotdeb squeeze repo
    action: template src="templates/dotdeb.list.j2" dest=/etc/apt/sources.list.d/dotdeb.list
    notify:
      - Download dotdeb GPG
```
