### ISSUE TITLE
Task with 'when: VARIABLE is defined' and 'with_items: VARIABLE' ends with error/warning

### ISSUE THREAD

**Issue by zeten30** [ansible/ansible#17611]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Conditional when:
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

no changes
##### OS / ENVIRONMENT

Managing RHEL7.2 from Fedora24 
##### SUMMARY

Task that should run only if VARIABLE is defined (using group_vars in inventory) and is also using VARIABLE to iterate over items

```
- name: Name
  something: x={{item}}
  when: VARIABLE is defined
  with_items: {{VARIABLE}}
```

Result is: 
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 
'<VARIABLE>' is undefined.
##### STEPS TO REPRODUCE

Create task similar to below

```
# Run this taks only for nodes participating in LB pools (routers)
- name: Schedule downtime for LB pools
  nagios:
    action: "{{ nagios_action }}"
    minutes: "{{ nagios_downtime_minutes }}"
    host: "{{ nagios_lb_host }}"
    service: "{{item}}"
    comment: "[Jenkins] OSCP job starting"
  when: nagios_lb_pools  is defined
  with_items: "{{ nagios_lb_pools }}"
```

Create inventory with two host sub groups,  define nagios_lb_pools only for one group

Run playbook on all nodes inventory 
##### EXPECTED RESULTS
- task should be skipped if VARIABLE is not defined, no warning or errors should appear. 
- `when:` should have precedence, `with_items:` doesn't need evaluation if `when:` condition is not met
##### ACTUAL RESULTS

`with_items:` is evaluated even if `when:` condition is not met & raises error/warning

```
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this will be a fatal error.: 
'nagios_lb_pools' is undefined.
This feature will be removed in a future release. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
```
