### ISSUE TITLE
a wrong way to judge ending of a role execution

### ISSUE THREAD

**Issue by liuyong2000** [ansible/ansible#17664]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ansible/lib/ansible/playbook  ??
ansible/lib/ansible/executor   ??
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### CONFIGURATION

no change.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

In a play, if you write down one role two times as below,

```

---
- name: play1
  hosts: SSHproxy
  remote_user: root
  gather_facts: false
  roles:
    - csfC
    - csfC
```

You can see that role csfC runs two times when playbook running

```
PLAY [play1] *******************************************************************

TASK [csfC : command] **********************************************************
changed: [SSHproxy]

TASK [csfC : command] **********************************************************
changed: [SSHproxy]

PLAY RECAP *********************************************************************
SSHproxy                   : ok=2    changed=2    unreachable=0    failed=0   
```

If you add another different role between the role, 

```

---
- name: play1
  hosts: SSHproxy
  remote_user: root
  gather_facts: false
  roles:
    - csfC
    - csfD
    - csfC
```

role csfC just run one times

```
PLAY [play1] *******************************************************************

TASK [csfC : command] **********************************************************
changed: [SSHproxy]

TASK [csfD : command] **********************************************************
changed: [SSHproxy]

PLAY RECAP *********************************************************************
SSHproxy                   : ok=2    changed=2    unreachable=0    failed=0   
```

It seems that the way to judge if a role execution ends has something wrong. 
two same role in a play should be executed once.
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```

```

**Comment by krzysztof-magosa** [comment]
> two same role in a play should be executed once.

I don't agree with that. You can have universal role deploying application and run it many times with different variables to deploy many applications.

**Comment by liuyong2000** [comment]
@krzysztof-magosa , in my playbook above, roleC doesn't take with different variables, 
and it will run one time in some condition,  eg.

```
---
- name: play1
  hosts: SSHproxy
  remote_user: root
  gather_facts: false
  roles:
    - csfC
    - csfD
    - csfC
```

in other condition, it will run two times, eg.

```
---
- name: play1
  hosts: SSHproxy
  remote_user: root
  gather_facts: false
  roles:
    - csfC
    - csfC
```

pls see my descriptions in above ticket.
