### ISSUE TITLE
Add Bandwidth Throttling to module_utils/urls.py

### ISSUE THREAD

**Issue by exodusftw** [ansible/ansible#17685]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

module_utils/urls.py
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Would like the ability to set bandwidth limiting/throttling on modules that use the various methods provided in urls.py, namely fetch_url. This would be handy for the maven_artifact, get_url, etc. modules.
##### STEPS TO REPRODUCE

```
# Download JUnit 4.11 from Maven Central
- maven_artifact:
  args:
    group_id: junit
    artifact_id: junit
    version: 4.11
    dest: /tmp/junit-4.11.jar
    bandwidth: 100kb

- name: download foo.conf
  get_url:
    url: http://example.com/path/file.conf
    dest: /etc/foo.conf
    mode: 0440
    limit: 100kb
```
##### EXPECTED RESULTS

Proposing support in module_utils/urls.py for throttling the retrieval of HTTP resources to prevent exceeding the specified bandwidth - obviously, this would also require modifications to the core/extras module to support either a `bandwidth` or `limit` parameter
