### ISSUE TITLE
List not parsed as a list ?

### ISSUE THREAD

**Issue by bechampion** [ansible/ansible#17701]
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

with_items
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

Basic
##### OS / ENVIRONMENT

N/A
##### SUMMARY

List picked up from facts not parsed as a list when called by with_items , instead being taken as a string

When using a basic task with with_items: "{{ groups['all'] }}" ,  the task doesn't iterate in each item
of the list , instead is taken as a string:

changed: [127.0.0.1] => (item= [u'1.1.1.1', u'10.16.0.5'] )  <--  String ?

```
 name: "common task following"
 command: echo " {{ item }} "
 with_items:
   - " {{ groups['all'] }} "                                        
   #- [1,2]

```
##### EXPECTED RESULTS

Should be parsed as a list
##### ACTUAL RESULTS

```
TASK [common : common task following] ******************************************
changed: [1.1.1.1] => (item= [u'1.1.1.1', u'10.16.0.5'] )
changed: [127.0.0.1] => (item= [u'1.1.1.1', u'10.16.0.5'] )

```
