### ISSUE TITLE
Rescue block does not execute when a run_once command fails

### ISSUE THREAD

**Issue by kkurian** [ansible/ansible#17721]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

block / rescue
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Rescue fails to execute in response to a failed command with `run_once: true`.
##### STEPS TO REPRODUCE

```
- hosts: [ cluster ]
  tasks:
    - block:
      - name: fail
        command: 'false'
        run_once: true
      rescue:
      - name: succeed
        assert: { that: 'true' }
```
##### EXPECTED RESULTS

The `command` should fail, triggering the rescue block, causing the `assert` to execute.
##### ACTUAL RESULTS

```
PLAY [cluster] *****************************************************************

TASK [setup] *******************************************************************
ok: [node1]

TASK [fail] ********************************************************************
fatal: [node1]: FAILED! => {"changed": true, "cmd": ["false"], "delta": "0:00:00.006519", "end": "2016-09-23 08:09:56.575114", "failed": true, "rc": 1, "start": "2016-09-23 08:09:56.568595", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
node1                      : ok=1    changed=0    unreachable=0    failed=0
```

Note a secondary problem: Not only didn't the rescue block execute, the play recap states `ok=1`, which can't be right given that the only task to run failed.

Also Note: The playbook runs as expected if the `run_once: true` line is removed.
