### ISSUE TITLE
|failed expects a dictionary when using "when"

### ISSUE THREAD

**Issue by worp1900** [ansible/ansible#17744]
The following configuration

```
- name: check if redis is already installed
  command: redis-cli
  register: redisInstalled
  ignore_errors: true
- name: install redis dependencies
  apt: name={{item}} state=latest
  with_items:
       - build-essential
       - tcl
  when:
    (online) and
    (redisInstalled.rc|failed)
```

results in

`fatal: [schreibnacht]: FAILED! => {"failed": true, "msg": "The conditional check '(online) and (redisInstalled.rc|failed)' failed. The error was: |failed expects a dictionary\n\nThe error appears to have been in '/Users/svhu/vagrant/schreibnacht/ansible/roles/redis/tasks/main.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  ignore_errors: true\n- name: install redis dependencies\n  ^ here\n"}`

According to documentation:
http://docs.ansible.com/ansible/playbooks_conditionals.html#applying-when-to-roles-and-includes
this should be possible:

```
tasks:
  - command: /bin/false
    register: result
    ignore_errors: True

  - command: /bin/something
    when: result|failed
```
