### ISSUE TITLE
when x is defined not working to prevent included tasks from running

### ISSUE THREAD

**Issue by toby-griffiths** [ansible/ansible#17769]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- task/when
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
ANSIBLE_NOCOWS=true
```
##### OS / ENVIRONMENT

OSX 10.10.5
##### SUMMARY

The 'when' condition on the 'include' for a task is not preventing the file form being included, even when false
##### STEPS TO REPRODUCE

Tasks file...

```
# main.yml

---
- debug: var='do_obsolete_users_ssh_keys is defined'

- name: Remove old SSH Keys
  include: ./ssh-keys-remove.yml
  when: do_obsolete_users_ssh_keys is defined
```

```
# ssh-keys-remove.yml

---
- name: Remove DO user's SSH keys
  digital_ocean:
    state: absent
    command: ssh
    name: '{{ item }}'
  with_items:  '{{ do_obsolete_users_ssh_keys }}'
  register:   do_ssh_keys_removed_result
```

Results...

```
PLAY [localhost] ***************************************************************

TASK [digital-ocean : debug] ***************************************************
ok: [localhost] => {
    "do_obsolete_users_ssh_keys is defined": false
}

TASK [digital-ocean : Remove DO user's SSH keys] *******************************
[DEPRECATION WARNING]: Skipping task due to undefined Error, in the future this
 will be a fatal error.: 'do_obsolete_users_ssh_keys' is undefined.
This
feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
skipping: [localhost]
```
##### EXPECTED RESULTS

The tasks within the ssh-keys-add.yml file should not be included.
##### ACTUAL RESULTS

The tasks within the ssh-keys-add.yml file is included, & therefore complains that the variable required does is not defined.
