### ISSUE TITLE
Some problems with :

### ISSUE THREAD

**Issue by Shrek27** [ansible/ansible#17804]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

YAML parser
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel fb50698da3) last updated 2016/09/29
  lib/ansible/modules/core: (detached HEAD 7808f42aff) last updated 2016/09/29 
  lib/ansible/modules/extras: (detached HEAD 881d2f95a8) last updated 2016/09/29 
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I have some problems with colon marks within playbook. Just installed ansible and tried to make simple playbook:

``` yaml
- name: Zabbix install
  hosts: test2
    tasks:
      - name: copy files to client
        copy: src=/var/distrib/zabbix_repo.rpm dest=/var/distrib/zabbix_repo.rpm
      - name: installing repo
        yum: name=/var/distrib/zabbix_repo.rpm
      - name: install zabbix-agent
        yum: name=zabbix-agent state=present
      - name: enabled zabbix autostart
        service: name=zabbix-agent state=running enabled=yes
      - name: some scripts are copying
        copy: src=/var/distrib/zabbix/etc/* dest=/etc/zabbix/ force
        copy: src=/var/distrib/zabbix/usr-libexec/zabbix-extensions dest=/usr/libexec/zabbix-extensions directory_mode
        notify:
          - restart zabbix

    handlers:
      - name: restart zabbix
        service: name=zabbix-agent state=restarted
```
##### ACTUAL RESULTS

So when i execute ansible-playbook -l clientname test.yml i got errors near all coon marks. It looks like parser doesn't understand what colon is.

```
  hosts: test2
    tasks:
         ^ here

```

**Comment by Shaps** [comment]
This is not a bug. `tasks` indentation is wrong, it has to be at the same level as `hosts`:

``` yaml
- name: Zabbix install
  hosts: test2
  tasks:
```
