### ISSUE TITLE
vars_prompt should consider tags

### ISSUE THREAD

**Issue by davixx** [ansible/ansible#1780]
Hi,

It would be great if vars_prompt could be taggable ; 
permitting :
    ansible-playbook my_playbook.yml --tags "config"
To ask for password.

But :
    ansible-playbook my_playbook.yml --tags "import"
To not ask it.

Sample :

```
vars_prompt:
    - name: "root_password"
       prompt: "the future root password"
       encryption: "md5_crypt"
       confirm: True
       private: True
       salt_size: 7
       salt: "blv"
       tags: config

vars_prompt:
    - name: "root_password"
       prompt: "the future root password"
       confirm: True
       private: True
       tags:
         - config
         - check
```

Thanks.

**Comment by mpdehaan** [comment]
I agree!

**Comment by mpdehaan** [comment]
Additionally, ansible commander should probably understand vars_prompt at some point.

**Comment by mpdehaan** [comment]
commander will understand --extra-vars

This is really a better solution in the command line case.  Two playbooks would be a good option here, one for each purpose.

**Comment by gilcot** [comment]
I have the same issue with a recent version on _Debian 7_ box
> ansible-playbook 2.3.1.0
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = Default w/o overrides
>   python version = 2.7.3 (default, Jun 21 2016, 18:38:19) [GCC 4.7.2]

Here is the playbook to reproduce: 
```yaml
---
# vim: ff=unix tw=76 ts=2 sts=2 sw=2 ai et sta fenc=utf-8
# atom:set useSoftTabs tabLength=2 lineending=lf encoding=utf-8
# -*- Mode: tab-width: 2; c-basic-offset: 2; indent-tabs-mode: nil -*-

- hosts: localhost
  gather_facts: no
  become: no
  vars_prompt:
    - name: 'mailaddr'
      private: no
      prompt: "User's Email"
  tasks:
    - name: "Register user's email"
      set_fact:
        email: '{{ mailaddr |lower }}'

- hosts: localhost
  tags: step1
  gather_facts: no
  vars_prompt:
    - name: 'login'
      private: no
      prompt: "User's Login"
    - name: 'cc'
      private: no
      prompt: "User's Country (ISO-3166-1 alpha2)"
      default: "fr"
  tasks:
    - debug:
        msg: "Step 1 for {{ hostvars.localhost.email }}"

- hosts: localhost
  tags: step2
  gather_facts: no
  vars_prompt:
    - name: 'firstname'
      private: no
      prompt: "User's First name"
    - name: 'lastname'
      private: no
      prompt: "User's Last name"
  tasks:
    - debug:
        msg: "Step 2 for {{ hostvars.localhost.email }}"

#eof
```
Now, first try `ansible-playbook issue1780.yml` (or the name you've gaven to the file) and everything should be fine.    
Next, try `ansible-playbook issue1780.yml --skip-tags=step1` and notice that first step variables are prompted but tasks for that play are skiped.   
The obvious understand is that tags are at play level here and then apply to the hole play, isn't it?
