### ISSUE TITLE
RFE: Add network manager ipv4.dns-search to the nmcli module

### ISSUE THREAD

**Issue by todd-dsm** [ansible/ansible#17843]
##### ISSUE TYPE

Feature Idea
##### COMPONENT NAME

nmcli 

##### ANSIBLE VERSION

NA
##### CONFIGURATION

NA
##### OS / ENVIRONMENT

control machine: F24 workstation
managed nodes: centos 7.2
##### SUMMARY

It would be helpful if the nmcli module had the ability to reset the search domain. 
(some clients need some crazy patches till things can be fixed properly)
##### STEPS TO REPRODUCE

Managed Node: CentOS (latest)
### Precondition

``` bash
$ sudo cat /etc/resolv.conf 
# Generated by NetworkManager
search bad-domain.tld
nameserver 8.8.8.8
nameserver 4.4.4.4
```
### Solution

Get connection name

``` bash
nmcli dev status
DEVICE       TYPE      STATE      CONNECTION  
eno16780032  ethernet  connected  **eno16780032** 
lo           loopback  unmanaged  --          
```

Check the search domain

``` bash
sudo nmcli con show eno16780032 | grep ipv4.dns-search
ipv4.dns-search:                        bad-domain.tld
```

Modify search domain associated with the connection

``` bash
sudo nmcli con mod eno16780032 ipv4.dns-search "good-domain.tld"
```

Verify changes to the search domain

``` bash
sudo nmcli con show eno16780032 | grep ipv4.dns-search
ipv4.dns-search:                        good-domain.tld
```

Restart the network manager service

``` bash
sudo systemctl restart NetworkManager
```

Get the net results

``` bash
$ sudo cat /etc/resolv.conf 
# Generated by NetworkManager
search good-domain.tld
nameserver NS1-IP
nameserver NS2-IP
```
### The Hack

Just issuing the command helps us get it done for now.

```
- hosts: all
  become: yes 
  become_method: sudo
  tasks:
      - name: setting DNS resolver config
        nmcli:
          conn_name=eno16780032
          dns4=["NS1-IP", "NS2-IP"]
          state=present
      - name: setting DNS resolver - search domain
        command: /usr/bin/nmcli con mod connName ipv4.dns-search "good-domain.tld"
      - name: restart NetworkManager service
        service: name=NetworkManager state=restarted
```
##### EXPECTED RESULTS

The search domain is modified from the incorrect domain to the correct domain.
These settings persist through reboots.
##### ACTUAL RESULTS

This works; it's just hacky. Perhaps search domain modification should exist for those "special" clients. Discuss it amongst yourselves.
