### ISSUE TITLE
with_first_found gets incorrectly traversed in static includes

### ISSUE THREAD

**Issue by jbergstroem** [ansible/ansible#17891]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`with_first_found`
##### ANSIBLE VERSION

```
$ ansible --version                                                                    
ansible 2.2.0 (detached HEAD 4643bb4c6a) last updated 2016/10/03 11:12:06 (GMT -300)
  lib/ansible/modules/core: (detached HEAD e4c5a13a7a) last updated 2016/10/03 11:12:27 (GMT -300)
  lib/ansible/modules/extras: (detached HEAD df35d324d6) last updated 2016/10/03 11:12:27 (GMT -300)
  config file = /Users/jbergstroem/Work/node/build/ansible/ansible.cfg
```
##### CONFIGURATION

Irrelevant
##### OS / ENVIRONMENT

N/A
##### SUMMARY

If an include is skipped tasks within should also be skipped - but a task using `with_first_found` is still run.
##### STEPS TO REPRODUCE

parent.yml:

``` yaml
- name: install monit
  when: os in needs_monit
  include: monit.yml
```

child.yml:

``` yaml
- name: install monit
  package: name=monit state=present

- name: add monit config
  copy:
  args:
    src: "{{ monitrc }}"
    dest: "/etc/monitrc"
    mode: 0600
  loop_control:
    loop_var: monitrc
  with_first_found:
    - files:
        - "{{ role_path }}/files/{{ os }}.monitrc"
        - "{{ role_path }}/files/{{ fallback }}.monitrc"
```
##### EXPECTED RESULTS

Task using `with_first_found` should not be run
##### ACTUAL RESULTS

Task using `with_first_found` is run (see gist), making it ultimately fail since it can't find the files:

```
TASK [jenkins-worker : install monit] ******************************************
skipping: [foo]

TASK [jenkins-worker : add monit config] ***************************************
 [WARNING]: Unable to find '/Users/jbergstroem/Work/node/build/ansible/roles/jenkins-worker/files/smartos15.monitrc' in expected paths.

 [WARNING]: Unable to find '/Users/jbergstroem/Work/node/build/ansible/roles/jenkins-worker/files/smartos.monitrc' in expected paths.

fatal: [foo]: FAILED! => {"failed": true, "msg": "No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}
```

**Comment by bcoca** [comment]
So the task itself is not executing, but the loop is, this cannot be short circuited through `when` as it runs per item in the loop, to allow for conditional execution of items.

As the message suggests, use the `skip` parameter to first found to avoid this error.

**Comment by jbergstroem** [comment]
(for the internets)

the "proper" way I solved this was by setting the include to dynamic, seeing how the task invoked a loop:

``` yaml
- name: install monit
  when: os in needs_monit
  include: monit.yml
  static: no
```
