### ISSUE TITLE
Binary content gets mangled in a playbook

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#17901]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`ansible-playbook` and Jinja2
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When trying to grab the content of a "binary" file and transfer it using Ansible, the content gets mangled. It appears as if this is due to UTF8-ification of the data.
##### STEPS TO REPRODUCE

Playbook:

```
- hosts: localhost
  gather_facts: no
  tasks:
  - command: cat /tmp/ansible_test/random.file
    register: foo
  - copy:
      dest: /tmp/ansible_test/random2.file
      content: "{{ foo.stdout }}"
```

Create file with binary junk:

```
$ dd if=/dev/urandom of=random.file bs=1 count=10
```

Result:

```
$ ls -l random*file
-rw-rw-r-- 1 agaffney agaffney 14 Oct  4 13:14 random2.file
-rw-rw-r-- 1 agaffney agaffney 10 Oct  4 13:14 random.file

$ hexdump -C random.file
00000000  7e f4 9c 3b 6e ef 55 2e  5e d6                    |~..;n.U.^.|
0000000a

$ hexdump -C random2.file
00000000  7e c3 b4 c2 9c 3b 6e c3  af 55 2e 5e c3 96        |~....;n..U.^..|
0000000e
```
##### EXPECTED RESULTS

Identical files
##### ACTUAL RESULTS

Non-identical files

**Comment by agaffney** [comment]
Additionally, if i add the following task in the playbook, it appears to show the correct length when capturing the data.

```
  - debug: msg="{{ foo.stdout | length }}"
```

Output:

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "10"
}
```

**Comment by ghost** [comment]
Thanks @agaffney, I am also experiencing this issue and would be glad to test any proposed fixes.

**Comment by sivel** [comment]
I believe the problem is in the `copy` task.  When using `content`, the content gets placed into the built module and shipped to the remote side.  So it may be getting encoded when placed into `MODULE_COMPLEX_ARGS`

**Comment by bcoca** [comment]
# Possible Misunderstanding

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

The `content` option in `copy` and any templating has to convert into unicode as this is a jinja2 requirement. As such we don't support binary data in the templating, you can use the `src` option instead to do this:

```
- hosts: localhost
  gather_facts: no
  tasks:
  - copy:
      dest: /tmp/ansible_test/random2.file
      src: /tmp/ansible_test/random.file
```

If the file is remote, use `fetch`, doing `cat` and putting it into a results field you will avoid many data conversions.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
- https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
