### ISSUE TITLE
osx error yaml syntax [only with git or pip]

### ISSUE THREAD

**Issue by akurach** [ansible/ansible#17900]
##### ISSUE TYPE

- Bug Report
##### ANSIBLE VERSION

```
ansible 2.3.0
```
##### CONFIGURATION

```
[defaults]

remote_tmp     = .ansible/tmp
local_tmp      = .ansible/tmp
forks          = 100
poll_interval  = 15
host_key_checking = False
handler_includes_static = True
timeout = 10
deprecation_warnings=False

log_path = ansible.log
ansible_managed = Ansible managed: {file} modified by {uid} on {host}

nocows = 1
cow_selection = random
cow_whitelist=bud-frogs,bunny,cheese,daemon,default,dragon,elephant-in-snake,elephant,eyes,\
              hellokitty,kitty,luke-koala,meow,milk,moofasa,moose,ren,sheep,small,stegosaurus,\
              stimpy,supermilker,three-eyes,turkey,turtle,tux,udder,vader-koala,vader,www

retry_files_enabled = False
retry_files_save_path = .ansible-retry

[privilege_escalation]
become=True
become_method=sudo
become_user=root

#[ssh_connection]
#ssh_args = -o ControlMaster=auto -o ControlPersist=60s

[defaults]
gathering = smart
fact_caching = jsonfile
fact_caching_connection =  .ansible/fact_caching
fact_caching_timeout = 60 
```
##### OS / ENVIRONMENT

```
OSX SIERRA
```
##### SUMMARY

Can't run playbooks, it founds syntax error. 
But if I install ansible from brew, or run it on unix host everything is ok. 
Error: 

```
➜  all git:(master) ansible-playbook all.yml -i inventory/tech -l puppet.tech -vvvv
[WARNING]: log file at ansible.log is not writeable and we cannot create it, aborting

Using /Users/sundelor/git/all/ansible.cfg as config file
statically included: /Users/sundelor/git/all/roles/common/tasks/rep_mosreg.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/selinux.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/ipv6_disable.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/ntp-cron.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/ntp-ntpd.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/users-rhel.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/users-rhel.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/users-ubuntu.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/vmguest.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/git-etc.yml
statically included: /Users/sundelor/git/all/roles/common/tasks/rsyslog.yml
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/Users/sundelor/git/all/roles/common/defaults/main.yml': line 3, column 22, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
selinux_disable: "no"       # yes
                     ^ here
This one looks easy to fix.  It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote.  For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"
```
##### STEPS TO REPRODUCE

Playbook:

```
➜  all git:(master) cat all.yml

---
- hosts: all
  become_method: sudo
  become: yes

  roles:
  - common

  - role: zabbix-agent
    when: zabbix_agent == "yes"

  - role: telegraf
    when: ansible_os_family == "RedHat"

  handlers:
  - include: handlers/main.yml

- hosts: elasticsearch
  become_method: sudo
  become: yes

  roles:
  - role: elasticsearch

  handlers:
  - include: handlers/main.yml

- hosts: zabbix-proxy
  become_method: sudo
  become: yes

  roles:
  - role: zabbix-proxy

- hosts: zabbix-server
  become_method: sudo
  become: yes

  roles:
  - role: zabbix-server

  handlers:
  - include: handlers/main.yml

- hosts: nginx
  become_method: sudo
  become: yes
  roles:
  - role: nginx

  handlers:
  - include: handlers/main.yml

- hosts: memcached
  become_method: sudo
  become: yes
  roles:
  - role: memcached

  handlers:
  - include: handlers/main.yml

- hosts: php-fpm
  become_method: sudo
  become: yes
  roles:
  - role: php-fpm

  handlers:
  - include: handlers/main.yml

```

error_file

```
➜  all git:(master) cat /Users/sundelor/git/all/roles/common/defaults/main.yml
#roles/common/defaults/main.yml

---
selinux_disable: "no"       # yes
autoupdate: "no"        # yes
add_repo_mosreg: "no"       # yes
install_git_etc: "no"       # yes
users_add: "no"         # yes
replace_hostname: "no"      # yes
replace_ssh_conf: "no"      # yes
replace_hosts: "no"     # yes
rsyslog: "no"           # yes
```

##### ACTUAL RESULTS

```
nothing
```
