### ISSUE TITLE
Default ansible_managed to a static string

### ISSUE THREAD

**Issue by abadger** [ansible/ansible#17947]
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

Various templates
##### ANSIBLE VERSION

```
devel, 2.3, 2.2
```
##### SUMMARY

Using the default values of "{{ ansible_managed }}" in a template file leads to the file being changed.  This is due to the variables used in the default definition of ansible_managed:
- The date replacement leads to it being changed whenever the date of the template's source is different.
  - This can happen when playbooks are stored in git as git does not store file timestamps.  Each checkout creates files from that date.  In a multi-admin setup, it is common for the playbooks to be shared with other admins via git.
- The uid replacement leads to it being changed anytime the playbook is run from a different account.
  - Running ansible does not require a single admin account because of its integration with sudo and su.  But this portion of the string hampers that because template will report changed each time a different account is used.
- The host replacement leads it to being changed whenever the playbook is run from a different controller.
  - Ansible is useful to run playbooks from each admin's laptop or workstation rather than having a single central master.  This setting makes it so templates cannot be used idempotently in that manner.
- The file replacement leads to the file being changed whenever the file is substituted from a different path.
  - When ansible gets its playbooks from a git checkout in each admin's home directory the paths to the template file will be different.  Thus each admin will get a change in the file.
##### STEPS TO REPRODUCE

Run the following playbook twice to show the first problem with date.  Note that in the real-world, the change in timestamp would come from using a fresh git checkout or a user on another machine, not from state='touch' in the playbook:

```

---
- hosts: localhost
  gather_facts: False
  tasks:
  - file:
      path: "/var/tmp/not-idempotent.j2"
      state: "touch"
  - copy:
      content: "{{'{{ ansible_managed }}\nSome content\n'}}"
      dest: "/var/tmp/not-idempotent.j2"
  - template:
      src: "/var/tmp/not-idempotent.j2"
      dest: "/var/tmp/not-idempotent"
```

You can take out the `file:` task and run the playbook as another user or on a different control host to see the problems with uid and host respectively.
##### EXPECTED RESULTS

The second run of the playbook should show no changes for the template task.
##### ACTUAL RESULTS

The template task shows changes every single run:

```
TASK [template] ****************************************************************
changed: [localhost]
```
