### ISSUE TITLE
Support commands with multiple interactive operation in Network modules

### ISSUE THREAD

**Issue by wise0103** [ansible/ansible#17950]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

Network modules
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel f57f33a8e7) last updated 2016/08/26 06:24:44 (GMT +000)
  lib/ansible/modules/core: (detached HEAD ef84dbbddd) last updated 2016/08/26 06:24:55 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD f29efb5626) last updated 2016/08/26 06:24:58 (GMT +000)
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using Network modules to communicate with routers like CISCO ones, there are some commands with different prompt messages for different conditions or several prompt message to interact.

Now in lib/ansible/module_utils/netcli.py

```
class Cli(object):
...
        def to_command
....
             cmd = cmd['command']
         if isinstance(prompt, string_types):
             prompt = re.compile(re.escape(prompt))
```

It only supports to define prompt as a string not as a list.
##### STEPS TO REPRODUCE

```
 ios_command:
          commands:
          - command: "copy scp://{{ scp_username }}@{{ scp_server }}/{{ device_config }} {{ admin_config }} -noconfirm"
            prompt:
              - "Target file exists, overwrite"
              - "Are you sure"
              - "password:"
            response:
              - y
              - "yes"
              - "{{ scp_password }}"
          provider: "{{ admin_cli }}"
```

##### EXPECTED RESULTS

Because I find it supports prompt as a list in lib/ansible/module_utils/shell.py. I expect to define multiple prompts as the playbook shown above.

To implement it, I tried to modify the code as below:

```
--- a/lib/ansible/module_utils/netcli.py
+++ b/lib/ansible/module_utils/netcli.py
@@ -78,6 +78,11 @@ class Cli(object):
             cmd = cmd['command']
         if isinstance(prompt, string_types):
             prompt = re.compile(re.escape(prompt))
+        elif isinstance(prompt, (list, tuple)):
+            temp = []
+            for index in range(len(prompt)):
+                temp.append(re.compile(re.escape(prompt[index])))
+            prompt = temp
         return Command(command, output, prompt=prompt, response=response)
```

To support different prompt for different condition and only one prompt at all, this is enough.
But if we want to support several prompts for one command, it would be much harder. I have tried a solution as below, but I think it would be better one.

```
--- a/lib/ansible/module_utils/shell.py
+++ b/lib/ansible/module_utils/shell.py
@@ -147,10 +147,17 @@ class Shell(object):
             window = self.strip(recv.read())

             if hasattr(cmd, 'prompt') and not handled:
-                if self.handle_prompt(window, prompt=cmd.prompt, response=cmd.response):
-                    handled = True
+                prompt_matched = self.handle_prompt(window, prompt=cmd.prompt, response=cmd.response)
+                if prompt_matched:
+                    if isinstance(cmd.prompt, (list, tuple)):
+                        del cmd.response[cmd.prompt.index(prompt_matched)]
+                        del cmd.prompt[cmd.prompt.index(prompt_matched)]
+                        if cmd.prompt == []:
+                            handled = True
+                    else:
+                        handled = True
                     time.sleep(cmd.delay)
-                    if cmd.is_reboot:
+                    if cmd.is_reboot and handled:
                         return

             try:
@@ -191,7 +198,7 @@ class Shell(object):
             if match:
                 cmd = '%s\r' % ans
                 self.shell.sendall(cmd)
-                return True
+                return pr
```
##### ACTUAL RESULTS

```

```
