### ISSUE TITLE
include_role does not work with with_items

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#17966]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

include_role
##### ANSIBLE VERSION

```
2.3.0
```
##### SUMMARY

The new "include_role" task does not work with with_items
##### STEPS TO REPRODUCE

In the example playbook below, the role "myrole" is first run stand-alone, and then as a with_items loop.

```

---
- name: Do stuff to stuff
  hosts: localhost
  tasks:
    - name: set fact
      set_fact:
        thing: otherstuff
    - name: myrole
      include_role:
        name: myrole
      vars:
        thing: "asdf"
    - name: myrole
      with_items:
        - "aone"
        - "atwo"
      include_role:
        name: myrole
      vars:
        thing: "{{ item }}"
```
##### EXPECTED RESULTS

Success
##### ACTUAL RESULTS

Error part of the output

```
TASK [myrole] ******************************************************************
task path: /mnt/c/Users/trond/Documents/projects/ansibledev/rolestesting/main.yml:13
failed: [localhost] (item=aone) => {
    "failed": true,
    "item": "aone",
    "msg": "No role was specified to include"
}
failed: [localhost] (item=atwo) => {
    "failed": true,
    "item": "atwo",
    "msg": "No role was specified to include"
}
ERROR! Unexpected Exception: 'results'
```

**Comment by ansibot** [comment]
@trondhindenes: Thanks for taking the time to open this issue, but it was filed under the wrong github repository. Please create a new issue at https://github.com/ansible/ansible-modules-core/issues
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by detiber** [comment]
@bcoca was this closed in error?

**Comment by trondhindenes** [comment]
@detiber I opened it in modules-core instead.

**Comment by detiber** [comment]
@trondhindenes indeed, I posted that prior to realizing that include_role is actually implemented in ansible-modules-core. Apologies for the noise.

**Comment by bcoca** [comment]
actually its not a module but coded inside the core interpreter, sadly the bot does not realize this and takes the documentation stub in core as a sign that it is a module. bot_skip

the repo unification will make all this go away.

**Comment by trondhindenes** [comment]
closed the issue I opened in modules-core, tracking here instead

**Comment by trondhindenes** [comment]
@bcoca thanks! Looping now works, but it doesn't look like the role inside the loop is able to access the "item" dynamic var in a with_items loop. Do you want me to post some example code here, or open a new issue?

**Comment by bcoca** [comment]
already pushed 2nd part of fix that takes care of that

**Comment by detiber** [comment]
@twiest @mwoodson fyi

**Comment by trondhindenes** [comment]
sweet, thanks!

**Comment by twiest** [comment]
@detiber thanks for the heads up

**Comment by orischwartz** [comment]
Is loop variable interpolation supported in the role name? I'm seeing the following on the latest version from `devel`:

```yml
- include_role:
    name: "{{ item }}"
  with_items:
    - "x"
    - "y"
```
```
ERROR! 'item' is undefined
```
