### ISSUE TITLE
include_role - role missing in execution when included more than once

### ISSUE THREAD

**Issue by stepanstipl** [ansible/ansible#18080]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

include_role
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel d9b570aaae) last updated 2016/10/17 12:17:46 (GMT +100)
  lib/ansible/modules/core: (detached HEAD 15f8c6835b) last updated 2016/10/17 12:17:49 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 4ca8e5347a) last updated 2016/10/17 12:17:49 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

The commit 0d5206f seems to fix missing tasks after the include_role (#18026), but there's now another issue - when same role is included more than once, all the subsequent includes are ignored.
##### STEPS TO REPRODUCE

Given play:

```
- hosts: localhost
  tasks:
    - include_role:
        name: test-intermediate
```

and roles

test-intermediate:

```
- include_role:
    name: test

- include_role:
    name: test
```

and test:

```
- debug:
    msg: Test
```
##### EXPECTED RESULTS

```
Test
Test
```
##### ACTUAL RESULTS

```
Test
```

So the second include of test role is missing in execution.

@bcoca @jimi-c I've updated the original issue (#18206), but it seemed to go unnoticed and as I can't reopen I've created this one. Thanks.
