### ISSUE TITLE
WinRM: Certification error when using "delegate_to" in playbook

### ISSUE THREAD

**Issue by naphta** [ansible/ansible#18082]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`WinRM -- pywinrm`
##### ANSIBLE VERSION

`ansible 2.1.0.0`
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

`Ubuntu 14.04 w/ Python 2.7.10`
##### SUMMARY

When using `pywinrm==2.0` or higher I recieve a certification error despite `ansible_winrm_server_cert_validation=ignore` being set.

Appears to not be respecting that specific setting. This only occurs when using the "delegate_to".
##### STEPS TO REPRODUCE

```
- hosts:  localhost
  tasks:

    - set_fact:
         primary_web2: 10.0.0.2

    - name: Ensure NTFS permissions
       delegate_to: "{{ primary_web2 }}"
       win_acl:
         path: d:/websites
         user: 'Everyone'
         rights: 'FullControl'
         type: 'allow'
         state: 'present'
         inherit: 'ContainerInherit, ObjectInherit'
```
##### EXPECTED RESULTS

To set the permissions on the remote host as per the module (this applies to all windows modules, not just the one in the example)
##### ACTUAL RESULTS

```
<10.0.0.2> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 10.0.0.2
fatal: [localhost]: UNREACHABLE! =>
{
    "changed": false,
    "msg": "ssl: (\"bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)\",)",
    "unreachable": true
}
```
##### WORK AROUND

Downgrading to pywinrm==0.1.1 works absolutely fine.
