### ISSUE TITLE
Integer variables are converted to strings when referenced in other variables

### ISSUE THREAD

**Issue by zacblazic** [ansible/ansible#18095]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Variables
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

macOS Sierra (10.12)
##### SUMMARY

Variables defined as integers (without quotes) are converted to strings when using them in the definition of another variable. 
##### STEPS TO REPRODUCE

```

---
- hosts: local
  connection: local
  gather_facts: no
  vars:
    some_integer: 5
    some_other_integer: "{{ some_integer }}"
  tasks:
    - debug: var=some_integer
    - debug: var=some_other_integer
```
##### EXPECTED RESULTS

```
LAY [local] *******************************************************************

TASK [debug] *******************************************************************
ok: [local] => {
    "some_integer": 5
}

TASK [debug] *******************************************************************
ok: [local] => {
    "some_other_integer": 5
}

PLAY RECAP *********************************************************************
local                      : ok=2    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
LAY [local] *******************************************************************

TASK [debug] *******************************************************************
ok: [local] => {
    "some_integer": 5
}

TASK [debug] *******************************************************************
ok: [local] => {
    "some_other_integer": "5"
}

PLAY RECAP *********************************************************************
local                      : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by alikins** [comment]
This seems to be a bug in how the output is shown. The variables themselves dont seem to end up as string types:

``` yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    some_integer: 5
    some_other_integer: "{{ some_integer }}"
  tasks:
    - debug: var=some_integer
    - debug: var=some_other_integer
    - name: assert some_integer and some_other_integer is an int 5 and not a string "5"
      assert:
          that:
              - some_integer == 5
              - some_other_integer == 5

    - name: assert some_int is not a string
      assert:
          that:
              - some_integer != "5"
              - some_other_integer != "5"
```

```
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "some_integer": 5
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "some_other_integer": "5"
}

TASK [assert some_integer and some_other_integer is an int 5 and not a string "5"] ***
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [assert some_int is not a string] *****************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```
