### ISSUE TITLE
include_role role does not work with `when:` if condition is a string

### ISSUE THREAD

**Issue by Tahvok** [ansible/ansible#18124]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

include_role
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 4549604cc7) last updated 2016/10/20 07:57:13 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 7a7ff3ebca) last updated 2016/10/20 07:57:15 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD accb04b867) last updated 2016/10/20 07:57:15 (GMT -400)
  config file = /root/lynx/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

centos 6
##### SUMMARY

You cannot use a registered variable in 'when' statement of the include_role task.
##### STEPS TO REPRODUCE

Create a role, than second role that should be included.
In the first role create a task that will register a variable.
Then try to use that variable in a 'when' statement in the include_role task.

``` yaml

---
- name: get mysql version
  shell: mysql -V | awk '{split($5,vn,"."); print vn[1] "." vn[2]}'
  register: mysql_version
  ignore_errors: true

- debug:
    msg: "{{ mysql_version }}"
  when: mysql_version.rc == 0


- name: update mysql version in consul if needed
  include_role:
    name: consul-kv
  vars:
    consul_environment: "{{ env }}"
    consul_key: "nodes/{{ ansible_hostname }}/mysql_version"
    consul_value: "{{ mysql_version.stdout }}"
  delegate_to: localhost
  when: mysql_version.rc == 0
```
##### EXPECTED RESULTS

The include_role task will work
##### ACTUAL RESULTS

You can see that the debug task works fine with the same 'when' check, while the include_role task fails.
It also works fine without the 'when' statement. So the problem appears to be only with the 'when' statement.

```
$ ansible-playbook playbooks/getmysql.yml -e 'env=lab'

PLAY [host1] **************************************************************

TASK [setup] *******************************************************************
ok: [host1]

TASK [lynx : get mysql version] ************************************************
changed: [host1]

TASK [lynx : debug] ************************************************************
ok: [host1] => {
    "msg": {
        "changed": true, 
        "cmd": "mysql -V | awk '{split($5,vn,\".\"); print vn[1] \".\" vn[2]}'", 
        "delta": "0:00:00.037524", 
        "end": "2016-10-20 11:03:19.995857", 
        "rc": 0, 
        "start": "2016-10-20 11:03:19.958333", 
        "stderr": "", 
        "stdout": "5.5", 
        "stdout_lines": [
            "5.5"
        ], 
        "warnings": []
    }
}

TASK [consul-kv : debug] *******************************************************
fatal: [host1]: FAILED! => {"failed": true, "msg": "The conditional check 'm' failed. The error was: error while evaluating conditional (m): 'm' is undefined\n\nThe error appears to have been in '/root/lynx/roles/lynx/tasks/main.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: update mysql version in consul if needed\n  ^ here\n"}
```
