### ISSUE TITLE
The value of 'serial' in playbook cannot be set based on a variable defined per group

### ISSUE THREAD

**Issue by FlorinAndrei** [ansible/ansible#18131]
##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

playbook
##### ANSIBLE VERSION

```
ansible 1.9.4
  configured module search path = None
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Doing rolling updates with Ansible.

```
ansible-playbook -i production deploy.yml

ansible-playbook -i staging deploy.yml
```

```
$ cat deploy.yml

---
- hosts: api_frontend
  serial: 4

  pre_tasks:
    - name: "Gather EC2 facts from API nodes"
      ec2_facts:

    - name: "Remove node from ELB"
      local_action: ec2_elb
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        region: "{{ aws.region }}"
        ec2_elbs: "{{ aws_api_lb }}"
        state: "absent"

  roles:
    - { role: api-deploy }

  post_tasks:
    - name: "Add node to ELB"
      local_action: ec2_elb
      args:
        instance_id: "{{ ansible_ec2_instance_id }}"
        region: "{{ aws.region }}"
        ec2_elbs: "{{ aws_api_lb }}"
        state: "present"
        wait_timeout: 30
```

The problem is, `serial: 4` works well in production, but the value is too large for staging. In staging I'd like to use `serial: 1`.

I've tried to define a variable such as `api_deploy_serial` in places like `production/group_vars/all/vars` (and also for staging), and used that to define the value for serial in the playbook, but it does not seem to be taken into account. Seems like variables are evaluated after serial is used in the playbook.

I do not want to maintain multiple deploy playbooks, one for each environment. That playbook needs to be created once, and pull variables from various environments for various behaviors. That's how config management is supposed to work.

Having multiple playbooks, one per environment, without the ability to template the behavior in the standard way, would be like a throw back to the bad old days of shell scripts.
##### STEPS TO REPRODUCE

If I do:

```
serial: "{{ api_deploy_serial | default(1) | int }}"
```

then only the default value is used, no matter what I add to `group_vars`.

```

```

##### ACTUAL RESULTS

```

```

**Comment by krzysztof-magosa** [comment]
What would happen if two groups have conflicting value of variable for serial?

**Comment by FlorinAndrei** [comment]
What happens when two groups have conflicting values of any variable?

**Comment by bcoca** [comment]
The groups are not an issue, that each host has a different value is, as vars are flattened by host so groups have no bearing after that.

**Comment by krzysztof-magosa** [comment]
@FlorinAndrei Normally each host would have some value calculated based on precedence, but I believe value of serial must be 'global' for entire play and cannot be different for hosts within it.

For example something like that:

```
- hosts:
    - frontend
    - backend
  serial: "{{ some_variable }}"
  roles:
    - role1
    - role2
    - role3
```

And assume that `frontend` and `backend` group does not share the same hosts, and `some_variable` is set to different value for each group.

**Comment by FlorinAndrei** [comment]
I just want some way to template that variable, the way many other variables can be templated. It's a bit crazy to have to use different versions of the same playbook for different environments, only because one variable is hardcoded. I would like to be able to pull its value from somewhere, no matter how many times it could potentially be overridden.

I'm sure there are good structural reasons for the current behavior, but from the user's perspective Ansible seems a little inconsistent. Some variables can be pulled from groups. Others can't. It's difficult to know what the logic is until you actually try to see if it works. :(

**Comment by bcoca** [comment]
you can template it, you just cannot use host variables to do so

**Comment by pabelanger** [comment]
Just ran into this issue too, was trying to have Zuul dynamically do this for me via host vars.  Back to the drawing board.

**Comment by danowar2k** [comment]
I've just run into this problem. My Ansible CM is a VM with X MB RAM. Each host consumes ca. 300 MB for the tasks I'm running. So I first set serial hard to 3.

But what if I decide to give more or less RAM to my Ansible CM? So I started to create some tasks to dynamically set the amount of servers this play can do in parallel:

```
- hosts: all
  name: Store CM dependent variables
  tasks:
    - name: Check Ansible CM memory
      local_action:
        module: setup
      register: ansible_cm_facts

    - name: Set server worker count depending on Ansible CM memory
      set_fact:
        parallel_server_workers: "{{ ansible_cm_facts.ansible_facts.ansible_memtotal_mb / 300) | int }}"

- hosts: all
  name: Memory intensive play
  serial: "{{ parallel_server_bla }}"
```

Which didn't work because I can't use host variables and Control Machine variables aren't a thing that exists. So, it would be nice if I could do this at some time in the future...
