### ISSUE TITLE
Ansible 2.1.0.0 set_fact with multiline expressions adds a trailing newline

### ISSUE THREAD

**Issue by 399a36c3b7** [ansible/ansible#18142]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

filter_plugins/core
##### ANSIBLE VERSION

```
ansible-playbook 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

In ansible 2.0 setting facts with multiline expressions seems to add a trailing newline
##### STEPS TO REPRODUCE

```

```

##### ACTUAL RESULTS

```
✗ cat foo.yml 
- hosts: localhost
  gather_facts: no
  tasks:
    - set_fact:
         xxx: >
            {{ 1 == 1
            }}

    - include: "bar.yml"
      vars:
        yyy: "{{ xxx | bool }}"

✗ cat bar.yml  
- debug:
    msg: "{{ yyy }}"

✗ virtualenv-ansible1.9  
done!

✗ ansible-playbook -i /dev/null foo.yml -vvvv
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ************************************************************** 

TASK: [set_fact ] ************************************************************* 
ok: [localhost] => {"ansible_facts": {"xxx": "True"}}

TASK: [debug ] **************************************************************** 
ok: [localhost] => {
    "msg": "True"
}

PLAY RECAP ******************************************************************** 
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

✗ virtualenv-ansible2.x
done!

✗ ansible-playbook -i /dev/null foo.yml -vvvv
No config file found; using defaults
 [WARNING]: provided hosts list is empty, only localhost is available

Loaded callback default of type stdout, v2.0

PLAYBOOK: foo.yml **************************************************************
1 plays in foo.yml

PLAY [localhost] ***************************************************************

TASK [set_fact] ****************************************************************
task path: /Users/alexnovikov/Workspace/firewalkwithme/foo.yml:4
ok: [localhost] => {"ansible_facts": {"xxx": "True\n"}, "changed": false, "invocation": {"module_args": {"xxx": "True\n"}, "module_name": "set_fact"}}

TASK [include] *****************************************************************
task path: /Users/alexnovikov/Workspace/firewalkwithme/foo.yml:9
included: /Users/alexnovikov/Workspace/firewalkwithme/bar.yml for localhost

TASK [debug] *******************************************************************
task path: /Users/alexnovikov/Workspace/firewalkwithme/bar.yml:1
ok: [localhost] => {
    "msg": false
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

**Comment by alikins** [comment]
reproduced behavior with devel/  (repro case added to https://github.com/alikins/ansible-bug-repro/tree/master/newline_18142)

Though, I'm not entirely sure if that behavior is unintentional, but it seems odd.

``` yaml
[fedora-23:newline_18142 (master %)]$ cat test.yml 
- hosts: localhost
  gather_facts: no
  tasks:
      - set_fact:
          xxx: >
                {{ 1 == 1
                }}
      - debug: var=xxx
      - debug: msg="{{ xxx }}"
[fedora-23:newline_18142 (master %)]$ ansible-playbook -v test.yml 
Using /home/adrian/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [set_fact] ****************************************************************
ok: [localhost] => {"ansible_facts": {"xxx": "True\n"}, "changed": false}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "xxx": "True\n"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "True\n"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

**Comment by alikins** [comment]
more testing...

``` yaml
[fedora-23:newline_18142 (master %)]$ cat test.yml 
- hosts: localhost
  gather_facts: no
  tasks:
      - set_fact:
          xxx: >
                {{ 1 == 1
                }}
          xx: |
              {{ 1 == 1
              }}
          yyy: >
              this is some stuff on a single line
          zzz: |
              this is some stuff on a single line that would include newlines
      - debug: var=xxx
      - debug: msg="{{ xxx }}"
      - debug: msg="{{ xx }}"
      - debug: msg="{{ yyy }}"
      - debug: msg="{{ zzz }}"

[fedora-23:newline_18142 (master %)]$ ansible-playbook -v test.yml 
Using /home/adrian/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [set_fact] ****************************************************************
ok: [localhost] => {"ansible_facts": {"xx": "True\n", "xxx": "True\n", "yyy": "this is some stuff on a single line\n", "zzz": "this is some stuff on a single line that would include newlines\n"}, "changed": false}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "xxx": "True\n"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "True\n"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "True\n"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "this is some stuff on a single line\n"
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "this is some stuff on a single line that would include newlines\n"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   
```

**Comment by 399a36c3b7** [comment]
So this also has a bad interaction with the situation when you pass the result of a multiline expression into other code snippets. Namely, this change now behaves differently with the |bool filter, since it does not tolerate newly introduced trailing newlines.

**Comment by gbevan** [comment]
I'm seeing same issue of retained new-lines with local_action in ansible 2.2:

```
- name: eg local shell action
  local_action: >
    shell
      some shell command
```

fails with shell\n module not found.
Seems like > is being treated like | in the yaml.

**Comment by mikelindsey-okta** [comment]
Seeing this with 2.2.3 as well.

**Comment by andremarianiello** [comment]
I believe this behavior is correct (but unexpected) because of YAML's many different multiline string variations. Specifically, '>' preserves the newline at the end, but '>-' does not preserve it, thus using '>-' instead fixed this issue for me. You can read more about this 'block comping indicator' at http://yaml-multiline.info/.

**Comment by geerlingguy** [comment]
@andremarianiello - Thanks! I had used that trick once before but didn't remember it until I came to this issue. Changing the scalar in the task from:

```yaml
  set_fact:
    variable_being_set: >
      {{ 'something' if version == '2.4' else 'something_else' }}
```

To:

```yaml
  set_fact:
    variable_being_set: >-
      {{ 'something' if version == '2.4' else 'something_else' }}
```

Fixed the issue where a newline `\n` was being jammed into the end of the set fact.

**Comment by fatmcgav** [comment]
Hmm, I've tried the work-around suggested above (using `>-`), however it doesn't work for me... 

```
- set_fact:
    variable: >-
      {{ cmd_out.stdout_lines | select('match', '.*\\)$') | map('regex_search', '^\\w+') | list }}
```

Results in:
```
TASK [playbook : set_fact] *****************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: error: unbalanced parenthesis
fatal: [hostt]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

Any ideas?

**Comment by samdoran** [comment]
Closing per above. The solution is to use `>-`. See https://yaml-multiline.info for more information.

**Comment by samdoran** [comment]
@fatmcgav Your error is unrelated to this issue. You need to add an additional `\` to the `match()` arguments.

```yaml
- set_fact:
    variable: >-
      {{ cmd_out.stdout_lines | select('match', '.*\\\)$') | map('regex_search', '^\\w+') | list }}
```
