### ISSUE TITLE
vault encrypted variables show up in verbose output or when playbook fails

### ISSUE THREAD

**Issue by kottapar** [ansible/ansible#18184]
- Bug Report
##### COMPONENT NAME

ansible-vault
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None changed
##### OS / ENVIRONMENT

RHEL 7.2
##### SUMMARY

I've used ansible-vault to encrypt a variable file in which a password is stored. The password variable is called in a playbook. However when the playbook is run in verbose or when it fails to run the password is shown in the debug output.
This is beating the purpose of placing the password in an encrypted file.
##### STEPS TO REPRODUCE

```

---
- hosts: all
  vars_files:
    - ../config/var.yml

  tasks:
    - name: status
       command: /path/to/script/serverstatus.sh abcappserver -username wasusr -password {{ was_pwd }}
```

##### ACTUAL RESULTS

```

```

**Comment by gundalow** [comment]
Thanks for the report

http://docs.ansible.com/faq.html#how-do-i-keep-secret-data-in-my-playbook

I don't believe Ansible keeps track of what came from the vault. To protect the data you can use `no_log: true`

``` yaml
 tasks:
    - name: status
       command: /path/to/script/serverstatus.sh abcappserver -username wasusr -password {{ was_pwd }}
      no_log: true
```

I'll raise an issue to update http://docs.ansible.com/ansible/playbooks_vault.html where it should also be documented
