### ISSUE TITLE
ansible_distribution_major_version missing on Solaris

### ISSUE THREAD

**Issue by photoninger** [ansible/ansible#18197]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

setup module (facts.py)
##### ANSIBLE VERSION

```
ansible 2.2.0.0 (detached HEAD eafb4043c9) last updated 2016/10/26 09:57:34 (GMT +200)
  lib/ansible/modules/core: (detached HEAD c51ced56cc) last updated 2016/10/26 09:56:37 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 8ffe314ea5) last updated 2016/10/26 09:56:37 (GMT +200)

ansible v2.2.0.0-0.3.rc3
```
##### OS / ENVIRONMENT

running on MacOS 10.12.1 
managing "Solaris 10 10/09 s10s_u8wos_08a SPARC"
##### SUMMARY

We are using 
`group_by: key={{ ansible_os_family }}-{{ ansible_distribution_major_version }}`
in our playbooks to include group_vars based on distro and major_version. Playbooks are used for Solaris, RHEL, SLES, and Debian at the same time.
With ansible-2.1.2 on Solaris we get `"ansible_distribution_major_version": "NA"` and therefore our grouping is working.
With ansible-2.2.0.0-0.3.rc3 "ansible_distribution_major_version" is missing an Solaris hosts and breaks grouping.
##### STEPS TO REPRODUCE

Run ansible-playbook with following playbook:

```
- hosts:
  - solaris-host
  - linux-host
  pre_tasks:
        - name: group by os-version
          group_by: key={{ ansible_os_family }}-{{ ansible_distribution_major_version }}
          changed_when: False
          tags: always

```
##### EXPECTED RESULTS

group_by pre_task still works for all OS
##### ACTUAL RESULTS

```
fatal: [solaris-host]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible_distribution_major_version' is undefined
```

For backwards compatibility  `"ansible_distribution_major_version": "NA"` should be reported for Solaris. 
Or it should get the real number (9,10,11).
