### ISSUE TITLE
How to loop over hashes having an undefined number of sub-elements?

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#18202]
##### ISSUE TYPE
- Documentation Report
##### COMPONENT NAME

all
##### ANSIBLE VERSION

```
ansible 2.2.0 rc2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- host: Ubuntu 16.10 4.8.0
##### SUMMARY

This is a tricky question which I have been unable to solve so far despîte multiple attempts, maybe it is not feasible with Ansible.
I have already asked the same question in [Ansible's Google group](https://groups.google.com/forum/#!topic/ansible-project/lBOynqt0NBE), but there has been no answer.
I can't tell for sure whether this is a:
- lack of skill on my part 
- or a bug report
- or a feature Idea because it may be impossible to perform with latest ansible
##### STEPS TO REPRODUCE

I pull some facts from a networking device, some of them end up in
{{ facts.ansible_facts.ansible_net_neighbors }}:

```
"ansible_net_neighbors": {
        "Gi0/0": [
            {
                "host": "IOSv_L2_10.actionmystique.net",
                "port": "Gi0/1"
            }
        ],
        "Gi0/3": [
            {
                "host": "IOSv_Leaf_13.actionmystique.net",
                "port": "Gi0/1.10"
            },
            {
                "host": "IOSv_Leaf_13.actionmystique.net",
                "port": "Gi0/1.20"
            },
            {
                "host": "IOSv_Leaf_13.actionmystique.net",
                "port": "Gi0/1"
            }
        ],
        "Gi0/4": [
            {
                "host": "IOSv_Leaf_14.actionmystique.net",
                "port": "Gi0/1"
            },
            {
                "host": "IOSv_Leaf_14.actionmystique.net",
                "port": "Gi0/1.20"
            },
            {
                "host": "IOSv_Leaf_14.actionmystique.net",
                "port": "Gi0/1.10"
            }
        ],
...
```

The number & names of ansible_net_neighbors sub-elements "Gin/p" (which stand for GigabitEthernet n/p) are dynamic: we have no clue in advance what they'll be.
Same characteristic for the number of host/port duo(s) inside each "Gin/p"

So, how can I loop over all those sub-elements? The tricky part for me is the fact that **there is no name for the field "Gin/p"**.
I have unsuccessfully tried the following for instance:

```
- name: Updating the description of all interfaces
  ios_config:
        provider: "{{ connections.ssh }}"
        parents: 
          - "interface {{ item }}"
        lines:
          - "description Connected to {{ item.host }} on its port {{ item.port }}"
  with_dict: "{{ facts.ansible_facts.ansible_net_neighbors }}"
```

Any ingenious trick in mind?
