### ISSUE TITLE
Callback only reports module_name for copy when force argument is set to no

### ISSUE THREAD

**Issue by justingood** [ansible/ansible#18232]
##### Issue Type:
- Bug Report
##### Ansible Version:

```
ansible 2.1.2.0
  config file = ansible.cfg
  configured module search path = None
```
##### Ansible Configuration:

```
[defaults]
hostfile     = ./hosts
callback_plugins = ./callback_plugins
callback_whitelist = callback
```
##### OS / ENVIRONMENT

N/A
##### COMPONENT NAME
Callbacks

##### Summary:

Callback only reports `module_name` for _copy_ when `force` argument is set to _no_
##### Steps To Reproduce:

hosts/local:

```
localhost ansible_connection=local
```

test_playbook.yml:

```
- name: test ansible callback for the copy module
  hosts: localhost
  gather_facts: no
  tasks:
  - name: copy initial
    copy:
      content: "testing"
      dest: "/tmp/test"

  - name: copy with force (module default)
    copy:
      content: "testing"
      dest: "/tmp/test"

  - name: copy without force
    copy:
      content: "testing"
      dest: "/tmp/test"
      force: no
```

callback.py:

```
from ansible.plugins.callback import CallbackBase

class CallbackModule(CallbackBase):

    def v2_runner_on_ok(self, result):
        try:
            print 'module name is %s' % str(result._result['invocation']['module_name'])
        except Exception as e:
            print 'Unable to print: %s' % str(e)
```
##### Expected Results:

```
# ansible-playbook test_playbook.yml

PLAY [test ansible callback for the copy module] *******************************

TASK [copy initial] ************************************************************
ok: [localhost]
module name is copy

TASK [copy with force (module default)] ****************************************
ok: [localhost]
module name is copy

TASK [copy without force] ******************************************************
ok: [localhost]
module name is copy

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
##### Actual Results:

Executing the playbook results in the following:

```
PLAY [test ansible callback for the copy module] *******************************

TASK [copy initial] ************************************************************
ok: [localhost]
Unable to print: 'module_name'

TASK [copy with force (module default)] ****************************************
ok: [localhost]
Unable to print: 'module_name'

TASK [copy without force] ******************************************************
ok: [localhost]
module name is copy

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
