### ISSUE TITLE
Ansible hangs on setup

### ISSUE THREAD

**Issue by em429** [ansible/ansible#18239]
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

setup
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Running it from OS X, on AWS Ubuntu 14.04 instances. It used to work, and the playbook still works on other AWS Ubuntu 14.04 instances. 
##### SUMMARY

I run this command:
`ansible-playbook site.yml -i hosts --private-key ~/.ssh/webserver.pem`
and it hangs on task 'setup'. It worked, then it suddenly stopped working... I didn't do anything that I think would be related, apache config changes, and copied some files between folders. The strange thing is I'm doing this on two hosts, and I didn't make any changes on the second, apart from sshing into it with a newly added user once. And it doesn't work on either one. 

```

---
# Deploys an apache php5 stack with users

- name: install apache
  hosts: webservers
  remote_user: ubuntu 
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - apache

- name: install php5
  hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  vars_files:
    - vars/main.yml
  roles:
    - php

- name: add users
  hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - sshusers

- name: additional packages
  hosts: webservers
  remote_user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - apt-get
```
#### part of the trace

https://gist.github.com/hajzso/704d3cecd87b9f050efd5bc8835f2ac1
##### EXPECTED RESULTS

Configuration succeeds
##### ACTUAL RESULTS

```
statically included: /Users/hajzso/ansible/provisioning-kits/apache_php_psql-EFS/roles/php/tasks/../../silpion.lib/tasks/os-specific-vars.yml
statically included: /Users/hajzso/ansible/provisioning-kits/apache_php_psql-EFS/roles/php/tasks/Ubuntu.yml

PLAY [install apache] **********************************************************

TASK [setup] *******************************************************************
```
