### ISSUE TITLE
Variables always evaluating inside conditional block when in loop

### ISSUE THREAD

**Issue by diego-treitos** [ansible/ansible#18292]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Loop

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/ans/.ansible.cfg
  configured module search path = ['/home/ans/ansible/library/']
```

##### OS / ENVIRONMENT
Debian Jessie amd64

##### SUMMARY
Variables inside loops are always evaluated even if they are in conditional blocks that should not be executed.
For example, this playbook would work in 2.1 but it does not in 2.2:
```yaml
- hosts: anstest

  tasks:
  - name: Check if we need to enter in the block
    command: grep "" /etc/hostname
    register: test_grep
    check_mode: false
    failed_when: "'grep' in test_grep.stderr"
    changed_when: test_grep.rc != 0


  - block:

    - name: Generate variable
      command: echo "$RANDOM"
      register: a

    - name: Store using facts
      set_fact:
        mytestfact: "{{ a.stdout }}"

    - name: Not failing 1
      command: echo '{{ mytestfact }}'

    - name: Not failing 2
      command: echo '{{ mytestfact }}'

    # Configure phpmyadmina
    - name: Failing
      command: echo '{{ item.value }}'
      with_items:
        - name: 'test'
          value: 'test'
        - name: '{{ mytestfact }}'
          value: '{{ mytestfact }}'
    
    when: test_grep.rc != 0
```

##### STEPS TO REPRODUCE
Exec the above playbook

##### EXPECTED RESULTS
No errors in any variable evaluation inside the block that is not being executed.

##### ACTUAL RESULTS
```
TASK [Failing] *****************************************************************
fatal: [anstest]: FAILED! => {"failed": true, "msg": "'mytestfact' is undefined"}
```
