### ISSUE TITLE
playbook_dir changes leak outside of include

### ISSUE THREAD

**Issue by m-messiah** [ansible/ansible#18299]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

playbook_dir variable

##### ANSIBLE VERSION

```
2.1.0.0
```

##### CONFIGURATION

Nope

##### OS / ENVIRONMENT

N/A

##### SUMMARY

playbook_dir may be changed inside the playbook.

##### STEPS TO REPRODUCE

~/Sources/ansible-roles/postgres.yml
~/Sources/ansible-roles/nginx.yml
~/Sources/web/playbooks/bootstrap.yml
```

---
- name: Install common
  hosts: all
  roles:
    - common
- include: "{{ playbook_dir }}/../../ansible-roles/postgres.yml"
- include: "{{ playbook_dir }}/../../ansible-roles/nginx.yml"
```

##### EXPECTED RESULTS

In that playbook, I assume, that playbook_dir in bootstrap.yml would point to `~/Sources/web/` all the time, and Both playbooks would be successfully included.

##### ACTUAL RESULTS

Actually, ansible shows error - nginx.yml not found, because playbook_dir overrided after include.

```
ERROR! the file_name '~/ansible-roles/nginx.yml' does not exist, or is not readable
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
