### ISSUE TITLE
setting vars  does not work on playbook include

### ISSUE THREAD

**Issue by jimmymccrory** [ansible/ansible#18294]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Include file variables

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/library']
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

A role name provided as a variable to an included playbook is not executed as expected.

###### init_play.yml
```

---
- include: play.yml
  vars:
    included_role_name: any_role
```
###### play.yml
```

---
 - hosts: localhost
   connection: local
   gather_facts: no
   roles:
    - role: "{{ included_role_name }}"
```
``ansible-playbook init_play.yml``

##### EXPECTED RESULTS

The role provided by the ``included_role_name`` var is executed.

##### ACTUAL RESULTS

```
ERROR! 'included_role_name' is undefined
```
