### ISSUE TITLE
Unquoted three digit file mode (mode=xxx) sets strange mode

### ISSUE THREAD

**Issue by edrozenberg** [ansible/ansible#18321]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core module 'file' (and maybe others are affected)

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
MacOS Sierra to MacOS Sierra (same machine, local connection)

##### SUMMARY
Setting a file module mode using for example 'mode=755' sets a very different mode

##### STEPS TO REPRODUCE
```
- name: ensure permissions on homebrew prefix dir
  file:
    path:  "/usr/local"
    owner: "{{ ansible_user_id }}"
    group: wheel
    mode:  755
    state: directory
  become: yes
  become_method: sudo
```

Weirdly this gives /usr/local the following mode, which appears equivalent to 1362:
```
d-wxrw--wt    15 myuser  wheel   510B Sep 20 12:18 local
```

##### EXPECTED RESULTS
Should set mode to 0755

##### ACTUAL RESULTS
Sets mode to 1362

To fix the problem, either of the following work fine:
 ```mode:  0755```
 ```mode:  '755'```

I know it's always recommended to use 4 digit modes, but I didn't expect the behavior with 3 unquoted digits, and believe it's a change from earlier behavior of Ansible (older versions).
