### ISSUE TITLE
using lineinfile or replace module to set a line ends with backslash

### ISSUE THREAD

**Issue by mootezbessifi** [ansible/ansible#18331]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
 2.1.1.0
```

##### OS / ENVIRONMENT

CentOS 7
##### STEPS TO REPRODUCE

i am trying to modify the following docker.service file:
[Unit]
Description=Docker Application Container Engine
Documentation=http://docs.docker.com
After=network.target rhel-push-plugin.socket
Wants=docker-storage-setup.service

[Service]
EnvironmentFile=/run/flannel/subnet.env
Type=notify
NotifyAccess=all
EnvironmentFile=-/etc/sysconfig/docker
EnvironmentFile=-/etc/sysconfig/docker-storage
EnvironmentFile=-/etc/sysconfig/docker-network
Environment=GOTRACEBACK=crash
ExecStart=/bin/sh -c 'exec -a docker /usr/bin/docker-current daemon \\
                               --exec-opt native.cgroupdriver=systemd \\
                                $OPTIONS \\
                                $DOCKER_STORAGE_OPTIONS \\
                                $DOCKER_NETWORK_OPTIONS \\
                                $ADD_REGISTRY \\
                                $BLOCK_REGISTRY \\
                                $INSECURE_REGISTRY'

LimitNOFILE=1048576
LimitNPROC=1048576
LimitCORE=infinity
TimeoutStartSec=0
MountFlags=slave
Restart=on-abnormal

[Install]
WantedBy=multi-user.target

i used the next task to modify the line that contains $OPTIONS (see above)
```
  - name: add options
    lineinfile:
      dest=/root/regexptest
      regexp='^\s+\$OPTIONS'
      line="          $OPTIONS --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} \"
```

##### EXPECTED RESULTS

if i did not set a white space between backslash '\' and double quotes ", an error happens because \ escape ". If i add a white space. it will appears into the config file which causes a service down. invalid docker.service file.
i want to add a backslash to the end of the new inserted line without making trouble.
PS: i tried \\ and many other things but nothing works correctly.
i even looked for https://github.com/ansible/ansible/issues/10464 and i tired this workaround https://github.com/ansible/ansible/issues/10464#issuecomment-133116051
but it does not work with me (ansible version problem).
 
##### ACTUAL RESULTS

```

```

**Comment by abadger** [comment]
If you use a yaml dict, this should work.  Your current example uses a yaml multi-line string.  Instead write it like this:
```
  - name: add options
    lineinfile:
      dest: /root/regexptest
      regexp: '^\s+\$OPTIONS'
      line: '          $OPTIONS --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU} \'
```

Here's what I just wrote in #10464 which explains a little more about this and a cornercase with yaml double quotes vs single quotes:

There's a variety of workarounds for this including the ones posted in comments above and using the extra space at the end but running it through jinja2's trim filter:
```
  - lineinfile: 'dest=/var/tmp/dest line="{{ \"conti nued\\ \" |trim }}" create=True'
```

However, the supported way to do this in Ansible-2.x is to use yaml dicts:
```
  - lineinfile:
      dest: /var/tmp/dest
     # Single quotes in yaml do not need to escape the backslash
      line: 'an other\'
      create: True
  - lineinfile:
      dest: /var/tmp/dest
     # double quotes in yaml do need to escape the backslash
      line: "final ly\\"
      create: True
```

k=v parsing has cornercases like this that will always make it inferior to yaml dicts when there is a need for escaping or complex quoting.

Since yaml dict format works and there are several workarounds if someone feels they must use k=v I'll close this ticket.

If you need more help on this, I'll paste the mailing list and irc information below:

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
