### ISSUE TITLE
Git module does not work via http proxy

### ISSUE THREAD

**Issue by linlinas** [ansible/ansible#18333]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- git module

##### ANSIBLE VERSION

```
- ansible 2.1.2.0

```

##### OS / ENVIRONMENT
 Suse 12

##### SUMMARY

Git module does not work via http proxy

##### STEPS TO REPRODUCE

Connection which is initialized on the remote host, does not include proxy and is going straight to destination IP vi default gateway.

Example task
```
- name: git reset
   environment:
      http_proxy: 'http://x.x.x.x:3128'
      https_proxy: 'http://x.x.x.x:3128'
   git:
      repo: https://bitbucket.org/account/myproject.git
      dest: /tmp
      update: yes
      force: yes
```
Ended with Connection timed error
```
fatal: [remote.local]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "invocation": {"module_args": {"accept_hostkey": false, "bare": false, "clone": true, "depth": null, "dest": "/tmp", "executable": null, "force": true, "key_file": null, "recursive": true, "reference": null, "refspec": null, "remote": "origin", "repo": "https://bitbucket.org/account/myproject.git", "ssh_opts": null, "track_submodules": false, "update": true, "verify_commit": false, "version": "HEAD"}, "module_name": "git"}, "msg": "fatal: unable to access 'https://bitbucket.org/account/myproject.git/': Failed to connect to bitbucket.org port 443: Connection timed out", "rc": 128, "stderr": "fatal: unable to access 'https://bitbucket.org/account/myproject.git/': Failed to connect to bitbucket.org port 443: Connection timed out\n", "stdout": "", "stdout_lines": []}
```
Tcpdump on a remote machine shows
,,,
12:10:26.074852 IP remote.local.44928 > bitbucket.org.https: Flags [S], seq 2674356411, win 29200, options [mss 1460,sackOK,TS val 1447144044 ecr 0,nop,wscale 7], length 0
12:10:42.090905 IP remote.local.44928 > bitbucket.org.https: Flags [S], seq 2674356411, win 29200, options [mss 1460,sackOK,TS val 1447148048 ecr 0,nop,wscale 7], length 0
12:11:14.154911 IP remote.local.44928 > bitbucket.org.https: Flags [S], seq 2674356411, win 29200, options [mss 1460,sackOK,TS val 1447156064 ecr 0,nop,wscale 7], length 0
,,,

##### EXPECTED RESULTS

git module should initialize connection on the remote host via proxy server to connect to remote repository.
