### ISSUE TITLE
If you specify localhost and 127.0.0.1 in different groups, variable not passed from one task to another.

### ISSUE THREAD

**Issue by Denis-Mak** [ansible/ansible#18356]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Task

##### ANSIBLE VERSION
2.2.0.0

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
CentOS  3.10.0-327.36.1.el7.x86_64

##### SUMMARY
If you specify localhost and 127.0.0.1 in different groups, variable not passed from one task to another.

##### STEPS TO REPRODUCE
File: /src/ansible-bug/environments/vars/hosts
```
[any-other-host]
localhost

[test-vars-host]
127.0.0.1
```

File: /src/ansible-bug/roles/test_vars/tasks/main.yml
```
- command: echo 1
  register: my_var

- debug: var=my_var verbosity=2
```

File: /src/ansible-bug/test_vars.yml
```
- hosts: test-vars-host
  connection: local
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - test_vars
```

Run command:
` ansible-playbook -vvv /src/ansible-bug/test_vars.yml -i /src/ansible-bug/environments/vars/`

##### EXPECTED RESULTS
Echo my_var value. You can see it if you change 'test-vars-host' to 'localhost' or 'any-other-host' to '127.0.0.1'

##### ACTUAL RESULTS
```
ok: [localhost] => {
    "my_var": "VARIABLE IS NOT DEFINED!"
}

```
