### ISSUE TITLE
includes wrapped in a block statement drop environment variables

### ISSUE THREAD

**Issue by iamfletch** [ansible/ansible#18392]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
block
include
environment

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Base ansible config

##### OS / ENVIRONMENT
N/A

##### SUMMARY
environment variables do not seem to carry when using includes inside a block

##### STEPS TO REPRODUCE

env.yml
```

---

- hosts: localhost
  connection: local
  vars:
    env:
      test: 123456
  tasks:
    - shell: env
      environment: "{{ env }}"
    - block:
      - shell: env
      environment: "{{ env }}"
    - block:
      - include: env_inc.yml
      environment: "{{ env }}"
```
env_inc.yml
```

---

- shell: env
```

##### EXPECTED RESULTS

```
#ansible-playbook env.yml -vvvv | grep -e '"test=123456"' -e '"cmd": "env"'
 [WARNING]: Host file not found: /etc/ansible/hosts
 [WARNING]: provided hosts list is empty, only localhost is available
    "cmd": "env", 
        "test=123456", 
    "cmd": "env", 
        "test=123456", 
    "cmd": "env", 
        "test=123456", 
```
##### ACTUAL RESULTS
```
ansible-playbook env.yml -vvvv | grep -e '"test=123456"' -e '"cmd": "env"'
 [WARNING]: Host file not found: /etc/ansible/hosts
 [WARNING]: provided hosts list is empty, only localhost is available
    "cmd": "env", 
        "test=123456", 
    "cmd": "env", 
        "test=123456", 
    "cmd": "env", 
```
