### ISSUE TITLE
Slot-based (Pogo-style) Strategy

### ISSUE THREAD

**Issue by michaelansel** [ansible/ansible#18390]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
New strategy: slot-based free

##### ANSIBLE VERSION
N/A (but would only work for 2.0+ where strategies exist)

##### CONFIGURATION
N/A: new feature

##### OS / ENVIRONMENT
N/A: new feature

##### SUMMARY
I would like to propose (and develop) a new strategy that follows the same model as Yahoo!'s Pogo tool: https://github.com/ytoolshed/pogo/wiki/Concepts#dispatching-commands

The goal of Pogo is to allow you to do "perfect" rolling updates in which you disable a set of hosts for maintenance, and each time a host finishes, you dispatch the next one. While the `serial` argument accomplishes a similar goal, slot-based rolling is muuuch faster when tasks take varying amounts of time. To exemplify this pain:

We have 10 hosts and we want to execute on only 50% at a time. In the serial model, we would disable the first 50% and wait for them all to complete before executing the second 50%. Now imagine we have two hosts (one in each batch) that take considerably longer to execute (say, 10x as long). In the serial model, we would take the 10x time in the first batch and then the 10x time again in the second batch. In the slot-based strategy, you would only take the 10x time (plus however long it took to get to the second host), because you could start on the second slow host before the first had finished.

Looking through the code, I _think_ the best way to implement this is as a strategy and not try to reuse the serial batching logic. However, I'm an Ansible-core noob and would love feedback from the developers on two things:

1. Is this something that you would be interested in reviewing and merging? Does it make sense as part of the Ansible ecosystem?
2. Is a strategy the right way to implement this? Can you see any major pitfalls to building this as a self-contained strategy plugin?

If you keep reading around in Pogo, they also support "global pools" in which multiple executions coordinate slot usage. While interesting, I don't plan on implementing this initially (and potentially ever).

##### STEPS TO REPRODUCE
`hosts.ini`
```
[web]
# fast drainer (1m)
web1
# slow drainer (10m)
web2
# fast drainer (1m)
web3
# slow drainer (10m)
web4
```

`upgrade.yml`
```

---
- name: safely do a rolling maintenance
  hosts: all
  strategy: slots
  slots: 50%
  tasks:
  - name: disable
    # (however you do that)
  - name: wait for traffic to drain
    wait_for:
      host: 0.0.0.0
      port: 80
      state: drained
      timeout: 1800
  - name: upgrade httpd
    package: name=httpd state=latest
  - name: restart httpd
    service: name=httpd state=restarted
  - name: healthcheck
    uri: "url=http://{{ ansible_nodename }}"
  - name: enable
    # (however you do that)
```

```
ansible-playbook -i hosts.ini upgrade.yml
```

##### EXPECTED RESULTS

1. start 50% of hosts
  * disable `web1`
  * disable `web2`
  * wait_for `web1`
  * wait_for `web2`
2. move on when a host finishes draining (similar to free strategy)
  * upgrade, restart, healthcheck, enable `web1`
3. slot free, fill it with the next host
  * disable `web3`
  * wait_for `web3`
4. move on when a host finishes draining
  * upgrade, restart, healthcheck, enable `web3`
5. slot free, fill it with the next host
  * disable `web4`
  * wait_for `web4`
6. move on when a host finishes draining
  * upgrade, restart, healthcheck, enable `web1`
  * upgrade, restart, healthcheck, enable `web4`

Total execution time:
```
drain_time(web2) + drain_time(web3) + drain_time(web4) = 1 + 1 + 10 = 12
```

For comparison, in the `serial` case, the total execution time would have been:
```
drain_time(web1) + drain_time(web4) = 10 + 10 = 20
```

##### ACTUAL RESULTS
N/A: new feature

**Comment by michaelansel** [comment]
One place where I do see a potential issue is in playbook retries. If the playbook fails and you use the *.retry file to run again, percentage math would be broken. The user-side fix for this is to specify a number of slots instead of a percentage when doing retries (basically the same as you would have to do in the serial model).

**Comment by alikins** [comment]
bot_skip

**Comment by bcoca** [comment]
doesn't the free strategy + serial do this already?

**Comment by michaelansel** [comment]
No, in free+serial, you still have the problematic batching behavior. Example:

Batch 1:

```
web1 # 10m drain time
web2 # 1m drain time
```

Batch 2:

```
web3 # 1m drain time
web4 # 10m drain time
```

In the free+serial strategy, `web2` will run all tasks to completion, but Ansible won't advance to Batch 2 until `web1` has also completed all tasks, which means we can't start the `web4` drain until after `web1` has completed instead of doing both long drains in parallel.

I can put together a better timing diagram if the difference is still unclear.

**Comment by bcoca** [comment]
OK, so this is just the behavior of free + forks, ignoring serial

**Comment by michaelansel** [comment]
Isn't task dispatch managed at the global level, not the fork level? I'm not sure I fully understand your comment.

**Comment by bcoca** [comment]
forks == number of concurrent hosts processed
serial == subset of hosts to run play for, per batch (default 100%)

So free + forks = numofhosts/2 would give you your 50% hosts in play, as soon as one host finishes another one will start.

**Comment by michaelansel** [comment]
Ohh, interesting. Is forks the number of concurrent hosts or the number of concurrent tasks? If hosts, then we are golden. If tasks, then there is nothing preventing you from doing 50% of the disable tasks, another 50% of the disable tasks, and then your entire site going down... 😭 

Doing some quick testing, it looks like it is task-based parallelism, not host-based.

`hosts.ini` is just `host1`...etc. with `ansible_host=127.0.0.1`

`fork-test.yml`

```
---
- hosts: all
  strategy: free
  tasks:
  - name: directory
    file:
      path: /tmp/fork-test
      state: directory
  - name: task1
    shell: sh -c "touch /tmp/fork-test/$(date +%s)-{{ inventory_hostname }}-task1 && sleep 10"
  - name: task2
    shell: sh -c "touch /tmp/fork-test/$(date +%s)-{{ inventory_hostname }}-task2 && sleep 10"
  - name: task3
    shell: sh -c "touch /tmp/fork-test/$(date +%s)-{{ inventory_hostname }}-task3 && sleep 10"
```

```
ansible-playbook -i hosts.ini --forks 5 fork-test.yml
```

Result:

```
1478557803-host1-task1
1478557804-host2-task1
1478557804-host4-task1
1478557805-host5-task1
1478557808-host3-task1
1478557814-host6-task1
1478557816-host1-task2
1478557817-host2-task2
1478557817-host4-task2
1478557819-host7-task1
1478557825-host3-task2
1478557827-host5-task2
1478557829-host8-task1
1478557829-host9-task1
1478557831-host1-task3
1478557836-host2-task3
1478557838-host4-task3
1478557840-host3-task3
1478557840-host6-task2
1478557842-host5-task3
1478557848-host7-task2
1478557850-host8-task2
1478557852-host6-task3
1478557852-host9-task2
1478557859-host7-task3
1478557861-host8-task3
1478557863-host9-task3
```

From this example, you can see that if those tasks corresponded to `disable`, `reboot`, `enable`, we would have disabled every host before enabling a single one (not guaranteed, but this example shows it nicely).
