### ISSUE TITLE
support for naming plays

### ISSUE THREAD

**Issue by leucos** [ansible/ansible#184]
Plays could be optionally named for clarity, e.g. :

```
play: foo
 - host: whatever
 ...
```

**Comment by mpdehaan** [comment]
+1

actually, it would just be this:

```
- name: foo
  hosts: whatever
  tasks:
     ...
```

And we'd show the name in output if it was there instead of the host specification
