### ISSUE TITLE
docker_container cannot download image with any tag, when tag not a "latest"

### ISSUE THREAD

**Issue by westsouthnight** [ansible/ansible#18425]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.1.1.0
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

1) MacOS X Ansible Native
2) Docker Containered Ansible

##### SUMMARY
When we use docker_container with tag and tag not a latest module fails with 

``` Error creating container: 404 Client Error: Not Found (\"No such image: company/image:0.1\")" ```

##### STEPS TO REPRODUCE

Add to you param "image" of docker_container section custom tag, and this tag not a "latest"

Before:

```
- name: Create a service Docker container {{ ansible_environment }}-{{ inventory_hostname }}
  become: true
  docker_container:
      name: service-{{ ansible_environment }}-{{ inventory_hostname }}
      image: company/service:latest
      command: service /usr/local/share/service/service.lua
      restart_policy: always
      volumes:
        - "{{ service_directories.service_mnt_path_data }}:/var/lib/service"
        - "{{ service_directories.service_mnt_new_data_schema_data }}:/usr/local/share/service/"
      detach: True
      state: started

```

After:

```
- name: Create a service Docker container {{ ansible_environment }}-{{ inventory_hostname }}
  become: true
  docker_container:
      name: service-{{ ansible_environment }}-{{ inventory_hostname }}
      image: company/service:0.1
      command: service /usr/local/share/service/service.lua
      restart_policy: always
      volumes:
        - "{{ service_directories.service_mnt_path_data }}:/var/lib/service"
        - "{{ service_directories.service_mnt_new_data_schema_data }}:/usr/local/share/service/"
      detach: True
      state: started

```

We test that, and if do a docker_image task before, with tag, and this works, but i cannot understand why image download by tag not work in docker_container section.

And, of course, if we do ``` docker pull company/service:0.1 ``` - woks fine, - image really exists on hub.docker.com and available. 

##### EXPECTED RESULTS

Ansible docker_container module download docker image with tag and start container

##### ACTUAL RESULTS

```
fatal: [stand-1-test-1.domain.com]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating container: 404 Client Error: Not Found (\"No such image: company/service:0.1\")"}
```
