### ISSUE TITLE
first_found lookup path differs from with_first_found

### ISSUE THREAD

**Issue by marcinhlybin** [ansible/ansible#18430]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
first_found lookup

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
Defaults

##### OS / ENVIRONMENT
Debian Jessie 64 GNU/Linux

##### SUMMARY

The `first_found` lookup requires different path than `with_first_found` when looking for the same file. For testing I use template module with `lookup('first_found')` used in `src` and `with_first_found` loop.

```
Excerpt from first task:
  src: "{{ item }}"
  with_first_found:
    - files: user/user.conf.j2

Exceprt from second task:
  src: "{{ lookup('first_found', ['user/user.conf.j2']) }}"
```

It works in Ansible 2.1. For Ansible 2.2 second task requires path change to `../templates/user/user.conf.j2`. My guess is that it looks for the file in current directory i.e. `tasks/` not in `templates/`.

I am reporting this as bug because it worked in previous version of Ansible but it might be intentional.

##### STEPS TO REPRODUCE

playbook.yml:
```

---
- hosts: localhost
  roles:
    - test-role
```

test-role:

tasks/main.yml:
```

---
- name: Copy user.conf file using with_first_found
  template:
     src: "{{ item }}"
     dest: /tmp/user.conf
  with_first_found:
    - files: user/user.conf.j2

- name: Copy user.conf using first_found
  template:
    src: "{{ lookup('first_found', ['user/user.conf.j2']) }}"
    dest: /tmp/user.conf
```

templates/user/user.conf.j2:
```
# user.conf file
```

##### EXPECTED RESULTS
Works in Ansible 2.1:

```
PLAY [localhost] ***************************************************************

TASK [test-role : Copy user.conf file with_first_found] ************************
ok: [localhost] => (item=/home/ansible/roles/test-role/templates/user/user.conf.j2)

TASK [test-role : Copy user.conf file first_found] *****************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS
In Ansible 2.2 path in second task requires change to `../templates/user/user.conf.j2`.

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [test-role : Copy user.conf file with_first_found] ************************
ok: [localhost] => (item=/home/ansible/roles/test-role/templates/user/user.conf.j2)

TASK [test-role : Copy user.conf file first_found] *****************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found"}

msg: No file was found when using with_first_found. Use the 'skip: true' option to allow this task to be skipped if no files are found

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment]
when used in 'with_' the first found lookup gets passed a 'paths' of template/vars/files(default) depending on the task. So a template task will default to using 'template/' as a path, include_vars will use 'vars/' instead.

**Comment by tterranigma** [comment]
How will the new loop syntax work with this? For instance:

```yaml
 - include_vars: "{{ item }}"                                                      
   loop: "{{ lookup('first_found', var_files) }}"                                  
   vars:                                                                           
     var_files:                                                                    
       - "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}.yml" 
       - "{{ ansible_distribution }}.yml"                                          
       - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"    
       - "{{ ansible_os_family }}.yml"                                             
       - default.yml                                                               
```

will fail, while `with_first_item would succeed. Am I missing something?
