### ISSUE TITLE
ansible don't skip task when iterating over jinja2 filtered list

### ISSUE THREAD

**Issue by yamb00** [ansible/ansible#18447]
##### ISSUE TYPE
 - Bug Report
##### ANSIBLE VERSION
```
ansible 2.2.0.0

```
##### OS / ENVIRONMENT
ubuntu 16.04
##### STEPS TO REPRODUCE
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [find] ********************************************************************
skipping: [localhost]

TASK [command] *****************************************************************
skipping: [localhost] => (item=list_bin.files) 

TASK [command] *****************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'files'"}

```
- hosts: localhost
  connection: local
  vars:
    run_task: "no"
  tasks:
    - find:
        path="/usr/bin"
      register: list_bin
      when: run_task == "yes"

    - command: "echo {{ item }}"
      with_items: list_bin.files
      when: run_task == "yes"
    
    - command: "echo {{ item }}"
      with_items: '{{ list_bin.files | map(attribute="path") | list }}'
      when: run_task == "yes"
```
