### ISSUE TITLE
fatal: [node1]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'Core'"}

### ISSUE THREAD

**Issue by gaurav-dalvi** [ansible/ansible#18475]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
NA

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/admin/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
centos 7.2

##### SUMMARY
Earlier till version 2.1.2.0 never faced this problem. Now Once I upgrade to 2.2.0 I am facing this problem.

##### STEPS TO REPRODUCE

```
- name: add docker's public key for CS-engine (debian)
  apt_key:
    url: "https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e"
    state: present
    validate_certs: "{{ validate_certs }}"

- name: add docker CS-engine repos (debian)
  apt_repository:
    repo: "deb https://packages.docker.com/{{ item }}/apt/repo ubuntu-{{ ansible_distribution_release }} main"
    state: present
  with_items: "{{ docker_cs_engine_supported_versions_ubuntu[ansible_distribution_release] }}"
```

Though I am running this playbook on Centos 7 still this is getting executed.
First task above gets skipped successfully but for second task it gives following error.

```
TASK [docker : add docker's public key for CS-engine (debian)] *****************
skipping: [node1]
skipping: [node2]

TASK [docker : add docker CS-engine repos (debian)] ****************************
fatal: [node1]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'Core'"}
fatal: [node2]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute u'Core'"}
	to retry, use: --limit @/home/admin/ansible/site.retry

PLAY RECAP *********************************************************************
node1                      : ok=7    changed=1    unreachable=0    failed=1
node2                      : ok=7    changed=1    unreachable=0    failed=1
```
