### ISSUE TITLE
Create magic variable that contains the value of sys.executable

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#18471]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Playbook variables

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
As discussed in `#ansible-devel`, it would be useful to have a magic global variable named something like `ansible_playbook_interpreter` that contains the value of `sys.executable`. This allows explicit use of the python interpreter used to run `ansible-playbook` rather than relying on the current implicit behavior that is triggered when you don't include `localhost` in your inventory.

Use in the inventory:

```
localhost2 ansible_connection=localhost ansible_python_interpreter="{{ansible_playbook_interpreter}}"
```

Use in a playbook:

```
- hosts: somegroup
  connection: local
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_interpreter }}"
```

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
