### ISSUE TITLE
local_action creates Syntax Error

### ISSUE THREAD

**Issue by zystem** [ansible/ansible#18503]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
local_action

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
using local_action in playbook got
ERROR! Syntax Error while loading YAML.
same playbooks written using alternative directives runs as expected
but it may be problem with 'subversion' module because using 'file' module local_action runs correct
##### STEPS TO REPRODUCE
```
---
- name: subversion test
  hosts: all
  gather_facts: False
  tasks:
  - name: subversion
    run_once: true
    local_action: subversion
        dest: "/tmp/111"
        repo: "http://svn.apache.org/repos/asf/zookeeper/trunk/conf/"
        checkout: yes
        update: yes
        force: yes
```
##### EXPECTED RESULTS
This playbook runs correct
```
---
- name: subversion test
  hosts: all
  gather_facts: False
  tasks:
  - name: subversion
    run_once: true
    delegate_to: 127.0.0.1
    subversion:
        dest: "/tmp/111"
        repo: "http://svn.apache.org/repos/asf/zookeeper/trunk/conf/"
        checkout: yes
        update: yes
        force: yes
```
returns 
```
PLAY [subversion test] *********************************************************

TASK [subversion] **************************************************************
ok: [192.168.1.1 -> 127.0.0.1]

PLAY RECAP *********************************************************************
192.168.1.1              : ok=1    changed=0    unreachable=0    failed=0   
```

This playbook runs correct too
```
---
- name: subversion test
  hosts: all
  gather_facts: False
  tasks:
  - name: subversion
    run_once: true
    connection: local
    subversion:
        dest: "/tmp/111"
        repo: "http://svn.apache.org/repos/asf/zookeeper/trunk/conf/"
        checkout: yes
        update: yes
        force: yes
```
returns
```
PLAY [subversion test] *********************************************************

TASK [subversion] **************************************************************
ok: [192.168.1.1]

PLAY RECAP *********************************************************************
192.168.1.1              : ok=1    changed=0    unreachable=0    failed=0   
```
##### ACTUAL RESULTS
```
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/etc/ansible/deploy_SandBoxCompositeService2.yml': line 9, column 13, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    local_action: subversion
        dest: "/tmp/111"
            ^ here
```

**Comment by abadger** [comment]
This is a Syntax Error because the yaml is trying to make local_action contain both a dictionary (the arguments) and a string (the module name).  I think it should work if you change it like this:

```
- local_action:
    module: subversion
    args:
      dest:  "/tmp/111"
      repo: "http://svn.apache.org/repos/asf/zookeeper/trunk/conf/"
      checkout: yes
      update: yes
      force: yes
```

**Comment by bcoca** [comment]
no need for args:

```
- local_action:
    module: subversion
    dest:  "/tmp/111"
    repo: "http://svn.apache.org/repos/asf/zookeeper/trunk/conf/"
    checkout: yes
    update: yes
    force: yes
```
