### ISSUE TITLE
A commit on ansible broke the template module

### ISSUE THREAD

**Issue by DB-CL** [ansible/ansible#18509]
A commit here, on ansible code, broke the template module for the stable-2.2 branch. I don't think this is module related, that's why I'm posting here. Please tell me if I'm doing it wrong.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template module or ansible (?)

##### ANSIBLE VERSION
Pulled from 2.2 stable branch
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
Debian 8 (vagrant image)

##### SUMMARY
I execute a simple playbook (that I've executed hundreds of times last month) with the last stable-2.2 commit and it fails on the first task using the template module.
I've tracked which commit make this task fails : 7602a2a030b73063368de3d627fcdad47a860e8f by @jimi-c 

##### STEPS TO REPRODUCE
I pull the repo on the following commit : 7602a2a030b73063368de3d627fcdad47a860e8f 
And this playbook fails 
```
- hosts: linux
  gather_facts: yes
  become: yes
  become_user: root
  tasks:
    - name: Copy over the NTP configuration
      template: src=ntp.conf.j2 dest=/etc/ntp.conf
```

If I pull the repo on the previous commit : 413f6ab7f1a570f60d6784dc6e01a8fd73f629c3 then I have no problem at all, the playbook is working well.

##### EXPECTED RESULTS
No error on that task

##### ACTUAL RESULTS
That task fails on all hosts with following message : Failed to get information on remote file (/etc/ntp.conf): MODULE FAILURE
