### ISSUE TITLE
SNI support is broken for new versions of urllib3

### ISSUE THREAD

**Issue by jwodder** [ansible/ansible#18528]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
SNI support provided by `ansible.module_utils.urls`

##### ANSIBLE VERSION
Everything since [commit 6e9c09d](https://github.com/ansible/ansible/commit/6e9c09d7f76decbbf50ee9804da69b7c25dba9f9)

##### SUMMARY
[As seen here](https://github.com/ansible/ansible/blob/77af3a68de3d054ddb3be905d96b1d07c2e89adf/lib/ansible/module_utils/urls.py#L148), Ansible currently tests for SNI support by attempting to import `ssl_wrap_socket` from `urllib3.contrib.pyopenssl`, falling back to importing from `requests.packages.urllib3.contrib.pyopenssl`.  However, version 1.19 of urllib3 [removed this function](https://github.com/shazow/urllib3/commit/1db3bba5f5bc83812810fb95803ea21971c6c052) ("As we never exported `ssl_wrap_socket` nobody should be using it."), and requests [updated its vendorized copy of urllib3 to match](https://github.com/kennethreitz/requests/commit/99fa7becf263473c7bfc1998b41c2c6c80a0f499) in version 2.12.0.  As a result, on systems using the latest versions of these packages, Ansible will falsely conclude that SNI is not supported, leading to attempts to connect to SNI-dependent sites (say, with `get_url`) to fail.

##### STEPS TO REPRODUCE
```
- name: Install the latest versions of SNI-related packages
  # Not shown here: Installing the SSL, FFI, and Python development libraries that are needed to build these modules.
  pip: name={{item}} state=latest
  with_items:
    - ndg-httpsclient
    - pyasn1
    - pyopenssl
    - requests
    - urllib3

- name: Try to download a file from an SNI-dependent site
  get_url:
    url: https://downloads.atlassian.com
    dest: /tmp/whatever
```

##### EXPECTED RESULTS
The file would be downloaded.

##### ACTUAL RESULTS
```
TASK [get_url] *****************************************************************
fatal: [sshbase]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for downloads.atlassian.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
```
