### ISSUE TITLE
delegate_to does not propagate to steps in a hierarchy of included playbooks

### ISSUE THREAD

**Issue by genei09** [ansible/ansible#18522]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
delegate_to

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
OSx 10.12.1.

##### SUMMARY
up to 2.1.2.0 delegate_to would be respected on all steps from included .yml files.  In 2.2.0.0 every include needs to have a delegate_to.

##### STEPS TO REPRODUCE
have a main playbook which includes a 2nd playbook
the 2nd playbook includes a 3rd playbook.

In the main delegate_to the call to the 2nd playbook.
Steps in the 2nd playbook will be run against the delegate_to
Steps in the 3rd playbook will be run against the original target.

```
for this example I'm delegating to a docker container:
create a directory and a file named setup.sh (contents of the file don't matter)

ansible-playbook playbooks/example/main.yml -e "container_name=test local_source=<path to setup.sh file>"

create 4 files
playbooks/example/main.yml
tasks/example.yml
tasks/example_setup.yml
tasks/build_demo.yml

playbooks/example/main.yml:
---
- hosts: localhost
  connection: local

  tasks:
  - name: Provisioning example container
    include: ../tasks/example.yml

  - name: "Finalize container setup"
    delegate_to: "{{ container_name }}"
    include: ../tasks/example_setup.yml

tasks/example.yml:
---
- name: start container
  docker:
    name: "{{ container_name }}"
    extra_hosts: "{ '{{ container_name }}': '127.0.0.1' }"
    image: centos:7
    state: "{{ action | default('started') }}"
    command: /bin/bash
    pull: missing
    tty: "{{ tty | default('True') }}"
    volumes:
      - "{{ local_source }}:/tmp:rw"

- name: register container hostname
  add_host:
    name: "{{ container_name }}"
    groups: test
    ansible_connection: docker
    ansible_docker_extra_args: "-H={{ lookup('env','DOCKER_HOST') }}"
    ansible_user: "{{ container_user | default('root') }}"

tasks/example_setup.yml:
---
- name: copy source
  shell: cp -r /tmp/* /opt

- name: "Rebuild the demo data"
  delegate_to: "{{ container_name }}"
  include: build_demo.yml

tasks/build_demo.yml
---
- name: Populate database
  shell: |
          cd /opt
          sh setup.sh
```

##### EXPECTED RESULTS
the final step named "Populate database" runs the setup.sh file within the docker container

##### ACTUAL RESULTS
the final step responds with no such file because the final step isn't run against the container.

if the tasks/build_demo.yml file has the same delegate_to line, or the include step has the delegate_to it runs as expected.

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [start container] *********************************************************
ok: [localhost]

TASK [register container hostname] *********************************************
changed: [localhost]

TASK [copy source] *************************************************************
changed: [localhost -> test]

TASK [Populate database] *******************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "cd /opt\n sh setup.sh", "delta": "0:00:00.006455", "end": "2016-11-17 08:39:02.011671", "failed": true, "rc": 127, "start": "2016-11-17 08:39:02.005216", "stderr": "sh: setup.sh: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/Users/example/Repos/example/playbooks/example/main.retry

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=1   
```

**Comment by DebianRoxx** [comment]
I have similar problem with ansible 2.3.0 (detached HEAD f6437f1b6e), _delegate_to_ doesn't work well over block : tasks run on the "top" host.
To bypass that, I must apply _delegate_to_ over each _include_ like that :

```
- block:
  - include: "install.yml"
    delegate_to: "{{ db_server }}"
    static: no

  - include: "create_database.yml"
    static: no
    delegate_to: "{{ db_server }}"

  - include: "grant_rights.yml"
    static: no
    delegate_to: "{{ db_server }}"

# didn't work anymore
# delegate_to: "{{ db_server }}"
```
