### ISSUE TITLE
Add option to fail on deprecated features

### ISSUE THREAD

**Issue by clonedagain** [ansible/ansible#18559]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
ansible 2.1.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Defaults from pip

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When deprecated features disappear, the results of a playbook may change and yet not fail.
Users would benefit from a mode in `ansible-playbook` where deprecated tasks would fail, so as to identify them early on.

For example, in Ansible up to 2.1.x, this fake playbook should adds 4 configuration lines, but in 2.2 it would silently changes to adding a bogus line "my_config".
```
---
- hosts: bla
  vars:
    my_config:
      - "vx200.configure=automagic"
      - "autofibulator.variation_mode=static"
  tasks:
    - lineinfile:
        dest=/etc/some-critical-file
        line: "{{ item }}"
      with_flattened:
        - my_config
        - ['kevo=levo', 'ano=revo']
```
##### STEPS TO REPRODUCE
The default would remain to not throw errors on deprecation.

Deprecation errors would be enabled/disabled through :
- environment variable `ANSIBLE_ERROR_ON_DEPRECATION`
- configuration option `error_on_deprecation`
- command-line option `--error-on-deprecation`

##### EXPECTED RESULTS
Playbooks plainly fail when they are not upgrade-proof regarding Ansible.

##### ACTUAL RESULTS
Playbooks run with deprecation warnings which are non-blocking and may be difficult to spot in the output flow.
