### ISSUE TITLE
Boto3 not detected on Mac OS

### ISSUE THREAD

**Issue by midN** [ansible/ansible#18563]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.2.0.0
Python 2.7.12
Python bin path - /usr/local/bin/python
Boto3 - /usr/local/lib/python2.7/site-packages/boto3/
```

##### OS / ENVIRONMENT
Mac OS El Capitan 10.11.6

##### SUMMARY
Every module that requires boto3 started erroring out with `fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "boto3 is required."}`

##### STEPS TO REPRODUCE
```
---
- hosts: localhost
  connection: local
  tasks:
    # Update required task_definitions with proper branch
    - name: Get CF-Stack facts
      cloudformation_facts:
        stack_name: mystack
```

##### ACTUAL RESULTS
```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
^R
ok: [localhost]

TASK [Get CF-Stack facts] ******************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "boto3 is required."}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

Boto and Boto3 are installed.
Calling `import boto3` from `python` also works fine.
I have tried setting `localhost ansible_python_interpreter=/usr/local/bin/python`, i have tried setting `export PYTHONPATH=/usr/local/lib/python2.7/site-packages`, no luck.

I've tried using Mac Os default Python2.7, Python2.7 installed from `brew`.
I have tried installing `ansible` from `brew` and from `pip`, still no difference.

Anybody has any idea what could be wrong and why `boto3` is not found by `ansible-playbook` ?
