### ISSUE TITLE
Handler fails to execute if it has the same name as a handler in a role conditionally included using when

### ISSUE THREAD

**Issue by jonathangreen** [ansible/ansible#18594]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- roles
- handlers

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Running Ansible from OSX 10.12.1
Managing Ubuntu Precise 

##### SUMMARY
When two roles are included in a playbook that both define handlers with the same name. If the first role is conditionally included using the when statement the handler is skipped even if its notified in the second role.

##### STEPS TO REPRODUCE
roles/a/tasks/main.yml
```yaml
---

- name: First test
  shell:
    touch ~/test
  notify: same handler name
```

roles/a/handlers/main.yml 
```yaml
---

- name: same handler name
  debug:
    msg: blah!!
```

roles/b/tasks/main.yml 
```yaml
---

- name: First test
  file:
    path: ~/test
    state: file
  notify: same handler name
```

roles/b/handlers/main.yml
```yaml
---

- name: same handler name
  debug:
    msg: blah!!
```

test.yml
```yaml
---

- name: test playbook
  hosts: webserver
  remote_user: "{{ deploy_user }}"
  become: yes

  roles:
    - { role: b, when: false }
    - a
```

##### EXPECTED RESULTS

I would expect the following sequence:
* role b gets skipped
* role a runs and notifies the handler `same handler name`
* then either:
  * role a's copy of the handler runs 
  * role b's copy of the handler runs

However the handler just gets skipped.

##### ACTUAL RESULTS

```
PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [test playbook] ***********************************************************

TASK [setup] *******************************************************************
ok: [test]

TASK [b : First test] **********************************************************
task path: /Users/jgreen/Documents/projects/test-playbook/roles/b/tasks/main.yml:3
skipping: [test] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

TASK [a : First test] **********************************************************
task path: /Users/jgreen/Documents/projects/test-playbook/roles/a/tasks/main.yml:3
NOTIFIED HANDLER same handler name
changed: [test] => {"changed": true, "cmd": "touch ~/test", "delta": "0:00:00.002720", "end": "2016-11-23 02:30:02.687300", "rc": 0, "start": "2016-11-23 02:30:02.684580", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": ["Consider using file module with state=touch rather than running touch"]}
 [WARNING]: Consider using file module with state=touch rather than running touch


RUNNING HANDLER [b : same handler name] ****************************************
skipping: [test] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}

PLAY RECAP *********************************************************************
test                  : ok=2    changed=1    unreachable=0    failed=0   
```

**Comment by gundalow** [comment]
From @bcoca 
>there is no 'conditional' include in roles:
> the condition is inherited by the tasks
> you can only call 1 handler by name, last one defined wins
> @jimi-c  the static/dynamic confusion i was talking about
> what does seem an error here is that the 'first' handler defined wins
> workaround, use listen: instead of name

**Comment by jonathangreen** [comment]
Okay. I was under a misunderstanding about how roles get included. 

Still is it correct that then condition is inherited by handlers within roles? I would expect the handlers to be still able to run.

I also agree that is seems incorrect that the first handler defined wins. 

My work around that is working for me is to manually include the handler I want to run in the playbook:
```yaml
handlers:
  - include: roles/a/handlers/main.yml
    static: yes
```
