### ISSUE TITLE
Ansible loading unexpected role varibles

### ISSUE THREAD

**Issue by mwmisner** [ansible/ansible#18593]
## Issue
```
Ansible appears to be loading variables from roles that are not being executed, is this expected behavior?
```
## Relation
I think this might possibly be related to  https://github.com/ansible/ansible/issues/3103 , but I think that this is a bit different in that I do not see a reason for it to load any of the variables in the role.

### default.yml
```
---
- hosts: all
  roles:
    - { role: common, when: ansible_distribution == 'Amazon' }
    - { role: windows, when: ansible_os_family == 'Windows' }
    - { role: custom, when: var == 'custom' }
```

### roles/common/vars/main.yml
```
directory: '/tmp/test/dir'
```

### roles/windows/vars/main.yml
```
directory: 'C:/Test/Dir/'
```

### roles/custom/task/main.yml
```
- name: Place file for linux customer instances
  template:
    src: roles/common/templates/file.j2
    dest: '{{ directory }}/file.conf'
  when: (ansible_distribution == 'Amazon') or
        (ansible_distribution == 'RedHat')

- name: Place file for linux customer instances
  win_template:
    src: roles/common/templates/file.j2
    dest: '{{ directory }}/file.windows.conf'
  when: (ansible_os_family == 'Windows')
```
## Output:
When applying to an amazon linux instance I receive the following result
```
Destination directory C:/testfile/file.conf does not exist
```

## Testing:
Commented out the following line and received expected variables.
### default.yml
```
- hosts: all
  roles:
    - { role: common, when: ansible_distribution == 'Amazon' }
    # - { role: windows, when: ansible_os_family == 'Windows' }
    - { role: custom, when: var == 'custom' }
```
