### ISSUE TITLE
Add possibility to list nested level of linked object in returned type of oVirt modules

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#18650]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ansible/module_utils/ovirt.py

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### SUMMARY

We should add an common option to all Ansible oVirt modules, which will say if we should fetch additional data from entities in API, which are provided as links. This would cost are addinional API calls and so performance degradation, but in favor of more user data.

We should add an new parameter called 'fetch_data' or similar, which will fetch names and ids of additinal entities, we should also consider doing it an integer so we can fetch another nested entities of nested entities.

**Comment by ganniterix** [comment]
An example where this would come useful, is when requiring the ID of a disk attached to a VM, create from a template. Since the name will get replicated a number of times, there is no way right now, to obtain through ansible the ID of the newly created disk.

**Comment by machacekondra** [comment]
I have a patch created, the output now looks like this:
```yaml
TASK [Print vms] ***************************************************************
ok: [localhost] => {
    "ovirt_vms": [
        {
            "affinity_labels": [], 
            "applications": [
                {
                    "id": "6f766972-742d-6775-6573-742d6167656e"
                }, 
                {
                    "id": "6b65726e-656c-2d33-2e31-302e302d3332"
                }, 
                {
                    "id": "636c6f75-642d-696e-6974-2d302e372e35"
                }
            ], 
            "bios": {
                "boot_menu": {
                    "enabled": false
                }
            }, 
            "cdroms": [
                {
                    "id": "00000000-0000-0000-0000-000000000000"
                }
            ], 
            "cluster": {
                "href": "/ovirt-engine/api/clusters/a33a2dfd-f8fe-47b8-8aad-f1353a5c80fe", 
                "id": "a33a2dfd-f8fe-47b8-8aad-f1353a5c80fe"
            }, 
            "cpu": {
                "architecture": "x86_64", 
                "topology": {
                    "cores": 1, 
                    "sockets": 1, 
                    "threads": 1
                }
            }, 
            "cpu_profile": {
                "href": "/ovirt-engine/api/cpuprofiles/d78098ea-b3bf-4188-9d97-a42dad03c6a1", 
                "id": "d78098ea-b3bf-4188-9d97-a42dad03c6a1"
            }, 
            "cpu_shares": 0, 
            "creation_time": "2016-11-29 09:23:55.195000+01:00", 
            "delete_protected": false, 
            "disk_attachments": [
                {
                    "id": "9a6826d8-344d-4667-acf0-3c0d49811136"
                }
            ], 
            "display": {
                "address": "10.34.61.45", 
                "allow_override": false, 
                "copy_paste_enabled": true, 
                "disconnect_action": "LOCK_SCREEN", 
                "file_transfer_enabled": true, 
                "monitors": 1, 
                "secure_port": 5900, 
                "single_qxl_pci": true, 
                "smartcard_enabled": false, 
                "type": "spice"
            }, 
            "fqdn": "mycomputer.local", 
            "graphics_consoles": [
                {
                    "id": "7370696365"
                }
            ], 
            "guest_operating_system": {
                "architecture": "x86_64", 
                "codename": "Maipo", 
                "distribution": "Red Hat Enterprise Linux Server", 
                "family": "Linux", 
                "kernel": {
                    "version": {
                        "build": 0, 
                        "full_version": "3.10.0-327.el7.x86_64", 
                        "major": 3, 
                        "minor": 10, 
                        "revision": 327
                    }
                }, 
                "version": {
                    "full_version": "7.2", 
                    "major": 7, 
                    "minor": 2
                }
            }, 
            "guest_time_zone": {
                "name": "Europe/Prague", 
                "utc_offset": "+01:00"
            }, 
            "high_availability": {
                "enabled": false, 
                "priority": 1
            }, 
            "host": {
                "href": "/ovirt-engine/api/hosts/7f92fcb8-7c31-4bb6-9ee3-721f555733d1", 
                "id": "7f92fcb8-7c31-4bb6-9ee3-721f555733d1"
            }, 
            "host_devices": [], 
            "href": "/ovirt-engine/api/vms/eb8ab4c8-2842-49e2-8d0a-7711d9a5782b", 
            "id": "eb8ab4c8-2842-49e2-8d0a-7711d9a5782b", 
            "initialization": {
                "nic_configurations": [], 
                "regenerate_ssh_keys": false
            }, 
            "io": {
                "threads": 0
            }, 
            "katello_errata": [], 
            "large_icon": {
                "href": "/ovirt-engine/api/icons/9910b0f0-9923-4021-b7d6-859b3acf851d", 
                "id": "9910b0f0-9923-4021-b7d6-859b3acf851d"
            }, 
            "memory": 1073741824, 
            "memory_policy": {
                "guaranteed": 1073741824
            }, 
            "migration": {
                "auto_converge": "inherit", 
                "compressed": "inherit"
            }, 
            "migration_downtime": -1, 
            "name": "rhel7_4", 
            "next_run_configuration_exists": false, 
            "nics": [
                {
                    "id": "ec533ced-41e8-481b-a727-3f0fe4be69b7"
                }, 
                {
                    "id": "b18b8cd6-76c9-4b7c-a108-c91203f3a09e"
                }
            ], 
            "numa_nodes": [], 
            "numa_tune_mode": "interleave", 
            "origin": "ovirt", 
            "os": {
                "boot": {
                    "devices": [
                        "hd"
                    ]
                }, 
                "type": "rhel_7x64"
            }, 
            "permissions": [
                {
                    "id": "57d2f893-0086-017c-01c2-00000000004a"
                }, 
                {
                    "id": "57d2f8d3-02a5-0317-008e-0000000002b1"
                }
            ], 
            "placement_policy": {
                "affinity": "migratable"
            }, 
            "reported_devices": [
                {
                    "id": "65746831-3030-3a31-613a-34613a31363a"
                }, 
                {
                    "id": "65746830-3030-3a31-613a-34613a31363a"
                }
            ], 
            "run_once": true, 
            "sessions": [
                {
                    "id": "37a6259c-c0c1-dae2-99a7-866489dff0bd"
                }, 
                {
                    "id": "37a6259c-c0c1-dae2-99a7-866489dff0bd"
                }
            ], 
            "small_icon": {
                "href": "/ovirt-engine/api/icons/d33fa845-4d73-4af5-aa72-0e53b838d0c8", 
                "id": "d33fa845-4d73-4af5-aa72-0e53b838d0c8"
            }, 
            "snapshots": [
                {
                    "id": "3b54f68e-6d31-4b40-bfee-54118642934c"
                }
            ], 
            "sso": {
                "methods": [
                    {
                        "id": "guest_agent"
                    }
                ]
            }, 
            "start_paused": false, 
            "start_time": "2016-11-29 09:24:05.442000+01:00", 
            "stateless": false, 
            "statistics": [
                {
                    "id": "5a89a1d2-32be-33f7-a0d1-f8b5bc974ff6"
                }, 
                {
                    "id": "b7499508-c1c3-32f0-8174-c1783e57bb08"
                }, 
                {
                    "id": "ef802239-b74a-329f-9955-be8fea6b50a4"
                }, 
                {
                    "id": "d849a55f-0049-36f8-ae65-face541473ac"
                }, 
                {
                    "id": "2ec286fe-4bec-32f5-8d63-dba7bed58763"
                }, 
                {
                    "id": "892b69a7-41ca-36b1-9a2e-ae5177ef21bb"
                }, 
                {
                    "id": "09e07489-64fd-32ab-8e4e-a2b61eed8d60"
                }, 
                {
                    "id": "1b6244ee-8dbd-365d-8762-482ddc05ee11"
                }, 
                {
                    "id": "5a0fba9d-33d7-3cbf-addd-ba462040c946"
                }
            ], 
            "status": "up", 
            "stop_time": "2016-11-29 09:24:02.507000+01:00", 
            "tags": [], 
            "template": {
                "href": "/ovirt-engine/api/templates/225931cb-c791-44e6-bd11-af9bdf19ae34", 
                "id": "225931cb-c791-44e6-bd11-af9bdf19ae34"
            }, 
            "time_zone": {
                "name": "Etc/GMT"
            }, 
            "type": "desktop", 
            "usb": {
                "enabled": false
            }, 
            "watchdogs": []
        }
    ]
}
```
