### ISSUE TITLE
git clone fatal error

### ISSUE THREAD

**Issue by farahfa** [ansible/ansible#18703]
Hello,

In my `tasks/main.yml` I have the following:

```
- name: Fetch nexus license
  become: true
  git: repo=git@git.company.com:user/repo.git dest=/tmp key_file="{{ key_file_dest_location }}" accept_hostkey=yes force=yes
  tags:
    - ansible-nexus
```

I get the following error:

```
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin '' /tmp", "failed": true, "msg": "fatal: destination path '/tmp' already exists and is not an empty directory.", "rc": 128, "stderr": "fatal: destination path '/tmp' already exists and is not an empty directory.\n", "stdout": "", "stdout_lines": []}
```

I'm expecting it to clone the repo (creates a dir) in `/tmp`, why is giving me this error?

P.S.: I'm (very) new to Ansible, so please excuse my newbieness.. 😄
