### ISSUE TITLE
'until' condition is not evaluated when 'retries' equals 0

### ISSUE THREAD

**Issue by nelsg** [ansible/ansible#18712]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

retries ... until

##### ANSIBLE VERSION

```
2.2.0.0
```

##### CONFIGURATION

default

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

In my playbooks, I often use a variable in 'retries' in order to be able to adjust this value.
When I want do disable the 'retries' with 0, 'until' expression is not evaluated, which results in a different behavior than when I use 'retries' > 0.

##### STEPS TO REPRODUCE

Use this playbook:

```
- hosts: all
  gather_facts: false
  tasks:
  - command: "echo this is an error"
    retries: "{{ nb_retries }}"
    delay: 1
    register: result
    until: '"error" not in result.stdout'
```

If I use nb_retries = 1, task fails (expected behavior) :

    ansible-playbook -c local -i "localhost," site.yml -e nb_retries=1

If I use nb_retries = 0, task succeeded :

    ansible-playbook -c local -i "localhost," site.yml -e nb_retries=0

To fix that, I need to overwrite 'failed_when' expression which makes an inverted duplicate of 'until' :

```
- hosts: all
  gather_facts: false
  tasks:
  - command: "echo this is an error"
    retries: "{{ nb_retries }}"
    delay: 1
    register: result
    failed_when: '"error" in result.stdout'
    until: '"error" not in result.stdout'
```

##### EXPECTED RESULTS

Both commands fails (with retries=0 or retries=1)

##### ACTUAL RESULTS

```
$ ansible-playbook -c local -i "localhost," site.yml -e nb_retries=0
PLAY [all] *********************************************************************

TASK [command] *****************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   

```
