### ISSUE TITLE
jinja2 templates can only yield strings

### ISSUE THREAD

**Issue by pablobm** [ansible/ansible#18722]
##### ISSUE TYPE
  - Bug Report

##### COMPONENT NAME
  - Evaluation of jinja2 templates

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A (assumed. Only tested on macOS)

##### SUMMARY
You can't have non-string variables as the result of arithmetic/filters/etc in jinja2 templates

##### STEPS TO REPRODUCE
Consider a playbook and a vars file:

```yaml
# test_vars.yml
seven: 7
seven_again: "{{ seven }}"
seven_once_more: "{{ seven | int }}"
fourteen: "{{ (seven * 2) | int }}"
```

```yaml
# test.yml
- hosts: all
  gather_facts: False
  vars_files:
    - test_vars.yml
  tasks:
    - debug:
        msg: "{{ seven | to_json}} {{ seven_again | to_json }} {{ seven_once_more | to_json }} {{ fourteen | to_json }}"
```

##### EXPECTED RESULTS

I would have expected all four numbers to appear unquoted, as follows (abridged):

```
$ ansible-playbook test.yml -i localhost, -c local -vvv
(...)
ok: [localhost] => {
    "msg": "7 7 7 14"
}
(...)
```

##### ACTUAL RESULTS

Instead, the last two numbers are quoted, as follows (abridged):

```
$ ansible-playbook test.yml -i localhost, -c local -vvv
(...)
ok: [localhost] => {
    "msg": "7 7 \"7\" \"14\""
}
(...)
```
