### ISSUE TITLE
Feature: loop threads

### ISSUE THREAD

**Issue by HanXHX** [ansible/ansible#18744]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

When you have "long" tasks in a loop or a very large list, it's very hard to optimize. Async tasks is not a solution when need "right now" to parse a registered vars.

My idea is to create a new feature on a task: `loop_threads`. A loop thread is launched *per host* (if you run your task on 10 hosts with 3 `loop_threads`, you have up to 30 threads).

Features:

- new ansible.cfg var (`max_loop_threads`)
- keep order on registered var (task 1, is on first place on registered var ".results")
- loop thread should be transparent for user to keep backward compatibility

Please note, all modules can't be compatible with `loop_threads`: like apt (system lock). Globally, every module with a list param should not be compatible.

##### STEPS TO REPRODUCE

Example 1:

```yaml
- name: COMMAND | Long tasks
  command: "sleep {{ item }}"
  with_items: [10, 20, 30]
  loop_threads: 3
```

Example 2:

```yaml
- name: COMMAND | Long tasks
  command: "sleep {{ item }}"
  with_items: [10, 20, 30, 40, 50]
  loop_threads: 3
```

##### EXPECTED RESULTS

- Example 1: max(10, 20, 30) = 30 sec
- Example 2: max(10, 20, 30) + max(40, 50) = 80 sec

##### ACTUAL RESULTS

- Example 1 (without `loop_threads`): 10 + 20 + 30 = 60 sec
- Example 2 (without `loop_threads`): 10 + 20 + 30 + 40 + 50 = 150 sec
