### ISSUE TITLE
Play include behaves weirdly when conditioned on groups

### ISSUE THREAD

**Issue by yfried** [ansible/ansible#18745]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Include

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

Not Affected:
```
ansible 2.3.0 (devel 8e375913b0) last updated 2016/12/05 12:34:04 (GMT +300)
  lib/ansible/modules/core: (detached HEAD 6890003c4f) last updated 2016/12/04 10:26:59 (GMT +300)
  lib/ansible/modules/extras: (detached HEAD 20ea46642b) last updated 2016/12/04 10:26:59 (GMT +300)
  config file = 
  configured module search path = Default w/o overrides
```
```
ansible 2.1.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Fedora 24
RHEL 7
##### SUMMARY
The following should not be included

```yaml
- include: fileB.yml
  when: "{{ 'localhost' not in groups }}"
```

However, **some** tasks in `fileB.yml` are executed while others are skipped

##### STEPS TO REPRODUCE

fileA.yml
```yaml
- include: fileB.yml
  when: "{{ switch in groups }}"
```

fileB.yml
```yaml
- hosts: localhost
  gather_facts: no
  any_errors_fatal: true
  tasks:
      - name: fail nested
        fail:
          msg:
              a: "this is skipped. groups={{ groups }}"
              b: "{{ 'localhost' not in groups }}"

      - name: debug nested
        debug:
          msg:
              a: "this isn't skipped. groups={{ groups }}"
              b: "{{ 'localhost' not in groups }}"
```

##### EXPECTED RESULTS

```
$ ansible-playbook fileA.yml -vvvv -e switch=localhost

TASK [fail nested] **************************************************************************************************
task path: /tmp/fileB.yml:5
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [debug nested] *************************************************************************************************
task path: /tmp/fileB.yml:11
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

PLAY RECAP **********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```

```
$ ansible-playbook fileA.yml -e switch=all

PLAY [localhost] ****************************************************************************************************

TASK [fail nested] **************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": {"a": "this is skipped. groups={'ungrouped': [u'localhost'], 'all': []}", "b": true}}

NO MORE HOSTS LEFT **************************************************************************************************
	to retry, use: --limit @/tmp/fileA.retry

PLAY RECAP **********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```
##### ACTUAL RESULTS
```
$ ansible-playbook -vvvv fileA.yml -e switch=localhost

PLAY [localhost] ***************************************************************

TASK [fail nested] *************************************************************
task path: /tmp/fileB.yml:5
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [debug nested] ************************************************************
task path: /tmp/fileB.yml:11
ok: [localhost] => {
    "msg": {
        "a": "this isn't skipped. groups={'ungrouped': [u'localhost'], 'all': []}", 
        "b": true
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   


```
