### ISSUE TITLE
Cron - Module Failure

### ISSUE THREAD

**Issue by tcruz1971** [ansible/ansible#18768]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

cron module

##### SUMMARY
While doing:
```
- name: Crontab Setting for Program
  cron: name="Check Program is running" minute="*/7" user="test"
        job='bash -c "source {{ homedir }}/.bashrc && $TEST_HOME/bin/Program.sh start" > /dev/null'
```
##### ANSIBLE VERSION
```ansible 2.3.0 (devel 39c2249e49)```

##### OS / ENVIRONMENT
CentOS 3.10.0-327.36.2.el7.x86_64

##### ACTUAL RESULTS
It sets the Crontab as:
```
#Ansible: Check Program is running
*/7 * * * * bash -c "source /home/test/.bashrc && $TEST_HOME/ARL/Program.sh start" > /dev/null
```

but returns back with:
```
 FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_vHdMFc/ansible_module_cron.py\", line 773, in <module>\r\n    main()\r\n  File \"/tmp/ansible_vHdMFc/ansible_module_cron.py\", line 741, in main\r\n    crontab.write()\r\n  File \"/tmp/ansible_vHdMFc/ansible_module_cron.py\", line 345, in write\r\n    selinux.selinux_lsetfilecon_default(self.cron_file)\r\nOSError: [Errno 14] Bad address\r\n", "msg": "MODULE FAILURE"
```

**Comment by ansibot** [comment]
cc @dsummersl, @EvanK
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by tcruz1971** [comment]
# Just figured out:

I had code:
```
- name: Crontab Setting for Program
  cron: name="Check Program is running" minute="*/7" user="test" job='bash -c "source {{ homedir }}/.bashrc && $TEST_HOME/bin/Program.sh start" > /dev/null'
```
Changed to:
```
- name: Crontab Setting for Program
  cron: 
    name: "Check Program is running" 
    minute: "*/7" 
    user: "test"
    job: 'bash -c "source {{ homedir }}/.bashrc && $TEST_HOME/bin/Program.sh start" > /dev/null'
```
and no issues.

**Comment by flatrocks** [comment]
Having the same issue (`OSError: [Errno 14] Bad address`) and the same FAILED! message.  It seems to be intermittent, and only occurs with the cron module.

Local:
* Ansible 2.3.0
* Mac Sierra 10.12.2
* OpenSSL 0.9.8zh 14 Jan 2016 via Homebrew

Deploying to Ubuntu 16.04
* OpenSSL 1.0.2g  1 Mar 2016

The offending task:
```
    - name: create cron job to rebuild indexes
      cron:
        user: tgo
        name: "index_sphinxsearch"
        job: "cd /home/tgo/deploy/current && /home/tgo/.rbenv/shims/bundle exec rake ts:index"
        hour: "1,13"
        minute: "40"
      tags:
        - cron
```
Whenever I think I have made a change that fixes it, it fails again, so realistically I do not have a solution.  I'd be glad to know I am doing something wrong, but so for no idea.
