### ISSUE TITLE
Abort/fail if host is unreachable

### ISSUE THREAD

**Issue by EthanStrider** [ansible/ansible#18782]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Abort/fail if host is unreachable

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible does not seem to treat an unreachable host as a failure, and in some cases (especially tasks where Ansible is involved in monitoring), I need any and all unreachable hosts to exit failure immediately, instead of continuing on to other hosts.

It looks like I'm not the only one either:
http://stackoverflow.com/questions/25930503/aborting-ansible-playbook-if-a-host-is-unreachable
http://stackoverflow.com/questions/31221165/ansible-abort-execution-if-a-host-is-unreachable
http://stackoverflow.com/questions/39657431/ansible-unreachable-instead-failed

FWIW, none of the suggestions in the posts above worked for me.

##### STEPS TO REPRODUCE
The feature would hopefully be as simple as a boolean that a user can toggle, e.g. 'fail_on_unreachable: true'

##### EXPECTED RESULTS
I expected some method for failing/aborting on unreachable hosts.

##### ACTUAL RESULTS
Couldn't find a good way to do it.

**Comment by krzysztof-magosa** [comment]
Maybe `any_errors_fatal` could help?

**Comment by linsomniac** [comment]
@krzysztof-magosa : Unfortunately, unreachable doesn't seem to be considered a fatal in a way that "any_errors_fatal" or "max_failure_percentage" will detect.  Even when combined with "gather_facts: false" and running a ping action on the host, it shows up in the output with a "fatal" prefix, but still doesn't seem to trigger the termination of the play with any combination of "any_errors_fatal" or "max_failure_percentage" I've tried.  According to one of the Stack Overflow discussions I've read, this behavior changed in 2.1, it worked before that.

**Comment by jimi-c** [comment]
Hi @linsomniac, have you tested recently to see if the issue has been corrected?

**Comment by bcoca** [comment]
This makes sure that 'current hosts in play' are the same as the initial hosts selected for the play, will detect unreachable, but also 'failed' hosts.
```yaml
    - assert:
        that:
            - ansible_play_hosts == ansible_play_hosts_all
```
another way is checking the registered var value for 'unreachable' key (via hostvars or clearing host errors).

```yaml
- fail:  msg='host {{item}} was unreachable'
  when: "'unreachable' in hostvars[item]['registeredvar']"
  with_items: "{{ ansible_play_hosts_all }}"
  run_once: True
```
