### ISSUE TITLE
[code] Add lookup_plugin to parse lines from a variable

### ISSUE THREAD

**Issue by liedekef** [ansible/ansible#1884]
I needed to add a line to several config files (all ending on e.g. ".cfg" but different names for the rest) on a group of servers, but there was no plugin suitable for this.
So, first I needed to do a ls on the client, grab the response and put it in a variable, then loop through each line of the response.
Since no lookup plugin did the looping, here's mine. Since it's based on items.py, I call it items_in_string.py:

```
# This file is part of Ansible
#
# Ansible is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Ansible is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Ansible.  If not, see <http://www.gnu.org/licenses/>.

class LookupModule(object):

    def __init__(self, **kwargs):
        pass

    def run(self, terms, **kwargs):
        return terms.split()
```

Usage example:

```

---
- hosts: test-servers

  tasks:
  - name: config file
    action: shell ls /some/dir/${ansible_hostname}_*.cfg
    register: my_configs
  - action: command echo $item
    with_items_in_string: ${my_configs.stdout}
```

**Comment by mpdehaan** [comment]
Yep, that will work.

It could also be done using with_lines, and executing ls -l piped to cut -f.

I don't think we need this in core given the above, but this is a nice example of how short lookup plugins can be.

You might want to share this with the list as it is a neat example.

**Comment by dhozac** [comment]
FYI, you can do this as

```
---
- hosts: test-servers

  tasks:
  - name: config file
    action: shell ls /some/dir/${ansible_hostname}_*.cfg
    register: my_configs
  - action: command echo $item
    with_items: ${my_configs.stdout_lines}
```

as well.
