### ISSUE TITLE
lxd_container does not validate HTTPS server certificate

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#18882]
_From @candlerb on December 5, 2016 16:32_

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lxd_container

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/brian/ansible-configs/auth-servers/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

lxd_container does not appear to validate server certificate when connecting via REST API to a remote host using HTTPS, and therefore seems to be using it insecurely.

##### STEPS TO REPRODUCE

```
- hosts: localhost
  tasks:
    - name: create container
      lxd_container:
        url: https://192.168.5.82:8443
        trust_password: XXXXXXXX
        name: foo
        state: started
        source:
          type: image
          mode: pull
          server: https://cloud-images.ubuntu.com/releases
          protocol: simplestreams
          alias: '16.04'
```

... where 192.168.5.82 is some remote lxd server which has remote access enabled using

~~~
lxc config set core.https_address "[::]"
lxc config set core.trust_password XXXXXXXX
~~~

Remove trust password and repeat. ansible is happy to talk to the host again (it is caching its own client certificate). However it doesn't appear to have cached the server certificate anywhere, so has no way to confirm it is still talking to the same host.

##### EXPECTED RESULTS

* lxd_container module should require that the server certificate fingerprint is provided, or explicitly that no fingerprint check is to be done
* even if no fingerprint check is done initially, the first time the connection is made to the server the server certificate is cached and used to validate subsequent connections

The 'lxc' command line tool does exactly this:

* It shows the server certificate fingerprint and asks you to confirm it's OK (unless you pass `--accept-certificate`)
* It creates `~/.config/lxc/servercerts/<remote>.crt` to cache the server certificate
* If you remove this file, it complains that it can't validate the certificate

~~~
error: Get https://192.168.5.82:8443/1.0/containers?recursion=1: x509: certificate signed by unknown authority
~~~

(Aside: until recently, lxd created certificates with "DNS:192.168.5.82" in the SubjectAltName. This has now been [fixed](https://github.com/lxc/lxd/issues/2457) so it has "IP:192.168.5.82". But you still need to accept the certificate since it's self-signed)

##### ACTUAL RESULTS

No server certificate checking or caching appears to be taking place

##### NOTES

In `lib/ansible/module_utils/lxd.py` the ssl context is created using:

~~~
            ctx = ssl.create_default_context(ssl.Purpose.CLIENT_AUTH)
~~~

However according to the [documentation](https://docs.python.org/2/library/ssl.html) Purpose.CLIENT_AUTH is used for when you are building an SSL server. If you are connecting *to* an SSL server you are supposed to use Purpose.SERVER_AUTH.

(But it's not entirely clear to me what the 'purpose' is doing. It does say that "Passing SERVER_AUTH as purpose sets verify_mode to CERT_REQUIRED" and loads CA certificates. But in this case we may wish to validate the server certificate *and* present a client certificate to the server)

_Copied from original issue: ansible/ansible-modules-extras#3663_
