### ISSUE TITLE
Add state=empty into file module

### ISSUE THREAD

**Issue by erikdw** [ansible/ansible#18910]
_From @Nindaleth on March 6, 2015 17:2_

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
file

##### SUMMARY
In our playbooks we need to empty some folders, but currently our only option seems to be using `command` or `shell` module. It has its uses to leave the folder intact as there may have been some owner/permission changes, or alternatively it may be a mountpoint that is not even possible to delete.
Similar ideas might be had about files as well.

##### PROPOSED BEHAVIOUR
- Directories: remove all files and subdirectories inside so that the directory contains nothing
- Files: truncate the target file, if it was empty then touch it
- Symlinks/Hardlinks: check which of the previous 2 types it is, act accordingly

State change changed if previously non-empty, ok if previously empty, failed if still non-empty.

##### EXAMPLE USAGE
```yaml
- name: Clean folders
  file: path=/var/zookeeper state=empty

- name: Truncate logs
  file: path=/var/log/local6 state=empty
```

##### WORKAROUND
How to empty a directory completely:
```yaml
- find: path=/my/dir file_type=file
  register: files

- find: path=/my/dir file_type=directory
  register: directories

- file: state=absent path={{ item.path }}
  with_items: 
    - "{{ files }}"
    - "{{ directories }}"
```

Not sure if there is a reasonable workaround for emptying _multiple_ directories.

_Copied from original issue: ansible/ansible-modules-core#902_

**Comment by erikdw** [comment]
_From @pako-pl on June 15, 2015 13:13_

+1

**Comment by erikdw** [comment]
_From @monkseal on July 4, 2015 19:38_

+1

**Comment by erikdw** [comment]
_From @maticmeznar on July 8, 2015 9:24_

I just needed this myself. +1 indeed. Please make it happen!

**Comment by erikdw** [comment]
_From @DavidGoodwin on August 27, 2015 12:23_

+1

**Comment by erikdw** [comment]
_From @lerouxju on August 27, 2015 18:29_

+1

**Comment by erikdw** [comment]
_From @gechr on September 30, 2015 7:45_

+1

**Comment by erikdw** [comment]
_From @adeelshahid on October 28, 2015 16:57_

+1

**Comment by erikdw** [comment]
_From @mutantcornholio on November 9, 2015 22:57_

+1

**Comment by erikdw** [comment]
_From @Element20Three on November 10, 2015 15:6_

+1

**Comment by erikdw** [comment]
_From @rafaelmagu on November 10, 2015 20:47_

Please click the Subscribe button on the right instead of adding `+1` as a comment.

**Comment by erikdw** [comment]
_From @mutantcornholio on November 10, 2015 22:24_

Github truly needs issue voting...

**Comment by erikdw** [comment]
_From @adeelshahid on November 11, 2015 0:13_

I need to hit the unsubscribe button with all these +1's coming into my inbox :smile:

**Comment by erikdw** [comment]
_From @smartwjw on November 18, 2015 12:3_

+1

**Comment by erikdw** [comment]
_From @tduchateau on November 23, 2015 15:22_

+1

**Comment by erikdw** [comment]
_From @tersmitten on November 23, 2015 21:1_

+1

**Comment by erikdw** [comment]
_From @thom8 on November 23, 2015 23:51_

+1

**Comment by erikdw** [comment]
_From @caljess599 on December 11, 2015 20:25_

This would be great!

**Comment by erikdw** [comment]
_From @bcoca on December 11, 2015 20:44_

remove files from dir

```yaml
- find: path=/my/dir
  register: files

- file: state=absent path={{item.path}}
  with_items: "{{files}}"
```

create empty file if it does not exist

```yaml
- copy: path=/to/file content='' force=no
```

truncate file:

```yaml
- copy: path=/to/file content='' force=yes
```

**Comment by erikdw** [comment]
_From @Nindaleth on December 12, 2015 9:25_

Thanks Brian! That should help in most cases. With that in mind:

completely empty a directory

```yaml
- find: path=/my/dir file_type=file
  register: files

- find: path=/my/dir file_type=directory
  register: directories

- file: state=absent path={{ item.path }}
  with_items: 
    - "{{ files }}"
    - "{{ directories }}"
```

Now, say I want to do the above for 10 directories, how could I go about that in a smart way? E.g. for an installed product clear any present logs, dumps, user configuration overrides, plugins, databases, downloads...

**Comment by erikdw** [comment]
_From @thom8 on December 12, 2015 9:51_

Something like this should work >

```yaml
vars:
  empty_dirs:
    - "/dir1"
    - "/dir2"
    - ...

- file: state=absent path={{ item }}
  with_items: empty_dirs

- file: state=directory path={{ item }}
  with_items: empty_dirs
```

However this feature would be nice as it doesn't require multiple tasks or separate methods for files and directories.

**Comment by erikdw** [comment]
_From @Nindaleth on December 12, 2015 12:3_

@thom8 That would discard the owner/group/access metadata, which is why I created this issue in the first place:

> It has its uses to leave the folder intact as there may have been some owner/permission changes, or alternatively it may be a mountpoint that is not even possible to delete.

**Comment by erikdw** [comment]
_From @m-emelchenkov on January 31, 2016 18:56_

+1

**Comment by erikdw** [comment]
_From @jc888 on February 3, 2016 10:26_

+1

**Comment by erikdw** [comment]
_From @st3fanK on February 11, 2016 13:47_

+1

**Comment by erikdw** [comment]
_From @j-carpentier on February 22, 2016 11:49_

+1

**Comment by erikdw** [comment]
_From @robputt796 on February 22, 2016 11:51_

+1

**Comment by erikdw** [comment]
_From @caspark on February 28, 2016 10:17_

Until #3095 gets merged (fingers crossed), here's a workaround snippet which will empty a list of directories of files without deleting the directories themselves:

```yaml
- name: Find files to purge
  find:
    path: "{{ item }}"
  register: find_results
  with_items: "{{ directories_to_purge_files_from }}"

  # ugly hack to extract paths; e.g. we want find_results.results[0].files[0].path (except for 0 to n in each case)
- name: Extract files to purge from find result
  local_action: command python -c "print '\n'.join([f['path'] for r in {{ find_results.results }} for f in r['files']])"
  register: find_results
  changed_when: false

- name: Ensure files to purge are absent
  file:
    state: absent
    path: "{{ item }}"
  with_items: "{{ find_results.stdout_lines|default([]) }}"

  # clean up just in case, since registered variables live on for the whole playbook
- name: Clean up temporary variable
  set_fact:
    find_results: ""
```

I want this as sort of a partial reset button, so I've got this as a role in `purge-files/tasks/main.yml` and it's set up in my playbook so that it requires a specific variable to be set:

```yaml
- hosts: all
  roles:
  - role: purge-files
    tags: purge
    when: do_explicit_config_purge is defined
    directories_to_purge_files_from:
      - /etc/nginx/sites-available
      - /etc/nginx/sites-enabled
      # you get the idea
```

So I can invoke it with something like `ansible-playbook myplaybook.yml --tags purge -e 'do_explicit_config_purge=true'`

(If you want to always run the "empty these directories" tasks, then you don't need `|default([])` - but I needed to add it to avoid a warning about `find_results.stdout_lines` being undefined when `not do_explicit_config_purge`; that smelt like a bug to me but seems to stem from `when` on roles being implemented as pushing the `when` down to tasks in a role, and `with_*` loops will be evaluated before `when`s.)

**Comment by erikdw** [comment]
_From @Nindaleth on February 28, 2016 10:47_

@caspark Fingers crossed indeed, I'm waiting for at least a review of similar PR #933... for a year now :-)
EDIT: Maybe you could find some inspiration in that one? You handle the "absent" state which is great, maybe you could handle the "hard"/"link" state as well, as long as their target is eiter a file or a directory.

**Comment by erikdw** [comment]
_From @Smana on March 3, 2016 9:58_

+1

**Comment by erikdw** [comment]
_From @robputt796 on March 3, 2016 11:18_

@Nindaleth yeah I noticed that your PR had been marked as requiring rebase, I am not sure what the rules of engagement are for ansible repos, whether original contributor is required to rebase or if somebody who forms a release rebases and merges as required. Anyone know if there is there any documentation surrounding this for these projects?

**Comment by erikdw** [comment]
_From @dylanmtaylor on March 27, 2016 21:45_

+1

**Comment by erikdw** [comment]
_From @geoand on March 30, 2016 11:46_

+1

**Comment by erikdw** [comment]
_From @michalkleiner on March 31, 2016 2:1_

+1

**Comment by erikdw** [comment]
_From @elnur on April 7, 2016 18:7_

:+1:

**Comment by erikdw** [comment]
_From @elnur on April 7, 2016 18:9_

Now all who +1'd this idea should go to #3095 and +1 it as well. :wink:

**Comment by erikdw** [comment]
I followed [the instructions](https://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo) to try to move the issue via the [GitHub Issue Mover](https://github-issue-mover.appspot.com/), but there were errors moving all comments: 
![screenshot 2016-12-07 11 17 49](https://cloud.githubusercontent.com/assets/1111441/20982847/03359640-bc6f-11e6-8216-e0337503dfd1.png)

**Comment by sjug** [comment]
@erikdw what does a merged PR #3095 have to do with this issue?

**Comment by Nindaleth** [comment]
@sjug Nothing, that's ID from a different (now defunct) repository. The full link should be  https://github.com/ansible/ansible-modules-core/pull/3095

**Comment by ansibot** [comment]
@erikdw Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dvershinin** [comment]
+1

**Comment by EdoBarroso** [comment]
+1

**Comment by PhilThurston** [comment]
+1

**Comment by copacetic** [comment]
+1

**Comment by abeyt** [comment]
+1

**Comment by dagwieers** [comment]
I don't mind a better solution for this intended purpose, but I don't like the fact we use the **file** module and imply a different behavior depending on whether the existing file is a regular file or a directory. What if it is a symlink, or a device, or something else ?

Furthermore, what if the file does not exist. Does it need to become and empty directory, or does it need to become an empty file ? The current design of the file-module is already ambiguous in this regard because `state=directory` when creating it. This works because that's the purpose of the file module (create files/directories/symlinks).

The file module never bothered about the content (of regular files or directories) and I don't think it is a good idea to add this.

**Update:** I updated the issue to reflect what ansibot was asking, namely to use the issue template so it can properly label this issue. Labels are important if you want to get heard, so don't ignore @ansibot. He's here to help us all.

**Comment by bcoca** [comment]
I agree with @dagwieers , i've been thinking of deprecating the file module into 4 diff ones for a while now

For this specific functionality either use the examples given above or create a 'touch' module that handles several cases of 'file creation'

**Comment by glasgow** [comment]
I'm afraid I have to disagree with @dagwieers and @bcoca insofar as the existing workarounds are cumbersome and/or don't meet the requirement as stated in the summary above.

Also, since the whole point of this feature is to empty out a file or directory _while preserving its metadata_, it seems to me that there is really no question about what to do if the object does not exist.  Since there's nothing to preserve, such a condition is an error.  Same as if one tried to "chmod" or "chown" a non-existent filesystem object.  Ditto if the object is a block or character device.

Personally I'd be ok if this only worked on directories or symlinks that were pointing at directories if enough people don't like the implied behavior.  There could be a separate state=truncate for files that fails on directories if that seems like a better way to go.

**Comment by dagwieers** [comment]
_From @raasss on October 20, 2017 13:10_

I was looking for similar solution and for me synchronize module was enough. Made empty directory on ansible host and synchronized it to remote dir. For example:
```yaml
- name: Empty remote directory
  synchronize:
    src: empty/
    dest: "{{ remote_dir }}/"
    delete: yes
    recursive: yes
```

**Comment by angystardust** [comment]
@dagwieers your solution is useful but you should be aware that the ownership and permission on the source folder will be copied over on the destination and if you don't have a 1-1 uid/gid mapping between your ansible controller host and the managed node, it can create quite a headache on you application :)

**Comment by dvershinin** [comment]
@angystardust if the rsync on the ansible machine is relatively new, then you can pass rsync option ```--chown``` to the synchronize module to specify user and group.

**Comment by dvershinin** [comment]
@angystardust if the rsync on the ansible machine is relatively new, then you can pass rsync option ```--chown``` to the synchronize module to specify user and group.

**Comment by dvershinin** [comment]
@angystardust if the rsync on the ansible machine is relatively new, then you can pass rsync option ```--chown``` to the synchronize module to specify user and group.

**Comment by raasss** [comment]
@angystardust you are totally right. I should have updated my comment with new findings. Actually rsync module behaves differently on mac os and linux regarding syncing permissions. Also, my ansible task is run with remote user who don't have root/admin rights so there is no chown problem. When run as root or user with sudo, complete task may look like.

```
- name: Empty DocumentRoot directory
  synchronize:
    src: empty/
    dest: "{{ remote_empty_dir }}/"
    delete: yes
    recursive: yes
    rsync_opts:
      - "--no-motd"
      - "--no-perms"
      - "--no-owner"
      - "--no-group"
      - "--omit-dir-times"
      - "--exclude=.gitkeep"
```
I'm excluding .gitkeep because it's there for git repo.

It would be definitely easier if file module support something like state=empty.
