### ISSUE TITLE
user module: Add the option to force password change on first login

### ISSUE THREAD

**Issue by parberge** [ansible/ansible#18917]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

user

##### SUMMARY

An option to user module which forces a password change upon next login

##### STEPS TO REPRODUCE

```yaml
user:  name=test password="hash" force_pwchange=yes
```

##### EXPECTED RESULTS

N/A

##### ACTUAL RESULTS

```
Upon logging in the user "test" with the password set, it should now prompt the user to enter a new password
```

**Comment by parberge** [comment]
_From @bcoca on February 20, 2015 15:30_

In my queue is adding password expiration, which would allow for this if you expire immediately.

**Comment by parberge** [comment]
@bcoca Cool!

**Comment by parberge** [comment]
@bcoca Isn't this what you implemented in #715?

**Comment by parberge** [comment]
_From @bcoca on November 9, 2015 18:29_

no 715 is user expiration (the account, not the password)

**Comment by parberge** [comment]
_From @bcoca on November 9, 2015 18:30_

password expiration is a bit harder as even on the same OS/distro it can be set in diff ways, also it is not always available.

**Comment by parberge** [comment]
I see.
I always use the `chage` utility. But then again, I usually only work with debian and redhat family.

**Comment by parberge** [comment]
_From @ansibot on August 1, 2016 3:38_

@grossws, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by parberge** [comment]
_From @ansibot on September 13, 2016 1:39_

@grossws, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by parberge** [comment]
_From @ansibot on October 6, 2016 16:8_

@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by parberge** [comment]
_From @guenhter on October 11, 2016 12:40_

Any update on this? Would be very nice.

**Comment by koallen** [comment]
I really hope this feature could be implemented, it will be very useful!

**Comment by parberge** [comment]
Based on the history in this ticket, I guess is should be assigned to @bcoca :wink:

**Comment by bcoca** [comment]
i have a looooooooooong list of TODO, labeling it open to any contributor that wants to add this. I might eventually get to it ...

**Comment by lwilke** [comment]
Hi,
i gave a shot at this feature and implemented it.
I you are interested, please have a look. Thank you.

https://github.com/lwilke/ansible/tree/forcepwchange

with kind regards

Lars Wilke

**Comment by ansibot** [comment]
@peerster Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by guenhter** [comment]
@ansibot 

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
user-module



##### SUMMARY
An option to user module which forces a password change upon next login


##### STEPS TO REPRODUCE
Example:

```
user: name=test password="hash" force_pwchange
```


##### EXPECTED RESULTS
Upon logging in the user "test" with the password set, it should now prompt the user to enter a new password

##### ACTUAL RESULTS
N/A

**Comment by ansibot** [comment]
cc @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alankis** [comment]
Any chance that it could be merged in a stable release soon?

**Comment by xandriaw** [comment]
Has this feature been implemented? If not, what is the best work around for now? I'm trying this but it doesn't actually make me change my password:
```
  - name: Add the user xandria
    user:
      name: xandria
      comment: Xandria Webb
      groups: wheel, nfsnobody
      password: "{{ 'password' | password_hash('sha512') }}"
      update_password: on_create
    register: xandria
  - name: Force Xandria to change password
    shell: chage -d 0 xandria
    when: xandria.changed
```

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MatthiasLohr** [comment]
This ticket is quite old... is there any known solution yet?

**Comment by dhoer** [comment]
I wanted to force password change as well on Ubuntu 16.04. The following is a work around for this limitation:

    # task
    - name: create accounts
      user:
        name: "{{ item }}"
        groups: sudo
        append: true
        shell: /bin/bash
        create_home: true
        password: "{{ accounts_password }}"
        update_password: on_create
      loop: "{{ new_accounts }}"
      register: accounts
      notify: force change password

    # handler
    - name: force change password
      command: "chage -d 0 {{ item.name }}"
      when: item.changed
      loop: "{{ accounts.results }}"

**Comment by da-edra** [comment]
I was able to get this working by first disabling the password for the user I'm creating and then expiring it:

```
- name: Ensure the bouncie user will set up a password on first login
  hosts: localhost
  become: yes
  tasks:
    - name: Disable bouncie's password
      shell:
        cmd: passwd -d bouncie
    - name: Expire bouncie's password
      shell:
        cmd: passwd -e bouncie
```
