### ISSUE TITLE
Ansible does not convert variables to their values when used with vars_files inside a playbook

### ISSUE THREAD

**Issue by ag0r** [ansible/ansible#18912]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vars_file

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### SUMMARY
Ansible does not convert variables to their values when used with vars_files inside a playbook. This functionality worked up until this morning, when it seemingly broke with no changes having been made anywhere.

##### STEPS TO REPRODUCE

```
command to run the playbook:
ansible-playbook playbooks/binder_install.yml -e "target_hosts=binder01-s1.chi group_vars_region=us group_vars_environment=staging" -i hosts

playbooks/binder_install.yml:

- name: install binder instance
  hosts: "{{ target_hosts }}"

  vars:
    - target_hosts: ''
    - group_vars_region: ''
    - group_vars_environment: ''

  vars_files:
    - ../group_vars/common/secret_vars.yml
    - ../group_vars/common/all.yml
    - ../group_vars/common/binder.yml
    - ../group_vars/{{ group_vars_region }}/{{ group_vars_environment }}/all.yml
    - ../group_vars/{{ group_vars_region }}/{{ group_vars_environment }}/binder.yml
```

##### EXPECTED RESULTS

The playbook runs successfully
##### ACTUAL RESULTS

```
PLAYBOOK: binder_install.yml ***************************************************
1 plays in playbooks/binder_install.yml
ERROR! vars file ../group_vars/{{ group_vars_region }}/{{ group_vars_environment }}/all.yml was not found```
