### ISSUE TITLE
uri: status "changed" never thrown

### ISSUE THREAD

**Issue by oupala** [ansible/ansible#18935]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

uri
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

standard
##### OS / ENVIRONMENT

debian to raspbian
##### SUMMARY

status "changed" never thrown by a uri task, even if an http call is sent
##### STEPS TO REPRODUCE

Create a task that generate an http call:

```
- name: create the database and the database schema
  uri: url=https://{{ hostname }}/{{ app_path }}/install.php
       creates={{ apps_install_path }}/database.sqlite3
       validate_certs=no
```
##### EXPECTED RESULTS

The task should be executed the first time you launch the playbook, because the file database.sqlite3 does not exist. You can see the http call in the logfile of your http server. The task status should be `ok` or `changed`, I'm not sure what would be the best solution.

On the second run of the playbook, the task shouldn't be executed, because the file database.sqlite3 does exist. You shouldn't see any http call in the logfile of your http server. The task status should be `skipped`.
##### ACTUAL RESULTS

The task is executed the first time, because the file database.sqlite3 does not exist. I can see the http call in the logfile of the http server. The task status is `ok`.

On the second run of the playbook, the file database.sqlite3 does exist. I can't see any http call in the logfile of the http server, which is normal. But the task status is `ok`.

The main problem is then the status report, which is alway `ok` whenever an http call has been sent or not.

```
TASK [myapp : create the database and the database schema] **********
ok: [myserver]
```

See also ansible/ansible-modules-core#4490

**Comment by sivel** [comment]
The `uri` module only reports `changed: True` when it is told to save the request to a file with the `dest` argument and the file is either written, or the permissions are changed on the written file.

Otherwise, you would have to use `changed_when` to evaluate a condition from the response of the URL requested.

Since we don't know what would constitute a change, it is left to the user to dictate that, such as:

```
uri:
    url: "https://{{ hostname }}/{{ app_path }}/install.php"
    creates: "{{ apps_install_path }}/database.sqlite3"
    validate_certs: no
    status_code:
        - 200
        - 201
register: response
changed_when: response.status == 201
```

The above would trigger a `changed: True` if the returned status code was 201.

**Comment by oupala** [comment]
It's not really intuitive, but it makes sense.

I tried your solution but I get an error:

```
TASK [mytask : create the database and the database schema] **********
fatal: [myhostname]: FAILED! => {"failed": true, "msg": "The conditional check 'response.status == 200' failed. The error was: error while evaluating conditional (response.status == 200): 'dict object' has no attribute 'status'"}
```

Could it be because I'm also using a retry?

```
  uri:
    url: https://{{ hostname }}/{{ app_path }}/install.php
    creates: "{{ app_install_path }}/database.sqlite3"
    validate_certs: no
    status_code:
      - 200
  register: response
  changed_when: response.status == 200
  until: response | success
  retries: 3
  delay: 10
```

I also tried without the retry options, and I still get the same error.

Does it work for you?
