### ISSUE TITLE
Idea on file module: avoid rm -fr /

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#18943]
_From @HanXHX on April 15, 2016 9:59_

##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

File
##### ANSIBLE VERSION

NA
##### CONFIGURATION

NA
##### OS / ENVIRONMENT

NA
##### SUMMARY

See: http://www.independent.co.uk/life-style/gadgets-and-tech/news/man-accidentally-deletes-his-entire-company-with-one-line-of-bad-code-a6984256.html

I think we can avoid some part this problem on file module.
##### STEPS TO REPRODUCE

```
- hosts: dummy
  vars:
    a: ""
    b: ""
  tasks:
    - file: path="{{ a }}/{{ b }}" state=absent
```
##### EXPECTED RESULTS

Fatal error!
##### ACTUAL RESULTS

It destroys all your data.

_Copied from original issue: ansible/ansible-modules-core#3443_
