### ISSUE TITLE
authorized_keys can't handle key in [normal + cert-authority] mode together

### ISSUE THREAD

**Issue by RRAlex** [ansible/ansible#18954]
##### ISSUE TYPE
- Bug Report / Feature Idea
##### COMPONENT NAME

authorized_keys
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### SUMMARY

authorized_keys can't add a key in 2 different modes, trying to add both:

ssh-ed25519 AAAAC3NzaC1lZDI1... user@box
cert-authority ssh-ed25519 AAAAC3NzaC1lZDI1... user@box

will overwrite the first with the latest...
##### STEPS TO REPRODUCE

```
# With the same key with and without cert-authority:
- name: "Add authorized_keys to {{ user }}"
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - authorized_keys/*
```
##### EXPECTED RESULTS

Both keys should end up in the authorized_keys
##### ACTUAL RESULTS

Only the last one is present.

_Copied from original issue: ansible/ansible-modules-core#5401_
