### ISSUE TITLE
Timeout: Cannot save running-config with nxos_command or save: yes in nxos_config

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#18971]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nxos_command
nxos_config
##### ANSIBLE VERSION

```
ansible 2.3.0~git20161010.03765ba
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/Roles/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- host: Ubuntu 16.04 4.4.0
- target: **NX-OSv 7.3(0)D1(1)**
##### SUMMARY

cf. title
##### STEPS TO REPRODUCE

**Inventory ./hosts**:

```
[all:vars]
nms_mgt_ip_address=172.21.100.1
[spines]
NX_OSv_Spine_11 ansible_host=172.21.100.11 
NX_OSv_Spine_12 ansible_host=172.21.100.12 
```

Structure passed as "**provider**": connections.ssh
Defined in group_vars/nx_osv/connections.yml and a symbolic link in roles/nxos_snmp/defaults points to nx_osv

```
connections
...
        nxapi:
          transport: nxapi
          host: "{{ ansible_host }}"
          # ansible_port
          port: "{{ http.port }}"
          # ansible_user
          username: admin
          password: xxxxxxxx
          # enable_secret_password
          auth_pass: xxxxxxxx
          # http or https
          use_ssl: no
          validate_certs: "{{ https.validate_certs }}"
```

**Role**: nxos_snmp:

```
- include_vars: "../defaults/{{ os_family }}/connections.yml"
...
- name: Saving the running-config
  nxos_command:
        provider: "{{ connections.nxapi }}"
        commands:
          - "copy running-config startup-config"
  register: result
```

**Playbook**:

```
- name: Configuring SNMP on NX-OS/NX-OSv
  hosts:
    - nx_osv
  roles:
    - nxos_snmp
```
##### EXPECTED RESULTS

We should be able to save the modifications.
##### ACTUAL RESULTS

```
TASK [nxos_snmp : Saving the running-config] ***********************************
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", "code": "400", "failed": true, "input": "copy running-config startup-config", "msg": "Input CLI command error", "output": {"clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", "code": "400", "input": "copy running-config startup-config", "msg": "Input CLI command error"}, "url": "http://172.21.100.12:8080/ins"}
```

No issue when configuring through the CLI:

```
NX_OSv_Spine_12# copy running-config startup-config 
[########################################] 100%
Copy complete.
NX_OSv_Spine_12# show startup-config

!Command: show startup-config
!Time: Mon Oct 10 18:12:08 2016
!Startup config saved at: Mon Oct 10 18:01:55 2016

version 7.3(0)D1(1)
power redundancy-mode redundant

```

**Comment by jean-christophe-manciot** [comment]
This issue has been originally posted in ansible//ansible-modules-core [here](https://github.com/ansible/ansible-modules-core/issues/5215#issuecomment-265543826).

**Comment by ansibot** [comment]
cc @jedelman8, @GGabriele, @privateip, @gundalow, @qalthos
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
Just pushed a commit to handle the `nxos_config` case.  In the `nxos_command` case you need to specify the command as text output (which is a little strange but it translates it correctly on the back side to adhere to nxapi properly).  The following has been tested working in the latest devel branch

```
- nxos_command:
    commands:
      - command: copy running-config startup-config
        output: text
    provider: "{{ nxapi }}"
```

**Comment by jean-christophe-manciot** [comment]
The issue is still there.
Running simple tasks with **nxos_config & nxos_command with or without double quotes for the CLI command**:
```
- name: Testing save running-config
  hosts:
    - nx_os
    - nx_osv
    - nx_osv_9k
  gather_facts: no
  tasks:
    - name: Saving configuration on remote node with nxos_config without double quotes
      nxos_config:
            provider: "{{ connections.nxapi }}"
            lines:
              - copy running-config startup-config
      register: result
      ignore_errors: yes

    - name: Saving configuration on remote node with nxos_config with double quotes
      nxos_config:
            provider: "{{ connections.nxapi }}"
            lines:
              - "copy running-config startup-config"
      register: result
      ignore_errors: yes

    - name: Saving configuration on remote node with nxos_command without double quotes
      nxos_command:
            provider: "{{ connections.nxapi }}"
            commands:
              - copy running-config startup-config
      register: result
      ignore_errors: yes

    - name: Saving configuration on remote node with nxos_command with double quotes
      nxos_command:
            provider: "{{ connections.nxapi }}"
            commands:
              - "copy running-config startup-config"
      register: result
      ignore_errors: yes
``
With **today's latest commit installed with pip, I get on NX-OSv (7.3(0)D1(1)) and on NX-OSv-9k (7.0.3.15.1)** with or without double quotes around the CLI command:
```
PLAY [Testing save running-config] ******************************************************************************************************************************************
META: ran handlers

TASK [Saving configuration on remote node with nxos_config without double quotes] *******************************************************************************************
task path: /media/actionmystique/SAMSUNG-850-Ext4/Labs/GNS3/CCNP-Cloud/CLDAUT/Cisco-Nexus-Cloud/7.3.0/Ansible/test-save.yml:35
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/nxos/nxos_config.py
<172.21.100.12> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.100.12> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [NX_OSv_Spine_12]: FAILED! => {
    "changed": false, 
    "clierror": "Syntax error while parsing  n \n\n\nCmd exec error.\n", 
    "code": "400", 
    "failed": true, 
    "input": "n", 
    "invocation": {
        "module_args": {
            "after": null, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "lines": [
                "copy running-config startup-config"
            ], 
            "match": "line", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "replace": "line", 
            "save": false, 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "msg": "Input CLI command error", 
    "output": {
        "clierror": "Syntax error while parsing  n \n\n\nCmd exec error.\n", 
        "code": "400", 
        "input": "n", 
        "msg": "Input CLI command error"
    }, 
    "url": "http://********:********/ins"
}
...ignoring

TASK [Saving configuration on remote node with nxos_config with double quotes] **********************************************************************************************
task path: /media/actionmystique/SAMSUNG-850-Ext4/Labs/GNS3/CCNP-Cloud/CLDAUT/Cisco-Nexus-Cloud/7.3.0/Ansible/test-save.yml:44
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/nxos/nxos_config.py
<172.21.100.12> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.100.12> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [NX_OSv_Spine_12]: FAILED! => {
    "changed": false, 
    "clierror": "Syntax error while parsing  n \n\n\nCmd exec error.\n", 
    "code": "400", 
    "failed": true, 
    "input": "n", 
    "invocation": {
        "module_args": {
            "after": null, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "lines": [
                "copy running-config startup-config"
            ], 
            "match": "line", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "replace": "line", 
            "save": false, 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "msg": "Input CLI command error", 
    "output": {
        "clierror": "Syntax error while parsing  n \n\n\nCmd exec error.\n", 
        "code": "400", 
        "input": "n", 
        "msg": "Input CLI command error"
    }, 
    "url": "http://********:********/ins"
}
...ignoring

TASK [Saving configuration on remote node with nxos_command without double quotes] ******************************************************************************************
task path: /media/actionmystique/SAMSUNG-850-Ext4/Labs/GNS3/CCNP-Cloud/CLDAUT/Cisco-Nexus-Cloud/7.3.0/Ansible/test-save.yml:53
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/nxos/nxos_command.py
<172.21.100.12> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.100.12> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [NX_OSv_Spine_12]: FAILED! => {
    "changed": false, 
    "clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", 
    "code": "400", 
    "failed": true, 
    "input": "copy running-config startup-config", 
    "invocation": {
        "module_args": {
            "commands": [
                "copy running-config startup-config"
            ], 
            "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "interval": 1, 
            "match": "all", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true, 
            "wait_for": null
        }
    }, 
    "msg": "Input CLI command error", 
    "output": {
        "clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", 
        "code": "400", 
        "input": "copy running-config startup-config", 
        "msg": "Input CLI command error"
    }, 
    "url": "http://********:********/ins"
}
...ignoring

TASK [Saving configuration on remote node with nxos_command with double quotes] *********************************************************************************************
task path: /media/actionmystique/SAMSUNG-850-Ext4/Labs/GNS3/CCNP-Cloud/CLDAUT/Cisco-Nexus-Cloud/7.3.0/Ansible/test-save.yml:62
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/nxos/nxos_command.py
<172.21.100.12> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.100.12> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [NX_OSv_Spine_12]: FAILED! => {
    "changed": false, 
    "clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", 
    "code": "400", 
    "failed": true, 
    "input": "copy running-config startup-config", 
    "invocation": {
        "module_args": {
            "commands": [
                "copy running-config startup-config"
            ], 
            "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "interval": 1, 
            "match": "all", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true, 
            "wait_for": null
        }
    }, 
    "msg": "Input CLI command error", 
    "output": {
        "clierror": "Syntax error while parsing 'copy running-config startup-config  | xml '\n\n\nCmd exec error.\n", 
        "code": "400", 
        "input": "copy running-config startup-config", 
        "msg": "Input CLI command error"
    }, 
    "url": "http://********:********/ins"
}
```
