### ISSUE TITLE
ios_config changes some items which do not need to be changed

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#18970]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
ansible 2.3.0 commit d9b570a
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
core modules commit ec4eebc
extras modules commit edbddf6
```
##### CONFIGURATION

inventory   = ./hosts
gathering = explicit
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles
private_role_vars = yes
log_path = /var/log/ansible.log
fact_caching = redis
fact_caching_timeout = 86400
retry_files_enabled = False
##### OS / ENVIRONMENT
- host: Ubuntu 16.04 4.4.0
- target: **CSR-1000v 16.2.2**
##### SUMMARY

There is a strange behavior when some commands are correctly applied multiple times in a row: the previous occurrences are not seen as changed.
For instance, the following tasks are always applied even though they have already been successfully run:

```
- name: Configuring location, contact & chassis ID information in new SNMPv{{ snmp.new_version }}
  ios_config:
        provider: "{{ connections.ssh }}"
        lines:
          - "snmp-server location {{ snmp.location }}"
          - "snmp-server contact {{ snmp.contact }}"
          - "snmp-server chassis-id {{ snmp.chassis_id }}"
          - "snmp-server ifindex persist"
  when: snmp.admin_state == "up"
  register: result
```

```
TASK [ios_snmp : Configuring location, contact & chassis ID information in new SNMPv2c] ***
changed: [XEv_Spine_31] => {"changed": true, "updates": ["snmp-server ifindex persist"], "warnings": []}
changed: [XEv_Spine_32] => {"changed": true, "updates": ["snmp-server ifindex persist"], "warnings": []}
```

```
- name: Configuring RO/RW community string in new IPv4/SNMPv{{ snmp.new_version }}
  ios_config:
        provider: "{{ connections.ssh }}"
        lines:
          - "snmp-server community {{ snmp.ssh.community }} {{ snmp.community_type }} {{ snmp.acl_name }}"
  when: snmp.ip_version == 'ip'
  register: result
```

```
TASK [ios_snmp : Configuring RO/RW community string in new IPv4/SNMPv2c] *******
changed: [XEv_Spine_32] => {"changed": true, "updates": ["snmp-server community xxxxxxxx ro authorized-snmp-nms"], "warnings": []}
changed: [XEv_Spine_31] => {"changed": true, "updates": ["snmp-server community xxxxxxxx ro authorized-snmp-nms"], "warnings": []}
```

```
- name: Configuring which NMS is allowed to receive the traps in new SNMPv{{ snmp.new_version }}
  ios_config:
        provider: "{{ connections.ssh }}"
        lines:
          - "snmp-server host {{ nms_mgt_ip_address }} {{ snmp.notifications_type }} version {{ snmp.new_version }} {{ snmp.ssh.community }} udp-port {{ snmp.trap_port }}"
  when: (snmp.notifications == 'all') or (snmp.notifications == 'list')
  register: result
```

```
TASK [ios_snmp : Configuring which NMS is allowed to receive the traps in new SNMPv2c] ***
changed: [XEv_Spine_31] => {"changed": true, "updates": ["snmp-server host 172.21.100.1 traps version 2c xxxxxxxx udp-port 162"], "warnings": []}
changed: [XEv_Spine_32] => {"changed": true, "updates": ["snmp-server host 172.21.100.1 traps version 2c xxxxxxxx udp-port 162"], "warnings": []}
```

Not all commands are concerned with this glitch. For instance, the second passage does not lead to a change for:

```
- name: Configuring the ACL for authorized NMS in new SNMPv{{ snmp.new_version }}
  ios_config:
        provider: "{{ connections.ssh }}"
        parents:
          - "{{ snmp.ip_version }} access-list extended {{ snmp.acl_name }}"
        lines:
          - "permit {{ snmp.ip_version }} host {{ nms_mgt_ip_address }} host {{ ansible_host }} log"
  when: snmp.admin_state == "up"
  register: result
```

```
TASK [ios_snmp : Configuring the ACL for authorized NMS in new SNMPv2c] ********
ok: [XEv_Spine_32] => {"changed": false, "warnings": []}
ok: [XEv_Spine_31] => {"changed": false, "warnings": []}
```

```
- name: Configuring the list of notifications in new SNMPv{{ snmp.new_version }}
  ios_config:
        provider: "{{ connections.ssh }}"
        lines:
          - "snmp-server enable traps {{ item }}"
  with_items:  "{{ snmp.notifications_list.traps }}"
  when: (snmp.notifications == 'list')
  register: result
```

The previous task works as expected for all the notifications I have tested, except for a few:
- cpu
- memory
- ospf
- snmp

```
TASK [ios_snmp : Configuring the list of notifications in new SNMPv2c] *********
ok: [XEv_Spine_31] => (item=bfd) => {"changed": false, "item": "bfd", "warnings": []}
ok: [XEv_Spine_32] => (item=bfd) => {"changed": false, "item": "bfd", "warnings": []}
ok: [XEv_Spine_31] => (item=bgp) => {"changed": false, "item": "bgp", "warnings": []}
ok: [XEv_Spine_32] => (item=bgp) => {"changed": false, "item": "bgp", "warnings": []}
changed: [XEv_Spine_31] => (item=cpu) => {"changed": true, "item": "cpu", "updates": ["snmp-server enable traps cpu"], "warnings": []}
changed: [XEv_Spine_32] => (item=cpu) => {"changed": true, "item": "cpu", "updates": ["snmp-server enable traps cpu"], "warnings": []}
ok: [XEv_Spine_31] => (item=eigrp) => {"changed": false, "item": "eigrp", "warnings": []}
ok: [XEv_Spine_32] => (item=eigrp) => {"changed": false, "item": "eigrp", "warnings": []}
ok: [XEv_Spine_31] => (item=event-manager) => {"changed": false, "item": "event-manager", "warnings": []}
ok: [XEv_Spine_32] => (item=event-manager) => {"changed": false, "item": "event-manager", "warnings": []}
ok: [XEv_Spine_31] => (item=firewall serverstatus) => {"changed": false, "item": "firewall serverstatus", "warnings": []}
ok: [XEv_Spine_32] => (item=firewall serverstatus) => {"changed": false, "item": "firewall serverstatus", "warnings": []}
ok: [XEv_Spine_32] => (item=ike policy add) => {"changed": false, "item": "ike policy add", "warnings": []}
ok: [XEv_Spine_31] => (item=ike policy add) => {"changed": false, "item": "ike policy add", "warnings": []}
ok: [XEv_Spine_32] => (item=ike policy delete) => {"changed": false, "item": "ike policy delete", "warnings": []}
ok: [XEv_Spine_31] => (item=ike policy delete) => {"changed": false, "item": "ike policy delete", "warnings": []}
ok: [XEv_Spine_32] => (item=ike tunnel start) => {"changed": false, "item": "ike tunnel start", "warnings": []}
ok: [XEv_Spine_31] => (item=ike tunnel start) => {"changed": false, "item": "ike tunnel start", "warnings": []}
ok: [XEv_Spine_31] => (item=ike tunnel stop) => {"changed": false, "item": "ike tunnel stop", "warnings": []}
ok: [XEv_Spine_32] => (item=ike tunnel stop) => {"changed": false, "item": "ike tunnel stop", "warnings": []}
ok: [XEv_Spine_31] => (item=ipsec cryptomap add) => {"changed": false, "item": "ipsec cryptomap add", "warnings": []}
ok: [XEv_Spine_32] => (item=ipsec cryptomap add) => {"changed": false, "item": "ipsec cryptomap add", "warnings": []}
ok: [XEv_Spine_32] => (item=ipsec cryptomap attach) => {"changed": false, "item": "ipsec cryptomap attach", "warnings": []}
ok: [XEv_Spine_31] => (item=ipsec cryptomap attach) => {"changed": false, "item": "ipsec cryptomap attach", "warnings": []}
ok: [XEv_Spine_32] => (item=ipsec cryptomap delete) => {"changed": false, "item": "ipsec cryptomap delete", "warnings": []}
ok: [XEv_Spine_31] => (item=ipsec cryptomap delete) => {"changed": false, "item": "ipsec cryptomap delete", "warnings": []}
ok: [XEv_Spine_32] => (item=ipsec cryptomap detach) => {"changed": false, "item": "ipsec cryptomap detach", "warnings": []}
ok: [XEv_Spine_31] => (item=ipsec cryptomap detach) => {"changed": false, "item": "ipsec cryptomap detach", "warnings": []}
ok: [XEv_Spine_32] => (item=ipsec too-many-sas) => {"changed": false, "item": "ipsec too-many-sas", "warnings": []}
ok: [XEv_Spine_31] => (item=ipsec too-many-sas) => {"changed": false, "item": "ipsec too-many-sas", "warnings": []}
ok: [XEv_Spine_32] => (item=ipsec tunnel start) => {"changed": false, "item": "ipsec tunnel start", "warnings": []}
ok: [XEv_Spine_31] => (item=ipsec tunnel start) => {"changed": false, "item": "ipsec tunnel start", "warnings": []}
ok: [XEv_Spine_32] => (item=ipsec tunnel stop) => {"changed": false, "item": "ipsec tunnel stop", "warnings": []}
ok: [XEv_Spine_31] => (item=ipsec tunnel stop) => {"changed": false, "item": "ipsec tunnel stop", "warnings": []}
ok: [XEv_Spine_32] => (item=ipsla) => {"changed": false, "item": "ipsla", "warnings": []}
ok: [XEv_Spine_31] => (item=ipsla) => {"changed": false, "item": "ipsla", "warnings": []}
ok: [XEv_Spine_32] => (item=isis) => {"changed": false, "item": "isis", "warnings": []}
ok: [XEv_Spine_31] => (item=isis) => {"changed": false, "item": "isis", "warnings": []}
changed: [XEv_Spine_32] => (item=memory) => {"changed": true, "item": "memory", "updates": ["snmp-server enable traps memory"], "warnings": []}
changed: [XEv_Spine_31] => (item=memory) => {"changed": true, "item": "memory", "updates": ["snmp-server enable traps memory"], "warnings": []}
changed: [XEv_Spine_32] => (item=ospf) => {"changed": true, "item": "ospf", "updates": ["snmp-server enable traps ospf"], "warnings": []}
changed: [XEv_Spine_31] => (item=ospf) => {"changed": true, "item": "ospf", "updates": ["snmp-server enable traps ospf"], "warnings": []}
ok: [XEv_Spine_32] => (item=ospfv3 errors) => {"changed": false, "item": "ospfv3 errors", "warnings": []}
ok: [XEv_Spine_31] => (item=ospfv3 errors) => {"changed": false, "item": "ospfv3 errors", "warnings": []}
ok: [XEv_Spine_32] => (item=ospfv3 rate-limit 60 150) => {"changed": false, "item": "ospfv3 rate-limit 60 150", "warnings": []}
ok: [XEv_Spine_31] => (item=ospfv3 rate-limit 60 150) => {"changed": false, "item": "ospfv3 rate-limit 60 150", "warnings": []}
ok: [XEv_Spine_32] => (item=ospfv3 state-change) => {"changed": false, "item": "ospfv3 state-change", "warnings": []}
ok: [XEv_Spine_31] => (item=ospfv3 state-change) => {"changed": false, "item": "ospfv3 state-change", "warnings": []}
ok: [XEv_Spine_32] => (item=pfr) => {"changed": false, "item": "pfr", "warnings": []}
ok: [XEv_Spine_31] => (item=pfr) => {"changed": false, "item": "pfr", "warnings": []}
ok: [XEv_Spine_32] => (item=pki) => {"changed": false, "item": "pki", "warnings": []}
ok: [XEv_Spine_31] => (item=pki) => {"changed": false, "item": "pki", "warnings": []}
changed: [XEv_Spine_32] => (item=snmp) => {"changed": true, "item": "snmp", "updates": ["snmp-server enable traps snmp"], "warnings": []}
changed: [XEv_Spine_31] => (item=snmp) => {"changed": true, "item": "snmp", "updates": ["snmp-server enable traps snmp"], "warnings": []}
ok: [XEv_Spine_32] => (item=syslog) => {"changed": false, "item": "syslog", "warnings": []}
ok: [XEv_Spine_31] => (item=syslog) => {"changed": false, "item": "syslog", "warnings": []}
ok: [XEv_Spine_32] => (item=tty) => {"changed": false, "item": "tty", "warnings": []}
ok: [XEv_Spine_31] => (item=tty) => {"changed": false, "item": "tty", "warnings": []}
```

Saving the running-config in between multiple runs does not change the situation at all.
