### ISSUE TITLE
Cannot use "name" attribute for a Block

### ISSUE THREAD

**Issue by Hexta** [ansible/ansible#18985]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Block.

##### ANSIBLE VERSION
```
2.2.0.0
```

##### SUMMARY
Ansible disallow to use "name" attribute for a Block. At the same time list of block attributes in documentation contains "name".
http://docs.ansible.com/ansible/playbooks_directives.html#block

##### STEPS TO REPRODUCE
```yaml
- name: Block name
  block:
    - name: Task name
      command: true
```

##### EXPECTED RESULTS
Playbook executed successfully.

##### ACTUAL RESULTS
Ansible prints error:
```
ERROR! 'name' is not a valid attribute for a Block
```
