### ISSUE TITLE
vmware_portgroup only updates 1 host.

### ISSUE THREAD

**Issue by Plork** [ansible/ansible#18980]
_From @Plork on October 20, 2016 11:11_

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vmware_portgroup
##### ANSIBLE VERSION

```
2.2
```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

When specifiying a vcenter server only 1 host of your datacenter is changed.
##### STEPS TO REPRODUCE

```
    - name: Add Management Network VM Portgroup
      local_action:
        module: vmware_portgroup
        hostname: vcenter_hostname
        username: vcenter_username
        password: vcenter_password
        switch_name: vswitch_name
        portgroup_name: portgroup_name
        vlan_id: vlan_id
```
##### EXPECTED RESULTS

When specifying a vcenter server you should be able to specify a cluster of all the hosts you want changed.
##### ACTUAL RESULTS

```
    host = get_all_objs(content, [vim.HostSystem])
    if not host:
        raise SystemExit("Unable to locate Physical Host.")
    host_system = host.keys()[0] <<
```

only the first item in host.keys is changed with the new portgroup

_Copied from original issue: ansible/ansible-modules-extras#3248_
