### ISSUE TITLE
When using the icmp-type switch along with ipv6 in the iptables the switch is not beeing ignored

### ISSUE THREAD

**Issue by madonius** [ansible/ansible#18989]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
iptables module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/madonius/.ansible.cfg
  configured module search path = ['/home/madonius/.ansible/library']
```

##### CONFIGURATION

```ini
[defaults]
inventory      = $HOME/.ansible/hosts
library        = $HOME/.ansible/library
remote_tmp     = $HOME/.ansible/tmp
local_tmp      = $HOME/.ansible/tmp
roles_path    = $HOME/.ansible/roles
nocows = 1
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
control_path = %(directory)s/%%C
[accelerate]
[selinux]
[colors]
```

##### OS / ENVIRONMENT

Debian Testing

##### SUMMARY

When using the iptables with ipv6 and a specified icmp type it returns an error

##### STEPS TO REPRODUCE

```yaml
- name: Permit ICMP echo requests and replies for v4 and v6
  iptables:
    chain: INPUT
    protocol: icmp
    icmp_type: "{{ item[0] }}"
    jump: ACCEPT
    ip_version: "{{ item[1] }}"
  with_nested:
  - [ 'echo-reply', 'echo-request', 'destination-unreachable' ]
  - [ 'ipv4', 'ipv6' ]
  when: ansible_version.major >= 2 and ansible_version.minor >= 2
```

```

```

##### EXPECTED RESULTS

I would expect the role to ignore the icmp-type if ipv6 is beeing used, since it is not supported by ip6tables
##### ACTUAL RESULTS

```

```
