### ISSUE TITLE
letsencrypt does not create a full-chain cert

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#18996]
_From @aioue on December 1, 2016 14:3_

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
letsencrypt

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel c064dce791) last updated 2016/10/19 15:21:39 (GMT +100)
  lib/ansible/modules/core: (detached HEAD b59b5d36e0) last updated 2016/10/19 15:22:00 (GMT +100)
  lib/ansible/modules/extras: (detached HEAD 3f77bb6857) last updated 2016/10/18 17:26:03 (GMT +100)
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
letsencrypt does not create a full-chain cert - it is missing the intermediate cert and so things like websockets and mobile browsers break.

##### EXPECTED RESULTS
Full chain cert created
or
cert, intermediate files created

##### ACTUAL RESULTS
cert, with no intermediate chain cert created.

_Copied from original issue: ansible/ansible-modules-extras#3607_

**Comment by aioue** [comment]
_From @ansibot on December 1, 2016 14:24_


@mgruener ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aioue** [comment]
_From @ansibot on December 7, 2016 15:49_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by 8w** [comment]
As a workaround I'm currently doing a `get_url` to https://letsencrypt.org/certs/lets-encrypt-x3-cross-signed.pem, `slurp`ing that and the signed cert into variables and then creating the full-chain cert using `copy` with `contents` of those two variables (signed cert first followed by the intermediate cert).  It's a bit of a mess but it works.


The [acme spec](https://github.com/ietf-wg-acme/acme/blob/master/draft-ietf-acme-acme.md) says that a link to the matching intermediate certificates is provided in the head of the certificate download GET resource:

> The "up" link relation is used with challenge resources to indicate the authorization resource to which a challenge belongs. It is also used from certificate resources to indicate a resource from which the client may fetch a chain of CA certificates that could be used to validate the certificate in the original resource.

It would be great if the module could download the intermediate certs using that link.

I do think the option to save the intermediate certs out to a separate file would useful too - you need that intermediate cert if you are going to use OCSP stapling (`SSLCACertificateFile` in Apache or `ssl_trusted_certificate` in nginx).

Having the module download/ update the intermediate cert when it pulls a new certificate would have the benefit of always being sure that we have the latest intermediate cert, in case letsencrypt update it.

**Comment by coofercat** [comment]
I suspect the (proper) fix for this is imminent, but I wanted a solution, so using @8w's suggestions, I added these steps to my role:

```
- name: WORKAROUND - download intermediate certs to server
  get_url: url=https://letsencrypt.org/certs/{{ item }} dest=/etc/ssl/letsencrypt/{{ item }} mode=0444
  with_items:
  - lets-encrypt-x3-cross-signed.pem
  - lets-encrypt-x4-cross-signed.pem

- name: WORKAROUND - make a fullchain cert from components
  shell: cat {{ domain }}.key lets-encrypt-x3-cross-signed.pem lets-encrypt-x4-cross-signed.pem {{ domain }}.csr > {{ domain }}.chain.pem
  args:
    chdir: /etc/ssl/letsencrypt
  when: challenge|changed
```
The resulting chaincert seems to work well enough, although YMMV.
