### ISSUE TITLE
service module fails on updated trusty

### ISSUE THREAD

**Issue by logan2211** [ansible/ansible#19030]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

service module, ansible_service_mgr

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Updated Ubuntu 14.04.5 LTS

##### SUMMARY

After fully updating trusty, ansible seems to detect the init system as being systemd based and things (service module, ansible_service_mgr fact, etc.) fail.

##### STEPS TO REPRODUCE

Built trusty LXC container, upgrade all services (shown here http://cdn.pasteraw.com/c8ajufdx6fo3d8kyiaf76rh19h02cxo) and then run ansible plays.

```
- hosts: unbound
  gather_facts: no
  tasks:
    - name: check lsb_release
      command: lsb_release -a
      register: lsb_rel
    - debug:
        msg: "{{ lsb_rel }}"
    - name: check init
      command: cat /proc/1/comm
      register: init_sys
    - debug:
        msg: "{{ init_sys }}"
    - debug:
        msg: "{{ ansible_service_mgr }}"
    - name: Restart unbound
      service:
        name: unbound
        state: restarted
```

##### ACTUAL RESULTS

```
PLAY [unbound] *****************************************************************

TASK [check lsb_release] *******************************************************
changed: [aio1_unbound_container-bf5686a6]

TASK [debug] *******************************************************************
ok: [aio1_unbound_container-bf5686a6] => {
    "msg": {
        "changed": true,
        "cmd": [
            "lsb_release",
            "-a"
        ],
        "delta": "0:00:00.074606",
        "end": "2016-12-09 02:16:59.911433",
        "rc": 0,
        "start": "2016-12-09 02:16:59.836827",
        "stderr": "No LSB modules are available.",
        "stdout": "Distributor ID:\tUbuntu\nDescription:\tUbuntu 14.04.5 LTS\nRelease:\t14.04\nCodename:\ttrusty",
        "stdout_lines": [
            "Distributor ID:\tUbuntu",
            "Description:\tUbuntu 14.04.5 LTS",
            "Release:\t14.04",
            "Codename:\ttrusty"
        ],
        "warnings": []
    }
}

TASK [check init] **************************************************************
changed: [aio1_unbound_container-bf5686a6]

TASK [debug] *******************************************************************
ok: [aio1_unbound_container-bf5686a6] => {
    "msg": {
        "changed": true,
        "cmd": [
            "cat",
            "/proc/1/comm"
        ],
        "delta": "0:00:00.003578",
        "end": "2016-12-09 02:17:01.761662",
        "rc": 0,
        "start": "2016-12-09 02:17:01.758084",
        "stderr": "",
        "stdout": "init",
        "stdout_lines": [
            "init"
        ],
        "warnings": []
    }
}

TASK [debug] *******************************************************************
ok: [aio1_unbound_container-bf5686a6] => {
    "msg": "systemd"
}

TASK [Restart unbound] *********************************************************
fatal: [aio1_unbound_container-bf5686a6]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to issue method call: Unit unbound.service not loaded.\nFailed to issue method call: Unit unbound.service failed to load: No such file or directory. See system logs and 'systemctl status unbound.service' for details.\n"}
```

**Comment by logan2211** [comment]
```
root@aio1-unbound-container-bf5686a6:/# stat /run/systemd/system
  File: ‘/run/systemd/system’
  Size: 40        	Blocks: 0          IO Block: 4096   directory
Device: 44h/68d	Inode: 48          Links: 2
Access: (0755/drwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-12-09 01:12:46.941631000 +0000
Modify: 2016-12-09 01:12:46.753631000 +0000
Change: 2016-12-09 01:12:46.753631000 +0000
 Birth: -
root@aio1-unbound-container-bf5686a6:/# apt-cache policy systemd
systemd:
  Installed: 204-5ubuntu20.20
  Candidate: 204-5ubuntu20.20
  Version table:
 *** 204-5ubuntu20.20 0
        500 http://mirror.lstn.net/ubuntu/ trusty-updates/main amd64 Packages
        100 /var/lib/dpkg/status
```

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py#L439-L441
If I remove `/run/systemd/system/` from the list, the service module works correctly again.

**Comment by cloudnull** [comment]
Looks like this also effects the systemd check also found in facts.py  [ https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/facts.py#L506-L515 ]

**Comment by odyssey4me** [comment]
@jimi-c I'm not sure how we can appropriately raise awareness for this, but for anyone doing code paths catering for upstart vs systemd (and perhaps others) this bug will catch them now with thanks to Ubuntu. The issue affects Ansible 2.1.1.0 onwards, but may also affect older versions.

**Comment by bcoca** [comment]
So `/run/systemd/system/` should only exist on systems that are running systemd, the problem with systemd and containers is that they 'lie' as they tend to replace/remove the init process which sometimes means the init management tools stop working. If it happened every time it would be easy to deal with it, but some containers are setup to actually run systemd.

If we remove that line, many systems will stop working as they legitimately run systemd and this is the only way we discover that fact. We need to find a way to 'disprove' systemd on these containers, I have not been able to find one yet.

**Comment by alikins** [comment]
Does the patch at https://github.com/ansible/ansible/pull/19034 work for folks that are seeing this issue?

**Comment by bcoca** [comment]
@alikins no, it might fix this issue, but that patch is what our code used to look like but it broke in many other systems.

**Comment by bcoca** [comment]
Just to confirm, I upgraded my trusty (14.04.5 LTS) and i don't get this file since I am running upstart.

You on the other hand, do have systemd installed as you noted in:
```
systemd:
  Installed: 204-5ubuntu20.20
```
and in use, since it creates that file.

After I install systemd I can reproduce your error as that version of systemd does not seem to be able to handle init scripts and there is no unbound service file. Similar bugs are present in debian (fixed in systemd/220 but was never backported).

So the detection seems to be working correctly, systemd is installed and running and is the 'service manager' for that host. It is supposed to handle init scripts for backwards compatibility but that seems to be broken in this version of systemd.

Changing the detection will break the other services, best case scenario its just them existing outside of systemd as 'unmanaged' services. 

At this point I'm not sure there is a good solution going forward,  short term, creating a service file for these cases seems to be the quickest fix.

For the long term, I'm currently creating upstart and sysvinit 'modules' splitting them out of the current 'service' one (systemd already exists) leaving service as an action plugin that relies on the fact detection, this detection can be overridden with use=<specific module>, but the modules need to exist.

**Comment by kr4ut** [comment]
Nasty thing is that yes an upstart based release shouldn't have `systemd` installed at all, but the vendor does even enforces that when using their `snapd` backport. So basically using Snap apps on Ubuntu 14.04 breaks Ansible's management of services there (no discussion on Snap itself please) :face_with_head_bandage:

While we banging towards trusty's EOL it would be lovely if we could work around such weird situation on distributions in general with Ansible. Just tried the following on `v2.7.4` but unfortunately without the ability to override the wrong choice when systemd is installed but not the service manager:
```
vars:
  ansible_service_mgr: upstart
...
service:
  use: upstart
...
service:
  use: service
```
@bcoca Any inspiring idea how to currently workaround with such double-headed creatures from the server zombie zoo before they will hopefully rest soon in peace at /dev/null?
