### ISSUE TITLE
Calling handlers with parameters does not work in many cases

### ISSUE THREAD

**Issue by Stehsegler** [ansible/ansible#19050]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

N/A

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

nothing special

##### OS / ENVIRONMENT

run from CentOS 7

##### SUMMARY

Calling handlers with parameters in many cases fails because of them not being found by ansible, depending on the way the variable you try to pass was originally set.

##### STEPS TO REPRODUCE

1. Get [this gist](https://gist.github.com/j0057/5af0ac913a203a5b94ef)
2. Run the playbook again to verify the handler is called as expected (one time with parameter `a`, one time with parameter `b`)
3. Replace `name: a` with `name: "{{ inventory_hostname }}"` in `site.yml`
4. Run the playbook again

##### EXPECTED RESULTS

Handler is called one time with parameter `localhost`, one time with parameter `b`.

##### ACTUAL RESULTS

Notifying the handler with parameter `localhost` fails with the following message:

```
ERROR! The requested handler 'something happened to localhost' was not found in either the main handlers list nor in the listening handlers list
```

This also happens under many other circumstances, for example, in the following single-file playbook notifying the handler fails in all four cases:
```
---
- hosts: localhost
  vars:
    static_var: static
    dynamic_var: "{{ inventory_hostname }}"
  tasks:
    - name: set fact
      set_fact: set_fact_var=set_fact
    - name: trigger handler for inventory_var
      command: /bin/true
      notify: handle {{ inventory_var }}
    - name: trigger handler for static_var
      command: /bin/true
      notify: handle {{ static_var }}
    - name: trigger handler for dynamic_var
      command: /bin/true
      notify: handle {{ dynamic_var }}
    - name: trigger handler for set_fact_var
      command: /bin/true
      notify: handle {{ set_fact_var }}
  handlers:
    - name: handle {{ event }}
      debug: msg="{{ event }}"
```
Corresponding inventory file:
```
localhost ansible_connection=local inventory_var=inventory
```

**Comment by abcfy2** [comment]
Same issue here, also in ansible 2.2:
```yaml
---
- hosts: all
  gather_facts: False
  tasks:
    - name: "Copy files to dest: src={{item.src}} dst={{item.dst}}"
      copy:
        src: "{{item.src}}"
        dest: "{{item.dst}}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - src: "../build/libs/backstage-service-{{service_version}}.war"
          dst: "{{service_install_dir}}"
      notify:
        - "restart {{service_name}}"

  handlers:
    - name: "restart {{service_name}}"
      service:
        name: "{{service_name}}"
        state: restarted
```

Will raise this error:

    ERROR! The requested handler 'restart backstage' was not found in either the main handlers list nor in the listening handlers list

Any updates for this issue?

**Comment by liquidat** [comment]
I can reproduce the problem with ansible 2.3.

**Comment by liquidat** [comment]
I can reproduce the problem with current Ansible stable:
```
$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

+label affects_2.3

**Comment by samdoran** [comment]
This is working as designed. Handler _names_ are not templated, but you can use variables for values in handlers.

```yaml
- hosts: all
  gather_facts: False
  tasks:
    - name: "Copy files to dest: src={{item.src}} dst={{item.dst}}"
      copy:
        src: "{{item.src}}"
        dest: "{{item.dst}}"
        owner: root
        group: root
        mode: '0644'
      with_items:
        - src: "../build/libs/backstage-service-{{service_version}}.war"
          dst: "{{service_install_dir}}"
      notify:
        - "restart service"

  handlers:
    - name: "restart service"
      service:
        name: "{{service_name}}"
        state: restarted
```
