### ISSUE TITLE
git - in Ansible 2.1 switching a shallow clone from tag to branch fails

### ISSUE THREAD

**Issue by adamchainz** [ansible/ansible#19074]
_From @adamchainz on June 1, 2016 14:54_

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

git module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Vanilla
##### OS / ENVIRONMENT

Happens on both OS X and Ubuntu with different versions of git (1.8 and 1.9)
##### SUMMARY

Updating a shallow clone based on a tag to one based on a branch fails
##### STEPS TO REPRODUCE

Run this with `ansible-playbook -i 127.0.0.1, ~/tmp/test.yml; rm /tmp/testclone`

```
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: initial clone from tag
      git:
        repo: git@github.com:adamchainz/nose-randomly.git
        dest: /tmp/testclone
        version: 1.2.0
        depth: 1

    - name: update to branch
      git:
        repo: git@github.com:adamchainz/nose-randomly.git
        dest: /tmp/testclone
        version: master
        depth: 1
```
##### EXPECTED RESULTS

On Ansible 2.0.2.0, it works fine:

```
PLAY [127.0.0.1] ***************************************************************

TASK [initial clone from tag] **************************************************
changed: [127.0.0.1]

TASK [update to branch] ********************************************************
changed: [127.0.0.1]

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=2    unreachable=0    failed=0
```
##### ACTUAL RESULTS

On Ansible 2.1.0.0, I get:

```
PLAY [127.0.0.1] ***************************************************************

TASK [initial clone from tag] **************************************************
changed: [127.0.0.1]

TASK [update to branch] ********************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/tmp/testclone/.git/refs/remotes/origin/HEAD'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/_z/wpddpg7d5hd6fd2zjn_fct7m0000gn/T/ansible_vBeq0g/ansible_module_git.py\", line 877, in <module>\n    main()\n  File \"/var/folders/_z/wpddpg7d5hd6fd2zjn_fct7m0000gn/T/ansible_vBeq0g/ansible_module_git.py\", line 832, in main\n    fetch(git_path, module, repo, dest, version, remote, depth, bare, refspec)\n  File \"/var/folders/_z/wpddpg7d5hd6fd2zjn_fct7m0000gn/T/ansible_vBeq0g/ansible_module_git.py\", line 530, in fetch\n    currenthead = get_head_branch(git_path, module, dest, remote)\n  File \"/var/folders/_z/wpddpg7d5hd6fd2zjn_fct7m0000gn/T/ansible_vBeq0g/ansible_module_git.py\", line 498, in get_head_branch\n    f = open(os.path.join(repo_path, 'refs', 'remotes', remote, 'HEAD'))\nIOError: [Errno 2] No such file or directory: '/tmp/testclone/.git/refs/remotes/origin/HEAD'\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/Users/adamj/tmp/test.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=1
```

It looks like `fetch` has started assuming that if we're updating to a remote branch, we must currently be on a branch, as per lines 530-532:

``` py
        elif is_remote_branch(git_path, module, dest, repo, version):
            currenthead = get_head_branch(git_path, module, dest, remote)
            if currenthead != version:
```

or that `get_head_branch` should work, but doesn't, when we're on a tag. N.B. this is the contents of the `.git` directory after the clone from tag:

```
$ tree /tmp/testclone/.git/refs
/tmp/testclone/.git/refs
├── heads
└── tags

2 directories, 0 files
```

_Copied from original issue: ansible/ansible-modules-core#3817_
