### ISSUE TITLE
Run a handler immediately

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#19075]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Core

##### SUMMARY
Sometimes it's useful to run a specific handler immediately after it was notified, without using `- meta: flush_handlers` to run all queued handlers, which isn't always desirable. A good example is when you are working with `systemd` unit files. After changing a unit file you always need to run `systemctl daemon-reload`, so you always have to use something like this:
```yml
- name: task which updates a unit file
  #...
  register: daemon_reload

- command: systemctl daemon-reload
  when: daemon_reload|changed
```
This is very inconvenient and repetitive, because you need to repeat the same exact register/command every time. It would be easier if you could define a handler, e.g:
```yml
- name: daemon-reload
  command: systemctl daemon-reload
```
and just call that handler to be executed immediately, e.g.:
```yml
- name: task which updates a unit file
  #...
  notify_now: daemon-reload
```
I used a `notify_now` keyword, but it could be named differently, or with an even different syntax, but just something which would run this handler immediately after the task which updates the unit file. The handler could even be defined in some role which could be put as a dependency to other roles.
