### ISSUE TITLE
ovirt_vms_facts fails win get_dict_of_struct() got an unexpected keyword argument 'connection'

### ISSUE THREAD

**Issue by drehelis** [ansible/ansible#19082]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

ovirt_modules/ovirt_vms_facts

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/ovirt_modules']
```

##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core) 
Linux hostname 3.10.0-327.28.3.el7.x86_64 #1 SMP Thu Aug 18 19:05:49 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

Following below example: https://github.com/machacekondra/ovirt-tests/blob/master/examples/vm/list.yml
Getting the error:
```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Z3XwZM/ansible_module_ovirt_vms_facts.py", line 94, in main
    ) for c in vms
TypeError: get_dict_of_struct() got an unexpected keyword argument 'connection'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "pattern": "", 
            "poll_interval": 3, 
            "timeout": 180, 
            "wait": true
        }, 
        "module_name": "ovirt_vms_facts"
    }, 
    "msg": "get_dict_of_struct() got an unexpected keyword argument 'connection'"
}
```
##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local
  vars_files:
    - ./vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Gather facts
    ovirt_vms_facts:
      auth: "{{ ovirt_auth }}"
```

##### ACTUAL RESULTS

```

```
@machacekondra can you take a look please?
