### ISSUE TITLE
vmware_guest fails on basic facts gathering

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#19080]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.2 with latest vmware_guest module

##### SUMMARY

When using the following playbook:
```yaml
- hosts: all
  gather_facts: no
  tasks:
  - name: Gather the VM facts
    vmware_guest:
      validate_certs: no
      hostname: '{{ vcenter_ipaddress }}'
      username: '{{ vcenter_username }}'
      password: '{{ vcenter_password }}'
      name: '{{ inventory_hostname_short }}'
    register: facts
    connection: local
  - debug:
      var: facts
```

The VM we are using does not exist, we want to check whether it exists.
It takes a long time and finally fails with:
```
[user@system ~]$ ansible-playbook vmware-test.yml -l system
 
PLAY [localhost] ***************************************************************
 
TASK [setup] *******************************************************************
ok: [localhost]
 
TASK [Gather the VM facts] *****************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'template'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_DfOLFw/ansible_module_vmware_guest.py\", line 1349, in <module>\n    main()\n  File \"/tmp/ansible_DfOLFw/ansible_module_vmware_guest.py\", line 1327, in main\n    wait_for_ip=module.params['wait_for_ip_address']\n  File \"/tmp/ansible_DfOLFw/ansible_module_vmware_guest.py\", line 651, in deploy_template\n    template = get_obj(self.content, [vim.VirtualMachine], self.params['template'])\nKeyError: 'template'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
 
PLAY RECAP *********************************************************************
system                    : ok=1    changed=0    unreachable=0    failed=1
```
