### ISSUE TITLE
Using `include_role` along with `with_items` and `async` for parallelised execution

### ISSUE THREAD

**Issue by Rylon** [ansible/ansible#19083]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`include_role`

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When using `include_role` and `with_items` along with the `async` plugin, in an attempt to parallelise multiple includes of a parameterised role, execution continues in serial, and the async feature doesn't seem to work.

We have a range of parameterised roles which we can include multiple times, with different parameters, such as a user management role, which we can include multiple times with different user data each time. We were trying to use the async role to parallelise this, to speed up playbook execution time.

Is what we're trying to do possible here? Or have we stumbled upon a bug? Thanks :) 

##### STEPS TO REPRODUCE

Create a playbook with the following tasks:

```
tasks:
  - name: Include a parameterised role
    include_role:
      name: my_role_name
    vars:
      my_role_var_one: value
      my_role_var_two: "{{item}}"
    with_items:
      - item1
      - item2
    register: my_async_job
    async: 300
    poll: 0

  - name: Waiting for role includes to complete
    async_status: jid={{ item.ansible_job_id }}
    register: my_async_job_status
    until: my_async_job_status.finished
    retries: 3
    with_items: my_async_job.results
```

##### EXPECTED RESULTS

I would expect the multiple include_roles to begin executing in parallel, and the playbook to start waiting on the `async_status` task until all iterations of the `include_role` were complete.

##### ACTUAL RESULTS

Execution continued in serial, including the role multiple times, once for each item listed in `with_items`.
