### ISSUE TITLE
include_role: inside a block: does not work with when: (even for non-string condition)

### ISSUE THREAD

**Issue by joaocc** [ansible/ansible#19085]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role:

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
include_role: inside a block: does not work with when: crashes when starting to execute the included role.
If I remove the external when: clause, everything works fine.

##### STEPS TO REPRODUCE

calling script:
```
- block:
    - include_role:
          name: "ansible-lib--infra/v1/ez123--moodle-moosh"
          static:  yes
          private: yes
      when:
        "{{ (zzz_moodle__skip__moosh is not defined) or (not (zzz_moodle__skip__moosh |bool)) }}"
```
on the included role, under tasks/main.yml
```
- name: "check if moosh is already installed (1)"
  command: "./moosh --help"
  args:
    chdir: "{{ ez123_moosh__bin_dir }}"
  register: _X_moosh_ver_0
  changed_when: false
  failed_when: false
```
##### EXPECTED RESULTS
There should be no error/crash.

##### ACTUAL RESULTS
```
TASK [ansible-lib--infra/v1/ez123--moodle-moosh : check if moosh is already installed (1)] ***
task path: /etc/ansible/roles.glx/ansible-lib--infra/v1/ez123--moodle-moosh/tasks/main.yml:4
fatal: [host000000]: FAILED! => {
    "failed": true,
    "msg": "The conditional check '{' failed. The error was: template error while templating string: unexpected '%'. String: {% if { %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/opt/src/ansible/dom/roles/dom-roles/func/tasks/main.yml': line 4, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n- block:\n    - include_role:\n      ^ here\n"
}```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

By forcing it static, you are ignoring the when condition for the include_role task itself, so it gets inherited by the included tasks. Works as expected

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by bcoca** [comment]
also, don't use {{ }} in when, it is already interpolated

**Comment by joaocc** [comment]
Hi. 
Thanks for your update. 
This also happens regardless of:
- static is not explicitly defined
- static is defined to false
- any of the above with "plain" when clause

On the "when" clause, since 2.1, I prefer to always explicit interpolate (this way, I never forget).
However, your comment on the when led me to find something curious...

plain "when"
```
{
    "failed": true,
    "msg": "The conditional check '{' failed. The error was: template error while templating string: unexpected '%'. String: {% if { %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/opt/src/ansible/dom/roles/dom-roles/func/tasks/main.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - include_role:\n      ^ here\n"
}
```

explicit interpolated "when"
```
{
    "failed": true,
    "msg": "The conditional check '(' failed. The error was: template error while templating string: unexpected '%'. String: {% if ( %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/opt/src/ansible/dom/roles/dom-roles/func/tasks/main.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - include_role:\n      ^ here\n"
}```

The messages are different... It seems it is trying to evaluate the initial char, either the parenthesis or the bracket.

**Comment by joaocc** [comment]
Also, if I use the following, it works.
```
- block:
    - include_role:
        ...
      when: false
```
