### ISSUE TITLE
docker_container sends volume to docker API erroneously

### ISSUE THREAD

**Issue by rsanr** [ansible/ansible#19103]
_From @rsanr on September 22, 2016 18:1_

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 3874e653c1)
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

docker_container erroneously sends `volume` in addition to `binds` to docker API during create container call.  
##### STEPS TO REPRODUCE

```
- name: assert state of my container
  docker_container:
    name: mc
    image: "my_container:1.0"
    command: "execute"
    state: started
    restart_policy: always
    exposed_ports:
    - 12345
    network_mode: host
    detach: True
    volumes:
    - "/a/b:/a/b"
    log_driver: "json-file"
    log_options:
      max-size: "10m"
      max-file: "10"
```

##### EXPECTED RESULTS

Docker daemon logs w/ debug level

```
DEBU[0111] Calling POST /v1.23/containers/create?name=mc 
DEBU[0111] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["execute"],"Env":[],"ExposedPorts":{"12345/tcp":{}},"HostConfig":{"Binds":["/a/b:/a/b:rw"],"LogConfig":{"Config":{"max-file":"10","max-size":"10m"},"Type":"json-file"},"Memory":0,"NetworkMode":"host","ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":null,"Name":"always"}},"Image":"my_container:1.0","NetworkDisabled":false,"OpenStdin":false,"StdinOnce":false,"Tty":false,"Volumes":{}} 
```
##### ACTUAL RESULTS

```
DEBU[0111] Calling POST /v1.23/containers/create?name=mc 
DEBU[0111] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["execute"],"Env":[],"ExposedPorts":{"12345/tcp":{}},"HostConfig":{"Binds":["/a/b:/a/b:rw"],"LogConfig":{"Config":{"max-file":"10","max-size":"10m"},"Type":"json-file"},"Memory":0,"NetworkMode":"host","ReadonlyRootfs":false,"RestartPolicy":{"MaximumRetryCount":null,"Name":"always"}},"Image":"my_container:1.0","NetworkDisabled":false,"OpenStdin":false,"StdinOnce":false,"Tty":false,"Volumes":{"/a/b":{}}} 
```

When the same task (adapted for) is run using the deprecated docker module we see the volume is not sent:

```
DEBU[0328] Calling POST /v1.22/containers/create?name=mc 
DEBU[0328] form data: {"AttachStderr":false,"AttachStdin":false,"AttachStdout":false,"Cmd":["execute"],"CpuShares":0,"Env":[],"ExposedPorts":{"12345/tcp":{}},"HostConfig":{"Binds":["/a/b:/a/b:rw"],"LogConfig":{"Config":{"max-file":"10","max-size":"10m"},"Type":"json-file"},"Memory":0,"NetworkMode":"host","RestartPolicy":{"Name":"always"}},"Image":"my_container:1.0","Labels":{},"NetworkDisabled":false,"OpenStdin":false,"StdinOnce":false,"Tty":false,"Volumes":{}} 
```

Note pinning API version to 1.22 on `docker_container` made no difference.  It still ends up sending volume as part of the request.   Based on the thread below it seems that volume shouldn't be sent in this scenario:
https://github.com/docker/docker/issues/2949#issuecomment-230883544

If my understating is accurate can this be looked into?  Thanks.

_Copied from original issue: ansible/ansible-modules-core#4974_

**Comment by rsanr** [comment]
_From @ansibot on September 22, 2016 18:14_



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rsanr** [comment]
_From @chouseknecht on September 27, 2016 1:59_

needs_info

I'm not clear on what the actual issue is. Your example playbook task is mounting a host directory to a container directory, and when I do that in an actual playbook it works just fine. It also produces the same results as `docker run`. Below are the results of my testing.

Do you have an actual error, traceback? 
Can you provide a playbook task that actually fails?

Here's my test playbook:

```
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - docker_container:
        name: mc
        image: busybox
        command: sleep 1d
        volumes:
        - /home/vagrant/data:/data:rw
```

It produces a container with the following binds:

```
"HostConfig": {
    "Binds": [
        "/home/vagrant/data:/data:rw"
    ],
```

...and the following mounts:

```
"Mounts": [
    {
        "Source": "/home/vagrant/data",
        "Destination": "/data",
        "Mode": "rw",
        "RW": true,
        "Propagation": "rprivate"
    }
],
```

If I run the following `docker run` command, which is the same as the above playbook task, it produces:

```
$ docker run -d -v /home/vagrant/data:data:rw --name mc2 busybox sleep 1d
```

Here are the binds:

```
"HostConfig": {
    "Binds": [
        "/home/vagrant/data:/data:rw"
    ],
```

...and the volumes:

```
"Mounts": [
    {
        "Source": "/home/vagrant/data",
        "Destination": "/data",
        "Mode": "rw",
        "RW": true,
        "Propagation": "rprivate"
     }
],
```
