### ISSUE TITLE
ec2_group requires "description" to delete SG

### ISSUE THREAD

**Issue by ralfbergs** [ansible/ansible#19117]
_From @ralfbergs on August 15, 2016 18:22_

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_group
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

`ec2_group` requires `description` parameter to be specified to delete a security group.

This doesn't make sense, IMHO, and it seems to contradict to [what Boto requires](http://boto.cloudhackers.com/en/latest/ref/ec2.html#boto.ec2.connection.EC2Connection.delete_security_group).
##### STEPS TO REPRODUCE

Tried to execute the following task:

```
    - name: "Destroy Security Group for FE trusted ELB"
      ec2_group:
        state: absent
        region: "{{ region }}"
        name: "{{ owner }}_sg_{{ env }}_fe_elb_trst"
```

##### EXPECTED RESULTS

Expected that the above task would execute without error.
##### ACTUAL RESULTS

The above task raised an error:

```
missing required arguments: description
```

_Copied from original issue: ansible/ansible-modules-core#4427_
