### ISSUE TITLE
ec2_elb_lb: Ansible didn't detect "scheme" change

### ISSUE THREAD

**Issue by ralfbergs** [ansible/ansible#19116]
_From @ralfbergs on August 12, 2016 20:44_

##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

ec2_elb_lb
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/rabe/Documents/Projects/IoT/Design/Devel/Env-Setup/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Changed the scheme from `internal` to `internet-facing`, and Ansible didn't detect that it had to change the state, i. e. perform some work.
##### STEPS TO REPRODUCE

Originally had the following:

```
    - name: Create Elastic Load Balancer for frontend
      ec2_elb_lb:
        name: "{{ owner }}-elb-{{ env }}-fe"
        region: "{{ region }}"
        subnets:
          - "{{ mgmt_subnet_fe_1 }}"
          - "{{ mgmt_subnet_fe_2 }}"
        state: present
        scheme: internal
        cross_az_load_balancing: yes
        listeners:
          - protocol: http
            instance_protocol: http
            load_balancer_port: 80
            instance_port: 80
        health_check:
          ping_protocol: http # options are http, https, ssl, tcp
          ping_port: 80
          ping_path: "/index.html" # not required for tcp or ssl
          response_timeout: 5 # seconds
          interval: 30 # seconds
          unhealthy_threshold: 2
          healthy_threshold: 10
        instance_ids:
          - "{{ mgmt_i_fe_1.tagged_instances[0].id }}"
          - "{{ mgmt_i_fe_2.tagged_instances[0].id }}"
        tags:
          Name: "{{ owner }}_elb_{{ env }}_fe"
          Env: "{{ owner }}_{{ env }}"
          Tier: "{{ owner }}_{{ env }}_frontend"
```

Changed the above "scheme" line as follows:

```
        scheme: internet-facing
```

##### EXPECTED RESULTS

I expected that Ansible noticed it had to change the ELB config.
##### ACTUAL RESULTS

Ansible did _not_ notice it got work to do. I had to manually remove the ELB and re-run the playbook.

_Copied from original issue: ansible/ansible-modules-core#4414_
