### ISSUE TITLE
elasticache misses "Description" parameter

### ISSUE THREAD

**Issue by ralfbergs** [ansible/ansible#19121]
_From @ralfbergs on October 28, 2016 21:40_

##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

elasticache
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

From the AWS Console I can set a "Description" -- via this Ansible module I can't. So I would suggest to add this parameter.
##### STEPS TO REPRODUCE

```
- name: "mgmt::db Create ElastiCache Redis"
  elasticache:
    state: present
    region: "{{ region }}"
    vpc_id: "{{ mgmt_vpc.id }}"
    # Name must be <= 20 chars
    name: "{{ owner }}-ec-{{ env }}-db-red"
    description: "ElastiCache Redis for Sentry"
    node_type: "cache.m4.large"
    num_nodes: 1 # no replicas
    engine: redis
    cache_engine_version: "3.2.4"
    cache_port: 6379
    cache_parameter_group: "default.redis3.2"
    cache_subnet_group: "{{ owner }}-sngrp-{{ env }}-db-redis"
    security_group_ids:
      - "{{ mgmt_sg_redis.group_id }}"
  register: mgmt_ec_redis
```

##### EXPECTED RESULTS

I expected that the module call would be run without any errors.
##### ACTUAL RESULTS

Got the following err msg:

```
unsupported parameter for module: description
```

_Copied from original issue: ansible/ansible-modules-core#5429_
