### ISSUE TITLE
os_security_group_rule is unable to add a rule in default security group

### ISSUE THREAD

**Issue by sdubrul** [ansible/ansible#19124]
_From @sdubrul on December 8, 2016 10:49_

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
os_security_group_rule

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT
macOS 10.12.1

##### SUMMARY

When logged in as admin and trying to update the default security group rules for this tenant the command fails as there are multiple security groups that are called default. Security group default is found in the admin and services tenant.

##### STEPS TO REPRODUCE

```
# clouds.yml
clouds:
  mycloud:
    auth:
      auth_url: https://mycloud:5000/v2.0
      username: admin
      password: password
      project_name: admin


# task in playbook.yml
    - name: update default security group to allow ssh
      os_security_group_rule:
        cloud: mycloud
        security_group: default
        protocol: tcp
        direction: ingress
        remote_ip_prefix: 0.0.0.0/0
        port_range_min: 22
        port_range_max: 22

```

##### EXPECTED RESULTS

Expecting the command to update the admin tenant default security group as project name is defined in clouds.yml .

##### ACTUAL RESULTS

Task fails with:

```
fatal: [server]: FAILED! => {"changed": false, "failed": true, "msg": "Multiple matches found for default"}
```

_Copied from original issue: ansible/ansible-modules-core#5862_

**Comment by sdubrul** [comment]
_From @ansibot on December 9, 2016 19:49_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide.

**Comment by ansibot** [comment]
cc @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz, @thingee
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Thingee** [comment]
I have also been able to verify this problem. Thanks for the report @sdubrul!

**Comment by Thingee** [comment]
Actually take that back. It was working as expected for me because I did in fact have two security groups called default in my setup. You mind double checking your environment @sdubrul?

```
(ansible) ubuntu@devstack:~/ansible-tests$ openstack --os-cloud local security group list
+--------------------------------------+---------+------------------------+----------------------------------+
| ID                                   | Name    | Description            | Project                          |
+--------------------------------------+---------+------------------------+----------------------------------+
| 50897f83-2946-4e46-a07f-87ec6d7d5364 | default | Default security group | 40f40cd2b1a9438697add40be77b74cf |
| 59de04a2-cf93-4f56-a71d-0b1f27fc59b6 | default | Default security group | dc077ad0bad24c9b9fb098feab530d5d |
+--------------------------------------+---------+------------------------+----------------------------------+
(ansible) ubuntu@devstack:~/ansible-tests$ openstack --os-cloud local security group delete 50897f83-2946-4e46-a07f-87ec6d7d5364
(ansible) ubuntu@devstack:~/ansible-tests$ ansible-playbook -vvvv test-os-default-security-group.yml
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /home/ubuntu/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test-os-default-security-group.yml ***********************************
1 plays in test-os-default-security-group.yml

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Using module file /home/ubuntu/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1482434283.74-141506423658362 `" && echo ansible-tmp-1482434283.74-141506423658362="` echo $HOME/.ansible/tmp/ansible-tmp-1482434283.74-141506423658362 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpO2sEoN TO /home/ubuntu/.ansible/tmp/ansible-tmp-1482434283.74-141506423658362/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1482434283.74-141506423658362/ /home/ubuntu/.ansible/tmp/ansible-tmp-1482434283.74-141506423658362/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/ubuntu/.virtualenvs/ansible/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1482434283.74-141506423658362/setup.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1482434283.74-141506423658362/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]

TASK [update default security group to allow ssh] ******************************
task path: /home/ubuntu/ansible-tests/test-os-default-security-group.yml:5
Using module file /home/ubuntu/.virtualenvs/ansible/local/lib/python2.7/site-packages/ansible/modules/core/cloud/openstack/os_security_group_rule.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1482434284.88-208943842438451 `" && echo ansible-tmp-1482434284.88-208943842438451="` echo $HOME/.ansible/tmp/ansible-tmp-1482434284.88-208943842438451 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpElmBBy TO /home/ubuntu/.ansible/tmp/ansible-tmp-1482434284.88-208943842438451/os_security_group_rule.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1482434284.88-208943842438451/ /home/ubuntu/.ansible/tmp/ansible-tmp-1482434284.88-208943842438451/os_security_group_rule.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/home/ubuntu/.virtualenvs/ansible/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1482434284.88-208943842438451/os_security_group_rule.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1482434284.88-208943842438451/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "id": "7eecf295-905f-4b46-ac75-86292f0bcb71",
    "invocation": {
        "module_args": {
            "api_timeout": null,
            "auth": null,
            "auth_type": null,
            "availability_zone": null,
            "cacert": null,
            "cert": null,
            "cloud": "local",
            "direction": "ingress",
            "endpoint_type": "public",
            "ethertype": "IPv4",
            "key": null,
            "port_range_max": 22,
            "port_range_min": 22,
            "protocol": "tcp",
            "region_name": null,
            "remote_group": null,
            "remote_ip_prefix": "0.0.0.0/0",
            "security_group": "default",
            "state": "present",
            "timeout": 180,
            "verify": true,
            "wait": true
        },
        "module_name": "os_security_group_rule"
    },
    "rule": {
        "created_at": "2016-12-22T19:18:07Z",
        "description": "",
        "direction": "ingress",
        "ethertype": "IPv4",
        "id": "7eecf295-905f-4b46-ac75-86292f0bcb71",
        "port_range_max": 22,
        "port_range_min": 22,
        "project_id": "dc077ad0bad24c9b9fb098feab530d5d",
        "protocol": "tcp",
        "remote_group_id": null,
        "remote_ip_prefix": "0.0.0.0/0",
        "revision_number": 1,
        "security_group_id": "59de04a2-cf93-4f56-a71d-0b1f27fc59b6",
        "tenant_id": "dc077ad0bad24c9b9fb098feab530d5d",
        "updated_at": "2016-12-22T19:18:07Z"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

needs_info

**Comment by ansibot** [comment]
cc @bennojoy @dagnello
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@sdubrul This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@sdubrul This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@sdubrul You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by m3gat0nn4ge** [comment]
This is still an issue... os_security_group_rule does not support the 'project' parameter.

Workaround:
Each project has a 'default' security group, to manipulate them currently you need a _member_ account in each project, you can then create custom clouds to auth to each project:
```
            overcloud-production:
              identity_api_version: 3
              auth:
                auth_url: http://x.x.x.x:5000/v3
                username: admin
                password: password
                project_name: production
                project_domain_name: Default
                user_domain_name: Default

    - name: Assign _member_ role in production - admin
      os_user_role:
        cloud: overcloud
        user: admin
        role: _member_
        project: production

    - name: Create secgroup rule - ICMP in production default
      os_security_group_rule:
        cloud: overcloud-production
        security_group: default
        protocol: icmp
        remote_ip_prefix: 0.0.0.0/0
```

The os_security_group module has already been fixed accordingly:
https://github.com/ansible/ansible/commit/8522e6420e0763ddea027ba64d46e58a5e3f9e61
