### ISSUE TITLE
hostname module does not rename correctly on debian

### ISSUE THREAD

**Issue by oupala** [ansible/ansible#19176]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

hostname module

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

none

##### OS / ENVIRONMENT

ansible running from debian, ansible managing raspbian

##### SUMMARY

As said in the title, it appears that [hostname module](http://docs.ansible.com/ansible/hostname_module.html) does not rename correctly on debian.

According to [hostname.py](https://github.com/ansible/ansible-modules-core/blob/e278f285aa6f61e45416be28b1e689b4d7607196/system/hostname.py#L489-L492), Debian usecase is not using systemd for changing its hostname with ansible.

And still according to [hostname.py](https://github.com/ansible/ansible-modules-core/blob/e278f285aa6f61e45416be28b1e689b4d7607196/system/hostname.py#L150-L156), Debian usecase is only updating the `/etc/hostname` file.

According to [debian wiki](https://wiki.debian.org/HowTo/ChangeHostname#Core_networking), it should update the `/etc/hostname` file **and** the `/etc/hosts` file. And then restart networking.

The behaviour is consistent with the ansible documentation, but it is not consistent with debian documentation.

The module is known to change the hostname but it doesn't do it correctly.

The behaviour of the module and its documentation should be updated in order to get it work.

I don't understand what does systemd do in this issue. I think hostname module does not work on debian whatever init system is used (SysVinit or systemd).

See also ansible/ansible-modules-core#2004.

##### STEPS TO REPRODUCE

Just set the name of a hostname on a host.

```yaml
  - name: set hostname
    hostname:
      name: "{{ hostname }}"

  # this workaround task is mandatory for hostname renaming
  # see https://github.com/ansible/ansible-modules-core/issues/2004
  - name: set hostname - workaround
    lineinfile:
      state: present
      dest: /etc/hosts
      regexp: "^127.0.1.1\t{{ hostname }}$"
      line: "127.0.1.1\t{{ hostname }}"
```

##### EXPECTED RESULTS

`/etc/hostname` contains `{{ hostname}}` **and** `/etc/hosts` mention **{{ hostname }}` on one line.

##### ACTUAL RESULTS

`/etc/hostname` contains `{{ hostname}}` **but** `/etc/hosts` has not been updated..

```

```
