### ISSUE TITLE
docker_container doc about volume mount modes is too restrictive

### ISSUE THREAD

**Issue by MikeSpreitzer** [ansible/ansible#19193]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

none

##### OS / ENVIRONMENT

Controller machine is MacOS 10.12.1
Managed machine is Ubuntu 14.04

##### SUMMARY

The current documentation of the `volumes` parameter of the `docker_container` module
says this about the mount mode: "You can specify a read mode for the mount with either `ro` or `rw`.  SELinux hosts can additionally use `z` or `Z` to use a shared or private label for the volume."  But I was able to use a mode of `rw,rshared` (with the host path naming a shared mount point).  It is good that I was able to do that; I wish the documentation indicated this and told me which Ansible version introuced that ability.

##### STEPS TO REPRODUCE

```
- name: Ensure /var/lib/kubelet exists
  command: mkdir -p /var/lib/kubelet

- name: Ensure /var/lib/kubelet is a mount point
  shell: grep /var/lib/kubelet /etc/mtab || mount --bind /var/lib/kubelet /var/lib/kubelet

- name: Ensure /var/lib/kubelet is a shared mount point
  shell: mount --make-rshared /var/lib/kubelet

- name: Ensure the kubelet container is defined
  docker_container:
    command: /hyperkube kubelet ...
    image: gcr.io/google_containers/hyperkube-amd64:v1.4.6
    name: kubelet
    network_mode: host
    pid_mode: host
    privileged: yes
    restart_policy: always
    state: started
    volumes:
        - /:/rootfs:ro
        - /sys:/sys:ro
        - /dev:/dev
        - /var/run:/var/run
        - /var/lib/kubelet:/var/lib/kubelet:rw,rshared
        - /var/lib/docker:/var/lib/docker
        - /etc/kubernetes:/etc/kubernetes
        - /etc/cni/net.d:/etc/cni/net.d
        - /opt/cni/bin:/opt/cni/bin
```

##### EXPECTED RESULTS

If the doc were accurate then executing that `docker_container` task would fail with a complaint about the mode of the `/var/lib/kubelet` volume mount.

##### ACTUAL RESULTS

The task ran without complaint and produced the desired result.  Below is what I saw when running with `-v`.

```
TASK [k8sm-worker : Ensure the kubelet container is defined] *******************
Saturday 10 December 2016  22:10:50 -0500 (0:00:00.114)       0:02:00.088 ***** 
changed: [192.168.10.2] => {"ansible_facts": {}, "changed": true}
```

After that, `docker inspect kubelet` had this to say about that volume mount:
```
            {
                "Source": "/var/lib/kubelet",
                "Destination": "/var/lib/kubelet",
                "Mode": "rw,rshared",
                "RW": true,
                "Propagation": "rshared"
            },
```
