### ISSUE TITLE
vmware_guest networks option using dict is problematic

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#19222]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.3 (devel branch)

##### SUMMARY

The vmware_guest module requires a dict for the networks customizations, the example shows this:

```yaml
        networks:
          '192.168.1.0/24':
            network: 'VM Network'
            gateway: '192.168.1.1' 
```

Which is problematic if the **192.168.1.0/24** is variable, which in most cases will be.
Ansible does not allow to template the key-part of a dictionary.

My proposal is that we change this interface to use a normal list, there is no need to use a dictionary in this case.

```yaml
        networks:
        - name: 'VM Network'
          network: '192.168.1.0/24':
          gateway: '192.168.1.1' 
```

I have a patch available to make this change and would propose we fix this before this is being released to the public.
