### ISSUE TITLE
ec2_group creates all-out egress rule on creation even if egress rule list is empty

### ISSUE THREAD

**Issue by Dieler** [ansible/ansible#19226]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT

MacOS X

##### SUMMARY

`ec2_group` creates an all-out egress rule even if the actual egress rule list is empty. This only happens when `purge_egress_rules` is false. Ingress rules won't be created when the ingress rule list is empty and `purge_rules` is false.

##### STEPS TO REPRODUCE

The following creates a security group with no inbound rules but an all-out egress rule:

```
    - ec2_group:
        name: development-test
        description: "Development Test"
        vpc_id:  vpc-12345
        purge_rules: False
        rules: []
        purge_rules_egress: False
        rules_egress: []
```

This leads to a security group with no inbound or outbound rules:
```
    - ec2_group:
        name: development-test
        description: "Development Test"
        vpc_id:  vpc-12345
        purge_rules: False
        rules: []
        purge_rules_egress: True
        rules_egress: []
```

##### EXPECTED RESULTS

The behaviour for inbound and outbound rules together with the purge flags should be consistent.

##### ACTUAL RESULTS

The behaviour for inbound and outbound rules together with the respective purge flags is not consistent. Inbound rules won't be created regardless of the value of `purge_rules`. Outbound rules won't be created only if the egress rule list is empty and the value of `purge_egress_rules` is `True`.

```

```
