### ISSUE TITLE
yum install failed but task outputs OK (with_items)

### ISSUE THREAD

**Issue by coreaut** [ansible/ansible#19221]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
yum

##### ANSIBLE VERSION
```
ansible 2.1.2.0
```

##### OS / ENVIRONMENT
Running on Ubuntu 14.04
Managing CentOS 7.2

##### SUMMARY
The tasks outputs OK but actually failed. This happens only when using with_items.
Because of the wrong output. In Big playbooks it's hard to find the error.

##### STEPS TO REPRODUCE
```

---
  - name: Test yum install
    hosts: somehost
    tasks:
      - name: install package
        become: yes
        yum:
          state: present
          name: "{{ item }}"
        with_items:
          - bash
          - doesnotexist
```

##### EXPECTED RESULTS
```
TASK [install package] *********************************************************
fatal: [somehost]: FAILED! => {"changed": false, "failed": true, "msg": "No Package matching 'doesnotexisthere' found available, installed or updated", "rc": 0, "results": []}
```

##### ACTUAL RESULTS
```
TASK [install package] *********************************************************
ok: [somehost] => (item=[u'bash', u'doesnotexist'])

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @/home/user/stuff/ansible/playbooks/test.retry

PLAY RECAP *********************************************************************
somehost              : ok=0    changed=0    unreachable=0    failed=1   

```
