### ISSUE TITLE
iam_policy not using role structure for policy_document path

### ISSUE THREAD

**Issue by MichaelBaydoun** [ansible/ansible#19249]
_From @MichaelBaydoun on March 4, 2016 16:57_

##### Issue Type:
- Bug Report
##### Component Name:

iam_policy module
##### Ansible Version:

ansible 2.0.1.0
##### Ansible Configuration:

no changes to ansible.cfg
##### Environment:

control server Redhat 6.7
target server Redhat 6.7
##### Summary:

iam_policy policy_document parameter does not use role file structure
##### Steps To Reproduce:

aws.yml

```

---
- hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - aws
```

roles/aws/task/main.yml

```

---
- name: configure iam policy
  iam_policy:
    iam_name: test
    iam_type: group
    policy_name: test
    policy_document: test.json
#    policy_document: roles/aws/files/test.json
    region: us-east-1
    state: present
```

roles/aws/files/test.json

```

---
<any valid policy>
```

run play
ansible-playbook aws.yml, task fails, no such file or directory test.json

however, if you change the policy_document argument to: roles/aws/files/test.json and it works
##### Expected Results:

Policy is created
##### Actual Results:

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: 'test.json'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}

_Copied from original issue: ansible/ansible-modules-core#3189_
