### ISSUE TITLE
apache2_module fails to add module if module was added to config file already

### ISSUE THREAD

**Issue by er1zo** [ansible/ansible#19275]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

apache2_module
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

apache2_module fails to add module, when commands were already added to configuration file and gives apache2ctl error. This setup worked though on ansible 2.1
##### STEPS TO REPRODUCE

```
  - name: setup service.conf
    template: src=service.conf.j2 dest=/etc/apache2/sites-enabled/service.conf owner=root group=root
  - name: add proxy_http module
    apache2_module: name={{ item }} state=present
    with_items:
        - proxy_http
```
service.conf.j2
```
<VirtualHost *:80>
        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log custom

    ProxyPass /server-status !
    ProxyPass / http://localhost:12345/
    ProxyPassReverse / http://localhost:12345/

</VirtualHost>
```

##### EXPECTED RESULTS

In apache configuration directory should be configuration file and modules proxy_http, ssl should be enabled. Config is not applied though(apache2 not restarted).
##### ACTUAL RESULTS

```
failed: [servername] (item=proxy_http) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "force": false,
            "name": "proxy_http",
            "state": "present"
        },
        "module_name": "apache2_module"
    },
    "item": "proxy_http",
    "msg": "Error executing /usr/sbin/apache2ctl: AH00526: Syntax error on line 9 of /etc/apache2/sites-enabled/service.conf:\nInvalid command 'ProxyPass', perhaps misspelled or defined by a module not included in the server configuration\n"
}
```
