### ISSUE TITLE
vmware_guest ignores disk changes when cloning from template

### ISSUE THREAD

**Issue by nitgithub** [ansible/ansible#19289]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /Users/user/dev/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The vmware_guest module does not resize (grow) the template disk if disk and networks settings are given.

##### STEPS TO REPRODUCE

```
- name: clone vm
  vmware_guest:
     hostname: vcenter.server
     datacenter: DC
     username: admin
     password: pass
     esxi_hostname: esxhost
     validate_certs: False
     name: "myvm"
     state: poweredOn
     disk:
        - size_gb: 33
           type: thin
           datastore: "datastore1"
     hardware:
        memory_mb: 2048
        num_cpus: 2
        osid: ubuntu64guest
        scsi: paravirtual
     template: template1
     wait_for_ip_address: yes
     customize: yes
     domain: "domain.tld"
     dns_servers: [ '1.2.3.4' ]
     ips: "1.2.3.10"
     networks: 
        '1.2.3.0/24':
           network: 'VM Network'
           gateway: '1.2.3.1' 
  delegate_to: localhost
```

##### EXPECTED RESULTS

Cloned Vm with custom IP/ Network settings and resized disk (template has one disk with 8GB)
##### ACTUAL RESULTS

disk settings get ignored, network settings are applied.
It seems, the disk deviceChange.configSpec gets overwritten with the network settings. In file https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/vmware/vmware_guest.py line 867 replace 
```
# Update the spec with the added NIC
clonespec_kwargs['config'].deviceChange = devices
```
with 
```
# Update the spec with the added NIC
clonespec_kwargs['config'].deviceChange.extend(devices)
```
