### ISSUE TITLE
fetch module: failed to transfer an existing file

### ISSUE THREAD

**Issue by sparkvilla** [ansible/ansible#19287]
##### ISSUE TYPE
 - Bug Report
 

##### COMPONENT NAME

fetch

##### ANSIBLE VERSION

```
ansible 2.2.0.0


```

##### OS / ENVIRONMENT

  hosts file:
  [nas]
  ds ansible_host=172.20.0.5 ansible_user=admin 

  ansible.cfg file:
  [ssh_connection]
  scp_if_ssh=True
  [defaults]
  hostfile = ./hosts
  retry_files_enabled=False #do not create retry files
  stdout_callback = json

##### SUMMARY

I have ubuntu 16.04 as a control machine and Synology as target host. I would like to fetch an existing file  `test_ans` from the synology at  `/var/services/homes/admin/test_ans`  and copy it over to the control machine at  `/tmp/`. Ansible sees the file, i.e. the stat module in the playbook returns `stat_result.stat.exists==true`  but is not able to fetch it.   

##### STEPS TO REPRODUCE

ansible-playbook -i hosts keys.yml -e "target=ds"

```
---
- hosts: '{{ target }}'
  tasks:
  - name: Check admin pub keys are present on synology
    stat:
      path: /var/services/homes/admin/test_ans
    register: stat_result
   - name: Downloading pub key
    fetch:
      src: /var/services/homes/admin/test_ans
      dest: /tmp/
      flat: yes
```

##### ACTUAL RESULTS

```
"msg": "failed to transfer file to /tmp/test_ans: /var/services/homes/admin/test_ans: No such file or directory\n"

```
