### ISSUE TITLE
git module: Task fails if 'origin' remote does not exist

### ISSUE THREAD

**Issue by odyssey4me** [ansible/ansible#19290]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

git

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /root/.ansible.cfg
  configured module search path = ['/root/.ansible/plugins/library']
```

##### CONFIGURATION

```
### /root/.ansible.cfg
[defaults]
transport         = ssh
host_key_checking = False
control_path      = /tmp/%%h-%%r
ssh_args          = -o ControlMaster=no -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ServerAliveInterval=64 -o ServerAliveCountMax=1024 -o Compression=no -o TCPKeepAlive=yes -o VerifyHostKeyDNS=no -o ForwardX11=no -o ForwardAgent=yes
library           = $HOME/.ansible/plugins/library
roles_path        = $HOME/.ansible/roles
```

##### OS / ENVIRONMENT

Ubuntu 16.04.1 LTS (Xenial Xerus)
Although I believe that this is not OS specific.

##### SUMMARY

If there is no existing ``origin`` remote in a git repository, the git module will fail with the error:

```
Failed to set a new url ... for origin:  fatal: No such remote 'origin'
```

##### STEPS TO REPRODUCE

```
---
- name: Test git module fuctionality
  hosts: localhost
  user: root
  tasks:
    - name: Pre-cache a git repository
      git:
        repo: "https://git.openstack.org/openstack/keystone"
        dest: "{{ git_clone_dest }}"
        clone: yes
        update: yes
    - name: Intentionally remove the repository remote origin
      shell: "git remote remove origin"
      args:
        chdir: "{{ git_clone_dest }}"
    - name: Update the git repository
      git:
        repo: "https://git.openstack.org/openstack/keystone"
        dest: "{{ git_clone_dest }}"
        clone: yes
        update: yes
  vars:
    git_clone_dest: "{{ lookup('ENV', 'HOME') }}/keystone }}"
```

##### EXPECTED RESULTS

The remote 'origin' should be created and have the correct URL set.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "accept_hostkey": false,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/root/keystone }}",
            "executable": null,
            "force": false,
            "key_file": null,
            "recursive": true,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "https://git.openstack.org/openstack/keystone",
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        },
        "module_name": "git"
    },
    "msg": "Failed to set a new url https://git.openstack.org/openstack/keystone for origin:  fatal: No such remote 'origin'\n"
}
```
