### ISSUE TITLE
Template module: create path if doesn't exist

### ISSUE THREAD

**Issue by alex-left** [ansible/ansible#19294]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Template Module

##### SUMMARY

Actually when path doesn't exist the module fails, maybe is good idea create the path if doesn't exist throught a new parameter. 

This way, doesn't need an extra task for create the path and could have a more clean an concise code. 

For example: 
```
- template:
    src: /mytemplates/foo.j2
    dest: /etc/file.conf
    owner: bin
    group: wheel
    mode: "u=rw,g=r,o=r"
    **create_path: yes**
```
-->

Regards!
