### ISSUE TITLE
include_role unable to reference non-playbook variables in included role name

### ISSUE THREAD

**Issue by orischwartz** [ansible/ansible#19305]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`include_role`

##### ANSIBLE VERSION

```
$ ansible --version

ansible 2.3.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
_No change to default configuration._

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`include_role` supports variable interpolation in the role `name` but cannot evaluate loop variables correctly. 

##### STEPS TO REPRODUCE
```yml
- include_role:
    name: "{{ item }}"
  with_items:
    - "x"
    - "y"
```
##### EXPECTED RESULTS
Expected roles `x` and `y` to be included.

##### ACTUAL RESULTS
Ansible fails to evaluate the loop control variable, `item`.
```
ERROR! 'item' is undefined
```

~~Possibly related to #17966 and its fixes which were committed in 885b218a7bab42bf9051fc8673b12889b9ab2134, 01b75f966b0923899281fd1cd2cceeb4fdf44287, fb921042db9e03fc805c3a5e83c8cf564d5c2199, and 99220a5f6cd2dd5af2903dce8cefeeb5ceaddf8f~~

**Comment by orischwartz** [comment]
This actually has nothing to do with loop vars -- `include_role`'s `name` cannot evaluate any variables defined outside of the playbook's scope:

```yml
- set_fact:
    role_name: "x"
- include_role:
    name: "{{ role_name }}"
```
```
ERROR! 'role_name' is undefined
```

(It can evaluate variables defined in the playbook or specified via the `-e` switch.)

**Comment by bcoca** [comment]
that is the difference between dynamic and static
```
- include_role:
    name: "{{ role_name }}"
  static: no
```

**Comment by orischwartz** [comment]
@bcoca I'm still seeing the same behavior:

```yml
- set_fact:
    role_name: "x"

- include_role:
    name: "{{ role_name }}"
    static: False
```

```
ERROR! 'role_name' is undefined
```

(Same result if indenting `static` as shown and as in [comment above](https://github.com/ansible/ansible/issues/19305#issuecomment-267163067).)

**Comment by bcoca** [comment]
you indented static too far

**Comment by orischwartz** [comment]
@bcoca I tried both :) same result either way:

```yml
- set_fact:
    role_name: "x"

- include_role:
    name: "{{ role_name }}"
  static: False
```
```
ERROR! 'role_name' is undefined
```

**Comment by bcoca** [comment]
ok, confirmed then, the dynamic evaluation does not seem to be getting hostvars

**Comment by kladiv** [comment]
include_roles does not evaluate "default/main.yml" (of included role itself). I got undefined error

playbook.yml
```
- name: _include_role
  include_role:
    name: [role name]
```
[role name].yml
```
- block:
  ...
  when:
    - variable != None
```

variable is defined into "[role name]/default/main.yml"

**Comment by ppluciennik** [comment]
Hi,
I've prepared a small patch to fix "{{item}}" problem. Please review it and apply if you feel it's a good one.
```
diff --git a/lib/ansible/executor/task_executor.py b/lib/ansible/executor/task_executor.py
index 64f8a6c3e..34f99b867 100644
--- a/lib/ansible/executor/task_executor.py
+++ b/lib/ansible/executor/task_executor.py
@@ -456,7 +456,9 @@ class TaskExecutor:
         # if this task is a IncludeRole, we just return now with a success code so the main thread can expand the task list for the given host
         elif self._task.action == 'include_role':
             include_variables = self._task.args.copy()
-            return dict(include_role=self._task, include_variables=include_variables)
+            return dict(include_role=self._task,
+                        include_variables=include_variables,
+                        include_executor_variables=templar._available_variables)
 
         # Now we do final validation on the task, which sets all fields to their final values.
         self._task.post_validate(templar=templar)
diff --git a/lib/ansible/plugins/strategy/linear.py b/lib/ansible/plugins/strategy/linear.py
index 12a9197f6..e53397090 100644
--- a/lib/ansible/plugins/strategy/linear.py
+++ b/lib/ansible/plugins/strategy/linear.py
@@ -298,8 +298,14 @@ class StrategyModule(StrategyBase):
                             display.debug("generating all_blocks data for role")
                             new_ir = hr._task.copy()
                             new_ir.vars.update(include_result.get('include_variables', dict()))
+
+                            executor_variables = include_result.get('include_executor_variables', dict())
+                            vars_item = {}
                             if loop_var and loop_var in include_result:
-                                new_ir.vars[loop_var] = include_result[loop_var]
+                                vars_item[loop_var] = include_result[loop_var]
+                            vars_item.update(executor_variables)
+                            templar = Templar(loader=self._loader, variables=vars_item)
+                            new_ir._role_name = templar.template(new_ir._role_name)
 
                             all_role_blocks.extend(new_ir.get_block_list(play=iterator._play, variable_manager=self._variable_manager, loader=self._loader))
 
```

**Comment by ppluciennik** [comment]
Is there a way to dynamically feed include_role "vars"?
I've tried:
vars: "{{item.my_vars}}", but vars must be dictionary or list of dictionaries.

**Comment by smemsh** [comment]
not just facts, but any variables; eg this does not work either:

```
vars:
  rolename: foo
include_role:
  name: '{{rolename}}'
```

**Comment by Atem18** [comment]
@ppluciennik Your patch works for me with the following play:
```yaml
---
- hosts: all
  vars_files:
    - "../host_vars/{{ ansible_hostname }}.yml"
  tasks:
    - name: Execute role for each services
      include_role:
        name: "zabbix-{{ zabbix_service }}"
      with_items:
        - "{{ zabbix_services }}"
      loop_control:
        loop_var: zabbix_service
```

{{ ansible_hostname }} is the default one and {{ zabbix_services }} is imported from the vars_files and is equal to:
```yaml
zabbix_services:
  - apt
  - mysql 
```
Do a pull request for your patch please so we can have it in standard.

**Comment by ppluciennik** [comment]
Added PR https://github.com/ansible/ansible/pull/23756.

**Comment by subsy** [comment]
@ppluciennik thanks for your patch, it helped us get one step further - but hitting the vars issue that you mentioned:

```yaml
- name: Deploy Products
  include_role:
    name: "{{ item.name }}"
  vars:
    productitem: "{{ item.component_list }}"
  with_items:
    - "{{ product_list }}"
```

returns:


`fatal: [10.23.7.180]: FAILED! => {
    "failed": true,
    "msg": "'component_list' is undefined"
}`
