### ISSUE TITLE
synchronize fail when currentuser@localhost tries to rsync to anotheruser@localhost on nonstandard ssh port

### ISSUE THREAD

**Issue by badkapitan** [ansible/ansible#19336]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
synchronize

##### ANSIBLE VERSION
ansible 2.1.2.0+

##### CONFIGURATION
Make ssh work listen on port 2222 on localhost
Inventory:
[samplehost]
ansible_ssh_user: anotheruser
ansible_ssh_host: localhost
ansible_ssh_port: 2222

##### OS / ENVIRONMENT
Debian 8

##### SUMMARY
synchronize fails to rsync files from current user to another user on the same machine

I've traced down this problem to this logic in ansible/plugins/action/synchronize.py:88-99:

        # If we're connecting to a remote host or we're delegating to another
        # host or we're connecting to a different ssh instance on the
        # localhost then we have to format the path as a remote rsync path
        if host not in C.LOCALHOST or transport != "local" or \
                (host in C.LOCALHOST and not port_matches_localhost_port):
            # If we're delegating to non-localhost and but the
            # inventory_hostname host is localhost then we need the module to
            # fix up the rsync path to use the controller's public DNS/IP
            # instead of "localhost"
            if port_matches_localhost_port and host in C.LOCALHOST:
                self._task.args['_substitute_controller'] = True
            return self._format_rsync_rsh_target(host, path, user)

This needs to cover different localhost users&ports case. Resolving this should also resolve https://github.com/ansible/ansible-modules-core/issues/5385

##### STEPS TO REPRODUCE
Use provided configuration and try:
`ansible -i <inventory> samplehost -m synchronize -a "src=~/source/ dest=~/destination"
`
##### EXPECTED RESULTS
Should work the same as:
`rsync -e "ssh -o Port=2222" -a ~/source anotheruser@localhost:~/destination
`
##### ACTUAL RESULTS
Doesn't provide rsh rsync path with user specified and fails due to badly expanded path/permission error.

`"cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh -i <key> -S none -o StrictHostKeyChecking=no -o Port=2222' --out-format='<<CHANGED>>%i %n%L' \"/home/currentuser/source\" \"/home/currentuser/destination\"", `

```

```

**Comment by tima** [comment]
Is this still an issue if you don't use a hostname with localhost in it? 

needs_info

**Comment by le9i0nx** [comment]
I came across this error too.

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/le9i0nx/isuse_19336/ansible.cfg
  configured module search path = ['/etc/ansible/library']
```


##### CONFIGURATION

```

[defaults]
filter_plugins = /etc/ansible/filter_plugins:/usr/share/ansible/plugins/filter
lookup_plugins = /etc/ansible/lookup_plugins:/usr/share/ansible/plugins/lookup
library        = /etc/ansible/library
roles_path     = ./roles
retry_files_save_path = /tmp/

# some basic default values...

remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 5
poll_interval  = 15
transport      = smart
remote_port    = 22
module_lang    = C

gathering = implicit
sudo_exe = sudo
timeout = 10
ansible_managed = Ansible managed: modified on %Y-%m-%d %H:%M:%S

gathering = smart

[paramiko_connection]

[ssh_connection]

[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0

accelerate_daemon_timeout = 30

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Different behavior depending on the target.

##### STEPS TO REPRODUCE

```yaml
---

- name: test
  hosts: test
  become: no
  vars:
    ansible_ssh_user: ansible
  tasks:

    - file:
        path: '/tmp/repo_{{ ansible_ssh_user }}/'
        state:  'directory'

    - synchronize:
        src: '../'
        dest: '/tmp/repo_{{ ansible_ssh_user }}/'

```

cat inventory/test_localhost/hosts
```
[test]
localhost ansible_host=localhost ansible_connection=ssh
```

cat inventory/test_remote/hosts
```
[test]
centos7_1 ansible_host=centos7_1 ansible_connection=ssh
```

##### EXPECTED RESULTS

``` yaml
ansible-playbook -i inventory/test_remote/ test.yml --diff -vvvv
Using /home/le9i0nx/isuse_19336/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<centos7_1> ESTABLISH SSH CONNECTION FOR USER: ansible
<centos7_1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/le9i0nx/.ansible/cp/ansible-ssh-%h-%p-%r centos7_1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496772.73-276335209387849 `" && echo ansible-tmp-1489496772.73-276335209387849="` echo $HOME/.ansible/tmp/ansible-tmp-1489496772.73-276335209387849 `" ) && sleep 0'"'"''
<centos7_1> PUT /tmp/tmpSOD2ai TO /home/ansible/.ansible/tmp/ansible-tmp-1489496772.73-276335209387849/setup.py
<centos7_1> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/le9i0nx/.ansible/cp/ansible-ssh-%h-%p-%r '[centos7_1]'
<centos7_1> ESTABLISH SSH CONNECTION FOR USER: ansible
<centos7_1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/le9i0nx/.ansible/cp/ansible-ssh-%h-%p-%r centos7_1 '/bin/sh -c '"'"'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1489496772.73-276335209387849/ /home/ansible/.ansible/tmp/ansible-tmp-1489496772.73-276335209387849/setup.py && sleep 0'"'"''
<centos7_1> ESTABLISH SSH CONNECTION FOR USER: ansible
<centos7_1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/le9i0nx/.ansible/cp/ansible-ssh-%h-%p-%r -tt centos7_1 '/bin/sh -c '"'"'/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1489496772.73-276335209387849/setup.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1489496772.73-276335209387849/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [centos7_1]

TASK [file] ********************************************************************
task path: /home/le9i0nx/isuse_19336/test.yml:10
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/files/file.py
<centos7_1> ESTABLISH SSH CONNECTION FOR USER: ansible
<centos7_1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/le9i0nx/.ansible/cp/ansible-ssh-%h-%p-%r centos7_1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496775.43-18360362175869 `" && echo ansible-tmp-1489496775.43-18360362175869="` echo $HOME/.ansible/tmp/ansible-tmp-1489496775.43-18360362175869 `" ) && sleep 0'"'"''
<centos7_1> PUT /tmp/tmpTPnyEA TO /home/ansible/.ansible/tmp/ansible-tmp-1489496775.43-18360362175869/file.py
<centos7_1> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/le9i0nx/.ansible/cp/ansible-ssh-%h-%p-%r '[centos7_1]'
<centos7_1> ESTABLISH SSH CONNECTION FOR USER: ansible
<centos7_1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/le9i0nx/.ansible/cp/ansible-ssh-%h-%p-%r centos7_1 '/bin/sh -c '"'"'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1489496775.43-18360362175869/ /home/ansible/.ansible/tmp/ansible-tmp-1489496775.43-18360362175869/file.py && sleep 0'"'"''
<centos7_1> ESTABLISH SSH CONNECTION FOR USER: ansible
<centos7_1> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/home/le9i0nx/.ansible/cp/ansible-ssh-%h-%p-%r -tt centos7_1 '/bin/sh -c '"'"'/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1489496775.43-18360362175869/file.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1489496775.43-18360362175869/" > /dev/null 2>&1 && sleep 0'"'"''
--- before
+++ after
@@ -1,4 +1,4 @@
 {
     "path": "/tmp/repo_ansible/", 
-    "state": "absent"
+    "state": "directory"
 }
changed: [centos7_1] => {
    "changed": true, 
    "diff": {
        "after": "{\n    \"path\": \"/tmp/repo_ansible/\", \n    \"state\": \"directory\"\n}", 
        "before": "{\n    \"path\": \"/tmp/repo_ansible/\", \n    \"state\": \"absent\"\n}"
    }, 
    "gid": 994, 
    "group": "ansible", 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "delimiter": null, 
            "diff_peek": null, 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "group": null, 
            "mode": null, 
            "original_basename": null, 
            "owner": null, 
            "path": "/tmp/repo_ansible/", 
            "recurse": false, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": "directory", 
            "unsafe_writes": null, 
            "validate": null
        }, 
        "module_name": "file"
    }, 
    "mode": "0775", 
    "owner": "ansible", 
    "path": "/tmp/repo_ansible/", 
    "secontext": "unconfined_u:object_r:user_tmp_t:s0", 
    "size": 4096, 
    "state": "directory", 
    "uid": 996
}

TASK [synchronize] *************************************************************
task path: /home/le9i0nx/isuse_19336/test.yml:14
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/files/synchronize.py
<centos7_1> ESTABLISH LOCAL CONNECTION FOR USER: le9i0nx
<centos7_1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496777.35-173240685794433 `" && echo ansible-tmp-1489496777.35-173240685794433="` echo $HOME/.ansible/tmp/ansible-tmp-1489496777.35-173240685794433 `" ) && sleep 0'
<centos7_1> PUT /tmp/tmpfveqOf TO /home/le9i0nx/.ansible/tmp/ansible-tmp-1489496777.35-173240685794433/synchronize.py
<centos7_1> EXEC /bin/sh -c 'chmod u+x /home/le9i0nx/.ansible/tmp/ansible-tmp-1489496777.35-173240685794433/ /home/le9i0nx/.ansible/tmp/ansible-tmp-1489496777.35-173240685794433/synchronize.py && sleep 0'
<centos7_1> EXEC /bin/sh -c '/usr/bin/python /home/le9i0nx/.ansible/tmp/ansible-tmp-1489496777.35-173240685794433/synchronize.py; rm -rf "/home/le9i0nx/.ansible/tmp/ansible-tmp-1489496777.35-173240685794433/" > /dev/null 2>&1 && sleep 0'
.d..tp..... ./
<f+++++++++ ansible.cfg
<f+++++++++ test.yml
cd+++++++++ inventory/
cd+++++++++ inventory/test_localhost/
<f+++++++++ inventory/test_localhost/hosts
cd+++++++++ inventory/test_remote/
<f+++++++++ inventory/test_remote/hosts
changed: [centos7_1] => {
    "changed": true, 
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=22' --out-format='<<CHANGED>>%i %n%L' \"/home/le9i0nx/isuse_19336/\" \"ansible@centos7_1:/tmp/repo_ansible/\"", 
    "diff": {
        "prepared": ".d..tp..... ./\n<f+++++++++ ansible.cfg\n<f+++++++++ test.yml\ncd+++++++++ inventory/\ncd+++++++++ inventory/test_localhost/\n<f+++++++++ inventory/test_localhost/hosts\ncd+++++++++ inventory/test_remote/\n<f+++++++++ inventory/test_remote/hosts\n"
    }, 
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync", 
            "_substitute_controller": false, 
            "archive": true, 
            "checksum": false, 
            "compress": true, 
            "copy_links": null, 
            "delete": false, 
            "dest": "ansible@centos7_1:/tmp/repo_ansible/", 
            "dest_port": 22, 
            "dirs": false, 
            "existing_only": false, 
            "group": null, 
            "links": null, 
            "mode": "push", 
            "owner": null, 
            "partial": false, 
            "perms": null, 
            "private_key": null, 
            "recursive": null, 
            "rsync_opts": null, 
            "rsync_path": null, 
            "rsync_timeout": 0, 
            "set_remote_user": true, 
            "src": "/home/le9i0nx/isuse_19336/", 
            "ssh_args": null, 
            "times": null, 
            "verify_host": false
        }
    }, 
    "msg": ".d..tp..... ./\n<f+++++++++ ansible.cfg\n<f+++++++++ test.yml\ncd+++++++++ inventory/\ncd+++++++++ inventory/test_localhost/\n<f+++++++++ inventory/test_localhost/hosts\ncd+++++++++ inventory/test_remote/\n<f+++++++++ inventory/test_remote/hosts\n", 
    "rc": 0, 
    "stdout_lines": [
        ".d..tp..... ./", 
        "<f+++++++++ ansible.cfg", 
        "<f+++++++++ test.yml", 
        "cd+++++++++ inventory/", 
        "cd+++++++++ inventory/test_localhost/", 
        "<f+++++++++ inventory/test_localhost/hosts", 
        "cd+++++++++ inventory/test_remote/", 
        "<f+++++++++ inventory/test_remote/hosts"
    ]
}

PLAY RECAP *********************************************************************
centos7_1                  : ok=3    changed=2    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

``` yaml
ansible-playbook -i inventory/test_localhost/ test.yml --diff -vvvv
Using /root/isuse_19336/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: ansible
<localhost> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496888.16-177193307964711 `" && echo ansible-tmp-1489496888.16-177193307964711="` echo $HOME/.ansible/tmp/ansible-tmp-1489496888.16-177193307964711 `" ) && sleep 0'"'"''
<localhost> PUT /tmp/tmptZEupP TO /home/ansible/.ansible/tmp/ansible-tmp-1489496888.16-177193307964711/setup.py
<localhost> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[localhost]'
<localhost> ESTABLISH SSH CONNECTION FOR USER: ansible
<localhost> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1489496888.16-177193307964711/ /home/ansible/.ansible/tmp/ansible-tmp-1489496888.16-177193307964711/setup.py && sleep 0'"'"''
<localhost> ESTABLISH SSH CONNECTION FOR USER: ansible
<localhost> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost '/bin/sh -c '"'"'/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1489496888.16-177193307964711/setup.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1489496888.16-177193307964711/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [localhost]

TASK [file] ********************************************************************
task path: /root/isuse_19336/test.yml:10
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/file.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: ansible
<localhost> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496890.74-116872432167883 `" && echo ansible-tmp-1489496890.74-116872432167883="` echo $HOME/.ansible/tmp/ansible-tmp-1489496890.74-116872432167883 `" ) && sleep 0'"'"''
<localhost> PUT /tmp/tmpISJTlZ TO /home/ansible/.ansible/tmp/ansible-tmp-1489496890.74-116872432167883/file.py
<localhost> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[localhost]'
<localhost> ESTABLISH SSH CONNECTION FOR USER: ansible
<localhost> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1489496890.74-116872432167883/ /home/ansible/.ansible/tmp/ansible-tmp-1489496890.74-116872432167883/file.py && sleep 0'"'"''
<localhost> ESTABLISH SSH CONNECTION FOR USER: ansible
<localhost> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansible -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost '/bin/sh -c '"'"'/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1489496890.74-116872432167883/file.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1489496890.74-116872432167883/" > /dev/null 2>&1 && sleep 0'"'"''
--- before
+++ after
@@ -1,4 +1,4 @@
 {
     "path": "/tmp/repo_ansible/", 
-    "state": "absent"
+    "state": "directory"
 }
changed: [localhost] => {
    "changed": true, 
    "diff": {
        "after": "{\n    \"path\": \"/tmp/repo_ansible/\", \n    \"state\": \"directory\"\n}", 
        "before": "{\n    \"path\": \"/tmp/repo_ansible/\", \n    \"state\": \"absent\"\n}"
    }, 
    "gid": 994, 
    "group": "ansible", 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "delimiter": null, 
            "diff_peek": null, 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "group": null, 
            "mode": null, 
            "original_basename": null, 
            "owner": null, 
            "path": "/tmp/repo_ansible/", 
            "recurse": false, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": "directory", 
            "unsafe_writes": null, 
            "validate": null
        }, 
        "module_name": "file"
    }, 
    "mode": "0775", 
    "owner": "ansible", 
    "path": "/tmp/repo_ansible/", 
    "secontext": "unconfined_u:object_r:user_tmp_t:s0", 
    "size": 4096, 
    "state": "directory", 
    "uid": 996
}

TASK [synchronize] *************************************************************
task path: /root/isuse_19336/test.yml:14
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/synchronize.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1489496892.33-13164885003722 `" && echo ansible-tmp-1489496892.33-13164885003722="` echo $HOME/.ansible/tmp/ansible-tmp-1489496892.33-13164885003722 `" ) && sleep 0'
<localhost> PUT /tmp/tmpP0lzyk TO /root/.ansible/tmp/ansible-tmp-1489496892.33-13164885003722/synchronize.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1489496892.33-13164885003722/ /root/.ansible/tmp/ansible-tmp-1489496892.33-13164885003722/synchronize.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1489496892.33-13164885003722/synchronize.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1489496892.33-13164885003722/" > /dev/null 2>&1 && sleep 0'
.d..tpog... ./
>f+++++++++ ansible.cfg
>f+++++++++ test.yml
cd+++++++++ inventory/
cd+++++++++ inventory/test_localhost/
>f+++++++++ inventory/test_localhost/hosts
cd+++++++++ inventory/test_remote/
>f+++++++++ inventory/test_remote/hosts
changed: [localhost] => {
    "changed": true, 
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=22' --out-format='<<CHANGED>>%i %n%L' \"/root/isuse_19336/\" \"/tmp/repo_ansible/\"", 
    "diff": {
        "prepared": ".d..tpog... ./\n>f+++++++++ ansible.cfg\n>f+++++++++ test.yml\ncd+++++++++ inventory/\ncd+++++++++ inventory/test_localhost/\n>f+++++++++ inventory/test_localhost/hosts\ncd+++++++++ inventory/test_remote/\n>f+++++++++ inventory/test_remote/hosts\n"
    }, 
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync", 
            "_substitute_controller": false, 
            "archive": true, 
            "checksum": false, 
            "compress": true, 
            "copy_links": null, 
            "delete": false, 
            "dest": "/tmp/repo_ansible/", 
            "dest_port": 22, 
            "dirs": false, 
            "existing_only": false, 
            "group": null, 
            "links": null, 
            "mode": "push", 
            "owner": null, 
            "partial": false, 
            "perms": null, 
            "private_key": null, 
            "recursive": null, 
            "rsync_opts": null, 
            "rsync_path": null, 
            "rsync_timeout": 0, 
            "set_remote_user": true, 
            "src": "/root/isuse_19336/", 
            "ssh_args": null, 
            "times": null, 
            "verify_host": false
        }
    }, 
    "msg": ".d..tpog... ./\n>f+++++++++ ansible.cfg\n>f+++++++++ test.yml\ncd+++++++++ inventory/\ncd+++++++++ inventory/test_localhost/\n>f+++++++++ inventory/test_localhost/hosts\ncd+++++++++ inventory/test_remote/\n>f+++++++++ inventory/test_remote/hosts\n", 
    "rc": 0, 
    "stdout_lines": [
        ".d..tpog... ./", 
        ">f+++++++++ ansible.cfg", 
        ">f+++++++++ test.yml", 
        "cd+++++++++ inventory/", 
        "cd+++++++++ inventory/test_localhost/", 
        ">f+++++++++ inventory/test_localhost/hosts", 
        "cd+++++++++ inventory/test_remote/", 
        ">f+++++++++ inventory/test_remote/hosts"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0   
```

The problem is here. This command is different. I counted on the same behavior of the team.
```
changed: [centos7_1] => {
    "changed": true, 
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=22' --out-format='<<CHANGED>>%i %n%L' \"/home/le9i0nx/isuse_19336/\" \"ansible@centos7_1:/tmp/repo_ansible/\"", 

changed: [localhost] => {
    "changed": true, 
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=22' --out-format='<<CHANGED>>%i %n%L' \"/root/isuse_19336/\" \"/tmp/repo_ansible/\"", 
```
