### ISSUE TITLE
When the tasks with with_items: "{{ var }}" inside a block are always evaluated

### ISSUE THREAD

**Issue by aebm** [ansible/ansible#19347]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Playbook

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A Just pip installed

##### OS / ENVIRONMENT

Ubuntu 14.04.5 LTS x86_64

##### SUMMARY

When a task inside a skipped block has a with_items: "{{ var }}" with var defined inside that block, ansible tries to run that task when it should have skipped (it is inside the block). It doesn't happens when using with_items: var

I summit 2 example playbooks.

##### STEPS TO REPRODUCE

```yaml
--
- name: "Fail"
  hosts: localhost
  gather_facts: False
  vars:
    something: False
  tasks:
  - block:
      - name: "Set fact"
        set_fact:
          stuff: "[0, 1, 2]"
      - debug:
          msg: "Item is: {{ item }}"
        with_items: "{{ stuff }}"
    when: something
```

```yaml
---
- name: "Works"
  hosts: localhost
  gather_facts: False
  vars:
    something: False
  tasks:
  - block:
      - name: "Set fact"
        set_fact:
          stuff: "[0, 1, 2]"
      - debug:
          msg: "Item is: {{ item }}"
        with_items: stuff
    when: something
```

##### EXPECTED RESULTS

To skip the task with with_items that is inside the block skipped

##### ACTUAL RESULTS

```
No config file found; using defaults
Loading callback plugin default of type stdout, v2.0 from /home/alejandro/ansible/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: fail.yml *************************************************************
1 plays in fail.yml

PLAY [Fail] ********************************************************************

TASK [Set fact] ****************************************************************
task path: /home/alejandro/fail.yml:9
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [debug] *******************************************************************
task path: /home/alejandro/fail.yml:12
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "'stuff' is undefined"
}
	to retry, use: --limit @/home/alejandro/fail.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```

```
No config file found; using defaults
Loading callback plugin default of type stdout, v2.0 from /home/alejandro/ansible/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: works.yml ************************************************************
1 plays in works.yml

PLAY [Works] *******************************************************************

TASK [Set fact] ****************************************************************
task path: /home/alejandro/works.yml:9
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [debug] *******************************************************************
task path: /home/alejandro/works.yml:12
skipping: [localhost] => (item=stuff)  => {
    "changed": false, 
    "item": "stuff", 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```
