### ISSUE TITLE
Register variables don't survive across plays with different hosts

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#1934]
If I use register to define a variable in one play in another playbook, if another play in the playbook uses different hosts, that variable isn't set anymore. 

Example, here's a playbook called register.yaml, both plays use the same host:

```
- name: First play in playbook
  gather_facts: False
  hosts: foo

  tasks:
  - name: get the current time for a timestamp
    command: date +%Y%m%d-%H%M%S
    register: time

- name: Second play in playbook
  gather_facts: False
  hosts: foo

  tasks:
  - name: echo the timestamp
    command: echo ${time.stdout}
```

It does what I expect:

```
$ ansible -v register.yaml
PLAY [First play in playbook] ********************* 

TASK: [get the current time for a timestamp] ********************* 
changed: [foo] => {"changed": true, "cmd": ["date", "+%Y%m%d-%H%M%S"], "delta": "0:00:00.006453", "end": "2013-01-28 16:53:46.991040", "rc": 0, "start": "2013-01-28 16:53:46.984587", "stderr": "", "stdout": "20130128-165346"}

PLAY [Second play in playbook] ********************* 

TASK: [echo the timestamp] ********************* 
changed: [foo] => {"changed": true, "cmd": ["echo", "20130128-165346"], "delta": "0:00:00.098823", "end": "2013-01-28 16:53:47.386730", "rc": 0, "start": "2013-01-28 16:53:47.287907", "stderr": "", "stdout": "20130128-165346"}

PLAY RECAP ********************* 
foo               : ok=2    changed=2    unreachable=0    failed=0    
```

But, if I change the host in the second play from foo to bar:

```
- name: First play in playbook
  gather_facts: False
  hosts: foo

  tasks:
  - name: get the current time for a timestamp
    command: date +%Y%m%d-%H%M%S
    register: time

- name: Second play in playbook
  gather_facts: False
  hosts: bar

  tasks:
  - name: echo the timestamp
    command: echo ${time.stdout}
```

Now it no longer evaluates the ${time.stdout} variable in the second play.

```
$ ansible -v register.yaml

PLAY [First play in playbook] ********************* 

TASK: [get the current time for a timestamp] ********************* 
changed: [foo] => {"changed": true, "cmd": ["date", "+%Y%m%d-%H%M%S"], "delta": "0:00:00.097106", "end": "2013-01-28 16:54:01.428042", "rc": 0, "start": "2013-01-28 16:54:01.330936", "stderr": "", "stdout": "20130128-165401"}

PLAY [Second play in playbook] ********************* 

TASK: [echo the timestamp] ********************* 
changed: [bar] => {"changed": true, "cmd": ["echo", "${time.stdout}"], "delta": "0:00:00.004245", "end": "2013-01-28 16:54:05.579452", "rc": 0, "start": "2013-01-28 16:54:05.575207", "stderr": "", "stdout": "${time.stdout}"}

PLAY RECAP ********************* 
bar           : ok=1    changed=1    unreachable=0    failed=0    
foo               : ok=1    changed=1    unreachable=0    failed=0    
```

(Note: If this is the intended behavior, the docs should be updated accordingly).
