### ISSUE TITLE
zfs: can't interpolate property name to set userquota

### ISSUE THREAD

**Issue by dylex** [ansible/ansible#19359]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module system/zfs

##### ANSIBLE VERSION
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides

##### OS / ENVIRONMENT
Linux CentOS7

##### SUMMARY
There is no way to set a dynamic userquota because you can't interpolate key/parameter names, e.g. `userquota@{{account_uid}}=20G`.  In some way this is a more general limitation of ansible, but since it's fairly specific to zfs to want to do this, perhaps the zfs module should provide a solution.  For example:
```
zfs:
  name: path
  state: present
  properties:
    - name: userquota@{{account_uid}}
      value: 20G
    - name: ...
```

##### STEPS TO REPRODUCE
```
zfs: name=path state=present userquota@{{account_uid}}=20G
```

##### EXPECTED RESULTS
Should set userquota@1234=20G (assuming account_uid=1234).

##### ACTUAL RESULTS
```
fatal: [home-0]: FAILED! => {"changed": false, "failed": true, "msg": "cannot set property for 'hdd/home': 'userquota@{{account_uid}}' has an invalid user/group name\n"}
```
