### ISSUE TITLE
jenkins_plugin fails - (item={u'version': 2.0, u'name': u'scm-api'}) => {"details": "HTTP Error 403: Forbidden", "failed": true, "item": {"name": "scm-api", "version": 2.0}, "msg": "Cannot get CSRF"}

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#19351]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

jenkins_plugin

##### ANSIBLE VERSION
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides

##### OS / ENVIRONMENT
management - macOS Sierra
controled machine - AWS EC2 Ubuntu 16.04

Jenkins 2.36

##### STEPS TO REPRODUCE

- name: install plugins
  jenkins_plugin:
    name: "{{ item.name }}"
    version: "{{ item.version }}"
  with_items: "{{ plugins }}"

plugins:
  - name: scm-api
    version: 2.0

##### ACTUAL RESULTS
(item={u'version': 2.0, u'name': u'scm-api'}) => {"details": "HTTP Error 403: Forbidden", "failed": true, "item": {"name": "scm-api", "version": 2.0}, "msg": "Cannot get CSRF"}

**Comment by tumbl3w33d** [comment]
I remember seeing that error when I started working with this module, I just don't exactly remember what was causing it.
Is it possible that you activated Jenkins' security and anonymous has no privileges to install plugins? In that case you need to provide basic auth parameters to the module. You can find the notation in the documentation of the plugin.
```
# my_jenkins_params:
#   url_username: admin
#   url_password: p4ssw0rd
#   url: http://localhost:8888
#
- name: Install plugin
  jenkins_plugin:
    name: build-pipeline-plugin
    params: "{{ my_jenkins_params }}"
```
