### ISSUE TITLE
ansible 2.2: docker_service 'Error starting project - ' 

### ISSUE THREAD

**Issue by manjitkumar** [ansible/ansible#19371]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
docker_service

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /Users/manjit/Desktop/deployement/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Mac OS 10.12.1 

##### SUMMARY

Also a similar issue was reported here - https://github.com/ansible/ansible-modules-core/issues/5513
##### STEPS TO REPRODUCE

```yaml
---

- name: Spin up docker container(s) using docker-compose
  docker_service:
    project_name: "registry"
    project_src: "{{ host_file_paths.docker_root_directory }}"
    state: present
    restarted: true
  tags:
    - docker-up

```

##### EXPECTED RESULTS

It should start the containers, if I run docker-compose from manually it spins up the containers.
##### ACTUAL RESULTS

It fails with error "msg": "Error starting project - . 
```
fatal: [172.31.80.139]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "api_version": null,
            "build": false,
            "cacert_path": null,
            "cert_path": null,
            "debug": false,
            "definition": null,
            "dependencies": true,
            "docker_host": null,
            "files": null,
            "filter_logger": false,
            "hostname_check": false,
            "key_path": null,
            "nocache": false,
            "project_name": "registry",
            "project_src": "/opt/docker",
            "pull": false,
            "recreate": "smart",
            "remove_images": null,
            "remove_orphans": false,
            "remove_volumes": false,
            "restarted": true,
            "scale": null,
            "services": null,
            "ssl_version": null,
            "state": "present",
            "stopped": false,
            "timeout": 10,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null
        },
        "module_name": "docker_service"
    },
    "msg": "Error starting project - "
}
```
