### ISSUE TITLE
include in JINJA2-Template only works if included template is in same directory like the playbook

### ISSUE THREAD

**Issue by tbar74235** [ansible/ansible#19373]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include within JINJA2 Template 

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 6.8

##### SUMMARY

If I use an include within a JINJA2-Template like {% include /configuration/common/standardShellProps.j2' %} this absolute path will be ignored. It works only if I put the standardShellProps.j2 in the same directory where the playbook is which is executing the template module. Then I have to use the include like this: {% include standardShellProps.j2' %}

##### STEPS TO REPRODUCE

Create 2 JINJA2 templates. One of these template should have an include for the other. Place the JINJA2 templates not in the same directory where your playbook is.
Create a playbook which is using the template module and use as src one of your two created JINJA2 templates which contains the include of the other.
Then execute your created playbook and you will get for example
FAILED! => {"changed": false, "failed": true, "msg": "TemplateNotFound: /configuration/common/standardShellProps.j2"}

```yaml
---
- hosts: "{{ host }}"
  tasks:
  - name: filter launcher standard template and copy it to the remote machine
    template:
      src: "/configuration/product/postlauncher.j2"
      dest: "{{ base_dir }}/{{ inventory_hostname }}.appserver.launch"
```

##### EXPECTED RESULTS

FAILED! => {"changed": false, "failed": true, "msg": "TemplateNotFound: /configuration/common/standardShellProps.j2"}

##### ACTUAL RESULTS

fatal: [machine01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "dest": "/opt/myapp/machine01.appserver.launch", 
            "src": "/configuration/product/postlauncher.j2"
        }, 
        "module_name": "template"
    }, 
    "msg": "TemplateNotFound: /configuration/common/standardShellProps.j2"
}

```
fatal: [machine01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "dest": "/opt/myapp/machine01.appserver.launch", 
            "src": "/configuration/product/postlauncher.j2"
        }, 
        "module_name": "template"
    }, 
    "msg": "TemplateNotFound: /configuration/common/standardShellProps.j2"
}
```
