### ISSUE TITLE
[regression over 2.2] ios_config now returning .updates

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#19382]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel a28d898c29) last updated 2016/12/13 11:36:33 (GMT +100)
```

##### SUMMARY
`ios_config` is returning `.updates` which it didn't used to in `stable-2.2` in this case

##### STEPS TO REPRODUCE
cd ansible/test/integration
ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvv -i inventory.network ios.yaml

```yaml
---
- debug: msg="START cli/src_basic.yaml"

- name: setup
  ios_config:
    commands:
      - no description
      - no shutdown
    parents:
      - interface Loopback999
    match: none
    provider: "{{ cli }}"

- name: configure device with config
  ios_config:
    src: basic/config.j2
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - "result.changed == true"
# https://github.com/ansible/ansible-modules-core/issues/4807
      - "result.updates is not defined"

```

##### ACTUAL RESULTS
```
TASK [ios_config : configure device with config] *************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/ios_config/tests/cli/src_basic.yaml:14
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/network/ios/ios_config.py
<ios01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<ios01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1481804170.6-178541422532697 `" && echo ansible-tmp-1481804170.6-178541422532697="` echo ~/.ansible/tmp/ansible-tmp-1481804170.6-178541422532697 `" ) && sleep 0'
<ios01> PUT /tmp/tmpCUYPJX TO /home/johnb/.ansible/tmp/ansible-tmp-1481804170.6-178541422532697/ios_config.py
<ios01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1481804170.6-178541422532697/ /home/johnb/.ansible/tmp/ansible-tmp-1481804170.6-178541422532697/ios_config.py && sleep 0'
<ios01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1481804170.6-178541422532697/ios_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1481804170.6-178541422532697/" > /dev/null 2>&1 && sleep 0'
changed: [ios01] => {
    "banners": {}, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "ios01", 
            "lines": null, 
            "match": "line", 
            "multiline_delimiter": "@", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "ios01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "cli", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "replace": "line", 
            "save": false, 
            "src": "interface Loopback999\n description this is a test\n shutdown\n\n", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": true, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "updates": [
        "interface Loopback999", 
        "description this is a test", 
        "shutdown"
    ], 
    "warnings": []
}

TASK [ios_config : assert] ***********************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/ios_config/tests/cli/src_basic.yaml:20
fatal: [ios01]: FAILED! => {
    "assertion": "result.updates is not defined", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "that": [
                "result.changed == true", 
                "result.updates is not defined"
            ]
        }, 
        "module_name": "assert"
    }
}
```
