### ISSUE TITLE
How to access variable from the yaml file executed by command module 

### ISSUE THREAD

**Issue by BruceZu** [ansible/ansible#19419]
I read the the page of https://docs.ansible.com/ansible/playbooks_conditionals.html#register-variables
and did not find answer.
I searched the issues using 'variable in temple file'  did not find related topic .
 

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 

##### COMPONENT NAME
command module

##### ANSIBLE VERSION

```
]# ansible --version
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
display_args_to_stdout = True
bin_ansible_callbacks = True

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY

# How to access the variable from the template file

##### STEPS TO REPRODUCE
 ` ansible-playbook  playbook2.yaml`

```yaml
 
]# cat playbook2.yaml
---
- hosts: k8s-09
  vars:
    namesapce: ansible
    gitlab_deploy_suffix_name: gitlab
    deploy_yaml_file_path: /root/temp-bruce/deploy-on-k8s/yaml

  remote_user: root
  tasks:
    - name: create namspace {{ namespace }}
      command: kubectl create ns "{{ namesapce }}"

    - name: deploy GitLab
      command: kubectl create -f "{{ deploy_yaml_file_path }}/deploy-gitlab.yaml"
 

 ]# cat yaml/deploy-gitlab.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ namespace }}-gitlab"
  namespace: "{{ namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: "{{ namespace }}-gitlab"
  template:
    metadata:
      labels:
        run: "{{ namespace }}-gitlab"
    spec:
      containers:
      - image: gitlab/gitlab-ce:8.13.6-ce.0
        imagePullPolicy: Always
        name: "{{ namespace }}-gitlab"
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 22
          protocol: TCP
        - containerPort: 80
          protocol: TCP
```

##### EXPECTED RESULTS
I hope the deploy-gitlab.yaml can access variable in playbook

##### ACTUAL RESULTS
 the out put is 
 **_"stderr": "Error from server: error when creating \"/root/temp-bruce/deploy-on-k8s/yaml/deploy-gitlab.yaml\": namespaces \"{{ namespace }}\" not found",_**

`fatal: [k8s-09]: FAILED! => {"changed": true, "cmd": ["kubectl", "create", "-f", "/root/temp-bruce/deploy-on-k8s/yaml/deploy-gitlab.yaml"], "delta": "0:00:00.373881", "end": "2016-12-15 17:27:44.068634", "failed": true, "rc": 1, "start": "2016-12-15 17:27:43.694753", "stderr": "Error from server: error when creating \"/root/temp-bruce/deploy-on-k8s/yaml/deploy-gitlab.yaml\": namespaces \"{{ namespace }}\" not found", "stdout": "", "stdout_lines": [], "warnings": []}`

```
# ansible-playbook  playbook2.yaml  -vvvv
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
 __________________________
< PLAYBOOK: playbook2.yaml >
 --------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

1 plays in playbook2.yaml
 _______________
< PLAY [k8s-09] >
 ---------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _____________________________________________________________
< TASK [Gathering Facts gather_subset=all, gather_timeout=10] >
 -------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r k8s-09 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1481852092.29-141492969320849 `" && echo ansible-tmp-1481852092.29-141492969320849="` echo ~/.ansible/tmp/ansible-tmp-1481852092.29-141492969320849 `" ) && sleep 0'"'"''
<k8s-09> PUT /tmp/tmpG8IPY3 TO /root/.ansible/tmp/ansible-tmp-1481852092.29-141492969320849/setup.py
<k8s-09> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[k8s-09]'
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r k8s-09 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1481852092.29-141492969320849/ /root/.ansible/tmp/ansible-tmp-1481852092.29-141492969320849/setup.py && sleep 0'"'"''
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt k8s-09 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1481852092.29-141492969320849/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1481852092.29-141492969320849/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [k8s-09]
 ___________________________________________________________
/ TASK [create namspace {{ namespace }} _raw_params=kubectl \
\ create ns "{{ namesapce }}"]                              /
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /root/temp-bruce/deploy-on-k8s/playbook2.yaml:10
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r k8s-09 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1481852093.15-191482148497735 `" && echo ansible-tmp-1481852093.15-191482148497735="` echo ~/.ansible/tmp/ansible-tmp-1481852093.15-191482148497735 `" ) && sleep 0'"'"''
<k8s-09> PUT /tmp/tmptoiC5K TO /root/.ansible/tmp/ansible-tmp-1481852093.15-191482148497735/command.py
<k8s-09> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[k8s-09]'
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r k8s-09 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1481852093.15-191482148497735/ /root/.ansible/tmp/ansible-tmp-1481852093.15-191482148497735/command.py && sleep 0'"'"''
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt k8s-09 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1481852093.15-191482148497735/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1481852093.15-191482148497735/" > /dev/null 2>&1 && sleep 0'"'"''
changed: [k8s-09] => {
    "changed": true,
    "cmd": [
        "kubectl",
        "create",
        "ns",
        "ansible"
    ],
    "delta": "0:00:00.353997",
    "end": "2016-12-15 17:34:53.718154",
    "invocation": {
        "module_args": {
            "_raw_params": "kubectl create ns \"ansible\"",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "rc": 0,
    "start": "2016-12-15 17:34:53.364157",
    "stderr": "",
    "stdout": "namespace \"ansible\" created",
    "stdout_lines": [
        "namespace \"ansible\" created"
    ],
    "warnings": []
}
 _______________________________________________________
/ TASK [deploy GitLab _raw_params=kubectl create -f "{{ \
\ deploy_yaml_file_path }}/deploy-gitlab.yaml"]         /
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /root/temp-bruce/deploy-on-k8s/playbook2.yaml:13
Using module file /usr/lib/python2.7/site-packages/ansible/modules/commands/command.py
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r k8s-09 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1481852093.79-85714900271576 `" && echo ansible-tmp-1481852093.79-85714900271576="` echo ~/.ansible/tmp/ansible-tmp-1481852093.79-85714900271576 `" ) && sleep 0'"'"''
<k8s-09> PUT /tmp/tmp69NynX TO /root/.ansible/tmp/ansible-tmp-1481852093.79-85714900271576/command.py
<k8s-09> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[k8s-09]'
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r k8s-09 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1481852093.79-85714900271576/ /root/.ansible/tmp/ansible-tmp-1481852093.79-85714900271576/command.py && sleep 0'"'"''
<k8s-09> ESTABLISH SSH CONNECTION FOR USER: root
<k8s-09> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt k8s-09 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1481852093.79-85714900271576/command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1481852093.79-85714900271576/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [k8s-09]: FAILED! => {
    "changed": true,
    "cmd": [
        "kubectl",
        "create",
        "-f",
        "/root/temp-bruce/deploy-on-k8s/yaml/deploy-gitlab.yaml"
    ],
    "delta": "0:00:00.392720",
    "end": "2016-12-15 17:34:54.377463",
    "failed": true,
    "invocation": {
        "module_args": {
            "_raw_params": "kubectl create -f \"/root/temp-bruce/deploy-on-k8s/yaml/deploy-gitlab.yaml\"",
            "_uses_shell": false,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "warn": true
        },
        "module_name": "command"
    },
    "rc": 1,
    "start": "2016-12-15 17:34:53.984743",
    "stderr": "Error from server: error when creating \"/root/temp-bruce/deploy-on-k8s/yaml/deploy-gitlab.yaml\": namespaces \"{{ namespace }}\" not found",
    "stdout": "",
    "stdout_lines": [],
    "warnings": []
}
        to retry, use: --limit @/root/temp-bruce/deploy-on-k8s/playbook2.retry
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

k8s-09                     : ok=2    changed=1    unreachable=0    failed=1

```

**Comment by mkwardakov** [comment]
Hi @BruceZu ,
did you deploy `deploy-gitlab.yaml` using template module?
and, i noticed a typo in your `playbook2.yaml`:
```
namesapce: ansible
```
could that be the issue?

**Comment by BruceZu** [comment]
Hi @mkwardakov 
Thank you for shedding light here.
I will fix that typo and try again once I get in office.
What is the template module? is it the new feature talked in https://github.com/kubernetes/kubernetes/pull/14918
like the case said in it: 
kubectl run --generator=template.yaml --name=foo --image=nginx --port=8080

**Comment by mkwardakov** [comment]
@BruceZu template module: http://docs.ansible.com/ansible/template_module.html
task takes a file in roles' `templates`, applies jinja2 filters to it and put it in specified path

**Comment by BruceZu** [comment]
Hi, @mkwardakov 
I fix that typo, test and find the same error.
But template module save me.
It works now.
Thank you so much!
```
 ]# cat playbook2.yaml
---
- hosts: k8s-09
  vars:
    namespace: ansible
    gitlab_deploy_suffix_name: gitlab
    deploy_yaml_file_path: /root/temp-bruce/deploy-on-k8s/yaml
    gitlab_deploy_image: gitlab/gitlab-ce:8.13.6-ce.0
  remote_user: root
  tasks:
    - name: create namespace {{ namespace }}
      command: kubectl create ns "{{ namespace }}"
    - name: copy template file
      template:
        src: "{{ deploy_yaml_file_path }}/deploy-gitlab.yaml"
        dest: /root/deploy-gitlab.yaml
    - name: deploy GitLab
      command: kubectl create -f deploy-gitlab.yaml
]# cat yaml/deploy-gitlab.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ namespace }}-gitlab"
  namespace: "{{ namespace }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      run: "{{ namespace }}-gitlab"
  template:
    metadata:
      labels:
        run: "{{ namespace }}-gitlab"
    spec:
      containers:
      - image: "{{ gitlab_deploy_image }}"
        imagePullPolicy: Always
        name: "{{ namespace }}-gitlab"
        ports:
        - containerPort: 443
          protocol: TCP
        - containerPort: 22
          protocol: TCP
        - containerPort: 80
          protocol: TCP
```
run and the output as:

```
]# ansible-playbook  playbook2.yaml
 _______________
< PLAY [k8s-09] >
 ---------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 _____________________________________________________________
< TASK [Gathering Facts gather_subset=all, gather_timeout=10] >
 -------------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [k8s-09]
 ___________________________________________________________
/ TASK [create namespace ansible _raw_params=kubectl create \
\ ns "{{ namespace }}"]                                     /
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [k8s-09]
 _________________________________________________________
/ TASK [copy template file dest=/root/deploy-gitlab.yaml, \
\ src={{ deploy_yaml_file_path }}/deploy-gitlab.yaml]     /
 ---------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [k8s-09]
 ___________________________________________________
/ TASK [deploy GitLab _raw_params=kubectl create -f \
\ deploy-gitlab.yaml]                               /
 ---------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

changed: [k8s-09]
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

k8s-09                     : ok=4    changed=3    unreachable=0    failed=0
```
