### ISSUE TITLE
ec2 module attempting to terminate unrelated instance outside of inventory when using exact_count, instance_tags, and count_tag

### ISSUE THREAD

**Issue by oucil** [ansible/ansible#19427]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel f1b5dde4cb) last updated 2016/12/16 05:20:05 (GMT -400)
  config file = /home/ecms/horizons_v2/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When iterating over inventory to launch a set of role instances with `exact_count`, `instance_tags`, `count_tag` all set, and no matching instances running, Ansible is attempting to terminate a completely unrelated instance in another VPC and subnet (the instance running Ansible). I was lucky that I had termination protection enabled on that instance.

##### STEPS TO REPRODUCE

```yaml
  - name: Launch instance
    ec2:
      aws_access_key: "{{ aws.access_key }}"
      aws_secret_key: "{{ aws.secret_key }}"
      instance_tags: {"Name":"{{ inventory_hostname }}"}
      exact_count: 1
      count_tag: Name
      key_name: "{{ instance.key_name }}"
      group: "{{ instance.security_group }}"
      instance_type: "{{ instance.type }}"
      image: "{{ instance.image }}"
      wait: true
      region: "{{ aws.region }}"
      vpc_subnet_id: "{{ instance.vpc_subnet_id }}"
      assign_public_ip: "{{ instance.public_ip }}"
      instance_profile_name: "{{ aws.iam_role }}"
      source_dest_check: "{{ instance.source_dest_check }}"
      volumes: "{{ instance.volumes }}"
    register: ec2
```

##### EXPECTED RESULTS
I expect Ansible to only work with the instances that are defined in my inventory, it SHOULD NOT be touching anything outside of that inventory.

##### ACTUAL RESULTS
Instead, Ansible is spitting out a fatal error for each instance in my inventory, but referencing the ID of the unrelated instance in the other VPC/subnet, illustrated below with `i-aaaaaaaa`.

```
fatal: [host.domain.internal]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "assign_public_ip": true,
            "aws_access_key": "*************************",
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "count": 1,
            "count_tag": "Name",
            "ebs_optimized": false,
            "ec2_url": null,
            "exact_count": 1,
            "group": [
                "loadbalancer"
            ],
            "group_id": null,
            "id": null,
            "image": "ami-b73b63a0",
            "instance_ids": null,
            "instance_initiated_shutdown_behavior": null,
            "instance_profile_name": "server",
            "instance_tags": {
                "Name": "host.domain.internal"
            },
            "instance_type": "c3.large",
            "kernel": null,
            "key_name": "host",
            "monitoring": false,
            "network_interfaces": null,
            "placement_group": null,
            "private_ip": null,
            "profile": null,
            "ramdisk": null,
            "region": "us-east-1",
            "security_token": null,
            "source_dest_check": true,
            "spot_launch_group": null,
            "spot_price": null,
            "spot_type": "one-time",
            "spot_wait_timeout": "600",
            "state": "present",
            "tenancy": "default",
            "termination_protection": null,
            "user_data": null,
            "validate_certs": true,
            "volumes": [
                {
                    "delete_on_termination": true,
                    "device_name": "/dev/xvda",
                    "volume_size": 10,
                    "volume_type": "gp2"
                }
            ],
            "vpc_subnet_id": "subnet-********",
            "wait": true,
            "wait_timeout": "300",
            "zone": null
        },
        "module_name": "ec2"
    },
    "msg": "Unable to terminate instance i-aaaaaaaa, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>OperationNotPermitted</Code><Message>The instance 'i-aaaaaaaa' may not be terminated. Modify its 'disableApiTermination' instance attribute and try again.</Message></Error></Errors><RequestID>d3a71576-0376-4293-b5ec-9ce9d241fee1</RequestID></Response>"
```
