### ISSUE TITLE
show output for meta: end_play

### ISSUE THREAD

**Issue by hloeffler** [ansible/ansible#19433]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

meta

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

meta: end_play lacks output

##### STEPS TO REPRODUCE

normal use of meta: end_play

```yaml
    - name: end if checkmode
      meta: end_play
      when: ansible_check_mode

```

##### EXPECTED RESULTS

output (name of the task)

##### ACTUAL RESULTS

no output

```

```
