### ISSUE TITLE
Add execution-timeout parameter for win_chocolatey

### ISSUE THREAD

**Issue by chrisvire** [ansible/ansible#19447]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

From: Ubuntu 16.04
To: Windows 7

##### SUMMARY

Some chocolatey packages (e.g. `visualstudio2015community`) take longer than the 2700 sec default timeout. Add execution-timeout support.

##### STEPS TO REPRODUCE

```yaml
- name: "Compiler: Visual Studio 2015 Community"
  win_chocolatey:
    name: visualstudio2015community
```

I would like to be able to specify the execution-timeout:

```yaml
- name: "Compiler: Visual Studio 2015 Community"
  win_chocolatey:
    name: visualstudio2015community
    execution_timeout: 100000
```

##### EXPECTED RESULTS
Be able to set the execution-timeout for chocolatey

##### ACTUAL RESULTS
ansible-playbook just hangs and never stops even though chocolatey has timed out.
