### ISSUE TITLE
git module needs better error messages for timeout related errors

### ISSUE THREAD

**Issue by oucil** [ansible/ansible#19440]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel f1b5dde4cb) last updated 2016/12/16 05:20:05 (GMT -400)
  config file = /home/ecms/horizons_v2/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible's git module reports a hostkey error rather than a timeout when in fact it simply couldn't make a connection at all. Sure, now that I've traced it to a firewall restriction and the ensuing timeout, that makes sense, but this could be a much more insightful and accurate error message.

##### STEPS TO REPRODUCE
Set a security group egress restriction on the ssh port (22), and attempt to do a git clone...

```yaml
- name: checkout application from repository
  git:
    repo: ssh://AAAAAAAAAAAAAAAAAAAA@git-codecommit.us-east-1.amazonaws.com/v1/repos/somerepo
    dest: "{{ app_home }}"
    key_file: /home/ec2-user/deploy.pem
    accept_hostkey: yes
    force: yes
```

##### EXPECTED RESULTS
```
2016-12-16 06:47:20,756 p=11741 u=user |  fatal: [host.domain.internal]: FAILED! => {"changed": false, "failed": true, "msg": "git connection timed out, waited 60s"}
```

##### ACTUAL RESULTS
Instead of a timeout related error, the error message refers to failing to get the hostkey.  
```
2016-12-16 06:47:20,756 p=11741 u=user |  fatal: [host.domain.internal]: FAILED! => {"changed": false, "failed": true, "msg": "failed to get the hostkey for git-codecommit.us-east-1.amazonaws.com"}
```
