### ISSUE TITLE
Assemble module ordering enhancement

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible/ansible#19442]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
assemble

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Ubuntu
##### SUMMARY

Would like the ability to assemble by means other than alphabetically. Namely by a list of files, or list of files in a specific directory. Becomes difficult to manage when you must prepend each file with number, e.g. 

110_tacacs
120_aaa
130_acl

Then realize you need 115_routing, etc... 

##### STEPS TO REPRODUCE

I envision something similar to: 

```yaml

- assemble:
    src_files:
      - /var/config/ny-sw01/route
      - /var/config/ny-sw01/aaa
      - /var/standard/acl
    dest: /var/finalconfig/ny-sw01/run.cfg

and
- assemble:
    src_root: /var/config/sw01
    src_files:
      - route
      - aaa
      - acl
    dest: /var/finalconfig/ny-sw01/run.cfg

```

The assemble happens in order of list, not alphabetical 

Only alphabetical 

N/A
