### ISSUE TITLE
unarchive and fetch action plugins report bogus error on failure

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#19494]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

action_plugins

##### ANSIBLE VERSION

v2.2 and earlier

##### SUMMARY

Internal action-plugin functions that call remote modules internally report bogus errors on failure

##### STEPS TO REPRODUCE

Consider the following playbook
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - unarchive:
      src: test126.tar.bz2
      dest: /tmp
    become: yes                                                                                                                        
    become_user: foobar
```

And consider the fact that the user **foobar** does not exist, so sudo obviously fails.
(This is a minimal reproducer, the real test-case was reported on IRC)

##### EXPECTED RESULTS

A proper error message so the user can fix the real issue.

##### ACTUAL RESULTS

Instead we get the bogus error message: **python isn't present on the system.  Unable to compute checksum**

```
[dag@moria ansible.testing]$ ansible-playbook -v test137.yml
Using /home/dag/home-made/ansible.testing/ansible.cfg as config file

PLAY [localhost] **********************************************************************************************************************

TASK [unarchive] **********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "python isn't present on the system.  Unable to compute checksum"}

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by xenithorb** [comment]
Hi, I'm the IRC mention in the ticket and I originally noticed the problem when trying to add Fedora support to my Rocket.Chat.Ansible role. The actual task that fails is: 

```yaml
  - name: Unpack the Rocket.Chat binary tarball
    unarchive:
      copy: false
      src: "{{ rocket_chat_application_path }}/rocket.chat-{{ rocket_chat_version }}.tgz"
      dest: "{{ rocket_chat_application_path }}"
      creates: "{{ rocket_chat_application_path }}/bundle"
    become: true
    become_user: "{{ rocket_chat_service_user }}"
    tags: build
```
This does in fact fail in the exact way described above, and is very misleading. (Especially since this is on Fedora where it is recommended to bootstrap python2 since it is not present by default. 

#### As it turns out the actual issue is:

The actual bug that caused this problem in the first place is that _on Fedora and apparently no other system_, the following play fails:

```yaml
---

- hosts: all
  connection: local
  become: yes
  tasks:

    - shell: whoami

    - shell: whoami
      become_user: daemon
      become: yes
```
* The user is not important, nor is the connection type, but this will fail on Fedora 
* The actual task is unimportant also, any task with `become_user` and `become` will do.

With the output:

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE"}
        to retry, use: --limit @/home/xenith/.ansible-retry/foo.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

For the layman, it appears that for some reason on Fedora alone, become is downgrading itself to the original SSH user before assuming the next identity, even when the play is run with `become: yes` itself to assume root first.

**Comment by xenithorb** [comment]
Quick mention that my personal workaround was to use the `user:` and `group:` attributes to the unarchive module instead of trying to assume the UID. 

I do think that the best course of action is to make the message clearer about the problem, but there is definitely something wrong (or very very right) with the way `become:` is working on Fedora systems.

**Comment by xenithorb** [comment]
@dagwieers Should I file my snippet as a separate bug? I tried searching through the the backlog and didn't see anything that specifically mentioned Fedora and `become_user`

**Comment by dagwieers** [comment]
@xenithorb I don't think there is an Ansible bug with Fedora and sudo. The behaviour is different, but that's completely related to Fedora. If you want to sudo to a user, it's the user's responsibility that it works regardless of the OS. If the user's shell is /bin/false and sudo/su fails because of that, the user will have to change whatever is required to make it work. (i.e. we are not going to modify Ansible to change stuff behind the user's back in order to make it work out of the box.)

PS I don't know exactly what was changes in Fedora, or even if something has changed. Maybe their default configuration is different, and it works as designed.

**Comment by xenithorb** [comment]
It's not failing because of the shell defined in `/etc/passwd` though. I can verify this because the exact same tasks (including the examples above) work just fine in CentOS, or Ubuntu, or Debian, and they all have the same `/bin/false` for the user. 

Bear in mind the prerequisite here is that the play itself must be `become: true` indicating that the play is running with sudo (or basically as root). 

In my mind, and since it works everywhere else, root should definitely be able to assume any identity on Fedora.

**Comment by xenithorb** [comment]
I have another task that I can't get around this time ( maybe I'm just not creative enough ) but  really do need `become_user` here: 

```yaml
  - name: Install Rocket.Chat via NPM
    npm:
      state: present
      path: "{{ rocket_chat_application_path }}/bundle/programs/server"
      executable: "{{ rocket_chat_npm_path }}"
    become: true
    become_user: "{{ rocket_chat_service_user }}"
    tags: build
```
Again, **only fails on fedora**, with:

```
fatal: [Fedora24]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "npm"
    },
    "module_stderr": "Shared connection to 192.168.121.35 closed.\r\n",
    "module_stdout": "sudo: a password is required\r\n",
    "msg": "MODULE FAILURE"
}
        to retry, use: --limit @/home/xenith/.ansible-retry/provision.retry

**Comment by dagwieers** [comment]
@xenithorb That's not proof (and it was just an example). Fact is Ansible relies on a working sudo, and on Fedora it apparently does not work. That's not Ansible's fault and something you will have to troubleshoot and fix in your Fedora setup. (Could be sudo, pam, selinux, or whatever...)

**Comment by xenithorb** [comment]
Sudo does work though, I can, as root, execute the task with `sudo -u rocketchat` no problem. The only time you get the "as password is required" message is when you're a normal user trying to assume the identity of another user, which is how I know it's doing that on fedora as the non-root user. The only other non-root user ansible could possibly be using is the one we've SSH as.

**Comment by dagwieers** [comment]
@xenithorb Sigh, that's what I asked you on IRC. I was assuming that you were using another user to SSH, and that become would go from ansible-user to rocketchat-user. You told me you were running Ansible on targets as root. So is it possible that you have a sudoers configuration allowing this on CentOS, Ubuntu and Debian, but not on Fedora ?

**Comment by xenithorb** [comment]
I'm _not_ sshing as root. The playbook sshs to the host as a normal user, but the _play_ is set as `become: yes` and it was always my understanding that doing so makes all tasks below run as root. I confirmed as much in my example because `- shell: whoami` in an arbitrary location shows `"root"`. 

Therefore root should definitely be able to assume the identity of `rocketchat` but that's not working, and I'm pretty sure it's because ansible isn't using the root account to do `become_user` for whatever reason on Fedora _only_

**Comment by dagwieers** [comment]
Something like */etc/sudoers.d/ansible
```
ansible-user ALL=(rocketchat) NOPASSWD: ALL
```

**Comment by dagwieers** [comment]
If you do `become: yes` it will default to `become_user: root`. But if you also do `become_user: rocketchat`, it will go from your ansible-user directly to user rocketchat. And that behaviour is exactly the same for Debian, CentOS and Ubuntu.

**Comment by xenithorb** [comment]
Yes a file like that is always present. How could I `- shell: whoami` == "root" without it?

**Comment by dagwieers** [comment]
The file allows the ansible-user to run something as rocket-chat, not root.

**Comment by xenithorb** [comment]
Ah right I glossed over that detail

**Comment by dagwieers** [comment]
Please check your configuration exactly on the other systems to understand what you are doing there to allow ansible-user to become user rocketchat. Please test if that works on CentOS.

**Comment by xenithorb** [comment]
In this example: 

```
---

- hosts: all
  become: yes
  tasks:

    - shell: whoami

    - shell: whoami
      become_user: daemon
      become: yes
```

If I connect via SSH as user: `ansible` with `become: yes` as a play-level directive, it causes each task to be as root, yes? 

You are saying that in the latter task, `become_user: daemon` as a subset of the `become: yes` play is attempting to become that user as the `ansible` user and NOT the root user? 

I believe you, but that doesn't seem intuitive, nor is it documented here: https://docs.ansible.com/ansible/become.html

**Comment by dagwieers** [comment]
The first task will be run as root (coming from user ansible), the second task will be run as user daemon (coming from user ansible). It is really not that hard.

What you typed is exactly the same as:
```yaml
---
- hosts: all
  become: yes
  tasks:
    - shell: whoami
      become_user: root

    - shell: whoami
      become_user: dag
```

And lo and behold:
```
[dag@moria ansible.testing]$ ansible-playbook -v test138.yml
Using /home/dag/home-made/ansible.testing/ansible.cfg as config file

PLAY [localhost] **********************************************************************************************************************

TASK [command] ************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.006463", "end": "2016-12-18 22:20:44.505822", "rc": 0, "start": "2016-12-18 22:20:44.499359", "stderr": "", "stdout": "root", "stdout_lines": ["root"], "warnings": []}

TASK [command] ************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": "whoami", "delta": "0:00:00.005889", "end": "2016-12-18 22:20:44.969993", "rc": 0, "start": "2016-12-18 22:20:44.964104", "stderr": "", "stdout": "dag", "stdout_lines": ["dag"], "warnings": []}

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   
```

Beware, the `connection: local` may be confusing you. Because the `connection: local` does NOT use SSH and so what you run, will be run as your own user.

But, this is not a support forum, and this has nothing to do with this issue (and is not an issue in itself). So let us end the discussion here, because it is making everything very confusing for people that simply want to see if this issue affects them. (It's probably better to remove all comments not related to this issue)
