### ISSUE TITLE
Playbook, doesn't trigger rescue block / completely aborts, when referring to an unreferenced handler

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#19498]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Handler referencing

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

Vanilla Ansible configuration

##### OS / ENVIRONMENT

Debian GNU/Linux stretch/sid

##### SUMMARY

Using a playbook with a tasks and rescue block, and a handler. Referring to an unreferenced handler borks the playbook run immediately without triggering the rescue block.

##### STEPS TO REPRODUCE

```yaml
---
- name: Playbook - playbook.yml
  connection: local
  hosts: all

  tasks:
    - block:
        - name: Playbook - playbook.yaml - tasks - block - File modification - /tmp/red
          copy:
            content: 'red'
            dest: /tmp/red
            owner: root
            group: root
            mode: 0644
          notify:
            - restart systemd-timesyncd.service

        - name: Playbook - playbook.yaml - tasks - block - File modification - /tmp/blue
          copy:
            content: 'blue'
            dest: /tmp/blue
            owner: root
            group: root
            mode: 0644

      rescue:
        - name: Playbook - playbook.yaml - tasks - rescue - Log error to systemd journal
          shell: echo 'WOOPS' | systemd-cat -t ansible
          ignore_errors: true
          changed_when: false

  handlers:
    - name: restart systemd-timesyncd.serviceeeeeeee
      service:
        name: systemd-timesyncd.service
        state: restarted
```

##### EXPECTED RESULTS

Our general expectation was for the rescue block to be triggered upon the 'unreferenced handler' error reported by Ansible

##### ACTUAL RESULTS

```
With properly referenced handler:
machine.subnet.branch.domain.tld # ansible-playbook -i localhost, playbook.yml

PLAY [Playbook - playbook.yml] *************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Playbook - playbook.yaml - tasks - block - File modification - /tmp/red] *
changed: [localhost]

TASK [Playbook - playbook.yaml - tasks - block - File modification - /tmp/blue]
changed: [localhost]

RUNNING HANDLER [restart systemd-timesyncd.service] ****************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0

machine.subnet.branch.domain.tld #


With improperly referenced handler:
machine.subnet.branch.domain.tld # ansible-playbook -i localhost, playbook.yml

PLAY [Playbook - playbook.yml] *************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Playbook - playbook.yaml - tasks - block - File modification - /tmp/red] *
ERROR! The requested handler 'restart systemd-timesyncd.service' was not found in either the main handlers list nor in the listening handlers list
machine.subnet.branch.domain.tld #
```
