### ISSUE TITLE
vsphere_guest: datastore does not exist when deploying on esxi 6

### ISSUE THREAD

**Issue by christiancruz11** [ansible/ansible#19495]
I don't see any issue reported similar to this.
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

[defaults]
inventory      = /etc/ansible/hosts
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 5
poll_interval  = 15
sudo_user      = root
transport      = smart
module_lang    = C
gathering = smart
roles_path    = $HOME
sudo_exe = sudo
timeout = 10
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins
fact_caching = memory
retry_files_enabled = False
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
ssh_args = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  -o ControlMaster=auto -o ControlPersist=60s
pipelining = false
[accelerate]
accelerate_port = 5099
accelerate_timeout = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout = 1
[selinux]
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 6.7 (Santiago)
2.6.32-573.22.1.el6.x86_64
##### SUMMARY

We have a playbook that provision a VM. We run this from Ansible tower.
It works on ESXi 5 but fails on ESXi 6.
We tried to hard code the datastore but still same error.
Opened issue previously to ansible-modules-core:
https://github.com/ansible/ansible-modules-core/issues/5718#issuecomment-262686804
##### STEPS TO REPRODUCE

Use vsphere_guest module to create VM. Use iso to boot from.

```yaml
This the play where it failed. This play is run from a role that we created.
   - name: Creating VM
     vsphere_guest:
      vcenter_hostname: "{{env}}"
      username: "{{user_name}}"
      password: "{{password}}"
      guest: "{{item.0}}"
      state: powered_on
      vm_extra_config:
       vcpu.hotadd: yes
       mem.hotadd:  yes
      vm_disk:
        disk1:
         size_gb: 70
         type: thin
         datastore: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
      vm_nic:
        nic1:
         type: vmxnet3
         network: "{{vlan_prefix}}130"
         network_type: dvs
      vm_hardware:
       memory_mb: "{{item.1}}"
       num_cpus: "{{item.2}}"
       osid: centos64Guest
       scsi: paravirtual
       vm_cdrom:
        type: "iso"
        iso_path: "{{isods}}/ISOs/xxxxxxxxxxxxxxx.{{item.0}}.iso"
      esxi:
       datacenter: "{{datacenter}}"
       hostname: "{{esx_server.stdout}}"
      validate_certs: False
     register: vm_create
     with_together:
       - "{{server_name}}.xxxxxxxxxxxxxxxxxxxxxxxx"
       - "{{memory}}"
       - "{{cpu}}"
```

##### EXPECTED RESULTS

It should create the VM and boot from ISO.
##### ACTUAL RESULTS

It failed and the error is the datastore does not exist.
"msg": "Datastore: u'xxxxxxxxxxxxxxxxxxxxx does not appear to exist"}

```
TASK [vm-provision : Creating VM] **********************************************
task path: /var/lib/awx/projects/vm-provision-project-test/roles/vm-provision/tasks/create-vm.yml:16
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<127.0.0.1> EXEC /bin/sh -c 'LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python2.6 && sleep 0'
failed: [localhost] (item=[u'xxxxxxxxxxxxxxxxxxxxx', u'2048', u'1']) => {"failed": true, "invocation": {"module_args": {"cluster": null, "esxi": {"datacenter": "Kapiti Datacenter", "hostname": "xxxxxxxxxxx"}, "force": false, "from_template": null, "guest": "xxxxxxxxxxxxxxxxx", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "power_on_after_clone": true, "resource_pool": null, "snapshot_to_clone": null, "state": "powered_on", "template_src": null, "username": "xxxxxxxx", "validate_certs": false, "vcenter_hostname": "u'xxxxxxxxxxxxxxxxxxxxx", "vm_disk": {"disk1": {"datastore": "u'xxxxxxxxxxxxxxxxxxxxx", "size_gb": 70, "type": "thin"}}, "vm_extra_config": {"mem.hotadd": true, "vcpu.hotadd": true}, "vm_hardware": {"memory_mb": "2048", "num_cpus": "1", "osid": "centos64Guest", "scsi": "paravirtual", "vm_cdrom": {"iso_path": "u'xxxxxxxxxxxxxxxxxxxxx/ISOs/u'xxxxxxxxxxxxxxxxxxxxx-auto-build.u'xxxxxxxxxxxxxxxxxxxxx.iso", "type": "iso"}}, "vm_hw_version": null, "vm_nic": {"nic1": {"network": "u'xxxxxxxxxxxxxxxxxxxxx", "network_type": "dvs", "type": "vmxnet3"}}, "vmware_guest_facts": null}, "module_name": "vsphere_guest"}, "item": ["u'xxxxxxxxxxxxxxxxxxxxx", "2048", "1"], "msg": "Datastore: u'xxxxxxxxxxxxxxxxxxxxx does not appear to exist"}
```

**Comment by christiancruz11** [comment]
@bcoca and @Abdul-Anshad-A appreciate if you can have a look on this. Thanks in advance.

**Comment by Abdul-Anshad-A** [comment]
@christiancruz11 If possible, could you please run the below python snippet against both host( ESXi 5 and ESXi 6) and post the output here ?

Replace the ESXi_hostname, username and password with appropriate values.

```
from pysphere import VIServer
from pysphere import VIServer, VIProperty, MORTypes
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

server = VIServer()
server.connect("ESXi_hostname", "username", "password")

for ds_mor, ds_name in server.get_datastores().items():
        ds_props = VIProperty(server, ds_mor)
        print("Datastore - %s, Accessible - %s" %(ds_name, ds_props.summary.accessible))
```

**Comment by christiancruz11** [comment]
Hi @Abdul-Anshad-A 

Thanks for your response.
It looks like its able to see the datastore on both ESXi 5 and ESXi 6.

ESXi 5:
[cruzc@kdclat5001 playbooks]$ python datastore.py
Datastore - ESX_DEV_Green_DP8_SR10, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR14, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR13, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR8, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR12, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR4, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR11, Accessible - True
Datastore - Local_KDCVMH5001, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR9, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR1, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR0, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR3, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR2, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR5, Accessible - True
Datastore - ESX_DEV_GreenTemplate_DP8_SR2, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR7, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR6, Accessible - True
[cruzc@kdclat5001 playbooks]$ 

ESXi 6:
[cruzc@kdclat5001 playbooks]$ python datastore.py
Datastore - KDCVMH1100_San_Boot, Accessible - True
Datastore - Local_KDCVMH0401, Accessible - True
Datastore - KDCVMH1103_San_Boot, Accessible - True
Datastore - KDCVMH1010_San_Boot, Accessible - True
Datastore - ESX_PRD_Management_Cluster_DS2, Accessible - True
Datastore - Local_KDCVMH0400, Accessible - True
Datastore - KDCVMH5002 San Boot, Accessible - True
Datastore - KDCVMH5210 SAN Boot, Accessible - True
Datastore - ESX_Purple_SR1, Accessible - True
Datastore - KDCVMH1012_San_Boot, Accessible - True
Datastore - KDCVMH5006 San Boot, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR12, Accessible - True
Datastore - ESX_GreenPRD-DS01_VSP_DP3_FMD_SAS_HDT, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR14, Accessible - True
Datastore - ESX_PRD_Green_DP3_SD1, Accessible - True
Datastore - KDCVMH5005 SAN Boot, Accessible - True
Datastore - KDCVMH5013 San Boot, Accessible - True
Datastore - KDCVMH5110_San _Boot, Accessible - True
Datastore - ESX_GreenDEV-DS02_VSP_DP8_SAS_NLSAS_HDT, Accessible - True
Datastore - KDCVMH1101_San_Boot, Accessible - True
Datastore - ESX_Purple_SR0, Accessible - True
Datastore - KDCVMH5014 SAN Boot, Accessible - True
Datastore - KDCVMH1102_San_Boot, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR13, Accessible - True
Datastore - KDCVMH1011_San_Boot, Accessible - True
Datastore - KDCVMH1104_San_Boot, Accessible - True
Datastore - ESX_GreenPRD-DS01_VSP_DP7_SAS_NLSAS_HDT, Accessible - True
Datastore - ESX_Purple_Templates, Accessible - True
Datastore - ESX_KDC_ISOs_Templates, Accessible - True
Datastore - KDCVMH1109_San_Boot, Accessible - True
Datastore - KDCVMH5200 San Boot, Accessible - True
Datastore - KDCVMH5102_San_Boot, Accessible - True
Datastore - ESX_DEV_DMZ_DP7_ISO_Templates, Accessible - True
Datastore - ESX_DEV_DMZ_DP7_DS1, Accessible - True
Datastore - KDCVMH1107_San_Boot, Accessible - True
Datastore - KDCVMH1108_San_Boot, Accessible - True
Datastore - Local_KDCVMH0500, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR0, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR1, Accessible - True
Datastore - KDCVMH1106_San_Boot, Accessible - True
Datastore - ESX_Orange_SR0, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR10, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR11, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR8, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR9, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR6, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR7, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR4, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR5, Accessible - True
Datastore - KDCVMH5003 San Boot, Accessible - True
Datastore - ESX_DEV_GreenTemplate_DP8_SR2, Accessible - True
Datastore - KDCVMH5101_San_Boot, Accessible - True
Datastore - KDCVMH5004 San Boot, Accessible - True
Datastore - ESX_GreenPRD-DS02_VSP_DP7_SAS_NLSAS_HDT, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR2, Accessible - True
Datastore - KDCVMH5008 San Boot, Accessible - True
Datastore - KDCVMH5100_San_Boot, Accessible - True
Datastore - ESX_DEV_Green_DP8_SR3, Accessible - True
Datastore - ESX_PRD_Green_DP3_DS10, Accessible - True
Datastore - KDCVMH1150_San_Boot, Accessible - True
Datastore - ESX_PRD_VIDEO_APP_Green_DP0_DS1, Accessible - True
Datastore - KDCVMH5112_San_Boot, Accessible - True
Datastore - KDCVMH1153_San_Boot, Accessible - True
Datastore - KDCVMH5009 San Boot, Accessible - True
Datastore - KDCVMH1154_San_Boot, Accessible - True
Datastore - KDCVMH5111_San_Boot, Accessible - True
Datastore - ESX_GreenDEV-DS01_VSP_DP7_SAS_NLSAS_HDT, Accessible - True
Datastore - ESX_GreenDEV-DS01_VSP_DP8_SAS_NLSAS_HDT, Accessible - True
Datastore - KDCVMH5007 SAS Disk, Accessible - True
Datastore - KDCVMH5007 SAN Boot, Accessible - True
Datastore - ESX_PRD_Management_Cluster_DS1, Accessible - True
Datastore - ESX_DEV_ADTE_SR2, Accessible - True
Datastore - ESX_DEV_ADTE_SR1, Accessible - True
Datastore - ESX_DEV_ADTE_SR0, Accessible - True
Datastore - Local_KDCVMH0501, Accessible - True
Datastore - ESX_Blue_SR0, Accessible - True
Datastore - ESX_Red_SR0, Accessible - True
Datastore - KDCVMH1105_San_Boot, Accessible - True
Datastore - ESX_DEV_General_DP7_DS1, Accessible - True
Datastore - ESX_DEV_ADTE_ISO, Accessible - True
Datastore - ESX_DEV_General_DP7_DS2, Accessible - True
[cruzc@kdclat5001 playbooks]$

**Comment by Abdul-Anshad-A** [comment]
@christiancruz11 Thanks for the update.

I see that datastore "ESX_PRD_VIDEO_APP_Green_DP0_DS1" is present and accessible on ESXi 6 but not on ESXi 5 ??

Also, could you please try running the below playbook directly against ESXi 6 (without Vcenter Server) and see if it succeeds ?

Replace vcenter_hostname, username, password and hostname with ESXi 6 credentials.

```
- name: Create VMware guest
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - vsphere_guest:
     vcenter_hostname: ESXi_6_hostname
     username: username
     password: password
     validate_certs: False
     guest: test_dummy_vm
     state: powered_on
     vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd:  yes
      notes: This is a test VM
     vm_disk:
      disk1:  {datastore: "ESX_PRD_VIDEO_APP_Green_DP0_DS1", size_gb: 6, type: "thin"}
     vm_nic:
      nic1:
        type: vmxnet3
        network: VM Network
        network_type: standard
     vm_hardware:
      memory_mb: 512
      num_cpus: 1
      osid: centos64Guest
      scsi: paravirtual
     esxi:
      datacenter: ha-datacenter
      hostname: ESXi_6_hostname
```
