### ISSUE TITLE
mongodb_user always reports as changed

### ISSUE THREAD

**Issue by BastianVoigt** [ansible/ansible#19504]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
mongodb_user

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT
Ubuntu Linux 16.04

##### SUMMARY
I use the mongodb_user command as part of my playbook for setting up the mongoDB machines. It always reports as changed whenever I run the playbook.

##### STEPS TO REPRODUCE

```yaml
- name: Create MongoDB user and database for some-app
  mongodb_user:
    name: some-app
    database: some-app
    password: "{{ mongodb_some_app_passwd }}"
    replica_set: mongodbpope
    roles:
      - readWrite
    login_database: admin
    login_user: admin
    login_password: "{{ mongodb_admin_passwd }}"
    state: present
```

##### EXPECTED RESULTS
It should report as changed only when the DB user does not already exist.

##### ACTUAL RESULTS

```

```
