### ISSUE TITLE
with_items on mydict.keys() fails with AnsibleUndefinedVariable error

### ISSUE THREAD

**Issue by RemiCardona** [ansible/ansible#19514]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
file and/or template

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.0.0
  config file = /home/rcardona/Projects/devtools/dev-servers/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```ini
[defaults]
hostfile = ./hosts.ini
jinja2_extensions =  jinja2.ext.with_
vault_password_file = .vault-password-file.txt
roles_path = roles/shared:roles/playbook
callback_plugins = plugins/callbacks
filter_plugins = plugins/filters
retry_files_enabled = False

[privilege_escalation]
become_ask_pass=True

[github]
token_uri = ./vars/vault.yml#vault.github_token
organization = Polyconseil

# Needed because of: https://github.com/ansible/ansible/issues/13401
[ssh_connection]
scp_if_ssh=True

[slack]
token_key = ./vars/vault.yml#vault.slack_ansible_token
```

##### OS / ENVIRONMENT
```
$ python --version
Python 3.4.2
 $ head -n1 /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
```

##### SUMMARY

`with_items` on `mydict.keys()` fails with `AnsibleUndefinedVariable` error

##### STEPS TO REPRODUCE

```yaml
- name: Add client configuration entries
  template:
    src: client-config-dir-entry.j2
    dest: /etc/openvpn/clients/{{ item }}
  with_items: "{{ openvpn_clients.keys() }}"
```
I had to rework the playbook to 
```yaml
- name: Add client configuration entries
  template:
    src: client-config-dir-entry.j2
    dest: /etc/openvpn/clients/{{ item.key }}
  with_dict: "{{ openvpn_clients }}"
```
and update my template accordingly.

##### EXPECTED RESULTS

Used to work on python2.7. Looks like a py3k regression.

##### ACTUAL RESULTS
```
TASK [openvpn-gateway : Add client configuration entries] **********************
task path: /home/rcardona/Projects/devtools/dev-servers/roles/playbook/openvpn-gateway/tasks/main.yml:20
{
  "changed": false,
  "failed": true,
  "msg": "One or more items failed"
}
failed: [misaki.polydev.blue] (item=dict_keys(['asterisk'])) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "dest": "/etc/openvpn/clients/dict_keys(['asterisk'])",
            "src": "client-config-dir-entry.j2"
        },
        "module_name": "template"
    },
    "item": "dict_keys(['asterisk'])",
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute \"dict_keys(['asterisk'])\""
}

```
