### ISSUE TITLE
ec2 module: instance_initiated_shutdown_behavior is invalid for instance-store backed AMIs

### ISSUE THREAD

**Issue by rentiak** [ansible/ansible#19521]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/vlg/ansible-playbooks/common/library']
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

After upgrading Ansible to 2.2.0 our playbooks fatal out due to AWS rejecting the setting of a flag on certain AMI types (instance-store backed AMIs)

##### STEPS TO REPRODUCE

```yaml
  - name: Spinning up 2 '{{ app }}' servers
    ec2:
      key_name: keynameishere
      instance_type: c3.xlarge
      image: '{{ image }}'
      wait: yes
      group_id: '{{ group }}'
      vpc_subnet_id: '{{ subnet }}'
      region: us-east-1
      count: 2
      user_data: |
                 #!/bin/bash
                 bootstrap script is here (redacted)
      assign_public_ip: '{{ use_public_ip }}'
      instance_profile_name: '{{ instance_profile }}'
      instance_tags:
        Platform: 'PlatformName'
        Environment: '{{ env }}'
        Application: '{{ app_type }}'
        Canary: 'Yes'
    register: ec2
```
relevant group_vars
```yaml
dl_image: ami-amiID
dl_group: sg-groupid
dl_subnet: subnet-subnetid
dl_elb: elbid
dl_instance_profile: IAMinstanceprofile
dl_use_public_ip: no
```

##### EXPECTED RESULTS

Instance should be spun up.

##### ACTUAL RESULTS

Instance spin up fails because current Amazon Linux AMI is instance-store rather than EBS backed. instance_initiated_shutdown_behavior default value of 'stop' is invalid for an instance-store backed AMI, which we are using. 

```
build	19-Dec-2016 10:14:25	fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Instance creation failed => InvalidParameterCombination: The attribute instanceInitiatedShutdownBehavior can only be used for EBS-backed images."}
```
