### ISSUE TITLE
file module : symlink detection

### ISSUE THREAD

**Issue by snadag** [ansible/ansible#19534]
##### ISSUE TYPE

 - Bug Report

Symlink creation fails with incorrect state. I'm not sure if this is permission related, destination does not exist.

##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### OS / ENVIRONMENT
```
MacOSx El capitan 10.11
```
##### STEPS TO REPRODUCE

```yaml
- name: "Create ruby config.h symlink"
  file:
    src: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/universal-darwin15/ruby/config.h"
    dest: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/config.h"
    state: link
    force: yes 
  when: xcode_version != "8.0"
```

##### ACTUAL RESULTS

```
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Error while linking: [Errno 2] No such file or directory", "path": "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/include/ruby-2.0.0/ruby/config.h", "state": "absent"}
```

It shows the state as absent when the actual state is link.

Note: Added force: yes based on discussion here - https://github.com/ansible/ansible/issues/7627

Any help is appreciated!
