### ISSUE TITLE
get_url should not re-download url  if checksum of already present dest file is matching desired checksum

### ISSUE THREAD

**Issue by levequej** [ansible/ansible#19548]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)

##### SUMMARY

get_url should not re-download  the remote file from url  if the checksum of already_present local dest file (from previous play or whatever)  is already matching the desired checksum

##### STEPS TO REPRODUCE

```yaml
- name: download stuff with checksum
  get_url:
    url: https://www.website.com/path/stuff.tar.gz
    dest: /tmp/
    sha256sum: 51597cb198403412ec0fbce141dfa245ed7194625431b517edf4a98c12b90f7e

```

##### EXPECTED RESULTS

no redownload
##### ACTUAL RESULTS

it is redownloading 

```

```
