### ISSUE TITLE
ec2 Module issue in Ansible 2.2

### ISSUE THREAD

**Issue by lalkrishnak** [ansible/ansible#19559]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

No Changes
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.3 (Maipo)
##### SUMMARY

I'm registering the output of ec2 module to a variable called ec2_info (register: ec2_info)
and then storing the details of the instance to a variable called item (debug: var=item, with_items: ec2_info.instances). But when I try to fetch the private ip of instance using {{ item.private_ip }}, it shows nothing.  ec2_info.instances is unable to get the instance details after the ec2 module execution.

The same playbook code is working fine with ansible 2.1.x version

##### STEPS TO REPRODUCE

Execute the below playbook with ansible 2.2 version

```yaml
- name: Launching Instance
  ec2:
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "key"
    group: "group"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami }}"
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    region: "{{ ec2_region }}"
    instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    wait: true
    count: 1
    volumes:
    - device_name: /dev/sda1
      volume_size: "{{ ec2_volume_size }}"
      delete_on_termination: true
  register: ec2_info

- debug: var=item
  with_items: ec2_info.instances

- name: Adding instance to host file
  copy: content="[group1]{{'\n'}}{{ item.private_ip }}" dest=/etc/ansible/hosts
  with_items: ec2_info.instances

```

##### EXPECTED RESULTS

ec2_info.instances variable should contain all details of ec2 module output.

##### ACTUAL RESULTS

```
changed: [localhost] => {
    "changed": true,
    "instance_ids": [
        "i-05199"
    ],
    "instances": [
        {
            "ami_launch_index": "0",
            "architecture": "x86_64",
            "block_device_mapping": {
                "/dev/sda1": {
                    "delete_on_termination": true,
                    "status": "attached",
                    "volume_id": "vol-0479"
                }
            },
            "dns_name": "ec2-.us-west-2.compute.amazonaws.com",
            "ebs_optimized": false,
            "groups": {
                "sg-aa7": "group"
            },
            "hypervisor": "xen",
            "id": "i-051",
            "image_id": "ami-31",
            "instance_type": "m4.large",
            "kernel": null,
            "key_name": "key",
            "launch_time": "2016-12-20T12:32:43.000Z",
            "placement": "us-west-2b",
            "private_dns_name": "ip-17-0-0-0.us-west-2.compute.internal",
            "private_ip": "17.0.0.0",
            "public_dns_name": "ec2-55-0-0-0-.us-west-2.compute.amazonaws.com",
            "public_ip": "55.0.0.0",
            "ramdisk": null,
            "region": "us-west-2",
            "root_device_name": "/dev/sda1",
            "root_device_type": "ebs",
            "state": "running",
            "state_code": 16,
            "tags": {
                "Environment": "Dev",
                "Name": "Node",
                "Type": "vpc-2c8"
            },
            "tenancy": "default",
            "virtualization_type": "hvm"
        }
    ],
    "invocation": {
        "module_args": {
            "assign_public_ip": true,
            "aws_access_key": "",
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "count": 1,
            "count_tag": null,
            "ebs_optimized": false,
            "ec2_url": null,
            "exact_count": null,
            "group": [
                "group"
            ],
            "group_id": null,
            "id": null,
            "image": "ami-3",
            "instance_ids": null,
            "instance_initiated_shutdown_behavior": null,
            "instance_profile_name": null,
            "instance_tags": {
                "Environment": "Dev",
                "Name": "Node",
                "Type": "vpc-048"
            },
            "instance_type": "m4.large",
            "kernel": null,
            "key_name": "key",
            "monitoring": false,
            "network_interfaces": null,
            "placement_group": null,
            "private_ip": null,
            "profile": null,
            "ramdisk": null,
            "region": "us-west-2",
            "security_token": null,
            "source_dest_check": true,
            "spot_launch_group": null,
            "spot_price": null,
            "spot_type": "one-time",
            "spot_wait_timeout": "600",
            "state": "present",
            "tenancy": "default",
            "termination_protection": null,
            "user_data": null,
            "validate_certs": true,
            "volumes": [
                {
                    "delete_on_termination": true,
                    "device_name": "/dev/sda1",
                    "volume_size": 100
                }
            ],
            "vpc_subnet_id": "subnet-39d",
            "wait": true,
            "wait_timeout": "300",
            "zone": null
        },
        "module_name": "ec2"
    },
    "tagged_instances": []
}

ok: [localhost] => (item=ec2_info.instances) => {
    "invocation": {
        "module_args": {
            "var": "item"
        },
        "module_name": "debug"
    },
    "item": "ec2_info.instances"
}

```
