### ISSUE TITLE
Add a cluster filter to the vmware_portgroup module

### ISSUE THREAD

**Issue by TheGuyDanish** [ansible/ansible#19553]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vmware_portgroup

##### SUMMARY
In certain situations, adding a portgroup to a vCenter may only be desirable upon a single cluster. For example if other clusters are also present in the vCenter that are not identical in hardware and won't be compatible with the desired changes.

I imagine it would be another option to the module, called 'cluster' or something alike.

```
- vmware_portgroup:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster: "DC1"
    vlan_id: "{{ vlan_id }}"
    switch_name: "vSwitch3"
    validate_certs: False
```
