### ISSUE TITLE
Slack module escapes all message text, preventing use of Slack markup

### ISSUE THREAD

**Issue by ThePletch** [ansible/ansible#19579]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Slack module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY
Slack notification messages are being HTML escaped before being sent to Slack, causing all Slack markup to appear as literal strings. This issue was introduced by [this PR](https://github.com/ansible/ansible-modules-extras/pull/3032).

##### STEPS TO REPRODUCE

Execute the following command using a valid Slack webhook token:

```yaml
- name: send a slack message
  slack:
    token: "{{ valid_token }}"
    username: "Test Message"
    msg: "<https://google.com|google>"
```

##### EXPECTED RESULTS

A message from Test Message appearing as: [google](https://google.com)
##### ACTUAL RESULTS

A message from Test Message appearing as: `<https://google.com|google>`
