### ISSUE TITLE
eos_config: fails on earlier EOS versions due to session-config

### ISSUE THREAD

**Issue by Zanthras** [ansible/ansible#19586]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
I believe this is unchanged in 2.3 from my quick read of the source, I have not however tested it.
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
EOS 4.14.12M 

##### SUMMARY
EOS config attempts to use a configuration session in a way that isnt supported on older EOS versions. Specifically the "show session-config diffs" command doesnt always exist.

##### STEPS TO REPRODUCE
On older versions of EOS specifically tested against 4.14.12M this play will fail
```yaml
---
- name: Change the password
  eos_config:
    provider: "{{ cli }}"
    force: true
    lines:
      - "username admin privilege 15 role network-admin secret 0 {{ secret_password }}"
```
##### EXPECTED RESULTS
Successful run of the play

##### ACTUAL RESULTS
```
fatal: [<removed>]: FAILED! => {
    "changed": false,
    "commands": [
        "configure session ansible_1482233620",
        "show session-config diffs",
        "end"
    ],
    "failed": true,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": false,
            "backup": false,
            "before": null,
            "config": null,
            "defaults": false,
            "force": true,
            "host": <removed>,
            "lines": [
                "username admin privilege 15 role network-admin secret 0 <removed>",
            ],
            "match": "none",
            "parents": null,
            "password": <removed>
            "port": null,
            "provider": {
                "host": <removed>
                "password": <removed>
                "transport": "cli",
                "username": <removed>
            },
            "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "use_ssl": true,
            "username": <removed>,
            "validate_certs": true
        }
    },
    "msg": "matched error in response: show session-config diffs\r\n% Invalid input\r\n<removed>(config-s-ansibl)#"
}
```

**Comment by ansibot** [comment]
cc @privateip, @gundalow, @Qalthos
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
DELETED
Not an issue with quotes

**Comment by Zanthras** [comment]
Just to clarify, its not the content of the play that matters, just how the module attempts to use configuration sessions, the below content is from a direct ssh session. On older versions the diff command doesnt exist yet, the(session config) feature was still being phased in.

switch1#config session
switch1(config-s-sess0)#show session-config ?
  diffs      Differences from running-config
switch1(config-s-sess0)#show session-config diffs

switch1(config-s-sess0)#abort
switch1#show ver
...
Software image version: 4.17.1F



switch2#config session
switch2(config-s-sess0)#show ses?
% Unrecognized command
switch2(config-s-sess0)#show session-config diffs
% Invalid input
switch2(config-s-sess0)#abort
switch2#show ver
...
Software image version: 4.14.8M

**Comment by calfonso** [comment]
This is fixed in 2.3, please retest and let us know if you still see the issue.

needs_info

**Comment by ansibot** [comment]
cc @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
@Zanthras Could you confim this is fixed in `2.3`, thanks

**Comment by trishnaguha** [comment]
@Zanthras just a suggestion: module `eos_user` can be used to create/configure user instead.

**Comment by ansibot** [comment]
cc @ganeshrn @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kedarX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
@Zanthras I see this bug was reported against `2.2.0.0`. We believe this is fixed in `2.3`. Did you ever get a chance to test this against `2.3`, `2.4`, or `devel`?

needs_info

**Comment by calfonso** [comment]
Closing this issue due to inactivity. If the issue continues to occur, please re-open this issue. Thanks!

**Comment by gundalow** [comment]
Reports on NTC that this is still an issue. Opening again to allow people to comment

**Comment by ansibot** [comment]
@Zanthras This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
Looks like a regression was introduced in 2.4.  For a workaround set `ANSIBLE_EOS_USE_SESSIONS=0`

**Comment by jchristopher327** [comment]
Here is the error when running a playbook against a switch running `4.12.7.1` The `eos.yml` playbook references a role used to apply basic system settings using the `src` parameter with a jinja2 template.

```
[root@ansible ansible]# ansible-playbook eos.yml --limit aac17 -vvvv
ansible-playbook 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: eos.yml *****************************************************************************************************************************************************************
1 plays in eos.yml

PLAY [Push configuration to devices] **********************************************************************************************************************************************
META: ran handlers

TASK [eos_base_config : Apply EOS system configuration] ***************************************************************************************************************************
task path: /etc/ansible/roles/eos_base_config/tasks/main.yml:3
<aac17> connection transport is cli
<aac17> using connection plugin network_cli
<aac17> socket_path: /root/.ansible/pc/45a53b4add
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/eos/eos_config.py
<aac17> ESTABLISH LOCAL CONNECTION FOR USER: root
<aac17> EXEC /bin/sh -c 'echo ~ && sleep 0'
<aac17> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1520011207.22-267845732175054 `" && echo ansible-tmp-1520011207.22-267845732175054="` echo /root/.ansible/tmp/ansible-tmp-1520011207.22-267845732175054 `" ) && sleep 0'
<aac17> PUT /tmp/tmpePZUqw TO /root/.ansible/tmp/ansible-tmp-1520011207.22-267845732175054/eos_config.py
<aac17> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1520011207.22-267845732175054/ /root/.ansible/tmp/ansible-tmp-1520011207.22-267845732175054/eos_config.py && sleep 0'
<aac17> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1520011207.22-267845732175054/eos_config.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1520011207.22-267845732175054/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_5P94Gm/ansible_module_eos_config.py", line 469, in <module>
    main()
  File "/tmp/ansible_5P94Gm/ansible_module_eos_config.py", line 396, in main
    response = load_config(module, commands, replace=replace, commit=commit)
  File "/tmp/ansible_5P94Gm/ansible_modlib.zip/ansible/module_utils/eos.py", line 472, in load_config
  File "/tmp/ansible_5P94Gm/ansible_modlib.zip/ansible/module_utils/eos.py", line 228, in load_config
TypeError: configure() takes exactly 2 arguments (3 given)

fatal: [aac17]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_5P94Gm/ansible_module_eos_config.py\", line 469, in <module>\n    main()\n  File \"/tmp/ansible_5P94Gm/ansible_module_eos_config.py\", line 396, in main\n    response = load_config(module, commands, replace=replace, commit=commit)\n  File \"/tmp/ansible_5P94Gm/ansible_modlib.zip/ansible/module_utils/eos.py\", line 472, in load_config\n  File \"/tmp/ansible_5P94Gm/ansible_modlib.zip/ansible/module_utils/eos.py\", line 228, in load_config\nTypeError: configure() takes exactly 2 arguments (3 given)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

PLAY RECAP ************************************************************************************************************************************************************************
aac17            : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by ansibot** [comment]
@Zanthras You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jchristopher327** [comment]
@gundalow FYI, the bot just closed the issue because the original user who created the issue hasn't commented.

**Comment by gundalow** [comment]
!needs_info

**Comment by Mshaik02** [comment]
I am facing similar issue with ansible 2.5

```yaml
- hosts:
    - "{{ switches }}"
  serial: 1
  gather_facts: no
  connection: local


  vars_prompt:
    - name: "password"
      prompt: "Enter user password"
      private: yes
      no_log: True

  vars:
    provider:
      host: "{{ inventory_hostname }}"
      username: "{{ ansible_user }}"
      password: "{{ password }}"

  tasks:

    - name: "Running pre-change confirmations"
      eos_command:
       provider: "{{ provider }}"
       commands: "show vlan | grep -w  {{ id }}"
       authorize: yes
      register: output

    - name: "Print pre-change output"
      debug: var=output.stdout_lines

#    - name: "Verifying the VLAN does not already exist"
#      fail: msg="[ERROR] VLAN {{ id }} already exists on {{ inventory_hostname }} Please verify the correct VLAN ID is being used. Aborting..."
#      when: output.stdout[0] != ""

    - name: " Pause for Implementor acknowledgement "
      pause:
        prompt: "Press 'Enter' to add the vlan"

    - name: "Adding the requested vlans"
      eos_config:
       provider: "{{ provider }}"
       authorize: yes
       lines:
          - vlan {{ id }}

    - name: "Running post-change confirmations"
      eos_command:
       provider: "{{ provider }}"
       commands: "show vlan | grep -w {{ id }}"
       authorize: yes
      register: output

    - name: "Print post-change output"
      debug: var=output.stdout_lines

#    - include: ../home/fds/netteam/arista-ansible/save_config.yml

    - name: "Pause for 50 seconds before proceeding to the next device.\r\nIf there is an STP event, abort the script!"
      pause:
        seconds: 50

```
ACTUAL RESULT
```
12:38:41[mshaik02@sysengb03:/home/fds/netteam/arista-ansible] ansible-playbook vlanadd.yml --extra-vars "id=125, switches=ct-bigip-lab"
Enter user password: 
 [WARNING]: Could not match supplied host pattern, ignoring: ct-bigip-lab

PLAY [ct-bigip-lab] *******************************************************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP ****************************************************************************************************************************************************************************************************************

12:38:59[mshaik02@sysengb03:/home/fds/netteam/arista-ansible] ansible-playbook vlanadd.yml --extra-vars "id=125, switches=CT-7500-LAB"
Enter user password: 

PLAY [CT-7500-LAB] ********************************************************************************************************************************************************************************************************

TASK [Running pre-change confirmations] ***********************************************************************************************************************************************************************************
ok: [CT-7500-LAB]

TASK [Print pre-change output] ********************************************************************************************************************************************************************************************
ok: [CT-7500-LAB] => {
    "output.stdout_lines": [
        [
            "125   VLAN0125                         active"
        ], 
        [
            ""
        ]
    ]
}

TASK [Pause for Implementor acknowledgement] ******************************************************************************************************************************************************************************
[Pause for Implementor acknowledgement]
Press 'Enter' to add the vlan:

ok: [CT-7500-LAB]

TASK [Adding the requested vlans] *****************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: CT-7500-LAB(s2)#
fatal: [CT-7500-LAB]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_H3uFBl/ansible_module_eos_config.py\", line 491, in <module>\n    main()\n  File \"/tmp/ansible_H3uFBl/ansible_module_eos_config.py\", line 414, in main\n    response = load_config(module, commands, replace=replace, commit=commit)\n  File \"/tmp/ansible_H3uFBl/ansible_modlib.zip/ansible/module_utils/network/eos/eos.py\", line 472, in load_config\n  File \"/tmp/ansible_H3uFBl/ansible_modlib.zip/ansible/module_utils/network/eos/eos.py\", line 241, in load_config\n  File \"/tmp/ansible_H3uFBl/ansible_modlib.zip/ansible/module_utils/connection.py\", line 146, in __rpc__\nansible.module_utils.connection.ConnectionError: show session-config diffs\r\n% Invalid input\r\nCT-7500-LAB(s2)#\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

PLAY RECAP ****************************************************************************************************************************************************************************************************************
CT-7500-LAB                : ok=3    changed=0    unreachable=0    failed=1
```


Gundalow editing formatting
