### ISSUE TITLE
yum skip broken issue

### ISSUE THREAD

**Issue by tuwid** [ansible/ansible#19587]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
yum module

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT
Mac OS Sierra 10.12.2 (16C67)

##### SUMMARY
yum module doesnt take --skip-broken as parameter somewhere

##### STEPS TO REPRODUCE
try doing an upgrade via yum on any cpanel host and you are likely to encounter that 

```yaml
    - name: Centos package upgrade 
      yum: name=* state=latest
      when: ansible_os_family == "RedHat"
```
