### ISSUE TITLE
need tag support in ec2_group

### ISSUE THREAD

**Issue by nergdron** [ansible/ansible#19580]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible/cloud/ec2_group

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/tessa/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
AWS Security Groups support tagging for organization and naming. However, ec2_group doesn't seem to support setting tags, according to the docs. It would be very useful to add tagging support for group, similar to how it works for instances, etc.

##### STEPS TO REPRODUCE
```yaml
  ec2_group:
    name: "{{ item.key }}"
    description: "This group is managed by Ansible."
    vpc_id: "{{ vpc_id }}"
    region: "{{ region }}"
    state: "{{ state }}"
    rules: "{{ item.value.rules }}"
    tags:
      Name: "{{ item.key }}"
      Something: "{{ item.other_val }}"
```
