### ISSUE TITLE
power on vms using vsphere_guest and inventory file

### ISSUE THREAD

**Issue by sayantandas** [ansible/ansible#19599]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vsphere_guest 

##### ANSIBLE VERSION

```
2.1.0
```

##### CONFIGURATION

default

##### OS / ENVIRONMENT
 Ubuntu 14.04

##### SUMMARY

I am looking to power on all VMs in VMware vcenter which are listed in the hosts(inventory) file using vsphere_guest

##### STEPS TO REPRODUCE

```
 - name: power on virtual machine
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      guest: "{{ vm_name}}"  <- this section I want to use the hosts file to pull the host name 
      state: powered_on
      force: yes
      esxi:
        datacenter: "{{ vcenter_datacenter }}"
    delegate_to: localhost


```

##### EXPECTED RESULTS

Expect to power on the VMs using the VM name from inventory file

##### ACTUAL RESULTS

Unable to find a solution to push VM names from the hosts file
```

```
