### ISSUE TITLE
vsphere_guest - Ability to deploy from template and change nic label

### ISSUE THREAD

**Issue by troxil** [ansible/ansible#19593]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

cloud/vmware/vsphere_guest

##### ANSIBLE VERSION

```
2.2.0.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

It would be a handy feature to be able to deploy a new VM using the vsphere_guest module and also change the NIC afterward (optionally). So you can deploy any instance from one template and then as the last step, prior to boot - to configure the NIC to be on a different VLAN.

If by design not doable whilst templating, then allow JUST the nic to be altered as a new task using vm_nic block. Which I believe isn't possible, considering the configuration requires vm_disk, vm_hardware as extras. 

##### STEPS TO REPRODUCE

```yaml
# from the vsphere_guest documentation.

# Deploy a guest from a template
- vsphere_guest:
    vcenter_hostname: vcenter.mydomain.local
    username: myuser
    password: mypass
    guest: newvm001
    from_template: yes
    template_src: centosTemplate
    cluster: MainCluster
    resource_pool: "/Resources"
    nic: DMZ
    vm_extra_config:
      folder: MyFolder
```

##### EXPECTED RESULTS

- Nic is configured on the VM specified in "hostname" to be the new nic in "nic" variable when deploying from template. 

##### ACTUAL RESULTS

N/A - feature request, "nic" or similar doesn't exist.

```

```
