### ISSUE TITLE
  module_stdout: "/bin/sh: 1: /usr/bin/python: not found\r\n", 

### ISSUE THREAD

**Issue by guruprasad85** [ansible/ansible#19605]
ansible -m ping -u ubuntu us-west-2a
35.166.197.222 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Shared connection to 35.166.197.222 closed.\r\n", 
    "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", 
    "msg": "MODULE FAILURE"
}

**Comment by nitzmahone** [comment]
Please use the issue template instead of deleting it- this is not an actionable or useful bug report. I suspect you're running Ubuntu 16+ or something else without a default python3 installed, but we can't tell that without a full bug report.

**Comment by richard-scott** [comment]
The latest images in AWS don't have a usable Python installed... you need to add this as a pre-task:

```
  pre_tasks:
         
    - name: Refresh apt cache
      become: no
      local_action: shell ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ inventory_hostname }} sudo apt-get update
       
    - name: Install Python-apt to pull in Python
      become: no
      local_action: shell ssh -q -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ConnectTimeout=5 {{ inventory_hostname }} sudo apt-get install --no-install-recommends --assume-yes python-apt
```

I have to use this in my tasks to get the AMI to work nicely with Ansible.
