### ISSUE TITLE
S3 module: Crash on nonexisting key, listing nonexisting keys.

### ISSUE THREAD

**Issue by mgla** [ansible/ansible#19600]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module: s3

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Running default ansible with s3 and boto

##### OS / ENVIRONMENT
Running Amazon Linux AMI 2016.09.0 (HVM), SSD Volume Type

##### SUMMARY
s3 module fails on wrong s3 key.

##### STEPS TO REPRODUCE
Create S3 bucket "myS3bucket"
Create key s3://myS3bucket/one/two/three.txt

Run this task on localhost:
```yaml
    - name: download ec2.py from s3
      s3:
        bucket: myS3bucket
        object: /one/
        dest: /tmp/test
        mode: get
```

```yaml
    - name: download ec2.py from s3 alternative)
      s3:
        bucket: myS3bucket
        object: /one/two/
        dest: /tmp/test
        mode: get
```

##### EXPECTED RESULTS
Clean failure on both tasks

##### ACTUAL RESULTS

The first task results in module failure, the second one does not.

```
TASK [download ec2.py from s3] *************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/etc/ansible/test/ec2.py'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_hY5S7p/ansible_module_s3.py\", line 686, in <module>\n    main()\n  File \"/tmp/ansible_hY5S7p/ansible_module_s3.py\", line 519, in main\n    download_s3file(module, s3, bucket, obj, dest, retries, version=version)\n  File \"/tmp/ansible_hY5S7p/ansible_module_s3.py\", line 329, in download_s3file\n    key.get_contents_to_filename(dest)\n  File \"/usr/lib/python2.7/dist-packages/boto/s3/key.py\", line 1714, in get_contents_to_filename\n    os.remove(filename)\nOSError: [Errno 2] No such file or directory: '/etc/ansible/test/ec2.py'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
        to retry, use: --limit @/home/ec2-user/s3test.retry
```
I suspect this is due to the s3 module in list mode listing /one/ as a key, but not /one/two/. This scenario is quite realistic, since a common way to sync a s3 buckets content to disk via ansible is collecting the keys with s3: mode=list and then using s3: mode=get to each key retrieved.

**Comment by gundalow** [comment]
@lwade I believe you created this module, what are your thoughts?

**Comment by havenchyk** [comment]
with `2.2.1` the same error

**Comment by djfang** [comment]
+1, any progress with this issue?

**Comment by gundalow** [comment]
Doesn't look like the maintainer isn't active anymore, so we'd be looking at the community to help with this.

**Comment by s-hertel** [comment]
I was able to recreate this issue, but I don't believe it's a bug or unexpected behavior. I think if we want s3 to support folder downloads that would be a feature request. I created folder structure of /one/two/three.txt in my bucket. Here is a playbook that fails with the same error you provided:
```
---
- hosts: localhost
  connection: local
  tasks:
    - name: download /one/ from s3
      s3:
        bucket: "{{ bucket }}"
        object: /one/
        dest: /tmp/doesnt/exist/yet
        mode: get
```
The problem is that the destination directory doesn't exist yet and the s3 module doesn't create or download folders as folders (so, for example, first doing `mkdir /tmp/doesnt/exist/yet` and then running the playbook would fail with a PermissionsError since '/yet' is a folder, not a file, and s3 module downloads files). When I run this playbook after first doing `mkdir /tmp/doesnt/exist` (with or without then doing touch `/tmp/doesnt/exist/yet`) and run the playbook again the get operation is successful. I think making a download_s3folder function for the s3 module could be really helpful though. I'm going to close this issue since it doesn't appear to be a bug, but feel free to open a PR for a feature request if you think it would be a helpful implementation or reopen this issue if you think I'm incorrect. :)
