### ISSUE TITLE
os_volume always returns `changed=true`

### ISSUE THREAD

**Issue by Thingee** [ansible/ansible#19619]
_From @ericcitaire on November 17, 2016 14:41_

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
Module `os_volume`

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Running from Mac OS 10.11.6 with virtualenv, managing Open Stack API

##### SUMMARY
When destroying an OpenStack volume, the module always resturns `changed=true`

##### STEPS TO REPRODUCE
```yaml
- os_volume:
    cloud: mycloud
    display_name: myvol
    state: absent
```

##### EXPECTED RESULTS
```
ok: [localhost]
```
##### ACTUAL RESULTS
```
changed: [localhost]
```

_Copied from original issue: ansible/ansible-modules-core#5649_
