### ISSUE TITLE
openstack module (e.g. os_server  / os_network) ignore endpoint_type:

### ISSUE THREAD

**Issue by Thingee** [ansible/ansible#19611]
_From @torbatux on September 21, 2015 12:44_

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
os_server module

##### ANSIBLE VERSION
```
[torba@localhost ~]$ ansible --version
ansible 2.0.0
```

##### SUMMARY
Hi I try to use ansible 2 with openstack support, to spin up new instances (I tried it now with different OS/installs to confirm): 

[torba@localhost ~]$ ansible --version
ansible 2.0.0

on a Centos 7 machine:
[torba@localhost ~]$ uname -r
3.10.0-229.11.1.el7.x86_64

when I try to use os_server with endpoint_type: internal and auto_floating_ip: yes
ansible still try to use the public IP (which I replaced down below with: **_PUBLIC-IP**_). 
I also tried inside of the sourced .novarc to use export OS_ENDPOINT_TYPE=internalURL which gets ignored as well.

-->SNIPP<---

```
- name: Spin up Nodes
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Ensure host is there
      os_server:
        state: present
        endpoint_type: internal
        timeout: 100
        api_timeout: 15
        name: tbade-2
        image: 32c2c8ff-824f-4533-99ba-39d1c8d43f62
        key_name: cloud_key
        flavor: m1.medium
        region_name: RegionOne
        availability_zone: nova
        security_groups: default
        nics:
          - net-id: c79d9116-a815-4919-abcc-d17c01df3676
        auto_floating_ip: yes
        meta:
          hostname: torba-1
          group: test-torba1
      register: rax
```

-->SNAPP<---

RESULT: 

```
fatal: [localhost]: FAILED! => {"changed": false, "extra_data": null, "failed": true, "msg": "unable to get available floating IPs: Error fetching network list: Unable to establish connection to http://***PUBLIC-IP***:9696/v2.0/networks.json"}
```

So I tried then to use a minimalistic approach os_network 

-->SNIPP<---

```
- name: Create test-net
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - os_network:
        name: testnetwork
        state: present
```

-->SNAPP<---

RESULT:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error fetching network list: Unable to establish connection to http://***PUBLIC-IP*** :9696/v2.0/networks.json"}
```

_Copied from original issue: ansible/ansible-modules-core#2118_
