### ISSUE TITLE
Dependency not executed multiple time even with allow_duplicates: yes

### ISSUE THREAD

**Issue by aerendil** [ansible/ansible#19635]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Role dependencies

##### ANSIBLE VERSION
```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

##### CONFIGURATION
ANSIBLE_ROLES_PATH=/home/ansible/roles

##### OS / ENVIRONMENT
Ubuntu 14.04 / Debian 3.2

##### SUMMARY
Having:
  - a role A with dependency to role B as well as allow_duplicates:yes
  - a playbook calling role A two times, with different parameters
Then the playbook actually do not execute the role B two times as expected.

##### STEPS TO REPRODUCE

Here is the code for main playbook:

test/main.yml
```yaml
---
- hosts: testhost
  become: true
  become_user: root
  gather_facts: yes
  roles:
     - { role: deploy, value: "repo1" }
     - { role: deploy, value: "repo2" }
```

Code of "deploy" role:

meta/main.yml
```yaml
---
allow_duplicates: yes
dependencies:
  - { role: update }
```

tasks/main.yml
```yaml
- debug: var=value
```

Code of "update" role:

tasks/main.yml
```yaml
- debug: msg="Update {{ value }}"
```

##### EXPECTED RESULTS
Expected result would be a print of "Update repo1" followed by "repo1" then "Update repo2" followed by "repo2".

Output of --list-tasks
```
playbook: test/main.yml

  play #1 (testhost): testhost	TAGS: []
    tasks:
      debug	TAGS: []
      debug	TAGS: []
      debug	TAGS: []
      debug	TAGS: []
```

##### ACTUAL RESULTS

```
PLAY [testhost] ******************************************************

TASK [setup] *******************************************************************
ok: [testhost]

TASK [update : debug] **********************************************************
ok: [testhost] => {
    "msg": "Update repo1"
}

TASK [deploy : debug] **********************************************************
ok: [testhost] => {
    "value": "repo1"
}

TASK [deploy : debug] **********************************************************
ok: [testhost] => {
    "value": "repo2"
}

PLAY RECAP *********************************************************************
testhost             : ok=4    changed=0    unreachable=0    failed=0   


```
