### ISSUE TITLE
handlers executed repeatedly

### ISSUE THREAD

**Issue by sdarwin** [ansible/ansible#19647]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

handlers

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 5f0815d7f4) last updated 2016/12/22 19:01:55 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

this is the latest devel branch from "git pull"
```

##### OS / ENVIRONMENT

Ubuntu 14.04.1 , Centos 7.1

##### SUMMARY

Handlers should only be triggered once, per the documentation, but they are triggered more than once.

"These ‘notify’ actions are triggered at the end of each block of tasks in a play, and will only be triggered once even if notified by multiple different tasks.  For instance, multiple resources may indicate that apache needs to be restarted because they have changed a config file, but apache will only be bounced once to avoid unnecessary restarts."
##### STEPS TO REPRODUCE

create a role, as follows:

```yaml
test/tasks/main.yml:
---
- shell: echo testing
  notify: handler1

- shell: echo testing
  notify: handler1

- shell: echo testing
  notify: handler1
  
test/handlers/main.yml
---
- name: handler1
  shell: echo "1" >> /tmp/test.txt
  
test/test.yml:
---
    - hosts: all
      remote_user: ansible
      become: true
      roles:
        - { role: 'test' }
```

run the playbook:
cd test 
ansible-playbook test.yml

##### EXPECTED RESULTS

/tmp/test.txt would contain a single "1"
##### ACTUAL RESULTS

/tmp/test.txt has three "1" values in it, corresponding to the handler running three times.

```
ansible-playbook test.yml

PLAY [all] *********************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************
ok: [localhost]

TASK [test : command] **********************************************************************************************************
GOT A NOTIFY
TRYING TO SEND NOTIFICATION TO HANDLER: handler1
changed: [localhost]

TASK [test : command] **********************************************************************************************************
GOT A NOTIFY
TRYING TO SEND NOTIFICATION TO HANDLER: handler1
changed: [localhost]

TASK [test : command] **********************************************************************************************************
GOT A NOTIFY
TRYING TO SEND NOTIFICATION TO HANDLER: handler1
changed: [localhost]

RUNNING HANDLER [test : handler1] **********************************************************************************************
changed: [localhost]
changed: [localhost]
changed: [localhost]

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=7    changed=6    unreachable=0    failed=0

```
