### ISSUE TITLE
until loop does not retry if conditional throws an exception

### ISSUE THREAD

**Issue by jonathanbouvier** [ansible/ansible#19651]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
lib/ansible/executor/task_executor.py

##### ANSIBLE VERSION
```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
```
ansible 2.3.0 (devel 241ad8cac3) last updated 2016/12/21 17:14:32 (GMT -400)
  config file = /local/jbouvier/workspace/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
timeout = 60
log_path = /path/to/my/log/file
vault_password_file = /path/to/my/vault/password/file

##### OS / ENVIRONMENT
Tested on both Debian 8.3 and CentOS 7.1.1503

##### SUMMARY
Tasks with a do-until loop do not retry if the conditional throws an exception.

As part of a deployment playbook I have a task that tries to validate a json response from a webapp until a certain field in the json array is == 0, however when the webapp is down or starting back up the output obtained is not proper JSON so the jinja2 filter throws an exception and aborts the task without retrying. 

Ideally I think there should be a exceptions_fatal option on the task to be used in conjunction with the until option. Something along the lines of the following, but hopefully a little prettier :)

```
#ansible/lib/ansible/executor/task_executor.py line 555
if retries > 1:
    cond = Conditional(loader=self._loader)
    cond.when = self._task.until
    result['attempts'] = attempt
    if self._task.exceptions_fatal:
        if cond.evaluate_conditional(templar, vars_copy):
            break
        else:
            # no conditional check, or it failed, so sleep for the specified time
            if attempt < retries:
                result['_ansible_retry'] = True
                result['retries'] = retries
                display.debug('Retrying task, attempt %d of %d' % (attempt, retries))
                self._rslt_q.put(TaskResult(self._host.name, self._task._uuid, result), block=False)
                time.sleep(delay)
    else:
        try:
            am_i_done = cond.evaluate_conditional(templar, vars_copy)
        except Exception, e:
            am_i_done = False
        if am_i_done:
            break
        else:
            # no conditional check, or it failed, so sleep for the specified time
            if attempt < retries:
                result['_ansible_retry'] = True
                result['retries'] = retries
                display.debug('Retrying task, attempt %d of %d' % (attempt, retries))
                self._rslt_q.put(TaskResult(self._host.name, self._task._uuid, result), block=False)
                time.sleep(delay)
```

##### STEPS TO REPRODUCE
```yaml
---
- name: check json output
  shell: curl -s -u {{ username }}:{{ password }}
    'http://{{ inventory_hostname }}:{{ port }}/some/json/file.json'
     warn=no
  no_log: True
  register: output
  until: "'{{ (output.stdout|from_json).s[3] }}' == '0'"
  retries: 10
  delay: 60

```

##### EXPECTED RESULTS
In this case I am running in an until loop, and am expecting any failure including an exception to invoke a retry.

##### ACTUAL RESULTS
```
fatal: [myhost]: FAILED! => {"failed": true, "msg": "The conditional check ''{{ (output.stdout|from_json).s[3] }}' == '0'' failed. The error was: No JSON object could be decoded"}

```

**Comment by bcoca** [comment]
I'm not sure what you are expecting here, until is there to deal with problems with task execution, not task definition errors.

**Comment by jonathanbouvier** [comment]
I am expecting this web service call to return JSON when the service is operational, but if the service is still initiating then I can not guarantee that it will be a JSON response. 

I'm expecting any failure (conditional returns false OR an exception thrown while parsing JSON) to invoke a retry of the until loop. Malformed JSON being returned from the service should not abort the task, the until loop should continue until its conditional returns true or max retries have been met. I do not see any way to check the whether the JSON is valid during execution of the conditional. 

Trying with the uri module provides similar results. 

```
---
- name: check json
  uri:
    user: '{{ username }}'
    password: '{{ password }}'
    url: 'http://{{ inventory_hostname }}:{{ port }}/some/json/file.json'
    return_content: yes
  register: response
  until: "{{ response.json.s[3] }}' == '0'"
  retries: 10
  delay: 60
```

```
TASK [check json] ***********************************************************
fatal: [myhost]: FAILED! => {"failed": true, "msg": "The conditional check ''{{ response.json.s[3] }}' == '0'' failed. The error was: error while evaluating conditional ('{{ response.json.s[3] }}' == '0'): 'dict object' has no attribute 'json'"}
```

There currently appears to be no way to handle this case short of writing a new ansible module with the logic I need.
