### ISSUE TITLE
rabbitmq_user should not update permissions each time

### ISSUE THREAD

**Issue by jackivanov** [ansible/ansible#19659]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rabbitmq_user

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### SUMMARY
If you are going to update permissions with items in the vhost options, all the permissions will be overwritten

##### STEPS TO REPRODUCE
use the playbook below

```yaml
- rabbitmq_user:
    user: "{{ rabbit_user }}"
    password: "{{ rabbit_password }}"
    permissions:
      - vhost: "{{ item }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
  with_items:
    - "{{ vhosts }}"
```

##### EXPECTED RESULTS
a user should has permissions for all {{ vhosts }}

##### ACTUAL RESULTS
a user has permissions for the last {{ vhosts }} value

**Comment by jackivanov** [comment]
Suggest to use something like a new option (append):
```
- rabbitmq_user:
    append: true
    user: "{{ rabbit_user }}"
    password: "{{ rabbit_password }}"
    permissions:
      - vhost: "{{ item }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
  with_items:
    - "{{ vhosts }}"
```

or additional state

```
- rabbitmq_user:
    state: append
    user: "{{ rabbit_user }}"
    password: "{{ rabbit_password }}"
    permissions:
      - vhost: "{{ item }}"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
  with_items:
    - "{{ vhosts }}"
```

**Comment by ansibot** [comment]
cc @manuel-sousa, @chrishoffman, @romanek-adam
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by krzysztof-magosa** [comment]
I would say that permissions should be controlled by separate module.
Then it could have state=absent or state=present to remove/add specific permission.

**Comment by schlueter** [comment]
@gunph1ld My understanding is that the `permissions` arg is meant to be used with a list of each vhost and its respective permissions, so 
```
- rabbitmq_user:
    state: append
    user: "{{ rabbit_user }}"
    password: "{{ rabbit_password }}"
    permissions:
      - vhost: "vhost1"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      - vhost: "vhost2"
        configure_priv: .*
        read_priv: .*
        write_priv: .*
      ... etc
```
and would set each vhost's permissions correctly. By using `with_items`, it is correctly running the module once for **each vhost** in your `vhosts` var and deleting permissions for vhosts not specified in to the module call, thus resulting in only the last vhost in the list.

There may be some trickery with jinja templates that can allow looping over the vhosts, as that is obviously a desirable pattern. I'll take a look at figuring that out without modifying the module.

**Comment by schlueter** [comment]
You can define a filter plugin (name it *something.py* and place it in a directory *filter_plugins* in your playbooks directory):
```
def vhost_default_perms(vhosts, default_perms):
    perms = ['configure_priv', 'write_priv', 'read_priv']
    default_perms_dict = dict(zip(perms, default_perms.split()))
    return [ {'vhost': vhost, **default_perms_dict} for vhost in vhosts ]

class FilterModule(object):
    ''' A filter to apply default permissions to a list of vhosts '''
    def filters(self):
        return dict(vhost_default_perms=vhost_default_perms)
```
which can be used like:
```
    - rabbitmq_user:
        user: example
        password: password
        permissions: "{{ vhosts | vhost_default_perms('.* .* .*') }}"
```
to assign the those permissions for the user on each vhost.

Admittedly, this is clunky and there ought to be a better way such as a dedicated permissions module as @krzysztof-magosa suggested.
