### ISSUE TITLE
Invalid Host error for host failed in previous play (dynamic inventory)

### ISSUE THREAD

**Issue by edyoucaterself** [ansible/ansible#19702]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

add_host
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']

```

##### OS / ENVIRONMENT

CentOS release 6.8 (Final)
2.6.32-642.3.1.el6.x86_64

##### SUMMARY

I have a playbook which collects information from vsphere, creates a yaml file containing servers and their business function and then uses add_host to build a dynamic inventory, then uses this inventory to push out ssh keys (and eventually more). The playbook fails on the last play, noting that a server name is invalid, the server its mentioning is in the host group of the previous play, but not in the failing play.

##### STEPS TO REPRODUCE

Playbook: 
```yaml
---
- name: Updating Inventory
  hosts: localhost
  roles:
    - get_inventory

- name: Push keys to Development servers
  hosts: dyn_dev
  roles:
    - key

- name: Push keys to test servers
  hosts: dyn_test
  roles:
    - key
```

get_inventory role:
```yaml
--- #Gathers data from vmware for inventory lists
  - include_vars: connection.yml
  - name: Collecting inventory from Vsphere
    shell: /usr/bin/python {{role_path}}/files/build_inv.py {{vsphere.login}} {{vsphere.passwd}}
  - include_vars: dynamic_inv.yml
  - name: Building inventory from dynamic data
    add_host:
      #name: "{{item.1.server.id}}"
      name: "{{item.1.server.name}}"
      groups: "{{item.0.function}}"
    with_subelements:
      - dyn_inv
      - servers
```

dynamic_inv.yml (reduced and redacted for security):
```yaml
---
dyn_inv:
  - function: dyn_test
    servers:
      - server: {'name':'server1','id':'xxx.xxx.xxx.xxx'}
  - function: dyn_dev
    servers:
      - server: {'name':'server_2','id':'xxx.xxx.xxx.xxx'}
      - server: {'name':'server_3','id':'xxx.xxx.xxx.xxx'}
      - server: {'name':'server_4','id':'xxx.xxx.xxx.xxx'}
      - server: {'name':'server_5','id':'xxx.xxx.xxx.xxx'}
```

##### EXPECTED RESULTS

I expect server_4 connection to fail, its missing some python modules. I expect the third play to run normally as its host group does not contain server_4
##### ACTUAL RESULTS

The third play fails, stating an invalid host name of the first server that was fatal from the previous play. It seems as though only servers with python issues (missing modules/packages) are causing this issue. 

```
PLAY [Updating Inventory] ******************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [get_inventory : include_vars] ********************************************
ok: [localhost]

TASK [get_inventory : Collecting inventory from Vsphere] ***********************
changed: [localhost]

TASK [get_inventory : include_vars] ********************************************
ok: [localhost]

TASK [get_inventory : Building inventory from dynamic data] ********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your playbooks
 so that the environment value uses the full variable syntax ('{{dyn_inv}}').

This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [localhost] => (item=({u'function': u'dyn_test'}, {u'server': {u'name': u'server_1', u'id': u'xxx.xxx.xxx.xxx'}}))
changed: [localhost] => (item=({u'function': u'dyn_dev'}, {u'server': {u'name': u'server_2', u'id': u'xxx.xxx.xxx.xxx'}}))
changed: [localhost] => (item=({u'function': u'dyn_dev'}, {u'server': {u'name': u'server_3', u'id': u'xxx.xxx.xxx.xxx'}}))
changed: [localhost] => (item=({u'function': u'dyn_dev'}, {u'server': {u'name': u'server_4', u'id': u'xxx.xxx.xxx.xxx'}}))
changed: [localhost] => (item=({u'function': u'dyn_dev'}, {u'server': {u'name': u'server_5', u'id': u'xxx.xxx.xxx.xxx'}}))

PLAY [Push keys to Development servers] *******************************

TASK [setup] *******************************************************************
ok: [server_2]
ok: [server_3]
fatal: [server_4]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/root/.ansible/tmp/ansible-tmp-1482872693.15-136579533077142/setup\", line 10, in ?\r\n    import subprocess\r\nImportError: No module named subprocess\r\n", "msg": "MODULE FAILURE", "parsed": false}
ok: [server_5]

TASK [key : Creating directory if needed]************************************************
ok: [server_2]
ok: [server_3]
ok: [server_5]

TASK [key : Copy over ssh keys] ************************************************
ok: [server_2]
ok: [server_3]
ok: [server_5]

NO MORE HOSTS LEFT *************************************************************

PLAY [Push keys to test servers] **************************************
ERROR! invalid host (server_4) specified for playbook iteration

```
