### ISSUE TITLE
apt: unable to install deb from URI with python3 interpreter

### ISSUE THREAD

**Issue by maxsolar** [ansible/ansible#19710]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
apt
```
##### ANSIBLE VERSION

```
2.2.0.0
```

##### CONFIGURATION

```
host_key_checking = False
ansible_python_interpreter=/usr/bin/python3
```

##### OS / ENVIRONMENT

```
both managed nodes and control node are: Ubuntu 16.04 LTS amd64
```

##### SUMMARY
When declare python3 as the default python, apt module is unable to install deb over the Internet. However, if python2 is the default python, issue doesn't exist.

##### STEPS TO REPRODUCE

Assume the inventory file call "hosts" defines one host "localhost".
```
ansible -i hosts localhost -e 'ansible_python_interpreter=/usr/bin/python3' -u username -k  --ask-sudo-pass -m apt -a "deb=http://ftp.twaren.net/Linux/Ubuntu/ubuntu/pool/main/v/vim/vim-common_7.3.547-6ubuntu3_amd64.deb"
```
and it returns:
```
"msg": "Failure downloading http://ftp.twaren.net/Linux/Ubuntu/ubuntu/pool/main/v/vim/vim-common_7.3.547-6ubuntu3_amd64.deb, 'NoneType' object has no attribute 'read'"
```
I tried to install deb from private deb repo, the error message turned:
```
"msg": "Failure downloading http://provision.hct.com/pub/pool/main/p/provision-priv-repo/provision-priv-repo_2016.0809_all.deb, write() argument must be str, not bytes"
```
However if python interpreter is python(2.7.x), there is no problem at all. Below is a part of my playbook:

```
- name: <registration> installing private apt repo...
  apt:
      deb: http://provision.hct.com/pub/pool/main/p/provision-priv-repo/provision-priv-repo_{{provision_version}}_all.deb

- name: <registration> installing AndApp8 private keys...
  apt:
      deb: http://provision.hct.com/pub/pool/main/a/andapp-privkey/andapp-privkey_{{privkey_version}}_all.deb
```

##### EXPECTED RESULTS

Both "ansible_python_interpreter=/usr/bin/python3" and "ansible_python_interpreter=/usr/bin/python" should produce the same result.

##### ACTUAL RESULTS

Parser seems to behave differently between python2 and python3.
