### ISSUE TITLE
ec2 volume creation breaks with older boto in v2

### ISSUE THREAD

**Issue by laurentgo** [ansible/ansible#19724]
_From @amenonsen on July 22, 2015 5:25_

Issue type: Bug report
Ansible version: devel
Ansible configuration: NA
Environment: boto 2.25
Summary:

Creating an EC2 instance using the task below fails with a traceback: "TypeError: **init**() got an unexpected keyword argument 'encrypted".

Support for encrypted volumes seems to have been added in boto 2.33, and I have 2.25. Can this be handled more gracefully somehow? Or make the module require the appropriate version?

Steps to reproduce:

```
# Create EC2 instances using the VPC subnets and security groups and
# access key we configured above.

- name: Set up EC2 instances
  ec2:
    exact_count: 1
    count_tag: "{{ cluster_tags }}"
    image: "{{ item.0.image }}"
    region: "{{ item.0.region }}"
    group_id: "{{ item.2.group_id }}"
    instance_type: "{{ item.0.type }}"
    vpc_subnet_id: "{{ item.1.subnets[0].id }}"
    instance_tags: "{{ cluster_tags | merge(item.0.tags) }}"
    key_name: "{{ ec2_key_name }}"
    assign_public_ip: yes
    volumes: "{{ item.0.volumes }}"
    wait: yes
  with_together:
    - instances
    - vpcs.results
    - security_groups.results
  register: ec2_instances
```

Expected results:

That the instance is created correctly (which it is, with stable-1.9; 1.9 supports volumes: but not 'encrypted'). Note that I'm not trying to create an encrypted volume.

Actual results:

```
"exception": "Traceback (most recent call last):\n  File \"/home/ams/.ansible/tmp/ansible-tmp-1437541681.83-138879933302241/ec2\", line 3174, in <module>\n    main()\n  File \"/home/ams/.ansible/tmp/ansible-tmp-1437541681.83-138879933302241/ec2\", line 1313, in main\n    (tagged_instances, instance_dict_array, new_instance_ids, changed) = enforce_count(module, ec2, vpc)\n  File \"/home/ams/.ansible/tmp/ansible-tmp-1437541681.83-138879933302241/ec2\", line 745, in enforce_count\n    = create_instances(module, ec2, vpc, override_count=to_create)\n  File \"/home/ams/.ansible/tmp/ansible-tmp-1437541681.83-138879933302241/ec2\", line 932, in create_instances\n    bdm[volume['device_name']] = create_block_device(module, ec2, volume)\n  File \"/home/ams/.ansible/tmp/ansible-tmp-1437541681.83-138879933302241/ec2\", line 707, in create_block_device\n    encrypted=volume.get('encrypted', None))\nTypeError: __init__() got an unexpected keyword argument 'encrypted'\n", 
```

_Copied from original issue: ansible/ansible-modules-core#1773_
