### ISSUE TITLE
Ansible to Solaris 5.10 not working but Solaris 5.11 ok

### ISSUE THREAD

**Issue by esncs16** [ansible/ansible#19728]
Hi 

Encouterred issue when run ansible on Solaris 5.10, needs advise and help.   Thank you very much

##### COMPONENT NAME

Installed Ansible as follow on Solaris VM ( (SunOS mysolaris1 5.10 Generic_147148-26 i86pc i386 i86pc) on virtual box
pkgadd -d http://get.opencsw.org/now
/opt/csw/bin/pkgutil -U
/opt/csw/bin/pkgutil -y -i ansible 
/usr/sbin/pkgchk -L CSWansible # list files

##### ANSIBLE VERSION

```
Ansible 2.0.0.2   (CSWansible)

```

##### SUMMARY

When run Ansible to Solaris 5.11 it worked but not on Solaris 5.10.  Throwing error: 
    "module_stderr": "/bin/sh: syntax error at line 1: `(' unexpected\r\n",
    "module_stdout": "/bin/sh: syntax error at line 1: `(' unexpected\r\n",
    "msg": "MODULE FAILURE",

##### STEPS TO REPRODUCE

```yaml

mysolaris1:/opt/csw/bin #./ansible 10.x.x.26 -m file -a "dest=/tmp/abc mode=755"  -u test -k -v -b --become-method=su --ask-become-pass
Using /etc/opt/csw/ansible/ansible.cfg as config file
SSH password:
SU password[defaults to SSH password]:
10.x.x.26 | FAILED! => {
    "changed": false, 
    "failed": true,
    "module_stderr": "/bin/sh: syntax error at line 1: `(' unexpected\r\n",
    "module_stdout": "/bin/sh: syntax error at line 1: `(' unexpected\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}

mysolaris1:/opt/csw/bin #./ansible 10.x.x.41 -m file -a "dest=/tmp/abc mode=755"  -u admin -k -v -b --become-method=su --ask-become-pass
Using /etc/opt/csw/ansible/ansible.cfg as config file
SSH password:
SU password[defaults to SSH password]:
10.x.x.41 | SUCCESS => {
    "changed": false,
    "gid": 0,
    "group": "root",
    "mode": "0755",
    "owner": "root",
    "path": "/tmp/abc",
    "size": 29,
    "state": "file",
    "uid": 0
}

```

##### EXPECTED RESULTS

Expect to see successful result as Solaris 5.11

##### ACTUAL RESULTS

"/bin/sh: syntax error at line 1: `(' unexpected\r\n",  on Solaris 5.10

```

Error on Solaris 5.10
mysolaris1:/opt/csw/bin #./ansible 10.x.x.70 -m file -a "dest=/tmp/abc mode=755" -u test -k -vvv -b --become-method=su --ask-become-pass
Using /etc/opt/csw/ansible/ansible.cfg as config file
SSH password:
SU password[defaults to SSH password]:
<10.x.x.70> ESTABLISH CONNECTION FOR USER: test on PORT 22 TO 10.x.x.70
<10.x.x.70> EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1482912590.43-126399425923882 )" && echo "$( echo $HOME/.ansible/tmp/ansibl e-tmp-1482912590.43-126399425923882 )" )
<10.x.x.70> PUT /tmp/tmpRFEd0w TO $( echo /export/home/test/.ansible/tmp/ansible-tmp-1482912590.43-126399425923882 )/file
<10.x.x.70> EXEC /bin/sh -c 'su  root -c "/bin/sh -c '"'"'echo BECOME-SUCCESS-crnszpmffbxxcqmekmlunzemcuyekcnl; LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/pyth on '"'"'"'"'"'"'"'"'$( echo /export/home/test/.ansible/tmp/ansible-tmp-1482912590.43-126399425923882 )/file'"'"'"'"'"'"'"'"'; rm -rf "$( echo /export/home/te st/.ansible/tmp/ansible-tmp-1482912590.43-126399425923882 )/" > /dev/null 2>&1'"'"'"'
10.x.x.70 | FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "file"
    },
    "module_stderr": "/bin/sh: syntax error at line 1: `(' unexpected\r\n",
    "module_stdout": "/bin/sh: syntax error at line 1: `(' unexpected\r\n",
    "msg": "MODULE FAILURE",
    "parsed": false
}


Succeeded on Solaris 5.11
mysolaris1:/opt/csw/bin #./ansible 10.x.x.41 -m file -a "dest=/tmp/abc mode=755" -u admin -k -vvv -b --become-method=su --ask-become-pass
Using /etc/opt/csw/ansible/ansible.cfg as config file
SSH password:
SU password[defaults to SSH password]:
<10.x.x.41> ESTABLISH CONNECTION FOR USER: admin on PORT 22 TO 10.x.x.41
<10.x.x.41> EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1482912667.26-183108740085870 )" && echo "$( echo $HOME/.ansible/tmp/ansibl e-tmp-1482912667.26-183108740085870 )" )
<10.x.x.41> PUT /tmp/tmpN7JYnc TO /export/home/admin/.ansible/tmp/ansible-tmp-1482912667.26-183108740085870/file
<10.x.x.41> EXEC /bin/sh -c 'su  root -c "/bin/sh -c '"'"'echo BECOME-SUCCESS-zggncvorsmkpqhfejtsceicdtpvxndda; LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/pyth on /export/home/admin/.ansible/tmp/ansible-tmp-1482912667.26-183108740085870/file; rm -rf "/export/home/admin/.ansible/tmp/ansible-tmp-1482912667.26-18310874 0085870/" > /dev/null 2>&1'"'"'"'
10.x.x.41 | SUCCESS => {
    "changed": false,
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "dest": "/tmp/abc",
            "diff_peek": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": null,
            "mode": "755",
            "original_basename": null,
            "owner": null,
            "path": "/tmp/abc",
            "recurse": false,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": null,
            "validate": null
        },
        "module_name": "file"
    },
    "mode": "0755",
    "owner": "root",
    "path": "/tmp/abc",
    "size": 29,
    "state": "file",
    "uid": 0
}

```
