### ISSUE TITLE
get_url with checksum and !force won't fix file permissions

### ISSUE THREAD

**Issue by joernheissler** [ansible/ansible#19721]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
get_url module does not set file attributes when the destination already exists and the checksum matches. See get_url.py line 355.

##### STEPS TO REPRODUCE
```yaml
- get_url:
    url: http://fun.drno.de/pics/english/nine_lives.jpg
    dest: /tmp/nine_lives.jpg
    checksum: "sha256:d4c93617fa241e9f3da2d244c7a1365a8019d1b473fbfd236fec4d8833ca6ced"
    mode: "{{ item }}"
  with_items:
    - 0600
    - 0644
```

##### EXPECTED RESULTS
I expect this to download the image on first item with mode 0600. On second item, I expect ansible to change mode to 0644.

##### ACTUAL RESULTS
Mode change is skipped.

```
changed: [target] => (item=384) => {"changed": true, "checksum_dest": null, "checksum_src": "e66a24b3dc16c079facd36a6544c92feece6bdf6", "dest": "/tmp/nine_lives.jpg", "gid": 0, "group": "root", "item": 384, "md5sum": "92171d40dbc1a59fad634dcc95461842", "mode": "0600", "msg": "OK (28343 bytes)", "owner": "root", "size": 28343, "src": "/tmp/tmpYZkUT7", "state": "file", "uid": 0, "url": "http://fun.drno.de/pics/english/nine_lives.jpg"}
ok: [target] => (item=420) => {"changed": false, "dest": "/tmp/nine_lives.jpg", "gid": 0, "group": "root", "item": 420, "mode": "0600", "msg": "file already exists", "owner": "root", "size": 28343, "state": "file", "uid": 0, "url": "http://fun.drno.de/pics/english/nine_lives.jpg"}
```
