### ISSUE TITLE
copy: do not chmod() if mode is not set

### ISSUE THREAD

**Issue by FlorentCoppint** [ansible/ansible#19731]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using "copy" module to copy files to a specific file system that does not support chmod(), module fails.
My /etc/pve directory is a mount point of a file system not supporting chmod().

##### STEPS TO REPRODUCE
```yaml
- name: Copy pve SSL cert and key
  copy: src=/etc/pve/pve-ssl.key dest=/etc/pve/nodes/host106/pve-ssl.key remote_src=True
```

##### EXPECTED RESULTS
copy successful.

##### ACTUAL RESULTS
```
failed: [host106] (item=pve-ssl.key) => {"failed": true, "item": "pve-ssl.key", "module_stderr": "Shared connection to XX.XX.XX.XX closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Vy2Iw6/ansible_module_copy.py\", line 364, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Vy2Iw6/ansible_module_copy.py\", line 342, in main\r\n    shutil.copy2(b_src, b_mysrc)\r\n  File \"/usr/lib/python2.7/shutil.py\", line 131, in copy2\r\n    copystat(src, dst)\r\n  File \"/usr/lib/python2.7/shutil.py\", line 100, in copystat\r\n    os.chmod(dst, mode)\r\nOSError: [Errno 38] Function not implemented: '/etc/pve/nodes/host106/tmptbef1A'\r\n", "msg": "MODULE FAILURE"}
```

**Comment by georgepsarakis** [comment]
I think the title is somehow misleading. You are copying a file in the remote system, from one filesystem to another and the copy operation (correctly) also attempts to copy the permission bits. So, your suggestion of not executing `chmod` when `mode` is not specified, may not be the solution here.

**Comment by FlorentCoppint** [comment]
"cp" command works for my example, no problem with chmod.

**Comment by georgepsarakis** [comment]
Did you try with `cp -a` or `cp -p`? The `-p` instructs `cp` to preserve mode, owner and timestamps and is the equivalent of the Ansible operation.

**Comment by FlorentCoppint** [comment]
I don't need it. I just want to copy files. With previous versions of Ansible, "copy" module was working in my situation.
If you think it's not bug, no problem, I use cp in command module.

**Comment by georgepsarakis** [comment]
Perhaps an additional parameter is required, that specifies that no metadata should be copied. 

There is another function, [shutil.copyfile](https://docs.python.org/2/library/shutil.html#shutil.copyfile) that does not copy metadata.

**Comment by themouette** [comment]
I have similar issue when trying to provision firewall files in proxmox as well.

@FlorentCoppint did you find a workaround?

**Comment by themouette** [comment]
Here is why the proxmox directory `/etc/pve` does not behave as expected: https://pve.proxmox.com/wiki/Proxmox_Cluster_File_System_(pmxcfs)#_posix_compatibility

It has a limited POSIX compatibility, especially when it comes to right management

**Comment by georgepsarakis** [comment]
@themouette I think the equivalent is the following:

```yaml
- name: Copy pve SSL cert and key
  command: "cp /etc/pve/pve-ssl.key /etc/pve/nodes/host106/pve-ssl.key"
  args:
    creates: /etc/pve/nodes/host106/pve-ssl.key
```

**Comment by themouette** [comment]
@georgepsarakis  Thank you.

So, to use `template` module, I have to provision elsewhere and then copy file/template using command module? Wouldn't I loose the ability to check diff?

Anyway, that's an acceptable fix until `shutil.copyfile` is used

**Comment by georgepsarakis** [comment]
@themouette in your example you are using the `copy` module. The `template` module should probably work if you do not specify `mode`, but I am not really sure, since these two modules are deeply related.

**Comment by themouette** [comment]
Yes I realize I used someone else's issue that was a bit different.

Sorry for the convenience, I thought it was kind of related as it was due to the same filesystem restrictions.

**Comment by EmmanuelKasper** [comment]
actually proxmox now implements chown and chmod since
70901ae9ac89f6e664e2acfaa95091e493dd3262 and pve 5.1

the issue here is that the copy module uploads a temporary file, and tries to do an an atomic rename via os.rename:

/etc/pve/hosts: [Errno 1] Operation not permitted: '/etc/pve/.ansible_tmpSDhOPlhosts'"

the proxmox cluster filesystem does not implement atomic file system renames

as a work around you can use the command module as described

This is not an ansible issue, and is specific to the cluster filesystem.

**Comment by user318** [comment]
> The template module should probably work if you do not specify mode

No. Template module fails too. I'm facing the same problem trying to put files on the FAT filesystem.

So is there any solution now for this problem besides copy/template to another filesystem and then running "cp" command?

**Comment by nchepanov** [comment]
The exception is raised from the call to `shutil.copy2` in https://github.com/ansible/ansible/blob/83c1cba511c99d5c68d4e0c5e596b9d07021ab8a/lib/ansible/modules/files/copy.py#L411

To reproduce (assuming `file.new` doesn't exist). Replace `/Users/nchepanov` with your path:
Note that `file` mode is `-rw-------`
```
export ANSIBLE_INVENTORY=/Users/nchepanov/ansible_hosts
echo "127.0.0.1" > /Users/nchepanov/ansible_hosts
ansible all -m copy -a "src=/Users/nchepanov/dev/ansible/ansible/file remote_src=True dest=/Users/nchepanov/dev/ansible/ansible/file.new" -e ansible_connection=local
```

By patching `os.chmod` I can see that it's called twice:

```
os.chmod('/Users/nchepanov/dev/ansible/ansible/tmpKqtUkm', 384) # 0600
os.chmod('/Users/nchepanov/dev/ansible/ansible/file.new', 420) # 0644
```

The newly copied file is `-rw-r--r--`

**Comment by user318** [comment]
@abadger In the #40099 it is mentioned that fix is "only relevant to remote_src=True". Does that mean it still will not work with local src? Than I would prefer this bug to be left open.

**Comment by abadger** [comment]
This bug does not affect remote_src=False.

If you can reproduce similar behavior with remote_src=False could you
please open a new bug with a reproducer for that behavior?

**Comment by user318** [comment]
OK. I will file a separate bug.

**Comment by tikismoke** [comment]
> My /etc/pve directory is a mount point of a file system not supporting chmod().
> ##### STEPS TO REPRODUCE
> 
> ```yaml
> - name: Copy pve SSL cert and key
>   copy: src=/etc/pve/pve-ssl.key dest=/etc/pve/nodes/host106/pve-ssl.key remote_src=True
> ```
> 


This i show i solved this issue:
```
# installs and updates proxmox SSL certs from a local directory on ansible and restarts pveproxy
# ansible-playbook proxmox-ssl.yml
- hosts: proxmox
  become: yes
  tasks:

  - name: Copy SSL certificate to proxmox
    copy:
      src: /root/acme_cert.fullchain
      dest: /root/pveproxy-ssl.pem
      follow: yes
    register: sslcert

  - name: Copy SSL key to proxmox
    copy:
      src: "/root/acme_cert.key"
      dest: "/root/pveproxy-ssl.key"
      follow: yes
    register: sslkey

  - name: Copy pve SSL cert
    command: "cp /root/pveproxy-ssl.pem /etc/pve/nodes/MYNODE/pveproxy-ssl.pem"

  - name: Copy pve SSL key
    command: "cp /root/pveproxy-ssl.key /etc/pve/nodes/MYNODE/pveproxy-ssl.key"

  - name: Restart pveproxy when certs change
    service: name=pveproxy state=restarted
    when:  sslcert.changed or sslkey.changed
```

Not sure how to do best
