### ISSUE TITLE
rax_identity module - novaclient.v2.client.Client is not designed to be initialized directly

### ISSUE THREAD

**Issue by f0x** [ansible/ansible#19733]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rax_identity

##### ANSIBLE VERSION
```
ansible 2.2.0.0
    configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Running ansible from MacOS 10.12.2
Ansible installed with brew

##### SUMMARY
Can't run this task because of novaclient error

##### STEPS TO REPRODUCE

```yaml
    - name: Load Identity
      local_action:
        module: rax_identity
        credentials: rackspace_credentials_filepath
        region: LON
      register: rackspace_identity
```

##### EXPECTED RESULTS
Verifies Rackspace Cloud credentials and returns identity information

##### ACTUAL RESULTS

error message: 

```
    "msg": "'novaclient.v2.client.Client' is not designed to be initialized directly. It is inner class of novaclient. You should use 'novaclient.client.Client' instead. Related lp bug-report: 1493576"
```
