### ISSUE TITLE
Add content option to template module

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#19741]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

template

##### ANSIBLE VERSION

v2.2+

##### SUMMARY

Being able to template a file inline (in the playbook itself) would be super-useful in those cases the content is very short and self-contained (e.g. a templated list, or templated content).

Also the `content:` option documentation in the **copy** module refers the **template** module if you need templated content.:
```
When used instead of 'src', sets the contents of a file directly to the specified value. This is for
simple values, for anything complex or with formatting please switch to the template module.
```

**Comment by georgepsarakis** [comment]
Why not use the `copy` module, and set the `content` parameter, exactly as you mention:

```yaml
- copy:
     content: "{{ my_variable }}"
```

**Comment by dagwieers** [comment]
Well, what I wanted to do was something like:

```yaml
- hosts: all
  tasks:
  - copy:
      content: |
        HOSTNAME;IPADDRESS;FQDN;OSNAME;OSVERSION;PROCESSOR;ARCHITECTURE;MEMORY;
        {% for host in hostvars %}
        {%   set vars = hostvars[host|string] %}
        {{ vars.ansible_hostname }};{{ vars.ansible_host }};{{ vars.ansible_fqdn }};{{ vars.ansible_distribution }};{{ vars.ansible_distribution_version }};{{ vars.ansible_processor[1] }};{{ vars.ansible_architecture }};{{ (vars.ansible_memtotal_mb/1024)|round|int }};
        {% endfor %}
      dest: /some/path/systems.csv
      backup: yes
    run_once: yes
    connection: local
```

But reading the documentation of the **copy** module, it appears that it only works for *simple values*. That is why I made this request.

Since the above appears to work, I will send a PR changing the documentation a bit and adding the above example. Nevertheless, I would assume most people would be looking at the template module, and not the copy module for doing the above.
