### ISSUE TITLE
cloud/amazon/rds don't wait while using modify and the wait param

### ISSUE THREAD

**Issue by gaelL** [ansible/ansible#19751]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`cloud/amazon/rds`

##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

I also tester with the last devel version of the related python file (`cloud/amazon/rds.py`)

##### CONFIGURATION

Default settings, just provided exported aws variables (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I created a RDS with ansible `rds_module` regarding the doc http://docs.ansible.com/ansible/rds_module.html
Really simple one with `instance_type: db.t2.micro`.

After created completed I desided to test a modify with the `wait` flag to yes to modify `instance_type` (also use `apply_immediately: yes`).

  * Expected behavior : ansible wait during the RDS is not in available state.
  * Behavior : Ansible didn't wait whereas the instance is not in available state on the aws console.

This issue seems to be only with modify, works find for create and delete action.

##### STEPS TO REPRODUCE

Note : I'm in region Irlande `eu-west-1`

After adding some debug logs here https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/rds.py#L652

I found that amazon don't instentanly put the RDS instance in `modifying` state, it take several secondes.

So during the modify, when we go through the `await_resource` methode, the state given by `resource.status` is already in `available` state.
The methode don't go in the while loop and stop to wait.

My ansible config :
```
  - rds:
      command: modify
      instance_name: "{{ instance_name }}"
      region: eu-west-1
      apply_immediately: yes 
      wait: yes 
      instance_type: db.t2.small
      wait_timeout: 600
```

My crappy debug code to have some logs :

```
def await_resource(conn, resource, status, module):
+    import datetime
+    for i in range(1,100):
+        resource = conn.get_db_instance(resource.name)
+        _now =  datetime.datetime.strftime(datetime.datetime.now(), '%H:%M:%S')
+        with open('/tmp/log', 'a+') as f:
+           f.write("STATUS %s %s waithing for %s\n" % (_now, resource.status, status))
+        time.sleep(0.5)
    wait_timeout = module.params.get('wait_timeout') + time.time()
    while wait_timeout > time.time() and resource.status != status:
```

The result :

```
STATUS  11:51:39 available waithing for available
...
STATUS  11:51:40 modifying waithing for available
```

```
STATUS  11:57:23 available waithing for available
...
STATUS  11:57:37 modifying waithing for available
```

The gap time before state change is kind of random.

**Idea of fix** :
  * Add a static wait time before checking the status
  * Add a `delay` parameter like it's done in the `wait_for` module (http://docs.ansible.com/ansible/wait_for_module.html)
  * Check if we are going through `modifying` status before wait

For people facing the same issue who want a workaround, I'm using that : 

```
  # Wait a bit
  - local_action: wait_for path="." state=present delay=20

  # Waiting end of modifying state
  - rds:
      command: facts
      instance_name: "{{ instance_name }}"
      region: eu-west-1
    register: new_database_facts
    until: new_database_facts.instance.status != "modifying"
    retries: 90
    delay: 10
```

**Comment by ansibot** [comment]
cc @bpennypacker, @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by willthames** [comment]
I'd probably just change this to wait for the modifying state, and then wait for the available state. There's a chance you could miss the modifying state, so at wait_timeout perhaps check if state is available. Also worth ensuring wait_timeout is used for the cumulative elapsed period of modifying and available (i.e. don't spend 2*wait_timeout waiting for both)

**Comment by Constantin07** [comment]
I'm facing the same issue. +1

**Comment by andygeorge** [comment]
Seeing this in 2.6.1, as well. I had to slightly tweak @gaelL's snippet to check for a state of `"available"`, as the instance can go into other states, depending on the modify being performed:

```
- name: Pause to allow RDS instance to go into modifying state
  pause:
    minutes: 1

- name: Wait for RDS modify to finish
  rds:
    command: facts
    instance_name: "{{ aws_rds_restore_name }}"
    region: "{{ aws_rds_region }}"
  register: aws_rds_facts
  until: aws_rds_facts.instance.status == "available"
  retries: 90
  delay: 10
```
