### ISSUE TITLE
azure_rm_virtualmachine - Creating a virtual machine from Marketplace image requires Plan information in the request

### ISSUE THREAD

**Issue by tivrobo** [ansible/ansible#19766]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Failed to create VM from Azure Marketplace, if image requires Plan information in the request.

##### STEPS TO REPRODUCE

For example try to create this VM using azure_rm_virtualmachine: https://azure.microsoft.com/en-us/marketplace/partners/netgate/netgate-pfsense-appliance/

    publisher: netgate
    offer: netgate-pfsense-appliance
    sku: pfsense-router-fw-vpn-225
    version: latest

Info: http://stackoverflow.com/questions/35871496/how-to-include-plan-information-when-creating-arm-vm-from-a-captured-image-usi

```yaml

---

- name: Create a resource group
  azure_rm_resourcegroup:
    name: "{{ azure_rg_name }}"
    profile: "{{ azure_rg_profile }}"
    location: "{{ azure_rg_location }}"

- name: Create storage account
  azure_rm_storageaccount:
    name: "{{ azure_storage_name }}"
    account_type: "{{ azure_storage_type }}"
    resource_group: "{{ azure_rg_name }}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    name: "{{ azure_vn_name }}"
    address_prefixes: "{{ azure_vn_prefix }}"
    resource_group: "{{ azure_rg_name }}"

- name: Create subnet
  azure_rm_subnet:
    name: "{{ azure_subnet_name }}"
    address_prefix: "{{ azure_subnet_prefix }}"
    virtual_network: "{{ azure_vn_name }}"
    resource_group: "{{ azure_rg_name }}"

- name: Create security group
  azure_rm_securitygroup:
    name: "{{ azure_rg_name }}"
    rules: "{{ azure_sg_rules }}"
    resource_group: "{{ azure_rg_name }}"

### VMs ###

- name: Create public IP
  azure_rm_publicipaddress:
    name: "{{ item.name }}-IP"
    allocation_method: Static
    resource_group: "{{ azure_rg_name }}"
  with_items: "{{ azure_vms }}"

- name: Create NIC
  azure_rm_networkinterface:
    name: "{{ item.name }}-NIC"
    subnet: "{{ item.subnet_name }}"
    public_ip_name: "{{ item.name }}-IP"
    private_ip_address: "{{ item.private_ip_address }}"
    private_ip_allocation_method: "{{ item.private_ip_allocation_method }}"
    virtual_network: "{{ azure_vn_name }}"
    resource_group: "{{ azure_rg_name }}"
  with_items: "{{ azure_vms }}"

- name: Create VM
  azure_rm_virtualmachine:
    name: "{{ item.name }}"
    vm_size: "{{ item.vm_size }}"
    storage_blob: "{{ item.name }}-OS.vhd"
    admin_username: "{{ item.username }}"
    admin_password: "{{ item.password }}"
    os_type: "{{ item.os_type }}"
    os_disk_caching: "{{ item.os_disk_caching }}"
    network_interfaces: "{{ item.name }}-NIC"
    image:
      offer: "{{ item.image_offer }}"
      publisher: "{{ item.image_publisher }}"
      sku: "{{ item.image_sku }}"
      version: "{{ item.image_version }}"
    storage_account: "{{ azure_storage_name }}"
    resource_group: "{{ azure_rg_name }}"
  with_items: "{{ azure_vms }}"

---
azure_vms:
    # XX-XXX-XX
  - name: XX-XXX-XX
    vm_size: Standard_A0
    os_type: Linux
    username: username
    password: password
    # Storage
    os_disk_caching: ReadWrite
    # Networking
    private_ip_address: "xxx.xxx.xxx.xxx"
    private_ip_allocation_method: Static
    subnet_name: Production
    # Image
    image_publisher: netgate
    image_offer: netgate-pfsense-appliance
    image_sku: pfsense-router-fw-vpn-225
    image_version: latest
```

##### EXPECTED RESULTS

That VM will be provisioned successfully.
(module parameters is missing for this case)

##### ACTUAL RESULTS

```
failed: [localhost](item = {
		u 'username': u 'username',
		u 'image_version': u 'latest',
		u 'name': u 'XX-XXX-XX',
		u 'image_offer': u 'netgate-pfsense-appliance',
		u 'image_publisher': u 'netgate',
		u 'image_sku': u 'pfsense-router-fw-vpn-225',
		u 'private_ip_allocation_method': u 'Static',
		u 'subnet_name': u 'Production',
		u 'private_ip_address': u 'xxx.xxx.xxx.xxx',
		u 'vm_size': u 'Standard_A0',
		u 'password': u 'password!',
		u 'os_type': u 'Linux',
		u 'os_disk_caching': u 'ReadWrite'
	}) => {
	"failed": true,
	"item": {
		"image_offer": "netgate-pfsense-appliance",
		"image_publisher": "netgate",
		"image_sku": "pfsense-router-fw-vpn-225",
		"image_version": "latest",
		"name": "XX-XXX-XX",
		"os_disk_caching": "ReadWrite",
		"os_type": "Linux",
		"password": "password!",
		"private_ip_address": "xxx.xxx.xxx.xxx",
		"private_ip_allocation_method": "Static",
		"subnet_name": "Production",
		"username": "username",
		"vm_size": "Standard_A0"
	},
	"msg": "Error creating or updating virtual machine XX-XXX-XX - Azure Error: VMMarketplaceInvalidInput\nMessage: Creating a virtual machine from Marketplace image requires Plan information in the request. OS disk name is XX-XXX-XX-OS.vhd."
}
```
