### ISSUE TITLE
Doc: missing examples for yum list

### ISSUE THREAD

**Issue by edysli** [ansible/ansible#19761]
_From @edysli on October 9, 2015 7:4_

Documentation for the yum module's `list` argument says "see examples" but there are no examples using it.

``` yaml
list:
  description:
    - Various (non-idempotent) commands for usage with C(/usr/bin/ansible) and I(not) playbooks. See examples.
  required: false
  default: null
```

Introduced in commit d6625a2b1f4c4c41e9a4ab9feddc5fffd327ca13.

_Copied from original issue: ansible/ansible-modules-core#2232_
