### ISSUE TITLE
notify on include does not run handler

### ISSUE THREAD

**Issue by marcinhlybin** [ansible/ansible#19765]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
notify

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
defaults

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Argument `notify` added to include instruction does not run handler on task change inside included file.

```
- include: other.yml
  notify: run handler
```

##### STEPS TO REPRODUCE

playbook.yml:

```yaml
---
- hosts: localhost
  gather_facts: no
  become: no
  roles:
    - testrole
```

testrole/tasks/main.yml:

```yaml
---
- include: other.yml
  notify: run handler
```

testrole/tasks/other.yml:

```yaml
---
- name: task always change
  shell: date
```

testroles/handlers/main.yml:

```yaml
---
- name: run handler
  debug:
    msg: Running handler on change
```

##### EXPECTED RESULTS
```
$ ansible-playbook playbook.yml

PLAY [localhost] ***************************************************************

TASK [testrole : task alaways change] ******************************************
changed: [localhost]

RUNNING HANDLER [testrole : run handler] ***************************************
ok: [localhost] => {
    "msg": "Running handler on change"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
$ ansible-playbook playbook.yml

PLAY [localhost] ***************************************************************

TASK [testrole : task alaways change] ******************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by nitzmahone** [comment]
Notify is not supported on an include. @bcoca @jimi-c  - should this be a playbook grammar warning/error?

**Comment by bcoca** [comment]
most directives should 'just work'tm, in this case i would argue that if the include is dynamic, the notify should apply to the include itself (which is a noop as it is always OK or FAILED, not CHANGED ... unless `changed_when`). If static i would expect that the included tasks inherit it (as I believe the ticket is expecting).

**Comment by ghost** [comment]
+1 for this feature

**Comment by tehfink** [comment]
+1

**Comment by ei-grad** [comment]
Same for ansible 2.4 with `import_tasks` and `include_tasks`...

**Comment by xiongchiamiov** [comment]
The current behavior is poor because there is no error or even warning - it just silently does not work.  If making it work is a lot of work, then I think in the meantime it should be an error.

To give a specific use case, I've been porting a bunch of sensu check configuration from using raw json templates to the `sensu_check` module.  This meant going from something like this:

```
- name: write sensu checks
  template:
    src: "{{ item }}.j2"
    dest: "/some/path/{{ item }}"
  notify:
    - restart sensu
  with_items:
    - < several dozen files of checks >
```

to this:

```
- name: write sensu checks
  include: checks/{{ item }}.yml
  notify:
    - restart sensu
  with_items:
    - < several dozen files of checks >
```

Since it transitioned from putting multiple checks in one json file (and thus, one task per group) to requiring one `sensu_check` per check, that means although the structure has remained essentially the same, Ansible interprets it as many more tasks, and as this ticket mentions, doesn't squash the `notify` into all of the included tasks.  To achieve the same thing, I either have to add the handler to every single task (and ensure it gets added to every new one), or do something a little bit crazy, like move all the check definitions into variables, and loop over them in one `sensu_check` task with a bunch of conditional logic (which in some cases isn't easy since there are already loops over the check definitions).
