### ISSUE TITLE
ec2_group: does not handle immutable description property properly 

### ISSUE THREAD

**Issue by alexlo03** [ansible/ansible#19789]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_group.py

##### ANSIBLE VERSION
```
ansible-playbook --version
ansible-playbook 2.1.3.0
  config file =
  configured module search path = Default w/o overrides
```
but also verified bug in devel branch

##### CONFIGURATION
nothing special

##### OS / ENVIRONMENT
osx / don't think it is os related

##### SUMMARY
ec2_group does not handle that the description property is immutable for some cases

##### STEPS TO REPRODUCE
(I've added an integration test to my pull request)

```yaml
- name: test state=present (expected changed=true)
  ec2_group:
    name='{{ec2_group_name}}'
    description='{{ec2_group_description}}'
    state=present
# ============================================================
- name: test state=present different description raises error
  ec2_group:
    name='{{ec2_group_name}}'
    description='{{ec2_group_description}}CHANGED'
    state=present
### Ansible will not report that the description was actually not updated unless the SG is currently used
```

##### EXPECTED RESULTS
Ansible ought to report that updating descriptions is always not possible.
Also Ansible ought not fetch the entire EC2 inventory as part of checking whether to error

##### ACTUAL RESULTS
No error
