### ISSUE TITLE
cloudformation_facts module returned output dict is uncomfortable to use

### ISSUE THREAD

**Issue by ricbartm** [ansible/ansible#19799]
##### ISSUE TYPE
Bug report (enhancement)

##### COMPONENT NAME
cloudformation_facts module (community module)

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.0.0
  config file =
  configured module search path =
```

##### CONFIGURATION
No specific configuration

##### OS / ENVIRONMENT
No specific operating system / environment

##### SUMMARY
The result of cloudformation_facts is not consistent with it's documentation and it's uncomfortable to use its output. In my opinion a small change in the returned data would make its behaviour more deterministic and more convenient in most of the use cases.

[Official module doc](https://docs.ansible.com/ansible/cloudformation_facts_module.html) says that module returns *stack_description*, *stack_outputs*, etc. This is not technically true. The module returns ```['ansible_facts']['cloudformation']['stack-name']['stack_outputs']```, which is mentioned in the *examples* section of the doc.

So, when using cloudformation_facts module with a ```register``` statement it creates an stack_name-dependant dictionary tree that we have to deal with (and it's not clear how to deal with it inside Ansible, because doing ```{{ testing['ansible_facts']['cloudformation']['{{stack_name}}']['stack_outputs']``` is not supported).

I was thinking on the use case when this might be useful (given my sort experience with Ansible) and that would be making ansible_facts a global variable while avoiding collisions, but with my sort experience with Ansible and this specific module, that is not the case. I mean, when using cloudformation_facts there is no variable ```ansible_facts```that gets automatically created. I also have seen that other *_facts modules return the results at the first level, so you can access them easily using ```registered_variable.returned_fact```. I'm assuming registering outputs is the way to go in order to get consistent names in order to access Ansible action outputs.

This might not be an issue if my Cloudformation stack names would be consistent. Why my stack names are not consistent? you might wonder. The use case is the following: we have hundreds of AWS accounts and each account has a cloudformation-based VPC deployment, but in the last years many people used the ansible-based tool with different parameters and the stack names are unfortunately, not consistent across all of them. Because it's a very low-level AWS resource, we can't easily replace (renaming a cloudformation stack is not possible) it without affecting the services running in the account. Now we are using cloudformation_facts and we're hitting this issue and some Ansible specific issues that make it harder.

##### STEPS TO REPRODUCE
Use cloudformation_facts module, register action output in a variable and try to access stack_outputs key from the variable as documentation says.

```yaml
- hosts: localhost
  connection: local

  vars:
    stack_name: 'common'
    region: 'eu-central-1'

  tasks:

    - name: test cloudformation_facts
      cloudformation_facts:
        stack_name: "{{ stack_name }}-cf-stack-asgard-vpc"
        region: "{{ region }}"
        all_facts: false
      register: testing

    - name: show stack outputs (raw ansible vpc facts)
      debug: msg="My stack outputs are {{ testing.stack_outputs }}"
```

##### EXPECTED RESULTS

I would expect ```testing.stack_outputs```, ```testing.stack_resources```, etc to be available at the top level of the registered variable. The output would look like this:

```
TASK [show stack outputs (raw ansible vpc facts)] ******************************
ok: [localhost] => {
    "msg": "My stack outputs are {u'VpcId': u'vpc-446ca12c', u'PublicSubnet1': u'subnet-f2e23488', u'PublicSubnet0': u'subnet-c69517ae', u'PrivateSubnet0': u'subnet-da9517b2', u'PrivateSubnet1': u'subnet-ffe23485', u'PublicElbSubnet1': u'subnet-f9e23483', u'PublicElbSubnet0': u'subnet-c79517af', u'InternetGateway': u'igw-9ecf99f7', u'PrivateElbSubnet1': u'subnet-fee23484', u'DataSubnet0': u'subnet-d89517b0', u'DataSubnet1': u'subnet-fde23487', u'PrivateElbSubnet0': u'subnet-d99517b1'}"
}
```

##### ACTUAL RESULTS

The resulted stack_outputs are returned as ```testing['ansible_facts']['cloudformation']['common-cf-stack-asgard-vpc']['stack_outputs']```, so ```testing.stack_outputs``` is not available. This is inconvenient because even I registered the cloudformation_facts output in the variable named ```testing```, I have to do nasty tricks for getting the stack outputs to be used in a different playbook.

```
TASK [show stack outputs (raw ansible vpc facts)] ******************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'stack_outputs'\n\nThe error appears to have been in 'PATH/bootstrap.yml': line 18, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: show stack outputs (raw ansible vpc facts)\n      ^ here\n"}
```

**Comment by ansibot** [comment]
cc @jmenga
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ricbartm** [comment]
Researching a bit more I got more clue about how ansible_facts work as well as a nasty workaround (triage), that works, but is terribly ugly. So far, I'm feeling tempted to clone the module into our git repo and change the behaviour of the module, using a custom module path fin order to workaround this.

Given that Ansible hash default behaviour is to override existing variable unless said otherwise [1], if we use cloudformation_facts twice in a playbook, ansible_facts['cloudformation'] will only contain the resturned values of the last cloudformation_facts stack rather than all of them. Issue #15187 might be related.

```yaml
- name: vpc facts register
  cloudformation_facts:
    stack_name: "{{ stack_name }}-cf-stack-asgard-vpc"
    region: "{{ region }}"
  register: stack_vpc_facts

- set_fact:
    stack_vpc: "{% for key, value in stack_vpc_facts.ansible_facts.cloudformation.iteritems() %}{{ value }}{%endfor%}"

- name: external access security group creation
  cloudformation:
    stack_name: "{{ stack_name }}-cf-stack-external-access-sg"
    region: "{{ region }}"
    template: "PATH/external_access_sg.json"
    state: "{{ stack_state }}"
    template_parameters:
      VPC: "{{ stack_vpc.stack_outputs.VpcId }}"
  register: stack_external_access_sg
```

This assumes we have a single item hash. If hashes are merged, we might have more than one and it will have unexpected behaviour (not verified, to be honest).

Regardless of this hack, if hash items are overritten by default, now makes more sense to me to stop exporting these outputs to ```ansible_facts``` and let the user control over what to do with the module output, as been suggested in the initial issue report.

[1] You can change ansible hash behaviour using https://docs.ansible.com/ansible/intro_configuration.html#hash-behaviour

**Comment by mixja** [comment]
The recommended behaviour for modules that return "facts" is described here - http://docs.ansible.com/ansible/dev_guide/developing_modules.html#module-provided-facts

I agree the current implementation overrides the `cloudformation` dictionary if you call the module more than once.  This should be easy enough to fix.  

In the meantime you can workaround the issues you describe as follows:

```
- cloudformation_facts:
      stack_name: stack_a
      stack_resources: true
- set_fact:
      stack_a: "{{ cloudformation['stack_a'] }}"
- cloudformation_facts:
      stack_name: stack_b
      stack_resources: true
      stack_template: true
- set_fact:
      stack_b: "{{ cloudformation['stack_b'] }}"
```
