### ISSUE TITLE
Redshift Cluster fails to Create -- InvalidClusterSubnetGroupStateFault

### ISSUE THREAD

**Issue by DaveWK** [ansible/ansible#19806]
- Bug Report

##### COMPONENT NAME
AWS Redshift Module

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION
``` 
pip install --user git+git://github.com/ansible/ansible.git@devel
```

##### OS / ENVIRONMENT
OSX

##### STEPS TO REPRODUCE
Create a Cluster VPC Subnet,
Verified in AWS console.
```
tasks:
    - name: provision redshift cluster
      redshift:
        command: create
        node_type: "dc1.large"
        identifier: "MyRedshiftCluster"
        region: "us-east-1"
        cluster_subnet_group_name: "MyRedshiftCluster-subnet"
        elastic_ip: yes
        publicly_accessible: true
        vpc_security_group_ids: "<SecurityGroupIdHere>"
        username: redshiftadmin
        password: 21nSecUre
```

##### EXPECTED RESULTS
Create the redshift cluster in the specified subnet

##### ACTUAL RESULTS
Failed with InvalidClusterSubnetGroupStateFault

```
TASK [provision redshift cluster] **********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "JSONResponseError: 400 Bad Request\n{u'RequestId': u'XXXX-XXX-XXX-XXXXXX-XXXXXXXX', u'Error': {u'Message': u'Vpc associated with db subnet group MyRedshiftCluster-subnet does not exist.', u'Code': u'InvalidClusterSubnetGroupStateFault', u'Type': u'Sender'}}"}
```
