### ISSUE TITLE
ec2_elb_lb intermittently failing to create an ELB with KeyError exception

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#19802]
_From @KpaBap on September 23, 2016 1:54_

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_elb_lb.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel fa5f8a7543) last updated 2016/09/18 02:10:05 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 488f082761) last updated 2016/09/18 02:10:48 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 24da3602c6) last updated 2016/09/18 02:10:57 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When running a playbook to create multiple ELBs, some of the ELBs would intermittently fail to get created with a KeyError exception.

I tracked this issue down to some data structure inconsistency in the _set_elb_listeners function.
It would appear that the data type stored in self.elb.listeners is sometimes a dict and other times a tuple.

I hacked around this issue but am not sure if my fix has broken anything else. See the diff below:

```
user@utf:/tmp$ diff ec2_elb_lb.py mine.py
755,758c755,760
<                 if existing_listener[0] == int(listener['load_balancer_port']):
<                     existing_listener_found = self._api_listener_as_tuple(existing_listener)
<                     break
<

---
>                 try:
>                     if self._listener_as_tuple(existing_listener)[0] == int(listener['load_balancer_port']):
>                         existing_listener_found = self._listener_as_tuple(existing_listener)
>                         break
>                 except KeyError:
>                     self.module.fail_json(msg="Ran into keyerror bug. self.elb.listeners is '%s'" % self.elb.listeners)
776c778
<                 existing_listener_tuple = self._api_listener_as_tuple(existing_listener)

---
>                 existing_listener_tuple = self._listener_as_tuple(existing_listener)
```
##### STEPS TO REPRODUCE

```
    - name: Create Control ELB
      ec2_elb_lb:
        name: "Control-ELB"
        state: present
        security_group_names: 
          - "{{ sg_name }}"
        region: "{{ aws_region }}"
        purge_instance_ids: true
        idle_timeout: 60
        subnets:
          - "{{ subnet_id }}"
        purge_listeners: true
        listeners:
          - protocol: tcp
            load_balancer_port: 443
            instance_port: 443
        health_check:
          ping_protocol: http
          ping_port: 80
          ping_path: "/health.html"
          response_timeout: 5
          interval: 10
          unhealthy_threshold: 2
          healthy_threshold: 2


    - name: Create Service ELB
      ec2_elb_lb:
        name: "Service-ELB"
        state: present
        security_group_names: 
          - "{{ sg_name }}"
        region: "{{ aws_region }}"
        purge_instance_ids: true
        idle_timeout: 3600
        subnets:
          - "{{ subnet_id }}"
        purge_listeners: true
        listeners:
          - protocol: tcp
            load_balancer_port: 443
            instance_port: 443
        health_check:
          ping_protocol: https
          ping_port: 443
          ping_path: "/health.html"
          response_timeout: 5
          interval: 10
          unhealthy_threshold: 2
          healthy_threshold: 2

    - name: Create Internal ELB
      ec2_elb_lb:
        name: "Int-ELB"
        state: present
        subnets:
          - "{{ subnet_id }}"
        security_group_names: 
          - "{{ sg_name }}"
        region: "{{ aws_region }}"
        purge_instance_ids: true
        scheme: "internal"
        idle_timeout: 3600
        purge_listeners: true
        listeners:
          - protocol: tcp
            load_balancer_port: 80
            instance_port: 80
        health_check:
          ping_protocol: tcp
          ping_port: 80
          response_timeout: 5
          interval: 10
          unhealthy_threshold: 2
          healthy_threshold: 2

```

##### EXPECTED RESULTS

I expect all ELBs to be created properly with the given settings.
##### ACTUAL RESULTS

The ELBs get created but Ansible quits with a Python exception which breaks further playbooks from running in a workflow.

```
TASK [Create Internal ELB] ******************************************
task path: /home/nsroot/ansible-work/playbooks/create-elbs.yml:96
Using module file /home/nsroot/ansible/lib/ansible/modules/core/cloud/amazon/ec2_elb_lb.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: nsroot
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1474500949.27-185632929248572 `" && echo ansible-tmp-1474500949.27-185632929248572="` echo $HOME/.ansible/tmp/ansible-tmp-1474500949.27-185632929248572 `" ) && sleep 0'
<localhost> PUT /tmp/tmp9oxobX TO /home/nsroot/.ansible/tmp/ansible-tmp-1474500949.27-185632929248572/ec2_elb_lb.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/nsroot/.ansible/tmp/ansible-tmp-1474500949.27-185632929248572/ /home/nsroot/.ansible/tmp/ansible-tmp-1474500949.27-185632929248572/ec2_elb_lb.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/nsroot/.ansible/tmp/ansible-tmp-1474500949.27-185632929248572/ec2_elb_lb.py; rm -rf "/home/nsroot/.ansible/tmp/ansible-tmp-1474500949.27-185632929248572/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py", line 1354, in <module>
    main()
  File "/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py", line 1338, in main
    elb_man.ensure_ok()
  File "/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py", line 410, in _do_op
    return op(*args, **kwargs)
  File "/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py", line 484, in ensure_ok
    self._set_elb_listeners()
  File "/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py", line 755, in _set_elb_listeners
    if existing_listener[0] == int(listener['load_balancer_port']):
KeyError: 0

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ec2_elb_lb"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py\", line 1354, in <module>\n    main()\n  File \"/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py\", line 1338, in main\n    elb_man.ensure_ok()\n  File \"/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py\", line 410, in _do_op\n    return op(*args, **kwargs)\n  File \"/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py\", line 484, in ensure_ok\n    self._set_elb_listeners()\n  File \"/tmp/ansible_Hbrcmm/ansible_module_ec2_elb_lb.py\", line 755, in _set_elb_listeners\n    if existing_listener[0] == int(listener['load_balancer_port']):\nKeyError: 0\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE"
}
    to retry, use: --limit @/home/nsroot/ansible-work/playbooks/create-elbs.retry
```

_Copied from original issue: ansible/ansible-modules-core#4977_

**Comment by aioue** [comment]
_From @ansibot on September 23, 2016 2:20_



@jsdalton ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aioue** [comment]
_From @jamesongithub on September 27, 2016 21:38_

seeing this issue also

**Comment by aioue** [comment]
_From @ansibot on October 8, 2016 8:28_

@jsdalton, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aioue** [comment]
_From @ansibot on October 23, 2016 8:44_

@jsdalton, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aioue** [comment]
_From @jamesongithub on November 4, 2016 23:18_

seeing this daily now in our ci

```
22:34:57 An exception occurred during task execution. The full traceback is:
22:34:57 Traceback (most recent call last):
22:34:57   File "/home/jenkins/.ansible/tmp/ansible-tmp-1478298892.42-226148869425382/ec2_elb_lb", line 3534, in <module>
22:34:57     main()
22:34:57   File "/home/jenkins/.ansible/tmp/ansible-tmp-1478298892.42-226148869425382/ec2_elb_lb", line 1333, in main
22:34:57     elb_man.ensure_ok()
22:34:57   File "/home/jenkins/.ansible/tmp/ansible-tmp-1478298892.42-226148869425382/ec2_elb_lb", line 414, in _do_op
22:34:57     return op(*args, **kwargs)
22:34:57   File "/home/jenkins/.ansible/tmp/ansible-tmp-1478298892.42-226148869425382/ec2_elb_lb", line 482, in ensure_ok
22:34:57     self._set_elb_listeners()
22:34:57   File "/home/jenkins/.ansible/tmp/ansible-tmp-1478298892.42-226148869425382/ec2_elb_lb", line 752, in _set_elb_listeners
22:34:57     if existing_listener[0] == int(listener['load_balancer_port']):
22:34:57 KeyError: 0
22:34:57 
```

**Comment by aioue** [comment]
_From @mxlan on November 7, 2016 21:7_

Just started seeing this today: version 2.0.2.0

<pre>An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/**user**/.ansible/tmp/ansible-tmp-1478552595.92-221111833899136/ec2_elb_lb", line 3205, in <module>
    main()
  File "/home/**user**/.ansible/tmp/ansible-tmp-1478552595.92-221111833899136/ec2_elb_lb", line 985, in main
    elb_man.ensure_ok()
  File "/home/**user**/.ansible/tmp/ansible-tmp-1478552595.92-221111833899136/ec2_elb_lb", line 360, in ensure_ok
    self._create_elb()
  File "/home/**user**/.ansible/tmp/ansible-tmp-1478552595.92-221111833899136/ec2_elb_lb", line 507, in _create_elb
    listeners = [self._listener_as_tuple(l) for l in self.listeners]
  File "/home/**user**/.ansible/tmp/ansible-tmp-1478552595.92-221111833899136/ec2_elb_lb", line 602, in _listener_as_tuple
    int(listener['load_balancer_port']),
KeyError: 'load_balancer_port'</pre>

I had modified a role I was using but the execution hasn't even gotten to the modified role... was working last week Friday.

**Comment by aioue** [comment]
_From @ansibot on November 7, 2016 21:13_

@jsdalton, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aioue** [comment]
_From @olecrivain on November 15, 2016 15:54_

Hi, Same error here! (ansible v2.2.0)

**Comment by aioue** [comment]
_From @kutay on November 17, 2016 14:57_

Hello, I have the same issue too (ansible v2.3.0)

**Comment by aioue** [comment]
_From @ansibot on November 23, 2016 9:44_

@jsdalton, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aioue** [comment]
_From @ansibot on December 7, 2016 19:8_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by aioue** [comment]
2.2.0.0

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 0
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/qb/0nbtzbx94pv57_jksjplywm80000gn/T/ansible_N4LIx1/ansible_module_ec2_elb_lb.py\", line 1354, in <module>\n    main()\n  File \"/var/folders/qb/0nbtzbx94pv57_jksjplywm80000gn/T/ansible_N4LIx1/ansible_module_ec2_elb_lb.py\", line 1338, in main\n    elb_man.ensure_ok()\n  File \"/var/folders/qb/0nbtzbx94pv57_jksjplywm80000gn/T/ansible_N4LIx1/ansible_module_ec2_elb_lb.py\", line 410, in _do_op\n    return op(*args, **kwargs)\n  File \"/var/folders/qb/0nbtzbx94pv57_jksjplywm80000gn/T/ansible_N4LIx1/ansible_module_ec2_elb_lb.py\", line 484, in ensure_ok\n    self._set_elb_listeners()\n  File \"/var/folders/qb/0nbtzbx94pv57_jksjplywm80000gn/T/ansible_N4LIx1/ansible_module_ec2_elb_lb.py\", line 755, in _set_elb_listeners\n    if existing_listener[0] == int(listener['load_balancer_port']):\nKeyError: 0\n", "module_stdout": "", "msg": "MODULE FAILURE"}


```
- name: create public masters ELB
  ec2_elb_lb:
    name: "{{ company_target_vpc_name | replace('_', '-') }}-{{ company_environment_name }}-pmst"
    connection_draining_timeout: 300
    cross_az_load_balancing: yes
    health_check:
        # options are http, https, ssl, tcp
        ping_protocol: https
        ping_port: 8443
        ping_path: "/healthz" # not required for tcp or ssl
        response_timeout: 3 # seconds
        interval: 5 # seconds
        unhealthy_threshold: 3
        healthy_threshold: 2
    # instance_ids: # DO AS SECOND PASS
    listeners:
      # options are http, https, ssl, tcp
      - protocol: tcp
        load_balancer_port: 443
        instance_port: 8443
        proxy_protocol: False
    # purge_instance_ids: yes
    purge_subnets: yes
    # purge_zones: yes
    region: "{{ aws_vpcs[company_target_vpc_name].aws_region }}"
    scheme: internet-facing
    security_group_names:
      - "{{ company_target_vpc_name }}_{{ company_environment_name }}_elb_public_to_masters"
    state: present
    subnets: "{{ openshift_subnet_ids }}"
    tags:
      env: "{{ company_environment_name }}"
      billing: "{{ aws_vpcs[company_target_vpc_name]['tag_billing'] }}"
      scheme: internet-facing
    wait: yes
  register: elb_pmst_output
```

The ELB does actually get created, but without tags, or logging (which I redacted).

A 2nd pass goes through fine.

**Comment by WizardOfArc** [comment]
No matter how many passes I go through my ec2_elb_lb task still breaks (although it worked a couple weeks ago with no change):
The Task:   
``` 
- name: Ensure Artifactory Load Balancer is created
      ec2_elb_lb:
        name: adc-artifactory-load-balancer-3
        state: present
        region: "{{ REGION }}"
        subnets: "{{ subnets }}"
        health_check:
          ping_protocol: http
          ping_port: 8081
          ping_path: "/artifactory/api/system/ping"
          response_timeout: 5
          interval: 30
          unlhealthy_threshold: 2
          healthy_threshold: 10
        purge_listeners: no
        security_group_ids:
          - "{{ artifactory_elb_sg.group_id }}"
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 8081
          - protocol: https
            load_balancer_port: 443
            instance_protocol: http
            instance_port: 8081
            ssl_certificate_id: [OBFUSCATED]
        stickiness:
          type: loadbalancer
          enabled: yes
          expiration: 300
        instance_ids: "{{ ec2_arthanodes.results | map(attribute='tagged_instances') | map('first') | map(attribute='id') | list }}"

```

The error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'unhealthy_threshold'
fatal: [localhost]: FAILED! => {
  "changed": false, 
  "failed": true, 
  "module_stderr": 
"Traceback (most recent call last):
  File \"/var/folders/8_/rfmvtn5s7g712p2fhd8lnn280000gp/T/ansible_PFm3DN/ansible_module_ec2_elb_lb.py\", line 1354, in <module>
    main()
  File \"/var/folders/8_/rfmvtn5s7g712p2fhd8lnn280000gp/T/ansible_PFm3DN/ansible_module_ec2_elb_lb.py\", line 1338, in main
    elb_man.ensure_ok()
  File \"/var/folders/8_/rfmvtn5s7g712p2fhd8lnn280000gp/T/ansible_PFm3DN/ansible_module_ec2_elb_lb.py\", line 410, in _do_op\n    return op(*args, **kwargs)
  File \"/var/folders/8_/rfmvtn5s7g712p2fhd8lnn280000gp/T/ansible_PFm3DN/ansible_module_ec2_elb_lb.py\", line 486, in ensure_ok
    self._set_health_check()
  File \"/var/folders/8_/rfmvtn5s7g712p2fhd8lnn280000gp/T/ansible_PFm3DN/ansible_module_ec2_elb_lb.py\", line 899, in _set_health_check
    \"unhealthy_threshold\": self.health_check['unhealthy_threshold'],
KeyError: 'unhealthy_threshold'", 
"module_stdout": "", 
"msg": "MODULE FAILURE"
}
```

**Comment by s-hertel** [comment]
What version of boto are you using? I haven't been able to recreate this. self.elb.listeners is consistently a list of tuples for me. Are you still experiencing this problem?

**Comment by s-hertel** [comment]
needs_info

**Comment by nsharmacovs** [comment]
Is there any update on this issue .I am facing same on  Ansible 2.3.1.0
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'load_balancer_port'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_2bIrbZ/ansible_module_ec2_elb_lb.py\", line 1359, in <module>\n    main()\n  File \"/tmp/ansible_2bIrbZ/ansible_module_ec2_elb_lb.py\", line 1346, in main\n    elb_man.ensure_ok()\n  File \"/tmp/ansible_2bIrbZ/ansible_module_ec2_elb_lb.py\", line 418, in _do_op\n    return op(*args, **kwargs)\n  File \"/tmp/ansible_2bIrbZ/ansible_module_ec2_elb_lb.py\", line 488, in ensure_ok\n    self._create_elb()\n  File \"/tmp/ansible_2bIrbZ/ansible_module_ec2_elb_lb.py\", line 709, in _create_elb\n    listeners = [self._listener_as_tuple(l) for l in self.listeners]\n  File \"/tmp/ansible_2bIrbZ/ansible_module_ec2_elb_lb.py\", line 814, in _listener_as_tuple\n    int(listener['load_balancer_port']),\nKeyError: 'load_balancer_port'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

**Comment by s-hertel** [comment]
Hi @nsharmacovs, would you be willing to share your reproducer, please?

**Comment by nsharmacovs** [comment]
- name: Create new   load balancer if it doesn't exists in 
  ec2_elb_lb:
    name: "{{ elb_name }}"
    state: present
    region: "{{aws_region}}"
    scheme: internal
    subnets:
      - "{{ elb_subnet_1 }}"
      - "{{ elb_subnet_2 }}"
      - "{{ elb_subnet_3 }}"
    security_group_ids: "{{vpc_sg}}"
    listeners:
    - protocol: tcp
      load_balancer_port: 9300
      instance_port: 9300
    access_logs:
      interval: 5 # minutes (defaults to 60)
      s3_location:  "{{ lb_log_location }}" # This value is required if access_logs is set
      s3_prefix: "logstash"
    cross_az_load_balancing: "yes"
  when: elb_name_output is undefined

**Comment by s-hertel** [comment]
Thanks so much @nsharmacovs. I would love to be able to fix this issue. I can run your task successfully. Do you notice anything about my setup that may be different? Can you check which version of boto you are using? Are you sure the syntax is the same as your reproducer?
```
$ ansible --version
ansible 2.3.1.0 (ec2_elb_lb_bug_2.3 97da8e161b) last updated 2017/06/29 14:02:45 (GMT -400)
  config file = /Users/shertel/Workspace/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```
```
$ pip freeze | grep boto
boto==2.47.0
```
Here is the exact playbook I'm running
```
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Create new   load balancer if it doesn't exists in
      ec2_elb_lb:
        name: "shertel-elb-test"
        state: present
        region: us-east-1
        scheme: internal
        subnets:
          - "{{ subnet1 }}"
          - "{{ subnet2 }}"
          - "{{ subnet3 }}"
        security_group_ids: "{{ sg }}"
        listeners:
        - protocol: tcp
          load_balancer_port: 9300
          instance_port: 9300
        access_logs:
          interval: 5 # minutes (defaults to 60)
          s3_location: "{{ bucketname }}"
          s3_prefix: "{{ prefix }}"
        cross_az_load_balancing: "yes"
```
Here is the output I get running that task:
```
changed: [localhost] => {
    "ansible_facts": {
        "ec2_elb": "info"
    },
    "changed": true,
    "elb": {
        "app_cookie_policy": null,
        "backends": [],
        "connection_draining_timeout": 300,
        "cross_az_load_balancing": "yes",
        "dns_name": "internal-shertel-elb-test-1043919800.us-east-1.elb.amazonaws.com",
        "health_check": {
            "healthy_threshold": 10,
            "interval": 30,
            "target": "TCP:9300",
            "timeout": 5,
            "unhealthy_threshold": 2
        },
        "hosted_zone_id": "Z35SXDOTRQ7X7K",
        "hosted_zone_name": null,
        "idle_timeout": 60,
        "in_service_count": 0,
        "instance_health": [],
        "instances": [],
        "lb_cookie_policy": null,
        "listeners": [
            [
                9300,
                9300,
                "TCP",
                "TCP"
            ]
        ],
        "name": "shertel-elb-test”,
        "out_of_service_count": 0,
        "proxy_policy": null,
        "region": "us-east-1",
        "scheme": "internal",
        "security_group_ids": [
            "sg-5e27db2f"
        ],
        "status": "ok",
        "subnets": [
            "subnet-cbdf56ae",
            "subnet-17bbda4c",
            "subnet-5c7ecc60"
        ],
        "tags": null,
        "unknown_instance_state_count": 0,
        "zones": [
            "us-east-1a",
            "us-east-1b",
            "us-east-1e"
        ]
    },
    "invocation": {
        "module_args": {
            "access_logs": {
                "interval": 5,
                "s3_location": "shertel-log-bucket",
                "s3_prefix": "mylog"
            },
            "aws_access_key": null,
            "aws_secret_key": null,
            "connection_draining_timeout": null,
            "cross_az_load_balancing": true,
            "ec2_url": null,
            "health_check": null,
            "idle_timeout": null,
            "instance_ids": null,
            "listeners": [
                {
                    "instance_port": 9300,
                    "load_balancer_port": 9300,
                    "protocol": "tcp"
                }
            ],
            "name": "shertel-elb-test”,
            "profile": "shertel",
            "purge_instance_ids": false,
            "purge_listeners": true,
            "purge_subnets": false,
            "purge_zones": false,
            "region": "us-east-1",
            "scheme": "internal",
            "security_group_ids": [
                "sg-5e27db2f"
            ],
            "security_group_names": null,
            "security_token": null,
            "state": "present",
            "stickiness": null,
            "subnets": [
                "subnet-cbdf56ae",
                "subnet-17bbda4c",
                "subnet-5c7ecc60"
            ],
            "tags": null,
            "validate_certs": true,
            "wait": false,
            "wait_timeout": 60,
            "zones": null
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ***************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by s-hertel** [comment]
I would like to add that although it isn't what your task is doing you *will* get the error if you specify listeners like:
```
        listeners:
          - protocol: tcp
          - load_balancer_port: 9300
          - instance_port: 9300
```
But that's due to invalid syntax since listeners expects one listener per list item, rather than one attribute per list item. So this is irrelevant to your reproducer, but I just wanted to throw that out there since it's the only way I have been able to reproduce this traceback.
