### ISSUE TITLE
git force=yes doesn't force a checkout if local changes exist on the target machine

### ISSUE THREAD

**Issue by afgane** [ansible/ansible#19809]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

git module

##### ANSIBLE VERSION

```
2.2.0.0
```

##### CONFIGURATION

```
[defaults]
callback_whitelist = profile_tasks
host_key_checking = False
allow_world_readable_tmpfiles=True
```
##### OS / ENVIRONMENT

Host: MacOS 10.12.2
Remote: Ubuntu 14.04

##### SUMMARY

When local modifications exist in a git repo on the machine with `force: yes` is set, `ansible-playbook` command does not update the repo.

##### STEPS TO REPRODUCE

```yaml
 - name: Checkout cloudlaunch client source
   git:
     repo: https://github.com/galaxyproject/cloudlaunch-ui
     dest: /opt/cloudlaunch-ui
     accept_hostkey: yes
     force: yes
     version: master
```

##### EXPECTED RESULTS

Updated git repo on the remote machine. 
If I manually do `git reset --hard` on the remote machine and rerun the playbook, the task runs fine.

##### ACTUAL RESULTS

```
TASK [cloudlaunch : Checkout cloudlaunch client source] ************************
Tuesday 03 January 2017  11:03:59 -0500 (0:00:01.336)       0:00:49.373 *******
changed: [149.165.171.39] => {"after": "f9803c25f039f19bdc6153bd4943538c2db12fb8", "before": "f9803c25f039f19bdc6153bd4943538c2db12fb8", "changed": true, "msg": "Local modifications exist", "warnings": []}
```

**Comment by alikins** [comment]
For that case, the module should also be doing a 'git reset --hard HEAD' to the checkout. But it may be failing to update after that.

Could you test this with the devel/ branch?

Was this working before 2.2.0?

**Comment by afgane** [comment]
I installed a new version directly from the repo here (it reports version 2.3.0.0) and the issue has gone away.

**Comment by goreilly** [comment]
I am still on 2.1 because of this. Will there be a bug patch or will I need to wait until 2.3 is stable?

**Comment by nickallevato** [comment]
I'm hitting this on a customer CI pipe. Work around with command module.

**Comment by minusdavid** [comment]
@afgane @goreilly I'm on Ansible 2.3.1.0 and I'm still having this issue.

**Comment by minusdavid** [comment]
When in doubt, look at the source code...

Looking at Ansible 2.3.1.0 at /usr/lib/python2.7/dist-packages/ansible/modules/source_control/git.py on Ubuntu 14.04.

Also taking a look at master and the problem is that I seem to be reaching this line: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/git.py#L855. 

There's no force there... even though I'd argue there should be.

**Comment by minusdavid** [comment]
Ah, looks like my issues stem from a few other things.

**Comment by karloskalcium** [comment]
Running into this on 2.3.1 as well. Any word on a fix?

**Comment by philipobrien** [comment]
Running into this on 2.3.2. Any fix or best-practice workaround? Use command module to `git reset --hard HEAD`?

**Comment by joehakimrahme** [comment]
Had the same issue in 2.2.0. Upgrading to 2.4.3 solved it for me. Thanks.

**Comment by mtyurt** [comment]
Still having the same issue on 2.5.5.

**Comment by ProudOne** [comment]
Experiencing this on 2.6.4 when changing the target version from `master` to `some/branch`.

````yml
- name: Clone or update
  git :
    repo          : "git@github.com:Organisation/some-repo.git"
    dest          : "/app_src"
    version       : "some/branch"
    update        : yes
    accept_hostkey: yes
    force         : yes
    key_file      : "~/.ssh/the-key-used-to.deploy"
````

````
TASK [get_sources : Clone or update] ***********************************************************************************************************************************************************************
task path: /[...]/tasks/main.yml:19
fatal: [...]: FAILED! => {
  "changed": false, 
  "cmd": "/usr/bin/git checkout --track -b some/branch origin/some/branch", 
  "msg": "Failed to checkout some/branch", 
  "rc": 1, 
  "stderr": "error: The following untracked working tree files would be overwritten by checkout:\n\tyarn.lock\nPlease move or remove them before you switch branches.\nAborting\n", 
  "stderr_lines": [
    "error: The following untracked working tree files would be overwritten by checkout:", 
    "\tyarn.lock", 
    "Please move or remove them before you switch branches.", 
    "Aborting"
  ], 
  "stdout": "", 
  "stdout_lines": []
}
to retry, use: --limit [...]
````
