### ISSUE TITLE
Unable to add a new monitored server with zabbix_host on Zabbix 2.4.7

### ISSUE THREAD

**Issue by angystardust** [ansible/ansible#19810]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
zabbix_host

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ansible/infra/library', '/usr/lib/python2.7/site-packages/ara/plugins/modules']

pyzabbix (0.7.3)
zabbix-api (0.4)

```

##### OS / ENVIRONMENT
Ansible control host: CentOS Linux release 7.2.1511 (Core)
Zabbix server: 2.4.7

##### SUMMARY
Unable to add a new zabbix host to a Zabbix server 2.4.7

##### STEPS TO REPRODUCE

```yaml
-  name: Create a new host or update an existing host's info
    zabbix_host:
      server_url: https://zabbix.test.local
      login_user: admin
      login_password: test123
      host_name: 'server01'
      host_groups:
        - Linux hosts
      link_templates:
        - Template OS Linux
      status: enabled
      state: present
      inventory_mode: automatic
      interfaces:
        - type: 1
          main: 1
          useip: 0
          ip: '1.1.1.1'
          dns: "server01.test.local"
          port: 10050
   delegate_to: localhost
```

##### EXPECTED RESULTS
Successfully add the new monitored host

##### ACTUAL RESULTS

```
TASK [Create a new host or update an existing host's info] *********************
task path: /home/ansible/infra/playbooks/include/zabbix_host.yml:1
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/monitoring/zabbix_host.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1483460081.93-208116994514496 `" && echo ansible-tmp-1483460081.93-208116994514496="` echo $HOME/.ansible/tmp/ansible-tmp-1483460081.93-208116994514496 `" ) && sleep 0'
<localhost> PUT /tmp/tmpbUhrB5 TO /home/ansible/.ansible/tmp/ansible-tmp-1483460081.93-208116994514496/zabbix_host.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1483460081.93-208116994514496/ /home/ansible/.ansible/tmp/ansible-tmp-1483460081.93-208116994514496/zabbix_host.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/ansible/.ansible/tmp/ansible-tmp-1483460081.93-208116994514496/zabbix_host.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1483460081.93-208116994514496/" > /dev/null 2>&1 && sleep 0'
fatal: [server01 -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "force": true,
            "host_groups": [
                "Zabbix"
            ],
            "host_name": "server01",
            "http_login_password": null,
            "http_login_user": null,
            "interfaces": [
                {
                    "dns": "server01.test.local",
                    "ip": "1.1.1.1",
                    "main": 1,
                    "port": 10050,
                    "type": 1,
                    "useip": 0
                },
                {
                    "dns": "server01.test.local",
                    "ip": "1.1.1.1",
                    "main": 0,
                    "port": 10050,
                    "type": 1,
                    "useip": 1
                }
            ],
            "inventory_mode": "automatic",
            "link_templates": [
                "Template OS Linux"
            ],
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "Admin",
            "proxy": null,
            "server_url": "https://zabbix.test.local",
            "state": "present",
            "status": "enabled",
            "timeout": 10
        },
        "module_name": "zabbix_host"
    },
    "msg": "Failed to create host server01: (u'Error -32500: Application error., SQL statement execution has failed \"INSERT INTO hosts (status,host,name,hostid) VALUES (\\'0\\',\\'server01\\',\\'server01\\',\\'10693\\')\". while sending {\"params\": {\"status\": 0, \"host\": \"server01\", \"interfaces\": [{\"ip\": \"1.1.1.1\", \"useip\": 0, \"dns\": \"server01.test.local\", \"main\": 1, \"type\": 1, \"port\": 10050}, {\"ip\": \"1.1.1.1\", \"useip\": 1, \"dns\": \"server01.test.local\", \"main\": 0, \"type\": 1, \"port\": 10050}], \"groups\": [{\"groupid\": \"11\"}]}, \"jsonrpc\": \"2.0\", \"method\": \"host.create\", \"auth\": \"6679e7475242f2e5149ef6ec3c4d5cfa\", \"id\": 5}', -32500)"
}

```
