### ISSUE TITLE
win_reboot never successfully continues after reboot is successful 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#19825]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_reboot module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
no special configs needed except username/password for winrm

##### OS / ENVIRONMENT
Windows Server 2012R2 Datacenter

##### SUMMARY
win_reboot never successfully continue after machine is rebooted, thus blocking playbook execution.

The machine in question has in fact been rebooted and is available for connections.

##### STEPS TO REPRODUCE

```yaml
- name: Reboot for changes to take effect
  win_reboot: reboot_timeout_sec=3600
              connect_timeout_sec=3600
              shutdown_timeout_sec=3600

```

With verbosity cranked up  this is the output:

```
TASK [risklink-common : Reboot for changes to take effect] *********************
task path: /Users/kbooth/rms/rms-ansible/roles/risklink-common/tasks/main.yml:71
<10.92.4.10> ESTABLISH WINRM CONNECTION FOR USER: ***** on PORT 5986 TO 10.92.4.10
<10.92.4.10> EXEC shutdown /r /t 2

```

##### EXPECTED RESULTS
Expect that ansible will detect machine is back online after reboot and continue executing plays

##### ACTUAL RESULTS

Actual results are that ansible waits forever until timeout values are reached.

```
TASK [risklink-common : Reboot for changes to take effect] *********************
task path: /Users/kbooth/rms/rms-ansible/roles/risklink-common/tasks/main.yml:71
<10.92.4.10> ESTABLISH WINRM CONNECTION FOR USER: techops on PORT 5986 TO 10.92.4.10
<10.92.4.10> EXEC shutdown /r /t 2

```

**Comment by jhawkesworth** [comment]
Can you check if winrm service comes back up when the machine is rebooted?  If not ansible wouldn't be able to detect that the server is available again.

Also can you specify the module parameters like this instead of using = ?  Probably won't make any difference but its the more usual syntax within a playbook.  



```
- name: Reboot for changes to take effect
  win_reboot: 
      reboot_timeout_sec: 3600
      connect_timeout_sec: 3600
      shutdown_timeout_sec: 3600
```

Also there might be some interplay setting all the parameters to the same value, so might be worth trying say a shorter shutdown_timeout_sec value.


needs_info

**Comment by ansibot** [comment]
@Kbooth-rms This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pablodav** [comment]
I have tested it also and when set: 

    shutdown_timeout_sec: 120
    reboot_timeout_sec: 120 

The task continues, but the server is never rebooted. 
Couldn't get more details, but seems that the module isn't functional yet. 

For that reason I have now in playbook: 

```yaml
- name: Reboot server
  win_shell: Restart-Computer -Force
```

This powershell cmdlet works without errors, maybe it can be used on the module.

**Comment by ansibot** [comment]
@Kbooth-rms This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by b-long** [comment]
Still seeing this issue in `ansible 2.3.0.0`.  Is anyone working on a fix?

cc/ @nitzmahone

**Comment by nathanwebsterdotme** [comment]
Same here.

Ansible 2.3.1.0 and target host is Vagrant.  The server has rebooted and can confirm that winrm is running and listening on the correct port. 

Playbook is sat hanging after the target host has rebooted successfully. 

If I then kill the playbook execution and re-run 'vagrant provision' again, it connects and run's the remainder of the playbook OK, proving that winrm is working as it should be on the target

**Comment by nitzmahone** [comment]
There's likely something "special" about your environment if you're seeing this behavior. 

For the one who never even reboots, I have no idea (and calling Restart-Computer *will* break on you at some point- that's why we have this action plugin), but for the OP that hangs after reboot, the one cause I've seen for this is if you're accessing WinRM on a VM through a port forward, and your hypervisor keeps the port open even when the target VM is down. In the current implementation, this will prevent `win_reboot` from working properly, as we wait for the port to stop answering (to ensure that the host went down) before we start trying to reconnect. This is mainly to allow the task to return as fast as possible after the host has rebooted while still actually ensuring that it's rebooted (ie, not using fixed timeouts, since things like post-reboot Windows Updates can break that). I prototyped some "clever-er" ways to do this when writing it, but what we shipped was by far the most stable.

The current impl also doesn't work for non-tcp connection plugins- we don't ship any of these that work with Windows yet, but there are some out in the wild that it *should* be able to work with and doesn't. The only way we can fix this without adding a bunch of special parameters to `win_reboot` to handle nonstandard cases would be to make it completely connection-oriented and make it sample the system startup time before and after, to determine that the host really rebooted. I prototyped this approach early on, and it was less stable and much slower (especially with default WinRM connection timeouts), but it's probably the way we'll have to go to keep the end-user interface simple and be connection-agnostic.

**Comment by ansibot** [comment]
cc @dagwieers @jborean93
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nathanwebsterdotme** [comment]
Hi

This does seem like an issue with Vagrant and forwarding ports, as above. 

The workaround I'm using is to check if we're running on Vagrant, and if so, send the restart command via win_shell: 

```
---

- name: Gather details about environment we're running on
  setup:
  register: remote_facts

... Tasks Here ...

- name: win_reboot
  win_reboot:
  when: remote_facts.ansible_facts.ansible_user_id != "vagrant"

### Vagrant Style win_reboot ###
# The win_reboot module hangs when targeting Vagrant so we restart differently.

- name: Reboot the server
  win_shell: Restart-Computer -Force
  when: remote_facts.ansible_facts.ansible_user_id == "vagrant"

- name: Wait 2 mins for server to reboot
  pause:
    seconds: 120
  when: remote_facts.ansible_facts.ansible_user_id == "vagrant"
```

Not perfect but it does the job for now.
