### ISSUE TITLE
ec2_group Errors using self referencing groups

### ISSUE THREAD

**Issue by campbill01** [ansible/ansible#19827]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

EC2_GROUP

##### ANSIBLE VERSION

```
  ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

Amazon Linux 2016.09
##### SUMMARY

"msg": "group referenced_group will be automatically created by rule {'to_port': 65535, 'from_port': 0, 'proto': 'tcp', 'group_name': 'referenced_group'} and no description was provided"

##### STEPS TO REPRODUCE

pip install ansible
attempt to apply group with a reference to another group

```
---
- name: new_group
  hosts: localhost
  gather_facts: no
  tasks:
  - name: new_group
    local_action:
      module: ec2_group
      name: new_group
      description: new security group for some service
      vpc_id: "{{ vpc }}"
      region: "{{ region }}"
      profile: "{{ profile }}"
      rules:
        - proto: tcp
          from_port: 0
          to_port: 65535
          group_name: referenced_group

        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip:  "{{ access_cidr }}"


```

##### EXPECTED RESULTS

Application of security group(s)
##### ACTUAL RESULTS

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 

```
 "msg": "group referenced_group will be automatically created by rule {'to_port': 65535, 'from_port': 0, 'proto': 'tcp', 'group_name': 'referenced_group'} and no description was provided"
```
