### ISSUE TITLE
pip creates bad virtualenv

### ISSUE THREAD

**Issue by p-hennessy** [ansible/ansible#19838]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
virtualenv
pip

##### ANSIBLE VERSION
```ini
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```ini
[defaults]
error_on_undefined_vars=True
gathering = 'explicit'
callback_whitelist = profile_tasks
```

##### OS / ENVIRONMENT
CentOS Linux release 7.2.1511 (Core) 

##### SUMMARY
Installing a `flask` app that runs behind a `uwsgi` emperor. This app uses Python 2.7.11 which is the system python and the same python running in the virtualenv

Seeing the following stack trace when running the app:
```
Traceback (most recent call last):
  File "app/server.py", line 3, in <module>
    import boto
  File "app/venv/lib/python2.7/site-packages/boto/__init__.py", line 35, in <module>
    import logging.config
  File "/usr/lib64/python2.7/logging/config.py", line 27, in <module>
    import sys, logging, logging.handlers, socket, struct, os, traceback, re
  File "/usr/lib64/python2.7/logging/handlers.py", line 26, in <module>
    import errno, logging, socket, os, cPickle, struct, time, re
ImportError: app/venv/lib/python2.7/lib-dynload/cPickle.so: undefined symbol: PyUnicodeUCS4_DecodeUTF8
unable to load app 0 (mountpoint='') (callable not found or import error)
```

Based on my Google-fu, the consensus is that the virtualenv was built using an outdated python?

Manually installing the virtualenv (via standard steps), works just fine and fixes the issue:

```bash
virtualenv app/venv
app/venv/bin/activate
pip install -r app/requirements.txt
deactivate

systemctl start uwsgi
```

As far as I can tell there is no difference between the manually installed virtualenv and the one using the pip module.

##### STEPS TO REPRODUCE
```yaml
    - name: Install virtualenv
      pip:
        name: virtualenv
        state: latest

    - name: Install venv packages
      pip:
        requirements: app/requirements.txt
        virtualenv: app/venv
```

app/requirements.txt: 
```
Flask==0.10.1
itsdangerous==0.23
simplejson==3.6.3
requests==2.0.1
pymongo==2.4
boto==2.9.7
```

Edit: Tried running this via the shell module, this seems to fail in the same way:
```yaml
    - name: Install VirtualEnv Packages
      shell: |
        virtualenv app/venv
        source app/venv/bin/activate
        pip install -r app/requirements.txt
        deactivate
```

**Comment by Lujeni** [comment]
Hello @ns-phennessy 

I am not able to reproduce your bug:
```yaml
- name: test venv
  hosts: all
  become: true
  tasks:
    - name: Install VirtualEnv Packages
      shell: |
        virtualenv app/venv
        source app/venv/bin/activate
        pip install -r requirements.txt
        deactivate
```

```bash
 ~/works/repos/perso/ansible/issue_19838 
13:54 $ ansible-playbook -i localhost, test.yml -c 'local' 

PLAY [test venv] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Install VirtualEnv Packages] *********************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

✔ ~/works/repos/perso/ansible/issue_19838 
13:54 $ source app/venv/bin/activate
(venv) ✔ ~/works/repos/perso/ansible/issue_19838 
13:54 $ python
Python 2.7.10 (default, May 31 2016, 23:05:11) 
[GCC 4.9.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import flask
>>>
```

Did you launch the ansible setup and your manually test with the same user ?
