### ISSUE TITLE
postgres_user module: `role_attr_flags` does nothing when combined with `no_password_changes`

### ISSUE THREAD

**Issue by wvidana** [ansible/ansible#19835]
_From @woqer on June 24, 2016 18:12_

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

postgresql_user
##### ANSIBLE VERSION

```
Ansible 2.1.0.0
```
##### OS / ENVIRONMENT

Mac OS X El Capitan, Version 10.11.4
Tested on Docker official postgres container and on Amazon RDS PostgreSQL DB instance
##### SUMMARY

When running a task with postgres_user module, the option `role_attr_flags` does not set any role attributes when `no_password_change` is set to `yes`
##### STEPS TO REPRODUCE

Run a task with module postgres_user, set any attribute in `role_attr_flags` and the option `no_password_changes` to `yes`

```

---
- hosts: localhost

  tasks:
    - name: create user
      postgresql_user:
        name: testing_user
        password: somerandompassword
        state: present
        login_host: your.amazon.url.to.postges.instance
        login_user: yourdefaultpostgresuser
        login_password: yoursecretpasswordforthedefaultuser
    - name: add attributes to user
      postgresql_user:
        name: testing_user
        no_password_changes: yes
        role_attr_flags: CREATEDB
        login_host: your.amazon.url.to.postges.instance
        login_user: yourdefaultpostgresuser
        login_password: yoursecretpasswordforthedefaultuser
```

##### EXPECTED RESULTS

The user testing_user should have the CreateDB attribute
##### ACTUAL RESULTS

No changes made.

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [create user] *************************************************************
changed: [localhost] => {"changed": true, "user": "test_user"}

TASK [add attributes to user] **************************************************
ok: [localhost] => {"changed": false, "user": "test_user"}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```

_Copied from original issue: ansible/ansible-modules-core#4034_
