### ISSUE TITLE
win_get_url not a valid attribute for a play

### ISSUE THREAD

**Issue by youssefelbakhar** [ansible/ansible#19839]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

-win_get_url
##### ANSIBLE VERSION

```
$ ansible --version
 [WARNING]: Optional dependency 'cryptography' raised an exception, falling back to 'Crypto'

ansible 2.3.0 (devel 02b08b1b0c) last updated 2016/10/05 16:34:46 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 0ee774ff15) last updated 2016/10/12 15:09:45 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 5cc72c3f06) last updated 2016/10/12 15:10:03 (GMT -400)
  config file = /home/user/ansible/ansible.cfg
  configured module search path = ['/opt/ansible/library']

```

##### CONFIGURATION

using hosts file with host groups and host children
specified Winrm connection settings in the host file
##### OS / ENVIRONMENT

Running Ansible on Centos 6, managing Windows 2008 & 2012 servers.
##### STEPS TO REPRODUCE

win_get_url works fine as a standalone command. However when included in a playbook i get the error above. Below is the playbook i'm using.

```
#Install Package
- name: Download Package.exe to C:\temp\Package.exe
  hosts: test_servers

  win_get_url: 
        url: http://server01/folder/Package.exe
        dest: C:/temp/Package.exe
        force: yes
 
- name:   Install Package 
  hosts: test_servers
 
  raw: "C:/temp/Package.exe"

```

##### EXPECTED RESULTS

I expected the playbook to get the file downloaded on the destination host, then the package will get executed by the following step in the playbook.

##### ACTUAL RESULTS

i get the following error 
ERROR! 'win_get_url' is not a valid attribute for a Play

The error appears to have been in '/home/user/ansible/package.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

#Package
- name: Download package.exe to C:\temp\Package.exe
  ^ here

```

```

**Comment by ansibot** [comment]
cc @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by jhawkesworth** [comment]
The error message is correct, your playbook is not properly formed as it doesn't contain the 'tasks' directive.

After you have specified hosts, you need to specify tasks to run on the hosts like this:

```
tasks:
   - name: name of first task
     module_name:
          module_parameter_name: module_parameter_value

   - name: name of second task
     module_name:
          module_parameter_name: module_parameter_value

```

Please re-read http://docs.ansible.com/ansible/playbooks_intro.html - this should make the syntax clearer for you.
