### ISSUE TITLE
Json template for s3_bucket module issue

### ISSUE THREAD

**Issue by dan-osms** [ansible/ansible#19865]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

s3_bucket
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

inventory      = /etc/ansible/local
retry_files_enabled = False
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Json templating for bucket policy
##### STEPS TO REPRODUCE

A capability to draft a template for application to s3_bucket on the fly

The json template would look like
```
{
	"Version": "2012-10-17",
	"Id": "PutObjPolicy",
	"Statement": [
		{
				"Sid": "IPAllow",
				"Effect": "Allow",
				"Principal": {
						"AWS": "*"
				},
				"Action": "s3:*",
				"Resource": "arn:aws:s3:::{{ ansible_s3_bucket_name }}/*",
				"Condition" : {
						"IpAddress" : {
								"aws:SourceIp": ["x.x.x.x/16"]
						}
				}
		},
		{
			"Sid": "DenyIncorrectEncryptionHeader",
			"Effect": "Deny",
			"Principal": "*",
			"Action": "s3:PutObject",
			"Resource": "arn:aws:s3:::{{ ansible_s3_bucket_name }}/*",
			"Condition": {
				"StringNotEquals": {
					"s3:x-amz-server-side-encryption": "AES256"
				}
			}
		},
		{
			"Sid": "DenyUnEncryptedObjectUploads",
			"Effect": "Deny",
			"Principal": "*",
			"Action": "s3:PutObject",
			"Resource": "arn:aws:s3:::{{ ansible_s3_bucket_name }}/*",
			"Condition": {
				"Null": {
					"s3:x-amz-server-side-encryption": "true"
				}
			}
		}
	]
}
```

```yaml
   - template:
    src: "{{ lookup('file','policy.json') }}"
    dest: "/dev/null"
    register: rendered_template

- s3_bucket:                                    
    name: somes3bucketname                            
    policy: "{{ rendered_template.stdout }}"
    versioning: yes                             
    tags:                                       
      project: some-project                             
      customer: some-customer
      contact:  some-admin
```

##### EXPECTED RESULTS

Nothing expected, the issue is that aws json policy requires the resource name. I am no Ansible pro, but it's annoying that I cannot simply draft a template policy and have the s3_bucket module contain a parameter into the json template.
##### ACTUAL RESULTS

```
 File "/Users/user/ansible/lib/ansible/parsing/dataloader.py", line 297, in path_dwim_relative_stack
elif source and (source.startswith('~') or source.startswith(os.path.sep)):
AttributeError: 'dict' object has no attribute 'startswith'

fatal: [127.0.0.1]: FAILED! => {
"failed": true,
"msg": "Unexpected failure during module execution.",
"stdout": ""
}
```
