### ISSUE TITLE
vmware_guest: Clone from template results in fault.NicSettingMismatch.summary

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#19860]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Spending a long time understanding what is going on, but the fact that it takes about 10 minutes before it fails (duing VM creation) makes it hard to troubleshoot.

The template has exactly one NIC, and my definition also has exactly one NIC, so it should be obvious that there is no real mismatch in number of NICs. But looking at other reports on the net seems to indicate a problem related to identity customizations (related to domain or DNS config).

**Comment by ansibot** [comment]
cc @jctanner
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@nerzhul Have you seen this before ? I cannot wrap my head around this one :-/

**Comment by nerzhul** [comment]
did saw this error before, it's a VMWare API error ?

**Comment by dagwieers** [comment]
https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.fault.NicSettingMismatch.html
"The number of network adapter settings in the customization specification does not match the number of network adapters present in the virtual machine."

**Comment by dagwieers** [comment]
What I noticed is that when this happens I end up with a VM with 2 NICs (the original from the template and a new one with my config). So this is definitely a regression in the logic, and I don't have to look at anything else anymore :-)

The reason this worked before was that the previous code removed all NICs and then added what was requested. (suboptimal, I agree, but it worked ;-))

I lost a few hours because of this though...

**Comment by dagwieers** [comment]
I think I found the bug/typo. Still need to verify it...

**Comment by nerzhul** [comment]
Yes old behaviour removed all NIC but it's not acceptable when using idempotence with running VM

**Comment by joshmullis** [comment]
Seems this is still an issue.
I have a template with no nics and this error still occurs.

Or was this related to something else and not the nic adapter count?

**Comment by nerzhul** [comment]
@joshmullis one of my student reproduced your bug today and i debugged with him to find the error.
VMware API is quite stupid, it clone the machine, every parameter is accepted by VMware, VM is okay but API returns an error whereas clone seems to be okay... it will be quite compilated to solve this issue

**Comment by joshmullis** [comment]
cool!  Well I found that the issue goes away if I specify an IP and Netmask (even though they are blank)

```
 networks:
   - name: "{{ vm_network }}"
      type: vmxnet3
      ip: ""
      netmask: ""
```

**Comment by iamkuldeepsingh** [comment]
I tried the above but did not help, Now started getting the error for IP, I am exactly facing the same issue

**Comment by luca-drf** [comment]
@joshmullis I tried your solution but I get a failure:
`"msg": "A specified parameter was not correct: spec.nicSettingMap.adapter.ip"`

I'm cloning a template with no NICs, creating a NIC with `networks` parameter. If I try to use the `customize` parameter in any way I get:
`"msg": "fault.NicSettingMismatch.summary"`

**EDIT**: The error is actually generated by the `network` parameter. If I only specify the attributes `name` and `mac` it will create the NIC but it will throw the error `"msg": "fault.NicSettingMismatch.summary"`.

Question: how do I create a NIC that uses a DHCP server?

**Comment by joshmullis** [comment]
@randome I am also using a template without a nic.  Below is the code I'm using.  Also, this code allows me to use DHCP (since I'm specifying a blank IP and Netmask)

My environment:
 - ansible 2.3.0.0
 - vcenter 5.5



main.yml
```
- hosts: localhost
  vars_files:
    - vars.yml

  vars_prompt:
    - name: vsphere_password
      prompt: "Enter vsphere password"
      private: yes

  tasks:

    #######################
    ## Create/Manage VMs ##
    #######################

    - name: Create/Modify VMs
      with_items: "{{ vm_names }}"
      when: vm_lifecycle == "create"
      vmware_guest:
        state: poweredon
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        validate_certs: no
        datacenter: "{{ vsphere_datacenter }}"
        cluster: "{{ vsphere_cluster }}"
        resource_pool: "{{ vsphere_resource_pool | default(omit) }}"
        name: "{{ item }}"
        template: "{{ vm_template }}"
        folder: "{{ vm_folder }}"
        wait_for_ip_address: yes

        # "ip:" and "netmask:" must be here to fulfill api requirement, but please leave blank for DHCP
        networks:
        - name: "{{ vm_network }}"
          type: vmxnet3
          ip: ""
          netmask: ""

        disk:
        - autoselect_datastore: true
          datastore: "{{ vm_datastore_filter }}"
          size_gb: 50
          type: thin

        # Uncomment to have a 2nd disk setup
        #disk:
        #- autoselect_datastore: true
        #  datastore: "{{ vm_datastore_filter }}"
        #  size_gb: "{{ disk2_size }}"
        #  type: thin

        hardware:
          memory_mb: "{{ vm_mem }}"
          num_cpus: "{{ vm_cpus }}"

        customization:
          hostname: "{{ item }}"
          domain: "{{ vm_domain }}"





    #################
    ## Destroy VMs ##
    #################

    - name: Poweroff VMs
      with_items: "{{ vm_names }}"
      when: vm_lifecycle == "destroy"
      vmware_guest:
        state: poweredoff
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        validate_certs: no
        datacenter: "{{ vsphere_datacenter }}"
        cluster: "{{ vsphere_cluster }}"
        resource_pool: "{{ vsphere_resource_pool | default(omit) }}"
        name: "{{ item }}"
        folder: "{{ vm_folder }}"

    - name: Delete VMs
      with_items: "{{ vm_names }}"
      when: vm_lifecycle == "destroy"
      vmware_guest:
        state: absent
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        validate_certs: no
        datacenter: "{{ vsphere_datacenter }}"
        cluster: "{{ vsphere_cluster }}"
        resource_pool: "{{ vsphere_resource_pool | default(omit) }}"
        name: "{{ item }}"
        folder: "{{ vm_folder }}"
```



vars.yml
```
## VM Preferences ##
vsphere_username: "<username>"
vm_template: "<template_name>"
vm_network: "<vm_network_name>"
vm_folder: "<folder_path>"
disk2_size: ""
vm_cpus: "2"
vm_mem: "4096"
vm_names:
  - my-app001
#  - my-app002
#  - my-app003


vsphere_hostname: "<vcenter_hostname>"
vsphere_datacenter: "<datacenter_name>"
vsphere_cluster: "<cluster_name>"
vm_datastore_filter: "<datastore_partial_name_for_search>"
vm_domain: "<domain_suffix_for_vm_naming>"
```
