### ISSUE TITLE
find paths doesn't use expanduser

### ISSUE THREAD

**Issue by yfried** [ansible/ansible#19869]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

``find`` module

##### ANSIBLE VERSION

```
ansible 2.1.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Fedora 25 -> RHEL 7.3

##### STEPS TO REPRODUCE

```yaml
find:
    paths: "~/mydir"
    patterns: somefile
```

##### EXPECTED RESULTS

expected ``find`` to search ``$HOME/mydir``

##### ACTUAL RESULTS
``~`` isn't resolved

```
msg: ~/mydir was skipped as it does not seem to be a valid directory or it cannot be accessed
```

**Comment by pwrmiller** [comment]
Additionally, the find module does not support relative paths. 

```yaml
- name: find some output with a relative path
  find:
    paths: "{{playbook_dir}}/../*.tar"
```

Results: 

```json
{"changed": false, "examined": 0, "files": [], "matched": 0, "msg": "/Users/pmiller/ansible-deploy/../*.tar was skipped as it does not seem to be a valid directory or it cannot be accessed\n"}
```

It seems that with_fileglob might be an appropriate workaround, as it supports relative paths. The find module not matching the same behaviour is counter-intuitive, however.
