### ISSUE TITLE
ansible_pull module / upgrade pull mode topology usage

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1987]
This module would upgrade ansible-pull as we know it today.

What it does is cause a git checkout on the remote server from a given URL and run that playbook, and then, using a callback which it ALSO transfers, return the structured data summary of that ansible playbook run into ansible-playbook output.

```
hosts: all
serial: 10

tasks:

   - yum: name=ansible state=installed
   - ansible_pull:  repo=git://.... user=root etc
```

Thus it could still be used with ansible as the orchestration front end for rolling updates (if desired), and with async, and so on.

Rather than implement this as a callback, it would be ideal if regular /usr/bin/ansible also had a --json output mode.

To be explored in further depth later.

**Comment by mpdehaan** [comment]
cc @skvidal -- may be better than an ansi-ball if done correctly :)

cc @sfromm -- thoughts?

**Comment by mpdehaan** [comment]
Use with async in fire and forget fashion would allow massive host reconfiguration.

```
hosts: all
gather_facts: False 

tasks:
      - yum: name=ansible state=installed
      - ansible_pull:  repo=git://.... user=root
        async: True
```

Though for this would require another playbook (maybe just a helper script?) to run and scrape the results and report on them, maybe, if not run async poll?
