### ISSUE TITLE
Openstack os_user_role module can't looping over elements

### ISSUE THREAD

**Issue by rrbarreto** [ansible/ansible#19877]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

os_user_role
##### ANSIBLE VERSION

```
ansible-2.1.0.0-1.fc22.noarch
ansible-2.3.0-100.git201612281416.fed079e.devel.fc22
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Fedora release 22 (Twenty Two)
##### SUMMARY

When creating a role and make the user parameter looping the task fails with undefined item variable
##### STEPS TO REPRODUCE

```yaml
# site.yml
- name: configuring user role
  hosts: localhost
  roles:
    - os_user_role

# role task
- os_user_role:
    cloud: "{{ os_cloud }}"
    state: "{{ os_user_role_state }}"
    user: "{{ item }}"
    role: "{{ os_user_role }}"
    project: "{{ os_project }}"
    with_items:
      - user1
      - user2
```

##### EXPECTED RESULTS

Expecting the module create the user role for both users through the loop elements
##### ACTUAL RESULTS

Task fails with:

```
TASK [os_user_role : os_user_role] *********************************************************************************************************************************************
task path: /home/rbarreto/Documents/os-templates/roles/os_user_role/tasks/main.yml:4
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/rbarreto/Documents/os-templates/roles/os_user_role/tasks/main.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- os_user_role:\n  ^ here\n"
```

**Comment by ansibot** [comment]
cc @emonty, @shrews, @juliakreger, @j2sol, @rcarrillocruz, @thingee
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nitzmahone** [comment]
You're missing the "tasks" element which the os_user_role task should be under...

**Comment by sivel** [comment]
Actually looks like that is a task in a role, however the problem is an indentation issue where `with_items` is indented too far.  It should look like:

```
# role task
- os_user_role:
    cloud: "{{ os_cloud }}"
    state: "{{ os_user_role_state }}"
    user: "{{ item }}"
    role: "{{ os_user_role }}"
    project: "{{ os_project }}"
  with_items:
    - user1
    - user2
```

**Comment by nitzmahone** [comment]
Ah, I misunderstood the "role task" comment. Yep, that'd do it too.

**Comment by rrbarreto** [comment]
Hello Guys,

Ident and ansible syntax are ok because if I use like below works properly:

```
- os_user_role:
    cloud: "{{ os_cloud }}"
    state: "{{ os_user_role_state }}"
    user: user1
    role: "{{ os_user_role }}"
    project: "{{ os_project }}"

- os_user_role:
    cloud: "{{ os_cloud }}"
    state: "{{ os_user_role_state }}"
    user: user2
    role: "{{ os_user_role }}"
    project: "{{ os_project }}"
```

Thank you
