### ISSUE TITLE
ec2_group: use of a single port_range argument instead of from_port and to_port

### ISSUE THREAD

**Issue by jbscare** [ansible/ansible#19888]
_From @nicolas-g on November 28, 2014 15:2_

##### Issue Type:

Feature Idea

##### Component Name:
ec2_group module

##### Summary:

This is a very small importance feature but it would be nice when using ec2_group module (http://docs.ansible.com/ec2_group_module.html) to define the ports using a single single `port_range` argument instead of having to define `from_port` and `to_port` .

This way it's going to be similar with the AWS console Port Range definition and you avoid to define the value twice when the rule is about a single port , as for example : 
##### Now:

```
rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
```
##### using port_range :

```
rules:
        - proto: tcp
          port_range: 80
          cidr_ip: 0.0.0.0/0
```

or defining a port range : 
##### Now:

```
rules:
        - proto: tcp
          from_port: 0
          to_port: 65535
          cidr_ip: 0.0.0.0/0
```
##### using port_range :

```
rules:
        - proto: tcp
          port_range: 0-65535
          cidr_ip: 0.0.0.0/0
```

_Copied from original issue: ansible/ansible-modules-core#401_

**Comment by jbscare** [comment]
_From @wrouesnel on September 17, 2015 21:16_

This could be made more succinct quite easily:

``` yaml
# A list of ports (expands into multiple rules)
rules:
  - proto: tcp
    ports: 80,443
# A port range
rules:
  - proto: tcp
    ports: 9000-9100
# A single port (degenerate case of 1)
rules:
  - proto: tcp
    ports: 80
# Alternate port list method
rules:
 - proto: tcp
   ports: 80 443 1122
```

List detection logic would also be good, so the parameter could just be passed a list of ports from jinja2 rather then doing a join.
