### ISSUE TITLE
Error when pulling docker image from aws ecr

### ISSUE THREAD

**Issue by damien-tinyclues** [ansible/ansible#19880]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_container
docker_image

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
ANSIBLE_HOST_KEY_CHECKING=False
ANSIBLE_RETRY_FILES_ENABLED=False
```

##### OS / ENVIRONMENT
ubuntu 16.04

##### SUMMARY
When I try to pull an image from aws ecr, the module can't pull the image but I can pull with the docker cli

##### STEPS TO REPRODUCE

```
- name: Git clone amazon-ecr-credential-helper
  git:
    repo: https://github.com/awslabs/amazon-ecr-credential-helper.git
    dest: /opt/amazon-ecr-credential-helper

- name: Stat amazon-ecr-credential-helper
  stat: path=/bin/docker-credential-ecr-login
  register: is_present

- name: Build amazon-ecr-credential-helper
  command: make docker
  args:
    chdir: /opt/amazon-ecr-credential-helper
  when: is_present.stat.exists != true

- name: Copy amazon-ecr-credential-helper to /bin
  command: mv /opt/amazon-ecr-credential-helper/bin/local/docker-credential-ecr-login /bin/
  when: is_present.stat.exists != true

- name: Start my_container_from_ecr
  docker_container:
    name: "my_container_from_ecr"
    image: "{{ my_container_from_ecr_image }}"
    state: started
```

The docker config contain that:
```
{
    "credsStore": "ecr-login"
}
```

When I use the `docker pull REGISTRY_ID.dkr.ecr.eu-west-1.amazonaws.com/my_container_from_ecr`, the pull run correctly

##### EXPECTED RESULTS

The docker module can use the `credsStore` in docker config or can get ecr credentials with boto or another library

##### ACTUAL RESULTS

```
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/cloud/docker/docker_container.py
<52.214.65.249> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.214.65.249> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/admin.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 52.214.65.249 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1483551349.94-237350112602778 `" && echo ansible-tmp-1483551349.94-237350112602778="` echo $HOME/.ansible/tmp/ansible-tmp-1483551349.94-237350112602778 `" ) && sleep 0'"'"''
<52.214.65.249> PUT /tmp/tmp6iLXrs TO /home/ubuntu/.ansible/tmp/ansible-tmp-1483551349.94-237350112602778/docker_container.py
<52.214.65.249> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/admin.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[52.214.65.249]'
<52.214.65.249> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.214.65.249> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/admin.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 52.214.65.249 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1483551349.94-237350112602778/ /home/ubuntu/.ansible/tmp/ansible-tmp-1483551349.94-237350112602778/docker_container.py && sleep 0'"'"''
<52.214.65.249> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<52.214.65.249> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/admin.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 52.214.65.249 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-ktqmxjmfiezzpdctmzdbrfpyztakixvy; /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1483551349.94-237350112602778/docker_container.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1483551349.94-237350112602778/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [52.214.65.249]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_version": null, 
            "blkio_weight": null, 
            "cacert_path": null, 
            "capabilities": null, 
            "cert_path": null, 
            "cleanup": false, 
            "command": null, 
            "cpu_period": null, 
            "cpu_quota": null, 
            "cpu_shares": null, 
            "cpuset_cpus": null, 
            "cpuset_mems": null, 
            "debug": false, 
            "detach": true, 
            "devices": null, 
            "dns_opts": null, 
            "dns_search_domains": null, 
            "dns_servers": null, 
            "docker_host": null, 
            "entrypoint": null, 
            "env": null, 
            "env_file": null, 
            "etc_hosts": null, 
            "exposed_ports": null, 
            "filter_logger": false, 
            "force_kill": false, 
            "groups": null, 
            "hostname": null, 
            "ignore_image": false, 
            "image": "REGISTRY_ID.dkr.ecr.eu-west-1.amazonaws.com/my_container_from_ecr:1", 
            "interactive": false, 
            "ipc_mode": null, 
            "keep_volumes": true, 
            "kernel_memory": null, 
            "key_path": null, 
            "kill_signal": null, 
            "labels": null, 
            "links": null, 
            "log_driver": null, 
            "log_options": null, 
            "mac_address": null, 
            "memory": "0", 
            "memory_reservation": null, 
            "memory_swap": null, 
            "memory_swappiness": null, 
            "name": "ci", 
            "network_mode": null, 
            "networks": null, 
            "oom_killer": null, 
            "oom_score_adj": null, 
            "paused": false, 
            "pid_mode": null, 
            "privileged": false, 
            "published_ports": null, 
            "pull": false, 
            "purge_networks": false, 
            "read_only": false, 
            "recreate": false, 
            "restart": false, 
            "restart_policy": null, 
            "restart_retries": null, 
            "security_opts": null, 
            "shm_size": null, 
            "ssl_version": null, 
            "state": "started", 
            "stop_signal": null, 
            "stop_timeout": null, 
            "timeout": null, 
            "tls": null, 
            "tls_hostname": null, 
            "tls_verify": null, 
            "trust_image_content": false, 
            "tty": false, 
            "ulimits": null, 
            "user": null, 
            "uts": null, 
            "volume_driver": null, 
            "volumes": null, 
            "volumes_from": null
        }, 
        "module_name": "docker_container"
    }, 
    "msg": "Error pulling REGISTRY_ID.dkr.ecr.eu-west-1.amazonaws.com/my_container_from_ecr - code: None message: unauthorized: authentication required"
}
```
