### ISSUE TITLE
Module ios_config: interoperability of src and match params

### ISSUE THREAD

**Issue by selfuryon** [ansible/ansible#19884]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY
Now I can't use src param with match. Default behaviour for src is match line. I can't use strict or exact for match param.

##### STEPS TO REPRODUCE. 
Now src are working like match line and only with them. It can be the problem in some cases if we want exact matching as example.

Example. I have this playbook:
```yaml
---
- hosts:
  - cisco_device
  gather_facts: no
  connection: local
  vars_prompt:
    - name: "pass"
      prompt: "Your password"
  vars:
    provider:
      host: "{{ inventory_hostname }}"
      username: username
      password: "{{ pass }}"
      transport: cli
  tasks:
  - name: IOS | Config object-group
    ios_config:
      src: ../config_templates/object_template.j2
      match: exact
      replace: block
      provider: "{{ provider }}"
    register: out
  - name: Result
    debug:
      var: out

```
My template for cisco looks like:
```HTML+Django
object-group network OG_GLOBAL_LAN_PREFIX
 {% for item in OG_GLOBAL_LAN_PREFIX %}
 {{ item }}
 {% endfor %}
```
In it I'm using host vars like this:
```yaml
OG_GLOBAL_LAN_PREFIX:
  - "10.0.0.0 255.0.0.0"
  - "172.16.0.0 255.240.0.0"
  - "192.168.0.0 255.255.0.0"
```

##### EXPECTED RESULTS
So I want to use match: exact in this situation. From cisco it should look like:
```
object-group network OG_GLOBAL_LAN_PREFIX 
 10.0.0.0 255.0.0.0
 172.16.0.0 255.240.0.0
 192.168.0.0 255.255.0.0
```

##### ACTUAL RESULTS
But without match: exact it can be a valid in this situation:
```
object-group network OG_GLOBAL_LAN_PREFIX 
 10.0.0.0 255.0.0.0
 172.16.0.0 255.240.0.0
 192.168.0.0 255.255.0.0
 X.X.X.X Y.Y.Y.Y
```
Because with have match line behaviour.

Now in ansible I can't use match exact/strict because they require line param...

**Comment by ansibot** [comment]
cc @privateip, @gundalow, @Qalthos
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by selfuryon** [comment]
params 'before' and 'after' also don't work with src. Maybe make them work together?

**Comment by ansibot** [comment]
cc @ganeshrn @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kedarX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
Once this we need very clear examples and documentation for this

**Comment by gundalow** [comment]
@ganeshrn thinks this may be supported now, need to check

**Comment by ganeshrn** [comment]
`src` option should be supported with `match` and `replace` options from Ansible 2.7 version onwards. Please retest with Ansible 2.7 version.

needs_info

**Comment by selfuryon** [comment]
ok, I'll try to test it at weekend!

**Comment by baltazar1** [comment]
I've tested with 

ansible --version
ansible 2.7.2

It says now: 

fatal: [TEST-AC3850]: FAILED! => {"changed": false, "msg": "match is exact but all of the following are missing: lines"}

**Comment by selfuryon** [comment]
Yeah, I've just tested it too and I have the same error. It's happening because we can use `match: exact` only with lines and cannot use it with templates in the new version?

Some output:
```
# yakovlev @ PRM-OSIC-0005 in ~/ansible/network [15:53:36] 
$ ansible --version                                                  
ansible 2.7.6
  config file = None
  configured module search path = ['/home/yakovlev/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0]

# yakovlev @ PRM-OSIC-0005 in ~/ansible/network [15:54:29] 
$ cat acl.yml
- name: Testing acl
  hosts: prm-br-01
  connection: network_cli 
  tasks: 
  - name: IOS | Config object-group 
    ios_config: 
      src: object_template.j2 
      match: exact 
      replace: block 
      diff_against: running
$ ansible-playbook -i inventory/network --diff -u yakovlev -k acl.yml                                                                       
SSH password:                                                                                                                               
                                                                                                                                            
PLAY [Testing acl] *************************************************************************************************************************
                                                                                                                                            
TASK [Gathering Facts] *********************************************************************************************************************
ok: [prm-br-01]                                                                                                                             
                                                                                                                                            
TASK [IOS | Config object-group] ***********************************************************************************************************
fatal: [prm-br-01]: FAILED! => {"changed": false, "msg": "match is exact but all of the following are missing: lines"}                      
        to retry, use: --limit @/home/yakovlev/ansible/network/acl.retry                                                                    
                                                                                                                                            
PLAY RECAP *********************************************************************************************************************************
prm-br-01                  : ok=1    changed=0    unreachable=0    failed=1 

```

**Comment by selfuryon** [comment]
If I use this config:
```yaml
- name: Testing acl
  hosts: prm-br-01
  connection: network_cli 
  tasks: 
  - name: IOS | Config object-group 
    ios_config: 
      parents: object-group network OG_GLOBAL_LAN_PREFIX
      before: no object-group network OG_GLOBAL_LAN_PREFIX
      lines: "{{ OG_GLOBAL_LAN_PREFIX }}"
      match: exact 
      replace: block 
      diff_against: running
```
All works fine:
```shell
$ ansible-playbook -i inventory/network --diff -u yakovlev -k acl2.yml                                                                      
SSH password:                                                                                                                               
                                                                                                                                            
PLAY [Testing acl] *************************************************************************************************************************
                                                                                                                                            
TASK [Gathering Facts] *********************************************************************************************************************
ok: [prm-br-01]                                                                                                                             
                                                                                                                                            
TASK [IOS | Config object-group] ***********************************************************************************************************
--- before                                                                                                                                  
+++ after
@@ -117,7 +117,6 @@
  10.0.0.0 255.0.0.0
  172.16.0.0 255.240.0.0
  192.168.0.0 255.255.0.0
- 202.0.0.0 255.0.0.0
 redundancy
 ip tftp source-interface Loopback0

changed: [prm-br-01]

PLAY RECAP *********************************************************************************************************************************
prm-br-01                  : ok=2    changed=1    unreachable=0    failed=0
```

I understand that there is a problem for template to understand how to revert some lines to needed, cuz for lines it's resolved by using `before` parameter (but this is a problem too due to deleting the whole parent object usually). But are there some solutions for that with using templates?
