### ISSUE TITLE
ec2_vpc doesn't wait for subnets to be created, errors out intermittently

### ISSUE THREAD

**Issue by nergdron** [ansible/ansible#19895]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_vpc

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/tessa/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When creating a VPC that has subnets embedded in the declaration, it appears that the underlying boto calls don't wait or check to make sure the subnets have been created before proceeding. This means if the calls happen quickly, it can error our with a message about the subnets being missing, only for them to appear in AWS moments later.

##### STEPS TO REPRODUCE
Run a VPC creation with subnets repeatedly, and at less busy times of the day (when the API is more responsive) it'll fail with missing subnet errors.

```yaml
    - name: "{{ prefix }} VPC"
      ec2_vpc:
        cidr_block: "{{ vpc_subnet }}"
        region: "{{ region }}"
        internet_gateway: yes
        resource_tags:
          Name: "{{ prefix }}-vpc"
          Prefix: "{{ prefix }}"
        state: "{{ state }}"
        subnets:
          - { cidr: "{{ dmz_subnet }}", resource_tags: { Name: "{{ prefix }}-dmz" } }
          - { cidr: "{{ private_subnet }}", resource_tags: { Name: "{{ prefix }}-private" } }
```

```bash
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to create subnet 172.30.0.0/17, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidSubnetID.NotFound</Code><Message>The subnet ID 'subnet-8e50e2b2' does not exist</Message></Error></Errors><RequestID>6a476f37-9be8-4e22-9f59-a3f500201e48</RequestID></Response>"}

# aws ec2 describe-subnets --subnet-ids subnet-8e50e2b2
{
    "Subnets": [
        {
            "VpcId": "vpc-cf1eaba9", 
            "Tags": [
                {
                    "Value": "tessa-dmz", 
                    "Key": "Name"
                }
            ], 
            "CidrBlock": "172.30.0.0/17", 
            "MapPublicIpOnLaunch": false, 
            "DefaultForAz": false, 
            "State": "available", 
            "AvailabilityZone": "us-east-1b", 
            "SubnetId": "subnet-8e50e2b2", 
            "AvailableIpAddressCount": 32763
        }
    ]
}
```

##### EXPECTED RESULTS
subnets and vpc to be created correctly

##### ACTUAL RESULTS
Errors out perhaps 5% of the time.

note that the AWS API docs seem to indicate a lot of these operations are atomic when in fact there can be significant delays from when the API call returns to when the resource is created. So this may be a larger class of issue where Ansible should always verify a resource has been created (with a timeout) before proceeding to next steps, at least where boto calls are concerned.
