### ISSUE TITLE
Ansible 2.2.0.0: Variables in handler names not populated

### ISSUE THREAD

**Issue by command-tab** [ansible/ansible#19898]
**Issue Type:** Bug Report, Regression from #15713

**Component Name:** handlers

**Ansible Version:** 2.2.0.0

**Environment:** OS X 10.11.6

**Summary:** Under Ansible 2.2.0.0, Jinja variables contained in a handler `name` are no longer populated. Under Ansible 1.9.x and 2.1.1.0, they were populated. Here's a quick example:

**Steps To Reproduce:**
1. Write this content to `playbook.yml`:
   
   ``` yml
   ---
   - hosts: localhost
     connection: local
     vars:
       appname: someapp
     handlers:
     # The following line, when the handler is executed, does not populate {{ appname }}
     - name: restart {{ appname }}
       debug:
         msg: some bogus module call in handler {{ appname }}
     tasks:
     - name: bogus task with notify for {{ appname }}
       command: ls
       notify: restart {{ appname }}
   ```
2. Run the playbook: `ansible-playbook --connection=local playbook.yml`

**Expected Results:** In the output of the playbook run, any mention of `{{ appname }}` should not appear, but replaced with `someapp`, per the given variables.

**Actual Results:**

```
  [WARNING]: Host file not found: /usr/local/etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [bogus task with notify for someapp] **************************************
changed: [localhost]

RUNNING HANDLER [restart {{ appname }}] ****************************************
ok: [localhost] => {
    "msg": "some bogus module call in handler someapp"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

Note that in the `RUNNING HANDLER` line, the Jinja template syntax is printed literally, rather than being populated with the variable that clearly exists, since it's populated elsewhere. This is a regression from [1.9.x](https://github.com/ansible/ansible/issues/14082) and [2.1.1.0](https://github.com/ansible/ansible/issues/16922#issuecomment-251805585).
