### ISSUE TITLE
docker_container module doesn't match existing container when entrypoint is used

### ISSUE THREAD

**Issue by yamatt** [ansible/ansible#19894]
_From @yamatt on October 31, 2016 21:15_

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`docker_container`

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Linux/Fedora 22

##### SUMMARY

When running a task with an `entrypoint` parameter, a docker container is destroyed and recreated each time after the first time it is run.

##### STEPS TO REPRODUCE

Fill in the variables and run this twice:
```
- name: Create data container
  docker_container:
    name: "{{ docker_data_name }}"
    image: "{{ image }}"
    state: present
    entrypoint: "/bin/echo Data-only container for {{ name }}"
```
On the second run this roduces:
```
TASK [docker-image : Create data container] ************************************
changed: [hostname]
```
Destroy that container, comment out the entrypoint, then run this twice
```
- name: Create data container
  docker_container:
    name: "{{ docker_data_name }}"
    image: "{{ image }}"
    state: present
    #entrypoint: "/bin/echo Data-only container for {{ name }}"
```
On the second run this poduces:
```
TASK [docker-image : Create data container] ************************************
ok: [hostname]
```

##### EXPECTED RESULTS

Ansible reports no change. The created timestamp should be the same as the first time it was run.

##### ACTUAL RESULTS

Ansible reports a change, and the created timestamp becomes recent.

_Copied from original issue: ansible/ansible-modules-core#5446_
