### ISSUE TITLE
AnsibleModuleCommon should natively speak JSON

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#1991]
We should transfer JSON to module common using modules to support future complex data transfer to modules, such as the URI module idea.

**Comment by rrtj3** [comment]
Hi Michael, Just an FYI, I have the URI module pretty much ready to go. I just need to be able to pass in headers in some sort of "key: value" pair format.

**Comment by mpdehaan** [comment]
Yeah I can see where we do _not_ want to just use the new enviornment: for this as it may contain spaces and other things, etc.

Though you could wire that up as a temporary hack until we get that in place.

**Comment by rrtj3** [comment]
Ok, I think I'll try to do something like the ec2 module is doing to pass in a dictionary for the time being.

**Comment by mpdehaan** [comment]
I had someone else asking about this.  It's in queue, but it may be a while.

I would really suggest disabling the argument checking and assuming
anything starting with HTTP_HEADER_ is a header.

There should be no reason we need complex headers here.

**Comment by rrtj3** [comment]
This seems to work well. Here's an example task:

``` yaml
   - name: Login to a webpage that uses a form based authentication
     uri: url=https://some.server.com/path/index.php method=POST body="name=your_user&password=your_pass&enter=Sign%20in" status_code=302 headers='{"Content-Type":"application/x-www-form-urlencoded"}'
     register: login
```

Then in the uri module I grab the data like so:

``` python
    dict_headers = {}
    if headers:
        dict_headers = json.loads(headers)
```

This seems like a nice solution (to me anyway). People can specify more headers if necessary, etc...
