### ISSUE TITLE
jinja templating applied inconsistently

### ISSUE THREAD

**Issue by nergdron** [ansible/ansible#19956]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
I guess this is in ansible core, or wheverever the jinja templating stuff lives.

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/tessa/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When doing more complex workflows, like trying to set nested fact variables, the way jinja templating is applied is inconsistent. In some cases, it'll be run through jinja, and in others, it clearly isn't.

##### STEPS TO REPRODUCE
```yaml
 set_fact:
    versions:
      "{{ item.item.key }}":
        "{{ item.versions[0] | default(None) }}"
```

##### EXPECTED RESULTS
get a result dict like this:

```
ok: [localhost] => {
    "versions": {
        "keyname": "some value"
    }
}
```

##### ACTUAL RESULTS
got a result dict like this:
```
ok: [localhost] => {
    "versions": {
        "{{ item.item.key }}": "some value"
    }
}
```
