### ISSUE TITLE
win_robocopy throw a exception when return_code is not 1||2||4 

### ISSUE THREAD

**Issue by newbe36524** [ansible/ansible#19959]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_robocopy module

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/tessa/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

when win_robocopy return_code is not 1||2||4 ,$change is not been set. it will throw a exception on the code below:

```
Set-Attr $result.win_robocopy "changed" $changed
```

##### STEPS TO REPRODUCE

```yaml
  - win_robocopy:
      src: D:\\tmp\\temp\\TMP.ClientAgent\\0.0.0.1\\Software\\Service\\
      dest: D:\\tmp\\deploy\\services\\TMP.ClientAgent\\0.0.0.1\\
      recurse: true
      purge: true
```

and content in src and dest are the same . win_robocopy.return_code will be 0.

##### EXPECTED RESULTS

```
ok: [10.0.200.141] => {"changed": false, "msg": "No files copied."}
```

##### ACTUAL RESULTS
```
fatal: [10.0.200.141]: FAILED! => {"changed": false, "failed": true, "msg": "The variable '$changed' cannot be retrieved because it has not been set."}
```
