### ISSUE TITLE
Evaluate "when" condition before evaluating variables

### ISSUE THREAD

**Issue by jamesongithub** [ansible/ansible#19955]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

`when` + `with_items`

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Variables in `with_items` are evaluated before `when` condition

##### STEPS TO REPRODUCE

Run the example.

```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: blah
      with_items:
        - "{{not_defined}}"
      when: false
```

##### EXPECTED RESULTS

If when condition evaluates to false, don't evaluate variables in task.

##### ACTUAL RESULTS

Undefined variable error

```
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'not_defined' is undefined"}
```

Expected when using a `block` as well

```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - set_fact:
        condition: false
    - block:
        - debug:
            msg: blah
          with_items:
            - "{{not_defined}}"
      when: condition
```

**Comment by sivel** [comment]
The `when` statement executes for every iteration of `with_items`, so that you can can make the task conditional based on the individual item of a `with_` loop.

As such, `with_items` must be able to properly evaluate.

The recommended way to achieve this is via the `default` filter, such as:

```
    - block:
        - debug:
            msg: blah
          with_items:
            - "{{not_defined|default([])}}"
      when: condition
```

In a block, the `when` condition is merged down onto the individual tasks, so it behaves just as if the `when` condition was applied directly to the task.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by jamesongithub** [comment]
what's recommended way to handle

```yaml
- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  tasks:
    - debug:
        msg: blah
      with_items:
        - "{{list[0]}}"
      when: list|length > 0
```
