### ISSUE TITLE
ecs_taskdefinition integer parameters do not auto-cast

### ISSUE THREAD

**Issue by schenksj** [ansible/ansible#19974]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible/lib/ansible/modules/cloud/amazon/ecs_taskdefinition.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel f5c1aefca9) last updated 2017/01/05 17:48:30 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

ecs_taskdefinition requires passing many integer parameters.  If you pass them as dynamic variables from a yaml   (cpu: "{{ cpu_units }}") they are passed to boto as strings, and rejected at runtime.  Some action may need to be taken to actively cast the integer parameters which are passed to boto

##### STEPS TO REPRODUCE

```yaml
- name: "Create task definition"
  ecs_taskdefinition:
    containers:
    - name: "{{ service_name }}"
      cpu: "{{ cpu_units }}"
      essential: true
      image: "{{ docker_repo }}/{{ service_name }}:{{ service_version }}"
      memory: "{{ memory_amt }}"
      mountPoints:
      - containerPath: /opt/apache-tomcat/logs
        sourceVolume: logs
      portMappings:
      - containerPort: 8080
        hostPort: 0
      - containerPort: 8443
        hostPort: 0
      - containerPort: 11400
        hostPort: 0
      - containerPort: 11401
        hostPort: 0
      - containerPort: 11402
        hostPort: 0
      environment: "{{ ecs_env_vars.vars }}"
    volumes:
    - name: logs
      host:
        sourcePath: /logs
    family: test-cluster-taskdef
    state: present
    region: "{{ aws_region }}"
  register: task_output



CPU and memory will fail with a casting error:

ParamValidationError(report=report.generate_report())\r\nbotocore.exceptions.ParamValidationError: Parameter validation failed:\r\nInvalid type for parameter containerDefinitions[0].memory, value: 512, type: <type 'str'>, valid types: <type 'int'>, <type 'long'>\r\nInvalid type for parameter containerDefinitions[0].cpu, value: 10, type: <type 'str'>, valid types: <type 'int'>, <type 'long'>\r\n", "msg": "MODULE FAILURE"}
```

##### EXPECTED RESULTS

The task should have registered with the dynamically registered cpu/memory amt
##### ACTUAL RESULTS

Casting error, boto kicked out the request

```

```
