### ISSUE TITLE
uri changes the case of custom headers name (it captializes them) where curl (for example, or software like postman as well) does not

### ISSUE THREAD

**Issue by levequej** [ansible/ansible#19973]
##### ISSUE TYPE
 - Bug Report ? or Feat Request ? : I let you decide

##### COMPONENT NAME
uri module
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT

Centos 7.2

##### SUMMARY

uri module changes the case of the headers . I am using an efficient IP appliance to manage IP and DNS stuff with ansible but I cannot autenticate properly :
 
The appliance uses case sensitive custom headers (I guess it's bad cos the RFC says it should not matter) : [The RFC says](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) : 

> Each header field consists of a name followed by a colon (":") and the field value. Field names are case-insensitive

"X-IPM-Username" becomes "X-Ipm-Username"
"X-IPM-Password" becomes "X-Ipm-Password"

I can check with a "curl" that a working query with the original uppercase IPM with the  headers fails when the "IPM" within the header is capitalized to "Ipm"

Anyway if it's case insensitive, could you just not modidy the case ? (dunno if it's ansible  related or underlying python libraries related).

I'm gonna use curl command, but I guess this behavior could affect other users and it took me a while to understand the problem.

##### STEPS TO REPRODUCE

```yaml
        url: >-
          {{ eip_restlike_api_url }}/dns_zone_list
        headers:
          "X-IPM-Username": "{{ eip_login | b64encode }}"
          "X-IPM-Password": "{{ eip_pwd | b64encode }}"
        status_code: 200
        method: GET
```

##### EXPECTED RESULTS

unmodified headers

##### ACTUAL RESULTS

-vvvv still show unmodified case, with 

```
            "headers": {
                "X-IPM-Password": " *****************", 
                "X-IPM-Username": " *****************"
            }, 
```
 but wireshark  gives

```
GET /rest/dns_zone_list HTTP/1.1
Accept-Encoding: identity
X-Ipm-Password: *****************
Connection: close
Host: *****************
User-Agent: ansible-httpget
X-Ipm-Username: *****************
Cache-Control: no-cache

```
