### ISSUE TITLE
kinesis_stream module fails when EC2_URL env var is set

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible#19970]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
kinesis_stream module

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.2.0.0
  config file = /role/tests/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Just like with the `s3_website` module, and potentially other modules that rely on `boto3`, this module fails without providing (any) helpful information when the EC2_URL environment variable is set.

##### STEPS TO REPRODUCE

```yaml
# Role task
- name: Streams should be added
  kinesis_stream:
    region: "{{ item.region }}"
    aws_access_key: "{{ item.access_key | default(omit) }}"
    aws_secret_key: "{{ item.secret_key | default(omit) }}"
    profile: "{{ item.boto_profile | default(omit) }}"
    name: "{{ item.name }}"
    retention_period: "{{ item.retention_period | default(omit) }}"
    shards: "{{ item.shards }}"
    tags: "{{ item.tags | default(omit) }}"
    wait: "{{ item.wait | default(omit) }}"
    wait_timeout: "{{ item.wait_timeout | default(omit) }}"
    state: present
  with_items: "{{ kinesis_to_add }}"

# Playbook excerpt
    - role: kinesis
      kinesis_to_add:
        - region: 'eu-central-1'
          name: 'ansible-role-test'
          shards: '1'
```
```bash
# printenv
AWS_REGION=eu-central-1
EC2_URL=https://ec2.eu-central-1.amazonaws.com
AWS_ACCESS_KEY=XXX
AWS_SECRET_KEY=YYY
```

If the `EC2_URL` variable is unset, then the module works as expected.

##### EXPECTED RESULTS
The Kinesis stream would be created as per its definition.

##### ACTUAL RESULTS

```
TASK [kinesis : Streams should be added] ************************************
failed: [localhost] (item={u'region': u'eu-central-1', u'name': u'ansible-role-test', u'shards': u'1'}) => {"changed": false, "failed": true, "item": {"name": "ansible-role-test", "region": "eu-central-1", "shards": "1"}, "msg": "", "result": {}, "success": false}
```
