### ISSUE TITLE
gce module fails with "unsupported parameter for module: credentials_file"

### ISSUE THREAD

**Issue by gpolyn** [ansible/ansible#19978]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/cloud/google/gce.py

##### ANSIBLE VERSION
```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Python 2.7.10 from virtualenv and using apache-libcloud==1.5.0

##### OS / ENVIRONMENT
OS X 10.10.5

##### SUMMARY
Attempting to duplicate instance creation from example at http://docs.ansible.com/ansible/guide_gce.html.

##### STEPS TO REPRODUCE

Please note I am able to interact with google cloud using apache-libcloud with same credentials.

<---hosts file--->
localhost ansible_connection=local

<---playbook.yml--->

```yaml
---
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: ...@developer.gserviceaccount.com
    credentials_file: /Users...json
    project_id: ...238
    machine_type: n1-standard-1
    image: debian-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
```

Command is: ansible-playbook -i hosts playbook.yml -vvvv

##### EXPECTED RESULTS
Something indicating success; undocumented!

##### ACTUAL RESULTS
```
PLAY [Create instance(s)] ******************************************************

TASK [Launch instances] ********************************************************
task path: /Users/me/ansible/me/guide_gce/as_of_010617.yml:16
ESTABLISH LOCAL CONNECTION FOR USER: me
localhost EXEC /bin/sh -c '( umask 22 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1483722674.82-53534914954591 `" && echo "` echo $HOME/.ansible/tmp/ansible-tmp-1483722674.82-53534914954591 `" )'
localhost PUT /var/folders/h1/bg76tk196rz065b81p1d28ch0000gn/T/tmpp7fYZZ TO /Users/me/.ansible/tmp/ansible-tmp-1483722674.82-53534914954591/gce
localhost EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /Users/me/.ansible/tmp/ansible-tmp-1483722674.82-53534914954591/gce; rm -rf "/Users/me/.ansible/tmp/ansible-tmp-1483722674.82-53534914954591/" > /dev/null 2>&1'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": <OMITTED>
"module_name": "gce"}, "msg": "unsupported parameter for module: credentials_file"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @as_of_010617.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by ansibot** [comment]
cc @supertom
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by supertom** [comment]
@gpolyn I haven't verified/tested, but my first inclination would be to swap 'credentials_file' with 'pem_file' and see if you have better results, given the versions of ansible and libcloud that you have.

If you are willing and able, I would recommend upgrading at least libcloud to the latest 1x release.

**Comment by gpolyn** [comment]
@supertom with no other changes to my playbook, except the following, as I think you recommended:
````YAML
   - name: Launch instances
     gce:
         instance_names: dev
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         # credentials_file: "{{ credentials_file }}"
         pem_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
````
I get the following error: "RSA key format is not supported"

I think it is reasonable to prefer success with the official guidance, rather than use *.pem.

Finally, as mentioned in my issue summary, I am using libcloud 1.5.
