### ISSUE TITLE
Add the ability to create / delete RDS Option Groups for AWS

### ISSUE THREAD

**Issue by jxn** [ansible/ansible#19987]
It is possible to use the RDS module to assign an option group, but it is not currently possible to create/remove an option group in Ansible (2.2)

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ec2 module, probably needs its own action, such as `rds_option_group`

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Cannot create / remove option groups for AWS RDS.  These are not the same as parameter groups.

##### STEPS TO REPRODUCE

Something like this would be nice:
```yaml
- name: create RDS Native Backup Option Group
  rds_option_group:
    name: "native-backup"
    state: present
    options:
        SQL_SERVER_BACKUP_RESTORE: my-bucket-name
- name: create RDS instance and add it to option group
  rds:
    ...
    - option_group: native-backup  
```

##### EXPECTED RESULTS
Option Group is created by ansible task

##### ACTUAL RESULTS
no such option exists
