### ISSUE TITLE
Unarchive module URL src does not follow redirect

### ISSUE THREAD

**Issue by siwyd** [ansible/ansible#19985]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
unarchive

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Arch Linux

##### SUMMARY
I'm trying to unarchive a zip file using the unarchive module. It works using a non-redirected URL, but not with a redirected URL.

##### STEPS TO REPRODUCE

In this playbook the first task will work and the second one won't. The first task's URL is one of the redirect URL's behind the second task's URL.
```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Install Kodi Subscene.com subtitles add-on (success).
      unarchive:
        src: http://ftp.heanet.ie/mirrors/xbmc/addons/jarvis/service.subtitles.subscene/service.subtitles.subscene-1.7.1.zip
        dest: /tmp
        remote_src: true

    - name: Install Kodi Subscene.com subtitles add-on (fail).
      unarchive:
        src: http://mirrors.kodi.tv/addons/jarvis/service.subtitles.subscene/service.subtitles.subscene-1.7.1.zip
        dest: /tmp
        remote_src: true
...
```

##### EXPECTED RESULTS
I would have expected redirecting to work.

##### ACTUAL RESULTS
```
hb@aramaki ~/git/hyperbaton-ansible (git)-[master] % ansible-playbook playbooks/bugreports/unarchive_url_redirect_fail.yml 

PLAY [localhost] ***************************************************************

TASK [Install Kodi Subscene.com subtitles add-on (success).] *******************
ok: [localhost]

TASK [Install Kodi Subscene.com subtitles add-on (fail).] **********************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://mirrors.kodi.tv/addons/jarvis/service.subtitles.subscene/service.subtitles.subscene-1.7.1.zip, HTTP Error 403: Forbidden"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
