### ISSUE TITLE
OpenStack quota modules

### ISSUE THREAD

**Issue by rrbarreto** [ansible/ansible#19991]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

os_nova_quota
os_neutron_quota
os_cinder_quota

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Currently, there isn't any module to manage quotas in OpenStack

##### STEPS TO REPRODUCE

Something like this:

```yaml
- os_nova_quota:
    cloud: os_cloud
    project: myproject
    instances: 4
    cores: 8
    ram: 8192
    key_pairs: 10

- os_neutron_quota:
    cloud: os_cloud
    project: myproject
    floatingip: 4
    network: 2
    router: 1
    security_group: 10
    security_group_rule: 100

- os_cinder_quota:
    cloud: os_cloud
    project: myproject
    gigabytes: 1000
    snapshots: 10
    volumes: 10
```

##### EXPECTED RESULTS

Manage resource quotas on OpenStack
##### ACTUAL RESULTS

There isn't any module to do like that
