### ISSUE TITLE
wait_for_connection: action plugin to wait until ansible connection is restored

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#19998]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

wait_for_connection

##### ANSIBLE VERSION

v2.3

##### SUMMARY

When you are building new systems (think: vmware clone) it would be nice to be able to just wait until you can run something remotely. Usually what's being done right now is that we use **wait_for** on e.g. tcp/22 and as soon there is a connection we can use it.

In the Windows world it's not that simple. The port may already be listened on, but WinRM is not working yet (it may take up to 20 seconds before it starts working instead of giving HTTP 500). win_reboot understands this quite well and what win_reboot does I want to have as well (without the reboot, that is).

Even on Linux your SSH may already be up, but the SSH keys may not have been deployed yet (think of kickstart SSH during installation, not %post). So testing for the connection to be actually working is what is required.

It is important to understand that depending on the systems configuration this could mean testing the ssh connection (on a different port using different credentials) or winrm connection (using kerberos, https, or other auth metods) based on a systems characteristics as configured in ansible.

That's why I'd like to have a wait_for_connection that is just an action plugin and works for both Linux and Windows equally well. I plan to write this the coming days.

```yaml
- name: Wait for system to become reachable
  wait_for_connection:
    timeout: 600
    sleep: 5
```

**Comment by jhawkesworth** [comment]
Not sure specifically what you want to connect to, but you might be able to use a trick like this

```yaml
- name: run test
  uri:
    url: "https://0.0.0.0:3030/api/canary"
    validate_certs: no
  register: result
  until: result['status']|default(0) == 200
```
as described here https://groups.google.com/d/topic/ansible-project/iLjIbsCASWU

It's a trick I use with tomcat which is pretty unhelpful in that it comes up, grabs a port then waits for (a long time) before actually responding on it.

**Comment by georgepsarakis** [comment]
I think you can also probably use the `search_regex` parameter, in order to establish that a service has started. From the documentation:

```yaml
# wait 300 seconds for port 22 to become open and contain "OpenSSH", don't assume the inventory_hostname is resolvable
# and don't start checking for 10 seconds
- local_action: wait_for
    port: 22
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    search_regex: OpenSSH
    delay: 10
```
