### ISSUE TITLE
win_package: should not require product_id information

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#19996]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_package

##### ANSIBLE VERSION

v2.3

##### SUMMARY

Requiring the user to provide the module with the product id manually is a tedious task, especially when that information is well-stored inside the MSI package itself.

See: http://www.scconfigmgr.com/2014/08/22/how-to-get-msi-file-information-with-powershell/

So why not get the product id directly from the MSI package, and use that to determine if the product is already installed or not ?

**Comment by ansibot** [comment]
cc @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trondhindenes** [comment]
Good point. There's a couple of things here:
1. win_package also deals with non-exe files (tho we could certainly add some logic for only enabling this for msifiles)
2. As you can see from the example code, you have to use com objects to get to the information - and I'm scared of running com as a part of an automation script.

However, it would be awesome to not have to go thru the motions of manually getting to the product id, so what we could do is if the `product_id` is set to `auto` or something, that would be the user's indication that we're allowed to try and auto-grab the product id. How would you feel about something like that?

**Comment by jhawkesworth** [comment]
I like the 'auto' idea - if it returned the product id in the results you
could run an ad-hoc to discover a product id.
I think it needs to be optional though as there are occasions where I must
use an exact version.

As long as it doesn't fail when it hits one of the (all too many) .msis
that don't have a product id at all, this would be a great feature.

**Comment by trondhindenes** [comment]
I'm thinking if the module params are product_id: auto and the module isn't able to extract the product id, then the module should fail. It's all it can do, really.

**Comment by jhawkesworth** [comment]
Sorry I was being vague.  I should have said if it hits one of these malformed .MSIs then it should fail gracefully with a message explaining that the product id couldn't be found.

**Comment by dagwieers** [comment]
@trondhindenes Indeed. If we expect idempotency, it should fail if it cannot guarantee.
But if it fails, it could hint to using the product_id instead !
And I would make it default to auto TBH.

**Comment by trondhindenes** [comment]
Yup, i think we totally agree. I'll see if I can get to this in the near future.

**Comment by trondhindenes** [comment]
I'm just looking into this now, and I got to thinking: Although we can estimate the correct product_id at install time (since we have the file), it's gonna be hard to do an "impodence check" to see if the software is already installed. For example, if the package path is a url, that would essentially require us to download the package on every module run, since we need to grab the product_id from the package. What are your thoughts on how we should deal with this? I'm reluctant to trust the "displayname" attribute only.

**Comment by jhawkesworth** [comment]
Feels to me like 'auto' mode can only work with local .msis.
If you want to use it like this its not a big hardship to have a win_get_url call beforehand (as win_get_url can now compare last modification times and only download if the url source is newer).
Also dag has improved win_copy recently so it better idepotence support so perhaps its ok to limit auto to local .msis now it easier to manage the .msis being stored locally.

**Comment by dagwieers** [comment]
auto-mode can work with remote files as well, but indeed they will be re-downloaded. It's not up to us to decide whether this is an acceptable proposition or not, on an internal network or for smaller files this may not really be an issue. So it's up to the user to make the right choice in using remote files, providing a product id or instead use auto-mode.

**Comment by trondhindenes** [comment]
Sounds good, I'll just have to document it well then. Thanks for the input!!

**Comment by jhawkesworth** [comment]
Yeah if you can document that it might be better not to do this, depending on what you are doing then dag is right, no need to stop it from happening.

**Comment by trondhindenes** [comment]
Guys, I've done a ton of work on this now. Would be really happy if you could test a bit before I submit the PR.
Essentially, the refactored win_package can:

- Infer msi product code from the package file, both for local and downloaded files
- Allows uninstalling without a path for msi-based files.
Updated module can be found here: https://github.com/trondhindenes/ansible/blob/devel/lib/ansible/modules/windows/win_package.ps1

Here's my little "test plan". I'd be especially keen on getting unc-based scenarios tested as I haven't gotten to that yet.
```
---
- hosts: windows
  gather_facts: false
  tasks:
    - name: SUCEEDS uninstall an msi with product id but without path
      win_package:
        name: NodeJS
        productid: "{A41A3BCF-14F8-4984-AE4E-DA662A6992B7}"
        state: absent

    - name: SUCEEDS install a local msi with product id
      win_package:
        name: NodeJS
        path: "C:\\packages\\node-v6.9.4-x64.msi"
        productid: "{A41A3BCF-14F8-4984-AE4E-DA662A6992B7}"

    - name: FAILS install an msi with product id but without path
      win_package:
        name: NodeJS
        productid: "{A41A3BCF-14F8-4984-AE4E-DA662A6992B7}"
      failed_when: false

    - name: SUCEEDS uninstall an msi with product id but without path
      win_package:
        name: NodeJS
        productid: "{A41A3BCF-14F8-4984-AE4E-DA662A6992B7}"
        state: absent

    - name: SUCCEEDS install an msi without product id
      win_package:
        name: NotepadPlusPlus
        path: "https://rikstvcommoncfmgmtsto.blob.core.windows.net/software/npp.6.9.2.installer.msi"
        productid: auto

    - name: FAILS install an msi without path (should fail)
      win_package:
        name: NPP
        productid: "{557BD390-3D2A-48EE-955D-1B88E0D00125}"
        state: present
      failed_when: False

    - name: SUCEEDS install an msi without product id
      win_package:
        name: NodeJS
        path: "C:\\packages\\npp.6.9.2.installer.msi"
        productid: auto

#This should fail in a "controlled" fashion, since it's a exe file and no product id is specified
    - name: FAILS Install the Visual C thingy
      win_package:
        name: Microsoft Visual C thingy
        path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
        arguments: /install /passive /norestart
        productid: auto
      failed_when: False

#This should fail in a "controlled" fashion as we always need the product id or path when absenting a package
    - name: FAILS uninstall an msi without product id and without path
      win_package:
        name: NotepadPlusPlus
        productid: auto
        state: absent
      failed_when: False

#This should succeed, since we infer the product id by downloading the package and getting its product id
    - name: SUCEEDS uninstall an msi without product id
      win_package:
        name: NotepadPlusPlus
        productid: auto
        state: absent
        path: "https://rikstvcommoncfmgmtsto.blob.core.windows.net/software/npp.6.9.2.installer.msi"

#This should fail in a "controlled" fashion, since it's a exe file and we won't be able to grab the product id
    - name: FAILS Install the Visual C thingy
      win_package:
        name: Microsoft Visual C thingy
        path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
        arguments: /install /passive /norestart
        productid: auto
        state: absent
      failed_when: false
```

**Comment by dagwieers** [comment]
In all of these cases I am wondering why the name-parameter is even relevant, except for documentation to the user ? Wouldn't it be better to get the name from the MSI as well, or when missing use the product-id or path instead ?

**Comment by dagwieers** [comment]
But your module is quite advanced Powershell. A bit over my head :-)

The only remarks I have is about the new Ansible windows module syntax (e.g. Get-AnsibleParam with -type and -aliases support, using normal dicts instead of PSObject for $result, implement check-mode, etc...)

**Comment by trondhindenes** [comment]
Good point,  I'll get those updated.

**Comment by jhawkesworth** [comment]
@trondhindenes - hi - I've probably just done something wrong but I just tried pulling your changed module from https://raw.githubusercontent.com/trondhindenes/ansible/devel/lib/ansible/modules/windows/win_package.ps1 so I could try  - but it is the same as the latest devel version.  Can you check your changes got pushed back up to your fork?

Many thanks,

Jon

**Comment by trondhindenes** [comment]
Sorry, my bad. Here's the correct branch:

https://github.com/trondhindenes/ansible/tree/win_package_enhancements?files=1

**Comment by jhawkesworth** [comment]
Finally got round to grabbing this.
a couple of tiny things about the docs.

might be worth saying 'since 2.3' about the 'auto' product_id functionality
some of the options descriptions end with a . and others don't (really tiny that one).

I will comment again when I have had a chance to run the module.

**Comment by dagwieers** [comment]
When I used this playbook:
```yaml
- hosts: all
  tasks:
  - win_package:
      name: Red Hat OpenJDK
      path: \\diskstation01\ictadmin\Tools\java-1.8.0-openjdk-1.8.0.121-1.b13.redhat.windows.x86_64.msi                                            
      arguments: /install /passive /norestart
      productid: auto
      state: present
```

I get this error:
```
[dag@moria crombeen]$ ansible-playbook java.yml -l computer51

PLAY [all] ******************************************************************************************************

TASK [win_package] ******************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
fatal: [computer51]: FAILED! => {"changed": false, "failed": true, "msg": "The variable '$fileExtension' cannot be retrieved because it has not been set."}

PLAY RECAP ******************************************************************************************************
computer51                 : ok=0    changed=0    unreachable=0    failed=1   
```

**Comment by dagwieers** [comment]
I needed win_package for the Red Hat OpenJDK MSI file and I tried win_package (after fixing a few issues, see up). However the playbook tells me:
```
fatal: [computer51]: FAILED! => {"changed": false, "failed": true, "msg": "Product Id was set to auto, but Ansible was unable to read the package product id automatically"}
```

So I went back to the implementation from http://www.scconfigmgr.com/2014/08/22/how-to-get-msi-file-information-with-powershell/

And that one worked fine:
```
PS Microsoft.PowerShell.Core\FileSystem::\\diskstation01\ictadmin\Tools> powershell.exe .\Get-MSIFileInformation.ps1 -Pa
th .\java-1.8.0-openjdk-1.8.0.121-1.b13.redhat.windows.x86_64.msi -Property ProductCode
{2677E1EB-C0C5-4316-B388-4E7904A5B1B8}
```

**Comment by dagwieers** [comment]
Alright, after adding the productid, the error was:
```
fatal: [computer51]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "The given Path (\\\\diskstation01\\ictadmin\\Tools\\java-1.8.0-openjdk-1.8.0.121-1.b13.redhat.windows.x86_64.msi) could not be found"
}
```
So it seems the code doesn't properly fail when the file is not found and productid = auto ?

**Comment by dagwieers** [comment]
Not sure why win_package cannot work with network paths, but I think that should work for all modules (if it doesn't out-of-the-box). Most people will expect this to work.

**Comment by jhawkesworth** [comment]
@dagwieers Network paths can be problematic because they qualify as a 'second hop' for authentication, which is usually not allowed. You can get round it using kerberos auth with auth delegation turned on of course.

**Comment by dagwieers** [comment]
@jhawkesworth A lot of things can fail because the user is not entitled (file access, running things, ...) so making this work for people that *do* have the right credentials ought to work IMO.

**Comment by jhawkesworth** [comment]
Sorry, I misunderstood before. Yes, it should work assuming all the conditions that Microsoft have imposed have been met.

**Comment by dagwieers** [comment]
If the share is open to anyone (as read-only), should it work ? Because that is the case here.

**Comment by jhawkesworth** [comment]
I think it depends on what is implementing the share on the other end.  I have definitely had this working with auth delegation when the remote share was running on a S2008R2 server.

S2012 implements a more recent version of CIFS/SMB protocol and I've had trouble in the past with shares running on non-microsoft servers which we had to tweak a registry setting to get round:
http://www.thomasmaurer.ch/2013/03/windows-8-or-windows-server-2012-cannot-access-netapp-smbcifs-share/

I haven't used win_package much in this way as I tend to fetch everything I want to install locally using win_get_url (which compares file timestamps in 'force=no' mode), then run the win_package on a local file.

**Comment by dagwieers** [comment]
I am using this only on Windows 10. The public share is a Synology NAS with DSM 6.0 (so Samba 4.1).
Anyone on the network has read-access to these shares from Explorer.

**Comment by dagwieers** [comment]
I just found out that for installing Wireshark idempotently, the product_id is actually just "Wireshark".
This was unexpected as all the examples seem to indicate it requires something in the form of "{9D573E71-1077-4C7E-B4DB-4E22A5D2B48B}".

```yaml
- name: Copy wireshark archive
  win_get_url:
    url: '{{ binaries_source }}/Wireshark-win64-2.2.6.exe'
    dest: C:\Windows\Temp\Wireshark-win64-2.2.6.exe
    force: no
    skip_certificate_validation: yes

- name: Install wireshark
  win_package:
    path: C:\Windows\Temp\Wireshark-win64-2.2.6.exe
    product_id: Wireshark
    state: present
    arguments: /NCRC /S /desktopicon=yes /quicklaunchicon=no /D=%ProgramFiles%\Wireshark
```

Maybe we should add an example like this as well ?

Beware that the obvious problem with this is that there is no unique version check. So I am not convinced that this *product_id* check for idempotency is what we should be doing :-/

Using **DisplayName** and **DisplayVersion** is probably the right way to go...
