### ISSUE TITLE
maven_artifact.py - add support for version ranges (dynamic version like 5.+) in maven artifact resolver

### ISSUE THREAD

**Issue by qwazer** [ansible/ansible#20003]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

maven_artifact

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

Add gradle-like dynamic version resolution mechanism to MavenDownloader in `packaging/language/maven_artifact.py`
For example,  
```
# Download JUnit 4.+ from Maven Central
- maven_artifact:
    group_id: junit
    artifact_id: junit
    version: 4.+
    dest: /tmp/junit-4.jar
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
