### ISSUE TITLE
jenkins_plugin: module is not installing dependencies.

### ISSUE THREAD

**Issue by vijayboopathy-zz** [ansible/ansible#20000]
##### ISSUE TYPE

 - Bug Report
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

```
[defaults]
remote_user = ubuntu
inventory = infra
```
##### OS / ENVIRONMENT

```
ubuntu 14.04
```
##### SUMMARY

```
jenkins_plugin module doesn't install dependencies of plugins
```
##### STEPS TO REPRODUCE

  
```
Task as follows:
- name: Install Build Pipeline Plugin
  jenkins_plugin:
    name: build-pipeline-plugin
    version: "1.5.6"
    with_dependencies: yes
    params: "{{ jenkins_params_plugins }}"

```

##### EXPECTED RESULTS

```
Install plugins with dependencies
```

##### ACTUAL RESULTS

```
TASK [ci : Install Build Pipeline Plugin] **************************************
changed: [192.x.x.x] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": true,
            "group": "jenkins",
            "http_agent": "ansible-httpget",
            "jenkins_home": "/home/ubuntu/docker/jenkins_home",
            "mode": "0644",
            "name": "build-pipeline-plugin",
            "owner": "jenkins",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "timeout": 30.0,
            "unsafe_writes": null,
            "updates_expiration": 86400,
            "updates_url": "https://updates.jenkins-ci.org",
            "url": "http://192.x.x.x:8080",
            "url_password": "*******",
            "url_username": "admin",
            "use_proxy": true,
            "validate_certs": false,
            "version": "1.5.6",
            "with_dependencies": true
        },
        "module_name": "jenkins_plugin"
    },
    "plugin": "build-pipeline-plugin",
    "state": "present"
}

```
```
Image added:
[Jenkins_plugin-bug](https://i.imgsafe.org/086c5ca877.jpg)
```
@jtyr

**Comment by jtyr** [comment]
As per the description of the `version` option of the [plugin](https://docs.ansible.com/ansible/jenkins_plugin_module.html):

> If this option is specified, all plugin dependencies must be installed manually.

@ansibot, please close this issue as this is `notabug`. I will modify the description of the `with_dependencies` option to clearly state that it only works if no `version` is defined.

**Comment by bcoca** [comment]
closing via #20010

**Comment by quietanomaly** [comment]
Even without specifying a version I have to read the dependency errors and install them manually. Only thing that worked for me.

- Ubuntu `16.04`
- Ansible `2.3.0.0`
- Jenkins `2.57`

```yaml
- hosts: all
  become: yes
  vars:
    # ...
    jenkins_plugins:
      - workflow-step-api
      - workflow-scm-step
      - credentials
      - git-client
      - display-url-api
      - mailer
      - junit
      - script-security
      - matrix-project
      - scm-api
      - ssh-credentials
      - structs
      - git #<--- all i needed to install
  tasks:
    # ...
    - name: install jenkins plugins
      jenkins_plugin:
        name: "{{ item }}"
        params: "{{ jenkins_cli_params }}"
        state: latest
      with_items: "{{ jenkins_plugins }}"
```

**Comment by rmohr** [comment]
I see the same. Although I don't specify a version (I even set `with_dependencies`) explicitly, it does not install dependencies.

```
ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

**Comment by jtyr** [comment]
@quietanomaly I have tried to install the `git` plugin and it worked just fine. I have been using my [`jenkins_master`](https://github.com/jtyr/ansible-jenkins_master) role for that with the following playbook:

```
- hosts: all
  vars:
    jenkins_master_plugins__default:
      git:
    jenkins_master_config_jenkins_java_options__custom: >
      -Djenkins.install.runSetupWizard=false
      -Djenkins.CLI.disabled=true
  roles:
    - jenkins_master
```

Just one more question: Did you restart Jenkins after you have installed the plugin?

**Comment by kmaris** [comment]
My dependencies are also not installing using the following task:

```
- name: Install plugins
  jenkins_plugin:
    name: "{{ item }}"
    state: latest
    with_dependencies: yes
  with_items:
    - git-client
    - workflow-aggregator
    - blueocean
  notify:
    - restart jenkins
```

The named plugins install successfully but they are not available due to missing their dependencies.

### Update

Not sure why but removing `state: latest` helped. Strange...
