### ISSUE TITLE
Win_nssm module doesn't honour the order of the app_parameters

### ISSUE THREAD

**Issue by caveman-dick** [ansible/ansible#20032]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_nssm

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT

* From: Ubuntu 15.10
* To: Windows Server 2016

##### SUMMARY
Using the win_nssm module you can supply parameters using the app_parameters field. When a specific parameter order is required this is not possible using the app_parameters as designed.

##### STEPS TO REPRODUCE

```yaml
- name: Create Jenkins windows service
     win_nssm:
       name: JenkinsSlave
       application:  C:\ProgramData\Oracle\Java\javapath\java.exe
       app_parameters:
         -jar: "{{ jenkins_path }}\\jenkins-swarm.jar"
         -fsroot: "{{ jenkins_path }}\\ws"
         -master: "{{ jenkins_url}}"
         -labels: "\"{{ jenkins_slave_labels }}\""
         -executors: "{{ jenkins_num_executors }}"
         -username: "{{ jenkins_username }}"
         -password: "{{ jenkins_password }}"         
       stdout_file: "{{ jenkins_path }}\\jenkins_slave.log"
       stderr_file: "{{ jenkins_path }}\\jenkins_slave.log"
     when: jenkins_service_installed | failed
     register: jenkins_service_installed
```

##### EXPECTED RESULTS
The parameters are added in the above order in the nssm command.

##### ACTUAL RESULTS

The order of the parameters is added in a random order.

```
TASK [Create Jenkins windows service] ******************************************
task path: /vagrant/site.yml:52
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/windows/win_nssm.ps1
<ahc-ada-build-agent1> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5986 TO ahc-ada-build-agent1
<ahc-ada-build-agent1> EXEC Set-StrictMode -Version Latest
(New-Item -Type Directory -Path $env:temp -Name "ansible-tmp-1483958401.64-260607888464786").FullName | Write-Host -Separator '';
<ahc-ada-build-agent1> PUT "/tmp/tmp3FSCrB" TO "C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1483958401.64-260607888464786\win_nssm.ps1"
<ahc-ada-build-agent1> EXEC Set-StrictMode -Version Latest
Try
{
& 'C:\Users\vagrant\AppData\Local\Temp\ansible-tmp-1483958401.64-260607888464786\win_nssm.ps1'
}
Catch
{
$_obj = @{ failed = $true }
If ($_.Exception.GetType)
{
$_obj.Add('msg', $_.Exception.Message)
}
Else
{
$_obj.Add('msg', $_.ToString())
}
If ($_.InvocationInfo.PositionMessage)
{
$_obj.Add('exception', $_.InvocationInfo.PositionMessage)
}
ElseIf ($_.ScriptStackTrace)
{
$_obj.Add('exception', $_.ScriptStackTrace)
}
Try
{
$_obj.Add('error_record', ($_ | ConvertTo-Json | ConvertFrom-Json))
}
Catch
{
}
Echo $_obj | ConvertTo-Json -Compress -Depth 99
Exit 1
}
changed: [ahc-ada-build-agent1] => {
    "changed": true,
    "changed_by": "set_stderr",
    "invocation": {
        "module_name": "win_nssm"
    },
    "nssm_app_parameters": "@{-password=[PASSWORD]; -jar=C:\\jenkins\\jenkins-swarm.jar; -master=https://jenkins.dev.local; -fsroot=C:\\jenkins\\ws; -executors=1; -labels=\"windows adastra\"; -username=[USERNAME]}",
    "nssm_app_parameters_keys": [
        "-password",
        "-fsroot",
        "-executors",
        "-jar",
        "-master",
        "-username",
        "-labels"
    ],
    "nssm_app_parameters_parsed": {
        "-executors": "1",
        "-fsroot": "C:\\jenkins\\ws",
        "-jar": "C:\\jenkins\\jenkins-swarm.jar",
        "-labels": "\"windows adastra\"",
        "-master": "https://jenkins.dev.local",
        "-password": "[PASSWORD]",
        "-username": "[USERNAME]"
    },
    "nssm_app_parameters_vals": [
        "[PASSWORD]",
        "C:\\jenkins\\ws",
        "1",
        "C:\\jenkins\\jenkins-swarm.jar",
        "https://jenkins.dev.local",
        "[USERNAME]",
        "\"windows adastra\""
    ],
    "nssm_single_line_app_parameters": "-password \"[PASSWORD]\"-fsroot \"C:\\jenkins\\ws\"-executors \"1\"-jar \"C:\\jenkins\\jenkins-swarm.jar\"-master \"https://jenkins.dev.local\"-username \"[USERNAME]\"-labels \"\"windows adastra\"\""
}
```
