### ISSUE TITLE
win_scheduled_task ability for hourly task

### ISSUE THREAD

**Issue by DepthDeluxe** [ansible/ansible#20056]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
ansible windows module: `win_scheduled_task`

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No special configuration

##### OS / ENVIRONMENT
OSX / should be general feature for all platforms

##### SUMMARY
I would like the ability to create hourly tasks and ideally, have full timing control (i.e. cron style time formatting) support for this windows module.  I recognize that the windows task scheduling tool doesn't provide that ability in a straightforward manner.

The way I did it in the past is to create a daily task and configure it to repeat hourly indefinitely.

##### STEPS TO REPRODUCE

Ansible playbook
```
- name: Configure windows task
  win_scheduled_task:
    name: TabUserGroupSynchUp
    execute: "{{ tableau_admin_path }}/Scripts/TabUserGroupSynchUp.bat"
    frequency: hourly
    time: 7:00pm
    user: SYSTEM
    state: present
    path: Tableau
```

Error output
```yaml
TASK [script-task : Configure windows task] ************************************
fatal: [tableau.***********.com]: FAILED! => {"changed": false, "exists": "True", "failed": true, "msg": "frequency must be daily or weekly"}
```

##### EXPECTED RESULTS
I would like the ability to create hourly windows tasks in Ansible.

##### ACTUAL RESULTS
The functionality currently doesn't exist in Ansible.
