### ISSUE TITLE
hosts added via add_host connect to localhost

### ISSUE THREAD

**Issue by iteratelance** [ansible/ansible#20068]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
wait_for

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### SUMMARY

When calling the `wait_for:` module I would expect setting the host property and path would indicate to test for the validation of the file on the host declaration but I've verified that it actually test for the local file system.   

I've tried this two ways. Both of these task are roles in a playbook that run on local host.

**Method 1**  _setting the delegate_to property_
Throws an error saying the path is not found.
```yaml
- name: Wait for python to be installed
  delegate_to: "{{ ami.instance.public_ip }}"
  wait_for:
    path: /usr/bin/python
    state: present
  ignore_errors: true
```
**Method 2** _setting the host property_
Looks for the file on my local host which is executing the playbook.
```yaml
- name: Wait for python to be installed
  wait_for:
    host: "{{ ami.instance.public_ip }}"
    path: /usr/bin/python
    state: present
  ignore_errors: true
```
Neither of these methods seem to work on the remote host.  The goal is to wait until python is installed on the remote host before proceeding.  I've worked around this issue by pausing, but this is obviously not ideal.

##### STEPS TO REPRODUCE
execute the play book by executing:

`ansible-playbook ami.yml -e "source=ami-e13739f6 name=test"`

Where the ami.yml  playbook calls the role:
```yaml
- name: Launch instance
  hosts: localhost
  roles:
    - {role: "aws-ami", ami_action: "launch"}
```

Below is the gist  of the `aws-ami` role.  Please note that python is installed as part of user_data.  I've verified this work by logging into the machine.
```yaml
#
#
# some other variable definitions

- name: Launch instance
  ec2:
    keypair: "{{ ami.keypair }}"
    group_id: "{{ ami.security_group_id }}"
    instance_type: "{{ ami.instance_type }}"
    image: "{{ ami.source }}"
    instance_tags:
      Name: "ami-{{ ami.name }}"
    count: 1
    wait: true
    user_data: |
      #!/bin/sh
      # add python 2.7 as required by ansible on ubuntu 16.04
      apt-get update 
      apt-get -y install python
  register: ami_result_ec2_instance

- name: Storing ec2 facts
  set_fact:
    ami: "{{ ami|combine({'instance': ami_result_ec2_instance.instances|first}) }}"
  when: ami_result_ec2_instance.changed

- name: Add new instance to host group
  add_host: 
    hostname: "{{ ami.instance.public_ip }}" 
    groupname: ami_host
    ansible_ssh_private_key_file: "{{ ami.local_keypath }}"
    ansible_user: ubuntu

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ ami.instance.public_ip }}" 
    port: 22 
    delay: 10 
    timeout: 320 
    state: started
```
Now here comes the issue. I've tried pausing here using wait_for in ever configuration imaginable and have had to settle on simply just pausing for a minute or so.

```yaml
- name: Wait for python to be installed
  delegate_to: "{{ ami.instance.public_ip }}" # does not work as expected
  wait_for:
    #host: "{{ ami.instance.public_ip }}"
    path: /usr/bin/python
    state: present
  ignore_errors: true
```

##### EXPECTED RESULTS
I expected wait_for to wait until the path defined in wait_for was defined.

##### ACTUAL RESULTS
```
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/system/setup.py
<54.167.49.200> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<54.167.49.200> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/tmp/ami-tmp-keypair.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/lancesanders/.ansible/cp/ansible-ssh-%h-%p-%r 54.167.49.200 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1484028247.14-84444498122590 `" && echo ansible-tmp-1484028247.14-84444498122590="` echo $HOME/.ansible/tmp/ansible-tmp-1484028247.14-84444498122590 `" ) && sleep 0'"'"''
<54.167.49.200> PUT /var/folders/ff/vcg73lrn5xx0z3wqrw6jbl1h0000gn/T/tmphhc8jI TO /home/ubuntu/.ansible/tmp/ansible-tmp-1484028247.14-84444498122590/setup.py
<54.167.49.200> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/tmp/ami-tmp-keypair.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/lancesanders/.ansible/cp/ansible-ssh-%h-%p-%r '[54.167.49.200]'
<54.167.49.200> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<54.167.49.200> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/tmp/ami-tmp-keypair.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/lancesanders/.ansible/cp/ansible-ssh-%h-%p-%r 54.167.49.200 '/bin/sh -c '"'"'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1484028247.14-84444498122590/ /home/ubuntu/.ansible/tmp/ansible-tmp-1484028247.14-84444498122590/setup.py && sleep 0'"'"''
<54.167.49.200> ESTABLISH SSH CONNECTION FOR USER: ubuntu
<54.167.49.200> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/tmp/ami-tmp-keypair.pem"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ubuntu -o ConnectTimeout=10 -o ControlPath=/Users/lancesanders/.ansible/cp/ansible-ssh-%h-%p-%r -tt 54.167.49.200 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-jlawkkvrhsmdpvowhayiwmjxddaiajmq; /usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1484028247.14-84444498122590/setup.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1484028247.14-84444498122590/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [54.167.49.200]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "setup"
    }, 
    "module_stderr": "OpenSSH_7.3p1, LibreSSL 2.4.1\r\ndebug1: Reading configuration data /Users/lancesanders/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 34474\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 54.167.49.200 closed.\r\n", 
    "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", 
    "msg": "MODULE FAILURE"
}
```

**Comment by iteratelance** [comment]
I've also tried to delegate_to the groupname `ami_host` in my case, and it appears that the group is set to my localhost:

```yaml
- name: Wait for python to be installed
  delegate_to: ami_host
  wait_for:
    # host: ami_host
    path: /usr/bin/python
    state: present
  ignore_errors: true
```
The error is as follows.
```
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/utilities/logic/wait_for.py
<ami_host> ESTABLISH SSH CONNECTION FOR USER: None
<ami_host> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/lancesanders/.ansible/cp/ansible-ssh-%h-%p-%r ami_host '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1484030445.12-274600522163854 `" && echo ansible-tmp-1484030445.12-274600522163854="` echo $HOME/.ansible/tmp/ansible-tmp-1484030445.12-274600522163854 `" ) && sleep 0'"'"''
fatal: [localhost]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.3p1, LibreSSL 2.4.1\r\ndebug1: Reading configuration data /Users/lancesanders/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/Users/lancesanders/.ansible/cp/ansible-ssh-ami_host-22-lancesanders\" does not exist\r\ndebug2: resolving \"ami_host\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to ami_host [198.105.244.228] port 22.\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug1: connect to address 198.105.244.228 port 22: Operation timed out\r\ndebug1: Connecting to ami_host [198.105.254.228] port 22.\r\ndebug2: fd 5 setting O_NONBLOCK\r\ndebug1: connect to address 198.105.254.228 port 22: Operation timed out\r\nssh: connect to host ami_host port 22: Operation timed out\r\n", 
    "unreachable": true
}
```

**Comment by iteratelance** [comment]
I found a workaround for this.

I had to set ansible_ssh_host when calling add_host.  Not sure if this is as designed or a bug.

```yaml
- name: Add new instance to host group
  add_host: 
    name: "{{ ami.instance.public_ip }}" 
    groups: ami_host
    ansible_ssh_private_key_file: "{{ ami.local_keypath }}"
    ansible_user: ubuntu
    ansible_ssh_host: "{{ ami.instance.public_ip }}"

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ ami.instance.public_ip }}" 
    port: 22 
    delay: 10 
    timeout: 320 
    state: started

# this method seems to check local host regardless of what host is set to
- name: Wait for python to be installed
  delegate_to: "{{ ami.instance.public_ip }}" 
  wait_for:
    path: /usr/bin/python
    state: present
  ignore_errors: true
```

**Comment by ansibot** [comment]
cc @gregswift
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by abadger** [comment]
From your latest comments it seems like wait_for is working as designed but something strange is happening with add_host.  

However, i was unable to reproduce this problem with the following playbook which has both the add_host and wait_for:
```
---
- hosts: localhost
  gather_facts: False
  vars:
    added_ip: 192.168.122.3
  tasks:
  - add_host:
      hostname: "{{ added_ip }}"
      groupname: testing
      ansible_ssh_private_key_file: "/home/badger/.ssh/id_rsa"
      ansible_user: "badger"
  - name: Wait for SSH to come up
    wait_for:
      host: "{{ added_ip }}"
      port: 22
      delay: 10
      timeout: 320
      state: started
  - wait_for:
      path: /var/tmp/advocate
      state: present
    delegate_to: "{{ added_ip }}"

  - command: hostname
    delegate_to: "{{ added_ip }}"
```
I tried this playbook with the host I'm adding shutoff until the playbook was in the wait_for for ssh on port 22.

Are you able to reproduce this without the use of a cloud instance?  Are you able to reproduce this without the use of variables?

needs_info

**Comment by iteratelance** [comment]
I think I've gotten to the bottom of this.  I do not thing it's a bug but rather that python is not yet installed on the remote host, which ironically is exactly what I was trying to accomplish by using `wait_for`.  However I'm unclear as to why my solution of explicitly defining `ansible_ssh_host` work.

For instance, the following will work if python is installed on the remote machine at the time of execution.  This is expected because ansible requires python on the remote host.

```yaml
- name: Add new instance to host group
  add_host: 
    name: "{{ added_ip }}"
    groups: ami_host
    ansible_ssh_private_key_file: "/home/badger/.ssh/id_rsa"
    ansible_user: ubuntu

  - wait_for:
      path: /var/tmp/advocate
      state: present
    delegate_to: "{{ added_ip }}"
```
results in `"module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", `

On the other hand if I explicitly define `ansible_ssh_host` when calling `add_host` all works ok.

```yaml
- name: Add new instance to host group
  add_host: 
    name: "{{ added_ip }}"
    groups: ami_host
    ansible_ssh_private_key_file: "/home/badger/.ssh/id_rsa"
    ansible_user: ubuntu
    ansible_ssh_host: "{{ added_ip }}"

  - wait_for:
      path: /var/tmp/advocate
      state: present
    delegate_to: "{{ added_ip }}"
```

Please be advised that I'm installing python via user_data on an ec2 module.

Full code block is here. Note the addition of adding `ansible_ssh_host` seems to address the issue that python is not yet installed on the remote machine.

```yaml
- name: Launch instance
  ec2:
    keypair: "{{ ami.keypair }}"
    group_id: "{{ ami.security_group_id }}"
    instance_type: "{{ ami.instance_type }}"
    image: "{{ ami.source }}"
    instance_tags:
      Name: "{{ ami.name }}"
    count: 1
    wait: true
    user_data: |
      #!/bin/sh
      # add python 2.7 as required by ansible on ubuntu 16.04
      apt-get update 
      apt-get -y install python
  register: ami_result_ec2_instance

- name: Storing ec2 facts
  set_fact:
    ami: "{{ ami|combine({'instance': ami_result_ec2_instance.instances|first}) }}"
  when: ami_result_ec2_instance.changed

- name: Add new instance to host group
  add_host: 
    name: "{{ ami.instance.public_ip }}"
    groups: ami_host
    ansible_ssh_private_key_file: "{{ ami.local_keypath }}"
    ansible_user: ubuntu
    ansible_ssh_host: "{{ ami.instance.public_ip }}" # you need this is you want delegate_to to work below.  see https://github.com/ansible/ansible/issues/20068

- name: Wait for SSH to come up
  wait_for: 
    host: "{{ ami.instance.public_ip }}" 
    port: 22 
    delay: 10 
    timeout: 320 
    state: started

- name: Wait for python to be installed
  delegate_to: "{{ ami.instance.public_ip }}" 
  wait_for:
    path: /usr/bin/python
    state: present
```

I guess the best way of handling this is somehow using the raw module to check for the existence of python before continuing.

Something to this effect: https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
