### ISSUE TITLE
Jinja2 2.9+ breaks included template context

### ISSUE THREAD

**Issue by sysadmind** [ansible/ansible#20063]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Template

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 0aad46c85b) last updated 2017/01/09 16:11:21 (GMT -400)
  config file = /home/jadams/.ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
Tested on vanilla / no extra configuration

##### OS / ENVIRONMENT
N/A but tested from Fedora 25

##### SUMMARY
When Jinja2 dependency is >= 2.9.0, nested templates inside of loops defined in a parent template do not receive the local scope. For example: 
```
{% for item in foo %}
    {% include "other_template.j2" %}
{% endfor %
```
In the above example, other_template.j2 would not have the item variable defined.

##### STEPS TO REPRODUCE
```yaml
# Example Playbook
- hosts: localhost
  connection: local
  vars:
    foo:
      - bar
      - baz
  tasks:
    - name: Test Template
      template: src=parent.j2 dest=/tmp/template.out
```
```jinja2
# parent.j2
{% for item in foo %}
    {% include "subtemplate.j2" %}
{% endfor %}

```

```
#subtemplate.j2
{{ item }}
```

##### EXPECTED RESULTS
Expected the output of the following file:
```
bar
baz
```

##### ACTUAL RESULTS
```
TASK [Test Template] ************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'item' is undefined"}
```

I believe this is because of the Jinja2 Context changes mentioned [here](http://jinja.pocoo.org/docs/2.9/changelog/#version-2-9) in combination with Ansible overriding default Jinja2 functions. I wasn't able to track down the root cause in my limited testing.
