### ISSUE TITLE
Add support for subdirectories in `tasks_from` option of include_role

### ISSUE THREAD

**Issue by chesster88** [ansible/ansible#20077]
##### ISSUE TYPE

 - Feature Idea
 - ~~Bug Report~~

##### COMPONENT NAME
`include_role`

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 8d29406d74) last updated 2017/01/10 09:07:36 (GMT +000)
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Default configuration used.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

`include_role` does not support subdirectories in `tasks_from` option.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - include_role:
        name: "my_role"
        tasks_from: "subdir/tasks_file.yml"
```

##### EXPECTED RESULTS

Tasks from `tasks/subdir/tasks_file.yml` of the role `my_role` are executed.

##### ACTUAL RESULTS

Ansible fails to find the `tasks_file.yml` inside the role.

```
ERROR! Could not find specified file in role: tasks/tasks_file.yml
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/role/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
scheduled the PR that adds this feature for the next core IRC meeting https://github.com/ansible/community/issues/415#issuecomment-443074554

we will probably discuss if we want this feature at all.

**Comment by ephracis** [comment]
Did you guys decide anything?

**Comment by fuxx** [comment]
Doesnt look so :) A year later, any news?

**Comment by aitseitz** [comment]
vote +1 for that feature request.

Same issue still exists with **import_role** in ansible 2.9.5

Example:
```
- import_role:
        name: my_project_role
        tasks_from: "subfolder/run_health_check_tasks.yml"
```

ERROR! Could not find specified file in role: tasks/run_health_check_tasks.yml


Any reason why subfolders in tasks folder should be made?

**Comment by jpiron** [comment]
Hi !
Any update on this feature ?

**Comment by robmcgee-mag** [comment]
Unfortunately I'm stuck using Ansible 2.7 so I'll never get this feature backported (..unless?) but please add this to the current dev versions for the love of all that's sacred.

**Comment by Garreat** [comment]
It's ugly, but using a symlink works

**Comment by ephracis** [comment]
We are using this in 2.9:

```
---
- name: Create OpenRC file
  hosts: localhost
  tasks:

    - name: Apply role openstack/facts/os_environment
      include_role:
        name: openstack
        tasks_from: facts/os_environment

   # ... omitted ...
```

This will execute the tasks in `roles/openstack/tasks/facts/os_environment.yml`.

**Comment by mihai-satmarean** [comment]
> We are using this in 2.9:
> 
> ```
> ---
> - name: Create OpenRC file
>   hosts: localhost
>   tasks:
> 
>     - name: Apply role openstack/facts/os_environment
>       include_role:
>         name: openstack
>         tasks_from: facts/os_environment
> 
>    # ... omitted ...
> ```
> 
> This will execute the tasks in `roles/openstack/tasks/facts/os_environment.yml`.

it looks that it works in ansible 2.10.3 from commandline, but is not working with ansible core 2.12.0.dev0 in awx 19.2.2
it is a very useful feature for our complex resource management engine

**Comment by sivel** [comment]
I can confirm this works as expected now.

roles/baz/tasks/foo/bar.yml
```
- debug:
```

20077.yml
```
- hosts: localhost
  gather_facts: false
  tasks:
    - include_role:
        name: baz
        tasks_from: foo/bar.yml
```

```
$ ansible-playbook -v 20077.yml

PLAY [localhost] ****************************************************************************

TASK [include_role : baz] *******************************************************************

TASK [baz : debug] **************************************************************************
ok: [localhost] => {
    "msg": "Hello world!"
}

PLAY RECAP **********************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```
