### ISSUE TITLE
docker_container task fail on exit code

### ISSUE THREAD

**Issue by m64253** [ansible/ansible#20085]
Unless i'm missing something i expect that if I were to do something like the following the task would fail? But it does not 😟 

```yaml
  tasks:
      docker_container:
        name: "exit-test"
        image: "ubuntu:latest"
        command: "bash -c 'exit 123'"
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
2.1.1.0
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
  tasks:
      docker_container:
        name: "exit-test"
        image: "ubuntu:latest"
        command: "bash -c 'exit 123'"
```
##### EXPECTED RESULTS
Should fail the task

##### ACTUAL RESULTS
Task is ok.
