### ISSUE TITLE
vmware_guest state: poweredon/poweredoff/restarted doesn't do anything

### ISSUE THREAD

**Issue by 6mile** [ansible/ansible#20106]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Ansible built from git clone: git clone git://github.com/ansible/ansible.git --recursive
pyshere 0.1.7
pyvmomi 6.5
ESX 6.0.0

##### OS / ENVIRONMENT
CentOS Linux release 7.3.1611 (Core) patched and up to date

##### SUMMARY
Can't use the state: modifier to start/stop/restart a vm guest.  

##### STEPS TO REPRODUCE
Run the below playbook using poweredon, poweredoff, restarted for the state condition.

```yaml
---
- hosts: localhost
  gather_facts: False
  connection: local

  tasks:
  - vmware_guest:
     hostname: esx.server.local
     username: sysadmin
     password: p@ssword
     validate_certs: False
     name: test_vm
     state: poweredon
```

##### EXPECTED RESULTS
Restart, power on or power off vm guests

##### ACTUAL RESULTS

Nothing.  Regardless of existing state vs. required state you get a green successful status from Ansible.  So if the vm is off and you run the above playbook with state: poweredon the playbook does nothing, saying nothing needs to be changed and exits with a successful green status.

```
ASK [vmware_guest] *************************************************************************************************************************************************************************************************************************************************
task path: /opt/playbooks/vmware_poweron.yml:7
Using module file /opt/ansible-devel/lib/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1484087489.99-132513874338350 `" && echo ansible-tmp-1484087489.99-132513874338350="` echo ~/.ansible/tmp/ansible-tmp-1484087489.99-132513874338350 `" ) && sleep 0'
<localhost> PUT /tmp/tmpbXlyAu TO /root/.ansible/tmp/ansible-tmp-1484087489.99-132513874338350/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1484087489.99-132513874338350/ /root/.ansible/tmp/ansible-tmp-1484087489.99-132513874338350/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1484087489.99-132513874338350/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1484087489.99-132513874338350/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": null,
            "disk": [],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "10.0.0.10",
            "is_template": false,
            "name": "test_vm",
            "name_match": "first",
            "networks": {},
            "new_name": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_op": {},
            "state": "poweredon",
            "template_src": null,
            "username": "sysadmin",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        },
        "module_name": "vmware_guest"
    }
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by dagwieers** [comment]
That is strange indeed. I am using CentOS 7.3 as well, with pyvmomi 6.0.0 and ESXi 5.5.
I don't think that should matter though, but it works fine for me using the latest devel branch.

Are you using the absolute latest devel branch for the module ?
Because we have been heavily modifying the module. There were issues in the past with name-matching.

I would advise to use uuid if you want to be absolutely sure the right VM is selected.

The current module is slower, but there are PRs that speed it up by factor 20 (depending on the size of your environment). The module should take between 5 tot 10 seconds (also depending on the complexity of your environment).

**Comment by dagwieers** [comment]
Also try to simply use 'state: present' and see if you get any facts back.
If not, things are going wrong. If you do get facts, check if they are from the correct system ;-)

**Comment by ansibot** [comment]
cc @jctanner @nerzhul @dav1x
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by 6mile** [comment]
Yep, just did a git clone and same thing when using state: poweredon or poweredoff.  Ie., always get a success.

One thing I hadn't tried is a state: present as you requested.   I did and got this error:

```
TASK [vmware_guest] *************************************************************************************************************************************************************************************************************************************************
task path: /opt/playbooks/vmware_poweron.yml:7
Using module file /opt/ansible/lib/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1484097815.51-83976415139859 `" && echo ansible-tmp-1484097815.51-83976415139859="` echo ~/.ansible/tmp/ansible-tmp-1484097815.51-83976415139859 `" ) && sleep 0'
<localhost> PUT /tmp/tmpgo6OQ7 TO /root/.ansible/tmp/ansible-tmp-1484097815.51-83976415139859/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1484097815.51-83976415139859/ /root/.ansible/tmp/ansible-tmp-1484097815.51-83976415139859/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1484097815.51-83976415139859/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1484097815.51-83976415139859/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_RgqcVH/ansible_module_vmware_guest.py", line 1869, in <module>
    main()
  File "/tmp/ansible_RgqcVH/ansible_module_vmware_guest.py", line 1832, in main
    result = pyv.reconfigure_vm()
  File "/tmp/ansible_RgqcVH/ansible_module_vmware_guest.py", line 1422, in reconfigure_vm
    task = self.current_vm_obj.ReconfigVM_Task(spec=self.configspec)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1370, in InvokeMethod
    raise obj # pylint: disable-msg=E0702
pyVmomi.VmomiSupport.RestrictedVersion: (vim.fault.RestrictedVersion) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = 'Current license or ESXi version prohibits execution of the requested operation.',
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) []
}

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "vmware_guest"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_RgqcVH/ansible_module_vmware_guest.py\", line 1869, in <module>\n    main()\n  File \"/tmp/ansible_RgqcVH/ansible_module_vmware_guest.py\", line 1832, in main\n    result = pyv.reconfigure_vm()\n  File \"/tmp/ansible_RgqcVH/ansible_module_vmware_guest.py\", line 1422, in reconfigure_vm\n    task = self.current_vm_obj.ReconfigVM_Task(spec=self.configspec)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 580, in <lambda>\n    self.f(*(self.args + (obj,) + args), **kwargs)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py\", line 386, in _InvokeMethod\n    return self._stub.InvokeMethod(self, info, args)\n  File \"/usr/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py\", line 1370, in InvokeMethod\n    raise obj # pylint: disable-msg=E0702\npyVmomi.VmomiSupport.RestrictedVersion: (vim.fault.RestrictedVersion) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'Current license or ESXi version prohibits execution of the requested operation.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) []\n}\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
	to retry, use: --limit @/opt/playbooks/vmware_poweron.retry
```

**Comment by dagwieers** [comment]
Interesting, I surely wasn't expecting this:
**Current license or ESXi version prohibits execution of the requested operation.**

We can fix it so that this message is clearly shown ;-)

Can you try using `state: gatherfacts` instead ?
Just to see if simple facts-gathering works ?

**Comment by 6mile** [comment]
state: gatherfacts works.  I get the correct facts for the test vm.

**Comment by 6mile** [comment]
Adding uuid: <uuid> and using state: poweredon or poweredoff makes no difference.  Gives me the same thing as if I didn't give it the uuid.  ie., playbook is always successful, no change, status green.

**Comment by 6mile** [comment]
Dag, are you using ESX with vcenter or stand alone ESXi to test with?  I'm using stand alone ESXi with no vcenter server.

**Comment by dagwieers** [comment]
@eastside-hustle We are using vCenter. And I am pretty sure that's the problem. Even though it should not matter for simply powering off/on a system.

**Comment by 6mile** [comment]
Dag, in your testing environment can you point your playbooks at one of your ESX servers IP instead of the vcenter box and see if you get the same results?

**Comment by 6mile** [comment]
I've verified that the latest versions of vmware_guest (ansible 2.3.0 (devel 8495b6323a)) does not fix this issue.  Guessing its related to vcenter API versus the esx API set?  Some of the vmware_guest functions work well with esx (no vcenter) directly.  Others, like poweredon, poweredoff, snapshots and more, do NOT work without vcenter.  I haven't actually tested that last statement as I don't have vcenter in my environment but based on Dag's comments earlier that's my guess.

**Comment by stanrate** [comment]
My playbook uses vmware_guest to create a VM from a template. "state: poweredoff" is specified but the VM is created in a poweredon state and verbose task output contains "hw_power_status": "poweredOn"
This occurred in 2.2.0 and also occurs in 2.2.1 (installed from epel on rhel7 with latest patches).
I'm using pyvmomi 6.5 with esxi 6.5 in a vcenter environment.
Hopefully someone will fix the "state" processing issue in the near future so I can migrate playbooks that use vsphere_guest (unsupported but works ok) to vmware_guest (supported but does not work properly).

**Comment by dav1x** [comment]
@eastside-hustle : hmm, the datacenter param is now a required option. DC is a managed resource at the vcenter level. I'm certain this is related to the free version vs. vCenter. 

@stanrate This is due to the default setting of wait_for_ip_address. I just tested the following play and it works as expected:

```
- name: create vm
  hosts: localhost
  tasks:
    - vmware_guest:
        hostname: "10.x.x.25"
        username: "administrator@vsphere.local"
        password: "******"
        validate_certs: False
        name: "test08"                                                                                                                                                                                                      
        datacenter: "Boston"
        cluster: "devel"
        validate_certs: False
        template: "ose3-system-template"
        wait_for_ip_address: False
        state: poweredoff

```

**Comment by dav1x** [comment]
@eastside-hustle Ok, I dug into this more. For the time being try to include datacenter: ha-datacenter in your play. I'm going to submit a PR to add it as a default. (thats the default datacenter regardless if you have vcenter or not)

I installed a nested version of esxi 6.5 and created a VM on it. 

I was able to change power states without an issue.

```
- name: create vm
  hosts: localhost
  tasks:
    - vmware_guest:
        hostname: "10.x.x.165"
        username: "root"
        password: "****"
        validate_certs: False
        name: "testvm"
        validate_certs: False
        datacenter: "ha-datacenter"
        #wait_for_ip_address: False
        state: poweredon
```

In your play you specify sysadmin as the user, can you verify that user has proper rights to manipulate said VM?

**Comment by stanrate** [comment]
The playbook contains the following task:

    vmware_guest:
      hostname: "{{dict.vcenter_hostname}}"
      username: "{{vcenter_username}}"
      password: "{{vcenter_password}}"
      validate_certs: 'false'
      name: "{{newhost}}"
      template: "{{mytemplate}}"
      folder: 'xxxxxxxxxxx'
      state: poweredoff
      datacenter: "{{ dict.datacenter }}"
      esxi_hostname: "{{ dict.esxi_host }}"
    register: reg_newvm

When the playbook runs, a new VM is created but it is powered on. It should be powered off. The below old playbook was functionally similar but used vsphere_guest. The new VM was created correctly in poweredoff state.

    vsphere_guest:
      vcenter_hostname: "{{dict.vcenter_hostname}}"
      username: "{{vcenter_username}}"
      password: "{{vcenter_password}}"
      guest: "{{newhost}}"
      from_template: yes
      template_src: "{{mytemplate}}"
      resource_pool: /Resources
      cluster: "{{dict.cluster}}"
      power_on_after_clone: false

I'm planning to continue to use vsphere_guest until epel has an Ansible rpm that includes a fix for this issue.

**Comment by 6mile** [comment]
@dav1x I was still running ansible 2.3.0 (devel 8495b6323a) last updated 2017/01/23 07:50:32 (GMT +000) and that version gives me a green unchanged status pretty much no matter what "state:" I use.  So, I git cloned the latest version (ansible 2.3.0 (devel c86a17b7a0) last updated 2017/02/07 10:55:22 (GMT +000)) and its giving me an error.  Like you if I leave the datacenter out I get a missing datacenter error.  However, if I add the datacenter: "ha-datacenter" I get a different error:
sing module file /opt/ansible/lib/ansible/modules/cloud/vmware/vmware_guest.py

```
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1486465454.35-243270960298941 `" && echo ansible-tmp-1486465454.35-243270960298941="` echo /root/.ansible/tmp/ansible-tmp-1486465454.35-243270960298941 `" ) && sleep 0'
<localhost> PUT /tmp/tmpsQ2j3i TO /root/.ansible/tmp/ansible-tmp-1486465454.35-243270960298941/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1486465454.35-243270960298941/ /root/.ansible/tmp/ansible-tmp-1486465454.35-243270960298941/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1486465454.35-243270960298941/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1486465454.35-243270960298941/" > /dev/null 2>&1 && sleep 0'
 [WARNING]: Removed unexpected internal key in module return: _ansible_parsed = False

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_oYRy1i/ansible_module_vmware_guest.py", line 1317, in <module>
    main()
  File "/tmp/ansible_oYRy1i/ansible_module_vmware_guest.py", line 1294, in main
    tmp_result = pyv.set_powerstate(vm, module.params['state'], module.params['force'])
  File "/tmp/ansible_oYRy1i/ansible_module_vmware_guest.py", line 482, in set_powerstate
    facts = self.gather_facts(vm)
  File "/tmp/ansible_oYRy1i/ansible_module_vmware_guest.py", line 536, in gather_facts
    return gather_vm_facts(self.content, vm)
  File "/tmp/ansible_oYRy1i/ansible_modlib.zip/ansible/module_utils/vmware.py", line 225, in gather_vm_facts
NameError: global name 'iteritems' is not defined

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_oYRy1i/ansible_module_vmware_guest.py\", line 1317, in <module>\n    main()\n  File \"/tmp/ansible_oYRy1i/ansible_module_vmware_guest.py\", line 1294, in main\n    tmp_result = pyv.set_powerstate(vm, module.params['state'], module.params['force'])\n  File \"/tmp/ansible_oYRy1i/ansible_module_vmware_guest.py\", line 482, in set_powerstate\n    facts = self.gather_facts(vm)\n  File \"/tmp/ansible_oYRy1i/ansible_module_vmware_guest.py\", line 536, in gather_facts\n    return gather_vm_facts(self.content, vm)\n  File \"/tmp/ansible_oYRy1i/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 225, in gather_vm_facts\nNameError: global name 'iteritems' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

My playbook looks like this:
```yaml
---
- name: power on esx guest
  hosts: localhost
  gather_facts: False
  connection: local

  tasks:
  - vmware_guest:
     hostname: esx-standalone-server
     username: sysadmin
     password: P@ssword
     validate_certs: False
     datacenter: "ha-datacenter"
     name: testvm
     state: poweredon
```
Oh, and sysadmin is indeed an administrator on the ESX server.

**Comment by 6mile** [comment]
The only difference I can tell between my environment and your test one is that my ESX box is running version 6.0.0 3620759 while yours is running 6.5.  If we think it's worth it I can upgrade my test server to 6.5 and try it then.

**Comment by dav1x** [comment]
@stanrate I've indeed patched this issue and the fix should be merged soon.

@eastside-hustle 
I'll deploy a nested 6.0 and 5.5 vSphere deployment just for testing purposes. It will probably be handy to have them around. Are you running python 3.0? Itemitems() was removed from it. That's the only thing I can think of to address that issue.

**Comment by stanrate** [comment]
We maintain our RHEL systems using the latest RPMs from RHEL and EPEL repositories. The last "yum update" was done last week so our systems, including Python are "up to date" (we don't update Python from Python repositories). Ansible is running on one of our RHEL6 hosts - see below:

```
# rpm -q python
python-2.6.6-66.el6_8.x86_64
# python --version
Python 2.6.6
# rpm -q kernel
kernel-2.6.32-642.1.1.el6.x86_64
kernel-2.6.32-642.11.1.el6.x86_64
```

This would probably be typical for many commercial/government sites.

Our RHEL7 systems are running Python 2.7.5

Our existing playbook uses vsphere_guest and creates VMs from a clone in a poweredoff state but when I tried vmware_guest, it created VMs in a poweredon state and vmware_guest cannot currently be used to change the state. That's why I took an interest in this discussion. Eventually, when vmware_guest can create a VM in a poweredoff state or can change the state from poweredon to poweredoff, I'll be able to migrate from vsphere_guest  to vmware_guest. Thanks.

**Comment by nerzhul** [comment]
vmware_guest works well to change state i'm using it at work to spawn a VM, configure TFTP+DHCP and after boot the machine

**Comment by stanrate** [comment]
Nerzhul, vmware_guest does not work properly and I cannot use it to spawn a VM, configure DHCP and afterwards boot the machine. Perhaps your environment is different to mine and you are not running the latest RPMs from RHEL6 and EPEL repos like many commercial and government organizations.

**Comment by nerzhul** [comment]
@stanrate i'm a commercial organization and we are using Debian 8 with pyvmomi from pip

**Comment by dagwieers** [comment]
BTW I fixed the iteritems() problem here #21106

**Comment by stanrate** [comment]
Nerzhul, vmware_guest does not work properly and I cannot use it to spawn a VM, configure DHCP and afterwards boot the machine. Perhaps your environment is different to mine and you are not running the latest RPMs from RHEL and EPEL repos like most commercial and government organizations.

**Comment by 6mile** [comment]
@dav1x I'm using python 2.7.5.  I git cloned the latest Ansible today (ansible 2.3.0 (devel c00604210c) last updated 2017/02/07 22:55:37 (GMT +000)) and still the same error:

```
TASK [vmware_guest] *********************************************************************************************************************************************************************
task path: /opt/playbooks/vmware_poweron.yml:8
Using module file /opt/ansible/lib/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1486508412.53-170428327119163 `" && echo ansible-tmp-1486508412.53-170428327119163="` echo /root/.ansible/tmp/ansible-tmp-1486508412.53-170428327119163 `" ) && sleep 0'
<localhost> PUT /tmp/tmp4ucSTW TO /root/.ansible/tmp/ansible-tmp-1486508412.53-170428327119163/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1486508412.53-170428327119163/ /root/.ansible/tmp/ansible-tmp-1486508412.53-170428327119163/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1486508412.53-170428327119163/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1486508412.53-170428327119163/" > /dev/null 2>&1 && sleep 0'
 [WARNING]: Removed unexpected internal key in module return: _ansible_parsed = False

An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Y5ArfS/ansible_module_vmware_guest.py", line 1330, in <module>
    main()
  File "/tmp/ansible_Y5ArfS/ansible_module_vmware_guest.py", line 1307, in main
    tmp_result = pyv.set_powerstate(vm, module.params['state'], module.params['force'])
  File "/tmp/ansible_Y5ArfS/ansible_module_vmware_guest.py", line 482, in set_powerstate
    facts = self.gather_facts(vm)
  File "/tmp/ansible_Y5ArfS/ansible_module_vmware_guest.py", line 547, in gather_facts
    return gather_vm_facts(self.content, vm)
  File "/tmp/ansible_Y5ArfS/ansible_modlib.zip/ansible/module_utils/vmware.py", line 225, in gather_vm_facts
NameError: global name 'iteritems' is not defined

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Y5ArfS/ansible_module_vmware_guest.py\", line 1330, in <module>\n    main()\n  File \"/tmp/ansible_Y5ArfS/ansible_module_vmware_guest.py\", line 1307, in main\n    tmp_result = pyv.set_powerstate(vm, module.params['state'], module.params['force'])\n  File \"/tmp/ansible_Y5ArfS/ansible_module_vmware_guest.py\", line 482, in set_powerstate\n    facts = self.gather_facts(vm)\n  File \"/tmp/ansible_Y5ArfS/ansible_module_vmware_guest.py\", line 547, in gather_facts\n    return gather_vm_facts(self.content, vm)\n  File \"/tmp/ansible_Y5ArfS/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 225, in gather_vm_facts\nNameError: global name 'iteritems' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

```
Will wait for Dag's commit [#21106](https://github.com/ansible/ansible/pull/21106) to go live as I'm still seeing the 'iteritems' error.

**Comment by jctanner** [comment]
@eastside-hustle it is merged

**Comment by 6mile** [comment]
The latest commit fixes the "iteritems" error.  However, I'm back to my original problem which is regardless of what "state:" I use my playbook exits successfully with no changes.  Ie., if I try to power on a guest that is currently off nothing happens.   So, short story long, I'm back where I was when I put this ticket in.

**Comment by Trezamere** [comment]
I am also seeing this issue with the following task

```
    - name: VM is powered on
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter: "{{ datacenter }}"
        name: "{{ inventory_hostname }}"
        state: poweredon
        validate_certs: no
        wait_for_ip_address: false
```

Oddly enough it _does_ set the state correctly in my above task; however I am trying to configure the machine before booting it; so they are mutually exclusive.  Seems like there might be some state in the underlying module that depends on something else getting flipped for the _state_ poweredon/off to work properly.

I'm targeting VCenter 6, ESXi 6 host, and a non-default datacenter.  VM is Ubuntu Server 16.04; if that matters.

The reconfigure task for posterity:

```
    - name: VM is configured
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        annotation: "{{ notes | default('Created by Ansible') }}"
        datacenter: "{{ datacenter }}"
        disk:
          - size_gb: "{{ disk | default(20) }}"
            type: thick
            datastore: "{{ datastore }}"
        esxi_hostname: "{{ esxi_host }}"
        guest_id: "{{ osid }}"
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          scsi: paravirtual
        networks:
          - name: "{{ network | default('VM Network') }}"
            device_type: vmxnet3
            mac: "{{ mac | default(omit) }}"
        name: "{{ inventory_hostname }}"
        resource_pool: "{{ resource_pool | default(omit) }}"
        state: present
        validate_certs: no
        wait_for_ip_address: false

```

Using the vsphere_guest module as a workaround for now.

**Comment by ansibot** [comment]
cc @akasurde
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@eastside-hustle Could you please try on latest vmware_guest and let me know if it works for you ?

needs_info

**Comment by hadfiiw** [comment]
@Akasurde  I know I didn't start this and you didn't ask me but more then happy to help as I seem to be running into the same issue.

I have tried the following without luck.  I am using ansible 2.4.2.0, python 2.7.12, and pyvmomi 6.5.0.2017.5.post 1 against a 6.0U3b vCenter.  The target VM is an Ubuntu VM with Guest Managed VMware tools installed (version 2147483647)

`      vmware_guest:
        name: "{{ upgrade }}"
        hostname: '{{ deploy_vcenter }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_passwd }}'
        validate_certs: '{{ validate_certs }}'
        state: shutdownguest
`

Even though the VM is powered on, it says '"Changed": false" and never actually powers off the VM.  This is also true if I use poweredoff.

`ok: [localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
(rest snipped)`

But, if I use the old "vsphere_guest" with the "powered_off" state, then it works as expected (but is not ideal as I would like it to gracefully power down rather then force off).

`changed: [localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
(rest snipped)`

**Comment by hadfiiw** [comment]
@Akasurde I know I didn't start this and you didn't ask me but more then happy to help as I seem to be running into the same issue.

I have tried the following without luck. I am using ansible 2.4.2.0, python 2.7.12, and pyvmomi 6.5.0.2017.5.post 1 against a 6.0U3b vCenter. The target VM is an Ubuntu VM with Guest Managed VMware tools installed (version 2147483647)

 ```
vmware_guest:
  name: "{{ upgrade }}"
  hostname: "{{ deploy_vcenter }}"
  username: "{{ vcenter_username }}"
  password: "{{ vcenter_passwd }}"
  validate_certs: "{{ validate_certs }}"
  state: shutdownguest
```

Even though the VM is powered on, it says '"Changed": false" and never actually powers off the VM. This is also true if I use poweredoff.

```
ok: [localhost] => {
    "changed": false,
    "invocation": { "module_args": {
(rest snipped)
```
But, if I use the old "vsphere_guest" with the "powered_off" state, then it works as expected (but is not ideal as I would like it to gracefully power down rather then force off).

```
changed: [localhost] => {
    "changed": true,
    "invocation": { "module_args": {
(rest snipped)
```

If there is other info you need from me to help get this fixed, please let me know.

**Comment by hadfiiw** [comment]
@Akasurde

Actually, I just got this to work.  I went on to the next phase of my playbook (vmware_guest_snapshot) and noticed that the "folder" documentation for "vmware_guest_snapshot" says...

```
Destination folder, absolute or relative path to find an existing guest.
This is required if name is supplied.
The folder should include the datacenter. ESX's datacenter is ha-datacenter
```

...but for "vmware_guest" it says...

```
Destination folder, absolute or relative path to find an existing guest or create the new guest.
The folder should include the datacenter. ESX's datacenter is ha-datacenter
```

Just as a test, I added the folder option to "vmware_guest" and it is now working.

So it seems that "folder" is required for "vmware_guest"(?)

Another difference is when "folder" is not supplied for "vmware_guest", it just doesn't do anything and continues.  But if "folder" is not supplied for "vmware_guest_snapshot" it errors out that it cannot find a VM by that name.

**Comment by Akasurde** [comment]
@hadfiiw Thanks for providing information about this. Actually, `vmware_guest` module has default value of folder as `/vm` which make this parameter optional. There is a [PR](https://github.com/ansible/ansible/pull/33525) which makes folder as a required parameter, only if there are multiple VMs with same name (VMware doesn't restrict from creating VM with same name! ) and also improves the way the VM is discovered from given infrastructure.

**Comment by hadfiiw** [comment]
Sounds good to me.

Yes, /vm should work for anybody running it against an ESXi host or a vCenter without folders.  What was confusing me was that "vsphere_guest" and "vmware_guest" were acting differently with the same info passed to them.

Seems that "vsphere_guest" is walking the folder tree while "vmware_guest" is not.  Either way is totally fine once one understands what they are actually doing.  ;-)

So to answer your original question, the latest version of "vmware_guest" seems to be working - at least with my setup and the following play:

```
    - name: Power DOWN "{{ upgrade }}"
      vmware_guest:
        name: "{{ upgrade }}"
        folder: "{{ datacenter }}/vm/{{ vcenter_folder }}"
        hostname: "{{ deploy_vcenter }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_passwd }}"
        validate_certs: "{{ validate_certs }}"
        state: shutdownguest
```

One last thing about the folder (for others who find this), the /vm part of the path is static and needs to be there.  In my actual VM and Templates view, it is just the "vcenter_folder" under the "datacenter".

Thanks!
