### ISSUE TITLE
known_hosts module reporting 'changed' incorrectly

### ISSUE THREAD

**Issue by Yannik** [ansible/ansible#20126]
_From @Yannik on March 29, 2016 13:24_

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

known_hosts
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 14.04.4 LTS
##### SUMMARY

The known_hosts module reports keys as changed even though they have not changed.
The reason for this is, that a known_hosts entry may include a comment, but this comment is not shown by `ssh-keygen -F <hostname> -f <known_hosts_file>` and therefore the check whether the key already exists fails. 
##### STEPS TO REPRODUCE

test.yml:

```

---
- hosts: all 
  tasks:
    - known_hosts:
        path: /tmp/known_hosts
        name: example.org
        key: "example.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLSqkXLnT85znqek/60y+FnuCYzW2egPfZF2hRm8uND1gtTsn4kVM9ZfN7D3mrM8fgEvLWi5NnMbbylQ78AhqDk= COMMENT"
```

Run as `ansible-playbook -i 'localhost,' -c local test.yml`

`/tmp/known_hosts` will contain

```
example.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLSqkXLnT85znqek/60y+FnuCYzW2egPfZF2hRm8uND1gtTsn4kVM9ZfN7D3mrM8fgEvLWi5NnMbbylQ78AhqDk= COMMENT
```

which is a correct known_hosts entry according to the section [SSH_KNOWN_HOSTS FILE FORMAT](http://manpages.ubuntu.com/manpages/trusty/en/man8/sshd.8.html#contenttoc7) of the sshd manpages:

> Each line in these files contains the following fields: markers
>      (optional), hostnames, bits, exponent, modulus, comment.  The fields are
>      separated by spaces.

`ssh-keygen -F example.org -f /tmp/known_hosts`, which is used by the known_hosts module to check whether a key already exists, returns

```
# Host example.org found: line 1 type ECDSA
example.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBLSqkXLnT85znqek/60y+FnuCYzW2egPfZF2hRm8uND1gtTsn4kVM9ZfN7D3mrM8fgEvLWi5NnMbbylQ78AhqDk=
```

on Ubuntu 14.04.4 LTS. The comment is, as you can see, not included.

Therefore the check (see https://github.com/ansible/ansible-modules-extras/blob/devel/system/known_hosts.py#L232) whether the key exists fails and known_hosts always reports the key as changed on subsequent runs of the playbook.
##### EXPECTED RESULTS

known_hosts should not report the task as changed.
##### ACTUAL RESULTS

known_hosts does report the task as changed.

_Copied from original issue: ansible/ansible-modules-extras#1924_
