### ISSUE TITLE
ec2_group rules_egress

### ISSUE THREAD

**Issue by jayenashar** [ansible/ansible#20120]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME

ec2_group task
rules_egress option parameter

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/jayen/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
[ssh_connection]
control_path = /tmp/control_%%l_%%h_%%p_%%r
```

##### OS / ENVIRONMENT

debian jessie managing EC2

##### SUMMARY

Docs say: `If none are supplied, a default all-out rule is assumed.` but I didn't supply `rules_egress` as an option parameter and ansible did not create the default all-out rule.  More info here: https://forums.aws.amazon.com/thread.jspa?threadID=246610

Seems to be the opposite of https://github.com/ansible/ansible/issues/19226

##### STEPS TO REPRODUCE

```yaml
- name: ec2_group default
  ec2_group:
    name: default
    description: for all EC2 systems to contact each other
    region: "{{ aws_region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    rules:
      - proto: all
        # the containing group name may be specified here
        group_name: default
```

##### EXPECTED RESULTS

a default all-out rule is created

##### ACTUAL RESULTS

a default all-out rule was not created

```
AWS_ACCESS_KEY_ID={{ ec2_access_key }} AWS_SECRET_ACCESS_KEY={{ ec2_secret_key }} ansible-playbook --inventory inventory ec2.yaml --vault-password-file=.password
```
