### ISSUE TITLE
Ansible 2.2 Fetch Module Broken

### ISSUE THREAD

**Issue by ifelsefi** [ansible/ansible#20142]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Fetch Module

##### ANSIBLE VERSION

```
douglas@quackmaster[~/repos/ansible/playbooks]$ ansible --version
ansible 2.2.0.0
  config file = /home/douglas/repos/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Does not fetch

This used to work 

##### STEPS TO REPRODUCE

roles/common/templates/em1.j2:

DEVICE=em1
BOOTPROTO=static
IPV6INIT=no
MTU=1500
IPADDR={{ lookup('dig', '{{ inventory_hostname }}')}}
NETMASK=255.255.0.0
GATEWAY=10.0.0.52
DEFROUTE=yes
NM_CONTROLLED=no
ONBOOT=yes
TYPE=Ethernet
PEERDNS=no

```yaml

- name: template em1
  tags: ifcfg, em1
  template: src=em1.j2 dest=/tmp/ifcfg-em1
  delegate_to: descartes
  when: em1 is defined

- name: copy em1 file
  tags: ifcfg, em1
  fetch: src=/tmp/ifcfg-em1 dest=/tmp flat=yes
  delegate_to: descartes
  when: em1 is defined

- name: copy em1 script
  tags: ifcfg, em1
  copy: src=/tmp/ifcfg-em1 dest=/etc/sysconfig/network-scripts mode=0644 owner=root group=root
  when: em1 is defined

```

##### ACTUAL RESULTS

TASK [common : template em1] **************************************************

ok: [polaris.pbtech -> descartes] => {
    "changed": false, 
    "diff": {
        "after": {
            "path": "/tmp/ifcfg-em1"
        }, 
        "before": {
            "path": "/tmp/ifcfg-em1"
        }
    }, 
    "gid": 0, 
    "group": "root", 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "delimiter": null, 
            "dest": "/tmp/ifcfg-em1", 
            "diff_peek": null, 
            "directory_mode": null, 
            "follow": true, 
            "force": false, 
            "group": null, 
            "mode": null, 
            "original_basename": "em1.j2", 
            "owner": null, 
            "path": "/tmp/ifcfg-em1", 
            "recurse": false, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": null, 
            "unsafe_writes": null, 
            "validate": null
        }
    }, 
    "mode": "0644", 
    "owner": "root", 
    "path": "/tmp/ifcfg-em1", 
    "size": 171, 
    "state": "file", 
    "uid": 0
}

TASK [common : copy em1 file] **************************************************
task path: /home/douglas/repos/ansible/playbooks/roles/common/tasks/mgmtconf.yml:85
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/files/stat.py
<descartes> ESTABLISH SSH CONNECTION FOR USER: root
<descartes> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=20 -o ControlPath=/home/douglas/.ansible/cp/ansible-ssh-%h-%p-%r descartes '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<descartes> FETCH /tmp/ifcfg-em1 TO /tmp
<descartes> SSH: EXEC scp -o ControlMaster=auto -o ControlPersist=60s -o Port=22 -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=20 -o ControlPath=/home/douglas/.ansible/cp/ansible-ssh-%h-%p-%r /tmp/ifcfg-em1 '[descartes]:/tmp'
fatal: [polaris.pbtech]: FAILED! => {
    "failed": true, 
    "msg": "failed to transfer file to /tmp:\n\n/tmp/ifcfg-em1: No such file or directory\n"
}
        to retry, use: --limit @/home/douglas/repos/ansible/playbooks/common.retry

```

```
