### ISSUE TITLE
Copy module with base64-encoded binary file adds extra character

### ISSUE THREAD

**Issue by ojkastl** [ansible/ansible#20150]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy module

##### ANSIBLE VERSION
Happens with both 2.2.0 and 2.2.1rc3

```
ansible 2.2.0.0
  config file = /Users/xyz/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Nothing relevant: inventory, control_path, retry_files_enabled, ...

##### OS / ENVIRONMENT
Running ansible on OSX 10.12 and openSUSE Tumbleweed

##### SUMMARY
I generate a base64-encoded string from a file binary_file via
`cat binary_file | base64` (or gbase64 in my case)
I put this string into a variable and use the copy module with content="..." to create a file. But the file differs from the original file, there is one additional character in the output.

Not sure if this is similar to  #5262...

##### STEPS TO REPRODUCE
Create the binary file by e.g.
`echo sxZARwIVokeqOMGPygc1S20CaGPiKDRGRzg0oSVGmCF2oXHua+9fVhriUQRd8vkmvpHoBmSsI6Y= | gbase64 -d >binary_file.2`
Try this playbook.

```yaml
- hosts: localhost
  vars:
    string_in_base64: sxZARwIVokeqOMGPygc1S20CaGPiKDRGRzg0oSVGmCF2oXHua+9fVhriUQRd8vkmvpHoBmSsI6Y=

  tasks:
    - copy:
        content: '{{ string_in_base64 | b64decode }}'
        dest: "/some/path/binary_file.ansible"
```
Compare the results with any checksum:
`md5sum binary_file*`

##### EXPECTED RESULTS
The created file and the original file should be identical.

##### ACTUAL RESULTS
The file is created and the content is almost right:

`cat binary_file; echo ""; cat binary_file.ansible; echo ""`
```
�@G�G�8��5Kmhc�(4FG84�%F�!v�q�k�_V�Q]��&���d�#�
�@G�G�8���5Kmhc�(4FG84�%F�!v�q�k�_V�Q]��&���d�#�
```
The second file actually has an additional character (at column 9).
