### ISSUE TITLE
Role dependency is run multiple times

### ISSUE THREAD

**Issue by paddatrapper** [ansible/ansible#20169]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Role dependencies

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/kyle/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
````
[defaults]
inventory = ~/.ansible/hosts
ansible_managed = Managed by ansible. All changes will be overwritten
ssh_args = -o ControlMaster=auto -o ControlPersist=60s StrictHostKeyChecking=no
ask_vault_pass = yes
retry_files_enabled = False
````

##### OS / ENVIRONMENT
Debian Stretch and Debian Sid managing Debian Stretch

##### SUMMARY
I have roles: `example_1`, `example_2`, `dependency_1` and `dependency_2`. `dependency_1` is set to be duplicated (`allow_duplicates: yes`) and `dependency_2` also depends on `dependency_1`.

When a playbook host has the roles `example_1` and `example_2` the following is executed:

1. `dependency_1` (for `dependency_2`)
2. `dependency_2` (for `example_1`)
3. `dependency_1` (for `example_1`)
4. `example_1`
5. `dependency_1` (for `dependency_2`)
6. `dependency_1` (for `example_2`)
7. `example_2`

Step 5 is redundant and shouldn't run, as `dependency_2` is only run once and its dependencies should only be run once.

##### STEPS TO REPRODUCE

```yaml
./site.yml
---
- hosts: example.com
  remote_user: user
  roles:
      - example_1
      - example_2
````
````yaml
./roles/example_{1,2}/meta/main.yml
---
dependencies:
    - role: dependency_2
    - role: dependency_1
````
````yaml
./roles/dependency_1/meta/main.yml
---
allow_duplicates: yes
````
````yaml
./roles/dependency_2/meta/main.yml
---
dependencies:
    - role: dependency_1
````

````yaml
./roles/{example_1,example_2,dependency_1,dependency_2}/tasks/main.yml
---
- name: display role
  debug:
    msg: this is role {{ role_path }}
````

##### EXPECTED RESULTS
````
$ ansible-playbook site.yml

PLAY [example.com] ***************************************************

TASK [setup] *******************************************************************
ok: [example.com]

TASK [dependency_1 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_1"
}

TASK [dependency_2 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_2"
}

TASK [dependency_1 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_1"
}

TASK [example_1 : display role] ************************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/example_1"
}

TASK [dependency_1 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_1"
}

TASK [example_2 : display role] ************************************************
ok: [example.com] => {
    "msg": "this is role /home/kyle/user/ansible/roles/example_2"
}

PLAY RECAP *********************************************************************
example.com      : ok=8    changed=0    unreachable=0    failed=0
````

##### ACTUAL RESULTS
````
$ ansible-playbook site.yml

PLAY [example.com] ***************************************************

TASK [setup] *******************************************************************
ok: [example.com]

TASK [dependency_1 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_1"
}

TASK [dependency_2 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_2"
}

TASK [dependency_1 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_1"
}

TASK [example_1 : display role] ************************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/example_1"
}

TASK [dependency_1 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_1"
}

TASK [dependency_1 : display role] *********************************************
ok: [example.com] => {
    "msg": "this is role /home/user/ansible/roles/dependency_1"
}

TASK [example_2 : display role] ************************************************
ok: [example.com] => {
    "msg": "this is role /home/kyle/user/ansible/roles/example_2"
}

PLAY RECAP *********************************************************************
example.com      : ok=8    changed=0    unreachable=0    failed=0
````

**Comment by vbotka** [comment]
Dependent role (vbotka.freebsd-mailserver) is repeated [1] if ansible-playbook (2.3.1.0) [2] is invoked with option "-t config_potfix_main_cf_relayhost" and there is only single occurence of this tag in the roles. With 2 occurences of this tag [3] the dependent role is run only once [4]. Controller is Ubuntu 17.10 and host is FreeBSD 10.3.

[1]
```
PLAY [mail.example.com] **********************************************************************************************                                               
                                                                                                                                                                     
TASK [Gathering Facts] ********************************************************************************************                                                  
ok: [mail.example.com]                                                                                                                                               
                                                                                                                                                                     
TASK [vbotka.freebsd-mailserver : Configure relayhost in /usr/local/etc/postfix/main.cf] **************************                                                  
skipping: [mail.example.com]                                                                                                                                         
                                                                                                                                                                     
TASK [vbotka.freebsd-mailserver : Configure relayhost in /usr/local/etc/postfix/main.cf] **************************                                                  
skipping: [mail.example.com]                                                                                                                                         
                                                                                                                                                                     
TASK [vbotka.freebsd-mailserver : Configure relayhost in /usr/local/etc/postfix/main.cf] **************************                                                  
skipping: [mail.example.com]                                                                                                                                         
                                                                                                                                                                     
PLAY RECAP ********************************************************************************************************                                                  
mail.example.com              : ok=1    changed=0    unreachable=0    failed=0                                                                                       

```

[2]
```
- hosts: mail.example.com                                                                                                                                            
  become: yes                                                                                                                                                        
  become_method: sudo                                                                                                                                                
  vars_files:                                                                                                                                                        
    - ~/.ansible/vars/example.yml                                                                                                                                      
  roles:                                                                                                                                                             
    - vbotka.freebsd-mailserver-sieve                                                                                                                                
    - vbotka.freebsd-mailserver-spamassassin                                                                                                                         
    - vbotka.freebsd-mailserver-roundcube                                                                                                                            

```
[3]    role vbotka.freebsd-mailserver
```
- debug:
    msg: "relayhost: {{ postfix_main_cf_relayhost }}"
  tags: config_potfix_main_cf_relayhost
                                                                                                      
- name: Configure relayhost in {{ postfix_main_cf }}                                                                                                                 
  lineinfile: >                                                                                                                                                      
    dest="{{ postfix_main_cf }}"                                                                                                                                     
    regexp="^relayhost"                                                                                                                                              
    line="relayhost = {{ postfix_main_cf_relayhost }}"                                                                                                               
    backup="yes"                                                                                                                                                     
  when: postfix_main_cf_relayhost != ""                                                                                                                              
  notify: reload postfix                                                                                                                                             
  tags: config_potfix_main_cf_relayhost                                                                                                                              

```

[4]
```
PLAY [mail.example.com] **********************************************************************************************

TASK [Gathering Facts] ********************************************************************************************
ok: [mail.example.com]

TASK [vbotka.freebsd-mailserver : debug] **************************************************************************
ok: [mail.example.com] => {
    "msg": "relayhost: "
}

TASK [vbotka.freebsd-mailserver : Configure relayhost in /usr/local/etc/postfix/main.cf] **************************
skipping: [mail.example.com]

PLAY RECAP ********************************************************************************************************
mail.example.com              : ok=2    changed=0    unreachable=0    failed=0   

```
