### ISSUE TITLE
EC2_EIP module: on reuse_existing_ip_allowed: True trying to associate the same IP for all hosts in group

### ISSUE THREAD

**Issue by morokin** [ansible/ansible#20174]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module: ec2_eip

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY
On reuse_existing_ip_allowed: True 

Same free EIP associating with all hosts in the group/play, all relevant tasks has status "changed" with no errors, but IP became associated only with the first host, rest of the hosts goes without EIP silently.

On  reuse_existing_ip_allowed: false
Everything works as expected

```yaml
- name: Associate elastic IP
  local_action:
    module: ec2_eip
    profile: "{{ profile }}"
    region: "{{ region }}"
    in_vpc: True
    release_on_disassociation: True
    reuse_existing_ip_allowed: True
    device_id: "{{ hostvars[inventory_hostname]['instance_id'] }}"
    state: present
  register: eip_debug

- debug: var=eip_debug
```

##### EXPECTED RESULTS
Elastic IP addresses became associated with all hosts in play scope, existing free EIPs associated first (reused), than new allocated.

##### ACTUAL RESULTS
One existing free EIP associated with all hosts in play scope, no new IPs allocated, task has status changed (not failed), all hosts except random one has no EIP at all.

```
TASK [add-eip : Associate elastic IP] ******************************************
changed: [ANSIBLE-02 -> localhost]
changed: [ANSIBLE-01 -> localhost]

TASK [add-eip : debug] *********************************************************
ok: [ANSIBLE-01] => {
    "eip_debug": {
        "allocation_id": "eipalloc-87146abd", 
        "changed": true, 
        "public_ip": "52.8.209.170"
    }
}
ok: [ANSIBLE-02] => {
    "eip_debug": {
        "allocation_id": "eipalloc-87146abd", 
        "changed": true, 
        "public_ip": "52.8.209.170"
    }
}
```
