### ISSUE TITLE
Module 'user' adds accounts to system when using 'expires=' if the user does not exist

### ISSUE THREAD

**Issue by ronator** [ansible/ansible#20172]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-modules-core/system/user.py

##### ANSIBLE VERSION
```
ansible 2.1.1.0
```
##### SUMMARY
The module "user" is not really behaving idempotent. If I want to expire user accounts _that do not exist_  (anymore), they actually will be created by the module. The accounts will be locked and expired, but they are also created before which is not expected nor intended. I cannot use state=absent because this would remove user data.
If you have 3 user on 10 server and ONE special user only on ONE servers, and you want to disable them all on all servers, the problem is, that the special user gets created on the other 9 servers. That's not what you want to achieve.

##### STEPS TO REPRODUCE
Try to expire a user that is non-existent and should therefore be skipped:

```yaml
---
- name: Test user module
  hosts: all
  become: yes
  vars_files:
    - /etc/ansible/secrets.yml
  tasks:
    - name: Try to expire non-existent user account
      user: name={{ item.name }} expires=1

      with_items:
        - { name: 'user1' }
```

##### EXPECTED RESULTS
If the user does not exist, I expect it to do nothing in this context.

##### ACTUAL RESULTS
The user account is added to the system, locked and expired - but it creates the account beforehand. This creates an unneccessarily lot of users on servers on which never existed there before.
