### ISSUE TITLE
Network modules: eos_config, ios_config,  nxos_config (and possibly others)

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#20171]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
junos_config
eos_config

##### ANSIBLE VERSION

```
ansible 2.3.0 (network-aws 1045e3a5a9) last updated 2017/01/11 19:42:39 (GMT +100)
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Ensure their is no ansible.cfg present

##### SUMMARY
It appears that if `self.fail_json` is called by a network module that the task will hang.

##### STEPS TO REPRODUCE

Ensure you have no `ansible.cfg` present, e.g. you are using the defaults

````
cd ansible/test/integration
ANSIBLE_ROLES_PATH=targets ansible-playbook -vvvv -i inventory.network junos.yaml  -u ansible --private-key=~/.ssh/yourkey.pem
```

Ignore the error regarding `"update is merge but the following are missing: src`. That will be fixed by a follow up PR.

The issue is that Ansible stops any further output after the `self.fail_json`

The playbook that hangs is `test/integration/targets/junos_config/tests/netconf/src_basic.yaml:4`

```yaml
- name: setup
  junos_config:
    lines:
      - set system host-name {{ inventory_hostname_short }}
      - delete interfaces lo0
    provider: "{{ netconf }}"
```


##### EXPECTED RESULTS

##### ACTUAL RESULTS
```

```

**Comment by gundalow** [comment]
Might not just be limited to `fail_json`
`ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvv -i inventory.network eos.yaml`

```yaml
  
  - name: setup
    eos_config:
      commands:
        - no description
        - no shutdown
      parents:
        - interface Ethernet5
      match: none
      provider: "{{ cli }}"
```

```
TASK [eos_config : setup] ************************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/eos_config/tests/cli/src_basic.yaml:4

{"invocation": {"module_args": {"authorize": true, "force": false, "replace": "line", "use_ssl": true, "port": null, "transport": "cli", "before": null, "auth_pass": null, "parents": ["interface Ethernet5"], "provider": {"username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "authorize": true, "host": "veos01", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "transport": "cli"}, "save": false, "config": null, "match": "none", "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "timeout": 10, "after": null, "host": "veos01", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "src": null, "commands": ["no description", "no shutdown"], "ssh_keyfile": null, "backup": false, "lines": ["no description", "no shutdown"], "defaults": false, "validate_certs": true}}, "diff": {"prepared": "--- system:/running-config\n+++ session:/ansible_1484222388-session-config\n@@ -53,7 +53,6 @@\n    shutdown\n !\n interface Ethernet5\n-   description this is a test\n    no switchport\n    vrf forwarding test\n !\n"}, "changed": true, "updates": ["interface Ethernet5", "no description", "no shutdown"], "warnings": []}

```
The hangs
