### ISSUE TITLE
ansible 2.3 ec2_ami_copy module shows error: boto3 required for this module

### ISSUE THREAD

**Issue by xuchen81** [ansible/ansible#20238]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
ec2_ami_copy
```
##### ANSIBLE VERSION

```
2.3
```

##### OS / ENVIRONMENT

```
OS I am Ansible from: ubuntu
OS I am managing: ubuntu
```
##### STEPS TO REPRODUCE

```yaml
- name: Copy AMI to {{ fallback_region }}
  ec2_ami_copy:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    source_region: "{{ region }}"
    region: "{{ fallback_region }}"
    source_image_id: "{{ image_id }}"
    name: test
    description: test
  register: result

```

##### ACTUAL RESULTS

```
TASK [create_snapshot : Copy AMI to us-east-1] *********************************
fatal: [xx.xx.xx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "boto3 required for this module"}
```
