### ISSUE TITLE
os_security_group_rule is not idempotent for a /32  if /32 is omitted

### ISSUE THREAD

**Issue by donovan** [ansible/ansible#20251]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
os_security_group_rule

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
```

##### SUMMARY
When creating a security group rule it is possible to provide an IP without a CIDR slash for remote_ip_prefix. When doing this the IP is evaluated as a /32. This will then allow the successful creation of a rule on first run (changed) and throw an error on second run.

The docs for remote_ip_prefix state: 'Source IP address(es) in CIDR notation (exclusive with remote_group)'. There are two obvious approaches to address this bug:

1. Fail immediately if the IP provided is not in CIDR notation.
2. Ensure the task does not fail when updating (state is ok)

##### STEPS TO REPRODUCE

```yaml
#!/usr/bin/env ansible-playbook
---

# This playbook assumes an openstack rc file has been sourced

- name: Demonstrate bug in os_security_group_rule
  hosts: localhost
  vars:
    remote_cidr_one: 1.2.3.4/32
    remote_cidr_two: 5.6.7.8
    security_group_name: bug-test-sg

  tasks:
    - name: Connect to OpenStack Cloud
      os_auth:

    - name: "Create the {{ security_group_name }} security group"
      os_security_group:
        state: present
        name: "{{ security_group_name }}"
        description: Network access for the example instance.

    - name: Create a security group rule using remote_cidr_one
      os_security_group_rule:
        state: present
        security_group: "{{ security_group_name }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: "{{ remote_cidr_one }}"

    - name: Create a security group rule using remote_cidr_two
      os_security_group_rule:
        state: present
        security_group: "{{ security_group_name }}"
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: "{{ remote_cidr_two }}"
```
```yaml
$ ansible-playbook sg-bug.yaml

PLAY [Demonstrate bug in os_security_group_rule] *******************************

TASK [setup] *******************************************************************
Saturday 14 January 2017  12:55:48 +1300 (0:00:00.015)       0:00:00.015 ****** 
ok: [localhost]

TASK [Connect to OpenStack Cloud] **********************************************
Saturday 14 January 2017  12:55:50 +1300 (0:00:01.730)       0:00:01.745 ****** 
ok: [localhost]

TASK [Create the bug-test-sg security group] ***********************************
Saturday 14 January 2017  12:55:51 +1300 (0:00:00.967)       0:00:02.712 ****** 
changed: [localhost]

TASK [Create a security group rule using remote_cidr_one] **********************
Saturday 14 January 2017  12:55:52 +1300 (0:00:01.889)       0:00:04.601 ****** 
changed: [localhost]

TASK [Create a security group rule using remote_cidr_two] **********************
Saturday 14 January 2017  12:55:54 +1300 (0:00:01.871)       0:00:06.473 ****** 
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=0   

Saturday 14 January 2017  12:55:56 +1300 (0:00:01.606)       0:00:08.079 ****** 
=============================================================================== 
Create the bug-test-sg security group ----------------------------------- 1.89s
Create a security group rule using remote_cidr_one ---------------------- 1.87s
setup ------------------------------------------------------------------- 1.73s
Create a security group rule using remote_cidr_two ---------------------- 1.61s
Connect to OpenStack Cloud ---------------------------------------------- 0.97s
```
```yaml
$ ansible-playbook sg-bug.yaml

PLAY [Demonstrate bug in os_security_group_rule] *******************************

TASK [setup] *******************************************************************
Saturday 14 January 2017  12:55:59 +1300 (0:00:00.014)       0:00:00.014 ****** 
ok: [localhost]

TASK [Connect to OpenStack Cloud] **********************************************
Saturday 14 January 2017  12:56:01 +1300 (0:00:01.737)       0:00:01.752 ****** 
ok: [localhost]

TASK [Create the bug-test-sg security group] ***********************************
Saturday 14 January 2017  12:56:02 +1300 (0:00:01.017)       0:00:02.769 ****** 
ok: [localhost]

TASK [Create a security group rule using remote_cidr_one] **********************
Saturday 14 January 2017  12:56:03 +1300 (0:00:01.329)       0:00:04.099 ****** 
ok: [localhost]

TASK [Create a security group rule using remote_cidr_two] **********************
Saturday 14 January 2017  12:56:04 +1300 (0:00:01.436)       0:00:05.536 ****** 
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating security group rule: Security group rule already exists. Rule id is 17c50b75-4a65-4558-9557-eb97cc48bfa4.\nNeutron server returns request_ids: ['req-9a55eb64-edba-40c1-b8de-49759545599c']"}
	to retry, use: --limit @/home/don/src/catalystcloud-ansible/example-playbooks/kubernetes-with-kubeadm/sg-bug.retry

PLAY RECAP *********************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

Saturday 14 January 2017  12:56:07 +1300 (0:00:02.116)       0:00:07.652 ****** 
=============================================================================== 
Create a security group rule using remote_cidr_two ---------------------- 2.12s
setup ------------------------------------------------------------------- 1.74s
Create a security group rule using remote_cidr_one ---------------------- 1.44s
Create the bug-test-sg security group ----------------------------------- 1.33s
Connect to OpenStack Cloud ---------------------------------------------- 1.02s
```

##### EXPECTED RESULTS

Task "Create a security group rule using remote_cidr_two" succeeds with ok: [localhost]

##### ACTUAL RESULTS

Task "Create a security group rule using remote_cidr_two" fails with:

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating security group rule: Security group rule already exists. Rule id is 17c50b75-4a65-4558-9557-eb97cc48bfa4.\nNeutron server returns request_ids: ['req-9a55eb64-edba-40c1-b8de-49759545599c']"}
	to retry, use: --limit @/home/don/src/catalystcloud-ansible/example-playbooks/kubernetes-with-kubeadm/sg-bug.retry

```

```
