### ISSUE TITLE
sysctl module error

### ISSUE THREAD

**Issue by ugugilla** [ansible/ansible#20263]
sysctl module error 

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

"/tmp/ansible_MuXmOF/ansible_module_sysctl.py

##### ANSIBLE VERSION
```
-bash-4.1$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
-bash-4.1$
```

##### OS / ENVIRONMENT

RHEL 6.7

##### SUMMARY

The simple play of setting a sysctl parameter is not working

```
  - name: Restrict core dumps  via sysctl
    sysctl:
      name: fs.suid_dumpable
      value: 0
      state: present
      ignoreerrors: yes
```

##### STEPS TO REPRODUCE

```

  - name: Restrict core dumps  via sysctl
    sysctl:
      name: fs.suid_dumpable
      value: 0
      state: present
      ignoreerrors: yes


```

##### ACTUAL RESULTS

```

```
