### ISSUE TITLE
vars_files doesn't play well with environment variables

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#2027]
```
ls -l /Users/jmartin/work/ansible/vars/global/aws_benchmark.yaml 
-rw-r--r--  1 jmartin  staff  395 Feb  8 11:46 /Users/jmartin/work/ansible/vars/global/aws_benchmark.yaml

export ANSIBLE_VARS=/Users/jmartin/work/ansible/vars
```

playbook runs:

```
ansible-playbook -vvv node-provisioner/aws/cloudformation/provision_stack.yaml --extra-vars="siteconfig=aws_benchmark" -i ./ec2.py 
```

and errors:

```
ERROR: file not found: node-provisioner/aws/cloudformation/['/Users/jmartin/work/ansible/vars']/global/aws_benchmark.yaml
```

This is the playbook snippet

```

---
- include: provision_mgr.yaml
- hosts: localhost
  connection: local
  vars_files:
    - "$ENV(ANSIBLE_VARS)/global/${siteconfig}.yaml"
    - "$ENV(ANSIBLE_VARS)/${siteconfig}/cfn.yaml"
    - "vars/default.yaml"
```

If I change 

```
"$ENV(ANSIBLE_VARS)/global/${siteconfig}.yaml"
```

 to 

```
"/$ENV(ANSIBLE_VARS)/global/${siteconfig}.yaml"  
```

the following error occurs:

```
ERROR: file not found: /['/Users/jmartin/work/ansible/vars']/global/aws_benchmark.yaml
```

So I think if there is not a '/' character at the beginning of the var_file path, it's assumed to be relative.  And since the $ENV(ANSIBLE_VAR) isn't returning a plain string, it's making it relative to the playbook.
