### ISSUE TITLE
win_regedit: Idempotency issue

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#20283]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_regedit

##### ANSIBLE VERSION

v2.3

##### OS / ENVIRONMENT

Windows 10

##### SUMMARY

When I run the following task:
```yaml
  - name: Enable VideoLan Client for ISO images
    win_regedit:
      key: 'HKCR:\Windows.IsoFile\shell\Open\command'
      value: '(default)'
      data: '"%ProgramFiles%\VideoLAN\VLC\vlc.exe" --started-from-file "%1"'
      datatype: 'expandstring'
```

It reports a change the first time:
```
TASK [Enable VideoLan Client for ISO images] ***********************************************************
changed: [computer61] => (item={u'type': u'expandstring', u'data': u'"%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe" --started-from-file "%1"', u'value': u'(default)', u'key': u'HKCR:\\Windows.IsoFile\\shell\\Open\\command'}) => {"changed": true, "data_changed": false, "data_type_changed": false, "item": {"data": "\"%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe\" --started-from-file \"%1\"", "key": "HKCR:\\Windows.IsoFile\\shell\\Open\\command", "type": "expandstring", "value": "(default)"}}
```

And an error every subsequent run:
```
TASK [Enable VideoLan Client for ISO images] ***********************************************************
failed: [computer61] (item={u'type': u'expandstring', u'data': u'"%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe" --started-from-file "%1"', u'value': u'(default)', u'key': u'HKCR:\\Windows.IsoFile\\shell\\Open\\command'}) => {"changed": false, "data_changed": false, "data_type_changed": false, "failed": true, "item": {"data": "\"%ProgramFiles%\\VideoLAN\\VLC\\vlc.exe\" --started-from-file \"%1\"", "key": "HKCR:\\Windows.IsoFile\\shell\\Open\\command", "type": "expandstring", "value": "(default)"}, "msg": "Property (default) does not exist at path HKEY_CLASSES_ROOT\\Windows.IsoFile\\shell\\Open\\command."}
```
