### ISSUE TITLE
ec2_group failings when using groups in other accounts

### ISSUE THREAD

**Issue by roadrunner2** [ansible/ansible#20286]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The current handling of security groups in other accounts is broken in two ways:
1. it requires knowing the group-id, not just the group-name
2. it doesn't handle multiples groups with the same name but in different accounts

##### STEPS TO REPRODUCE
Instead of this:
```
  rules:
    - proto: tcp
      from_port: 9999
      to_port: 9999
      group_id: "{{ acct1 }}/sg-11111111/group-foo"
    - proto: tcp
      from_port: 9999
      to_port: 9999
      group_id: "{{ acct2 }}/sg-22222222/group-foo"
```
we need to be able specify rules like this:
```
  rules:
    - proto: tcp
      from_port: 9999
      to_port: 9999
      group_name: "{{ acct1 }}/group-foo"
    - proto: tcp
      from_port: 9999
      to_port: 9999
      group_name: "{{ acct2 }}/group-foo"
```

First of all, requiring the group-id here is very painful when this is used to create security-groups in multple regions, because while the group name can be kept the same, the group-id's are different (since they are assigned by Amazon). We really want to be able to specify just the group name.

Second, the code currently stores entries in the `groups` dictionary based on name, which obviously fails in the above case where there are multiple groups in different accounts but with the same name. Instead, the entries need to be stored under keys like `<acct>/<group-name>` or similar.

This is re-post of issue ansible/ansible-modules-core#3529
