### ISSUE TITLE
win_service module fails when service is not installed

### ISSUE THREAD

**Issue by bargemb** [ansible/ansible#20297]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_service

##### ANSIBLE VERSION
```
ansible 2.1.1.0
  config file = /path/to/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.1 (Maipo)
Target Host Windows Server 2008 R2

##### SUMMARY
When using win_service module to disable service which is not installed, ansible fails with fatal error 

##### STEPS TO REPRODUCE

```yaml
  - name: Stop and disable w32time service
    win_service:
      name: w32time
      state: stopped
      start_mode: disabled
```

##### EXPECTED RESULTS
win_service module should skip the task if service is not installed. May be with optional parameter

##### ACTUAL RESULTS

```
TASK [Stop and disable w32time service] ****************************************
fatal: [win2k8r2]: FAILED! => {"changed": false, "failed": true, "msg": "Service 'w32time' not installed"}
```

**Comment by ansibot** [comment]
cc @chrishoffman
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
Could you try this with a 2.2 release as well? (either 2.2.0.0, or the 2.2.1.0 release which should  be out any minute now).

I don't see any obvious changes in 2.2 that would fix this however, but the info would be useful.

**Comment by bargemb** [comment]
I have tested with `ansible 2.2.1.0` and getting the same results

**Comment by jhawkesworth** [comment]
@bargemb - please could you try again using latest devel version (or release candidate) as there have been changes to the module recently.

If it still does not work, you can probably work around the problem by discovering if the service exists first, using some playbook tasks like this:

```yaml
- hosts: windows
  tasks:
  - name: check w32time service exists
    win_shell: Get-Service -name w32time -ea SilentlyContinue | Select-Object -Property status | Format-List
    register: w32time_status

  - name: debug
    debug:
       var: w32time_status

  - name: Stop and disable w32time service
#    debug:
#       msg: "status in w32time_status"
    win_service:
      name: w32time
      state: stopped
      start_mode: disabled
    when: w32time_status.stdout | search("Status")
```

Please can you try latest devel?

needs_info

**Comment by jborean93** [comment]
This is the correct behaviour, you are ultimately telling Ansible to set the state of a service to stop which it cannot do if the service does not exist. In your case @jhawkesworth option slightly modified below is an option. You could have a failed_when clause to ignore the msg `Service 'w32time' not installed`.

```
- name: get info on service
  win_service:
    name: w32time
  register: w32time_service

- name: stop and disable w32time service
  win_service:
    name: w32time
    state: stopped
    start_mode: disabled
  when: win32time_service.exists
```

Closing Issue as this is the expected behaviour.
