### ISSUE TITLE
Remove package using product ID, omitting path from win_package

### ISSUE THREAD

**Issue by joshtbernstein** [ansible/ansible#20319]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_package

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

Ansible Host: CentOS Linux release 7.2.1511 (Core)
Managing: Windows Server 2012 R2 Standard

##### SUMMARY

I'd like to be able to have win_package remove a software item by using the product ID and without supplying an MSI/path like I can do with MSIEXEC /X.

An example of when this is useful:
Installing Java places two product IDs in the registry. One is for Java the other is for the Java Auto Updater component. It's not appropriate to point win_package to the MSI as this would remove Java as well. 

##### STEPS TO REPRODUCE

```yaml
- name: 'Remove Java Auto Updater'
  win_package:
    state: 'absent'
    product_id: '{4A03706F-666A-4037-7777-5F2748764D10}'
```

##### EXPECTED RESULTS

Ansible would run MSIEXEC /X {4A03706F-666A-4037-7777-5F2748764D10}

##### ACTUAL RESULTS

```
TASK [role_name : Remove Java Updater] *******************************
/var/lib/awx/venv/ansible/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
fatal: [IP ADDRESS]: FAILED! => {"changed": false, "failed": true, "msg": "Missing required argument: path"}
```

**Comment by ansibot** [comment]
cc @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
That would be useful.  The java autoupdater can be a nuisance in a server environment.
We got round it by passing win package the following arguments:

arguments: INSTALL_SILENT=1 AUTO_UPDATE=0 WEB_JAVA=0 WEB_ANALYTICS=0 /s /L C:\logs\java-installation.log

I found install options documented here: http://docs.oracle.com/javase8/docs/technotes/guides/install/config.html#table_config_options.

Hope this helps,

Jon

**Comment by trondhindenes** [comment]
good idea. I'll check how much of a refactor this would require.

**Comment by joshtbernstein** [comment]
@jhawkesworth Thank you for that, it worked!

@trondhindenes Thanks for looking into this!

**Comment by trondhindenes** [comment]
Guys, I've done a ton of work on this now. Would be really happy if you could test a bit before I submit the PR. 
Essentially, the refactored win_package can:
1. Infer msi product code from the package file, both for local and downloaded files
2. Allows uninstalling without a path for msi-based files.

Updated module can be found here: https://github.com/trondhindenes/ansible/blob/devel/lib/ansible/modules/windows/win_package.ps1

Here's my little "test plan". I'd be especially keen on getting unc-based scenarios tested as I haven't gotten to that yet.
```
---
- hosts: windows
  gather_facts: false
  tasks:
    - name: SUCEEDS uninstall an msi with product id but without path
      win_package:
        name: NodeJS
        productid: "{A41A3BCF-14F8-4984-AE4E-DA662A6992B7}"
        state: absent

    - name: SUCEEDS install a local msi with product id
      win_package:
        name: NodeJS
        path: "C:\\packages\\node-v6.9.4-x64.msi"
        productid: "{A41A3BCF-14F8-4984-AE4E-DA662A6992B7}"

    - name: FAILS install an msi with product id but without path
      win_package:
        name: NodeJS
        productid: "{A41A3BCF-14F8-4984-AE4E-DA662A6992B7}"
      failed_when: false

    - name: SUCEEDS uninstall an msi with product id but without path
      win_package:
        name: NodeJS
        productid: "{A41A3BCF-14F8-4984-AE4E-DA662A6992B7}"
        state: absent

    - name: SUCCEEDS install an msi without product id
      win_package:
        name: NotepadPlusPlus
        path: "https://rikstvcommoncfmgmtsto.blob.core.windows.net/software/npp.6.9.2.installer.msi"
        productid: auto

    - name: FAILS install an msi without path (should fail)
      win_package:
        name: NPP
        productid: "{557BD390-3D2A-48EE-955D-1B88E0D00125}"
        state: present
      failed_when: False

    - name: SUCEEDS install an msi without product id
      win_package:
        name: NodeJS
        path: "C:\\packages\\npp.6.9.2.installer.msi"
        productid: auto

#This should fail in a "controlled" fashion, since it's a exe file and no product id is specified
    - name: FAILS Install the Visual C thingy
      win_package:
        name: Microsoft Visual C thingy
        path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
        arguments: /install /passive /norestart
        productid: auto
      failed_when: False

#This should fail in a "controlled" fashion as we always need the product id or path when absenting a package
    - name: FAILS uninstall an msi without product id and without path
      win_package:
        name: NotepadPlusPlus
        productid: auto
        state: absent
      failed_when: False

#This should succeed, since we infer the product id by downloading the package and getting its product id
    - name: SUCEEDS uninstall an msi without product id
      win_package:
        name: NotepadPlusPlus
        productid: auto
        state: absent
        path: "https://rikstvcommoncfmgmtsto.blob.core.windows.net/software/npp.6.9.2.installer.msi"

#This should fail in a "controlled" fashion, since it's a exe file and we won't be able to grab the product id
    - name: FAILS Install the Visual C thingy
      win_package:
        name: Microsoft Visual C thingy
        path: http://download.microsoft.com/download/1/6/B/16B06F60-3B20-4FF2-B699-5E9B7962F9AE/VSU_4/vcredist_x64.exe
        arguments: /install /passive /norestart
        productid: auto
        state: absent
      failed_when: false
```
