### ISSUE TITLE
rpm_key should verify fingerprint

### ISSUE THREAD

**Issue by sedrubal** [ansible/ansible#20325]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Module [`rpm_key`](https://github.com/ansible/ansible-modules-core/blob/d749ec91e513c40a50b539a7eaccf29c31dda4d4/packaging/os/rpm_key.py)

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
`-`

##### OS / ENVIRONMENT
`-`

##### SUMMARY
It should be possible to verify the long key fingerprint of a key imported by `rpm_key`.

##### STEPS TO REPRODUCE

- There should be an argument `fingerpint`:
```yaml
- rpm_key:
    state: present
    key: http://apt.sw.be/RPM-GPG-KEY.dag.txt
    fingerprint: 0123 4567 89AB CDEF 0123  4567 89AB CDEF 0123 4567
```

##### EXPECTED RESULTS
- A downloaded key or a key imported from a file should be verified against this fingerprint *before* it will be imported to rpm database
