### ISSUE TITLE
win_iis_webapppool Exception: "The property 'Value' cannot be found on this object"

### ISSUE THREAD

**Issue by drowzy** [ansible/ansible#20342]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_iis_webapppool
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY
Setting attributes where the corresponding IIS AppPool property is not an object with the property `Value`
causes an exception. I.e setting the attribute `managedRuntimeVersion:v4.0` will work, setting the attribute `startMode:AlwaysRunning` will fail.
[line 82](https://github.com/ansible/ansible-modules-extras/blob/devel/windows/win_iis_webapppool.ps1#L82):
```powershell
if(-not $currentParameter -or ($currentParameter.Value -as [String]) -ne $newParameter.Value) {
    Set-ItemProperty ("IIS:\AppPools\" + $name) $newParameter.Key $newParameter.Value
    $result.changed = $TRUE
}
```
`$currentParameter` can be a string and will fail when accessing `Value`.
##### STEPS TO REPRODUCE

Use an attribute which is of type string for example `startMode`

```yaml
  win_iis_webapppool:
    name: name
    state: started
    attributes: startMode:AlwaysRunning
```

##### EXPECTED RESULTS

`startMode` is set to `AlwaysRunning`. The execution succeeds. 

##### ACTUAL RESULTS

```
fatal: []: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "win_iis_webapppool"
    }, 
    "msg": "The property 'Value' cannot be found on this object. Verify that the property exists."
}
```

**Comment by ansibot** [comment]
cc @whenrik
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
@drowzy I did a fix for this issue here: https://github.com/ansible/ansible-modules-extras/pull/3257
Unfortunately no one got round to testing it before the repository merge took place.

If you can test out the fix (which also enhances the information returned by the module) let me know (here) and I'll create a new pull request.

**Comment by drowzy** [comment]
@jhawkesworth Your fix solves this issue. However specifying attributes with int values does not seem to work. For instance:
```yml
  win_iis_webapppool:
    name: name
    state: started
    attributes: queueLength:1000
```
Returns the error:

```bash
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "msg": "Specified cast is not valid."}

```

**Comment by jhawkesworth** [comment]
@drowzy thanks for testing.  Can you try the following (just in case yaml parsing is not splitting the key from the var in the case where there is no space)?
```yml
  win_iis_webapppool:
    name: name
    state: started
    attributes: 
       queueLength: 1000

```

**Comment by deekayen** [comment]
@jhawkesworth I re-tried your fix applied against 2.2.1.0, but I still have issues.

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was: +                      ~~~~~~~~~
> fatal: [server.domain.net]: FAILED! => {"changed": false, "failed": true, "msg": "Property 'PropertyType' cannot be found on this object. Make sure that it exists."}

The attributes line is a pipe-delimited list, as the docs show, not split like you're recommending.

processModel.identityType:3|processModel.userName:{{ user_iis_username }}|processModel.password:{{ user_iis_password }}|managedRuntimeVersion:v2.0|enable32BitAppOnWin64:false|managedPipelineMode:1

The same attributes work with my brute-force method of turning off strict mode in https://github.com/ansible/ansible/pull/20366, though it would be nice to get yours to work instead.

**Comment by drowzy** [comment]
@jhawkesworth Yup it works.

**Comment by jhawkesworth** [comment]
@drowzy - great news, thanks for testing.

@deekayen - I'd forgotten this module wants a pipe separated list - I imagine it will work if as I described if you are only setting 1 attribute pair.  With my changes you will need to use the enumerated names for things like pipelineMode etc, rather than the index integer.  My version of the module will tell you what the enumerated names are in the return output (run ansible or ansible-playbook -v to see these).

Looking in the PR the values are:

            "managedPipelineMode": ["Integrated", "Classic"]
            "startMode": ["OnDemand", "AlwaysRunning"]
            "state": ["Starting", "Started", "Stopping", "Stopped", "Unknown"]

Please can you try again using 'managedPipelineMode:Integrated'? instead of 'managedPipelineMode:1'

Also I think you are trying to set some attributes which aren't exposed as part of the app pool interface.  You can set them by running appcmd though, like this though (but use win_shell, not raw!)

```yaml
- name: configure listed app pools to run as correct user
  raw: 'C:\Windows\System32\inetsrv\appcmd.exe set config /section:applicationPools /[name="{{ item }}"].processModel.id
entityType:SpecificUser /[name="{{ win_domain }}\{{ iis_user }}"].processModel.userName: {{ win_domain }}\{{
 win_user }} /[name="{{ win_domain }}\{{ iis_user }}"].processModel.password: {{ iis_password }}'
  with_items:
   - DefaultAppPool
   - AnotherAppPool
```

**Comment by jhawkesworth** [comment]
Hello, I wrote the comment below days ago but it seems it didn't get posted to github.  Sorry - probably because of dodgy network connection on the train.

@drowzy - great news, thanks for testing.

@deekayen - I'd forgotten this module wants a pipe separated list - I imagine it will work if as I described if you are only setting 1 attribute pair.  With my changes you will need to use the enumerated names for things like pipelineMode etc, rather than the index integer.  My version of the module will tell you what the enumerated names are in the return output (run ansible or ansible-playbook -v to see these).

Looking in the PR the values are:

            "managedPipelineMode": ["Integrated", "Classic"]
            "startMode": ["OnDemand", "AlwaysRunning"]
            "state": ["Starting", "Started", "Stopping", "Stopped", "Unknown"]

Please can you try again using 'managedPipelineMode:Integrated'? instead of 'managedPipelineMode:1'

Also I think you are trying to set some attributes which aren't exposed as part of the app pool interface.  You can set them by running appcmd though, like this though (but use win_shell, not raw!)

```yaml
- name: configure listed app pools to run as correct user
  raw: 'C:\Windows\System32\inetsrv\appcmd.exe set config /section:applicationPools /[name="{{ item }}"].processModel.id
entityType:SpecificUser /[name="{{ win_domain }}\{{ iis_user }}"].processModel.userName: {{ win_domain }}\{{
 win_user }} /[name="{{ win_domain }}\{{ iis_user }}"].processModel.password: {{ iis_password }}'
  with_items:
   - DefaultAppPool
   - AnotherAppPool
```
