### ISSUE TITLE
Trying to install PPA, throws "Invalid repository string: ppa:ondrej/php"

### ISSUE THREAD

**Issue by dwdraju** [ansible/ansible#20345]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

apt_repository_module
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```

##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

I tried to add ppa on ubuntu 14.04 server but getting "invalid repository" error. But when I try to add it from the server cli, it works fine.

```yaml
- name: Add PHP repo
  apt_repository:
    repo: 'ppa:ondrej/php'
```
Error output

```
fatal: [ip]: FAILED! => {"changed": false, "failed": true, "msg": "Invalid repository string: ppa:ondrej/php"}
````
