### ISSUE TITLE
Report failed tasks that were rescued separately from other failures

### ISSUE THREAD

**Issue by aabdnn** [ansible/ansible#20346]
##### ISSUE TYPE
 - Feature Request

##### COMPONENT NAME
Ansible core

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
ANSIBLE_GATHERING=smart
ANSIBLE_HASH_BEHAVIOUR=merge
ANSIBLE_REMOTE_TEMP=/tmp
ANSIBLE_RETRY_FILES_ENABLED=no
ANSIBLE_SSH_PIPELINING=yes
ANSIBLE_TRANSPORT=local

##### OS / ENVIRONMENT
CentOS 7, with ansible running in local mode.

##### SUMMARY
Under Ansible 2.1, a block that had a failed task, but that was rescued, did not cause Ansible to report any failures. In other words, at the end of the play, I would see "failed=0".

With Ansible 2.2.1, even though a failed task is rescued, Ansible reports "failed=1" at the end.

##### STEPS TO REPRODUCE
Create a block..rescue sequence, containing a task that fails, and run the playbook. Ansible will report failed tasks at the end.

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - block:
    - fail: msg="This failure will be rescued"
    rescue:
    - debug: msg=NOOP
```

##### EXPECTED RESULTS
The summary line at the end should have shown failed=0

##### ACTUAL RESULTS
The summary line shows failed=1

```
PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
