### ISSUE TITLE
ec2 module does not create root volume as documented

### ISSUE THREAD

**Issue by zyv** [ansible/ansible#20347]
_From @AgDude on July 18, 2016 13:26_

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2 module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

ubuntu 14.04
##### SUMMARY

Launching an EBS backed ec2 instance with a non-default root volume does not work as shown in the documentation example. Instead it launches an instance with a standard 8GB root volume, and an additional volume per the definition.

The following is the task which was used to launch the instance (some keys removed for brevity):

```
    - name: Launch ec2 instance
      ec2:
        instance_type: "t2.small"
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 15
      register: ec2
```

This is the example from http://docs.ansible.com/ansible/ec2_module.html, which shows a non-standard root volume:

```
# Single instance with ssd gp2 root volume
- ec2:
    key_name: mykey
    group: webserver
    instance_type: c3.medium
    image: ami-123456
    wait: yes
    wait_timeout: 500
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
    vpc_subnet_id: subnet-29e63245
    assign_public_ip: yes
    exact_count: 1
```

_Copied from original issue: ansible/ansible-modules-core#4204_

**Comment by zyv** [comment]
_From @adeimos on July 26, 2016 16:25_

Hello,
I'm having the same problem. In addition, I can say that if you use an AMI that has the root folder set to /dev/sda (such as CentOS one), really weird things happen: from the web console I noticed that an additional EBS volume get created (from the snapshot of the AMI) but it is completely detached from the instance, so it becomes an effective "dangling reference". I tried to reference it from inside the command, but when I use /dev/sda as a device_name I get an error. In order to test it you can use, as ami id, the following one: ami-6d1c2007.

**Comment by zyv** [comment]
_From @marcovnyc on August 30, 2016 18:44_

I solved this problem instead of using the example
- device_name: /dev/xvda
  i used this instead. 
- device_name: /dev/sda1 

then the root drive was created as a 20 Gig drive as  i had defined it. 

root@ip-172-31-154-181:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.4G   12K  7.4G   1% /dev
tmpfs           1.5G  352K  1.5G   1% /run
/dev/xvda1       20G  1.2G   18G   7% /

this is on an ubuntu machine.

**Comment by zyv** [comment]
_From @ansibot on August 30, 2016 18:51_

@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zyv** [comment]
_From @chris-neely on September 14, 2016 0:45_

I'm having a similar issues with windows instances but regardless of the mount point it launches an instances with the default volume_size.  I opened my own problem; but curious if you had any luck with this?

**Comment by zyv** [comment]
_From @mazzystr on September 30, 2016 23:31_

Confirmed with ansible 2.1.2.0 against Red Hat Cloud Access ami (us-east-1 / ami-10251c7a)

```
  ec2:
    key_name: mykey
    instance_type: "{{ bastion }}"
    image: "{{ ami }}"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 25
        delete_on_termination: true
    monitoring: no
    region: "{{ region }}"
    instance_tags:
      Name: "bastion.{{ public }}"
    termination_protection: no
    vpc_subnet_id: "{{ vpc.subnets.0.id }}"
    assign_public_ip: yes
```

**Comment by zyv** [comment]
_From @ansibot on September 30, 2016 23:41_

@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zyv** [comment]
_From @ansibot on October 16, 2016 8:28_

@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zyv** [comment]
_From @mazzystr on October 19, 2016 14:29_

The following works for us

```
- name: Creating AWS EC2 Bastion instances
  ec2:
    assign_public_ip: no
    exact_count: 1
    group: ['BastionSg']
    instance_profile_name: bastion
    instance_type: "{{ type }}"
    image: "{{ ami }}"
    instance_tags:
      Name: "bastion.{{ domain }}"
      Role: "Bastion"
      environment: "dev"
    key_name: "{{ keypair }}"
    monitoring: no
    region: "{{ region }}"
    termination_protection: no
    volumes:
      - device_name: /dev/sda1
        device_type: gp2
        volume_size: 30
        delete_on_termination: true
    vpc_subnet_id: "{{ subnet }}"
```

**Comment by zyv** [comment]
_From @ansibot on October 31, 2016 8:40_

@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zyv** [comment]
_From @pauricthelodger on November 5, 2016 22:21_

Also affects 2.2

**Comment by zyv** [comment]
_From @ansibot on November 15, 2016 9:43_

@ansible, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zyv** [comment]
_From @zubrabubra on November 29, 2016 20:58_

Looks like it might be the problem of some of RedHat AMIs v 6.5 / 7.0, please check the [link](https://access.redhat.com/solutions/1599103)
In case your infrastructure allows switching to the different version you can use 7.3 which does not have this issue.

**Comment by zyv** [comment]
_From @ansibot on December 7, 2016 17:56_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by zyv** [comment]
Confirmed on `ansible 2.2.1.0` / `ami-fe408091` (Ubuntu Server 16.04 LTS (HVM), SSD Volume Type); apparently for these AMIs the default is still `device_name: /dev/sda1`.

**Comment by sandstrom** [comment]
You probably already know, but I think this is an issue with AWS and/or Ubuntu. Seeing the same even though I'm not using Ansible.

**Comment by ansibot** [comment]
cc @lwade @tgerla
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jdoss** [comment]
This still impacts 2.4. Trying to set the volume size with `/dev/xvda` results in the default size being used. This is with Fedora 26.

**Comment by ansibot** [comment]
cc @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dlouzan** [comment]
Just FYI, I don't think this is an ansible issue and could be closed. Actually, it seems it's not even an issue at all according to the AWS docs (whether this is good API design by Amazon is another question)
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/device_naming.html

Quoting that page:
>  The block device driver for the instance assigns the actual volume name when mounting the volume, and the name assigned can be different from the name that Amazon EC2 uses.

Depending on the instance type, one name or another needs to be chosen if you want to configure the root device, and in my experience, failing to choose the appropriate combination will create a new detached EBS volume with the configured values and leave the root with the defaults.

**Comment by gpiszczek** [comment]
Hit the same problem. As @dlouzan wrote the problem boils down to choosing appropriate device_name value. In my case I was using Debian Stretch image (ami-ada0f946). To get the correct device name use web console (Images -> AMI -> Details -> Root Device Name) or awscli:
```
$ aws ec2 describe-images --image-ids ami-ada0f946
[...]
            "BlockDeviceMappings": [
                {
                    "DeviceName": "xvda",
                    "Ebs": {
                        "Encrypted": false,
                        "DeleteOnTermination": true,
                        "VolumeType": "gp2",
                        "VolumeSize": 8,
                        "SnapshotId": "snap-0771f9370fe1a3449"
                    }
                }
            ],
 [...]
```
Here we have **"xvda"**. To create an instance with different volume size you must use this **EXACT** device name, in particular **DO NOT** prepend it with /dev/ when it is not there. So in this case following snippet does the job:
```
  - ec2:
[...]
    volumes:
    - device_name: xvda
      volume_type: gp2
      volume_size: 50
      delete_on_termination: yes
[...]
```
Hope it helps :).

**Comment by ansibot** [comment]
cc @skvidal
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mglantz** [comment]
It seems to me, that depending on how the AMI image has been built, different arguments must be passed as device_name. As I found out, on the RHEL 7 AMI, it is /dev/sda1.
To find out what the argument should be, I think you should check the volume created in the EC2 console and look for the field called _Attachment information_. In my example of the RHEL 7 AMI, it reads as follows:
```
Attachment information
i-083e2aae53e8b0df7:/dev/sda1 
```

Changing the device name passed to read /dev/sda1, changes the root volume as it should. Passing any other name causes Ansible to create an additional device instead of creating a larger root volume.

If my theory is correct, I don't see how Ansible can cater for different ways that vendors build AMI images and the different Linux vendors or Amazon should implement a standard, possibly.

**Comment by mglantz** [comment]
Extended root volume for RHEL 7 AMI:
```
  - name: Provision RHEL7 server
    ec2:
      ...
      key_name: "{{ec2_key}}"
      region: "{{ ec2_region }}"
      group: "{{ ec2_security_group }}"
      instance_type: t2.micro
      image: "{{ ami_id }}"
      volumes:
      - device_name: /dev/sda1
        volume_size: 100
        volume_type: gp2
        delete_on_termination: true
      wait: true
      exact_count: 1
    register: foobar
```

**Comment by mglantz** [comment]
If you check your instance root device field, it also indicates what value to choose, AFAIKS:
Example:
```
Root device
/dev/sda1
```

**Comment by victorock** [comment]
You need to know what is the RootDeviceName of your AMI and replace it, as described by @mglantz

**Comment by trevorijones** [comment]
I found it usefull to pair with the ec2_ami_facts to fetch the root_device_name of the current image being launched:
```
- name: ami facts
  ec2_ami_facts:
    image_ids: "{{ ami_id }}"
  register: ami_facts

- name: set current ami
  set_fact:
    ami: "{{ ami_facts.images | first }}"
```

then you can use `ami.root_device_name` in `ec2` tasks to set the `device_name`
