### ISSUE TITLE
Ansible Skip (check mode) logic mismatch

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible#20357]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.2
```

##### SUMMARY
I place this bug, so we all can brainstorm about it.

I do migrate some old scripts, from 1.9 to 2.2, the issue:

```
Old code (1.9):
- name: "check file.tgz local sha1 var"
  shell: sha1sum /tmp/file.tgz || echo 'no file'   #By the time I did write it the file.stat did not support sha1
  register: local_sha1
  changed_when: False

- debug: msg="{{ local_sha1 }}"

#this fails when the local file sha1 is different than the one in hostvars
- name: 'Fail if file changed maunally'
  ping: nonehost
  when: local_sha1 is defined and local_sha1.stdout not in 'no file' and campaigns.promo_opt.sha1_sum not in local_sha1.stdout
```
This fails when run in ansible 2.2 with:
> ERROR! this task 'ping' has extra params, which is only allowed in the following modules: command, win_command, shell, win_shell, script, include, include_vars, add_host, group_by, set_fact, raw, meta

Now switching to ansible 2.2
```
- name: 'Fail if wordVec changed maunally'
  assert: 
      that:
          - local_sha1 is defined
          - local_sha1 is defined and local_sha1.stdout is defined
            #- local_sha1 is defined and local_sha1.stdout not in 'no file' and campaigns.promo_opt.sha1_sum not in local_sha1.stdout
```

##### THE GOAL:
1. The idea [in this case] is to look if there was manual file change, that result in different sha1 hash, than is registered in the repository. Do it BEFORE possible future file download.
2. [Other similar case] Verify the Nexus file checksum, before downlading the file by the 'get_url' module (for my current knowledge, the get_url module can not validate the file checksum (exposed by the Nexus or sth) _before_ downlading it).

Issues:

1. In the **checkmode**, the local_sha1 is defined! (for me that is a **BUG**), but no local_sha1.stdout present - assert would fail
Please note! in ansible 1.9, my 'hack around' solution was passing correctly (because ping is supporting the check/SKIP mode), and in the regular-mode it did evaluate properly!

##### EXPECTED RESULTS
Allow skipping assert in checkmode, or skip the conditional if variable is not present (due to not beeing registered - because of check mode)

**Comment by robinro** [comment]
In general it's a good idea that modules fill the `register` variable even in checkmode, since many modules can generate a reasonable output even without writing anything to disc (package managers, lineinfile, ...).

For your case you can add `when: not ansible_check_mode` to the first task to skip it in checkmode.
Or even better: use the `file` module to get the sha1, since this also works in checkmode.

**Comment by sirkubax** [comment]
I like `when: not ansible_check_mode` option (for the assert).

WRT file module, to get the checksum, this would solve only a part of the problem, for the completnes of the topic, please consider this example. The jar download (that takes noticeable amount of time) is skipped if the Nexus file checksum match the one of the disk.

```
  - name: "GENERIC | register nexus sha1 var from url lookup"     
    set_fact:                                                     
        sha1_from_url: "{{ lookup('url', url_sha1) }}"

  - name: "GENERIC | register {{ jar_file_dest }} local sha1 var"   #this can be rewritten to use the file module
    shell: sha1sum {{ jar_file_dest }} || echo 'no file'            
    register: local_sha1                                                        
    changed_when: False          
                                               
  - name: "GENERIC | get {{ jar_file_dest }}"      #downlad file only if the checksum change                  
    get_url: >                                                            
        url={{ url }}                                         
        dest={{ jar_file_dest }}                              
    when: local_sha1 is defined and sha1_from_url not in local_sha1.stdout
    notify: restart default-service      
```

**Comment by robinro** [comment]
I meant the `when: not ansible_check_mode` for the `shell` call, but this is obsolete when using the stat module.

I'd suggest
```
 - name: "GENERIC | register nexus sha1 var from url lookup"     
    set_fact:                                                     
        sha1_from_url: "{{ lookup('url', url_sha1) }}"

  - name: "GENERIC | register {{ jar_file_dest }} local sha1 var"
    stat: 
        path: "{{ jar_file_dest }}" 
        get_checksum: True 
        checksum_algorithm: sha1 
    register: local_sha1                                                        
                                               
  - name: "GENERIC | get {{ jar_file_dest }}"
    get_url: 
        url: "{{ url }}"                                      
        dest: "{{ jar_file_dest }}"                           
    when: not local_sha1.stat.exists or sha1_from_url not in local_sha1.stat.checksum
    notify: restart default-service      
```

**Comment by sirkubax** [comment]
heh, I did forget, that the 'remote checksum' has been added in >2.x. I even did write a proper doc for that :P [commit](https://github.com/ansible/ansible/commit/2e3ad2b80ad766102aeea4fb578178a89460d230)

Then this can be simplified to
```
  - name: "GENERIC | get {{ jar_file_dest }}"
    get_url: 
        url: "{{ url }}"                                      
        dest: "{{ jar_file_dest }}"         
        checksum: "sha1:{{ lookup('url', url_sha1) }}"                   
    notify: restart default-service      
```
