### ISSUE TITLE
win_user: Fails with Exception calling "SetInfo" with "0" argument(s)

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#20369]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_user

##### ANSIBLE VERSION
v2.3

##### OS / ENVIRONMENT
Windows 2012 R2

##### SUMMARY
When using the below playbook (without password !) I get this error:
```powershell
Exception calling "SetInfo" with "0" argument(s): "The password does not meet the password policy requirements. Check the minimum password length, password complexity and password history requirements."
```

```yaml
- win_user:
    name: sqlsvc
    groups:
    - Administrators
    groups_action: add
    password_never_expires: yes
    state: present
```

Obviously I didn't provide a password, but it shouldn't bail out with this specific error.
