### ISSUE TITLE
cannot filter host_lists with group_by generated groups

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#20360]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
group_by

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /Users/dkimsey/ansible/ansible.cfg
  configured module search path = ['library/']
```

##### CONFIGURATION
not applicable

##### OS / ENVIRONMENT
OS X

##### SUMMARY

When I attempt to use a dynamically created group as a host selector, it does not work if the dynamically created group was referenced before it was created.

##### STEPS TO REPRODUCE

See complete [playbook test case][1], excerpt follows.

```yaml
# ansible-playbook -i localhost, test-play.yml

- name: Gather facts and partition hosts
  hosts: '!__partitioned'
  become: false
  connection: local
  tasks:
    - group_by:
        key: __partitioned

- hosts: '!__partitioned'
  become: false
  connection: local
  tasks:
    - fail: msg='I should not run, !__partitioned filter used'
```

##### EXPECTED RESULTS

The playbook should not fail.

##### ACTUAL RESULTS

```
...
PLAY [!__partitioned] **********************************************************

TASK [fail] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "I should not run, !__partitioned filter used"}
```

[1]: https://gist.github.com/dekimsey/015e3131625e00878b8bf6cee3aa6f02

**Comment by bmalynovytch** [comment]
I confirm I can reproduce a similar case:
```yaml
    - name: Add groups based on OS family
      group_by:
      args:
        key: "OS_{{ ansible_os_family }}"
      check_mode: false
      tags: always

    - debug: var=groups
      check_mode: false
      tags: always
```
produces:
```
TASK [Add groups based on OS family] *******************************************
ok: [ddd-1] => {"add_group": "OS_RedHat", "changed": false}
ok: [ddd-3] => {"add_group": "OS_RedHat", "changed": false}
ok: [ddd-2] => {"add_group": "OS_RedHat", "changed": false}
ok: [xxx-2] => {"add_group": "OS_RedHat", "changed": false}
ok: [xxx-3] => {"add_group": "OS_RedHat", "changed": false}
ok: [yyy-2] => {"add_group": "OS_RedHat", "changed": false}
ok: [yyy-1] => {"add_group": "OS_RedHat", "changed": false}
ok: [xxx-1] => {"add_group": "OS_RedHat", "changed": false}
ok: [zzz-2] => {"add_group": "OS_RedHat", "changed": false}
ok: [zzz-1] => {"add_group": "OS_RedHat", "changed": false}
ok: [bbb] => {"add_group": "OS_RedHat", "changed": false}
ok: [aaa] => {"add_group": "OS_RedHat", "changed": false}
ok: [ccc] => {"add_group": "OS_RedHat", "changed": false}

TASK [debug] *******************************************************************
ok: [zzz-1] => {
    "groups": {
        "OS_RedHat": [
            "ddd-1"
        ],
        "all": [
            "yyy-2",
            "yyy-1",
            "ddd-1",
            "ddd-3",
            "ddd-2",
            "xxx-3",
            "xxx-2",
            "xxx-1",
            "zzz-2",
            "zzz-1",
            "aaa",
            "bbb",
            "ccc"
        ],
...
```
OS_RedHat should be populated the entire list of hosts, as they are all running CentOS, which is confirmed by the first task's output.
And, "funnily", the playbook runs properly with the following selector:
```yaml
- name: Global configuration
  hosts: all:&OS_RedHat
...
```
So, the `groups` variable is wrong, but the real (inner) groups seem to be fine (I've tested changing the selector with invalid `OS_xxx`, which doesn't match any host anymore).

I also tried with:
```yaml
    - name: Add groups based on OS family
      group_by:
      args:
        key: "OS_{{ hostvars[item].ansible_os_family }}"
      check_mode: false
      run_once: true
      with_items: "{{ groups.all }}"
      tags: always
```
... result is the same: `groups.OS_RedHat` contains only the first host (depending on the `with_items` order).

**Comment by ansibot** [comment]
cc @jhoekx
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
In the first play in the example playbook it is targeting `!__partitioned` before the group is created by the `group_by` task. When wanting to group_by facts, the first play needs to gather facts. This first play should target all the hosts and not use the `local` connection in order to first gather facts then create the group. Then subsequent plays in the same playbook can target the group.

```yaml
- name: Gather facts on all hosts and create __partitioned group
  hosts: all
  tasks:
    - group_by:
        key: __partitioned
      when: "{{ some test that matches partitioned hosts }}"

- name: Run tasks against all hosts except those in the __partitioned group 
  hosts: '!__partitioned'
  tasks:
    - fail: msg='I should not run, !__partitioned filter used'
```
