### ISSUE TITLE
Docker modules don't work with latest docker-py (2.0+)

### ISSUE THREAD

**Issue by berlic** [ansible/ansible#20380]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container, docker_image, other docker modules

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /vagrant/cloudocker/ansible.cfg
  configured module search path = ['./library/']
```

##### CONFIGURATION
Standard configuration

##### OS / ENVIRONMENT
On target Docker host
```
# pip list
...
docker (2.0.1)
...
```

##### SUMMARY
Although `docker-py` is installed Ansible gives:

> Failed to import docker-py - cannot import name Client. Try `pip install docker-py`

##### STEPS TO REPRODUCE
`pip install docker-compose` this will install latest version of docker-compose, which is dependent on `docker-py` 2.0+ (named `docker` on pypi from now on). 

`docker_image` calls stops working after this.

Quotes from `docker-py` release notes:

> **Breaking changes**
>
> docker.Client has been renamed to docker.APIClient
> ...
> The name of the pip package is now docker (was: docker-py). New versions of this library will only be published as docker from now on.
> ...

So [this](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/docker_common.py#L34) gives error.

**Comment by yuriidanyliak** [comment]
It affected us as well. 

The workaround, if you use `angstwad.docker_ubuntu` playbook is to lock versions prior `2.0.1`

```yaml
    - role: angstwad.docker_ubuntu
      docker_group_members: ['{{ ssh_user }}']
      pip_version_docker_py: '1.10.6'
      pip_version_docker_compose: '1.9.0'
      tags: ['docker']
```

Also, I've got to remove all pip packages from host machine:

    pip list | grep -v pip | awk '{print $1}' | while read i; do sudo pip uninstall -y "$i"; done
