### ISSUE TITLE
with_nested is broken when used contiditional when

### ISSUE THREAD

**Issue by chrisrana** [ansible/ansible#20382]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME
with_nested

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### SUMMARY

when condition for list is not working when used with with_nested

Ideal way of calling script
 ansible-playbook sample2.yml --ask-vault-pass  --extra-vars '{"fp_list": [iwan]}'

1. When i run the following script without passing arguments, 
    ansible-playbook sample2.yml --ask-vault-pass 
 
    it fails.

   Ideally if argumenst i.e fp_list is not passed it should  not include the script.yml but it is including it and it is failing.

2.  It works fine if i include script2.yml instead of script1.yml. In script2.yml doesnot have with_nested loop.

I feel with_nested is broken here.Please update me if it has any 

```
**Doesnot work**
bash-4.3# ansible-playbook sample2.yml --ask-vault-pass 
Vault password:
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Monday 16 January 2017  19:14:15 +0000 (0:00:00.044)       0:00:00.044 ********
ok: [localhost]

TASK [Writing function pack list in a file] ************************************
Monday 16 January 2017  19:14:18 +0000 (0:00:03.565)       0:00:03.610 ********
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'fp_list' is undefined"}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

**Working**

bash-4.3# ansible-playbook sample.yml --ask-vault-pass
Vault password:
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
Monday 16 January 2017  20:07:32 +0000 (0:00:00.032)       0:00:00.032 ********
ok: [localhost]

TASK [set_fact] ****************************************************************
Monday 16 January 2017  20:07:35 +0000 (0:00:03.601)       0:00:03.634 ********
skipping: [localhost]

TASK [debug] *******************************************************************
Monday 16 January 2017  20:07:35 +0000 (0:00:00.041)       0:00:03.676 ********
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

Monday 16 January 2017  20:07:35 +0000 (0:00:00.043)       0:00:03.719 ********
===============================================================================
setup ------------------------------------------------------------------- 3.60s
debug ------------------------------------------------------------------- 0.05s
set_fact ---------------------------------------------------------------- 0.04s
```

 
##### STEPS TO REPRODUCE

```yaml
**sample.yml**
---
- hosts: localhost
  vars_files:
    - ./servicepack_vars.yml

  tasks:
    - include: script1.yml
      when: fp_list is defined and fp_list

**script1.yml**

---

- name: Writing function pack list in a file
  when: item.0.name == item.1
  lineinfile:
    dest: ./sampletext.yml
    line: '  - {{ item.1 }}'
  with_nested:
    - "{{ jobs.nso1.f_packs }}"
    - "{{ fp_list }}"

- set_fact:
    isTrue: True

- debug: msg="vikram ranabhatt"
  when: isTrue


**script2.yml**

- set_fact:
    isTrue: True

- debug: msg="vikram ranabhatt"
  when: isTrue


**servicepack.yml**

name: user
jobs:
  nso1:
    f_packs:
      - f-pack-1:
        name: "service pack1"
        microservices:
        - microservice-1:
          name: "vsrservice"
          streams: "vi-noti,jk-noti"
          version: latest
        - microservice-2:
          name: "mymicroservice"
          streams: "device-notifications,ncs-events,vms-notif,pnpnotif"
          version: latest
```

##### ACTUAL RESULTS

```

```
