### ISSUE TITLE
with_dict cannot recognize dict object

### ISSUE THREAD

**Issue by dimakievua** [ansible/ansible#20387]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible Loops module

##### ANSIBLE VERSION
ansible 2.0.0.2

##### CONFIGURATION
No changes were made in ansible.cfg

##### OS / ENVIRONMENT
Ubuntu 5.4.0-6ubuntu1~16.04.4

##### SUMMARY
When I try to use dict object inside include task - with_dict tells "ERROR! with_dict expects a dict"

##### STEPS TO REPRODUCE
In my task/main.yml I'm including another file for specific task:

```
- name: Calling env.yml for different users
  include: env.yml user={{item}}
  with_items: "{{ users }}"
```
In env.yml code is:
```
- name: Add env
  lineinfile: dest="/home/{{ user }}/{{ docker_compose_base_dir }}/dev.env" line="{{ item.key }}{{ ":" }} {{ item.value }}"
  with_dict: 
    - "{{ nginx }}"
  become: yes
  become_user: "{{ user }}"
```
dictionary is:
```
nginx:
  FE_PORT: 11115
  FE_SOCKET: 11116
  BE_PORT: 1337
  BE_NGINX_PORT: 11117
```

##### EXPECTED RESULTS
Add lines:
  FE_PORT: 11115
  FE_SOCKET: 11116
  BE_PORT: 1337
  BE_NGINX_PORT: 11117
to dev.env file

##### ACTUAL RESULTS
when I try to use with_items it says:

> TASK [users : Add env] ***********************************************************
> fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! 'dict object' has no attribute 'key'"

change it to with_dict:

> TASK [users : Add env] ********************
> fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! with_dict expects a dict"}

Anyway code:
```
- name: debug
  debug: msg="{{ nginx }}"
  tags: [user,devfiles]
```
shows:

> TASK [users : debug] ***********************************************************
> ok: [localhost] => {
>     "msg": {
>         "BE_NGINX_PORT": 11117, 
>         "BE_PORT": 1337, 
>         "FE_PORT": 11115, 
>         "FE_SOCKET": 11116
>     }
> }
