### ISSUE TITLE
[WARNING]: network provider arguments are no longer supported.  Please use connection: network_cli for the task

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#20391]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_command

##### ANSIBLE VERSION
```
ansible 2.3.0 (aws-ios 64432c8f7c) last updated 2017/01/17 11:13:57 (GMT +100)

```

##### SUMMARY
Even on tasks that don't specify any `provider:` arguments we get the following warnign
`[WARNING]: network provider arguments are no longer supported.  Please use connection: network_cli for the task`

Even on simple tasks like:
```yaml
- name: Ensure we have loopback 888 for testing
  ios_config:
    src: config.j2
```

Adding in some debug shows that this is being triggered because `timeout` is set (via a default) and the following code is detecting that

```python



##### STEPS TO REPRODUCE
```yaml
      for key in NET_TRANSPORT_ARGS:
          if module.params[key]:
              warnings.append(
                  'network provider arguments are no longer supported.  Please '
                  'use connection: network_cli for the task'
              )   
+             warnings.append(key) # Added in so I can see which key is failing
              break

```
`NET_TRANSPORT_ARGS` is defined in `module_utils/network.py`
`transport:` is the only option with a default (that isn't `False`)

##### ACTUAL RESULTS
```yaml
- name: Ensure we have loopback 888 for testing
  ios_config:
    src: config.j2
```
