### ISSUE TITLE
Updating tagging only for RDS module

### ISSUE THREAD

**Issue by dan-osms** [ansible/ansible#20395]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

RDS
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 7f17718b82) last updated 2017/01/05 13:54:42 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

MAC 10.12.2
##### SUMMARY

Need to be able to update tags on current running RDS instances. Tried using modify command to simply have a play identify RDS instance via name to update it's tagging
##### STEPS TO REPRODUCE

---
```
- name: RDS Tagger
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  vars_files:
    - ./RDS_Profiles/instances.yml ### where vars for instance name and tagging structure are defined.
  tasks:
  - name: RDS modify tag
    with_items: "{{ list }}"
    when: ("{{ item.cmd }}" == "modify" )
    rds:
      command: modify
      instance_name: "{{ item.name }}"
      tags:
        dept: "{{ item.dept }}"
        app_name: "{{ item.app_name }}"
        project_name: "{{ item.project_name }}"
        owner_email: "{{ item.owner_email }}"
```
##### vars file
```
      - { cmd: "modify",
          where: "us-east-1",
          profile: "dev",
          name: "somedb",
          dept: "test",
          app_name: "test",
          project_name: "test",
          owner_email: "test@test.com"
        }
```

```yaml
- name: RDS Tagger
  hosts: 127.0.0.1
  gather_facts: no
  connection: local
  vars_files:
    - ./RDS_Profiles/instances.yml ### where vars for instance name and tagging structure are defined.
  tasks:
  - name: RDS modify tag
    when: ("{{ item.cmd }}" == "modify" )
    with_items: "{{ list }}"
    rds:
      command: modify
      instance_name: "{{ item.name }}"
      tags:
        dept: "{{ item.dept }}"
        app_name: "{{ item.app_name }}"
        project_name: "{{ item.project_name }}"
        owner_email: "{{ item.owner_email }}"
```

##### EXPECTED RESULTS

A feature could allow modify command to allow me to modify the tagging structure on the running RDS instance. Currently tagging is only applicable to create, replicate, and/or restore.
##### ACTUAL RESULTS

"msg": "Parameter tags is not valid for modify command"

```
"msg": "Parameter tags is not valid for modify command"
```
