### ISSUE TITLE
Accessing registered variables created from shell module raises `template error while templating string: unexpected '.'.`

### ISSUE THREAD

**Issue by ko-christ** [ansible/ansible#20400]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`shell` module

##### ANSIBLE VERSION
```
[~]>ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
inventory = ./inventory.sh
callback_whitelist = profile_tasks
gathering = smart
gather_subset = !facter,!network,!virtual,!ohai,!hardware

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=600s
pipelining = True
```

##### OS / ENVIRONMENT
Ubuntu 15.10

##### SUMMARY
Accessing registered variables created from `shell` module raises  `template error while templating string: unexpected '.'.`.
The shell command I am running is this (this is not jinja).
```
$ docker inspect --format '{{ .State.Running }}' foo-test-6819
true
```
Using `command` module instead of `shell` is a my workaround.
Note: Error is not present on `2.2.0.0`.

##### STEPS TO REPRODUCE
execution of a simple `status.yml` playbook with a role
`ansible-playbook -i inventory.sh status.yml -c local -e name=test -e port=6819 -v` 
```yaml
---
# Play to run actions
- name: Actions "{{ name }}"
  hosts: "{{ name }}"
  serial: 1
  max_fail_percentage: 0

  roles:
    - { role: node-action, action: status }
```
Role `node-action`
```yaml
  - name: inspect container
    shell: "docker -H {{ docker_url }} inspect --format '{{ '{{ .State.Running }}' }}' foo-{{ name }}-{{ port }}'"
    register: inspect_output
    changed_when: false

  - name: container status
    debug:
      msg: "foo-{{ name }}-{{ port }} State.Running: {{ inspect_output.stdout }}"
    when: 
      - inspect_output.stdout == 'false' or inspect_output.stdout == 'true'
```

##### EXPECTED RESULTS
No Error on `container status` task.

##### ACTUAL RESULTS
Error on `container status` task.
```
TASK [node-action : container status] ******************************************
Wednesday 18 January 2017  15:07:46 +0200 (0:00:00.135)       0:00:00.471 ***** 
fatal: [test_localpc_1]: FAILED! => {"failed": true, "msg": "The conditional check 'inspect_output.stdout == 'false' or inspect_output.stdout == 'true'' failed. The error was: {u'cmd': u\"docker -H unix:///var/run/docker.sock inspect --format '{{ .State.Running }}' foo-test-6819\", u'end': u'2017-01-18 15:07:46.555975', u'stdout': u'true', u'changed': False, u'start': u'2017-01-18 15:07:46.544866', u'delta': u'0:00:00.011109', u'stderr': u'', u'rc': 0, 'stdout_lines': [u'true'], u'warnings': []}: template error while templating string: unexpected '.'. String: docker -H unix:///var/run/docker.sock inspect --format '{{ .State.Running }}' localpc-test-6819\n\nThe error appears to have been in '/home/localpc/Documents/roles/node-action/tasks/docker-action.yml': line 8, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: container status\n    ^ here\n"}
```
Workaround is to abandon `shell` module and use `command` when possible.

**Comment by dmsimard** [comment]
Seeing this as well, interestingly enough in the same docker context -- it looks like a regression from 2.2.0.0 because downgrading the version fixes it.

A simple reproducer doing a 'echo' instead of requiring docker:
```
#!/bin/bash
cat << EOF >/tmp/playbook.yml
- name: Test playbook
  hosts: localhost
  tasks:
    - shell: >
        echo "docker images --format {{ '{{' }}.Repository{{ '}}' }}"
      register: foo

    - debug:
        msg: "{{ foo }}"
EOF
ansible-playbook -i "localhost" /tmp/playbook.yml
```

**ansible 2.2.1.0**
```
# ansible-playbook -i "localhost" playbook.yml
 [WARNING]: Host file not found: localhost

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [Test playbook] ***********************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [command] *****************************************************************
changed: [localhost]

TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "{u'cmd': u'echo \"docker images --format {{.Repository}}\"', u'end': u'2017-01-18 21:06:50.366960', u'stdout': u'docker images --format {{.Repository}}', u'changed': True, u'start': u'2017-01-18 21:06:50.364691', u'delta': u'0:00:00.002269', u'stderr': u'', u'rc': 0, 'stdout_lines': [u'docker images --format {{.Repository}}'], u'warnings': []}: template error while templating string: unexpected '.'. String: echo \"docker images --format {{.Repository}}\""}
	to retry, use: --limit @/tmp/playbook.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```

**ansible 2.2.0.0**
```
# ansible-playbook -i "localhost" playbook.yml
 [WARNING]: Host file not found: localhost

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [Test playbook] ***********************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [command] *****************************************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "cmd": "echo \"docker images --format {#.Repository#}\"", 
        "delta": "0:00:00.002158", 
        "end": "2017-01-18 21:07:14.673771", 
        "rc": 0, 
        "start": "2017-01-18 21:07:14.671613", 
        "stderr": "", 
        "stdout": "docker images --format {#.Repository#}", 
        "stdout_lines": [
            "docker images --format {#.Repository#}"
        ], 
        "warnings": []
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

**Comment by berlic** [comment]
Yes, this bug is introduced in 2.2.1 –  `{{` is not replaced to `{#` as in 2.2.0.

**Comment by nitzmahone** [comment]
cc @jimi-c templating changes from 2.2.0-2.2.1?

**Comment by kamalsaurabh** [comment]
I got the error on 2.2.0.0 as well.
temporary workaround I am using , use {#.Names#} instead of {{.Names}}

**Comment by PickledDragon** [comment]
Had similar issue with 2.2.1.0
```yml
- name: Gather MySQL Docker container address and port
  shell: "docker inspect --format {{'{{'}}.NetworkSettings.IPAddress{{'}}'}} {{accounting_docker_database_service_name}}_{{accounting_instance_name}}"
  register: mysql_docker_inspect_ip
```

Worked around with BASH concatenation
```bash
docker inspect --format '{''{ .NetworkSettings.IPAddress }''}'
```
