### ISSUE TITLE
Issue with junos_config module with order of statements

### ISSUE THREAD

**Issue by narankhetani** [ansible/ansible#20412]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

modules/junos/junos_config

##### ANSIBLE VERSION

```
/glide/bin/ansible --version
ansible 2.2.0.0
  config file = /home/users/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

no changes.

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I was using the junos_template module in 2.1 with pretty good results, but 2.2 merged junos_template into junos_config.  Good idea, but I don't think it's working right.  The first line is there to instantiate the ACL in case it doesn't already exist, in order to prevent any errors when executing the second line which blows away the existing ACL in order to replace it.  This worked using junos_template, but when I use junos_config it seems that the second 'delete' statement is not executing and I get this output:

```
[cns04.sea3:/glide/cns/ansible/playbook/deploy]$ ansible-playbook junos_config_test.yml --check --diff -i inventory --limit test

PLAY [Test junos_config module] ************************************************

TASK [junos_config ACL test] ***************************************************

[edit firewall family inet]
      filter ISP-INBOUND { ... }
+     filter ANSIBLE-TEST {
+         term ANSIBLE {
+             then accept;
+         }
+         term TEST-TERM-1 {
+             from {
+                 protocol udp;
+             }
+             then {
+                 log;
+                 discard;
+             }
+         }
+     }

changed: [router_name]

PLAY RECAP *********************************************************************
router_name : ok=1    changed=1    unreachable=0    failed=0   
```
I shouldn't see that ANSIBLE term in the diff if those lines execute in the proper order.   I should only see TEST-TERM-1.  Any ideas?

Basically it seems its not honoring the ordering the same case applies when using src: template.

##### STEPS TO REPRODUCE

```yaml
---
- name: Test junos_config module
  gather_facts: no
  connection: local

  vars:
    cli:
      host: "{{ inventory_hostname }}"

  tasks:
    - name: junos_config ACL test
      junos_config:
        provider: "{{ cli }}"
        backup: yes
        lines:
          - set firewall family inet filter ANSIBLE-TEST term ANSIBLE then accept
          - delete firewall family inet filter ANSIBLE-TEST
          - set firewall family inet filter ANSIBLE-TEST term TEST-TERM-1 from protocol udp
          - set firewall family inet filter ANSIBLE-TEST term TEST-TERM-1 then log
          - set firewall family inet filter ANSIBLE-TEST term TEST-TERM-1 then discard

```

##### EXPECTED RESULTS

the ordering of the lines or config to be honored.

##### ACTUAL RESULTS

```

```
