### ISSUE TITLE
lineinfile not idempotent for multiple lines

### ISSUE THREAD

**Issue by ceving** [ansible/ansible#20413]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/xxxxxxxx/ansible/ansible.cfg
  configured module search path = ['./library']
```

##### OS / ENVIRONMENT
Ubuntu 14.04.5 LTS

##### SUMMARY
`lineinfile` is not idempotent for multi-line strings.

##### STEPS TO REPRODUCE
The following task works as expected:
```yaml
---
- name: Disable IP-Filter
  lineinfile:
    dest: /etc/ipf/ipf.conf
    insertafter: '^set intercept_loopback false;'
    line: >-
      pass in quick all
      pass out quick all
    backup: yes
```
It inserts one line:

    set intercept_loopback false;
    pass in quick all pass out quick all

When executed a second time nothing is done.

But the following task does not stop adding lines:

```yaml
---
- name: Disable IP-Filter
  lineinfile:
    dest: /etc/ipf/ipf.conf
    insertafter: '^set intercept_loopback false;'
    line: |-
      pass in quick all
      pass out quick all
    backup: yes
```

Look ahead for more than one line does not seem to work.

##### EXPECTED RESULTS
I expect two new lines:
```
set intercept_loopback false;
pass in quick all
pass out quick all
```

##### ACTUAL RESULTS
But I get two lines for each run. The file after the third run:
```
set intercept_loopback false;
pass in quick all
pass out quick all
pass in quick all
pass out quick all
pass in quick all
pass out quick all
```

**Comment by nitzmahone** [comment]
The regex for lineinfile doesn't handle multi-line matches- you want [blockinfile](https://docs.ansible.com/ansible/blockinfile_module.html)...

**Comment by ceving** [comment]
I don't have a text-block surrounded by markers. I have just two lines.

Blockinfile is no option, because the markers are required:
http://serverfault.com/questions/755934/ansible-blockinfile-disable-marker

**Comment by nitzmahone** [comment]
Regardless, I don't believe lineinfile was written to support multi-line (hence `line` not `lines`). If you have to hack the existing file instead of just templating it, you might want to try two lineinfile tasks, or try to hack the existing `lineinfile` module to support multi-line regex (have you tried an inline multiline signifier in the `regexp` arg?).

**Comment by fthommen** [comment]
Having the same issue here (ansible 2.4) will that definitively not be fixed/changed?

**Comment by garkin** [comment]
```yaml
- name: Update sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: {{ item.regexp }}
    line: {{ item.line }}
    backup: yes
    state: {{ item.state }}
  with_items:
  - regexp: '^MaxSessions\s+(\d+|.+)\s+$'
    line: 'MaxSessions 30'
  - regexp: '^GatewayPorts\s+\(yes|no|clientspecified|.+)\s+$'
    state: absent
  register: SSHD_CONFIG_RESULT

- name: Restart sshd
  systemd: { name: sshd, state: reloaded }
  when: SSHD_CONFIG_RESULT.changed
```
This does not scale, imagine 30 changes. Writes are not atomic. 30 backup files. 
This is not solved by `blockinfile:`.
