### ISSUE TITLE
s3_logging cannot use variable + string or Variable+Variable for argument

### ISSUE THREAD

**Issue by dan-osms** [ansible/ansible#20426]
##### ISSUE TYPE

 - Bug Report
##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 7f17718b82) last updated 2017/01/05 13:54:42 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Mac 10.12.2
##### SUMMARY

s3_logging: 

target_bucket: "{{ item.profile }}"-s3-log    #fails cannot "mesh variable into string
or
target_bucket: "{{ item.profile }}"-"{{ item.log_target }}"    #fails cannot "mesh variable into string
 always complains about quotes ^^ here
##### STEPS TO REPRODUCE

```yaml
  - name: Enable logging of s3 bucket      
    with_items: "{{ list }}"
    tags:
      - logging
    when: ("{{ item.profile }}" == "dev" )
    s3_logging:
      name: "{{ item.bucket }}"
      profile: "{{ item.profile }}"
      region: "{{ item.where }}"
      target_bucket: "{{ item.profile }}"-"{{ item.log_target }}"
      target_prefix: s3_logs/
      state: "{{ item.track }}"
```
Where list provides { profile: "dev", track: "present", name: "bucket", where: "us-east-1", log_target: "-s3-log" } 

Log target exists.

##### EXPECTED RESULTS

Merger of variables to create string for "target_bucket:"
##### ACTUAL RESULTS

The offending line appears to be:

      region: "{{ item.where }}"
      target_bucket: "{{ item.profile }}"-s3-logs
                                         ^ here

```

```
