### ISSUE TITLE
Name of a role may prevent it from being executed in 2.2.0

### ISSUE THREAD

**Issue by theLastTrain** [ansible/ansible#20448]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`roles` in a play

##### ANSIBLE VERSION
```
 #ansible 2.2.0.0
  config file = /home/nutstore/etp-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```yaml
[defaults]
hostfile=hosts
ask_sudo_pass=True
host_key_checking=False

[privilege_escalation]
become=True
become_method=sudo
become_user=root
```

##### OS / ENVIRONMENT
CentOS release 6.8 (Final)

##### SUMMARY
Name of a role can prevent it from running in 2.2.0

##### STEPS TO REPRODUCE
Structure of Ansible dir like this
```
etp-ansible/
├── ansible.cfg
├── group_vars
│   └── target.yml
├── hosts
├── roles
    ├── fail2ban
        ├── files
        │   └── jail.local
        ├── tasks
        │   └── main.yml
        └── tests
            └── main.yml
```

Content of `roles/fail2ban/tasks/main.yml `
```yaml
---
- name: Install package `fail2ban`
  package:
    name: fail2ban
    state: present

- name: Ensure fail2ban path exists
  file:
    dest: /etc/fail2ban
    state: directory
    owner: root
    group: root

- name: Copy jail.local
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644

- name: Restart service fail2ban
  service: name=fail2ban state=restarted
```

Content of `roles/fail2ban/tests/main.yml ` is quite straight forward
```yaml
---
- name: Test suit
  hosts: localhost
  roles:
    - role: ../../fail2ban
```

##### EXPECTED RESULTS
Tasks listed in `tasks/main.yml` should be executed.

##### ACTUAL RESULTS
After I run `ansible-playbook roles/fail2ban/tests/main.yml`, nothing happens:
```shell
PLAY [Test suit] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```   

And `--list-tasks` gives me this
```
playbook: roles/fail2ban/tests/main.yml

  play #1 (localhost): Test suit	TAGS: []
    tasks:
```

However, if I mv `fail2ban\` to `failban\` and change `- role: ../../fail2ban` into `- role: ../../failban`, everything seems fine
```shell
$ ansible-playbook roles/failban/tests/main.yml --list-tasks
playbook: roles/failban/tests/main.yml

  play #1 (localhost): Test suit	TAGS: []
    tasks:
      ../../failban : Install package `fail2ban`	TAGS: []
      ../../failban : Ensure fail2ban path exists	TAGS: []
      ../../failban : Copy jail.local	TAGS: []
      ../../failban : Restart service fail2ban	TAGS: []
```
