### ISSUE TITLE
No error for non-existent handlers when notify is used with include

### ISSUE THREAD

**Issue by vhosakot** [ansible/ansible#20440]
Bug Report:

When "notify" is used with "include" and the handler specified for "notify" does not exist, Ansible does not display any error and the playbook runs fine without failures.

##### COMPONENT NAME
notify, include

##### ANSIBLE VERSION
```
$ ansible --version
ansible 1.9.6
```

##### CONFIGURATION
$ env | grep ANS
ANSIBLE_INSTRUMENT_MODULES=true
ANSIBLE_HOST_KEY_CHECKING=false
ANSIBLE_SSH_ARGS=-F /root/.axion/ssh_config
ANSIBLE_INVENTORY=/root/vFusion/ansible-systems/inventory/fusion/metapod/proxmox/
ANSIBLE_VAULT_PASSWORD_FILE=/root/.config/ansible-systems/vault-proxmox.pass
ANSIBLE_VAR_DEFAULTS_GLOB=/root/vFusion/ansible-systems/inventory/fusion/metapod/defaults/*.yml
ANSIBLE_VARS_PLUGINS=/root/vFusion/ansible-systems/plugins/vars

##### OS / ENVIRONMENT
Red Hat Linux 7.3

##### STEPS TO REPRODUCE

This playbook does not fail.
```
---
- include: test1.yml
  notify: this notify handler does not exist

- include: test2.yml
  notify:
    - this also does not exist
    - this totally is not present anywhere
    - another non-existent notify handler
    - this does not throw any error either
```
##### EXPECTED RESULTS
Errors must be displayed for handlers that do not exist like:
```
Handler "this notify handler does not exist" not found.
```

##### ACTUAL RESULTS
The playbook works fine with no failures.

**Comment by Martin-Temme** [comment]
Hi @vhosakot, 

I was curious and have played around with this a bit on ansible 2.2.1.0.
Looks to my like the problem lies within "include" like "debug" not firing the "notify" module.

**What I did to test this**
_scenario 1_
```
- name: get a missing handler error plx
  file:
    path: "~/Desktop/pleaseDeleteMe"
    state: directory
  notify:
    - this is not an existing handler
    - but this one does
```

**Result**
```
TASK [testingGrounds : get a missing handler error plx] ************************
ERROR! The requested handler 'this is not an existing handler' was not found in either the main handlers list nor in the listening handlers list
```

When I commented out the missing handler it worked fine of course.

However when the "tasks/main.yml" looks like
**this**
_scenario 2_
```
- name: get a missing handler error plx
  include: test.yml
  notify:
    - this is not an existing handler
    - but this one does
```
**or this**
_scenario 3_
```
- name: get a missing handler error plx
  debug: msg="Is this trowing an error?"
  notify:
    - this is not an existing handler
    - but this one does
```

No error is thrown.
Further more if the included file looks like the task in _scenario 1_
the  'this is not an existing handler' error is also thrown.

My best guess is that because "debug" and "include" are not making any changes to the target system ansible does not start the "notify" just as if task had been run before and gave a status of 'nothing to do'
So that would mean it's not really a bug I guess.

**Does this make sense?**
