### ISSUE TITLE
s3_sync module not setting mime_type

### ISSUE THREAD

**Issue by djk** [ansible/ansible#20469]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

s3_sync
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Running Ansible from: macOS 12.2.2, python 2.7 virtualenv.
Managing: Ubuntu 16.04.1 LTS

##### SUMMARY

Using the s3_sync module, all files uploaded to the bucket end up with the binary/octet-stream mime_type. This happens even if I set the `mime_map` option in the module to be specific. 
##### STEPS TO REPRODUCE

Send files to an s3 bucket using the module. Happens every time I use it, with or without `mime_map`.

```yaml
- name: "Upload to S3"
  s3_sync:
    bucket: "{{ s3_bucket }}"
    mode: push
    permission: public-read
    file_root: <redacted>
    file_change_strategy: date_size
    mime_map:
      .js: application/javascript
      .css: text/css
    include: "*"
    key_prefix: assets
```

##### EXPECTED RESULTS

Have the mime types sniffed and set correctly in S3 when uploaded.
##### ACTUAL RESULTS

```
Mime sniffing seems to be working properly (excerpt from verbose output):

```
    {
      "_strategy": "date_size",
      "bytes": 116993,
      "chopped_path": "css/app.css",
      "fullpath": "<redacted>",
      "local_etag": "\"f666848aa7b36065f663cf9ede5dd114\"",
      "mime_type": "text/css",
      "modified_epoch": 1484836418,
      "s3_path": "assets/css/app.css"
    },
    {
      "_strategy": "date_size",
      "bytes": 4811,
      "chopped_path": "img/icon.svg",
      "encoding": null,
      "fullpath": "<redacted>",
      "local_etag": "\"f00992a258303b6b18cfacdd06b28529\"",
      "mime_type": "image/svg+xml",
      "modified_epoch": 1484836389,
      "s3_path": "assets/img/icon.svg"
    },
```
```
