### ISSUE TITLE
Lambda module: add support for env vars

### ISSUE THREAD

**Issue by danvaida** [ansible/ansible#20479]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lambda module

##### ANSIBLE VERSION
n/a

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
The module should support setting environment variables for Lambda functions.
I think there's no arguing about the fact that this feature needs to be supported.
Here's an example of the implementation: https://github.com/pjodouin/ansible-lambda/blob/master/modules/lambda.py

##### STEPS TO REPRODUCE
```yaml
# Create Lambda functions
tasks:
- name: looped creation
  lambda:
    name: '{{ item.name }}'
    state: present
    zip_file: '{{ item.zip_file }}'
    runtime: 'python2.7'
    role: 'arn:aws:iam::987654321012:role/lambda_basic_execution'
    env_vars: "{{ item.env_vars | default(omit) }}"
    handler: 'hello_python.my_handler'
    vpc_subnet_ids:
    - subnet-123abcde
    - subnet-edcba321
    vpc_security_group_ids:
    - sg-123abcde
    - sg-edcba321
  with_items:
    - { name: HelloWorld, zip_file: 'hello-code.zip' }
    - { name: ByeBye, zip_file: 'bye-code.zip' }
    - name: NotSoFast
       zip_file: 'nsf-code.zip'
       env_vars:
         key1: value
         key2: value      
```

##### EXPECTED RESULTS
The env vars are set in an idempotent fashion.

##### ACTUAL RESULTS
The support for this in the current module is not present.
