### ISSUE TITLE
gce_net error on firewall rule update: NoneType object is not iterable

### ISSUE THREAD

**Issue by wyscan** [ansible/ansible#20481]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gce_net

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/rsimmons/work/clearcorrect/provisioning/ansible_env/devinfra/build/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
host_key_checking = False

[ssh_connection]
ssh_args = -F ./ssh.config -o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o CheckHostIP=no
control_path = ~/.ssh/ansible-%%r@%%h:%%p
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When updating a firewall rule in GCE using gce_net, rules without a src_range cause an error.

I believe the problem exists for other attributes of type list.

##### STEPS TO REPRODUCE
Update an existing GCE firewall rule that has an empty list for src_range (beause it uses src_tags). You won't see the error on rule creation, only on update.

##### EXPECTED RESULTS
The rule would either be updated or unchanged.

##### ACTUAL RESULTS
```
"msg": "Unexpected response: ('NoneType' object is not iterable). Detail: Traceback (most recent call last):\n  File \"/tmp/ansible_4iGjcK/ansible_module_gce_net.py\", line 364, in main\n    if sorted(fw.source_ranges) != sorted(src_range):\nTypeError: 'NoneType' object is not iterable\n"
}
```

**Comment by ansibot** [comment]
cc @supertom
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by supertom** [comment]
Hi @wyscan, thanks for flagging the issue (and sending the PR).  Just so I'm clear, could you provide a playbook and/or ad-hoc commands to replicate this.  The following playbook works for me, so I want to be sure I understand the issue correctly.


```
    - name: Create Firewall Rule
      gce_net:
        name: default
        fwname: "{{ fwname }}"
        allowed: tcp:80
        state: "{{ state }}"
        src_tags: "foo,bar"
      register: result
    - name: "assert fw created"
      assert:
        that:
          - 'result.changed'
          - 'result.state == "{{ state }}"'
    - name: Update Firewall Rule
      gce_net:
        name: default
        fwname: "{{ fwname }}"
        allowed: tcp:81
        state: "{{ state }}"
        src_tags: "foo,bar,baz"
        src_range:
      register: result
    -  name: "assert fw updated"
       assert:
         that:
           - 'result.changed'
           - 'result.state == "{{ state }}"'
           - 'result.src_tags|length == 3'
```
'''

**Comment by wyscan** [comment]
Your role does indeed work corectly for me.

If I set any value for target_tags or src_range it gives me an error.  Both of the following cause errors:

```
- name: Create Firewall Rule
  gce_net:
    name: default
    credentials_file: "{{ gce_credentials_file }}"
    service_account_email: "{{ gce_service_account }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ fwname }}"
    allowed: tcp:80
    state: "{{ state }}"
    src_range: '0.0.0.0/0'
  register: result

- name: Create Firewall Rule 2
  gce_net:
    name: default
    credentials_file: "{{ gce_credentials_file }}"
    service_account_email: "{{ gce_service_account }}"
    project_id: "{{ gce_project_id }}"
    fwname: "{{ fwname }}"
    allowed: tcp:80
    state: "{{ state }}"
    target_tags: 'foo'
  register: result
```

It appears that src_tags may be immune to the problem.
