### ISSUE TITLE
Module s3_bucket do not enable versioning

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#20491]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module s3_bucket

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS

##### SUMMARY
Setting s3_bucket versioning option to true do not enable versioning.

##### STEPS TO REPRODUCE

```yaml
---

- set_fact:
    aws_storage_versioning: yes

- name: Create the storage bucket
  s3_bucket:
    name: my-awesome-bucket
    region: '{{ aws_region }}'
    tags:
      environment: '{{ aws_environment }}'
      tier: storage
    versioning: '{{ aws_storage_versioning|bool }}'
    state: present

```

##### EXPECTED RESULTS
Go to AWS console and see versioning enabled.

##### ACTUAL RESULTS
Go to AWS console and see versioning IS NOT enabled.
