### ISSUE TITLE
Using set_fact with delegate_to, delegate_facts and with_items only sets the fact on the first host

### ISSUE THREAD

**Issue by alexjrussell** [ansible/ansible#20508]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Client release 7.3 (Maipo)

##### SUMMARY

In Ansible 2.2.1.0, if you use set_fact, delegate_to and delegate_facts to set facts on several hosts listed in with_items, only the first host in the list will have the fact set.  In all other versions of Ansible 2.x, the fact will be set on all hosts.

##### STEPS TO REPRODUCE

Create a playbook like this:
```yaml
---

- hosts: localhost
  tasks:
  - name: "Set fact on localhost"
    set_fact:
      my_test_fact: "Hello"

  - name: "Copy fact to other servers"
    set_fact:
      my_test_fact: "{{ my_test_fact }}"
    delegate_to: "{{ item }}"
    delegate_facts: True
    with_items: "{{ groups['all'] }}"
    when: item != "localhost"

- hosts: server1
  gather_facts: True
  tasks:
  - name: "Show fact on server1"
    debug: var=my_test_fact

- hosts: server2
  gather_facts: True
  tasks:
  - name: "Show fact on server2"
    debug: var=my_test_fact
```
I am using a simple inventory file:
```
[server1]
192.168.1.105 ansible_user=admin

[server2]
192.168.1.106 ansible_user=admin
```

##### EXPECTED RESULTS

If I run the playbook with Ansible 2.2.0.0 I get these results:
```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Set fact on localhost] ***************************************************
ok: [localhost]

TASK [Copy fact to other servers] **********************************************
ok: [localhost -> 192.168.1.105] => (item=192.168.1.105)
ok: [localhost -> 192.168.1.106] => (item=192.168.1.106)

PLAY [server1] *****************************************************************

TASK [setup] *******************************************************************
ok: [192.168.1.105]

TASK [Show fact on server1] ****************************************************
ok: [192.168.1.105] => {
    "my_test_fact": "Hello"
}

PLAY [server2] *****************************************************************

TASK [setup] *******************************************************************
ok: [192.168.1.106]

TASK [Show fact on server2] ****************************************************
ok: [192.168.1.106] => {
    "my_test_fact": "Hello"
}

PLAY RECAP *********************************************************************
192.168.1.105              : ok=2    changed=0    unreachable=0    failed=0   
192.168.1.106              : ok=2    changed=0    unreachable=0    failed=0   
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
If I run with Ansible 2.2.1.0, the fact is only set for the first host:
```

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Set fact on localhost] ***************************************************
ok: [localhost]

TASK [Copy fact to other servers] **********************************************
ok: [localhost -> 192.168.1.105] => (item=192.168.1.105)
ok: [localhost -> 192.168.1.106] => (item=192.168.1.106)

PLAY [server1] *****************************************************************

TASK [setup] *******************************************************************
ok: [192.168.1.105]

TASK [Show fact on server1] ****************************************************
ok: [192.168.1.105] => {
    "my_test_fact": "Hello"
}

PLAY [server2] *****************************************************************

TASK [setup] *******************************************************************
ok: [192.168.1.106]

TASK [Show fact on server2] ****************************************************
ok: [192.168.1.106] => {
    "my_test_fact": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
192.168.1.105              : ok=2    changed=0    unreachable=0    failed=0   
192.168.1.106              : ok=2    changed=0    unreachable=0    failed=0   
localhost                  : ok=3    changed=0    unreachable=0    failed=0   

```

The bug seems to be related to a change to plugins/strategy/__init__.py here: https://github.com/ansible/ansible/commit/2d8ebbfe8cc9332b34ce807b1c30e69507ba36a0

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hobgoblinsmaster** [comment]
In fact, delegated_facts seams not to work at all with version 2.2.1.0 (at list the way descrubed in [Delegation, Rolling Updates, and Local Actions](https://docs.ansible.com/ansible/playbooks_delegation.html#delegated-facts).

```
ansible 2.2.1.0
  config file = /tmp/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Config file:
```ini
[defaults]
gathering = smart
# le cache nécessite la version 1.8 minimum
fact_caching = jsonfile
fact_caching_connection = facts_cache
fact_caching_timeout = 86400

nocows = 1
retry_files_enabled = False
remote_user = root
```

playbook:
```yaml
---
- hosts: all
  tags: ['always']
  gather_facts: no
  vars:
    debug: false
  tasks:
    - name: gather facts on all hosts
      setup: gather_subset=!all
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups['all'] }}"
      when: inventory_hostname == ansible_play_hosts[0]

    - debug: var=hostvars[item].ansible_fqdn
      with_items: "{{ groups['all'] }}"
```

Result with version 2.2.0.0:
```
PLAY [all] *********************************************************************

TASK [gather facts on all hosts] ***********************************************
ok: [dedi2.hobgoblins-master.info -> dedi2.hobgoblins-master.info] => (item=dedi2.hobgoblins-master.info)
ok: [dedi2.hobgoblins-master.info -> guenievre.minoza.info] => (item=guenievre.minoza.info)

TASK [debug] *******************************************************************
ok: [dedi2.hobgoblins-master.info] => (item=dedi2.hobgoblins-master.info) => {
    "hostvars[item].ansible_fqdn": "dedi2.hobgoblins-master.info",
    "item": "dedi2.hobgoblins-master.info"
}
ok: [dedi2.hobgoblins-master.info] => (item=guenievre.minoza.info) => {
    "hostvars[item].ansible_fqdn": "guenievre.minoza.info",
    "item": "guenievre.minoza.info"
}

PLAY RECAP *********************************************************************
dedi2.hobgoblins-master.info : ok=2    changed=0    unreachable=0    failed=0
```

Result with 2.2.1.0:
```
PLAY [all] *********************************************************************

TASK [gather facts on all hosts] ***********************************************
ok: [dedi2.hobgoblins-master.info -> dedi2.hobgoblins-master.info] => (item=dedi2.hobgoblins-master.info)
ok: [dedi2.hobgoblins-master.info -> guenievre.minoza.info] => (item=guenievre.minoza.info)

TASK [debug] *******************************************************************
ok: [dedi2.hobgoblins-master.info] => (item=dedi2.hobgoblins-master.info) => {
    "hostvars[item].ansible_fqdn": "guenievre.minoza.info",
    "item": "dedi2.hobgoblins-master.info"
}
ok: [dedi2.hobgoblins-master.info] => (item=guenievre.minoza.info) => {
    "hostvars[item].ansible_fqdn": "VARIABLE IS NOT DEFINED!",
    "item": "guenievre.minoza.info"
}

PLAY RECAP *********************************************************************
dedi2.hobgoblins-master.info : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by egongu90** [comment]
I can confirm the issue:

```
- name: Gather facts for all hosts (if using --limit)
  hosts: all
  serial: '{{ serial|default("0") }}'
  gather_facts: false
  tasks:
    - setup:
      delegate_to: "{{item}}"
      delegate_facts: true
      with_items:
        - "{{ groups.all }}"
- name: Debug delegated facts
  hosts: all
  tasks:
    - name: Debug facts
      debug:
         msg: "{{ hostvars['192.168.100.215']['ansible_' + hostvars['192.168.100.215']['api_interface']]['ipv4']['address'] }}"
```

Expected result:

```
TASK [Debug facts] *************************************************************
ok: [192.168.100.170] => {
    "msg": "192.168.100.215"
```
Actual result:

```
TASK [Debug facts] *************************************************************
ok: [192.168.100.170] => {
    "msg": "192.168.100.170"
}
```

With Ansible 2.1 works as expected

**Comment by samdoran** [comment]
This is still broken in `2.2.0-0.1.rc1` but works properly in `2.1.5.0-0.1.rc1`.

**Comment by dagwieers** [comment]
The problem is not really related to the set_fact module itself. Maybe best to involve the person that was responsible of the change ? @jimi-c 

PS And we should definitely add these (failing) examples to the integration tests too !

**Comment by chrulri** [comment]
I added a comment to the responsible changes in the commit ( 2d8ebbf ) that caused this issue.

Ansible version: Ansible from source, commit ref: 2d8ebbf
Tested with this simplified play:
```yml
- hosts: controller
  tasks:
    - name: "gather data from nodes"
      setup:
      delegate_to: "{{ item }}"
      delegate_facts: true
      with_items: "{{ groups.nodes }}"
    - name: "print ipv4s"
      debug: var=hostvars[item].ansible_all_ipv4_addresses
      with_items: "{{ groups.nodes }}"
```
And using this simplified inventory:
```ini
controller ansible_connection=local
node1      ansible_ssh_host=172.17.2.11
node2      ansible_ssh_host=172.17.2.12

[nodes]
node1
node2
```

Result with commit 2d8ebbf:
```
PLAY [controller] **************************************************************

TASK [setup] *******************************************************************
ok: [controller]

TASK [gather data from nodes] **************************************************
ok: [controller -> None] => (item=node1)
ok: [controller -> None] => (item=node2)

TASK [print ipv4s] *************************************************************
ok: [controller] => (item=node1) => {
    "hostvars[item].ansible_all_ipv4_addresses": [
        "172.17.2.12"
    ],
    "item": "node1"
}
ok: [controller] => (item=node2) => {
    "hostvars[item].ansible_all_ipv4_addresses": "VARIABLE IS NOT DEFINED!",
    "item": "node2"
}
```

Result with same commit, but reverted the three lines:
```
PLAY [controller] **************************************************************

TASK [setup] *******************************************************************
ok: [controller]

TASK [gather data from nodes] **************************************************
ok: [controller -> None] => (item=node1)
ok: [controller -> None] => (item=node2)

TASK [print ipv4s] *************************************************************
ok: [controller] => (item=node1) => {
    "hostvars[item].ansible_all_ipv4_addresses": [
        "172.17.2.11"
    ],
    "item": "node1"
}
ok: [controller] => (item=node2) => {
    "hostvars[item].ansible_all_ipv4_addresses": [
        "172.17.2.12"
    ],
    "item": "node2"
}
```

The reverted changes / lines:
```patch
diff --git a/lib/ansible/plugins/strategy/__init__.py b/lib/ansible/plugins/strategy/__init__.py
index 1d4fee5..7f7a3e6 100644
--- a/lib/ansible/plugins/strategy/__init__.py
+++ b/lib/ansible/plugins/strategy/__init__.py
@@ -483,9 +483,12 @@ class StrategyBase:

                         # if delegated fact and we are delegating facts, we need to change target host for them
                         if original_task.delegate_to is not None and original_task.delegate_facts:
+                            task_vars = self._variable_manager.get_vars(loader=self._loader, play=iterator._play, host=original_host, task=original_task)
+                            self.add_tqm_variables(task_vars, play=iterator._play)
                             item = result_item.get(loop_var, None)
                             if item is not None:
                                 task_vars[loop_var] = item
+                            templar = Templar(loader=self._loader, variables=task_vars)
                             host_name = templar.template(original_task.delegate_to)
                             actual_host = self._inventory.get_host(host_name)
                             if actual_host is None:
```
