### ISSUE TITLE
ModuleArgsParser doesn't recognize action plugins in tasks

### ISSUE THREAD

**Issue by rhcarvalho** [ansible/ansible#20513]
##### ISSUE TYPE
 - Bug Report
 - Or maybe this is a feature request, since the documentation around action plugins is scarce...

##### COMPONENT NAME

`parsing/mod_args.py`

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
  config file = /home/vagrant/src/github.com/openshift/openshift-ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

It is possible to write plays with custom actions that are implemented as modules in a role, but if the action is implemented as an action plugin, the ModuleArgsParser doesn't recognize it.

##### STEPS TO REPRODUCE

```console
$ tree
.
├── action-plugin-new-syntax.yml
├── action-plugin-old-syntax.yml
├── module-new-syntax.yml
├── module-old-syntax.yml
└── roles
    └── myrole
        ├── action_plugins
        │   └── myaction.py
        └── library
            └── mymodule.py

4 directories, 6 files
```

action-plugin-new-syntax.yml:
```yaml
---
- hosts: all
  roles:
    - myrole
  post_tasks:
    - action: myaction
```

action-plugin-old-syntax.yml:
```yaml
---
- hosts: all
  roles:
    - myrole
  post_tasks:
    - myaction:
```

module-new-syntax.yml:
```yaml
---
- hosts: all
  roles:
    - myrole
  post_tasks:
    - mymodule:
```

module-old-syntax.yml:
```yaml
---
- hosts: all
  roles:
    - myrole
  post_tasks:
    - action: mymodule
```

myaction.py:
```python
from ansible.plugins.action import ActionBase

class ActionModule(ActionBase):

    def run(self, tmp=None, task_vars=None):
        if task_vars is None:
            task_vars = dict()

        result = super(ActionModule, self).run(tmp, task_vars)

        # import ipdb; ipdb.set_trace()

        return result
```

mymodule.py:
```python
from ansible.module_utils.basic import AnsibleModule


def main():
    module = AnsibleModule(argument_spec=dict())
    module.exit_json(changed=False)


if __name__ == '__main__':
    main()
```

##### EXPECTED RESULTS

I expected all 4 playbooks to work the same (and do basically nothing).

##### ACTUAL RESULTS

Modules can be called with either new or old syntax, action plugins only work with the **old** syntax.
The new syntax gives:

```console
$ ansible-playbook -i hosts.ini /tmp/ansible-example/action-plugin-new-syntax.yml -vvvv
Using /home/vagrant/src/github.com/openshift/openshift-ansible/ansible.cfg as config file
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/tmp/ansible-example/action-plugin-new-syntax.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  post_tasks:
    - myaction:
      ^ here


The error appears to have been in '/tmp/ansible-example/action-plugin-new-syntax.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  post_tasks:
    - myaction:
      ^ here

```

This seems to be a limitation in [lib/ansible/parsing/mod_args.py](https://github.com/ansible/ansible/blob/e3c95615b2117ab4a5ebb43f1c96272bc252dbb6/lib/ansible/parsing/mod_args.py#L283-L295)
