### ISSUE TITLE
tempalte module failling to apply 'to_nice_yaml' filter on a list variable

### ISSUE THREAD

**Issue by albertomurillo** [ansible/ansible#20529]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Cannot apply a `to_nice_yaml` filter to a list of ip address. Note that this same playbook works well on ansible 2.2.0.0

##### STEPS TO REPRODUCE
template.j2
```
subnets:
  {{ subnets | to_nice_yaml }}
```

test.yaml
```
---
  - hosts: localhost
    connection: local
    vars:
      subnets: "{{ [(ansible_default_ipv4.network + '/' + ansible_default_ipv4.netmask) | ipaddr] }}"
    tasks:
      - name: Create config
        template:
          src: template.j2
          dest: ./config
```

# ansible-playbook test.yaml

##### EXPECTED RESULTS
```
TASK [Create config] ***********************************************************
changed: [localhost] => {"changed": true, "checksum": "50a3b2ac0572ebc8e4fe03a7f40bfabcd222d63c", "dest": "./config", "gid": 20, "group": "staff", "md5sum": "d89ea9ad98dadabf94e53226657c21f8", "mode": "0644", "owner": "albertom", "size": 28, "src": "/Users/albertom/.ansible/tmp/ansible-tmp-1484951820.46-246530977738450/source", "state": "file", "uid": 502}
```

##### ACTUAL RESULTS
```
TASK [Create config] ***********************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "RepresenterError: cannot represent an object: 192.168.1.20/24"}
	to retry, use: --limit @/Users/albertom/github/template/test.retry
```
