### ISSUE TITLE
blockinfile with_items in path doesn't work as expected

### ISSUE THREAD

**Issue by ak5** [ansible/ansible#20556]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

blockinfile

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

ubuntu xenial 16.04 64bit

##### SUMMARY

blockinfile with path: "{{ item }}" and with_items: does not work, however if I use the "dest" alias for "path" instead, it works.

##### STEPS TO REPRODUCE

```yaml
- name: add block to mulitple files
  blockinfile:
    path: "{{ item }}"
    block: |
        myblock
        hello
  with_items:
    - "file1"
    - "file2"
```

##### ACTUAL RESULTS

```
failed: [default] (item=file1) => {"failed": true, "item": "file1", "msg": "unsupported parameter for module: path"}

```
