### ISSUE TITLE
sysctl errors on comments

### ISSUE THREAD

**Issue by hanej** [ansible/ansible#20569]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

sysctl

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /var/lib/awx/jason/management/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Red Hat 6 and 7

##### SUMMARY

When Ansible is reading sysctl files it errors when encountering a comment.

##### STEPS TO REPRODUCE

**Variables**
```yaml
sysctl:
  postgres:
    file: "/etc/sysctl.d/99-postgres.conf"
    params:
      - name: "kernel.sem"
        value: "150 4000 100 400"
      - name: "kernel.shmall"
        value: 4294967296
      - name: "kernel.shmmax"
        value: 4294967296
      - name: "kernel.shmmni"
        value: 2048
```

**Tasks**
```yaml
---
- name: sysctl header
  lineinfile:
    create: yes
    dest: "{{ item.value.file }}"
    owner: root
    group: root
    insertbefore: BOF
    line: "{{ ansible_managed }}"
  with_dict: '{{ sysctl }}'
  when: (item.value.state is defined and item.value.state == 'present') or
         item.value.state is not defined
  tags: [sysctl]

- name: configure sysctl
  sysctl:
    name: "{{ item.1.name }}"
    value: "{{ item.1.value }}"
    sysctl_file: "{{ item.0.file }}"
    reload: yes
  with_subelements:
    - "{{ sysctl }}"
    - params
    - flags:
      skip_missing: yes
  when: (item.0.state is defined and item.0.state == 'present') or
         item.0.state is not defined
  tags: [sysctl]
```

##### EXPECTED RESULTS

The comment header would be applied to the top of the file and then the sysctl parameters would be applied.

##### ACTUAL RESULTS

When Ansible got to the comment in the file it failed.  Removing the comment fixes the issue.

```
Traceback (most recent call last):
  File \"/tmp/ansible_skBeie/ansible_module_sysctl.py\", line 371, in <module>
    main()
  File \"/tmp/ansible_skBeie/ansible_module_sysctl.py\", line 364, in main
    result = SysctlModule(module)
  File \"/tmp/ansible_skBeie/ansible_module_sysctl.py\", line 124, in __init__
    self.process()
  File \"/tmp/ansible_skBeie/ansible_module_sysctl.py\", line 144, in process
    self.read_sysctl_file()
  File \"/tmp/ansible_skBeie/ansible_module_sysctl.py\", line 296, in read_sysctl_file
    k, v = line.split('=',1)
ValueError: need more than 1 value to unpack
```
