### ISSUE TITLE
influxdb_retention_policy: Setting default doesn't alter retention policy

### ISSUE THREAD

**Issue by smalenfant** [ansible/ansible#20573]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
influxdb_retention_policy

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Centos 7.2

##### SUMMARY
There is a default policy called "autogen" created as default, but when using a playbook to change the default using the influxdb_retention_policy role, the default stays on "autogen". I've also deleted "autogen" and the default wasn't getting set. Somehow the document says "default" is required and there is no default value. 

##### STEPS TO REPRODUCE

Variables used :

```
influx_db_telegraf:
  - telegraf

influx_rp_telegraf:
  - { name: daily, default: true, duration: 7d }
  - { name: monthly, default: false, duration: 30d }
  - { name: indefinite, default: false, duration: INF }
```

Task :

```
- name: Create Retention Policy(s)
  influxdb_retention_policy:
    hostname: "{{ ansible_fqdn }}"
    database_name: "{{ item[0] }}"
    port: "{{ influxdb_http_port | default('8086') }}"
    policy_name: "{{ item[1].name }}"
    duration: "{{ item[1].duration | default('0') }}"
    replication: "{{ item[1].replication | default('1') }}"
  #connection: local
  with_nested:
   - "{{ influx_db }}"
   - "{{ influx_rp }}"
```

##### EXPECTED RESULTS

I expected my retention policy to take the "default: True" 

##### ACTUAL RESULTS

```
TASK [influxdb/rp : Create Retention Policy(s)] ********************************
ok: [influx01] => (item=[u'telegraf', {u'default': True, u'duration': u'7d', u'name': u'daily'}])
ok: [influx01] => (item=[u'telegraf', {u'default': False, u'duration': u'30d', u'name': u'monthly'}])
changed: [influx01] => (item=[u'telegraf', {u'default': False, u'duration': u'INF', u'name': u'indefinite'}])

> SHOW RETENTION POLICIES ON "telegraf"
name		duration	shardGroupDuration	replicaN	default
----		--------	------------------	--------	-------
autogen		0s		168h0m0s		1		true
daily		168h0m0s	24h0m0s			1		false
monthly		720h0m0s	24h0m0s			1		false
indefinite	0s		168h0m0s		1		false

```
