### ISSUE TITLE
docker_login

### ISSUE THREAD

**Issue by FlorianLudwig** [ansible/ansible#20581]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
docker_login

##### ANSIBLE VERSION

```
2.2.1.0
```

##### OS / ENVIRONMENT
Linux

##### SUMMARY
Using `docker_login` to log out does not work.

##### STEPS TO REPRODUCE
Copy paste from [documentation example](https://docs.ansible.com/ansible/docker_login_module.html):
```yaml
- name: Log out of DockerHub
  docker_login:
    state: absent
    email: docker@docker.com
```

##### EXPECTED RESULTS
User is removed from ~/.docker/config.json

##### ACTUAL RESULTS
```
{"changed": false, "failed": true, "msg": "unsupported parameter for module: state"}
```
