### ISSUE TITLE
lineinfile module : insertbefore should insert before first match of specified regular expression

### ISSUE THREAD

**Issue by tYYGH** [ansible/ansible#20582]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module lineinfile

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Defaults

##### OS / ENVIRONMENT
Manager host : Archlinux, package ansible-git v2.3.0.28204.61e6e7868c.
Managed hosts: Archlinux.

##### SUMMARY
Same as:
* https://github.com/ansible/ansible/issues/15824 on `ansible/ansible`, but it got closed because the issue had to be reported in `ansible/ansible-modules-core` instead ;
* https://github.com/ansible/ansible-modules-core/issues/3648 on `ansible/ansible-modules-core`, still open, but locked because now issues must be reported in `ansible/ansible` :-D

For consistency, and because that’s what’s needed in real life (PAM, SSHD…), insertbefore must insert before the *first* occurrence of the regexp, not the last!

##### STEPS TO REPRODUCE
```yaml
- name: configure PAM auth
  lineinfile:
    path: '/etc/pam.d/system-auth'
    regexp: '^{{ item }}\s.*ldap'
    line: '{{ item }} sufficient pam_ldap.so'
    insertbefore: '^{{ item }}\s.*required'
  with_items:
    - auth
    - account
    - password
```

##### EXPECTED RESULTS
```
*auth sufficient pam_ldap.so*
auth      required  pam_unix.so     try_first_pass nullok
auth      optional  pam_permit.so
auth      required  pam_env.so

account sufficient pam_ldap.so
account   required  pam_unix.so
account   optional  pam_permit.so
account   required  pam_time.so

password sufficient pam_ldap.so
password  required  pam_unix.so     try_first_pass nullok sha512 shadow
password  optional  pam_permit.so
```

##### ACTUAL RESULTS
```
auth      required  pam_unix.so     try_first_pass nullok
auth      optional  pam_permit.so
*auth sufficient pam_ldap.so*
auth      required  pam_env.so

account sufficient pam_ldap.so
account   required  pam_unix.so
account   optional  pam_permit.so
account   required  pam_time.so

password sufficient pam_ldap.so
password  required  pam_unix.so     try_first_pass nullok sha512 shadow
password  optional  pam_permit.so
```
