### ISSUE TITLE
get_url gives: 'function' object has no attribute 'urlsplit'.

### ISSUE THREAD

**Issue by xuchen81** [ansible/ansible#20585]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
Latest devel branch
$ ansible --version
ansible 2.3.0

```

##### OS / ENVIRONMENT

Mac OS: 10.11.6
Vagrant: 1.9.1

##### STEPS TO REPRODUCE

```yaml
- name: Download Python 3.4.3
  get_url:
    url: "https://www.python.org/ftp/python/3.4.3/Python-3.4.3.tgz"
    dest: /usr/local/src/
  become: true
```

##### ACTUAL RESULTS

```
TASK [common : Download Python 3.4.3] ******************************************
fatal: [xxxx-local.xxx.xxxx.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to localhost closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_QVe93o/ansible_module_get_url.py\", line 437, in <module>\r\n    main()\r\n  File \"/tmp/ansible_QVe93o/ansible_module_get_url.py\", line 358, in main\r\n    filename = url_filename(info['url'])\r\n  File \"/tmp/ansible_QVe93o/ansible_module_get_url.py\", line 192, in url_filename\r\n    fn = os.path.basename(urlparse.urlsplit(url)[2])\r\nAttributeError: 'function' object has no attribute 'urlsplit'\r\n", "msg": "MODULE FAILURE", "rc": 0}

```
