### ISSUE TITLE
After upgrading from 2.2.0 to 2.2.1 on Centos7.3.1611 , Ansible fails  to find handlers using include (referenced from an included task)

### ISSUE THREAD

**Issue by levequej** [ansible/ansible#20603]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
I tried forcing handler_includes_static = True in ansible.cfg without success (even though I already added static:yes to the include task in handlers)

##### OS / ENVIRONMENT
Centos7.3.1611

##### SUMMARY
upgrading from 2.2.0 to 2.2.1 on Centos7  broke notification from indluded handlers

similar to https://github.com/ansible/ansible/issues/13485 , but not exactly the same

My exact same code broke after yum update , when updating from ansible 2.2.0 to ansible 2.2.1 on Centos 7.3.1611

ERROR! The requested handler '*********' was not found in either the main handlers list nor in the listening handlers list

NB : if the handler is a simple command, it works fine. Only handlers that are doing "include" are failing.

NB: I don't know if the fact that the notify is made from  within an included task has anything to do with the problem but this is my scenario.

##### STEPS TO REPRODUCE

with a directory structure as follows
```
myrole/handlers/main.yml
                mypackage_postinstall_handler.yml
myrole/tasks/main.yml
             install_my_package.yml
```

and code like that in *myrole/tasks/main.yml*
```yaml
- include: install_my_package.yml
```
with code like that in *install_my_package*

```yaml
- name: install package
  yum:
    name: "mypackage"
    state: present
  notify: postinstall mypackage
```

 and code like that in *myrole/handlers/main.yml*
```yaml
# I tired adding static: yes , but it made no difference
- name: postinstall mypackage
  include: mypackage_postinstall_handler.yml
  static: yes
````

then it fails  with:
```
ERROR! The requested handler 'postinstall mypackage' was not found in either the main handlers list nor in the listening handlers list
```

Thing is also that because package is installed, handler won't be notified on next run, and the whole play is useless.

Is there any workaround ?  I am afraid to be forced to rewrite all my  handlers with something like register stuff, then  when stuff.changed

##### EXPECTED RESULTS
working handlers
##### ACTUAL RESULTS
handler is not found

**Comment by ryansb** [comment]
@bcoca this looks like an includes issue, but I'm not sure how to test it.

**Comment by nuklea** [comment]
Same issue on 2.2.1. I have `roles/project/handlers/main.yml`:

```yml
- name: Prepare static files
  include: static.yml

- name: Restart uwsgi service
  include: uwsgi.yml
```
and `roles/project/tasks/main.yml`:

```yml
- name: Clone project repository
  git:
    repo: git@bitbucket.org:company/project.git
    dest: "{{ home_dir }}"
    accept_hostkey: yes
  notify:
    - Prepare static files
    - Restart uwsgi 
```

I've run playbook and got:

```
ERROR! The requested handler 'Restart uwsgi service' was not found in either the main handlers list nor in the listening handlers list
```

but `Prepare static files` handler works fine 😳

Ansible 2.2.0 works fine for all handlers.
