### ISSUE TITLE
Any way to force SSH session to reconnect with pipelining=true ?

### ISSUE THREAD

**Issue by carn1x** [ansible/ansible#20604]
The following tasks fail with `pipelining=true`, since the `docker` user group applied in the first has no effect on the existing SSH session used for both tasks:
```
- name: Add ubuntu user to docker group
  become: true
  user: name=ubuntu
        groups=docker
        append=yes

- name: Pull Docker load test image
  docker_image:
    name: "{{ docker_image }}"
    tag: "{{ docker_image_tag }}"
    force: true
```

I've attempted to use https://galaxy.ansible.com/udondan/ssh-reconnect/ however this appears to be too limited (for instance ignores ansible private key setting).
