### ISSUE TITLE
stdout_callback: debug does not always wrap the newlines as expected

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#20602]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
plugins/callbacks/debug.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### CONFIGURATION
Inside `ansible.cfg`:
```
[defaults]
stdout_callback = debug
```
##### OS / ENVIRONMENT
* Bug **present** on Fedora 23-25 or RedHat 7.3
* Bug **not present** on: MacOS 10.12 or Ubuntu
Both tested using Python 2.7

##### SUMMARY
It seems that, at least on Fedora, the escaped newlines are not converted to normal newlines by the `debug` stdout callback, this being its main purpose: to make the output more human friendly (old name was `human_long.py`)

##### STEPS TO REPRODUCE
Try to run this sample playbook
```
#!/usr/bin/env ansible-playbook -i localhost, -v
---
- name: sample playbook
  hosts: localhost
  gather_facts: no
  vars:
      ansible_connection: local
      base_dir: "{{ base_dir }}"
  tasks:

    - name: "This is the sample task name"
      shell: |
         echo "1\n2\n3"
         echo "error 1\nerror 2\nerror 3" >&2
```

##### EXPECTED RESULTS
To see each stdout and stderr line on their own lines (not joined into a single line and separated by `\n`)

##### ACTUAL RESULTS
```
PLAY [sample playbook] *********************************************************

TASK [This is the sample task name] ********************************************
changed: [localhost] => {
    "changed": true,
    "cmd": "echo \"1\\n2\\n3\"\n echo \"error 1\\nerror 2\\nerror 3\" >&2",
    "delta": "0:00:00.003724",
    "end": "2017-01-24 14:06:31.806755",
    "rc": 0,
    "start": "2017-01-24 14:06:31.803031",
    "warnings": []
}

STDOUT:

1\n2\n3


STDERR:

error 1\nerror 2\nerror 3


PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
