### ISSUE TITLE
Unable to interpolate variable when used as the key of a dict object

### ISSUE THREAD

**Issue by dmizelle** [ansible/ansible#20613]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Using sensu_check, but I fear its not actually caused by the module.

##### ANSIBLE VERSION

Broken version:
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Working version:
```
ansible 2.2.1.0 (detached HEAD fe33c937c4) last updated 2017/01/24 15:51:00 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 48a3ce1223) last updated 2017/01/24 15:51:02 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 4e720b48ae) last updated 2017/01/24 15:51:02 (GMT -400)
  config file = /home/devon/git/arin/ansible/ansible.cfg
  configured module search path = ['library']
```
##### CONFIGURATION

```
[defaults]
roles_path=./roles:./galaxy_roles
library         = library
ansible_managed = Ansible managed: Do NOT edit this file manually!
retry_files_enabled = False
```
```
$ export | grep ANSIBLE
ANSIBLE_VAULT_PASSWORD_FILE=[redacted]
```

##### OS / ENVIRONMENT

OS Running Ansible:
```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.10
DISTRIB_CODENAME=yakkety
DISTRIB_DESCRIPTION="Ubuntu 16.10"
```

Host being managed, vagrant+virtualbox:
```
[vagrant@centos7 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
```

##### SUMMARY

Background:

In order to get around this bug:
https://github.com/ansible/ansible/issues/17892

We've needed to run ansible from a detached HEAD state until a stable release was pushed for 2.2.10.

Now that that's happened, we're seeing issues where using variable interpolation / moustaches in keys of dicts in YAML are failing.

I'm not sure if there has been a regression since this detached commit to v.2.2.1.0, or if I was somehow unknowingly abusing a bug.

##### STEPS TO REPRODUCE

The task:
```yaml
  - name: Deploy Sensu-client Checks
    sensu_check:
      aggregate: "{{ item.value.aggregate | default('false') }}"
      command: "{{ item.value.command }}"
      custom: "{{ item.value.custom | default(omit) }}"
      dependencies: "{{ item.value.dependencies | default(omit) }}"
      handle: "{{ item.value.handle | default('true') }}"
      handlers: "{{ item.value.handlers | default('default') }}"
      interval: "{{ item.value.interval | default(30) }}"
      metric: "{{ item.value.metric | default('false') }}"
      name: "{{ item.key }}"
      occurrences: "{{ item.value.occurrences | default(3) }}"
      path: "{{ item.value.path | default('/etc/sensu/conf.d/checks.json') }}"
      source: "{{ item.value.source | default(ansible_fqdn) }}"
      standalone: "{{ item.value.standalone | default('true') }}"
      state: "{{ item.value.state | default('present') }}"
      subscribers: "{{ item.value.subscribers | default(['sensu']) }}"
      subdue_begin: "{{ item.value.subdue_begin | default(omit) }}"
      subdue_end: "{{ item.value.subdue_end | default(omit) }}"
      timeout: "{{ item.value.timeout | default(10) }}"
    with_dict:
      "{{ sensu_base_checks }}"
    notify: restart sensu-client
    tags:
      - monitoring
```

The defaults/main.yml:
```yaml
sensu_base_checks:
  "Swap_Usage_on_{{ ansible_fqdn }}":
    command: "{{ sensu_plugin_dir }}/check-swap-percent.rb"
    handlers:
      - 'logstash'
      - 'pagerduty'
```

##### EXPECTED RESULTS

Working version output:
```
TASK [Deploy Sensu-client Checks] **********************************************
changed: [centos7.example.dev] => (item={'key': u'Swap_Usage_on_{{ ansible_fqdn }}', 'value': {u'command': u'/opt/sensu/embedded/bin/check-swap-percent.rb', u'handlers': [u'logstash', u'page
rduty']}}) => {"changed": true, "gid": 0, "group": "root", "item": {"key": "Swap_Usage_on_{{ ansible_fqdn }}", "value": {"command": "/opt/sensu/embedded/bin/check-swap-percent.rb", "handlers
": ["logstash", "pagerduty"]}}, "mode": "0644", "msg": "OK", "name": "Swap_Usage_on_centos7.example.dev", "owner": "root", "path": "/etc/sensu/conf.d/checks.json", "reasons": ["`checks' sect
ion did not exist", "check was absent and state is `present'", "`command' did not exist or was different", "`handlers' did not exist or was different", "`subscribers' did not exist or was di
fferent", "`interval' did not exist or was different", "`timeout' did not exist or was different", "`handle' did not exist or was different", "`standalone' did not exist or was different", "
`occurrences' did not exist or was different", "`aggregate' did not exist or was different", "`source' did not exist or was different"], "secontext": "unconfined_u:object_r:etc_t:s0", "size"
: 443, "state": "file", "uid": 0}

[vagrant@centos7 ~]$ sed 11q /etc/sensu/conf.d/checks.json 
{
  "checks": {
    "Swap_Usage_on_centos7.example.dev": {
      "handle": true, 
      "timeout": 10, 
      "standalone": true, 
      "interval": 30, 
      "source": "centos7.example.dev", 
      "command": "/opt/sensu/embedded/bin/check-swap-percent.rb", 
```
##### ACTUAL RESULTS

Broken output:
```
TASK [Deploy Sensu-client Checks] **********************************************
changed: [centos7.example.dev] => (item={'key': u'Swap_Usage_on_{{ ansible_fqdn }}', 'value': {u'command': u'/opt/sensu/embedded/bin/check-swap-percent.rb', u'handlers': [u'logstash', u'page
rduty']}}) => {"changed": true, "gid": 0, "group": "root", "item": {"key": "Swap_Usage_on_{{ ansible_fqdn }}", "value": {"command": "/opt/sensu/embedded/bin/check-swap-percent.rb", "handlers
": ["logstash", "pagerduty"]}}, "mode": "0644", "msg": "OK", "name": "Swap_Usage_on_{{ ansible_fqdn }}", "owner": "root", "path": "/etc/sensu/conf.d/checks.json", "reasons": ["`checks' secti
on did not exist", "check was absent and state is `present'", "`command' did not exist or was different", "`handlers' did not exist or was different", "`subscribers' did not exist or was dif
ferent", "`interval' did not exist or was different", "`timeout' did not exist or was different", "`handle' did not exist or was different", "`standalone' did not exist or was different", "`
occurrences' did not exist or was different", "`aggregate' did not exist or was different", "`source' did not exist or was different"], "secontext": "unconfined_u:object_r:etc_t:s0", "size":
 442, "state": "file", "uid": 0}

[vagrant@centos7 ~]$ sed 11q /etc/sensu/conf.d/checks.json 
{
  "checks": {
    "Swap_Usage_on_{{ ansible_fqdn }}": {
      "handle": true, 
      "timeout": 10, 
      "standalone": true, 
      "interval": 30, 
      "source": "centos7.example.dev", 
      "command": "/opt/sensu/embedded/bin/check-swap-percent.rb", 
      "occurrences": 3, 
      "subscribers": [
```

**Comment by ansibot** [comment]
cc @andsens
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This has been looked at before, and we attempted to resolve it, with the final decision being that it has unintended side effects that we were not comfortable with:

https://github.com/ansible/ansible/pull/19664

There are some work arounds provided in that pull request that may be of assistance.

Additionally there are probably some other solutions to the problem such as:

```
sensu_base_checks:
    - name: "Swap_Usage_on_{{ ansible_fqdn }}":
      command: "{{ sensu_plugin_dir }}/check-swap-percent.rb"
      handlers:
        - 'logstash'
        - 'pagerduty'
```

And then:

```
- name: Deploy Sensu-client Checks
    sensu_check:
      [...]
      metric: "{{ item.metric | default('false') }}"
      name: "{{ item.name }}"
      occurrences: "{{ item.occurrences | default(3) }}"
      [...]
    with_items:
      "{{ sensu_base_checks }}"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
