### ISSUE TITLE
lineinfile module: unsupported parameter for module: path

### ISSUE THREAD

**Issue by ecranfill** [ansible/ansible#20611]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lineinfile

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

lineinfile fails with:

fatal: [192.168.254.4]: FAILED! =>{"failed": true, "msg": "unsupported parameter for module: path"}

##### STEPS TO REPRODUCE

```yaml
---
- name:  Append excludes to /etc/yum.conf
  lineinfile:
    path: /etc/yum.conf
    line: 'exclude=check_mk cuda'
...


```

##### EXPECTED RESULTS
I expected the module to append text to end of /etc/yum.conf as it did with ansible 2.2.0

##### ACTUAL RESULTS

```
fatal: [192.168.254.4]: FAILED! =>{"failed": true, "msg": "unsupported parameter for module: path"}
```
