### ISSUE TITLE
Idempotence problems with win_nssm's app_parameters

### ISSUE THREAD

**Issue by strangeman** [ansible/ansible#20625]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_nssm module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
current devel branch
```
##### ENVIRONMENT
* Windows 2016, Windows 2012
* NSSM 2.24 64-bit

##### SUMMARY
`win_nssm` module have two problems with `app_parameters`: extra space added if only one noname (`_`) parameter added, and extra quotes added for the named parameters

##### STEPS TO REPRODUCE
For first, I added extra output for win_nssm module with old `nssm_single_line_app_parameters` line (see https://github.com/strangeman/ansible/commit/a61bc4c8af78ea276ab5d1ab0e9f0559969e5adb).

After that I reproduced a first path of the issue with the task (I ran the same task twice to test idempotency):

```yaml
- name: create Aurora service
  win_nssm:
    name: "Aurora"
    application: "some\path\to\the.exe"
    state: started
    app_parameters:
      _: console
```
Task output:
```yaml
changed: [test16.test.com] => {"changed": true, "changed_by": "update_app_parameters", "item": {"name": "ServerManager"}, "nssm_app_parameters": "@{_=console}", "nssm_app_parameters_keys": ["_"], "nssm_app_parameters_parsed": {"_": "console"}, "nssm_app_parameters_vals": ["console"], "nssm_single_line_app_parameters": "console ", "old_nssm_single_line_app_parameters": "console"}
```
As you see, `"nssm_single_line_app_parameters"` was `"console "` (with space at end), but `"old_nssm_single_line_app_parameters"` was `"console"` (without space). Looks like NSSM automatically deletes ending spaces.

Then, I tested second part of the issue with the task (ran twice too):
```yaml
- name: create Aurora service
  win_nssm:
    name: "Aurora"
    application: "some\path\to\the.exe"
    state: started
    app_parameters:
      _: console
      "--name": 'ServerManager'
```
Task output:
```yaml
changed: [test16.test.com] =>{"changed": true, "changed_by": "update_app_parameters", "item": {"name": "ServerManager"}, "nssm_app_parameters": "@{--name=ServerManager; _=console}", "nssm_app_parameters_keys": ["_", "--name"], "nssm_app_parameters_parsed": {"--name": "ServerManager", "_": "console"}, "nssm_app_parameters_vals": ["console", "ServerManager"], "nssm_single_line_app_parameters": "console --name \"ServerManager\"", "old_nssm_single_line_app_parameters": "console --name ServerManager"}
```
As you see, Ansible passing `console --name \"ServerManager\"` string to NSSM, but it cuts quotes.

##### EXPECTED RESULTS
Tasks should be idempotent when runs twice with the same parameters.

##### ACTUAL RESULTS
Tasks are not idempotent when runs twice with the same parameters.
