### ISSUE TITLE
systemd module doesn't handle template unit files

### ISSUE THREAD

**Issue by afeld** [ansible/ansible#20621]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

`systemd`

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /Users/aidanfeldman/dev/GSA/d2d/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Also tested d6cdd9151169a52d42c01ebe00d9cc30c30e465c.

##### CONFIGURATION

```
$ cat ansible.cfg
[defaults]
vault_password_file = vault_pass.txt
```

##### OS / ENVIRONMENT

Control machine: OSX 10.12.3

Remote machine: RHEL 7.1

##### STEPS TO REPRODUCE

Paraphrased from https://github.com/silpion/ansible-tomcat.

```
# tomcat@.service
[Service]
ExecStart=java \
  -Djava.util.logging.config.file=/srv/tomcat/catalina/%i/conf/logging.properties \
  ...
```

```yaml
# install-tomcat.yml
- name: Install tomcat service template
  copy:
    src: tomcat@.service
    dest: /etc/systemd/system/tomcat@.service
- name: Start tomcat service
  tags: tomcat
  become: true
  systemd:
    state: started
    enabled: true
    name: tomcat@tomcat
```

##### EXPECTED RESULTS

I expected the service to be started successfully.

##### ACTUAL RESULTS

```
TASK [Start tomcat service] *******************************
failed: [...] (item={u'name': u'tomcat'}) => {"failed": true, "item": {"name": "tomcat"}, "msg": "Unable to enable service tomcat@tomcat: Failed to issue method call: No such file or directory\n"}
```

---

While I am new to the Ansible codebase, I think the issue is that [`sysv_exists()`](https://github.com/ansible/ansible/blob/a715d03a832032562f16f07cc1833414982bd051/lib/ansible/module_utils/service.py#L45-L46) is expecting the unit name to match the filename, when in fact it should also try and truncate the instance name (the part after the `@`) to find the corresponding template name. From [the systemd documentation](https://www.freedesktop.org/software/systemd/man/systemd.unit.html):

> If systemd looks for a unit configuration file, it will first search for the literal unit name in the file system. If that yields no success and the unit name contains an "`@`" character, systemd will look for a unit template that shares the same name but with the instance string (i.e. the part between the "`@`" character and the suffix) removed. Example: if a service `getty@tty3.service` is requested and no file by that name is found, systemd will look for `getty@.service` and instantiate a service from that configuration file if it is found.

Thanks!

##### Additional references

* https://www.digitalocean.com/community/tutorials/understanding-systemd-units-and-unit-files#creating-instance-units-from-template-unit-files
* https://fedoramagazine.org/systemd-template-unit-files/
