### ISSUE TITLE
async + vsphere_guest issue

### ISSUE THREAD

**Issue by temtemtemtem** [ansible/ansible#20639]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

async
vsphere_guest

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

Default except for using host variables

##### OS / ENVIRONMENT

Running on CentOS 7.3 and managing ESXi 6.0.0 systems

##### SUMMARY

I want to start the set of async tasks and then check their status inside "until" loop.
During the checking ansible fails with error "'dict object' has no attribute 'ansible_job_id'"
Nearly same problem like [here](https://github.com/ansible/ansible/issues/12254)

##### STEPS TO REPRODUCE

```yaml
  tasks:
  - name: add test host (fire and forget)
    vsphere_guest:
      vcenter_hostname: srv-vcenter01.ansible.local
      username: administrator@vsphere.ansible.local
      password: password
      guest: "{{item.hostname}}"
      from_template: yes
      template_src: temp-win-2k12-r2
      esxi:
        datacenter: Ansible-DC
        hostname: srv-esx02.ansible.local
      vm_extra_config:
        folder: VMs
    with_items: "{{ serverlist }}"
    async: 1800
    poll: 0
    register: sleeper1

  - name: check fire and forget
    async_status:
      jid: "{{ sleeper1.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 30

```

##### EXPECTED RESULTS

No errors

##### ACTUAL RESULTS

```
TASK [add test host (fire and forget)] *****************************************
ok: [localhost] => (item={u'ip': u'192.168.11.32', u'hostname': u'srv-wintesthost03'})
ok: [localhost] => (item={u'ip': u'192.168.11.33', u'hostname': u'srv-wintesthost04'})

TASK [check fire and forget] ***************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'ansible_job_id'
The error appears to have been in '/playbooks/vmware/temp/multiple_winhost_from_template.yml': line 25, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  - name: check fire and forget
    ^ here
"}

```
(I replaced all "\n" with actual newlines)

**Comment by joe90p** [comment]
Also having this issue. Here are the tasks to reproduce.

```yml
- name: Start platform topology flows
  shell: '{{ storm_path }}/bin/storm jar {{ topologies_base }}/{{curiosity_service_jar}} {{ item.value }} {{ item.key }} {{ ps_environment }} {{ zookeeper_servers_list }}  -c nimbus.host={{ nimbus_host }} {{ storm_config_args }}'
  with_dict: "{{ topology_lookup|default({}) }}"
  when: (topology_start is undefined) or (topology_start is defined and topology_start == item.key)
  register: topology_deploy
  async: 7200
  poll: 0
   environment:
     STORM_JAR_JVM_OPTS: "{{ storm_jar_jvm_opts }}"
   tags:
   - topology
   - load_all
   - curiosity
   - curiosity-service
   - topology_single
 
- name: Wait for topology deploy to complete
  async_status: jid={{ item.ansible_job_id }}
  register: topology_jobs
  until: topology_jobs.finished
  retries: 300
  with_items: topology_deploy.results
```
@temtemtemtem did you resolve your issue?
