### ISSUE TITLE
Error: cannot import name IPAMConfig with docker_service module

### ISSUE THREAD

**Issue by scne** [ansible/ansible#20634]
##### ISSUE TYPE
Bug

##### COMPONENT NAME
docker_service_module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
ubntu 16.04 LTS

##### SUMMARY
Whene I try to use docker_service module I get an error about docker-compose.
In my machine I've install docker, docker-compose and docker has port 4243 enabled for API

```
---
- hosts: all
  user: root
  vars:
    username: claudio
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    public_key: ~/.ssh/id_rsa.pub
  tasks:
    - name: cloning repo
      become: yes
      become_user: manager
      git:
        repo=git@bitbucket.org:xxxxx/xxxxxxxxxxx.git
        dest=/home/manager/project
        accept_hostkey=yes
        version=master
        force=yes
           recursive=no
           key_file=/home/manager/.ssh/id_rsa
- hosts: local
  user: root
  vars:
    username: claudio
    password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    public_key: ~/.ssh/id_rsa.pub
  tasks:
    - name: docker system
      become: yes
      become_user: manager
      docker_service:
        project_src: /home/manager/project/conf_default
        state: present

```

##### ACTUAL RESULTS
```
Using /home/manager/project/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [xxx.xxx.xxx.xxx]
ok: [xxx.xxx.xxx.xxx]

TASK [cloning repo] ************************************************************
ok: [xxx.xxx.xxx.xxx] => {"after": "4ff912eaf4a81f83ebf19ef5e871ac15c9ff9177", "before": "4ff912eaf4a81f83ebf19ef5e871ac15c9ff9177", "changed": false, "warnings": []}
ok: [xxx.xxx.xxx.xxx] => {"after": "4ff912eaf4a81f83ebf19ef5e871ac15c9ff9177", "before": "4ff912eaf4a81f83ebf19ef5e871ac15c9ff9177", "changed": false, "warnings": []}

PLAY [local] *******************************************************************

TASK [setup] *******************************************************************
ok: [xxx.xxx.xxx.xxx]

TASK [docker system] ***********************************************************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to load docker-compose. Try `pip install docker-compose`. Error: cannot import name IPAMConfig"}
	to retry, use: --limit @/home/manager/control-methods/ansible/provision.retry

PLAY RECAP *********************************************************************
xxx.xxx.xxx.xxx             : ok=2    changed=0    unreachable=0    failed=0   
xxx.xxx.xxx.xxx            : ok=3    changed=0    unreachable=0    failed=1 

```
