### ISSUE TITLE
Letsencrypt Certificate public key must be different than account key

### ISSUE THREAD

**Issue by andrewhowdencom** [ansible/ansible#20638]
_From @codegastudio on November 12, 2016 9:3_

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Letsencrypt

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

MacOS Sierra to Ubuntu 14.04.2 LTS trusty

##### SUMMARY

Follow steps describe in [letsencrypt_module](https://docs.ansible.com/ansible/letsencrypt_module.html) and get error

>  Error creating new cert :: Certificate public key must be different than account key

At first run, i get error during ' letsencrypt step two'.
At second run, error appear during ' letsencrypt step one'.
At any time crt file is created.
curl access fine to challenge.

##### STEPS TO REPRODUCE

```
---
- stat: path=/home/{{ user }}/ssl/{{ inventory_hostname }}.key
  register: rsa_key_file
  tags: letsencrypt 


- stat: path=/home/{{ user }}/ssl/{{ inventory_hostname }}.csr
  register: csr_file
  tags: letsencrypt 
  

- name: create letsencrypt SSL repository
  file: >
    path=/home/{{ user }}/ssl 
    state=directory 
    mode=0755 
    owner={{ user }} 
    group={{ user }} 
  tags: letsencrypt  

- name: generate RSA key
  command: openssl genrsa -out /home/{{ user }}/ssl/{{ inventory_hostname }}.key 2048  
  when: rsa_key_file.stat.exists == False
  
  
- name: change KEY owner
  file: >
    path=/home/{{ user }}/ssl/{{ inventory_hostname }}.key 
    owner={{ user }} 
    group={{ user }}
  tags: letsencrypt   


- name: generate CSR 
  command: openssl req -new -sha256 -key /home/{{ user }}/ssl/{{ inventory_hostname }}.key -out /home/{{ user }}/ssl/{{ inventory_hostname }}.csr -passin pass:{{ letsencrypt.csr_pass_phrase }} -subj {{ letsencrypt.csr_subj }}
  when: csr_file.stat.exists == False
  tags: letsencrypt  
  
- name: change CSR owner
  file: path=/home/{{ user }}/ssl/{{ inventory_hostname }}.csr owner={{ user }} group={{ user }}
  tags: letsencrypt   


- name: letsencrypt step one
  letsencrypt: >
    account_key=/home/{{ user }}/ssl/{{ inventory_hostname }}.key 
    csr=/home/{{ user }}/ssl/{{ inventory_hostname }}.csr 
    dest=/home/{{ user }}/ssl/{{ inventory_hostname }}.crt 
    remaining_days={{ letsencrypt.ssl_days_duration }} 
    account_email={{ letsencrypt.account_email }}
  register: sample_com_challenge
  tags: letsencrypt 

- name: create letsencrypt challenge data repository
  file: >
    path=/home/{{ user }}/challenges/{{ sample_com_challenge['challenge_data'][ inventory_hostname]['http-01']['resource'] | dirname }} 
    state=directory 
    mode=0755 
    owner={{ user }} 
    group={{ user }} 
    recurse=yes
  tags: letsencrypt 
  

- name: copy challenge data in directory
  copy: >
    dest=/home/{{ user }}/challenges/{{ sample_com_challenge['challenge_data'][ inventory_hostname]['http-01']['resource'] }}
    content="{{ sample_com_challenge['challenge_data'][inventory_hostname]['http-01']['resource_value'] }}"
    owner={{ user }} 
    group={{ user }}
  when: sample_com_challenge|changed
  tags: letsencrypt 

  
- name: letsencrypt step two
  letsencrypt: >
    account_key=/home/{{ user }}/ssl/{{ inventory_hostname }}.key
    csr=/home/{{ user }}/ssl/{{ inventory_hostname }}.csr
    dest=/home/{{ user }}/ssl/{{ inventory_hostname }}.crt
    data={{ sample_com_challenge }}
    remaining_days={{ letsencrypt.ssl_days_duration }} 
    account_email={{ letsencrypt.account_email }}
  when: sample_com_challenge
  tags: letsencrypt
```

##### ACTUAL RESULTS

**letsencrypt step two** (first run)
```
fatal: [mydomain.com]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "account_email": "account email",
            "account_key": "/path/to/mydomain.com.key",
            "acme_directory": "https://acme-staging.api.letsencrypt.org/directory",
            "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf",
            "challenge": "http-01",
            "csr": "/path/to/mydomain.com.csr",
            "data": {
                "authorizations": [
                    {
                        "challenges": [
                            {
                                "status": "pending",
                                "token": "3lrXt6Z4BoiG1-chtNQN5qp1NpZSPxsqMO_fXrsVkUg",
                                "type": "dns-01",
                                "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/hoWJesKjyhFDejgmLdr5OeYw0DnjNxu4Q3km6MvO5C4/16834820"
                            },
                            {
                                "status": "pending",
                                "token": "fmbH41Un6qNaAscvfWRgTjeyqepRGC5bE75Ok5tlrW8",
                                "type": "http-01",
                                "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/hoWJesKjyhFDejgmLdr5OeYw0DnjNxu4Q3km6MvO5C4/16834821"
                            },
                            {
                                "status": "pending",
                                "token": "WLsp235f8mMR6vDMFSKvPFD4ksb3Ih-6cLExV2nZuo0",
                                "type": "tls-sni-01",
                                "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/hoWJesKjyhFDejgmLdr5OeYw0DnjNxu4Q3km6MvO5C4/16834822"
                            }
                        ],
                        "combinations": [
                            [
                                1
                            ],
                            [
                                2
                            ],
                            [
                                0
                            ]
                        ],
                        "expires": "2016-11-19T08:50:42.20041263Z",
                        "identifier": {
                            "type": "dns",
                            "value": "mydomain.com"
                        },
                        "status": "pending",
                        "uri": "https://acme-staging.api.letsencrypt.org/acme/authz/hoWJesKjyhFDejgmLdr5OeYw0DnjNxu4Q3km6MvO5C4"
                    }
                ],
                "cert_days": -1,
                "challenge_data": {
                    "mydomain.com": {
                        "dns-01": {
                            "resource": "_acme-challenge",
                            "resource_value": "IcS0IrdJ1Y18Ss0E751NsxQW2Pac9HqHPVLYr95CE4s"
                        },
                        "http-01": {
                            "resource": ".well-known/acme-challenge/fmbH41Un6qNaAscvfWRgTjeyqepRGC5bE75Ok5tlrW8",
                            "resource_value": "fmbH41Un6qNaAscvfWRgTjeyqepRGC5bE75Ok5tlrW8.oBDu6v-YxqIYLfJ80VhCzjYW2UyoK9P6HuZP0IkENAc"
                        }
                    }
                },
                "changed": true
            },
            "dest": "/path/to/mydomain.com.crt",
            "remaining_days": 365
        },
        "module_name": "letsencrypt"
    },
    "msg": "Error new cert: CODE: 400 RESULT: {\n  \"type\": \"urn:acme:error:malformed\",\n  \"detail\": \"Error creating new cert :: Certificate public key must be different than account key\",\n  \"status\": 400\n}"
}
```

**letsencrypt step one** (second run)
```
fatal: [mydomain.com]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "account_email": "account email",
            "account_key": "/path/to/mydomain.com.key",
            "acme_directory": "https://acme-staging.api.letsencrypt.org/directory",
            "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf",
            "challenge": "http-01",
            "csr": "/path/to/mydomain.com.csr",
            "data": null,
            "dest": "/path/to/mydomain.com.crt",
            "remaining_days": 365
        },
        "module_name": "letsencrypt"
    },
    "msg": "Error new cert: CODE: 400 RESULT: {\n  \"type\": \"urn:acme:error:malformed\",\n  \"detail\": \"Error creating new cert :: Certificate public key must be different than account key\",\n  \"status\": 400\n}"
}
```

_Copied from original issue: ansible/ansible-modules-extras#3444_

**Comment by andrewhowdencom** [comment]
_From @ansibot on November 13, 2016 9:59_



@mgruener ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andrewhowdencom** [comment]
_From @ansibot on November 29, 2016 9:40_

@mgruener, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andrewhowdencom** [comment]
_From @ansibot on December 7, 2016 15:45_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by andrewhowdencom** [comment]
I have duplicated this issue from the previous repository, as it appears to still be the case with the current version of Ansible, and @codegastudio did an excellent job of writing up the steps to reproduce.

**Comment by gundalow** [comment]
Would you be interested in raising a PR to fix this?
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/letsencrypt.py

**Comment by andrewhowdencom** [comment]
I would be interested, but I think it's unlikely I will be able to contribute due to time constraints. Sorry :( I have developed a playbook using Xenolf/Lego, but if we start hitting the constraints of that (it's a bit hacky) I'll revisit this with the view to submitting a PR.

This will likely be a while.

**Comment by gundalow** [comment]
needs_contributor Need someone to have a look at fixing this

**Comment by andrewhowdencom** [comment]
Yeah sorry dude, not even close to looking at it!

**Comment by gundalow** [comment]
@andrewhowdencom That's totally understandable. It's got the `waiting_on_contributor` label now, so if anyone looks at this issue it's clear that help is welcome.

**Comment by flowerysong** [comment]
This is not a bug.in the module, though probably the documentation could be clearer if multiple people have tried to use it incorrectly. The account_key is used to sign the ACME requests and it must not be the same as the private key for the requested cert; this is enforced by the ACME server.  Here's a working example:

```yaml
---

- name: Create account key
  command: openssl genrsa -out /var/tmp/letsencrypt_account.key 4096
  args:
    creates: /var/tmp/letsencrypt_account.key

- name: Create certificate storage directory
  file:
    dest: /etc/pki/collab/private
    owner: root
    group: mail
    mode: 0750
    state: directory

- name: Create certificate key
  command: "openssl genrsa -out /etc/pki/collab/private/{{ certificate }}.key 4096"
  args:
    creates: "/etc/pki/collab/private/{{ certificate }}.key"
  register: result

- name: Generate CSR
  command: "openssl req -new -sha256 -key /etc/pki/collab/private/{{ certificate }}.key -out /var/tmp/{{ certificate }}.csr -subj /CN={{ certificate }}"
  when: result | changed

- name: ACME step one
  letsencrypt:
    account_email: "letsencrypt@devnull.mail.umich.edu"
    account_key: /var/tmp/letsencrypt_account.key
    challenge: dns-01
    csr: "/var/tmp/{{ certificate }}.csr"
    dest: "/etc/pki/collab/private/{{ certificate }}.crt"
  register: acme_data

- name: You challenge me, sirrah?
  route53:
    command: create
    overwrite: yes
    wait: yes
    zone: "{{ subd }}"
    record: "{{ acme_data.challenge_data[certificate]['dns-01']['resource'] }}.{{ certificate }}"
    type: TXT
    value: "\"{{ acme_data.challenge_data[certificate]['dns-01']['resource_value'] }}\""
    ttl: 30
  when: acme_data | changed

- name: ACME step two
  letsencrypt:
    account_key: /var/tmp/letsencrypt_account.key
    challenge: dns-01
    csr: "/var/tmp/{{ certificate }}.csr"
    dest: "/etc/pki/collab/private/{{ certificate }}.crt"
    data: "{{ acme_data }}"
```
