### ISSUE TITLE
rhn_register not parsing serverURL in /etc/sysconfig/rhn/up2date

### ISSUE THREAD

**Issue by gkspranger** [ansible/ansible#20652]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rhn_register

##### ANSIBLE VERSION
```bash
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
allow_world_readable_tmpfiles = True

##### OS / ENVIRONMENT
rhel 6
osx

##### SUMMARY
when using rhn_register, am getting an error about non-existent Config dictionary
i verified that the serverURL value is present in the file /etc/sysconfig/rhn/up2date

##### STEPS TO REPRODUCE
use the rhn_register module with an activation key and do not provide the server_url param .. it *should* find it in the up2date file

```yaml
- name: register with RHN Base Key
  rhn_register: >
    state=present
    activationkey="{{ rhn_base_key }}"
#    server_url="https://xmlrpc.rhn.redhat.com/XMLRPC"
#    i added the server_url as a workaround
```

##### EXPECTED RESULTS
i expected there not to be an error and that the module would auto-find that serverURL value in the noted up2date file

##### ACTUAL RESULTS
```
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_rob6iG/ansible_module_rhn_register.py\", line 411, in <module>\r\n    main()\r\n  File \"/tmp/ansible_rob6iG/ansible_module_rhn_register.py\", line 361, in main\r\n    module.params['server_url'] = rhn.config.get_option('serverURL')\r\n  File \"/tmp/ansible_rob6iG/ansible_module_rhn_register.py\", line 153, in get_option_default\r\n    if key in self.dict:\r\nAttributeError: Config instance has no attribute 'dict'\r\n",
    "msg": "MODULE FAILURE"
```
