### ISSUE TITLE
vsphere_guest - vm_extra_config: hardware virtualization not being set

### ISSUE THREAD

**Issue by Trezamere** [ansible/ansible#20663]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vsphere_guest - vm_extra_config

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/devops/infrastructure/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Also present in 2.2.0

##### CONFIGURATION
[defaults]
deprecation_warnings=False
gathering=smart
host_key_checking=False
remote_user=vagrant
retry_files_enabled=False

[privilege_escalation]
become=True
become_method=sudo
become_user=root

[ssh_connection]
pipelining=True
ssh_args=-o ForwardAgent=yes

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The vm_extra_config option does not appear to be working as expected and is not being applied / updating the .vmx file.  

Specifically I'm looking to enable hardware virtualization on the VM and it appears my best option is to use the vm_extra_config and set the flag in the vmx directly.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: all
  connection: local
  user: remote
  sudo: false

  vars_prompt:
    - name: "vcenter_hostname"
      prompt: "Enter vcenter hostname"
      private: no
      default: "vcenter"
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
      default: "administrator@vsphere.local"
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes

  vars:
    datacenter: "PG Rack"
    esxi_host: "{{ host }}"

  tasks:
    - vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        guest: "{{ inventory_hostname }}"
        resource_pool: "/Resources/{{ resource_pool | default(omit) }}"
        state: present
        validate_certs: no
        vm_extra_config: {
            "notes": "{{ notes | default('Created by Ansible') }}",
            "vhv.enable": "TRUE",
            "annotation": "THIS IS A TEST"
          }
        vm_disk:
          disk1:
            size_gb: "{{ disk | default(20) }}"
            type: thick
            datastore: "{{ datastore }}"
        vm_nic:
          nic1:
            type: vmxnet3
            network: "{{ network | default('VM Network') }}"
            network_type: standard
        vm_hardware:
          memory_mb: 2048
          num_cpus: 2
          osid: ubuntu64Guest
          scsi: paravirtual
          vm_cdrom:
            type: "iso"
            iso_path: "{{ iso_path }}"
        esxi:
          datacenter: "{{ datacenter }}"
          hostname: "{{ esxi_host }}"
      register: guest
```

Will need to specify valid `vcenter_hostname`, `vcenter_user`, `vcenter_pass`, `iso_path`, `datastore`, `datacenter`, and `esxi_host` values.

##### EXPECTED RESULTS
Running the above playbook I expected the VM to be initialized with _Hardware virtualization_ Enabled under the CPU menu in vCenter and the notes to contain "THIS IS A TEST".

##### ACTUAL RESULTS
The machine is initialized with without hardware virtualization and the note is "Created by Ansible".  Checked the *.vmx file and there is no _vhv.enabled = "TRUE"_ or _annotation = "THIS IS A TEST"_ entries.

I added the annotation option as a guess just to see if it would overwrite the 'notes' setting above since looking through the code we explicitly set 'notes' to 'annotation' before setting the rest of the extra config options.  I thought maybe the hardware virtualization setting is weird and can't be updated like that so I thought maybe setting annotation would be a good baseline as well.  Neither showed up in the .vmx file.

I've also tried using native boolean types and many different permutations of creating the dict with different types.
