### ISSUE TITLE
nxos_portchannel: first two portchannells are reported as being created but they did not

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#20684]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_portchannel
##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

Ubuntu 14.04.5 LTS
NXOS: version 7.0(3)I4(1)
##### SUMMARY

I'm trying to create portchannels on a pair of Nexus 9372. Lets say we want to create 4 portchannels on both devices, so there will be 8 similar ansible tasks. 
Every time I run my playbook ansible reports (ok) for first two portchannels as if they were being created early. So ansible does nothing for those two portchannels. Remaining 6 tasks it processes perfectly

##### STEPS TO REPRODUCE

```yaml
#hosts
[n9k]
n9k1 
n9k2 
  
[n9k:vars]
ansible_connection=local
username=ansible
password=ansible
---------------------------------------------------------

#nxos-portchannel.yml
---

- name: Manage VPCs
  hosts: n9k 

  tasks:
    - name: create portchannels
      nxos_portchannel:
        group: "{{ item.group }}"
        members: "{{ item.int }}"
        mode: "{{ item.mode }}"
        state: present
        host: "{{ inventory_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        transport: nxapi
      with_items: 
          - {int: 'Eth1/25', group: 25, mode: passive}
          - {int: ['Eth1/26', 'Eth1/27'], group: 26, mode: 'active'}
          - {int: 'Eth101/1/10', group: 110, mode: 'passive'}
          - {int: ['Eth101/1/11', 'Eth101/1/12'], group: 111, mode: 'passive'}

```

##### EXPECTED RESULTS

Port-channel created and physical interfaces added into it.
##### ACTUAL RESULTS

nryzhkov@zabbix:~/ansible/nxos$ ansible-playbook nxos-portchannel.yml 

PLAY [Manage VPCs] *************************************************************

TASK [setup] *******************************************************************
ok: [n9k1]
ok: [n9k2]

TASK [create portchannels] *****************************************************
ok: [n9k2] => (item={u'int': u'Eth1/25', u'group': 25, u'mode': u'passive'})
ok: [n9k2] => (item={u'int': [u'Eth1/26', u'Eth1/27'], u'group': 26, u'mode': u'active'})
changed: [n9k1] => (item={u'int': u'Eth1/25', u'group': 25, u'mode': u'passive'})
changed: [n9k2] => (item={u'int': u'Eth101/1/10', u'group': 110, u'mode': u'passive'})
changed: [n9k1] => (item={u'int': [u'Eth1/26', u'Eth1/27'], u'group': 26, u'mode': u'active'})
changed: [n9k2] => (item={u'int': [u'Eth101/1/11', u'Eth101/1/12'], u'group': 111, u'mode': u'passive'})
changed: [n9k1] => (item={u'int': u'Eth101/1/10', u'group': 110, u'mode': u'passive'})
changed: [n9k1] => (item={u'int': [u'Eth101/1/11', u'Eth101/1/12'], u'group': 111, u'mode': u'passive'})

PLAY RECAP *********************************************************************
n9k1                       : ok=2    changed=1    unreachable=0    failed=0   
n9k2                       : ok=2    changed=1    unreachable=0    failed=0   

```
on the Nexuses we can validate the result
N9K1# show port-channel summary 
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
25    Po25(SD)    Eth      LACP      Eth1/25(D)   
26    Po26(SD)    Eth      LACP      Eth1/26(D)   Eth1/27(D)   
110   Po110(SD)   Eth      LACP      Eth101/1/10(D)  
111   Po111(SD)   Eth      LACP      Eth101/1/11(D)  Eth101/1/12(D)  
999   Po999(SU)   Eth      LACP      Eth1/53(P)   Eth1/54(P)   


N9K2# sh port-channel summary 
--------------------------------------------------------------------------------
Group Port-       Type     Protocol  Member Ports
      Channel
--------------------------------------------------------------------------------
110   Po110(SD)   Eth      LACP      Eth101/1/10(D)  
111   Po111(SD)   Eth      LACP      Eth101/1/11(D)  Eth101/1/12(D)  
999   Po999(SU)   Eth      LACP      Eth1/53(P)   Eth1/54(P)   

You can see that n9k2 is missing 2 portchannels

This is not a question about nexuses itself . If I change their order in the inventory file, or reorder with_items list of portchannels I got the same result - first two tasks are not being performed with no regards to nexus or portchannel numbers.
I've tried to analize this issue with wireshark. First two tasks do request "show run" then recieve it and then do nothing as if those portchannels were being found on the running-config.

POST /ins HTTP/1.1
Accept-Encoding: identity
Content-Length: 145
Host: n9k2:80
User-Agent: ansible-httpget
Connection: close
Content-Type: application/json
Authorization: Basic YW5zaWJsZTp6b2I4b0tvbzNo

{"ins_api": {"chunk": "0", "version": "1.0", "sid": null, "input": "show running-config all", "type": "cli_show_ascii", "output_format": "json"}}HTTP/1.1 200 OK

p.s. I skipped a verbose output for ansible because it has a lot of information but nothing valuable for my issue
I can be wrong though
so this is a -vvvv output for one of the failed tasks foollowed by a successfull task:
ok: [n9k2] => (item={u'int': u'Eth1/25', u'group': 25, u'mode': u'passive'}) => {
    "changed": false, 
    "end_state": {}, 
    "existing": {}, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "config": null, 
            "force": "false", 
            "group": "25", 
            "host": "n9k2", 
            "include_defaults": "False", 
            "members": [
                "Eth1/25"
            ], 
            "min_links": null, 
            "mode": "passive", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": null, 
            "save": false, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": "nxapi", 
            "use_ssl": false, 
            "username": "ansible", 
            "validate_certs": true
        }, 
        "module_name": "nxos_portchannel"
    }, 
    "item": {
        "group": 25, 
        "int": "Eth1/25", 
        "mode": "passive"
    }, 
    "proposed": {
        "group": "25", 
        "members": [
            "Eth1/25"
        ], 
        "mode": "passive"
    }, 
    "updates": []
}
changed: [n9k1] => (item={u'int': u'Eth1/25', u'group': 25, u'mode': u'passive'}) => {
    "changed": true, 
    "end_state": {
        "group": "25", 
        "members": [
            "Ethernet1/25"
        ], 
        "members_detail": {
            "Ethernet1/25": {
                "mode": "passive", 
                "status": "D"
            }
        }, 
        "min_links": "1", 
        "mode": "passive"
    }, 
    "existing": {}, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "config": null, 
            "force": "false", 
            "group": "25", 
            "host": "n9k1", 
            "include_defaults": "False", 
            "members": [
                "Eth1/25"
            ], 
            "min_links": null, 
            "mode": "passive", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": null, 
            "save": false, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": "nxapi", 
            "use_ssl": false, 
            "username": "ansible", 
            "validate_certs": true
        }, 
        "module_name": "nxos_portchannel"
    }, 
    "item": {
        "group": 25, 
        "int": "Eth1/25", 
        "mode": "passive"
    }, 
    "proposed": {
        "group": "25", 
        "members": [
            "Eth1/25"
        ], 
        "mode": "passive"
    }, 
    "updates": [
        "interface port-channel25", 
        "interface Eth1/25", 
        "channel-group 25 mode passive"
    ], 
    "warnings": [
        "The proposed port-channel interface did not exist. It's recommended to use nxos_interface to create all logical interfaces."
    ]
}

```
