### ISSUE TITLE
Inconsistent mount when changing mountpoint

### ISSUE THREAD

**Issue by p53** [ansible/ansible#20682]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
mount

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using mount module on first run set name/path variable to some value /mnt/files on second run, change that parameter to different value e.g. /mnt/other, mount is still mounted on the /mnt/files and additionally two values are now in fstab for same device:
/dev/somedev /mnt/files ...
/dev/somedev /mnt/other

##### STEPS TO REPRODUCE
on first run:
```
  mount:
    name: /mnt/files
    src: /dev/sdb
    opts: ''
    fstype: ext4
    dump: 0
    passno: 2
    state: mounted
```

on second run:
```
  mount:
    name: /mnt/other
    src: /dev/sdb
    opts: ''
    fstype: ext4
    dump: 0
    passno: 2
    state: mounted
```

##### EXPECTED RESULTS
either throw error that filesystem is already mounted somewhere else and don't modify fstab
or
remount filesystem and modify fstab, so there is just one correct entry (exception for multiple entries
could be just in case device is mounted with bind option..)

##### ACTUAL RESULTS
```
device mounted on /mnt/files

and in fstab:

/dev/sdb /mnt/files defaults 0 2
/dev/sdb /mnt/other defaults 0 2

```
