### ISSUE TITLE
--check fails on acl task if user doesn't exist

### ISSUE THREAD

**Issue by jan-xyz** [ansible/ansible#20683]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- acl

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
all standard

##### OS / ENVIRONMENT
provision Debian 8 from OSX
provision Debian 8 from Debian 8

##### SUMMARY
One of our tests to merge a pull request is running the playbook with --check. The ACL module fails on Linux if the entity doesn't exist.

##### STEPS TO REPRODUCE
```yaml
---
    - name: set ACL for user doesnt_exist
      acl:
        path: "{{ item }}"
        entity: doesnt_exist
        etype: user
        permissions: rw-
        state: present
      with_items:
        - /opt/sectret_folder
```
##### EXPECTED RESULTS
When I run --check I would like to have a defined output. skipping the task when the user doesn't exist would be fine.

##### ACTUAL RESULTS
```
19:01:06 failed: [192.168.56.101] (item=/opt/sectret_folder) => {"cmd": "/bin/setfacl --test -m user: doesnt_exist:rw- /opt/sectret_folder", "failed": true, "item": "/opt/sectret_folder", "msg": "setfacl: Option -m: Invalid argument near character 6", "rc": 2, "stderr": "setfacl: Option -m: Invalid argument near character 6\n", "stdout": "", "stdout_lines": []}
```
