### ISSUE TITLE
Installing a key with rpm_key does not really import it

### ISSUE THREAD

**Issue by cubranic** [ansible/ansible#20711]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rpm_key 
yum_repository

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No changes

##### OS / ENVIRONMENT
Running from MacOS, installing in a Centos 7 VM.

##### SUMMARY
After I run `yum_repository` and `rpm_key` to add a yum repository and (presumably) import its GPG key, I still can't install package from the repository because `yum` complains that it can't verify its `respond.xml`: `Gpg Keys not imported, cannot verify repomd.xml for repo {...}`.

##### STEPS TO REPRODUCE

```yaml
    - name: add Grafana repository
      yum_repository:
        name: grafana
        description: Grafana YUM repo
        baseurl: https://packagecloud.io/grafana/stable/el/$releasever/$basearch/
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: https://packagecloud.io/gpg.key https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana
        sslverify: yes
        sslcacert: /etc/pki/tls/certs/ca-bundle.crt

    - name: add the repository keys
      rpm_key:
        key: "{{ item }}"
        state: present
      with_items:
        - https://packagecloud.io/gpg.key
        - https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana

    - name: install Grafana package
      yum: name=grafana
```

##### EXPECTED RESULTS
Package `grafana` is installed.

##### ACTUAL RESULTS
```
TASK [add Grafana repository] **************************************************
ok: [node0.vagrant.test] => {"changed": false, "repo": "grafana", "state": "present"}

TASK [add the repository keys] *************************************************
ok: [node0.vagrant.test] => (item=https://packagecloud.io/gpg.key) => {"changed": false, "item": "https://packagecloud.io/gpg.key"}
ok: [node0.vagrant.test] => (item=https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana) => {"changed": false, "item": "https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana"}

TASK [install Grafana package] *************************************************
fatal: [node0.vagrant.test]: FAILED! => {"changed": false, "failed": true, "msg": "Failure talking to yum: failure: repodata/repomd.xml from grafana: [Errno 256] No more mirrors to try.\nhttps://packagecloud.io/grafana/stable/el/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for grafana"}
```

**Comment by cubranic** [comment]
I find I need to force the import of the new repo key(s) by running `yum makecache` for that repo:

```yaml
    - name: update repo cache for the new repo
      command: yum -q makecache -y --disablerepo=* --enablerepo=grafana
```

**Comment by ansibot** [comment]
cc @hacosta
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cubranic** [comment]
Disregard my last comment, the `makecache` workaround doesn't seem to work reliably. So the issue stands as reported.

**Comment by tronicum** [comment]
i have an similar issue running on rhel7. it seems yum is asking to import key. i will create a extra issue for that.

**Comment by tronicum** [comment]
@cubranic try running
rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n'
then install the key manual (rpmkeys --import URL)
run rpm -q gpg-pubkey --qf '%{name}-%{version}-%{release} --> %{summary}\n' again.
for some strange reasons (on my bug). If i install the key manual it works and i have the key installed twice. i wonder if RPM has mutiple locations or trust levels on those keys....

**Comment by hany** [comment]
I'm having the *exact* same issue with the same repo as well. I wonder if it's an issue with this repo/GPG key as opposed to Ansible.

**Comment by dmitryzykov** [comment]
I'm having the same issue with this repo service (packagecloud.io) but another repo:
https://packagecloud.io/prometheus-rpm/release 
https://github.com/lest/prometheus-rpm

```yaml
- name: add prometheus repo key
  rpm_key:
    state: present
    key: "{{ item }}"
    validate_certs: yes
  with_items:
    - https://packagecloud.io/prometheus-rpm/release/gpgkey
    - https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm

- name: add prometheus repository
  yum_repository:
    name: prometheus
    description: Repository with Prometheus RPM packages for CentOS 7
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/7/$basearch
    gpgkey: https://packagecloud.io/prometheus-rpm/release/gpgkey
    gpgcheck: yes
    repo_gpgcheck: yes
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- name: install prometheus
  yum:
    name: prometheus
    state: installed
```

```bash
TASK [prometheus : install prometheus repo key] ********************************
ok: [10.2.77.2] => (item=https://packagecloud.io/prometheus-rpm/release/gpgkey)
ok: [10.2.77.2] => (item=https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm)

TASK [prometheus : add prometheus repository] **********************************
ok: [10.2.77.2]

TASK [prometheus : install prometheus] *****************************************
fatal: [10.2.77.2]: FAILED! => {"changed": false, "failed": true, "msg": "Failure talking to yum: failure: repodata/repomd.xml from prometheus: [Errno 256] No more mirrors to try.\nhttps://packagecloud.io/prometheus-rpm/release/el/7/x86_64/repodata/repomd.xml: [Errno -1] repomd.xml signature could not be verified for prometheus"}

```
But if I will try to install it manually from console, I will get key add confirmation after which package will be installed successfully 

```bash
[root@zabbix1 yum.repos.d]# yum install prometheus
Loaded plugins: fastestmirror
base                                                                                                                                  | 3.6 kB  00:00:00
centos-gluster38                                                                                                                      | 2.9 kB  00:00:00
elrepo                                                                                                                                | 2.9 kB  00:00:00
epel/x86_64/metalink                                                                                                                  |  10 kB  00:00:00
extras                                                                                                                                | 3.4 kB  00:00:00
icinga-stable-release                                                                                                                 | 2.5 kB  00:00:00
pgdg94                                                                                                                                | 4.1 kB  00:00:00
prometheus/x86_64/signature                                                                                                           |  836 B  00:00:00
Retrieving key from https://packagecloud.io/prometheus-rpm/release/gpgkey
Importing GPG key 0x7457CCD1:
 Userid     : "https://packagecloud.io/prometheus-rpm/centos (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: d7df c575 af4b 92c6 e62a d3c5 f721 6757 7457 ccd1
 From       : https://packagecloud.io/prometheus-rpm/release/gpgkey
Is this ok [y/N]: y
...
Installed:
  prometheus.x86_64 0:1.5.2-1.el7.centos

```

**My workaround for this problem**
```yaml
- name: update yum package cache for prometheus repo
  shell: yum -q makecache -y --disablerepo='*' --enablerepo=prometheus
  changed_when: false
```

**Comment by tronicum** [comment]
are you using a proxy? i was behind a corporate proxy and maybe it is not set in some modules?

**Comment by dmitryzykov** [comment]
No, I didn't use proxy. My connection is direct.

**Comment by austinbutler** [comment]
@dmizyk's workaround also works for me with Grafana.

**Comment by lastsky** [comment]
all you need is `update_cache`.

~~~
    - name: install repo file
      copy: src=files/node-any/{{ item }} dest=/{{ item }} mode=0644
      with_items:
        - etc/yum.repos.d/grafana.repo
        - etc/yum.repos.d/prometheus.repo

    - name: import rpm keys
      rpm_key: state=present key={{ item }}
      with_items:
         - https://packagecloud.io/prometheus-rpm/release/gpgkey
         - https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm
         - https://packagecloud.io/gpg.key
         - https://grafanarel.s3.amazonaws.com/RPM-GPG-KEY-grafana

    - name: install or update rpm packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
          - grafana
          - fontconfig
          - initscripts
          - prometheus
          - alertmanager
~~~

**Comment by giovtorres** [comment]
I'm getting the same error and `update_cache` did not work for me.  While searching for a resolution to this issue, I am noticing a trend where the repo is hosted with packagecloud.io, which sign their repodata.  I use `rpm_key` in other modules, but haven't come across this issue with those.

I used the `rpm_key` module to add the gpg key from packagecloud twice in a row and registered the output just to verify that changed=true is in the first output and changed=false is in the second.

Before the `rpm_key` task runs, I checked for gpg packages:
```
[vagrant@localhost ~]$ rpm -qa \*gpg\*
libgpg-error-1.12-3.el7.x86_64
gpgme-1.3.2-5.el7.x86_64
pygpgme-0.3-9.el7.x86_64
```

In my case, I'm trying to install varnish using the repo from packagecloud.io.  After running the `rpm_key` task, I run `yum: name=varnish state=present` and get the `[Errno -1] repomd.xml signature could not be verified for varnishcache_varnish41`, similar to what others have been reporting.

I rerun the check for gpg packages and now I get:
```
[vagrant@localhost ~]$ rpm -qa \*gpg\*
libgpg-error-1.12-3.el7.x86_64
gpg-pubkey-cbf5c49e-57bed102
gpgme-1.3.2-5.el7.x86_64
pygpgme-0.3-9.el7.x86_64
```

There's the packagecould gpg key for the varnish repo.  However, when I run `yum info` on it, it asks again to import the gpg key:

```
[vagrant@localhost ~]$ yum info gpg-pubkey-cbf5c49e-57bed102
Loaded plugins: fastestmirror
varnishcache_varnish41/x86_64/signature                                                                  |  836 B  00:00:00     
Retrieving key from https://packagecloud.io/varnishcache/varnish41/gpgkey
Importing GPG key 0xCBF5C49E:
 Userid     : "https://packagecloud.io/varnishcache/varnish41 (https://packagecloud.io/docs#gpg_signing) <support@packagecloud.io>"
 Fingerprint: 9c96 f9ca 0dc3 f4ea 78ff 3328 34bf 6e8e cbf5 c49e
 From       : https://packagecloud.io/varnishcache/varnish41/gpgkey
Is this ok [y/N]:
```

Interestingly enough, `rpm -qi gpg-pubkey-cbf5c49e-57bed102` does report the PGP key as if though it is installed in the rpmdb.

With EPEL, for example, I don't get the same error.  I could do `rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7` and then do `yum install htop` and I won't get prompted to import the key.

Doing `rpm --import https://packagecloud.io/varnishcache/varnish41/gpgkey` manually and then `yum install varnish` does prompt me again to import the GPG key, even though it shouldn't since the key was ostensibly imported already.  So, it doesn't appear this is a problem directly related to Ansible.

Still haven't figured out why this is the case.  Moreover, disabling `repo_gpgcheck` in the yum task does get past this, but I want to keep the gpg verification on.

My workaround, as other suggested, was to add the following in between adding the repository and installing the package:

```
- name: import gpg key
  rpm_key:
    key: "https://packagecloud.io/varnishcache/varnish{{ varnish_ver }}/gpgkey"
    state: present
  register: import_key
                                                                                                       
- name: Make cache
  command: "yum -q makecache -y --disablerepo='*' --enablerepo='varnishcache_varnish{{ varnish_ver }}'"
  when: import_key.changed
```

This should make it idempotent, but I get a nasty warning from Ansible: **[WARNING]: Consider using yum module rather than running yum**.
