### ISSUE TITLE
Persistent Connections: raw with unicode arg and output

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#20710]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
persistent connection manager

##### ANSIBLE VERSION
```

```

##### STEPS TO REPRODUCE

```yaml
- hosts: "{{ hosts }}"
  gather_facts: no
  serial: 1
  tasks:

  ### raw with unicode arg and output

  - name: raw with unicode arg and output
    raw: echo 汉语
    register: command
  - name: check output of raw with unicode arg and output
    assert:
      that:
      - "'汉语' in command.stdout"
      - command | changed # as of 2.2, raw should default to changed: true for consistency w/ shell/command/script modules
```
If the above doesn't copy correctly you can find it in `ansible/test/integration/targets/connection/test_connection.yml`

Running with `ANSIBLE_USE_PERSISTENT_CONNECTIONS`
##### ACTUAL RESULTS
```
TASK [raw with unicode arg and output] ********************************************************************************************************************************************************************************************************
fatal: [local-pipelining]: FAILED! => {"changed": true, "failed": true, "rc": 255, "stderr": "Traceback (most recent call last):\n  File \"/home/johnb/git/ansible-inc/ansible/bin/ansible-connection\", line 184, in run\n    (rc, stdout, stderr) = self.conn.exec_command(cmd)\n  File \"/home/johnb/git/ansible-inc/ansible/lib/ansible/plugins/connection/local.py\", line 72, in exec_command\n    display.vvv(u\"EXEC {0}\".format(cmd), host=self._play_context.remote_addr)\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 5: ordinal not in range(128)\n", "stdout": "", "stdout_lines": []}
```
