### ISSUE TITLE
iptables: invert of the uid_owner parameter

### ISSUE THREAD

**Issue by miglen** [ansible/ansible#20747]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
module/iptables

##### ANSIBLE VERSION
ansible 2.2.0.0

##### CONFIGURATION
nothing special

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Having a "!" argument to invert the uid_owner parameter will allow to use the module when we want to have explicit rule for all users except one. In my example below I want to block the EC2 metadata service in AWS and not I'm able to do that with iptables module.

##### STEPS TO REPRODUCE
Example task:
```
- name: Block EC2 metadata service for all except root
  iptables:
    chain: OUTPUT
    source: 169.254.169.254
    jump: DROP
    uid_owner: ! root
  become: yes
```
##### EXPECTED RESULTS
Rule looks like:
` -A OUTPUT -m owner ! --uid-owner root -d 169.254.169.254 -j DROP`

##### ACTUAL RESULTS
N/A - not implemented
