### ISSUE TITLE
apt_repository fails to enable a disabled apt repository

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#20754]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apt_repository

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/mg/src/mg-infra/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS on the target; Ubuntu 16.10 on the controller

##### SUMMARY

`apt_repository: repo='ppa:pov' state=present` fails to re-enable the apt repository after it's been disabled by Ubuntu's `do-release-upgrade`

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
    # simulate adding a repository and then disabling it during do-release-upgrade
    - copy:
        content: "# deb http://ppa.launchpad.net/pov/ppa/ubuntu xenial main # disabled on upgrade to xenial\n"
        dest: /etc/apt/sources.list.d/ppa_pov_trusty.list
    - apt_repository: repo='ppa:pov' state=present
    - shell: grep -h ^deb /etc/apt/sources.list /etc/apt/sources.list.d/*.list
      register: repos
    - debug: var=repos.stdout_lines
```

##### EXPECTED RESULTS

I expect the repository to be re-enabled.

##### ACTUAL RESULTS

```
PLAY [ranka] *******************************************************************

TASK [copy] ********************************************************************
ok: [ranka]

TASK [apt_repository] **********************************************************
ok: [ranka]

TASK [command] *****************************************************************
changed: [ranka]

TASK [debug] *******************************************************************
ok: [ranka] => {
    "repos.stdout_lines": [
        "deb http://ports.ubuntu.com/ubuntu-ports xenial main universe", 
        "deb-src http://ports.ubuntu.com/ubuntu-ports xenial main universe", 
        "deb http://ports.ubuntu.com xenial-security main", 
        "deb http://ports.ubuntu.com xenial-security universe", 
        "deb http://ports.ubuntu.com xenial-updates main universe"
    ]
}

PLAY RECAP *********************************************************************
ranka                      : ok=4    changed=1    unreachable=0    failed=0   
```
