### ISSUE TITLE
required_if functionality broken

### ISSUE THREAD

**Issue by Harosgr** [ansible/ansible#20762]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module_utils/basic.py

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
It seems that the required_if functionality is broken. Execution continues even though the required_if criteria are not met.

##### STEPS TO REPRODUCE
For example the "mount" module uses the required_if 
```
        required_if=(
            ['state', 'mounted', ['src', 'fstype']],
            ['state', 'present', ['src', 'fstype']]
        )
```
We can try to run the module with state present but without any src or fstype defined
```
- hosts: localhost
  tasks:
    - name: Just a test
      mount:
        state: present
        path: /mnt/foo
```

##### EXPECTED RESULTS
Get a message that the src or fstype arguments are required before proceeding to the actual execution

##### ACTUAL RESULTS
Execution continues
