### ISSUE TITLE
os_quota fails with AttributeError

### ISSUE THREAD

**Issue by rrbarreto** [ansible/ansible#20763]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

os_quota

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Fedora release 22 (Twenty Two)

##### SUMMARY

When using `os_quota` module it fails out with AttributeError

##### STEPS TO REPRODUCE

```yaml
# site.yml
- name: configuring project quota
  hosts: localhost
  roles:
    - os_quota

$ cat roles/os_quota/tasks/main.yml 
---
- os_quota:
    cloud: "{{ os_cloud }}"
    name: "{{ os_project }}"
    cores: "{{ os_quota_cores }}"
    ram: "{{ os_quota_ram }}"
    instances: "{{ os_quota_instances }}"
    floating_ips: "{{ os_quota_floating_ips }}"
    security_group: "{{ os_quota_security_group }}"
    volumes: "{{ os_quota_volumes }}"
    gigabytes: "{{ os_quota_gigabytes }}"
```

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "os_quota"
    }, 
    "module_stderr": "Shared connection to localhost closed.\r\n", 
    "module_stdout": "/usr/lib/python2.7/site-packages/os_client_config/config.py:476: UserWarning: Couldn't find the vendor profile 'os-cloud1', for the cloud 'os-cloud'\r\n  name))\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_cpnlhk/ansible_module_os_quota.py\", line 483, in <module>\r\n    main()\r\n  File \"/tmp/ansible_cpnlhk/ansible_module_os_quota.py\", line 417, in main\r\n    project_quota_output = _get_quotas(cloud, cloud_params['name'])\r\n  File \"/tmp/ansible_cpnlhk/ansible_module_os_quota.py\", line 296, in _get_quotas\r\n    quota['volume'] = _get_volume_quotas(cloud, project)\r\n  File \"/tmp/ansible_cpnlhk/ansible_module_os_quota.py\", line 283, in _get_volume_quotas\r\n    return cloud.get_volume_quotas(project)\r\nAttributeError: 'OperatorCloud' object has no attribute 'get_volume_quotas'\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```
