### ISSUE TITLE
lxc_container: any reliable way of doing clone ?

### ISSUE THREAD

**Issue by sokoow** [ansible/ansible#20803]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lxc_container

##### ANSIBLE VERSION
```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
none, all defaults 

##### OS / ENVIRONMENT
ubuntu 16.10

##### SUMMARY
I'm trying to do a simple lxc clone with ansible.

lxc-clone -s -B overlayfs -n test1-xenial-$(date +%s) zzz_xenial_template

So, equivalent in ansible would be: 
```
  vars:
    containers:
      - name: memcached-1
        service: memcache
      - name: mysql-1
        service: mysql
  
tasks:

    - action: shell whoami
      register: whoami

    - name: Create the containers
      lxc_container:
        name: "{{ item.name }}"
        backing_store: overlayfs
        clone_name: zzz_xenial_template
        clone_snapshot: true
      with_items: "{{ containers }}"
      register: containers_info
```
Right? Wrong! Here's what above code is trying to do:

```
TASK [Create the containers] ***************************************************
failed: [172.17.0.1] (item={u'name': u'memcached-1', u'service': u'memcache'}) => {"command": "/usr/bin/lxc-create --name memcached-1 --quiet --template ubuntu --bdev overlayfs", "err": "", "failed": true, "item": {"name": "memcached-1", "service": "memcache"}, "msg": "Failed executing lxc-create.", "rc": 1}
failed: [172.17.0.1] (item={u'name': u'mysql-1', u'service': u'mysql'}) => {"command": "/usr/bin/lxc-create --name mysql-1 --quiet --template ubuntu --bdev overlayfs", "err": "", "failed": true, "item": {"name": "mysql-1", "service": "mysql"}, "msg": "Failed executing lxc-create.", "rc": 1}
```
Why is it trying to invoke lxc-create instead of lxc-clone, and whaere does it take 'ubuntu' template name from?

##### STEPS TO REPRODUCE
1. Install lxc
2. Follow cookbook up above

##### EXPECTED RESULTS
Same behaviour like calling lxc-clone -s -B overlayfs -n test1-xenial-$(date +%s) zzz_xenial_template command.

##### ACTUAL RESULTS
Check above in problem description

**Comment by ansibot** [comment]
cc @cloudnull
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cloudnull** [comment]
Hello @sokoow, there is a patch in that should resolve the lxc-clone/copy issues https://github.com/ansible/ansible/pull/20373 If you could pull in that patch and retest your playbook it'd be greatly appreciated.

**Comment by sokoow** [comment]
still same on 2.3.0:

```
ansible-playbook -i inventory basic-playbook.yml --extra-vars "ansible_sudo_pass=$(cat ../host-key)"
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This feature will be removed in a future 
release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [lxc-servers] *****************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [172.17.0.1]

TASK [command] *********************************************************************************************************************************************************
changed: [172.17.0.1]

TASK [Create the containers] *******************************************************************************************************************************************
failed: [172.17.0.1] (item={u'name': u'memcached-1', u'service': u'memcache'}) => {"command": "/usr/bin/lxc-create --name memcached-1 --quiet --template ubuntu --bdev overlayfs", "err": "", "failed": true, "item": {"name": "memcached-1", "service": "memcache"}, "msg": "Failed executing lxc-create.", "rc": 1}
failed: [172.17.0.1] (item={u'name': u'mysql-1', u'service': u'mysql'}) => {"command": "/usr/bin/lxc-create --name mysql-1 --quiet --template ubuntu --bdev overlayfs", "err": "", "failed": true, "item": {"name": "mysql-1", "service": "mysql"}, "msg": "Failed executing lxc-create.", "rc": 1}
	to retry, use: --limit @/home/lxc-playbook/basic-playbook.retry

PLAY RECAP *************************************************************************************************************************************************************
172.17.0.1                 : ok=2    changed=1    unreachable=0    failed=1   
```

am I doing something wrong ?

**Comment by cloudnull** [comment]
@sokoow I think we've the wires crossed so I apologize not catching this before. Testing with the following playbook seems to do the right thing, even without the above mentioned patch. 

``` yaml
- name: test playbook
  hosts: localhost
  user: root
  vars:
    containers:
      - name: test-target
        service: test
  tasks:                                                                                                                                                                                                                                                                                                                  
    - name: Create cloned container                                                                                                                                                                                                                                                                                            
      lxc_container:                                                                                                                                                                                                                                                                                                         
        name: container-base
        clone_name: "{{ item.name }}"                                                                                                                                                                                                                                                                
      with_items: "{{ containers }}"                                                                                                                                                                                                                                                                                         
      register: containers_info
```

This playbook has a resulting command of ``"command": "/usr/bin/lxc-clone --backingstore dir --new test-target --orig container-base"`` which seem to work as expected. Essentially the "clone_name" is the name of the container that will be created while the "name" is that of the existing container. 


All this said, It may be time to clarify the docs http://docs.ansible.com/ansible/lxc_container_module.html as I can see it may be a little confusing. Let me know if you're still running into issues with it.
