### ISSUE TITLE
expose 'dest' attribute in s3 module data

### ISSUE THREAD

**Issue by mmmorris1975** [ansible/ansible#20808]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
s3 module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
allow s3 'get' operations to include `dest` attribute in the returned module data so it can be used with register vars to get download path for "ephemeral" files (ex. software packages whose archive can be deleted once installed).  Probably just a simple add of the dest attribute to the `module.exit_json` call in the `download_s3file` function.

##### STEPS TO REPRODUCE
```yaml
- name: download
  s3:
    bucket: my-bucket
    mode: get
    object: /s3/path/to/object.rpm
    dest: /sys/path/to/object.rpm
  register: s3_obj

- name: install
  yum: name={{ s3_obj.dest }} state=present

- name: cleanup
  file: name={{ s3_obj.dest }} state=absent
```

##### EXPECTED RESULTS
package would be installed using `dest` attribute of the registered `s3_obj` var, since destination path and file name may come from variables.

##### ACTUAL RESULTS
```
the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'dest'
```
