### ISSUE TITLE
Support templates in patch module

### ISSUE THREAD

**Issue by perrin4869** [ansible/ansible#20810]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
Patch module

##### SUMMARY
Add an option such as `template=true`, supporting `jinja2` templates like `src=foo.patch.j2`, so that variables become available from inside the patch.

**Comment by ansibot** [comment]
cc @jirutka @luisperlaz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
I advise against it as you just need an extra task to do this, it is not worth the complexity nor maintenance of duplicating the code for templating.

**Comment by perrin4869** [comment]
hm... how would you do this then? Something like this:

```
- template:
    src: /mytemplates/foo.patch.j2
    dest: /tmp/foo.patch
    owner: bin
    group: wheel
    mode: 0644

- name: apply patch to one file
  patch:
    src: /tmp/foo.patch
    dest: /etc/foo
```

I think this would work... I think it isn't 100% ideal to install the patch to the filesystem but I can live with that
