### ISSUE TITLE
znode: kazoo >= 2.1 is required even when installed

### ISSUE THREAD

**Issue by andmos** [ansible/ansible#20816]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module: znode

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
All defaults

##### OS / ENVIRONMENT
Running from Ubuntu 14.04
Provisioning CentOS 7 

##### SUMMARY
When I try to run a task with `znode` I get the following error: 
```
FAILED! => {"changed": false, "failed": true, "msg": "kazoo >= 2.1 is required to use this module. Use pip to install it."}
```
I have installed `kazoo` (among others): 
```
$ pip list
ansible (2.2.1.0)
apt-xapian-index (0.45)
argparse (1.2.1)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
html5lib (0.999)
httplib2 (0.8)
Jinja2 (2.7.2)
jsonpatch (1.3)
jsonpointer (1.0)
kazoo (2.2.1)
keyring (3.5)
Landscape-Client (14.12)
launchpadlib (1.10.2)
lazr.restfulclient (0.13.3)
lazr.uri (1.0.3)
MarkupSafe (0.18)
ntlm-auth (1.0.2)
oauth (1.0.1)
ordereddict (1.1)
PAM (0.4.2)
paramiko (1.10.1)
pip (1.5.4)
prettytable (0.7.2)
pycrypto (2.6.1)
pycurl (7.19.3)
pygobject (3.12.0)
pyOpenSSL (0.13)
pyserial (2.6)
pysphere (0.1.7)
python-apt (0.9.3.5ubuntu1)
python-debian (0.1.21-nmu2ubuntu2)
pyvmomi (6.5)
pywinrm (0.2.2)
PyYAML (3.10)
requests (2.13.0)
requests-ntlm (1.0.0)
SecretStorage (2.0.0)
setuptools (3.3)
simplejson (3.3.1)
six (1.10.0)
ssh-import-id (3.21)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
urllib3 (1.7.1)
wadllib (1.3.2)
wheel (0.24.0)
wsgiref (0.1.2)
xmltodict (0.10.2)
zope.interface (4.0.5)
```

##### STEPS TO REPRODUCE
`pip install kazoo` (On the machine running Ansible itself) 

```
- name: Add Clusterprops.json to {{ zookeeper_hosts }}
  znode:
    hosts: "{{ zookeeper_hosts }}"
    name: /clusterprops.json
    value: {"urlScheme":"https"}
    state: present
  tags: znode
```

##### EXPECTED RESULTS
I expect the znode module to run - if it fails it should fail against Zookeeper or something, not when loading `Kazoo`. 

##### ACTUAL RESULTS

```
TASK [SolrEhrConfig : Add Clusterprops.json to 10.0.110.74] ********************
task path: /vagrant/roles/SolrEhrConfig/tasks/main.yml:9
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/extras/clustering/znode.py
<10.0.110.74> ESTABLISH SSH CONNECTION FOR USER: root
<10.0.110.74> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r 10.0.110.74 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1485765637.49-49317814135987 `" && echo ansible-tmp-1485765637.49-49317814135987="` echo ~/.ansible/tmp/ansible-tmp-1485765637.49-49317814135987 `" ) && sleep 0'"'"''
<10.0.110.74> PUT /tmp/tmpJUGvKx TO /root/.ansible/tmp/ansible-tmp-1485765637.49-49317814135987/znode.py
<10.0.110.74> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r '[10.0.110.74]'
<10.0.110.74> ESTABLISH SSH CONNECTION FOR USER: root
<10.0.110.74> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r 10.0.110.74 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1485765637.49-49317814135987/ /root/.ansible/tmp/ansible-tmp-1485765637.49-49317814135987/znode.py && sleep 0'"'"''
<10.0.110.74> ESTABLISH SSH CONNECTION FOR USER: root
<10.0.110.74> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/home/vagrant/.ansible/cp/ansible-ssh-%h-%p-%r -tt 10.0.110.74 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1485765637.49-49317814135987/znode.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1485765637.49-49317814135987/" > /dev/null 2>&1 && sleep 0'"'"''
fatal: [10.0.110.74]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "hosts": "10.0.110.74",
            "name": "/clusterprops.json",
            "op": null,
            "recursive": false,
            "state": "present",
            "timeout": 300,
            "value": "{'urlScheme': 'https'}"
        },
        "module_name": "znode"
    },
    "msg": "kazoo >= 2.1 is required to use this module. Use pip to install it."
}
```

**Comment by ansibot** [comment]
cc @treyperry
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
please share your playbook - i think you might just need to delegate the znode step in your to localhost, something like the following:


```
- hosts: localhost
  vars:
    replacement_solrconfig_xml: "{{ lookup('file', 'solrconfig.xml') }}"
  tasks:

    - name: set fact zookeeper hosts
      set_fact:
         zk_hosts: "{{ groups['zookeeper'] | join(':' ~ zookeeper_client_port ~ ',') }}:{{ zookeeper_client_port }}"

    - name: replace solrconfig.xml
      znode:
        hosts: "{{ zk_hosts }}"
        name: /configs/documents2017/solrconfig.xml
        state: present
        value: "{{ replacement_solrconfig_xml }}"
      delegate_to: localhost

```

**Comment by andmos** [comment]
The task itself is a part of the role `SolrEhrConfig`:
```
- name: Solr setup
  hosts: solr_hosts
  become: yes
  become_user: root
  roles:
    - role: Java-Linux
    - role: Solr
    - role: SolrEhrConfig
```
So I should try to move out the task itself to the playbook and then run it on localhost?

**Comment by jhawkesworth** [comment]
not looked at the role, but maybe you just need to target the role against localhost in a separate play

```
- name: Solr setup
  hosts: solr_hosts
  become: yes
  become_user: root
  roles:
    - role: Java-Linux
    - role: Solr
- name: Solr configuration
  hosts: localhost
  become: yes
  become_user: root
    - role: SolrEhrConfig
```

**Comment by andmos** [comment]
I added `delegate_to: 127.0.0.1` and that did the trick: 
```
- name: Ensure clusterprops on "{{ zookeeper_hosts }}"
  znode:
    hosts: "{{ zookeeper_hosts }}"
    name: /clusterprops.json
    value: {"urlScheme":"https"}
    state: present
  delegate_to: 127.0.0.1
```
Could keep it in the role itself.
It is not documented in the docs for the module however... 
I want to keep this issue open until the docs gets updated if that is OK?
