### ISSUE TITLE
Error on vmware_host : 'vim.fault.DuplicateName' object has no attribute 'thumbprint'

### ISSUE THREAD

**Issue by daBONDi** [ansible/ansible#20819]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/cloud/vmware/vmware_host

##### ANSIBLE VERSION

```
2.2.1.0
```

##### OS / ENVIRONMENT
Ansiblehost: Ubuntu 16.04
ESX/VSphere: 6.5

##### SUMMARY
Trying to add multiple ESX Host to a VSphere Cluster

##### STEPS TO REPRODUCE

```yaml
- name: "Ensure ESX Host is in vSphere Center and in the vSphere Cluster VMC1"
  hosts: vsphere-vmc1-esx
  connection: local
  vars:
    cluster: "{{vsphere_cluster_default}}"
    datacenter: "{{vsphere_datacenter_default}}"
    vcenterserver: "{{vsphere_default_vcenter}}"
    vsphereuser: "{{vsphere_vmc1_user}}"
    vspherepw: "{{vsphere_vmc1_password}}"
  tasks:
    - name: "debug"
      debug:
        var: vsphere_vmc1_user
    - name: "Add to vCenter"
      vmware_host:
        cluster_name: "{{cluster}}"
        datacenter_name: "{{datacenter}}"
        esxi_hostname: "{{ansible_host}}"
        esxi_username: "{{esxi_username}}"
        esxi_password: "{{esxi_password}}"
        hostname: "{{vcenterserver}}"
        username: "{{vsphereuser}}"
        password: "{{vspherepw}}"
        validate_certs: False
        state: present

```

##### ACTUAL RESULTS
Looks like something is missing in the Module to handle the thumbprint attribute

Looks like same Issue like https://github.com/ansible/ansible-modules-extras/issues/1484
but not resolved.

```
fatal: [fj-p-vmnode1]: FAILED! => {

    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "cluster_name": "vmc1",
            "datacenter_name": "FJ",
            "esxi_hostname": "172.16.125.1",
            "esxi_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "esxi_username": "root",
            "hostname": "172.16.125.200",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "username": "ansible@vsphere.local",
            "validate_certs": false
        },
        "module_name": "vmware_host"
    },
    "msg": "'vim.fault.DuplicateName' object has no attribute 'thumbprint'"
}
```
