### ISSUE TITLE
include_role: The rescue block does not get executed inside a role (nested block)

### ISSUE THREAD

**Issue by spamulap12** [ansible/ansible#20837]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /root/projects/upgrade/nuage-metro/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY
When using include_role to call a role, the rescue block inside the role does not get executed.

##### STEPS TO REPRODUCE
1. Create a role with block and rescue 
2. Use include_role from a playbook to call the role
3. Make sure the rescue part is being executed

```
#This is the playbook using include_role
- name: Deploy Node1 and Node3 with new qcow2 image
    include_role:
      name: deploy
#These are the tasks inside the deploy role
- block:
  - name: task1
    command: "ip route"
  - block:
    - name: copy a file to the qcow2 image
      command: guestfish --rw -a vm1.qcow2 -m /dev/sda2 copy-in /etc/test_file
    - name: Set var if sda2 is the partition
      set_fact: guestfish_mount=/dev/sda2
    rescue:
    - name: copy a file to the qcow2 image
      command: guestfish --rw -a vm1.qcow2 -m /rhel/rootvol copy-in /etc/test_file
    - name: Set var if rhel/rootvol is the partition
      set_fact: guestfish_mount=/dev/rhle/rootvol 
  when: vm not in list_vms
```

##### EXPECTED RESULTS
The vm image I am using does not have sda2 as partition always. So, the rescue block is in place to catch the error.
This is working as expected when running the role individually.

##### ACTUAL RESULTS
But, when calling the role with include_role the role errors out at the sda2 task in the block part. It does not go to rescue part as expected

```

```

**Comment by scurvydoggo** [comment]
We're hitting this issue too, which appears to impact both `2.2.0` and `2.2.1`.

Very interested in a fix, since the workaround using registers is terribly brittle.

**Comment by sivel** [comment]
I cannot reproduce this issue with the following reproducer:

```
- hosts: localhost
  gather_facts: false
  vars:
    vm: foo
    list_vms: []
  tasks:
    - include_role:
        name: role
```

roles/role/tasks/main.yml
```
- block:

    - block:
        - command: "false"
        - debug:
            msg: block
      rescue:
        - command: "true"
        - debug:
            msg: rescue

  when: vm not in list_vms
```

Produces:

```
TASK [role : command] **********************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["false"], "delta": "0:00:00.004292", "end": "2018-05-01 10:07:31.141600", "failed": true, "rc": 1, "start": "2018-05-01 10:07:31.137308", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

TASK [role : command] **********************************************************
changed: [localhost] => {"changed": true, "cmd": ["true"], "delta": "0:00:00.007398", "end": "2018-05-01 10:07:31.530486", "rc": 0, "start": "2018-05-01 10:07:31.523088", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}

TASK [role : debug] ************************************************************
ok: [localhost] => {
    "msg": "rescue"
}
```

Please provide a full reproducer following a format like I provide in this comment.

needs_info
