### ISSUE TITLE
EC2 Module will attempt to start Terminated instance when "all_instances" ini setting is set to True.

### ISSUE THREAD

**Issue by shard923** [ansible/ansible#20867]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2.py
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.0.0
  config file = /root/aws/aws-cycle-instances/ansible.cfg
  configured module search path = Default w/o overrides

```

##### SUMMARY

Task to start all EC2 instances that have a tag with a certain name in the morning.
Dynamic inventory picks up 'terminated' instances and ec2.py module fails when trying to "start" a terminated instance.

##### STEPS TO REPRODUCE

```yaml
---
- name: Start EC2 instances after savings shutdown 
  # Running locally to talk to AWS and not the instances
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
  - name: Start the instance
    ec2:
      state: running
      instance_tags: 
        "Shutdown Tag": "*"
      region: us-west-2

```

##### EXPECTED RESULTS

All stopped EC2 instances should be started if they possess the tag indicated
##### ACTUAL RESULTS

Error message, some EC2 instances are started, but it will stop when it comes to a terminated instance. Any instances after that are not started.
I have modified the ec2 module at my /usr/lib/python2.6/site-packages/ansible/modules/core/cloud/amazon/ec2.py
with the following:
line 1378
if inst.state != state:
to
if inst.state != state and inst.state != "terminated":

```
    "msg": "Unable to change state for instance i-0d0da8dc249601c81, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>Unsupported</Code><Message>The requested configuration is currently not supported. Please check the documentation for supported configurations.</Message></Error></Errors><RequestID>3a63bed9-f11b-4b7e-a1e9-a99e73eaffc8</RequestID></Response>"

```
