### ISSUE TITLE
support for count attribute to os_server module

### ISSUE THREAD

**Issue by samvarankashyap** [ansible/ansible#20864]
##### ISSUE TYPE
  - Feature Idea
 
##### COMPONENT NAME
os_server

##### ANSIBLE VERSION

```
ansible 2.2.1.0
ansible 2.3
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Currently ansible os_server module does not have support to provision servers based on count. 
However , I see rackspace cloud which is openstack based cloud and AWS EC2 modules have support to provision multiple instances based on count.  With few tweaks to existing module, it is highly possible to incorporate this feature into os_server module. 

##### FEATURE IDEA

With this feature , there would better performance in asynchronous provisioning of multiple servers. Currently in order to do a provision one has to use a ansible loop as follows: 
```yaml
---
- name: provision openstack servers on count
  hosts: localhost
  tasks:
  - name: "register count"
    shell: python -c "print [x for x in range( 1, 3)]"
    register: count
  - name: "provision os_server by looping on count"
    os_server:
      state: "present"
      name: "testvm_{{ instance.0 }}"
      image: "centos7"
      key_name: "testkeypair"
      flavor: "m1.small"
      networks: "testnetwork"
    with_items: "{{ count.stdout }}"
    loop_control:
      loop_var: instance
    register: output
```

If the feature is included , the playbook to provision servers will be simplified to:

```yaml
---
- name: This is a hello-world example
  hosts: localhost
  tasks:
    os_server:
      state: "present"
      name: "testvm"
      image: "centos7"
      key_name: "test_keypair"
      flavor: "m1.small"
      network:  "test_network"
      count: 2
```

##### EXPECTED RESULTS

expected output woudl contain the outputs of the provisioned openstack servers with names
testvm1, testvm2
