### ISSUE TITLE
vmware_guest: vm does not come online with only a network: block

### ISSUE THREAD

**Issue by stobias123** [ansible/ansible#20904]
I know that there is active development on the **vmware_guest** module, and I checked all active issues, but couldn't see anything specific like this. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`vmware_guest`

##### ANSIBLE VERSION
I installed with `pip install git+https://github.com/ansible/ansible.git@devel` earlier today, so I think I'm at commit cdc56afe010ef8640ffaa5e9d0f85903bd69b977 but I'm not 100% sure how to check via pip.
```
ansible 2.3.0
```

##### CONFIGURATION
N/A - Defaults

##### OS / ENVIRONMENT
Fedora 23

##### SUMMARY
When I specify a custom network/IP via the "networks" block, but do not specify any other customization options in the "customization" block, the IP address isn't set.

If you add the "customization" block, IP address will be set as expected.

##### STEPS TO REPRODUCE
Deploy a VM with a task containing **only** the networks block
Ex.
```yaml
  vmware_guest:
    ...
    networks:
      - name: My Network
        ip: 192.168.1.150
        netmask: 255.255.255.0
        dns_servers: ['192.168.1.2']
        gateway: 192.168.1.1
```
This VM **will not** come online at 192.168.1.150

Now deploy a VM with the customize block in addition to the networks block.

```yaml
  vmware_guest:
    ...
    networks:
      - name: My Network
        ip: 192.168.1.150
        netmask: 255.255.255.0
        dns_servers: ['192.168.1.2']
        gateway: 192.168.1.1
    customization:
        hostname: foo
        domain: bar.com
        dns_servers:
          - 192.168.1.2
        dns_suffix: bar.com
```
This VM **will** come online at 192.168.1.150

##### EXPECTED RESULTS
Both playbooks should spawn a VM that comes online at the desired IP address.

##### ACTUAL RESULTS
In the first playbook, the VM doesn't come online. If you tell it to `wait_for_ip_address` you sit waiting for a very long time, and eventually still returns "change" and not "failed".

I would think that the "networks" block should just belong indented underneath the "customization" block and then that would trigger the customization.
