### ISSUE TITLE
when condition does not behaves correctly using with_file

### ISSUE THREAD

**Issue by rascasoft** [ansible/ansible#20919]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Everything is the default.

##### OS / ENVIRONMENT

Fedora 25 and CentOS 7.3.1611

##### SUMMARY

Using a conditional "when" to skip part or an entire task list all the task are in any case mentioned on the output as "skipped".
But in some cases "skipped" does not mean that the step id fully jumped, since if you're using for example "with_file:" ansible tries in any case to load somewhere the variable.

##### STEPS TO REPRODUCE

You can simply declare this main site.yml file:

```yaml
---
- hosts: 192.168.122.100
  roles:
    - { role: test, when: do_the_test|bool }
```
Than have inside the role this /tasks/main.yml task list:
```yaml
---
- name: Create key
  delegate_to: localhost
  command: >
    ssh-keygen -f {{ my_key }} -N ''
    -C 'ansible_generated_virt_host'
    -t rsa -b 4096
  args:
    creates: "{{ my_key }}"

- name: Configure key on remote host
  authorized_key:
    user: root
    key: "{{ item }}"
  with_file:
    - "{{ my_key }}.pub"
  become: true
```
with this defaults/main.yml:
```yaml
my_key: rasca
do_the_test: false
```
Now, if you invoke ansible like this:
```
ansible-playbook -vvv -u root -i inventories/hosts.vms -e do_the_test=false site.yml
```
You will get an error from which you realize that the first task is correctly skipped, but the second one fails, because "with_file" does not find the associated file (which should have been generated by the previous, and skipped, task).
This does not happen if you use:
```yaml
---
- name: Create key
  delegate_to: localhost
  command: >
    ssh-keygen -f {{ my_key }} -N ''
    -C 'ansible_generated_virt_host'
    -t rsa -b 4096
  args:
    creates: "{{ my_key }}"

- name: Configure key on remote host
  authorized_key:
    user: root
    key: "{{ lookup('file', '{{ my_key }}.pub') }}"
  become: true
```
In this case also the second task is omitted.

##### EXPECTED RESULTS

Skipped items should never be "parsed" and so also the first tasks/main.yml should work without any problem (skipping both tasks).

##### ACTUAL RESULTS

```
TASK [test : Create key] *******************************************************
task path: /home/rasca/ansible/roles/test/tasks/main.yml:2
skipping: [192.168.122.100] => {
    "changed": false, 
    "skip_reason": "Conditional check failed", 
    "skipped": true
}

TASK [test : Configure key on remote host] *************************************
task path: /home/rasca/ansible/roles/test/tasks/main.yml:10
 [WARNING]: Unable to find 'rasca.pub' in expected paths.

fatal: [192.168.122.100]: FAILED! => {
    "failed": true, 
    "msg": "could not locate file in lookup: rasca.pub"
}
	to retry, use: --limit @/home/rasca/ansible/site.retry

PLAY RECAP *********************************************************************
```
Ansible is looking for a file for which we asked a skip.
