### ISSUE TITLE
ec2_vpc_net multi_ok not working as expected

### ISSUE THREAD

**Issue by surfuga** [ansible/ansible#20951]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

modules/cloud/amazon/ec2_vpc_net.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 64f98f855d) last updated 2017/02/02 00:15:21 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Option "multi_ok" does not work properly allowing to provision a new vpc with cidr_block and tag Name already existent in the AWS account.

##### STEPS TO REPRODUCE

Assuming a vpc with cidr_block 10.0.0.0/16 and tag Name 'test_vpc' already exists, run ansible with the module like this:

```yaml
- ec2_vpc_net:
    name: test_vpc
    cidr_block: 10.0.0.0/16
    region: us-east-1
    multi_ok: true
```

##### EXPECTED RESULTS

A new vpc named 'test_vpc' with cidr_block 10.0.0.0/16 to be created, and the module to return changed = True.
##### ACTUAL RESULTS

The ec2_vpc_net module return changed False and no new vpc is created for real.

```

```
