### ISSUE TITLE
new to ansible - condition doesn't get evaluated, register variable not defined.

### ISSUE THREAD

**Issue by jgalleri** [ansible/ansible#20975]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/jgalleri/cis-rhel-ansible-master/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

No Changes
##### OS / ENVIRONMENT

Linux  3.10.0-327.13.1.el7.x86_64 (RHEL 7.2)
##### SUMMARY

New to Ansible.
Downloaded Zip from https://github.com/sanderv32/cis-rhel-ansible#ansible--cis-benchmarks--rhelcentos-7 for Hardening RHEL 7

##### STEPS TO REPRODUCE

```yaml
sudo ansible-playbook -i hosts -C playbook.yml -u jgalleri --ask-pass --ask-become-pass -become --become-method=su --become-user=root

Check:
- name: 1.1.2 - 1.1.4 Set nodev,nosuid,noexec option for /tmp Partition (Scored)
    mount: >
      name="/tmp"
      src={{ item.device }}
      state=mounted
      fstype={{ item.fstype }}
      opts="nodev,nosuid,noexec"
    when: item.mount == "/tmp"
    with_items: ansible_mounts
    tags:
      - scored
      - section1.1
      - section1.1.2
      - section1.1.3
      - section1.1.4

```

##### EXPECTED RESULTS

Sorry, but it should either say, ok/changed/skipped.

##### ACTUAL RESULTS

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [xyz.corp.local]

TASK [cis : 1.1.1 Create Separate Partition for /tmp (Scored)] *****************
ok: [xyz.corp.local] => {
    "failed": false,
    "failed_when_result": false,
    "msg": "*** Manually create Separate Partition for /tmp."
}

TASK [cis : 1.1.2 - 1.1.4 Set nodev,nosuid,noexec option for /tmp Partition (Scored)] ***
fatal: [xyz.corp.local]: FAILED! => {"failed": true, "msg": "The conditional check 'item.mount == \"/tmp\"' failed. The error was: error while evaluating conditional (item.mount == \"/tmp\"): 'unicode object' has no attribute 'mount'\n\nThe error appears to have been in '/home/jgalleri/cis-rhel-ansible-master/roles/cis/tasks/section_01_level1.yml': line 27, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: 1.1.2 - 1.1.4 Set nodev,nosuid,noexec option for /tmp Partition (Scored)\n    ^ here\n"}
        to retry, use: --limit @/home/jgalleri/cis-rhel-ansible-master/playbook.retry

PLAY RECAP *********************************************************************
xyz.corp.local : ok=2    changed=0    unreachable=0    failed=1

```
