### ISSUE TITLE
Module Request: Hostname and Timezone

### ISSUE THREAD

**Issue by mbadran** [ansible/ansible#2098]
Bundling these together because I'm not sure if they fit into the Ansible Way (tm).

Every time I provision a new ec2 instance using Ansible, I use the following playbook tasks:

```
- name: immediately update the hostname
  command: hostname -v ${hostname}

- name: persist the hostname
  lineinfile: dest=/etc/sysconfig/network
              regexp=^HOSTNAME=
              line=HOSTNAME=${hostname}
              state=present

- name: add the hostname to the hosts file
  lineinfile: dest=/etc/hosts
              regexp="^127.0.0.1    ${hostname}"
              line="127.0.0.1    ${hostname}"
              state=present

- name: symlink the correct localtime - 1
  file: path=/etc/localtime
        state=absent

- name: symlink the correct localtime - 2
  file: src=/usr/share/zoneinfo/${timezone}
        dest=/etc/localtime
        state=link

- name: update the (hardware) clock config
  lineinfile: dest=/etc/sysconfig/clock
              regexp=^ZONE=
              line=ZONE=${timezone}
              state=present

- name: install ntpd daemon
  yum: name=ntp state=installed

- name: start ntp daemon now and after reboots
  service: name=ntpd state=started enabled=yes

- name: configure local ntp servers
  template: src=${ntp_file}
            dest=/etc/ntp.conf
            backup=yes
```

Ideally, I would like to replace all of this with just two idempotent modules:

```
- name: update the hostname
  hostname: name=product.example.com
```

And:

```
- name: set the local time according to the timezone
  time: timezone=Australia/Sydney
        backup=yes
        ntp=yes
        ntp_servers=${item}
  with_items:
    - 0.au.pool.ntp.org
    - 1.au.pool.ntp.org
    - 2.au.pool.ntp.org
    - 3.au.pool.ntp.org
```

Thanks.
