### ISSUE TITLE
Failure with apt module when installing python mysql dependencies

### ISSUE THREAD

**Issue by shobhitsingh** [ansible/ansible#21006]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

apt
##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### OS / ENVIRONMENT

Both Ubuntu 14.04
##### SUMMARY

Trying to install python mysql dependencies results in error. Earlier same scripts used to work.

##### STEPS TO REPRODUCE

```yaml
- name: Install Test requirements
  register: test_requirements_installed
  apt: name={{item}} state=installed update_cache=true
  with_items:
    - python-pip
    - python-dev
    - libmysqlclient-dev
    - python-mysqldb

```

##### EXPECTED RESULTS

Should install successfully
##### ACTUAL RESULTS

Failure

```
failed: [] (item=[u'python-pip', u'python-dev', u'libmysqlclient-dev', u'python-mysqldb']) => {"failed": true, "item": ["python-pip", "python-dev", "libmysqlclient-dev", "python-mysqldb"], "module_stderr": "Shared connection to 10.96.20.105 closed.\r\n", "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_ynaeyZ/ansible_module_apt.py\", line 962, in <module>\r\n    main()\r\n  File \"/tmp/ansible_ynaeyZ/ansible_module_apt.py\", line 945, in main\r\n    if updated_cache and not retvals['changed']:\r\nKeyError: 'changed'\r\n", "msg": "MODULE FAILURE"}
```
