### ISSUE TITLE
Default URL doesn't work for maven_artifact

### ISSUE THREAD

**Issue by wawrzek** [ansible/ansible#21005]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

maven_artifact

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### CONFIGURATION

No special chanfes

##### OS / ENVIRONMENT

Running from MacOSX on remote Ubuntu 16.04 LTS

##### SUMMARY

Ansible cannot download jar using default Maven Central url

##### STEPS TO REPRODUCE

I have following task in a role:

```yaml
- name: Get corda jar from Maven Central
  maven_artifact: group_id=net.corda artifact_id={{ item }} version=0.7 extension=jar dest={{ dir_location }}/{{ item }}.jar 
  with_items:
    - corda
  when: source is defined and source == "maven"
```

##### EXPECTED RESULTS

Ansible download and install jar file
##### ACTUAL RESULTS

Corda is available in Centra Maven, but Ansible fails with following error message:
```
{
    "failed": true,
    "invocation": {
        "module_args": {
            "artifact_id": "corda",
            "classifier": null,
            "dest": "/opt/corda/corda.jar",
            "extension": "jar",
            "group_id": "net.corda",
            "password": null,
            "repository_url": null,
            "state": "present",
            "username": null,
            "validate_certs": true,
            "version": "0.7"
        },
        "module_name": "maven_artifact"
    },
    "item": "corda",
    "msg": "url parsing went wrong 'NoneType' object has no attribute 'find'"
}
```

**Comment by wawrzek** [comment]
As I expected adding 'default' url as repository_url fixes problem.
```
- name: Get corda jar from Maven Central
  maven_artifact: group_id=net.corda artifact_id={{ item }} version={{ version }} extension=jar dest={{ dir_location }}/{{ item }}.jar repository_url='http://repo1.maven.org/maven2'
  with_items:
    - corda
  when: source is defined and source == "maven"
```

Output (expected in first place)
```
 {
    "artifact_id": "corda",
    "changed": true,
    "classifier": null,
    "dest": "/opt/corda/corda.jar",
    "extension": "jar",
    "gid": 0,
    "group": "root",
    "group_id": "net.corda",
    "invocation": {
        "module_args": {
            "artifact_id": "corda",
            "classifier": null,
            "dest": "/opt/corda/corda.jar",
            "extension": "jar",
            "group_id": "net.corda",
            "http_agent": null,
            "password": null,
            "repository_url": "http://repo1.maven.org/maven2",
            "state": "present",
            "url_password": null,
            "url_username": null,
            "username": null,
            "validate_certs": true,
            "version": "0.7"
        },
        "module_name": "maven_artifact"
    },
    "item": "corda",
    "mode": "0644",
    "owner": "root",
    "repository_url": "http://repo1.maven.org/maven2",
    "size": 46988093,
    "state": "file",
    "uid": 0,
    "version": "0.7"
}```
