### ISSUE TITLE
docker_container module is not able to get port range as an argument for exposed_ports or published_ports 

### ISSUE THREAD

**Issue by albdv** [ansible/ansible#21002]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container module

##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.1.0
  config file = /Users/username/projects/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
docker_container module fails on port ranges for exposed or published ports

##### STEPS TO REPRODUCE

```yaml
tasks/main.yml
- name: Starting an docker container
  docker_container:
    name: container
    image: {{container_name}}
    privileged: true
    network_mode: bridge
    published_ports: "{{ ports }}"
    detach: true
    restart_policy: on-failure
    state: started

vars/main.yml
ports:
   - 2100-2140:2100-2140
```

##### EXPECTED RESULTS
docker container should start and listen on the port range

##### ACTUAL RESULTS

```
TASK [pool : Starting an docker container] *****************************
fatal: [pool]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_hWeixm/ansible_module_docker_container.py\", line 2007, in <module>\r\n    main()\r\n  File \"/tmp/ansible_hWeixm/ansible_module_docker_container.py\", line 2000, in main\r\n    cm = ContainerManager(client)\r\n  File \"/tmp/ansible_hWeixm/ansible_module_docker_container.py\", line 1644, in __init__\r\n    self.parameters = TaskParameters(client)\r\n  File \"/tmp/ansible_hWeixm/ansible_module_docker_container.py\", line 759, in __init__\r\n    self.published_ports = self._parse_publish_ports()\r\n  File \"/tmp/ansible_hWeixm/ansible_module_docker_container.py\", line 968, in _parse_publish_ports\r\n    container_port = int(parts[-1])\r\nValueError: invalid literal for int() with base 10: '2100-2140'\r\n"
}

MSG:

MODULE FAILURE
```
