### ISSUE TITLE
vmware_guest does not register correct "changed" value when cloning from template

### ISSUE THREAD

**Issue by dinosaurhead** [ansible/ansible#21013]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/jenkins/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ansible and guest:
Red Hat Enterprise Linux Server release 7.2 (Maipo)

##### SUMMARY

When cloning from a template using the vmware_guest module the "changed" value registers incorrectly as false. 

##### STEPS TO REPRODUCE

Running the following play should clone a VM from the specified template and register the results in the variable "cloned". If the VM is not present prior to execution, the "changed" value should be true.

```yaml
- name: VMWARE_GUEST | Deploying VMs
  connection: local
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username:  "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    template: "{{ template_name }}"
    name: "{{ vm_name }}"
    folder: "{{ vm_folder }}"
    datacenter: "{{ esxi_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    state: poweredon
    validate_certs: false
    wait_for_ip_address: true
  register: vm_net_reconfigured
```

##### EXPECTED RESULTS

VM cloned from template and "changed" value set to true.

##### ACTUAL RESULTS

derek-as1 is not present before executing the play. The VM  is created from the template but the "changed" value is set to false.

The names have been changed to protect the innocent. I've masked some output with "#".
```
changed: [derek-as1] => {
     "changed": false,
     "failed": false,
     "instance": {
         "annotation": "root = redhat",
         "customvalues": {}
         "hw_eth0": {
             "addresstype": "assigned",
             "ipaddresses": [
                 "##.##.##.###",
                 "####::####:####:####:####"
             ],
             "label": "Network adapter 1",
             "macaddress": "##:##:##:##:##:##",
             "macaddress_dash": "##-##-##-##-##-##",
             "summary": "DVSwitch: ## ## ## ## ## ## ## ## ##-## ## ## ## ## ## ## ##"
         },
         "hw_eth1: {
             "addresstype": "assigned",
             "ipaddresses": [ ],
             "label": "Network adapter 2",
             "macaddress": "##:##:##:##:##:##",
             "macaddress_dash": "##-##-##-##-##-##",
             "summary": "DVSwitch: ## ## ## ## ## ## ## ## ##-## ## ## ## ## ## ## ##"
         },
         "hw_guest_full_name": "Red Hat Enterprise Linux 7 (64-bit)",
         "hw_guest_id": "rhel7_64Guest",
         "hw_interfaces": [
             "eth0",
             "eth1",
         ],
         "hw_memtotal_mb": 4096,
         "hw_name": "derek-as1",
         "hw_power_status": "poweredOn",
         "hw_processor_count": 2,
         "hw_product_uuid": "########-####-####-####-############",
         "ipv4": "##.##.##.##",
         "ipv6": "####::####:####:####:####",
         "module_hw": true
    },
    "invocation": {
         "module_args": {
             "annotation": null,
             "cluster": "####"
             "customization": {},
             "customvalues": [],
             "datacenter": "####",
             "disk": [],
             "esxi_hostname": null,
             "hardware": {},
             "hostname": "######.####.###",
             "is_template": false,
             "name": "derek-as1"
             "name_match": "first",
             "networks": [ ],
             "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
             "resource_pool" null,
             "snapshot_op": {},
             "state": "poweredon",
             "template_src" "rhel7",
             "username": "########",
             "uuid": null,
             "validate_certs": false,
             "wait_for_ip_address": true
         },
        "module_name": "vmware_guest"
    }
}         
```
