### ISSUE TITLE
vmware_guest does not allow changing vNIC networks

### ISSUE THREAD

**Issue by dinosaurhead** [ansible/ansible#21011]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /home/jenkins/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ansible and guest:
Red Hat Enterprise Linux Server release 7.2 (Maipo)

##### SUMMARY

Vsphere_guest allows changing the network a vNIC is connected to but this does not work in vmware_guest.

##### STEPS TO REPRODUCE

Running the following play should connect the vNICs to the specified networks:

```yaml
- name: VMWARE_GUEST | connect vNICs to correct network
  connection: local
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username:  "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    name: "{{ vm_name }}"
    folder: "{{ vm_folder }}"
    datacenter: "{{ esxi_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    validate_certs: false
    state: present
    networks:
    - name: "{{ nic1_network }}"
      device_type: vmxnet3
    - name: "{{ nic2_network }}"
      device_type:  vmxnet3
  register: vm_net_reconfigured
```

I am able to get expected results with the vsphere_guest module with the following play:
```yaml
- name: VSPHERE_GUEST | connect vNICs to correct network
  connection: local
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_hostname }}"
    username:  "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    guest: "{{ vm_name }}"
    state: reconfigured
    esxi:
        datacenter: "{{ esxi_datacenter }}"
        hostname: "{{ esxi_hostname }}"
    vm_nic:
        nic1:
            type: vmxnet3
            network: "{{ nic1_network }}"
            network_type: dvs
            state: connected
        nic2:
            type: vmxnet3
            network: "{{ nic2_network }}"
            network_type: dvs
            state: connected
  register: vm_net_reconfigured    
```

##### EXPECTED RESULTS

Expect vNICs to connect correct network. 

##### ACTUAL RESULTS

vNICs stay connected to the network they were connected to prior to running the play. 

The names have been changed to protect the innocent. I've masked some output with "#".
```
changed: [derek-as1] => {
     "changed": true,
     "failed": false,
     "instance": {
         "annotation": "root = redhat",
         "customvalues": {}
         "hw_eth0": {
             "addresstype": "assigned",
             "ipaddresses": [
                 "##.##.##.###",
                 "####::####:####:####:####"
             ],
             "label": "Network adapter 1",
             "macaddress": "##:##:##:##:##:##",
             "macaddress_dash": "##-##-##-##-##-##",
             "summary": "DVSwitch: ## ## ## ## ## ## ## ## ##-## ## ## ## ## ## ## ##"
         },
         "hw_eth1: {
             "addresstype": "assigned",
             "ipaddresses": [
                 "##.##.##.###",
                 "####:###:####:####:####"
             ],
             "label": "Network adapter 2",
             "macaddress": "##:##:##:##:##:##",
             "macaddress_dash": "##-##-##-##-##-##",
             "summary": "DVSwitch: ## ## ## ## ## ## ## ## ##-## ## ## ## ## ## ## ##"
         },
         "hw_guest_full_name": "Red Hat Enterprise Linux 7 (64-bit)",
         "hw_guest_id": "rhel7_64Guest",
         "hw_interfaces": [
             "eth0",
             "eth1",
         ],
         "hw_memtotal_mb": 16384,
         "hw_name": "derek-as1",
         "hw_power_status": "poweredOn",
         "hw_processor_count": 8,
         "hw_product_uuid": "########-####-####-####-############",
         "ipv4": "##.##.##.##",
         "ipv6": "####::####:####:####:####",
         "module_hw": true
    },
    "invocation": {
         "module_args": {
             "annotation": null,
             "cluster": "####"
             "customization": {},
             "customvalues": [],
             "datacenter": "####",
             "disk": [],
             "esxi_hostname": null,
             "hardware": {},
             "hostname": "######.####.###",
             "is_template": false,
             "name": "derek-as1"
             "name_match": "first",
             "networks": [
                 {
                      "device_type": "vmxnet3",
                      "name": "VM_network1"
                 },
                 {
                      "device_type": "vmxnet3",
                      "name": "VM_network2"
                 },
             ],
             "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
             "resource_pool" null,
             "snapshot_op": {},
             "state": "present",
             "template_src" null,
             "username": "########",
             "uuid": null,
             "validate_certs": false,
             "wait_for_ip_address": true
         },
        "module_name": "vmware_guest"
    }
}         
```
