### ISSUE TITLE
Add support for DeadLetterConfig

### ISSUE THREAD

**Issue by RobertMacDonald** [ansible/ansible#21032]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lambda module

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
lambda module does not currently support setting or retrieving the DeadLetterConfig setting on lambda functions.

##### STEPS TO REPRODUCE

```yaml
# Create Lambda functions
tasks:
- name: looped creation
  lambda:
    name: '{{ item.name }}'
    state: present
    zip_file: '{{ item.zip_file }}'
    runtime: 'python2.7'
    role: 'arn:aws:iam::987654321012:role/lambda_basic_execution'
    dead_letter_config_arn: "{{ item.dead_letter_config_arn | default(omit) }}"
    handler: 'hello_python.my_handler'
    vpc_subnet_ids:
    - subnet-123abcde
    - subnet-edcba321
    vpc_security_group_ids:
    - sg-123abcde
    - sg-edcba321
  with_items:
    - { name: HelloWorld, zip_file: 'hello-code.zip' }
    - { name: ByeBye, zip_file: 'bye-code.zip' }
    - name: NotSoFast
       zip_file: 'nsf-code.zip'
       dead_letter_config_arn: value      
```

##### EXPECTED RESULTS
The function has its DeadLetterConfig:TargetArn set to value in an idempotent fashion.

##### ACTUAL RESULTS
The support for this in the current module is not present.
