### ISSUE TITLE
sefcontext missing serole parameter

### ISSUE THREAD

**Issue by rgarrigue** [ansible/ansible#21052]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

sefcontext

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Uncommented stdout_callback = skippy

##### OS / ENVIRONMENT

N/A, but Ubuntu 16.10

##### SUMMARY

file module got serole seuser selevel setype parameters, which match selinux

sefcontextgot seuser selevel setype parameters, but is missing serole. If I'm not mistaken, serole default to object_r, that works for me but might be a problem ?

/opt/tomcat/logs/.*?                               all files          system_u:object_r:tomcat_log_t:s0  

##### STEPS TO REPRODUCE

```yaml
 - name: Logrotate | SELinux fcontext for /opt/tomcat/logs
      sefcontext:
        target: '/opt/tomcat/logs/.*?'
        seuser: system_u
        serole: object_r
        setype: tomcat_log_t
        selevel: s0
        state: present
```

##### EXPECTED RESULTS

```
changed: [reequresw01]
```

##### ACTUAL RESULTS

```
fatal: [reequresw01]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: serole"}
```
