### ISSUE TITLE
iosxr_template: "src:" isn't idempotent

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21055]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
iosxr_template
iosxr_config

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel db8fd95d68) last updated 2017/02/06 09:59:55 (GMT +100)

```

##### SUMMARY
iosxr_template is returning `changed` when running
```yaml
- name: check device with config
  iosxr_template:
    src: basic/config.j2
  register: result
```

**templates/basic/config.j2**
```
hostname {{ inventory_hostname_short }}
!
interface Loopback999
   description this is a test
   shutdown

```
##### STEPS TO REPRODUCE
Assuming you have SSH keys setup
```
cd test/integration
ANSIBLE_USE_PERSISTENT_CONNECTIONS=False ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvvv  -i  inventory.network-jobarker iosxr.yaml -e "limit_to=iosxr_template" -u root --private-key=~/.ssh/id
```

```yaml
- name: setup
  iosxr_config:
    commands:
      - no interface Loopback999
    match: none

- name: configure device with config
  iosxr_template:
    src: basic/config.j2
  register: result

- assert:
    that:
      - "result.changed == true"
      - "result.updates is defined"

- name: check device with config
  iosxr_template:
    src: basic/config.j2
  register: result

- assert:
    that:
      - "result.changed == false"
      - "result.updates is defined"

```
##### ACTUAL RESULTS
```yaml
TASK [iosxr_template : check device with config] *************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/iosxr_template/tests/cli/basic.yaml:20
<iosxr01> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO iosxr01
<iosxr01> closing connection
changed: [iosxr01] => {
    "changed": true, 
    "delta": "0:00:05.921929", 
    "end": "2017-02-06 11:38:25.775341", 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "config": null, 
            "force": false, 
            "host": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "src": "hostname iosxr01\n!\ninterface Loopback999\n   description this is a test\n   shutdown\n", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": null, 
            "username": null
        }
    }, 
    "start": "2017-02-06 11:38:19.853412", 
    "updates": [
        "interface Loopback999", 
        "description this is a test", 
        "shutdown"
    ], 
    "warnings": [
        "network provider arguments are no longer supported.  Please use connection: network_cli for the task"
    ]
}

TASK [iosxr_template : assert] *******************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/iosxr_template/tests/cli/basic.yaml:25
<iosxr01> closing connection
fatal: [iosxr01]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "that": [
                "result.changed == false", 
                "result.updates is defined"
            ]
        }, 
        "module_name": "assert"
    }
}
```
