### ISSUE TITLE
postgresql module not working properly on Ubuntu 12.04

### ISSUE THREAD

**Issue by vmalloc** [ansible/ansible#2107]
Tried devel branch version. 

My playbook is more or less this sequence as root:

```
- hosts: installed_hosts
  tasks:
    - name: set up packages
      action: apt pkg=$item state=latest
      with_items:
        - python-psycopg2
        - postgresql
```

And then this:

```
- hosts: installed_hosts
  sudo_user: postgres
  gather_facts: false
  tasks:
    - name: database setup
      action: postgresql_db name=my_db
```

I get this output running on clean ubuntu 12.04:

```
failed: [server] => {"failed": true, "item": ""}
msg: unable to connect to database: FATAL:  Peer authentication failed for user "postgres"


FATAL: all hosts have already failed -- aborting
```

I'm running ansible-playbook with `-u root`.
