### ISSUE TITLE
vmware_guest: No default Datacenter for non-vCenter configurations

### ISSUE THREAD

**Issue by dav1x** [ansible/ansible#21074]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest 

##### ANSIBLE VERSION

```
-> ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### SUMMARY

Attempt to use vmware_guest with a direct ESXi host without specifying a datacenter. You get an error.

If you install a fresh install of ESXi the default datacenter will always be:

govc ls
/ha-datacenter/vm
/ha-datacenter/network
/ha-datacenter/host
/ha-datacenter/datastore

The default setting for datacenter should be ha-datacenter.

##### STEPS TO REPRODUCE

```yaml
---
- name: create vm
  hosts: localhost
  tasks:
    - vmware_guest_cpu:
        hostname: "10.x.x.165"
        username: "root"
        password: "***"
        validate_certs: False
        name: "testvm"
        validate_certs: False
        #datacenter: "ha-datacenter"
        #wait_for_ip_address: False
        state: present      
```

##### EXPECTED RESULTS

The VM is powered on. 

##### ACTUAL RESULTS

You get an error about missing datacenter setting. 

```

```
