### ISSUE TITLE
docker_container - cryptic error message ("Boolean always not in either boolean list")

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible#21075]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
2.2.1.0

##### OS / ENVIRONMENT
Control Machine: Fedora 25
Hosts: CentOS 7.3

##### SUMMARY
While converting from the docker module to the docker_container module, a non-boolean value for the 'pull' parameter causes the following error:

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Boolean always not in either boolean list"}

##### STEPS TO REPRODUCE
```
- name: Launch CouchDB container
  docker_container:
    name: couchdb
    image: inclusivedesign/couchdb
    networks:
      - name: bridge  # work around for https://github.com/ansible/ansible-modules-core/issues/1885
    state: started
    pull: always
    restart_policy: always
```

Note "pull: always" is code remaining from the old docker module. It should be either true or false with the docker_container module.

##### EXPECTED RESULTS
A less cryptic message
