### ISSUE TITLE
URI Module : Passing file as body

### ISSUE THREAD

**Issue by yaniveliash** [ansible/ansible#21092]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
URI

##### ANSIBLE VERSION
2.2.1.0

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I'm trying to pass a json file as my body in a URI POST task
for that I'm combining a lookup module to a local file (on my host - not remote machine) however it doesn't seems to work and there is no documentation for that (at least not one that I can found)

##### STEPS TO REPRODUCE
My task looks like this:
```
      - name: Populating browsers collection
        uri:
            url: "http://{{groups['default'][0]}}:8529/_db/collectionDB/_api/document/browsers"
            HEADER_Content-Type: "application-type: json"
            body: "{{ lookup('file','include/Browsers-CollectionDB.json') }}"
            user: "{{ARANGODB_USER}}"
            password: "{{ARANGODB_PASS}}"
            method: POST
            force_basic_auth: yes
            status_code: 200
```
