### ISSUE TITLE
vmware_guest: vm_cdrom

### ISSUE THREAD

**Issue by Trezamere** [ansible/ansible#21112]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
2.3.0

##### SUMMARY
 The newer vmware_guest module does not currently support loading / managing cd_roms.  The older vsphere_guest has this functionality; it would be nice to have it ported forward so we can do something like the following.

```
    hardware:
      memory_mb: 2048
      num_cpus: 2
      scsi: paravirtual
      vm_cdrom:
        type: "iso"
        iso_path: "DatastoreName/cd-image.iso"
```
