### ISSUE TITLE
os_security_group_rule should support all IP protocols specified as integers

### ISSUE THREAD

**Issue by szponek** [ansible/ansible#21125]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
os_security_group_rule

##### ANSIBLE VERSION
Checked on both:
- ansible 2.3.0
```
ansible 2.3.0 (devel d12e9f5748) last updated 2017/02/08 12:19:12 (GMT +1300)
  config file = 
  configured module search path = Default w/o overrides
```
- ansible 2.1.2.0
```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None
##### OS / ENVIRONMENT
N/A
##### SUMMARY
Just as it was described in an already closed #4412, ansible doesn't support creating OpenStack security rules for other protocols than tcp, udp, icmp and vrrp, while there are around 250 other IP protocols, i.e 50(esp), 51(ah), 47(gre), L2TP(115) used frequently.

##### STEPS TO REPRODUCE
Run a task to add a new security group rule in OpenStack
```yaml
    - name: ipsec1-dev
      os_security_group_rule:
        state: present
        security_group: dev
        protocol: 50
        remote_ip_prefix: 0.0.0.0/0
```
##### EXPECTED RESULTS
I expect ansible to successfully create a security group rule with other IP protocols specified using integers.
It's possible to do with heat, so no reason why ansible shouldn't support it as well:
```yaml
#
# Deploying a security-group with IP protocol number using Heat
#
heat_template_version: 2013-05-23

description: >
  new security group rule

resources:

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: test
      description: test sg for esp
      rules:
      - remote_ip_prefix: 0.0.0.0/0
        protocol: 50
```

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "value of protocol must be one of: None,tcp,udp,icmp,112, got: 50"}
```
