### ISSUE TITLE
Rescue part of block loses hostvars

### ISSUE THREAD

**Issue by alvaroaleman** [ansible/ansible#21138]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Ansible block/rescue feature

##### ANSIBLE VERSION

```
ansible 2.3.0 (devel 64ed9bcfd7) last updated 2017/02/08 14:18:00 (GMT +200)
Also affects 2.2.1
```

##### SUMMARY

* The task in the rescue block doesn't contain the ssh user anymore

Relevant role part:

```yaml
- block:
    - name: Create root user
      run_once: true
      delegate_to: "{% for h in play_hosts if hostvars[h].percona_type=='node' %}{% if loop.first %}{{ h }}{% endif %}{% endfor %}"
      mysql_user:
        name: root
        host: localhost
        password: "{{ percona_root_password }}"
        priv: "*.*:ALL,GRANT"
        login_unix_socket: "{{ percona_mycnf.socket }}"
        login_password: "{{ percona_root_password }}"
        login_user: root
  rescue:
    - name: Create root user
      run_once: true
      delegate_to: "{% for h in play_hosts if hostvars[h].percona_type=='node' %}{% if loop.first %}{{ h }}{% endif %}{% endfor %}"
      mysql_user:
        name: root
        host: localhost
        password: "{{ percona_root_password }}"
        priv: "*.*:ALL,GRANT"
        login_unix_socket: "{{ percona_mycnf.socket }}"
        login_user: root
```

##### ACTUAL RESULTS

```
TASK [ansible-percona-config : Create root user] *******************************
task path: /home/alvaro/git/LHIND/ansible-percona-config/tasks/main.yml:416
Using module file /home/alvaro/ansible/lib/ansible/modules/database/mysql/mysql_user.py
<192.168.121.250> ESTABLISH SSH CONNECTION FOR USER: vagrant
<192.168.121.250> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o 'IdentityFile="/home/alvaro/git/LHIND/ansible-percona-config/.vagrant/machines/box1/libvirt/private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/home/alvaro/.ansible/cp/d10f7f5bd4 192.168.121.250 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
fatal: [box1 -> None]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "append_privs": false, 
            "check_implicit_admin": false, 
            "config_file": "/home/vagrant/.my.cnf", 
            "connect_timeout": 30, 
            "encrypted": false, 
            "host": "localhost", 
            "host_all": false, 
            "login_host": "localhost", 
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "login_port": 3306, 
            "login_unix_socket": "/home/vagrant/var/run/mysqld.sock", 
            "login_user": "root", 
            "name": "root", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "priv": "*.*:ALL,GRANT", 
            "sql_log_bin": true, 
            "ssl_ca": null, 
            "ssl_cert": null, 
            "ssl_key": null, 
            "state": "present", 
            "update_password": "always", 
            "user": "root"
        }
    }, 
    "msg": "unable to connect to database, check login_user and login_password are correct or /home/vagrant/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: YES)\")"
}

TASK [ansible-percona-config : Create root user] *******************************
task path: /home/alvaro/git/LHIND/ansible-percona-config/tasks/main.yml:428
Using module file /home/alvaro/ansible/lib/ansible/modules/database/mysql/mysql_user.py
<192.168.121.250> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.121.250> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=30 -o ControlPath=/home/alvaro/.ansible/cp/d4d3613ba3 192.168.121.250 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
fatal: [box1]: UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"192.168.121.250\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
```
