### ISSUE TITLE
LVOL module failed on with_dict

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#21140]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
LVOL module

##### ANSIBLE VERSION

```
ansible 2.2.0.0

Installed Packages
Name        : ansible
Arch        : noarch
Version     : 2.2.0.0
Release     : 4.el7
Size        : 21 M
Repo        : installed
From repo   : epel

also

ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Installed Packages
Name        : ansible
Arch        : noarch
Version     : 2.2.1.0
Release     : 1.el7
Size        : 21 M
Repo        : installed
From repo   : epel
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
CentOS Linux release 7.2.1511 (Core)
3.10.0-327.36.3.el7.x86_64

##### SUMMARY
LVOL module does not see variables passed via **with_dict**

##### STEPS TO REPRODUCE
The test yaml

```yaml
- hosts: test
  vars:
    lv:
      vol1:
        vg: cl
        size: 1g
      vol2:
        vg: cl
        size: 5g
      vol3:
        vg: cl
        size: 1g
  tasks:
  - name: Debug mode to see if ansible itself passes variables
    debug: msg="{{ item.key }} --> {{ item.value.vg }} --> {{ item.value.size }}"
    with_dict: "{{ lv }}"

  - name: Test lvol module to build an example lv layout
    lvol:
      vg: "{{ item.value.vg }}"
      lv: "{{ item.key }}"
      size: "{{ item.value.size }}"
      active: yes
      state: present
      with_dict: "{{ lv }}"

```

##### EXPECTED RESULTS
The lvol task should be accomplished as the debug task does not show any variable issues

##### ACTUAL RESULTS
LVOL task returns fatal state
```
PLAY [test] ****************************************************************

TASK [setup] *******************************************************************
ok: [10.10.0.1]

TASK [Debug mode to see if ansible itself passes variables] ********************
ok: [10.10.0.1] => (item={'key': u'vol2', 'value': {u'vg': u'cl', u'size': u'5g'}}) => {
    "item": {
        "key": "vol2", 
        "value": {
            "size": "5g", 
            "vg": "cl"
        }
    }, 
    "msg": "vol2 --> cl --> 5g"
}
ok: [10.10.0.1] => (item={'key': u'vol3', 'value': {u'vg': u'cl', u'size': u'1g'}}) => {
    "item": {
        "key": "vol3", 
        "value": {
            "size": "1g", 
            "vg": "cl"
        }
    }, 
    "msg": "vol3 --> cl --> 1g"
}
ok: [10.10.0.1] => (item={'key': u'vol1', 'value': {u'vg': u'cl', u'size': u'1g'}}) => {
    "item": {
        "key": "vol1", 
        "value": {
            "size": "1g", 
            "vg": "cl"
        }
    }, 
    "msg": "vol1 --> cl --> 1g"
}

TASK [Test lvol module to build an example lv layout] **************************
fatal: [10.10.0.1]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/ansible-playbook/test.yaml': line 18, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Test lvol module to build an example lv layout\n    ^ here\n"}
	to retry, use: --limit @/ansible-playbook/test.retry

PLAY RECAP *********************************************************************
10.10.0.1                : ok=2    changed=0    unreachable=0    failed=1
```
