### ISSUE TITLE
ovirt_vms module should not fail on starting vms when there is a running operation with disk snapshot

### ISSUE THREAD

**Issue by dron23** [ansible/ansible#21158]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ovirt_vms module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
without custom modifications, just nocow = 1

##### OS / ENVIRONMENT
Fedora23 (running ansible on it) and CentOS7.3 (managed OS)

##### SUMMARY
ovirt_vms module should not fail on starting vms when there is a running operation with disk snapshot.

##### STEPS TO REPRODUCE
let have a vm running as stateless and make some changes on it. Then try to stop and start it to revert all the changes. For example with this task:

```yaml
- name: stop vm
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: stopped
    name: "{{ vm_name }}"
    wait: yes

- name: start vm
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: running
    name: "{{ vm_name }}"
    wait: yes
```

If there were lot of changes then deletion of a stateless snapshot could take some time. Because using  wait: yes ansible should wait until snapshot is removed but this task could end with this error:

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot run VM. The VM is performing an operation on a Snapshot. Please wait for the operation to finish, and try again.]\". HTTP response code is 409."}

##### EXPECTED RESULTS
Ansible should wait until snapshot is removed, then run the vm.

##### ACTUAL RESULTS
Task fails because "The VM is performing an operation on a Snapshot".
