### ISSUE TITLE
vmware_guest: mac address not setting addressType as static

### ISSUE THREAD

**Issue by Trezamere** [ansible/ansible#21161]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 5f29117e59) last updated 2017/02/08 09:50:39 (GMT -700)
  config file = /home/user/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
VCenter 6, ESXi 6 host, targeting ubuntu server 16.04 amd64.

##### SUMMARY
When setting the 'mac' address field; I expected the `ethernet0.addressType` field to be set to 'static' (manual in the UI); it remains as 'vpx' (automatic in the UI).

This has the implication of not allowing one to manually set the MAC address, vCenter will throw an error when you try and boot the machine up.

Additionally, it would be nice if there was some documentation or better error checking for valid values; which are 00:50:56:00-3F:00-FF:00-FF.

See https://pubs.vmware.com/vsphere-51/index.jsp#com.vmware.vsphere.networking.doc/GUID-F9243FED-F081-498F-B4A9-EF950292AF77.html for more information on the MAC address restrictions (it's the same for 6).

##### STEPS TO REPRODUCE

The following playbook shows the issue.

```yaml
    - name: VM is configured
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        annotation: "{{ notes | default('Created by Ansible') }}"
        datacenter: "{{ datacenter }}"
        disk:
          - size_gb: "{{ disk | default(20) }}"
            type: thick
            datastore: "{{ datastore }}"
        esxi_hostname: "{{ esxi_host }}"
        guest_id: "ubuntu64guest"
        hardware:
          memory_mb: "2048"
          num_cpus: "2"
          scsi: paravirtual
        networks:
          - name: "{{ network | default('VM Network') }}"
            device_type: vmxnet3
            mac: "00:50:56:33:7e:20"
        name: "{{ inventory_hostname }}"
        resource_pool: "{{ resource_pool | default(omit) }}"
        state: present
        validate_certs: no
        wait_for_ip_address: false
```

Then check the machine settings in the UI; it will show the MAC address as automatic.  

Oddly it seems to be hit and miss with whether or not vCenter will actually throw an error and boot the machine up or not; some addresses it works and others it doesnt; I suspect it's just a bug in vcenter.  The address I provided is throwing an error in vcenter for me.
