### ISSUE TITLE
Blockinfile with insertbefore does not insert before in some cases

### ISSUE THREAD

**Issue by cdosborn** [ansible/ansible#21176]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
blockinfile
https://docs.ansible.com/ansible/blockinfile_module.html

##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /opt/dev/clank/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

##### OS / ENVIRONMENT
ubuntu14

##### SUMMARY
When I use `insertbefore` in `blockinfile` it is ignored if the the block is already present in another place in the file. The block is appended to the end of the file.

##### STEPS TO REPRODUCE

```yaml
- blockinfile:
    dest: "/tmp/test.txt"
    insertbefore: "^INSERT BEFORE ME"
    block: |
      SOME TEXT

```

##### EXPECTED RESULTS
before: `/tmp/test.txt`:
```
INSERT BEFORE ME
# BEGIN ANSIBLE MANAGED BLOCK
SOME TEXT
# END ANSIBLE MANAGED BLOCK
```
after:
```
# BEGIN ANSIBLE MANAGED BLOCK
SOME TEXT
# END ANSIBLE MANAGED BLOCK
INSERT BEFORE ME
...
```

##### ACTUAL RESULTS
```
INSERT BEFORE ME
# BEGIN ANSIBLE MANAGED BLOCK
SOME TEXT
# END ANSIBLE MANAGED BLOCK
```

`lineinfile` behaves as I expect.
