### ISSUE TITLE
Restarting container with non-default log driver fails with "No command specified"

### ISSUE THREAD

**Issue by bbayani** [ansible/ansible#21188]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module: docker_container

##### ANSIBLE VERSION
```
[root@gsljumphost restart_issue]# ansible --version
ansible 2.1.3.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
No configurations done in ansible.cfg

##### OS / ENVIRONMENT
OS: CentOS7

##### SUMMARY
Restarting a container created with log driver syslog failed to restart. The error shown is : "No command specified"

##### STEPS TO REPRODUCE
1. Install ansible version 2.1.3.0
2. Install docker version 1.13.0
```
[root@gsljumphost restart_issue]# docker --version
Docker version 1.13.0, build 49bf474
```
3. Configure docker daemon to use logging driver syslog
4. create site.yml with below content
```
[root@gsljumphost restart_issue]# cat site.yml 
- hosts:
  - all

  tasks:
    - docker_container:
        name: myservice
        image: busybox
        command: /bin/sh -c 'sleep 1000000'
        log_driver: syslog
        log_options:
          syslog-address: tcp://localhost:514
          syslog-facility: daemon
          tag: myservice


    - name: Restart above container
      docker_container:
        name: myservice
        state: "started"
        restart: "yes"
```
5. Run playbook as:
```
[root@gsljumphost restart_issue]# ansible-playbook -i "localhost," -c local site.yml 
```
##### EXPECTED RESULTS
The container should have been restarted.

##### ACTUAL RESULTS
Restart failed. Playbooks ends with an error.

```
[root@gsljumphost restart_issue]# ansible-playbook -i "localhost," -c local site.yml 

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [docker_container] ********************************************************
changed: [localhost]

TASK [Restart above container] *************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating container: 400 Client Error: Bad Request (\"{\"message\":\"No command specified\"}\")"}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/cloud-user/bbayani/workspaces/ansible_bugs/restart_issue/site.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```

If the restart task is provided again with log-driver and log-options input, the task works. But only for restarting a container, we should not need to specify the logging options again.

**Comment by ansibot** [comment]
cc @ThomasSteinbach @cove @dusdanig @jctanner @joshuaconner @kassiansun @softzilla @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mrdaemon** [comment]
I can confirm the issue happens as well on the following configuration:
- Ubuntu 14.04.5 LTS on every system
- Docker host running 17.06.1-ce
- Ansible 2.3.2.0 on control host
- Syslog driver in container configuration

We have a playbook that restarts containers after deployment of a new version of a configuration file, and it inevitably fails in this way now, causing CI jobs to report failure. On next run the separate task that ensures the container is started (with the parameters) causes it to start correctly.

The tasks are structurally identical to the example provided by bbayani above.

This is a bit of a breaking issue and I'm not sure how to work around it at this point, short of stepping down to shell commands for the restart task and hoping for the best.

**Comment by ti-mo** [comment]
Same issue here:

- ansible==2.3.2.0

On the remote:

- docker-py==1.10.6

```
Client:
 Version:      1.13.1
 API version:  1.26

Server:
 Version:      1.13.1
 API version:  1.26 (minimum version 1.12)
```

Workaround using `command`.

**Comment by markgoddard** [comment]
I'm also seeing this, although I'm not using the log_driver or log_options arguments to create the container.

The task used to create the container is
```
---
- name: Ensure containers are running
  docker_container:
    image: "{{ item.value.image }}"                                                                                                                                                                         
    name: "{{ item.value.container_name }}"
    ports: "{{ item.value.ports | default(omit) }}"
    privileged: "{{ item.value.privileged | default(omit) }}"
    read_only: "{{ item.value.read_only | default(omit) }}"
    restart_policy: "{{ my_restart_policy }}"
    restart_retries: "{{ my_restart_retries }}"
    state: "{{ item.value.enabled | ternary('started', 'absent') }}"
    volumes: "{{ item.value.volumes }}"
  with_dict: "{{ my_container_definitions }}"
```
The handler task used to restart the container is:
```
---
- name: Restart containers
  docker_container:
    name: "{{ item.value.container_name }}"
    state: started
    restart: True                                                                                                                                                                 
  with_dict: "{{ my_container_definitions }}"
  when: item.value.enabled
```
And it fails with the following output:
```RUNNING HANDLER [inspection-store : Restart inspection store container] ************************************************************************************************************************************
failed: [sv-b16-u23] (item=<scrubbed>, "msg": "Error creating container: 400 Client Error: Bad Request (\"No command specified\")"}
```
Docker daemon logs contain the following:
```
level=error msg="Handler for POST /v1.24/containers/create returned error: No command specified"
```
Adding an `image` argument to the restart handler allows it to successfully restart the container.

Ansible info (it's based on commit e8e2c5a9f7b2fcbe55664b576f38976bea8f7883 in stable-2.3, with a cherry-picked fix for issue 30350).
```
ansible 2.3.2.0 (detached HEAD 00eec1e830) last updated 2017/09/14 13:21:59 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
