### ISSUE TITLE
Script Module Documented as Module but only contains description

### ISSUE THREAD

**Issue by swizzley** [ansible/ansible#21207]
Fix your documentation, do not put documentation up for modules that are not tested. 

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
module/commands/script/*

##### ANSIBLE VERSION
tower 3.x

##### SUMMARY
This module is in official documentation, but the module only contains a description and no actual code

```yaml
- script: /some/local/remove_file.sh --some-arguments 1234
  args:
    removes: /the/removed/file.txt
```

##### ACTUAL RESULTS
```
fatal: FAILED! => {"failed": true, "msg": "file or module does not exist: 
```
