### ISSUE TITLE
start service doesn't work in docker + ubuntu 14.04

### ISSUE THREAD

**Issue by JMLX42** [ansible/ansible#21208]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
2.2

##### OS / ENVIRONMENT
host: Ubuntu 16.04
guest: Ubuntu 14.04 Docker image

This error does **not** happen when using Ubuntu 14.04 in VirtualBox, only when using Ubuntu 14.04 in Docker.

##### SUMMARY
similar to:

* https://github.com/ansible/ansible/issues/4320
* https://github.com/hashbangcode/vlad/issues/188

but none of the proposed fix/workaround works.

##### STEPS TO REPRODUCE
```yaml
- name: install mysql
  apt: name={{ item }} state=present update_cache=yes
  when:
    - ansible_os_family == 'Debian'
  with_items:
    - python-mysqldb
    - mysql-server

- name: start mysql service
  service: name={{ mysql_daemon }} state=started enabled=yes

- name: set mysql password
  sudo: yes
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ home_db_pass }}"
    login_user: root
    login_password: "{{ home_db_pass }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
```

##### EXPECTED RESULTS
Root password is changed.

##### ACTUAL RESULTS
```
failed: [qualif-image] (item=localhost) => {
"failed": true,
"invocation": {
"module_args": {
"append_privs": false,
"check_implicit_admin": true,
"config_file": "/********/.my.cnf",
"connect_timeout": 30,
"encrypted": false,
"host": "localhost",
"host_all": false,
"login_host": "localhost",
"login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"login_port": 3306,
"login_unix_socket": null,
"login_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
"priv": "*.*:ALL,GRANT",
"sql_log_bin": true,
"ssl_ca": null,
"ssl_cert": null,
"ssl_key": null,
"state": "present",
"update_password": "always",
"user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
},
"module_name": "mysql_user"
},
"item": "localhost",
"msg": "unable to connect to database, check login_user and login_password are correct or /********/.my.cnf has the credentials. Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)\")"
}
```
