### ISSUE TITLE
Inconsistent behavior dependent on name of variable/key

### ISSUE THREAD

**Issue by GriffithLea** [ansible/ansible#21216]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

--extra-vars and/or set_fact and/or vars_prompt

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

# cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.5 (Santiago)
##### SUMMARY

I get different behavior depending on whether I use --extra-vars or not to bypass vars_prompt in my playbook, unless I make what seem to be insignificant changes to my variable/key names (see below).

##### STEPS TO REPRODUCE

Run the playbook below two different ways:
* ansible-playbook playbook.yml (answer "1" and "2" to the two prompts)
* ansible-playbook playbook.yml --extra-vars "var_worked_around=1 var_not_worked_around=2"

```yaml
---

- hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: var_worked_around
      prompt: "Please specify a value for var_worked_around"
      private: no
    - name: var_not_worked_around
      prompt: "Please specify a value for var_not_worked_around"
      private: no

  tasks:
    - set_fact:
# Note underscore appended to "var_worked_around" on next line, to make it "different"
        var_worked_around_: "{{(var_worked_around != '') |ternary('--var_worked_around=' + var_worked_around, '')}}"
    - set_fact:
        var_not_worked_around: "{{(var_not_worked_around != '') |ternary('--var_not_worked_around=' + var_not_worked_around, '')}}"

- hosts: beehive01
  gather_facts: no

  tasks:
    - name: Gather facts
      setup:

    - debug:
        var: "{{item}}"
      with_items:
        - hostvars['localhost']['var_worked_around_']
        - hostvars['localhost']['var_not_worked_around']
```

##### EXPECTED RESULTS

I expected to see the debug output be the same whether I used --extra-vars or supplied the same information via the prompts, for both variables.

##### ACTUAL RESULTS

I got different results for one of the variables, the one that had the same "name:" in vars_prompt as I called it in set_fact. If I differentiate the names, all is well. Should this make a difference? Aren't these two different namespaces (for lack of a better word)?

```
# ansible-playbook /tmp/fakeheadnode.yml
Please specify a value for var_worked_around: 1
Please specify a value for var_not_worked_around: 2

PLAY [localhost] ***************************************************************

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

PLAY [beehive01] ***************************************************************

TASK [Gather facts] ************************************************************
ok: [beehive01]

TASK [debug] *******************************************************************
ok: [beehive01] => (item=hostvars['localhost']['var_worked_around_']) => {
    "hostvars['localhost']['var_worked_around_']": "--var_worked_around=1", 
    "item": "hostvars['localhost']['var_worked_around_']"
}
ok: [beehive01] => (item=hostvars['localhost']['var_not_worked_around']) => {
    "hostvars['localhost']['var_not_worked_around']": "--var_not_worked_around=2", 
    "item": "hostvars['localhost']['var_not_worked_around']"
}

PLAY RECAP *********************************************************************
beehive01                  : ok=2    changed=0    unreachable=0    failed=0   
localhost                  : ok=2    changed=0    unreachable=0    failed=0   

# ansible-playbook /tmp/fakeheadnode.yml --extra-vars "var_worked_around=1 var_not_worked_around=2"

PLAY [localhost] ***************************************************************

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [set_fact] ****************************************************************
ok: [localhost]

PLAY [beehive01] ***************************************************************

TASK [Gather facts] ************************************************************
ok: [beehive01]

TASK [debug] *******************************************************************
ok: [beehive01] => (item=hostvars['localhost']['var_worked_around_']) => {
    "hostvars['localhost']['var_worked_around_']": "--var_worked_around=1", 
    "item": "hostvars['localhost']['var_worked_around_']"
}
ok: [beehive01] => (item=hostvars['localhost']['var_not_worked_around']) => {
    "hostvars['localhost']['var_not_worked_around']": "2", 
    "item": "hostvars['localhost']['var_not_worked_around']"
}

PLAY RECAP *********************************************************************
beehive01                  : ok=2    changed=0    unreachable=0    failed=0   
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
