### ISSUE TITLE
ec2_elb_facts not working 

### ISSUE THREAD

**Issue by RahulMahale** [ansible/ansible#21252]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_elb_facts

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

```ubuntu 15.10```

##### SUMMARY

```
According to document http://docs.ansible.com/ansible/ec2_elb_facts_module.html
We want a dns name and hosted zone ID of ELB  but we are not able to get it for our ELB and it is failing 
```

##### STEPS TO REPRODUCE

```
  local_action:
    module: ec2_elb_facts
    aws_access_key: "{{ aws_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    names: test-12345667.us-east-1.elb.amazonaws.com
    region: us-east-1
  register: elb_facts
- set_fact: 
      ELB_TEST: "{{ elb_facts.elbs.0.dns_name }}"
- action:
    module: debug
    msg: "{{ ELB_TEST}}"

```

##### EXPECTED RESULTS
DNS of ELB and complete information

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: list object has no element 0\n\nThe error appears to have been in '/roles/ansi-kube/tasks/main.yml': line 59, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  register: elb_facts\n- set_fact:\n  ^ here\n"}
```
