### ISSUE TITLE
Undefined 'ansible_host' in local_action hostvars

### ISSUE THREAD

**Issue by dgoodwin** [ansible/ansible#21269]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
local_action

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Seen on Fedora 25 and RHEL 7.

##### SUMMARY

There appears to be a problem where the ansible_host inventory variable appears unset if used within a local_action.

##### STEPS TO REPRODUCE

```yaml
---
- name: Test Play
  hosts:  yourhostgroup
  gather_facts: no
  remote_user: root
  tasks:
  - name: Task 1
    debug: var=inventory_hostname

  - name: Task 2
    debug: var=ansible_host

  - name: Task 3
    local_action:
      module: debug
        var=ansible_host

  - name: Task 4
    local_action:
      module: debug
        var=hostvars[inventory_hostname]['ansible_host']
```

##### EXPECTED RESULTS

We expected Task 4 to output the ansible_host value of "54.158.245.48".

Per https://github.com/ansible/ansible/issues/16139 it appears that this is the recommended way to do something like wait_for in a local_action when waiting for a system to restart. Without it, there appears to be no way to access the host in situations where inventory_hostname cannot be reached from the local system running ansible.

##### ACTUAL RESULTS

Solution from https://github.com/ansible/ansible/issues/16139 appears to no longer work as ansible_host is not defined by default within inventory_vars. (unless you set it yourself explicitly)

```
PLAY [Test Play] ***************************************************************

TASK [Task 1] ******************************************************************
ok: [ded-int-aws-master-dbea1] => {
    "inventory_hostname": "ded-int-aws-master-dbea1"
}
ok: [ded-int-aws-master-4b25f] => {
    "inventory_hostname": "ded-int-aws-master-4b25f"
}
ok: [ded-int-aws-master-9938e] => {
    "inventory_hostname": "ded-int-aws-master-9938e"
}

TASK [Task 2] ******************************************************************
ok: [ded-int-aws-master-dbea1] => {
    "ansible_host": "54.158.245.48"
}
ok: [ded-int-aws-master-4b25f] => {
    "ansible_host": "54.227.231.254"
}
ok: [ded-int-aws-master-9938e] => {
    "ansible_host": "54.242.207.100"
}

TASK [Task 3] ******************************************************************
ok: [ded-int-aws-master-dbea1 -> localhost] => {
    "ansible_host": "localhost"
}
ok: [ded-int-aws-master-4b25f -> localhost] => {
    "ansible_host": "localhost"
}
ok: [ded-int-aws-master-9938e -> localhost] => {
    "ansible_host": "localhost"
}

TASK [Task 4] ******************************************************************
ok: [ded-int-aws-master-dbea1 -> localhost] => {
    "hostvars[inventory_hostname]['ansible_host']": "VARIABLE IS NOT DEFINED!"
}
ok: [ded-int-aws-master-4b25f -> localhost] => {
    "hostvars[inventory_hostname]['ansible_host']": "VARIABLE IS NOT DEFINED!"
}
ok: [ded-int-aws-master-9938e -> localhost] => {
    "hostvars[inventory_hostname]['ansible_host']": "VARIABLE IS NOT DEFINED!"
}

PLAY RECAP *********************************************************************
ded-int-aws-master-4b25f   : ok=4    changed=0    unreachable=0    failed=0   
ded-int-aws-master-9938e   : ok=4    changed=0    unreachable=0    failed=0   
ded-int-aws-master-dbea1   : ok=4    changed=0    unreachable=0    failed=0   
```

We did find a simple workaround just using a set_fact to assign some variable to the value of ansible_host, then using it within the local_action.
