### ISSUE TITLE
win_nssm is not idempodent

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#21289]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_nssm

##### ANSIBLE VERSION
```
2.3.0
```

##### OS / ENVIRONMENT
Target node: Windows Server 2016, control node Bash on Windows 10

##### SUMMARY
The win_nssm module takes a list of parameters in its `app_parameters` option. It seems that these are expected to be key-value options, tho in real life cmds often accept an arbitrary list of params not strictly of the key/value spec. For instance, I'm trying to set up the Consul agent on windows with the following exe and parameters:
 `consul.exe agent -config-dir=C:\apps\consul\config agent`. It's hard to reflect this in win_nssm, and my best attempt so far has been:

```
- name: Make sure the Consul service runs
  win_nssm:
      name: consul
      application: "{{ consul_folder }}\\consul.exe"
      app_parameters:
        "agent": 
        "-config-dir": "{{ consul_folder }}\\config"
      stdout_file: "{{ consul_logs_folder }}\\log.txt"
      stderr_file: "{{ consul_logs_folder }}\\error.txt"
```
This produces the following parameters in nssm: `-config-dir C:\apps\consul\config agent`. Notice that there's doesn't seem to be any way to specify the `=` sign in such a way that it's reflected in the configured service.

While consul graciously accepts a space instead of the equal sign, the win_nssm module does not correctly tract idempodence, and therefore reports `changed:true` on every run.

It seems to me that win_nssm is built around the premise of key/value pairs, when that premise simply doesn't hold true in real-life application

##### STEPS TO REPRODUCE
See above

##### EXPECTED RESULTS
Ansible should report `changed: false`

##### ACTUAL RESULTS
Ansible reports `changed: true`

```
{
   "changed":true,
   "changed_by":"update_app_parameters",
   "nssm_app_parameters":"@{agent=; -config-dir=C:\\apps\\consul\\config}",
   "nssm_app_parameters_keys":[
      "-config-dir",
      "agent"
   ],
   "nssm_app_parameters_parsed":{
      "-config-dir":"C:\\apps\\consul\\config",
      "agent":""
   },
   "nssm_app_parameters_vals":[
      "C:\\apps\\consul\\config",
      ""
   ],
   "nssm_single_line_app_parameters":"-config-dir \"C:\\apps\\consul\\config\"agent \"\""
}
```

**Comment by ansibot** [comment]
cc @smadam813
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by caveman-dick** [comment]
I've currently got some changes in progress fixing some of the issues with this module. This isn't one of them but I've so far added Pester unit-tests so will be able to add support for this fairly easily.

Currently there is a workaround for this kind of problem though, which is to use just one key-pair which is what I'm having to use for a java based service, so this should work for you:

```yaml
- name: Make sure the Consul service runs
  win_nssm:
      name: consul
      application: "{{ consul_folder }}\\consul.exe"
      app_parameters:
        "agent": "-config-dir {{ consul_folder }}\\config" 
      stdout_file: "{{ consul_logs_folder }}\\log.txt"
      stderr_file: "{{ consul_logs_folder }}\\error.txt"
```
Luckily you don't have too many parameters so it doesn't look too bad, mine however makes the line about 200 chars long!
