### ISSUE TITLE
include_role error with with_items (2.3.0 devel)

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible#21285]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
ansible 2.3.0 (devel 59306e2aef) last updated 2017/02/11 12:44:45 (GMT +000)

##### OS / ENVIRONMENT
N/A

##### SUMMARY
include_role fails to execute when used with_items (similar to issue #17966)

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
    - include_role:
        name: '{{ item }}'
      with_items:
        - role1
        - role2
```

##### EXPECTED RESULTS
include_role loops over list and updates item variable

##### ACTUAL RESULTS
```
TASK [include_role] 
ERROR! 'item' is undefined
```

**Comment by smemsh** [comment]
also affects 2.2

**Comment by smemsh** [comment]
note, I couldn't get the `name:` value to expand from *any* variable set at play scope, not just the with_items loop var.

**Comment by Dixon3** [comment]
The same issue...

**Comment by snowsky** [comment]
yes, loop_var not working with include_role.

**Comment by jbilbro** [comment]
I'm hitting this, too.  Any work around you guys have discovered?

**Comment by bearrito** [comment]
I've reproduced this. Does the maintainer need information?

**Comment by broferek** [comment]
I also came to this issue, I need to be able to loop over a list of roles from a fact set in a previous play.

**Comment by lennyby93** [comment]
There is a pull request that contains a fix here: 
[here](https://github.com/ansible/ansible/pull/23104)

**Comment by jbilbro** [comment]
@lennyby93 have you tried it with success?

**Comment by lennyby93** [comment]
yes, I got 'item' to resolve correctly. It looks like the generic vars (like inventory_hostname) still do not resolve. This works now for me:
```
- name: load and run services
  include_role:
    name: "resource_{{ item.resource }}"
  with_items:
    - "{{ services }}"

```

**Comment by jbilbro** [comment]
Posted this on that pull request, too.

I have tried installing these two files on my Ansible 2.3 install on my Ansible Tower 3.1.3 server. When trying to execute a job template, it fails immediately when trying to update from SCM. If I revert these two files everything works fine (other than you know, include_roles failing to take a variable).

`TASK [Set the git repository version] ****************************************** An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'NAMESPACE_FACTS' fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}`

**Comment by holmesb** [comment]
Same happens when trying to loop over tasks_from eg:
```
    - include_role:
        name: a_role
        tasks_from: "{{ item }}"
      with_items:
        - a_task_in_a_role
        - another_task_in_a_role
```
Get error "ERROR! Could not find specified file in role: tasks/{{ item }}".
