### ISSUE TITLE
Module with async not properly handling changed_when conditional?

### ISSUE THREAD

**Issue by mpatenaude** [ansible/ansible#21298]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

async module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### SUMMARY

Trying to set the "changed" state of the "async" task is unsuccessful using the `changed_when` conditional described below.

##### STEPS TO REPRODUCE

The first tasks runs a command in async mode and register the results to `reposync_task`.  Using the `changed_when` conditional, we should set the task "changed" flag to true if `Downloading` is found in the `reposync_task.stdout` string:

```yaml
- name: Synchronize product RPMs for {{ repo_product_name }}/{{ repo_product_version }}
  command: >
    sudo -u {{ repo_owner }} reposync --config="{{ repo_product_folder }}/.reposync_config_{{ repo_product_version }}"
      --download_path="{{ repo_product_folder }}"  --cachedir={{ repo_product_folder }}/.reposync_cache
      --newest-only --repoid="{{ repo_product_version }}"
  async: "{{ 2 * 60 * 60 }}"
  poll: 15
  register: reposync_task
  changed_when: >
    reposync_task.stdout is defined and 'Downloading' in reposync_task.stdout

- name: Set RPM sync status
  set_fact: >
    rpm_changed={{ true if 'Downloading' in reposync_task.stdout else false }}
  tags: always

- debug:
    var: rpm_changed
```

##### EXPECTED RESULTS

Assuming my syntax is correct (was ok in 1.9x), the `changed_when` conditional should set the task "changed" state to `true` since `Downloading` exists in the `reposync_task.stdout`, see the full debug below.

##### ACTUAL RESULTS

The task "changed" state remained to `false`.  But to validate that the 'Downloading' string can be found in the registered variable `reposync_task.stdout`, the subsequent tasks set the boolean `rpm_changed`, i.e `set_fact / debug`, confirms it.

```
TASK [master-repo : Synchronize product RPMs for cdh5/5.9.1] *******************

ok: [ca1-pkg001] => {
    "ansible_job_id": "331275759293.19408", 
    "changed": false, 
    "cmd": [
        "sudo", 
        "-u", 
        "build", 
        "reposync", 
        "--config=/u01/yum-repos/cloudera/cdh5/rhel/7/.reposync_config_5.9.1", 
        "--download_path=/u01/yum-repos/cloudera/cdh5/rhel/7", 
        "--cachedir=/u01/yum-repos/cloudera/cdh5/rhel/7/.reposync_cache", 
        "--newest-only", 
        "--repoid=5.9.1"
    ], 
    "delta": "0:00:00.412403", 
    "end": "2017-02-11 16:30:08.160271", 
    "finished": 1, 
    "invocation": {
        "module_args": {
            "_raw_params": "sudo -u build reposync --config=\"/u01/yum-repos/cloudera/cdh5/rhel/7/.reposync_config_5.9.1\"\n --download_path=\"/u01/yum-repos/cloudera/cdh5/rhel/7\" --cachedir=/u01/yum-repos/cloudera/cdh5/rhel/7/.reposync_cache\n --newest-only --re
poid=\"5.9.1\"", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "async_status"
    }, 
    "rc": 0, 
    "start": "2017-02-11 16:30:07.747868", 
    "stderr": "", 
    "stdout": "[5.9.1: 1     of 118   ] Skipping existing RPMS/noarch/avro-doc-1.7.6+cdh5.9.1+117-1.cdh5.9.1.p0.5.el7.noarch.rpm\n[5.9.1:
< removed >
Downloading RPMS/x86_64/zookeeper-server-3.4.5+cdh5.9.1+99-1.cdh5.9.1.p0.5.el7.x86_64.rpm\n\r zookeeper-server-3.4.5+cdh5.9.1+99-1.cdh5.9.1.p0.5.el7.x | 5.1 kB     00:00     ", 
    "stdout_lines": [ 
        < removed >
    ],
    "warnings": [
        "Consider using 'become', 'become_method', and 'become_user' rather than running sudo"
    ]
}
 [WARNING]: Consider using 'become', 'become_method', and 'become_user' rather than running sudo


TASK [master-repo : Set RPM sync status] ***************************************

ok: [ca1-pkg001] => {
    "ansible_facts": {
        "rpm_changed": true
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "rpm_changed": true
        }, 
        "module_name": "set_fact"
    }
}

TASK [master-repo : debug] *****************************************************

ok: [ca1-pkg001] => {
    "rpm_changed": true
}
```

**Comment by mpatenaude** [comment]
I wrote a quicker / easier to reproduce example:

```yaml
---
- hosts: test-hosts
  gather_facts: False
  become: False

  tasks:
  - name: Test updating the task changed status flag using changed_when conditional
    shell: |
      sleep 15
      echo "Downloading"
      sleep 15
    async: "{{ 2 * 60 * 60 }}"
    poll: 5
    register: async_status
    changed_when: >
      async_status.stdout is defined and 'Downloading' in async_status.stdout

  - name: Set status_changed based on async_status stdout value
    set_fact: >
      status_changed={{ true if 'Downloading' in async_status.stdout else false }}
```

Executing with `-vvv` produce the results described earlier: the first task does not get its `changed` flag set to `true`, even if `Downloading` exists in the `stdout`:

```
TASK [Test updating the task changed status flag using changed_when conditional] ***
....
ok: [test-hosts] => {
    "ansible_job_id": "670074154997.22941", 
    "changed": false, 
    "cmd": "sleep 15\n echo \"Downloading\"\n sleep 15", 
    "delta": "0:00:30.003610", 
    "end": "2017-02-12 14:29:17.158970", 
    "finished": 1, 
    "invocation": {
        "module_args": {
            "_raw_params": "sleep 15\n echo \"Downloading\"\n sleep 15", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "async_status"
    }, 
    "rc": 0, 
    "start": "2017-02-12 14:28:47.155360", 
    "stderr": "", 
    "stdout": "Downloading", 
    "stdout_lines": [
        "Downloading"
    ], 
    "warnings": []
}

TASK [Set status_changed based on async_status stdout value] *******************

ok: [test-hosts] => {
    "ansible_facts": {
        "status_changed": true
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "status_changed": true
        }, 
        "module_name": "set_fact"
    }
}

PLAY RECAP *********************************************************************
test-hosts                 : ok=2    changed=0    unreachable=0    failed=0   
```


If I run the same first task, without checking if `async_status.stdout` is defined in the `changed_when` conditional, ex:

```yaml
    changed_when: >
      'Downloading' in async_status.stdout
```

It results in an undefined var error:

```
TASK [Test updating the task changed status flag using changed_when conditional] ***
...
fatal: [test-hosts]: FAILED! => {
    "failed": true, 
    "msg": "The conditional check ''Downloading' in async_status.stdout\n' failed. The error was: error while evaluating conditional ('Downloading' in async_status.stdout\n): Unable to look up a name or access an attribute in template string ({% if 'Downloading' in async_status.stdout\n %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"
```

If I now re-write the conditional using python `find()` method instead, I get a different output, but similar results.  This time it clearly indicates that `stdout` is not defined:

```yaml    
    changed_when: >
      async_status.stdout.find("Downloading") != -1
```
Results:
```
fatal: [test-hosts]: FAILED! => {
    "failed": true, 
    "msg": "The conditional check 'async_status.stdout.find(\"Downloading\") != -1\n' failed. The error was: error while evaluating conditional (async_status.stdout.find(\"Downloading\") != -1\n): 'dict object' has no attribute 'stdout'"
}
```

Not certain why this last example is not "templated" the same way, but that may be normal...
