### ISSUE TITLE
Git: depth=1 prevents checking out a tag

### ISSUE THREAD

**Issue by nedbat** [ansible/ansible#21316]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

git

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Observed on Mac OS/X and Ubuntu 16.04

##### SUMMARY

If you use `depth: 1` on a git clone, then you will not be able to use `version: any_tag` successfully.

##### STEPS TO REPRODUCE

```yaml
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
    - name: make a deep clone
      git:
        repo: git@github.com:edx/ecommerce.git
        dest: deep
        version: open-release/ficus.1rc3

    - name: make a shallow clone
      git:
        repo: git@github.com:edx/ecommerce.git
        dest: shallow
        version: open-release/ficus.1rc3
        depth: 1

```

##### EXPECTED RESULTS

I expected to get two clones of my git repo, `shallow` and `deep`, each checked out to the requested tag.

##### ACTUAL RESULTS

My `deep` repo is as I wanted, checked out to the tag.  The `shallow` repo is incorrectly checked out to `master`, and ansible has failed.

```
$ ansible-playbook -i 127.0.0.1, ./test.yml

PLAY [127.0.0.1] ***************************************************************

TASK [make a deep clone] *******************************************************
changed: [127.0.0.1]

TASK [make a shallow clone] ****************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/git checkout --force open-release/ficus.1rc3", "failed": true, "msg": "Failed to checkout open-release/ficus.1rc3", "rc": 1, "stderr": "error: pathspec 'open-release/ficus.1rc3' did not match any file(s) known to git.\n", "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/Users/ned/foo/ansible_git_bug/test.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=1
```

Using direct git commands, adding `--no-single-branch` would solve this problem, by getting a little bit of history from all the branches.

I think this is the same root cause as #19074, though this issue is a simpler use-case, since one clone is all it takes, rather than cloning and then later checking out a different revision.

Also, note that specifying a branch as version works fine. Only tags are affected.

**Comment by robinro** [comment]
We should not have `--no-single-branch` in general. This effectively download the majority of the repo for typical repos, that have tags for releases going back the full history. 
See e.g. https://github.com/ansible/ansible/issues/14954 for a potential regression then.

There is a (simple) workaround: Add a `reference`.

The solution is probably to add `--branch` to the clone. One should extend the test coverage to prevent regressions on this.

**Comment by nedbat** [comment]
@robinro i'm sorry, i don't understand how `reference` helps? That refers to another repo?

**Comment by robinro** [comment]
I meant `refspec`, but when trying to build an example I just found in the current state this only works with hashes, not tags:
```
        git: 
          repo: git@github.com:edx/ecommerce.git
          dest: shallow
          version: '52b86ef4168707df94de7921b8bbbe25026c8ac8'
          refspec: 'open-release/ficus.master'
          depth: 1
```

In the integration tests we already have a test for switching to a tag on a shallow clone, but not for the initial clone...
