### ISSUE TITLE
win_regedit doesn't create new entries 

### ISSUE THREAD

**Issue by leerich** [ansible/ansible#21362]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_regedit

##### ANSIBLE VERSION

```
ansible-2.2.1.0-1.el7.noarch
ansible-tower-3.0.3-1.el7.centos.x86_64
```

##### SUMMARY

win_regedit module can create paths but not any entries underneath the path

##### STEPS TO REPRODUCE

```yaml
---
- name: test windows registry module
  hosts: all
  connection: winrm
  gather_facts: false
  
  tasks:
  
    - name: change registry
      win_regedit:
        key: HKLM:\Software\Ansible
        name: hello
        data: 1337
        type: dword
        state: present
       
    - win_regedit:
         key: HKLM:\Software\\Microsoft\inetstp
         name: PathWWWRoot-test
         data: E:\\Inetpub\\wwwroot
         type: dword
         state: present
```

##### EXPECTED RESULTS

Expect the results to be reflected in regedit on the windows machine

##### ACTUAL RESULTS

When run from Tower:

```
Using /etc/ansible/ansible.cfg as config file
SSH password: 
Vault password: 

PLAYBOOK: registry-test.yaml ***************************************************
1 plays in windows/registry-test.yaml

PLAY [test windows registry module] ********************************************

TASK [change registry] *********************************************************
task path: /var/lib/awx/projects/_3796__ansible_examples_lr/windows/registry-test.yaml:16
 [WARNING]: Module invocation had junk after the JSON data:

ok: [54.161.41.218] => {"changed": false, "data_changed": false, "data_type_changed": false}

TASK [win_regedit] *************************************************************
task path: /var/lib/awx/projects/_3796__ansible_examples_lr/windows/registry-test.yaml:24
 [WARNING]: Module invocation had junk after the JSON data:

ok: [54.161.41.218] => {"changed": false, "data_changed": false, "data_type_changed": false}

PLAY RECAP *********************************************************************
54.161.41.218              : ok=2    changed=0    unreachable=0    failed=0   
```

**Comment by ansibot** [comment]
cc @joshludwig @smadam813
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
Hi

I think the double backslash in 

HKLM:\Software\\Microsoft\inetstp

might be confusing things here - please could you try again without the second \ between 'Software' and 'Microsoft'

By the way this module has had some bug fixing in the latest version of ansible (2.3 in development) so it would be very useful if you could test with latest development version of ansible.

**Comment by jhawkesworth** [comment]
needs_info

**Comment by leerich** [comment]
Yes, I've tried it both ways and it gives me the same result.  In my first example I am only using single back slashes.

**Comment by leerich** [comment]
I just tested with Tower 3.1 and the latest modules on github and got the same result.  This time the module is more particular about the slashes and will only take a single slash.

**Comment by jhawkesworth** [comment]
Well that's odd.

I just tried your playbook and the first example works fine.
The second fails as is, because the value you want to set 'E:\\Inetpub\\wwwroot' can't be converted to a dword, so I just commented out the following line (default type is 'string') and it ran fine, and I can see the changes in regedit.
         type: dword

what version of windows are you targetting?  Please ensure you are checking the registry from 64bit perspective (there's a 32 bit version of regedit on 64 bit boxes which I think only 'sees' the 32 bit part of the registry).

needs_info

**Comment by leerich** [comment]
The first example only works for me in that it creates the registry path HKLM:\Software\Ansible but then it doesn't seem to create the entries underneath.  In your example did you see the entries underneath?  I'm targeting Windows 2012 R2.  I tried looking at the registry with both regedit and regedt32.  Is there something else I should be using to check the entries?  

Thanks!

**Comment by jhawkesworth** [comment]
Yes the stuff is there under the key for me in both cases.  To be fair, I have probably run the playbook a few times. So I just pruned both keys and re-ran once... and both keys and the values they contain are present.
I was using a s2012r2 vm as well.


Here is the exact playbook I used:
```yaml

---
- name: test windows registry module
  hosts: WIN-12.home
  connection: winrm
  gather_facts: false

  tasks:

    - name: change registry
      win_regedit:
        key: HKLM:\Software\Ansible
        name: hello
        data: 1337
        type: dword
        state: present

    - win_regedit:
         key: HKLM:\Software\Microsoft\inetstp
         name: PathWWWRoot-test
         data: E:\\Inetpub\\wwwroot
#         type: dword
         state: present
```

Only differences I can think of are I am using latest development version of ansible.
