### ISSUE TITLE
Unarchive module catastrophically changes root directory access rights

### ISSUE THREAD

**Issue by michal-jewel** [ansible/ansible#21397]
##### ISSUE TYPE
 - Bug Report

NOTE: This is rather catastrophic failure.

##### COMPONENT NAME
 - Unarchive module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /Users/michal/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
[defaults]
allow_world_readable_tmpfiles: true
```

##### OS / ENVIRONMENT
Managed OS: Ubuntu Linux 16.04 LTS

##### SUMMARY
Unarchive with `--strip-components=1` on an archive without any root paths works, but changes access rights to root directory to "root only read write", which breaks all user access.

```yaml
      - name:   "Unpack Apache Spark"                                      
        unarchive:                                                         
          src:         "/home/username/Downloads/spark-2_1_0-bin-hadoop2_7.tgz"
          dest:       "/usr/local/share/spark"                             
          remote_src:  yes                                                 
          mode:        0440                                                
          extra_opts: ['--strip-components=1']
```

##### STEPS TO REPRODUCE
Use the following playbook, and say goodbye to non-root login:
*WARNING* This may disable all your user accounts!

```yaml
  - hosts: all
  - tasks:
      - name: "Create Downloads directory"        
        file:                                     
          path:  /home/username/Downloads         
          state: directory                        
          mode:  0755                             
      - name:   "Download Apache Spark"           
        get_url:                                  
          url:  "http://d3kbcqa49mib13.cloudfront.net/spark-2.1.0-bin-hadoop2.7.tgz"
          dest:             "/home/username/Downloads/spark-2_1_0-bin-hadoop2_7.tgz"
          mode: 0440                              
      - name: "Create Spark directory"            
        file:                                     
          path:  /usr/local/share/spark           
          state: directory                        
          mode:  0755                             
      - name:   "Unpack Apache Spark"             
        unarchive:                                
          src:              "/home/username/Downloads/spark-2_1_0-bin-hadoop2_7.tgz"
          dest:       "/usr/local/share/spark"    
          remote_src:  yes                        
          mode:        0440                       
          extra_opts: ['--strip-components=1', "-C /usr/local/share/spark"]
```

##### EXPECTED RESULTS
Running this playbook, you will see:
```
TASK [Unpack Apache Spark] *****************************************************
 [WARNING]: Module invocation had junk after the JSON data: /bin/sh: 1: sleep: Permission denied

changed: [1.2.3.4]
```
Listing access rights to root directory from root account gives:
```
bash$ ls -alth /
dr--r-----  22 root root 4.0K Sep 15 21:11 .
dr--r-----  22 root root 4.0K Sep 15 21:11 ..
```

##### ACTUAL RESULTS

No idea why and how it happens, but here are Ansible logs at -vvvv

```
TASK [Unpack Apache Spark] *****************************************************
task path: /Users/michal/src/voldemort-vm/config.yml:259
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: username
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r 1.2.3.4 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487068628.77-3385553654911 `" && echo ansible-tmp-1487068628.77-3385553654911="` echo ~/.ansible/tmp/ansible-tmp-1487068628.77-3385553654911 `" ) && sleep 0'"'"''
Using module file /usr/local/Cellar/ansible/2.2.1.0/libexec/lib/python2.7/site-packages/ansible/modules/core/files/stat.py
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: username
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r 1.2.3.4 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487068628.89-18627339563725 `" && echo ansible-tmp-1487068628.89-18627339563725="` echo ~/.ansible/tmp/ansible-tmp-1487068628.89-18627339563725 `" ) && sleep 0'"'"''
<1.2.3.4> PUT /var/folders/b_/psf56c3d1vn34tm8mm3x501r0000gp/T/tmpKU2jxY TO /home/username/.ansible/tmp/ansible-tmp-1487068628.89-18627339563725/stat.py
<1.2.3.4> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r '[1.2.3.4]'
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: username
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r 1.2.3.4 '/bin/sh -c '"'"'chmod u+x /home/username/.ansible/tmp/ansible-tmp-1487068628.89-18627339563725/ /home/username/.ansible/tmp/ansible-tmp-1487068628.89-18627339563725/stat.py && sleep 0'"'"''
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: username
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r -tt 1.2.3.4 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-gtdoezchpqakpvijkjoqhrvhjsrbrpkg; /usr/bin/python /home/username/.ansible/tmp/ansible-tmp-1487068628.89-18627339563725/stat.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
Using module file /usr/local/Cellar/ansible/2.2.1.0/libexec/lib/python2.7/site-packages/ansible/modules/core/files/unarchive.py
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: username
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r 1.2.3.4 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487068629.41-74555029658256 `" && echo ansible-tmp-1487068629.41-74555029658256="` echo ~/.ansible/tmp/ansible-tmp-1487068629.41-74555029658256 `" ) && sleep 0'"'"''
<1.2.3.4> PUT /var/folders/b_/psf56c3d1vn34tm8mm3x501r0000gp/T/tmpdHuMwo TO /home/username/.ansible/tmp/ansible-tmp-1487068629.41-74555029658256/unarchive.py
<1.2.3.4> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r '[1.2.3.4]'
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: username
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r 1.2.3.4 '/bin/sh -c '"'"'chmod u+x /home/username/.ansible/tmp/ansible-tmp-1487068629.41-74555029658256/ /home/username/.ansible/tmp/ansible-tmp-1487068629.41-74555029658256/unarchive.py && sleep 0'"'"''
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: username
<1.2.3.4> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=username -o ConnectTimeout=10 -o ControlPath=/Users/michal/.ansible/cp/ansible-ssh-%h-%p-%r -tt 1.2.3.4 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-vefpwcwkynrvbpsxfbswcjhycrakqpha; /usr/bin/python /home/username/.ansible/tmp/ansible-tmp-1487068629.41-74555029658256/unarchive.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
 [WARNING]: Module invocation had junk after the JSON data: /bin/sh: 1: sleep: Permission denied

changed: [1.2.3.4] => {
    "changed": true, 
    "dest": "/usr/local/share/spark", 
    "gid": 0, 
    "group": "root", 
    "handler": "TgzArchive", 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "copy": true, 
            "creates": null, 
            "delimiter": null, 
            "dest": "/usr/local/share/spark", 
            "directory_mode": null, 
            "exclude": [], 
            "extra_opts": [
                "--strip-components=1"
            ], 
            "follow": false, 
            "force": null, 
            "group": null, 
            "keep_newer": false, 
            "list_files": false, 
            "mode": 288, 
            "original_basename": "spark-2_1_0-bin-hadoop2_7.tgz", 
            "owner": null, 
            "regexp": null, 
            "remote_src": true, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/home/username/Downloads/spark-2_1_0-bin-hadoop2_7.tgz", 
            "unsafe_writes": null, 
            "validate_certs": true
        }
    }, 
    "mode": "0755", 
    "owner": "root", 
    "size": 4096, 
    "src": "/home/username/Downloads/spark-2_1_0-bin-hadoop2_7.tgz", 
    "state": "directory", 
    "uid": 0
}
```
