### ISSUE TITLE
Cannot use gitlab_user and gitlab_group with authorization by password and self-signed certificate

### ISSUE THREAD

**Issue by kharkevich** [ansible/ansible#21414]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

modules/source_control/gitlab_user
modules/source_control/gitlab_group

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Cannot use gitlab_user and gitlab_group with authorization by password and self-signed certificate
(validate_certs: False options is not used)
##### STEPS TO REPRODUCE

Setup GitLab with self-signed certificate
Try to configure it by ansible using gitlab_user or gitlab_group with password authorization

```yaml
- name: Create Gitlab User
  gitlab_user:
    server_url: https://gitlab.dj-wasabi.local
    validate_certs: False
    login_user: dj-wasabi
    login_password: MySecretPassword
    name: My Name
    username: myusername
    password: mysecretpassword
    email: me@example.com
    sshkey_name: MySSH
    sshkey_file: ssh-rsa AAAAB3NzaC1yc...
    state: present
  delegate_to: localhost
```

##### EXPECTED RESULTS

GitLab was configured successfully

##### ACTUAL RESULTS

```
Failed to connect to Gitlab server: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
```
