### ISSUE TITLE
when statement issue when used over a with_dict loop variable

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#21425]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

when
##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.1
ansible 2.3.0 commit git20170213.f2c22109f
```
##### CONFIGURATION

inventory = ./hosts
roles_path = /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/Roles/roles
fact_caching = redis
fact_caching_timeout = 86400
##### OS / ENVIRONMENT
- **Local host**: Ubuntu 16.10 4.8
- **Target nodes**: 
  - NX-OSv-9k 7.0(3)I5(1) (last release available in Cisco VIRL)
##### SUMMARY

Using the when statement over a with_dict loop variable is inoperative when we dig into the data structure
##### STEPS TO REPRODUCE

Interfaces data model excerpt

```
interfaces:
        mgmt0: # name
          description: "Management interface 0"
          state: present
          admin_state: up
...
          url: "mgmt_0.NX_OSv_Spine_31.actionmystique.net"
          ip_address: "172.21.100.31"
          ip_subnet_length: 24
          ip_address_secondary: 
          ip_subnet_length_secondary:
          ip_unnumbered_loopback_id:
          ipv6_address:
          ipv6_subnet_length:
...
        loopback0: # name
          description: "Loopback interface 0"
          state: present
          admin_state: up
...
          url: "loopback_0.NX_OSv_Spine_31.actionmystique.net"
          ip_address: "172.21.0.31"
          ip_subnet_length: 32
          ip_address_secondary: 
          ip_subnet_length_secondary:
          ip_unnumbered_loopback_id:
          ipv6_address:
          ipv6_subnet_length:
...
```

**Role**: nxos_ip_interfaces

```
...
- name: Managing all IPv6 interface(s) on the remote node
  nxos_ip_interface:
        provider: "{{ connections.nxapi }}"
        addr: "{{ item.value.ipv6_address }}"
        interface: "{{ item.key }}"
        mask: "{{ item.value.ipv6_subnet_length }}"
        state: "{{ item.value.state }}"
  with_dict: "{{ interfaces }}"
  when: item.value.ipv6_address is defined
  register: status
...
```

**Playbook**: interfaces.yml

```
- name: Configuring all L3 interfaces on NX-OS/NX-OSv/NX-OS-9k/NX-OSv-9k
  hosts:
    - nx_os
    - nx_osv
    - nx_os_9k
    - nx_osv_9k
  roles:
    - { role: nxos_ip_interfaces, command: 'all' }
```

##### EXPECTED RESULTS

- The task "Managing all IPv6 interface(s) on the remote node" should not be played since no interfaces.ipv6_address is defined
- A null variable should not be considered as defined.

##### ACTUAL RESULTS

```
TASK [nxos_ip_interfaces : Managing all IPv6 interface(s) on the remote node] **
task path: /home/actionmystique/Program-Files/Ubuntu/Ansible/Roles/roles/nxos_ip_interfaces/tasks/main.yml:88
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/network/nxos/nxos_ip_interface.py
<172.21.100.31> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.100.31> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
failed: [NX_OSv_Spine_31] (item={'key': u'loopback0', 'value': {u'fhrp': None, u'ip_subnet_length_secondary': None, u'ipv6_address': None, u'svi_anycast_gateway': False, u'switchport_type': None, u'speed': u'auto', u'ipv6_subnet_length': None, u'duplex': u'auto', u'pvlan.primary': None, u'delay': None, u'state': u'present', u'ip_subnet_length': 32, u'mtu': None, u'type': u'loopback', u'pvlan.secondary': None, u'vmac': None, u'description': u'Loopback interface 0', u'ip_unnumbered_loopback_id': None, u'svi_ip_forward': u'enable', u'vlan': None, u'mac': None, u'admin_state': u'up', u'ip_address_secondary': None, u'ip_address': u'172.21.0.31', u'url': u'loopback_0.NX_OSv_Spine_31.actionmystique.net', u'operational_state': None, u'mode': u'layer3', u'vm_tracker': u'disabled', u'vrf': None}}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "addr": "", 
            "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "authorize": false, 
            "config": null, 
            "host": "172.21.100.31", 
            "include_defaults": "True", 
            "interface": "loopback0", 
            "mask": "", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 8080, 
            "provider": {
                "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "host": "172.21.100.31", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": "8080", 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "admin", 
                "validate_certs": false
            }, 
            "save": false, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": "nxapi", 
            "use_ssl": false, 
            "username": "admin", 
            "validate_certs": false, 
            "version": "v4"
        }, 
        "module_name": "nxos_ip_interface"
    }, 
    "item": {
        "key": "loopback0", 
        "value": {
            "admin_state": "up", 
            "delay": null, 
            "description": "Loopback interface 0", 
            "duplex": "auto", 
            "fhrp": null, 
            "ip_address": "172.21.0.31", 
            "ip_address_secondary": null, 
            "ip_subnet_length": 32, 
            "ip_subnet_length_secondary": null, 
            "ip_unnumbered_loopback_id": null, 
            "ipv6_address": null, 
            "ipv6_subnet_length": null, 
            "mac": null, 
            "mode": "layer3", 
            "mtu": null, 
            "operational_state": null, 
            "pvlan.primary": null, 
            "pvlan.secondary": null, 
            "speed": "auto", 
            "state": "present", 
            "svi_anycast_gateway": false, 
            "svi_ip_forward": "enable", 
            "switchport_type": null, 
            "type": "loopback", 
            "url": "loopback_0.NX_OSv_Spine_31.actionmystique.net", 
            "vlan": null, 
            "vm_tracker": "disabled", 
            "vmac": null, 
            "vrf": null
        }
    }, 
    "mask": "", 
    "msg": "Warning! 'mask' must be an integer between 1 and 32 when version v4 and up to 128 when version v6.", 
    "version": "v4"
}
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/network/nxos/nxos_ip_interface.py
<172.21.100.31> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
failed: [NX_OSv_Spine_31] (item={'key': u'mgmt0', 'value': {u'fhrp': None, u'ip_subnet_length_secondary': None, u'ipv6_address': None, u'svi_anycast_gateway': False, u'switchport_type': None, u'speed': u'auto', u'ipv6_subnet_length': None, u'duplex': u'auto', u'pvlan.primary': None, u'delay': None, u'state': u'present', u'ip_subnet_length': 24, u'mtu': None, u'type': None, u'pvlan.secondary': None, u'vmac': None, u'description': u'Management interface 0', u'ip_unnumbered_loopback_id': None, u'svi_ip_forward': u'enable', u'vlan': None, u'mac': None, u'admin_state': u'up', u'ip_address_secondary': None, u'ip_address': u'172.21.100.31', u'url': u'mgmt_0.NX_OSv_Spine_31.actionmystique.net', u'operational_state': None, u'mode': u'layer3', u'vm_tracker': u'disabled', u'vrf': None}}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "addr": "", 
            "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "authorize": false, 
            "config": null, 
            "host": "172.21.100.31", 
            "include_defaults": "True", 
            "interface": "mgmt0", 
            "mask": "", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 8080, 
            "provider": {
                "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "host": "172.21.100.31", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": "8080", 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "admin", 
                "validate_certs": false
            }, 
            "save": false, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": "nxapi", 
            "use_ssl": false, 
            "username": "admin", 
            "validate_certs": false, 
            "version": "v4"
        }, 
        "module_name": "nxos_ip_interface"
    }, 
    "item": {
        "key": "mgmt0", 
        "value": {
            "admin_state": "up", 
            "delay": null, 
            "description": "Management interface 0", 
            "duplex": "auto", 
            "fhrp": null, 
            "ip_address": "172.21.100.31", 
            "ip_address_secondary": null, 
            "ip_subnet_length": 24, 
            "ip_subnet_length_secondary": null, 
            "ip_unnumbered_loopback_id": null, 
            "ipv6_address": null, 
            "ipv6_subnet_length": null, 
            "mac": null, 
            "mode": "layer3", 
            "mtu": null, 
            "operational_state": null, 
            "pvlan.primary": null, 
            "pvlan.secondary": null, 
            "speed": "auto", 
            "state": "present", 
            "svi_anycast_gateway": false, 
            "svi_ip_forward": "enable", 
            "switchport_type": null, 
            "type": null, 
            "url": "mgmt_0.NX_OSv_Spine_31.actionmystique.net", 
            "vlan": null, 
            "vm_tracker": "disabled", 
            "vmac": null, 
            "vrf": null
        }
    }, 
    "mask": "", 
    "msg": "Warning! 'mask' must be an integer between 1 and 32 when version v4 and up to 128 when version v6.", 
    "version": "v4"
}
...
```
##### Troubleshooting
- Using latest dev ansible version instead of 2.2.1 does not change anything
- Replacing (item.value.ipv6_address is defined) by not (item.value.ipv6_address == "") does not change anything

```

**Comment by ryansb** [comment]
This seems to have more to do with the use of `defined`. This should work if you use a test like `item.value.ipv6_address | bool`. The `== ""` check won't pass either, because the value is `null`, not empty string. 

If using `|bool` or `not item.value.ipv6 is None` doesn't fix your issue, feel free to reopen.

**Comment by jean-christophe-manciot** [comment]
- ```not item.value.ipv6 is None``` is not recognized by ansible:
  ```The conditional check 'not (item.value.ip_address is None)' failed. The error was: no test named 'None'```
- ```tem.value.ipv6_address | bool``` checks if the variable is a boolean or not, which is not the use case
- there is **no reason why ```item.value.ipv6_address is defined``` should not work**.

Trying to use a workaround & closing this issue won't trigger an investigation & a solution: someone else will inevitably hit the same issue sooner rather than later.
Please do not close any issue unless you have tested that it is truly not an issue or your proposal does work.
We spend quite some time writing them carefully.

**Comment by jean-christophe-manciot** [comment]
Cf. [official documentation](http://docs.ansible.com/ansible/playbooks_conditionals.html#the-when-statement) about ```defined``` used with when:
```
If a required variable has not been set, you can skip or fail using Jinja2’s defined test. For example:

tasks:
    - shell: echo "I've got '{{ foo }}' and am not afraid to use it!"
      when: foo is defined

    - fail: msg="Bailing out. this play requires 'bar'"
      when: bar is undefined
```
