### ISSUE TITLE
postgresql_user fails against an existing user when using 'expires'

### ISSUE THREAD

**Issue by billietl** [ansible/ansible#21453]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT
Debian 8-based docker container, installed via pip.
Playbook is run via user `ansible`, which has sudo rights `ALL = NOPASSWD : ALL` and `ALL =(postgres) NOPASSWD : ALL`.

##### SUMMARY
When running the following task, creating the user works, but fails when the user already exists.
Workaround found : remove `expires` argument from the module. Of course, this is not a really acceptable workaround since it remove some functionnality from the module...

##### STEPS TO REPRODUCE
Run the following tasks against a fresh debian 8 install.
```yaml
  tasks:
    - name: Install PostgreSQL
      apt:
        name="{{item}}"
        state=present
        update_cache=yes
      with_items:
        - "postgresql-9.4"
        - "postgresql-client-9.4"
        - "postgresql-contrib-9.4"

    - postgresql_user:
        name              :  "foo"
        password          :  "bar"
        db                :  "postgres"
        expires           : 'infinity'
        role_attr_flags   :  'NOSUPERUSER,LOGIN'
        state             :  "present"
        login_user        :  "postgres"
        port              :  '5432'
      become         :  yes
      become_user    :  "postgres"
      become_method  :  sudo
```

##### EXPECTED RESULTS
It should run without errors.

##### ACTUAL RESULTS
On the second run, the task fails :
```
TASK [postgresql_user] *********************************************************
task path: /usr/local/ansible/orchestrator/playbooks/test.yml:22
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/database/postgresql/postgresql_user.py
<baz> ESTABLISH SSH CONNECTION FOR USER: None
<baz> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ansible/.ansible/cp/ansible-ssh-%h-%p-%r baz '/bin/sh -c '"'"'sudo -H -S -n -u postgres /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-mcuvxudmkvmshlccczlwbqaaeuavmidx; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [baz]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "postgresql_user"
    }, 
    "module_stderr": "OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016\r\ndebug1: Reading configuration data /home/ansible/.ssh/config\r\ndebug1: /home/ansible/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 8179\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nTraceback (most recent call last):\n  File \"/tmp/ansible_RDMjms/ansible_module_postgresql_user.py\", line 666, in <module>\n    main()\n  File \"/tmp/ansible_RDMjms/ansible_module_postgresql_user.py\", line 621, in main\n    changed = user_alter(cursor, module, user, password, role_attr_flags, encrypted, expires, no_password_changes)\n  File \"/tmp/ansible_RDMjms/ansible_module_postgresql_user.py\", line 277, in user_alter\n    expires_changing = (expires is not None and expires == current_roles_attrs['rol_valid_until'])\nNameError: global name 'current_roles_attrs' is not defined\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```
