### ISSUE TITLE
Lambda: unsupported parameter for module: environment_variable

### ISSUE THREAD

**Issue by kmcnallymetapack** [ansible/ansible#21455]
##### ISSUE TYPE

 - Documentation Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.1.0

```

##### OS / ENVIRONMENT
```
macOS Sierra 10.12.2
boto
boto3
python >= 2.6
```

##### SUMMARY
```
When running task to create lambda function, if I add the environment_variables parameter the task fails with msg:
unsupported parameter for module: environment_variables
When I comment the line out it runs fine.
```

##### STEPS TO REPRODUCE

```yaml
file lambda-create-function.yml

- name: Create lambda function
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Create lambda function
    lambda:
      name: "{{ lambda_name }}"
      description: "{{ lambda_description }}"
      state: 'present'
      timeout: "{{ lambda_timeout }}"
      zip_file: "{{ lambda_zip_file }}"
      runtime: "{{ lambda_runtime }}"
      memory_size: "{{ lambda_memory_size }}"
      handler: "{{ lambda_handler }}"
      role: "{{ lambda_iam_role_arn }}"
      vpc_subnet_ids: "{{ lambda_vpc_subnet_ids }}"
      vpc_security_group_ids: "{{ lambda_vpc_security_group_ids }}"
      environment_variables: "{{ lambda_environment_variables }}"

ansible-playbook lambda-create-function.yml
```

##### EXPECTED RESULTS
```
Play should run without errors as it does without the  environment_variables parameter
```

##### ACTUAL RESULTS
```
TASK [Create lambda function] **************************************************
task path: /Users/kmcnally/git/devops-infrastructure/ansible/tasks/lambda-create-function.yml:21
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: environment_variables"}
```
