### ISSUE TITLE
hash filter is broken with non-ascii and on python3 due to lack of encoding

### ISSUE THREAD

**Issue by naveens** [ansible/ansible#21452]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Hashing filters

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
CentOS 7, Python 3.5

##### SUMMARY
An ASCII file that was slurped could not be hashed. It fails with `Unicode-objects must be encoded before hashing`

##### STEPS TO REPRODUCE

- touch a file `openssl.cnf` with some plaintext data
- run the below playbook (client should run with Python 3.5)

```yaml
---

- hosts: localhost
  tasks:
    - name: slurp openssl.cnf content
      slurp:
        src: "openssl.cnf"
      register: openssl_cnf
      run_once: true

    - name: record openssl.cnf hash
      set_fact:
        openssl_cnf_sha1: "{{ openssl_cnf.content | hash('sha1') }}"
```

##### EXPECTED RESULTS
It's expected the openssl_cnf_sha1 fact is set, which is the case when run with python 2.
```
TASK [record openssl.cnf hash] *************************************************
ok: [localhost] => {"ansible_facts": {"openssl_cnf_sha1": "8a7426daafe2edf55e2adeb3500d2628915a171d"}, "changed": false}
```

##### ACTUAL RESULTS
The hashing filter failed with the below error:

```
TASK [record openssl.cnf hash] *************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected templating type error occurred on ({{ openssl_cnf.content | hash('sha1') }}): Unicode-objects must be encoded before hashing"}

```
