### ISSUE TITLE
with_items + when + __getitem__ = "when" ignored

### ISSUE THREAD

**Issue by kazh000** [ansible/ansible#21465]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- core

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

```
Debian GNU/Linux 8
# uname -a
Linux vm-ansible 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
```
##### SUMMARY

"when:" doesn't work with conjunction "with_items:" and `__getitem__`

##### STEPS TO REPRODUCE

run playbook

```yaml
---
- hosts: host1 host2
  vars:
# Only for comparison
    test_list: [ it1, it2 ]
# Simulating set variables in role/vars/main.yml
    test_array: { name1: [ it1, it2 ], name2: [ it3, it4 ] }

  tasks:

  - name: Simulating to set variables in host_vars/host1
    set_fact:
      list_roles: [ role_bug ]
      test_name: name1
    when: inventory_hostname == "host1"

  - name: Debug print vars
    debug: msg={{ item }}
    with_items: "{{ test_list }}"
    when: "{{ list_roles is defined and 'role_bug' in list_roles }}"

  - name: Debug print vars
    debug: msg={{ test_array[test_name] }}
    when: "{{ list_roles is defined and 'role_bug' in list_roles }}"

  - name: Debug print vars
    debug: msg={{ item }}
    with_items: "{{ test_array[test_name] }}"
    when: "{{ list_roles is defined and 'role_bug' in list_roles }}"

```

##### EXPECTED RESULTS

I expect "skipping" instead of "fatal"
##### ACTUAL RESULTS

```
PLAY [host1 host2] *************************************************************

TASK [setup] *******************************************************************
ok: [host2]
ok: [host1]

TASK [Simulating to set variables in host_vars/bug1] ***************************
ok: [host1]
skipping: [host2]

TASK [Debug print vars] ********************************************************
ok: [host1] => (item=it2) => {
    "item": "it2",                                                                                                                                          
    "msg": "it2"                                                                                                                                            
}                                                                                                                                                           
ok: [host1] => (item=it1) => {
    "item": "it1",                                                                                                                                          
    "msg": "it1"                                                                                                                                            
}                                                                                                                                                           
skipping: [host2] => (item=it1) 
skipping: [host2] => (item=it2) 

TASK [Debug print vars] ********************************************************
skipping: [host2]
ok: [host1] => {
    "msg": [
        "it1", 
        "it2"
    ]
}

TASK [Debug print vars] ********************************************************
fatal: [host2]: FAILED! => {"failed": true, "msg": "'test_name' is undefined"}
ok: [host1] => (item=it1) => {
    "item": "it1", 
    "msg": "it1"
}
ok: [host1] => (item=it2) => {
    "item": "it2", 
    "msg": "it2"
}
        to retry, use: --limit @/etc/ansible/playbooks/bug.retry

PLAY RECAP *********************************************************************
host1                      : ok=5    changed=0    unreachable=0    failed=0   
host2                      : ok=1    changed=0    unreachable=0    failed=1
```
