### ISSUE TITLE
Ansible-playbook ignore hosts custom python interpreter

### ISSUE THREAD

**Issue by yaniveliash** [ansible/ansible#21468]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
any component - not a specific one

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
From : OSX
To : Ubuntu 16.04

##### SUMMARY
Creating a dynamic hosts file while provisioning ec2 instances but ansible
ignore my request to use python3 interpreter and fails due to that.

##### STEPS TO REPRODUCE
```yaml
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Provision a set of instances
      ec2:
         key_name: AWS
         region: eu-west-1
         group: default
         instance_type: t2.micro
         image: ami-6f587e1c # For Ubuntu 14.04 LTS use ami-b9b394ca # For Ubuntu 16.04 LTS use ami-6f587e1c
         wait: yes
         volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 50
            wait: true
         count: 2
         vpc_subnet_id: subnet-xxxxxxxx
         assign_public_ip: yes
         instance_tags:
            Name: Ansible
      register: ec2

    - name: Add all instance private IPs to host group
      add_host:
          hostname: "{{ item.private_ip }}"
          ansible_ssh_user: ubuntu
          groups: aws
      with_items: "{{ ec2.instances }}"

    - local_action: file path=./hosts state=absent
      ignore_errors: yes

    - local_action: file path=./hosts state=touch

    - local_action: lineinfile line="[all]" insertafter=EOF dest=./hosts

    - local_action: lineinfile line="{{ item.private_ip }}  ansible_python_interpreter=/usr/bin/python3" insertafter=EOF dest=./hosts
      with_items: "{{ ec2.instances }}"

    - name: Wait for SSH to come up
      wait_for:
          host: "{{ item.private_ip }}"
          port: 22
          delay: 60
          timeout: 600
          state: started
      with_items: "{{ ec2.instances }}"

    - name: refreshing inventory cache
      meta: refresh_inventory

- hosts: all
  gather_facts: False
  tasks:
    - command: hostname -i
```

##### EXPECTED RESULTS
Use the custom interpreter that I've stated in my hosts file

##### ACTUAL RESULTS
Ansible use the default interpreter which doesn't exist on Ubuntu 16.04 LTS

```
fatal: [172.31.38.20]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 172.31.38.20 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE"}
```
