### ISSUE TITLE
copy module slower than expected when recursive

### ISSUE THREAD

**Issue by PriceChild** [ansible/ansible#21513]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrid
```

##### OS / ENVIRONMENT
Debian Sid -> Centos 6

##### SUMMARY
The copy module documentation states:
> The “copy” module recursively copy facility does not scale to lots (>hundreds) of files.
and I'm finding incredible slowdowns at barely 50 files.

If I list each file individually using with_items in my task however, ansible completes an order of magnitude faster.

I'm confident that there is a large speed boost to be gained somewhere here.

##### STEPS TO REPRODUCE
```
copy: src=directory dest=somewhere
```
vs
```
file: path=somewhere state=directory

copy: src={{ item }} dest=directory/{{ item }}
with_items:
  - file1
  - file2
  - etc
```

##### EXPECTED RESULTS
Using the copy module recursively _should_ take a similar amount of time to listing the files using with_items?

##### ACTUAL RESULTS
Using the copy module recursively takes at least 10x longer.

**Comment by PriceChild** [comment]
I've tried profiling this but all the time is spent on ansible/plugins/strategy._wait_on_pending_results()

I've tried ANSIBLE_KEEP_REMOTE_FILES=1, hoping I could profile the resultant script. That leaves copy.py but no source directory? Maybe that's a separate bug...

**Comment by PriceChild** [comment]
To put some numbers to it:
synchronize:
real	0m4.311s
user	0m2.408s
sys	0m0.276s

copy recursive:
real	9m36.888s
user	1m25.800s
sys	0m15.456s

copy with_items:
real	0m42.066s
user	0m8.348s
sys	0m1.352s

synchronize hasn't been an option for us historically (bugs around become, ssh keys etc.) but 40 seconds is still definitely acceptable. 10 minutes for the benefit of not having to write files out in the task yaml is... silly.

Now I don't want to do this for obvious reasons, but something like:

```
name: Find files to install.
delegate_to: localhost
connection: local
run_once: true
find:
  paths: "{{ role_path }}/files/webservice"
  file_type: "file"
  recurse: yes
register: webservice
become: false

name: copy
copy: 
  src: "{{ item.path }}"
  dest: "/var/www/python/webservice/{{ item.path[(role_path + '/files/webservice/').__len__():] }}"
with_items: "{{ webservice.files }}"
when: item.path is defined
```
...matches a simple with_items loop:
real	0m43.873s
user	0m9.160s
sys	0m1.348s

and gives us the benefit of both. (Directory creation not shown but taken into account for timings) 

There are separate reasons why we're not using synchronize but I'm not entirely sure if they're merely historical at this point. It's something we probably want to move to, but still I think there's room for improvement here.
