### ISSUE TITLE
azure_rm_deployment - ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded

### ISSUE THREAD

**Issue by msghaleb** [ansible/ansible#21515]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_deployment

##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /var/lib/awx/projects/_6__ansible_cloudfirst_master/ansible.cfg
  configured module search path = ['modules', '/usr/share/ansible']
```

##### CONFIGURATION

installed msrest 0.4.2 and msrestazure 0.4.2
##### OS / ENVIRONMENT

Ubuntu 14.04 LTS
Ansible 2.1.1.0
ansible tower 3.0.1
Azure 2.0.0rc5
##### SUMMARY

It used to work correctly up till few weeks ago, now we are getting the below error, which pointed us to may be an invalid Key - but it seems to be something else.
We are mainly trying to spin up a VM in a RG and install on it some software
##### STEPS TO REPRODUCE

Well to reproduce this, just spin up a CentOS 7 or Ubuntu 14.04 LTS, install ansible and ansible tower and try to get this work using the default configuration.

p.s. install msrest 0.4.2 and msrestazure 0.4.2 otherwise you will get InvalidHeader.

```yaml
- name: Deploying your Azure Jumphox - this may take time - time for a coffee
        azure_rm_deployment:
          state: present
          secret: "{{ secret }}"
          subscription_id: "{{ subscription_id }}"
          client_id: "{{ client_id }}"
          tenant: "{{ tenant }}"
          resource_group_name: "{{ resource_group_name }}"
          location: "{{ location }}"
          template:
              "$schema": https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#
              contentVersion: 1.0.0.0
              parameters:
                adminUsername:
                  type: string
                  metadata:
                    description: Username for the Virtual Machine.
                adminPassword:
                  type: securestring
                  metadata:
                    description: Password for the Virtual Machine.
                dnsLabelPrefix:
                  type: string
                  metadata:
                    description: Unique DNS Name for the Public IP used to access the Virtual Machine.
                windowsOSVersion:
                  type: string
                  defaultValue: 2012-R2-Datacenter
                  allowedValues:
                  - 2008-R2-SP1
                  - 2012-Datacenter
                  - 2012-R2-Datacenter
                  metadata:
                    description: 'The Windows version for the VM. This will pick a fully patched
                      image of this given Windows version. Allowed values: 2008-R2-SP1, 2012-Datacenter,
                      2012-R2-Datacenter.'
              variables:
                imagePublisher: MicrosoftWindowsServer
                imageOffer: WindowsServer
                OSDiskName: osdiskforwindowssimple
                nicName: myVMNic
                addressPrefix: 10.0.0.0/16
                subnetName: Subnet
                subnetPrefix: 10.0.0.0/24
                storageAccountType: Standard_LRS
                publicIPAddressName: myPublicIP
                publicIPAddressType: Dynamic
                vmStorageAccountContainerName: vhds
                vmName: "{{ vmName }}"
                vmSize: "{{ vmSize }}"
                virtualNetworkName: MyVNET
                vnetID: "[resourceId('Microsoft.Network/virtualNetworks',variables('virtualNetworkName'))]"
                subnetRef: "[concat(variables('vnetID'),'/subnets/',variables('subnetName'))]"
                newStorageAccountName: "[concat(uniqueString(resourceGroup().id),'winrmsa')]"
                apiVersion: '2015-06-15'
                hostDNSNameScriptArgument: "[concat('*.',resourceGroup().location,'.cloudapp.azure.com')]"
              resources:
              - type: Microsoft.Storage/storageAccounts
                name: "[variables('newStorageAccountName')]"
                apiVersion: "[variables('apiVersion')]"
                location: "[resourceGroup().location]"
                properties:
                  accountType: "[variables('storageAccountType')]"
              - apiVersion: "[variables('apiVersion')]"
                type: Microsoft.Network/publicIPAddresses
                name: "[variables('publicIPAddressName')]"
                location: "[resourceGroup().location]"
                properties:
                  publicIPAllocationMethod: "[variables('publicIPAddressType')]"
                  dnsSettings:
                    domainNameLabel: "[parameters('dnsLabelPrefix')]"
              - apiVersion: "[variables('apiVersion')]"
                type: Microsoft.Network/virtualNetworks
                name: "[variables('virtualNetworkName')]"
                location: "[resourceGroup().location]"
                properties:
                  addressSpace:
                    addressPrefixes:
                    - "[variables('addressPrefix')]"
                  subnets:
                  - name: "[variables('subnetName')]"
                    properties:
                      addressPrefix: "[variables('subnetPrefix')]"
              - apiVersion: "[variables('apiVersion')]"
                type: Microsoft.Network/networkInterfaces
                name: "[variables('nicName')]"
                location: "[resourceGroup().location]"
                dependsOn:
                - "[concat('Microsoft.Network/publicIPAddresses/', variables('publicIPAddressName'))]"
                - "[concat('Microsoft.Network/virtualNetworks/', variables('virtualNetworkName'))]"
                properties:
                  ipConfigurations:
                  - name: ipconfig1
                    properties:
                      privateIPAllocationMethod: Dynamic
                      publicIPAddress:
                        id: "[resourceId('Microsoft.Network/publicIPAddresses',variables('publicIPAddressName'))]"
                      subnet:
                        id: "[variables('subnetRef')]"
              - apiVersion: "[variables('apiVersion')]"
                type: Microsoft.Compute/virtualMachines
                name: "[variables('vmName')]"
                location: "[resourceGroup().location]"
                dependsOn:
                - "[concat('Microsoft.Storage/storageAccounts/', variables('newStorageAccountName'))]"
                - "[concat('Microsoft.Network/networkInterfaces/', variables('nicName'))]"
                properties:
                  hardwareProfile:
                    vmSize: "[variables('vmSize')]"
                  osProfile:
                    computername: "[variables('vmName')]"
                    adminUsername: "[parameters('adminUsername')]"
                    adminPassword: "[parameters('adminPassword')]"
                  storageProfile:
                    imageReference:
                      publisher: "[variables('imagePublisher')]"
                      offer: "[variables('imageOffer')]"
                      sku: "[parameters('windowsOSVersion')]"
                      version: latest
                    osDisk:
                      name: osdisk
                      vhd:
                        uri: "[concat('http://',variables('newStorageAccountName'),'.blob.core.windows.net/',variables('vmStorageAccountContainerName'),'/',variables('OSDiskName'),'.vhd')]"
                      caching: ReadWrite
                      createOption: FromImage
                  networkProfile:
                    networkInterfaces:
                    - id: "[resourceId('Microsoft.Network/networkInterfaces',variables('nicName'))]"
                resources:
                - type: Microsoft.Compute/virtualMachines/extensions
                  name: "[concat(variables('vmName'),'/WinRMCustomScriptExtension')]"
                  apiVersion: "[variables('apiVersion')]"
                  location: "[resourceGroup().location]"
                  dependsOn:
                  - "[concat('Microsoft.Compute/virtualMachines/', variables('vmName'))]"
                  properties:
                    publisher: Microsoft.Compute
                    type: CustomScriptExtension
                    typeHandlerVersion: '1.4'
                    settings:
                      fileUris:
                      - https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/ConfigureWinRM.ps1
                      - https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/makecert.exe
                      - https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/201-vm-winrm-windows/winrmconf.cmd
                      commandToExecute: "[concat('powershell -ExecutionPolicy Unrestricted -file
                        ConfigureWinRM.ps1 ',variables('hostDNSNameScriptArgument'))]"

          parameters:
            adminUsername:
              value: "{{ adminUsername }}"
            adminPassword:
              value: "{{ adminPassword }}"
            dnsLabelPrefix:
              value: "{{ dnsLabelPrefix }}"
        register: azure

      - name: provision | Waiting for winrm port to open
        wait_for:
          port="{{ ansible_ssh_port | default('5986') }}"
          host="{{ item['ips'][0].public_ip }}"
          delay=1
          timeout=1200
        with_items: "{{ azure.deployment.instances }}"

      - name: provision | set facts for ansible_ssh_host
        set_fact:
              ansible_ssh_host: "{{ item['ips'][0].public_ip }}"
        with_items: "{{ azure.deployment.instances }}"
```

##### EXPECTED RESULTS

It should spin up the template in azure as expected

##### ACTUAL RESULTS

We get the below error

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_4RZ_sG/ansible_module_azure_rm_deployment.py", line 660, in <module>
    main()
  File "/tmp/ansible_4RZ_sG/ansible_module_azure_rm_deployment.py", line 656, in main
    AzureRMDeploymentManager()
  File "/tmp/ansible_4RZ_sG/ansible_module_azure_rm_deployment.py", line 438, in __init__
    supports_check_mode=False)
  File "/tmp/ansible_4RZ_sG/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py", line 181, in __init__
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 403, in __init__
    self.set_token()
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrestazure/azure_active_directory.py", line 434, in set_token
    raise_with_traceback(AuthenticationError, "", err)
  File "/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrest/exceptions.py", line 50, in raise_with_traceback
    raise error
msrest.exceptions.AuthenticationError: , ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /612b45cc-4beb-4ddc-ae8e-4882a369d6a8/oauth2/token (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f44b0a93450>: Failed to establish a new connection: [Errno 110] Connection timed out',))

fatal: [azure-jumphost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "azure_rm_deployment"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_4RZ_sG/ansible_module_azure_rm_deployment.py\", line 660, in <module>\n    main()\n  File \"/tmp/ansible_4RZ_sG/ansible_module_azure_rm_deployment.py\", line 656, in main\n    AzureRMDeploymentManager()\n  File \"/tmp/ansible_4RZ_sG/ansible_module_azure_rm_deployment.py\", line 438, in __init__\n    supports_check_mode=False)\n  File \"/tmp/ansible_4RZ_sG/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 181, in __init__\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrestazure/azure_active_directory.py\", line 403, in __init__\n    self.set_token()\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrestazure/azure_active_directory.py\", line 434, in set_token\n    raise_with_traceback(AuthenticationError, \"\", err)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrest/exceptions.py\", line 50, in raise_with_traceback\n    raise error\nmsrest.exceptions.AuthenticationError: , ConnectionError: HTTPSConnectionPool(host='login.microsoftonline.com', port=443): Max retries exceeded with url: /612b45cc-4beb-4ddc-ae8e-4882a369d6a8/oauth2/token (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f44b0a93450>: Failed to establish a new connection: [Errno 110] Connection timed out',))\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```
