### ISSUE TITLE
allow subnet names to be used in os_port instead of subnet ids only

### ISSUE THREAD

**Issue by dev00** [ansible/ansible#21522]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

os_port

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Right now we can only create instances which will be attached to a specific network. Openstack will then place the instance in the first subnet.
However, when having multiple subnets, you may want to choose in which subnet the instance should be placed.
This can at the moment only be done by creating an openstack port with os_port. os_port will accept only subnet-ids at the moment, which are a little bit messy (because you need to get the id first from the name etc.).
However, the openstack-client already supports creating a port in a subnet and allows the subnet to be chosen by name.

It would be great to take out some restrictions from the os_port module and allow a subnet name or subnet id (this is btw. the default behavior for the network-parameter already) to be supplied instead of allowing an id only.

##### STEPS TO REPRODUCE

```
- name: create the port in the needed subnet                                                                                                                                    
  os_port:                                                                                                                                                                      
    state: present                                                                                                                                                              
    fixed_ips:                                                                                                                                                                  
      - subnet: foo                                                                                                                                                          
    network: "first-nw" 
    security_groups: "some_security_group" 
    name: a_port 
```

##### EXPECTED RESULTS

That the port would be created.
##### ACTUAL RESULTS

The step fails and asks for an ID.

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating port for network $network_id: Invalid input for fixed_ips. Reason: 'foo' is not a valid UUID.\nNeutron server returns request_ids: ['$neutron_id']"}
```
