### ISSUE TITLE
synchronize modules does not respect become_user

### ISSUE THREAD

**Issue by cadavre** [ansible/ansible#21530]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

`synchronize`

##### ANSIBLE VERSION

ansible 2.2.1.0

##### SUMMARY

`synchronize` module is not respecting `become_user`.

##### STEPS TO REPRODUCE

```yaml
# playbook.yml
- hosts: remote
  tasks:
    - synchronize:
        src: "/src/dir"
        dest: "/dest/dir"
        archive: no
        recursive: yes
```

```ini
# inventory
remote ansible_host=somehost.com ansible_user=ubuntu ansible_become=true ansible_become_user=ci
```

##### EXPECTED RESULT

Files created by `rsync` in `/dest/dir` should have ownership of `ci` user.

##### CURRENT RESULT

Files created by `rsync` in `/dest/dir` have ownership of `root` user.

##### SOLUTION PROPOSAL

Set default `"rsync-path: sudo -u {{ become_user | default(ansible_user) | default('root') }} rsync "` _(pseudo-code!)_.

##### WHY?

Right now, `synchronize` is the only module that doesn't respect `become_user` and as a result doesn't allow you to set preferred `user:group` ownership.

While having `become` set in inventory, there's also no way to `become: no` on task level (due to http://docs.ansible.com/ansible/become.html#directives – _(...)can be set from play to task level, but are overridden by connection variables_) to overwrite this manually. The only solution is to overwrite `rsync_path` which is a dirty hack.

This means lack of unification.
