### ISSUE TITLE
file module should allow setting symlink ownership without src

### ISSUE THREAD

**Issue by orev** [ansible/ansible#21537]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
file module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /home/user/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
CentOS 7 x86_64

##### SUMMARY
The file module should allow setting the owner and group of a symlink without having to specify the link src.  This is useful when the link may point to different locations (possibly unknown to ansible), but the link itself should be owned by a specific user/group.

Equivalent to:
    chown -h myuser:mygroup /path/to/link

##### STEPS TO REPRODUCE
```yaml
- name: Set ownership on link
  file:
    path:  /path/to/link
    state:  link
    owner:  myuser
    group:  mygroup
    follow: no
```

##### EXPECTED RESULTS
/path/to/link has owner/group: myowner/mygroup

##### ACTUAL RESULTS
```
FAILED! => {"changed": false, "failed": true, "msg": "src and dest are required for creating links"}
```
