### ISSUE TITLE
module apt: fails to set changed to true when run for the first time (when installing dependencies)

### ISSUE THREAD

**Issue by nusenu** [ansible/ansible#21547]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module: apt

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```
(also tested on master)

##### OS / ENVIRONMENT
target: debian 8 minimal netinstall 
important: ansible apt module has never been run on that target before

##### SUMMARY
apt module fails to set changed to 'True' when run for the first time (and installing its dependencies)

##### STEPS TO REPRODUCE
on a fresh minimal installation apt module will install 'lsb-release' but will never trigger the handler since 'changed' is 'false':

```yaml
- name: Ensure lsb-release is installed
  become: yes
  apt:
    name: lsb-release
  notify:
     - myhandler
```

##### EXPECTED RESULTS
`changed` should be `true`
myhandler should be run

##### ACTUAL RESULTS
the handler will not run if the apt module is used for the first time, even though apt installed lsb-release
