### ISSUE TITLE
ec2_ami_find does not return correct result.

### ISSUE THREAD

**Issue by xuchen81** [ansible/ansible#21551]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_ami_find

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### OS / ENVIRONMENT

Linux Ubuntu

##### SUMMARY

I try to create a ami using ec2_ami, it succeed,  and I want to find it right after it is created using ec2_ami_find, it cannot find it.

However, if I run it a few minutes later, I will get the result from ec2_ami_find.

##### STEPS TO REPRODUCE

```yaml
- name: Create today's  AMI.
  ec2_ami:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ region }}"
    instance_id: "{{ ansible_ec2_instance_id }}"
    wait: yes
    no_reboot: yes
    name: aperture_image
    description: aperture image from today
  register: created

- debug:
    msg: "{{ created }}"

- name: Find today's AMI.
  ec2_ami_find:
    name: aperture_image
    region: "{{ region }}"
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
  register: new_created_instance

- debug:
    msg: "{{ new_created_instance }}"

```

##### EXPECTED RESULTS

I expect to get the result from  variable new_created_instance

##### ACTUAL RESULTS

```
Results from ec2_ami omitted. (the following debug shows it.)

TASK [create_snapshot : debug] *************************************************
ok: [xx.xxx.xxx.xxx] => {
    "changed": false, 
    "msg": {
        "architecture": "x86_64", 
        "block_device_mapping": {
            "/dev/sda1": {
                "delete_on_termination": false, 
                "encrypted": false, 
                "size": 200, 
                "snapshot_id": "snap-xxxxxxxxxxxxxxxx", 
                "volume_type": "gp2"
            }, 
            "/dev/sdb": {
                "delete_on_termination": false, 
                "encrypted": null, 
                "size": null, 
                "snapshot_id": null, 
                "volume_type": null
            }, 
            "/dev/sdc": {
                "delete_on_termination": false, 
                "encrypted": null, 
                "size": null, 
                "snapshot_id": null, 
                "volume_type": null
            }
        }, 
        "changed": true, 
        "creationDate": "2017-02-17T02:05:24.000Z", 
        "description": "aperture image from 20170217", 
        "hypervisor": "xen", 
        "image_id": "ami-f44ec894", 
        "is_public": false, 
        "location": "8xxxxxxxxxxx6/aperture_image", 
        "msg": "AMI creation operation complete", 
        "ownerId": "8xxxxxxxxxxx6", 
        "root_device_name": "/dev/sda1", 
        "root_device_type": "ebs", 
        "state": "available", 
        "tags": {}, 
        "virtualization_type": "hvm"
    }
}

msg: {
  "root_device_name": "/dev/sda1", 
  "root_device_type": "ebs", 
  "description": "aperture image from today", 
  "block_device_mapping": {
    "/dev/sdb": {
      "encrypted": null, 
      "size": null, 
      "delete_on_termination": false, 
      "volume_type": null, 
      "snapshot_id": null
    }, 
    "/dev/sda1": {
      "encrypted": false, 
      "size": 200, 
      "delete_on_termination": false, 
      "volume_type": "gp2", 
      "snapshot_id": "snap-xxxxxxxxxxxxx"
    }, 
    "/dev/sdc": {
      "encrypted": null, 
      "size": null, 
      "delete_on_termination": false, 
      "volume_type": null, 
      "snapshot_id": null
    }
  }, 
  "hypervisor": "xen", 
  "changed": true, 
  "image_id": "ami-xxxxxxxx", 
  "state": "available", 
  "location": "8xxxxxxxxxxx6/aperture_image", 
  "ownerId": "8xxxxxxxxxxx6", 
  "msg": "AMI creation operation complete", 
  "is_public": false, 
  "creationDate": "2017-02-17T02:05:24.000Z", 
  "virtualization_type": "hvm", 
  "tags": {}, 
  "architecture": "x86_64"
}

TASK [create_snapshot : Find today's AMI.] ********************
ok: [xx.xxx.xxx.xxx]

TASK [create_snapshot : debug] *************************************************
ok: [xx.xxx.xxx.xxx] => {
    "changed": false, 
    "msg": {
        "changed": false, 
        "results": []
    }
}

msg: {
  "changed": false, 
  "results": []
}


```
