### ISSUE TITLE
win_chocolatey: No means of upgrading all existing packages

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#21559]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_chocolatey

##### ANSIBLE VERSION

v2.3

##### STEPS TO REPRODUCE

There is a shortcoming in the current win_chocolatey module. There is no means of updating all existing chocolatey packages, like the yum-equivalent:
```yaml
- win_chocolatey:
    name: *
    state: latest
```
I think this is essential to have (and a lot more efficient than looping over a predefined list).

**Comment by ansibot** [comment]
cc @smadam813
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Woutrrr** [comment]
On the command line can use `choco upgrade all` to upgrade all packages. Using "all" as package name also works for the win_chocolatey module:

~~Example:~~  (this example will not work in 2.3, see @dagwieers comment below)
```yaml
- win_chocolatey:                                                          
    upgrade: True                                                          
    name: "all"
```

**Comment by ansibot** [comment]
cc @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
This appears to work.

BTW The new way of specifying 'upgrade: True' is:
```yaml
- win_chocolatey:
    name: all
    state: latest
```
