### ISSUE TITLE
Docs for complex return types are not generated

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#21556]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
Module HTML documentation

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

If a module documentation specifies a complex return type, the fields of the complex type are not rendered into the document.

##### STEPS TO REPRODUCE

Example, browse to the [os_image_facts module's Return Values section](https://docs.ansible.com/ansible/os_image_facts_module.html#return-values)

##### EXPECTED RESULTS

Documentation about the subkeys of openstack_image key (id, name, status, created_at, deleted, ...)

The RETURN field for that module looks like this:

```
RETURN = '''
openstack_image:
    description: has all the openstack facts about the image
    returned: always, but can be null
    type: complex
    contains:
        id:
            description: Unique UUID.
            returned: success
            type: string
        name:
            description: Name given to the image.
            returned: success
            type: string
        status:
            description: Image status.
            returned: success
            type: string
...
```

##### ACTUAL RESULTS

Docs do not render the documentation for the subkeys.

And, indeed, the [hacking/templates/rst.j2](https://github.com/ansible/ansible/blob/devel/hacking/templates/rst.j2) file does not appear to contain any logic for handling complex types.
