### ISSUE TITLE
unarchive_module: ERROR! 'src' is not a valid attribute for a Task

### ISSUE THREAD

**Issue by magick93** [ansible/ansible#21561]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
http://docs.ansible.com/ansible/unarchive_module.html

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT
Ansible host: Ubuntu 16.04

##### SUMMARY
Error when using unarchive module in playbook.

`ERROR! 'src' is not a valid attribute for a Task`

But documentation clearly shows `src` is valid.

##### STEPS TO REPRODUCE

```yaml

    - unarchive:
      src: https://github.com/openshift/origin/releases/download/v1.5.0-alpha.2/openshift-origin-client-tools-v1.5.0-alpha.2-e4b43ee-linux-64bit.tar.gz
      dest: /usr/local/bin
      remote_src: True

```

##### EXPECTED RESULTS
Expect it to work, as described by documentation.

##### ACTUAL RESULTS

`ERROR! 'src' is not a valid attribute for a Task`
