### ISSUE TITLE
Handle file common args in maven_artifact module

### ISSUE THREAD

**Issue by zigarn** [ansible/ansible#21577]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module `maven_artifact`

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The module should handle default file arguments to set dest file owner, group, mode and others.

##### STEPS TO REPRODUCE

```yaml
- maven_artifact:
  group_id: ...
  artifact_id: ...
  dest: /tmp/artifact.jar
  mode: '0755'
  owner: user
```

##### EXPECTED RESULTS

`/tmp/artifact.jar` is created with filemode '0755' and owned by 'user'.

##### ACTUAL RESULTS

`/tmp/artifact.jar` use default mode and is owned by `remote_user`
