### ISSUE TITLE
ini_file custom character for comment (# or ;)

### ISSUE THREAD

**Issue by cristiroma** [ansible/ansible#21578]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ini_file

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Customize ini_file comment character to choose between # and ;
##### STEPS TO REPRODUCE

```
ini_file: dest="/etc/php.ini" option="mail.add_x_header" value="" section="mail function" state="absent"
```

```yaml

- name: install webtatic repos
  yum: name="https://mirror.webtatic.com/yum/el7/webtatic-release.rpm" state="installed" validate_certs="false"

- name: install PHP and libs from webtatic
  yum: name="{{ item }}" state="installed"
  with_items: [ php56w, php56w-cli, php56w-devel, php56w-pear,
  php56w-process, php56w-common, php56w-intl, php56w-xml,
  php56w-pecl-memcached, php56w-pdo, php56w-gd, php56w-mbstring,
  php56w-opcache, php56w-mcrypt, php56w-mysql, php56w-ldap ]

- name: configure php
  ini_file: dest="/etc/php.ini" option="{{ item.option }}" value="{{ item.value }}" section="{{ item.section }}" state="{{ item.state }}"
  with_items:
    - { option: "mail.add_x_header", section: "mail function", state: "absent",  value: "" }
```

##### EXPECTED RESULTS

Commenting a line in /etc/php.ini using ini_file to work with PHP correcty (using ";" character)
##### ACTUAL RESULTS

When using ini_file to comment lines in /etc/php.ini file is adding "#" which yields a PHP warning PHP ``Deprecated:  Comments starting with '#' are deprecated in /etc/php.ini on line ...``

```
```
