### ISSUE TITLE
firewalld - set masquerade

### ISSUE THREAD

**Issue by tdobrovolny** [ansible/ansible#21632]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
firewalld module

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 76c9ad9dfc) last updated 2017/02/19 14:00:22 (GMT +200)
  config file = /home/tomas/ansible/net/ansible.cfg
  configured module search path = Default w/o overrides
```
##### FIREWALLD VERSION
```
firewalld.noarch          0.4.4.2-2.fc24
python-firewall.noarch    0.4.4.2-2.fc24
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Fedora 24

##### SUMMARY
Setting masquerade option for zone with firewalld module failed with error:
`ERROR: Exception caught: get_masquerade_enabled_permanent() takes exactly 1 argument (6 given)`

##### STEPS TO REPRODUCE
Run `ansible-playbook firewall.yml`

firewall.yml is here:
```yaml
- hosts: all
  become: yes
  tasks:
  - name: Set masquarade for zones
    tags:
      - firewalld
    firewalld:
      zone: SmazMe
      masquerade: yes
      permanent: true
      state: enabled
```

##### EXPECTED RESULTS
Set firewalld masquerade option for zone SmazMe

##### ACTUAL RESULTS
Action failed with error.

```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "immediate": false, 
            "interface": null, 
            "masquerade": "True", 
            "offline": null, 
            "permanent": true, 
            "port": null, 
            "rich_rule": null, 
            "service": null, 
            "source": null, 
            "state": "enabled", 
            "timeout": 0, 
            "zone": "SmazMe"
        }
    }, 
    "msg": "ERROR: Exception caught: get_masquerade_enabled_permanent() takes exactly 1 argument (6 given)"
}
```

**Comment by ansibot** [comment]
cc @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
Proposed fix for this at https://github.com/ansible/ansible/pull/21693

**Comment by aioue** [comment]
@alikins @tdobrovolny I have the exact same issue when using `immediate: true`, even after the fix. Without `immediate: true`, there is no problem.

**Comment by tdobrovolny** [comment]
@aioue Confirm. Adding `immediate: true` make the nearly same error. But on set function.

`FAILED! => {"changed": false, "failed": true, "msg": "ERROR: Exception caught: set_masquerade_enabled() takes exactly 1 argument (6 given)"}`

`ansible 2.4.0 (devel 6ce7448ca4) last updated 2017/06/08 18:13:48 (GMT +200)`

```yaml
---
- hosts: localhost
  become: yes
  tasks:
  - name: Set masquarade for zones
    tags:
      - firewalld
    firewalld:
      zone: SmazMe
      masquerade: yes
      immediate: true
      permanent: true
      state: enabled
...
```
