### ISSUE TITLE
lineinfile with serial is overwriting the data

### ISSUE THREAD

**Issue by njchandu** [ansible/ansible#21671]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
ansible 2.1.1.0 (dx-stable-2.1 553aca5dc7) last updated 2017/02/08 15:43:47 (GMT +550)

##### SUMMARY
lineinfile when used with serial is overwriting the data. 

**Here's what I'm trying to do in a broader picture:**
There are n hosts and I do not want to stop the execution when a task fails for one host. I'm using ignore_failure to ignore the failure and continue exec on other hosts. At the end of the exec I want to list all the hosts which failed to execute the task. I tried using a local var, I wasn't successful. I tried writing the hostname to a file and at the end of playbook exec I want to print the file.

I'm able to do it with shell module >>. But I am unable to do it with lineinfile.

##### STEPS TO REPRODUCE
```
- hosts: webservers
  remote_user: sudo
  serial: "{{ serial_count | default('100%') }}"
  tasks:
    - name: update file
      lineinfile: hosts.txt line="{{ inventory_hostname }}"
      delegate_to: localhost
```
##### EXPECTED RESULTS
All the hostnames in the file

##### ACTUAL RESULTS
Only few hostnames, random every time.

Thanks.
