### ISSUE TITLE
asa_acl does not perform before or after commands

### ISSUE THREAD

**Issue by kylebevans** [ansible/ansible#21683]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
asa_acl

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY
asa_acl does not perform before or after commands

##### STEPS TO REPRODUCE

```yaml
- name: Cisco ASA access-list config
  connection: local
  hosts: 192.168.10.10
  gather_facts: false
  vars:
    cli:
      username: someuser
      password: XXXXXX
      host: 192.168.10.10
      authorize: yes
      auth_pass: XXXXXX
  tasks:
    - name: configure access-list
      asa_acl:
        lines:
          - access-list TEMPACL extended permit tcp any any eq 443
          - access-list TEMPACL extended permit udp any any eq domain
          - access-list TEMPACL extended deny ip any any
        before: clear configure access-list TEMPACL
        after: write mem
        match: strict
        replace: block
        provider: "{{ cli }}" 
      register: result

    - asa_command:
        commands:
          - wr mem
        provider: "{{ cli }}"

    - debug: var=result

```

##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: testacl.yml **********************************************************
1 plays in testacl.yml

PLAY [Cisco ASA access-list config] ********************************************

TASK [configure access-list] ***************************************************
task path: /home/someuser/testacl.yml:13
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/network/asa/asa_acl.py
<192.168.10.10> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.10.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487629270.81-201418757310507 `" && echo ansible-tmp-1487629270.81-201418757310507="` echo ~/.ansible/tmp/ansible-tmp-1487629270.81-201418757310507 `" ) && sleep 0'
<192.168.10.10> PUT /tmp/tmpxr6ugv TO /root/.ansible/tmp/ansible-tmp-1487629270.81-201418757310507/asa_acl.py
<192.168.10.10> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487629270.81-201418757310507/ /root/.ansible/tmp/ansible-tmp-1487629270.81-201418757310507/asa_acl.py && sleep 0'
<192.168.10.10> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487629270.81-201418757310507/asa_acl.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487629270.81-201418757310507/" > /dev/null 2>&1 && sleep 0'
changed: [192.168.10.10] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "after": [
                "write mem"
            ], 
            "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "authorize": true, 
            "before": [
                "clear configure access-list TEMPACL"
            ], 
            "config": null, 
            "context": null, 
            "force": false, 
            "host": "192.168.10.10", 
            "lines": [
                "access-list TEMPACL extended permit tcp any any eq 443", 
                "access-list TEMPACL extended permit udp any any eq domain", 
                "access-list TEMPACL extended deny ip any any"
            ], 
            "match": "strict", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "authorize": true, 
                "host": "192.168.10.10", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "username": "someuser"
            }, 
            "replace": "block", 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": null, 
            "username": "someuser"
        }, 
        "module_name": "asa_acl"
    }, 
    "responses": [
        "access-list TEMPACL extended permit tcp any ad permit tcp any an                          eq 443access-list TEMPACL extended permit tcp any $\n", 
        ""
    ], 
    "updates": [
        "access-list TEMPACL extended permit tcp any any eq 443"
    ]
}

TASK [asa_command] *************************************************************
task path: /home/someuser/testacl.yml:26
Using module file /usr/lib/python2.7/site-packages/ansible/modules/extras/network/asa/asa_command.py
<192.168.10.10> ESTABLISH LOCAL CONNECTION FOR USER: root
<192.168.10.10> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1487629271.7-10904289136330 `" && echo ansible-tmp-1487629271.7-10904289136330="` echo ~/.ansible/tmp/ansible-tmp-1487629271.7-10904289136330 `" ) && sleep 0'
<192.168.10.10> PUT /tmp/tmplMVoyP TO /root/.ansible/tmp/ansible-tmp-1487629271.7-10904289136330/asa_command.py
<192.168.10.10> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1487629271.7-10904289136330/ /root/.ansible/tmp/ansible-tmp-1487629271.7-10904289136330/asa_command.py && sleep 0'
<192.168.10.10> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1487629271.7-10904289136330/asa_command.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1487629271.7-10904289136330/" > /dev/null 2>&1 && sleep 0'
ok: [192.168.10.10] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "authorize": true, 
            "commands": [
                "wr mem"
            ], 
            "context": null, 
            "host": "192.168.10.10", 
            "interval": 1, 
            "match": "all", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "authorize": true, 
                "host": "192.168.10.10", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "username": "someuser"
            }, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": null, 
            "username": "someuser", 
            "wait_for": null
        }, 
        "module_name": "asa_command"
    }, 
    "stdout": [
        "Building configuration...\nCryptochecksum: 299d190b 5e065890 14662168 a1b7fa8b \n\n106619 bytes copied in 0.170 secs\n[OK]\n"
    ], 
    "stdout_lines": [
        [
            "Building configuration...", 
            "Cryptochecksum: 299d190b 5e065890 14662168 a1b7fa8b ", 
            "", 
            "106619 bytes copied in 0.170 secs", 
            "[OK]", 
            ""
        ]
    ], 
    "warnings": []
}

TASK [debug] *******************************************************************
task path: /home/someuser/testacl.yml:31
ok: [192.168.10.10] => {
    "result": {
        "changed": true, 
        "responses": [
            "access-list TEMPACL extended permit tcp any ad permit tcp any an                          eq 443access-list TEMPACL extended permit tcp any $\n", 
            ""
        ], 
        "updates": [
            "access-list TEMPACL extended permit tcp any any eq 443"
        ]
    }
}

PLAY RECAP *********************************************************************
192.168.10.10                : ok=3    changed=1    unreachable=0    failed=0   

```
