### ISSUE TITLE
Register result with templated name not working

### ISSUE THREAD

**Issue by antigremlin** [ansible/ansible#21682]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
remote_tmp     = /tmp/$USER/.ansible
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible/facts
fact_caching_timeout = 7200
```

##### OS / ENVIRONMENT

Case 1:

```
"ansible_distribution": "CentOS"
"ansible_distribution_release": "Core"
"ansible_distribution_version": "7.2.1511"
```

Case 2:

```
"ansible_distribution": "RedHat"
"ansible_distribution_release": "Maipo"
"ansible_distribution_version": "7.2"
```

##### SUMMARY

Registering a variable with a templated name doesn't work:

```
- module: args
  register: "{{subst}}_var"
```

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  vars:
    subst: test
  tasks:
    - action: ping
      register: "{{subst}}_var"
    - debug: var=vars
```

##### EXPECTED RESULTS

Works under Ansible 2.1.2.0:

```
"test_var": {
  "changed": false,
  "ping": "pong"
}
```

##### ACTUAL RESULTS

```
"{{subst}}_var": {
  "changed": false,
  "ping": "pong"
}
```
