### ISSUE TITLE
Feature Idea: map vars from private=yes include_role module

### ISSUE THREAD

**Issue by cognifloyd** [ansible/ansible#21690]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
include_role module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/cognifloyd/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Nothing relevant:
```
[defaults]
cow_selection = small
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I have a role_include task with private=yes, so that it can allow_duplicates without conflicting vars.

However, it would be nice to selectively retrieve vars, especially register vars, created by the role.
To make that possible, I think I would have to map the name of a var used in the include_role to a var that is safe to outside the role.

Would there be some way to map include_role vars (when the role is Private), to external var names? Perhaps this could be something like register, but as a paramater to include_role.

##### STEPS TO REPRODUCE
something like this (maybe):
```yaml
- name: example role
  include_role:
    name: acme.example_role
    allow_duplicates: yes
    private: yes
    register_map:
      safe_external_var: acme_internal_registered_var
```

##### EXPECTED RESULTS

safe_external_var should be set to the contents of acme_internal_registered_var which in essence is a way to selectively make certain vars not private.

##### ACTUAL RESULTS
There's no way to selectively access specific vars in an include_role that is Private.
