### ISSUE TITLE
When conditional fatal error if group is empty rather then skipping due to failed conditional check 

### ISSUE THREAD

**Issue by Guitaraholic** [ansible/ansible#21698]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

When Conditions
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

retry_files_enabled = False
##### OS / ENVIRONMENT

OSX Sierra Host to Ubuntu VM's
##### SUMMARY

If you a playbook with when statement declared with a when inventory_hostname in groups['foo'] it will cause a fatal error if the inventory group is empty rather then just skip the task
##### STEPS TO REPRODUCE

Create a simple task to execute against hosts in two groups
leave one group empty 
define that it only runs when in the empty group

```yaml

ran against all hosts 

- name: Create default dir
  file:
    path: "{{ app_path }}/etc/local"
    state: directory
    owner: "{{ username }}"
    group: "{{ group }}"
    mode: u=rwX,g=rX,o=rX
  become: yes
  become_user: "{{ username }}"
  when:
    - inventory_hostname in groups['deployer']


inventory

[core]
app-server ansible_ssh=192.168.111.1
app-server ansible_ssh=192.168.111.2

[deployer]


-
```

##### EXPECTED RESULTS

expected group to return 0 results so conditional fails and task is skipped 

    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true

##### ACTUAL RESULTS

fatal error that causes the run to end unless ignore errors is set ( which is not ideal ) 

```
fatal: [app-server]: FAILED! => {"failed": true, "msg": "The conditional check 'inventory_hostname in groups['deployer']' failed. The error was: error while evaluating conditional (inventory_hostname in groups['deployer']): Unable to look up a name or access an attribute in template string ({% if inventory_hostname in groups['deployer'] %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable\n\nThe error appears to have been in '/<snip>/tasks/main.yml': line 62, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n# final step to connect apps to deployer server\n- name: Link all clients to deployment server\n  ^ here\n"}
```
