### ISSUE TITLE
add variable or lookup plugin for ansible current user

### ISSUE THREAD

**Issue by gzm55** [ansible/ansible#21702]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Core

##### ANSIBLE VERSION
```
2.2.1
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Need a variable, e.g. ansible_playbook_user, or a lookup plugin, e.g. lookup('id', 'name') as the current local username who running the playbook.

##### STEPS TO REPRODUCE
ansible localhost -m debug -a msg="{{ansible_playbook_user}}"

##### EXPECTED RESULTS
output contains `id -un`

##### ACTUAL RESULTS
N/A

**Comment by bcoca** [comment]
this is what i use `lookup('env', 'USER')`, worst case you can `lookup('pipe', 'id -un')`

**Comment by gzm55** [comment]
USER env is not reliable. when ansible is called from 'env -i sh', USER is not set. So now, I use 

```
- name: current local user
  run_once: True
  set_fact:
    ansible_local_user: "{{ lookup('pipe', 'id -un') | d(lookup('pipe', 'whoami'), True) | d(lookup('env', 'USER'), True) |  d(lookup('env', 'user'), True) |  d(lookup('env', 'LOGNAME'), True) }}"
  failed_when: ansible_local_user == ''
```

This is complicated and also not always get the the real name.
