### ISSUE TITLE
wrong ansible_distribution fact on Linux Mint 13

### ISSUE THREAD

**Issue by netsandbox** [ansible/ansible#21706]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module setup

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
The ansible_distribution fact is set to "Ubuntu" for Linux Mint (13) hosts.

```yaml
"ansible_distribution": "Ubuntu",
"ansible_distribution_major_version": "13",
"ansible_distribution_release": "maya",
"ansible_distribution_version": "13",

"ansible_lsb": {
  "codename": "maya",
  "description": "Linux Mint 13 Maya",
  "id": "LinuxMint",
  "major_release": "13",
  "release": "13"
},
```
