### ISSUE TITLE
Roles cannot find resources within their own role if not using main.yml as task list

### ISSUE THREAD

**Issue by wltjr** [ansible/ansible#21735]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Template module, but I think this is a core issue effecting all

##### ANSIBLE VERSION
Does not work
ansible 2.2.1.0
  config file = /sites/site1/ansible/ansible.cfg
  configured module search path = Default w/o overrides

ansible 2.3.0
  config file = /sites/site1/ansible/ansible.cfg
  configured module search path = Default w/o overrides

Works in 
ansible 2.1.4.0
  config file = /sites/site1/ansible/ansible.cfg
  configured module search path = Default w/o override

##### CONFIGURATION
```
$ cat ansible.cfg 
[defaults]
inventory=hosts
pipelining=True
remote_user=ro
```
##### OS / ENVIRONMENT
Gentoo

##### SUMMARY
Roles cannot find files/templates in the roles own directories

##### STEPS TO REPRODUCE

Same with ansible 2.2.1.0 and 2.3.0, works with 2.1.4.0

mkdir -p roles/test/tasks roles/test/templates

$ cat test.yaml 
```yaml
---
- name: Test the test role
  hosts: ws
  roles:
   - test
```

$ cat roles/test/tasks/main.yaml 
```yaml
- name: Install test template from role
  template:
    src: templates/empty.j2
    dest: /tmp/empty.j2
```

$ cat roles/test/templates/empty.j2

## Versions 2.1.4.0 ##

$ ansible-playbook test.yaml 

PLAY [Test the test role] ******************************************************

TASK [setup] *******************************************************************
ok: [ws]

TASK [test : Install test template from role] **********************************
changed: [ws]

PLAY RECAP *********************************************************************
ws                         : ok=2    changed=1    unreachable=0    failed=0   

## Versions 2.2.1.0 and 2.3.0 ##

$ ansible-playbook test.yaml 

PLAY [Test the test role] ******************************************************

TASK [Gathering Facts] *********************************************************
ok: [ws]

TASK [test : Install test template from role] **********************************
fatal: [ws]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find 'templates/empty.j2' in expected paths."}
        to retry, use: --limit @/sites/site1/ansible/test.retry

PLAY RECAP *********************************************************************
ws                         : ok=1    changed=0    unreachable=0    failed=1

**Comment by wltjr** [comment]
Seems this may be specific to the templates module. Previous behavior was
role_path, now it seems to be role_path/templates, so when I add templates to the path, it ends up as role_path/templates/templates and fails. Not sure if other modules are doing this as well.

**Comment by jctanner** [comment]
@wltjr I'm unable to reproduce this on any of the versions you've specified. I did notice this line in your description though ...

```
mkdir -p roles/test/tasks roles/tests/templates
```

Did you make a typo in the description or did you accidentally create a "test" and a "tests" role?

needs_info

**Comment by wltjr** [comment]
Yes that was a typo, sorry I will edit and correct. I got someone else who was on 2.2.0 to replicate. They discovered that it worked when templates was not part of the path. I attached a archive of the test.
[ansible_role_test.zip](https://github.com/ansible/ansible/files/794077/ansible_role_test.zip). Not sure what else I can do to help replicate.

**Comment by wltjr** [comment]
@jctanner What version of python are  you using? I wonder if it is an issue in that. I am on 2.7. The person running 2.2.0 that had it fail is also on python 2.7.

**Comment by fia5000** [comment]
I am able to replicate this with 2.2.1.0.

**Comment by jctanner** [comment]
[test.txt](https://github.com/ansible/ansible/files/804402/test.txt)

@wltjr my test results from your zipfile are attached. I still don't seen any issue.

```
[jtanner@fedmac AP-21735]$ uname -a
Linux fedmac.lab.net 4.9.9-200.fc25.x86_64 #1 SMP Thu Feb 9 17:28:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[jtanner@fedmac AP-21735]$ cat /etc/redhat-release 
Fedora release 25 (Twenty Five)
[jtanner@fedmac AP-21735]$ python --version
Python 2.7.13
```

Please re-run on your machine with -vvvv so we can see if there's anything related to the connection method(s).

needs_info

**Comment by wltjr** [comment]
I see that it worked for you... I can see about getting a log from the person who said it failed on 2.2.0. Here the requested output. I should have provided initially.
[ansible-test-2.1.4.0.txt](https://github.com/ansible/ansible/files/804951/ansible-test-2.1.4.0.txt)
[ansible-test-2.2.1.0.txt](https://github.com/ansible/ansible/files/804952/ansible-test-2.2.1.0.txt)

I am on the same version of python
```bash
# python2 --version
Python 2.7.13
```

The system python is 3, but Ansible uses 2.7
```bash
[ebuild   R    ] app-admin/ansible-2.2.1.0::gentoo  USE="-keyczar {-test}" PYTHON_TARGETS="python2_7"
```
Really cannot explain. I have even tried using role_path in ansible.cfg and no change. Given I have a role that uses role_path variable for an included task from another role. That works but then the following tasks that use the roles own path like this test fail. Its strange.

```yaml
---
- include: roles/firewall/tasks/firewall_extra_file.yaml
  vars:
    - { path: "{{ role_path }}/files" }

- name: Create bind directories
  tags: bind
  file: path=/etc/bind/{{ item.zone }} state=directory mode=0755
  with_items: "{{ zones }}"

- name: Configure bind zones
  tags: bind
  template:
    src: templates/etc/bind/zones/pri.{{ item[1] }}.j2
    dest: /etc/bind/{{ item[0].zone }}/pri.{{ item[1] }}
    mode: 0644
    backup: yes
  notify: Restart named
  with_nested:
    - "{{ zones }}"
    - "{{ domains }}"

- name: Configure bind
  tags: bind
  template:
    src: templates/etc/bind/named.conf.j2
    dest: /etc/bind/named.conf
    mode: 0644
    backup: yes
  notify: Restart named
```
In that, the include task works using role_path variable. But then the last 2 tasks configuring bind fail. With those being in the same location. I tried removing the top entry and had no effect. The remaining ones failed. That is for the templates directory in that role. role_path is clearly populated just not in use when not specified. The above works as the test does in 2.1.4.0, but fails in 2.2.1.0 just as the test in this issue.
