### ISSUE TITLE
os_stack fails with AttributeError

### ISSUE THREAD

**Issue by ericcitaire** [ansible/ansible#21770]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
os_stack module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When the stack creation fails (`stack_status != 'CREATE_COMPLETE'`), the module raises an `AttributeError`.

##### STEPS TO REPRODUCE
1. Create a Heat template `template.yml` like so :
```yaml
# Simple Heat template which will fail quickly
heat_template_version: 2013-05-23
resources:
  wait_condition:
    type: OS::Heat::WaitCondition
    properties:
      handle: {get_resource: wait_handle}
      count: 1
      timeout: 5
  wait_handle:
    type: OS::Heat::WaitConditionHandle
```

2. Run `os_stack` module :
```bash
ansible -m os_stack -a 'name=failing_stack template=template.yml' localhost
```

##### EXPECTED RESULTS
The module should not raise an error in case of a failure. It should call `module.fail_json()` with a proper error message.

##### ACTUAL RESULTS
The module raises an `AttributeError` :
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'bool' object has no attribute 'id'
```

Full traceback :
```python
Traceback (most recent call last):
  File "/tmp/ansible_pfxIaX/ansible_module_os_stack.py", line 262, in <module>
    main()
  File "/tmp/ansible_pfxIaX/ansible_module_os_stack.py", line 247, in main
    id=stack.id)
AttributeError: 'bool' object has no attribute 'id'
```
