### ISSUE TITLE
yum_repository does not import gpgkey

### ISSUE THREAD

**Issue by tronicum** [ansible/ansible#21783]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
yum_repository

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 75d7c70e70) last updated 2017/02/22 16:04:21 (GMT +200)
  config file = /Users/sels.s/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
running ansible on OSX (10.11.6)
Target os is Redhat EL 7.3

##### SUMMARY
I want to install an RPM from a Repo, including the GPG Key

##### STEPS TO REPRODUCE

```yaml
---
- hosts: '{{ host }}'
  environment:
    http_proxy: http://192.168.160.x:3128
    https_proxy: http://192.168.160.x:3128
  tasks:
  - name: add zabbix repo
    yum_repository:
      name: zabbix
      description: Zabbix repo
      baseurl: http://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/
      gpgkey: https://repo.zabbix.com/zabbix-official-repo.key
  - name: install zabbix agent
    yum: name=zabbix-agent state=latest
  - name: make sure server is set (dirty implementation)
    lineinfile: dest=/etc/zabbix/zabbix_agentd.conf regexp=^Server= line=Server=127.0.0.1,192.168.x.x
  - name: make sure zabbix client ist (re)started
    service: name=zabbix-agent state=restarted
```

##### EXPECTED RESULTS
Installing the RPM, including the gpgkey https://repo.zabbix.com/zabbix-official-repo.key

##### ACTUAL RESULTS

```yaml
fatal: [my-target-hostname]: FAILED! => {
    "changed": true,
    "failed": true,
    "invocation": {
        "module_args": {
            "conf_file": null,
            "disable_gpg_check": false,
            "disablerepo": null,
            "enablerepo": null,
            "exclude": null,
            "install_repoquery": true,
            "list": null,
            "name": [
                "zabbix-agent"
            ],
            "state": "latest",
            "update_cache": false,
            "validate_certs": true
        }
    },
    "msg": "warning: /var/cache/yum/x86_64/7Server/zabbix/packages/zabbix-agent-3.2.3-1.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID a14fe591: NOKEY\nImporting GPG key 0x79EA5ED4:\n Userid     : \"Zabbix SIA <packager@zabbix.com>\"\n Fingerprint: fbab d5fb 2025 5eca b22e e194 d13d 58e4 79ea 5ed4\n From       : https://repo.zabbix.com/zabbix-official-repo.key\n\n\nPublic key for zabbix-agent-3.2.3-1.el7.x86_64.rpm is not installed\n\n\n Failing package is: zabbix-agent-3.2.3-1.el7.x86_64\n GPG Keys are configured as: https://repo.zabbix.com/zabbix-official-repo.key\n\n",
    "rc": 1,
    "results": [
        "Loaded plugins: product-id, search-disabled-repos, subscription-manager\nResolving Dependencies\n--> Running transaction check\n---> Package zabbix-agent.x86_64 0:3.2.3-1.el7 will be installed\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package              Arch           Version               Repository      Size\n================================================================================\nInstalling:\n zabbix-agent         x86_64         3.2.3-1.el7           zabbix         338 k\n\nTransaction Summary\n================================================================================\nInstall  1 Package\n\nTotal size: 338 k\nInstalled size: 1.1 M\nDownloading packages:\nRetrieving key from https://repo.zabbix.com/zabbix-official-repo.key\n"
    ]
}
```

If I run a  manual 
```
yum install zabbix-agent
``` 
on that host, yum asks me to confirm the key:
```
=========================================================================================================================================================================================================
 Package                                            Arch                                         Version                                              Repository                                    Size
=========================================================================================================================================================================================================
Installing:
 zabbix-agent                                       x86_64                                       3.2.3-1.el7                                          zabbix                                       338 k

Transaction Summary
=========================================================================================================================================================================================================
Install  1 Package

Total size: 338 k
Installed size: 1.1 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7Server/zabbix/packages/zabbix-agent-3.2.3-1.el7.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID a14fe591: NOKEY
Retrieving key from https://repo.zabbix.com/zabbix-official-repo.key
Importing GPG key 0x79EA5ED4:
 Userid     : "Zabbix SIA <packager@zabbix.com>"
 Fingerprint: fbab d5fb 2025 5eca b22e e194 d13d 58e4 79ea 5ed4
 From       : https://repo.zabbix.com/zabbix-official-repo.key
Is this ok [y/N]:
```

I could disable the gpgcheck but having the https secured URL I want yum to download the key and add it. There is another issue that reports problem on adding the key manually #20711

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
The key you are using wasn't used to sign the package you are trying to install. Please change the `gpgkey` to `https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591` and it will work.

```
- hosts: all
  become: yes
  tasks:
    - yum_repository:
        name: zabbix
        description: Zabbix repo
        baseurl: http://repo.zabbix.com/zabbix/3.2/rhel/$releasever/$basearch/
        gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591

    - package:
        name: zabbix-agent
```

```
PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [test-gpgkey]

TASK [yum_repository] **********************************************************
changed: [test-gpgkey]

TASK [package] *****************************************************************
changed: [test-gpgkey]

PLAY RECAP *********************************************************************
test-gpgkey                : ok=3    changed=2    unreachable=0    failed=0
```

@ansibot please close this issue as this is `notabug`.
