### ISSUE TITLE
nxos_config: Not idempotent when used with src

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21828]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
nxos_command

##### ANSIBLE VERSION
```
b8d308d919c89d86dc72d4fd62335b9f948544f1
```

##### SUMMARY
Running the following playbook shows a change

```yaml
- name: setup
  nxos_config:
    commands:
      - no description
      - no shutdown
    parents:
      - interface Ethernet2/5
    match: none
    provider: "{{ cli }}"

- name: configure device with config
  nxos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - "result.changed == true"

- name: check device with config
  nxos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - "result.changed == false"

```

##### STEPS TO REPRODUCE
```
cd test/integration
time ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvvv  -i  inventory.network-jobarker nxos.yaml  -e "limit_to=nxos_config"
```

Note that depending when you look at this bug you may have to comment out the `- "result.updates is not defined"` tests
