### ISSUE TITLE
nxos_nxapi: Not idempotent 

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21832]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
nxos_nxapi

##### ANSIBLE VERSION
```
b8d308d919c89d86dc72d4fd62335b9f948544f1
```

##### SUMMARY
Looks like nxapi isn't detecting the following or for some othe reason wants to send the following commands
```yaml
    "changed": true, 
    "commands": [
        "nxapi https port 9443"
    ], 
```

On a second run, and therefore isn't idempotent

##### STEPS TO REPRODUCE
`
time ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvvv  -i  inventory.network nxos.yaml  -e "limit_to=nxos_nxapi"
`
