### ISSUE TITLE
nxos_template: Not reading transport/provider correctly

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21835]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
nxos_template

##### ANSIBLE VERSION
```
b8d308d919c89d86dc72d4fd62335b9f948544f1
```

##### SUMMARY
Looks like `nxos_template` isn't correctly reading in the `transport` option from `provider`.

I wonder if this is because `nxos_template` is using `NetworkModule` rather than `AnsibleModule`
```yaml
- name: configure device with config
  nxos_template:
    src: basic/config.j2
    provider: "{{ cli }}"
    force: yes
  register: result

```

Gives
```yaml
fatal: [nxos01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "authorize": false, 
            "backup": false, 
            "force": true, 
            "host": "nxos01", 
            "include_defaults": true, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "provider": {
                "host": "nxos01", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "use_ssl": null, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": null
            }, 
            "src": "interface Ethernet2/5\n   description this is a test\n   shutdown\n\n", 
            "timeout": 10, 
            "transport": "cli", 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    }, 
    "msg": "value of transport must be one of: , got: cli"
}
```

Noteice that `transport` *is* returned in the above both at the top level, and under provider
##### STEPS TO REPRODUCE
`
time ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvvv  -i  inventory.network nxos.yaml  -e "limit_to=nxos_template"
`
