### ISSUE TITLE
create list based on a dynamic number of inventory groups

### ISSUE THREAD

**Issue by dirkvdplas** [ansible/ansible#21872]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
set_facts /  with_items / vars_file

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.3 (Maipo)

##### SUMMARY
I have a simple YML vars file as input-file for network configuration which is passed to playbook. The YML file contains a dynamic number of definitions which refers to sites which are defined in the host inventory. 

In the playbook  I want to create a new list which combines all devices based on the mentioned sites in vars file in a new list. So I need to iterate over the "site names" defined in the linput ist, lookup the specifics group to get all devices which I need to process further on in the play (omitted in the output below)

Not sure if this is a bug, anyway at least it is suspicious because item variable is known when passed to debug module. An alternative solution to accomplish the required functionality is highly appreciated.

Dirk

##### STEPS TO REPRODUCE

```yaml

Example of vars-file: network-input.yml

---

vpn_id: 999
vpn_name: TST

scope:
      dc1: 10.0.0.0/24
      dc2: 192.168.0.0.0/24
      dc3: 172.16.1.0/24


+++++++++++++++++++++

playbook:

---

- hosts: localhost
  vars_files:
              - "network-input.yml"
  strategy: debug
  gather_facts: false
  tasks:

    - name: Debug vars
      debug: msg=vars="{{groups[item]}}"
      with_items: "{{ scope }}"

    - name: create new combined list based on input
      set_fact:
         var3: "{{ groups['dc1'] }} + {{ groups[item] }} "
         with_items: "{{ scope }}"

#    - name: Displaying all groups
#      debug: msg=vars="{{var3}}"


+++++++++++++ inventory ++++++++++
[dc1]
dc1-host1
dc1-host2

[dc2]
dc2-host1
dc2-host2

[dc3]
dc3-host1
dc3-host2

```

##### EXPECTED RESULTS
In the debug output all looks fine. All hosts in the referenced sites are listed. But strange enough  when same construct is applied under set_fact to actually produce the new list this results in an error (undefined variable item)

##### ACTUAL RESULTS

```
PLAYBOOK: for-github.yml *******************************************************
1 plays in for-github.yml

PLAY [localhost] ***************************************************************

TASK [Debug vars] **************************************************************
task path: /opt/gbitools/ansible/ntc-ansible/for-github.yml:10
ok: [localhost] => (item=dc2) => {
    "invocation": {
        "module_args": {
            "msg": "vars=\"[u'dc2-host1', u'dc2-host2']\""
        },
        "module_name": "debug"
    },
    "item": "dc2",
    "msg": "vars=\"[u'dc2-host1', u'dc2-host2']\""
}
ok: [localhost] => (item=dc3) => {
    "invocation": {
        "module_args": {
            "msg": "vars=\"[u'dc3-host1', u'dc3-host2']\""
        },
        "module_name": "debug"
    },
    "item": "dc3",
    "msg": "vars=\"[u'dc3-host1', u'dc3-host2']\""
}
ok: [localhost] => (item=dc1) => {
    "invocation": {
        "module_args": {
            "msg": "vars=\"[u'dc1-host1', u'dc1-host2']\""
        },
        "module_name": "debug"
    },
    "item": "dc1",
    "msg": "vars=\"[u'dc1-host1', u'dc1-host2']\""
}

TASK [create new combined list based on input] *********************************
task path: /opt/gbitools/ansible/ntc-ansible/for-github.yml:14
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'item' is undefined\n\nThe error appears to have been in '/opt/gbitools/ansible/ntc-ansible/for-github.yml': line 14, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: create new combined list based on input\n      ^ here\n"
}
Debugger invoked


```

**Comment by jctanner** [comment]
@dirkvdplas please check the alignment of your final with_items parameter.

```

    - name: create new combined list based on input
      set_fact:
         var3: "{{ groups['dc1'] }} + {{ groups[item] }} "
         with_items: "{{ scope }}"
```

Should probably be ...

```

    - name: create new combined list based on input
      set_fact:
         var3: "{{ groups['dc1'] }} + {{ groups[item] }} "
      with_items: "{{ scope }}"
```

needs_info
