### ISSUE TITLE
win_chocolatey errors when upgrading powershell

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#21873]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

win_chocolatey

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0 (devel 01436cf186) last updated 2017/02/21 12:05:34 (GMT -500)
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Ansible configuration from git clone

##### OS / ENVIRONMENT

Control host macOS 10.12.3
Managed host Windows 7

##### SUMMARY

Attempting to upgrade powershell4 to powershell5 using the win_chocolatey module.

##### STEPS TO REPRODUCE

```yaml
- name: install powershell5
  win_chocolatey:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - "powershell"
  register: check_powershell5
  when: "{{ ansible_PSVersionTable.Major|int < 5 }}"
  tags: chocolatey
```

##### EXPECTED RESULTS

Upgrade/install of powershell5

##### ACTUAL RESULTS

Ansible/win_chocolatey error out.

https://gist.github.com/basictheprogram/018789574e04104932c002777e5a3a76
