### ISSUE TITLE
Add win_chocolatey proxy support

### ISSUE THREAD

**Issue by ptemplier** [ansible/ansible#21886]
_From @ptemplier on September 23, 2016 12:33_

##### ISSUE TYPE
- Feature Pull Request
##### COMPONENT NAME

win_chocolatey
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

Add win_chocolatey proxy support.
Add parameters to specify proxy url, user and password to be used when installing chocolatey and when installing package.
##### WORKAROUND

```
- name:  Check if chocolatey is installed
  win_stat: path='C:/ProgramData/chocolatey'
  register: choco_install

- name: Install Chocolatey using proxy
  raw: 'Set-ExecutionPolicy -ExecutionPolicy Unrestricted ; $wc=new-object net.webclient ; $proxy = New-Object System.Net.WebProxy("{{http_proxy_host}}:{{http_proxy_port}}", $true)  ; $wc.proxy=$proxy ; iex($wc.downloadstring("https://chocolatey.org/install.ps1"))'
  when: choco_install.stat.exists == False

- name: Chocolatey set proxy
  raw: 'choco config set proxy http://{{http_proxy_host}}:{{http_proxy_port}}'

- name: install curl
  win_chocolatey:
    name: curl
```

_Copied from original issue: ansible/ansible-modules-extras/pull/3022_
