### ISSUE TITLE
Network modules: Only password should be masked under provider

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21892]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_*
junos_*
Most likely all platforms

##### ANSIBLE VERSION
```

```

##### SUMMARY
Marking as P1 as leaking passwords is bad
During the argspec work that went into the Network modules in 2.3 we seem to have lost the feature that only masks out `password:` in `provider:`

##### STEPS TO REPRODUCE
```yaml

```

##### ACTUAL RESULTS
```yaml
fatal: [ios01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": null, 
            "commands": [
                "show version", 
                "show foo"
            ], 
            "host": null, 
            "interval": 1, 
            "match": "all", 
            "password": null, 
            "port": null, 
            "provider": {
                "auth_pass": null, 
                "authorize": null, 
                "host": "ios01", 
                "password": "password12345", 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "username": "cisco"
            }, 
            "retries": 10, 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null, 
            "wait_for": null

```
