### ISSUE TITLE
Git module do not update local copy if tag ref is updated, but reports diff in check + diff mode

### ISSUE THREAD

**Issue by davidfischer-ch** [ansible/ansible#21899]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module git

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Nothing to declare

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS

##### SUMMARY
1. create a tag like v1.0
2. use git module to "clone" the project with version=v1.0
3. make some commits and push force v1.0 (=changed)
4. use git module to "clone" the project with version=v1.0

Should report changed and local copy should be updated.
Reports no change and do not update local copy.
But running in check + diff mode then changes are reported!

##### STEPS TO REPRODUCE
```yaml
- hosts:
    - localhost
  tasks:
    - name: Clone some
      git: repo=some.git dest=/some force=yes version=v1.0
```

##### EXPECTED RESULTS
```
TASK [...]
changed: [localhost] ...
```

##### ACTUAL RESULTS
```
TASK [...]
ok: [localhost] ...
```
