### ISSUE TITLE
cron: state=absent is not idempotent (always reports changed)

### ISSUE THREAD

**Issue by mgedmin** [ansible/ansible#21904]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cron

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Debian GNU/Linux 8.6 (jessie) on the target

##### SUMMARY

The following task
```
    - name: Cron job to delete old Qvarn logs
      cron:
        name: "delete old qvarn logs"
        minute: 12
        hour: 1
        job: "find /var/log/qvarn -mtime +5 -delete"
        state: absent
```

always reports `changed`, no matter how many times you run it.
