### ISSUE TITLE
nxos_command: results.result[0] -> result.stdout[0]

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21900]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_command
##### ANSIBLE VERSION
```
ansible 2.3.0 (test_ios_again 1dde9971ae) last updated 2017/02/23 09:43:19 (GMT +100)

```

##### SUMMARY
This change may be correct, though it is a change in functionality...

In 2.2

```yaml
- name: Check NXAPI state
  nxos_command:
      commands:
          - show feature | grep nxapi
      provider: "{{ cli }}"
  register: result

- name: Assert NXAPI is enabled
  assert:
      that: result.result[0] | search('enabled')
```

in 2.3 that's changed to
```yaml
      that: result.stdout[0] | search('enabled')
```
ie `result.result[0]` to `result.stdout[0]`
