### ISSUE TITLE
eos_config: not idempotent with src:

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21903]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION
```
ansible 2.3.0 (test_ios_again 1dde9971ae) last updated 2017/02/23 09:43:19 (GMT +100)

```

##### STEPS TO REPRODUCE
 time ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvvv  -i  inventory.network-jobarker eos.yaml  -e "limit_to=eos_config" 

```yaml
- name: setup
  eos_config:
    commands:
      - no description
      - no shutdown
    parents:
      - interface Ethernet5
    match: none
    provider: "{{ cli }}"

- name: configure device with config
  eos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result

- assert:
    that:
      - "result.changed == true"


- name: check device with config
  eos_config:
    src: basic/config.j2
    provider: "{{ cli }}"
    match: none
  register: result

- assert:
    that:
      # Idempotent test
# https://github.com/ansible/ansible-modules-core/issues/4807
      - "result.changed == false"

```

##### ACTUAL RESULTS
```yaml
TASK [eos_config : configure device with config] *************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/eos_config/tests/cli/src_match_none.yaml:14
<veos01> connection transport is cli
<veos01> socket_path: /home/johnb/.ansible/pc/ca5960d27a
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/network/eos/eos_config.py
<veos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<veos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<veos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1487951751.88-271989310078853 `" && echo ansible-tmp-1487951751.88-271989310078853="` echo /home/johnb/.ansible/tmp/ansible-tmp-1487951751.88-271989310078853 `" ) && sleep 0'
<veos01> PUT /tmp/tmpABmIyk TO /home/johnb/.ansible/tmp/ansible-tmp-1487951751.88-271989310078853/eos_config.py
<veos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1487951751.88-271989310078853/ /home/johnb/.ansible/tmp/ansible-tmp-1487951751.88-271989310078853/eos_config.py && sleep 0'
<veos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1487951751.88-271989310078853/eos_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1487951751.88-271989310078853/" > /dev/null 2>&1 && sleep 0'
changed: [veos01] => {
    "changed": true, 
    "commands": [
        "interface Ethernet5", 
        "description this is a test", 
        "shutdown"
    ], 
    "diff": {
        "prepared": "--- system:/running-config\n+++ session:/ansible_1487951752-session-config\n@@ -57,6 +57,8 @@\n    shutdown\n !\n interface Ethernet5\n+   description this is a test\n+   shutdown\n    no switchport\n    vrf forwarding test\n !"
    }, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": true, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "lines": null, 
            "match": "none", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "auth_pass": null, 
                "authorize": true, 
                "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "use_ssl": null, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": null
            }, 
            "replace": "line", 
            "save": false, 
            "src": "interface Ethernet5\n   description this is a test\n   shutdown\n\n", 
            "ssh_keyfile": null, 
            "timeout": null, 
            "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": null, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": null
        }
    }, 
    "session": "ansible_1487951752", 
    "updates": [
        "interface Ethernet5", 
        "description this is a test", 
        "shutdown"
    ]
}

TASK [eos_config : assert] ***********************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/eos_config/tests/cli/src_match_none.yaml:21
ok: [veos01] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [eos_config : check device with config] *****************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/eos_config/tests/cli/src_match_none.yaml:28
<veos01> connection transport is cli
<veos01> socket_path: /home/johnb/.ansible/pc/ca5960d27a
Using module file /home/johnb/git/ansible-inc/ansible/lib/ansible/modules/network/eos/eos_config.py
<veos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<veos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<veos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1487951755.36-2294956198958 `" && echo ansible-tmp-1487951755.36-2294956198958="` echo /home/johnb/.ansible/tmp/ansible-tmp-1487951755.36-2294956198958 `" ) && sleep 0'
<veos01> PUT /tmp/tmpmw2vI9 TO /home/johnb/.ansible/tmp/ansible-tmp-1487951755.36-2294956198958/eos_config.py
<veos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1487951755.36-2294956198958/ /home/johnb/.ansible/tmp/ansible-tmp-1487951755.36-2294956198958/eos_config.py && sleep 0'
<veos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1487951755.36-2294956198958/eos_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1487951755.36-2294956198958/" > /dev/null 2>&1 && sleep 0'
changed: [veos01] => {
    "changed": true, 
    "commands": [
        "interface Ethernet5", 
        "description this is a test", 
        "shutdown"
    ], 
    "diff": {
        "prepared": ""
    }, 
    "invocation": {
        "module_args": {
            "after": null, 
            "auth_pass": null, 
            "authorize": true, 
            "backup": false, 
            "before": null, 
            "config": null, 
            "defaults": false, 
            "force": false, 
            "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "lines": null, 
            "match": "none", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "auth_pass": null, 
                "authorize": true, 
                "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "use_ssl": null, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": null
            }, 
            "replace": "line", 
            "save": false, 
            "src": "interface Ethernet5\n   description this is a test\n   shutdown\n\n", 
            "ssh_keyfile": null, 
            "timeout": null, 
            "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": null, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": null
        }
    }, 
    "session": "ansible_1487951755", 
    "updates": [
        "interface Ethernet5", 
        "description this is a test", 
        "shutdown"
    ]
}

TASK [eos_config : assert] ***********************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible/test/integration/targets/eos_config/tests/cli/src_match_none.yaml:35
fatal: [veos01]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

```
