### ISSUE TITLE
to_bool filter functionality extension

### ISSUE THREAD

**Issue by anryko** [ansible/ansible#21914]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

plugins/filter/core.py

##### ANSIBLE VERSION

```
ansible 2.3.0 (main 3b1500d033) last updated 2017/02/23 09:41:19 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/opt/ansible/ansible/library']
```

##### SUMMARY

Ansible bool filter behavior was surprising to me. After investigating YAML standard I understand the motivation behind this implementation. However, IMHO it would be useful to step over YAML limitations and extend ```|bool``` functionality.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - set_fact:
        z_dict_empty: "{{ {}|bool }}"
        z_dict_not_empty: "{{ {'key': 1}|bool }}"
        z_str_empty: "{{ ''|bool }}"
        z_str_not_empty: "{{ 'aaa'|bool }}"
        z_str_eq_yes: "{{ 'yes'|bool }}"
        z_int_0: "{{ 0|bool }}"
        z_int_1: "{{ 1|bool }}"
        z_int_negative: "{{ -7|bool }}"
    - debug:
        var: hostvars[inventory_hostname]
```

##### EXPECTED RESULTS

```bash
$ ansible-playbook plays/bool-test.yml | grep "\"z_"
        "z_dict_empty": false,
        "z_dict_not_empty": true,
        "z_int_0": false,
        "z_int_1": true,
        "z_int_negative": true,
        "z_str_empty": false,
        "z_str_eq_yes": true,
        "z_str_not_empty": false
```

##### ACTUAL RESULTS

```bash
$ ansible-playbook plays/bool-test.yml | grep "\"z_"
        "z_dict_empty": false,
        "z_dict_not_empty": false,
        "z_int_0": false,
        "z_int_1": true,
        "z_int_negative": false,
        "z_str_empty": false,
        "z_str_eq_yes": true,
        "z_str_not_empty": false
```
I acknowledge that this is a strange mix between Python variable truthiness and YAML... but I think this is better then what we have now.
