### ISSUE TITLE
Feature request: Enable squash action for portage module

### ISSUE THREAD

**Issue by cognifloyd** [ansible/ansible#21928]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`portage` module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/cognifloyd/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
/home/cognifloyd/.ansible.cfg:
```
[defaults]
cow_selection = small
```

##### OS / ENVIRONMENT
Gentoo
/etc/gentoo-release:
```
Gentoo Base System release 2.3
```

##### SUMMARY
Please enable squash action for portage module.

0c320e1 made it possible to use squash via the package module (see [extras pull 3556](https://github.com/ansible/ansible-modules-extras/pull/3556)). It should be enabled directly for the portage module ([DEFAULT_SQUASH_ACTIONS](https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py#L285)).

##### STEPS TO REPRODUCE
test.yml
```yaml
- hosts: all
  vars:
    my_required_packages:
      - systemd
      - bash
  tasks:
    - name: ensure installed (portage module space separated list)
      portage:
        name: "{{ my_required_packages | join(' ') }}"
        state: installed
    - name: ensure installed (portage module with_items)
      portage:
        name: "{{ item }}"
        state: installed
      with_items: "{{ my_required_packages }}"
    - name: ensure installed (portage module list)
      portage:
        name: "{{ my_required_packages }}"
        state: installed
    - name: ensure installed (package module)
      package:
        name: "{{ item }}"
        state: installed
      with_items: "{{ my_required_packages }}"
```

##### EXPECTED RESULTS
All of these tasks should work.

##### ACTUAL RESULTS
I haven't run this on the latest devel. The last two tasks fail on 2.2.1.0 because it doesn't have 0c320e1 which won't land till 2.3. They should succeed on devel, but without squashing.

**Comment by ansibot** [comment]
cc @wltjr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
you can set `squash_actions` in ansible.cfg or ANSIBLE_SQUASH_ACTIONS environment var

FYI, we plan on removing 'squashing' in the future, so you can pass the list directly to the module

**Comment by cognifloyd** [comment]
Is there a discussion in the ML or somewhere else where I can learn more about removing squashing? What will replace it? Is the replacement to pass a list directly instead of via with_items?

**Comment by wltjr** [comment]
Anything else that needs to be done here? Should it remain open or be closed?

**Comment by cognifloyd** [comment]
@bcoca you said squashing will be removed. So, I guess that means portage won't ever be added to DEFAULT_SQUASH_ACTIONS https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py#L306

The comment above DEFAULT_SQUASH_ACTIONS (from two years ago) says:

```
# In the future we should probably generalize this even further
# (mapping of param: squash field)"
```

Is there a feature request somewhere for this? Does that mean that portage could eventually opt-in by adding a squash field? Or when you say that squash actions will be removed, are you saying that no squashing will be done at all?

**Comment by wltjr** [comment]
It seems to be a general Ansible feature, not module specific. I think they are removing that function as its replaced by the same internally. Not sure just my take on the comments thus far. I am not as familiar with squashing. Seems its passing a list or something. Which should be possible now or with new versions of ansible.

**Comment by wltjr** [comment]
If this does require any modification. I am happy to modify the portage module as needed. I plan to further it time permitting. Ideally hooking directly into portage python code rather than invoking another python process. Though that may be unsafe if it has an issue may take out ansible as well. The remote python actions, if running portage module under same instance of python.

**Comment by bcoca** [comment]
To support squashing a module just has to accept a list as well as a single item, there is no need to add to the harcoded defaults, you can do this in config.

As for removing the feature, we plan to phase it out and have users just pass a list directly to the module vs having loops do 'magic' to do same.

**Comment by sivel** [comment]
Additionally, any module that could support squashing, can also be achieved without squashing, by providing `name` with a YAML list or a comma separated value of packages, as opposed to using `with_items`.

Squashing basically takes the value from `with_items` and passes it directly to `name` as a list.

The following example, is typically what I do whenever possible:

```
    - name: ensure installed (portage module list)
      portage:
        name: "{{ my_required_packages }}"
        state: installed
```
