### ISSUE TITLE
pip install latest devel branch fails.

### ISSUE THREAD

**Issue by xuchen81** [ansible/ansible#21945]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pip

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### OS / ENVIRONMENT

local: Mac OS
remote: Ubuntu 14.04
Remote git version: git version 1.9.1

##### SUMMARY

Looks like when I run this for the first time without /srv/example/virtualenvs/provisioner/src/devel directory, it will be successful, and then it will fail if I run it again after the first with the following error message.

##### STEPS TO REPRODUCE

```yaml
- name: Install latest ansible devel branch.
  pip:
    name: git+git://github.com/ansible/ansible.git#egg=devel
    state: forcereinstall
    virtualenv: "{{venv_home}}"
    virtualenv_command: virtualenv
  become: yes
```

##### ACTUAL RESULTS

```
TASK [ansible : Install latest ansible devel branch.] *************************************************************************************************************************************************************************************
fatal: [xx.xxx.xx.xxx]: FAILED! => {"changed": false, "cmd": "/srv/example/virtualenvs/provisioner/bin/pip install -U --force-reinstall -e git+git://github.com/ansible/ansible.git#egg=devel", "failed": true, "msg": "stdout: Obtaining devel from git+git://github.com/ansible/ansible.git#egg=devel\n  Updating /srv/example/virtualenvs/provisioner/src/devel clone\nfatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n\n:stderr:   Could not find a tag or branch 'origin/master', assuming commit.\nCommand \"git reset --hard -q origin/master\" failed with error code 128 in /srv/example/virtualenvs/provisioner/src/devel\n"}
```
