### ISSUE TITLE
remountrw before any other action on a read-only system

### ISSUE THREAD

**Issue by kosli** [ansible/ansible#2197]
Hi

i am using voyage linux (http://linux.voyage.hk/) on small embedded devices. voyage runs a debian distribution in read-only mode. so the first thing that i need to do before i can do any changs to the running system is to execute "remountrw" (which remounts the root file system as writable). 

i have been trying with the shell and command modules to execute remountrw in a playbook before doing anything else. but it seems that even for that ansible has to copy files over and execute them. is there a way to execute a command on the remote host WITHOUT copying any files over? or what is the appropriate way to execute the "remountrw" command? 

thanks for sharing your ideas
 KoS

**Comment by kosli** [comment]
i am connecting as root to the remote machine and i thought that, regarding #188, the files should be written to /var/tmp. indeed the files are written to $HOME/.ansible/tmp. is this issue still open ? 

```
ESTABLISH CONNECTION FOR USER: root on PORT 22 TO xx
EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1361812061.99-191408239879480 && echo $HOME/.ansible/tmp/ansible-1361812061.99-191408239879480'
```

**Comment by kosli** [comment]
after looking through the source code i found a reference in https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py to the "remote_tmp" config option in the ansible.cfg file....  and it works :-)
there is no documentation (http://ansible.cc/docs/) about the config file nor the remote_tmp option. i only found a reference in the examples file which is missing in the ubuntu PPA. 

so i will let this issue here as reference for others that stumble over the same problem :-)

**Comment by mpdehaan** [comment]
I concur that we should document it.   I will make a note to do so.

It's also settable via the ANSIBLE_REMOTE_TMP environment variable.

BTW, very interested in what you are doing with Voyage as I'm always
interested in embedded stuff.   Shoot me an email at
michael.dehaan@gmail.com perhaps?

--Michael

**Comment by kosli** [comment]
thanks michael, i'll drop you an email.

just as a side note: in the end i used the "raw" module to install the required debian packages for ansible. here is my playbook for the initial run:

```
---
- hosts: all
  gather_facts: no
  user: root
  tasks:
  - name: mount read-writeable
    raw: remountrw
  - name: update apt
    action: raw apt-get -qq update
  - name: install python-simplejson python-apt
    raw: apt-get -q -y install python-simplejson python-apt
  - name: mount read-only
    raw: remountro
```
