### ISSUE TITLE
OpenSSL_{public,private}key do not expose the key's fingerprint(s)

### ISSUE THREAD

**Issue by KellerFuchs** [ansible/ansible#21974]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Modules openssl_privatekey and openssl_publickey

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/kellerfuchs/hashbang/admin-tools/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Debian “Stretch” (current testing release, undergoing freeze)

##### SUMMARY
The modules `openssl_privatekey` and `openssl_publickey` should provide, as returned values, the pubkey's hash, under various algorithms (say, SHA-1, SHA-256 and SHA-512; yes, SHA-1 is broken but lots of software only support it for pinning pubkeys).

Those hashes can then be used in configuration templates and so on.

##### STEPS TO REPRODUCE
An example playbook, inspired by <https://github.com/hashbang/admin-tools>, would look like
```yaml
- hosts: irc_servers
  tasks:
    - name: Create server-link certificate if needed
      openssl_privatekey:
        path: /home/unrealircd/server_link.pem
        size: 4096
        type: RSA
      register: link_key
      notify: [rehash ircd]

    - name: Create a matching self-signed cert
      command: openssl x509 [...]
      when: link_key.changed

    - name: Copy static configuration
      copy:
        src: "{{ item }}"
        dest: /home/core/unrealircd/{{ item | basename }}
      with_fileglob:
        - unrealircd/*.conf
        - unrealircd/ircd.motd
      notify: [rehash ircd]

    - name: Generate templated configuration
      template:
        src: "{{ item }}"
        dest: /home/core/unrealircd/{{ item | basename | regex_replace('\.j2$', '') }}
      with_fileglob:
        - unrealircd/*.j2
      notify: [rehash ircd]
```

Then, it becomes possible to use configuration snippets such as:
```
{% for server in groups.irc_servers if not server == ansible_fqdn %}
link {{ server }} {
    username *;
    hostname "{{ server }}";
    port 6697;
    password-connect "*";
    password-receive "{{ hostvars[server].link_key.fingerprint.sha256 }}" { sslclientcertfp; };
    hub *;
    class servers;
    options { [...] };
};
{% endfor %}
```

##### EXPECTED RESULTS
The service gets configured with SSL key pinning.

##### ACTUAL RESULTS
This feature doesn't yet exist, though it can be simulated manually by calling `openssl` and parsing the output...
