### ISSUE TITLE
cs_sshkeypair: unhandled case of already registered ssh keys

### ISSUE THREAD

**Issue by furkanmustafa** [ansible/ansible#21986]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudstack/cs_sshkeypair

##### ANSIBLE VERSION
```
ansible-playbook 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Nothing specific

##### OS / ENVIRONMENT
Using ansible in `alpine:3.5.0` docker image, also did `pip install sshpubkeys cs uritools`

##### SUMMARY
In a specific (east-2) region of IDCF Japan, API is returning 431 response (full detailed below).

##### STEPS TO REPRODUCE
Failing step config is below, and quite simple.

```yaml
- name: "SSH Key Registration"
  cs_sshkeypair:
    name: "{{ inventory_hostname }}"
    public_key: "{{ lookup('file', ssh_public_key_file) }}"
```

##### EXPECTED RESULTS
if I'm not wrong, if the API result says "the key is already registered", that means the step should not fail, and should marked as `not changed` or `ok` (some something else that does not fail?).

##### ACTUAL RESULTS
```
fatal: [***some-hostname-here****]: FAILED! => {"changed": false, "failed": true, "msg": "CloudStackException: ('HTTP 431 response from CloudStack', <Response [431]>, {u'errorcode': 431, u'uuidList': [], u'cserrorcode': 4350, u'errortext': u\"A key pair with key 'ssh-rsa AAAA...some ssh public key here ....c' already exists for this account.\"})"}
```
