### ISSUE TITLE
iosxr_template & iosxr_config: unable to enter configuration mode

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#21994]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
iosxr_config
iosxr_template

##### ANSIBLE VERSION
```
ansible 2.3.0 (iosxr_tests ebc2716be7) last updated 2017/02/27 12:09:47 (GMT +100)
```

##### SUMMARY
`"unable to enter configuration mode"` with `iosxr_config` and `iosxr_template`

##### STEPS TO REPRODUCE
`time ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvvv  -i  inventory.network iosxr.yaml  -e "limit_to=iosxr_config" -u root -k`

`time ANSIBLE_ROLES_PATH=targets  ansible-playbook -vvvvv  -i  inventory.networ iosxr.yaml  -e "limit_to=iosxr_template" -u root -k`

```yaml
- name: setup
  iosxr_config:
    commands:
      - no description
      - no shutdown
    parents:
      - interface Loopback999
    match: none

- name: configure device with config
  iosxr_config:
    src: basic/config.j2
  register: result
```

**basic/config.j2**
```yaml
interface Loopback999
 description this is a test
 shutdown

```

##### ACTUAL RESULTS
```yaml
TASK [iosxr_config : configure device with config] ***********************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible-workspace-2/test/integration/targets/iosxr_config/tests/cli/src_basic.yaml:13
Using module file /home/johnb/git/ansible-inc/ansible-workspace-2/lib/ansible/modules/network/iosxr/iosxr_config.py
<iosxr01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<iosxr01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<iosxr01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1488202112.61-275083561754384 `" && echo ansible-tmp-1488202112.61-275083561754384="` echo /home/johnb/.ansible/tmp/ansible-tmp-1488202112.61-275083561754384 `" ) && sleep 0'
<iosxr01> PUT /tmp/tmplhB6gE TO /home/johnb/.ansible/tmp/ansible-tmp-1488202112.61-275083561754384/iosxr_config.py
<iosxr01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1488202112.61-275083561754384/ /home/johnb/.ansible/tmp/ansible-tmp-1488202112.61-275083561754384/iosxr_config.py && sleep 0'
<iosxr01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1488202112.61-275083561754384/iosxr_config.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1488202112.61-275083561754384/" > /dev/null 2>&1 && sleep 0'
fatal: [iosxr01]: FAILED! => {
    "changed": false, 
    "err": "configure terminal\r\n\r                                    ^\r\n% Invalid input detected at '^' marker.\r\nRP/0/0/CPU0:iosxr01(config)#", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "after": null, 
            "backup": false, 
            "before": null, 
            "comment": "configured by iosxr_config", 
            "config": null, 
            "force": false, 
            "host": null, 
            "lines": null, 
            "match": "line", 
            "parents": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "replace": "line", 
            "src": "interface Loopback999\n description this is a test\n shutdown\n\n", 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null
        }
    }, 
    "msg": "unable to enter configuration mode"
}
	
```
