### ISSUE TITLE
nmcli module does not work as described for the dns4 paramater

### ISSUE THREAD

**Issue by juliedavila** [ansible/ansible#22093]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
ubuntu 16.04

##### SUMMARY
In the nmcli module there is a documentation bit AND an example, as follows:

```yml
# line 85 Docstring
dns4:
  required: False
  default: None
  description:
  - 'A list of upto 3 dns servers, ipv4 format e.g. To add two IPv4 DNS server addresses: ["192.0.2.53", "198.51.100.53"]'

# again in line 455 of the EXAMPLES string
# To add two IPv4 DNS server addresses:
- nmcli:
  conn_name: my-eth1
  dns4:
   - 192.0.2.53
   - 198.51.100.53
  state: present
```
This is implies that the parameter takes in `dns4` as a list. This is incorrect.

##### STEPS TO REPRODUCE

1. Create a task that is intended to update nameserver entries for an ipv4 interface

```yml
- nmcli:
    state: present
    type: ethernet
    conn_name: foo
    dns4:
        - 10.10.10.1
        - 10.10.100.1
```
##### EXPECTED RESULTS
For things to run as expected

##### ACTUAL RESULTS
Error message of
    `"msg": "Error: failed to modify ipv4.dns: invalid IPv4 address '['10.10.10.1''.\n", `

I have a patch and will submit the pull request momentarily.
