### ISSUE TITLE
Unable to have block variable in bulleted list

### ISSUE THREAD

**Issue by mathew-bulletin** [ansible/ansible#22117]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include_vars
##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

Unable to include block variable inside bulleted list.

##### STEPS TO REPRODUCE

```yaml
---

# vault_vars/variables.yml
var0:
  - {
      var1: "value1",
      var2: "value2",
      var3: |
        ABCDEF
        123456
        GHIJKL
        678910
    }

```
```yaml
---

# tasks/main.yml
- name: include variables
  include_vars:
    file="vault_vars/variables.yml"
```

##### EXPECTED RESULTS

Expect to include var0 successfully.

##### ACTUAL RESULTS

ansible-playbook execution failed.

```
TASK [replace_vault_placeholders : Include file from vault_vars/ directory] ****
task path: /etc/ansible/roles/include_vars/tasks/main.yml:4
fatal: [workstation]: FAILED! => {
    "ansible_facts": {}, 
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "file": "vault_vars/variables.yml"
        }, 
        "module_name": "include_vars"
    }, 
    "message": "Syntax Error while loading YAML.\n\n\nThe error appears to have been in 'True': line 6, column 13, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\n(could not open file to display line)"
}

```
