### ISSUE TITLE
In Ansible 2.3, junos action module hijacks junos_ task namespace and ignores library/

### ISSUE THREAD

**Issue by tjuberg** [ansible/ansible#22121]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

plugins/action/junos

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides


Making package: ansible-git 2.3.0.29085.76c46e9039-1 (Wed Mar  1 09:18:36 CET 2017)
```

##### OS / ENVIRONMENT

Arch linux, but should be N/A

##### SUMMARY

Starting in Ansible 2.3, the junos_ task namespace (and possibly others) is hijacked by plugins/action/junos even if you have junos_get_facts for example from https://github.com/Juniper/ansible-junos-stdlib placed in library/ of a playbook. The result is that plugins/action/junos instead is run and in our case due to differing arguments results in an error.

This is possibly related to issue #22094, and it seems even the built in junos facts module is currently broken in the same manner.

##### STEPS TO REPRODUCE

place contents of https://raw.githubusercontent.com/Juniper/ansible-junos-stdlib/master/library/junos_get_facts into library/ folder of a playbook
run example playbook below

```yaml
- name: Get JunOS facts
  hosts: mx104
  gather_facts: no
  connection: local
  tasks:

    - name: Gather Junos facts
      junos_get_facts:
        host={{ host }}
        user={{ default_user }}
        passwd={{ default_pw }}
        port=22
      register: junos
```

##### EXPECTED RESULTS

```
TASK [Gather Junos facts] **********************************************************************************************************************************************************************************************************
task path: /home/tjuberg/work/gitlab/bachelor_ansible/notjunos.yml:9
Using module file /home/tjuberg/work/gitlab/bachelor_ansible/library/notjunos_get_facts.py
```
##### ACTUAL RESULTS

library/junos_get_facts.py never gets called as the call is hijacked.

```
TASK [Gather Junos facts] **********************************************************************************************************************************************************************************************************
task path: /home/tjuberg/work/gitlab/bachelor_ansible/junos_facts.yml:9
using connection plugin netconf
<mx104> socket_path: /home/tjuberg/.ansible/pc/3309cc7c88
fatal: [mx104]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "unable to connect to control socket"
}
```
