### ISSUE TITLE
Windows module win_get_url don't use proxy when "force: no" used

### ISSUE THREAD

**Issue by ar7z1** [ansible/ansible#22126]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

windows/win_get_url

##### ANSIBLE VERSION

```
ansible 2.3.0 (win_get_url_force_with_proxy 76c46e9039) last updated 2017/03/01 12:57:19 (GMT +300)
  config file = /home/art/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Windows module [win_get_url](http://docs.ansible.com/ansible/win_get_url_module.html) don't use proxy when `force: no` used.

##### STEPS TO REPRODUCE

```yaml
- name: Download earthrise.jpg to specified path through a proxy server only if modified.
  win_get_url:
    url: http://www.example.com/earthrise.jpg
    dest: C:\Users\RandomUser\earthrise.jpg
    force: no
    proxy_url: http://10.0.0.1:8080
    proxy_username: username
    proxy_password: password
```

##### ACTUAL RESULTS

Got an error:
```
fatal: [host]: FAILED! => {"changed": false, "failed": true, "msg": "Error when requesting Last-Modified date from http://www.example.com/earthrise.jpg Exception calling \"GetResponse\" with \"0\" argument(s): \"The remote server returned an error: (407) Proxy Authentication Required.\"", "win_get_url": {"dest": "C:\\Users\\RandomUser\\earthrise.jpg", "url": "http://www.example.com/earthrise.jpg"}}
```
