### ISSUE TITLE
Mount  module: incorrect command-line arguments used for Solaris.

### ISSUE THREAD

**Issue by AlexZolotarenko** [ansible/ansible#22135]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

mount module 

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

Running ansible on ubuntu linux 16.04.1
Controlling hosts with Solaris 11.2/11.3

##### SUMMARY

mount module uses incorrect command-line arguments for SunOS,
"mount" command on Solaris does not support pointing to fstab file, 
but _set_fstab_args(args)  do not check if task is running against SunOS and in this case adds "-T  path_to_fstab..." to command-line arguments. 

##### STEPS TO REPRODUCE

Just try any mount task with state "mounted" against Solaris.

cat roles/nfs_client/defaults/main.yml 
```yaml
---
nfs_shares:
  - dst:        "/opt/storage"
    dst_owner:  "support"
    dst_mode:   "0755"
    dst_group:  "support"
    src:        "tribune:/opt/storage"

  - dst: "/opt/homes"
    src: "tribune:/opt/nfs/homes"
```
tail  roles/nfs_client/tasks/solaris.yml 
```yaml
  mount:	
    fstype:		"nfs"
    name:		"{{ share.dst }}"
    src:		"{{ share.src }}"
    state:		"mounted"

  with_items:		"{{ nfs_shares }}"
  loop_control:		
    loop_var:		"share"

```

##### EXPECTED RESULTS

According to these var and task, two NFS shares mounted on destination server. 

##### ACTUAL RESULTS

```
failed: [sulla] (item={u'dst_owner': u'support', u'src': u'tribune:/opt/storage', u'dst': u'/opt/storage', u'dst_group': u'support'}) => {"failed": true, "msg": "Error mounting /opt/storage: /sbin/mount: illegal option -- T\nUsage:\nmount [-v | -p]\nmount [-F FSType] [-V] [current_options] [-o specific_options]\n\t{special | mount_point}\nmount [-F FSType] [-V] [current_options] [-o specific_options]\n\tspecial mount_point\nmount -a [-F FSType ] [-V] [current_options] [-o specific_options]\n\t[mount_point ...]\n", "share": {"dst": "/opt/storage", "dst_group": "support", "dst_owner": "support", "src": "tribune:/opt/storage"}}
```

##### POTENTIAL FIX 
```
ansible@nero:~$ diff ./library/mount.py ./lib/ansible/modules/core/system/mount.py  
313c313
<     if 'fstab' in args and args['fstab'] != '/etc/fstab' and get_platform().lower() != 'sunos' :
---
>     if 'fstab' in args and args['fstab'] != '/etc/fstab':
ansible@nero:~$ 
```
