### ISSUE TITLE
"msg": "This command cannot be run due to the error: Access is denied."

### ISSUE THREAD

**Issue by svobozhin** [ansible/ansible#22141]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.2.1
```

##### OS / ENVIRONMENT

Run Ansible on RHEL, Windows Server 2012 R2 managing
##### SUMMARY

I need interactive run *.exe file as another user (for create local user profile).

packages.yml
```yaml
- name: Installation and configuration TortoiseSVN
  win_chocolatey:
    name: tortoisesvn
    params: '/chocoUser:"{{ choco_user }}" /chocoPassword:"{{ choco_user_password }}"'
  notify:
    - Test
  tags: TortoiseSVN
```

main.yml
```yaml
- name: Test
  run_another_user:
    command: "C:\\Program Files\\TortoiseSVN\\bin\\TortoiseProc.exe"
    username: "DOMAIN\\{{ bamboo_agent_user }}"
    password: "{{ bamboo_agent_user_password }}"
```

library\run_another_user.ps1
```yaml
#!powershell

# WANT_JSON
# POWERSHELL_COMMON

$params = Parse-Args $args;

$result = New-Object psobject @{
    changed = $false
};

$username = Get-Attr $params "username" -failifempty $true
$password = Get-Attr $params "password" -failifempty $true
$command = Get-Attr $params "command" -failifempty $true

$securePassword = ConvertTo-SecureString $password -AsPlainText -Force
$credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

Start-Process -FilePath $command -Credential $credential -LoadUserProfile -WorkingDirectory (Split-Path $command)


$result.changed = $true


Exit-Json $result 
```

In log - message: "msg": "This command cannot be run due to the error: Access is denied."
User/pass - right, in event log not events login.
