### ISSUE TITLE
file module bulk creation performance and usage improvement

### ISSUE THREAD

**Issue by tumbl3w33d** [ansible/ansible#22152]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
file module

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel dbb452100a) last updated 2017/02/16 12:20:32 (GMT +200)
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The file module does
* not accept lists as argument to path
* perform really poor when working with a loop

This forces users to fall back to shell to mitigate this performance impact (which can be considerable).

The issue was reported before [here](http://grokbase.com/t/gg/ansible-project/153x5dx2fb/create-multiple-directories-one-by-one-slow) and @bcoca mentioned there that this is something that could get optimized in the future. Now is the time. :)

##### STEPS TO REPRODUCE
I would like to write
```yaml
- name: create some folders
  file:
    state: directory
    path:
      - /some/path
      - /some/other/path
      - /imagine/a/long/list/of/paths/here
```
The current syntax even accepts that without throwing errors, but the folders don't get created. I would like this syntax to work (like it does for the apt and yum module, for example) and to perform nearly as well as the following hack
``` yaml
- name: create some folders
  shell: mkdir -p {{ (' ').join(variable_that_contains_folder_list) }}
  args:
    warn: no
```
To give an idea about the difference in performance in my setup:
* the loop example (see below) takes 8.89s
* in exactly the same setup the shell hack does the same thing in 1.5s

##### ACTUAL RESULTS
The syntax which I usually used so far
``` yaml
- name: create some folders
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - /some/path
    - /some/other/path
    - /imagine/a/long/list/of/paths/here
```
