### ISSUE TITLE
shell command runs despite file already existing and "creates" is being used

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#22170]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
shell

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### SUMMARY
Shell command runs even though sential file exists and "creates" is being used.

##### STEPS TO REPRODUCE
```yaml
- name: some task
  shell: runcommand && touch /var/service/configured
  args:
    creates: /var/service/configured
```

##### EXPECTED RESULTS
As the file exists, the command should not run.

##### ACTUAL RESULTS
The command runs (and fails as it cannot be run if already configured).

**Comment by jctanner** [comment]
### Testcase

```yaml
# site.yml 
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - copy:
        content: "0"
        dest: /tmp/file.txt

    - shell: echo "I AM RUNNING" > /tmp/file.txt
      args:
          creates: /tmp/file.txt
      register: shellshock

    - shell: cat /tmp/file.txt
      register: data

    - assert:
        that:
            - "not shellshock.changed"
            - "data.stdout == '0'"
```

### Results

version | rc
------ | ------
v1.9.0-0.1.rc1 |  0
v1.9.0-0.2.rc2 |  0
v1.9.0-1 |  0
v1.9.0-2 |  0
v1.9.0.1-1 |  0
v1.9.1-0.1.rc1 |  0
v1.9.1-0.2.rc2 |  0
v1.9.1-0.3.rc3 |  0
v1.9.1-0.4.rc4 |  0
v1.9.1-1 |  0
v1.9.2-0.1.rc1 |  0
v1.9.2-0.2.rc2 |  0
v1.9.2-1 |  0
v1.9.3-0.1.rc1 |  0
v1.9.3-0.2.rc2 |  0
v1.9.3-0.3.rc3 |  0
v1.9.3-1 |  0
v1.9.4-0.1.rc1 |  0
v1.9.4-0.2.rc2 |  0
v1.9.4-0.3.rc3 |  0
v1.9.4-1 |  0
v1.9.5-0.1.rc1 |  0
v1.9.5-1 |  0
v1.9.6-0.1.rc1 |  0
v1.9.6-1 |  0
v2.0.0-0.6.rc1 |  0
v2.0.0-0.7.rc2 |  0
v2.0.0-0.8.rc3 |  0
v2.0.0-0.9.rc4 |  0
v2.0.0.0-1 |  0
v2.0.0.1-1 |  0
v2.0.0.2-1 |  0
v2.0.1.0-0.1.rc1 |  0
v2.0.1.0-0.2.rc2 |  0
v2.0.1.0-1 |  0
v2.0.2.0-0.1.rc1 |  0
v2.0.2.0-0.2.rc2 |  0
v2.0.2.0-0.3.rc3 |  0
v2.0.2.0-0.4.rc4 |  0
v2.0.2.0-1 |  0
v2.1.0.0-0.1.rc1 |  0
v2.1.0.0-0.2.rc2 |  0
v2.1.0.0-0.3.rc3 |  0
v2.1.0.0-0.4.rc4 |  0
v2.1.0.0-1 |  0
v2.1.1.0-0.1.rc1 |  0
v2.1.1.0-0.2.rc2 |  0
v2.1.1.0-0.3.rc3 |  0
v2.1.1.0-0.4.rc4 |  0
v2.1.1.0-0.5.rc5 |  0
v2.1.1.0-1 |  0
v2.1.2.0-0.1.rc1 |  0
v2.1.2.0-0.2.rc2 |  0
v2.1.2.0-0.3.rc3 |  0
v2.1.2.0-0.4.rc4 |  0
v2.1.2.0-0.5.rc5 |  0
v2.1.2.0-1 |  0
v2.1.3.0-0.1.rc1 |  0
v2.1.3.0-0.2.rc2 |  0
v2.1.3.0-0.3.rc3 |  0
v2.1.3.0-1 |  0
v2.1.4.0-0.1.rc1 |  0
v2.1.4.0-0.2.rc2 |  0
v2.1.4.0-0.3.rc3 |  0
v2.1.4.0-1 |  0
v2.1.5.0-0.1.rc1 |  0
v2.1.5.0-0.2.rc2 |  0
v2.1.5.0-1 |  0
v2.1.6.0-0.1.rc1 |  0
v2.1.6.0-1 |  0
v2.2.0.0-0.1.rc1 |  0
v2.2.0.0-0.2.rc2 |  0
v2.2.0.0-0.3.rc3 |  0
v2.2.0.0-0.4.rc4 |  0
v2.2.0.0-1 |  0
v2.2.1.0-0.1.rc1 |  0
v2.2.1.0-0.2.rc2 |  0
v2.2.1.0-0.3.rc3 |  0
v2.2.1.0-0.4.rc4 |  0
v2.2.1.0-0.5.rc5 |  0
v2.2.1.0-1 |  0
v2.2.2.0-0.1.rc1 |  0
v2.2.2.0-0.2.rc2 |  0
v2.2.2.0-1 |  0
v2.2.3.0-0.1.rc1 |  0
v2.2.3.0-1 |  0
v2.3.0.0-0.1.rc1 |  0
v2.3.0.0-0.2.rc2 |  0
v2.3.0.0-0.3.rc3 |  0
v2.3.0.0-0.4.rc4 |  0
v2.3.0.0-0.5.rc5 |  0
v2.3.0.0-0.6.rc6 |  0
v2.3.0.0-1 |  0
v2.3.1.0-0.1.rc1 |  0
v2.3.1.0-0.2.rc2 |  0
v2.3.1.0-1 |  0
v2.3.2.0-0.1.rc1 |  0
v2.3.2.0-0.2.rc2 |  0
v2.3.2.0-0.3.rc3 |  0
v2.3.2.0-0.4.rc4 |  0
v2.3.2.0-0.5.rc5 |  0
v2.3.2.0-1 |  0
