### ISSUE TITLE
VM is always started as run once using ovirt_vms module

### ISSUE THREAD

**Issue by nijinashok** [ansible/ansible#22189]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ovirt_vms

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0
```

##### SUMMARY

Currently the VM is always started as "run once" . Even if we are only giving option as "state: running" , the RunVmOnceCommand is executed in the backend. There is no option to start the virtual machine without the "run once" logic.

##### STEPS TO REPRODUCE

```yaml
   - name: Start the VM
     ovirt_vms:
       auth: "{{ ovirt_auth }}"
       name: 'rhelh4.0'
       state: running

```

##### EXPECTED RESULTS

When we are not giving any option for initial run like cloud-init parameters, VM should start as normally instead of "run once" 
##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @machacekondra
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by machacekondra** [comment]
This was fixed by:

 https://github.com/ansible/ansible/pull/21246/commits/b9745dde239286b1f53ab1380cb46f7485651223

**Comment by machacekondra** [comment]
resolved_by_pr 21246

**Comment by martinbydefault** [comment]
@machacekondra I'm still having this problem with Ansible 2.4 and Red Hat Virtualization Manager Version: 4.1.4.2-0.1.el7.  
The output of `ansible --version` in MacOS were I'm running the playbook:
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/martin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```
But I also tried it from running it from a RHEL 7.4 with ansible 2.3:
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```
and I have the same problem.

The vms I'm creating are using a RHEL 7.3 template.  
To check if the template was the problem I also tried with others templates (CentOS 7 and others) but all them also starts as "run once".   
Also I tried to create the machine (without ansible) by hand using the RHEL 7.3 template and setting the cloud init parameters in the "Initial Run" (see [4.9.3.4.5. Using Cloud-Init to Prepare a Template](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Virtualization/3.4/pdf/User_Guide/Red_Hat_Enterprise_Virtualization-3.4-User_Guide-en-US.pdf#__WKANCHOR_58)) section and the machine started correctly as "normal" run.  

Logs in RHEV (`/var/log/ovirt-engine/engine.log`) also shows that `RunVmOnceCommand` is invoked when I use this module, instead of `RunVmCommand`.

If you need more details let me know.  

Also bug from issue https://github.com/ansible/ansible/issues/27382 seems to be present (using ansible 2.4), because if I create a new vm using `ovirt_vms` with `state` set to `present`, the machine is created **and started**.

**Comment by machacekondra** [comment]
@martinbydefault Can you please share the playbook you are using?
The VM should be started as run_once only in case you pass any of the following parameters:
 - host
 - kernel_params
 - initrd_path
 - kernel_path
 - sysprep
 - cloud_init
 - cloud_init_nics

> Also bug from issue #27382 seems to be present (using ansible 2.4), because if I create a new vm using ovirt_vms with state set to present, the machine is created and started.

Yes, if the VM does not exist the VM is created and started. If VM does exist we don't touch it's state, so if it exist and it is stopped, we don't run it.
If you want to create VM which is stopped, you should use stopped state.
Do you think this is wrong behavior? I can improve it.

**Comment by martinbydefault** [comment]
This is task from my playbook:  
```
- name: Deploy VMs and Apply Cloud Init
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    cluster: cluster1
    template: test_template
    type: server
    name: test
    memory: 2GiB
    cpu_cores:1
    state: present
    cloud_init:
      host_name: test_vm
      authorized_ssh_keys: <ssh public key>
      user_name: my_user
      dns_servers: 192.168.20.1
      dns_search: my.dns.search.domain
      nic_name: eth0
      nic_boot_protocol: dhcp
      nic_ip_address: 192.168.20.31
      nic_netmask: 255.255.255.0
      nic_gateway: 192.168.20.1
      nic_on_boot: true
      custom_script: |
        write_files:
          - content: |
              search my.dns.search.domain
              nameserver 192.168.20.1
            path: /etc/resolv.conf
            permissions: '0644'
        runcmd: 
          - systemctl restart NetworkManager
          - echo "GATEWAY=192.168.20.1" >> "/etc/sysconfig/network-scripts/ifcfg-eth0"
          - systemctl restart network
          - hostnamectl set-hostname test_vm"
```
Taking in account what you said, then the reason why is running as "run once" is because I'm using `cloud_init`, right?  

**My normal workflow**
I create a new virtual machine and assign at creation time all the parameters from the task above under `cloud_init`: nic name, protocol, ip, netmask and gateway, dns server and search domain, hostname, etc.  
If I do it by hand (without ansible), I normally would go to RHEV a select "New VM" and configure the cloud init parameters in the section "Initial Run" as explained and referenced in my previous comment. This makes the cloud init parameters permament, so if I create and start the machine it will get all these parameters and the if I reboot it, the parameters will be preserved.  
When you set cloud init parameters in "run once" mode, if you reboot the machine the cloud init parameters are lost.  
This is what is happening when I run my playbook.  


*To sum up*:   
right now I think I don't have a way to create a machine and set permanent cloud init parameters, but manually is possible.  
Maybe the solution could be adding another parameter to toggle between "run"/"run once"?
Or have some way to be able to provide permanent `cloud_init` parameters to the machine.  

> If you want to create VM which is stopped, you should use stopped state.
Do you think this is wrong behavior? I can improve it.

I think that if the VM doesn't exist yet, then the `present` state shouldn't imply also started.  
My arguments are the same that @rgroten said (https://github.com/ansible/ansible/issues/27382#issuecomment-318480050).   

Ignore the `custom_script` : `write_files` and `runcmd`. These are there because the DNS settings weren't being applied and neither the gateway of the interface, for some reason (I think that's a bug from cloud unit for redhat).
