### ISSUE TITLE
netconf-config.py should provide control for deployment strategy

### ISSUE THREAD

**Issue by wisotzky** [ansible/ansible#22192]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lib/ansible/modules/network/netconf/netconf_config.py

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY
The current implementation of netconf-config.py is enforcing lock/unlock of the datastore, discard-changes before edit-config and commit after edit-config (if there are changes). Technically there is nothing to say against this principle. But the current approach might cause performance issues, if you call the module 100 times to create for example 100 VPN services. Reason is, that from netconf server point of view a "commit" is relatively compute intense. For example I have seen cases with large configs on Juniper MX, where a commit was taking several minutes.

So for performance optimization it makes a lot of sense to call the module 100 times without commit and just do single commit after all the changes - which potentially means to break down the functionality into two modules: one to apply changes and another one to commit changes. 

An important aspect for this optimization is, that ncclient will open/close the NETCONF-over-SSH session each time the module is called. Using explicit lock()/unlock() NETCONF servers typically will release the lock if the NETCONF session is closed and changes in candidate are automatically discarded. Therefore it makes absolutely sense, not just to control the "commit" - but to make the discard-changes and lock/unlock options as well.

**Comment by ansibot** [comment]
cc @lpenz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lpenz** [comment]
Hi there!

The module, in its current state, is indeed not appropriate for sending several XML files to the same device. The idea here is that you would send a single XML to each device, or (in the future) a parameterized XML.

I understand what you are saying about the lock/unlock and it makes sense - but I'm not so sure that servers discard changes to the candidate when the session is closed. I'd have to test that.

BTW, I have a separate repository with the OpenYuma client that I used for testing. If you know of other free servers let me know so that we can it them there and test against multiple implementations.
https://github.com/lpenz/ansible-testing-netconf

**Comment by wisotzky** [comment]
Limiting yourself to free servers sounds like quite a limitation to me. Having the flexibility to control lock/unlock makes quite some sense for me. For example in Nokia SROS today you can only lock either <running> or <candidate> while the other is implicitly locked. SDN Controllers like ODL today always try to lock both datastores - which causes errors in this specific scenario.
Same is basically true about the explicit lock on <candidate>. As the lock belongs to a specific netconf session (not the user) - at least in the Nokia SROS case the datastore will be discarded if the netconf session is going down. Sounds like reasonable implementation for me.

**Comment by wisotzky** [comment]
Btw, could you give some insight about what XML templating technique you would see - and what other Ansible modules are going in the same direction?

Unclear if single XML is always a good answer, as in essence this means that you XML templates become much more complex. With short XML files and many commits you might cause performance issues... So alternative might be using frameworks like NAPALM which provide more granular access to datastores - but with NAPALM there is currently no blueprint NETCONF implementation. I am currently working to build my first NETCONF driver for NAPALM - but it will still take a while to complete this work.

**Comment by lpenz** [comment]
The free servers I use for testing are in the context of continuous integration, where they are executed on travis. There might be legal issues with non-free servers; if there aren't, we can use them.

I agree with the locking. The candidate datastore, however, can be shared among sessions, as documented here: https://tools.ietf.org/html/rfc6241#section-8.3

Jinja2 is ansible's templating engine, and it is integrated with other features. The documentation is here: https://docs.ansible.com/ansible-container/container_yml/template.html
It is used extensively by other network modules, for example: http://docs.ansible.com/ansible/eos_config_module.html
You can, for instance, have loops inside the template, and render them with host information (facts).

I had not heard of NAPALM before, I'll take a look into it. Looks like there's already an external ansible module for it.

**Comment by wisotzky** [comment]
You are absolutely right. Usage of commercial NETCONF servers raises legal/license questions to be sorted out. But I think, you can leave it to the community to check against their use-cases and server specific behaviour - as I am doing for Nokia SROS.

In general there are quite some open NC servers available, you might integrate into your CI. Tail-f confd has a non-commercial version and from open-source point of view you should have a look into netopeer and opendaylight.

From commercial NETCONF stacks, it might be relevant to have at least validation against Juniper, Cisco and Nokia.

Shared access to candidate raises lot of questions, as you don't want by accident commit changes made by others. Nokia SROS is dealing with implicit locks as soon a session is adding changes.

Need still to figure out, how session management works with NAPALM/Ansible. In theory NAPALM is able to keep session open and to commit as needed. But doubt this is fully supported with Ansible and likely you end up with Salt for this.

The free servers I use for testing are in the context of continuous integration, where they are executed on travis. There might be legal issues with non-free servers; if there aren't, we can use them.

I agree with the locking. The candidate datastore, however, can be shared among sessions, as documented here: https://tools.ietf.org/html/rfc6241#section-8.3

Jinja2 is ansible's templating engine, and it is integrated with other features. The documentation is here: https://docs.ansible.com/ansible-container/container_yml/template.html
It is used extensively by other network modules, for example: http://docs.ansible.com/ansible/eos_config_module.html
You can, for instance, have loops inside the template, and render them with host information (facts).

I had not heard of NAPALM before, I'll take a look into it. Looks like there's already an external ansible module for it.

**Comment by wisotzky** [comment]
Hi

I’ve checked about Nokia SROS routers. In principle we have provided RedHat with the latest VSR 15.0.R1 image and license keys to be used for Ansible integration. So it could be used in CI environments as needed.
If you need to know the contacts in the Ansible community who have the software+licenses, you might get in contact with greg.hankins@nokia.com<mailto:greg.hankins@nokia.com> – or he will be able to provide you with licenses and loads as well.

Sven

**Comment by ansibot** [comment]
cc @userlerueda
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by userlerueda** [comment]
In my opinion with current implementation it is not an easy fix, in addition to that any implementation that does not treat a task as a transaction (i.e. locks, sends config and unlocks) could lead to potential issues. What I see doable is for the XML not be text within the task but for it to come from a file (or template as @lpenz mentions) and the files to be a list that could potentially provide for all the XML files under a specific directory to be sent one by one without closing the transaction.

**Comment by lpenz** [comment]
I think the template file implementation is worth it, and is potentially simple, as the infrastructure is already there.

**Comment by wisotzky** [comment]
I do agree, but it might require to build long/complex templates which contain everything, you want to submit in a single transaction. Would you suggest jinja2 to be used as template language - or more an XSLT approach?

**Comment by ansibot** [comment]
cc @ganeshrn
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wisotzky** [comment]
@ganeshrn, the answer to the original request might be using persistent connections with Connection Plugins as introduced from Ansible 2.3. In consequence this would mean to provide elementary Ansible modules to lock, edit-config, commit and unlock using NETCONF.
Still I am confused about the usage of Connection Plugins (invocation, vendor independence) - so need to have more info about it, before I can contribute those new modules.

**Comment by privateip** [comment]
@wisotzky yes the right answer here is to use the persistence connections to handle this; however, i have to question if providing separate modules to handle what are essentially low level API calls is the right approach here.   Netconf, imho, is an API not an implementation and Ansible modules should be built on top of APis not expose them where possible.

**Comment by wisotzky** [comment]
@privateip, there is no simple answer for that... Typically I prefer to keep configuration templates simple/clean for readability and re-usability. Also there are use-cases where you want to read state information and apply changes based on the output of the read-out. In all of these cases persistence potentially lock/unlock is the only answer.

The other important issue is about the performance of a netconf commit or "copy-config running > startup" - which could take minutes. In those cases, you might want to combine more elementary task to one big transactions.

Unclear what the conclusion would be. Potentially we might come to the conclusion, that modules like netconf_config needs to be much more flexible to support read-out before executing multiple XML templates in a single run. In this case, the module still would keep the ownership of the transaction.

**Comment by privateip** [comment]
@wisotzky completely in agreement on the issues around lock/unlock and edit/commit/discard.  My point is that we should be striving to build resource based modules not wrappers around xml documents.  The module should expose a set of configurable resources that are based on a set of arguments.  Those resources + arguments would then map to one (or more) netconf calls in the module code.   Instead of building xml templates, you can implement modules to do the heavy lifting.

That said, I'm fully aware of the fact that it will take time to build the vast number of resource modules necessary to cover a given set of use cases and therefore having a lower level module to push raw xml documents makes sense to cover those cases.  

We should, however, expand the capabilities of the current `netconf_config` module to provide the implementer more control of the actions.  I could easily see a playbook that does something like the following:

```
- name: start transaction
  netconf_config:
    lock: yes

- name: do some config
  netconf_config:
    xml: "{{ lookup('file', 'xmlconfig.xml') }}"

- name: read some state
  netconf_config:
    xml: "{{ lookup('file', 'xmlread.xml') }}" 
  register: some_var

- name: do some more config
  netconf_config:
    xml: "{{ lookup('file', 'xmlconfig.xml') }}"

- name: do some more config
  netconf_config:  
    xml: "{{ lookup('file', 'xmlconfig.xml') }}"

- name: read some state
  netconf_config:
    xml: "{{ lookup('file', 'xmlread.xml') }}" 
  register: some_other_var

- name: discard the config with conditional
  netconf_config:
    discard: yes
    unlock: yes
  when: some_other_var is False

- name: commit the config with conditional
  netconf_config:
    commit: yes
    unlock: yes
  when: some_other_var is True
```

In the above example, `netconf_config` isn't just reflective of the action but starts to become more representative of managing the config.  In fact, it was just this type of implementation that persistent connections was designed to handle.  

The longer term goal should, imho, be to start to infuse more declarative based configuration modules and reduce the dependency on templates.  So an updated playbook would look more like this

```
- name: start transaction
  netconf_config:
    lock: yes

- name: do global bgp config
  bgp:
    as: 65000
    router_id: 1.1.1.1
    enabled: yes

- name: do bgp peer config
  bgp_peers:
    peer_group: ebgp_peers
    neighbors:
      - 1.1.1.1
      - 2.2.2.2
    next_hop_self: yes

- name: do some more xml config (since no resource module exists yet)
  netconf_config:  
    xml: "{{ lookup('file', 'xmlconfig.xml') }}"

- name: read some state
  netconf_config:
    xml: "{{ lookup('file', 'xmlread.xml') }}" 
  register: some_other_var

- name: discard the config with conditional
  netconf_config:
    discard: yes
    unlock: yes
  when: some_other_var is False

- name: commit the config with conditional
  netconf_config:
    commit: yes
    unlock: yes
  when: some_other_var is True
```
