### ISSUE TITLE
Remove warning "argument authorize has been deprecated"

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#22193]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_banner

##### ANSIBLE VERSION
```
029ccf9aa0cd490224bfcf403ed94bc397e3af63
```

##### SUMMARY
In 2.3 using `authorise: yes` is the correct way to go into privileged mode on `eos` and `ios`.
Though we throw a warning that's it's a deprecated option, most likely as it's its in 

##### STEPS TO REPRODUCE
```yaml
- name: setup - remove motd
  eos_banner:
    banner: motd
    state: absent
    authorize: yes
```

##### ACTUAL RESULTS
```
 [WARNING]: argument authorize has been deprecated and will be removed in a future version

```
