### ISSUE TITLE
eos_banner not idempotent

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#22194]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_banner

##### ANSIBLE VERSION
```
029ccf9aa0cd490224bfcf403ed94bc397e3af63
```

##### STEPS TO REPRODUCE
```yaml
- name: Set login
  eos_banner:
    banner: login
    text: |
      this is my login banner
      that has a multiline
      string
    state: present
    authorize: yes 
  register: result

- debug:
    msg: "{{ result }}"

- assert:
    that:
      - "result.changed == true"
      - "'that has a multiline' in result.commands" # does this break due to "contains?"
      # Ensure sessions contains epoc. Will fail after 18th May 2033
      - "'ansible_1' in result.session_name"

- name: Set login again (idempotent)
  eos_banner:
    banner: login
    text: |
      this is my login banner
      that has a multiline
      string
    state: present
    authorize: yes 
  register: result

```

##### EXPECTED RESULTS
2nd run shouldn't report changed
##### ACTUAL RESULTS
```yaml
 changed: [veos01] => {
    "changed": true, 
    "commands": [
        "banner login", 
        "this is my login banner", 
        "that has a multiline", 
        "string", 
        "EOF"
    ], 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": true, 
            "banner": "login", 
            "host": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "text": "this is my login banner\nthat has a multiline\nstring\n", 
            "timeout": null, 
            "transport": null, 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }, 
    "session_name": "ansible_1488455488"
}

TASK [eos_banner : debug] ************************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible-workspace-2/test/integration/targets/eos_banner/tests/cli/eos_banner_basic.yaml:27
ok: [veos01] => {
    "changed": false, 
    "msg": {
        "changed": true, 
        "commands": [
            "banner login", 
            "this is my login banner", 
            "that has a multiline", 
            "string", 
            "EOF"
        ], 
        "session_name": "ansible_1488455488", 
        "warnings": [
            "argument authorize has been deprecated and will be removed in a future version"
        ]
    }
}

TASK [eos_banner : assert] ***********************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible-workspace-2/test/integration/targets/eos_banner/tests/cli/eos_banner_basic.yaml:30
ok: [veos01] => {
    "changed": false, 
    "msg": "All assertions passed"
}

TASK [eos_banner : Set login again (idempotent)] *************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/ansible-workspace-2/test/integration/targets/eos_banner/tests/cli/eos_banner_basic.yaml:37
<veos01> connection transport is cli
<veos01> socket_path: /home/johnb/.ansible/pc/ca5960d27a
Using module file /home/johnb/git/ansible-inc/ansible-workspace-2/lib/ansible/modules/network/eos/eos_banner.py
<veos01> ESTABLISH LOCAL CONNECTION FOR USER: johnb
<veos01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<veos01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/johnb/.ansible/tmp/ansible-tmp-1488455491.69-116354442763630 `" && echo ansible-tmp-1488455491.69-116354442763630="` echo /home/johnb/.ansible/tmp/ansible-tmp-1488455491.69-116354442763630 `" ) && sleep 0'
<veos01> PUT /tmp/tmpyLoa44 TO /home/johnb/.ansible/tmp/ansible-tmp-1488455491.69-116354442763630/eos_banner.py
<veos01> EXEC /bin/sh -c 'chmod u+x /home/johnb/.ansible/tmp/ansible-tmp-1488455491.69-116354442763630/ /home/johnb/.ansible/tmp/ansible-tmp-1488455491.69-116354442763630/eos_banner.py && sleep 0'
<veos01> EXEC /bin/sh -c 'python /home/johnb/.ansible/tmp/ansible-tmp-1488455491.69-116354442763630/eos_banner.py; rm -rf "/home/johnb/.ansible/tmp/ansible-tmp-1488455491.69-116354442763630/" > /dev/null 2>&1 && sleep 0'
changed: [veos01] => {
    "changed": true, 
    "commands": [
        "banner login", 
        "this is my login banner", 
        "that has a multiline", 
        "string", 
        "EOF"
    ], 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": true, 
            "banner": "login", 
            "host": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "text": "this is my login banner\nthat has a multiline\nstring\n", 
            "timeout": null, 
            "transport": null, 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }, 
    "session_name": "ansible_1488455492"
}


```
