### ISSUE TITLE
Azure NSG rule purge does not work.

### ISSUE THREAD

**Issue by bearrito** [ansible/ansible#22197]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 azure_rm_securitygroup

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/barrett/Git/ansible-dock-robot/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT
Ubuntu 14.04.

##### SUMMARY
Rule purge does not work

##### STEPS TO REPRODUCE
Run the azure  azure_rm_securitygroup with purge set to true, go to the azure portal, witness that the rules are not purged.

##### EXPECTED RESULTS
My existing rules to be purged

##### ACTUAL RESULTS
The rules are not purged.

**Comment by trstringer** [comment]
What exactly are you seeing? I just tried this out with a sample playbook (see below), and the rule that was first created was purged on the second task. The end result is a single rule `allow-http`, and `allow-ssh` rule was purged.

Are you getting an error? Could you share a repro playbook?

```yml
---
- name: test out Azure NSG
  hosts: localhost

  tasks:
    - name: create nsg
      azure_rm_securitygroup:
        resource_group: ansiblensg-rg
        name: mynsg
        rules:
          - name: allow-ssh
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 110
            direction: Inbound

    - name: purge rule
      azure_rm_securitygroup:
        resource_group: ansiblensg-rg
        name: mynsg
        purge_rules: true
        rules:
          - name: allow-http
            protocol: Tcp
            destination_port_range: 80
            access: Allow
            priority: 100
            direction: Inbound
```

**Comment by trstringer** [comment]
Also, what version of the azure python sdk are you using? `pip show azure`

**Comment by bearrito** [comment]
```
(ansible)➜   git:(master) pip show azure
---
Metadata-Version: 2.0
Name: azure
Version: 2.0.0rc5
Summary: Microsoft Azure Client Libraries for Python
Home-page: https://github.com/Azure/azure-sdk-for-python
Author: Microsoft Corporation
Author-email: ptvshelp@microsoft.com
License: Apache License 2.0
```

**Comment by trstringer** [comment]
@bearrito do you get an error when you run your original playbook (if yes, then please copy/paste that error here)? Or does it succeed execution, but the rule doesn't purge when you check the portal?

**Comment by bearrito** [comment]
Here is a more thorough explanation.

I went to the portal and altered one of our rules by hand. I change a subnet from 10.3.5.x to 10.3.6.x.

10.3.6.x does not exist in this vnet.

When I run the play I get

```
 {
                "access": "Allow", 
                "description": null, 
                "destination_address_prefix": "*", 
                "destination_port_range": "5432", 
                "direction": "Inbound", 
                "etag": """, 
                "id": scrubber/securityRules/TCP-backend-5432", 
                "name": "TCP-backend-5432", 
                "priority": 520, 
                "protocol": "Tcp", 
                "provisioning_state": "Succeeded", 
                "source_address_prefix": "10.3.6.0/24", 
                "source_port_range": "*"
            }
```

```
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=15   changed=0    unreachable=0    failed=0   
```


Again 10.3.6.x or 10.3.6.0/24 doesn't exist anywhere in a our playbook. Either a var or fact or anything. It is only coming from the portal.

**Comment by trstringer** [comment]
Can you provide the playbook? I can try to repro this behavior.

**Comment by bearrito** [comment]
I'm not sure I can provide the whole playbook. This is obviously related to our NSG and the infosec team wouldn't be thrilled if I handed out reams of security config. 

What is the minimal amount you need?

Here is the slightly scrubbed version

```
- name: Create data nsg 
  azure_rm_securitygroup:
    resource_group: "{{ network_rg }}"
    name: "{{ data_nsg_name }}"
    purge_rules: yes
    rules:
      - name: "TCP-{{ vnet_backend_name }}-{{ postgres_port }}"
        protocol: Tcp
        destination_port_range: "{{ postgres_port }}"
        access: Allow
        priority: 520
        direction: Inbound
        source_address_prefix: "{{ vnet_backend }}"
      - name: DisallowVnetInbound
        access: Deny
        priority: 4096
        direction: Inbound
        source_address_prefix: "VirtualNetwork"
  tags: [azure_nsg, azure_data_nsg]
```
