### ISSUE TITLE
remote_path is not respected when become is true for script module

### ISSUE THREAD

**Issue by gjelu** [ansible/ansible#22203]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
sccript module

##### ANSIBLE VERSION
ansible 2.1.2.0
  config file = /home/lsc8100/.ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
```ini
[defaults]
remote_tmp = /var/opt/app/.ansible/tmp/
host_key_checking = False
timeout = 30
retry_files_enabled = False
retry_files_save_path = ~/.ansible-retry
hash_behaviour=merge
```
##### OS / ENVIRONMENT
Ansible server: RedHat 6.8
target host: RedHat 7.3 but /tmp is mounted with noexec option

##### SUMMARY
when a playbook is started as become:true and become_user, a script from a role is copied to /tmp/ instead of the remote_tmp and executed from this location. 

As the /tmp is mounted as noexec, we cannot execute the script. 

##### STEPS TO REPRODUCE
```yaml
playbook:
- hosts: all
  become: true
  become_user: jenkins
  gather_facts: no
  roles:
   - role: myrole
```
the role 'myrole' has the following myrole/tasks/main.yaml
```yaml
 - name: execute test
   script: test.sh
   register: cmdtest
```
The dummy script test.sh is located in 'myrole/files'

##### EXPECTED RESULTS

The script test should be copied in the remote_tmp location being, /var/opt/app/.ansible/tmp/
and should be executed from here. 

##### ACTUAL RESULTS

The script is copied in /tmp. 
```
fatal: [inetyiaplv003]: FAILED! => {"changed": true, "failed": true, "rc": 126, "stderr": "", "stdout": "/bin/sh: /tmp/ansible-tmp-1488470170.18-148393376669627/test.sh: Permission denied\r\n", "stdout_lines": ["/bin/sh: /tmp/ansible-tmp-1488470170.18-148393376669627/test.sh: Permission denied"]}
```
When we remove the become and become_user from the playbook, the playbook is executed fine.
