### ISSUE TITLE
missing host in a task and duplicated on the next in the same playbook/role

### ISSUE THREAD

**Issue by jsecchiero** [ansible/ansible#22220]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
task

##### ANSIBLE VERSION
2.2.1.0

##### CONFIGURATION
```ini
[defaults]
host_key_checking       = False
host_key_checking       = False
record_host_keys        = False
remote_user		        = "ubuntu"
timeout			        = 600
nocows			        = 1
forks                   = 25
[privilege_escalation]
become                  = True
become_method           = sudo
become_user             = root
become_ask_pass         = False
[ssh_connection]
pipelining              = True
```
##### OS / ENVIRONMENT
ubuntu 16.04

##### SUMMARY
missing host in a task and duplicated on the next in the same playbook/role

##### STEPS TO REPRODUCE
```yaml
- name: Check if one app have failed           <- missing host
  set_fact: one_fail=true
  delegate_to: "{{ groups.BASTION[0] }}"
  delegate_facts: true
  when: item.rc != 0
  with_items: "{{ custom_script.results | default([]) }}"

- name: Delete all apps if one script fails     <- dupliated host
  file: path={{ destpath }}/{{ item.item.stdout.split('@')[0] }}/releases/{{ item.item.stdout }} state=absent
  when: hostvars[groups.BASTION[0]].one_fail | default([]) and
        exit_fast
  with_items: "{{ custom_script.results | default([]) }}"
```
##### EXPECTED RESULTS
no missing or duplicated hosts

##### ACTUAL RESULTS
```console
TASK [deployer : Check if one app have failed] *********************************
ok: [172.16.16.128 -> 172.16.17.1] => (item={u'_ansible_parsed': True, u'cmd': u'sudo -E ...
skipping: [172.16.16.135] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout': ...
skipping: [172.16.16.138] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout': ...
skipping: [172.16.16.139] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout': ...
skipping: [172.16.16.102] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout': ...
skipping: [172.16.16.140] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout': ...
skipping: [172.16.16.149] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout': ...
skipping: [172.16.16.150] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout': ...
skipping: [172.16.16.146] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout': ...

TASK [deployer : Delete all apps if one script fails] **************************
skipping: [172.16.16.148] => (item={u'_ansible_parsed': True, u'changed': True, u'std  <- DUPLICATED
skipping: [172.16.16.145] => (item={u'_ansible_parsed': True, u'changed': True, u'std  <- DUPLICATED
skipping: [172.16.16.128] => (item={u'_ansible_parsed': True, u'cmd': u'sudo -E -         ...
skipping: [172.16.16.139] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout' ...
skipping: [172.16.16.138] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout' ...
skipping: [172.16.16.135] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout' ...
skipping: [172.16.16.140] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout' ...
skipping: [172.16.16.102] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout' ...
skipping: [172.16.16.145] => (item={u'_ansible_parsed': True, u'changed': True, u'std <- DUPLICATED
skipping: [172.16.16.146] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout' ...
skipping: [172.16.16.149] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout' ...
skipping: [172.16.16.150] => (item={u'_ansible_parsed': True, u'changed': True, u'stdout' ...
skipping: [172.16.16.148] => (item={u'_ansible_parsed': True, u'changed': True, u'std  <- DUPLICATED
```
