### ISSUE TITLE
vyos_config fails with timeout with big configuration

### ISSUE THREAD

**Issue by davidsummers** [ansible/ansible#22233]
- Bug Report

##### COMPONENT NAME

vyos_config

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

Running from: Mac OS X 10.11.6
Managing: vyos 1.1.7

##### SUMMARY

I'm trying to load a whole configuration into a vyos 1.1.7 router with ansible 2.2.1.0 and the 'vyos_config' module.

My current list of commands is about 12.8 K characters and about 201 commands and this is really just the start, it will probably get bigger.

Up until some number of commands it works.

At some number of commands I get:

TASK [Configure VyOS Router Commands] **************************************
fatal: [testserver]: FAILED! => {"changed": false, "commands": "commit comment "configured by vyos_config"", "failed": true, "msg": "timeout trying to send command: commit comment "configured by vyos_config"\r"}

*** I tried adjusting the timeout in the vyos_config parameter but that didn't change anything.

When I log in remotely and check, it seems it has dropped at least some of the commands sent and not loaded all of them.

I then reload from a known good configuration to restore it to known configuration, but without being able to accomplish the goal of changing the configuration remotely.

What are the limits on the number of commands that can be sent?

I've tried using ansible_command to upload a file and load it and the error message says to use vyos_config.

I've also tried to break up the commands into groups and that errored out in the same way.

Is there either some work-around or some other way to configure a whole box with not just a few commands?

##### STEPS TO REPRODUCE

```yaml
# Note: We need multiple plays here because each play has a different
# connection method.

- name: Setup VPN files
  hosts: all
  gather_facts: no
  tasks:
    - name: Copy VPN1 <-> VPN2 VPN Key file
      template:
        src:  vpn1-vpn2.key
        dest: /config/auth/vpn1-vpn2.key
        mode: u=rw,g=rw,o=r

- name: Deploy VPN2 VyOS Router
  hosts: all
  gather_facts: no
  connection: local
  vars:
    cli:
      host: 10.0.2.138
      port: 23
      username: admin
      transport: cli
  tasks:
    - name: Configure VPN2 VyOS Router Commands
      vyos_config:
        provider: "{{cli}}"
        timeout: 120
        lines:
          - delete system ntp server '0.pool.ntp.org'
          - delete system ntp server '1.pool.ntp.org'
          - delete system ntp server '2.pool.ntp.org'
          - set firewall all-ping 'enable'
          - set firewall broadcast-ping 'disable'
          - set firewall config-trap 'disable'
          - set firewall group port-group OPENVPN-PORTS port '1195'
          - set firewall group port-group OPENVPN-PORTS port '1196'
          - set firewall ip-src-route 'disable'
          - set firewall ipv6-name allow-all6 default-action 'accept'
          - set firewall ipv6-name internet-local6 default-action 'drop'
          - set firewall ipv6-name internet-local6 description 'Internet to local (router).'
          - set firewall ipv6-name internet-local6 rule 1 action 'accept'
          - set firewall ipv6-name internet-local6 rule 1 state established 'enable'
          - set firewall ipv6-name internet-local6 rule 1 state related 'enable'
          - set firewall ipv6-name internet-local6 rule 10 action 'accept'
          - set firewall ipv6-name internet-local6 rule 10 destination port '23'
          - set firewall ipv6-name internet-local6 rule 10 protocol 'tcp'
          - set firewall ipv6-name internet-local6 rule 10 state new 'enable'
          - set firewall ipv6-name internet-local6 rule 2 action 'drop'
          - set firewall ipv6-name internet-local6 rule 2 state invalid 'enable'
          - set firewall ipv6-name internet-local6 rule 30 action 'accept'
          - set firewall ipv6-name to_jec6 'enable-default-log'
          - set firewall ipv6-name to_jec6 description 'Allow IPv6 traffic to JEC network.'
          - set firewall ipv6-name to_jec6 rule 1 action 'accept'
          - set firewall ipv6-name to_jec6 rule 1 description 'Allow all established and related traffic.'
          - set firewall ipv6-name to_jec6 rule 1 protocol 'all'
          - set firewall ipv6-name to_jec6 rule 1 state established 'enable'
          - set firewall ipv6-name to_jec6 rule 1 state related 'enable'
          - set firewall ipv6-name to_jec6 rule 10 action 'accept'
          - set firewall ipv6-name to_jec6 rule 10 description 'Allow selected TCP traffic.'
          - set firewall ipv6-name to_jec6 rule 10 destination port 'smtp,http,https,imaps,8025,9090,9091,5222,5223,5269'
          - set firewall ipv6-name to_jec6 rule 10 protocol 'tcp'
          - set firewall ipv6-name to_jec6 rule 10 state new 'enable'
          - set firewall ipv6-name to_jec6 rule 11 action 'accept'
          - set firewall ipv6-name to_jec6 rule 11 description 'Allow email port
 465'
          - set firewall ipv6-name to_jec6 rule 11 destination port '465'
          - set firewall ipv6-name to_jec6 rule 11 protocol 'tcp'
          - set firewall ipv6-name to_jec6 rule 11 state new 'enable'
          - set firewall ipv6-name to_jec6 rule 12 action 'accept'
          - set firewall ipv6-name to_jec6 rule 12 description 'Port 587 - Mail submission'
          - set firewall ipv6-name to_jec6 rule 12 destination port '587'
          - set firewall ipv6-name to_jec6 rule 12 protocol 'tcp'
          - set firewall ipv6-name to_jec6 rule 12 state new 'enable'
          - set firewall ipv6-name to_jec6 rule 20 'icmpv6'
          - set firewall ipv6-name to_jec6 rule 20 action 'accept'
          - set firewall ipv6-name to_jec6 rule 20 description 'Allow ICMP/ping.'
          - set firewall ipv6-name to_jec6 rule 20 protocol 'icmpv6'
          - set firewall ipv6-name to_jec6 rule 30 action 'accept'
          - set firewall ipv6-name to_jec6 rule 30 description 'Allow Traceroute.'
          - set firewall ipv6-name to_jec6 rule 30 destination port '33434-33534'
          - set firewall ipv6-name to_jec6 rule 30 protocol 'udp'
          - set firewall ipv6-name to_jec6 rule 40 action 'accept'
          - set firewall ipv6-name to_jec6 rule 40 description 'Allow SYSLOG from router.'
          - set firewall ipv6-name to_jec6 rule 40 destination address '2001:470:5678::22'
          - set firewall ipv6-name to_jec6 rule 40 destination port '514'
          - set firewall ipv6-name to_jec6 rule 40 protocol 'udp'
          - set firewall ipv6-name to_jec6 rule 40 source address '2001:470:1234:64::0001:0203'
          - set firewall ipv6-name to_jec6 rule 8 action 'accept'
          - set firewall ipv6-name to_jec6 rule 8 description 'Allow SSH.'
          - set firewall ipv6-name to_jec6 rule 8 destination port '22'
          - set firewall ipv6-name to_jec6 rule 8 protocol 'tcp'
          - set firewall ipv6-name to_jec6 rule 8 state new 'enable'
          - set firewall ipv6-name to_jec6 rule 9 action 'accept'
          - set firewall ipv6-name to_jec6 rule 9 destination port 'domain'
          - set firewall ipv6-name to_jec6 rule 9 protocol 'tcp_udp'
          - set firewall ipv6-src-route 'disable'
          - set firewall log-martians 'enable'
          - set firewall name allow-all4 default-action 'accept'
          - set firewall name internet-local4 default-action 'drop'
          - set firewall name internet-local4 description 'Internet to local (r outer).'
          - set firewall name internet-local4 rule 1 action 'accept'
          - set firewall name internet-local4 rule 1 state established 'enable'
          - set firewall name internet-local4 rule 1 state related 'enable'
          - set firewall name internet-local4 rule 10 action 'accept'
          - set firewall name internet-local4 rule 10 destination port '23'
          - set firewall name internet-local4 rule 10 protocol 'tcp'
          - set firewall name internet-local4 rule 10 state new 'enable'
          - set firewall name internet-local4 rule 2 action 'drop'
          - set firewall name internet-local4 rule 2 state invalid 'enable'
          - set firewall name internet-local4 rule 20 'source'
          - set firewall name internet-local4 rule 20 action 'accept'
          - set firewall name internet-local4 rule 20 description 'Allow OpenVpn tunnels.'
          - set firewall name internet-local4 rule 20 destination group port-group 'OPENVPN-PORTS'
          - set firewall name internet-local4 rule 20 protocol 'udp'
          - set firewall name internet-local4 rule 30 action 'accept'
          - set firewall name internet-local4 rule 30 description 'Allow traceroute.'
          - set firewall name internet-local4 rule 30 destination port '33434-33534'
          - set firewall name internet-local4 rule 4 action 'accept'
          - set firewall name internet-local4 rule 4 protocol 'icmp'
          - set firewall name internet-local4 rule 7 action 'accept'
          - set firewall name internet-local4 rule 7 description 'Allow protocol IPv6 tunnels protocol 41.'
          - set firewall ipv6-name internet-local6 rule 30 description 'Allow traceroute.'
          - set firewall ipv6-name internet-local6 rule 30 destination port '33434-33534'
          - set firewall ipv6-name internet-local6 rule 30 protocol 'udp'
          - set firewall ipv6-name internet-local6 rule 4 'icmpv6'
          - set firewall ipv6-name internet-local6 rule 4 action 'accept'
          - set firewall ipv6-name internet-local6 rule 4 protocol 'icmpv6'
          - set firewall ipv6-name to_internet6 default-action 'reject'
          - set firewall ipv6-name to_internet6 description 'Block anything other than our addresses.'
          - set firewall ipv6-name to_internet6 rule 100 action 'accept'
          - set firewall ipv6-name to_internet6 rule 100 source address '2001:470:9012:7cb::/64'
          - set firewall ipv6-name to_internet6 rule 200 action 'accept'
          - set firewall ipv6-name to_internet6 rule 200 source address '2001:470:5678::/48'
          - set firewall ipv6-name to_internet6 rule 300 action 'accept'
          - set firewall ipv6-name to_internet6 rule 300 destination address '2001:470:5678::/48'
          - set firewall ipv6-name to_internet6 rule 300 source address '2001:470:5678::/48'
          - set firewall ipv6-name to_jec6 'enable-default-log'
          - set firewall ipv6-name to_jec6 description 'Allow IPv6 traffic to JEC network.'
          - set firewall ipv6-name to_jec6 rule 1 action 'accept'
          - set firewall ipv6-name to_jec6 rule 1 description 'Allow all established and related traffic.'
          - set firewall ipv6-name to_jec6 rule 1 protocol 'all'
          - set firewall ipv6-name to_jec6 rule 1 state established 'enable'
          - set firewall ipv6-name to_jec6 rule 1 state related 'enable'
          - set firewall ipv6-name to_jec6 rule 10 action 'accept'
          - set firewall ipv6-name to_jec6 rule 10 description 'Allow selected TCP traffic.'
          - set firewall ipv6-name to_jec6 rule 10 destination port 'smtp,http,https,imaps,8025,9090,9091,5222,5223,5269'
          - set firewall ipv6-name to_jec6 rule 10 protocol 'tcp'
          - set firewall ipv6-name to_jec6 rule 10 state new 'enable'
          - set firewall ipv6-name to_jec6 rule 11 action 'accept'
          - set firewall ipv6-name to_jec6 rule 11 description 'Allow email port
 465'
          - set firewall ipv6-name to_jec6 rule 11 destination port '465'
          - set firewall ipv6-name to_jec6 rule 11 protocol 'tcp'
          - set firewall ipv6-name to_jec6 rule 11 state new 'enable'
          - set firewall ipv6-name to_jec6 rule 12 action 'accept'
          - set firewall ipv6-name to_jec6 rule 12 description 'Port 587 - Mail submission'
          - set firewall ipv6-name to_jec6 rule 12 destination port '587'
          - set firewall ipv6-name to_jec6 rule 12 protocol 'tcp'
          - set firewall ipv6-name to_jec6 rule 12 state new 'enable'
          - set firewall ipv6-name to_jec6 rule 20 'icmpv6'
          - set firewall ipv6-name to_jec6 rule 20 action 'accept'
          - set firewall ipv6-name to_jec6 rule 20 description 'Allow ICMP/ping.'
          - set firewall ipv6-name to_jec6 rule 20 protocol 'icmpv6'
          - set firewall ipv6-name to_jec6 rule 30 action 'accept'
          - set firewall ipv6-name to_jec6 rule 30 description 'Allow Traceroute.'
          - set firewall ipv6-name to_jec6 rule 30 destination port '33434-33534'
          - set firewall ipv6-name to_jec6 rule 30 protocol 'udp'
          - set firewall ipv6-name to_jec6 rule 40 action 'accept'
          - set firewall ipv6-name to_jec6 rule 40 description 'Allow SYSLOG from router.'
          - set firewall ipv6-name to_jec6 rule 40 destination address '2001:470:5678::22'
          - set firewall ipv6-name to_jec6 rule 40 destination port '514'
          - set firewall ipv6-name to_jec6 rule 40 protocol 'udp'
          - set firewall ipv6-name to_jec6 rule 40 source address '2001:470:1234:64::0001:0203'
          - set firewall ipv6-name to_jec6 rule 8 action 'accept'
          - set firewall ipv6-name to_jec6 rule 8 description 'Allow SSH.'
          - set firewall ipv6-name to_jec6 rule 8 destination port '22'
          - set firewall ipv6-name to_jec6 rule 8 protocol 'tcp'
          - set firewall ipv6-name to_jec6 rule 8 state new 'enable'
          - set firewall ipv6-name to_jec6 rule 9 action 'accept'
          - set firewall ipv6-name to_jec6 rule 9 destination port 'domain'
          - set firewall ipv6-name to_jec6 rule 9 protocol 'tcp_udp'
          - set firewall ipv6-src-route 'disable'
          - set firewall log-martians 'enable'
          - set firewall name allow-all4 default-action 'accept'
          - set firewall name internet-local4 default-action 'drop'
          - set firewall name internet-local4 description 'Internet to local (r outer).'
          - set firewall name internet-local4 rule 1 action 'accept'
          - set firewall name internet-local4 rule 1 state established 'enable'
          - set firewall name internet-local4 rule 1 state related 'enable'
          - set firewall name internet-local4 rule 10 action 'accept'
          - set firewall name internet-local4 rule 10 destination port '23'
          - set firewall name internet-local4 rule 10 protocol 'tcp'
          - set firewall name internet-local4 rule 10 state new 'enable'
          - set firewall name internet-local4 rule 2 state invalid 'enable'
          - set firewall name internet-local4 rule 20 'source'
          - set firewall name internet-local4 rule 20 action 'accept'
          - set firewall name internet-local4 rule 20 description 'Allow OpenVpn tunnels.'
          - set firewall name internet-local4 rule 20 destination group port-group 'OPENVPN-PORTS'
          - set firewall name internet-local4 rule 20 protocol 'udp'
          - set firewall name internet-local4 rule 30 action 'accept'
          - set firewall name internet-local4 rule 30 description 'Allow traceroute.'
          - set firewall name internet-local4 rule 30 destination port '33434-33534'
          - set firewall name internet-local4 rule 4 action 'accept'
          - set firewall name internet-local4 rule 4 protocol 'icmp'
          - set firewall name internet-local4 rule 7 action 'accept'
          - set firewall name internet-local4 rule 7 description 'Allow protocol IPv6 tunnels protocol 41.'
          - set firewall name internet-local4 rule 7 protocol '41'
          - set firewall name to_internet4 default-action 'reject'
          - set firewall name to_internet4 rule 100 action 'accept'
          - set firewall name to_internet4 rule 100 source address '192.168.0.0/24'
          - set firewall name to_jec4 default-action 'accept'
          - set firewall receive-redirects 'disable'
          - set firewall send-redirects 'enable'
          - set firewall source-validation 'disable'
          - set firewall syn-cookies 'enable'
          - set firewall twa-hazards-protection 'disable'
          - set interfaces ethernet eth0 address 'dhcp'
          - set interfaces ethernet eth0 hw-id '00:00:24:d1:60:c0'
          - set interfaces ethernet eth1 address '192.168.0.1/24'
          - set interfaces ethernet eth1 address '2001:470:1234::1/64'
          - set interfaces ethernet eth1 hw-id '00:00:24:d1:60:c1'
          - set interfaces ethernet eth1 ipv6 dup-addr-detect-transmits '1'
          - set interfaces ethernet eth1 ipv6 router-advert cur-hop-limit '64'
          - set interfaces ethernet eth1 ipv6 router-advert link-mtu '0'
          - set interfaces ethernet eth1 ipv6 router-advert managed-flag 'false'          - set interfaces ethernet eth1 ipv6 router-advert max-interval '600'
          - set interfaces ethernet eth1 ipv6 router-advert other-config-flag 'false'
          - set interfaces ethernet eth1 ipv6 router-advert reachable-time '0'
          - set interfaces ethernet eth1 ipv6 router-advert retrans-timer '0'
          - set interfaces ethernet eth1 ipv6 router-advert send-advert 'true'
          - set interfaces ethernet eth2 hw-id '00:00:24:d1:60:c2'
          - set interfaces ethernet eth3 hw-id '00:00:24:d1:60:c3'
          - set interfaces loopback 'lo'
          - set interfaces openvpn vtun0 description 'Summersoft <-> JEC VPN'
          - set interfaces openvpn vtun0 encryption 'bf128'
          - set interfaces openvpn vtun0 hash 'sha1'
          - set interfaces openvpn vtun0 local-address '10.0.255.5'
          - set interfaces openvpn vtun0 local-port '1196'
          - set interfaces openvpn vtun0 mode 'site-to-site'
          - set interfaces openvpn vtun0 protocol 'udp'
          - set interfaces openvpn vtun0 remote-address '10.0.255.6'
          - set interfaces openvpn vtun0 remote-host '5.6.7.8'
          - set interfaces openvpn vtun0 remote-port '1196'
          - set interfaces openvpn vtun0 shared-secret-key-file '/config/auth/vpn1-vpn2.key'
          - set interfaces tunnel tun0 address '2001:470:9012:345::2/64'
          - set interfaces tunnel tun0 description 'HE.NET Cox IPv6 Tunnel'
          - set interfaces tunnel tun0 encapsulation 'sit'
          - set interfaces tunnel tun0 local-ip '9.0.1.2'
          - set interfaces tunnel tun0 remote-ip '1.1.2.3'
          - set nat source rule 20 description 'Masquerade internal IPv4'
          - set nat source rule 20 outbound-interface 'eth0'
          - set nat source rule 20 protocol 'all'
          - set nat source rule 20 source address '192.168.0.0/24'
          - set nat source rule 20 translation address 'masquerade'
          - set protocols static interface-route6 ::/0 next-hop-interface 'tun0'
          - set protocols static route 10.0.0.0/8 'blackhole'
          - set protocols static route 172.16.0.0/12 'blackhole'
          - set protocols static route 192.168.0.0/16 'blackhole'
          - set protocols static route6 2001:470:5679::/48 blackhole distance '254'
          - set protocols static route6 fc00::/7 'blackhole'
          - set service ssh port '23'
          - set system config-management commit-revisions '20'
          - set system console device ttyS0 speed '9600'
          - set system host-name 'newjecrouter'
          - set system login user admin level 'admin'
          - set system name-server 192.168.0.5
          - set system name-server 2001:470:5679::5
          - set system ntp server '0.us.pool.ntp.org'
          - set system ntp server '1.us.pool.ntp.org'
          - set system ntp server '2.us.pool.ntp.org'
          - set system package repository community components 'main'
          - set system package repository community distribution 'helium'
          - set system package repository community url 'http://packages.vyos.net/vyos'
          - set system syslog global facility all level 'notice'
          - set system syslog global facility protocols level 'debug'
          - set system time-zone 'Chicago'
          - set zone-policy zone internet default-action 'drop'
          - set zone-policy zone internet from jec firewall ipv6-name 'to_internet6'
          - set zone-policy zone internet from jec firewall name 'to_internet4'
          - set zone-policy zone internet from local firewall ipv6-name 'allow-all6'
          - set zone-policy zone internet from local firewall name 'allow-all4'
          - set zone-policy zone internet interface 'eth0'
          - set zone-policy zone jec default-action 'drop'
          - set zone-policy zone jec from internet firewall ipv6-name 'to_jec6'
          - set zone-policy zone jec from internet firewall name 'to_jec4'
          - set zone-policy zone jec from local firewall ipv6-name 'allow-all6'
          - set zone-policy zone jec from local firewall name 'allow-all4'
          - set zone-policy zone jec interface 'eth1'
          - set zone-policy zone local 'local-zone'
          - set zone-policy zone local default-action 'drop'
          - set zone-policy zone local from internet firewall ipv6-name 'internet-local6'
          - set zone-policy zone local from internet firewall name 'internet-local'
          - set zone-policy zone local from jec firewall ipv6-name 'allow-all6'
          - set zone-policy zone local from jec firewall name 'allow-all4'
```

##### EXPECTED RESULTS

No error message, successful configuration as what happens with some unknown number of fewer commands.

##### ACTUAL RESULTS

```
TASK [Configure JEC VyOS Router Commands] **************************************
task path: /Users/david/projects/jecrouter/jecrouter.yml:27
Using module file /Library/Python/2.7/site-packages/ansible/modules/core/network/vyos/vyos_config.py
<jecrouter> ESTABLISH LOCAL CONNECTION FOR USER: david
<jecrouter> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488512141.65-6070751761957 `" && echo ansible-tmp-1488512141.65-6070751761957="` echo ~/.ansible/tmp/ansible-tmp-1488512141.65-6070751761957 `" ) && sleep 0'
<jecrouter> PUT /var/folders/q3/pw4y1qrs0hv6q4rml1qcxmqc0000gp/T/tmppTujjB TO /Users/david/.ansible/tmp/ansible-tmp-1488512141.65-6070751761957/vyos_config.py
<jecrouter> EXEC /bin/sh -c 'chmod u+x /Users/david/.ansible/tmp/ansible-tmp-1488512141.65-6070751761957/ /Users/david/.ansible/tmp/ansible-tmp-1488512141.65-6070751761957/vyos_config.py && sleep 0'
<jecrouter> EXEC /bin/sh -c '/usr/bin/python /Users/david/.ansible/tmp/ansible-tmp-1488512141.65-6070751761957/vyos_config.py; rm -rf "/Users/david/.ansible/tmp/ansible-tmp-1488512141.65-6070751761957/" > /dev/null 2>&1 && sleep 0'
fatal: [testserver]: FAILED! => {
    "changed": false, 
    "commands": "commit comment \"configured by vyos_config\"", 
    "failed": true, 
    "invocation": {
            "auth_pass": null, 
            "authorize": false, 
            "backup": false, 
            "comment": "configured by vyos_config", 
            "config": null, 
            "host": "10.0.2.138", 
            "lines": [

 ..... all the lines that were sent and match exactly with above ....

            ], 
            "match": "line", 
            "password": null, 
            "port": 23, 
            "provider": {
                "host": "10.0.2.138", 
                "port": 23, 
                "transport": "cli", 
                "username": "admin"
            }, 
            "save": false, 
            "src": null, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "username": "admin"
        }
    }, 
    "msg": "timeout trying to send command: commit comment \"configured by vyos_config\"\r"
}

```
