### ISSUE TITLE
vmware finding vm using regular expression or recursively

### ISSUE THREAD

**Issue by fasterfish** [ansible/ansible#22240]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

vmware_guest_snapshot

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

Ubuntu 14.0.4 amd64

##### SUMMARY

As the ansible user I want to find vm using regular expression or recursively

##### STEPS TO REPRODUCE

I've some folder structure in datacenter:
DataCenter/root/team-1/SecondName/VM1
DataCenter/root/team-2/SecondName/VM2
DataCenter/root/team-3/SecondName/VM3
DataCenter/root/team-4/SecondName/VM4
And i want manage this vms.

```yaml
  tasks:
  - name: Vsphere Revert To Snapshot
    local_action:
      module: vmware_guest_snapshot
      hostname: ip
      datacenter: DataCenter
      folder: /
      username: user
      password: pass
      validate_certs: false
      name: VM1
      state: revert
      snapshot_name: snapshot
```

##### EXPECTED RESULTS

TASK [Vsphere Revert To Snapshot] **********************************************
ok: [127.0.0.1 -> localhost]

##### ACTUAL RESULTS

```
TASK [Vsphere Revert To Snapshot] **********************************************
task path: /home/tester/ansible_test/vsphere.yml:31
Using module file /home/tester/ansible_test/library/vmware_guest_snapshot.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: tester
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1488541087.97-221001296717482 `" && echo ansible-tmp-1488541087.97-221001296717482="` echo ~/.ansible/tmp/ansible-tmp-1488541087.97-221001296717482 `" ) && sleep 0'
<localhost> PUT /tmp/tmpZnPDjL TO /home/tester/.ansible/tmp/ansible-tmp-1488541087.97-221001296717482/vmware_guest_snapshot.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/tester/.ansible/tmp/ansible-tmp-1488541087.97-221001296717482/ /home/tester/.ansible/tmp/ansible-tmp-1488541087.97-221001296717482/vmware_guest_snapshot.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/tester/.ansible/tmp/ansible-tmp-1488541087.97-221001296717482/vmware_guest_snapshot.py; rm -rf "/home/tester/.ansible/tmp/ansible-tmp-1488541087.97-221001296717482/" > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "datacenter": DataCenter, 
            "description": "", 
            "folder": "/vm", 
            "hostname": "ip", 
            "name": "VM1", 
            "name_match": "first", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "snapshot_name": "snapshot", 
            "state": "revert", 
            "username": "********", 
            "uuid": null, 
            "validate_certs": false
        }, 
        "module_name": "vmware_guest_snapshot"
    }, 
    "msg": "Unable to manage snapshots for non-existing VM VM1"
}
	to retry, use: --limit @/home/tester/ansible_test/vsphere.retry

```

Can you add supporting regular expressions on folder path and recurse boolean parameter.
