### ISSUE TITLE
redhat_subscription module does not fail if pool not matched

### ISSUE THREAD

**Issue by sosiouxme** [ansible/ansible#22265]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
redhat_subscription module 

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/lmeyer/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Running from Fedora 25, against RHEL 7 hosts

##### SUMMARY
If you specify a pool to attach upon registration, but it doesn't match any actual subscription names, the task still succeeds, leaving you without the subscription you expected or any indication that it's missing.

Side notes: I was using the pool ID, which is what I expected "pool" to mean. Per https://github.com/ansible/ansible/issues/19466 this semantic will start working with 2.3. However it's still going to take forever (in my account) enumerating all the subscriptions when you've given it a specific ID and no lookup is required. And, if you fat-finger the name, you'll only find out later when you try to install something or update repos.

##### STEPS TO REPRODUCE

1. Fire up a RHEL 7 VM
2. Use the redhat_subscription module to try to register and subscribe it.
3. Check `subscription-manager status` which indicates the system is not properly subscribed.

Playbook:
```yaml
- hosts: all
  tasks:
    - redhat_subscription:
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        pool: something_bogus
        state: present
```

##### EXPECTED RESULTS
Failure because there's no "something_bogus" subscription.

##### ACTUAL RESULTS
Task reports "changed" as if everything is OK.

**Comment by ansibot** [comment]
cc @barnabycourt @alikins
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
@sosiouxme Does the `pool_ids` option added in 2.4 [1] solves your issue?

[1] http://docs.ansible.com/ansible/latest/redhat_subscription_module.html

needs_info

**Comment by sosiouxme** [comment]
@mkrizek doesn't look like the docs have been updated to mention that option.

Assuming that exists in 2.4, though, that only really solves the side issue. The main issue is that the module doesn't let you know if you're actually subscribed to what you expected to be.

**Comment by mkrizek** [comment]
@sosiouxme Haven't tried it but it looks like If you put bogus ID into `pool_ids` the task should fail.

**Comment by nrwahl2** [comment]
@mkrizek I've reproduced this with Ansible 2.4 on RHEL 7.3.

**Comment by nrwahl2** [comment]
Here's the problem. It first removes existing subs that don't match the pool you passed. If it succeeds in removing your existing subs and it doesn't match any pools, it sets `changed` to `True` and goes on its merry way:
```
    def update_subscriptions(self, regexp):
        changed = False
        consumed_pools = RhsmPools(self.module, consumed=True)
        pool_ids_to_keep = [p.get_pool_id() for p in consumed_pools.filter_pools(regexp)]
        pool_ids_to_keep.extend([p.get_pool_id() for p in consumed_pools.filter_products(regexp)])

        serials_to_remove = [p.Serial for p in consumed_pools if p.get_pool_id() not in pool_ids_to_keep]
        serials = self.unsubscribe(serials=serials_to_remove)

        subscribed_pool_ids = self.subscribe(regexp)

        if subscribed_pool_ids or serials:
            changed = True
        return {'changed': changed, 'subscribed_pool_ids': subscribed_pool_ids,
                'unsubscribed_serials': serials}
```

**Comment by nrwahl2** [comment]
I think I have a fix. I'll put in the PR tomorrow and find out.

**Comment by nrwahl2** [comment]
PR is in. Waiting for reviewers.

**Comment by ansibot** [comment]
cc @kahowell
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ikke-t** [comment]
this is still broken. I have rhel 7.6 and ansible-2.7.7-1.el7.noarch.

I hadn't noticed Red Hat Employee SKU had changed pool id again, and I run into this bug. I create new VMs and run:

```
---
# call this role with repos you want, eg:
# enabled_repos: [ rhel-7-server-rpms, rhel-7-server-optional-rpms,
#                  rhel-7-server-extras-rpms ]

- name: Subscribe to Red Hat
  redhat_subscription:
    state: present
    autosubscribe: false
    username: "{{ rh_sub_user }}"
    password: "{{ rh_sub_password }}"
    pool: "{{ rh_sub_pool }}"
  register: subscribe

# - name: Disable all the channels
#   rhsm_repository:
#     name: *
#     state: disabled
#   when: subscribe.changed

- name: Enable given repos
  rhsm_repository:
    name: "{{ enabled_repos }}"
    state: enabled
  with_items: "{{ enabled_repos }}"
  #when: subscribe.changed
```
It comes out with subscription as ok, but in reality it's not:

```
TASK [rhn : Subscribe to Red Hat] ********************************************************************************************************************************************
ok: [ocp-apps1]
ok: [bastion]
ok: [ocp-master]
ok: [ocp-apps2]
ok: [ocp-infra]

TASK [rhn : Enable given repos] **********************************************************************************************************************************************
failed: [ocp-apps2] (item=rhel-7-server-rpms) => {"changed": false, "item": "rhel-7-server-rpms", "msg": "This system has no repositories available through subscriptions"}
failed: [ocp-apps1] (item=rhel-7-server-rpms) => {"changed": false, "item": "rhel-7-server-rpms", "msg": "This system has no repositories available through subscriptions"}
failed: [bastion] (item=rhel-7-server-rpms) => {"changed": false, "item": "rhel-7-server-rpms", "msg": "This system has no repositories available through subscriptions"}
failed: [ocp-master] (item=rhel-7-server-rpms) => {"changed": false, "item": "rhel-7-server-rpms", "msg": "This system has no repositories available through subscriptions"}
failed: [ocp-infra] (item=rhel-7-server-rpms) => {"changed": false, "item": "rhel-7-server-rpms", "msg": "This system has no repositories available through subscriptions"}
failed: [ocp-apps2] (item=rhel-7-server-optional-rpms) => {"changed": false, "item": "rhel-7-server-optional-rpms", "msg": "This system has no repositories available through
```

Module should not come back as OK, if something went wrong. This is unreliable, and gives really bad experience on RHEL.
