### ISSUE TITLE
add service module to configure xinetd-based services

### ISSUE THREAD

**Issue by amunter** [ansible/ansible#22267]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

service
##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

Running from RHEL7, managing RHEL7
##### SUMMARY

I was trying to disable the chargen-dgram and other xinetd-based services using the service module and it errors out.  Is this intended behavior?
##### STEPS TO REPRODUCE

```yaml
- name: Ensure chargen-dgram service is not enabled 
  service:
      name: chargen-dgram
      state: stopped
      enabled: no
```

##### EXPECTED RESULTS

I expected it to return a success saying that it had disabled the service.  On the command line `chkconfig chargen-dgram off` works just fine.  Maybe it is failing because it's a RHEL7 system and the assumption is that it should use systemctl for everything, including xinetd services?

##### ACTUAL RESULTS

```
fatal: [ansible.local]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": false,
            "masked": null,
            "name": "chargen-dgram",
            "state": "stopped",
            "user": false
        }
    },
    "msg": "Could not find the requested service chargen-dgram: cannot disable"
}
```
