### ISSUE TITLE
complex args complain: None has invalid type

### ISSUE THREAD

**Issue by akvadrako** [ansible/ansible#2228]
Hi. When I try to use the new complex args (with devel HEAD) it complains:

> ERROR: action specified for task mail: None has invalid type <type 'NoneType'>

My playbook is like so:

``` yaml

---
- hosts: ${hosts}
  tasks:
    - mail:
      args:
        subject: hello
```
