### ISSUE TITLE
nagios - Unable to delete_downtime by service name 

### ISSUE THREAD

**Issue by jaredledvina** [ansible/ansible#22298]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nagios

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 3afb67e9b2) last updated 2017/03/05 19:01:21 (GMT +000)
  config file = /home/jaredledvina/ansible-test/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION
`/home/jaredledvina/ansible-test/ansible.cfg`:
```
[defaults]
host_key_checking = False
ask_sudo_pass = True
inventory = ./inventory.py
retry_files_enabled = False
remote_tmp = /tmp/$USER/.ansible/tmp

[ssh_connection]
scp_if_ssh = True
pipelining = False
```

##### OS / ENVIRONMENT
All hosts are running CentOS release 6.8 (Final) 
Nagios v4.1.1

##### SUMMARY
Using the `delete_downtime` action with the `nagios` module fails. From the nagios logs it appears the command it's using, `DEL_DOWNTIME_BY_HOST_NAME` is invalid.

##### STEPS TO REPRODUCE

Using the below Ansible playbook, I'm able to successfully scheduled downtime but, the `delete_downtime` task fails to actually execute. Note, `monitor_host` is a host variable for the FQDN of the Nagios host

```yaml
---
- hosts: all
  become: yes
  tasks:
  - name: Downtime Nagios check_example for 2 hours
    nagios:
      action: downtime
      service: check_example
      host: "{{ item }}"
      comment: Automated Ansible downtime
      minutes: 120
    delegate_to: "{{ monitor_host }}"
    with_items: "{{ play_hosts }}"

  - name: Remove Nagios downtime for check_example
    nagios:
      action: delete_downtime
      service: check_example
      host: "{{ item }}"
    delegate_to: "{{ monitor_host }}"
    with_items: "{{ play_hosts }}"
```

On the Nagios side, I see the following in the logs:
```
[1488663024] EXTERNAL COMMAND: SCHEDULE_SVC_DOWNTIME;redacted-hostname.example.com;check_example;1488663024;1488670224;1;0;7200;Ansible;Automated Ansible downtime. Set by root
[1488663025] EXTERNAL COMMAND: DEL_DOWNTIME_BY_HOST_NAME;redacted-hostname.example.com;check_example;;Scheduling downtime
[1488663025] Error: External command failed -> DEL_DOWNTIME_BY_HOST_NAME;redacted-hostname.example.com;check_example;;Scheduling downtime
```
##### EXPECTED RESULTS
The set downtime on a specific service would be deleted. 

##### ACTUAL RESULTS
Playbook executes successfully and does set downtime however, on the Nagios side the downtime is never deleted as it appears to error due to the command `DEL_DOWNTIME_BY_HOST_NAME` not existing. 

I did some digging and found https://assets.nagios.com/downloads/nagioscore/docs/nagioscore/4/en/extcommands.html which leads me to https://old.nagios.org/developerinfo/externalcommands/commandlist.php it seems that `DEL_DOWNTIME_BY_HOST_NAME` is not a command native to Nagios but that `DEL_SVC_DOWNTIME` is. I did find https://docs.icinga.com/latest/en/extcommands2.html which has the note for `DEL_DOWNTIME_BY_HOST_NAME` of "Changes provided by the Opsview team." I'm not entirely certain what that refers to. 

Happy to provide any other information that might help here!
