### ISSUE TITLE
jira module no longer able to edit labels against jira 7.1

### ISSUE THREAD

**Issue by jhawkesworth** [ansible/ansible#22314]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

jira
##### ANSIBLE VERSION

```

```

##### STEPS TO REPRODUCE

Created a list of jiras and labels that looked like this:

```
TASK [notify-jira-change : debug jiras_and_labels] ******************************
Monday 06 March 2017  14:04:50 +0000 (0:00:01.309)       0:00:25.676 **********
ok: [localhost] => {
    "jiras_and_labels": [
        {
            "jira": "PRJ-5663",
            "labels": [
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-5393",
            "labels": [
                "VInput",
                "CustomerZ",
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-4792",
            "labels": [
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-5695",
            "labels": [
                "JobSearch",
                "CustomerX",
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-4802",
            "labels": [
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-4831",
            "labels": [
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-4814",
            "labels": [
                "ServerSide",
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-4406",
            "labels": [
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-5599",
            "labels": [
                "Queueing",
                "Permissions",
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-4751",
            "labels": [
                "On_BLEEDING"
            ]
        },
        {
            "jira": "PRJ-5665",
            "labels": [
                "Searching",
                "CustomerX",
                "On_BLEEDING"
            ]
        }
    ]
}
```

```yaml
 - name: label existing jira.  DOES NOT SEEM TO WORK WITH JIRA 7.1
   jira: uri="https://redacted/" username=redacted password=redacted operation=edit project=PRJ issue="{{item.jira}}"
   args:
      fields:
          labels: "{{item.labels|list|default([])}}"
   with_items: "{{updated_jiras_and_labels}}"
   register: jira_updates
   ignore_errors: yes

```

##### EXPECTED RESULTS

Jiras successfully updated
##### ACTUAL RESULTS

400: Bad Request response

```

```

**Comment by jhawkesworth** [comment]
For info I worked around this problem by using the uri module

```
- name: set jira labels using uri module
  uri:
    url: "{{ 'https://redacted/rest/api/2/issue/' + item.jira }}"
    method: PUT
    user: redacted
    password: redacted
    force_basic_auth: yes
    status_code: 204
    body:
      update:
        labels:
          - set: "{{item.labels|default([])|list}}"
    body_format: json
  with_items: "{{updated_jiras_and_labels}}"
  register: jira_updates
  ignore_errors: yes
```
