### ISSUE TITLE
fedora 25 dnf installed packages not marked as user installed

### ISSUE THREAD

**Issue by fulminemizzega** [ansible/ansible#22320]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

dnf

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/edo/Sviluppo/fedora-vmware/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
ansible.cfg
```
[defaults]
inventory=inventory

[privilege_escalation]
become_method=sudo
become_user=root
```
##### OS / ENVIRONMENT
Fedora 25

##### SUMMARY

When running the playbook below not every package is marked as user installed, this means for example that running "dnf autoremove" afterwards will remove packages installed by the playbook.

##### STEPS TO REPRODUCE
Run the following playbook, then run "dnf history userinstalled":

```yaml
---
- name: Fedora on VMware post-install
  hosts: localhost
  become: yes
  tasks:
    - name: Update everything
      dnf: name="*" state=latest
    - name: Install packages
      dnf: name={{ item }} state=latest
      with_items:
        - vim-enhanced
        - emacs
        - tmux
        - powertop
        - gnome-tweak-tool
        - libselinux-python
        - dconf-editor
        - open-vm-tools-desktop
        - git
...
```
```dnf history userinstalled``` output:
```
Packages installed by user
anaconda-25.20.9-1.fc25.x86_64
ansible-2.2.1.0-1.fc25.noarch
docker-2:1.12.6-6.gitae7d637.fc25.x86_64
dracut-live-044-78.fc25.x86_64
gnome-tweak-tool-3.22.0-1.fc25.noarch
google-chrome-stable-56.0.2924.87-1.x86_64
kernel-modules-extra-4.9.12-200.fc25.x86_64
langpacks-en-1.0-8.fc25.noarch
memtest86+-5.01-15.fc25.x86_64
python2-dnf-1.1.10-5.fc25.noarch
syslinux-6.04-0.1.fc25.x86_64
tmux-2.2-3.fc25.x86_64
```

##### EXPECTED RESULTS
All the packages in the playbook should be listed as user installed, so that 'dnf autoremove' will not remove them. A possible workaround is running 'dnf mark <pkgs>'.
Plus, if you support also dnf autoremove https://github.com/ansible/ansible/pull/20333, then interesting things will happen.
