### ISSUE TITLE
maven_artifact module should allow preserving the name of the downloaded artifact

### ISSUE THREAD

**Issue by tumbl3w33d** [ansible/ansible#22337]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 3e4be156d7) last updated 2017/03/06 21:46:14 (GMT +200)
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When downloading an artifact you can ask the module to determine the latest version automatically (it gets extracted from the repo's metadata). The artifact's name in the repository comes with a version string which currently gets overwritten with 'latest' when downloading.
The problem with this approach is that you sometimes need to know what version the downloaded artifact has for further processing, My use case is transferring the version to the RPM that I build from it.

##### STEPS TO REPRODUCE
The implementation should introduce an additional parameter which causes what I described above. This is only relevant for the constellation _version: latest_ and _dest_ being a directory, because else the filename chosen by dest or the version explicitly selected win.

```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - maven_artifact:
        version: latest
        artifact_id: spring-core
        group_id: org.springframework
        dest: /tmp/
        keep_name: yes
```

##### EXPECTED RESULTS
The downloaded artifact contains the dynamically determined version string. In this case, the last version found in [this list](http://central.maven.org/maven2/org/springframework/spring-core/maven-metadata.xml). At the moment of creating this issue this is _/tmp/spring-core-4.3.7.RELEASE.jar_

##### ACTUAL RESULTS
The downloaded artifact is renamed to _/tmp/spring-core-latest.jar_
