### ISSUE TITLE
Unarchive unable to pass -j for zip files

### ISSUE THREAD

**Issue by Findarato** [ansible/ansible#22342]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

unarchive
##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/joe/.ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

using local hosts per playbook, all default

##### OS / ENVIRONMENT

Deploying from Fedora 25
Deploying to CentOS 7

##### SUMMARY

Attemping to extract a zip file into the same directory that it resides. passing '-j' to extra_ops and exclude:"README*" This results in a failed play
##### STEPS TO REPRODUCE

fatal: [wpl-amazonDriveSync.vm]: FAILED! => {
    "changed": false, 
    "dest": "/home/it/rclone/", 
    "extract_results": {
        "cmd": [
            "/bin/unzip", 
            "-o", 
            "/home/it/rclone/rclone64.zip", 
            "-j", 
            "-x", 
            "README*", 
            "-d", 
            "/home/it/rclone/"
        ], 
        "err": "caution: filename not matched:  -j\ncaution: excluded filename not matched:  README*\n", 
        "out": "Archive:  /home/it/rclone/rclone64.zip\n", 
        "rc": 11

```yaml
---
# tasks file for roles/rclone

- name: Create rclone folder
  file:
    path: /home/it/rclone
    state: directory
    mode: 0755
    owner: it
    group: it

- name: Download current Rclone
  get_url:
    url: http://downloads.rclone.org/rclone-current-linux-amd64.zip
    dest: /home/it/rclone/rclone64.zip
  tags: [rclone, program]

- name: Unzip rclone
  unarchive:
    src: /home/it/rclone/rclone64.zip
    dest: "/home/it/rclone/"
    remote_src: True
    extra_opts: ['-j']
    owner: it
    exclude: "README*"

- name: Copy rclone config file
  template:
    src: rclone.conf.j2
    dest: /home/it/.rclone.conf
    mode: 0644
  tags: [rclone, config]
```

##### EXPECTED RESULTS

extract zip file into folder it resides

##### ACTUAL RESULTS

```
fatal: [wpl-amazonDriveSync.vm]: FAILED! => {
    "changed": false, 
    "dest": "/home/it/rclone/", 
    "extract_results": {
        "cmd": [
            "/bin/unzip", 
            "-o", 
            "/home/it/rclone/rclone64.zip", 
            "-j", 
            "-x", 
            "README*", 
            "-d", 
            "/home/it/rclone/"
        ], 
        "err": "caution: filename not matched:  -j\ncaution: excluded filename not matched:  README*\n", 
        "out": "Archive:  /home/it/rclone/rclone64.zip\n", 
        "rc": 11
    }, 
    "failed": true, 
    "gid": 1000, 
    "group": "it", 
    "handler": "ZipArchive", 
    "invocation": {
        "module_args": {
            "backup": null, 
            "content": null, 
            "copy": true, 
            "creates": null, 
            "delimiter": null, 
            "dest": "/home/it/rclone/", 
            "directory_mode": null, 
            "exclude": [
                "README*"
            ], 
            "extra_opts": [
                "-j"
            ], 
            "follow": false, 
            "force": null, 
            "group": null, 
            "keep_newer": false, 
            "list_files": false, 
            "mode": null, 
            "original_basename": "rclone64.zip", 
            "owner": "it", 
            "regexp": null, 
            "remote_src": true, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/home/it/rclone/rclone64.zip", 
            "unsafe_writes": null, 
            "validate_certs": true
        }
    }, 
    "mode": "0755", 
    "msg": "failed to unpack /home/it/rclone/rclone64.zip to /home/it/rclone/", 
    "owner": "it", 
    "secontext": "unconfined_u:object_r:user_home_t:s0", 
    "size": 25, 
    "src": "/home/it/rclone/rclone64.zip", 
    "state": "directory", 
    "uid": 1000
}
```

I wanted to add to the bug :
```
/bin/unzip -o /home/it/rclone/rclone64.zip -j -x README* -d "/home/it/rclone/"
```
Fails

But 
```
/bin/unzip -j -o /home/it/rclone/rclone64.zip -x README* -d "/home/it/rclone/"
```

works correctly. This might just be a small paramters in the wrong order problem
