### ISSUE TITLE
json_query filter not expanding variable inside query

### ISSUE THREAD

**Issue by j--wong** [ansible/ansible#22346]
##### ISSUE TYPE
 - Bug Report
 
##### COMPONENT NAME
json_query filter

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
- Default configuration

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`json_query` filter returns no results when a `variable` is used in the query.

##### STEPS TO REPRODUCE

Commented lines in below playbook work as expected.  It has hardcoded value of `joe` in the query.

```yaml
---
- name: test json_query
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    all_names:
      names:
        - name: john
        - name: joe
        - name: joan
    name_filter: joe

  tasks:
    - set_fact:
        selected_names: "{{ all_names | json_query(\"names[?name=='{{ name_filter }}'].name\") }}"

    # - set_fact:
    #     selected_names: "{{ all_names | json_query(\"names[?name=='joe'].name\") }}"

    - debug: var=selected_names

```

##### EXPECTED RESULTS

```
PLAY [test json_query] *********************************************************

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "selected_names": [
        "joe"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```

##### ACTUAL RESULTS

```
PLAY [test json_query] *********************************************************

TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "selected_names": []
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
