### ISSUE TITLE
IAM module remove all groups does not work

### ISSUE THREAD

**Issue by bfloyd89** [ansible/ansible#22388]
##### ISSUE TYPE
Feature Request

##### COMPONENT NAME
iam

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using IAM module want to be able to set groups input parameter to [] in order to remove all the groups associated with a user. Currently the code does "if groups" and thus does not change anything with an empty list.

##### STEPS TO REPRODUCE
```
- hosts: localhost
  connection: local
  become: False
  pre_tasks:
    - include_vars: envs/iam_users.yml
    - set_fact:
        iam_users: "{{iam_users[account]}}"
        aws_account_id: "{{account_info[account]['aws_account_id']}}"
  tasks:
    - name: create users
      iam:
        iam_type: user
        name: "test-user"
        groups: ["test-group"]
        state: present

    - name: update user groups
      iam:
        iam_type: user
        name: "test-user"
        groups: []
        state: update
```

##### EXPECTED RESULTS
Remove "test-group" from "test-user"

##### ACTUAL RESULTS
Does not get removed

```
TASK [create users] ************************************************************
task path: /home/bfloyd/ansible/temp.yml:13
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/cloud/amazon/iam.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: bfloyd
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [localhost] => {
    "changed": true,
    "groups": [
        "test-group"
    ],
    "invocation": {
        "module_args": {
            "access_key_ids": null,
            "access_key_state": null,
            "aws_access_key": null,
            "aws_secret_key": null,
            "ec2_url": null,
            "groups": [
                "test-group"
            ],
            "iam_type": "user",
            "key_count": 1,
            "name": "test-user",
            "new_name": null,
            "new_path": null,
            "password": null,
            "path": "/",
            "profile": null,
            "region": null,
            "security_token": null,
            "state": "present",
            "trust_policy": null,
            "trust_policy_filepath": null,
            "update_password": "always",
            "validate_certs": true
        },
        "module_name": "iam"
    },
    "keys": [],
    "user_meta": {
        "access_keys": null,
        "created_user": {
            "arn": "arn:aws:iam::230700467799:user/test-user",
            "create_date": "2017-03-08T00:04:40.819Z",
            "path": "/",
            "user_id": "AIDAJOUN7ZJF6VWQCKJM2",
            "user_name": "test-user"
        },
        "password": null
    }
}

TASK [update user groups] ******************************************************
task path: /home/bfloyd/ansible/temp.yml:20
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/cloud/amazon/iam.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: bfloyd
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [localhost] => {
    "changed": false,
    "groups": null,
    "invocation": {
        "module_args": {
            "access_key_ids": null,
            "access_key_state": null,
            "aws_access_key": null,
            "aws_secret_key": null,
            "ec2_url": null,
            "groups": [],
            "iam_type": "user",
            "key_count": 1,
            "name": "test-user",
            "new_name": null,
            "new_path": null,
            "password": null,
            "path": "/",
            "profile": null,
            "region": null,
            "security_token": null,
            "state": "update",
            "trust_policy": null,
            "trust_policy_filepath": null,
            "update_password": "always",
            "validate_certs": true
        },
        "module_name": "iam"
    },
    "keys": {},
    "user_name": "test-user"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=0

```
