### ISSUE TITLE
Ansible pip module fails to use version conditionals or environment markers

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#22399]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pip
##### ANSIBLE VERSION
```
2.2.1
```

##### SUMMARY
it seems that unless you are using external requirements.txt files you cannot specify version conditions or environment markes when using ansible pip module. The workaround is to move the requirements outside the playbook and this means an additional file, file that also needs to be deployed to the host.

Please note that even **`pip install xxx` already accepts ranges and environment markers, if you quote the string to avoid bash processing.**

##### STEPS TO REPRODUCE

```yaml
- name: Installing pip modules with conditions and environment markers (like req.txt)
  pip:
    name="{{ item }}"
    state=present
  with_items:
    - 'pip>=9.0;!=9.0.1'
    - "futures>=3.0.5; python_version == '2.6' or python_version=='2.7''
```

##### Current results
```
 Exception:
Traceback (most recent call last):
  File \"/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/pip/basecommand.py\", line 215, in main
    status = self.run(options, args)
  File \"/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/pip/commands/install.py\", line 312, in run
    wheel_cache
  File \"/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/pip/basecommand.py\", line 276, in populate_requirement_set
    wheel_cache=wheel_cache
  File \"/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/pip/req/req_install.py\", line 182, in from_line
    markers = Marker(markers)
  File \"/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/pip/_vendor/packaging/markers.py\", line 282, in __init__
    raise InvalidMarker(err_str)
InvalidMarker: Invalid marker: '!=9.0.1', parse error at '!=9.0.1'
"}
failed: [localhost] (item=futures>=3.0.5; python_version == '2.6' or python_version=='2.7') => {"cmd": "/Users/ssbarnea/.venv/rh/bin/pip install futures>=3.0.5; python_version == '2.6' or python_version=='2.7'", "failed": true, "item": "futures>=3.0.5; python_version == '2.6' or python_version=='2.7'", "msg": "
:stderr: Invalid requirement: '=='
Traceback (most recent call last):
  File \"/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/pip/req/req_install.py\", line 82, in __init__
    req = Requirement(req)
  File \"/Users/ssbarnea/.venv/rh/lib/python2.7/site-packages/pip/_vendor/packaging/requirements.py\", line 96, in __init__
    requirement_string[e.loc:e.loc + 8]))
InvalidRequirement: Invalid requirement, parse error at \"'=='\"

"}
```
References:
* [PEP 0345](https://www.python.org/dev/peps/pep-0345/)
* [PEP 0508](https://www.python.org/dev/peps/pep-0508/#environment-markers).

Note: consider that it would be unreasonable to try to re-implement the parsing logic in ansible when pip knows it the best and implements it for both: external requirements files and command line usage. A correct implementation should allow these to be part of the `name` parameter and allow pip to take care of it. This would also be easy to maintain as we would not have to re-implement any bug fixes or features related to these.

**Comment by ansibot** [comment]
cc @mattupstate
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alextricity25** [comment]
I'm seeing the same thing. In my role's `defaults/main.yml` I have:
```
elasticsearch_pip_packages:
  - elasticsearch<3.0.0,>=2.0.0
  - elasticsearch-curator==4.0.4
  - httplib2
```

My task:
```
- name: Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: "{{ pip_install_options | default('') }}"
  register: install_pip_packages
  until: install_pip_packages | success
  retries: 5
  delay: 2
  with_items: "{{ elasticsearch_pip_packages }}"
  tags:
    - elasticsearch-pip-packages
```

The failure:
```
TASK [elasticsearch : Install pip packages] ************************************
...
failed: [xxxx] (item=elasticsearch<3.0.0,>=2.0.0) => 
{"attempts": 5, "cmd": "/usr/local/bin/pip2 install -U elasticsearch<3.0.0 >=2.0.0", "failed": true, "item": 
"elasticsearch<3.0.0,>=2.0.0", "msg": "\n:stderr: Invalid requirement: '>=2.0.0'\nTraceback (most recent call 
last):\n  File \"/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py\", line 82, in __init__\n    req = 
Requirement(req)\n  File \"/usr/local/lib/python2.7/dist-packages/pip/_vendor/packaging/requirements.py\", 
line 96, in __init__\n    requirement_string[e.loc:e.loc + 8]))\nInvalidRequirement: Invalid requirement, parse 
error at \"'>=2.0.0'\"\n\n"}
...
```

I am ensure if this is a problem with the latest version of Ansible.
