### ISSUE TITLE
DNF module gives inconsistent output dict to register

### ISSUE THREAD

**Issue by johnbieren** [ansible/ansible#22407]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

DNF

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

Fedora 25 cloud
##### SUMMARY

The registered output for dnf is different when it passes than when it fails.
##### STEPS TO REPRODUCE

Use the debug module to print out a registered result from the dnf module and compare it across a failed dnf run and a passed dnf run

```yaml
  - name: dnf test work
    dnf:
      name: golang
      state: present
    register: result
    ignore_errors: yes
  - name: dnf test work result
    debug:
      msg: "{{ result }}"
  - name: dnf test fail
    dnf:
      name: fakepackage
      state: present
    register: result2
    ignore_errors: yes
  - name: dnf test fail result
    debug:
      msg: "{{ result2 }}"

```

##### EXPECTED RESULTS

```
TASK [dnf test work result] ****************************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "failed": false,
        "msg": "<something>"
        "results": [
            "Installed: golang-src-1.7.5-1.fc25.noarch", 
            "Installed: go-srpm-macros-2-7.fc25.noarch", 
            "Installed: golang-1.7.5-1.fc25.x86_64", 
            "Installed: golang-bin-1.7.5-1.fc25.x86_64"
        ]
    }
}
TASK [dnf test fail result] ****************************************************
ok: [localhost] => {
    "msg": {
        "changed": false, 
        "failed": true, 
        "msg": "No package fakepackage available."
        "results": []
    }
}
```
##### ACTUAL RESULTS

```
TASK [dnf test work result] ****************************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "results": [
            "Installed: golang-src-1.7.5-1.fc25.noarch", 
            "Installed: go-srpm-macros-2-7.fc25.noarch", 
            "Installed: golang-1.7.5-1.fc25.x86_64", 
            "Installed: golang-bin-1.7.5-1.fc25.x86_64"
        ]
    }
}
TASK [dnf test fail result] ****************************************************
ok: [localhost] => {
    "msg": {
        "changed": false, 
        "failed": true, 
        "msg": "No package fakepackage available."
    }
}
```
