### ISSUE TITLE
Stopping glusterfs volume does not work due to the interactive question

### ISSUE THREAD

**Issue by Hubbitus** [ansible/ansible#22402]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gluster_volume

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Irrelevant

##### OS / ENVIRONMENT
Fedora 25 packages

##### SUMMARY
Call `gluster_volume` with `state: absent` leads to error: `Stopping volume will make its data inaccessible. Do you want to continue? (y/n)`

##### STEPS TO REPRODUCE
```yaml
    - name: UNMount new filesystem
      mount: state=unmounted src='egais.app.node1:{{volume_name}}' path='{{mount_dir}}'

    - name: stop gluster volume
      gluster_volume:
        state: stopped
        name: '{{volume_name}}'
        force: true

    - name: remove gluster volume
      gluster_volume:
        state: absent
        name: '{{volume_name}}'
```

##### EXPECTED RESULTS
Volume stopped

##### ACTUAL RESULTS
```
TASK [UNMount new filesystem] **************************************************
task path: /home/pasha/Projects/Ansible.cfg/Test_glusterfs.yml:67
changed: [egais.app.node2] => {"changed": true, "dump": "0", "fstab": "/etc/fstab", "name": "/mnt/glusterfs.test.mountpoint", "opts": "defaults", "passno": "0", "src": "egais.app.node1:glusterfs_vol1"}
changed: [egais.app.node1] => {"changed": true, "dump": "0", "fstab": "/etc/fstab", "name": "/mnt/glusterfs.test.mountpoint", "opts": "defaults", "passno": "0", "src": "egais.app.node1:glusterfs_vol1"}

TASK [stop gluster volume] *****************************************************
task path: /home/pasha/Projects/Ansible.cfg/Test_glusterfs.yml:70
fatal: [egais.app.node2]: FAILED! => {"changed": false, "failed": true, "msg": "error running gluster (/usr/sbin/gluster volume stop glusterfs_vol1) command (rc=1): Stopping volume will make its data inaccessible. Do you want to continue? (y/n) "}
changed: [egais.app.node1] => {"ansible_facts": {"glusterfs": {"peers": {"10.0.17.33": ["0c2d8c9f-66e5-48d9-98cb-dae546418b10", "Peer in Cluster (Connected)"], "egais.app.node2": ["0c2d8c9f-66e5-48d9-98cb-dae546418b10", "Peer in Cluster (Connected)"]}, "quotas": {}, "volumes": {"glusterfs_vol1": {"bricks": ["10.0.17.32:/mnt/glusterfs.brick.0", "10.0.17.33:/mnt/glusterfs.brick.0"], "id": "4993306c-ba2b-4d00-9f08-65b6423375e3", "name": "glusterfs_vol1", "options": {"nfs.disable": "on", "performance.cache-size": "32MB", "performance.readdir-ahead": "on", "transport.address-family": "inet"}, "quota": false, "status": "Stopped", "transport": "tcp"}}}}, "changed": true}
```

That seams like some race condition, because one host succeeded and one failed.
If I run that again I got error `volume does not exists`:

```
TASK [stop gluster volume] *****************************************************
task path: /home/pasha/Projects/Ansible.cfg/Test_glusterfs.yml:67
fatal: [egais.app.node1]: FAILED! => {"changed": false, "failed": true, "msg": "volume not found glusterfs_vol1"}
fatal: [egais.app.node2]: FAILED! => {"changed": false, "failed": true, "msg": "volume not found glusterfs_vol1"}
	to retry, use: --limit @.ansible-retry/Test_glusterfs.retry
```
