### ISSUE TITLE
letsencrypt module does not create any cert when using DNS-based validation

### ISSUE THREAD

**Issue by walterdolce** [ansible/ansible#22411]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME

letsencrypt

##### ANSIBLE VERSION

Ansible version is `2.2.1.0`

##### SUMMARY

It looks like the Let's Encrypt Ansible module doesn't create any cert when running with the DNS-based validation. 

##### STEPS TO REPRODUCE

```
# vars
---
aws:
   access_key: "some_access_key"
   secret_key: "some_secret_key"
letsencrypt_account_email: "some_email@example.com"
letsencrypt_key_filename: "some_filename"
letsencrypt_dir: "some/path"
letsencrypt_domains:
   - "foo"
   - "bar"

# tasks
---
- name: Install Route53 dependencies
  pip:
    name: boto

- name: Create folder
  file:
    path: "{{ letsencrypt_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Create key
  shell: 'ssh-keygen -t rsa -b 2048 -C "{{ letsencrypt_account_email }}" -f ~/.ssh/{{ letsencrypt_key_filename }} -q -N ""'
  args:
    creates: "~/.ssh/{{ letsencrypt_key_filename }}"

- name: Create domain key
  shell: 'ssh-keygen -t rsa -b 2048 -C "{{ letsencrypt_account_email }}" -f ~/.ssh/id_rsa.{{ item }} -q -N ""'
  args:
    creates: '~/.ssh/id_rsa.{{ item }}'
  with_items: "{{ letsencrypt_domains }}"

- name: Create CSR (Certificate Signing Request)
  shell: 'openssl req -new -nodes -key ~/.ssh/{{ letsencrypt_key_filename }} -out {{ letsencrypt_dir }}/{{ item }}.csr -subj "/CN={{ item }}"'
  args:
    creates: '{{ letsencrypt_dir }}/{{ item }}.csr'
  with_items: "{{ letsencrypt_domains }}"

- name: Create challenge
  letsencrypt:
    account_key: '~/.ssh/id_rsa.{{ item }}'
    challenge: dns-01
    csr: '{{ letsencrypt_dir }}/{{ item }}.csr'
    dest: '{{ letsencrypt_dir }}/{{ item }}.crt'
    remaining_days: 20
  register: letsencrypt_challenge
  with_items: "{{ letsencrypt_domains }}"

- name: Create Route53 TXT record for DNS-based certificate validation
  route53:
    command: create
    aws_access_key: "{{ aws.access_key_id }}"
    aws_secret_key: "{{ aws.secret_access_key }}"
    zone: 'some_hosted_zone.com'
    record: "{{ item.1.challenge_data[item.0]['dns-01']['resource'] }}.some_hosted_zone.com"
    retry_interval: 300
    type: TXT
    ttl: 7200
    value: '"{{ item.1.challenge_data[item.0]["dns-01"]["resource_value"] }}"'
    wait: yes
  when: "letsencrypt_challenge|changed"
  with_together:
    - "{{ letsencrypt_domains }}"
    - "{{ letsencrypt_challenge['results'] }}"
  ignore_errors: yes

- name: Validate challenge
  letsencrypt:
    account_key: '~/.ssh/id_rsa.{{ item }}'
    challenge: dns-01
    csr: '{{ letsencrypt_dir }}/{{ item }}.csr'
    dest: '{{ letsencrypt_dir }}/{{ item }}.crt'
    data: '{{ letsencrypt_challenge }}'
    remaining_days: 20
  when: '{{ letsencrypt_challenge|changed }}'
  with_items: "{{ letsencrypt_domains }}"

- name: Delete Route53 TXT record for DNS-based certificate validation
  route53:
    command: delete
    aws_access_key: "{{ aws.access_key_id }}"
    aws_secret_key: "{{ aws.secret_access_key }}"
    zone: 'some_hosted_zone.com'
    record: "{{ item.1.challenge_data[item.0]['dns-01']['resource'] }}.some_hosted_zone.com"
    retry_interval: 300
    type: TXT
    ttl: 7200
    value: '"{{ item.1.challenge_data[item.0]["dns-01"]["resource_value"] }}"'
    wait: yes
  when: "letsencrypt_challenge|changed"
  with_together:
    - "{{ letsencrypt_domains }}"
    - "{{ letsencrypt_challenge['results'] }}"
  ignore_errors: yes

```

##### ACTUAL RESULTS

No errors are being thrown or anything, it provisions just fine

##### EXPECTED RESULTS
 
There should be a cert generated
