### ISSUE TITLE
default(omit) support for role variables

### ISSUE THREAD

**Issue by user140547** [ansible/ansible#22417]
- Feature Idea

##### COMPONENT NAME
Omit Jinja Filter not working for roles

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
 
no changes

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using a role I would like to conditionally overwrite a default role variable. E.g. when using
```
role: add-datasource, database_port: "{{specific_port}}"
```
and its role default is:
```
database_port:  555
```

this code fails if ```"{{specific_port}}"``` is undefined. I tried to use 
```
role: add-datasource, database_port: "{{specific_port | default(omit)}}"
```
This does something, since that produces something like ```__omit_place_holder__13591cbadc06ab5c983999f1e2f08e6bddb0779a```

According to http://docs.ansible.com/ansible/playbooks_filters.html#omitting-parameters, omitting parameters only works for module parameters. Would it not be possible to include support for others types of variables, like role variables in this case?

##### STEPS TO REPRODUCE

Playbook
```yaml
- name: test omit in role
  hosts: localhost
  gather_facts: false

  roles:
     - {
         role: add-datasource,
         database_port:  "{{ specific_port | default(omit) }}"
       }
```
roles/add-datasource/defaults/main.yml

```yaml
database_port: 555

```
roles/add-datasource/tasks/main.yml
```yaml
- debug:
    msg: " db port is {{database_port}}"
```

##### EXPECTED RESULTS

```
[root@localhost bugrep]# ansible-playbook -i fooinv test.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [test omit in role] *******************************************************

TASK [add-datasource : debug] **************************************************
ok: [localhost] => {
    "msg": " db port is 555"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
[root@localhost bugrep]# ansible-playbook -i fooinv test.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [test omit in role] *******************************************************

TASK [add-datasource : debug] **************************************************
ok: [localhost] => {
    "msg": " db port is __omit_place_holder__a499aad4f9c7710383ff196b5b6770c9d9a0382b"
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by sivel** [comment]
I think you are overcomplicating the situation slightly, and likely don't need to use `omit` at all.

Due to having `database_port` in your roles defaults, you don't need to supply it all to the role call.

`omit` is specifically designed to work for module arguments, and not just generic variables throughout a playbook.  There isn't a way to "undefine" a variable, so as long as you define `database_port` in your call to that role, it will always be defined, and defaults will not be used.

**Comment by user140547** [comment]
Well in a more complex playbook, I want to add many datasources (possibly spread over multiple files)

```
 - { role: add-datasource, database_port:  "{{ database_1_port | default(omit) }}" }
 - { role: add-datasource, database_port:  "{{ database_2_port | default(omit) }}" }
 - { role: add-datasource, database_port:  "{{ database_3_port | default(omit) }}" }
```

It should be possible to override that parameter if necessary, but the playbook should not fail if  `database_1_port` etc. is undefined.

I could do

```

 - { role: add-datasource, database_port:  "{{ database_1_port | default("555") }}" }
 - { role: add-datasource, database_port:  "{{ database_2_port | default("555") }}" }
 - { role: add-datasource, database_port:  "{{ database_3_port | default("555") }}" }
```

But then, if I wanted to change the default port, I have to change it n-times instead of once at the role default.

I could also define a variable and put it into group_vars, but in my opinion that variable better fits into a role default

**Comment by sivel** [comment]
If anything, I think perhaps the correct solution, would be to have vars in defaults apply, when a variable passed to the role is undefined.  Simply by just not putting `|default` on the var passed into the role.

**Comment by snowsky** [comment]
You may want to use omit to avoid recursive variable calls, but I don't think omit applies for this case.

**Comment by ingvagabund** [comment]
@sivel if you mean:
```yaml
roles:
- role: some_role
  r_some_role_variable: some_undefined_variable
```

```yaml
# inside some_role
- name: do something
  task
  when:
  - r_some_role_variable is defined
```

that does not work

**Comment by freeseacher** [comment]
Reusable roles they said...

**Comment by dtantsur** [comment]
> If anything, I think perhaps the correct solution, would be to have vars in defaults apply, when a variable passed to the role is undefined. Simply by just not putting |default on the var passed into the role.

This will not work, undefined variables in `vars` cause a failure (just tried).

**Comment by BarbzYHOOL** [comment]
Yes, I got this issue when trying to put variables in conditions so I can't make an advanced command role -_-'

i just need to be able to skip a variable if not defined, to ignore it

**Comment by emz00** [comment]
This makes it difficult to re-use roles and forces me to specify default values in multiple places. I've only started using Ansible recently and already run into this multiple times. Most recent use case:

Role **active_user** creates a Linux user account and sets its home directory mode. Role **app_service** creates a systemd service and a user account for it to run under, calling the **active_user** role to do that. For a particular service I want to override the home directory mode, so I create a variable for that in the **active_user** role with a default value of 0700. In the **app_service** role I also want to accept the home directory mode as a variable and pass that to the **active_user** role, if specified. If not specified, I want to use the default value.

Currently I have to either specify the value every time or repeat the default value in the **app_service** role.

**Comment by BradFelmey** [comment]
I have a different scenario that could benefit from the variable equivalent of (omit).

When running code through Ansible check mode (ansible-playbook --check), sometimes it's necessary to skip certain actions (usually API calls banging up against non-idempotent systems). This means that for subsequent actions to be evaluated in check mode variable values need to be provided as if the skipped action had actually taken place. The thing is - these variables should only be faux-populated if in check mode ; otherwise, it's desired for the task to fail in normal operation if the value isn't populated.

Task 1 runs and produces, if successful, a variable value. Due to non-idempotency, this task needs to be skipped when in check mode.

Task 2 runs and needs values from task 1. In check mode (and ONLY in check mode), we need to supply a faux variable value for check mode to succeed in evaluating this task.

Something akin to (pseudocode):
```
- name: Task 1 action against non-idempotent API
  when:
    - not ansible_check_mode
  uri:
    url: "https://somehost/stupid/non-idempotent/api/action"
    method: POST
    return-content: yes
  register: retval

- name: Task 2 action dependent upon value from task 1
  vars:
    retval: "{{ 'foo' if ansible_check_mode else omit }}"
  uri:
    url: "https://otherhost/query/{{ retval }}"
```

I know what you're thinking - why doesn't this idiot just use _e.g._:

```
- name: Set values for check mode
  when:
    - ansible_check_mode
  set_fact:
    retval: foo
```

That DOES work, but adds clutter to the output ('skipping...'), which I'm trying to minimize. Not a world-ender, but does fall under the heading of "would be nice if..."
