### ISSUE TITLE
Iterated values cannot be used in when condition when using with_subelements

### ISSUE THREAD

**Issue by ju2wheels** [ansible/ansible#22426]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
- with_subelements
- loop_control.loop_var
- when condition

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file = /home/user/repos/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION 
```
[defaults]
inventory      = ./hosts
roles_path = ./roles
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using `loop_control.loop_var`, `with_subelements`, and `when` conditions together on a module, I am not able to use iterated values in the `when` condition.

##### STEPS TO REPRODUCE
```yaml
- hosts: localhost
  tasks:
    - name: Test with_subelements combined with a loop_var and when conditions
      loop_control:
        loop_var: debug_user
      vars:
        debug_users:
          - username: user_one
            properties:
              - one
              - two
              - three
          - username: user_two
            properties:
              - one
              - two
              - three
      debug:
        msg: "User {{ debug_user.0.username }} property {{ debug_user.1 }}"
      with_subelements:
        - "{{ debug_users }}"
        - properties
      when: >
        debug_users is iterable and
        debug_user is mapping and
        debug_user.0 is mapping and
        debug_user.0.properties is iterable and
        debug_user.0.username is defined
```

##### EXPECTED RESULTS
Expected the `when` conditions to be valid and the task not be skipped. A similar kind of `when` condition check works fine when combined with `with_items`, so I expected this way to work as well.

##### ACTUAL RESULTS
The `when` conditions are not valid and the task is skipped.

```
ansible-playbook test.yml 

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Test with_subelements combined with a loop_var and when conditions] ******
skipping: [localhost] => (item=[{u'username': u'user_one'}, u'one']) 
skipping: [localhost] => (item=[{u'username': u'user_one'}, u'two']) 
skipping: [localhost] => (item=[{u'username': u'user_one'}, u'three']) 
skipping: [localhost] => (item=[{u'username': u'user_two'}, u'one']) 
skipping: [localhost] => (item=[{u'username': u'user_two'}, u'two']) 
skipping: [localhost] => (item=[{u'username': u'user_two'}, u'three']) 

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by snowsky** [comment]
I reproduced the part of with_subelements but not for with_items with this yaml file:
```yaml
- hosts: localhost
  tasks:
    - name: Test with_subelements combined with a loop_var and when conditions
      loop_control:
        loop_var: debug_user
      vars:
        debug_users:
          - username: user_one
            properties:
              - one
              - two
              - three
          - username: user_two
            properties:
              - one
              - two
              - three
      debug:
        msg: "User {{ debug_user.0.username }} property {{ debug_user.1 }}"
      with_items:
        - "{{ debug_users[0].properties }}"
      when: >
        debug_users is iterable and
        debug_user is mapping and
        debug_user.0 is mapping and
        debug_user.0.properties is iterable and
        debug_user.0.username is defined
```
What I got is:
```
TASK [Test with_subelements combined with a loop_var and when conditions] ******
skipping: [localhost] => (item=one) 
skipping: [localhost] => (item=two) 
skipping: [localhost] => (item=three) 
```
