### ISSUE TITLE
[Feature request] Conditionals in with_items loop

### ISSUE THREAD

**Issue by kees-closed** [ansible/ansible#22439]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
conditional with_items

##### ANSIBLE VERSION
2.4.0

##### SUMMARY
In playbooks it's possible to set conditionals for roles:
```
  roles:
    - { role: common }
    - { role: desktop, when: ansible_hostname == "host1" }
    - { role: samba, when: ansible_hostname == "host1" }
    - { role: openvpn, when: ansible_hostname == "host2" }
    - { role: git, when: ansible_hostname == "host3" }
    - { role: unbound, when: ansible_hostname == "host2" }
```

It would be awesome to also have this for with_items. My first use case for that would be to use the [package](https://docs.ansible.com/ansible/package_module.html) module to install the same common packages on different Linux distributions (so with support for both dnf and apt). But some packages don't share the same name in e.g. Fedora and Debian. It would be very nice to be able to use the package module and make conditions possible based on the distribution (ansible_distribution) to define the little semantics in package naming. Otherwise it would result in different tasks for all the different package names using the package module, which might as well could be using the dnf or apt module directly.

**Comment by jhawkesworth** [comment]
I think people usually conditionally include a vars file which is specific to the distribution to do this.
I can't think of an example of this now but have a search on galaxy for roles which target different distributions.
Hope this helps,
Jon

**Comment by ansibot** [comment]
@AquaL1te Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
@AquaL1te i'm not certain that I understand what you are asking for. Can you please provide a mocked playbook example that demonstrates what you think this might look like?

needs_info

**Comment by kees-closed** [comment]
There are many examples I can give you, but here is just one.

```
- name: install ansible dependencies
  package: name={{ item }} state=present
  with_items:
    - "{{ ansible_dependencies_debian }}"
  when: ansible_distribution == "Debian"
  tags:
    - setup_ansible
    - install_packages
- name: install ansible dependencies
  package: name={{ item }} state=present
  with_items:
    - "{{ ansible_dependencies_fedora }}"
  when: ansible_distribution == "Fedora" 
  tags: 
    - setup_ansible
    - install_packages
```
Which could also be written as below (please note that it's pseudo code).

```
- name: install ansible dependencies
  package: name={{ package.item }} state=present
  with_items:
    - { package: "{{ ansible_dependencies_debian }}", when: ansible_distribution == "Debian" }
    - { package: "{{ ansible_dependencies_fedora }}", when: ansible_distribution == "Fedora" }
    tags:
    - setup_ansible
    - install_packages
```

**Comment by ghost** [comment]
I agree that this would be a very useful feature. Instead, I now write two separate tasks based on a conditional. I would _like_ to use one task, and include/exclude the items based on a variable.

**Comment by bcoca** [comment]
Closing as `include_role` already provides this.

**Comment by allenluce** [comment]
How does `include_role` provide this functionality?

**Comment by bcoca** [comment]
include_role allows for conditional execution, but if you really need an example, here it is:
```
- name: no need to include cause it is not dynamic
  import_role: name=common
- name: "this is really better a  play with hosts: host1, using block to only write condition once" 
  block:
      - include_role: name=desktop
      - include_role: name=samba
  when: ansible_hostname == "host1"
- name: again, its better to select hosts via plays
  include_role: name=openvpn
  when: ansible_hostname == "host2"
- inclue_role: name=git
  when: ansible_hostname == "host3" 
- include_role: name=unbound
  when: ansible_hostname == "host2" 
```

**Comment by bcoca** [comment]
As for the other example, which has always worked:
```
- name: install ansible dependencies
  package: name={{ package.item }} state=present
  when: ansible_distribution == item.when
  with_items:
    - { package: "{{ ansible_dependencies_debian }}", when: "Debian" }
    - { package: "{{ ansible_dependencies_fedora }}", when: "Fedora" }
  tags:
    - setup_ansible
    - install_packages
```
