### ISSUE TITLE
Usebility problem with RUNNING HANDLER

### ISSUE THREAD

**Issue by xrow** [ansible/ansible#22440]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Reconnect due HANDLER while RUNNING HANDLER

##### ANSIBLE VERSION
all

##### CONFIGURATION
n.a.

##### OS / ENVIRONMENT
any

##### SUMMARY
The problem is a minor usebility issue. When ever the HANDLER cause the connection to get killed/restarted. The rest of the hanlders will not get executed.

##### STEPS TO REPRODUCE
1.) run multiple roles vpn server is one of them
2.) Execution will stop after restart vpn server step

problematic code
```yaml
- name: "configure openvpn conf"
  copy:
   src: "vpn/servers/{{item.name}}/{{item.name}}.conf"
   dest: "/etc/openvpn/{{'server_' ~ item.name}}.conf"
  with_items: "{{vpn.servers}}"
  notify: restart openvpn
```

handlers
```yaml
---
 - name: "restart openvpn"
   service:
    name: "openvpn@{{'server_' ~ item.name}}"
    state: restarted
   with_items: "{{vpn.servers}}"

 - name: "reload firewalld"
   command: firewall-cmd --reload
```

##### EXPECTED RESULTS
Execution shall recontinue. All handlers shall run.

##### ACTUAL RESULTS
Execution stops after vpn restart
```
TASK [vpn-server : copy scripts] ***********************************************
ok: [admin01] => (item=connect.sh)
ok: [admin01] => (item=disconnect.sh)

TASK [vpn-server : enable and start vpn services] ******************************
ok: [admin01] => (item={u'name': u'intern'})

RUNNING HANDLER [vpn-server : restart openvpn] *********************************
```
