### ISSUE TITLE
Module Mail should have a "when" statement

### ISSUE THREAD

**Issue by flix444** [ansible/ansible#22444]
Hello, 

##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

mail Module 

##### ANSIBLE VERSION

```
ansible 2.2.1.0

```

##### OS / ENVIRONMENT

RHEL7 

##### SUMMARY

mail should have a when statement, if something in stdout it should send a mail. 

##### STEPS TO REPRODUCE

```yaml
- name: list contents of directory
        command: ls mydir
        register: contents
 mail:
      host: localhost
      subject: 'System {{ ansible_hostname }} has been successfully provisioned.'
      to: test@test.com
      body: "Some Thing"
      when: contents.stdout == "something"


```

##### EXPECTED RESULTS

Send mail but the module fails, with: 
unsupported parameter for module: when

##### ACTUAL RESULTS

```
fatal: [XXXXX]: FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: when"}

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In any case, you seem to be confusing module options with directives, `when` is applied to the task definition, not the module options, this is the correct way of adding a conditional:

```yaml
- name: list contents of directory
  command: ls mydir
  register: contents

- mail:
      host: localhost
      subject: 'System {{ ansible_hostname }} has been successfully provisioned.'
      to: test@test.com
      body: "Some Thing"
  when: contents.stdout == "something"
```
You also make the mistake of trying to have 2 actions in the same task, mail is it's own action and requires a leading `-`.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project


Thank you once again for this and your interest in Ansible!
