### ISSUE TITLE
Add support for virtualenv to mysql_user

### ISSUE THREAD

**Issue by denisemauldin** [ansible/ansible#22452]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
MacOS Sierra to Centos 7

##### SUMMARY
I have installed MySQL-python in my virtualenv.  In order to get mysql_user to work I have to set ansible_python_interpreter to the virtualenv version of python and then back after the mysql_user calls.  Please add a way to specify the python interpreter for mysql_user, ideally with virtualenv support.

##### STEPS TO REPRODUCE
```yaml
---
- name: Add mariadb repository to yum
  copy: src=mariadb.repo dest=/etc/yum.repos.d/mariadb.repo
  become: true
  tags:
      - mariadb

- name: Install mariadb
  yum: name={{ item }} state=latest
  with_items:
    - MariaDB-server
    - MariaDB-client
    - mariadb-devel
  become: true
  tags:
      - mariadb

- name: Create mariadb group
  group: name=mariadb state=present
  become: true
  tags:
      - mariadb

- name: Install python3 mariadb module
  pip:
    name: mysqlclient
    virtualenv: "{{ virtualenv_application_home }}"
  tags:
      - mariadb

- name: Start mysql service
  service: name=mysql state=started enabled=yes
  become: true
  tags:
      - mariadb

- name: Set ansible_python_interpreter
  set_fact: ansible_python_interpreter="{{ virtualenv_application_home }}/bin/python"
  tags:
      - mariadb

# sets root password if mariadb allows login as root/nopassword
- name: Set root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ mariadb_root_password }}"
  tags:
      - mariadb

```

##### EXPECTED RESULTS
I'd like the last command to be something like:
```yaml
- name: Set root password
  mysql_user:
    name: root
    password: "{{ mariadb_root_password }}"
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ mariadb_root_password }}"
    virtualenv: "{{ virtualenv_application_home }}"
  tags:
      - mariadb

```

**Comment by ansibot** [comment]
cc @Jmainguy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The supported mechanism is to utilize `ansible_python_interpreter`.  This is compatible with all modules and does not require per module changes.

It is possible to set `ansible_python_interpreter` per task using per task `vars` such as:

```
- mysql_user:
    [...]
  vars:
    ansible_python_interpreter: /path/to/venv/bin/python
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by denisemauldin** [comment]
@sivel That would be nice, but it doesn't work.  Maybe I should file a bug report?

```yaml
- name: Add SQL dump to MySQL/MariaDB database
  mysql_db:
      name: "{{ mariadb_databases[0].name }}"
      state: import
      target: "{{  mariadb_sql_file }}"
  become: true
  become_user: "{{ application_user }}"
  when: database_type  == 'mysql' or database_type == 'mariadb'
  vars:
      ansible_python_interpreter: "{{ virtualenv_application_home }}/bin/python"
  tags:
      - mariadb
      - mysql
      - import_database
```

Results in 

```
TASK [lims_roles/lims : Add SQL dump to MySQL/MariaDB database] ****************
task path: 
~/Projects/buildTools/test/test_roles/test/tasks/load_databases.yml:4
Using module file /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible/modules/core/database/mysql/mysql_db.py
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2202 -o 'IdentityFile="/Users/dmauldin/.vagrant.d/boxes/virtualboxes-VAGRANTSLASH-centos7-minimal-20170104.box/0/virtualbox/vagrant_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/dmauldin/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1489596669.84-79073289338087 `" && echo ansible-tmp-1489596669.84-79073289338087="` echo ~/.ansible/tmp/ansible-tmp-1489596669.84-79073289338087 `" ) && sleep 0'"'"''
<127.0.0.1> PUT /var/folders/23/mvvpcyl57t5_wvgnwcjxrfn0cm01cc/T/tmpmGsTKd TO /home/vagrant/.ansible/tmp/ansible-tmp-1489596669.84-79073289338087/mysql_db.py
<127.0.0.1> SSH: EXEC sftp -b - -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2202 -o 'IdentityFile="/Users/dmauldin/.vagrant.d/boxes/virtualboxes-VAGRANTSLASH-centos7-minimal-20170104.box/0/virtualbox/vagrant_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/dmauldin/.ansible/cp/ansible-ssh-%h-%p-%r '[127.0.0.1]'
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2202 -o 'IdentityFile="/Users/dmauldin/.vagrant.d/boxes/virtualboxes-VAGRANTSLASH-centos7-minimal-20170104.box/0/virtualbox/vagrant_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/dmauldin/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1489596669.84-79073289338087/ /home/vagrant/.ansible/tmp/ansible-tmp-1489596669.84-79073289338087/mysql_db.py && sleep 0'"'"''
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2202 -o 'IdentityFile="/Users/dmauldin/.vagrant.d/boxes/virtualboxes-VAGRANTSLASH-centos7-minimal-20170104.box/0/virtualbox/vagrant_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/dmauldin/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 '/bin/sh -c '"'"'{{ virtualenv_application_home }}/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1489596669.84-79073289338087/mysql_db.py && sleep 0'"'"''
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2202 -o 'IdentityFile="/Users/dmauldin/.vagrant.d/boxes/virtualboxes-VAGRANTSLASH-centos7-minimal-20170104.box/0/virtualbox/vagrant_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/dmauldin/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1489596669.84-79073289338087/ > /dev/null 2>&1 && sleep 0'"'"''
fatal: [default]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "mysql_db"
    }, 
    "module_stderr": "OpenSSH_7.3p1, LibreSSL 2.4.1\r\ndebug1: Reading configuration data /Users/dmauldin/.ssh/config\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 20: Applying options for *\r\ndebug1: /etc/ssh/ssh_config line 56: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 74792\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 127\r\nShared connection to 127.0.0.1 closed.\r\n", 
    "module_stdout": "/bin/sh: {{: command not found\r\n", 
    "msg": "MODULE FAILURE"
}
```

It doesn't expand the virtualenv parameter setting it with vars:
```'/bin/sh -c '"'"'{{ virtualenv_application_home }}/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1489596669.84-79073289338087/mysql_db.py && sleep 0'"'"''```

The following works, but it seems like a kludgy work around to set and unset the ansible_python_interpreter globally around each MariaDB/MySQL task (so that I can get access to MySQL-python/mysqlclient in my virtualenv)
```yaml
- name: set ansible_python_interpreter
  set_fact: ansible_python_interpreter="{{ virtualenv_application_home }}/bin/python"
  tags:
      - mariadb
```
