### ISSUE TITLE
Feature Idea: Ability to update complex facts

### ISSUE THREAD

**Issue by Arano-kai** [ansible/ansible#22482]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### SUMMARY

Give to `set_fact` ability to update key in dictionary, not overwriting all dictionary.
Or make module with such ability (`update_fact`)
 
##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - set_fact:
        complex1:
          key1_1: "val1_1"
          key2_2: "val1_2"
          complex2:
            key2_1: "val2_1"
            key2_2: "val2_2"

    - debug: var=complex1

    - set_fact:
        complex1:
          key1_3: "val1_3"

    - debug: var=complex1

    - set_fact:
        complex1:
          complex2:
            key2_1: "trololo"
            key2_3: "val2_3"

    - debug: var=complex1
```

##### EXPECTED RESULTS

```
TASK [debug] *******************************************************************
ok: [localhost] => {
    "complex1": {
        "complex2": {
            "key2_1": "val2_1", 
            "key2_2": "val2_2"
        }, 
        "key1_1": "val1_1", 
        "key2_2": "val1_2"
    }
}
{SKIPPED}
TASK [debug] *******************************************************************
ok: [localhost] => {
    "complex1": {
        "complex2": {
            "key2_1": "val2_1", 
            "key2_2": "val2_2"
        }, 
        "key1_1": "val1_1", 
        "key1_2": "val1_2", 
        "key1_3": "val1_3"
    }
}
{SKIPPED}
ok: [localhost] => {
    "complex1": {
        "complex2": {
            "key2_1": "trololo", 
            "key2_2": "val2_2", 
            "key2_3": "val2_3"
        }, 
        "key1_1": "val1_1", 
        "key1_2": "val1_2", 
        "key1_3": "val1_3"
    }
}
```
##### ACTUAL RESULTS

```
{SKIPPED}
TASK [debug] *******************************************************************
ok: [localhost] => {
    "complex1": {
        "complex2": {
            "key2_1": "val2_1", 
            "key2_2": "val2_2"
        }, 
        "key1_1": "val1_1", 
        "key2_2": "val1_2"
    }
}
{SKIPPED}
TASK [debug] *******************************************************************
ok: [localhost] => {
    "complex1": {
        "key1_3": "val1_3"
    }
}
{SKIPPED}
TASK [debug] *******************************************************************
ok: [localhost] => {
    "complex1": {
        "complex2": {
            "key2_1": "trololo", 
            "key2_3": "val2_3"
        }
    }
}
```
##### "WORKAROUND"
Use jinja2/python black magik
```yaml
---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - set_fact:
        complex1:
          key1_1: "val1_1"
          key1_2: "val1_2"
          complex2:
            key2_1: "val2_1"
            key2_2: "val2_2"


    - debug: var=complex1

    - set_fact:
        complex1: '
        {#- use "update" to not overwriting -#}
        {%- set _ = complex1.update(
          key1_3="val1_3"
        ) -%}
        {#- return updated var -#}
        {{ complex1 }}'

    - debug: var=complex1

    - set_fact:
        complex1: '
        {%- set _ = complex1["complex2"].update(
          key2_1="trololo",
          key2_3="val2_3"
        ) -%}
        {{ complex1 }}'

    - debug: var=complex1
```
