### ISSUE TITLE
per tasks vars not evaluated properly for lookups other than with_items

### ISSUE THREAD

**Issue by haad** [ansible/ansible#22487]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lookups other than with_items

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /Users/haad/Desktop/cracz/cracz-ansible-repo/ansible.cfg
  configured module search path = ['./library', './dist/ansible-plugins/library']
```

##### STEPS TO REPRODUCE

```yaml
- name: Test
  hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    list_hosts:
      - node1
      - node2

    test_list:
      - '{{ host_name }}'
      - bar

  tasks:
    - name: WORKS fine
      debug: var=test_list
      vars:
        host_name: '{{ item }}'
      with_items:
        - '{{ list_hosts }}'

    - name: Doesn't work
      copy:
        dest: '/tmp/nested/{{ host_name }}_ping-check.json'
        content: '{{ host_name }}'
      vars:
        host_name: '{{ item.0 }}'
      with_nested:
        - '{{ list_hosts }}'
        - '{{ test_list }}'
```

##### EXPECTED RESULTS

I would expect to see `host_name` defined to `{{ item.0 }}` in with_nested case. This happens to all lookups other than with_items which is really strange.

##### ACTUAL RESULTS

```
TASK [WORKS fine] **************************************************************
task path: /tmp/test.yml:16
ok: [localhost] => (item=node1) => {
    "invocation": {
        "module_args": {
            "var": "test_list"
        },
        "module_name": "debug"
    },
    "item": "node1",
    "test_list": [
        "node1",
        "bar"
    ]
}
ok: [localhost] => (item=node2) => {
    "invocation": {
        "module_args": {
            "var": "test_list"
        },
        "module_name": "debug"
    },
    "item": "node2",
    "test_list": [
        "node2",
        "bar"
    ]
}

TASK [Doesn't work] ************************************************************
task path: /tmp/test.yml:23
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "[u'{{ host_name }}', u'bar']: {{ item.0 }}: 'item' is undefined"
}
```
