### ISSUE TITLE
Add boot sequence to Service module

### ISSUE THREAD

**Issue by shaharmor** [ansible/ansible#22509]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Service Module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### CONFIGURATION
Nothing

##### OS / ENVIRONMENT
N/A

##### SUMMARY
There is no option to configure the desired boot sequence when using the service module.

##### STEPS TO REPRODUCE
```yaml
- name: enable zookeeper service
  service:
    name: zookeeper
    state: started
    enabled: yes
    sequence: 5
```

##### EXPECTED RESULTS
The passed `sequence` will be passed to `update-rc.d` command at the end like this: `update-rc.d zookeeper defaults 5`
