### ISSUE TITLE
Issues cloning more than 2 GIT repositories per playbook

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#22504]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
GIT

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/echodrome/git/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 16.10

##### SUMMARY

It seems the GIT module cannot handle more than 3 repository clones per playbook

##### STEPS TO REPRODUCE

In the main YAML file include another three different YAML files that each contain the instructions on cloning a different repo for example:

```yaml
 name: Checkout pkg repo
  git:
    repo: "{{pkg_repo}}"
    dest: "/home/{{user_name}}/.ansible-tmp/{{pkg_root}}"
    key_file: "/home/{{user_name}}/.ssh/id_rsa"
    accept_hostkey: no
    force: yes
    version: "{{pkg_branch}}"
    ssh_opts: "-o StrictHostKeyChecking=no"
```

Run the playbook and the code will fail:

```
fatal: [remotebox]: FAILED! => {"changed": false, "cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", "failed": true, "msg": "ssh: connect to host gitbox port 22: Connection refused\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "ssh: connect to host gitbox port 22: Connection refused\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stdout": "", "stdout_lines": []}
```

This is not a permissions issue on the GIT or SSH because _all three repositories got cloned correctly and all files are present_. Manually running the failed command on the remote box works correctly too:

```
/usr/bin/git ls-remote origin -h refs/heads/master
```

Executing this on the remote box works as well:

```
ssh-agent bash -c 'ssh-add /home/echodrome/.ssh/id_rsa; git clone git@gitbox:localpip.git'
```

Running any two repositories works without the error as well.

```yaml
---

- include: pkgtoolsgit.yml

- include: pkgreportsgit.yml

- meta: flush_handlers

- include: localpipgit.yml
```

##### EXPECTED RESULTS

No errors, all three repositories cloned on the remote box.

##### ACTUAL RESULTS

```
fatal: [remotebox]: FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/git ls-remote origin -h refs/heads/master", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "accept_hostkey": true, 
            "bare": false, 
            "clone": true, 
            "depth": null, 
            "dest": "/home/echodrome/.ansible-tmp/localpip", 
            "executable": null, 
            "force": true, 
            "key_file": "/home/echodrome/.ssh/id_rsa", 
            "recursive": true, 
            "reference": null, 
            "refspec": null, 
            "remote": "origin", 
            "repo": "git@gitbox:localpip.git", 
            "ssh_opts": null, 
            "track_submodules": false, 
            "umask": null, 
            "update": true, 
            "verify_commit": false, 
            "version": "master"
        }, 
        "module_name": "git"
    }, 
    "msg": "ssh: connect to host gitbox port 22: Connection refused\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", 
    "rc": 128, 
    "stderr": "ssh: connect to host gitbox port 22: Connection refused\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", 
    "stdout": "", 
    "stdout_lines": []
}
```
