### ISSUE TITLE
Dynamically run “ansible-galaxy install -r requirement.yml -p roles/” as a prerequisite before running a role

### ISSUE THREAD

**Issue by slmingol** [ansible/ansible#22508]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

roles & tasks

##### ANSIBLE VERSION

```
ansible 2.2.0.0 (stable-2.2 05dfed7575) last updated 2016/10/13 22:07:57 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 275fa3f055) last updated 2016/10/13 22:07:39 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 3e1ea76a75) last updated 2016/10/13 22:07:39 (GMT -400)
  config file = /Users/sammingolelli/ANSIBLE_CFGS/ansible_slm.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

```
ANSIBLE_CONFIG=/Users/sammingolelli/ANSIBLE_CFGS/ansible_slm.cfg
```

##### SUMMARY

Trying to pre-run a ansible-galaxy command to install needed roles from Git repository before using them later downstream within the same playbook .yml file.

##### STEPS TO REPRODUCE

```yaml
- name: Install prerequisite roles
  hosts: all
  become: no

  tasks:
    - name: run ansible galaxy
      local_action: command ansible-galaxy install -r requirements.yml -p roles/

- name: Install Oracle Java
  hosts: tomcat-servers:ss-servers:ns-servers:ld-servers
  become: yes

  roles:
    - raltd-jdk
```

##### EXPECTED RESULTS

I expect the raltd-jdk role to be downloaded if needed, and then used later within the same playbook.

##### ACTUAL RESULTS

```
$ ansible-playbook -i inv/myinventory raltd-jdk.yml
 ERROR! the role 'raltd-jdk' was not found in /path/to/ansible/roles:/etc/ansible/roles:/path/to/ansible

 The error appears to have been in '/path/to/ansible/raltd-jdk.yml': line 16, column 7, but may
 be elsewhere in the file depending on the exact syntax problem.

 The offending line appears to be:

   roles:
       - raltd-jdk
             ^ here
```
