### ISSUE TITLE
docker_container 's entrypoint directive incompatibility between 2.2.0.0 and 2.1.3.0

### ISSUE THREAD

**Issue by stepanv** [ansible/ansible#22510]
_From @stepanv on November 23, 2016 14:37_

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Linux and MacOS, probably unrelated

##### SUMMARY

`docker_container`'s `entrypoint` directive 

- in 2.2.0.0, it doesn't work with *exec form* parameters correctly
- in 2.2.0.0, it works ok with *shell form* parameters
- in 2.1.3.0, it didn't work with *shell form* parameters
- in 2.1.3.0, it worked with *exec form* parameters

In other words, in Ansible 2.2.0.0, `entrypoint` directive works with *shell form*, such as `/bin/sh -c date` (which is not preferred by docker) but when an array is used, such as `["/bin/sh", "-c", "date"]`, the container is unable to start. It looks like the complex value of `entrypoint` is incorrectly passed to docker.

In Ansible 2.1.3.0, it worked exactly the other way around. The `/bin/sh -c date` didn't work, but the `["bin/sh", "-c", "date"]` worked ok.

##### STEPS TO REPRODUCE

Execute:
```
docker info  # it is expected that Docker is installed
docker pull alpine  # On MacOS, this is required because with `-c local`, `docker_container` incorrectly pulls images (which is just another bug)
ansible-playbook /tmp/reproducer.yml
```

File `/tmp/reproducer.yml` content:
```
---

- name: docker_container module entrypoint directive regression
  hosts: localhost
  connection: local

  tasks:
    - name: "Show that running docker container with 'entrypoint' param does not always work"
      docker_container:
        image: alpine
        entrypoint: ["/bin/sh", "-c", "date"] # works in 2.1.3.0 but stopped working in 2.2.0.0
        #entrypoint: "/bin/sh -c date" # works in 2.2.0.0 but did not work in 2.1.3.0
        name: my_test

```

##### EXPECTED RESULTS

I would expect Ansible 2.2.0.0 to work the same way as version 2.1.3.0 where a container was created and its logs contains output of `/bin/sh -c date` command:
```
$ docker logs my_test
Wed Nov 23 14:14:28 UTC 2016
```

##### ACTUAL RESULTS

With Ansible 2.2.0.0, when `["/bin/sh", "-c", "date"]` is used:
```
ansible-playbook /tmp/reproducer.yml

PLAY [docker_container module entrypoint directive regression] *****************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Show that running docker container with 'entrypoint' param does not always work] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container 86b656ecf976370936e2c0d3c63ba51bdea47f04f9e77346d0db9b90c993563a: 404 Client Error: Not Found (\"{\"message\":\"oci runtime error: exec: \\\"[/bin/sh,\\\": stat [/bin/sh,: no such file or directory\"}\")"}
	to retry, use: --limit @/tmp/reproducer.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

As you can see, the executable was parsed as `[/bin/sh,` instead, it was supposed to be just `/bin/sh`.

With Ansible 2.1.3.0, when `"/bin/sh -c date"` is used, it's obvious the whole string was used as the executable:
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error starting container 09976976506a02149ea346032b15845e162cace65cf1e94e20881f6f6442120e: 404 Client Error: Not Found (\"{\"message\":\"oci runtime error: exec: \\\"/bin/sh -c date\\\": stat /bin/sh -c date: no such file or directory\"}\")"}
```

_Copied from original issue: ansible/ansible-modules-core#5711_
