### ISSUE TITLE
Trailing new lines aren't kept by default by template module

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#22531]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
Jinja

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
```
[defaults]
ask_pass = False
remote_user = root
inventory = inventories
timeout = 5
roles_path = roles

ansible_managed = This file is managed by DOCK42 Configuration Management, all manual changes will be lost.

[ssh_connection]
control_path = %(directory)s/%%h-%%p-%%r
```

##### SUMMARY
(referring to commit 1998eddf8d5213e476973a39a0ee57db020941ec)

When trying to wrap a conditional inside a template in an one liner, the line break will be skipped if there's no trailing character (e.g. like a whitespace to workaround this issue)

##### STEPS TO REPRODUCE
Create a template like this:

```yaml

# GSSAPI options
GSSAPIAuthentication {% if openssh.gssapi_authentication %}yes{% else %}no{% endif %}
GSSAPICleanupCredentials no
#GSSAPIStrictAcceptorCheck yes

```

```yaml

 openssh.gssapi_authentication: no

- name: Configure sshd
  template: 
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: root 
    group: root 
    mode: 0600
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - restart sshd
  become: yes
  tags:
    - sshd_config
```

##### EXPECTED RESULTS
```
# GSSAPI options
GSSAPIAuthentication no 
GSSAPICleanupCredentials no
```

##### ACTUAL RESULTS
```
 # GSSAPI options
GSSAPIAuthentication noGSSAPICleanupCredentials no
```
