### ISSUE TITLE
cannot power on VM with vmware_guest

### ISSUE THREAD

**Issue by jeroenjacobs79** [ansible/ansible#22542]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
ansible 2.2.1.0

##### SUMMARY
Receiving weird error when trying to power on exisisting vm
##### STEPS TO REPRODUCE
```
- name: power on created machine
  vmware_guest: hostname="{{ vsphere_host }}" username="{{ vsphere_user }}" password="{{ vsphere_pw }}" name="{{ label }}_{{ image_version_major }}.{{ image_version_minor }}" folder="{{ vsphere_folder }}" state="poweredon" validate_certs="{{ validate_ssl }}"

```

Results in:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'template'
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vCHhHE/ansible_module_vmware_guest.py\", line 959, in <module>\n    main()\n  File \"/tmp/ansible_vCHhHE/ansible_module_vmware_guest.py\", line 937, in main\n    wait_for_ip=module.params['wait_for_ip_address']\n  File \"/tmp/ansible_vCHhHE/ansible_module_vmware_guest.py\", line 494, in deploy_template\n    template = get_obj(self.content, [vim.VirtualMachine], self.params['template'])\nKeyError: 'template'\n", "module_stdout": "", "msg": "MODULE FAILURE"}

```

**Comment by jeroenjacobs79** [comment]
Also, I need certain properties (like "is_template") of vmware_guest in later phases. So don't recommend "use vsphere_guest as a workaround" as a solution.

**Comment by ansibot** [comment]
cc @jctanner @nerzhul @dav1x
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nerzhul** [comment]
Hello, do you have a vcenter ? Is the folder an absolute folder and do you use module from devel branch not stable ?

**Comment by jeroenjacobs79** [comment]
Yes, I have a vcenter host. I'm using the latest ansible version installed via pip, so I guess that's the stable version of the module, not development.

I added `template="" `, to bypass the error, but now Ansible complains that the vm already exists. This makes sense, as the vm already is there. I just want to turn it on via Ansible.

**Comment by nerzhul** [comment]
we did many many rework on vmware_guest module on devel branch, which will become available on 2.3 next month.
Can you test with devel branch, as it's non pertinent to use 2.2 module atm ?

**Comment by Illydth** [comment]
@nerzhul 

As the "OP" has not responded with a "I've tried this with the most recent version of the code", I'll go ahead and do it for him.

"ansible --version" provides:
ansible 2.3.0.0 (stable-2.3 9785d5b2fb) last updated 2017/03/28 23:46:59 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

Downloaded today from GitHub off branch "stable-2.3".

Current Playbook Invocation (ignore formatting please):
```yaml
- name: Boot VMWare Guest
   vmware_guest:
      hostname: "{{ vsphere_host }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      datacenter: "{{ data_center }}"
      validate_certs: no
      name: "{{ vsphere_vmname }}"
      wait_for_ip_address: yes
      state: poweredon
```
The intent here is simply to boot the vm, not create a new vm and this does indeed work using the most recent code.  

That said, a consideration and a request:

Consider:
-----------
If "name" doesn't match a system in "datacenter", the code seems to assume you're building new and starts prompting you for "datastore".  If, for instance, you simply are connecting to the wrong VCenter, it looks like you're required to provide "datastore" to boot an instance (which is a bit weird).  I would prefer to see an error message such as the following:
   "VM Name not found and Datastore not Provided" 
or better
   "VM Name not found, assuming new VM but Datastore not Provided."
Instead of just an error about datastore not provided.  This provides a bit more clue that it's not about missing parameters for a proper request (which is what I assumed) but that the code actually failed to find the VM and thus is assuming the request is to build a new VM.

Request:
------------
Can we get some documentation on the VMWare_Guest docs page for doing something other than Creating and Deleting VMware Guests (such as booting, rebooting and shutting down a guest)?  

A couple short examples would go a LONG way.  Between lack of documentation and the unclear return code, I ended up spending somewhere in the neighborhood of 2 - 3 hours this evening trying different things to get a server to boot only to realize that I was connecting to the wrong VCenter.

**Comment by iamkuldeepsingh** [comment]
Facing similar issue difference is I am able to make the machine power on in second attempt.
Error Message "msg": "fault.NicSettingMismatch.summary"
I even can not skip the error because it is not defined and if I define outside the function it fails before reaching there

**Comment by nerzhul** [comment]
can you try this patch please ? https://github.com/ansible/ansible/pull/24138

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by suhancz** [comment]
I'm getting the following also on Ansible 2.3.2.0 with the following playbook:

```yaml
- hosts: localhost
  tasks:
   - name: start VM
     vmware_guest:
       hostname: "{{ vsphere_IP }}"
       username: ansible@vsphere.local
       password: "{{ vsphere_password }}"
       datacenter: "{{ vsphere_datacenter }}"
       cluster: "{{ vsphere_cluster }}"
       name: "{{ vsphere_vmname }}"
       name_match: first
       uuid: "{{ vsphere_uuid }}"
       state: poweredon
       validate_certs: False
     delegate_to: localhost`
```
> fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find a matching datastore"}

Any idea what I'm doing wrong?

**Comment by dav1x** [comment]
@suhancz The only thing I can think is perhaps the uuid isn't correct or isn't locating the VM properly. I've never tested the UUID functionality. Can you try adding the folder path and using name and folder instead?

**Comment by suhancz** [comment]
I finally figured out powering machines on and off, but via the vsphere_guest module:
```
- hosts: localhost
  tasks:
    - name: start VM
      vsphere_guest:
        vcenter_hostname: "{{ vsphere_IP }}"
        username: ansible@vsphere.local
        password: "{{ vsphere_password }}"
        validate_certs: no
        guest: "{{ vsphere_vmname }}"
        state: powered_on`
```

**Comment by dagwieers** [comment]
@jctanner @Akasurde As long as people fall back to vsphere_guest, we cannot deprecate it IMO :-/

So how is it possible that **vsphere_guest** is working better than **vmware_guest** for users ?

**Comment by suhancz** [comment]
@dagwieers the issue from my side is having difficulties figuring out what path to provide for the module about the VM. While **vmware_guest** doesn't find the machine without path properly given **vsphere_guest** does. Unfortunately I'm stuck on an Ubuntu machine where 2.3 is the latest version of Ansible in the repos, so **vmware_guest_find** is not a way for me

**Comment by Akasurde** [comment]
@jeroenjacobs1205 @suhancz There is a new module called [vmware_guest_powerstate](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_powerstate.py) which manages the states of VMs. Let me know if it works for you.

**Comment by ansibot** [comment]
cc @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ZubairLK** [comment]
Something is subtly broken.

Here is what I've tried.
Get latest ansible

```
sudo pip install git+https://github.com/ansible/ansible.git@devel
```

Run vmware_facts
```
---
- name: gather vCenter facts
  hosts: localhost
  gather_facts: no
  vars:
    ansible_connection: local
  tasks:
    - vmware_vm_facts:
        hostname: 'le-sdkvcs.mipstec.com'
        username: 'administrator@vsphere.local'
        password: 'hidden'
        validate_certs: no
      register: data
    - debug: msg={{ data }}
```
I get many vms. The one I want to power on is this
```
            "mips-ubt1604-004": {
                "guest_fullname": "Ubuntu Linux (64-bit)",
                "ip_address": "",
                "mac_address": [
                    "00:50:56:ad:fe:78"
                ],
                "power_state": "poweredOff",
                "uuid": "422dfb95-aaaa-585f-2cf2-37633689b263"
            },
```

So now I use vmware_guest_powerstate in a role:

```
---
- name: Power up a VM
  vmware_guest_powerstate:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_user }}'
    password: '{{ vcenter_pass }}'
    validate_certs: no
    uuid: 422dfb95-aaaa-585f-2cf2-37633689b263
    state: powered-on
    force: true
  delegate_to: localhost
```

It runs and returns ok but doesn't power up the machine.

```
ok: [mips-ubt1604-004.mipstec.com -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "folder": "/vm",
            "force": true,
            "hostname": "le-sdkvcs.mipstec.com",
            "name": null,
            "name_match": "first",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "powered-on",
            "username": "administrator@vsphere.local",
            "uuid": "422dfb95-aaaa-585f-2cf2-37633689b263",
            "validate_certs": false
        }
    }
}
```

I can definitely find my vm using vmware_guest_find

```
---
- name: Find my VM
  vmware_guest_find:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_user }}'
    password: '{{ vcenter_pass }}'
    datacenter: 'le-sdk'
    validate_certs: no
    name: mips-ubt1604-004
  delegate_to: localhost
```

Which responds like this: 

```
ok: [mips-ubt1604-004.mipstec.com -> localhost] => {
    "changed": false,
    "folders": [
        "/vm"
    ],
    "invocation": {
        "module_args": {
            "datacenter": "le-sdk",
            "hostname": "le-sdkvcs.mipstec.com",
            "name": "mips-ubt1604-004",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false
        }
    }
}
```

So its there. But when I want to power it on using vmware_guest like this:
```
---
- name: Power up a VM
  vmware_guest:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_user }}'
    password: '{{ vcenter_pass }}'
    datacenter: 'le-sdk'
    validate_certs: no
    name: mips-ubt1604-004
    wait_for_ip_address: yes
    state: poweredon
    # disk:
    # - datastore: '{{ vm_disk.datastore }}'
  delegate_to: localhost
```

Doesn't work. 

```
fatal: [mips-ubt1604-004.mipstec.com -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "le-sdk",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "le-sdkvcs.mipstec.com",
            "is_template": false,
            "linked_clone": false,
            "name": "mips-ubt1604-004",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": null,
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    },
    "msg": "Failed to find a matching datastore"
}
```

The error message But that is because it couldn't find the VM and is now trying to make one as stated in
https://github.com/ansible/ansible/issues/22542#issuecomment-289964889

I've tried diving into the module code. Rabbit hole led me to https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py#L1512

```
    pyv = PyVmomiHelper(module)

    # Check if the VM exists before continuing
    vm = pyv.get_vm()

    # VM already exists
    if vm:
...
```

Regards,
ZubairLK
