### ISSUE TITLE
[1]  Clarify when not to use ansible_date_time 

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible#22561]
##### ISSUE TYPE

 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
setup

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### CONFIGURATION
```
fact_caching_connection = /var/tmp/facts_cache
fact_caching_timeout = 86400
```

##### SUMMARY
The variable `ansible_date_time` keeps the value from the last run. In my case it can be up to 24h old (cache), In your case, it _usually 'by default' would be a few minutes old!_ (If you run the `gather_facts` on the beginning of your PB, before you manage use, the time passes, so it would not be up-to-date.

I could not find any docs related to this behaviour except for:
https://github.com/ansible/ansible/blob/stable-2.2/docsite/rst/playbooks_variables.rst
please correct me if I'm wrong...

##### Mismatch example 1

```yaml
(venv2)ansible@hostx:~/ansible$ cat /tmp/test.yml 
- hosts: localhost
  tasks:
      - debug: var=ansible_date_time

      - debug: msg="the current date is {{ ansible_date_time.date }}"

      - shell: date
(venv2)ansible@hostx:~/ansible$ ansible-playbook /tmp/test.yml  -v


PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
ok: [localhost] => {
    "ansible_date_time": {
        "date": "2017-03-10", 
        "day": "10", 
        "epoch": "1489184403", 
        "hour": "22", 
        "iso8601": "2017-03-10T22:20:03Z", 
        "iso8601_basic": "20170310T222003714907", 
        "iso8601_basic_short": "20170310T222003", 
        "iso8601_micro": "2017-03-10T22:20:03.714985Z", 
        "minute": "20", 
        "month": "03", 
        "second": "03", 
        "time": "22:20:03", 
        "tz": "UTC", 
        "tz_offset": "+0000", 
        "weekday": "Friday", 
        "weekday_number": "5", 
        "weeknumber": "10", 
        "year": "2017"
    }
}

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": "the current date is 2017-03-10"
}

TASK [command] *****************************************************************
changed: [localhost] => {"changed": true, "cmd": "date", "delta": "0:00:00.008221",
"end": "2017-03-11 09:54:26.745700", "rc": 0, 
"start": "2017-03-11 09:54:26.737479", "stderr": "",
"stdout": "Sat Mar 11 09:54:26 UTC 2017", 
"stdout_lines": ["Sat Mar 11 09:54:26 UTC 2017"], 
"warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0 
```

##### ACTUAL RESULTS
```
ansible -m debug -a "msg={{ lookup('pipe', 'date +%Y-%m-%d-%H:%M:%s') }}" localhost;
ansible -m debug -a 'msg={{ ansible_date_time }}' localhost; 
ansible -m setup localhost; 
ansible -m shell -a 'sleep 61' localhost -e 'no_log=True' ;  #<<<<< 'no_log=True' does not work :/
ansible -m debug -a 'msg={{ ansible_date_time }}' localhost;
ansible -m debug -a "msg={{ lookup('pipe', 'date +%Y-%m-%d-%H:%M:%s') }}" localhost;
################


ansible -m debug -a "msg={{ lookup('pipe', 'date +%Y-%m-%d-%H:%M:%s') }}" localhost; ansible -m debug -a 'msg={{ ansible_date_time }}' localhost; ansible -m setup localhost; ansible -m shell -a 'sleep 61' localhost ; ansible -m debug -a 'msg={{ ansible_date_time }}' localhost ;ansible -m debug -a "msg={{ lookup('pipe', 'date +%Y-%m-%d-%H:%M:%s') }}" localhost;

localhost | SUCCESS => {
    "msg": "2017-03-13-12:54:1489406066"        ###<<< Real time!
}
localhost | SUCCESS => {
    "msg": {
        "date": "2017-03-13", 
        "day": "13", 
        "epoch": "1489405853", 
        "hour": "12", 
        "iso8601": "2017-03-13T11:50:53Z", 
        "iso8601_basic": "20170313T125053699648", 
        "iso8601_basic_short": "20170313T125053", 
        "iso8601_micro": "2017-03-13T11:50:53.699701Z", 
        "minute": "50", 
        "month": "03", 
        "second": "53", 
        "time": "12:50:53",        ###<<< The facts_cache time
        "tz": "CET", 
        "tz_offset": "+0100", 
        "weekday": "Monday", 
        "weekday_number": "1", 
        "weeknumber": "11", 
        "year": "2017"
    }
}

[setup module output visible here, no_log=True does not work]

[sleep 61 seconds]


localhost | SUCCESS => {
    "msg": {
        "date": "2017-03-13", 
        "day": "13", 
        "epoch": "1489406067", 
        "hour": "12", 
        "iso8601": "2017-03-13T11:54:27Z", 
        "iso8601_basic": "20170313T125427904407", 
        "iso8601_basic_short": "20170313T125427", 
        "iso8601_micro": "2017-03-13T11:54:27.904459Z", 
        "minute": "54", 
        "month": "03", 
        "second": "27", 
        "time": "12:54:27",         ###<<< 12:54:27 while already it is 12:55:14
        "tz": "CET", 
        "tz_offset": "+0100", 
        "weekday": "Monday", 
        "weekday_number": "1", 
        "weeknumber": "11", 
        "year": "2017"
    }
}
localhost | SUCCESS => {
    "msg": "2017-03-13-12:55:1489406130"
}

```

##### EXPECTED RESULTS
Either give a warning in the docs, that the variable is not strictly reliable, or modify the behaviour as for the `{{ ansible_managed }}` variable
For the moment, as a reliable workaround I'd recommend usage of the `{{ lookup('pipe', 'date +%Y-%m-%d-%H:%M:%s') }}`
