### ISSUE TITLE
postgresql_user unable to add role with 1 dot

### ISSUE THREAD

**Issue by indreek** [ansible/ansible#22568]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

postgresql_user

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

ubuntu 16.04
##### SUMMARY

When adding role first.last i get error 
```json
FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "db": "",
            "encrypted": false,
            "expires": null,
            "fail_on_user": true,
            "login_host": "",
            "login_password": "",
            "login_unix_socket": "",
            "login_user": "postgres",
            "no_password_changes": false,
            "password": null,
            "port": "5432",
            "priv": null,
            "role_attr_flags": "",
            "state": "present",
            "user": "first.last"
        },
        "module_name": "postgresql_user"
    },
    "msg": "PostgreSQL does not support role with more than 1 dots"
}
```
##### STEPS TO REPRODUCE

```yaml
- name: add roles
  postgresql_user: user=first.last
  become: yes
  become_user: postgres
  tags:
    - add_pg_roles
```

##### ACTUAL RESULTS

```

```
