### ISSUE TITLE
cs_staticnat fails on second execution

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#22565]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cs_staticnat

##### ANSIBLE VERSION

```
2.2.1.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Trying to assign an ip with `cs_staticnat` to a network in VPC (I don't know if it plays a role), the
first time works out fine. On the second execution one gets:

> Unable to enable static nat for the ipAddress ... as ip is not associated with any network

##### STEPS TO REPRODUCE

Execute the following task multiple times

```yaml

- name: assign primary nat IPs
  cs_staticnat:
    zone: "MyZone"
    network: "MyNetwork"
    api_region: "MyRegion"
    ip_address: "MyAlreadyAcquiredIP"
    vm: "MyVM"
```

##### EXPECTED RESULTS
First time: `changed`
Second time : `ok`

##### ACTUAL RESULTS
- On the first execution I get: `changed` and the IP address is assigned
- On the second execution I get: 

```
failed: ...
"msg": "CloudStackException: ('HTTP 431 response from CloudStack', <Response [431]>, {u'errorcode': 431, u'uuidList': [], u'cserrorcode': 4350, u'errortext': u'Unable to enable static nat for the ipAddress id=2816 as ip is not associated with any network and no networkId is passed in'})

```
and the StaticNAT  is not there anymore

- On the third execution same result as on the first execution

I suppose there is some error in Logic if state has not changed
