### ISSUE TITLE
Execution of junos galaxy modules hangs in junos action handler after #22423

### ISSUE THREAD

**Issue by stacywsmith** [ansible/ansible#22589]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lib/ansible/plugins/action/junos.py

##### ANSIBLE VERSION
```
user@h0:~/Automation/Projects/Ansible$ ansible --version
ansible 2.3.0 (devel 07674a8446) last updated 2017/03/13 17:48:23 (GMT -600)
  config file = /media/sf_Automation/Projects/Ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION
```
user@h0:~/Automation/Projects/Ansible$ more ansible.cfg 
[defaults]
forks = 1
gathering = explicit
hash_behaviour = merge
inventory = ./inventory
log_path = ~/.ansible/log/ansible.log
retry_files_save_path = ~/.ansible/retry
roles_path = ./roles
host_key_checking = False
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
After #22423, the junos action handler attempts to import the module which is about to be executed in order to see if `USE_PERSISTENT_CONNECTION` is set:
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/junos.py#L50-L52

Unfortunately, the junos galaxy modules are poorly written and attempt to execute upon import (this will be addressed in those modules). Executing the junos galaxy module in this context leads to a problem reading stdin and `sys.exit(1)` being called.
https://github.com/ansible/ansible/blob/374d491ba5f9c4b52fc15544f563abcb490fc81a/lib/ansible/module_utils/basic.py#L608-L613

Exiting the process which is executing the junos action handler causes playbook execution to hang indefinitely.

##### STEPS TO REPRODUCE
```
user@h0:~/Automation/Projects/Ansible$ ansible-playbook -vvvv --limit r0 playbooks/galaxy/facts.pb.yaml 
Using /media/sf_Automation/Projects/Ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /media/sf_Automation/Projects/Ansible/Repos/stacywsmith/ansible/lib/ansible/plugins/callback/__init__.pyc
Loading callback plugin jsnapy of type aggregate, v2.0 from /media/sf_Automation/Projects/Ansible/Repos/stacywsmith/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: facts.pb.yaml ********************************************************************************************************************
1 plays in playbooks/galaxy/facts.pb.yaml

PLAY [Get facts from Junos routers using the galaxy module] ********************************************************************************
META: ran handlers

TASK [Get Junos Facts] *********************************************************************************************************************
task path: /media/sf_Automation/Projects/Ansible/playbooks/galaxy/facts.pb.yaml:9

{"msg": "Error: Module unable to decode valid JSON on stdin.  Unable to figure out what parameters were passed", "failed": true}
^C [ERROR]: User interrupted execution
```

```yaml
---
- name: Get facts from Junos routers using the galaxy module
  hosts: junos-all
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  tasks:
    - name: Get Junos Facts
      junos_get_facts:
        host: "{{ inventory_hostname }}"
        user: "user"
        passwd: "user123"
      register: response
    - name: Print Facts
      debug:
        var: response.facts
```

##### EXPECTED RESULTS
Playbook executes without failure.

##### ACTUAL RESULTS
See above.
