### ISSUE TITLE
Copy module doesn't work when dest host is localhsot 

### ISSUE THREAD

**Issue by akaradzha** [ansible/ansible#22597]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module: copy

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

copy module unable to locate src or dest when host is localhost (for test purpose)

**hosts** file:
localhost
[target]
localhost         ansible_connection=local

##### STEPS TO REPRODUCE

```yaml
- name: Upload the new build
    copy:
      scr: '{{item.src}}'
      dest: '{{item.dest}}'
    with_items:
      - {src: '{{dir.src.backup}}/app-{{version}}.zip', dest: '{{dir.dest.tmp}}/app-{{version}}.zip'}
      - {src: '{{dir.src.backup}}/moxiemanager-{{version}}.zip', dest: '{{dir.dest.tmp}}/moxiemanager-{{version}}.zip'}
```

##### EXPECTED RESULTS

copy files from src to dest 
##### ACTUAL RESULTS

task failed

```
failed: [localhost] (item={u'dest': u'/home/dre/insign/tmp/app-master-latest.zip', u'src': u'/home/dre/workspace/online-kiosk/devops/ansible/artifacts/app-master-latest.zip'}) => {"failed": true, "item": {"dest": "/home/dre/insign/tmp/app-master-latest.zip", "src": "/home/dre/workspace/online-kiosk/devops/ansible/artifacts/app-master-latest.zip"}, "msg": "src (or content) and dest are required"}
failed: [localhost] (item={u'dest': u'/home/dre/insign/tmp/moxiemanager-master-latest.zip', u'src': u'/home/dre/workspace/online-kiosk/devops/ansible/artifacts/moxiemanager-master-latest.zip'}) => {"failed": true, "item": {"dest": "/home/dre/insign/tmp/moxiemanager-master-latest.zip", "src": "/home/dre/workspace/online-kiosk/devops/ansible/artifacts/moxiemanager-master-latest.zip"}, "msg": "src (or content) and dest are required"}

```
