### ISSUE TITLE
Archive module doesn't support 'with_items'

### ISSUE THREAD

**Issue by akaradzha** [ansible/ansible#22595]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module: archive 

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

archive module doesn't support 'with_items'
##### STEPS TO REPRODUCE

```yaml
 - archive:
      path: '{{item.path}}'
      dest: '{{item.dest}}'
      format: zip
   with items:
      - {path: '{{dir.src.app}}/target/universal', dest: '{{dir.src.backup}}/{{version}}.zip'}
      - {path: '{{dir.src.moxiemanager}}', dest: '{{dir.src.backup}}/moxiemanager-{{version}}.zip'}
```

##### EXPECTED RESULTS

make two separate archives
##### ACTUAL RESULTS

Task Failed: "'with items' is not a valid attribute

```
fatal: [localhost]: FAILED! => {"failed": true, "reason": "'with items' is not a valid attribute for a Task\n\nThe error appears to have been in '/home/dre/workspace/online-kiosk/devops/ansible/roles/deploy/tasks/pre_deploy_build.yml': line 9, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: Archive the application and moxiemanager\n    ^ here\n"}

```

**Comment by ansibot** [comment]
cc @bendoh
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

Your indentation is wrong, `with_` is a 'task level directive' not part of the module options. If you outdent to the task level it should work fine.
```
- archive:
      path: '{{item.path}}'
      dest: '{{item.dest}}'
      format: zip
  with_items:
    - {path: '{{dir.src.app}}/target/universal', dest: '{{dir.src.backup}}/{{version}}.zip'}
    - {path: '{{dir.src.moxiemanager}}', dest: '{{dir.src.backup}}/moxiemanager-{{version}}.zip'}
```

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
