### ISSUE TITLE
Docker containers always redeployed when security_opts are specified

### ISSUE THREAD

**Issue by cawilliamson** [ansible/ansible#22606]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
security_opts:
    - "apparmor:unconfined"
    - "seccomp:unconfined"
```

##### OS / ENVIRONMENT
Ubuntu 16.04.2

##### SUMMARY
When security_opts are specified the docker container is always rebuilt with the config:

```
- name: deploy gitlab
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce
    state: started
    restart_policy: always
    security_opts:
    - "apparmor:unconfined"
    - "seccomp:unconfined"
```

##### STEPS TO REPRODUCE
```
1.) Create a playbook with the following content:

---
- name: deploy gitlab
  docker_container:
    name: gitlab
    image: gitlab/gitlab-ce
    state: started
    restart_policy: always
    security_opts:
    - "apparmor:unconfined"
    - "seccomp:unconfined"

2.) Run the playbook (container is built as expected!)

3.) Run the playbook again (container is re-built - not expected.)
```
