### ISSUE TITLE
Add daemon_reload as a systemd state

### ISSUE THREAD

**Issue by Fale** [ansible/ansible#22612]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
lib/ansible/modules/system/systemd.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
There is no "easy" way to trigger a systemd daemon reload without reloading or restarting a daemon.

##### STEPS TO REPRODUCE
```yaml
    - name: Reload systemd daemons. Not cleanest way thought
      systemd:
        state: daemon_reloaded
```

or

```yaml
    - name: Reload systemd daemons. Not cleanest way thought
      systemd:
        daemon_reload: True
```

##### EXPECTED RESULTS
`systemd daemon-reload` to be executed on target hosts
