### ISSUE TITLE
IOS_CONFIG offline

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible/ansible#22619]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

IOS_CONFIG
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ntc/ansible-modules/']
  python version = 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]

```

##### OS / ENVIRONMENT

Ubuntu 
python virtual env for 2.3
##### SUMMARY

Offline mode is not working in 2.3, updates from src is not working in 2.2. 

##### STEPS TO REPRODUCE

```yaml
---

- name: TEST OFFLINE
  hosts: all
  connection: local
  gather_facts: no
  strategy: free


  tasks:

    - name: TEST OFFLINE CONFIG
      ios_config:
        host: "{{ inventory_hostname }}"
        src: 'orig.cfg'
        config: "{{ lookup('file', './new.cfg' ) }}"
      register: "test_update"
      check_mode: true

    - name: debug
      debug:
        var: "test_update"

```

##### EXPECTED RESULTS

No connection tried, shows updates intended to push. 

##### ACTUAL RESULTS

In 2.3 the ios_module error's out with `unable to open shell`. In 2.2 it does not show updates. 

```
(ansible2.3) ken@kcelenza-ubuntu:/github/ntc-temp/ansible-playbooks$ ansible-playbook -i inventory version3.yml --limit=ios-sw1

PLAY [TEST OFFLINE] **********************************************************************************************************************************************************************************************

TASK [TEST OFFLINE CONFIG] ***************************************************************************************************************************************************************************************
fatal: [ios-sw1]: FAILED! => {"changed": false, "failed": true, "msg": "unable to open shell", "rc": 255}

PLAY RECAP *******************************************************************************************************************************************************************************************************
ios-sw1                    : ok=0    changed=0    unreachable=0    failed=1

(ansible2.3) ken@kcelenza-ubuntu:/github/ntc-temp/ansible-playbooks$ workon ansible2.2
(ansible2.2) ken@kcelenza-ubuntu:/github/ntc-temp/ansible-playbooks$ ansible-playbook -i (ansible2.2) ken@kcelenza-ubuntu:/github/ntc-temp/ansible-playbooks$ ansible-playbook -i inventory version3.yml --limit=ios-sw1

PLAY [TEST OFFLINE] ************************************************************

TASK [TEST OFFLINE CONFIG] *****************************************************
changed: [ios-sw1]

TASK [debug] *******************************************************************
ok: [ios-sw1] => {
    "test_update": {
        "changed": true,
        "warnings": []
    }
}

PLAY RECAP *********************************************************************
ios-sw1                    : ok=2    changed=1    unreachable=0    failed=0



```

pinging @privateip @gundalow @rcarrillocruz  just in case bot misses.
