### ISSUE TITLE
slow ansible-playbook commands with dynamic inventory

### ISSUE THREAD

**Issue by nareshku** [ansible/ansible#22633]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
dynamic inventory

##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

[defaults]
inventory      = /etc/ansible/abc_inventory
forks          = 500
sudo_user      = ***
ask_sudo_pass  = False
ask_pass       = False
force_color    = 1
gathering = explicit
host_key_checking = False
notification_callback = somejsonfile
callback_whitelist = profile_tasks
timeout = 30
log_path = /var/log/ansible.log
private_key_file = ****
deprecation_warnings = False
command_warnings = False
callback_plugins    = /etc/ansible/plugins/callback/:/usr/share/ansible_plugins/callback_plugins
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
retries = 5
ssh_args = -o ControlMaster=auto -o ControlPersist=2h
pipelining = True
[accelerate]
[selinux]

##### OS / ENVIRONMENT

Redhat

##### SUMMARY

ansible playbook runs really slow with dynamic inventory.

With static inventory takes about 6s.

Same task with dynamic inventory takes about:
real    0m56.844s
user    0m38.109s
sys     0m12.441s

Time take for the dynamic inventory to return data is shown below:
time python inventory.py --list
real    0m1.163s
user    0m0.145s
sys     0m0.051s

Dynamic inventory includes 3 groups and with empty "_meta": {}, has about 300 hosts.

**Comment by jctanner** [comment]
@nareshku please provide an example playbook/task

needs_info

**Comment by nareshku** [comment]
@jctanner Thanks for responding. Below is the playbook
```
# playbook to sync some files across all hosts

- hosts: "group1-{{ dc }},group2-{{ dc }}"
  tasks:
    - file: path=path state=directory owner=user group=group mode=0755 recurse=yes
      become_user: root
      become_method: sudo
      become: true
    - name: sync some files
      synchronize:
        dest: "path"
        src: "src_path"
        mode: push
        recursive: true
        rsync_opts:
          - "--exclude=*.swp"
          - "--exclude=*.pyc"
```
once play book command is ran, it spends a lot of time on below line and the actual play execution is faster.
ansible-playbook -v path_to_playbook -i path_to_dynamic_inventory -e "dc=abc"
Using /etc/ansible/ansible.cfg as config file
