### ISSUE TITLE
docker_image task with archive_path loads an full image to a memory

### ISSUE THREAD

**Issue by KORPSE** [ansible/ansible#22638]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_image

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT
N/A
##### SUMMARY
Executing a task of archiving docker image to tar-file completely loads it into memory before writing to HDD. It could result with out-of-memory error if image is bigger than available amount of memory.
It looks like for some reasons request goes not in a streaming way in this line https://github.com/ansible/ansible-modules-core/blob/d749ec91e513c40a50b539a7eaccf29c31dda4d4/cloud/docker/docker_image.py#L399
Maybe it is because of outdated version of requests-library or wrong usage of it?

##### STEPS TO REPRODUCE
1. Create a task like the below one.
```yaml
- delegate_to: localhost
  docker_image:
    name: "gcc" #size is ~1.5GB
    tag: latest
    pull: yes
    force: yes
    archive_path: "/tmp/gcc.tar"
```
2. Run htop to see the actual memory usage.
3. Run `ansible-playbook` for this task on a machine with 1GB memory.

##### EXPECTED RESULTS
Image is downloaded to tar archive on HDD.

##### ACTUAL RESULTS
Fatal error ```"msg": "Error writing image archive /tmp/gcc.tar - "``` error
Memory usage increases due to overflow.
