### ISSUE TITLE
vmware_guest_snapshot don't find vm if not folder is specified

### ISSUE THREAD

**Issue by ikkaro** [ansible/ansible#22644]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest_snapshot

##### ANSIBLE VERSION

```
ansible 2.3.0
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

ArchLinux

##### SUMMARY

If you want to take a snapshot from a VM without specify the vm folder is not possible.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: "vc"
      prompt: "Enter Virtual Center Server"
      default: "XXXX"
      private: no

    - name: "vc_user"
      prompt: "Enter Virtual Center Username"
      default: "DDDD"
      private: no
      
    - name: "vc_passwd"
      prompt: "Enter Virtual Center Password"
      private: yes

  tasks:
    - name: Take vmware snapshot
      vmware_guest_snapshot:
        hostname: "{{ vc }}"
        username: "{{ vc_user }}"
        password: "{{ vc_passwd }}"
        datacenter: "DDCC"
        validate_certs: False
        name: "srv-blah-blah"
        state: present
        snapshot_name: snap1

```

##### EXPECTED RESULTS

A snapshot should be created.

##### ACTUAL RESULTS

The VM is not found. The module is searching the VM in the path /vm, it should search the VM in all the datacenter.

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "datacenter": "DDCC",
            "description": "",
            "folder": "/vm", <-----------------------------------
            "hostname": "XXXX",
            "name": "srv-blah-blah",
            "name_match": "first",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "snapshot_name": "snap1",
            "state": "present",
            "username": "DDDD",
            "uuid": null,
            "validate_certs": false
        }
    },
    "msg": "Unable to manage snapshots for non-existing VM srv-blah-blah"```
```

**Comment by ansibot** [comment]
cc @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
@ikkaro you passed in "datacenter: DDCC". Is the VM not in that datacenter?

needs_info

**Comment by ikkaro** [comment]
@jctanner the VM is inside DDCC, but is not found.
In this way the VM is found, and the snap is taken.
```- name: Take vmware snapshot
      vmware_guest_snapshot:
        hostname: "{{ vc }}"
        username: "{{ vc_user }}"
        password: "{{ vc_passwd }}"
        datacenter: "DDCC"
        validate_certs: False
        name: "srv-blah-blah"
        state: present
        snapshot_name: snap1
        folder: "/my_vm_folders"
```
In this way the VM is not found:
 ```- name: Take vmware snapshot
      vmware_guest_snapshot:
        hostname: "{{ vc }}"
        username: "{{ vc_user }}"
        password: "{{ vc_passwd }}"
        datacenter: "DDCC"
        validate_certs: False
        name: "srv-blah-blah"
        state: present
        snapshot_name: snap1
```

**Comment by nerzhul** [comment]
@ikkaro with 2.3 maintainers, including myself talked about the magic finding VM instead of getting the right object because of many performances issues due to magic finding, and we removed the non folded VM support

**Comment by ikkaro** [comment]
I can't imagine the problem the magic finding. As you know i've tried this code (i know is small compared to your libs etc...) but it just works and quickly, and i don't see the real performance issue. I've tested this in an environment with about 1100VMs.
```
def get_obj(content, vimtype, name):
    obj = None
    container = content.viewManager.CreateContainerView(
        content.rootFolder, vimtype, True)
    for c in container.view:
        if c.name == name:
            obj = c
            break
    return obj

def main():
    args = get_args()

    serviceInstance = SmartConnectNoSSL(
            host=args.host,
            user=args.user,
            pwd=args.password,
            port=args.port)
    atexit.register(Disconnect, serviceInstance)

    vm = None
    content = serviceInstance.RetrieveContent()
    vm = get_obj(content, [vim.VirtualMachine], args.vm_name)

    if vm:
        print("VM found")
    else:
        print ("VM not found")
    print(vm)

if __name__ == "__main__":
    main()
```

**Comment by jctanner** [comment]
@ikkaro how would you revise that code when there are two VMs with the same name?

**Comment by ikkaro** [comment]
@jctanner , you're right, you need some other attribute like the path.

**Comment by mike45379** [comment]
Without the magic finding, the module would be really difficult to reuse, you'd have to maintain variables for the folder where your VM is and I'm not sure how you'd do that programmatically.  Perhaps if ansible_facts returned a VMware ID, it might be easier.

If you get two VMs with the same name, fail the task and prompt the user to folder: in order to narrow it down.

**Comment by ikkaro** [comment]
@mike45379 it's an ugly solution but i've created a variable named "vm_folder" in my node definition file. On the other hand, maybe with the vmware inventory script you can get the vm folder, just an idea i need to try.

**Comment by mike45379** [comment]
@ikkaro For me personally, my VM folder structure on my newer environments is designed in a way that I can work around this since I'm using a flat structure where the folder is <datacenter>/vms/<service_name> and then I set a service_name variable in host or group vars that I use to find it.  Since I'll need the service_name var elsewhere it's not a lot of extra work.

My legacy VMs and Templates structure is not designed that way, so I'm just correcting it as I go.  If I was still using that structure extensively I'd have a real big problem on my hands.  Still, thanks for the workaround, I'm sure it will help some others with the same problem.

A really elegant solution would be if ansible could pull a vmware_id when it gathers facts and then we could pass that to the snapshot function, but I'm not sure if that's even technically possible.  I'd be real happy to just call it by name and have it fail if it finds two with the same name.

**Comment by fdutheil** [comment]
Hello,
We had to deal with an inconsistent "Folders" tree here too, so using UUID was mandatory. The good point is that getting it from ansible is pretty easy: ansible_product_uuid contains the UUID from the BIOS of a machine, which is where VMware actually put the VM's UUID. Lucky isn't it? Oh, and don't forget to apply the lower() filter to it before passing it to vmware_guest_snapshot.
Works like a charm here (provided the VMware guests are up, of course).

**Comment by rgarrow** [comment]
Hi Guys and Gals if there are any, thank goodness for Kai Stian Olstad in the Ansible Forums as after weeks if issues with this module he pointed me to this. I am still trying to understand how to do. My structure of how we have our DC setup is Datacenter > Cluster > resource group (default)> we do not use folders I am able to pull the VM name vm guest by doing name: "{{ ansible_hostname }}" and it pull the name. I am have the exact issue you are talking about. Fduthell mention using lower() filter on UUID not sure how to do it. Any help would be greatly appreciated.

**Comment by rgarrow** [comment]
Hi all,
I got it to work thanks for the help I will post my results 

```yaml
---
   - hosts: all
     tasks:
     - name: Create Snapshot
       vmware_guest_snapshot:
         datacenter: Development
         hostname: virtual server name
         folder: /DVT-UX
         username: John doe
         password: xxxxxx
         name: "{{ ansible_hostname }}"
         uuid: "{{ ansible_product_uuid | lower }}"
         state: present
         snapshot_name: test1
         description: patch_snapshot
         validate_certs: false
       delegate_to: localhost
```

This does work I have confirmed it.
