### ISSUE TITLE
apt_key returns 403 Forbidden when downloading OpenVPN GPG key

### ISSUE THREAD

**Issue by chroche** [ansible/ansible#22647]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apt_key

##### ANSIBLE VERSION
```
ansible 2.3.0 (devel 34498590e3) last updated 2017/03/15 14:07:26 (GMT +100)
  config file = /Users/chris/Git/edw-poc/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
apt_key fails when trying to download GPG key from OpenVPN web site:
```
fatal: [host]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download key at https://swupdate.openvpn.net/repos/repo-public.gpg: HTTP Error 403: Forbidden"}
```

##### STEPS TO REPRODUCE
The following task triggers the error:
```yaml
- name: Add OpenVPN gpg key
  become: yes
  apt_key:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    state: present
```

##### EXPECTED RESULTS
Key is downloaded and added to the APT GPG public keyring

##### ACTUAL RESULTS
The HTTP GET request is rejected by CloudFlare based on the value of the User Agent header:
```bash
$ curl -v -A 'Python-urllib/2.6' https://swupdate.openvpn.net/repos/repo-public.gpg
* Connected to swupdate.openvpn.net (104.20.194.50) port 443 (#0)
[...]
> GET /repos/repo-public.gpg HTTP/1.1
> Host: swupdate.openvpn.net
> User-Agent: Python-urllib/2.6
> Accept: */*
>
< HTTP/1.1 403 Forbidden
< Server: cloudflare-nginx
< CF-RAY: 34002af2ce952999-DUB
[...]
<head>
<title>Access denied | swupdate.openvpn.net used Cloudflare to restrict access</title>
```
whereas with another User Agent:
```bash
$ curl -v https://swupdate.openvpn.net/repos/repo-public.gpg
* Connected to swupdate.openvpn.net (104.20.195.50) port 443 (#0)
[...]
> GET /repos/repo-public.gpg HTTP/1.1
> Host: swupdate.openvpn.net
> User-Agent: curl/7.47.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: cloudflare-nginx
< CF-RAY: 34002a613dc0299f-DUB
[...]
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1
[...]
```
##### NOTES

A simple fix would be to allow to set the default User Agent string globally. Notably an [ old commit](https://github.com/ansible/ansible/commit/9730157525c8cd539c2f657f40c34b73bb189e44#diff-b77962b6b54a830ec373de0602918318) submitted 3 years ago did exactly that but was reversed shortly after for whatever reason.

I'm currently patching my stable-2.2 version as follows to work around the error:
```diff
--- lib/ansible/module_utils/urls.py    2017-03-15 14:44:54.000000000 +0000
+++ lib/ansible/module_utils/urls.py.fixed      2017-03-15 14:03:06.000000000 +0000
@@ -978,7 +978,7 @@

     username = module.params.get('url_username', '')
     password = module.params.get('url_password', '')
-    http_agent = module.params.get('http_agent', None)
+    http_agent = module.params.get('http_agent', 'Ansible/2.2')
     force_basic_auth = module.params.get('force_basic_auth', '')

     follow_redirects = module.params.get('follow_redirects', 'urllib2')
```

**Comment by ansibot** [comment]
cc @jvantuyl
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dylan4224** [comment]
+1, same error here

**Comment by dylan4224** [comment]
Thanks @chroche 
after adding `http_agent = module.params.get('http_agent', 'Ansible/2.4')`, this issue resolved

**Comment by chroche** [comment]
Note: another workaround, that doesn't require meddling with the Ansible source code, is to download the key from a GPG key server:
```yaml
- name: Add OpenVPN GPG key
  become: yes
  apt_key:
    id: 8E6DA8B4E158C569
    keyserver: hkps.pool.sks-keyservers.net
    state: present
```

**Comment by bau-sec** [comment]
Another workaround: use url_get to retrieve the key (it adds a user-agent header, unlike apt_key)
```
get_url: 
  url: https://swupdate.openvpn.net/repos/repo-public.gpg
  dest: /tmp/openvpn.gpg
apt_key:
    file: /tmp/openvpn.gpg
    state: present
```

Based on the behavior of get_url, it looks like it would be more consistent for apt_key to add a user-agent header rather than omitting it as currently implemented.
