### ISSUE TITLE
Blockinfile using |2 for indentation issue with marker

### ISSUE THREAD

**Issue by pboesch** [ansible/ansible#22668]
Hello,

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/tek/depots/ansible/ansible.cfg
  configured module search path = ['library']

```

##### CONFIGURATION

Nothing special

##### OS / ENVIRONMENT
Ansible running from Debian/ArchLinux, managing a FreeBSD server, seems not to be specific of distribution.

##### SUMMARY
When I used blockinfile with content |2 * to indent configuration and personnal 'marker', whenever I started playbook with called this blockinfile, the block is added. 

**Without specific 'marker',** task works normally.

* see: http://stackoverflow.com/a/41615336

##### STEPS TO REPRODUCE
```yaml
- name: blockinfile with |2
  blockinfile:
    dest: /etc/login.conf
    insertafter: "^default:\\\\$"
    marker: "# example"
    content: |2
              :charset=UTF-8:\
              :lang=fr_FR.UTF-8:\

```
In role or playbook, it does not matter.

##### EXPECTED RESULTS
I expect normal behavior of blockinfile

##### ACTUAL RESULTS
Launch task and you will see every time:
```
TASK [base : blockinfile with |2] **********************************************
changed: [freebsd]
```
And in dest file:
```
default:\
# example
        :charset=UTF-8:\
        :lang=fr_FR.UTF-8:\
# example
        :charset=UTF-8:\
        :lang=fr_FR.UTF-8:\
# example

[...] and more: depending of how many times you run the taks
```
Can you reproduce this issue ?

Thanks in advance
