### ISSUE TITLE
Ignores Variable during Playbook execution

### ISSUE THREAD

**Issue by littleprivate** [ansible/ansible#22688]
##### ISSUE TYPE
 - Bug Report
 

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### SUMMARY
Variable "ansible_winrm_server_cert_validation: ignore" is ignored in the playbook

##### STEPS TO REPRODUCE

```
  vars:
    - ansible_user: "{{ ad_user }}"
    - ansible_password: "{{ ad_pass }}"
    - ansible_port: 5986
    - ansible_connection: winrm
    - ansible_winrm_server_cert_validation: ignore

```

##### EXPECTED RESULTS
use the "ansible_winrm_server_cert_validation" - Variable from the playbook

##### ACTUAL RESULTS
```
TASK [Gathering Facts] ***********************************************************************************************************************************************
fatal: [<SYSTEMNAME>]: UNREACHABLE! => {"changed": false, "msg": "kerberos: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590), ssl: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)", "unreachable": true}
```
