### ISSUE TITLE
Request for cron env variable dependencies

### ISSUE THREAD

**Issue by unode** [ansible/ansible#22699]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

`cron`

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

As of version 2.2 the `cron` module does **not** allow creating the following `cron` content:

```
MAILTO="foo@example.com"
0 0 * * * /bin/uname

MAILTO="foo@example.com,bar@example.com"
0 1 * * * /bin/hostname
```

The options `insertbefore` and `insertafter` exist but they target variable names, and not cron names.
This also restricts the use of variables. For instance, it's not possible to define the same variable more than once in the same crontab.

Therefore, the following doesn't work (`<===` highlights the modified lines):

```
- hosts: target
  tasks:
      - cron:
          name: MAILTO
          env: yes
          value: "foo@example.com"
          insertbefore: "Cleanup"            <===

      - cron:
          name: "Cleanup"
          minute: "0"
          hour: "0"
          job: "/opt/bin/cleanup"

      - cron:
          name: MAILTO
          env: yes
          value: "foo@example.com,bar@example.com"
          insertbefore: "Test"               <===

      - cron:
          name: "Test"
          minute: "0"
          hour: "0"
          job: "/opt/bin/test"

```

Another slightly more flexible possibility could be:

```
- hosts: target
  tasks:
      - cron:
          name: "Mail foo"                   <===
          var: MAILTO                        <===
          env: yes
          value: "foo@example.com"

      - cron:
          name: "Cleanup"
          minute: "0"
          hour: "0"
          job: "/opt/bin/cleanup"
          insertafter: "Mail foo"            <===

      - cron:
          name: "Mail foo & bar"             <===
          var: MAILTO                        <===
          env: yes
          value: "foo@example.com,bar@example.com"

      - cron:
          name: "Test"
          minute: "0"
          hour: "0"
          job: "/opt/bin/test"
          insertafter: "Mail foo & bar"      <===

```
This allows multiple cron entries to depend on an environment variable.
Multiple variables could be defined by cascading dependencies:
```
- hosts: target
  tasks:
      - cron:
          name: "Mail binary"                <===
          var: PATH                          <===
          env: yes
          value: "/bin:/usr/bin"

      - cron:
          name: "Mail foo"                   <===
          var: MAILTO                        <===
          env: yes
          value: "foo@example.com"
          insertafter: "Mail binary"         <===

      - cron:
          name: "Cleanup"
          minute: "0"
          hour: "0"
          job: "/opt/bin/cleanup"
          insertafter: "Mail foo"            <===

      - cron:
          name: "Mail foo & bar"             <===
          var: MAILTO                        <===
          env: yes
          value: "foo@example.com,bar@example.com"
          insertafter: "Mail binary"         <===

      - cron:
          name: "Test"
          minute: "0"
          hour: "0"
          job: "/opt/bin/test"
          insertafter: "Mail foo & bar"      <===

```

resulting in:

```
#Ansible: Mail binary
PATH="/bin:/usr/bin"
#Ansible: Mail foo
MAILTO="foo@example.com"
#Ansible: Cleanup
0 0 * * * /opt/bin/cleanup
(... additional jobs depending on "Mail foo")

#Ansible: Mail foo & bar
MAILTO="foo@example.com,bar@example.com"
#Ansible: Test
0 0 * * * /opt/bin/test
(...)
```
