### ISSUE TITLE
[branch?] file.set_context_if_different() crashes with IndexError

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#227]
file.set_context_if_different() contains this code:

```
for i in range(len(context)):
    if context[i] is not None and context[i] != cur_context[i]:
```

On my box `context` looks like this:

```
[None, None, None, u's0']
```

And `cur_context` looks like this:

```
[u'user_u', u'object_r', u'etc_t']
```

Point being that `cur_context[3]` doesn't exist, so it crashes with `list index out of range`.  I don't know anything about SELinux, so I have no idea what these mean or what the fix is.  Incidentally, this error is _not_ bubbled up to the user, so I just get an 'unreachable' error with a dict that looks like everything is fine.

**Comment by mpdehaan** [comment]
assigning to sfromm who wrote the SELinux module.

Including the line from your playbook would be helpful in understanding what you are doing.

**Comment by jkleint** [comment]
Sure; nothing special:

```
---
- hosts: box
  sudo: True
  tasks: 
  - name: Copy yum local.repo to /etc/yum.repos.d
    action: copy src=local.repo dest=/etc/yum.repos.d/local.repo owner=root group=root mode=0644
```
