### ISSUE TITLE
Mount module src=LABEL={{ disk_label }} syntax improvement

### ISSUE THREAD

**Issue by kees-closed** [ansible/ansible#22702]
Hi,

The syntax of the mount module is a bit odd. For instance in the documentation it's shown like this:
```
- name: Mount up device by label
  mount:
    path: /srv/disk
    src: LABEL=SOME_LABEL
    fstype: ext4
    state: present
```
I want to use this module in one line, like this:
`mount: path=/srv/git src="LABEL=git" fstype=ext4 opts=defaults,noatime state=mounted`

But the LABEL syntax prohibits this. Could this be improved somehow? Or am I doing something wrong here?
