### ISSUE TITLE
vmware_guest: default resource_pool vs vapp

### ISSUE THREAD

**Issue by stroobl** [ansible/ansible#22706]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = ... /inventory/test/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I've been testing the vmware_guest module with Ansible 2.3 and noticed a discrepancy between the docs an my results. According to the docs, resource_pool seems to be optional:
resource_pool (added in 2.3)
required:	no default: None 		
"Affect machine to the given resource pool
Resource pool should be child of the selected host parent"
We don't have resource pools configured, but when I don't include resource_pool when creating a guest from a template, the guest is apparently assigned to a random vapp on our setup (vmware 5.5).

##### STEPS TO REPRODUCE
Create a guest on a VMware env with no resource pools configured and one or more vapps with the task below:
```
- name: create vm from template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vmware_admin_user }}"
    password: "{{ vmware_admin_pass }}"
    validate_certs: no
    datacenter: "{{ vm_datacenter }}"
    cluster: "{{ vm_cluster }}"
    name: "{{ inventory_hostname|upper }}"
    state: "{{ vm_state }}"
    guest_id: "{{ vm_guest_id }}"
    template: "{{ vm_template_src }}"
    folder: "{{ vm_folder }}"
    annotation: "{{ vm_notes }}"
  connection: local
  register: created
```

##### EXPECTED RESULTS
The VM should be created without a specific vapp/resource pool configured.

##### ACTUAL RESULTS
VM is assigned to a random(?) vapp.

To create the VM in the normal state, I had to add resource_pool: Resources to the above task.
