### ISSUE TITLE
Using include asynchronously with with_items

### ISSUE THREAD

**Issue by fasterfish** [ansible/ansible#22716]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

i don't know

##### ANSIBLE VERSION

```
2.2.1.0
```

##### OS / ENVIRONMENT

Ubuntu 14.0.4 amd64

##### STEPS TO REPRODUCE

I want to play the task list asynchronously for several group vars.

```yaml
tasks:
- include: sync.yml
  async: 1000
  poll: 0
  with_items: "{{groups['groupname']}}"
  loop_control:
    loop_var: variable
```

##### EXPECTED RESULTS

The task list executed asynchronously.

##### ACTUAL RESULTS

The task list is executed in sequence for each variable.
