### ISSUE TITLE
Vault variables undefined when using delegate_to

### ISSUE THREAD

**Issue by orgito** [ansible/ansible#22737]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- vault
- delegate_to

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel b90517caf9) last updated 2017/03/17 09:57:43 (GMT -200)
  config file = /home/renato/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
```
[defaults]
inventory = ~/ansible/hosts
host_key_checking = False
remote_user = root
forks = 15
roles_path = ~/ansible/roles
filter_plugins  = ~/ansible/plugins/filter_plugins
gathering = smart
fact_caching = jsonfile
fact_caching_connection = /tmp/ansiblefactscache
fact_caching_timeout = 86100
vault_password_file = ~/ansible/.vault-passwd.sh

[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
control_path = %(directory)s/ansible-ssh-%%C
pipelining = True
```

##### OS / ENVIRONMENT
Fedora 25

##### SUMMARY
Ansible fails when using delegate_to in a playbook when a vault variable is needed. If ansible_user or ansible_password are defined in a vault it always fails when the variable is not defined in the original host.

##### STEPS TO REPRODUCE
host_vars for mylinuxserver:
```yaml
ansible_user: "{{ vault_ansible_user }}"
ansible_password: "{{ vault_ansible_password }}"
ansible_port: 5986
ansible_connection: winrm
ansible_winrm_server_cert_validation: ignore
```

playbook
```yaml
---
- hosts: mylinuxserver
  gather_facts: yes

  vars:
    primary: mywindowsserver

  tasks:
  # any task
  - debug: msg="any task here"
    delegate_to: "{{ primary }}"
```

##### EXPECTED RESULTS
The playbook should execute without problemas

##### ACTUAL RESULTS
```
Using /home/renato/.ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /home/renato/git/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: teste.yml ***********************************************************************************************************************************************************************************************
1 plays in playbooks/teste.yml

PLAY [mylinuxserver] ********************************************************************************************************************************************************************************************
META: ran handlers

TASK [debug] ******************************************************************************************************************************************************************************************************
task path: /home/renato/ansible/playbooks/teste.yml:9
fatal: [mylinuxserver]: FAILED! => {
    "failed": true, 
    "msg": "the field 'remote_user' has an invalid value, which appears to include a variable that is undefined. The error was: 'vault_ansible_user' is undefined"
}
	to retry, use: --limit @/home/renato/ansible/playbooks/teste.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
mylinuxserver            : ok=0    changed=0    unreachable=0    failed=1 
```
