### ISSUE TITLE
Ansible 2.0.2 sts_asume_role error - Region does not seem to be available for aws module boto.sts

### ISSUE THREAD

**Issue by igoratencompass** [ansible/ansible#22731]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

sts_assume_role

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

```bash
# lsb_release -a
No LSB modules are available.
Distributor ID:    Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:    14.04
Codename:    trusty

# python --version
Python 2.7.6

# dpkg -l python-boto | grep ^ii
ii  python-boto                      2.20.1-2ubuntu2                   all          Python interface to Amazon's Web Services
```

##### SUMMARY

Getting error about region does not seem to be available for aws module boto.sts

##### STEPS TO REPRODUCE

Enter the role ARN from the EC2 instance in the below playbook and execute it on the EC2 instance it self.

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Assume the instance profile role
      sts_assume_role:
        region: "eu-west-1"
        role_arn: "arn:aws:iam::xxxxxxxxxx:instance-profile/profile-name"
        role_session_name: "someRoleSession"
      register: assumed_role
```

##### EXPECTED RESULTS

Get temp credentials in the assumed_role object

##### ACTUAL RESULTS

```
TASK [Assume the instance profile role] ****************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Region eu-west-1 does not seem to be available for aws module boto.sts. If the region definitely exists, you may need to upgrade boto or extend with endpoints_path"} 
```
