### ISSUE TITLE
Add Jinja2 templates to Cloudformation module

### ISSUE THREAD

**Issue by lobsterdore** [ansible/ansible#22736]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

AWS Cloudformation

##### SUMMARY

Using Jinja2 to produce Cloudformation templates allows for a flexible infra provisioning solution, however at the moment it is necessary to render a Jinja2 CF template into a temp file so it can be used to invoke the CF module like so:

```YAML
---

- name: Create a temp file for CF template
  command: mktemp
  register: tmpfile

- name: Create CF template
  template:
    dest: "{{ tmpfile.stdout }}"
    src: template.json.j2

- name: Ensure CF stack
  cloudformation:
    region: "..."
    stack_name: "..."
    state: present
    template: "{{ tmpfile.stdout }}"

- name: cleanup the temp file
  command: "rm {{ tmpfile.stdout }}"
```

It would be nice if the CF module could be invoked with a Jinja template directly:

```YAML
---

- name: Ensure CF stack
  cloudformation:
    format: j2
    region: "..."
    stack_name: "..."
    state: present
    template: template.json.j2
```
