### ISSUE TITLE
template/copy module regression: allow redirection inside validate

### ISSUE THREAD

**Issue by juju4** [ansible/ansible#22773]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template module.
can apply to copy module

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
+2.2.1

##### OS / ENVIRONMENT
Ubuntu trusty host or Travis with docker host (trusty/xenial/...)

##### SUMMARY
Under 2.2.0, validate arguments with shell redirection worked.
Under 2.2.1 (Travis), it does not.

##### STEPS TO REPRODUCE

```
- block:
    - name: ensure iptables directory exists
      file: dest=/etc/iptables state=directory mode=0755
    - name: iptables configuration file update
      template:
        src: "{{ harden_fw_template }}"
        dest: /etc/iptables/rules.v4
        backup: yes 
        owner: '0' 
        group: '0' 
        mode: '0644'
## works in ansible 2.2.0.0, nok 2.2.1.0?
#        validate: 'iptables-restore -tv < %s'
      notify:
        - restart iptables
        - restart iptables - xenial
      register: rulesv4
## as validate option seems incorrect
    - name: ensure rules are correct
      shell: "iptables-restore -tv < /etc/iptables/rules.v4"
      when: rulesv4.changed
  when: harden_fw is defined and harden_fw
```

##### ACTUAL RESULTS
with 2.2.1 (2.2.0 fine)
```
FAILED! => {"changed": true, "exit_status": 1, "failed": true, "msg": "failed to validate", "stderr": "Unknown arguments found on commandline\n", "stdout": "", "stdout_lines": []}

```
