### ISSUE TITLE
win_firewall_rule fails if remoteip is single IPv4 and task run more than once

### ISSUE THREAD

**Issue by ar7z1** [ansible/ansible#22786]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

windows/win_firewall_rule

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel dc68503ef2) last updated 2017/03/20 09:48:55 (GMT +300)
  config file = /home/art/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Managing Windows 7.

##### SUMMARY

[win_firewall_rule](http://docs.ansible.com/ansible/win_firewall_rule_module.html) fails when `remoteip` points to single IPv4 and the task runs more than once.

##### STEPS TO REPRODUCE

Run this task more than once:

```yaml
- name: Add firewall rule
  win_firewall_rule:
    name: http
    enable: yes
    state: present
    localport: 80
    remoteip: '192.168.0.1'
    action: allow
    direction: In
    protocol: TCP
```

##### EXPECTED RESULTS

Task returns ok.

##### ACTUAL RESULTS

Task fails:

```
fatal: [windows]: FAILED! => {
  "changed": false,
  "difference": ["192.168.0.1"],
  "failed": true,
  "fwsettings": {
    "Action": "allow",
    "Direction": "In",
    "Enabled": "yes",
    "LocalIP": "any",
    "LocalPort": 80,
    "Profiles": "any",
    "Protocol": "TCP",
    "RemoteIP": "192.168.0.1",
    "RemotePort": "any",
    "Rule Name": "http",
    "Service": "any"
  },
  "msg": ["The rule 'http' exists.", "The rule exists but has different values", "There was already a rule http with different values, use force=True to overwrite it"]
}
```

The first run of task creates:
```
C:\Windows\system32>netsh advfirewall firewall show rule name=http

Rule Name:                            http
----------------------------------------------------------------------
Enabled:                              Yes
Direction:                            In
Profiles:                             Domain,Private,Public
Grouping:
LocalIP:                              Any
RemoteIP:                             192.168.0.1/32
Protocol:                             TCP
LocalPort:                            80
RemotePort:                           Any
Edge traversal:                       No
Action:                               Allow
Ok.
```

As you can see `RemoteIP` is "192.168.0.1/32", but `win_firewall_rule` expects "192.168.0.1".

**Comment by ansibot** [comment]
cc @TimothyVandenbrande
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ar7z1** [comment]
PR: #22555

**Comment by ar7z1** [comment]
I ran into a similar issue on Windows Server 2008.
Task:
```yaml
- name: Add firewall rule
  win_firewall_rule:
    name: http
    enable: yes
    state: present
    localport: 80
    remoteip: '192.168.0.1'
    action: allow
    direction: In
    protocol: TCP
```
unfolds ip `192.168.0.1` into `192.168.0.1/255.255.255.255`:
```
C:\Users\Administrator>netsh advfirewall firewall show rule name="http" verbose

Rule Name:                            http
----------------------------------------------------------------------
Enabled:                              Yes
Direction:                            In
Profiles:                             Domain,Private,Public
Grouping:
LocalIP:                              Any
RemoteIP:                             192.168.0.1/255.255.255.255
Protocol:                             TCP
LocalPort:                            80
RemotePort:                           Any
Edge traversal:                       No
Service:                              Any
InterfaceTypes:                       Any
Security:                             NotRequired
Action:                               Allow
Ok.
```
