### ISSUE TITLE
Maven_Artifact Community Module

### ISSUE THREAD

**Issue by rmauc** [ansible/ansible#22806]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

maven_artifact

##### ANSIBLE VERSION

```
ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

None of significance 

##### OS / ENVIRONMENT

Ansible Control Server is Linux
Target Server could be any platform - Linux, Window, Unix 

##### SUMMARY

For the Maven _Artifact module - does the download of the artifact need to be 'staged' on the Ansible control server/Tower? Is there is no way to have it pushed directly to target machine? 
If we have all artifacts in JFROG Artifactory (i.e. Maven) and all artifacts are passing through Ansible - this would need a significant amount of disk space locally - which is probably not practical.

##### STEPS TO REPRODUCE

This is my playbook which sends the code to the Control Server. The documentation does not mention shipping it to the target Linux/Windows/Unix machine

```
- name: Download artifact from maven repository
  hosts: localhost
  tasks:
    - maven_artifact:
        group_id: 200
        artifact_id: 2001
        version: 1.0
        repository_url: "http://0980.XXXXX.com:80XX/artifactory/XXXX/"
        extension: xls
        dest: /tmp/2001-1.0.xls
        state: present
        validate_certs: no

```

##### ACTUAL RESULTS

```
changed: [localhost] => {
    "artifact_id": "2001",
    "changed": true,
    "classifier": null,
    "dest": "/tmp/2001-1.0.xls",
    "extension": "xls",
    "gid": 50128,
    "group": "ansible",
    "group_id": "200",
    "invocation": {
        "module_args": {
            "artifact_id": "2001",
            "classifier": null,
            "dest": "/tmp/2001-1.0.xls",
            "extension": "xls",
            "group_id": "200",
            "http_agent": null,
            "password": null,
            "repository_url": "http://0980.XXXXX.com:80XX/artifactory/XXX/",
            "state": "present",
            "url_password": null,
            "url_username": null,
            "username": null,
            "validate_certs": false,
            "version": "1.0"
        },
        "module_name": "maven_artifact"
    },
    "mode": "0664",
    "owner": "ansible",
    "repository_url": "http://0980.XXXXXX.com:80XX/artifactory/XXX/",
    "size": 15397376,
    "state": "file",
    "uid": 80107,
    "version": "1.0"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0


Thanks very much
```
