### ISSUE TITLE
vmware_guest - Won't allow more than 15 disks

### ISSUE THREAD

**Issue by thunderpants73** [ansible/ansible#22808]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### OS / ENVIRONMENT

RedHat 6.3/7.2
##### SUMMARY

Cannot create VM with more than 15 disks using vmware_guest.  This seems to have to do with the fact that you cannot only have 15 disks on each scsi bus.  This fails with the error: "A specified parameter was not correct: unitNumber"

In looking through the vmware_guest.py script, it appears there's no mechanism to increment the busNumber.

    @staticmethod
    def create_scsi_controller(scsi_type):
        scsi_ctl = vim.vm.device.VirtualDeviceSpec()
        scsi_ctl.operation = vim.vm.device.VirtualDeviceSpec.Operation.add
        if scsi_type == 'lsilogic':
            scsi_ctl.device = vim.vm.device.VirtualLsiLogicController()
        elif scsi_type == 'paravirtual':
            scsi_ctl.device = vim.vm.device.ParaVirtualSCSIController()
        elif scsi_type == 'buslogic':
            scsi_ctl.device = vim.vm.device.VirtualBusLogicController()
        elif scsi_type == 'lsilogicsas':
            scsi_ctl.device = vim.vm.device.VirtualLsiLogicSASController()

        scsi_ctl.device.deviceInfo = vim.Description()
        scsi_ctl.device.slotInfo = vim.vm.device.VirtualDevice.PciBusSlotInfo()
        scsi_ctl.device.slotInfo.pciSlotNumber = 16
        scsi_ctl.device.controllerKey = 100
        scsi_ctl.device.unitNumber = 3
        scsi_ctl.device.busNumber = 0
        scsi_ctl.device.hotAddRemove = True
        scsi_ctl.device.sharedBus = 'noSharing'
        scsi_ctl.device.scsiCtlrUnitNumber = 7

        return scsi_ctl

##### STEPS TO REPRODUCE

```yaml
---
- name: Create VM
  vmware_guest:
    hostname: "{{vsphere_hostname}}"
    username: "{{vsphere_username}}"
    password: "{{vsphere_password}}"
    validate_certs: no
    datacenter: "{{datacenter}}"
    cluster: "{{cluster}}"
    folder: "{{folder}}"
    name: "{{ site_code }}{{server_name | default('test2') }}"
    state: "poweredoff"
    guest_id: rhel7_64Guest
    hardware:
      memory_mb: "{{memory}}"
      num_cpus: "{{cpu}}"
      scsi: paravirtual
    networks:
      - name: "ACCESS"
        device_type: "vmxnet3"
    disk:
      - size_gb: "{{disk1_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk2_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk3_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"  
      - size_gb: "{{disk4_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk5_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk6_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk7_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk8_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk9_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk10_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk11_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk12_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk13_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk14_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk15_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk16_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk17_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk18_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk19_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"
      - size_gb: "{{disk20_size}}"
        type: "thin"
        #autoselect_datastore: True
        datastore: "{{datastore}}"                                                                                                                                          
    wait_for_ip_address: no
```

##### EXPECTED RESULTS

VM is built with multiple disks
##### ACTUAL RESULTS

```
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.6/site-packages/ansible-2.3.0.0-py2.6.egg/ansible/plugins/callback/__init__.pyc

PLAYBOOK: site.yml *********************************************************************************************************************************************
1 plays in site.yml

PLAY [127.0.0.1] ***********************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************
Using module file /usr/lib/python2.6/site-packages/ansible-2.3.0.0-py2.6.egg/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1490042590.13-69315754579242 `" && echo ansible-tmp-1490042590.13-69315754579242="` echo /root/.ansible/tmp/ansible-tmp-1490042590.13-69315754579242 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpnj30Th TO /root/.ansible/tmp/ansible-tmp-1490042590.13-69315754579242/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1490042590.13-69315754579242/ /root/.ansible/tmp/ansible-tmp-1490042590.13-69315754579242/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1490042590.13-69315754579242/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1490042590.13-69315754579242/" > /dev/null 2>&1 && sleep 0'
ok: [127.0.0.1]
META: ran handlers

TASK [estem2 : Create VM] **************************************************************************************************************************************
task path: /opt/ansible/ansible-2.3.0.0/plays/roles/estem2/tasks/main.yml:2
Using module file /usr/lib/python2.6/site-packages/ansible-2.3.0.0-py2.6.egg/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1490042591.23-130289669432941 `" && echo ansible-tmp-1490042591.23-130289669432941="` echo /root/.ansible/tmp/ansible-tmp-1490042591.23-130289669432941 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpnj30Th TO /root/.ansible/tmp/ansible-tmp-1490042591.23-130289669432941/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1490042591.23-130289669432941/ /root/.ansible/tmp/ansible-tmp-1490042591.23-130289669432941/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1490042591.23-130289669432941/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1490042591.23-130289669432941/" > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1]: FAILED! => {
    "changed": true, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cluster": "shared_storage", 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "Staging", 
            "disk": [
                {
                    "datastore": "Deployment1", 
                    "size_gb": "135", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "40", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "40", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "29", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "29", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "81", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "81", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "81", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "81", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "58", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "200", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "50", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "50", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "50", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "50", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "30", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "30", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "58", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "58", 
                    "type": "thin"
                }, 
                {
                    "datastore": "Deployment1", 
                    "size_gb": "50", 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "/vm/test", 
            "force": false, 
            "guest_id": "rhel7_64Guest", 
            "hardware": {
                "memory_mb": "8192", 
                "num_cpus": "2", 
                "scsi": "paravirtual"
            }, 
            "hostname": "192.168.0.100", 
            "is_template": false, 
            "name": "testserver2", 
            "name_match": "first", 
            "networks": [
                {
                    "device_type": "vmxnet3", 
                    "name": "ACCESS"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": null, 
            "state": "poweredoff", 
            "template_src": null, 
            "username": "administrator@vsphere.local", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "A specified parameter was not correct: unitNumber"
}
        to retry, use: --limit @/opt/ansible/ansible-2.3.0.0/plays/site.retry

PLAY RECAP *****************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1 
```

**Comment by ansibot** [comment]
cc @jctanner @nerzhul @dav1x
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nerzhul** [comment]
yes, you can only have 15 disks per bus, and we don't increase it, but is this normal to have more than 10 disks on a VM as it's not recommended by vmware ? do we need to allow that ?

**Comment by dav1x** [comment]
@thunderpants73 this is a physical limitation via the SCSI chain via a single controller. 

https://www.vmware.com/pdf/vsphere6/r65/vsphere-65-configuration-maximums.pdf

The work around would be to add another controller and create disks via it. There should be some logic built into the module to accommodate that. 

@nerzhul it is best practice on IO bound workloads to utilize separate PVSCSI controllers for each disk in question.

**Comment by thunderpants73** [comment]
@dav1x Are you saying this logic is already there, or this would need to be added?

**Comment by dav1x** [comment]
@thunderpants73 the logic is not currently there. But, its really a larger discussion since there are use cases for VM creation that might involve customizing disk layouts across multiple controllers.

**Comment by jctanner** [comment]
needs_contributor

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
VMware does not allow adding more than 15 disks to particular VM for performance. You can go through [VMware Configuration Maximums](https://www.vmware.com/pdf/vsphere6/r60/vsphere-60-configuration-maximums.pdf) to checkout maximum limits of Virtual disks to given VM.

**Comment by ansibot** [comment]
cc @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr #33338

**Comment by Akasurde** [comment]
@thunderpants73 Could you please check if this PR works for your setup ?

**Comment by Akasurde** [comment]
cc @pdellaert @angystardust @aperigault

**Comment by thunderpants73** [comment]
@Akasurde This appears to work.

Tested this in 2.3.1.0 and 2.5.0.

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

**Comment by Akasurde** [comment]
@thunderpants73 Thanks.

**Comment by ansibot** [comment]
cc @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by webstylesInt** [comment]
Hi Guys, 

I get this when adding only 3 disks
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/lloydwilke/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

Playbook

```yaml
- name: Add VMware server 1
    vmware_guest:
      hostname: "{{ vmware_host }}"
      username: "{{ esxi_user }}"
      password: "{{ esxi_pass }}"
      validate_certs: False
      datacenter: "{{ datacenter }}"
      cluster: PROD 
      folder: Windows
      name: vm1
      guest_id: windows8Server64Guest
      state: poweredoff
      disk:
      - size_gb: 80
        type: thin
        autoselect_datastore: yes
        datastore: "{{ vmware_datastore }}"
      - size_gb: 120
        type: thin
        autoselect_datastore: yes
        datastore: "{{ vmware_datastore }}"
      - size_gb: 120
        type: thin
        autoselect_datastore: yes
        datastore: "{{ vmware_datastore }}"
      hardware:
        memory_mb: 8192
        num_cpus: 2
        num_cpu_cores_per_socket: 1
        scsi: lsilogicsas
        hotadd_cpu: True
        hotadd_memory: True
      cdrom:
        type: iso
        iso_path: "[{{ vmware_isostore }}] Windows Server 2012 R2.ISO"
      networks:
      - name: vm network
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy_vm
```
