### ISSUE TITLE
vsphere_guest extra_config folder is not scoped to targeted datacenter: can return the wrong folder

### ISSUE THREAD

**Issue by lglussen** [ansible/ansible#22811]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vsphere_guest

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
VMware vCenter Server Version 6.0.0

##### SUMMARY
The `extra_config: folder` lookup is not limited to the target datacenter.  This means if a folder of the same name exists in more than one datacenter, the deployment can fail if the wrong folder is returned.

Because the `folder` parameter dose not accept a path - only a folder name, I have come to accept that it will deploy to the first folder it finds by the provided name.  Even if not the desired folder, it will still deploy.  However, when the folders are on different datacenters, it breaks the deployment when the "wrong" folder is returned.

I would expect the search to be scoped to the datacenter you are deploying to since only those folders would work.

##### STEPS TO REPRODUCE

1. Configure vCenter with at least 2 Datacenters and put a folder of the same name (`main`) in each. Try naming the  datacenters such that the "Undesired" datacenters name comes first alphabetically. 
    > *I don't know for a fact that it goes in alphabetical order - but that matches what I've seen so far* 
2. Add a template so we have something to clone (`canvas`)
```
vcenter.example.net
   AdminDatacenter
       main/
   ProductionDatacenter
       main/
       canvas
```
Run the `vsphere_guest` task making sure to use the target folder and datacenter to deploy from the template.

```yaml
- name: "Create virtual machines from templates in vCenter"
  vsphere_guest:
    vcenter_hostname: "vcenter.example.net"
    username: "bob.ross@example.net"
    password: "happyTr33s"
    guest: "thaloBlue "
    from_template: yes
    template_src: "canvas"
    cluster: "something_that_works"
    esxi:
      datacenter: "ProductionDatacenter"
      hostname: "192.168.1.42"
    power_on_after_clone: no
    validate_certs: "no"
    force: no
    vm_extra_config:
      folder: "main"
```

##### EXPECTED RESULTS

```
vcenter.example.net
   AdminDatacenter
       main/
   ProductionDatacenter
       main/thaloBlue
       canvas
```
##### ACTUAL RESULTS
The folder from the wrong datacenter is selected resulting in an error: `A specified parameter was not correct: spec.location.folder`
![A specified parameter was not correct: spec.location.folder](https://cloud.githubusercontent.com/assets/2031197/24122537/8aa553bc-0d92-11e7-8a21-02e04d73e8c8.PNG)

And in Ansible:
```
"msg": "Could not clone selected machine: [Task Error]: A specified parameter was not correct: spec.location.folder"

```
