### ISSUE TITLE
win_regedit - Not adding new reg entries

### ISSUE THREAD

**Issue by windowsansiblernew** [ansible/ansible#22829]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_regedit

##### ANSIBLE VERSION

```
ansible 2.2.1.0

```

##### SUMMARY
Following is a basic playbook for testing out win_regedit and i could see that the newkey is alone getting created, not the entry and the data in it

##### STEPS TO REPRODUCE

```yaml
hosts: web
tasks:

    name: Crete and add reg entries
    win_regedit:
    key: HKLM:\SOFTWARE\testing\SDk\newkey
    entry: hello
    data: world

```

##### EXPECTED RESULTS
create a reg key called newkey and after that create entry called  hello with data in it as world

##### ACTUAL RESULTS

it created only newkey, rest is not done

```

```
