### ISSUE TITLE
Specifying "latest" for pkg5 state does not install uninstalled package

### ISSUE THREAD

**Issue by autarch** [ansible/ansible#22823]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

pkg5

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/autarch/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Ubuntu 16.04, host is Solaris 11

##### SUMMARY

Specifying state as `latest` leads to packages not being installed at all.

##### STEPS TO REPRODUCE

```yaml
- name: Make sure all packages we want are installed
  pkg5:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc # installs C, C++, and Fortran compilers plus helper tools
    - /editor/gnu-emacs/gnu-emacs-no-x11
    - vim
    - autoconf
    - automake
    - bison
    - byaccj
    - elfutils
    - flex
    - libtool
    - /text/gnu-patch
    - /text/patchutils
    - swig
    - gnu-binutils
    - /file/gnu-coreutils
    - /text/gnu-diffutils
    - /file/gnu-findutils
    - git
```

##### EXPECTED RESULTS

I thought packages would be installed

##### ACTUAL RESULTS

```
TASK [solaris : Make sure all packages we want are installed] ******************
task path: /home/autarch/work/camel/ansible/roles/solaris/tasks/packages.yml:2
ok: [192.168.42.108] => (item=gcc) => {"changed": false, "item": "gcc", "msg": "", "results": []}
ok: [192.168.42.108] => (item=/editor/gnu-emacs/gnu-emacs-no-x11) => {"changed": false, "item": "/editor/gnu-emacs/gnu-emacs-no-x11", "msg": "", "results": []}
ok: [192.168.42.108] => (item=/solaris/editor/vim) => {"changed": false, "item": "/solaris/editor/vim", "msg": "", "results": []}
ok: [192.168.42.108] => (item=autoconf) => {"changed": false, "item": "autoconf", "msg": "", "results": []}
ok: [192.168.42.108] => (item=automake) => {"changed": false, "item": "automake", "msg": "", "results": []}
ok: [192.168.42.108] => (item=bison) => {"changed": false, "item": "bison", "msg": "", "results": []}
ok: [192.168.42.108] => (item=byaccj) => {"changed": false, "item": "byaccj", "msg": "", "results": []}
ok: [192.168.42.108] => (item=elfutils) => {"changed": false, "item": "elfutils", "msg": "", "results": []}
ok: [192.168.42.108] => (item=flex) => {"changed": false, "item": "flex", "msg": "", "results": []}
ok: [192.168.42.108] => (item=libtool) => {"changed": false, "item": "libtool", "msg": "", "results": []}
ok: [192.168.42.108] => (item=/solaris/text/gnu-patch) => {"changed": false, "item": "/solaris/text/gnu-patch", "msg": "", "results": []}
ok: [192.168.42.108] => (item=/text/patchutils) => {"changed": false, "item": "/text/patchutils", "msg": "", "results": []}
ok: [192.168.42.108] => (item=swig) => {"changed": false, "item": "swig", "msg": "", "results": []}
ok: [192.168.42.108] => (item=gnu-binutils) => {"changed": false, "item": "gnu-binutils", "msg": "", "results": []}
ok: [192.168.42.108] => (item=/solaris/file/gnu-coreutils) => {"changed": false, "item": "/solaris/file/gnu-coreutils", "msg": "", "results": []}
ok: [192.168.42.108] => (item=/solaris/text/gnu-diffutils) => {"changed": false, "item": "/solaris/text/gnu-diffutils", "msg": "", "results": []}
ok: [192.168.42.108] => (item=/solaris/file/gnu-findutils) => {"changed": false, "item": "/solaris/file/gnu-findutils", "msg": "", "results": []}
ok: [192.168.42.108] => (item=git) => {"changed": false, "item": "git", "msg": "", "results": []}
```
