### ISSUE TITLE
sros_config difference between lines and src attribute

### ISSUE THREAD

**Issue by wisotzky** [ansible/ansible#22828]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
Module sros_config

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file = /home/nokia/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
```
$ uname --all
Linux srv17 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY
From documentation point of view it is expected that the behavior of "lines" and "src" attribute is almost the same. Only difference expected is, that src is loading the configuration from configuration file or j2 template - while lines is including the configuration directly into the yaml file.

Seems like, the "lines" attribute is not supporting entering a new configuration context, while this is supported using files/templates. Find example below. Unclear if this is a bug - or if this should just be better described within the module documentation (known limitation).

##### STEPS TO REPRODUCE

Yaml task file used:
```
- name: create vpls service
  sros_config:
    provider: "{{ cli }}"
    lines:
      - description "ansible-created"
      - endpoint "abc" create
      -     description "blub"
      - exit
      - no shutdown
    parents:
      - configure
      - service
      - vpls 1000 customer 1 create
    provider: "{{ cli }}"
    backup: yes
```

##### EXPECTED RESULTS
It is expected that all configuration is created as per ansible yaml file.

##### ACTUAL RESULTS
The "endpoint" description "blub" is not added to the configuration.
