### ISSUE TITLE
sros_config always sets changed indicator

### ISSUE THREAD

**Issue by wisotzky** [ansible/ansible#22827]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module sros_config

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file = /home/nokia/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
```
$ uname --all
Linux srv17 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY
When I run the same configuration template multiple times, it seems the "changed=1" indicator is always set. It would be expected when running the same configuration the second time, this ansible module recognizes that no changes are contained.

##### STEPS TO REPRODUCE

Configuration template used:
```
vpls 1000 customer 1 create
    description "ansible-created"
    no shutdown
exit
```

Task file used:
```
yaml
- name: create vpls service
  sros_config:
    provider: "{{ cli }}"
    src: vpls1000.cfg
    backup: yes
    save: yes
    match: line
    parents:
      - configure
      - service
```

##### EXPECTED RESULTS
When running the 2nd time, I would expect it shows "changed=0" or similar.

##### ACTUAL RESULTS
```
PLAY RECAP *********************************************************************
192.168.122.10             : ok=1    changed=1    unreachable=0    failed=0
```
