### ISSUE TITLE
synchronize cannot mkdir dest folder if the parent doesn't exist

### ISSUE THREAD

**Issue by timotheemoulin** [ansible/ansible#22862]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
synchronize

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

##### CONFIGURATION
No change

##### OS / ENVIRONMENT
host : Linux dev-tmoulin 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux
remote : localhost

##### SUMMARY
When using the *synchronize* plugin to copy file from the remote to local, the destination folder cannot be created if its parent does not already exists.

##### STEPS TO REPRODUCE
```bash
ansible-playbook playbook-dev.yml --extra-vars "host_web=web
```

**hosts**
```
[web]
127.0.0.1 ansible_connection=local web_root=/var/www/html
```

**playbook-dev.yml**
```yaml
- hosts: "{{ host_web }}"
  vars: 
    local_archive_storage: /tmp
  tasks:
  - name: "backup website {{ inventory_hostname }} : {{ web_root }}"
    synchronize: 
      archive: yes #default: yes
      compress: yes #default: yes
      src: "{{ web_root }}/"
      dest: "{{ local_archive_storage }}/{{ inventory_hostname }}/backup"
      mode: pull
```

##### EXPECTED RESULTS
The destination folder `/tmp/127.0.0.1/web` should be created with `mkdir -p` so the full hierarchy folders would be created if needed.

##### ACTUAL RESULTS
If the parent `/tmp/127.0.0.1` folder does not exist, the process fails.

```
TASK [backup website 127.0.0.1 : /var/www/html] **********
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no -o Port=22' --out-format='<<CHANGED>>%i %n%L' \"/var/www/html/\" \"/tmp/127.0.0.1/web\"", "failed": true, "msg": "rsync: mkdir \"/tmp/127.0.0.1/web\" failed: No such file or directory (2)\nrsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]\n", "rc": 11}

```

**Comment by abadger** [comment]
This is the way synchronize works.  You can create the folder with a task like this:
```
- name: Create backup folder
  file:
    path: "{{ local_archive_storage }}/{{ inventory_hostname }}/backup"
    state: directory
```

prior to the synchronize task.

**Comment by richardsonlima** [comment]
I had the same issue!

**Comment by filipnowakswissre** [comment]
i don't see a reason why dst creation needs to be worked around and is not part of synchronize module.

**Comment by cericoda** [comment]
Hi. I have just had this issue and tried to follow the advice @abadger gave but it didn't work for me.

What I needed to do was:

```
  - name: Create backup folder
    local_action:
      module: file
      path: "{{ local_archive_storage }}/{{ inventory_hostname }}/backup"
      state: directory
```
