### ISSUE TITLE
Traceback:  Container.name contains invalid characters.\r\n using ecs_taskdefinition

### ISSUE THREAD

**Issue by Ankur012** [ansible/ansible#22860]
Hi ,

I am trying to create ecs task definantion usnig ecs_taskdefinition module. but getting "module_stderr": "Shared connection to localhost closed.\r\n" " error.  

my localhost system ssh connecting is working successfully. i am straggling to resolve this issue from last 2 day.

#ssh localhost
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-66-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

261 packages can be updated.
12 updates are security updates.

ssh root@localhost
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-66-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

261 packages can be updated.
12 updates are security updates.

##### ISSUE TYPE
 - Bug Report
 

##### COMPONENT NAME
Name of the module ecs_taskdefinition 

##### ANSIBLE VERSION
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
```
cat hosts 
[local]
localhost

cat nginx.yaml
---
- hosts: local
  tasks:
    - name: application as an ECS Task Definition
      ecs_taskdefinition:
         state: present
         family: Nginx
         containers:
           - name: Nginx web server
             cpu: 100
             essential: true
             image: nginx
             memory: 300
             entryPoint:
               - "bash"               
               - "-c"
             command:
               - /bin/bash -c "while true; do echo '<html><head><title>ECS Sample App</title></head><body><div><h1>ECS Sample Page</h1><h2>Congratulations!</h2><p>Your application is now running on a container in ECS box.</p>' > top; /bin/date > date ; echo '</div></body></html>' > bottom; cat top date bottom > /var/www/html/index.html ; sleep 1; done"
             portMappings:
               - containerPort: 80
                 hostPort: 80
```
##### OS / ENVIRONMENT
Ubuntu 1604

##### ACTUAL RESULTS
```
ansible-playbook  -i hosts  nginx.yaml  -vvv
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: nginx.yaml ***********************************************************
1 plays in nginx.yaml

PLAY [local] *******************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ankur/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/${USER}/ansible/ansible-tmp-1490171890.45-63141006780109 `" && echo ansible-tmp-1490171890.45-63141006780109="` echo /tmp/${USER}/ansible/ansible-tmp-1490171890.45-63141006780109 `" ) && sleep 0'"'"''
<localhost> PUT /tmp/tmpz4FCfO TO /tmp/ankur/ansible/ansible-tmp-1490171890.45-63141006780109/setup.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ankur/.ansible/cp/ansible-ssh-%h-%p-%r '[localhost]'
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ankur/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'chmod u+x /tmp/ankur/ansible/ansible-tmp-1490171890.45-63141006780109/ /tmp/ankur/ansible/ansible-tmp-1490171890.45-63141006780109/setup.py && sleep 0'"'"''
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ankur/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost '/bin/sh -c '"'"'/usr/bin/python /tmp/ankur/ansible/ansible-tmp-1490171890.45-63141006780109/setup.py; rm -rf "/tmp/ankur/ansible/ansible-tmp-1490171890.45-63141006780109/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [localhost]

TASK [Nginx Describe the application as an ECS Task Definition] ****************
task path: /home/ankur/ansible/ecs/ecs-ansible/nginx.yaml:4
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/extras/cloud/amazon/ecs_taskdefinition.py
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ankur/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/${USER}/ansible/ansible-tmp-1490171891.04-233902707019645 `" && echo ansible-tmp-1490171891.04-233902707019645="` echo /tmp/${USER}/ansible/ansible-tmp-1490171891.04-233902707019645 `" ) && sleep 0'"'"''
<localhost> PUT /tmp/tmplhuhn0 TO /tmp/ankur/ansible/ansible-tmp-1490171891.04-233902707019645/ecs_taskdefinition.py
<localhost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ankur/.ansible/cp/ansible-ssh-%h-%p-%r '[localhost]'
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ankur/.ansible/cp/ansible-ssh-%h-%p-%r localhost '/bin/sh -c '"'"'chmod u+x /tmp/ankur/ansible/ansible-tmp-1490171891.04-233902707019645/ /tmp/ankur/ansible/ansible-tmp-1490171891.04-233902707019645/ecs_taskdefinition.py && sleep 0'"'"''
<localhost> ESTABLISH SSH CONNECTION FOR USER: None
<localhost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/ankur/.ansible/cp/ansible-ssh-%h-%p-%r -tt localhost '/bin/sh -c '"'"'/usr/bin/python /tmp/ankur/ansible/ansible-tmp-1490171891.04-233902707019645/ecs_taskdefinition.py; rm -rf "/tmp/ankur/ansible/ansible-tmp-1490171891.04-233902707019645/" > /dev/null 2>&1 && sleep 0'"'"''
**## fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "ecs_taskdefinition"
    }, 
    "module_stderr": "Shared connection to localhost closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_TarrDY/ansible_module_ecs_taskdefinition.py\", line 222, in <module>\r\n    main()\r\n  File \"/tmp/ansible_TarrDY/ansible_module_ecs_taskdefinition.py\", line 200, in main\r\n    module.params['containers'], volumes)\r\n  File \"/tmp/ansible_TarrDY/ansible_module_ecs_taskdefinition.py\", line 138, in register_task\r\n    containerDefinitions=container_definitions, volumes=volumes)\r\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 253, in _api_call\r\n    return self._make_api_call(operation_name, kwargs)\r\n  File \"/usr/local/lib/python2.7/dist-packages/botocore/client.py\", line 543, in _make_api_call\r\n    raise error_class(parsed_response, operation_name)\r\nbotocore.errorfactory.ClientException: An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Container.name contains invalid characters.\r\n", 
    "msg": "MODULE FAILURE"
}
	to retry, use: --limit @/home/ankur/ansible/ecs/ecs-ansible/nginx.retry**

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1 
```
