### ISSUE TITLE
Ansible network module junos_config update: overwrite issue

### ISSUE THREAD

**Issue by frederic-loui** [ansible/ansible#22880]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible network module / Junos -> junos_config 

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 6318229bc4) last updated 2017/03/22 14:22:28 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/ansible/library']
  python version = 2.7.13 (default, Dec 20 2016, 16:33:50) [GCC 6.2.1 20160822]

```
##### OS / ENVIRONMENT
Alpine linux edge running as a docker container.

##### SUMMARY
Issue with :
junos_config with update argument set to "overwrite" and src_format argument set to "set": 
junos_config with update argument set to "overwrite" and src_format argument set to "text":
junos_config with backup argument set to "yes",

##### STEPS TO REPRODUCE
```yaml

With src_format argument set to "set" value

    - name: load configure file into device using file "/ansible-vanilla-config-set/{{ ansible_ssh_host }}"
      junos_config:
        update: overwrite
        src: "/ansible-vanilla-config-set/{{ ansible_ssh_host }}"
        src_format: set
        backup: yes
        comment: update config
        host: "{{ ansible_ssh_host }}"
        username: "{{ juniper_user }}"
        password: "{{ juniper_passwd }}"


With src_format argument set to "text" value

    - name: load configure file into device using file "/ansible-vanilla-config-set/{{ ansible_ssh_host }}"
      junos_config:
        update: overwrite
        src: "/ansible-vanilla-config-set/{{ ansible_ssh_host }}"
        src_format: text
        backup: yes
        comment: update config
        host: "{{ ansible_ssh_host }}"
        username: "{{ juniper_user }}"
        password: "{{ juniper_passwd }}"
```
With src_format set to "text" value and a Junos text configuration format the playbook report:
TASK [load configure file into device using file "/ansible-vanilla-config-set/10.134.250.35"] ***
task path: /ansible-playbook-dir/pb-nmaas-lab-init.yml:32
fatal: [gn4-net-core-5]: FAILED! => {"changed": false, "failed": true, "msg": "invalid action format text"}
        to retry, use: --limit @/ansible-playbook-dir/pb-nmaas-lab-init.retry
 
##### EXPECTED RESULTS
junos_config with update argument set to overwrite and srf_format set to "set" or "text" value.
The configuration should be overwritten as per the documentation description.

##### ACTUAL RESULTS
junos_config with update argument set to "overwrite" and src_format argument set to "set": 
the Junos configuration using "set" format is not entireley replaced as per the behaviour described by the module documentation. The config seems to be  merged.

junos_config with update argument set to "overwrite" and src_format argument set to "text":
the Junos configuration using "text" format is not replaced and the playbook throw the following error: 
fatal: [gn4-net-core-5]: FAILED! => {"changed": false, "failed": true, "msg": "invalid action format text"}

junos_config with backup argument set to "yes", systematically delete backup folder and all files inside this backup. Meaning that all previous backup done by running the plabook are lost. It would be great to chose the name of the path of the backup folder but also avoid to delete recursively thos folder.
