### ISSUE TITLE
win_chocolatey installing powershell when powershell4 is installed

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#22892]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

win_chocolatey

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel cc50b803df) last updated 2017/03/22 14:15:18 (GMT -500)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

Ansible configuration from git clone

##### OS / ENVIRONMENT

Control host macOS 10.12.3
Managed host Windows 7

##### SUMMARY

Attempting to upgrade powershell4 to powershell5 using the win_chocolatey module. 

Might be related to https://github.com/ansible/ansible/issues/21873

##### STEPS TO REPRODUCE

  - Have chocolatey installed
  - Install powershell4

```yaml
- name: install powershell 
  win_chocolatey:
    name: "{{ item }}"
    state: present
  with_items:
    - "powershell"
  register: check_powershell5
```

##### EXPECTED RESULTS

Powershell5 will be installed

##### ACTUAL RESULTS

win_chocolatey seems to think powershell4 satisfies the requirement for powershell?

```
TASK [win_powershell : install powershell ] **************************
task path: /Users/tanner/projects/ansible.git/playbooks.git/roles/win_powershell/tasks/main.yml:64
Using module file /Users/tanner/projects/ansible.git/ansible/lib/ansible/modules/windows/win_chocolatey.ps1
<192.168.249.130> ESTABLISH WINRM CONNECTION FOR USER: IEUser on PORT 5986 TO 192.168.249.130
EXEC (via pipeline wrapper)
ok: [ie11win7] => (item=powershell) => {
    "changed": false,
    "item": "powershell",
    "rc": 0
}
```

**Comment by ansibot** [comment]
cc @smadam813 @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by basictheprogram** [comment]
Changing state to latest causes a problem as well. Let me know if I need to open a different ticket.

```yaml
- name: install powershell 
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items:
    - "powershell"
  register: check_powershell5
```
https://gist.github.com/basictheprogram/74b48320e386d308a69f82f7c90019b5

choco_summary.log
https://gist.github.com/basictheprogram/de146516fe292a43630c10e7df205f38

chocolatey.log
https://gist.github.com/basictheprogram/5cc240c1f89fba6ef7ac769ff5e41a01

**Comment by jhawkesworth** [comment]
@basictheprogram - could this be the same as the issue described and fixed in #23098 ?
If so, please can you test that PR? There's some information on testing PRs here: http://docs.ansible.com/ansible/dev_guide/developing_test_pr.html

needs_info

**Comment by dagwieers** [comment]
@basictheprogram Please open a new ticket for your issue with `state: latest`. However, this is just the same as `state: present` and `upgrade: yes`. So I doubt we introduced a regression there.

**Comment by dagwieers** [comment]
At [19:00 UTC](http://www.thetimezoneconverter.com/?t=19:00&tz=UTC) this ticket will be processed during [the first Windows Sprint](https://github.com/ansible/community/wiki/Windows:-sprints#2017-07-04-1900-utc-sprint-1), we would appreciate if you could join the Sprint to help out with fixing/closing this issue.

**Comment by dagwieers** [comment]
Ok, so I cannot reproduce this exact issue because I only have Windows 10 systems here.
It simply results in an OK :-)
needs_info

**Comment by jborean93** [comment]
While I can't reproduce the error @basictheprogram has on the latest devel version I am still getting another error. This is the playbook I am using and am running on a Server 2012 on PS 4.

```
---
- name: test out ps issue
  hosts: windows
  tasks:
  - name: update ps version
    win_chocolatey:
      name: powershell
      state: latest
```

The error I am receiving
```
TASK [update ps version] ***********************************************************************************************
task path: /home/jborean/dev/module-tester/testing.yml:5
Wednesday 05 July 2017  11:10:37 +1000 (0:00:06.279)       0:00:06.386 ********
fatal: [Server2012R2]: FAILED! => {"changed": false, "choco_error_cmd": "choco.exe install -dv -y powershell -timeout 27
00 --failonunfound", "choco_error_log": null, "failed": true, "msg": "Error installing powershell", "rc": 5}

PLAY RECAP *************************************************************************************************************
Server2012R2               : ok=1    changed=0    unreachable=0    failed=1
```

I'll need to look at it more but honestly I wouldn't be suprised if it will always fail due to to the reliance WinRM has on WMF and Powershell.
