### ISSUE TITLE
win_domain_membership - Feature Request - Allow to specifie Organization Unit

### ISSUE THREAD

**Issue by daBONDi** [ansible/ansible#22908]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
win_domain_membership

##### ANSIBLE VERSION
Latest Devel Pull, aka 2.4

##### CONFIGURATION
Add a Property something like "ou" or "organization_unit"

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Would allow to place the host to a specified OU in Active Directory

##### STEPS TO REPRODUCE
Feature Idea nothing to Reproduce

```yaml
- hosts: winclient
  gather_facts: no
  tasks:
  - win_domain_membership:
      dns_domain_name: ansible.vagrant
      organization_unit: "OU=myserver,DC=ansible,DC=vagrant"
      hostname: mydomainclient
      domain_admin_user: testguy@ansible.vagrant
      domain_admin_password: password123!
      state: domain
    register: domain_state
```

##### EXPECTED RESULTS
Computer Account gets Created in the OU

##### ACTUAL RESULTS
Nothing, Feature Request :-)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andmos** [comment]
This would be nice - and is actually what's keeping us from using the module. Today we use some custom PowerShell-scripts to be able to set `-OuPath "{{ domain_ou_path }}"` as such: `domain_ou_path: OU=Team SomeTeam,OU=Application Servers,OU=Domain Servers,DC=mydomain,DC=local`

**Comment by dagwieers** [comment]
needs_contributor

**Comment by daBONDi** [comment]
Will try and work on it hopefully i can spare some time this or next weekend for it stil dont got a good dev toolchain for ansible development 😣

**Comment by trondhindenes** [comment]
in the meantime, the xComputername dsc module works fairly well, it's what we use:
```
  - name: set computer name/join domain
    win_dsc:
      resource_name: xComputer
      name: "{{ inventory_hostname }}"
      DomainName: "{{ join_domain_name }}"
      JoinOu: "{{ join_domain_default_dn_base }}"
      Credential_username: "{{ domain_join_cred_username }}"
      Credential_password: "{{ domain_join_cred_password }}"
    register: rename
    retries: 3
    delay: 3
    until: rename | success
  when: join_domain | bool
```
