### ISSUE TITLE
Regression: junos_config fails with error message "unable to retrieve device configuration"

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#22907]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_config

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (91a385b87d) last updated 2017/03/23 11:12:45 (GMT +550)
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

JUNOS version is < 15.1
##### OS / ENVIRONMENT

macOS Sierra
##### STEPS TO REPRODUCE

Run below playbook which is using junos_config module to configure JUNOS device with version < 15.1

```yaml
- name: load configure file
  hosts: junos_host
  connection: local
  tasks:
  - name: Run junos_config
    junos_config:
      src: config.set
      src_format: set
      backup: yes
      comment: update config
      host: xxx
      username: xxx
      password: xxx
```

##### EXPECTED RESULTS

Playbook should run successfully and configuration should be applied on device.

##### ACTUAL RESULTS

```
ASK [Run junos_config] ***********************************************************************************************************
fatal: [junos_host]: FAILED! => {"changed": false, "failed": true, "msg": "unable to retrieve device configuration"}
	to retry, use: --limit @/Users/gnalawad/targets/junos_config_1.retry

PLAY RECAP ************************************************************************************************************************
junos_host                   : ok=1    changed=0    unreachable=0    failed=1   

```
