### ISSUE TITLE
DellOS6 module hangs when execute ansible-playbook

### ISSUE THREAD

**Issue by changzhi1990** [ansible/ansible#22901]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/core/network/dellos6

##### ANSIBLE VERSION
```
root@ansible:~# ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
root@ansible:~# cat /etc/ansible/ansible.cfg |grep -v "#"|grep -v ^$
[defaults]
transport      = paramiko
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Playbook command hangs when try to get dell switch's version info. Maybe ansible triggers some deal lock about python.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: dell
  connection: ssh
  gather_facts: no

  vars:
    cli:
      username: admin
      password: admin123
      transport: cli
      authorize: yes
      timeout: 3

  tasks:
  - name: "Get Dell EMC OS6 Show version"
    dellos6_command:
      commands: ['show version']
      provider: "{{ cli }}"
    register: show_ver

  - debug: var=show_ver
```

Yaml file shows like above.

##### ACTUAL RESULTS

```
root@ansible:~# ansible-playbook  dellos6.yaml  -vvvv
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: dellos6.yaml *********************************************************
1 plays in dellos6.yaml

PLAY [dell] ********************************************************************

TASK [Get Dell EMC OS6 Show version] *******************************************
task path: /root/dellos6.yaml:15
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/network/dellos6/dellos6_command.py
<172.16.0.5> ESTABLISH SSH CONNECTION FOR USER: admin
<172.16.0.5> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o User=admin -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 172.16.0.5 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1490264914.24-223645501715890 `" && echo ansible-tmp-1490264914.24-223645501715890="` echo ~/.ansible/tmp/ansible-tmp-1490264914.24-223645501715890 `" ) && sleep 0'"'"''

```
