### ISSUE TITLE
Variable expansion changed from 2.2.0.0 to 2.2.1.0

### ISSUE THREAD

**Issue by bjne** [ansible/ansible#22913]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
set_fact
##### ANSIBLE VERSION
2.2.0.0 -> 2.2.1.0 behavior change
##### SUMMARY
When changing from 2.2.0.0 to 2.2.1.0 we noticed incorrect IMO behavior of variable
expansion in set_fact, where variables only seem to be expanded one step back,
and not all the way. This seems to (perhaps) only affect vars[...]

##### STEPS TO REPRODUCE
playbook:
```
- hosts: localhost
  vars:
    foo: somevalue
    bar: "{{ foo }}"
  tasks:
    - set_fact:
        baz: "{{ vars.bar }}"
    - debug: var=baz

```
##### EXPECTED RESULTS
```
somevalue
```
##### ACTUAL RESULTS
```
{{ foo }}
```

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
So far I have been unable to validate this.  I have tested in `v2.2.1.0-1`, `stable-2.2` and `devel`.

and I am getting the following:

```
TASK [test : debug] ************************************************************
ok: [localhost] => {
    "baz": [
        "foo",
        "bar",
        "baz"
    ]
}
```

Since I noticed the use of `defaults` I tested this as a role, and also tested with everything in a playbook, with `foo` and `bar` defined under the `vars` section.  I also tested with the vars defined in `roles/test/defaults/main.yml` and the `set_fact` and `debug` in the playbook itself.

Playbook from my test:

```yaml
---
- hosts: all
  vars:
    foo:
      - foo
      - bar
      - baz
    bar: "{{ foo }}"
  tasks:
    - set_fact:
        baz: "{{ bar }}"

    - debug: var=baz
```
