### ISSUE TITLE
apt state=absent name=XXX does not always stop the service before deleting the package

### ISSUE THREAD

**Issue by dimikot** [ansible/ansible#2292]
E.g. on Ubuntu Server:

```
- name: ensure non-needed and conflicting packages are removed
  apt: pkg=$item state=absent purge=yes
  with_items:
    - sendmail
    - sendmail-bin
    - sendmail-base
    - sendmail-cf
    - sendmail-doc
```

This successfully removes sendmail, but sendmail daemon process remains in the memory and is still running, because the service is not stopped. If I add

```
service: name=sendmail state=stopped
```

before this task, it helps, but ONLY at the very first time (because next time "service" cannot find /etc/init.d/sendmail anymore - it was purged - and fails).

My proposal is one of:
- add a flag to softly ignore (with no error messages, i.e. as OK code) missing services in "service stopped" task;
- or add a flag to "apt" task to force service stopping before executing the real removal procedure.

P.S.
Maybe this is an issue in sendmail deb package (it does not stop the daemon on removal), but I suppose there is a number of similar cases (e.g. apache2), so it could be a good ansible feature if implemented.
