### ISSUE TITLE
Mount Module doesn't properly handle cifs option "credentials"

### ISSUE THREAD

**Issue by seljuck** [ansible/ansible#22930]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

mount module
##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/user/project/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

None
##### OS / ENVIRONMENT

Running Ansible on Ubuntu Mate 16.10
Managing Ubuntu Server 16.04
##### SUMMARY

Using the mount module to create a mount for a cifs share. In the options argument
using the credentials option fails to create the mount.

##### STEPS TO REPRODUCE

```yaml
- name: add mount remote backup
    mount:
      name: /mnt/RemoteBackups
      src: //server/RemoteBackups$
      opts: "credentials=/root/smbcred,gid=999,uid=999"
      fstype: cifs
      state: mounted
    become: true # as root
```

##### EXPECTED RESULTS

I expected the mount to be created.
##### ACTUAL RESULTS

```
   "invocation": {                                                                                                              [1728/4589]
        "module_args": {
            "boot": "yes", 
            "dump": null, 
            "fstab": "/etc/fstab", 
            "fstype": "cifs", 
            "name": "/mnt/RemoteBackups", 
            "opts": "credentials=/root/smbcred", 
            "passno": null, 
            "src": "//server/RemoteBackups$", 
            "state": "mounted"
        }, 
        "module_name": "mount"
    }, 
    "msg": "Error mounting /mnt/RemoteBackups: mount: wrong fs type, bad option, bad superblock on //server/RemoteBackups$,\n       miss
ing codepage or helper program, or other error\n       (for several filesystems (e.g. nfs, cifs) you might\n       need a /sbin/mount.<type>
 helper program)\n\n       In some cases useful info is found in syslog - try\n       dmesg | tail or so.\n"

```

**Comment by deekayen** [comment]
I'm not able to reproduce this specific issue, however I do still have a problem with opts in Ansible 2.2 and 2.3. Input debug:

```
ok: [host.example.com] => {
    "changed": false,
    "share_mount": {
        "changed": true,
        "dump": "0",
        "fstab": "/etc/fstab",
        "fstype": "cifs",
        "name": "/input_files",
        "opts": "credentials=/home/svc_account/.smbcredentials,dir_mode=0777,file_mode=0777,uid=0,gid=0,noserverino 0 0",
        "passno": "0",
        "src": "//share/shared"
    }
}
```

Then when I look in the `/etc/fstab` file on the target machine, it always adds `\0400\0400` at the first whitespace of the opts. The next time it runs, I think the `\0400\0400` confuses it and it re-adds the fstab line, so I ended up with like 40 duplicate, garbage lines that didn't mount when I went to debug it.

```
//share/shared /input_files cifs credentials=/home/svc_account/.smbcredentials,dir_mode=0777,file_mode=0777,uid=0,gid=0,noserverino\0400\0400 0 0
```

I'm considering resorting to lineinfile to add cifs mounts.

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
Please could you test it again with the latest version of the `mount` module and let us know if the problem still exists?

**Comment by ghost** [comment]
I have the same issue with a nfs4 mount.
 It is exactly as deekayen described it. I tried also several things like setting a fact to use it as var in mount: 
  opts: "{{ var }}" 

same behavior.
This is really nasty.
Tested with ansible 2.3.2.0

**Comment by hightower101** [comment]
With version 2.3 it is still not working.

**Comment by mprahl** [comment]
This works for me using Ansible 2.4.2.0 on a Fedora 27 node.

**Comment by adragoset** [comment]
Not working on rhel7 

```
fatal: [wagusno2.worker.wagcluster.prod.laitram.loc]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "boot": "yes",
            "dump": null,
            "fstab": null,
            "fstype": "cifs",
            "opts": "credentials=/home/wildcard_infrastructure_admin/smbcred,dir_mode=0777,file_mode=0777,uid=0,gid=0,noserverino 0 0",
            "passno": null,
            "path": "/mnt/app",
            "src": "\\\\usnodc01.prod.laitram.loc\\root\\v_drive\\team\\Intralox_NPD_Software_Dev\\_application_data_",
            "state": "mounted"
        }
    },
    "msg": "Error mounting /mnt/app: mount error(22): Invalid argument\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs)\n"
}
```

**Comment by Straevaras** [comment]
This is also broken for me on ansible-2.4.4.0.

**Comment by ansibot** [comment]
cc @skvidal
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aaronk1** [comment]
@seljuck is this still an issue in 2.7.x?

**Comment by seljuck** [comment]
@aaronk1  Sorry, I have not upgraded in sometime so I can't comment on 2.7

**Comment by andyeff** [comment]
Spotted this open issue - I'll be writing a playbook to mount an Azure CIFS file share to RHEL machines in the next day or two and I'll be using Ansible 2.7.5 so will report back on whether it works or not.

**Comment by andyeff** [comment]
Can confirm this is working for me as intended.

The relevant pair of tasks that do the work from my playbook:

```yaml
- name: Concatenate mount options
  set_fact:
    mount_opts_cat: "{{ item.value.mount_opts + ',credentials=' + cifs_creds }}"

- name: Mount Share
  mount:
    path: "{{ item.value.mountpoint }}"
    src: "{{ cifs_url }}"
    fstype: "cifs"
    opts: "{{ mount_opts_cat }}"
    passno: "{{ item.value.passno | default(omit) }}"
    state: mounted
  become: true
```

If it's of any use, my mount_opts before I add the credential location is: mount_opts: "vers=3.0,dir_mode=0777,file_mode=0777,sec=ntlmssp"
