### ISSUE TITLE
win_update not fully updating and not creating log

### ISSUE THREAD

**Issue by johnnysheppard-isode** [ansible/ansible#22938]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module: win_update
Plugins: related to winrm (maybe?)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel e084e8809e) last updated 2017/03/24 07:55:08 (GMT +100)
  config file = /home/js/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
[defaults]
host_key_checking = False
```

##### OS / ENVIRONMENT
Ansible Host: Ubuntu 16.04.
Managed Machine: Windows Server 2012 R2

##### SUMMARY
The **win_update** module doesn't seem to be working properly anymore. It doesn't find and install all the updates available, and it no longer produces a log file when using the *log_path* parameter. Nothing has changed with this module for a while, so I've tracked it down to the big re-write change to the way the "Win Exec Wrapper" works(8527013fbe539487e6998e806ec4e063eaeb299a). Using Ansible with the commit before this change (7bf56ceee39bbc8f2c3f01bc45b7a151bc54bcdc) works fine, but anything after this seems to produce the problems described.

I'm trying to find more information, but because of the changes made, I'm not finding it so easy to debug. Before the change, the win_update.ps1 module script seemed to be copied over to the windows tmp folder, and I could take a look at what was going on and run it locally on the machine in question. Now because of the way it works, it doesn't do this, so I'm finding it hard to track down what's going on. - Any advice?

##### STEPS TO REPRODUCE

1. Install Win2012 Server R2 using ISO.
2. Run the tasks listed below up to 10 times (the tasks will automatically stop when there are no more updates to find).
3. Check for `{{ ansible_env.TMP }*\wsus_log.txt`. Used to be there, now isn't.
4. Manually check for more updates. It used to capture them all, now it doesn't.

```yaml
- name: Update Windows
  win_updates:
    log_path: '{{ ansible_env.TMP }}\wsus_log.txt'
    category_names:
     - SecurityUpdates
     - CriticalUpdates
     - UpdateRollups
     - Updates
     - Application
     - ServicePacks
     - FeaturePacks
     - Guidance
     - Tools
  register: update_result
  failed_when: 'update_result.failed_update_count is defined and update_result.failed_update_count == update_result.found_update_count'
  when: "(update_result is not defined) or (update_result.found_update_count is defined and update_result.found_update_count > 0)"

- debug:
    var: update_result

- name: Reboot
  win_reboot:
    shutdown_timeout_sec: 3600
    reboot_timeout_sec: 3600
  when: '(update_result.failed is defined and update_result.failed == True) or (update_result.reboot_required is defined and update_result.reboot_required) or (update_result.failed_update_count is defined and update_result.failed_update_count > 0)'

```
##### EXPECTED RESULTS
Log file should be created and there should be no more updates to find.
##### ACTUAL RESULTS
Log file is not there, and if you run the windows update check manually, it finds a load more updates.
