### ISSUE TITLE
Archive option for git module 

### ISSUE THREAD

**Issue by Hipska** [ansible/ansible#22943]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
git

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It would be nice to also have, next to the `bare` option, a `archive` option. When using this option, Ansible will run the [git-archive](https://git-scm.com/docs/git-archive) command and produce a archive (tar or zip) file.

##### STEPS TO REPRODUCE
```yaml
# Example git archive from Ansible Playbooks
- git:
    repo: git://foosball.example.org/path/to/repo.git
    dest: /srv/repo-release-0.22.zip
    version: release-0.22
    archive: yes
    update: no

# Archive with latest commits
- git:
    repo: git://foosball.example.org/path/to/repo.git
    dest: /srv/repo-nightly.tar.gz
    archive: yes
```
##### EXPECTED RESULTS
Ansible creates the files `/srv/repo-release-0.22.zip` and `/srv/repo-nightly.tar.gz` by running `git archive`.

**Comment by Akasurde** [comment]
@s-hertel I would like to work on this issue. Can you please guide me ?

**Comment by Hipska** [comment]
The repo could also be a local bare repo, so pulling from the remote is not needed every time:
```yaml
# Archive with latest commits from local bare repo
- git:
    repo: /path/to/bare/repo.git
    dest: /srv/repo-nightly.tar.gz
    archive: yes
```
