### ISSUE TITLE
Ansible gives syntax error when defining a task with tempfile module

### ISSUE THREAD

**Issue by onderogluserdar** [ansible/ansible#22942]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

tempfile module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

default conf

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core) 

##### SUMMARY
When defining task with tempfile module, ansible gives syntax error.

##### STEPS TO REPRODUCE

ansible-playbook -i hosts site.yml -vvvv

```yaml
---
- hosts: Servers
  name: Deployment
  gather_facts: no
  remote_user: root
  #strategy: debug

  tasks:
    - name: install python bindings for SELinux
      yum: name={{item}} state=present
      with_items:
      - libselinux-python
      - libsemanage-python

    - name: test to see if SELinux is running
      command: getenforce
      register: sestatus
      changed_when: false
    
    - name: Install my SSH public keys on Remote Servers
      authorized_key: user=root state=present key="{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
    
    - name: create temporary build directory
      tempfile: state=directory suffix=build
      register: temp_path

    - name: print temp path
      debug: var=temp_path
```

##### EXPECTED RESULTS

Created a  temp file on remote machine.

##### ACTUAL RESULTS

```
[vagrant@ansible-node aaa-ansible-deployment]$ ansible-playbook -i hosts site.yml -vvvv
Using /etc/ansible/ansible.cfg as config file
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/vagrant/aaa-ansible-deployment/site.yml': line 23, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: create temporary build directory
      ^ here


The error appears to have been in '/vagrant/aaa-ansible-deployment/site.yml': line 23, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


    - name: create temporary build directory
      ^ here
```
