### ISSUE TITLE
parted module returns "[Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by worsco** [ansible/ansible#22955]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

parted

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
git pull from stable-2.3 branch and 'make rpm'
$ rpm -qa | grep ^ansible
ansible-2.3.0.0-100.git201703241924.58f002d.stable23.el7.centos.noarch

##### OS / ENVIRONMENT

CentOS 7.3 x86_64

##### SUMMARY

Cannot use the parted module.  Returns "[Errno 2] No such file or directory
##### STEPS TO REPRODUCE

```
ansible othermachine.office -s -K -m parted -a "device=/dev/sdb unit=MiB"
```
Also tried this in a role:
```
# Install parted
- name: Install parted
  yum:
    name: parted
    state: present

# Read device information
- name: read device information
  parted: device=/dev/sdb unit=MiB
  register: sdb_info
  become: yes
```
Returned with "[Errno 2] No such file or directory".

A "which parted" returns:
/usr/sbin/parted

##### EXPECTED RESULTS

I expected to be able to use the 'parted' module
##### ACTUAL RESULTS

```
SUDO password:
othermachine.office | FAILED! => {
    "changed": false,
    "cmd": "parted --version",
    "failed": true,
    "msg": "[Errno 2] No such file or directory",
    "rc": 2
}
```
