### ISSUE TITLE
Installing pip packages in virtualenv

### ISSUE THREAD

**Issue by mackwage** [ansible/ansible#22967]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
2.2.1.0

##### COMPONENT NAME
lib/ansible/modules/packaging/language/pip.py

##### SUMMARY
I am running into similar to a few others on here but didn't readily find a solution (sorry if my google-fu failed me).

I use Ansible to auto-setup Cowrie boxes. Had no issues on older versions of Ansible but after get getting everything up to date, run into an issue with the step where i install the needed pip packages into the virtual environment setup. 

Below is the error followed by the step in my playbook. If I ssh into the box and manually install the packages into the virtualenv, it works. Did syntax for this step change with recent versions of Ansible? I am running 2.2.1.0.

`failed: [honeypot] (item=twisted>=15.2.1) => {"failed": true, "item": "twisted>=15.2.1", "msg": "Unable to find pip in the virtualenv, cowrie-env, under any of these names: pip2, pip. Make sure pip is present in the virtualenv."}
failed: [honeypot1] (item=cryptography) => {"failed": true, "item": "cryptography", "msg": "Unable to find pip in the virtualenv, cowrie-env, under any of these names: pip2, pip. Make sure pip is present in the virtualenv."}`

- name: Setup virtualenv with needed pip packages
    become_user: cowrie
    pip: name="{{item}}" virtualenv="cowrie-env"
    with_items:
      - twisted>=15.2.1
      - cryptography
      - configparser
      - pyopenssl
      - gmpy2
      - service_identity
      - pycrypto
      - python-dateutil
      - tftpy
      - csirtgsd

**Comment by ansibot** [comment]
cc @mattupstate
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
Is this related to https://github.com/ansible/ansible-modules-core/issues/5347 ?

https://github.com/ansible/ansible-modules-core/issues/5347 should have been fixed in https://github.com/ansible/ansible-modules-core/pull/5453  (and backported to stable-2.2 branch in commit 8f0ab373d59fd59fbb2942e870ebc6502dce0f89)

Need more info:
- what version of python/pip is used by the cowrie-env virtualenv?
- Can you provide the output of 'ansible --version' ?

**Comment by mackwage** [comment]
`ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides`

`pip --version
pip 9.0.1 from /home/cowrie/cowrie-env/local/lib/python2.7/site-packages (python 2.7)`

**Comment by ioggstream** [comment]
@mackwage the following playbook reproduces the issue. What happens if you use an absolute path for the virtualenv like shown in the docs?
 

```
- hosts: localhost
  tags: broken
  tasks:
  - name: cleanup
    become_user: a
    file: 
      path: /home/a/a-venv
      state: absent
      force: yes
  - name: Setup virtualenv with needed pip packages
    become_user: a
    pip: 
      name: "{{item}}" 
      virtualenv: "a-venv"
    with_items:
    - twisted>=15.2.1

- hosts: localhost
  tags: working
  tasks:
  - name: cleanup
    become_user: a
    file: 
      path: /tmp/venv
      state: absent
      force: yes
  - name: Setup virtualenv with needed pip packages
    become_user: a
    pip: 
      name: "{{item}}" 
      virtualenv: /tmp/venv
    with_items:
    - twisted>=15.2.1

```

**Comment by ansibot** [comment]
cc @lujeni @robinro
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wvidana** [comment]
@ioggstream I just tried using full paths and it finally worked.

Note that i'm trying to setup a python3.6 environment.

My error was `Unable to find pip in the virtualenv, my_env, under any of these names: pip2, pip. Make sure pip is present in the virtualenv.`

This is my local ansible installation
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 13 2017, 15:15:09) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Fails
```
- name: installing pip packages
  pip:
    requirements: "requirements.txt"
    virtualenv: "my_env"
    virtualenv_python: python3.6
    chdir: /my_app
  become_user: my_user
```

### Succeeds
```
- name: installing pip packages
  pip:
    requirements: "/my_app/requirements.txt"
    virtualenv: "/my_app/my_env"
    virtualenv_python: python3.6
  become_user: my_user
```
### Extra bug with shell module and virtualenv
I must also add that trying to create the virtualenv with the shell module also failed
```
- name: creating new virtualenv envs
  shell: virtualenv -p /usr/bin/python3.6 my_env
  args:
    chdir: /my_app
  become_user: /my_user
```
That code resulted in a broken `python3` binary inside the virtualenv that was actually python 2.7

**Comment by cropr** [comment]
I can confirm the bug.  If the virtualenv parameter is  specified as a relative path, the command fails

**Comment by weskerfoot** [comment]
The suggested workaround seems to break if you are trying to use pyenv as well. Pyenv expects you to give it the name of a virtualenv, not the path to one as far as I can tell.

**Comment by weskerfoot** [comment]
@woqer @ioggstream The workaround breaks with pyenv:

`fatal: [test]: FAILED! => {"changed": false, "cmd": "/home/wes/.pyenv/bin/pyenv virtualenv 3.6.6 --system-site-packages /home/wes/.pyenv/versions/3.6.6/envs/test_venv", "failed": true, "msg": "\n:stderr: pyenv-virtualenv: no slash allowed in virtualenv name.\n"}`

**Comment by ansibot** [comment]
cc @webknjaz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by TeraInferno** [comment]
I found a workaround to install packages with pip into a virtualenv managed by pyenv. As this issue has been around for awhile, this workaround may help other ansible users until the pip module is able to handle pyenv managed virtualenvs. 

The workaround avoids using the pip module and instead just executes some shell commands. I am providing some variables I used, a *.pyenvrc* file I created, and the ansible task that does the shell magic. 

**Variables**:
```yaml
# Installation paths
pyenv_root: "{{ ansible_env.HOME }}/.pyenv"
pyenv_rc: "{{ pyenv_root }}/.pyenvrc"
# Whatever your virtualenv is named
pyenv_venv_name: "foo_virtualenv"
project_dir: /path/to/your/project
```

**Tasks**:

```yaml
- name: Pip - install requirements using shell
  shell: |
    # cd to project directory
    cd {{ project_dir }}
    # Check to see if we are already inside a virtualenv
    if ! [[ ${VIRTUAL_ENV} ]]; then
    	# Load pyenv into the shell
        source {{ pyenv_rc }}
        # Activate the virtualenv
        pyenv activate {{ pyenv_venv_name }}
    fi
    # Install python requirements 
    pip install -r requirements.txt
  args:
    executable: /bin/bash
  register: pip_script_result
```


Contents of *.pyenvrc*:
```bash
# Add pyenv into path if installed into default location
export PYENV_ROOT="{{ pyenv_root }}"
export PATH="${PYENV_ROOT}/bin:${PATH}"

# Initialise pyenv and pyenv-virtualenv if installed
if [[ -d $HOME/.pyenv ]];then
    eval "$(pyenv init -)"
    if [ -d "${PYENV_ROOT}/plugins/pyenv-virtualenv" ]; then
        eval "$(pyenv virtualenv-init -)"
    fi
fi

# Disable prompt changing
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
```

In the above example, I installed the contents of *requirements.txt* using `pip` into my pyenv managed virtualenv.

**Comment by webknjaz** [comment]
@weskerfoot @TeraInferno `pyenv` is a custom wrapper in the style of one-ring-to-rule-them-all. It's totally incompatible with `virtualenv` interfaces.

Yet, if you create a venv using `pyenv` separately and then feed it to `pip` module this should work. The usual path for such virtualenvs would be smth like `${PYENV_ROOT:~/.pyenv}/versions/{{ venv_name }}`.

Since `pyenv` is a separate Python and virtualenv manager, it'd require a separate module, which is out of the scope of the `pip` module.

**Comment by weskerfoot** [comment]
@webknjaz Thanks, I had realized that after but forgot to update my comments

**Comment by sover02** [comment]
A dirty workaround. It's not beautiful but it solves the initial problem for now:
```
- name: Get present working directory
  become: no
  command: pwd
  register: pwd
  changed_when: false

- name: Install requirements for my_script.py in a new virtualenv
  become: no
  pip:
    chdir: "{{ pwd.stdout }}"
    virtualenv: "venv_my_script"
    requirements: "my_project/requirements.txt"
```
