### ISSUE TITLE
Unable to find in expected paths

### ISSUE THREAD

**Issue by TinajaLabs** [ansible/ansible#22970]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
command: bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
normal

##### OS / ENVIRONMENT
Ansible running on Ubuntu 16.04
Managing Rasbian - Debian Jessie

##### SUMMARY
I am trying to execute the following on a raspberry pi (Rasbian - Debian Jessie)
```
bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)
```
I couldn't get that to work so, an alternative, I am downloading the script in one step and executing it in another step (see the yml definition below).

The script gets downloaded into the /home/pi directory but ansible complains that the file cannot be found.

##### STEPS TO REPRODUCE

That command downloads and runs a script to install node-red, the latest node.js, and the latest npm.

The installation requires that it be installed as user pi.

```yaml
---

- hosts: mf-tinaja-co
  remote_user: root

  tasks:

    # - name: install node-red, npm
    #   command: bash <(curl -sL https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered)
    #   become: yes
    #   become_user: pi

    - name: Download node-red installer
      get_url: 
        url: https://raw.githubusercontent.com/node-red/raspbian-deb-package/master/resources/update-nodejs-and-nodered
        dest: /home/pi/update-nodejs-and-nodered.sh
        mode: 0755
      become: yes
      become_user: pi


    - name: Execute the node-red installer
      script: /home/pi/update-nodejs-and-nodered.sh
      become: yes
      become_user: pi


    - name: config nodered systemd 
      command: systemctl enable nodered.service
```

##### EXPECTED RESULTS
that the above works...

##### ACTUAL RESULTS
Get an error:
```
Unable to find '/home/pi/update-nodejs-and-nodered.sh' in expected paths.
```
The file is, in fact, there.
```
root@mf-tinaja-co:/home/pi# ls -la
total 40
drwxr-xr-x 2 pi   pi    4096 Mar 25 11:04 .
drwxr-xr-x 3 root root  4096 Mar  3 15:27 ..
-rw------- 1 pi   pi      99 Mar 25 10:08 .bash_history
-rw-r--r-- 1 pi   pi     220 Mar  3 15:27 .bash_logout
-rw-r--r-- 1 pi   pi    3512 Mar  3 15:27 .bashrc
-rw-r--r-- 1 pi   pi     675 Mar  3 15:27 .profile
-rwxr-xr-x 1 pi   pi   15454 Mar 25 11:04 update-nodejs-and-nodered.sh
```

The execution of the task with -vvvv:
```
TASK [Execute the node-red installer] ******************************************
task path: /etc/ansible/mf-tinaja-co.yml:22
<mf-tinaja-co> ESTABLISH SSH CONNECTION FOR USER: root
<mf-tinaja-co> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r mf-tinaja-co '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1490439855.3-70093354419105 `" && echo ansible-tmp-1490439855.3-70093354419105="` echo /tmp/ansible-tmp-1490439855.3-70093354419105 `" ) && sleep 0'"'"''
fatal: [mf-tinaja-co]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Unable to find '/home/pi/update-nodejs-and-nodered.sh' in expected paths."
}
        to retry, use: --limit @/etc/ansible/mf-tinaja-co.retry
```

Thanks for any tips,
Chris.
