### ISSUE TITLE
loop item not working with include_role

### ISSUE THREAD

**Issue by snowsky** [ansible/ansible#22982]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel ac74520b6f) last updated 2017/03/26 18:45:42 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: cluster
  strategy: debug
  gather_facts: no
  tasks:
    - name: Execute test role
      include_role:
        name: "testrole_{{item}}"
      with_items:
      - 'one'
      - 'two'
      - 'three'
```

##### EXPECTED RESULTS

playbook will include 3 roles.
##### ACTUAL RESULTS

```
root@ubuntu-xenial:~/ansible# ansible-playbook testPlaybook.yml -vvvvvvvv
No config file found; using defaults
Loading callback plugin default of type stdout, v2.0 from /home/ubuntu/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: testPlaybook.yml ***************************************************************************************************************************************
1 plays in testPlaybook.yml

PLAY [cluster] ***************************************************************************************************************************************************
META: ran handlers

TASK [Execute test role] *****************************************************************************************************************************************
task path: /home/ubuntu/ansible/testPlaybook.yml:6
ERROR! 'item' is undefined
```

```

```
