### ISSUE TITLE
v2.2.1 local_action with_fileglob trying to ssh to localhost, v2.1.2 doesn't

### ISSUE THREAD

**Issue by berney** [ansible/ansible#22987]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- local_action
- with_fileglob

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /home/ansible/co/work/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```
nocows = 1
inventory = production
vault_password_file = xxx
```
* no `ANSIBLE_`* environment variables

##### OS / ENVIRONMENT

* Linux 4

##### SUMMARY

In ansible v2.1.2 local_action would run python modules directly on localhost, after upgrading to ansible v2.2.1 it tries to ssh to localhost (which fails auth). No changes to playbooks/roles/etc, I rolled back ansible version to verify behavioural difference.

##### STEPS TO REPRODUCE

breakage.yml: -
```yaml
---
- hosts: somegroup
  tasks:
    - name: broken local_action
      local_action: command echo "{{item}}"
      with_fileglob:
        - break*.yml
```

##### EXPECTED RESULTS

run command module locally, echoing: `breakage.yml`

##### ACTUAL RESULTS

- Ansible v2.2.1 tries to SSH to localhost

##### Notes
- System is air gapped so hard for me to copy-paste.
- I have simplified the reproduction from complex config I hit it in to simple playbook (no roles) above and worked out that it only happens when `with_fileglob` is used.
- `with_items` works in both versions
- `with_fileglob` only works properly in v2.1.2, broken in v.2.2.1

```

```
