### ISSUE TITLE
roles: cannot take a variable list, it must be inline

### ISSUE THREAD

**Issue by smemsh** [ansible/ansible#22985]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
roles

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### SUMMARY

the `roles:` keyword cannot take a list that is not specified inline.  that is, it cannot be a variable.

##### STEPS TO REPRODUCE

```
- hosts: localhost
  gather_facts: false

  vars:
    whatroles:
      - role1
      - role2
      - role3

  roles: '{{whatroles}}'
```

##### EXPECTED RESULTS

execute the give list of roles

##### ACTUAL RESULTS

```
ERROR! A malformed role declaration was encountered.

The error appears to have been in '/home/scott/src/setup/test/test.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- hosts: all
  ^ here

```
