### ISSUE TITLE
sequence lookup shortcut syntax doesn't work and wrong docs

### ISSUE THREAD

**Issue by berlic** [ansible/ansible#22988]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
`sequence` lookup plugin

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```
2.1, 2.3 and 2.4 have the same bug.

##### CONFIGURATION
Standard config

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`with_sequence` shortcut syntax `[start-]end[/stride][:format]` is not honoured.

##### STEPS TO REPRODUCE
```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - debug:
        msg: "{{ item }}"
      with_sequence: '5-6'
```

##### EXPECTED RESULTS
Loop over [5,6]:
```
TASK [debug] *******************************************************************
ok: [localhost] => (item=5) => {
    "item": "5",
    "msg": "5"
}
ok: [localhost] => (item=6) => {
    "item": "6",
    "msg": "6"
}
```

##### ACTUAL RESULTS
Parameter error:
```
TASK [debug] *******************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "unknown error parsing with_sequence arguments: u'5-6'. Error was: unrecognized arguments to with_sequence: [u'_raw_params']"}
```

Also there is wrong parameters passing in the docs:
```
    - user:
        name: "{{ item }}"
        state: present
        groups: "evens"
      with_sequence:
        - start: 0
        - end: 32
        - format: testuser%02x
```

Parameters can be passed to `with_sequence` only as string, not as list or dict.
