### ISSUE TITLE
Filter quote fails to escape concatenated strings

### ISSUE THREAD

**Issue by Nirkus** [ansible/ansible#22992]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Filter `quote` from filter plugin `core`

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
```
$ lsb_release -icrd
Distributor ID: Debian
Description:    Debian GNU/Linux 8.7 (jessie)
Release:        8.7
Codename:       jessie
```

##### SUMMARY
When trying to escape concatenated strings using the quote filter, I get a stack trace complaining about:
`ValueError: No closing quotation`
Using the same string w/o concatenating it within the template expression works fine.

Additionally, the quote filter does not produce a string escaped as a single shell token when called on a tuple or list.

##### STEPS TO REPRODUCE

Execute the following play to reproduce:

```yaml

- hosts: test
  tasks:
  - name: set test fact
    set_fact:
      test_eins: /tmp/te'st
      test_zwei: /tmp/te'st/static_component

  - name: test shell quote of variable
    shell: |
        echo {{ test_zwei | quote }}
    args:
      executable: "/bin/bash"

  - name: test shell quote of concat string
    shell: |
        echo {{ test_eins + '/static_component' | quote }}
    args:
      executable: "/bin/bash"

```

##### EXPECTED RESULTS
I excpected the strings to be concatenated to a single string and the resulting string to be escaped as a single shell token.

##### ACTUAL RESULTS
The third task (string concatenated) stack traces:

```
..
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_HKlyey/ansible_module_command.py", line 212, in <module>
    main()
  File "/tmp/ansible_HKlyey/ansible_module_command.py", line 189, in main
    rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell, encoding=None)
  File "/tmp/ansible_HKlyey/ansible_modlib.zip/ansible/module_utils/basic.py", line 2162, in run_command
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

fatal: [test.example.invalid]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "command"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_HKlyey/ansible_module_command.py\", line 212, in <module>\n    main()\n  File \"/tmp/ansible_HKlyey/ansible_module_command.py\", line 189, in main\n    rc, out, err = module.run_co
mmand(args, executable=executable, use_unsafe_shell=shell, encoding=None)\n  File \"/tmp/ansible_HKlyey/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2162, in run_command\n  File \"/usr/lib/python2.7/shlex.py\", line 279, in split\n    return list(l
ex)\n  File \"/usr/lib/python2.7/shlex.py\", line 269, in next\n    token = self.get_token()\n  File \"/usr/lib/python2.7/shlex.py\", line 96, in get_token\n    raw = self.read_token()\n  File \"/usr/lib/python2.7/shlex.py\", line 172, in read_token\n    raise
 ValueError, \"No closing quotation\"\nValueError: No closing quotation\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}

```

**Comment by alikins** [comment]
I can reproduce with devel/

repro example at https://github.com/alikins/ansible-bug-repro/tree/master/quote_filter_concat_22992

playbook:
``` yaml
[fedora-25:ansible (devel % u=)]$ cat repro/quote_filter_concat_22992/test.yml 
- hosts: localhost
  gather_facts: false
  tasks:
  - name: set test fact
    set_fact:
      test_eins: /tmp/te'st
      test_zwei: /tmp/te'st/static_component

  - name: debug shell quote filter
    debug:
      msg: "{{ test_zwei }} :  {{ test_zwei | quote }}"

  - name: debug shell quote filter concat string
    debug:
      msg: "{{ test_eins + '/static_component'  }} :  {{ test_eins + '/static_component'| quote }}"

  - name: test shell quote of variable
    shell: |
        echo {{ test_zwei | quote }}
    args:
      executable: "/bin/bash"

  - name: test shell quote of concat string
    shell: |
        echo {{ test_eins + '/static_component' | quote }}
    args:
      executable: "/bin/bash"
```

output: 
``` 
[fedora-25:ansible (devel % u=)]$ ansible --version
ansible 2.4.0 (devel 36e24c53c6) last updated 2017/03/27 11:05:54 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

[fedora-25:ansible (devel % u=)]$ ansible-playbook -vvv repro/quote_filter_concat_22992/test.yml 
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml ********************************************************************************************************************************************************************************
1 plays in repro/quote_filter_concat_22992/test.yml

PLAY [localhost] **********************************************************************************************************************************************************************************
META: ran handlers

TASK [set test fact] ******************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/quote_filter_concat_22992/test.yml:4
ok: [localhost] => {
    "ansible_facts": {
        "test_eins": "/tmp/te'st", 
        "test_zwei": "/tmp/te'st/static_component"
    }, 
    "changed": false
}

TASK [debug shell quote filter] *******************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/quote_filter_concat_22992/test.yml:9
ok: [localhost] => {
    "changed": false, 
    "msg": "/tmp/te'st/static_component :  '/tmp/te'\"'\"'st/static_component'"
}

TASK [debug shell quote filter concat string] *****************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/quote_filter_concat_22992/test.yml:13
ok: [localhost] => {
    "changed": false, 
    "msg": "/tmp/te'st/static_component :  /tmp/te'st/static_component"
}

TASK [test shell quote of variable] ***************************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/quote_filter_concat_22992/test.yml:17
Using module file /home/adrian/src/ansible/lib/ansible/modules/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/adrian/.ansible/tmp/ansible-tmp-1490628040.91-64661470774106 `" && echo ansible-tmp-1490628040.91-64661470774106="` echo /home/adrian/.ansible/tmp/ansible-tmp-1490628040.91-64661470774106 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpleO0Vu TO /home/adrian/.ansible/tmp/ansible-tmp-1490628040.91-64661470774106/command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1490628040.91-64661470774106/ /home/adrian/.ansible/tmp/ansible-tmp-1490628040.91-64661470774106/command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1490628040.91-64661470774106/command.py; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1490628040.91-64661470774106/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "cmd": "echo '/tmp/te'\"'\"'st/static_component'", 
    "delta": "0:00:00.002759", 
    "end": "2017-03-27 11:20:41.064959", 
    "invocation": {
        "module_args": {
            "_raw_params": "echo '/tmp/te'\"'\"'st/static_component'", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": "/bin/bash", 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2017-03-27 11:20:41.062200", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "/tmp/te'st/static_component", 
    "stdout_lines": [
        "/tmp/te'st/static_component"
    ]
}

TASK [test shell quote of concat string] **********************************************************************************************************************************************************
task path: /home/adrian/src/ansible/repro/quote_filter_concat_22992/test.yml:23
Using module file /home/adrian/src/ansible/lib/ansible/modules/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/adrian/.ansible/tmp/ansible-tmp-1490628041.11-30361013942004 `" && echo ansible-tmp-1490628041.11-30361013942004="` echo /home/adrian/.ansible/tmp/ansible-tmp-1490628041.11-30361013942004 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpgWvxMR TO /home/adrian/.ansible/tmp/ansible-tmp-1490628041.11-30361013942004/command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1490628041.11-30361013942004/ /home/adrian/.ansible/tmp/ansible-tmp-1490628041.11-30361013942004/command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1490628041.11-30361013942004/command.py; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1490628041.11-30361013942004/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_2beKYC/ansible_module_command.py", line 220, in <module>
    main()
  File "/tmp/ansible_2beKYC/ansible_module_command.py", line 197, in main
    rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell, encoding=None)
  File "/tmp/ansible_2beKYC/ansible_modlib.zip/ansible/module_utils/basic.py", line 2388, in run_command
  File "/usr/lib64/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib64/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib64/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib64/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_2beKYC/ansible_module_command.py\", line 220, in <module>\n    main()\n  File \"/tmp/ansible_2beKYC/ansible_module_command.py\", line 197, in main\n    rc, out, err = module.run_command(args, executable=executable, use_unsafe_shell=shell, encoding=None)\n  File \"/tmp/ansible_2beKYC/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2388, in run_command\n  File \"/usr/lib64/python2.7/shlex.py\", line 279, in split\n    return list(lex)\n  File \"/usr/lib64/python2.7/shlex.py\", line 269, in next\n    token = self.get_token()\n  File \"/usr/lib64/python2.7/shlex.py\", line 96, in get_token\n    raw = self.read_token()\n  File \"/usr/lib64/python2.7/shlex.py\", line 172, in read_token\n    raise ValueError, \"No closing quotation\"\nValueError: No closing quotation\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/home/adrian/src/ansible/repro/quote_filter_concat_22992/test.retry

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=1   

```

**Comment by alikins** [comment]
Also tested this on older versions (2.x) and they get the same error.

Suspect module_utiles/basic.py needs to be catching exceptions from where shlex.split() ends up being used.

**Comment by alikins** [comment]
Try using the quote filter before the concat

``` yaml
- hosts: localhost
  gather_facts: false
  tasks:
  - name: set test fact
    set_fact:
      test_eins: /tmp/te'st
      test_zwei: /tmp/te'st/static_component

  - name: debug shell quote filter
    debug:
      msg: "{{ test_zwei }} :  {{ test_zwei | quote }}"

  - name: debug shell quote filter concat string
    debug:
      msg: "{{ test_eins + '/static_component'  }} :  {{ test_eins + '/static_component'| quote }}"

  - name: debug shell quote filter concat string
    debug:
      msg: "{{ test_eins + '/static_component'  }} :  {{ test_eins | quote + '/static_component'}}"

  - name: test shell quote of variable
    shell: |
        echo {{ test_zwei | quote }}
    args:
      executable: "/bin/bash"

  # try the quote before the concat
  - name: test shell quote of concat string quote after test_eins before concat
    shell: |
        echo {{ test_eins | quote + '/static_component'}}
    args:
      executable: "/bin/bash"

      #  - name: test shell quote of concat string
      #    shell: |
      #        echo {{ test_eins + '/static_component' | quote }}
      #    args:
      #      executable: "/bin/bash"
```

output:

```
[fedora-25:quote_filter_concat_22992 (master %)]$ ansible-playbook -vvv test.yml 
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml ********************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [localhost] **********************************************************************************************************************************************************************************
META: ran handlers

TASK [set test fact] ******************************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/quote_filter_concat_22992/test.yml:4
ok: [localhost] => {
    "ansible_facts": {
        "test_eins": "/tmp/te'st", 
        "test_zwei": "/tmp/te'st/static_component"
    }, 
    "changed": false
}

TASK [debug shell quote filter] *******************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/quote_filter_concat_22992/test.yml:9
ok: [localhost] => {
    "changed": false, 
    "msg": "/tmp/te'st/static_component :  '/tmp/te'\"'\"'st/static_component'"
}

TASK [debug shell quote filter concat string] *****************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/quote_filter_concat_22992/test.yml:13
ok: [localhost] => {
    "changed": false, 
    "msg": "/tmp/te'st/static_component :  /tmp/te'st/static_component"
}

TASK [debug shell quote filter concat string] *****************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/quote_filter_concat_22992/test.yml:17
ok: [localhost] => {
    "changed": false, 
    "msg": "/tmp/te'st/static_component :  '/tmp/te'\"'\"'st'/static_component"
}

TASK [test shell quote of variable] ***************************************************************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/quote_filter_concat_22992/test.yml:21
Using module file /home/adrian/src/ansible/lib/ansible/modules/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/adrian/.ansible/tmp/ansible-tmp-1490628651.42-188445421554025 `" && echo ansible-tmp-1490628651.42-188445421554025="` echo /home/adrian/.ansible/tmp/ansible-tmp-1490628651.42-188445421554025 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpiUt8Dk TO /home/adrian/.ansible/tmp/ansible-tmp-1490628651.42-188445421554025/command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1490628651.42-188445421554025/ /home/adrian/.ansible/tmp/ansible-tmp-1490628651.42-188445421554025/command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1490628651.42-188445421554025/command.py; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1490628651.42-188445421554025/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "cmd": "echo '/tmp/te'\"'\"'st/static_component'", 
    "delta": "0:00:00.002570", 
    "end": "2017-03-27 11:30:51.577011", 
    "invocation": {
        "module_args": {
            "_raw_params": "echo '/tmp/te'\"'\"'st/static_component'", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": "/bin/bash", 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2017-03-27 11:30:51.574441", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "/tmp/te'st/static_component", 
    "stdout_lines": [
        "/tmp/te'st/static_component"
    ]
}

TASK [test shell quote of concat string quote after test_eins before concat] **********************************************************************************************************************
task path: /home/adrian/src/ansible-bug-repro/quote_filter_concat_22992/test.yml:27
Using module file /home/adrian/src/ansible/lib/ansible/modules/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: adrian
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/adrian/.ansible/tmp/ansible-tmp-1490628651.63-203141953939608 `" && echo ansible-tmp-1490628651.63-203141953939608="` echo /home/adrian/.ansible/tmp/ansible-tmp-1490628651.63-203141953939608 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpVgote5 TO /home/adrian/.ansible/tmp/ansible-tmp-1490628651.63-203141953939608/command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/adrian/.ansible/tmp/ansible-tmp-1490628651.63-203141953939608/ /home/adrian/.ansible/tmp/ansible-tmp-1490628651.63-203141953939608/command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/adrian/.ansible/tmp/ansible-tmp-1490628651.63-203141953939608/command.py; rm -rf "/home/adrian/.ansible/tmp/ansible-tmp-1490628651.63-203141953939608/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "cmd": "echo '/tmp/te'\"'\"'st'/static_component", 
    "delta": "0:00:00.002274", 
    "end": "2017-03-27 11:30:51.775491", 
    "invocation": {
        "module_args": {
            "_raw_params": "echo '/tmp/te'\"'\"'st'/static_component", 
            "_uses_shell": true, 
            "chdir": null, 
            "creates": null, 
            "executable": "/bin/bash", 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2017-03-27 11:30:51.773217", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "/tmp/te'st/static_component", 
    "stdout_lines": [
        "/tmp/te'st/static_component"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=2    unreachable=0    failed=0   
```
