### ISSUE TITLE
[parted] module 'parted' is not idempotent

### ISSUE THREAD

**Issue by worsco** [ansible/ansible#22996]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

parted

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
git pull from stable-2.3 branch and 'make rpm'
$ rpm -qa | grep ^ansible
ansible-2.3.0.0-100.git201703241924.58f002d.stable23.el7.centos.noarch

##### OS / ENVIRONMENT

CentOS 7.3 x86_64

##### SUMMARY

First run of parted module is successful.
Second run of parted module is not idempotent, returns "parted: invalid token: primary"
##### STEPS TO REPRODUCE

```
ansible-playbook config-partition.yml -s -K --extra-vars="target=somemachine.domain.tld"
```
Inside a role is the following:
```
# Install parted
- name: Install parted
  yum:
    name: parted
    state: present

# Use entire storage for /dev/sdb1 (default)
- name: NFS parted /dev/sdb
  parted:
    label: gpt
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present
  environment:
    PATH: "/usr/bin:/usr/sbin"
  become: yes
```
Returns with a "rc": 1 and "err": "parted: invalid token: primary\n"

}

##### EXPECTED RESULTS

I expected to be able to use the 'parted' module in an idempotent way without trapping "rc: 1" errors.
##### ACTUAL RESULTS

```
Verbose output:
fatal: [somemachine.domain.tld]: FAILED! => {
    "changed": false,
    "err": "parted: invalid token: primary\n",
    "failed": true,
    "invocation": {
        "module_args": {
            "align": "optimal",
            "device": "/dev/sdb",
            "flags": [
                "lvm"
            ],
            "label": "gpt",
            "name": null,
            "number": 1,
            "part_end": "100%",
            "part_start": "0%",
            "part_type": "primary",
            "state": "present",
            "unit": "KiB"
        }
    },
    "msg": "Error while running parted script: parted -s -m -a optimal /dev/sdb -- unit KiB set 1 lvm on set 1 primary off",
    "out": "",
    "rc": 1
}
```

**Comment by ansibot** [comment]
cc @ColOfAbRiX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ColOfAbRiX** [comment]
It seems the code that manages flags is receiving wrong information. Let me dig more

**Comment by ColOfAbRiX** [comment]
I've patched the module, a feedback is appreciated. Thanks.

**Comment by ColOfAbRiX** [comment]
resolved_by_pr 23037

**Comment by abadger** [comment]
#23037 merged. Closing.

**Comment by kwohlfahrt** [comment]
This does not seem fixed. Specifically, if the `label` is specified, the partition table is always recreated, even if it already exists.

Running the following task:

```yaml
- name: Create partition
  become: yes
  parted:
    label: gpt
    state: present
    device: /dev/vda
    number: 1
    name: foo
```

Causes the results below, alternating on each run. Note the second destroys the partition:

```
TASK [Create partition] ********************************************************************************
changed: [debianvm] => {"changed": true, "disk": {"dev": "/dev/vda", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 10485760.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 10484736.0, "flags": [], "fstype": "", "num": 1, "size": 10483712.0, "unit": "kib"}], "script": "unit KiB mklabel gpt mkpart primary 0% 100% unit KiB name 1 foo"}
```

```
TASK [Create partition] ********************************************************************************
changed: [debianvm] => {"changed": true, "disk": {"dev": "/dev/vda", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 10485760.0, "table": "gpt", "unit": "kib"}, "partitions": [], "script": "unit KiB mklabel gpt"}
```

**Comment by ColOfAbRiX** [comment]
I've found the issue but I can't fix it today. I'll get back next week.

**Comment by ColOfAbRiX** [comment]
Please have a look at #22996, it fixes the issue reported by @kwohlfahrt

**Comment by kwohlfahrt** [comment]
The issue I reported appears fixed. There is a different issue now, in that the sizes are not correctly checked:

```
    - name: Create EFI partitions
      become: yes
      parted:
        label: gpt
        state: present
        device: /dev/vda
        part_start: 0%
        part_end: 512MiB
        number: 1
```

Results in:
```
changed: [vm] => {"changed": true, "disk": {"dev": "/dev/vda", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 10485760.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 524288.0, "flags": [], "fstype": "", "name": "primary", "num": 1, "size": 523264.0, "unit": "kib"}], "script": "unit KiB mkpart primary 0% 512MiB"}
```

And then:
```
ok: [vm] => {"changed": false, "disk": {"dev": "/dev/vda", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 10485760.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 524288.0, "flags": [], "fstype": "", "name": "primary", "num": 1, "size": 523264.0, "unit": "kib"}], "script": ""}
```

So far, this is expected. If I now edit the play to a different size (by changing `part_end`), it still reports OK and no change is made:

```
    - name: Create EFI partitions
      become: yes
      parted:
        label: gpt
        state: present
        device: /dev/vda
        part_start: 0%
        part_end: 1024MiB
        number: 1
```
```
ok: [vm] => {"changed": false, "disk": {"dev": "/dev/vda", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 10485760.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 524288.0, "flags": [], "fstype": "", "name": "primary", "num": 1, "size": 523264.0, "unit": "kib"}], "script": ""}
```
