### ISSUE TITLE
docker_container homedir ('/~') issue running localhost

### ISSUE THREAD

**Issue by Smuggla** [ansible/ansible#22999]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.0.0
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
OS X El Capitan Version 10.11.6

##### SUMMARY

Created a local playbook for building docker hosts for testing.

Moved config files for container into $USER '~/' dir

docker_container uses an incorrect path for '~/' when mounting volumes.

##### STEPS TO REPRODUCE

These are all done with 

```
- hosts: all
  connection: local
```

Prometheus Container

```
    - name: prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus
        command: -config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://127.0.0.1:9093/ -storage.local.path=/var/lib/prometheus/data -log.level=debug
        published_ports:
          - 9090:9090
        volumes:
        - "~/prometheus-dev/lib/prometheus/:/var/lib/prometheus/"
        - "~/prometheus-dev/etc/prometheus/:/etc/prometheus/"
```
From Debug

```
            "volumes": [
                "~/prometheus-dev/lib/prometheus/:/var/lib/prometheus/",
                "~/prometheus-dev/etc/prometheus/:/etc/prometheus/"
            ],
```

Prometheus cannot find any of the files in ~/

To get around this ran pwd command in ~/ and used output

```
    - name: check 
      shell: pwd
      args:
        chdir: ~/
      register: homedir

    - name: prometheus container
      docker_container:
        name: prometheus
        image: prom/prometheus
        command: -config.file=/etc/prometheus/prometheus.yml -alertmanager.url=http://127.0.0.1:9093/ -storage.local.path=/var/lib/prometheus/data -log.level=debug
        published_ports:
          - 9090:9090
        volumes:
        - "{{ homedir.stdout }}/prometheus-dev/lib/prometheus/:/var/lib/prometheus/"
        - "{{ homedir.stdout }}/prometheus-dev/etc/prometheus/:/etc/prometheus/"
      tags: docker, prometheus

```
From debug:
```
            "volumes": [
                "/Users/smuggla/prometheus-dev/lib/prometheus/:/var/lib/prometheus/",
                "/Users/smuggla/prometheus-dev/etc/prometheus/:/etc/prometheus/"
            ],
```

##### EXPECTED RESULTS
Access to ~/ of non-sudo user

##### ACTUAL RESULTS
~/ used is not that of user running playbook
