### ISSUE TITLE
Error in jinja parsing in shell task, but not name or debug msg.

### ISSUE THREAD

**Issue by welchwilmerck** [ansible/ansible#23009]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

shell doesn't fully honor jinja {% raw %} block.

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = <masked>/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Mac OS

##### SUMMARY

Jinja raw block works as expected to escape unbalanced jinja directives in many other places in a playbook, but not directly in shell.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local

  tasks:
  - name: |
           shell fails to treat jinja block openers ({% raw %}{# {{ {%{% endraw %}) as literal in raw block
           fails in both multiline and quoted
           Same construct is fine here in name and in debug msg.
           comment out shell tasks (with openers) below to verify that use in name or debug msg doesn't throw the error.
    debug:
      msg: "name, multiline worked"
  - name: "also works in name in quotes {% raw %}{# {{ {%{% endraw %}"
    debug:
      msg: "name, quoted worked"

  - name: "comment out this name and the two shell tasks below to stop error"
    shell:  "           {% raw %}             echo  '{#'  '{{' '{%'           {% endraw %}"
  - shell:  |
             {% raw %}             echo  '{#'  '{{' '{%'           {% endraw %}

  - name: "block closers are fine in shell ({% raw %} #} }} %} {% endraw %})"
    shell:  "           {% raw %}             echo  '#}'  '}}' '%}'           {% endraw %}"
  - shell:  |
            {% raw %}             echo  '#}'  '}}' '%}'           {% endraw %}

  - debug:
         msg: |
               {% raw %}             echo  '{#'  '{{' '{%'           {% endraw %}
  - debug:
         msg: "{% raw %}             echo  '{#'  '{{' '{%'           {% endraw %}"
...
```

##### EXPECTED RESULTS

```
TASK [command] ******************
changed: [localhost] => {"changed": true, "cmd": " echo '{#' '{{' '{%' ", ... , "stdout": "{# {{ {%", ...}
```
##### ACTUAL RESULTS

```
ERROR! failed at splitting arguments, either an unbalanced jinja2 block or quotes: {% raw %}             echo  '{#'  '{{' '{%'           {% endraw %}

The offending line appears to be:

  -  shell:  "            {% raw %}             echo  '{#'  '{{' '{%'           {% endraw %}"
     ^ here
```
