### ISSUE TITLE
win_command incorrectly parses args containing spaces

### ISSUE THREAD

**Issue by johnboy2** [ansible/ansible#23019]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_command

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
Windows Server 2012 r2 (target host); Ubuntu 16.04 (management system)

##### SUMMARY
Double-quoted commands containing spaces are incorrectly parsed by "win_command.ps1", causing arguments to be split incorrectly before execution.

##### STEPS TO REPRODUCE

Example playbook demonstrating this issue:

```yaml

- hosts: windows
  gather_facts: false
  tasks:
  - win_command: C:\windows\system32\netsh.exe advfirewall firewall show rule name="File and Printer Sharing (SMB-In)"
    register: win_command_output
    failed_when: false
  - debug: var=win_command_output
  vars:
    ansible_user: Administrator
    ansible_password: FIXME
    ansible_port: 5986
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
```

##### EXPECTED RESULTS

* win_command_output.rc == 0
* win_command_output.stdout encodes a table of firewall rule information.

##### ACTUAL RESULTS
* win_command_output.rc == 1
* win_command_output.stdout contains an usage/invocation error

##### NOTES
* The issue can be traced to incorrect handling of the command string _after_ it is passed to "win_command.ps1".
* The _relevant_ processing logic of the current implementation can be summarized as follows:
  1. It parses the command from a single string into a list of strings (and appears to do so correctly).
  1. It uses that list to infer the "command" (ie list's first entry), as distinct from the "arguments" (ie everything in the list _after_ the first entry, if any).
  1. It then re-assembles a single string containing _just_ the arguments by simply joining the individual arguments strings together with a space between each entry. **This is incorrect behavior whenever there are any arguments containing a space, tab, or double-quote.**
* For MS' escaping rules, see https://msdn.microsoft.com/en-us/library/17w5ykft.aspx.
* Workarounds may be developed using either "win_raw" or "win_shell".

**Comment by nitzmahone** [comment]
We delegated this behavior to Microsoft's own [CommandLineToArgvW](https://msdn.microsoft.com/en-us/library/windows/desktop/bb776391(v=vs.85).aspx) function so we didn't have to care. However, it doesn't appear that it's following the exact same rules that the shell does when parsing, as it strips the quotes from your example. :( Here's how we get it back: (pipes delimit individual post-parsed arg values as received from CommandLineToArgvW: ` netsh.exe|advfirewall|firewall|show|rule|name=iSCSI Service (TCP-Out)`

**Comment by nitzmahone** [comment]
The only reason we're using CommandLineToArgvW is for the handling of the initial executable- IIRC it's because `Process.Start()` doesn't support the underlying `CreateProcess` behavior where you can pass the raw command line including the executable in `lpCommandLine` (so we have to split the executable and set both `Filename` and `Arguments` on the `ProcessStartInfo`). I think our only options here (short of switching to P/Invoking `CreateProcess` and dealing with all the stream piping mess directly, which I'd rather not do) are to handle stripping off the initial executable ourselves, or to have the arg splitter post-process what `CommandLineToArgvW` did and remove the right bits from the original string. I'm leaning toward the former, since it's basically just quotes that we have to worry about.

**Comment by nitzmahone** [comment]
Yet another workaround that seems to fly with `win_command` is to backslash the embedded quotes (which is actually what https://msdn.microsoft.com/en-us/library/17w5ykft.aspx says). 

So it'd be: 
```
C:\windows\system32\netsh.exe advfirewall firewall show rule name=\"File and Printer Sharing (SMB-In)\"
```

Too many layers of escaping here- I'd be pretty nervous to post-process those and *add* the quotes...

**Comment by johnboy2** [comment]
RE escaping the dquotes, I like your suggestion for my specific case, but it is a kludge that is easily broken. In particular, it doesn't work for the reason you have implied, only works by accident in my specific case, and wouldn't work any more if ever win_command is modified to use CreateProcess instead.

Here's a breakdown:
- Version 1 (like the original)
  - Command line: `foo.exe name="bar baz" buz`
  - After breakup by CommandLineToArgvW:
    1. `foo.exe`
    1. `name=bar baz`
    1. `buz`
  - Arguments portion, after (improper) re-assembly in PS: `name=bar baz buz`  (note that the argument splitting points have been lost)
  - Final split to feed the subprocesses' `argv` array (done internally by MSVC):
    1. `foo.exe`
    1. `name=bar`
    1. `baz`
    1. `buz`
  - Result: Fail (first argument is incorrectly split into two)
- Version 2 (like your backslash-escaped suggestion)
  - Command line: `foo.exe name=\"bar baz\" buz`
  - Note: This one will work, but only through an accidental side-effect!
  - After breakup by CommandLineToArgvW:
    1. `foo.exe`
    1. `name="bar`
    1. `baz"`
    1. `buz`
  - Arguments portion, after (improper) re-assembly in PS: `name="bar baz" buz`
  - Final split to feed the subprocesses' `argv` array (done internally by MSVC):
    1. `foo.exe`
    1. `name=bar baz`
    1. `buz`
  - Result: Pass (but only due to common conventions -- so basically an accident)
- Version 3 (like your backslash escaped suggestion, but modified to no longer work)
  - Command line: `foo.exe name=\"bar___baz\" buz` (understand the triple-underscore as 3-spaces)
  - Note: This uses your backslash-escaping, but with a few extra spaces insert to demonstrate why that solution is special-case only.
  - After breakup by CommandLineToArgvW:
    1. `foo.exe`
    1. `name="bar`
    1. `baz"`
    1. `buz`
  - Arguments portion, after (improper) re-assembly in PS: `name="bar baz" buz`
  - Final split to feed the subprocesses' `argv` array (done internally by MSVC):
    1. `foo.exe`
    1. `name=bar baz`
    1. `buz`
  - Result: Fail (first argument is missing spacing content)

**Comment by johnboy2** [comment]
For my own use-cases, I did look into some modifications to win_command.ps1 (first as a custom parser/splitter, and then later as an escaping recombiner), but the MSVC rules are so irregular that it was very difficult to reason about correctness for _either_ approach. (Witness: whether backslashes are counted singly or pair-wise depends on what follows _after_ a complete BS-sequence! I mean, yikes!) So, yeah, totally agreed RE those approaches being messy and probably unwise.

Agreed also that `CreateProcess` looks like the only way to do this both correctly _and_ safely/sanely.

**Comment by Pantharian** [comment]
@nitzmahone I found this bug when trying to create a scheduled task. Originally a 'raw' command, it failed when the same arguments were passed to 'win_command'. 

However, using 'win_shell' with the 
```
 args:
    executable: cmd
```
I found I could run the same unmodified command successfully. e.g.

```
- name: Create "MyScheduledTask"
  win_shell: schtasks /CREATE /RU {{ansible_user}} /RP {{ansible_ssh_pass}} /SC ONCE /SD 01/01/1910 /ST 00:00 /TN "MyScheduledTask" /RL HIGHEST /F /TR "wmic service where `'name like `'MyScheduledTask%`'`' call stopservice"
  args:
    executable: cmd
  register: command_result
  failed_when: not ("SUCCESS:" in command_result.stdout)
```
