### ISSUE TITLE
setup module with delegate_facts broken on non-play hosts in 2.2.2

### ISSUE THREAD

**Issue by rouge8** [ansible/ansible#23023]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`setup` module/`delegate_facts`

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Using the `setup` module to gather facts from a host not in the play with `delegate_to` and `delegate_facts: true` no longer works on 2.2.2. Worked on 2.2.1 and works on `devel`.

This works on 2.2.2 if I use hostnames rather than looking up `{{ stack_name }}-db`.

##### STEPS TO REPRODUCE

```yaml
---

- hosts: web_servers
  tasks:
    - name: Gather DB server IP address
      setup: filter=ansible_default_ipv4
      delegate_to: "{{ stack_name }}-db"
      delegate_facts: true

    - debug: msg="{{ hostvars[stack_name + '-db']['ansible_default_ipv4']['address'] }}"
```

##### EXPECTED RESULTS

```
$ ansible-playbook -l some-stack-web playbook.yaml

PLAY [web_servers] *************************************************************

TASK [setup] *******************************************************************
ok: [some-stack-web]

TASK [Gather DB server IP address] *********************************************
ok: [some-stack-web -> some-stack-db]

TASK [debug] *******************************************************************
ok: [some-stack-web] => {
    "msg": "10.50.1.224"
}

PLAY RECAP *********************************************************************
some-stack-web          : ok=3    changed=0    unreachable=0    failed=0

Playbook run took 0 days, 0 hours, 0 minutes, 8 seconds
```

##### ACTUAL RESULTS

```
$ ansible-playbook -l some-stack-web playbook.yaml

PLAY [web_servers] *************************************************************

TASK [setup] *******************************************************************
ok: [some-stack-web]

TASK [Gather DB server IP address] *********************************************
ok: [some-stack-web -> some-stack-db]

TASK [debug] *******************************************************************
fatal: [some-stack-web]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'ansible_default_ipv4'\n\nThe error appears to have been in '/Users/andy/playbook.yaml': line 10, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug: msg=\"{{ hostvars[some_stack + '-db']['ansible_default_ipv4']['address'] }}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
	to retry, use: --limit @/Users/andy/playbook.retry

PLAY RECAP *********************************************************************
some-stack-web          : ok=2    changed=0    unreachable=0    failed=1

Playbook run took 0 days, 0 hours, 0 minutes, 9 seconds
```

**Comment by rouge8** [comment]
@jimi-c This is fixed in 2.3.0. Should I close it, or leave it open to fix on the 2.2.x branch?

**Comment by IngussNeilands** [comment]
Bug still exists in pip install git+git://github.com/ansible/ansible.git@v2.2.3.0-1

**Comment by bcoca** [comment]
fix should be in 2.3.1 (which is currently in RC1)

**Comment by IngussNeilands** [comment]
No bug is still in both rc1 and rc2 - ansible\.cache dir contains {{ item }} file

pip install git+git://github.com/ansible/ansible.git@v2.3.1.0-0.1.rc1
pip install git+git://github.com/ansible/ansible.git@v2.3.1.0-0.2.rc2

**Comment by jimi-c** [comment]
I can confirm this is working as expected in 2.3.1.0-1, and does not work in 2.2.3.0-1. The question is, is this something we want to backport?

**Comment by ptv-ldts** [comment]
Issue not fixed in 2.3.1.0-1 with remote hosts!

my Inventory
```
test1 ansible_connection=ssh
test2  ansible_connection=local
```

playbook1:
```
- hosts: test1
  tasks:
    - name: Gather DB server IP address
      setup: filter=ansible_default_ipv4
      delegate_to: "test2"
      delegate_facts: true
    - debug: msg="{{ hostvars['test2']['ansible_default_ipv4']['address'] }}"
```
RESULT: works as expected no error 

playbook2:

```
- hosts: test2
  tasks:
    - name: Gather DB server IP address
      setup: filter=ansible_default_ipv4
      delegate_to: "test1"
      delegate_facts: true
    - debug: msg="{{ hostvars['test1']['ansible_default_ipv4']['address'] }}"
```
RESULT: error

**Comment by asouchang** [comment]
Same issue here. I can confirm this defeat is not fixed in the latest 2.3.1.0 release.
It seems that `delegate_facts` is broken from 2.2.1.0 to 2.3.1.0. My workaround is downgrading to 2.2.0.0. It is the latest version which this function works.

**Comment by ansibot** [comment]
cc @david_obrien
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cacampbell** [comment]
Hi, me too thanks

```
---
# roles/gather-facts/tasks/main.yml
- setup: "{{ item[0] }}"
    filter: ansible_default_ipv4
  delegate_to: "{{ item[1] }}"
  delegate_facts: True
  when: hostvars[item[0]]['defualt_ipv4'] is not defined
  with_nested:
    - "{{ targets }}"
    - "{{ delegates }}"

---
# roles/gather-facts/defaults/main.yml

targets: "{{ groups['all'] }}"
delegates: [localhost]
```

Still getting 'ansible_default_ipv4 is undefined' for these hosts in the next task (when this is imported via import_role into a task list)
