### ISSUE TITLE
allow_duplicates handlers broken

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#23031]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### SUMMARY

Handlers broken for role with duplicates allowed.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  roles:
    - role: test
      wheel_position: front left
      tags: test
    - role: test
      wheel_position: front right
      tags: test
```

See attached zip with this role.

##### EXPECTED RESULTS

```
RUNNING HANDLER [test/wheel : rotate {{ wheel_position }} wheel] ***************
ok: [localhost] => {
    "msg": "rotating front left wheel"
}

RUNNING HANDLER [test/wheel : rotate {{ wheel_position }} wheel] ***************
ok: [localhost] => {
    "msg": "rotating front right wheel"
}
```

##### ACTUAL RESULTS

```
RUNNING HANDLER [test/wheel : rotate {{ wheel_position }} wheel] ***************
ok: [localhost] => {
    "msg": "rotating front left wheel"
}
```

[test.zip](https://github.com/ansible/ansible/files/875533/test.zip)

**Comment by estahn** [comment]
I suppose I'm running into the same issue:

```yaml
---
- name: test
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - { role: foobar, tasks: [foo] }
    - { role: foobar, tasks: [foo] }
```

Runs only once.
