### ISSUE TITLE
gitlab_project module changes each time

### ISSUE THREAD

**Issue by boxrick** [ansible/ansible#23039]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

https://docs.ansible.com/ansible/gitlab_project_module.html

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = ./ansible.cfg
  configured module search path = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A - Defaults

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Every time the module gitlab_project is used, it detects a change each and every time even if no values are changed. This appears when using a minimal set of configuration and all the options available.

##### STEPS TO REPRODUCE

```yaml
- name: Test
  gitlab_project:
    server_url: "https://{{ etckeeper_install_gitlab_url }}"
    validate_certs: false
    login_token: "{{ etckeeper_install_gitlab_token }}"
    name: my_first_project
    group: ansible
    issues_enabled: False
    wiki_enabled: True
    snippets_enabled: True
    state: present
  delegate_to: localhost
```

##### EXPECTED RESULTS

When no changes made, this shows as "ok"

##### ACTUAL RESULTS

Changes each and every time

```
TASK [etckeeper_install : Test] ***************************************************************************************************************************************************
task path: /home/user/ansible_test/roles-dev/etckeeper_install/tasks/configure.yml:54
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/source_control/gitlab_project.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: rickb
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-brmolsnpwbepprjunhdhwobqyhwjhnro; /usr/bin/python'"'"' && sleep 0'
changed: [bios -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "description": null,
            "group": "ansible",
            "issues_enabled": false,
            "login_password": null,
            "login_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": null,
            "merge_requests_enabled": true,
            "name": "my_first_project",
            "path": null,
            "public": false,
            "server_url": "https://git.internal.domain",
            "snippets_enabled": true,
            "state": "present",
            "validate_certs": false,
            "visibility_level": "0",
            "wiki_enabled": true
        }
    },
    "result": "Successfully created or updated the project my_first_project"
}
```
