### ISSUE TITLE
Jinja filters output trailing whitespace breaking idempotency

### ISSUE THREAD

**Issue by ypid** [ansible/ansible#23078]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
`lib/ansible/parsing/yaml/dumper.py:AnsibleDumper`

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 6c101087ac) last updated 2017/03/29 16:09:54 (GMT +200)
  config file = 
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

[and]
ansible 2.2.2.0 (stable-2.2 2273800f7c) last updated 2017/03/29 10:54:33 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 31a1f19cd8) last updated 2017/03/29 16:07:02 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD 921bc0d464) last updated 2017/03/29 14:42:48 (GMT +200)
```

##### CONFIGURATION
Ansible default. No changes.

##### OS / ENVIRONMENT
Isolated Debian Jessie VM on Qubes OS setup only for testing with Ansible devel.

##### SUMMARY
The `to_nice_json` filter and others like `indent` output trailing whitespace. That is not in itself a problem (although bad style). But in the case of `to_nice_json` it becomes a problem because it is potentially not idempotent which breaks CI which test for this property (e.g. DebOps).

Also note that the task itself outputs trailing whitespace (select the task output below).

##### STEPS TO REPRODUCE

```yaml
---

- hosts: localhost
  vars:
    input:
      - test: True
        test2:
          - 23
      - test: True

  tasks:

    - name: Jinja2 templating outputting trailing spaces which change depending
      debug:
        msg: "{{ (input | to_nice_json).split('\n') }}"

    # Workaround is part of https://github.com/debops/debops-playbooks/blob/master/templates/debops__tpl_macros.j2
    - name: Clean Jinja2 templating using workaround
      debug:
        msg: "{{ (input | to_nice_json | regex_replace(\"[ \\t\\r\\f\\v]+(\\n|$)\", \"\\1\")).split('\n') }}"
```

##### EXPECTED RESULTS

```
TASK [Clean Jinja2 templating using workaround]
ok: [localhost] => {
    "changed": false, 
    "msg": [
        "[", 
        "    {", 
        "        \"test\": true,", 
        "        \"test2\": [", 
        "            23", 
        "        ]", 
        "    },", 
        "    {", 
        "        \"test\": true", 
        "    }", 
        "]"
    ]
}
```

Example role in CI: https://travis-ci.org/debops/ansible-apt/builds/216374820

##### ACTUAL RESULTS

```
TASK [Jinja2 template outputting trailing spaces which change depending on next element]
ok: [localhost] => {
    "changed": false, 
    "msg": [
        "[", 
        "    {", 
        "        \"test\": true, ", 
        "        \"test2\": [", 
        "            23", 
        "        ]", 
        "    }, ", 
        "    {", 
        "        \"test\": true", 
        "    }", 
        "]"
    ]
}
```

Example role in CI: https://travis-ci.org/debops/ansible-apt/builds/216355310#L824-L825
