### ISSUE TITLE
iptables module invokes match with singe quotes

### ISSUE THREAD

**Issue by dev00** [ansible/ansible#23073]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

iptables

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

none

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

Using the `iptables` module with the `match` parameter will put the match entry in single quotes which will result in fails when using it with tools like ipset.

##### STEPS TO REPRODUCE

```yaml
name: this fails
become: true
hosts: localhost
tasks:
  - name: Install needed tools to make iptables rules permanent
    apt:
      name: "ipset"
      state: latest
      cache_valid_time: 3600

  - name: download list of chinese IP
    get_url:
      url: http://www.ipdeny.com/ipblocks/data/countries/cn.zone
      dest: /tmp/cn.zone

  - name: destroy all sets for ipset
    shell: ipset destroy

  - name: create net ipset for china
    shell: ipset -N china hash:net

  - name: Add each IP address from the downloaded list into the ipset 'china'
    shell: for i in $(cat /etc/cn.zone ); do ipset -A china $i; done

  - name: block china via iptables
    iptables:
       table: filter
       chain: INPUT
       protocol: tcp
       match: set --match-set china src
       jump: DROP
```

##### EXPECTED RESULTS

It should be invoked like:
```
iptables -t filter -A INPUT -p tcp -m set --match-set china src -j DROP
```
##### ACTUAL RESULTS

It fails because Ansible invokes it in a manner which results in fails:
```
iptables -t filter -A INPUT -p tcp -m 'set --match-set china src' -j DROP
```

Output
```
TASK [jumphost : block china via iptables] *************************************
fatal: [jumphost]: FAILED! => {"changed": false, "cmd": "/sbin/iptables -t filter -A INPUT -p tcp -m 'set --match-set china src' -j DROP", "failed": true, "msg": "iptables v1.6.0: Couldn't load match `set --match-set china src':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.6.0: Couldn't load match `set --match-set china src':No such file or directory\n\nTry `iptables -h' or 'iptables --help' for more information.\n", "stdout": "", "stdout_lines": []}
```

**Comment by ansibot** [comment]
cc @LinusU
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by LinusU** [comment]
I think that the quoting is the right thing to do here. How about adding a `matchSet` option?

**Comment by ansibot** [comment]
cc @sebastiendarocha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sebastiendarocha** [comment]
Hello @dev00 

Could you replace the "ISSUE TYPE" in the initial comment by "Feature Idea" instead of "Bug Report"

Thank you

**Comment by dev00** [comment]
@sebastiendarocha Done. Maybe we should add some information to the docs regarding working with ipset?

**Comment by BarbzYHOOL** [comment]
Could we instead have an "extra_args" parameter to deal with these special cases? I also have another special case that is not the same. There was already another case solved previously. Seems like it will be endless

Like this:

```
  - name: block china via iptables
    iptables:
       table: filter
       chain: INPUT
       protocol: tcp
       match: set
       jump: DROP
       extra_args:
           zone: 1
           match-set: china src
```

it would add "--zone 1" and "--match-set china src" to the command
