### ISSUE TITLE
docker dynamic inventory script ignores DOCKER_CONFIG_FILE environment variable

### ISSUE THREAD

**Issue by milo-minderbinder** [ansible/ansible#23095]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker dynamic inventory
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 097173c6f5) last updated 2017/03/29 12:35:28 (GMT -400)
  config file = /Users/milo/code/ansible-data/ansible.cfg
  configured module search path = [u'/Users/milo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

`ANSIBLE_CONFIG` points to mostly default config file, which only changes the inventory path (`inventory`) and roles path (`roles_path`) options.

Related to the `contrib/inventory/docker.py` dynamic inventory script in question for this issue, I have set the `DOCKER_CONFIG_FILE` environment variable to the absolute path of a custom docker config file which sets multiple docker hosts for use in building the dynamic inventory.
##### OS / ENVIRONMENT

N/A
##### SUMMARY

The documentation for the `docker.py` dynamic inventory script in `contrib/inventory` indicates that a docker configuration file can be specified by providing the `--config-file` cli argument or by setting the `DOCKER_CONFIG_FILE` environment variable. However, the environment variable is never checked, regardless of whether the `--config-file` option is given or not, or if the default/fallback `docker.yml` file exists or not.
##### STEPS TO REPRODUCE

* Copy the `docker.yml` example config file from `contrib/inventory/` to any directory (e.g. `/some/path/docker.yml`), and uncomment lines 64-74, e.g: 
    ```yaml
    defaults:
      host: unix:///var/run/docker.sock
      private_ssh_port: 22
      default_ip: 127.0.0.1

  hosts:
    - host: tcp://10.45.5.16:4243
      private_ssh_port: 2022
      default_ip: 172.16.3.45
    - host: tcp://localhost:4243
      private_ssh_port: 2029
    ```
* set the `DOCKER_CONFIG_FILE` environment variable to the path set above (`/some/path/docker.yml`)
* call the docker.py inventory script from the command line with `<ansible_root_dir>/contrib/inventory/docker.py --debug` and note that the debug output under `defaults:`, `hosts:`, and `auth params:` do not reflect the values set in the config file.

##### EXPECTED RESULTS

```yaml
defaults:

{
  "default_ip": "127.0.0.1", 
  "host": "unix:///var/run/docker.sock", 
  "private_ssh_port": 22
}
hosts: 

[
  {
    "api_version": "1.24", 
    "cacert_path": null, 
    "cert_path": null, 
    "default_ip": "172.16.3.45", 
    "default_ssh_port": 2022, 
    "docker_host": "tcp://10.45.5.16:4243", 
    "key_path": null, 
    "ssl_version": null, 
    "timeout": 60, 
    "tls": false, 
    "tls_hostname": "localhost", 
    "tls_verify": false
  }, 
  {
    "api_version": "1.24", 
    "cacert_path": null, 
    "cert_path": null, 
    "default_ip": "127.0.0.1", 
    "default_ssh_port": 2029, 
    "docker_host": "tcp://localhost:4243", 
    "key_path": null, 
    "ssl_version": null, 
    "timeout": 60, 
    "tls": false, 
    "tls_hostname": "localhost", 
    "tls_verify": false
  }
]
auth params:

  tls: False

  cacert_path: None

  timeout: 60

  default_ip: 172.16.3.45

  ssl_version: None

  tls_hostname: localhost

  docker_host: tcp://10.45.5.16:4243

  tls_verify: False

  key_path: None

  default_ssh_port: 2022

  cert_path: None

  api_version: 1.24
```
##### ACTUAL RESULTS

```yaml
defaults:

{}
hosts: 

[
  {
    "api_version": "1.24", 
    "cacert_path": null, 
    "cert_path": null, 
    "default_ip": "127.0.0.1", 
    "default_ssh_port": "22", 
    "docker_host": "unix://var/run/docker.sock", 
    "key_path": null, 
    "ssl_version": null, 
    "timeout": 60, 
    "tls": false, 
    "tls_hostname": "localhost", 
    "tls_verify": false
  }
]
auth params:

  tls: False

  cacert_path: None

  timeout: 60

  default_ip: 127.0.0.1

  ssl_version: None

  tls_hostname: localhost

  docker_host: unix://var/run/docker.sock

  tls_verify: False

  key_path: None

  default_ssh_port: 22

  cert_path: None

  api_version: 1.24
```
