### ISSUE TITLE
route53_health_check resource_path uniqueness ignored

### ISSUE THREAD

**Issue by jameelur** [ansible/ansible#23110]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
route53_health_check

##### ANSIBLE VERSION

```
ansible 2.2.2.0
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Mac OSX

##### SUMMARY

Tried to create multiple route53 healthchecks to the same server but different resource paths using `with_items` . Instead of creating one health check for each resource path, only the first is created. 

##### STEPS TO REPRODUCE

```yaml
- name: set up route53 health checks
  connection: local
  become: false
  route53_health_check:
    failure_threshold: 3
    ip_address: '{{ ip_address }}'
    port: 80
    request_interval: 30
    resource_path: '{{ item }}'
    state: present
    type: HTTP
  register: result
  with_items:
    - /some_status1
    - /other_status2
```

##### EXPECTED RESULTS

* 2 health checks created
* `result` contains `health_check.id`s for each health check

##### ACTUAL RESULTS

* 1 health check created
* `result` contains two items, both having the same `health_check.id`
