### ISSUE TITLE
New warning  [WARNING]: Found variable using reserved name: hosts

### ISSUE THREAD

**Issue by Chris-YBS** [ansible/ansible#23121]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
playbook

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel ab8578d343) last updated 2017/03/28 11:23:01 (GMT +000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/roles/cmprescott.xml/library']
  python version = 2.7.13 (default, Jan 13 2017, 10:15:16) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### OS / ENVIRONMENT
Fedora 7

##### STEPS TO REPRODUCE

```yaml
- name: ETLDeploy
  vars_prompt:
    - name: "hosts"
      prompt: |- 
                You can just press return for the default or enter a comma seperated
                list of machines with name in uppercase and domain in lower case
                (e.g. XXX.ybs.com or windowspervasive)
                
                Which hosts would you like to setup?
      private: no
      default: "XXX.ybs.com"
  hosts: "{{hosts}}"


```

##### EXPECTED RESULTS
run without warnings

##### ACTUAL RESULTS

```
 [WARNING]: Could not match supplied host pattern, ignoring: {{hosts}}

 [WARNING]: Found variable using reserved name: hosts

```
The first warning already reported in another defect (#23057)
