### ISSUE TITLE
sros_config is treating commas in commands as delimiters, breaking single lines into multi

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#23142]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
sros_config

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
N/A

##### SUMMARY
SROS supports regex as-path policy specifications that include commas, e.g. ".{60,}". sros_config incorrectly interprets the comma as a delimiter and breaks the setting into two parts, both of which fail to be applied.

##### STEPS TO REPRODUCE
Attempt to configure a router policy option that includes a comma in the regex. In our case, we were attempting to create the following, which works using the SROS command line:

```
# configure
config# router
config>router# policy-options
config>router>policy-options# as-path "greater-60" ".{60,}"
config>router>policy-options# info
----------------------------------------------
            as-path "greater-60" ".{60,}"
```   

We attempted to accomplish this operation using Ansible via the following playbook:

```yaml
---
- name: create policy-options
  hosts: spines
  connection: local
  gather_facts: False
  serial: 1

  vars:
    cli:
      host: "{{ inventory_hostname }}"
      username: xxxxx
      password: XXXXXX
      transport: cli

  tasks:
    - name: set as-path
      sros_config:
        lines: configure router policy-options as-path "greater-60" ".{60,}"
        provider: "{{ cli }}"
```

Note that we also attempted this same operation in the playbook using alternate notation, such as:

```yaml
- name: set as-path
  sros_config:
    lines:
        - 'as-path "greater-60" ".{60,}"'
    parents:
        - configure
        - router
        - policy-options
    provider: "{{ cli }}"
    backup: yes
    save: yes
```

and

```yaml
- name: set as-path
  sros_config:
      src: "as-path.cfg"
      provider: "{{ cli }}"
      save: yes
```

We also tried specifying the as-path command as a variable. We saw no difference in the results between the various permutations. We also tried various methods of escaping the comma and different combinations of single- and double-quotes.

##### EXPECTED RESULTS
We expected to see ansible output as shown, below, _emphasis_ added:

```json 
changed: [host.example.com] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": false,
            "backup": false,
            "config": null,
            "defaults": false,
            "host": "myjenkinsvsc1.example.com",
            "lines": [
                _"configure router policy-options as-path \"greater-60\" \".{60,}\""_
            ],
            "match": "line",
            "parents": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": {
                "host": "host.example.com",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "transport": "cli",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "updates": [
        _"configure router policy-options as-path \"greater-60\" \".{60,}\""_
    ],
    "warnings": [
    ]
}
```

##### ACTUAL RESULTS
When we ran, both `lines` and `updates` in the ansible output showed 2 lines instead of the one we expected. Ansible broke the as-path command line into `'configure router policy-options as-path "greater-60" ".{60'` and `'}"'`. Here's the output, _emphasis_ added:

```
changed: [host.example.com] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": false,
            "backup": false,
            "config": null,
            "defaults": false,
            "host": "host.example.com",
            "lines": [
                _"configure router policy-options as-path \"greater-60\" \".{60",_
                _"}\""_
            ],
            "match": "line",
            "parents": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": {
                "host": "myjenkinsvsc1.example.com",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "transport": "cli",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "updates": [
        _"configure router policy-options as-path \"greater-60\" \".{60",_
        _"}\""_
    ],
    "warnings": [
    ]
}
```

**Comment by ansibot** [comment]
cc @privateip @gundalow @Qalthos
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
I was able to replicate the first use case but not the second one.  It should work fine with list notation.  See testing playbook output below.

If you are still experiencing the bug, could you run the playbook with `-vvv` and provide the output to help troubleshoot further?

needs_info

**ansible version**
```
ansible 2.2.2.0 (stable-2.2 42afc7dc45) last updated 2017/03/30 15:00:44 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 31a1f19cd8) last updated 2017/03/30 15:00:50 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 921bc0d464) last updated 2017/03/30 15:00:50 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
**test playbook**
```
---
- hosts: sros01

  tasks:
    - sros_config:
        lines:
          - 'as-path "greater-60" ".{60,}"'
        parents:
          - configure
          - router
          - policy-options
        provider: "{{ cli }}"

    - sros_config:
        lines:
          - 'configure router policy-options as-path "greater-60" ".{60,}"'
        match: none
        provider: "{{ cli }}"
```
**test playbook output**
```
$ play test.yaml -vvv --check
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test.yaml ************************************************************
1 plays in test.yaml

PLAY [sros01] ******************************************************************

TASK [sros_config] *************************************************************
task path: /home/sprygada/Workspaces/playbooks/ansible-sros/test.yaml:5
Using module file /home/sprygada/Workspaces/ansible-2.2/lib/ansible/modules/core/network/sros/sros_config.py
<sros01> ESTABLISH LOCAL CONNECTION FOR USER: sprygada
<sros01> EXEC /bin/sh -c 'python && sleep 0'
changed: [sros01] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": false,
            "backup": false,
            "config": null,
            "defaults": false,
            "host": "sros01",
            "lines": [
                "as-path \"greater-60\" \".{60,}\""
            ],
            "match": "line",
            "parents": [
                "configure",
                "router",
                "policy-options"
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": {
                "host": "sros01",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "transport": "cli",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "updates": [
        "configure router policy-options as-path \"greater-60\" \".{60,}\""
    ],
    "warnings": [
        "Cannot create checkpoint.  Please enable this feature using the sros_rollback module.  Automatic rollback will be disabled"
    ]
}
 [WARNING]: Cannot create checkpoint.  Please enable this feature using the sros_rollback module.
Automatic rollback will be disabled


TASK [sros_config] *************************************************************
task path: /home/sprygada/Workspaces/playbooks/ansible-sros/test.yaml:14
Using module file /home/sprygada/Workspaces/ansible-2.2/lib/ansible/modules/core/network/sros/sros_config.py
<sros01> ESTABLISH LOCAL CONNECTION FOR USER: sprygada
<sros01> EXEC /bin/sh -c 'python && sleep 0'
changed: [sros01] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": false,
            "backup": false,
            "config": null,
            "defaults": false,
            "host": "sros01",
            "lines": [
                "configure router policy-options as-path \"greater-60\" \".{60,}\""
            ],
            "match": "none",
            "parents": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": {
                "host": "sros01",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "transport": "cli",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "updates": [
        "configure router policy-options as-path \"greater-60\" \".{60,}\""
    ],
    "warnings": [
        "Cannot create checkpoint.  Please enable this feature using the sros_rollback module.  Automatic rollback will be disabled"
    ]
}

PLAY RECAP *********************************************************************
sros01                     : ok=2    changed=2    unreachable=0    failed=0
```

**Comment by ghost** [comment]
I was able to confirm your results, @privateip. We will use that as a work-around. Note that there is another case that fails. Using this playbook:

```
---
- name: create policy-options
  hosts: spines
  connection: local
  gather_facts: False
  serial: 1 
            
  vars:     
    cli:
      host: "{{ inventory_hostname }}"
      username: admin
      password: admin
      transport: cli

  tasks:
    - name: set as-path
      sros_config:
        src: test.cfg
        provider: "{{ cli }}"
```

And this cfg file:

```
exit all
configure
    router
        policy-options
            begin
            as-path "greater-15" ".{15,}"
            as-path "greater-25" ".{25,}"
            as-path "greater-35" ".{35,}"
            commit
        exit
    exit
exit all
```

We see this output, which we see in the `updates` section has been stripped of the curly braces in the regex:

```
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [create policy-options] ***************************************************

TASK [set as-path] *************************************************************
task path: /home/caso/brcastel/oscar/test.yml:17
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/network/sros/sros_config.py
<host.example.com> ESTABLISH LOCAL CONNECTION FOR USER: caso
<host.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<host.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/caso/.ansible/tmp/ansible-tmp-1490988930.22-110336495134961 `" && echo ansible-tmp-1490988930.22-110336495134961="` echo /home/caso/.ansible/tmp/ansible-tmp-1490988930.22-110336495134961 `" ) && sleep 0'
<host.example.com> PUT /tmp/tmpiXziSB TO /home/caso/.ansible/tmp/ansible-tmp-1490988930.22-110336495134961/sros_config.py
<host.example.com> EXEC /bin/sh -c 'chmod u+x /home/caso/.ansible/tmp/ansible-tmp-1490988930.22-110336495134961/ /home/caso/.ansible/tmp/ansible-tmp-1490988930.22-110336495134961/sros_config.py && sleep 0'
<host.example.com> EXEC /bin/sh -c '/usr/bin/python /home/caso/.ansible/tmp/ansible-tmp-1490988930.22-110336495134961/sros_config.py; rm -rf "/home/caso/.ansible/tmp/ansible-tmp-1490988930.22-110336495134961/" > /dev/null 2>&1 && sleep 0'
changed: [host.example.com] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": false,
            "backup": false,
            "config": null,
            "defaults": false,
            "host": "myjenkinsvsc1.example.com",
            "lines": null,
            "match": "line",
            "parents": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": {
                "host": "myjenkinsvsc1.example.com",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "transport": "cli",
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "save": false,
            "src": "exit all\nconfigure\n    router\n        policy-options\n            begin\n            as-path \"greater-15\" \".{15,}\"\n            as-path \"greater-25\" \".{25,}\"\n            as-path \"greater-35\" \".{35,}\"\n            commit\n        exit\n    exit\nexit all\n",
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        }
    },
    "updates": [
        "configure router policy-options as-path \"greater-15\" \".15,\"",
        "configure router policy-options as-path \"greater-25\" \".25,\"",
        "configure router policy-options as-path \"greater-35\" \".35,\""
    ],
    "warnings": [
        "Cannot create checkpoint.  Please enable this feature using the sros_rollback module.  Automatic rollback will be disabled"
    ]
}

PLAY RECAP *********************************************************************
host.example.com  : ok=1    changed=1    unreachable=0    failed=0
```

The requested policy-options do not appear on the router.
