### ISSUE TITLE
service arguments ignored if using systemd

### ISSUE THREAD

**Issue by chrislong** [ansible/ansible#23144]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

service module

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

No changes

##### OS / ENVIRONMENT

Ubuntu 14.04 LTS

##### SUMMARY
The documentation for the service module says the "arguments" parameter can be used. However, this is not true if the system uses systemd (e.g., CentOS 7).

##### STEPS TO REPRODUCE

Run ansible-playbook with the following task, where the inventory is a host running `systemd`:

```yaml
- name: start docker and enable it on boot
  service:
    enabled: yes
    name: docker
    state: started
    arguments: --insecure-registry myregistry:5000
  become: true
```

##### EXPECTED RESULTS

That the service would be started with the specified parameters, as the documentation for the service module states.

##### ACTUAL RESULTS

When I run `ansible-playbook` that includes the above task, it says:

```
 [WARNING]: Ignoring "arguments" as it is not used in "systemd"
```

and the arguments are ignored.

I suspect this is not going to be fixed by adding support for arguments to the systemd module, so I am filing this as a documentation bug for the service module.
