### ISSUE TITLE
Semicolons are stipped from templates

### ISSUE THREAD

**Issue by jmighion** [ansible/ansible#23154]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.1.0
  config file = /home/jmighion/git/blank-ansible-repo/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

inventory      = inventory
forks          = 1400
roles_path    = roles
timeout = 20
log_path = ~/ansible.log
retry_files_enabled = False

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Semicolon in jinja2 template gets removed before being sent to the device. When using the same command as a `line:` the semicolon is present on the device. So running a command to config snmp like : `snmp-server location some;location` from `src:` will end up with `somelocation` vs being sent from `lines:` will end up with `some;location`. I've tried escaping the semicolons with \ and \\ but that just results in `some\location` or `some\\location`.

##### STEPS TO REPRODUCE

Switching between the `lines:` and the `src:` will show how `lines:` will leave `some;location` and `src:` will leave `someotherlocation` without the semicolons.

```yaml
- name: dev
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: dev
      ios_config:
        provider: "{{ cli }}"
        #lines: snmp-server location some;location
        src: test.j2
        save: yes
```

test.j2 : 
```
snmp-server location some;other;location
```

provider cli : 
```
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ cli_username }}"
  password: "{{ cli_password }}"
```

##### EXPECTED RESULTS

`some;other;location`

##### ACTUAL RESULTS

`someotherlocation`
