### ISSUE TITLE
parted : ERROR! no action detected in task.

### ISSUE THREAD

**Issue by ZuluPro** [ansible/ansible#23163]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

parted

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Linux 3.19.0-25 / Ubuntu 14.04.3 LTS

##### SUMMARY
If I add this block to my playbook, I have the following error:
```
# ansible-playbook -i hosts site.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/home/zulu/cs_ansible/roles/master/tasks/main.yml': line 17, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Create HDFS partition
  ^ here


The error appears to have been in '/tmp/site.yml': line 17, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Create HDFS partition
  ^ here
```

If I replace `parted` by `debug`, it works.

##### STEPS TO REPRODUCE

```yaml
---
- name: deploy
  hosts: all
  remote_user: root
  tasks:
  - name: Create partition
    parted:
      device: "{{ hdfs_device }}"
      state: present
      number: 1
      part_type: primary
```
