### ISSUE TITLE
ec2_asg_facts - additonal parameters in module.

### ISSUE THREAD

**Issue by mprzygrodzki** [ansible/ansible#23174]
Hello, it would be great if there's a possibility to add some limit & sort parameter similar to ones which were included in ec2_lc_find or ec2_ami_find called "limit" or "sort_order (ascending/descending, sorted by creation date or something like that )" so we can list current ASG's from oldest to newest - i would like to integrate this with my playbook i.e. to list and keep latest 2 ASG's

##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

```
ec2_asg_facts
```
##### ANSIBLE VERSION

```
ansible 2.2.2.0
```
##### EXPECTED RESULTS
```
local_action:
   module: ec2_asg_facts
   region: 
   name: "my-asg-release-*"
   sort_order: ascending
   limit: "-2"
register: ec2_asg

Adding "sort_order" based on creation date & "limit" paramters
```
