### ISSUE TITLE
get_url retry, resume/continue

### ISSUE THREAD

**Issue by TheTesla** [ansible/ansible#23182]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

nothing changed

##### OS / ENVIRONMENT

N/A

##### SUMMARY

retry and resume/continue get_url downloads:
If connection was broken during download, retry download [retry]-counts. Do not download at start, resume/continue on the stopped end like 'wget -c'. Also resume or continue if playbook is restarted manually after end of retry count or any playbook interrupt. If anything after the download fails like not enough memory or permission problems, keep the temporary file. Resume transfering the temporary file to the destination on the next user attempt. Only delete it, if task was completed successfully.

##### STEPS TO REPRODUCE

```yaml
- name: download some files
  get_url:
     url: http://example.example/file.txt
     dest: /my/downloads
     retry_limit: 3
     continue: yes
```

##### EXPECTED RESULTS

file is downloaded correctly, even the server times out

##### ACTUAL RESULTS

server times out, file downloaded from beginning, server times out again...
