### ISSUE TITLE
Synchronize module: incorrect documentation for "dest"

### ISSUE THREAD

**Issue by vinigfer** [ansible/ansible#23192]
##### ISSUE TYPE
 - Documentation Report (bug on documentation)

##### COMPONENT NAME
- Synchronize

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
- None changed

##### OS / ENVIRONMENT
Host is:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Destination is a VM running Ubuntu 16.04

##### STEPS TO REPRODUCE
When attempting to "push" a git repository to a host using the syncronize module, documentation says the "dest" parameter is a path. Either absolute, or relative. However when running the task inside a role, and looking at the play result with --vvv argument, it was pretty clear that I needed to supply the whole SSH path, such as `user@hostname:/home/userhome/`

The first piece of code will not work
```yaml
- name: 'Pushing code from localhost to remove server'
  synchronize:
    src: "{{ local_folder }}"
    dest: "{{ destination_folder }}"
    rsync_opts:
      - "--protect-args -aP"
```
However this sample of code will. Please update the documentation in order to match the correct use of the module.
```yaml
- name: 'Pushing code from localhost to remove server'
  synchronize:
    src: "{{ local_folder }}"
    dest: "{{ ansible_user }}@{{ inventory_hostname }}:{{ destination_folder }}"
    rsync_opts:
      - "--protect-args -aP"
```

##### EXPECTED RESULTS
No errors or using verbose:

```
TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: telessaude
<127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=3022 -o 'IdentityFile="/home/vinicius/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=telessaude -o ConnectTimeout=10 -o ControlPath=/home/vinicius/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1490990911.04-126668737154226 `" && echo ansible-tmp-1490990911.04-126668737154226="` echo ~/.ansible/tmp/ansible-tmp-1490990911.04-126668737154226 `" ) && sleep 0'"'"''
<127.0.0.1> PUT /tmp/tmp0YEjro TO /home/telessaude/.ansible/tmp/ansible-tmp-1490990911.04-126668737154226/setup.py
<127.0.0.1> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o Port=3022 -o 'IdentityFile="/home/vinicius/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=telessaude -o ConnectTimeout=10 -o ControlPath=/home/vinicius/.ansible/cp/ansible-ssh-%h-%p-%r '[127.0.0.1]'
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: telessaude
<127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=3022 -o 'IdentityFile="/home/vinicius/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=telessaude -o ConnectTimeout=10 -o ControlPath=/home/vinicius/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /home/telessaude/.ansible/tmp/ansible-tmp-1490990911.04-126668737154226/ /home/telessaude/.ansible/tmp/ansible-tmp-1490990911.04-126668737154226/setup.py && sleep 0'"'"''
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: telessaude
<127.0.0.1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o Port=3022 -o 'IdentityFile="/home/vinicius/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=telessaude -o ConnectTimeout=10 -o ControlPath=/home/vinicius/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 '/bin/sh -c '"'"'DJANGO_SETTINGS_MODULE=telessaude.settings.dev /usr/bin/python /home/telessaude/.ansible/tmp/ansible-tmp-1490990911.04-126668737154226/setup.py; rm -rf "/home/telessaude/.ansible/tmp/ansible-tmp-1490990911.04-126668737154226/" > /dev/null 2>&1 && sleep 0'"'"''
ok: [127.0.0.1]
```

##### ACTUAL RESULTS

```
TASK [role_deploy : Pushing code from localhost to remove server] **************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh 'ssh -i /home/vinicius/.ssh/id_rsa -S none -o StrictHostKeyChecking=no -o Port=3022' --protect-args -aP --out-format='<<CHANGED>>%i %n%L' \"/home/vinicius/telessaude_branch_homologacao/\" \"/home/telessaude/telessaude_branch_homologacao\"", "failed": true, "msg": "rsync: mkdir \"/home/telessaude/telessaude_branch_homologacao\" failed: No such file or directory (2)\nrsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]\n", "rc": 11}
```

**Comment by erwilan** [comment]
- your task runs for host 127.0.0.1 - which ist localhost
  so synchronize syncs from localhost to localhost
  therefore there is no 'user@host:' in the rsync command

- rsync does not create the parent directory of dest - you have to create it in advance

so this is not a bug.

also note:
the documentation says: specify additional rsync options by passing in an array.
pass the rsync_opts this way:
```
- name: 'Pushing code from localhost to remove server'
  synchronize:
    src: "{{ local_folder }}"
    dest: "{{ destination_folder }}"
    rsync_opts:
      - "--protect-args"
      - "-aP"
```
by the way: use the module option instead of rsync_opts if available - e.g. the archive option (is on by default)
