### ISSUE TITLE
blockinfile should show diff

### ISSUE THREAD

**Issue by MartinNowak** [ansible/ansible#23198]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It's very easy to accidentally overwrite changes in content managed via blockinfile because `--diff --check` does not show a diff of the update atm.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  tasks:
  - name: original block
    blockinfile:
      dest: test.txt
      create: yes
      block: |
        foo bar
  - name: updated block
    blockinfile:
      dest: test.txt
      create: yes
      block: |
        foo bar baz
```
`ansible-playbook --diff test.yml`

##### EXPECTED RESULTS
Should show the diff between `foo bar` and `foo bar baz`

##### ACTUAL RESULTS
With `-vvvv` it still only shows the new block content.
