### ISSUE TITLE
File task fails when file does not exist, contradicting documentation

### ISSUE THREAD

**Issue by ctorgalson** [ansible/ansible#23203]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

File

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

macOS

##### SUMMARY

The [File module's documentation](http://docs.ansible.com/ansible/file_module.html) states that "Note that file will not fail if the `path` does not exist as the state did not change."

However, running tasks that attempt to change the properties of files not (yet) present fails **because the file is absent**.

##### STEPS TO REPRODUCE

1. Create a task using the file module to ensure the state of a file as the following commands would:

    ```bash
    chown root:example .htaccess
    chmod 644 .htaccess
    ```
2. Run it against a machine where that file is not present. 

```yaml
    - name: Change ownership, permissions of .htaccess files.
      file:
        path: "/var/www/example.com/docroot/{{ item }}"
        owner: "root"
        group: "example"
        mode: "u=rw,go=r"
        state: file
      with_items:
        - ".htaccess"
        - "data/.htaccess"
      become: yes
```

##### EXPECTED RESULTS

Two things:

- [x] Existing files permissions changed.
- [ ] Nonexistent files bypassed by task.

##### ACTUAL RESULTS

The task fails with the message "file ... is absent, cannot continue."

```
failed: [example.com] (item=data/.htaccess) => {
    "failed": true,
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "diff_peek": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": "jenkins",
            "mode": "u=rwx,go=r",
            "original_basename": null,
            "owner": "root",
            "path": "/var/www/example.com/docroot/data/.htaccess",
            "recurse": false,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": null,
            "unsafe_writes": null,
            "validate": null
        },
        "module_name": "file"
    },
    "item": "data/.htaccess",
    "msg": "file (/var/www/example.com/docroot/data/.htaccess) is absent, cannot continue",
    "path": "/var/www/example.com/docroot/data/.htaccess",
    "state": "absent"
}
```
