### ISSUE TITLE
Pip module returns unchanged when creating a venv with already installed packages

### ISSUE THREAD

**Issue by kulinacs** [ansible/ansible#23204]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pip module

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

[defaults]
hostfile = inventory
legacy_playbook_variables = false
nocows = 1
retry_files_enabled = false

##### OS / ENVIRONMENT

Debian 9 primary, deployed to Void Linux, likely N/A

##### SUMMARY

When creating a virtualenv with only default packages i.e. pip, the pip module returns green despite the fact it created the venv.

##### STEPS TO REPRODUCE

```yaml
- name: Create Python Virtual Environment
  pip:
    name: pip
    virtualenv: /home/user/venv/
    virtualenv_python: python2
```

##### EXPECTED RESULTS

Even if no new python packages are installed to the venv, the pip module should return changed if the venv is created

##### ACTUAL RESULTS

The module returns unchanged

```
TASK [server : Create Python Virtual Environment] ***********************
ok: [ctfd-testing]
```
