### ISSUE TITLE
Unarchive in 2.4 yields unexpected result

### ISSUE THREAD

**Issue by hyperized** [ansible/ansible#23214]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
unarchive

##### ANSIBLE VERSION
```
ansible 2.4.0
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
When using `unarchive` in ansible 2.4, the following no longer works:

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  vars:
    lynis_name: lynis
    lynis_base_path: /usr/local
    lynis_directory: "{{ lynis_base_path }}/{{ lynis_name }}"
    lynis_executable_path: "{{ lynis_directory }}/{{ lynis_name }}"
    lynis_version: 2.4.8
    lynis_url: "https://cisofy.com/files/{{ lynis_name }}-{{ lynis_version }}.tar.gz"
  tasks:
    - name: ensure lynis is present
      unarchive:
        src: "{{ lynis_url }}"
        dest: "{{ lynis_base_path }}"
        remote_src: True
        creates: "{{ lynis_executable_path }}"
```

##### EXPECTED RESULTS
Result in 2.2:
```
$ ansible-playbook tests/main.yml --connection=local

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [fdmg.lynis : ensure lynis is executable] *********************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=0
```

##### ACTUAL RESULTS
Result in 2.4:
```
$ ansible-playbook tests/main.yml --connection=local

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [fdmg.lynis : ensure lynis is present] ************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Source 'https://cisofy.com/files/lynis-2.4.8.tar.gz' failed to transfer"}
	to retry, use: --limit @/builds/ansible/lynis/tests/main.retry

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=1
```
