### ISSUE TITLE
win_acl - Bug?

### ISSUE THREAD

**Issue by mikeeaton83** [ansible/ansible#23215]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_acl

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 11138abc51) last updated 2017/04/03 10:20:12 (GMT +000)
  config file =
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### OS / ENVIRONMENT

Running from CentOS 7 and targeting Windows Server 2016. Using kerberos auth, but same issue using local account.

##### SUMMARY
Settings FullControl permissions on a folder to a domain user causes an exception

##### STEPS TO REPRODUCE

task:
```yaml
- name: Set ACL on Inbox dir
  win_acl:
    user: iom.domain.com\DeploymentAgent
    path: W:\\folder\DeploymentAgent\\Inbox
    state: present
    type: allow
    rights: FullControl
  tags: set-acl

```
inventory
```yaml
[appservers]
appt-001-iom.IOM.DOMAIN.COM

[windows:children]
appservers

[windows:vars]
ansible_user =  ansible@IOM.DOMAIN.COM
ansible_password = **********

ansible_port = 5986
ansible_connection =  winrm
ansible_winrm_server_cert_validation =  ignore
ansible_winrm_transport = kerberos
ansible_winrm_service = HOST

```

ansible-playbook -i inventories/development-iom -l appservers windows.yml --tags set-acl -vvvvvv

##### EXPECTED RESULTS
I expected iom.domain.com\DeploymentAgent to have FullControl perms on W:\\folder\DeploymentAgent\\Inbox

##### ACTUAL RESULTS

```
https://gist.github.com/if-meaton/8d7dcde9def1fc7bab5522a087d3b971
```
