### ISSUE TITLE
[Feature Request] apt module: add state "downloaded"

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible/ansible#23220]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
apt module, potentially other package managing modules

##### ANSIBLE VERSION
n/a

##### OS / ENVIRONMENT
Debian and derivatives

##### SUMMARY
Add option to download packages locally without installing them.

##### STEPS TO REPRODUCE
Emulating the user experience of:

    apt-get -d / apt-get download / apt-get --download-only [package1 package2]

Example:

```yaml
tasks:
  - name: Download all latest packages, but don't install yet
    apt:
      update_cache: yes
      only_upgrade: yes
      state: downloaded
```

##### EXPECTED RESULTS

After setting this flag, the specified package(s) can be installed later without requiring a download from the repository server(s).

##### ACTUAL RESULTS

Currently, this functionality of apt-get is not exposed in the apt module.
