### ISSUE TITLE
win_chocolatey installing powershell when powershell4 is installed and state: latest

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#23249]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel cc50b803df) last updated 2017/03/22 14:15:18 (GMT -500)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
Ansible configuration from git clone

##### OS / ENVIRONMENT
Control host macOS 10.12.3
Managed host Windows 7

##### SUMMARY
Attempting to upgrade powershell4 to powershell5 using the win_chocolatey module with state: latest

Might be related to #21873
Related to #22892 

##### STEPS TO REPRODUCE
  * Have chocolatey installed
  * Install powershell4

```yaml
- name: install powershell 
  win_chocolatey:
    name: "{{ item }}"
    state: latest
  with_items:
    - "powershell"
  register: check_powershell5
```

##### EXPECTED RESULTS
Powershell4 would be upgraded to Powershell5

##### ACTUAL RESULTS
https://gist.github.com/basictheprogram/74b48320e386d308a69f82f7c90019b5

choco_summary.log
https://gist.github.com/basictheprogram/de146516fe292a43630c10e7df205f38

chocolatey.log
https://gist.github.com/basictheprogram/5cc240c1f89fba6ef7ac769ff5e41a01
