### ISSUE TITLE
Allow lineinfile to just ensure that a line is present, but not replacing matching existing ones

### ISSUE THREAD

**Issue by guenhter** [ansible/ansible#23255]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
```
ansible 2.3.0.0 (detached HEAD f001646f2c) last updated 2017/04/04 09:04:29 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION
Nothing special

##### OS / ENVIRONMENT
Debian 8.7
Linux head 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

##### SUMMARY
The `lineinfile` always replaces lines when the line matches. This is not always intended.
E.g. if a line in a file should be rolled out with a default value but that line shouldn't be touched further so it can be manually edited. So a new option would be helpful which controls what to do when `lineinfile` finds a matching line.

##### STEPS TO REPRODUCE

```yaml
  - lineinfile:
      path: /srv/versions
      regexp: '^version='
      line: 'version=latest'
      replace: false   <-- this would be a new option
```

##### EXPECTED RESULTS

1. The first time, the line `version=latest` is added to the file (because line missing)
2. Then the line is altered manually to `version=1.0.1`
3. The line should stay `version=1.0.1`

##### ACTUAL RESULTS

1. The first time, the line `version=latest` is added to the file (because line missing)
2. Then the line is altered manually to `version=1.0.1`
3. The line is again `version=latest`

**Comment by ryansb** [comment]
I think this is intended behavior. We try to keep each individual module on the simpler side, and make sure there's facilities to compose simpler modules to get what you need done. If you need to not automatically replace something you can use the `find` module to check the contents and store the list, like:

```
- find:
    name: /srv/versions
    contains: "^version="
  register: found
- lineinfile:
    path: /srv/versions
    regexp: '^version='
    line: 'version=latest'
  when: not found.matched
```

That'll look in the versions file, and if there is a line you want to be there, the lineinfile will get skipped.
