### ISSUE TITLE
ios_command & ios_config: copy running-config startup-config timeout due to lack of "file prompt quiet"

### ISSUE THREAD

**Issue by joelwking** [ansible/ansible#23263]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_command and ios_config

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /home/administrator/ansible/playbooks/ansible.cfg
  configured module search path = ['/usr/share/ansible/', '/home/administrator/ansible/playbooks']

```

##### CONFIGURATION
inventory      = $HOME/ansible/playbooks/hosts
library        = /usr/share/ansible/:/home/administrator/ansible/playbooks
retry_files_enabled = False

##### OS / ENVIRONMENT
Ubuntu 14.4 as control node
```
isr-2911-a# show ver | inc image
System image file is "flash0:c2900-universalk9-mz.SPA.153-3.M5.bin"
isr-2911-b>show ver | inc image
System image file is "flash0:c2900-universalk9-mz.SPA.153-3.M5.bin"
ISR-2911-D#show ver | inc image
System image file is "flash0:/c2900-universalk9-mz.SPA.154-2.T.bin"
```

##### SUMMARY
Encountering timeout trying to send command: `copy running-config startup-config`. Other commands are send  as expected.

##### STEPS TO REPRODUCE

Please see this [Gist](https://gist.github.com/joelwking/b06ec9a6cd048c5d0e24644f6f62c392) . It demonstrates the playbook working as expected, then when the 
`save: yes` option is added, it fails on some, but not all hosts. I also tried using the ios_command module, and also encountered timeouts.
```
- name: save running config
    ios_command:
      provider: "{{ provider }}"
      auth_pass: "{{ ios.enable_password }}"
      authorize: yes
      commands:
       - "copy running-config startup-config"
```
##### EXPECTED RESULTS

See [Gist](https://gist.github.com/joelwking/b06ec9a6cd048c5d0e24644f6f62c392)
##### ACTUAL RESULTS

See [Gist](https://gist.github.com/joelwking/b06ec9a6cd048c5d0e24644f6f62c392)
