### ISSUE TITLE
SVN module in check mode should check modified files

### ISSUE THREAD

**Issue by vjcalvo** [ansible/ansible#23285]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
subversion module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
N/A

##### SUMMARY
For our deployment purposes using Ansible and SVN we would need to test (check mode, dry-run) before run the deployment playbook. If there is some missing file in the destination it will pass the check-mode but not the definitive one.

I looked at the code and I think it will do the job to add in current line 287:

if module.check_mode or not update:
if (svn.has_local_mods() && !force)
module.fail_json(msg="ERROR: modified files exist in the repository.")
check, before, after = svn.needs_update()
module.exit_json(changed=check, before=before, after=after)

I am far from an expert on this, so I prefer to post it here so maybe someone can help and implement it! :)

##### STEPS TO REPRODUCE

```yaml
- subversion:
    repo: svn+ssh://an.example.org/path/to/repo
    dest: /src/checkout
ansible-playbook example.yml --check
```

##### EXPECTED RESULTS
If there are modified files should give an ERROR.

##### ACTUAL RESULTS
Everything is OK.

**Comment by ansibot** [comment]
cc @dsummersl
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by vjcalvo** [comment]
anyone? :(

**Comment by dsummersl** [comment]
@vjcalvo I'm sorry I haven't had a chance to look at this recently - I'll take a look tonight.

**Comment by vjcalvo** [comment]
thanks, no hurries! (it's my first reported issue, don't know how it goes) Anything I can do for help, just let me know. regards!

**Comment by vjcalvo** [comment]
@dsummersl thanks!!

**Comment by towolf** [comment]
EDIT: disregard this, `force: yes` with `check_mode: yes` makes it work again.

@dsummersl this broke our "is your SVN up-to-date" check task that we have in every playbook to remind people to do `svn update` before they roll out stuff.

```yaml
- name: Check if Ansible SVN is up-to-date
  local_action:
    module: subversion
    repo: svn+ssh://svn@sub.our-repo.local/ansible
    dest: "{{ inventory_dir }}/.."
    checkout: no
  check_mode: yes
  changed_when: false
  run_once: true
  register: svncheck
  failed_when: svncheck.before != svncheck.after
  ignore_errors: yes
```

Our policy is to first roll out and *then* to commit the changes to svn. So having modified files in the local repo is to be expected. But the changes from the subversion server need to the pulled first.

So, this fix broke our check. At least make it optional.
