### ISSUE TITLE
ssh to in-memory host not reachable

### ISSUE THREAD

**Issue by sugun999** [ansible/ansible#23287]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

openstack os_server, add_host

##### ANSIBLE VERSION

ansible 2.2.1.0

##### OS / ENVIRONMENT

Centos 7.3, Openstack

##### SUMMARY

Created server with openstack os_server module and added that server to in memory inventory with add_host module.

Running below ansible-playbook throws error

fatal: [20.20.0.37]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '20.20.0.37' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}

Please note that there is ssh key private key file at /root/.ssh/id_rsa

##### STEPS TO REPRODUCE

Run below code "ansible-playbook demo-site.yml"

**demo-site.yml**

```
---

- hosts:
    localhost
  gather_facts: False
  roles:
    - launch_vms

- name: display host
  hosts: 
    microservices
  become: yes
  become_user: root
  roles:
    - user_tomcat

```

**roles/launch_vms/tasks/main.yml**

```
name: launch servers
os_server:
  name: server1
  state: present
  key_name: key1
  image: centos
  flavor: m1.medium
  auto_ip: False
  network: demonet
  security_groups: default
  wait: true
register: "os_servers"

name: add hosts to inventory
add_host:
  groups: microservices
  name: "{{ item.openstack.public_v4 }}"
  ansible_user: 'centos'
  ansible_ssh_private_key_file: "/root/.ssh/id_rsa"
  ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null"
  ansible_ssh_host: "{{ item.openstack.public_v4 }}"
  instance_name: "{{item.server.name}}"
with_items: "{{ os_servers.results }}"

name: Wait for instances to listen on port 22
wait_for:
  state=started
  host={{ item.openstack.public_v4 }}
  port=22
with_items: "{{ os_servers.results }}"
```

**roles/user_tomcat/tasks/main.yml**

```
---
name: create tomcat group
become: yes
group:
  name: tomcat
  gid: 9600
  state: present

name: create tomcat user
become: yes
user:
  name: tomcat
  comment: "tomcat user"
  group: tomcat
  uid: 9599
  home: "{{ tomcat_user_home }}"
```

##### EXPECTED RESULTS
user_tomcat role should be executed successfully.

##### ACTUAL RESULTS
Server gets created successfully. But it fails open ssh connection to run user_tomcat role.

Here is the corresponding play output:

PLAY [display host] ************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<20.20.0.37> ESTABLISH SSH CONNECTION FOR USER: centos
<20.20.0.37> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 20.20.0.37 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1491458655.05-75222456360058 `" && echo ansible-tmp-1491458655.05-75222456360058="` echo ~/.ansible/tmp/ansible-tmp-1491458655.05-75222456360058 `" ) && sleep 0'"'"''
fatal: [20.20.0.37]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '20.20.0.37' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}

**Comment by ansibot** [comment]
@sugun999 Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sugun999** [comment]
Bug report

ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

OS: Centos

**Comment by gundalow** [comment]
@sugun999 The problem is you've deleted the template so the bot can't find the details

Can you please copy the template back from https://github.com/ansible/ansible/issues/new and update the description, thanks

**Comment by sugun999** [comment]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

openstack os_server, add_host

##### ANSIBLE VERSION

ansible 2.2.1.0

##### CONFIGURATION

##### OS / ENVIRONMENT

Centos 7.3, Openstack

##### SUMMARY

Created server with openstack os_server module and added that server to in memory inventory with add_host module.

Running below ansible-playbook throws error

fatal: [20.20.0.37]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '20.20.0.37' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}

Please note that there is ssh key private key file at /root/.ssh/id_rsa

##### STEPS TO REPRODUCE

Run below code "ansible-playbook demo-site.yml"


**demo-site.yml**

```
---

- hosts:
    localhost
  gather_facts: False
  roles:
    - launch_vms

- name: display host
  hosts: 
    microservices
  become: yes
  become_user: root
  roles:
    - user_tomcat

```

**roles/launch_vms/tasks/main.yml**

```
name: launch servers
os_server:
  name: server1
  state: present
  key_name: key1
  image: centos
  flavor: m1.medium
  auto_ip: False
  network: demonet
  security_groups: default
  wait: true
register: "os_servers"

name: add hosts to inventory
add_host:
  groups: microservices
  name: "{{ item.openstack.public_v4 }}"
  ansible_user: 'centos'
  ansible_ssh_private_key_file: "/root/.ssh/id_rsa"
  ansible_ssh_common_args: "-o UserKnownHostsFile=/dev/null"
  ansible_ssh_host: "{{ item.openstack.public_v4 }}"
  instance_name: "{{item.server.name}}"
with_items: "{{ os_servers.results }}"

name: Wait for instances to listen on port 22
wait_for:
  state=started
  host={{ item.openstack.public_v4 }}
  port=22
with_items: "{{ os_servers.results }}"
```

**roles/user_tomcat/tasks/main.yml**

```
---
name: create tomcat group
become: yes
group:
  name: tomcat
  gid: 9600
  state: present

name: create tomcat user
become: yes
user:
  name: tomcat
  comment: "tomcat user"
  group: tomcat
  uid: 9599
  home: "{{ tomcat_user_home }}"
```

##### EXPECTED RESULTS
user_tomcat role should be executed successfully.

##### ACTUAL RESULTS
Server gets created successfully. But it fails open ssh connection to run user_tomcat role.

Here is the corresponding play output:

PLAY [display host] ************************************************************

TASK [setup] *******************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/system/setup.py
<20.20.0.37> ESTABLISH SSH CONNECTION FOR USER: centos
<20.20.0.37> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/root/.ssh/id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=centos -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r 20.20.0.37 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1491458655.05-75222456360058 `" && echo ansible-tmp-1491458655.05-75222456360058="` echo ~/.ansible/tmp/ansible-tmp-1491458655.05-75222456360058 `" ) && sleep 0'"'"''
fatal: [20.20.0.37]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Warning: Permanently added '20.20.0.37' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}
