### ISSUE TITLE
vyos_config does not support bracketed config

### ISSUE THREAD

**Issue by mellowplace** [ansible/ansible#23286]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vyos_config

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

vyos_config module does not support bracket format despite it's documentation saying it does.

##### STEPS TO REPRODUCE

```yaml
- name: save the config
  become: false
  local_action:
    module: vyos_config
    args:
      src: boot.config.j2
      backup: yes
      save: yes
      provider:
        host: "{{ inventory_hostname }}"
        ssh_keyfile: "{{ role_path }}/files/vyos.pem"
        username: vyos
```

##### EXPECTED RESULTS

The bracketed template file is loaded into vyos

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: line must start with either `set` or `delete`
fatal: [52.214.201.120 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_XBWrsH/ansible_module_vyos_config.py\", line 292, in <module>\n    main()\n  File \"/tmp/ansible_XBWrsH/ansible_module_vyos_config.py\", line 283, in main\n    run(module, result)\n  File \"/tmp/ansible_XBWrsH/ansible_module_vyos_config.py\", line 243, in run\n    updates = diff_config(candidate, config)\n  File \"/tmp/ansible_XBWrsH/ansible_module_vyos_config.py\", line 191, in diff_config\n    raise ValueError('line must start with either `set` or `delete`')\nValueError: line must start with either `set` or `delete`\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```
