### ISSUE TITLE
synchronize module uses ansible_shell_executable of controlled node on controller

### ISSUE THREAD

**Issue by ericzolf** [ansible/ansible#23291]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
synchronize module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
The control node should be n/a (happens both on Fedora and RHEL/CentOS 7)
The managed host must just be "different" (e.g. Android, but see below).

##### SUMMARY
If `ansible_shell_executable` is set for a managed host, the synchronize-module will try to use the same executable on the control host, which will obviously fail.

##### STEPS TO REPRODUCE

Use an inventory similar to:

```ini
[strange]
strange42 ansible_host=192.168.121.231

#[controller]
#localhost

[kassenterminale:vars]
ansible_shell_executable=/system/xbin/bash
ansible_python_interpreter=/system/xbin/python

#[controller:vars]
#ansible_shell_executable=/usr/bin/bash
#ansible_python_interpreter=/usr/bin/python
```
and a playbook like:

```yaml
- name: repeater for CASE xxx
  hosts: all
  vars:
    tmp_dir: /var/tmp
  tasks:
    - name: ping
      ping:
    - name: setup
      setup:

    - name: run uname on remote host using command
      command: uname -a
    - name: run uname on remote host using raw
      raw: uname -a
    - name: run uname on remote host using shell
      shell: uname -a
      args:
        executable: "{{ ansible_shell_executable }}"

    - name: run uname locally on control host using command
      local_action: command uname -a
    - name: run uname locally on control host using raw
      local_action: raw uname -a
    - name: run uname locally on control host using shell
      local_action: shell uname -a

    - name: run uname delegated to control host using command
      command: uname -a
      delegate_to: localhost
    - name: run uname delegated to control host using raw
      raw: uname -a
      delegate_to: localhost
    - name: run uname delegated to control host using shell
      shell: uname -a
      delegate_to: localhost

    - name: synchronize a file
      synchronize:
        src: /etc/motd
        dest: "{{ tmp_dir }}/motd"
```

All the tasks will succeed, with the exception of the synchronize one, which tries to use `/system/xbin/bash` on the controller host. Uncommenting the commented lines in the inventory file didn't help.

##### EXPECTED RESULTS
The synchronize task works using the default or explicitly set shell for the control node (aka localhost).

##### ACTUAL RESULTS

Calling `ansible-playbook -i inventory test_common.yml -l strange42 -k -vvv -u vagrant` makes the last synchronize task fail:

```
TASK [synchronize a file] ******************************************************
task path: .../reproducer/test_common.yml:37
Using module file /usr/lib/python2.7/site-packages/ansible/modules/core/files/synchronize.py
<192.168.121.231> ESTABLISH LOCAL CONNECTION FOR USER: elavarde
<192.168.121.231> EXEC /system/xbin/bash -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1491397112.59-24599770471255 `" && echo ansible-tmp-1491397112.59-24599770471255="` echo ~/.ansible/tmp/ansible-tmp-1491397112.59-24599770471255 `" ) && sleep 0'
fatal: [strange42]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo ~/.ansible/tmp/ansible-tmp-1491397112.59-24599770471255 `\" && echo ansible-tmp-1491397112.59-24599770471255=\"` echo ~/.ansible/tmp/ansible-tmp-1491397112.59-24599770471255 `\" ), exited with result 127", 
    "unreachable": true
}
```

Adding a symlink on the controller node from `/system/xbin/bash` to `/usr/bin/bash` makes it work.
