### ISSUE TITLE
Role Dependency Max Depth and Variables

### ISSUE THREAD

**Issue by patran** [ansible/ansible#23327]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Nested Role dependencies - meta/main.yml

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /mymy/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Linux rgserver 4.4.0-71-generic #92-Ubuntu SMP Fri Mar 24 12:59:01 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

Role A depends (using meta/main.yml) on Role B depends on Role C depends on Role D depends on Role E.

Role is not able to pick up a variable passed in from Role A. It's considered "undefined"
Reducing the nested depth by having Role A include_role (using tasks/main.yml) solves the problem

##### STEPS TO REPRODUCE

```yaml
Role A
dependencies:
 - { role: B,            
              vnameB1: "{{vnA1}}",
              vnameB2: "{{vnA2}}" }

Role B
dependencies:
 - { role: C,            
              vnameC1: "{{vnB1}}",
              vnameC2: "{{vnB2}}" }

Role C
dependencies:
 - { role: D,            
              vnameD1: "{{vnC1}}",
              vnameD2: "{{vnC2}}" }

and so on
```

##### EXPECTED RESULTS

Everything to work :)

##### ACTUAL RESULTS

vnameB1 and vnameB2 are undefined with nested error messages showing substitution back to Role A

```

```

Is there a limit on how deep nested role dependencies can go?
