### ISSUE TITLE
yum module with rpm file failing to install when state=latest

### ISSUE THREAD

**Issue by jmalette** [ansible/ansible#23324]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

Yum

##### ANSIBLE VERSION

```
ansible 2.1.4.0
  config file = /Users/jacquesmalette/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

from: OSX 10.11.6
managing: RHEL 7

##### SUMMARY
I am attempting to install a local RPM package using state=latest.  This does not install the RPM if the RPM isn't already installed but will upgrade the RPM if there is a previous one installed.

##### STEPS TO REPRODUCE

```yaml
- name: Install or Update RPM
  yum:
    name: /tmp/test.rpm
    state: latest
  become: yes
```

##### EXPECTED RESULTS

I expected the rpm to install on the box if missing or upgrade if it's already there. 

##### ACTUAL RESULTS

RPM upgrades if already there
RPM does NOT install if missing

```

```
