### ISSUE TITLE
Proxmox KVM: Unable to create VMs

### ISSUE THREAD

**Issue by morph027** [ansible/ansible#23345]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

proxmox_kvm

##### ANSIBLE VERSION

```
2.2.1.0
```

plus

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/proxmox_kvm.py

and Proxmox:

```
pve-manager/4.4-13/7ea56165 (running kernel: 4.4.49-1-pve)
```

##### SUMMARY

Can't create VM's against PVE cluster anymore...

##### STEPS TO REPRODUCE

```
  - name: Create KVM
    proxmox_kvm:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      node: "{{ node }}"
      name: "foobar"
      net: '{"net0":"virtio,bridge={{ vmbr }}"}'
      virtio: '{"virtio0":"{{ storage }}:{{ disk_size }},cache=writeback"}'
      cores: 4
      memory: "{{ memory_size }}"
      balloon: 512
      vga: qxl
      ostype: l26
      state: present
```

##### EXPECTED RESULTS

VM gets created.

##### ACTUAL RESULTS

```
TASK [Create KVM] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "creation of qemu VM foobar with vmid xxx failed with exception='name'"}
```

**Comment by morph027** [comment]
@helldorado 

Strange thing is it looks like it's working against a single node (no cluster). Will doublecheck this.

**Comment by morph027** [comment]
Hm, no, got another cluster running ```pve-manager/4.4-13/7ea56165 (running kernel: 4.4.49-1-pve)``` and it works without issues...Any ideas how to debug stuff?

**Comment by morph027** [comment]
```
Invoked with force=None smbios=None boot=cnd startup=None agent=None freeze=None migrate_speed=None virtio={'virtio0': 'rpool-vm:16,cache=writeback'} keyboard=None watchdog=None serial=None numa_enabled=None sockets=1 digest=None template=False startdate=None api_user= bios=None balloon=512 format=qcow2 storage=None vga=qxl shares=None onboot=True machine=None hostpci=None state=present autostart=False memory=2048 net={'net0': 'virtio,bridge=vmbr0'} api_host=xxx migrate_downtime=None localtime=None node=xxx full=True description=None scsihw=None api_password=NOT_LOGGING_PARAMETER clone=None kvm=True args=-serial tcp:0.0.0.0:38285,server,nowait -kernel /tmp/kernel.38285 -initrd /tmp/initrd.38285 -append "inst.stage2=http://ftp.hosteurope.de/mirror/centos.org/7/os/x86_64/ inst.repo=http://ftp.hosteurope.de/mirror/centos.org/7/os/x86_64/ inst.ks=https://gitlab.com/morph027/kickstart-gitlab-ci-multi-runner/raw/master/gitlab-runner.cfg rd.noverifyssl hostname=foobar"  tdf=None update=False sata=None protection=None reboot=None numa=None parallel=None pool=None name=foobar lock=None ide=None tablet=False hotplug=None vmid=None snapname=None revert=None vcpus=None hugepages=None bootdisk=None ostype=l26 acpi=True cpuunits=1000 newid=None timeout=30 target=None skiplock=None cores=4 scsi=None cpulimit=None validate_certs=False cpu=kvm64 delete=None
```

**Comment by helldorado** [comment]
Hi,

This error can be made on a cluster in a different situation:

- the call to the get_nextvmid function passed too quickly after a previous query and the cluster is not up to date on all the nodes. Corosync lock ?
- loosing quorum
- One member of the cluster no longer answers

Hope puting `time.sleep (15)` in get_nextvimd wil solve your problem. like:

```python
def get_nextvmid(proxmox):
   time.sleep(15)
    try:
        vmid = proxmox.cluster.nextid.get()
        return vmid
    except Exception as e:
        module.fail_json(msg="Unable to get next vmid. Failed with exception: %s")
```

**Comment by morph027** [comment]
Thanks for your reply! :heart: 

Unfortunately, putting sleep into does not help.

I do have 2 offline nodes but the cluster still got quorum:

```
Votequorum information
----------------------
Expected votes:   7
Highest expected: 7
Total votes:      5
Quorum:           4  
Flags:            Quorate
```

It also has a free vm id as seen in the error. Weird.

**Comment by davidlapsleyio** [comment]
Hi: just wondering if there is a workaround for this? I'm hitting the same problem on a single node.

**Comment by helldorado** [comment]
Hi @delapsley please provide more info.

Version of your PVE and output in verbose mode.

**Comment by morph027** [comment]
Hm....issue is still present :(

**Comment by helldorado** [comment]
@delapsley @morph027 sorry for the late response.

Can you make an output of the following command from the primary node. The one specified in `api_host`?

`pvesh get /cluster/nextid`

If you get a valid `vmid` without no error, please use this id as parameter for `vmid` and remove parameter `name`.

If the creation of the host goes well, can provide me the proxmox side environment, as well as the playbook (remove any personal info) so that I do my tests in the same situation as you.

Of experience, this problem only occurs if there is an error on the cluster.

**Comment by morph027** [comment]
No hurry and thanks for checking in!

Same error with vmid instead of name.

```
# pvesh get /cluster/nextid
200 OK
"103"
```

This is the relevant parts of the playbook:

```
---

- hosts: localhost
  gather_facts: false

  vars_prompt:
  - name: "vmname"
    prompt: "Hostname"
    private: no

  - name: "api_host"
    prompt: "PVE API host"
    default: "proxmox-1"
    private: no

  - name: "node"
    prompt: "PVE target node"
    default: "proxmox-1"
    private: no

  - name: "storage"
    prompt: "PVE target storage"
    default: "rpool-vm"
    private: no

  - name: "disk_size"
    prompt: "boot disk size in GB"
    default: "8"
    private: no

  - name: "memory_size"
    prompt: "memory size in MB"
    default: "2048"
    private: no

  - name: "vmbr"
    prompt: "vmbr"
    default: "vmbr0"
    private: no

  - name: "api_user"
    prompt: "PVE API user"
    default: "root@pam"
    private: no

  - name: "api_password"
    prompt: "PVE API password"
    private: yes

  tasks:

  - name: Create KVM
    proxmox_kvm:
      api_user: "{{ api_user }}"
      api_password: "{{ api_password }}"
      api_host: "{{ api_host }}"
      node: "{{ node }}"
      #name: "{{ vmname }}"
      vmid: 103
      net: '{"net0":"virtio,bridge={{ vmbr }}"}'
      virtio: '{"virtio0":"{{ storage }}:{{ disk_size }},cache=writeback"}'
      cores: 4
      memory: "{{ memory_size }}"
      vga: qxl
      ostype: l26
      state: present
```

```
# pvecm n

Membership information
----------------------
    Nodeid      Votes Name
         7          1 xxx
         1          1 xxx
         3          1 xxx
         5          1 xxx
         6          1 xxx (local)
         8          1 xxx

# pvecm s
Quorum information
------------------
Date:             Wed Apr 26 07:33:38 2017
Quorum provider:  corosync_votequorum
Nodes:            6
Node ID:          0x00000006
Ring ID:          7/10168
Quorate:          Yes

Votequorum information
----------------------
Expected votes:   8
Highest expected: 8
Total votes:      6
Quorum:           5  
Flags:            Quorate 

Membership information
----------------------
    Nodeid      Votes Name
0x00000007          1 xxx
0x00000001          1 xxx
0x00000003          1 xxx
0x00000005          1 xxx
0x00000006          1 xxx (local)
0x00000008          1 xxx
```

2 Nodes are currently offline, but the cluster is still functional and has quorum.

PVE API requests during creation shows no errors as well:

```
xxx - - [26/Apr/2017:07:29:13 +0200] "POST /api2/json/access/ticket HTTP/1.1" 200 637
xxx - root@pam [26/Apr/2017:07:29:13 +0200] "GET /api2/json/version HTTP/1.1" 200 92
xxx - root@pam [26/Apr/2017:07:29:13 +0200] "GET /api2/json/cluster/resources?type=vm HTTP/1.1" 200 3425
xxx - root@pam [26/Apr/2017:07:29:13 +0200] "GET /api2/json/cluster/resources?type=vm HTTP/1.1" 200 3440
```

I'll try a quick test setup with nested PVE's and let you know.

**Comment by morph027** [comment]
Well...a cluster of three with one down still works.

**Comment by morph027** [comment]
My cluster appears to be fully functional, i can create VMs via WebGUI and ```qm``` (These are using the API too). Any hints how to debug further?

btw....have a nice weekend! ;)

**Comment by helldorado** [comment]
@morph027 , @delapsley

I'm sorry but i can't reproduce. 

## PVE Environment
```
pveversion
pve-manager/4.4-13/7ea56165 (running kernel: 4.4.49-1-pve)
```
```
pvecm s
Quorum information
------------------
Date:             Fri Apr 28 17:02:02 2017
Quorum provider:  corosync_votequorum
Nodes:            2
Node ID:          0x00000001
Ring ID:          2/5580
Quorate:          Yes

Votequorum information
----------------------
Expected votes:   2
Highest expected: 2
Total votes:      2
Quorum:           2
Flags:            Quorate

Membership information
----------------------
    Nodeid      Votes Name
0x00000002          1 x.x.x.x
0x00000001          1 x.x.x.x (local)
```

### Playbooks
```yaml
 ansible@spynal-orchestrator:/usr/local/ansible/orchestrator (master)$ cat playbooks/morph027.yml
- hosts: orchestrator
  remote_user: root
  tasks:
    - name: Create KVM
      proxmox_kvm:
        api_user: "root@pam"
        api_host: "pmxlab.helldorado.info"
        node: "awhlabhyp2"
        name: "morph"
        net: '{"net0":"virtio,bridge=vmbr0"}'
        virtio: '{"virtio0":"VMs_awhlabhyp2:50,cache=writeback"}'
        cores: 4
        memory: 2048
        balloon: 512
        vga: qxl
        ostype: l26
        state: present
```
> ℹ️  `api_password` not provide in playbook it's fetched from `PROXMOX_PASSWORD` environment variable.

### RUN with (-vvvv)
```yaml
ansible@spynal-orchestrator:/usr/local/ansible/orchestrator (master)$ ansible-playbook playbooks/morph027.yml -vvvv
Using /usr/local/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin unnamed of type old, v1.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: morph027.yml **********************************************************
1 plays in playbooks/morph027.yml

PLAY [orchestrator] ************************************************************

TASK [Create KVM] **************************************************************
task path: /usr/local/ansible/orchestrator/playbooks/morph027.yml:4
Using module file /usr/local/ansible/orchestrator/playbooks/library/proxmox_kvm.py
<spynal-orchestrator> ESTABLISH LOCAL CONNECTION FOR USER: abdoul.bah
<spynal-orchestrator> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1493392455.31-260320373581937 `" && echo ansible-tmp-1493392455.31-260320373581937="` echo $HOME/.ansible/tmp/ansible-tmp-1493392455.31-260320373581937 `" ) && sleep 0'
<spynal-orchestrator> PUT /tmp/tmp4zoJ8j TO /home/ansible/.ansible/tmp/ansible-tmp-1493392455.31-260320373581937/proxmox_kvm.py
<spynal-orchestrator> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1493392455.31-260320373581937/ /home/ansible/.ansible/tmp/ansible-tmp-1493392455.31-260320373581937/proxmox_kvm.py && sleep 0'
<spynal-orchestrator> EXEC /bin/sh -c '/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1493392455.31-260320373581937/proxmox_kvm.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1493392455.31-260320373581937/" > /dev/null 2>&1 && sleep 0'
changed: [spynal-orchestrator] => {
    "changed": true,
    "devices": {
        "virtio0": "VMs_awhlabhyp2:104/vm-104-disk-1.raw"
    },
    "invocation": {
        "module_args": {
            "acpi": true,
            "agent": null,
            "api_host": "pmxlab.helldorado.info",
            "api_password": null,
            "api_user": "root@pam",
            "args": null,
            "autostart": false,
            "balloon": 512,
            "bios": null,
            "boot": "cnd",
            "bootdisk": null,
            "clone": null,
            "cores": 4,
            "cpu": "kvm64",
            "cpulimit": null,
            "cpuunits": 1000,
            "delete": null,
            "description": null,
            "digest": null,
            "force": null,
            "format": "qcow2",
            "freeze": null,
            "full": true,
            "hostpci": null,
            "hotplug": null,
            "hugepages": null,
            "ide": null,
            "keyboard": null,
            "kvm": true,
            "localtime": null,
            "lock": null,
            "machine": null,
            "memory": 2048,
            "migrate_downtime": null,
            "migrate_speed": null,
            "name": "morph",
            "net": {
                "net0": "virtio,bridge=vmbr0"
            },
            "newid": null,
            "node": "awhlabhyp2",
            "numa": null,
            "numa_enabled": null,
            "onboot": true,
            "ostype": "l26",
            "parallel": null,
            "pool": null,
            "protection": null,
            "reboot": null,
            "revert": null,
            "sata": null,
            "scsi": null,
            "scsihw": null,
            "serial": null,
            "shares": null,
            "skiplock": null,
            "smbios": null,
            "snapname": null,
            "sockets": 1,
            "startdate": null,
            "startup": null,
            "state": "present",
            "storage": null,
            "tablet": false,
            "target": null,
            "tdf": null,
            "template": false,
            "timeout": 30,
            "update": false,
            "validate_certs": false,
            "vcpus": null,
            "vga": "qxl",
            "virtio": {
                "virtio0": "VMs_awhlabhyp2:50,cache=writeback"
            },
            "vmid": null,
            "watchdog": null
        },
        "module_name": "proxmox_kvm"
    },
    "mac": {
        "net0": "36:60:D7:38:31:4E"
    },
    "msg": "VM morph with vmid 104 deployed",
    "vmid": 104
}

PLAY RECAP *********************************************************************
spynal-orchestrator        : ok=1    changed=1    unreachable=0    failed=0
```
### RUN AGAIN with (-vvvv)
```yaml
ansible@spynal-orchestrator:/usr/local/ansible/orchestrator (master)$ ansible-playbook playbooks/morph027.yml -vvvv
Using /usr/local/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin unnamed of type old, v1.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: morph027.yml **********************************************************
1 plays in playbooks/morph027.yml

PLAY [orchestrator] ************************************************************

TASK [Create KVM] **************************************************************
task path: /usr/local/ansible/orchestrator/playbooks/morph027.yml:4
Using module file /usr/local/ansible/orchestrator/playbooks/library/proxmox_kvm.py
<spynal-orchestrator> ESTABLISH LOCAL CONNECTION FOR USER: abdoul.bah
<spynal-orchestrator> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1493392600.58-127717646529100 `" && echo ansible-tmp-1493392600.58-127717646529100="` echo $HOME/.ansible/tmp/ansible-tmp-1493392600.58-127717646529100 `" ) && sleep 0'
<spynal-orchestrator> PUT /tmp/tmpX1BXtQ TO /home/ansible/.ansible/tmp/ansible-tmp-1493392600.58-127717646529100/proxmox_kvm.py
<spynal-orchestrator> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1493392600.58-127717646529100/ /home/ansible/.ansible/tmp/ansible-tmp-1493392600.58-127717646529100/proxmox_kvm.py && sleep 0'
<spynal-orchestrator> EXEC /bin/sh -c '/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1493392600.58-127717646529100/proxmox_kvm.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1493392600.58-127717646529100/" > /dev/null 2>&1 && sleep 0'
ok: [spynal-orchestrator] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "acpi": true,
            "agent": null,
            "api_host": "pmxlab.helldorado.info",
            "api_password": null,
            "api_user": "root@pam",
            "args": null,
            "autostart": false,
            "balloon": 512,
            "bios": null,
            "boot": "cnd",
            "bootdisk": null,
            "clone": null,
            "cores": 4,
            "cpu": "kvm64",
            "cpulimit": null,
            "cpuunits": 1000,
            "delete": null,
            "description": null,
            "digest": null,
            "force": null,
            "format": "qcow2",
            "freeze": null,
            "full": true,
            "hostpci": null,
            "hotplug": null,
            "hugepages": null,
            "ide": null,
            "keyboard": null,
            "kvm": true,
            "localtime": null,
            "lock": null,
            "machine": null,
            "memory": 2048,
            "migrate_downtime": null,
            "migrate_speed": null,
            "name": "morph",
            "net": {
                "net0": "virtio,bridge=vmbr0"
            },
            "newid": null,
            "node": "awhlabhyp2",
            "numa": null,
            "numa_enabled": null,
            "onboot": true,
            "ostype": "l26",
            "parallel": null,
            "pool": null,
            "protection": null,
            "reboot": null,
            "revert": null,
            "sata": null,
            "scsi": null,
            "scsihw": null,
            "serial": null,
            "shares": null,
            "skiplock": null,
            "smbios": null,
            "snapname": null,
            "sockets": 1,
            "startdate": null,
            "startup": null,
            "state": "present",
            "storage": null,
            "tablet": false,
            "target": null,
            "tdf": null,
            "template": false,
            "timeout": 30,
            "update": false,
            "validate_certs": false,
            "vcpus": null,
            "vga": "qxl",
            "virtio": {
                "virtio0": "VMs_awhlabhyp2:50,cache=writeback"
            },
            "vmid": null,
            "watchdog": null
        },
        "module_name": "proxmox_kvm"
    },
    "msg": "VM with name <morph> already exists"
}

PLAY RECAP *********************************************************************
spynal-orchestrator        : ok=1    changed=0    unreachable=0    failed=0
```

If you need help, you can ping me on `ansible` or `ansible-devel`  irc channel. 

Annyway if you have time, give me the play raw output with (-vvvv)
