### ISSUE TITLE
Ansible: How to run the for command through playbook

### ISSUE THREAD

**Issue by nb00471049** [ansible/ansible#23348]
##### ISSUE TYPE

 - Bug Report
ansible 2.2.0.0
##### COMPONENT NAME

-
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```
##### STEPS TO REPRODUCE

```
- name: "Fetch the ip of all the servers from hosts.new file"
  command: for i in `awk '{print $1}' hosts.new`
            do echo "$i"
            done
  args:
    chdir: "/home/dp794d/"
  failed_when: "output.rc > 1"
  register: output
```

##### EXPECTED RESULTS
<Ifor command must run from the playbook
##### ACTUAL RESULTS

```
fatal: [zlp12037]: FAILED! => {"changed": false, "cmd": "for i in 'awk' '{print $1}' 'hosts.new' do echo '$i' done", "failed": true, "failed_when_result": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
>
```

```
-
```

**Comment by snowsky** [comment]
@nb00471049 could you please use ``` to quote the playbook?

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, the `command` module does not allow shellisms, for that use the `shell` module.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by nb00471049** [comment]
I have used the shell instead of command, still the register variable output is coming as empty. Can anyone please suggest what changes exactly needs to be done

**Comment by snowsky** [comment]
@nb00471049 you missed ; in shell command. This works:
```
    - name: "Fetch the ip of all the servers from hosts.new file"
      shell: for i in `awk '{print $1}' hosts.new`; do echo "$i"; done
      args:
        chdir: "/home/ubuntu/ansible"
      failed_when: "output.rc > 1"
      register: output
```
