### ISSUE TITLE
Conditional succeeds in 2.1.1.0 but fails in 2.2.2.0

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#23358]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.1.1.0 
2.2.2.0
```

##### CONFIGURATION
```
[defaults]
inventory = inventory/site
host_key_checking=False
timout=30 
allow_world_readable_tmpfiles=True
```

##### COMPONENT NAME
`changed_when`

##### OS / ENVIRONMENT
Ubuntu 16.04.01

##### SUMMARY
A specific conditional that succeeded with version 2.1.1.0 is now failing with version 2.2.2.0.

##### STEPS TO REPRODUCE
1. Hit a specific rest endpoint to register a variable to be used for a check

```
- name: get users list
  uri:
    url: "{{ api_endpoint }}/security/users"
    user: 'myusername'
    password: 'mypassword'
    return_content: yes
  register: groups_list
```

2. Make a task changed based on a specific conditional

```
- name: create readers / groups
  uri:
    url: "{{ api_endpoint }}/security/groups/{{ item }}-readers"
    method: PUT
    user: 'myusername'
    password: 'mypassword'
    body: "{{ readers_group_json|to_json }}"
    force_basic_auth: yes
    body_format: json
    return_content: yes
    status_code: 201
  with_items: "{{ projects }}"
  changed_when: "'{{ item }}-readers' not in '{{ groups_list.content }}'"
```
The problem is in `changed_when`. This conditional was being executed without issues on `2.1.1.0`
On `2.2.2.0` I get the following error:

```
fatal: [10.10.49.99]: FAILED! => {"failed": true, "msg": "The conditional check ''{{ item }}-readers' not in '{{ groups_list.content }}'' failed. The error was: Invalid conditional detected: EOL while scanning string literal (<unknown>, line 1)"}
```

When I downgrade to `2.1.1.0` it works, when I upgrade to `2.2.2.0` I get the error again (without modifying anything in the play)
