### ISSUE TITLE
os_server works extremely slow with large tenants 

### ISSUE THREAD

**Issue by ksoftirqd** [ansible/ansible#23354]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
os_server

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /Users/user1/.ansible.cfg
  configured module search path = Default w/o overrides
```
shade 1.19.0

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
os_server module works extremely slow when a tenant has many instances (~200)

##### STEPS TO REPRODUCE
```yaml
- name: Create vms
  os_server:
    state: present
    auth:
      username: "{{ lookup('env', 'OS_USERNAME') }}"
      project_name: "{{ lookup('env', 'OS_TENANT_NAME') }}"
      auth_url: "{{ lookup('env', 'OS_AUTH_URL') }}"
    name: "test{{'{0:03d}'.format(item|int)}}"
    image: "{{ vars.image_name }}"
    key_name: "{{ vars.key_name }}"
    flavor: "{{ vars.flavor_name }}"
    auto_ip: no
    network: "{{ vars.network }}"
  register: servers
  with_sequence:
    count="{{ vars.servers_num }}"

```

##### EXPECTED RESULTS
Time needed to create instances with ansible is comparable to other tools (e.g. python-openstackclient, terraform, etc)

##### ACTUAL RESULTS
When ansible creates openstack instances, it uses shade library to do that, and whenever a new instance is created, it:
 - waits for the instance to become available
 - tries to get a full list of all instances in that tenant
 - tries to pre populate server list with instance details by doing different API calls for every instance in the list (e.g. `PortList`, `NeutronFloatingIPList`)

A stack trace looks similar to this:
```
create_server [OpenStackCloud] <decorator-gen-6>:2 ->
 func_wrapper _utils.py:393 ->
  create_server [OpenStackCloud] openstackcloud.py:5515 ->
   wait_for_server [OpenStackCloud] openstackcloud.py:5541 ->
    get_server [OpenStackCloud] openstackcloud.py:2761 ->
     _get_entity _utils.py:212 ->
      search_servers [OpenStackCloud] openstackcloud.py:1571 ->
       list_servers [OpenStackCloud] openstackcloud.py:1969 ->
        _list_servers [OpenStackCloud] openstackcloud.py:1996 ->
         add_server_interfaces meta.py:385 ->
          _get_supplemental_addresses meta.py:349 ->
           search_ports [OpenStackCloud] openstackcloud.py:1533 ->
            list_ports [OpenStackCloud] openstackcloud.py:1685 [...]
```

If we could make it run `get_server` with `bare=True`, it would improve situation a lot.
