### ISSUE TITLE
junso_config fails if 'src' contains set format

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#23360]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_config
##### ANSIBLE VERSION

```
2.3
```

##### STEPS TO REPRODUCE

```yaml
---
- name: setup
  hosts: junos_mx
  connection: local
  tasks:
  - name: "junos_mx"
    junos_config:
      host: junos_mx
      username: "xxx"
      password: "xxx"
      backup: yes
      src: config.set
```
```
#cat config.set
set interfaces ge-0/0/8 unit 0 description "abc"
delete interfaces ge-0/0/7
```

##### ACTUAL RESULTS

```
fatal: [junos_mx]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "backup": true, 
            "comment": "configured by junos_config", 
            "confirm": 0, 
            "host": "junos_mx", 
            "lines": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": null, 
            "replace": null, 
            "rollback": null, 
            "src": "set interfaces ge-0/0/8 unit 0 description \"abc\"\ndelete interfaces ge-0/0/7\n", 
            "src_format": null, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": null, 
            "update": "merge", 
            "username": "root", 
            "zeroize": false
        }
    }, 
    "msg": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc-error xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" xmlns:junos=\"http://xml.juniper.net/junos/12.1R1/junos\" xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n<error-severity>error</error-severity>\n<error-info>\n<bad-element>set</bad-element>\n</error-info>\n<error-message>syntax error</error-message>\n</rpc-error>\n"
}

```
