### ISSUE TITLE
Ansible: get docker container output during container creation

### ISSUE THREAD

**Issue by vinigfer** [ansible/ansible#23375]
##### ISSUE TYPE
 - Bug Report/Feature Idea

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/vinicius/sentry/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Ubuntu 16.04.2

##### SUMMARY
When creating a docker container that produces an output (a secret key), no output is set when using the "register" option.

##### STEPS TO REPRODUCE
Run a simple docker container such as hello-world

```yaml
    ...
    - name: Cria secret key para utilizacao em passos seguintes
      docker_container:
        name: sentry-key-generator
        cleanup: True
        image: hello-world   #sentry-onpremise
      register: saida
      tags:
        - debug
 
    - fail:
        msg: "Valor de saida: {{ saida }}"
      tags:
        - debug
    ....
```

##### EXPECTED RESULTS
Hello from Docker!
...

##### ACTUAL RESULTS
Nothing. The output for the running Ansible playbook is something like this:

TASK [Cria secret key para utilizacao em passos seguintes] *********************
changed: [45.56.93.133]

TASK [fail] ********************************************************************
fatal: [45.56.93.133]: FAILED! => {"changed": false, "failed": true, "msg": "Valor de saida: {u'changed': True, u'ansible_facts': {}}"}
