### ISSUE TITLE
rds.py reverts multi-AZ RDS back to single-AZ on any 'modify' action where 'multi_zone' is not specified

### ISSUE THREAD

**Issue by bobobox** [ansible/ansible#23385]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rds.py

##### ANSIBLE VERSION
```
ansible 2.3.0.0 (stable-2.3 0fe53eda86) last updated 2017/04/06 22:20:16 (GMT -500)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
Any 'modify' action using the rds.py module taken against a multi-AZ RDS, where the optional `multi_zone` parameter is not explicitly included in the task, results in the RDS being modified to a single-AZ RDS.

##### STEPS TO REPRODUCE
Example playbook:

```
---

- name: Update password on RDS
  hosts: localhost
  tasks:
    - name: Apply new password to RDS
      rds:
        region: us-east-1
        command: modify
        instance_name: some-rds-12345
        password: supersekrit123

```

##### EXPECTED RESULTS
The `password` and/or other specified parameters are updated, while the `multi_zone` (multi-AZ) status of the RDS is left alone unless specified.

##### ACTUAL RESULTS
The requested parameters are updated but in addition, the RDS is changed as if we had specified `multi_zone` to false (ie. multi-AZ is disabled).
