### ISSUE TITLE
Include variables with with_first_found looks into tasks path

### ISSUE THREAD

**Issue by kfeine** [ansible/ansible#23392]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`include_vars` / `with_first_found`

##### ANSIBLE VERSION

```
ansible 2.2.2.0
```

##### CONFIGURATION

I use a standard configuration.

##### OS / ENVIRONMENT

Debian 8.7

##### SUMMARY

When using `include_vars` with a `with_first_found`, **Ansible will look for a matching variable file in tasks directory before matching the next option**.
If I understand [the documentation](https://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) well, it is not the expected behavior.

##### STEPS TO REPRODUCE

Create a role with missing variables files for some OS, and add a task with those OS name:
```
roles/test-bug
├── tasks
│   ├── CentOS.yml
│   ├── main.yml
│   └── Ubuntu.yml
└── vars
    ├── Debian.yml
    ├── default.yml
    └── Ubuntu.yml
```

Then try to include variables in `main.yml`:
```yaml
---

- name: set specific variables for distributions
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- name: say something
  debug: msg="foo={{ foo }}"
```

##### EXPECTED RESULTS

```
$ ansible-playbook main.yml

PLAY [run test role] ***********************************************************

TASK [setup] *******************************************************************
ok: [test-debian]
ok: [test-centos]
ok: [test-ubuntu]

TASK [test-bug : set specific variables for distributions] *********************
ok: [test-debian] => (item=/etc/ansible/roles/test-bug/vars/Debian.yml)
ok: [test-centos] => (item=/etc/ansible/roles/test-bug/vars/default.yml)
ok: [test-ubuntu] => (item=/etc/ansible/roles/test-bug/vars/Ubuntu.yml)

TASK [test-bug : say something] ************************************************
ok: [test-debian] => {
    "msg": "foo=Debian"
}
ok: [test-centos] => {
    "msg": "foo=default"
}
ok: [test-ubuntu] => {
    "msg": "foo=Ubuntu"
}

PLAY RECAP *********************************************************************
test-centos : ok=3    changed=0    unreachable=0    failed=0
test-debian : ok=3    changed=0    unreachable=0    failed=0
test-ubuntu : ok=3    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
$ ansible-playbook main.yml

PLAY [run test role] ***********************************************************

TASK [setup] *******************************************************************
ok: [test-debian]
ok: [test-centos]
ok: [test-ubuntu]

TASK [test-bug : set specific variables for distributions] *********************
failed: [test-centos] (item=/etc/ansible/roles/test-bug/tasks/RedHat.yml) => {"ansible_facts": {}, "failed": true, "item": "/etc/ansible/roles/test-bug/tasks/RedHat.yml", "message": "/etc/ansible/roles/test-bug/tasks/RedHat.yml must be stored as a dictionary/hash"}
ok: [test-debian] => (item=/etc/ansible/roles/test-bug/vars/Debian.yml)
ok: [test-ubuntu] => (item=/etc/ansible/roles/test-bug/vars/Ubuntu.yml)

TASK [test-bug : say something] ************************************************
ok: [test-debian] => {
    "msg": "foo=Debian"
}
ok: [test-ubuntu] => {
    "msg": "foo=Ubuntu"
}

PLAY RECAP *********************************************************************
test-centos : ok=1    changed=0    unreachable=0    failed=1
test-debian : ok=3    changed=0    unreachable=0    failed=0
test-ubuntu : ok=3    changed=0    unreachable=0    failed=0
```

Thanks,
Regards,

**Comment by aurimasl** [comment]
I think it's not a bug, it may just be poorly documented feature. `with_first_found` does lookup in current directory, so it means you should specify different path as in ansible test https://github.com/ansible/ansible/blob/31d6b6ef67636537037f542e4d089e411843bd44/test/integration/targets/setup_postgresql_db/tasks/main.yml#L11-L18

**Comment by vincent-legoll** [comment]
It is not only a poorly documented thing, as the error message is not really helping.

Maybe that's a separate issue though.

**Comment by yjftsjthsd-g** [comment]
This bug still occurs in Ansible 2.7.7, and I would argue that it _is_ a bug and not just a poorly documented feature, because `include_vars` should not look at tasks. I understand that it might be nontrivial to make `with_first_found` behave differently depending on what is using it, but always including _tasks_ is inconsistent with an apparently generic function.

**Comment by eproxus** [comment]
Using `paths:` doesn't even work. The following finds `tasks/main.yml` and not `vars/main.yml`:

```
- name: include OS specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - paths:
      - ../vars
    - files:
      - "os/{{ansible_system|lower}}.yml"                # linux.yml
      - "main.yml"                                       # main.yml
```

**Comment by bcoca** [comment]
Let me clarify some things:
- `with_first_found` IS aware of the task action, if it has 'var' in the name, it will add 'vars' subdir to the searchpath when using include_vars.
- the `paths` option adds 'additional' paths to search, the basic search paths are always used
- the `ansible_search_path` variable will show the 'top level search paths used' , this always includes 'current task directory' at the end of the list. `tasks/` is only searched because that is where the task is defined.

This is why in a role you will always hit `tasks/main.yml` if no other file is found first, in any case adding `vars/main.yml` would be irrelevant in a role (since the role import itself has higher precedence and this would be a repeat that would never get used), so it is a bad default by definition and something I do not recommend.

**Comment by eproxus** [comment]
@bcoca Interesting information, thanks!

It sound like including dynamic files can get all kinds of messy fast. I wanted to make a task that includes dynamic OS vars _and_ dynamic OS tasks. I guess this can include tasks by mistake when a variable file is not defined for that OS?

**Comment by bcoca** [comment]
my suggestion (top my head, might need fixes):
```yaml
- name: include OS specific vars
  include_vars: "{{ myfiles }}"
  when: myfiles
  vars:
    myfiles: '{{ lookup("first_found", files=candidates, paths='../vars')|default([])}}'
    candidates:
      - "os/{{ansible_system|lower}}.yml"      
```
you can have many variations on this, but MAIN issue is 'do not include main.yml'
