### ISSUE TITLE
win_copy with remote_src=true not working

### ISSUE THREAD

**Issue by sergey-rsa** [ansible/ansible#23403]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.2.2.0
```

##### OS / ENVIRONMENT

ubuntu 16.04
windows server 2016
##### SUMMARY

doc at http://docs.ansible.com/ansible/win_copy_module.html do not contain any info about original_basename. but must be set for win_copy. But also not work with it.
##### STEPS TO REPRODUCE

```yaml
  win_copy:
    src: 'c:\tmp\1'
    dest: 'c:\tmp\2'
    original_basename: 'c:\tmp'
    remote_src: True
```

##### EXPECTED RESULTS

files and folder from c:\tmp\1 in c:\tmp\2
##### ACTUAL RESULTS

error 

```
FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "dest": "c:\\tmp\\2",
            "original_basename": "c:\\tmp",
            "remote_src": true,
            "src": "c:\\tmp\\1"
        },
        "module_name": "win_copy"
    },
    "msg": "If src is a folder, dest must also be a folder"
}

```
