### ISSUE TITLE
Failure in ec2_vpc_subnet module creating sunet with pre-existing one - InvalidSubnet.Conflict

### ISSUE THREAD

**Issue by michael-dev2rights** [ansible/ansible#23400]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_vpc_subnet

##### ANSIBLE VERSION

```
ansible 2.3.0.0 (stable-2.3 0fe53eda86) last updated 2017/04/07 13:52:27 (GMT +100)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mikedd/dev/ansible/ansible-add-modules/library']
  python version = 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

this is standard stable taken straight out of git today

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS + boto/boto3 from PIP

##### SUMMARY

In the case where I already have a smaller subnet existing inside the range of a subnet to be created ec_vpc_subnet fails to create the new subnet

##### STEPS TO REPRODUCE

1) create subnet 10.12.34.16/28 named Ansible Testing Subnet

tu 

```
- hosts: localhost
  tasks:
  - name: Create subnet for use in testing
    ec2_vpc_subnet:
      region: us-east-1
      tags: create_subnet
      state: present
      vpc_id: vpc-12345678
      cidr: 10.12.34.0/24
      resource_tags:
        Name: Ansible Testing Subnet
    register: testing_subnet

```

##### EXPECTED RESULTS

Normally I'd expect ansible to create the subnet.  
If theres a decision not to I'd expect it to fail with a clear message saying what to do

##### ACTUAL RESULTS
Asible bombs out with error below

```
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] *******************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create subnet for use in testing] ********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to create subnet 10.12.34.0/24, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidSubnet.Conflict</Code><Message>The CIDR '10.12.34.0/24' conflicts with another subnet</Message></Error></Errors><RequestID>xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx</RequestID></Response>"}
	to retry, use: --limit @/home/mikedd/bug/ansible/ec2_vpc_subnet/ec2_vpc_subjet_cidr_fix_fail.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  
```
