### ISSUE TITLE
cloudformation_facts fails if stack doesn't exist

### ISSUE THREAD

**Issue by knightsg** [ansible/ansible#23419]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
cloudformation_facts module

##### ANSIBLE VERSION

```
ansible 2.2.3.0 (stable-2.2 7ff9fa52cf) last updated 2017/04/07 11:55:42 (GMT -700)
  lib/ansible/modules/core: (detached HEAD cfe3c844f4) last updated 2017/04/07 11:55:49 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 8b78d56a08) last updated 2017/04/07 11:55:49 (GMT -700)
  config file = /Users/guy.knights/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
* Added 'hash_behaviour = merge'

##### OS / ENVIRONMENT
Control machine: OSX 10.12.3
Managed machine: same (playbook execution=local)

##### SUMMARY
The cloudformation_facts module causes ansible-playbook to fail if the stack name given doesn't exist. In my use case, I have a playbook that's creating IAM user keys, and it's possible to pass in an incremented serial number if the keys are to be rotated. I want to get this number from the existing stack, or set it to 0 if the stack doesn't yet exist, but the playbook fails when cloudformation_facts is run.

I'm currently using ignore_errors=true on this task, which works, but it spits out a big red error message before continuing. It would be nicer if it just continued but returned a variable with a "stack_exists" value set to false, or something similar.

##### STEPS TO REPRODUCE
Create at task using the cloudformation_facts module, passing in the name of a stack that doesn't exist.

```yaml
- cloudformation_facts:
    stack_name: "{{ vpcenvironment }}-iam"
    region: "{{ whitelabel_data[wl_name].region }}"
    profile: "{{ wl_name }}"
  register: stack_iam_data

- block:
  - set_fact:
      key_index: "{{ stack_iam_data['ansible_facts']['cloudformation'][vpcenvironment + '-iam']['stack_description']['parameters']|selectattr('parameter_key', 'equalto', 'AccessKeySerial')|map(attribute='parameter_value')|list }}"

  - set_fact:
      key_serial: "{{ key_index[0]|int }}"
    when: rotate_keys == 'n'

  - set_fact:
      key_serial: "{{ key_index[0]|int + 1 }}"
    when: rotate_keys == 'y'
  when: stack_iam_data['failed'] is not defined

- name: create IAM stack
  cloudformation:
    stack_name: "{{ vpcenvironment }}-iam"
    state: present
    region: "{{ whitelabel_data[wl_name].region }}"
    template_url: https://bbcloudformation.s3.amazonaws.com/GTP/GTPIAMConfig.json
    profile: "{{ wl_name }}"
    template_parameters:
      GTPWhitelabelName: "{{ wl_name }}"
      Environment: "{{ vpcenvironment }}"
      AccessKeySerial: "{{ key_serial | default(0) }}"
    tags:
      Name: "{{ wl_name }}"
      Type: iam
      Creator: ansible
      Environment: "{{ vpcenvironment }}"
```

##### EXPECTED RESULTS
Playbook execution would continue, but stack_iam_data would be empty or have a key to indicate no data was returned.

##### ACTUAL RESULTS
Playbook execution fails with big red error message saying stack doesn't exist.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id dev-iam does not exist
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error describing stack - An error occurred (ValidationError) when calling the DescribeStacks operation: Stack with id dev-iam does not exist"}
```

**Comment by ansibot** [comment]
cc @jmenga
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mixja** [comment]
You could use the Ansible blocks feature to handle the failure - http://docs.ansible.com/ansible/playbooks_blocks.html#error-handling

```
- block:
  - cloudformation_facts:
       stack_name: "{{ vpcenvironment }}-iam"
       region: "{{ whitelabel_data[wl_name].region }}"
       profile: "{{ wl_name }}"
     register: stack_iam_data
  - set_fact:
      key_index: "{{ stack_iam_data['ansible_facts']['cloudformation'][vpcenvironment + '-iam']['stack_description']['parameters']|selectattr('parameter_key', 'equalto', 'AccessKeySerial')|map(attribute='parameter_value')|list }}"
  - set_fact:
      key_serial: "{{ key_index[0]|int }}"
    when: rotate_keys == 'n'
  - set_fact:
      key_serial: "{{ key_index[0]|int + 1 }}"
    when: rotate_keys == 'y'
  rescue:
  - debug: msg="Perform some exception handling tasks here"
```

**Comment by knightsg** [comment]
Interesting, I will check that out. It's been a while since I've looked at the block feature and I hadn't read the error handling section.

This should be a satisfactory workaround for my issue but I still kind of feel like the best workflow would be that the module shouldn't fail, just return a message to indicate the stack wasn't found. It's not like a facts module (or, at least this one) makes a change which could break things.

**Comment by mixja** [comment]
Sounds reasonable - the failed key signals failure to Ansible, so perhaps setting the return code to non-zero with empty output is the best approach based upon the best practices guide - 
http://docs.ansible.com/ansible/dev_guide/developing_modules_best_practices.html

**Comment by knightsg** [comment]
Yes, and actually I just tried the block/rescue approach you outlined and while it does indeed work fine, it still spits out a big red error message which looks nasty and in certain situations possibly confusing.

**Comment by mixja** [comment]
You can suppress (**ALL**) errors from any task using `failed_when: false` but I agree it is not ideal

**Comment by knightsg** [comment]
Yep, I gave that a go and it does help cover up the error output, but then
I had to add a bunch of conditions to the rest of the tasks in the block so
they wouldn't also fail which added a degree of complexity to the whole
thing.

**Comment by knightsg** [comment]
Good suggestion. I did that and it's helped me achieve what I was after.

Thanks!

**Comment by lobsterdore** [comment]
I've been specifically checking for stack doesn't exist and stack exists like so:

```YAML
- cloudformation_facts:
    stack_name: "{{ vpcenvironment }}-iam"
    region: "{{ whitelabel_data[wl_name].region }}"
    profile: "{{ wl_name }}"
  register: stack_iam_data
  failed_when:
    - "'msg' in stack_iam_data and 'does not exist' not in stack_iam_data.msg"
    - "'ansible_facts' not in stack_iam_data"
```

This means that API throttling and errors like that will still cause a failure, which I think is preferred.
