### ISSUE TITLE
Add support to user module for overwriting the SSH key

### ISSUE THREAD

**Issue by gaddman** [ansible/ansible#23439]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
user module

##### SUMMARY
Add support for overwriting the SSH key.

##### JUSTIFICATION
The user module is able to generate an SSH key for a new user, but is not able to overwrite an existing key. In some scenarios it is useful to regenerate SSH keys, such as when they have been compromised or a templated filesystem is used.
One current workaround is an initial task to delete the existing SSH key, followed by another task to create the new one, for example:

```yaml
  - name: Delete current SSH client key
    file: path=~/.ssh/id_rsa state=absent
    when: regenerateSSHkeys

  - name: Generate new SSH key pair
    user: name=chris generate_ssh_key=yes
```
This is risky since if the playbook fails after the first task then all hosts in the playbook have lost their SSH key with no new one generated.

##### PROPOSAL
The user module uses ssh-keygen to create the SSH key, and while this can overwrite an existing key, it can only do so interactively. As in [this advice](http://stackoverflow.com/a/15890748/3592326) the user module could use pipe like so:
`echo y | ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa`
Whether to overwrite or not could be determined by the existing `force` flag.

I'm happy to write a pull request to do this, but thought I'd check if it's something people want, and if the suggested approach is reasonable.
