### ISSUE TITLE
MXRRDATAPriorityRequired when adding an MX record with Route53

### ISSUE THREAD

**Issue by aquarion** [ansible/ansible#23435]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

route53

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /home/aquarion/code/autopelago/ansible/ansible.cfg
  configured module search path = Default w/o overrides
 ```
##### CONFIGURATION

```
🔹 @archipelago (master *) ~/code/autopelago/ansible: cat ansible.cfg 
[defaults]
inventory = ./inventory
roles_path = galaxy-roles
```

##### OS / ENVIRONMENT
Running from OS X and also tried on Debian

##### SUMMARY

When attempting to create an AWS Route53 MX record, I get an error about not having a priority field. This worked with Ansible 2.0, but not since I upgraded to 2.2

##### STEPS TO REPRODUCE

As far as I can tell, this happens with any MX record attempting to be created with Ansible 2.2

Using 2.0, the following code worked:

```yaml
- name: aquarionics.com. - MX
  route53:
      overwrite: true
      command: "create"
      zone: "aquarionics.com"
      record: "aquarionics.com."
      type: "MX"
      ttl: "300"
      value: [
        '10 ASPMX.L.GOOGLE.COM.',
        '10 ALT1.ASPMX.L.GOOGLE.COM.',
        '20 ALT2.ASPMX.L.GOOGLE.COM.',
        '20 ASPMX2.GOOGLEMAIL.COM.',
        '30 ASPMX3.GOOGLEMAIL.COM.'
        ]
```

When running it with 2.2, I get the error:

```TASK [aws-aqcom-dns : aquarionics.com. - MX] ***********************************
fatal: [archipelago.water.gkhs.net]: FAILED! => {"changed": false, "failed": true, "msg": "Invalid Resource Record: FATAL problem: MXRRDATAPriorityRequired (MX record doesn't have a priority field) encountered with ''10 ALT1.ASPMX.L.GOOGLE.COM.''"}```

( https://github.com/aquarion/autopelago/blob/master/ansible/roles/aws-aqcom-dns/tasks/aquarionics.yml#L25-L39 )

##### EXPECTED RESULTS

An MX record would be created if it didn't exist (it does)

##### ACTUAL RESULTS

``` TASK [aws-aqcom-dns : aquarionics.com. - MX] ***********************************
task path: /home/aquarion/code/autopelago/ansible/roles/aws-aqcom-dns/tasks/aquarionics.yml:25
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/cloud/amazon/route53.py
<archipelago.water.gkhs.net> ESTABLISH SSH CONNECTION FOR USER: None
<archipelago.water.gkhs.net> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/aquarion/.ansible/cp/ansible-ssh-%h-%p-%r archipelago.water.gkhs.net '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<archipelago.water.gkhs.net> ESTABLISH SSH CONNECTION FOR USER: None
<archipelago.water.gkhs.net> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/aquarion/.ansible/cp/ansible-ssh-%h-%p-%r archipelago.water.gkhs.net '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/aquarion/.ansible/tmp/ansible-tmp-1491702681.7-43611308904749 `" && echo ansible-tmp-1491702681.7-43611308904749="` echo /home/aquarion/.ansible/tmp/ansible-tmp-1491702681.7-43611308904749 `" ) && sleep 0'"'"''
<archipelago.water.gkhs.net> PUT /tmp/tmpGBZEVB TO /home/aquarion/.ansible/tmp/ansible-tmp-1491702681.7-43611308904749/route53.py
<archipelago.water.gkhs.net> SSH: EXEC sftp -b - -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/aquarion/.ansible/cp/ansible-ssh-%h-%p-%r '[archipelago.water.gkhs.net]'
<archipelago.water.gkhs.net> ESTABLISH SSH CONNECTION FOR USER: None
<archipelago.water.gkhs.net> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/aquarion/.ansible/cp/ansible-ssh-%h-%p-%r archipelago.water.gkhs.net '/bin/sh -c '"'"'chmod u+x /home/aquarion/.ansible/tmp/ansible-tmp-1491702681.7-43611308904749/ /home/aquarion/.ansible/tmp/ansible-tmp-1491702681.7-43611308904749/route53.py && sleep 0'"'"''
<archipelago.water.gkhs.net> ESTABLISH SSH CONNECTION FOR USER: None
<archipelago.water.gkhs.net> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/aquarion/.ansible/cp/ansible-ssh-%h-%p-%r -tt archipelago.water.gkhs.net '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-gzvpzznlelymjipfexwspwaryookxsge; /usr/bin/python /home/aquarion/.ansible/tmp/ansible-tmp-1491702681.7-43611308904749/route53.py; rm -rf "/home/aquarion/.ansible/tmp/ansible-tmp-1491702681.7-43611308904749/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [archipelago.water.gkhs.net]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "alias": null, 
            "alias_evaluate_target_health": false, 
            "alias_hosted_zone_id": null, 
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "command": "create", 
            "ec2_url": null, 
            "failover": null, 
            "health_check": null, 
            "hosted_zone_id": null, 
            "identifier": null, 
            "overwrite": true, 
            "private_zone": false, 
            "profile": null, 
            "record": "aquarionics.com.", 
            "region": null, 
            "retry_interval": "500", 
            "security_token": null, 
            "ttl": 300, 
            "type": "MX", 
            "validate_certs": true, 
            "value": "['10 ASPMX.L.GOOGLE.COM.', '10 ALT1.ASPMX.L.GOOGLE.COM.', '20 ALT2.ASPMX.L.GOOGLE.COM.', '20 ASPMX2.GOOGLEMAIL.COM.', '30 ASPMX3.GOOGLEMAIL.COM.']", 
            "vpc_id": null, 
            "wait": false, 
            "wait_timeout": 300, 
            "weight": null, 
            "zone": "aquarionics.com"
        }, 
        "module_name": "route53"
    }, 
    "msg": "Invalid Resource Record: FATAL problem: MXRRDATAPriorityRequired (MX record doesn't have a priority field) encountered with ''10 ALT1.ASPMX.L.GOOGLE.COM.''"
}
	to retry, use: --limit @/home/aquarion/code/autopelago/ansible/playbook.retry
```

**Comment by ansibot** [comment]
cc @bpennypacker
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aquarion** [comment]
I've found a workaround, which is to use this instead:

```
- name: aquarionics.com. - MX
  route53:
      overwrite: true
      command: "create"
      zone: "aquarionics.com"
      record: "aquarionics.com."
      type: "MX"
      ttl: "300"
      value: "10 ASPMX.L.GOOGLE.COM.,10 ALT1.ASPMX.L.GOOGLE.COM.,20 ALT2.ASPMX.L.GOOGLE.COM.,20 ASPMX2.GOOGLEMAIL.COM.,30 ASPMX3.GOOGLEMAIL.COM."
```

But I'm not sure why it stopped collapsing the list properly, especially with that error message
