### ISSUE TITLE
to_nice_yaml filter not printing correctly

### ISSUE THREAD

**Issue by peterhorvath** [ansible/ansible#23470]
##### ISSUE TYPE
 - Feature request

##### COMPONENT NAME
to_nice_yaml filter

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS 64bit

##### SUMMARY
I want to print a yaml config into a file keeping the formatting
template:
```
{{ gitlab_docker_compose | to_nice_yaml(width=200) }}
```
variable:
```yaml
gitlab_docker_compose:
  git.blabla.com:
    image: gitlab/gitlab-ce
    ports:
      - 443:443
      - 222:22
      - 80:80
    hostname: git.blabla.com
    restart: always
    volumes:
      - /opt/git.blabla.com/mounts/var/opt/gitlab:/var/opt/gitlab
      - /opt/git.blabla.com/mounts/etc/gitlab:/etc/gitlab
      - /opt/git.blabla.com/mounts/var/log/gitlab:/var/log/gitlab
      - /var/run/docker.sock:/var/run/docker.sock
    command: bash -c "echo -e '#!/bin/sh\nexec svlogd -ttt /var/log/gitlab/sshd' > /opt/gitlab/sv/sshd/log/run && /assets/wrapper"
```

Output:
```yaml
git.blabla.com:
    command: bash -c "echo -e '#!/bin/sh\nexec svlogd -ttt /var/log/gitlab/sshd' > /opt/gitlab/sv/sshd/log/run && /assets/wrapper"
    hostname: git.blabla.com
    image: gitlab/gitlab-ce
    ports:
    - 443:443
    - 13342
    - 80:80
    restart: always
    volumes:
    - /opt/git.blabla.com/mounts/var/opt/gitlab:/var/opt/gitlab
    - /opt/git.blabla.com/mounts/etc/gitlab:/etc/gitlab
    - /opt/git.blabla.com/mounts/var/log/gitlab:/var/log/gitlab
    - /var/run/docker.sock:/var/run/docker.sock
```
if i keep the docker-compose formatting recommendation and enclose ports in ""
```yaml
ports:
    - "443:443"
    - "222:22"
    - "80:80"
```
output will be:
```yaml
ports:
    - 443:443
    - '222:22'
    - 80:80
```

##### STEPS TO REPRODUCE
define variable and use to_nice_yaml 
222:22 enclosed between "" or without

```yaml
- name: create docker-compose file
  template:
    dest: /opt/{{ gitlab_domain_name }}/docker-compose.yml
    src: gitlab_docker_compose.j2
    owner: root
    group: root
    mode: 644
```

##### EXPECTED RESULTS
```yaml
ports:
    - "443:443"
    - "222:22"
    - "80:80"
```
or

```yaml
ports:
    - 443:443
    - 222:22
    - 80:80
```
##### ACTUAL RESULTS

```

```

**Comment by fefe** [comment]
Something along the way interprets 222:22 as a time value and converts it to serial.
222 minutes and 22 seconds will give you 13342 seconds
222 * 60 + 22 = 13342
No idea about the reason, but this is what looks like to be happening.

**Comment by peterhorvath** [comment]
yeah tested and if  the number after : is between 00 and 59 it always converts it to time

**Comment by sivel** [comment]
Yes, what is happening is it is matching the regex for a timestamp value:

http://yaml.org/type/timestamp.html

FWIW, yamllint.com parses this the same way.

Quoting, or using `!!str 222:22` would be the ways to get it to not parse as a timestamp.

**Comment by peterhorvath** [comment]
output is still different compared to the other ports even if i add !!str
```yaml
ports:
      - !!str "443:443"
      - !!str "222:22"
      - !!str "80:80"

ports:
    - 443:443
    - '222:22'
    - 80:80
```
