### ISSUE TITLE
Network *_command modules need terminal width set to avoid seeing paged input in the expected output

### ISSUE THREAD

**Issue by jmighion** [ansible/ansible#23474]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`*_command` network command modules

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.1.0
  config file = /home/jmighion/git/blank-ansible-repo/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The terminal width on network devices isn't being set to avoid paging. If a command goes over the default amount the output from a `*_command` module will include the paged output of the command first, followed by the expected output.

The terminal length appears to be set already to avoid this.

##### STEPS TO REPRODUCE

```yaml
- name: dev
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: command
      iosxr_command:
        commands:
          - show terminal
          - show ipv4 vrf all interface brief | include {{ ansible_host }}
        provider: "{{ cli }}"
```

##### EXPECTED RESULTS

Not seeing the paging in the output.

##### ACTUAL RESULTS

```
    "stdout_lines": [
        [
            "",
            "Line \"vty0\", Location \"ip.ip.ip.ip\", Type \"VTY\"",
            "Length: 0 lines, Width: 80 columns",
            "Baud rate (TX/RX) is 0, \"Empty\" Parity, 0 stopbits, 0 databits",
            "Template: default",
            "Capabilities: Timestamp Disabled",
            "Allowed transports are ssh telnet."
        ],
        [
            "show ipv4 vrf all interface brief | include ip.ipbrief | include ip.ip                                 ip.ipshow ipv4 vrf all interface brief | include ip.i$",
            "",
            "Loopback0                      ip.ip.ip.ip   Up              Up       default "
        ]
    ],
```
