### ISSUE TITLE
mount with `opts: bind` fails to recognize mounted state

### ISSUE THREAD

**Issue by MasterofJOKers** [ansible/ansible#23487]
I've looked at the code of the mount core module and the problematic part looks the same as in my version.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
[`ansible.modules.core.system.mount`](https://github.com/ansible/ansible-modules-core/blob/devel/system/mount.py)

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT
Linux. especially Debian jessie trying to manage a Debian jessie.

##### SUMMARY
The mount module fails to recognize already mounted bind mounts in two situations:
1) if there are multiple bind mounts, as the code expands the path to the full path more than once and thus might find another bind mount earlier in the mountinfo list
2) if absolute paths are used, as the code does not handle two adjoining slashes correctly (e.g. when mounting `/mnt/bla` on `/` the code seems to create a `//mnt/bla` which cannot be found in the mountinfo) 

There's actually a test for this case [here](https://github.com/ansible/ansible/blob/324702c38fc67d601b94de6e6c4cc825dbdb4bdd/test/integration/targets/mount/tasks/main.yml), but that seems to use relative paths and uses only one bind mount.

##### STEPS TO REPRODUCE
Run the steps below multiple times. 

```yaml
- name: create directories, that can be mounted
  file:
    dest: "/srv/{{ item }}"
    state: directory
  with_items:
    - data
    - metadata

- name: create mount points
  file:
    dest: "/mnt/{{ item }}"
    state: directory
  with_items:
    - data
    - metadata

- name: mount it all
  mount:
    name: "/mnt/{{ item }}"
    src: "/srv/{{ item }}"
    opts: bind
    fstype: "none"
    state: mounted
  with_items:
    - data
    - metadata
```

##### EXPECTED RESULTS
The directories will only get mounted once.

##### ACTUAL RESULTS
The directories will get mounted every time.

##### WHAT WORKS FOR ME
This obviously doesn't handle relative paths, since it's only a quick fix to keep me working. It might still point anyone wanting to fix this in the right direction, so I included it here.
```diff
--- /usr/lib/python2.7/dist-packages/ansible/modules/core/system/mount.py	2017-04-11 10:58:39.378894537 +0200
+++ library/mount.py	2017-04-11 11:51:59.426882330 +0200
@@ -524,7 +524,8 @@
             for j, m in enumerate(mntinfo):
                 if j < i:
                     if m['src'] == mnt['src']:
-                        src = "%s%s" % (m['dst'], mnt['root'])
+                        src = "%s%s" % (m['dst'], mnt['root'][1:])
+                        break
                 else:
                     break
 
```
