### ISSUE TITLE
Using become_user and with_dict results in one being applied to the ansible login user

### ISSUE THREAD

**Issue by hylaride** [ansible/ansible#23499]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

with_dict/become_user
##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### OS / ENVIRONMENT

Ansible Host: MacOS Sierra 10.12.4

Ansible Target: ubuntu 16.04 LTS

##### SUMMARY

We're setting up user accounts in a playbook and it applies one of the `with_dict` tasks to the ubuntu user (the default account name for AWS when an instance is spun up) and not as the user in `item.key`.  In the below role, if the user has `oh_my_zsh: yes`, then it'll clone it into that user's home directory.  However, what's really happening is that it's cloning it for `user2` into the `ubuntu` user, but then for `user3` it does it properly in their home dir. 😢 

We have a few other custom setups (setting up homesick) that also clones into ubuntu for the first user it matches, but then the rest are applied properly.  It seems the first time get's applied to the ansible login user (ubuntu)
##### STEPS TO REPRODUCE
We're trying to apply this to all accounts in `accounts`

```yaml
- name: Setup Accounts' 'Oh my, zsh'
  git: repo={{ oh_my_zsh_repo }} dest=~/.oh-my-zsh version=master
  become: true
  become_user: "{{ item.key }}"
  with_dict: "{{ accounts }}"
  when: item.value.oh_my_zsh is defined and item.value.oh_my_zsh|bool
```

```yaml
accounts:
  user1:
    admin: yes
    fullname: user1
    hash: REMOVED
    public_key: common-files/public_keys/user1.pub
  user2:
    admin: yes
    fullname: user2
    shell: /bin/zsh
    oh_my_zsh: yes
    homeshick_dotfiles: https://github.com/user2/dotfiles
    hash: REMOVED
    public_key: common-files/public_keys/user2.pub
  user3:
    admin: yes
    fullname: user3
    shell: /bin/zsh
    oh_my_zsh: yes
    homeshick_dotfiles: https://github.com/user3/dotfiles
    hash: REMOVED
    public_key: common-files/public_keys/user3.pub
```

##### EXPECTED RESULTS

User2 and user3 should have oh-my-zsh cloned into their home directories
##### ACTUAL RESULTS

The ansible login user and user3 had oh-my-zsh cloned into their home directories

It shows as run properly, but user2 is being applied to the `ubuntu` user (which is the ansible login user).

```
   non-prod: TASK [contxt-base : Setup Accounts' 'Oh my, zsh'] **************************
    non-prod: skipping: [default] => (item={'key': 'user1', 'value': {'admin': True, 'fullname': 'user1', 'hash': 'removed', 'public_key': 'common-files/public_keys/user1.pub'}})
    non-prod: changed: [default] => (item={'key': 'user2', 'value': {'admin': True, 'fullname': 'user2', 'shell': '/bin/zsh', 'oh_my_zsh': True, 'homeshick_dotfiles': 'https://github.com/user2/dotfiles', 'hash': 'removed.', 'public_key': 'common-files/public_keys/user2.pub'}})
    non-prod: changed: [default] => (item={'key': 'user3', 'value': {'admin': True, 'fullname': 'user3', 'shell': '/bin/zsh', 'oh_my_zsh': True, 'homeshick_dotfiles': 'https://github.com/user3/dotfiles', 'hash': 'removed', 'public_key': 'common-files/public_keys/user3.pub'}})
```

**Comment by hylaride** [comment]
To further add, when my colleague runs the build, everything works as expected.  when I run the build, (the username on my mac is the same as the one error'ing out) that user skips and gets added to `ubuntu` instead.

**Comment by abadger** [comment]
I've tried to replicate your conditions as closely as possible but I'm afraid that just like your colleague, I cannot yet reproduce.  I've tried with both current devel and with a checkout of 2.2.1.0

My playbook:
```
---
- hosts: ub16
  vars:
    oh_my_zsh_repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    accounts:
      nobody:
        admin: yes
        fullname: Toshio
        hash: REMOVED
        public_key: common-files/public_keys/user2.pub
      badger:
        admin: yes
        fullname: Toshio
        shell: /bin/zsh
        oh_my_zsh: yes
        homeshick_dotfiles: https://github.com/user2/dotfiles
        hash: REMOVED
        public_key: common-files/public_keys/user2.pub
      root:
        admin: yes
        fullname: Toshio
        shell: /bin/zsh
        oh_my_zsh: yes
        homeshick_dotfiles: https://github.com/user2/dotfiles
        hash: REMOVED
        public_key: common-files/public_keys/user2.pub
  gather_facts: False
  tasks:
    - name: see things
      command: whoami
      become: True
      become_user: "{{ item.key }}"
      with_dict: "{{ accounts }}"

    - name: Setup Accounts' 'Oh my, zsh'
      git: repo={{ oh_my_zsh_repo }} dest=~/.test version=master
      become: true
      become_user: "{{ item.key }}"
      with_dict: "{{ accounts }}"
      when: item.value.oh_my_zsh is defined and item.value.oh_my_zsh|bool
```
My inventory:
```
ub16 ansible_host=ubuntu16-test ansible_user=toshiotest
```
How I'm running it:
```
ansible-playbook -i inven 23499.yml -K  -vv 
```

My local username is badger just like the second user in the accounts dict.

For me the first task is properly printing that whoami is each of the three become users, never the user toshiotest.  The git checkouts occur in /home/badger/.test and /root/.test, not in /home/toshiotest/.test

Do you have any other information to help us reproduce?  Perhaps more information about what differs between your colleague's machine and your own?

needs_info
