### ISSUE TITLE
ec2_group IPv6 rule fails with error CIDR is malformed

### ISSUE THREAD

**Issue by sramakr** [ansible/ansible#23507]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
Module ec2_group

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /vagrant/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 14.04

##### SUMMARY

I am trying to add security group rule in aws. I can successfully add ipv4 cidr , but , fails when it's ipv6.

I believe it's not yet supported , but wanted to confirm for sure. 

failed: [127.0.0.1] (item={u'direction': u'ingress', u'protocol': u'tcp', u'remote_ip_prefix': u'*:*:*::/40', u'port_range_max': u'*', u'port_range_min': u'*', u'ethertype': u'IPv4'}) => {
    "failed": true, 
    "invocation": {
        "module_name": "ec2_group"
    }, 
    "item": {
        "direction": "ingress", 
        "ethertype": "IPv6", 
        "port_range_max": "*", 
        "port_range_min": "*", 
        "protocol": "tcp", 
        "remote_ip_prefix": "*:*:*::/40"
    }, 
    
Error - CIDR block *:*:*::/40 is malformed

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by s-hertel** [comment]
Hi, thanks for opening an issue for this. ec2_group doesn't have a remote_ip_prefix option. Are you trying to use the [os_security_group_rule module](http://docs.ansible.com/ansible/os_security_group_rule_module.html)? Can you share your task, please?

**Comment by sramakr** [comment]
Here is the task.
```
# file: roles/ec2_security_group/tasks/main.yml
- name: add amazon ec2 credentials
  include_vars: ec2_credentials.vault
  no_log: true

- name: Create security group
  ec2_group:
    name: "{{ secgroup.name }}"
    description: "{{ secgroup.description }}"
    vpc_id: "{{ servers.vpc_id }}"
    region: "{{ region_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    rules:
      - proto: "{{ item.protocol }}"
        from_port: "{{ item.port_range_min }}"
        to_port: "{{ item.port_range_max }}"
        cidr_ip: "{{ item.remote_ip_prefix }}"
    purge_rules: false
  with_items: "{{ secgroup.rules }}"
  when: secgroup.rules is defined

- name: Programmatically create group rules
  ec2_group:
    name: "{{ secgroup.name }}"
    description: "{{ secgroup.description }}"
    vpc_id: "{{ servers.vpc_id }}"
    region: "{{ region_id }}"
    aws_secret_key: "{{ aws_secret_key }}"
    aws_access_key: "{{ aws_access_key }}"
    rules:
      - proto: "{{ secgroup.protocol }}"
        from_port: '{{ item[0].min }}'
        to_port: '{{ item[0].max }}'
        cidr_ip: '{{ item[1] }}'
  with_nested:
    - '{{ secgroup.incoming_ports }}'
    - '{{ secgroup.incoming_ips }}'
  when: secgroup.incoming_ports is defined
```
