### ISSUE TITLE
Support for more vmnic to the module vmware_vswitch

### ISSUE THREAD

**Issue by wernermarcel** [ansible/ansible#23522]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
module: vmware_vswitch

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']

```

##### OS / ENVIRONMENT

ANSIBLE: Oracle Enterprise Linux 7 
SYSTEM: ESXI5.5

##### SUMMARY
Adding a possibility that more vmnic can be added to the creation of a vswitch.

##### STEPS TO REPRODUCE

 

```yaml
  - name: Add a VMware vSwitch
      local_action:
        module: vmware_vswitch
        hostname: esxi_hostname
        username: esxi_username
        password: esxi_password
        switch_name: vswitch_name
        nic_name: "vmnic1","vmnic2"
        mtu: 9000

```

##### EXPECTED RESULTS
Possibility to add more vmnic's to create a vswitch. 

##### ACTUAL RESULTS

Only one nic is possible to add.
