### ISSUE TITLE
apt_repository consider only URL

### ISSUE THREAD

**Issue by mavimo** [ansible/ansible#2352]
### Description

In the module **apt_repository** only repository URL is considered to find repo in _source.list_ files
### How to reproduce:

```
tasks:
  - name: Add main repo
    apt_repository: repo="deb http://archive.canonical.com quantal main"
  - name: Add multiverse repo
    apt_repository: repo="deb http://archive.canonical.com quantal multiverse"
```
### Expected

We expect to have two different entry in _source.list_, first for **main** and second for **multiverse**
### Occured

Only on repo (main) is in _source.list_
### How to fix

After a first check the apt_pkg module for python do not manage this information, maybe need to be improved this library and next apt_repocitory module need to check for repo URL **AND** addictional items.
### Workaround

Using **lineinfile** to ensure repo in file.
