### ISSUE TITLE
Error running shell script locally using local_action module

### ISSUE THREAD

**Issue by mohtashims** [ansible/ansible#23543]
ISSUE TYPE

>         Bug Report

COMPONENT NAME

> local_action

ANSIBLE VERSION

>     ansible 2.1.0.0

mybank.com is my target host. 

I have ansible roles called "mgr"

I run the ansible roles using the below command.

`ansible-playbook -vvv site.yml -i /web/hostfiles/myhost.txt
`
I have pull.yml under tasks which has a shell script called renew.sh that needs to run locally and not on the target host. 

Contents of pull.yml are as below.
```

---

- name: ==== String Log Rotation Execution using ID 'user1' ====
  ping:

- name: ====Sync  to remote hosts at location= /tmp/dr/ using ID 'user1' ====
  command: "mkdir -p  {{ CERT_HOME }}dump"

- name: ====Sync from remote hosts at location= /tmp/certs/ using ID 'user1' ====

  synchronize: mode=pull src="{{ CERT_HOME }}" dest="{{ LOCAL_CERT_HOME }}keystore_dump/" rsync_opts="--include='*.sh', --exclude='*'"

- name: ==== Run script renew.sh on LOCAL hosts with ID 'user1' ====

  local_action: shell  "sh {{ ROLE_PATH }}mgr/files/renew.sh {{ DOMAIN_NAME }} chdir={{ ROLE_PATH }}mgr/files/"

```

Error during execution:
> 
> TASK [mgr : ==== Run script renew.sh on LOCAL host with ID 'user1' ====] ***
> task path: /tmp/roles/mgr/tasks/pull.yml:17
> <localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansusr
> <localhost> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'
> fatal: [mybank.com -> localhost]: FAILED! => {"changed": true, "cmd": "\"sh /tmp/roles/mgr/files/renew.sh mydom chdir=/tmp/roles/mgr/files/\"", "delta": "0:00:00.005222", "end": "2017-04-12 16:19:22.782488", "failed": true, "invocation": {"module_args": {"_raw_params": "\"sh /tmp/roles/mgr/files/renew.sh mydom chdir=/tmp/roles/mgr/files/\"", "_uses_shell": true, "chdir": null, "creates": null, "executable": null, "removes": null, "warn": true}, "module_name": "command"}, "rc": 127, "start": "2017-04-12 16:19:22.777266", "stderr": "/bin/sh: sh /tmp/roles/mgr/files/renew.sh mydom chdir=/tmp/roles/mgr/files/: No such file or directory", "stdout": "", "stdout_lines": [], "warnings": []}
>         to retry, use: --limit @site.retry
> 
> PLAY RECAP *********************************************************************
> mybank.com : ok=5    changed=1    unreachable=0    failed=1

Note that all the path to the folder and file does exist on the local ansible server. So i am not sure why is it complaining. 

Can you please suggest how can i get renew.sh to run locally and what is wrong with what i am doing above ?
