### ISSUE TITLE
Network *_command returned always

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible/ansible#23566]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

ios_command
asa_command
presumably others

##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ntc/ansible-modules/']
  python version = 2.7.6 (default, Oct 26 2016, 20:32:47) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

some {{ os }}_command docs indicate that stdout/stdout_lines should always be returned. They do not show when the configuration errors out. 

##### STEPS TO REPRODUCE

```yaml
  - name: "IOS SHOW COMMAND"
    ios_command:
      provider: "{{ ios_provider }}"
      commands: "{{ commands }}"
    ignore_errors: True
    register: "command_data"

  - name: debug
    debug:
      var: command_data
```

##### EXPECTED RESULTS

```
ok: [IOS-SW1] => {
    "changed": false,
    "command_data": {
        "stdout": ["", ""],
        "stdout_lines": ["", ""],
        "changed": false,
        "failed": true,
        "msg": "unable to open shell",
        "rc": 255
    }
}
```
##### ACTUAL RESULTS

```
ok: [IOS-SW1] => {
    "changed": false,
    "command_data": {
        "changed": false,
        "failed": true,
        "msg": "unable to open shell",
        "rc": 255
    }
}
```
