### ISSUE TITLE
Warning about Jinja2 delimiters in when statement not relevant?

### ISSUE THREAD

**Issue by flaf** [ansible/ansible#23578]
##### ISSUE TYPE

 - Bug Report (not sure)

##### COMPONENT NAME

It concerns the `when` statement.

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /root/poc-cl-ansible/etc-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Here is the playbook to reproduce the "problem":

```yaml
---
- name: Test
  hosts: all
  vars:
    var: '{{ foo | default(True) }}'
  tasks:
    - command: 'true'
      when: var
```

##### OS / ENVIRONMENT

```
~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

##### SUMMARY

In fact, I'm not sure if it's really an issue. But I have a warning with the playbook above which doesn't seems to me relevant, but maybe I'm wrong. In this case, I don't know how I can avoid this warning.

##### STEPS TO REPRODUCE

Here is the warning with the playbook above:

```
~# ansible-playbook -i 'localhost,' -c local test.yaml --extra-vars foo=False

PLAY [Test] **********************************************************************

TASK [Gathering Facts] ***********************************************************
ok: [localhost]

TASK [command] *******************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such
as {{ }} or {% %}. Found: {{ foo | default(True) }}

skipping: [localhost]

PLAY RECAP ***********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

I can confirm that I hadn't any warning with Ansible 2.2.2.

Regards.

**Comment by dieswaytoofast** [comment]
I worked around it by adding `== true` to the "when" statement.  e.g.
```
- debug: msg="This doesn't complain"
      when: bar == true
```

(more info in [22690](https://github.com/ansible/ansible/issues/22690)

**Comment by ghost** [comment]
@dieswaytoofast I am pretty not sure this is not the clue of the problem.
The bases of it lies in (#20312). I think it should check whether `conditional` is not a variable and this commit is not doing that, but I might be wrong.

**Comment by dieswaytoofast** [comment]
Oh you're right - i was, literally, responding to the "how to avoid the warning " part of the question :-)

**Comment by flaf** [comment]
Hi,

Thx @dieswaytoofast, indeed with `== True` I have no warning.

Should I close the issue? Or can we consider that is a (little) bug?

**Comment by ghost** [comment]
@flaf This is a bug. Do not close this issue. I will take care of it when I will have a little time.

**Comment by djmitche** [comment]
same as #22690

**Comment by kladiv** [comment]
+1 same issue

Playbook:
```
  tasks:

    - include_role:
        name: <rolename>
      vars:
        my_var: "{{ user_input|default(True) }}"
```

Role (main.yml)

```
- include: "tasks.yml"
  when: my_var
```

**Comment by kladiv** [comment]
+1 same issue

Playbook:
```
  tasks:

    - include_role:
        name: <rolename>
      vars:
        my_var: "{{ user_input|default(True) }}"
```

Role (main.yml)

```
- include: "tasks.yml"
  when: my_var
```
