### ISSUE TITLE
Memory load increased in 2.3.0 compared to 2.2.0.1 (high memory use, high ram use)

### ISSUE THREAD

**Issue by hyperized** [ansible/ansible#23579]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible

##### ANSIBLE VERSION
```
2.3.0
```

##### CONFIGURATION
```
[defaults]
hostfile       = inventory/
library        = /usr/share/ansible
remote_tmp     = $HOME/.ansible/tmp
pattern        = *
forks          = 30
poll_interval  = 15
sudo_user      = root
ask_sudo_pass  = True
transport      = ssh
remote_port    = 22
module_lang    = C
allow_world_readable_tmpfiles = True
gathering = implicit
host_key_checking = False
stdout_callback = actionable_debug
sudo_exe = sudo
sudo_flags = -i
timeout = 15
ansible_managed = This file is managed by Ansible.
action_plugins     = /usr/share/ansible_plugins/action_plugins
callback_plugins   = /usr/share/ansible_plugins/callback_plugins:./callback_plugins
connection_plugins = /usr/share/ansible_plugins/connection_plugins
lookup_plugins     = /usr/share/ansible_plugins/lookup_plugins
vars_plugins       = /usr/share/ansible_plugins/vars_plugins
filter_plugins     = /usr/share/ansible_plugins/filter_plugins
fact_caching = jsonfile
fact_caching_connection = /tmp/$USER
retry_files_enabled = False

[privilege_escalation]

[paramiko_connection]

[ssh_connection]
retries=10
pipelining = False

[accelerate]

[selinux]

[colors]
```

##### OS / ENVIRONMENT
Ubuntu 14.04.5 (exclusively) hosts & clients

##### SUMMARY
Increased memory usage when 2.3.0 is rolled out: http://imgur.com/a/ZgUCe

Recovery takes place when 2.2.0.1 is reverted.

##### STEPS TO REPRODUCE

- Install Ansible 2.3.0
- Run regular job schedule (6x a day a full run of ~100 roles, several irregular jobs like backups), started from the Rundeck job scheduler over regular SSH.

##### EXPECTED RESULTS
Similar memory usage.

##### ACTUAL RESULTS
http://imgur.com/a/ZgUCe

**Comment by jctanner** [comment]
@hyperized any idea how many tasks in total?

**Comment by alikins** [comment]
A few shot-in-the-dark questions...
Is ansible-vault used? How about 'async'? 

Any difference if ssh retries are disabled or lowered from current config of 10?  
``` ini
[ssh_connection]
retries=10
```

Any difference if json fact caching is disabled?  (If you have a way to test that...)

**Comment by alikins** [comment]
@hyperized  Would it be possible to get the output of 'lsof $THE_ANSIBLE_PLAYBOOK_PID' ?

Curious if the uuid fd leak described at https://github.com/irmen/Pyro4/issues/146 could be involved (that issue was also reported on ubuntu 14.04.5).

Looks like the tell-tale is a fd leak on '/var/lib/libuuid/clock.txt' so curious if that shows up in the lsof output.

**Comment by hyperized** [comment]
I placed one server back on 2.3.0 for today to obtain more data.

I will look for the following signals:

- `/var/lib/libuuid/clock.txt`
- `lsof` & `ps` of memory hogging processes
- Will lower the ssh_connection retries to see the effect.

**Comment by hyperized** [comment]
I used a different server, now with 60-some nodes (best thing I could find).

- Ruled out the `ssh_connection`, tried the default and setting it to `1` and both resulted in the same excessive memory usage.
- I `lsof`'ed the pid of the playbook (`site.yml` in this case), results below
- No occurance of the `/var/lib/libuuid/clock.txt` at all it seems.

```
stat /var/lib/libuuid/clock.txt
stat: cannot stat ‘/var/lib/libuuid/clock.txt’: No such file or directory
```
Also during runs.

The results of `lsof`: https://gist.github.com/hyperized/68b4bd95a5a7cdb8c3a7373d697dc144

**Comment by hyperized** [comment]
Found that `memstat -w` gives me a little more data than `lsof`: https://gist.github.com/hyperized/2fc903b69aa4a688e9d7d8186956eb8c

**Comment by hyperized** [comment]
I ran the setup without the `jsonfile` `fact_caching` and results are identical.

**Comment by merlin-tc** [comment]
We're facing the problem when upgrading to 2.3.
I could reproduce it by running a job we have on 20 hosts in parallel and the memory usage increased to 8GB+ RAM and the OOM killer starts to kill processes.

I could trace it back to the following task:
```
- name: Check if sda is grub boot device
  with_dict: "{{ ansible_devices }}"
  set_fact: boot_device="{{ 'sda' }}"
  tags: [kernel]
  when: "'sda' in item.key and boot_device is not defined"
  loop_control:
    label: "Checking {{item.key}}"
```
If I can be of any further assistance let me know.

**Comment by hyperized** [comment]
@merlin-tc nice to know we're not the only ones, I was starting to think it was just us.

Just a hunch here, if the `loop_control` `label` does not contain a dynamic variable, does it still have this issue? And could you tell me how you traced it back to that particular task so I can do the same?

**Comment by tersmitten** [comment]
Might be related to https://github.com/ansible/ansible/issues/15416

**Comment by lberruti** [comment]
Similar issue here: play with 20 hosts, the memory grows up at first task with loop_control.
The issue can be reproduced with this playbook:
```
---
- hosts: all
  vars:
    my_facts:
      - { src: a, dest: 1 }
      - { src: b, dest: 2 }
      - { src: c, dest: 3 }
      - { src: d, dest: 4 }
  tasks:
    - command: echo {{item.dest}}
      with_items: '{{my_facts}}'
      loop_control:
        label: '{{item.src}}'           # memory grows up also with 'label: "static text"'
```
