### ISSUE TITLE
run_once: true with delegate_to now getting skipped (2.3.0)

### ISSUE THREAD

**Issue by Codelica** [ansible/ansible#23594]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

run_once
delegate_to

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
##### CONFIGURATION

Nothing notable changed.

##### OS / ENVIRONMENT

N/A  (but using Ubuntu 16.0.4.2 for both)

##### SUMMARY

I recently updated Ansible to 2.3.0.0 and several tasks that use a run_once: true with delegate_to: 127.0.0.1 are now being skipped.  I've included an example below which used to run as long as at least one host was valid (not skipped).   Now the play is skipped regardless when run_once: true.

##### STEPS TO REPRODUCE

Including the task below with one skipped host and one valid host on Ansible 2.3.0.0 results in the task being skipped altogether for me.  Changing it to run_once: false allows it to process with first host being skipped and the other triggering it.  The issue seems similar to this old (closed) issue -- https://github.com/ansible/ansible/issues/9784

"As run_once will always target the first host in the list, if that host is supposed to skip a set of tasks (due to some condition, for instance), it will also skip any run_once tasks even though they may delegate_to other hosts which are willing to run that task."

```yaml
- name: Clone XXXXXXX locally for v{{ _current_version }}
  git:
    repo: 'git@somehost.somewhere.com:group/project.git'
    dest: '{{ _local_repobase }}/{{ _current_version }}'
    depth: 1
    update: yes
    version: 'v{{ _current_version }}'
  run_once: true
  delegate_to: 127.0.0.1
```

##### EXPECTED RESULTS

Task should run once on the local host

##### ACTUAL RESULTS

Task is skipped.

```

```

**Comment by sivel** [comment]
I cannot duplicate this.  A full output of your playbook run where it fails would be useful.

**Comment by Codelica** [comment]
Sorry I posted and ran on this one.  Should have waited until I was clear of a few things. :) 

Anyway, It's entirely possible I don't understand how a "run_once" w/ "delegate_to" **should** function, but this only popped up after my 2.3.0.0 update.  I'm assuming that as long as at least one host is valid (not skipped) that the task will run once and be delegated to the specified host.   Just looking at http://docs.ansible.com/ansible/playbooks_delegation.html#run-once

My actual playbook is quite large with lots of inclusions, so I've pared down a simple example.

With the following hosts file:

```
[test-hosts]
False-Host ansible_host=10.250.0.2 _myVar=false
True-Host ansible_host=10.250.0.3 _myVar=true
```

and the following playbook:

```yaml
- hosts: test-hosts

  tasks:

    - name: Clone iot-platform locally for v4.4.5
      git:
        repo: 'git@ourserver.domain.com:group/iot-platform.git'
        dest: '/etc/ansible/test/4.4.5'
        depth: 1
        update: yes
        version: 'v4.4.5'
      run_once: true
      delegate_to: 127.0.0.1
      when: _myVar
```

The task will be skipped and not cloned locally.  Output:

```
PLAY [test-hosts] *******************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************
ok: [False-Host]
ok: [True-Host]

TASK [Clone iot-platform locally for v4.4.5] ****************************************************************************
skipping: [False-Host]

PLAY RECAP **************************************************************************************************************
False-Host                 : ok=1    changed=0    unreachable=0    failed=0
True-Host                  : ok=1    changed=0    unreachable=0    failed=0
```

However, if I switch the order of the hosts so that a valid host is first, like this:

```
[test-hosts]
True-Host ansible_host=10.250.0.3 _myVar=true
False-Host ansible_host=10.250.0.2 _myVar=false
```

Then the task will execute:

```
PLAY [test-hosts] *******************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************
ok: [False-Host]
ok: [True-Host]

TASK [Clone iot-platform locally for v4.4.5] ****************************************************************************
changed: [True-Host -> 127.0.0.1]

PLAY RECAP **************************************************************************************************************
False-Host                 : ok=1    changed=0    unreachable=0    failed=0
True-Host                  : ok=2    changed=1    unreachable=0    failed=0
```
