### ISSUE TITLE
cloudformation module no longer works in 2.3.0

### ISSUE THREAD

**Issue by jagibson** [ansible/ansible#23593]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudformation.py

##### ANSIBLE VERSION
```
ansible --version
ansible 2.3.0.0
  config file = /home/jagibson/ansible/playbooks/myplaybook/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]
```

##### CONFIGURATION
ansible.cfg
```
[defaults]
roles_path = roles
remote_user = ubuntu
host_key_checking = false
retry_files_enabled = False
inventory = inventory
jinja2_extensions = jinja2.ext.do

[ssh_connection]
pipelining = True
retries = 5
```

##### OS / ENVIRONMENT
Ubuntu 16.10
ansible (2.3.0.0)
boto (2.46.1)
boto3 (1.4.4)
botocore (1.5.39)

##### SUMMARY
When running the cloudformation module in Ansible 2.3.0 the play fails with the error:

"botocore.exceptions.ClientError: An error occurred (InvalidAction) when calling the DescribeStacks operation: The action DescribeStacks is not valid for this web service."

When running Ansible 2.2.1 the module works as expected.

##### STEPS TO REPRODUCE

test.yml
```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  vars:
    eni_stack_name: dev-host1-us-east-1-a
    eni_tags: 
      Name: "dev_eni"
  tasks:
    - name: run cloudformation
      cloudformation:
        stack_name: "{{ eni_stack_name }}"
        template: "tmp/{{ eni_stack_name }}.yml"
        tags: "{{ eni_tags }}"
      register: eni_cf_outputs
```
tmp/dev-host1-us-east-1-a.yml
```yaml
---
AWSTemplateFormatVersion: 2010-09-09
Description: Creates an Amazon ENI, DNS Records, and associated security groups.
Resources:
  ENI:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: Elastic Network Interface
      GroupSet:
        - sg-01234567
        - Ref: ENISG
      SubnetId: "subnet-01234567"
      SourceDestCheck: "true"
      PrivateIpAddress: "10.20.30.40"
      Tags:
        - Key: "Name"
          Value: "dev_eni"
  ENISG:
    Type: "AWS::EC2::SecurityGroup"
    Properties: 
      GroupDescription: Primary security group
      SecurityGroupIngress:
        - CidrIp: "10.20.30.0/24"
          FromPort: "22"
          ToPort: "22"
          IpProtocol: "tcp"
      Tags:
        - Key: "Name"
          Value: "dev_eni"
      VpcId: "vpc-01234567"
  ForwardDNS:
    Type: "AWS::Route53::RecordSet"
    Properties: 
      HostedZoneName: "myinternal.zone."
      Name: "dev-host1-us-east-1-a.myinternal.zone."
      ResourceRecords:
        - Fn::GetAtt:
            - ENI
            - PrimaryPrivateIpAddress
      TTL: "300"
      Type: "A"
Outputs:
  EniIp:
    Description: Primary IP address of the ENI
    Value: 
      Fn::GetAtt:
        - ENI
        - PrimaryPrivateIpAddress
  EniId:
    Description: AWS ID for the ENI
    Value:
      Ref: ENI
  EniSg:
    Description: Primary security group ID for the ENI
    Value:
      Fn::GetAtt:
        - ENISG
        - GroupId
  EniDns:
    Description: DNS record for the ENI
    Value:
      Ref: ForwardDNS
```

##### EXPECTED RESULTS
Ansible runs successfully
(here's the 2.2.1 output)
```
ansible-playbook test.yml -vvvv
Using /home/jagibson/ansible/playbooks/myplaybook/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from/home/jagibson/ansible/playbooks/myplaybook/.virtualenv/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [localhost] ***************************************************************

TASK [run cloudformation] ******************************************************
task path: /home/jagibson/ansible/playbooks/myplaybook/test.yml:10
Using module file /home/jagibson/ansible/playbooks/myplaybook/.virtualenv/local/lib/python2.7/site-packages/ansible/modules/core/cloud/amazon/cloudformation.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jgibson
<127.0.0.1> EXEC /bin/sh -c '/home/jagibson/ansible/playbooks/myplaybook/.virtualenv/bin/python2 && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "events": [
        "StackEvent AWS::CloudFormation::Stack dev-host1-us-east-1-a CREATE_COMPLETE", 
        "StackEvent AWS::Route53::RecordSet ForwardDNS CREATE_COMPLETE", 
        "StackEvent AWS::Route53::RecordSet ForwardDNS CREATE_IN_PROGRESS", 
        "StackEvent AWS::Route53::RecordSet ForwardDNS CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::NetworkInterface ENI CREATE_COMPLETE", 
        "StackEvent AWS::EC2::NetworkInterface ENI CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::NetworkInterface ENI CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroup ENISG CREATE_COMPLETE", 
        "StackEvent AWS::EC2::SecurityGroup ENISG CREATE_IN_PROGRESS", 
        "StackEvent AWS::EC2::SecurityGroup ENISG CREATE_IN_PROGRESS", 
        "StackEvent AWS::CloudFormation::Stack dev-host1-us-east-1-a CREATE_IN_PROGRESS"
    ], 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "disable_rollback": false, 
            "ec2_url": null, 
            "notification_arns": null, 
            "profile": null, 
            "region": null, 
            "security_token": null, 
            "stack_name": "dev-host1-us-east-1-a", 
            "stack_policy": null, 
            "state": "present", 
            "tags": {
                "Name": "dev_eni"
            }, 
            "template": "tmp/dev-host1-us-east-1-a.yml", 
            "template_format": null, 
            "template_parameters": {}, 
            "template_url": null, 
            "validate_certs": true
        }, 
        "module_name": "cloudformation"
    }, 
    "output": "Stack CREATE complete", 
    "stack_outputs": {
        "EniDns": "dev-host1-us-east-1-a.myinternal.zone", 
        "EniId": "eni-01234567", 
        "EniIp": "10.20.30.40", 
        "EniSg": "sg-01234567"
    }, 
    "stack_resources": [
        {
            "last_updated_time": null, 
            "logical_resource_id": "ENI", 
            "physical_resource_id": "eni-01234567", 
            "resource_type": "AWS::EC2::NetworkInterface", 
            "status": "CREATE_COMPLETE", 
            "status_reason": null
        }, 
        {
            "last_updated_time": null, 
            "logical_resource_id": "ENISG", 
            "physical_resource_id": "sg-01234567", 
            "resource_type": "AWS::EC2::SecurityGroup", 
            "status": "CREATE_COMPLETE", 
            "status_reason": null
        }, 
        {
            "last_updated_time": null, 
            "logical_resource_id": "ForwardDNS", 
            "physical_resource_id": "dev-host1-us-east-1-a.myinternal.zone", 
            "resource_type": "AWS::Route53::RecordSet", 
            "status": "CREATE_COMPLETE", 
            "status_reason": null
        }
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
```
ansible-playbook test.yml -vvvv
Using /home/jagibson/ansible/playbooks/myplaybook/ansible.cfg as config file

Loading callback plugin default of type stdout, v2.0 from /home/jagibson/ansible/playbooks/myplaybook/.virtualenv/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test.yml *******************************************************************************************************************************************************
1 plays in test.yml

PLAY [localhost] *********************************************************************************************************************************************************
META: ran handlers

TASK [run cloudformation] ************************************************************************************************************************************************
task path: /home/jagibson/ansible/playbooks/myplaybook/test.yml:10
Using module file /home/jagibson/ansible/playbooks/myplaybook/.virtualenv/local/lib/python2.7/site-packages/ansible/modules/cloud/amazon/cloudformation.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jgibson
<127.0.0.1> EXEC /bin/sh -c '/home/jagibson/ansible/playbooks/myplaybook/.virtualenv/bin/python2 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_dpM0mB/ansible_module_cloudformation.py", line 508, in <module>
    main()
  File "/tmp/ansible_dpM0mB/ansible_module_cloudformation.py", line 452, in main
    stack_info = get_stack_facts(cfn, stack_params['StackName'])
  File "/tmp/ansible_dpM0mB/ansible_module_cloudformation.py", line 381, in get_stack_facts
    raise err
botocore.exceptions.ClientError: An error occurred (InvalidAction) when calling the DescribeStacks operation: The action DescribeStacks is not valid for this web service.

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_dpM0mB/ansible_module_cloudformation.py\", line 508, in <module>\n    main()\n  File \"/tmp/ansible_dpM0mB/ansible_module_cloudformation.py\", line 452, in main\n    stack_info = get_stack_facts(cfn, stack_params['StackName'])\n  File \"/tmp/ansible_dpM0mB/ansible_module_cloudformation.py\", line 381, in get_stack_facts\n    raise err\nbotocore.exceptions.ClientError: An error occurred (InvalidAction) when calling the DescribeStacks operation: The action DescribeStacks is not valid for this web service.\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

PLAY RECAP ***************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```
