### ISSUE TITLE
Playbook ansible with vagrant raises error because of task docker_service.

### ISSUE THREAD

**Issue by JorisLA** [ansible/ansible#23607]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Task docker_service
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

Running Ansible from ubuntu 16.04 LTS.
Managing Ansible from a VM (debian 8 jessie)
##### SUMMARY

Using docker_service to do a 'docker-compose up'. At the end a FAILED message appears but the containers runs properly in the VM.
##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  become: yes
    - docker_service:
        project_src: /vagrant
        state: present
```
This is a part of my Vagrantfile
```   
 config.vm.box = "debian/jessie64"

 config.vm.network "forwarded_port", guest: 8080, host: 8080

 config.vm.provision "ansible" do |ansible|
      ansible.groups = {
        'localhost' => ['default']
      }
      ansible.playbook = "bootstrap.yml"
 end
```
This is my docker-compose.yml

```yaml
version: '2'

services:
  backend:
    build:
      context: backend/
      args:
        TAIGA_SECRET_KEY: ${TAIGA_SECRET_KEY}
        TAIGA_HOSTNAME: ${TAIGA_HOSTNAME}
        # To use an external SMTP for emails, fill in these values:
        TAIGA_ENABLE_EMAIL: ${TAIGA_ENABLE_EMAIL}
        TAIGA_EMAIL_FROM: ${TAIGA_EMAIL_FROM}
        TAIGA_EMAIL_USE_TLS: ${TAIGA_EMAIL_USE_TLS}
        TAIGA_EMAIL_HOST: ${TAIGA_EMAIL_HOST}
        TAIGA_EMAIL_PORT: ${TAIGA_EMAIL_PORT}
        TAIGA_EMAIL_USER: ${TAIGA_EMAIL_USER}
        TAIGA_EMAIL_PASS: ${TAIGA_EMAIL_PASS}
        RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
        RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    volumes:
      - ./media:/usr/src/taiga-back/media
    environment:
      # Database settings
      # To use an external database, simply update these and remove the postgres
      # service from this docker-compose.yml file
      TAIGA_DB_NAME: ${TAIGA_DB_NAME}
      TAIGA_DB_HOST: ${TAIGA_DB_HOST}
      TAIGA_DB_USER: ${TAIGA_DB_USER}
      TAIGA_DB_PASSWORD: ${TAIGA_DB_PASSWORD}
      TAIGA_SLEEP: 15 # when the db comes up from docker, it is usually too quick
      RABBIT_PORT: 5672
      REDIS_PORT: 6379

  frontend:
    build: frontend/
    ports:
      - "80:80"
    environment:
      # Your hostname (REQUIRED)
      TAIGA_HOSTNAME: ${TAIGA_HOSTNAME}
    depends_on:
      - backend

  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbitmq
    command: rabbitmq-server
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      # https://www.rabbitmq.com/clustering.html#erlang-cookie
      #- RABBITMQ_ERLANG_COOKIE='secret_cookie_here'
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
      # http://www.rabbitmq.com/configure.html#config-items
      # - RABBITMQ_HIPE_COMPILE=1

  redis:
    image: redis:latest
    command: redis-server
    ports:
      - '6379:6379'

  events:
    hostname: events
    build: events/
    environment:
      TAIGA_SECRET_KEY: ${TAIGA_SECRET_KEY}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}
    command: ['coffee','index.coffee']

```

##### EXPECTED RESULTS

```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [docker_service] **************************************************
ok: [default]
```
##### ACTUAL RESULTS

```
TASK [docker_service] **********************************************************
fatal: [default]: FAILED! => {
"changed": false, "failed": true,
"module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
"module_stdout": "Traceback (most recent call last):\r\n
File \"/tmp/ansible_yvaFKx/ansible_module_docker_service.py\", line 1016,
in <module>\r\n    main()\r\n  File \"/tmp/ansible_yvaFKx/ansible_module_docker_service.py\",
line 1011, in main\r\n
result = ContainerManager(client).exec_module()\r\n
File \"/tmp/ansible_yvaFKx/ansible_module_docker_service.py\",
line 608, in exec_module\r\n    result = self.cmd_up()\r\n
File \"/tmp/ansible_yvaFKx/ansible_module_docker_service.py\",
line 703, in cmd_up\r\n    get_stdout(fd_name)\r\n
File \"/tmp/ansible_yvaFKx/ansible_module_docker_service.py\",
line 512, in get_stdout\r\n    new_line = re.sub(r'\\x1b\\[.+m', '',
line.encode('ascii'))\r\n
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0:
 ordinal not in range(128)\r\n",
 "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by snowsky** [comment]
What is the output on your terminal, echo $LANG?

**Comment by surudoiryu** [comment]
Got the same error also with docker_service in my project:

**Ansible task:**
```
- name: Run Docker-Compose from project
  docker_service:
    build: yes
    project_name: project
    project_src: /var/www
```

**Docker-compose:**
```
version: '3'
services:
  web:
    build:
      context: .
      dockerfile: web.docker
    volumes:
      - .:/var/www
    ports:
      - 80:80
    links:
      - app
  app:
    build:
      context: .
      dockerfile: app.docker
    volumes:
      - .:/var/www
    links:
      - db
      - cache
    environment:
      - DB_PORT=3306
      - DB_HOST=db
      - REDIS_PORT=6379
      - REDIS_HOST=cache
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=project
    ports:
      - 3306:3306
  cache:
    image: redis:latest
    ports:
      - 6379:6379
```

**Error:**
```
Traceback (most recent call last):\r\n  
File \"/tmp/ansible_p8pdzrpz/ansible_module_docker_service.py\", line 1016, in <module>\r\n    
main()\r\n  
File \"/tmp/ansible_p8pdzrpz/ansible_module_docker_service.py\", line 1011, in main\r\n    
result = ContainerManager(client).exec_module()\r\n  
File \"/tmp/ansible_p8pdzrpz/ansible_module_docker_service.py\", line 608, in exec_module\r\n    
result = self.cmd_up()\r\n  
File \"/tmp/ansible_p8pdzrpz/ansible_module_docker_service.py\", line 703, in cmd_up\r\n 
get_stdout(fd_name)\r\n  
File \"/tmp/ansible_p8pdzrpz/ansible_module_docker_service.py\", line 512, in get_stdout\r\n    
new_line = re.sub(r'\\x1b\\[.+m', '', line.encode('ascii'))\r\n  
File \"/usr/lib/python3.5/re.py\", line 182, in sub\r\n    
return _compile(pattern, flags).sub(repl, string, count)\r\n
TypeError: cannot use a string pattern on a bytes-like object\r\n
", "msg": "MODULE FAILURE", "rc": 0}
```
