### ISSUE TITLE
debug module does not trigger notify

### ISSUE THREAD

**Issue by sirkubax** [ansible/ansible#23606]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

debug
haproxy

##### ANSIBLE VERSION

```
ansible 2.2.1.0

```

##### SUMMARY

The debug module does not trigger notify

##### STEPS TO REPRODUCE

Haproxy module does not have a 'force enable' option build in. Since my enable task is a handler, that should trigger only if there was UP->DOWN change (notify on change) - there is a risk of having haproxy backend in MAINT mode in the scenarios:
- you run a playbook that fails 
- you stop the playbook
then the MAINT is left, and next time you successfully run a playbook, the backend would not be enabled.

'Easy fix' - trigger notification - somehow it does not work with the debug module...

```yaml
- haproxy:
    state: disabled
    host: '{{ inventory_hostname }}'
    socket: /etc/haproxy/haproxysock
    backend: "{{ so1_generic.proxy_backend }}"
  notify:
    - "enable_haproxy"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['service-proxy'] }}"
  when: "so1_generic.proxy_backend is defined and so1_generic.proxy_backend not in 'backend_not_defined'"

- debug: msg="Force enable haproxy"
  when: haproxy_force_enable_backend |default(True)
  changed_when: True
  notify:
    - "enable_haproxy"


HANDLER:
- name: "enable_haproxy"
  haproxy:
    state: enabled
    host: '{{ inventory_hostname }}'
    socket: /etc/haproxy/haproxysock
    backend: "{{ so1_generic.proxy_backend |default('backend_not_defined') }}"
  delegate_to: "{{ item }}"
  with_items: "{{ groups['service-proxy'] }}"

```

##### EXPECTED RESULTS

debug + changed_when=True should trigger notify

It seems that it was working in 1.9.x 
https://serverfault.com/questions/617548/always-trigger-handler-execution-in-ansible

##### ACTUAL RESULTS

```
TASK [app_brand_image : debug] *************************************************
ok: [stg-front102] => {
    "msg": "Force enable haproxy"
}

no notification triggered (-vvv verbosity)
```

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
Attempted to reproduce with:

``` yaml
---
- name: The first Play
  hosts: localhost
  gather_facts: false
  vars:
      haproxy_force_enable_backend: true
      # some_undefined_var
  handlers:
    - name: enable_haproxy
      debug:
        msg: handler for enable_haproxy
        #when: haproxy_force_enable_backend |default(True)
        #changed_when: True

  tasks:
    - name: debug just to trigger a handler
      debug:
        msg: "Force enable haproxy"
      changed_when: true
      when: haproxy_force_enable_backend |default(true)
      notify:
        - enable_haproxy

```

I see the handlers triggered with 2.1, 2.2, 2.3, and devel

2.2.1
```
[fedora-25:ansible (v2.2.1.0-1-branch %)]$ ansible --version
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[fedora-25:ansible (v2.2.1.0-1-branch %)]$ ansible-playbook -vvv handler_ping.yml 
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: handler_ping.yml *****************************************************
1 plays in handler_ping.yml

PLAY [The first Play] **********************************************************

TASK [debug just to trigger a handler] *****************************************
task path: /home/adrian/src/ansible/handler_ping.yml:16
NOTIFIED HANDLER enable_haproxy
ok: [localhost] => {
    "msg": "Force enable haproxy"
}

RUNNING HANDLER [enable_haproxy] ***********************************************
ok: [localhost] => {
    "msg": "handler for enable_haproxy"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

```

2.2.3:
```
[fedora-25:ansible (stable-2.2 % u=)]$ ansible --version
ansible 2.2.3.0 (stable-2.2 7cc351a237) last updated 2017/04/17 13:08:40 (GMT -400)
  lib/ansible/modules/core: (detached HEAD cfe3c844f4) last updated 2017/04/17 13:10:28 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 8b78d56a08) last updated 2017/04/17 13:10:28 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[fedora-25:ansible (stable-2.2 % u=)]$ ansible-playbook -vvv handler_ping.yml 
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: handler_ping.yml *****************************************************
1 plays in handler_ping.yml

PLAY [The first Play] **********************************************************

TASK [debug just to trigger a handler] *****************************************
task path: /home/adrian/src/ansible/handler_ping.yml:16
NOTIFIED HANDLER enable_haproxy
ok: [localhost] => {
    "msg": "Force enable haproxy"
}

RUNNING HANDLER [enable_haproxy] ***********************************************
ok: [localhost] => {
    "msg": "handler for enable_haproxy"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```


2.1:
```
[fedora-25:ansible (stable-2.1 % u-1)]$ ansible --version
ansible 2.1.5.0 (detached HEAD ref: refs/) last updated 2017/04/17 13:04:51 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 649627f64d) last updated 2017/04/17 13:04:55 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD f73e29fb5c) last updated 2017/04/17 13:04:55 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

[fedora-25:ansible (stable-2.1 % u-1)]$ ansible-playbook -vvv handler_ping.yml 
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: handler_ping.yml *****************************************************
1 plays in handler_ping.yml

PLAY [The first Play] **********************************************************

TASK [debug just to trigger a handler] *****************************************
task path: /home/adrian/src/ansible/handler_ping.yml:16
NOTIFIED HANDLER enable_haproxy
ok: [localhost] => {
    "msg": "Force enable haproxy"
}

RUNNING HANDLER [enable_haproxy] ***********************************************
ok: [localhost] => {
    "msg": "handler for enable_haproxy"
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

```
