### ISSUE TITLE
force_handlers: true should fire the handler despite the task failing

### ISSUE THREAD

**Issue by ExplorerOnTheMoon** [ansible/ansible#23617]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
``force_handlers``

##### ANSIBLE VERSION

```
ansible-playbook 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

centos

##### SUMMARY

handlers do not fire when a task fails despite ``force_handlers: true``

##### STEPS TO REPRODUCE

- Play file is ``main_play.yaml``

```yaml
--
- name: any errors fatal demo with flush handlers
  hosts: failtest
  gather_facts: false
  max_fail_percentage: 0
  # serial: 10
  # flush on fatal condition
  force_handlers: true

  tasks:
    - name: a fake change
      debug:
        msg: "some change"
      notify: critical handler
      changed_when: true
      when: inventory_hostname == play_hosts[-2]
      failed_when: true

    - name: never ran
      debug:
        msg: "i should never run"
      when: inventory_hostname == play_hosts[-1]

  handlers:
    - name: critical handler
      debug:
        msg: "executed a critical task"
...
```

- Inventory file is ``hosts.ini``

```ini
[failtest]
failer[01:10]
```

```bash
# shows the issue; handler will never be fired
# see actual results below
ansible-playbook -i hosts.ini main_play.yaml  -vv
```

*Now change the ``failed_when`` clause to ``false``

```yaml
---
- name: any errors fatal demo with flush handlers
  hosts: failtest
  gather_facts: false
  max_fail_percentage: 0
  # serial: 10
  # flush on fatal condition
  force_handlers: true

  tasks:
    - name: a fake change
      debug:
        msg: "some change"
      notify: critical handler
      changed_when: true
      when: inventory_hostname == play_hosts[-2]
      # failed_when: inventory_hostname == play_hosts[-2]
      failed_when: false

    - name: never ran
      debug:
        msg: "i should never run"
      when: inventory_hostname == play_hosts[-1]

  handlers:
    - name: critical handler
      debug:
        msg: "executed a critical task"
...
```

```bash
# handler will now be fired
ansible-playbook -i hosts.ini main_play.yaml  -vv
```

##### EXPECTED RESULTS

``force_handlers: true`` should fire the handler despite the task failing

##### ACTUAL RESULTS

Handlers were never fired

```
ansible-playbook -i hosts.ini main_play.yaml  -vv --force-handlers
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: main_play.yaml *******************************************************
1 plays in main_play.yaml

PLAY [any errors fatal demo with flush handlers] *******************************

TASK [a fake change] ***********************************************************
task path: /home/deploy/downloads/003_forcing_handlers/main_play.yaml:11
skipping: [failer01] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [failer04] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [failer06] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [failer05] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [failer03] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [failer02] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [failer07] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [failer10] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
skipping: [failer08] => {"changed": false, "skip_reason": "Conditional check failed", "skipped": true}
fatal: [failer09]: FAILED! => {
    "changed": true,
    "failed": true,
    "failed_when_result": true,
    "msg": "some change"
}

NO MORE HOSTS LEFT *************************************************************

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/home/deploy/downloads/003_forcing_handlers/main_play.retry

PLAY RECAP *********************************************************************
failer01                   : ok=0    changed=0    unreachable=0    failed=0
failer02                   : ok=0    changed=0    unreachable=0    failed=0
failer03                   : ok=0    changed=0    unreachable=0    failed=0
failer04                   : ok=0    changed=0    unreachable=0    failed=0
failer05                   : ok=0    changed=0    unreachable=0    failed=0
failer06                   : ok=0    changed=0    unreachable=0    failed=0
failer07                   : ok=0    changed=0    unreachable=0    failed=0
failer08                   : ok=0    changed=0    unreachable=0    failed=0
failer09                   : ok=0    changed=0    unreachable=0    failed=1
failer10                   : ok=0    changed=0    unreachable=0    failed=0
```
