### ISSUE TITLE
set_fact bug. template parser works fine only with first element of array

### ISSUE THREAD

**Issue by gudron** [ansible/ansible#23624]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
set_fact

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 14.04

##### STEPS TO REPRODUCE
just run paybook

```yaml
---
- name: test set_fact bug
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - dig_list:
      - one

    - digits:
      - two
      - three
      - four
  tasks:

    - name: test bug
      set_fact:
        dig_list: "{{ dig_list + [ '{{digit}}' ] }}"
      with_items: "{{ digits }}"
      loop_control:
        loop_var: digit

    - debug: msg="{{ dig_list }}"
```
##### EXPECTED RESULTS
```
ansible-playbook test.yml     

PLAY [test set_fact bug] *******************************************************

TASK [test bug] ****************************************************************
ok: [localhost] => (item=two)
ok: [localhost] => (item=three)
ok: [localhost] => (item=four)

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": [
        "one", 
        "two", 
        "three", 
        "four"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0 
```

##### ACTUAL RESULTS
```
ansible-playbook -vvv test.yml
No config file found; using defaults

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [test set_fact bug] *******************************************************

TASK [test bug] ****************************************************************
task path: /home/development/projects/test.yml:16
ok: [localhost] => (item=two) => {
    "ansible_facts": {
        "dig_list": [
            "one", 
            "{{digit}}"
        ]
    }, 
    "changed": false, 
    "digit": "two", 
    "invocation": {
        "module_args": {
            "dig_list": [
                "one", 
                "{{digit}}"
            ]
        }, 
        "module_name": "set_fact"
    }
}
ok: [localhost] => (item=three) => {
    "ansible_facts": {
        "dig_list": [
            "one", 
            "three", 
            "{{digit}}"
        ]
    }, 
    "changed": false, 
    "digit": "three", 
    "invocation": {
        "module_args": {
            "dig_list": [
                "one", 
                "three", 
                "{{digit}}"
            ]
        }, 
        "module_name": "set_fact"
    }
}
ok: [localhost] => (item=four) => {
    "ansible_facts": {
        "dig_list": [
            "one", 
            "three", 
            "{{digit}}", 
            "{{digit}}"
        ]
    }, 
    "changed": false, 
    "digit": "four", 
    "invocation": {
        "module_args": {
            "dig_list": [
                "one", 
                "three", 
                "{{digit}}", 
                "{{digit}}"
            ]
        }, 
        "module_name": "set_fact"
    }
}

TASK [debug] *******************************************************************
task path: /home/development/projects/test.yml:23
ok: [localhost] => {
    "msg": [
        "one", 
        "three", 
        "{{digit}}", 
        "{{digit}}"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by snowsky** [comment]
reproduced and my outputs are:
```
root@ubuntu-xenial:~/ansible# bin/ansible-playbook --version
ansible-playbook 2.4.0 (devel c2370f14dd) last updated 2017/04/14 21:52:22 (GMT +000)
  config file =
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/ansible/lib/ansible
  executable location = bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
```
TASK [test bug] *****************************************************************************************************************************
task path: /home/ubuntu/ansible/23624.yml:16
ok: [localhost] => (item=two) => {
    "ansible_facts": {
        "dig_list": [
            "one",
            "{{digit}}"
        ]
    },
    "changed": false,
    "digit": "two"
}
ok: [localhost] => (item=three) => {
    "ansible_facts": {
        "dig_list": [
            "one",
            "three",
            "{{digit}}"


        ]
    },
    "changed": false,
    "digit": "three"
}
ok: [localhost] => (item=four) => {
    "ansible_facts": {
        "dig_list": [
            "one",
            "three",
            "{#digit#}",
            "{{digit}}"
        ]
    },
    "changed": false,
    "digit": "four"
}

TASK [debug] ********************************************************************************************************************************
task path: /home/ubuntu/ansible/23624.yml:23
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: [u'one', u'three', u'{#digit#}', u'{{digit}}']: 'digit' is undefined\n\nThe error appears to have been in '/home/ubuntu/ansible/23624.yml': line 23, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug: msg=\"{{ dig_list }}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"
}
```

**Comment by snowsky** [comment]
Does set_facts support loop_control?

**Comment by gudron** [comment]
``` yml
---
- name: test set_fact bug
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - dig_list:
      - one

    - digits:
      - two
      - three
      - four
  tasks:

    - name: test bug
      set_fact:
        dig_list: "{{ dig_list + [ digit ] }}"
      with_items: "{{ digits }}"
      loop_control:
        loop_var: digit

    - debug: msg="{{ dig_list }}"
```
works fine without {{ }} 

```
PLAY [test set_fact bug] *******************************************************

TASK [test bug] ****************************************************************
ok: [localhost] => (item=two)
ok: [localhost] => (item=three)
ok: [localhost] => (item=four)

TASK [debug] *******************************************************************
ok: [localhost] => {
    "msg": [
        "one", 
        "two", 
        "three", 
        "four"
    ]
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0  
```
