### ISSUE TITLE
openssl_csr module Indentation Error

### ISSUE THREAD

**Issue by isador999** [ansible/ansible#23628]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openssl_csr module. 

##### ANSIBLE VERSION
Ansible 2.3.0.0
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
Default configuration. 

##### OS / ENVIRONMENT
Linux Mint - 17.3  /   Ubuntu 14.04. 

##### SUMMARY
openssl_csr module returns Indentation Error

##### STEPS TO REPRODUCE
After copied manually "openssl_csr.py"  (from ansible github)  in  "/usr/lib/python2.7/dist-packages/ansible/modules/crypto/" ,  I launch the follwing tasks : 

```
- name: Create /opt/letsencrypt/ directory
  file: path=/opt/letsencrypt/ state=directory owner=root group=root mode=0750

- name: Create openssl account key
  openssl_privatekey: path=/opt/letsencrypt/account.key size=4096 type=RSA

- name: Create Openssl domain key
  openssl_privatekey: path=/opt/letsencrypt/domain.key size=4096 type=RSA

- name: Generate CSR for test
  openssl_csr:
    path: /opt/letsencrypt/test.csr
    privatekey_path: /opt/letsencrypt/domain.key
    commonName: "myhost"
    countryName: FR
    stateOrProvinceName: France
    localityName: Rennes
    organizationName: OrgaName
    organizationUnitName: OrgaUnitName

```

The result is the following : 
```
TASK [Generate CSR for test] *****************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndentationError: expected an indented block
fatal: [192.168.122.X]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

I tried to do the same thing manually : 
```
openssl req -new -sha256 -key /opt/letsencrypt/domain.key  > /opt/letsencrypt/test.csr
```

and it's working.
