### ISSUE TITLE
group_names not assigned properly with ranged defined inventory files.

### ISSUE THREAD

**Issue by rubbsdecvik** [ansible/ansible#2364]
When the inventory file is defined with ranged definitions, playbook/templates using the group_names variable will not contain all groups the host is a part of.

For example, an inventory file like this:

``` ini
[gluster]
ak[001:004]

[centos63]
ak[001:010]

[mysql]
ak[009:010]

[cloud]
ak[001:010]
```

Along with a playbook like this:

``` yaml
- hosts: gluster
  user: root
  tasks:
    - name: test this shit out
      action: template src=/etc/ansible/templates/temp.j2 dest=/tmp/temp.txt
```

And a template like this:

``` django
This is the beginning

{% if 'gluster' in group_names %}
In Gluster!
{% endif %}

this is the ending
```

Will produce output that looks like this:

```
This is the beginning


this is the ending
```

When the ranged definitions are replaced with explicit definitions, the template works as expected.
