### ISSUE TITLE
win_updates: Log is not output.

### ISSUE THREAD

**Issue by aabbss757** [ansible/ansible#23653]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### OS / ENVIRONMENT

Ansible Server：Amazon Linux AMI release 2017.03
Client：Windows Server 2012 R2

##### SUMMARY

I tried windows update from ansible.
However, log file specified by "log_path" is not output.

##### STEPS TO REPRODUCE

```yaml
---
- name: Sample Playbook
  hosts: windows
  tasks:
    - name: Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        log_path: 'C:\ansible_win_update.log'
      register: check_winupdate_result

    - name: Reboot
      win_reboot:
        reboot_timeout_sec: 1800
      when: check_winupdate_result.reboot_required
```

##### EXPECTED RESULTS

I want to output execution log of win_updates.

##### ACTUAL RESULTS

```
[root@<Address> ~]# ansible-playbook /etc/ansible/playbook/main.yml

PLAY [Sample Playbook] ********************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************
ok: [<Address>]

TASK [Windows Updates] ********************************************************************************************************************************************************************
changed: [<Address>]

TASK [Reboot] *****************************************************************************************************************************************************************************
changed: [<Address>]

PLAY RECAP ********************************************************************************************************************************************************************************
<Address>                : ok=3    changed=2    unreachable=0    failed=0
```
