### ISSUE TITLE
vmware_guest fails when VM already exists

### ISSUE THREAD

**Issue by arshantz** [ansible/ansible#23663]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

[defaults]
pipelining = True
#remote_tmp = /opt/appdata/ansible
host_key_checking = False
timeout = 20

##### OS / ENVIRONMENT

RHEL6

##### SUMMARY

vmware_guest fails (is not idempotent) when the VM already exists.

##### STEPS TO REPRODUCE

Execute play below to create the VM.  Then execute it again & it will fail because the VM already exists.

```yaml
- name: Clone template and customize
  vmware_guest:
    hostname: "xxx"
    username: xxx
    password: "{{vspherePass}}"
    validate_certs: no
    datacenter: xxx
    name: "{{item}}"
    template: "lab-template-rhel6"
    esxi_hostname: "xxx"
    wait_for_ip_address: yes
    folder: lab
    hardware:
      memory_mb: 36000
      num_cpus: 8
  with_items:
    - "labsystem022"
  register: output
```

##### EXPECTED RESULTS

If the VM already exists, I expected the task to detect it exists, and say "no changes," and continue to the next task.
##### ACTUAL RESULTS

It succeeds the first time, and fails the second time because the VM was created from the first execution.

```
failed: [172.24.227.46] (item=labsystem022) => {
    "changed": true, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "datacenter": "xxx", 
            "disk": null, 
            "esxi_hostname": "xxx", 
            "folder": "lab", 
            "force": false, 
            "hardware": {
                "memory_mb": 36000, 
                "num_cpus": 8
            }, 
            "hostname": "xxx", 
            "name": "labsystem022", 
            "name_match": "first", 
            "nic": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "template": "lab-template-rhel6", 
            "template_src": "lab-template-rhel6", 
            "username": "xxx", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }, 
        "module_name": "vmware_guest"
    }, 
    "item": "labsystem022", 
    "msg": "The name 'labsystem022' already exists."
}

```

**Comment by ansibot** [comment]
cc @jctanner @nerzhul @dav1x
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nerzhul** [comment]
vmware_guest has received many and many changes in 2.3, please re-test in 2.3, 2.2 version is very far from 2.3

**Comment by dagwieers** [comment]
Yup, this is definitely fixed in v2.3 and later.

bug_resolved

**Comment by FleischKarussel** [comment]
I still have the problem in v2.4, shall I create a new issue?

**Comment by TomaszKlosinski** [comment]
I confirm that the problem exists in v2.4.

**Comment by wvcardoso** [comment]
I've the same problem with the version 2.4. Follow the mensage: ... "The name '<vm_name>' already exists." With the version 2.3, the same code works.

**Comment by ArcticPheenix** [comment]
I can confirm that the issue exists in v2.4 when using a template.

**Comment by bendews** [comment]
Can also confirm this issue exists in 2.4

**Comment by wvcardoso** [comment]
@ArcticPheenix @bendews 
Look my comment in #28250

**Comment by ArcticPheenix** [comment]
Thanks @williancardoso. This solved the issue for me.

**Comment by bendews** [comment]
@williancardoso, unfortunately I'm having this issue when not using the folder directive, at the moment I'm just trying with a resource pool

**Comment by bendews** [comment]
@williancardoso Apologies I didn't read the comment threads closely enough. 

In my situation (resource pool in root of datacenter), I was able to follow your advice, this is working under Ansible2.4:
```yaml
- name: Create VM from template
  vmware_guest:
    datacenter: "{{ datacenter }}"
    name: "{{ vm_name }}"
    template: "server-template"
    resource_pool: "MyResourcePool"
    folder: "{{ datacenter }}/vm"
    wait_for_ip_address: True
    state: present
```
