### ISSUE TITLE
Folder named '$HOME' created when Ansible invoked by cloud-init

### ISSUE THREAD

**Issue by greggilbert** [ansible/ansible#23665]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Core

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
# ansible.cfg
[defaults]
log_path = /var/log/ansible.log
host_key_checking = False
```

##### OS / ENVIRONMENT
```
Python 2.7.12
```

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```

##### SUMMARY

When invoking a playbook from cloud-init, a folder named `$HOME` gets created.

##### STEPS TO REPRODUCE

This is my cloud-init:
```
#!/bin/bash
source /etc/environment
doit() {
  aws s3 cp s3://dev.tar.gz /tmp/s3-push.tar.gz
  mkdir -p /app/deploy
  tar -C /app/deploy -zxvf /tmp/s3-push.tar.gz
  cd /app/deploy
  ansible-playbook -i "localhost," -c local -e "first_run=true" master.yml
}
doit
```

```
# master.yml
  - hosts: all
    remote_user: ubuntu
    become: yes
    become_user: root

    tasks:

      - name: Start splash.service
        systemd: state=restarted name=splash daemon_reload=yes
```

Start an instance with that configuration and I end up with a folder in `/app/deploy` called `$HOME`. The only thing in the folder is `.ansible/tmp`.

##### EXPECTED RESULTS

Not to have a folder named `$HOME`.

##### ACTUAL RESULTS

There is a `$HOME` folder in `/app/deploy`, in other words `/app/deploy/$HOME`.

This is pretty closely related to #16032, but I'm not sure why that ticket was closed. The merge there doesn't seem to have made a difference for 2.2.0.
