### ISSUE TITLE
conditional `is defined` fails to capture undefined var

### ISSUE THREAD

**Issue by jmcostecalde** [ansible/ansible#23675]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
includes / when

##### ANSIBLE VERSION
```
  ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Mention any settings you have changed/added/removed in ansible.cfg
Didn't touch andible.cfg

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I have a block that includes a play (made of other tasks) and passes variables
```
  - block:
       - include: tasks/APlay.yml 
         vars:
            iwsVariable: "{{ someVariable }}"
```
in the APlay.yml, I have block with a condition
```
 - block:
      - do something
   when: iwsVariable is undefined
```
in Ansible 2.2.x, when "{{ someVariable }}" was undefined, so was iwsVariable and the block was executed successfully.
Since Ansible 2.3, that same condition raises the following error
```
The conditional check 'iwsVariable' is undefined' failed. The error was: error while evaluating conditional (iwsVariable is undefined): {{ someVariable }}: 'someVariable' is undefined\n\nThe error appears to have been in ...
```
##### STEPS TO REPRODUCE
See above

##### EXPECTED RESULTS
 iwsVariable should be undefined just like the variable that initialized it

##### ACTUAL RESULTS
Error out (see description above)

**Comment by er1zo** [comment]
It looks like it's more common problem with conditionals. 
When is not working as it use to anymore.
I have this block
```
- name: get list of currently installed vms
   delegate_to: "{{ item }}"
   with_items: "{{ groups.hns }}"
   virt:
     command: list_vms
   register: virt_vms

 - name: get one list for all hns
   set_fact:
     vmlist: "{{ virt_vms.results[0].list_vms }}"
   when: virt_vms.results[1].list_vms is undefined
```
Previously(2.2.1) when list was empty(undefined) ansible executed this step, now it fails with:

> FAILED! => {"failed": true, "msg": "The conditional check 'virt_vms.results[1].list_vms is undefined' failed. The error was: error while evaluating conditional (virt_vms.results[1].list_vms is undefined): list object has no element 1\n\nThe error appears to have been in '/some/path': line 11, column 4, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n - name: get one list for all hns\n   ^ here\n"

Ansible version is 
```
 ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```
Running ansible on both ubuntu 14.04 and mac os x 10.12
Target node is ubuntu 16.04

**Comment by emoshaya** [comment]
I'm having the exact same issue... Ansible is failing its run when it evaluates the condition and complains the variable is undefined. This issue definitely stems from 2.3.0... Is there a workaround?

**Comment by er1zo** [comment]
any update on the issue?

**Comment by jmcostecalde** [comment]
Hi there,

Is there a plan to fix that regression ?
It's making the scenario convoluted to work around that issue.

**Comment by hurricanehrndz** [comment]
I am being affected by the issue as well.

**Comment by hyperized** [comment]
Maybe beside the point but you might want to reverse the way this is used, use a positive form. So use:
```
when:
    - my_var is defined
    - my_var.changed
```

If you forget the first check and the my_var is undefined it'll throw the same error.

**Comment by eumel8** [comment]
me too! The last working version is 2.2.0.0. Later versions failed with

> error while evaluating conditional

```
- name: Set fact for availability_zone_id (eu_de-01)
  set_fact:
    availability_zone_id: "bf84aba586ce4e948da0b97d9a7d62fb"
  when:
    - listener_name is undefined
    - elb_availability_zone is defined
```

elb_availability_zone is a lookup variable of an ini_file in this case with a non-existing section. The non-existing section caused the error in 2.2.3.0

living code. https://github.com/eumel8/ansible-otc/blob/245f8963f2628f3cfa368ee9de5705c08346ed66/roles/lookup_name/tasks/main.yml#L6

**Comment by er1zo** [comment]
Positive form not working as well, fails with same undefined error

**Comment by krzysztof-magosa** [comment]
I'm also affected, it prevents me from upgrade to 2.3/2.4.

**Comment by nicladas** [comment]
Also experiencing the same issue in 2.3.1.0

**Comment by npolonski** [comment]
Seems to also be in 2.3.2.0

**Comment by jmcostecalde** [comment]
I don't think Ansible people plan to fix it. They don't seem to care much. It was removed from triage from the beginning.

"abadger removed the needs_triage label on Apr 19"

**Comment by npolonski** [comment]
@abadger or @bcoca Can someone help us understand why this was removed from Triage?
The folks on this list (myself included) are experiencing this issue and we'd like to know how to proceed. 
The referenced issues appear to be specific to SSH variable changes and not as generic as what we're seeing with referenced variable definition and resolution. 

Any help would be appreciated.

**Comment by bcoca** [comment]
'triage' means no human has looked at it and still needs to be verified as to correct labeling and severity, if it were NOT removed from triage it would be more concerning.

This is  an open bug and it is on the list to investigate and fix as appropriate, we just not have had the time/resources to address it yet.

**Comment by npolonski** [comment]
Thanks for the response @bcoca that helps clear up that part!

**Comment by npolonski** [comment]
My case is a little complex and unique to my situation, so I'm going to try to simplify with *pseudo code* below. 

vars.yml file:
```
list_of_stuff:
  - special_variable: "{{ thing_to_learn.id }}"
```

Role task:
```
include_vars: vars.yml
- task that populates thing_to_learn
  when: some_other_var == 'something'

- assert:
    that: 
      special_variable is defined and some_other_var == 'something'
```

Mine fails when `some_other_var` is set to `foo` trying to determine if `special_variable` is defined. It fails with the same error the others list above. It's says that `special_variable` is undefined, but really it's because `thing_to_learn.id` doesn't exist. 

I managed to work-around this failure with:
vars.yml file:
```
list_of_stuff:
  - special_variable: "{{ thing_to_learn.id if thing_to_learn is defined else omit }}"
```

I don't like this hack-around and would prefer it worked the way that it did in 1.9. The conditional should be False when `special_variable` is undefined regardless of the presence of a k/v pair lower in the dict. 
But this got me past my blocking issue. 

Sorry for the pseudo code vagary.

**Comment by nicladas** [comment]
I resolved this for my usage with adding a combo:
```yml
when:
    - variable is defined
    - variable != ""
```

**Comment by kamilszkoda** [comment]
This bug is very annoying.
Will be this bug resolved in coming version ?

**Comment by telegrapher** [comment]
Hi, I've just arrived to this issue because I've had some problems in my syntax. 

Ansible 2.4.0.0 works well for me. The following playbook doesn't fail when the disk sdb doesn't exist

    ---
    - name: Auxiliary playbook to print facts
      remote_user: root
      hosts: myhost
      vars:
    
      tasks:
      - name: Print a fact
        debug:
          msg: "The fact is {{ facter_disks }}"
    
      - name: Print another fact
        debug:
          msg: "The fact is {{ facter_disks['sda'] }}"
        when: facter_disks.sda is defined
    
      - name: Print the third fact
        debug:
          msg: "The fact is {{ facter_disks.sdb }}"
        when: facter_disks.sdb is defined
    
      - name: Print the third fact
        debug:
          msg: "The disk is not there "
        when: facter_disks.sdb is not defined

**Comment by chrisgahlert** [comment]
It took me quite a bit of searching to understand what has changed here:
The final hint came from #22729:

It seems like, when skipping a task, the output is registered nevertheless - but being empty. That means:

**Old way:**
`when: myoutput is defined and myoutput.stdout != ''`

**New way:**
`when: "'stdout' in myoutput and myoutput.stdout != ''"`

Hope this helps someone else in desperate need of a solution! ;)

**Comment by karniemi** [comment]
or another workaround:
```when: "myvar|d()|json_query('my.precious.sub.field')"```

Explanation: pass variable "myvar" through the default()-filter "d()" to ignore missing variable, then pass on to json_query to pick the sub-sub-field "my.precious.sub.field". So this also avoids testing the existence of each intermediate sub-fields individually.

**Comment by huxiaoliang** [comment]
above workaround solution is ok to me, thanks! @karniemi

**Comment by ice-8** [comment]
another one workaround
```
when: item not in vars
```
instead of
```
when: item is not defined
```

https://coderleaf.wordpress.com/2017/07/06/ansible-check-for-required-variables-before-role-execution/

**Comment by bcoca** [comment]
@ice-8 I would not rely on `vars`, it is on it's way out, there is a reason it is not documented.

Also this seems to already been fixed, i had found that 'not' was not matching the capture but now both of these work:
```
  - debug: msg=i always worked
    when: not item is defined

  - debug: msg=i sometimes failed
    when: item is not defined
```
any examples not working with latest devel?

needs_info

**Comment by BarbzYHOOL** [comment]
not sure if related but if you try to evaluate if a variable is defined inside a jinja {{ 'blabla' if var is defined }} and the variable 'var' has a default value with the "| default('value')" filter, then it's considered undefined (2.6 ansible)

@bcoca

**Comment by ansibot** [comment]
@jmcostecalde This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jmcostecalde** [comment]
That issue is 1year and a half old. I have moved to other work since then. I unfortunately cannot verify any fix at this point.
Thank you for working on it though

**Comment by ainiml** [comment]
not working still

```
ansible 2.9.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/eric/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]
```

```
---
- hosts: all
  tasks:

  - name: Create rancher-cluster.yaml
    vars:
      ACME_DOMAIN: "{{ lookup('env','ACME_DOMAIN') }}"
      NODE_PUBLIC_ADDRESS: "{{ lookup('env','NODE_PUBLIC_ADDRESS') }}"
      NODE_INTERNAL_ADDRESS: 172.16.22.12
      node_user: ubuntu
      node_role: [controlplane, worker, etcd]
    copy:
       dest: "rancher-cluster.yaml"
       content: |
         nodes:
           - address: {{ NODE_PUBLIC_ADDRESS }}
             internal_address: {{ NODE_INTERNAL_ADDRESS }}
             user: {{ node_user }}
             role: {{ node_role }}

         services:
           etcd:
             snapshot: true
             creation: 6h
             retention: 24h

         # Required for external TLS termination with
         # ingress-nginx v0.22+
         ingress:
           provider: nginx
           options:
             use-forwarded-headers: "true"
    when: ACME_DOMAIN is defined and NODE_PUBLIC_ADDRESS is defined 
```

Needs: 
`ACME_DOMAIN is defined and ACME_DOMAIN == True`

**Comment by tgadiev** [comment]
Any plans to fix that? I see that related PR was closed and there's no more activity...

**Comment by Zocker1999NET** [comment]
today I ran into the same issue, this needs to be fixed because it is unexpected behavior, small example:
```yaml
- hosts: localhost
  connection: local
  vars:
    # CHECKED: ""
    MY_VAR: "{{ CHECKED }}"
  tasks:
    - debug: msg="MY_VAR is defined"
      when: MY_VAR is defined
    - debug: msg="MY_VAR is undefined"
      when: MY_VAR is undefined
```
I expect this example playbook to run without any issues, but Ansible complains about `CHECKED` not being defined. A workaround checking first if `CHECKED is defined` does not help me here, because I use this kind of structure in a role where on some hosts `CHECKED` will be defined and in some special cases per host `MY_VAR` will be defined while `CHECKED` will or will not be defined.
```
ansible 2.9.13
  config file = /home/zocker/Repositories/ansible2/ansible.cfg
  configured module search path = ['/home/zocker/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 09:36:53) [GCC 10.2.0]
```

**Comment by sivel** [comment]
This has been resolved by https://github.com/ansible/ansible/pull/56116 and will be included in the 2.14 release in Nov 2022.

```yaml
- hosts: localhost
  gather_facts: false
  vars:
    thing: "{{ other }}"
  tasks:
    - debug:
        var: thing
      when: thing is defined
```

output:

```
PLAY [localhost] ***************************************************************

TASK [debug] *******************************************************************
skipping: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.libera.chat
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
