### ISSUE TITLE
Windows: some git operations cause error in raw module

### ISSUE THREAD

**Issue by varmil** [ansible/ansible#23679]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

raw module / git

##### ANSIBLE VERSION

```
2.3.0
```
(When I use v2.2.2, this problem is not occurred)

##### CONFIGURATION

N / A

##### OS / ENVIRONMENT

from: Mac 
managing: windowsservercore on Windows Server 2016 (docker)

##### SUMMARY

Some git operations return `rc: 1`. Ansible regards it as error, then stop the process.
(Actually, the git operation is NOT failed, but success.)

for example:
`git checkout <newBranch>`
```
- CategoryInfo          : NotSpecified: (Switched to branch 'newBranch':String) [], RemoteException
- FullyQualifiedErrorId : NativeCommandError

rc: 1
```

##### STEPS TO REPRODUCE

```yaml
- name: fetch
  raw: cd {{ path_of_repo }} | git fetch -p

- name: clean
  raw: cd {{ path_of_repo }} | git clean -df

- name: checkout -f
  raw: cd {{ path_of_repo }} | git checkout -f

- name: checkout branch
  raw: cd {{ path_of_repo }} | git checkout {{ branch }}

- name: pull
  raw: cd {{ path_of_repo }} | git pull
  register: pull_result
  changed_when: '"Already up-to-date" not in pull_result.stdout'
```

##### EXPECTED RESULTS

* Ansible continues the  process

##### ACTUAL RESULTS

* Ansible stops the process

```
TASK [build_deploy : checkout branch] ******************************************
changed: [xxx.xxx.xxx.xx]

stdout: "Your branch is behind 'origin/develop' by 26 commits, and can be fast-forwarded.
  (use \"git pull\" to update your local branch)"

changed: true

stderr: "#< CLIXML
Switched to branch 'develop'
<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"1\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">2</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>"

- CategoryInfo          : NotSpecified: (Switched to branch 'develop':String) [], RemoteException
- FullyQualifiedErrorId : NativeCommandError

rc: 1
```

**Comment by dagwieers** [comment]
This is not a bug. **raw**, **win_command** and **win_shell** do not know when a command succeeds or failed. By default it expects a return code of 0 to mean "success", but that may not be true.

If in your case the return code is non-zero, but this still means success, it is up to you to use `failed_when` so that it works for your use-case. http://docs.ansible.com/ansible/playbooks_error_handling.html#controlling-what-defines-failure

Example using robocopy (see: https://ss64.com/nt/robocopy-exit.html):
```yaml
- raw: robocopy.exe \\Server1\reports \\Server2\backup
  register: rbcopy
  failed_when: rbcopy.rc >= 4
```

notabug

**Comment by dagwieers** [comment]
BTW I am intrigued by your examples doing
```yaml
- raw: cd /some/path | git operation
```

Why would you pipe anything to git like that ?

Should you not be doing:
```yaml
- raw: cd /some/path && git operation
```

Or even better:
```yaml
- raw: git operation
  args:
    chdir: /some/path
```

See: https://ss64.com/nt/syntax-redirection.html

**Comment by gundalow** [comment]
@varmil Do the examples given by Dag work for you?
needs_info

**Comment by varmil** [comment]
Thank you for reply !
Sorry, I have not tried the example yet. However, I understand I have to use `failed_when` if the return code is non-zero but the task is success. I'll try it within a few days.

`- raw: cd /some/path | git operation`
I use pipe because it is PowerShell script. In PowerShell, sadly `&&` doesn't work. Pipe is a alternative, but is not best choice, maybe.

**Comment by dagwieers** [comment]
A pipe in powershell is not the same as '&&' in cmd.exe.

You probably want to do something like this:
```powershell
(cd /some/path) && (git operation)
```

However, I do think using the chdir-argument to **raw** is probably better. In this case I also do not see why you would be using **raw** specifically, and I would opt to use **win_shell** instead.

```yaml
- win_shell: git operations
  args:
    chdir: /some/path
```

And I would expect **git** to use non-zero return code for errors, and a zero-return code for success. And I tested a similar situation:
```
[dag@moria ansible.git]$ git checkout devel
Switched to branch 'devel'
Your branch is behind 'origin/devel' by 25 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
[dag@moria ansible.git]$ echo $?
0
```
Seems fine to me (regardless of the branch being behind). Please verify before implementing `failed_when:` !

**Comment by varmil** [comment]
I tried the method you taught, and did well !
For example, `win_shell: git pull`, like this.

input
```yaml
- name: pull
  win_shell: git pull
  args:
    chdir: '{{ path_of_repo }}'
  register: pull_result
  changed_when: '"Already up-to-date" not in pull_result.stdout'
```

output
```
TASK [build_deploy : pull] *****************************************************
changed: [XXXXXXXXXX]

_ansible_parsed: true

stderr_lines: [
  "Checking out files:  17% (378/2108)   ", 
  "Checking out files:  18% (380/2108)   ", 
  .....
  "Checking out files: 100% (2108/2108), done."
]

cmd: "git pull"

end: "2017-05-01 01:49:53.876790"

stdout: "Updating 132e7a3b3..390e72f2a
Fast-forward
....."

changed: true

rc: 0

start: "2017-05-01 01:49:03.109676"

stderr: "Checking out files:  17% (378/2108)   \rChecking out files:  18% (380/2108) ..... Checking out files: 100% (2108/2108), done."

delta: "0:00:50.767113"
```

I used `raw` because I had used `v2.0` before upgrade, and `win_shell` is new in `v2.2`. Now, `win_shell` is perfect !! Thank you for helping me.
