### ISSUE TITLE
Ansible 2.3.0.0 uri response would replace character b with ********

### ISSUE THREAD

**Issue by yunj** [ansible/ansible#23671]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

uri

##### ANSIBLE VERSION

```
2.3.0.0
```

##### CONFIGURATION

[defaults]
hostfile = hosts
roles_path = .galaxy:roles

##### OS / ENVIRONMENT

Windows 8.1

##### SUMMARY

Ansible 2.2.0.0 uri module behaves as expected but after upgrading to 2.3.0.0 uri response would replace character b with ********

##### STEPS TO REPRODUCE

Access some Rest API which would return application/xml containing, e.g., 1.0.0.beta. Please see the attachment as below.
![uri response](https://cloud.githubusercontent.com/assets/18545475/25104112/35a32316-2413-11e7-81e0-4733d35925c0.PNG)

```yaml
- name: Retrieve uploaded solutions
  uri:
    url: http://ip:port/path/to/resource
    user: admin
    password: b
    force_basic_auth: yes
    return_content: yes
  register: result
  until: result.status == 200
```

##### EXPECTED RESULTS

1.0.0.beta
321 bytes
##### ACTUAL RESULTS

1.0.0.********eta
321 ********ytes

```

```
