### ISSUE TITLE
known_hosts does not refer known_hosts file as expected.

### ISSUE THREAD

**Issue by fubarhouse** [ansible/ansible#23678]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`known_hosts`

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None.

##### OS / ENVIRONMENT
```
host: MacOSX 10.12.4
guest: Ubuntu 12.04
```

##### SUMMARY
When attempting to use the known_hosts module, the task is failing, verbose output is indicative of the module referring a non-existent file in /tmp instead of the specified (or default) known_hosts file.

Running `/usr/bin/ssh-keygen -F github.com -f ~/.ssh/known_hosts` separate of the module succeeds

##### STEPS TO REPRODUCE
defaults/main.yml
```yaml
default_server_hosts:
  - bitbucket.org
  - github.com
```
tasks/main.yml
```yaml
- name: Ensure hosts are known for user Jenkins.
  become: yes
  become_user: "jenkins"
  known_hosts:
    name: "{{ item }}"
    key: "/var/lib/jenkins/.ssh/id_rsa.pub"
  with_items:
    - "{{ default_server_hosts }}"
```

##### EXPECTED RESULTS
Success on task, where the result is changed or ok and the respective entry is now in the known_hosts entry if not previously. Running the command independently replacing /tmp/file with the known_hosts path achieves the expected results outside of use of this module.

A task which replicates what should happen and successfully is below, and the only change is the reference to this weird /tmp/file to the known_hosts file:
```yaml
- name: Jenkins | Ensure hosts are known.
  become: yes
  become_user: "jenkins"
  shell: "/usr/bin/ssh-keygen -F {{ item }} -f /var/lib/jenkins/.ssh/known_hosts"
  with_items:
    - "{{ default_server_hosts }}"
```

##### ACTUAL RESULTS

Module is referring to non-existent file in `/tmp` instead of the key file, as indicated by `/tmp/tmpkwyYj2 is not a valid known_hosts file.`.

```
failed: [drupalvm] (item=bitbucket.org) => {"cmd": "/usr/bin/ssh-keygen -F bitbucket.org -f /tmp/tmpkwyYj2", "failed": true, "item": "bitbucket.org", "msg": "line 1 missing key: /var/lib/jenkins/.ssh/id_rsa.pub...\r\n/tmp/tmpkwyYj2 is not a valid known_hosts file.", "rc": 1, "stderr": "line 1 missing key: /var/lib/jenkins/.ssh/id_rsa.pub...\r\n/tmp/tmpkwyYj2 is not a valid known_hosts file.\n", "stdout": "", "stdout_lines": []}
failed: [drupalvm] (item=github.com) => {"cmd": "/usr/bin/ssh-keygen -F github.com -f /tmp/tmp1A7fX5", "failed": true, "item": "github.com", "msg": "line 1 missing key: /var/lib/jenkins/.ssh/id_rsa.pub...\r\n/tmp/tmp1A7fX5 is not a valid known_hosts file.", "rc": 1, "stderr": "line 1 missing key: /var/lib/jenkins/.ssh/id_rsa.pub...\r\n/tmp/tmp1A7fX5 is not a valid known_hosts file.\n", "stdout": "", "stdout_lines": []}
```

**Comment by ansibot** [comment]
cc @mcv21
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fridim** [comment]
@fubarhouse, in :

```
- name: Ensure hosts are known for user Jenkins.
  become: yes
  become_user: "jenkins"
  known_hosts:
    name: "{{ item }}"
    key: "/var/lib/jenkins/.ssh/id_rsa.pub"
  with_items:
    - "{{ default_server_hosts }}"
```

Are you sure you're using know_hosts key param properly ? It seems you're using user jenkins' public key instead of specifying a public _host_ key. From doc :

> Key: The SSH public host key, as a string (required if state=present, optional when state=absent, in which case all keys for the host are removed). The key must be in the right format for ssh (see sshd(1), section "SSH_KNOWN_HOSTS FILE FORMAT")
