### ISSUE TITLE
A specified parameter was not correct: spec.location.datastore

### ISSUE THREAD

**Issue by sayantandas** [ansible/ansible#23685]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vsphere_guest

##### ANSIBLE VERSION

```
$ansible --version                                                                                                              
ansible 2.1.0.0
  config file = /home/ansible/.ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
```
[defaults]
hostfile = hosts
remote_user = ansible
private_key_file = /home/ansible/.ssh/id_rsa
host_key_checking = false

#ansible_managed = This file is managed by Ansible.%n
#  template: {file}
#  date: %Y-%m-%d %H:%M:%S
#  user: {uid}
#  host: {host}
```

##### OS / ENVIRONMENT
```

 cat /etc/lsb-release                                                                                                             
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
```

##### SUMMARY

Creating a Windows 2012 VM from  template fails with error "A specified parameter was not correct: spec.location.datastore" . The template is in working condition; VMs can be created using the template when commissioned from Vsphere web interface.

##### STEPS TO REPRODUCE

Below is the playbook used for  creating the VM. 
```
vars_prompt:
    - name: vcenter_hostname
      prompt: "enter hostname of vcenter"
      private: no

    - name: vm_name
      prompt: "please enter the vm name"
      private: no

    - name: vcenter_cluster
      prompt: "please enter the vcenter cluster"
      private: no

    - name: vm_template
      prompt: "please enter the templatename to use"
      private: no

    - name: vcenter_datacenter
      prompt: "please enter the vcenter datacenter"
      private: no

    - name: vcenter_hypervisor
      prompt: "please enter the hypervisor"
      private: no

 - name: deploy virtual machine from template
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      guest: "{{ vm_name }}"
      cluster: "{{ vcenter_cluster }}"
      resource_pool: "/Resources"
      from_template: "true"
      template_src: "{{ vm_template }}"
      esxi:
        datacenter: "{{ vcenter_datacenter }}"
        hostname: "{{ vcenter_hypervisor }}"
    delegate_to: "localhost"


```

##### EXPECTED RESULTS
 VM should be created from template successfully

##### ACTUAL RESULTS
The playbook failed with error  "A specified parameter was not correct: spec.location.datastore" . The template is in working condition as new VMs can be created from the template directly from the Vcenter dashboard.

```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"cluster": "Cluster2", 
"esxi": {"datacenter": "TEST-DC", "hostname": "host25.domain.com"}, 
"force": false, "from_temp late": true, "guest": "win2012-test", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "power_on_after_clone": true, 
"resource_ pool": "/Resources", "snapshot_to_clone": null, "state": "present", "template_src": "win2012", "username": "Ansible_old@vsphere.local", 
"validate_certs": true, "vcenter_hostname": "vcenter.domain.com", "vm_disk": {}, "vm_extra_config": {}, "vm_hardware ": {}, "vm_hw_version": null, 
"vm_nic": {}, "vmware_guest_facts": null}, "module_name": "vsphere_guest"}, "msg": "Could not clone selected machine: [Task Error]: A specified parameter was not correct: spec.location.datastore"}
```
