### ISSUE TITLE
UnboundLocalError in `cloudflare_dns` module in check mode

### ISSUE THREAD

**Issue by jackprice** [ansible/ansible#23682]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`cloudflare_dns`

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel a06014663c) last updated 2017/04/18 07:08:27 (GMT +100)
  config file = 
  configured module search path = [u'/Users/jack/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jack/Projects/ansible/lib/ansible
  executable location = /Users/jack/Projects/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 30 2016, 18:31:42) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Using the `cloudflare_dns` module in check mode, where a change would be made, causes an `UnboundLocalError` to be thrown.

Without check mode, or if no changes would be made, the module works as expected.

##### STEPS TO REPRODUCE

Playbook:

```yaml
- hosts: localhost
  connection: local
  
  tasks:
  - name: create dns record
    cloudflare_dns:
      zone: example.com
      record: a-record-that-does-not-exist
      type: A
      value: 1.2.3.4
      state: present
      account_email: foo@example.com
      account_api_token: aabbccddeeff
```

Command:

```bash
ansible-playbook example.yml --check
```

##### EXPECTED RESULTS
A `changed` result to be outputted, and no record created.

##### ACTUAL RESULTS
An error is thrown:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'result' referenced before assignment
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ioQv52/ansible_module_cloudflare_dns.py\", line 648, in <module>\n    main()\n  File \"/tmp/ansible_ioQv52/ansible_module_cloudflare_dns.py\", line 636, in main\n    result,changed = cf_api.ensure_dns_record()\n  File \"/tmp/ansible_ioQv52/ansible_module_cloudflare_dns.py\", line 584, in ensure_dns_record\n    return result,self.changed\nUnboundLocalError: local variable 'result' referenced before assignment\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

The error cleaned up:

```
UnboundLocalError: local variable 'result' referenced before assignment

Traceback (most recent call last):
  File "/tmp/ansible_ioQv52/ansible_module_cloudflare_dns.py", line 648, in <module>
    main()
  File "/tmp/ansible_ioQv52/ansible_module_cloudflare_dns.py", line 636, in main
    result,changed = cf_api.ensure_dns_record()
  File "/tmp/ansible_ioQv52/ansible_module_cloudflare_dns.py", line 584, in ensure_dns_record
    return result,self.changed
```
