### ISSUE TITLE
facter > 3.1.8 fails when used in ansible

### ISSUE THREAD

**Issue by merlin-tc** [ansible/ansible#23695]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/system/facter.py

##### ANSIBLE VERSION
ansible 2.3.0.0

##### CONFIGURATION
standard ansible configuration

##### OS / ENVIRONMENT
Gentoo Linux

##### SUMMARY
Upstream facter removed the --puppet flag which causes facter to fail silently even though it's called by ansible.
If called directly it shows the error.
Removing "--puppet" from the facter command fixes the problem if the facter module is called directly. Strangely enough there is still no output if the ansible "setup" module is used, which should pull in the facter output as well.

Output from older version of facter where it still works:
  -p [ --puppet ]                (Deprecated: use `puppet facts` instead) Load 
                                 the Puppet libraries, thus allowing Facter to 
                                 load Puppet-specific facts.

##### STEPS TO REPRODUCE

```yaml
ansible localhost -m facter
```

##### EXPECTED RESULTS
Add facts gathered by ansible.

##### ACTUAL RESULTS
```yaml
META: ran handlers
Using module file /usr/lib64/python2.7/site-packages/ansible/modules/system/facter.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: merlintc
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2.7 && sleep 0'
localhost | FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/facter --puppet --json", 
    "failed": true, 
    "invocation": {
        "module_args": {}
    }, 
    "msg": "2017-04-18 13:04:24.366258 FATAL puppetlabs.facter - unhandled exception: boost::too_many_args: format-string referred to fewer arguments than were passed", 
    "rc": 1, 
    "stderr": "2017-04-18 13:04:24.366258 FATAL puppetlabs.facter - unhandled exception: boost::too_many_args: format-string referred to fewer arguments than were passed\n", 
    "stderr_lines": [
        "2017-04-18 13:04:24.366258 FATAL puppetlabs.facter - unhandled exception: boost::too_many_args: format-string referred to fewer arguments than were passed"
    ], 
    "stdout": "", 
    "stdout_lines": []
}
```
```

```
