### ISSUE TITLE
apt-repository drops the arch specification given in the source string of the repo parameter

### ISSUE THREAD

**Issue by kpachar** [ansible/ansible#23690]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apt_repository

##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file = /redacted/ansible.cfg
  configured module search path = ['modules']
```

##### CONFIGURATION
No changes to ansible.cfg

##### OS / ENVIRONMENT
N/A

##### SUMMARY
apt-repository drops the arch specification given in the source string of the repo parameter

##### STEPS TO REPRODUCE
When I run the apt_repository task shown below (note that the `repo` parameter has an `arch` specified), the resultant repository in the /etc/apt/sources.list.d misses the `[arch=amd64]` in it. Everything else is retained verbatim, except the arch spec.

```yaml
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - apt_repository:
      repo: deb [arch=amd64] http://192.168.102.54/mirror/gniwollof/elpmaxe prodcode main
      state: present
```
(This causes a problem when the repository being added is only a partial mirror of a larger repository containing distributions for all architectures. A subsequent `apt-get update` would error out saying that it does not find the index files for the other archs that are not used. Had it not dropped the arch spec, this problem would not have been there)

##### EXPECTED RESULTS
The resulting file in /etc/apt/sources.list.d should have retained the arch spec

##### ACTUAL RESULTS
The resulting file in /etc/apt/sources.list.d omits the arch spec

**Comment by zarnovican** [comment]
### Unable to reproduce

I have successfully added Docker repo using these tasks:
```
- name: 'import Docker GPG signing key'
  apt_key:
    id: 0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg

- name: 'add Docker repository'
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
```
And the repo in Apt _does_ contain "[arch=amd64]" string.
```
$ cat /etc/apt/sources.list.d/download_docker_com_linux_ubuntu.list 
deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
```
(I'm on Ansible 2.2.0, but I have gently tested it also on 2.2.2 and 2.3.1 with the same result)

Would it be possible that your issue is unrelated to Ansible ?
