### ISSUE TITLE
mount Solaris 11

### ISSUE THREAD

**Issue by helltone** [ansible/ansible#23693]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 ansible/lib/ansible/modules/system/mount.py

##### ANSIBLE VERSION
ansible 2.2.1.0

##### CONFIGURATION
out the box

##### OS / ENVIRONMENT
running Ansible on - Red Hat Enterprise Linux Server release 6.8 (Santiago)
managing OS - Solaris 11.3 FMRI: pkg://solaris/entire@0.5.11,5.11-0.175.3.9.0.4.0

##### SUMMARY
mount NFS fails

##### STEPS TO REPRODUCE
```yaml
---
- hosts: test_solaris
  sudo: True

  tasks:
  - name: Create dir for nfs mount
    file: path=/mounted state=directory mode=777 owner=root group=root

  - mount:
     name: /mounted
     src: 10.10.10.20:/Distr
     fstype: nfs
     state: mounted
```

##### EXPECTED RESULTS
on Solaris host (test_solaris) /mounted dir will be created and 10.10.10.20:/Distr NFS share will be mounted

##### ACTUAL RESULTS
```json
fatal: [10. 10. 10. 10]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "boot": "yes",
            "dump": null,
            "fstab": "/etc/fstab",
            "fstype": "nfs",
            "name": "/mounted",
            "opts": null,
            "passno": null,
            "src": "10.10.10.20:/Distr",
            "state": "mounted"
        },
        "module_name": "mount"
    },
    "msg": "Error mounting /mounted: /sbin/mount: illegal option -- T\nUsage:\nmount [-v | -p]\nmount [-F FSType] [-V] [current_options] [-o specific_options]\n\t{special | mount_point}\nmount [-F FSType] [-V] [current_options] [-o specific_options]\n\tspecial mount_point\nmount -a [-F FSType ] [-V] [current_options] [-o specific_options]\n\t[mount_point ...]\n"
```

##### WORKAROUND
Comment  line 357 in mount.py
cmd += _set_fstab_args(args['fstab'])

##### ACTUAL RESULTS AFTER WORKAROUND
```json
changed: [10. 10. 10. 10] => {
    "boot": "yes",
    "changed": true,
    "fstab": "/etc/vfstab",
    "fstype": "nfs",
    "invocation": {
        "module_args": {
            "boot": "yes",
            "dump": null,
            "fstab": "/etc/fstab",
            "fstype": "nfs",
            "name": "/mounted",
            "opts": null,
            "passno": null,
            "src": "10.10.10.20:/Distr",
            "state": "mounted"
        },
        "module_name": "mount"
    },
    "name": "/mounted",
    "opts": "-",
    "passno": "-",
    "src": "10.116.90.20:/Distr"
}
```
