### ISSUE TITLE
eos_command is sending module warnings even when arguments are not set.

### ISSUE THREAD

**Issue by ktbyers** [ansible/ansible#23720]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
eos_command

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/kbyers/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### SUMMARY
```
[WARNING]: argument use_ssl has been deprecated and will be removed in a future version

 [WARNING]: argument port has been deprecated and will be removed in a future version

 [WARNING]: argument validate_certs has been deprecated and will be removed in a future version
```

Note, in my `provider` I am not even specifying `use_ssl` or `port` (I am just using the defaults for each of these). I am specifying validate_certs.

Here is my provider:

```    
    eapi:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: eapi
      validate_certs: no
```

It looks like you are setting these with default values at the task level (i.e. outside of the provider) which is causing the warning message.

in ./module_utils/eos.py

```
    'port': dict(type='intf, default=443),

    'use_ssl': dict(type='bool', default=True),
    'validate_certs': dict(type='bool', default=True),
```
