### ISSUE TITLE
vmware_guest state: rebootguest invalid

### ISSUE THREAD

**Issue by arshantz** [ansible/ansible#23724]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

[defaults]
pipelining = True
#remote_tmp = /opt/appdata/ansible
host_key_checking = False
timeout = 20

##### OS / ENVIRONMENT

RHEL6
##### SUMMARY

Running the vmware_guest module with "state: rebootguest" (as documented) results in an error stating that value is not supported.

##### STEPS TO REPRODUCE

```
    - name: restart VM
      vmware_guest:
        hostname: "xxx"
        username: xxx
        password: "{{vspherePass}}"
        validate_certs: no
        datacenter: xxx
        name: "{{item}}"
        wait_for_ip_address: yes
        folder: lab
        state: rebootguest
      with_items:
        - "labsystem028"

```

##### EXPECTED RESULTS

I expected the module to reboot the VM.

##### ACTUAL RESULTS

The module execution failed with a unsupported value error.

```
failed: [10.250.0.131] (item=labnrsqn028) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "datacenter": "US2", 
            "folder": "lab", 
            "force": false, 
            "hardware": {}, 
            "hostname": "iad1vcenter001.bd.trust", 
            "name": "labnrsqn028", 
            "name_match": "first", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "rebootguest", 
            "username": "ashantz", 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }, 
        "module_name": "vmware_guest"
    }, 
    "item": "labnrsqn028", 
    "msg": "value of state must be one of: poweredon,poweredoff,present,absent,restarted,reconfigured, got: rebootguest"
}
```
