### ISSUE TITLE
script plugin should fail when used with async

### ISSUE THREAD

**Issue by fridim** [ansible/ansible#23729]
Before the refactoring of async : https://github.com/ansible/ansible/commit/c86a17b7a003ac22c173cfa832ed2368e15015e6 : using async with script returns an error
After: async param ignored.

see also #20232
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
plugins/action/script.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel a06014663c) last updated 2017/04/18 10:08:09 (GMT +200)
  config file =
  configured module search path = ['/home/fridim/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/fridim/sync/dev/ansible/lib/ansible
  executable location = /home/fridim/sync/dev/ansible/bin/ansible
  python version = 3.6.0 (default, Jan 16 2017, 12:12:55) [GCC 6.3.1 20170109]
```

##### SUMMARY
Using async with script should fail, but it's ignored.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - copy:
        dest: /tmp/script.sh
        content: |-
          #!/bin/bash
          sleep 200
    - name: bla
      script: /tmp/script.sh
      async: 2
      poll: 1
```

##### EXPECTED RESULTS
```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "async mode is not supported with the script module"}
```

##### ACTUAL RESULTS

async ignored
