### ISSUE TITLE
known_hosts module fail when ssh-keygen exit with 1

### ISSUE THREAD

**Issue by tdihp** [ansible/ansible#23727]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

modules.system.known_hosts

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/pp/proj/barejenkins/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Dec 13 2016, 10:45:11) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
not configuration specific

##### OS / ENVIRONMENT

Running Ansible from: Mac
Managing: Ubuntu 1604

##### SUMMARY

Using known_hosts to add a new host entry gives me an unexplained error

I'm pretty sure it's these lines in `sanity_check` (persist in devel branch too)

    rc,stdout,stderr=module.run_command([sshkeygen,'-F',host,
                                         '-f',outf.name],
                                        check_rc=True)

While the other place with `ssh-keygen -F` allows `rc==1`

While I want to try fix this, I'm not able to get the test suite pass using either
`ansible-test units --local` (no pytest), or `ansible-test units --docker` (no python 2.6)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: myhost
tasks:
  - name: add some host that myhost haven't seen
    known_hosts:
      name: "other.host.name"
      key: "{{ some_rsa_public_key }}"
```

##### EXPECTED RESULTS
OK (changed)

##### ACTUAL RESULTS

fail with:

    {"changed": false, "cmd": "/usr/bin/ssh-keygen -F other.host.name -f /tmp/tmpNWb8U9", "failed": true, "msg": "", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
