### ISSUE TITLE
!unsafe broken in Ansible 2.3.0.0?

### ISSUE THREAD

**Issue by mellowplace** [ansible/ansible#23734]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

jinja2 (?)

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /ansible/ansible.cfg
  configured module search path = [u'/ansible/library']
  python version = 2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]

```

##### OS / ENVIRONMENT

Docker Alpine container running on Ubuntu

##### SUMMARY

Templating out...
```
!unsafe |
            ALERT InstanceDown
            IF up == 0
            FOR 5m
            LABELS { severity = "page" }
            ANNOTATIONS {
              summary = "Instance {{ $labels.instance }} down",
              description = "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.",
            }
```
Should result in the `{{ $labels.instance }}` and  `{{ $labels.job }}` remaining unchanged (i.e. not interpolated) but infact Ansible is now interpolating them again.

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

For variables in unsafe strings to remain un-interpolated.

##### ACTUAL RESULTS

The string was interpolated

**Comment by mellowplace** [comment]
I can confirm this also affects 2.2.2.0 but is working in 2.2.1.0

**Comment by snowsky** [comment]
Do you have yaml playbook file?

need_info

**Comment by snowsky** [comment]
I didn't reproduce with this playbook with or w/o $ sign in $labels:

```
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    labels:
      instance: "test"
      job: "test"
    a: !unsafe |
            ALERT InstanceDown
            IF up == 0
            FOR 5m
            LABELS { severity = "page" }
            ANNOTATIONS {
              summary = "Instance {{ $labels.instance }} down",
              description = "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 5 minutes.",
            }

  tasks:
    - debug: msg={{a}}
```

**Comment by mellowplace** [comment]
Playbook

```
---

- name: Test unsafe
  hosts: localhost
  become: false
  gather_facts: false
  connection: local
  vars:
    prometheus_alerts:
      - name: test
        rule: !unsafe |
          {{ $test }}
          {{ another_test }}

  tasks:
    - name: create rules
      tags: [prometheus]
      blockinfile:
        dest: /tmp/{{ item.name }}.rules
        create: yes
        block: "{{ item.rule }}"
        marker: "# {{ item.name }} {mark}"
      with_items: "{{ prometheus_alerts }}"

    - command: cat /tmp/test.rules
      register: output
```

Run with `-v` to get debug 

Running in 2.2.1.0

```
PLAY [Test unsafe] *************************************************************

TASK [create rules] ************************************************************
ok: [localhost] => (item={u'name': u'test', u'rule': u'{{ $test }}\n{{ another_test }}\n'}) => {"changed": false, "item": {"name": "test", "rule": "{{ $test }}\n{{ another_test }}\n"}, "msg": ""}

TASK [command] *****************************************************************
changed: [localhost] => {"changed": true, "cmd": ["cat", "/tmp/test.rules"], "delta": "0:00:00.008700", "end": "2017-04-19 12:44:23.552773", "rc": 0, "start": "2017-04-19 12:44:23.544073", "stderr": "", "stdout": "# test BEGIN\n{{ $test }}\n{{ another_test }}\n# test END", "stdout_lines": ["# test BEGIN", "{{ $test }}", "{{ another_test }}", "# test END"], "warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

You can see the stdout contains the `{{ $test }}` and `{{ another_test }}` lines

Running in 2.2.2.0

```
PLAY [Test unsafe] *************************************************************

TASK [create rules] ************************************************************
changed: [localhost] => (item={u'name': u'test', u'rule': u'{# $test #}\n{# another_test #}\n'}) => {"changed": true, "item": {"name": "test", "rule": "{# $test #}\n{# another_test #}\n"}, "msg": "Block inserted"}

TASK [command] *****************************************************************
changed: [localhost] => {"changed": true, "cmd": ["cat", "/tmp/test.rules"], "delta": "0:00:00.008554", "end": "2017-04-19 12:46:33.281070", "rc": 0, "start": "2017-04-19 12:46:33.272516", "stderr": "", "stdout": "# test BEGIN\n\n# test END", "stdout_lines": ["# test BEGIN", "", "# test END"], "warnings": []}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=2    unreachable=0    failed=0   
```

You can see stdout just has the block header and footer.
