### ISSUE TITLE
iosxr_facts gathering memory summary broken

### ISSUE THREAD

**Issue by chrmcd** [ansible/ansible#23737]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module/network/iosxr/iosxr_facts
##### ANSIBLE VERSION

```
ansible 2.3.0.0 (stable-2.3 f66852f1ef) last updated 2017/04/18 08:24:40 (GMT +000)
  config file = /root/bachelor/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

Not relevant
##### OS / ENVIRONMENT

N/A
##### SUMMARY

iosxr_facts does not gather memory summary from router when gathering the hardware subset
##### STEPS TO REPRODUCE

```yaml
- name: Get iosXR facts
  hosts: xxxx
  connection: local
  tasks:

    - name: gather facts
      iosxr_facts:
        provider: "{{ router_provider }}"
        gather_subset: "hardware"

```

##### EXPECTED RESULTS

Getting the facts "memtotal_mb" and "memfree_mb"
##### ACTUAL RESULTS

The facts doesn't exist (the module doesn't fail)

I've found the error, and it's caused by a broken regex, which when fixed breaks the module because the event in the if condition is also broken:
```
        match = re.search(r'Physical Memory (\d+)M total \((\d+)',
            results['show memory summary'])
        if match:
            self.facts['memtotal_mb'] = int(match[0])
            self.facts['memfree_mb'] = int(match[1])
```
this works if it looks like this:
```
        match = re.search(r'Physical Memory: (\d+)M total \((\d+)',
            results['show memory summary'])
        if match:
            self.facts['memtotal_mb'] = match.group(1)
            self.facts['memfree_mb'] = match.group(2)
```
