### ISSUE TITLE
get_url module works as expected on MAC OS but fails in Debian/ubuntu OS

### ISSUE THREAD

**Issue by rajashekharkethireddy** [ansible/ansible#23749]
##### ISSUE TYPE
 - Bug Report
 

##### COMPONENT NAME
get_url module 

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /root/ansible.cfg
  configured module search path = Default w/o overrides

```

##### SUMMARY
using get_url module to GET from artifactory
working on my local macbook , but if I run same task on debian/ubuntu os it fails
##### STEPS TO REPRODUCE

```
- name: Download artifact
  get_url:
    url: https://xxxxxx:443/billing-{{ processing_version }}-py2-none-any.whl
    url_username: "{{ artifactory_user }}"
    url_password: "{{ artifactory_pass }}"
    dest: /tmp/billing-{{ processing_version }}-py2-none-any.whl
  when: action == "download"
```

##### EXPECTED RESULTS
```
TASK [processing : Download artifact] ******************************************
task path: /Users/rkethireddym011004/storage/objectstorage-billing-ansible/roles/processing/tasks/download.yml:1
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: rkethireddym011004
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/local/opt/python/bin/python2.7 && sleep 0'
ok: [localhost] => {"changed": false, "dest": "/tmp/billing-1.0.18-py2-none-any.whl", "gid": 0, "group": "wheel", "invocation": {"module_args": {"backup": false, "checksum": "", "content": null, "delimiter": null, "dest": "/tmp/billing-1.0.18-py2-none-any.whl", "directory_mode": null, "follow": false, "force": false, "force_basic_auth": false, "group": null, "headers": null, "http_agent": "ansible-httpget", "mode": null, "owner": null, "path": "/tmp/obilling-1.0.18-py2-none-any.whl", "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "sha256sum": "", "src": null, "timeout": 10, "tmp_dest": "", "url": "https://xxxxxxx:443/artifactory/billing/uat/billing-1.0.18-py2-none-any.whl", "url_password": "xxxxxx", "url_username": "xxxxxx", "use_proxy": true, "validate_certs": true}, "module_name": "get_url"}, "mode": "0644", "msg": "file already exists", "owner": "rkethireddym011004", "size": 58733, "state": "file", "uid": 501, "url": "https://xxxx:443/artifactory/billing-1.0.18-py2-none-any.whl"}
```
##### ACTUAL RESULTS

TASK [processing : Download artifact] ******************************************
fatal: [localhost]: FAILED! => {"changed": false, "dest": "/tmp/billing-1.0.18-py2-none-any.whl", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://xxxxx:443/artifactory/billing-1.0.18-py2-none-any.whl"}

```

```
