### ISSUE TITLE
support defining vars inside tasks files

### ISSUE THREAD

**Issue by tyll** [ansible/ansible#2374]
It would be nice to be possible to specify vars in tasks files such as the following:

```
# playbook.yml
- hosts: localhost
  tasks:
    - include: tasks.yml
```

```
# tasks.yml
vars:
- path: /srv/bar

- name: copy file foo
  action: copy src=foo dest=$path/foo

- name: copy file bar
  action: copy src=bar dest=$path/bar
```

This allows to bundle common strings inside a tasks file.
