### ISSUE TITLE
vmware_guest_snapshot: better error message when using UUID and not finding VM

### ISSUE THREAD

**Issue by fdutheil** [ansible/ansible#23750]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest_snapshot

##### ANSIBLE VERSION
```
ansible 2.3.0.0
```

##### OS / ENVIRONMENT

Control machine: Ubuntu 12.04
Remote machine: Ubuntu 12.04 on vSphere 6

##### SUMMARY
When using the UUID parameter, if the module fails to find the VM, it displays a misleading message containing the "name" parameter, which is non relevant when using UUID. Indeed, "name" is mandatory but UUID parameter takes precedence (as far as I understand the module source code), so it's more than probable that "name" will contain a dummy value.

##### STEPS TO REPRODUCE

```yaml
- name: Manage VM Snapshots
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create snapshot
      vmware_guest_snapshot:
        datacenter: my_DC
        uuid: 42248E46-B8C0-41E3-C257-90A3E6DD146A
        hostname: my_vsphere_host
        username: my_account
        password: my_pw
        name: DUMMY_VALUE
        state: present
        snapshot_name: snap_ANSIBLE
        description: Test snapshot by Ansible
        validate_certs: false
```

##### EXPECTED RESULTS
```
PLAY [Manage VM Snapshots] ************************************************************************************************************************************************************************************************************

TASK [Create snapshot] ****************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to manage snapshots for non-existing VM 42248E46-B8C0-41E3-C257-90A3E6DD146A"}
	to retry, use: --limit @/home/ansible/.ansible/retry/test_vmsnapshot.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

##### ACTUAL RESULTS

```
PLAY [Manage VM Snapshots] ************************************************************************************************************************************************************************************************************

TASK [Create snapshot] ****************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to manage snapshots for non-existing VM DUMMY_VALUE"}
	to retry, use: --limit @/home/ansible/.ansible/retry/test_vmsnapshot.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```

##### COMMENTS
I found this out because I wanted to be sure the UUID was taken into account and not the name when both parameters are provided to the module.
My issue what that the UUID has to be lowercase when passed to vmware_guest_snapshot (and dmidecode show it uppercase, of course).
Involved code (line 300):
```
if not vm:
   module.fail_json(msg="Unable to manage snapshots for non-existing VM %(name)s" % module.params)
```
