### ISSUE TITLE
azure_rm_virtualmachine appending tags does not work

### ISSUE THREAD

**Issue by bjornicus** [ansible/ansible#23765]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/ubuntu/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
##### OS / ENVIRONMENT
I think this is NA but I'm running it on Linux ubuntu-xenial 4.4.0-71-generic

##### SUMMARY
the azure_rm_virtualmachine module 
https://docs.ansible.com/ansible/azure_rm_virtualmachine_module.html
has documented a `append_tags` parameter, which should append tags if set to true, but does not.

There are actually two issues that prevent this from working correctly,  the first is, I believe, the same as issue number #20444, which I believe causes *any* change to an existing VM to fail with a `KeyError: 'vmId'` (which is what happens when running the below playbook without appylying the [fix](https://github.com/ansible/ansible/pull/22974) for that, which unfortunately has not yet been merged.  However, after applying that fix, the playbook runs successfully, but results in the tags from the second task replacing the ones set at creation time, rather than being appended.

##### STEPS TO REPRODUCE
run the following playbook, specifying `vmname` and `rg` on the command line using --extra-vars

```yaml
---
- name: "create and update the tags on a VM"
  hosts: localhost
  tasks: 
  - name: Create {{vmname}} VM 
    azure_rm_virtualmachine:
      resource_group: '{{ rg }}'
      name: '{{vmname}}'
      vm_size: Standard_DS1_v2
      admin_username: yoda
      admin_password: do0rDoNot
      image:
        offer: UbuntuServer
        publisher: Canonical
        sku: '16.04-LTS'
        version: latest
      append_tags: no
      tags: 
        'foo': 'bar'

  - name: Append tags to {{vmname}}
    azure_rm_virtualmachine:
      resource_group: '{{ rg }}'
      name: '{{vmname}}'
      vm_size: Standard_DS1_v2
      append_tags: yes
      tags: 
        'derp': 'snort'
```

##### EXPECTED RESULTS
VM should be created and tagged with both `'foo':'bar'` and `'derp':'snort' `

##### ACTUAL RESULTS
The resulting VM has only `'derp':'snort'` tags (though it's clearly created with `'foo':'bar'`, it just gets overridden
