### ISSUE TITLE
wait_for_connection Not Utilizing group_vars

### ISSUE THREAD

**Issue by npazo** [ansible/ansible#23766]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
wait_for_connection

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /tmp/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]
```

##### CONFIGURATION

```
[defaults]
host_key_checking=false
retry_files_enabled = False
private_key_file=<PATH REMOVED>
inventory=inventory.ini
```

##### OS / ENVIRONMENT

Run inside an Alpine Linux Docker container with OS X as the host machine

##### SUMMARY

`wait_for_connection` does not appear to use `group_vars` settings. In this case it doesn't seem to be using `ansible_ssh_common_args:` to properly utilize the bastion server needed to connect to the new instance.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  tasks:  
  - name: Launch Testing Server
    ec2:
      ...

 - name: Add new instance to host group
    add_host:
      hostname: new_server
      ansible_host: <ip from EC2>
      groupname: gatewayed


- name: Setup Instances
  hosts: gatewayed
  gather_facts: no
  pre_tasks:

   - name: Wait 600 seconds for target connection to become reachable/usable
     wait_for_connection:

```

##### EXPECTED RESULTS

It would wait_for_connection to the `test_server` host using the `ansible_ssh_common_args` from the `group_vars` file `gatewayed.yml`. 

##### ACTUAL RESULTS

It appears to just try to connect to the IP on port 22 based on the -vvvv, but it's unclear if it's trying to use any of these custom configurations.

```
attempting transport test to 172.31.13.116:22
attempting transport test to 172.31.13.116:22
<repeat>
```
