### ISSUE TITLE
YAML block indentation indicator not working in Ansible 2.3.0.0

### ISSUE THREAD

**Issue by jondoig** [ansible/ansible#23777]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Block indentation indicator

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Jul  1 2016, 15:12:24) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

YAML block indentation indicator not working.

##### STEPS TO REPRODUCE

```
   - name: Add parameters into virtualHost block
     blockinfile:
       path: /etc/apache2/sites-available/geonode.conf
       insertbefore: '^\s*\</VirtualHost'
       block: |4
         SSLEngine on
         SSLCertificateFile    /etc/ssl/certs/geonode.crt
         SSLCertificateKeyFile /etc/ssl/private/geonode.key
         BrowserMatch "MSIE [2-6]" \
           nokeepalive ssl-unclean-shutdown \
           downgrade-1.0 force-response-1.0
         # MSIE 7 and newer should be able to use keepalive
         BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
     become: true

```

##### EXPECTED RESULTS

Add a block with 4 space indent (6 for "nokeepalive ..." and the next line).

##### ACTUAL RESULTS

Instead it gives a syntax error

```
ERROR! Syntax Error while loading YAML.

The error appears to have been in 'myfile.yml': line 30, column 10, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

       block: |4
         SSLEngine on
         ^ here
```

**Comment by s-hertel** [comment]
Not a yaml expert, but is the problem that your block is only indented two? If you indent everything in the block by two spaces does that work? 
```
   - name: Add parameters into virtualHost block
     blockinfile:
       path: /etc/apache2/sites-available/geonode.conf
       insertbefore: '^\s*\</VirtualHost'
       block: |4
           SSLEngine on
           SSLCertificateFile    /etc/ssl/certs/geonode.crt
           SSLCertificateKeyFile /etc/ssl/private/geonode.key
           BrowserMatch "MSIE [2-6]" \
             nokeepalive ssl-unclean-shutdown \
             downgrade-1.0 force-response-1.0
           # MSIE 7 and newer should be able to use keepalive
           BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
     become: true
```

**Comment by s-hertel** [comment]
needs_info

**Comment by jondoig** [comment]
No the 2-space tab is not a problem.

On 6 May 2017 03:49, "Sloane Hertel" <notifications@github.com> wrote:

needs_info

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ansible/ansible/issues/23777#issuecomment-299530998>,
or mute the thread

**Comment by s-hertel** [comment]
When I run your reproducer through a YAML validator (yamllint) it doesn't think it is valid (I get the error: `(<unknown>): did not find expected key while parsing a block mapping at line 3 column 8`). But when I indent your reproducer by 2 spaces (as I posted above) it is verified as correct YAML (and runs as expected with Ansible).

**Comment by sivel** [comment]
I have confirmed what @s-hertel is saying.

With a more simple reproducer:

```
    - set_fact:
        foo: |4
          bar
          baz
```

That fails, because `bar` and `baz` are only indented 2 spaces farther than `foo`.  If you increase to 4 spaces, it works:

```
    - set_fact:
        foo: |4
            bar
            baz
```

Child indentation is relative to the indentation of the parent node.

**Comment by sivel** [comment]
Per the spec, this is expected http://yaml.org/spec/1.2/spec.html#id2793979

Under "Example 8.3. Invalid Block Scalar Indentation Indicators"

```
- |2
·text
```

```
- The text is less indented
  than the indicated level.
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by BarbzYHOOL** [comment]
Doesn't work in the replace module

**Comment by streetster** [comment]
> Doesn't work in the replace module

Do you have an example? I was struggling to get this to work with `blockinfile`, but with trial-and-error I got it working (and then re-read the thread and understood the comments).

the `|2` means there are two spaces after the expected indentation, and then the content will take the remaining indentation. 

The following block:
```yaml
    - name:
      blockinfile:
        path: /tmp/server.xml
        marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
        #insertbefore: "</Host>"
        content: |2
                  <Valve className="org.apache.catalina.valves.RemoteIpValve"
                       internalProxies="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
                       remoteIpHeader="x-forwarded-for"
                       proxiesHeader="x-forwarded-by"
                       protocolHeader="x-forwarded-proto" />
```
creates the following in the target file:
```xml
<!-- BEGIN ANSIBLE MANAGED BLOCK -->
        <Valve className="org.apache.catalina.valves.RemoteIpValve"
             internalProxies="\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
             remoteIpHeader="x-forwarded-for"
             proxiesHeader="x-forwarded-by"
             protocolHeader="x-forwarded-proto" />
<!-- END ANSIBLE MANAGED BLOCK -->
```

**Comment by BarbzYHOOL** [comment]
Yes, I think it works in blockinfile but not in replace, I haven't verified in blockinfile but I have done it in replace.

I had no error after I followed what Sivel said, but it just resulted in 0 indentation

**Comment by simonpie** [comment]
Does not work for me with ansible 2.7.8

```yml
    - name: on insère le block de réécriture dans le https_gluu.conf
      blockinfile:
        path: /tmp/https_gluu.conf
        insertbefore: "</VirtualHost>"
        block: |8
                  #Redirection pour conserver les anciens endpoint.
                  RewriteEngine On
                  RewriteRule ^/oxauth/seam/resource/restv1/oxauth/(.*)$ /oxauth/restv1/$1 [PT]
                  RewriteRule ^/oxauth/oxauth/restv1/id$ /oxauth/restv1/id [PT]
                  RewriteRule ^/oxauth/seam/resource/restv1/introspection$ /oxauth/restv1/introspection [PT]
```

generates 

```
        ProxyPass        /.well-known/scim-configuration http://localhost:8082/identity/restv1/scim-configuration

# BEGIN ANSIBLE MANAGED BLOCK
 #Redirection pour conserver les anciens endpoint.
 RewriteEngine On
 RewriteRule ^/oxauth/seam/resource/restv1/oxauth/(.*)$ /oxauth/restv1/$1 [PT]
 RewriteRule ^/oxauth/oxauth/restv1/id$ /oxauth/restv1/id [PT]
 RewriteRule ^/oxauth/seam/resource/restv1/introspection$ /oxauth/restv1/introspection [PT]
# END ANSIBLE MANAGED BLOCK
</VirtualHost>
```
