### ISSUE TITLE
puppet module execute parameter ignored

### ISSUE THREAD

**Issue by b4ldr** [ansible/ansible#23813]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/system/puppet.py

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
ANSIBLE_NOCOWS=1
ANSIBLE_SSH_PIPLINEING=1

##### OS / ENVIRONMENT
mac osx 10.12.3

##### SUMMARY
when using the puppet module execute function a full `puppet agent -t` run is preformed instead

##### STEPS TO REPRODUCE

```yaml
- name: Disable puppet cron job
  puppet:
    execute: 'cron {"puppet_conf: Kick puppet" : ensure => absent }'
```

##### EXPECTED RESULTS
runs the following command
`puppet apply -e 'cron {"puppet_conf: Kick puppet" : ensure => absent }`

##### ACTUAL RESULTS
ran `puppet agent -t`
