### ISSUE TITLE
Cannot search for "string" in command result when using variable arrays/hashes

### ISSUE THREAD

**Issue by ichundu** [ansible/ansible#23823]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

N/A

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 21 2016, 07:16:46) [GCC 6.2.1 20160830]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I'm trying to run a command on the remote host:
```bash
grep john /etc/passwd
```
and register the result. John user parameters are declared in a variable array:
```yaml
user:
  - name: "john"
    comment: "John Lennon"
    shell: "/sbin/nologin"
```
I use the variable as follows in the command module:
```yaml
- command: "grep {{ item.name }} /etc/passwd"
  with_items: "{{ user }}"
  register: result
```
And then I try to search for a string (the user name) in the command regitered result:
```yaml
- debug:
    msg: "User exists"
  when: '"john" in result.stdout'
```
But I get a failure which is explained below.
Declaring the variables in simple format:
```yaml
key: "value"
```
fixes the problem, but I have a very big variable array and feels better to use an array in my case than split it into separate simple variables.

##### STEPS TO REPRODUCE

Run the playbook below.

```yaml
---

- hosts: localhost
  connection: local

  vars:
    user:
      - name: "john"
        comment: "John Lennon"
        shell: "/sbin/nologin"

  tasks:
    - name: Check if user exists
      command: "grep {{ item.name }} /etc/passwd"
      with_items: "{{ user }}"
      register: result
      failed_when: result.rc == 2

    - debug:
        msg: "User exists"
      when: '"john" in result.stdout'
```

##### EXPECTED RESULTS

```bash
PLAY [localhost] **********************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************
ok: [localhost]

TASK [Check if user exists] ***********************************************************************************************
changed: [localhost]

TASK [debug] **************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": "User exists"
}

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```bash
PLAY [localhost] **********************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************
ok: [localhost]

TASK [Check if user exists] ***********************************************************************************************
changed: [localhost] => (item={u'comment': u'John Lennon', u'name': u'john'})

TASK [debug] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '\"john\" in result.stdout' failed. The error was: error while evaluating conditional (\"john\" in result.stdout): Unable to look up a name or access an attribute in template string ({% if \"john\" in result.stdout %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable\n\nThe error appears to have been in '/home/john/test/site.yml': line 17, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug:\n      ^ here\n"}
	to retry, use: --limit @/home/john/test/site.retry

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```
