### ISSUE TITLE
nxos_facts only returns output when gather subset is config

### ISSUE THREAD

**Issue by davidburge1** [ansible/ansible#23828]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_facts

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

CentOS 7 connecting to Cisco Nexus5020

##### STEPS TO REPRODUCE

```yaml
---
- name: Gather Facts for NXOS devices
  hosts: all
  connection: local
  gather_facts: no
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{username}}"
      password: "{{password}}"
      transport: cli
  tasks:
  - nxos_facts:
      gather_subset: "!config"
      provider: "{{cli}}"
    register: fact_data
  - debug: var=fact_data

PLAY [Gather Facts for NXOS devices] **********************************************************************************************************************

TASK [nxos_facts] *****************************************************************************************************************************************
ok: [10.1.1.1]

TASK [debug] **********************************************************************************************************************************************
ok: [10.1.1.1] => {
    "changed": false,
    "fact_data": {
        "ansible_facts": {
            "ansible_net_all_ipv4_addresses": [],
            "ansible_net_all_ipv6_addresses": [],
            "ansible_net_filesystems": [
                "bootflash:"
            ],
            "ansible_net_gather_subset": [
                "hardware",
                "default",
                "interfaces",
                "legacy"
            ]
        },
        "changed": false
    }
}

PLAY RECAP ************************************************************************************************************************************************
10.1.1.1               : ok=2    changed=0    unreachable=0    failed=0
```

##### EXPECTED RESULTS

I expected facts to be returned and parsed into variables.

##### ACTUAL RESULTS

Output is only returned with using the config subset.  Other subsets return no results.

```
PLAYBOOK: nxos_facts.yml **********************************************************************************************************************************
1 plays in /home/DaUser/BO_NW/nxos_facts.yml

PLAY [Gather Facts for NXOS devices] **********************************************************************************************************************
META: ran handlers

TASK [nxos_facts] *****************************************************************************************************************************************
task path: /home/DaUser/BO_NW/nxos_facts.yml:15
<10.1.1.1> connection transport is cli
<10.1.1.1> socket_path: /home/DaUser/.ansible/pc/367d28af2e
open_shell() returned 0 ok
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_facts.py
<10.1.1.1> ESTABLISH LOCAL CONNECTION FOR USER: DaUser
<10.1.1.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.1.1.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/DaUser/.ansible/tmp/ansible-tmp-1492714723.96-37326569761585 `" && echo ansible-tmp-1492714723.96-37326569761585="` echo /home/DaUser/.ansible/tmp/ansible-tmp-1492714723.96-37326569761585 `" ) && sleep 0'
<10.1.1.1> PUT /tmp/tmpmZRsaz TO /home/DaUser/.ansible/tmp/ansible-tmp-1492714723.96-37326569761585/nxos_facts.py
<10.1.1.1> EXEC /bin/sh -c 'chmod u+x /home/DaUser/.ansible/tmp/ansible-tmp-1492714723.96-37326569761585/ /home/DaUser/.ansible/tmp/ansible-tmp-1492714723.96-37326569761585/nxos_facts.py && sleep 0'
<10.1.1.1> EXEC /bin/sh -c '/usr/bin/python /home/DaUser/.ansible/tmp/ansible-tmp-1492714723.96-37326569761585/nxos_facts.py; rm -rf "/home/DaUser/.ansible/tmp/ansible-tmp-1492714723.96-37326569761585/" > /dev/null 2>&1 && sleep 0'
ok: [10.1.1.1] => {
    "ansible_facts": {
        "ansible_net_all_ipv4_addresses": [],
        "ansible_net_all_ipv6_addresses": [],
        "ansible_net_filesystems": [
            "bootflash:"
        ],
        "ansible_net_gather_subset": [
            "hardware",
            "default",
            "interfaces",
            "legacy"
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "!config"
            ],
            "host": "10.1.1.1",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": {
                "gather_timeout": 60,
                "host": "10.1.1.1",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": 60,
                "transport": "cli",
                "use_ssl": null,
                "username": "DaRemoteUser",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "timeout": 60,
            "transport": "cli",
            "use_ssl": null,
            "username": "DaRemoteUser",
            "validate_certs": null
        }
    }
}

TASK [debug] **********************************************************************************************************************************************
task path: /home/DaUser/BO_NW/nxos_facts.yml:19
ok: [10.1.1.1] => {
    "changed": false,
    "fact_data": {
        "ansible_facts": {
            "ansible_net_all_ipv4_addresses": [],
            "ansible_net_all_ipv6_addresses": [],
            "ansible_net_filesystems": [
                "bootflash:"
            ],
            "ansible_net_gather_subset": [
                "hardware",
                "default",
                "interfaces",
                "legacy"
            ]
        },
        "changed": false
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ************************************************************************************************************************************************
10.1.1.1               : ok=2    changed=0    unreachable=0    failed=0
```
