### ISSUE TITLE
feature-request/Add remote_src option to synchronize or exclude option to copy

### ISSUE THREAD

**Issue by BenCoffeed** [ansible/ansible#23836]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- Files/synchronize Files/Copy

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I frequently use source repositories from either git or other hosted services and then modify files locally for specific applications. 

i.e. to install on-premise Sentry, I want to use the original source repo instead of a fork so I don't have to manage keeping the fork up to date. However, I keep a couple of configuration files in ansible and copy them over. My solution is to download the repo to the /tmp folder using the `git` module and then to copy them to my source module. This prevents me from having to use the `force: yes` argument on git and prevents re-downloading on subsequent runs when there aren't updates. 

I then use the `shell` module with a local rscync command with the --exclude options to copy over all of the files except for my two modified files. Which, will of course always run.

It would be nice to be able to leverage either the `copy` module using the `remote_src` argument and a new `exclude` option which would take a list of files and directories (denoted by trailing /). The `synchronize` module will allow passing rsync arguments. However, in this module, there does not appear to be a `remote_src` option.

##### STEPS TO REPRODUCE
Download content, modify particular file, re-run play, see if modified files are overwritten or if error is thrown. If no error is thrown, ensure that changing one of the remote files at the remote source 

```yaml
- name: Download sentry-onpremise
  git:
    repo: https://github.com/getsentry/onpremise
    dest: /opt/code/sentry
    force: yes

- name: Copy configuration file sentry.conf.py into repo
  template:
    src: sentry.conf.py.j2
    dest: /opt/code/sentry/sentry.conf.py

- name: Copy configuration file config.yml into repo
  template:
    src: config.yml.j2
    dest: /opt/code/sentry/config.yml
```

##### Desired RESULTS
A way to do this cleanly and repeatedly, only downloading/copying files when there are updates to the origin repository without overriding particular locally-modified files.

##### ACTUAL RESULTS
Since I'm modifying files in the repository, I have to set the `git` command to force. This always re-downloads the files. 

```
TASK [sentry : Download sentry-onpremise] **************************************
changed: [10.5.0.220]

TASK [sentry : Copy configuration file sentry.conf.py into repo] ***************
changed: [10.5.0.220]

TASK [sentry : Copy configuration file config.yml into repo] *******************
changed: [10.5.0.220]
```

**Comment by erwilan** [comment]
is the 'mode: pull' option of the synchronize module what you are looking for?

**Comment by BenCoffeed** [comment]
Potentially. I read the [docs](http://docs.ansible.com/ansible/synchronize_module.html) to mean that pull mode would copy items from the remote node to the host running the play.

> Specify the direction of the synchronization. In push mode the localhost or delegate is the source; In pull mode the remote host in context is the source.

The second sentence of the mentioned description seems to suggest the functionality I desire.

The name of the mode and the first sentence of the description seem to describe the behavior I assumed.

**Comment by abadger** [comment]
<nod> synchronize with appropriate rsync_opts seems like it is the way to go.  To achieve a copy from two directories on the remote side, you probably want to utilize delegate_to (For synchronize and synchronize alone, delegate_to works this way.  Most modules act differently):

```
---
- hosts: testhost
  gather_facts: False
  tasks:
  - synchronize:
      rsync_opts:
        - --exclude=excuded_file
      src: /home/badger/test
      dest: /var/tmp/
    delegate_to: '{{ inventory_hostname }}'
```

Closing this now.  If anyone has more questions feel free to ask on the mailing list or the IRC channel.  I'll paste links to those below:

List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
