### ISSUE TITLE
synchronize module doesn't work with --ask-pass, keeps asking for password

### ISSUE THREAD

**Issue by EdoBarroso** [ansible/ansible#23834]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Synchronize Module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Not changed. Installed with Homebrew for MacOS

##### OS / ENVIRONMENT

MacOS Sierra

##### SUMMARY

I'm trying to synchronize a folder to a remote host. There's no Key Authentication, so I have to enter the password before running Ansible, with --ask-pass.

Everytime a file needs to be changed, the module asks for the password. I tried to use set_remote_user: no inside the playbook, but nothing happens.

##### STEPS TO REPRODUCE

Trying to run this play inside a Playbook:

```yaml
## Update files
    - name: "Copy files to /home"
      synchronize:
        src: "files/home/"
        dest: "/home"
        set_remote_user: no
      when: "'group_name' in group_names"
      ignore_errors: yes
```

##### EXPECTED RESULTS

Folder gets synchronized

##### ACTUAL RESULTS

Can't synchronize. Keeps asking for password.

```
TASK [Copy files to /home] *****************************************************
Password: 
Password: 
Password: 
...ignoring
failed: [x.x.x.x] (item={u'path': u'files/home'}) => {"cmd": "/usr/bin/rsync --delay-updates -F --compress --dry-run --archive --rsh 'ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/Users/edobarroso/Code/path/to/home/\" \"x.x.x.x:/home\"", "failed": true, "item": {"path": "files/home"}, "msg": "Permission denied (publickey,keyboard-interactive).\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-51/rsync/io.c(453) [sender=2.6.9]\n", "rc": 12}
```

**Comment by sivel** [comment]
Closing as a duplicate of:

https://github.com/ansible/ansible/issues/14836
https://github.com/ansible/ansible/issues/16616

**Comment by EdoBarroso** [comment]
Might be obvious, but if somebody needs a workaround for this, you can try to add an SSH key and then remove it using the authorized_key module, like this:

```yaml
- name: "Add my key to authorized_keys"
      authorized_key:
        user: user
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

## Insert synchronize play here ##
- name: "remove my key from authorized_keys"
      authorized_key:
        user: user
        state: absent
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
```
