### ISSUE TITLE
host variable in provider argument ignored for persistent connection setup in 2.3

### ISSUE THREAD

**Issue by sdktr** [ansible/ansible#23854]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_command / network_cli module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/dist-packages/ansible/modules/']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
ansible.cfg contains a custom dynamic inventory, but problem can be reproduced with local host file as well
[defaults]
inventory=/mnt/c/inventory/ermainventory.ps1
gathering=explicit
transport=local
remote_user=ansible
library=/usr/lib/python2.7/dist-packages/ansible/modules/
host_key_auto_add = True

##### OS / ENVIRONMENT
WSL (Ubuntu 14.04)

##### SUMMARY
using a custom variable as the `host` parameter for the `provider` argument of the ios_command module failes in 2.3. Using a host variable or directly declared value in the playbook doesn't make a difference.
The new network debug log states seems to indicate that `ansible_host` is used when available with a fallback to `inventory_hostname`. The other `provider` variables are used correctly (authtorize, credentials etc)

##### STEPS TO REPRODUCE

```yaml
#ansible23.yml
---
- hosts: host1
  vars:
    cliprovider:
      hostname: "{{ mgmtip }}"
      host: "{{ mgmtip }}"
      username: testuser
      password: testpassword

  tasks:
    - name: view cliprovider
      debug: var=cliprovider

    - name: run show version
      ios_command:
        commands: show version
        provider: "{{ cliprovider }}"
```
```
cat host
host1 ansible_host=192.2.0.2 mgmtip=192.2.0.1
```
Enable debug
`export ANSIBLE_LOG_PATH=~/ansible.log
export ANSIBLE_DEBUG=True`

Execute playbook
`ansible-playbook ansible23.yml -i hosts -vvvv`

##### EXPECTED RESULTS
Connection setup to IP address: 192.2.0.1 using `provider `argument

##### ACTUAL RESULTS
A connection to 192.2.0.2 is attempted
```
TASK [view cliprovider]
ok: [host1] => {
    "changed": false,
    "cliprovider": {
        "host": "192.2.0.1",
        "hostname": "192.2.0.1",
        "password": "testpassword",
        "username": "testuser"
    }
}
TASK [run show version]
fatal: [host1]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell",
    "rc": 255
}
```
```
cat ~/ansible.log | grep socket
creating new control socket for host 192.2.0.2:22 as user testuser
```
