### ISSUE TITLE
EFS Name is blank when created with ansible efs module

### ISSUE THREAD

**Issue by pinkal-vansia** [ansible/ansible#23853]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

efs
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS
##### SUMMARY

I am using Ansible efs module to create AWS EFS Filesystem. File system gets created but name field is always blank.
##### STEPS TO REPRODUCE

```
---
- name: install python packages
  pip: name="{{ item }}" state=present
  with_items:
    - Jinja2
    - boto
    - boto3
    - argh

- name: Create EFS fileserver
  efs:
    state: present
    name: "TEST-fileserver-1"
    tags:
      name: "TEST-fileserver-1"
    targets:
      - subnet_id: "REMOVED"
        security_groups: [ "REMOVED" ]
    performance_mode: "general_purpose"
    region: "us-east-1"

```

##### EXPECTED RESULTS

New EFS file system created
##### ACTUAL RESULTS

New File system gets created but without Name

```
changed: [localhost] => {
    "changed": true, 
    "efs": {
        "creation_time": "2017-04-21 07:55:59+00:00", 
        "creation_token": "TEST-fileserver-1", 
        "file_system_id": "REMOVED", 
        "life_cycle_state": "available", 
        "mount_point": ".REMOVED.efs.us-east-1.amazonaws.com:/", 
        "mount_targets": [
            {
                "file_system_id": "REMOVED", 
                "ip_address": "REMOVED", 
                "life_cycle_state": "available", 
                "mount_target_id": "REMOVED", 
                "network_interface_id": "REMOVED", 
                "owner_id": "REMOVED", 
                "security_groups": [
                    "REMOVED"
                ], 
                "subnet_id": "REMOVED"
            }
        ], 
        "number_of_mount_targets": 1, 
        "owner_id": "REMOVED", 
        "performance_mode": "generalPurpose", 
        "size_in_bytes": {
            "value": 6144
        }, 
        "tags": {
            "name": "TEST-fileserver-1"
        }
    }, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "ec2_url": null, 
            "id": null, 
            "name": "TEST-fileserver-1", 
            "performance_mode": "general_purpose", 
            "profile": null, 
            "region": "us-east-1", 
            "security_token": null, 
            "state": "present", 
            "tags": {
                "name": "TEST-fileserver-1"
            }, 
            "targets": [
                {
                    "security_groups": [
                        "REMOVED"
                    ], 
                    "subnet_id": "REMOVED"
                }
            ], 
            "validate_certs": true, 
            "wait": false, 
            "wait_timeout": 0
        }, 
        "module_name": "efs"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=8    changed=1    unreachable=0    failed=0   
```
