### ISSUE TITLE
ansible git module seems not idempotent

### ISSUE THREAD

**Issue by bitfoo1** [ansible/ansible#23869]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/thielking/Documents/git/dthielking/deployment/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 21 2016, 07:16:46) [GCC 6.2.1 20160830]
```

##### CONFIGURATION
Nothing special just setting roles path

##### OS / ENVIRONMENT
OS Ansible: Arch Linux
OS Client: Debian 8

##### SUMMARY
I am using git module to clone repository on github.com. Task look like followed:
```
- name: Load local environment for users from github.com                                               
  git:                                                                                                 
    dest: "/home/{{ item.key }}/dots"                                                                  
    repo: "{{ item.value.git_repo }}"                                                                  
    recursive: yes                                                                                     
    force: no                                                                                          
  become_user: "{{ item.key }}"                                                                                                                                                               
  become: True                                                                                         
  when: item.value.git_repo is defined                                                                 
  with_dict: "{{ local_users }}" 
```
It clones my repository state is changed on ansible-playbook run 

##### EXPECTED RESULTS
If existent state is `ok`
##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @robinro
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by robinro** [comment]
Thanks for opening this issue.

Can you give a minimal working example of this issue that does not depend on other variables?
The general feature you describe works, so it might depend on the use of submodules/...
needs_info

**Comment by JimCircadian** [comment]
I just tested this, because I thought the checkout wasn't idempotent in some code I was using (the test is below, can't share the other), using CentOS7 and Ansible v2.4. All seems OK (I got stuck simply with having changed the checkout path leaving git with a destination it couldn't use...)

```
- hosts: localhost
  tasks:
  - name: Getting a repo from github
    git:
      accept_hostkey: yes
      dest: /tmp/checkoutfolder
      repo: https://github.com/JimCircadian/smtpnodes.git 
```
