### ISSUE TITLE
run_once and delegate_to affect both host and delegated host register variables

### ISSUE THREAD

**Issue by perigee** [ansible/ansible#23883]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- run_once
- delegate_to
- register

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
defaults]
host_key_checking = False
```

##### OS / ENVIRONMENT

Linux ubuntu 4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

When using `run_once` and `delegate_to`  on `shell` + `register`, the
active host and delegate_to host 's register variables will be set same
as delegate_to host.

##### STEPS TO REPRODUCE

```yaml
### Reset all docker info swarm as inactive
- name: testing only
  shell: docker swarm leave --force
  ignore_errors: yes

### Set swarm_status (value inactive)
- name: check swarm mode
  shell: docker info --format \{\{\.Swarm\.LocalNodeState\}\}
  register: swarm_status

### Set swarm manager swarm_status (value active)
- name: run only once among all
  shell: docker swarm init
  run_once: true
  delegate_to: "{{ swarm_primary['ip'] }}"

### Update swarm manager swarm_status (value active)
- name: update primary manager
  shell: docker info --format \{\{\.Swarm\.LocalNodeState\}\}
  register: swarm_status
  run_once: true
  delegate_to: "{{ swarm_primary['ip'] }}"

- debug: msg={{ swarm_status.stdout }}
```

both

- delegate_to host
- the first host in whole playbook (run_once active host)

`swarm_status` will be set to the value as on delegate_to host as `active`

##### EXPECTED RESULTS

- `swarm_status` on active host: `inactive`
- `swarm_status` on delegated host: `active`

##### ACTUAL RESULTS

- `swarm_status` on active host: `active`
- `swarm_status` on delegated host: `active`

```

```

Don't know if I were using wrong module combination or a bug. Thank you in advance.
