### ISSUE TITLE
FirewalldD Module Fails if Port is Already Opened

### ISSUE THREAD

**Issue by fia5000** [ansible/ansible#23895]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

firewalld
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT

OS Targeting, RHEL 7.3
##### STEPS TO REPRODUCE

```yaml
- name: Open Common Public Ports
  firewalld:
    port: "{{item.port}}"
    permanent: true
    state: enabled
    immediate: true
  with_items:
    - {port: '9080/tcp'}
    - {port: '9081/tcp'}
    - {port: '1443/tcp'}
```

##### EXPECTED RESULTS

Expected results would be that if the the port is already opened, the firewalld module would gracefully notice that the port is already opened and skip the task. 

##### ACTUAL RESULTS

```
failed: [CPE-1] (item={u'port': u'9080/tcp'}) => {"failed": true, "item": {"port": "9080/tcp"}, "msg": "ERROR: Exception caught: ALREADY_ENABLED: '9080:tcp'"}
failed: [ICN-2] (item={u'port': u'1080/tcp'}) => {"failed": true, "item": {"port": "9081/tcp"}, "msg": "ERROR: Exception caught: org.fedoraproject.FirewallD1.Exception: ALREADY_ENABLED: '9081:tcp' already in 'public'"}
```
