### ISSUE TITLE
sysctl module fails to unset variable if value is empty

### ISSUE THREAD

**Issue by caio2k** [ansible/ansible#23905]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
sysctl

##### ANSIBLE VERSION
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
default settings

##### OS / ENVIRONMENT
Host: Debian 9
Target: Centos 7

##### SUMMARY
When running task with `state=absent` and `value={{ not_defined_variable | default(omit) }}` or `value` is not specified, sysctl fails

##### STEPS TO REPRODUCE
playbook 1
```
- name: update sysctl
  sysctl:
    name: '{{ item.key }}'
    value: '{{ item.value | default(omit) }}'
    sysctl_set: yes
    state: '{{ item.state | default("present")}}'
    reload: yes
  with_items:
    - { key: 'net.ipv4.ip_forward',                        value: '1' }  #needed by docker
    - { key: 'net.ipv4.conf.all.forwarding',               state: 'absent' } #disabled as it affects docker 
```
playbook 2
```
- name: update sysctl
  sysctl:
    name: '{{ item.key }}'
    sysctl_set: yes
    state: '{{ item.state | default("present")}}'
    reload: yes
    value: "0"
  with_items:
    - { key: 'net.ipv4.conf.all.forwarding',               state: 'absent' } #disabled as it affects docker 
```

##### EXPECTED RESULTS
Success :)

##### ACTUAL RESULTS
playbook 1
```
ok: [XXX] => (item={u'value': u'1', u'key': u'net.ipv4.ip_forward'}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "ignoreerrors": false, 
            "name": "net.ipv4.ip_forward", 
            "reload": true, 
            "state": "present", 
            "sysctl_file": "/etc/sysctl.conf", 
            "sysctl_set": true, 
            "value": "1"
        }, 
        "module_name": "sysctl"
    }, 
    "item": {
        "key": "net.ipv4.ip_forward", 
        "value": "1"
    }
}

failed: [XXX] (item={u'state': u'absent', u'key': u'net.ipv4.conf.all.forwarding'}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "ignoreerrors": false, 
            "name": "net.ipv4.conf.all.forwarding", 
            "reload": true, 
            "state": "absent", 
            "sysctl_file": "/etc/sysctl.conf", 
            "sysctl_set": true, 
            "value": ""
        }, 
        "module_name": "sysctl"
    }, 
    "item": {
        "key": "net.ipv4.conf.all.forwarding", 
        "state": "absent"
    }, 
    "msg": "setting net.ipv4.conf.all.forwarding failed: sysctl: malformed setting \"net.ipv4.conf.all.forwarding=\"\n"
}
```
playbook 2
```
failed: [XXX] (item={u'state': u'absent', u'key': u'net.ipv4.conf.all.forwarding'}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "ignoreerrors": false, 
            "name": "net.ipv4.conf.all.forwarding", 
            "reload": true, 
            "state": "absent", 
            "sysctl_file": "/etc/sysctl.conf", 
            "sysctl_set": true, 
            "value": ""
        }, 
        "module_name": "sysctl"
    }, 
    "item": {
        "key": "net.ipv4.conf.all.forwarding", 
        "state": "absent"
    }, 
    "msg": "setting net.ipv4.conf.all.forwarding failed: sysctl: malformed setting \"net.ipv4.conf.all.forwarding=\"\n"
}
```

**Comment by ansibot** [comment]
cc @davixx
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fridim** [comment]
The issue is the param <code>sysctl_set</code> that triggers a <code>sysctl -w</code> command with no value.

this works :
```yaml
- name: update sysctl
  become: yes
  sysctl:
    name: vm.swappiness
    value: 40
    sysctl_set: yes
    state: present
    reload: yes
    sysctl_file: /tmp/test_sysctl.conf

- name: update sysctl
  become: yes
  sysctl:
    name: vm.swappiness
    sysctl_file: /tmp/test_sysctl.conf
    state: absent
    reload: yes
```

and this does not:
```yaml
- name: update sysctl
  become: yes
  sysctl:
    name: vm.swappiness
    sysctl_set: yes
    sysctl_file: /tmp/test_sysctl.conf
    state: absent
    reload: yes
```

I'm not sure it's a bug.
If you specify <code>state: absent</code>, you actually mean: absent from the conf file.

Using <code>state: absent</code> and <code>sysctl_set: yes</code> at the same time could eventually mean : "restore this value to default", like after a reboot. But it's not the case.

There is no built-in option for the sysctl shell command to "reset this specific option to default". This cannot be  simulated _in a simple way_ by ansible because it's absent "by design" in sysctl. To my knowledge there is no easy and built-in way to get the default value for a sysctl option when it's not in the conf file (at least for linux).

And i don't think we can ignore the sysctl_set param when used with <code>state: absent</code>, because the user would expect it to be effective once the task is executed.


Maybe we could raise a warning when both <code>state: absent</code> and <code>sysctl_set: yes</code> are used ?
