### ISSUE TITLE
'utf8' codec can't decode byte 0xff in position 0: invalid start byte"

### ISSUE THREAD

**Issue by windowsansiblernew** [ansible/ansible#23903]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lookup
##### ANSIBLE VERSION

```
2.3.0.0
```

##### SUMMARY

Getting the error "'utf8' codec can't decode byte 0xff in position 0: invalid start byte" when a compressed json is being called by lookup plugin
##### STEPS TO REPRODUCE

```yaml
    - name: read local file
      set_fact:
       reg_changes: "{{ lookup('file', '/home/tess/xl.json') | from_json }}"                    
      delegate_to: localhost
```

##### EXPECTED RESULTS

Json file should be parsed

##### ACTUAL RESULTS

```
'utf8' codec can't decode byte 0xff in position 0: invalid start byte"
```
