### ISSUE TITLE
copy module doesn't handle symlinks and empty directories

### ISSUE THREAD

**Issue by mario-pranjic** [ansible/ansible#23902]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME

copy module
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/student/kubernetes/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

When using copy module, and there are symlinks on src, it will create copy of a file/dir in dest instead of creating a symlink.
Also, if there is a directory on src with no files/dirs in it, it will not be copied at all.

##### STEPS TO REPRODUCE

```
-rw-rw-r--. 1 student student  4 Apr 24 06:19 a
-rw-rw-r--. 1 student student  4 Apr 24 06:19 b
lrwxrwxrwx. 1 student student  1 Apr 24 06:19 c -> a
drwxrwxr-x. 2 student student 14 Apr 24 06:59 d
drwxrwxr-x. 2 student student  6 Apr 24 10:46 g
lrwxrwxrwx. 1 student student  1 Apr 24 10:52 x -> d
```
Directory "g" is an empty directory.

```yaml
- hosts: kub-master
  tasks:
    - name: Copy website directories
      copy:
        src: files/www
        dest: /tmp/test
        owner: root
        group: root
```

##### EXPECTED RESULTS

Expecting to get dest = src.

##### ACTUAL RESULTS

On dest side, symlinks are handled as copies of files/dirs.
Empty dirs are not handled at all.

If copy module is designed to ignore empty dirs and not handle symlinks, this should be written  in Note on http://docs.ansible.com/ansible/copy_module.html

```

```
