### ISSUE TITLE
parted module does not resize partitions

### ISSUE THREAD

**Issue by kwohlfahrt** [ansible/ansible#23914]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
parted module

##### ANSIBLE VERSION
```
ansible 2.4.0
```

##### OS / ENVIRONMENT
Debian Stretch

##### SUMMARY
Partitions are kept unchanged (and an OK result is reported), even if the size of the partition in the play is different to the actual size. This continues from discussions in #22996 and #23411 

##### STEPS TO REPRODUCE
Run the following task:

```yaml
- name: Create EFI partitions
  become: yes
  parted:
    label: gpt
    state: present
    device: /dev/vda
    part_start: 0%
    part_end: 512MiB
    number: 1
    name: EFI
```

Then, run the following (note the changed `part_end`):
```yaml
- name: Create EFI partitions
  become: yes
  parted:
    label: gpt
    state: present
    device: /dev/vda
    part_start: 0%
    part_end: 1024MiB
    number: 1
    name: EFI
```

##### EXPECTED RESULTS
The result after the first play is correct:
```
changed: [vm] => {"changed": true, "disk": {"dev": "/dev/vda", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 10485760.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 524288.0, "flags": [], "fstype": "", "name": "EFI", "num": 1, "size": 523264.0, "unit": "kib"}], "script": "unit KiB mklabel gpt mkpart primary 0% 512MiB unit KiB name 1 EFI"}
```

After the second, I expect to see:
```
changed: [vm] => {"changed": true, "disk": {"dev": "/dev/vda", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 10485760.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 1048576.0, "flags": [], "fstype": "", "name": "EFI", "num": 1, "size": 1047552.0, "unit": "kib"}], "script": "unit KiB mkpart primary 0% 1024MiB unit KiB name 1 EFI"}
```

##### ACTUAL RESULTS

I see the following output after running the second task, and the partition is not changed.
```
ok: [vm] => {"changed": false, "disk": {"dev": "/dev/vda", "logical_block": 512, "model": "Virtio Block Device", "physical_block": 512, "size": 10485760.0, "table": "gpt", "unit": "kib"}, "partitions": [{"begin": 1024.0, "end": 524288.0, "flags": [], "fstype": "", "name": "EFI", "num": 1, "size": 523264.0, "unit": "kib"}], "script": ""}
```

**Comment by ansibot** [comment]
cc @ColOfAbRiX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fridim** [comment]
Thanks for reporting.
Indeed, current implementation just look at the partition number. I don't know if it's an intended fail-safe or not. Because this bring questions like: "what to do if you increase the size of the partition and it overlaps the next one ? delete and recreate both ?"
With the current code you will need to explicitly delete the partition with <code>state: absent</code> and then recreate it with new size.
I'll let others step in regarding this behavior.

I tried to find the answer in the tests, but there are none for this module. So i link here the PR to add tests to parted (a start at least) : #24164 
(it can't be a bad idea to have tests before potentially changing this module)

**Comment by kwohlfahrt** [comment]
Sure. I think a safe behaviour would be to extend the partition if the space after is free (this shouldn't do anything to the filesystem, which would have to be resized separately), and to error otherwise.

**Comment by ColOfAbRiX** [comment]
My choice was to keep things simple, avoid any manipulation and just provide the parted functionalities as they are. In this situation it would be up to the user to decide what to do.

Maybe the behaviour that @kwohlfahrt is looking for should be implemented using LVM: I'm actually finding myself in the same scenario, a template VM with minimal disk plus an additional disk that I partition and add to a volume group.

**Comment by Lekensteyn** [comment]
LVM is not needed for simple scenarios. In my case there is a single partition (`/dev/vda1`) which should grow occupy the full, expanded disk.

Looking at the current implementation, the dimensions are only taken into account when creating a partition, it won't modify an existing one. Playbook example:

```
---
- hosts: buildbot-workers
  become: yes
  vars:
    dev: /dev/vda
    part: 1
  tasks:
    # Check for device name in QMP/HMP with:  info block
    # Then resize the virtio disk with:       block_resize virtio0 12G
    - name: install apt packages
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - parted
        - e2fsprogs
    - name: grow partition until maximum
      parted:
        device: "{{dev}}"
        number: "{{part}}"
        state: present
    - name: grow filesystem until maximum block size
      filesystem:
        fstype: ext4
        dev: "{{dev}}{{part}}"
        resizefs: yes
```

I came up with this hack instead... Using parted 3.2-15 on Ubuntu 16.04. At least it is idempotent, it also only works when there is a single partition.
```
---
- hosts: buildbot-workers
  become: yes
  vars:
    dev: /dev/vda
    part: 1
    max_gap_kb: 1024
  tasks:
    # Check for device name in QMP/HMP with:  info block
    # Then resize the virtio disk with:       block_resize virtio0 12G
    - name: install apt packages
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - parted
        - e2fsprogs
    - name: partition info
      parted:
        device: "{{dev}}"
        number: "{{part}}"
      register: partinfo
    - set_fact:
        gap_kb: "{{partinfo.disk.size - partinfo.partitions[vars.part-1].end}}"
    - debug: 'msg="Gap after partition {{part}}: {{gap_kb}}kiB"'
    # parted does not resize: https://github.com/ansible/ansible/issues/23914
    - name: grow too small partition to maximum
      # Request resize, ack resize of partition that is in use (when requested).
      # https://bugs.launchpad.net/ubuntu/+source/parted/+bug/1270203
      # https://unix.stackexchange.com/a/365657
      command: 'parted ---pretend-input-tty {{dev}} resizepart {{part}} Yes 100%'
      when: max_gap_kb < gap_kb|int
    - name: grow filesystem until maximum block size
      filesystem:
        fstype: ext4
        dev: "{{dev}}{{part}}"
        resizefs: yes
```
