### ISSUE TITLE
nxos_aaa_server fails when using transport nxapi

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#23924]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_aaa_server

##### NXOS VERSION
7.0(3)I5(1)

##### ANSIBLE VERSION
```
ansible 2.3.0.0 (detached HEAD d56ba0945d) last updated 2017/04/24 15:14:00 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT
running on OSX

##### STEPS TO REPRODUCE
```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  user_ssl: no

---
- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: "Radius Server Basic settings"
    nxos_aaa_server:
      server_type: radius
      server_timeout: 9
      deadtime: 20
      directed_request: enabled
      provider: "{{ nxapi }}"
```

##### EXPECTED RESULTS
Expect radius server to be configured properly.

**NOTE:** If the provider is changed to `cli` the module works as expected.

##### ACTUAL RESULTS
```
$ansible-playbook -i /etc/ansible/hosts ../ap/test_nxos_aaa_server.yaml -vvvv
No config file found; using defaults
Loading callback plugin default of type stdout, v2.0 from /Users/mwiebe/Projects/nxos_ansible/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test_nxos_aaa_server.yaml *************************************************************************************************************************************************************
1 plays in ../ap/test_nxos_aaa_server.yaml

PLAY [nxos] *************************************************************************************************************************************************************************************
META: ran handlers

TASK [Radius Server Basic settings] *************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/ap/test_nxos_aaa_server.yaml:7
<n9k> connection transport is nxapi
Using module file /Users/mwiebe/Projects/nxos_ansible/ansible/lib/ansible/modules/network/nxos/nxos_aaa_server.py
<n9k> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1493061611.5-113321328876848 `" && echo ansible-tmp-1493061611.5-113321328876848="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1493061611.5-113321328876848 `" ) && sleep 0'
<n9k> PUT /var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/tmpJfs3Bz TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1493061611.5-113321328876848/nxos_aaa_server.py
<n9k> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1493061611.5-113321328876848/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1493061611.5-113321328876848/nxos_aaa_server.py && sleep 0'
<n9k> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1493061611.5-113321328876848/nxos_aaa_server.py; rm -rf "/Users/mwiebe/.ansible/tmp/ansible-tmp-1493061611.5-113321328876848/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_NUjHWg/ansible_module_nxos_aaa_server.py", line 382, in <module>
    main()
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_NUjHWg/ansible_module_nxos_aaa_server.py", line 321, in main
    existing = get_aaa_server_info(server_type, module)
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_NUjHWg/ansible_module_nxos_aaa_server.py", line 196, in get_aaa_server_info
    split_server = server_body.splitlines()
AttributeError: 'dict' object has no attribute 'splitlines'

fatal: [n9k]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_NUjHWg/ansible_module_nxos_aaa_server.py\", line 382, in <module>\n    main()\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_NUjHWg/ansible_module_nxos_aaa_server.py\", line 321, in main\n    existing = get_aaa_server_info(server_type, module)\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_NUjHWg/ansible_module_nxos_aaa_server.py\", line 196, in get_aaa_server_info\n    split_server = server_body.splitlines()\nAttributeError: 'dict' object has no attribute 'splitlines'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/Users/mwiebe/Projects/nxos_ansible/ap/test_nxos_aaa_server.retry

PLAY RECAP **************************************************************************************************************************************************************************************
n9k          : ok=0    changed=0    unreachable=0    failed=1   
```

#####  RESULTS USING CLI PROVIDER
```
$ansible-playbook -i /etc/ansible/hosts ../ap/test_nxos_aaa_server.yaml 

PLAY [nxos] *************************************************************************************************************************************************************************************

TASK [Radius Server Basic settings] *************************************************************************************************************************************************************
ok: [n9k]

PLAY RECAP **************************************************************************************************************************************************************************************
n9k          : ok=1    changed=0    unreachable=0    failed=0   

```
