### ISSUE TITLE
nxos_acl fails for both cli and nxapi transports

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#23928]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_acl

##### NXOS VERSION
7.0(3)I5(1)

##### ANSIBLE VERSION
```
ansible 2.3.0.0 (detached HEAD d56ba0945d) last updated 2017/04/24 15:14:00 (GMT -400)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT
running on OSX

##### STEPS TO REPRODUCE
```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  user_ssl: no

---
- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: "Acl Configuration"
    nxos_acl:
      name: TEST_ACL
      seq: 10
      action: permit
      proto: tcp
      src: 1.1.1.1/24
      dest: any
      state: present
      provider: "{{ cli }}"
      #provider: "{{ nxapi }}"
```

##### EXPECTED RESULTS
Expect acl to be configured properly.

##### ACTUAL RESULTS
Same results using `cli` or `nxapi` transport
```
$ansible-playbook -i /etc/ansible/hosts ../ap/test_nxos_acl.yaml -vvvv
No config file found; using defaults
Loading callback plugin default of type stdout, v2.0 from /Users/mwiebe/Projects/nxos_ansible/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test_nxos_acl.yaml ********************************************************************************************************************************************************************
1 plays in ../ap/test_nxos_acl.yaml

PLAY [nxos] *************************************************************************************************************************************************************************************
META: ran handlers

TASK [Acl Configuration] ************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/ap/test_nxos_acl.yaml:7
<n9k.example.com> connection transport is cli
<n9k.example.com> socket_path: /Users/mwiebe/.ansible/pc/30512dd245
open_shell() returned 0 ok 
Using module file /Users/mwiebe/Projects/nxos_ansible/ansible/lib/ansible/modules/network/nxos/nxos_acl.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1493062947.94-271522979556261 `" && echo ansible-tmp-1493062947.94-271522979556261="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1493062947.94-271522979556261 `" ) && sleep 0'
<n9k.example.com> PUT /var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/tmpr0hk6N TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1493062947.94-271522979556261/nxos_acl.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1493062947.94-271522979556261/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1493062947.94-271522979556261/nxos_acl.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1493062947.94-271522979556261/nxos_acl.py; rm -rf "/Users/mwiebe/.ansible/tmp/ansible-tmp-1493062947.94-271522979556261/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_GvaNyM/ansible_module_nxos_acl.py", line 601, in <module>
    main()
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_GvaNyM/ansible_module_nxos_acl.py", line 586, in main
    new_existing_core, end_state, seqs = get_acl(module, name, seq)
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_GvaNyM/ansible_module_nxos_acl.py", line 287, in get_acl
    temp = collections.OrderedDict()
NameError: global name 'collections' is not defined

fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_GvaNyM/ansible_module_nxos_acl.py\", line 601, in <module>\n    main()\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_GvaNyM/ansible_module_nxos_acl.py\", line 586, in main\n    new_existing_core, end_state, seqs = get_acl(module, name, seq)\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_GvaNyM/ansible_module_nxos_acl.py\", line 287, in get_acl\n    temp = collections.OrderedDict()\nNameError: global name 'collections' is not defined\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/Users/mwiebe/Projects/nxos_ansible/ap/test_nxos_acl.retry

PLAY RECAP **************************************************************************************************************************************************************************************
n9k.example.com          : ok=0    changed=0    unreachable=0    failed=1   

```
