### ISSUE TITLE
make tags be specifiable by a string or comma seperated string, not just a list

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#2394]
Let the code example speak for itself:

``` yaml
serge@cyberlab:~/tmp$ cat testtag.yml 

---
- name: test tags
  hosts: all
  tags: test1
  gather_facts: false
  tasks:
  - local_action: debug

serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=doesnotextist
ERROR: tag(s) not found in playbook: doesnotextist.  possible values: 1,e,s,t

serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=test1
ERROR: tag(s) not found in playbook: test1.  possible values: 1,e,s,t

serge@cyberlab:~/tmp$ cat testtag.yml 

---
- name: test tags
  hosts: all
  tags: 
  - test1
  gather_facts: false
  tasks:
  - local_action: debug

serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=doesnotextist
ERROR: tag(s) not found in playbook: doesnotextist.  possible values: test1

serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=test1
PLAY [test tags] ********************* 

TASK: [debug] ********************* 
ok: [localhost]

PLAY RECAP ********************* 
localhost                      : ok=1    changed=0    unreachable=0    failed=0

serge@cyberlab:~/tmp$ 
```

The inline tag notation does work on task level:

``` yaml
serge@cyberlab:~/tmp$ cat testtag.yml 

---
- name: test tags
  hosts: all
  gather_facts: false
  tasks:
  - local_action: debug
    tags: test1
serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=doesnotexist
ERROR: tag(s) not found in playbook: doesnotexist.  possible values: test1
serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=test1

PLAY [test tags] ********************* 

TASK: [debug] ********************* 
ok: [localhost]

PLAY RECAP ********************* 
localhost                      : ok=1    changed=0    unreachable=0    failed=0 
```

Putting two tags inline does not work, though I'm not sure this is supposed to work:

``` yaml
serge@cyberlab:~/tmp$ cat testtag.yml 

---
- name: test tags
  hosts: all
  gather_facts: false
  tasks:
  - local_action: debug
    tags: test1, test2
serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=test2
ERROR: tag(s) not found in playbook: test2.  possible values: test1, test2
serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=test1
ERROR: tag(s) not found in playbook: test1.  possible values: test1, test2
```

And for the sake of completeness:

``` yaml
serge@cyberlab:~/tmp$ cat testtag.yml 

---
- name: test tags
  hosts: all
  gather_facts: false
  tags: test1, test2
  tasks:
  - local_action: debug
serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=test1
ERROR: tag(s) not found in playbook: test1.  possible values:  ,,,1,2,e,s,t
serge@cyberlab:~/tmp$ ansible-playbook -i localhost, testtag.yml --tags=test2
ERROR: tag(s) not found in playbook: test2.  possible values:  ,,,1,2,e,s,t
```
