### ISSUE TITLE
Copy module shows 'changed' in check mode

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#23955]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
copy

##### ANSIBLE VERSION
```
2.3.0.0
```
##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### SUMMARY
When using the `copy` module to copy a file into a directory on the target system, the check mode yields `changed` though there is no change on the target system. The problem only occurs if the path
is given **without trailing slash**.

##### STEPS TO REPRODUCE
Call in check mode after file exists:

```yaml

- name: copy file
  copy:
    src=myfile
    dest=/path/to/folder
```

##### EXPECTED RESULTS
`changed: false`

##### ACTUAL RESULTS
`changed: true`

This effect does not occur if `dest` is given with a trailing slash:

```
- name: copy file
  copy:
    src=myfile
    dest=/path/to/folder/
```

**Comment by fridim** [comment]
modules supporting check mode will report what changes they would have made rather than making them. Check mode is a simulation.

So <code>changed: true</code> is expected here.

I could not reproduce the second behavior with 'tailing slash' with 2.4.0. Both versions, with or without trailing slash, return <code>changed: true</code>.

**Comment by fridim** [comment]
@profhase i'm sorry, i could not reproduce with 2.3.0 neither, i still have <code>changed: true</code> for both versions with or without trailing slash. Can you provide more details ?

I tried this with <code>--check</code> mode :
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
          - name: copy file
            copy:
                    src=myfile
                    dest=/tmp/foo/
          - name: copy file
            copy:
                    src=myfile
                    dest=/tmp/foo
          - name: copy file
            copy:
                    src: myfile
                    dest: /tmp/foo/
          - name: copy file
            copy:
                    src: myfile
                    dest: /tmp/foo
```
