### ISSUE TITLE
Lambda Event: Function ARN is limited to 64 characters in length.

### ISSUE THREAD

**Issue by rhumie** [ansible/ansible#23959]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lambda_event module

##### ANSIBLE VERSION

N/A

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The module has `lambda_function_arn` parameter representing a name or ARN of the lambda function.

If this parameter is the name of function, it must be 64 characters or less.
On the other hand, if this parameter is the ARN of the lambda function, it must be 140 characters or less.
[cf. AWS API Reference](http://docs.aws.amazon.com/ja_jp/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-FunctionName)

However, in either case the validation check fails if it is 64 characters or less.
The corresponding source code is as follows.
https://github.com/ansible/ansible/blob/eb1214baad0cbe2c4b7304caebb9ae1c7dc0d8db/lib/ansible/modules/cloud/amazon/lambda_event.py#L233

##### STEPS TO REPRODUCE

```
lambda_event:
  state: "{{ state | default('present') }}"
  event_source: stream
  function_name: arn:aws:lambda:ap-northeast-1:123456789012:function:LAMBDA-FUNCTION-NAME
  alias: Dev
  source_params:
    source_arn: arn:aws:kinesis:ap-northeast-1:123456789012:stream/STREAM-NAME
    enabled: yes
    batch_size: 100
    starting_position: TRIM_HORIZON
```

```yaml

```

##### EXPECTED RESULTS

Play should run without errors.

##### ACTUAL RESULTS

```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "alias": "Dev", 
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "ec2_url": null, 
            "event_source": "stream", 
            "lambda_function_arn": "arn:aws:lambda:ap-northeast-1:123456789012:function:LAMBDA-FUNCTION-NAME", 
            "profile": null, 
            "region": null, 
            "security_token": null, 
            "source_params": {
                "batch_size": 100, 
                "enabled": true, 
                "source_arn": "arn:aws:kinesis:ap-northeast-1:123456789012:stream/STREAM-NAME", 
                "starting_position": "TRIM_HORIZON"
            }, 
            "state": "present", 
            "validate_certs": true, 
            "version": 0
        }
    }, 
    "msg": "Function name \"arn:aws:lambda:ap-northeast-1:123456789012:function:LAMBDA-FUNCTION-NAME\" exceeds 64 character limit"
}
```
