### ISSUE TITLE
junos_config fails if config format is xml

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#23960]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_config

##### ANSIBLE VERSION

```
2.3
```

##### STEPS TO REPRODUCE
```
Create a file with junos config in xml format
$ cat junos_config.xml
<interfaces>
    <interface>
        <name>ae11</name>
        <unit>
            <name>0</name>
            <description>Test</description>
        </unit>
    </interface>
</interfaces>
```
-->

```yaml
  - name: Run junos_config
    junos_config:
      src:  junos_config.xml
      comment: update config
      host: "{{ ansible_ssh_host }}"
      username: "{{ juniper_user }}"
      password: "{{ juniper_passwd }}"
```

##### EXPECTED RESULTS

Run should configure interface on device
##### ACTUAL RESULTS

Fails with error message.

```
 "msg": "<?xml version=\"1.0\" encoding=\"UTF-8\"?><rpc-error xmlns=\"urn:ietf:params:xml:ns:netconf:base:1.0\" xmlns:junos=\"http://xml.juniper.net/junos/15.1X49/junos\" xmlns:nc=\"urn:ietf:params:xml:ns:netconf:base:1.0\">\n<error-type>protocol</error-type>\n<error-tag>operation-failed</error-tag>\n<error-severity>error</error-severity>\n<error-message>syntax error, expecting &lt;/configuration&gt;</error-message>\n<error-info>\n<bad-element>&lt;interfaces&gt;\n    &lt;interface&gt;\n        &lt;name&gt;ae11&lt;/name&gt;\n        &lt;unit&gt;\n            &lt;name&gt;0&lt;/name&gt;\n            &lt;description&gt;Test&lt;/description&gt;\n        &lt;/unit&gt;\n    &lt;/interface&gt;\n&lt;/interfaces&gt;</bad-element>\n</error-info>\n</rpc-error>\n"
```
