### ISSUE TITLE
Some kind of Syntax Error in Replace module 

### ISSUE THREAD

**Issue by JorgeSivil** [ansible/ansible#23968]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

replace

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
Using Python 3 in the target host. (ansible_python_interpreter: /usr/bin/python3)

##### SUMMARY
The regex does not seem to support single quote, even escaped ones.

##### STEPS TO REPRODUCE
```
replace:
    path: "{{ drupal.install_dir }}/{{ drupal.project_name }}/sites/default/settings.php"
    regexp: '(\s+)(\'database\' => \'{{ drupal.database_name }}\',)$'
    replace: '\1\2\n\1\'charset\' => \'utf8mb4\',\n\1\'collation\' => \'utf8mb4_unicode_ci\','
```

The error:
```
The offending line appears to be:
path: "{{ drupal.install_dir }}/{{ drupal.project_name }}/sites/default/settings.php"
regexp: '(\s+)(\'database\' => \'{{ drupal.database_name }}\',)$'
                 ^ here
```
In the column 26 (the 'd' of 'database')

My workaround was to use:

```
replace:
        path: "{{ drupal.install_dir }}/{{ drupal.project_name }}/sites/default/settings.php"
        regexp: '^(\s+)(\x27database\x27 => \x27{{ drupal.database_name }}\x27,)$'
        replace: '\1\2\n\1"charset" => "utf8mb4",\n\1"collation" => "utf8mb4_general_ci",'
```

Stack Overflow post: http://stackoverflow.com/questions/43610578/strange-error-in-ansible-regarding-regex/43611123#43611123

**Comment by ansibot** [comment]
cc @EvanK
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by EvanK** [comment]
@JorgeSivil This looks like a restriction of the YAML format that ansible uses (before the module itself is invoked).

Essentially, **you cannot escape single quotes with a backslash**...instead you must use another single quote:

```yml
replace:
    path: "{{ drupal.install_dir }}/{{ drupal.project_name }}/sites/default/settings.php"
    regexp: '(\s+)(''database'' => ''{{ drupal.database_name }}'',)$'
    replace: '\1\2\n\1''charset'' => ''utf8mb4'',\n\1''collation'' => ''utf8mb4_unicode_ci'','
```
