### ISSUE TITLE
Ansible Module pamd status already changed

### ISSUE THREAD

**Issue by xoxys** [ansible/ansible#23963]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - ansible/lib/ansible/modules/system/pamd.py

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### OS / ENVIRONMENT
Debian 8.7

##### SUMMARY
The pamd module reports already "changed" if i try to change some module arguments from pam.d/system-auth

##### STEPS TO REPRODUCE

I use the following two tasks both reports changed while the file on the target system not changed (because it is the same). If i use only on item at module_arguments all works fine (status changed/ok is correct)
```yaml
- name: hardening auth pam_unix.so
  pamd:
    name: system-auth
    type: auth
    module_path: pam_unix.so
    control: sufficient
    module_arguments: 'nullok try_first_pass'

- name: hardening password pam_unix.so
  pamd:
    name: system-auth
    type: password
    control: sufficient
    module_path: pam_unix.so
    module_arguments: 'sha512 shadow try_first_pass use_authtok'

```

##### ACTUAL RESULTS
```
TASK [pam : hardening password pam_unix.so] ************************************************************************************************************************************
task path: /home/ansible/roles/pam/tasks/system-auth.yml:11
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/pamd.py
<192.168.0.54> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.54> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ansible/.ssh/ansible"' -o User=root -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/ansible/.ansible/cp/67be250705 192.168.0.54 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.0.54> (0, '/root\n', '')
<192.168.0.54> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.54> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ansible/.ssh/ansible"' -o User=root -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/ansible/.ansible/cp/67be250705 192.168.0.54 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322 `" && echo ansible-tmp-1493117456.41-10799670326322="` echo /root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322 `" ) && sleep 0'"'"''
<192.168.0.54> (0, 'ansible-tmp-1493117456.41-10799670326322=/root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322\n', '')
<192.168.0.54> PUT /tmp/tmpvoCuLy TO /root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322/pamd.py
<192.168.0.54> SSH: EXEC sshpass -d12 sftp -o BatchMode=no -b - -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ansible/.ssh/ansible"' -o User=root -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/ansible/.ansible/cp/67be250705 '[192.168.0.54]'
<192.168.0.54> (0, 'sftp> put /tmp/tmpvoCuLy /root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322/pamd.py\n', '')
<192.168.0.54> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.54> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ansible/.ssh/ansible"' -o User=root -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/ansible/.ansible/cp/67be250705 192.168.0.54 '/bin/sh -c '"'"'chmod u+x /root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322/ /root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322/pamd.py && sleep 0'"'"''
<192.168.0.54> (0, '', '')
<192.168.0.54> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.0.54> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="/home/ansible/.ssh/ansible"' -o User=root -o ConnectTimeout=10 -o StrictHostKeyChecking=no -o ControlPath=/home/ansible/.ansible/cp/67be250705 -tt 192.168.0.54 '/bin/sh -c '"'"'/usr/bin/python /root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322/pamd.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1493117456.41-10799670326322/" > /dev/null 2>&1 && sleep 0'"'"''
<192.168.0.54> (0, '\r\n{"invocation": {"module_args": {"control": "sufficient", "new_module_path": null, "name": "system-auth", "dest": "/etc/pam.d/system-auth", "module_path": "pam_unix.so", "new_type": null, "state": "updated", "new_control": null, "path": "/etc/pam.d", "type": "password", "module_arguments": ["sha512 shadow try_first_pass use_authtok"]}}, "changed": true, "ansible_facts": {"pamd": {"changed": true, "result": {"action": "update_rule", "change_count": 1, "updated_rule_0": "password  \\tsufficient\\tpam_unix.so sha512 shadow try_first_pass use_authtok", "new_rule": "None      \\tNone\\tNone sha512 shadow try_first_pass use_authtok"}}}}\r\n', 'Shared connection to 192.168.0.54 closed.\r\n')
changed: [test.example.com] => {
    "ansible_facts": {
        "pamd": {
            "changed": true, 
            "result": {
                "action": "update_rule", 
                "change_count": 1, 
                "new_rule": "None      \tNone\tNone sha512 shadow try_first_pass use_authtok", 
                "updated_rule_0": "password  \tsufficient\tpam_unix.so sha512 shadow try_first_pass use_authtok"
            }
        }
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "control": "sufficient", 
            "dest": "/etc/pam.d/system-auth", 
            "module_arguments": [
                "sha512 shadow try_first_pass use_authtok"
            ], 
            "module_path": "pam_unix.so", 
            "name": "system-auth", 
            "new_control": null, 
            "new_module_path": null, 
            "new_type": null, 
            "path": "/etc/pam.d", 
            "state": "updated", 
            "type": "password"
        }
    }
}
META: ran handlers
META: ran handlers
```

**Comment by geeww** [comment]
I also see the same behaviour on RHEL7.3. I tried with state: updated and state: args_present with the same result. 
It seems that the args_present state must be used with only one item at a time, so as a workaround, you can do the following which was idempotent in my testing

```yaml
- name:                hardening auth pam_unix.so
  pamd:
    name:              system-auth
    type:              auth
    module_path:       pam_unix.so
    control:           sufficient
    module_arguments:  "{{ item }}"
    state:             args_present
  with_items:
    - nullok
    - try_first_pass
```
