### ISSUE TITLE
mysql_replication does not allow setting blank values

### ISSUE THREAD

**Issue by JoelFeiner** [ansible/ansible#23976]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module: mysql_replication

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/XXX/..../ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When setting properties to an empty string, the module treats those properties as not being specified at all, so they won't be blanked out on the server. For example, if I want to remove SSL certificates because the connection no longer requires SSL, setting the various ssl properties to an empty string does not result in any change to the slave's configuration. The module ignores the properties with empty strings entirely.

I looked in the source and it appears that the module checks each property for truthiness before making a change, and since empty strings are falsy, properties with them fail the checks for updates.

##### STEPS TO REPRODUCE
```yaml
- name: Change master (Slave)
  mysql_replication:
    mode: changemaster
    master_host: '{{ DATABASE_MASTER_IP_ADDRESS }}'
    master_port: '{{ DATABASE_MASTER_PORT }}'
    master_user: '{{ DATABASE_REPLICATION_USERNAME }}'
    master_password: '{{ DATABASE_REPLICATION_PASSWORD }}'
    master_ssl: "{{ 1 if DATABASE_REQUIRES_SSL else 0 }}"
    master_ssl_ca: ''
    master_ssl_capath: ''
    master_ssl_cert: "{{ DATABASE_SERVER_SSL_CERTIFICATE_DIRECTORY + '/' + DATABASE_CLIENT_SSL_CERTIFICATES.cert.filename if DATABASE_REQUIRES_SSL else '' }}"
    master_ssl_key: "{{ DATABASE_SERVER_SSL_CERTIFICATE_DIRECTORY + '/' + DATABASE_CLIENT_SSL_CERTIFICATES.key.filename if DATABASE_REQUIRES_SSL else '' }}"
    master_log_file: '{{ _master_status.File }}'
    master_log_pos: '{{ _master_status.Position }}'
  become: yes
```

This is not a complete example, but illustrates the issue. If SSL is no longer enabled, then `master_ssl_cert` and `master_ssl_key` will evaluate to empty strings, but the module will not actually change these properties. Instead, they remain at their old values, which can be verified by running `SHOW SLAVE STATUS\G` on the slave.
