### ISSUE TITLE
Yum module, add downloadonly and downloaddir options

### ISSUE THREAD

**Issue by aroundthecode** [ansible/ansible#24004]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
yum module

##### SUMMARY
add parameters to yum module to support downloadonly and downloaddir parameters

from **yum install --help**
>   --downloadonly        don't update, just download
>   --downloaddir=DLDIR   specifies an alternate directory to store packages

this is quite useful to use yum to download RPM packages once to be installed elsewhere (e.g. subnets with no direct internet access)

**Comment by MarkusTeufelberger** [comment]
You mean like https://github.com/ansible/ansible/issues/23220, just for yum?

**Comment by aroundthecode** [comment]
@MarkusTeufelberger yes, it's quite similar, but my focus is also on the fact that the downloaded packages should not simply be available on the yum local cache (which is the expected behaviour in the linked apt module ticket, or with only the **downloadonly** parameter) but downloaded on a desired location (the **downloaddir** parameter) to be easily managed afterwards.

Currently to do this simple step I have to relay on command module or upload bash script simply to add the two extra parameters to the yum command (this parameters afaik cannot be managed via yum configuration via external file, i.e. via **conf_file** module parameter ).

Probably a more generic "extra_args" to be passed to the yum command like the one available in the [PIP](http://docs.ansible.com/ansible/pip_module.html) module could do this (and many other) tricks.
With the extra_args i could simply invoke the yum module with "present" state including the 2 additional parameter an obtain the very same goal.

**Comment by spl** [comment]
Adding the `--downloadonly`, `--downloaddir`, and `--releasever` flags would allow one to use the `yum` module to do the trick I'm currently using `command` for, in which I download packages and create a local repository:

```yaml
- name: Create managed-epel repository configuration
  yum_repository:
    name: managed-epel
    description: Managed EPEL - CentOS-$releasever
    baseurl: "file://{{managed_epel_repository_path}}/"
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-$releasever
    gpgcheck: yes
    enabled: yes

- name: Create temporary installroot
  shell: mktemp -d
  register: installroot

- name: Download ansible
  command: >
    yum install
      --downloadonly
      --releasever=/
      --installroot={{installroot.stdout}}
      --downloaddir={{managed_epel_repository_path}}
      --disablerepo=*
      --enablerepo=managed-centos-media,epel
      ansible

- name: Update managed-epel repository database
  command: createrepo --update --database {{managed_epel_repository_path}}
```

Of course, the change check for the `--downloadonly` option would be to check if the package was successfully downloaded, not if it was installed. (Currently, I do all of the above plus install the packages and check if the packages are installed.)
