### ISSUE TITLE
support for zabbix maintenance to modify the period

### ISSUE THREAD

**Issue by wouterh-dev** [ansible/ansible#24015]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
zabbix_maintenance

##### ANSIBLE VERSION
```
ansible 2.2.2.0
```

##### STEPS TO REPRODUCE

The module correctly creates and removes maintenance periods, however it cannot be used to update a maintenance period. The status is shown as OK instead of changed and no changes to the maintenance period occur.

```yaml
    - name: Start maintenance window
      delegate_to: localhost
      zabbix_maintenance:
        name: test-window
        server_url: http://example.org
        login_user: "{{username}}"
        login_password: "{{password}}"
        host_name: "{{inventory_hostname}}"
        state: present
        minutes: 15
        collect_data: false
        
    - name: Update maintenance window
      delegate_to: localhost
      zabbix_maintenance:
        name: test-window
        server_url: http://example.org
        login_user: "{{username}}"
        login_password: "{{password}}"
        host_name: "{{inventory_hostname}}"
        state: present
        minutes: 5
        collect_data: false
```

##### EXPECTED RESULTS

I expect the first step to create the maintenance window for 15 minutes. I then expect the second step to reduce this maintenance window to 5 minutes.

##### ACTUAL RESULTS

The maintenance window is set to 15 minutes in the first step, then the second step does nothing.

```
TASK [Start maintenance window] ************************************************
changed: [test-host -> localhost]

TASK [Adjust maintenance window] ***********************************************
ok: [test-host -> localhost]
```
