### ISSUE TITLE
unable to gather facts for non-existing VM 

### ISSUE THREAD

**Issue by edwardvanhazendonk** [ansible/ansible#24018]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest_facts

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/e.vanhazendonk/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### SUMMARY

Most VM's in vsphere are not existing to ansible, while they are running and o.k.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  vars_files:
    - group_vars/all.yml
  connection: local
  become_user: root
  gather_facts: true
  serial: 1

  tasks:
  - name: Gather VM facts
    vmware_guest_facts:
      datacenter: "{{ item.datacenter }}"
      folder: "{{ item.folder }}"
      hostname: "{{ vsphere_hostname }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      name: "{{ item.name }}"
    with_items:
      - { name: 'ns2.glasoperator.local', datacenter: 'bod-kla', folder: '/vm/Office' }
      - { name: 'lnxedward.wiericke.local', datacenter: 'bod-kla', folder: '/vm/Office' }
      - { name: 'quorum02.db.glasoperator.acc', datacenter: 'asd-tc4', folder: '/vm/ACC/DB' }
```

##### EXPECTED RESULTS

I would have expected that on the same vsphere another datacenter should be searchable.

##### ACTUAL RESULTS

The folder for host ns2 isn't correct but works, if I use /vm/ where it belongs it doesn't work.

So it's a hit and miss for finding hosts into vSphere, even hosts in the same folders will not always work.

```

```
