### ISSUE TITLE
ec2_elb_facts module broken on 2.2.3.0

### ISSUE THREAD

**Issue by mattwwarren** [ansible/ansible#24016]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_elb_facts

##### ANSIBLE VERSION
```
[ansible@host ~]$ ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION
redis fact caching is enabled

##### OS / ENVIRONMENT
Running and managing Amazon Linux although N/A because we're dealing with ELBs

##### SUMMARY
There is no self any more and so line 260 in the module is wrong

```python
except BotoServerError as err:
    self.module.fail_json(msg="{0}: {1}".format(err.error_code, err.error_message),
                              exception=traceback.format_exc())
```

##### STEPS TO REPRODUCE
Try to gather facts of an ELB and get an error

```yaml
- name: Gather elb facts
  action: 
    module: ec2_elb_facts
    region: "{{ ec2_region }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    names: "{{ ec2_elbs }}"
  register: elb_facts
  delegate_to: localhost
  run_once: yes
```

##### EXPECTED RESULTS
In the case of AWS error, ansible should report the error and not crash.

##### ACTUAL RESULTS
```
fatal: [10.30.0.143 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_eFbJEs/ansible_module_ec2_elb_facts.py\", line 267, in <module>\n    main()\n  File \"/tmp/ansible_eFbJEs/ansible_module_ec2_elb_facts.py\", line 260, in main\n    self.module.fail_json(msg=\"{0}: {1}\".format(err.error_code, err.error_message),\nNameError: global name 'self' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

I will have a PR up later today for this.
