### ISSUE TITLE
IRC module is not working with irc server

### ISSUE THREAD

**Issue by offlinehoster** [ansible/ansible#24023]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
irc.py

##### ANSIBLE VERSION
```
2.3.0.0
```
##### CONFIGURATION

default no changes

##### OS / ENVIRONMENT
ubuntu 16.10 64bit

##### SUMMARY
Using irc module is not working as expected with an irc server from hackint.org

##### STEPS TO REPRODUCE

```yaml
- irc:
    server: 'irc.hackint.org'
    port: 6667
    channel: #foobar
    msg: 'Hello world'
    nick: AnsibleBot
    timeout: 60

```

##### EXPECTED RESULTS
Should work

##### ACTUAL RESULTS
```
	fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "channel": null, 
            "color": "none", 
            "key": null, 
            "msg": "Hello world", 
            "nick": "AnsibleBot", 
            "nick_to": null, 
            "part": true, 
            "passwd": null, 
            "port": 6667, 
            "server": "irc.hackint.org", 
            "style": "none", 
            "timeout": 60, 
            "topic": null, 
            "use_ssl": false
        }
    }, 
    "msg": "unable to send to IRC: Timeout waiting for IRC server welcome response"
}

```
