### ISSUE TITLE
Composer Module without `working_dir` and with `global`

### ISSUE THREAD

**Issue by thomasbilk** [ansible/ansible#24052]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- Composer

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Composer can install packages [globally](https://getcomposer.org/doc/03-cli.md#global) with `composer global require ...`. It automatically changes to the users local composer directory so no working directory parameter is required.

##### STEPS TO REPRODUCE
Use the `composer` module and try to use the `global require` command without `working_dir`.

```yaml
---

- hosts: all
  tasks:
  - composer:
      command: global require
      arguments: fabpot/php-cs-fixer
```

##### EXPECTED RESULTS
I expected the package to be installed globally.

##### ACTUAL RESULTS
The `composer` module does not work at all with this command and/or without working directory

```
fatal: [default]: FAILED! => {"changed": false, "failed": true, "msg": "Use the 'arguments' param for passing arguments with the 'command'"}
```
