### ISSUE TITLE
Scrubbing passwords in uri module breaks return_content

### ISSUE THREAD

**Issue by geekmug** [ansible/ansible#24073]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
uri

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible 2.3 just landed in RHEL7, so I just spent the last couple hours chasing down an obscure bug in our infrastructure. Ultimately, I have isolated this issue to the change in #20427. On it's face, this is a good idea, but the no_log attribute effects everything returned by the module, including the content. It just happened to be that the password appeared in one of our files, so it was replaced with stars and broke the file.

##### STEPS TO REPRODUCE

```yaml
- uri:
    url: '{{ someFileThatContainsPasswordToDownload }}'
    user: '{{ user }}'
    password: '{{ password }}'
    return_content: yes
  register: result
```

##### EXPECTED RESULTS
The value of `result.content` should match the original file on the server.

##### ACTUAL RESULTS
All appearances of `{{ password }}` in `{{ someFileThatContainsPasswordToDownload }}` are replaced with `*`, corrupting the value of `result.content`.
