### ISSUE TITLE
replace and lineinfile module can not use the TMP TEMPDIR and TEMP env variables

### ISSUE THREAD

**Issue by helldorado** [ansible/ansible#24082]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

[modules/files/replace.py](https://github.com/ansible/ansible/blob/631a10745d344c85817ab504f678d2c40ec8ae4b/lib/ansible/modules/files/replace.py)
[modules/files/lineinfile.py](https://github.com/ansible/ansible/blob/631a10745d344c85817ab504f678d2c40ec8ae4b/lib/ansible/modules/files/lineinfile.py)

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.0.0
  config file = /usr/local/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
# config file for ansible -- http://ansible.com/
# ==============================================

[defaults]

inventory               = /usr/local/ansible/orchestrator/hosts
remote_tmp              = $HOME/.ansible/tmp
pattern                 = *
forks                   = 5
poll_interval           = 15
sudo_user               = root
transport               = smart
module_lang             = C
gathering               = explicit
roles_path              = /usr/local/ansible/orchestrator/roles
sudo_exe                = sudo
timeout                 = 10
ansible_managed         = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
action_plugins          = /usr/share/ansible_plugins/action_plugins
callback_plugins        = /usr/local/ansible/callback
#stdout_callback         = actionable
connection_plugins      = /usr/share/ansible_plugins/connection_plugins
lookup_plugins          = /usr/share/ansible_plugins/lookup_plugins
vars_plugins            = /usr/share/ansible_plugins/vars_plugins
filter_plugins          = /usr/share/ansible_plugins/filter_plugins
vault_password_file     = /usr/local/ansible/vaultpass.py
bin_ansible_callbacks   = True
fact_caching            = memory
retry_files_enabled     = False
display_skipped_hosts   = False

[accelerate]
accelerate_port            = 5099
accelerate_timeout         = 30
accelerate_connect_timeout = 5.0
accelerate_daemon_timeout  = 30
```
##### OS / ENVIRONMENT

>  Testing in local connection. 
Docker container
```
uname -a
Linux spynal-orchestrator 4.9.13-moby #1 SMP Sat Mar 25 02:48:44 UTC 2017 x86_64 GNU/Linux
```
```
lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.7 (jessie)
Release:	8.7
Codename:	jessie
```

##### SUMMARY
Unable to use `replace` or `lineinfile` module for managing  file in `/sys/devices/system/...`  or any file in the subtree like `/sys/devices/system/clocksource/clocksource0/current_clocksource`.

Both modules use the `mkstemp` function of the `tempfile` lib to create the temporary file. This function has a parameter `dir` to define the TMP dir. 

> If dir is specified, the file will be created in that directory; otherwise, a default directory is used. The default directory is chosen from a platform-dependent list, but the user of the application can control the directory location by setting the **`TMPDIR`**, **`TEMP`** or **`TMP`** environment variables. 

The `atomic_move()` function from ansible `module_utils` set the `dir` parameter with 
```
tmp_dest_fd, tmp_dest_name = tempfile.mkstemp( prefix=native_prefix, dir=native_dest_dir, suffix=native_suffix)
```
 
Since `dir` is in param it is impossible for it to take the parameters from **`ENV`** as defined in lib `tempfile`.

###### Playbooks
```yaml
- hosts: orchestrator
  remote_user: root
  become: True
  gather_facts: True
  environment:
    TMPDIR: /tmp
    TEMP: /tmp
    TMP: /tmp
  tasks:
    - name: Show ENV
      debug: var=ansible_env.{{ item }}
      with_items: ['TMPDIR','TEMP','TMP']

    - name: Show user_id
      debug: var=ansible_user_id

    - name: Ensure clocksource is set to tsc
      replace:
        dest: /sys/devices/system/clocksource/clocksource0/current_clocksource
        regexp: '^hpet$'
        replace: 'tsc'
```
###### RUN
```yaml
ansible-playbook playbooks/denied.yml

PLAY [orchestrator] ************************************************************

TASK [setup] *******************************************************************
ok: [spynal-orchestrator]

TASK [Show ENV] ****************************************************************
ok: [spynal-orchestrator] => (item=TMPDIR) => {
    "ansible_env.TMPDIR": "/tmp",
    "item": "TMPDIR"
}
ok: [spynal-orchestrator] => (item=TEMP) => {
    "ansible_env.TEMP": "/tmp",
    "item": "TEMP"
}
ok: [spynal-orchestrator] => (item=TMP) => {
    "ansible_env.TMP": "/tmp",
    "item": "TMP"
}

TASK [Show user_id] ************************************************************
ok: [spynal-orchestrator] => {
    "ansible_user_id": "root"
}

TASK [Ensure clocksource is set to tsc] ****************************************
fatal: [spynal-orchestrator]: FAILED! => {"changed": false, "failed": true, "msg": "The destination directory (/sys/devices/system/clocksource/clocksource0) is not writable by the current user. Error was: [Errno 13] Permission denied: '/sys/devices/system/clocksource/clocksource0/.ansible_tmphJUqQgcurrent_clocksource'"}

PLAY RECAP *********************************************************************
spynal-orchestrator        : ok=3    changed=0    unreachable=0    failed=1
```
##### EXPECTED RESULTS
```
# cat /sys/devices/system/clocksource/clocksource0/current_clocksource
tsc
```

##### ACTUAL RESULTS
```yaml
$ ansible-playbook playbooks/denied.yml -vvvv
Using /usr/local/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin unnamed of type old, v1.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: denied.yml ***********************************************************
1 plays in playbooks/denied.yml

PLAY [orchestrator] ************************************************************

TASK [setup] *******************************************************************
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<spynal-orchestrator> ESTABLISH LOCAL CONNECTION FOR USER: abdoul.bah
<spynal-orchestrator> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1493319387.44-68024350656262 `" && echo ansible-tmp-1493319387.44-68024350656262="` echo $HOME/.ansible/tmp/ansible-tmp-1493319387.44-68024350656262 `" ) && sleep 0'
<spynal-orchestrator> PUT /tmp/tmpbfWUOd TO /home/ansible/.ansible/tmp/ansible-tmp-1493319387.44-68024350656262/setup.py
<spynal-orchestrator> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1493319387.44-68024350656262/ /home/ansible/.ansible/tmp/ansible-tmp-1493319387.44-68024350656262/setup.py && sleep 0'
<spynal-orchestrator> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-dnfrkypuqiooinvfcwgmmeyijpectzcc; TMP=/tmp TMPDIR=/tmp TEMP=/tmp /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1493319387.44-68024350656262/setup.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1493319387.44-68024350656262/" > /dev/null 2>&1'"'"' && sleep 0'
ok: [spynal-orchestrator]

TASK [Show ENV] ****************************************************************
task path: /usr/local/ansible/orchestrator/playbooks/denied.yml:10
ok: [spynal-orchestrator] => (item=TMPDIR) => {
    "ansible_env.TMPDIR": "/tmp",
    "invocation": {
        "module_args": {
            "var": "ansible_env.TMPDIR"
        },
        "module_name": "debug"
    },
    "item": "TMPDIR"
}
ok: [spynal-orchestrator] => (item=TEMP) => {
    "ansible_env.TEMP": "/tmp",
    "invocation": {
        "module_args": {
            "var": "ansible_env.TEMP"
        },
        "module_name": "debug"
    },
    "item": "TEMP"
}
ok: [spynal-orchestrator] => (item=TMP) => {
    "ansible_env.TMP": "/tmp",
    "invocation": {
        "module_args": {
            "var": "ansible_env.TMP"
        },
        "module_name": "debug"
    },
    "item": "TMP"
}

TASK [Show user_id] ************************************************************
task path: /usr/local/ansible/orchestrator/playbooks/denied.yml:14
ok: [spynal-orchestrator] => {
    "ansible_user_id": "root"
}

TASK [Ensure clocksource is set to tsc] ****************************************
task path: /usr/local/ansible/orchestrator/playbooks/denied.yml:17
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/files/replace.py
<spynal-orchestrator> ESTABLISH LOCAL CONNECTION FOR USER: abdoul.bah
<spynal-orchestrator> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1493319390.8-280370025912413 `" && echo ansible-tmp-1493319390.8-280370025912413="` echo $HOME/.ansible/tmp/ansible-tmp-1493319390.8-280370025912413 `" ) && sleep 0'
<spynal-orchestrator> PUT /tmp/tmpMeMgmh TO /home/ansible/.ansible/tmp/ansible-tmp-1493319390.8-280370025912413/replace.py
<spynal-orchestrator> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1493319390.8-280370025912413/ /home/ansible/.ansible/tmp/ansible-tmp-1493319390.8-280370025912413/replace.py && sleep 0'
<spynal-orchestrator> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-hitqahptezehpfyveseqfpbamdbvvzhn; TMP=/tmp TEMP=/tmp TMPDIR=/tmp /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1493319390.8-280370025912413/replace.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1493319390.8-280370025912413/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [spynal-orchestrator]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "backup": false,
            "content": null,
            "delimiter": null,
            "dest": "/sys/devices/system/clocksource/clocksource0/current_clocksource",
            "directory_mode": null,
            "follow": false,
            "force": null,
            "group": null,
            "mode": null,
            "owner": null,
            "regexp": "^hpet$",
            "remote_src": null,
            "replace": "tsc",
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "unsafe_writes": null,
            "validate": null
        },
        "module_name": "replace"
    },
    "msg": "The destination directory (/sys/devices/system/clocksource/clocksource0) is not writable by the current user. Error was: [Errno 13] Permission denied: '/sys/devices/system/clocksource/clocksource0/.ansible_tmp40BeKjcurrent_clocksource'"
}

PLAY RECAP *********************************************************************
spynal-orchestrator        : ok=3    changed=0    unreachable=0    failed=1
```

**Comment by s-hertel** [comment]
There is a discrepancy between how mkstemp is used in lineinfile/replace and in module_utils.basic.atomic_move() but I can't find Ansible documentation about intentionally allowing the user to control the directory. When I manually modify the directory in module_utils.basic I then get "Unable to rename file: /var/folders/by/k8_fbl593dlctgqmwq5wzl2c0000gn/T/tmp6IRTZ_ to /private/etc/ansible/hosts: [Errno 13] Permission denied". Have you tried using `become: yes` in the playbook?

**Comment by bcoca** [comment]
This is not a 'real' file `/sys/devices/system/clocksource/clocksource0/current_clocksource` so normal semantics won't work, use `unsafe_writes=yes` to enable to writing to such files. (things in /sys, /proc, /system are 'special').

**Comment by helldorado** [comment]
`become` is already to `yes` in my test.

If i modify the active_move like with `unsafe_writes=yes` or not

```python
tmp_dest_fd, tmp_dest_name = tempfile.mkstemp(
                        prefix=native_prefix, dir='/tmp', suffix=native_suffix)
                except (OSError, IOError):
```
I get the error:
```yaml
fatal: [spynal-orchestrator]: FAILED! => {"changed": false, "failed": true, "msg": "Could not replace file: /tmp/.ansible_tmpfiU3QXcurrent_clocksource to /sys/devices/system/clocksource/clocksource0/current_clocksource: [Errno 18] Invalid cross-device link"}
```

This issue is not linked to the replace and lineinfile module. But rather to `sysfs` pseudo file system.

I think adding the possibility of overriding the temporary folder path would be a plus for some operations.

Issue can be closed. 

Thank's.

**Comment by robertpeteuil** [comment]
It sounds like the root cause may already be identified.  

I'll post my debug data in case it helps.  Note: This error occurs even when "unsafe_writes: yes" is specified (as you can see in the debug module args).

```
- lineinfile:
    path: /sys/module/hid_apple/parameters/iso_layout
    regexp: '^1'
    line: '0'
    state: present
    unsafe_writes: yes
  become: True
```

Debug Data

```
fatal: [macubu]: FAILED! => {"changed": false, "failed": true, "msg": "The destination directory (/sys/module/hid_apple/parameters) is not writable by the current user. Error was: [Errno 13] Permission denied: '/sys/module/hid_apple/parameters/.ansible_tmpxc2mO6iso_layout'"}
Debugger invoked
(debug) p result
{'_ansible_no_log': False,
 '_ansible_parsed': True,
 'changed': False,
 u'failed': True,
 u'invocation': {u'module_args': {u'attributes': None,
                                  u'backrefs': False,
                                  u'backup': False,
                                  u'content': None,
                                  u'create': False,
                                  u'delimiter': None,
                                  u'directory_mode': None,
                                  u'follow': False,
                                  u'force': None,
                                  u'group': None,
                                  u'insertafter': None,
                                  u'insertbefore': None,
                                  u'line': u'0',
                                  u'mode': None,
                                  u'owner': None,
                                  u'path': u'/sys/module/hid_apple/parameters/iso_layout',
                                  u'regexp': u'^1',
                                  u'remote_src': None,
                                  u'selevel': None,
                                  u'serole': None,
                                  u'setype': None,
                                  u'seuser': None,
                                  u'src': None,
                                  u'state': u'present',
                                  u'unsafe_writes': True,
                                  u'validate': None}},
 u'msg': u"The destination directory (/sys/module/hid_apple/parameters) is not writable by the current user. Error was: [Errno 13] Permission denied: '/sys/module/hid_apple/parameters/.ansible_tmpxc2mO6iso_layout'"}
```

My workaround requires using "shell" which re-writes the desired value on every run, and thus is not idempotent.

```
- shell: "echo 0 | sudo tee /sys/module/hid_apple/parameters/iso_layout"
  changed_when: False
```
