### ISSUE TITLE
Archive is unable to create zip archives over 4GB

### ISSUE THREAD

**Issue by spyrexd** [ansible/ansible#24125]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

archive module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/user/projectpath/ansible.cfg
  configured module search path - Default w/o overrides
  python version - 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When trying to create a zip archive with a files over 4GB in size the task fails stating
the following:

Filesize would require ZIP64 extensions

##### STEPS TO REPRODUCE

Create a file over 4GB

$ truncate 5GB test.file

```yaml
- name: Archive test
  hosts: localhost

  tasks:
    - archive:
         path: test.file
         dest: test.file.zip
         format: zip
```

##### EXPECTED RESULTS

A zip archive named test.file.zip is created containing the file test.file

##### ACTUAL RESULTS

```
fatal: [hostname]: Failed! => {"changed": false, "failed": true, "msg": "Error when writing zip at test.file.zip: Filesize would require ZIP64 extensions"}
```
