### ISSUE TITLE
ec2_vpc_nat_gateway returns NAT gateway ID differently between create and no-op

### ISSUE THREAD

**Issue by davidvartan** [ansible/ansible#24129]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`ec2_vpc_nat_gateway` module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 [...]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When a NAT gateway is created, its ID is returned via the `NatGatewayId` key. If it had already existed, the ID is returned via the `nat_gateway_id` key.

This makes it difficult to use the ID in a subsequent task, e.g. for configuring the route table. 

##### STEPS TO REPRODUCE

```
- name: Ensure NAT Gateway exists
  ec2_vpc_nat_gateway:
    state: present
    region: "{{ region }}"        
    subnet_id: "{{ public_subnet.subnet.id }}"
    if_exist_do_not_create: yes
  register: nat_gateway
```

##### EXPECTED RESULTS

Regardless of create vs. no-op, the output should use the same key to return the NAT gateway ID.

##### ACTUAL RESULTS

`NatGatewayId` when created:

```
changed: [localhost] => {
    "CreateTime": "2017-04-28T19:40:04.867000+00:00",
    "NatGatewayAddresses": [{"AllocationId": "eipalloc-61e0805b"}],
    "NatGatewayId": "nat-01265b7f703ec3efc",
    "State": "pending",
    "SubnetId": "subnet-1280e75b",
    "VpcId": "vpc-63261604",
    "changed": true,
    "msg": "",
    "success": true
}
```

`nat_gateway_id` when unchanged:

```
ok: [localhost] => {
    "changed": false,
    "create_time": "2017-04-28T18:41:43.941000+00:00",
    "msg": "NAT Gateway nat-0374f5f52448be44c already exists in subnet_id subnet-ccabcc85",
    "nat_gateway_addresses": [ ... ],
    "nat_gateway_id": "nat-0374f5f52448be44c",
    "state": "available",
    "subnet_id": "subnet-ccabcc85",
    "success": true,
    "vpc_id": "vpc-2f477748"}
```
