### ISSUE TITLE
Proxmox failure to create VM

### ISSUE THREAD

**Issue by peternavr** [ansible/ansible#24139]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
contrib/inventory/proxmox.py

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = .../moon-ansible.windows/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

```
[defaults]
inventory = ./inventory
```

##### STEPS TO REPRODUCE

All you see is either a 500 Forbidden or a 400 Bad request error. No follow up errors why it happens.

```yaml
---
- name: create prox serves
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
     - proxmox:
        node: 'pve2'
        api_user: 'xxx'
        api_password: 'xxx'
        api_host: '127.0.0.1'
        ostemplate: 'data:vztmpl/debian-8.0-standard_8.6-1_amd64.tar.gz'
        pubkey: '...'

```

##### EXPECTED RESULTS

A VM or Container to be created.

##### ACTUAL RESULTS

`

```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_host": "xxx", 
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "api_user": "xxx@pve", 
            "cpus": 1, 
            "cpuunits": 1000, 
            "disk": "3", 
            "force": false, 
            "hostname": null, 
            "ip_address": null, 
            "memory": 512, 
            "mounts": null, 
            "nameserver": null, 
            "netif": {
                "node0": "gw=xxx,bridge=vmbr1,name=eth0,ip=xxx/25"
            }, 
            "node": "pve2", 
            "onboot": false, 
            "ostemplate": "data:vztmpl/debian-8.0-standard_8.6-1_amd64.tar.gz", 
            "password": null, 
            "pool": null, 
            "pubkey": "...", 
            "searchdomain": null, 
            "state": "present", 
            "storage": "local", 
            "swap": 0, 
            "timeout": 30, 
            "unprivileged": false, 
            "validate_certs": false, 
            "vmid": null
        }
    }, 
    "msg": "creation of lxc VM 198 failed with exception: 400 Bad Request"
}
```

You can't debug the proxmox api easily. No idea why it's throwing a bad request and the provider isn't helpful either.
