### ISSUE TITLE
Implicit localhost is ignored in all groups, instead of just the 'all' group

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#24156]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Inventory, playbook

##### ANSIBLE VERSION
```
ansible 2.3.0.0
```
and
```
ansible 2.4.0 (devel 594d7d5d9d) last updated 2017/04/30 13:11:01 (GMT -600)
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using the implicit `localhost`, adding it to groups, and referencing those groups in a later play, the play is skipped due to it not matching any hosts.

##### STEPS TO REPRODUCE

Playbook:

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - group_by:
        key: my_group

- hosts: my_group
  gather_facts: no
  tasks:
    - debug: msg="here I am"
```

With implicit localhost:

```
$ ansible-playbook foo.yml 

PLAY [localhost] **************************************************************************************************************************************************************

TASK [group_by] ***************************************************************************************************************************************************************
ok: [localhost]

PLAY [my_group] ***************************************************************************************************************************************************************
skipping: no hosts matched

PLAY RECAP ********************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

With explicit localhost:

```
$ ansible-playbook -i localhost, -c local foo.yml 

PLAY [localhost] **************************************************************************************************************************************************************

TASK [group_by] ***************************************************************************************************************************************************************
ok: [localhost]

PLAY [my_group] ***************************************************************************************************************************************************************

TASK [debug] ******************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "here I am"
}

PLAY RECAP ********************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0  
```

##### EXPECTED RESULTS
Result for implicit localhost should look like explicit localhost

##### ACTUAL RESULTS
The implicit localhost is excluded/ignored from *all* groups instead of just the `all` group.

**Comment by agaffney** [comment]
I was able to work around this fairly easily by using `add_host` instead of `group_by`.

```
---
- hosts: localhost
  gather_facts: no
  tasks:
    # Add a dummy host pointing to localhost that's in the groups expected by
    # the other playbooks
    - add_host:
        name: dummy
        groups: my_group
        ansible_connection: local
```
