### ISSUE TITLE
Allow passing --allowerasing to DNF packaging module

### ISSUE THREAD

**Issue by dvershinin** [ansible/ansible#24161]
##### ISSUE TYPE

Feature Idea

##### COMPONENT NAME
dnf module

##### SUMMARY
Currently there seems to be no way to pass ```--allowerasing``` option to ```dnf```. 
For instance there is no way to run equivalent of: 

```dnf --allowerasing install git2u```

Would be great to add extra option like so:

```
- name: install the latest version of git
  dnf:
    name: git2u
    state: latest
    allowerasing: yes
```

**Comment by ansibot** [comment]
cc @ignatenkobrain @DJMuggs
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by igor-raits** [comment]
usually, it is a bad idea to pass allowerasing via non-interactive scenarios..

**Comment by dvershinin** [comment]
@ignatenkobrain maybe it is. 

My use case is to deploy latest git to CentOS 7 machines where ```dnf``` is installed.

**Comment by real666maverick** [comment]
Bypass path:

```
packages:
  allowerasing:
    - package1
    - package2
  present:
    - package1
    - package3
    - ....
  absent:
    - ....
```    
```
- name: is this the actual version of the package
  shell: "`which rpm` -qa | grep {{item}}"
  args:
    warn: false
  ignore_errors: true
  changed_when: false
  register: rpm_check
  with_items: "{{packages.allowerasing}}"
  tags:
    - packages
```
```
- name: replace package to actual version
  shell: "dnf --allowerasing -y install {{item}}"
  args:
    warn: false
  with_items: "{{rpm_check.results}}"
  when: item.rc != 0
  tags:
    - packages

```
