### ISSUE TITLE
Weird behaviour with include/dependencies and variable scoping

### ISSUE THREAD

**Issue by estahn** [ansible/ansible#24168]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 05:35:35) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Running the same role configuration from from the playbook and then as a dependency will not change the variable scope.

Example: `- { role: roleA, tasks: [1] }` within the play and after it as a dependency from another role

##### STEPS TO REPRODUCE
Test Case: https://www.dropbox.com/s/z8lvpa139wc4ljh/ansible-test.zip?dl=0
Gist: https://gist.github.com/88713c68f9b288f2113e33c5e1d795a3

Playbook:
```yaml
---
- name: Play
  hosts: localhost
  connection: local
  gather_facts: false

  roles:
    - { role: roleA, tasks: [1] }
    - { role: roleB, name: two }
```
roleB/meta/main.yml
```yaml
allow_duplicates: yes
dependencies:
  - { role: roleA, tasks: [1] }
```

roleA/tasks/main.yml
```yml
---

- debug:
    msg: "{{ role_name }} main.yml name={{ name | default('N/A') }}"

- include: test{{ item }}.yml
  with_items: "{{ tasks }}"
```

##### EXPECTED RESULTS
The role that runs as part of the dependencies should have `name` in it's scope.

##### ACTUAL RESULTS
```
ok: [localhost] => {
    "changed": false,
    "msg": "roleA test1 name=N/A"
}
```

**Comment by bcoca** [comment]
cc @jimi-c

**Comment by estahn** [comment]
This is still happening in `devel`:
```
ansible 2.4.0
  config file =
  configured module search path = [u'/Users/estahn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/estahn/.virtualenvs/iod/lib/python2.7/site-packages/ansible
  executable location = /Users/estahn/.virtualenvs/iod/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 05:35:35) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

The following is not working either:
```
- name: test1
  include_role:
    name: roleA
  vars:
    name: foobar1
- name: test1
  include_role:
    name: roleA
  vars:
    name: foobar3
    name2: foobar4
```

`name` will always be `foobar1`.

**Comment by woodsae** [comment]
👍

**Comment by estahn** [comment]
@bcoca @jimi-c I tried to troubleshoot the python code. Any pointers where I could investigate? It's pretty much a show-stopper for reusable roles.

**Comment by bcoca** [comment]
it is a precedence issue, 'inline vars'  `  - { role: roleA, tasks: [1] }`  have higher precedence than those in `vars:` so you cannot override them that way. I would avoid using them directly inline and use `vars:` in all cases.

**Comment by estahn** [comment]
@bcoca Brian, thanks for the response although I think you're missing the point. Or I'm not entirely following with the concepts.

**Question:** If nothing else is specified (no `<role>/vars/` folder) should the variable that is passed into the role override the variable of the parent?

Example:
```yaml
- play
  - roleA, name=1
    - output name => **1**
    - include roleB, name=2
      - output name => **1** (**expected is 2**)
```
Here is a simplified gist showing it: https://gist.github.com/55117881935965a680ee683b2d95ed12

**Expected Result:**
```bash
PLAY [Ansible test] ************************************************************************************************************************************************************************************************************************************************************

TASK [roleA : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "A"
}

TASK [roleA : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "B"
}

TASK [roleB : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "C"
}

TASK [roleA : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "First include of roleA"
}

TASK [roleA : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "Second include of roleA"
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0
```

**Actual result:**
```bash
PLAY [Ansible test] ************************************************************************************************************************************************************************************************************************************************************

TASK [roleA : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "A"
}

TASK [roleA : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "B"
}

TASK [roleB : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "C"
}

TASK [roleA : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "C"
}

TASK [roleA : debug] ***********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "name": "C"
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=0
```

**Comment by bcoca** [comment]
I did not mention the `vars/` directory, my point is about precedence in vars declared inline in roles (i.e `- roleA, name=1`) vs those declared in a `vars:` key

``` - include roleB, name=2``` <= not sure what this is

**Comment by estahn** [comment]
@bcoca Thanks, I think i understand now, but it seems still weird to me.

So, basically I **can't** use `include_role` and pass in variables that are already defined.

The [documentation](https://docs.ansible.com/ansible/include_role_module.html) has this example:

```yaml
- name: Pass variables to role
  include_role:
    name: myrole
  vars:
    rolevar1: 'value from task'
```

In case I want to run this twice with a different value for `rolevar` it won't work. (see gist above)

Example:

```yaml
- name: Pass variables to role 1
  include_role:
    name: myrole
  vars:
    rolevar1: 'value from task 1'

- name: Pass variables to role 2
  include_role:
    name: myrole
  vars:
    rolevar1: 'value from task 1'
```

`rolevar1` will always be `value from task 1`.

Is there another way to pass in variables into `include_role` then `vars`?

**Comment by bcoca** [comment]
No, its a precedence issue with vars inline in role declaration, the example above seems flawed as you keep passing the same value:

my quick test:
```yaml
- name: test
  hosts: localhost
  gather_facts: False
  connection: local
  tasks:
  - include_role: name=test1
    vars:
        varforrole: 'called1'
  - include_role: name=test1
    vars:
        varforrole: 'called2'
```
my output:
```
ok: [localhost] => {
    "msg": "in test1 role called1!"
}
ok: [localhost] => {
    "msg": "in test1 role called2!"
}
```
