### ISSUE TITLE
dicts that contain Single Encrypted Variables cannot be copied to a new fact

### ISSUE THREAD

**Issue by mdelagrange** [ansible/ansible#24175]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Vault Single Encrypted Variables

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 033fe5548b) last updated 2017/05/01 13:20:42 (GMT -500)
```

##### CONFIGURATION

Single Encrypted Variable is encrypted with the key "notasecret".

##### OS / ENVIRONMENT

OS X running against localhost

##### SUMMARY

If you have a dict that contains a Single Encrypted Variable, you can access its value normally, but if you copy that dict to a new fact with `set_fact`, you get an error trying to access it.

##### STEPS TO REPRODUCE

Run the following script with the command `ansible-playbook --ask-vault-pass combine_test.yml` and the password `notasecret`.

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - name: setting facts with and without secret
      set_fact:
        without_secret:
          the_key: 'some_value'
        with_secret:
          the_key: !vault |
            $ANSIBLE_VAULT;1.1;AES256
            33303334336532393762663839343035623331613866653830353364613862386161373533643234
            6134396562633530623662653864626539366634336339620a613130373065323864383539323632
            33646530653234356537343765353731636335306465336664373031393463623837646564643739
            3064626463396234300a363633316461376331623664623631326466356236623962626133353932
            6337

    - name: set new fact that includes without_secret
      set_fact:
        new_fact_without_secret: "{{ without_secret }}"

    - name: show the secret in new_fact_without_secret
      debug:
        msg: "{{ new_fact_without_secret['the_key'] }}"

    - name: set new fact that includes with_secret
      set_fact:
        new_fact_with_secret: "{{ with_secret }}"

    - name: show the secret in new_fact_with_secret
      debug:
        msg: "{{ new_fact_with_secret['the_key'] }}"
```

##### EXPECTED RESULTS

All the tasks succeed and show the values of the facts.

##### ACTUAL RESULTS

The final task fails with:

```
TASK [show the secret in new_fact_with_secret] *********************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'the_key'\n\nThe error appears to have been in '/Users/mdelagrange/Desktop/combine-test/combine_test.yml': line 29, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: show the secret in new_fact_with_secret\n      ^ here\n"}
```
