### ISSUE TITLE
Use ansible module proxmox_kvm can't use full clone to new vm

### ISSUE THREAD

**Issue by zarr12steven** [ansible/ansible#24188]
##### SUMMARY

Management of Qemu(KVM) Virtual Machines in Proxmox.

I follow this document [CentOS 7 1511 Minimal oVirt Template](https://github.com/rharmonson/richtech/wiki/CentOS-7-1511-Minimal-oVirt-Template), and I also transfer vm to template.

Now I want to  use  full clone VM template for create New VM, so I wrote the ansible playbook.

##### ISSUE TYPE

 - Bug Pull Request

##### COMPONENT NAME

```
proxmox_kvm
```
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

Proxmox Version:  pve-manager/4.4-1/eb2d6f1e (running kernel: 4.4.35-1-pve)
```

##### ADDITIONAL INFORMATION

```
- name: Clone for Create New VM
  proxmox_kvm:
    api_user    : root@pam
    api_password: password
    api_host    : FQDN
    node        : "{{ ansible_nodename }}"
    clone       : test
    vmid        : 30001
    newid       : 30002
    name        : hello
    pool        : Stage
    storage     : VMs
    format      : raw
    timeout     : 500
```

#### Error

```
fatal: [proxmox2]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "acpi": true,
            "agent": null,
            "api_host": "FQDN",
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "api_user": "root@pam",
            "args": null,
            "autostart": false,
            "balloon": 0,
            "bios": null,
            "boot": "cnd",
            "bootdisk": null,
            "clone": "test",
            "cores": 1,
            "cpu": "kvm64",
            "cpulimit": null,
            "cpuunits": 1000,
            "delete": null,
            "description": null,
            "digest": null,
            "force": null,
            "format": "raw",
            "freeze": null,
            "full": true,
            "hostpci": null,
            "hotplug": null,
            "hugepages": null,
            "ide": null,
            "keyboard": null,
            "kvm": true,
            "localtime": null,
            "lock": null,
            "machine": null,
            "memory": 512,
            "migrate_downtime": null,
            "migrate_speed": null,
            "name": "hello",
            "net": null,
            "newid": 30002,
            "node": "proxmox-2",
            "numa": null,
            "numa_enabled": null,
            "onboot": true,
            "ostype": "l26",
            "parallel": null,
            "pool": "Stage",
            "protection": null,
            "reboot": null,
            "revert": null,
            "sata": null,
            "scsi": null,
            "scsihw": null,
            "serial": null,
            "shares": null,
            "skiplock": null,
            "smbios": null,
            "snapname": null,
            "sockets": 1,
            "startdate": null,
            "startup": null,
            "state": "present",
            "storage": "VMs",
            "tablet": false,
            "target": null,
            "tdf": null,
            "template": false,
            "timeout": 500,
            "update": false,
            "validate_certs": false,
            "vcpus": null,
            "vga": "std",
            "virtio": null,
            "vmid": 30001,
            "watchdog": null
        }
    },
    "msg": "Unable to clone vm hello from vimd 30001=500 Internal Server Error"
}
	to retry, use: --limit @/Users/daniel/work/tenmax/lab/proxmox.retry

PLAY RECAP ******************************************************************************************************************************************************************
proxmox2                   : ok=1    changed=0    unreachable=0    failed=1
```

How to fixed this error ?

**Comment by ansibot** [comment]
cc @helldorado
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by helldorado** [comment]
@zarr12steven thank's for this report.

Can you provide your PVE Env: 

## From any node
- **Cluster State** =>  `pvecm status`
- **Pool list** => `pvesh get /pools`
- **Storage list** => `pvesh get /storage/`

## Testing the clone via `pvesh` from **`proxmox-2`** node
- **Linked clone**:
   `pvesh create /nodes/proxmox-2/qemu/30001/clone -newid 30002  --name hello`
- **Full clone with specified storage target (This what you want i guess)**:
   `pvesh create /nodes/proxmox-2/qemu/30001/clone -newid 30002 --ful 1 --storage VMs --name hello`
- **Full clone with specified pool and storage target**: 
   `pvesh create /nodes/proxmox-2/qemu/30001/clone -newid 30002 --ful 1 --pool Stage --storage VMs  --name hello`

## From my tests:

##### Playbooks (Note i don't use Pool in play)
```yaml
ansible@spynal-orchestrator:/usr/local/ansible/orchestrator (master)$ cat playbooks/issue-24188.yml
- hosts: orchestrator
  remote_user: root
  tasks:
    - name: Clone for Create New VM
      proxmox_kvm:
        api_user    : "root@pam"
        api_host    : "pmxlab.helldorado.info"
        node        : "awhlabhyp2"
        clone       : test
        vmid        : 104
        newid       : 200
        name        : hello
        #pool       : Stage
        storage     : VMs_awhlabhyp2
        format      : raw
        timeout     : 500
```
##### RUN
```yaml
ansible@spynal-orchestrator:/usr/local/ansible/orchestrator (master)$ ansible-playbook playbooks/issue-24188.yml -vvvvv
Using /usr/local/ansible/ansible.cfg as config file
Loading callback plugin actionable of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin unnamed of type old, v1.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: issue-24188.yml ******************************************************
1 plays in playbooks/issue-24188.yml

PLAY [orchestrator] ************************************************************
Using module file /usr/local/ansible/orchestrator/playbooks/library/proxmox_kvm.py
<spynal-orchestrator> ESTABLISH LOCAL CONNECTION FOR USER: abdoul.bah
<spynal-orchestrator> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1493711241.87-150931064709187 `" && echo ansible-tmp-1493711241.87-150931064709187="` echo $HOME/.ansible/tmp/ansible-tmp-1493711241.87-150931064709187 `" ) && sleep 0'
<spynal-orchestrator> PUT /tmp/tmpVS46s_ TO /home/ansible/.ansible/tmp/ansible-tmp-1493711241.87-150931064709187/proxmox_kvm.py
<spynal-orchestrator> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1493711241.87-150931064709187/ /home/ansible/.ansible/tmp/ansible-tmp-1493711241.87-150931064709187/proxmox_kvm.py && sleep 0'
<spynal-orchestrator> EXEC /bin/sh -c '/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1493711241.87-150931064709187/proxmox_kvm.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1493711241.87-150931064709187/" > /dev/null 2>&1 && sleep 0'

TASK [Clone for Create New VM] *************************************************
task path: /usr/local/ansible/orchestrator/playbooks/issue-24188.yml:4
changed: [spynal-orchestrator] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "acpi": true,
            "agent": null,
            "api_host": "pmxlab.helldorado.info",
            "api_password": null,
            "api_user": "root@pam",
            "args": null,
            "autostart": false,
            "balloon": 0,
            "bios": null,
            "boot": "cnd",
            "bootdisk": null,
            "clone": "test",
            "cores": 1,
            "cpu": "kvm64",
            "cpulimit": null,
            "cpuunits": 1000,
            "delete": null,
            "description": null,
            "digest": null,
            "force": null,
            "format": "raw",
            "freeze": null,
            "full": true,
            "hostpci": null,
            "hotplug": null,
            "hugepages": null,
            "ide": null,
            "keyboard": null,
            "kvm": true,
            "localtime": null,
            "lock": null,
            "machine": null,
            "memory": 512,
            "migrate_downtime": null,
            "migrate_speed": null,
            "name": "hello",
            "net": null,
            "newid": 200,
            "node": "awhlabhyp2",
            "numa": null,
            "numa_enabled": null,
            "onboot": true,
            "ostype": "l26",
            "parallel": null,
            "pool": null,
            "protection": null,
            "reboot": null,
            "revert": null,
            "sata": null,
            "scsi": null,
            "scsihw": null,
            "serial": null,
            "shares": null,
            "skiplock": null,
            "smbios": null,
            "snapname": null,
            "sockets": 1,
            "startdate": null,
            "startup": null,
            "state": "present",
            "storage": "VMs_awhlabhyp2",
            "tablet": false,
            "target": null,
            "tdf": null,
            "template": false,
            "timeout": 500,
            "update": false,
            "validate_certs": false,
            "vcpus": null,
            "vga": "std",
            "virtio": null,
            "vmid": 112,
            "watchdog": null
        },
        "module_name": "proxmox_kvm"
    },
    "msg": "VM hello with newid 200 cloned from vm with vmid 112"
}

PLAY RECAP *********************************************************************
spynal-orchestrator        : ok=1    changed=1    unreachable=0    failed=0
```
