### ISSUE TITLE
Cannot trigger handler with variable in name that is passed through inventory

### ISSUE THREAD

**Issue by KKoukiou** [ansible/ansible#24194]
First I would like to put this issue link here https://github.com/ansible/ansible/issues/12427, which is closed but is related.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
handlers with parameterized names

##### ANSIBLE VERSION
```
$ ansible --version 
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.3 (default, Mar 21 2017, 17:21:33) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### SUMMARY
I am unable to successfully trigger the handler with a variable in its name when the variable is passed through the inventory file.

##### STEPS TO REPRODUCE
Example files:
```yaml
$ cat playbooks/test-playbook/config.yml 
---
- hosts: test-target
  roles:
    - role: "test-role"

$ cat roles/test-role/tasks/main.yml 
- name: Install {{ test_role_service }}
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ test_role_service }}"
  notify: enable and start {{ test_role_service }}
  changed_when: true

$ cat roles/test-role/handlers/main.yaml 
---
- name: enable and start {{ test_role_service }}
  service:
    name: "{{ test_role_service }}"
    state: started
    enabled: yes
```
``` bash
$ cat inv 
[test-target]
localhost              ansible_connection=local

[test-target:vars]
test_role_service=httpd
ansible_python_interpreter=/usr/bin/python3
ansible_become=true

$ tree -d -L 3
.
├── playbooks
│   └── test-playbook
│       └── roles -> ../../roles
└── roles
    └── test-role
        ├── defaults
        ├── handlers
        └── tasks

```

##### EXPECTED RESULTS
Expected that the handler "enable and start httpd" will get triggered.

##### ACTUAL RESULTS
```
+ ansible-playbook -u root -i inv playbooks/test-playbook/config.yml

PLAY [test-target] ***************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [test-role : Install httpd] *************************************************************************************************************************************************************
ERROR! The requested handler 'enable and start httpd' was not found in either the main handlers list nor in the listening handlers list

```

However when I have this `test_role_service` variable in the role default variables it works fine and also if I pass the variable with -e option in the ansible-playbook command it works fine as well.
So, should this configuration be supported?

Thanks,
Katerina
