### ISSUE TITLE
vmware_guest module fails to customize vm built from template

### ISSUE THREAD

**Issue by drpuur** [ansible/ansible#24193]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/ansible/.ansible.cfg
  configured module search path = [u'/data/ansible/library']
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
[defaults]
inventory      = /data/ansible/hosts
library        = /data/ansible/library
roles_path    = /data/ansible/roles
host_key_checking = False
retry_files_enabled = False
force_color = 1
pipelining = True
forks = 25
ssh_args = -o ControlMaster=auto -o ControlPersist=60s

##### OS / ENVIRONMENT
RHEL7.3

##### SUMMARY
Running the module vmware_guest to create a VM from a template gives the following error:

Customization of the guest operating system 'rhel7_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.

The template does not contain any OS at all (it will only be used as a base for a kickstart installation).

##### STEPS TO REPRODUCE
Run Playbook task (see below).

```yaml
  - name: create the VM
    vmware_guest:
      validate_certs: False
      hostname: "{{ vcenter_server }}"
      username: ansible@vsphere.local
      password: "{{ vcenter_password[vcenter_server] }}"
      name: "{{ inventory_hostname_short }}"
      annotation: "{{ vm_annotation }}"
      state: present
      hardware:
        memory_mb: "{{ vm_memory_mb }}"
        num_cpus: "{{ vm_num_cpus }}"
        scsi: paravirtual
      disk: "{{ disks }}"
      networks:
      - name: "{{ vm_network }}"
      datacenter: Datacenter_01
      cluster: "{{ vmware_cluster }}"
      template: "RHEL7_CONFIG_ONLY"
      wait_for_ip_address: no
    register: deploy
    delegate_to: localhost
```

##### EXPECTED RESULTS

That a VM is created with the specified parameters.

##### ACTUAL RESULTS

FAILED: Output see below (-vvvv)

```
TASK [create the VM] *********************************************************************************************************************************************************************************************************************
task path: /data/ansible/playbooks/deploy/create_vm.yml:42
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1493717714.4-8150352648256 `" && echo ansible-tmp-1493717714.4-8150352648256="` echo /home/ansible/.ansible/tmp/ansible-tmp-1493717714.4-8150352648256 `" ) && sleep 0'
<localhost> PUT /tmp/tmpvTjLRt TO /home/ansible/.ansible/tmp/ansible-tmp-1493717714.4-8150352648256/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1493717714.4-8150352648256/ /home/ansible/.ansible/tmp/ansible-tmp-1493717714.4-8150352648256/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/ansible/.ansible/tmp/ansible-tmp-1493717714.4-8150352648256/vmware_guest.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1493717714.4-8150352648256/" > /dev/null 2>&1 && sleep 0'
fatal: [xa1000.test.com -> localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": "Test VM",
            "cluster": "Cluster_TST",
            "customization": {},
            "customvalues": [],
            "datacenter": "Datacenter_01",
            "disk": [
                {
                    "datastore": "DATASTORE1",
                    "size_gb": 30,
                    "type": "thin"
                },
                {
                    "datastore": "DATASTORE1",
                    "size_gb": 50,
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 2048,
                "num_cpus": 2,
                "scsi": "paravirtual"
            },
            "hostname": "vcentertest.test.com",
            "is_template": false,
            "name": "xa1000",
            "name_match": "first",
            "networks": [
                {
                    "name": "VLAN123"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "state": "present",
            "template": "RHEL7_CONFIG_ONLY",
            "template_src": "RHEL7_CONFIG_ONLY",
            "username": "ansible@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "Customization of the guest operating system 'rhel7_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations."
}
```
