### ISSUE TITLE
[Regression] ios_command pollutes the fetched configuration with some *

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#24212]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ios_command
ios_facts

##### ANSIBLE VERSION

Both latest stable & unstable versions:
```
ansible 2.3.0.0-1
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/actionmystique/Ansible/git-yang-networkop/ansible-101/library']
  python version = 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]```
```
##### CONFIGURATION

inventory   = ./hosts
library        = /home/actionmystique/Ansible/git-yang-networkop/ansible-101/library
forks = 1000
gathering = explicit
gather_timeout = 10
roles_path = /home/actionmystique/Ansible/Roles/roles
private_role_vars = yes
hash_behaviour = merge
log_path = /var/log/ansible.log
retry_files_enabled = False
show_custom_stats = True
timeout = 10
pipelining = True
connect_timeout = 30
connect_retries = 30
connect_interval = 1

##### OS / ENVIRONMENT
- host: Ubuntu 16.10 4.8
- target: 
  + **IOSv 15.6(2)T**
  + **IOS-XEv 16.4.1**

##### SUMMARY

cf. title, for instance with a show running-config command.

##### STEPS TO REPRODUCE

Structure passed as "**provider**": connections.ssh

```
connections
...
        ssh:
          transport: cli 
          host: "{{ ansible_host }}"
          # ansible_port
          port: 22
          # ansible_user
          username: admin
          # ansible_ssh_pass
          password: xxxxxxxxxxx
          authorize: yes
          # enable_secret_password
          auth_pass: xxxxxxxxxxx
          # private_key_file
          ssh_keyfile: "~/.ssh/id_rsa"
          version: 2
          timeout: 10
```

**Role**: ios_pull_config:

```
- include_vars: "../defaults/{{ os_family }}/connections.yml"
  when: (connections is undefined)

- name: Fetching config from the remote node
  ios_command:
        provider: "{{ connections.ssh }}"
        commands:
          - "show {{ config }}"
  register: configuration

- name: Printing {{ config }}
  debug: msg="{{ config }} on host {{ inventory_hostname }} {{ configuration.stdout_lines }}"
  ignore_errors: yes
```

**Playbook**:

```
- name: Pulling IOS/IOSv/IOSv-L2/IOS-XE/IOS-XEv (CSR-1000v) startup and running configs
  hosts:
    - iosv
    - iosv_l2
    - ios_xev
  gather_facts: no
  roles:
    - { role: ios_pull_config, config: startup-config, with_date_time: 'no' }
    - { role: ios_pull_config, config: running-config, with_date_time: 'no' }
```

##### EXPECTED RESULTS

Startup & running configurations from the target IOSv node.

##### ACTUAL RESULTS

```
...
TASK [ios_pull_config : Fetching config from the remote node] ***************************************************************************************************************
task path: /home/actionmystique/Ansible/Roles/roles/ios_pull_config/tasks/main.yml:77
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/ios/ios_command.py
<172.21.100.211> ESTABLISH LOCAL CONNECTION FOR USER: root
<172.21.100.211> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [IOSv_Spine_11] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "auth_pass": null, 
            "authorize": null, 
            "commands": [
                "show running-config"
            ], 
            "host": null, 
            "interval": 1, 
            "match": "all", 
            "password": null, 
            "port": null, 
            "provider": {
                "auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "authorize": true, 
                "host": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "ssh_keyfile": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "timeout": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "transport": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "version": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "retries": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "ssh_keyfile": null, 
            "timeout": null, 
            "username": null, 
            "wait_for": null
        }
    }, 
...
    "stdout_lines": [
        [
            "Building configuration...", 
            "", 
            "Current configuration : ********843 bytes", 
            "!", 
            "version 15.6", 
            "service timestamps debug datetime msec", 
            "service timestamps log datetime msec", 
            "service password-encryption", 
            "!", 
            "hostname IOSv_Spine_11", 
            "!", 
            "boot-start-marker", 
            "boot-end-marker", 
            "!", 
            "!", 
            "vrf definition Dev-Ops", 
            " rd 65003:********", 
            " !", 
            " address-family ipv4", 
            "  import ipv4 unicast map global-to-vrf-default-route", 
            "  export ipv4 unicast map vrf-to-global-********", 
 ...
```

The configuration is fine on the target:

```
#sh run
Building configuration...

Current configuration : 10843 bytes
!
version 15.6
service timestamps debug datetime msec
service timestamps log datetime msec
service password-encryption
!
hostname IOSv_Spine_11
!
boot-start-marker
boot-end-marker
!
!
vrf definition Dev-Ops
 rd 65003:10
 !
 address-family ipv4
  import ipv4 unicast map global-to-vrf-default-route
  export ipv4 unicast map vrf-to-global-10
 exit-address-family
...
```
