### ISSUE TITLE
Template: "AnsibleUndefinedVariable: dict object has no element 0" when using template with with_dict

### ISSUE THREAD

**Issue by fields** [ansible/ansible#24219]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 13 2017, 16:29:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### STEPS TO REPRODUCE

I’m getting an error `AnsibleUndefinedVariable: dict object has no element 0` when trying to use with_dict with a template. My dictionary (loaded from a variable file in the role) has the form:

 ```
---
users:
  a:
    name: 'xxxx'
    hash: 'xxxx'
    password: 'xxxx'
  b:
    name: 'xxxx'
    hash: 'xxxx'
    password: 'xxxx'
```

The error message seems to indicate that it’s getting each value for the dictionary properly, and I am referencing `{{ item.key }}`, `{{ item.value.name }}`, `{{ item.value.hash }}`, and `{{ item.value.password }}` in the template.

The task is:
```
- name: copy user files
  template: src=job dest=/path/to/users/{{ item.key }}/config mode=0644 owner={{ user }} group={{ user }}
  with_dict: "{{ users }}"
  notify: "Restart"
```

Am I doing something wrong here?

**Comment by ansibot** [comment]
@fields Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
needs_info please include the output from running with `ansible-playbook -vvv` when this takes fails. 

Please also dump `users`

```
- debug:
    msg: "{{ users]}}" 
```

**Comment by fields** [comment]
@gundalow using the -vvv flag does not give any more useful information for that task - it's the exact same error message except pretty printed.

This is the sanitized output from the debug task:

```
TASK [xxx : debug] *******************************************************************************************************************************************************************************
task path: /Users/fields/projects/xxx/xxx/roles/xxx/tasks/users_setup.yml:5
ok: [xx.xx.xx.xx] => {
    "changed": false,
    "msg": {
        "xxxx": {
            "hash": "xxxx",
            "name": "xxxx",
            "password": "xxxx"
        },
        "xxxx": {
            "hash": "xxxx",
            "name": "xxxx",
            "password": "xxxx"
        },
        "xxxx": {
            "hash": "xxxx",
            "name": "xxxx",
            "password": "xxxx"
        },
        "xxxx": {
            "hash": "xxxx",
            "name": "xxxx",
            "password": "xxxx"
        },
        "xxxx": {
            "hash": "xxxx",
            "name": "xxxx",
            "password": "xxxx"
        }
    }
}
```

**Comment by fields** [comment]
The output from the task that's failing looks like this:

```
TASK [xxx : copy user files] *********************************************************************************************************************************************************************
task path: /Users/fields/projects/xxx/xxx/roles/xxx/tasks/users_setup.yml:8
failed: [xx.xx.xx.xx] (item={'key': u'xxx', 'value': {u'hash': u'xxx', u'name': u'xxx', u'password': u'xxx'}}) => {
    "failed": true,
    "item": {
        "key": "xxx",
        "value": {
            "hash": "xxx",
            "name": "xxx",
            "password": "xxx"
        }
    },
    "msg": "AnsibleUndefinedVariable: dict object has no element 0"
}
```

With a line for each key in the dictionary.

**Comment by sivel** [comment]
Can you show the template as well?  With my test template of the following, it works without issue.

```
{{ item.key }}
{{ item.value.name }}
{{ item.value.hash }}
{{ item.value.password }}
```

Also, can you confirm what jinja2 version you are using?

needs_info

**Comment by fields** [comment]
I was using jinja2 2.8, but I just uninstalled that and installed 2.9.6. It did not help. I stripped the template down to just:

```
{{ item.value.name }}
{{ item.value.hash }}
{{ item.value.password }}
```

and it still did not work.

Could it be something in the values of the dict that's not getting escaped properly?

**Comment by fields** [comment]
I have tried removing everything but alphanumeric characters from the dict and I'm still getting this error.

**Comment by sivel** [comment]
Does it work with the example `users` you provided here?

```
---
users:
 a:
   name: 'xxxx'
   hash: 'xxxx'
   password: 'xxxx'
 b:
   name: 'xxxx'
   hash: 'xxxx'
   password: 'xxxx'
```

It it reproducible with the following simple playbook?

```
---
- hosts: all
  gather_facts: false
  vars:
    users:
     a:
       name: 'xxxx'
       hash: 'xxxx'
       password: 'xxxx'
     b:
       name: 'xxxx'
       hash: 'xxxx'
       password: 'xxxx'
  tasks:
    - name: copy user files
      template:
        src: 24219.j2
        dest: "./{{ item.key }}.out"
      with_dict: "{{ users }}"
```

Where `24219.j2` is:

```
{{ item.key }}
{{ item.value.name }}
{{ item.value.hash }}
{{ item.value.password }}
```
