### ISSUE TITLE
vmware_guest: fails when using customization and hostname with domain

### ISSUE THREAD

**Issue by dbosso** [ansible/ansible#24225]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

CentOS 7.3
vCenter 6.5

##### SUMMARY
Using a VM name with a domain in the name parameter to vmware_guest when creating a VM from a template, the create fails. For example, specifying myhost.example.com results in:

fatal: [myhost]: FAILED! => {"changed": true, "failed": true, "msg": "A specified parameter was not correct: spec.identity.hostName"}

whereas using simply myhost for the name succeeds.

This only occurs when using guest customization. For my example, if I leave out the networks: customization section, I do not get the error.

##### STEPS TO REPRODUCE

Run the following playbook

```yaml
---
- hosts: unprovisioned
  gather_facts: No
  connection: local

  tasks:
  - name: create the vm
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"    
      name: myhost.example.com
      state: "{{ vm_state }}"
      folder: "{{ vm_folder }}"
      datacenter: "{{ vm_datacenter }}"
      cluster: "{{ vm_cluster }}"
      template: "{{ vm_template }}"
      annotation: "{{ vm_note }}"
      wait_for_ip_address: true
      networks:
      - name: "{{ vm_net1 }}"
        device_type: vmxnet3
        ip: "{{ eth0_ip }}"
        netmask: "{{ eth0_netmask }}"
        gateway: "{{ default_gateway }}"
    register: deploy
```

##### EXPECTED RESULTS

VM creation and customization

##### ACTUAL RESULTS

"msg": "A specified parameter was not correct: spec.identity.hostName"

```
(anonymized output)

fatal: [myhost]: FAILED! => {
    "changed": true, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "annotation": "This is a test for an ansible bug report", 
            "cluster": "cluster-name", 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "datacenter", 
            "disk": [], 
            "esxi_hostname": null, 
            "folder": "/vm/foo", 
            "force": false, 
            "guest_id": null, 
            "hardware": {}, 
            "hostname": "vc.example.com", 
            "is_template": false, 
            "name": "myhost.example.com", 
            "name_match": "first", 
            "networks": [
                {
                    "device_type": "vmxnet3", 
                    "gateway": "192.168.0.1", 
                    "ip": "192.168.0.55", 
                    "name": "PrivNet", 
                    "netmask": "255.255.255.0"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": null, 
            "state": "poweredon", 
            "template": "CentOS 7 Template", 
            "template_src": "CentOS 7 Template", 
            "username": "VSPHERE.LOCAL\\ansible", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }
    }, 
    "msg": "A specified parameter was not correct: spec.identity.hostName"
}
```
