### ISSUE TITLE
netconf-config.py to add option save

### ISSUE THREAD

**Issue by wisotzky** [ansible/ansible#24220]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
module netconf-config.py

##### ANSIBLE VERSION
latest

##### SUMMARY
To improve usability of this netconf module, it is recommended to have the explicit option to make configuration changes persistent.

From [rfc6241 Section 8.7.5.1](https://tools.ietf.org/html/rfc6241#section-8.7.5.1):
```
<rpc message-id="101" xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
  <copy-config>
    <target>
      <startup/>
    </target>
    <source>
      <running/>
    </source>
  </copy-config>
</rpc>
```

Using ncclient:
```
  m.copy_config(source="running", target="startup")
```

Potentially the module should check before, if the netconf server advertises the ":startup" capability. If not, saving the configuration should generate an appropriate error message.

**Comment by ansibot** [comment]
cc @lpenz @userlerueda
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wisotzky** [comment]
Design proposal...

Add new option `save` to `argument_spec`:
```
  save=dict(type='bool', default=False),
```

Documentation:
```
  save:
    description:
      - The C(save) argument instructs the module to save the running-
        config to the startup-config at the conclusion of the module
        running.
    required: false
    default: no
    choices: ['yes', 'no']
    version_added: "2.4"
```
Once this is done, following logic should be implemented:
```
  IF changed AND option(save) THEN
    IF :startup IN netconf_server_capabilities THEN
      copy-config running => startup
   ELSE
     issue module warning message, that startup is not supported
```
