### ISSUE TITLE
ipa-hbacrule doesn't allow rule to be placed against specified host.

### ISSUE THREAD

**Issue by sc10n** [ansible/ansible#24243]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ipa-hbacrule

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
Nothing additional
##### OS / ENVIRONMENT
RHEL 7.3

##### SUMMARY
I am trying to add in an HBAC rule that only allows a user group to connect to a specified host. It won't allow a host to be specified, it keeps asking for a hostcategory. The only option it will accept is "all", which would defeat the purpose of specifying a host.

##### STEPS TO REPRODUCE
```
- name: Ensure rule to allow admins to connect
  ipa_hbacrule:
    name: "{{inventory_hostname ~ '_HBAC'}}"
    description: Allow users in the usergroup to connect to specified host
    host:
      - "{{ inventory_hostname ~ '.example.com' }}"
    usergroup:
      - admins
    servicecategory: all
    state: present
    validate_certs: no
    ipa_host: "{{int_server}}"
    ipa_user: "{{userid}}"
    ipa_pass: "{{password}}"
```
##### EXPECTED RESULTS
The expected action is to apply the the rule to the host specified by the "host:" param.
##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "repsonse hbacrule_add_host: hosts cannot be added when host category='all'"}
```

**Comment by ansibot** [comment]
cc @Nosmoht
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Nosmoht** [comment]
@sc10n,
i try to reproduce the issue but it works on my local Vagrant box.

```shell
$ ansible --version
ansible 2.3.0.0
  config file = /home/ntbc/workspace/vagrant/ipa/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 21 2016, 07:16:46) [GCC 6.2.1 20160830]
```
```shell
$ rpm -qa | grep '^ipa-' | sort
ipa-admintools-4.4.0-14.el7.centos.7.noarch
ipa-client-4.4.0-14.el7.centos.7.x86_64
ipa-client-common-4.4.0-14.el7.centos.7.noarch
ipa-common-4.4.0-14.el7.centos.7.noarch
ipa-server-4.4.0-14.el7.centos.7.x86_64
ipa-server-common-4.4.0-14.el7.centos.7.noarch
ipa-server-dns-4.4.0-14.el7.centos.7.noarch

```
Playbook
```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Ensure rule to allow admins to connect
    ipa_hbacrule:
      name: "{{inventory_hostname ~ '_HBAC'}}"
      description: Allow users in the usergroup to connect to specified host
      host:
        - "{{ inventory_hostname ~ '.example.com' }}"
      usergroup:
        - admins
      servicecategory: all
      state: present
      validate_certs: no
      ipa_host: "ipa-server.example.com"
      ipa_user: admin
      ipa_pass: t0ps3cr3t
```
```shell
$ ansible-playbook ansible-issue-24243.yml
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ************************************************************************

TASK [Ensure rule to allow admins to connect] *******************************************
changed: [localhost]

PLAY RECAP ******************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0   
```
Could you please provide me more information that might help me to reproduce it?

**Comment by sc10n** [comment]
Thank you for looking into this. Here is the list of IPA packages that are on the client I am trying to create the HBAC for. The only difference in how you are running it vs, how I am is that the role is being included in a much larger playbook. Would delegating the task to the IPA server make a difference? 
````
[jamie@example ~]$ rpm -qa | grep '^ipa-' | sort
ipa-client-4.4.0-14.el7.centos.7.x86_64
ipa-client-common-4.4.0-14.el7.centos.7.noarch
ipa-common-4.4.0-14.el7.centos.7.noarch
````

Here are the packages from the IPA server
```
[admin@ipa-server ~]$ rpm -qa | grep '^ipa-' | sort
ipa-admintools-4.4.0-14.el7_3.7.noarch
ipa-client-4.4.0-14.el7_3.7.x86_64
ipa-client-common-4.4.0-14.el7_3.7.noarch
ipa-common-4.4.0-14.el7_3.7.noarch
ipa-python-compat-4.4.0-14.el7_3.7.noarch
ipa-server-4.4.0-14.el7_3.7.x86_64
ipa-server-common-4.4.0-14.el7_3.7.noarch
ipa-server-dns-4.4.0-14.el7_3.7.noarch
````

**Comment by ansibot** [comment]
cc @akasurde
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hit0ri** [comment]
I'm having the same issue.
`ipa-hbacrule` fails to add hosts to the rules that have `hostcategory` attribute set to `all`.
I think `ipa-hbacrule` should first check for this attribute and then unset it (in case it is present) before adding hosts.

Modified playbook

```
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
  - name: Ensure rule to allow admins to connect (hostcategory=all)
    ipa_hbacrule:
      name: "{{inventory_hostname ~ '_HBAC'}}"
      description: Allow users in the usergroup to connect to specified host
      hostcategory: all
      usergroup:
        - admins
      servicecategory: all
      state: present
      validate_certs: no
      ipa_host: "ipa-server.example.com"
      ipa_user: admin
      ipa_pass: t0ps3cr3t

  - name: Ensure rule to allow admins to connect
    ipa_hbacrule:
      name: "{{inventory_hostname ~ '_HBAC'}}"
      description: Allow users in the usergroup to connect to specified host
      host:
        - "{{ inventory_hostname ~ '.example.com' }}"
      usergroup:
        - admins
      servicecategory: all
      state: present
      validate_certs: no
      ipa_host: "ipa-server.example.com"
      ipa_user: admin
      ipa_pass: t0ps3cr3t
```

```
$ ansible --version
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/hitori/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

```
$ rpm -qa | grep '^freeipa-' | sort
freeipa-client-4.6.3-2.fc27.x86_64
freeipa-client-common-4.6.3-2.fc27.noarch
freeipa-common-4.6.3-2.fc27.noarch
freeipa-server-4.6.3-2.fc27.x86_64
freeipa-server-common-4.6.3-2.fc27.noarch
freeipa-server-dns-4.6.3-2.fc27.noarch
```
