### ISSUE TITLE
difflib-based module fails to produce diff markers

### ISSUE THREAD

**Issue by danielhneville** [ansible/ansible#24255]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Writing a module using python difflib's ndiff

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
in the ansible.cfg file: `ssh_args = -o ControlMaster=auto -o ControlPersist=60s`

##### OS / ENVIRONMENT
macOS Sierra 10.12.4

##### SUMMARY
Attempting to use any of the python 2.7 difflib methods within an ansible module strips the diff markers from the output.

##### STEPS TO REPRODUCE
example of the module as written:
```
from difflib import ndiff
from ansible.module_utils.basic import AnsibleModule

FIELDS = dict(
    file_a=dict(required=True),
    file_b=dict(required=True),
    dest=dict(required=True)
)

MODULE = AnsibleModule(argument_spec=FIELDS)

file_a = open(MODULE.params['file_a']).readlines()
file_b = open(MODULE.params['file_a']).readlines()
dest = open(MODULE.params['dest'], 'w+')

def main():
    config_diff = list(ndiff(file_a, file_b))
    dest.writelines(config_diff)
    MODULE.exit_json(changed=True)

if __name__ == '__main__':
    main()
```

Run the differ with a task, for example:
```yaml
- task: Compare output
   diff_print:
      file_a: "{{ playbook_dir }}/files/original.txt"
      file_b: "{{ playbook_dir }}/files/revised.txt"
      dest: "{{ playbook_dir }}/files/diff.txt"
```

##### EXPECTED RESULTS

I expect the module to save a diff to a file, including all the diff markers that ndiff (or Differ, or any other difflib thing that I've tried) produces.

##### ACTUAL RESULTS

I get the diff file, but none of the diff markers are there.

##### WHAT I'VE TRIED
I've tried many of the options within difflib, and they all produce the same problem. I can run the diff from the command line using exactly the same code and get the result I need. So it seems to be something within Ansible that is preventing difflib from working properly.
