### ISSUE TITLE
FEAT: ios_config module save: option

### ISSUE THREAD

**Issue by staffordrau** [ansible/ansible#24251]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /usr/local/rancid/ansible/ntc_stuff/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Currently, when using the save: yes option to the ios_config module, the running config is written to the startup config regardless of whether any changes were needed to be made. I'm requesting that this option be changed or have another choice added where the running config is only written to the startup config when the ios_config task actually produces a change to the running config. This would preserve idempotency for the ios_config module when the save: option is used.
##### STEPS TO REPRODUCE

```yaml
  tasks:
  - name: configure logging
    ios_config:
      src: "configs/logging.cfg"
      provider: "{{ ios_provider }}"
      save: if_changed
```

##### EXPECTED RESULTS

I'd like the above to save the config on that device if and only if the task produced a change.
##### ACTUAL RESULTS

```
With the current save: yes option, the save is executed even if no config changes were needed.

See: https://github.com/ansible/ansible/issues/22727
```
