### ISSUE TITLE
rds module doesn't correctly detect and apply changes

### ISSUE THREAD

**Issue by nergdron** [ansible/ansible#24268]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rds module (https://docs.ansible.com/ansible/rds_module.html)

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.0.0
  config file = /home/tessa/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
RDS module doesn't correctly see all changes, and skips applying important changes to configuration. We're specifically having problems with changes to parameter_group not being applied.

##### STEPS TO REPRODUCE
```yaml
- rds:
    command: create
    db_name: "{{ item.value.name | default(item.key) }}"
    region: "{{ region }}"
    instance_name: "{{ prefix }}-{{ item.key }}"
    db_engine: "{{ item.value.db_engine }}"
    engine_version: "{{ item.value.engine_version }}"
    parameter_group: "{{ item.value.parameter_group }}"
    instance_type: "{{ item.value.instance_type | default(rds_default_type) }}"
    size: "{{ item.value.size_gb }}"
    subnet: "{{ prefix }}-rds-subnet-group"
    username: "{{ item.value.username }}"
    password: "{{ item.value.password }}"
  with_dict: "{{ databases }}"
```

##### EXPECTED RESULTS
Apply new parameter_group.

##### ACTUAL RESULTS
```
ok: [localhost] => (item={'key': u'test', 'value': {u'username': u'test', u'size_gb': u'100', u'db_engine': u'postgres', u'parameter_group': u'test-postgres95', u'engine_version': u'9.5.6', u'db_name': u'test, u'password': u'test'}}) => {"changed": false, "instance": {"availability_zone": "us-west-2a", "backup_retention": 1, "create_time": 1493325056.486, "endpoint": "something.us-west-2.rds.amazonaws.com", "id": "test", "instance_type": "db.t2.small", "iops": null, "maintenance_window": "fri:11:03-fri:11:33", "multi_zone": false, "port": 5432, "replication_source": null, "status": "available", "username": "test"}, "item": {"key": "test", "value": {"db_engine": "postgres", "db_name": "test", "engine_version": "9.5.6", "parameter_group": "test-postgres95", "password": "test" "size_gb": "100", "username": "test"}}}
```

The important part is the "changed": false, which shows it hasn't applied anything. Looking at the instance itself, even after manually restarting, it still has the old (default) parameter-group.
