### ISSUE TITLE
Ansible Redshift Module erros when wait:true

### ISSUE THREAD

**Issue by annapurnam** [ansible/ansible#24267]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### ANSIBLE VERSION

```
2.3.0.0
```

##### SUMMARY

Ansible Module : redshift erros out when wait value is true/yes
It doenst error when it is false or no.
##### STEPS TO REPRODUCE
Any redshift module, add wait: yes in yml file

```yaml
local_action:
        module: redshift
        command: create
        identifier: "x1234"
        node_type: "{{ redshift_node_type  }}"
        username: "ds2.xlarge"
        password: "xxxxxx"
        db_name: "x1234"
        cluster_type: multi-node
        encrypted: true
        number_of_nodes: "4"
        automated_snapshot_retention_period: "35"
        port: 5439
        allow_version_upgrade: false
        publicly_accessible: false
        vpc_security_groups: "SG's"
        param_group_name: "param-group-name"
        subnet: "ssubnet-12344"
        zone: us-east-1a
        maint_window: "mon:03:00-mon:03:30"
        wait: yes
        wait_timeout: 300
      register: redshift_example
      tags:
        - redshift

```

##### EXPECTED RESULTS

Should cretae redshift cluster successfully
##### ACTUAL RESULTS

fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/vd/c64ynx3d16vf7nbllrsqdw6ddnhrlt/T/ansible_osq1hY/ansible_module_redshift.py\", line 480, in <module>\n    main()\n  File \"/var/folders/vd/c64ynx3d16vf7nbllrsqdw6ddnhrlt/T/ansible_osq1hY/ansible_module_redshift.py\", line 462, in main\n    (changed, cluster) = create_cluster(module, conn)\n  File \"/var/folders/vd/c64ynx3d16vf7nbllrsqdw6ddnhrlt/T/ansible_osq1hY/ansible_module_redshift.py\", line 288, in create_cluster\n    wait_timeout = time.time() + wait_timeout\nTypeError: unsupported operand type(s) for +: 'float' and 'str'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

```

```
