### ISSUE TITLE
digital_ocean_tag reporting that tag on droplet changed, when it didn't.

### ISSUE THREAD

**Issue by brad2014** [ansible/ansible#24265]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

digital_ocean_tag

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/brad/Projects/systems/vpn/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

MacOS

##### SUMMARY

When using digital_ocean_tag to create a tag, the task is marked "changed" even if the tag already exists.  When using digital_ocean_tag to apply a tag to a droplet, the task is marked "changed" even if the droplet already has that tag.  

##### STEPS TO REPRODUCE

Simply run the playbook containing that task twice, and notice that it is "changed" the second time.

```yaml
    - name: Tag the droplet
      digital_ocean_tag:
        name: "{{ do_tag }}"
        resource_id: "{{ do.droplet.id }}"
        api_token: "{{ do_token }}"
        state: present

```

##### EXPECTED RESULTS

When the state is "present", and the tag is already present on the droplet, the task result should be "ok", not "changed".

##### ACTUAL RESULTS

The task result is invariably "changed" (even when the droplet tag state did not change).
