### ISSUE TITLE
Add 'slaves' parameter to 'alternatives' module

### ISSUE THREAD

**Issue by aklemp** [ansible/ansible#24278]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
alternatives

##### ANSIBLE VERSION
```
ansible 2.3.0.0 (stable-2.3 4b5553c97f) last updated 2017/04/23 13:15:41 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The tool `update-alternatives` allows slaves to be managed with a parent alternative, so for example manpages point to the version matching the selected tool. This should be possible in the `alternatives` module as well.

##### STEPS TO REPRODUCE
This is the proposal of the new parameter using `nc` example on a Debian system.
```yaml
- name: install alternative with slaves
  alternatives:
    name: "nc"
    link: "/bin/nc"
    path: "/bin/nc.traditional"
    priority: 10
    slaves:
      - name: "nc.1.gz"
        link: "/usr/share/man/man1/nc.1.gz"
        path: "/usr/share/man/man1/nc.traditional.1.gz"
      - name: "netcat"
        link: "/bin/netcat"
        path: "/bin/nc.traditional"
      - name: "netcat.1.gz"
        link: "/usr/share/man/man1/netcat.1.gz"
        path: "/usr/share/man/man1/nc.traditional.1.gz"
  become: yes
```

##### EXPECTED RESULTS
The listed slaves are installed with the parent. If single slaves are missing, they should be installed without changing the others.

##### ACTUAL RESULTS
Currently, the `shell` command must be used as a workaround.
