### ISSUE TITLE
win_user does not create user

### ISSUE THREAD

**Issue by Pantharian** [ansible/ansible#24285]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
'win_user' module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
```

##### SUMMARY
'win_user' module fails to create the specified user

The same playbook run with Ansible 2.2.1.0 creates the user.

##### STEPS TO REPRODUCE
When

```
---
- name: Add new windows user
  hosts: all 
  gather_facts: False
  tasks:
    - name: Add 'NewUser'
      win_user:
        name: NewUser
        password: ["NewUserPassword"]
        state: ["present"]
```
##### EXPECTED RESULTS

```
PLAY [Add new windows user] ****************************************************

TASK [Add 'NewUser'] ***********************************************************
changed: [windows] => {"account_disabled": false, "account_locked": false, "changed": true, 
"description": "", "fullname": "NewUser", "groups": [], "name": "NewUser", "password_expired": false, 
"password_never_expires": false, "path": "WinNT://WORKGROUP/MSEDGEWIN10/NewUser", "sid": 
"S-1-5-21-2136340953-1270018429-413759281-1026", "state": "present", 
"user_cannot_change_password": false}

PLAY RECAP *********************************************************************
windows                    : ok=1    changed=1    unreachable=0    failed=0  
```
##### ACTUAL RESULTS

```
PLAY [Add new windows user] ****************************************************

TASK [Add 'NewUser'] ***********************************************************
ok: [windows] => {"changed": false, "msg": "User 'NewUser' was not found", "name": "NewUser", 
"state": "absent"}

PLAY RECAP *********************************************************************
windows                    : ok=1    changed=0    unreachable=0    failed=0 
```
