### ISSUE TITLE
registered dictionary variable (with command output) should always have "failed" key

### ISSUE THREAD

**Issue by maxgalbu** [ansible/ansible#24288]
##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Nothing changed

##### OS / ENVIRONMENT
Centos 7.2

##### COMPONENT NAME
`when` and `register`

##### SUMMARY
A `register`ed variable, with command output, should always have "failed"

##### STEPS TO REPRODUCE
With these tasks:

```yaml
- name: Check if package.json changed
  become: no
  run_once: true
  register: package_json_copy
  ignore_errors: yes
  local_action:
    module: copy
    src: ./src/package.json
    dest: ./oldsrc/package.json

- name: Installing npm deps
  become: no
  run_once: true
  when: (package_json_copy.failed is defined and package_json_copy.failed) or (package_json_copy.changed is defined and package_json_copy.changed)
  local_action:
    module: npm
    path: ./src

- name: Copying npm deps
  become: no
  run_once: true
  when: not(package_json_copy.failed) and not(package_json_copy.changed)
  local_action:
    module: copy
    src: ./oldsrc/node_modules
    dest: ./src/node_modules
```

The "Check if package.json changed" can fail, but if it doesn't, `package_json_copy.failed` is not defined, and this forces me to:

```yaml
#from this:
not(package_json_copy.failed) and not(package_json_copy.changed)

#I'm forced to use this
(package_json_copy.failed is not defined or (package_json_copy.failed is defined and not(package_json_copy.failed))) and not(package_json_copy.changed)
```

##### EXPECTED RESULTS
The `variable.failed` should always be defined

##### ACTUAL RESULTS
```
fatal: [10.0.10.36]: FAILED! => {"failed": true, "msg": "The conditional check 'not(package_json_copy.failed) and not(package_json_copy.changed)' failed. The error was: error while evaluating conditional (not(package_json_copy.failed) and not(package_json_copy.changed)): 
'dict object' has no attribute 'failed'\n\nThe error appears to have been in '/vagrant/deploy-front-ansible/before.yaml': line 36, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copying 
npm deps\n  ^ here\n"}
```
