### ISSUE TITLE
Clearing facts (to refresh them) does not work

### ISSUE THREAD

**Issue by yajo** [ansible/ansible#24295]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- meta
- setup

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION

None.

##### OS / ENVIRONMENT

```
➤ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 25 (Twenty Five)
Release:	25
Codename:	TwentyFive
```

##### SUMMARY

If you need to reload some facts (in my case I need the VPN IP after I configured it), it does not work

##### STEPS TO REPRODUCE

Option A:

```yaml
- name: vpn client must be running
  service:
    name: openvpn@example
    enabled: true
    state: started

- name: refresh facts
  setup:
```

Option B:

```yaml
- name: vpn client must be running
  service:
    name: openvpn@example
    enabled: true
    state: started

- name: refresh facts
  meta: clear_facts
```

##### EXPECTED RESULTS

Facts reloaded, VPN ip data available.

##### ACTUAL RESULTS

Option A: 

```
TASK [vpn-client : refresh facts] ********************************************************************************************************************
ok: [server.example.com]
```

... but later another task fails with:

```
fatal: [server.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'ansible_tun0' is undefined"}
```

Option B:

```
TASK [vpn-client : refresh facts] *********************************************************************************************************
fatal: [server.example.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to server.example.com closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

##### WORKAROUND

Run the playbook again 😞

**Comment by nitzmahone** [comment]
I'm guessing you have a race condition in your play logic here- just because you started a service to open a VPN connection doesn't mean it's done what it needs to do before you refresh the facts. You might want to add an until loop with delay on the setup task so it will re-run every few seconds until the fact you need is available...

I *think* `meta: clear_facts` is only supposed to clear any cached facts from a backing store (eg, redis/memcached/file cache), but waiting for response from @bcoca about that, since I think he wrote it.

**Comment by bcoca** [comment]
So from option A, it seems like a race condition, option B ...the error makes no sense as `meta:` does not connect to the remote host.

**Comment by yajo** [comment]
Is it possible that clearing facts clears also the connection variables `ansible_port`, `ansible_user`, etc?

PS: Gonna try the race condition and will report back.

**Comment by yajo** [comment]
Fine, the race condition has been fixed with your suggestion, @nitzmahone, thank you very much!:

```yaml
- name: refresh facts to know the vpn connection details
  setup:
  until: ansible_tun0 is defined
  delay: 5
  retries: 6
```

There's still the problem with disconnecting when using option B, not sure if it is a bug, maybe you want to keep this open for that, although on my side this can be closed.
