### ISSUE TITLE
Stat module cause 'dict object' has no attribute 'islnk' if path does not exist

### ISSUE THREAD

**Issue by shrabok-surge** [ansible/ansible#24296]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
stat module: http://docs.ansible.com/ansible/stat_module.html

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /my_working_dir/ansible.cfg
  configured module search path = [u'/usr/share/ansible', u'./library']
  python version = 2.7.12 (default, Oct 11 2016, 05:24:00) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
OSX Darwin Kernel 15.6.0
Centos 7

##### SUMMARY
As per the documentation to check if a folder or file exists and is a symlink you can run:
```
- debug:
    msg: "Path exists and isn't a symlink"
  when: sym.stat.islnk is defined and sym.stat.islnk == False
```

We were using this in ansible <= 2.2 and it would not fail, since upgrading to 2.3 we found if you run you will get an error with:
```
'dict object' has no attribute 'islnk'
```

##### STEPS TO REPRODUCE

```yaml
- name: Check for ebs database volume mount
  stat:
    path: "/database"
  register: db_volume

- name: Check for mysql dir is symlink
  stat:
    path: "/var/lib/mysql"
  register: data_dir

- debug:
    msg: "{{ data_dir }} {{ db_volume }}"

- name: Delete mysql dir if not symlink
  file:
    path: "/var/lib/mysql"
    state: absent
  when: (data_dir is defined and data_dir.stat.islnk == False) and (db_volume is defined and db_volume.stat.exists)

- name: Symlink mysql directory to ebs database volume if exists
  file:
    state: link
    src: "/database"
    dest: "/var/lib/mysql"
  when: db_volume.stat.exists
```

##### EXPECTED RESULTS

Expected stat to work as previous versions and per documentation that it would contain the islnk object as False to not fail with an undefined dict_ojbect

##### ACTUAL RESULTS

We get the following error:
```
fatal: [10.254.3.208]: FAILED! => {"failed": true, "msg": "The conditional check '(data_dir is defined and data_dir.stat.islnk == False) and (db_volume is defined and db_volume.stat.exists)' failed.
The error was: error while evaluating conditional ((data_dir is defined and data_dir.stat.islnk == False) and (db_volume is defined and db_volume.stat.exists)): 'dict object' has no attribute 'islnk'

The error appears to have been in '/my_working_dir/roles/mysql/tasks/RedHat.yml': line 15, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
- name: Delete mysql dir if not symlink
  ^ here"}
```

```
TASK [mysql : include_vars] *************************************************************************************************************************************
ok: [10.254.3.208]

TASK [mysql : Check for ebs database volume mount] **************************************************************************************************************

ok: [10.254.3.208]

TASK [mysql : Check for mysql dir is symlink] *******************************************************************************************************************
ok: [10.254.3.208]

TASK [mysql : debug] ********************************************************************************************************************************************
ok: [10.254.3.208] => {
    "changed": false,
    "msg": "{u'stat': {u'exists': False}, u'changed': False}  {u'stat': {u'isuid': False, u'uid': 0, u'exists': True, u'attr_flags': u'', u'woth': False, u'isreg': False, u'device_type': 0, u'mtime': 1493908395.367564, u'block_size': 4096, u'inode': 64, u'isgid': False, u'size': 6, u'executable': True, u'charset': u'binar
y', u'readable': True, u'version': u'', u'pw_name': u'root', u'gid': 0, u'ischr': False, u'wusr': True, u'writeable': True, u'mimetype': u'inode/directory', u'bl
ocks': 0, u'xoth': True, u'islnk': False, u'nlink': 2, u'issock': False, u'rgrp': True, u'gr_name': u'root', u'path': u'/database', u'xusr': True, u'atime': 0.0,
 u'isdir': True, u'ctime': 1493908395.367564, u'isblk': False, u'wgrp': False, u'xgrp': True, u'dev': 64768, u'roth': True, u'isfifo': False, u'mode': u'0755', u
'rusr': True, u'attributes': []}, u'changed': False}"
}

TASK [mysql : Delete mysql dir if not symlink] ******************************************************************************************************************

fatal: [10.254.3.208]: FAILED! => {"failed": true, "msg": "The conditional check '(data_dir is defined and data_dir.stat.islnk == False) and (db_volume is define
d and db_volume.stat.exists)' failed. The error was: error while evaluating conditional ((data_dir is defined and data_dir.stat.islnk == False) and (db_volume is
 defined and db_volume.stat.exists)): 'dict object' has no attribute 'islnk'\n\nThe error appears to have been in '/my_working_dir/roles/mysql/tasks/RedHat.yml': line 15, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending li
ne appears to be:\n\n\n- name: Delete mysql dir if not symlink\n  ^ here\n"}
```

**Comment by nitzmahone** [comment]
I'm surprised that this worked in 2.2.x- regardless, `data_dir` will always be defined. To make this work right with the short-circuit (so you don't get the missing key error), you should change the when to:
`(data_dir.stat.exists and data_dir.stat.islnk == False) and (db_volume.stat.exists)`

**Comment by shrabok-surge** [comment]
We run this before installing mysql so the data_dir does not exist at this time. This is something we do to accommodate an lvm partition provided by ebs volume, I'll see what happens with your recommendation.

**Comment by nitzmahone** [comment]
The file may not exist, but the `data_dir` variable (at least in the sample you provided) should always be defined, so that check is redundant.

**Comment by shrabok-surge** [comment]
ah I see, so still the missing data_dir.stat.islnk == False will not work because object data_dir.stat.islnk is not defined as per the debug:
{u'stat': {u'exists': False}, u'changed': False}

**Comment by nitzmahone** [comment]
Correct, but if you short-circuit that check with another one that evaluates to False first (eg, the .exists check), it won't run, and thus won't fail. Like I said, I'd be surprised if that ever really worked for you in older versions (I tested it on 2.2 and it failed the same way). If it did, it was a fluke.

**Comment by shrabok-surge** [comment]
Double checked an you are right, that was very helpful, Thanks!

**Comment by stejoo** [comment]
I have a similar issue as sharbok-surge. I have been unable to resolve it yet. This is a bit of the tasks:

```
- name: "Install : Create TeamSpeak {{ teamspeak.version }} Server directory"
  file:
    path: "{{ teamspeak.home }}/teamspeak3-server_linux_amd64-{{ teamspeak.version }}"
    state: directory
    owner: "{{ teamspeak.user }}"
    group: "{{ teamspeak.user }}"
  register: mkdir

# If a new directory has been created, check for (current) user data.
- name: "Install : Checking for a currently installed TeamSpeak 3 Server with user data"
  stat:
    path: "{{ teamspeak.home }}/{{ teamspeak.symlink }}/teamspeak3-server_linux_amd64/files"
  register: userdata
  when: mkdir.changed

# If user data has been found, this is an upgrade situation.
- include: ts3update.yml
  when: userdata.stat.exists is defined and userdata.stat.exists == True
```

The error is similar:
```
TASK [teamspeak : Install : Create TeamSpeak 3.0.13.6 Server directory] *******************************************************************************************************************************************
ok: [myhostname]

TASK [teamspeak : Install : Checking for a currently installed TeamSpeak 3 Server with user data] *****************************************************************************************************************
skipping: [myhostname]

TASK [teamspeak : Update : Check if a TeamSpeak 3 Server systemd service unit exists] *****************************************************************************************************************************
fatal: [myhostname]: FAILED! => {"failed": true, "msg": "The conditional check '(userdata.stat.exists is defined and userdata.stat.exists == True)' failed. The error was: error while evaluating conditional ((userdata.stat.exists is defined and userdata.stat.exists == True)): 'dict object' has no attribute 'stat'\n\nThe error appears to have been in '/home/stefan/Projects/ansible/roles/teamspeak/tasks/ts3update.yml': line 4, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Update : Check if a TeamSpeak 3 Server systemd service unit exists\"\n  ^ here\nThis one looks easy to fix.  It seems that there is a value started\nwith a quote, and the YAML parser is expecting to see the line ended\nwith the same kind of quote.  For instance:\n\n    when: \"ok\" in result.stdout\n\nCould be written as:\n\n   when: '\"ok\" in result.stdout'\n\nOr equivalently:\n\n   when: \"'ok' in result.stdout\"\n"}
```

I have tried variations with parenthesis ( `(userdata.stat.exists is defined and userdata.stat.exists == True)` ) as well. And dropped the `if defined` part. However that part does make sense to me in my code, because it can actually be missing if the `file` task did not notice a change that would register  the `mkdir` to trigger the check for user data.

This worked for me in Ansible 2.2 as well. I expected this code to get skipped because the conditional fails when userdata.stat.exists does not exist. 

If you have some tips to try and resolve the issue I would be grateful.
