### ISSUE TITLE
Allow ini_file module to handle keys without values

### ISSUE THREAD

**Issue by MarcinOrlowski** [ansible/ansible#24294]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ini_file

##### SUMMARY
mysql/mariadb config files are pretty close to what ini file is yet they do allow just keys, without values. Unfortunately ini_file module does not allow anything like that, which prevents using this module to manage mysql/mariadb config file. Imaginary mysql.cnf file can look like this:

     [mysql]
     skip-name-resolve
     max_connections=5000

and it would be useful to be able to create `skip-name-resolve` entry with `ini_file`. Unfortunately neither skipping `value` argument does not help as `None` is then used as value instead.

    - ini_file
         src: .....
         section: "mysqld"
         option: "skip-name-resolve"

would produce

    [mysql]
    skip-name-resolve = None

That would probably additional option to enable such behavior like `allow_no_values`. Also, if that would be possible to have this feature introduced, we'd need option to do that in a loop (so i.e. `null` would no be converted to `None` if `allow_no_values` is on), i.e.:

    - ini_file
         src: .....
         section: "mysqld"
         option: "{{ item.o }}"
         value: "{{ item.v }}"
       with_items:
          - { o: "skip-name-resolve", v: null }
          - { o: "max_connections", v: "500" }

**Comment by ansibot** [comment]
cc @jpmens @noseka1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jpmens** [comment]
needs_contributor

**Comment by fridim** [comment]
Cc @jpmens created PR #24442

**Comment by ghost** [comment]
I'm facing the same issue when doing:

```yaml
- name: ensure instances are persisted in static inventory
  ini_file:
    path: ventures/{{ venture_name }}/hosts
    section: "{{ environment_name }}"
    value: "{{ item.private_ip_address }} ansible_user=userfoo"
  with_items: "{{ launched_instances.instances }}"
  delegate_to: localhost
  become: no
```
results in:
```ini
[staging]
None = 10.10.1.202 ansible_user=userfoo
None = 10.10.7.123 ansible_user=userfoo
None = 10.10.5.123 ansible_user=userfoo
```

Maybe a `raw` option for the `ini_file` module could be nice too.
