### ISSUE TITLE
filetree usage fails to log any task information when files don't exist

### ISSUE THREAD

**Issue by MGD1981** [ansible/ansible#24300]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
with_filetree

##### ANSIBLE VERSION
ansible 2.2.1.0

##### CONFIGURATION
private_key_file = <path to private key>
host_key_checking = False

##### OS / ENVIRONMENT
CentOS Linux release 7.2.1511

##### SUMMARY
Using the "with_filetree" function as part of the file module or as part of the template module logs no information about the task when the "with_filetree" value is a path that contains no files -- even when run in maximum verbosity (-vvvv). This was discovered by accident, because I'd forgotten to populate the source directory at which with_filetree was supposed to look, but this logging bug made it very difficult to figure out what was wrong.

##### STEPS TO REPRODUCE
1. Create an ansible-playbook which uses the "with_filetree" option as part of a "file" task or a "template" task.
2. In the "with_filetree" field, use a path that contains no files.
3. Run the playbook with maximum verbosity (-vvvv) and watch the logs.

```yaml
  - name: Ensure configuration file directory structure
    file: 
      path: "{{ config_dest }}/{{ item.path }}"
      state: directory
    with_filetree: "{{ config_source }}/{{ env }}"
    when: item.state == 'directory'
  - name: Transfer configuration files
    template:
      src: "{{ item.src }}"
      dest: "{{ config_dest }}/{{ item.path }}"
    with_filetree: "{{ config_source }}/{{ env }}"
    when: item.state == 'file'
```

##### EXPECTED RESULTS
Either a task result "skipping" with the skip_reason "No files in filetree path" or a task result "ok".  No result indicates that the task was not even acknowledged.

##### ACTUAL RESULTS
```
TASK [Ensure configuration file directory structure] ***************************
task path: /home/bamboo/bamboo/xml-data/build-dir/7241730-7340034/deployment.yml:54

TASK [Transfer configuration files] ********************************************
task path: /home/bamboo/bamboo/xml-data/build-dir/7241730-7340034/deployment.yml:60
```
