### ISSUE TITLE
FEAT: ios_/nxos_/eos_compare_run_start

### ISSUE THREAD

**Issue by staffordrau** [ansible/ansible#24303]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ios_compare_run_start, nxos_compare_run_start, etc
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

I'd like to request a set of network modules to compare the running_config with the startup_config on ios, nxos, and eos, output any diffs, and optionally save the running config to the startup config.
##### STEPS TO REPRODUCE

```yaml
---
- name: compare running-config with startup-config
  hosts: dogfood-net
  gather_facts: no
  connection: local

  tasks:
  - name: compare configs
    ios_compare_run_start:
            save: if_different
    register: config_diffs
```

##### ACTUAL RESULTS

```

```
