### ISSUE TITLE
Ansible 2.3 Datadog module: No handlers could be found for logger dd.datadogpy

### ISSUE THREAD

**Issue by vanomashey** [ansible/ansible#24325]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
datadog module

##### ANSIBLE VERSION
2.3

##### SUMMARY
We assume there is an issue with Ansible 2.3 Datadog module.

After upgrade of Ansible to 2.3 and Python to 2.7.12 we have faced following issue when using Datadog module. Googling around does not really help. 

TASK [datadog-monitor : Module name] ***************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "No handlers could be found for logger \"dd.datadogpy\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_2Gi1Dz/ansible_module_datadog_monitor.py\", line 343, in <module>\n    main()\n  File \"/tmp/ansible_2Gi1Dz/ansible_module_datadog_monitor.py\", line 202, in main\n    install_monitor(module)\n  File \"/tmp/ansible_2Gi1Dz/ansible_module_datadog_monitor.py\", line 289, in install_monitor\n    monitor = _get_monitor(module)\n  File \"/tmp/ansible_2Gi1Dz/ansible_module_datadog_monitor.py\", line 225, in _get_monitor\n    if monitor['name'] == module.params['name']:\nTypeError: string indices must be integers, not str\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

---------

ansible --version
ansible 2.3.0.0
  config file = <pass to folder>/ansible/ansible.cfg
  configured module search path = [u'library']
  python version = 2.7.12 (default, Jul 18 2016, 15:02:52) [GCC 4.8.4]

OS: Ubuntu

**Comment by ansibot** [comment]
@vanomashey Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@vanomashey Thanks for reporting this issue. Could you please provide your Ansible playbook sample ?

**Comment by vanomashey** [comment]
Hi @Akasurde,

Thank you for prompt reply.

This is my yml file:

```
# Install Datadog Monitors
- hosts: localhost
  connection: local
  roles:
    - { role: datadog-monitor, tags: ['datadog-monitor'] }
```

And this is a datadog-monitor role: 

```
- name: Create Datadog Server can connect
  datadog_monitor:
    type: "service check"
    name: "Masters can connect"
    state: "present"
    notify_no_data: true
    no_data_timeframe: 30
    query: '"mesos_master.can_connect".over("type:dcos").last(4).count_by_status()'
    message: "Mesos Masters"
    api_key: "{{ dd_api_key }}"
    app_key: "{{ dd_app_key }}"
  tags:
    - mesos
```
