### ISSUE TITLE
Not able to create new instance with custom user image in azure with Ansible playbook.

### ISSUE THREAD

**Issue by param3sh** [ansible/ansible#24328]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.3.0.0
```

##### SUMMARY
I am not able to create instance from my custom image in azure but at the same time i am able to create instance with available images in the market.

##### STEPS TO REPRODUCE

```yaml
    - name: Create VM in azure
      azure_rm_virtualmachine:
        client_id: <my client id>
        tenant: <My tenant id>
        secret: <my secret key>
        subscription_id: <my subscription>
        resource_group: my-resource-group
        image: <my custom image name>
        name: ansibleTestVM
        location: 'eastus2'
        admin_username: 'myusername'
        admin_password: 'mypassword'
        os_type: Linux
        storage_account_name: mystorage
        vm_size: Standard_D1
        tags:
          Name: Ansible_test_tag
          Queqe: Q4
        network_interface_names: 'ansibleTestVM1-nic'
```

##### ACTUAL RESULTS

```

```
