### ISSUE TITLE
Datacenter should not be required in modules vmware_guest_facts and vmware_guest_snapshot

### ISSUE THREAD

**Issue by gormux** [ansible/ansible#24321]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest_facts
vmware_guest_snapshot

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

datacenter is required by the plugin, but it is not in reality

##### STEPS TO REPRODUCE

```yaml
      vmware_guest_snapshot:
        hostname: my-vmware
        username: user
        password: pass
        #datacenter: my-dc
        validate_certs: no
        snapshot_name: test
        name: my-vm
      delegate_to: localhost
```

##### EXPECTED RESULTS

It should work without datacenter

##### ACTUAL RESULTS

"msg": "missing required arguments: datacenter"

On these plugins, required should be set to false for datacenter

```

```
