### ISSUE TITLE
issue with changing permissions of directories and files using file module for ansible 2.3 

### ISSUE THREAD

**Issue by vvs1987** [ansible/ansible#24363]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
 file module

##### ANSIBLE VERSION
2.3.0
```

```

##### SUMMARY

i have been trying to change permission of directories and files in a mount point using file module . 
so while changing permissions from any random value to 755 for directories all the files and directories get changed . 
Please note i am no trying to use shell or command module as its not allowed . 

##### STEPS TO REPRODUCE

```yaml

  tasks:
     - file:
         path: /tmp/apps/abc
         state: directory
         mode: 0755
         recurse: yes
     - file:
         path: /tmp/apps/abc
         state: file
         mode: 0644
         recurse: yes

```

##### EXPECTED RESULTS

i expected : 
first part to change all directories to 755 -- this step changes all files and directories to 755
second part to change all files to 644 - this fails with below output , as files cant be used with recursive . 

##### ACTUAL RESULTS

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "failed": true,
    "gid": 513,
    "group": "domusers",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "content": null,
            "delimiter": null,
            "diff_peek": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": null,
            "mode": 420,
            "original_basename": null,
            "owner": null,
            "path": "/tmp/apps/apps",
            "recurse": true,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "file",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "mode": "0755",
    "msg": "recurse option requires state to be 'directory'",
    "owner": "vvs",
    "path": "/tmp/apps/abc",
    "size": 4096,
    "state": "directory",
    "uid": 284090
}
        to retry, use: --limit @/home/vvs/filepermission1.retry

PLAY RECAP ******************************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1

```

```

**Comment by vvs1987** [comment]
i tried below as well 
``` yaml
 tasks:
     - file:
         path: /tmp/apps/abc
         state: directory
         mode: 0755
         recurse: yes
     - file:
         path: /tmp/apps/abc
         state: file
         mode: 0644
```
but this fails as /tmp/apps/abc is a directory , so all files and directories remain at 755
