### ISSUE TITLE
Ansible reads and loads commented out variables in vault

### ISSUE THREAD

**Issue by SandrewCheru** [ansible/ansible#24376]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible Vault
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May  2 2017, 14:13:20) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Commented out variables are read and loaded when used in a vault.
##### STEPS TO REPRODUCE

- Create the folders group_vars/all
- Create the file group_vars/all/vars and group_vars/all/vault
-  group_vars/all/vars contains 
```
username: "{{ vault_username }}"
password: group_specific_password
```
- group_vars/all/vault (which is an encrypted file, created with ansible-vault) contains:
`vault_username: group_specific_username`
- Create the folders host_vars/destruction (destruction is the remote host)
- Create the files host_vars/destruction/vars and host_vars/destruction/vault
- host_vars/destruction/vars contains
```
# username: "{{ vault_username }}"
# password: host_specific_password
```
- host_vars/destruction/vault ((which is an encrypted file, created with ansible-vault) contains:
`vault_username: host_specific_username`

- Create the folders roles/echoing/tasks/
- Create the file roles/echoing/tasks/main.yml containing
```
- name: Echoing username
  debug: msg="{{ username }}"

- name: Echoing password
  debug: msg="{{ password }}"
```
- Create an inventory file pointing to the remote host (destruction in this example)

```yaml
---

- hosts: destruction

  roles:
      - echoing
```

##### EXPECTED RESULTS

```
TASK [echoing : Echoing username] *********************************************************************************************************************************************************************************************************************************************
ok: [destruction] => {
    "changed": false,
    "msg": "group_specific_value"
}

TASK [echoing : Echoing password] *********************************************************************************************************************************************************************************************************************************************
ok: [destruction] => {
    "changed": false,
    "msg": "host_specific_password"
}

```
##### ACTUAL RESULTS

```
TASK [echoing : Echoing username] *********************************************************************************************************************************************************************************************************************************************
ok: [destruction] => {
    "changed": false,
    "msg": "host_specific_value"
}

TASK [echoing : Echoing password] *********************************************************************************************************************************************************************************************************************************************
ok: [destruction] => {
    "changed": false,
    "msg": "host_specific_password"
}
```

```

```

**Comment by alikins** [comment]
If I understand correctly, for host 'destruction', it will get vars from:


group_vars/all/vars
group_vars/all/vault
host_vars/destruction/vars
host_vars/destruction/vault 

The vars after each:


group_vars/all/vars
``` yaml
 # since 'destruction' is in the 'all' group
 username: "{{ vault_username }}"
 password: group_specific_password
```

group_vars/all/vault:
``` yaml
username: "{{ vault_username }}"
password: group_specific_password
vault_username: group_specific_username
```

(nothing changes here, since its all commented out)
host_vars/destruction/vars:
``` yaml
username: "{{ vault_username }}"
password: group_specific_password
vault_username: group_specific_username
```

host_vars/destruction/vault:
``` yaml
username: "{{ vault_username }}"
password: group_specific_password
vault_username: host_specific_username
```

host_vars override group_vars (http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable) so 'username' ends as 'host_specific_username'

'username: "{{ vault_username }}"' is defined in group_vars/all/vars so it exist even without host/destruction/vars content.

As far as I can tell, that is the correct behavior.
