### ISSUE TITLE
In junos_config  if diff is empty changed is set to True

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#24375]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_config

##### ANSIBLE VERSION

```
2.4
```

##### STEPS TO REPRODUCE

Run below playbook twice. For second run `changed` should be `False`

```yaml
- name: configure multiple commands
  junos_config:
    lines:
      - 'set system host-name {{ inventory_hostname_short }}'
      - 'set interfaces lo0 unit 0 family inet address 1.1.1.1/32'
    provider: "{{ netconf }}"
  register: result
```

##### ACTUAL RESULTS

For second run changed is set to`true`

```
changed: [vsrx01] => {
    "changed": true,
    "diff": {
        "prepared": ""
    },
    "invocation": {
        "module_args": {
            "backup": false,
            "comment": "configured by junos_config",
            "confirm": 0,
            "host": null,
            "lines": [
                "set system host-name vsrx01",
                "set interfaces lo0 unit 0 family inet address 1.1.1.1/32"
            ],
            "password": null,
            "port": null,
            "provider": {
                "host": "vsrx01",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "netconf",
                "username": "ansible"
            },
            "replace": null,
            "rollback": null,
            "src": null,
            "src_format": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": null,
            "update": "merge",
            "username": null,
            "zeroize": false
        }
    }
}
```
