### ISSUE TITLE
git status shows modified files after pulling with ansible git module

### ISSUE THREAD

**Issue by devopsberlin** [ansible/ansible#24401]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible git module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
```

##### SUMMARY
git status shows modified files after pulling to get only the new updates or checkout branch with ansible git module.

    - name: retrieve new revisions from the origin repository for staging
      git:
        repo: git@github.com:repo/repo.git
        dest: "{{staging_path}}"
        version: "{{ version }}" # without the version in a case of pull only
        accept_hostkey: yes
        key_file: /home/my_local_user/.ssh/id_rsa
        force: yes
        update: yes
      become_user: my_local_user

For example:

    git status
    modified:   vendor/rmccue/requests/tests/Proxy/HTTP.php
    modified:   vendor/rmccue/requests/tests/Requests.php

Nothing wrong with the remote/local repo on the remote machine, if I am doing `git reset --hard` and `git pull` it fix the issue.

    $ git reset --hard
    HEAD is now at 5acdb55 Merge pull request #333 from
    $ git checkout master
    Switched to branch 'master'
    Your branch is up-to-date with 'origin/master'.
    $ git pull
    Already up-to-date.
    $ git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    nothing to commit, working directory clean

Any idea why it's happening ?

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @robinro
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by robinro** [comment]
@devopsberlin Can you give a minimal working example playbook to reproduce this issue? I.e. a repo and a version jump that leads to this.

Do you have local modifications in the repo before the pull?

**Comment by devopsberlin** [comment]
@robinro thanks for your quick response, I have only one local modification on the remote repo, I copy index_tmp.php to index.php on the root of the repo, but git status is not complain about this file.

If I want to pull only I am using this command:

`ansible-playbook -i environments/staging/staging playbooks/deploy.yml --extra-vars "target=web pull_only=true" --flush-cache`
```
- name: retrieve new revisions from the origin repository for staging
  git:
    repo: git@github.com:repo/repo.git
    dest: "{{staging_path}}"
    accept_hostkey: yes
    key_file: /home/user/.ssh/id_rsa
    force: yes
    update: yes
  become_user: user
  register: gitresult
  when: check_if_repo_exist.stat.exists
```

When I want to check out:
```
ansible-playbook -i environments/staging/staging playbooks/deploy.yml --extra-vars "target=web version=someversion" --flush-cache

- name: check what branch the checkout is on
  shell: cd "{{staging_path}}" ; git rev-parse --abbrev-ref HEAD
  register: branch
  when: check_if_repo_exist.stat.exists

- name: clone git repo to staging
  git:
    repo: git@github.com:repo/repo.git
    dest: "{{staging_path}}"
    version: "{{ version }}"
    accept_hostkey: yes
    key_file: /home/user/.ssh/id_rsa
    force: yes
    update: yes
  become_user: user
  register: git_commit_staging
  when: (version != false) and (pull_only == false)
```

Is there any more details do you like me to provide?
Thank you

**Comment by devopsberlin** [comment]
@robinro one more thing that I forgot to mention, each time before the pull/checkout I am specifying permissions to the remote repo folder, maybe is it related to the issue?

```
# make sure user is the owner of staging_path - drwxrwxr-x
- name: fix staging_path permissions
  file: dest={{staging_path}} owner=user group=user mode=0775 recurse=yes
  when: staging_folder.stat.exists

```

**Comment by robinro** [comment]
Can you provide a playbook that I can run that reproduces the issue?

**Comment by devopsberlin** [comment]
@robinro yes of course, but first let me try to change the task permissions, maybe this is the issue, I will keep you update. thanks!

**Comment by devopsberlin** [comment]
@robinro please one question, what is the right wait to pull only the latest updates from git ?
should I need first to find the current branch/tag on the remote machine and the use the git module ?

```
- name: check which branch
  shell: cd "{{production_path}}"; git symbolic-ref -q --short HEAD || git describe --tags --exact-match
  register: branch

 git:
    repo: git@github.com:repo/repo.git
    dest: "{{production_path}}"
    version: "{{ branch }}"
    accept_hostkey: yes
    key_file: /home/user/.ssh/id_rsa
    force: no
    update: yes
```

Or I can only pull without specify the version ?

```
 git:
    repo: git@github.com:repo/repo.git
    dest: "{{production_path}}"
    accept_hostkey: yes
    key_file: /home/user/.ssh/id_rsa
    force: no
    update: yes
```

Thanks in advance.

**Comment by robinro** [comment]
@devopsberlin I'm not sure I understand the question. The default is `version: HEAD`, which gets the remote HEAD. See the version description in the docs.

**Comment by devopsberlin** [comment]
@robinro, sorry for the misunderstanding, let me explain my question, let say the repository on the remote server is on tag 12.8.54, if I pull changes without specify the version it change automatically the branch on the remote server to master, is it because the the HEAD origin/master and ansible git module use `version: HEAD` as default  ?

```
  /var/app ((HEAD detached at 12.8.54)) $ git branch
* (HEAD detached at 12.8.54)
  from_12.8.17
  master
```
`/var/app ((HEAD detached at 12.8.54)) $ git log --pretty=oneline --decorate`
`11a921e8ba9b281e6c625365119b5b2f1736bc6a (HEAD, tag: 12.8.54, origin/master, origin/HEAD) Merge pull request #339 from repo/example`

So Ansible not really have the 'git pull' feature, and I need to find the current branch/tag on the remote server if I want only to pull changes without changing branch (something like the below example) ?

```
  - name: check which branch/tag on the remote machine
    shell: cd "{{staging_path}}" ; git symbolic-ref -q --short HEAD || git describe --tags --exact-match
    register: branch

  - name: clone git repo to staging
    git:
      repo: git@github.com:repo/repo.git
      dest: "{{staging_path}}"
      version: "{{branch.stdout}}"
      accept_hostkey: yes
      key_file: /home/user/.ssh/id_rsa
      force: yes
      update: yes
    become_user: user
```

Beside that, the issue with "git status shows modified files after pulling with ansible git module" has been resolved after I stopped to change permissions on the repo folder, so I guess it was permission issue with the files, so sorry for wasting your time.

Thanks
