### ISSUE TITLE
file modules backups created while using become to root are owned by root

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/ansible#24408]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Template module

##### ANSIBLE VERSION

```
2.3
devel
```

##### OS / ENVIRONMENT
RHEL 7.3

##### SUMMARY

Found the similar issue here but its closed https://github.com/ansible/ansible/issues/11886
I have a task that runs a template with become=true and backup=Yes. The owner and group is set to an account niks with a lower privilege than root. The templated file that is uploaded has the owner set to niks. But the backups are owned by root.

##### STEPS TO REPRODUCE
Attaching my playbook to reproduce with the case

```yaml
---
 - name: test template
   hosts: localhost
   gather_facts: false
   become: true
   vars:
      foo: "bar"
   tasks:
     - name: template
       template:
          src=/home/niks/ansible_test/templates/test.j2
          dest=/tmp/test1.conf
          owner=niks
          group=niks
          backup=yes
```

##### EXPECTED RESULTS

The back up file should have permission as niks niks
##### ACTUAL RESULTS

The back up file has permissions as root root
```
-rw-r--r--. 1 root root 18 May  8 18:27 /tmp/test1.conf.21163.2017-05-09@19:27:49~
-rw-r--r--. 1 niks niks 19 May  9 19:27 /tmp/test1.conf
```
