### ISSUE TITLE
Receive "msg": "unable to retrieve current config", "stderr": "show running-config\r\n when running playbook with ios_config module

### ISSUE THREAD

**Issue by joemsanchez** [ansible/ansible#24411]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION

```
ansible 2.3.0.0

```

##### OS / ENVIRONMENT

Ubuntu 16.04.2 LTS

##### SUMMARY

Still new to Ansible, and trying to build Playbook based off some the information out there.   I saw a similar issue here, but I not sure what the resolution is.  I never have issues with nexus modules, but when I run a playbook with ios_config module I get the error below
```
fatal: [SW01]: FAILED! => {"changed": false, "failed": true, "msg": "unable to retrieve current config", "stderr": "show running-config\r\n             ^\r\n% Invalid input detected at '^' marker.\r\n\r\nSwitch>", "stderr_lines": ["show running-config", "             ^", "% Invalid input detected at '^' marker.", "", "Switch>"]}

```
##### STEPS TO REPRODUCE

```yaml
---
- hosts: SW01
  gather_facts: no
  connection: local

  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname  }}"
        username: "{{ mgmt_username  }}"
        password: "{{ mgmt_password  }}"

  - name: LOAD NEW ACL INTO DEVICE
    ios_config:
      provider: "{{ provider  }}"
      lines:
        - 10 permit ip host 1.1.1.1 any log
        - 20 permit ip host 2.2.2.2 any log
        - 30 permit ip host 3.3.3.3 any log
      parents: ip access-list extended test
      before: no ip access-list extended test


```

##### ACTUAL RESULTS

```
TASK [LOAD NEW ACL INTO DEVICE] *************************************************************************************************************************************************************************************************************
task path: /etc/ansible/ios.yml:22
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/ios/ios_config.py
<SW01> ESTABLISH LOCAL CONNECTION FOR USER: root
<SW01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<SW01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1494344222.49-5366168771680 `" && echo ansible-tmp-1494344222.49-5366168771680="` echo /root/.ansible/tmp/ansible-tmp-1494344222.49-5366168771680 `" ) && sleep 0'
<SW01> PUT /tmp/tmpjLFP9F TO /root/.ansible/tmp/ansible-tmp-1494344222.49-5366168771680/ios_config.py
<SW01> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1494344222.49-5366168771680/ /root/.ansible/tmp/ansible-tmp-1494344222.49-5366168771680/ios_config.py && sleep 0'
<SW01> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1494344222.49-5366168771680/ios_config.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1494344222.49-5366168771680/" > /dev/null 2>&1 && sleep 0'
fatal: [SW01]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": [
                "no ip access-list extended test"
            ],
            "config": null,
            "defaults": false,
            "force": false,
            "host": null,
            "lines": [
                "10 permit ip host 1.1.1.1 any log",
                "20 permit ip host 2.2.2.2 any log",
                "30 permit ip host 3.3.3.3 any log"
            ],
            "match": "line",
            "multiline_delimiter": "@",
            "parents": [
                "ip access-list extended test"
            ],
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": null,
                "host": "SW01",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "msg": "unable to retrieve current config",
    "stderr": "show running-config\r\n             ^\r\n% Invalid input detected at '^' marker.\r\n\r\nSwitch>",
    "stderr_lines": [
        "show running-config",
        "             ^",
        "% Invalid input detected at '^' marker.",
        "",
        "Switch>"
    ]
}

```
