### ISSUE TITLE
Extend the ETCD Lookup to get all variables from a folder

### ISSUE THREAD

**Issue by jparrill** [ansible/ansible#24414]
##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
Plugin ETCD Lookup

##### ANSIBLE VERSION
All

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
OS: Linux

##### SUMMARY
The feature basically is calling to get a ETCD key/value, when you make an API call to request a folder, the response must be all the keys-values inside of it.

##### STEPS TO REPRODUCE

```yaml
- name: 'ETCD Variables'
  hosts: 127.0.0.1
  connection: local
  remote_user: root
  vars:
    - REGION: 'SAMPLE'
    - RELEASE: 'liberty'
  pre_tasks:
    ## This step will fullfil the vars to be used on Ansible Roles/Playbooks
    - name: 'Getting Variables from ETCD Folder'
      set_fact:
        VAR_MAP: "{{ lookup('etcd2', '/{{ REGION }}/{{ RELEASE }}') }}"

    - debug:
        var: VAR_MAP
```

Output:
```
PLAY [ETCD Variables] *********************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************
ok: [localhost]

TASK [Getting Variables from ETCD Folder] ****************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *********************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": {
        ...
        ...
        ...
        "CEILOMETER_API_PORT": "8777",
        "CEILOMETER_LOG": "LOG_LOCAL6",
        "CEILOMETER_TTL": "7776000",
        "CEILOMETER_USER": "ceilometer",
        "CEPH_VERSION": "0.80.8",
        "CINDER_BCK_DRIVER": "cinder.backup.drivers.ceph",
        "CINDER_CEPH_BCK_USER": "backup",
        "CINDER_CEPH_CHUNK": "134217728",
        "CINDER_DB": "cinder",
        "CINDER_DEF_VOL": "standard",
        "CINDER_ENABLE_BACKEND": "standard,ssd",
        ...
        ...
      }
}

TASK [00_entry_validation : Creating controller files] ***************************************************************************************************************************************
changed: [localhost] => (item={'key': u'ceilometer', 'value': {u'origin': u'/etc/ceilometer/ceilometer.conf', u'tmp': u'/home/test/ceilometer.conf', u'template': u'ceilometer-controller.conf.j2'}})

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0   
```

##### EXPECTED RESULTS
Inside of fact {{ VAR_MAP }} you will find a dictionary with all variable mapping from an ETCD folder 

##### ACTUAL RESULTS
Actually  you get a empty variable
