### ISSUE TITLE
mysql_db - add `check_implicit_admin` option support

### ISSUE THREAD

**Issue by MarcinOrlowski** [ansible/ansible#24418]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

mysql_db

##### ANSIBLE VERSION

```

```

##### SUMMARY

`mysql_db` module does not support `check_implicit_admin` option (which is part of `mysql_user` module). This is inconsistent and unnecesairly enforces order of operations in DB setup playbooks/roles and disallows proper handling of provisioning using DB's `root` account without password set.

##### STEPS TO REPRODUCE

```yaml
- name: create database
  mysql_db:
    login_user: "root"
    login_password: "foobar"
    check_implicit_admin: yes
    name: "db"
    state: present
```

##### EXPECTED RESULTS

Support for `check_implicit_admin` should act the same it does in `mysql_user` - check if mysql allows login as root/nopassword before trying supplied credentials. That would allow provisioning using default passwordless DB `root` account and also would allow playing the same role over provisioned DB with password set. For now I have to set the root password prior using `mysql_db` on the machine I change root password during provisioning but the readability of playbook suffers.

##### ACTUAL RESULTS

If tails as `check_implicit_admin` is not supported.
