### ISSUE TITLE
Looping over variables containing raw jinja2 values fails with undefined variable error.

### ISSUE THREAD

**Issue by amaczuga** [ansible/ansible#24417]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Looping over variables containing raw jinja2 values

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
also
```
ansible 2.4.0
  config file =
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/ubuntu/venv/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

No additional configuration or modules.

##### OS / ENVIRONMENT

```
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
```
Ansible installed using pip - tried latest stable from pypi, also github repo master branch

##### SUMMARY

Looping over list data structure using `with_items` breaks, when one of variable values is a Jinja2 expression containing an unset variable, even though `{% raw %}` clause has been used.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  vars:
#  - bugme: "not"
  - paramlist:
    -
      name: "firstparam"
      inifile: "rawj2.ini"
      params:
        j2value: "{% raw %}{{ bugme }}{% endraw %}"
  tasks:
  - name: trigger raw j2 bug
    template:
      src: "{{ item.inifile }}.j2"
      dest: "{{ playbook_dir }}/{{ item.inifile }}"
    with_items: "{{ paramlist }}"
```

rawj2.ini.j2:
```yaml
[config]
{% for param,value in (paramlist | selectattr("name", "equalto", "firstparam") | first).params.items() %}
{{ param }} = {{ value }}
{% endfor %}
```

##### EXPECTED RESULTS

The expected output file rawj2.ini:
```ini
[config]
j2value = {{ bugme }}
```

##### ACTUAL RESULTS

```
No config file found; using defaults
Set default localhost to localhost
Loading callback plugin default of type stdout, v2.0 from /home/ubuntu/venv/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: rawbug.yml *******************************************************************************************************************************************************
1 plays in rawbug.yml

PLAY [localhost] ***********************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************
Using module file /home/ubuntu/venv/local/lib/python2.7/site-packages/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1494360864.53-211319025889132 `" && echo ansible-tmp-1494360864.53-211319025889132="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1494360864.53-211319025889132 `" ) && sleep 0'
<localhost> PUT /tmp/tmpMJ163q TO /home/ubuntu/.ansible/tmp/ansible-tmp-1494360864.53-211319025889132/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1494360864.53-211319025889132/ /home/ubuntu/.ansible/tmp/ansible-tmp-1494360864.53-211319025889132/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1494360864.53-211319025889132/setup.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1494360864.53-211319025889132/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [trigger raw j2 bug] **************************************************************************************************************************************************
task path: /home/ubuntu/bug/rawbug.yml:13
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: {u'inifile': u'rawj2.ini', u'params': {u'j2value': u'{{ bugme }}'}, u'name': u'firstparam'}: 'bugme' is undefined\n\nThe error appears to have been in '/home/ubuntu/bug/rawbug.yml': line 13, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n  - name: trigger raw j2 bug\n    ^ here\n"
}
        to retry, use: --limit @/home/ubuntu/bug/rawbug.retry

PLAY RECAP *****************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by bcoca** [comment]
raw cannot protect it as it will recursively template (1st pass removes raw), use `!unsafe`

**Comment by amaczuga** [comment]
@bcoca `!unsafe` will tamper jinja variable start strings, producing
```ini
[config]
j2value = {# bugme #}
```
I would need the result to be exactly as in the description

**Comment by bcoca** [comment]
unsafe should not template at all....

**Comment by sivel** [comment]
I have confirmed that using `!unsafe` works as expected:

```
---
- hosts: localhost
  vars:
#  - bugme: "not"
  - paramlist:
    -
      name: "firstparam"
      inifile: "rawj2.ini"
      params:
        j2value: !unsafe "{{ bugme }}"
  tasks:
  - name: trigger raw j2 bug
    template:
      src: "{{ item.inifile }}.j2"
      dest: "{{ playbook_dir }}/{{ item.inifile }}"
    with_items: "{{ paramlist }}"
```

Produces:
```
[config]
j2value = {{ bugme }}
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
