### ISSUE TITLE
user module on HP-UX cannot append secondary-groups

### ISSUE THREAD

**Issue by taksekine** [ansible/ansible#24429]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

user module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

- Runnning Ansible on CentOS 7.3
- Managing to HP-UX 11i v3

##### SUMMARY

On HP-UX, user.py cannot **append** secondary groups.
Because **usermod.sam** command  on HP-UX (not only 11i v3, but also 11i v2)
have neither -A nor -a option.

So, function **modify_user** ("if self.groups is not None:" caluse) in HPUX subclass
 implements like FreeBsdUser or SunOS subclass , I think.

##### STEPS TO REPRODUCE

Run playbook like playbooks as follow,
- assign groupA to testuser is OK   (1st time use create_user function)
- assign groupB to testuser is FAIL (2nd time use modify_user function)
 

```yaml
- hosts: hpux
  become: yes
  vars:
    mygroup: [ 'groupA', 'groupB' ]
  tasks:
    - name: make group
      group:
        state: present
        name: "{{ item }}"
      with_items: [ 'groupA', 'groupB' ]
    - name: make user
      user:
        state: present
        name: testuser
        append: yes
        groups: "{{ item }}"
      with_items: [ 'groupA', 'groupB' ]
```

##### EXPECTED RESULTS

Success to **append** secondary-groups multi-times.

##### ACTUAL RESULTS

```
$ ansible-playbook -K -i hosts test.yml
SUDO password:

PLAY [hpux] ********************************************************************


TASK [make group] **************************************************************

changed: [hpux.foobar.com] => (item=groupA)
changed: [hpux.foobar.com] => (item=groupB)

TASK [make user] ***************************************************************

changed: [hpux.foobar.com] => (item=groupA)
failed: [hpux.foobar.com] (item=groupB) => {"failed": true, "item": "groupB", "msg": "Unrecognized Option 'A'\nUsage: usermod.sam [-F] [-p <encrypted-password>] [-u <uid> [-o]] [-g <group>] [-G <group>[,<group...>]] [-d <dir> [-m] [-i]] [-s <shell>] [-c <comment>] [-f <inactive>] [-e <expire>] [-l <new
logname>] [-P -S <alternate password file>] <login>\n", "name": "testuser", "rc": 2}

PLAY RECAP *********************************************************************

hpux.foobar.com  : ok=1    changed=1    unreachable=0    failed=1

$
```
