### ISSUE TITLE
docker_container: arguments pass to command are split on comma incorrectly

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#24430]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
RHEL7.3

##### SUMMARY
When I pass an argument to the "command" option that contains commas (that should be preserved as a single string), the argument is split on the command and passed as separate arguments.

##### STEPS TO REPRODUCE

```yaml
- name: Run etcd
  vars: 
    myip: "{{ inventory_hostname }}"
  docker_container:
    name: etcd
    image: quay.io/coreos/etcd
    state: started
    volumes:
      - /data
    published_ports:
      - 4001
      - 2380
      - 2379
    command: >
        /usr/local/bin/etcd 
        -name etcd{{ node }}
        -advertise-client-urls http://{{ myip }}:2379,http://{{ myip }}:4001
        -listen-client-urls http://0.0.0.0:2379,http://0.0.0.0:4001
        -initial-advertise-peer-urls http://{{ myip }}:2380
        -listen-peer-urls http://0.0.0.0:2380
        -initial-cluster-token etcd-cluster-1
        -initial-cluster etcd0=http://{{ groups['kube-nodes'][0] }}:2380,etcd1=http://{{ groups['kube-nodes'][1] }}:2380,etcd2=http://{{ groups['kube-nodes'][2] }}:2380
        -initial-cluster-state new
```

##### EXPECTED RESULTS
In the arguments passed to etcd, I would expect the value of the argument -initial-cluster to be the string as defined, with commas.

##### ACTUAL RESULTS
The value of the "-initial-cluster" argument was split into separate arguments on comma and passed separately to the command. This can be easily seen in the debug output:

"Args": ["-name", "etcd3", "-advertise-client-urls", "http://10.1.1.187:2379", "http://10.1.1.187:4001", "-listen-client-urls", "http://0.0.0.0:2379", "http://0.0.0.0:4001", "-initial-advertise-peer-urls", "http://10.1.1.187:2380", "-listen-peer-urls", "http://0.0.0.0:2380", "-initial-cluster-token", "etcd-cluster-1", **"-initial-cluster", "etcd0=http://10.1.1.109:2380", "etcd1=http://10.1.1.110:2380", "etcd2=http://10.1.1.187:2380"**, "-initial-cluster-state", "new"]

Note that the values following "-initial-cluster" are separate and surrounded by quotes, instead of the original string.
