### ISSUE TITLE
template error while templating string: no filter named 'map'

### ISSUE THREAD

**Issue by nb00471049** [ansible/ansible#24439]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

Copy module

##### ANSIBLE VERSION

```
ansible --version - ansible 2.2.0.0
```

##### SUMMARY

```
---
- hosts: localhost
  tasks:
   - name: "check the connectivity with username for all the LLC servers from hosts.new file"
     shell: ssh dp794d@{{ item }} "date"
     register: result
     with_lines: cat "/home/capio/ansible/pmossWipm/day2/logs/ipAddress.txt"
   - copy:
       content: '{{ result.results | map(attribute="stdout") | list | join("\n") }}'
       dest: /home/capio/ansible/pmossWipm/day2/logs/out.txt
```
##### ACTUAL RESULTS

```
TASK [copy] ********************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "template error while templating string: no filter named 'map'. String: {{ result.results | map(attribute=\"stdout\") | list | join(\"\\\\n\") }}"}
        to retry, use: --limit @/home/capio/ansible/pmossWipm/day2/playbooks/day2_activity.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1
```
