### ISSUE TITLE
[vmware_guest]  creating VM from template causes error "A specified parameter was not correct: spec.location.host" when disk option is added

### ISSUE THREAD

**Issue by sayantandas** [ansible/ansible#24435]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
 ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

Standard ansible config, no changes
##### OS / ENVIRONMENT

 cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

##### SUMMARY

Following the example given in  https://docs.ansible.com/ansible/vmware_guest_module.html, `Create a VM from a template`,  I tried to add an extra disk while creating a VM from template. It throws an error.

##### STEPS TO REPRODUCE

I tried to use a template to create a VM . The template is a RHEL 7, 64bit one, with 40GB HDD attached and partitioned via LVM.  The code  used is given below . 

```
  - name: deploy virtual machine from template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      name: "{{ vm_name }}"
      validate_certs: "false"
      cluster: "{{ vcenter_cluster }}"
      datacenter: "{{ vcenter_datacenter }}"
      folder: "/dev/VMs"
      state: poweredon
      #guest_id: rhel7Guest
      disk:
        - size_gb: 40
          type: thin
         datastore: "{{ datastore }}"
         # autoselect_datastore: True
        - size_gb: 150
          type: thin
          datastore: "{{ datastore }}"
          #autoselect_datastore: True
      hardware:
        memory_mb: "4096"
        num_cpus: "2"
        scsi: paravirtual
      networks:
        - name: "{{ vm-vlan }}"
          ip: 192.168.051
          netmask: 255.255.255.0          
      template: "{{ vm_template }}"
    delegate_to: "localhost"
    register: "deploy"


```

##### EXPECTED RESULTS

Expected to create a VM with 2 HDDs,  40GB and  150GB HDDs
##### ACTUAL RESULTS

Fails. with error

```
fatal: [localhost -> localhost]: FAILED! => {"changed": true, "failed": true, "msg": "A specified parameter was not correct: spec.location.host"}
```

If I omit the disk option and its variables, the VM is created with the default 40GB HDD and in the same datastore where the template is stored.
