### ISSUE TITLE
iosxr_facts module cant decode special unicode symbols

### ISSUE THREAD

**Issue by chrmcd** [ansible/ansible#24447]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

iosxr_facts
##### ANSIBLE VERSION

```
ansible 2.3.1.0 (stable-2.3 5f0be9dcd0) last updated 2017/05/10 14:12:19 (GMT +000)
  config file = /root/bachelor/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When retrieving config subset the module failes due to not being able to decode special characters like "æ", "ø" and "å".
##### STEPS TO REPRODUCE

```yaml
- name: Get iosXR facts
  hosts: myrouter
  connection: local
  tasks:

    - name: gather facts
      iosxr_facts:
        provider: "{{ ansible_provider }}"
        gather_subset: "config"

```

##### EXPECTED RESULTS

Expected it to retrieve the config
##### ACTUAL RESULTS

```
fatal: [myrouter]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "gather_subset": [
                "optics"
            ], 
            "host": null, 
            "password": null, 
            "port": null, 
            "provider": {
                "host": "127.0.0.1", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 22, 
                "ssh_keyfile": null, 
                "timeout": 20, 
                "username": "ansible"
            }, 
            "ssh_keyfile": null, 
            "timeout": 20, 
            "username": null
        }
    }, 
    "msg": "'ascii' codec can't decode byte 0x93 in position 15: ordinal not in range(128)", 
    "rc": 1
}
```
