### ISSUE TITLE
unsafe_writes doesn't seem to work

### ISSUE THREAD

**Issue by smaftoul** [ansible/ansible#24449]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

template

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Oct 11 2016, 05:24:00) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### CONFIGURATION

ansible.cfg:
```[defaults]
roles_path = roles
transport = ssh

[ssh_connection]
ssh_args = -o ForwardAgent=yes
```

##### OS / ENVIRONMENT

Ansible is running on osx, the target is ubuntu linux 16.04.1.
The target filesystem is ext4 pretty standard

##### SUMMARY

I'm using unsafe_writes to render a template that is bind-mounted in a docker container.
The container doesn't reflect the changes, and the inode of the file changes.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  tasks:
    - name: "inode"
      command: ls -i /etc/test
      register: lsi1
      changed_when: False
    - debug: var=lsi1.stdout_lines

    - name: "render a test template"
      template:
        src: templates/test.j2
        dest: /etc/test
        unsafe_writes: True

    - name: "2nd inode"
      command: ls -i /etc/test
      register: lsi2
      changed_when: False
    - debug: var=lsi2.stdout_lines
```

the content of `templates/test.j2`:
```
{{ ansible_date_time.epoch }}
```

##### EXPECTED RESULTS

I expect the inode to not change, when I use cat or (properly configured) vi, the inode doesn't change and I see do see the change within the docker container.

##### ACTUAL RESULTS

The inode of the file is changing.
Using `copy` seems to have the same behaviour.

```
PLAY [all] *************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
ok: [host]

TASK [inode] ***********************************************************************************************************************************************************************************************
ok: [host]

TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [host] => {
    "changed": false, 
    "lsi1.stdout_lines": [
        "18219775 /etc/test"
    ]
}

TASK [render a test template] ******************************************************************************************************************************************************************************
changed: [host]

TASK [2nd inode] *******************************************************************************************************************************************************************************************
ok: [host]

TASK [debug] ***********************************************************************************************************************************************************************************************
ok: [host] => {
    "changed": false, 
    "lsi2.stdout_lines": [
        "18219944 /etc/test"
    ]
}

PLAY RECAP *************************************************************************************************************************************************************************************************
host                        : ok=6    changed=1    unreachable=0    failed=0   
```
