### ISSUE TITLE
Unable to json_query when attribute is a NUMBER

### ISSUE THREAD

**Issue by abhigrover** [ansible/ansible#24445]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

json_query filter

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar 13 2017, 20:56:15) [GCC 5.4.0]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Windows

##### SUMMARY

I have a dict that contains an attribute that is a "NUMBER" rather than a "STRING". Unable to make json_query filter work to query against this attribute

##### STEPS TO REPRODUCE

```yaml
---
- name: Find BigIP Pools in STAGE by host and port
  hosts: sdc_bigip
  connection: local
  gather_facts: False
  vars:
          match_port: 40680
  tasks:
          - name: Read the configured pools in B12
            set_fact:
                    bigip_pool_file: "{{lookup('file','/tmp/bigip_pool') | from_json }}"
            tags: read_json

          - name: search for pools
            debug:
                    msg: "Pool name: {{item.key}}"
            with_dict: "{{ bigip_pool_file['ansible_facts']['pool'] }}"
            when:
                    (item.value |json_query("member[?port==match_port]"))
```

Sample Data:
            "Pool": {
                "member": [
                    {
                        "address": "/Common/laziodr.cit.nih.gov",
                        "port": 40680
                    },
                    {
                        "address": "/Common/levantedr.cit.nih.gov",
                        "port": 40680
                    }
                ]
}
##### EXPECTED RESULTS

item.key equal to "Pool"
##### ACTUAL RESULTS

Blank search result

```

```
