### ISSUE TITLE
Nested loop with lists not working as expected

### ISSUE THREAD

**Issue by peter216** [ansible/ansible#24458]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
with_nested

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### SUMMARY
Using with_nested with lists embedded in the items, I am not able to check for membership of a constant in a list.  Instead of iterating the lists themselves, ansible appears to iterate over _members_ of the list.

##### STEPS TO REPRODUCE

```
---                                                                                              
                                                                                                 
- name: Test nested loop                                                                         
  hosts: localhost                                                                               
  gather_facts: no                                                                               
  connection: local                                                                              
  tasks:                                                                                         
    - name: Set facts                                                                            
      set_fact:                                                                                  
        foo: ["a", "b", "c"]                                                                     
        bar: ["a", "b", "d"]                                                                     
    - name: Check constants for membership in lists                                              
      assert:                                                                                    
        that:                                                                                    
          - "{{ item[0] }} in {{ item[1] }}"                                                     
      with_nested:                                                                               
        - ["a", "b"]                                                                             
        - [ "{{ foo }}", "{{ bar }}"]      

```

##### EXPECTED RESULTS

assert should pass

##### ACTUAL RESULTS

```
(ansible) {17-05-10 14:19}ip-10-203-227-164:~/sandbox ec2-user% ansible-playbook -vvvv test_nested.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test_nested.yml *************************************************************************************************************************************************************************
1 plays in test_nested.yml

PLAY [Test nested loop] ***************************************************************************************************************************************************************************
META: ran handlers

TASK [Set facts] **********************************************************************************************************************************************************************************
task path: /home/ec2-user/sandbox/test_nested.yml:8
ok: [localhost] => {
    "ansible_facts": {
        "bar": [
            "a", 
            "b", 
            "d"
        ], 
        "foo": [
            "a", 
            "b", 
            "c"
        ]
    }, 
    "changed": false
}

TASK [Check constants for membership in lists] ****************************************************************************************************************************************************
task path: /home/ec2-user/sandbox/test_nested.yml:12
fatal: [localhost]: FAILED! => {
    "failed": true, 
    "msg": "The conditional check 'a in a' failed. The error was: error while evaluating conditional (a in a): Unable to look up a name or access an attribute in template string ({% if a in a %} True {% else %} False {% endif %}).\nMake sure your variable name does not contain invalid characters like '-': argument of type 'StrictUndefined' is not iterable"
}
        to retry, use: --limit @/home/ec2-user/sandbox/test_nested.retry

PLAY RECAP ****************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

```
