### ISSUE TITLE
Multiple includes involving with_dict doesn't work

### ISSUE THREAD

**Issue by abhigrover** [ansible/ansible#24481]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar 13 2017, 20:56:15) [GCC 5.4.0]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Windows

##### SUMMARY

I have a playbook (outer playbook) that is looking for items within a dictionary, and based on the items that qualifies the when condition, includes another playbook (inner playbook) that executes a set of tasks against those identified items. The inner playbook then includes another playbook in one of the tasks (3rd level include) that is searching another dict for items, however, the result of this search is empty, even though it returns results if invoked standalone.
##### STEPS TO REPRODUCE

```yaml
outer_playbook.yml
          - name: Generate PARAM file for matching Tomcat
            include: innerPlaybook.yml
                   _host={{ inventory_hostname }}
                   _tomcatID={{ outer_item.key }}
            with_dict: "{{local_facts['ansible_facts']['ansible_local']['tomcat']}}"
            when:
                    (outer_item.value | json_query("TomcatBuildID=='{{current_tomcat_version}}'")) and
                    (outer_item.value | json_query("app_info.AppName=='" ~ app_name ~ "'"))
            loop_control:
                    loop_var: outer_item

innerPlaybook.yml:

- include: task_disable_poolMem_by_hostandport.yml
  vars:
          bigip: "hostname"
          match_host: "{{_host}}"
          match_port: "{{_tomcatAttributes.TomcatBasePort}}"

task_disable_poolMem_by_hostandport.yml:
- name: search for pools
  set_fact:
      matched_pool: "{{search_pool_item.key}}"
  with_dict: "{{ bigip_pools['ansible_facts']['pool'] }}"
  when:
     (search_pool_item.value |json_query("member[?address=='" ~ match_host ~ "']")) and
     (search_pool_item.value |json_query("member[?port==`" ~ match_port ~ "`]"))
  loop_control:
     loop_var: search_pool_item
```

{
    "ansible_facts": {
        "pool": {
            "Testpool": {
                "member": [
                    {
                        "address": "host1",
                        "port": 23101
                    },
                    {
                        "address": "host2",
                        "port": 23101
                    }
                ]
}
}
}
##### EXPECTED RESULTS

In the task_disable_poolMem_by_hostandport.yml search, expect to get "TestPool"
##### ACTUAL RESULTS

Empty result

```

```
