### ISSUE TITLE
win_shortcut: Using a relative src= can cause error

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#24494]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_shortcut

##### ANSIBLE VERSION

v2.3+

##### SUMMARY

When using a task like this:
```yaml
- name: Create putty shortcut
  win_shortcut:
    src: 'putty.exe'
    dest: '%Public%\Desktop\PuTTY.lnk'
    icon: '%ProgramFiles%\PuTTY\putty.exe,0'
```

The following error occurs:
```
fatal: [windows-2012]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "
        Exception setting \"TargetPath\": \"The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))\"
        At line:89 char:9
        +         $ShortCut.TargetPath = $src
        +         ~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
        + FullyQualifiedErrorId : CatchFromBaseAdapterSetValueTI", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

This is fixed by using an absolute path:
```yaml
- name: Create putty shortcut
  win_shortcut:
    src: '%ProgramFiles%\PuTTY\putty.exe'
    dest: '%Public%\Desktop\PuTTY.lnk'
    icon: '%ProgramFiles%\PuTTY\putty.exe,0'
```

**Comment by jhawkesworth** [comment]
I think this might just be an understanding. I would expect a relative path to resolve to the user's home directory (or to be a bit more windowsy, I'd expect the relative path root to be the same as %HOMEPATH% for any given user).  So I think the src value needs to change.

to demonstrate this

`ansible windowshosts -m raw -a 'pwd'`

The below ought to fix it - can you test?

```
- name: Create putty shortcut
  win_shortcut:
    src: '%ProgramFiles%\PuTTY\putty.exe'
    dest: '%Public%\Desktop\PuTTY.lnk'
    icon: '%ProgramFiles%\PuTTY\putty.exe,0'
```

That said I think it should be documented that relative paths are relative to %HOMEPATH% though.

needs_info
