### ISSUE TITLE
[vmware_guest] After deploy VM network is disconnected and cannot connect.

### ISSUE THREAD

**Issue by lampogass** [ansible/ansible#24506]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### SUMMARY

After deploy new vm network is disconnected and cannot connect. Only way is to edit settings, remove network and give back again. I think problem is the presence of distributed switch.

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  tasks:
    - name: configure VM
      vmware_guest:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: false
        datacenter: "datacenter"
        folder: "{{ folder }}"
        name: "{{ name }}"
        state: poweredon
        guest_id: rhel7_64Guest
        disk:
        - size_gb: 50
          type: thin
          datastore: "{{ datastore }}"
        hardware:
          memory_mb: 512
          num_cpus: 1
          scsi: paravirtual
        networks:
        - name: "{{ network_name }}"
          ip: "{{ ip }}"
          netmask:  "{{ netmask }}"
          gateway: "{{ gateway }}"
          domain: "{{ domain }}"
          dns_server:
          - 10.x.xx.xx
          - 10.x.xx.xx
        template: "{{ template }}"
        wait_for_ip_address: no
```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @jctanner @nerzhul @dav1x
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lampogass** [comment]
![networkisuue](https://cloud.githubusercontent.com/assets/17727610/25950428/44736fa4-365b-11e7-84de-5109735fd133.PNG)

**Comment by lampogass** [comment]
![networkisuue](https://cloud.githubusercontent.com/assets/17727610/25950504/79de8516-365b-11e7-9d26-a0166511a342.PNG)

**Comment by hlavacek87** [comment]
Hello, I have exactly the same problem. If deployment is to vSwitch then it is OK, but to VDS there is the problem as described.
As far I understand there is no specific parameter for dvs(VDS) network option.

Thanks for help.

Martin

**Comment by lampogass** [comment]
I solved the issue, i think. This happen if you have same named network on different vswitch/dvs. Here in my situation customer migrate from standard virtual switch to distributed and do not change network name. This morning i've changed network and used on that is unique on dvs and all works fine.

**Comment by dav1x** [comment]
@hlavacek87 yes. The logic for the vDS checks for a port_group attribute. The network name should be unique. This shouldnt be an issue on a vDS since a port group is unique on a vDS. 

![screenshot 2017-05-16 11 32 42](https://cloud.githubusercontent.com/assets/7294149/26117224/6eec7b26-3a2b-11e7-90f7-762e6f078bc4.png)

**Comment by dagwieers** [comment]
Right, referencing non-unique objects is an issue. We could improve vmware_guest so that you can specify whether it should be looking for a vSwitch or a vDS though...

Or make this more clear from the documentation.

**Comment by luca-drf** [comment]
I have the same problem on the standard switch. ESXi 6.0.

The following task will create the nic but not connect it.

```
- name: create vm
  vmware_guest:
    hostname: '{{ vcenter_host }}'
    username: '{{ vcenter_user }}'
    password: '{{ vcenter_pass }}'
    name: '{{ vm_name }}'
    datacenter: '{{ datacenter }}'
    validate_certs: no
    state: poweredon
    guest_id: '{{ vm_guest_id }}'
    esxi_hostname: '{{ esxi_hostname }}'
    template: '{{ vm_template }}'
    wait_for_ip_address: yes
    disk:
      - size_gb: '{{ vm_disk.size_gb }}'
        type: '{{ vm_disk.type }}'
        datastore: '{{ vm_disk.datastore }}'
    networks:
      - name: 'VM Network'
        mac: '{{ vm_networks.mac }}'
  delegate_to: localhost
```

The weird thing is that it connects NICs of windows9_64guest type guests but not ubuntu64guest.

I'm puzzled.
