### ISSUE TITLE
pam module not updating files

### ISSUE THREAD

**Issue by theballdredge** [ansible/ansible#24516]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pamd module
##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

bog standard

##### OS / ENVIRONMENT

mac os 10.12.4

##### SUMMARY

ansible pam module does not update files correctly

##### STEPS TO REPRODUCE

using the play and example file below, no changes are executed

```
- name: insert pam_wheel requirement because it doesnt exist
  pamd:
    name: su
    type: auth
    control: required
    module_path: pam_wheel.so
    module_arguments: 'use_uid'
    state: before
    new_type: auth
    new_control: sufficient
    new_module_path: pam_rootok.so
	

#%PAM-1.0
# Uncomment the following line to implicitly trust users in the "wheel" group.
#auth           sufficient      pam_wheel.so trust use_uid
# Uncomment the following line to require a user to be in the "wheel" group.
auth            sufficient      pam_rootok.so
auth            substack        system-auth
auth            include postlogin

account         sufficient      pam_succeed_if.so uid = 0 use_uid quiet
```

##### EXPECTED RESULTS
given the above play and file, the line
``` auth required pam_wheel.so use_uid```
should be inserted after ```auth sufficient pam_rootok.so``` but it is not
##### ACTUAL RESULTS
no change occurs
```
PLAY [all] ***********************************************************************************************************************************************************

TASK [testplay : insert pam_wheel requirement because it doesnt exist] ******************************************************************************************
task path: /Users/excutinguser/repos/ansible-repo/roles/testplay/tasks/main.yml:867
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/system/pamd.py
<targethost> ESTABLISH SSH CONNECTION FOR USER: ansibleuser
<targethost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansibleuser -o ConnectTimeout=10 -o ControlPath=/Users/excutinguser/.ansible/cp/7963328e97 targethost '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<targethost> (0, '/home/ansibleuser\n', '')
<targethost> ESTABLISH SSH CONNECTION FOR USER: ansibleuser
<targethost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansibleuser -o ConnectTimeout=10 -o ControlPath=/Users/excutinguser/.ansible/cp/7963328e97 targethost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570 `" && echo ansible-tmp-1494281124.64-106881662588570="` echo /home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570 `" ) && sleep 0'"'"''
<targethost> (0, 'ansible-tmp-1494281124.64-106881662588570=/home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570\n', '')
<targethost> PUT /var/folders/d9/7d_sb4mj1bz1jywsy8rrpj61n4xnb5/T/tmpn5u5tS TO /home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570/pamd.py
<targethost> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansibleuser -o ConnectTimeout=10 -o ControlPath=/Users/excutinguser/.ansible/cp/7963328e97 '[targethost]'
<targethost> (0, 'sftp> put /var/folders/d9/7d_sb4mj1bz1jywsy8rrpj61n4xnb5/T/tmpn5u5tS /home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570/pamd.py\n', '')
<targethost> ESTABLISH SSH CONNECTION FOR USER: ansibleuser
<targethost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansibleuser -o ConnectTimeout=10 -o ControlPath=/Users/excutinguser/.ansible/cp/7963328e97 targethost '/bin/sh -c '"'"'chmod u+x /home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570/ /home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570/pamd.py && sleep 0'"'"''
<targethost> (0, '', '')
<targethost> ESTABLISH SSH CONNECTION FOR USER: ansibleuser
<targethost> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=ansibleuser -o ConnectTimeout=10 -o ControlPath=/Users/excutinguser/.ansible/cp/7963328e97 -tt targethost '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-uksgmxxzejdxgcahpebkeiztjrtjbshs; /usr/bin/python /home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570/pamd.py; rm -rf "/home/ansibleuser/.ansible/tmp/ansible-tmp-1494281124.64-106881662588570/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<targethost> (0, '\r\n{"invocation": {"module_args": {"control": "required", "new_module_path": "pam_rootok.so", "name": "su", "dest": "/etc/pam.d/su", "module_path": "pam_wheel.so", "new_type": "auth", "state": "before", "new_control": "sufficient", "path": "/etc/pam.d", "type": "auth", "module_arguments": ["use_uid"]}}, "changed": false, "ansible_facts": {"pamd": {"changed": false, "result": {"action": "insert_before_rule", "change_count": 0}}}}\r\n', 'Shared connection to targethost closed.\r\n')
ok: [targethost] => {
    "ansible_facts": {
        "pamd": {
            "changed": false, 
            "result": {
                "action": "insert_before_rule", 
                "change_count": 0
            }
        }
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "control": "required", 
            "dest": "/etc/pam.d/su", 
            "module_arguments": [
                "use_uid"
            ], 
            "module_path": "pam_wheel.so", 
            "name": "su", 
            "new_control": "sufficient", 
            "new_module_path": "pam_rootok.so", 
            "new_type": "auth", 
            "path": "/etc/pam.d", 
            "state": "before", 
            "type": "auth"
        }
    }
}

```

**Comment by Akasurde** [comment]
@theballdredge I think, you are trying to add an existing module `pam_rootok.so` using `new_module_path` argument. This will result in no change in `/etc/pam.d/su` file as module exists previously. 

You can try following Ansible Playbooks to have 
`auth required pam_wheel.so use_uid` inserted after `auth sufficient pam_rootok.so`

```yaml
---
- name: Debugging
  hosts: localhost
  tasks:
    - name: insert pam_wheel requirement because it doesnt exist
      pamd:
        name: su
        type: auth
        control: sufficient
        module_path: pam_rootok.so
        module_arguments: 'use_uid'
        state: after
        new_type: auth
        new_control: required
        new_module_path: pam_wheel.so
```
Notice that `new_module_path` is `pam_wheel.so` which needs to be inserted after `pam_rootok.so`
