### ISSUE TITLE
tower_user set organisation field has no effect.  

### ISSUE THREAD

**Issue by lshake** [ansible/ansible#24510]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module: tower_user

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/xxxxxxx/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar  3 2017, 11:49:06) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

- Tower CLI 3.1.3
- Tower 3.1.3
- Tower 3.03

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Ansible : OSX El Capitan 
Tower 3.1 : RHEL7.3
Tower 3.0 : RHEL 6.6

##### SUMMARY
The tower-user module suggests that when adding a user it should be added to an organisation when the organization option is set on the task : "Organization the user should be made a member of."  This fails and user is not made a member of the specified organisation.  

##### STEPS TO REPRODUCE
```
- hosts: localhost
  gather_facts: false

  tasks:
    - name: create the tower orgs
      tower_organization:
        name: project2
        description: "Org for Project2"
        state: present
        tower_config_file: "./tower_cli_data/192.168.133.153.cfg"
        
    - name: create the users
      tower_user:
        organization: project2
        username: testuser
        password: password
        email: user@example.com
        first_name: Testy
        last_name: McTestFace
        state: present
        tower_config_file: "./tower_cli_data/192.168.133.153.cfg"
```

##### EXPECTED RESULTS
testuser should be a member of organization project2

##### ACTUAL RESULTS
testuser exists and can login but is not a member of any organisations

**Comment by lshake** [comment]
It looks like the organization field doesn't exist in the tower_cli function here : https://github.com/ansible/tower-cli/blob/c5d246a1bfa5dcc56f716c7d5b0cac8acb4ad7cd/tower_cli/resources/user.py

This might just be a documentation bug and need removing, if so I can prepare a pull request to remove the organization field from the documentation and calling code.

**Comment by ansibot** [comment]
cc @ghjm @jlaska @matburt @wwitzel3
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wwitzel3** [comment]
Users are no longer directly associated with organizations and must be given the `member` role.
You can use the `tower_role` module to perform this action.

```
- name: Add testuser to project2 org
  tower_role:
    user: testuser
    organization: project2
    role: member
```
