### ISSUE TITLE
replace module fails when processing non-utf-8 encoded files with umlauts

### ISSUE THREAD

**Issue by flokru** [ansible/ansible#24521]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
replace module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/flokru/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb  4 2017, 22:02:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
None.

##### OS / ENVIRONMENT
macOS Sierra, Ansible via Homebrew

##### SUMMARY
replace module fails when processing non-utf-8 encoded files with umlauts

##### STEPS TO REPRODUCE
```
- name: Replace something in a iso-8859-1-encoded file
  replace:
    dest: /path/to/iso-8859-1-encoded-file.txt
    replace: "{{ item.replace }}"
    regexp: "{{ item.regexp }}"
  with_items:
    - { regexp: "pattern", replace: "new_value" }
```

##### EXPECTED RESULTS
`pattern` will be replaced by `new_value` in `/path/to/iso-8859-1-encoded-file.txt`

##### ACTUAL RESULTS
Ansible crashes with 

```
failed: [myhost.domain.tld] (item={u'regexp': u'pattern', u'replace': u'new_value'}) => {"failed": true, "item": {"regexp": "pattern", "replace": "new_value"}, "module_stderr": "Shared connection to myhost.domain.tld closed.
", "module_stdout": "Traceback (most recent call last):
  File \"/tmp/ansible_D5fUnl/ansible_module_replace.py\", line 200, in <module>
    main()
  File \"/tmp/ansible_D5fUnl/ansible_module_replace.py\", line 169, in main
    contents = to_text(f.read(), errors='surrogate_or_strict')
  File \"/tmp/ansible_D5fUnl/ansible_modlib.zip/ansible/module_utils/_text.py\", line 232, in to_text
  File \"/usr/lib/python2.7/encodings/utf_8.py\", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 114: invalid continuation byte
", "msg": "MODULE FAILURE", "rc": 0}
```

Position 114 in the text file is a German umlaut in iso-8859-1 encoding.
