### ISSUE TITLE
adding firewalld sources with delegated task does not work properly

### ISSUE THREAD

**Issue by mafalb** [ansible/ansible#24529]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
firewalld module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /path/to/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 27 2017, 03:04:19) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
```
[defaults]

# default to local vagrant dev setup
inventory = inventories/vagrant

roles_path = roles
gathering = smart
```

##### OS / ENVIRONMENT
ansible on macOS
target machines are CentOS 7

##### SUMMARY
I want to add IP Addresses as source to a firewalld zone.
I delegate the firewalld task.
Only one IP per run is added (not all of them).

##### STEPS TO REPRODUCE
start firewalld on x1
run the following play against x1,x2,x3

```yaml
---
- hosts: x1,x2,x3
  tasks:
    - name: allow access to x1
      firewalld:
        source: "{{ansible_eth1['ipv4']['address']}}"
        zone: dmz
        state: enabled
        permanent: yes
        immediate: no
      delegate_to: x1
```

##### EXPECTED RESULTS
the ip addresses of all 3 hosts are added as source to the firewalld zone

```
# firewall-cmd --info-zone dmz --permanent
dmz (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 192.168.33.200 192.168.33.201 192.168.33.202
  services: ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  sourceports: 
  icmp-blocks: 
  rich rules:
```

##### ACTUAL RESULTS
only one address is added as source. after subsequent runs eventually all addresses are added. 

```
# firewall-cmd --info-zone dmz --permanent
dmz (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 192.168.33.200
  services: ssh
  ports: 
  protocols: 
  masquerade: no
  forward-ports: 
  sourceports: 
  icmp-blocks: 
  rich rules:
```
