### ISSUE TITLE
Feature Idea: Change font color of failed tasks that are "rescued" to bright purple (color for warn) or some non-red color

### ISSUE THREAD

**Issue by jamesongithub** [ansible/ansible#24525]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  configured module search path = [u'modules']
  python version = 2.7.13 (default, Apr 13 2017, 16:18:01) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

When scanning logs, people are confused when tasks that are "rescued" are shown in red thinking it's a failure. In reality the error was handled or the error actually came later. It's not really a big deal in terms of functionality, mainly usability, just easier to search for errors quickly and to not confuse people unfamiliar with ansible. Changing all error tasks to non-red would probably not be helpful.

##### STEPS TO REPRODUCE

```yaml
---

- hosts: localhost
  connection: local
  tasks:
    - block:
      - name: i'm red
        command: "false"
      rescue:
        - name: i'm yellow
          command: "true"
    - name: still going
      command: "true"
```
![image](https://cloud.githubusercontent.com/assets/4452738/25970907/49aad568-364f-11e7-951d-95712836429f.png)

##### EXPECTED RESULTS

Non-red color for rescued tasks.

##### ACTUAL RESULTS

All failed tasks are shown in red.

```

```
