### ISSUE TITLE
puppet module fails because of PUP-6739

### ISSUE THREAD

**Issue by nicobrevin** [ansible/ansible#24530]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

puppet module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

puppet4, centos7, but probably affects all

##### SUMMARY

puppet module reports "Puppet agent state could not be determined." with puppet4 when environment directory does not exist on slave, due to lockfile detection method and bug in puppet4 (https://tickets.puppetlabs.com/browse/PUP-6739)

##### STEPS TO REPRODUCE

```yaml
# on a clean centos7 machine, presumably other OSs are affected as well
- name:	Repeat a bug
  hosts: 'localhost'
  become: true
  gather_facts: false
  tasks:

    - name: Install PuppetLabs GPG key
      rpm_key:
        state: present
        key: https://yum.puppetlabs.com/RPM-GPG-KEY-puppet

    - get_url: url=https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm dest=/tmp/puppetlabs-repo.rpm

    - name: Add PuppetLabs rpm repo
      yum: name=/tmp/puppetlabs-repo.rpm

    - name: Install Puppet
      yum:
        name: puppet-client-tools
        update_cache: yes

    - lineinfile:
        path: /etc/puppetlabs/puppet/puppet.conf
        regexp: ^environment
        line: environment=non-default

    - puppet: tags=foo-bar
 
```

##### EXPECTED RESULTS

Some kind of output from puppet to say no cert and wait for cert disabled

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "certname": null, 
            "environment": null, 
            "execute": null, 
            "facter_basename": "ansible", 
            "facts": null, 
            "logdest": "stdout", 
            "manifest": null, 
            "puppetmaster": null, 
            "show_diff": false, 
            "tags": [
                "foo-bar"
            ], 
            "timeout": "30m"
        }
    }, 
    "msg": "Puppet agent state could not be determined."
}

```

**Comment by nicobrevin** [comment]
Simple workaround is to add this when setting up agents:

```
name: Puppet environment
  file:
    path: "/etc/puppetlabs/code/environments/{{ puppet_environment }}"
    state: directory
```
