### ISSUE TITLE
Meta doesn't pick up on variable defined in group_vars, defaults or role vars

### ISSUE THREAD

**Issue by Ortham** [ansible/ansible#24538]
#### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core, I think?

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/oliver/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.11 (default, Jan 22 2016, 08:29:18) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION

My ~/.ansible.cfg contains only the following:

```
[defaults]
transport=paramiko
timeout=60
remote_tmp = /tmp/.ansible/tmp
```

##### OS / ENVIRONMENT
Running on macOS Sierra 10.12.4
Managing OEL 6.4

##### SUMMARY

I'm trying to specify a role dependency, giving a path to the dependency role that includes a variable defined in my `group_vars`, but I get `ERROR! 'common_roles_path' is undefined`. It only works if I define the variable in the play that uses the role.

##### STEPS TO REPRODUCE

My directory structure is as follows

```
common_roles/
  foo/
project/
  group_vars/
    all.yml
  roles/
    server/
       defaults/
          main.yml
       meta/
          main.yml
       tasks/
          main.yml
       vars/
          main.yml
  hosts
  sites.yml
```

`project/group_vars/all.yml`, `project/roles/server/defaults/main.yml` and `project/roles/server/vars/main.yml` all contain

```yaml
---

common_roles_path: "{{ playbook_dir }}/../common_roles"
```

`project/roles/server/meta/main.yml` contains

```yaml
---

dependencies:
  - role: "{{ common_roles_path }}/foo"
```

`project/roles/server/tasks/main.yml` contains

```yaml
---

- include_role:
    name: "{{ common_roles_path }}/foo"
```

`project/hosts` contains

```
[servers]
project.dev.vm
```

`project/sites.yml` contains

```yaml
---

- name: Install project server
  hosts: servers
  roles:
    - server
```

##### EXPECTED RESULTS

I expect the role at `common_roles/foo` to be executed as a dependency, then run again due to the `include_role` task.

##### ACTUAL RESULTS

I get the following:

```
$ ansible-playbook -vvvv -i hosts sites.yml
Using /Users/oliver/.ansible.cfg as config file
ERROR! 'common_roles_path' is undefined
```

However, if I modify `project/sites.yml` to contain

```yaml
---

- name: Install project server
  hosts: servers
  roles:
    - server
  vars:
    common_roles_path: "{{ playbook_dir }}/../common_roles"
```

then everything works as expected. It also works if I remove `project/roles/server/meta` and just rely on the `include_role` task (so the same variable used there is OK). 

The duplicate variable definitions in `project/roles/server/defaults` and `project/roles/server/vars` were only added to check if it was some scoping issue, their presence or absence makes no difference.
