### ISSUE TITLE
Module - tower_project fails to add scm_credential 

### ISSUE THREAD

**Issue by lshake** [ansible/ansible#24547]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module - tower_project

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/xxxxxxx/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar  3 2017, 11:49:06) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

```
- Tower CLI 3.1.3
- Tower 3.1.3

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Ansible : OSX El Capitan 
Tower 3.1 : RHEL7.3

##### SUMMARY
The tower_project module fails to set the credential required for SCM sync

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  tasks:

  - name: create the tower org
    tower_organization:
      name: Org1
      description: "A test org"

  - name: create a credential
    tower_credential:
      name: scm_key
      description: "GitHub key for project repo"
      organization: Org1
      kind: scm
      ssh_key_data: "files/git_deploy_key"
      ssh_key_unlock: "password123"

  - name: create a project
    tower_project:
      name: project01
      description: "A test Project"
      organization: Org1
      scm_branch: master
      scm_type: git
      scm_url: "git@git.example.com:project01.git"
      scm_credential: scm_key
```

##### EXPECTED RESULTS
A new project, project01, should be created using the scm_key credential

##### ACTUAL RESULTS
Playbook completes without errors, but the project has an empty credential.  

This looks to be some misalignment between the module and tower-cli python 
module.  There may be two problems here, the first is that the API requires the 
credential to be submitted as an ID, but I can't see the translation from name 
to ID happening.  It would be trivial to do that in the tower_project module as 
a look up in the same way that the organization is looked up, but this might not
be the intent as creating the project using native tower-cli works.   

The second problem, might be related to the field name being "scm_credential"
rather than just "credential".   Changing the parameters supplied to the 
project.modify call in tower_project to be 
"credential=<hard_coded_credential_id>" make it work, but this may have unknown
implications.
