### ISSUE TITLE
vmware_guest.py Clone operation not working with tree of default resource pools

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#24548]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- vmware_guest.py 

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

Default configuration

##### OS / ENVIRONMENT

Debian Jessie managing vCenter Server 5.1.0 2669725

##### SUMMARY

Deploy a VM from a template is not working in an environment with multiple hosts under multiple clusters in a datacenter with no resource pools defined.

##### STEPS TO REPRODUCE

```yaml
- name: deploy new VM from template
  vmware_guest:
#   cluster: "{{ cluster }}"
    annotation: "{{ annotation }}"
    hostname: "{{ hostname }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: "{{ validate_certs }}"
    esxi_hostname: "{{ esxi_hostname }}"
    datacenter: "{{ datacenter }}"
    folder: "{{ folder }}"
    name: "{{ name }}"
    state: "{{ state }}"
    guest_id: "{{ guest_id }}"
    template: "{{ template }}"
    disk:
      - size_gb: 30
        type: thin
        datastore: "{{ datastore }}"
    networks:
      - name: "{{ network }}"
        ip: "{{ guest_ip }}"
        netmask: 255.255.255.0
    hardware:
      memory_mb: "{{ vm_memory | default(1024) }}"
      num_cpus: 2

```

##### EXPECTED RESULTS

A VM should be deployed from the template to the host 192.168.1.6

##### ACTUAL RESULTS

Running the above playbook with the command
```
ansible-playbook -i hosts --check deploy_VMTemplate_webserver.yml --ask-vault-pass -vvvv
```
and entering the vault password results in
```
fatal: [192.168.1.5]: FAILED! => {
    "changed": true, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "annotation": "Testing deploy automation", 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "MY-DATACENTER", 
            "disk": [
                {
                    "datastore": "MY-DATASTORE", 
                    "size_gb": 30, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": "192.168.1.6", 
            "folder": "/vm/TEMPLATES/MY-TEMPLATES", 
            "force": false, 
            "guest_id": "debian6_64Guest", 
            "hardware": {
                "memory_mb": "1024", 
                "num_cpus": 2
            }, 
            "hostname": "192.168.1.5", 
            "is_template": false, 
            "name": "debian-deploy", 
            "name_match": "first", 
            "networks": [
                {
                    "ip": "192.168.1.10", 
                    "name": "HOSTING-DMZ", 
                    "netmask": "255.255.255.0"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": null, 
            "state": "poweredon", 
            "template": "TEMPLATE_INFRA_debian8", 
            "template_src": "TEMPLATE_INFRA_debian8", 
            "username": "internal\\me", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "A specified parameter was not correct. \n"
}
```
I've checked all the parameters multiple times.

From the vCenter logs: Host not found in the specified resource pool
```
grep -r "error 'VmProv'" .

./Logs/vpxd/vpxd-4342.log:2017-05-09T01:23:58.528-04:00 [07124 error 'VmProv' opID=d38b251d-c1] Host [vim.HostSystem:host-3328,172.16.1.131] not found in the specified resource pool [vim.ResourcePool:resgroup-27,Resources]
./Logs/vpxd/vpxd-4342.log:2017-05-09T01:23:58.528-04:00 [07124 error 'VmProv' opID=d38b251d-c1] [Workflow] Get exception while executing action vpx.vmprov.SelectDestination: vmodl.fault.InvalidArgument

```
Please see also https://github.com/ansible/ansible-modules-extras/issues/2911

Since the circumstances and errors are identical in these two cases, I suspect an issue remains with ansible walking the default resource pool tree - but while the patch for the issue linked above fixed a situation with two levels of default resource pools (datacenter with multiple hosts)  my environment has three levels - datacenter with multiple host clusters and some non-clustered hosts on the second level, and multiple hosts under the clusters as well for a third level in the tree.
