### ISSUE TITLE
Install Chocolatey from Internal Source

### ISSUE THREAD

**Issue by ferventcoder** [ansible/ansible#24569]
Originally at https://github.com/ansible/ansible-modules-extras/issues/2916 @dagwieers suggested it get moved here.

cc @nitzmahone 
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME
win_chocolatey

##### OS / ENVIRONMENT
Windows

##### SUMMARY
Folks would like to be able to have Chocolatey installed from internal sources when using the Ansible module, particularly when they are completely offline.

This would be a good capability added to the module. It is already supported by other config mgmt tools so those could provide good references on how to add it to the chocolatey ansible module.

**Comment by ferventcoder** [comment]
Some relevant details at https://github.com/ansible/ansible-modules-extras/issues/2916#issuecomment-247076990

**Comment by ansibot** [comment]
cc @smadam813
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
At [19:00 UTC](http://www.thetimezoneconverter.com/?t=19:00&tz=UTC) this ticket will be processed during [the first Windows Sprint](https://github.com/ansible/community/wiki/Windows:-sprints#2017-07-04-1900-utc-sprint-1), we would appreciate if you could join the Sprint to help out with fixing/closing this issue.

**Comment by dagwieers** [comment]
This feature request was discussed during Windows Sprint 1, it definitely seems very useful to have as a feature. We are looking for someone willing to implement this.
needs_contributor

**Comment by dagwieers** [comment]
@ferventcoder Maybe I don't understand the request correctly, but isn't this already possible with the `source:` parameter ? You can provide a URL where to install the package from.

If you want to change the default source, that's something that is going to require a separate module (**win_chocolatey_config** ?) or could be done adding environment variables using **win_environment**.

So I see 2 possible solutions, and 1 potential new module.

**Comment by ferventcoder** [comment]
Install of Chocolatey itself, not packages. If there is already a way to do this, please point me to the docs

**Comment by jhawkesworth** [comment]
@ferventcoder looks like there are instructions for offline install of chocolatey on the chocolatey site here. You would probably just need to modify the powershell script https://chocolatey.org/install#completely-offline-install run it via the script module.

**Comment by nitzmahone** [comment]
(just for context, @ferventcoder is the creator of chocolatey) There aren't currently any knobs to turn on the win_chocolatey module to control the installation process of the chocolatey tools, but there probably should be. In particular, the current implementation violates a check mode tenet by potentially making changes to a target in check mode (installing chocolatey itself)- this has been corrected in most other package manager modules. This should probably be an option, as well as the source of the install script, and potentially the target chocolatey location.

**Comment by dagwieers** [comment]
I was thinking about this earlier. We could easily use the options of the module for the chocolatey installation when the package-name is "chocolatey". This would make sense because that's what the user is requesting anyway.

In this case `source:` would be acted on. Wouldn't that be possible ?

needs_contributor

**Comment by ansibot** [comment]
cc @elventear @petemounce @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jborean93
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ptemplier
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ferventcoder** [comment]
Just as an FYI, I'm writing some user documentation on how to support offline installation across different configuration managers and I'm noting that it's not possible and pointing back to this issue as a placeholder until this is implemented.

**Comment by ferventcoder** [comment]
FYI, here is a view of those docs:

![image](https://user-images.githubusercontent.com/63502/36075607-ec69a90a-0f16-11e8-9131-671d9a51f534.png)

**Comment by mjdavies** [comment]
Hello everyone.  This is showstopper for us, is there any news on this?

We'll have to use something other than ansible if we can't install chocolatey from an internal source, and I'd really prefer not to have to do that as we're big fans of both softwares.

**Comment by jhawkesworth** [comment]
@mjdavies You can probably script the installation of chocolatey using a few playbook steps - download the chocolatey installer from some local location using `win_get_url` and run it using `win_shell`, so adding this feature into the module itself, while desirable, probably hasn't proved necessary for others.
You can probably take a look at the module code to see how it runs the chocolatey installer too.

I suggest you have a look at the module code though (win_chocolatey.ps1), as it might be easy enough to add another another parameter to specify a location to fetch chocolatey installer from.  If so, please consider creating a pull request.  I suspect this one has just languished because it can be worked around, and fully air-gapped systems such as yours are relatively rare.

**Comment by jborean93** [comment]
Adding to what @jhawkesworth says, there is nothing stopping you from getting the offline installers for Chocolatey and installing it with win_shell. This is just a convenience if the module allowed you to do it but I'm still not sure if it should install Chocolatey at all.

Having a web server to source the files from is pretty much assumed in an offline scenario as you would require this web server for win_chocolatey to actually get the packages from anyway.

**Comment by anvpetrov** [comment]
Hello It is easy to add this feature.  I ll try to create pull request on this week.

**Comment by jborean93** [comment]
Updated the title to reflect that we don't want to add more options to the win_chocolatey module for installing Chocolatey but rather have some better examples of how to do this outside the module. See https://github.com/ansible/community/issues/294#issuecomment-399319602

**Comment by ferventcoder** [comment]
Please can you put back original title and close it as won't do, then add another issue for what you suggest and point to that from here?

If the module is going to contain any ability to install Chocolatey itself, then it needs to be able to point to an internal source - that is a requirement of many of our customers - unlike non-Windows platforms the community repository is not used at all (or at least not directly) by organizations who would use Chocolatey and Ansible.

Adding it to win_chocolatey is the is the spirit of my original request - I already knew there were other ways to handle it (there is always a way when you have exec or win_shell resources). Some folks might consider using those low level resources as an anti-pattern and harder to make idempotent, but that's not what we are discussing here.

**Comment by ferventcoder** [comment]
That is the spirit of my original request - I already knew there were other ways to handle it (there is always a way when you have exec or win_shell resources). Some folks might consider using those low level resources as an anti-pattern and harder to make idempotent, but that's not what we are discussing here.

**Comment by jborean93** [comment]
Changing it back @ferventcoder, I've opened a new issue here https://github.com/ansible/ansible/issues/42026.

In reality I just need to play around with installing Chocolatey a bit more to get a better understanding of what is really involved. One quick question for you though, do you find most customers who need to install offline create their own scripts to deploy the nupkg or just use the existing one [here](https://chocolatey.org/install#completely-offline-install)?

**Comment by jborean93** [comment]
Hmm I am going to reopen this, I need to have a closer look at how Chocolatey Server actually works with serving the `install.ps1` script.

**Comment by Tras2** [comment]
I've managed to do this by doing this:-

(you need to pass in _choco_server_ variable)
```
  # check if chocolatey is already installed
  - name: Get status of Chocolatey installation
    win_stat:
      path: c:\programdata\chocolatey\choco.exe
    register: choco_file_info
    changed_when: false

  # if it isn't, install it
  # Powershell command forces TLS 1.2 as the internal chocolatey server only listens on that
  - name: Install Chocolatey
    win_command: powershell.exe -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12; iex ((New-Object System.Net.WebClient).DownloadString('https://{{ choco_server }}/install.ps1'))"
    when: choco_file_info.stat.exists == false

  - name: Add Chocolatey to path
    win_path:
      elements: '%ALLUSERSPROFILE%\chocolatey\bin'
      scope: machine
      state: present
```

**Comment by jborean93** [comment]
With https://github.com/ansible/ansible/pull/43013, it is ~~not~~ now possible for win_chocolatey to source the install.ps1 script based on the `source` option. Will be going through the Chocolatey docs at a future point to reference all the recent changes.

**Comment by ferventcoder** [comment]
> In reality I just need to play around with installing Chocolatey a bit more to get a better understanding of what is really involved. One quick question for you though, do you find most customers who need to install offline create their own scripts to deploy the nupkg or just use the existing one here?

@jborean93 Most organizations ***NEVER*** use the community repository (aka https://chocolatey.org/packages) directly (including installing Chocolatey itself). It might be a good idea to review https://chocolatey.org/docs/how-to-setup-offline-installation to really understand the organizational perspective.

**Comment by ferventcoder** [comment]
> Hmm I am going to reopen this, I need to have a closer look at how Chocolatey Server actually works with serving the install.ps1 script.

@jborean93 Chocolatey.Server is also only one option for a repository out of like 30+ different repository options, so I wouldn't tie too specifically to it either. https://chocolatey.org/docs/how-to-host-feed and https://chocolatey.org/docs/how-to-setup-offline-installation#exercise-6-installing-chocolatey-on-client-machines

**Comment by ferventcoder** [comment]
A diagram will save a lot of explaining - [Chocolatey Architecture Diagram (PDF)](https://github.com/ansible/ansible/files/2225829/Chocolatey.Central.Management.Architecture.Diagram.-.Low.Level.-.v1_4.pdf)

**Comment by jborean93** [comment]
@ferventcoder sorry massive typo, `not == now` so with PR 43013 it is **now** possible to specify the source. There is some difficulty with trying to specify the install URL due to some of the magic that goes with the `http://site/install.ps1` in Chocolatey server, currently here is what happens;

* If the source specified ends with `install.ps1` then the module will use that script to install Chocolatey allowing people to use a non Chocolatey server repo source
* If the source does not end with `install.ps1` then it will be parsed and the URL `{scheme}://{host}:{port}/install.ps1` is used instead allowing a single call to win_chocolatey to install Chocolatey itself as well as any packages required by the user
* If the source is not specified then the public URL is used - the default option right now

What makes this difficult is that it pretty much relies on a user to have the install script called `install.ps1` (this can be located on any path though just needs to be called that). This is easy for Chocolatey server users and we wanted to try and go the path of least resistence for the Chocolatey ecosystem.

The main reason why we parse the URL in this way is that `win_chocolatey` is mostly used to specify the packages the user wants and they expect the module to handle all the bootstrapping of Chocolatey itself for them. So when someone writes a task for this module they specify the packages with a source to the nuget feed of the server and not to the individual script/nupkg. We need to handle this accordingly so the below will work when Chocolatey is not present (by sourcing the install script from `http://server/install.ps1`);

```
- name: install Chocolatey and notepadplusplus from internal Chocolatey server
  win_chocolatey:
    name: notepadplusplus
    state: present
    source: http://server/chocolatey
```

If someone was not using Chocolatey server, or they wished to specify a custom script, then the following will also work for them;

```
- name: install Chocolatey from internal server
  win_chocolatey:
    name: chocolatey
    state: present
    source: https://someserver/somepath/chocolatey/install.ps1  # must end with install.ps1 or https://someserver/install.ps1 is used instead

- name: install notepadplusplus from internal server
  win_chocolatey:
    name: notepadplusplus
    state: present
    source: https://someserver/api/v2/  # now Chocolatey is installed the source is the usual nuget feed path
```

They can also use [win_chocolatey_source](https://docs.ansible.com/ansible/devel/modules/win_chocolatey_source_module.html) (also new to 2.7) to configure the sources once Chocolatey has been initially installed, reducing the need to specify `source` on each call.

Hopefully that clears up the confusion but in devel and 2.7 (once released) it is possible to get the `win_chocolatey` module to install Chocolatey itself from an internal source.

Thanks for the added information, it explains a bit more I didn't understand more.
