### ISSUE TITLE
New feature: iptables module

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#2459]
The local firewall, via iptables is a common configuration task, but often a PITA.

We could really use a module for this. Issues are the ordered nature of the file.

An approach would be to execute iptables rules from the command line, then use "save" features to allow the firewall to write its own config. However, idempotency may be difficult to implement then, and there's a good bit of risk of locking yourself out!

Example taken from Gluster 3.1 guide:

```
$ iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 24007:24011 -j ACCEPT 
$ iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 111 -j ACCEPT 
$ iptables -A INPUT -m state --state NEW -m udp -p udp --dport 111 -j ACCEPT 
$ iptables -A INPUT -m state --state NEW -m tcp -p tcp --dport 38465:38485 -j ACCEPT
$ service iptables save
$ service iptables restart
```

on Fedora 17 the "save" command is "/usr/libexec/iptables.init save "

**Comment by leucos** [comment]
Not sure how an iptables module would solve this. I see two ways to handle iptables rules :
- have an iptables playbook (mostly a template) that cover all use cases : central, but cumbersome, hard to read and hard to maitain
- use the assemble module which could assemble iptables fragments and notify a reload. A bit verbose though, since each service-level playbook has to notify assembling the rules and eventually reload them

While I still use the first approach, I'm faily convinced that the latter is the right way to do it. It introduces a real separation of concerns, and each service takes care of it's own rules. 

I might be mistaken, but this is why I don't see what an iptables module would add compared to the assemble way of building the rules.

**Comment by lwade** [comment]
Maybe I'm missing something here but template the rules into a file and then iptables-restore < myfile ?  I think an iptables module might be difficult since you'd need to run lots of actions to populate a pretty complex ruleset, I see no way of doing this neatly through a single action with a module.

**Comment by bennojoy** [comment]
The way i handled it was as such:
- name: Add the iptable rule to allow traffice dynamically
  shell: iptables -I INPUT 2  -p tcp --dport
  ${mongodb_port_prefix}${result.stdout} -j ACCEPT
- name: insert iptables rule for mongod
  lineinfile: dest=/etc/sysconfig/iptables state=present
  regexp="$mongodb_port_prefix${result.stdout}" insertafter="^:OUTPUT "
  line="-A INPUT -p tcp  --dport "$mongodb_port_prefix${result.stdout}" -j
  ACCEPT"

first add the rule dynamatically, and then add it to
/etc/sysconfig/iptables, which is the default file for iptables load in
centos.

Regards,
Benno Joy

**Comment by robparrott** [comment]
Building iptables from from a single template is not adequate, since you want

(1) idempotency and
(2) to be able to combine multiple functionalities into an aggregate playbook (i.e. a table that makes mysql ports available would wipe out ports opened for a web server)

While doing the job the "100% right way" -- maintaining order and allowing for complex rules and all the vagaries of iptables -- would be hard, a limited functionality that simply added (appended) or dropped rules from a given chain would be straightforward, and would cover 80% of real world cases (i.e. "I need to open port 80 and 443 to an IP range").

Ala Benno's example.

**Comment by lwade** [comment]
Doing this via the template module is idempotent though, so I don't think (1) is valid and I don't think (2) is of concern either, since you just need to make sure groups and roles are defined correctly.

**Comment by robparrott** [comment]
Can you define what you mean my groups and roles here?

This is how I think of it:

Suppose I have a playbook that sets up service A (apache), and a different
one that sets up service B (jabber). On both, iptables is configured using
a template as you suggest. If service A is on host A, and service B is
setup on host B, then things are fine.

But now I want to put both services on the same host A. With this approach,
the template in the 2nd playbook will clobber the config from the first.

The point is that this approach is brittle, and well written playbooks
should be compatible. That's why a template approach, while useful in a
narrow sense, does not scale.

If we are only dealing with adding rules to a default chain, then adding
rules via iptables -A and then saving state -- as Benno suggest -- will
avoid this issue, avoid "clobbering."

What you lose is an easy way to manage the order of the rules, but in many
cases that's not a big deal.

So I think an iptables module that would (all in a single, legible playbook
line) check for rules in a chain, and then append the rule if it's not
present (and same with state=absent), will be of service to many folks,
though not comprehensive. If you need careful tuning of the chains, then
one would need to take your template approach.

Rob

**Comment by lwade** [comment]
In my mind that's why you'd have a _common_ templating operation, with some conditionals.  Not a templating operation for both.  If the host is in both groups then template like blablabla, whereby it just piles up rules depending on what services exist on the host.  That was basically what I meant by my statement re: (2).

**Comment by mpdehaan** [comment]
I believe iptables should be managed by template, or you should punch holes in the firewall via something like lokkit, but much better if you do something with template.

Idempotency is not an issue because you can gate the restart on the template changing.

**Comment by rclayton-the-terrible** [comment]
This worked for me, and it didn't require managing a template (allowing you to compose IPTables modifications from multiple playbooks):

``` yaml
- hosts: all
  tasks:
    - name: Open the correct IPTables ports
      lineinfile: dest=/etc/sysconfig/iptables
                  regexp="^-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT$"
                  line="-A INPUT -p {{item.protocol}} -m {{item.protocol}} --dport {{item.port}} -j ACCEPT"
                  insertafter="^:OUTPUT ACCEPT \[\d*:\d*\]$"
      with_items:
        - { protocol: tcp, port: 80 }
        - { protocol: tcp, port: 443 }
        - { protocol: tcp, port: 389 }
        - { protocol: tcp, port: 636 }
        - { protocol: tcp, port: 88 }
        - { protocol: tcp, port: 464 }
        - { protocol: tcp, port: 53 }
        - { protocol: udp, port: 88 }
        - { protocol: udp, port: 464 }
        - { protocol: udp, port: 53 }
        - { protocol: udp, port: 123 }
      notify:
        - restart iptables

  handlers:
      - name: restart iptables
        action: service name=iptables state=restarted
```
