### ISSUE TITLE
Valid SSH connection fails with delegate_to and forks >15

### ISSUE THREAD

**Issue by weldpua2008** [ansible/ansible#24594]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
ansible-playbook --version

```
ansible-playbook 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### CONFIGURATION
 cat /etc/Ansible/ansible.cfg |grep -vE '^#|^$'
```
[defaults]
gathering = smart
host_key_checking = False
callback_whitelist = slack
fact_caching = jsonfile
fact_caching_connection = /tmp
fact_caching_timeout = 1800
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[accelerate]
[selinux]
[colors]
```

##### OS / ENVIRONMENT
CentOS Linux release 7.2.1511 (Core)
3.10.0-327.18.2.el7.x86_64

##### SUMMARY
When I am using -f > 15 task with task (where delegate_to is used) it cannot complete due to Unreachable error.
If I am using -f <15 it's never failed.

##### STEPS TO REPRODUCE
 ansible-playbook -i /etc/Ansible/cedato/hosts /etc/Ansible/cedato/site.yml -l s* -f 19 -t zabbix_userparams

##### EXPECTED RESULTS
All hosts aviable

##### ACTUAL RESULTS
ansible-playbook -i /etc/Ansible/cedato/hosts /etc/Ansible/cedato/site.yml -l s* -f 19 -t zabbix_userparams -vvvv

```
<zabbix.local> PUT /tmp/tmpl5vI26 TO /root/.ansible/tmp/ansible-tmp-1494757544.08-167735311526944/command.py
<zabbix.local> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[zabbix.local]'
<zabbix.local> PUT /tmp/tmpayqzRx TO /root/.ansible/tmp/ansible-tmp-1494757544.08-46307252744577/command.py
<zabbix.local> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r '[zabbix.local]'
fatal: [s21.local]: UNREACHABLE! => {
    "changed": true,
    "msg": "All items completed",
    "results": [
        {
            "_ansible_item_result": true,
            "item": "nginx.avg.rt[_total]",
            "msg": "Failed to connect to the host via ssh: ssh_exchange_identification: read: Connection reset by peer\r\n",
            "unreachable": true
        },


PLAY RECAP *********************************************************************
s1.local             : ok=3    changed=2    unreachable=0    failed=0
s10.local            : ok=3    changed=2    unreachable=0    failed=0
s11.local            : ok=3    changed=2    unreachable=0    failed=0
s12.local            : ok=3    changed=2    unreachable=0    failed=0
s13.local            : ok=3    changed=2    unreachable=0    failed=0
s14.local            : ok=3    changed=2    unreachable=0    failed=0
s15.local            : ok=3    changed=2    unreachable=0    failed=0
s16.local            : ok=1    changed=0    unreachable=1    failed=0
s17.local            : ok=3    changed=2    unreachable=0    failed=0
s19.local            : ok=1    changed=0    unreachable=1    failed=0
s2.local             : ok=3    changed=2    unreachable=0    failed=0
s21.local            : ok=1    changed=0    unreachable=1    failed=0
s3.local             : ok=3    changed=2    unreachable=0    failed=0
s4.local             : ok=3    changed=2    unreachable=0    failed=0
s5.local             : ok=3    changed=2    unreachable=0    failed=0
s6.local             : ok=3    changed=2    unreachable=0    failed=0
s7.local             : ok=3    changed=2    unreachable=0    failed=0
s8.local             : ok=3    changed=2    unreachable=0    failed=0
s9.local             : ok=3    changed=2    unreachable=0    failed=0

```

```yaml
---
- name: Test Zabbix Nginx VTS module Keys
  shell: "[[ $(zabbix_get -s {{ inventory_hostname }} -k {{ item }} | tr -d '.') -ge 0 ]] || exit 1"  
  with_items:
    - "nginx.avg.rt[_total]"
    - "nginx.requests[_total,1xx]"
    - "nginx.requests[_total,2xx]"
    - "nginx.requests[_total,3xx]"
    - "nginx.requests[_total,4xx]"
    - "nginx.requests[_total,5xx]"
    - "nginx.pool.avg.rt[fastcgi_backend,127.0.0.1:9000]"
    - "nginx.pool.requests[rtb_us_west,10.1.1.1:80,1xx]"
    - "nginx.pool.requests[rtb_us_west,10.1.1.1:80,2xx]"
    - "nginx.pool.requests[rtb_us_west,10.1.1.1:80,3xx]"
    - "nginx.pool.requests[rtb_us_west,10.1.1.1:80,4xx]"
    - "nginx.pool.requests[rtb_us_west,10.1.1.1:80,5xx]"
    - "nginx.pool.requests[fastcgi_backend,127.0.0.1:9000,1xx]"
    - "nginx.pool.requests[fastcgi_backend,127.0.0.1:9000,2xx]"
    - "nginx.pool.requests[fastcgi_backend,127.0.0.1:9000,3xx]"
    - "nginx.pool.requests[fastcgi_backend,127.0.0.1:9000,4xx]"
    - "nginx.pool.requests[fastcgi_backend,127.0.0.1:9000,5xx]"
    - "nginx.pool.node.down[rtb_us_west,10.1.1.1:80]"
    - "nginx.pool.node.down[fastcgi_backend,127.0.0.1:9000]"
    - "nginx.pool.node.backup[rtb_us_west,10.1.1.1:80]"
    - "nginx.pool.node.backup[fastcgi_backend,127.0.0.1:9000]"
  delegate_to: zabbix.local
  tags:
    - 06-zabbix_agent-keys-test.yml
```

ansible -i /etc/Ansible/hosts  -m ping -f 25 s*.*
Is working
