### ISSUE TITLE
Pipe lookup plugin giving "/bin/sh: 1: docker: not found"

### ISSUE THREAD

**Issue by chenzhiwei** [ansible/ansible#24612]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lookup pipe plugin

##### ANSIBLE VERSION
```
2.3.0.0
```

##### OS / ENVIRONMENT
rhel7

##### SUMMARY
```
- debug: msg="{{ lookup('pipe', 'docker --version') }}"
```

returned "/bin/sh: 1: docker: not found", even if I used `/usr/bin/docker --version`, the error still appear.

##### STEPS TO REPRODUCE
Install Docker engine, and run following task.

```
- debug: msg="{{ lookup('pipe', 'docker --version') }}"
```

**Comment by alikins** [comment]
Where is docker installed? (ie, results of 'which docker'  ran as the user ansible-playbook runs as?)
Is the docker location in the PATH for the user ansible-playbook runs as?

**Comment by bcoca** [comment]
could you run?:
``` - local_action: shell docker --version```

**Comment by chenzhiwei** [comment]
- shell: docker --version

is ok.

docker is in /usr/bin dir

**Comment by chenzhiwei** [comment]
Hi, I run this inside a container and can reproduce it every time.

1. Create a Ubuntu 16.04 container and install Ansible 2.3.0.0

```
docker run -it ubuntu:16.04 bash
apt update
apt -y --no-install-recommends install python-pip python-wheel gcc python-dev libffi-dev libssl-dev python-setuptools
pip install ansible==2.3.0.0
```

2. Run the ansible command to reproduced the issue

```
ansible 172.16.10.123 -i hosts --key-file=id_rsa -m debug -a msg="{{ lookup('pipe', 'date') }}"
ansible 172.16.10.123 -i hosts --key-file=id_rsa -m debug -a msg="{{ lookup('pipe', 'docker --version') }}"
```

The output:

```
root@2699bc3d1c80:/xx# ansible 172.16.10.123 -i hosts --key-file=id_rsa -m debug -a msg="{{ lookup('pipe', 'date') }}"
172.16.10.123 | SUCCESS => {
    "changed": false,
    "msg": "Tue May 16 15:20:02 UTC 2017"
}

root@2699bc3d1c80:/xx# ansible 172.16.10.123 -i hosts --key-file=id_rsa -m debug -a msg="{{ lookup('pipe', 'docker --version') }}"
/bin/sh: 1: docker: not found
172.16.10.123 | FAILED! => {
    "failed": true,
    "msg": "An unhandled exception occurred while running the lookup plugin 'pipe'. Error was a <class 'ansible.errors.AnsibleError'>, original message: lookup_plugin.pipe(docker --version) returned 127"
}
```

**Comment by chenzhiwei** [comment]
I may find some issues:

When I run `ansible 172.16.10.123 -i hosts --key-file=id_rsa -m debug -a msg="{{ lookup('pipe', 'date') }}"`, actually it runs on Ansible controller node, not the node `172.16.10.123`.

The purpose of using lookup.pipe is to solve one thing:

```
    - name: Getting Docker engine version
      shell: (docker --version 2>/dev/null || echo ,,0.1) | awk -F"[ ,-]" '{print $3}'
      args:
        executable: /bin/bash
      register: docker_version

    - name: Validating Docker engine version
      fail: msg="Docker engine is not installed or version is not compatible"
      when: docker_version.stdout | version_compare('1.11.1', '<', strict=True)
```

Merge the above two task to one like following:

```
- name: Validating Docker engine version
  fail: msg="Docker engine is not installed or version is not compatible"
  when: lookup('pipe', (docker --version 2>/dev/null || echo ,,0.1) | awk -F"[ ,-]" '{print $3}') | version_compare('1.11.1', '<', strict=True)
```

Is there another way to merge the two tasks into one?
