### ISSUE TITLE
RDS read replica both requires and disallows 'subnet' parameter

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#24630]
## ISSUE TYPE

This was copied over from https://github.com/ansible/ansible-modules-core/issues/4477

Bug Report
## COMPONENT NAME

module: rds

## ANSIBLE VERSION

ansible 2.1.1.0
CONFIGURATION

[defaults]
log_path=~/.ansible/ansible.log
host_key_checking = False
vault_password_file = ~/.ansible_vault

## SUMMARY

Using the rds module with 'command: replicate' to create a read-replica in a VPC results in a failure stating that the 'subnet' must be specified. However, when the parameter is provided, a failure results stating that the 'subnet' parameter is not valid.

## STEPS TO REPRODUCE
```
- name: RDS - Replica
  hosts: localhost
  connection: local
  tasks:
    - name: Create the RDS read replica
      rds:
        command: replicate
        instance_name: "{{ rds_name }}-replica" 
        source_instance: "{{ rds_arn }}"
        publicly_accessible: no
        subnet: "{{ rds_subnet }}"
        vpc_security_groups: "{{ default_security_group_id }}"
        region: "{{ region }}"
        wait: yes
        wait_timeout: 1200
```
OR
```
- name: RDS - Replica
  hosts: localhost
  connection: local
  tasks:
    - name: Create the RDS read replica
      rds:
        command: replicate
        instance_name: "{{ rds_name }}-replica" 
        source_instance: "{{ rds_arn }}"
        publicly_accessible: no
        vpc_security_groups: "{{ default_security_group_id }}"
        region: "{{ region }}"
        wait: yes
        wait_timeout: 1200
```
## EXPECTED RESULTS

Replica gets created

## ACTUAL RESULTS

```fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Parameter subnet is not valid for replicate command"}```
OR
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to create replica instance: Cannot create t```
