### ISSUE TITLE
vmware_guest - deploy from template - object has no attribute port

### ISSUE THREAD

**Issue by mvrk69** [ansible/ansible#24648]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### OS / ENVIRONMENT
Running from: Fedora 25 (x86_64)
Managing: VMware vSphere 6 with distributed vswitch
                  ESXi: 6.0.0 build-4192238
                  vCenter: VMware vCenter Server Appliance 6.0.0.20000

##### SUMMARY
I'm trying to deploy a VM from a template using vmware_guest module, but i'm getting this error:

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_yfXPli/ansible_module_vmware_guest.py", line 1332, in <module>
    main()
  File "/tmp/ansible_yfXPli/ansible_module_vmware_guest.py", line 1321, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_yfXPli/ansible_module_vmware_guest.py", line 1070, in deploy_vm
    self.configure_network(vm_obj=vm_obj)
  File "/tmp/ansible_yfXPli/ansible_module_vmware_guest.py", line 674, in configure_network
    if nic.device.backing and ( nic.device.backing.port.portgroupKey != pg_obj.key or nic.device.backing.port.switchUuid != pg_obj.config.distributedVirtualSwitch.uuid ):
AttributeError: 'vim.vm.device.VirtualEthernetCard.NetworkBackingIn' object has no attribute 'port'

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_yfXPli/ansible_module_vmware_guest.py\", line 1332, in <module>\n    main()\n  File \"/tmp/ansible_yfXPli/ansible_module_vmware_guest.py\", line 1321, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_yfXPli/ansible_module_vmware_guest.py\", line 1070, in deploy_vm\n    self.configure_network(vm_obj=vm_obj)\n  File \"/tmp/ansible_yfXPli/ansible_module_vmware_guest.py\", line 674, in configure_network\n    if nic.device.backing and ( nic.device.backing.port.portgroupKey != pg_obj.key or nic.device.backing.port.switchUuid != pg_obj.config.distributedVirtualSwitch.uuid ):\nAttributeError: 'vim.vm.device.VirtualEthernetCard.NetworkBackingIn' object has no attribute 'port'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

##### STEPS TO REPRODUCE

```yaml
# Create a VM from a template

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
  - name: create the VM
    vmware_guest:
      hostname: 192.168.xxx.xxx
      username: xxxxxxxxxxxxxxxxx
      password: xxxxxxxxxxxxxxxxx
      validate_certs: no
      esxi_hostname: 192.168.xxx.xxx
      datacenter: DATACENTER
      folder: /TEST/
      name: ANSIBLE-TESTVM
      state: poweredoff
      hardware:
        memory_mb: 512
        num_cpus: 1
        scsi: paravirtual
      disk:
    - size_kb: 279552
          type: thin
          datastore: datastore1
        - size_gb: 10
          type: thin
          datastore: datastore1
      networks:
      - name: "DPG-Lan"
        ip: 192.168.xxxx.xxx
        netmask: 255.255.255.0
        gateway: 192.168.xxx.xxx
      - name: "DPG-Cluster"
        ip: 192.168.xxx.xxx
        netmask: 255.255.255.0
      - name: "DPG-iSCSI1"
        ip: 192.168.xxx.xxx
        netmask: 255.255.255.0
      - name: "DPG-iSCSI2"
        ip: 192.168.xxx.xxx
        netmask: 255.255.255.0
      template: Template_CentOS_7_x86_64
      wait_for_ip_address: yes
    register: deploy
  - debug: var=deploy
```

##### ACTUAL RESULTS

```

```
