### ISSUE TITLE
vmware_vswitch doesn't specify host

### ISSUE THREAD

**Issue by silid** [ansible/ansible#24647]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_vswitch

##### ANSIBLE VERSION
```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS

##### SUMMARY
I'd expect that when running the vmware_vswitch module it would apply the vswitch to the host that the playbook was run against, however it doesn't seem to specify a host at all, and consequently seems to apply the playbook to the wrong host via the vsphere.

##### STEPS TO REPRODUCE

```yaml
---
- name: vmware-switch-deploy
  hosts: all
  gather_facts: no
 
  tasks:
  - name: Add a VMware vSwitch
    local_action:
      module: vmware_vswitch
      hostname: "{{ lookup('env', 'VMWARE_HOST') }}"
      username: "{{ lookup('env', 'VMWARE_USER') }}"
      password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
      switch_name: vSwitch3
      number_of_ports: 2
      state: present
      nic_name: vmnic9
      mtu: 9000
      validate_certs: false
```

##### EXPECTED RESULTS
I expected the vSwitch to be added to the host the playbook was run against via the vSphere specified in hostname.

##### ACTUAL RESULTS
vSphere showed an attempt to add a switch to a different esxi host and it failed with the error: A general system error occurred: Invalid fault

```
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_vswitch.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1494926688.54-221130794998158 `" && echo ansible-tmp-1494926688.54-221130794998158="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1494926688.54-221130794998158 `" ) && sleep 0'
<localhost> PUT /tmp/tmpJ0Msse TO /var/lib/awx/.ansible/tmp/ansible-tmp-1494926688.54-221130794998158/vmware_vswitch.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1494926688.54-221130794998158/ /var/lib/awx/.ansible/tmp/ansible-tmp-1494926688.54-221130794998158/vmware_vswitch.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1494926688.54-221130794998158/vmware_vswitch.py; rm -rf "/var/lib/awx/.ansible/tmp/ansible-tmp-1494926688.54-221130794998158/" > /dev/null 2>&1 && sleep 0'
fatal: [esxi.example.com -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "hostname": "vcenter.example.com", 
            "mtu": 9000, 
            "nic_name": "vmnic9", 
            "number_of_ports": 2, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "switch_name": "vSwitch3", 
            "username": "example-admin", 
            "validate_certs": false
        }
    }, 
    "msg": "A general system error occurred: Invalid fault"
}
```
