### ISSUE TITLE
know_hosts hash_host parameter ignored

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#24651]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
known_hosts module

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /Users/jddupas/Projects/python/playbooks/app/ansible.cfg
  configured module search path = ['/Users/jddupas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jddupas/Projects/python/playbooks/env/lib/python3.5/site-packages/ansible
  executable location = /Users/jddupas/Projects/python/playbooks/env/bin/ansible
  python version = 3.5.3 (default, Apr 23 2017, 18:09:27) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
Nothing relevant

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When passing the `hash_host` parameter to the known_hosts module, it ignore it and generate unhashed entry as follow:

```yaml
- known_hosts:
      name: "hostname"
      key: "hostname ecdsa-sha2-nistp256 {{ ssh_host_key_ecdsa_public }}"
      hash_host: yes
```

```
<hostname> ecdsa-sha2-nistp256 <privkey>
```

instead of 

```
|1|<host_hash> ecdsa-sha2-nistp256 <privkey>
```

##### STEPS TO REPRODUCE

```yaml
- known_hosts:
      name: "hostname"
      key: "hostname ecdsa-sha2-nistp256 {{ ssh_host_key_ecdsa_public }}"
      hash_host: yes
```

##### EXPECTED RESULTS
The generated entry should use hashed hostname.

##### ACTUAL RESULTS

The generated entry is not hashed.
