### ISSUE TITLE
FAILED! => {"changed": false, "failed": true, "msg": "Unable to gather facts for non-existing VM websrvtst-01"}

### ISSUE THREAD

**Issue by nevertryneverfail** [ansible/ansible#24691]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

vmware_guest_facts

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### OS / ENVIRONMENT

CentOS release 6.9 (Final)

##### SUMMARY

Cannot gather facts on a VM Guest -- nor does the snapshot module work.

##### STEPS TO REPRODUCE

[meuser@it-ansibleserver-01]$ ansible-playbook -i ./snapping_inventory  -e "serverpool=webservers" ./gather_facts.yml

PLAY [Patching Servers] **********************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************
ok: [websrvtst-01]

TASK [Gather VM facts] ***********************************************************************************************************************************
fatal: [websrvtst-01 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to gather facts for non-existing VM it-websrvtst-01"}
	to retry, use: --limit @/var/ansibleConfigs/rebuild/gather_facts.retry

PLAY RECAP ***********************************************************************************************************************************************
websrvtst-01            : ok=1    changed=0    unreachable=0    failed=1
-->

```yaml
---
- name: Patching Servers
  hosts: "{{ serverpool }}"
  become: yes
  become_user: root
  become_method: sudo
  serial: 1


  vars_files:
    - ~/.ansible_creds


  tasks:
      - name: Gather VM facts
        vmware_guest_facts:
          hostname: "vcenter01.exxxxxx.xxx.xxx"
          username: 'XXXXXXXX\{{ ansible_env.SUDO_USER }}'
          password: '{{ vsphere_password }}'
          datacenter: "XXXXXXX Datacenter"
          validate_certs: False
          name: '{{ ansible_hostname }}'
        delegate_to: localhost
        register: facts

```

##### EXPECTED RESULTS

Facts gathered...

##### ACTUAL RESULTS

TASK [Gather VM facts] ***********************************************************************************************************************************
task path: /var/ansibleConfigs/rebuild/gather_facts.yml:15
Using module file /usr/lib/python2.6/site-packages/ansible/modules/cloud/vmware/vmware_guest_facts.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: USERXXXX
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/XXXXX/XXXXX/.ansible/tmp/ansible-tmp-1494964896.82-201964064941127 `" && echo ansible-tmp-1494964896.82-201964064941127="` echo /home/XXXXXXX/USERXXXX/.ansible/tmp/ansible-tmp-1494964896.82-201964064941127 `" ) && sleep 0'
<localhost> PUT /tmp/tmpHST0Cf TO /home/XXXXXXX/USERXXXX/.ansible/tmp/ansible-tmp-1494964896.82-201964064941127/vmware_guest_facts.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/XXXXXXX/USERXXXX/.ansible/tmp/ansible-tmp-1494964896.82-201964064941127/ /home/XXXXXXX/USERXXXX/.ansible/tmp/ansible-tmp-1494964896.82-201964064941127/vmware_guest_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-vduebpxpwtfnfesaokglkjesujuretre; /usr/bin/python2.6 /home/XXXXXXX/USERXXXX/.ansible/tmp/ansible-tmp-1494964896.82-201964064941127/vmware_guest_facts.py; rm -rf "/home/XXXXXXX/USERXXXX/.ansible/tmp/ansible-tmp-1494964896.82-201964064941127/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [websrvtst-01 -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "datacenter": “XXXXXX Datacenter",
            "folder": "/vm",
            "hostname": "vcenter01.XXXXXXX.XXX.XXX”,
            "name": "websrvtst-01",
            "name_match": "first",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "XXXXXXX\\USERXXXX",
            "uuid": null,
            "validate_certs": false
        }
    },
    "msg": "Unable to gather facts for non-existing VM websrvtst-01"
}
	to retry, use: --limit @/var/ansibleConfigs/rebuild/gather_facts.retry

PLAY RECAP ***********************************************************************************************************************************************
websrvtst-01            : ok=1    changed=0    unreachable=0    failed=1

```

```
