### ISSUE TITLE
pause in loop_control not working with templating

### ISSUE THREAD

**Issue by hyperized** [ansible/ansible#24719]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
loop_control -> pause

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### SUMMARY
When using pause inside loop_control, it won't accept my float-casted variable.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  vars:
    my_var: 20
    something: true
    my_items:
      - hello
      - world
  tasks:
    - block:
        - debug:
            var: my_var
        - debug:
            msg: "Hurray! {{ outer_item }}"
          with_items:
            - "{{ my_items }}"
          loop_control:
            loop_var: outer_item
            pause: my_var | float
```

Also tried variants like:
```
pause: my_var
pause: "{{ my_var | float }}"
pause: my_var | int
pause: "{{ my_var | int }}"
```

To no avail, the error remains the same.

##### EXPECTED RESULTS
I expect a pause of `my_var` seconds.

##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "my_var": 20
}

TASK [debug] *******************************************************************
ok: [localhost] => (item=hello) => {
    "msg": "Hurray! hello",
    "outer_item": "hello"
}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: a float is required
fatal: [localhost]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1
```
