### ISSUE TITLE
vmware_guest - deploy from template - can't see new VM in inventory

### ISSUE THREAD

**Issue by mvrk69** [ansible/ansible#24729]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### OS / ENVIRONMENT
Running from: Fedora 25 (x86_64)
Managing: VMware vSphere 6 with distributed vswitch
ESXi: 6.0.0 build-4192238
vCenter: VMware vCenter Server Appliance 6.0.0.20000

##### SUMMARY
After deploying a new VM from template using ansible playbook, the new VM isn't visible in inventory.

![image](https://cloud.githubusercontent.com/assets/3237472/26158374/f38dc06a-3b1b-11e7-94c2-bfd8c9e08d06.png)

I can only find the new VM using search :

![image](https://cloud.githubusercontent.com/assets/3237472/26158411/1222e76c-3b1c-11e7-8725-3a648cec4cbd.png)

##### STEPS TO REPRODUCE
```yaml
# Create a VM from a template

- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
  - name: create the VM
    vmware_guest:
      hostname: 192.168.xxx.xxx
      username: xxxxxxxxxxxxxxxxx
      password: xxxxxxxxxxxxxxxxx
      validate_certs: no
      esxi_hostname: 192.168.xxx.xxx
      datacenter: AZAR-DATACENTER
      folder: /TEST/
      name: ANSIBLE-TESTVM
      state: poweredoff
      hardware:
        memory_mb: 512
        num_cpus: 1
        scsi: paravirtual
      disk:
    - size_kb: 279552
          type: thin
          datastore: datastore1
        - size_gb: 10
          type: thin
          datastore: datastore1
      networks:
      - name: "DPG-Lan"
        ip: 192.168.xxxx.xxx
        netmask: 255.255.255.0
        gateway: 192.168.xxx.xxx
      - name: "DPG-Cluster"
        ip: 192.168.xxx.xxx
        netmask: 255.255.255.0
      - name: "DPG-iSCSI1"
        ip: 192.168.xxx.xxx
        netmask: 255.255.255.0
      - name: "DPG-iSCSI2"
        ip: 192.168.xxx.xxx
        netmask: 255.255.255.0
      template: Template_CentOS_7_x86_64
      wait_for_ip_address: yes
    register: deploy
  - debug: var=deploy
```
