### ISSUE TITLE
Replacement not working correctly when iterating through hosts in a group under a restricted range of hosts

### ISSUE THREAD

**Issue by robparrott** [ansible/ansible#2473]
Seeing a funky issue when iterating through hosts in a group where only one is resolved, while the others end up with a failed replacement. Play and output to follow. All runs locally.

Note that this group "gluster_nodes" is created dynamically in the playbook via "add_host" module. It has three host entries that are instances in EC2.

Play looks like this:

```
- hosts: gluster_nodes[0:0]
  vars_files: 
  - iaas/vars/ec2-vars.yaml
  - gluster/vars/gluster-vars.yaml 
  user: '${remote_user}'
  sudo: True
  gather_facts: True

  tasks:

  # List hosts
  - name: list out all the hosts in the group
    action: debug  msg="gluster_nodes = ${groups.gluster_nodes}"
    tags: gluster_volume

  # Test the substitution
  - name: test the substitution
    action: debug  msg="IP address = ${hostvars.{$item}.ansible_eth0.ipv4.address}"
    with_items: ${groups.gluster_nodes}  
    tags: gluster_volume
```

The output is as follows (formatted to be easier to read):

```
PLAY [gluster_nodes[0:0]] ********************* 

GATHERING FACTS ********************* 
ok: [ec2-54-234-255-179.compute-1.amazonaws.com]

TASK: [list out all the hosts in the group] ********************* 
ok: [ec2-54-234-255-179.compute-1.amazonaws.com] => 
  {
    "item": "", 
    "msg": "gluster_nodes = ec2-54-234-255-179.compute-1.amazonaws.com,
                                        ec2-54-234-86-163.compute-1.amazonaws.com,
                                        ec2-54-235-16-246.compute-1.amazonaws.com"
  }

TASK: [test the substitution] ********************* 
ok: [ec2-54-234-255-179.compute-1.amazonaws.com] => 
      (item=ec2-54-234-255-179.compute-1.amazonaws.com) => 
       {
           "item": "ec2-54-234-255-179.compute-1.amazonaws.com", 
           "msg": "IP address = 10.165.7.163"
      }
ok: [ec2-54-234-255-179.compute-1.amazonaws.com] => 
       (item=ec2-54-234-86-163.compute-1.amazonaws.com) => 
       {
         "item": "ec2-54-234-86-163.compute-1.amazonaws.com", 
         "msg": "IP address = ${hostvars.{$item}.ansible_eth0.ipv4.address}"
       }
ok: [ec2-54-234-255-179.compute-1.amazonaws.com] => 
      (item=ec2-54-235-16-246.compute-1.amazonaws.com) => 
      {
         "item": "ec2-54-235-16-246.compute-1.amazonaws.com", 
          "msg": "IP address = ${hostvars.{$item}.ansible_eth0.ipv4.address}"
      }
```

The upshot here is that the parser only seems to be able to access hosts over which the play is acting, and not the entire set of hosts. However "group_names" resolves fine.

The end goal will be to add each host to a gluster cluster on the first host, iterating over them all.
