### ISSUE TITLE
zabbix_host: cannot set host from being monitored by a proxy to being monitored by the server

### ISSUE THREAD

**Issue by Rickkwa** [ansible/ansible#24735]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
zabbix_host

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
I think everything is default.

##### OS / ENVIRONMENT
Running ansible on Centos 7, and managing Centos 6/7.

##### SUMMARY
Suppose you have a Zabbix host that is being monitored by a proxy and you want to update it so that it is monitored by the server instead of a proxy. If run an ansible playbook using the `zabbix_host` module, and you set `force: yes` and `proxy: null`, the resulting Zabbix host will still be monitored by the proxy.

##### STEPS TO REPRODUCE
Run the following playbook.
```yaml
---
- hosts: localhost
  vars:
    zabbix_hostname: "test.example.com"
    zabbix_proxy: "my-zabbix-proxy"
  tasks:
    - name: Create Zabbix host
      zabbix_host:
        host_name: "{{ zabbix_hostname }}"
        host_groups:
          - "Linux servers"
        link_templates:
          - "Template OS Linux"
        interfaces:
          - type: 1
            main: 1
            useip: 0
            ip: ""
            dns: "{{ zabbix_hostname }}"
            port: 10050
        proxy: "{{ zabbix_proxy }}"
        force: yes
        login_user: "Admin"
        login_password: "zabbix"
        server_url: "http://myzabbixinstance.com"
```
So this successfully creates a Zabbix host that is being monitored by `my-zabbix-proxy` (as expected). 
Now, rerun the playbook after setting the variable `zabbix_proxy: null`. 

##### EXPECTED RESULTS
The expected result is that it should be monitored by `(no proxy)`, ie. the Zabbix server.

##### ACTUAL RESULTS
The Zabbix host is still being monitored by `my-zabbix-proxy`.
