### ISSUE TITLE
ec2_customer_gateway returns different values depending if CGW exists already or not

### ISSUE THREAD

**Issue by mcaulifn** [ansible/ansible#24747]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_customer_gateway

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
standard

##### OS / ENVIRONMENT
Ubuntu, AWS

##### SUMMARY
Creating CGW vs reporting on existing CGW returns different results.

##### STEPS TO REPRODUCE
Sample task:
```yaml
- name: Create Spoke Customer Gateway
  ec2_customer_gateway:
    bgp_asn: "{{ asn_spoke }}"
    ip_address: "{{ item.public_ip }}"
    name: cgw-spoke
    region: "{{ aws_region }}"
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
  with_items: "{{ eip_spoke.results }}"
  register: cgw_spoke
```

##### EXPECTED RESULTS
On the first run, a dictionary "customer_gateway" is returned. On subsequent runs, list "customer_gateway" and list "customer_gateways" are returned. This creates issues when attempting to code for create and already created scenarios.

##### ACTUAL RESULTS

Running the above task the first time returns the following result:
```
"gateway": {
                    "customer_gateway": {
                        "bgp_asn": "65000", 
                        "customer_gateway_id": "cgw-1d05de03", 
                        "ip_address": "52.27.234.211", 
                        "state": "available", 
                        "type": "ipsec.1"
                    }
}
```

Running the above task with the same information will return the following result:
```
"gateway": {
                    "customer_gateway": [
                        {
                            "bgp_asn": "65000", 
                            "customer_gateway_id": "cgw-1d05de03", 
                            "ip_address": "52.27.234.211", 
                            "state": "available", 
                            "tags": [
                                {
                                    "key": "Name", 
                                    "value": "cgw-spoke"
                                }
                            ], 
                            "type": "ipsec.1"
                        }
                    ], 
                    "customer_gateways": [
                        {
                            "bgp_asn": "65000", 
                            "customer_gateway_id": "cgw-1d05de03", 
                            "ip_address": "52.27.234.211", 
                            "state": "available", 
                            "tags": [
                                {
                                    "key": "Name", 
                                    "value": "cgw-spoke"
                                }
                            ], 
                            "type": "ipsec.1"
                        }
                    ]
}

```
