### ISSUE TITLE
eos_user getting a warning for username and password

### ISSUE THREAD

**Issue by dgarros** [ansible/ansible#24749]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/network/eos/eos_user.py

##### ANSIBLE VERSION
```
ansible 2.4.0 (fix-aos-login-port 395d4d4c5b) last updated 2017/05/09 08:59:20 (GMT -700)
  config file = /Users/damien/projects/cloudlabs-topologies/vpod-l2-xs/ansible.cfg
  configured module search path = [u'/Users/damien/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/damien/projects/ansible/lib/ansible
  executable location = /Users/damien/projects/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
Mac OS X

##### SUMMARY
When using the module `eos_user` to change the password of an existing user, I'm getting two warning messages indicating that parameters `username` and `password` are getting deprecated. 
Based on my discussion with @gundalow, it's a mistake and these 2 parameters are valid for this module

##### STEPS TO REPRODUCE
Try to change the password of a user using `eos_user`
```yaml
    - name: Change Password for User Admin
      eos_user:
        username: "admin"
        password: "{{ new_password }}"
        update_password: always
        state: present
        provider: "{{ eoscli }}"
```

##### EXPECTED RESULTS

No warning messages related to `username` and `password`

##### ACTUAL RESULTS

```
TASK [Change Password for User Admin] *******************************************************************************************
 [WARNING]: argument username has been deprecated and will be removed in a future version

 [WARNING]: argument password has been deprecated and will be removed in a future version

changed: [vrack_2_leaf]
changed: [vrack_1_leaf]
```
