### ISSUE TITLE
AWS ec2_lb module not reading ENV var credentials

### ISSUE THREAD

**Issue by marcinkubica** [ansible/ansible#24765]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ec2_lb

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/centos/aws-web-example/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
```
$ grep -v "\#" ansible.cfg |sed '/^\s*$/d'
[defaults]
inventory      = ./inv/ec2.py
roles_path    = ./roles
host_key_checking = False
[privilege_escalation]
[paramiko_connection]
[ssh_connection]
[persistent_connection]
connect_timeout = 30
connect_retries = 30
connect_interval = 1
[accelerate]
[selinux]
[colors]
[diff]
```

##### OS / ENVIRONMENT

```
$ python -m platform "platform.system()"
Linux-3.10.0-514.16.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core
```

##### SUMMARY
Using AWS credentials in env variables works for creating instances, lbs, security groups or adding ssh-keys - fine. However when hitting `ec2_lb` module it's erroring on authentication.

```
FAILED! => {"changed": false, "failed": true, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['QuerySignatureV2AuthHandler'] Check your credentials"}
```
lookup env trick from #10638 helps as a workaround.

##### STEPS TO REPRODUCE

```yaml
- name: register in LB
#become: false or true has no impact
  ec2_elb:
    state: present
    ec2_elbs: "{{ web_lb_name }}"
    region: "{{ web_region }}"
    instance_id: "{{ ec2_id }}"


```

##### EXPECTED RESULTS
`OK`

##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "failed": true, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['QuerySignatureV2AuthHandler'] Check your credentials"}
```

**Comment by lalkrishnak** [comment]
+1

**Comment by s-hertel** [comment]
I'm having a hard time reproducing this on devel. What environment variables do you have set? AWS profile? Secret/access keys?

**Comment by marcinkubica** [comment]
Hi @s-hertel thanks for trying to reproduce this on devel. After that I believe I've found it - user error :)

Module has to be run as local action if it's a part of a play run alongside dynamic inventory.

So, in a role like this:

```yml
---
- name: delete "{{ web_html_path}}"
  file:
    path: "{{ web_html_path }}"
    state: absent

- name: deploy web from "{{ web_git_url }}"
  git:
    repo: "{{ web_git_url }}"
    dest: "{{ web_html_path }}"
    version: "{{ web_code_version }}"

- name: regexp hostname (loadbalancer example)
  lineinfile:
    path: "{{ web_html_path }}/index.html"
    regexp: '^Host'
    line: 'Hostname (local): {{ ansible_hostname }}'

- name: register in LB (local action)
  tags: register-in-lb
  become: false
  local_action: ec2_elb
  args:
    state: present
    ec2_elbs: "{{ web_lb_name }}"
    region: "{{ web_region }}"
    instance_id: "{{ ec2_id }}"

- name: register in LB (normal action)
  tags: register-in-lb
  ec2_elb:
        state: present
        ec2_elbs: "{{ web_lb_name }}"
        region: "{{ web_region }}"
        instance_id: "{{ ec2_id }}"
```

Result is

```sh
PLAY [localhost] *****************************************************************************************************************************************************************************************************************

PLAY [tag_node_web] **************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************
ok: [52.70.127.165]
ok: [107.22.155.75]

TASK [deploy-web : register in LB (local action)] ********************************************************************************************************************************************************************************
ok: [52.70.127.165 -> localhost]
ok: [107.22.155.75 -> localhost]

TASK [deploy-web : register in LB (normal action)] *******************************************************************************************************************************************************************************
fatal: [107.22.155.75]: FAILED! => {"changed": false, "failed": true, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['QuerySignatureV2AuthHandler'] Check your credentials"}
fatal: [52.70.127.165]: FAILED! => {"changed": false, "failed": true, "msg": "No handler was ready to authenticate. 1 handlers were checked. ['QuerySignatureV2AuthHandler'] Check your credentials"}
        to retry, use: --limit @/home/centos/aws-web-example/site-create.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************
107.22.155.75              : ok=2    changed=0    unreachable=0    failed=1
52.70.127.165              : ok=2    changed=0    unreachable=0    failed=1
```
