### ISSUE TITLE
Stat module malformed docstring?

### ISSUE THREAD

**Issue by itdependsnetworks** [ansible/ansible#24775]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

Stat module

##### ANSIBLE VERSION

```
N/A
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

In the doc string I see the return values: https://github.com/ansible/ansible/blob/a0dfa8616a8e7b00ce8c6f344ea721a387434721/lib/ansible/modules/files/stat.py#L144

however, on http://docs.ansible.com/ansible/stat_module.html I do not. My only guess is a malformed docstring? 

##### STEPS TO REPRODUCE

Go to http://docs.ansible.com/ansible/stat_module.html#return-values

##### EXPECTED RESULTS

```
        exists:
            description: if the destination path actually exists or not
            returned: success
            type: boolean
            sample: True
        path:
            description: The full path of the file/object to get the facts of
            returned: success and if path exists
            type: string
            sample: '/path/to/file'
        mode:
            description: Unix permissions of the file in octal
            returned: success, path exists and user can read stats
            type: octal
            sample: 1755
```
##### ACTUAL RESULTS

No table
