### ISSUE TITLE
syntax problem

### ISSUE THREAD

**Issue by hkyyx** [ansible/ansible#24771]
ansible 2.2.0
my playbook as blew, and ansible say syntax error
```
- name: "checking file owner and group"
    stat: path= "/dev/{{item.0.device_name}}{{item.1.index}}"
    register: part
    fail: msg= "chown owner or group failed"
    when: part.stat.pw_name != 'root' or part.stat.gr_name != 'disk'
    # failed_when: part.stat.pw_name != 'root' or part.stat.gr_name != 'disk'
    with_subelements:
    - "{{ devices }}"
    - partitions
```

error log
```
The error appears to have been in 'partition.yml': line 51, column 5, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


  - name: "checking file owner and group"
    ^ here
```

if I use failed_when,  the playbook success
```
- name: checking owner and group
    stat:
      path: "/dev/{{item.0.device_name}}{{item.1.index}}"
    register: part
    failed_when: part.stat.pw_name != 'root' or part.stat.gr_name != 'disk'
    with_subelements:
    - "{{ devices }}"
    - partitions
```
