### ISSUE TITLE
ansible and ansible-playbook inconsistent

### ISSUE THREAD

**Issue by maxamillion** [ansible/ansible#2478]
Using the playbook here: https://github.com/maxamillion/ansible-openshift_origin/blob/f8598ae52068a419e71353a2a3e3ca0edae5dc74/broker.yml (relevant parts pasted here for convenience)

```
- name: MongoDB
  hosts: brokers
  user: root
  vars_files:
    - varfiles/origin_vars.yml
  tasks:
    # MongoDB Install and configure 
    #   This could be broken out into it's own playbook to allow for some
    #   fancy orchestration and replication set configuration but for now 
    #   we will keep this simple.
    - name: Install MongoDB
      yum: pkg=mongodb state=latest
    - name: Install MongoDB Server
      yum: pkg=mongodb-server state=latest
    - name: Ensure MongoDB daemon stopped
      service: name=mongod state=stopped
    - name: Configure MongoDB
      template: src=templates/mongodb/mongodb.conf.j2
                dest=/etc/mongodb.conf backup=yes
    - name: Start and Enable MongoDB daemon
      service: name=mongod state=started enabled=yes
    - name: Check for mongo auth
      command: ${egrep} '^auth = true' /etc/mongodb.conf
      ignore_errors: yes 
      register: e_nocheckmongoauth
    - name: MongoDB user/pw script template copy
      template: src=templates/mongodb/set_mongopw.sh.j2
                dest=/root/00-set_mongopw.sh
                owner=root group=root mode=0500
      only_if: ${e_nocheckmongoauth.rc} != 0
    - name: Run MongoDB user/pw script 
      action: raw /root/00-set_mongopw.sh
      only_if: ${e_nocheckmongoauth.rc} != 0
    - name: Clean up after MongoDB user/pw script
      file: path=/root/00-set_mongopw.sh state=absent
    - name: Enable mongo auth
      shell: printf "auth = true\n" >> /etc/mongodb.conf
      only_if: ${e_nocheckmongoauth.rc} != 0
  tags:
    - mongo
```

The file /etc/ansiblehosts with the following:

```
[brokers]
10.4.59.155 

[nodes]
10.4.59.155
```

When I run the following command, I get a failure on the egrep section (snippet posted below):

```
$ ansible-playbook -vvv broker.yml -i /tmp/ansiblehosts -t mongo
TASK: [Check for mongo auth] ********************* 
<10.4.59.155> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.4.59.155
<10.4.59.155> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1363894887.09-149776753170068 && echo
 $HOME/.ansible/tmp/ansible-1363894887.09-149776753170068'
<10.4.59.155> REMOTE_MODULE command /usr/bin/egrep '^auth = true' /etc/mongodb.conf
<10.4.59.155> PUT /tmp/tmpJZkyeX TO /root/.ansible/tmp/ansible-1363894887.09-149776753170068/command
<10.4.59.155> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1363894887.09-149776753170068/
command; rm -rf /root/.ansible/tmp/ansible-1363894887.09-149776753170068/ >/dev/null 2>&1'
failed: [10.4.59.155] => {"changed": true, "cmd": ["/usr/bin/egrep", "^auth = true", "/etc/mongodb.conf"
], "delta": "0:00:00.002620", "end": "2013-03-21 12:41:28.823348", "rc": 1, "start": "2013-03-21 12:41:2
8.820728"}
...ignoring
```

However, when run the same command with ansible and not ansible-playbook, it succeeds:

```
$ ansible brokers -i /tmp/ansiblehosts -m command -a "/usr/bin/egrep '^auth = true' /etc/mongodb.conf" -
u root
10.4.59.155 | success | rc=0 >>
auth = true
```

Running ansible 1.0 on Fedora 18 from the Fedora repos: ansible-1.0-1.fc18.noarch

If there is more information I can provide, please let me know.

**Comment by mpdehaan** [comment]
Did you figure out why it was returning differently?

**Comment by bennojoy** [comment]
Adam,

Can you try shell instead of command, and let us know how that goes.

Benno

**Comment by maxamillion** [comment]
Shell errors the same way as Command:

```
TASK: [Check for mongo auth] ********************* 
<10.4.59.155> ESTABLISH CONNECTION FOR USER: root on PORT 22 TO 10.4.59.155
<10.4.59.155> EXEC /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-1363965400.72-69233016462274 && echo 
$HOME/.ansible/tmp/ansible-1363965400.72-69233016462274'
<10.4.59.155> REMOTE_MODULE command /usr/bin/egrep '^auth = true' /etc/mongodb.conf #USE_SHELL
<10.4.59.155> PUT /tmp/tmpn7f6Yx TO /root/.ansible/tmp/ansible-1363965400.72-69233016462274/command
<10.4.59.155> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-1363965400.72-69233016462274/c
ommand; rm -rf /root/.ansible/tmp/ansible-1363965400.72-69233016462274/ >/dev/null 2>&1'
failed: [10.4.59.155] => {"changed": true, "cmd": "/usr/bin/egrep '^auth = true' /etc/mongodb.conf ", "d
elta": "0:00:00.005444", "end": "2013-03-22 08:16:42.668725", "rc": 1, "start": "2013-03-22 08:16:42.663
281"}
...ignoring
```

ansible vs. ansible-playbook still succeeds though:

```
$ ansible brokers -i /tmp/ansiblehosts -m shell -a "/usr/bin/egrep '^auth = true' /etc/mongodb.conf" -u root
10.4.59.155 | success | rc=0 >>
auth = true
```

**Comment by mpdehaan** [comment]
Ok, so no to my question then :)

**Comment by mpdehaan** [comment]
Can you show me where ${egrep} is defined?

**Comment by maxamillion** [comment]
https://github.com/maxamillion/ansible-openshift_origin/blob/master/varfiles/origin_vars.yml

I also ran this without the var, just running the command with full path at the suggestion/recommendation of skvildal and got the same result. Also quoted the entire command in a string, same result.

**Comment by mpdehaan** [comment]
Ok, thanks, I'll test and look into this.

**Comment by mpdehaan** [comment]
I assume you are ok if you don't define the egrep as a variable?

**Comment by mpdehaan** [comment]
hey @maxamillion I just tested this with the following playbook:

```
---
- hosts: all
  vars_files:
    - /tmp/vars.yml
  tasks:
    - action: shell ${egrep} '^auth = true' /etc/mongodb.conf
    - action: command ${egrep} '^auth = true' /etc/mongodb.conf
    - command: ${egrep} '^auth = true' /etc/mongodb.conf
    - shell: ${egrep} '^auth = true' /etc/mongodb.conf
```

And all of those are working for me.

Looking at your -v -v -v output the shlex also looks correct to me.  Is it possible the mongo file contents had changed between the first run and the second test?

Here is my variables file:

```
---
egrep: /bin/egrep
```

This was on CentOS 6.3, but really shouldn't matter.

It just seems from the output the only thing different is the command returning differently.

Any thoughts?
