### ISSUE TITLE
unarchive remote source from http URL fails

### ISSUE THREAD

**Issue by pvdputte** [ansible/ansible#24780]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
unarchive

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel 5741712a09) last updated 2017/05/18 16:08:41 (GMT +200)
  config file = 
  configured module search path = [u'/home/pvdputte/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pvdputte/VC/vendor/ansible-master/lib/ansible
  executable location = /home/pvdputte/VC/vendor/ansible-master/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

```

##### OS / ENVIRONMENT

Ubuntu 14.04 'Trusty', managing Debian 7.0 'Wheezy'

##### SUMMARY
unarchive in current master won't work with remote files anymore. Simply copying lib/ansible/plugins/action/unarchive.py and lib/ansible/modules/files/unarchive.py from ansible 2.3 makes it work again.

Perhaps also check out https://github.com/ansible/ansible/issues/17009

##### STEPS TO REPRODUCE

```yaml
- name: "install AWStats"
  unarchive:
    remote_src: "yes"
    src:        "http://netix.dl.sourceforge.net/project/awstats/AWStats/7.5/awstats-7.5.tar.gz"
    dest:       "/tmp"
    owner:      "root"
    group:      "root"
    keep_newer: "yes"
    creates:    "/tmp/awstats-7.5"
```

##### EXPECTED RESULTS
It is expected that the file will be properly downloaded and extracted to the destination directory.

##### ACTUAL RESULTS
```
TASK [hclwrk-init : install AWStats] *******************************************
fatal: [com-dhclwrk001.srv.combell-ops.net]: FAILED! => {"changed": false, "failed": true, "msg": "Source 'http://netix.dl.sourceforge.net/project/awstats/AWStats/7.5/awstats-7.5.tar.gz' failed to transfer"}
```

```

```
