### ISSUE TITLE
include_role does not work with, with_items for executing multiple roles parallely

### ISSUE THREAD

**Issue by udyshnkr** [ansible/ansible#24792]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

include_role
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel c1397626fc) last updated 2017/05/18 13:07:37 (GMT -700)
  config file = /Users/XXX/ansible/ansible.cfg
  configured module search path = [u'/Users/XXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/XXX/ansible/ansible-devel/lib/ansible
  executable location = /Users/XXX/ansible/ansible-devel/bin/ansible
  python version = 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### OS / ENVIRONMENT

Mac OS Sierra version 10.12.5
##### SUMMARY

I have a role with task to call multiple roles using include_role and with_items, wanted to use loop to call multiple roles so that my tasks in nested roles can be executed in parallel.

##### STEPS TO REPRODUCE

```
# role/ServiceDeploy/tasks/main.yml
- name: Initiating SERVICE Deployment
  include_role:
    name: '{{item}}'
  with_items:
     - "{{ SERVICE_DEPLOY_LIST }}"


# Defaults/main.yml
SERVICE_DEPLOY_LIST:
  - 'MicroService1'
  - 'MicroService2'
  - 'MicroService3'
  - 'MicroService4'
  - 'MicroService5'
 
```
Note: Each item in the SERVICE_DEPLOY_LIST is actually a role that inturn call my core role which has deployment logic.

##### EXPECTED RESULTS

I should be able to call multiple roles, using include_role and with_items.

##### ACTUAL RESULTS

It does not call Nested Roles
playbook: deploy.yml

  play #1 (all): Service Deployment	TAGS: []
    tasks:
      ServiceDeploy : Initiating Service Deployment	TAGS: [ServiceDeploy]

```

```
