### ISSUE TITLE
ec2 rds postgres creation fails with error: Failed to create instance: null

### ISSUE THREAD

**Issue by jmcginn13** [ansible/ansible#24802]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
rds module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/jmcginn/workspaces/askrail-infrastructure/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
[defaults]
inventory = inventory

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=30m -F ./.ssh_config
control_path = ~/.ssh/ansible-%%r@%%h:%%p

Plus standard AWS environment variables for credentials

##### OS / ENVIRONMENT
Centos 7
Linux version 3.10.0-514.16.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Apr 12 15:04:24 UTC 2017

##### SUMMARY
Automating creation of environment in AWS - trying to create postgres database after creating vpc, subnets, security groups, gateways, route tables, ec2 instances, etc.

##### STEPS TO REPRODUCE
Using ec2.py for dynamic inventory
Set ec2.ini to use private IP & DNS
destination_variable = private_dns_name
vpc_destination_variable = private_ip_address

Main playbook that invokes roles (following plays omitted)
```yaml
---
- name: Test region network configuration and bastion instance creation
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    vpc_name: "railinc-aws-test-vpc"
    vpc_cidr_block: "172.35.0.0/16"
    env: "test"
    bastion_hosts_to_proxy: "172.35.*.*"
    public_subnets: 
      - cidr: "172.35.0.0/22"
        az: "us-east-1a"
      - cidr: "172.35.4.0/22"
        az: "us-east-1b"
    private_subnets:
      - cidr: "172.35.16.0/22"
        az: "us-east-1a"
      - cidr: "172.35.32.0/22"
        az: "us-east-1b"
  roles:
    - vpc
    - askrail-infrastructure
```
role defaults for askrail-infrastructure
```yaml
---
# Global default settings
region:                   "us-east-1"

# askrail server instance defaults
askrail_instances_per_az:        1
askrail_server_ami:              "ami-6d1c2007" 
askrail_server_instance_type:    "t2.micro"
askrail_server_key_pair:         "{{ my_key_pair }}"

# askrail server instance volume specs /dev/sda1
askrail_default_volume_type:     "gp2"
askrail_default_volume_size:     8
askrail_default_volume_delete_on_term: yes

# askrail database defaults
database_port:                   5432
database_engine_version:         "9.6.1"
database_instance_class:         "db.t2.small"
database_size:                   20
database_multizone:              no
database_backup_retention_days:  7
database_availability_zone:      "us-east-1a"
```
task for creating rds postgres instance (verified all dependent resources exist - vpc, subnets, db subnet group, security groups). I have played around with different values for engine version and also took the value out completely since the docs are unclear what value should be used.
```yaml
- name:                   "Create askrail database"
  rds:
    command:              "create"
    region:               "{{ region }}"
    instance_name:        "askrail-{{ env }}-db"
    instance_type:        "{{ database_instance_class }}"
    subnet:               "railinc-aws-{{ env }}-db-subnet-grp-01"
    zone:                 "{{ database_availability_zone }}"
    port:                 "{{ database_port }} "
    db_engine:            postgres
    size:                 "{{ database_size }}"
    db_name:              "askrail"
    username:             "railinc"
    password:             "xxxxxxxxxxx"
    license_model:        postgresql-license
    multi_zone:           "{{ database_multizone }}"
    backup_retention:     "{{ database_backup_retention_days }}"
    upgrade:              yes 
    vpc_security_groups:  "{{ postgres_railinc_sec_grp.group_id }}"
    wait:                 yes
```
##### EXPECTED RESULTS
postgres instance to be created and running

##### ACTUAL RESULTS
```
Error results
```
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/amazon/rds.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jmcginn
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jmcginn/.ansible/tmp/ansible-tmp-1495153256.36-108353162371443 `" && echo ansible-tmp-1495153256.36-108353162371443="` echo /home/jmcginn/.ansible/tmp/ansible-tmp-1495153256.36-108353162371443 `" ) && sleep 0'                                                                                                             
<127.0.0.1> PUT /tmp/tmpz0LtYq TO /home/jmcginn/.ansible/tmp/ansible-tmp-1495153256.36-108353162371443/rds.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jmcginn/.ansible/tmp/ansible-tmp-1495153256.36-108353162371443/ /home/jmcginn/.ansible/tmp/ansible-tmp-1495153256.36-108353162371443/rds.py && sleep 0'                                                            
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/jmcginn/.ansible/tmp/ansible-tmp-1495153256.36-108353162371443/rds.py; rm -rf "/home/jmcginn/.ansible/tmp/ansible-tmp-1495153256.36-108353162371443/" > /dev/null 2>&1 && sleep 0'                          
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "apply_immediately": false, 
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "backup_retention": "7", 
            "backup_window": null, 
            "character_set_name": null, 
            "command": "create", 
            "db_engine": "postgres", 
            "db_name": "askrail", 
            "ec2_url": null, 
            "engine_version": null, 
            "force_failover": false, 
            "instance_name": "askrail-test-db", 
            "instance_type": "db.t2.small", 
            "iops": null, 
            "license_model": "postgresql-license", 
            "maint_window": null, 
            "multi_zone": false, 
            "new_instance_name": null, 
            "option_group": null, 
            "parameter_group": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": "5432 ", 
            "profile": null, 
            "publicly_accessible": null, 
            "region": "us-east-1", 
            "security_groups": null, 
            "security_token": null, 
            "size": "20", 
            "snapshot": null, 
            "source_instance": null, 
            "subnet": "railinc-aws-test-db-subnet-grp-01", 
            "tags": null, 
            "upgrade": true, 
            "username": "railinc", 
            "validate_certs": true, 
            "vpc_security_groups": [
                "sg-322c6a4c"
            ], 
            "wait": true, 
            "wait_timeout": 300, 
            "zone": "us-east-1a"
        }
    }, 
    "msg": "Failed to create instance: null"

```

```
