### ISSUE TITLE
Excessive memory usage when using "large" with_* loops with a "large" number of hosts.

### ISSUE THREAD

**Issue by szynaka** [ansible/ansible#24833]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core - Loops

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 53baa36a8b) last updated 2017/05/18 16:33:37 (GMT -400)
  config file = /home/szynaka/src/mass_files/ansible.cfg
  configured module search path = [u'/home/szynaka/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/szynaka/src/ansible_upstream/lib/ansible
  executable location = /home/szynaka/src/ansible_upstream/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
ansible.cfg:
```
[defaults]
nocows=1
hash_behaviour=merge
remote_tmp = $HOME/.ansible/tmp
```

##### OS / ENVIRONMENT
N/A
Tested on Linux (Debian) and MacOS

##### SUMMARY
Excessive memory usage when using "large" with_* loops with a "large" number of hosts.
20-30 loop items on 5 hosts seems to typically be enough to trigger the excessive ram usage
Setting ```gather_facts: no``` or ```serial:``` to a low number helps but larger loops can still trigger the issue.
Setting any ```loop_control:``` setting makes the problem significantly worse.
Setting different versions of ```forks``` does not appear to make any difference.

We originally ran into this issue when trying to distribute about 30 template files to a directory on about 60 hosts.  The module used doesn't seem to matter, nor does the with_ loop function.  We've tested with file, template, copy, and debug tasks, and with_fileglob, with_items, and with_sequence loops.

##### STEPS TO REPRODUCE
Simlified template playbook:
```yaml
---
- name: mass file placement
  hosts: all
  become: no
  tasks:
    - name: Create the tmp directory
      file:
        path: "/tmp/mass_file/{{ ansible_host }}"
        state: directory

    - name: Install files
      template:
        src: "{{ filename }}"
        dest: "/tmp/mass_file/{{ ansible_host }}/{{ filename | basename | regex_replace('.j2$', '') }}" # get just the filename and strip off the .j2 suffix
      with_fileglob: "../files/*"
      loop_control:
        loop_var: filename
        label: "{{ filename | basename }}" # get print the filename
      register: install_files_task
```
Other playbooks we've tested with can be found at https://github.com/szynaka/ansible_large_loops

##### EXPECTED RESULTS
https://gist.github.com/szynaka/b18b598dae5bd198ffe87296016fcf6b

##### ACTUAL RESULTS
```
$ time timeout -s 2 300 ansible-playbook -i hosts plays/template_with_fileglob.yml

PLAY [mass file placement] ****************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************
ok: [host1]
ok: [host2]
ok: [host3]
ok: [host4]
ok: [host5]
ok: [host6]
ok: [host7]
ok: [host8]
ok: [host9]
ok: [host10]

TASK [Create the tmp directory] ***********************************************************************************************************************************************************
changed: [host1]
changed: [host2]
changed: [host3]
changed: [host4]
changed: [host5]
changed: [host6]
changed: [host7]
changed: [host8]
changed: [host9]
changed: [host10]

TASK [Install files] **********************************************************************************************************************************************************************
 [ERROR]: User interrupted execution


real    14m59.738s
user    1m23.599s
sys     1m19.375s
```
Ram usage.  Gathered during play run.
```
$ ps aux | grep [a]nsible-playbook
szynaka   7366  5.6 65.3 3040228 2644276 pts/8 Sl+  10:27   0:44 /usr/bin/python /usr/bin/ansible-playbook -i hosts plays/template_with_fileglob.yml --check
```

Long run with -vvvv:  https://gist.github.com/szynaka/94325e323851abd0e6848c925c3d8fd8
