### ISSUE TITLE
Feature Idea: New 'comment:' arg for lineinfile module

### ISSUE THREAD

**Issue by RKov** [ansible/ansible#24836]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

lineinfile

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.8 (default, Aug 10 2016, 10:26:01) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### SUMMARY

Many times I would like to add a comment to a line I am changing, creating in a file.
I can do this if I use the module twice of course, but it would be nice to have a "comment:" 
argument that would place a comment on the line before the "line:".
Support for different comments could also be added (c-style, hash, slash, etc..), even though this would complicate things I guess, esp. with already existing comments.
I use the comment_style: arg in the below example.

##### STEPS TO REPRODUCE

E.g. we would want to have the following in /tmp/somefile:
  # This is just a test line
  put a test line here

```yaml
- name: insert a line with comment 
  lineinfile: 
    path: /tmp/somefile
    line: "put a test line here"
    comment: "This is just a test line"
    comment_style: hash
```

##### ACTUAL RESULTS

```

```
