### ISSUE TITLE
`find_vm_by_id` broken for searching by UUID

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [ansible/ansible#24835]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Function `find_vm_by_id` in `module_utils/vmware.py`

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/dennis/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using one of the VMware cloud modules which internally searches a VM by UUID via `find_vm_by_id` you'll see the error `TypeError: Required field "uuid" not provided (not @optional)`.

The issue is that the internal method `find_vm_by_id` is broken when searching by UUID. It uses the the `FindByUuid` function from VMware wrongly. I propose this call instead:

    vm = si.FindByUuid(datacenter=datacenter, instanceUuid=True, vmSearch=True, uuid=vm_id) 

The documentation for this function is on:

http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.SearchIndex.html?path=7_1_0_2_5_6_10#findByUuid

Please note the usage of `instanceUuid=True` here. Only with that the search is done by the instance UUID and not the SMBIOS UUID. Which despite its name is not fully unique. Documentation about the two fields can be found on:

http://pubs.vmware.com/vsphere-60/index.jsp#com.vmware.wssdk.apiref.doc/vim.vm.ConfigInfo.html

To add to the confusion the SMBIOS UUID is return by VMware in the `uuid` field and the instance UUID in `instanceUuid`. There you'll also find the explanation that the SMBIOS UUID may be shared.

**Comment by alikins** [comment]
Have an example playbook that triggers this error? (Mostly just to see which task/module args can trigger this...)

**Comment by dennis-benzinger-hybris** [comment]
A short playbook to trigger this error is:
```yaml
---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Find by UUID
      vmware_guest_facts:
        hostname: "{{ vcenter_address }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_password }}"
        validate_certs: False

        datacenter: "{{ datacenter }}"

        name: '' # Workaround for 24398
        uuid: 1234-5678
```
