### ISSUE TITLE
cloudformation template_parameters not working

### ISSUE THREAD

**Issue by toddrosner** [ansible/ansible#24866]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudformation module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

##### CONFIGURATION
No changes to default ansible.cfg

##### OS / ENVIRONMENT
Arch Linux

##### SUMMARY
When running a playbook with the cloudformation module and specifying template_parameters, an error is thrown.

##### STEPS TO REPRODUCE
Add template_parameters section to cloudformation task like so:
```
- name: Run CloudFormation stack
      cloudformation:
        stack_name: "{{ project }}"
        region: "{{ region }}"
        state: "present"
        template: "../templates/stack.yaml"
        template_parameters:
          VpcdId: "{{ VpcId }}"
        tags:
          CostCentre: "{{ cost_centre }}"
      register: "{{ project }}"
```

##### EXPECTED RESULTS
Expect the template_parameters to be passed to the template file.

##### ACTUAL RESULTS
```
"msg": "<class 'Exception'>: An error occurred (ValidationError) when calling the CreateStack operation: Parameter values specified for a template which does not require them."
```

**Comment by ansibot** [comment]
cc @tedder @ryansb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Can you share your template? needs_info

**Comment by toddrosner** [comment]
Hi s-hertel, thanks for getting back. The template is below.

```
#jinja2:lstrip_blocks:False,trim_blocks:False
---
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: '{{ project }}-sg'
      GroupDescription: 'Allow http to client host'
      VpcId: '{{ VpcId }}'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
```

**Comment by tedder** [comment]
You need a `Parameters` section.

Leaving this ticket open so I can catch the exception.

**Comment by toddrosner** [comment]
Ah. Thanks for that tedder! Everything works with the following update:
```
#jinja2:lstrip_blocks:False,trim_blocks:False
---
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'multi-az-vpc-sg'
      GroupDescription: 'Allow http to client host'
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0
```
