### ISSUE TITLE
authorized key examples need quoting in documentation

### ISSUE THREAD

**Issue by dch** [ansible/ansible#2486]
This from http://www.ansible.cc/docs/playbooks2.html?highlight=authorized_key#lookup-plugins-accessing-outside-data doesn't work :

``` yaml
    - name: 1 enable key-based ssh access for users
      authorized_key: user=ubuntu key=$item
      with_fileglob:
        - /dropbox/keys/ssh/*.pub

```

But these ones do:

``` yaml
    - name: 2 enable key-based ssh access for users
      authorized_key: user=ubuntu key='$FILE(/keys/$item)'
      with_items:
         - akey.pub

    - name: 3 distribute valid ssh keys
      authorized_key: user=ubuntu key='$FILE(/keys/akey.pub)'

    - name: 4 enable key-based ssh access for users
      authorized_key: user=ubuntu key='$FILE(/keys/$item)'
      with_items:
         - akey.pub
         - bkey.pub

    - name: 5 enable key-based ssh access for users
      authorized_key: user=ubuntu key='$FILE($item)'
      with_fileglob:
        - /keys/*.pub
```

Currently running ansible 1.1. from devel checkout #50461a6
