### ISSUE TITLE
ec2_ami_find is slow

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#24886]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ec2_ami_find

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/tom/repos/aws-codecommit/ansible-tower/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT

OS X 10.12.4

##### SUMMARY

ec2_ami_find takes ~37 seconds to find an AMI

The deprecated ubuntu image finder returned almost instantly.

##### STEPS TO REPRODUCE

```yaml
- name: search for latest CentOS AMI
  ec2_ami_find:
    architecture: x86_64
    name: CentOS Linux 7*EBS*
    no_result_action: fail
    # CentOS AWS Marketplace account
    owner: 679593333241
    region: eu-west-1
    sort: creationDate
    sort_order: descending
    virtualization_type: hvm
  register: ebs_ami_data
```

##### EXPECTED RESULTS

Returns in 5 seconds or less

##### ACTUAL RESULTS

Took 37 seconds to return

```
Monday 22 May 2017  12:18:45 +0100 (0:00:00.041)       0:01:01.014 ************
===============================================================================
search for latest CentOS AMI ------------------------------------------- 37.49s
```
