### ISSUE TITLE
RFE: Notifying global defined handlers in a playbook

### ISSUE THREAD

**Issue by frankotron** [ansible/ansible#2488]
I'm working with a system where several machines have dependencies on each other, where one package update or service restart requires a reload on another process located on another node of machines. At first glance the delegate_to keyword seemed to be perfect. However; for every dependency listed that requires a reload on another machine node, it will reload that group of hosts in the context of the play. Currently stacking up to three reloads of the same process during the run of one playbook, all performed sequentially on the hosts (with_items $group). I have thought about writing reload_trigger files, but that seems quite ugly.

I would like to suggest a notify_(global?) keyword that can span over several plays looking for its handler. That way I could use:

```

---
- hosts: configuration_machines
  tasks:
    - name: Updating packages
      action: yum ensure=latest name=configuration_packages
      notify_global:
      - webserver reload

- hosts: webservers
  tasks:
    - name: Ensuring latest packages
      action: yum ensure=latest name=webstuff
      notify:
      - webserver reload

  handlers:
    - name: webserver reload
      action: service name=apache2 ensure=reloaded
```

But maybe there is an alternative way that I've might have missed

**Comment by mpdehaan** [comment]
I don't know what you mean by "reloads".

If you want to disable fact gathering this is "gather_facts: False" on the play.   Maybe this is what you mean by reloads?

Currently there is no handler mechanism for delegation, so just use delegate_to with when_changed, and you'll be solid.

That being said, I kind of like the idea of being able to notify a handler for all hosts, as that makes things syntactically nicer to understand in a few ways.

I'll keep this idea on file.  The trick is, of course, whether you mean to notify it for all hosts in the group or ALL hosts, so that could be a point of contention.

**Comment by frankotron** [comment]
Sorry for being unclear. I'll illustrate with a short example, built on the sample I posted before. My scenario simply boils down to the problem of executing tasks on a separate set of hosts other than the current running play.

Lets say I create a handler task that can restart apache:

```
- name: reload webservers 
  action: service name=apache2 state=reloaded
  delegate_to: $item
  with_items: ${groups.webservers}
```

This is the current way of manipulating hosts not addressed in the currently running play. If any packages are updated on either my configuration machines or my cache servers I have to reload my apache instances located on their respective "webservers" machines:

```
---
- hosts: configuration_servers
  tasks:
    - name: Updating packages, needs web servers to reload
      action: yum ensure=latest name=configuration_packages
      notify:
      - reload webservers
  handlers.
    - include handlers/webservers.yml

- hosts: cache_servers
  tasks:
    - name: Updating packages, needs web servers to reload
      action: yum ensure=latest name=cache_packages
      notify:
      - reload webservers
  handlers.
    - include handlers/webservers.yml

- hosts: webservers
  tasks:
    - name: Ensuring latest packages
      action: yum ensure=latest name=web_packages
      notify:
      - reload webservers
  handlers.
    - include handlers/webservers.yml
```

If I run this, by the time I've gotten to the play for webservers, I have restarted the apache instances two times on every machine already (If I've updated my configuration and cache packages), and if the "web_packages" are also set to be updated, I'll reload apache again a third time (all done sequentially on the hosts). However, in the third play I could ditch the delegate_to handler task and write a usual task which will reload the apache instance normally. I mean, it works, but there are quite a bit of redundant reloading going on here, which is why I thought of having global handlers or something.
