### ISSUE TITLE
vmware_guest not work with defined datastore 

### ISSUE THREAD

**Issue by daBONDi** [ansible/ansible#24887]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /opt/it-infra/ansible.cfg
  configured module search path = [u'/opt/it-infra/library']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
VMware Vsphere 6.5 Cluster
Deploy Windows Server 2016 Template with additional disks,...

##### SUMMARY
When a VM gets created from an Template and new Disks getting added on different Datastore
it place the new disks on the Same  Datastore, and not on the defined

Tryed it with 2.3 and latest devel

##### STEPS TO REPRODUCE

```yaml
- name: "Test Vsphere"
  hosts: fj-v-file1
  gather_facts: false
  vars:
    vsphere_cluster:  "{{vsphere_default_cluster}}"
    vsphere_datacenter: "{{vsphere_default_datacenter}}"
    vsphere_user: "{{vsphere_vmc1_user}}"
    vsphere_pw: "{{vsphere_vmc1_password}}"
    vsphere_host: "{{vsphere_default_vcenter}}"
    VMConfiguration:
        name: fj-v-file1
        primary_esxhost: "fj-p-vmnode1.vsphere.local"
        annotation: "Fileserver for Management and Research"
        template: "server2016core-v1"
        disk:
         # OS Disk
         - size_gb: 146
           type: thin
           datastore: "ds-lun-11-sys1"
           autoselect_datastore: false

         # Verwaltung/LMTZ File Share = 1000GB * 1,07
         - size_gb: 1070
           type: thin
           datastore: "ds-lun-25-vwfs"
           autoselect_datastore: false

         # BLT File Shares = 2000GB * 1,07
         - size_gb: 2140
           type: thin
           datastore: "ds-lun-25-vwfs"
           autoselect_datastore: false

         # JR File Shares = 2000GB * 1,07
         - size_gb: 2140
           type: thin
           datastore: "ds-lun-25-vwfs"
           autoselect_datastore: false

        hardware:
          memory_mb: 4096
        networks:
         - name: "23-VWResource"
           mac: "00:50:56:8E:35:97"

  tasks:
    - name: "Create VM"
      tags: vsphere
      delegate_to: 127.0.0.1
      vmware_guest:
        name: "{{VMConfiguration.name}}"
        annotation: "{{VMConfiguration.annotation}}"
        hostname: "{{vsphere_host}}"
        cluster: "{{vsphere_cluster}}"
        datacenter: "{{vsphere_datacenter}}"
        template: "{{VMConfiguration.template}}"
        username: "{{vsphere_user}}"
        password: "{{vsphere_pw}}"
        wait_for_ip_address: no
        validate_certs: False
        state: present
        customization:
          password: "nothing"
        disk: "{{VMConfiguration.disk}}"
        hardware: "{{VMConfiguration.hardware}}"
```

##### EXPECTED RESULTS
VM gets Created with Disks on the defined datastore

##### ACTUAL RESULTS
All Disks getting placed on the first datastore "ds-lun-11-sys1"

Looks like it ignore the defined Datastore

Datastore is there (See it in vsphere client and on the Host where the vm gets placed)

```
changed: [fj-v-file1 -> 127.0.0.1] => {
    "changed": true,
    "failed": false,
    "instance": {
        "annotation": "Fileserver for Management and Research",
        "current_snapshot": null,
        "customvalues": {},
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "10272",
        "hw_guest_full_name": null,
        "hw_guest_id": null,
        "hw_interfaces": [],
        "hw_memtotal_mb": 4096,
        "hw_name": "fj-v-file1",
        "hw_power_status": "poweredOff",
        "hw_processor_count": 2,
        "hw_product_uuid": "420ede86-9d81-067f-f0a6-3c57d48938a4",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": "Fileserver for Management and Research",
            "cluster": "vmc1",
            "customization": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "FJ",
            "disk": [
                {
                    "autoselect_datastore": false,
                    "datastore": "ds-lun-11-sys1",
                    "size_gb": 146,
                    "type": "thin"
                },
                {
                    "autoselect_datastore": false,
                    "datastore": "ds-lun-25-vwfs",
                    "size_gb": 1070,
                    "type": "thin"
                },
                {
                    "autoselect_datastore": false,
                    "datastore": "ds-lun-25-vwfs",
                    "size_gb": 2140,
                    "type": "thin"
                },
                {
                    "autoselect_datastore": false,
                    "datastore": "ds-lun-25-vwfs",
                    "size_gb": 2140,
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 4096
            },
            "hostname": "172.16.125.200",
            "is_template": false,
            "linked_clone": false,
            "name": "fj-v-file1",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "template": "server2016core-v1",
            "template_src": "server2016core-v1",
            "username": "ansible@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}
```

**Comment by ansibot** [comment]
cc @jctanner @nerzhul @dav1x
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lepiepl** [comment]
I have the same issue.
I'm not a python developer but I made a dirty hack that works for our needs. 
I assume the first disk is used to store the vmx file.

```
            # which datastore?
            if expected_disk_spec.get('datastore'):
                # TODO: This is already handled by the relocation spec,
                # but it needs to eventually be handled for all the
                # other disks defined
                #pass
                if disk_index > 0:
                    diskspec.device.backing.fileName = '[' + expected_disk_spec.get('datastore') + ']' + self.params['name'] + '/' + self.params['name'] + '.vmdk'
                    disk_modified = True
```

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@daBONDi Could please check PR #33230 and let me know if it works for you ?

**Comment by BDragonReborn** [comment]
I am having the same issue with Ansible 2.5, works but datastores are all the same

```yaml
tasks:
    - name: Deploy guest from template
      vmware_guest:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: "{{ vm_state }}"
        validate_certs: "{{ validate_certs }}"
        name: "{{ guest_name }}"
        template: "{{ template }}"
        cluster: "{{ cluster }}"
        resource_pool: "{{ resource_pool }}"
        datacenter: "{{ datacenter }}"
        annotation: "{{ vm_description }}"
        disk:
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_one_size }}"
          datastore: "{{ datastore_one }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_two_size }}"
          datastore: "{{ datastore_two }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_three_size }}"
          datastore: "{{ datastore_three }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_four_size }}" 
          datastore: "{{ datastore_four }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_five_size }}"
          datastore: "{{ datastore_five }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_six_size }}" 
          datastore: "{{ datastore_six }}"
          type: "{{ datastore_type }}" 
        - autoselect_datastore: "False"
          size_gb: "{{ datastore_seven_size }}" 
          datastore: "{{ datastore_seven }}"
          type: "{{ datastore_type }}" 
        hardware:
          memory_mb: "{{ memory_size }}"
          num_cpus: "{{ cpu_numbers }}"
          scsi: paravirtual
        networks:
        - name: "{{ network_name }}"
          ip: "{{ ip_address }}"
          netmask: "{{ netmask }}"
          gateway: "{{ default_gateway }}"
          domain: "{{ domain_name }}"
          dns_servers:
          - "{{ dns_server_one }}"
          - "{{ dns_server_two }}"
        customization:
          autologin: True
          username: "{{ local_username }}"
          password: "{{ local_password }}"
          hostname: "{{ guest_name }}"
          dns_servers:
          - "{{ dns_server_one }}"
          - "{{ dns_server_two }}"
```
