### ISSUE TITLE
Extreme Resource Usage During include_role w/ with_items

### ISSUE THREAD

**Issue by 1efty** [ansible/ansible#24891]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role w/ with_items

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
private_role_vars = yes
fact_caching = redis
retry_files_enabled = False

##### OS / ENVIRONMENT
CentOS 7.2
AWS EC2 Instance
t2.medium

##### SUMMARY
Using include_role with a with_items loop causes memory and CPU usage to skyrocket.

##### STEPS TO REPRODUCE

The loop_var looks like this (group_var):
```yaml
virtualhosts:
  - name: name
    state: enabled
    ServerName: name.org
    ssl: yes
    cert: name.crt
    internal_access_only: no
    iframes: yes
    force_https: yes
    password_protect: no
    htaccess: []
    redirect_login_cookie: no
    custom_directives: no
    varnish: yes
    logpath: /var/www/logs
    files: yes
    proxy: yes
    mobile_redirects: no
    balancers:
      - 10.121.67.151
      - 10.121.67.152
      - 10.121.67.153
    bucket: files.name.org
    request_methods:
      - GET
      - POST
      - HEAD
.
.
.
```
All the virtualhosts take up ~800 lines.

The issues occurred here (apache role):
```yaml
- include_role: >
    name=virtualhost
  with_items: "{{ virtualhosts }}"
  loop_control:
    loop_var: virtualhost
  notify: Restart Apache
  tags:
    - apache-virtualhosts

- include_role: >
    name=certificate
  with_items: "{{ virtualhosts | map(attribute='cert') | list }}"
  loop_control:
    loop_var: certificate
  notify: Restart Apache
  tags:
    - apache-certificates
``` 

##### EXPECTED RESULTS
To not use 5GB of memory for two forks. 

##### ACTUAL RESULTS
The playbook runs fine until it reaches the include_role action w\ with_items.  Then the playbook halts and CPU usage is maxed out and memory fills up dipping into about 1GB of swap space.

NOTE: This playbook is only being ran on a single host. 

NOTE: These roles are using copy (synchronize didn't help)

NOTE: These are being ran in a role that has already been included by another playbook.  

i.e:
parent role includes: apache
apache role includes: virtualhost and certificate (both in a with_items) looping through the same virtualhosts variable.
