### ISSUE TITLE
docker_container: published_ports not triggering rebuild when having less ports

### ISSUE THREAD

**Issue by wkhere** [ansible/ansible#24892]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible-playbook 2.3.1.0
  config file = /home/wkaczmarek/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Changed inventory, roles path & vault pass file.

##### OS / ENVIRONMENT

Ubuntu Server 16.04 LTS
both Ansible host and managed system

##### SUMMARY

Module does not recreate container when giving it *less* of `published_ports` than the container already has.

Note the container is recreated when ports are *added*. My expected result would be that contained is recreated also in the case when I want less ports, in general - in any case when the existing ports differs from the list of desired ports. 

##### STEPS TO REPRODUCE

First you run
```yaml
- name: Run container
  docker_container:
    published_ports:
      - "443:443"
      - "22:22"
    name: "foo"
    restart_policy: unless-stopped
    image: "{{ my_image }}"
    volumes:
    state: started
```
then you run
```yaml
- name: Run container
  docker_container:
    published_ports:
      - "443:443"
    name: "foo"
    restart_policy: unless-stopped
    image: "{{ my_image }}"
    volumes:
    state: started
```

##### EXPECTED RESULTS

I expected for the second run:
```
TASK [my-role : Run container] ***************************************************
changed: [my-host]
```
Plus of course, docker container to be rebuilt.

##### ACTUAL RESULTS

```
TASK [my-role : Run container] ***************************************************
ok: [my-host]
```
..and docker container is not rebuilt.

```

```
