### ISSUE TITLE
xattr state absent sets attribute to empty

### ISSUE THREAD

**Issue by bengerman13** [ansible/ansible#24917]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
xattr

##### ANSIBLE VERSION
git commit hash 45e4b8f97aa8adb8222e8b83584601d3e8298ba6

##### OS / ENVIRONMENT
host: Ubuntu 16.04
node: Ubuntu 16.04, Fedora 25

##### STEPS TO REPRODUCE
```yaml
- name: Set attributes
  xattr:
    path: "{{ test_file }}"
    key: user.foo
    value: bar

- name: Unset attribute
  xattr:
    path: "{{ test_file }}"
    key: user.foo
    state: absent
  register: xattr_unset_result

- name: get attributes
  xattr:
    path: "{{ test_file }}"
  register: xattr_get_after_unset_result

- name: print result
  debug: var=xattr_get_after_unset_result['xattr']
```

##### EXPECTED RESULTS
`xattr_get_after_unset_result['xattr'] == { }`
##### ACTUAL RESULTS
`xattr_get_after_unset_result['xattr'] == { "user.foo": "" }`

```
TASK [xattr : Set attributes] **************************************************
changed: [testhost] => {"changed": true, "msg": "user.foo set to bar", "xattr": {}}

TASK [xattr : Unset attribute] *************************************************
changed: [testhost] => {"changed": true, "msg": "user.foo removed", "xattr": {"user.foo": "bar"}}

TASK [xattr : get attributes] **************************************************
ok: [testhost] => {"changed": false, "msg": "returning None", "xattr": {"user.foo": ""}}

TASK [xattr : print result] ****************************************************
ok: [testhost] => {
    "xattr_get_after_unset_result['xattr']": {
        "user.foo": ""
    }
}
```
