### ISSUE TITLE
synchronize broken in 2.3

### ISSUE THREAD

**Issue by retr0h** [ansible/ansible#24910]
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

* synchronize

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May  4 2017, 15:45:50) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### OS / ENVIRONMENT

* Mac OS
* Travis CI Standard Linux

##### STEPS TO REPRODUCE

```yaml
- name: Copy binaries from archive into etcd dir
  synchronize: src="{{ etcd_download_dir }}/{{ etcd_release }}/{{ item }}"
                         dest="{{ etcd_dir }}"
                         archive=True
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - etcd
    - etcdctl
  when: not etcd_config_only|bool
```

##### EXPECTED RESULTS

Works perfectly fine against 2.2 Ansible.

```
    changed: [etcd-03-default -> etcd-03-default] => (item=etcd)
    changed: [etcd-01-default -> etcd-01-default] => (item=etcd)
    changed: [etcd-02-default -> etcd-02-default] => (item=etcd)
    changed: [etcd-03-default -> etcd-03-default] => (item=etcdctl)
    changed: [etcd-01-default -> etcd-01-default] => (item=etcdctl)
    changed: [etcd-02-default -> etcd-02-default] => (item=etcdctl)
```
##### ACTUAL RESULTS

```
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnboundLocalError: local variable 'user' referenced before assignment
    fatal: [etcd-03-default]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
```

Local Inventory:

```yaml
---
all:
  hosts:
    etcd-01-default: &id001
      ansible_connection: docker
    etcd-02-default: &id002
      ansible_connection: docker
    etcd-03-default: &id003
      ansible_connection: docker
etcd:
  hosts:
    etcd-01-default: *id001
    etcd-02-default: *id002
    etcd-03-default: *id003
ungrouped:
  vars: {}
```
