### ISSUE TITLE
azure_rm_deployment fails to deploy ACS template with "TypeError: 'ResourceGroup' object is not iterable"

### ISSUE THREAD

**Issue by minherz** [ansible/ansible#24926]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_deployment

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
$ az --version
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]

Python location '/home/medcon/lib/azure-cli/bin/python'
```

##### OS / ENVIRONMENT
OS:
```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```

##### SUMMARY
Receiving an error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'ResourceGroup' object is not iterable
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):
  File \"/tmp/ansible_0dApZ5/ansible_module_azure_rm_deployment.py\", line 665, in <module>
      main()
	    File \"/tmp/ansible_0dApZ5/ansible_module_azure_rm_deployment.py\", line 661, in main
		    AzureRMDeploymentManager()
			  File \"/tmp/ansible_0dApZ5/ansible_module_azure_rm_deployment.py\", line 443, in __init__
			  supports_check_mode=False)
			  File \"/tmp/ansible_0dApZ5/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 197, in __init__
			  File \"/tmp/ansible_0dApZ5/ansible_module_azure_rm_deployment.py\", line 454, in exec_module
			  deployment = self.deploy_template()
			  File \"/tmp/ansible_0dApZ5/ansible_module_azure_rm_deployment.py\", line 498, in deploy_template
			  self.rm_client.resource_groups.create_or_update(self.resource_group_name, params)
			  File \"/home/medcon/.local/lib/python2.7/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/resource_groups_operations.py\", line 138, in create_or_update
			      body_content = self._serialize.body(parameters, 'ResourceGroup')
				    File \"/home/medcon/.local/lib/python2.7/site-packages/msrest/serialization.py\", line 301, in body
					    data = _convert_to_datatype(data, data_type, self.dependencies)
						  File \"/home/medcon/.local/lib/python2.7/site-packages/msrest/serialization.py\", line 171, in _convert_to_datatype
    localtypes) for key in data\nTypeError: 'ResourceGroup' object is not iterable
	", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0} 

	to retry, use: --limit @/home/medcon/ansible/playbooks/deploy_acs.retry
```

##### STEPS TO REPRODUCE
1. Create Kubernetes ACS on Azure with 1 master node and 2 Windows OS agents
2. Open a new created resource group and select `1 Succeeded` link under "Deployments" label in the top of the resource group window (above the list of items
3. Select the single deployment item from the new opened window
4. Select "View Template" button in the top toolbar in the Deployment window
5. Select "Download" button in the top toolbar in the Template window
6. Delete the resource group and wait until the process is completed
7. Use files `template.json` and `parameters.json` from the downloaded archive to create a new deployment using the following playbook (principal credentials and subscription id i removed):
```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Deploy static K8S ACS
      azure_rm_deployment:
        state: present
        location: eastus
        subscription_id: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        resource_group_name: ansible_deployment_test1
        deployment_name: k8s_auto1
        deployment_mode: complete
        wait_for_deployment_completion: false
        template_link: '<path to template.json>'
        parameters_link: '<path to parameters.json>'
        tenant: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        client_id: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        secret: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

##### EXPECTED RESULTS
Kubernetes cluster on Azure is created

##### ACTUAL RESULTS
An error is reported (see SUMMARY)
