### ISSUE TITLE
postgresql_user use role_attr_flags=CREATEUSER  KeyError: 'rolcreateuser'

### ISSUE THREAD

**Issue by le9i0nx** [ansible/ansible#24928]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE

```yaml

- name: Create vagrant user
  sudo: true
  sudo_user: postgres
  postgresql_user: name=vagrant role_attr_flags=CREATEDB,CREATEUSER

- name: Create vagrant user2
  sudo: true
  sudo_user: postgres
  postgresql_user: name=vagrant role_attr_flags=CREATEDB,CREATEUSER

```
https://lookonmyworks.co.uk/2016/03/03/error-from-postgresql_user/

##### ACTUAL RESULTS

```
TASK [postgresql : Create PostgreSQL roles] ************************************
changed: [centos7-1.ru] => (item={u'priv': [u'ALL'], u'password': u'test324234', u'db': u'timevizor_applp', u'role_attr_flags': [u'NOCREATEUSER', u'CREATEDB'], u'name': u'timevizor_applp'})

TASK [postgresql : Create PostgreSQL roles] ************************************
failed: [centos7-1.ru] (item={u'priv': [u'ALL'], u'password': u'test324234', u'db': u'timevizor_applp', u'role_attr_flags': [u'NOCREATEUSER', u'CREATEDB'], u'name': u'timevizor_applp'}) => {"failed": true, "item": {"db": "timevizor_applp", "name": "timevizor_applp", "password": "test324234", "priv": ["ALL"], "role_attr_flags": ["NOCREATEUSER", "CREATEDB"]}, "module_stderr": "Shared connection to 192.168.0.227 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_qJnmMu/ansible_module_postgresql_user.py\", line 666, in <module>\r\n    main()\r\n  File \"/tmp/ansible_qJnmMu/ansible_module_postgresql_user.py\", line 621, in main\r\n    changed = user_alter(cursor, module, user, password, role_attr_flags, encrypted, expires, no_password_changes)\r\n  File \"/tmp/ansible_qJnmMu/ansible_module_postgresql_user.py\", line 274, in user_alter\r\n    if current_role_attrs[PRIV_TO_AUTHID_COLUMN[role_attr_name]] != role_attr_value:\r\n  File \"/usr/lib64/python2.7/site-packages/psycopg2/extras.py\", line 144, in __getitem__\r\n    x = self._index[x]\r\nKeyError: 'rolcreateuser'\r\n", "msg": "MODULE FAILURE"}
        to retry, use: --limit @/tmp/cloud.retry

PLAY RECAP *********************************************************************
centos7-1.ru               : ok=2    changed=1    unreachable=0    failed=1   

```
