### ISSUE TITLE
Support for with_* syntax for roles

### ISSUE THREAD

**Issue by wzyboy** [ansible/ansible#24921]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
roles

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/wzyboy/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Could `with_*` syntax be supported for roles?

Here's my story: we have three different environments (e.g. `['dev', 'testing', 'prod']`), and there are three different firewall zones in each environment (e.g. `['dmz', 'app', 'db']`). So we need a total of 3 * 3 = 9 different `nginx.conf`s for 9 nginx clusters. I have written an `nginx` role with heavy use of Jinja2 and templating. I would like to render them locally on my laptop to test the role before rendering them on 9 different nginx clusters for real. So I write a simple playbook:

```yaml
- hosts: "localhost"
  connection: local
  vars:
    nginx_conf_dir: "/tmp/nginx-render/nginx-{{ nginx_env }}-{{ zone }}"
  roles:
    - role: nginx
      nginx_env: "{{ item[0] }}"
      zone: "{{ item[1] }}"
      with_nested:
        - ["dev", "testing", "prod"]
        - ["dmz", "app", "db"]
```

However, this does not work. With the help of `debug` module, I realized that `with_nested` (or other `with_*`) are passed in as a literal list, without looping them over.

Google brought me to [this issue](https://github.com/ansible/ansible/issues/12623), from which I can see the syntax is not supported.

Without `with_*` syntax for roles, in the example above, I have to repeat `- role: nginx` 9 times to run this role 9 times with different vars.

Could maintainers of Ansible consider adding support for `with_*` syntax for roles?

**Comment by wzyboy** [comment]
Current workaround is to use `include_role` task module:

```yaml
- hosts: "localhost"
  connection: local
  vars:
    nginx_conf_dir: "/tmp/nginx-render/nginx-{{ nginx_env }}-{{ zone }}"
  handlers:
    # Workaround of https://github.com/ansible/ansible/issues/18411
    - include: ../roles/nginx/handlers/main.yaml
  tasks:
    - include_role:
        name: nginx
      private: yes
      vars:
        nginx_env: "{{ role_item[0] }}"
        zone: "{{ role_item[1] }}"
      with_nested:
        - ["dev", "testing", "prod"]
        - ["dmz", "app", "db"]
      loop_control:
        loop_var: "role_item"
```

Note that you need to include handlers manually before #18411 is fixed.
