### ISSUE TITLE
yum_repository module always reports the status as changed

### ISSUE THREAD

**Issue by GriffithLea** [ansible/ansible#24948]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

yum_repository
##### ANSIBLE VERSION

```
# ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION

pointed inventory at a directory containing my inventory sources
##### OS / ENVIRONMENT

RHEL 7.2
##### SUMMARY

If I run a task that creates yum repo file(s) in /etc/yum.repos.d, it always says they changed.
##### STEPS TO REPRODUCE

Run the playbook pasted below twice. I would expect the 2nd run to show nothing changing.

```yaml
---

- hosts: localhost
  vars:
    yum_servers:
      - server1
      - server2
    yum_repositories:
      - name: centos72
        description: CentOS-7.2 - Base
        baseurl: distros/CentOS/7/7.2.1511
      - name: centosplus
        description: CentOS-7 - Plus
        baseurl: distros/CentOS/7/centosplus/x86_64
        enabled: no
      - name: misc-rhel7
        description: misc YUM repo
        baseurl: repos/misc-rhel7
      - name: epel
        description: Extra Packages for Enterprise Linux 7
        baseurl: distros/Fedora-EPEL/7/x86_64
      - name: extras
        description: CentOS-7 - Extras
        baseurl: distros/CentOS/7/extras/x86_64
        enabled: no
      - name: updates
        description: CentOS-7 - Updates
        baseurl: distros/CentOS/7/updates/x86_64
        enabled: no
      - name: centos72-base
        description: CentOS-7 - Base
        baseurl: distros/CentOS/7/os/x86_64
        enabled: no
  tasks:
    - yum_repository:
        name: "{{item.name}}"
        description: "{{item.description}}"
        baseurl: |
          {% for yum_server in yum_servers %}
          https://{{yum_server}}/{{item.baseurl}}
          {% endfor %}
        enabled: "{{item.enabled|default(omit)}}"
      with_items: "{{yum_repositories}}"
      loop_control:
        label: "{{item.description}}"
```

##### EXPECTED RESULTS

The 2nd run should have reported no changes.
##### ACTUAL RESULTS

The second run showed changes.

I think that the multiple baseurl's are confusing yum_repository when it comes to deciding if something has changed. There is at least one extra newline in result.diff.after compared to result.diff.before .

```
# ansible-playbook ~/yumrepo.yml 

PLAY [localhost] *************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [yum_repository] ********************************************************************************************************************************************************************************************************
changed: [localhost] => (item=CentOS-7.2 - Base)
changed: [localhost] => (item=CentOS-7 - Plus)
changed: [localhost] => (item=misc YUM repo)
changed: [localhost] => (item=Extra Packages for Enterprise Linux 7)
changed: [localhost] => (item=CentOS-7 - Extras)
changed: [localhost] => (item=CentOS-7 - Updates)
changed: [localhost] => (item=CentOS-7 - Base)

PLAY RECAP *******************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

# ansible-playbook ~/yumrepo.yml 

PLAY [localhost] *************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [yum_repository] ********************************************************************************************************************************************************************************************************
changed: [localhost] => (item=CentOS-7.2 - Base)
changed: [localhost] => (item=CentOS-7 - Plus)
changed: [localhost] => (item=misc YUM repo)
changed: [localhost] => (item=Extra Packages for Enterprise Linux 7)
changed: [localhost] => (item=CentOS-7 - Extras)
changed: [localhost] => (item=CentOS-7 - Updates)
changed: [localhost] => (item=CentOS-7 - Base)

PLAY RECAP *******************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
Thanks for reporting this, @GriffithLea. The problem is in the formatting of the `baseurl` string. Basically, there is a difference between how the string is written into the file and how it's read by the `configparser` Python module. You can use the following formatting to achieve what you need and still maintain the compatible formatting:

```
- yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ 'https://' ~ ( yum_servers | join('/' ~ item.baseurl ~ '\nhttps://') ) ~ '/' ~ item.baseurl }}"
    enabled: "{{ item.enabled|default(omit) }}"
  with_items: "{{ yum_repositories }}"
```

Using this kind of templating in playbook is not recommended and therefore I'm closing this issue as `notabug`.
