### ISSUE TITLE
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'NoneType':

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#24963]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel 6dc2a6ce8b) last updated 2017/05/24 01:39:19 (GMT -500)
  config file = /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

Default ansible.cfg that is in the git repository

##### OS / ENVIRONMENT

macOS 10.12.4

##### SUMMARY

"git pull" to 2.4 code base and playbooks that worked in 2.3 fail in 2.4

##### STEPS TO REPRODUCE

real-time/testing inventory file
```yaml
[cross-fire.org]
forum.cross-fire.org

[linux-servers]
forum.cross-fire.org 
```
phpbb3-servers.yml
```yaml
---
# file: php-BB-servers.yml

- hosts: all
  vars:
  pre_tasks:
  roles:
    - { role: bootstrap, become: yes }
    - { role: updates, become: yes }
    - { role: grub2, become: yes }
    - { role: network-interface, become: yes }
    - { role: syslog-clients, become: yes }
    - { role: virtual-servers, become: yes }
    - { role: postfix-satellite, become: yes }
    - { role: logrotate, become: yes }
    - { role: apticron, become: yes }
    - { role: listchanges, become: yes }
    - { role: support-users, become: yes }
    - { role: backuppc-client, become: yes }
    - { role: nagios-plugins, become: yes }
    - { role: phpbb3-servers, become: yes }
  tasks:
  post_tasks:
    - command: "/usr/bin/passwd -l {{ ansible_user_id }}"
      become: yes
```

##### EXPECTED RESULTS

Ansible would run the playbook and associated roles

##### ACTUAL RESULTS

```
$ ansible-playbook -i real-time.com/testing --user=testing phpbb3-servers.yml --limit="forum.cross-fire.org" -vvvv
Using /Users/tanner/projects/ansible.git/playbooks.git/ansible.cfg as config file
setting up inventory plugins
Parsed /Users/tanner/projects/ansible.git/playbooks.git/real-time.com/testing inventory source with ini plugin
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/bootstrap/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/bootstrap/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/updates/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/updates/tasks/ubuntu/lucid.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/updates/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/grub2/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/grub2/tasks/ubuntu.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/grub2/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/network-interface/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/network-interface/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/syslog-clients/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/syslog-clients/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/virtual-servers/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/virtual-servers/tasks/remove-official-vmware-tools.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/virtual-servers/tasks/install-official-vmware-tools.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/virtual-servers/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/postfix-satellite/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/postfix-satellite/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/logrotate/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/logrotate/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/apticron/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/listchanges/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/listchanges/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/support-users/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/backuppc-client/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/backuppc-client/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/lib/sudo-safety-backup.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/lib/sudo-safety-restore.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/lib/sudo-safety-backup.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/lib/sudo-safety-restore.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/nagios-plugins/tasks/debian.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/lib/sudo-safety-backup.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/lib/sudo-safety-restore.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/nagios-plugins/tasks/suse.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/lib/sudo-safety.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/apache2-servers/tasks/remote-git-conf.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/apache2-servers/tasks/template-conf.yml
statically included: /Users/tanner/projects/ansible.git/playbooks.git/roles/phpbb3-servers/tasks/debian.yml
Loading callback plugin default of type stdout, v2.0 from /Users/tanner/projects/ansible.git/ansible/lib/ansible/plugins/callback/__init__.pyc

PLAYBOOK: phpbb3-servers.yml ***************************************************
1 plays in phpbb3-servers.yml

PLAY [all] *********************************************************************
ERROR! failed to combine variables, expected dicts but got a 'dict' and a 'NoneType':
{}
null
```
