### ISSUE TITLE
win_firewall_rule deletes firewall rules

### ISSUE THREAD

**Issue by adam-kosseck** [ansible/ansible#24976]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
windows/win_firewall_rule

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT
Ansible Server - Ubuntu 17.04
Ansible Clients - Windows Server 2012 R2 (Google Cloud)

##### SUMMARY
When playbook is run firewall rules are removed if they already existed, and not created if they did not previously exist.

##### STEPS TO REPRODUCE
Run this task (more than once if necessary):

```yaml
  vars:
    mdc_ip: "{{ hostvars['mdc1p']['gce_private_ip'] }}"

  tasks:
    - name: Firewall rule to allow metadata Comms incoming on subnet
      win_firewall_rule:
          name: Allow incoming from metadata server
          enable: True
          state: present
          localport: any
          action: allow
          direction: in
          protocol: any
          remoteip: "{{ mdc_ip }}/24"
          force: True

    - name: Firewall rule to allow metadata Comms outgoing on subnet
      win_firewall_rule:
          name: Allow outgoing to metadata server
          enable: True
          state: present
          localport: any
          action: allow
          direction: out
          protocol: any
          remoteip: "{{ mdc_ip }}/24"
          force: True
```

##### EXPECTED RESULTS

Firewall rule is created or updated

##### ACTUAL RESULTS

Ansible reports that firewall rules have been changed, but firewall rules appear to be deleted.
Firewall rules are not visible in Windows Firewall UI, and comms do not work.

Check via command line:
```
netsh advfirewall firewall show rule name="Allow outgoing to metadata server" verbose

No rules match the specified criteria.
```
Output of ansible playbook with -vvvv

```
TASK [Firewall rule to allow metadata Comms incoming on subnet] ************************************************************************************************************************************************************************************************************************
task path: /home/adam/playbook-install-firewall.yml:10
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_firewall_rule.ps1
<REMOVED> ESTABLISH WINRM CONNECTION FOR USER: REMOVED on PORT 5986 TO REMOVED
EXEC (via pipeline wrapper)
changed: [mdc1p] => {
    "changed": true, 
    "difference": [], 
    "failed": false, 
    "fwsettings": {
        "Action": "allow", 
        "Direction": "in", 
        "Enabled": "yes", 
        "LocalIP": "any", 
        "LocalPort": "any", 
        "Profiles": "any", 
        "Protocol": "any", 
        "RemoteIP": "10.148.0.5/24", 
        "RemotePort": "any", 
        "Rule Name": "Allow incoming from metadata server", 
        "Service": "any"
    }, 
    "msg": [
        "No rule could be found", 
        "Created firewall rule Allow incoming from metadata server"
    ]
}

TASK [Firewall rule to allow metadata Comms outgoing on subnet] ************************************************************************************************************************************************************************************************************************
task path: /home/adam/playbook-install-firewall.yml:22
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_firewall_rule.ps1
<REMOVED> ESTABLISH WINRM CONNECTION FOR USER: REMOVED on PORT 5986 TO REMOVED
EXEC (via pipeline wrapper)
changed: [mdc1p] => {
    "changed": true, 
    "difference": [], 
    "failed": false, 
    "fwsettings": {
        "Action": "allow", 
        "Direction": "out", 
        "Enabled": "yes", 
        "LocalIP": "any", 
        "LocalPort": "any", 
        "Profiles": "any", 
        "Protocol": "any", 
        "RemoteIP": "10.148.0.5/24", 
        "RemotePort": "any", 
        "Rule Name": "Allow outgoing to metadata server", 
        "Service": "any"
    }, 
    "msg": [
        "No rule could be found", 
        "Created firewall rule Allow outgoing to metadata server"
    ]
}

META: ran handlers

PLAY RECAP ************************************************************************************************************************************************************************************************************************************************************************
mdc1p                      : ok=3    changed=2    unreachable=0    failed=0   

```
