### ISSUE TITLE
Module unarchive: Failure when the group name in the group parameter contains a space.

### ISSUE THREAD

**Issue by areobe** [ansible/ansible#24989]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module: unarchive

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  3 2016, 22:05:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Running unarchive using the group ownership parameter fails to unarchive a tar file when the group has a space in it.

This is a regression from 2.0.0.2.
Fails in 2.2.3 and 2.3.0.

We use sssd with AD authentication, so "domain users" is a valid system group.

##### STEPS TO REPRODUCE

```yaml
---
- name: Unarchive
  hosts: remote_host
  become: True

  vars:
    user: "root"
    # Must be a valid system group with a space in it
    # e.g. /etc/group: domain users:x:10000:
    # $ getent group "domain users"
    # domain users:x:10000:
    group: "domain users"

  tasks:
    - unarchive: src="/tmp/archive.tar.gz" dest="/opt" copy=no owner="{{ user }}" group="{{ group }}"
```

##### ACTUAL RESULTS

unarchive fails to unarchive.

```
PLAY [Unarchive] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [remote_host]

TASK [unarchive] ***************************************************************
fatal: [remote_host]: FAILED! => {"changed": false, "dest": "/opt", "failed": true, "gid": 0, "group": "root", "handler": "TgzArchive", "mode": "0755", "msg": "Unexpected error when accessing exploded file: [Errno 2] No such file or directory: '/opt/etc/'", "owner": "root", "size": 4096, "src": "/tmp/archive.tar.gz", "state": "directory", "uid": 0}

PLAY RECAP *********************************************************************
remote_host                    : ok=1    changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
