### ISSUE TITLE
nxos_evpn_vni state present not working

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#24995]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_evpn_vni

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### OS / ENVIRONMENT

RHEL 7.2

##### SUMMARY

Setting evpn configs as state:absent. Ansible outputs "ok" not "changed". Checked NxOS and configs were not deleted. 

##### STEPS TO REPRODUCE

```
      - name: Ensure EVPN is not on device
        nxos_evpn_vni:
          vni: "{{ vnid }}"
          username: un
          password: pwd
          host: "{{ item }}"
          state: absent
          transport: cli
        with_items:
          - "{{ leaf1ip }}"
          - "{{ leaf2ip }}"
          - "{{ leaf3ip }}"
          - "{{ leaf4ip }}"
        register: delevpn
        ignore_errors: yes
```

##### EXPECTED RESULTS

```
changed: [localhost] => (item=leaf1)
changed: [localhost] => (item=leaf2)
changed: [localhost] => (item=leaf3)
changed: [localhost] => (item=leaf4)
```
expected configs deleted when playbook is ran

##### ACTUAL RESULTS

output below is the same for the four items
```
<127.0.0.1> connection transport is cli
<> using connection plugin network_cli
<> socket_path: /root/.ansible/pc/531159983e
open_shell() returned 0 ok
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_evpn_vni.py
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1495645321.48-36455347467130 `" && echo ansible-tmp-1495645321.48-36455347467130="` echo /root/.ansible/tmp/ansible-tmp-1495645321.48-36455347467130 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp10V3Dw TO /root/.ansible/tmp/ansible-tmp-1495645321.48-36455347467130/nxos_evpn_vni.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1495645321.48-36455347467130/ /root/.ansible/tmp/ansible-tmp-1495645321.48-36455347467130/nxos_evpn_vni.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1495645321.48-36455347467130/nxos_evpn_vni.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1495645321.48-36455347467130/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => (item=) => {
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "config": null,
            "host": "",
            "include_defaults": "True",
            "password": "",
            "port": null,
            "provider": null,
            "route_distinguisher": null,
            "route_target_both": null,
            "route_target_export": null,
            "route_target_import": null,
            "save": false,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": 10,
            "transport": "cli",
            "use_ssl": null,
            "username": "",
            "validate_certs": null,
            "vni": "5304"
        }
    },
    "item": "",
    "warnings": [
        "argument username has been deprecated and will be removed in a future version",
        "argument host has been deprecated and will be removed in a future version",
        "argument password has been deprecated and will be removed in a future version"
    ]
}

```

**Comment by ghost** [comment]
@trishnaguha

**Comment by ansibot** [comment]
cc @jedelman8 @GGabriele @rahushen @privateip @rcarrillocruz @mikewiebe
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
@donsantos Can you please make sure that the config is already present on your device or not?

**Comment by ghost** [comment]
@trishnaguha 
this is the config for creating it and output 

```
    - name: Configure EVPN
      nxos_evpn_vni:
        vni: "{{ vnid }}"
        route_distinguisher: auto
        route_target_import: auto
        route_target_export: auto
        username: un
        password: pwd
        host: "{{ item }}"
        state: present
        transport: cli
      with_items:
        - "{{ leaf1ip }}"
        - "{{ leaf2ip }}"
        - "{{ leaf3ip }}"
        - "{{ leaf4ip }}"
      register: evpnconfig
      ignore_errors: yes
```

```
changed: [localhost] => (item=) => {
    "changed": true,
    "commands": [
        "evpn",
        "vni 5304 l2"
    ],
    "invocation": {
        "module_args": {
            "config": null,
            "host": "",
            "include_defaults": "True",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": null,
            "route_distinguisher": "auto",
            "route_target_both": null,
            "route_target_export": [
                "auto"
            ],
            "route_target_import": [
                "auto"
            ],
            "save": false,
            "ssh_keyfile": null,
            "state": "present",
            "timeout": 10,
            "transport": "cli",
            "use_ssl": null,
            "username": "",
            "validate_certs": null,
            "vni": "5304"
        }
    },
    "item": "",
    "warnings": [
        "argument username has been deprecated and will be removed in a future version",
        "argument host has been deprecated and will be removed in a future version",
        "argument password has been deprecated and will be removed in a future version"
    ]
}
```

After creation I ran nxos_evpn_vni with state: absent and received "ok" as the output
