### ISSUE TITLE
Module: junos_config - ValueError: line must start with either `set` or `delete`

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#24998]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
junos_config

##### ANSIBLE VERSION

```
2.2+
```

##### CONFIGURATION
host_key_checking = False

##### OS / ENVIRONMENT
Executing Ansible from RHEL7
Managing Juniper networking equipment

##### SUMMARY
junos_config module does not allow us to leverage the `wildcard range set|delete` configuration commands when executing lines in src_format: set

in the event we wanted to change spanning-tree, for instance, we would have to send one line for every interface. by using the wildcard feature within Junos, we could reduce that down to one

##### STEPS TO REPRODUCE
```yaml
---
- name: change spanning-tree mode
  hosts: qfx5100
  connection: local
  gather_facts: no
  vars:
    netconf:
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      port: 22
  tasks:
    - include_vars: vars.yml
    - name: build MST instance 1 configuration
      junos_config:
        src_format: set
        comment: "this will fail :)"
        timeout: 300
        provider: "{{ netconf }}"
        lines:
          - delete protocols vstp
          - set protocols mstp bpdu-block-on-edge
          - set protocols mstp revision-level1
          - set protocols mstp msti 1 vlan 10-20
          - set protocols mstp msti 1 configuration-name PLEASE_CONSIDER_ADDING_WILDCARDS
          - wildcard range set protocols mstp interface xe-[0-1]/0/[0-37] edge
          - wildcard range set protocols mstp interface ae-[0-3] edge mode point-to-point
```

##### EXPECTED RESULTS
module could handle Juniper's method of applying a configuration to multiple elements within a single command. 

##### ACTUAL RESULTS
 ```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: line must start with either `set` or `delete`
```

To work around this, my playbook increased from seven lines to over two hundred, as I broke was forced to break out of the wildcard method.

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
@packetferret Thanks for the feature request, this is something we will look at for Ansible 2.5.

**Comment by ansibot** [comment]
cc @privateip
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kedarX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by packetferret** [comment]
are we still looking at 2.5 as being the release to enable this feature?

**Comment by ghost** [comment]
I have confirmed that this can now be pulled off successfully

```
  - name: "### JUNOS - APPLY CONFIGURATION ###"
    hosts: leaf
    gather_facts: False
    connection: local
    tasks:
      - name: "# JUNOS - DELETE DEFAULT INTERFACE CONFIGURATION #"
        junos_config:
          provider:
            host: "{{ ansible_ssh_host }}"
            port: "{{ ansible_port }}"
            username: root
            password: Juniper
          lines:
            - wildcard delete interfaces xe-0/0/[0-9]
            - wildcard delete interfaces et-0/0/[0-9]
```
