### ISSUE TITLE
Parameter validation failed for int types using CloudFormation Module

### ISSUE THREAD

**Issue by therealdwright** [ansible/ansible#25013]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cloudformation

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION
ANSIBLE_HOST_KEY_CHECKING=False

##### OS / ENVIRONMENT
Amazon Linux (4.9.27-14.31.amzn1.x86_64)
Mac OSX 16.6.0
Boto3: 1.4.3
Boto2: 2.47.0

##### SUMMARY
After upgrading to Ansible 2.3.0 Parameter validation failed for int types using CloudFormation Module.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost

  vars:
    stack_name: front-end-service
    region: ap-southeast-2
    template_parameters:
      serviceMaxSize: 2
      serviceMinSize: 1
      targetEnvironment: DEV

  tasks:
    - name: launch front end cloudformation stack if none exists else update
      cloudformation:
        stack_name: "{{ front_end_service_stack_name }}"
        state: "present"
        region: "{{  aws_region }}"
        profile: "{{ aws_account_name }}"
        template: "{{ playbook_dir }}/roles/front-end-service/files/front_end.json"
        template_parameters: "{{ template_parameters }}"
        tags:
          Stack: "{{ front_end_service_stack_name }}"
      register: service_stack
      when: delete_resources is not defined
```

##### EXPECTED RESULTS

The template creates or updates the stack with the output below.

```
TASK [front-end-service : launch front end cloudformation stack if none exists else update] ***
changed: [localhost]
```

##### ACTUAL RESULTS

The stack will not create/update with the parameter error below.

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Parameter validation failed:
Invalid type for parameter Parameters[3].ParameterValue, value: 1, type: <type 'int'>, valid types: <type 'basestring'>
Invalid type for parameter Parameters[16].ParameterValue, value: 2, type: <type 'int'>, valid types: <type 'basestring'> Parameter validation failed:
Invalid type for parameter Parameters[3].ParameterValue, value: 1, type: <type 'int'>, valid types: <type 'basestring'>
Invalid type for parameter Parameters[16].ParameterValue, value: 2, type: <type 'int'>, valid types: <type 'basestring'> - <class 'botocore.exceptions.ParamValidationError'>"}
```
##### WORKAROUND

Convert integer variables to strings as per below:

```yaml
- hosts: localhost

  vars:
    stack_name: front-end-service
    region: ap-southeast-2
    template_parameters:
      serviceMaxSize: "2"
      serviceMinSize: "1"
      targetEnvironment: DEV

  tasks:
    - name: launch front end cloudformation stack if none exists else update
      cloudformation:
        stack_name: "{{ front_end_service_stack_name }}"
        state: "present"
        region: "{{  aws_region }}"
        profile: "{{ aws_account_name }}"
        template: "{{ playbook_dir }}/roles/front-end-service/files/front_end.json"
        template_parameters: "{{ template_parameters }}"
        tags:
          Stack: "{{ front_end_service_stack_name }}"
      register: service_stack
      when: delete_resources is not defined
```
