### ISSUE TITLE
ini_file create a backup file for each key change and not per run

### ISSUE THREAD

**Issue by rabin-io** [ansible/ansible#25026]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ini_file

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
nothing

##### OS / ENVIRONMENT
Gnu/Linux Fedora 25/x64

##### SUMMARY
Not sure it's a but or a future, but when setting `backup=yes` for this module, it will create a backup for each key change, and not per-run change.

##### STEPS TO REPRODUCE

```yaml
- name: Configure postfix
  ini_file:
    backup=yes owner=root group=root  mode=0644
    dest=/etc/postfix/main.cf
    section=
    option={{item.key}} value={{item.value}} state=present
  with_items:
    - { key: relayhost             , value: smtp                 }
    - { key: mydestination         , value: ""                   }
    - { key: inet_protocols        , value: ipv4                 }
    - { key: smtp_host_lookup      , value: native               }
    - { key: enable_long_queue_ids , value: yes                  }
  tags:
    - postfix
```
```
# ll /etc/postfix/main.cf.*
-rw-r--r--. 1 root root 27176 May 25 02:09 /etc/postfix/main.cf.21986.2017-05-25@02:11:37~
-rw-r--r--. 1 root root 27215 May 25 02:11 /etc/postfix/main.cf.22000.2017-05-25@02:11:38~
-rw-r--r--. 1 root root 27232 May 25 02:11 /etc/postfix/main.cf.22014.2017-05-25@02:11:38~
-rw-r--r--. 1 root root 27249 May 25 02:11 /etc/postfix/main.cf.22028.2017-05-25@02:11:38~
-rw-r--r--. 1 root root 27271 May 25 02:11 /etc/postfix/main.cf.22042.2017-05-25@02:11:38~
-rw-r--r--. 1 root root 27297 May 25 02:11 /etc/postfix/main.cf.22056.2017-05-25@02:11:38~
```

##### EXPECTED RESULTS
I was expecting for single backup for each run which change the file.

##### ACTUAL RESULTS
Ansible will create a backup for each key it change
```
[root@dbase1 usr]# diff -ub  /etc/postfix/main.cf.22000.2017-05-25@02:11:38~ /etc/postfix/main.cf.22014.2017-05-25@02:11:38~                                                                                                                   
--- /etc/postfix/main.cf.22000.2017-05-25@02:11:38~     2017-05-25 02:11:37.853129000 +0000
+++ /etc/postfix/main.cf.22014.2017-05-25@02:11:38~     2017-05-25 02:11:38.049212000 +0000
@@ -679,3 +679,4 @@
 readme_directory = /usr/share/doc/postfix-2.10.1/README_FILES
+relayhost = smtp
[root@dbase1 usr]# diff -ub  /etc/postfix/main.cf.22014.2017-05-25@02:11:38~ /etc/postfix/main.cf.22028.2017-05-25@02:11:38~                                                                                           
--- /etc/postfix/main.cf.22014.2017-05-25@02:11:38~     2017-05-25 02:11:38.049212000 +0000
+++ /etc/postfix/main.cf.22028.2017-05-25@02:11:38~     2017-05-25 02:11:38.266962000 +0000
@@ -680,3 +680,4 @@
 relayhost = smtp
+mydestination = 
```
