### ISSUE TITLE
Wait_for should return matches to groups in its search_regex

### ISSUE THREAD

**Issue by tidzo** [ansible/ansible#25020]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
wait_for

##### ANSIBLE VERSION
```
2.3
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
When using the wait_for module to monitor, say, a file for a string matching a particular search_regex, it would be helpful if the matches to that regex were available in the module's output.

In my current use case, I'm monitoring a log file from a remote process which was started asynchronously and want to display certain pertinent information from it in the Ansible output.

##### STEPS TO REPRODUCE

```yaml
 - name: Wait for message in log file
    wait_for:
        path: "somefile.log'
        search_regex: "SOMETHING_HAPPENED start_delimiter(.*)end_delimiter"
    register: foo

 - name: show text between delimiters
    debug: msg="The text between delimiters was {{foo.result.matches[0]}}"
```

##### EXPECTED RESULTS

The wait_for task will pause until text matching the search_regex is found in somefile.log (or timeout occurs).  The text between the parens in the regex will be available somewhere in the variable registered in wait_for task.

##### ACTUAL RESULTS

The matches are not available in the registered variable.
