### ISSUE TITLE
[parted] module parted fails if partition has lvm volumes

### ISSUE THREAD

**Issue by zunkree** [ansible/ansible#25033]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
parted

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /Users/zunkree/Projects/infrastructure/k8s.ringlabskiev.com/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
```
[defaults]
inventory = /usr/local/bin/terraform-inventory
retry_files_enabled = False

gathering = smart
fact_caching = jsonfile
fact_caching_timeout = 86400
fact_caching_connection = cachedir

host_key_checking = False
```

##### OS / ENVIRONMENT
Ubuntu 16.04 on AWS

##### SUMMARY
Partition has been created with previous run and lvm volume group/volumes has been created. Module fails next runs with message:
```
fatal: [XXX.XXX.XXX.XXX]: FAILED! => {"changed": false, "err": "Error: Partition(s) 1 on /dev/xvdf have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.\n", "failed": true, "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/xvdf -- unit KiB mklabel gpt mkpart primary 0% 100%", "out": "", "rc": 1}
```

##### STEPS TO REPRODUCE
Run ansible again with such tasks
```yaml
---
# tasks file for roles/etcd
- name: create partition...
  parted:
    number: 1
    label: gpt
    flags: [ lvm ]
    state: present
    device: "{{ storage_dev }}"
  become: yes

- name: create volume group...
  lvg:
    vg: "{{ storage_vg }}"
    pvs: "{{ storage_pv }}"
  become: yes

- name: create lvm volumes...
  lvol:
    vg: "{{ storage_vg }}"
    lv: "{{ item.name }}"
    size: "{{ item.size }}"
  become: yes
  with_items: "{{ storage_lvol }}"

- name: make filesystems...
  filesystem:
    fstype: ext4
    resizefs: yes
    dev: "/dev/{{ storage_vg }}/{{ item.name }}"
  become: yes
  with_items: "{{ storage_lvol }}"

- name: create mount directories...
  file:
    path: "{{ item.mount }}"
    state: directory
  become: yes
  with_items: "{{ storage_lvol }}"

- name: mount directories...
  mount:
    name: "{{ item.mount }}"
    src: "/dev/{{ storage_vg }}/{{ item.name }}"
    fstype: ext4
    opts: defaults,relatime
    state: mounted
  become: yes
  with_items: "{{ storage_lvol }}"
```
defaults:
```
storage_dev: /dev/xvdf
storage_pv: "{{ storage_dev }}1"
storage_vg: etcd00
storage_lvol:
  - name: data
    size: 2g
    mount: '/var/lib/data'
```

##### EXPECTED RESULTS
Module detects correctly created partition and works without errors.

##### ACTUAL RESULTS
Module fails with error:
```
<XXX.XXX.XXX.XXX> (0, '\r\n{"rc": 1, "out": "", "err": "Error: Partition(s) 1 on /dev/xvdf have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.\\n", "invocation": {"module_args": {"align": "optimal", "part_end": "100%", "flags": ["lvm"], "part_type": "primary", "device": "/dev/xvdf", "unit": "KiB", "part_start": "0%", "state": "present", "label": "gpt", "number": 1, "name": null}}, "failed": true, "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/xvdf -- unit KiB mklabel gpt mkpart primary 0% 100%"}\r\n', 'Shared connection to XXX.XXX.XXX.XXX closed.\r\n')
fatal: [XXX.XXX.XXX.XXX]: FAILED! => {
    "changed": false,
    "err": "Error: Partition(s) 1 on /dev/xvdf have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.\n",
    "failed": true,
    "invocation": {
        "module_args": {
            "align": "optimal",
            "device": "/dev/xvdf",
            "flags": [
                "lvm"
            ],
            "label": "gpt",
            "name": null,
            "number": 1,
            "part_end": "100%",
            "part_start": "0%",
            "part_type": "primary",
            "state": "present",
            "unit": "KiB"
        }
    },
    "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/xvdf -- unit KiB mklabel gpt mkpart primary 0% 100%",
    "out": "",
    "rc": 1
}```

**Comment by ansibot** [comment]
cc @ColOfAbRiX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ColOfAbRiX** [comment]
Hi @zunkree and thanks for reporting.

I actually cannot reproduce the issue, every time I run the play it works, but I'm testing on CentOS. I'll get my hands on an Ubuntu 16 machine and try again.

**Comment by ColOfAbRiX** [comment]
Even on Ubuntu I have the same result, here is the output. My guess is that it's not parted but an inconsistent state of the system where something has been done and the change is not reflected in the kernel.

**The system I'm using**
```
root@vagrant:~# cat /etc/issue
Ubuntu 16.04 LTS \n \l

root@vagrant:~# uname -a
Linux vagrant 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

root@vagrant:~# ansible --version
ansible 2.4.0 (devel 797259f757) last updated 2017/05/26 10:28:22 (GMT -400)
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

root@vagrant:~# lsblk
NAME                   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                      8:0    0   80G  0 disk
├─sda1                   8:1    0  487M  0 part /boot
├─sda2                   8:2    0    1K  0 part
└─sda5                   8:5    0 79.5G  0 part
  ├─vagrant--vg-root   252:0    0 78.8G  0 lvm  /
  └─vagrant--vg-swap_1 252:1    0  768M  0 lvm  [SWAP]
sdb                      8:16   0    2G  0 disk
sr0                     11:0    1 1024M  0 rom
```
**The playbook:**
```
root@vagrant:~# cat issue_25033.yml
- hosts: all
  become: yes
  gather_facts: no
  connection: local
  vars:
    storage_dev: /dev/sdb
    storage_pv: "{{ storage_dev }}1"
    storage_vg: etcd00
    storage_lvol:
      - name: data
        size: 1g
        mount: '/tmp/issue_25033'
    reset_dev: true
  tasks:
   - name: create partition...
     parted:
       number: 1
       label: gpt
       flags: [ lvm ]
       state: present
       device: "{{ storage_dev }}"
     become: yes

   - name: create volume group...
     lvg:
       vg: "{{ storage_vg }}"
       pvs: "{{ storage_pv }}"
     become: yes

   - name: create lvm volumes...
     lvol:
       vg: "{{ storage_vg }}"
       lv: "{{ item.name }}"
       size: "{{ item.size }}"
     become: yes
     with_items: "{{ storage_lvol }}"

   - name: make filesystems...
     filesystem:
       fstype: ext4
       resizefs: yes
       dev: "/dev/{{ storage_vg }}/{{ item.name }}"
     become: yes
     with_items: "{{ storage_lvol }}"

   - name: create mount directories...
     file:
       path: "{{ item.mount }}"
       state: directory
     become: yes
     with_items: "{{ storage_lvol }}"

   - name: mount directories...
     mount:
       name: "{{ item.mount }}"
       src: "/dev/{{ storage_vg }}/{{ item.name }}"
       fstype: ext4
       opts: defaults,relatime
       state: mounted
     become: yes
     with_items: "{{ storage_lvol }}"
```
**Two runs:**
```
root@vagrant:~# ansible-playbook -i inventory issue_25033.yml

PLAY [all] ****************************************************************************************************************************************************************

TASK [create partition...] ************************************************************************************************************************************************
ok: [localhost]

TASK [create volume group...] *********************************************************************************************************************************************
ok: [localhost]

TASK [create lvm volumes...] **********************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'1g'})

TASK [make filesystems...] ************************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'1g'})

TASK [create mount directories...] ****************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'1g'})

TASK [mount directories...] ***********************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'1g'})

PLAY RECAP ****************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0


root@vagrant:~# ansible-playbook -i inventory issue_25033.yml

PLAY [all] ****************************************************************************************************************************************************************

TASK [create partition...] ************************************************************************************************************************************************
ok: [localhost]

TASK [create volume group...] *********************************************************************************************************************************************
ok: [localhost]

TASK [create lvm volumes...] **********************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'1g'})

TASK [make filesystems...] ************************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'1g'})

TASK [create mount directories...] ****************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'1g'})

TASK [mount directories...] ***********************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'1g'})

PLAY RECAP ****************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0
```

**Comment by ColOfAbRiX** [comment]
issue_25033

Even on Ubuntu I have the same result, here is the output. My guess is that it's not parted but an inconsistent state of the system where something has been done and the change is not reflected in the kernel.

**The system I'm using**
```
root@vagrant:~# cat /etc/issue
Ubuntu 16.04 LTS \n \l

root@vagrant:~# uname -a
Linux vagrant 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

ansible 2.3.0.0 (detached HEAD d56ba0945d) last updated 2017/05/26 11:43:16 (GMT -400)
  config file = /root/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

root@vagrant:~# lsblk
NAME                   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda                      8:0    0   80G  0 disk
├─sda1                   8:1    0  487M  0 part /boot
├─sda2                   8:2    0    1K  0 part
└─sda5                   8:5    0 79.5G  0 part
  ├─vagrant--vg-root   252:0    0 78.8G  0 lvm  /
  └─vagrant--vg-swap_1 252:1    0  768M  0 lvm  [SWAP]
sdb                      8:16   0    2G  0 disk
sr0                     11:0    1 1024M  0 rom
```
**The playbook:**
```
root@vagrant:~# cat issue_25033.yml
- hosts: all
  become: yes
  gather_facts: no
  connection: local
  vars:
    storage_dev: /dev/sdb
    storage_pv: "{{ storage_dev }}1"
    storage_vg: etcd00
    storage_lvol:
      - name: data
        size: 1g
        mount: '/tmp/issue_25033'
    reset_dev: true
  tasks:
   - name: create partition...
     parted:
       number: 1
       label: gpt
       flags: [ lvm ]
       state: present
       device: "{{ storage_dev }}"
     become: yes

   - name: create volume group...
     lvg:
       vg: "{{ storage_vg }}"
       pvs: "{{ storage_pv }}"
     become: yes

   - name: create lvm volumes...
     lvol:
       vg: "{{ storage_vg }}"
       lv: "{{ item.name }}"
       size: "{{ item.size }}"
     become: yes
     with_items: "{{ storage_lvol }}"

   - name: make filesystems...
     filesystem:
       fstype: ext4
       resizefs: yes
       dev: "/dev/{{ storage_vg }}/{{ item.name }}"
     become: yes
     with_items: "{{ storage_lvol }}"

   - name: create mount directories...
     file:
       path: "{{ item.mount }}"
       state: directory
     become: yes
     with_items: "{{ storage_lvol }}"

   - name: mount directories...
     mount:
       name: "{{ item.mount }}"
       src: "/dev/{{ storage_vg }}/{{ item.name }}"
       fstype: ext4
       opts: defaults,relatime
       state: mounted
     become: yes
     with_items: "{{ storage_lvol }}"
```
**Two runs, on a freshly provisioned machine with Vagrant:**
```
root@vagrant:~# ansible-playbook -i inventory issue_25033.yml

PLAY [all] ****************************************************************************************************************************************************************

TASK [create partition...] ************************************************************************************************************************************************
changed: [localhost]

TASK [create volume group...] *********************************************************************************************************************************************
changed: [localhost]

TASK [create lvm volumes...] **********************************************************************************************************************************************
changed: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'2g'})

TASK [make filesystems...] ************************************************************************************************************************************************
changed: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'2g'})

TASK [create mount directories...] ****************************************************************************************************************************************
changed: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'2g'})

TASK [mount directories...] ***********************************************************************************************************************************************
changed: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'2g'})

PLAY RECAP ****************************************************************************************************************************************************************
localhost                  : ok=6    changed=6    unreachable=0    failed=0


root@vagrant:~# ansible-playbook -i inventory issue_25033.yml

PLAY [all] ****************************************************************************************************************************************************************

TASK [create partition...] ************************************************************************************************************************************************
ok: [localhost]

TASK [create volume group...] *********************************************************************************************************************************************
ok: [localhost]

TASK [create lvm volumes...] **********************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'2g'})

TASK [make filesystems...] ************************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'2g'})

TASK [create mount directories...] ****************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'2g'})

TASK [mount directories...] ***********************************************************************************************************************************************
ok: [localhost] => (item={u'mount': u'/tmp/issue_25033', u'name': u'data', u'size': u'2g'})

PLAY RECAP ****************************************************************************************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0
```

**Comment by ppruchnerovic** [comment]
Hello,

I can confirm this bug exists on 
RHEL 7 on AWS
```
#ansible --version
ansible 2.5.4
  config file = /home/ansible/peterp/energy.monitoring/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/aws/venv/lib/python2.7/site-packages/ansible
  executable location = /home/ansible/aws/venv/bin/ansible
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

I created partition, lvm volume group and logical volume.

Then tried to re-run playbook and with this definition, ansible is trying to create partition again.
```
- name: Create empty partiton for LVM volume group
  parted:
    device: "{{ lvm_device }}"
    number: 1
    label: "{{ lvm_device_partition_label }}"
    state: present
    flags: [ lvm ]
```

But if I remove `flags: [ lvm ]`, it is not trying to change it.
