### ISSUE TITLE
docker_image push is not idempotent

### ISSUE THREAD

**Issue by tardich** [ansible/ansible#25040]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
docker_image

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### SUMMARY
Trying to push an image to a private registry with the above code:

    docker_image:
      name: 192.0.2.101:5000/myimage
      push: yes
      use_tls: false
      state: present

always return changed=1

##### STEPS TO REPRODUCE

```
    docker_image:
      name: 192.0.2.101:5000/myimage
      push: yes
      use_tls: false
      state: present
```

##### EXPECTED RESULTS
When the image is already present, the code should return OK rather than changed, for itempotency (very important in CICD pipelines

##### ACTUAL RESULTS

```
PLAY RECAP *****************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0

```
