### ISSUE TITLE
Redshift Module Broken When wait: yes

### ISSUE THREAD

**Issue by micsy** [ansible/ansible#25056]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
redshift module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/ubuntu/ansible/ansible.cfg
  configured module search path = [u'modules/']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT
Ubuntu

##### SUMMARY
When creating a redshift cluster using the built in redshift module there is a python exception where the code is trying to add a string to a float, this happens whether i specify my own value or omit to force the default value.

##### STEPS TO REPRODUCE
Using the redshift module, create a cluster specifying wait as true. For wait_timeout, either setting an int value or omitting the line will cause the exception

```yaml
- name: "Create AWS Redshift Cluster"
  redshift:
    region: "eu-west-1"
    command: create
    identifier: "test-redshift"
    node_type: "ds2.xlarge"
    number_of_nodes: "4"
    cluster_type: "multi-node"
    subnet: "{{ aws_redshift_subnet_group.group.name }}"
    cluster_version: "1.0" 
    automated_snapshot_retention_period: 1
    publicly_accessible: no
    vpc_security_groups: "{{ aws_redshift_security_group.group.name }}"
    username: "admin"
    password: "Passwrod123"
    wait: yes #Error does not seem to happen when set to no
    wait_timeout: 3600 #Setting a value or omitting this line causes the issue
  register: aws_redshift_instance
```

##### EXPECTED RESULTS
Redshift cluster should create with the wait flag set

##### ACTUAL RESULTS

```
TASK [create-network : Create AWS Redshift Cluster] ***********************************************************************
task path: /home/ubuntu/code/ansible/ansible-dev/roles/create-redshift/tasks/main.yml:106
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/amazon/redshift.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1495788650.68-58620293769733 `" && echo ansible-tmp-1495788650.68-58620293769733="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1495788650.68-58620293769733 `" ) && sleep 0'
<localhost> PUT /tmp/tmpQSw3Hl TO /home/ubuntu/.ansible/tmp/ansible-tmp-1495788650.68-58620293769733/redshift.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1495788650.68-58620293769733/ /home/ubuntu/.ansible/tmp/ansible-tmp-1495788650.68-58620293769733/redshift.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1495788650.68-58620293769733/redshift.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1495788650.68-58620293769733/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ByRYQt/ansible_module_redshift.py", line 485, in <module>
    main()
  File "/tmp/ansible_ByRYQt/ansible_module_redshift.py", line 467, in main
    (changed, cluster) = create_cluster(module, conn)
  File "/tmp/ansible_ByRYQt/ansible_module_redshift.py", line 293, in create_cluster
    wait_timeout = time.time() + wait_timeout
TypeError: unsupported operand type(s) for +: 'float' and 'str'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ByRYQt/ansible_module_redshift.py\", line 485, in <module>\n    main()\n  File \"/tmp/ansible_ByRYQt/ansible_module_redshift.py\", line 467, in main\n    (changed, cluster) = create_cluster(module, conn)\n  File \"/tmp/ansible_ByRYQt/ansible_module_redshift.py\", line 293, in create_cluster\n    wait_timeout = time.time() + wait_timeout\nTypeError: unsupported operand type(s) for +: 'float' and 'str'\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```
