### ISSUE TITLE
Add Hiera Lookup to integrate with a already running ENC on a Puppetmaster

### ISSUE THREAD

**Issue by jparrill** [ansible/ansible#25057]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- Plugin

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:36) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### OS / ENVIRONMENT
- Linux

##### SUMMARY
Add Hiera Lookup to consume those variables from Ansible, working obviusly from a Foreman Node or Smart Proxy.

##### STEPS TO REPRODUCE
```yaml
---
- name: Create Facts with Hiera Data
  hosts: nodes
  become: yes
  tasks:
    - name: 'Get Hiera Variables'
      set_fact:
        hiera_get_test: "{{ lookup('hiera', 'line environment=production') }}"
        hiera_get_test1: "{{ lookup('hiera', 'test1') }}"

    - debug: var=item
      with_items:
        - "{{ hiera_get_test }}"
        - "{{ hiera_get_test1 }}"

```

##### EXPECTED RESULTS

```
[root@puppet01 vagrant]# ansible-playbook -i inventories/puppetmaster_example_inv -l nodes hiera_lookup.yml 

PLAY [Create Facts with Hiera Data] **********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [vagrantServer]

TASK [Get Hiera Variables] *******************************************************************************************************************************************************************************************************************
ok: [vagrantServer]

TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [vagrantServer] => (item=01) => {
    "item": "01"
}
ok: [vagrantServer] => (item=PRO05) => {
    "item": "PRO05"
}

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
vagrantServer              : ok=3    changed=0    unreachable=0    failed=0   

```
