### ISSUE TITLE
when condition checks complain about templated variables

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#25053]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
when templating checking

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 2af5556901) last updated 2017/05/26 11:55:34 (GMT +1000)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/src/ansible/lib/ansible
  executable location = /home/will/src/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
ansible-playbook is warning about `when` conditions that are variables that are composed of other variables (e.g. anything of the form `x: "{{ y }}"` and then doing `when: x`

##### STEPS TO REPRODUCE
ansible-playbook playbook.yml

```yaml
$ cat playbook.yml 
- hosts: localhost
  connection: local
  gather_facts: False

  vars:
    x: hello
    y: world
    a_list:
      - "{{ x }}"
      - "{{ y }}"

  tasks:
    - debug:
        var: a_list
      when: a_list
```

##### EXPECTED RESULTS
As below without the WARNING

##### ACTUAL RESULTS
```

$ ansible-playbook playbook.yml -v
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] *********************************************************************************************************************************************

TASK [debug] *************************************************************************************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: [u'{{ x }}', u'{{ y }}']

ok: [localhost] => {
    "a_list": [
        "hello", 
        "world"
    ]
}

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```
