### ISSUE TITLE
win_nssm: Failure when removing a service which is stopped

### ISSUE THREAD

**Issue by rleigh-codelibre** [ansible/ansible#25065]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_nssm

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /data/code/infrastructure/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
```
[defaults]
forks = 20
gathering = smart
roles_path = vendor/:roles/:roles-dev/
inventory = ../../ansible/inventory/
retry_files_enabled = False
inventory_ignore_extensions = ~, .orig, .bak, .ini, .retry, .pyc, .pyo, .html, .omero, .gif, .png, .js, .md
callback_plugins = ./plugins/callback
```

##### OS / ENVIRONMENT
Managing with Ubuntu 17.04, host is Windows Server 2012 x64

##### SUMMARY
`win_nssm` fails to remove a service which is already stopped.

##### STEPS TO REPRODUCE

```yaml
- name: ci-jenkins-service (windows) | Remove Jenkins service
  win_nssm:
    name: jenkins
    state: absent
  environment:
    PATH: "{{ tools_location }}\\sbin;{{ ansible_env.Path }}"
```

##### EXPECTED RESULTS
I expected that the service would be removed

##### ACTUAL RESULTS
The service removal failed.  This is due to this error:

```
TASK [ci-jenkins-service : ci-jenkins-service (windows) | Remove Jenkins service] *********************************************************************
fatal: [wrasse.openmicroscopy.org]: FAILED! => {"changed": false, "failed": true, "msg": "an exception occurred when invoking NSSM: jenkins: STOP: The service has not been started."}                                                                                                                        
```

The failure to stop should not be treated as a failure.  It should maybe be checking that the service was running before trying to stop it.  In the above example, the service could have been removed immediately.
