### ISSUE TITLE
win_lineinfile: Functionally identical regexps are not idempotent

### ISSUE THREAD

**Issue by rleigh-codelibre** [ansible/ansible#25077]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_lineinfile

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /home/rleigh/.ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
```
hostfile = /home/rleigh/code/management_tools/ansible/inventory
roles_path = /home/rleigh/code/infrastructure/ansible/roles
allow_world_readable_tmpfiles = True
```

##### OS / ENVIRONMENT
Running ansible on Ubuntu 17.04 with Python 2.7.10.  Managed node is Windows Server 2012 x64.

##### SUMMARY
Depending upon the regular expression I use, win_lineinfile erroneously reports a *changed* status when no change occurred.

##### STEPS TO REPRODUCE

```yaml
- name: ci-base-setup (windows) | Export security policy
  win_command: "secedit /export /cfg {{ ansible_user_dir }}\\secpol.cfg"

- name: ci-base-setup (windows) | Update security policy to relax password rules and match Unix hosts
  win_lineinfile:
    dest: "{{ ansible_user_dir }}\\secpol.cfg"
    regexp: '^PasswordComplexity = 1$'
    line: 'PasswordComplexity = 0'
  register: secpol

- name: ci-base-setup (windows) | Import security policy
  win_command: "secedit /configure /db c:\\windows\\security\\local.sdb /cfg {{ ansible_user_dir }}\\secpol.cfg /areas SECURITYPOLICY"
  when: secpol.changed

- name: ci-base-setup (windows) | Delete exported security policy
  win_file:
    path: "{{ ansible_user_dir }}\\secpol.cfg"
    state: absent
```

`win_lineinfile` always reports that a change occurred with the above regular expression.

##### EXPECTED RESULTS
The `PasswordComplexity = 1` line was changed to `PasswordComplexity = 0` on the first invocation.  On following invocations, no change should have been made since the regex wouldn't match anything.

##### ACTUAL RESULTS
The status is set to changed, even when no change was made.

Trying a few different regular expressions:

```
    regexp: '^PasswordComplexity.*=.*'
    regexp: '^PasswordComplexity =.*'
```
are OK -- no change is recorded as having been made

but

```
    regexp: '^PasswordComplexity = 1'
    regexp: '^PasswordComplexity = 1$'
```

always report a change.  Maybe this is just an expectation and/or documentation issue.  Or is it matching `\r` at the line end when I use a glob but failing the match when I don't glob?  The working regexps match both the original and changed line, while the latter non-idempotent variants match only the original line.  Both cases are functionally identical in that the same input results in the same output, but is erroneously reported as being changed only for the less strict matches.  Alternatively, is a failed match being erroneously counted as a change?

From: https://github.com/ansible/ansible-modules-core/issues/3381#issuecomment-304235887

**Comment by ansibot** [comment]
cc @brianlloyd
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nwsparks** [comment]
The lineinfile module is a bit frustrating to use.

I believe this is actually functioning as intended and matches the behavior of the Linux version. If `regexp` is defined the behavior of the module is..

1. Match is found. Replace if needed and exit. If no change is needed, exit.
2. If no match is found, add `line` at default `insertafter: eof`

The reason for this is that comparison to determine if a change where a change may be required is now dependent on the regex match instead of matching `line`. So what's happening here is because your `regexp` is not changing in between runs, it is failing to match anything to replace, and defaulting to adding the line at the end of the file.

You should be able to alter this behavior by using `backrefs: yes` which will cause it to only make a change if the regexp matches:

> This flag changes the operation of the module slightly; insertbefore and insertafter will be ignored, and if the regexp doesn't match anywhere in the file, the file will be left unchanged.

I tested this with your use case and confirmed it works as expected.

````
- name: ci-base-setup (windows) | Update security policy to relax password rules and match Unix hosts
  win_lineinfile:
    dest: "{{ ansible_user_dir }}\\secpol.cfg"
    regexp: '^PasswordComplexity = 1$'
    line: 'PasswordComplexity = 0'
    backrefs: yes
  register: secpol
````

Also, the reason why the following work is that they always match any value for `PasswordComplexity`, and trigger item 1. above.

````
regexp: '^PasswordComplexity.*=.*'
regexp: '^PasswordComplexity =.*'
````
