### ISSUE TITLE
synchronize module fails with rsync

### ISSUE THREAD

**Issue by gsrigo** [ansible/ansible#25072]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
synchronize module

##### ANSIBLE VERSION
ansible 2.0.2.0

When using the synchronize module, I get several error messages regardless of how it Tery to accomplish it. Error messages are as follow:

> fatal: [host1 -> host1]: FAILED! => {"changed": false, "cmd": "/bin/rsync --delay-updates -F --compress --archive --rsh '/bin/ssh  -S none -o StrictHostKeyChecking=no' --out-format='<<CHANGED>>%i %n%L' \"/home/ansible/file1.tar.gz\" \"/var/lib/awx/projects/host_test/buntu1:/home/ansible/\"", "failed": true, "msg": "rsync: mkdir \"/var/lib/awx/projects/host_test/buntu1:/home/ansible\" failed: No such file or directory (2)\nrsync error: error in file IO (code 11) at main.c(587) [Receiver=3.0.9]\nrsync: connection unexpectedly closed (9 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]\n", "rc": 12}

or this one:

> ... to the list of known hosts.\r\nrsync: change_dir \"/home/ansible\" failed: Operation not permitted (1)\nrsync: mkdir \"/home/ansible/buntu1:/home/ansible\" failed: No such file or directory (2)\nrsync error: error in file IO (code 11) at main.c(587) [Receiver=3.0.9]\nrsync: connection unexpectedly closed (9 bytes received so far) [sender]\nrsync error: error in rsync protocol data stream (code 12) at io.c(600) [sender=3.0.6]\n", "rc": 12}

The part that fails is in here
```
  - name: get necessary files
    synchronize:
      src: /home/ansible/file1.tar.gz
      dest: buntu1:/home/ansible/
#      dest: rsync://buntu1
    delegate_to: host1
```

**Comment by ansibot** [comment]
@gsrigo Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
cc @jctanner

**Comment by jctanner** [comment]
@gsrigo please provide an example playbook + inventory. We also need to know which machine is the control host and which hosts should be sending/receiving files.

needs_info

**Comment by ansibot** [comment]
cc @tima
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mike-pt** [comment]
I'm seeing a similar issue when trying to download a file from a "remote_hostC"

This would be the task:
```
 - name: rsync database from DB SERVER
      synchronize:
        mode: pull
        src: rsync://user@IP_ADDRESS:"'/data/Some Path /database.db'"
        dest: /tmp/
        checksum: yes
        use_ssh_args: yes
      delegate_to: "{{ inventory_hostname }}" 
      when: ansible_os_family == "Darwin"
```

The target host (hostB) is the same as the controller (hostA) in this case, I'm unsure if I really need the delage_to in such case, but since it might not be the case when this goes in prod I though it best to have it delagate to `hostB`.

the issue seems to be that  `hostC`doesn't allow the rsync connection (and I can't use sudo in this particular case).

So I tried to use "-e ssh" and still fails....

removing "rsync://" from path means it will no longer use a absolute path but a relative one in respect to the dir I'm running this from :| 


>fatal: [127.0.0.1 -> 127.0.0.1]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --checksum --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -C -o ControlMaster=auto -o ControlPersist=60s --out-format=<<CHANGED>>%i %n%L /Users/user/automation/ansible/ansible/user@IP_ADDRESS:\"'//data/Some Path /database.db'\" /tmp/", "failed": true, "msg": "rsync: link_stat \"/Users/user/automation/ansible/ansible/user@IP_ADDRESS:\"'//data/Some Path /database.db'\"\" failed: No such file or directory (2)\nrsync error: some files could not be transferred (code 23) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/rsync/rsync-52/rsync/main.c(996) [sender=2.6.9]\n", "rc": 23}



So it seem only when using rsync:// is the path consider remote and absolute, is this intended or a bug?


I tested locally by just using rsync normally and if I don't specify "rsync://" it works just fine, i.e:

```
rsync -avrh user@IP_ADDRESS:"'/data/Some Path /database.db'" /tmp/
receiving file list ... done
database.db
````

**Comment by mike-pt** [comment]
To clarify the comment above the "bug" would be that that path becomes relative even when the "host:" format is used...  but this could also be a feature request maybe?

rsync supports ssh/rsh or using the rsync daemon, it seems that ansible only accepts the "rsync://" option, I tested the `::` format and that still converts the path to a relative one in respect to the dir I'm running this from.

which make me thing that this might be more of a FR than bug.

**Comment by mike-pt** [comment]
Just found #17492 which seems to indicate there's a bug here even when using "rsync://"

**Comment by ansibotdev** [comment]
@gsrigo You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ThoTischner** [comment]
Issue still there..

##### SUMMARY
Ansible synchronize not working with rsync:// dest or src

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
synchronize_module

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/tti/nm-ansible/ansible.cfg
  configured module search path = [u'/home/tti/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/home/tti/nm-ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_ROLES_PATH(/home/tti/nm-ansible/ansible.cfg) = [u'/home/tti/nm-ansible/roles']
DEFAULT_SCP_IF_SSH(/home/tti/nm-ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/tti/nm-ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
- hosts: "{{hosts|default('*')}}"
  gather_facts: false
  tasks:
    - name: Rsync files from remote to remote hosts
      synchronize:
        src: /tmp
        dest: 'rsync://bla.blub.com/tmp/'
        rsync_opts: "{{sync_rsync_opts|default(omit)}}"
      delegate_to: "{{inventory_hostname}}"
```


##### EXPECTED RESULTS
working

##### ACTUAL RESULTS
```
fatal: [vmxxx.xxxx.lan -> vmxxxxxxxxx.lan]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --out-format=<<CHANGED>>%i %n%L /tmp/xxx.sql rsync://vmxxx.xxxx.lan/tmp/xxx.sql", "msg": "@ERROR: Unknown module 'tmp'\nrsync error: error starting client-server protocol (code 5) at main.c(1516) [sender=3.0.9]\n", "rc": 5}
```
