### ISSUE TITLE
Allow creation/deletion of chains the 'iptables' module

### ISSUE THREAD

**Issue by aklemp** [ansible/ansible#25099]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
iptables

##### ANSIBLE VERSION
```
ansible 2.3.0.0 (stable-2.3 4b5553c97f) last updated 2017/04/23 13:15:41 (GMT +200)
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Mar  1 2015, 12:57:24) [GCC 4.9.2]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I propose to extend the iptables module to allow creation and deletion of chains. The following are samples of the commands that should be supported for both ipv4 and ipv6 (the `ip_version` is omitted for simplicity). The `table` parameter is optional and default to `filter`.

* deleting a single chain
  ```
  iptables [-t mytable] -X mychain
  ```
  would become
  ```
  iptables:
    chain: mychain
    table: mytable
    state: absent
  ```
* deleting all chains
  ```
  iptables [-t mytable] -X
  ```
  would become
  ```
  iptables:
    table: mytable
    state: absent
  ```
* adding a chain
  ```
  iptables [-t mytable] -N mychain
  ```
  would become
  ```
  iptables:
    chain: mychain
    table: mytable
    state: present
  ```

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by ansibot** [comment]
cc @LinusU
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by LinusU** [comment]
Sounds like a good idea 👍

**Comment by ansibot** [comment]
cc @sebastiendarocha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by czerasz** [comment]
I also run also into this issue:

```bash
iptables: No chain/target/match by that name.
```

I solved it by creating the chain manually:

```yaml
- name: Create the MYSQL_FIREWALL chain
  shell: iptables --new-chain MYSQL_FIREWALL
  # Don't fail 
  ignore_errors: yes
```

**Comment by george-oniceag** [comment]
I would also appreciate this feature in the module !

**Comment by gundalow** [comment]
@czerasz @george-oniceag Does https://github.com/ansible/ansible/pull/32158 solve this for you?

resolved_by_pr: 32158

**Comment by maab** [comment]
Another workaround:

```yml
- name: Create REJECTRECENT chain
  shell: 'iptables -L REJECTRECENT || iptables -N REJECTRECENT'
  register: rejectrecent_chain
  changed_when: "'No chain/target/match by that name' in rejectrecent_chain.stderr"
```
