### ISSUE TITLE
The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available

### ISSUE THREAD

**Issue by minherz** [ansible/ansible#25108]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`azure_rm_deployment` module

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Default ansible configuration

##### OS / ENVIRONMENT

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial
```
Azure package version is 2.0.0rc5 as it explained in issue #24926
```
$ az --version
azure-cli (2.0.6)

acr (2.0.4)
acs (2.0.6)
appservice (0.1.6)
batch (2.0.4)
cdn (0.0.2)
cloud (2.0.2)
cognitiveservices (0.1.2)
command-modules-nspkg (2.0.0)
component (2.0.4)
configure (2.0.6)
core (2.0.6)
cosmosdb (0.1.6)
dla (0.0.6)
dls (0.0.6)
feedback (2.0.2)
find (0.2.2)
interactive (0.3.2)
iot (0.1.5)
keyvault (2.0.4)
lab (0.0.4)
monitor (0.0.4)
network (2.0.6)
nspkg (3.0.0)
profile (2.0.4)
rdbms (0.0.1)
redis (0.2.3)
resource (2.0.6)
role (2.0.4)
sf (1.0.1)
sql (2.0.3)
storage (2.0.6)
vm (2.0.6)

Python (Linux) 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609]

Python location '/home/medcon/lib/azure-cli/bin/python'
```

##### SUMMARY
Attempt to deploy a template of the Kubernetes ACS using the module fails due inability to create Windows agents with error
`The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available`
It seems like the template execution using azure-sdk-for-python uses either incorrect or incorrectly formatted image info for Windows nodes which results in setup failure.

##### STEPS TO REPRODUCE

1. Create Kubernetes ACS on Azure with 1 master node and 2 Windows OS agents
2. Open a new created resource group and select 1 Succeeded link under "Deployments" label in the top of the resource group window (above the list of items
3. Select the single deployment item from the new opened window
4. Select "View Template" button in the top toolbar in the Deployment window
5. Select "Download" button in the top toolbar in the Template window
6. Delete the resource group and wait until the process is completed
7. Place template to github or another location (no support for local files as it was explained in issue #25024)

```
---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Deploy static K8S ACS
      azure_rm_deployment:
        state: present
        location: eastus
        subscription_id: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        resource_group_name: ansible_deployment_test1
        deployment_name: k8s_auto1
        deployment_mode: complete
        wait_for_deployment_completion: false
        template_link: PLACE URL TO TEMPLATE JSON
        parameters:
          masterDnsNamePrefix:
            value: k8sdepl1mgmt
          agentDnsNamePrefix:
            value: k8sdepl1agents
          agentCount:
            value: 2
          agentVMSize:
            value: Standard_DS2
          linuxAdminUsername:
            value: 'medcon'
          windowsAgentAdminUsername:
            value: 'medcon'
          windowsAgentAdminPassword:
            value: 'simplePassword123$'
          masterCount:
            value: 1
          sshRSAPublicKey:
            value: PLACE PUBLIC SSH KEY
          osType:
            value: Windows
        tenant: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        client_id: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        secret: xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

##### EXPECTED RESULTS
Instance of the Kubernetes ACS will be created according to the template.

##### ACTUAL RESULTS
Executing ansible playbook (above) results in the following error output:

```
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /home/medcon/.local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: deploy_acs.yaml *******************************************************************************************************************************************************************************************************************
1 plays in playbooks/deploy_acs.yaml

PLAY [localhost] ****************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Deploy static K8S ACS] ****************************************************************************************************************************************************************************************************************
task path: /home/medcon/ansible/playbooks/deploy_acs.yaml:6
Using module file /home/medcon/.local/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_deployment.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: medcon
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/medcon/.ansible/tmp/ansible-tmp-1495971843.97-230940408225126 `" && echo ansible-tmp-1495971843.97-230940408225126="` echo /home/medcon/.ansible/tmp/ansible-tmp-1495971843.97-230940408225126 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpv1mNcU TO /home/medcon/.ansible/tmp/ansible-tmp-1495971843.97-230940408225126/azure_rm_deployment.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/medcon/.ansible/tmp/ansible-tmp-1495971843.97-230940408225126/ /home/medcon/.ansible/tmp/ansible-tmp-1495971843.97-230940408225126/azure_rm_deployment.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/medcon/.ansible/tmp/ansible-tmp-1495971843.97-230940408225126/azure_rm_deployment.py; rm -rf "/home/medcon/.ansible/tmp/ansible-tmp-1495971843.97-230940408225126/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "failed_deployment_operations": [
        {
            "id": "/subscriptions/********/resourceGroups/ansible_deployment_test1/providers/Microsoft.Resources/deployments/k8s_auto1/operations/F0630E1F23CDB2F4", 
            "operation_id": "F0630E1F23CDB2F4", 
            "provisioning_state": "Failed", 
            "status_code": "Conflict", 
            "status_message": {
                "error": {
                    "code": "ResourceDeploymentFailure", 
                    "details": [
                        {
                            "code": "ProvisioningFailed", 
                            "message": "Provisioning of resource(s) for container service 'containerservice-ansible_deployment_test1' in resource group 'ansible_deployment_test1' failed with errors: Resource type: Microsoft.Compute/virtualMachines, name: 9443Aacs9000, id: /subscriptions/********/resourceGroups/ansible_deployment_test1/providers/Microsoft.Compute/virtualMachines/9443Aacs9000, StatusCode: NotFound, StatusMessage: \\n {\r\n  \"error\": {\r\n    \"code\": \"ImageNotFound\",\r\n    \"target\": \"imageReference\",\r\n    \"message\": \"The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available. Verify that all fields in the storage profile are correct.\"\r\n  }\r\n}\r\nResource type: Microsoft.Compute/virtualMachines, name: 9443Aacs9001, id: /subscriptions/********/resourceGroups/ansible_deployment_test1/providers/Microsoft.Compute/virtualMachines/9443Aacs9001, StatusCode: NotFound, StatusMessage: \\n {\r\n  \"error\": {\r\n    \"code\": \"ImageNotFound\",\r\n    \"target\": \"imageReference\",\r\n    \"message\": \"The platform image 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter-with-Containers:2016.0.20170127' is not available. Verify that all fields in the storage profile are correct.\"\r\n  }\r\n}\r\n"
                        }
                    ], 
                    "message": "The resource operation completed with terminal provisioning state 'Failed'."
                }, 
                "status": "Failed"
            }, 
            "target_resource": {
                "id": "/subscriptions/********/resourceGroups/ansible_deployment_test1/providers/Microsoft.ContainerService/containerServices/containerservice-ansible_deployment_test1", 
                "resource_name": "containerservice-ansible_deployment_test1", 
                "resource_type": "Microsoft.ContainerService/containerServices"
            }
        }, 
        {
            "id": "/subscriptions/********/resourceGroups/ansible_deployment_test1/providers/Microsoft.Resources/deployments/k8s_auto1/operations/08587056350401160216", 
            "operation_id": "08587056350401160216", 
            "provisioning_state": "Failed", 
            "status_code": "Conflict", 
            "status_message": "Template output evaluation skipped: at least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.", 
            "target_resource": null
        }
    ], 
    "invocation": {
        "module_args": {
            "ad_user": null, 
            "append_tags": true, 
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "deployment_mode": "complete", 
            "deployment_name": "k8s_auto1", 
            "location": "eastus", 
            "parameters": {
                "agentCount": {
                    "value": 2
                }, 
                "agentDnsNamePrefix": {
                    "value": "k8sdepl1agents"
                }, 
                "agentVMSize": {
                    "value": "Standard_DS2"
                }, 
                "linuxAdminUsername": {
                    "value": "medcon"
                }, 
                "masterCount": {
                    "value": 1
                }, 
                "masterDnsNamePrefix": {
                    "value": "k8sdepl1mgmt"
                }, 
                "osType": {
                    "value": "Windows"
                }, 
                "sshRSAPublicKey": {
                    "value": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABACABAQCvGAKveft0Y9T5AI2OTdptTsNsVhaNjYmuP3KSCfcGDOEBSRaKcwvob/wYaXmXBzamO2DXMYNuYOVqjmF5PgBChTFukgLKRuXTukmbk7iczKa7LQLH5644Tzzhf2j5SfwV7NVpbvWOn1UWU2gKSVUKxYfKcAQWbr2NMcj5PO4laNvW34oUdJ00xe3yFiiF1ruK1mEpxcVDfdCAuliJ5PV5Ds+pEM8I6o1f/nZ64Ijb9tFa9AtFDEQ8lqaaAb8HB6xrXqaBZe1b6Jh4+7nDTy8jIQqHgg4HT2vPGphQ1Zcysbr3CC1hWRnGEf80KlSgx1cPKqbyb+yMgrJ+ZCMWwRq9"
                }, 
                "windowsAgentAdminPassword": {
                    "value": "simplePassword123$"
                }, 
                "windowsAgentAdminUsername": {
                    "value": "medcon"
                }
            }, 
            "parameters_link": null, 
            "password": null, 
            "profile": null, 
            "resource_group_name": "ansible_deployment_test1", 
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "present", 
            "subscription_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "tags": null, 
            "template": null, 
            "template_link": "https://raw.githubusercontent.com/minherz/ansible-configurations/master/files/template.json", 
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "wait_for_deployment_completion": false, 
            "wait_for_deployment_polling_period": 10
        }
    }, 
    "msg": "Deployment failed with status code: 200 and message: The deployment operation failed, because it was unable to cleanup. Please see https://aka.ms/arm-debug for usage details."
}
	to retry, use: --limit @/home/medcon/ansible/playbooks/deploy_acs.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
