### ISSUE TITLE
 azure_rm_virtualmachine missing Microsoft.Compute/virtualMachines/extensions Support

### ISSUE THREAD

**Issue by barroei** [ansible/ansible#25109]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine 

##### ANSIBLE VERSION

ansible 2.2.1.0
  config file = /home/mckadmin/cmdemomachines/ansible.cfg
  configured module search path = Default w/o overrides

##### CONFIGURATION
[defaults]
inventory = inventory.yml

##### OS / ENVIRONMENT

OS is UBuntu Linux Based

##### SUMMARY
as part of Azure VM Deployment, it is needed to enable WinRM Features, as Such there is an Option to run Post Deployment Commands via "Microsoft.Compute/virtualMachines/extensions"

however those are not available through the " azure_rm_virtualmachine" forcing to move to the  azure_rm_deployment module as a workaround, which moves logic into Template, and get you out of Ansible context

##### STEPS TO REPRODUCE

Install Windows Based System, and Try to Run another Playbook as next phase for system Configurations, if WINRM is not configured it will fail. 

```
- name: CREATE VM PLAYBOOK
  hosts: localhost
  connection: local
  gather_facts: False
  vars:
    # vmname: josetestansible03
    # resgrp: PermanentLab
    # vnet: PermanentLab-vnet
    # Variables 'vnet', 'subnet', 'vmname' and 'resgrp' need to be provided at command line with arg --extra-vars
    dnsname: '{{ vmname }}.{{ location }}.cloudapp.azure.com'
    # The DNS name might not be right depending on your region!!
    ip: "{{ lookup ('dig', '{{ dnsname }}') }}"
   
  tasks:
  - debug: msg="Public DNS name {{ dnsname }} resolved to IP {{ ip }}. "
  - name: Check if DNS is taken
    fail: msg="That DNS name seems to be already taken"
    when: ip != 'NXDOMAIN'
  - name: Create public IP address
    azure_rm_publicipaddress: 
      resource_group: '{{ resgrp }}'
      allocation_method: Static 
      name: '{{ vmname }}'
      domain_name_label: '{{ vmname }}'
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      virtual_network: '{{ vnet }}'
      subnet: '{{ subnet }}'
      public_ip_name: '{{ vmname }}'
      private_ip_address: '{{ host }}'
      private_ip_allocation_method: Static
      security_group: '{{ vmname }}'
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: '{{ resgrp }}'
      name: '{{ vmname }}'
      storage_account: '{{ storageaccount }}'
      storage_container: '{{ vmname }}'
      storage_blob: '{{ vmname }}.vhd'
      network_interfaces: '{{ vmname }}'
      vm_size: Standard_A0
      admin_username: sampleAAA
      admin_password: sampleAAA
      image:
        offer: WindowsServer
        publisher: MicrosoftWindowsServer
        sku: '2016-Datacenter'
        version: latest
```

##### EXPECTED RESULTS

this is the platform Build Script, but next phase is to run Windows Configuration, which is failing due to lack of support on WinRM Basic.
##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @haroldwongms @tstringer @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
cc @nitzmahone

**Comment by ansibot** [comment]
cc @chouseknecht
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @xscript @yaweiw @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
This can be done by using the `azure_rm_virtualmachine_extension` module. I've used the below to build a Windows server and then setup WinRM once it is built

```
# Below is UTF-16 Base64 encoding for:
#   Invoke-Expression -Command ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1')); Enable-WSManCredSSP -Role Server -Force
# A UTF-16 Base64 encoded script is used so we don't have to escape any
# characters that may cause issues
- name: set fact for Extension Code
  set_fact:
    winrm_enable_script: SQBuAHYAbwBrAGUALQBFAHgAcAByAGUAcwBzAGkAbwBuACAALQBDAG8AbQBtAGEAbgBkACAAKAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAKQAuAEQAbwB3AG4AbABvAGEAZABTAHQAcgBpAG4AZwAoACcAaAB0AHQAcABzADoALwAvAHIAYQB3AC4AZwBpAHQAaAB1AGIAdQBzAGUAcgBjAG8AbgB0AGUAbgB0AC4AYwBvAG0ALwBhAG4AcwBpAGIAbABlAC8AYQBuAHMAaQBiAGwAZQAvAGQAZQB2AGUAbAAvAGUAeABhAG0AcABsAGUAcwAvAHMAYwByAGkAcAB0AHMALwBDAG8AbgBmAGkAZwB1AHIAZQBSAGUAbQBvAHQAaQBuAGcARgBvAHIAQQBuAHMAaQBiAGwAZQAuAHAAcwAxACcAKQApADsAIABFAG4AYQBiAGwAZQAtAFcAUwBNAGEAbgBDAHIAZQBkAFMAUwBQACAALQBSAG8AbABlACAAUwBlAHIAdgBlAHIAIAAtAEYAbwByAGMAZQA=

- name: provision new Azure virtual host
  azure_rm_virtualmachine:
    os_type: Windows
    image:
      offer: WindowsServer
      publisher: MicrosoftWindowsServer
      sku: 2016-Datacenter
      version: latest
    name: TestVM01
    resource_group: TestRG01
    state: present

- name: create Azure vm extension to enable HTTPS WinRM listener
  azure_rm_virtualmachine_extension:
    name: winrm-extension
    resource_group: TestRG01
    virtual_machine_name: TestVM01
    publisher: Microsoft.Compute
    virtual_machine_extension_type: CustomScriptExtension
    type_handler_version: 1.9
    settings: '{"commandToExecute": "powershell.exe -ExecutionPolicy ByPass -EncodedCommand {{winrm_enable_script}}"}'
    auto_upgrade_minor_version: true

- name: wait for the WinRM port to come online
  wait_for:
    port: 5986
    host: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress}}'
    timeout: 600
```

I believe separating them into different modules is done on purpose as we don't want to have another `ec2` module that does everything and is now a complex beast.
