### ISSUE TITLE
authorized_key tries to create /root/.ssh/ even tho it exists and manage_dir is 'no'

### ISSUE THREAD

**Issue by simbalion** [ansible/ansible#25117]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
auhtorized_key

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

```

##### SUMMARY

I created a small playbook to install ssh keys in a number of user accounts. It works but not for the root user, who keeps getting 'permission denied' trying to create /root/.ssh/

##### STEPS TO REPRODUCE

```yaml
- hosts: groupname
  remote_user: root
  tasks:
  - name: add key
    authorized_key:
      user: '{{ item }}'
      key: "{{ lookup('file', '/home/me/.ssh/keyname.pub') }}"
      state: present
      manage_dir: no
    with_items:
      - root
      - username
```

##### ACTUAL RESULTS

```
failed: [hostname.com] (item=root) => {"failed": true, "item": "root", "module_stderr": "Shared connection to hostname.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_DiHEw8/ansible_module_authorized_key.py\", line 660, in <module>\r\n    main()\r\n  File \"/tmp/ansible_DiHEw8/ansible_module_authorized_key.py\", line 656, in main\r\n    results = enforce_state(module, module.params)\r\n  File \"/tmp/ansible_DiHEw8/ansible_module_authorized_key.py\", line 621, in enforce_state\r\n    filename = keyfile(module, user, do_write, path, manage_dir)\r\n  File \"/tmp/ansible_DiHEw8/ansible_module_authorized_key.py\", line 340, in keyfile\r\n    os.mkdir(sshdir, int('0700', 8))\r\nOSError: [Errno 13] Permission denied: '/root/.ssh'\r\n", "msg": "MODULE FAILURE", "rc": 0}
```

```

```
