### ISSUE TITLE
1603 returned when running win_chocolatey

### ISSUE THREAD

**Issue by rutkowskii** [ansible/ansible#25114]
##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### COMPONENT NAME
win_chocolatey, trying to install Visual Studio 2015 community edition (https://chocolatey.org/packages/VisualStudio2015Community)

##### Environment
Running win_chocolatey against an agent with Windows 2012 R2 Standard

##### STEPS TO REPRODUCE
Trying to install Visual Studio Community 2015 the following way:
```
  - name: Install 7zip
    hosts: all
    gather_facts: false
    tasks:
      - name: Install 7zip
        win_chocolatey:
          name: 7zip.install
          state: present
  - name: Install Visual Studio
    hosts: all
    gather_facts: false
    tasks:
      - name: Install Visual Studio
        win_chocolatey:
          name: visualstudio2015community
          state: present
```

##### ACTUAL RESULTS
Output when running the playbook:
```
PLAY [Install 7zip] *****************************************************************************************************

TASK [Install 7zip] *****************************************************************************************************
ok: [10.2.75.156]

PLAY [Install Visual Studio] ********************************************************************************************

TASK [Install Visual Studio] ********************************************************************************************
fatal: [10.2.75.156]: FAILED! => {"changed": false, "choco_error_cmd": "choco.exe install -dv -y visualstudio2015community -timeout 2700", "choco_error_log": null, "failed": true, "msg": "Error installing visualstudio2015community", "rc": 1603}
        to retry, use: --limit @/etc/ansible/plays/main.retry
```
Visual Studio is visible in Programs list in control panel, although most of components (eg. MsBuild are not installed). 
Link to installation log:
https://www.dropbox.com/s/14jd2obrh6ifnye/dd_vs_community_20170528192409.log?dl=0

7zip, showed in a config, is installed with no problems. 
Installing Visual Studio running chocolatey at the target machine (running chocolatey command from the output above, from powershell with elevated privileges), works as well.
