### ISSUE TITLE
Module: nxos_nxapi - disabling http does not get pushed to devices

### ISSUE THREAD

**Issue by jchristopher327** [ansible/ansible#25137]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_nxapi
##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

Running ansible on: CentOS Linux release 7.3.1611 (Core) 
Managing: C9236C, 93180YC-EX running 7.0.3.I5.2
##### SUMMARY

I'm running a playbook to configure nxapi with https (and port) and to disable http. The command to disable http does not get sent to the device, which leaves http enabled. I've tried using the alias `enable_http: false` and `http: no`.
##### STEPS TO REPRODUCE

```
---
- hosts: lab
  connection: local
  gather_facts: no

   - name: Configure nxapi
     nxos_nxapi:
      https: yes
      https_port: 8443
      http: False
```

##### EXPECTED RESULTS

The playbook should push the following confing to devices `no nxapi http`.
##### ACTUAL RESULTS

The `no nxapi http` is not sent to the device.

```
changed: [172.19.154.12] => {
    "changed": true, 
    "commands": [
        "nxapi https port 8443"
    ], 
    "invocation": {
        "module_args": {
            "config": null, 
            "host": null, 
            "http": false, 
            "http_port": null, 
            "https": true, 
            "https_port": 8443, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "sandbox": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}
changed: [172.19.154.22] => {
    "changed": true, 
    "commands": [
        "nxapi https port 8443"
    ], 
    "invocation": {
        "module_args": {
            "config": null, 
            "host": null, 
            "http": false, 
            "http_port": null, 
            "https": true, 
            "https_port": 8443, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "sandbox": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}
```

**Comment by ansibot** [comment]
cc @jedelman8 @GGabriele @rahushen @privateip @rcarrillocruz @mikewiebe @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jchristopher327** [comment]
It looks like trying disabling https also has the same issue.
```
---
- hosts: lab
  connection: local
  gather_facts: no

   - name: Configure nxapi
     nxos_nxapi:
      https: False
      #https_port: 8443
      http: False
```
```
ok: [172.19.154.22] => {
    "changed": false, 
    "commands": [], 
    "invocation": {
        "module_args": {
            "config": null, 
            "host": null, 
            "http": false, 
            "http_port": null, 
            "https": false, 
            "https_port": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "sandbox": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}
ok: [172.19.154.12] => {
    "changed": false, 
    "commands": [], 
    "invocation": {
        "module_args": {
            "config": null, 
            "host": null, 
            "http": false, 
            "http_port": null, 
            "https": false, 
            "https_port": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "sandbox": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}
```

**Comment by Qalthos** [comment]
Okay, I've looked into this and I just can't reproduce the issue. Can you send the output of `show nxapi` before and after the playbooks are run?

**Comment by jchristopher327** [comment]
Hi @Qalthos, I disabled the nxapi feature and ran the playbook again. 
Below is the playbook to enable the feature and then configure it with HTTPS (8443) enabled and HTTP disabled. Notice the commented out `no nxapi` under the nxos_config task. This was done to actually have HTTP disabled.
```
---
- hosts: lab
  connection: local
  gather_facts: no
 
  tasks:
   - name: Enable nxapi feature
     nxos_feature:
      feature: nxapi
      state: enabled
   - name: Configure nxapi
     nxos_nxapi:
      state: present
      http: False
      https: True
      https_port: 8443
   - name: Configure certificate for nxapi
     nxos_config:
      lines:
       - nxapi certificate httpscrt certfile bootflash:///xxxxx.crt
       - nxapi certificate httpskey keyfile bootflash:///xxxxx.key
       - nxapi certificate enable
       #- no nxapi http 
      save: yes
```
Disable the feature prior to running playbook
```
evpn-leaf-1(config)# no feature nxapi 
evpn-leaf-1(config)# 
evpn-leaf-1(config)# end
evpn-leaf-1# show nxapi 
                   ^
% Invalid command at '^' marker.
```
Playbook debug. The HTTP key is showing as false but there is no command being sent to disable it.
```
changed: [172.19.154.11] => {
    "changed": true, 
    "commands": [
        "nxapi https port 8443"
    ], 
    "invocation": {
        "module_args": {
            "config": null, 
            "host": null, 
            "http": false, 
            "http_port": null, 
            "https": true, 
            "https_port": 8443, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "sandbox": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}
```
Results after the playbook is ran.
```
evpn-leaf-1# show nxapi 
nxapi enabled
HTTP Listen on port 80
HTTPS Listen on port 8443
```
