### ISSUE TITLE
Ansible not reading shell/bash executable paths properly

### ISSUE THREAD

**Issue by yabhinav** [ansible/ansible#25147]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
```
ansible --version
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
RedHAT 6.6

##### SUMMARY
Unable to use service module because initctl commands fail

##### STEPS TO REPRODUCE
```yaml
- name: Restart ambari-agent
   service: name=ambari-agent state=restarted enabled=yes sleep=10 
```

##### EXPECTED RESULTS
 [testlab]: => {"changed": true, enabled:yes, started:yes}

##### ACTUAL RESULTS
```
fatal: [testlab]: FAILED! => {"changed": false, "cmd": "initctl version", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```

##### Work around

```yaml
- block:
      - name: Restart ambari-agent
        service: name=ambari-agent state=restarted enabled=yes sleep=10 #init script exiting immediately
        when: agentconfig.changed
  rescue:
      # Ambari Init Scripts don't follow proper LSB Standards and hence causing issues
      - name: Ensure ambari-agent is running and enabled at reboot
        shell:  /etc/init.d/ambari-agent restart  && /sbin/chkconfig ambari-agent on
        register: agentstart
        changed_when: "'Ambari Agent successfully started' in agentstart.stdout "
  become: True
```

As you can see all module like shell , service , command and script need absolute path to programs that are not in /usr/bin. The issue might be ansible is not reading  programs from  /sbin/ , /usr/sbin/ etc .. and adding them to the shell path.

Is there are property to make ansible read all shell paths ?

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

In any case, it is probably that the path is being set for interactive shells but not for batch shells/logins, which is what Ansible uses.

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by yabhinav** [comment]
Ansible Env  ansible_env.PATH doesn't load path properly and hence need to add /sbin/ for initctl to be read by module

```yaml

- name: Restart ambari-agent
   service: name=ambari-agent state=restarted enabled=yes sleep=10 
   environment: 
        PATH: "{{ ansible_env.PATH}}:/sbin:/usr/sbin"

```
