### ISSUE TITLE
iptables: setting chain policy is not idempotent

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [ansible/ansible#25153]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
iptables

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /Users/valkra/code/ansible-config/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) \
    [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT

Running ansible on MacOS Sierra 12.12.3 (probably irrelevant), and managing Ubuntu 16.04 (kernel: 4.4.0-62-generic)

##### SUMMARY

Using the `iptables` module to set policies on built in chains always returns `changed`, is hence not idempotent.

##### STEPS TO REPRODUCE

Run the following playbook twice on any host with iptables, substituting the hostname appropriately.

```yaml
---
- hosts: myhost.local
  tasks:
  - name: set output policy to accept
    iptables:
      chain: OUTPUT
      policy: ACCEPT
    become: yes
```

##### EXPECTED RESULTS

Should report OK at least on the second run.

##### ACTUAL RESULTS

```
PLAY [myhost.local] ***********************

TASK [Gathering Facts] *********************
ok: [myhost.local]

TASK [set output policy to accept] ***********************
changed: [myhost.local]

PLAY RECAP *****************
myhost.local         : ok=2    changed=1    unreachable=0    failed=0
```
