### ISSUE TITLE
[python3] pip failed to create virtual env when using custom command (pyvenv)

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#25151]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module/pip

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /Users/jddupas/Projects/python/playbooks/app/ansible.cfg
  configured module search path = ['/Users/jddupas/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jddupas/Projects/python/playbooks/env/lib/python3.5/site-packages/ansible
  executable location = /Users/jddupas/Projects/python/playbooks/env/bin/ansible
  python version = 3.5.3 (default, Apr 23 2017, 18:09:27) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I'm trying to create a virtual env on Ubuntu. The target system don't have Python 2 installed, so it don't have the virtualenv package installed (it requires python2). 
To avoid having to install unnecessary dependencies, I want to use the pyenv command to create the virtual env. Unfortunately, when running in python3 mode, the pip module unconditionally append a '-p' argument to the command line to execute and pyenv neither support nor need that argument.

So the command execution fails with an unrecognized argument error.

Note that the execution also fail with python2 if the `virtualenv_python` parameter is specified.

##### STEPS TO REPRODUCE

```yaml
  - name: Create virtual env
    with_items: [ setuptools, pip ]
    pip:
      name: "{{ item }}"
      state: latest
      virtualenv: "venv"
      virtualenv_command: pyvenv
```

##### EXPECTED RESULTS
Execution of the playbook succeed

##### ACTUAL RESULTS
Execution fails because pyenv does not recognize the -p parameter.
