### ISSUE TITLE
mysql_user column privileges always changed

### ISSUE THREAD

**Issue by aurimasl** [ansible/ansible#25158]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`mysql_user` module
##### ANSIBLE VERSION

```
2.3.0.0
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using `mysql_user` with more than one column permissions in `priv` argument, task is always marked as changed. Columns are sorted in some strange way, that this module always sees a difference between existing user permissions and those in playbook.

It's ok when there is only one column or columns are not mentioned at all.

##### STEPS TO REPRODUCE

Database:
```sql
CREATE DATABASE test_db;
CREATE TABLE test_table (
  col1 integer,
  col2 integer,
  col3 integer
);
```

```yaml
- name: Add user with column permissions
  mysql_user:
    name: user
    password: password
    priv: test_db.test_table:SELECT (COL1, COL2)
    host: localhost
```

##### EXPECTED RESULTS

Task should not change permissions and be marked `ok` when ran several times.
##### ACTUAL RESULTS

Task is always marked as `changed`:
```
       TASK [hostinger-apidb : Add user with column permissions] **********************
       Tuesday 30 May 2017  10:22:59 +0000 (0:00:00.099)       0:00:01.929 ***********
       changed: [lt-office-web1.hostinger.io] => {"changed": true, "user": "user"}
```
```
MariaDB [test_db]> show grants for 'user'@'localhost';
+-------------------------------------------------------------------------------------------------------------+
| Grants for user@localhost                                                                                   |
+-------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'user'@'localhost' IDENTIFIED BY PASSWORD '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' |
| GRANT SELECT (COL2, COL1) ON `test_db`.`test_table` TO 'user'@'localhost'                                   |
+-------------------------------------------------------------------------------------------------------------+
```

When columns are swapped to match `show grants` output in ansible task - MariaDB permissions are changed and they mismatch again.

```yaml
- name: Add user with column permissions
  mysql_user:
    name: user
    password: password
    priv: test_db.test_table:SELECT (COL2, COL1)
    host: localhost
```
```
MariaDB [test_db]> show grants for 'user'@'localhost';
+-------------------------------------------------------------------------------------------------------------+
| Grants for user@localhost                                                                                   |
+-------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'user'@'localhost' IDENTIFIED BY PASSWORD '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' |
| GRANT SELECT (COL1, COL2) ON `test_db`.`test_table` TO 'user'@'localhost'                                   |
+-------------------------------------------------------------------------------------------------------------+
```
