### ISSUE TITLE
task can no longer find variable set in previous task within same role

### ISSUE THREAD

**Issue by EvertMDC** [ansible/ansible#25167]
There where some issues that touched the same type of problem but they are more specific to logic that is not used here.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include_vars

##### ANSIBLE VERSION

```
ansible 2.2.3.0
  config file = /Users/evert/git/infrastructure/ansible.cfg
  configured module search path = ['./library', '../other_repo/ansible/library/']
```

##### OS / ENVIRONMENT

Running on Mac OS X 10.12.5, managing a aws ec2 ubuntu 16.04 instance

##### SUMMARY
This playbook was working before, is under version control and has not been touched since the last run.
I had upgraded to Ansible 2.3.0.0, had some issues with a few modules and downgraded back to 2.2.3.0
Issues have started once I upgraded. Since the downgrade did not work it might have something to do with one of Ansible's dependencies?

##### STEPS TO REPRODUCE

```yaml
- name: Include vars of vault.yml
  include_vars:
    file: vault.yml
    name: vault
  #no_log: True

- name: debug vault variable
  debug:
    var: vault

- name: Create the users
  user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    state: present
    groups: "{{ item.groups }}"
    shell: "{{ item.shell }}"
  become: yes
  become_user: root
  with_items: "{{ vault.users }}"
```

##### EXPECTED RESULTS
I would have expected that a variable set in a task would be accessible to the remaining tasks in the same role.

##### ACTUAL RESULTS
Ansible complains that there is no variable with that name, although it was set in the same role.

```
TASK [role_create_user_environment : Include vars of vault.yml] ****************
task path: /Users/evert/git/infrastructure/roles/role_create_user_environment/tasks/main.yml:2
ok: [localhost -> None] => {
    "ansible_facts": {
        "vault": {
            "dockerlogins": [
                {
                    "name": "user1",
                    "password": "password"
                },
                {
                    "name": "user2",
                    "password": "password"
                }
            ],
            "users": [
                {
                    "groups": "adm,sudo,docker",
                    "name": "user2",
                    "password": "hash",
                    "shell": "/usr/bin/fish"
                },
                {
                    "groups": "adm,sudo,docker",
                    "name": "user1",
                    "password": "hash",
                    "shell": "/usr/bin/fish"
                }
            ]
        }
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "file": "vault.yml",
            "name": "vault"
        },
        "module_name": "include_vars"
    }
}

TASK [role_create_user_environment : debug vault variable] *********************
task path: /Users/evert/git/infrastructure/roles/role_create_user_environment/tasks/main.yml:12
ok: [localhost -> None] => {
    "vault": "VARIABLE IS NOT DEFINED!"
}

TASK [role_create_user_environment : Create the users] *************************
task path: /Users/evert/git/infrastructure/roles/role_create_user_environment/tasks/main.yml:16
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "'vault' is undefined"
}
```

**Comment by EvertMDC** [comment]
Additionally, when printing out the hostvars with a debug task I get the variables of localhost, not the machine the role was supposed to be delegated to.
When printing out the hostvars of the machine I delegated to, but hard-coding the name in, the correct variables are printed.
The delegated machine is added in-memory using the add_host module.

**Comment by bcoca** [comment]
have you tried using `ansible_facts.vault ` as the variable?

- delegation will NOT set vars on the delegated machine UNLESS you also use `delegate_facts: True`

**Comment by Evertvz** [comment]
Hello @bcoca ,

`ansible_facts.vault` also gives an error that the variable is not defined. Here is the output.
```
TASK [role_create_user_environment : Create the users] *************************
task path: /Users/pathtorole/role_create_user_environment/tasks/main.yml:9
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "'ansible_facts' is undefined"
}
```

I wasn't aware of the `delegate_facts: True` option. I put the option on the task that uses the include_vars module to load the variables but to no avail.
```yaml
- name: Include vars of vault.yml
  include_vars:
    file: vault.yml
    name: vault
  no_log: True
  delegate_facts: True
```
Then I put it on the parent role where the delegate_to statement is set and it did not work either.
```yaml
- name: Create user environment
  include_role:
    name: role_create_user_environment
  delegate_to: tmp-ami
  delegate_facts: True
```
In the end I put it on both the parent task and all tasks in the role that was called. But it still did not work.

Any hint as to how this can be debugged is helpful. I think the delegate_facts is on the right track though.
