### ISSUE TITLE
expose $ansible_ssh_user as a variable to reduce workarounds.

### ISSUE THREAD

**Issue by steverweber** [ansible/ansible#2516]
please expose the parent connection user as a variable

since $ansible_ssh_user is not a variable.
I have to use one of theses work around when trying to get the user name when running a sudo play.

```
- name: get ssh user
  hosts: any
  sudo: no
  gather_facts: no
  tasks:
    - shell: echo "$USER"
      register: ansible_ssh_user

- name: a sudo play
  hosts: any
  sudo: yes
  tasks:
    - shell: echo "user is ${ansible_ssh_user.stdout}"
```

or

```
ansible-playbook -i localhost sudo_play_test.yml --user=$USER --extra-vars="ansible_ssh_user=$USER" --K
```

extra background on the issue.
https://groups.google.com/forum/?fromgroups=#!topic/ansible-project/ETVSHYDJE_Y

thanks.
