### ISSUE TITLE
ec2_asg returns as changed when multiple subnets/AZs are provided

### ISSUE THREAD

**Issue by conlon** [ansible/ansible#25182]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_asg

##### ANSIBLE VERSION

```
ansible 2.3.0.0 (devel d56ba0945d) last updated 2017/05/10 16:28:41 (GMT -500)
  config file = /Users/mconlon/git/hyperwave_relay_inf_as_code/ansible.cfg
  configured module search path = [u'custom_modules']
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### CONFIGURATION

ansible.cfg:
```
[defaults]
roles_path = roles
lookup_plugins = lookup_plugins
filter_plugins = filter_plugins
hash_behaviour = merge
library = custom_modules
forks = 50

[ssh_connection]
scp_if_ssh = True
pipelining = True
# an attempt to fix ssh unreachable errors when machines are actually reachable
retries = 5
```
##### OS / ENVIRONMENT

N/A

##### SUMMARY

When providing a list of subnets in the `vpc_zone_identifier` arg, the module always returns as changed.
When providing a single subnet, the module returns as `ok` as expected.

This issue was closed seemingly for no reason in 2014 and apparently hasn't been addressed since https://github.com/ansible/ansible/issues/8501

From the summary (which looks useful in full):
> the module supplied list of zones are not necessarily in the same order of the zones in the list returned from EC2.

##### STEPS TO REPRODUCE

```yaml
- name: create auto scaling group
  ec2_asg:
    region: "{{ region }}"
    name: "{{ asg_name }}"
    vpc_zone_identifier: "{{ subnets | join(,) }}"
    launch_config_name: "{{ launch_config_name }}"
    state: present
```

##### EXPECTED RESULTS

The module should only return as `changed` if something actually changed

##### ACTUAL RESULTS

The module returns as changed unless I specify the exact ordering of subnets/AZs that was provided by AWS
