### ISSUE TITLE
win_dns_client failing on 2008R2 SP1 server when no DNS servers are configured on the server

### ISSUE THREAD

**Issue by MikeKlebolt** [ansible/ansible#25216]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_dns_client

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

```

##### CONFIGURATION
display_args_to_stdout = True
inventory      = /etc/ansible/hosts
sudo_user      = root
transport      = smart
ansible_port: 5985
deprecation_warnings=False
gathering = smart
fact_caching_timeout = 3600
fact_caching = jsonfile
fact_caching_connection = /tmp/ansible_fact_cache
host_key_checking = False
nocows = 1
force_color = 1
become_method=sudo
become_user=root

##### OS / ENVIRONMENT
Running Ansible From:
Red Hat Enterprise Linux Server release 6.9 (Santiago)
2.6.32-696.el6.x86_64

OSes being managed:
Windows 2008 R2 SP1 Enterprise - Not working
   Powershell V5
Windows 2012 R2 Standard - Working
   Powershell V5
DNS server variable are being pulled from a vars file.

##### SUMMARY

When using the win_dns_client module on a 2008 R2 SP1 server, ansible bombs out on $v4_match if $current_dns_v4 = $null.  I can run the exact same task against a 2012 R2 server without issue.

##### STEPS TO REPRODUCE
1. Run the following playbook against a Windows 2008 R2 SP1 Enterprise server with no DNS servers configured.

```yaml
- name: Obtaining interface index of mgmt interface
  win_shell: Get-WmiObject win32_ip4routetable | Where-Object {$_.Destination -match "<<IP Omitted>>"} | Foreach InterfaceIndex
  register: interfaceIndex
  changed_when: False

- name: Obtain name of mgmt interface
  win_shell: Get-WmiObject Win32_NetworkAdapter | Where-Object {$_.InterfaceIndex -eq "{{ interfaceIndex.stdout }}"} | Foreach NetConnectionID
  register: intName
  changed_when: False

- name: Configure DNS client with "{{ dnsServers }}"
  win_dns_client:
   adapter_names: "{{intName.stdout|trim(\r\n)}}"
   ipv4_addresses: "{{ dnsServers }}"

```

##### EXPECTED RESULTS
Server gets configured with IPs x.x.x.x and y.y.y.y.

##### ACTUAL RESULTS

```yaml
    "module_stderr": "#< CLIXML\r\nCompare-Object : Cannot bind argument to parameter 'ReferenceObject' because \r\nit is null.\r\nAt line:138 char:34\r\n+     $v4_match = @(Compare-Object $current_dns_v4 $ipv4_addresses)
.Cou ...\r\n+                                  ~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParentContain \r\n   sErrorRecordException\r\n    + FullyQualifiedErrorId : ParameterArgum
entValidationErrorNullNotAllowed,M \r\n   icrosoft.PowerShell.Commands.CompareObjectCommand\r\n \r\n\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><
TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>
Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1

```
