### ISSUE TITLE
ec2_group should have a present vs. exact 

### ISSUE THREAD

**Issue by one-t** [ansible/ansible#25238]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Being able to instantiate an empty security group is very useful if you want to use them in rules. If the group doesn't exist already and you try to add it to a rule, the task will fail. This module could benefit from having an "exact" option in the "state" parameter.

##### STEPS TO REPRODUCE
Create two tasks referencing the same security group

```yaml
  - name: Instantiate Database Security Group
    ec2_group:
      name: "Database"
      description: "Database Servers"
      vpc_id: "vpc-xxxxxxxx"
      state: present

  - name: Instantiate Application Security Group
    ec2_group:
      name: "Application"
      description: "Application Servers"
      vpc_id: "vpc-xxxxxxxx"
      state: present

  - name: Configure DB Security Group
    ec2_group:
      name: Database
      description: "Database Servers"
      vpc_id: "vpc-xxxxxxxx"
      state: present
      rules:
        - proto: tcp
          group_name: Application
          from_port: 5432
          to_port: 5432
        - proto: tcp
          group_name: Database
          from_port: 5432
          to_port: 5432
```

##### EXPECTED RESULTS
The first task would leave the group alone since it exists, the second one would change the group if needed.

##### ACTUAL RESULTS
The first task clears out all of the rules. The second task adds them back
