### ISSUE TITLE
win_regedit case sensitivity

### ISSUE THREAD

**Issue by adam-kosseck** [ansible/ansible#25239]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_regedit

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT

NA

##### SUMMARY

Module does not properly check case of data, two issues:
1. If writing a key value of ```false``` when key value was ```False``` before playbook was run  - then key is not changed.

2. if writing a key value of ```false``` (without quotes around value in data field) when key value was anything else (e.g.  ```true```) before playbook was run, then Ansible writes value as ```False```

##### STEPS TO REPRODUCE

Case 1:

```yaml
    - name: Set value to false (from False)
      win_regedit:
          path: HKLM:\SOFTWARE\COMPANY\Product\global
          name: report_engine_issue
          type: string
          data: 'false'
          state: present
```

Case 2:

```yaml
    - name: Set value to false (from True)
      win_regedit:
          path: HKLM:\SOFTWARE\COMPANY\Product\global
          name: report_engine_issue
          type: string
          data: false
          state: present
```

##### EXPECTED RESULTS

'global' key value is set to ```false```

##### ACTUAL RESULTS

Case 1:
Key value unchanged
```
ok: [mdc-nc2] => {
    "changed": false, 
    "data_changed": false, 
    "data_type_changed": false
}
```
Case 2
Key value set to ```False```, not ```false```
```
ok: [mdc-nc2] => {
    "changed": true, 
    "data_changed": true, 
    "data_type_changed": false
}
```

**Comment by ansibot** [comment]
cc @joshludwig @smadam813
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
I think this is actually to do with yaml data typing, rather than any specific behavior of the module.

By quoting the data value, you tell yaml to handle the value as a string.  But the bare word false is treated as a boolean by yaml.  I believe yaml also treats Yes and No as acceptable boolean representations, so I suspect if you changed task to look like this, you would still wind up with False in the registry data (not tested).

```yaml
    - name: Set value to false (from True)
      win_regedit:
          path: HKLM:\SOFTWARE\COMPANY\Product\global
          name: report_engine_issue
          type: string
          data: No
          state: present
```
I think this edge case would be worth documenting (in win_regedit examples perhaps), but I think the principle here is if you need a string, pass the module a string.   

It's not clear to me whether or not anything should change in ansible to handle this case, though.

If we forced a type conversion in the win_regedit module itself it would still guess wrongly (as it is doing now) because the yaml parsing will have happened and typing information lost before the module parameters are passed to the module.  I don't know the core of ansible well enough to say whether anything could be done on the controller side that wouldn't affect the behavior of other modules or pre-existing playbooks.
