### ISSUE TITLE
warnings messages not reported when using lists

### ISSUE THREAD

**Issue by pijpe00** [ansible/ansible#25258]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

modules with "warning messages"

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### SUMMARY

A task which using with_items don't report warning messages

##### STEPS TO REPRODUCE

```yaml
---
create module: test.py
#-----------------------------------------------------------
#! /usr/bin/env python2
from ansible.module_utils.basic import *
module.exit_json(changed=False, warnings=['test'])
#-----------------------------------------------------------
create playbook: test.yml
#-----------------------------------------------------------
---
  - name: test
    hosts: 127.0.0.1

    tasks:
      - name: test 
        test:
#-----------------------------------------------------------
run: playbook:
ansible-playbook  test.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [test user:pijpe00] *******************************************************
ok: [127.0.0.1]
 [WARNING]: test


PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0

Change: playbook in (test.yml):
#-----------------------------------------------------------
---
  - name: test
    hosts: 127.0.0.1

    tasks:
      - name: test
        test:
        with_items:
          - edwin
          - henk
#-----------------------------------------------------------

Run module again:
ansible-playbook  test.yml
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [test] ********************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [test] ********************************************************************
ok: [127.0.0.1] => (item=edwin)
ok: [127.0.0.1] => (item=henk)

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0

The warnings are not reported!

```

##### EXPECTED RESULTS

I expected two warnings, like:
ok: [127.0.0.1] => (item=edwin)
 [WARNING]: test
ok: [127.0.0.1] => (item=henk)
 [WARNING]: test
##### ACTUAL RESULTS

I did not get any warning message. I got:
ok: [127.0.0.1] => (item=edwin)
ok: [127.0.0.1] => (item=henk)

```

```
