### ISSUE TITLE
get_url documentation - others parameter

### ISSUE THREAD

**Issue by JimCircadian** [ansible/ansible#25263]
##### ANSIBLE VERSION
```
ansible 2.3.1.0 (devel 995f387c34) last updated 2017/06/01 16:37:13 (GMT +100)
```
and
```
ansible 2.4.0 (devel 45a9f96774) last updated 2017/06/01 17:08:32 (GMT +100)
```
##### COMPONENT NAME
get_url

##### CONFIGURATION
None relevant

##### OS / ENVIRONMENT
N/A

##### SUMMARY
get_url module documentation specifies file parameters should all work with get_url.

> all arguments accepted by the file module also work here 

##### STEPS TO REPRODUCE
```yaml
---
- hosts:    localhost
  tasks:
    - name: Download
      get_url:
        url:        http://ipecho.net/plain
        dest:       ./newdirectory/
        state:      directory
```

##### EXPECTED RESULTS
I was hoping that specifying "state" would result in creation of destination directories alongside moving the file to the destination 

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "dest": "./newdirectory/", 
            "state": "directory", 
            "url": "http://ipecho.net/plain"
        }
    }, 
    "msg": "Unsupported parameters for (get_url) module: state. Supported parameters include: attributes,backup,checksum,client_cert,client_key,content,delimiter,dest,directory_mode,follow,force,force_basic_auth,group,headers,http_agent,mode,owner,regexp,remote_src,selevel,serole,setype,seuser,sha256sum,src,timeout,tmp_dest,unsafe_writes,url,url_password,url_username,use_proxy,validate_certs"
}
```
