### ISSUE TITLE
Global Name 'vim' not defined error when called from Ansible

### ISSUE THREAD

**Issue by Illydth** [ansible/ansible#25281]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest Module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION
No Config Changes

##### OS / ENVIRONMENT
Debian 8 Jessie running in a docker Container (jenkinsci/jenkins:2.63)

##### SUMMARY
Getting error "Global Name 'vim' not defined" error when called from Ansible using Ansible 2.3.1.0 and pyvmomi (6.5.0.2017.5.post1)

##### STEPS TO REPRODUCE
pip install ansible
pip install pyvmomi
Execute Playbook for creation of VM from Template.

```
  - name: VMWare | Create VM from Template
    vmware_guest:
      hostname: "{{ vsphere_host }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      datacenter: "{{ data_center }}"
      cluster: "{{ cluster }}"
      folder: "{{ folder }}"
      annotation: "{{ note }}"
      name: "{{ vsphere_vmname }}"
      template: "{{ template }}"
      wait_for_ip_address: yes
      guest_id: rhel7_64Guest
      state: present
      hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
        scsi: lsilogic
      networks:
      - name: "{{ final_vlan }}"
        device_type: vmxnet3
        ip: "{{ ip_addr }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain }}"
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      customization:
        vcpu.hotadd: yes
        mem.hotadd:  yes
    register: deploy
```

##### EXPECTED RESULTS
As with two other boxes running pyvmomi (6.5) I expect the VMWare task to complete and a VM to be created.

##### ACTUAL RESULTS
```
TASK [roles-vmware-create-vm-from-template : VMWare | Create VM from Template] *********************
task path: /var/jenkins_home/workspace/Development_Jobs/Ansible_Export_OVA_for_AMI/servicedef-aws-build-ami/roles/roles-vmware-create-vm-from-template/tasks/create_vm.yml:5
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_guest.py
<stldtpl-mongodb.rgare.net> ESTABLISH LOCAL CONNECTION FOR USER: jenkins
<stldtpl-mongodb.rgare.net> EXEC /bin/sh -c 'echo ~ && sleep 0'
<stldtpl-mongodb.rgare.net> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/jenkins_home/.ansible/tmp/ansible-tmp-1496358955.4-107369950966905 `" && echo ansible-tmp-1496358955.4-107369950966905="` echo /var/jenkins_home/.ansible/tmp/ansible-tmp-1496358955.4-107369950966905 `" ) && sleep 0'
<stldtpl-mongodb.rgare.net> PUT /tmp/tmpnSvO2X TO /var/jenkins_home/.ansible/tmp/ansible-tmp-1496358955.4-107369950966905/vmware_guest.py
<stldtpl-mongodb.rgare.net> EXEC /bin/sh -c 'chmod u+x /var/jenkins_home/.ansible/tmp/ansible-tmp-1496358955.4-107369950966905/ /var/jenkins_home/.ansible/tmp/ansible-tmp-1496358955.4-107369950966905/vmware_guest.py && sleep 0'
<stldtpl-mongodb.rgare.net> EXEC /bin/sh -c '/usr/bin/python /var/jenkins_home/.ansible/tmp/ansible-tmp-1496358955.4-107369950966905/vmware_guest.py; rm -rf "/var/jenkins_home/.ansible/tmp/ansible-tmp-1496358955.4-107369950966905/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_StmZvW/ansible_module_vmware_guest.py", line 1332, in <module>
    main()
  File "/tmp/ansible_StmZvW/ansible_module_vmware_guest.py", line 1291, in main
    pyv = PyVmomiHelper(module)
  File "/tmp/ansible_StmZvW/ansible_module_vmware_guest.py", line 436, in __init__
    self.content = connect_to_api(self.module)
  File "/tmp/ansible_StmZvW/ansible_modlib.zip/ansible/module_utils/vmware.py", line 321, in connect_to_api
NameError: global name 'vim' is not defined

fatal: [stldtpl-mongodb.rgare.net]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_StmZvW/ansible_module_vmware_guest.py\", line 1332, in <module>\n    main()\n  File \"/tmp/ansible_StmZvW/ansible_module_vmware_guest.py\", line 1291, in main\n    pyv = PyVmomiHelper(module)\n  File \"/tmp/ansible_StmZvW/ansible_module_vmware_guest.py\", line 436, in __init__\n    self.content = connect_to_api(self.module)\n  File \"/tmp/ansible_StmZvW/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 321, in connect_to_api\nNameError: global name 'vim' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

It appears that something has changed between pyvmomi 6.5 and 6.5.0.2017.5.post1 uploaded on the 24th.

I have 2 ansible installations (both running ansible 2.3.1) that run this command just fine while my other ansible install (the on on my jenkins box) is blowing up with the above error.  The only differences I could find with Ansible or what's being used is the pyvmomi version.

Apologies for the cross post, i've reported this on pyvmomi's github as well as I wasn't sure which group the "error" would be under.

**Comment by ansibot** [comment]
cc @jctanner @nerzhul @dav1x @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Illydth** [comment]
From the "unworking" box:

```$ python
Python 2.7.9 (default, Jun 29 2016, 13:08:31)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyVmomi import vim
>>> dir(vim)
['__call__', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattr__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'name']
>>> help(vim)
Help on LazyModule in module pyVmomi.VmomiSupport object:

class LazyModule(__builtin__.object)
 |  ## LazyModule class
 |  # Used as a placeholder until the actual type is loaded
 |  # If someone wants to use the type, then it is loaded on-demand
 |
<snip>
```
It looks like "vim" is there and available through python.

**Comment by jctanner** [comment]
@Illydth the task is using a local connection

```
<stldtpl-mongodb.rgare.net> ESTABLISH LOCAL CONNECTION FOR USER: jenkins
```

Did you run your python test on the ansible control host (maybe a jenkins worker) ?

needs_info

**Comment by Illydth** [comment]
Yes, the test was run actually inside the Jenkins Master docker container (the control host that would be kicking off the ansible job).

I've actually gotten farther down this stack in the last 12 hours or so.  I reproduced the container and started building it package by package to see if I could track down what was causing the issue.

Apparently after I "apt-get purge python-pip" (which removes a bunch of packages) this becomes a problem.  I haven't determined what package it is that causes this specifically, but with the python-pip package installed (and it's Debian dependencies) I DO NOT get the error about the "vim" global.  However with python-pip and it's dependencies removed I do get the "vim" issue.

In both cases, however (with and without python-pip), I can go to the python command line and "from pyVmomi import vim" and get a valid import so while this doesn't make much sense to me, it's reproducible behavior.

To be clear, this does NOT appear to be an issue with pyVmomi or it's implementation, it appears to be package related (what's installed vs. not installed).

**Comment by Illydth** [comment]
@jctanner Just checking back in with the thread to make sure i've been clear.  What it looks like is that there's a dependency within Ansible's use of the pyVMomi library within the vmware_guest module that has requirements beyond the pyVMomi library...dependencies that are NOT installed with either pip install pyVMomi or pip install Ansible.

**Comment by Illydth** [comment]
@jctanner @nerzhul @dav1x @dagwieers

Apparently on Debian 8 (jessie) - There is a soft dependency on package "python-requests" or "python-urllib3" (one of the two, installing/uninstalling python-requests or python-urllib3 forces installation/uninstallation of the other).

Upon installing python-pip onto a debian 8 box, these two packages are installed, and upon uninstalling python-pip they are uninstalled.  Removing python-urllib3 or python-requests breaks the pyVMomi / Ansible vmware_guest module.  

Not sure what other information I need to supply.

**Comment by ansibot** [comment]
cc @akasurde
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@Illydth So wouldn't that be a Debian packaging issue rather than a problem with Ansible ? Not sure what we can or should do about it.

**Comment by Illydth** [comment]
First, apologies for the lack of response, i've gotten pulled in a hundred different directions.

@dagwieers It's a very valid question you ask.  And you may very well be right, this might all boil down to a packaging issue or maybe it's not even an issue at all.

The only reason i'm looking for help here and not filing an issue with Debian is because the behavior seems weird and ONLY shows with Ansible.

The point that caused me to file a report here was with pip uninstalled (and thus no "python-requests" or "python-urllib3") if I go to the command line, open Python 2.7 and do a "from pyVmomi import vim" I will successfully be able to "dir" and "help" that part of pyVMomi...with my (potentially limited) understanding, this should mean that the global "vim" is indeed accessible.

However, if I then go to Ansible and execute a VMWare build task, it will fail with "NameError: global name 'vim' is not defined".  

If I can "from pyVMomi import vim" and the command is successful within python's interpreter, i'm not sure how or why Ansible is throwing a "vim" not defined error using the same library...which is what prompted me to open an issue here.

Suggested another way:  There appears to be a dependency between Ansible and whatever packages are installed with "python-requests" or "python-urllib3."  
* PIP installing Ansible does not include whatever this dependency is.
* If these packages are missing, Ansible's python code seems unable to recognize the "vim" global, even though that global appears to be there and functional when using the Python Interpreter from the command line.

Apologies if I'm missing something obvious.

**Comment by dagwieers** [comment]
Ansible requires pyvmomi, and pyvmomi requires python-requests.

https://github.com/vmware/pyvmomi/blob/master/setup.cfg

Are you absolutely sure that the location that is running this module has pyvmomi installed ? Is it possible you are confused about where Ansible is running these modules ? The example doesn't show you are running this with e.g. `delegate_to: localhost`, so you are running this on some other remote target ?

**Comment by Illydth** [comment]
@dagwieers Yep, absolutely sure.

In the top level playbook is the following:
```
- name: Deploy Templates to Servers in VSphere
  hosts: all
  become: no
  gather_facts: no
  connection: local
  serial: 1
  vars_files:
    - group_vars/creds.yml
  roles:
    - roles-vmware-create-vm-from-template
```
WIthin the create-vm-from-template role is 
```
- name: VMWare | Create VM from Template
    vmware_guest:
      hostname: "{{ vsphere_host }}"
      username: "{{ vsphere_username }}"
      password: "{{ vsphere_password }}"
      validate_certs: no
      datacenter: "{{ data_center }}"
      cluster: "{{ cluster }}"
      folder: "{{ folder }}"
      annotation: "{{ note }}"
      name: "{{ vsphere_vmname }}"
      template: "{{ template }}"
      wait_for_ip_address: yes
      guest_id: rhel7_64Guest
      state: present
      hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
        scsi: lsilogic
      networks:
      - name: "{{ final_vlan }}"
        device_type: vmxnet3
        ip: "{{ ip_addr }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        domain: "{{ domain }}"
        dns_servers:
        - "{{ dns1 }}"
        - "{{ dns2 }}"
      customization:
        vcpu.hotadd: yes
        mem.hotadd:  yes
    register: deploy
```

So yes, I'm running locally (in the jenkins container) with Ansible running a local pyvmomi.  In that same container I can run the python shell, and "from pyVmomi import vim", it successfully imports and works.

I think what we're boiled down to then is how is pyVmomi running without whatever python-requests is providing being there.  Again, I'm MORE than OK with calling this an issue at Debian's side from a package perspective, and maybe that's what we've just proven...if there IS a required link between pyVmomi and python-requests, and I can uninstall python requests and have pyvmomi still functional, that tells me this is a package problem on Debian's side.

Is there a potential for the PIP package NOT to include something Ansible needs while the OS package DOES?  As i'm looking through the container creation code I'm seeing PIP is installed with it's dependencies by the OS through apt-get...and that will include python-requests.  Then sometime down the line pyvmomi is installed through pip install.  Finally, PIP and it's dependencies  are removed through apt-get (which removes the python-requests OS package) which creates the scenario where Ansible fails but Python Command Line works at least for the import command.

I am not a master on debian packaging in any way, and particularly not the interaction between apt-get install and pip install.  If python-requests is installed by apt-get, and then is on the required line for "pip install pyvmomi" does a "second copy" of python-requests get installed?  (I wouldn't think so).  If I then remove python-requests I absolutely get the OS package doesn't understand there's a dependent pip package installed and would happily remove python-requests, breaking pyvmomi.  So in this case the EXPECTED result would be the "from pyVmomi" command in python failing with the same error Ansible is throwing since the dependent package isn't there....instead however the from works while Ansible is broken.

To be honest, with where we've gotten to in the conversation I'm more than ok with calling this a packaging bug and/or a stupid installation method on my part (we really shouldn't be crossing OS packages with pip install packages), but at this point I'm curious as to how two things using the same library are behaving in two different ways.
