### ISSUE TITLE
Ansible lineinfile duplicates line when with \n

### ISSUE THREAD

**Issue by movie0125** [ansible/ansible#25286]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
module  lineinfile

##### ANSIBLE VERSION

```
2.3.0.0
```

```yaml
---
- hosts: 127.0.0.1
  tasks:
    - name:
      lineinfile:
        dest: foo.txt
        regexp: "msgid aaaa\nmsgstr bbbbb\n"
        line:   "msgid aaaa\nmsgstr bbbbb\n"
```

```
# echo > foo.txt
# ansible-playbook aa.yaml
# ansible-playbook aa.yaml
# ansible-playbook aa.yaml
# cat foo.txt 
msgid aaaa
msgstr bbbbb

msgid aaaa
msgstr bbbbb

msgid aaaa
msgstr bbbbb
```

**Comment by movie0125** [comment]
Enables idioms when there is \ n

**Comment by JayKayy** [comment]
I don't believe lineinfile was meant for multi-line entries. There are a few alternatives to use for what you're trying to accomplish. For multi-line inserts I found using `with_items` helpful like so:
```
  - name:
     lineinfile:
        dest: foo.txt
        regexp: "{{ item }}"
        line:   "{{ item }}"
     with_items:
          - "msgid aaaa"
          - "msgstr bbbbb"

```

Another method is to use the blockinfile module. 

https://docs.ansible.com/ansible/blockinfile_module.html

Best,

John

**Comment by ansibot** [comment]
cc @ahtik @dhozac
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kees-closed** [comment]
I don't see why this issue was closed. I'm trying to replace a specific line in a file, a line that occurs twice. In order to make sure the right line is replaced, the line above it must be included in the regexp.

File I want to change:
```
# Authentication for passwd-file users. Included from 10-auth.conf.
#
# passwd-like file with specified location.
# <doc/wiki/AuthDatabase.PasswdFile.txt>

passdb {
  driver = passwd-file
  args = scheme=SHA512-CRYPT username_format=%u /etc/dovecot/%d/passwd
}

userdb {
  driver = passwd-file
  args = uid=vmail gid=nogroup home=/var/vmail/%d/%n

  # Default fields that can be overridden by passwd-file
  #default_fields = quota_rule=*:storage=1G

  # Override fields from passwd-file
  #override_fields = home=/home/virtual/%u
}
```

Code of my task:
```
    - name: configure dovecot
      lineinfile:
        path: /etc/dovecot/conf.d/{{ item.path }}
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: "{{ item.backrefs | default('no') }}"
        insertafter: "{{ item.insertafter | default('EOF') }}"
        state: present
      loop:
        - path: auth-passwdfile.conf.ext
          regexp: '^userdb\s{\n\s+driver\s=\spasswd-file$'
          line: 'userdb {\n  driver = static'
          backrefs: yes
```

Syntax check [here](https://regex101.com/r/KsiKWu/1/)

Ansible doesn't recognize it, it passes as an OK. When I change the regexp to `^\s{\n\s+driver\s=\spasswd-file$` it works, but then replaces two lines...
