### ISSUE TITLE
Module foreman fails with no Content View found for, swallows params name for organization

### ISSUE THREAD

**Issue by ericzolf** [ansible/ansible#25299]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
foreman module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /some/current/path/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
```
[defaults]
roles_path = ./roles
inventory = ./inventory.cfg
remote_user = admin
```

(no roles used, though)

##### OS / ENVIRONMENT
Control host is Fedora 25.
Satellite 6 runs on RHEL7 (but doesn't seem involved anyway)

##### SUMMARY
The module doesn't work at all, even when just reproducing what is written in the documentation.

##### STEPS TO REPRODUCE

```yaml
- name: Configure Satellite 6
  hosts: satellite_6.2
  vars_files:
    - credentials.cfg
  tasks:
  - name: create organizations
    local_action:
      module: foreman
      username: "{{ sat6_user }}"
      password: "{{ sat6_pass }}"
      server_url: "https://{{ inventory_hostname }}"
      entity: "organization"
      params:
        # label: "Test_Org"
        name: "Test Org"
    register: foreman_result
  - debug: var=foreman_result
...
```
Inventory file used:

```ini
[satellite_6.2]
sat6.example.com

[satellite_6.2:vars]
satellite_version=6.2
```
credentials.cfg just defines my credentials.

##### EXPECTED RESULTS

That an organization is created in Satellite with the name and/or the label given.

##### ACTUAL RESULTS

```
[... gathering facts on the Satellite server works ...]
TASK [create organizations] ******************************************************************************
task path: /home/myuser/Documents/Work/SOE-CI/sat6-automated/satellite6_configure.yml:7
Using module file /usr/lib/python2.7/site-packages/ansible/modules/remote_management/foreman/foreman.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: myuser
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/myuser/.ansible/tmp/ansible-tmp-1496398194.83-185071126181725 `" && echo ansible-tmp-1496398194.83-185071126181725="` echo /home/myuser/.ansible/tmp/ansible-tmp-1496398194.83-185071126181725 `" ) && sleep 0'
<localhost> PUT /tmp/tmpEG9L3p TO /home/myuser/.ansible/tmp/ansible-tmp-1496398194.83-185071126181725/foreman.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/myuser/.ansible/tmp/ansible-tmp-1496398194.83-185071126181725/ /home/myuser/.ansible/tmp/ansible-tmp-1496398194.83-185071126181725/foreman.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/myuser/.ansible/tmp/ansible-tmp-1496398194.83-185071126181725/foreman.py; rm -rf "/home/myuser/.ansible/tmp/ansible-tmp-1496398194.83-185071126181725/" > /dev/null 2>&1 && sleep 0'
fatal: [sat6.example.com -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "entity": "organization", 
            "params": {}, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server_url": "https://sat6.example.com", 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "verify_ssl": false
        }
    }, 
    "msg": "No Content View found for ********"
}
	to retry, use: --limit @/home/myuser/Documents/Work/SOE-CI/sat6-automated/satellite6_configure.retry

PLAY RECAP ***********************************************************************************************
sat6.example.com   : ok=1    changed=0    unreachable=0    failed=1   
```

Notice that the params 'name' disappears (it disappears as well if I put label in, label doesn't disappear, order of name and label doesn't matter: name disappears, label doesn't).

Also, the error message has nothing to do with the action requested.
