### ISSUE TITLE
nxos_switchport parameter transport Unsupported

### ISSUE THREAD

**Issue by hemskgren** [ansible/ansible#25305]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_switchport

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  python version = 2.7.9 (default, Oct 19 2015, 10:36:53) [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
```

##### CONFIGURATION

```
default
```
##### OS / ENVIRONMENT

```
centos 6
```
##### SUMMARY

```
Module nxos_switchport and some more nxos_* module report paramerter 'transport' as unsupported.
```
##### STEPS TO REPRODUCE

```yaml
  vars:
    nxapi:
      username: "{{ tower_user_name }}"
      password: "{{ password }}"
      transport: nxapi
      use_ssl: yes
      validate_certs: no
      port: 10443
      #timeout: 15
      host: "{{ inventory_hostname }}"

    cli:
      username: "{{ tower_user_name }}"
      password: "{{ password }}"
      transport: cli
      host: "{{ inventory_hostname }}"

  tasks:
   #
  - name: allow vlan on POD trunk (Po50)
    nxos_switchport:
      state: present
      mode: trunk
      interface: Port-Channel50
      trunk_vlans: "{{ vlan_id }}"
      #transport: nxapi
      #provider: "{{ nxapi }}"

```

##### EXPECTED RESULTS

```
More like nxos_facts module:


ok: [ix1-test-s11a] => {
    "ansible_facts": {
        "ansible_net_gather_subset": [
            "default",
            "legacy"
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "legacy"
            ],
            "host": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    }
}
```
##### ACTUAL RESULTS

```
$ ansible-playbook -vvvv ptest-vlan-trunk.yml --extra-vars="tower_user_name=userid password=password vlan_id=49" -u userid -k
Using /etc/ansible/ansible.cfg as config file
SSH password:
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: ptest-vlan-trunk.yml *************************************************************************************************
1 plays in ptest-vlan-trunk.yml

PLAY [gather facts from leaf to find vlan name] ********************************************************************************
META: ran handlers

TASK [allow vlan on POD trunk (Po50)] ******************************************************************************************
task path: /home/eu2187/dev/ptest-vlan-trunk.yml:27
<ix1-test-s11a> connection transport is cli
<ix1-test-s11a> using connection plugin network_cli
<ix1-test-s11a> socket_path: /home/eu2187/.ansible/pc/d62bfe69e4
open_shell() returned 0 ok
Using module file /usr/share/ansible/cisco_nxos/nxos_switchport
<ix1-test-s11a> ESTABLISH LOCAL CONNECTION FOR USER: eu2187
<ix1-test-s11a> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1496412395.93-193046486462416 `" && echo ansible-tmp-1496412395.93-193046486462416="` echo $HOME/.ansible/tmp/ansible-tmp-1496412395.93-193046486462416 `" ) && sleep 0'
<ix1-test-s11a> PUT /tmp/tmp8AWvJO TO /home/eu2187/.ansible/tmp/ansible-tmp-1496412395.93-193046486462416/nxos_switchport
<ix1-test-s11a> EXEC /bin/sh -c 'chmod u+x /home/eu2187/.ansible/tmp/ansible-tmp-1496412395.93-193046486462416/ /home/eu2187/.ansible/tmp/ansible-tmp-1496412395.93-193046486462416/nxos_switchport && sleep 0'
<ix1-test-s11a> EXEC /bin/sh -c '/usr/bin/python /home/eu2187/.ansible/tmp/ansible-tmp-1496412395.93-193046486462416/nxos_switchport; rm -rf "/home/eu2187/.ansible/tmp/ansible-tmp-1496412395.93-193046486462416/" > /dev/null 2>&1 && sleep 0'
fatal: [ix1-test-s11a]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "interface": "Port-Channel50",
            "mode": "trunk",
            "state": "present",
            "transport": "cli",
            "trunk_vlans": "49"
        }
    },
    "msg": "Unsupported parameters for (nxos_switchport) module: transport. Supported parameters include: access_vlan,host,interface,mode,native_vlan,password,port,protocol,state,trunk_vlans,username"
}

```
