### ISSUE TITLE
nxos_vlan parameter transport Unsupported

### ISSUE THREAD

**Issue by hemskgren** [ansible/ansible#25304]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vlan

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  python version = 2.7.9 (default, Oct 19 2015, 10:36:53) [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
```

##### SUMMARY
Module nxos_vlan and some more nxos_* module report paramerter 'transport' as unsupported.

##### STEPS TO REPRODUCE

```yaml
  vars:
    nxapi:
      username: "{{ tower_user_name }}"
      password: "{{ password }}"
      transport: nxapi
      use_ssl: yes
      validate_certs: no
      port: 10443
      #timeout: 15
      host: "{{ inventory_hostname }}"

    cli:
      username: "{{ tower_user_name }}"
      password: "{{ password }}"
      transport: cli
      host: "{{ inventory_hostname }}"

  tasks:
   #
  - name: run multiple commands and evaluate the output
    nxos_command:
      #provider: "{{ nxapi }}"
      command:
        - show version
        - show clock
```

##### EXPECTED RESULTS

```
More like nxos_facts module:


ok: [ix1-test-s11a] => {
    "ansible_facts": {
        "ansible_net_gather_subset": [
            "default",
            "legacy"
        ]
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "gather_subset": [
                "legacy"
            ],
            "host": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": "cli",
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    }
}
```
##### ACTUAL RESULTS

```
$ ansible-playbook -vvvv ptest-gather-facts.yml --extra-vars="tower_user_name=user password=password vlan_id=49" -u username -k
Using /etc/ansible/ansible.cfg as config file
SSH password:
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: ptest-gather-facts.yml ***********************************************************************************************
1 plays in ptest-gather-facts.yml

TASK [run multiple commands and evaluate the output] ***************************************************************************
task path: /home/eu2187/dev/ptest-gather-facts.yml:46
<ix1-test-s11a> connection transport is cli
<ix1-test-s11a> using connection plugin network_cli
<ix1-test-s11a> socket_path: /home/eu2187/.ansible/pc/d62bfe69e4
Using module file /usr/share/ansible/cisco_nxos/nxos_command.py
<ix1-test-s11a> ESTABLISH LOCAL CONNECTION FOR USER: eu2187
<ix1-test-s11a> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1496411323.66-190170153675890 `" && echo ansible-tmp-1496411323.66-190170153675890="` echo $HOME/.ansible/tmp/ansible-tmp-1496411323.66-190170153675890 `" ) && sleep 0'
<ix1-test-s11a> PUT /tmp/tmpy8FKqi TO /home/eu2187/.ansible/tmp/ansible-tmp-1496411323.66-190170153675890/nxos_command.py
<ix1-test-s11a> EXEC /bin/sh -c 'chmod u+x /home/eu2187/.ansible/tmp/ansible-tmp-1496411323.66-190170153675890/ /home/eu2187/.ansible/tmp/ansible-tmp-1496411323.66-190170153675890/nxos_command.py && sleep 0'
<ix1-test-s11a> EXEC /bin/sh -c '/usr/bin/python /home/eu2187/.ansible/tmp/ansible-tmp-1496411323.66-190170153675890/nxos_command.py; rm -rf "/home/eu2187/.ansible/tmp/ansible-tmp-1496411323.66-190170153675890/" > /dev/null 2>&1 && sleep 0'
fatal: [ix1-test-s11a]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "command": [
                "show version",
                "show clock"
            ],
            "transport": "cli"
        }
    },
    "msg": "Unsupported parameters for (nxos_command) module: transport. Supported parameters include: command,command_list,host,password,port,protocol,text,type,username"
```
