### ISSUE TITLE
find module does not error when encountering a path with permission denied

### ISSUE THREAD

**Issue by cukal** [ansible/ansible#25314]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
find module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /home/ansible/DPP-Deployer_LVC_TEST/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
CentOS Linux release 7.3.1611 (Core)

##### SUMMARY
The find module does not return an error when encountering a permission denied error for a given path. The task finished correctly although a permission denied was encountered which should ideally result in an error. 

##### STEPS TO REPRODUCE
Prepare a test directory with a file
```bash
#mkdir /tmp/denied
#touch /tmp/denied/file
#chmod -R 600 /tmp/denied
```
Run Ansible find
```yaml
- find:
    paths: "/tmp/denied"
    recurse: yes
  register: files

- debug:
    msg: "Found Files:: {{ files }}"
```
Confusion ensues. 

##### EXPECTED RESULTS
find module would return an error due to permission denied of the given path. 

##### ACTUAL RESULTS
```yaml
ok: [192.168.0.144] => {
    "changed": false,
    "examined": 0,
    "files": [],
    "invocation": {
        "module_args": {
            "age": null,
            "age_stamp": "mtime",
            "contains": null,
            "file_type": "file",
            "follow": true,
            "get_checksum": false,
            "hidden": true,
            "paths": [
                "/tmp/denied/"
            ],
            "patterns": [
                "*"
            ],
            "recurse": true,
            "size": null,
            "use_regex": false
        },
        "module_name": "find"
    },
    "matched": 0,
    "msg": ""
}

ok: [192.168.0.144] => {
    "msg": "Found Files:: {u'files': [], u'msg': u'', u'changed': False, u'examined': 0, u'matched': 0}"
}
```
