### ISSUE TITLE
unarchive 

### ISSUE THREAD

**Issue by daincredibleholg** [ansible/ansible#25326]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

unarchive

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/daincredibleholg/projects/mk2/repos/devops/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY
Unarchive reports it can not find the archive but it is definitely there and accessible. Looks like a regression.

##### STEPS TO REPRODUCE

```yaml
## This downloads the tar.gz - tested with zip version as well --> same result
- name: "Download Piwik 3.0.4"
  become: no
  get_url:
    url: "https://builds.piwik.org/{{ item }}"
    dest: "/tmp/{{ item }}"
    mode: 0644
  with_items:
    - "piwik-3.0.4.tar.gz"
    - "piwik-3.0.4.tar.gz.asc"
  register: piwik_download
  tags: [ "piwik", "foofoo" ]

...

- name: Extract Piwik
  unarchive:
    src: "{{ piwik_download.results[0].dest }}"
    dest: "/var/www/"
    extra_opts: [ "--strip 1" ]
    owner: "www-data"
    group: "webdev"
    creates: "/var/www/piwik.php"
  when: piwik_download is defined and piwik_download.results is defined
  tags: [ "piwik", "foofoo" ]

```

##### EXPECTED RESULTS
Extracted file in /var/www/.

##### ACTUAL RESULTS

```
fatal: [quasicletus]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "Unable to find '/tmp/piwik-3.0.4.tar.gz' in expected paths."
}
```

Testing the that everything else looks good:
```
# Check file exists
$ ls -al /tmp/piwik-3.0.4.tar.gz
-rw-r--r-- 1 ansible adm 14336702 Jun  3 08:20 /tmp/piwik-3.0.4.tar.gz

# Check file type
$ file /tmp/piwik-3.0.4.tar.gz
/tmp/piwik-3.0.4.tar.gz: gzip compressed data, last modified: Tue May 16 23:24:09 2017, from Unix

# Check tar
$ tar tf /tmp/piwik-3.0.4.tar.gz | head
piwik/
piwik/SECURITY.md
piwik/LEGALNOTICE
piwik/tests/
piwik/tests/README.md
piwik/config/
piwik/config/global.php
piwik/config/manifest.inc.php
piwik/config/global.ini.php
piwik/config/environment/

# Check tar command
$ which tar
/bin/tar

$ echo $PATH | grep \/bin
/home/ansible/bin:/home/ansible/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
```
