### ISSUE TITLE
azure_rm_virtualmachine , started parameter is True by default. Unable to get status of VMs

### ISSUE THREAD

**Issue by lukasmrtvy** [ansible/ansible#25352]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.3.0.0
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

azure_rm_virtualmachine task without state parameter always starting VM. 
I want to know status of VM, if it is running, or it is stopped. Its not possible to get this information without changing state of actual VM.

##### STEPS TO REPRODUCE

```yaml
- azure_rm_virtualmachine:
    secret: "{{ secret }}"
    tenant: "{{ tenant }}"
    client_id: "{{ client_id }}"
    subscription_id: "{{ subscription_id }}"
    resource_group: "{{ resource_group }}"
    name: "{{ item }}"
  register: output
  async: 360
  poll: 0
  with_items:
    - "{{ groups.vms1 }}"



ok: [localhost] => {
    "changed": false, 
    "msg": {
        "changed": true, 
        "msg": "All items completed", 
        "results": [
            {
                "_ansible_item_result": true, 
                "_ansible_no_log": false, 
                "_ansible_parsed": true, 
                "ansible_job_id": "123932757055.16094", 
                "changed": true, 
                "finished": 0, 
                "item": "mydev", 
                "results_file": "/home/user/.ansible_async/123932757055.16094", 
                "started": 1
            }
        ]
    }
}



```

##### EXPECTED RESULTS

```yaml
ok: [localhost] => {
    "changed": false, 
    "msg": {
        "changed": true, 
        "msg": "All items completed", 
        "results": [
            {
                "_ansible_item_result": true, 
                "_ansible_no_log": false, 
                "_ansible_parsed": true, 
                "ansible_job_id": "123932757055.16094", 
                "changed": true, 
                "finished": 0, 
                "item": "mydev", 
                "results_file": "/home/user/.ansible_async/123932757055.16094", 
            }
        ]
    }
}
```

##### ACTUAL RESULTS

```

```
