### ISSUE TITLE
mysql_user: with_items only keeps last item's privilege

### ISSUE THREAD

**Issue by xiata** [ansible/ansible#25366]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

mysql_user

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = <redacted>/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 25 2017, 11:18:02) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

```
[defaults]
stdout_callback = skippy
```

##### OS / ENVIRONMENT

Mac OS X 10.12.3
Python 2.7.13 (virtualenv)

##### SUMMARY

When granting the same privilege across multiple databases using the `with_items` directive, it resets that user's grants on every with_items iteration rather than just on the first iteration for that user. This is causing grants created by the previous with_items iteration to be removed. The databases is a host variable. Unfortunately the only work arounds I can think of is to issue the grants by using the `command` module, grant the permission on `*.*`, or some set_fact hackery. All workarounds are less than ideal.

Note: this is a simplified test case to show the issue. Real structure involves lists of dicts which complicates jinja syntax.

##### STEPS TO REPRODUCE

Defaults:
  
```yaml
shared_user: shareduser
shared_pass: sharedpass
databases:
  - db1
  - db2
  - db3
```

Task:
  
```yaml
- name: Create site databases
  mysql_db:
    name: '{{ item }}'
    state: present
  with_items: '{{ databases }}'

- name: Setup shared read-only user on databases
  mysql_user:
    host: '%'
    password: '{{ shared_pass }}'
    priv: '{{ item }}.*:SELECT'
    state: present
    user: '{{ shared_user }}'
  with_items: '{{ databases }}'
````

##### EXPECTED RESULTS

The specified `priv` granted to the user on each database specified in `with_items`.

```
mysql> show grants for 'shareduser'@'%';
+---------------------------------------------+
| Grants for shareduser@%                     |
+---------------------------------------------+
| GRANT USAGE ON *.* TO 'shareduser'@'%'      |
| GRANT SELECT ON `db1`.* TO 'shareduser'@'%' |
| GRANT SELECT ON `db2`.* TO 'shareduser'@'%' |
| GRANT SELECT ON `db3`.* TO 'shareduser'@'%' |
+---------------------------------------------+
4 rows in set (0.00 sec)
```

##### ACTUAL RESULTS

Any existing grants on the user is removed on each iteration of with_items, including grants the command previously created.

```
mysql> show grants for 'shareduser'@'%';
+---------------------------------------------+
| Grants for shareduser@%                     |
+---------------------------------------------+
| GRANT USAGE ON *.* TO 'shareduser'@'%'      |
| GRANT SELECT ON `db3`.* TO 'shareduser'@'%' |
+---------------------------------------------+
2 rows in set (0.00 sec)
```

**Comment by ansibot** [comment]
cc @Jmainguy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ghost** [comment]
Observing at this reported issue, the behavior is correct not to say expected; on my understanding. When you use `with_items`, ansible is not keeping track on the very initial privileges so each run has a different value for `curr_priv` (current privileges) on `mysql_user.user_mod`. Since you are affecting the user 3 times, the only one that is prevailing is the last change you requested. You could see this behavior if you add `db1`, `db2`, `db3` and `db4` and grant `SELECT` to your user; on your initial run if you don't define the `append_privs` as `yes`, all the previous permissions will be flushed and this will keep on happening 3 times according to your task until the final item is evaluated.

Surely there is no work around for this and probably you want to propose the option to **preserve** privileges while not appending, this would prevent the `privileges_revoke` execution which is flushing all your privileges from the very beginning (_item 1_)

What could produce the results you want to see here would be something of this fashion:
``` yaml
- name: Create site databases
  mysql_db:
    name: '{{ item }}'
    state: present
  with_items: '{{ databases }}'

- name: Clearing up previous settings on user
  mysql_user:
    host: '%'
    password: '{{ shared_pass }}'
    priv: '*.*:USAGE'
    state: present
    user: '{{ shared_user }}'

- name: Setup shared read-only user on databases
  mysql_user:
    host: '%'
    password: '{{ shared_pass }}'
    priv: '{{ item }}.*:SELECT'
    state: present
    user: '{{ shared_user }}'
    append_privs: 'yes'
  with_items: '{{ databases }}'
```
