### ISSUE TITLE
win_scheduled_task No MSFT_ScheduledTask objects found with property 'TaskPath' equal to '\'. Verify the value of the property and retry

### ISSUE THREAD

**Issue by berney** [ansible/ansible#25377]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_scheduled_task

##### ANSIBLE VERSION

```
Ansible 2.3.0.0
```

##### CONFIGURATION

```
[defaults]
nocows = 1
stdout_callback = debug
retry_files_enabled = False
```

##### OS / ENVIRONMENT
Ansible is running on Linux host, trying to manage a Windows 10 1703 Creators Edition host.

##### SUMMARY
Trying to create a scheduled task on a Windows 10 1703 Creators Edition host. Get an error `No MSFT_ScheduledTask objects found with property 'TaskPath' equal to '\'. Verify the value of the property and retry.`

##### STEPS TO REPRODUCE

```yaml
- name: Try to create scheduled task
  win_scheduled_task:
    name: some_task
    description: Do some task
    executable: powershell
    arguments: -NoProfile -NonInteractive -ExecutionPolicy RemoteSigned c:\users\someuser\some-script.ps1
    state: present
    frequency: once
    time: 9am
    user: someuser
  register: sched_task
```

##### EXPECTED RESULTS
A scheduled task is created.

##### ACTUAL RESULTS

Module fails with error 

```
fatal: [somehost]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

No MSFT_ScheduledTask objects found with property 'TaskPath' equal to '\'. Verify the value of the property and retry.

```
