### ISSUE TITLE
All defaults_from to use files outside of a role

### ISSUE THREAD

**Issue by gilesw** [ansible/ansible#25384]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
https://docs.ansible.com/ansible/include_role_module.html

##### ANSIBLE VERSION

```
ansible 2.2.2.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I would like to be able to override some defaults when including a role, but still allow those new defaults to be overridable at the group_vars level.

##### STEPS TO REPRODUCE
Currently defaults_from will only look for files within the included role

```yaml
- include_role:
    name: geerlingguy.nginx
    defaults_from: ../roles/ansible-liferay-nginx/defaults/liferay.yml
```

##### EXPECTED RESULTS
liferay.yml included instead of the roles defaults/main.yml

##### ACTUAL RESULTS

```
ERROR! Could not find specified file in role: liferay.yml
```

##### Followup

So even if this was to work, it still means that liferay.yml must be a complete fork of all the defaults of the core nginx module. In reality what I'm looking for it some like:-

```yaml
- include_role:
    name: geerlingguy.nginx
    defaults_override: ../roles/ansible-liferay-nginx/defaults/liferay.yml
```
and liferay.yml only includes the defaults we want to change, and these defaults are still overridable at group_vars level if needed.

The current workaround is to include the nginx config needed for liferay to function correctly in :- 

ansible-liferay-nginx/vars/main.yml

However the caveat is that this config is not overridable at group_var level if it was needed to be.

**Comment by ansibot** [comment]
cc @isharacomix @jrrivers @privateip
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gilesw** [comment]
Some explanation of why this useful. There are currently a few mechanisms of overriding a modules behaviour without a fork. Adding extra files, tasks and data overrides at the playbook level however this is outside the standards of a role structure and not a self contained artifact like a role.

If a sub role is used for all file and logic based extensions that calls the parent role with include_role as I've used here then group_vars could be used to set the data level overrides. However again these changes are not a single artifact, they're outside the role. An example of the group_vars needed to use the role could be added to the readme of the module however there's no mechanism for ensuring this is kept up to date.

**Comment by gilesw** [comment]
I'm struggling a bit to get started on this work. The defaults_from code is here:-

modules/utilities/logic/include_role.py

presumably this DOCUMENTATION variable is parsed somehow to provide that functionality. The nub of the problem is being able to load defaults or any files from outside the role path, and that defaults loading code must be elsewhere..

**Comment by gilesw** [comment]
I've tried some of the other include roles options.

```
- name: include geerlingguy.nginx
  include_role:
    name: geerlingguy.nginx
  vars:
    nginx_client_max_body_size: "{{ liferay_nginx_client_max_body_size }}"
```

like using vars/main.yml in the calling module this is not overridable at group_var level.
