### ISSUE TITLE
file based modules change ownership after editing.

### ISSUE THREAD

**Issue by cbeckley** [ansible/ansible#25389]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION

```
2.3.0.0
```

##### OS / ENVIRONMENT
Centos 7

##### SUMMARY
If you use the lineinfile module to edit a file and if the file belongs to a different user than the user running Ansible, lineinfile will change the owner of the file to the user running Ansible.

##### STEPS TO REPRODUCE
Create a file owned by user A, that is rw to user B via group permissions:
-rw-rw-r-- 1 cloud_ops cloud_ops 119 Jun 1 14:10 hosts
User B in this case belongs to the cloud_ops group.

This is the lineinfile from the playbook

```yaml
      - name: Add the newly created EC2 instance(s) to the local host group
        local_action: lineinfile
                      dest="./hosts"
                      regexp={{ item.private_dns_name }}
                      insertafter="[provisioning]" line={{ item.private_dns_name }}
        with_items:
         - "{{ ec2.instances }}"
```

##### EXPECTED RESULTS
It would be expected that the ownership stay the same.

##### ACTUAL RESULTS
The file will be edited, but the new owner of the file will be user B.
