### ISSUE TITLE
CentOS 7: System V init script can't be enabled

### ISSUE THREAD

**Issue by jacobweber** [ansible/ansible#25440]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
```
ansible 2.2.0.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Managing a CentOS 7.3 box from a CentOS 6.9 hub

##### SUMMARY
If I install an old System V init script in /etc/init.d, and try to enable it with the `service` module, it will say "Could not find the requested service".

##### STEPS TO REPRODUCE

```yaml
- name: install httpd init script
  template: src=httpd.j2 dest=/etc/init.d/httpd mode=0755 owner=root group=root

- name: enable httpd
  service: name=httpd enabled=yes
```

##### EXPECTED RESULTS
Although CentOS 7 uses systemd, it should still be able to support System V init scripts. Ansible should fall back to them when they're available.

##### ACTUAL RESULTS
```
failed: [myhost] (u'name': u'myhost', u'base_dir': u'/usr/local/apache2/htdocs'}) => {
    "failed": true, 
    "invocation": {
        "module_args": {
            "daemon_reload": false, 
            "enabled": true, 
            "masked": null, 
            "name": "httpd", 
            "state": null, 
            "user": false
        }
    }, 
    "msg": "Could not find the requested service \"'httpd'\": "
}
```

Same issue as #915...more details there.
