### ISSUE TITLE
win_iis_website ssl flag does nothing

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25465]
_From @nathanwebsterdotme on August 17, 2016 12:40_

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_iis_website
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (detached HEAD 35da6ba9d1) last updated 2016/07/25 09:38:23 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 45128c8bab) last updated 2016/07/25 09:38:23 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 511752e53a) last updated 2016/07/25 09:38:23 (GMT +000)
  config file = ********
  configured module search path = ['modules']
```
##### OS / ENVIRONMENT

Server 2012 R2
##### SUMMARY

The ssl flag on web_iis_website doesn't do anything.
##### STEPS TO REPRODUCE

Run the win_iis_webssite module with 'ssl' option set to true. 

```
    - name: IIS | Create Website with SSL Binding
      win_iis_website:
        name: "SSLSite"
        physical_path: "C:\Websites\SSLSite"
        application_pool: "SSLSite-AppPool"
        hostname: "SSLsite.test.com"
        state: "present"
        ssl: true
```

##### EXPECTED RESULTS

SSL binding attached to website upon creation
##### ACTUAL RESULTS

No SSL binding is created on IIS.

_Copied from original issue: ansible/ansible-modules-extras#2746_
