### ISSUE TITLE
win_iis_webbinding fails to assign specified certificate_hash

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25466]
_From @nathanwebsterdotme on August 16, 2016 13:44_

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

win_iis_webbinding
##### ANSIBLE VERSION

```
ansible 2.1.1.0 (detached HEAD 35da6ba9d1) last updated 2016/07/25 09:38:23 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 45128c8bab) last updated 2016/07/25 09:38:23 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 511752e53a) last updated 2016/07/25 09:38:23 (GMT +000)
  config file = /tmp/***/ansible/ansible.cfg
  configured module search path = ['modules']
```
##### CONFIGURATION

[defaults]
roles_path  = roles
library     = modules
##### OS / ENVIRONMENT

Server 2012 R2
##### SUMMARY

win_iis_webbinding module is not assigning the certificate specified in the certificate_hash variable.
##### STEPS TO REPRODUCE

- Install certificate on to IIS server (we've tested this with a PS script and installing manually, it's installed properly).
- Paste the certificate hash in to the win_iis_webbinding module
- After the play, the IIS website should have a HTTPS web binding attached with the specified certificate - it doesn't. 

```
    - name: IIS | Add HTTPS binding with cert for Default Website
      win_iis_webbinding:
        name: "Default Web Site"
        protocol: https
        port: 443
        state: present
        certificate_hash: ‎"***VALID CERT HASH OF INSTALLED CERT*****"
```

##### EXPECTED RESULTS

HTTPS web binding created with specified certificate used. 
##### ACTUAL RESULTS

A web binding is created successfully for HTTPS, but the certificate is not attached properly. 

```
changed: [ec2-**-***-***-***.eu-west-1.compute.amazonaws.com] => {"added": [{"bindingInformation": "*:443:", "certificateHash": "", "certificateStoreName": "", "isDsMapperEnabled": false, "protocol": "https", "sslFlags": 0}], "changed": true, "invocation": {"module_name": "win_iis_webbinding"}, "ip": "0.0.0.0", "matched": [], "parameters": {"Name": "Default Web Site", "Port": 443, "Protocol": "https"}, "port": 443, "removed": []}
```

_Copied from original issue: ansible/ansible-modules-extras#2733_

**Comment by dagwieers** [comment]
_From @nathanwebsterdotme on August 16, 2016 13:46_

I think this has something to do with the variable names; there is a mixture of "certificatehash" and "certificateHash" being used which I think is causing the problem.  

If I explicitly define the cert hash value in to the module ps1 file, I can get it to work.

**Comment by dagwieers** [comment]
_From @ansibot on August 16, 2016 13:54_

@whenrik, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
_From @ansibot on September 11, 2016 14:53_

@whenrik, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
_From @nathanwebsterdotme on September 15, 2016 13:57_

Any updates ?

**Comment by dagwieers** [comment]
_From @ahnooie on September 30, 2016 17:51_

@nathanwebsterdotme I don't know why it isn't working for you but thought I'd let you know the module works for me me using Server 2012 R2.  PowerShell seems to be case insensitive so I don't think that's the issue.

**Comment by dagwieers** [comment]
_From @ansibot on September 30, 2016 18:7_

@whenrik, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
_From @Klezst on November 2, 2016 14:31_

The module checks if a binding with the specified name, host header, protocol, port, and IP exists. If not, it creates the binding. It does not check that the existing binding is using the specified certificate. Thus, if the binding already exists on the system and you attempt to add a certificate to it the module makes no changes. Perhaps this is what @nathanwebsterdotme experienced. If so, the steps to reproduce can be amended as follows:

**STEPS TO REPRODUCE**
- Install a certificate into IIS
- Run the Ansible task without a certificate hash

```
- name: IIS | Add HTTPS binding with cert for Default Website
      win_iis_webbinding:
        name: "Default Web Site"
        protocol: https
        port: 443
        state: present
```
- Run the Ansible task with a certificate hash

```
- name: IIS | Add HTTPS binding with cert for Default Website
      win_iis_webbinding:
        name: "Default Web Site"
        protocol: https
        port: 443
        state: present
        certificate_hash: ‎"****CERT HASH*****"
```
- The web binding is not associated with the certificate (unexpected behavior)
- If you delete the web binding and run the Ansible task with a certificate hash the expected binding is created
