### ISSUE TITLE
win_iis_webbinding references property 'sslFlags' which did not exist before IIS 8

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25470]
_From @Matt-Byrne on August 16, 2016 5:49_

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

win_iis_webbinding
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /home/ubuntu/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

IIS 7.5 on Windows Server 2008R2
##### SUMMARY

Adding bindings to a website in IIS 7.5 (and I suspect earlier versions) throws the following error:

"msg": "The property 'sslFlags' cannot be found on this object. Verify that the property exists."

This seems to be because win_iis_webbinding.ps1 attempts to access the sslFlags property of the current website before it proceeds with the addition, but this property was only added in IIS 8 (ref: https://www.iis.net/configreference/system.applicationhost/sites/site/bindings/binding)

It's worth noting, the binding does get created, despite the error.
##### STEPS TO REPRODUCE

```
- name: Add additional bindings
    win_iis_webbinding:
        name: "{{ site_name }}"
        state: present
        protocol: http
        ip: '*'
        port: 80
        host_header: "{{ item }}"
    with_items: "{{ site_additional_bindings | default([]) }}"
```

##### EXPECTED RESULTS

```
TASK [Add additional bindings] *************************************************
ok: [x.x.x.x]
```
##### ACTUAL RESULTS

```
TASK [Add additional bindings] *************************************************
failed: [x.x.x.x] (item=testbinding.com) => {"failed": true, "item": "testbinding.com", "msg": "The property 'sslFlags' cannot be found on this object. Verify that the property exists."}
```

_Copied from original issue: ansible/ansible-modules-extras#2728_
