### ISSUE TITLE
win_acl error with LDAP signing enabled using Univention

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25475]
_From @philicious on November 22, 2016 15:37_

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_acl

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION
none / default

##### OS / ENVIRONMENT
managing Windows7 from MacOS 10.11

##### SUMMARY
win_acl is failing if having LDAP signing enabled

##### STEPS TO REPRODUCE

```
- name: Give Domain Users the required access rights for folder
  win_acl:
    path: 'C:\Users\Public\Desktop\somefolder'
    user: 'DOMAIN\Domain Users'
    rights: 'ReadAndExecute,Write,ListDirectory,CreateDirectories,CreateFiles,DeleteSubdirectoriesAndFiles,Synchronize,Traverse'
    type: 'allow'
```

##### EXPECTED RESULTS
ACL for that folder updated

##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "failed": true, "msg": "exception calling \"FindOne\" with 0 argument(s):  \"A more secure authentication method is required for this server.\r\n\""}
```

_Copied from original issue: ansible/ansible-modules-extras#3519_
