### ISSUE TITLE
win_iis_webapplication: slashes in physical path are not converted to windows style

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25471]
_From @aensidhe on December 29, 2015 19:41_

##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

win_iis_webapplication module
##### ANSIBLE VERSION

N/A
##### SUMMARY

win_iis_website converts them. Example:

vars somewhere:

```
path: c:/sites/https/develop
```

playbook:

```
- name: create website
  win_iis_website:
    name: "{{ name }}"
    state: started
    application_pool: "{{ appdomain }}"
    physical_path: "{{ path }}/web"

- name: create rest virtual folder
  win_iis_webapplication:
    name: rest
    state: present
    site: "{{ name }}"
    physical_path: "{{ path }}/api"
    application_pool: "{{ appdomain }}"
```

Website will work ok, webapplication will always fail with 404.

_Copied from original issue: ansible/ansible-modules-extras#1436_
