### ISSUE TITLE
win_scheduled_task: Disable existing Scheduled Task

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#25478]
_From @willuk2010 on November 24, 2016 21:27_

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_scheduled_task 

##### ANSIBLE VERSION

```
ansible 2.1.0.0
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
```

##### CONFIGURATION

no changes to ansible.cfg, or ansible variables set.

##### OS / ENVIRONMENT

Ansible running from = RHEL 6.7 (Santiago)
OS i'm managing = Windows 2008 r2

##### SUMMARY

trying to use  win_scheduled_task to disable an existing scheduled task, using;

win_scheduled_task: name="ServerManager" enable=no state=present  returns,

"Missing required argument: execute"

##### STEPS TO REPRODUCE

as above, simply using 

win_scheduled_task: name="ServerManager" enable=no state=present

results in an failed message, stating "Missing required argument: execute" even though execute is not a required option according to http://docs.ansible.com/ansible/win_scheduled_task_module.html.

```
- name: Windows Build Test
   hosts: all
   tasks:
     - name: Disable Server Manager Scheduled Task
       win_scheduled_task: name="ServerManager" enable=no state=present
```

##### EXPECTED RESULTS

I would have expected the existing scheduled task to be disabled, and even then not error asking for an execute option, when its not required.

##### ACTUAL RESULTS

```
server1.domain.com]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "win_scheduled_task"}, "msg": "Missing required argument: execute"}
```

_Copied from original issue: ansible/ansible-modules-extras#3544_
