### ISSUE TITLE
debconf misreports changed status for boolean variables

### ISSUE THREAD

**Issue by pjnagel** [ansible/ansible#25481]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
debconf module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/pieter.nagel/setup/lautus_ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Nothing relevant

##### OS / ENVIRONMENT
Ubuntu 16.04.2 LTS

##### SUMMARY
When using debconf module to set a boolean value to true, the module keeps reporting a 'changed' status even if the value is already true.

##### STEPS TO REPRODUCE
Run the following task twice:

```yaml
- name: 'Accept the Oracle Java license'
  debconf:
    name: oracle-java8-installer
    question: shared/accepted-oracle-license-v1-1
    vtype: boolean
    value: true
```

##### EXPECTED RESULTS
At least on the second run, I expect the task to show ok in green.

##### ACTUAL RESULTS
I see changed in yellow everytime. Running with --diff reveals that the module does not know that 'true' and 'True' are already the same value:
```
TASK [tau_common : Accept the Oracle Java license] ****
--- before
+++ after
@@ -1,3 +1,3 @@
 {
-    "shared/accepted-oracle-license-v1-1": "true"
+    "shared/accepted-oracle-license-v1-1": "True"
 }

changed: [dev3.lautus.net]
```
