### ISSUE TITLE
lxd connection only works on localhost

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible/ansible#25489]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/lxd_container_module.html

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Xubuntu 16.04

##### SUMMARY
The lxd connection plugin can ONLY interact with containers running on localhost.

See https://github.com/ansible/ansible/issues/18881 for a discussion about changing this.

##### EXPECTED RESULTS
I would expect some information about this on the module documentation page.

Something along the lines of "Running commands in containers via the lxd connection plugin only works on localhost, if you need to run commands in a container running on a remote machine, use the command module instead"

It would be nice if the documentation would also show how to install python (and maybe ssh) using the command module into an LXD container.

##### ACTUAL RESULTS
Trial, error, frustration... and missing documentation.

The fact that this only works on localhost is only implied from the examples and not made explicit.

**Comment by ansibot** [comment]
cc @hnakamur
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hnakamur** [comment]
Sorry about frustration.
As for installing python, the first example in the documentation does show how to install python using the raw module.

**Comment by MarkusTeufelberger** [comment]
Yes, but it delegates to "mycontainer", which will only work on localhost and is still part of the "connection: local" task group.

I meant something like "command: lxc exec mycontainer -- apt install python"

**Comment by xmj** [comment]
You can use `delegate_to` in combination with `lxd_container`.

**Comment by ansibot** [comment]
cc @kevensen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MarkusTeufelberger** [comment]
> You can use `delegate_to` in combination with `lxd_container`.

Even if that container is not running on localhost, but on a remote LXD host? I highly doubt that.

**Comment by xmj** [comment]
@MarkusTeufelberger did you try it? "works for me" ;-)

**Comment by MarkusTeufelberger** [comment]
To be clear: LXD is not even installed on localhost but you can `delegate_to` a container that is running on a remote via its name?

**Comment by xmj** [comment]
I'm running something like:
```
- name: do things
  lxd_container: 
    ...
  delegate_to: "{{ container_host }}"
```

from FreeBSD 12.0-CURRENT, which most definitely has no lxc/lxd installed, and it works fine.

You'd delegate to the remote machine *hosting* the containers.

**Comment by MarkusTeufelberger** [comment]
I'm talking about this part of the documentation:

````
# An example for creating a Ubuntu container and install python
- hosts: localhost
  connection: local
  tasks:
    - name: Create a started container
      lxd_container:
        name: mycontainer
        state: started
        source:
          type: image
          mode: pull
          server: https://images.linuxcontainers.org
          protocol: lxd
          alias: ubuntu/xenial/amd64
        profiles: ["default"]
        wait_for_ipv4_addresses: true
        timeout: 600

    - name: check python is installed in container
      delegate_to: mycontainer
      raw: dpkg -s python
      register: python_install_check
      failed_when: python_install_check.rc not in [0, 1]
      changed_when: false

    - name: install python in container
      delegate_to: mycontainer
      raw: apt-get install -y python
      when: python_install_check.rc == 1
````
Starting a container on a remote is easy - but I need to run commands inside them to install/configure sshd and python.

The example in the docs will only work on localhost from my experience and it would be nice to document this (and give an example on how to run commands without SSH on a remote container).

**Comment by xmj** [comment]
You could declare them inside of your inventory, have `sshd` running inside each container and then use OpenSSH tunneling (with `-J` or `-o ProxyCommand` glue in `ansible_ssh_common_args`)

**Comment by MarkusTeufelberger** [comment]
That's what I plan on doing (and what I have done already), but LXD containers typically don't have sshd running inside them when freshly pulled. This means you need to install it first somehow via a raw command. These raw commands are the domain of the lxd connection plugin (https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/connection/lxd.py). According to #18881, this plugin only works on localhost for now.

The documentation of http://docs.ansible.com/ansible/latest/lxd_container_module.html makes it sound like the lxd connection plugin could also work on remote hosts. The only way I know of how to actually run commands inside an LXD container on remote hosts right now is to run a `command` that runs `lxc exec ...` on that host.

**Comment by xmj** [comment]
@bcoca might know about the status of chaining connection plugins, which, while very useful, is afaik still not possible.

**Comment by bcoca** [comment]
really need to rename `lxd` plugin to `lxc_cli`  to clarify

@xmj stackable connections are still not on the horizon

**Comment by tlc** [comment]
FWIW, there is a 3rd party plugin on github, https://github.com/antifuchs/ansible-sshlxd-connection,
that appears to address this.  I've never used it.

**Comment by candlerb** [comment]
Perhaps more by luck than design, lxd_connection plugin works with hostnames of the form

    <remote>:<container>

to talk to a remote lxd server over the network.

This means you can configure your containers in the inventory like this:

```
mycontainer  ansible_connection=lxd ansible_host=otherhost:mycontainer
```

You must have pre-configured the named remote (in the example it's `otherhost`) in lxc's local configuration - that is, as shown by `lxc remote list`.  Unfortunately there's no `lxd_remote` ansible module to do that for you (#18881), so you need to do `lxc remote add` by hand.  Also, the user running ansible must have access to the relevant key/cert and config, usually under `~/.config/lxc/`.

This all works because the lxd connection plugin shells out to `lxc exec` under the hood, so anything that works with `lxc exec` works here too.

Conversely, the `lxd_container` and `lxd_profile` modules *don't* shell out to lxc; they talk the native lxd protocol, by default via the local unix domain socket.

With a bit of care, you can make the inventory work with those modules too, when your `ansible_host` is of the form `<remote>:<container>`

Here's how I do it:

```
- name: create and start container
  delegate_to: '{{ ansible_host.split(":").0 }}'
  lxd_container:
    name: '{{ ansible_host.split(":").1 }}'
    state: started
    source: ...
    wait_for_ipv4_addresses: true/false
    timeout: 600
```

For local containers, use `ansible_connection=lxd ansible_hostname=local:<container>`

This relies on ansible having an inventory entry with the same name as the named lxd remote.  There is already a remote called `local` (see `lxc remote list`), hence you need an inventory item for this:

```
local ansible_connection=local
```

Similarly for all other named remotes: you need to have an inventory item with matching name so that ansible can ssh to that host, and delegate the `lxd_container` operation to it.

This works, but it's messy.  Consider what happens when you access container `foo:bar`:

* For the `lxd` connection plugin, the local machine makes a native lxd connection over the network to the URL in the named remote 'foo'
* But for the `lxd_container` module, the local machine makes an *ssh* connection to the inventory host called "foo", running the ansible `lxd_container` module *on that host*

So the other way to do it is to give `lxd_container` the *url* of the remote node, and have it talk the lxd protocol over the network.  You will also have to set `cert_file` and `key_file` (which you can read from `~/.config/lxc/client.crt` and `~/.config/lxc/client.key`), and you'll have to set `trust_password`.  Also, you have to lookup the remote name to convert this to the correct URL, which you can do by parsing `~/.config/lxc/config.yml`.

Note: the last time I looked, the lxd_container module didn't check the cert presented by the remote host - it has no known certificate to compare it with - so it's insecure to use over the network.  That is, it's vulnerable to a MITM attack.  See #18882

Anyway, it would be great if there were more consistency: either change the lxd connection plugin to use the native lxd protocol (like lxd_container), or change the lxd_container module to shell out to lxc.
