### ISSUE TITLE
Flush handlers by name

### ISSUE THREAD

**Issue by sean797** [ansible/ansible#25491]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
Flush handlers by name

##### ANSIBLE VERSION
```
ansible 2.3.0.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Add a `handler_names` list argument to the `flush_handlers` module.

Kind of similar to https://github.com/ansible/ansible/issues/10829 but that is asking for an immediate flush.

Current work around is shown at https://github.com/ansible/ansible/issues/10829#issuecomment-260183546

##### STEPS TO REPRODUCE
I suggest either
```yaml
- name: some task
  flush: 
    - my first handler
    - my third handler
```
OR
``` yaml
- name: flush handlers
  meta: 
    flush_handlers: 
      - my first handler
      - my third handler
```

This is useful when you have a situation wherein most scenarios you want to run something as a "traditional handler" (at the end of a run) but it one situation you need to run it right away, do something else, then notify the handler again.

##### EXPECTED RESULTS
Flush handlers listed

##### ACTUAL RESULTS
Currently you can only flush all handlers.
