### ISSUE TITLE
vyos modules no connection possible

### ISSUE THREAD

**Issue by stegmajo** [ansible/ansible#25495]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- vyos_command
- vyos_config
- vyos_facts
- vyos_system

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### CONFIGURATION

- Nothing was changed

##### OS / ENVIRONMENT

- macOS Sierra, Version: 10.12.5 (16F73)

##### SUMMARY

I try to connect to a vyos system via the vyos modules, but I always get an error

##### STEPS TO REPRODUCE

I tried to run the following code against a vyos installed on a local VM to which I can connect via ssh. And I also tried to run this code remotely against a Vyatta running in a datacenter. But on both servers I get the same error.

```yaml
- name: deploy vyatta basic settings
  hosts: vyatta
  tasks:

  - name: get all facts from vyos
    vyos_facts:
      gather_subset: all
```

##### ACTUAL RESULTS

```
TASK [get all facts from vyos] **********************************************************************************************************************************************************
fatal: [192.168.56.2]: FAILED! => {"changed": false, "failed": true, "msg": "invalid connection specified, expected connection=local, got ssh"}

```
