### ISSUE TITLE
Module fortios_ipv4_policy does not add new policies

### ISSUE THREAD

**Issue by m2106lw** [ansible/ansible#25508]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module: [fortios_ipv4_policy](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/fortios/fortios_ipv4_policy.py)

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

No special configuration options.

##### OS / ENVIRONMENT

FROM: CentOS Linux release 7.3.1611 (Core)
TO: Fortigate 200B

##### SUMMARY

The FortiosIPV4 module for Ansible can edit and delete existing policies, but it cannot create new policies.

##### STEPS TO REPRODUCE

ID can be 0 or any policy number that doesn't already exist.

```yaml
  - name: Try adding a new policy (Adding Public Web)
    fortios_ipv4_policy:
      host: fortigate_box
      username: user
      password: password
      vdom: "{{ VDOM }}"
      id: "{{ ID }}"
      state: present
      src_intf: "{{ SRCINTF }}"
      dst_intf: "{{ DSTINTF }}"
      src_addr: "{{ SRCADDR }}"
      dst_addr: "{{ DSTADDR }}"
      policy_action: "{{ ACTION }}"
      services: "{{ SERVICES }}"
      timeout: 20
```

##### EXPECTED RESULTS

A new policy should have been created.

##### ACTUAL RESULTS

An error arises because the source address can't be found. If run with an existing policy the error does not occur. Only when creating a new policy does ansible say that the source address is not there. Only the source address gives errors.

```
Verbose error code:
"msg": "Unable to commit change, check your args, the error was [(u'-3', u'set srcaddr \"db\"')]", 
"msg_error_list": [
    {
        "error_code": "-3", 
        "error_string": "set srcaddr \"db\"", 
         "error_type": "Object not found"
    }
]


PLAY [localhost] *********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Try adding a new policy (Adding Public Web)] ***********************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to commit change, check your args, the error was [(u'-3', u'set srcaddr \"db\"')]", "msg_error_list": [{"error_code": "-3", "error_string": "set srcaddr \"db\"", "error_type": "Object not found"}]}

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1 

```

**Comment by ansibot** [comment]
cc @bjolivot
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bjolivot** [comment]
Hello,

Could you post partial config file with "db" address block
and playbook -vvv ?

I saw same error when:
 - address dont exists
 - address exists but not in corresponding interface
 - address exists but not in this vdom

you can try to ping me on IRC (freenode network,  ansible-devel channel) if you want more active help

needs_info

**Comment by m2106lw** [comment]
```Fortigate_Box (DEVTEST) # show firewall address

config firewall address
    edit "all"
    next
    edit "web"
        set associated-interface "V.101-web"
        set subnet 10.42.42.0 255.255.255.0
    next
    edit "app"
        set associated-interface "V.102-app"
        set subnet 10.42.43.0 255.255.255.0
    next
    edit "web1"
        set associated-interface "V.101-web"
        set subnet 10.42.42.2 255.255.255.255
    next
    edit "app1"
        set associated-interface "V.102-app"
        set subnet 10.42.43.2 255.255.255.255
    next
    edit "db"
        set associated-interface "V.103-db"
        set subnet 10.42.44.0 255.255.255.0
    next
end
```

Here is the playbook run:
```
ansible-playbook test.yml --extra-vars "VDOM=DEVTEST ID=0 SRCINTF=V.103-db DSTINTF=V.102-app SRCADDR=db DSTADDR=app1 ACTION=accept SERVICES=PING" -vvv
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mwilliams
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mwilliams/.ansible/tmp/ansible-tmp-1497015225.61-120430627012418 `" && echo ansible-tmp-1497015225.61-120430627012418="` echo /home/mwilliams/.ansible/tmp/ansible-tmp-1497015225.61-120430627012418 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpX7RHxv TO /home/mwilliams/.ansible/tmp/ansible-tmp-1497015225.61-120430627012418/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/mwilliams/.ansible/tmp/ansible-tmp-1497015225.61-120430627012418/ /home/mwilliams/.ansible/tmp/ansible-tmp-1497015225.61-120430627012418/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/mwilliams/.ansible/tmp/ansible-tmp-1497015225.61-120430627012418/setup.py; rm -rf "/home/mwilliams/.ansible/tmp/ansible-tmp-1497015225.61-120430627012418/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Try adding a new policy (Adding Public Web)] *****************************
task path: /home/mwilliams/Desktop/ansible/test.yml:5
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/fortios/fortios_ipv4_policy.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: mwilliams
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/mwilliams/.ansible/tmp/ansible-tmp-1497015226.03-272507480057776 `" && echo ansible-tmp-1497015226.03-272507480057776="` echo /home/mwilliams/.ansible/tmp/ansible-tmp-1497015226.03-272507480057776 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp0rYxJO TO /home/mwilliams/.ansible/tmp/ansible-tmp-1497015226.03-272507480057776/fortios_ipv4_policy.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/mwilliams/.ansible/tmp/ansible-tmp-1497015226.03-272507480057776/ /home/mwilliams/.ansible/tmp/ansible-tmp-1497015226.03-272507480057776/fortios_ipv4_policy.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/mwilliams/.ansible/tmp/ansible-tmp-1497015226.03-272507480057776/fortios_ipv4_policy.py; rm -rf "/home/mwilliams/.ansible/tmp/ansible-tmp-1497015226.03-272507480057776/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "application_list": null, 
            "av_profile": null, 
            "backup": false, 
            "backup_filename": null, 
            "backup_path": null, 
            "comment": null, 
            "dst_addr": [
                "app1"
            ], 
            "dst_addr_negate": false, 
            "dst_intf": "V.102-app", 
            "fixedport": false, 
            "host": "Fortigate_Box", 
            "id": 0, 
            "ips_sensor": null, 
            "nat": false, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "policy_action": "accept", 
            "poolname": null, 
            "schedule": "always", 
            "service": [
                "PING"
            ], 
            "service_negate": false, 
            "services": "PING", 
            "src_addr": [
                "db"
            ], 
            "src_addr_negate": false, 
            "src_intf": "V.103-db", 
            "state": "present", 
            "timeout": 20, 
            "username": "username", 
            "vdom": "DEVTEST", 
            "webfilter_profile": null
        }
    }, 
    "msg": "Unable to commit change, check your args, the error was [(u'-3', u'set srcaddr \"db\"')]", 
    "msg_error_list": [
        {
            "error_code": "-3", 
            "error_string": "set srcaddr \"db\"", 
            "error_type": "Object not found"
        }
    ]
}
	to retry, use: --limit @/home/mwilliams/Desktop/ansible/test.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

This will happen when the ID is equal to 0 or a number that doesn't exist already.
Let me know if there is anything else you need.

**Comment by bjolivot** [comment]
I can't reproduce your problem.
Are you sure your "db" address is in the "DEVTEST" vdom ?

Could you download address management module here:
https://github.com/ansible/ansible/pull/21542/files#diff-cece00922d0648f114607e79c02036e7
And try to add db address before adding policy ?

Something like:
```yml
  - name: Add DB address
    fortios_address:
      host: fortigate_box
      username: user
      password: password
      vdom: "{{ VDOM }}"
      name: "db"
      state: present
      value: "{{ db_ip}}"
      timeout: 20
```

**Comment by bjolivot** [comment]
needs_info

**Comment by m2106lw** [comment]
Running a playbook like this:
```
  - name: Add DB address
    fortios_address:
      host: fortigate_box
      username: user
      password: pass
      vdom: "{{ VDOM }}"
      name: "db"
      state: present
      value: "{{ ip }}"
      timeout: 20
```
Will result in a success
```
ansible-playbook test.yml --extra-vars "VDOM=DEVTEST ID=0 SRCINTF=V.103-db DSTINTF=V.102-app SRCADDR=db DSTADDR=app1 ACTION=accept SERVICES=PING"
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Try adding a new policy (Adding Public Web)] *****************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0  
```

With further testing it seems like as long as we modify the addresses with ansible we don't have any issues modifying the policies with ansible.

**Comment by voipmeister** [comment]
Hello @bjolivot 

I can confirm this, sort of. I think that the problem lies in the order in which the change is being done by ansible.

### Working playbook example

This will work, regardless whether the rule is present or not:
```
    - name: test policy
      fortios_ipv4_policy:
        host: "{{ forti_address }}"
        username: "{{ forti_user }}"
        password: "{{ forti_pass }}"
        id: 444
        comment: "no comment (created by ansible)"
        src_intf:
          - vl1000
        src_addr:
          - all
        dst_intf:
          - vl2000
          - vl3000
        dst_addr:
          - all
        services:
          - HTTP
          - HTTPS
        nat: True
        state: present
        policy_action: accept
        logtraffic: disable
      tags:
        - testpolicy
```

This would have change_string of (please not the order of set srcaddr and set srcintf):
```
"change_string": "    config firewall policy\n        edit 444\n          set comment \"no comment (created by ansible)\"\n          set nat enable\n          set service \"HTTP\" \"HTTPS\"\n          set schedule always\n          set srcaddr \"all\"\n          set dstintf \"vl2000\" \"vl3000\"\n          set srcintf \"vl1000\"\n          set action accept\n          set dstaddr \"all\"\n          set logtraffic disable\n        next\n    end\n",
```

### Failing playbook example

However, this will *not* work (please note that *some_serverA* is already created and tied to interface *vl1000*):
```
    - name: test policy
      fortios_ipv4_policy:
        host: "{{ forti_address }}"
        username: "{{ forti_user }}"
        password: "{{ forti_pass }}"
        id: 444
        comment: "no comment (created by ansible)"
        src_intf:
          - vl1000
        src_addr:
          - some_serverA
        dst_intf:
          - vl2000
          - vl3000
        dst_addr:
          - all
        services:
          - HTTP
          - HTTPS
        nat: True
        state: present
        policy_action: accept
        logtraffic: disable
      tags:
        - testpolicy
```

The error is:
```
    "msg_error_list": [
        {
            "error_code": "-3",
            "error_string": "set srcaddr \"some_serverA\"",
            "error_type": "Object not found"
        }
    ]
```

### Root cause

The reason that modifying an existing rule works, is that the source interface might already be set to something else then 'any' (and the address object is tied to that interface).  

The problem (I think) is that the srcaddr statement is entered *before* the srcintf statement. Therefore, address objects that are specifically tied to an interface (like some_serverA in my example to the vl1000 interface) cannot be allocated in the policy because the source interface is still *any*, to which the some_serverA is not tied.

### CLI test confirmation

Confirmed by a CLI test:
```
FGT70D3Z14000954 # config firewall policy
FGT70D3Z14000954 (policy) # edit 444
new entry '444' added
FGT70D3Z14000954 (444) # set srcaddr some_serverA
entry not found in datasource
value parse error before 'some_serverA'
Command fail. Return code -3
FGT70D3Z14000954 (444) # set srcintf vl1000
FGT70D3Z14000954 (444) # set srcaddr some_serverA
FGT70D3Z14000954 (444) #
```

### Suggested fixes

- modify change_string so srcintf comes before srcaddr
- modify change_string so dstintf comes before dstaddr

On a side note, I have looked at fortios.py, but don't feel confident enough to modify it and set a PR.

needs_contributor
