### ISSUE TITLE
iosxr_config shows passwords to devices

### ISSUE THREAD

**Issue by jmighion** [ansible/ansible#25501]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

iosxr_config
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.0.0
  config file = /home/jmighion/git/blank-ansible-repo/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

When connecting to a device the password in the provider object does not get set to no_log. The other *_config modules import the module_utils' check_args function and call that to ensure that the password is set to `no_log: true`.
##### STEPS TO REPRODUCE

```yaml
- name: dev
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Apply config line password changes
      iosxr_config:
        provider: "{{ cli }}"
        lines: password {{ read_pass }}
```

```
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ cli_username }}"
  password: "{{ cli_password }}"
```

##### EXPECTED RESULTS

Passwords should not be logged.
##### ACTUAL RESULTS

Passwords are being logged.

**Comment by ansibot** [comment]
cc @privateip @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
I wonder if `no_log: True` at the task level would help for this. e.g.

```yaml
- name: dev
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Apply config line password changes
      iosxr_config:
        provider: "{{ cli }}"
        lines: password {{ read_pass }}
        no_log: True
```
