### ISSUE TITLE
nxos_pim_interface errors out for transport nxapi

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#25510]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_pim_interface

##### NXOS VERSION
7.0(3)I3(1)

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0 (devel 781bb44b02) last updated 2017/06/08 15:20:16 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible-playbook
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
running on Ubuntu 14.04

##### SUMMARY
The module errors out in latest `devel` when using transport `nxapi`.

##### STEPS TO REPRODUCE
```yaml
---
- debug: msg="START TRANSPORT:NXAPI nxos_pim_interface sanity test"

- name: configure
  nxos_pim_interface:
    interface: eth1/5
    state: absent
    provider: "{{ nxapi }}"

- name: configure
  nxos_pim_interface:
    interface: eth1/5
    dr_prio: 10
    hello_interval: 40
    state: present
    provider: "{{ nxapi }}"

- name: configure
  nxos_pim_interface:
    interface: eth1/5
    jp_policy_in: JPIN
    jp_policy_out: JPOUT
    jp_type_in: routemap
    jp_type_out: routemap
    provider: "{{ nxapi }}"

- name: configure
  nxos_pim_interface:
    interface: eth1/5
    state: default
    provider: "{{ nxapi }}"

- debug: msg="END TRANSPORT:NXAPI nxos_pim_interface sanity test"
```

##### EXPECTED RESULTS
Expect nxapi_pim_interface module to run properly.

##### ACTUAL RESULTS FOR TRANSPORT NXAPI

```shell
TASK [nxos_pim_interface : debug] *************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_pim_interface/tests/nxapi/sanity.yaml:2
ok: [n9k] => {
    "failed": false, 
    "msg": "START TRANSPORT:NXAPI nxos_pim_interface sanity test"
}

TASK [nxos_pim_interface : configure] *********************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_pim_interface/tests/nxapi/sanity.yaml:4
<n9k> connection transport is nxapi
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/nxos.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/_six.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/connection.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/urls.py
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_pim_interface.py
<n9k> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1496952476.75-27913149598597 `" && echo ansible-tmp-1496952476.75-27913149598597="` echo $HOME/.ansible/tmp/ansible-tmp-1496952476.75-27913149598597 `" ) && sleep 0'
<n9k> PUT /tmp/tmp8xRLVS TO /root/.ansible/tmp/ansible-tmp-1496952476.75-27913149598597/nxos_pim_interface.py
<n9k> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1496952476.75-27913149598597/ /root/.ansible/tmp/ansible-tmp-1496952476.75-27913149598597/nxos_pim_interface.py && sleep 0'
<n9k> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1496952476.75-27913149598597/nxos_pim_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1496952476.75-27913149598597/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_J4iM9L/ansible_module_nxos_pim_interface.py", line 723, in <module>
    main()
  File "/tmp/ansible_J4iM9L/ansible_module_nxos_pim_interface.py", line 623, in main
    if get_interface_mode(interface, intf_type, module) == 'layer2':
  File "/tmp/ansible_J4iM9L/ansible_module_nxos_pim_interface.py", line 263, in get_interface_mode
    interface_table = body[0]['TABLE_interface']['ROW_interface']
TypeError: string indices must be integers

fatal: [n9k]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_J4iM9L/ansible_module_nxos_pim_interface.py\", line 723, in <module>\n    main()\n  File \"/tmp/ansible_J4iM9L/ansible_module_nxos_pim_interface.py\", line 623, in main\n    if get_interface_mode(interface, intf_type, module) == 'layer2':\n  File \"/tmp/ansible_J4iM9L/ansible_module_nxos_pim_interface.py\", line 263, in get_interface_mode\n    interface_table = body[0]['TABLE_interface']['ROW_interface']\nTypeError: string indices must be integers\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/root/agents-ci/ansible/test/integration/nxos.retry

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
n9k          : ok=6    changed=0    unreachable=0    failed=1   

```
