### ISSUE TITLE
ec2_route_table fails with Unable to associate subnets for route table RouteTable:rtb-XXXXXXXX

### ISSUE THREAD

**Issue by trinitronx** [ansible/ansible#25521]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`ec2_vpc_route_table`: `ansible/lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py`

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0 (devel 1ce5fcf061) last updated 2017/02/08 22:36:02 (GMT +000)
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

OS running Ansible from: `CentOS Linux 7 (Core)`
OS managing: `N/A` (AWS resource only)

##### SUMMARY

When managing an existing EC2 VPC Route Table with the `ec2_vpc_route_table` module, the play fails with an error such as:

```
{"msg": "Unable to associate subnets for route table RouteTable:rtb-dddd3333, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>cannot disassociate the main route table association rtbassoc-XXXXXXXX</Message></Error></Errors><RequestID>abcde123-f00d-cafe-beef-fedcba987654</RequestID></Response>", "failed": true, "invocation": {"module_args": {"profile": null, "subnets": ["10.123.0.0/19", "10.123.32.0/19", "10.123.64.0/19", "10.123.96.0/19"], "aws_access_key": null, "security_token": null, "tags": {"Name": "BAD VPC - Smelly Public Route Table"}, "region": "us-east-1", "aws_secret_key": null, "routes": [{"gateway_id": "igw-ffffaaaa", "destination_cidr_block": "0.0.0.0/0"}, {"gateway_id": "vgw-00009999", "destination_cidr_block": "10.12.0.0/16"}, {"gateway_id": "vpce-abcdef00", "destination_cidr_block": "pl-12345678"}], "state": "present", "lookup": "tag", "ec2_url": null, "route_table_id": null, "vpc_id": "vpc-aaaaaaaa", "validate_certs": true, "propagating_vgw_ids": ["vgw-fedcba98"]}}}
```

This only happens with route tables with a `vgw` and/or `vpce` added.  The problem is due to [code in `ensure_subnet_associations()` & `ensure_subnet_association()` functions][ensure_subnet_association] expecting every RouteTableAssociation (`a`) in `route_table.associations` to have a `subnet`.  However, `boto3`, and `awscli` both return a `rtbassoc-XXXXXXXX` with a `null` or `None` value for `a.subnet_id`.

Thus, when `current_association_ids` (list with one `rtbassoc` having SubnetId `None` and Main `True`)  is compared with `new_association_ids` (list without the `rtbassoc` having SubnetId `None`) the result is that `to_delete` ends up containing the "Main" `rtbassoc-XXXXXXXX` which does not have a subnet associated with it.  The module tries to delete this presumably "bad" `rtbassoc`, and fails with the error above.

As far as why AWS behavior is this way only with route tables with a VPCE or VGW... beats me.

Here is a sample of `awscli` output when describing the strange route table:

```
aws ec2 describe-route-tables --route-table-ids rtb-dddd3333
-----------------------------------------------------------------------------------------------------------------
|                                              DescribeRouteTables                                              |
+---------------------------------------------------------------------------------------------------------------+
||                                                 RouteTables                                                 ||
|+-----------------------------------------------------+-------------------------------------------------------+|
||                    RouteTableId                     |                         VpcId                         ||
|+-----------------------------------------------------+-------------------------------------------------------+|
||  rtb-dddd3333                                       |  vpc-71eed817                                         ||
|+-----------------------------------------------------+-------------------------------------------------------+|
|||                                               Associations                                                |||
||+------------+----------------------------------------+------------------------+----------------------------+||
|||    Main    |        RouteTableAssociationId         |     RouteTableId       |         SubnetId           |||
||+------------+----------------------------------------+------------------------+----------------------------+||
|||  True      |  rtbassoc-XXXXXXXX                     |  rtb-dddd3333          |                            |||
|||  False     |  rtbassoc-f00dcafe                     |  rtb-dddd3333          |  subnet-12345678           |||
|||  False     |  rtbassoc-deadbeef                     |  rtb-dddd3333          |  subnet-98765432           |||
|||  False     |  rtbassoc-feedbeef                     |  rtb-dddd3333          |  subnet-abcdefff           |||
|||  False     |  rtbassoc-beefface                     |  rtb-dddd3333          |  subnet-ffacebad           |||
||+------------+----------------------------------------+------------------------+----------------------------+||
|||                                              PropagatingVgws                                              |||
||+-----------------------------------------------------------------------------------------------------------+||
|||                                                 GatewayId                                                 |||
||+-----------------------------------------------------------------------------------------------------------+||
|||  vgw-00009999                                                                                             |||
||+-----------------------------------------------------------------------------------------------------------+||
|||                                                  Routes                                                   |||
||+----------------------+---------------------------+----------------+-----------------------------+---------+||
||| DestinationCidrBlock |  DestinationPrefixListId  |   GatewayId    |           Origin            |  State  |||
||+----------------------+---------------------------+----------------+-----------------------------+---------+||
|||  10.123.0.1/16       |                           |  local         |  CreateRouteTable           |  active |||
|||  0.0.0.0/0           |                           |  igw-ffffaaaa  |  CreateRoute                |  active |||
|||                      |  pl-12345678              |  vpce-abcdef00 |  CreateRoute                |  active |||
|||  10.12.0.0/16        |                           |  vgw-00009999  |  EnableVgwRoutePropagation  |  active |||
||+----------------------+---------------------------+----------------+-----------------------------+---------+||
|||                                                   Tags                                                    |||
||+-----------------+-----------------------------------------------------------------------------------------+||
|||       Key       |                                          Value                                          |||
||+-----------------+-----------------------------------------------------------------------------------------+||
|||  Name           |  BAD VPC - Smelly Public Route Table                                                    |||
||+-----------------+-----------------------------------------------------------------------------------------+||
```

[ensure_subnet_association]: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py#L395-L437

##### STEPS TO REPRODUCE

`vars/bad-vpc-vars.yml`:
```yaml
# VPC information
vpc_cidr_block: &VPCCIDR 10.123.0.0/16
vpc_tags: &VPC_TAGS
  Name: BAD-VPC
  location: us-east-1

vpc_subnets:
## Public subnets
  -
    cidr: &PUBa 10.123.0.0/19
    az: us-east-1a
    resource_tags:
      Name: BAD VPC Public A
      private: false
  -
    cidr: &PUBb 10.123.32.0/19
    az: us-east-1b
    resource_tags:
      Name: BAD VPC Public B
      private: false
  -
    cidr: &PUBd 10.123.64.0/19
    az: us-east-1d
    resource_tags:
      Name: BAD VPC Public D
      private: false
  -
    cidr: &PUBe 10.123.96.0/19
    az: us-east-1e
    resource_tags:
      Name: BAD VPC Public E
      private: false
## Private subnets
  -
    cidr: &PRIVa 10.123.128.0/19
    az: us-east-1a
    resource_tags:
      Name: BAD VPC Private A
      private: true
  -
    cidr: &PRIVb 10.123.160.0/19
    az: us-east-1b
    resource_tags:
      Name: BAD VPC Private B
      private: true
  -
    cidr: &PRIVd 10.123.192.0/19
    az: us-east-1d
    resource_tags:
      Name: BAD VPC Private D
      private: true
  -
    cidr: &PRIVe 10.123.224.0/19
    az: us-east-1e
    resource_tags:
      Name: BAD VPC Private E
      private: true

# Due to limitation with AWS Peering & VPN Gateways:
# Initialize VPC with simple routes for the first creation
# Then afterwards, set up route tables with vpc_routes!
# vpc_routes_init:
#   - subnets:
#       - *PRIVa
#       - *PRIVb
#       - *PRIVd
#       - *PRIVe
#     routes:
#     - dest: 0.0.0.0/0
#       gw: igw

vpc_public_routes:
  - subnets:
    - *PUBa
    - *PUBb
    - *PUBd
    - *PUBe
    ## Tried this hack to avoid faulty Ansible module wanting to delete the "Main" route table association id
    ## This probably has something to do with adding the VPCE or VGW
    ## If you are confused, see:
    ##     aws ec2 describe-route-tables --route-table-ids <rtb-yourIDhere>
    ## Look for Main: True, RouteTableAssociationId & Notice "SubnetId" is blank...
    ## AWS & boto is returning a null / None SubnetId here, and Ansible gets confused wanting to delete it if it's not matched
    ## This hack workaround did not work because it did not pass the RegEx checks for subnet id against `SUBNET_RE`, and `CIDR_RE`
    ## - null
    routes:
      - dest: 0.0.0.0/0
        gateway_id: igw
      - dest: 10.12.0.0/16
        gateway_id: vgw-00009999
      ## Handle matching Buggy VPC Endpoint for S3 so Ansible module marks as not to be changed
      - dest: None
        # Really this is 'pl-12345678', a DestinationPrefixListId and NOT a DestinationCidrBlock
        # but Boto3 or AWS bug always returns us 'None' in list of routes from get_all_route_tables()
        # ec2_route_table module does not know how to handle a DestinationPrefixListId
        gateway_id: vpce-abcdef00
    propagating_vgw_ids:
      - vgw-00009999
```

`test-route-table.yml`:
```yaml
---
# This playbook should reproduce the route table association error
- name: Launch/verify a Test VPC + Route Table
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "vars/bad-vpc-vars.yml"
  tasks:
    - name: Prepare VPC
      local_action:
        module: ec2_vpc_net
        name: "{{ vpc_tags.Name }}"
        state: present
        cidr_block: "{{ vpc_cidr_block }}"
        resource_tags: "{{ vpc_tags }}"
        # subnets: "{{ vpc_subnets }}"
        # internet_gateway: True
        # route_tables: "{{ vpc_routes_init }}"
        region: "{{ default_aws_region }}"
      register: vpc
      tags:
        - vpc
    - name: Create VPC subnets
      local_action:
        module: ec2_vpc_subnet
        state: present
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ item.cidr }}"
        az: "{{ item.az }}"
        resource_tags: "{{ item.resource_tags }}"
      with_items: "{{ vpc_subnets }}"
      register: vpc_subnets_created

    # Ensure that the VPC has an Internet Gateway.
    # The Internet Gateway ID is can be accessed via {{igw.gateway_id}} for use in setting up NATs etc.
    - name: Set up VPC public Inet Gateway
      local_action:
        module: ec2_vpc_igw
        vpc_id: "{{ vpc.vpc.id }}"
        state: present
      register: igw
    - name: Gather Subnet Facts for Public
      local_action:
        module: ec2_vpc_subnet_facts
        region: "{{ default_aws_region }}"
        filters:
          "tag:private": False
          vpc-id: "{{ vpc.vpc.id }}"
      register: vpc_subnets_public
      tags:
        - vpc
        - subnets
        - private

    - name: Set vpc_subnets variable to Public Subnet result
      set_fact: vpc_subnets_public="{{ vpc_subnets_public.subnets | sort(attribute='availability_zone') }}"
      always_run: true
      failed_when: false
      ignore_errors: true
      when: vpc_subnets_public is defined and vpc_subnets_public.subnets is defined
      tags:
        - vpc
        - subnets
        - private
    - name: Set up Smelly Public Subnet Route Table Gateway & Routes
      local_action:
        module: ec2_vpc_route_table
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ default_aws_region }}"
        tags:
          Name: BAD VPC - Smelly Public Route Table
        subnets: "{{ vpc_public_routes[0]['subnets'] }}"
        routes: "{{ vpc_public_routes[0]['routes'] }}"
        propagating_vgw_ids: "{{ vpc_public_routes[0]['propagating_vgw_ids'] | default(None) }}"
      register: public_route_table
```

1. Create a VPC to test
2. Create a public route table
3. Add a VPCE for S3
4. Add a VGW connection
5. Fill in your resulting `vgw-XXXXXXXX` and `vpce-XXXXXXXX` in the playbook vars file above
6. Try running a playbook with task running `ec2_vpc_route_table`

##### EXPECTED RESULTS

Expected the playbook to validate routes were the same & not change anything.

##### ACTUAL RESULTS

Error:

```
ansible-playbook -i inventory/hosts test-route-table.yml -vv --diff
TASK [Set up Smelly Public Subnet Route Table Gateway & Routes] *************************************************************************************************************************
task path: /Users/me/src/path/to/playbooks/bad-vpc/test-route-table.yml:56
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to associate subnets for route table RouteTable:rtb-dddd3333, error: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>cannot disassociate the main route table association rtbassoc-XXXXXXXX</Message></Error></Errors><RequestID>abcde123-f00d-cafe-beef-fedcba987654</RequestID></Response>"}
```
