### ISSUE TITLE
request: pacemaker module could support maintenance mode

### ISSUE THREAD

**Issue by davebiffuk** [ansible/ansible#25528]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

pacemaker_cluster

##### ANSIBLE VERSION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY
It would be useful for the pacemaker module to support putting the cluster into and out of maintenance mode, to invoke `pcs property set maintenance-mode=true` and `pcs property set maintenance-mode=false`

Suggested syntax:
```yaml
  tasks:
    - name: enter maintenance mode
      pacemaker_cluster: maintenance=true
```
This would enable "unsafe" operations to be done without disrupting a running cluster, for example copying a resource agent script into place.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
