### ISSUE TITLE
New Module ETCD

### ISSUE THREAD

**Issue by jparrill** [ansible/ansible#25542]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- Feature: New Module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:36) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
OS: Linux

##### SUMMARY
New module to add/remove/overwrite key-values from ETCD

##### STEPS TO REPRODUCE

```yaml
---
- name: 'Testing ETCD Module'
  hosts: localhost
  become: false
  vars:
    - etcd_test_key: '/test_key'
    - etcd_test_value: 'test_value'
    - etcd_inner_test_key: '/test/test_inner_key'
    - etcd_inner_test_value: 'test_inner_value'
  tasks:
    - name: 'Set Value on etcd'
      etcd:
        state: present
        host: 127.0.0.1
        port: 2379
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      delegate_to: localhost
      connection: local
      with_items:
        - { key: "{{ etcd_test_key}}" , value: "{{ etcd_test_value }}" }
        - { key: "{{ etcd_inner_test_key }}" , value: "{{ etcd_inner_test_value }}" }
```

##### EXPECTED RESULTS
```
PLAY [Testing ETCD Module] *******************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Set Value on etcd] *************************************************************************************************************************************************************************************************
changed: [localhost -> localhost] => (item={u'value': u'test_value', u'key': u'/test_key'}) => {"changed": true, "item": {"key": "/test_key", "value": "test_value"}, "key": "/test_key", "value": "test_value"}
changed: [localhost -> localhost] => (item={u'value': u'test_inner_value', u'key': u'/test/test_inner_key'}) => {"changed": true, "item": {"key": "/test/test_inner_key", "value": "test_inner_value"}, "key": "/test/test_inner_key", "value": "test_inner_value"}
```
##### ACTUAL RESULTS
N/A
