### ISSUE TITLE
eos_facts fails with error `"AF_UNIX path too long"` when debug log is enabled

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#25544]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bin/ansible-connection

##### ANSIBLE VERSION

```
2.4
```

##### STEPS TO REPRODUCE

Enable debug logs and run below playbook

```yaml
---
- name: Config using the core module
  hosts: veos02
  connection: local
  tasks:
    - name: Config Using Core Module
      eos_facts:
        authorize: yes
        provider:
          host: xxxx
          username: xxxx
          password: xxxx
          timeout: 30
        gather_subset: all
      register: response
```

##### EXPECTED RESULTS

Should fetch facts from device

##### ACTUAL RESULTS

Error message:
```
fatal: [xxxx]: FAILED! => {
    "changed": false,
    "err": "AF_UNIX path too long",
    "failed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": true,
            "gather_subset": [
                "all"
            ],
            "host": "veos02",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": "xxxx",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": 30,
                "transport": null,
                "use_ssl": null,
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": null
            },
            "ssh_keyfile": null,
            "timeout": 30,
            "transport": "cli",
            "use_ssl": true,
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "validate_certs": true
        }
    },
    "msg": "unable to connect to socket"
}
```
Getting wrong socket-path from `ansible-connection`
```
<xxxx> socket_path:  47164 1497017236.67982: Loading Connection 'ssh' from /Users/xxxx/ansible/xxxx/platform_agnostic/ansible/lib/ansible/plugins/connection/ssh.py (found_in_cache=False, class_only=True)
/Users/xxxx/.ansible/pc/c215142d24
```

Expected path
```
<xxxx> socket_path: /Users/xxxx/.ansible/pc/c215142d24
```
