### ISSUE TITLE
[RFE] Support one to many A records in nsupdate module

### ISSUE THREAD

**Issue by dcritch** [ansible/ansible#25554]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
nsupdate

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/srv/hpe-ansible/library']
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The nsupdate module was brought in to v2.3 and its great!

I had a need to create a wildcard DNS entry (for OpenShift/kubernetes routers) so the same A record is  pointing to multiple IPs. Out of the box this module would update the one entry rather than make additional ones.

It'd be sweet if the module supported this use case. For now, I made some modifications to a fork to accept a `state: multiple` so a call to the module won't overwrite the existing entry.

I submitted a PR to the original repo, not realising its now managed in github under ansible proper. The PR is here: https://github.com/mskarbek/ansible-nsupdate/pull/11

It might not be the preferred implementation, but I'd be happy to submit it if it was deemed acceptable.

##### STEPS TO REPRODUCE

An example task would look like so:

```yaml
- name: update wildcard DNS entry
  nsupdate:
    state: multiple
    key_name: "rndc-key"
    key_secret: "r/KKKKKEEEEEYYYYY"
    server: "192.168.1.1"
    zone: "example.com"
    record: "*.paas.example.com"
    value: "{{ ansible_default_ipv4.address }}"
  delegate_to: localhost
```

##### ACTUAL RESULTS

```

```
