### ISSUE TITLE
RFE: redhat_subscription should provide a way to manage channels

### ISSUE THREAD

**Issue by xromec** [ansible/ansible#25581]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
redhat_subscription

##### ANSIBLE VERSION
```
config file = /etc/ansible/ansible.cfg
configured module search path = Default w/o overrides
python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
N/A
##### OS / ENVIRONMENT
N/A

##### SUMMARY
redhat_subscription currently does not allow enabling and disabling specific channels. That is needed when the pool where the OS is registered to contains many channels which are enabled by default and can cause package conflicts or simply take resources when updating the channel metadata.

##### STEPS TO REPRODUCE

```
  - name: Register                               
    redhat_subscription:                                                        
      consumer_name: "{{inventory_hostname}}.{{dns.domain}}"                    
      username: UserName
      password: password                                                       
      autosubscribe: true                            
```

##### EXPECTED RESULTS
An option for enabling/disabling channels is available. Like
enable_channels:
    - Channel01
    - Cahnnel02

disable_channels:
    - Channel01
    - Channel02

channels:
    - Channel01
    - Channel02

Where channels would say the exact list of channels which is suppose to be enabled. 

##### ACTUAL RESULTS
System is registered to all channels in the pool
