### ISSUE TITLE
Cannot set kernel_id using Linode module

### ISSUE THREAD

**Issue by ababra** [ansible/ansible#25583]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
linode

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /Users/user/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
macOS Sierra 10.12.5

##### SUMMARY
Linode module [documentation](http://docs.ansible.com/ansible/linode_module.html) states that you can pass "kernel_id" as a parameter. However this parameter does not seem to be working.

##### STEPS TO REPRODUCE

```yaml
---
# Provision a new Linode server
- hosts: all

  vars_files:
    - vars/vars.yaml
    - vars/vault.yaml

  tasks:
    - name: Create Linode
      local_action:
        module: linode
        api_key: "{{linode_token}}"
        name: mr-linode
        # Linode 1GB
        plan: 1
        # Newark, NJ
        datacenter: 6
        # Ubuntu 16.04 LTS
        distribution: 138
        # As per Linode avail.distributions endpoint, should equal: Latest 64 bit (4.9.15-x86_64-linode81)
        # Also tried 210, 248, 250, etc.
        kernel_id: 138
        password: "***PASSWORD***"
        private_ip: yes
        ssh_pub_key: "***KEY***"
        wait: yes
        state: present
```

Executing playbook using: `ansible-playbook provision-linode.yaml -i localhost, -c local`

##### EXPECTED RESULTS
Linode created successfully

##### ACTUAL RESULTS
```
TASK [Create Linode] ***************************************************************************************************
task path: /Users/user/ansible-playbooks/provision-linode/provision-linode.yaml:15
Using module file /Library/Python/2.7/site-packages/ansible/modules/cloud/linode/linode.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/user/.ansible/tmp/ansible-tmp-1497175086.49-74393203089156 `" && echo ansible-tmp-1497175086.49-74393203089156="` echo /Users/user/.ansible/tmp/ansible-tmp-1497175086.49-74393203089156 `" ) && sleep 0'
<localhost> PUT /var/folders/f6/ztj2sj9s63b1cd6f3lqj7cph0000gn/T/tmpP6MS2l TO /Users/user/.ansible/tmp/ansible-tmp-1497175086.49-74393203089156/linode.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/user/.ansible/tmp/ansible-tmp-1497175086.49-74393203089156/ /Users/user/.ansible/tmp/ansible-tmp-1497175086.49-74393203089156/linode.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /Users/user/.ansible/tmp/ansible-tmp-1497175086.49-74393203089156/linode.py; rm -rf "/Users/user/.ansible/tmp/ansible-tmp-1497175086.49-74393203089156/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "datacenter": 6, 
            "distribution": 138, 
            "kernel_id": 138, 
            "name": "mr-linode", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "plan": 1, 
            "private_ip": true, 
            "ssh_pub_key": "***KEY***", 
            "state": "present", 
            "wait": true
        }
    }, 
    "msg": "Unsupported parameters for (linode) module: kernel_id. Supported parameters include: additional_disks,alert_bwin_enabled,alert_bwin_threshold,alert_bwout_enabled,alert_bwout_threshold,alert_bwquota_enabled,alert_bwquota_threshold,alert_cpu_enabled,alert_cpu_threshold,alert_diskio_enabled,alert_diskio_threshold,api_key,backupweeklyday,backupwindow,datacenter,displaygroup,distribution,linode_id,name,password,payment_term,plan,private_ip,ssh_pub_key,state,swap,wait,wait_timeout,watchdog"
}

```
