### ISSUE TITLE
ERROR! 'files_matching' is not a valid attribute for a Task

### ISSUE THREAD

**Issue by foafk** [ansible/ansible#25599]
##### ISSUE TYPE
 Bug Report

##### COMPONENT NAME
 include_vars

##### ANSIBLE VERSION
 2.3.0.0

##### CONFIGURATION
 Redhat Linux machines both source and target

##### SUMMARY
I tried to load a variable file within a Task of a role 
....../ansible/tasks/main.yml
and I get this: 
ERROR! 'files_matching' is not a valid attribute for a Task

# include variable OUYT
```
- name: Include variables in ouyt.yml
  include_vars:
  dir: '/opt/ansible/glex/variables'
  files_matching: 'ouyt.yml'

`
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, your indentation is wrong, you want:
```
- name: Include variables in ouyt.yml
  include_vars:
      dir: '/opt/ansible/glex/variables'
      files_matching: 'ouyt.yml'
```
As `dir` and `files_matching` are options of `include_vars`, not task level keywords.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
