### ISSUE TITLE
Updating owner on existing directory using file module does not update parents

### ISSUE THREAD

**Issue by dandrestor** [ansible/ansible#25596]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
file module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If creating a directory with a certain owner, i.e. use file state=directory with a non-existing path, all the necessary parent directories will be created with the same owner. If the directory already exists with a different owner, it itself will be updated to the new owner, but not the parents.

##### STEPS TO REPRODUCE
Ensure `/some/test/path exists`, and that `/some` and `/some/test` are owned by `root`.

Run then the following task:

```yaml
- name: Test task
  file:
    path: "/some/test/path"
    state: directory
    owner: some_user
    group: some_group
    mode: 0750
  become: yes
```

##### EXPECTED RESULTS
Parent directories `/some` and `/some/test` updated to new owner `some_user`

##### ACTUAL RESULTS
Parent directories not updated
