### ISSUE TITLE
cs_host doesn't handle IP address based names properly

### ISSUE THREAD

**Issue by netservers** [ansible/ansible#25627]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cs_host
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /home/john/.ansible.cfg
  configured module search path = [u'/home/john/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Using the Cloudstack API it is valid to provide an IP address as the name of the host to add. The cs_host module accepts this, and the host is successfully added to CloudStack.

The problem is that Cloudstack replaces the IP address with the hostname that it learns from the host that was added. CloudStack does record the IP address, but writes it to the ipaddress field, not the name field.

On subsequent runs of the ansible playbook cs_host does not recognise the host as being the same at that added previously.

I have a patch that solves this problem. I'll open a pull request shortly with the fix.

##### STEPS TO REPRODUCE

Use the cs_host module passing an IP address instead of a hostname. On subsequent runs the added host will not be matched to the IP address.

```yaml
  - name: Add compute hosts
    local_action:
      module: cs_host
      name: 192.168.1.10
      api_timeout: 120
      username: root
      password: "{{ compute_root_password }}"
      cluster: Xeon
      pod: Telehouse
      zone: London
      hypervisor: KVM
      allocation_state: enabled
      state: present
```

##### EXPECTED RESULTS

Subsequent run of the playbook should recognise the host as already having been added.
##### ACTUAL RESULTS

The host added in the first pass is not matched, and the hosted is added repeatedly.

```
N/A
```
