### ISSUE TITLE
sensu_check uses outdated syntax

### ISSUE THREAD

**Issue by dajeffers** [ansible/ansible#25626]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

sensu_check
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

```
[defaults]
roles_path          = ./roles:./galaxy_roles
library             = library
ansible_managed     = Ansible managed: Do NOT edit this file manually!
retry_files_enabled = False
nocows              = 1
stdout_callback     = skippy
remote_tmp          = /tmp/.ansible-${USER}/tmp

[colors]
diff_add            = bright green
diff_remove         = bright magenta
diff_lines          = bright cyan
```

```
# export | grep ANSIBLE
ANSIBLE_VAULT_PASSWORD_FILE=[redacted]
```
##### OS / ENVIRONMENT

OS Running Ansible:
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
```
Host being managed, Docker:
```
# cat /etc/redhat-release 
CentOS release 6.9 (Final)
```
##### SUMMARY

sensu_check is creating an incorrect/outdated hash for Sensu. It should be creating a hash that looks like this:
https://sensuapp.org/docs/latest/reference/checks.html#subdue-attributes

This changed following Sensu going from 0.25 -> 0.26
https://sensuapp.org/docs/0.25/reference/checks.html#subdue-attributes
##### STEPS TO REPRODUCE

The task:

```yaml
  - name: Deploy Sensu-Client Checks
    sensu_check:
      aggregate: "{{ item.aggregate | default('false') }}"
      command: "{{ item.command }}"
      custom: "{{ item.custom | default(omit) }}"
      dependencies: "{{ item.dependencies | default(omit) }}"
      handle: "{{ item.handle | default('true') }}"
      handlers: "{{ item.handlers | default('default') }}"
      interval: "{{ item.interval | default(30) }}"
      metric: "{{ item.metric | default('false') }}"
      name: "{{ item.name }}"
      occurrences: "{{ item.occurrences | default(3) }}"
      path: "{{ item.path | default('/etc/sensu/conf.d/checks.json') }}"
      source: "{{ item.source | default(ansible_nodename) }}"
      standalone: "{{ item.standalone | default('true') }}"
      state: "{{ item.state | default('present') }}"
      subscribers: "{{ item.subscribers | default(['sensu']) }}"
      subdue_begin: "{{ item.subdue_begin | default(omit) }}"
      subdue_end: "{{ item.subdue_end | default(omit) }}"
      timeout: "{{ item.timeout | default(10) }}"
      ttl: "{{ item.ttl | default(360) }}"
    with_items:
      "{{ sensu_base_checks }}"
    notify: restart sensu-client service
    tags:
      - monitoring
```
The variable passed via group_vars:
```yaml
sensu_base_checks:
  - name: "CPU_Usage_on_{{ ansible_nodename }}"
    command: "{{ sensu_plugin_dir }}/check-cpu.rb"
    handlers:
      - 'logstash'
      - 'pagerduty'
    occurences: '6'
    subdue_begin: '7:00 AM'
    subdue_end: '7:20 AM'
```

##### EXPECTED RESULTS

```
# cat /etc/sensu/conf.d/checks.json
{
  "checks": {
    "CPU_Usage_on_centos6.ci.dev": {
      "handle": true, 
      "subscribers": [
        "sensu"
      ], 
      "subdue": {
        "days": {
          "all": [
            {
              "begin": "7:00 AM",
              "end": "7:20 AM"
            }
          ]
        }
      },
      "handlers": [
        "logstash", 
        "pagerduty"
      ], 
      "interval": 30, 
      "standalone": true, 
      "source": "centos6.ci.dev", 
      "command": "/opt/sensu/embedded/bin/check-cpu.rb", 
      "occurrences": 3, 
      "timeout": 10, 
      "ttl": 360, 
      "aggregate": false
    }
  }
}
```

##### ACTUAL RESULTS

```
TASK [cmacrae.sensu : Ensure Sensu client service is running] ******************
fatal: [centos6.example.dev]: FAILED! => {"changed": false, "failed": true, "msg": "Starting sensu-client[FAILED]\r[FAILED]\r\n"}

# cat /etc/sensu/conf.d/checks.json
[root@centos6 /]# cat /etc/sensu/conf.d/checks.json 
{
  "checks": {
    "CPU_Usage_on_centos6.ci.dev": {
      "handle": true, 
      "subscribers": [
        "sensu"
      ], 
      "subdue": {
        "begin": "7:00 AM", 
        "end": "7:20 AM"
      }, 
      "handlers": [
        "logstash", 
        "pagerduty"
      ], 
      "interval": 30, 
      "standalone": true, 
      "source": "centos6.ci.dev", 
      "command": "/opt/sensu/embedded/bin/check-cpu.rb", 
      "occurrences": 3, 
      "timeout": 10, 
      "ttl": 360, 
      "aggregate": false
    }
  }
}
```
