### ISSUE TITLE
async_status does not notice if task timed out

### ISSUE THREAD

**Issue by Antaxify** [ansible/ansible#25637]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
async
##### ANSIBLE VERSION
ansible 2.3.0.0

##### CONFIGURATION
default ansible.cfg file

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When a task is executed with 'poll: 0' (fire and forget) and the time specified in 'async' expires, the async cache remains and a following 'async_status' task reports that the task is still running, although the process was killed. 

##### STEPS TO REPRODUCE
```yaml
---

- hosts: localhost
  tasks:
    - command: sleep 100
      async: 10
      poll: 0
      register: myJob

    - command: sleep 20

    - name: wait until playbooks are finished
      async_status:
        jid: "{{ myJob.ansible_job_id }}"
      register: myJob_result

    - debug: var=myJob_result
```

##### EXPECTED RESULTS
The async_status task should report that the job is not running (like it would be if the job was cleaned up by 'async_status' with 'mode: cleanup'). 'Failed' should not be 0.

##### ACTUAL RESULTS
```
PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [command] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost] => {"ansible_job_id": "964367425822.17508", "changed": true, "finished": 0, "results_file": "/home/stephan/.ansible_async/964367425822.17508", "started": 1}

TASK [command] *************************************************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": ["sleep", "20"], "delta": "0:00:20.005145", "end": "2017-06-13 08:26:51.140481", "rc": 0, "start": "2017-06-13 08:26:31.135336", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [wait until playbooks are finished] ***********************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {"ansible_job_id": "964367425822.17508", "changed": false, "finished": 0, "started": 1}

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "myJob_result": {
        "ansible_job_id": "964367425822.17508", 
        "changed": false, 
        "finished": 0, 
        "started": 1
    }
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0  
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/async_wrapper.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/async_wrapper.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by AlekSi** [comment]
I can confirm it is still an issue with Ansible 2.8.2.

**Comment by jhg03a** [comment]
I also can still confirm it's an issue with 2.9.1 as well:
Sample Playbook:
```
---
- hosts: localhost
  gather_facts: no
  connection: local

  tasks:
    - name: background task
      shell:
        cmd: "sleep 30"
        executable: "{{ lookup('pipe','which bash') }}"
      register: async_res
      async:  20
      poll: 0

    - name: Wait for the background task to finish
      async_status:
        jid: "{{ async_res.ansible_job_id }}"
      register: async_test_job
      until: async_test_job.finished
      retries: 5
      delay: 5
```
What I'd love to see is the ability to see either the async job finished attribute also include timeout, or a separate attribute so we can do `until: async_test_job.finished or async_test_job.timed_out`
