### ISSUE TITLE
cloud/vmware/vmware_vswitch.py nic_name should be optional

### ISSUE THREAD

**Issue by jpsenior** [ansible/ansible#25632]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloud/vmware/vmware_vswitch.py

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
n/a
##### OS / ENVIRONMENT
n/a
##### SUMMARY
The vmware_vswitch module erroneously assumes that 'nic_name' is required.  It is valid (and sometimes desired) to make a vmware virtual switch that does not have any uplink nics at all - the use case is multiple isolated port-groups for isolated networking. 

After the vswitch is created, we create a port-group with VLAN 4095 (all vlans), with network policy permitting mac changes, forged transmit, and promiscuous all enabled.

In /ansible/modules/cloud/vmware/vmware_vswitch.py , we can omit this line if nic_name is not specified and the port-group is created as desired.

```python
if self.nic_name:
    vss_spec.bridge = vim.host.VirtualSwitch.BondBridge(nicDevice=[self.nic_name])
```

##### STEPS TO REPRODUCE

Run ansible-playbook against a task using the vmware_vswitch module, omitting nic_name.
```
    - name: add test_switch
      local_action:
        module: vmware_vswitch
        hostname: esxi_host
        username: esxi_username
        password: esxi_password
        switch_name: item
        mtu: 9000
        validate_certs: no
        number_of_ports: 8
        #nic_name: 'null'

```

##### EXPECTED RESULTS
I expect the vmware vswitch to be created, but without any uplink nics.

##### ACTUAL RESULTS
```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: nic_name"}
```
