### ISSUE TITLE
find module not returning pw_name and gr_name

### ISSUE THREAD

**Issue by 0mmariano** [ansible/ansible#25643]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
find module, stat module

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/local/ansible/modules/community']
```

##### CONFIGURATION
```
ansible.cfg
[defaults]
inventory = /etc/ansible/hosts
library = /usr/local/ansible/modules/community
stdout_callback = skippy
callback_whitelist = skippy
command_warnings = True
retry_files_enabled = false
[galaxy]
ignore_certs = yes
[privilege_escalation]
become_ask_pass=True
[paramiko_connection]
[ssh_connection]
pipelining = True
[accelerate]
[selinux]
[colors]
```
In an ansible-playbook wrapper script --
export ANSIBLE_LOG_PATH=/var/log/ansible/playbook_$(echo $1 | cut -d . -f 1).log

##### OS / ENVIRONMENT
Debian Jessie

##### SUMMARY
This is either a bug or a documentation error, depending on the intended output of "find"

I have a playbook that does the following --
```
    - name: find all j2 templates in {{ search_path }} for processing
      find:
        paths: "{{ search_path }}"
        patterns: "*.j2"
        recurse: yes
      register: files_found
    - name: Process each j2 template found
      template:
        src: "{{ item.path }}"
        dest: "{{ item.path|regex_replace('^(.*)(.j2)$', '\\1') }}"
      with_items: "{{ files_found|json_query('files') }}"
      when: item.path | search(".j2$")
```
The above works but I am unable to specify the user and group owner of the product of the template module because the result of find is the uid and the gid. Unfortunately, the uids and gids across my servers do not match (ansible_user may have different uids) so I can't use the output of find. However, in the documentation for "find," the return value "file" is described as "all matches found with the specified criteria (see stat module for full output of each dictionary)." Looking at the stat module documentation, it says it has gr_name (group name of owner) and pw_name (user name of owner) as return values which are exactly what I need. Based on this, "find" should also be returning pw_name and gr_name in addition to gid and uid.
http://docs.ansible.com/ansible/find_module.html#return-values
http://docs.ansible.com/ansible/stat_module.html#return-values

##### STEPS TO REPRODUCE
See sample playbook lines below which errors out because gr_name and pw_name (outputs of stat) are not outputs of find

```
    - name: find all j2 templates in {{ search_path }} for processing
      find:
        paths: "{{ search_path }}"
        patterns: "*.j2"
        recurse: yes
      register: files_found
    - name: Process each j2 template found
      template:
        src: "{{ item.path }}"
        dest: "{{ item.path|regex_replace('^(.*)(.j2)$', '\\1') }}"
        group: "{{ item.gr_name }}"
        owner: "{{ item.pw_name }}"
        mode: "{{ item.mode }}"
      with_items: "{{ files_found|json_query('files') }}"
      when: item.path | search(".j2$")
```

##### EXPECTED RESULTS
Based on documentation, pw_name and gr_name should be included in the returned values of "find" because they are returned by "stat"

##### ACTUAL RESULTS
```
"the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'gr_name'" 
```
