### ISSUE TITLE
CloudStack wants http:// prefix when adding host with cs_host module

### ISSUE THREAD

**Issue by netservers** [ansible/ansible#25641]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lib/ansible/modules/cloud/cloudstack/cs_host.py
##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /home/john/.ansible.cfg
  configured module search path = [u'/home/john/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### OS / ENVIRONMENT

This bug has been confirmed when testing against both CloudStack 4.9.2.0 and 4.10 (snapshot).
##### SUMMARY

When adding a host to Cloudstack the API insists that the hostname or IP address is prefixed with a URI scheme. Specifically it wants a prefix of "http://". This is only the case when adding the host, and this prefix is apparently never used again, and does not for part of this host name in the database/API.

Adding the http:// prefix to the hostname is a workaround that will allow you to successfully add a host, but you must subsequently remove it from your playbook to manage the host afterward.

I have a fix for this and will open a pull request shortly.
##### STEPS TO REPRODUCE

```yaml
---
- name: Setup Cloudstack
  hosts: ceph-the1
  tasks:
  # Ensure a host is present but disabled
  - local_action:
      module: cs_host
      name: server12.example.com
      cluster: Xeon
      pod: Telehouse
      zone: London
      hypervisor: KVM
      allocation_state: disabled
      password: SUPERsecret
      username: root
```

##### EXPECTED RESULTS

The request would pass API validation and be accepted.
##### ACTUAL RESULTS

The API rejects the request due to a lack of a uri scheme prefix.

```
$ ansible-playbook test_cs_host.yml

PLAY [Setup Cloudstack] ***********************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************
ok: [ceph-the1]

TASK [cs_host] ********************************************************************************************************************************
fatal: [ceph-the1 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "CloudStackException: ('HTTP 431 response from CloudStack', <Response [431]>, {u'errorcode': 431, u'uuidList': [], u'cserrorcode': 4350, u'errortext': u'uri.scheme is null server12.example.com, add nfs:// (or cifs://) as a prefix'})"}
        to retry, use: --limit @/home/john/ansible/theceph/test_cs_host.retry

PLAY RECAP ************************************************************************************************************************************
ceph-the1                  : ok=1    changed=0    unreachable=0    failed=1   

```
