### ISSUE TITLE
Kubernetes: no support for HPA (horizontal pod autoscaling)

### ISSUE THREAD

**Issue by luispabon** [ansible/ansible#25656]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
kubernetes

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
CentOS Linux release 7.2.1511 (Core) 
Ubuntu 17.04

##### SUMMARY
Deployments are not supported by the kubernetes plugin. This is the recommended way of deploying apps on Kubernetes 1.4+.

##### STEPS TO REPRODUCE

```yaml

- name: HPA policy for something
  kubernetes:
    api_endpoint: somewhere.api
    insecure: true
    state: present
    validate_certs: off
    inline_data:
      apiVersion: autoscaling/v1
      kind: HorizontalPodAutoscaler
      metadata:
        name: stuff-hpa
      spec:
        scaleTargetRef:
          kind: Deployment
          name: stuff-deployment
        minReplicas: 1
        maxReplicas: 3
        targetCPUUtilizationPercentage: 30

```

Which when run results on

```
TASK [some/service : HPA policy for something] ******
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "invalid resource kind specified in the data: 'horizontalpodautoscaler'"}
```

##### EXPECTED RESULTS
```
TASK [some/service : HPA policy for something] ******
ok: [localhost]

```
