### ISSUE TITLE
Kubernetes - no support for deployments

### ISSUE THREAD

**Issue by luispabon** [ansible/ansible#25653]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
kubernetes

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
CentOS Linux release 7.2.1511 (Core)
Ubuntu 17.04

##### SUMMARY
Deployments are not supported by the kubernetes plugin. This is the recommended way of deploying apps on Kubernetes 1.4+.

##### STEPS TO REPRODUCE

```yaml

- name: add some stuff somewhere by someone
  kubernetes:
    api_endpoint: awesome.endpoint
    insecure: true
    state: present
    inline_data:
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: some-deployment
        namespace: gr8
      spec:
        replicas: 1
        revisionHistoryLimit: 3
        strategy:
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: some-pod
          spec:
            containers:
            - name: webserver
              imagePullPolicy: Always
              image: nginx
              ports:
                - containerPort: 80
              resources:
                requests:
                  cpu:    "50m"
                  memory: "64Mi"
```

Which when run results on

```
TASK [kubernetes/thing :add some stuff somewhere by someone] ***
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "invalid resource kind specified in the data: 'deployment'"}
```

##### EXPECTED RESULTS
```
TASK [kubernetes/thing :add some stuff somewhere by someone] ***
ok: [localhost]

```
