### ISSUE TITLE
Deprecated message when using provider arguments

### ISSUE THREAD

**Issue by perimore** [ansible/ansible#25663]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

networking
eos-config

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/sean/src/ansibledemos/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### STEPS TO REPRODUCE

Ran a playbook and wasn't expecting to receive the deprecated messages as per the post below from Peter that states the provider argument is not deprecated:

https://www.ansible.com/blog/network-device-authentication-with-ansible-2-3

```yaml
---
- hosts: switches
  gather_facts: 'no'
  # Run Anisble on the local server using CLI or eAPI to the node
  connection: local
  vars:
    model_name: '{{ version_data.stdout[0].modelName }}'
    eos_version: '{{ version_data.stdout[0].internalVersion }}'

  tasks:
    - name: Get Version
      eos_command:
        commands: 'show version'
        provider: '{{ eos_connection }}'
      register: version_data

  #    - debug: msg="{{version_data}}"

    - name: Print report
      template:
        src: version_report.j2
        dest: ./version_report-{{ inventory_hostname }}.txt

    - name: Configure vlans
      eos_config:
        backup: yes
        src: vlans.j2
        provider: '{{ eos_connection }}'

    - name: Configure interfaces
      eos_config:
        src: intf.j2
        provider: '{{ eos_connection }}'

---
# make ansible play nice in a virtualenv
ansible_python_interpreter: python

eos_connection:
  host: "{{ inventory_hostname }}"
  transport: eapi
  use_ssl: yes
  validate_certs: no
```

##### EXPECTED RESULTS

No deprecated messages as using the provider argument

##### ACTUAL RESULTS

```
PLAY [switches] ******************************************************************************************************************************************************************************************************************************

TASK [Get Version] ***************************************************************************************************************************************************************************************************************************
 [WARNING]: argument username has been deprecated and will be removed in a future version

 [WARNING]: argument password has been deprecated and will be removed in a future version

 [WARNING]: argument transport has been deprecated and will be removed in a future version

ok: [spine1]

TASK [Print report] **************************************************************************************************************************************************************************************************************************
ok: [spine1]

TASK [Configure vlans] ***********************************************************************************************************************************************************************************************************************
ok: [spine1]

TASK [Configure interfaces] ******************************************************************************************************************************************************************************************************************
ok: [spine1]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
spine1                     : ok=4    changed=0    unreachable=0    failed=0
```
