### ISSUE TITLE
The ldap_attr module fails to initially add/modify olcTLS* attributes

### ISSUE THREAD

**Issue by ionosphere80** [ansible/ansible#25665]
- Bug Report

##### COMPONENT NAME
modules/network/ldap_attr

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
OpenLDAP recommends using OLC (cn=config) for configuration rather than the conventional slapd.conf file [1]. Each change via OLC triggers a reload of the OpenLDAP service (slapd) rather than requiring a restart.

Configuring OpenLDAP for TLS/SSL requires at least three attributes in cn=config:

- olcTLSCACertificateFile
- olcTLSCertificateFile
- olcTLSCertificateKeyFile

Initially adding the olcTLSCertificateFile and olcTLSCertificateKeyFile attributes must occur in the same add/modify operation because TLS/SSL requires a server certificate and key. Triggering a reload with only one of these attributes would prevent operation of TLS/SSL, so the OpenLDAP service returns an error (80) if the add/modify operation only contains one of them. The ldap_attr module appears to treat each attribute/value pair as a separate add/modify operation. Thus, attempting to initially add these attributes using the module returns an error and prevents configuration of TLS/SSL. Although the OpenLDAP service returns an error, it still adds one of the two attributes. Running the task a second time usually succeeds because it adds the other attribute which meets the OLC requirement of both attributes present for TLS/SSL. The ldap_attr module should consider these attributes (and possibly other similar situations) as a special case or provide an option to add/modify all attributes in a task using the same add/modify operation.

##### STEPS TO REPRODUCE

- Install OpenLDAP server (with default OLC tree)
- Create a task using ldap_attr to add/modify the olcTLSCertificateFile and olcTLSCertificateKeyFile attributes
- Run task

```yaml
- name: configure openldap server tls/ssl
  ldap_attr:
    dn: "cn=config"
    name: "{{ item.0 }}"
    values: "{{ item.1 }}"
    state: exact
  with_together:
    - [ 'olcTLSCertificateFile', 'olcTLSCertificateKeyFile' ]
    - [ '/etc/ssl/certs/server.pem', '/etc/ssl/private/server.key' ]
```

(Note: The actual task attempts to add/modify all necessary attributes in cn=config using attribute/value pairs from a key/value store.)

##### EXPECTED RESULTS
The ldap_attr module should successfully add/modify the olcTLSCertificateFile and olcTLSCertificateKeyFile attributes.

##### ACTUAL RESULTS
The task fails because the ldap_attr module attempts to add/modify each attribute in a separate add/modify operation.

```
TASK [openldap-server : configure openldap server tls/ssl] ****************************************************************************************************
<1.2.3.4> (0, '\r\n{"msg": "Attribute action failed.", "failed": true, "details": "{\'desc\': \'Other (e.g., implementation specific) error\'}", "invocation": {"module_args": {"dn": "cn=config", "name": "olcTLSCertificateFile", "server_uri": "ldapi:///", "start_tls": false, "bind_dn": null, "state": "exact", "params": null, "bind_pw": "", "values": "/etc/ssl/certs/server.pem"}}}\r\n', 'OpenSSH_7.4p1, LibreSSL 2.5.0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 18481\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 1.2.3.4 closed.\r\n')
failed: [1.2.3.4] (item=[u'olcTLSCertificateFile', u'/etc/ssl/certs/server.pem']) => {
    "details": "{'desc': 'Other (e.g., implementation specific) error'}",
    "failed": true,
    "invocation": {
        "module_args": {
            "bind_dn": null,
            "bind_pw": "",
            "dn": "cn=config",
            "name": "olcTLSCertificateFile",
            "params": null,
            "server_uri": "ldapi:///",
            "start_tls": false,
            "state": "exact",
            "values": "/etc/ssl/certs/server.pem"
        }
    },
    "item": [
        "olcTLSCertificateFile",
        "/etc/ssl/certs/server.pem"
    ],
    "msg": "Attribute action failed."
}
```

[1] https://www.openldap.org/doc/admin24/slapdconf2.html

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rbott** [comment]
Just to add some information:

We observed that running the tasks like this actually works (but we have not yet figured out why):
```
- name: Configure LDAP Core TLS Settings
  ignore_errors: True
  ldap_attr:
    dn: "cn=config"
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: exact
  with_dict:
    olcTLSCertificateFile: "/etc/ssl/certs/{{ ansible_fqdn }}-cert.pem"
    olcTLSCertificateKeyFile: "/etc/ssl/private/{{ ansible_fqdn }}-key.pem"

- name: Configure LDAP Core TLS Settings
  ldap_attr:
    dn: "cn=config"
    name: "{{ item.key }}"
    values: "{{ item.value }}"
    state: exact
  with_dict:
    olcTLSCertificateFile: "/etc/ssl/certs/{{ ansible_fqdn }}-cert.pem"
    olcTLSCertificateKeyFile: "/etc/ssl/private/{{ ansible_fqdn }}-key.pem"
```

On the very first run, the first task will partially fail (only one item of the dict will work) - hence the ignore_errors. The second task will complete just fine. During the following runs, both tasks will just finish with 'OK'.

**Comment by ionosphere80** [comment]
The OpenLDAP server attempts to reload the configuration after every add/modify operation to OLC (cn=config). The server returns an error (80) if it receives an add/modify operation containing only olcTLSCertificateFile or olcTLSCertificateKeyFile (rather than both attributes) because it cannot successfully reload the configuration. Although the first task fails, the server still adds/modifies the attribute. The second task succeeds because it adds/modifies the other olcTLS attribute which satisfies the requirement for the server to reload the configuration and enable TLS/SSL.

**Comment by p12i** [comment]
My workaround:
```
- name: Configure TLS CA                                                                                                                                                                         
  ldap_attr:                                                                                                                                                                                     
      dn: cn=config                                                                                                                                                                              
      name: "{{ item.key }}"                                                                                                                                                                     
      values: "{{ item.value }}"                                                                                                                                                                 
      server_uri: ldapi:///                                                                                                                                                                      
      state: exact                                                                                                                                                                               
  with_dict:                                                                                                                                                                                     
      olcLogLevel:              "-1"                                                                                                                                                             
      olcTLSCACertificateFile:  "{{p12i_ldap_cacert}}"                                                                                                                                           
  notify: Restart slapd                                                                                                                                                                                                                                                                                                                                                                           
- name: Configure TLS                                                                                                                                                                            
  shell:                                                                                                                                                                                         
      cmd: |                                                                                                                                                                                     
          cat <<EOF | /usr/bin/ldapmodify -Q -H ldapi:/// -Y EXTERNAL -D "cn=admin,{{p12i_ldap_base}}" -w "{{ldap_admin_password}}"                                                              
          dn: cn=config                                                                                                                                                                          
          changetype: modify                                                                                                                                                                     
          replace: olcTLSCertificateFile                                                                                                                                                         
          olcTLSCertificateFile: "{{p12i_ldap_cert}}"                                                                                                                                            
          -                                                                                                                                                                                      
          replace: olcTLSCertificateKeyFile                                                                                                                                                      
          olcTLSCertificateKeyFile: "{{p12i_ldap_key}}"                                                                                                                                          
          EOF                                                                                                                                                                                    
  no_log: True                                                                                                                                                                                   
  when: p12i_ldap_change_admin_password
```

**Comment by ipeacocks** [comment]
From my side it looks like openLDAP bug, ansible isn't guilty. openLDAP just can't replace olcTLSCertificateKeyFile and olcTLSCertificateFile  values after enabling.

**Comment by azaghal** [comment]
It would be interesting to perhaps add ability to pass in a bunch of parameters into the `ldap_attr` module instead of just a single attribute. Then again, that could complicate the module more than it's worth - perhaps an additional module that operates on multiple attributes would be helpful?

Depending on how you look at it, one could say that OpenLDAP should either not error-out on this, or actually it should error-out and refuse to change the value altogether. From one side, it's not a bad check they are doing on their side - they merely want to ensure the certificate matches with private key provided.

**Comment by azaghal** [comment]
Since somebody just might find this useful, I've figured out a bit more specifics around @rbotts 's solution. Now, I would not be surprised this behaviour changes depending on distro and TLS library OpenLDAP has been built against. This particular solution works against (soon to be expired) Debian 8.

Essentially, what you can attempt to do is:

1. Attempt to set the `olcTLSCertificateKeyFile` first, and ignore the errors. This will not change the attribute in LDAP directory, but it seems that the OpenLDAP server will store the key or its path in-memory for "use" with subsequent operations.

2. Now you set the `olcTLSCertificateFile` attribute. This _will_ change the `olcTLSCertificateFile` attribute without errors. But - the `olcTLSCertificateKeyFile` attribute will remain the same.

3. Finally, set the `olcTLSCertificateKeyFile` attribute again. This time around it will succeed, and now both attributes will have intended values.

So, something like this would work as expected (on a plus note, you can still rely on changed/failed states of the 2nd and 3rd task):

```
- name: Configure TLS private key (ignore errors)
  ldap_attr:
    dn: cn=config
    name: olcTLSCertificateKeyFile
    values: "/etc/ssl/private/ldap.key.pem"
    state: exact
  failed_when: False

- name: Configure TLS certificate
  ldap_attr:
    dn: cn=config
    name: olcTLSCertificateFile
    values: "/etc/ssl/certs/ldap.cert.pem"
    state: exact

- name: Configure TLS private key
  ldap_attr:
    dn: cn=config
    name: olcTLSCertificateKeyFile
    values: "/etc/ssl/private/ldap.key.pem"
    state: exact
```
