### ISSUE TITLE
omit does not work in task environment

### ISSUE THREAD

**Issue by pjnagel** [ansible/ansible#25678]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
task `environment` argument (all modules, not specific to a any module)

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/pieter.nagel/setup/lautus_ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Nothing relevant

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Using the 'some_var | default(omit)' construct in the context of environment values does not work as expected.

If this is not expected to work, the docs should be clearer on this topic, and this bug report should be considered a wishlist item that this construct should be made to work.

##### STEPS TO REPRODUCE

```yaml
- shell: 'printenv | grep XYZZY'
  environment:
    XYZZY: '{{ undefined_variable | default(omit) }}'
  register: result

- debug: msg='{{ result.stdout }}'
```

##### EXPECTED RESULTS
I expected result.stdout to be entirely empty.

##### ACTUAL RESULTS
The environment variable was set:

```
TASK [tau_devel : debug] **********************************************************************************************************************************************************************************************************************************************************
ok: [dev3.lautus.net] => {
    "msg": "XYZZY=__omit_place_holder__3a9b44ab3747672df782fe3743c15e71a5db5202\nSUDO_COMMAND=/bin/sh -c echo BECOME-SUCCESS-rqhncxoovhhmrvncugmtexxjsqombzdm; XYZZY=__omit_place_holder__3a9b44ab3747672df782fe3743c15e71a5db5202 /usr/bin/python3.5"
}

```

**Comment by nitzmahone** [comment]
Yeah, `omit` is currently only implemented for module args ATM, but I could definitely see uses for it in other contexts as well...

**Comment by ansibot** [comment]
cc @dharmabumstead
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bkimble
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pilou-** [comment]
Current documentation states: `it is possible to use the default filter to omit module parameters using the special omit variable` is that not clear enough ? if so, `docs` can be removed.

**Comment by s-hertel** [comment]
You can use something like 
```yaml
environment: '{{ env|default(omit, true) }}'
vars:
  maybe_env:
    FOO: "foo"
    BAR: '{{ some_variable | default(omit) }}'
  env: '{{ dict(maybe_env|dictsort|rejectattr("1", "eq", omit)) }}'
```
Or compressed:
```yaml
environment: '{{ dict(env|dictsort|rejectattr("1", "eq", omit))|default(omit, true) }}'
vars:
  env:
    FOO: "foo"
    BAR: '{{ some_variable | default(omit) }}'
```
as a workaround
