### ISSUE TITLE
iptables: "!" argument ignored in the source specification

### ISSUE THREAD

**Issue by matthyx** [ansible/ansible#25684]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
iptables

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
Nothing particular

##### OS / ENVIRONMENT
CentOS Linux release 7.3.1611 (Core)

##### SUMMARY
iptables module doesn't properly handle "!" in the source specification, contradicting the documentation.

##### STEPS TO REPRODUCE
Run the following playbook to create a rule equivalent to:
`iptables -t nat -A PREROUTING ! -s 10.2.64.3 -p tcp --dport 80 -j DNAT --to 10.2.64.3:3128`

```yaml
  iptables:
    table: nat
    chain: PREROUTING
    source: ! 10.2.64.3
    protocol: tcp
    destination_port: 80
    jump: DNAT
    to_destination: 10.2.64.3:3128
```

##### EXPECTED RESULTS
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DNAT       tcp  -- !10-2-64-3_hostname  anywhere             tcp dpt:http to:10.2.64.3:3128
```

##### ACTUAL RESULTS
```
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DNAT       tcp  --  10-2-64-3_hostname  anywhere             tcp dpt:http to:10.2.64.3:3128
```

As you can see, the "!" is missing.
