### ISSUE TITLE
alternatives module: also run when link doesn't exist

### ISSUE THREAD

**Issue by twouters** [ansible/ansible#25693]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

alternatives

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

##### SUMMARY

If the filename defined by `link` doesn't exist, update-alternatives should be run.

##### STEPS TO REPRODUCE

```yaml
- name: remove existing regular file
  shell: [ ! -L /etc/mysql/my.cnf ] && rm /etc/mysql/my.cnf
- name: alternatives link created
  alternatives:
    name: my.cnf
    link: /etc/mysql/my.cnf
    path: /etc/mysql/percona-server.cnf
```

##### EXPECTED RESULTS

update-alternatives should be run and `/etc/mysql/my.cnf` should be a symlink to `/etc/alternatives/my.cnf`.

##### ACTUAL RESULTS

file `/etc/mysql/my.cnf` does not exist.

```
ls /etc/mysql/my.cnf
ls: cannot access /etc/mysql/my.cnf: No such file or directory
```
