### ISSUE TITLE
alternatives module: add a force option

### ISSUE THREAD

**Issue by twouters** [ansible/ansible#25694]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

alternatives

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

##### SUMMARY

If the filename defined by `link` is a regular file, update-alternatives refuses to replace it with a link, unless --force is provided.

##### STEPS TO REPRODUCE

```yaml
- name: alternatives link created
  alternatives:
    name: my.cnf
    link: /etc/mysql/my.cnf
    path: /etc/mysql/percona-server.cnf
    force: yes
```

##### EXPECTED RESULTS

update-alternatives should be run and `/etc/mysql/my.cnf` should become a symlink to `/etc/alternatives/my.cnf`.

##### ACTUAL RESULTS

file `/etc/mysql/my.cnf` remains a regular file as it is not possible to run update-alternatives with --force enabled.

```
file /etc/mysql/my.cnf
/etc/mysql/my.cnf: ASCII text
```
