### ISSUE TITLE
vmware_guest: non-helpful error when omitting required parameter..

### ISSUE THREAD

**Issue by mikeeaton83** [ansible/ansible#25696]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION
Default config, nothing changed

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY
I got the following error when trying to use vmware_guest:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'encode'... <truncated>
```

##### STEPS TO REPRODUCE
Use vmware_guest module and omit the hostname parameter for vcenter

```yaml
- name: Clone template and customise
    vmware_guest:
      username: Administrator@vsphere.local
      password: "{{ vcenter_password }}"
      validate_certs: no
      datacenter: "{{ dc_name }}"
      esxi_hostname: "{{ esxi_hostname }}"
      name: "{{ vm_name|upper }}"
      state: "{{ vm_state }}"
      template: "{{ vm_template }}"
      networks:
      - name: "{{ vlan_id }}"
        ip: "{{ vm_ipaddress }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gateway }}"
        domain: "{{ vm_domain }}"
      customization:
        autologon: true
        password: "{{ vm_password }}"
        joindomain: true
        domainadmin: "{{ domain_admin }}"
        domainadminpassword: "{{ domain_password }}"
```

##### EXPECTED RESULTS
I expected an error message telling me that a mandatory parameter was missing..

##### ACTUAL RESULTS
Ambiguous error message 

```
{
    "_ansible_parsed": false,
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_t0MsFQ/ansible_module_vmware_guest.py\", line 1332, in <module>\n    main()\n  File \"/tmp/ansible_t0MsFQ/ansible_module_vmware_guest.py\", line 1291, in main\n    pyv = PyVmomiHelper(module)\n  File \"/tmp/ansible_t0MsFQ/ansible_module_vmware_guest.py\", line 436, in __init__\n    self.content = connect_to_api(self.module)\n  File \"/tmp/ansible_t0MsFQ/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 333, in connect_to_api\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py\", line 817, in SmartConnect\n    sslContext)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py\", line 702, in __FindSupportedVersion\n    sslContext)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py\", line 622, in __GetServiceVersionDescription\n    path + \"/vimServiceVersions.xml\", sslContext)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py\", line 588, in __GetElementTree\n    conn.request(\"GET\", path)\n  File \"/usr/lib64/python2.7/httplib.py\", line 1017, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib64/python2.7/httplib.py\", line 1045, in _send_request\n    self.putrequest(method, url, **skips)\n  File \"/usr/lib64/python2.7/httplib.py\", line 946, in putrequest\n    host_enc = self.host.encode(\"ascii\")\nAttributeError: 'NoneType' object has no attribute 'encode'\n",
    "_ansible_no_log": false,
    "_ansible_delegated_vars": {
        "ansible_host": "localhost"
    },
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_t0MsFQ/ansible_module_vmware_guest.py\", line 1332, in <module>\n    main()\n  File \"/tmp/ansible_t0MsFQ/ansible_module_vmware_guest.py\", line 1291, in main\n    pyv = PyVmomiHelper(module)\n  File \"/tmp/ansible_t0MsFQ/ansible_module_vmware_guest.py\", line 436, in __init__\n    self.content = connect_to_api(self.module)\n  File \"/tmp/ansible_t0MsFQ/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 333, in connect_to_api\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py\", line 817, in SmartConnect\n    sslContext)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py\", line 702, in __FindSupportedVersion\n    sslContext)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py\", line 622, in __GetServiceVersionDescription\n    path + \"/vimServiceVersions.xml\", sslContext)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/pyVim/connect.py\", line 588, in __GetElementTree\n    conn.request(\"GET\", path)\n  File \"/usr/lib64/python2.7/httplib.py\", line 1017, in request\n    self._send_request(method, url, body, headers)\n  File \"/usr/lib64/python2.7/httplib.py\", line 1045, in _send_request\n    self.putrequest(method, url, **skips)\n  File \"/usr/lib64/python2.7/httplib.py\", line 946, in putrequest\n    host_enc = self.host.encode(\"ascii\")\nAttributeError: 'NoneType' object has no attribute 'encode'\n",
    "changed": false,
    "module_stdout": "",
    "failed": true,
    "rc": 0,
    "msg": "MODULE FAILURE"
}
```
