### ISSUE TITLE
lineinfile to encrypted var file corrupt vault

### ISSUE THREAD

**Issue by Nir-Tal** [ansible/ansible#25739]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

LineInFile + ansible-vault

##### ANSIBLE VERSION

```
2.2.2.1
```

##### OS / ENVIRONMENT

Mac OSX
##### SUMMARY

I'm writing a playbook to add var item to var file on the local host to be used with other playbook when deploying

I'm using lineinfile module to add item to var
```yaml
    tasks:
      - name: Read present users list
        command: 'grep "add_name: {{ customer_name }}" ../roles/exchange/vars/main.yml'
        register: exist
        check_mode: no
        ignore_errors: True
        changed_when: False

      - name: Add customer to present users list
        lineinfile:
          dest: ../roles/exchange/vars/main.yml
          insertafter: '^customer_users:'
          line: "  - { add_name: {{customer_name}} , password: '{{customer_password}}' , foldername: '{{customer_folder}}' }"
        when: exist.rc != 0
```
I'm running the playbook against encrypted var file with `--ask-vault-password`

After running the playbook the var file cannot be decrypted and provide the following error:
```
ERROR! Unexpected Exception: Non-hexadecimal digit found
```

When decrypting the vault manually before running the playbook and encrypting after that everything works as expected.
##### STEPS TO REPRODUCE

create var file with:
```yaml
customer_users:
```
create playbook to write to var file:
```yaml
---
  - hosts: localhost
    connection: local
    vars_prompt:
      - name: customer_name
        prompt: "What is the name of the customer (without spaces) ?"
        private: no
    vars:
      customer_password: "{{ lookup('pipe', 'date +%s%S | sha256sum | base64 | head -c 12 ; echo') }}"
      customer_folder: "Arch-{{ lookup('pipe', 'date +%s%N | sha256sum | base64 | head -c 6 ; echo') }}"

    tasks:
      - name: Read present users list
        command: 'grep "add_name: {{ customer_name }}" ../roles/exchange/vars/main.yml'
        register: exist
        check_mode: no
        ignore_errors: True
        changed_when: False

      - name: Add customer to present users list
        lineinfile:
          dest: ../roles/exchange/vars/main.yml
          insertafter: '^customer_users:'
          line: "  - { add_name: {{customer_name}} , password: '{{customer_password}}' , foldername: '{{customer_folder}}' }"
        when: exist.rc != 0
```

Encrypt the var file with `ansible-vault encrypt` and run the playbook

##### EXPECTED RESULTS

var file can be decrypted
##### ACTUAL RESULTS

After running the playbook the var file cannot be decrypted and provide the following error:
```
ERROR! Unexpected Exception: Non-hexadecimal digit found
```
