### ISSUE TITLE
Inject variables from separated file into playbook

### ISSUE THREAD

**Issue by a9tm** [ansible/ansible#25738]
##### ISSUE TYPE

 - Usage

##### COMPONENT NAME

user
mysql_user

##### ANSIBLE VERSION

```
2.3.0
```

##### CONFIGURATION

Defaults

##### OS / ENVIRONMENT

CentOS 7.3

##### SUMMARY

I'm currently re-writing a playbook where there's a role to create system user and mysql users as well. I'm following this template:

    |-- inventories
    |   |-- staging
    |   |   |-- hosts
    |   |   |-- group_vars
    |-- roles
    |   |-- create_users
    |   |   |-- tasks
    |   |   |   |-- main.yml
    |   |   |-- handlers
    |   |   |-- vars
    |   |   |    |-- users.yml
    |   |-- create_mysql_users
    |   |   |-- tasks
    |   |   |   |-- main.yml
    |   |   |-- vars
    |   |   |   |-- users.yml
    |-- site.yml   

##### STEPS TO REPRODUCE

site.yml content

```yaml
    - hosts: mysql
      remote_user: centos
      become: yes
      become_method: sudo
      roles:
      - create_users
      - create_mysql_users
```
roles/create_mysql_users/tasks/main.yml content

```yaml
    ---
    - include_vars: users.yml
    
    - name: Create MySQL account
      mysql_user:
        name: {{item.username}}
        password: {{item.password}}
        host_all: {{item.host_all}}
        priv: {{item.priv}}
        when: '{{item.remove}} == False'
      with_items: {{users}}
```

roles/create_mysql_users/vars/users.yml file

```yaml
    users:
      - username: root
        password: [secret]
        host_all: yes
        priv: "*.*:ALL"
        remove: no
```

##### EXPECTED RESULTS

Create MySQL user with password

##### ACTUAL RESULTS

```
ERROR! Syntax Error while loading YAML.
```
