### ISSUE TITLE
win_dsc : Stringified enum types are not accepted as they are in native policy files

### ISSUE THREAD

**Issue by ricardogaspar2** [ansible/ansible#25754]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`win_dsc` while using `cAdministrativeTemplateSetting` from `PolicyFileEditor` Module (https://github.com/dlwyatt/PolicyFileEditor)

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 83703e3137) last updated 2017/06/15 16:47:54 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/afs/cern.ch/user/r/rchavesg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /afs/cern.ch/user/r/rchavesg/ansible/lib/ansible
  executable location = /afs/cern.ch/user/r/rchavesg/ansible/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
My ansible.cfg as the default/original settings

##### OS / ENVIRONMENT

Ansible Control Machine is running on a CENTOS  `CentOS Linux release 7.3.1611 (Core)` and managing Windows Server 2012 machines.

##### SUMMARY
While using the cAdministrativeTemplateSetting DSC Resource with win_dsc module and specifying a value for the**Type** property ("Unknown","String","ExpandString","Binary","DWord","MultiString","QWord","None") the following error is throwned:

`fatal: [myserver.mydomain.com]: FAILED! => {"Data": "1", "Ensure": "Present", "KeyValueName": "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirUNC", "PolicyType": "Machine", "Type": "Dword", "attributes": [{"Key": "Type", "Name": "Type", "Value": "Dword"}, {"Key": "Ensure", "Name": "Ensure", "Value": "Present"}, {"Key": "Data", "Name": "Data", "Value": "1"}, {"Key": "KeyValueName", "Name": "KeyValueName", "Value": "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirUNC"}, {"Key": "PolicyType", "Name": "PolicyType", "Value": "Machine"}], "changed": false, "dsc_attributes": {"Data": "1", "Ensure": "Present", "KeyValueName": "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirUNC", "PolicyType": "Machine", "Type": "Dword"}, "failed": true, "msg": "Convert property 'Type' value from type 'STRING' to type 'SINT32' failed\r\n At line:12, char:2\r\n Buffer:\r\nirectResourceAccess\";\n};^\n\ninsta\r\n", "reboot_required": null, "resource_name": "cAdministrativeTemplateSetting"}`

The **Type** property is an Integer. Found it in the cAdministrativeTemplateSetting resource MOF file definition (https://github.com/dlwyatt/PolicyFileEditor/blob/master/DscResources/PshOrg_AdminTemplateSetting/PshOrg_AdminTemplateSetting.schema.mof):
`[write,ValueMap{"0","1","2","3","4","7","11","-1"},Values{"Unknown","String","ExpandString","Binary","DWord","MultiString","QWord","None"}] sint32 Type;`

The thing is that using a DSC Script is possible to use these string values ("Unknown","String","ExpandString","Binary","DWord","MultiString","QWord","None") and in Ansible it's not.

##### STEPS TO REPRODUCE

1. Install the PolicyFileEditor in PowerShell of the target machine:
```
PS C:\Users\user>Find-DSCResource -ModuleName PolicyFileEditor
PS C:\Users\user> Install-Module PolicyFileEditor
```
2. Run a simple DSC Script on the target Windows machine to prove that the resource **works fine**:
```powershell
Configuration LocalGPO
{
    param
    (
        [string[]] $NodeName = 'localhost'
    )

    Import-DSCResource -ModuleName PolicyFileEditor

    Node $NodeName
    {
        cAdministrativeTemplateSetting "RDP Users Home Directory Path"
        {
        #    SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services!WFHomeDirUNC 
        #    SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services!WFHomeDir
        #    SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services!WFHomeDirDrive
            KeyValueName = "SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\WFHomeDir"
            PolicyType = "Machine"
            Data = "\\servershare\test"
            Ensure = "Present"
            Type = "String"
        }

        cAdministrativeTemplateSetting "RDP Users Home Directory Letter"
        {
            KeyValueName = "SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\WFHomeDirDrive"
            PolicyType = "Machine"
            Data = "X:"
            Ensure = "Present"
            Type = "String"
        }

        cAdministrativeTemplateSetting "RDP Users Home Directory UNC boolean"
        {
            KeyValueName = "SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\WFHomeDirUNC"
            PolicyType = "Machine"
            Data = "1"
            Ensure = "Present"
            Type = "Dword"
        }

    }
}

LocalGPO
Start-DscConfiguration -Path .\LocalGPO -Wait -Force -Verbose
```

3. On the target machine, run the command `gpupdate` to update the Group Policy. Then Check the registry keys in `HKLM:SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services\`. There should be a **DWORD** key with the name `WFHomeDirUNC` and value `1`.

Using Ansible with the same strategy:
```yaml
---
 - hosts: windows-ansible
   tasks:
# GPO rule
   - name: "RDP Users Home Directory Path"
     win_dsc:
      resource_name: cAdministrativeTemplateSetting
      Ensure: "Present"
      KeyValueName: "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDir"
      PolicyType: "Machine"
      Data: "\\\\servershare\\test"

   - name: "RDP Users Home Directory Letter"
     win_dsc:
      resource_name: cAdministrativeTemplateSetting
      Ensure: "Present"
      KeyValueName: "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirDrive"
      PolicyType: "Machine"
      Data: "X:"

   - name: "RDP Users Home Directory UNC boolean"
     win_dsc:
      resource_name: cAdministrativeTemplateSetting
      Ensure: "Present"
      KeyValueName: "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirUNC"
      PolicyType: "Machine"
      Data: 1 # Also tried with "1"
      Type: Dword #Also tried with "DWord" and  "[Microsoft.Win32.RegistryValueKind]::DWord"
...
```
**Note:** I think by default, when not specifying the **Type** property, the resource assumes it is a **String**.

##### EXPECTED RESULTS
All the win_dsc settings to be applied correclty like in the DSC Script.

![gpedit-multiple_values-setting-example-croped](https://user-images.githubusercontent.com/3660448/27188691-47ceea8e-51ef-11e7-9b43-e9e88231b2bd.png)

##### ACTUAL RESULTS
The last resource didn't work because of a type conversion from String to SINT32. This is just part of the output from the ansible playbook.
```
TASK [RDP Users Home Directory UNC boolean] *****************************************************************************************************************
task path: /afs/mydomain.com/user/r/rchavesg/config_test.yml:30
Using module file /afs/mydomain.com/user/r/rchavesg/ansible/lib/ansible/modules/windows/win_dsc.ps1
<windev-test-05.mydomain.com> ESTABLISH WINRM CONNECTION FOR USER: None on PORT 5986 TO windev-test-05.mydomain.com
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:852: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
EXEC (via pipeline wrapper)
fatal: [windev-test-05.mydomain.com]: FAILED! => {
    "Data": "1",
    "Ensure": "Present",
    "KeyValueName": "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirUNC",
    "PolicyType": "Machine",
    "Type": "Dword",
    "attributes": [
        {
            "Key": "Type",
            "Name": "Type",
            "Value": "Dword"
        },
        {
            "Key": "Ensure",
            "Name": "Ensure",
            "Value": "Present"
        },
        {
            "Key": "Data",
            "Name": "Data",
            "Value": "1"
        },
        {
            "Key": "KeyValueName",
            "Name": "KeyValueName",
            "Value": "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirUNC"
        },
        {
            "Key": "PolicyType",
            "Name": "PolicyType",
            "Value": "Machine"
        }
    ],
    "changed": false,
    "dsc_attributes": {
        "Data": "1",
        "Ensure": "Present",
        "KeyValueName": "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirUNC",
        "PolicyType": "Machine",
        "Type": "Dword"
    },
    "failed": true,
    "msg": "Convert property 'Type' value from type 'STRING' to type 'SINT32' failed\r\n At line:12, char:2\r\n Buffer:\r\nirectResourceAccess\";\n};^\n\ninsta\r\n",
    "reboot_required": null,
    "resource_name": "cAdministrativeTemplateSetting"
}
        to retry, use: --limit @/afs/mydomain.com/user/r/rchavesg/config_test.retry

PLAY RECAP **************************************************************************************************************************************************
windev-test-05.mydomain.com     : ok=4    changed=0    unreachable=0    failed=1

```
But, I managed to put it to work using the actual **integer** corresponding to the **DWord** value. Although I was expecting for win_dsc to accept the same as the DSC script.

Successful code:

```yaml
---
 - hosts: windows-ansible
   tasks:
# GPO rule
   - name: "RDP Users Home Directory Path"
     win_dsc:
      resource_name: cAdministrativeTemplateSetting
      Ensure: "Present"
      KeyValueName: "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDir"
      PolicyType: "Machine"
      Data: "\\\\servershare\\test"

   - name: "RDP Users Home Directory Letter"
     win_dsc:
      resource_name: cAdministrativeTemplateSetting
      Ensure: "Present"
      KeyValueName: "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirDrive"
      PolicyType: "Machine"
      Data: "X:"

   - name: "RDP Users Home Directory UNC boolean"
     win_dsc:
      resource_name: cAdministrativeTemplateSetting
      Ensure: "Present"
      KeyValueName: "SOFTWARE\\Policies\\Microsoft\\Windows NT\\Terminal Services\\WFHomeDirUNC"
      PolicyType: "Machine"
      Data: "1"
      Type: 4 #DWord #"[Microsoft.Win32.RegistryValueKind]::DWord" # 
      ## from the MOF file:
      ## [write,ValueMap{"0","1","2","3","4","7","11","-1"},Values{"Unknown","String","ExpandString","Binary","DWord","MultiString","QWord","None"}] sint32 Type;
...
```
