### ISSUE TITLE
regression: delegated hosts are searched using ansible_host instead of inventory_hostname then results belong to the wrong host

### ISSUE THREAD

**Issue by pilou-** [ansible/ansible#25770]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`lib/ansible/plugins/strategy/__init__.py (StrategyBase)`

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0 (devel 8ad04d6348) last updated 2017/06/15 15:42:47 (GMT +200)
```
```
ansible-playbook 2.3.1.0 (stable-2.3 5605091dc1) last updated 2017/06/15 12:47:10 (GMT +200)
```

##### SUMMARY
When a task is delegated on an host which have an `ansible_host` variable defined, the result host is defined using `ansible_host` instead of `inventory_hostname`. This is a regression introduced by e5cd675b38d49b22f1ecc929943d016fb7159856. This regression was backported in 2.3 (7e605f4e84d5280cb0987fe5c1ea7da0a12b127c).

I have created a [unit test](https://github.com/ansible/ansible/commit/c8ff896cf9158d86116c5ce9eb622e03c9f4c947) in order to test any potential fix and prevent future regression, this unit test is available [here](https://github.com/pilou-/ansible/tree/delegated_host_test_case). Please, add the 3 related commits to any fix attempt.

##### STEPS TO REPRODUCE
inventory (`hosts.yml`):
```yaml
all:
  hosts:
    Korutopi:
    Orfeo:
```

Hosts configuration:
```
$ cat host_vars/Korutopi/connection.yml
ansible_host: 10.10.10.10
```

Playbook `test.yml`:
```yaml
---
- hosts: Orfeo
  tasks:
    - name: 'Gather facts from server'
      setup:
        gather_subset: '!all'
      delegate_facts: True
      delegate_to: 'Korutopi'

    - name: 'Check timezone of the server'
      assert:
        that: "{{ hostvars['Korutopi']['ansible_date_time']['tz'] == 'UTC' }}"
        msg: "Server timezone is {{ hostvars['Korutopi']['ansible_date_time']['tz'] }}, expected timezone: UTC"
```

Note that `fact_caching` feature must be disabled while testing this playbook: otherwise the cached facts will interfere.

##### EXPECTED RESULTS

```
ansible-playbook -i hosts.yml -l Orfeo test.yml 

PLAY [Orfeo] *

TASK [Gathering Facts] *
ok: [Orfeo]

TASK [Gather facts from server] *
ok: [Orfeo -> 10.10.10.10]

TASK [Check timezone of the server] *
ok: [Orfeo] => {
    "changed": false, 
    "msg": "All assertions passed"
}

PLAY RECAP *
Orfeo                      : ok=3    changed=0    unreachable=0    failed=0 
```

##### ACTUAL RESULTS
```
PLAY [Orfeo] *

TASK [Gathering Facts] *
ok: [Orfeo]

TASK [Gather facts from server] *
ok: [Orfeo -> 10.10.10.10]

TASK [Check timezone of the server] *
fatal: [Orfeo]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'dict object' has no attribute 'ansible_date_time'\n\nThe error appears to have been in '/home/pilou/admin/ansible/test.yml': line 10, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: 'Check timezone of the server'\n      ^ here\n"}
	to retry, use: --limit @/home/pilou/admin/ansible/test.retry

PLAY RECAP ***************************************************************************************************************************************************
Orfeo                      : ok=2    changed=0    unreachable=0    failed=1  
```
