### ISSUE TITLE
eos deprecation warning on transport even when not used and when used in provider

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible#25779]
##### SUMMARY

eos throws deprecation warning on transport even when the param is not used explicitly and when used in provider. 

This issue exists only for `2.3`.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module_utils/eos.py
##### ANSIBLE VERSION

```
2.3
```

##### STEPS TO REPRODUCE

```
---
- name: Config using the core module
  hosts: eoshost

  tasks:
    - name: Config Using Core Module
      eos_facts:
        authorize: yes
        gather_subset: all
      register: response
```

##### EXPECTED RESULTS

The playbook should run with no warning
##### ACTUAL RESULTS

Throws deprecation warning on transport.

```
PLAY [Config using the core module] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [eoshost]

TASK [Config Using Core Module] ***********************************************************************************************************************************************************************************
 [WARNING]: argument transport has been deprecated and will be removed in a future version

ok: [eoshost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
eoshost                    : ok=2    changed=0    unreachable=0    failed=0   
```
