### ISSUE TITLE
group_vars/all not useable for storing paths to included tasks

### ISSUE THREAD

**Issue by skvidal** [ansible/ansible#2579]
For example:
group_vars/all:

``` yaml

---
files: /home/skvidal/ansible/files
tasks: /home/skvidal/ansible/tasks
playbooks: /home/skvidal/ansible/playbooks
handlers: /home/skvidal/ansible/handlers
```

playbook has:

``` yaml
- name: test vars in included tasks
  hosts: myserver
  user: root
  gather_facts: True

  vars_files:
  - $vars/base.yml

  tasks:
  - include: ${tasks}/test1.yml

  handlers:
  - include: ${handlers}/restart_services.yml

```

that results in

```
ERROR: file not found: playbooks/${tasks}/test1.yml
```

just to be sure:

```
ls /home/skvidal/ansible/tasks/test1.yml
      /home/skvidal/ansible/tasks/test1.yml
```

I'd really love to be able to use group_vars/all as a global var definition, but I can't for the above. There are a number of work arounds but I'd rather something a bit more graceful.

Suggestions?
