### ISSUE TITLE
proxmox module: missing pubkey option

### ISSUE THREAD

**Issue by cwiggs** [ansible/ansible#25835]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
proxmox [http://docs.ansible.com/ansible/proxmox_module.html](http://docs.ansible.com/ansible/proxmox_module.html)

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/cwiggs/dev/ansible/ansible.cfg
  configured module search path = [u'./ansible-modules-extras/cloud/misc/']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
inventory      = ./hosts
library        = ./ansible-modules-extras/cloud/misc/
```

##### OS / ENVIRONMENT
```
Running ansible on workstation:
Distributor ID: neon
Description:    KDE neon User Edition 5.10
Release:        16.04
Codename:       xenial
```

```
Running playbook against: Proxmox Virtual Environment 4.4-1/eb2d6f1e
```

##### SUMMARY
Using parameter 'pubkey' throws an error with running ansible-playbook:

```
fatal: [vmhost01]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (proxmox) module: pubkey. Supported parameters include: api_host,api_password,api_user,cpus,cpuunits,disk,force,hostname,ip_address,memory,mounts,nameserver,netif,node,onboot,ostemplate,password,pool,searchdomain,state,storage,swap,timeout,validate_certs,vmid"}
```

However according to the [documentation](http://docs.ansible.com/ansible/proxmox_module.html) pubkey is an option.  Looking at the [code](https://github.com/ansible/ansible-modules-extras/blob/devel/cloud/misc/proxmox.py) there is no pubkey anywhere in the module.

##### STEPS TO REPRODUCE
```
* run playbook with proxmox module with 'pubkey' as a parameter
* ansible errors out
```

tasks main.yml:
```yaml
- name: "Creating fog01 container"
  proxmox:
    node: "{{ node }}"
    api_host: "{{ api_host }}"
    api_user: "{{ api_user }}"
    api_password: "{{ proxmox_password }}"
    cpus: 2
    disk: 15
    ip_address: '10.26.9.36'
    memory: 4096
    ostemplate: 'local:vztmpl/ubuntu-16.04-standard_16.04-1_amd64.tar.gz'
    hostname: 'fog01'
    storage: 'local-zfs'
    state: 'present'
    pubkey: "{{ pubkey }}"
```

vars main.yml:
```yaml
---
# General vars
node: "vmhost01"
api_host: "10.26.9.10"
api_user: "********@pam"
proxmox_password: "**************"
pubkey: "{{ lookup('file', 'roles/proxmox/files/ansible.pub') }}"
```

##### EXPECTED RESULTS
Ansible should create a container and put  the public key in the ~/.ssh/authorized_keys file

##### ACTUAL RESULTS
Ansible errors out saying that 'pubkey' isn't an option.

```
fatal: [vmhost01]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_host": "10.26.9.10", 
            "api_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "api_user": "*****@pam", 
            "cpus": 2, 
            "disk": 15, 
            "hostname": "fog01", 
            "ip_address": "10.26.9.36", 
            "memory": 4096, 
            "node": "vmhost01", 
            "ostemplate": "local:vztmpl/ubuntu-16.04-standard_16.04-1_amd64.tar.gz", 
            "pubkey": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCj8fIRH0HySBTlrZ9ShQpUPLvDiMYQiXc8BWU4hns+9HuP3C3qI+e2IWGZXMRrlbrTa0aQi3fCH875fQlSYZL09LTez0d4XdckuZfiDXE+Oo+iuLNsXkgXtFub1G36XA3n41x2/CI9XL9uaoo8Acx9Mnp/Jo3F8KgvZUh2OxMRRR4txHaULmh6b5xbySL1HPkdvaVYWW9jS6S6ipQln4rL25iRulUHbbKo+w44+2Jc5/A2aAaY5h05inpdtkNXDiaFwuFr8DEou96iCzpupAppOn0XSv4jaKLjsXTvS0a39tqTIWIueqaTl1WnPEGXCYZCaBLuG5jqzkpDCYIEB0QJ ansible", 
            "state": "present", 
            "storage": "local-zfs"
        }
    }, 
    "msg": "Unsupported parameters for (proxmox) module: pubkey. Supported parameters include: api_host,api_password,api_user,cpus,cpuunits,disk,force,hostname,ip_address,memory,mounts,nameserver,neif,node,onboot,ostemplate,password,pool,searchdomain,state,storage,swap,timeout,validate_certs,vmid"
}

```
