### ISSUE TITLE
Ansible doesn't work on Linux guests with root filesystem in read-only mode. 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#25831]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
all

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:36) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Fedora 24 ansible install, managing all common linux distributions. Ubuntu, Debian, Redhat, Centos

##### SUMMARY
Ansible is not working when VM's / partition is in read only mode. I am trying to use ansible as a method of recognising which VM's on a vmware are in read-only mode after datastore failure and then trigger vmware to hard reset. 

##### STEPS TO REPRODUCE

```yaml
- hosts: linux
  tasks:
    - name: Check for read only file systems
      shell: 'awk ''$4 ~ /(^|,)ro(,|$)/'' /proc/mounts|sed ''/tmp/,/^/d''' 
      register: result
      changed_when: result.stdout != ""
      failed_when: "'SUCCESS' in result.stderr"
    - name: Check
      debug: msg="No Read-Only Filesystem detected."
      when: result.stdout == ""

    - name: Confirm
      debug: msg="Read-Only Filesystem detected!"
      when: result.stdout != ""

    - mail:
       host: xxx
       port: 587
       username: xxx
       password: xxx
       from: xxx
       to: xxx
       subject: '{{ansible_hostname}} Read-Only Filesystem detected !'
       body: '{{ansible_fqdn}} : {{result.stdout}}'
      delegate_to: localhost
      when: result.changed
```

##### EXPECTED RESULTS
Ansible should return result.stdout.
I have edited ansible.cfg to match setting from here : https://github.com/ansible/ansible/issues/5725 
remote_tmp     = /tmp/${USER}/ansible  

##### ACTUAL RESULTS

```
ansible -vvvv -m ping testhost
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin minimal of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
META: ran handlers
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/ping.py
<testhost> ESTABLISH SSH CONNECTION FOR USER: None
<testhost> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/xxx/.ansible/cp/267a45c4af testhost '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/${USER}/ansible/ansible-tmp-1497791641.37-81867972228751 `" && echo ansible-tmp-1497791641.37-81867972228751="` echo /tmp/${USER}/ansible/ansible-tmp-1497791641.37-81867972228751 `" ) && sleep 0'"'"''
<testhost> (1, '', "OpenSSH_7.2p2, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 16193\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\nmkdir: cannot create directory `/tmp/xxx': Read-only file system\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\n")
testhost | UNREACHABLE! => {
    "changed": false, 
    "msg": "Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the remote directory. Consider changing the remote temp path in ansible.cfg to a path rooted in \"/tmp\". Failed command was: ( umask 77 && mkdir -p \"` echo /tmp/${USER}/ansible/ansible-tmp-1497791641.37-81867972228751 `\" && echo ansible-tmp-1497791641.37-81867972228751=\"` echo /tmp/${USER}/ansible/ansible-tmp-1497791641.37-81867972228751 `\" ), exited with result 1", 
    "unreachable": true
}
```
