### ISSUE TITLE
os_server problems with special chars in metadata

### ISSUE THREAD

**Issue by DarkBitz** [ansible/ansible#25845]
- Bug Report

##### COMPONENT NAME
os_server

##### ANSIBLE VERSION
```
ansible 2.3.0.0
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY
metadata does not allow special chars like +. 

##### STEPS TO REPRODUCE
```yaml
os_server:
    ...
    name: "fancy-instance-name"
    ...
    meta: "chrony=2.1.1,libstdc++=4.8.5"
```

##### EXPECTED RESULTS
No errors and updated metadata.

##### ACTUAL RESULTS
```
Error updating metadata: Invalid input for field/attribute metadata. Value: {u'libstdc++': u'4.8.5', u'chrony': u'2.1.1'}. Additional properties are not allowed (u'libstdc++' was unexpected) (HTTP 400) (Request-ID: req-214156ec-9bdd-4cf8-bfea-46401d28990b)"
```
