### ISSUE TITLE
Linode Module -- Bad values should bail, not continue

### ISSUE THREAD

**Issue by rwaweber** [ansible/ansible#25842]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- Linode module
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 3f17e87c5a) last updated 2017/06/18 00:06:32 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/demos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/demos/dev/ansible/lib/ansible
  executable location = /home/demos/dev/ansible/bin/ansible
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]

```

##### OS / ENVIRONMENT

- N/A

##### SUMMARY

- In some situations, when bad data is provided to the module, the execution will still talk to the linode api; doing things on the users behalf. This seems misleading to a user and could end up causing them some unneccessary expenditures. At the very least, I didn't expect it to do this.

##### STEPS TO REPRODUCE

```yaml
---
- name: build me a linode
  hosts: local
  tasks:
   - local_action:
       name: dont_make_me
       module: linode
       plan: 1
       datacenter: 2
       distribution: 125 # important for this example
       ssh_pub_key: 'ssh-rsa 42'
       swap: 768
       wait: yes
       wait_timeout: 600
       state: present
       alert_bwquota_enabled: True
       alert_bwquota_threshold: 80
       alert_bwin_enabled: True
       alert_bwin_threshold: 10
       alert_cpu_enabled: True
       alert_cpu_threshold: 210
       alert_bwout_enabled: True
       alert_bwout_threshold: 10
       alert_diskio_enabled: True
       alert_diskio_threshold: 10000
       backupweeklyday: 1
       backupwindow: 2
       displaygroup: 'test'
       additional_disks:
        - {Label: 'disk1', Size: 2500, Type: 'raw'}
        - {Label: 'newdisk', Size: 2000}
       watchdog: True
```

##### EXPECTED RESULTS

- returns a failure
- doesn't do anything to the linode account, since it wasn't a valid distributionID

##### ACTUAL RESULTS

- returns a failure
- creates a linode without a distribution template

###### MY SUSPICIONS
- I have a feeling that this isn't the only parameter that has this sort of thing occur.

```
ansible-playbook provision.yml -i hosts

$ cat hosts
[local]
local ansible_host=localhost

```

I would be happy to look at this myself and get a fix drafted!
