### ISSUE TITLE
Add function 'absent' to pamd.py, to remove a whole rule

### ISSUE THREAD

**Issue by silvinux** [ansible/ansible#25855]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

/usr/lib/python2.7/site-packages/ansible/modules/system/pamd.py
Add function 'absent' to pamd.py, to remove a whole rule

```
- name: "Remove rules with pam_tally"
  become: yes
  pamd:
    name: system-auth
    type: auth
    control: requisite
    module_path: pam_tally.so
    state: absent
```

##### ANSIBLE VERSION

```

```

##### SUMMARY

Need to ensure to some rules are not in the pamd files. 
           
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
