### ISSUE TITLE
yum_repository - multiple GPG keys

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible#25867]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
yum_repository

##### ANSIBLE VERSION
2.3.1.0

##### OS / ENVIRONMENT
Control host: Fedora 26
Servers: CentOS 7.3

##### SUMMARY
Some public Yum repositories use multiple GPG keys and yum_repository does not support that currently.

##### STEPS TO REPRODUCE

```yaml
    - name: Enable Kubernetes yum repository
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: 
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        state: present
```

##### EXPECTED RESULTS
Multiple entries would be added for the "gpgkey" key in the Yum repository configuration.

```
gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
```

##### ACTUAL RESULTS

```
gpgkey = ['https://packages.cloud.google.com/yum/doc/yum-key.gpg', 'https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg']
```

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gtirloni** [comment]
Workaround is to supply it with a single string and added newlines:

```yaml
    - name: Enable Kubernetes yum repository
      yum_repository:
        name: kubernetes
        description: Kubernetes
        baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled: yes
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg\nhttps://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
        state: present
```
