### ISSUE TITLE
invalid 'ipasudoopt': Only one value is allowed

### ISSUE THREAD

**Issue by auth-day** [ansible/ansible#25863]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ipa
##### ANSIBLE VERSION

```
2.3.1.0
```

##### SUMMARY

When I add option  

```
sudoopt:
    - '!authenticate'

```
it says: 
```
TASK [ipa_sudorule] ********************************************************************************************************************************************************************
fatal: [10.200.3.155]: FAILED! => {"changed": false, "failed": true, "msg": "repsonse sudorule_add_option: invalid 'ipasudoopt': Only one value is allowed"}
```

##### STEPS TO REPRODUCE

```
  - ipa_sudorule:
      name: "{{ hostname }}"
      description: "Sudo rule for {{ hostname }}"
      sudoopt:
      - '!authenticate'
      cmdcategory: all
      state: present
      hostgroup:
        - "{{ hostname }}"
      usergroup:
        - "{{ hostname }}-admins"
        - "{{ hostname }}-admins-ext"
        - admins
      ipa_host: *
      ipa_user: *
      ipa_pass: *


```

##### ACTUAL RESULTS

the same error 

```

```
