### ISSUE TITLE
core junos_rpc module conflicts to Juniper.junos module

### ISSUE THREAD

**Issue by vnitinv** [ansible/ansible#25892]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
https://docs.ansible.com/ansible/junos_rpc_module.html

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
```

##### CONFIGURATION
Not reqired

##### OS / ENVIRONMENT
Not required

##### SUMMARY
We had module name junos_rpc from ansible 2.1 timeframe. 
http://junos-ansible-modules.readthedocs.io/en/1.4.2/junos_rpc.html
Why same name was chosen in core module. It is causing lot of confusion to user. 
As a matter of bug, sometimes even if roles is defined in playbook core module is being invloked.

##### STEPS TO REPRODUCE
not required

```yaml
---
- name: Junos rpc call
  hosts: MX
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
    - name: Get rpc run
      junos_rpc:
        host={{ inventory_hostname }}
```
