### ISSUE TITLE
Ansible ASA_acl: Failed to connect to the host via ssh: Connection closed by remote host.\r\n

### ISSUE THREAD

**Issue by pmares127** [ansible/ansible#25899]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

- asa_acl - Manage access-lists on a Cisco ASA

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

```

##### CONFIGURATION

No config-changes made.

##### OS / ENVIRONMENT
 Debian 8.8.0

##### SUMMARY
 

# if I Start my Playbook with "Ansible-playbook playbook-yml -vvv" I get this Error: 

Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/asa/asa_acl.py
<192.168.6.6> ESTABLISH SSH CONNECTION FOR USER: user
<192.168.6.6> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/a002569a2b 192.168.6.6 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.6.6> (255, '', 'Permission denied (publickey,password).\r\n')
fatal: [testasa]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n",
    "unreachable": true
}
        to retry, use: --limit @/usr/bin/playbook.retry

# and if I start it with --ask-pass i get this: 

task path: /usr/bin/playbook.yml:16
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/asa/asa_acl.py
<192.168.6.6> ESTABLISH SSH CONNECTION FOR USER: user
<192.168.6.6> SSH: EXEC sshpass -d12 ssh -C -o ControlMaster=auto -o ControlPersist=60s -o User=user -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/a002569a2b 192.168.6.6 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<192.168.6.6> (255, "Type help or '?' for a list of available commands.\r\n\rciscoasa# /bin/sh -c 'echo ~ && sleep 0'", 'Connection to 192.168.6.6 closed by remote host.\r\n')
fatal: [testasa]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Connection to 192.168.6.6 closed by remote host.\r\n",
    "unreachable": true
}
        to retry, use: --limit @/usr/bin/playbook.retry

The Hosts file has got an entry with 
[Servers]
testasa Ansible_host=192.168.6.6  <-- Ansible_user and Ansible_pass is in it as well.

Can Someone help me with this issue? I saw an other thread to that problem, but that could not help me.

##### STEPS TO REPRODUCE

```yaml
- name: Cisco ASA access-list config
  connection: ssh
  hosts: servers
  gather_facts: false
  remote_user: user

  vars:
    cli:
      username: user
      password: rcconnect007
      host: 192.168.6.6
      authorize: yes
#      key: AAAAB3NzaC1yc2EAAAADAQABAAAAgQC7igtonAc8u7pbEcgWAiJiQvOwdSZpXE40/L7tM8V8BXwzjlyjchoUsFFM1+U7xiNNvGRObLXNxpBLBCeSYox8HDsFCAwiRVcC9JDVyOIIZWyurxa8fMNUY39GfV0XmkP8rhEdOa8XvMlrykEJ6s8l9r//4BJaWBsonLTx43XsLw==

  tasks:
    - name: configure access-list
      asa_acl:
        lines:
          - access-list acl_inside extended permit tcp object-group dummy-group any eq www
          - access-list acl_inside extended permit udp object-group dummy-group any eq domain
          - access-list acl_inside extended deny ip any any
        before: clear configure access-list acl_inside
        match: strict
        replace: block
        provider: "{{ cli }}"
#      register: result

    - debug: var=result

```

##### ACTUAL RESULTS

```

```
