### ISSUE TITLE
Offer more graceful way to replace instances in an AWS EC2 Auto Scaling Group

### ISSUE THREAD

**Issue by jonathanwcrane** [ansible/ansible#25929]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
ec2_asg (AWS EC2 Autoscaling Group)

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/hcv902/dev/ansible/stateless-rehydration/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 |Anaconda 4.4.0 (x86_64)| (default, Dec 20 2016, 23:05:08) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
```

##### OS / ENVIRONMENT

OS:  Running on Mac OS Sierra 12.12.5
Target OS:  N/A (AWS)

##### SUMMARY

When replacing instances in an ASG, Ansible terminates the instances in each "batch" more or less simultaneously with launching the new ones.  It would be more graceful to update the Launch Config, then increase desired_instances by batch_size, wait for the prescribed time, then decrement, etc until it has replaced the requisite number of instances.  This should be offered as an option in a future release of Ansible.

##### STEPS TO REPRODUCE

```yaml
- name: update asg 
  ec2_asg:
    profile:               "{{ aws_profile }}"
    name:                  "{{ asg.name }}"
    launch_config_name:    "{{ new_lc_name }}"
    region:                "{{ asg.region }}"
    max_size:              "{{ current_asg_facts.max_size | int }}"
    min_size:              "{{ current_asg_facts.min_size | int }}"
    desired_capacity:      "{{ current_asg_facts.desired_capacity | int }}"
    replace_batch_size:    "{{ replace_batch_size }}"
    wait_for_instances:    true
    lc_check:              true
    replace_all_instances: true
    #go ahead and make this explicit
    termination_policies: 'Default'
    #go ahead and save us some trouble if possible
    lc_check:              true
    state:                 present

```

##### EXPECTED RESULTS

I expected the capacity of my ASG to remain constant, rather than seeing an immediate drop in capacity while the new instances passed health checks, configured themselves, etc.

##### ACTUAL RESULTS

Instances were terminated immediately, with new ones launched more or less simultaneously

```

```
