### ISSUE TITLE
Ansible Git Module ssh-keyscan error

### ISSUE THREAD

**Issue by MyTotoro** [ansible/ansible#25937]
- Bug Report

Git

```
ansible 2.3.1.0
  config file = /Users/mytotoro/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```
OS:
MacAir
Sierra 10.12.4

##### SUMMARY
Git module produces an ssh-keyscan error

##### STEPS TO REPRODUCE
```
tasks:
    - name: Create git repos
      file:
        path: ~/repos
        state: directory
        mode: 0755
        owner: mytotoro
        group: mytotoro

    - git:
        repo: 'ssh://git@github.com:labstack/echo.git'
        dest: ~/repos/
        # key_file: ~/.ssh/github
        accept_hostkey: yes
        force: yes
```
Needless to say, it doesn't work when I enable the `key_file` for personal projects

##### EXPECTED RESULTS
a folder in ~/repos/

##### ACTUAL RESULTS
```
FAILED! => {"changed": false, "failed": true, "msg": "failed to retrieve hostkey. \"/usr/bin/ssh-keyscan -t rsa -p labstack github.com\" returned no matches. [stderr]: Bad port 'labstack'\n"}
```

**Comment by ansibot** [comment]
@MyTotoro Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@MyTotoro Thanks for reporting this issue. Could you please try replacing `:` with `/` in git url as follows : 

```yaml
- git:
    repo: 'ssh://git@github.com/labstack/echo.git'
    dest: ~/repos/
    key_file: ~/.ssh/github
    accept_hostkey: yes
    force: yes
```

I am able to run this ansible playbook as follows :

```
ansible -m git -a "repo=ssh://git@github.com/labstack/echo.git key_file=~/.ssh/github dest=/tmp/ba accept_hostkey=yes force=yes" localhost
localhost | SUCCESS => {
    "after": "687f05470a89150b1b558effbb717b872382ccc5",
    "before": null,
    "changed": true
}
```

Let me know if you face any issue.

**Comment by MyTotoro** [comment]
@Akasurde 

I tried it with `/` instead of `:`, I get a different error - I'm not using key_file, I'm not an owner of the repo or anything like that:

```
'FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin 'ssh:********@github.com/labstack/echo.git' /home/mytotoro/repos", "failed": true, "msg": "Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.\r\nPermission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128,'
```

However, when I used a different url: `https://github.com/labstack/echo.git`, it worked:
```
TASK [git] ********************************************************************************
changed: [...] => {"after": "935a60782cbbc55110e7bd4b33120e4567cbee43", "before": null, "changed": true}
```

So I tried it on my private github repo:
```
- git:
        repo: 'ssh://git@github.com:MyTotoro/....git'
        dest: ~/repos/DBServer
        key_file: ~/.ssh/github
        accept_hostkey: yes
        force: yes
```

I get the same error as above - but I believe I set up my keys correctly. 
and when I use `https://github.com/MyTotoro/....git` as the url, it just hangs (whether or not I include my key_file).
