### ISSUE TITLE
ERROR! Timeout (XXs) waiting for privilege escalation prompt

### ISSUE THREAD

**Issue by bearrito** [ansible/ansible#25961]
Re-opening of https://github.com/ansible/ansible/issues/14426
##### ISSUE TYPE
Issue Type: Bug Report

Ansible Version: Ansible 2.3
Python Version: 2.7.6
Environment: Ubuntu 16.04 Ubuntu 14.04

##### COMPONENT NAME
Ansible SSH connections

Summary:
I am seeing the following error, at random times

FAILED! => {"failed": true, "msg": "ERROR! Timeout (12s) waiting for privilege escalation prompt: "}

**Comment by ansibot** [comment]
@bearrito Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bearrito** [comment]
I am able to SSH into the machine.
Running with `-c paramiko` also works most of the time.

**Comment by bearrito** [comment]
More info

Logging into the machine directly is fast

```
➜  ansible-dock-robot git:(feature/es) ✗ date
Wed Jun 21 11:31:54 EDT 2017
➜  ansible-dock-robot git:(feature/es) ✗ ssh root@x.x.x.x
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-81-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Wed Jun 21 15:29:55 2017 from y.y.yy
machine:~$ exit
logout
Connection to x.x.x.x closed.
➜  ansible-dock-robot git:(feature/es) ✗ date
Wed Jun 21 11:31:58 EDT 2017
➜  ansible-dock-robot git:(feature/es) ✗ 
```

However tasks almost certainly time out initially or after a few

```
TASK [setup] *******************************************************************
ok: [x.x.x.x ]

TASK [jnv.unattended-upgrades : add distribution-specific variables] ***********
ok: [x.x.x.x ]

TASK [jnv.unattended-upgrades : add Debian Wheezy workaround] ******************
skipping: [x.x.x.x ]

TASK [jnv.unattended-upgrades : install unattended-upgrades] *******************
fatal: [x.x.x.x ]: FAILED! => {"failed": true, "msg": "Timeout (32s) waiting for privilege escalation prompt: "}
	to retry, use: --limit @/home/barrett/Git/ansible-dock-robot/build.retry

PLAY RECAP *********************************************************************
x.x.x.x                : ok=2    changed=0    unreachable=0    failed=1   

````

**Comment by bearrito** [comment]
More info

I am not overriding ssh args

```
 EXEC ssh -vvv -F ssh.cfg -o ControlMaster=auto -o ControlPersist=1m -o 'IdentityFile="blha blaht"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=30 -o 'ControlPath=~/.ssh/ansible-%r@%h:%p' x.x.x.x '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-dmvzmfpfnygyyyubcuhrdhvnzmdajrrh; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```

**Comment by mplanchard** [comment]
This is happening to us, also, but only against our old CentOS 5.6 servers. It does **not** occur on plays against Ubuntu 16.04. Ansible is being run from Ubuntu 14.04. Weirdly, turning on verbose output allowed it to successfully execute **some** commands, but it does still eventually timeout. Verbose output for the commands that fail under non-verbose mode is linked in a gist below.

Ansible Version: 2.3.1.0
Paramiko Version: 2.2.1

Playbook:
```yaml
# Populate secrets on PHP servers
- name: Check groups, users, and secrets on PHP servers
  hosts: invision_php:&{{ host_environment }}
  roles:
    # Ensure that base users & groups are present on old servers
    # - this includes the CI user, so it is important that this be
    #   up to date
    - role: groups
      managed_groups: "{{ base_groups }}"
      when: host_environment in ('staging', 'production')
    - role: users
      login_users: "{{ base_login_users }}"
      when: host_environment in ('staging', 'production')
    - role: invision_api
      invision_api_php_server_run: yes
      when: host_environment in ('staging', 'production')
```

The role task that is failing is always the first to request privilege escalation, which winds up being the "manage groups" portion of the following:

```yaml
# Manage system groups

- name: managing the following groups
  debug:
    var: managed_groups

- name: manage groups
  become: yes
  group:
   name: "{{ item.name }}"
   state: "{{ item.state }}"
  with_items: "{{ managed_groups }}"
```

Output (non-verbose - verbose output below):
```
PLAY [Check groups, users, and secrets on PHP servers] ********************************************************

TASK [Gathering Facts] ****************************************************************************************
ok: [stagingweb2]
ok: [stagingweb3]

TASK [groups : managing the following groups] *****************************************************************
ok: [stagingweb3] => {
    "managed_groups": [
        {
            "name": "sysadmin",
            "state": "present",
            "sudo": true
        }
    ]
}
ok: [stagingweb2] => {
    "managed_groups": [
        {
            "name": "sysadmin",
            "state": "present",
            "sudo": true
        }
    ]
}

TASK [groups : manage groups] *********************************************************************************
fatal: [stagingweb3]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}
fatal: [stagingweb2]: FAILED! => {"failed": true, "msg": "Timeout (12s) waiting for privilege escalation prompt: "}

PLAY RECAP ****************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
stagingweb2                : ok=2    changed=0    unreachable=0    failed=1
stagingweb3                : ok=2    changed=0    unreachable=0    failed=1
```


Verbose Output (5 v's): https://gist.github.com/mplanchard/57790ecfad39a19e4c6fb0ade3323427
