### ISSUE TITLE
local_action lineinfile skipping some hosts' input if writing same file

### ISSUE THREAD

**Issue by infrascripting** [ansible/ansible#25968]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`local_action` and `lineinfile`

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = /opt/uss/ansible/config/2.2.1.cfg
  configured module search path = ['/usr/share/ansible']
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When calling `lineinfile` as the module argument to `local_action`, if all hosts are writing information to the same file, not all of the information is successfully added to the file.

This is useful for dynamically generating reports without having to write a custom plugin.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  tasks:
  - name: create csv file
    local_action:
        module: file
        path: ~/outfile.csv
        state: touch
    run_once: yes

  - name: put info in file
    local_action:
        module: lineinfile
        dest: ~/outfile.csv
        line: "Hello World, I am {{ ansible_nodename }}"
```

##### EXPECTED RESULTS

I expected that all of the hosts would be able to successfully insert their information into the file. And at the end of the run, that all of the information would be in that file.

##### ACTUAL RESULTS

All of the hosts returned 'changed', however:

```
$ sort -u hosts | wc -l
600
$ sort -u ~/outfile.csv
381
```

##### Subsequent Runs

On subsequent runs, some hosts reported 'ok', and others 'changed' depending on if they had been put in the file on the initial run. However, even after the second run of the exact same output above:

```
$ sort -u ~/outfile.csv
556
```

##### Temporary Work-arounds

1. Add `serial: 1` to the playbook
2. Run the playbook multiple times (baaaaaad - and does not guaranteed completeness)
