### ISSUE TITLE
docker_container.py _compare_dicts incorrectly reports matches

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible#25974]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.4.0 (add_tmpfs_support_to_docker_container ba3d5d9676) last updated 2017/06/22 01:05:52 (GMT +1100)
  config file = /home/will/tmp/ansible-deploy/ansible.cfg
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/src/ansible-work/ansible/lib/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### OS / ENVIRONMENT
Linux

##### SUMMARY
docker_container.py _compare_dicts() has a logic bug where if the two dictionaries being compared are not of equal length, then it will not detect that they do not match if the keys of the left dictionary (being shorter) match the keys of the right dictionary.

##### STEPS TO REPRODUCE
Easiest is with my PR #25747 , but it would apply to any dictionary-based parameters used in a docker container.

Deploy the following container:
```yaml
---
- hosts: all
  tasks:
  - docker_container:
      name: test
      image: ubuntu:xenial
      entrypoint: /bin/sleep
      command: '86400'
      debug: true
      volumes:
      - /test1
      - /test2
```
Then remove the second entry:
```yaml
- hosts: all
  tasks:
  - docker_container:
      name: test
      image: ubuntu:xenial
      entrypoint: /bin/sleep
      command: '86400'
      debug: true
      volumes:
      - /test1
```

##### EXPECTED RESULTS
The _compare_dictionaries code should report a different in the volume configuration and recreate the container. 

##### ACTUAL RESULTS
This doesn't happen because reliably, the dictionary comparison only runs against the list of items in the new configuration - the shorter volumes entries, and this results in the following comparison results in debug mode:
```
check differences expected_volumes {'/test1': {}} vs {u'/test2': {}, u'/test1': {}}
comparing two dicts: expected_volumes
comparing /test1: {} {}
comparison result for: expected_volumes = True
```
(note, I've added extra debug log lines to highlight the issue).
