### ISSUE TITLE
Datastore Cluster not being found when listed as datastore= parameter, vm template datastore being used by default

### ISSUE THREAD

**Issue by jepurdy** [ansible/ansible#25970]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest.py

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

host_key_checking = False is uncommented in ansible.cfg

##### OS / ENVIRONMENT

This is running from RHEL 6.9 x86_64 and controls other RHEL 6.x x86_64 guests as well as accessing VMware ESXi 6.

##### SUMMARY

When deploying a new VM from a template and defining the datastore= parameter and listing a Datastore Cluster, the new VM is always created on the same datastore as the VM template.  It appears to be completely ignoring the Datastore Cluster that is defined.  However, if a real datastore name within the datastore cluster is used the VM will be provisioned correctly on that datastore.  The environment is an enterprise setup that has multiple datacenters, multiple clusters, and multiple datastore clusters.

The issue here is when trying to deploy 10's or 100's of new guests, it is impractical to manually define an individual datastore target for each target guest.  It would be much more preferable to define the Datastore Cluster and let VMware place the new guest on the appropriate LUN according to space availability.

##### STEPS TO REPRODUCE

Any VM cloned from template will deploy to the same datastore as the template when a datastore cluster is defined.  If an individual datastore within the datastore cluster is defined, it will deploy to that datastore. 

```yaml
---

- hosts: vmcreate
  gather_facts: false
  connection: local
  user: remote
  become: true

  vars_prompt:
    - name: "vcenter_hostname"
      prompt: "Enter vcenter hostname"
      private: no
    - name: "vcenter_user"
      prompt: "Enter vcenter username"
      private: no
    - name: "vcenter_pass"
      prompt: "Enter vcenter password"
      private: yes

  vars:
    notes: 'Created by Ansible'

  tasks:

  - name: create the VM
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      cluster: "{{ cluster_name }}"
      datacenter: "{{ datacenter_name }}"
      folder: "{{ folder_name }}"
      name: "{{ inventory_hostname_short }}"
      state: poweredon
      guest_id: rhel6_64Guest
      annotation: "{{ notes }}"
      disk:
      - size_gb: 50
        type: thin
        datastore: "{{ datastore_name }}"
        autoselect_datastore: False
      - size_gb: 30
        type: thin
        datastore: "{{ datastore_name }}"
        autoselect_datastore: False
      - size_gb: "{{ disk3_size }}"
        type: thin
        datastore: "{{ datastore_name }}"
        autoselect_datastore: False
      hardware:
        memory_mb: "{{ memory_size }}"
        num_cpus: "{{ cpu_number }}"
        scsi: paravirtual
      networks:
      - name: "{{ network_name }}"
        device_type: e1000
        ip: "{{ ip_info }}"
        netmask: "{{ netmask_info }}"
        gateway: "{{ gateway_info }}"
      customization:
        dns_servers:
        - "{{ dns1_info }}"
        - "{{ dns2_info }}"
        domain: example.com
      template: "{{ template_name }}"
      wait_for_ip_address: yes
    register: deploy
    delegate_to: localhost
```

##### EXPECTED RESULTS

I expect the VM deployed from template to be created on the datastore that is appropriate according to it's space requirements within the defined datastore cluster.

##### ACTUAL RESULTS

The VM will be deployed to the same datastore as the template if a datastore cluster is defined.

```
Using /etc/ansible/ansible.cfg as config file
SSH password:
SUDO password[defaults to SSH password]:

PLAYBOOK: vmcreate.yml ******************************************************************************************************************************************************************************
1 plays in vmcreate.yml
Enter vcenter hostname [virtualcenter.example.com]:
Enter vcenter username: user
Enter vcenter password:

PLAY [vmcreate] *************************************************************************************************************************************************************************************
META: ran handlers

TASK [create the VM] ********************************************************************************************************************************************************************************
task path: /home/user/vmcreate.yml:31
Using module file /usr/lib/python2.6/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: user
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp/ansible-tmp-1498056764.14-124742047066847 `" && echo ansible-tmp-1498056764.14-124742047066847="` echo /home/user/.ansible/tmp/ansible-tmp-1498056764.14-124742047066847 `" ) && sleep 0'
<localhost> PUT /tmp/tmpLo2ou3 TO /home/user/.ansible/tmp/ansible-tmp-1498056764.14-124742047066847/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1498056764.14-124742047066847/ /home/user/.ansible/tmp/ansible-tmp-1498056764.14-124742047066847/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=eufidajpepdznrceibzzjftmfawzbplc] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-eufidajpepdznrceibzzjftmfawzbplc; /usr/bin/python2.6 /home/user/.ansible/tmp/ansible-tmp-1498056764.14-124742047066847/vmware_guest.py; rm -rf "/home/user/.ansible/tmp/ansible-tmp-1498056764.14-124742047066847/" > /dev/null 2>&1'"'"' && sleep 0'
changed: [testvm01.example.com -> localhost] => {
    "changed": true,
    "failed": false,
    "instance": {
        "annotation": "Created by Ansible",
        "current_snapshot": null,
        "customvalues": {},
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "2147483647",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": [
                "10.113.x.y"
            ],
            "label": "Network adapter 1",
            "macaddress": "00:50:56:8f:14:c8",
            "macaddress_dash": "00-50-56-8f-14-c8",
            "summary": "DVSwitch: 7f 0f 05 50 d1 93 2e b5-2b 1c d3 79 d5 ce 6e b2"
        },
        "hw_guest_full_name": "Red Hat Enterprise Linux 6 (64-bit)",
        "hw_guest_id": "rhel6_64Guest",
        "hw_interfaces": [
            "eth0"
        ],
        "hw_memtotal_mb": 8192,
        "hw_name": "testvm01",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 2,
        "hw_product_uuid": "420da604-0383-26d0-4ed0-091210614c1e",
        "ipv4": "10.113.x.y",
        "ipv6": null,
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": "Created by Ansible",
            "cluster": "my_cluster",
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "my_datacenter",
            "disk": [
                {
                    "autoselect_datastore": false,
                    "datastore": "my_datastore_cluster",
                    "size_gb": 50,
                    "type": "thin"
                },
                {
                    "autoselect_datastore": false,
                    "datastore": "my_datastore_cluster",
                    "size_gb": 30,
                    "type": "thin"
                },
                {
                    "autoselect_datastore": false,
                    "datastore": "my_datastore_cluster",
                    "size_gb": 10,
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm/nonprod",
            "force": false,
            "guest_id": "rhel6_64Guest",
            "hardware": {
                "memory_mb": 8192,
                "num_cpus": 2,
                "scsi": "paravirtual"
            },
            "hostname": "virtualcenter.********",
            "is_template": false,
            "name": "testvm01",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "e1000",
                    "gateway": "10.113.x.1",
                    "ip": "10.113.x.y",
                    "name": "10.113.x.0%2f24",
                    "netmask": "255.255.255.0"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "state": "poweredon",
            "template": "template_20170607",
            "template_src": "template_20170607",
            "username": "user",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ******************************************************************************************************************************************************************************************
testvm01.example.com      : ok=1    changed=1    unreachable=0    failed=0
```
