### ISSUE TITLE
ec2_elb_facts throws an exception if ELB is deleted during the query

### ISSUE THREAD

**Issue by joejulian** [ansible/ansible#25982]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_elb_facts module

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /kraken/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]
```

##### CONFIGURATION

No changes

##### OS / ENVIRONMENT

N/A

##### SUMMARY

LoadBalancerNotFound: Cannot find Load Balancer <lb name>

##### STEPS TO REPRODUCE

This seems to occur when there is a lag between a service being taken down and the load balancer being removed. We are running kubernetes on aws and when a service is taken down, the load balancer may be removed by kubernetes itself. If, after the service is stopped we run a loop to wait for all the load balancers to be removed, the is occasionally a race condition that produces the above error.

```yaml
- name: Wait for ELBs to be deleted
  action:
    module: ec2_elb_facts
    region: "{{ cluster.providerConfig.region }}"
    aws_access_key: "{{ cluster.providerConfig.authentication.accessKey or omit }}"
    aws_secret_key: "{{ cluster.providerConfig.authentication.accessSecret or omit }}"
    profile: "{{ cluster.providerConfig.authentication.credentialsProfile or omit }}"
  register: elb_facts
  vars:
    vpc_lookup: "elbs[?vpc_id=='{{ vpcid }}']"
  when: kraken_action == 'down' and cluster.providerConfig.provider == 'aws'
  until: (elb_facts is none) or (elb_facts | json_query(vpc_lookup) is none) or (elb_facts | json_query(vpc_lookup) | length <= 1)
  retries: 120
  delay: 5
```

##### EXPECTED RESULTS

The expectation would be that it would loop and wait for the ELBs to be removed but aws. If there's a failure, it should not be fatal.

##### ACTUAL RESULTS

A fatal error occurs.

```
FAILED - RETRYING: Wait for ELBs to be deleted (109 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: </ErrorResponse>
fatal: [localhost]: FAILED! => {"attempts": 13, "changed": false, "failed": true, "msg": "LoadBalancerNotFound: Cannot find Load Balancer ad7dc468e56cc11e7a4ac02570a8bbd5"}
```
