### ISSUE TITLE
Duplicate parameters for container_config in lxc_container module

### ISSUE THREAD

**Issue by zerkms** [ansible/ansible#25988]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lxc_container

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY
This issue is a follow-up (but it's not a duplicate: that issue was about something different but still contains relevant messages) for the https://github.com/ansible/ansible-modules-extras/issues/1998.

In short, if you change the `container_config` it's easy to reach the state when the config contains duplicates.

I understand `lxc` allows some configuration directives to present multiple times in the config, but at least the module could de-duplicate the entries that are guaranteed to be unique.

Eg: `lxc.start.auto`. Having duplicates for it really can cause issues when you expect (or do not) the container to start on the host restart, but due to multiple duplicate lines arbitrarily ordered - the outcome is basically random.

What I suggest: what if the module kept the list of directives that are guaranteed to be unique and for those only kept the currently set values, and removed everything else.

##### STEPS TO REPRODUCE

```yaml
- name: Create a container
  lxc_container:
    name: container-to-demonstrate-duplicate-issues
    template: ubuntu
    state: started
    template_options: "--release xenial"
    container_config:
        - "lxc.start.auto = 1"
```

then change to `lxc.start.auto = 0`

##### EXPECTED RESULTS

There should be just one `lxc.start.auto` in the container's `config` file.

##### ACTUAL RESULTS

There are 2 entries

```

```
