### ISSUE TITLE
OpenStack server userdata field gets corrupted with JSON template file

### ISSUE THREAD

**Issue by pteichner** [ansible/ansible#25999]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
os_server

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### SUMMARY
When Creating an OpenStack instance with userdata specified as JSON (ignition config for CoreOS) it changes the structure of the input from the template file

##### STEPS TO REPRODUCE

```yaml
- name: Lunch Instance
  os_server:
    state: present
    auth:
      auth_url: "{{ os_url }}"
      username: "{{ os_user }}"
      password: "{{ os_pass }}"
      project_name: "{{ os_project }}"
    security_groups: "{{ security_groups}}"
    name: "{{ inventory_hostname }}"
    region_name: RegionOne
    availability_zone: eu-zrh-a
    image: "{{ image }}"
    key_name: SSH
    timeout: 200
    flavor: "{{ instance }}"
    volume_size: 30
    volumes: "{{ volume }}"
    auto_ip: "{{ public_ip}}"
    userdata: "{{lookup('template','./{{inventory_hostname}}.j2',convert_data=true)}}"
  register: instance
```
```json
{
  "ignition": {
    "version": "2.0.0",
    "config": {}
  },
  "storage": {},
  "systemd": {
    "units": [
      {
        "name": "coreos-metadata.service",
        "dropins": [
          {
            "name": "20-clct-provider-override.conf",
            "contents": "[Service]\nEnvironment=COREOS_METADATA_OPT_PROVIDER=--provider=openstack-metadata"
          }
        ]
      },
      {
        "name": "docker-tcp.socket",
        "enable": true,
        "contents": "[Unit]\nDescription=Docker Socket for the API\n\n[Socket]\nListenStream=2375\nBindIPv6Only=both\nService=docker.service\n\n[Install]\nWantedBy=sockets.target\n"
      },
      {
        "name": "coreos-metadata-sshkeys-workaround.service",
        "enable": true,
        "contents": "[Unit]\nDescription=CoreOS Metadata Agent Workaround (SSH Keys)\n\n[Service]\nType=oneshot\nExecStart=/usr/bin/coreos-metadata --provider=openstack-metadata --ssh-keys=core\n\n[Install]\nRequiredBy=multi-user.target\n"
      }
    ]
  },
  "networkd": {},
  "passwd": {}
}
```

##### EXPECTED RESULTS
Openstack instance created and userdata passed correctly

##### ACTUAL RESULTS
Userdata field changed as follows
```
"userdata": "{'passwd': {}, 'networkd': {}, 'storage': {}, 'systemd': {'units': [{'dropins': [{'name': '20-clct-provider-override.conf', 'contents': '[Service]\\nEnvironment=COREOS_METADATA_OPT_PROVIDER=--provider=openstack-metadata'}], 'name': 'coreos-metadata.service'}, {'enable': True, 'name': 'docker-tcp.socket', 'contents': '[Unit]\\nDescription=Docker Socket for the API\\n\\n[Socket]\\nListenStream=2375\\nBindIPv6Only=both\\nService=docker.service\\n\\n[Install]\\nWantedBy=sockets.target\\n'}, {'enable': True, 'name': 'coreos-metadata-sshkeys-workaround.service', 'contents': '[Unit]\\nDescription=CoreOS Metadata Agent Workaround (SSH Keys)\\n\\n[Service]\\nType=oneshot\\nExecStart=/usr/bin/coreos-metadata --provider=openstack-metadata --ssh-keys=core\\n\\n[Install]\\nRequiredBy=multi-user.target\\n'}]}, 'ignition': {'version': '2.0.0', 'config': {}}}", 
```

**Comment by ansibot** [comment]
cc @emonty @shrews @juliakreger @j2sol @rcarrillocruz @thingee
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pteichner** [comment]
It seem that the fact that boolean were turned caps is one of the problem

**Comment by pteichner** [comment]
Workaround was based on suggestion from here https://github.com/ansible/ansible/issues/15603 

As you can see belowe the lookup was changed to file and passed as a string
 **userdata: "{{ lookup('file','./roles/create-instance/templates/{{inventory_hostname}}.j2') | string}}"**

```yaml
- name: Lunch Instance
  os_server:
    state: present
    auth:
      auth_url: "{{ os_url }}"
      username: "{{ os_user }}"
      password: "{{ os_pass }}"
      project_name: "{{ os_project }}"
    security_groups: "{{ security_groups}}"
    name: "{{ inventory_hostname }}"
    region_name: RegionOne
    availability_zone: eu-zrh-a
    image: "{{ image }}"
    key_name: SSH
    timeout: 200
    flavor: "{{ instance }}"
    volume_size: 30
    volumes: "{{ volume }}"
    auto_ip: "{{ public_ip}}"
    userdata: "{{ lookup('file','./roles/create-instance/templates/{{inventory_hostname}}.j2') | string}}"
  register: instance
```
 

_Sent from my ZTE A2017G using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
