### ISSUE TITLE
azure_rm_deployment ignores 'wait_for_deployment_completion' option

### ISSUE THREAD

**Issue by antoineco** [ansible/ansible#26014]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
azure_rm_deployment

##### ANSIBLE VERSION
```
2.3.1.0
```

##### CONFIGURATION
*nope*

##### OS / ENVIRONMENT

macOS Sierra

##### SUMMARY

The `azure_rm_resourcegroup` module ignores the `wait_for_deployment_completion: False` option and blocks until the deployment completes. 

##### STEPS TO REPRODUCE

1. Download the [example ARM templates](https://github.com/Azure/azure-quickstart-templates/tree/master/101-container-registry) to the local ansible directory.

2. Run the following playbook.

```yaml
- name: Create infra
  hosts: localhost
  gather_facts: False

  tasks:

    - name: Create resource group
      azure_rm_resourcegroup:
        name: foobar
        location: westeurope
      register: reg_rg

    - name: Deploy Docker registry
      azure_rm_deployment:
        deployment_name: registry
        resource_group_name: '{{ reg_rg.state.name }}'
        location: '{{ reg_rg.state.location }}'
        template: "{{ lookup('file', './azuredeploy.json') }}"
        parameters: "{{ lookup('file', './azuredeploy.parameters.json') }}"
        wait_for_deployment_completion: False
      register: reg_depl

    - debug: var=reg_depl
```

##### EXPECTED RESULTS
Ansible initiates the deployment then moves on to the `debug` task without waiting for the deployment completion.

##### ACTUAL RESULTS
Ansible blocks until the deployment has completed.
