### ISSUE TITLE
(P2)nxos_bgp - event_history properties and suppress_fib_pending are not idempotent

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#26024]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
- nxos_bgp

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel e8072ee616) last updated 2017/06/21 14:40:23 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

- Ansible Server : Ubuntu 14.04
- Device: Nexus9000 C9508  running 7.0(3)I6(1)

##### SUMMARY
The properties event_history_cli, event_history_detail, event_history_events, event_history_periodic, suppress_fib_pending are not idempotent. The same playbook applied twice shows the result as 'changed'.

##### STEPS TO REPRODUCE

```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  user_ssl: no

---
- name: NXOS Sample Playbook
  hosts: nxos
  connection: local
  gather_facts: no

  tasks:

  - name: Ensure BGP Is Enabled
    nxos_feature:
      feature: bgp
      state: enabled
      provider: "{{ cli }}"

  - name: "Configure BGP non defaults"
    nxos_bgp: &configure_non_default
      asn: 65535
      router_id: 1.1.1.1
      bestpath_always_compare_med: true
      bestpath_aspath_multipath_relax: true
      bestpath_compare_routerid: true
      bestpath_cost_community_ignore: true
      bestpath_med_confed: true
      bestpath_med_missing_as_worst: true
      bestpath_med_non_deterministic: true
      cluster_id: 10.0.0.1
      confederation_id: 99
      disable_policy_batching: true
      enforce_first_as: false
      fast_external_fallover: false
      flush_routes: true
      graceful_restart_helper: true
      graceful_restart_timers_restart: 130
      graceful_restart_timers_stalepath_time: 310
      isolate: false
      log_neighbor_changes: true
      maxas_limit: 50
      neighbor_down_fib_accelerate: true
      reconnect_interval: 55
      router_id: 192.168.0.66
      shutdown: true
      timer_bestpath_limit: 255
      timer_bgp_hold: 110
      timer_bgp_keepalive: 45
      event_history_cli: size_medium
      event_history_detail: size_large
      event_history_events: size_medium
      event_history_periodic: size_small
      suppress_fib_pending: true
      state: present
      provider: "{{ cli }}"
```

##### EXPECTED RESULTS

When the above playbook is run a second time the result should be

PLAY RECAP ************************************************************************************************************************************************
nxxxx-x-xxx.example.com          : ok=2    changed=0    unreachable=0    failed=0 

##### ACTUAL RESULTS

```
PLAY RECAP ************************************************************************************************************************************************
nxxxx-x-xxx.example.com          : ok=2    changed=1    unreachable=0    failed=0
```
