### ISSUE TITLE
AWS EC2 module ignores the idempotency ID when using status

### ISSUE THREAD

**Issue by andrewhowdencom** [ansible/ansible#26021]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = ${NOTHING_EXCITING_GOING_ON_HERE}
  configured module search path = Default w/o overrides
  python version = 3.5.3+ (default, Jun  7 2017, 23:23:48) [GCC 6.3.0 20170516]

```

##### STEPS TO REPRODUCE
1. Create a playbook that consumes the following task:

```
- name: "Ensure the webserver is in the expected state"
  ec2:
    state: "running"
    key_name: "{{ ec2_key_name }}"
    instance_type: "t2.micro"
    image: "{{ ec2_ami_id }}"
    wait: "yes"
    wait_timeout: "300"
    count: 1
    instance_tags: "{{ ec2_tags }}"
    monitoring: "{{ ec2_monitoring }}"
    region: "{{ ec2_region }}"
    vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
    id: "__THIS_IS_A_UNIQUE_ID__"
  register: "ec2_provisioner"
```
2. Notice that it doesn't change anything. Weird, because that instance is stopped
3. Notice that during debugging all VMS are output by ec2_provisioner, rather than just the one that's supposed to be changed.
4. Modify the task by deleting `state`
5. Observe it works as expected.

```yaml
ansible-playbook --inventory-file=inventory/static site.yaml  --limit=infrastructure  --flush-cache
```

##### EXPECTED RESULTS

I expected my machine to start back up again

##### ACTUAL RESULTS

Depending on how I worked it, a machine completely irrelevant was started and modified. (This was beyond terrifying for me!)
