### ISSUE TITLE
iam_role should have a parameter to suppress creation of instance profiles

### ISSUE THREAD

**Issue by bertramn** [ansible/ansible#26023]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
iam_role

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar 13 2017, 20:56:15) [GCC 5.4.0]
```

##### CONFIGURATION
Nothing spectacular

##### OS / ENVIRONMENT
Not relevant

##### SUMMARY
When creating custom roles in AWS using the iam_role module, it is not always desirable to create an instance profile and role association. It would be good if the iam_role gains an additional option to suppress the creation of instance profile.

##### STEPS TO REPRODUCE

The standard iam_role example will create a role and instance profile in AWS.

```yaml
- iam_role:
    name: MyTestRole
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
    managed_policy:
      - arn:aws:iam::aws:policy/PowerUserAccess
```
Creation of instance profiles could be suppressed with an additional task parameter `create_instance_profile`:

```yaml
- iam_role:
    name: MyTestRole
    create_instance_profile: no
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
    managed_policy:
      - arn:aws:iam::aws:policy/PowerUserAccess
```

##### EXPECTED RESULTS

`aws iam list-instance-profiles-for-role --role-name MyTestRole`

```json
{
    "InstanceProfiles": []
}
```

##### ACTUAL RESULTS

`aws iam list-instance-profiles-for-role --role-name MyTestRole`

```json
{
  "InstanceProfiles": [
    {
      "InstanceProfileId": "AIIIIIIIPPPPPPPPPPPP2",
      "InstanceProfileName": "MyTestRole",
      "CreateDate": "2017-06-22T16:47:00Z",
      "Path": "/",
      "Arn": "arn:aws:iam::xxxxxxxxxxxx:instance-profile/MyTestRole",
      "Roles": [
        {
          "AssumeRolePolicyDocument": {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Action": "sts:AssumeRoleWithSAML",
                "Effect": "Allow",
                "Condition": {
                  "StringEquals": {
                    "SAML:aud": "https://signin.aws.amazon.com/saml"
                  }
                },
                "Principal": {
                  "Federated": "arn:aws:iam::xxxxxxxxxxxx:saml-provider/ADFS"
                }
              }
            ]
          },
          "RoleId": "ARREDDFGGGGHHHHJJJK34",
          "CreateDate": "2017-06-03T11:56:47Z",
          "RoleName": "MyTestRole",
          "Path": "/",
          "Arn": "arn:aws:iam::xxxxxxxxxxxx:role/MyTestRole"
        }
      ]
    }
  ]
}
```
