### ISSUE TITLE
vmware_guest state:absent fails on powered on machines

### ISSUE THREAD

**Issue by theballdredge** [ansible/ansible#26020]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
[defaults]
host_key_checking=False
[ansible]
deprecation_warnings=False

##### OS / ENVIRONMENT
Running on OSX targeting vsphere 6.0, expect that this is platform agnostic.

##### SUMMARY
when setting state: absent on a named vm instance, the task fails if the target is powered on.  if a task to power off precedes, it fails if the vm is not present. 

##### STEPS TO REPRODUCE
run a task with state:absent targeting a poweredon guest instance

```
- name: Remove previous nightly build
  delegate_to: localhost
  # become: false
  vmware_guest:
    validate_certs: false
    folder: "/path/on/disk"
    hostname: "{{ vsphere_host }}"
    username: "{{ ansible_vmware_username }}"
    password: "{{ ansible_vmware_password }}"
    datacenter: "Center"
    name: "{{ target_vm }}"
    state: absent
  register: newvm
  tags:
    - vm_build
```

##### EXPECTED RESULTS
the vm gets removed

##### ACTUAL RESULTS

```
TASK [vmware_rebuild_host : Remove previous nightly template] *************************************************************************************************************************************************************
task path: /Users/redacted/repos/ansible-repo/roles/vmware_rebuild_host/tasks/main.yml:22
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: redacted
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/redacted/.ansible/tmp/ansible-tmp-1498146094.09-198727545541449 `" && echo ansible-tmp-1498146094.09-198727545541449="` echo /Users/redacted/.ansible/tmp/ansible-tmp-1498146094.09-198727545541449 `" ) && sleep 0'
<localhost> PUT /var/folders/d9/7d_sb4mj1bz1jywsy8rrpj61n4xnb5/T/tmpnFTWWU TO /Users/redacted/.ansible/tmp/ansible-tmp-1498146094.09-198727545541449/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/redacted/.ansible/tmp/ansible-tmp-1498146094.09-198727545541449/ /Users/redacted/.ansible/tmp/ansible-tmp-1498146094.09-198727545541449/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/local/opt/python/bin/python2.7 /Users/redacted/.ansible/tmp/ansible-tmp-1498146094.09-198727545541449/vmware_guest.py; rm -rf "/Users/redacted/.ansible/tmp/ansible-tmp-1498146094.09-198727545541449/" > /dev/null 2>&1 && sleep 0'
fatal: [testplay -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "redacted", 
            "disk": [], 
            "esxi_hostname": null, 
            "folder": "/vm/path/on/disk", 
            "force": false, 
            "guest_id": null, 
            "hardware": {}, 
            "hostname": "redacted", 
            "is_template": false, 
            "name": "redacted", 
            "name_match": "first", 
            "networks": [], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": null, 
            "state": "absent", 
            "template_src": null, 
            "username": "redacted", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "The attempted operation cannot be performed in the current state (Powered on)."
}

```
