### ISSUE TITLE
yum module and redhat fail to register even with rpm local install

### ISSUE THREAD

**Issue by gregbkr** [ansible/ansible#26035]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

yum

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /home/rc/efg/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Running on Ubuntu 16.04
Targets are redhat 7

##### SUMMARY

When using yum to install any local rpm package, I get an error that `This system is not registered with RHN Classic`. 

##### STEPS TO REPRODUCE

This fails:
```yaml
- name: get logstash rpm package
  get_url:
    url: "https://artifacts.elastic.co/downloads/logstash/logstash-5.4.1.rpm"
    dest: "/tmp/logstash-5.4.1.rpm"
    validate_certs: no

- name: installing logstash package
  yum:
    name: "/tmp/logstash-5.4.1.rpm"
    state: present
```

This works, but ugly:
```yaml
- name: Install logstash rpm
  command: "rpm -U /tmp/logstash-5.4.1.rpm"
  ignore_errors: yes
```

##### EXPECTED RESULTS

I wish yum could manage my local package.

##### ACTUAL RESULTS

Error message with yum module:
```
TASK [logstash : installing logstash package] ******************************************************************************
fatal: [myserver]: FAILED! => {"changed": true, "failed": true, "msg": "Server error attempting a GET to https://subscription.rhn.redhat.com:443/rhsm/ returned status 404\nThis system is not registered with RHN Classic or RHN Satellite.\nYou can use rhn_register to register.\nRHN Satellite or RHN Classic support will be disabled.\nhttps://myserver/pulp/repos/myrepo/Production/CCV_RHEL_6_EFG/custom/EFG_Thirdparty/RHEL6_Thirdparty_repository/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - \"The requested URL returned error: 503\"\nTrying other mirror.\nhttps://myserver/pulp/repos/myrepo/Production/CCV_RHEL_6_EFG/custom/VMware_Tools_ESX/VMware_Tools_RHEL6/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - \"The requested URL returned error: 503\"\nTrying other mirror.\nhttp://packages.elastic.co/logstash/5.4.0/centos/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - \"The requested URL returned error: 404 Not Found\"\nTrying other mirror.\nError: Cannot retrieve repository metadata (repomd.xml) for repository: logstash. Please verify its path and try again\n Warning: Due to potential bad behaviour with rhnplugin and certificates, used slower repoquery calls instead of Yum API.", "rc": 1, "results": ["Loaded plugins: package_upload, product-id, rhnplugin, security, subscription-\n              : manager\nSetting up Install Process\nExamining /tmp/logstash-5.4.1.rpm: 1:logstash-5.4.1-1.noarch\nMarking /tmp/logstash-5.4.1.rpm to be installed\n"]}
```

Thank you for your help!
Greg.
