### ISSUE TITLE
disk_size does not work for boot disk

### ISSUE THREAD

**Issue by hentismith** [ansible/ansible#26037]
Tried to test again latest release in schroot, but got other errors, so was not able to test. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module/gce

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/henti/src/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
[defaults]
hostfile = inventory.d
vault_password_file = scripts/get_vault_password.sh
jinja2_extensions = jinja2.ext.do
log_path=~/logs/ansible.log
ansible_managed = Ansible managed
roles_path = ./roles:./ext_repos/ext-ansible/roles
inventory_ignore_extensions = gce.ini
```
##### OS / ENVIRONMENT
```Linux henti 4.4.0-78-generic #99-Ubuntu SMP Thu Apr 27 15:29:09 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

##### SUMMARY
Using the example on http://docs.ansible.com/ansible/gce_module.html I'm trying to create a instance with a 50GB boot disk. Using gcloud command it works fine, but using the gce module it just creates the default 10GB disk. 

Anisble gce module uses secrets.py to authenticate.

##### STEPS TO REPRODUCE
create playbook gce-test.yml 

```
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: instance
      gce:
        instance_names: my-test-instance1
        zone: us-central1-a
        machine_type: n1-standard-1
        image: debian-8
        state: present
        disk_size: 50
```
Run ansible. 
```ansible-playbook gce-test.yml```

##### EXPECTED RESULTS
```
NAME               ZONE           SIZE_GB  TYPE         STATUS
my-test-instance1  us-central1-a  50       pd-standard  READY
```

##### ACTUAL RESULTS
```
NAME               ZONE           SIZE_GB  TYPE         STATUS
my-test-instance1  us-central1-a  10       pd-standard  READY
```

**Comment by ansibot** [comment]
cc @erjohnso
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @supertom
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mrjoshuap** [comment]
I can confirm this issue is still present.  I too am running into this same issue.  In the short term, I've been performing a gcloud command immediately after the gce module runs to grow the disk -- which works -- however, specifying the disk_size has no apparent impact as I would have expected.

I'm using environment variables to configure GCE modules.

```
ansible 2.3.1.0
  config file = /Users/jpreston/Desktop/DeskDrawer/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

**Comment by erjohnso** [comment]
Thanks for filing this @henti and confirming @mrjoshuap. Sorry it's taken so long to take a look.

I know it's not well documented, and this module was written back when you couldn't create a disk and instance in the same API call. But, if you add the `persistent_boot_disk` param, it works for me.

```
- name: Create instance(s)                                                         
  hosts: localhost                                                                 
  connection: local                                                                
  gather_facts: no                                                                 
                                                                                   
  tasks:                                                                           
    - name: instance                                                               
      gce:                                                                         
        project_id: graphite-demos                                                 
        credentials_file: /home/erjohnso/ansible-dev.json                          
        service_account_email: ansible-dev@graphite-demos.iam.gserviceaccount.com
        instance_names: my-test-instance1                                          
        zone: us-central1-a                                                        
        machine_type: n1-standard-1                                                
        image: debian-8                                                            
        state: present                                                             
        disk_size: 50                                                              
        persistent_boot_disk: True                                                 
```
