### ISSUE TITLE
yum and apt break with included playbooks

### ISSUE THREAD

**Issue by tonk** [ansible/ansible#2607]
Running the Ansible development version I do have a (stripped down) playbook like this:

file: `test.yml`

```

---
- hosts: all
  tasks:
      - name: install packages for RedHat
        yum: pkg=${item} state=present
        with_items:
            - zsh
        when_string: ${ansible_os_family} == "RedHat"

      - name: install packages for Debian
        apt: pkg=${item} state=present
        with_items:
            - zsh
        when_string: ${ansible_os_family} == "Debian"
```

And a second one, that includes the above playbook.

file: `breaks.yml`

```

---
- include: test.yml
```

When I run: `ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -vvv test.yml`
everythings works fine.

But when I run: `ANSIBLE_KEEP_REMOTE_FILES=1 ansible-playbook -vvv breaks.yml`
things break with:

```
failed: [master] => (item=zsh) => {"changed": false, "failed": true, "item": "zsh", "rc": 0, results": []}
msg: No Package matching '' found available, installed or updated
```

When I look into the files `ansible` generates, the variable `MODULE_ARGS` isn't filled correctly.

```
MODULE_ARGS = """pkg= state=present"""
```

I have been searching, but I cannot find where this variable is filled.
