### ISSUE TITLE
win_owner cannot find domain user

### ISSUE THREAD

**Issue by brainsam** [ansible/ansible#26083]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_owner

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/ansible/ansible-jenkins/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT
ansible host environment:
```
uname -a
Linux SBT-OAINR-017.ca.sbrf.ru 3.10.0-514.16.1.el7.x86_64 #1 SMP Fri Mar 10 13:12:32 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
```
agent:
Windows Server 2012R2

##### SUMMARY
win_owner can't find domain user at all. Local accounts works. I tried to run win_owner.ps1 function UserSearch on windows machine and it returns actual SID

##### STEPS TO REPRODUCE

```yaml
- hosts: slavewintest
  vars:
    ansible_user: Administrator
    ansible_connection: winrm
  tasks:
  - name: change owner
    win_owner:
      path: C:\jenkins_slave
      user: ALPHA\test
```
##### EXPECTED RESULTS
changed: [slavewinest]

##### ACTUAL RESULTS
fatal: [slavewintest]: FAILED! => {"changed": false, "failed": true, "msg": "ALPHA\\test is not a valid user or group on the host machine or domain"}
        to retry, use: --limit @/home/ansible/ansible-test/tasks.retry

```
ansible-playbook -i hosts tasks.yml -k
```
