### ISSUE TITLE
os_keystone_domain fails to work with identity v3 API when cloud options is not presented

### ISSUE THREAD

**Issue by bluesalt** [ansible/ansible#26092]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

* `modules/cloud/openstack/os_keystone_domain.py`
* `module_utils/openstack.py`

And I believe most OpenStack modules which need to call domain API are affected too.

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /root/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

Content of `ansible.cfg` file
```
[defaults]
retry_files_enabled = False
```
##### OS / ENVIRONMENT

* Control Machine: `CentOS Linux release 7.2.1511 (Core)`
* Managed Machines:  `CentOS Linux release 7.3.1611 (Core)`

##### SUMMARY

Most of time, the information of managed OpenStack clouds is presented by the  [`cloud`](https://github.com/ansible/ansible/blob/v2.3.1.0-1/lib/ansible/module_utils/openstack.py#L76) options which is driven by `os-client-config`.  This option will be used by [`shade`](https://github.com/openstack-infra/shade). 
The `cloud` option is not needed when [`auth`](https://github.com/ansible/ansible/blob/v2.3.1.0-1/lib/ansible/module_utils/openstack.py#L78) is provided.  In that case, `os-client-config` will provides a default `cloud` option based on the `auth` option.  The default `cloud` option will use identity 2.0 and there is no way to inject identity version in the `auth` option at the moment. 

When identity v2.0 is indicated, [`shade`](https://github.com/openstack-infra/shade/blob/master/shade/_tasks.py#L177) will use 2.0 keystone client who knows nothing about the domain. 

##### STEPS TO REPRODUCE

`playbook.yml`
```yaml
- hosts: all
  vars_files:
    - vars/main.yml

  tasks:
    - name: create domain for jdomain
      os_keystone_domain:
        name: jdomain
        state: present
        region_name: RegionOne
        auth: "{{ keystone_admin_auth }}"
        endpoint_type: admin
      delegate_to: localhost
      run_once: yes
```

`vars/main.yml`
```
---
keystone_admin_auth:
  auth_url: http://{{ keystone_host }}:35357
  username: admin
  password: "{{ keystone_admin_token }}"
  project_name: admin
  project_domain_name: Default
  user_domain_name: Default
```
It should be noted that it still fails even the `auth_url` is changed to `http://{{ keystone_host }}:35357/v3` or `http://{{ keystone_host }}:35357/v3/`.

##### EXPECTED RESULTS

The new domain was created.

##### ACTUAL RESULTS

The task failed to create a new domain.

```
fatal: [keystone01 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to list domains (Inner Exception: Unknown Attribute: domains)"}
```

**Comment by bluesalt** [comment]
I have sent a [PR](https://github.com/ansible/ansible/pull/26103) to fix the problem.

**Comment by ansibot** [comment]
cc @emonty @shrews @juliakreger @j2sol @rcarrillocruz @thingee
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bluesalt** [comment]
Create new [PR](https://github.com/ansible/ansible/pull/26103) because [former one](https://github.com/ansible/ansible/pull/26094) has a bug which will override the option specified in `os-client-config`.

**Comment by ansibot** [comment]
cc @dagnello
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dharmabumstead
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bluesalt** [comment]
@alikins is there any further plan to review this issue ?

**Comment by markgoddard** [comment]
I was able to work around this issue by specifying the environment variable `OS_IDENTITY_API_VERSION=3`:

```
- hosts: all
  vars_files:
    - vars/main.yml

  tasks:
    - name: create domain for jdomain
      os_keystone_domain:
        name: jdomain
        state: present
        region_name: RegionOne
        auth: "{{ keystone_admin_auth }}"
        endpoint_type: admin
      delegate_to: localhost
      run_once: yes
      environment:
        OS_IDENTITY_API_VERSION: 3
```
