### ISSUE TITLE
Unable to create a 2-disks vm on different datastores

### ISSUE THREAD

**Issue by angystardust** [ansible/ansible#26095]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloud/vmware_guest.py

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/infra/library', u'/usr/lib/python2.7/site-packages/ara/plugins/modules']
  python version = 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
N.A.

##### OS / ENVIRONMENT
Red Hat Enterprise Linux 7.3
VMware Vsphere 6.0

##### SUMMARY
When you try to create a 2-disks vm with each disk on a different datastore, both are created on the datastore specified as the first one.

##### STEPS TO REPRODUCE
Create a playbook with the below example and specify 2 different datastores as the _datastore_ and the _disk2_datastore_ variables.

```yaml
- name: Create VM from template
  vmware_guest:
    name: "{{ inventory_hostname }}"

    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: False

    esxi_hostname: "{{ esxhost }}"
    datacenter: "{{ datacenter }}"

    template: '{{ os_family}}{{ os_vers }}{{os_arch}}-template'
    folder: "{{ folder | default('/vm') }}"

    hardware:
      num_cpus: "{{ vm_cpus }}"
      memory_mb: "{{ vm_memory * 1024 | default(1024) }}"

    disk:
      - size_gb: "{{ disk_size | default(10) }}"
        type: thin
        datastore: "{{ datastore }}"
        autoselect_datastore: False
      - size_gb: "{{ disk2_size | default(10) }}"
        type: thin
        datastore: "{{ disk2_datastore }}"
        autoselect_datastore: False

    networks:
      - name: "{{ vlan }}"
        ip: "{{ primary_ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
      - name: "{{ nic2_vlan }}"
        ip: "{{ nic2_ip }}"
        netmask: "{{ nic2_netmask }}"

    customization:
      domain: "{{ domain }}"
      dns_servers: "{{ dns_servers }}"

    annotation: "Created with Ansible"
    wait_for_ip_address: true

  register: newvm
  delegate_to: localhost

```

##### EXPECTED RESULTS
The new vm is created with the each disk on the his own datastore

##### ACTUAL RESULTS
The new vm is created with the both disks on the same datastore

```

```
