### ISSUE TITLE
os_server ignores v4-fixed-ip argument in nics

### ISSUE THREAD

**Issue by cyrilchapon** [ansible/ansible#26108]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
os_server

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### OS / ENVIRONMENT
Debian 8

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - name: Create OpenStack instance
      os_server:
        state: present
        auth:
          auth_url: <hidden>
          username: <hidden>
          password: <hidden>
          project_name: <hidden>
        name: myinstance
        image: Debian 8
        key_name: root-gateway
        timeout: 200
        flavor: s1-8
        auto_ip: false
        nics: "net-id=0572161e-f71e-47d8-81a4-d1d7558e5ab0,v4-fixed-ip=192.168.0.100"
```

##### EXPECTED RESULTS
Ansible to accept "v4-fixed-ip" arg

##### ACTUAL RESULTS
Instance is created under network, but not with fixed-ip

**Comment by ansibot** [comment]
cc @emonty @shrews @juliakreger @j2sol @rcarrillocruz @thingee
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Shrews** [comment]
Could you try using 'fixed_ip' instead of 'v4-fixed-ip' and see if that works for you?

**Comment by ansibot** [comment]
cc @dagnello
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by agorbachev** [comment]
`fixed_ip` did not help me.
```yml
  - name: Run VSC VM instance
    local_action:
      module: os_server
      auth: "{{ os_auth }}"
      name: "{{ inventory_hostname }}"
      flavor: "{{ vsc_flavor }}"
      image: "{{ vsc_image }}"
      nics:
        - "net-id={{vsc_mgmt_network_id}},fixed_ip={{mgmt_ip}}"
        - "port-id={{ _vsc_trunk_port.port.id }}"
      security_groups: "{{ vsc_mgmt_security_group }}"
```
