### ISSUE TITLE
ovirt_disks module doesn't export disks to openstack glance storage

### ISSUE THREAD

**Issue by lukas-bednar** [ansible/ansible#26129]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- ovirt_disks

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/lbednar/work/ansible-playbooks/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

oVirt (4.1+) supports exporting disks of templates separately into OpenStack Glance storage.
Nowadays **ovirt_disks** module doesn't support this option.
In my opinion it is nice feature to have there.

##### STEPS TO REPRODUCE

```yaml
- ovirt_disks:
    name: mytemplate_disk
    status: exported
    export_domain: myglance_repository
    exclusive: yes
```

##### EXPECTED RESULTS

Given disk will be exported to OpenStack Glance.

##### ACTUAL RESULTS

Currently it is not supported.

```
N/A
```
