### ISSUE TITLE
eos_config ignores config lines within a hierarchy from a source config file

### ISSUE THREAD

**Issue by petereh** [ansible/ansible#26136]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION

```
TEST WITH **ip access-l** works .

"updates": [
        "no ip access-list ABCD", 
        "ip access-l ABCD", 
        "remark ##MANAGED BY CAPIRCA NO MANUAL CHANGES ALLOWED##
        "remark stats-per-entry", 
        "statistics per-entry", 

```

TESTWITH THE FULL COMMAND  IN THE CONFIG FILE i.e ip **access-list** does not work :+1: 
fatal: [dub-dc-lb05-ta-1]: FAILED! => {
    "changed": false, 
    "commands": [
        "no ip access-list ABCD", 
        "remark ##MANAGED BY CAPIRCA NO MANUAL CHANGES ALLOWED##,
        "remark stats-per-entry", 
        "statistics per-entry", 

##### OS / ENVIRONMENT
Debian 3.x

##### SUMMARY
When i have config in a file that i need to push to an arista switch . anytime there is hierarchy , for example configuring an interface  or configuring an access-list , ansible ignores some lines , in all my tests it ignores the second line in the config file , as a result this causes ansible to fail since the switch will report an error when you try to configure an extended access-list entry in global mode . when i shorten the second line in the config file  from "ip access-list" to "ip access-l" , ansible is able to read that line in the config file , so it seems like the logic to read and parse hierarchy .

##### STEPS TO REPRODUCE
CFG FILE 
======
no ip access-list ABCD

ip access-l ABCD
 remark ##MANAGED BY CAPIRCA NO MAUAL CHANGES ALLOWED##

 remark stats-per-entry
 statistics per-entry

```
ANSIBLE PLAYBOOK
==============

---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: push configs
      eos_config:
         username: xxxxxxx
         password: xxxxxxxx
         host: "{{ inventory_hostname }}"
         src:  "{{ src_file }}"
         transport: cli
      register: output
```

##### EXPECTED RESULTS
When you run with this config file below , ansible job will fail . 

no ip access-list ABCD

ip **access-list** ABCD
 remark ##MANAGED BY CAPIRCA NO MAUAL CHANGES ALLOWED##

 remark stats-per-entry
 statistics per-entry

however when you run with this config file below , ansible will pass.

no ip access-list ABCD

ip **access-l**  ABCD
 remark ##MANAGED BY CAPIRCA NO MAUAL CHANGES ALLOWED##

 remark stats-per-entry
 statistics per-entry

##### ACTUAL RESULTS

```
pasted excerpt above 
```

**Comment by ansibot** [comment]
cc @privateip @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
@petereh I think there might be a little confusion on how to properly use `eos_config` here.   The file specified in by the `src` argument must be a validly formatted EOS configuration file equivilent to what you would see from `show running-config`.   In this case, the value of `src` should look like something like this:

```
ip access-list ABCD
   10 remark ##MANAGED BY CAPRICA NO MANUAL CHANGES ALLOWED##
   20 remark stats-per-entry
   30 permit ip any any 
```
Complete with proper indents (3 spaces in the case of EOS).  

In order to remove the ACL before programming it into the device, use the `before` argument:

```before: no ip access-list ABCD```

So the final playbook entry would be:

```
name: configure eos acl
eos_config:
  src: "{{ acl.cfg }}"
  provider: "{{ cli }}"
  before: no ip access-list ABCD
```
And the contents of `acl.cfg` would be as above.

notabug
