### ISSUE TITLE
template with default empty string as filter returns None.

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#26141]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template module, jinja 2.8

##### ANSIBLE VERSION

```
  ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
no changes

##### OS / ENVIRONMENT
Debian stretch

##### SUMMARY
`default('')` returns None instead of empty string

##### STEPS TO REPRODUCE
```
# test_template.yml.j2

KEY:  {{ undefined | default('') }}
```

```yaml
# testbook.yml

- hosts: localhost
  tasks:
      - name: template bug
        template:
            src: test_template.yml.j2
            dest: ./templated.yml
```

```shell
$ ansible-playbook testbook.yml 

PLAY [localhost] ***************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [template bug] ************************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```

##### EXPECTED RESULTS
```shell
$ cat templated.yml 
KEY:  ''
$ python3
>>> import yaml
>>> with open('templated.yml') as f:
...   print(yaml.load(f))
... 
{'KEY': ''}
```

##### ACTUAL RESULTS

```shell
$ cat templated.yml
KEY:  
$ python3
>>> import yaml
>>> with open('templated.yml') as f:
...   print(yaml.load(f))
... 
{'KEY': None}
```

----

changing `default('')` to `default("''")` is a workaround for this
