### ISSUE TITLE
nxos_bgp_af - client_to_client property is not idempotent

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#26159]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_bgp_af

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 6bed831f8c) last updated 2017/06/27 15:24:19 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

- Ansible Server : Ubuntu 14.04
- Device: Nexus9000 C9508  running 7.0(3)I6(1)

##### SUMMARY

The property client_to_client is not idempotent. The same playbook applied the second time reports failed.

##### STEPS TO REPRODUCE

```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  user_ssl: no

---
- name: NXOS Sample Playbook
  hosts: nxos
  connection: local
  gather_facts: no

  tasks:

  - name: Ensure BGP Is Enabled
    nxos_feature:
      feature: bgp
      state: enabled
      provider: "{{ cli }}"


  - name: "Enable feature nv overlay"
    nxos_feature:
      feature: nv overlay
      state: enabled
      provider: "{{ cli }}"

  - name: "Enable nv overlay evpn"
    nxos_config:
      lines:
        - nv overlay evpn
      provider: "{{ cli }}"
    ignore_errors: yes

  - name: "Configure BGP_AF non defaults"
    nxos_bgp_af: &configure_non_default
      asn: 65535
      vrf: TESTING
      afi: ipv4
      safi: unicast
      advertise_l2vpn_evpn: true
      additional_paths_install: true
      additional_paths_receive: true
      additional_paths_selection: RouteMap
      additional_paths_send: true
      client_to_client: false
      dampen_igp_metric: 200
      dampening_half_time: 1
      dampening_max_suppress_time: 4
      dampening_reuse_time: 2
      dampening_suppress_time: 3
      default_information_originate: true
      default_metric: 50
      distance_ebgp: 30
      distance_ibgp: 60
      distance_local: 90
      maximum_paths: 9
      maximum_paths_ibgp: 9
      next_hop_route_map: RouteMap
      suppress_inactive: true
      table_map: RouteMap
      table_map_filter: true
      state: present
      provider: "{{ cli }}"
```

##### EXPECTED RESULTS

Expected playbook to pass a second time

##### ACTUAL RESULTS

```
PLAY [NXOS Sample Playbook] *************************************************************************************************************************************************************************************************************************************

TASK [Ensure BGP Is Enabled] ************************************************************************************************************************************************************************************************************************************
changed: [nxxxx.cisco.com]

TASK [Enable feature nv overlay] ********************************************************************************************************************************************************************************************************************************
ok: [nxxxx.cisco.com]

TASK [Enable nv overlay evpn] ***********************************************************************************************************************************************************************************************************************************
changed: [nxxxx.cisco.com]

TASK [Configure BGP_AF non defaults] ****************************************************************************************************************************************************************************************************************************
 [WARNING]: The BGP process 65535 didn't exist but the task just created it.

changed: [nxxxx.cisco.com]

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************
nxxxx.cisco.com          : ok=4    changed=3    unreachable=0    failed=0   

xxxxxxxxxxxx:~/agents-ci/ansible# ansible-playbook -i ~/hosts playbook/bgp_af.yaml 

PLAY [NXOS Sample Playbook] *************************************************************************************************************************************************************************************************************************************

TASK [Ensure BGP Is Enabled] ************************************************************************************************************************************************************************************************************************************
ok: [nxxxx.cisco.com]

TASK [Enable feature nv overlay] ********************************************************************************************************************************************************************************************************************************
ok: [nxxxx.cisco.com]

TASK [Enable nv overlay evpn] ***********************************************************************************************************************************************************************************************************************************
ok: [nxxxx.cisco.com]

TASK [Configure BGP_AF non defaults] ****************************************************************************************************************************************************************************************************************************
fatal: [nxxxx.cisco.com]: FAILED! => {"changed": false, "failed": true, "msg": "no client-to-client reflection\r\r\n                                  ^\r\n% Invalid command at '^' marker.\r\n\rnxxxx(config-router-vrf)# "}
	to retry, use: --limit @/root/agents-ci/ansible/playbook/bgp_af.retry

PLAY RECAP ******************************************************************************************************************************************************************************************************************************************************
nxxxx.cisco.com          : ok=3    changed=0    unreachable=0    failed=1
```
