### ISSUE TITLE
win_chocolatey exit codes are note handled

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#26165]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
```
2.4.0
```

##### SUMMARY
Several chocolatey packages exit with the installer's exit code, such as 3010 indicating a required restart.
There's currently no way to pick this up in win_chocolatey, without elaborate failed_when/register patterns.

##### STEPS TO REPRODUCE
The following playbook consistently produces an 3010 exit code (its super-big and slow so brace yerself)
```
- name: Install vs2015 community
  win_chocolatey:
    name: visualstudio2015community
    timeout: 5400
    version: "2015.03.02"
```
##### EXPECTED RESULTS
An allowed_exitcode parameter would be nice

##### ACTUAL RESULTS
```
fatal: [wdm-0102007]: FAILED! => {"changed": true, "failed": true, "rc": 3010}
```
