### ISSUE TITLE
ovirt_disks: Can't download qcow2 disk

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#26177]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ovirt_disks

##### ANSIBLE VERSION

```
2.3.0
```

##### CONFIGURATION

No.

##### OS / ENVIRONMENT

No.

##### SUMMARY

Downloading a qcow2 disk via `ovirt_disks` module fails on `IncompleteRead` exception.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  vars_files:
    - ../vars.yml

  tasks:
  - name: Obtain SSO token
    ovirt_auth:
      url: "{{ url }}"
      username: "{{ username }}"
      password: "{{ password }}"
      insecure: "{{ insecure }}"

  - name: Download disk
    ovirt_disks:
      auth: "{{ ovirt_auth }}"
      id: 46c70e50-6355-4494-8562-88ede29b3882
      download_image_path: /home/omachace/mydisk.qcow2
```

##### EXPECTED RESULTS

The disk with id `46c70e50-6355-4494-8562-88ede29b3882` should be downloaded .

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_HfXUsF/ansible_module_ovirt_disks.py", line 585, in main
    downloaded = download_disk_image(connection, module)
  File "/tmp/ansible_HfXUsF/ansible_module_ovirt_disks.py", line 363, in download_disk_image
    transfer_func=_transfer,
  File "/tmp/ansible_HfXUsF/ansible_module_ovirt_disks.py", line 299, in transfer
    transfer.signed_ticket
  File "/tmp/ansible_HfXUsF/ansible_module_ovirt_disks.py", line 354, in _transfer
    mydisk.write(r.read())
  File "/usr/lib64/python2.7/httplib.py", line 581, in read
    s = self._safe_read(self.length)
  File "/usr/lib64/python2.7/httplib.py", line 690, in _safe_read
    raise IncompleteRead(''.join(s), amt)
IncompleteRead: IncompleteRead(4899328 bytes read, 15872 more expected)

fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "auth": {
                "ca_file": null, 
                "compress": true, 
                "insecure": true, 
                "kerberos": false, 
                "timeout": 0, 
                "token": "sI7IYBKL48QJrrdxXuZKrHo5230Tat7pJI3tOrPXT1aJNAaqu1vz5cNKejD_AWETpaBMXJ0KPcENR5VMeGbHnQ", 
                "url": "https://ondra.local:8443/ovirt-engine/api"
            }, 
            "bootable": null, 
            "download_image_path": "/home/omachace/mydisk.qcow2", 
            "fetch_nested": false, 
            "force": false, 
            "format": "cow", 
            "id": "46c70e50-6355-4494-8562-88ede29b3882", 
            "interface": null, 
            "logical_unit": null, 
            "name": null, 
            "nested_attributes": [], 
            "openstack_volume_type": null, 
            "poll_interval": 3, 
            "profile": null, 
            "shareable": null, 
            "size": null, 
            "sparsify": null, 
            "state": "present", 
            "storage_domain": null, 
            "storage_domains": null, 
            "timeout": 180, 
            "upload_image_path": null, 
            "vm_id": null, 
            "vm_name": null, 
            "wait": true
        }
    }, 
    "msg": "IncompleteRead(4899328 bytes read, 15872 more expected)"
}
```
