### ISSUE TITLE
Cannot default an undefined variable to another defined variable inside a dictionary

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#26182]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

default filter

##### ANSIBLE VERSION

**Both latest stable & unstable** versions:
```
ansible 2.3.2.0 (detached HEAD 7424e1c417) last updated 2017/06/28 14:37:25 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/actionmystique/Ansible/git-yang-networkop/ansible-101/library']
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

ansible 2.4.0 (devel a5b905c941) last updated 2017/06/28 15:03:00 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/actionmystique/Ansible/git-yang-networkop/ansible-101/library']
  ansible python module location = /home/actionmystique/src/Ansible/git-ansible/lib/ansible
  executable location = /home/actionmystique/src/Ansible/git-ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```
##### CONFIGURATION

inventory   = ./hosts
library        = /home/actionmystique/Ansible/git-yang-networkop/ansible-101/library
forks = 1000
gathering = explicit
gather_timeout = 30
roles_path = /home/actionmystique/Ansible/Roles/roles
private_role_vars = yes
hash_behaviour = merge
log_path = /var/log/ansible.log
retry_files_enabled = False
show_custom_stats = True
timeout = 60
pipelining = True
connect_timeout = 60
connect_retries = 30
connect_interval = 1

##### OS / ENVIRONMENT
- host: **Ubuntu 17.04 4.10**
- target: **IOS-XEv 16.5.1**

##### SUMMARY

The generic {{ undefined_variable | default(defined_variable) }} does not work inside a dictionary, although it follows what is described in this [post](https://github.com/ansible/ansible/issues/9867#issuecomment-67689161) from @bcoca in a slightly different context: dictionary vs inventory file.
Maybe the expected feature is not defined yet, in which case I can change this bug report into a feature request.

##### STEPS TO REPRODUCE

Structure passed as "**provider**": connections.ssh (the arrow is absent from the original dictionary)

```
connections
...
        ssh:
          transport: cli 
--------->host: "{{ ansible_host | default(inventory_hostname) }}"
          # ansible_port
          port: 22
          # ansible_user
          username: admin
          # ansible_ssh_pass
          password: xxxxxxxxxxx
          authorize: yes
          # enable_secret_password
          auth_pass: xxxxxxxxxxx
          # private_key_file
          ssh_keyfile: "~/.ssh/id_rsa"
          version: 2
          timeout: 10
```

**Role**: ios_push_config:

```
- include_vars: "../defaults/{{ os_family }}/connections.yml"
  when: (connections is undefined)
...
- name: Pushing adapted config to remote node
  ios_config:
        provider: "{{ connections.ssh }}"
        src: "{{ role_path }}/templates/{{ inventory_hostname }}/startup-config.txt"
        save: yes
  register: result
```

**Playbook**:

```
- name: Pushing IOS/IOSv/IOSv-L2/IOS-XE/IOS-XEv configs
  hosts:
    - ios
    - iosv
    - iosv_l2
    - ios_xe
    - ios_xev
  gather_facts: no
  roles:
    - ios_push_config
```

##### EXPECTED RESULTS

inventory_hostname should be used instead of the undefined ansible_host in "connections.yml" & startup configurations should be pushed to the target nodes.

##### ACTUAL RESULTS: Log

```
...
/ TASK [ios_push_config : Pushing adapted config to remote \
\ node]                                                    /
 ----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/actionmystique/Ansible/Roles/roles/ios_push_config/tasks/main.yml:79
fatal: [XEv_Spine_11]: FAILED! => {
    "failed": true, 
    "msg": "the field 'connection' has an invalid value, which appears to include a variable that is undefined.The error was: {u'protocol': u'ssh', u'xeapi': {u'username': u'admin', u'authorize': True, u'auth_pass': u'Cisco2016$', u'host': u'{{ ansible_host }}', u'use_ssl': False, u'password': u'Cisco2016$', u'port': 80, u'transport': u'xeapi'}, u'compute': u'local', u'target': u'cisco', u'ssh': {u'username': u'admin', u'authorize': True, u'ssh_keyfile': u'~/.ssh/id_rsa', u'auth_pass': u'Cisco2016$', u'host': u'{{ ansible_host | default(inventory_hostname) }', u'version': 2, u'timeout': 60, u'password': u'Cisco2016$', u'port': 22, u'transport': u'cli'}}: 'ansible_host' is undefined\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: {u'protocol': u'ssh', u'xeapi': {u'username': u'admin', u'authorize': True, u'auth_pass': u'Cisco2016$', u'host': u'{{ ansible_host }}', u'use_ssl': False, u'password': u'Cisco2016$', u'port': 80, u'transport': u'xeapi'}, u'compute': u'local', u'target': u'cisco', u'ssh': {u'username': u'admin', u'authorize': True, u'ssh_keyfile': u'~/.ssh/id_rsa', u'auth_pass': u'Cisco2016$', u'host': u'{{ ansible_host | default(inventory_hostname) }', u'version': 2, u'timeout': 60, u'password': u'Cisco2016$', u'port': 22, u'transport': u'cli'}}: 'ansible_host' is undefined"
}
...
```
##### ACTUAL RESULTS: Successful Manual SSH with inventory_hostname content
```
# ssh admin@XEv_Spine_11
CC
**************************************************************************
* IOSv is strictly limited to use for evaluation, demonstration and IOS  *
* education. IOSv is provided as-is and is not supported by Cisco's      *
* Technical Advisory Center. Any use or disclosure, in whole or in part, *
* of the IOSv Software or Documentation to any third party for any       *
* purposes is expressly prohibited except as otherwise authorized by     *
* Cisco in writing.                                                      *
**************************************************************************CC
XEv_Spine_11# #sh ver
Cisco IOS XE Software, Version 16.05.01b
Cisco IOS Software [Everest], Virtual XE Software (X86_64_LINUX_IOSD-UNIVERSALK9-M), Version 16.5.1b, RELEASE SOFTWARE (fc1)
...
```
