### ISSUE TITLE
nxos_interface module will not reset interfaces to theyre defaults. It returns the interface you are trying to default does not exist

### ISSUE THREAD

**Issue by tauputa** [ansible/ansible#26202]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
2.3.1.0
```

##### STEPS TO REPRODUCE

```yaml
  tasks:
   - name: "return interface to its default"
     nxos_interface:
       interface: Ethernet1/47
       state: default
       provider: "{{nexus_auth_provider}}"
```

##### EXPECTED RESULTS

Expect the interface to be set to its default. The interface exists because I can see it on the switch and update it with the interface module when using state: present

##### ACTUAL RESULTS

```
 "msg": "interface you are trying to default does not exist"
```
