### ISSUE TITLE
Filesystem module is not idempotent when applied to an imagefile

### ISSUE THREAD

**Issue by straight-shoota** [ansible/ansible#26265]
_From @straight-shoota on March 2, 2016 17:7_

##### Issue Type:
- Bug Report

##### COMPONENT NAME
filesystem

##### Ansible Version:

```
ansible 2.0.1.0
```
##### Ansible Configuration:

nothing special
##### Environment:

N/A
##### Summary:

I am trying to create a filesystem on a virtual imagefile using filesystem module. First run it worked and the filesystem was created. But in subsequent runs the play fails with `ValueError: invalid literal for int() with base 10: ''`. This issue might be caused by the filesystem module expecting a real block device instead of a imagefile.
##### Steps To Reproduce:

Run the following playbook twice:

```
- hosts: 127.0.0.1
  connection: local
  vars:
    imagefile: /tmp/image.img
    imagesize: 16M

  tasks:
    - name: Create dd image
      command: dd if=/dev/zero of={{ imagefile }} bs=1 seek={{ imagesize }} count=1
    - name: Create filesystem
      filesystem: "dev={{ imagefile }} resizefs=yes fstype=ext4"
```
##### Expected Results:

On the first run, I expect an imagefile with filesystem to be created. This is fine.
On subsequent runs, I expect the play to recognize the existing filesystem (and resize it, if `imagesize` has changed). The task should result in `ok` (or `changed`) but instead it fails.
##### Actual Results:

From the second run onwards (when filesystem is in place), the task fails with the error message:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1456916978.28-235253654676566/filesystem", line 2207, in <module>
    main()
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1456916978.28-235253654676566/filesystem", line 199, in main
    devsize_in_bytes = _get_dev_size(dev, module)
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1456916978.28-235253654676566/filesystem", line 71, in _get_dev_size
    return int(devsize_in_bytes)
ValueError: invalid literal for int() with base 10: ''

fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "filesystem"}, "parsed": false}
```

It should be possible to find a workaround and only apply the filesystem task if the filesystem does not exists (test if mounting fails) but I'd prefer a proper solution.

Originally posted as ansible/ansible#14746

_Copied from original issue: ansible/ansible-modules-extras#1773_

**Comment by straight-shoota** [comment]
_From @ansibot on August 4, 2016 20:20_



@abulimov ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by straight-shoota** [comment]
_From @ansibot on September 13, 2016 3:33_

@abulimov, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by straight-shoota** [comment]
_From @ansibot on October 6, 2016 18:8_

@abulimov, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by straight-shoota** [comment]
_From @ansibot on October 22, 2016 10:19_

@abulimov, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by straight-shoota** [comment]
_From @ansibot on November 6, 2016 10:54_

@abulimov, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by straight-shoota** [comment]
_From @ansibot on November 22, 2016 11:2_

@abulimov, ping. This issue is still waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by straight-shoota** [comment]
_From @ansibot on December 7, 2016 15:55_

This repository has been locked. All new issues and pull requests should be filed in https://github.com/ansible/ansible

Please read through the <a href="http://docs.ansible.com/ansible/dev_guide/repomerge.html#move-issues-and-prs-to-new-repo">repomerge</a> page in the dev guide. The guide contains links to tools which automatically move your issue or pull request to the ansible/ansible repo.

**Comment by ansibot** [comment]
@straight-shoota Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@straight-shoota Thanks for reporting this issue. 

You are directly using a file for filesystem module, which is not supported. As filesystem module is meant for block devices and not for a regular file.

But, you can still use it for your use case as follows: 

```yaml
---
- name: fs
  hosts: localhost
  vars:
    - imagefile: /tmp/sample.img
    - imagesize: 16M
  tasks:
    - name: create a file
      command: dd if=/dev/zero of="{{ imagefile }}" bs=1 seek="{{ imagesize }}" count=1

    - name: create a loop device
      command: losetup /dev/loop2 "{{imagefile}}"

    - name: format
      filesystem: dev=/dev/loop2 resizefs=yes fstype=ext4
```
