### ISSUE TITLE
nxos_bgp_neighbor - timers_keepalive, timers_holdtime, shutdown properties not working as expected

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#26260]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_bgp_neighbor
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 6bed831f8c) last updated 2017/06/27 15:24:19 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

- Ansible Server : Ubuntu 14.04
- Device: Nexus9000 C9508  running 7.0(3)I6(1)

##### SUMMARY

timers_keepalive, timers_holdtime, shutdown properties don't work as expected.

##### STEPS TO REPRODUCE

```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  user_ssl: no

---
- name: NXOS Sample Playbook
  hosts: nxos
  connection: local
  gather_facts: no

  tasks:

  - name: Ensure BGP Is Enabled
    nxos_feature:
      feature: bgp
      state: enabled
      provider: "{{ cli }}"

  - name: "Configure BGP neighbor"
    nxos_bgp_neighbor: &configure_non_default
      asn: 65535
      neighbor: 3.3.3.3
      description: "tested by ansible"
      connected_check: true
      capability_negotiation: true
      dynamic_capability: true
      ebgp_multihop: 2
      log_neighbor_changes: enable
      low_memory_exempt: true
      remote_as: 12.1
      remove_private_as: all
      shutdown: true
      suppress_4_byte_as: true
      timers_keepalive: 90
      timers_holdtime: 270
      update_source: loopback151
      state: present
      provider: "{{ cli }}"
```

##### EXPECTED RESULTS

The playbook should apply clean

##### ACTUAL RESULTS

```
PLAY [NXOS Sample Playbook] ***********************************************************************************************************************************************************************************************************************************

TASK [Ensure BGP Is Enabled] **********************************************************************************************************************************************************************************************************************************
ok: [nxxxx.cisco.com]

TASK [Configure BGP neighbor] *********************************************************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'timers-keepalive'
fatal: [nxxxx.cisco.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mwd6V4/ansible_module_nxos_bgp_neighbor.py\", line 508, in <module>\n    main()\n  File \"/tmp/ansible_mwd6V4/ansible_module_nxos_bgp_neighbor.py\", line 492, in main\n    state_present(module, existing, proposed, candidate)\n  File \"/tmp/ansible_mwd6V4/ansible_module_nxos_bgp_neighbor.py\", line 394, in state_present\n    proposed_commands['timers-keepalive'],\nKeyError: 'timers-keepalive'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```
