### ISSUE TITLE
(P2)nxos_bgp_neighbor - several properties not idempotent

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#26262]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_bgp_neighbor

##### ANSIBLE VERSION

```
 ansible 2.4.0 (devel 6bed831f8c) last updated 2017/06/27 15:24:19 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

- Ansible Server : Ubuntu 14.04
- Device: Nexus9000 C9508  running 7.0(3)I6(1)

##### SUMMARY

Several properties are not idempotent

##### STEPS TO REPRODUCE

```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  user_ssl: no

---
- name: NXOS Sample Playbook
  hosts: nxos
  connection: local
  gather_facts: no

  tasks:

  - name: Ensure BGP Is Enabled
    nxos_feature:
      feature: bgp
      state: enabled
      provider: "{{ cli }}"

  - name: "Configure BGP neighbor"
    nxos_bgp_neighbor: &configure_non_default
      asn: 65535
      neighbor: 3.3.3.3
      description: "tested by ansible"
      connected_check: true
      capability_negotiation: true
      dynamic_capability: true
      ebgp_multihop: 2
      log_neighbor_changes: enable
      low_memory_exempt: true
      remote_as: 12.1
      remove_private_as: all
      suppress_4_byte_as: true
      update_source: loopback151
      state: present
      provider: "{{ cli }}"
```

##### EXPECTED RESULTS

expected playbook to be ok the second time instead of 'changed'.

##### ACTUAL RESULTS

```
PLAY [NXOS Sample Playbook] ***********************************************************************************************************************************************************************************************************************************

TASK [Ensure BGP Is Enabled] **********************************************************************************************************************************************************************************************************************************
ok: [nxxxx-xxx.example.com]

TASK [Configure BGP neighbor] *********************************************************************************************************************************************************************************************************************************
changed: [nxxxx-xxx.example.com]

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************
nxxxx-xxx.example.com          : ok=2    changed=1    unreachable=0    failed=0
```
