### ISSUE TITLE
vmware_guest_snapshot should allow memory dump and quiese of FS

### ISSUE THREAD

**Issue by javierurien** [ansible/ansible#26270]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

vmware_guest_snapshot.py

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Ubuntu 16.04 64 bits

##### SUMMARY

currently snapshot operations call CreateSnapshot from pyvmomi (https://github.com/vmware/pyvmomi/blob/575ab56eb56f32f53c98f40b9b496c6219c161da/docs/vim/VirtualMachine.rst) with flags for memory dump and filesystem quiece in False. This leads to every snapshot of a VM be in a powered down state irregardless of the state of the VM when the snapshot is taken.
Having these flags in False makes for a really fast snapshot procedure, but I belive it is less usefull.

##### STEPS TO REPRODUCE

dummy_vm is powered on

```yaml
- name: Create snapshot
  vmware_guest_snapshot:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    name: dummy_vm
    state: present
    snapshot_name: snap1
    description: snap1_description
  delegate_to: localhost
```

##### EXPECTED RESULTS

restoring snapshot will result in dummy_vm in powered on state.

##### ACTUAL RESULTS

dummy_vm is restored in powered off state.

```

```
