### ISSUE TITLE
nxos_bgp_neighbor_af max_prefix* property issues.

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#26301]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_bgp_neighbor_af

##### NXOS VERSION
7.0(3)I5(3)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel d08ff86169) last updated 2017/06/30 13:58:00 (GMT -400)
  config file = None
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT
macOS

##### SUMMARY
According to the module documentation, only `max_prefix_limit` needs to be set to 'default' if the default behavior is desired.

Fails for both transports: `cli` and `nxapi`

Reference: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_bgp_neighbor_af.py#L39

##### STEPS TO REPRODUCE
The following steps use this playbook as a starting point
```yaml
  - name: "Configure BGP neighbor address-family defaults"
    nxos_bgp_neighbor_af: &configure_default
      asn: 65535
      vrf: 'blue'
      neighbor: '3.3.3.3'
      afi: ipv4
      safi: unicast
      max_prefix_limit: 'default'
      #max_prefix_interval: 'default'
      #max_prefix_threshold: 'default'
      #max_prefix_warning: 'false'
      state: present
      provider: "{{ cli }}"
```
1. Test result when only max_prefix_default is set to `default`
```shell
TASK [nxos_bgp_neighbor_af : Configure BGP neighbor address-family defaults] **************************************************************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "parameters are required together: ['max_prefix_limit', 'max_prefix_interval']"}
```

2. Test result when both max_prefix_limit and max_prefix_interval are set to `default`
```shell
TASK [nxos_bgp_neighbor_af : Configure BGP neighbor address-family defaults] **************************************************************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "parameters are required together: ['max_prefix_limit', 'max_prefix_warning']"}
```

3. Test result when both max_prefix_limit, max_prefix_interval and max_prefix_warning are set to `default`
```shell
TASK [nxos_bgp_neighbor_af : Configure BGP neighbor address-family defaults] **************************************************************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "parameters are required together: ['max_prefix_limit', 'max_prefix_threshold']"}
```
4. Test result when all max_prefix* properties are set to `default`.
```shell
TASK [nxos_bgp_neighbor_af : Configure BGP neighbor address-family defaults] **************************************************************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "maximum-prefix default default restart default\r\r\n                                                              ^\r\n% Invalid number at '^' marker.\r\n\revergreen-nx-1(config-router-vrf-neighbor-af)# "}
```
NOTE: This works properly when transport is `nxapi`.

```shell

```

**Comment by ansibot** [comment]
cc @jedelman8 @GGabriele @rahushen @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Qalthos** [comment]
@mikewiebe, does #26370 fix the issue?

**Comment by mikewiebe** [comment]
@Qalthos This does allow me to specify 'default' as an option to the command but then it tries to send the string 'default' to the device.

```
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1499713309.36-181272997708614/nxos_bgp_neighbor_af.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1499713309.36-181272997708614/" > /dev/null 2>&1 && sleep 0'
fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "clierror": "% Invalid number\n", 
    "code": "400", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "additional_paths_receive": "inherit", 
            "additional_paths_send": "inherit", 
            "advertise_map_exist": "default", 
            "advertise_map_non_exist": null, 
            "afi": "ipv4", 
            "allowas_in": false, 
            "allowas_in_max": "default", 
            "as_override": false, 
            "asn": "65535", 
            "default_originate": false, 
            "default_originate_route_map": "default", 
            "filter_list_in": "default", 
            "filter_list_out": "default", 
            "host": "n9k.example.com", 
            "max_prefix_interval": null, 
            "max_prefix_limit": "default", 
            "max_prefix_threshold": null, 
            "max_prefix_warning": null, 
            "neighbor": "3.3.3.3", 
            "next_hop_self": false, 
            "next_hop_third_party": true, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 80, 
            "prefix_list_in": "default", 
            "prefix_list_out": "default", 
            "provider": {
                "host": "n9k.example.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 80, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "route_map_in": "default", 
            "route_map_out": "default", 
            "route_reflector_client": false, 
            "safi": "unicast", 
            "send_community": "default", 
            "soft_reconfiguration_in": "inherit", 
            "soo": "default", 
            "ssh_keyfile": null, 
            "state": "present", 
            "suppress_inactive": false, 
            "timeout": 10, 
            "transport": "nxapi", 
            "unsuppress_map": "default", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true, 
            "vrf": "blue", 
            "weight": "default"
        }
    }, 
    "msg": "CLI execution error", 
    "output": [
        {
            "body": {}, 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "body": {}, 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "body": {}, 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "body": {}, 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "body": {}, 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "clierror": "% Invalid number\n", 
            "code": "400", 
            "msg": "CLI execution error"
        }
    ], 
    "url": "http://n9k.example.com:80/ins"
}
```

General question:  Does ansible by convention map the keyword 'default' to functionality in the module that puts that property into the default state?

Based on the module documentation I would have expected to be able to set only the `max_prefix_limit: 'default'` property and it put the property into the default state.  In this case that is 'no max_prefix_limit'

**Comment by Qalthos** [comment]
> Does ansible by convention map the keyword 'default' to functionality in the module that puts that property into the default state?

Not in my experience (outside of quite a few nxos modules), though it might be present elsewhere. I was really hoping this was something handled by nxos, as there are quite a few places where `'default'` is allowed to fall through unchanged, and I don't know what the proper values for each might be.

**Comment by Qalthos** [comment]
Ah, 'default' is handled by the module, and I found out how I screwed up to make it not work for `max_prefix_*`. Let me know how #26370 works for you now.

**Comment by mikewiebe** [comment]
I took #26370 for a test drive.  I can now specify `default` for `max_prefix_limit` but the module is no longer idempotent.  The same playbook with the `max_prefix_limit` property commented out is idempotent in `devel`. 

Here is the playbook I am using.
```yaml
  - name: "Configure BGP neighbor address-family defaults"
    nxos_bgp_neighbor_af: &configure_default
      asn: 65535
      vrf: 'blue'
      neighbor: '3.3.3.3'
      afi: ipv4
      safi: unicast
      additional_paths_receive: 'inherit'
      additional_paths_send: 'inherit'
      advertise_map_exist: 'default'
      # -----------------------------------------------
      # advertise_map_exist and advertise_map_non_exist
      # are mutually exclusive
      #advertise_map_non_exist: 'default'
      # -----------------------------------------------
      allowas_in: 'false'
      allowas_in_max: 'default'
      as_override: 'false'
      default_originate: 'false'
      default_originate_route_map: 'default'
      filter_list_in: 'default'
      filter_list_out: 'default'
      # ------------------------------------------
      # max_prefix* properities are off by default
      max_prefix_limit: 'default'
      #max_prefix_interval: 'default'
      #max_prefix_threshold: 'default'
      #max_prefix_warning: 'false'
      # ------------------------------------------
      next_hop_self: 'false'
      next_hop_third_party: 'true'
      prefix_list_in: 'default'
      prefix_list_out: 'default'
      route_map_in: 'default'
      route_map_out: 'default'
      route_reflector_client: 'false'
      send_community: 'default'
      soft_reconfiguration_in: 'inherit'
      soo: 'default'
      suppress_inactive: 'false'
      unsuppress_map: 'default'
      weight: 'default'
      state: present
      provider: "{{ cli }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Check Idempotence"
    nxos_bgp_neighbor_af: *configure_default
    register: result

  - assert: &false
      that:
        - "result.changed == false"
```

```shell
TASK [nxos_bgp_neighbor_af : Check Idempotence] *************************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_bgp_neighbor_af/tests/cli/sanity.yaml:69
<n9k.example.com> connection transport is cli
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> socket_path: /root/.ansible/pc/4cc10f215f
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_bgp_neighbor_af.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1500480959.08-141389138638211 `" && echo ansible-tmp-1500480959.08-141389138638211="` echo $HOME/.ansible/tmp/ansible-tmp-1500480959.08-141389138638211 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmp_LfFuC TO /root/.ansible/tmp/ansible-tmp-1500480959.08-141389138638211/nxos_bgp_neighbor_af.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1500480959.08-141389138638211/ /root/.ansible/tmp/ansible-tmp-1500480959.08-141389138638211/nxos_bgp_neighbor_af.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1500480959.08-141389138638211/nxos_bgp_neighbor_af.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1500480959.08-141389138638211/" > /dev/null 2>&1 && sleep 0'
changed: [n9k.example.com] => {
    "changed": true, 
    "commands": [
        "router bgp 65535", 
        "vrf blue", 
        "neighbor 3.3.3.3", 
        "address-family ipv4 unicast", 
        "prefix-list default out", 
        "no allowas-in", 
        "next-hop-third-party", 
        "route-map default in", 
        "filter-list default out"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "additional_paths_receive": "inherit", 
            "additional_paths_send": "inherit", 
            "advertise_map_exist": "default", 
            "advertise_map_non_exist": null, 
            "afi": "ipv4", 
            "allowas_in": false, 
            "allowas_in_max": "default", 
            "as_override": false, 
            "asn": "65535", 
            "default_originate": false, 
            "default_originate_route_map": "default", 
            "filter_list_in": "default", 
            "filter_list_out": "default", 
            "host": null, 
            "max_prefix_interval": null, 
            "max_prefix_limit": "default", 
            "max_prefix_threshold": null, 
            "max_prefix_warning": null, 
            "neighbor": "3.3.3.3", 
            "next_hop_self": false, 
            "next_hop_third_party": true, 
            "password": null, 
            "port": null, 
            "prefix_list_in": "default", 
            "prefix_list_out": "default", 
            "provider": null, 
            "route_map_in": "default", 
            "route_map_out": "default", 
            "route_reflector_client": false, 
            "safi": "unicast", 
            "send_community": "default", 
            "soft_reconfiguration_in": "inherit", 
            "soo": "default", 
            "ssh_keyfile": null, 
            "state": "present", 
            "suppress_inactive": false, 
            "timeout": 10, 
            "transport": "cli", 
            "unsuppress_map": "default", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null, 
            "vrf": "blue", 
            "weight": "default"
        }
    }
}

TASK [nxos_bgp_neighbor_af : assert] ************************************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_bgp_neighbor_af/tests/cli/sanity.yaml:73
fatal: [n9k.example.com]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```

**Comment by Qalthos** [comment]
I'm not really sure why that should work with `max_prefix_limit` commented (it didn't for me), but this did expose six or so _other_ parameters which weren't idempotent, which should now be fixed in #26370. Let me know if it runs now.

**Comment by mikewiebe** [comment]
Ok, this is much better but there is still an issue.  When I run the following playbook for the first time (no bgp config present on the device) it applies cleanly.  When I run the idempotence check however it fails.

```yaml
  - name: "Configure BGP neighbor non-defaults"
    nxos_bgp_neighbor_af: &configure_non_default
      asn: 65535
      vrf: 'blue'
      neighbor: '3.3.3.3'
      afi: ipv4
      safi: unicast
      additional_paths_receive: 'enable'
      additional_paths_send: 'disable'
      #advertise_map_non_exist: 'my_non_exist_map'
      # -----------------------------------------------
      # advertise_map_exist and advertise_map_non_exist
      # are mutually exclusive
      #advertise_map_exist: 'my_map'
      # -----------------------------------------------
      allowas_in: 'true'
      allowas_in_max: '5'
      as_override: 'true'
      default_originate: 'true'
      default_originate_route_map: 'my_route_map'
      filter_list_in: 'my_filter_list_in'
      filter_list_out: 'my_filter_list_out'
      max_prefix_limit: 100
      max_prefix_interval: 30
      max_prefix_threshold: 50
      max_prefix_warning: 'true'
      next_hop_self: 'true'
      next_hop_third_party: 'false'
      prefix_list_in: 'pfx_in'
      prefix_list_out: 'pfx_out'
      route_map_in: 'rm_in'
      route_map_out: 'rm_out'
      send_community: 'extended'
      soft_reconfiguration_in: 'enable'
      soo: '3:3'
      suppress_inactive: 'true'
      unsuppress_map: 'unsup_map'
      weight: '30'
      state: present
      provider: "{{ cli }}"
    register: result

  - assert: &true
     that:
       - "result.changed == true"

  - name: "Check Idempotence"
    nxos_bgp_neighbor_af: *configure_non_default
    register: result

  - assert: &false
     that:
       - "result.changed == false"
```

```shell
TASK [nxos_bgp_neighbor_af : Check Idempotence] ***************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_bgp_neighbor_af/tests/cli/sanity.yaml:135
<n9k.example.com> connection transport is cli
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> socket_path: /root/.ansible/pc/4cc10f215f
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_bgp_neighbor_af.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501697013.37-72276412316723 `" && echo ansible-tmp-1501697013.37-72276412316723="` echo $HOME/.ansible/tmp/ansible-tmp-1501697013.37-72276412316723 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmpvGwRAN TO /root/.ansible/tmp/ansible-tmp-1501697013.37-72276412316723/nxos_bgp_neighbor_af.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501697013.37-72276412316723/ /root/.ansible/tmp/ansible-tmp-1501697013.37-72276412316723/nxos_bgp_neighbor_af.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501697013.37-72276412316723/nxos_bgp_neighbor_af.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501697013.37-72276412316723/" > /dev/null 2>&1 && sleep 0'
fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "additional_paths_receive": "enable", 
            "additional_paths_send": "disable", 
            "advertise_map_exist": null, 
            "advertise_map_non_exist": null, 
            "afi": "ipv4", 
            "allowas_in": true, 
            "allowas_in_max": "5", 
            "as_override": true, 
            "asn": "65535", 
            "default_originate": true, 
            "default_originate_route_map": "my_route_map", 
            "filter_list_in": "my_filter_list_in", 
            "filter_list_out": "my_filter_list_out", 
            "host": null, 
            "max_prefix_interval": "30", 
            "max_prefix_limit": "100", 
            "max_prefix_threshold": "50", 
            "max_prefix_warning": true, 
            "neighbor": "3.3.3.3", 
            "next_hop_self": true, 
            "next_hop_third_party": false, 
            "password": null, 
            "port": null, 
            "prefix_list_in": "pfx_in", 
            "prefix_list_out": "pfx_out", 
            "provider": null, 
            "route_map_in": "rm_in", 
            "route_map_out": "rm_out", 
            "route_reflector_client": null, 
            "safi": "unicast", 
            "send_community": "extended", 
            "soft_reconfiguration_in": "enable", 
            "soo": "3:3", 
            "ssh_keyfile": null, 
            "state": "present", 
            "suppress_inactive": true, 
            "timeout": 10, 
            "transport": "cli", 
            "unsuppress_map": "unsup_map", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null, 
            "vrf": "blue", 
            "weight": "30"
        }
    }, 
    "msg": "maximum-prefix options\r\r\n                                                       ^\r\n% Invalid number at '^' marker.\r\n\rn9k-109(config-router-vrf-neighbor-af)# "
}
```

During the idempotence check the module is attempting to send an invalid command `maximum-prefix options`.  I added some debug code to write the contents of `candidate` inside of `main()` and you can see the difference between the first and second attempts.

```python
    if candidate:
        f = open('alog', 'w')
        candidate = candidate.items_text()
        f.write('Candidate Config:\n %s' % candidate)
        f.close()
```

**First Attempt: No bgp configured**
```shell
Candidate Config:
 ['router bgp 65535', 'vrf blue', 'neighbor 3.3.3.3', 'address-family ipv4 unicast', 'weight 30', 'maximum-prefix 100 50 restart 30', 'unsuppress-map unsup_map', 'as-override', 'filter-list my_filter_list_in in', 'next-hop-self', 'capability additional-paths receive', 'default-originate route-map my_route_map', 'route-map rm_out out', 'capability additional-paths send disable', 'no next-hop-third-party', 'default-originate', 'suppress-inactive', 'send-community extended', 'soft-reconfiguration inbound', 'allowas-in 5', 'soo 3:3', 'prefix-list pfx_in in']
```

**Second Attempt: Idempotence check**
```shell
Candidate Config:
 ['router bgp 65535', 'vrf blue', 'neighbor 3.3.3.3', 'address-family ipv4 unicast', 'filter-list my_filter_list_out out', 'as-override', 'maximum-prefix options', 'route-map rm_in in', 'default-originate route-map my_route_map', 'send-community extended', 'allowas-in 5', 'prefix-list pfx_out out']
```

As you can see the invalid command is sent.  Also not sure why any commands are being send in the second case since the configuration presumably already exists.
