### ISSUE TITLE
Successor bug of #5739, not removing temp files

### ISSUE THREAD

**Issue by mowgli** [ansible/ansible#26310]
Sorry, I have to reopen this old bug.

I have the following task:
```
- copy:
     dest: /etc/ansible/vault.pw
     force: no
     mode: 0400
     content: "{{ lookup('pipe', 'dd status=none if=/dev/random bs=1 count=24 | base64') }}\n"
```

Every time it is running, it left behind a temp file in /tmp with the output of the pipe.

Edit:
ansible --version
ansible 2.2.1.0
