### ISSUE TITLE
ec2_eip not idempotent, plus check mode makes changes

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#26345]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_eip

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/tom/repos/aws-codecommit/ansible-tower/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

Running an `ec2_eip` module task twice creates new IPs instead of recognising that the public IP specified already exists and returning OK.

_edit_ worringly, this also occurs when running the task in check mode! `--check`

##### STEPS TO REPRODUCE

Create an EIP inside a VPC and record the public IP (e.g. `1.2.3.4`).

Use that public IP in the `ec2_eip` task. The task will always create a new EIP (`3.4.5.6` etc) until the allocation on the account is exhausted.

Running the playbook with `--check` also causes the IP to be allocated.

```yaml
- name: manage EC2 EIP address
  ec2_eip:
    device_id:
    in_vpc: yes
    private_ip_address: 
    public_ip: 1.2.3.4
    region: eu-central-1
    release_on_disassociation: no
    reuse_existing_ip_allowed: no
    state: present
```

##### EXPECTED RESULTS

The EIP already exists, so no action should be taken.

##### ACTUAL RESULTS

A new, different EIP is created.

```
changed: [localhost] => {
    "allocation_id": "eipalloc-2a222222",
    "changed": true,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "device_id": null,
            "ec2_url": null,
            "in_vpc": true,
            "private_ip_address": null,
            "profile": null,
            "public_ip": "1.2.3.4",
            "region": "eu-central-1",
            "release_on_disassociation": false,
            "reuse_existing_ip_allowed": false,
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "wait_timeout": "300"
        }
    },
    "public_ip": "3.4.5.6"
}
```
