### ISSUE TITLE
junos_command: cannot get output of a command

### ISSUE THREAD

**Issue by playgroundctl** [ansible/ansible#26358]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_command

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/app/saint/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```
host_key_checking = False
```

##### SUMMARY

Cannot get command output from a Juniper device.

##### STEPS TO REPRODUCE

`ansible-playbook dev-conf.yml --extra-vars "dev=athens os=juniper"`

```yaml
---

  - name: dev-conf
    hosts: LOCAL
    roles:
      - common


    tasks:

      - name: "Retrieve router's configuration: junos"
        connection: local
        junos_command:
          commands: "show configuration | display set | no-more"
          provider:
            host: "{{ dev }}"
            port: 22
            username: "{{ lookup('env','USR_NETOPS') }}"
            password: "{{ lookup('env','PASS_NETOPS') }}"
        when: dev is defined and os is defined and os == "juniper"
        register: _

      - debug: msg="{{ _ }}"
```

##### EXPECTED RESULTS

Get router's configuration in `display set` format

##### ACTUAL RESULTS

```
$ ansible-playbook dev-conf.yml --extra-vars "dev=athens os=juniper" -vvvv
Using /home/app/saint/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: dev-conf.yml *******************************************************************************************************************************
1 plays in dev-conf.yml

PLAY [dev-conf] **************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: app
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/app/.ansible/tmp/ansible-tmp-1499090338.08-16740590805618 `" && echo ansible-tmp-1499090338.08-16740590805618="` echo /home/app/.ansible/tmp/ansible-tmp-1499090338.08-16740590805618 `" ) && sleep 0'
<localhost> PUT /tmp/tmpMTpD5T TO /home/app/.ansible/tmp/ansible-tmp-1499090338.08-16740590805618/setup.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/app/.ansible/tmp/ansible-tmp-1499090338.08-16740590805618/ /home/app/.ansible/tmp/ansible-tmp-1499090338.08-16740590805618/setup.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/app/.ansible/tmp/ansible-tmp-1499090338.08-16740590805618/setup.py; rm -rf "/home/app/.ansible/tmp/ansible-tmp-1499090338.08-16740590805618/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Retrieve router's configuration: junos] ********************************************************************************************************
task path: /home/app/saint/ansible/dev-conf.yml:12
<athens> using connection plugin netconf
<athens> socket_path: /home/app/.ansible/pc/d090e15c31
open_session() returned 0 ok 
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/junos/junos_command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: app
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/app/.ansible/tmp/ansible-tmp-1499090340.43-6328802200596 `" && echo ansible-tmp-1499090340.43-6328802200596="` echo /home/app/.ansible/tmp/ansible-tmp-1499090340.43-6328802200596 `" ) && sleep 0'
<localhost> PUT /tmp/tmpGOR9Z2 TO /home/app/.ansible/tmp/ansible-tmp-1499090340.43-6328802200596/junos_command.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/app/.ansible/tmp/ansible-tmp-1499090340.43-6328802200596/ /home/app/.ansible/tmp/ansible-tmp-1499090340.43-6328802200596/junos_command.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/app/.ansible/tmp/ansible-tmp-1499090340.43-6328802200596/junos_command.py; rm -rf "/home/app/.ansible/tmp/ansible-tmp-1499090340.43-6328802200596/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_t7Cbbz/ansible_module_junos_command.py", line 388, in <module>
    main()
  File "/tmp/ansible_t7Cbbz/ansible_module_junos_command.py", line 338, in main
    responses = rpc(module, items)
  File "/tmp/ansible_t7Cbbz/ansible_module_junos_command.py", line 229, in rpc
    responses.append(data.text.strip())
AttributeError: 'NoneType' object has no attribute 'text'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_t7Cbbz/ansible_module_junos_command.py\", line 388, in <module>\n    main()\n  File \"/tmp/ansible_t7Cbbz/ansible_module_junos_command.py\", line 338, in main\n    responses = rpc(module, items)\n  File \"/tmp/ansible_t7Cbbz/ansible_module_junos_command.py\", line 229, in rpc\n    responses.append(data.text.strip())\nAttributeError: 'NoneType' object has no attribute 'text'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/home/app/saint/ansible/dev-conf.retry

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  
```

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ganeshrn** [comment]
@nskalis Thank you for raising this issue.
Can you please test with referenced PR #26392 and  confirm if it fixes the issue

**Comment by narankhetani** [comment]
Hello,

Im still seeing the same issue:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'text'
fatal: [hostname]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_K2bWyJ/ansible_module_junos_command.py\", line 425, in <module>\n    main()\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_K2bWyJ/ansible_module_junos_command.py\", line 377, in main\n    responses = rpc(module, items)\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_K2bWyJ/ansible_module_junos_command.py\", line 260, in rpc\n    responses.append(data.text.strip())\nAttributeError: 'NoneType' object has no attribute 'text'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}```

**Comment by ganeshrn** [comment]
@narankhetani  That's strange, for me same playbook is working fine. 

Can you please re-verify with below change in the playbook
```
        junos_command:
          commands: show configuration
          display: set
```

**Comment by narankhetani** [comment]
yeap still not working:

```
     - name: Get Configuration
       junos_command:
         commands: show configuration
         display: set
         provider: "{{ cli }}"
```
This also fails with the same error:
```
     - name: Check DCL Interfaces
       junos_command:
         commands: show interfaces description | match DCL
         provider: "{{ cli }}"
```

and this works:
```
     - name: Check chassis enviornment information
       junos_command:
         commands: show chassis environment
         provider: "{{ cli }}"
```

**Comment by ganeshrn** [comment]
What is the `junos` version running on the device?

Only display option mentioned after pipe `|` is considered, all other options after `|` are ignored.

**Comment by narankhetani** [comment]
its a mx104 running 14.2R5.8, any idea how to get matched config if we cannot use pipe?

**Comment by ganeshrn** [comment]
As per doc [here](https://www.juniper.net/documentation/en_US/junos/topics/reference/tag-summary/junos-xml-protocol-get-configuration.html) fetching configuration in `set` format is supported from `15.1` onwards. 

I will add a check and throw an appropriate error if the device does not support `set` format.

You can apply ansible filter eg. `contains` `eq` etc to match the output of the command.

**Comment by narankhetani** [comment]
ah I see okay well that explains that.

**Comment by narankhetani** [comment]
im having the same issue now with an mx480 the same commands work on the mx104, see my commands below:
```
- name: Get protocol status 
  junos_command:
    commands: 
      - show vrrp brief
      - show vrrp brief logical-system BOR
      - show bgp summary
      - show bgp summary logical-system BOR
      - show isis adjacency
      - show isis adjacency logical-system BOR
    provider: "{{ cli }}"
  register: protocol_check
  tags: juniper
```
Get the following error:
```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_2jBV_R/ansible_module_junos_command.py", line 425, in <module>
    main()
  File "/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_2jBV_R/ansible_module_junos_command.py", line 377, in main
    responses = rpc(module, items)
  File "/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_2jBV_R/ansible_module_junos_command.py", line 253, in rpc
    responses.append(data.text.strip())
AttributeError: 'NoneType' object has no attribute 'text'

fatal: [cor-001a.ams0]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_2jBV_R/ansible_module_junos_command.py\", line 425, in <module>\n    main()\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_2jBV_R/ansible_module_junos_command.py\", line 377, in main\n    responses = rpc(module, items)\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_2jBV_R/ansible_module_junos_command.py\", line 253, in rpc\n    responses.append(data.text.strip())\nAttributeError: 'NoneType' object has no attribute 'text'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

Both running the same version of junos: 14.2R5.8
