### ISSUE TITLE
Dependency is being skipped as duplicate

### ISSUE THREAD

**Issue by infrascripting** [ansible/ansible#26364]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- Dependencies
- Conditionals
- Playbooks

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /opt/uss/ansible/config/test.cfg
  configured module search path = [u'/usr/share/ansible']
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

If a server is skipped in a playbook, the dependencies for subsequent roles do not run.

##### STEPS TO REPRODUCE

```yaml
----- hosts.yml ------

dev # rhel box
centtest # rhel box
cent6test # rhel box
sles # suse box

----- site.yml -----

- hosts: all
  roles:

    - { role: upgrade_kernel, when: ansible_os_family != 'Suse' }
    - { role: uptodate }

----- roles/upgrade_kernel/meta/main.yml -----

allow_duplicates: yes
dependencies:
  - { role: preinstall }

----- roles/uptodate/meta/main.yml -----

allow_duplicates: yes
dependencies:
  - { role: preinstall }

----- roles/preinstall/tasks/main.yml -----

- name: (main) Preinstall Checks
  include: "{{ ansible_pkg_mgr }}.yml"

----- roles/preinstall/tasks/yum.yml ------

- name: (yum) [1/2] Cache is dispelled
  file:
    path: "/var/cache/yum/"
    state: absent

- name: (yum) [2/2] Execute yum clean
  command: /usr/bin/yum clean all

----- roles/preinstall/tasks/zypper.yml -----

- name: (zypper) [1/1] Cache is dispelled
  file:
    path: "/var/cache/zypper/"
    state: absent

```

##### EXPECTED RESULTS

I expected that even though a SUSE box would be skipped for the first role in the playbook, that when it ran the second time, it would have its dependency run.

##### ACTUAL RESULTS

```
TASK [preinstall : (main) Preinstall Checks] ******************************
task path: /ansible/orchest/ansible-orchestrator-roles/preinstall/tasks/main.yml:3
skipping: [sles] => { 
    "changed":false,  
    "skip_reason": "Conditional result was False",
    "skipped": true }                                                                                                                                                                  

included: /ansible/orchest/ansible-orchestrator-roles/preinstall/tasks/yum.yml for cent6test, dev, centtest

#
#
# The three servers run preinstall successfully, and then the rest of upgrade_kernel runs and finishes successfully
#
# 

TASK [preinstall : (main) Preinstall Checks] *************************
task path: /ansible/orchest/ansible-orchestrator-roles/preinstall/tasks/main.yml:3
included: /ansible/orchest/ansible-orchestrator-roles/preinstall/tasks/zypper.yml for sles 
META: noop
META: noop

TASK [preinstall : (zypper) [1/1] Cache is dispelled] ****************************
task path: /ansible/orchest/ansible-orchestrator-roles/preinstall/tasks/zypper.yml:3
META: noop
skipping: [sles] => {
    "changed": false,
    "skip_reason": "Conditional result was False",
    "skipped": true
}
META: noop
META: noop

TASK [uptodate : (main) [1/1] Update all packages] *******************************
task path: /ansible/orchest/ansible-orchestrator-roles/uptodate/tasks/main.yml:3
included: /ansible/orchest/ansible-orchestrator-roles/uptodate/tasks/yum.yml for cent6test, dev, centtest
included: /ansible/orchest/ansible-orchestrator-roles/uptodate/tasks/zypper.yml for sles
```

##### Workaround

Switch the order of the playbooks. This way all servers' dependencies are accepted initially.

```
- hosts: all
  roles:
    - { role: uptodate }
    - { role: upgrade_kernel, when: ansible_os_family != 'Suse' }
```

This does not seem scalable, and does seem prone to error.

##### See Also

https://github.com/ansible/ansible/issues/14438

https://groups.google.com/forum/#!topic/ansible-project/24k-m1h4nnk
