### ISSUE TITLE
clear_host_errors does not clear error state when **ALL** servers generate an error

### ISSUE THREAD

**Issue by MKPhil** [ansible/ansible#26362]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
clear_host_errors

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/user/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
RHEL6

##### SUMMARY
clear_host_errors fails to reset the error state when **ALL** servers in target generate an error

##### STEPS TO REPRODUCE
```yaml
---
- name: Check Servers
  gather_facts: false
  hosts: windows
  tasks:
    - name: Check server with win_ping
      win_ping:
      register: result
      ignore_errors: yes
    - meta: clear_host_errors
    - debug:
        msg: "{{ inventory_hostname | quote }} {{ result | default() }}"
...
```
Run the above playbook against a non-existent server:
ansible-playbook -i hosts  ping_check.yml -l failingserver.fqdn.local

Alternatively:
ansible-playbook -i hosts  ping_check.yml 
where **ALL** the servers the inventory file do not exist.

Note:
If _at least_ one server in the inventory exists the playbook runs as expected for **ALL** servers (i.e. including the non-existent ones)

##### EXPECTED RESULTS
A debug print of the result, regardless of whether the win_ping task failed or not.

##### ACTUAL RESULTS
Play errors after the win_ping task and never reaches the debug task

(Not sure if #26227 is related as that seems to be a different issue with clear_host_errors)
