### ISSUE TITLE
Failed to use variable on docker_service's scale option

### ISSUE THREAD

**Issue by semente** [ansible/ansible#26374]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_service

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /srv/control/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### SUMMARY

Looks like we have a regression on 2.3 when using `docker_service.scale` with a variable as you can see below:

```
    - name: set up web apps
      docker_service:
        project_src: "/srv/{{ item }}"
        stopped: "{{ instances.get(item).is_disabled | default('false') }}"
        pull: yes
        scale:
          web: "{{ instances.get(item).scale }}"
      with_items: "{{ web_instances }}"
```

I've tried with and without `| int`. On 2.2.0 it used to work.

@kassiansun provided me a hot patch at https://github.com/ansible/ansible/issues/5865#issuecomment-302634030 and it is working for me now.
