### ISSUE TITLE
mail sending with STARTTLS broken because auth_flag variable is not updated after the starttls connection

### ISSUE THREAD

**Issue by Numerico** [ansible/ansible#26376]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

mail
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/my/path/ansibles/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

```

##### OS / ENVIRONMENT

Debian 8
##### SUMMARY

unable to  connect to mail server in ansible version 2.3.1, but it does work with 2.2.1.0
after some debug it seems that the **auth_flag** variable is not updated after the *STARTTLS* connection is established, [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/notification/mail.py#L308)
i have tried the connection in a python console, and  `smtp.has_extn('AUTH')` will return *False* before the *smtp.starttls()* method is called, but *True* after it. However, the variable is not updated, though *smtp.ehlo()* is called again.
this makes that when the variable is checked [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/notification/mail.py#L324), the **No Authentication on the server** exception is raised.

##### STEPS TO REPRODUCE

Reproducible with a simple mail task

```yaml
  mail:
    host: 'mail.server.net'
    port: 587
    username: "{{from_mail}}"
    password: '************'
    from: "{{from_mail}}"
    to: "{{email}}"
    subject: 'Hi there...'
    charset: 'utf8'
```

##### EXPECTED RESULTS

Mail sent
##### ACTUAL RESULTS

fatal: [etc.is]: FAILED! => {"changed": false, "failed": true, "msg": "No Authentication on the server at mail.server.net:587", "rc": 1}

```

```
