### ISSUE TITLE
win_chocolatey: Cannot install hotfixes (KB####) over WinRM

### ISSUE THREAD

**Issue by CFSworks** [ansible/ansible#26385]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- `win_chocolatey`

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, May  5 2017, 21:21:54) [GCC 6.3.0]
```

##### CONFIGURATION
- Default

##### OS / ENVIRONMENT

- Ansible on **Gentoo**
- Target system is **Windows via WinRM**

##### SUMMARY
[Microsoft does not support](https://support.microsoft.com/en-us/help/2773898/windows-update-standalone-installer-wusa-returns-0x5-error-access-deni) using WUSA over a WinRM connection. If WUSA.exe has a WinRM session for an ancestor, it will exit immediately with "Access denied."

Chocolatey packages that install Windows hotfixes (kb######) use WUSA to install the update after downloading it. If the Chocolatey command is running within a WinRM session, it encounters the same problem.

Special-casing win_chocolatey for names beginning with "kb" is no solution either; some Chocolatey packages depend on these hotfix packages, perhaps even indirectly.

This could be argued as a bug with the Chocolatey packages themselves, as there exists some condition under which installation will fail. However, I believe this is appropriate as an Ansible bug, because the `win_chocolatey` task cannot install hotfixes (or packages depending on them) at all.

##### STEPS TO REPRODUCE

```yaml
- name: Demonstrate bug with installing hotfixes over WinRM
  hosts: all
  tasks:
    - name: Install Chocolatey
      raw: "iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))"
    - name: Attempt to install KB3033929
      win_chocolatey: name=kb3033929
```

Please see [this gist](https://gist.github.com/CFSworks/490cf68574739df11b9deaaee1fcaa67) if you would like to reproduce the bug in Vagrant.

##### EXPECTED RESULTS

Hotfix package should install like any other Chocolatey package.

##### ACTUAL RESULTS

```
==> default: Running provisioner: ansible...
    default: Running ansible-playbook...

PLAY [Demonstrate bug with installing hotfixes over WinRM] *********************

TASK [Gathering Facts] *********************************************************
ok: [default]

TASK [Install Chocolatey] ******************************************************
changed: [default]

TASK [Attempt to install KB3033929] ********************************************
fatal: [default]: FAILED! => {"changed": false, "choco_error_cmd": "choco.exe install -dv -y kb3033929 -timeout 2700", "choco_error_log": null, "failed": true, "msg": "Error installing kb3033929", "rc": 5}
        to retry, use: --limit @/home/cfsworks/Desktop/winbug/playbook.retry

PLAY RECAP *********************************************************************
default                    : ok=2    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by ansibot** [comment]
cc @smadam813 @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
I am not sure where the best place to fix this is (in chocolatey, or in ansible module), but there is a workaround.  From what you are saying it might need to be fixed in chocolatey as the ansible module would likely be unmanageable if it also included (and replicated exactly) chocolatey's dependency management.

Although you can't install using WUSA you can extract the contents of a .msu using WUSA and then use DISM to install the cab.

Here's an example from one of my roles:

```yaml
- name: check if Windows8.1-KB2999226-x64.msu hotfix has been applied
  win_shell: Get-Hotfix -Id KB2999226
  register: hotfix_status
  ignore_errors: true

- name: show hotfix status
  debug:
    var: hotfix_status

# Unfortunately you can't use wusa directly to install windows updates.
# see https://support.microsoft.com/en-us/kb/2773898 for details
# you have to unpack the update file and then use dism.exe to install the cab

- name: unpack the hotfix if needed
  win_shell: 'wusa C:\deployment\current\Windows8.1-KB2999226-x64.msu /extract:C:\deployment\archive'
  when: hotfix_status.rc == 1

- name: use dism to install the cab containing the hotfix
  win_shell: 'dism.exe /online /add-package /PackagePath:C:\deployment\archive\Windows8.1-KB2999226-x64.cab'
  when: hotfix_status.rc == 1
```
