### ISSUE TITLE
lookup module fail to compute value of a template using regex_replace filter

### ISSUE THREAD

**Issue by Id2ndR** [ansible/ansible#26397]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
template action and template lookup give different results using regex_replace filter.

##### STEPS TO REPRODUCE

Playbook
```
- template:
    dest: /tmp/test.xml
    src: test.xml.j2
- copy:
    content: "{{ lookup( 'template', 'test.xml.j2' ) }}"
    dest: /tmp/test2.xml
```

template test.xml.j2
```
<command>ssh {{ command| regex_replace('"(.*)"', '"\\"\1\\""') }} #1</command>
<command>ssh {{ command| regex_replace('"(.*)"', '"\\"\\1\\""') }} #2</command>
{% set workaround_repl = '"\\"\\1\\""' %}
<command>ssh {{ command| regex_replace('"(.*)"', workaround_repl) }} #3</command>
```

##### EXPECTED RESULTS

I expect to get same /tmp/test2.xml after the two tasks

##### ACTUAL RESULTS

- when escaping once, template module fail to display the reference (#1)
- when escaping twice, lookup module fail to dereference the reference (#2)
- using workaround_repl (escaping twice), it work's normally (#3)
