### ISSUE TITLE
Apt module using with_items fail to apply the right versions

### ISSUE THREAD

**Issue by zbal** [ansible/ansible#2639]
When using a task in the following format:

```
- name: install a couple of pkg with same version
  apt: pkg=$item=1.2.3 state=present
  with_items:
    - foo-core
    - foo-utils
```

It gets converted on exec to:

```
apt-get install foo-core foo-utils=1.2.3
```

Where the expected command would be:

```
apt-get install foo-core=1.2.3 foo-utils=1.2.3
```

Not critical bug, but that should be the expected behavior.
