### ISSUE TITLE
jabber module does not connect to the server and looks like it takes in the user as the host

### ISSUE THREAD

**Issue by snevs** [ansible/ansible#26395]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- jabber.py

##### ANSIBLE VERSION

```
---> ansible --version
ansible 2.1.1.0
  config file = /home/myuser/ansible-tests/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

EL7, trying to control localhost

##### SUMMARY

The module doesn't take in the host as the proper host and attempts to connect to the 'user' instead of 'host'

##### STEPS TO REPRODUCE

- Nothing particular.

```
- name: announce on XMPP
  jabber:
      host: jabber1.mydomain.com
      user: user.name@mydomain.com
      password: "{{ my_pass }}"
      to: 'test_chatroom@conference.mydomain.com/test_chatroom'
      port: 5223
      msg: test
```

##### EXPECTED RESULTS

Connect to the server and post a message to a chatroom

##### ACTUAL RESULTS
`
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: myser
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-cyuqlpshwxdhnxstkkzmvjzxkhchgxvc; LANG=C LC_ALL=C LC_MESSAGES=C /usr/bin/python'"'"' && sleep 0'`

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"encoding": null, "host": "jabber1.mydomain.com", "msg": "test", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": "5223", "to": "test_chatroom@conference.mydomain.com/test_chatroom", "user": "user.name@mydomain.com"}, "module_name": "jabber"}, "msg": "Failed to connect to server: mydomain.com", "rc": 1}
```
