### ISSUE TITLE
New warning for "when" statements and jinja2 delimiters gives false positive

### ISSUE THREAD

**Issue by afunix** [ansible/ansible#26402]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
ansible 2.3.2.0 (stable-2.3 0c8459b01b) last updated 2017/07/04 10:40:32 (GMT -500)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### CONFIGURATION
ANSIBLE_HOME=/Users/cqx874/ansible/ansible
no ansible.cfg in the directory.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
New warning `when statements should not include jinja2 templating delimiters such as {{ }} or {% %}.` gives a false positive in a quite a big number of my playbooks.

The pattern I use is to execute some command, register the stdout and decide if the next step should be executed based on the stdout contents.
It's not always possible to write a condition like `when: '"something" in var.stdout'` or `when: 'variable in var.stdout'`.
Sometimes it is required to build a condition like `when: '"text {{variable}} text" in var.stdout'`, but this construction now generates the warning.

##### STEPS TO REPRODUCE
`ansible-playbook playbook.yml`

```yaml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - set_fact:
        gluster_version_target: "3.10"

    - name: get gluster version
      #command: "gluster --version"
      shell: 'printf "glusterfs 3.10.3\nRepository revision: git://git.gluster.org/glusterfs.git\nBla-bla-bla\n"'
      register: gluster_version_installed
      changed_when: no

    - name: do something if gluster of specific version
      when: '"glusterfs {{gluster_version_target}}" in gluster_version_installed.stdout'
      command: "/bin/true"
```

##### EXPECTED RESULTS
```
TASK [do something if gluster of specific version] **********************************************************************************************************************************
changed: [127.0.0.1]
```

##### ACTUAL RESULTS
```
TASK [do something if gluster of specific version] **********************************************************************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: "glusterfs {{gluster_version_target}}" in
gluster_version_installed.stdout

changed: [127.0.0.1]
```
