### ISSUE TITLE
ec2_elb_lb does not support check mode

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#26428]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ec2_elb_lb

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/tom/repos/aws-codecommit/ansible-tower/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

`ec2_elb_lb` module does not support check mode, making safe 'dry-run' testing impossible.

##### STEPS TO REPRODUCE

Run an ELB task using the `--check` command line switch, or `check_mode: yes` task modifier.

```yaml
- name: manage ELB [1/10]
  ec2_elb_lb:
    health_check:
      - ping_protocol: TCP
        ping_port: 80
        ping_path: 
        response_timeout: 2
        interval: 5
        unhealthy_threshold: 2
        healthy_threshold: 2
    instance_ids:
      - i-08c8ab
    listeners:
      - protocol: TCP
        load_balancer_port: 80
        instance_protocol: TCP
        instance_port: 80
        ssl_certificate_id: 
        proxy_protocol:
    name: foo-elb
    purge_instance_ids:
    purge_listeners:
    purge_subnets:
    purge_zones:
    region: us-west-1
    scheme: internal
    security_group_ids:
      - sg-12345678
    security_group_names:
    state: present
    stickiness:
    subnets:
      - subnet-12345678
    tags:
    wait: yes
    wait_timeout:
    zones:
      - us-west-1a
```

##### EXPECTED RESULTS

Ansible will tell me if any changes will be made, but doesn't make any changes.

##### ACTUAL RESULTS

```
    "msg": "remote module (ec2_elb_lb) does not support check mode",
    "skipped": true
```
