### ISSUE TITLE
junos_config: confirming previous commit not possible

### ISSUE THREAD

**Issue by benagricola** [ansible/ansible#26433]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
junos_config

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/bagricola/dev/network_deploy/ansible.cfg
  configured module search path = [u'./plugins/module']
  python version = 2.7.13 (default, Jun 29 2017, 16:19:32) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ansible documentation (https://docs.ansible.com/ansible/junos_config_module.html) states that it is possible to commit a previously commit-confirmed commit by passing no arguments to `junos_config`:

```
- name: confirm a previous commit
  junos_config:
    provider: "{{ netconf }}"
```

However, this is not the case. When no configuration options are passed to `junos_config` other than `provider`, an error message from `module_utils/junos.py` is thrown - `one of candidate or rollback must be specified`.

From looking at the code, it appears that this is an explicit check.

It also appears that even if this check were to pass, it would not be possible to commit since the commit code called by `load_config` explicitly checks for a diff before attempting to commit.

##### STEPS TO REPRODUCE
Live example

```yaml
- name: Enable RPM Monitoring for BGP Peers
  hosts: all
  gather_facts: True
  connection: local
  vars_files:
   - ../../vars/junos.yml
  tasks:
   - name: Enable RPM Monitoring on BGP Peers
     junos_config:
       comment: "Enable ICMP-Ping monitoring for BGP Peers"
       lines:
         - "set services rpm bgp probe-type icmp-ping"
         - "set services rpm bgp test-interval {{ junos.bgp.rpm.probe_test_interval | default(30) }}"
         - "set services rpm bgp probe-count {{ junos.bgp.rpm.probe_count | default(10) }}"
         - "set services rpm bgp probe-interval {{ junos.bgp.rpm.probe_interval | default(3) }}"
         - "set services rpm bgp history-size {{ junos.bgp.rpm.history_size | default(120) }}"
       confirm: '{{ junos.commit.confirm }}'
       provider: '{{ junos.provider }}'
     register: enable_rpm_monitoring

   - name: Confirming router access and BGP RPM Checks Exist
     junos_command:
       commands: 'show services rpm probe-results owner {{ junos.bgp.rpm.owner }}'
       display: xml
       wait_for:
         - "result[0]['rpc-reply']['probe-results'] contains probe-test-results"
       retries: '{{ junos.commit.retries }}'
       interval: '{{ junos.commit.interval }}'
       provider: '{{ junos.provider }}'

   - name: Confirm configuration
     junos_config:
       provider: '{{ junos.provider }}'
```

##### EXPECTED RESULTS
Expected result is the first call to `junos_config` triggers a commit confirmed, the `junos_command` validates that the config applied, and the second call to `junos_config` confirms the previous commit.

##### ACTUAL RESULTS
The first 2 steps complete successfully, and the third fails with an error:

```
TASK [Confirm configuration] *******************************
fatal: [bdr1.mgt]: FAILED! => {"changed": false, "failed": true, "msg": "one of candidate or rollback must be specified"}
```
