### ISSUE TITLE
null values in ec2_group cause failures with no message

### ISSUE THREAD

**Issue by aioue** [ansible/ansible#26431]
null `group_id` or `cidr_ip` in `rules` list causes task failure with no explanation message.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/tom/repos/aws-codecommit/ansible-tower/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT

Using latest devel version of ec2_group

https://github.com/ansible/ansible/blob/e9447e9481c6a1677f7276ccdeed986f47b588aa/lib/ansible/modules/cloud/amazon/ec2_group.py

##### SUMMARY

null (empty) `group_id` or `cidr_ip` in `rules` list causes task failure with no explanation message.

No other modules tested behave the same way and apply sensible defaults when presented with null values.

##### STEPS TO REPRODUCE

```yaml
- name: create security group
  ec2_group:
    description: foo
    name: bar
    purge_rules: true
    purge_rules_egress: true
    region: eu-central-1
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip:
          - 0.0.0.0/0
        group_id:
    rules_egress:
      - []
    state: present
    vpc_id: vpc-123456a
```

Also the same as above, but with  no `group_id` line, and a null (empty) `cidr_ip`

##### EXPECTED RESULTS

A security group is created.

##### ACTUAL RESULTS

Module fails with no message.

```
Using module file /Users/tom/repos/aws-codecommit/ansible-tower/library/ec2_group.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tom
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python2.7 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "failed_when_result": true,
    "group_id": "sg-12345678",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "Allow all",
            "ec2_url": null,
            "group_id": null,
            "name": "public",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "eu-central-1",
            "rules": [
                {
                    "cidr_ip": [
                        "0.0.0.0/0"
                    ],
                    "from_port": 22,
                    "group_id": null,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": [
                []
            ],
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-12345678"
        }
    }
}
```

And `cidr_ip` null failure:

```
Using module file /Users/tom/repos/aws-codecommit/ansible-tower/library/ec2_group.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tom
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python2.7 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "failed_when_result": true,
    "group_id": "sg-12345678",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "Allow all",
            "ec2_url": null,
            "group_id": null,
            "name": "public",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "eu-central-1",
            "rules": [
                {
                    "cidr_ip": null,
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": [
                []
            ],
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-12345678"
        }
    }
}
```

**Comment by s-hertel** [comment]
Hi @aioue.

Here is the playbook I'm running to try to trigger the TypeError with no cidr_ip:
```
---
- hosts: localhost
  connection: local
  tasks:
    - name: create security group
      ec2_group:
        description: foo
        name: bar
        purge_rules: true
        purge_rules_egress: true
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip:
        rules_egress:
          - []
        state: present
        vpc_id: vpc-XXXXXXXX
```
Here is the output:
```
changed: [localhost] => {
    "changed": true,


    "failed": false,
    "group_id": "sg-bee688cf",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "foo",
            "ec2_url": null,
            "group_id": null,
            "name": "bar",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "region": "us-east-1",
            "rules": [
                {
                    "cidr_ip": null,
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": [
                []
            ],
            "security_token": null,
            "state": "present",
            "validate_certs": true,
            "vpc_id": "vpc-XXXXXXXX"
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
Checking in the console I see that as expected a security group with no inbound or outbound rules is created. Are you still experiencing this problem with the latest changes on devel?

Giving a null value for group_id no longer results in a traceback (I believe fixed in https://github.com/ansible/ansible/pull/26333, but correct me if I'm wrong).
