### ISSUE TITLE
error with using digital_ocean_tag with ansible running with python3

### ISSUE THREAD

**Issue by wolfthefallen** [ansible/ansible#26489]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
digital_ocean_tag

##### ANSIBLE VERSION

```
ansible-2.3.1.0
```

##### OS / ENVIRONMENT

```
Ubuntu 16.04
Python 3.5

environment var do_api_key
```
##### SUMMARY
When running ansible version 2.3.10 installed with `python3 -m pip install ansbile` does not convert the json request to string prior to sending the create tag request to digital ocean.

##### STEPS TO REPRODUCE

```yaml
  vars:
    do_api_key: "{{ lookup('env', 'DO_API_KEY') }}"

  - name: create the new do droplet
    digital_ocean:
      api_token: "{{ do_api_key }}"
      backups_enabled: no
      command: droplet
      name: mysuperdroplet
      size_id: 2gb
      state: present
      region_id: ny1
      image_id: 22071043
      wait: yes
      wait_timeout: 600
    register: new_droplet

  - name: add droplet tag
    digital_ocean_tag:
      api_token: "{{ do_api_key }}"
      name: mytag
      state: present
      resource_id: "{{ new_droplet.droplet.id }}"
```

##### EXPECTED RESULTS
tag added to digital ocean droplet

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "the JSON object must be str, not 'bytes'"}
```
