### ISSUE TITLE
Gather facts from hosts specified in play, whatever --limit has been passed to ansible-playbook, in reasonable time

### ISSUE THREAD

**Issue by ei-grad** [ansible/ansible#26503]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
delegated_facts

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/ei-grad/repos/edadeal-ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

##### CONFIGURATION
```
[defaults]
roles_path = roles
gathering = smart
gather_subset = !hardware
fact_caching = redis
transport = ssh
fact_caching_timeout = 86400
forks = 100
retry_files_save_path = ~/.ansible-retry
remote_tmp = /tmp
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The [documentation](http://docs.ansible.com/ansible/playbooks_delegation.html#delegated-facts) mentions delegated facts as a silver bullet for `--limit` problem (it is not possible to get facts from all hosts while running the play tasks only for hosts, specified by `--limit` without `delegated_facts` usage), but delegated_facts run in `with_items` loop, which couldn't be parallelized. It tooks very long time to gather facts this way.

##### STEPS TO REPRODUCE
Setup a 10 hosts inventory. Run the following playbook with `ansible-playbook -f10 -l localhost,host1`.

```yaml
- name: gather facts via delegate_facts
  hosts: localhost
  tasks:
    - setup:
      delegate_to: "{{item}}"
      delegate_facts: True
      with_items: "{{groups.all}}"

- name: do some job
  hosts: all
    - command: sleep 10  # just a sample job, not related to this issue in any way
```

##### EXPECTED RESULTS
There should be the way to gather facts from specified hosts whatever `--limit`  has been passed to play, and this facts gathering should complete in reasonable time.

One way could be to make a special gather_facts mode - https://github.com/ansible/ansible/pull/15404, the other - implement the `forks` option for `with_` loops - https://github.com/ansible/ansible/issues/12086.

##### ACTUAL RESULTS
Delegated facts gathering via with_items loop tooks a very long time due to with_items loop can't be parallelized yet, and there is no other way to gather facts for speficied hosts without respect to `--limit`.

##### POSSIBLE WORKAROUND
One could setup the fact caching and gather facts via `ansible -m setup`. Cached facts would be available during the next ansible-playbook run. Though it seems to me someone would call this behaviour a bug.
