### ISSUE TITLE
Delete snapshot in vmware_guest_snapshot.py deletes snapshot subtree

### ISSUE THREAD

**Issue by johnnys66** [ansible/ansible#26522]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest_snapshot

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.3 (Maipo)
vCenter 5.5.0
ESXi 5.5.0

##### SUMMARY

When using module vmware_guest_snapshot to delete a snapshot it deletes the entire snapshot subtree.

##### STEPS TO REPRODUCE

```yaml
- name: delete vmware guest snapshot
  vmware_guest_snapshot:
    hostname: <hostname>
    datacenter: <datacenter>
    username: <username>
    password: <password>
    name: <vm_name>
    uuid: <vm_uuid>
    state: absent
    snapshot_name: <snapshot_name>
  delegate_to: localhost

```

##### EXPECTED RESULTS

Only the snapshot with the snapshot name should be deleted.

##### ACTUAL RESULTS

Every snapshot below the snapshot with the snapshot name is deleted (all the snapshot subtree).

```

```
##### SUGGESTION
This happens because in vmware_guest_snapshot.py, function remove_or_revert_snapshot, the method RemoveSnapshot_Task is called with parameter "True" which by vmware's sdk documentation means that the removeChildren flag is enabled ("Flag to specify removal of the entire snapshot subtree. "). https://pubs.vmware.com/vi3/sdk/ReferenceGuide/vim.vm.Snapshot.html

The default when invoking the RemoveSnapshot_Task should be with the "False" parameter.
```
task = snap_obj.RemoveSnapshot_Task(False)
```
