### ISSUE TITLE
reboot & wait_for works, fact gathering in subsequent play fails

### ISSUE THREAD

**Issue by jharting** [ansible/ansible#26543]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
fact module?

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /opt/insights/ansible-test/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:36) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
defaults

##### OS / ENVIRONMENT
Host (also running Ansible): Fedora 24
Guest (ansible-managed) CentOS v1706.02 VM run with Vagrant (VirtualBox)

##### SUMMARY
I set up tasks to do the common reboot & wait_for sequence. Tasks in the same play that follow reboot & wait_for run fine. If I add another play after the play that does reboot, fact gathering fails with 
```
fatal: [jozef_vm01]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh_exchange_identification: read: Connection reset by peer\r\n", "unreachable": true}
```
If I disable fact gathering in this play, its tasks run fine.

##### STEPS TO REPRODUCE

```yaml
﻿---
- name: Play 1 (reboot)
  hosts: jozef_vm01
  become: True
  tasks:
    - debug:
        msg: "Will reboot and then wait for {{ ansible_ssh_host }}:{{ ansible_ssh_port }} to come back to life"

    - name: Reboot system
      shell: sleep 2 && shutdown -r now "Ansible triggered reboot"
      async: 1
      poll: 0
      ignore_errors: true

    - name: Wait for system to boot up
      local_action: wait_for host={{ ansible_ssh_host }} port={{ ansible_ssh_port }} state=started delay=15 timeout=300
      become: False

    - debug:
        msg: "We're back again. Running on {{ inventory_hostname }}"

- name: Play 2
  hosts: jozef_vm01
  become: True
  gather_facts: True
  tasks:
    - debug:
        msg: "Hello from Play 2 on {{ inventory_hostname }}"
```

##### EXPECTED RESULTS
The play reboots the box and then prints:
```
"msg": "We're back again. Running on jozef_vm01"
"msg": "Hello from Play 2 on jozef_vm01"
```

##### ACTUAL RESULTS
```
PLAY [Play 1 (reboot)] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************
ok: [jozef_vm01]

TASK [debug] *******************************************************************************************************************************************************************************************************************************
ok: [jozef_vm01] => {
    "msg": "Will reboot and then wait for 127.0.0.1:2222 to come back to life"
}

TASK [Reboot system] ***********************************************************************************************************************************************************************************************************************
changed: [jozef_vm01]

TASK [Wait for system to boot up] **********************************************************************************************************************************************************************************************************
ok: [jozef_vm01 -> localhost]

TASK [debug] *******************************************************************************************************************************************************************************************************************************
ok: [jozef_vm01] => {
    "msg": "We're back again. Running on jozef_vm01"
}

PLAY [Play 2] ******************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************
fatal: [jozef_vm01]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh_exchange_identification: read: Connection reset by peer\r\n", "unreachable": true}
        to retry, use: --limit @/opt/insights/ansible-test/reboot/reproducer.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
jozef_vm01                 : ok=5    changed=1    unreachable=1    failed=0
```

Note that "We're back again. Running on jozef_vm01" **is printed** so waiting for the machine to come back online seems to work fine. However, fact gathering on the subsequent play fails afterwards.

**Note that if change Play 2 to gather_facts: False both plays finish successfully:**
```
LAY [Play 1 (reboot)] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************
ok: [jozef_vm01]

TASK [debug] *******************************************************************************************************************************************************************************************************************************
ok: [jozef_vm01] => {
    "msg": "Will reboot and then wait for 127.0.0.1:2222 to come back to life"
}

TASK [Reboot system] ***********************************************************************************************************************************************************************************************************************
changed: [jozef_vm01]

TASK [Wait for system to boot up] **********************************************************************************************************************************************************************************************************
ok: [jozef_vm01 -> localhost]

TASK [debug] *******************************************************************************************************************************************************************************************************************************
ok: [jozef_vm01] => {
    "msg": "We're back again. Running on jozef_vm01"
}

PLAY [Play 2] ******************************************************************************************************************************************************************************************************************************

TASK [debug] *******************************************************************************************************************************************************************************************************************************
ok: [jozef_vm01] => {
    "msg": "Hello from Play 2 on jozef_vm01"
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
jozef_vm01                 : ok=6    changed=1    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
cc @gregswift
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
My first guess would be that ssh controlMaster is in use, and post reboot, the shared connection to the remote host fails. 

1) Does adding a 'meta: reset_connection' after the reboot/wait_for help?

2) Could you post output with a higher verbosity (ie, 'ansible-playbook -vvvv')?

**Comment by ansibot** [comment]
cc @AnderEnder @jarv @jhoekx
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Tekki** [comment]
I'm fighting with wait_for since a long time. @jharting, are you sure the task breaks at gather_facts? I know it's from the example, but doesn't ansible_ssh_host (a deprecated variable name, by the way) called under local_action contain 'localhost'? This would mean we are waiting for localhost:22 instead of the_remote_host:22. I came to this idea because I have some servers with ssh on exotic ports and always get a timeout error with a message containing 'localhost:some_exotic_port'.

**Comment by jharting** [comment]
The problem went away after I upgraded my host machine to newer Fedora version. Disabling gather_facts for the after-reboot play really worked as a reliable workaround. `ansible_ssh_host` seems to work fine (proper IP and waits the right amount of time) even with `local_action`.

**Comment by Tekki** [comment]
I'll have to check it on a new system. Currently I work on Debian 8 (Ansible 2.3.1.0), so I'll try on Debian 9.

You can read about the variable names at http://docs.ansible.com/ansible/latest/intro_inventory.html#list-of-behavioral-inventory-parameters

I reboot my servers after a kernel upgrade. At the moment I have the situation that the following simple playbook fails with "Timeout when waiting for localhost:[exotic_port]":
```yaml
- hosts: xyz
  tasks:
    - name: wait for server with exotic port
      local_action: wait_for host="{{ ansible_host }}" port="{{ ansible_port }}"
```
While this one works fine:
```yaml
- hosts: xyz
  tasks:
    - name: wait for server with exotic port
      local_action: wait_for host="{{ inventory_hostname }}" port="{{ ansible_port }}"
```
