### ISSUE TITLE
ec2_eni module does not allow to assign additional secondary private ip 

### ISSUE THREAD

**Issue by pvshewale** [ansible/ansible#26575]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- ec2_eni

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /home/pshewale/ansible.cfg
  configured module search path = ['library']
```
##### OS / ENVIRONMENT
NA

##### SUMMARY
When using `ec2_eni` module to modify existing network interface on AWS, it does not allow to assign additional secondary private IP. It removed all existing secondary private IP addresses, instead of just assigning additional one.

##### STEPS TO REPRODUCE
1. Get an ec2 instance where multiple private IPs are allowed ( for example c4.xlarge allows 15 IPs)
2. Make sure its network interface is already having one or more secondary private IPs
3. Try to assign new secondary private IP using ec2_eni module

```
- ec2_eni:
        region: us-east-1
        eni_id: eni-yyyyyyyy
        state: present
        secondary_private_ip_addresses: 172.16.1.3

```

##### EXPECTED RESULTS

It should assign additional secondary private IP instead of overwriting it.

##### ACTUAL RESULTS

It removed existing secondary private IP and then added new one.
