### ISSUE TITLE
ios_template tries to get configuration when in config mode and fails

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#26605]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- ios_template

##### ANSIBLE VERSION

```
ansible 2.4.0 (aws-ios e7cf9de929) last updated 2017/07/10 08:45:10 (GMT -400)
  config file = None
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

ios_template tries to run `show running-config` while the device is in configure mode. This fails because `show` isn't a valid command in config mode. 

##### STEPS TO REPRODUCE

Network device: Cisco IOS XE Software, Version 16.03.01a.

Run `ansible-test network-integration ios_template --platform ios/csr1000v -vvvv`

Note: running ansible-test network-integration requires AWS credentials. Additionally use the following file for `test/integration/group_vars/ios.yaml` when running the ios_config tests on AWS.

```
---
cli:
  host: "{{ ansible_host }}"
  # username: "{{ ios_cli_user | default('cisco') }}"
  # password: "{{ ios_cli_pass | default('cisco') }}"
  transport: cli
```

`test/integration/targets/ios_template/tests/cli/backup.yaml`

```yaml
---
- debug: msg="START cli/backup.yaml"

- name: setup
  ios_config:
    commands:
      - no interface Loopback999
    match: none
  ignore_errors: yes

- name: collect any backup files
  find:
    paths: "{{ role_path }}/backup"
    pattern: "{{ inventory_hostname_short }}_config*"
  register: backup_files
  delegate_to: localhost

- name: delete backup files
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{backup_files.files|default([])}}"

- name: configure device with config
  ios_template:
    src: basic/config.j2
    backup: yes
  register: result

- assert:
    that:
      - "result.changed == true"
      - "result.updates is defined"

- name: collect any backup files
  find:
    paths: "{{ role_path }}/backup"
    pattern: "{{ inventory_hostname_short }}_config*"
  register: backup_files
  delegate_to: localhost

- assert:
    that:
      - "backup_files.files is defined"

- name: teardown
  ios_config:
    commands:
      - no interface Loopback999
    match: none

- debug: msg="END cli/backup.yaml"

```

##### ACTUAL RESULTS

```
TASK [ios_template : configure device with config] ***************************************************************************************************************************************************************************************************************************
task path: /Users/dnewswan/code/ansible/test/integration/targets/ios_template/tests/cli/backup.yaml:24
<ec2-34-229-7-29.compute-1.amazonaws.com> using connection plugin network_cli
<ec2-34-229-7-29.compute-1.amazonaws.com> socket_path: /Users/dnewswan/.ansible/pc/f363aa4a94
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/netcfg.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/netcli.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/ios.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/six/_six.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /Users/dnewswan/code/ansible/lib/ansible/module_utils/connection.py
Using module file /Users/dnewswan/code/ansible/lib/ansible/modules/network/ios/_ios_template.py
<ec2-34-229-7-29.compute-1.amazonaws.com> ESTABLISH LOCAL CONNECTION FOR USER: dnewswan
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1499697750.18-170368745268425 `" && echo ansible-tmp-1499697750.18-170368745268425="` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1499697750.18-170368745268425 `" ) && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> PUT /tmp/tmp3ndR2V TO /Users/dnewswan/.ansible/tmp/ansible-tmp-1499697750.18-170368745268425/_ios_template.py
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c 'chmod u+x /Users/dnewswan/.ansible/tmp/ansible-tmp-1499697750.18-170368745268425/ /Users/dnewswan/.ansible/tmp/ansible-tmp-1499697750.18-170368745268425/_ios_template.py && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c '/tmp/ansible-test-coverage-3OSowC/coverage/injector.py /Users/dnewswan/.ansible/tmp/ansible-tmp-1499697750.18-170368745268425/_ios_template.py; rm -rf "/Users/dnewswan/.ansible/tmp/ansible-tmp-1499697750.18-170368745268425/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_BwHtv0/ansible_modlib.zip/ansible/module_utils/ios.py", line 92, in get_config
    return _DEVICE_CONFIGS[cmd]

fatal: [ios-csr1000v]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "backup": true,
            "config": null,
            "force": false,
            "host": null,
            "include_defaults": true,
            "password": null,
            "port": null,
            "provider": null,
            "src": "interface Loopback999\n description this is a test\n shutdown\n\n",
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "msg": "unable to retrieve current config",
    "stderr": "show running-config\r\n                          ^\r\n% Invalid input detected at '^' marker.\r\n\r\nip-192-168-2-93(config)#",
    "stderr_lines": [
        "show running-config",
        "                          ^",
        "% Invalid input detected at '^' marker.",
        "",
        "ip-192-168-2-93(config)#"
    ]
}
	to retry, use: --limit @/Users/dnewswan/code/ansible/test/integration/ios_template-2kIcvk.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
ios-csr1000v               : ok=11   changed=1    unreachable=0    failed=1
```
