### ISSUE TITLE
A failure in cloudformation stack creation does not trigger a failure in the Ansible process

### ISSUE THREAD

**Issue by alexejpissarev** [ansible/ansible#26603]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudformation module

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
become_method = sudo
sudo_flags = -H -S -n
become_allow_same_user = True

##### OS / ENVIRONMENT
Ubuntu 16.04.1 LTS

##### SUMMARY
Cloudformation errors seem not always being handled correctly: a failure in cloudformation stack creation does not trigger a failure in the Ansible process but it continues the execution as if there was no mistake. E.g. in case a cloudformation stack tries to create a ressource which already exists and belongs to anogher stack.
In this case the stack became the status "ROLLBACK_COMPLETE" but the play recap displayed "failed=0"

##### STEPS TO REPRODUCE
```yaml
- name: Create 1st CF stack in AWS
  cloudformation:
    stack_name: "devops-voyager-cf-reproduce-test"
    state: "present"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "eu-central-1"
    template: "cf_templates/cf_reproduce.json"
    template_parameters: {}
  register: stack

- name: Create 2nd CF stack in AWS from the same template
  cloudformation:
    stack_name: "devops-voyager-cf-reproduce-test2"
    state: "present"
    aws_access_key: "{{ assumed_role.sts_creds.access_key }}"
    aws_secret_key: "{{ assumed_role.sts_creds.secret_key }}"
    security_token: "{{ assumed_role.sts_creds.session_token }}"
    region: "eu-central-1"
    template: "cf_templates/cf_reproduce.json"
    template_parameters: {}
  register: stack

```
Here is the the cf stack template "cf_reproduce.json":
...
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Description": "v0.2 | DB Systel | ... | Creates a new log group",
    "Resources": {
        "LogGroup": {
            "Properties": {
                "LogGroupName": "devops-voyager-try-sde"
            },
            "Type": "AWS::Logs::LogGroup"
        }
    }
}
...

##### EXPECTED RESULTS
- the first cf stack is created successfully
- the second cf stack creation fails
- the ansible process breaks

##### ACTUAL RESULTS
- the first cf stack is created successfully
- the second cf stack creation fails
- the ansible process proceedes with "failed=0" in play recap

```
TASK [provision_cf_stack : Create 1st CF stack in AWS] **************************************************************************************************************************************************************************************
...
changed: [persistent] => {
    "changed": true,
    "events": [
        "StackEvent AWS::CloudFormation::Stack devops-voyager-cf-reproduce-test CREATE_COMPLETE",
        "StackEvent AWS::Logs::LogGroup LogGroup CREATE_COMPLETE",
        "StackEvent AWS::Logs::LogGroup LogGroup CREATE_IN_PROGRESS",
        "StackEvent AWS::Logs::LogGroup LogGroup CREATE_IN_PROGRESS",
        "StackEvent AWS::CloudFormation::Stack devops-voyager-cf-reproduce-test CREATE_IN_PROGRESS"
    ],
    "invocation": {
        "module_args": {
            "aws_access_key": "...",
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "disable_rollback": false,
            "ec2_url": null,
            "notification_arns": null,
            "profile": null,
            "region": "eu-central-1",
            "role_arn": null,
            "security_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "stack_name": "devops-voyager-cf-reproduce-test",
            "stack_policy": null,
            "state": "present",
            "tags": null,
            "template": "cf_templates/cf_reproduce.json",
            "template_format": null,
            "template_parameters": {},
            "template_url": null,
            "validate_certs": true
        }
    },
    "log": [],
    "output": "Stack CREATE complete",
    "stack_outputs": {},
    "stack_resources": [
        {
            "last_updated_time": "2017-07-10T14:17:47.750000+00:00",
            "logical_resource_id": "LogGroup",
            "physical_resource_id": "devops-voyager-try-sde",
            "resource_type": "AWS::Logs::LogGroup",
            "status": "CREATE_COMPLETE",
            "status_reason": null
        }
    ]
}

TASK [provision_cf_stack : Create 2nd CF stack in AWS from the same template] ***************************************************************************************************************************************************************
...
changed: [persistent] => {
    "changed": true,
    "events": [
        "StackEvent AWS::CloudFormation::Stack devops-voyager-cf-reproduce-test2 ROLLBACK_COMPLETE",
        "StackEvent AWS::Logs::LogGroup LogGroup DELETE_COMPLETE",
        "StackEvent AWS::CloudFormation::Stack devops-voyager-cf-reproduce-test2 ROLLBACK_IN_PROGRESS",
        "StackEvent AWS::Logs::LogGroup LogGroup CREATE_FAILED",
        "StackEvent AWS::Logs::LogGroup LogGroup CREATE_IN_PROGRESS",
        "StackEvent AWS::CloudFormation::Stack devops-voyager-cf-reproduce-test2 CREATE_IN_PROGRESS"
    ],
    "invocation": {
        "module_args": {
            "aws_access_key": "...",
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "disable_rollback": false,
            "ec2_url": null,
            "notification_arns": null,
            "profile": null,
            "region": "eu-central-1",
            "role_arn": null,
            "security_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "stack_name": "devops-voyager-cf-reproduce-test2",
            "stack_policy": null,
            "state": "present",
            "tags": null,
            "template": "cf_templates/cf_reproduce.json",
            "template_format": null,
            "template_parameters": {},
            "template_url": null,
            "validate_certs": true
        }
    },
    "log": [
        "AWS::Logs::LogGroup LogGroup CREATE_FAILED: devops-voyager-try-sde already exists in stack arn:aws:cloudformation:eu-central-1:<account>:stack/devops-voyager-cf-reproduce-test/<hash>"
    ],
    "output": "Stack CREATE complete",
    "stack_outputs": {},
    "stack_resources": [
        {
            "last_updated_time": "2017-07-10T14:18:16.734000+00:00",
            "logical_resource_id": "LogGroup",
            "physical_resource_id": "",
            "resource_type": "AWS::Logs::LogGroup",
            "status": "DELETE_COMPLETE",
            "status_reason": null
        }
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
persistent                 : ok=4    changed=3    unreachable=0    failed=0
```
