### ISSUE TITLE
ios_system tests fail because commands are slightly different between versions

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#26607]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- ios_system

##### ANSIBLE VERSION

```
ansible 2.4.0 (aws-ios e7cf9de929) last updated 2017/07/10 08:45:10 (GMT -400)
  config file = None
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

In IOS Version 15.6(2)T `no ip domain lookup source-interface` works. In IOS Version 16.03.01a (which we use for testing on AWS) `no ip domain lookup source-interface' requires additional arguments. We need to update the tests for ios_system to dynamically pick the right command for the right version of IOS.

##### STEPS TO REPRODUCE

Network device: Cisco IOS XE Software, Version 16.03.01a.

Playbook: `test/integration/targets/ios_system/tests/cli/set_lookup_source.yaml`
run using: `ansible-test network-integration ios_system --platform ios/csr1000v -vvvv`

Note: running ansible-test network-integration requires AWS credentials. Additionally use the following file for `test/integration/group_vars/ios.yaml` when running the ios_config tests on AWS.

```
---
cli:
  host: "{{ ansible_host }}"
  # username: "{{ ios_cli_user | default('cisco') }}"
  # password: "{{ ios_cli_pass | default('cisco') }}"
  transport: cli
```

```yaml
---
- debug: msg="START cli/set_lookup_source.yaml"

- name: setup
  ios_config:
    lines:
      - no ip domain lookup source-interface
      - vrf definition ansible
    match: none
    authorize: yes
    provider: "{{ cli }}"

- name: configure lookup_source
  ios_system:
    lookup_source: Loopback10
    provider: "{{ cli }}"
    authorize: yes
  register: result

- assert:
    that:
      - result.changed == true
      - "'ip domain lookup source-interface Loopback10' in result.commands"

- name: verify lookup_source
  ios_system:
    lookup_source: Loopback10
    provider: "{{ cli }}"
    authorize: yes
  register: result

- assert:
    that:
      - result.changed == false

#- name: change to vrf
#  ios_system:
#    lookup_source:
#      - interface: Loopback10
#        vrf: ansible
#    authorize: yes
#    provider: "{{ cli }}"
#  register: result
#
#- assert:
#    that:
#      - result.changed == true
#      - "'no ip domain lookup source-interface Management1' in result.commands"
#      - "'ip domain lookup vrf ansible source-interface Management1' in result.commands"
#      - result.commands|length == 2
#
#- name: verify change to vrf
#  ios_system:
#    lookup_source:
#      - interface: Management1
#        vrf: ansible
#    authorize: yes
#    provider: "{{ cli }}"
#  register: result
#
#- assert:
#    that:
#      - result.changed == false

- name: teardown
  ios_config:
    lines:
      - no ip domain lookup source-interface
      - no vrf definition ansible
    match: none
    authorize: yes
    provider: "{{ cli }}"
  ignore_errors: yes
# FIXME: Not sure why this is failing with msg": "no vrf definition ansible\r\n% IPv4 and IPv6 addresses from all interfaces in VRF ansible have been removed\r\nfoo(config)#", rc:1

- debug: msg="END cli/set_lookup_source.yaml"

```

##### ACTUAL RESULTS

```
TASK [ios_system : setup] ****************************************************************************************************************************************************************************************************************************************************
task path: /Users/dnewswan/code/ansible/test/integration/targets/ios_system/tests/cli/set_lookup_source.yaml:4
<ec2-34-229-7-29.compute-1.amazonaws.com> using connection plugin network_cli
<ec2-34-229-7-29.compute-1.amazonaws.com> socket_path: /Users/dnewswan/.ansible/pc/f363aa4a94
Using module file /Users/dnewswan/code/ansible/lib/ansible/modules/network/ios/ios_config.py
<ec2-34-229-7-29.compute-1.amazonaws.com> ESTABLISH LOCAL CONNECTION FOR USER: dnewswan
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1499698304.64-170194575293916 `" && echo ansible-tmp-1499698304.64-170194575293916="` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1499698304.64-170194575293916 `" ) && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> PUT /tmp/tmp_Sicom TO /Users/dnewswan/.ansible/tmp/ansible-tmp-1499698304.64-170194575293916/ios_config.py
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c 'chmod u+x /Users/dnewswan/.ansible/tmp/ansible-tmp-1499698304.64-170194575293916/ /Users/dnewswan/.ansible/tmp/ansible-tmp-1499698304.64-170194575293916/ios_config.py && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c '/tmp/ansible-test-coverage-VelljY/coverage/injector.py /Users/dnewswan/.ansible/tmp/ansible-tmp-1499698304.64-170194575293916/ios_config.py; rm -rf "/Users/dnewswan/.ansible/tmp/ansible-tmp-1499698304.64-170194575293916/" > /dev/null 2>&1 && sleep 0'
fatal: [ios-csr1000v]: FAILED! => {
    "changed": false,
    "command": "no ip domain lookup source-interface",
    "failed": true,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": true,
            "backup": false,
            "before": null,
            "config": null,
            "defaults": false,
            "force": false,
            "host": null,
            "lines": [
                "no ip domain lookup source-interface",
                "vrf definition ansible"
            ],
            "match": "none",
            "multiline_delimiter": "@",
            "parents": null,
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": "ec2-34-229-7-29.compute-1.amazonaws.com",
                "password": null,
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "username": null
            },
            "replace": "line",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "msg": "no ip domain lookup source-interface\r\n% Incomplete command.\r\n\r\nios-csr1000v(config)#",
    "rc": 1
}
	to retry, use: --limit @/Users/dnewswan/code/ansible/test/integration/ios_system-iUwrhW.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
ios-csr1000v               : ok=46   changed=13   unreachable=0    failed=1
```
