### ISSUE TITLE
Handler is not executed when task fails and force_handlers: True

### ISSUE THREAD

**Issue by szymula** [ansible/ansible#26600]
##### ISSUE TYPE: 

 - Bug Report

##### COMPONENT NAME

 - ansible handlers

##### ANSIBLE VERSION

 - 2.3.1.0

##### CONFIGURATION

force_handlers = True

##### OS / ENVIRONMENT

 - Red Hat Enterprise Linux Server release 6.9 (Santiago)

##### SUMMARY

According to Ansible documentation (http://docs.ansible.com/ansible/playbooks_error_handling.html#id7) if I set force_handlers to True handler should be notified despite task has failed. Unfortunately this is not true. I would like to notify handler when my command fails (rc=1) therefore I use ignore_errors: True and changed_when: "result.rc != 0" in task definition, but my handler is not called.

##### STEPS TO REPRODUCE

``` yaml

- name: "Testing handlers"
  hosts: localhost
  gather_facts: no
  # force handlers, they will run when notified even if a task failed on that host
  force_handlers: True

  tasks:
    - name: "Running a command whose rc == 1"
      shell: "/bin/false"
      register: result
      ignore_errors: True
      changed_when: "result.rc != 0"
      notify: "my handler"

  handlers:
    - name: "my handler"
      debug: msg="My handler has been called"

```

##### EXPECTED RESULTS

$ ansible-playbook test-hanlers.yml

PLAY [Testing handlers] **************************************************************************************************************

TASK [Running a command whose rc == 1] ***********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "/bin/false", "delta": "0:00:00.004156", "end": "2017-07-10 09:05:23.192513", "failed": true, "rc": 1, "start": "2017-07-10 09:05:23.188357", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
...ignoring
PLAY RECAP ***************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
