### ISSUE TITLE
ios_user: create user fails idempotent test

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#26609]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- ios_user

##### ANSIBLE VERSION

```
ansible 2.4.0 (aws-ios e7cf9de929) last updated 2017/07/10 08:45:10 (GMT -400)
  config file = None
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

Adding the same user twice using ios_user returns results.changed=true.

##### STEPS TO REPRODUCE

Network device: Cisco IOS XE Software, Version 16.03.01a.

run `ansible-test network-integration ios_user --platform ios/csr1000v -vvvv`

Note: running ansible-test network-integration requires AWS credentials. Additionally use the following file for `test/integration/group_vars/ios.yaml` when running the ios tests on AWS.

```
---
cli:
  host: "{{ ansible_host }}"
  # username: "{{ ios_cli_user | default('cisco') }}"
  # password: "{{ ios_cli_pass | default('cisco') }}"
  transport: cli
```

```yaml
---
- name: Create user (SetUp)
  ios_user:
    name: ansibletest1
    privilege: 15
    role: network-operator
    state: present
    authorize: yes
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - 'result.changed == true'
      - 'result.commands == ["username ansibletest1 view network-operator", "username ansibletest1 privilege 15"]'

- name: Collection of users (SetUp)
  ios_user:
    users:
      - name: ansibletest2
      - name: ansibletest3
    authorize: yes
    state: present
    view: network-admin
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - 'result.changed == true'
      - 'result.commands == ["username ansibletest2 view network-admin", "username ansibletest3 view network-admin"]'

- name: Add user again (Idempotent)
  ios_user:
    name: ansibletest1
    privilege: 15
    role: network-operator
    state: present
    authorize: yes
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - 'result.changed == false'
      - 'result.commands | length == 0'

- name: Add collection of users again (Idempotent)
  ios_user:
    users:
      - name: anisbletest2
      - name: ansibletest3
    authorize: yes
    state: present
    view: network-admin
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - 'result.changed == false'
      - 'result.commands | length == 0'

- name: tearDown
  ios_user:
    users:
      - name: ansibletest1
      - name: ansibletest2
      - name: ansibletest3
    state: absent
    authorize: yes
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - 'result.changed == true'
      - 'result.commands == ["no username ansibletest1", "no username ansibletest2", "no username ansibletest3"]'

```

##### EXPECTED RESULTS

results.changed should be false

##### ACTUAL RESULTS

```
TASK [ios_user : Add collection of users again (Idempotent)] *****************************************************************************************************************************************************************************************************************
task path: /Users/dnewswan/code/ansible/test/integration/targets/ios_user/tests/cli/basic.yaml:48
<ec2-34-229-7-29.compute-1.amazonaws.com> using connection plugin network_cli
<ec2-34-229-7-29.compute-1.amazonaws.com> socket_path: /Users/dnewswan/.ansible/pc/f363aa4a94
Using module file /Users/dnewswan/code/ansible/lib/ansible/modules/network/ios/ios_user.py
<ec2-34-229-7-29.compute-1.amazonaws.com> ESTABLISH LOCAL CONNECTION FOR USER: dnewswan
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1499700171.09-85128723020700 `" && echo ansible-tmp-1499700171.09-85128723020700="` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1499700171.09-85128723020700 `" ) && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> PUT /tmp/tmpbVyzSJ TO /Users/dnewswan/.ansible/tmp/ansible-tmp-1499700171.09-85128723020700/ios_user.py
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c 'chmod u+x /Users/dnewswan/.ansible/tmp/ansible-tmp-1499700171.09-85128723020700/ /Users/dnewswan/.ansible/tmp/ansible-tmp-1499700171.09-85128723020700/ios_user.py && sleep 0'
<ec2-34-229-7-29.compute-1.amazonaws.com> EXEC /bin/sh -c '/tmp/ansible-test-coverage-07305o/coverage/injector.py /Users/dnewswan/.ansible/tmp/ansible-tmp-1499700171.09-85128723020700/ios_user.py; rm -rf "/Users/dnewswan/.ansible/tmp/ansible-tmp-1499700171.09-85128723020700/" > /dev/null 2>&1 && sleep 0'
changed: [ios-csr1000v] => {
    "changed": true,
    "commands": [
        "username anisbletest2 view network-admin"
    ],
    "failed": false,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": true,
            "host": null,
            "name": null,
            "nopassword": null,
            "password": null,
            "port": null,
            "privilege": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": "ec2-34-229-7-29.compute-1.amazonaws.com",
                "password": null,
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "cli",
                "username": null
            },
            "purge": false,
            "ssh_keyfile": null,
            "state": "present",
            "timeout": null,
            "update_password": "always",
            "username": null,
            "users": [
                {
                    "name": "anisbletest2",
                    "nopassword": null,
                    "password": null,
                    "privilege": null,
                    "state": "present",
                    "view": "network-admin"
                },
                {
                    "name": "ansibletest3",
                    "nopassword": null,
                    "password": null,
                    "privilege": null,
                    "state": "present",
                    "view": "network-admin"
                }
            ],
            "view": "network-admin"
        }
    }
}

TASK [ios_user : assert] *****************************************************************************************************************************************************************************************************************************************************
task path: /Users/dnewswan/code/ansible/test/integration/targets/ios_user/tests/cli/basic.yaml:59
fatal: [ios-csr1000v]: FAILED! => {
    "assertion": "result.changed == false",
    "changed": false,
    "evaluated_to": false,
    "failed": true
}
	to retry, use: --limit @/Users/dnewswan/code/ansible/test/integration/ios_user-SLu9bD.retry

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************
ios-csr1000v               : ok=12   changed=3    unreachable=0    failed=1
```
