### ISSUE TITLE
ios_config: IndexError

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#26620]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

-ios_config

##### ANSIBLE VERSION

```
ansible 2.4.0 (aws-junos-vmx f31d3ddeb7) last updated 2017/07/10 11:51:43 (GMT -400)
  config file = None
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

ios_config throws an IndexError when attempting to configure device from source file.

##### STEPS TO REPRODUCE

IOS Version 15.6

`ANSIBLE_ROLES_PATH=~/code/ansible/test/integration/targets/ ansible-playbook ios.yaml -i inventory.network -e limit_to=ios_config -u cisco -k -vvvv`

```yaml
---
- debug: msg="START cli/defaults.yaml"

- name: setup
  ios_config:
    commands:
      - no description
      - shutdown
    parents:
      - interface Loopback999
    match: none

- name: configure device with defaults included
  ios_config:
    src: defaults/config.j2
    defaults: yes
  register: result

- debug: var=result

- assert:
    that:
      - "result.changed == true"
# FIXME Bug https://github.com/ansible/ansible/issues/19382
#    - "result.updates is not defined"

- name: check device with defaults included
  ios_config:
    src: defaults/config.j2
    defaults: yes
  register: result

- debug: var=result

- assert:
    that:
      - "result.changed == false"
      - "result.updates is not defined"

- debug: msg="END cli/defaults.yaml"

```

##### EXPECTED RESULTS

Test should run without failure.

##### ACTUAL RESULTS

```
TASK [ios_config : configure device with defaults included] ******************************************************************************************************************************************************************************************************************
task path: /Users/dnewswan/code/ansible/test/integration/targets/ios_config/tests/cli/defaults.yaml:13
<ios01> using connection plugin network_cli
<ios01> socket_path: /Users/dnewswan/.ansible/pc/e9c21a7b4c
Using module file /Users/dnewswan/code/ansible/lib/ansible/modules/network/ios/ios_config.py
<ios01> ESTABLISH LOCAL CONNECTION FOR USER: dnewswan
<ios01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<ios01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1499710553.28-5521628199470 `" && echo ansible-tmp-1499710553.28-5521628199470="` echo /Users/dnewswan/.ansible/tmp/ansible-tmp-1499710553.28-5521628199470 `" ) && sleep 0'
<ios01> PUT /var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/tmpiHy3TZ TO /Users/dnewswan/.ansible/tmp/ansible-tmp-1499710553.28-5521628199470/ios_config.py
<ios01> EXEC /bin/sh -c 'chmod u+x /Users/dnewswan/.ansible/tmp/ansible-tmp-1499710553.28-5521628199470/ /Users/dnewswan/.ansible/tmp/ansible-tmp-1499710553.28-5521628199470/ios_config.py && sleep 0'
<ios01> EXEC /bin/sh -c 'python /Users/dnewswan/.ansible/tmp/ansible-tmp-1499710553.28-5521628199470/ios_config.py; rm -rf "/Users/dnewswan/.ansible/tmp/ansible-tmp-1499710553.28-5521628199470/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_nInA6W/ansible_module_ios_config.py", line 394, in <module>
    main()
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_nInA6W/ansible_module_ios_config.py", line 346, in main
    config, have_banners = get_running_config(module)
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_nInA6W/ansible_module_ios_config.py", line 270, in get_running_config
    flags.append(get_defaults_flag(module))
  File "/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_nInA6W/ansible_modlib.zip/ansible/module_utils/ios.py", line 75, in get_defaults_flag
IndexError: list index out of range

fatal: [ios01]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_nInA6W/ansible_module_ios_config.py\", line 394, in <module>\n    main()\n  File \"/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_nInA6W/ansible_module_ios_config.py\", line 346, in main\n    config, have_banners = get_running_config(module)\n  File \"/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_nInA6W/ansible_module_ios_config.py\", line 270, in get_running_config\n    flags.append(get_defaults_flag(module))\n  File \"/var/folders/ql/d9_087wj4cd10grvwzxmk4hc0000gn/T/ansible_nInA6W/ansible_modlib.zip/ansible/module_utils/ios.py\", line 75, in get_defaults_flag\nIndexError: list index out of range\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```
