### ISSUE TITLE
pamd.py - After/Before state duplicate lines

### ISSUE THREAD

**Issue by silvinux** [ansible/ansible#26633]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

/usr/lib/python2.7/site-packages/ansible/modules/system/pamd.py

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug 29 2016, 10:12:21) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### SUMMARY

The last pamd.py update has a bug, after/before state duplicate lines, is not idempotent. I took the library from pamd-fixes (#25817).

##### STEPS TO REPRODUCE

```yaml

---
- hosts: lab
  gather_facts: yes
  remote_user: gnfux
  become: yes
  become_method: sudo
  tasks:
    - name: "Ensure cryptographic hash and rember last 6 pwd /etc/pam.d/system-auth"
      become: yes
      pamdl:
        path: /etc/pam.d/
        name: system-auth
        type: password
        control: requisite
        module_path: pam_cracklib.so
        new_type: password
        new_control: sufficient
        new_module_path: pam_unix.so
        module_arguments: 'remember=6 sha512 shadow nullok try_first_pass use_authtok'
        state: after
```

##### EXPECTED RESULTS

```
/etc/pam.d/system-auth
auth      	required	pam_env.so
auth      	required	pam_tally2.so deny=5 onerr=fail
auth      	sufficient	pam_unix.so nullok try_first_pass
auth      	requisite	pam_succeed_if.so uid >= 1000 quiet_success
auth      	required	pam_deny.so

password  	requisite	pam_cracklib.so retry=5 minlen=6 dcredit=-1 ucredit=0 lcredit=-1 ocredit=0 reject_username
password  	sufficient	pam_unix.so remember=6 sha512 shadow nullok try_first_pass use_authtok
password  	sufficient	pam_sss.so use_authtok
password  	required	pam_deny.so

```

##### ACTUAL RESULTS

```
/etc/pam.d/system-auth

auth      	required	pam_env.so
auth      	required	pam_tally2.so deny=5 onerr=fail
auth      	sufficient	pam_unix.so nullok try_first_pass
auth      	requisite	pam_succeed_if.so uid >= 1000 quiet_success
auth      	required	pam_deny.so

password  	requisite	pam_cracklib.so retry=5 minlen=6 dcredit=-1 ucredit=0 lcredit=-1 ocredit=0 reject_username
password  	sufficient	pam_unix.so remember=6 sha512 shadow nullok try_first_pass use_authtok
password  	sufficient	pam_unix.so remember=6 sha512 shadow nullok try_first_pass use_authtok
password  	sufficient	pam_sss.so use_authtok
password  	required	pam_deny.so
```

```

```
