### ISSUE TITLE
File Module: Symlink source not exists - force not working

### ISSUE THREAD

**Issue by Tux12Fun** [ansible/ansible#26638]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module: File

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

OS: Ubuntu 16.04.02 Xenial 64 Bit

##### SUMMARY

The Symlink is not created.

##### STEPS TO REPRODUCE

```yaml
  - name:                        TEST
    file:
       src:                      "/tmp/not_existing"
       dest:                     "/tmp/link"
       force:                    true
       mode:                     link

```

##### EXPECTED RESULTS

The Symlink should be created

##### ACTUAL RESULTS

```
fatal: [xxx-xx1.xxxxxxx.local]: FAILED! => {"changed": false, "failed": true, "msg": "file (/tmp/link) is absent, cannot continue", "path": "/tmp/link", "state": "absent"}
```
