### ISSUE TITLE
docker_service got an unexpected keyword argument

### ISSUE THREAD

**Issue by mchassy** [ansible/ansible#26647]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
* ansible
* ansible-playbook
* docker_service
* ansible-container

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION
```
```
##### OS / ENVIRONMENT
```
AWS Linux 64 bit
Python 2.7.12
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
ansible==2.3.1.0
-e git+https://github.com/ansible/ansible-container@0d54b0efba8a6bc205c0619226397201381e8e20#egg=ansible_container
aws-cfn-bootstrap==1.4
awscli==1.11.83
Babel==0.9.4
backports.ssl-match-hostname==3.5.0.1
boto==2.42.0
botocore==1.5.46
cached-property==1.3.0
certifi==2017.4.17
chardet==3.0.4
cloud-init==0.7.6
colorama==0.3.9
configobj==4.7.2
dictdiffer==0.6.1
docker==2.0.1
docker-compose==1.14.0
docker-pycreds==0.2.1
dockerpty==0.4.1
docopt==0.6.2
docutils==0.11
ecdsa==0.11
enum34==1.1.6
functools32==3.2.3.post2
futures==3.0.3
httplib2==0.10.3
idna==2.5
iniparse==0.3.1
ipaddress==1.0.18
Jinja2==2.9.6
jmespath==0.9.2
jsonpatch==1.2
jsonpointer==1.0
jsonschema==2.6.0
kitchen==1.1.1
kubernetes==1.0.2
lockfile==0.8
MarkupSafe==1.0
oauth2client==4.1.2
openshift==0.0.1
paramiko==1.15.1
PIL==1.1.6
ply==3.4
pyasn1==0.1.7
pyasn1-modules==0.0.9
pycrypto==2.6.1
pycurl==7.19.0
pygpgme==0.3
pyliblzma==0.5.3
pystache==0.5.3
python-daemon==1.5.2
python-dateutil==2.1
python-string-utils==0.6.0
pyxattr==0.5.0
PyYAML==3.12
requests==2.11.1
rsa==3.4.1
ruamel.ordereddict==0.4.9
ruamel.yaml==0.15.18
simplejson==3.6.5
six==1.10.0
structlog==17.2.0
texttable==0.8.8
urlgrabber==3.10
urllib3==1.21.1
virtualenv==12.0.7
websocket-client==0.44.0
yum-metadata-parser==1.1.4
```

##### SUMMARY
Playbook, generated by ansible-container, fails to run.
There were already some basic error in the generated playbook which i fixed.
The images now download but then there is this error message
```
TASK [docker_service] **********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "Error starting project __init__() got an unexpected keyword argument 'cpu_count'"}
	to retry, use: --limit @/home/ec2-user/orson/orson.retry

```

##### STEPS TO REPRODUCE
Run this command on the playbook. You can either put other generic images in place of mine or you can contact me and I will give you temporary access to our private registry. 

```
ansible-playbook --step -t start orson.yml
```

```yaml
  - gather_facts: false
    tasks:
      - docker_login: username=mchassy password=XXXXXXX email=mchassy@orsontestdata.com
        tags:
          - start
      - docker_service:
            definition:
                services: &id001
                    tomee:
                        image: orsontestdata/orson-tomee:1.2.0-ansible
                        working_dir: /opt
                        entrypoint:
                          - /entrypoint.sh
                        user: orson
                        command:
                          - /usr/bin/dumb-init
                          - /opt/orson/tomee/bin/catalina.sh
                          - run
                        ports:
                          - 8080:8080
                    mongo:
                        image: orsontestdata/orson-mongo:1.2.0-ansible
                        working_dir: /opt
                        entrypoint:
                          - /entrypoint.sh
                        user: orson
                        volumes:
                          - mongo_data:/opt/orson/mongo/data
                        command:
                          - /usr/bin/dumb-init
                          - /opt/orson/mongo/bin/mongod --config /opt/orson/mongo/conf/mongod.conf
                        expose:
                          - 27017
                version: '2'
                volumes:
                    mongo_data: &id002 {}
            state: present
            project_name: orson
        tags:
          - start

```

##### EXPECTED RESULTS
images pulled and services started
##### ACTUAL RESULTS
images are pulled but services don't start
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "", "msg": "Error starting project __init__() got an unexpected keyword argument 'cpu_count'"}
	to retry, use: --limit @/home/ec2-user/orson/orson.retry

```

**Comment by calfonso** [comment]
Would you please re-run this with -vvvv and provide the output for us to examine?

needs_info

**Comment by mchassy** [comment]
Here you go 
```
[ec2-user@ip-172-31-47-32 orson]$ ./play_on_orson_master.sh
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: orson.yml ***************************************************************************************************************
1 plays in orson.yml

PLAY [localhost] ******************************************************************************************************************
META: ran handlers
Perform task: TASK: docker_login (N)o/(y)es/(c)ontinue: y

Perform task: TASK: docker_login (N)o/(y)es/(c)ontinue: ***************************************************************************

TASK [docker_login] ***************************************************************************************************************
task path: /home/ec2-user/orson/orson.yml:3
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_login.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ec2-user
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1499870798.36-76229811255496 `" && echo ansible-tmp-1499870798.36-76229811255496="` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1499870798.36-76229811255496 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpqzMgWQ TO /home/ec2-user/.ansible/tmp/ansible-tmp-1499870798.36-76229811255496/docker_login.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ec2-user/.ansible/tmp/ansible-tmp-1499870798.36-76229811255496/ /home/ec2-user/.ansible/tmp/ansible-tmp-1499870798.36-76229811255496/docker_login.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1499870798.36-76229811255496/docker_login.py; rm -rf "/home/ec2-user/.ansible/tmp/ansible-tmp-1499870798.36-76229811255496/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_version": null,
            "cacert_path": null,
            "cert_path": null,
            "config_path": "~/.docker/config.json",
            "debug": false,
            "docker_host": null,
            "email": "mchassy@orsontestdata.com",
            "filter_logger": false,
            "key_path": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "reauthorize": false,
            "registry_url": "https://index.docker.io/v1/",
            "ssl_version": null,
            "state": "present",
            "timeout": null,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null,
            "username": "mchassy"
        }
    },
    "login_result": {
        "email": "mchassy@orsontestdata.com",
        "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "serveraddress": "https://index.docker.io/v1/",
        "username": "mchassy"
    }
}
Perform task: TASK: docker_service (N)o/(y)es/(c)ontinue: y

Perform task: TASK: docker_service (N)o/(y)es/(c)ontinue: *************************************************************************

TASK [docker_service] *************************************************************************************************************
task path: /home/ec2-user/orson/orson.yml:6
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_service.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ec2-user
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1499870801.94-212166113163594 `" && echo ansible-tmp-1499870801.94-212166113163594="` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1499870801.94-212166113163594 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpIq89Y9 TO /home/ec2-user/.ansible/tmp/ansible-tmp-1499870801.94-212166113163594/docker_service.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ec2-user/.ansible/tmp/ansible-tmp-1499870801.94-212166113163594/ /home/ec2-user/.ansible/tmp/ansible-tmp-1499870801.94-212166113163594/docker_service.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1499870801.94-212166113163594/docker_service.py; rm -rf "/home/ec2-user/.ansible/tmp/ansible-tmp-1499870801.94-212166113163594/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "api_version": null,
            "build": false,
            "cacert_path": null,
            "cert_path": null,
            "debug": false,
            "definition": {
                "services": {
                    "mongo": {
                        "command": [
                            "/usr/bin/dumb-init",
                            "/opt/orson/mongo/bin/mongod --config /opt/orson/mongo/conf/mongod.conf"
                        ],
                        "entrypoint": [
                            "/entrypoint.sh"
                        ],
                        "expose": [
                            27017
                        ],
                        "image": "orsontestdata/orson-mongo:1.2.0-ansible",
                        "user": "orson",
                        "volumes": [
                            "mongo_data:/opt/orson/mongo/data"
                        ],
                        "working_dir": "/opt"
                    },
                    "tomee": {
                        "command": [
                            "/usr/bin/dumb-init",
                            "/opt/orson/tomee/bin/catalina.sh",
                            "run"
                        ],
                        "entrypoint": [
                            "/entrypoint.sh"
                        ],
                        "image": "orsontestdata/orson-tomee:1.2.0-ansible",
                        "ports": [
                            "8080:8080"
                        ],
                        "user": "orson",
                        "working_dir": "/opt"
                    }
                },
                "version": "2",
                "volumes": {
                    "mongo_data": {}
                }
            },
            "dependencies": true,
            "docker_host": null,
            "files": null,
            "filter_logger": false,
            "hostname_check": false,
            "key_path": null,
            "nocache": false,
            "project_name": "orson",
            "project_src": null,
            "pull": false,
            "recreate": "smart",
            "remove_images": null,
            "remove_orphans": false,
            "remove_volumes": false,
            "restarted": false,
            "scale": null,
            "services": null,
            "ssl_version": null,
            "state": "present",
            "stopped": false,
            "timeout": 10,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null
        }
    },
    "module_stderr": "",
    "module_stdout": "",
    "msg": "Error starting project __init__() got an unexpected keyword argument 'cpu_count'"
}
	to retry, use: --limit @/home/ec2-user/orson/orson.retry

PLAY RECAP ************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

[ec2-user@ip-172-31-47-32 orson]$
```

**Comment by chouseknecht** [comment]
@mchassy 

I pared your definition down to the following, so that I could run it locally:

```
- name: Test
  connection: local
  hosts: localhost
  gather_facts: false
  tasks:
      - docker_service:
          definition:
            services:
              tomee:
                image: tomee:latest
                working_dir: /opt
                #entrypoint:
                #- /entrypoint.sh
                #command:
                #- /usr/bin/dumb-init
                #- /opt/orson/tomee/bin/catalina.sh
                #- run
                ports:
                - 8080:8080
              mongo:
                image: mongo:latest
                working_dir: /opt
                #entrypoint:
                #- /entrypoint.sh
                volumes:
                - mongo_data:/opt/orson/mongo/data
                #command:
                #- /usr/bin/dumb-init
                #- /opt/orson/mongo/bin/mongod --config /opt/orson/mongo/conf/mongod.conf
                expose:
                - 27017
            version: '2'
            volumes:
              mongo_data: {}
          state: present
          project_name: orson
```

Not seeing an error. The services start as expected. I wonder if `cpu_count` is a configuration setting on your images?

**Comment by mchassy** [comment]
I have pared down to the same, but I am still getting the same error.
Are you using the AWS linux as well?

```
    connection: local
    hosts: localhost
    tasks:
      - docker_service:
            definition:
                services:
                    tomee:
                        image: tomee:latest
                        working_dir: /opt
#                        entrypoint:
#                          - /entrypoint.sh
#                        user: orson
#                        command:
#                          - /usr/bin/dumb-init
#                          - /opt/orson/tomee/bin/catalina.sh
#                          - run
                        ports:
                          - 8080:8080
                    mongo:
                        image: mongo:latest
                        working_dir: /opt
#                        entrypoint:
#                          - /entrypoint.sh
#                        user: orson
#                        volumes:
#                          - mongo_data:/opt/orson/mongo/data
#                        command:
#                          - /usr/bin/dumb-init
#                          - /opt/orson/mongo/bin/mongod --config /opt/orson/mongo/conf/mongod.conf
                        expose:
                          - 27017
                version: '2'
                volumes:
                    mongo_data:
            state: present
            project_name: orson
```
```
[ec2-user@ip-172-31-47-32 orson]$ ./play_on_orson_master.sh
No config file found; using defaults
 [WARNING]: Host file not found: /etc/ansible/hosts

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: orson.yml *************************************************************************************************************************
1 plays in orson.yml

PLAY [Test] *********************************************************************************************************************************
META: ran handlers

TASK [docker_service] ***********************************************************************************************************************
task path: /home/ec2-user/orson/orson.yml:6
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_service.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ec2-user
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1499941715.51-229243879844145 `" && echo ansible-tmp-1499941715.51-229243879844145="` echo /home/ec2-user/.ansible/tmp/ansible-tmp-1499941715.51-229243879844145 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmppE5u_W TO /home/ec2-user/.ansible/tmp/ansible-tmp-1499941715.51-229243879844145/docker_service.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/ec2-user/.ansible/tmp/ansible-tmp-1499941715.51-229243879844145/ /home/ec2-user/.ansible/tmp/ansible-tmp-1499941715.51-229243879844145/docker_service.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/ec2-user/.ansible/tmp/ansible-tmp-1499941715.51-229243879844145/docker_service.py; rm -rf "/home/ec2-user/.ansible/tmp/ansible-tmp-1499941715.51-229243879844145/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "api_version": null,
            "build": false,
            "cacert_path": null,
            "cert_path": null,
            "debug": false,
            "definition": {
                "services": {
                    "mongo": {
                        "expose": [
                            27017
                        ],
                        "image": "mongo:latest",
                        "working_dir": "/opt"
                    },
                    "tomee": {
                        "image": "tomee:latest",
                        "ports": [
                            "8080:8080"
                        ],
                        "working_dir": "/opt"
                    }
                },
                "version": "2",
                "volumes": {
                    "mongo_data": null
                }
            },
            "dependencies": true,
            "docker_host": null,
            "files": null,
            "filter_logger": false,
            "hostname_check": false,
            "key_path": null,
            "nocache": false,
            "project_name": "orson",
            "project_src": null,
            "pull": false,
            "recreate": "smart",
            "remove_images": null,
            "remove_orphans": false,
            "remove_volumes": false,
            "restarted": false,
            "scale": null,
            "services": null,
            "ssl_version": null,
            "state": "present",
            "stopped": false,
            "timeout": 10,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null
        }
    },
    "module_stderr": "",
    "module_stdout": "",
    "msg": "Error starting project __init__() got an unexpected keyword argument 'cpu_count'"
}
	to retry, use: --limit @/home/ec2-user/orson/orson.retry

PLAY RECAP **********************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

[ec2-user@ip-172-31-47-32 orson]$
```
