### ISSUE TITLE
ec2_vol is unable to create larger volumes from snapshots

### ISSUE THREAD

**Issue by mgiannos** [ansible/ansible#26687]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_vol

##### ANSIBLE VERSION
```
ansible 2.3.1.0

```

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
Ubuntu  16.04.2 but it's not relevant

##### SUMMARY
Creating a new larger EBS volume from a snapshot using ec2_vol module, produces an error:
"Cannot specify volume_size together with id or snapshot"

##### STEPS TO REPRODUCE
Use the following task to reproduce:

```yaml
- name: Create volume and restore from snapshot
  ec2_vol:
    volume_size: 10
    volume_type: standard
    instance: XXXXXXXX
    snapshot: XXXXXXXXXXXXX
    device_name: "/dev/sdX"
```

##### EXPECTED RESULTS
A new larger EBS volume should be created by the snapshot

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Cannot specify volume_size together with id or snapshot"}
--

##### SOLUTION
ansible/lib/ansible/modules/cloud/amazon/ec2_vol.py
lines 612, 613

ORIGINAL:
```
if volume_size and (id or snapshot):
        module.fail_json(msg="Cannot specify volume_size together with id or snapshot")
```
CHANGE TO:
```
if volume_size and id :
        module.fail_json(msg="Cannot specify volume_size together with id ")
```
