### ISSUE TITLE
"replace" module replaces wrong lines with regex containing `[^#]*`

### ISSUE THREAD

**Issue by gg7** [ansible/ansible#26712]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`modules/files/replace.py`

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/george/dev/my_repo/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Jul  6 2017, 21:50:05) [GCC 5.4.0]
```

I also tried reproducing with the `devel` branch but Ansible is completely broken:

```
ERROR! Unexpected Exception, this is probably a bug: unsupported operand type(s) for %: 'bytes' and 'bytes'
the full traceback was:

Traceback (most recent call last):
  File "/home/george/dev/external/ansible/bin/ansible", line 85, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/home/george/dev/external/ansible/lib/ansible/cli/__init__.py", line 38, in <module>
    from ansible.inventory.manager import InventoryManager
  File "/home/george/dev/external/ansible/lib/ansible/inventory/manager.py", line 44, in <module>
    IGNORED_EXTS = [b'%s$' % to_bytes(re.escape(x)) for x in C.INVENTORY_IGNORE_EXTS]
  File "/home/george/dev/external/ansible/lib/ansible/inventory/manager.py", line 44, in <listcomp>
    IGNORED_EXTS = [b'%s$' % to_bytes(re.escape(x)) for x in C.INVENTORY_IGNORE_EXTS]
TypeError: unsupported operand type(s) for %: 'bytes' and 'bytes'
```

##### CONFIGURATION

Problem occurs even without `ansible.cfg`.

##### OS / ENVIRONMENT

Gentoo Linux.

##### SUMMARY

The `replace` module replaces the wrong line(s).

##### STEPS TO REPRODUCE

This:

```yaml
- name: 'Comment out IPv6 entries in /etc/hosts'
  replace:
    path: /etc/hosts
    regexp: '^(.*::.*)$'
    replace: '# \1'
  become: yes
```

Leads to

```diff
--- before: /etc/hosts
+++ after: /etc/hosts
@@ -1,7 +1,7 @@
 127.0.0.1      localhost
-::1            localhost ip6-localhost ip6-loopback
-ff02::1                ip6-allnodes
-ff02::2                ip6-allrouters
+# ::1          localhost ip6-localhost ip6-loopback
+# ff02::1              ip6-allnodes
+# ff02::2              ip6-allrouters
```

Great. If I change it to

```yaml
- name: 'Comment out IPv6 entries in /etc/hosts'
  replace:
    path: /etc/hosts
    regexp: '^([^#]*::.*)$'
    replace: '# \1'
  become: yes
```

Instead I get

```diff
--- before: /etc/hosts
+++ after: /etc/hosts
@@ -1,4 +1,4 @@
-127.0.0.1      localhost
+# 127.0.0.1    localhost
 ::1            localhost ip6-localhost ip6-loopback
 ff02::1                ip6-allnodes
 ff02::2                ip6-allrouters
```

WTF?

`sed` likes my regular expression:

```bash
george@server:~$ diff -u /etc/hosts <(sed -r 's/^([^#]*::.*)$/# \1/' < /etc/hosts)
```
```diff
--- /etc/hosts  2017-07-06 18:50:01.558476824 +0000
+++ /dev/fd/63  2017-07-12 16:58:06.363344462 +0000
@@ -1,7 +1,7 @@
 127.0.0.1      localhost
-::1            localhost ip6-localhost ip6-loopback
-ff02::1                ip6-allnodes
-ff02::2                ip6-allrouters
+# ::1          localhost ip6-localhost ip6-loopback
+# ff02::1              ip6-allnodes
+# ff02::2              ip6-allrouters
```

##### EXPECTED RESULTS

I expect trivial perl-compatible regular expressions to work.

**Comment by ansibot** [comment]
cc @EvanK
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by EvanK** [comment]
This isn't an issue with the replace module, but rather with the intricacies of [python's regex engine](https://docs.python.org/2/library/re.html) when `re.MULTILINE` is switched on.

Specifically, it looks like the greedy matching of `[^#]*` is what's throwing you -- zero or more (and _as many as possible_) non-hash characters, _possibly including linebreaks_.

That's why it's commenting out the first entry (without the double colon), because it's literally matching `([^#]*::.*)` as:

```
127.0.0.1      localhost
::1            localhost ip6-localhost ip6-loopback
ff02::1                ip6-allnodes
ff02::2                ip6-allrouters
```

This instead should get you the desired result:

```yml
- name: 'Comment out IPv6 entries in /etc/hosts'
  replace:
    path: /etc/hosts
    regexp: '^([^#\n]*::.*)$'
    replace: '# \1'
  become: yes
```

@ansibot notabug
