### ISSUE TITLE
azure_rm_virtualmachine not create VM with multi NICs

### ISSUE THREAD

**Issue by bronco0** [ansible/ansible#26755]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION

```
2.3.1.0
```

##### CONFIGURATION

Nope

##### OS / ENVIRONMENT

Linux Ubuntu 16.10 Yaketty
Linux Debian 8 Jessy

##### SUMMARY

Is not possible to create a VM with more than one NIC.
The ```azure_rm_virtualmachine``` module return error.

##### STEPS TO REPRODUCE

1. Getting Started with Azure
Follow this page https://docs.ansible.com/ansible/guide_azure.html

2. Run this playbook 

```yaml
- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Create storage account
      azure_rm_storageaccount:
        resource_group: RGtest2
        name: 'jonstorage01'
        account_type: Standard_LRS
    
    - name: Create virtual network
      azure_rm_virtualnetwork:
        resource_group: RGtest2
        name: 'jon-vn'
        address_prefixes: "10.1.0.0/16"
    
    - name: Add subnet
      azure_rm_subnet:
        resource_group: RGtest2
        name: 'jon-subnet1'
        address_prefix: "10.1.0.0/24"
        virtual_network: 'jon-vn'

    - name: Add subnet2
      azure_rm_subnet:
        resource_group: RGtest2
        name: 'jon-subnet2'
        address_prefix: "10.1.1.0/24"
        virtual_network: 'jon-vn'

    - name: Create public ip
      azure_rm_publicipaddress:
        resource_group: RGtest2
        allocation_method: Static
        name: 'jon-public-ip'
    
    - name: Create security group that allows SSH
      azure_rm_securitygroup:
        resource_group: RGtest2
        name: 'jon-securitygroup-ssh'
        rules:
          - name: SSH
            protocol: Tcp
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound

    - name: Create security group all denied
      azure_rm_securitygroup:
        resource_group: RGtest2
        name: 'jon-securitygroup-alldenied'

    - name: Create NIC
      azure_rm_networkinterface:
        resource_group: RGtest2
        name: 'jon-nic1'
        virtual_network: 'jon-vn'
        subnet: 'jon-subnet1'
        public_ip_name: 'jon-public-ip'
        security_group: 'jon-securitygroup-ssh'

    - name: Create NIC02
      azure_rm_networkinterface:
        resource_group: RGtest2
        name: 'jon-nic2'
        virtual_network: 'jon-vn'
        subnet: 'jon-subnet2'
        public_ip: no
        security_group: 'jon-securitygroup-alldenied'

    - name: Create virtual machine
      azure_rm_virtualmachine:
        resource_group: RGtest2
        name: 'jon-vm'
        vm_size: Standard_D1
        storage_account: 'jonstorage01'
        storage_container: 'jon-vm'
        storage_blob: 'jon-vm01.vhd'
        admin_username: Ansible
        admin_password: Password99!
        network_interfaces: [ 'jon-nic1', 'jon-nic2' ]
        image:
          offer: Debian
          publisher: credativ
          sku: '8'
          version: latest
```

##### EXPECTED RESULTS

Create VM.

##### ACTUAL RESULTS

Error, the VM is not created.
Problem with Primary property for network interfaces.

```
TASK [Create virtual machine] ********************************************************************************************************************************
task path: /home/jon/test/azure/azure.yml:88
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jon
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "ad_user": null, 
            "admin_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "admin_username": "Ansible", 
            "allocated": true, 
            "append_tags": true, 
            "client_id": null, 
            "image": {
                "offer": "Debian", 
                "publisher": "credativ", 
                "sku": "8", 
                "version": "8.0.201706210"
            }, 
            "location": null, 
            "name": "jon-vm", 
            "network_interface_names": [
                "jon-nic1", 
                "jon-nic2"
            ], 
            "network_interfaces": [
                "jon-nic1", 
                "jon-nic2"
            ], 
            "open_ports": null, 
            "os_disk_caching": "ReadOnly", 
            "os_type": "Linux", 
            "password": null, 
            "profile": null, 
            "public_ip_allocation_method": "Static", 
            "remove_on_absent": [
                "all"
            ], 
            "resource_group": "RGtest2", 
            "restarted": false, 
            "secret": null, 
            "short_hostname": null, 
            "ssh_password_enabled": true, 
            "ssh_public_keys": null, 
            "started": true, 
            "state": "present", 
            "storage_account": "jonstorage01", 
            "storage_account_name": "jonstorage01", 
            "storage_blob": "jon-vm01.vhd", 
            "storage_blob_name": "jon-vm01.vhd", 
            "storage_container": "jon-vm", 
            "storage_container_name": "jon-vm", 
            "subnet_name": null, 
            "subscription_id": null, 
            "tags": null, 
            "tenant": null, 
            "virtual_network_name": null, 
            "vm_size": "Standard_D1"
        }
    }, 
    "msg": "Error creating or updating virtual machine jon-vm - Azure Error: NetworkInterfaceMustHavePrimaryPropertySet\nMessage: Network interface jon-nic1 must have Primary property set."
}
```

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating or updating virtual machine jon-vm - Azure Error: NetworkInterfaceMustHavePrimaryPropertySet\nMessage: Network interface jon-nic1 must have Primary property set."}
```
