### ISSUE TITLE
feature-request/Add 'remote_src' option to 'template' module

### ISSUE THREAD

**Issue by qnick** [ansible/ansible#26797]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
Files/Template

##### ANSIBLE VERSION

```
ansible 2.3.2.0 (stable-2.3 10aa164166) last updated 2017/06/29 18:32:01 (GMT +300)
  config file = /home/user/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
none
##### OS / ENVIRONMENT
N/A

##### SUMMARY
Lots of application, I install with ansible, are tar archives downloaded with 'maven_artifact' or 'unarchive' modules.
Some of these archives contains templates of configuration files in jinja2 format. I want to be able copy those files to application config directory with replacing jinja2 placeholders and without copying them to my local machine.
Now I have to use module 'replace', but I think it may be more native to use 'template' module with option 'remote_src=yes'

##### STEPS TO REPRODUCE

```yaml
- name: Get Snapshot app
  maven_artifact:
    group_id: "{{ component_group_id }}"
    artifact_id: "{{ component_artifact_id }}"
    repository_url: "{{ snapshot_repository }}"
    version: "{{ component_version }}"
    extension: 'tar.gz'
    dest: "{{ some_path }}.tgz"

- name: Extract tarball
  unarchive:
    remote_src: yes
    src: "{{ some_path }}.tgz"
    dest: "{{ app_directory }}"

- name: Copy configuration files
  template:
    remote_src: yes  # <- this is what I want
    src: "{{ app_directory }}/conf_templates/{{ item }}.j2"
    dest: "{{ app_directory }}/conf/{{ item }}"
  with_items: "{{ conf_files }}"
```

##### EXPECTED RESULTS

Files from directory 'conf_templates' should be copied to directory 'conf' with jinja2 filters applied

##### ACTUAL RESULTS
Now I can fetch those files to my local machine into temporary directory and then copy them back as templates, or use 'replace' module to replace jinja2 placeholders.
