### ISSUE TITLE
cloud/misc/virt.py does not support multiple args (e.g. state and autostart)

### ISSUE THREAD

**Issue by chrisbainbridge** [ansible/ansible#26791]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
cloud/misc/virt.py

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

"state" and "autostart" can not be specified at the same time, as in:
```
    virt:
      name: testvm
      autostart: true
      state: running
```

virt.py core(module) will return success if state is changed without executing the autostart option. I don't know if this is by design or a bug, but this behaviour is counter-intuitive and not documented. If this is desired behaviour it should at least be documented that args are mutually exclusive (even better, this could be enforced by raising an error in this case). If this is not desired behaviour then it is a bug.

##### STEPS TO REPRODUCE

Specify both autostart and state as above

Also specifying autostart alone does not work:

```yaml
  - name: Autostart
    virt:
      name: testvm
      autostart: true
```

results in "expected state or command parameter to be specified". The autostart code block in core() sets res['changed'] = True but then falls through to the fail case.

As a workaround, the following works:

```yaml
  - name: Autostart
    virt:
      name: testvm
      autostart: true
      command: status
```

##### EXPECTED RESULTS

- Ansible reports success so user would expect all args to be executed
- Expect to be able to specify multiple args unless otherwise documented

##### ACTUAL RESULTS

- Only state is changed, autostart is ignored but ansible returns success
- autostart only works if `command:` is also specified.
