### ISSUE TITLE
Blockinfile: insert[before|after] throws: cannot use a string  pattern on a bytes-like object

### ISSUE THREAD

**Issue by Tux12Fun** [ansible/ansible#26793]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

blockinfile.py

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

OS: Ubuntu 16.04 Xenial with Python3 (interpreter is set to Python3)

##### SUMMARY

Python3 changes the behavior for the search function as it seams. 

##### STEPS TO REPRODUCE

Only affects insertbefore / insertafter

```yaml
  - name: Insert new Prompt
    blockinfile:
      path:            /root/.bashrc
      insertafter:     '###_OLD-PROMPT_###.'
      block: |
               if [ "$USER" == "root" ]; then
                  PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;31m\]$(__cegit)\[\033[00m\]\$ '
               else
                  PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;31m\]$(__cegit)\[\033[00m\]\$ '
               fi
```

##### EXPECTED RESULTS

No error should occur. We are only replacing in a ASCII file a part.

##### ACTUAL RESULTS

Module crash

```
fatal: [******-wi1*********.local]: FAILED! => {"changed": false, "failed": true, "module_stderr": 
"Shared connection to ******-wi1.**********.local closed.\r\n", "module_stdout": 
"Traceback (most recent call last):\r\n  File \"/tmp/ansible_0s3yacif/ansible_module_blockinfile.py\", 
line 334, in <module>\r\n main()\r\n  File \"/tmp/ansible_0s3yacif/ansible_module_blockinfile.py\",
 line 284, in main\r\n    if insertre.search(line):\r\nTypeError: cannot use a string 
pattern on a bytes-like object\r\n", "msg": 
"MODULE FAILURE", "rc": 0}
```

##### BUGFIX
Caution, a developer should verify this, because I'am not firm with Python at all.
Neither with Python 2 / Python 3 differencees

```
FILE: ansible/lib/ansible/modules/files/blockinfile.py
                       Current Source Code                >>          Changed to
255
256    if insertafter not in (None, 'EOF'):
257        insertre = re.compile(insertafter)             >>        insertre = re.compile(b(insertafter))
258    elif insertbefore not in (None, 'BOF'):
259        insertre = re.compile(insertbefore)            >>        insertre = re.compile(b(insertbefore))
260    else:
261        insertre = None
262

```
