### ISSUE TITLE
complex arg format with file module

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#2680]
seb___
file: mode argument in a dictionary argument is a bit of a trap
toi has left IRC (Ping timeout: 255 seconds)
seb___
you have to specify it as a yaml string or else the yaml parser will hand it to the file: module as a int on which it will choke
seb___
id est AnsibleModule.set_mode_if_different() says 'mode needs to be something octalish'
seb___
that is if you are lucky and the base-10 number does not look like a base-8 number
seb___
else you end with surprising perms :-}
seb___
s/end/& up/

referreing to this (valid) syntax

file:
   path:  blarg
   mode: 0x755

complex_arg_hack stuff can probably be just be made to be avoided for new-style (ansible module common modules) to avoid much of this.

**Comment by stoned** [comment]
It is more about with_items than complex args.

Take for example the following playbook

```
---      
- name: octalish
  hosts: vagrant
  user: vagrant
  gather_facts: no
  tasks:
    - action: copy content=foo dest={{item.path}} mode={{item.mode}}
      with_items:
        - { path: /tmp/f, mode: 0644 }
        - { path: /tmp/g, mode: "0644" }
    - action: command ls -l /tmp/f /tmp/g
```

Here is what a verbose run would give

```
PLAY [octalish] *************************************************************** 

TASK: [copy content=foo dest={{item.path}} mode={{item.mode}}] **************** 
ok: [vagrant] => (item={'path': '/tmp/f', 'mode': 420}) => {"changed": false, "group": "vagrant", "item": {"mode": 420, "path": "/tmp/f"}, "mode": "0420", "owner": "vagrant", "path": "/tmp/f", "size": 3, "state": "file"}
ok: [vagrant] => (item={'path': '/tmp/g', 'mode': '0644'}) => {"changed": false, "group": "vagrant", "item": {"mode": "0644", "path": "/tmp/g"}, "mode": "0644", "owner": "vagrant", "path": "/tmp/g", "size": 3, "state": "file"}

TASK: [command ls -l /tmp/f /tmp/g] ******************************************* 
changed: [vagrant] => {"changed": true, "cmd": ["ls", "-l", "/tmp/f", "/tmp/g"], "delta": "0:00:00.002123", "end": "2013-04-14 20:51:22.035277", "rc": 0, "start": "2013-04-14 20:51:22.033154", "stderr": "", "stdout": "-r---w---- 1 vagrant vagrant 3 Apr 14 20:43 /tmp/f\n-rw-r--r-- 1 vagrant vagrant 3 Apr 14 20:43 /tmp/g"}

PLAY RECAP ******************************************************************** 
vagrant                    : ok=2    changed=1    unreachable=0    failed=0   
```

Compare the permission of /tmp/f and /tmp/g
