### ISSUE TITLE
New Module Idea: Support for Windows Event Log Management

### ISSUE THREAD

**Issue by andrewsaraceni** [ansible/ansible#26825]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
New module

##### ANSIBLE VERSION

```
Latest
```

##### SUMMARY
Currently, no module exists for managing Windows event logs, e.g. creating/removing event logs themselves, sources, specifying additional settings (retention, size, overflow).  PowerShell contains a series of `*-EventLog` cmdlets that provide this functionality, and then some:

```powershell
PS C:\Windows\system32> Get-Command *-EventLog | select name

Name
----
Clear-EventLog
Get-EventLog
Limit-EventLog
New-EventLog
Remove-EventLog
Show-EventLog
Write-EventLog
```

A `win_eventlog` module would offer the ability to manage these logs, event sources and associated settings, e.g.:

```yaml
- name: Create a new event log, source and set max size and retention days
  win_eventlog:
    name: NewLog
    state: present
    source: NewSource
    retention_days: 30
    maximum_size: 256mb

- name: Add a new source to an existing log
  win_eventlog:
    name: Application
    state: present
    source: NewSource

- name: Remove an event log
  win_eventlog:
    name: NewLog
    state: absent
```

This is something I'll actually need for some upcoming work I'm doing, so I'd be happy to take this on and open a PR when it's ready, if others think this would be a useful addition.

There's also the generation of event log entries themselves, which (if deemed useful), could maybe exist as its own module and a wrapper around `Write-EventLog` (`win_eventlog_entry`, perhaps?).  I could probably work on something for this as well if it was thought to be useful.
