### ISSUE TITLE
AWS_URL not currently compatible with dynamodb_table

### ISSUE THREAD

**Issue by lukemorton** [ansible/ansible#26875]
##### ISSUE TYPE

Feature Idea

##### COMPONENT NAME

dynamodb_table

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Aug 22 2015, 20:33:39) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.1)]
```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a

##### SUMMARY

AWS_URL not currently compatible with dynamodb_table

##### STEPS TO REPRODUCE

```yaml
- name: Migrate tables
  hosts: localhost
  connection: local
  vars:
    env: "{{ansible_env.MIGRATE_ENV}}"
  environment:
    AWS_REGION: "eu-west-1"
    AWS_URL: "http://locahost:8000"
  tasks:
  -  dynamodb_table:
       name: "page_releases_{{env}}"
       hash_key_name: id
       hash_key_type: STRING
       read_capacity: 1
       write_capacity: 1
       indexes:
        - name: uri-created_at
          type: global_all
          hash_key_name: uri
          range_key_name: created_at
          read_capacity: 1
          write_capacity: 1
```

##### EXPECTED RESULTS

It should connect to local dynamodb instance instead of AWS endpoint.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "hash_key_name": "id", "hash_key_type": "STRING", "indexes": [{"hash_key_name": "uri", "name": "uri-created_at", "range_key_name": "created_at", "read_capacity": 1, "type": "global_all", "write_capacity": 1}], "msg": "Failed to create/update dynamo table due to error: Traceback (most recent call last):\n  File \"/var/folders/18/5wdtlv6962j6414mh8__cskr0000gn/T/ansible_xZYL7s/ansible_module_dynamodb_table.py\", line 210, in create_or_update_dynamo_table\n    if dynamo_table_exists(table):\n  File \"/var/folders/18/5wdtlv6962j6414mh8__cskr0000gn/T/ansible_xZYL7s/ansible_module_dynamodb_table.py\", line 262, in dynamo_table_exists\n    raise e\nJSONResponseError: JSONResponseError: 400 Bad Request\n{u'message': u'The security token included in the request is invalid.', u'__type': u'com.amazon.coral.service#UnrecognizedClientException'}\n", "range_key_name": null, "range_key_type": "STRING", "read_capacity": 1, "region": null, "table_name": "page_releases_dev", "write_capacity": 1}
```

This happens because `ec2_url` is not used by connect_to_aws:

https://github.com/ansible/ansible/blob/stable-2.3/lib/ansible/module_utils/ec2.py#L256
