### ISSUE TITLE
win_stat: cannot access file because it is in use by another process

### ISSUE THREAD

**Issue by 4001982248998** [ansible/ansible#26885]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_stat

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul  2 2017, 22:24:59) [GCC 7.1.1 20170621]

```

##### CONFIGURATION
```
nocows = 1
```

##### OS / ENVIRONMENT
running Ansible from Arch Linux, managing Windows Server 2016

##### SUMMARY
win_stat fails to determine file existence, because a process is using it.

##### STEPS TO REPRODUCE
```
$ ansible win-host -i inventory/hosts -m win_stat -a "path=c:\\windows\\system32\\dhcp\\dhcp.mdb" --ask-pass
SSH password: 
win-host | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "#< CLIXML\r\nGet-FileHash : Die Datei \"C:\\windows\\system32\\dhcp\\dhcp.mdb\" kann nicht gelesen werden: Der Prozess kann nicht auf die \r\nDatei \"C:\\windows\\system32\\dhcp\\dhcp.mdb\" zugreifen, da sie von einem anderen Prozess verwendet wird..\r\nIn Zeile:303 Zeichen:25\r\n+             $raw_hash = Get-FileHash $path -Algorithm $algorithm\r\n+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : ReadError: (C:\\windows\\system32\\dhcp\\dhcp.mdb:PSObject) [Write-Error], WriteErrorExcepti \r\n   on\r\n    + FullyQualifiedErrorId : FileReadError,Get-FileHash\r\n \r\nDie Eigenschaft \"Hash\" wurde für dieses Objekt nicht gefunden. Vergewissern Sie sich, dass die Eigenschaft vorhanden \r\nist.\r\nIn Zeile:304 Zeichen:13\r\n+             $hash = $raw_hash.Hash.ToLower()\r\n+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : PropertyNotFoundStrict\r\n \r\n\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Module werden für erstmalige Verwendung vorbereitet.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

##### EXPECTED RESULTS
ansible should determine if the file exists (and possibly other information about it)

##### ACTUAL RESULTS
ansible exits with MODULE FAILURE. See above

**Comment by ansibot** [comment]
cc @cchurch @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
I've been able to reproduce this on a Server 2012 R2 box with the following playbook

```
- name: adhoc stuff
  hosts: 2012R2
  vars:
    test_win_stat_output_file: C:\temp\file

  tasks:
  - name: ensure file is deleted before test
    win_file:
      path: '{{test_win_stat_output_file}}'
      state: absent
  
  - name: create very large file
    win_command: fsutil file createnew {{test_win_stat_output_file}} 1073741824

  - name: write file for 10 seconds
    win_command: powershell.exe "$start = Get-Date; while (((Get-Date) - $start).TotalSeconds -lt 10) { Add-Content -Path '{{test_win_stat_output_file}}' -Value 'a' }"
    async: 30
    poll: 0

  - win_stat:
      path: '{{test_win_stat_output_file}}'
```

The issue is that when win_stat goes to get the hash of a large file which is in use it will throw this error. There are 2 ways in which we can overcome this issue;

* set `get_checksum` and `get_md5` to false so we don't get the hash
* enclose the hash functions in a try/catch and return null if this fails (and set a warning)

I would go for the former as if a user doesn't care about the checksum they would set those flags to false.

@4001982248998 are you able to try running this with `get_checksum` and `get_md5` to `False` and let us know how it goes?

@nitzmahone @dagwieers @jhawkesworth thoughts on the 2 options.
