### ISSUE TITLE
parted module doesn't check if it needs to modify the system state, and doesn't unmount partitions

### ISSUE THREAD

**Issue by robomancer-or** [ansible/ansible#26905]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
parted

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/.../ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
[defaults]
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
ask_sudo_pass = True
command_warnings = True
error_on_undefined_vars = True
inventory = hosts

##### OS / ENVIRONMENT
Everything running on Ubuntu LTS, the servers are running server edition, my laptop is the regular one.

##### SUMMARY
Parted fails when the partitions are already mounted, even if nothing needs to happen.

##### STEPS TO REPRODUCE
Run the following against some hosts two times, it will fail the second time because sdb1 and sdc1 will be mounted.

```yaml
    - parted:
        device: "/dev/{{item}}"
        label: gpt
        name: "{{item}}Part"
        number: 1
        state: present
      with_items:
        - sdb
        - sdc
    - filesystem:
        fstype: ext4
        dev: "/dev/{{item}}1"
      with_items:
        - sdb
        - sdc
    - mount:
        path: "/mnt/{{item}}1/"
        src: "/dev/{{item}}1"
        fstype: ext4
        opts: noatime
        state: mounted
      with_items:
        - sdb
        - sdc
```

##### EXPECTED RESULTS
parted should succeed both times (it should be idempotent...), the first time by partitioning the disk (unmounting only if necessary), and the second by noticing that it is already partitioned correctly and then succeeding by doing nothing.

##### ACTUAL RESULTS

It prints the following for each disk on each server.

```
failed: [rs0.internal] (item=sdc) => {
    "err": "Error: Partition(s) on /dev/sdc are being used.\n", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "align": "optimal", 
            "device": "/dev/sdc", 
            "flags": null, 
            "label": "gpt", 
            "name": "sdcPart", 
            "number": 1, 
            "part_end": "100%", 
            "part_start": "0%", 
            "part_type": "primary", 
            "state": "present", 
            "unit": "KiB"
        }
    }, 
    "item": "sdc", 
    "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/sdc -- unit KiB mklabel gpt", 
    "out": "", 
    "rc": 1
}
...
```

**Comment by ansibot** [comment]
cc @ColOfAbRiX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
This might be related to https://github.com/ansible/ansible/issues/22996  ?

@robomancer-or If possible, could you test this with the devel version of ansible? It has a couple of 
idempotence related fixes for parted that were not in 2.3.1

**Comment by robomancer-or** [comment]
Do you happen to have a containerized devel version I could use for the test?  I'm not feeling particularly excited about mucking about installing and uninstalling competing versions of stuff I depend on.

**Comment by jrosengren** [comment]
I just happened to hit this same problem today, using 2.3.1.0 on MacOS:

$ ansible --version
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 22 2016, 09:52:19) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

**Comment by danielkza** [comment]
Still present on 2.4.

task:

```
    - name: Cassandra | Create commitlog partition
      parted:
        device: "{{ cassandra_storage_commitlog_dev }}"
        label: gpt
        number: 1
        state: present
        align: optimal
```

Which was previously used to create a single partition encompassing a whole GPT-labeld disk. Running it twice produces:

```
fatal: [cassandra-test-1]: FAILED! => {"changed": false, "err": "Error: Partition(s) on /dev/xvdc are being used.\n", "failed": true, "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/xvdc -- unit KiB mklabel gpt", "out": "", "rc": 1}
```

**Comment by achamayou** [comment]
Still present in 2.7.10

task:

```
- name: Partition
  parted:
    device: /dev/sdc
    number: 1
    state: present
  become: yes
```

Produces this on the second and subsequent runs:

```
FAILED! => {"changed": false, "err": "Error: Partition(s) on /dev/sdc are being used.\n", "msg": "Error while running parted script: /sbin/parted -s -m -a optimal /dev/sdc -- unit KiB mklabel msdos", "out": "", "rc": 1}
```
