### ISSUE TITLE
mysql_db defaults overriding config_file

### ISSUE THREAD

**Issue by dylanjbarth** [ansible/ansible#26919]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
`mysql_db`

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.0.0
  config file = /Users/dylan/projects/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.11 (default, Jun 17 2016, 20:01:51) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a

##### SUMMARY

.my.cnf is being overridden by defaults set by the module. specifically if a host is specified in the .my.cnf and not in the task, it seems to be overridden with `localhost`

##### STEPS TO REPRODUCE

I'm trying to dump a database with the following task: 

```yaml
- name: Dump databases
    mysql_db:
      state: dump
      db: api_db
      config_file: /home/dylan/.my.cnf
      target: /tmp/api_db.sql.gz
```

The .my.cnf provides the mysql user, password, and remote host url. However, it appears to be overridden by the default value set by login_host. When I don't explicitly set login_host (even though it's defined properly in the .my.cnf), I get `Cannot dump database api_db - not found` however if I explicitly set it in the task, eg
```yaml
- name: Dump databases
    mysql_db:
      state: dump
      db: api_db
      login_host: ........rds.amazonaws.com
      config_file: /home/dylan/.my.cnf
      target: /tmp/api_db.sql.gz
```
It completes successfully.

I would expect that the config file would override the defaults of the module instead of the other way around. 

Let me know if you can confirm this issue, if others agree I'm happy to dig into the code and submit a PR.
