### ISSUE TITLE
Implicit localhost does not add localhost variables to hostvars

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#26916]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
implicit localhost

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/nikos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul  2 2017, 22:24:59) [GCC 7.1.1 20170621]
```

##### CONFIGURATION
None custom

##### OS / ENVIRONMENT
Running on Arch linux. Remote is Ubuntu 16.04.2

##### SUMMARY
When using implicit localhost, any variable specific to the localhost is not available in the hostvars hash.

##### STEPS TO REPRODUCE
Example inventory file:

```ini
vpn ansible_ssh_host=1.2.3.4 ansible_ssh_port=22 ansible_ssh_user='qwerty' ansible_ssh_private_key_file='ssh.key'
# localhost ansible_connection=local
```

playbook.yml
```yaml
- hosts: localhost
  tasks:
 - name: register
   set_fact:
     network_name: mynet

- hosts: vpn
  connection: local
  post_tasks:
  - name: fff
      debug:
      msg: "{{hostvars}}"
    delegate_to: localhost
```
Run `ansible -i inventory_file playbook.yml`  both with the localhost commented out and uncommented out.

##### EXPECTED RESULTS
A `localhost` key should be included in the output, together with all the variables specific to the localhost (eg network_name) 

##### ACTUAL RESULTS
Only the vpn host is included in the output.
