### ISSUE TITLE
Can I send variables to the .j2 file?

### ISSUE THREAD

**Issue by xieguangtai** [ansible/ansible#26977]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

task
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I wonder whether it is possible for me to send variables to the .j2 file so I can adjust it dynamically.
##### STEPS TO REPRODUCE

For example

playbook.yml
```yaml
---
- name: test
  hosts: all
  template:
      src: /tmp/example.j2
      dest: /opt/example.conf
      vars: 
          ips: 
            - 1.1.1.1
            - 2.2.2.2
```
And the example.j2
```yaml
...
allowed_ip_address {
{% for ip in sended['ips'] %}
    ip;    
{% endfor %}
}
...
```
And if I can use the "extend" function for list in jinja such as in python, it would be better.
```yaml
foo:
   ips:
      - 10.10.10.1
      - 10.10.10.2
bar:
   ips:
      - 10.10.20.1
      - 10.10.20.2
```
When there is another guy foo_bar joined, I can easily add its ips to the allowed_ip_address.
If I generate each file for foo, bar and foo_bar, and then use assembly module to generate a new file,
things will be like this:
```
allowed_ip_address {
    10.10.10.1;
    10.10.10.1;
}
allowed_ip_address {
    10.10.20.1;
    10.10.20.2;
}
allowed_ip_address {
    10.10.30.1;
    10.10.30.2;
}
```
But I want the file to be like this:
```
allowed_ip_address {
    10.10.10.1;
    10.10.10.1;
    10.10.20.1;
    10.10.20.2;
    10.10.30.1;
    10.10.30.2;
}
```

Can this be realized now in ansible? Can anyone tell me? Thanks!

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

I'm reffering you to the lists because this already works, you can add `vars:` to any task, including template. I recommend asking there before you file a feature request.
```yaml
- name: test
  hosts: all
  template:
      src: /tmp/example.j2
      dest: /opt/example.conf
  vars: 
          ips: 
            - 1.1.1.1
            - 2.2.2.2
```

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
