### ISSUE TITLE
Unhandled 'An error occured waiting for the image to become available' in ansible_module_ec2_ami_copy.py

### ISSUE THREAD

**Issue by piotrkarbowski-ciklum** [ansible/ansible#26971]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`ansible_module_ec2_ami_copy.py`

##### ANSIBLE VERSION
```
ansible==2.3.1.0 
```

##### OS / ENVIRONMENT

Linux, AWS CodeBuild

##### SUMMARY

Today, while executing a task with `ec2_ami_copy:` ansible execution crashed with:

    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'WaiterError' object has no attribute 'reason'
    /aws/codebuild/core-build-ami c6b4c0b1-5035-4833-8456-f486d8f78e27 fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):
      File \"/tmp/ansible_wM5kH0/ansible_module_ec2_ami_copy.py\", line 226, in <module>
        main()
      File \"/tmp/ansible_wM5kH0/ansible_module_ec2_ami_copy.py\", line 222, in main
    copy_image(module, ec2)
      File \"/tmp/ansible_wM5kH0/ansible_module_ec2_ami_copy.py\", line 183, in copy_image
    module.fail_json(msg='An error occured waiting for the image to become available. (%s)' %  we.reason)
    AttributeError: 'WaiterError' object has no attribute 'reason'
    ", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

##### STEPS TO REPRODUCE

Occasional 

```yaml
  - name: copy image
    ec2_ami_copy:
      name: tmp-encrypted-{{ ubuntu_ami_result.results[0].name }}-{{ ansible_date_time.iso8601_basic_short }}
      source_region: "{{ aws_region }}"
      region: "{{ aws_region }}"
      source_image_id: "{{ ubuntu_ami_result.results[0].ami_id }}"
      encrypted: yes
      wait: yes
      tags:
        terminate_after: 1h
    register: image_id
```

##### EXPECTED RESULTS

Going forward to next task.

##### ACTUAL RESULTS

Not handled error resulting in nasty crash

CC @adamchainz
