### ISSUE TITLE
New-style variables don't work with when_unset/when_set

### ISSUE THREAD

**Issue by nigma** [ansible/ansible#2699]
Test case:

``` yml
- hosts: all

  vars:
    hostname: hello

  tasks:
    - fail: msg="this action shouldn't run"
      when_unset: "{{ hostname }}"

    - fail: msg="this action shouldn't run"
      when_set: "{{ hostname_xyz }}"
```

Both of these checks raise fatal errors.

```
Conditional expression must evaluate to True or False: hello
Conditional expression must evaluate to True or False: {{hostname_xyz}}
```

The old `when_unset: $hostname_xyz` works as expected. Is there any other recommended way of checking for defined/undefined variables using the new syntax?
