### ISSUE TITLE
nxos_snmp_location/contact modules always give changed

### ISSUE THREAD

**Issue by ejade9** [ansible/ansible#27010]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_snmp_location
- nxos_snmp_contact

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/ejade/.ansible.cfg
  configured module search path = [u'/home/ejade/napalm-ansible/library', u'/home/ejade/ansible-extras/ntc-ansible/library']
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

nxos_snmp_location and nxos_snmp_contact always give changed when there's any space in input
##### STEPS TO REPRODUCE

Run first playbook twice then run the second playbook twice.

```yaml
#First playbook
---
- hosts: nxos
  tasks:
    - nxos_snmp_location:
        provider: "{{ provider_ssh }}"
        location: "xx x"

    - nxos_snmp_contact:
        provider: "{{ provider_ssh }}"
        contact : "x xx"


#Second playbook
---
- hosts: nxos
  tasks:
    - nxos_snmp_location:
        provider: "{{ provider_ssh }}"
        location: "xxx"

    - nxos_snmp_contact:
        provider: "{{ provider_ssh }}"
        contact : "xxx"

```

##### EXPECTED RESULTS

For both playbook, the second time should give
PLAY [nxos] ********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [nxos2]
ok: [nxos1]

TASK [nxos_snmp_location] ******************************************************
ok: [nxos1]
ok: [nxos2]

TASK [nxos_snmp_contact] *******************************************************
ok: [nxos2]
ok: [nxos1]

PLAY RECAP *********************************************************************
nxos1                      : ok=3    changed=0    unreachable=0    failed=0
nxos2                      : ok=3    changed=0    unreachable=0    failed=0

Since after first time execution it is already set.
##### ACTUAL RESULTS

For the first playbook with space, it still gives
PLAY [nxos] ********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [nxos2]
ok: [nxos1]

TASK [nxos_snmp_location] ******************************************************
changed: [nxos1]
changed: [nxos2]

TASK [nxos_snmp_contact] *******************************************************
changed: [nxos1]
changed: [nxos2]

PLAY RECAP *********************************************************************
nxos1                      : ok=3    changed=2    unreachable=0    failed=0
nxos2                      : ok=3    changed=2    unreachable=0    failed=0
in the second run.
For the second playbook without spaces, it gives output as expected in the second run.
This is just a simple case, more tests have been done to prove the bug lies in whether there is any space in input.

```

```
