### ISSUE TITLE
virt_net silently ignores autostart parameter if command is specified

### ISSUE THREAD

**Issue by pdreker** [ansible/ansible#27064]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
virt_net

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /Users/pd/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Mar 15 2017, 15:15:48) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
[defaults]
roles_path = /Users/pd/Ansible/Roles
library = /Users/pd/Ansible/Modules

[privilege_escalation]
become = True
become_method = sudo

##### OS / ENVIRONMENT
Controller: MacOS (Darwin ghost.nbg.teamix.net 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64)
Target: Ubuntu 16.04

##### SUMMARY
When e.g. defining a network using XML the autostart parameter is silently ignored.

##### STEPS TO REPRODUCE
```yaml
- name: Create Libvirt Networks
  virt_net:
    autostart: yes
    state: active
    command: define
    name: somenetwork
    xml: '{{ lookup("template", "libvirt-net-bridged.xml.j2") }}'
```

##### EXPECTED RESULTS
The network is created and autostart is set to true.

##### ACTUAL RESULTS
The network is created, but autostart is set to false/no (as per the default). When following up with a second task, which only sets autostart the intended result is achieved:
```
- name: Autostart all Libvirt Networks
  virt_net:
    autostart: yes
    name: somenetwork
```

It seems like all codepaths from ansible/lib/ansible/modules/cloud/misc/virt_net.py starting from line 545 ("if command:") actually exit/fail/return from within the "if" block, when a command is specified, so that the following "if autostart:" has no effect, when a command is specified (Code is never reached).

This behaviour should either be corrected (evaluate and act on "autostart" regardless if a command is specified) or it should be documented. I strongly prefer the former.
