### ISSUE TITLE
unarchive module feature request: allow to extract specific files

### ISSUE THREAD

**Issue by shankerrhce** [ansible/ansible#27081]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

unarchive module
##### ANSIBLE VERSION

```
ansible 2.3.1
```

##### SUMMARY
need a feature to extract single/multiple files from .zip file .  current unarchive module will unzip all the files to the destination folder

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @dagwieers @pileofrogs
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cognifloyd** [comment]
This was requested previously in ansible/ansible-modules-core#2037, but that request was "solved" with a blacklist filter (exclude certain files from extraction) instead of a whitelist filter (only extract these files) in ansible/ansible-modules-core#3307.

I would also like the ability to specify a single file that should be extracted instead of blacklisting everything that should not be extracted. Perhaps the option could be called `include` to mirror the `exclude` option.

**Comment by dagwieers** [comment]
Yeah, so the whole problem here is that we are using `unzip` and `gtar` underneath and this is all too fragile and possibly problematic and we really really would like to go to a pure-python implementation.

I don't mind if people want to contribute this, and then support it. But I think all this effort would be better spent on writing a pure-python **uncompress** alternative module.

needs_contributor

**Comment by zystem** [comment]
Workaround is to use extra_opts
      extra_opts:
      - --wildcards
      - '*/helm'
Example
  - name: helm
    unarchive:
      src: https://storage.googleapis.com/kubernetes-helm/helm-v2.14.0-linux-amd64.tar.gz
      dest: /usr/local/bin
      extra_opts:
      - --strip=1
      - --wildcards
      - '*/helm'
      remote_src: True

**Comment by onitake** [comment]
Possible duplicate of #16130

**Comment by yurtesen** [comment]
@zystem what if the file is a zip file? unzip does not have such options?

**Comment by onitake** [comment]
@yurtesen You don't need to special options to specify the files to extract. Just list them as additional arguments.

**Comment by blackwood821** [comment]
Any update on this? Looking to extract specific files from a jar/zip.

**Comment by ossm1db** [comment]
@zsystem @onitake 

Adding the filename as an additional argument does not work:

`fatal: [xxxxxxxx]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (unarchive) module: extra_ops Supported parameters include: attributes, backup, content, creates, delimiter, dest, directory_mode, exclude, extra_opts, follow, force, group, keep_newer, list_files, mode, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate_certs"}`

with

```
- name: extract
  unarchive:
    remote_src: yes
    src: /tmp/files.zip
    dest: /tmp
    extra_ops:
    - 'myscript.sh'
```

We need a solution for .zip files please.

**Comment by zystem** [comment]
You write "extra_ops" when must to be "extra_opts"

**Comment by ossm1db** [comment]
@zsystem You are correct, I apologize for the typo. However, it still does not work:

`fatal: [xxxxxxxx]: FAILED! => {"changed": false, "dest": "/tmp", "extract_results": {"cmd": ["/usr/bin/unzip", "-o", "myscript.sh", "/tmp/files.zip", "-d", "/tmp"], "err": "unzip:  cannot find or open myscript.sh, myscript.sh.zip or myscript.sh.ZIP.\n", "out": "", "rc": 9}, "gid": 0, "group": "root", "handler": "ZipArchive", "mode": "01777", "msg": "failed to unpack /tmp/files.zip to /tmp", "owner": "root", "secontext": "system_u:object_r:tmp_t:s0", "size": 4096, "src": "/tmp/files.zip", "state": "directory", "uid": 0}`

It appears that the extra options are passed to unzip before the module arguments, so it thinks that the filename to extract is actually the .zip file.

`["/usr/bin/unzip", "-o", "myscript.sh", "/tmp/files.zip", "-d", "/tmp"]`

which is interpreted according to unzip usage:

`Usage: unzip [-Z] [-opts[modifiers]] file[.zip] [list] [-x xlist] [-d exdir]`

There is an ugly hack to work around this:
```
unarchive:
  remote_src: yes
  src: '/tmp/files.zip'
  dest: /tmp
  owner: 'devops.ansible'
  group: 'domain users'
  extra_opts:
  - '-q'
  - '/tmp/files.zip'
  - 'myscript.sh'
```

It is necessary to repeat the .zip filename in the extra_opts along with '-q' for it to ignore errors. This results in the unzip command:

`"/usr/bin/unzip", "-o", "-q", "/tmp/files.zip", "myscript.sh", "/tmp/files.zip", "-d", "/tmp"`

The three extra_opts are placed before the module arguments, with the .zip file before the filename to extract. The .zip file argument placed by the module is then safely ignored by '-q'.

**Comment by fgimian** [comment]
I opted to use the `unzip` tool with the `shell` module.  Of course this did add a lot of extra steps because I had a remote source.

This does work perfectly but isn't quite as elegant as I would like 😄 

```yaml
---
- hosts: localhost
  connection: local
  tasks:
    # Currently there's no way to check that a shell command creates multiple files,
    # see https://github.com/ansible/ansible/issues/34454
    - name: Check whether the files exist
      stat:
        path: '{{ item }}'
      loop:
        - ~/.local/share/fonts/SourceCodePro-BlackIt.otf
        - ~/.local/share/fonts/SourceCodePro-Black.otf
        - ~/.local/share/fonts/SourceCodePro-BoldIt.otf
        - ~/.local/share/fonts/SourceCodePro-Bold.otf
        - ~/.local/share/fonts/SourceCodePro-ExtraLightIt.otf
        - ~/.local/share/fonts/SourceCodePro-ExtraLight.otf
        - ~/.local/share/fonts/SourceCodePro-It.otf
        - ~/.local/share/fonts/SourceCodePro-LightIt.otf
        - ~/.local/share/fonts/SourceCodePro-Light.otf
        - ~/.local/share/fonts/SourceCodePro-MediumIt.otf
        - ~/.local/share/fonts/SourceCodePro-Medium.otf
        - ~/.local/share/fonts/SourceCodePro-Regular.otf
        - ~/.local/share/fonts/SourceCodePro-SemiboldIt.otf
        - ~/.local/share/fonts/SourceCodePro-Semibold.otf
      changed_when: False
      register: font_files_stat

    # Sadly there's no way to have a whitelist with the unarchive module, so we must use the unzip
    # command directly, see https://github.com/ansible/ansible/issues/27081
    - name: Install the Source Code Pro font
      block:
        - name: Create a temporary directory to dowlnoad Source Code Pro to
          tempfile:
            state: directory
          changed_when: False
          register: font_dowload_tempdir

        - name: Dowload the Source Code Pro font archive to the temporary directory
          get_url:
            url: https://github.com/adobe-fonts/source-code-pro/releases/download/2.030R-ro%2F1.050R-it/source-code-pro-2.030R-ro-1.050R-it.zip
            dest: '{{ font_dowload_tempdir.path }}/source-code-pro-2.030R-ro-1.050R-it.zip'
          changed_when: False

        - name: Install the Source Code Pro font
          shell: 'unzip -j "{{ font_dowload_tempdir.path }}/source-code-pro-2.030R-ro-1.050R-it.zip" *.otf -d ~/.local/share/fonts'
          args:
            warn: no
      always:
        - name: Clean up the Source Code Pro temporary download directory
          file:
            path: '{{ font_dowload_tempdir.path }}'
            state: absent
          changed_when: False
      when: font_files_stat.results | rejectattr('stat.exists') | list
```
