### ISSUE TITLE
Cannot add ssh keys into image as buildargs

### ISSUE THREAD

**Issue by Demaunt** [ansible/ansible#27098]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

 - docker_image

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
##### CONFIGURATION

- https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg

##### OS / ENVIRONMENT

 - Ubuntu:16.04

##### SUMMARY

- Container built from image does not have ssh_keys, passed to image as build args in playbook

##### STEPS TO REPRODUCE

- Create Dockerfile like this:
```
FROM ubuntu:16.04

ARG ssh_prv_key
ARG ssh_pub_key

RUN apt-get update && \
    apt-get install -y language-pack-en-base && \
    export LC_ALL=en_US.UTF-8 && \
    export LANG=en_US.UTF-8 && \
    apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:ondrej/php

RUN apt-get update && \
    apt-get install -y \
        git \
        openssh-client \
        curl \
        php7.0-cli \
        php7.0-mcrypt \
        php7.0-sqlite \
        php7.0-mysqlnd \
        php7.0-json \
        php7.0-gd \
        php7.0-curl \
        php7.0-mbstring \
        php7.0-dom \
        php7.0-imagick

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Authorize SSH Host
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan github.com > /root/.ssh/known_hosts

# Add the keys and set permissions
RUN echo "$ssh_prv_key" > /root/.ssh/id_rsa && \
    echo "$ssh_pub_key" > /root/.ssh/id_rsa.pub && \
    chmod 600 /root/.ssh/id_rsa && \
    chmod 600 /root/.ssh/id_rsa.pub

WORKDIR /app/

CMD git clone PUT_YOUR_REPO_HERO && \ 
    composer install --no-scripts -d /app/wapclick && \
    chown -R www-data:www-data /app/ && \
    RUN chmod -R 775 /app/wapclick/storage

# BUILD LIKE THIS: $ docker build -t example --build-arg ssh_prv_key="$(cat ~/.ssh/id_rsa)" --build-arg ssh_pub_key="$(cat ~/.ssh/id_rsa.pub)" .
```
Create playbook:
```yaml
---
- hosts: localhost
  environment:
    PYTHONPATH: /usr/local/lib/python2.7/site-packages/

  tasks:
  - name: create image from Dockerfile
    docker_image:
      path: /home/demaunt/Jun/dock_click
      dockerfile: biba.dockerfile
      name: myimage
      buildargs: 
        ssh_pub_key: 
            command: "cat ~/.ssh/id_rsa.pub"
        ssh_prv_key:
            command: "cat ~/.ssh/id_rsa"
```
Create image:
`ansible-playbook bibansible.yml`

Run the container: 
`$docker container --rm -v$(pwd):/app/ myimage`

##### EXPECTED RESULTS

When container is created it starts pulling git repo and updates it using composer

##### ACTUAL RESULTS

Permission is denied, I think buildargs are not working while creating image process, they remain empty.

```
Cloning into 'wapclick'...
key_load_public: invalid format
Warning: Permanently added the RSA host key for IP address 'some_ip' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.
```
