### ISSUE TITLE
s3_bucket for minio

### ISSUE THREAD

**Issue by varpa89** [ansible/ansible#27099]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

s3_bucket
##### ANSIBLE VERSION

```
2.3.1.0
```

##### CONFIGURATION

minio/minio:RELEASE.2017-05-05T01-14-51Z

##### OS / ENVIRONMENT

macOS Sierra
##### SUMMARY

I'm trying to use s3_bucket for Minio. I'm available to create a bucket only if set parameter ceph:true
But parameter policy always ignore
##### STEPS TO REPRODUCE

```yaml
    - name: create bucket
      s3_bucket:
        name: mys3bucket10
        s3_url: http://{{ansible_default_ipv4.address}}:28653
        aws_access_key: access
        aws_secret_key: secret
        ceph: true
        state: present
        policy: "{{ lookup('template','./policy.json.j2') }}"
      register: termination_status
```

##### EXPECTED RESULTS

Bucket has policy from policy.json file
##### ACTUAL RESULTS

There is no any policy on created bucket

If parameter ceph not using
```
TASK [create bucket] ***********************************************************
fatal: [localabm]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to localabm closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_3eilMm/ansible_module_s3_bucket.py\", line 443, in <module>\r\n    main()\r\n  File \"/tmp/ansible_3eilMm/ansible_module_s3_bucket.py\", line 438, in main\r\n    create_or_update_bucket(connection, module, location, flavour=flavour)\r\n  File \"/tmp/ansible_3eilMm/ansible_module_s3_bucket.py\", line 323, in create_or_update_bucket\r\n    _create_or_update_bucket(connection, module, location)\r\n  File \"/tmp/ansible_3eilMm/ansible_module_s3_bucket.py\", line 167, in _create_or_update_bucket\r\n    bucket = connection.get_bucket(name)\r\n  File \"/usr/lib/python2.7/site-packages/boto-2.48.0-py2.7.egg/boto/s3/connection.py\", line 509, in get_bucket\r\n    return self.head_bucket(bucket_name, headers=headers)\r\n  File \"/usr/lib/python2.7/site-packages/boto-2.48.0-py2.7.egg/boto/s3/connection.py\", line 528, in head_bucket\r\n    response = self.make_request('HEAD', bucket_name, headers=headers)\r\n  File \"/usr/lib/python2.7/site-packages/boto-2.48.0-py2.7.egg/boto/s3/connection.py\", line 671, in make_request\r\n    retry_handler=retry_handler\r\n  File \"/usr/lib/python2.7/site-packages/boto-2.48.0-py2.7.egg/boto/connection.py\", line 1071, in make_request\r\n    retry_handler=retry_handler)\r\n  File \"/usr/lib/python2.7/site-packages/boto-2.48.0-py2.7.egg/boto/connection.py\", line 1030, in _mexe\r\n    raise ex\r\nsocket.error: [Errno 111] Connection refused\r\n", "msg": "MODULE FAILURE", "rc": 0}

```
