### ISSUE TITLE
when_string evaluation failing

### ISSUE THREAD

**Issue by rrtj3** [ansible/ansible#2710]
When testing a new version of ansible:

ansible --version
ansible 1.2 (devel cce2cad8dc) last updated 2013/04/16 18:59:16 (GMT -1000)

I get this error:

fatal: [127.0.0.1] => Conditional expression must evaluate to True or False:

when using this when_string evaluation:

``` yaml
when_string: '"COW" in "${webpage.content}"'
```

This worked fine in earlier version of ansible. I do realize there is a better way to do this now.

**Comment by mpdehaan** [comment]
Thanks for filing the ticket, I will check this out now.

**Comment by mpdehaan** [comment]
Ok so the following test works for me:

```
---
- hosts: all

  vars:
     webpage:
          content: 'Animal that says moo is a COW.  Quack.'

  tasks:
    - shell: echo foo
      when_string: '"COW" in "${webpage.content}"'
    - shell: echo bar
      when_string: '"DUCK" in "${webpage.content}"'
```

Is your 1.2 branch very very up to date and does the above also work for you?

**Comment by rrtj3** [comment]
My ansible version was a clone from last night. The above does work correctly for me. So I'm guessing it has something to do with the odd characters in the webpage contents. For example, this fails with the same error:

``` yaml
---
- hosts: all

  tasks:
    - name: Check that a page returns a status 200 and make the next task depend on something in the page contents. 
      uri: url=http://www.google.com method=GET return_content=yes 
      register: webpage 

    - name: Run uptime if the webpage contains the word COW. 
      command: /usr/bin/uptime
      when_string: '"COW" in "${webpage.content}"'

```
