### ISSUE TITLE
maven_artifact doesn't read the proper snapshotVersion of the artifact

### ISSUE THREAD

**Issue by ericcitaire** [ansible/ansible#27102]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### SUMMARY

Given multiple Maven artifacts with same `groupId` and `artifactId` but different `extension` and/or `classifier`, Ansible doesn't read `snapshotVersions` in `maven-metadata.xml`.

##### STEPS TO REPRODUCE

Create a dummy Maven repository with dummy artifacts `foo:bar:1.2.3-SNAPSHOT:pom`, `foo:bar:1.2.3-SNAPSHOT:war` and `foo:bar:1.2.3-SNAPSHOT:properties`.
```
mkdir -p foo/bar/1.2.3-SNAPSHOT

echo "<?xml version="1.0" encoding="UTF-8"?>
<metadata modelVersion="1.1.0">
  <groupId>foo</groupId>
  <artifactId>bar</artifactId>
  <version>1.2.3-SNAPSHOT</version>
  <versioning>
    <snapshot>
      <timestamp>20170719.155215</timestamp>
      <buildNumber>9</buildNumber>
    </snapshot>
    <lastUpdated>20170720025620</lastUpdated>
    <snapshotVersions>
      <snapshotVersion>
        <extension>pom</extension>
        <value>1.2.3-20170719.155215-10</value>
        <updated>20170719155215</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>war</extension>
        <value>1.2.3-20170719.155215-10</value>
        <updated>20170719155215</updated>
      </snapshotVersion>
      <snapshotVersion>
        <extension>properties</extension>
        <value>1.2.3-20170719.155215-9</value>
        <updated>20170719155215</updated>
      </snapshotVersion>
    </snapshotVersions>
  </versioning>
</metadata>" > foo/bar/1.2.3-SNAPSHOT/maven-metadata.xml

touch foo/bar/1.2.3-SNAPSHOT/bar-1.2.3-20170719.155215-10.pom \
  foo/bar/1.2.3-SNAPSHOT/bar-1.2.3-20170719.155215-10.war \
  foo/bar/1.2.3-SNAPSHOT/bar-1.2.3-20170719.155215-9.properties

for i in foo/bar/1.2.3-SNAPSHOT/bar-1.2.3-* ; do
  md5sum $i > $i.md5
done

python -m SimpleHTTPServer
```

Artifacts download with Maven is working fine :
```
mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get \                                                                                           [8d8ef76]
  -DrepoUrl=http://localhost:8000/ \
  -Dartifact=foo:bar:1.2.3-SNAPSHOT:pom

mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get \                                                                                           [8d8ef76]
  -DrepoUrl=http://localhost:8000/ \
  -Dartifact=foo:bar:1.2.3-SNAPSHOT:war

mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get \                                                                                           [8d8ef76]
  -DrepoUrl=http://localhost:8000/ \
  -Dartifact=foo:bar:1.2.3-SNAPSHOT:properties
```

Artifacts download with Ansible fails :
```yaml
---
- hosts: localhost
  tasks:

    - maven_artifact:
        group_id: foo
        artifact_id: bar
        version: 1.2.3-SNAPSHOT
        extension: pom
        dest: /tmp/bar.pom
        repository_url: http://localhost:8000/

    - maven_artifact:
        group_id: foo
        artifact_id: bar
        version: 1.2.3-SNAPSHOT
        extension: war
        dest: /tmp/bar.war
        repository_url: http://localhost:8000/

    - maven_artifact:
        group_id: foo
        artifact_id: bar
        version: 1.2.3-SNAPSHOT
        extension: properties
        dest: /tmp/bar.properties
        repository_url: http://localhost:8000/
```

##### EXPECTED RESULTS

Ansible shouldn't fail to download the artifacts.

##### ACTUAL RESULTS

```
TASK [maven_artifact] *************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download artifact foo:bar:pom:1.2.3-SNAPSHOT because of HTTP Error 404: File not foundfor URL http://localhost:8000/foo/bar/1.2.3-SNAPSHOT/bar-1.2.3-20170719.155215-9.pom"}
```
