### ISSUE TITLE
Assert module should not always be verbose

### ISSUE THREAD

**Issue by JoelFeiner** [ansible/ansible#27124]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
assert module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = <redacted>/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]
```

##### CONFIGURATION
Nothing relevant.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When using the assert module, full output is produced, which clutters the normal Ansible output and can potentially reveal sensitive information. Using `no_log` blocks all useful information, so that's not a preferred option.

##### STEPS TO REPRODUCE
Use assert

```yaml
- name: "check_configuration : Ensure CLOUD_ENABLED is boolean"
  assert:
    that:
     - "CLOUD_ENABLED is defined"
     - "CLOUD_ENABLED|string in ['True', 'False']"
    msg: "Must be boolean: {{ CLOUD_ENABLED|default('undefined') }}"
```

##### EXPECTED RESULTS
Something like:
```
TASK [common : check_configuration : Ensure CLOUD_ENABLED is a boolean] *******************************************************************************************************************
ok: [some_host]
```

##### ACTUAL RESULTS
```
TASK [common : check_configuration : Ensure CLOUD_ENABLED is a boolean] *******************************************************************************************************************
ok: [some_host] => {
    "changed": false, 
    "msg": "All assertions passed"
}
```

It's even worse when using constructs like `with_items`, where it also shows the full item information.

This is all caused by the following line in plugins/action/assert.py:
```
result['_ansible_verbose_always'] = True
```

This should either be removed, or be configurable through an argument to the module.

**Comment by nitzmahone** [comment]
Hrm, this was added explicitly in #17654, but removing it still seems to display the failure message fine on both default and minimal stdout plugins. Not sure why we'd always want to display the success output- @tima, can you shed any light?

**Comment by bcoca** [comment]
If what bothers you is 'changed' and other fields aside from message, we can do the same as we do with `debug` and filter those out.

As per item, the `loop_control: label ` feature should help

I would reclassify this as 'feature request' `quiet=no|yes`

**Comment by JoelFeiner** [comment]
I think fixing the overly verbose output is a bug, but certainly adding a new flag would be a feature request. For me personally, now that I think about it, I don't see any value in the quiet flag at all as it really adds nothing (if you want more details, just run with extra verbosity).

**Comment by tima** [comment]
It's been a while and unfortunately that issue didn't capture exactly why that was a good idea. I know I didn't come up with it in a vacuum and probably worked that out on IRC or something before sending the PR. 

I seem to recall it had to do with getting a message to know which assertion had failed when multiple assertion clauses where in use. It also struck me as odd that you defined a `msg` and is didn't display unless you where running in verbose mode. I think the compromise to avoiding special logic in the callback plugin was to just throw it into verbose. 

I could be mistaken, but I believe it was something like that. Things have changed a bit since then that there may be a better way now.

**Comment by JoelFeiner** [comment]
@tima I think things have changed. I commented out the relevant line, and it behaves exactly as I would expect it to. That is, when there is no failure, it produces an "ok" line as other tasks would. When there is a failure, it dumps all of the relevant information, as other tasks would.

**Comment by tima** [comment]
What does the output of a failure look like? What is included in a dump of all?

**Comment by JoelFeiner** [comment]
@tima, I don't have access to my work computer right now, but my memory is that it shows the JSON output of the assert module in red. It does not include newlines, but it does include all of the fields (e.g., "changed", "failure", "msg").

**Comment by tima** [comment]
Is `assertion` in the return when it fails?

```
fatal: [localhost]: FAILED! => {
    "assertion": "CLOUD_ENABLED is defined", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "msg": "Must be boolean: undefined"
}
```

That module's docs probably needs some clarification that the `msg` is an error/failure message since it doesn't get displayed on success. It would be more helpful if the value of `assertion` could be used in the `msg`. Also noticed in testing this that only the first assertion that failed is listed even with `ignore_errors: yes`.

**Comment by JoelFeiner** [comment]
When I'm writing these, I write follow-up assertions that assume the earlier ones succeeded. Multiple failure messages would not be useful to me. But whatever way it works, it should be documented.

That is what I see when it fails.

**Comment by bcoca** [comment]
I woudl also check the `fail` module just to make sure they are congruent

**Comment by bcoca** [comment]
this gets rid of the extra 'status' entries that now appear in 2.4 https://github.com/ansible/ansible/pull/27175

**Comment by bcoca** [comment]
@tima if you want multiple assertions to be tested you would use a loop, then you always get the complete report

**Comment by JoelFeiner** [comment]
@bcoca: it's not clear that the changes in #27175 would be enough to reduce output (if I'm reading it right). It will still show something like:
```
TASK [common : check_configuration : Ensure CLOUD_ENABLED is a boolean] *******************************************************************************************************************
ok: [some_host] => {
    "msg": "All assertions passed"
}
```

In the case of using a loop, it would also show things like this, where the output is even more unnecessarily verbose and does not match, e.g., the `fail` module:
```
TASK [common : check_configuration : Ensure CLOUD_ENABLED is a boolean] *******************************************************************************************************************
ok: [some_host] => {
    "item": {
        "x": "..."
    }
    "msg": "All assertions passed"
}
```

**Comment by tima** [comment]
@bcoca: It's not so much as what I want as much as I'm trying to resolve how it works to how its documented and how it is seems to be used. I find this area of ansible still too "raw" and could be made easier to get things done faster.

Why make `that` a list if I'm supposed to use a loop to test a bunch of things? In the event you want to do a series of related _cascading_ assertions. If that is correct, that should be clarified in the docs and that you only get one _failure_ message for all of the assertions and that it stops checking as soon as the first assertion in the `that` list fails.

Also, do we want to force looping complex data structures? 

```
  - name: "check_configuration : Ensure CLOUD_ENABLED is boolean"
    assert:
      that: "{{ item.that }}"
      msg: "{{ item.err_msg }}"
    with_items:
      - that:
         - "CLOUD_ENABLED is defined"
         - "CLOUD_ENABLED|string in ['True', 'False']"
        err_msg: "Must be boolean: {{ CLOUD_ENABLED|default('undefined') }}"
      - that:
         - "1 == 0"
        err_msg: "This is impossible."
```

That makes for some pretty verbose even harder to read output. 

```
failed: [localhost] (item={u'err_msg': u'Must be boolean: undefined', u'that': [u'CLOUD_ENABLED is defined', u"CLOUD_ENABLED|string in ['True', 'False']"]}) => {
    "assertion": "CLOUD_ENABLED is defined", 
    "evaluated_to": false, 
    "failed": true, 
    "item": {
        "err_msg": "Must be boolean: undefined", 
        "that": [
            "CLOUD_ENABLED is defined", 
            "CLOUD_ENABLED|string in ['True', 'False']"
        ]
    }, 
    "msg": "Must be boolean: undefined"
}
failed: [localhost] (item={u'err_msg': u'This is impossible.', u'that': [u'1 == 0']}) => {
    "assertion": "1 == 0", 
    "evaluated_to": false, 
    "failed": true, 
    "item": {
        "err_msg": "This is impossible.", 
        "that": [
            "1 == 0"
        ]
    }, 
    "msg": "This is impossible."
}
```

**Comment by bcoca** [comment]
@JoelFeiner not a fix for this, but it does remove some of the noise

@tima, not saying its ideal but it is how it currently works, but you can control the output a bit better:

```yaml
  - name: "check_configuration : Ensure CLOUD_ENABLED is boolean"
    assert:
      that: "{{ item.that }}"
      msg: "{{ item.err_msg }}"
    with_items:
      - that:
         - "CLOUD_ENABLED is defined"
         - "CLOUD_ENABLED|string in ['True', 'False']"
        err_msg: "Must be boolean: {{ CLOUD_ENABLED|default('undefined') }}"
        check:  Cloud
      - that:
         - "1 == 0"
        err_msg: "This is impossible."
        check: do_fail
    loop_control:
      label: "{{ item.check}}"
```

which results in:

```json
failed: [localhost] (item=Cloud) => {
    "assertion": "CLOUD_ENABLED is defined",
    "evaluated_to": false,
    "item": {
        "check": "Cloud",
        "err_msg": "Must be boolean: undefined",
        "that": [
            "CLOUD_ENABLED is defined",
            "CLOUD_ENABLED|string in ['True', 'False']"
        ]
    },
    "msg": "Must be boolean: undefined"
}
failed: [localhost] (item=do_fail) => {
    "assertion": "1 == 0",
    "evaluated_to": false,
    "item": {
        "check": "do_fail",
        "err_msg": "This is impossible.",
        "that": [
            "1 == 0"
        ]
    },
    "msg": "This is impossible."
}
 __
```

**Comment by JoelFeiner** [comment]
This line is still in the plugin as of 2.4.2. It really doesn't seem necessary and I'm not sure why it can't just be removed.

plugins/action/assert.py (line 70)
```
result['_ansible_verbose_always'] = True
```

**Comment by cpu** [comment]
Hi folks :wave:

I've also run into this unexpected verbosity problem with the `assert` module. In my case I'm performing GPG signature validation in a loop across several files. Each iteration of the loop causes two `assert` tasks to be run (one to check the signature, one to check the source of the signature), and each prints out a **lot** of information each run because the `item` is a complex object `register`ed by a `command` to run `gpgv2`. The playbook tasks in question are here: 
https://github.com/cpu/streisand/blob/3a0f603bec375ff75f5f1f9a29310f61bdd30dd3/playbooks/roles/download-and-verify/tasks/main.yml#L24-L59

Similar to @JoelFeiner I want to avoid `no_log` unless there is no other resort. Initially I had no `loop_control.label` set but per [@bcoca's earlier comment](https://github.com/ansible/ansible/issues/27124#issuecomment-316855948) I tried adding one to see what the difference would be. The results were underwhelming (here's a before and after example in a gist: https://gist.github.com/cpu/5d357e9ce757da3c1219eceb82c8ec59 )

I'm a bit stumped on how to proceed. This seems like a genuine fault in the `assert` module. I want to be able to use this tool to write reliable Ansible code that ensures its own invariants are always met but I'm having to do a lot of contortions to work around the volume of output it produces. I would greatly appreciate more consistency between this task and others with respect to default output verbosity.

Advice & feedback welcome. Thanks!

(Edit: Forgot to mention, using `Ansible 2.5.0`)

**Comment by jcheroske** [comment]
Is there an Ansible module that validates the structure of a variable in a simple, non-verbose (both in usage and output) fashon? I'm about to write my own role to validate the structure of objects and arrays, but it seems like this should be part of the core library. Maybe I've missed it, but something like this would be awesome:
```
check_variable:
  var: someVar
  object:
    name: string
    port:
      type: number
      greaterThan: 1024
```
Essentially, where's the built-in validation framework? `assert`, `debug`, and `fail` are all used to do this kind of validation, but they are not really suited to it.
