### ISSUE TITLE
iosxr_config fails to indicate changed

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#27120]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
isoxr_config

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel aed35aba70) last updated 2017/07/20 09:27:04 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### STEPS TO REPRODUCE

`ansible-playbook -i inventory.network  iosxr.yaml -vvvv -u root -k -e limit_to=iosxr_config`

```yaml

```

##### ACTUAL RESULTS

```
TASK [iosxr_config : assert] *************************************************************************************************************************************************************************************************************************************************
task path: /Users/dnewswan/code/ansible/test/integration/targets/iosxr_config/tests/cli/toplevel_nonidempotent.yaml:26
fatal: [iosxr01]: FAILED! => {
    "assertion": "result.changed == true",
    "changed": false,
    "evaluated_to": false,
    "failed": true
}

```

**Comment by newswangerd** [comment]
I think that the tests might be wrong in this case. The test that fails is:
```
- name: configure top level command idempotent check
  iosxr_config:
    commands: ['hostname foo']
    match: strict
register: result
```

From what I can tell it basically takes the list of commands and compares each line in list of commands to the corresponding configuration line, so command[x] == config[x]. If the lines don't equal each other, than then command is applied.

In this case command = ['hostname foo'] and the running config = ['hostname foo', 'lots', 'of', 'other', 'lines']. Because the first line of the running config is the same as the list of commands, no changes are applied and result.changed is set to false. Based on the description of the `match: strict` option, it seems like this is the correct behavior. 

Assuming that the module is behaving correctly I would recommend changing the test to either:
```
- name: configure top level command idempotent check
  iosxr_config:
    lines: ['some other config', 'hostname foo']
    match: strict
  register: result
```
so that `hostname foo' won't match against running config[0] or change the assert so that it checks that passes when no change happens.
```
- assert:
    that:
      - "result.changed == true"
```
