### ISSUE TITLE
(P1) nxos_vpc fails on n7k

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27129]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vpc

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: Nexus7000 C7010 running 8.0(1)

##### SUMMARY
When we run nxos_vpc playbook, on n7k, we get timeout for peer-gateway. 
The reason is that on n7k, when we execute peer-gateway CLI, user input is needed from the console and this is holding it up until it times out.
 Here is the console log when the command is run manually from the CLI:
```
n7k.example.com(config)# vpc domain 100
n7k.example.com(config-vpc-domain)# pe 
peer-gateway     peer-keepalive   peer-switch      
n7k.example.com(config-vpc-domain)# peer-gateway 
This peer-gateway config may cause traffic loss. Do you want to continue (y/n)? [n]
```
##### STEPS TO REPRODUCE
Playbook:
```
- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: Configure vpc
    nxos_vpc:
      state: present
      domain: 100
      role_priority: 32667
      system_priority: 2000
      pkl_dest: 192.168.100.4
      pkl_src: 10.1.100.20
      peer_gw: true
      auto_recovery: false
      provider: "{{ cli }}"
```

##### EXPECTED RESULTS
```
PLAY RECAP **********************************************************************************************************************************************                                                                            
n7k.example.com           : ok=20   changed=2    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
TASK [nxos_vpc_interface : configure vpc] ***************************************************************************************************************
fatal: [n7k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "timeout trying to send command: peer-gateway"}
```
