### ISSUE TITLE
nxos_vrf fails for nxapi

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27134]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vrf

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: Nexus9000 C9396PX running 7.0(3)I7(1)

##### SUMMARY
When we run nxos_vrf playbook, we get errors.

##### STEPS TO REPRODUCE
Playbook:

```
- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: Ensure ntc VRF exists on switch
    nxos_vrf:
      vrf: ntc
      provider: "{{ nxapi }}"

  - name: Ensure ntc VRF does not exist on switch
    nxos_vrf:
      vrf: ntc
      state: absent
      provider: "{{ nxapi }}"

```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com          : ok=16   changed=1    unreachable=0    failed=0
```
##### ACTUAL RESULTS
```
TASK [nxos_vrf : Ensure ntc VRF exists on switch] *****************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {"changed": false, "clierror": "", "code": "501", "failed": true, "input": "show run all | section vrf.context.ntc", "msg": "Pipe is not allowed for this message type", "output": {"clierror": "", "code": "501", "input": "show run all | section vrf.context.ntc", "msg": "Pipe is not allowed for this message type"}, "url": "http://n9k.example.com:80/ins"}
```
