### ISSUE TITLE
win_chocolatey fails to deploy packages

### ISSUE THREAD

**Issue by lmilbaum** [ansible/ansible#27155]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

##### OS / ENVIRONMENT

control machine: OS-X 10.12.6
target machine - Windows 2012 R2 

##### SUMMARY

The following packages fail to deploy:
officeproplus2013
sql-server-management-studio

Extending the win_chocolatey timeout attribute didn't change the result.

Manually running choco on the target machine successfully deploys all packages.

##### STEPS TO REPRODUCE

```yaml
- name: Deploy tools
  win_chocolatey:
    name: "{{ item }}"
  with_items:
    - officeproplus2013
    - visualstudio2013professional
    - sql-server-management-studio
```

##### EXPECTED RESULTS

Successfully deployed all packages

##### ACTUAL RESULTS
```python
TASK [depy.dev : Deploy tools] ***************************************************************************************************************************
task path: /Users/liora/git/depy-backend/depy/ansible/roles/depy/depy.dev/tasks/main.yml:9
Using module file /Users/liora/venv/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
<185.109.149.152> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 185.109.149.152
EXEC (via pipeline wrapper)
failed: [185.109.149.152] (item=officeproplus2013) => {
    "changed": true,
    "choco_error_cmd": "C:\\ProgramData\\chocolatey\\bin\\choco.exe install -dv -y officeproplus2013 -timeout 2700",
    "choco_error_log": null,
    "failed": true,
    "item": "officeproplus2013",
    "msg": "Error installing officeproplus2013",
    "rc": -2147418113
}
Using module file /Users/liora/venv/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
EXEC (via pipeline wrapper)
changed: [185.109.149.152] => (item=visualstudio2013professional) => {
    "changed": true,
    "item": "visualstudio2013professional",
    "rc": 0
}
Using module file /Users/liora/venv/lib/python2.7/site-packages/ansible/modules/windows/win_chocolatey.ps1
EXEC (via pipeline wrapper)
failed: [185.109.149.152] (item=sql-server-management-studio) => {
    "changed": true,
    "choco_error_cmd": "C:\\ProgramData\\chocolatey\\bin\\choco.exe install -dv -y sql-server-management-studio -timeout 2700",
    "choco_error_log": null,
    "failed": true,
    "item": "sql-server-management-studio",
    "msg": "Error installing sql-server-management-studio",
    "rc": 5
}
```

**Comment by ansibot** [comment]
cc @elventear @nitzmahone @petemounce @smadam813 @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
It looks like it is failing because the installers are exiting with a non-zero exit code (hence the "rc": -2147418113 for officeproplus2013 and "rc": 5 for sql-server-management-studio

Its worth using search engines to see why these packages might return these non-zero exit codes.

I have encounted '5' as an exit code before and in my case it was because a dependency on a visual studio c++ runtime was not present.  In my case the VS runtime required a hotfix to be installed (this may have now been rolled up so perhaps not needed), but I will share the tasks needed to install the hotfix and runtime below in case it is relevant.  It is a very vague error message though 5 means 'Access is denied' but doesn't tell you anything specific about what exactly has failed.

I don't use chocolately myself but worth checking if it logs any further information on the affected host, and worth checking the event log too.

**Comment by jhawkesworth** [comment]
Here's the hotfix and VC runtime installation steps.

```yaml
- name: check if Windows8.1-KB2999226-x64.msu hotfix has been applied
  win_shell: Get-Hotfix -Id KB2999226
  register: hotfix_status
  ignore_errors: true

- name: show hotfix status
  debug:
    var: hotfix_status

# Unfortunately you can't use wusa directly to install windows updates.
# see https://support.microsoft.com/en-us/kb/2773898 for details
# you have to unpack the update file and then use dism.exe to install the cab

- name: unpack the hotfix if needed
  win_shell: 'wusa C:\deployment\current\Windows8.1-KB2999226-x64.msu /extract:C:\deployment\archive'
  when: hotfix_status.rc == 1

- name: use dism to install the cab containing the hotfix
  win_shell: 'dism.exe /online /add-package /PackagePath:C:\deployment\archive\Windows8.1-KB2999226-x64.cab'
  when: hotfix_status.rc == 1

- name: ensure Microsoft Visual C++ 2015 x64 Additional Runtime is present
  win_package:
     name: Microsoft Visual C++ 2015 x64 Additional Runtime
     path: 'C:/Program Files/FireDaemon Session 0 Viewer/vc_redist.x64.exe'
     state: present
     product_id: '{BC958BD2-5DAC-3862-BB1A-C1BE0790438D}'
     arguments: "/install /passive /norestart /quiet"

#  Info on the hotfix that needs to be applied first
# see http://stackoverflow.com/questions/33265663/api-ms-win-crt-runtime-l1-1-0-dll-is-missing-when-open-office-file
# the hotfix is KB2999226
```
