### ISSUE TITLE
New module: yaml_file

### ISSUE THREAD

**Issue by HanXHX** [ansible/ansible#27158]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
yaml_file

##### SUMMARY
Like [ini file module](http://docs.ansible.com/ansible/latest/ini_file_module.html), it should be great to have a yaml file module.

###### Options

* `key`: YAML key (mandatory)
*  `value`: YAML value (mandatory if `state` = present)

###### Other infos
Like others files modules, it uses these options: dest/path, state, owner, group, mode...

##### EXPECTED RESULTS

Example:

```yaml
- yaml_file:
    dest: /etc/program/config.yml
    key: foo
    value: bar

- yaml_file:
    dest: /etc/program/config.yml
    key: lorem.ipsum
    value: "sit dolor amet"

- yaml_file:
    dest: /etc/program/config.yml
    key: lorem.parameters
    value:
      - abc
      - efg
```

Output:

```yaml
---

foo: "bar"

lorem:
  ipsum: "sit dolor amet"
  parameters:
    - "abc"
    - "efg"
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by drzraf** [comment]
for reference: #16993

**Comment by keitalbame** [comment]
This would be very useful for me. I'm looking for a way of deleting specific lists of dictionaries on yaml files.
In the case below, I would like to be able to delete the list entry with id **user**
```
nexus_roles:
  - id: developers
    name: Developers
    description: All developers
    privileges:
      - nx-search-read
      - all-repos-read
    roles: []
  - id: users
    name: Users
    description: All users
    privileges:
      - nx-search-read
      - all-repos-read
    roles: []
```
