### ISSUE TITLE
ec2_customer_gateway should not require bgp_asn

### ISSUE THREAD

**Issue by sysinit** [ansible/ansible#27157]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_customer_gateway

##### ANSIBLE VERSION
```
2.3.1.0
```
##### SUMMARY
The ec2_customer_module makes it mandatory to set bgp_asn because this is required when state=present. 
state is present by default, so bgp_asn is always required.
When creating a customer gateway in the AWS Console manualy, the bgp asn is only required, when routing is set to dynamic instead of static.
So the depenency between state and bgp_asn should be removed. Instead there should be a new parameter called "routing" with values static or dynamic.
Setting routing to dynamic should make it mandatory to set bgp_asn, not any other parameter.

##### STEPS TO REPRODUCE

```yaml
- ec2_customer_gateway:
    ip_address: 1.2.3.4
    name: IndianapolisOffice
    state: present
    region: us-east-1
  register: cgw
```

##### EXPECTED RESULTS
Create customer gateway

##### ACTUAL RESULTS

```
TASK [Create customer gateway] *************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "state is present but the following are missing: bgp_asn"}
```
