### ISSUE TITLE
Issue when importing tasks in role main.yml

### ISSUE THREAD

**Issue by alexraileanu** [ansible/ansible#27159]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.1 (default, Apr  4 2017, 09:40:21) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT

OS X 10.12

##### SUMMARY

I can not seem to be able to include tasks in a main.yml file within a role. I followed the examples from the documentation, more exactly: http://docs.ansible.com/ansible/latest/playbooks_roles.html#task-include-files-and-encouraging-reuse

##### STEPS TO REPRODUCE

```yaml
# ~/ansible/roles/secure/tasks/main.yml
tasks:
  - include: sshd.yml

# ~/ansible/roles/secure/tasks/sshd.yml
---
- name: copy ssh config
  template:
    src: sshd.conf.j2
    dest: /etc/ssh/sshd_config
  notify: restart ssh
```

##### ACTUAL RESULTS

```
ERROR! The tasks/main.yml file for role 'secure' must contain a list of tasks

The error appears to have been in '~/ansible/roles/secure/tasks/main.yml': line 1, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


tasks:
^ here
```

Any help will be greatly appreciated. Thanks!
