### ISSUE TITLE
group_vars/all.yml variables not available

### ISSUE THREAD

**Issue by ruimcfreitas** [ansible/ansible#27166]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.0
```

##### OS / ENVIRONMENT

Ansible on CentOS 7
managed nodes with windows 2016

##### SUMMARY

Variables from group_vars/all.yml cannot be referenced in a playbook
Since all variables belong to all groups, shouldn't they be available at the start of play execution ?

##### STEPS TO REPRODUCE

```yaml

group_vars/all.yml:
---
num_parallel: 1


playbook.yml:
- hosts: all
  serial: {{num_parallel}}
  tasks:
  - debug: msg= "{{ num_parallel }}"

```

##### EXPECTED RESULTS

TASK [debug] ***************************************************************************************************************
ok: [testserver] => {
    "changed": false,
    "msg": "1"

##### ACTUAL RESULTS

```
ERROR! the field 'serial' has an invalid value, which appears to include a variable that is undefined. The error was: 'num_parallel' is undefined
```
