### ISSUE TITLE
sros_command: cannot connect on TiMOS-C-14.0.R6

### ISSUE THREAD

**Issue by playgroundctl** [ansible/ansible#27161]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

sros_command

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.1.0
  config file = /home/app/saint/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```
# uncomment this to disable SSH key host checking
host_key_checking = False
```

##### OS / ENVIRONMENT

```
$ hostnamectl
   Static hostname: xxx
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ac9776aa446543db999bf3a2fc4e3be8
           Boot ID: 6179792919bb4ff9bb0761a0a8dceb6c
    Virtualization: vmware
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-327.10.1.el7.x86_64
      Architecture: x86-64
```

##### SUMMARY

`sros_command` module complains about
```
"msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell", 
    "rc": 255
```
in NOKIA devices running `TiMOS-C-14.0.R6 cpm/hops64 Nokia 7750 SR`
while it works in NOKIA devices running `TiMOS-C-12.0.R13 cpm/hops64 ALCATEL XRS 7950`

##### STEPS TO REPRODUCE

`$ ansible-playbook dev-conf.yml --extra-vars "todo=roles/common/vars/aftr.yml"`

```yaml
---

  - name: dev-conf
    hosts: LOCAL
    roles:
      - common

    vars_files:
      - "{{ todo }}"


    # ansible-playbook dev-conf.yml --extra-vars "todo=roles/common/vars/lab.yml"
    tasks:

      - name: "Run commands on remote devices running Nokia SR OS"
        connection: local
        sros_command:
          commands:
            - environment no more
            - environment reduced-prompt 2
            - environment no saved-ind-prompt
            - admin display-config
          provider:
            host: "{{ item.name }}"
            port: 22
            username: "{{ lookup('env','USR_NETOPS') }}"
            password: "{{ lookup('env','PASS_NETOPS') }}"
        when: item.os == "sros"
        with_items: "{{ netelement }}"
        ignore_errors: yes
        register: _
```

##### EXPECTED RESULTS

Retrieve the configuration from the NOKIA device in question.

##### ACTUAL RESULTS

```
TASK [Run commands on remote devices running Nokia SR OS] ********************************************************************************************
task path: /home/app/saint/ansible/dev-conf.yml:75
<xxx> using connection plugin network_cli
<xxx> socket_path: /home/app/.ansible/pc/ae925b46ad
open_shell() returned 255  failed to connect to control socket
failed: [localhost] (item={u'os': u'sros', u'name': u'xxx'}) => {
    "failed": true, 
    "item": {
        "name": "xxx", 
        "os": "sros"
    }, 
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell", 
    "rc": 255
}
```
