### ISSUE TITLE
(P1) Attempting to set ipv6 interface errors out for nxos_ip_interface module

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27170]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_ip_interface

##### NXOS VERSION
7.3(0)I5(1)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 85e7e342b0) last updated 2017/07/20 14:17:47 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
Attempt to set the ipv6 address using the `nxos_ip_interface` module.  The module errors out.

Failure occurs for both `cli` and `nxapi` transports.

```yaml
---
- debug: msg="START TRANSPORT:CLI nxos_ip_interface sanity test"

- set_fact: testint1="{{ nxos_int1 }}"
- set_fact: testint2="{{ nxos_int2 }}"

- name: "Make {{testint1}} a layer3 interface"
  nxos_interface: &l3int1
    interface: "{{ testint1 }}"
    mode: layer3
    description: 'Configured by Ansible - Layer3'
    admin_state: 'up'
    state: present
    provider: "{{ cli }}"

- name: "Make {{testint2}} a layer3 interface"
  nxos_interface: &l3int2
    interface: "{{ testint2 }}"
    mode: layer3
    description: 'Configured by Ansible - Layer3'
    admin_state: 'up'
    state: present
    provider: "{{ cli }}"

- name: Ensure ipv4 address is configured
  nxos_ip_interface:
    interface: "{{ testint1 }}"
    version: v4
    state: present
    addr: 20.20.20.20
    mask: 24
    provider: "{{ cli }}"

- name: Ensure ipv6 address is configured
  nxos_ip_interface:
    interface: "{{ testint2 }}"
    version: v6
    state: present
    addr: 'fd56:31f7:e4ad:5585::1'
    mask: 64
    provider: "{{ cli }}"

- debug: msg="END TRANSPORT:CLI nxos_ip_interface sanity test"
```
##### STEPS TO REPRODUCE

```shell
TASK [nxos_ip_interface : Ensure ipv4 address is configured] ********************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ip_interface/tests/cli/sanity.yaml:25
<n9k.example.com> connection transport is cli
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> socket_path: /root/.ansible/pc/2ead40b205
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/nxos.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/_six.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/connection.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/urls.py
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_ip_interface.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1500659143.81-186913983097485 `" && echo ansible-tmp-1500659143.81-186913983097485="` echo $HOME/.ansible/tmp/ansible-tmp-1500659143.81-186913983097485 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmp8cidoa TO /root/.ansible/tmp/ansible-tmp-1500659143.81-186913983097485/nxos_ip_interface.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1500659143.81-186913983097485/ /root/.ansible/tmp/ansible-tmp-1500659143.81-186913983097485/nxos_ip_interface.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1500659143.81-186913983097485/nxos_ip_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1500659143.81-186913983097485/" > /dev/null 2>&1 && sleep 0'
ok: [n9k.example.com] => {
    "changed": false, 
    "commands": [], 
    "end_state": {
        "addresses": [
            {
                "addr": "20.20.20.20", 
                "mask": "24", 
                "secondary": false, 
                "tag": 0
            }
        ], 
        "interface": "ethernet1/1", 
        "prefixes": [
            "20.20.20.0/24"
        ], 
        "type": "ethernet", 
        "vrf": "\"default\"(1)"
    }, 
    "existing": {
        "addresses": [
            {
                "addr": "20.20.20.20", 
                "mask": "24", 
                "secondary": false, 
                "tag": 0
            }
        ], 
        "interface": "ethernet1/1", 
        "prefixes": [
            "20.20.20.0/24"
        ], 
        "type": "ethernet", 
        "vrf": "\"default\"(1)"
    }, 
    "failed": false, 
    "invocation": {
        "module_args": {
            "addr": "20.20.20.20", 
            "allow_secondary": false, 
            "config": null, 
            "host": null, 
            "include_defaults": "True", 
            "interface": "Ethernet1/1", 
            "mask": "24", 
            "password": null, 
            "port": null, 
            "provider": null, 
            "save": false, 
            "ssh_keyfile": null, 
            "state": "present", 
            "tag": 0, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null, 
            "version": "v4"
        }
    }, 
    "proposed": {
        "addr": "20.20.20.20", 
        "allow_secondary": false, 
        "interface": "ethernet1/1", 
        "mask": "24", 
        "tag": 0
    }
}

TASK [nxos_ip_interface : Ensure ipv6 address is configured] ********************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ip_interface/tests/cli/sanity.yaml:34
<n9k.example.com> connection transport is cli
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> socket_path: /root/.ansible/pc/2ead40b205
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_ip_interface.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1500659145.55-36881611223138 `" && echo ansible-tmp-1500659145.55-36881611223138="` echo $HOME/.ansible/tmp/ansible-tmp-1500659145.55-36881611223138 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmp9zxIn8 TO /root/.ansible/tmp/ansible-tmp-1500659145.55-36881611223138/nxos_ip_interface.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1500659145.55-36881611223138/ /root/.ansible/tmp/ansible-tmp-1500659145.55-36881611223138/nxos_ip_interface.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1500659145.55-36881611223138/nxos_ip_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1500659145.55-36881611223138/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_fnFZPX/ansible_module_nxos_ip_interface.py", line 542, in <module>
    main()
  File "/tmp/ansible_fnFZPX/ansible_module_nxos_ip_interface.py", line 502, in main
    existing = get_ip_interface(interface, version, module)
  File "/tmp/ansible_fnFZPX/ansible_module_nxos_ip_interface.py", line 321, in get_ip_interface
    interface = parse_unstructured_data(body, interface_name, version, module)
  File "/tmp/ansible_fnFZPX/ansible_module_nxos_ip_interface.py", line 277, in parse_unstructured_data
    interface['prefixes'].append(str(ipaddress.ip_interface(address).network))
  File "/usr/local/lib/python2.7/dist-packages/ipaddress.py", line 239, in ip_interface
    address)
ValueError: '2001::db8:800:200c:cccb/64' does not appear to be an IPv4 or IPv6 interface

fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_fnFZPX/ansible_module_nxos_ip_interface.py\", line 542, in <module>\n    main()\n  File \"/tmp/ansible_fnFZPX/ansible_module_nxos_ip_interface.py\", line 502, in main\n    existing = get_ip_interface(interface, version, module)\n  File \"/tmp/ansible_fnFZPX/ansible_module_nxos_ip_interface.py\", line 321, in get_ip_interface\n    interface = parse_unstructured_data(body, interface_name, version, module)\n  File \"/tmp/ansible_fnFZPX/ansible_module_nxos_ip_interface.py\", line 277, in parse_unstructured_data\n    interface['prefixes'].append(str(ipaddress.ip_interface(address).network))\n  File \"/usr/local/lib/python2.7/dist-packages/ipaddress.py\", line 239, in ip_interface\n    address)\nValueError: '2001::db8:800:200c:cccb/64' does not appear to be an IPv4 or IPv6 interface\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/root/agents-ci/ansible/test/integration/nxos.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************
n9k.example.com   : ok=18   changed=0    unreachable=0    failed=1   
```
