### ISSUE TITLE
(P2) nxos_ip_interface is not idempotent on specific nxos image versions

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27172]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_ip_interface

##### NXOS VERSION
7.0(3)I2(5) and 7.0(3)F1(1)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 85e7e342b0) last updated 2017/07/20 14:17:47 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook is idempotent on most nxos image versions but not on version `7.0(3)I2(5) ` and `7.0(3)F1(1)`

```yaml
---
- debug: msg="START TRANSPORT:CLI nxos_ip_interface sanity test"

- set_fact: testint1="{{ nxos_int1 }}"
- set_fact: testint2="{{ nxos_int2 }}"

- name: "Put interface {{testint1}} into default state"
  nxos_config: &intdefault1
    lines:
      - "default interface {{ testint1 }}"
    provider: "{{ cli }}"
  ignore_errors: yes

- name: "Put interface {{testint2}} into default state"
  nxos_config: &intdefault2
    lines:
      - "default interface {{ testint2 }}"
    provider: "{{ cli }}"
  ignore_errors: yes

- name: "Make {{testint1}} a layer3 interface"
  nxos_interface: &l3int1
    interface: "{{ testint1 }}"
    mode: layer3
    description: 'Configured by Ansible - Layer3'
    admin_state: 'up'
    state: present
    provider: "{{ cli }}"

- name: "Make {{testint2}} a layer3 interface"
  nxos_interface: &l3int2
    interface: "{{ testint2 }}"
    mode: layer3
    description: 'Configured by Ansible - Layer3'
    admin_state: 'up'
    state: present
    provider: "{{ cli }}"

- name: Ensure ipv4 address is configured
  nxos_ip_interface: &ipv4
    interface: "{{ testint1 }}"
    version: v4
    state: present
    addr: 20.20.20.20
    mask: 24
    provider: "{{ cli }}"
  register: result

- assert: &true
    that:
      - "result.changed == true"

- name: "Check Idempotence"
  nxos_ip_interface: *ipv4
  register: result

- assert: &false
    that:
      - "result.changed == false"
```

```shell
TASK [nxos_ip_interface : Ensure ipv4 address is configured] ********************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ip_interface/tests/cli/sanity.yaml:39
<n9kfretta.example.com> connection transport is cli
<n9kfretta.example.com> using connection plugin network_cli
<n9kfretta.example.com> socket_path: /root/.ansible/pc/956090d009
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/nxos.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/_six.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/connection.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/urls.py
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_ip_interface.py
<n9kfretta.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9kfretta.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1500661066.22-273071477858456 `" && echo ansible-tmp-1500661066.22-273071477858456="` echo $HOME/.ansible/tmp/ansible-tmp-1500661066.22-273071477858456 `" ) && sleep 0'
<n9kfretta.example.com> PUT /tmp/tmpvGWAYd TO /root/.ansible/tmp/ansible-tmp-1500661066.22-273071477858456/nxos_ip_interface.py
<n9kfretta.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1500661066.22-273071477858456/ /root/.ansible/tmp/ansible-tmp-1500661066.22-273071477858456/nxos_ip_interface.py && sleep 0'
<n9kfretta.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1500661066.22-273071477858456/nxos_ip_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1500661066.22-273071477858456/" > /dev/null 2>&1 && sleep 0'
changed: [n9kfretta.example.com] => {
    "changed": true, 
    "commands": [
        "interface ethernet8/1", 
        "ip address 20.20.20.20/24"
    ], 
    "end_state": {
        "addresses": [], 
        "interface": "ethernet8/1", 
        "prefixes": [], 
        "type": "ethernet", 
        "vrf": "\"default\"(1)"
    }, 
    "existing": {
        "addresses": [], 
        "interface": "ethernet8/1", 
        "prefixes": [], 
        "type": "ethernet", 
        "vrf": null
    }, 
    "failed": false, 
    "invocation": {
        "module_args": {
            "addr": "20.20.20.20", 
            "allow_secondary": false, 
            "config": null, 
            "host": null, 
            "include_defaults": "True", 
            "interface": "Ethernet8/1", 
            "mask": "24", 
            "password": null, 
            "port": null, 
            "provider": null, 
            "save": false, 
            "ssh_keyfile": null, 
            "state": "present", 
            "tag": 0, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null, 
            "version": "v4"
        }
    }, 
    "proposed": {
        "addr": "20.20.20.20", 
        "allow_secondary": false, 
        "interface": "ethernet8/1", 
        "mask": "24", 
        "tag": 0
    }
}

TASK [nxos_ip_interface : assert] ***********************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ip_interface/tests/cli/sanity.yaml:49
ok: [n9kfretta.example.com] => {
    "changed": false, 
    "failed": false, 
    "msg": "All assertions passed"
}

TASK [nxos_ip_interface : Check Idempotence] ************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ip_interface/tests/cli/sanity.yaml:53
<n9kfretta.example.com> connection transport is cli
<n9kfretta.example.com> using connection plugin network_cli
<n9kfretta.example.com> socket_path: /root/.ansible/pc/956090d009
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_ip_interface.py
<n9kfretta.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9kfretta.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1500661068.16-149189556577812 `" && echo ansible-tmp-1500661068.16-149189556577812="` echo $HOME/.ansible/tmp/ansible-tmp-1500661068.16-149189556577812 `" ) && sleep 0'
<n9kfretta.example.com> PUT /tmp/tmpcrzuOH TO /root/.ansible/tmp/ansible-tmp-1500661068.16-149189556577812/nxos_ip_interface.py
<n9kfretta.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1500661068.16-149189556577812/ /root/.ansible/tmp/ansible-tmp-1500661068.16-149189556577812/nxos_ip_interface.py && sleep 0'
<n9kfretta.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1500661068.16-149189556577812/nxos_ip_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1500661068.16-149189556577812/" > /dev/null 2>&1 && sleep 0'
changed: [n9kfretta.example.com] => {
    "changed": true, 
    "commands": [
        "interface ethernet8/1", 
        "ip address 20.20.20.20/24"
    ], 
    "end_state": {
        "addresses": [], 
        "interface": "ethernet8/1", 
        "prefixes": [], 
        "type": "ethernet", 
        "vrf": "\"default\"(1)"
    }, 
    "existing": {
        "addresses": [], 
        "interface": "ethernet8/1", 
        "prefixes": [], 
        "type": "ethernet", 
        "vrf": "\"default\"(1)"
    }, 
    "failed": false, 
    "invocation": {
        "module_args": {
            "addr": "20.20.20.20", 
            "allow_secondary": false, 
            "config": null, 
            "host": null, 
            "include_defaults": "True", 
            "interface": "Ethernet8/1", 
            "mask": "24", 
            "password": null, 
            "port": null, 
            "provider": null, 
            "save": false, 
            "ssh_keyfile": null, 
            "state": "present", 
            "tag": 0, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null, 
            "version": "v4"
        }
    }, 
    "proposed": {
        "addr": "20.20.20.20", 
        "allow_secondary": false, 
        "interface": "ethernet8/1", 
        "mask": "24", 
        "tag": 0
    }
}

TASK [nxos_ip_interface : assert] ***********************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ip_interface/tests/cli/sanity.yaml:57
fatal: [n9kfretta.example.com]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
	to retry, use: --limit @/root/agents-ci/ansible/test/integration/nxos.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************
n9kfretta.example.com          : ok=23   changed=6    unreachable=0    failed=1    
```
