### ISSUE TITLE
Add plugin as parameter for mysql_user, to allow use of auth_socket plugin

### ISSUE THREAD

**Issue by pgrenaud** [ansible/ansible#27179]
##### ISSUE TYPE

Feature Idea

##### COMPONENT NAME

`mysql_user`

##### ANSIBLE VERSION

```shell
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

Default configuration

##### OS / ENVIRONMENT

N/A

##### SUMMARY

From the MySQL 5.7 what's new page:

> The server now requires account rows in the mysql.user table to have a nonempty plugin column value and disables accounts with an empty value.

On a fresh installation of MySQL 5.7 the `root` user for host `localhost` is now configured with a plugin value of `auth_socket`. This prevents users other then root to connect as root using the `mysql`client utility:

```shell
user@server$ mysql -u root -pP4ssw0rd
ERROR 1698 (28000): Access denied for user 'root'@'localhost'
```

While as root this works:

```shell
root@server# mysql
```

Currently, this cannot be done with Ansible.

References:

* https://dev.mysql.com/doc/refman/5.7/en/socket-pluggable-authentication.html
* https://www.slideshare.net/ottokekalainen/passwordless-login-with-unix-authsocket

##### STEPS TO REPRODUCE

It would be nice to introduce a new parameter to this module which accepts all possible plugin values (defaulting to `mysql_native_password`) , e.g.:

```yaml
mysql_user: name=root password=abc123 plugin=mysql_native_password
mysql_user: name=root plugin=auth_socket
```

##### EXPECTED RESULTS

N/A

##### ACTUAL RESULTS

N/A

##### CHALLENGES

* @oscherler noted that the syntax varies between MySQL and MariaDB: https://github.com/ansible/ansible-modules-core/pull/3587#issuecomment-227364601
* @wouteroostervld added that you have to change the plugin and password in one action, to avoid exposure: https://github.com/ansible/ansible-modules-core/issues/3003#issuecomment-256328101

##### NOTES

* Issue migrated from https://github.com/ansible/ansible-modules-core/issues/3003
* Releated PR: https://github.com/ansible/ansible-modules-core/pull/3587

I changed a few details:

* @verwilst mentioned that you can use either a password or auth_socket not both: https://github.com/ansible/ansible-modules-core/issues/3003#issuecomment-199799891
* I updated the format to follow the latest one
* I updated the ansible version output, even if not very usefull in this case
* I also added some references and a challenges section

**Comment by ansibot** [comment]
cc @Jmainguy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by guidodobboletta** [comment]
Would be nice to get this feature as this would also be useful for people trying to add IAM authentication to RDS databases on AWS.

**Comment by BarbzYHOOL** [comment]
Is there a workaround to this? I don't know how to change root password because of this o_0

**Comment by ansibot** [comment]
cc @Xyon @bmalynovytch @dagwieers @michaelcoburn @oneiroi @tolland
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by oscherler** [comment]
@BarbzYHOOL There is. First, do you really need to set a root password? You can use MySQL as root without a password using `sudo mysql`, which is what’s nice about the `auth_socket` plugin. If you’re used to using the root user with projects you are developing (e.g. in Vagrant), you can create another user instead.

If you really want to set up a root user with a password using Ansible, you can:
* Create a MySQL user with sufficient privileges for use with Ansible
* Check the root plugin by selecting from mysql.user
* If it’s not `mysql_native_password`, delete the root user and recreate it.

**Comment by BarbzYHOOL** [comment]
@oscherler I can't use the "mysql_user" module if I don't set any password (on a clean install, I didn't run a security script afterwards)

```
- name: Create user for databases "auth"
  mysql_user:
    name: "testou"
    password: "testou"
    priv: "*.*:ALL"
    state: "present"
    append_privs: no

  msg: 'unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, u"Access denied for user ''root''@''localhost''")'
```

Also I wonder if the auth_socket thing will allow me to connect to mysql from another local machine (virtual machine), as root.

**Comment by BarbzYHOOL** [comment]
In fact, I can't even create any user with ansible because of this on mysql 5.7.

I just can't connect to mysql because it can only connects through root and I don't connect to my server with the root account (who does that?). I also tried to add "become: yes" to the role but it didn't do anything

**Comment by oscherler** [comment]
@BarbzYHOOL I’m writing a dev.to article about how to do it. Should be ready tomorrow.

**Comment by bmalynovytch** [comment]
@BarbzYHOOL you need to set `login_user` and `login_password` or `check_implicit_admin `

**Comment by BarbzYHOOL** [comment]
> you need to set login_user and login_password or check_implicit_admin

I install mysql, then i run a task with mysql_user module and it can't connect:

  msg: 'unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1698, u"Access denied for user ''root''@''localhost''")


If i don't set any user, it uses by default root. I can't set any password since root has no password

```
+---------------+-----------+------------------------------------------------------------------------------------+-----------------------+
| User          | Host      | HEX(authentication_string)                                                         | plugin                |
+---------------+-----------+------------------------------------------------------------------------------------+-----------------------+
| root          | localhost |                                                                                    | auth_socket   
```

So basically I'm stuck there. However if I run the shell module I can run mysql as root (but not with mysql modules... makes no sense to me) and execute queries

There is a solution, use debconf to set the root password during install though but I'm surprised to have to do this annoying thing

**Comment by bmalynovytch** [comment]
Ok, thank you for the update, it's clearer now.
Could you give a try with #45355 ?
This PR is still not merged (needing more reviews and `shipit` commands) but adds `authentication_string` column management, which is not the case to the current module (not able to use recent versions of MySQL and MariaDB)

**Comment by bmalynovytch** [comment]
The PR is related to MySQL and MariaDB, and probably also to Percona-server.

To try the module, just pull it in a `library` folder next to your playbook, it'll override the one in your current version of Ansible.

**Comment by bmalynovytch** [comment]
> You mean the actual plugin uses the "password" column instead of "authentication_string" ??
Yes, sadly

**Comment by BarbzYHOOL** [comment]
Ok but how do I pull the module? it's a PR for the entire ansible project @bmalynovytch

**Comment by bmalynovytch** [comment]
In the PR, click "Files changed", then click "View file" on the `mysql_user.py` file, then click "Raw" to get the link to the file at the right version: https://raw.githubusercontent.com/ansible/ansible/402ca8c06ab3d26b4cec8ab5fd9ddd64deffcaee/lib/ansible/modules/database/mysql/mysql_user.py

**Comment by BarbzYHOOL** [comment]
So I just put this file in a "library" directory?

**Comment by bmalynovytch** [comment]
Yes

**Comment by BarbzYHOOL** [comment]
ok so I have this
```
/playbook.yml
/library/mysql_user.yml
```

Now I run this task in a role:

```
- name: Create root user for local network
  mysql_user:
    login_user: root
    name: "root"
    # host_all: true
    host: "192.168.0.%"
    priv: "*.*:ALL"
    state: present
    check_implicit_admin: true

msg: 'unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, u"Access denied for user ''root''@''localhost'' (using password: NO)")'

```

**Comment by bmalynovytch** [comment]
Not necessary as it is probably unrelated

**Comment by BarbzYHOOL** [comment]
well it doesn't seem to work for that issue

**Comment by bmalynovytch** [comment]
Got it !
Try setting `become: true` and `become_user: root`.
The connection can only work if you run the connection being `root` (system, not db user).

**Comment by BarbzYHOOL** [comment]
Same thing (I put the task directly in the playbook instead)

**Comment by oscherler** [comment]
Here is my post. Give it a try, and comment there if you’re still experiencing problems.

[Changing the MySQL root User from auth_socket to Password Authentication Using Ansible](https://dev.to/oscherler/changing-the-mysql-root-user-from-authsocket-to-password-authentication-using-ansible-3l5m)

**Comment by bmalynovytch** [comment]
Ok, so this is weird: the error says you connect to `localhost`, which means that you used the socket to connect (MySQL internal transforms `localhost` in `use the socket`, and not `use network on 127.0.0.1`), without password, which is what you want.

@BarbzYHOOL could you run it again, with `become: true` and `become_user: root` and `-vvv` ?
@oscherler using shell commands as a workaround shouldn't be the way to go

**Comment by BarbzYHOOL** [comment]
```
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_mysql_user_payload_IykDl4/__main__.py", line 648, in main
    connect_timeout=connect_timeout)
  File "/tmp/ansible_mysql_user_payload_IykDl4/ansible_mysql_user_payload.zip/ansible/module_utils/mysql.py", line 76, in mysql_connect
    db_connection = mysql_driver.connect(**config)
  File "/usr/lib/python2.7/dist-packages/pymysql/__init__.py", line 90, in Connect
    return Connection(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 699, in __init__
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 928, in connect
    self._request_authentication()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1148, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 1010, in _read_packet
    packet.check_error()
  File "/usr/lib/python2.7/dist-packages/pymysql/connections.py", line 393, in check_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python2.7/dist-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)

fatal: [HOST]: FAILED! => changed=false 
  invocation:
    module_args:
      append_privs: false
      check_implicit_admin: true
      config_file: /root/.my.cnf
      connect_timeout: 30
      encrypted: false
      host: 192.168.0.%
      host_all: false
      login_host: localhost
      login_password: null
      login_port: 3306
      login_unix_socket: null
      login_user: root
      name: root
      password: null
      priv: '*.*:ALL'
      sql_log_bin: true
      ssl_ca: null
      ssl_cert: null
      ssl_key: null
      state: present
      update_password: always
      user: root
  msg: 'unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, u"Access denied for user ''root''@''localhost'' (using password: NO)")'
```

**Comment by bmalynovytch** [comment]
Ok, you should then set:
```
      login_unix_socket: /path/to/your/mysql/socket
```

**Comment by BarbzYHOOL** [comment]
lol @bmalynovytch 

```
 invocation:
    module_args:
      append_privs: false
      check_implicit_admin: true
      config_file: /root/.my.cnf
      connect_timeout: 30
      encrypted: false
      host: 192.168.0.%
      host_all: false
      login_host: localhost
      login_password: null
      login_port: 3306
      login_unix_socket: /var/run/mysqld/mysqld.sock
      login_user: root
      name: root
      password: null
      priv: '*.*:ALL'
      sql_log_bin: true
      ssl_ca: null
      ssl_cert: null
      ssl_key: null
      state: present
      update_password: always
      user: root
  msg: 'unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, u"Access denied for user ''root''@''localhost'' (using password: NO)")'
```

**Comment by bmalynovytch** [comment]
Ok, new try (a bit cumbersome):
```
- name: Create root user for local network
   mysql_user:
     login_user: root

     login_host: "{{ omit }}"
     login_password: null
     login_port: "{{ omit }}"
     login_unix_socket: /var/run/mysqld/mysqld.sock

     name: "root"
    # host_all: true
     host: "192.168.0.%"
     priv: "*.*:ALL"
     state: present
```
