### ISSUE TITLE
Intersection of two lists behaves incorrectly (jinja)

### ISSUE THREAD

**Issue by yellowmegaman** [ansible/ansible#27180]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
jinja/templating

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
default one
`https://raw.githubusercontent.com/ansible/ansible/devel/examples/ansible.cfg`

##### OS / ENVIRONMENT
debian stretch

##### SUMMARY
intersect of two lists behaves incorrectly

##### STEPS TO REPRODUCE
ansible-playbook -i hosts bug.yml -e 'servers=som1,som2222'

###### hosts file
```yaml
localhost	ansible_host=localhost
som1		ansible_host=localhost
som2		ansible_host=localhost
```

###### playbook
```yaml
---
- hosts: all
  gather_facts: no
  tasks:

    - name: variable
      set_fact: 
        buglist: |
          {% if servers is undefined or servers == '*' or servers == '' %}
          {{play_hosts|list}}
          {% else %}
          {{play_hosts|list|intersect(servers)}}
          {% endif %}

    - name: output
      debug: msg="{{item}}"
      with_items: "{{buglist}}"
      run_once: yes
```

##### EXPECTED RESULTS
I should see only real intersection, som1. Since som2222 is not actually in play_hosts

##### ACTUAL RESULTS
Intersection won't match lists strictly. I get both som1 and som2, i can actually input som2ANYTHIING and still get som2

```
PLAY [all] ******************************************************************************************************************************************

TASK [variable] *************************************************************************************************************************************
ok: [localhost]
ok: [som1]
ok: [som2]

TASK [output] ***************************************************************************************************************************************
ok: [localhost] => (item=som1) => {
    "item": "som1", 
    "msg": "som1"
}
ok: [localhost] => (item=som2) => {
    "item": "som2", 
    "msg": "som2"
}

PLAY RECAP ******************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
som1                       : ok=1    changed=0    unreachable=0    failed=0   
som2                       : ok=1    changed=0    unreachable=0    failed=0
```
