### ISSUE TITLE
ovirt_templates:  when state is imported support cloning and so giving a new name to template

### ISSUE THREAD

**Issue by rsimonfr** [ansible/ansible#27187]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ovirt-templates

##### ANSIBLE VERSION

```
2.3.0.0 
```

##### OS / ENVIRONMENT

Rhel 7 
##### SUMMARY

When importing a template it is not possible to change the name of the imported template as it can be done via the web interface with cloning option 
##### STEPS TO REPRODUCE

Syntax could be something like this:

``` yaml
# Import template
- ovirt_templates:
  state: imported
  name: mytemplate
  export_domain: myexport
  storage_domain: mystorage
  imported_name::  mytemplate_imported 
  cluster: mycluster
```

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @machacekondra
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lukas-bednar** [comment]
I would like to extend this feature request by following:

When importing image from Glance storage, I would like to have a option to set target disk name of template, same as I am able to do in Web 

```yaml
    - name: "Import template from glance"
      ovirt_templates:
        auth: "{{ ovirt_auth }}"
        state: imported
        name: "template_name"
        image_disk: "disk_located_in_glance"
        image_disk_target_name: "name_of_disk_after_import"
        image_provider: "myglance"
        cluster: "Default"
        storage_domain: "iscsi0"
        wait: true
```

Please let me know if you need more info.

**Comment by lukas-bednar** [comment]
I am thinking how to  implement this feature.

Here is my proposal for changing name of imported template.
In my opinion, the `name` should be name of template which should be created (by importing) in Engine.
So I think we need to add parameter to refer template to be imported.
I have some three names but I don't know what to pick:
* import_from
* source_template
* imported_template

Something like this:
```yaml
- ovirt_templates:
  state: imported
  name: mytemplate  # this will appear in engine
  export_domain: myexport
  import_from:  mytemplate_to_be_imported  # name of template in export domain
  storage_domain: mystorage
  cluster: mycluster
```

Regarding to changing name of `disk_name` in case of importing from glance.
The simplest way would be to add parameter `image_disk_new_name`.
But I don't really like such name.

Something like this:
```yaml
    - ovirt_templates:
        state: imported
        name: "template_name"
        image_disk: "disk_located_in_glance"
        image_disk_new_name: "name_of_disk_after_import"
        image_provider: "myglance"
        cluster: "Default"
        storage_domain: "iscsi0"
        wait: true
```

@machacekondra if you have some idea or preference, I would appreciate your comments.

**Comment by lukas-bednar** [comment]
I hit issue to implement template-rename feature, because it is not supported by engine to do that during the import.
It is possible to do it afterwards. So what we can do is implement feature to rename template after import ...
something like:
```yaml
- ovirt_templates:
    id: THE_ID_OF_TEMPLATE
    name: new_name_of_template
```

@rsimonfr @machacekondra any other suggestions ?
