### ISSUE TITLE
ec2_group does not allow referencing "self"

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#27203]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION
```
2.3.0
```

##### SUMMARY
In AWS, a security group can reference "itself", which is incredibly powerful. ec2_group does not support this. It would be great if it was possible to use the special keyword "self" or similar to reference the group itself when configuring rules, something like:
```
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: self
```

**Comment by ansibot** [comment]
cc @adq
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
I believe you're able to accomplish this by doing:
```
    - name: create security group
      ec2_group:
        description: description
        name: foo
        vpc_id: "{{ vpc }}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_name: foo
```
@trondhindenes Let me know if that works for you!
needs_info
