### ISSUE TITLE
win_copy in "folder mode" with remote_src does not exclude parent directory

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#27206]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_copy

##### ANSIBLE VERSION
```
2.3.2
```

##### OS / ENVIRONMENT
Control node: Ubuntu 16
Target node: Windows Server 2016

##### SUMMARY
The documentation states that if the "src" parameter ends with a "/", then the contents of the directory is copied, not the directory itself. However, when using this together with "remote_src" the module seems to be broken.

##### STEPS TO REPRODUCE
Source folder layout:
```powershell
PS C:\Users\trond.hindenes> ls F:\softwaredownload\nginx-1.13.3\nginx-1.13.3


    Directory: F:\softwaredownload\nginx-1.13.3\nginx-1.13.3


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        7/23/2017  10:24 AM                conf
d-----        7/23/2017  10:24 AM                contrib
d-----        7/23/2017  10:24 AM                docs
d-----        7/23/2017  10:24 AM                html
d-----        7/11/2017   4:30 PM                logs
d-----        7/11/2017   4:30 PM                temp
------        7/11/2017   4:28 PM        3066880 nginx.exe


PS C:\Users\trond.hindenes>
```
playbook:
```yaml
- name: copy nginx.exe to target dir
  win_copy:
    src: "F:\\softwaredownload\\nginx-1.13.3\\nginx-1.13.3/"
    dest: "F:\\apps\\nginx"
    remote_src: yes
    force: yes
```

ansible `vvvv` output:
```
changed: [wpm-0101001] => {
    "changed": true, 
    "dest": "F:\\apps\\nginx", 
    "operation": "folder_copy", 
    "original_basename": null, 
    "size": 3943932, 
    "src": "F:\\softwaredownload\\nginx-1.13.3\\nginx-1.13.3/"
}

```

##### EXPECTED RESULTS
The contents of `F:\\apps\\nginx` should be equal to the contents of `F:\\softwaredownload\\nginx-1.13.3\\nginx-1.13.3`

##### ACTUAL RESULTS
The root folder is also copied, so `F:\\apps\\nginx` only contains one folder, `nginx-1.13.3` (which again has the copied files)

**Comment by trondhindenes** [comment]
Looking at the code, I can't see any special logic to separate between cases where only the folder _contents_ is to be copied vs copying the folder itself. This should probably be handled inside copy_folder.

**Comment by ansibot** [comment]
cc @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by KroArtem** [comment]
We had the same issue with the same use-case and Ansible 2.3.x version.

**Comment by jhawkesworth** [comment]
Here's a simple reproducer for this:

```yaml
- hosts: windows
  gather_facts: false

  tasks:

    - name: ensure src and dest folders are setup
      win_file:
        state: directory
        path: "{{ item }}"
      with_items:
        - C:\test-from\lib
        - C:\test-to

    - name: ensure test content is present
      win_shell: "echo '' > {{item}}"
      with_items:
        - C:\test-from\1.txt
        - C:\test-from\2.txt
        - C:\test-from\lib\lib1.txt
        - C:\test-from\lib\lib2.txt

    - name: try the remote source copy
      win_copy:
        src: C:\test-from\
        dest: C:\test-to\
        remote_src: yes
        force: yes
```
