### ISSUE TITLE
yaml error has misleading suggestion to fix escaping issue when mixing key=value args and yaml dict args

### ISSUE THREAD

**Issue by Dmitriusan** [ansible/ansible#27210]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

lineinfile
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
Linux Mint

##### SUMMARY
Error message suggests to fix escaping. Actually, the problem is that some command parameters are provided in a short form, and some are provided as dictionary

##### STEPS TO REPRODUCE
Just run the task provided

```yaml
- name: adjust sudoers
  lineinfile: dest=/etc/sudoers.d/enable-passwordless-sudo
      line: 'i ALL= (ALL) NOPASSWD: ALL'
      state: present
      create: True
      validate: 'visudo -cf /etc/sudoers'
```

##### EXPECTED RESULTS
Expected more clear error message

##### ACTUAL RESULTS

```
The error appears to have been in '/system_tuning.yml': line 4, column 11, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  lineinfile: dest=/etc/sudoers.d/enable-dmi-su
      line: 'i ALL= (ALL) NOPASSWD: ALL'
          ^ here
This one looks easy to fix.  It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote.  For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

```
