### ISSUE TITLE
Unnecessary warning about using a jinja2 template when testing if a variable is defined

### ISSUE THREAD

**Issue by mnarusze** [ansible/ansible#27225]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`when`

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /mnt/ansible.cfg
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
[root@ddca1a67d538 mnt]# ansible-playbook zabbix-deploy.yml -vv -i inventory/static_inventory --private-key=.id_rsa
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

For all our roles, we require that the first task checks if all required variables are defined and if they are not empty. The check uses `{{ item }}` in `when` to get the value of every variable. It works as expected, but the output is flooded with warnings about using Jinja2 templates in `when`. We could probably make the checks in a different way (for example, by using a list of variables vs variable names) but our current method requires less typing (much efficiency, yeah!).

##### STEPS TO REPRODUCE

```yaml
- fail:
    msg: "variable {{ item }} is not set! "
  when: "{{ item }} is not defined or {{ item }} == ''"
  with_items:
    - var1
    - var2
```

##### EXPECTED RESULTS

```
skipping: [node-1] => (item=var1)  => {"changed": false, "item": "var1", "skip_reason": "Conditional result was False", "skipped": true}
skipping: [node-1] => (item=var2)  => {"changed": false, "item": "var2", "skip_reason": "Conditional result was False", "skipped": true}
```
##### ACTUAL RESULTS

```
[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ item }} is not defined or {{ item }} == ''

skipping: [node-1] => (item=var1)  => {"changed": false, "item": "var1", "skip_reason": "Conditional result was False", "skipped": true}
skipping: [node-1] => (item=var2)  => {"changed": false, "item": "var2", "skip_reason": "Conditional result was False", "skipped": true}
```

**Comment by alikins** [comment]
Try:

``` yaml
- fail:
    msg: "variable {{ item }} is not set! "
  when: "item is not defined or item == ''"
  with_items:
    - var1
    - var2
```

or

``` yaml
- fail:
     msg: "variable {{ item }} is not set! "
  when: item is not defined or item == ''
  with_items:
    - var1
    - var2
```

The {{}}'s aren't needed for conditionals.

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

**Comment by mnarusze** [comment]
Thanks for the response @alikins . However, we tested the suggested alternatives before submitting this issue and they do not work the same way. You will see what I mean using the following playbook:

```yaml
- hosts: localhost
  vars:
    var1: ""
    var2: "test"
  tasks:
  - name: suggestion 1, doesn't work
    fail:
      msg: "variable {{ item }} is not set! "
    when: "item is not defined or item == ''"
    with_items:
      - var1
      - var2
  - name: suggestion 2, doesn't work
    fail:
      msg: "variable {{ item }} is not set! "
    when: item is not defined or item == ''
    with_items:
      - var1
      - var2
  - name: desired result with a warning
    fail:
      msg: "variable {{ item }} is not set! "
    when: "{{ item }} is not defined or {{ item }} == ''"
    with_items:
      - var1
      - var2
```

Maybe the problem is that the first two don't work?
