### ISSUE TITLE
netapp-lib required error

### ISSUE THREAD

**Issue by Amruthapv** [ansible/ansible#27220]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME
netapp-lib 

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
host_key_checking=false

##### OS / ENVIRONMENT
Ansible is running ubuntu 14.04. And trying to create a vserver on netapp ontapp cluster

##### SUMMARY
On running the playbook that uses the netapp storage modules (ex: na_cdot_svm) I get "python netapp-lib required" error.
Infact I have the latest version of netapp-lib installed.

##### STEPS TO REPRODUCE
NA

``` yaml
---
- hosts: localhost
  connection: local
  vars:

     netapp_hostname: ####

     netapp_username: ###

     netapp_password: ####

  tasks:
   - name: SVM Manager
     na_cdot_svm:
       state: present
       name: ansibleVServer
       root_volume: vol1
       root_volume_aggregate: aggr1
       root_volume_security_style: mixed
       hostname: "{{ netapp_hostname }}"
       username: "{{ netapp_username }}"
       password: "{{ netapp_password }}"


```

##### EXPECTED RESULTS
vserver up and running

##### ACTUAL RESULTS

```
TASK [SVM Manager] **************************************************************************************************************************************************************
task path: /root/sv.yml:13
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.3.0.0-py2.7.egg/ansible/modules/storage/netapp/na_cdot_svm.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1500885650.33-56057899424868 `" && echo ansible-tmp-1500885650.33-56057899424868="` echo /root/.ansible/tmp/ansible-tmp-1500885650.33-56057899424868 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmppkOlFh TO /root/.ansible/tmp/ansible-tmp-1500885650.33-56057899424868/na_cdot_svm.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1500885650.33-56057899424868/ /root/.ansible/tmp/ansible-tmp-1500885650.33-56057899424868/na_cdot_svm.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1500885650.33-56057899424868/na_cdot_svm.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1500885650.33-56057899424868/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "hostname": "10.236.155.69",
            "name": "ansibleVServer",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "root_volume": "vol1",
            "root_volume_aggregate": "aggr1",
            "root_volume_security_style": "mixed",
            "state": "present",
            "username": "admin"
        }
    },
    "msg": "the python NetApp-Lib module is required"

```
