### ISSUE TITLE
Allow for with_first_found in playbooks

### ISSUE THREAD

**Issue by mnarusze** [ansible/ansible#27224]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Playbook

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /mnt/ansible.cfg
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
```
##### OS / ENVIRONMENT

N/A

##### SUMMARY
Playbooks cannot use `with_first_found`. My use case wants to remove a component using included variables. The variables can be defined in one of two places: generic .yml which is always there and .yml.local, which represents an optional, local configuration.

I can work around the issue by ignoring `with_first_found` and just including the vars files in a reverse order but I need to overwrite all variables from all previously included to make sure nothing goes wrong.

##### STEPS TO REPRODUCE

```yaml
- name: remove zabbix
  hosts: "{{ target_hosts }}"
  roles:
  - zabbix_web
  - zabbix_server
  - galera
  vars_files: "{{ item }}"
  with_first_found:
  - vars/zabbix/purge.yml.local
  - vars/zabbix/purge.yml
```

##### EXPECTED RESULTS

Playbook includes the first working option.

##### ACTUAL RESULTS

```
Using /mnt/ansible.cfg as config file
ERROR! 'with_first_found' is not a valid attribute for a Play

The error appears to have been in '/mnt/zabbix-purge.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: remove zabbix
  ^ here
```
