### ISSUE TITLE
regex_replace filter doesn't work inside lookup('template')

### ISSUE THREAD

**Issue by 2k0ri** [ansible/ansible#27222]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- `template` lookup plugin
- `regex_replace` filter
- any other non-jinja2 native filters

##### ANSIBLE VERSION

```
ansible 2.3.1.0
```

##### CONFIGURATION

```
[defaults]
retry_files_save_path = ~/
log_path=~/ansible.log
host_key_checking = False
```

##### OS / ENVIRONMENT

CentOS 7.3
macOS 10.12.5

##### SUMMARY

`regexp_replace` filter works in template with `template` module, but doesn't work inside `lookup('template')` module.
It seems that non-jinja2 native filters such as `regex_replace` are only works inside module and not called in `lookup('template')`.

##### STEPS TO REPRODUCE

```yaml
cat <<'EOT' > test.yml
---
- hosts: all
  connection: local
  vars:
    base:
      value: "1.2.3.4-5"
  tasks:
  - template:
      src: "{{playbook_dir}}/test.json.j2"
      dest: "{{playbook_dir}}/test.json"
  - set_fact:
      from_module: "{{ lookup('file', '{{playbook_dir}}/test.json') }}"
      from_lookup: "{{ lookup('template', '{{playbook_dir}}/test.json.j2') | to_json }}"
  - name: "from_module"
    debug:
      var: "from_module"
  - name: "from_lookup"
    debug:
      var: "from_lookup"
EOT
```

```
cat <<'EOT' > test.json.j2
{
  "1_original": "{{ base.value }}",
  "2_truncated": "{{ base.value[0:3] }}",
  "3_filtered": "{{ base.value | regex_replace('^(\\d\\.\\d).*$', '\\1') }}"
}
EOT
```

```
ansible-playbook -i localhost, test.yml
```

##### EXPECTED RESULTS

output of `from_lookup` is same as `from_module`.

```
ok: [localhost] => {
    "from_module": {
        "1_original": "1.2.3.4-5",
        "2_truncated": "1.2",
        "3_filtered": "1.2"
    }
}
```

##### ACTUAL RESULTS

`3_filtered` output in from_lookup has no changes.

```
TASK [from_module] ****************************************************************************************************************************************************************************
ok: [localhost] => {
    "from_module": {
        "1_original": "1.2.3.4-5",
        "2_truncated": "1.2",
        "3_filtered": "1.2"
    }
}

TASK [from_lookup] ****************************************************************************************************************************************************************************
ok: [localhost] => {
    "from_lookup": {
        "1_original": "1.2.3.4-5",
        "2_truncated": "1.2",
        "3_filtered": "1.2.3.4-5"
    }
}
```
