### ISSUE TITLE
netconf-config.py should support allow_agent and look_for_keys options

### ISSUE THREAD

**Issue by sfloresk** [ansible/ansible#27243]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
lib/ansible/modules/network/netconf/netconf_config.py

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = ****
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

[defaults]
hostfile=./hosts
host_key_checking = false
gathering = smart
pipelining = true
retry_files_enabled = false

##### OS / ENVIRONMENT

Linux - Mac

##### SUMMARY

There are netconf servers that will give authentication error under default settings for the booleans 'allow_agent' and 'look_for_keys' using ncclient.

The component should provide the following options:
allow_agent
look_for_keys

##### STEPS TO REPRODUCE

```yaml
  - name: Sending configuration via netconf
    netconf_config:
      host: 10.90.54.216
      username: admin
      password: admin
      xml: "{{ lookup('template', 'templates/xml_template.j2') }}"
      port: 2022
      hostkey_verify: false
      allow_agent: false
      look_for_keys: false
```

##### EXPECTED RESULTS

Connection successfully
##### ACTUAL RESULTS

Authentication failed 

```
"error connecting to the device: AuthenticationException('Authentication failed.',)"
```
