### ISSUE TITLE
Add rc and stdout/stderr to lxc_container return values

### ISSUE THREAD

**Issue by VojtechMyslivec** [ansible/ansible#27240]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lxc_container module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
No configuration options effects desired behaviour.

##### OS / ENVIRONMENT
Running on GNU/Linux Debian, controling Ubuntu.

##### SUMMARY
Module `lxc_container` should set the `stdout`, `stderr`, `rc` and other values as the `command`, `shell` and other modules. This functionality is needed when working with LXC containers to control the error handling, flow, etc. 

##### STEPS TO REPRODUCE
```yaml
- name: grep something in the container
  lxc_container:
    name: 'container'
    container_command: |
      grep -- regex file
  register: result
  failed_when: false
  changed_when: false

- name: do something in the container
  debug:
    msg: 'Repair the container'
  when: result.rc != 0
```

##### EXPECTED RESULTS
Ansible should run the second task, if the grep failed (*ok*, *changed*). If the regex is found, second task is skipped (*ok*, *skipping*).

##### ACTUAL RESULTS
`rc` variable is not defined.
