### ISSUE TITLE
win_scheduled_task: start task at system startup

### ISSUE THREAD

**Issue by sebLopezCot** [ansible/ansible#27248]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_scheduled_task

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Running control machine on Ubuntu 16.04 managing Windows Server 2016.

##### SUMMARY

I would simply like the ability to create a scheduled task in Windows to run at system startup.

##### STEPS TO REPRODUCE

```yaml
```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @petemounce
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
needs_contributor

**Comment by jborean93** [comment]
Hi @sebLopezCot are you able to try out https://github.com/ansible/ansible/pull/28995 and post your results on there to see if it does what you are looking for.

I am able to use it to create a task that runs at startup using the following task

```
- win_scheduled_task:
    name: task to run on startup
    state: present
    actions:
    - path: cmd.exe
      arguments: /c echo hi
    triggers:
    - type: boot
```

This is the task it creates

![image](https://user-images.githubusercontent.com/8462645/30576037-46bc7c8e-9d48-11e7-99c8-6df85c87e60e.png)
