### ISSUE TITLE
ios_facts: 'show interfaces' gives different output from 'show ipv6 interfaces'

### ISSUE THREAD

**Issue by tyler-8** [ansible/ansible#27242]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /opt/isv/netflow/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 24 2016, 13:29:06) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT

- RHEL 7
- Cisco IOS Software, C2951 Software (C2951-UNIVERSALK9-M), Version 15.4(3)M3, RELEASE SOFTWARE (fc2)
##### SUMMARY

ios_facts fails on a VoIP interface when doing a fact-gather of all subsets.

The problem appears to be because `parse_interfaces` doesn't present the Voip-related interfaces, so when `populate_ipv6_interfaces` is run, it finds the new Voip interfaces, but can't tie them back to any existing key and so fails.

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_facts.py#L268
##### STEPS TO REPRODUCE

```yaml
$ cat cisco-router.yaml 
---
- hosts: cisco_routers
  gather_facts: no
  connection: local 


  tasks:
  - name: GET CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE CONNECTION
    set_fact:
       connection:
          authorize: yes
          host: "{{ inventory_hostname }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"

  - name: Get Cisco Facts
    ios_facts:
      gather_subset: all
      provider: "{{ connection }}"
    register: thefacts

  - debug: var=thefacts.stdout_lines
```

##### EXPECTED RESULTS

Router facts are returned

##### ACTUAL RESULTS

```
TASK [Get Cisco Facts] ***************************************************************************************************************************
task path: /opt/ansible/cisco-router.yaml:20
<cisco_rtr1> using connection plugin network_cli
<cisco_rtr1> socket_path: /home/usertest/.ansible/pc/23176f0a55
open_shell() returned 0 ok 
Using module file /opt/virtualenvs/ansiblerun/lib/python2.7/site-packages/ansible/modules/network/ios/ios_facts.py
<cisco_rtr1> ESTABLISH LOCAL CONNECTION FOR USER: usertest
<cisco_rtr1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<cisco_rtr1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/usertest/.ansible/tmp/ansible-tmp-1500908715.18-68393613750600 `" && echo ansible-tmp-1500908715.18-68393613750600="` echo /home/usertest/.ansible/tmp/ansible-tmp-1500908715.18-68393613750600 `" ) && sleep 0'
<cisco_rtr1> PUT /tmp/tmpRQRKJf TO /home/usertest/.ansible/tmp/ansible-tmp-1500908715.18-68393613750600/ios_facts.py
<cisco_rtr1> EXEC /bin/sh -c 'chmod u+x /home/usertest/.ansible/tmp/ansible-tmp-1500908715.18-68393613750600/ /home/usertest/.ansible/tmp/ansible-tmp-1500908715.18-68393613750600/ios_facts.py && sleep 0'
<cisco_rtr1> EXEC /bin/sh -c '/usr/bin/python /home/usertest/.ansible/tmp/ansible-tmp-1500908715.18-68393613750600/ios_facts.py; rm -rf "/home/usertest/.ansible/tmp/ansible-tmp-1500908715.18-68393613750600/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_POLuRN/ansible_module_ios_facts.py", line 489, in <module>
    main()
  File "/tmp/ansible_POLuRN/ansible_module_ios_facts.py", line 474, in main
    inst.populate()
  File "/tmp/ansible_POLuRN/ansible_module_ios_facts.py", line 269, in populate
    self.populate_ipv6_interfaces(data)
  File "/tmp/ansible_POLuRN/ansible_module_ios_facts.py", line 302, in populate_ipv6_interfaces
    self.facts['interfaces'][key]['ipv6'] = list()
KeyError: 'VoIP-Null0'

fatal: [cisco_rtr1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_POLuRN/ansible_module_ios_facts.py\", line 489, in <module>\n    main()\n  File \"/tmp/ansible_POLuRN/ansible_module_ios_facts.py\", line 474, in main\n    inst.populate()\n  File \"/tmp/ansible_POLuRN/ansible_module_ios_facts.py\", line 269, in populate\n    self.populate_ipv6_interfaces(data)\n  File \"/tmp/ansible_POLuRN/ansible_module_ios_facts.py\", line 302, in populate_ipv6_interfaces\n    self.facts['interfaces'][key]['ipv6'] = list()\nKeyError: 'VoIP-Null0'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
        to retry, use: --limit @/opt/ansible/cisco-router.retry
```
Here's the truncated output of `show ipv6 interface`
```
#sh ipv6 interface | i Null
VoIP-Null0 is up, line protocol is up
VoipNull0.1 is up, line protocol is down
VoipNull0.2 is up, line protocol is down
VoipNull0.3 is up, line protocol is down
VoipNull0.4 is up, line protocol is down
VoipNull0.5 is up, line protocol is down
VoipNull0.6 is up, line protocol is down
```
