### ISSUE TITLE
module argument not omited

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#27266]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

user, may be others
##### ANSIBLE VERSION

```
ansible 2.3.1.0
```

##### CONFIGURATION

hash_behaviour=merge
##### OS / ENVIRONMENT

Debian stretch
##### SUMMARY

user's shell is defaulted to omit, but actually sends empty value.
##### STEPS TO REPRODUCE

dict:
```
accounts:
  user1:
    uid: 1001
```
task:
```
- name: manage users
  user:
    uid: "{{ item.value.uid | default(omit) }}"
    shell: "{{ item.value.shell | default( default_user_shell ) | default(omit) }}"
  with_dict: "{{ accounts }}"
```
##### EXPECTED RESULTS

since there is no 'item.value.shell' in dict, nor 'default_user_shell' is defined, 'shell' argument is omitted and new user is created with whatever default shell system is configured with.
```
ansible-user[26126]: Invoked with ... # no "Shell=" parameter here
useradd[26129]: new user: name=user1, UID=1001, GID=100, home=/home/user1
```
##### ACTUAL RESULTS

user is created with empty shell

```
ansible-user[26126]: Invoked with ... shell=None ...
useradd[26129]: new user: name=user1, UID=1001, GID=100, home=/home/user1, shell=
```
