### ISSUE TITLE
AWS EFS Module Casting TypeError

### ISSUE THREAD

**Issue by PatrickMurray** [ansible/ansible#27270]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`lib/ansible/modules/cloud/amazon/efs.py`

##### ANSIBLE VERSION
```bash
$ ansible --version
ansible 2.3.1.0
  config file = /home/patrick/PycharmProjects/devops_ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
N/A, less AWS account credentials.

##### OS / ENVIRONMENT
```bash
$ uname -a
Linux T440 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY
Within `efs.py`, the addition of a filter object to a list results in a TypeError being thrown as the operator's behavior is undefined in this circumstance.

###### EXAMPLE

```python3
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> values = [1,2,3,4,5,6,7,8,9]
>>> gt = lambda x: x > 5
>>> results = filter(gt, values)
>>> type(values)
<class 'list'>
>>> type(results)
<class 'filter'>
>>> values + results
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can only concatenate list (not "filter") to list
```
##### SOLUTION

The solution is simply to cast the filter to a list.

```
409,410c409,410
<             targets_to_delete = list(targets_to_delete) + changed
<             targets_to_create = list(targets_to_create) + changed
---
>             targets_to_delete = list(targets_to_delete) + list(changed)
>             targets_to_create = list(targets_to_create) + list(changed)
```

##### STEPS TO REPRODUCE
```yaml
---
- name: Establish EFS Volume, Launch Configuration, And ASG
  hosts: localhost
  tasks:
    - name: Create EFS Volume
      efs:
        profile: account
        state: present
        name: "efs_name"
        tags:
          Name: "internal_tagging"
          Application: "application"
          Service: "service"
        targets:
          - subnet_id: "subnet-XXXXXXXX"
            security_groups:
              - sg-XXXXXXXX
 
    - name: Create Launch Configuration
      ec2_lc:
        name: lc_name
        image_id: "{{ hardened_ami }}"
        region: us-east-1
        profile: account
        security_groups:
          - sg-XXXXXXXX
          - sg-XXXXXXXX
          - sg-XXXXXXXX
          - sg-XXXXXXXX
        instance_type: t2.medium
        assign_public_ip: no
        instance_monitoring: yes
        volumes:
          - device_name: /dev/sda1
            volume_size: 20
            delete_on_termination: true
            device_type: gp2

    - name: Create Auto-Scaling Group
      ec2_asg:
        name: asg_name
        launch_config_name: lc_name
        health_check_period: 60
        health_check_type: EC2
        profile: account
        min_size: 1
        max_size: 1
        desired_capacity: 1
        region: us-east-1
        lc_check: yes
        replace_all_instances: no
        vpc_zone_identifier:
          - subnet-XXXXXXXX
        tags:
          - "Name": "internal_tagging"
          - "Application": "application"
          - "Service": "service"
          - "Owner": "Patrick Murray"
          - "Team": "DevOps"
      changed_when: False
```

```bash
$ ansible-playbook site/internal_ca.yml
```

##### EXPECTED RESULTS
```
PLAY [Establish EFS Volume, Launch Configuration, And ASG] ***********************************************************

TASK [Gathering Facts] ***********************************************************************************************
ok: [localhost]

TASK [Create EFS Volume] *********************************************************************************************
changed: [localhost]

TASK [Create Launch Configuration] ***********************************************************************************
ok: [localhost]

TASK [Create Auto-Scaling Group] *************************************************************************************
ok: [localhost]

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```bash
$ ansible-playbook site/internal_ca.yml -vvv
```

```
Using /home/patrick/PycharmProjects/devops_ansible/ansible.cfg as config file
/usr/lib/python3/dist-packages/cryptography/hazmat/backends/openssl/backend.py:901: UserWarning: implicit cast from 'char *' to a different pointer type: will be forbidden in the future (check that the types are as you expect; use an explicit ffi.cast() if they are correct)
  buf

PLAYBOOK: internal_ca.yml ********************************************************************************************
1 plays in site/internal_ca.yml

PLAY [Establish EFS Volume, Launch Configuration, And ASG] ***********************************************************

TASK [Gathering Facts] ***********************************************************************************************
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: patrick
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/patrick/.ansible/tmp/ansible-tmp-1500985349.986229-178644267903476 `" && echo ansible-tmp-1500985349.986229-178644267903476="` echo /home/patrick/.ansible/tmp/ansible-tmp-1500985349.986229-178644267903476 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmptpe6ycl0 TO /home/patrick/.ansible/tmp/ansible-tmp-1500985349.986229-178644267903476/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/patrick/.ansible/tmp/ansible-tmp-1500985349.986229-178644267903476/ /home/patrick/.ansible/tmp/ansible-tmp-1500985349.986229-178644267903476/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/patrick/.ansible/tmp/ansible-tmp-1500985349.986229-178644267903476/setup.py; rm -rf "/home/patrick/.ansible/tmp/ansible-tmp-1500985349.986229-178644267903476/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Create EFS Volume] *********************************************************************************************
task path: /home/patrick/PycharmProjects/devops_ansible/site/internal_ca.yml:5
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/cloud/amazon/efs.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: patrick
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/patrick/.ansible/tmp/ansible-tmp-1500985350.620461-90811446438836 `" && echo ansible-tmp-1500985350.620461-90811446438836="` echo /home/patrick/.ansible/tmp/ansible-tmp-1500985350.620461-90811446438836 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpiqh_49y0 TO /home/patrick/.ansible/tmp/ansible-tmp-1500985350.620461-90811446438836/efs.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/patrick/.ansible/tmp/ansible-tmp-1500985350.620461-90811446438836/ /home/patrick/.ansible/tmp/ansible-tmp-1500985350.620461-90811446438836/efs.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /home/patrick/.ansible/tmp/ansible-tmp-1500985350.620461-90811446438836/efs.py; rm -rf "/home/patrick/.ansible/tmp/ansible-tmp-1500985350.620461-90811446438836/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_0e9i5m5j/ansible_module_efs.py", line 631, in <module>
    main()
  File "/tmp/ansible_0e9i5m5j/ansible_module_efs.py", line 614, in main
    changed = connection.converge_file_system(name=name, tags=tags, targets=targets) or changed
  File "/tmp/ansible_0e9i5m5j/ansible_module_efs.py", line 409, in converge_file_system
    targets_to_delete = list(targets_to_delete) + changed
TypeError: can only concatenate list (not "filter") to list

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_0e9i5m5j/ansible_module_efs.py\", line 631, in <module>\n    main()\n  File \"/tmp/ansible_0e9i5m5j/ansible_module_efs.py\", line 614, in main\n    changed = connection.converge_file_system(name=name, tags=tags, targets=targets) or changed\n  File \"/tmp/ansible_0e9i5m5j/ansible_module_efs.py\", line 409, in converge_file_system\n    targets_to_delete = list(targets_to_delete) + changed\nTypeError: can only concatenate list (not \"filter\") to list\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

PLAY RECAP ***********************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
