### ISSUE TITLE
Pamd not correctly work 

### ISSUE THREAD

**Issue by felrivero** [ansible/ansible#27287]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pamd

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT
OS where ansible - Debian 9 (try on Debian 8 - the same result)
OS target - Debian 8

##### SUMMARY
I try to configure add to the file /etc/pam.d/common-account extra line to the beginning of the file

##### STEPS TO REPRODUCE
aply next step
```
- name: Setup pam
  pamd:
    name: common-account
    type: account
    control: '[success=1 new_authtok_reqd=done default=ignore]'
    module_path: pam_unix.so
    new_type: account
    new_module_path: pam_tally.so
    new_control: required
    state: before
```

##### EXPECTED RESULTS
I expect to get this:
```
account    required    pam_tally.so
account [success=1 new_authtok_reqd=done default=ignore]        pam_unix.so
account requisite                       pam_deny.so
account required                        pam_permit.so
```

##### ACTUAL RESULTS
But the result is
```
account         [success=1 new_authtok_reqd=done default=ignore]        new_authtok_reqd=done default=ignore] pam_unix.so
account         requisite       pam_deny.so
account         required        pam_permit.so
```
