### ISSUE TITLE
(P1)nxos_gir: module fails after times out while trying to enter maintenance mode

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#27292]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_gir

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 9649195c26) last updated 2017/07/24 12:53:01 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04

##### SUMMARY
The module fails with a timeout message while trying to enter maintenance mode. The device actually successfully enters maintenance mode, but playbook fails.

##### STEPS TO REPRODUCE

```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  user_ssl: no

---
- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: "Put system in maintenance mode"
     nxos_gir:
       system_mode_maintenance: true
       provider: "{{ cli }}"
```

##### EXPECTED RESULTS

Expected play to succeed and put device in maintenance mode.

##### ACTUAL RESULTS
The device actually enters maintenance mode, but the play fails.

```
TASK [nxos_gir : Put system in maintenance mode] **********************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_gir/tests/cli/sanity.yaml:19
<n3k-xxx.example.com> connection transport is cli
<n3k-xxx.example.com> using connection plugin network_cli
<n3k-xxx.example.com> socket_path: /root/.ansible/pc/5e0d338906
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_gir.py
<n3k-xxx.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n3k-xxx.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n3k-xxx.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1501003500.47-200760878008043 `" && echo ansible-tmp-1501003500.47-200760878008043="` echo /root/.ansible/tmp/ansible-tmp-1501003500.47-200760878008043 `" ) && sleep 0'
<n3k-xxx.example.com> PUT /tmp/tmpzZJ4HR TO /root/.ansible/tmp/ansible-tmp-1501003500.47-200760878008043/nxos_gir.py
<n3k-xxx.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501003500.47-200760878008043/ /root/.ansible/tmp/ansible-tmp-1501003500.47-200760878008043/nxos_gir.py && sleep 0'
<n3k-xxx.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501003500.47-200760878008043/nxos_gir.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501003500.47-200760878008043/" > /dev/null 2>&1 && sleep 0'
fatal: [n3k-xxx.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "host": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "ssh_keyfile": null, 
            "state": "present", 
            "system_mode_maintenance": true, 
            "system_mode_maintenance_dont_generate_profile": null, 
            "system_mode_maintenance_on_reload_reset_reason": null, 
            "system_mode_maintenance_shutdown": null, 
            "system_mode_maintenance_timeout": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }, 
    "msg": "timeout trying to send command: system mode maintenance"
}
```
