### ISSUE TITLE
ovirt_disks: when ansible is interupted by sigint during downloading disk, disk get stucked in transfering state for ever

### ISSUE THREAD

**Issue by lukas-bednar** [ansible/ansible#27317]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ovirt_disks

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### SUMMARY

Lets have a playbook which downloads disk from oVirt Engine
using ovirt_disk module.
When the ansible interrupted by sigint (ctrl+c), the image in oVirt engine
gets stucked in "Transferring via API" for ever.

##### STEPS TO REPRODUCE

- run playbook below to download disk
- wait until download is initialized
- press ctrl+c
- inspect state of disk in oVirt Engine.

```yaml
- ovirt_disks:
    id: 7de90f31-222c-436c-a1ca-7e655bd5b60c
    download_image_path: /home/user/mydisk.qcow2
```

##### EXPECTED RESULTS

The disk will release lock and end up in state OK.

##### ACTUAL RESULTS

Disk ends up in "Transferring via API" for ever

```

```
