### ISSUE TITLE
(P2)nxos_gir_profile_management: creating a profile is not idempotent

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#27336]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_gir_profile_management

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 9649195c26) last updated 2017/07/24 12:53:01 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04 

##### SUMMARY

Creating a gir profile is **not** idempotent. Deleting one is. 

##### STEPS TO REPRODUCE

```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  user_ssl: no

---
- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: "Create maintenace mode profile"
    nxos_gir_profile_management:
      mode: maintenance
      commands:
        - router eigrp 11
        - isolate
      state: present
      provider: "{{ cli }}"

```

##### EXPECTED RESULTS

The playbook should be idempotent and come back as ok=1 the second time it is applied.

##### ACTUAL RESULTS

The play is not idempotent. `changed=1` in the output.
