### ISSUE TITLE
(P1) nxos_ospf is not idempotent

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27339]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_ospf

##### NXOS VERSION
7.0(3)I5(3) All version tested failed idempotence test.

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel bb5b1680f8) last updated 2017/07/26 08:18:32 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook is not idempotent

```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_ospf sanity test"

- name: "Enable feature OSPF"
  nxos_feature:
    feature: ospf
    state: enabled
    provider: "{{ connection }}"
  ignore_errors: yes

- block:
  - name: Configure ospf
    nxos_ospf: &config
      ospf: 1
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Check Idempotence"
    nxos_ospf: *config
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  rescue:
  - name: "Disable feature OSPF"
    nxos_feature:
      feature: ospf
      state: disabled
      provider: "{{ connection }}"
    ignore_errors: yes

  always:
  - name: Unconfigure ospf
    nxos_ospf: &unconfig
      ospf: 1
      state: absent
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: "Check Idempotence"
    nxos_ospf: *unconfig
    register: result

  - assert: *false

  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_ospf sanity test"
```

```shell
TASK [nxos_ospf : debug] ********************************************************************************************************************************************************************************************************************************
ok: [n9k.example.com] => {
    "msg": "START TRANSPORT:nxapi nxos_ospf sanity test"
}

TASK [nxos_ospf : Enable feature OSPF] ******************************************************************************************************************************************************************************************************************
changed: [n9k.example.com]

TASK [nxos_ospf : Configure ospf] ***********************************************************************************************************************************************************************************************************************
changed: [n9k.example.com]

TASK [nxos_ospf : assert] *******************************************************************************************************************************************************************************************************************************
ok: [n9k.example.com] => {
    "changed": false, 
    "failed": false, 
    "msg": "All assertions passed"
}

TASK [nxos_ospf : Check Idempotence] ********************************************************************************************************************************************************************************************************************
changed: [n9k.example.com]

TASK [nxos_ospf : assert] *******************************************************************************************************************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

TASK [nxos_ospf : Disable feature OSPF] *****************************************************************************************************************************************************************************************************************
changed: [n9k.example.com]

TASK [nxos_ospf : Unconfigure ospf] *********************************************************************************************************************************************************************************************************************
ok: [n9k.example.com]

TASK [nxos_ospf : assert] *******************************************************************************************************************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {
    "assertion": "result.changed == true", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

TASK [nxos_ospf : disable nxapi] ************************************************************************************************************************************************************************************************************************
changed: [n9k.example.com]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************
n9k.example.com          : ok=36   changed=10   unreachable=0    failed=4   
```
