### ISSUE TITLE
SELinux module for compiling a type enforcement (.te) file and installing it

### ISSUE THREAD

**Issue by ivanbaldo** [ansible/ansible#27349]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
SELinux SEModule

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Not relevant.

##### OS / ENVIRONMENT
CentOS 7.3

##### SUMMARY
This playbook is nice https://galaxy.ansible.com/MWojtowicz/semodule/ but in reality, a module would be much better.

##### STEPS TO REPRODUCE
```yaml
- semodule:
    src: mypolicy.te
    state: present (or absent)
```
or
```yaml
- semodule:
    template: mypolicy.te.j2
    state: present (or absent)
```
and also this other way:
```yaml
- semodule:
    name: mypolicy
    content: "allow httpd_t ssh_port_t:tcp_socket name_connect;"
    state: present (or absent)
```
Name is optional for file or template since it could be inferred from the basename of the filename.

##### EXPECTED RESULTS
It should only show if changed or already up to date.

##### ACTUAL RESULTS
Not relevant.

Thanks for considering!!!
