### ISSUE TITLE
win_updates: Exception from HRESULT: 0x8024402C

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#27346]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel bfdf85e002) last updated 2017/07/26 15:31:51 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

Management host macOS 10.12.5
Managed host Windows 7

##### SUMMARY

win_updates fails with  "error": "Exception from HRESULT: 0x8024402C",

##### STEPS TO REPRODUCE

```yaml
- name: Window updates
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
  register: updates 
```

##### EXPECTED RESULTS

Window updates would be applied for the category_names

##### ACTUAL RESULTS

https://gist.github.com/basictheprogram/ccf2109f854d7f64658bbbe556108e93
