### ISSUE TITLE
Docker port binding fails when both same UDP and TCP is bound

### ISSUE THREAD

**Issue by Doooooo0o** [ansible/ansible#27367]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`docker_container`

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/doo/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

```

##### OS / ENVIRONMENT
FC 26

##### SUMMARY
```
    published_ports:
       - "{{ ansible_docker0.ipv4.address }}:53:53"
       - "{{ ansible_docker0.ipv4.address }}:53:53/udp"
```
only binds TCP/53 and not both udp and tcp.

##### STEPS TO REPRODUCE
```yaml
- name: FML
  tags:
    - service
  docker_container:
    name: "osef"
    image: "httpd:2.4"
    pull: yes
    user: root:root
    memory: "128M"
    timeout: 10
    stop_timeout: 10
    restart_policy: "unless-stopped"
    restart: yes
    state: started
    published_ports:
       - "{{ ansible_docker0.ipv4.address }}:53:53"
       - "{{ ansible_docker0.ipv4.address }}:53:53/udp"

```

##### EXPECTED RESULTS
both UDP/53 and TCP/53 are bound.

##### ACTUAL RESULTS
`docker inspect foobar`

```json
            "Ports": {
                "53/tcp": [
                    {
                        "HostIp": "$docker0_ip_addr",
                        "HostPort": "53"
                    }
                ]
            },

```

**Comment by ansibot** [comment]
cc @ThomasSteinbach @cove @dusdanig @jctanner @joshuaconner @kassiansun @softzilla @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kassiansun** [comment]
@theonlydoo This works for me with `docker-py 2.4.2`, could you please upgrade it and try again?

**Comment by Doooooo0o** [comment]
```
root@foo:~ $ pip freeze|grep -i docker
docker-py==1.10.6
docker-pycreds==0.2.1
root@foo:~ $ pip install docker-py==2.4.2
Collecting docker-py==2.4.2
  Could not find a version that satisfies the requirement docker-py==2.4.2 (from versions: 0.0.4, 0.0.5, 0.0.6, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.6.0, 0.7.0, 0.7.1, 0.7.2, 1.0.0, 1.1.0, 1.2.1, 1.2.2, 1.2.3rc1, 1.2.3, 1.3.0, 1.3.1, 1.4.0, 1.5.0, 1.6.0, 1.7.0rc1, 1.7.0rc2, 1.7.0rc3, 1.7.0, 1.7.1, 1.7.2, 1.8.0rc2, 1.8.0rc4, 1.8.0rc5, 1.8.0, 1.8.1, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6)
No matching distribution found for docker-py==2.4.2
```

I tried with the latest version of docker-py and had the same result

**Comment by kassiansun** [comment]
@theonlydoo `pip install docker`, it was renamed to `docker` since version 2.0

**Comment by Doooooo0o** [comment]
same result:

```bash
$ pip freeze|grep -i docker
docker==2.4.2
docker-pycreds==0.2.1
```

```json
      "Ports": {
        "53/tcp": [
          {
            "HostIp": "$docker0_ip_addr",
            "HostPort": "53"
          }
        ]
      },
```

**Comment by ansibot** [comment]
cc @chouseknecht
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Doooooo0o** [comment]
Still affects the latest version:

```
ansible 2.5.0
  python version = 3.6.5 (default, Mar 29 2018, 18:20:46) [GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)]
```

```yaml
- name: Run bind as a container
  tags: 
    - docker
    - bind
  docker_container:
    image: "reg.b47ch.com/foo:{{ foo|default('master') }}"
    name: foo
    state: started
    restart_policy: always
    ports:
      - "{{ ansible_docker0.ipv4.address }}:53:53"
      - "{{ ansible_docker0.ipv4.address }}:53:53/udp"
      - "{{ eth1 }}:9119:9119"
    pull: yes
    dns_servers:
      - 8.8.8.8
```
