### ISSUE TITLE
vmware_guest module error message for nonexistent host is confusing

### ISSUE THREAD

**Issue by theballdredge** [ansible/ansible#27384]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /Users/user/repos/linux-templates/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

none
##### OS / ENVIRONMENT

OSX10.12.6, RHEL7
##### SUMMARY

The error message produced when a host is not found is not descriptive/helpful.
##### STEPS TO REPRODUCE

```
- name: power up vm
  delegate_to: localhost
  become: false
  vmware_guest:
    validate_certs: false
    folder: "/VMs"
    hostname: vmware_host.foo.com
    username: "{{ ansible_vmware_username }}"
    password: "{{ ansible_vmware_password }}"
    datacenter: "Datacenter1"
    name: **nonexistent-host**
    state: poweredon
  # tags:
  #   - vm_build
  # with_items: "{{ hosts }}"
```

##### EXPECTED RESULTS

A message indicating the host was not found/did not exist.

##### ACTUAL RESULTS

A message indicating a datastore was not found.

```
PLAY [Configure RHEL dev template] ****************************************************************************************************************************************************************************

TASK [power_up_vm : power up vm] ******************************************************************************************************************************************************************************
fatal: [rhel-latest-template -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find a matching datastore"}
	to retry, use: --limit @/Users/user/repos/linux-templates/rhel_dev_template.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************
rhel-latest-template       : ok=0    changed=0    unreachable=0    failed=1   

```
