### ISSUE TITLE
501 error with nxos_ntp

### ISSUE THREAD

**Issue by laurent-perrin** [ansible/ansible#27383]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_ntp

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT
Ansible Server: Ubuntu 17.04
Nexus: Cisco Nexus 5672UP-16G

##### SUMMARY
The issue is similar to https://github.com/ansible/ansible/issues/27134 and https://github.com/ansible/ansible/issues/27134.

When the playbook is run, I get an error message

##### STEPS TO REPRODUCE

```yaml
- hosts: nexus
  connection: local

  tasks:
  - name: set ntp1 settings
    nxos_ntp:
      server: 10.175.254.130
      vrf_name: management
      provider: "{{ nxos_provider }}"
```

##### EXPECTED RESULTS
Apply the ntp setting correcty

##### ACTUAL RESULTS
```
TASK [set ntp1 settings] *******************************************************************************************************************
fatal: [cloud-sw-z01r-prd.cloud.620nm.net]: FAILED! => {"changed": false, "clierror": "", "code": "501", "failed": true, "input": "show run | inc ntp.(server|peer)", "msg": "Pipe is not allowed for this messge type", "output": {"clierror": "", "code": "501", "input": "show run | inc ntp.(server|peer)", "msg": "Pipe is not allowed for this messge type"}, "url": "http://cloud-sw-z01r-prd.cloud.620nm.net:80/ins"}
```
