### ISSUE TITLE
ec2_eip does not allow reassociation

### ISSUE THREAD

**Issue by JeanFred** [ansible/ansible#27385]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ec2_eip

##### ANSIBLE VERSION

```
ansible 2.3.1.0
```

##### OS / ENVIRONMENT
N/A 
(Ubuntu 16.04)

##### SUMMARY

ec2_eip does not allow to reallocate an already associated Elastic IP.

##### STEPS TO REPRODUCE

- Have an associated ElasticIP
- Try associate it with another device

```yaml
    - name: Reassociate IP address to
      ec2_eip:
        public_ip: 1.2.3.4
        state: present
        device_id: "foo"
        private_ip_address: 'bar'
        in_vpc: yes
```

##### EXPECTED RESULTS

The ElasticIP is associated to the new device

##### ACTUAL RESULTS

```
    "msg": "EC2ResponseError: 400 Bad Request

<?xml version="1.0" encoding="UTF-8"?>
<Response>
  <Errors>
    <Error>
      <Code>Resource.AlreadyAssociated</Code>
      <Message>resource eipalloc-xxxxx is already associated with associate-id eipassoc-yyy</Message>
    </Error>
  </Errors>
</Response>
```

The [`boto` method](http://boto.cloudhackers.com/en/latest/ref/ec2.html#boto.ec2.connection.EC2Connection.associate_address) used under the hood does allow the reallocation.
