### ISSUE TITLE
(P2) nxos_overlay_global is not idempotent

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27399]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_overlay_global

##### NXOS VERSION
7.0(3)I5(3)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 0fb64214a4) last updated 2017/07/27 13:55:58 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook demonstrates the idempotency issue.  The configuration is applied so I suspect it's a casing issue with the mac address.

```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_overlay_global sanity test"

- name: "Enable nv overlay evpn"
  nxos_evpn_global: &enable_evpn
    nv_overlay_evpn: true
    provider: "{{ connection }}"
  ignore_errors: yes

# N7K? feature-set fabric

- block:
  - name: Configure overlay global
    nxos_overlay_global: &configure
      anycast_gateway_mac: "b.b.b"
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Check Idempotence"
    nxos_overlay_global: *configure
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  always:
  - name: "Disable nv overlay evpn"
    nxos_evpn_global: &disable_evpn
      nv_overlay_evpn: false
      provider: "{{ connection }}"
    ignore_errors: yes

- debug: msg="END TRANSPORT:{{ connection.transport }} nxos_overlay_global sanity test"
```

```shell
TASK [nxos_overlay_global : Check Idempotence] ******************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_overlay_global/tests/common/sanity.yaml:23
<n9k.example.com> connection transport is cli
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> socket_path: /root/.ansible/pc/4cc10f215f
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_overlay_global.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501185415.0-138857765998437 `" && echo ansible-tmp-1501185415.0-138857765998437="` echo $HOME/.ansible/tmp/ansible-tmp-1501185415.0-138857765998437 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmpf5GW0s TO /root/.ansible/tmp/ansible-tmp-1501185415.0-138857765998437/nxos_overlay_global.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501185415.0-138857765998437/ /root/.ansible/tmp/ansible-tmp-1501185415.0-138857765998437/nxos_overlay_global.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501185415.0-138857765998437/nxos_overlay_global.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501185415.0-138857765998437/" > /dev/null 2>&1 && sleep 0'
changed: [n9k.example.com] => {
    "changed": true, 
    "commands": [
        "fabric forwarding anycast-gateway-mac 000B.000B.000B"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "anycast_gateway_mac": "b.b.b", 
            "host": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "ssh_keyfile": null, 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}

TASK [nxos_overlay_global : assert] *****************************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_overlay_global/tests/common/sanity.yaml:27
fatal: [n9k.example.com]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```
