### ISSUE TITLE
(P1) nxos_ospf_vrf module sends invalid command

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27392]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_ospf_vrf

##### NXOS VERSION
7.0(3)I5(3)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel b93b9e68d7) last updated 2017/07/26 14:52:17 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The `nxos_ospf_vrf` module sends an invalid command using the following playbook.  Problem exists for both `nxapi` and `cli`
```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_ospf_vrf sanity test"

- name: "Enable feature OSPF"
  nxos_feature:
    feature: ospf
    state: enabled
    provider: "{{ connection }}"
  ignore_errors: yes

- block:
  - name: Configure ospf vrf
    nxos_ospf_vrf: &config
      ospf: 1
      timer_throttle_spf_start: 50
      timer_throttle_spf_hold: 1000
      timer_throttle_spf_max: 2000
      timer_throttle_lsa_start: 60
      timer_throttle_lsa_hold: 1100
      timer_throttle_lsa_max: 3000
      vrf: test
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Check Idempotence"
    nxos_ospf: *config
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  rescue:
  - name: "Disable feature OSPF"
    nxos_feature:
      feature: ospf
      state: disabled
      provider: "{{ connection }}"
    ignore_errors: yes

  always:
  - name: Unconfigure ospf vrf
    nxos_ospf_vrf: &unconfig
      ospf: 1
      state: absent
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: "Check Idempotence"
    nxos_ospf: *unconfig
    register: result

  - assert: *false

  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_ospf_vrf sanity test"
```

```shell
TASK [nxos_ospf_vrf : debug] ************************************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ospf_vrf/tests/common/sanity.yaml:2
ok: [n9k.example.com] => {
    "msg": "START TRANSPORT:cli nxos_ospf_vrf sanity test"
}

TASK [nxos_ospf_vrf : Enable feature OSPF] **********************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ospf_vrf/tests/common/sanity.yaml:4
<n9k.example.com> connection transport is cli
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> socket_path: /root/.ansible/pc/4cc10f215f
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/nxos.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/connection.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/urls.py
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_feature.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501177595.03-269280703013175 `" && echo ansible-tmp-1501177595.03-269280703013175="` echo $HOME/.ansible/tmp/ansible-tmp-1501177595.03-269280703013175 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmpIr4cde TO /root/.ansible/tmp/ansible-tmp-1501177595.03-269280703013175/nxos_feature.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501177595.03-269280703013175/ /root/.ansible/tmp/ansible-tmp-1501177595.03-269280703013175/nxos_feature.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501177595.03-269280703013175/nxos_feature.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501177595.03-269280703013175/" > /dev/null 2>&1 && sleep 0'
changed: [n9k.example.com] => {
    "changed": true, 
    "commands": [
        "feature ospf"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "config": null, 
            "feature": "ospf", 
            "host": null, 
            "include_defaults": null, 
            "password": null, 
            "port": null, 
            "provider": null, 
            "save": null, 
            "ssh_keyfile": null, 
            "state": "enabled", 
            "timeout": 10, 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null
        }
    }
}

TASK [nxos_ospf_vrf : Configure ospf vrf] ***********************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_ospf_vrf/tests/common/sanity.yaml:12
<n9k.example.com> connection transport is cli
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> socket_path: /root/.ansible/pc/4cc10f215f
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/netcfg.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/nxos.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/connection.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/urls.py
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_ospf_vrf.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501177597.52-53233907747449 `" && echo ansible-tmp-1501177597.52-53233907747449="` echo $HOME/.ansible/tmp/ansible-tmp-1501177597.52-53233907747449 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmpL1tkiO TO /root/.ansible/tmp/ansible-tmp-1501177597.52-53233907747449/nxos_ospf_vrf.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501177597.52-53233907747449/ /root/.ansible/tmp/ansible-tmp-1501177597.52-53233907747449/nxos_ospf_vrf.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501177597.52-53233907747449/nxos_ospf_vrf.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501177597.52-53233907747449/" > /dev/null 2>&1 && sleep 0'
fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "auto_cost": null, 
            "config": null, 
            "default_metric": null, 
            "host": null, 
            "include_defaults": "True", 
            "log_adjacency": null, 
            "ospf": "1", 
            "password": null, 
            "port": null, 
            "provider": null, 
            "router_id": null, 
            "save": false, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "timer_throttle_lsa_hold": "1100", 
            "timer_throttle_lsa_max": "3000", 
            "timer_throttle_lsa_start": "60", 
            "timer_throttle_spf_hold": "1000", 
            "timer_throttle_spf_max": "2000", 
            "timer_throttle_spf_start": "50", 
            "transport": "cli", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null, 
            "vrf": "test"
        }
    }, 
    "msg": "ospf 1\r\r\n                             ^\r\n% Invalid command at '^' marker.\r\n\rn9k-109(config-router-vrf)# "
}

```
