### ISSUE TITLE
Replacement for the old "action" shorthand to run modules from variables

### ISSUE THREAD

**Issue by fthommen** [ansible/ansible#27393]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
action

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /.../ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
_none_

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The old "action" shorthand (http://docs.ansible.com/ansible/latest/playbooks_intro.html#action-shorthand) allowed to run modules from variables (albeit with somehow unintuitive syntax):

```yam
l- name: install basic package
   action: >
     {{ ansible_pkg_mgr }} name=vim state=present update_cache=yes 
```
There doesn't seem to be an equivalent possibility with the current syntax.  Even though http://docs.ansible.com/ansible/latest/playbooks_intro.html#action-shorthand states, that "[...] The old form continues to work in newer versions without any plan of deprecation.[...]" I think that an equivalent "new" form should be made available or that playbooks generally accept variables as module names.

**Comment by nitzmahone** [comment]
Seems to work fine for me:

```
- hosts: localhost
  gather_facts: no
  vars:
    pingac: ping
  tasks:
  - action: '{{ pingac }}'

```

```
(ansible-dev) [mdavis@mdavis-t460p tmp]$ ansible-playbook ac.yml
 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] ***********************************************************************************

TASK [{{ pingac }}] ********************************************************************************
ok: [localhost]

PLAY RECAP *****************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by fthommen** [comment]
Doesn't here:

```yaml
- name: Check autofs package
  action: '{{ ansible_pkg_mgr }}' name=autofs state=present
```
(is part of an included playbook in a role)


```yaml
$ ansible-playbook site.yml --limit=xxxx
SSH password: 
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/data/homes/ansible/ansible-config/deploy/roles/common/tasks/autofs-config.yml': line 16, column 35, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Check autofs package
  action: '{{ ansible_pkg_mgr }}' name=autofs state=present
                                  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

$
```

Ansible version is 2.3.1.0 on CentOS 7.

Anyway this wouldn't invalidate the wish to have this functionality with the "new" syntax :-)
