### ISSUE TITLE
(P1) nxos* modules timeout sending long running command for transport == cli

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27403]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_config

##### NXOS VERSION
version 8.0(1)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 0fb64214a4) last updated 2017/07/27 13:55:58 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook times out using transport `cli` but it's somewhat intermittent.  Increasing the `timeout:` setting appears to have no effect as it times out rather quickly.

```yaml
- name: "Configure VDC setting limit-resource module-type f3"
  nxos_config:
    commands:
      - "terminal dont-ask ; vdc {{ vdcid }} ;  limit-resource module-type f3"
    match: none
    provider: "{{ connection }}"
    timeout: 120
```

```shell
TASK [nxos_overlay_global : Configure VDC setting limit-resource module-type f3] ******************************************************************************************************************************************************************************
fatal: [n7k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "timeout trying to send command: terminal dont-ask ; vdc n7k.example.com ;  limit-resource module-type f3"}
	to retry, use: --limit @/root/agents-ci/ansible/test/integration/nxos.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************
n7k.example.com           : ok=20   changed=3    unreachable=0    failed=1   
```

**Comment by ansibot** [comment]
cc @GGabriele @jedelman8 @privateip @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
@mikewiebe would you mind giving the module a try now?
I have been facing the same issue last week. But it seems to be fixed now for last couple of days.

**Comment by mikewiebe** [comment]
@trishnaguha I tested this in the latest `devel` today but still see the problem.
```shell
TASK [nxos_overlay_global : Configure VDC setting limit-resource module-type f3] ***************************************************************************************************************************************************************************************
fatal: [n7k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "timeout trying to send command: terminal dont-ask ; vdc n7k-99 ;  limit-resource module-type f3"}
```

```
ansible 2.4.0 (devel ccdea1c3b8) last updated 2017/08/18 15:08:01 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

**Comment by trishnaguha** [comment]
@mikewiebe can you try adding `command_timeout` under flag `persistent_connection` in your ansible.cfg?
It should look like:
```
[presistent_connection]
command_timeout=60
```

**Comment by mikewiebe** [comment]
@trishnaguha We are running this playbook as part of our integration tests for nxos.  I did a quick search for `ansible.cfg` files under the integration folder and I found the following.

`targets/pull/pull-integration-test/ansible.cfg`

Is this the file I need to modify?  I tried adding it there but it made no difference.

I suspect I might need one under a directory called `targets/nxos`?  Not sure here.

Also, this seems like it would apply to all modules.  How do we increase timeouts for a single task?  I don't want to apply a global timeout.

**Comment by trishnaguha** [comment]
@mikewiebe No. `command_timeout` is a config value. It applies the config to all the tasks. No way to apply this for single task for now.
I do not know where you have config values for your tests.
We have ansible.cfg here https://github.com/ansible/ansible/blob/devel/test/integration/network-integration.cfg

**Comment by ganeshrn** [comment]
@mikewiebe @trishnaguha   Timeout value under provider can be used to increase timeout for a single task. 
Timeout value per task for nxos is set [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/nxos.py#L62)
However, if the provider timeout value is more than 30 seconds you need to increase persistent connection timer value as well.
Doc for connection timer settings can be found [here](https://github.com/ansible/ansible/blob/devel/examples/ansible.cfg#L398)

To set persistent timer either set`command_timeout` config variable in effective ansible.cfg file or 
set value of environment variable [`ANSIBLE_PERSISTENT_COMMAND_TIMEOUT`](https://github.com/ansible/ansible/blob/devel/lib/ansible/config/base.yml#L1292)

**Comment by mikewiebe** [comment]
@ganeshrn Thanks for the info.  I tried setting the environment variable but it still seems to have not impact.  Command timed out after 10-15 seconds.

```shell
(py2-ansible) mwiebe@MWIEBE-M-D2TB:~/Projects/nxos_ansible/fix_ansible/test/integration$env | grep ANS
ANSIBLE_ROLES_PATH=/Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/
ANSIBLE_HOME=/Users/mwiebe/Projects/nxos_ansible/fix_ansible
ANSIBLE_PERSISTENT_CONNECT_TIMEOUT=300
ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD=True
(py2-ansible) mwiebe@MWIEBE-M-D2TB:~/Projects/nxos_ansible/fix_ansible/test/integration$
```
```shell
TASK [nxos_overlay_global : Configure VDC setting limit-resource module-type f3] ****************************************************************************************************************************************
fatal: [n7k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "timeout trying to send command: terminal dont-ask ; vdc n7k-99 ;  limit-resource module-type f3"}
```

**Comment by ganeshrn** [comment]
@mikewiebe From the output you shared, I can see a setting only for connect_timeout. In addition to this, you need to also set command_timeout. 
```
ANSIBLE_PERSISTENT_COMMAND_TIMEOUT=300
```
As default command timeout value is 10 sec, it is expected to timeout after ~10 secs

**Comment by ganeshrn** [comment]
needs_info

**Comment by ansibot** [comment]
cc @Qalthos @gundalow
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kedarX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mikewiebe** [comment]
@ganeshrn and @trishnaguha Thanks for the help you have provided for this issue.  I need to revisit this because I have tried the solutions suggested above and in certain cases have had limited success but I also have more insight based on some updates I am making to nxos modules.

In the latest `devel` branch, this is the behavior I have observed for transport `nxapi` vs. transport `cli`.

For my use cases I need to be able to set the timeout value for a **single** task when it is a long running task.

**Transport nxapi:**
For long running commands we **DO NOT** have to set the `ANSIBLE_PERSISTENT_COMMAND_TIMEOUT` or `ANSIBLE_PERSISTENT_CONNECT_TIMEOUT`.  

I simply set the `timeout` value in the task itself and it works as expected.

Example:
```yaml
  - name: "Install image {{ system }}"
    check_mode: "{{ chkmode }}"
    nxos_install_os:
      system_image_file: "{{ system }}"
      kickstart_image_file: "{{kick|default(omit)}}"
      issu: "{{ issu }}"
      provider: "{{ connection }}"
      timeout: 400  <--------------- I only want to increase the timeout for this task
    register: result
```

**Transport cli:**
I would expect and (based on this [documentation](http://docs.ansible.com/ansible/latest/network_debug_troubleshooting.html) it seems to confirm my expectation) that I should also be able to control the timeout for a task by setting the timeout parameter.

This does not work as expected for transport: `cli`.  **IF** I set both `ANSIBLE_PERSISTENT_COMMAND_TIMEOUT` and `ANSIBLE_PERSISTENT_CONNECT_TIMEOUT` I can control the timeout but it impacts all tasks for all playbooks and this is **NOT** what I need.

How do I control the timeout on a per/task level for transport `cli`?

**Comment by mikewiebe** [comment]
**Update:** It would appear that the latest `devel` code actually does work the way I would expect for both transports.  Not sure what changed but I will do some more testing and then close this issue if it's fixed.  I do notice that the `timeout` param will be deprecated in version 2.9 however.

```
[DEPRECATION WARNING]: Param 'timeout' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be 
disabled by setting deprecation_warnings=False in ansible.cfg.
```

What is the plan to allow per/task timeout or long running commands after it's deprecated?

**Comment by ganeshrn** [comment]
As discussed in IRC meeting `timeout` and other credential arguments are deprecated at the top level and will be supported only by `provider` argument. Please remove `timeout` from the top level and add it inside `provider`. 
This change in behavior is mentioned in [2.5 porting guide](https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/porting_guide_2.5.rst)

**Comment by mikewiebe** [comment]
@ganeshrn That is not my question.  Today I can do the following.

```yaml
 - Some task that uses the default timeout
 
 - Some other task that uses the default timeout

  - name: "Install image {{ system }}"
    check_mode: "{{ chkmode }}"
    nxos_install_os:
      system_image_file: "{{ system }}"
      kickstart_image_file: "{{kick|default(omit)}}"
      issu: "{{ issu }}"
      provider: "{{ connection }}"
      timeout: 400  <--------------- I only want to increase the timeout for this task
    register: result

  - Back to another set of tasks that use the default timeout.
```

How do I accomplish this same per/task timeout capability in 2.9 and later?

**Comment by trishnaguha** [comment]
@mikewiebe After timeout is deprecated in 2.9, timeout per task can still be achieved with the following way. I am not saying that this is the best solution, but doable. 

**Variables set:**
```
# transport cli without timeout
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"
  transport: cli

# transport nxapi
nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  use_ssl: no
  port: 80

# transport cli with timeout
connection: 
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"
  transport: cli
  timeout: 400
```

**Play:**
```
- name: Enable nxapi (Doesn't require timeout)
  nxos_feature:
    feature: nxapi
    state: enabled
    provider: "{{ cli }}"

# This task requires timeout but still has the same transport
- name: Gather facts (Requires timeout)
  nxos_facts:
    gather_subset: all
    provider: "{{ connection }}"
```
