### ISSUE TITLE
nxos_vxlan_vtep does not configure properly

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27404]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vxlan_vtep

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel b49be56c5b) last updated 2017/07/13 12:38:51 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: Nexus9000 C9396PX running 7.0(3)I2(2e)

##### SUMMARY
When we run a playbook for configuring vxlan_vtep on the node, it only creates an interface nve but no other parameters are being configured.

##### STEPS TO REPRODUCE
playbook:

```
- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: configure vxlan_vtep
    nxos_vxlan_vtep: &configure
      interface: nve1
      description: default
      host_reachability: true
      source_interface: Loopback0
      source_interface_hold_down_time: 30
      shutdown: true
```

##### EXPECTED RESULTS
On the node we should see
```
interface nve1
  no description
  source-interface loopback0
  host-reachability protocol bgp
  source-interface hold-down-time 30
  shutdown
```
##### ACTUAL RESULTS
```
interface nve1
```
