### ISSUE TITLE
(P2) nxos_pim is not idempotent

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27406]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_pim

##### NXOS VERSION
7.0(3)I5(3), 8.0(1)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 0fb64214a4) last updated 2017/07/27 13:55:58 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook demonstrates the idempotency issue.  Same problem for both transports.

```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_pim sanity test"

- name: "Disable feature PIM"
  nxos_feature: &disable_feature
    feature: pim
    state: disabled
    provider: "{{ connection }}"

- name: "Enable feature PIM"
  nxos_feature:
    feature: pim
    state: enabled
    provider: "{{ connection }}"

- block:
  - name: Configure ssm_range
    nxos_pim: &configure
      ssm_range: "232.0.0.0/8"
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: Check idempotence
    nxos_pim: *configure
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  always:
  - name: "Disable feature PIM"
    nxos_feature: *disable_feature

  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_pim sanity test"
```

```shell
TASK [nxos_pim : debug] ***************************************************************************************************************************************************************************************************************************************
ok: [n7k.example.com] => {
    "msg": "START TRANSPORT:nxapi nxos_pim sanity test"
}

TASK [nxos_pim : Disable feature PIM] *************************************************************************************************************************************************************************************************************************
ok: [n7k.example.com]

TASK [nxos_pim : Enable feature PIM] **************************************************************************************************************************************************************************************************************************
changed: [n7k.example.com]

TASK [nxos_pim : Configure ssm_range] *************************************************************************************************************************************************************************************************************************
changed: [n7k.example.com]

TASK [nxos_pim : assert] **************************************************************************************************************************************************************************************************************************************
ok: [n7k.example.com] => {
    "changed": false, 
    "failed": false, 
    "msg": "All assertions passed"
}

TASK [nxos_pim : Check idempotence] ***************************************************************************************************************************************************************************************************************************
changed: [n7k.example.com]

TASK [nxos_pim : assert] **************************************************************************************************************************************************************************************************************************************
fatal: [n7k.example.com]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

TASK [nxos_pim : Disable feature PIM] *************************************************************************************************************************************************************************************************************************
changed: [n7k.example.com]

TASK [nxos_pim : debug] ***************************************************************************************************************************************************************************************************************************************
ok: [n7k.example.com] => {
    "msg": "END TRANSPORT:nxapi nxos_pim sanity test"
}
	to retry, use: --limit @/root/agents-ci/ansible/test/integration/nxos.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************
n7k.example.com           : ok=24   changed=6    unreachable=0    failed=1   
```
