### ISSUE TITLE
nxos_vpc returns with CLI command error

### ISSUE THREAD

**Issue by laurent-perrin** [ansible/ansible#27422]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vpc

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT
Ansible Server: Ubuntu 17.04
Nexus: Cisco Nexus 5672UP-16G 7.3(0)N1(1)

##### SUMMARY
When the playbook is run, I get an error message

##### STEPS TO REPRODUCE

```yaml
- hosts: nexus
  connection: local

  tasks:
  - name: set vpc domain
    nxos_vpc:
      domain: 11
      delay_restore: true
      peer_gw: true
      pkl_src: 192.168.108.1
      pkl_dest: 192.168.108.2
      pkl_vrf: default
      auto_recovery: true
      provider: "{{ nxos_provider }}"
```

##### EXPECTED RESULTS
Apply the vpc domain correctly

##### ACTUAL RESULTS
```
TASK [vpc : create vpc domain] *************************************************************************************************************
fatal: [nexus]: FAILED! => {"changed": false, "clierror": "Syntax error while parsing 'show running section vpc  | xml '\n\n\nCmd exec error.\n", "code": "400", "failed": true, "input": "show running section vpc", "msg": "Input CLI command error", "output": {"clierror": "Syntax error while parsing 'show running section vpc  | xml '\n\n\nCmd exec error.\n", "code": "400", "input": "show running section vpc", "msg": "Input CLI command error"}, "url": "http://nexust:80/ins"}
```
