### ISSUE TITLE
Establish a possibility to use variables as module names w/o using the action shorthand

### ISSUE THREAD

**Issue by fthommen** [ansible/ansible#27424]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
none so far

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /.../ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]``

```

##### CONFIGURATION
_none_

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It would be nice to have the possibility to use variables as module names, e.g. to be able to run

```yaml
- hosts: localhost
  tasks:
  - {{ ansible_pkg_mgr }}:
     name: mypackage
     state: present
```

this doesn't seem to be possible with "new" ansible syntax but was/is possible with the "action" shorthand, which is documented to be "old form" (http://docs.ansible.com/ansible/latest/playbooks_intro.html#action-shorthand).  I feel, this should also be possible in "new" syntax _without_ the usage of the "action" shorthand.
