### ISSUE TITLE
Copy module src path ends with "/" does not copy just the contents

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#27439]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Copy module

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel 0fb64214a4) last updated 2017/07/27 12:32:13 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

Management host macOS 10.12.5
Managed host Ubuntu 16.04

##### SUMMARY

http://docs.ansible.com/ansible/latest/copy_module.html says "...if [src] path ends with "/", only inside contents of that directory are copied to destination.." It's copying the directory and the contents.

##### STEPS TO REPRODUCE

```yaml
- name: copy support users skeleton directory
  copy:
    src: "{{ private_data }}/users/tanner/" 
    dest: "/home/tanner"
    owner: "tanner"
    group: "tanner"
```

Contents of  "{{ private_data }}/users/tanner/"
```
$ ls -al
total 32
drwxr-xr-x  7 tanner  staff   238 Jul 12 13:25 .
drwxr-xr-x  7 tanner  staff   238 Dec 19  2016 ..
-rw-r--r--  1 tanner  staff  3701 Apr  8  2016 .bashrc
-rw-r--r--  1 tanner  staff     7 Apr  8  2016 .digrc
drwxr-xr-x  4 tanner  staff   136 Apr  8  2016 .ssh
-rw-r--r--  1 tanner  staff   259 Dec 14  2016 .swatchrc
-rw-r--r--  1 tanner  staff   129 Jul 12 13:25 .vimrc
```
Before running Ansible
```
# pwd
/home/tanner
# ls -al
total 8
drwx------ 2 tanner tanner 4096 Jul 28 19:09 .
drwxr-xr-x 6 root   root   4096 Jul 28 19:00 ..
#
```
After running Ansible 
```
# pwd
/home/tanner
# ls -al
total 20
drwx------ 4 tanner tanner 4096 Jul 28 19:10 .
drwxr-xr-x 6 root   root   4096 Jul 28 19:00 ..
drwxr-xr-x 3 tanner tanner 4096 Jul 28 19:10 tanner
```

##### EXPECTED RESULTS

The **contents** of "{{ private_data }}/users/tanner/" would be copied into  "/home/tanner"

##### ACTUAL RESULTS

The directory "{{ private_data }}/users/tanner/"  was copied into  "/home/tanner"

```

```

**Comment by basictheprogram** [comment]
git bisect f86ce0975d8496b61ed6e2206cab917d0779cec9 is the first bad commit
```
commit f86ce0975d8496b61ed6e2206cab917d0779cec9
Author: Toshio Kuratomi <a.badger@gmail.com>
Date:   Mon May 8 22:19:54 2017 -0700

    Add a directory walker to copy

    * We need a directory walker that can handle symlinks, empty directories,
      and some other odd needs.  This commit contains a directory walker that
      can do all that.  The walker returns information about the files in the
      directories that we can then use to implement different strategies for
      copying the files to the remote machines.
    * Add local_follow parameter to copy that follows local symlinks (follow
      is for remote symlinks)
    * Refactor the copying of files out of run into its own method
    * Add new integration tests for copy

    Fixes #24949
    Fixes #21513
```

**Comment by basictheprogram** [comment]
No idea how to run integration tests but I think this test needs to be added to the copy module.
```
diff --git a/test/integration/targets/copy/tasks/main.yml b/test/integration/targets/copy/tasks/main.yml
index 9041ff3a26..3fb9df8f86 100644
--- a/test/integration/targets/copy/tasks/main.yml
+++ b/test/integration/targets/copy/tasks/main.yml
@@ -347,6 +347,10 @@
     that:
       - "recursive_copy_result|changed"

+- name: check that file in the top level directory was transferred
+  stat: path={{output_dir}}/foo.txt
+  register: stat_foo
+
 - name: check that a file in a directory was transferred
   stat: path={{output_dir}}/sub/bar.txt
   register: stat_bar
@@ -362,6 +366,7 @@
 - name: assert recursive copy files
   assert:
     that:
+      - "stat_foo.stat.exists"
       - "stat_bar.stat.exists"
       - "stat_bar2.stat.exists"
       - "stat_bar3.stat.exists"
```

**Comment by basictheprogram** [comment]
I'm not sure the documentation is aligned with the integration tests
```yaml
- name: test recursive copy to directory trailing slash, local_follow=False
  copy: src=subdir/ dest={{output_subdir}} directory_mode=0700 local_follow=False
  register: recursive_copy_result
```
I read the above integration test as copy the **contents** of subdir/ (because of the ending "/") to {{output_subdir}} 

But I see these tests
```yaml
- name: check that a file in a directory was transferred
  stat: path={{output_dir}}/sub/bar.txt
  register: stat_bar
```
Shouldn't you be testing for bar in {{output_dir}?
```yaml
- name: check that a file in a directory was transferred
  stat: path={{output_dir}}/bar.txt
  register: stat_bar
```
What created the {{output_dir}}/sub directory? And why?
