### ISSUE TITLE
Mark resource pool as required parameter

### ISSUE THREAD

**Issue by Akasurde** [ansible/ansible#27475]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest.py

##### ANSIBLE VERSION
```
2.4devel
```

##### CONFIGURATION
Default 

##### OS / ENVIRONMENT
Fedora 26

##### SUMMARY
Resource pool is required parameter while creating a virtual machine using vmware_guest

##### STEPS TO REPRODUCE

```yaml
---
- name: SAmple to create VM
  hosts: localhost
  tasks:
    - name: samle
      vmware_guest:
        datacenter: mydatacenter
        esxi_hostname: myhost
        hostname: 127.0.0.1
        name: SampleVM02
        validate_certs: False
        username: user
        password: pass
        folder: /mycity
        state: present
        guest_id: ubuntu_id
        disk:
          - size_gb: 1
            type: thin
            datastore: mydatastore
        hardware:
            memory_mb: 512
            num_cpus: 1
            osid: centos64guest
            scsi: paravirtual
```

##### EXPECTED RESULTS
Resource pool is required for `CreateVM_Task` API 

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to localhost closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_60lrasrl/ansible_module_vmware_guest.py\", line 1386, in <module>\r\n    main()\r\n  File \"/tmp/ansible_60lrasrl/ansible_module_vmware_guest.py\", line 1378, in main\r\n    result = pyv.deploy_vm()\r\n  File \"/tmp/ansible_60lrasrl/ansible_module_vmware_guest.py\", line 1185, in deploy_vm\r\n    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)\r\nUnboundLocalError: local variable 'resource_pool' referenced before assignment\r\n", "msg": "MODULE FAILURE", "rc": 0}
```
