### ISSUE TITLE
Its impossible use changeset_name parameter in cloudformation module

### ISSUE THREAD

**Issue by gregory-dan** [ansible/ansible#27487]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cloudformation

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 97aaf103e8) last updated 2017/07/31 15:29:18 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admin/ansible/lib/ansible
  executable location = /home/admin/ansible/bin/ansible
  python version = 2.7.5 (default, Sep 15 2016, 22:37:39) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Using "changeset_name" parameter results in error:

"msg": "local variable 'changeset_name' referenced before assignment local variable 'changeset_name' referenced before assignment - <type 'exceptions.UnboundLocalError'>"

##### STEPS TO REPRODUCE

```yaml
- name: Creating/Updating stack
  cloudformation:
    stack_name:   "{{stack_name}}"
    profile:      "{{profile}}"
    region:       "{{region}}"
    state:        "{{stack_state}}"
    template_url: "test-change-set.yaml"
    changeset_name: test1
    create_changeset: true
  register:     "{{stack_name}}"
```

##### EXPECTED RESULTS

change set is created with predefined name
##### ACTUAL RESULTS

Fails with error above

```

```
