### ISSUE TITLE
(P2)nxos_igmp_interface: applying default values is not idempotent

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#27484]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_igmp_interface

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel b93b9e68d7) last updated 2017/07/26 14:19:36 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04

##### SUMMARY

The 'immediate_leave' leave property causes problems with idempotence. When this property is not specified in the playbook (i.e. default value) it tries to do 'no ip igmp immediate-leave'.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: nxos
  connection: local
  gather_facts: no

  tasks:
  - name: "Configure igmp interface with default value"
    nxos_igmp_interface:
      interface: "ethernet1/1"
      state: default
      provider: "{{ cli }}"
```

##### EXPECTED RESULTS

Expected playbook to be idempotent
