### ISSUE TITLE
(P1) nxos_pim_interface structured output not supported

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27489]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_pim_interface

##### NXOS VERSION
7.0(3)I2(5), 7.0(3)F1(1)
##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 0fb64214a4) last updated 2017/07/27 13:55:58 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook fails to apply properly because structured output is not supported on nxos image versions `7.0(3)I2(5)` and `7.0(3)F1(1)`
```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_pim_interface sanity test"

- name: "Disable feature PIM"
  nxos_feature: &disable_feature
    feature: pim
    state: disabled
    provider: "{{ connection }}"

- name: "Enable feature PIM"
  nxos_feature:
    feature: pim
    state: enabled
    provider: "{{ connection }}"

- set_fact: testint="{{ nxos_int1 }}"

- name: "Ensure {{testint}} is layer3"
  nxos_interface:
    interface: "{{ testint }}"
    mode: layer3
    description: 'Configured by Ansible - Layer3'
    admin_state: 'up'
    state: present
    provider: "{{ connection }}"

- name: configure
  nxos_pim_interface:
    interface: "{{ testint }}"
    state: absent
    provider: "{{ connection }}"

- block:
  - name: configure pim interface
    nxos_pim_interface: &config
      interface: "{{ testint }}"
      dr_prio: 10
      hello_interval: 40
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: Check idempotence
    nxos_pim_interface: *config
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: configure gp policy and type
    nxos_pim_interface: &configjp
      interface: "{{ testint }}" 
      jp_policy_in: JPIN
      jp_policy_out: JPOUT
      jp_type_in: routemap
      jp_type_out: routemap
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_interface: *configjp
    register: result

  - assert: *false

  - name: configure state default
    nxos_pim_interface: &configdefault
      interface: "{{ testint }}" 
      state: default
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_interface: *configdefault
    register: result

  - assert: *false

  always:
  - name: "Disable feature PIM"
    nxos_feature: *disable_feature

- debug: msg="END TRANSPORT:{{ connection.transport }} nxos_pim_interface sanity test"
```

```shell
TASK [nxos_pim_interface : Ensure Ethernet8/1 is layer3] ************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_pim_interface/tests/common/sanity.yaml:18
<n9kfretta.example.com> connection transport is nxapi
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_interface.py
<n9kfretta.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9kfretta.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501510174.15-79242406010780 `" && echo ansible-tmp-1501510174.15-79242406010780="` echo $HOME/.ansible/tmp/ansible-tmp-1501510174.15-79242406010780 `" ) && sleep 0'
<n9kfretta.example.com> PUT /tmp/tmpcc4LQY TO /root/.ansible/tmp/ansible-tmp-1501510174.15-79242406010780/nxos_interface.py
<n9kfretta.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501510174.15-79242406010780/ /root/.ansible/tmp/ansible-tmp-1501510174.15-79242406010780/nxos_interface.py && sleep 0'
<n9k.example.com> connection transport is nxapi
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_interface.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501510174.16-3203367656168 `" && echo ansible-tmp-1501510174.16-3203367656168="` echo $HOME/.ansible/tmp/ansible-tmp-1501510174.16-3203367656168 `" ) && sleep 0'
<n9kfretta.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501510174.15-79242406010780/nxos_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501510174.15-79242406010780/" > /dev/null 2>&1 && sleep 0'
<n9k.example.com> PUT /tmp/tmpXEIyJZ TO /root/.ansible/tmp/ansible-tmp-1501510174.16-3203367656168/nxos_interface.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501510174.16-3203367656168/ /root/.ansible/tmp/ansible-tmp-1501510174.16-3203367656168/nxos_interface.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501510174.16-3203367656168/nxos_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501510174.16-3203367656168/" > /dev/null 2>&1 && sleep 0'
ok: [n9k.example.com] => {
    "changed": false, 
    "commands": [], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "admin_state": "up", 
            "description": "Configured by Ansible - Layer3", 
            "fabric_forwarding_anycast_gateway": null, 
            "host": "n9k.example.com", 
            "interface": "Ethernet1/1", 
            "interface_type": null, 
            "ip_forward": null, 
            "mode": "layer3", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 80, 
            "provider": {
                "host": "n9k.example.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 80, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": "nxapi", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }
}
ok: [n9kfretta.example.com] => {
    "changed": false, 
    "commands": [], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "admin_state": "up", 
            "description": "Configured by Ansible - Layer3", 
            "fabric_forwarding_anycast_gateway": null, 
            "host": "n9kfretta.example.com", 
            "interface": "Ethernet8/1", 
            "interface_type": null, 
            "ip_forward": null, 
            "mode": "layer3", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 80, 
            "provider": {
                "host": "n9kfretta.example.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 80, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 10, 
            "transport": "nxapi", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }
}

TASK [nxos_pim_interface : configure] *******************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_pim_interface/tests/common/sanity.yaml:27
<n9kfretta.example.com> connection transport is nxapi
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_pim_interface.py
<n9kfretta.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9kfretta.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501510175.03-69242339870905 `" && echo ansible-tmp-1501510175.03-69242339870905="` echo $HOME/.ansible/tmp/ansible-tmp-1501510175.03-69242339870905 `" ) && sleep 0'
<n9k.example.com> connection transport is nxapi
<n9kfretta.example.com> PUT /tmp/tmpj3YFMw TO /root/.ansible/tmp/ansible-tmp-1501510175.03-69242339870905/nxos_pim_interface.py
<n9kfretta.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501510175.03-69242339870905/ /root/.ansible/tmp/ansible-tmp-1501510175.03-69242339870905/nxos_pim_interface.py && sleep 0'
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_pim_interface.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501510175.04-256455400689213 `" && echo ansible-tmp-1501510175.04-256455400689213="` echo $HOME/.ansible/tmp/ansible-tmp-1501510175.04-256455400689213 `" ) && sleep 0'
<n9kfretta.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501510175.03-69242339870905/nxos_pim_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501510175.03-69242339870905/" > /dev/null 2>&1 && sleep 0'
<n9k.example.com> PUT /tmp/tmpjoxKPb TO /root/.ansible/tmp/ansible-tmp-1501510175.04-256455400689213/nxos_pim_interface.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501510175.04-256455400689213/ /root/.ansible/tmp/ansible-tmp-1501510175.04-256455400689213/nxos_pim_interface.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501510175.04-256455400689213/nxos_pim_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501510175.04-256455400689213/" > /dev/null 2>&1 && sleep 0'
fatal: [n9kfretta.example.com]: FAILED! => {
    "changed": false, 
    "clierror": "Note:  process currently not running\n", 
    "code": "501", 
    "failed": true, 
    "input": "show ip pim interface Ethernet8/1", 
    "invocation": {
        "module_args": {
            "border": null, 
            "dr_prio": null, 
            "hello_auth_key": null, 
            "hello_interval": null, 
            "host": "n9kfretta.example.com", 
            "interface": "Ethernet8/1", 
            "jp_policy_in": null, 
            "jp_policy_out": null, 
            "jp_type_in": null, 
            "jp_type_out": null, 
            "neighbor_policy": null, 
            "neighbor_type": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 80, 
            "provider": {
                "host": "n9kfretta.example.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 80, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "sparse": true, 
            "ssh_keyfile": null, 
            "state": "absent", 
            "timeout": 10, 
            "transport": "nxapi", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "msg": "Structured output unsupported", 
    "output": {
        "clierror": "Note:  process currently not running\n", 
        "code": "501", 
        "input": "show ip pim interface Ethernet8/1", 
        "msg": "Structured output unsupported"
    }, 
    "url": "http://n9kfretta.example.com:80/ins"
}
fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "clierror": "Note:  process currently not running\n", 
    "code": "501", 
    "failed": true, 
    "input": "show ip pim interface Ethernet1/1", 
    "invocation": {
        "module_args": {
            "border": null, 
            "dr_prio": null, 
            "hello_auth_key": null, 
            "hello_interval": null, 
            "host": "n9k.example.com", 
            "interface": "Ethernet1/1", 
            "jp_policy_in": null, 
            "jp_policy_out": null, 
            "jp_type_in": null, 
            "jp_type_out": null, 
            "neighbor_policy": null, 
            "neighbor_type": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 80, 
            "provider": {
                "host": "n9k.example.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 80, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "nxapi", 
                "use_ssl": false, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": true
            }, 
            "sparse": true, 
            "ssh_keyfile": null, 
            "state": "absent", 
            "timeout": 10, 
            "transport": "nxapi", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "use_ssl": false, 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": true
        }
    }, 
    "msg": "Structured output unsupported", 
    "output": {
        "clierror": "Note:  process currently not running\n", 
        "code": "501", 
        "input": "show ip pim interface Ethernet1/1", 
        "msg": "Structured output unsupported"
    }, 
    "url": "http://n9k.example.com:80/ins"
}
	to retry, use: --limit @/root/agents-ci/ansible/test/integration/nxos.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************
n9k.example.com      : ok=44   changed=9    unreachable=0    failed=1   
n9kfretta.example.com          : ok=47   changed=9    unreachable=0    failed=1   
```
