### ISSUE TITLE
ec2_elb_facts returns null

### ISSUE THREAD

**Issue by abhikumar-singh** [ansible/ansible#27496]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_elb_facts

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /tmp/install-dev-cluster/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT

RHEL7.2

##### SUMMARY

We created a new ELB using the ec2_elb_lb module and when we use the ec2_elb_facts to get the facts about the newly created elb we are getting an empty list. 

##### STEPS TO REPRODUCE

Create a new classic load balancer using the ec2_elb_lb module 

```yaml
    - name: Create load balancer
      ec2_elb_lb:
        name: "{{ elk_elb_name }}"
        scheme: internal
        state: present
        security_group_ids: "{{ security_groups }}"
        subnets: "{{ subnets }}"
        listeners:
          - protocol: http
            load_balancer_port: "{{ loadbalancer_port }}"
            instance_port: "{{ elk_instance_port }}"
        health_check:
            ping_protocol: tcp
            ping_port: "{{ elk_instance_port }}"
            response_timeout: 59
            interval: 60
            unhealthy_threshold: 10
            healthy_threshold: 3

    - name: Get elk elb facts
      ec2_elb_facts:
        names: "{{ elk_elb_name }}"
      register: elb_facts

```

##### EXPECTED RESULTS

Expected to see the ELB facts with the DNS name of the newly created ELB

##### ACTUAL RESULTS

Getting empty list

```
ok: [localhost] => {
    "changed": false, 
    "elbs": [], 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "ec2_url": null, 
            "names": [
                "elk_dev_lb"
            ], 
            "profile": null, 
            "region": null, 
            "security_token": null, 
            "validate_certs": true
        }
    }
}
```

**Comment by ansibot** [comment]
cc @mjschultz @nand0p
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Thanks for opening the bug report @aks774. I can't reproduce this on stable-2.3. I think the problem may be that your ELB is still being created.
Does:
```
    - name: Get elk elb facts
      ec2_elb_facts:
        region: us-east-1
        names: "{{ name }}"
      register: elb_facts
      until: elb_facts.elbs
```
work? Perhaps an option would also be to enhance the elb module to use the `wait`/`wait_timeout` options for creation as well.
