### ISSUE TITLE
nxos_mtu sysmtu option fails idempotency test

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#27498]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_mtu

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 350018de73) last updated 2017/07/31 08:50:00 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/dnewswan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/dnewswan/code/ansible/lib/ansible
  executable location = /Users/dnewswan/code/ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY

Setting sysmtu to 2000 twice in a row fails to mark the second task as not changed.

##### STEPS TO REPRODUCE

`ansible-playbook -i inventory.network -u admin -k -vvvv nxos.yaml -e limit_to=nxos_mtu`

```yaml
- name: configure system mtu
  nxos_mtu:
    sysmtu: 2000
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - "result.changed == true"

- name: verify system mtu
  nxos_mtu:
    sysmtu: 2000
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - "result.changed == false"

```

##### EXPECTED RESULTS

results.changed should evaluate to false. 

##### ACTUAL RESULTS

```
TASK [nxos_mtu : assert] *******************************************************
task path: /Users/dnewswan/code/concurrent_ci/ansible/test/integration/targets/nxos_mtu/tests/cli/set_sysmtu.yaml:26
fatal: [nxos01]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```
