### ISSUE TITLE
git module add separate remotes for push / pull

### ISSUE THREAD

**Issue by elaske** [ansible/ansible#27493]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
git module

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```
(but others as well).

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The `repo` option of the `git` module only allows setting of one remote URL for the entire repo. The ability to set separate push / pull URLs would be useful in managing the protocols to use. Currently, we use the `git` module to set a remote, and then a `command` to change the `--push` URL to a different URL. 

##### STEPS TO REPRODUCE
Something like this would be nice:
```yaml
#  A single URL
git: 
    repo: https://github.com/ansible/ansible.git

# Different URLs
git: 
    repo:
        pull: git@github.com:ansible/ansible.git
        push: https://github.com/ansible/ansible.git
```

In this usage it allows anyone to pull on that machine, but you have to authenticate to push ^. There may be other use-cases that require different URLs, however.

##### EXPECTED RESULTS
The equivalent of running `git remote set-url --push <remote> <pushurl> --pull <remote> <pullurl>`.

##### ACTUAL RESULTS
N/A
