### ISSUE TITLE
(P2) nxos_pim_interface is not idempotent

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27491]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_pim_interface

##### NXOS VERSION
7.3(0)D1(1), 8.0(1), 7.0(3)I7(1), 7.0(3)I4(6)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 0fb64214a4) last updated 2017/07/27 13:55:58 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook demonstrates the idempotency problem for the nxos versions listed above.

```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_pim_interface sanity test"

- name: "Disable feature PIM"
  nxos_feature: &disable_feature
    feature: pim
    state: disabled
    provider: "{{ connection }}"

- name: "Enable feature PIM"
  nxos_feature:
    feature: pim
    state: enabled
    provider: "{{ connection }}"

- set_fact: testint="{{ nxos_int1 }}"

- name: "Ensure {{testint}} is layer3"
  nxos_interface:
    interface: "{{ testint }}"
    mode: layer3
    description: 'Configured by Ansible - Layer3'
    admin_state: 'up'
    state: present
    provider: "{{ connection }}"

- name: configure
  nxos_pim_interface:
    interface: "{{ testint }}"
    state: absent
    provider: "{{ connection }}"

- block:
  - name: configure pim interface
    nxos_pim_interface: &config
      interface: "{{ testint }}"
      dr_prio: 10
      hello_interval: 40
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: Check idempotence
    nxos_pim_interface: *config
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: configure gp policy and type
    nxos_pim_interface: &configjp
      interface: "{{ testint }}" 
      jp_policy_in: JPIN
      jp_policy_out: JPOUT
      jp_type_in: routemap
      jp_type_out: routemap
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_interface: *configjp
    register: result

  - assert: *false

  - name: configure state default
    nxos_pim_interface: &configdefault
      interface: "{{ testint }}" 
      state: default
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: Check idempotence
    nxos_pim_interface: *configdefault
    register: result

  - assert: *false

  always:
  - name: "Disable feature PIM"
    nxos_feature: *disable_feature

- debug: msg="END TRANSPORT:{{ connection.transport }} nxos_pim_interface sanity test"
```
