### ISSUE TITLE
nxos_switchport is not idempotent for access vlan for {{ nxapi }}

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27503]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_switchport

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I2(5)

##### SUMMARY
Configuring an access vlan is NOT idempotent when using {{ nxapi }} provider. The issue seems to be coming from string to integer comparison.

##### STEPS TO REPRODUCE
playbook:

```
- name: "Setup interface"
  nxos_config: &default
    lines:
      - "default interface ethernet1/1"
    provider: "{{ nxapi }}"
  ignore_errors: yes

- name: "Setup vlans"
  nxos_vlan:
    vlan_range: "5-10,20"
    provider: "{{ nxapi }}"

- block:
  - name: Ensure interface is in L2 state
    nxos_interface:
      interface: "{{ ethernet1/1 }}"
      mode: 'layer2'
      provider: "{{ nxapi }}"

  - name: Ensure interface is in its default switchport state
    nxos_switchport: &def_swi
      interface: "{{ ethernet1/1 }}"
      state: unconfigured
      provider: "{{ nxapi }}"

  - name: Ensure interface is configured for access vlan 20
    nxos_switchport: &acc_vl
      interface: "{{ ethernet1/1 }}"
      mode: access
      access_vlan: 20
      provider: "{{ nxapi }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "access vlan Idempotence"
    nxos_switchport: *acc_vl
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: Ensure interface only has vlans 5-10 as trunk vlans
    nxos_switchport: &tr_vl
      interface: "{{ ethernet1/1 }}"
      mode: trunk
      native_vlan: 10
      trunk_allowed_vlans: 5-10
      provider: "{{ nxapi }}"
    register: result

  - assert: *true

  - name: "trunk vlan Idempotence"
    nxos_switchport: *tr_vl
    register: result

  - assert: *false

  - name: Ensure interface is a trunk port and ensure 2-50 are being tagged (doesn't mean others aren't also being tagged)
    nxos_switchport: &tag
      interface: "{{ ethernet1/1 }}"
      mode: trunk
      native_vlan: 10
      trunk_vlans: 2-50
      provider: "{{ nxapi }}"
    register: result

  - assert: *true

  - name: "tag vlan Idempotence"
    nxos_switchport: *tag
    register: result

  - assert: *false

  - name: Ensure these VLANs are not being tagged on the trunk
    nxos_switchport: &no_tag
      interface: "{{ ethernet1/1 }}"
      mode: trunk
      trunk_vlans: 30-4094
      state: absent
      provider: "{{ nxapi }}"
    register: result

  - assert: *true

  - name: "no tag vlan Idempotence"
    nxos_switchport: *no_tag
    register: result

  - assert: *false

  - name: put interface default state
    nxos_switchport: *def_swi
    register: result

  - assert: *true

  - name: "default state idempotence"
    nxos_switchport: *def_swi
    register: result

  - assert: *false

  always:
  - name: "remove vlans"
    nxos_vlan:
      vlan_range: "5-10,20"
      state: absent
      provider: "{{ nxapi }}"
    ignore_errors: yes

  - name: "default interface"
    nxos_config: *default
    ignore_errors: yes
```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com      : ok=79   changed=19   unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
TASK [nxos_switchport : access vlan Idempotence] ******************************************************************************************************
changed: [n9k.example.com]                                                                                                                       

TASK [nxos_switchport : assert] ***********************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {                                                                                                           
    "assertion": "result.changed == false",                                                                                                            
    "changed": false,                                                                                                                                  
    "evaluated_to": false,                                                                                                                             
    "failed": true                                                                                                                                     
}                     
```
