### ISSUE TITLE
WinRM certificate-based authentication doesn't understand ansible-vault encrypted content

### ISSUE THREAD

**Issue by b5hsiung** [ansible/ansible#27510]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

WinRM connection using "certificate" authentication

##### ANSIBLE VERSION

```
ansible 2.3.1.0
```

##### CONFIGURATION

ANSIBLE_INVENTORY = <ansible_path>/ansible/inventories/dev/hosts

<ansible_path>/ansible/inventories/dev/hosts (inventory) file excerpt:

[windows]
windows01.mydomain.com

<ansible_path>/ansible/inventories/dev/group_vars/windows.yml:
ansible_connection: winrm
ansible_port: 5986
ansible_winrm_server_cert_validation: ignore
ansible_winrm_transport: certificate
ansible_winrm_cert_pem: <ansible_path>/ansible/certs/winrm_client_cert.crt
ansible_winrm_cert_key_pem: <ansible_path>/ansible/certs/winrm_client_cert.key

##### OS / ENVIRONMENT

Running ansible on RedHat Enterprise 6.9, connecting to Windows 8.1 system via WinRM

##### SUMMARY

(file paths and hostnames in this bug report have been sanitized)

When I use ansible-vault to encrypt the file specified by "ansible_winrm_cert_key_pem" (which is desirable because it's the private key used to connect to Windows systems in order to manage them), the WinRM connection code does not appear to check for and apply ansible-vault decrypt to it if needed before attempting to use it.  Encrypting the file specified by "ansible_winrm_cert_pem" doesn't work either, but that's less critical.

##### STEPS TO REPRODUCE

```yaml
$ ansible windows -m win_ping --ask-vault-pass
Vault password: 
windows01.mydomain.com | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}

ansible-vault encrypt <ansible_path>/ansible/certs/winrm_client_cert.key
New Vault password: 
Confirm New Vault password: 
Encryption successful

ansible windows -m win_ping --ask-vault-pass
Vault password: 
windows01.mydomain.com | UNREACHABLE! => {
    "changed": false, 
    "msg": "certificate: HTTPSConnectionPool(host='windows01.mydomain.com', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(336265225, '_ssl.c:341: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib'),))", 
    "unreachable": true
}

$ ansible-vault decrypt <ansible_path>/ansible/certs/winrm_client_cert.key
Vault password: 
Decryption successful

$ ansible windows -m win_ping --ask-vault-pass
Vault password: 
windows01.mydomain.com | SUCCESS => {
    "changed": false, 
    "ping": "pong"
}
```

##### EXPECTED RESULTS

win_ping should give SUCCESS when using ansible-vault encrypted data for files specified by the ansible_winrm_cert_pem and ansible_winrm_cert_key_pem variables

##### ACTUAL RESULTS

win_ping gives UNREACHABLE, and the error message suggests that it ran into trouble because the supplied file is not accepted by the system being connected to (no surprise there since it's not in PEM format).  It seems like it needs to test if the file supplied has been encrypted, and decrypt it using the vault password before using it to make the connection if so.

```
windows01.mydomain.com | UNREACHABLE! => {
    "changed": false, 
    "msg": "certificate: HTTPSConnectionPool(host='windows01.mydomain.com', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(336265225, '_ssl.c:341: error:140B0009:SSL routines:SSL_CTX_use_PrivateKey_file:PEM lib'),))", 
    "unreachable": true
}
```
