### ISSUE TITLE
(P2) nxos_vpc not idempotent for delay_restore

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27522]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vpc

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I2(5)

##### SUMMARY
if we try to configure delay_restore property using nxos_vpc, it is not idempotent. The issue seems to be that the get method is using "show vpc" command which does not show the delay restore properly. It is advisable to use "show running-config | section vpc" to get accurate configuration.

##### STEPS TO REPRODUCE
playbook:

```
- block:
  - name: enable feature vpc
    nxos_feature:
      feature: vpc
      state: enabled
      provider: "{{ cli }}"

  - name: Ensure ntc VRF exists on switch
    nxos_vrf:
      vrf: ntc
      provider: "{{ cli }}"

  - name: Configure vpc
    nxos_vpc: &conf_vpc
      state: present
      domain: 100
      role_priority: 500
      system_priority: 2000
      pkl_dest: 192.168.100.4
      pkl_src: 10.1.100.20
      pkl_vrf: ntc
      peer_gw: true
      delay_restore: 5
      auto_recovery: true
      provider: "{{ cli }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Conf Idempotence"
    nxos_vpc: *conf_vpc
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: remove vpc
    nxos_vpc: &rem_vpc
      state: absent
      domain: 100
      role_priority: 32667
      system_priority: 2000
      pkl_dest: 192.168.100.4
      pkl_src: 10.1.100.20
      pkl_vrf: ntc
      peer_gw: true
      delay_restore: 5
      auto_recovery: false
      provider: "{{ cli }}"
    register: result

  - assert: *true

  - name: "Remove Idempotence"
    nxos_vpc: *rem_vpc
    register: result

  - assert: *false

  always:
  - name: remove vrf
    nxos_vrf:
      vrf: ntc
      state: absent
      provider: "{{ cli }}"
    ignore_errors: yes

  - name: disable feature vpc
    nxos_feature:
      feature: vpc
      state: disabled
      provider: "{{ cli }}"
    ignore_errors: yes
```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com      : ok=45   changed=12   unreachable=0    failed=0 
```

##### ACTUAL RESULTS
```
TASK [nxos_vpc : Conf Idempotence] ********************************************************************************************************************
changed: [n9k.example.com]

TASK [nxos_vpc : assert] ******************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {
    "assertion": "result.changed == false",
    "changed": false,
    "evaluated_to": false,
    "failed": true
}

```
