### ISSUE TITLE
Execute multiple services on a single host by playbook

### ISSUE THREAD

**Issue by mesopodamia** [ansible/ansible#27539]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.3.1.0
```

##### INVENTORY

demo.yml

```
{
  "app.source.1": {
    "hosts": [
      "192.168.1.100"
    ],
    vars: {
    ansible_expr: "app.source.1"
    }
  },
  "app.source.2": {
    "hosts": [
      "192.168.1.101"
    ],
    "vars": {
    ansible_expr: "app.source.2"
    }
  },
}
```

##### STEPS TO REPRODUCE

when I set the host variable is  app.source.* To match the host
execute the instruction only a orders can be completed
and can not be completed several times
```
ansible-playbook demo.yml -e "host=app.source.*"
```

##### PLAYBOOK

```yaml
- hosts: "{{host}}"
  gather_facts: no
  tasks:
    - name:
      shell: echo {{ansible_expr}} >> /tmp/test.txt
```

##### EXPECTED RESULTS
i want the content is 
```
app.source.1
app.source.2
``` 

##### ACTUAL RESULTS
```
app.source.2
```
