### ISSUE TITLE
nxos_vpc confirmation prompt documentation needed

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible#27562]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_vpc

##### ANSIBLE VERSION

```
ansible 2.4.0 (nxos_vpc ade593da52) last updated 2017/08/01 18:48:09 (GMT +550)
  config file = /home/tguha/RHWork/ansible/hacking/example/ansible.cfg
  configured module search path = [u'/home/tguha/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/tguha/RHWork/ansible/lib/ansible
  executable location = /home/tguha/RHWork/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 12 2017, 17:59:37) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```

##### OS / ENVIRONMENT

NX-OS 7.3
##### SUMMARY

nxos_vpc fails on confirmation prompt on a particular param `peer_gw` (peer-gateway). 
After testing this manually it is confirmed that peer-gateway does ask for confirmation on both nxapi and cli transport.
same with peer-gateway `false`.

##### STEPS TO REPRODUCE

```
    - name: Configure vpc port channel
      nxos_vpc:
        domain: 100
        role_priority: 32667
        system_priority: 2000
        peer_gw: true
        pkl_src: 10.1.100.2
        pkl_dest: 192.168.100.4
        auto_recovery: true
        provider: "{{ nxapi }}"
```

##### EXPECTED RESULTS

nxos_vpc should work
##### ACTUAL RESULTS

Fails on confirmation prompt

```
    "msg": "CLI execution error", 
    "output": [
        {
            "body": {}, 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "body": {}, 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "body": "Warning: \n Enables restoring of vPCs in a peer-detached state after reload, will wait for 240 seconds to determine if peer is un-reachable\n", 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "clierror": "\nThis peer-gateway config may cause traffic loss. Do you want to continue (y/n)? [[n] \n\n\n", 
            "code": "400", 
            "msg": "CLI execution error"
        }
    ], 
```

**Comment by ansibot** [comment]
cc @GGabriele @jedelman8 @mikewiebe @privateip @rahushen @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
Since `peer-gateway` asks for confirmation, a way to handle this would be passing `terminal dont-ask` as command. `dont-ask` takes the default answer.
```
    - name: Disable prompt
      nxos_command:
        commands: terminal dont-ask

    - name: Configure vpc port channel
      nxos_vpc:
        domain: 100
        role_priority: 32667
        system_priority: 2000
        peer_gw: true
        pkl_src: 10.1.100.2
        pkl_dest: 192.168.100.4
        auto_recovery: true
```
this way `nxos_vpc` won't fail.
