### ISSUE TITLE
junos_netconf fails to disable netconf port

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#27567]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- junos_netconf

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY

Setting junos netconf port fails to disable communication over the default junos netconf port. 

##### STEPS TO REPRODUCE

run junos integration tests `ansible-playbook -i inventory.network -k -vvvv -u ansible junos.yaml --diff -e limit_to=junos_netconf`

```yaml
- name: idempotent tests
  junos_netconf:
    state: present
    netconf_port: 8080
    provider: "{{ cli }}"
  register: result

- assert:
    that:
      - "result.changed == false"

- name: Ensure we can communicate over 8080
  junos_command:
    rpcs: get-software-information
    provider: "{{ netconf }}"
    port: 8080

# This protects against the port override above not being honoured and a bug setting the port
- name: Ensure we can NOT communicate over default port
  junos_command:
    rpcs: get-software-information
    provider: "{{ netconf }}"
  register: result
  ignore_errors: true

- assert:
    that:
      - "result.failed == true"
      - "'unable to connect to' in result.msg"

- name: Set back netconf to default port
  junos_netconf:
    state: present
    provider: "{{ cli }}"
  register: result
```

##### ACTUAL RESULTS

```

```
