### ISSUE TITLE
junos_vrf: assertion failed

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#27585]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
devel
```

##### SUMMARY

`+   test-1` not in result.diff.prepared

##### STEPS TO REPRODUCE

`ansible-playbook -i inventory.network -k -vvvv -u ansible junos.yaml --diff -e limit_to=junos_vrf`

```yaml
- name: Configure vrf and its parameter
  junos_vrf:
    name: test-1
    description: test-vrf-1
    interfaces:
          - ge-0/0/6
          - ge-0/0/5
    rd: 3.3.3.3:10
    target: target:65513:111
    state: present
    provider: "{{ netconf }}"
  register: result

- assert:
    that:
      - "result.changed == true"
      - "'+   test-1' in result.diff.prepared"
      - "'+       description test-vrf-1;' in result.diff.prepared"
      - "'+       instance-type vrf;' in result.diff.prepared"
      - "'+       interface ge-0/0/5.0;' in result.diff.prepared"
      - "'+       interface ge-0/0/6.0;' in result.diff.prepared"
      - "'+       route-distinguisher 3.3.3.3:10;' in result.diff.prepared"
      - "'+       vrf-target target:65513:111;' in result.diff.prepared"

```

##### ACTUAL RESULTS

```

TASK [junos_vrf : assert] ******************************************************
task path: /Users/dnewswan/code/concurrent_ci/ansible/test/integration/targets/junos_vrf/tests/netconf/basic.yaml:23
fatal: [vsrx01]: FAILED! => {
    "assertion": "'+   test-1' in result.diff.prepared", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```
