### ISSUE TITLE
(P2) nxos_vrf_af not idempotent

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27595]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vrf_af

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I4(6)

##### SUMMARY
- nxos_vrf_af is not idempotent. It keeps changing the configuration repeatedly. This is true whether route_target_both_auto_evpn property is present or not. Changed the title accordingly.
- There is one issue worth mentioning here. The address-family identifier (AFI) can be ipv4 or ipv6. However, the sub address-family identifier (SAFI) can only be unicast for vrf context. multicast option is there for "router bgp" but not for "vrf context". I am not sure why multicast is listed as an option here. Please verify this and remove it. If we run playbook with the "multicast" option on nxos_vrf_af, it always throws invalid command.

##### STEPS TO REPRODUCE
Playbook:

```
- name: Configure feature bgp
  nxos_feature:
    feature: bgp
    state: enabled
    provider: "{{ cli }}"

- name: Configure feature nv overlay
  nxos_config:
    commands: "feature nv overlay"
    provider: "{{ cli }}"

- name: Configure nv overlay evpn
  nxos_config:
    commands: "nv overlay evpn"
    provider: "{{ cli }}"

- block:
  - name: Configure vrf af
    nxos_vrf_af: &configure
      vrf: ansible
      afi: ipv4
      safi: unicast
      route_target_both_auto_evpn: true
      provider: "{{ cli }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Conf Idempotence"
    nxos_vrf_af: *configure
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: Remove vrf af
    nxos_vrf_af: &remove
      vrf: ansible
      afi: ipv4
      safi: unicast
      route_target_both_auto_evpn: true
      state: absent
      provider: "{{ cli }}"
    register: result

  - assert: *true

  - pause:
      seconds: 30

  - name: "Remove Idempotence"
    nxos_vrf_af: *remove
    register: result

  - assert: *false

  always:
  - name: Remove feature bgp
    nxos_feature:
      feature: bgp
      state: disabled
      provider: "{{ cli }}"

  - name: Remove feature nv overlay
    nxos_config:
      commands: "no feature nv overlay"
      provider: "{{ cli }}"
    ignore_errors: yes

  - name: Remove nv overlay evpn
    nxos_config:
      commands: "no nv overlay evpn"
      provider: "{{ cli }}"
    ignore_errors: yes

```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com       : ok=22   changed=5    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
TASK [nxos_vrf_af : Conf Idempotence] *****************************************************************************************************************
changed: [n9k.example.com]                                                                                                                        

TASK [nxos_vrf_af : assert] ***************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {                                                                                                            
    "assertion": "result.changed == false",                                                                                                            
    "changed": false,                                                                                                                                  
    "evaluated_to": false,                                                                                                                             
    "failed": true                                                                                                                                     
}                     
```
