### ISSUE TITLE
possible bug on using new style (dict-name-only) complex args with loops

### ISSUE THREAD

**Issue by b6d** [ansible/ansible#2760]
Ansible Version: `ansible 1.2 (devel 521375a7fe) last updated 2013/04/23 21:11:13 (GMT +200)`

This might be related to issue #2743 from a few commits earlier: I get the same error (`ValueError: dictionary update sequence element #0 has length 1; 2 is required`) when using `args: var`-style complex args inside a with_items-loop. (`args: $var`-style works for me.)

Here is a basic playbook that might help to reproduce this behaviour:

```

---
- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  vars:
    - my_args:
       msg: foo
    - my_args_list:
       - msg: bar
       - msg: baz
  tasks:
    - name: "this works"
      action: debug
      args: my_args

    - name: "this works"
      action: debug
      args: $item
      with_items: my_args_list

    - name: "this doesn't"
      action: debug
      args: item
      with_items: my_args_list
```

(I have not tested this with other forms of loops)
