### ISSUE TITLE
(P2) nxos_vrf_interface is not idempotent while removing and throws errors

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27600]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vrf_interface

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I2(5)

##### SUMMARY
While deleting nxos_vrf_interface, it is not idempotent and throws error.

##### STEPS TO REPRODUCE
Playbook:

```
- block:
  - name: put interface in L3
    nxos_config:
      commands:
        - no switchport
      parents:
        - "interface ethernet1/1"
      match: none
      provider: "{{ cli }}"

  - name: Ensure vrf ntc exists on interface
    nxos_vrf_interface: &configure
      vrf: ntc
      interface: ethernet1/1
      state: present
      provider: "{{ cli }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Conf Idempotence"
    nxos_vrf_interface: *configure
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: Ensure ntc VRF does not exist on interface
    nxos_vrf_interface: &remove
      vrf: ntc
      interface: ethernet1/1
      state: absent
      provider: "{{ cli }}"
    register: result

  - assert: *true

  - name: "Remove Idempotence"
    nxos_vrf_interface: *remove
    register: result

  - assert: *false

  always:
  - name: put interface in default mode
    nxos_config:
      lines: "default interface ethernet1/1"
      provider: "{{ cli }}"
      match: none
    ignore_errors: yes

```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com      : ok=22   changed=4    unreachable=0    failed=0
```
##### ACTUAL RESULTS
```
fatal: [n9k.example.com]: FAILED! => {"changed": false, "existing_vrf": "", "failed": true, "interface": "ethernet1/1", "msg": "The VRF you are trying to remove from the interface does not exist on that interface.", "proposed_vrf": "ntc"}
```
