### ISSUE TITLE
(P1) nxos_install_os errors for both cli and nxapi transports

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27604]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_install_os

##### NXOS VERSION
N9K Upgrade from 7.0(3)I5(3) to 7.0(3)I6(1) and vice-versa.
N7K Upgrade from 7.0(3)D1(1) to 8.0.1 and vice-versa

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel aa19563388) last updated 2017/08/01 09:45:40 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook demonstrates the issues.

* CLI Issue:
  **NOTE:** The key to reproduce this issue is setting the `timeout:` property in group_vars when defining the provider attributes to a value large enough to allow the `install all` command to complete
  * The upgrade does progress in the cli case.

* NXAPI Issue:
  * The module simply errors out and does not upgrade.

```yaml
---
cli:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_cli_user | default('admin') }}"
  password: "{{ nxos_cli_pass | default('admin') }}"
  transport: cli
  # I can set the timeout here and it seems to work
  timeout: 200

nxapi:
  host: "{{ inventory_hostname }}"
  username: "{{ nxos_nxapi_user | default('admin') }}"
  password: "{{ nxos_nxapi_pass | default('admin') }}"
  transport: nxapi
  timeout: 200
  use_ssl: no
```

I would prefer to set the timeout under the nxos_install_os task below but for whatever reason this does not seem to have the desired effect.

```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_os_install sanity test"

- block:
  - name: Install OS
    nxos_install_os:
      system_image_file: nxos.7.0.3.I5.3.bin
      #timeout: 200 - Setting the timeout here seems to have no effect.
      provider: "{{ connection }}"

  rescue:
  - name: Wait for device to perform checks
    wait_for:
      port: 22
      state: stopped
      timeout: 300
      delay: 60
      host: "{{ inventory_hostname }}"
  - name: Wait for device to come back up
    wait_for:
      port: 22
      state: started
      timeout: 300
      delay: 60
      host: "{{ inventory_hostname }}"
  - name: Check installed OS
    nxos_command:
      commands:
        - show version | json
      provider: "{{ connection }}"
    register: output
  - assert:
      that:
        - output['stdout'][0]['kickstart_ver_str'] == '7.0(3)I5(3)'

  always:
  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_os_install sanity test"
```

##### CLI Problem N9K
```shell
TASK [nxos_install_os : debug] *************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_install_os/tests/common/sanity.yaml:2
ok: [n9k.example.com] => {
    "msg": "START TRANSPORT:cli nxos_os_install sanity test"
}

TASK [nxos_install_os : Install OS] ********************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_install_os/tests/common/sanity.yaml:5
<n9k.example.com> connection transport is cli
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> socket_path: /root/.ansible/pc/4cc10f215f
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/nxos.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/connection.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/urls.py
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_install_os.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501616314.19-50696856250500 `" && echo ansible-tmp-1501616314.19-50696856250500="` echo $HOME/.ansible/tmp/ansible-tmp-1501616314.19-50696856250500 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmpX1RWrE TO /root/.ansible/tmp/ansible-tmp-1501616314.19-50696856250500/nxos_install_os.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501616314.19-50696856250500/ /root/.ansible/tmp/ansible-tmp-1501616314.19-50696856250500/nxos_install_os.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501616314.19-50696856250500/nxos_install_os.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501616314.19-50696856250500/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_wydU7C/ansible_module_nxos_install_os.py", line 232, in <module>
    main()
  File "/tmp/ansible_wydU7C/ansible_module_nxos_install_os.py", line 220, in main
    if not already_set(install_state,
UnboundLocalError: local variable 'install_state' referenced before assignment

fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_wydU7C/ansible_module_nxos_install_os.py\", line 232, in <module>\n    main()\n  File \"/tmp/ansible_wydU7C/ansible_module_nxos_install_os.py\", line 220, in main\n    if not already_set(install_state,\nUnboundLocalError: local variable 'install_state' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
##### CLI Problem N7K
```shell
TASK [nxos_install_os : debug] ******************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_install_os/tests/common/sanity.yaml:2
ok: [n7k.example.com] => {
    "msg": "START TRANSPORT:cli nxos_os_install sanity test"
}

TASK [nxos_install_os : Install OS] *************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_install_os/tests/common/sanity.yaml:5
<n7k.example.com> connection transport is cli
<n7k.example.com> using connection plugin network_cli
<n7k.example.com> socket_path: /root/.ansible/pc/1140474c5f
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/nxos.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/connection.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/urls.py
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_install_os.py
<n7k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n7k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501619444.49-153231921540103 `" && echo ansible-tmp-1501619444.49-153231921540103="` echo $HOME/.ansible/tmp/ansible-tmp-1501619444.49-153231921540103 `" ) && sleep 0'
<n7k.example.com> PUT /tmp/tmpsHzCtq TO /root/.ansible/tmp/ansible-tmp-1501619444.49-153231921540103/nxos_install_os.py
<n7k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501619444.49-153231921540103/ /root/.ansible/tmp/ansible-tmp-1501619444.49-153231921540103/nxos_install_os.py && sleep 0'
<n7k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501619444.49-153231921540103/nxos_install_os.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501619444.49-153231921540103/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_x6Qdto/ansible_module_nxos_install_os.py", line 232, in <module>
    main()
  File "/tmp/ansible_x6Qdto/ansible_module_nxos_install_os.py", line 220, in main
    if not already_set(install_state,
UnboundLocalError: local variable 'install_state' referenced before assignment

fatal: [n7k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_x6Qdto/ansible_module_nxos_install_os.py\", line 232, in <module>\n    main()\n  File \"/tmp/ansible_x6Qdto/ansible_module_nxos_install_os.py\", line 220, in main\n    if not already_set(install_state,\nUnboundLocalError: local variable 'install_state' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

##### NXAPI Problem
```shell
TASK [nxos_install_os : debug] *************************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_install_os/tests/common/sanity.yaml:2
ok: [n9k.example.com] => {
    "msg": "START TRANSPORT:nxapi nxos_os_install sanity test"
}

TASK [nxos_install_os : Install OS] ********************************************************************************************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_install_os/tests/common/sanity.yaml:5
<n9k.example.com> connection transport is nxapi
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/basic.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/nxos.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/_text.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/parsing/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/pycompat24.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/six/__init__.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/connection.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/network_common.py
Using module_utils file /root/agents-ci/ansible/lib/ansible/module_utils/urls.py
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_install_os.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1501616959.34-108931789583887 `" && echo ansible-tmp-1501616959.34-108931789583887="` echo $HOME/.ansible/tmp/ansible-tmp-1501616959.34-108931789583887 `" ) && sleep 0'
<n9k.example.com> PUT /tmp/tmpIWBQAS TO /root/.ansible/tmp/ansible-tmp-1501616959.34-108931789583887/nxos_install_os.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1501616959.34-108931789583887/ /root/.ansible/tmp/ansible-tmp-1501616959.34-108931789583887/nxos_install_os.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1501616959.34-108931789583887/nxos_install_os.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1501616959.34-108931789583887/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_J0z0HK/ansible_module_nxos_install_os.py", line 232, in <module>
    main()
  File "/tmp/ansible_J0z0HK/ansible_module_nxos_install_os.py", line 208, in main
    current_boot_options = get_boot_options(module)
  File "/tmp/ansible_J0z0HK/ansible_module_nxos_install_os.py", line 145, in get_boot_options
    boot_options_raw_text = body.split('Boot Variables on next reload')[1]
AttributeError: 'dict' object has no attribute 'split'

fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_J0z0HK/ansible_module_nxos_install_os.py\", line 232, in <module>\n    main()\n  File \"/tmp/ansible_J0z0HK/ansible_module_nxos_install_os.py\", line 208, in main\n    current_boot_options = get_boot_options(module)\n  File \"/tmp/ansible_J0z0HK/ansible_module_nxos_install_os.py\", line 145, in get_boot_options\n    boot_options_raw_text = body.split('Boot Variables on next reload')[1]\nAttributeError: 'dict' object has no attribute 'split'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
