### ISSUE TITLE
get_url should support acquiring checksum from remote source

### ISSUE THREAD

**Issue by wrouesnel** [ansible/ansible#27617]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel b629e36d3b) last updated 2017/07/20 15:14:54 (GMT +1100)
  config file = None
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/will/src/ansible-work/ansible/lib/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```
##### OS / ENVIRONMENT
N/A

##### SUMMARY
`get_url`'s checksum parameter currently just takes a literal value. When using an artifact store such as artifactory, or the schema many open source projects follow however, `<url>.md5` or similar usually yields the checksum of an artifact. Other systems correctly set ETag to a unique identifier.

`get_url` should allow using this metadata to determine if a file has changed and to manage downloads accordingly. This would allow for efficient change detection behaviour without the associated network traffic.

##### STEPS TO REPRODUCE
Proposal:
```yaml
# Full path to a sha1sum
- name: download foo.conf
  get_url:
    url: http://example.com/path/file.conf
    dest: /etc/foo.conf
    mode: 0440
    checksum_url: http://example.com/path/file.conf.sha1sum
# Checksum Header (send a HEAD request first)
- name: download foo.conf
  get_url:
    url: http://example.com/path/file.conf
    dest: /etc/foo.conf
    mode: 0440
    checksum_header: ETag
# Header caching (support when ETag is unique but nothing identifiable) - this would be an advanced use
- name: download foo.conf
  get_url:
    url: http://example.com/path/file.conf
    dest: /etc/foo.conf
    mode: 0440
    changed_header: ETag
    changed_cache_file: /root/file.conf.etag
# Check for changes using remote file, but confirm checksum is whatever we supply locally
# i.e. fail-fast - check local file, check if remote file checksum matches, download only if it would work.
# Makes large file failures fast.
- name: download foo.conf
  get_url:
    url: http://example.com/path/file.conf
    dest: /etc/foo.conf
    mode: 0440
    checksum_url: http://example.com/path/file.conf.sha1sum
    checksum: 4e1243bd22c66e76c2ba9eddc1f91394e57f9f83
```
