### ISSUE TITLE
Blockinfile not returning backup file name with backup: yes.

### ISSUE THREAD

**Issue by ecsumed** [ansible/ansible#27626]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [<redacted>]
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```
##### OS / ENVIRONMENT
Ubuntu 14.04 trusty

##### SUMMARY
The blockinfile module should return the name of the backed up file when used with "backup: yes" and "register: result". Instead the registered variable is empty even though a backup file is created.

##### STEPS TO REPRODUCE
Inventory:
`localhost ansible_connection=local`

Playbook:
```---
- hosts: localhost
  gather_facts: off

  tasks:
    - file:
        path: /tmp/test
        state: touch

    - name: update line
      lineinfile:
        dest: /tmp/test
        regexp: "old_line"
        line: "new_line"
        backup: yes
      register: lineinfile_result

    - debug: msg="{{ lineinfile_result }}"

    - name: update block
      blockinfile:
        dest: /tmp/test
        backup: yes
        block: |
          block content
      register: blockinfile_result

    - debug: msg="{{ blockinfile_result }}"

```

##### EXPECTED RESULTS
"blockinfile_result" should contain a "backup" key with the name of the backed up file just as with "lineinfile_result". 

##### ACTUAL RESULTS
```
ansible-playbook -i inventory local.yml

PLAY [localhost] **********************************************************************************************************************

TASK [file] ***************************************************************************************************************************
changed: [localhost]

TASK [update line] ********************************************************************************************************************
changed: [localhost]

TASK [debug] **************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "backup": "/tmp/test.27030.2017-08-02@14:01:58~", 
        "changed": true, 
        "diff": [
            {
                "after": "", 
                "after_header": "/tmp/test (content)", 
                "before": "", 
                "before_header": "/tmp/test (content)"
            }, 
            {
                "after_header": "/tmp/test (file attributes)", 
                "before_header": "/tmp/test (file attributes)"
            }
        ], 
        "msg": "line added"
    }
}

TASK [update block] *******************************************************************************************************************
changed: [localhost]

TASK [debug] **************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "msg": "Block inserted"
    }
}

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=0 
```

**Comment by ansibot** [comment]
cc @yaegashi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by richard-mck** [comment]
The same issue is present in Ansible 2.7.2;

**ISSUE TYPE**
    Bug Report

**COMPONENT NAME**
blockinfile

**ANSIBLE VERSION**
ansible 2.7.2
  config file = redacted/ansible.cfg
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  python version = 2.7.12 (default, Nov 12 2018, 14:36:49) [GCC 5.4.0 20160609]

**PLAYBOOK**
```yaml
- name: install nagios on hosts
  hosts: "{{host_group}}"
  remote_user: "{{ username }}"
  gather_facts: no
  tasks:
  - name: modify firewall ports
    blockinfile:
      path: /etc/init.d/firewall
      backup: yes
      insertbefore: '((echo)\s+(-)(en)\s+("   loading modules: "))'
      marker: "# {mark} ANSIBLE MANAGED BLOCK nagios ports"
      block: |

        NAGIOS_PORT="5666"

    register: firewall_ports
  - name: print result of block change
    debug:
      var: firewall_ports
  - name: rename backup file
    copy:
      remote_src: yes
      src: "{{firewall_ports.backup_file}}"
      dest: /etc/init.d/firewall.{{ansible_date_time.date}}
    register: move_backup
```
**EXPECTED RESULTS**
"blockinfile_result" should contain a "backup_file" key with the name of the backed up file just as with "lineinfile_result".

**ACTUAL RESULTS**
```bash
PLAY [install nagios on hosts] ***************************************************************************************************************************************************************************************************************

TASK [modify firewall ports] *****************************************************************************************************************************************************************************************************************ok: [systems-lab] => changed=false
  msg: ''

TASK [print result of block change] **********************************************************************************************************************************************************************************************************ok: [systems-lab] =>
  firewall_ports:
    changed: false
    diff:
    - after: ''
      after_header: /etc/init.d/firewall (content)
      before: ''
      before_header: /etc/init.d/firewall (content)
    - after_header: /etc/init.d/firewall (file attributes)
      before_header: /etc/init.d/firewall (file attributes)
    failed: false
    msg: ''

TASK [rename backup file] ********************************************************************************************************************************************************************************************************************fatal: [systems-lab]: FAILED! =>
  msg: |-
    The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'backup_file'

    The error appears to have been in 'redacted/install_nagios_on_hosts.yaml': line 78, column 5, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:

      - name: rename backup file
        ^ here
```

I note there's an outstanding pull request to fix this issue, has there been any traction on getting that through?
