### ISSUE TITLE
lxc_container module does not support lxc2

### ISSUE THREAD

**Issue by LordAro** [ansible/ansible#27628]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lxc_container

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
lxc_container module does not support lxc2, which has dropped its "extra" binaries like `lxc-copy` and `lxc-create` in favour of a unified binary, using `lxc copy` and `lxc launch` respectively.

The lxd_container module is not a reasonable replacement for this as its API is rather different (notably for me, missing any sort of "container_command" option) (And lxd's own documentation uses the lxc client)

##### STEPS TO REPRODUCE
* Have lxc2/lxd installed (xenial-backports currently comes with 2.15)
* Try to create container
* Fail

```yaml
- name: Create a started container
  lxc_container:
    name: test-container-started
    container_log: true
    template: ubuntu
    state: started
    template_options: --release trusty
```

(Taken from the documentation page)

##### EXPECTED RESULTS
Container to be created

##### ACTUAL RESULTS
```
failed: [lxchost.example.com] (item=testhost) => {"failed": true, "item": "testhost", "msg": "Failed to find required executable lxc-create in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"}
```
