### ISSUE TITLE
systemd --user unit-file "failure 1 during daemon-reload: Failed to connect to bus"

### ISSUE THREAD

**Issue by kees-closed** [ansible/ansible#27631]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
systemd

##### ANSIBLE VERSION
```
ansible 2.3.1.0                   
  config file = /home/keesj/git/ansible/ansible.cfg                 
  configured module search path = Default w/o overrides             
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### CONFIGURATION
No special configs in the scope of this bug.

##### OS / ENVIRONMENT
Ansible is ran from Fedora 25/26, managing hosts on Fedora 25/26 and Debian.

##### SUMMARY
I want to start the gpg-agent as a non-root user, for this the --user switch is needed for the systemctl command. This switch is incorporated in Ansible in the systemd module. However when used I get the error below:
```
RUNNING HANDLER [common : restart gpg-agent] ********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "failure 1 during daemon-reload: Failed to connect to bus: No such file or directory\n"}
...ignoring    
```

##### STEPS TO REPRODUCE
Use a handler similar as this one:
```
- name: restart gpg-agent
  systemd: name=gpg-agent enabled=yes state=restarted user=True daemon_reload=True
  ignore_errors: True
```
I also tried with these lines below, both in the handler and in the task, no use.
```
  become: True
  become_user: {{ my_user }}
```

##### EXPECTED RESULTS
I would like to enable and start a custom systemd task for a non-root user with Ansible.

##### ACTUAL RESULTS
I get an error that the file can't be found. I don't get any more details with -vvvv.

**Comment by ghost** [comment]
This isue somehow resembles on [**this**](https://answers.launchpad.net/ubuntu/+source/systemd/+question/287454) launchpad bug report, where `systemd --user` fails since either `XDG_RUNTIME_DIR` hasn't been set for the user (I'd try that one on your playbook) or the service takes too long to report back the started status.

**Comment by kees-closed** [comment]
Stuff below doesn't work, but it should work as root with the --global switch.

```
- name: enable gpg systemd sockets
  systemd: name={{ item }} enabled=yes user=yes daemon_reload=yes
  with_items:
    - gpg-agent.socket
    - gpg-agent-ssh.socket
```

Some more information about this [here](https://dev.gnupg.org/source/gnupg/browse/master/doc/examples/systemd-user/). These commands simply work as root and should also work with Ansible.
* `systemctl --user --global enable gpg-agent.socket`
* `systemctl --user --global enable gpg-agent-ssh.socket`

**Comment by traverseda** [comment]
```yaml
- name: Register uid of {{name}}
  command: id -u {{name}}
  register: uid

- name: Enable systemd user service
  become: True
  become_user: "{{name}}"

  systemd:
    daemon_reload: True
    name: example.service
    enabled: True
    user: True
    state: restarted
  environment:
    XDG_RUNTIME_DIR: /run/user/{{uid}}
```

Works, but only when I run it as a local. When I run it normally, I get 'failure 1 during daemon-reload: Failed to connect to bus: Argument list too long'.

The only documentation I can find relating to that relates to the recent CVE, and is behind a redhat paywall...

**Comment by traverseda** [comment]
```yaml
- name: Register uid of {{name}}
  command: id -u {{name}}
  register: uid

- name: Enable systemd services for uwsgi app
  become: True
  become_user: "{{name}}"

  systemd:
    daemon_reload: True
    name: example.service
    enabled: True
    user: True
    state: restarted
  environment:
    XDG_RUNTIME_DIR: /run/user/{{uid.stdout}}
```

Fixes this.

**Comment by deckardbsd** [comment]
I have the same error. The funny thing is that if I run the playbook using ansible-playbook all works fine, but if I'm using the python api, then I get this error.
ansible version 2.7.5

**Comment by bcoca** [comment]
fixed via #50607

**Comment by deckardbsd** [comment]
```
- name: Reload systemd for the user and enable and start csserver.service            
  systemd:                                                                           
      scope: user                                                                    
      daemon_reload: yes                                                             
  environment:                                                                       
      XDG_RUNTIME_DIR: "/run/user/{{ uid.stdout }}"                                                                                                                                                                                                                                                                          
  tags:                                                                              
      - systemd_user_reload
```

Still does not work.
