### ISSUE TITLE
nxos_snmp_user not idempotent

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27659]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_snmp_user

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I2(5)

##### SUMMARY
nxos_snmp_user is not idempotent when deleting users.

##### STEPS TO REPRODUCE
playbook:

```
- name: Create snmp user
  nxos_snmp_user: &create
    user: ntc
    group: network-operator
    authentication: md5
    pwd: Testing1%
    privacy: HelloU$er1
    encrypt: true
    provider: "{{ cli }}"
  register: result

- assert: &true
    that:
      - "result.changed == true"

- name: "Conf Idempotence"
  nxos_snmp_user: *create
  register: result

- assert: &false
    that:
      - "result.changed == false"

- name: delete snmp user
  nxos_snmp_user: &remove
    user: ntc
    group: network-operator
    authentication: md5
    pwd: Testing1%
    privacy: HelloU$er1
    encrypt: true
    state: absent
    provider: "{{ cli }}"
  register: result

- assert: *true

- name: "Remove Idempotence"
  nxos_snmp_user: *remove
  register: result

- assert: *false
```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com      : ok=16   changed=3    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
TASK [nxos_snmp_user : Remove Idempotence] ************************************************************************************************************                                                                                                                      
ok: [n9k.example.com]                                                                                                                   

TASK [nxos_snmp_user : assert] ************************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {                                                                                                           
    "assertion": "result.changed == true",                                                                                                             
    "changed": false,                                                                                                                                  
    "evaluated_to": false,                                                                                                                             
    "failed": true                                                                                                                                     
}                          
```
