### ISSUE TITLE
(P2) nxos_udld_interface is not idempotent when mode = enabled

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27654]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_udld_interface

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I2(5)

##### SUMMARY
When we set mode = enabled on nxos_udld_interface, it is not idempotent.

##### STEPS TO REPRODUCE
Playbook:

```
- block:
  - name: "Enable feature udld"
    nxos_feature: 
      feature: udld
      state: enabled
      provider: "{{ cli }}"

  - name: ensure interface is configured to be in aggressive mode
    nxos_udld_interface: &conf1
      interface: ethernet1/1
      mode: aggressive
      state: present
      provider: "{{ cli }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Conf1 Idempotence"
    nxos_udld_interface: *conf1
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: Remove the aggressive config only if it's currently in aggressive mode and then disable udld (switch default)
    nxos_udld_interface: &remove
      interface: ethernet1/1
      mode: aggressive
      state: absent
      provider: "{{ cli }}"
    register: result

  - assert: *true

  - name: "remove Idempotence"
    nxos_udld_interface: *remove
    register: result

  - assert: *false

  - name: ensure interface has aggressive mode enabled
    nxos_udld_interface: &conf2
      interface: ethernet1/1
      mode: enabled
      state: present
      provider: "{{ cli }}"

  - assert: *true

  - name: "conf2 Idempotence"
    nxos_udld_interface: *conf2
    register: result

  - assert: *false

  when: not (platform | search('N9K-F'))

  always:
  - name: "Disable udld"
    nxos_feature: 
      feature: udld
      state: disabled
      provider: "{{ cli }}"
    ignore_errors: yes
```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com      : ok=25   changed=5    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
TASK [nxos_udld_interface : ensure interface has aggressive mode enabled] *****************************************************************************
changed: [n9k.example.com]

TASK [nxos_udld_interface : assert] *******************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {
    "assertion": "result.changed == true",
    "changed": false,
    "evaluated_to": false,
    "failed": true
}
```
