### ISSUE TITLE
nxos_vtp_domain not idempotent

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27663]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vtp_domain

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I2(5)

##### SUMMARY
nxos_vtp_domain is not idempotent. it keeps setting the domain always.

##### STEPS TO REPRODUCE
playbook:

```
- block:
  - name: enable feature vtp
    nxos_feature:
      feature: vtp
      state: enabled
      provider: "{{ cli }}"

  - name: configure vtp domain
    nxos_vtp_domain: &configure
      domain: ntc
      provider: "{{ cli }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"
  
  - name: "Conf Idempotence"
    nxos_vtp_domain: *configure
    register: result

  - assert: &false
      that:
        - "result.changed == true"

  always:
  - name: disable feature vtp
    nxos_feature:
      feature: vtp
      state: disabled
      provider: "{{ cli }}"
```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com      : ok=18   changed=2    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
TASK [nxos_vtp_domain : Conf Idempotence] *************************************************************************************************************
ok: [n9k.example.com]                                                                                                                   

TASK [nxos_vtp_domain : assert] ***********************************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {                                                                                                           
    "assertion": "result.changed == true",                                                                                                             
    "changed": false,                                                                                                                                  
    "evaluated_to": false,                                                                                                                             
    "failed": true                                                                                                                                     
}              
```
