### ISSUE TITLE
(P2) nxos_vtp_password is not idempotent while removing and throws errors

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27676]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vtp_password

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I2(5)

##### SUMMARY
While removing nxos_vtp_password, it is not idempotent and throws error.

##### STEPS TO REPRODUCE
Playbook:

```
- block:
  - name: enable feature vtp
    nxos_feature:
      feature: vtp
      state: enabled
      provider: "{{ cli }}"

  - name: configure vtp domain
    nxos_vtp_domain:
      domain: testing
      provider: "{{ cli }}"

  - name: configure vtp password
    nxos_vtp_password: &configure
      vtp_password: ntc
      state: present
      provider: "{{ cli }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"
  
  - name: "Conf Idempotence"
    nxos_vtp_password: *configure
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: remove vtp password
    nxos_vtp_password: &remove
      vtp_password: ntc
      state: absent
      provider: "{{ cli }}"
    register: result

  - assert: *true

  - name: "Remove Idempotence"
    nxos_vtp_password: *remove
    register: result

  - assert: *false

  always:
  - name: disable feature vtp
    nxos_feature:
      feature: vtp
      state: disabled
      provider: "{{ cli }}"
```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com      : ok=23   changed=6    unreachable=0    failed=0
```
##### ACTUAL RESULTS
```
TASK [nxos_vtp_password : Remove Idempotence] *********************************************************************************************************
fatal: [n9k.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "Proposed vtp password doesn't match current vtp password. It cannot be removed when state=absent. If you are trying to change the vtp password, use state=present."}
```
