### ISSUE TITLE
debug var is throwing template error

### ISSUE THREAD

**Issue by zi46** [ansible/ansible#27694]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

debug var
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

```

##### OS / ENVIRONMENT

CentOS

##### SUMMARY

Debug var is not printing the exact string and is throwing template error. 
This  used to work fine with ansible 2.0

##### STEPS TO REPRODUCE

```yaml
---
- name: set and print variable
  hosts: localhost
  any_errors_fatal: yes
  tasks:
    - name: set lb url for app slots
      set_fact: slots_url="{{'http://' + 'inter-load-balancer' + ':9877/v1'}}"

    - debug: var="{{slots_url}}"

```

##### EXPECTED RESULTS

With ansible 2.0 we used to get below result.
```
ok: [localhost] => {
    "http://inter-load-balancer:9877/v1": "VARIABLE IS NOT DEFINED!"
}
````
##### ACTUAL RESULTS

With ansible 2.3, we are getting below result. 
Because of this, the script is failing. 

```
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "template error while templating string: expected token 'end of print statement', got ':'. String: {{http://inter-load-balancer:9877/v1}}"
}

```
