### ISSUE TITLE
vmware_guest: "The number of network adapter settings in the customization specification: 0 does not match the number of network adapters present in the virtual machine: 1"

### ISSUE THREAD

**Issue by MisterRogersHaus** [ansible/ansible#27707]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

Creating a new VM from a template.

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
default configuration / ansible.cfg

##### OS / ENVIRONMENT

Ansible controller: CentOS7
Guest VM: Windows Server 2016
vSphere / ESXi: 6.5.0, using vSphere Web Client

##### SUMMARY

When executing a playbook to create multiple VM's, the first non-existing VM is created, but VMware_guest fails with the following error: "The number of network adapter settings in the customization specification: 0 does not match the number of network adapters present in the virtual machine: 1"

I get the same error regardless of whether the template used has a network adaptor (1) defined, or none defined. I've also set the state to 'poweredon', which is not observed I assume because of the error. 

If I rerun my playbook, it will correctly set the state of the now existing VM to powered on, attempt to create the next, and fail with the same error.

##### STEPS TO REPRODUCE

The below yaml snippet is executed against vSphere / ESXi 6.5.0, with a template without a network adaptor. It will create the VM (with a nic), but fail with the above error and not power on the VM.

```yaml
    - name: create database vms
      vmware_guest:
        hostname: "{{ vcenter_host }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter: "{{ vcenter_datacenter }}"
        validate_certs: no
        name: "{{ item['guest'] }}"
        state: "{{ item['state'] }}"
        template: "{{ template_name }}"
        disk:
            - size_gb: "{{ item['disk']['size'] }}"
              type: "{{ item['disk']['type'] }}"
              datastore: "{{ vcenter_datastore }}"
        hardware:
          memory_mb: "{{ item['memory'] }}"
          num_cpus: "{{ item['cpus'] }}"
          scsi: "paravirtual"
        networks:
        - name: "{{ item['network'] }}"
          type: "dhcp"
        customization:
          password: "{{ vcenter_vm_password }}"
        wait_for_ip_address: yes
      delegate_to: localhost
      register: deploy
```

##### EXPECTED RESULTS
VM is created, left in a powered on state, with the vmware_guest module returning failed=0.

##### ACTUAL RESULTS

```
failed: [localhost -> localhost] (item={u'network': u'VM Network', u'vm_role': 2, u'cpus': 1, u'guest_id': u'windows9Server64Guest', u'state': u'poweredon', u'memory': 2048, u'disk': {u'type': u'thin', u'size': 30}, u'annotation': u'Ansible created HOPS MQ Server', u'guest': u'OA_HOPS_MQ'}) => {
    "changed": true, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cluster": null, 
            "customization": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "customvalues": [], 
            "datacenter": "NC_DEV", 
            "disk": [
                {
                    "datastore": "datastore1", 
                    "size_gb": "30", 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "/vm", 
            "force": false, 
            "guest_id": null, 
            "hardware": {
                "memory_mb": "2048", 
                "num_cpus": "1", 
                "scsi": "paravirtual"
            }, 
            "hostname": "10.80.33.190", 
            "is_template": false, 
            "name": "OA_HOPS_MQ", 
            "name_match": "first", 
            "networks": [
                {
                    "name": "VM Network", 
                    "type": "dhcp"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": null, 
            "state": "poweredon", 
            "template": "Win-Server-2016-OA-Base", 
            "template_src": "Win-Server-2016-OA-Base", 
            "username": "administrator@vsphere.local", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }
    }, 
    "item": {
        "annotation": "Ansible created HOPS MQ Server", 
        "cpus": 1, 
        "disk": {
            "size": 30, 
            "type": "thin"
        }, 
        "guest": "OA_HOPS_MQ", 
        "guest_id": "windows9Server64Guest", 
        "memory": 2048, 
        "network": "VM Network", 
        "state": "poweredon", 
        "vm_role": 2
    }, 
    "msg": "The number of network adapter settings in the customization specification: 0 does not match the number of network adapters present in the virtual machine: 1."
}
	to retry, use: --limit @/home/ironfist/hops/create_hops_vms_no_nic.retry

PLAY RECAP *****************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
```
