### ISSUE TITLE
(P1) nxos_snmp_location does work properly for transport nxapi

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#27720]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_snmp_location

##### NXOS VERSION
7.0(3)I5(3)

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 661d81ef86) last updated 2017/08/03 12:33:15 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY
The following playbook demonstrates the problem:

**NOTE:** Test passes for transport `cli`.

```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_snmp_location sanity test"

- name: Setup - Remove snmp_location if configured
  nxos_snmp_location: &remove
    location: Test
    state: absent
    provider: "{{ connection }}"
  ignore_errors: yes

- block:

  - name: Configure snmp host
    nxos_snmp_location: &config
      location: Test
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: Idempotence Check
    nxos_snmp_location: *config
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  always:
  - name: Cleanup
    nxos_snmp_location: *remove
    register: result

  - assert: *true

  - name: Cleanup Idempotence
    nxos_snmp_location: *remove
    register: result

  - assert: *false

  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_snmp_location sanity test"
```

```shell
TASK [nxos_snmp_location : debug] ***********************************************************************************************************************************************************************************************************************
ok: [n9k.example.comm] => {
    "msg": "START TRANSPORT:nxapi nxos_snmp_location sanity test"
}

TASK [nxos_snmp_location : Setup - Remove snmp_location if configured] **********************************************************************************************************************************************************************************
fatal: [n9k.example.comm]: FAILED! => {"changed": false, "failed": true, "msg": "Connection failure: timed out", "status": -1, "url": "http://n9k.example.comm:80/ins"}
...ignoring

TASK [nxos_snmp_location : Configure snmp host] *********************************************************************************************************************************************************************************************************
fatal: [n9k.example.comm]: FAILED! => {"changed": false, "failed": true, "msg": "Connection failure: timed out", "status": -1, "url": "http://n9k.example.comm:80/ins"}

TASK [nxos_snmp_location : Cleanup] *********************************************************************************************************************************************************************************************************************
fatal: [n9k.example.comm]: FAILED! => {"changed": false, "failed": true, "msg": "Connection failure: timed out", "status": -1, "url": "http://n9k.example.comm:80/ins"}
	to retry, use: --limit @/root/agents-ci/ansible/test/integration/nxos.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************
n9k.example.comm          : ok=34   changed=5    unreachable=0    failed=2   
```

If I set the timeout to 60 I don't get the timed out errors, but the configuration is not applied to the device.
