### ISSUE TITLE
replace module is not encoding agnostic anymore

### ISSUE THREAD

**Issue by mowgli** [ansible/ansible#27779]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
replace module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /home/klaus/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13+ (default, Jul 19 2017, 18:15:03) [GCC 6.4.0 20170704]
```

##### OS / ENVIRONMENT
LC_*=de_DE (without utf-8, so it is iso8859-1)

##### SUMMARY
I have the following part:
```yaml
- name: Keep all passwd-entries in /etc/password sane
  replace:
     dest: /etc/passwd
     regexp: '^([^:]+):[^:]*:'
     replace: '\1:x:'
```

This worked with earlier versions but now it fails with an error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnicodeDecodeError: 'utf8' codec can't decode byte 0xee in position 668: invalid continuation byte
```

The problem is that I have user full names in passwd that includes latin1 chars (like ï)

##### STEPS TO REPRODUCE
See above in the description

**Comment by ansibot** [comment]
cc @EvanK
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by EvanK** [comment]
This was a deliberate change (see #24861), in which the `encoding` parameter was added and defaulted to "utf-8".

Have you tried specifying an encoding, eg:

```yml
- name: Keep all passwd-entries in /etc/password sane
  replace:
     dest: /etc/passwd
     regexp: '^([^:]+):[^:]*:'
     replace: '\1:x:'
     encoding: 'iso8859-1'
```

**Comment by mowgli** [comment]
Hmm... But in many cases you cannot say which encoding is the right for the file.

In case of the /etc/passwd, it could be difference line by line.

The only safe way to handle files, is to be encoding agnostic and see the file as stream of bytes. (Another way would be to have a default of iso8859-1 (or any other latin-x code) as this include all byte values as valid. UTF-8 does not have this property that all values are valid.)

Even if the file should be UTF-8, as this is on the target system, it could hold any other byte value until it gets corrected by ansible.

**Comment by mowgli** [comment]
After reading the other PR, I think it would be much better to keep the old way (handling just bytes) unless there is a explicite encoding parameter in the task file.

That would allow to hold advance of the encoding and also be compatible with older versions (I have a setup where I have ansible 2.2 on one machine and 2.3 on another. With the current use case I have to double the task yaml as the parameter encoding is not allowed in 2.2.) And on the other hand, if you really be sure that the file has a specific encoding, you can set it.

(I am even not convinced that it is a good idea to use encoding with config files. I mean, we talk about config files, not simple text files. Config files could have parts in any encoding, even in binary. And sometimes you have to do your work on text parts of binary files to fix a broken stuff.)

**Comment by abadger** [comment]
I've put this onto the public IRC meeting agenda for discussion.  Since Ansible-1.7 we've adopted the strategy of all text being utf-8.  Not every module complied with that strategy but as bugs came up, that was the guiding principle for resolving them.  Recently, I've started taking PRs that add encoding parameters when we're operating on a file's contents.  That allows the file contents to be read and written in a single, different encoding.

You do raise use cases that are not handled by either of these strategies; I mentioned them to the other core contributors at the time we decided to make this our global strategy and we decided not to address them.

* binary data should not be handled by these modules.  If someone wants something like bbe via an ansible module we should write a special module for that.  The module will need to have some escaped format to take byte data in from yaml otherwise we'll always struggle to place every byte into the yaml file.

Mixed encoding within a file are indeed possible but we decided that although making modules handle that would be a more flexible approach, it would also make it much easier for naive users to shoot themselves in the foot. To take the replace module as a case study, the module would take an encoding parameter that operated on the parameters passed into the module rather than on the file contents.  Since the parameters are always passed in as a utf-8 json string, we eventually end up with a text string which we transform into bytes via this parameter.  we then find the following ways that the parameter can corrupt data:
  * If the user specifies a non-ascii compatible encoding, null bytes or special characters (like colon in /etc/passwd) can cause problems for the file.  (Imagine /etc/passwd if utf-16 or EBCDIC are specified as the encoding)
  * If the user doesn't know what the existing key in a file is encoded as, there is a chance for "duplicated" entries.  With a file mapping usernames to attributes, for instance, if the username exists in the file using latin-1 but the playbook has an encoding specified of utf-8, then a second username mapping will be created as the two sets of bytes are unequal.
  * It becomes very easy for a user to make single-encoding files into multiple encoding files.  Since best practice is to move towards a single encoding rather than towards disparate encodings, we should not make this easy for naive users to do to themselves.
  * We're operating on the file contents as text -- splitting on newlines, doing search and replace, etc.  Some text operations are reasonably safe to perform on bytes in an unknown encoding but others are not.  The non-ascii compatible encodings mentioned above are particularly problematic but even among ascii-supersets, there are issues.  For instance, you can't count text characters and some regexes don't function the same.

**Comment by mowgli** [comment]
Some of your points are absolutelly valid. However, the only what I would read out of them is to handle files as byte stream. That way, all regex would work correctly.

About forcing all /text/ files to be UTF-8. That is great for the files of ansible and in fact, yaml specifies UTF-8 here. But you cannot pretend one charset of a file on the target system as you simply don't know it. There are many charsets out there and all are valid in one or the other case. Again, the only solution would be a byte stream until the role author can be pretty sure to force one charset.

About patching binary files, I do not want to patch the binary but what I have in mind are files that are partly binary and partly simple text. Think, for example, of a shellpack, some of that shell scripts that have the tar concatenated at the end. Also here, the solution is byte strings.

And I think, it is the safest way to read it as byte strings as that way there cannot be invalid content.

**Comment by mowgli** [comment]
Just a side note:

For my case above, Parts of /etc/passwd are under full control of the user (chfn). So the user can simply break my task by putting some weird chars inside his user informations.

The only solution would be to go back to (untested):
```yaml
- name: Keep all passwd-entries in /etc/password sane
  command: sed -i -e 's/^([^:]+):[^:]*:/\1:x:/g' /etc/passwd
```

… With all the downsides; especially changing /etc/passwd every time ansible run. Actually, I think, `replace` is exactly to prevent the use of sed in a command module.

**Comment by abadger** [comment]
We talked about this at today's IRC meeting and felt that this needed to have the various approaches laid out and then evaluated by more people.  The plan is for me to write a proposal and then we'll discuss this at the contributor summit in September (perhaps more places as well).  This will definitely not be changed in time for 2.4.  I'll post a link to the proposal here when I get it written.  (I'm thinking of writing down several alternatives to what I fel is the best path so that people can evaluate the variants fairly).

**Comment by mowgli** [comment]
I made a workaround for this mess.
```yaml
- name: Keep all passwd-entries in /etc/password sane (ansible < 2.3)
  replace:
     dest: /etc/passwd
     regexp: '^([^:]+):[^:]*:'
     replace: '\1:x:'
  when: ansible_version.major != 2 or ansible_version.minor < 3

- name: Keep all passwd-entries in /etc/password sane (ansible = 2.3)
  shell: "grep -Pvq '^[^:]+:x:' /etc/passwd && sed -i -e 's/^\\([^:]\\+\\):[^:]*:/\\1:x:/g' /etc/passwd && echo 'Changed' || echo 'Unchanged'"
  when: ansible_version.major == 2 and ansible_version.minor == 3
  register: shell_result
  changed_when: "shell_result.stdout == 'Changed'"

- name: Keep all passwd-entries in /etc/password sane (ansible > 2.3)
  replace:
     dest: /etc/passwd
     regexp: '^([^:]+):[^:]*:'
     replace: '\1:x:'
     encoding: iso-8859-1
  when: ansible_version.major == 2 and ansible_version.minor > 3
```

Unfortunatelly that has some disadvantages:
- In version 2.4 and above that assumes iso-8859-1 as it is a full 8bit charset. Other such charsets would work too but in fact the file is mixed charset. So at least it works.
- In version 2.3 the nasty workaround with shell ans sed is needed.
- In version 2.3 a failure in sed will not be notified. That is the worsed point.

Alltogether I think, the additional parameter `encoding` would be helpful however, the standard behavior should be encoding agnostic.
