### ISSUE TITLE
`fetch` does not report unreachable on authentication error when gather_facts=false

### ISSUE THREAD

**Issue by darkk** [ansible/ansible#27816]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`fetch` module

##### ANSIBLE VERSION

```
ansible 2.3.2.0 (detached HEAD c7052b42c7) last updated 2017/08/06 09:06:45 (GMT +300)
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
ansible is running from Ubuntu 16.04 and manages various debian jessie hosts.

##### SUMMARY

`fetch` can't properly handle authentication failure for some reason.
Seems to be duplicate of closed #16877

##### STEPS TO REPRODUCE
NB: `gather_facts: false` matters.

```yaml
- hosts: all
  gather_facts: false
  tasks:
    - name: mktemp
      command: mktemp -td boot_id.XXXXXXXX
      register: tmp
      run_once: true
      delegate_to: localhost
    - name: fetch kernel/random/boot_id
      fetch: src=/proc/sys/kernel/random/boot_id dest={{tmp.stdout}}/{{inventory_hostname}} flat=yes fail_on_missing=yes
```

##### EXPECTED RESULTS

I expected the host to report some sort of failure as with `ping` module:
```
$ ansible -m ping ooni-fdroid-build.infra.ooni.io
ooni-fdroid-build.infra.ooni.io | UNREACHABLE! => {
    "changed": false, 
    "msg": "SSH Error: data could not be sent to remote host \"ooni-fdroid-build.infra.ooni.io\". Make sure this host can be reached over ssh", 
    "unreachable": true
}
```

##### ACTUAL RESULTS

```
TASK [fetch kernel/random/boot_id] *************************************************************************************************************************************************************************
task path: /home/darkk/oo/sysadmin/ansible/check-inventory.yml:16
Using module file /home/darkk/contrib-src/ansible/lib/ansible/modules/files/stat.py
<ooni-fdroid-build.infra.ooni.io> ESTABLISH SSH CONNECTION FOR USER: None
<ooni-fdroid-build.infra.ooni.io> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/darkk/.ansible/cp/7735c2afbf ooni-fdroid-build.infra.ooni.io '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
ok: [ooni-fdroid-build.infra.ooni.io] => {
    "changed": false, 
    "file": "/proc/sys/kernel/random/boot_id", 
    "msg": "unable to calculate the checksum of the remote file"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/fetch.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/fetch.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/fetch.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/fetch.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gparent** [comment]
This still affects 2.9.

Simpler example playbook:

```
- hosts: all
  gather_facts: no
  tasks:
  - fetch:
      src: /etc/hostname
      dest: /tmp/backup
```
