### ISSUE TITLE
junos_command: unable to get partial config

### ISSUE THREAD

**Issue by Kokozzi** [ansible/ansible#27815]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
junos_command

##### ANSIBLE VERSION

```
ansible 2.4.0
```

##### CONFIGURATION

```
“N/A”
```

##### OS / ENVIRONMENT

```
“N/A”
```

##### SUMMARY

junos_command module can't get partial config from juniper, for example result of `show configuration interfaces ae2` will be full device config (instead of interface part)
I think, that problem is in [this file](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/junos/junos_command.py), , func "rpc" (201 line). Fetch_config var becomes true for all "show configuration"-type commands and as a result - running get_configuration func (240 line). This func runs exactly "show configuration".

##### STEPS TO REPRODUCE

```yaml
---
- name: Configure Spec
  hosts: jun1
  connection: local
  gather_facts: false

  tasks:

    - name: Check if interface already exist
      junos_command:
        commands: show configuration interfaces ae2 unit {{ vlan }}
        provider: "{{ cli }}"
      register: existing_check
```

##### EXPECTED RESULTS

Config part, that includes only ae2.{{vlan}}

##### ACTUAL RESULTS

Full device config (too long for displaying in issue)

```

```

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn @privateip
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ganeshrn** [comment]
@Kokozzi The implementation is not intended to support fetching partial configuration.
 Since junos does not have a one to one mapping between `show configuration` cli command and `get-configuration` rpc with filters as in case of other junos operational mode commands

**Comment by Kokozzi** [comment]
@ganeshrn But that was possible in ansible 2.3, I've succesfully tested it in stable version before updating to develop.

**Comment by privateip** [comment]
@ganeshrn @Kokozzi #28025  should fix this issue

**Comment by calfonso** [comment]
@Kokozzi please re-test and let us know if it's still an issue.

needs_info

**Comment by Kokozzi** [comment]
@calfonso @privateip  Sorry for long waiting. Nothing changed after update to last develop version.

```    
     - name: Show syslog conf
      junos_command:
        commands: show configuration system syslog
        provider: "{{ cli }}"
      register: existing_syslog
```

Still gets full config instead of syslog-part.
