### ISSUE TITLE
Jira module documentation

### ISSUE THREAD

**Issue by Jaurman** [ansible/ansible#27820]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

Jira Module
##### ANSIBLE VERSION

```
ansible 2.3.1.0
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

In Jira module documentation, **Create link** part has example how to link two issues:
**linktype: Relate**
It should be:
**linktype: Relates**
Same typo in jira.py file
##### STEPS TO REPRODUCE

```
---
- hosts: all
  tasks:
  - name: Create link from TEST-60 to TEST-61
    jira:
      uri: '{{ server }}'
      username: '{{ user }}'
      password: '{{ pass }}'
      operation: link
      linktype: "Relate"
      inwardissue: "TEST-60"
      outwardissue: "TEST-61"
```

##### EXPECTED RESULTS

Linked correctly
##### ACTUAL RESULTS

"msg": "HTTP Error 404: "

```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "assignee": null, 
            "comment": null, 
            "description": null, 
            "fields": {}, 
            "inwardissue": "TEST-60", 
            "issue": null, 
            "issuetype": null, 
            "linktype": "Relate", 
            "operation": "link", 
            "outwardissue": "TEST-61", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "project": null, 
            "status": null, 
            "summary": null, 
            "timeout": 10.0, 
            "uri": "http://localhost:8080", 
            "username": "user"
        }
    }, 
    "msg": "HTTP Error 404: "
}

```
