### ISSUE TITLE
[parted] Partition is not create if label was absent

### ISSUE THREAD

**Issue by sophie-h** [ansible/ansible#27841]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
parted
##### ANSIBLE VERSION
git `devel`

##### OS / ENVIRONMENT
Debian stretch

##### SUMMARY
Partition is not create if no label is present.

##### STEPS TO REPRODUCE

```
  - parted:
     device: /dev/loop0
     state: present
     number: 1
```

If /dev/loop0 is an empty device:

- First run: Label is create but no partition
- Second run: Partition is created
- Third run: Nothing is changed

The partition should be created on the first run.
