### ISSUE TITLE
vmware_guest_find by UUID or name does not find VMs in resource pools and vmware_guest_facts by name does not either

### ISSUE THREAD

**Issue by jmcginn13** [ansible/ansible#27860]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
vmware_guest_facts
vmware_guest_find

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel cde1b1b255) last updated 2017/08/07 09:38:49 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jmcginn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jmcginn/workspaces/ansible/ansible/lib/ansible
  executable location = /home/jmcginn/workspaces/ansible/ansible/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
Default
##### OS / ENVIRONMENT
Guest OS: Centos 7
VSphere 5.5 with VCenter 6.0

##### SUMMARY
Would like to find facts about VMs that are part of a resource group

##### STEPS TO REPRODUCE
1. Create a resource group
2. Create a VM in that resource group
3. Execute one of the following tasks as part of a playbook with appropriate variables for your environment
```yaml
    - name: Find VM
      vmware_guest_find:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        uuid: "{{ vm_uid }}"
        # or
        # name: {{ vm_name }}"
      register: found

    - name: Get VM facts
      vmware_guest_facts:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        folder: "{{ vm_folder }} "
        name: "{{ vm_name}} "
      register: my_vm
```
Notice the error message returned indicating the VM could not be found

##### EXPECTED RESULTS
Be nice to include a resource_pool name as an optional argument to the above tasks. If the resource pool name is included it only look in that resource pool for the matching VM instead of just searching globally.

For example in vmware_guest_find you could have something like the following if a resource pool name was set:
        pool = get_obj(self.content, [vim.ResourcePool], resourcePool)
        for vm in pool.vm:
            .... check if name/uid match

**Comment by ansibot** [comment]
cc @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by abhinav-chittora** [comment]
Hi All,

I have the same issue. 
`Ansible version: 2.3.1.0`

`vcenter version: 6.0.0`

`ESXi version: 6.0 Update 3`

My code is same, I am trying to get vmware_guest_facts but each time I run the code, it says the virtual machine doesn't exists. However, in inventory view, I am able to find that.

**Comment by Akasurde** [comment]
@abhinav-chittora Could you please try with latest devel branch of Ansible (2.4devel), lot of things are fixed related to vmware_* in this version?

@jmcginn13 Could you please provide output of [govc find /](https://github.com/vmware/govmomi/tree/master/govc)?

**Comment by jmcginn13** [comment]
I don't have govmomi installed, should I have had it installed? I'll install and try

**Comment by jmcginn13** [comment]
I got govmomi installed and ran the govc find / command, but it is listing every hostname of every VM in our data center, Security won't let me provide the full output. However I grepped for my test VMs since I'll be deleting them soon and you can see this output:
govc find / | grep mcginn
/Railinc Cary/host/CHQ DEV TST/Resources/mcginn
/Railinc Cary/vm/mcginn
/Railinc Cary/host/CHQ DEV TST/Resources/mcginn/mcginn-kafka-app/mcginn-zoo-03
/Railinc Cary/host/CHQ DEV TST/Resources/mcginn/mcginn-kafka-app/mcginn-zoo-02
/Railinc Cary/host/CHQ DEV TST/Resources/mcginn/mcginn-kafka-app/mcginn-vm-01
/Railinc Cary/host/CHQ DEV TST/Resources/mcginn/mcginn-kafka-app/mcginn-zoo-01
/Railinc Cary/vm/mcginn/mcginn-centos
/Railinc Cary/host/CHQ DEV TST/Resources/mcginn/mcginn-kafka-app

The output includes my folder (/vm/mcginn), my resource group (Resources/mcginn/mcginn-kafka-app), the 4 VMs in that resource group, and one VM template not in the resource group (just in the folder)

**Comment by abhinav-chittora** [comment]
Hi @Akasurde, 

I installed govmomi and findout the vm's absolute path is /Datacenter/AM-Datacenter/vm/DevOps/<VM name>. But when I run the ansible playbook, it prefix /vm,  hence the VM is not found by the vmware_guest_facts or vmware_guest_snapshot module. 

Probably, we need to make this prefix optional. Any suggestions.

**Comment by abhinav-chittora** [comment]
I checked out version 2.4 and it was working fine there after specifying the vm folder as /Datacenter/AM-Datacenter/vm/DevOps/.

**Comment by abhinav-chittora** [comment]
Hi @Akasurde ,

However, I encounter another problem now. 

Now vmware_guest is not able to create virtual machine in /Datacenter/AM-Datacenter/vm/DevOps. When I run the playbook to create a virtual machine using template it says `"No folder matched the path:  /Datacenter/AM-Datacenter/vm/DevOps"`. 

However the same path is used to create vmware_guest_snapshot module and it is able to create snapshot of virtual machine available in that folder.

**Comment by jmcginn13** [comment]
@abhinav-chittora try using the folder /vm/DevOps when creating the VM. That is working for me when I create the VM. 

I also tried the vmware_guest_facts using the full folders as defined above and it seems to be working for the vm template that is not in the resource group (mcginn-centos). 

If I try the following:
```
tasks:
    - name: Get VM facts
      vmware_guest_facts:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        #uuid: "420f8c31-5918-28f2-5931-4a2baae0d230"
        folder: "/Railinc Cary/host/CHQ DEV TST/Resources/mcginn/mcginn-kafka-app"
        name: "mcginn-zoo-03"
      register: my_vm
```

I get the following error:
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_JfVAHx/ansible_module_vmware_guest_facts.py", line 164, in <module>
    main()
  File "/tmp/ansible_JfVAHx/ansible_module_vmware_guest_facts.py", line 146, in main
    uuid=module.params['uuid'])
  File "/tmp/ansible_JfVAHx/ansible_module_vmware_guest_facts.py", line 119, in getvm
    vm = find_vm_by_id(self.content, vm_id=name, vm_id_type="inventory_path", folder=folder, match_first=match_first)
  File "/tmp/ansible_JfVAHx/ansible_modlib.zip/ansible/module_utils/vmware.py", line 200, in find_vm_by_id
AttributeError: 'vim.VirtualApp' object has no attribute 'childEntity'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_JfVAHx/ansible_module_vmware_guest_facts.py\", line 164, in <module>\n    main()\n  File \"/tmp/ansible_JfVAHx/ansible_module_vmware_guest_facts.py\", line 146, in main\n    uuid=module.params['uuid'])\n  File \"/tmp/ansible_JfVAHx/ansible_module_vmware_guest_facts.py\", line 119, in getvm\n    vm = find_vm_by_id(self.content, vm_id=name, vm_id_type=\"inventory_path\", folder=folder, match_first=match_first)\n  File \"/tmp/ansible_JfVAHx/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 200, in find_vm_by_id\nAttributeError: 'vim.VirtualApp' object has no attribute 'childEntity'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```

**Comment by abhinav-chittora** [comment]
Hi @jmcginn13,

I tried /vm/DevOps as well but still getting the same error that the folder is not available.

**Comment by Akasurde** [comment]
@abhinav-chittora Can you please open a new issue for vmware_guest with details about your Playbook and infrastructure details ?

**Comment by brokenjacobs** [comment]
I have this same issue with vmware_guest_find and vmware_guest. All of our vm's are in resource pools and neither module works with uuid instead of name. 

Furthermore, vmware_guest_find shouldn't need a datacenter set to find a vm by uuid should it? uuid's are unique per vcenter.

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kkolk** [comment]
So folder seems to be a required item even though the documentation indicates it's not when searching by name.

So, lets say I'm searching for a server called 'webd01' in a Datacenter called 'Wayland' and in my inventory the inventory_hostname is webd01.wayland.com.   Assume that other variables are properly populated.   The complete folder path from govc is /Wayland/vm/Website/Development.

If I comment out the folder value as shown below:

 ````
 - name: VMWare | Search VSphere for VMWare Guest
    vmware_guest_facts:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ domain_admin_user }}"
      password: "{{ domain_admin_pass }}"
      validate_certs: false
      name: "{{ inventory_hostname | regex_search('([^.]+)') }}"
      datacenter: Hastings
    #  folder: /Wayland/vm/Website/Development
    delegate_to: localhost
    register: vmguest_facts
````

I get this result:

    "msg": "Unable to gather facts for non-existing VM webd01"

Return the folder value, quickly finds the host.

UUID works without the folder.

Is this the intended behavior?
