### ISSUE TITLE
How to use Ansible to execute multiple services on a single host by playbook simultaneously

### ISSUE THREAD

**Issue by mesopodamia** [ansible/ansible#27882]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.3.1.0
```

##### INVENTORY

demo.yml

```
{
  "app.source.1": {
    "hosts": [
      "192.168.1.100"
    ],
    vars: {
    ansible_expr: "app.source.1"
    }
  },
  "app.source.2": {
    "hosts": [
      "192.168.1.100"
    ],
    "vars": {
    ansible_expr: "app.source.2"
    }
  },
}
```

##### STEPS TO REPRODUCE

when I set the host variable is  app.source.* To match the host
execute the instruction only a orders can be completed
and can not be completed several times
```
ansible-playbook demo.yml -e "host=app.source.*"
```

##### PLAYBOOK

```yaml
- hosts: "{{host}}"
  gather_facts: no
  tasks:
    - file:
         path: /tmp/"{{ ansible_expr }}"
         state: touch
```

##### EXPECTED RESULTS
i want touch two files  on the host(192.168.1.100)
```
/tmp/app.source.1
/tmp/app.source.2
``` 

##### ACTUAL RESULTS
only one file on the hosts(192.168.1.100)
```
/tmp/app.source.2
```
