### ISSUE TITLE
cant change nic's network

### ISSUE THREAD

**Issue by yosefy** [ansible/ansible#27900]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
2.3.0
```

##### CONFIGURATION
  - name: test
    vmware_guest:
      validate_certs: no
      datacenter: aaa
      folder: /aaa
      cluster: aaa
      hostname: test.com
      username: user
      password: pass
      name: ny-name
      networks:
      - name: DPortGroup -vlan110-NFS
      - vlan: 110

##### OS / ENVIRONMENT

running from ubuntu 16

##### SUMMARY
expected to "move" nic to new network
but instead it adds another nic created in new network and the old one moved

##### STEPS TO REPRODUCE

```
  - name: Rename a VM (requires the VM's uuid)


```

##### EXPECTED RESULTS
nic moves to new network

##### ACTUAL RESULTS

```
second nic is created and got expected results
also first nic moved to expected network ( both on distributed switch )
```

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dav1x** [comment]
Can you list the full plays that you are trying to run @yosefy ? I'm a little uncertain how to try and recreate this.

**Comment by dagwieers** [comment]
From the example it seems you are expecting 2 NICs to be created. I think you have the syntax wrong, it should be only one entry:
```yaml
- name: test
  vmware_guest:
  validate_certs: no
  datacenter: aaa
  folder: /aaa
  cluster: aaa
  hostname: test.com
  username: user
  password: pass
  name: ny-name
  networks:
  - name: DPortGroup -vlan110-NFS
    vlan: 110
```
The `vlan` key belongs to the `name: DPortGroup -vlan110-NFS` entry, right ?
