### ISSUE TITLE
(P1) nxos_snapshot fails for {{ nxapi  }}

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27908]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_snapshot

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: Nexus9000 C9396PX running 7.0(3)I7(1)

##### SUMMARY
When we run a playbook on nxos_snapshot with {{ nxapi }} to create a snapshot, it errors out.

##### STEPS TO REPRODUCE
playbook:

```
- name: create snapshot
  nxos_snapshot:
    action: create
    snapshot_name: test_snapshot
    description: Ansible
    provider: "{{ nxapi }}"

- name: delete snapshot
  nxos_snapshot:
    action: delete
    snapshot_name: test_snapshot
    provider: "{{ nxapi }}"
```

##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com          : ok=21   changed=1    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
fatal: [n9k.example.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Zosdmt/ansible_module_nxos_snapshot.py\", line 476, in <module>\n    main()\n  File \"/tmp/ansible_Zosdmt/ansible_module_nxos_snapshot.py\", line 455, in main\n    final_snapshots = invoke('get_existing', module)\n  File \"/tmp/ansible_Zosdmt/ansible_module_nxos_snapshot.py\", line 356, in invoke\n    return func(*args, **kwargs)\n  File \"/tmp/ansible_Zosdmt/ansible_module_nxos_snapshot.py\", line 236, in get_existing\n    split_body = body.splitlines()\nAttributeError: 'dict' object has no attribute 'splitlines'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'dict' object has no attribute 'splitlines'
```
