### ISSUE TITLE
ec2_vpc_nat_gateway output is inconsistent between runs

### ISSUE THREAD

**Issue by inhumantsar** [ansible/ansible#27916]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_vpc_nat_gateway

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /workspace/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### SUMMARY
During the intial creation of a NAT Gateway, keys in the dict returned by the module use names which align with the AWS API output rather than the Pythonic keys shown in the documentation.

##### STEPS TO REPRODUCE

```yaml
  - name: Create NAT gateway for private subnets
    ec2_vpc_nat_gateway:
      subnet_id: "{{ vpc_public_subnets[0] }}"
      region: "{{ vpc_region }}"
      if_exist_do_not_create: true
    register: natgw
  - debug: var=natgw

  - pause: seconds=30

  - name: Create NAT gateway for private subnets
    ec2_vpc_nat_gateway:
      subnet_id: "{{ vpc_public_subnets[0] }}"
      region: "{{ vpc_region }}"
      if_exist_do_not_create: true
    register: natgw
  - debug: var=natgw
```

##### EXPECTED RESULTS

```
TASK [inhumantsar.ec2-vpc : Create NAT gateway for private subnets] ************
ok: [localhost]

TASK [inhumantsar.ec2-vpc : debug] *********************************************
ok: [localhost] => {
    "natgw": {
        ...
        "nat_gateway_addresses": [
            {
                "allocation_id": "eipalloc-xxxxxxx", 
                "network_interface_id": "eni-xxxxxx", 
                "private_ip": "10.0.1.175", 
                "public_ip": "xx.xx.xx.xx"
            }
        ], 
        "nat_gateway_id": "nat-xxxxxxxxxx", 
        "state": "available", 
        "subnet_id": "subnet-xxxxxxx", 
        "success": true, 
        "vpc_id": "vpc-xxxxxxxx"
    }
}

TASK [inhumantsar.ec2-vpc : Create NAT gateway for private subnets] ************
ok: [localhost]

TASK [inhumantsar.ec2-vpc : debug] *********************************************
ok: [localhost] => {
    "natgw": {
        ...
        "nat_gateway_addresses": [
            {
                "allocation_id": "eipalloc-xxxxxxx", 
                "network_interface_id": "eni-xxxxxx", 
                "private_ip": "10.0.1.175", 
                "public_ip": "xx.xx.xx.xx"
            }
        ], 
        "nat_gateway_id": "nat-xxxxxxxxxx", 
        "state": "available", 
        "subnet_id": "subnet-xxxxxxx", 
        "success": true, 
        "vpc_id": "vpc-xxxxxxxx"
    }
}
```
##### ACTUAL RESULTS

```
TASK [inhumantsar.ec2-vpc : Create NAT gateway for private subnets] ************
ok: [localhost]

TASK [inhumantsar.ec2-vpc : debug] *********************************************
ok: [localhost] => {
    "natgw": {
        "CreateTime": "2017-08-08T18:11:53+00:00", 
        "NatGatewayAddresses": [
            {
                "AllocationId": "eipalloc-xxxxxxxx"
            }
        ], 
        "NatGatewayId": "nat-xxxxxxxx", 
        "State": "pending", 
        "SubnetId": "subnet-xxxxxxx", 
        "VpcId": "vpc-xxxxxxxx", 
        "changed": true, 
        "msg": "", 
        "success": true
    }
}

TASK [inhumantsar.ec2-vpc : Create NAT gateway for private subnets] ************
ok: [localhost]

TASK [inhumantsar.ec2-vpc : debug] *********************************************
ok: [localhost] => {
    "natgw": {
        ...
        "nat_gateway_addresses": [
            {
                "allocation_id": "eipalloc-xxxxxxx", 
                "network_interface_id": "eni-xxxxxx", 
                "private_ip": "10.0.1.175", 
                "public_ip": "xx.xx.xx.xx"
            }
        ], 
        "nat_gateway_id": "nat-xxxxxxxxxx", 
        "state": "available", 
        "subnet_id": "subnet-xxxxxxx", 
        "success": true, 
        "vpc_id": "vpc-xxxxxxxx"
    }
}

```
