### ISSUE TITLE
(P2) nxos_vxlan_vtep_vni errors out when trying to test remove idempotence

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#27926]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vxlan_vtep_vni

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: NX-OSv9K running 7.0(3)I2(5)

##### SUMMARY
Removing vxlan_vtep_vni configuration is NOT idempotent. The config has no associate-vrf.

##### STEPS TO REPRODUCE

```
- block:
  - name: "Enable feature nv overlay"
    nxos_config: 
      commands:
        - feature nv overlay
      provider: "{{ cli }}"
      match: none

  - name: configure vxlan_vtep
    nxos_vxlan_vtep:
      interface: nve1
      host_reachability: True
      provider: "{{ cli }}"

  - name: configure vxlan_vtep_vni assoc-vrf
    nxos_vxlan_vtep_vni: &conf1
      interface: nve1
      vni: 6000
      assoc_vrf: True
      provider: "{{ cli }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Conf 1 Idempotence"
    nxos_vxlan_vtep_vni: *conf1
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: remove vxlan_vtep_vni
    nxos_vxlan_vtep_vni:
      interface: nve1
      vni: 6000
      assoc_vrf: True
      state: absent
      provider: "{{ cli }}"

  - name: configure vxlan_vtep_vni mcast
    nxos_vxlan_vtep_vni: &conf2
      interface: nve1
      vni: 8000
      multicast_group: 224.1.1.1
      provider: "{{ cli }}"
    register: result

  - assert: *true

  - name: "Conf 2 Idempotence"
    nxos_vxlan_vtep_vni: *conf2
    register: result

  - assert: *false

  - name: "remove config"
    nxos_vxlan_vtep_vni: &remove
      interface: nve1
      vni: 8000
      state: absent
      provider: "{{ cli }}"

  - name: configure vxlan_vtep_vni peer-list
    nxos_vxlan_vtep_vni: &conf3
      interface: nve1
      vni: 8000
      peer_list: 
        - 1.1.1.1
        - 2.2.2.2
        - 3.3.3.3
        - 4.4.4.4
      ingress_replication: static
      provider: "{{ cli }}"
    register: result

  - assert: *true

  - name: "Conf 3 Idempotence"
    nxos_vxlan_vtep_vni: *conf3
    register: result

  - assert: *false

  - name: remove vxlan_vtep_vni
    nxos_vxlan_vtep_vni: *remove
    register: result

  - assert: *true

  - name: "remove Idempotence"
    nxos_vxlan_vtep_vni: *remove
    register: result

  - assert: *false

  always:
  - name: remove vxlan_vtep
    nxos_vxlan_vtep:
      interface: nve1
      shutdown: true
      state: absent
      provider: "{{ cli }}"
    ignore_errors: yes

  - name: "Disable feature nv overlay"
    nxos_feature: 
      feature: nve
      state: disabled
      provider: "{{ cli }}"
    ignore_errors: yes

```
##### EXPECTED RESULTS
```
PLAY RECAP ********************************************************************************************************************************************
n9k.example.com      : ok=22   changed=5    unreachable=0    failed=0
```

##### ACTUAL RESULTS
```
TASK [nxos_vxlan_vtep_vni : remove Idempotence] *******************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'assoc_vrf'                                 
fatal: [n9k.example.com]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NcYgj1/ansible_module_nxos_vxlan_vtep_vni.py\", line 347, in <module>\n    main()\n  File \"/tmp/ansible_NcYgj1/ansible_module_nxos_vxlan_vtep_vni.py\", line 334, in main\n    state_absent(module, existing, proposed, candidate)\n  File \"/tmp/ansible_NcYgj1/ansible_module_nxos_vxlan_vtep_vni.py\", line 255, in state_absent\n    if existing['assoc_vrf']:\nKeyError: 'assoc_vrf'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```
