### ISSUE TITLE
`lxd_container` cannot handle `state: absent` for ephemeral containers properly

### ISSUE THREAD

**Issue by zerkms** [ansible/ansible#27923]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lxd_container

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### SUMMARY

If you create the ephemeral container, then make it `state: absent` it throws an error

````
fatal: [...]: FAILED! => {"actions": ["stop"], "changed": true, "failed": true, "msg": "not found"}
````
It happens because container removal is implemented as

```python
    def _destroyed(self):
        if self.old_state != 'absent':
            if self.old_state == 'frozen':
                self._unfreeze_container()
            if self.old_state != 'stopped':
                self._stop_container()
            self._delete_container()
```

So as you may see - it first stops the container, then tries to delete. But the ephemeral container is removed on stop.

##### STEPS TO REPRODUCE

1. Create an ephemeral container using `lxd_container` module

2. Try to destroy it with `state: absent`

```yaml
- name: create a container
  lxd_container:
    name: i-am-ephemeral
    state: started
    ephemeral: yes
    source:
        type: image
        mode: pull
        server: https://cloud-images.ubuntu.com/releases
        protocol: simplestreams
        alias: "xenial/amd64"
    profiles: ["default"]
    wait_for_ipv4_addresses: true

- name: destroy a container
  lxd_container:
    name: i-am-ephemeral
    state: absent
    ephemeral: yes
    source:
        type: image
        mode: pull
        server: https://cloud-images.ubuntu.com/releases
        protocol: simplestreams
        alias: "xenial/amd64"
    profiles: ["default"]
    wait_for_ipv4_addresses: true

```

##### EXPECTED RESULTS

The container should be removed, both tasks should succeed.

##### ACTUAL RESULTS

The container is removed, but the second task fails.

```
fatal: [...]: FAILED! => {"actions": ["stop"], "changed": true, "failed": true, "msg": "not found"}
```
