### ISSUE TITLE
vmware_guest fails to modify CPU and RAM of a guest VM

### ISSUE THREAD

**Issue by sayantandas** [ansible/ansible#27939]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
 ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### SUMMARY

vmware_guest does not change the CPU and RAM of a running VM. The output shows result as changed
##### STEPS TO REPRODUCE

I ran the playbook below on a Ubuntu 14.04 VM. Playbook completed successfully but change was not reflected on the Vcenter UI. I am using the latest vmware_guest yml file from development branch of ansible . I have put that in the /library folder to make use of it.

```
- name: Stop virtual machine
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "false"
    folder: "{{ vm_folder }}"
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vm_name }}"
    state: "poweredoff"
  delegate_to: "localhost"
  register: stop_vm

- name: reconfigure CPU and RAM of VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vm_name }}"
    state: "poweredon"
    validate_certs: "false"
    folder: "{{ vm_folder }}"
    hardware:
      memory_mb: "{{ memory }}"
      num_cpus: "{{ cpu }}"
      scsi: "lsilogic"
  delegate_to: "localhost"


```

##### EXPECTED RESULTS

Expected the CPU and RAM to change. 
##### ACTUAL RESULTS

The CPU and RAM remains unchanged

```
TASK [reconfigure-vm : Stop virtual machine]  ***********************************
changed: [localhost -> localhost] => {
    "changed": true,
    "failed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "Cluster1",
            "customization": {},
            "customvalues": [],
            "datacenter": "",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/DC1/vm/testvms/",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "vcenter.test.local.com",
            "is_template": false,
            "linked_clone": false,
            "name": "ubuntu14-test6",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredoff",
            "template": null,
            "username": "ansible@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}

TASK [reconfigure-vm : reconfigure CPU and RAM of VM] *********************************
changed: [localhost -> localhost] => {
    "changed": true,
    "failed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "Cluster1",
            "customization": {},
            "customvalues": [],
            "datacenter": "",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/DC1/vm/testvms/",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": "4096",
                "num_cpus": "2",
                "scsi": "lsilogic"
            },
            "hostname": "vcenter.test.local.com",
            "is_template": false,
            "linked_clone": false,
            "name": "ubuntu14-test6",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": null,
            "username": "ansible@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}

```
