### ISSUE TITLE
Couldn't read packet: Connection reset by peer - Ansible cannot connect on Ubuntu 10.04

### ISSUE THREAD

**Issue by maethor** [ansible/ansible#27938]
This seems to be a duplicate of #25116. But this issue has been closed automatically, and actually I have no problem with 14.04. So I will try to reformulate it better.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- ssh

##### ANSIBLE VERSION

Ansible 2.3.1.0 and 2.3.0.0

```
ansible 2.3.1.0
  config file = /home/gsubiron/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

```
[defaults]

gathering=explicit
fact_caching=redis
fact_caching_timeout=86400

[privilege_escalation]

become=True
become_user=root
become_method=sudo
become_ask_pass=True
```

##### OS / ENVIRONMENT

Ansible is running on Debian 8 (Jessie). The host managed is an old Ubuntu 10.04.

##### SUMMARY

Since 2.3, Ansible cannot connect on my Ubuntu 10.04 (LTS) host.

#25116 seems to say it also concerns Ubuntu 14.04 LTS, but It works well for me on 14.04 servers. It must depends on SSH configuration.

##### STEPS TO REPRODUCE

```
ansible myhost.sysnove.net -m ping -vvvv
```

##### EXPECTED RESULTS

It is working fine with Ansible 2.2.0.0

```yaml
myhost.sysnove.net | SUCCESS => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "data": null
        }, 
        "module_name": "ping"
    }, 
    "ping": "pong"
}
```

##### ACTUAL RESULTS

But not with Ansible 2.3.0.0 and 2.3.1.0

```yaml
myhost.sysnove.net | UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_6.7p1 Debian-5+deb8u3, OpenSSL 1.0.1t  3 May 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 10613\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Control master terminated unexpectedly\r\nCouldn't read packet: Connection reset by peer\r\n", 
    "unreachable": true
}
```
