### ISSUE TITLE
ios_config overwrites unchanged config section on every run where running_config whitespace is inconsistent

### ISSUE THREAD

**Issue by dbpqdb** [ansible/ansible#27933]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
No customisation

##### OS / ENVIRONMENT
Ubuntu Xenial
Controlling Cisco ISR router running IOS 15.5(3)M4

##### SUMMARY
Every time the role is run, a section of config that should match the lines supplied is overwritten.
It is caused by inconsistent whitespace in the Cisco configuration output which is being incorrectly interpreted by the `ansible/module_utils/netcfg.py` file, line 236 `curlevel = int(line_indent / self._indent)` which expects the indentation level to be consistent between levels.

The running_config of the Cisco router causing the issue appears as follows; notice the white-space of the `username rancid` section is 2 characters and for the `key-hash` within that it's 3 characters, whereas normal Cisco behavior would expect that those should be 1 and 2 whitespace levels respectively.

```
ip ssh pubkey-chain
  username rancid
   key-hash ssh-rsa F75[REDACTED]679 rancid
```

##### STEPS TO REPRODUCE

```yaml
- name: Configure RANCID SSH keys for access
  ios_config:
    provider: "{{ cli }}"
    parents:
      - ip ssh pubkey-chain
      - username rancid
    lines:
      - key-hash ssh-rsa F75[REDACTED]679 rancid
    before:
      - ip ssh pubkey-chain
      - no username rancid
    match: exact
    replace: block
```

##### EXPECTED RESULTS
After the initial run, no changes should occur if no changes have been made to that section of config.

##### ACTUAL RESULTS
Section is removed and re-added on every playbook run.

```
TASK [router-management : Configure RANCID SSH keys for access] ******************************************************************************************************************
task path: /home/cloud/ansible/roles/router-management/tasks/main.yml:97
<192.168.1.33> using connection plugin network_cli
<192.168.1.33> socket_path: /home/cloud/.ansible/pc/67faa6dae0
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/ios/ios_config.py
<192.168.1.33> ESTABLISH LOCAL CONNECTION FOR USER: cloud
<192.168.1.33> EXEC /bin/sh -c 'echo ~ && sleep 0'
<192.168.1.33> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/cloud/.ansible/tmp/ansible-tmp-1502248150.14-67365105764290 `" && echo ansible-tmp-1502248150.14-67365105764290="` echo /home/cloud/.ansible/tmp/ansible-tmp-1502248150.14-67365105764290 `" ) && sleep 0'
<192.168.1.33> PUT /tmp/tmpV13zmw TO /home/cloud/.ansible/tmp/ansible-tmp-1502248150.14-67365105764290/ios_config.py
<192.168.1.33> EXEC /bin/sh -c 'chmod u+x /home/cloud/.ansible/tmp/ansible-tmp-1502248150.14-67365105764290/ /home/cloud/.ansible/tmp/ansible-tmp-1502248150.14-67365105764290/ios_config.py && sleep 0'
<192.168.1.33> EXEC /bin/sh -c '/usr/bin/python /home/cloud/.ansible/tmp/ansible-tmp-1502248150.14-67365105764290/ios_config.py; rm -rf "/home/cloud/.ansible/tmp/ansible-tmp-1502248150.14-67365105764290/" > /dev/null 2>&1 && sleep 0'
changed: [192.168.1.33] => {
    "banners": {},
    "changed": true,
    "commands": [
        "ip ssh pubkey-chain",
        "no username rancid",
        "ip ssh pubkey-chain",
        "username rancid",
        "key-hash ssh-rsa F75[REDACTED]679 rancid",
        "username rancid",
        "key-hash ssh-rsa F75[REDACTED]679 rancid"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": [
                "ip ssh pubkey-chain",
                "no username rancid"
            ],
            "config": null,
            "defaults": false,
            "force": false,
            "host": null,
            "lines": [
                "key-hash ssh-rsa F75[REDACTED]679 rancid"
            ],
            "match": "exact",
            "multiline_delimiter": "@",
            "parents": [
                "ip ssh pubkey-chain",
                "username rancid"
            ],
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": null,
                "host": "192.168.1.33",
                "password": null,
                "port": null,
                "ssh_keyfile": null,
                "timeout": 60,
                "transport": "cli",
                "username": "cloud"
            },
            "replace": "block",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "updates": [
        "ip ssh pubkey-chain",
        "no username rancid",
        "ip ssh pubkey-chain",
        "username rancid",
        "key-hash ssh-rsa F75[REDACTED]679 rancid",
        "username rancid",
        "key-hash ssh-rsa F75[REDACTED]679 rancid"
    ]
}
META: ran handlers
META: ran handlers
```

**Comment by ansibot** [comment]
cc @privateip @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn @gundalow @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kedarX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
@dbpqdb Would you please be able to retest this on Ansible 2.4
We made some indentation fixes in 2.4, I believe they were for ios.

needs_info

**Comment by ohmer** [comment]
Hi,

Same problem here with version 2.4.1.0 and python version = 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0]

task definition :
```
- name: add SSH keys
  ios_config:
    provider: "{{ cli }}"
    match: exact
    replace: line
    before: "username {{ item.username }} privilege 15"
    lines: "key-hash {{ item.pubkeytype }} {{ item.pubkeydata | b64decode | hash('md5') | upper }}"
    parents:
      - ip ssh pubkey-chain
      - "username {{ item.username }}"
  with_items: "{{ ssh_keys }}"
  notify: "save configuration"
  tags:
    - sshkeys
```
inventory/group_vars/dev.yml
```
---
ssh_keys:
  - username: test
    pubkeytype: ssh-rsa
    pubkeydata:
      AAAAB3NzaC1yc2EAAAADAQABAAABAQDZfSxwDzZOurPuQ8BiCXVHbzhjB5XJszJ6mCtb389q6
      WnB/0xpx1XNtdQrSyH8S8W91GkoDuejXW7a33UDm6jPH+Nrp+hpfRHOIrwHnVIAXM0/IJQWYF
      dOfM2HjAZMQ5dRD6RPNGTi/3tUq059w6E4D7VWzpivpD8lZCdLsMdv3BFoVQfSwNHG0y978kr
      227/DS822HPKMipDLCRzLDDT9ak2J4DlwFYLgnp8iIXVJakLilxGa1L2lTIId36E229lTst6k
      8krQi8xNOvS39YkzinVqtRnnIx+Nz3cbj2hM+eQjnAp2IC1UWI0PfNIGLvD2R7lV1dnXQBcfH
      QcnZ03t
```
ansible-playbook -vv output :
```
TASK [hub : add SSH keys] *******************************************************************************************************************************************************************************************************************
changed: [<hidden>] => (item={u'username': u'test', u'pubkeytype': u'ssh-rsa', u'pubkeydata': u'AAAAB3NzaC1yc2EAAAADAQABAAABAQDZfSxwDzZOurPuQ8BiCXVHbzhjB5XJszJ6mCtb389q6 WnB/0xpx1XNtdQrSyH8S8W91GkoDuejXW7a33UDm6jPH+Nrp+hpfRHOIrwHnVIAXM0/IJQWYF dOfM2HjAZMQ5dRD6RPNGTi/3tUq059w6E4D7VWzpivpD8lZCdLsMdv3BFoVQfSwNHG0y978kr 227/DS822HPKMipDLCRzLDDT9ak2J4DlwFYLgnp8iIXVJakLilxGa1L2lTIId36E229lTst6k 8krQi8xNOvS39YkzinVqtRnnIx+Nz3cbj2hM+eQjnAp2IC1UWI0PfNIGLvD2R7lV1dnXQBcfH QcnZ03t'}) => {"banners": {}, "changed": true, "commands": ["username test privilege 15", "ip ssh pubkey-chain", "username test", "key-hash ssh-rsa 8D9BAFD40C625F77FEE3EF03D006D284"], "failed": false, "item": {"pubkeydata": "AAAAB3NzaC1yc2EAAAADAQABAAABAQDZfSxwDzZOurPuQ8BiCXVHbzhjB5XJszJ6mCtb389q6 WnB/0xpx1XNtdQrSyH8S8W91GkoDuejXW7a33UDm6jPH+Nrp+hpfRHOIrwHnVIAXM0/IJQWYF dOfM2HjAZMQ5dRD6RPNGTi/3tUq059w6E4D7VWzpivpD8lZCdLsMdv3BFoVQfSwNHG0y978kr 227/DS822HPKMipDLCRzLDDT9ak2J4DlwFYLgnp8iIXVJakLilxGa1L2lTIId36E229lTst6k 8krQi8xNOvS39YkzinVqtRnnIx+Nz3cbj2hM+eQjnAp2IC1UWI0PfNIGLvD2R7lV1dnXQBcfH QcnZ03t", "pubkeytype": "ssh-rsa", "username": "test"}, "updates": ["username test privilege 15", "ip ssh pubkey-chain", "username test", "key-hash ssh-rsa 8D9BAFD40C625F77FEE3EF03D006D284"]}
```

running-configuration before play includes:
```
username test privilege 15
ip ssh pubkey-chain
  username test
   key-hash ssh-rsa 8D9BAFD40C625F77FEE3EF03D006D284
```

I am very interested in a solution / help because I have been struggling on this for hours now !

Thanks !

**Comment by ansibot** [comment]
@dbpqdb This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dbpqdb** [comment]
I've tested on 2.4.2.0 and confirmed the same issue exists.

@ohmer The workaround we're using in the meantime is as follows:

```
- name: Get existing Cisco IOS SSH key if any for rancid user account
 ios_command:
   provider: "{{ cli }}"
   commands:
     - "show run | s ip ssh pubkey-chain"
   retries: 1
 register: ios_pubkeychain_output
 when: "'ciscoios' in group_names"

- name: Set SSH key of rancid user account
 set_fact:
   ios_pubkeychain_rancid: "{{ ios_pubkeychain_output.stdout[0]|default(0) | regex_replace('^[\\s\\S]+username rancid\\W[\\s\\S]+(key-hash ssh-rsa ' + hostvars[inventory_hostname]['ioskeyhashrancid'] + ' rancid[\\w\\d\\.\\@]*)(?:$|[\\s\\S]+$)', '\\1') }}"
 when: "'ciscoios' in group_names"

- name: Configure Cisco IOS SSH key for RANCID access
 ios_config:
   provider: "{{ cli }}"
   parents:
     - ip ssh pubkey-chain
   lines:
     - username rancid
     - key-hash ssh-rsa {{ hostvars[inventory_hostname]['ioskeyhashrancid'] }} rancid
   before:
     - ip ssh pubkey-chain
     - no username rancid
   match: strict
   replace: block
 notify:
   - Cisco IOS save config
 when: "('ciscoios' in group_names) and \
       (ios_pubkeychain_rancid != 'key-hash ssh-rsa ' + hostvars[inventory_hostname]['ioskeyhashrancid'] + ' rancid')"
```
