### ISSUE TITLE
shell/command - password in journal with no_log: true

### ISSUE THREAD

**Issue by VAdamec** [ansible/ansible#27941]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
shell or command

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/library/']
  python version = 2.7.5 (default, Sep  5 2016, 02:30:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]
```

##### CONFIGURATION
no change of logging
```
# logging is off by default unless this path is defined
# if so defined, consider logrotate
#log_path = /var/log/ansible.log
# if the *module* considers an argument to be no_log at the time that the
# stdout from ansible-playbook (or you have manually specified no_log in your
# want, for example, a notification or logging callback to also apply to
# prevents logging of task data, off by default
#no_log = False
# prevents logging of tasks, but only on the targets, data is still logged on the master/controller
#no_target_syslog = False
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.3 (Maipo)

##### SUMMARY
Commands from shell module is fully logged on journal on host servers (_raw_params)

##### STEPS TO REPRODUCE

```yaml
  - name: Get user
    shell: 'grep user /etc/vaulted/mysql.cnf | cut -f 3 -d " "'
    no_log: true
    register: login

  - name: Getpassword
    shell: 'grep password /etc/vaulted/mysql.cnf | cut -f 3 -d " "'
    no_log: true
    register: password

  - name: ADD backup timestamp to table
    shell: mysql -u "{{ login.stdout }}" -p"{{ password.stdout }}" changelog -e 'INSERT INTO versions (id,state) VALUES(NULL,"{{ state }}";'
    no_log: true
```
or

```yaml
...
  - name: ADD backup timestamp to table
    shell: mysql -u "{{ login.stdout }}" -p"{{ password.stdout }}" changelog -e 'INSERT INTO versions (id,state) VALUES(NULL,"{{ state }}";'
    no_log: true
```

##### EXPECTED RESULTS
No command logged at all (or at least with obfuscated password)

##### ACTUAL RESULTS

```
Aug 08 23:35:33 test-server python[19854]: ansible-command Invoked with warn=True executable=None _uses_shell=True _raw_params=mysql -u "root" -p"SUPERSECRET" changelog -e 'INSERT INTO test (id,state) VALUES(NULL,"test","Running",NULL);' removes=None creates=None chdir=None
```
