### ISSUE TITLE
xml module: Reading attribute value into ansible variable is undocumented

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#27951]
_From @ssbarnea on April 15, 2016 11:54_

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION
v2.4

##### SUMMARY
The documentation should include a code sample that loads an attribute value into an ansible variable. I may make sense to provide a simple example for reading the `charset` attribute from insite HTML page. `html>headers>meta>charset`. Maybe even specifying what happens if it is missing.

_Copied from original issue: cmprescott/ansible-xml#59_

**Comment by dagwieers** [comment]
_From @cmprescott on May 20, 2016 14:24_

That should definitely be included.

**Comment by dagwieers** [comment]
_From @wheelq on June 15, 2016 10:25_

is it possible to read the value? what is the syntax?

**Comment by dagwieers** [comment]
_From @kenthua on June 15, 2016 18:38_

Looks like it's "xmlstring" [from the source](https://github.com/cmprescott/ansible-xml/blob/master/library/xml#L31)

**Comment by dagwieers** [comment]
_From @hdimitriou on October 14, 2016 12:4_

The xmlstring is inaccurate:

```
    - name: xml test
      xml:
        file: "{{ some_file }}"
        xpath: //some_xpath
        content: text
      register: xml_hits
```

**Comment by dagwieers** [comment]
_From @glzavert on March 15, 2017 15:21_

So it has been months since this issue was opened and identified as a bug.  What is the status of an example on how to load an attribute or element value into an ansible variable.  Examples with and with out namespaces are relevant as many users simply need to access the values and do not need to manipulate the XML.  

I have spent many many days trying to do this and the closest I have gotten returns the following
```
TASK [test : Print patch] ******************************************************
ok: [capiis.ibm.com] => {
    "get_element_attribute.matches[0]['PatchManifest']['patchName']": "patch_JR55554_ISD_all_11500-1"
}
```
or
```
TASK [test : Print hist] *******************************************************
ok: [capiis.ibm.com] => {
    "get_applied_patches.matches[21]['{http://www.ibm.com/LocalInstallRegistry}HistoricalEvent']['installerId']": "patch_JR55554_ISD_all_11500-1"
}
```

I have been unable to get the values "patch_JR55554_ISD_all_11500-1" into variables so that I can compare a patch manifest to a list of applied patches in order to determine if a patch has been applied.  This is to prevent what is apparent in the attached Version.xml file where a patch has been repeatedly applied.  I like many, don't want to manipulate the xml files, I simply need the values in the attributes.

Here are my files:
[PatchManifest.xml.txt](https://github.com/cmprescott/ansible-xml/files/844918/PatchManifest.xml.txt)
[Version.xml.txt](https://github.com/cmprescott/ansible-xml/files/844919/Version.xml.txt)

Here is my main.yml
```yaml
- name: Get patch name attributes
  xml:
    file: "/opt/IBM/install/tmp/PatchManifest.xml"
    xpath: /PatchManifest
    content: 'attribute'
  register: get_element_attribute

- name: print get_element_attribute 
  debug: var=get_element_attribute
      
- name: pring patchName attributes
  debug: var=get_element_attribute.matches[0]['PatchManifest']['patchName']
  
- name: Count applied patches
  xml:
    file: "/opt/IBM/InformationServer/Version.xml"
    xpath: /iis:History/iis:HistoricalEvent
    namespaces:
      iis: http://www.ibm.com/LocalInstallRegistry
    count: true
  register: applied_patches

- name: Print count of applied patches
  debug: var=applied_patches.count

- name: Get applied patches
  xml:
    file: "/opt/IBM/InformationServer/Version.xml"
    xpath: //iis:HistoricalEvent
    namespaces:
      iis: http://www.ibm.com/LocalInstallRegistry
    content: 'attribute'
  register: get_applied_patches

- name: Print applied patch for first patch
  debug: var=get_elements.matches[0]['{http://www.ibm.com/LocalInstallRegistry}HistoricalEvent']['installerId']

- name: iterate over applied patches applied patchs
  include: inner.yml
  vars:
    patch: get_element_attribute.matches[0]['PatchManifest']['patchName']
    hist: get_applied_patches.matches[{{item}}]['{http://www.ibm.com/LocalInstallRegistry}HistoricalEvent']['installerId']
  with_sequence: start=0 end={{ get_applied_patches.count|int - 1}}
```

Here is my inner.yml
```yaml
- name: Print patch
  debug: var="{{ patch }}"

- name: Print hist
  debug: var="{{ hist }}"
```

I have no idea why this has to be so difficult but any prompt resolution to this bug or direction on how to get the values into variables for testing would be appreciated.
