### ISSUE TITLE
Unable to open shell - Junos_Command

### ISSUE THREAD

**Issue by zgould** [ansible/ansible#27958]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Junos_Command

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### SUMMARY

I can utilize all JunOS modules, and they work just fine, except for the Junos_Command module. It continues to throw a socket connection error.

##### STEPS TO REPRODUCE

```
- name: Install JunOS
  hosts: junos-sales-switch
  serial: 1
  roles:
  - Juniper.junos
  connection: local
  gather_facts: no

  vars:
   wait_time: 3600
   pkg_dir: /tftpboot/juniper/
   OS_version: 15.1R6.7
   OS_package: jinstall-ex-2200-15.1R6.7-domestic-signed.tgz
   OS_version2: 12.3R12.4
   OS_package2: jinstall-ex-2200-12.3R12.4-domestic-signed.tgz
   log_dir: /var/log/ansible
   netconf:
    host: "{{ inventory_hostname }}"
    username: databank
    port: 830

  tasks:

  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

#  - name: Get Facts
#    junos_get_facts:
#     host={{ inventory_hostname }}
#     user=databank

  - name: Test Command
    junos_command:
     commands:
      - set interfaces ge-0/0/1 description {{ BGP_GROUP }}
     provider: "{{ netconf }}"
```

##### ACTUAL RESULTS

```
<192.168.244.27> using connection plugin netconf
 31173 1502285195.90825: Loading Connection 'persistent' from /usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/persistent.py
 31173 1502285195.90872: Loading ShellModule 'csh' from /usr/local/lib/python2.7/dist-packages/ansible/plugins/shell/csh.py (found_in_cache=True, class_only=False)
 31173 1502285195.90885: Loading ShellModule 'fish' from /usr/local/lib/python2.7/dist-packages/ansible/plugins/shell/fish.py (found_in_cache=True, class_only=False)
 31173 1502285195.90898: Loading ShellModule 'powershell' from /usr/local/lib/python2.7/dist-packages/ansible/plugins/shell/powershell.py (found_in_cache=True, class_only=False)
 31173 1502285195.90917: Loading ShellModule 'sh' from /usr/local/lib/python2.7/dist-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 31173 1502285195.90933: Loading ShellModule 'sh' from /usr/local/lib/python2.7/dist-packages/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 31173 1502285195.91042: Loading Connection 'ssh' from /usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py (found_in_cache=False, class_only=True)
<192.168.244.27> socket_path: /home/zgould/.ansible/pc/ca70ef5ed2
open_session() returned 255  31174 1502285196.69655: Loading Connection 'ssh' from /usr/local/lib/python2.7/dist-packages/ansible/plugins/connection/ssh.py (found_in_cache=False, class_only=True)
 failed to connect to control socket
 31173 1502285226.75726: handler run complete
 31173 1502285226.75749: attempt loop complete, returning result
 31173 1502285226.75765: _execute() done
 31173 1502285226.75779: dumping result to json
 31173 1502285226.75800: done dumping result, returning
 31173 1502285226.75821: done running TaskExecutor() for 192.168.244.27/TASK: Test Command [005056a5-5683-ff24-f1ef-00000000000f]
 31173 1502285226.75848: sending task result for task 005056a5-5683-ff24-f1ef-00000000000f
 31173 1502285226.75926: done sending task result for task 005056a5-5683-ff24-f1ef-00000000000f
 31173 1502285226.76004: WORKER PROCESS EXITING
 31144 1502285226.76132: marking 192.168.244.27 as failed
 31144 1502285226.76157: marking host 192.168.244.27 failed, current state: HOST STATE: block=2, task=2, rescue=0, always=0, run_state=ITERATING_TASKS, fail_state=FAILED_NONE, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
 31144 1502285226.76174: ^ failed state is now: HOST STATE: block=2, task=2, rescue=0, always=0, run_state=ITERATING_COMPLETE, fail_state=FAILED_TASKS, pending_setup=False, tasks child state? (None), rescue child state? (None), always child state? (None), did rescue? False, did start at task? False
 31144 1502285226.76193: getting the next task for host 192.168.244.27
 31144 1502285226.76210: host 192.168.244.27 is done iterating, returning
fatal: [192.168.244.27]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell",
    "rc": 255
}
 31144 1502285226.76279: no more pending results, returning what we have
 31144 1502285226.76290: results queue empty
 31144 1502285226.76299: checking for any_errors_fatal
 31144 1502285226.76310: done checking for any_errors_fatal
 31144 1502285226.76319: checking for max_fail_percentage
 31144 1502285226.76327: done checking for max_fail_percentage
 31144 1502285226.76336: checking to see if all hosts have failed and the running result is not ok
 31144 1502285226.76347: done checking to see if all hosts have failed
 31144 1502285226.76362: getting the remaining hosts for this loop
 31144 1502285226.76385: done getting the remaining hosts for this loop
 31144 1502285226.76404: building list of next tasks for hosts
 31144 1502285226.76418: getting the next task for host 192.168.244.27
 31144 1502285226.76431: host 192.168.244.27 is done iterating, returning
 31144 1502285226.76446: done building task lists
 31144 1502285226.76459: counting tasks in each state of execution
 31144 1502285226.76477: done counting tasks in each state of execution:

```
