### ISSUE TITLE
java_cert module: One of cert_path, cert_url required to remove a key

### ISSUE THREAD

**Issue by dflock** [ansible/ansible#27982]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
java_cert

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/duncan/dev/tools/cluster_provisioning/ansible/ansible.cfg
  configured module search path = [u'/usr/local/lib/python2.7/dist-packages/ara/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The `java_cert` module currently requires one of `cert_path` or `cert_url` in order to remove a key from a keystore. I can understand this for _adding_ a key - but I can remove keys by alias using the `keystore` command line, so this should also work using the `java_cert` module. I should not need to point to the key file on disk/net in order to remove it from a local keystore - I should just need to supply the alias.

##### STEPS TO REPRODUCE

```yaml
- name: Remove existing certificate
  java_cert:
    state: absent
    cert_alias: '{{ keystore.alias }}'
    keystore_path: /etc/ssl/certs/java/cacerts
    keystore_pass: changeit
```

##### EXPECTED RESULTS
Expected it to remove the cert with the given alias, as the equivalent `keytool` command would do:

```yaml
- name: Remove existing certificate
  command: >
    keytool
    -delete
    -alias {{ keystore.alias }} 
    -keystore /etc/ssl/certs/java/cacerts
    -storepass changeit
```

##### ACTUAL RESULTS
```
TASK [dev_test : Remove existing certificate] **************************************************************************************************************************************************************************************************************************
Wednesday 09 August 2017  14:25:53 -0700 (0:00:01.929)       0:00:10.739 ****** 
fatal: [dev.example.com]: FAILED! => {"changed": false, "failed": true, "msg": "one of the following is required: cert_path,cert_url"}
```

**Comment by dflock** [comment]
Yeah, looks like you always have to pass in one of `cert_pass` or `cert_url` regardless of the `state`: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/java_cert.py#L223

```python
    module = AnsibleModule(
        argument_spec=argument_spec,
        required_one_of=[['cert_path', 'cert_url']],
        required_together=[['keystore_path', 'keystore_pass']],
        mutually_exclusive=[
            ['cert_url', 'cert_path']
        ],
        supports_check_mode=True,
    )
```

It looks like these parameters are actually _ignored_ when deleting a cert, so you can pass in any value (or no value), as long as the parameter exists:

```yaml
- name: Remove existing certificate
  java_cert:
    state: absent
    cert_alias: '{{ keystore.alias }}'
    cert_url: 'dummy value - see https://github.com/ansible/ansible/issues/27982'
    keystore_path: /etc/ssl/certs/java/cacerts
    keystore_pass: changeit
```
