### ISSUE TITLE
git mistakenly requires --depth for cloning with --branch

### ISSUE THREAD

**Issue by minusdavid** [ansible/ansible#27991]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
git module

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Host: Ubuntu 14.04
Remote: Ubuntu 14.04

##### SUMMARY
The --branch option for git clone is only used in newer versions of Ansible if --depth is also supplied. This is a (seemingly unreasonable) departure from older versions of Ansible (like 1.8.2). 

##### STEPS TO REPRODUCE
Run the following playbook with a new version of Ansible (e.g. 2.3.2 or devel). If you want to see the comparison, you can also run it with an older version of Ansible (e.g. 1.8.2). 

```yaml
---
- hosts: localhost
  tasks:
    - name: "Checkout archivematica-storage-service code"
      git:
        repo: "https://github.com/artefactual/archivematica-storage-service.git"
        dest: "/opt/archivematica/archivematica-storage-service"
        version: "qa/0.x"
        force: "yes"
        accept_hostkey: "yes"
```

##### EXPECTED RESULTS
```
dcook@linux:/opt/archivematica/archivematica-storage-service> git branch -vv
* qa/0.x 610e4eb [origin/qa/0.x] move db dependencies out of base requirements
```

##### ACTUAL RESULTS
As you can see, it's cloned using the HEAD of the upstream repository (ie stable/0.10.x) and then switched to the desired version of qa/0.x. The above expected results are what we see in Ansible 1.8.2 and I think what accords with user expectations. 

```
dcook@linux2:/opt/archivematica/archivematica-storage-service> git branch -vv
* qa/0.x        610e4eb [origin/qa/0.x] move db dependencies out of base requirements
  stable/0.10.x 1afb22a [origin/stable/0.10.x] Re-ingest: don't delete pointer file, refs #113
56
```
