### ISSUE TITLE
Documentation example in win_file module is misleading

### ISSUE THREAD

**Issue by rnestler** [ansible/ansible#28005]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
win_file

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A
##### OS / ENVIRONMENT
N/A

##### SUMMARY
The documentation of [win_file](https://docs.ansible.com/ansible/latest/win_file_module.html#id3) shows that to create a file you have to do the following:
```
- name: Create a file
  win_file:
    path: C:\Temp\foo.conf
    state: file
```
This does not work and it is clearly stated above in the Options section that it won't work:
> If file, the file will NOT be created if it does not exist, see the copy or template module if you want that behavior.

##### Proposed Fix
The example should be removed or changed to use `state: touch`
