### ISSUE TITLE
Apt update all packages generates an 'impossibly' long list of conflicts

### ISSUE THREAD

**Issue by jmvbxx** [ansible/ansible#28011]
- Bug Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION
```
ansible 2.3.1.0
```

##### CONFIGURATION
Nothing special

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS

##### SUMMARY
I'm trying to run a task to update all packages on the server. Here's a snippet of the output:
```
(0, '\r\n{"cache_updated": false, "stdout": "Reading package lists...\\nBuilding dependency tree...\\nReading state information...\\nSome packages could not be installed. This may mean that you have\\nrequested an impossible situation or if you are using the unstable\\ndistribution that some required packages have not yet been created\\nor been moved out of Incoming.\\nThe following information may help to resolve the situation:\\n\\nThe following packages have unmet dependencies:\\n 389-ds-base : Conflicts: slapd but 2.4.42+dfsg-2ubuntu3.2 is to be installed\\n ace : Conflicts: libace-perl but 1.92-4 is to be installed\\n adb : Breaks: android-tools-adb\\n aide : Conflicts: aide-dynamic but 0.16~a2.git20130520-3 is to be installed\\n        Conflicts: aide-xen but 0.16~a2.git20130520-3 is to be installed\\n aide-dynamic : Conflicts: aide but 0.16~a2.git20130520-3 is to be installed\\n                Conflicts: aide-xen but 0.16~a2.git20130520-3 is to be installed\\n aide-xen : Cx-proxy-sqlite3 but 1:2.4.7+dfsg-2ubuntu2.1 is to be installed", 
```
The entire output is an enormous list of the same.

##### STEPS TO REPRODUCE
```
- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
```

##### EXPECTED RESULTS
Expected same result as `apt upgrade -y`

##### ACTUAL RESULTS
Snippet pasted above

Thank you in advance!

**Comment by ansibot** [comment]
cc @mgwilliams
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jmvbxx** [comment]
Any update on this?

**Comment by nkane2898** [comment]
I'm having the same issue.
[ubuntu_ansible.txt](https://github.com/ansible/ansible/files/1275991/ubuntu_ansible.txt)

**Comment by jmvbxx** [comment]
To confirm there truly is a problem with the task and not with my roles .. I created a brand new instance using today's ubuntu 16.04 lts ami. I manually ran `apt update; apt install -y python-minimal`.

The only task I applied was:
```
- name: Perform apt upgrade
  apt:
    name: "*"
    state: latest
```
Here's the output!
[apt_update_all.txt](https://github.com/ansible/ansible/files/1278470/apt_update_all.txt)

**Comment by mkaimal** [comment]
looks like its the python module for apt , is configured incorrect . 

i wanted to do apt-get update -y , but had the conflict on all the packages .

this is the result : 
```
fatal: [10.227.158.21]: FAILED! => {
    "cache_update_time": 1505986925,
    "cache_updated": false,
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoremove": null,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "install_recommends": null,
            "name": "*",
            "only_upgrade": false,
            "package": [
                "*"
            ],
            "purge": false,
            "state": "latest",
            "update_cache": null,
            "upgrade": null
        }
    },
```
for the task 
```
---
- hosts: all
  gather_facts: True
  become: yes


  tasks: 
    - name: Upgrade when ubuntu 
      apt: 
        name: "*"
        state: latest  
      when: ansible_distribution == "Ubuntu"


```
But it worked when i had  this ... 

```
---
- hosts: all
  gather_facts: True
  become: yes


  tasks: 
    - name: Upgrade when ubuntu 
      apt: 
        upgrade: dist 
      when: ansible_distribution == "Ubuntu"
```
**as apt-get upgrade -y  , and not as apt-get dist-upgrade ( as mentioned in the doc)** 

```
changed: [10.227.158.21] => {
    "changed": true,
    "diff": {},
    "invocation": {
        "module_args": {
            "allow_unauthenticated": false,
            "autoremove": null,
            "cache_valid_time": 0,
            "deb": null,
            "default_release": null,
            "dpkg_options": "force-confdef,force-confold",
            "force": false,
            "install_recommends": null,
            "only_upgrade": false,
            "package": null,
            "purge": false,
            "state": "present",
            "update_cache": null,
            "upgrade": "dist"
        }
    },```
