### ISSUE TITLE
Ansible environment.PATH fails to resolve ~

### ISSUE THREAD

**Issue by JamesMcGuigan** [ansible/ansible#28014]
Ansible version 2.3.1.0 (running on cygwin against RHEL)

The environment.PATH variable fails to resolve ~/ as the user home directory.

```
# playbook.yml
- hosts: server
  environment:
    PATH: "~/bin"
  tasks:
    npm:
      name: yarn
```
failed: [server] { msg: "unable to find npm in paths: ~/bin

However this does work if I remove the ~/ prefix and set the path as simply being a relative directory with the assumption that everything is running with cwd as ~/

With npm installed as symlink in userspace as: ~/bin/npm (no root access on corporate servers)

```
# playbook.yml
- hosts: server
  environment:
    PATH: "bin"
  tasks:
    npm:
      name: yarn
```

the workaround if setting path visit host_vars is
```
- host: server
  environment:
    PATH: "{{ host_environment | regexp_replace('~/', '') }}"
```

This is a little item, but does mean I require two different strings for my bash and ansible paths.
