### ISSUE TITLE
Iterating over nested dictionary throws 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'value'

### ISSUE THREAD

**Issue by mschuchard** [ansible/ansible#28010]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`with_items`

##### ANSIBLE VERSION
2.3.1 (from licensed Tower 3.1.4)

##### CONFIGURATION
none

##### OS / ENVIRONMENT
RHEL 7.4

##### SUMMARY
`with_items` is not iterating over a nested dictionary

##### STEPS TO REPRODUCE
This also throws the same error if the dictionary is specified directly in the `with_items` key and/or the nested keys are changed to `reg` and `lin` to avoid name conflicts.

```yaml
# task
- name: do a thing
  lineinfile:
    path: /path/to/file
    regexp: "{{ item.value.regex }}"
    line: "{{ item.value.line }}"
  with_items: "{{ configs }}"
  when: ansible_distribution_major_version == "7" or
        ansible_distribution_major_version == "6"

# default var
configs:
  keyone:
    regex: 'a regex'
    line: 'a line'
  keytwo:
    regex: 'another regex'
    line: 'another line'
```

##### EXPECTED RESULTS
`with_items` successfully iterates over a dictionary

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'value'
```
