### ISSUE TITLE
pamd broke my pam files and I lost access

### ISSUE THREAD

**Issue by ITD27M01** [ansible/ansible#28026]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pamd module
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)
##### SUMMARY

pamd broke my pam files and I lost access

Source password-auth file:
```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth        required      pam_env.so
auth        required      pam_faildelay.so delay=2000000
auth        [default=1 ignore=ignore success=ok] pam_succeed_if.so uid >= 1000 quiet
auth        [default=1 ignore=ignore success=ok] pam_localuser.so
auth        sufficient    pam_unix.so nullok try_first_pass
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        sufficient    pam_sss.so forward_pass
auth        required      pam_deny.so

account     required      pam_unix.so
account     sufficient    pam_localuser.so
account     sufficient    pam_succeed_if.so uid < 1000 quiet
account     [default=bad success=ok user_unknown=ignore] pam_sss.so
account     required      pam_permit.so

password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok
password    sufficient    pam_sss.so use_authtok


password    required      pam_deny.so

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so
session     optional      pam_sss.so
```

There is my task:
```yaml
  - name: Configure Odjob pam.d
    pamd:
      name: password-auth
      type: session
      control: optional
      module_path: pam_sss.so
      new_type: session
      new_control: optional
      new_module_path: pam_oddjob_mkhomedir.so
      module_arguments: 'umask=0077'
      state: before
```
And there is final file after task to be run:
```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth        required      pam_env.so
auth        required      pam_faildelay.so delay=2000000
auth        [default=1 ignore=ignore success=ok] pam_succeed_if.so uid >= 1000 quiet
auth        [default=1 ignore=ignore success=ok] pam_localuser.so
auth        sufficient    pam_unix.so nullok try_first_pass
auth        requisite     pam_succeed_if.so uid >= 1000 quiet_success
auth        sufficient    pam_sss.so forward_pass
auth        required      pam_deny.so

account     required      pam_unix.so
account     sufficient    pam_localuser.so
account     sufficient    pam_succeed_if.so uid < 1000 quiet

## THERE IS BROKED STRING
account     [default=bad success=ok user_unknown=ignore] success=ok user_unknown=ignore] pam_sss.so

account     required      pam_permit.so

password    requisite     pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
password    sufficient    pam_unix.so sha512 shadow nullok try_first_pass use_authtok
password    sufficient    pam_sss.so use_authtok


password    required      pam_deny.so

session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so
session     optional      pam_sss.so
session         optional        pam_oddjob_mkhomedir.so umask=0077
```
##### STEPS TO REPRODUCE

1. Check /etc/pam.d/password-auth
2. Enable sssd usage:
```
authconfig --enablesssd --enablesssdauth --enablekrb5kdcdns --update
```
3. Run task and check /etc/pam.d/password-auth again 

```yaml
  - name: Configure Odjob pam.d
    pamd:
      name: password-auth
      type: session
      control: optional
      module_path: pam_sss.so
      new_type: session
      new_control: optional
      new_module_path: pam_oddjob_mkhomedir.so
      module_arguments: 'umask=0077'
      state: before
```

##### EXPECTED RESULTS

pamd module should affect only configured string but not any other sttrings in cfg
##### ACTUAL RESULTS

pamd broke my pam files and I lost access

```

```

**Comment by ansibot** [comment]
cc @kevensen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kevensen** [comment]
Similar to #25522

**Comment by kevensen** [comment]
@ITD27M01 This likely addressed by a recent pull https://github.com/ansible/ansible/pull/25817.  Can you please check to see if it solves this issue?

**Comment by ITD27M01** [comment]
@kevensen 
Hi, thank you for reply. I'll try to check with library/pamd.py

**Comment by ITD27M01** [comment]
@kevensen 

I try to use https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/pamd.py

By task:
```
  - name: Configure Odjob pam.d
    pamd:
      name: password-auth
      type: session
      control: optional
      module_path: pam_sss.so
      new_type: session
      new_control: optional
      new_module_path: pam_oddjob_mkhomedir.so
      module_arguments: 'umask=0077'
      state: before
```

And get the following file:

```
#%PAM-1.0
# This file is auto-generated.
# User changes will be destroyed the next time authconfig is run.
auth            required        pam_env.so 
auth            required        pam_faildelay.so delay=2000000
auth            [default=1 ignore=ignore success=ok]    ignore=ignore success=ok] pam_succeed_if.so uid >= 1000 quiet
auth            [default=1 ignore=ignore success=ok]    ignore=ignore success=ok] pam_localuser.so
auth            sufficient      pam_unix.so nullok try_first_pass
auth            requisite       pam_succeed_if.so uid >= 1000 quiet_success
auth            sufficient      pam_sss.so forward_pass
auth            required        pam_deny.so 

account         required        pam_unix.so 
account         sufficient      pam_localuser.so 
account         sufficient      pam_succeed_if.so uid < 1000 quiet
account         [default=bad success=ok user_unknown=ignore]    success=ok user_unknown=ignore] pam_sss.so
account         required        pam_permit.so 

password        requisite       pam_pwquality.so try_first_pass local_users_only retry=3 authtok_type=
password        sufficient      pam_unix.so sha512 shadow nullok try_first_pass use_authtok
password        sufficient      pam_sss.so use_authtok
password        required        pam_deny.so 

session         optional        pam_keyinit.so revoke
session         required        pam_limits.so 

-session        optional        pam_systemd.so 

session         [success=1 default=ignore]      pam_succeed_if.so service in crond quiet use_uid
session         required        pam_unix.so 
session         optional        pam_oddjob_mkhomedir.so umask=0077
session         optional        pam_sss.so 
```
