### ISSUE TITLE
win_scheduled_task: Weekly with multiple days doesn't work

### ISSUE THREAD

**Issue by nwalke** [ansible/ansible#28039]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_scheduled_task

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
Mac configuring Windows Server 2012 R2

##### SUMMARY
When trying to create a weekly task, I am unable to get it to recognize multiple days.

##### STEPS TO REPRODUCE
```yaml
    - name: Add task to run a thing
      win_scheduled_task:
        executable: cmd
        state: present
        days_of_week: 'Sunday,Wednesday'
        frequency: weekly
        time: 2am
        name: Run a thing
```

##### EXPECTED RESULTS
I expected to see a scheduled task that was scheduled for both Sunday and Wednesday, weekly.

##### ACTUAL RESULTS
It creates the scheduled task, but only for Wednesday.  I was able to verify that it's actually pasting in "Sunday,Wednesday" to the Powershell cmdlet, so I have no idea why this isn't working.

I'm able to do this in Powershell and it seems to work just fine.  I don't know why it would be different via Ansible.
```
PS C:\Users\nwalke> New-ScheduledTaskTrigger -Weekly -At 2:00AM -DaysOfWeek Sunday,Wednesday

Id         Frequency       Time                   DaysOfWeek              Enabled
--         ---------       ----                   ----------              -------
0          Weekly          8/10/2017 2:00:00 AM   {Sunday, Wednesday}     True

```

**Comment by ansibot** [comment]
cc @petemounce
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
@nwalke are you able to try out the PR https://github.com/ansible/ansible/pull/28995. This is a complete rewrite of the module to handle more features that were missing and fix up some issues with the current version. The options have changed but for your case you want to have something like

```
- win_scheduled_task:
    name: Run a thing
    state: present
    actions:
    - path: cmd
    triggers:
    - type: weekly
      days_of_week: sunday,wednesday
      start_boundary: '2017-09-19T02:00:00'
```

I did a test myself and it creates the task to run on those specific days as shown by the screenshot below

![image](https://user-images.githubusercontent.com/8462645/30575975-dddc905a-9d47-11e7-904f-ddfddd4fdf78.png)


If you are able to test it out, please leave a comment on the PR saying if it did or did not work for you.
