### ISSUE TITLE
Invalid YAML group_vars file not showing errors on failed import

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#28038]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
hostvars

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /Users/Yves/Infrastructure/ansible-provisioning/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
There are a few hosts I'm able to connect to, to execute tasks successfully - but even in the same play the hostvars for this host are empty.

##### STEPS TO REPRODUCE

```yaml
TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
ok: [host1.example.com]

TASK [return motd to registered var] ******************************************************************************************************************************************************************************************************************************************
changed: [host1.example.com]

TASK [debug test - motd] ******************************************************************************************************************************************************************************************************************************************************
ok: [host1.example.com] => {
    "motd": {
        "changed": true, 
        "cmd": [
            "cat", 
            "/etc/motd"
        ], 
        "delta": "0:00:00.002175", 
        "end": "2017-08-10 23:55:52.192378", 
        "rc": 0, 
        "start": "2017-08-10 23:55:52.190203", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "", 
        "stdout_lines": []
    }
}

TASK [debug test - hostvars] **************************************************************************************************************************************************************************************************************************************************
ok: [host1.example.com] => {
    "hostvars['host1.example.com']": "VARIABLE IS NOT DEFINED!"
}
```

##### EXPECTED RESULTS

```yaml
TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
ok: [workinghost.example.com]

TASK [return motd to registered var] ******************************************************************************************************************************************************************************************************************************************
changed: [workinghost.example.com]

TASK [debug test - motd] ******************************************************************************************************************************************************************************************************************************************************
ok: [workinghost.example.com] => {
    "motd": {
        "changed": true, 
        "cmd": [
            "cat", 
            "/etc/motd"
        ], 
        "delta": "0:00:00.003442", 
        "end": "2017-08-10 23:59:45.907492", 
        "rc": 0, 
        "start": "2017-08-10 23:59:45.904050", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "", 
        "stdout_lines": []
    }
}

TASK [debug test - hostvars] **************************************************************************************************************************************************************************************************************************************************
ok: [workinghost.example.com] => {
    "hostvars['workinghost.example.com']": {
        "ansible_all_ipv4_addresses": [
            "10.255.0.36"
        ], 
        "ansible_all_ipv6_addresses": [
            "fe80::a25:6ccb:ef7:eacd"
        ], 
       (…)
    }
}
```

##### ACTUAL RESULTS
```yaml
ok: [host1.example.com] => {
    "hostvars['host1.example.com']": "VARIABLE IS NOT DEFINED!"
}
```
Even as host facts have been gathered in the same run.

I've discovered that this is only true for versions > 2.3.0.0.

With version 2.3.0.0 installed the result above is:

```yaml
TASK [Gathering Facts] ********************************************************************************************************************************************************************************************************************************************************
ok: [host1.example.com]

TASK [return motd to registered var] ******************************************************************************************************************************************************************************************************************************************
changed: [host1.example.com]

TASK [debug test - motd] ******************************************************************************************************************************************************************************************************************************************************
ok: [host1.example.com] => {
    "changed": false, 
    "motd": {
        "changed": true, 
        "cmd": [
            "cat", 
            "/etc/motd"
        ], 
        "delta": "0:00:00.002076", 
        "end": "2017-08-11 00:05:43.564600", 
        "rc": 0, 
        "start": "2017-08-11 00:05:43.562524", 
        "stderr": "", 
        "stderr_lines": [], 
        "stdout": "", 
        "stdout_lines": []
    }
}

TASK [debug test - hostvars] **************************************************************************************************************************************************************************************************************************************************
ok: [host1.example.com] => {
    "changed": false, 
    "hostvars['host1.example.com']": "{u'ohai_chef_packages': {u'chef': {u'chef_root': u'/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib', u'version': u'12.5.1'}, u'ohai': {u'version': u'8.7.0', u'ohai_root': u'/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/ohai-8.7.0/lib/ohai'}}, u'module_setup': True, u'ohai_block_device': {u'ram14': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram15': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram12': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram13': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram10': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram11': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'md2': {u'rotational': u'1', u'removable': u'0', u'size': u'1459899616'}, u'md0': {u'rotational': u'1', u'removable': u'0', u'size': u'4194280'}, u'md1': {u'rotational': u'1', u'removable': u'0', u'size': u'1048552'}, u'ram8': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram9': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram4': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram5': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram6': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram7': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram0': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram1': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram2': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'ram3': {u'rotational': u'1', u'removable': u'0', u'size': u'32768'}, u'sda': {u'rotational': u'1', u'vendor': u'ATA', u'removable': u'0', u'rev': u'1H15', u'state': u'running', u'timeout': u'30', u'model': u'WDC WD7500AALX-0', u'size': u'1465149168'}
    (…)
}


```

**Comment by ghost** [comment]
Alright… when I'm using more than just test data I can reproduce this error even with 2.3.0.0.
But it seems that this happens when an inline vault string is used.
When using 2.3.0.0,  the error is "Odd-length string". For version > 2.3.0.0 it seems that the hostvars are fully discarded.

Here are my hostvars:

```yaml

---
  
rsyncd:
  shares:
    - name: root
      path: /
      auth_users: backup
      use_chroot: no
      read_only: no
      hosts_allow: xx.x.x.x
      
  users:
    - name: backup    
      password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        65313732383033353939373464343335656666643335386266353663373962303165316139613866
        6237313234343230643738396361386634393834316339380a333363636266663039303432666535
        37343864333466373335393763616230376636373538643436383934373232386338663134363935
        6633323466656437380a356163313562643266383863373339663239653532353630643061323730
        3032 

```

When not using an inline vault and a plain string instead everything works as expected.

**Comment by ghost** [comment]
OK… this happens when the inline vault is not indented correctly.

```yaml
rsyncd:
  shares:
    - name: root
      path: /
      auth_users: backup
      use_chroot: no
      read_only: no
      hosts_allow: x.x.x.x
      
  users:
    - name: backup    
      password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63626664366661373462633938376532663233353732376333386532663731353738616464643164
          6164383065343731336566346238303661633564656331370a623563623261346234326164373666
          36303435343434363234366432613936383432633138303438633962643331336230623139323739
          3938313230346535310a343239386165356233613564333432636661393637353933653265343165
          3034

```


Conclusion: Using invalid inline vault leads to unavailability of hostvars.

**Comment by bcoca** [comment]
Not really, other hostvars should exist, but making the YAML file invalid is probably preventing any of the other vars in same file from being defined. 

Since you don't supply a reproducing playbook (just the output), i cannot conform nor deny that this affects anything else.

The current bug would be that you get no warning on invalid YAML file (but i do get one in my tests). In either case I need more info to reproduce the error.

**Comment by ghost** [comment]
Please don't try to make the YAML invalid. Try to make just the inline vault string itself invalid.

**Comment by bcoca** [comment]
im not making it invalid, i suspect that is what is currently happening, so the other vars are not getting declared. I'm planning on issuing an error when this happens.

**Comment by ghost** [comment]
Hi Brian, how can I help you? Should I create some files which reproduce this behaviour?

**Comment by bcoca** [comment]
yes, that is what i asked for above, since i dont seem to be able to, tried to reconstruct same with info given but I either get everything working or an error on badly formatted yaml file.

**Comment by ghost** [comment]
Alright, I created a repo.

https://github.com/yves-vogl/ansible-inline-vault-issue

Here are the steps to reproduce:

Run 

```$ ansible-playbook -i inventory --vault-password-file=vault-secret tasks.yml ```


Output will be:

```yaml

PLAY [all] ***************************************************************************************************************************************************************

TASK [Display hostvars] **************************************************************************************************************************************************
fatal: [broken.example.com]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.hostvars.HostVars object' has no attribute u'broken.example.com'\n\nThe error appears to have been in '/Users/Yves/Desktop/#28038/tasks.yml': line 7, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n    - name: Display hostvars\n      ^ here\n"}
ok: [working.example.com] => {
    "msg": "working.example.com hostvars: {'inventory_hostname': u'working.example.com', 'inventory_file': u'/Users/Yves/Desktop/#28038/inventory', 'ansible_playbook_python': '/usr/bin/python', 'inventory_hostname_short': u'working', 'playbook_dir': u'/Users/Yves/Desktop/#28038', 'omit': '__omit_place_holder__a1db8ff276dbc6f01e212386f63938d9f50adc3e', 'inventory_dir': u'/Users/Yves/Desktop/#28038', 'group_names': [u'test-servers'], 'groups': {'ungrouped': [], 'all': [u'broken.example.com', u'working.example.com'], u'test-servers': [u'broken.example.com', u'working.example.com']}, 'ansible_check_mode': False, u'foo': {u'bar': u'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'}, 'ansible_version': {'major': 2, 'full': '2.3.1.0', 'string': '2.3.1.0', 'minor': 3, 'revision': 1}}"
}
	to retry, use: --limit @/Users/Yves/Desktop/#28038/tasks.retry

PLAY RECAP ***************************************************************************************************************************************************************
broken.example.com         : ok=0    changed=0    unreachable=0    failed=1   
working.example.com        : ok=1    changed=0    unreachable=0    failed=0   
```

The happens because of the content in `host_vars/broken.example.com/vars`:

```yaml
---
  
rsyncd:
  shares:
    - name: root
      path: /
      auth_users: backup
      use_chroot: no
      read_only: no
      hosts_allow: 1.2.3.4
      
  users:
    - name: backup    
      password: !vault |
         $ANSIBLE_VAULT;1.1;AES256
         64323332393930623633306662363165386332376638653035356132646165663632616263653366
         6233383362313531623238613461323861376137656265380a366464663835633065616361636231
         ifuckedupthissecret
         3366323866663763660a323766383531396433663861656532373663373134376263383263316261
         3137
```

Here you can see that I obviously messed around with the encrypted string.


When you fix the secret (see comment in tasks.yml) you get the complete output:

```yaml

$ ansible-playbook -i inventory --vault-password-file=vault-secret tasks.yml 

PLAY [all] ***************************************************************************************************************************************************************

TASK [Display hostvars] **************************************************************************************************************************************************
ok: [working.example.com] => {
    "msg": "working.example.com hostvars: {'inventory_hostname': u'working.example.com', 'inventory_file': u'/Users/Yves/Desktop/#28038/inventory', 'ansible_playbook_python': '/usr/bin/python', 'inventory_hostname_short': u'working', 'playbook_dir': u'/Users/Yves/Desktop/#28038', 'omit': '__omit_place_holder__f5ca75f8ba369d9173101da152d5bcc2e68f4f76', 'inventory_dir': u'/Users/Yves/Desktop/#28038', 'group_names': [u'test-servers'], 'groups': {'ungrouped': [], 'all': [u'broken.example.com', u'working.example.com'], u'test-servers': [u'broken.example.com', u'working.example.com']}, 'ansible_check_mode': False, u'foo': {u'bar': u'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'}, 'ansible_version': {'major': 2, 'full': '2.3.1.0', 'string': '2.3.1.0', 'minor': 3, 'revision': 1}}"
}
ok: [broken.example.com] => {
    "msg": "broken.example.com hostvars: {'inventory_hostname': u'broken.example.com', 'inventory_file': u'/Users/Yves/Desktop/#28038/inventory', 'ansible_playbook_python': '/usr/bin/python', 'inventory_hostname_short': u'broken', 'playbook_dir': u'/Users/Yves/Desktop/#28038', 'group_names': [u'test-servers'], 'inventory_dir': u'/Users/Yves/Desktop/#28038', u'rsyncd': {u'users': [{u'password': u'test', u'name': u'backup'}], u'shares': [{u'read_only': False, u'use_chroot': False, u'name': u'root', u'auth_users': u'backup', u'path': u'/', u'hosts_allow': u'1.2.3.4'}]}, 'groups': {'ungrouped': [], 'all': [u'broken.example.com', u'working.example.com'], u'test-servers': [u'broken.example.com', u'working.example.com']}, 'ansible_check_mode': False, 'omit': '__omit_place_holder__f5ca75f8ba369d9173101da152d5bcc2e68f4f76', 'ansible_version': {'major': 2, 'full': '2.3.1.0', 'string': '2.3.1.0', 'minor': 3, 'revision': 1}}"
}

PLAY RECAP ***************************************************************************************************************************************************************
broken.example.com         : ok=1    changed=0    unreachable=0    failed=0   
working.example.com        : ok=1    changed=0    unreachable=0    failed=0   

```

To summarize: I'd have expected to just the attribute with the broken secret instead of skipping the whole hostvars. Also I'd have expected a warning/error message which tells me that the encrypted string could not be decrypted.

But "decryption failed" is only logged if the decryption key is wrong - not if the encrypted string itself could not be decrypted.


I hope that helps.
