### ISSUE TITLE
ec2_vpc_igw pascal case properties

### ISSUE THREAD

**Issue by cheng93** [ansible/ansible#28035]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_vpc_igw
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/derek/Code/ansible-aws/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]

```

##### OS / ENVIRONMENT

arch linux
##### SUMMARY

On creation, the output has pascal case properties
##### STEPS TO REPRODUCE

```yaml
- name: Create {{group_name}} igw
  ec2_vpc_igw:
    aws_access_key: "{{aws_access_key}}"
    aws_secret_key: "{{aws_secret_key}}"
    region: "{{region}}"
    state: present
    #tags:
    #  Name: "{{group_name}}-igw"
    #  group: "{{group_name}}"
    vpc_id: "{{vpc.vpc.id}}"
  register: igw

- debug:
    var: igw
```

##### ACTUAL RESULTS

created
```
TASK [vpc : Create jenkins igw] ********************************************************************************************************************************
changed: [localhost]

TASK [vpc : debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "nat_gateway": {
        "CreateTime": "2017-08-10T20:59:04+00:00", 
        "NatGatewayAddresses": [
            {
                "AllocationId": "eipalloc-7dbf1614"
            }
        ], 
        "NatGatewayId": "nat-097a0a0ca53b4d041", 
        "State": "pending", 
        "SubnetId": "subnet-3b3ab540", 
        "VpcId": "vpc-2c64fb45", 
        "changed": true, 
        "msg": "", 
        "success": true
    }
}
```
no change
```
TASK [vpc : Create jenkins igw] ********************************************************************************************************************************
ok: [localhost]

TASK [vpc : debug] *********************************************************************************************************************************************
ok: [localhost] => {
    "nat_gateway": {
        "changed": false, 
        "create_time": "2017-08-10T20:59:04+00:00", 
        "msg": "NAT Gateway nat-097a0a0ca53b4d041 already exists in subnet_id subnet-3b3ab540", 
        "nat_gateway_addresses": [
            {
                "allocation_id": "eipalloc-7dbf1614", 
                "network_interface_id": "eni-c8a8c2b2", 
                "private_ip": "10.0.0.146"
            }
        ], 
        "nat_gateway_id": "nat-097a0a0ca53b4d041", 
        "state": "pending", 
        "subnet_id": "subnet-3b3ab540", 
        "success": true, 
        "vpc_id": "vpc-2c64fb45"
    }
}
```
