### ISSUE TITLE
hashi_vault plugin not recognizing hvac

### ISSUE THREAD

**Issue by BenCoffeed** [ansible/ansible#28050]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
[hashi_vault plugin](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/hashi_vault.py)

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /Users/btennant/Documents/GitHub/DevOps_bencoffeed/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
no recent changes. 

##### OS / ENVIRONMENT
Ansible is running on MacOS High Sierra targeting Ubuntu 16.04 running in EC2.
VAULT_ADDR and VAULT_TOKEN are exported as environment variables.

##### SUMMARY
Attempting to run the playbook listed below results in the error:
```
ASK [Gathering Facts] *************************************************************************************************************************************************************************************
fatal: [serverIP]: FAILED! => {
    "failed": true,
    "msg": "An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Please pip install hvac to use this module"
}
```

`pip list` shows hvac listed on both the localhost and the target server.

I've verified only one version of python installed on localhost and target. 2.7.10 on localhost, 2.7.12 on the target.
I've also verified that I can import hvac and read secrets both locally and on the target host without error.

##### STEPS TO REPRODUCE
```yml
---
- name: Configure production RWell App server
  hosts: "{{ target_hosts| default('app-servers') }}"

  vars:
    runtime_env: production
    api_key: "{{ lookup('hashi_vault','secret=secret/production/api_key:value') }}"

  environment:
    AWS_ACCESS_KEY: "{{ lookup('hashi_vault', 'aws/creds/common_get_s3_build:access_key') }}"
    AWS_SECRET_KEY: "{{ lookup('hashi_vault', 'aws/creds/common_get_s3_build:secret_key') }}"

  pre_tasks:
    - name: install dependencies for ansible
      apt: name={{ item }} state=latest
      with_items:
        - python-psycopg2
        - python-boto

  roles:
    - common
    - { role: users, include_dev: false }
    - postgres
    - { role: rwell-apps, server_role: app }
```

##### EXPECTED RESULTS
I expected the playbook to run and break somewhere later ;) . . .this was one of the first runs since converting the script to use Hashicorp Vault instead of variables defined in an Ansible-vault encrypted variable dictionary.

##### ACTUAL RESULTS
```
ansible-playbook app.yml --extra-vars "target_hosts=<IP>" -vvvv
Using /Users/btennant/Documents/GitHub/DevOps_bencoffeed/ansible.cfg as config file
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/common/tasks/CloudWatch.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/users/tasks/install_oh_my_zsh.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/rwell-apps/tasks/standalone_rwell_setup.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/rwell-apps/tasks/release_init.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/rwell-apps/tasks/production_rwell_setup.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/rwell-apps/tasks/release_init.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/rwell-apps/tasks/app_server.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/rwell-apps/tasks/api_server.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/rwell-apps/tasks/admin_server.yml
statically included: /Users/btennant/Documents/GitHub/DevOps_bencoffeed/roles/rwell-apps/tasks/util_server.yml
Loading callback plugin default of type stdout, v2.0 from /usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: app.yml ******************************************************************************************************************************************************************************************
1 plays in app.yml

PLAY [Configure production RWell App server] ***************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************
fatal: [<IP>]: FAILED! => {
    "failed": true,
    "msg": "An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Please pip install hvac to use this module"
}
	to retry, use: --limit @<Ansible directory>/app.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
<IP>                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by srinathkotu** [comment]
I am having the same issue, using the same ansible version and OS environment

**Comment by srinathkotu** [comment]
installing [`hvac[parser]`](https://github.com/ianunruh/hvac) seems to have fixed the issue:

```
pip install hvac[parser]
```

**Comment by Akasurde** [comment]
@BenCoffeed Could you please try suggestion given by @srinathkotu and let us know if it helps ?

needs_info

**Comment by ansibot** [comment]
@BenCoffeed This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by BenCoffeed** [comment]
I'm digging into this this week. I was tinkering with [jhaals/ansiblevault](https://github.com/jhaals/ansible-vault). I'll retry with this, though.

**Comment by BenCoffeed** [comment]
I've tried again. Here are my steps for troubleshooting:
```
brew uninstall ansible
brew uninstall python
brew uninstall python3
sudo pip uninstall pip
sudo easy_install pip
sudo pip install ansible
sudo pip install "hvac[parser]"
```

`ansible --version`
```
ansible 2.4.3.0
  config file = /Users/btennant/GitHub/DevOps_bencoffeed/ansible.cfg
  configured module search path = [u'/Users/btennant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

`python --version`
```
Python 2.7.10
```

`pip --version`
```
pip 9.0.1 from /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg (python 2.7)
```

`pip freeze`
```
pip freeze
altgraph==0.10.2
ansible==2.4.3.0
asn1crypto==0.23.0
awscli==1.11.136
bcrypt==3.1.4
bdist-mpkg==0.5.0
bonjour-py==0.3
boto==2.48.0
boto3==1.4.7
botocore==1.7.17
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
colorama==0.3.7
cryptography==2.1.4
docutils==0.14
enum34==1.1.6
futures==3.1.1
github3.py==1.0.0a4
hvac==0.3.0
idna==2.6
ipaddress==1.0.18
Jinja2==2.10
jmespath==0.9.3
macholib==1.5.1
MarkupSafe==1.0
matplotlib==1.3.1
modulegraph==0.10.4
ndg-httpsclient==0.4.3
numpy==1.8.0rc1
paramiko==2.4.0
ply==3.4
psycopg2==2.7.3.2
py2app==0.7.3
pyasn1==0.3.2
pycparser==2.18
pyhcl==0.2.3
PyNaCl==1.2.1
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==0.13.1
pyparsing==2.0.1
python-dateutil==2.6.1
pytz==2013.7
PyYAML==3.12
requests==2.18.4
rsa==3.4.2
s3transfer==0.1.11
scipy==0.13.0b1
six==1.11.0
uritemplate==3.0.0
uritemplate.py==3.0.2
urllib3==1.22
vboxapi==1.0
virtualenv==15.1.0
xattr==0.6.4
zope.interface==4.1.1
```


Still, when I run my playbook I get:
```
vars:
    api_key: "{{ lookup('hashi_vault','secret/development/api_key:value') }}"
. . . 
pre_tasks:
    - debug:
      var: "{{ api_key }}"
```

```json
{
    "msg": "{{ lookup('hashi_vault','secret/development/api_key:value') }}: An unhandled exception occurred while running the lookup plugin 'hashi_vault'. Error was a <class 'ansible.errors.AnsibleError'>, original message: hashi_vault lookup plugin needs key=value pairs, but received ['secret/development/api_key:value']"
}

```

**Comment by srinathkotu** [comment]
just FYI.. below is my pre_task for the vault's pip dependencies:
```
    - name: Installing pip modules for using vault lookup
      pip: name={{item}}
        with_items:
          - hvac
          - hvac[parser]
```

**Comment by BenCoffeed** [comment]
🤦‍♂️  Duh. . .
Good news: I'm not getting the hvac not installed error.
Bad news: Python is hard-crashing, but that's another bug report and some more digging.

For others, here's my updated format:
```yml
. . .
  vars:
    api_key: "{{ secret=lookup('hashi_vault','secret/development/api_key:value') }}"
. . .
  pre_tasks:
    - name: Install Pip
      apt: 
        name: python-pip
        state: latest

    - name: Install ansible pip dependencies for Ansible
      pip:
        name: "{{ item }}"
        state: latest
      with_items:
        - pip
        - psycopg2
        - boto
        - hvac
        - "hvac[parser]"
 
    - debug:
        var: "{{ api_key }}"
```
