### ISSUE TITLE
LVOL snapshot creation ask for confirmation in some corner case

### ISSUE THREAD

**Issue by VAdamec** [ansible/ansible#28052]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
LVOL

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/library/']
  python version = 2.7.5 (default, Sep  5 2016, 02:30:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]
```

##### CONFIGURATION
Not aplicable

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.4

##### SUMMARY
I have ansible playbook which do mysql backup using LVM snapshot, occasionally I get into state where LVM request confirmation

##### STEPS TO REPRODUCE
Repeat snapshot creating end removing

```yaml

  - name: Create snapshot
    lvol:
      vg: "{{ VG_NAME }}"
      lv: "{{ LV_NAME }}"
      snapshot: "{{ snapshot }}"
      size: 300G
      force: yes

  - name: Merge/Drop snapshot
    shell: "lvconvert --merge /dev/{{ VG_NAME }}/{{ snapshot }}"

  - name: LV backup deactivation
    shell: "lvchange -an /dev/{{ VG_NAME }}/{{ LV_NAME }}"

  - name: LV backup activation
    shell: "lvchange -ay /dev/{{ VG_NAME }}/{{ LV_NAME }}"

```

##### EXPECTED RESULTS
 force: yes or opts: '-y' should handle confirmation (although I don't know if it's correct to resulted snapshot and origin content)

##### ACTUAL RESULTS

```
fatal: [172.24.248.241]: FAILED! 
=> {"changed": false, 
"err": "Change of snapshot vg_backup/snap1 will also change its origin vg_backup/lv_backup. Proceed? [y/n]: [n]\n  
Logical volume vg_backup/snap1 not changed.\n", "failed": true, 
"msg": "Failed to activate logical volume lv_backup", "rc": 5}
```

**Comment by ansibot** [comment]
cc @abulimov @jhoekx
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nfj25** [comment]
I also have this problem with
```
# ansible --version
ansible 2.8.5
```

When I do:

```
  - name: "Take Snapshots"
    lvol: 
      vg: "vgsystem" 
      lv: "root" 
      snapshot: "lv_root_snap"
      size: "2G"
```

And the snapshot already exists, it hangs with lvchange asking for a user input. After I kill the lvchange it returns:

```
    "msg": "Failed to activate logical volume root",
    "rc": -9,
    "err": "Change of snapshot vgsystem/lv_root_snap will also change its origin vgsystem/root. Proceed? [y/n]: ",
    "invocation": {
        "module_args": {
            "pvs": null,
            "force": false,
            "vg": "vgsystem",
            "lv": "root",
            "resizefs": false,
            "state": "present",
            "thinpool": null,
            "snapshot": "lv_root_snap",
            "active": true,
            "shrink": true,
            "opts": null,
            "size": "2G"
        }

```

Maybe I should not create a snapshot if it already exists (perhaps it should do a refresh?) but it definitely should not hang.
