### ISSUE TITLE
(P1) nxos_snapshot compare does not work

### ISSUE THREAD

**Issue by saichint** [ansible/ansible#28079]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_snapshot

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 54cd641df4) last updated 2017/07/19 18:06:44 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/p2/Projects/nxos_ansible/p1_ansible/lib/ansible
  executable location = /root/p2/Projects/nxos_ansible/p1_ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT
Ansible Server : Ubuntu 14.04
Device: Nexus7000 C7010 running 8.1(1)

##### SUMMARY
When we try to compare 2 snapshots, it is supposed save the difference in a file but nothing happens. The issue seems to be that, there is a method write_on_file() defined but never getting called. So basically, the output of the compare is just thrown away once the task is complete and the properties "comparison_results_file", "path" and "save_snapshot_locally" are never being used.

##### STEPS TO REPRODUCE
playbook:

```
- name: create snapshot
  nxos_snapshot:
    action: create
    snapshot_name: test_snapshot1
    description: Ansible
    provider: "{{ cli }}"

- nxos_snapshot:
    action: create
    snapshot_name: test_snapshot2
    description: row
    section: myshow
    show_command: show ip interface brief
    row_id: ROW_intf
    element_key1: intf-name
    provider: "{{ cli }}"

- nxos_snapshot:
    action: compare
    snapshot1: test_snapshot1
    snapshot2: test_snapshot2
    comparison_results_file: compare_snapshots.txt
    compare_option: summary
    path: '/root/p2'
    provider: "{{ cli }}"

- name: delete snapshot
  nxos_snapshot:
    action: delete_all
    snapshot_name: test_snapshot
    provider: "{{ cli }}"
```

##### EXPECTED RESULTS
A file "compare_snapshots.txt" should be created in the given path.

##### ACTUAL RESULTS
Nothing happens, no file is created.
