### ISSUE TITLE
(P2) nxos_bgp_af idempotence fails when multiple networks are defined

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#28080]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_bgp_af

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel ebb1d75ee0) last updated 2017/08/10 15:40:07 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04 

##### SUMMARY

nxos_bgp_af module crops the list of networks to the first one when checking for existing networks. This causes idempotence issues.

##### STEPS TO REPRODUCE

```yaml
---
- name: NXOS Sample Playbook
  hosts: nxos
  connection: local
  gather_facts: no

  tasks:

  - set_fact:
      bgp_af_def:
      - {bgp_af: ipv4, bgp_saf: unicast , adv_net: ['10.114.0.0/16', '10.74.0.0/16', '137.221.96.0/22', '137.221.100.0/22'] }
      - {bgp_af: ipv6, bgp_saf: unicast , adv_net: ['2a04:e800:5010:3623::/64', '2a04:e800:5010:3673::/64'] }

  - name: turn on BGP
    nxos_feature:
      feature: bgp
      state: enabled
      provider: "{{ cli }}"

  - name: BGP Address Family Config
    nxos_bgp_af:
      asn: 65535
      afi: "{{ item.bgp_af }}"
      safi: "{{ item.bgp_saf }}"
      networks: "{{ item.adv_net }}"
      maximum_paths: 8
      maximum_paths_ibgp: 8
      provider: "{{ cli }}"
    with_items: "{{ bgp_af_def }}"
```
