### ISSUE TITLE
Have the ec2_asg module stop overshooting instances.

### ISSUE THREAD

**Issue by einarc** [ansible/ansible#28087]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_asg Module
##### ANSIBLE VERSION

```

```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### OS / ENVIRONMENT

RHEL7 and AWS
##### SUMMARY

Prevent the ec2_asg module from overshooting when either creating or updating an autoscaling group.
##### STEPS TO REPRODUCE

1.-Call the ec2_asg module for AWS using the replace_all_instances and replace_batch_size set to all and 1 respectively.
2.-Watch how AWS launches the ASG when Boto talks to the AWS API, it wastes resources and time. See behavior below.

```yaml
  ec2_asg:
    name: "{{ app_name }}"
    load_balancers: "{{ app_name }}"
    launch_config_name: "{{ launch_config.name }}"
    min_size:  4
    max_size: 8
    desired_capacity: 4
    region: "{{ region }}"
    vpc_zone_identifier: "{{ subnets | join(',') }}"
    health_check_type: EC2
    replace_all_instances: yes
    replace_batch_size: 1
    lc_check: false
    default_cooldown: 1200
    health_check_period: 1200
```

##### EXPECTED RESULTS

An ASG is created with min, desired and max values set as indicated by the Ansible YAML code. The amount of instances created only reaches the desired amount.
##### ACTUAL RESULTS

The ASG launches the MAXIMUM amount of instances: 8 then scales down by terminating the instances until it reaches the desired amount. If the ASG health check is based on an ELB this might cause the ec2_asg module to time out and fail. Not to mention customers have to OVERPAY for instances they'll never get to use.

```

```

**Comment by ansibot** [comment]
cc @garethr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by einarc** [comment]
Here's an example of how the module fails when it takes longer than the healthcheck period (1200 seconds mind in this example):

`{
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "changed": false,
    "failed": true,
    "invocation": {
        "module_name": "ec2_asg",
        "module_args": {
            "default_cooldown": 1200,
            "health_check_period": 1200,
            "ec2_url": null,
            "aws_secret_key": null,
            "lc_check": false,
            "availability_zones": null,
            "replace_batch_size": 1,
            "replace_instances": [],
            "desired_capacity": 1,
            "state": "present",
            "health_check_type": "ELB",
            "max_size": 1,
            "profile": null,
            "tags": [
                {
                    "Name": "redeem-dev"
                },
                {
                    "Application": "redeem"
                },
                {
                    "Originating_ECM": "ECM-1736"
                },
                {
                    "Product_Owner": "bshamsian@boingo.com"
                },
                {
                    "Resource_Owner": "ecoutin@boingo.com"
                },
                {
                    "Role": "Comes-with-Boingo"
                },
                {
                    "Service_Category": "Platform Systems - Wordpress - redeem.boingo.com"
                }
            ],
            "min_size": 1,
            "vpc_zone_identifier": [
                "subnet-6673d410",
                "subnet-7cfe7218"
            ],
            "load_balancers": [
                "redeem-dev"
            ],
            "launch_config_name": "redeem-dev-copy-1502491816",
            "aws_access_key": null,
            "name": "redeem-dev",
            "security_token": null,
            "replace_all_instances": true,
            "wait_for_instances": true,
            "region": "us-west-2",
            "termination_policies": [
                "Default"
            ],
            "wait_timeout": 300,
            "notification_topic": null,
            "notification_types": [
                "autoscaling:EC2_INSTANCE_LAUNCH",
                "autoscaling:EC2_INSTANCE_LAUNCH_ERROR",
                "autoscaling:EC2_INSTANCE_TERMINATE",
                "autoscaling:EC2_INSTANCE_TERMINATE_ERROR"
            ],
            "validate_certs": true
        }
    },
    "msg": "Waited too long for ELB instances to be healthy. Fri Aug 11 18:58:07 2017"
} `

Code is the same as above.

**Comment by alikins** [comment]
@einarc Could you test this with ansible-2.3 or the current ansible devel branch from git? There have been a lot of changes to the ec2_asg.py since ansible-2.2.

If possible, paste a copy of the 'ansible-playbook' output with the '-vvvv' verbosity level enabled for a run that shows this error.

**Comment by einarc** [comment]
@alikins  Version 2.3.2 passes Unit Testing, unfortunately we still have to do regression and integration with the rest of our code to make sure the update did not break things or introduced new bugs. Not to mention we're using Tower so Integration is also required.

**Comment by einarc** [comment]
I cannot update to 2.3.2 because it breaks another module, aws s3:

"
![image](https://user-images.githubusercontent.com/6519208/29736598-a642bd02-89b7-11e7-9d6f-48df2012acc2.png)

"

Code:
- name: Inject SQL - Get dump
  s3: bucket="{{ s3_bucket }}" object="{{ s3_key }}" dest="{{ s3_sql_file }}" mode=get overwrite=always
  when: create_rds
  tags: rds_database
  when: create_rds

Case:
https://access.redhat.com/support/cases/#/case/01904604

On the other hand 2.1.2 handles the same file on the same DB instance with success, the only thing that changed was the ansible core version. Here's output:
![image](https://user-images.githubusercontent.com/6519208/29736625-ef8e57aa-89b7-11e7-949f-e421eae81624.png)


![image](https://user-images.githubusercontent.com/6519208/29736617-e06636b2-89b7-11e7-8294-aaf139326d72.png)

[2.2.1-Ansible-Core-Inject-DB-Success.txt](https://github.com/ansible/ansible/files/1253262/2.2.1-Ansible-Core-Inject-DB-Success.txt)


[2.3.2-Ansible-Core_Failed.txt](https://github.com/ansible/ansible/files/1253263/2.3.2-Ansible-Core_Failed.txt)

**Comment by einarc** [comment]
Reducing file size to about 630 MB, still no success.

**Comment by einarc** [comment]
Hello,

Actually we're still seeing the same behavior on 2.3.2 as in 2.2.1,
![image](https://user-images.githubusercontent.com/6519208/29897810-8c92dd22-8d97-11e7-8fbf-d2c1e514a49c.png)

![image](https://user-images.githubusercontent.com/6519208/29897840-a4599fe0-8d97-11e7-814e-c99247579ff8.png)


![image](https://user-images.githubusercontent.com/6519208/29897887-f2f51f9e-8d97-11e7-954e-e8f9bd8f4908.png)

**Comment by einarc** [comment]
And btw, this ALSO affects 2.3.2, so please go ahead and add that tag

**Comment by ansibot** [comment]
cc @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by josephtate** [comment]
Still affecting ansible 2.4.3.0.


Edit. Well, perhaps not. I asked for max_cap 3 desired_cap 3, have two running, asked for 1 to be killed, 3 started and then one was terminated a minute later.

**Comment by msven** [comment]
I ran into this issue as well.  Looking into it I think the issue is related to `lc_check: false` in combination with `replace_all_instances: yes`. I believe I understand where the issue is and will try to submit a pull request for a fix this weekend.

Also, giving the specific replace_instances list worked for me instead of using `replace_all_instances` as a temporary workaround. e.g.
```
---

- hosts: localhost
  gather_facts: false
  tasks:
    - ec2_asg_facts:
        name: "{{asg_name}}"
      register: ec2_facts

    # If asg doesn't exist yet results won't be defined
    - set_fact:
        rinst: "{{ ec2_facts.results.0.instances|map(attribute='instance_id')|list }}"
      when:
          ec2_facts.results

    - ec2_asg:
        name: "{{ asg_name }}"
        launch_config_name: test-lc
        replace_instances: "{{ rinst|default( [] ) }}"
        wait_for_instances: true
        lc_check: false
        min_size: 2
        max_size: 2
        desired_capacity: 2
        replace_batch_size: 2
```
