### ISSUE TITLE
pamd eats trailing comma in module_arguments

### ISSUE THREAD

**Issue by Cerebus** [ansible/ansible#28096]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pamd

##### ANSIBLE VERSION
```
ansible 2.3.1.0
config file =
configured module search path = Default w/o overrides
python version = 2.7.13 (default, March 13 2017, 20:56:15) [GCC 5.4.0]
```

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If module_arguments has a trailing comma, the resulting line in the module stack has an empty string.

##### STEPS TO REPRODUCE
pam_access.so requires the argument "listsep=," in order to parse Active Directory groups properly, as they often contain spaces (e.g., "Domain Users").  pamd is unable to add this argument correctly; quoted strings and escape sequences have no effect. 

For example, attempting this task on Ubuntu fails:

```yaml
- name: Ensure specific arguments are present in a rule
  pamd:
    name: common-account
    type: account
    control: required
    module_path: pam_access.so
    module_arguments: "listsep=,"
    state: args_present
```

##### EXPECTED RESULTS
The task should add "listsep=," to the pam_access.so line.

##### ACTUAL RESULTS
pamd adds "listsep= ".

Sorry, verbatim output not available; source is on a closed network.
