### ISSUE TITLE
xml module: Changing an attribute value is non-obvious ('attribute' is not documented)

### ISSUE THREAD

**Issue by gerph** [ansible/ansible#28119]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
lib/ansible/modules/files/xml.py

##### ANSIBLE VERSION

```shell
charles@work ~/ansible.gerph (master￪13)> ansible --version
ansible 2.2.1.0
  config file = /home/charles/.ansible.cfg
  configured module search path = Default w/o overrides
```

I'm using the module on an earlier version of ansible than the latest, as I've just noticed that it's been pulled in to the main core. This particular issue should not be relevant to the version.

##### OS / ENVIRONMENT
N/A, although I'm testing with ubuntu/trusty.

##### SUMMARY
I want to change an attribute value in an XML file, but the way you do it isn't obvious using the documented calls. The 'xpath' parameter + 'value' would seem to be all I need, but it appears that when changing the attribute of an element it is necessary to explicitly select the element node and supply the attribute value, rather than specifying the attribute node and giving the value to set.

##### STEPS TO REPRODUCE
My initial attempt to do this was:

```yaml
- name: Update port number
  xml:
    file: /opt/jfrog/artifactory/tomcat/conf/server.xml
    xpath: "/Server/Service/Connector[not(@protocol)]/@port"
    value: "{{ artifactory_port }}"
    pretty_print: yes
```
However this returns an error, saying that it selects no nodes. That seems an outright lie :) For example:

```shell
root@charon:/home/local# xpath -e '/Server/Service/Connector[not(@protocol)]/@port' /opt/jfrog/artifactory/tomcat/conf/server.xml
Found 1 nodes in /opt/jfrog/artifactory/tomcat/conf/server.xml:
-- NODE --
 port="8081"

root@charon:/home/local# xmllint --xpath '/Server/Service/Connector[not(@protocol)]/@port' /opt/jfrog/artifactory/tomcat/conf/server.xml
 port="8081"
```

Both the perl xpath, and the xmllint one both believe that this selects a node for the attribute.

A little digging around showed that there is an 'attribute' parameter that names the attribute on an element node that needs to be set. The following works:

```yaml
- name: Update port number
  xml:
    file: /opt/jfrog/artifactory/tomcat/conf/server.xml
    xpath: "/Server/Service/Connector[not(@protocol)]"
    attribute: 'port'
    value: "{{ artifactory_port }}"
    pretty_print: yes
```

So the problem is at least 2-fold:

* Changing an attribute value is non-obvious, and requires the element to be selected, and an out-of-xpath 'attribute' supplied.
* The documentation of the 'attribute' parameter is not given.

... and potentially:

* An example of changing an attribute value would really help make this obvious.

It'd be nice if the xpath '.../@port' could be used, rather than having a separate syntax for changing attribute values, but as a quick and easy fix, documenting that it's not (and maybe giving a clue in the error message if the xpath element ends in `/@<name>`) would probably be enough.

##### EXPECTED RESULTS
* I had expected that plain 'xpath' + 'value' to work.
* I had hoped to find something in the documentation that would explain why this didn't work and what I needed to do to change the attribute.
* (after finding the answer by looking at the test code) I had hoped that I had missed the documentation of the 'attribute' parameter.
