### ISSUE TITLE
[parted] Can't create BIOS boot partition on GPT disk

### ISSUE THREAD

**Issue by anonymous09** [ansible/ansible#28126]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

parted

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Dec 10 2016, 01:52:44) [GCC 5.4.0]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Module "parted" doesn't handle fs-type option:
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/parted.py#L559

##### STEPS TO REPRODUCE

Try create BIOS boot partition on GPT disk

```yaml
- name: Create Grub BIOS Partition
  parted:
    device: "{{ main_disk }}"
    number: 1
    part_type: primary ef02
    state: present
```

##### EXPECTED RESULTS

Ansible should create BIOS boot partition on GPT disk.

##### ACTUAL RESULTS

Error: value of part_type must be one of: primary,extended,logical, got: primary ef02.

```
TASK [gentoo-remote-install : Create Grub BIOS Partition] *********************************************************************************************************************************************************
fatal: [anonymous.net.eu.org]: FAILED! => {"changed": false, "failed": true, "msg": "value of part_type must be one of: primary,extended,logical, got: primary ef02"}

```
