### ISSUE TITLE
letsencrypt v2.4 http-01 certificate validation false positive error - No 'Not after' date found

### ISSUE THREAD

**Issue by joshmorel** [ansible/ansible#28148]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
letsencrypt

##### ANSIBLE VERSION
```
ansible-doc 2.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/morel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-doc
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
logging on - doesn't make a difference

##### OS / ENVIRONMENT
Both are:
Ubuntu 16.04.3 LTS x64

##### SUMMARY

I get this error in version 2.4.0 when trying to create a letsencrypt certificate which I confirmed does not occur in 2.3.2.

`FAILED! => {"changed": false, "failed": true, "msg": "No 'Not after' date found in /etc/letsencrypt/certs/********.crt"}`

##### STEPS TO REPRODUCE
```
--- # Install Letsencrypt Certificate

- name: Create ssl file directories
  file:
    path: "{{ ssl_root }}/{{ item }}"
    state: directory
  with_items:
    - csr
    - keys
    - certs

- name: Generate account key
  command: "openssl genrsa -out {{ ssl_root }}/account.key"

- name: Generate certificate private key
  command: "openssl genrsa -out {{ ssl_root }}/keys/{{ inventory_hostname }}.pem"

- name: Generate certificate signing request
  command: "openssl req -new -sha256 -key {{ ssl_root }}/keys/{{ inventory_hostname }}.pem -out {{ ssl_root }}/csr/{{ inventory_hostname }}.pem -subj /CN={{ inventory_hostname }}"

- name: Initiate letsencrypt challenge
  letsencrypt:
    account_key: "{{ ssl_root }}/account.key"
    csr: "{{ ssl_root }}/csr/{{ inventory_hostname }}.pem"
    acme_directory: "https://acme-v01.api.letsencrypt.org/directory"
    dest: "{{ ssl_root }}/certs/{{ inventory_hostname }}.crt"
    account_email: "{{ admin_email }}"
    challenge: "http-01"
  register: letsencrypt_challenge

- name: Create directory to fulfill letsencrypt challenge
  file:
    dest: /var/www/html/{{ letsencrypt_challenge['challenge_data'][inventory_hostname]['http-01']['resource']|dirname }}
    state: directory

- name: Create file to fulfill letsencrypt challenge
  copy:
    dest: /var/www/html/{{ letsencrypt_challenge ['challenge_data'][inventory_hostname]['http-01']['resource'] }}
    content: "{{ letsencrypt_challenge ['challenge_data'][inventory_hostname]['http-01']['resource_value'] }}"
    owner: www-data
    group: www-data
    mode: 0644
  when: letsencrypt_challenge|changed

- name: Write signed letsencrypt certificate
  letsencrypt:
    account_key: "{{ ssl_root }}/account.key"
    csr: "{{ ssl_root }}/csr/{{ inventory_hostname }}.pem"
    dest: "{{ ssl_root }}/certs/{{ inventory_hostname }}.crt"
    acme_directory: "https://acme-v01.api.letsencrypt.org/directory"
    account_email: "{{ admin_email }}"
    challenge: "http-01"
    data: "{{ letsencrypt_challenge }}"
```

##### EXPECTED RESULTS

Success.

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_1eahLV/ansible_module_letsencrypt.py", line 218, in get_cert_days
    not_after = datetime.datetime.fromtimestamp(time.mktime(time.strptime(not_after_str, '%b %d %H:%M:%S %Y %Z')))

fatal: [ilios.refactored.ca]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "account_email": "OMITTED", 
            "account_key": "/etc/letsencrypt/account.key", 
            "acme_directory": "https://acme-v01.api.letsencrypt.org/directory", 
            "agreement": "https://letsencrypt.org/documents/LE-SA-v1.1.1-August-1-2016.pdf", 
            "challenge": "http-01", 
            "csr": "/etc/letsencrypt/csr/ilios.refactored.ca.pem", 
            "data": null, 
            "dest": "/etc/letsencrypt/certs/ilios.refactored.ca.crt", 
            "remaining_days": 10
        }
    }, 
    "msg": "No 'Not after' date found in /etc/letsencrypt/certs/ilios.refactored.ca.crt"
}
```
