### ISSUE TITLE
ResourceNotFoundError when assigning disk to GC instance

### ISSUE THREAD

**Issue by flawaetz** [ansible/ansible#28168]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lib/ansible/modules/cloud/google/gce.py

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /data/DevOps/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Running on Ubuntu 16.0.4.2 LTS inside Google Cloud

##### SUMMARY
@supertom @bcoca 
ansible instance creation fails due to error indicating it can not find the assigned boot disk.  This same playbook runs fine with ansible 2.3.2.  I suspect this commit is responsible for the changed behavior:

https://github.com/ansible/ansible/commit/1c38cba7ca408630b37670d054beaa87cf84c4fc

##### STEPS TO REPRODUCE
Playbook excerpts:

```
    - name: Create boot disk
      gce_pd:
        disk_type: pd-ssd
        zone: us-east1-c
        image: ubuntu-1604-xenial-v20170619a
        name:  "{{ instance_name }}-boot0"
        size_gb:  20

    - name: Provision instance
      gce:
        instance_names: "{{ instance_name }}"
        zone: us-east1-c
        disk_size: 16
        machine_type: n1-standard-8
        image: ubuntu-1604-xenial-v20170619a
        state: active
        disks:
         - name: "{{ instance_name }}-boot0"
           mode: READ_WRITE
```
##### ACTUAL RESULTS
Stack trace is as follows:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_FXUuZr/ansible_module_gce.py", line 735, in <module>
    main()
  File "/tmp/ansible_FXUuZr/ansible_module_gce.py", line 700, in main
    module, gce, inames, number, lc_zone)
  File "/tmp/ansible_FXUuZr/ansible_module_gce.py", line 419, in create_instances
    lc_disks.append(gce.ex_get_volume(disk['name'], lc_zone))
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 7100, in ex_get_volume
    return self._ex_lookup_volume(name, zone)
  File "/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py", line 7411, in _ex_lookup_volume
    zone), None, None)
libcloud.common.google.ResourceNotFoundError: u'Volume \'deleteme-boot0\' not found for zone <GCEZone id="2233" name="us-east1-c" status="UP">.'
```
Proof disk exists:
```
$ gcloud compute disks describe deleteme-boot0 --zone us-east1-c | grep status
status: READY
```

**Comment by ansibot** [comment]
cc @erjohnso
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
ping @supertom Could https://github.com/ansible/ansible/commit/1c38cba7ca408630b37670d054beaa87cf84c4fc be involved here?

**Comment by erjohnso** [comment]
I think this is a timing issue. I was able to reproduce the error, but if I introduce a delay, then the instance gets created the the specified disk.  See if this works for you,

```
  tasks:
    - name: pd-ssd
      gce_pd:
        disk_type: pd-ssd
        zone: us-east1-c
        image: ubuntu-1604-xenial-v20170619a
        name:  inst-boot0
        size_gb:  20

    - name: sleep for a bit...
      pause:
        minutes: 1

    - name: instance
      gce:
        instance_names: inst
        zone: us-east1-c
        machine_type: n1-standard-1
        disks:
          - name: inst-boot0
            mode: READ_WRITE
```
