### ISSUE TITLE
Foreman module going for katello API

### ISSUE THREAD

**Issue by rgarrigue** [ansible/ansible#28167]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME

Foreman module

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2+ (default, Sep 22 2016, 12:18:14) [GCC 6.2.0 20160927]
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

Ubuntu 16.10 Unity

##### SUMMARY

I use ansible to install puppet agent, sign cert on master, and last step would be to switch them to enable "managed" and assign a default puppet class, using foreman module. But this module go for katello api, which isn't installed in my foreman 1.15.1.

In my humble opinion it should use foreman own api. Or this point should be documented.

##### STEPS TO REPRODUCE

Install foreman without Katello

```yaml
---
- hosts: all
  tasks:
  - name: Enable server in foreman and set puppet classes to roles::default
    local_action:
      module: foreman
      username: myself
      password: ...............
      server_url: https://foreman01
      entity: host
      params:
        name: "{{inventory_hostname}}"
        managed: True
        puppet_ca_proxy_id: "2"
        puppet_ca_proxy_name: smartproxy01
        puppetclasses:
        - roles::default
```

##### EXPECTED RESULTS

Working 

##### ACTUAL RESULTS

```
TASK [Enable server in foreman and set puppet classes to roles::default] ************************************************************************************************************************************
fatal: [server.local.domain -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to connect to Foreman server: 404 Client Error: Not Found for url: https://foreman01/katello/api/v********/organizations "}

```

**Comment by ansibot** [comment]
cc @ehelms
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
I'm also seeing this, makes the module 100% non-functional if you're running foreman and not katello.

**Comment by milliams** [comment]
The same here. I have the following in my playbook:
```yaml
- name: create CentOS 7 medium
  foreman:
    username: admin
    password: "{{password}}"
    server_url: https://foreman.priv
    entity: media
    params:
      name: CentOS 7 x86_64
      os_family: Redhat
      path: http://packages.priv/isos/CentOS-7-x86_64/
```

and the output I get is:
```python-traceback
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_2TJfxV/ansible_module_foreman.py", line 140, in main
    org.search()
  File "/usr/lib/python2.7/site-packages/blinker_herald/base.py", line 137, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 1361, in search
    results = self.search_json(fields, query)['results']
  File "/usr/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 1213, in search_json
    response.raise_for_status()
  File "/usr/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 404 Client Error: Not Found for url: https://foreman.priv/katello/api/v2/organizations

fatal: [foreman.priv]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "entity": "media", 
            "params": {
                "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "os_family": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "path": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "server_url": "https://foreman.priv", 
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "verify_ssl": false
        }
    }, 
    "msg": "Failed to connect to Foreman server: 404 Client Error: Not Found for url: https://foreman.priv/katello/api/v2/organizations "
}
```

I don't have organisations set up and I don't have Katello installed. It's just a basic Foreman install. This makes using this module for anything impossible.

@ehelms Is there any way we can help get this fixed? Or is this a bug in nailgun?
