### ISSUE TITLE
Support 'recurse=yes' in 'template' action

### ISSUE THREAD

**Issue by michaelkrupp** [ansible/ansible#2818]
It would be great if a complete directory-tree could be synced, and all files under it rendered as templates. 

The following definition sould (IMHO) create a directory /some/conf.d/ with mode 755 (cause it's a directory, not a file), sync all files found under /some/directory/conf.d/, but parse them as templates before and set mode 644.

``` yaml
template: >
    dest=/some/conf.d/
    src=/some/directory/conf.d/
    recurse=yes
    mode=644
```

**Comment by bcoca** [comment]
i use with_lines/files/pipe to do this

On Tue, Apr 30, 2013 at 9:11 PM, keksinat0r notifications@github.comwrote:

> It would be great if a complete directory-tree could be synced, and all
> files under it rendered as templates. I'm used to having this feature,
> coming from Puppet and Saltstack.
> 
> The following definition sould (IMHO) create a directory /some/conf.d/
> with mode 755 (cause it's a directory, not a file), sync all files found
> under /some/directory/conf.d/, but parse them as templates before and set
> mode 644.
> 
> template: >
>     dest=/some/conf.d/
>     src=/some/directory/conf.d/
>     recurse=yes
>     mode=644```
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ansible/ansible/issues/2818
> .

## 

Brian Coca
Stultorum infinitus est numerus
0110000101110010011001010110111000100111011101000010000001111001011011110111010100100000011100110110110101100001011100100111010000100001
Pedo mellon a minno

**Comment by mpdehaan** [comment]
with_fileglob is also useful!

**Comment by mpdehaan** [comment]
BTW, should be like this:  (using 1.2 syntax):

```
- copy: src={{ item }} dest=/some/remote/dir/
  with_fileglob:
      - local_path/*.txt
```

Not entirely recursive.

The best way to do this is really:

local_action: rsync -avz some_dir user@{{ inventory_hostname }}/where/to

Where basically ansible is just invoking rsync and specifying the remote hostname from the host loop to use.

There are some examples of this in the technical FAQ in the docs.

**Comment by daniilyar** [comment]
@mpdehaan, I see that issue author (just like me) looks for solution which would template each file into target directory recursively (with preserving relative paths).
@bcoca, could you, please, share an example of how do you implement this using 'with_lines/files/pipe'?

**Comment by michaelkrupp** [comment]
@daniilyar, back then I ended up working around this issue:
- render templates from `/src/` into a temporary directory `/temp/`
- remove files in `/src/` that do not exist in `/temp/`
- synchronize `/temp/` to `/dest/` using rsync

it's ugly and tedious, but worked back then. You can do all this using the `with_*` syntax.

**Comment by daniilyar** [comment]
@michaelkrupp,

> synchronize /temp/ to /dest/ using rsync

Let me put this again here:

> issue author (just like me) looks for solution which would template each file into target directory recursively 

I.e., I need to execute ansible template module at each file from src folder, but do that recursively and use same relative paths in dest folder as in src folder. So rsync (or Ansible rsync wrappers) won't help me.

I have my own solution right now:

```
  vars:
    src_dir: "/tmp/src"
    dst_dir: "/tmp/dst"
  tasks:
    - name: Get source directories relative paths
      shell: find "{{ src_dir }}/*" -type d | xargs -0 sh -c 'for filename; do prefix="{{ src_dir }}/" && echo "${filename#$prefix}"; done' arg
      register: directory_relative_paths

    - name: Create all destination directories needed because template module cannot create directories
      file: dest={{ dst_dir }}/{{ item }} state=directory
      with_items: directory_relative_paths.stdout_lines

    - name: Get source file relative paths
      shell: find "{{ src_dir }}" -type f | xargs sh -c 'for filename; do prefix="{{ src_dir }}/" && echo "${filename#$prefix}"; done' arg
      register: file_relative_paths

    - name: Template files recursively
      template: src="{{ src_dir }}/{{ item }}" dest="{{ dst_dir }}/{{ item }}"
      with_items: file_relative_paths.stdout_lines

It doesn't use temp folders.
But it is ugly because it executes shell commands (which is definitely non-Ansible way). Also it doesn't support Windows. Also it doesn't support spaces in directory names (but that could be fixed by rewriting shell commands).

Possibly, somebody knows how to solve this task in Ansible without running shell commands.
```
