### ISSUE TITLE
xml module: "ensure: present" command does not work poperly

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#28194]
_From @hammersoft on May 18, 2017 9:5_

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION
unknown

##### SUMMARY
Hi! 
I am using this xml

```xml
<?xml version='1.0' encoding='utf-8'?>
<tomcat-users>
    <role rolename="admin"/>
    <role rolename="admin-gui"/>
    <role rolename="admin-script"/>
    <role rolename="manager"/> 
</tomcat-users>
```

and next ansible task:
```yaml
- name: "Check selected roles"
  xml:
    path: "/etc/tomcat/tomcat-users.xml"
    xpath: "/tomcat-users/role[@rolename=\"{{ item }}\"]"
    pretty_print: True
    ensure: present
  with_items:
    - "manager"
    - "manager-script"
```
According to documentation 
> ensure:
>    description:
>      - Set or remove an xpath selection (node(s), attribute(s))

expecting to add node <role rolename="manager-script"/> into xml file. 
Task reporting all ok, but no new nodes added. 

With **ensure: absent** works fine: only specified node `<role rolename="manager"/>` is gone. 

Is this behaviour correct or this is error?

_Copied from original issue: cmprescott/ansible-xml#110_
