### ISSUE TITLE
"when:" conditionals not behaving as they suppose - different behaviour with/without {{}} when variable is set with "-e"

### ISSUE THREAD

**Issue by wvidana** [ansible/ansible#28191]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`when` conditionals
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 13 2017, 15:15:09) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

nothing special
##### OS / ENVIRONMENT

MacOS
##### SUMMARY

Different behaviour on `when:` if declaring with/without `{{}}`. if a variable is overriden on the command line with `-e`
##### STEPS TO REPRODUCE

Run this playbook changing `my_var` on the command line with `ansible-playbook -v my-playbook.yml -e my_var=False`

```yaml
---
- hosts: localhost

  vars:
    my_var: True

  tasks:
    - name: debug var
      debug:
        var: my_var

    - name: my task
      shell: echo hello wolrd
      when: my_var | default(True)

    - name: my task with mustaches
      shell: echo hello world mustaches
      when: "{{ my_var | default(True) }}"


```

##### EXPECTED RESULTS

Neither of the 2 tasks should run
##### ACTUAL RESULTS

```
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] *******************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************
ok: [localhost]

TASK [debug var] *******************************************************************************************************************************************
ok: [localhost] => {
    "my_var": false
}

TASK [my task] *********************************************************************************************************************************************
changed: [localhost] => {"changed": true, "cmd": "echo hello wolrd", "delta": "0:00:00.005378", "end": "2017-08-16 09:42:36.973496", "rc": 0, "start": "2017-08-16 09:42:36.968118", "stderr": "", "stderr_lines": [], "stdout": "hello wolrd", "stdout_lines": ["hello wolrd"]}

TASK [my task with mustaches] ******************************************************************************************************************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found: {{ my_var | default(True) }}

skipping: [localhost] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

PLAY RECAP *************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```
