### ISSUE TITLE
vsphere_guest : VM is created on an unexpected host 

### ISSUE THREAD

**Issue by osamu-shirota** [ansible/ansible#28211]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vsphere_guest.py

##### ANSIBLE VERSION

```
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

•RHEL 7.2
•VMware vSphere Enterprise Plus 6.0 
•ESXi6.2
•useing VMware cluster with DRS.

##### SUMMARY

When deploying a new VM from a template using the vsphere_guest module, the new VM created on the another esxi host that i did not specify as playbook.

##### STEPS TO REPRODUCE

```yaml
- name: Deploying VM on ESXI from template
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: no
    power_on_after_clone: no
    force: yes
    guest: "{{ inventory_hostname }}"
    from_template: yes
    cluster: "{{ cluster_name }}"
    template_src: "{{ template_name }}"
    vm_extra_config:
      vcpu.hotadd: yes
      mem.hotadd: yes
    esxi:
       datacenter: "{{ datacenter }}"
       hostname: "{{ esxi_ip_address }}"
```

##### EXPECTED RESULTS

I expect the VM deployed from template to be created on the esxi host that is specified by plyabook.

##### ACTUAL RESULTS

The VM was created on a esxi host that I did not expect

```

```
