### ISSUE TITLE
Play continues after a failed task when `any_errors_fatal` is set on other host

### ISSUE THREAD

**Issue by hmajid2301** [ansible/ansible#28222]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
NA

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
No Changes

##### OS / ENVIRONMENT

Linux- Centos 7

##### SUMMARY

Play continues after a failed task when any_errors_fatal is set. (almost same issue as https://github.com/ansible/ansible/issues/13744)

##### STEPS TO REPRODUCE

```bash
$ cat inv
app01
app02

$ ansible-playbook -i inv stop.yml
```

```yaml
---
- hosts: all
  any_errors_fatal: true
  max_fail_percentage: 0
  serial: 100%
  tasks:
    - name: "shell command failing on one node"
      shell: "test $(hostname --short) == app01"

    - name: stop before this
      command: echo noooooooo
```

##### EXPECTED RESULTS

expected playbook to finish and report back an error, not carry on running app01

##### ACTUAL RESULTS

```
$ ansible-playbook -i inv stop.yml

PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [app02]
ok: [app01]

TASK [shell command failing on one node] ***************************************
fatal: [app02]: FAILED! => {"changed": true, "cmd": "test $(hostname --short) == app01", "delta": "0:00:00.005278", "end": "2016-01-07 01:38:57.751466", "failed": true, "rc": 1, "start": "2016-01-07 01:38:57.746188", "stderr": "", "stdout": "", "stdout_lines": [], "warnings": []}
changed: [app01]

TASK [stop before this] ********************************************************
changed: [app01]

PLAY RECAP *********************************************************************
app01                      : ok=3    changed=2    unreachable=0    failed=0
app02                      : ok=1    changed=0    unreachable=0    failed=1
```
