### ISSUE TITLE
pamd broke /etc/pam.d/su file after task

### ISSUE THREAD

**Issue by ITD27M01** [ansible/ansible#28225]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pamd

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
But I use latest version from https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/pamd.py
##### CONFIGURATION

default
##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7.3
##### SUMMARY

pamd broke /etc/pam.d/su file after task
##### STEPS TO REPRODUCE

```yaml
  - name: Disable switch for domain users
    pamd:
      name: su
      type: auth
      control: sufficient
      module_path: pam_rootok.so
      new_type: auth
      new_control: required
      new_module_path: pam_succeed_if.so
      module_arguments: 'uid < 40000'
      state: before
```

##### EXPECTED RESULTS

Good /etc/pam.d/su file:
```
#%PAM-1.0
auth            required        pam_succeed_if.so uid < 40000
auth            sufficient      pam_rootok.so
# Uncomment the following line to implicitly trust users in the "wheel" group.
#auth           sufficient      pam_wheel.so trust use_uid
# Uncomment the following line to require a user to be in the "wheel" group.
#auth           required        pam_wheel.so use_uid
auth            substack        system-auth
auth            include         postlogin
account         sufficient      pam_succeed_if.so uid = 0 use_uid quiet
account         include         system-auth
password        include         system-auth
session         include         system-auth
session         include         postlogin
session         optional        pam_xauth.so
```
##### ACTUAL RESULTS

Bad /etc/pam.d/su file:

```
#%PAM-1.0
# Uncomment the following line to implicitly trust users in the "wheel" group.
#auth           sufficient      pam_wheel.so trust use_uid
# Uncomment the following line to require a user to be in the "wheel" group.
#auth           required        pam_wheel.so use_uid
auth            required        pam_succeed_if.so uid < 40000
auth            sufficient      pam_rootok.so
auth            substack        system -auth
auth            include postlogin

account         sufficient      pam_succeed_if.so uid = 0 use_uid quiet
account         include system -auth

password        include system -auth

session         include system -auth
session         include postlogin
session         optional        pam_xauth.so
```
Spaces in system-auth module name.
