### ISSUE TITLE
Tasks and/or plays should support a "become_pass" attribute

### ISSUE THREAD

**Issue by marvingreenberg** [ansible/ansible#28232]
##### ISSUE TYPE

 - New Feature

##### COMPONENT NAME
Privilege escalation/changing effective user

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /home/foo/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May  8 2017, 12:47:14) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
from:rhel6
to: mixed (w7,w10,centos6, centos7)
Mention the OS you are running Ansible from, and the OS you are
managing

##### SUMMARY
The capability to 'become' a different user is important when setting up modular reusable playbooks.  Because the desired effective user may be different for different plays, setting the become_user for the play or task is important, and is supported.   However, when using basic authentication approaches, the password for this account can only be provided via the global configuration via ansible_become_pass.

```
---
- hosts: windows
  tasks:
  - name: run some stuff in context of TestUser
    win_shell: 'do_some-complex_stuff.ps1'
    become: True
    become_user: TestUser

  - name: run some stuff in context of BuildUser
    win_shell: 'do_some-other_stuff.ps1'
    become: True
    become_user: BuildUser

```

This can work without prompting by setting ansible_become_pass in the inventory or group_vars.  But that requires the two user ids to have the same password.  Obviously in some configurations, this can be done without any requirement for a password (and ansible_become_pass is not required).  But for logical consistency, and since it is perfectly reasonable, plays and tasks should support setting become_pass, like:

```
---
- hosts: windows
  tasks:
  - name: run some stuff in context of TestUser
    win_shell: 'do_some-complex_stuff.ps1'
    become: True
    become_user: TestUser
    become_pass: {{ testuser_pass }}   # from group_vars/windows/vault.yml

  - name: run some stuff in context of BuildUser
    win_shell: 'do_some-other_stuff.ps1'
    become: True
    become_user: BuildUser
    become_pass: {{ builduser_pass }} # from group_vars/windows/vault.yml

```

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, you can already achieve this with `ansbile_become_pass` as you can set `vars:` at play or task level:

```
  - name: run some stuff in context of BuildUser
    win_shell: 'do_some-other_stuff.ps1'
    become: True
    become_user: BuildUser
    vars:
       ansible_become_pass: {{ builduser_pass }} # from group_vars/windows/vault.yml
```

We really don't encourage hardcoding passwords in plays, that is why the keyword is absent, but we also don't prevent it.


Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
