### ISSUE TITLE
'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'ansible_job_id'

### ISSUE THREAD

**Issue by bdmyxgh** [ansible/ansible#28230]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
ansible 2.3.2.0
  config file = /Users/mic/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] 

##### CONFIGURATION

[defaults]
host_key_checking = False
forks = 50

##### OS / ENVIRONMENT
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64

##### SUMMARY
I am trying to speedup the Azure VM creation, by using azure_rm_virtualmachine with async and poll. 

##### STEPS TO REPRODUCE

Here is my Playbook example:

**azure_bootstrap.yml**
```
---
- name: Create Resource group
  azure_rm_resourcegroup:
    name: "{{resource_group}}"
    location: "{{location}}"

- name: Create virtual network
  azure_rm_virtualnetwork:
    resource_group: "{{resource_group}}"
    name: "{{vnet}}-test"
    address_prefixes: "10.10.0.0/16"

- name: Add subnet
  azure_rm_subnet:
    resource_group: "{{resource_group}}"
    name: "{{subnet}}-test"
    address_prefix: "10.10.0.0/24"
    virtual_network: "{{vnet}}"

- name: Create public ip
  azure_rm_publicipaddress:
    resource_group: "{{resource_group}}"
    allocation_method: Static
    name: "{{item.key}}-ip"
  with_dict: "{{vms}}"
  async: 1000
  poll: 0
  register: azure

- name: Wait for IP's
  async_status: jid={{ item.ansible_job_id }}
  register: az_jobs
  until: az_jobs.finished
  retries: 300
  with_items: azure.results
```

**provision.yml**

```
- hosts: localhost
  vars:
    resource_group: testgroup
    vnet: testnet
    subnet: testsubnet
    location: westus
    sshkey: "xxxx"
    adminuser: "admin"
    vms:
      vm1:
        tags:
          role: test
      vm2:
        tags:
          role: test
      vm3:
        tags:
          role: test
  tasks:
    - include: azure_bootstrap.yml
```

The error I get when trying to run this playbook:

```
TASK [Wait for IP's] ****************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible.vars.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'ansible_job_id'\n\nThe error appears to have been in 'azure_bootstrap.yml': line 48, column 3, but may\nbe elsewhere in the file depending on the exact
 syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Wait for IP's\n  ^ here\n"}
        to retry, use: --limit @provision.yml.retry
```

Please advise.
> Sorry if it is not a bug - I was trying to as in IRC channel first, but got no answer..
