### ISSUE TITLE
vmware_guest state poweredon with template fails with error if VM already exists with same name

### ISSUE THREAD

**Issue by jmcginn13** [ansible/ansible#28250]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.4.0 (devel cde1b1b255) last updated 2017/08/07 09:38:49 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jmcginn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jmcginn/workspaces/ansible/ansible/lib/ansible
  executable location = /home/jmcginn/workspaces/ansible/ansible/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
Nothing but my vmware password

##### OS / ENVIRONMENT
Centos 7 and VSphere 5.5

##### SUMMARY
Running the same playbook that creates a VM and powers it on multiple times results in an error after the first time indicating a VM with that name already exists.

##### STEPS TO REPRODUCE
Running the following task more than once

```yaml
 - name: Create VM
      vmware_guest:
        hostname: "{{ hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        esxi_hostname: "xdl380chqtst01.railinc.com"
        datacenter: "{{ datacenter }}"
        folder: "/vm/mcginn"
        resource_pool: "{{ resource_pool }}"
        name: mcginn-test
        state: poweredon
        template: "mcginn-centos"
      register: new_vm
```

##### EXPECTED RESULTS
If the VM with the same name doesn't exist then the VM is created, if the VM does already exist, then the task ensures the VM is in the proper state and if it is reports no changes, if not it changes the VM into the new state

##### ACTUAL RESULTS
The following error is returned:
The name 'mcginn-test' already exists.

Note this error also appears in VSphere console, so this error is coming from VSphere

See [23663](https://github.com/ansible/ansible/issues/23663) - this appears to be broken in 2.4 now
