### ISSUE TITLE
ovirt_templates not overriding existing templates when exclusive is True

### ISSUE THREAD

**Issue by mordechai** [ansible/ansible#28275]
- Bug Report

##### COMPONENT NAME
ovirt_template module 
##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```

##### CONFIGURATION
n/a
##### OS / ENVIRONMENT
Fedora 25 and RHEL 7

##### SUMMARY
Assuming the ovirt enviroment already contains an existing template called "mytemplate".
Attempt to import "mytemplate" template with exclusive set to true.
```
 - ovirt_templates:
      auth: "{{ ovirt_auth }}"
      state: exported
      name: "mytemplate"
      export_domain: NFS
      storage_domain: SD1
      cluster: Default
      exclusive: True
      wait: True
```
Expecting that "mytemplate" will be overwritten when exclusive is set to True
The template is not overwritten.

##### STEPS TO REPRODUCE

1) Import Template "mytemplate"
2) execute code paste below [a]
3) Expecting 'mytemplate' to be overwritten it is not.

[a] Code Paste
```
 - ovirt_templates:
      auth: "{{ ovirt_auth }}"
      state: exported
      name: "mytemplate"
      export_domain: NFS
      storage_domain: SD1
      cluster: Default
      exclusive: True
      wait: True
```

##### EXPECTED RESULTS
Template to be overwritten

##### ACTUAL RESULTS
Template not overwritten
