### ISSUE TITLE
Please make the loop control easy and simple

### ISSUE THREAD

**Issue by maxmengtor** [ansible/ansible#28286]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
Is it possible to simple the loop_control and even remove it?
Easy way is to merge it into with_

Sample:

- name: "Sample of with_items"
  task:
  with_items: item_list as item

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by maxmengtor** [comment]
```yaml
- name: "Sample of with_items"
  task:
  with_items: item_list as any_you_want
```
and set the default as item if no "as item_name" provided
