### ISSUE TITLE
Can't use full Jinja2 templating in playbooks

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#283]
I'd like to do something like this:

```

---
- hosts: localhost
  vars:
    list: [1, 2, 3]
  tasks: 
  - name: Test $item
    action: command echo $item
    with_items:
    {% for item in list %}
    - {{ item }}
    {% endfor %}
```

But this gives a yaml ScannerError.

From reading the docs, I got the impression that playbooks were Jinja2 templates, but it seems templating is applied kind of ad-hoc.  For instance, there doesn't seem to be a way to display the results of templating a playbook, which makes debugging kind of difficult.

Would it be feasible to run entire playbooks though Jinja2, and then parse the result as YAML?
