### ISSUE TITLE
lineinfile module of ansible with delegate_to localhost doesn't write all data to localhost, it writes only 1 or 2  entries on localhost

### ISSUE THREAD

**Issue by sushilkumarsah** [ansible/ansible#28313]
- Bug Report

##### COMPONENT NAME, Ansible modules
lineinfile
delegate_to

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
no change in ansible.cfg, using the default ansible.cfg

##### OS / ENVIRONMENT

OS: RHEL 7.x
Tried on RHEL 7.2 VM with ansible 2.1.0.0
Tried on RHEL 7.3 docker container with ansible 2.3.1.0

##### SUMMARY
I have 3 remote VMs and 1 ansible node.

I am getting the hostname of those VMs by running hostname command on those remote VMs through ansible shell module and registering that output in hostname_output variable.

Then I want to add those VM's IP (collected using gather_facts: True, {{ ansible_default_ipv4.address }} ) with their hostname and append it to a file temp_hostname on localhost, hence I am delegating the task to localhost.

But the issue is, when I see on console, the lineinfile module says that line has been added when the module executed for each node and delegated to localhost, but when I check the file on the localhost, only 1 entry is shown on localhost instead of 3.

##### STEPS TO REPRODUCE
1. Have 3 VMs/nodes on which ansible can execute playbook's tasks
2. Execute the ansible-playbook attached in the bug report
3. Check the file generated on localhost

```yaml

**get_hostname.yml**
---
- name: get hostnames of dynamically created VMs
  hosts: all
  remote_user: "{{ remote_user }}"
  gather_facts: True

  tasks:
   - name: save hostname in variable, as this command is executed remotely, and we want the value on the ansible node
     shell: hostname
     register: hostname_output

   - name: writing hostname_output in ansible node in file on ansible node
     lineinfile:
      line: "{{ ansible_default_ipv4.address }} {{ hostname_output.stdout }}"
      dest: temp_hostname
      state: present
     delegate_to: 127.0.0.1



**hosts**
10.194.11.86 private_key_file=/root/.ssh/id_rsa
10.194.11.87 private_key_file=/root/.ssh/id_rsa
10.194.11.88 private_key_file=/root/.ssh/id_rsa


**command used to execute playbook:**

ansible-playbook -i hosts get_hostname.yml --ssh-extra-args="-o StrictHostKeyChecking=no" --extra-vars "remote_user=cloud-user" -vvv

```

I have raised this question on stackoverflow also:
https://stackoverflow.com/questions/45716225/lineinfile-module-of-ansible-with-delegate-to-localhost-doesnt-write-all-data-t

##### EXPECTED RESULTS
**cat temp_hostname**

10.194.11.86 hostname_of.86.com
10.194.11.87 hostname_of.87.com
10.194.11.88 hostname_of.88.com

##### ACTUAL RESULTS

```
sometimes only 1 entry is there in temp_hostname
sometimes 2 or 3 entries are there in temp_hostname

```

I get the expected result properly if I use the shell module with the redirection operator instead of lineinfile module as shown in below code
```yaml
---
- name: get hostnames of dynamically created VMs
  hosts: all
  remote_user: "{{ remote_user }}"
  gather_facts: True

  tasks:
   - name: save hostname in variable, as this command is executed remotely, and we want the value on the ansible node
     shell: hostname
     register: hostname_output

   - name: writing hostname_output in ansible node in file on ansible node
     shell: echo -e "{{ ansible_default_ipv4.address }} {{ hostname_output.stdout }}" >> temp_hostname
     delegate_to: 127.0.0.1
```

**Comment by dagwieers** [comment]
Concurrent write access to the same file is always going to be problematic, as they all read from the same file and then modify it. The solution here is to ensure no 2 tasks are running at the same time using `serial: 1`.

notabug

**Comment by sushilkumarsah** [comment]
Thank you for clarifying my mistake and giving the correct solution.

**Comment by dagwieers** [comment]
You're welcome !

**Comment by kvaps** [comment]
Same problem,
When I have a lot of hosts (100 for example), and this task:

      - name: Write nodes to config
        lineinfile:
          path: "/tmp/config.conf"
          regexp: 'host {{ inventory_hostname }}'
          line: "host {{ inventory_hostname }} something_else"
        delegate_to: myconfigserver
        notify:
        - Restart my server

Some hosts reports that changed, but line in file is not updated. (about 5~10 hosts)

Option `serial: 1` not aplicable for me, because this task have linked handler, and there is no way for call handler only one time, after all hosts will be added into config.

**Comment by dagwieers** [comment]
@kvaps So the question I have is what server needs to be restarted here ? Because I assume the notification handlers are for each target node, while you are modifying a single file on `myconfigserver`.

Not sure if this is what you expect.

**Comment by kvaps** [comment]
@dagwieers,
Yes, I need to restart daemon on `myconfigserver` after all changes in the config.

```
handlers:
  - name: Restart my server
    command: systemctl restart myservice
    run_once: true
    delegate_to: myconfigserver
```

There is also another option how it can be solved. Playbook can be splitted into two sections.
The first one will gather needed variables from hosts, and generate lines which should be added into config on `myconfigserver`.
The second one will dedicated to `myconfigserver` host only and will use, something liker that:
```
- name: Add moonshot nodes to DHCP
  hosts: myconfigserver
  gather_facts: no
  tasks:
    - lineinfile:
        path: "/tmp/config.conf"
        line: "{{ item }}"
      with_items:
        - "{{ hostvars | json_query('*.config_line_variable') }}"
```
Minus such a solution is that any time you should add `myconfigserver` host into `--limit` option. 
another word you can not do so:
```
./dhcp-add.yaml -l node1,node2,node3
```
every time you should add:
```
./dhcp-add.yaml -l mydhcpserver,node1,node2,node3
```
- this is not so problematic, as two more tasks each time when you want to update one config for multiple nodes, instead just using `delegate_to` option with `lineinfile` module together.

Thanks!
