### ISSUE TITLE
Ansible does not recognize jenkins_configure_proxy role

### ISSUE THREAD

**Issue by dzieciou** [ansible/ansible#28329]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

jenkins

##### ANSIBLE VERSION

```
ansible 2.4.0
  config file = None
  configured module search path = [u'/Users/mgawinec/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Sep 29 2016, 08:24:25) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

##### OS / ENVIRONMENT

MacOs 10.11.6

##### SUMMARY

Ansible does not recognize `jenkins_configure_proxy` role documented at http://ansible-jenkins-roles.readthedocs.io/en/latest/, but it recognize other roles documented there like `jenkins_plugin`.

##### STEPS TO REPRODUCE

Just run `ansible-playbook` on the following file:

```yaml
- hosts: master
  roles:
    - jenkins_configure_proxy:
      jenkins_home: "{{ jenkins_home }}"
      proxy_host: www.somehost.com
      proxy_port: 6060
      become: true
```

##### EXPECTED RESULTS

Proxy configured on Jenkins.

##### ACTUAL RESULTS

```
ERROR! role definitions must contain a role name

The error appears to have been in '/Users/mgawinec/projects/krakow-jenkins/jenkins.yml': line 10, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - jenkins_configure_proxy:
      ^ here

```
