### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ANSIBLE_SSH_CONTROL_PATH_DIR'

### ISSUE THREAD

**Issue by sdodson** [ansible/ansible#28330]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ssh connection plugin

##### ANSIBLE VERSION
```
ansible-2.3.1.0-3.el7.noarch
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### CONFIGURATION
host_key_checking = False
callback_whitelist = profile_tasks
ssh_args = -o ControlMaster=auto -o ControlPersist=600s
all others are default values, ANSIBLE_SSH_CONTROL_PATH_DIR is NOT set

##### OS / ENVIRONMENT
RHEL 7.3 on both control and target hosts

##### SUMMARY
During a long running playbook we randomly got the following. We're not setting this environment variable.

TASK [openshift_sanitize_inventory : Standardize on latest variable names] *****
Thursday 17 August 2017  11:19:18 +0000 (0:00:01.342)       13:32:56.348 ****** 
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'ANSIBLE_SSH_CONTROL_PATH_DIR'
fatal: [starter-us-west-2-node-compute-9e96b]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'ANSIBLE_SSH_CONTROL_PATH_DIR'
fatal: [starter-us-west-2-node-compute-93cf4]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'module' object has no attribute 'ANSIBLE_SSH_CONTROL_PATH_DIR'

This is the task
```
- name: Standardize on latest variable names
  set_fact:
    # goal is to deprecate deployment_type in favor of openshift_deployment_type.
    # both will be accepted for now, but code should refer to the new name.
    # TODO: once this is well-documented, add deprecation notice if using old name.
    deployment_type: "{{ openshift_deployment_type | default(deployment_type) | default | string }}"
    openshift_deployment_type: "{{ openshift_deployment_type | default(deployment_type) | default | string }}"
```
##### STEPS TO REPRODUCE
Unknown at this point, this happened during a long running playbook at approximately 6 hours in.
