### ISSUE TITLE
Network modules that use HTTPS don't work on IPv6-only hosts

### ISSUE THREAD

**Issue by dnmvisser** [ansible/ansible#28350]
I'm operating a number of Ubuntu 16.04 systems that **only** have a (public) IPv6 address.
In order to reach legacy IPv4 HTTP content they use a dual stack HTTP proxy.
This works fine when HTTP URLs are accessed:

```
  - name: Download file
    get_url:
      url:  http://downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-6.3.2.tar.gz 
      dest: /tmp/confluence.tar.gz
    environment:
      http_proxy: 'http://proxy.geant.org'

....

TASK [Download file] **************************************************************************************************************************************************************
changed: [okeanos41] => {"changed": true, "checksum_dest": null, "checksum_src": "aa73473d03920933c64eb4970864db0ac48f05e3", "dest": "/tmp/confluence.tar.gz", "gid": 0, "group": "root", "md5sum": "e73132cb8b1ed08e700b1fadcf13334f", "mode": "0644", "msg": "OK (536042205 bytes)", "owner": "root", "size": 536042205, "src": "/tmp/tmpp69mSF", "state": "file", "status_code": 200, "uid": 0, "url": "http://downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-6.3.2.tar.gz"}
```

But when I try HTTPS it fails:

```
  - name: Download Confluence
    get_url:
      url:  https://downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-6.3.2.tar.gz
      dest: /tmp/confluence.tar.gz
    environment:
      https_proxy: 'http://proxy.geant.org:3128'

....


TASK [Download file] **************************************************************************************************************************************************************
fatal: [okeanos41]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to connect to downloads.atlassian.com at port 443: [Errno 101] Network is unreachable"}
```

It seems to be caused by the `SSLValidationHandler()` class in `lib/ansible/module_utils/urls.py`, If I edit and change this section around line 706:

```
        try:
            s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
```

To:

```
        try:
            s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM)
```

Then things start to work for HTTPS as well:

```
TASK [Download file] **************************************************************************************************************************************************************
changed: [okeanos41] => {"changed": true, "checksum_dest": null, "checksum_src": "aa73473d03920933c64eb4970864db0ac48f05e3", "dest": "/tmp/confluence.tar.gz", "gid": 0, "group": "root", "md5sum": "e73132cb8b1ed08e700b1fadcf13334f", "mode": "0644", "msg": "OK (536042205 bytes)", "owner": "root", "size": 536042205, "src": "/tmp/tmp3P6UyB", "state": "file", "status_code": 200, "uid": 0, "url": "https://downloads.atlassian.com/software/confluence/downloads/atlassian-confluence-6.3.2.tar.gz"}
```

This is on MacOS 10.12.6 using homebrew's ansible:

```
 ansible --version
ansible 2.3.1.0
  config file = /Users/henk/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```
