### ISSUE TITLE
Using nmcli to change a network ifcfg file always results in "changed" status even if ifcfg file is not changed

### ISSUE THREAD

**Issue by leontp587** [ansible/ansible#28366]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION
No edits to ansible.cfg and ANSIBLE_* variables from defaults

##### OS / ENVIRONMENT
RedHat Enterprise Linux 7.2

##### SUMMARY
When using the nmcli module to edit a network ifcfg file (/etc/sysconfig/network-scripts/ifcfg-* files), the play status is always shown as changed, even if the ifcfg file is not changed. The changed status should be based on whether the ifcfg file has actually been changed by the nmcli module.

##### STEPS TO REPRODUCE
Inventory file

```yaml
- hosts: all
  tasks:
    - name: use nmcli to change ifcfg file
      nmcli:
        conn_name: eth0
        type: ethernet
        dns4: 8.8.8.8
        state: present
      register: nmcli_out

    - debug:
        var: nmcli_out
```

##### EXPECTED RESULTS
When the /etc/sysconfig/network-scripts/ifcfg-eth0 file has been added, or the dns entry added, then the play status should be "changed". Otherwise, the play status should not be changed.

##### ACTUAL RESULTS
The result is always "changed" even if the ifcfg-eth0 file is unchanged.

```

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [use nmcli to change ifcfg file] ******************************************
changed: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "nmcli_out": {
        "Exists": "Connections do exist so we are modifying them", 
        "changed": true, 
        "conn_name": "eth0", 
        "state": "present"
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   


```
