### ISSUE TITLE
'copy' and 'template' fail when sudo_user is not 'root' (in remote/push mode)

### ISSUE THREAD

**Issue by gildegoma** [ansible/ansible#2837]
```
- name:  Play with sudo_user != 'root'
  sudo: yes
  sudo_user: someone    # different from 'root' (and from 'remote_user' !)
  tasks:
    - name: COPY as NON-ROOT
      copy: src=dummy dest=/tmp/someone.dummy
```

The ssh-remote execution of this task fails

```
TASK: [COPY as NON-ROOT] ********************* 
failed: [192.168.111.222] => {"failed": true}
msg: Could not replace file: /tmp/ansible-1367617803.08-99078451783367/source 
to /tmp/someone.dummy: [Errno 13] Permission denied: 
'/tmp/ansible-1367617803.08-99078451783367/source'
```

because `sudo_user` needs write permission on /tmp/ansible-... temporary folder to move the file. `chmod a+rwx` is required in [`runner._make_tmp_path`](https://github.com/ansible/ansible/blob/a81089231e921b5067518065cf5de253ac4cbbc9/lib/ansible/runner/__init__.py#L666).

**Attention:** There is also a second (and worst) problem (after `chmod a+w` the temporary folder), because `sudo_user` cannot take ownership on /tmp/ansible-.../source file. The copied file is thus still owned by `remote_user` (who performed the file transfer).

After digging into the situation and history of these parts, I see so far two possible directions to solve that problem. I need your expert review to decide which direction to take (maybe not even one of both proposed below... :tada:)

**The Problem:** a normal user (`sudo_user`) has to _take ownership and move_ a file created by someone else (`remote user`). sudo_user is not root, but _can be_ a sudoer... but not necessarily!

**Central Questions:** 
- Should really `sudo_user` reuse the original file, or is it okay to take a copy of it ?
- in other words: Can we loosen from using `module_common.atomic_move` or not ? (read below to better understand why I ask...)

if 'atomic_move' must absolutely be used in any case, I would suggest following procedure (similar to #701):
- `chmod a+rwx` on `/tmp/ansible-...` temporary folder, to allow `sudo_user` to move the file from this location
- `sudo chown` the transferred file to `sudo_user`, to apply correct uid and gid

But such approach presents following tricky points:
- the primary group of `sudo_user` should be dynamically gathered
- if `remote_user` has not enough 'sudo' permissions to `chown` the file, the task must fail with an explicit error about that limitation...

Another possible way would consist in (basically) `shutil.copy2` the source file, instead of `atomic_move` it (from `lib/ansible/module_common.py`). `sudo_user` thus creates a new file with correct ownership (and umask?), without tricky sudo-in-the-middle described above. This second variant sounds quite more elegant in my opinion. 

With my little understanding, I feel that `atomic_move` is not strictly required (either for performance or security reasons). But maybe I'm quite wrong... please pardon if I missed obvious things! Anyway, we could still rely on `atomic_move` in all other situations (no sudo, sudo_user is root), and make this "trick" conditional.

Thank you in advance for review and comments :-)

So far, I have some ~working patches for both variants, but I preferred to avoid to create messy pull request. That's why I first open bug report without code attached (hoping not losing too much bonus points ;-). When the direction to take is confirmed, I'll try my best to provide a decent pull request ([hub](https://github.com/defunkt/hub) conversion of this github issue?).

Related issues and discussions (for the records):
- #700 (similar issue when sudo_user to non-root was introduced. `/tmp` was enough by this time... I guess (atomic) move was not yet introduced (not verified in details)
- #1018 (Attention: code is not yet DRY between 'copy' and 'template' action plugins)

Below, I pasted a small playbook example that can be used to reproduce this problem (it also illustrate how you can work around it, with ansible code unchanged)

```
- name:  Play with sudo_user == 'root'
  hosts: test-host
  sudo: yes

  tasks:
    - name: Create Someone
      user: name=someone state=present

    - name: COPY as ROOT
      copy: src=dummy dest=/tmp/root.dummy owner=someone group=someone
      tags: as-root

- name:  Play with user == someone (sudo_user not used)
  hosts: test-host
  user: someone

  tasks:
    # TODO: add a task to add public key to someone...

    - name: "COPY as NON-ROOT - Workaround: Remote SSH connection directly with 'someone' (no more 'sudo_user')"
      copy: src=dummy dest=/tmp/ssh-workaround.dummy
      tags: ssh-workaround

- name:  Play with sudo_user != 'root'
  hosts: test-host
  sudo: yes
  sudo_user: someone    # different from 'root' (and from 'remote_user' !)

  tasks:
    - name: "COPY as NON-ROOT - Workaround: sudo to root and set owner and group"
      copy: src=dummy dest=/tmp/sudo-workaround.dummy owner=someone group=someone
      tags: sudo-workaround
      sudo_user: root

    ##
    # Failing Tasks because of permission problem between 'transferred files' 
    # (owned by remote_user) and 'atomic move' (performed by sudo_user):
    #  - sudo_user needs write permission on /tmp/ansible-... temporary folder
    #  - sudo_user cannot take ownership on /tmp/ansible-.../source file
    ##

    - name: COPY ERROR - /tmp/ansible-.../source owned by 'remote_user'
      copy: src=dummy dest=/tmp/someone.dummy
      tags: copy-error

    - name: TEMPLATE ERROR - /tmp/ansible-.../source owned by'remote_user'
      copy: src=dummy.j2 dest=/tmp/someone-template.dummy
      tags: template-error
```
