### ISSUE TITLE
Unable to set up A record round robin with dnsmadeeasy

### ISSUE THREAD

**Issue by msl-kabo** [ansible/ansible#28386]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
dnsmadeeasy

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### CONFIGURATION
Standard

##### OS / ENVIRONMENT
Running Ansible on Debian Stretch

##### SUMMARY
I'd like to set up a round robin configuration, as done in [this tutorial](http://help.dnsmadeeasy.com/managed-dns/records/round-robin/), using ansible and the dnsmadeeasy module.

##### STEPS TO REPRODUCE
If the variable `ips` is a list with two IP addresses

This first creates one record, then replaces it with the next record
```yaml
    - dnsmadeeasy:
        account_key: "{{dns_account_key}}"
        account_secret: "{{dns_account_secret}}"
        state: present
        domain: "{{domainname}}"
        record_name: ""
        record_type: A
        record_ttl: 60
        record_value: "{{item}}"
      with_items: "{{ips}}"
```

This gives a 400 error
```yaml
    - dnsmadeeasy:
        account_key: "{{dns_account_key}}"
        account_secret: "{{dns_account_secret}}"
        state: present
        domain: "{{domainname}}"
        record_name: ""
        record_type: A
        record_ttl: 60
        record_value: "{{ips}}"
```

##### EXPECTED RESULTS
I expected to end up with two A records for my domain, pointing to the two IPs.

##### ACTUAL RESULTS
I end up with one A record pointing to the last IP in the list.

Checking the code it looks to me like `A` and `AAAA` records should be checked in the same manner as `MX` records.
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/dnsmadeeasy.py#L474

**Comment by ansibot** [comment]
cc @briceburg
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by briceburg** [comment]
@kabo thanks -- you're correct. I want to make sure that this is tested for non-round-robin domains as well. Did you try your patch against a domain where a single record is the expected return?

**Comment by kabo** [comment]
Yup, setting a single domain works as well. There are differences compared to the current behaviour though.

Let's say the domain `a.com` currently has an A record pointing to `1.1.1.1`. If you run this play with my patch:

```yaml
- dnsmadeeasy:
    account_key: key
    account_secret: secret
    domain: a.com
    state: present
    record_name: ""
    record_type: A
    record_value: 1.1.1.2
```

you'll end up with two A records, one pointing to `1.1.1.1`, and one pointing to `1.1.1.2`. The current behaviour is to replace the A record.

If you want to remove an A record without my patch you could do:

```yaml
- dnsmadeeasy:
    account_key: key
    account_secret: secret
    domain: a.com
    state: absent
    record_name: ""
    record_type: A
```

but after my patch you'd have to specify the value as well, i.e.:

```yaml
- dnsmadeeasy:
    account_key: key
    account_secret: secret
    domain: a.com
    state: absent
    record_name: ""
    record_type: A
    record_value: 1.1.1.1
```

So in order to replace the A record for `a.com` pointing to `1.1.1.1` with an A record pointing to `1.1.1.2` after my patch you'd have to:

```yaml
- dnsmadeeasy:
    account_key: key
    account_secret: secret
    domain: a.com
    state: present # first create the new record
    record_name: ""
    record_type: A
    record_value: 1.1.1.2
- dnsmadeeasy:
    account_key: key
    account_secret: secret
    domain: a.com
    state: absent # then remove the old record
    record_name: ""
    record_type: A
    record_value: 1.1.1.1
```

I find this the expected behaviour, the current behaviour was quite unexpected to me.
