### ISSUE TITLE
win_reboot does not wait for OS updates to finish installing/confguring after reboot

### ISSUE THREAD

**Issue by Pantharian** [ansible/ansible#28389]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_reboot

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```
##### OS / ENVIRONMENT
Any Windows OS (v10 or later)

##### SUMMARY
Having rebooted the machine following OS updates (patches/security fixes etc) using win_reboot, Ansible resumes processing the playbook even though the OS updates have not completed.

This is OK for some operations: e.g. disk access, reading/writing to the registry, but not for example, starting/stopping services.

##### STEPS TO REPRODUCE
Create a playbook that applies the latest patch/security fixes, does a win_reboot, and then runs additional commands after that reboot. The playbook resumes playing before the Windows updates have completed. 

##### EXPECTED RESULTS
To wait until the Windows OS has completed its update process BEFORE resuming playbook.

##### ACTUAL RESULTS
The Windows machines reports that it is configuring Windows, but the playbook continues and errors because an action cannot be completed because Windows is not ready.

```
TASK [win_config : Restart Service] ****************************
task path: /home/jenkins/workspace/windows/roles/win_config/tasks/win_restart_service.yml:6
<19.20.56.18> ESTABLISH WINRM CONNECTION FOR USER: **** on PORT 5986 TO 19.20.56.18
EXEC (via pipeline wrapper)
fatal: [windows]: FAILED! => {
    "changed": true, 
    "failed": true, 
    "rc": 1, 
    "stderr": "#< CLIXML\r\nrestart-service : Service cannot be started due to the following error: \r\nCannot start service on computer '.'.\r\nAt line:1 char:1\r\n+ restart-service \r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Restart-Service] \r\n   , ServiceCommandException\r\n    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.RestartServiceCommand\r\n \r\n\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>", 
    "stdout": "", 
    "stdout_lines": []
}
	to retry, use: --limit @/home/jenkins/workspace/windows/vsgpust_prod.retry


PLAY RECAP *********************************************************************
windows                    : ok=52   changed=37   unreachable=0    failed=1   
```

Presumably what is happening is that WinRM becomes available before Windows has completed its installation and configuration of its updates and then Ansible resumes playing the playbook even though the Windows machine is not really ready (as some services, for example, may not have started).

Ansible should wait until it is possible to login to the machine rather than just assuming that because WinRM is ready that the machine is ready to accept Ansible commands,

**Comment by ansibot** [comment]
cc @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@Pantharian Good call, I guess we have to find a way to ask Windows when the system is really ready to be used again. Or we could add a special condition to check for in **win_wait_for**. https://github.com/ansible/ansible/pull/26556

The main question is whether this should be standard behavior from **win_reboot**, or is this something specific we expect the user to take into account (so explained in **win_update** and/or **win_reboot**) and either as a parameter to **win_reboot** or required by the user to add **win_wait_for**.

BTW I can imagine **win_wait_for** has some special Windows event-related functionality to wait for.

**Comment by dagwieers** [comment]
So a possible workaround would be to use the `post_reboot_delay` option of **win_reboot**. Unfortunately, that patch has not been accepted yet. https://github.com/ansible/ansible/pull/22178

Maybe I should single those features out so that the new functionality can be merged. (And now I did: https://github.com/ansible/ansible/pull/28448)

@nitzmahone Do you agree ? Can https://github.com/ansible/ansible/pull/28448 be merged for v2.4 ?

**Comment by jborean93** [comment]
Now that https://github.com/ansible/ansible/pull/28448 is merged, the best way to avoid this is to use the `post_reboot_delay` option that was added. Unfortunately I am unaware of a way to detect if Windows is still configuring updates after the initial reboot. I've raised a a question with MS over this here https://social.msdn.microsoft.com/Forums/en-US/ddad5597-b03d-4f9c-931c-71f1b692f71f/how-to-wait-for-windows-update-to-be-finished-on-reboot-remotely?forum=wcf but so far I haven't gotten anything conclusive that would help.

**Comment by Pantharian** [comment]
For how long does one set `post_boot_delay`: 10 secs, 600 secs, 1800 secs? Whatever value is chosen could be too short or too long as the amount of time required will depend on the number of updates and how fast the machine is running which can vary on virtual machine platforms depending on load. Therefore, it is not possible to 'guess' or even gauge how long to set the delay as there is no way to estimate how long it will take the machine to be ready. So not sure that this option is going to help very much,

**Comment by jborean93** [comment]
Yea that's unfortunately the issue and makes this a pretty poort workaround. I've got the same problem with creating a role that installed all windows updates from a base image and come across this. I found 2 minutes was a good time to use so far but it would really depend on the environment. Unfortunately unless we can get more info from MS around detecting whether Windows is in this particular mode there is not too much we can do.

**Comment by ansibot** [comment]
cc @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by BenMitchell1979** [comment]
I see 'post_reboot_delay" has been introduced in 2.4 - but I get the following error when calling it.
```
TASK [include_tasks] *****************************************************************************************************************************************************************************************
 [WARNING]: Ignoring invalid attribute: post_reboot_delay

included: /Users/163131/Projects/cis-base-image-windows/ansible/update.yml for xxx.xxx.xxx.xxx
```

Block containing reboot:
```yaml
- name: Check for Updates
  win_updates: state=searched
  register: update_count

# Apply pending updates
- name: Running Windows Update
  win_updates:
    category_names:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
  register: result

# reboot only if required
- win_reboot:
  when: 
    - result.reboot_required is defined
    - result.reboot_required
    - update_count.found_update_count|int >= 1
  post_reboot_delay: 180
```

**Comment by jhawkesworth** [comment]
@BenMitchell1979 post_reboot_delay is a module parameter so you need to indent it (and I think put it before the 'when' action directive), like this:

```yaml
# reboot only if required
- win_reboot:
    post_reboot_delay: 180
  when: 
    - result.reboot_required is defined
    - result.reboot_required
    - update_count.found_update_count|int >= 1
```

**Comment by jborean93** [comment]
For anyone following along here, until changes occur within Ansible itself to better handle this, I have found the following 3 tasks can be run to ensure Windows is rebooted and handle subsequent reboots in the case of Windows Updates.

```yaml
- name: reboot server
  win_reboot:
    reboot_timeout: 1200

- name: check if the Windows Update process is busy
  win_shell: (New-Object -ComObject Microsoft.Update.Session).CreateUpdateInstaller().IsBusy
  become: yes
  become_user: SYSTEM
  ignore_errors: yes

- name: make sure connection is back online before continuing
  wait_for_connection:
```

It works by extending the timeout of the reboot timer as it can take some time for Windows to actually install the updates. Once it is back online Ansible will then call a specific method of WUA where it checks if it is busy or not. While the value returns as `false` regardless it does give the benefit of waiting for WUA to be free (updates are installed) before returning. Finally we have one last `wait_for_connection` in case the server is rebooted and it will wait until it is finally back online.

This uses some features added in 2.5 so it only will work under the devel version but it is at least something. I've been using these 3 tasks successfully to install all Windows updates on a base image where this issue is a regular problem and it should work for most Windows Update cases.

**Comment by BenMitchell1979** [comment]
@jborean93 

I'm getting the following error when Checking for WUS (I'm guessing it's because of Become_User: SYSTEM).. 

fatal: [10.49.128.157]: FAILED! => {"failed": true, "msg": "Internal Error: this connection module does not support running commands via sudo"}
...ignoring

**Comment by BenMitchell1979** [comment]
@jborean93 - I keep getting the following error on Check for WUA. 
```
TASK [Check if WUS is available.] *************************************************************************************************************************************
fatal: [10.49.128.132]: FAILED! => {"failed": true, "msg": "Internal Error: this connection module does not support running commands via sudo"}
...ignoring
```
Is this the step that requires 2.5 devel version ?

**Comment by jborean93** [comment]
@BenMitchell1979, if you want to become the SYSTEM account then yes 2.5 is required otherwise it can be done with 2.4 and an administrator account. You would have to add the `become_method: runas` task arg to tell Ansible to use the runas become method required by windows.

**Comment by BenMitchell1979** [comment]
@jborean93 - Thanks mate! 

Would I still need to use 'become_method' if I'm hitting WinRM with Local Administrator?

**Comment by jborean93** [comment]
If you want to use become, Ansible needs to know which become method to use, the default I believe is `sudo`. For Windows the only become method that is supported is `runas` and so it needs to be set for become on Windows to work. The easier way is to set `become_method: runas` on either the task or playbook level but you can also set `ansible_become_method: runas` on your hostvars.

**Comment by BenMitchell1979** [comment]
@jborean93 - After upgrading to v2.5 - still getting the same error when running the following play:

```yaml
- name: Check if WUS is available.
  win_shell: (New-Object -ComObject Microsoft.Update.Session).CreateUpdateInstaller().IsBusy
  become: yes
  become_user: SYSTEM
  ignore_errors: yes

```
```
Output: 
TASK [Check if WUS is available.] *****************************************************************************
fatal: [10.49.128.146]: FAILED! => {"failed": true, "msg": "Internal Error: this connection module does not support running commands via sudo"}
...ignoring
```

Any help on this would be greatly appreciated :D

**Comment by jborean93** [comment]
@BenMitchell1979 you still need to add `become_method: runas` to the task arts so in the end it will look like this

```yaml
- win_shell: ...
  become: yes
  become_method: runas
  become_user: SYSTEM
  ignore_errors: yes
```

You can also set it under the var `ansible_become_method: runas` for the host if you don’t want to specify it for each become task you do but that’s up to you.
