### ISSUE TITLE
win_updates does not update windows server

### ISSUE THREAD

**Issue by tar7** [ansible/ansible#28385]
ISSUE TYPE
Bug Report

COMPONENT NAME
Module: win_update

ANSIBLE VERSION

``ansible 2.3.1.0``

OS / ENVIRONMENT
Ansible is running on linux server: Ubuntu 16.04.2 LTS
Connected to windows server 2012 r2 datacenter

SUMMARY
Ansible fails to update windows server using the windows module: win_updates. In ansible it shows ok but when i check my server, Most recent check for updates was not when i tried to update using ansible. No updates were installed.

```yaml
---
- name: Install Updates
  hosts: PBIPRDSVR01
  gather_facts: true
  tasks:
  - win_updates:
        category_names: ['SecurityUpdates','CriticalUpdates','UpdateRollups']

The result:
PLAY [Install Updates] *********************************************************

TASK [Gathering Facts] *********************************************************
ok: [172.xx.xx.xxx]

TASK [win_updates] *************************************************************
ok: [172.xx.xx.xxx]

PLAY RECAP *********************************************************************
172.xx.xx.xxx              : ok=2    changed=0    unreachable=0    failed=0



```

EXPECTED RESULTS

Should be able to update windows server

ACTUAL RESULTS

Does not update windows server

```

```
