### ISSUE TITLE
eos_user module does not give error when nopassword is not given and does not create new user

### ISSUE THREAD

**Issue by rkandilarov** [ansible/ansible#28388]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- eos_user

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/ansible-manager/config/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

Default configuration

##### OS / ENVIRONMENT

```
lsb_release -a
```
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.3 LTS
> Release:        16.04
> Codename:       xenial

##### SUMMARY

When running task for creating user with eos_user without providing explicitly *nopassword* the user is not created and there is no error. If trying to add nonexisting user with ssh key eos_user will fail... 
I cannot say if this is really a bug or not a proper usage of eos_user from my side. I was thinking that *state: present* is instructive.
 
##### STEPS TO REPRODUCE

Run the following playbook:

```yaml
---
- name: Fake user to be added for the test
  hosts: test-arista-sw
  gather_facts: no
  connection: local

  tasks:
  - name: 1 This task WILL NOT ADD user but WILL NOT provide any error
    eos_user:
      username: testme
      state: present
      provider: "{{ ans_provider }}"

  - name: 2 This task WILL rise missing user error
    eos_user:
      username: testme
      state: present
      sshkey: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      provider: "{{ ans_provider }}"
    ignore_errors: yes

  - name: 3 This task WILL ADD user finally because nopassword is explicitly set
    eos_user:
      username: testme
      state: present
      nopassword: yes
      provider: "{{ ans_provider }}"

  vars:
    ans_provider:
      host: "{{ ansible_host }}"
      username: administrator
      password: testtest
      authorize: yes
      transport: cli
      port: 22
```

##### EXPECTED RESULTS

I expect that:
- Task 1 will add user or warn/error me that the user is not added
- Task 2 will add user with key and no password
- Task 3 is as expected :)

##### ACTUAL RESULTS

```
PLAY [Fake user to be added for the test] *******************************************************************************************************************

TASK [1 This task WILL NOT ADD user but will not provide any error] *****************************************************************************************
ok: [test-arista-sw]

TASK [2 This task WILL rise missing user error] *************************************************************************************************************
fatal: [test-arista-sw]: FAILED! => {
    "changed": false, 
    "commands": [
        "username testme sshkey ssh-rsa AAAA........CeHY/v ansible-manager@orch-manager-ansible"
    ], 
    "failed": true
}

MSG:

szFw9vSxL9...........Y/v ansible-manager@orch-manager-ansible
% User not present
localhost(config-s-ansibl)#

...ignoring

TASK [3 This task WILL ADD user finally because nopassword is explicitly set] *******************************************************************************
changed: [test-arista-sw]

PLAY RECAP **************************************************************************************************************************************************
test-arista-sw             : ok=3    changed=1    unreachable=0    failed=0   
```
##### COMMANDS THAT HAVE BEEN RUN ON ARISTA
- Task 1: 
```
terminal length 0
terminal width 512
enable
show running-config section username
```
- Task 2: 
```
terminal length 0
terminal width 512
enable
show running-config section username
show clock
show configuration sessions
configure session ansible_150305661
username testme sshkey * * *
abort
```
- Task 3: 
```
terminal length 0
terminal width 512
enable
show running-config section username
show clock
show configuration sessions
configure session ansible_1503056675
username testme nopassword
show session-config diffs
commit
```
