### ISSUE TITLE
azure_rm_virtualmachine does not clean up after itself when it fails on an error in Azure

### ISSUE THREAD

**Issue by elaurijssens** [ansible/ansible#28392]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

##### SUMMARY
azure_rm_virtualmachine throws an error, __NameError: global name 'VirtualMachineSizeTypes' is not defined__, although the requirements in the documentation ) python >=2.7, azure==2.0.0rc5 are met. 

##### STEPS TO REPRODUCE
Installed ansible, pywinrm, pyvmomi, azure==2.0.0rc5 
(pyvmomi is included for the sake of completeness, we use Ansible for VMware as well)

```
---
- name: Start the template creation process (from scratch)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cloud_type: "{{ cloud_envs[cloud].type }}"

  tasks:
    - name: Create Azure VM with Ansible
      azure_rm_virtualmachine:
        admin_username: "{{ base_templates[cloud_type][template].admin_user }}"
        admin_password: "{{ base_templates[cloud_type][template].admin_password }}"
        client_id: "{{ cloud_envs[cloud].client_id }}"
        image:
          publisher: "{{ base_templates[cloud_type][template].image_publisher }}"
          offer: "{{ base_templates[cloud_type][template].image_offer }}"
          sku: "{{ base_templates[cloud_type][template].image_sku }}"
          version: latest
        location: "{{ base_templates[cloud_type][template].location }}"
        name: "w2016-stage1"
        os_type: "{{ base_templates[cloud_type][template].os_type }}"
        resource_group: "{{ cloud_envs[cloud].resource_group_name }}"
        secret: "{{ cloud_envs[cloud].client_secret }}"
        state: present
        storage_account_name: "{{ cloud_envs[cloud].storage_account }}"
        virtual_network_name: voyager-templates
        subscription_id: "{{ cloud_envs[cloud].subscription_id }}"
        tenant: "{{ cloud_envs[cloud].tenant_id }}"
        vm_size: "{{ base_templates[cloud_type][template].vm_size }}"

```
(of course, with all variables substituted with meaningful values)

##### EXPECTED RESULTS
- with a machine name longer than 15 characters, the module fails right away
- when any non-predictible azure error is encountered, for instance deploying the VM means quota are exceeded, the module fails, but before exiting it cleans up any unnecessary resources it created in the meantime.

##### ACTUAL RESULTS
the module just fails, leaving behind a lot of artefacts that aren't needed anymore.
