### ISSUE TITLE
Assignment of uri response to a variable

### ISSUE THREAD

**Issue by rajnkamr** [ansible/ansible#28390]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.1.0.0
```

##### SUMMARY

I assign the response of login in register based on some condition and later need to use same login response in subsequent section.
Again i will login and get the response  and use in subsequent section.
Is there any way to do it. Currently I am getting error.
If i use one login and response it works fine.
##### STEPS TO REPRODUCE

```yaml

- name: Login 
  uri:
    url: "http://{{connection_ip}}:5000/vse/api/v1.0/login/"
    method: POST
    return_content: yes
    HEADER_Content-Type: "application/json"
    body: "{{ login }}"
    body_format: json
  #register: old_login_resp
  when: connection_ip == '0.0.0.0'
  register: json_resp

- set_fact: login_resp=json_resp
  when: connection_ip == '0.0.0.0'

- debug: var=login_resp


- name: 2nd login with different ip
  uri:
    url: "http://{{connection_ip}}:5000/vse/api/v1.0/login/"
    method: POST
    return_content: yes
    HEADER_Content-Type: "application/json"
    body: "{{ connector_login }}"
    body_format: json
  register: connector_login_resp
  when: connection_ip == "{{connector_login.ipaddr}}"

- set_fact: login_resp=connector_login_resp
  when: connection_ip == "{{connector_nid.ipaddr}}"

- name: Get the  type using REST API  
  uri:
    url: "http://{{connection_ip}}:5000/vse/api/v1.0/info"
    method: GET
    return_content: yes
    HEADER_x-auth-token: "{{ login_resp.json.token }}"
    HEADER_Content-Type: "application/json"
  register: info_resp

```

##### EXPECTED RESULTS

I want to use same variable name login response login_resp in subsequent calls
##### ACTUAL RESULTS

fatal: [0.0.0.0]: FAILED! => {"failed": true, "msg": "'unicode object' has no attribute 'json'"}

```

```
