### ISSUE TITLE
azure_rm_virtualmachine - NameError: global name 'VirtualMachineSizeTypes' is not defined

### ISSUE THREAD

**Issue by elaurijssens** [ansible/ansible#28391]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)

##### SUMMARY
azure_rm_virtualmachine throws an error, __NameError: global name 'VirtualMachineSizeTypes' is not defined__, although the requirements in the documentation ) python >=2.7, azure==2.0.0rc5 are met. 

##### STEPS TO REPRODUCE
Installed ansible, pywinrm, pyvmomi, azure==2.0.0rc5 
(pyvmomi is included for the sake of completeness, we use Ansible for VMware as well)

```
---
- name: Start the template creation process (from scratch)
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    cloud_type: "{{ cloud_envs[cloud].type }}"

  tasks:
    - name: Create Azure VM with Ansible
      azure_rm_virtualmachine:
        admin_username: "{{ base_templates[cloud_type][template].admin_user }}"
        admin_password: "{{ base_templates[cloud_type][template].admin_password }}"
        client_id: "{{ cloud_envs[cloud].client_id }}"
        image:
          publisher: "{{ base_templates[cloud_type][template].image_publisher }}"
          offer: "{{ base_templates[cloud_type][template].image_offer }}"
          sku: "{{ base_templates[cloud_type][template].image_sku }}"
          version: latest
        location: "{{ base_templates[cloud_type][template].location }}"
        name: "w2016-stage1"
        os_type: "{{ base_templates[cloud_type][template].os_type }}"
        resource_group: "{{ cloud_envs[cloud].resource_group_name }}"
        secret: "{{ cloud_envs[cloud].client_secret }}"
        state: present
        storage_account_name: "{{ cloud_envs[cloud].storage_account }}"
        virtual_network_name: voyager-templates
        subscription_id: "{{ cloud_envs[cloud].subscription_id }}"
        tenant: "{{ cloud_envs[cloud].tenant_id }}"
        vm_size: "{{ base_templates[cloud_type][template].vm_size }}"

```
(of course, with all variables substituted with meaningful values)

##### EXPECTED RESULTS

Ansible starts deploying the specified VM on Azure

##### ACTUAL RESULTS

```
TASK [Create Azure VM with Ansible] **************************************************************************************************************************************************************************
task path: /root/playbooks/playbook.yml:11
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_virtualmachine.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1503058954.92-34620927571165 `" && echo ansible-tmp-1503058954.92-34620927571165="` echo /root/.ansible/tmp/ansible-tmp-1503058954.92-34620927571165 `" ) && sleep 0'
<localhost> PUT /tmp/tmpLW7GFe TO /root/.ansible/tmp/ansible-tmp-1503058954.92-34620927571165/azure_rm_virtualmachine.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1503058954.92-34620927571165/ /root/.ansible/tmp/ansible-tmp-1503058954.92-34620927571165/azure_rm_virtualmachine.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1503058954.92-34620927571165/azure_rm_virtualmachine.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1503058954.92-34620927571165/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_4yxhl0/ansible_module_azure_rm_virtualmachine.py", line 1309, in <module>
    main()
  File "/tmp/ansible_4yxhl0/ansible_module_azure_rm_virtualmachine.py", line 1306, in main
    AzureRMVirtualMachine()
  File "/tmp/ansible_4yxhl0/ansible_module_azure_rm_virtualmachine.py", line 513, in __init__
    for key in VirtualMachineSizeTypes:
NameError: global name 'VirtualMachineSizeTypes' is not defined

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_4yxhl0/ansible_module_azure_rm_virtualmachine.py\", line 1309, in <module>\n    main()\n  File \"/tmp/ansible_4yxhl0/ansible_module_azure_rm_virtualmachine.py\", line 1306, in main\n    AzureRMVirtualMachine()\n  File \"/tmp/ansible_4yxhl0/ansible_module_azure_rm_virtualmachine.py\", line 513, in __init__\n    for key in VirtualMachineSizeTypes:\nNameError: global name 'VirtualMachineSizeTypes' is not defined\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
	to retry, use: --limit @/root/playbooks/playbook.retry

PLAY RECAP ***************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

The error goes away when I install msrestazure 0.4.11. However, the list of Azure VM types/sizes is quite outdated. Depending on this static list seems a bit useless anyway as the available VM types in Azure vary by datacenter location.
