### ISSUE TITLE
vars_prompt fires even if no hosts matched for a play

### ISSUE THREAD

**Issue by akamac** [ansible/ansible#28408]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
playbook, vars_prompt

##### ANSIBLE VERSION
ansible 2.3.1.0
  config file = /home/amiasoedov/ansible/playbooks/linux/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
- hosts: no_hosts
  vars_prompt:
    - name: varname
      prompt: fired
```

##### EXPECTED RESULTS
the play is skipped with no var prompts

##### ACTUAL RESULTS
I'm asked for input
