### ISSUE TITLE
nxos_bgp_neighbor_af advertise-map properties are not idempotent

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#28412]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nxos_bgp_neighbor_af

##### NXOS VERSION
7.0(3)I5(3)

##### ANSIBLE VERSION
```
ansible 2.4.0 (rel140/fix_nxos_bgp_neighbor_af 8ff4dbfc10) last updated 2017/08/18 14:03:16 (GMT -400)
  config file = None
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT
macOS

##### SUMMARY
The blank properties are not idempotent.

The following playbook can be used to demonstrate the problem

##### STEPS TO REPRODUCE
```yaml
---
- debug: msg="START TRANSPORT:{{ connection.transport }} nxos_bgp_neighbor_af sanity test"

- name: "Disable feature BGP"
  nxos_feature: &disable_bgp
    feature: bgp
    state: disabled
    provider: "{{ connection }}"
  ignore_errors: yes

- name: "Enable feature BGP"
  nxos_feature:
    feature: bgp
    state: enabled
    provider: "{{ connection }}"
  ignore_errors: yes

- block:
  - name: "Configure BGP neighbor address-family defaults"
    nxos_bgp_neighbor_af: &configure_default
      asn: 65535
      neighbor: '3.3.3.3'
      afi: ipv4
      safi: unicast
      additional_paths_receive: 'inherit'
      additional_paths_send: 'inherit'
      advertise_map_exist: 'default'
      # -----------------------------------------------
      # advertise_map_exist and advertise_map_non_exist
      # are mutually exclusive
      #advertise_map_non_exist: 'default'
      # -----------------------------------------------
      allowas_in: 'false'
      allowas_in_max: 'default'
      as_override: 'false'
      default_originate: 'false'
      default_originate_route_map: 'default'
      filter_list_in: 'default'
      filter_list_out: 'default'
      # ------------------------------------------
      # max_prefix* properities are off by default
      max_prefix_limit: 'default'
      # For the default case, only max_prefix_limit
      # is set.  The rest should be left unset.
      #max_prefix_interval: 'default'
      #max_prefix_threshold: 'default'
      #max_prefix_warning: 'false'
      # ------------------------------------------
      next_hop_self: 'false'
      next_hop_third_party: 'true'
      prefix_list_in: 'default'
      prefix_list_out: 'default'
      route_map_in: 'default'
      route_map_out: 'default'
      route_reflector_client: 'false'
      send_community: 'default'
      soft_reconfiguration_in: 'inherit'
      suppress_inactive: 'false'
      unsuppress_map: 'default'
      weight: 'default'
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Check Idempotence"
    nxos_bgp_neighbor_af: *configure_default
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: "Setup: Remove BGP config"
    nxos_bgp: &remove
      asn: 65535
      state: absent
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: "Check Idempotence"
    nxos_bgp: *remove
    register: result

  - assert: *false

  - name: "Configure eBGP setting remote_as 2 prior to non-defaults test"
    nxos_bgp_neighbor:
      asn: 65535
      vrf: 'blue'
      neighbor: '3.3.3.3'
      remote_as: 2
      provider: "{{ connection }}"

  - name: "Configure BGP neighbor non-defaults"
    nxos_bgp_neighbor_af: &configure_non_default
      asn: 65535
      vrf: 'blue'
      neighbor: '3.3.3.3'
      afi: ipv4
      safi: unicast
      additional_paths_receive: 'enable'
      additional_paths_send: 'disable'
      advertise_map_non_exist: ['ansible_rm', 'my_non_exist_map']
      # -----------------------------------------------
      # advertise_map_exist and advertise_map_non_exist
      # are mutually exclusive
      #advertise_map_exist: 'my_map'
      # -----------------------------------------------
      allowas_in: 'true'
      allowas_in_max: '5'
      as_override: 'true'
      default_originate: 'true'
      default_originate_route_map: 'my_route_map'
      filter_list_in: 'my_filter_list_in'
      filter_list_out: 'my_filter_list_out'
      max_prefix_limit: 100
      # max_prefix_interval and max_prefix_warning
      # are mutually exclusive.
      max_prefix_interval: 30
      max_prefix_threshold: 50
      #max_prefix_warning: 'true'
      next_hop_self: 'true'
      next_hop_third_party: 'false'
      prefix_list_in: 'pfx_in'
      prefix_list_out: 'pfx_out'
      route_map_in: 'rm_in'
      route_map_out: 'rm_out'
      send_community: 'extended'
      soft_reconfiguration_in: 'enable'
      soo: '3:3'
      suppress_inactive: 'true'
      unsuppress_map: 'unsup_map'
      weight: '30'
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: "Check Idempotence"
    nxos_bgp_neighbor_af: *configure_non_default
    register: result

  - assert: *false

  - name: "Remove BGP"
    nxos_bgp: *remove
    register: result

  - assert: *true

  - name: "Configure BGP neighbor af route_reflector_client"
    nxos_bgp_neighbor:
      asn: 65535
      neighbor: '2.2.2.2'
      remote_as: 65535
      provider: "{{ connection }}"

  - name: "Configure BGP neighbor af route_reflector_client"
    nxos_bgp_neighbor_af: &configure_rr_client
      asn: 65535
      neighbor: '2.2.2.2'
      afi: ipv4
      safi: unicast
      route_reflector_client: 'true'
      #advertise_map_non_exist: ['ansible_rm', 'my_non_exist_map']
      # -----------------------------------------------
      # advertise_map_exist and advertise_map_non_exist
      # are mutually exclusive
      advertise_map_exist: ['ansible_rm', 'my_exist_map']
      # -----------------------------------------------
      # max_prefix_interval and max_prefix_warning
      # are mutually exclusive. Add testing for
      # warning since interval is tested above.
      max_prefix_limit: 100
      #max_prefix_interval: 30
      max_prefix_threshold: 50
      max_prefix_warning: 'true'
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: "Check Idempotence"
    nxos_bgp_neighbor_af: *configure_rr_client
    register: result

  - assert: *false

  always:
  - name: "Cleanup BGP"
    nxos_bgp: *remove
    ignore_errors: yes

  - name: "Disable feature bgp"
    nxos_feature: *disable_bgp

  - debug: msg="END TRANSPORT:{{ connection.transport }} nxos_bgp_neighbor_af sanity test"

```

```shell
TASK [nxos_bgp_neighbor_af : Configure BGP neighbor non-defaults] ******************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_bgp_neighbor_af/tests/common/sanity.yaml:100
<n9k.example.comm> connection transport is cli
<n9k.example.comm> using connection plugin network_cli
<n9k.example.comm> socket_path: /Users/mwiebe/.ansible/pc/30512dd245
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_bgp_neighbor_af.py
<n9k.example.comm> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k.example.comm> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k.example.comm> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079797.3-205195575388820 `" && echo ansible-tmp-1503079797.3-205195575388820="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079797.3-205195575388820 `" ) && sleep 0'
<n9k.example.comm> PUT /var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/tmphMrgDV TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079797.3-205195575388820/nxos_bgp_neighbor_af.py
<n9k.example.comm> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079797.3-205195575388820/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079797.3-205195575388820/nxos_bgp_neighbor_af.py && sleep 0'
<n9k.example.comm> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079797.3-205195575388820/nxos_bgp_neighbor_af.py; rm -rf "/Users/mwiebe/.ansible/tmp/ansible-tmp-1503079797.3-205195575388820/" > /dev/null 2>&1 && sleep 0'
changed: [n9k.example.comm] => {
    "changed": true, 
    "commands": [
        "router bgp 65535", 
        "vrf blue", 
        "neighbor 3.3.3.3", 
        "address-family ipv4 unicast", 
        "weight 30", 
        "filter-list my_filter_list_out out", 
        "soo 3:3", 
        "capability additional-paths receive", 
        "advertise-map ansible_rm non-exist my_non_exist_map", 
        "default-originate", 
        "suppress-inactive", 
        "no next-hop-third-party", 
        "allowas-in 5", 
        "maximum-prefix 100 50 restart 30", 
        "route-map rm_in in", 
        "next-hop-self", 
        "send-community extended", 
        "prefix-list pfx_in in", 
        "as-override", 
        "unsuppress-map unsup_map", 
        "filter-list my_filter_list_in in", 
        "default-originate route-map my_route_map", 
        "route-map rm_out out", 
        "capability additional-paths send disable", 
        "soft-reconfiguration inbound", 
        "prefix-list pfx_out out"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "additional_paths_receive": "enable", 
            "additional_paths_send": "disable", 
            "advertise_map_exist": null, 
            "advertise_map_non_exist": [
                "ansible_rm", 
                "my_non_exist_map"
            ], 
            "afi": "ipv4", 
            "allowas_in": true, 
            "allowas_in_max": "5", 
            "as_override": true, 
            "asn": "65535", 
            "default_originate": true, 
            "default_originate_route_map": "my_route_map", 
            "filter_list_in": "my_filter_list_in", 
            "filter_list_out": "my_filter_list_out", 
            "host": null, 
            "max_prefix_interval": "30", 
            "max_prefix_limit": "100", 
            "max_prefix_threshold": "50", 
            "max_prefix_warning": null, 
            "neighbor": "3.3.3.3", 
            "next_hop_self": true, 
            "next_hop_third_party": false, 
            "password": null, 
            "port": null, 
            "prefix_list_in": "pfx_in", 
            "prefix_list_out": "pfx_out", 
            "provider": null, 
            "route_map_in": "rm_in", 
            "route_map_out": "rm_out", 
            "route_reflector_client": null, 
            "safi": "unicast", 
            "send_community": "extended", 
            "soft_reconfiguration_in": "enable", 
            "soo": "3:3", 
            "ssh_keyfile": null, 
            "state": "present", 
            "suppress_inactive": true, 
            "timeout": null, 
            "transport": "cli", 
            "unsuppress_map": "unsup_map", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null, 
            "vrf": "blue", 
            "weight": "30"
        }
    }
}

TASK [nxos_bgp_neighbor_af : assert] ***********************************************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_bgp_neighbor_af/tests/common/sanity.yaml:144
ok: [n9k.example.comm] => {
    "changed": false, 
    "failed": false, 
    "msg": "All assertions passed"
}

TASK [nxos_bgp_neighbor_af : Check Idempotence] ************************************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_bgp_neighbor_af/tests/common/sanity.yaml:146
<n9k.example.comm> connection transport is cli
<n9k.example.comm> using connection plugin network_cli
<n9k.example.comm> socket_path: /Users/mwiebe/.ansible/pc/30512dd245
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_bgp_neighbor_af.py
<n9k.example.comm> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k.example.comm> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k.example.comm> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079803.39-91430409778796 `" && echo ansible-tmp-1503079803.39-91430409778796="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079803.39-91430409778796 `" ) && sleep 0'
<n9k.example.comm> PUT /var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/tmpFbLPaw TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079803.39-91430409778796/nxos_bgp_neighbor_af.py
<n9k.example.comm> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079803.39-91430409778796/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079803.39-91430409778796/nxos_bgp_neighbor_af.py && sleep 0'
<n9k.example.comm> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1503079803.39-91430409778796/nxos_bgp_neighbor_af.py; rm -rf "/Users/mwiebe/.ansible/tmp/ansible-tmp-1503079803.39-91430409778796/" > /dev/null 2>&1 && sleep 0'
changed: [n9k.example.comm] => {
    "changed": true, 
    "commands": [
        "router bgp 65535", 
        "vrf blue", 
        "neighbor 3.3.3.3", 
        "address-family ipv4 unicast", 
        "advertise-map ansible_rm non-exist my_non_exist_map"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "additional_paths_receive": "enable", 
            "additional_paths_send": "disable", 
            "advertise_map_exist": null, 
            "advertise_map_non_exist": [
                "ansible_rm", 
                "my_non_exist_map"
            ], 
            "afi": "ipv4", 
            "allowas_in": true, 
            "allowas_in_max": "5", 
            "as_override": true, 
            "asn": "65535", 
            "default_originate": true, 
            "default_originate_route_map": "my_route_map", 
            "filter_list_in": "my_filter_list_in", 
            "filter_list_out": "my_filter_list_out", 
            "host": null, 
            "max_prefix_interval": "30", 
            "max_prefix_limit": "100", 
            "max_prefix_threshold": "50", 
            "max_prefix_warning": null, 
            "neighbor": "3.3.3.3", 
            "next_hop_self": true, 
            "next_hop_third_party": false, 
            "password": null, 
            "port": null, 
            "prefix_list_in": "pfx_in", 
            "prefix_list_out": "pfx_out", 
            "provider": null, 
            "route_map_in": "rm_in", 
            "route_map_out": "rm_out", 
            "route_reflector_client": null, 
            "safi": "unicast", 
            "send_community": "extended", 
            "soft_reconfiguration_in": "enable", 
            "soo": "3:3", 
            "ssh_keyfile": null, 
            "state": "present", 
            "suppress_inactive": true, 
            "timeout": null, 
            "transport": "cli", 
            "unsuppress_map": "unsup_map", 
            "use_ssl": null, 
            "username": null, 
            "validate_certs": null, 
            "vrf": "blue", 
            "weight": "30"
        }
    }
}

TASK [nxos_bgp_neighbor_af : assert] ***********************************************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_bgp_neighbor_af/tests/common/sanity.yaml:150
fatal: [n9k.example.comm]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

```
