### ISSUE TITLE
YAML filter is generating invalid list output

### ISSUE THREAD

**Issue by bcdonadio** [ansible/ansible#28427]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

jinja2 yaml filter

##### ANSIBLE VERSION

The bug is reproducible both from the current devel branch just as the 2.3.1.0 release.
```
ansible 2.4.0 (devel 688823014f) last updated 2017/08/18 22:48:42 (GMT -200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/bcdonadio/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/bcdonadio/ansible/lib/ansible
  executable location = /home/bcdonadio/ansible/bin/ansible
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### CONFIGURATION

All configs are default.

##### OS / ENVIRONMENT

Both Fedora 26 and RHEL7.4.

##### SUMMARY

The YAML parser is generating invalid YAML lists with wrong indentation.

##### STEPS TO REPRODUCE

Playbook content:
```yaml
---
- name: reproduce yaml bug
  hosts: all
  tasks:
    - name: proccess template
      template:
        src: template.yml.j2
        dest: /tmp/template.yml
  vars:
    somevar:
      insidevar1:
        - someList: "value"
          anotherOption: "value"
      insidevar2:
        - anotherList: "value"
          anotherOption: "value"
```

The `template.yml.j2` content is:
```
{{ somevar | to_nice_yaml }}
```

A tarball that contain those files to easen reproduction may be found here: https://bcdonadio.com/res/yamlbug.tar.xz

##### EXPECTED RESULTS

The result of the `/tmp/template.yml` file should be:
```yaml
insidevar1:
  - anotherOption: value
    someList: value
insidevar2:
  - anotherList: value
    anotherOption: value
```

##### ACTUAL RESULTS

The result of `/tmp/template.yml` actually is:
```yaml
insidevar1:
-   anotherOption: value
    someList: value
insidevar2:
-   anotherList: value
    anotherOption: value
```

**Comment by nrwahl2** [comment]
For what it's worth, this behavior is coming directly from Python's `yaml` module. I'm not sure how feasible it's going to be to get the type of customization you're wanting at the Ansible layer.

From c:/plugins/filter/core.py:
```
def to_nice_yaml(a, indent=4, *args, **kw):
    '''Make verbose, human readable yaml'''
    transformed = yaml.dump(a, Dumper=AnsibleDumper, indent=indent, allow_unicode=True, default_flow_style=False, **kw)
    return to_text(transformed)
```

Interpreter session using simple call of `yaml.dump` for illustration:
```
>>> print yaml.dump(my_dict, indent=4, default_flow_style=False)
insidevar1:
-   anotherOption: value
    someList: value
insidevar2:
-   anotherList: value
    anotherOption: value
```

**Comment by bcdonadio** [comment]
> I'm not sure how feasible it's going to be to get the type of customization you're wanting

But is this a customization? I mean, is the actual output valid YAML while having more than one space after the dash?

According to http://www.yamllint.com/, it seems to be valid. According to https://codebeautify.org/yaml-validator, it is not.

I just tried to yaml.load() the actual output and it worked. I'm unsure if should I report it upstream.

**Comment by bcdonadio** [comment]
Even stranger is if we use this input:
```yaml
    somevar:
      insidevar1:
        - someList: "value"
          anotherOption:
            - "AValue"
            - "moreValues"
      insidevar2:
        - anotherList: "value"
          anotherOption: "value"
```

Which generates this strange output:
```yaml
insidevar1:
-   anotherOption:
    - AValue
    - moreValues
    someList: value
insidevar2:
-   anotherList: value
    anotherOption: value
```
According to http://www.yamllint.com/, this output is also valid. It really seems to be?
