### ISSUE TITLE
Documentation and example for win_user, state: query 

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#28431]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

win_user

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel de16ce42ef) last updated 2017/08/18 17:08:29 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### SUMMARY

Document returned result from a state: query play

##### STEPS TO REPRODUCE

```yaml
- name: query for old accounts
  win_user:
    name: "{{ item }}"
    state: query
  with_items:
    - "BobTanner"
```

##### EXPECTED RESULTS

No sure what to expect. It's not documented :-) 

##### ACTUAL RESULTS

```yaml
     "msg": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "changed": false,
                "failed": false,
                "item": {
                    "name": "BobTanner"
                },
                "msg": "User 'BobTanner' was not found",
                "name": "BobTanner",
                "state": "absent"
            }
        ]
    }
```

**Comment by ansibot** [comment]
@basictheprogram Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- ansible version

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @angstwad @cchurch @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
Looks like you get a message saying the user wasn't found!

By the way, you can create documentation pull requests directly on the github page for the module documentation here:
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_user.py

**Comment by jhawkesworth** [comment]
For info, here's what I get when a user is/isn't found:
```yaml
DESK10 | SUCCESS => {
    "account_disabled": false,
    "account_locked": false,
    "changed": false,
    "description": "",
    "fullname": "J Hawkesworth",
    "groups": [
        {
            "name": "Administrators",
            "path": "WinNT://WORKGROUP/DESK10/Administrators"
        }
    ],
    "name": "jon",
    "password_expired": false,
    "password_never_expires": true,
    "path": "WinNT://WORKGROUP/DESK10/jon",
    "sid": "S-1-5-21-3322259488-2828151810-3939402796-1001",
    "state": "present",
    "user_cannot_change_password": false
}

jon@DESK10:~/ansible_testing$ ansible SPEECH -m win_user -a"name=joan state=query"
DESK10 | SUCCESS => {
    "changed": false,
    "msg": "User 'joan' was not found",
    "name": "joan",
    "state": "absent"
}
```
