### ISSUE TITLE
postgresql_user & become_user fails

### ISSUE THREAD

**Issue by matonb** [ansible/ansible#28433]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### OS / ENVIRONMENT
CentOS 7.3 - CentOS 7.3

##### STEPS TO REPRODUCE

```yaml
---
- name: "Create foreman PostgreSQL user"
  become:      true
  become_user: postgres
  postgresql_user:
    name:            foreman
    password:        "{{foreman_db_password}}"
    role_attr_flags: LOGIN,NOSUPERUSER,NOCREATEDB,NOCREATEUSER
```

##### EXPECTED RESULTS
PostgreSQL user foreman created

##### ACTUAL RESULTS
Doesn't become postgres user and fails to connect to database

```
TASK [linux/postgresql : Create foreman PostgreSQL user] ***********************
fatal: [testlab004]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database: FATAL:  Peer authentication failed for user \"postgres\"\n"}
```

PostgreSQL server log:
```
< 2017-08-19 10:00:46.657 BST > LOG:  provided user name (postgres) and authenticated user name (root) do not match
< 2017-08-19 10:00:46.657 BST > FATAL:  Peer authentication failed for user "postgres"
```
