### ISSUE TITLE
vmware_guest without MAC address gather facts error

### ISSUE THREAD

**Issue by tmarlok88** [ansible/ansible#28471]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT
"N/A"

##### SUMMARY
If the guest vm has no MAC address assigned to it (prior the first boot, th e MAC is empty), the guest module is unable to start the vm. The problem lies in the module_utils/vmware.py in the gather_vm_facts function (line 247). The error is:
```
AttributeError: 'NoneType' object has no attribute 'replace'
```
I made the following workaround to make it work:
```python
        macaddress_dash = ''
        if entry.macAddress:
            macaddress_dash = entry.macAddress.replace(':', '-' )

        factname = 'hw_eth' + str(ethernet_idx)
        facts[factname] = {
            'addresstype': entry.addressType,
            'label': entry.deviceInfo.label,
            'macaddress': entry.macAddress,
            'ipaddresses': net_dict.get(entry.macAddress, None),
            'macaddress_dash': macaddress_dash,
            'summary': entry.deviceInfo.summary,
        }

```

##### STEPS TO REPRODUCE
First the assigned MAC address should be removed from the VM. Then one can try to start the vm with the folloving task:

```yaml
- name: start the guest vm
  vmware_guest:
    hostname: "{{ansible_hos] }}"
    username: "{{esxi_admin_user}}"
    password: "{{esxi_admin_password}}"
    validate_certs: no
    name: "{{ inventory_hostname }}"
    wait_for_ip_address: yes
    state: poweredon
```
