### ISSUE TITLE
Increase duplicated key overriding warning verbosity

### ISSUE THREAD

**Issue by yajo** [ansible/ansible#28470]
##### ISSUE TYPE

 - ~B ug Report~
- Feature Idea

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When running a playbook that has a yaml anchor in a task and it is used in a subsequent task that overrides some of the original keys, with no verbosity specified, the user gets ugly warnings.

##### STEPS TO REPRODUCE

Among some other tasks, I have these:

```yaml
- &iamuserupdate
  name: create present bucket iam users
  with_subelements:
    - "{{ s3_buckets }}"
    - users
  when:
    - item.0.state|default('present') != 'absent'
  iam:
    <<: *aws_access
    name: "{{ item.1 }}"
    iam_type: user
    state: "{{ item.0.state|default('present') }}"

# Other tasks, not relevant

- <<: *iamuserupdate
  name: delete absent bucket iam users
  when:
    - item.0.state|default('present') == 'absent'
```

##### EXPECTED RESULTS

I don't want to get those ugly warnings for doing something that I did on purpose and expected it to happen: overriding a task definition on some keys that already existed in the previous task.

##### ACTUAL RESULTS

```
 [WARNING]: While constructing a mapping from /path/roles/aws-
manager/tasks/setup.yaml, line 147, column 3, found a duplicate dict key (name). Using last defined value only.

 [WARNING]: While constructing a mapping from /path/roles/aws-
manager/tasks/setup.yaml, line 147, column 3, found a duplicate dict key (when). Using last defined value only.
```

Those warnings are OK, but only in `-v` mode at least.
