### ISSUE TITLE
Ansible's `yum` module should support checksum checking when `name` points to a url

### ISSUE THREAD

**Issue by wildefires** [ansible/ansible#28481]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
yum

##### OS / ENVIRONMENT

CentOS/RHEL Linux

##### SUMMARY
Currently the `yum` module has no functionality for handling checksums (according to https://docs.ansible.com/ansible/latest/yum_module.html). Thus, if you want to check that a downloaded RPM has the expected checksum you need to break it into a `get_url` and then a `yum` to install from the downloaded artifact

##### STEPS TO REPRODUCE

Currently:
```yaml
- name: Get RPM
  get_url:
    url: https://centos7.iuscommunity.org/ius-release.rpm
    checksum: "md5:insertmd5sumhere"
    dest: /tmp/ius-release.rpm

- name: Install downloaded rpm
   yum:
      name: /tmp/ius-release.rpm
      state: present
```

Proposed:

```yaml
- name: get and install RPM
  yum:
    url: https://centos7.iuscommunity.org/ius-release.rpm
    checksum: "md5:insertmd5sumhere"
    state: present
```
