### ISSUE TITLE
pamd fails when inserting a new rule at the end of a file

### ISSUE THREAD

**Issue by davidkretch** [ansible/ansible#28487]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pamd

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

Also affects 2.4:
```
ansible 2.4.0 (devel beed59f303) last updated 2017/08/19 20:29:45 (GMT -400)
  config file = None
  configured module search path = [u'/home/david/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/david/ansible/lib/ansible
  executable location = /home/david/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

In the pamd module, when you try to insert a new rule after the last rule in a file, it crashes with a list index error.

##### STEPS TO REPRODUCE

```yaml
---
- name: pamd bug example
  hosts: localhost
  connection: local
  become: yes
  tasks:
  - pamd:
      name: common-session
      type: session
      control: optional
      module_path: pam_systemd.so
      new_type: session
      new_control: optional
      new_module_path: pam_mkhomedir.so
      state: after
...
```

Given the following /etc/pam.d/common-session (the Ubuntu 16.04 default, not including comments):
```
session [default=1]                     pam_permit.so
session requisite                       pam_deny.so
session required                        pam_permit.so
session optional                        pam_umask.so
session required        pam_unix.so
session optional        pam_systemd.so
```

##### EXPECTED RESULTS

/etc/pam.d/common-session with last line 
```
session optional        pam_mkhomedir.so
```

##### ACTUAL RESULTS

```
TASK [pamd] ********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "error running changing pamd: list index out of range"}
        to retry, use: --limit @/home/ubuntu/pamd.retry
```
