### ISSUE TITLE
haproxy module: Ansible should get backends which has specified host first

### ISSUE THREAD

**Issue by iredmail** [ansible/ansible#28507]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
haproxy module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT
macOS 10.12.6

##### SUMMARY

Code used to put a haproxy node to offline:

```
      - name: "Mark host {{ host }} as OFFLINE."
        haproxy:
            state: disabled
            host: "{{ host }}"
            shutdown_sessions: yes
            fail_on_not_found: no
```

##### EXPECTED RESULTS

Ansible should send command `show servers state` to haproxy socket to get a list of backends which has the given host, then put `<backend>/<host>` to offline.

##### ACTUAL RESULTS

Ansible failed if one backend doesn't contain specified host.
