### ISSUE TITLE
filesystem - Idempotence broken with XFS and `resizefs`

### ISSUE THREAD

**Issue by zigarn** [ansible/ansible#28514]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Module filesystem

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Apr  9 2015, 11:03:32) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

RHEL7

##### SUMMARY

In the [filesystem](http://docs.ansible.com/ansible/latest/filesystem_module.html) module, `resizefs` is documented with a note:
> Note, XFS Will only grow if mounted.

But there is another bad effect: if the FS is not mounted, calling the module twice will fail with this error:
```
fatal: [localhost]: FAILED! => {"changed": false, "err": "xfs_info: /dev/sdc is not a mounted XFS filesystem\n", "failed": true, "msg": "Failed to get block count and block size of /dev/sdc with /sbin/xfs_info", "rc": 1}
```

It happened for me when the playbook failed for some reason between the filesystem creation and the mounting of the FS: when relaunching the playbook it failed.

It's because `resizefs`, ansible is trying to get the current FS size using `xfs_info`, but `xfs_info` (or `xfs_grow` in last version of the module) doesn't works on not mounted FS.  
It's OK for failing if a resize is necessary on an unmounted xfs FS, but it should fail if no resize is required.  
It could be better to use another way to get the FS size that does not require a mounted FS.

##### STEPS TO REPRODUCE

```yaml
# playbooks.yml
---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
    - name: create fs
      filesystem:
        fstype: xfs
        dev: /dev/sdc
        resizefs: yes
    - name: create fs again (simulate a relaunch without mounting the FS)
      filesystem:
        fstype: xfs
        dev: /dev/sdc
        resizefs: yes
```

##### EXPECTED RESULTS

```
TASK [create fs] ****************************************************************************
changed: [localhost]

TASK [create fs again (simulate a relaunch without mounting the FS)] ************************
ok: [localhost]
```

##### ACTUAL RESULTS

```
TASK [create fs] ****************************************************************************
changed: [localhost]

TASK [create fs again (simulate a relaunch without mounting the FS)] ************************
fatal: [localhost]: FAILED! => {"changed": false, "err": "xfs_info: /dev/sdc is not a mounted XFS filesystem\n", "failed": true, "msg": "Failed to get block count and block size of /dev/sdc with /sbin/xfs_info", "rc": 1}
```
