### ISSUE TITLE
(P1) nxos_igmp_interface: module errors out for cli 

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#28516]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_igmp_interface

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel b3a90253fc) last updated 2017/08/22 10:29:18 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04

##### SUMMARY

Module errors with traceback for `cli`

##### STEPS TO REPRODUCE

```yaml
- name: "Enable feature PIM"
  nxos_feature:
    feature: pim
    state: enabled
    provider: "{{ connection }}"
  ignore_errors: yes

- block:

  - name: put interface in L3 and enable PIM
    nxos_config:
      commands:
        - no switchport
        - ip pim sparse-mode
      parents:
        - "interface {{ intname }}"
      match: none
      provider: "{{ connection }}"

  - name: Configure igmp interface with default value
    nxos_igmp_interface: &default
      interface: "{{ intname }}"
      state: default
      provider: "{{ connection }}"
```

##### EXPECTED RESULTS

Expected module to not error out

##### ACTUAL RESULTS

module errors out with tracebacks

```
TASK [nxos_igmp_interface : Configure igmp interface with default value] **********************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_igmp_interface/tests/common/sanity.yaml:26
<n9k-xxx.example.com> connection transport is cli
<n9k-xxx.example.com> using connection plugin network_cli
<n9k-xxx.example.com> socket_path: /root/.ansible/pc/3747b7341f
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_igmp_interface.py
<n9k-xxx.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n9k-xxx.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k-xxx.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1503412190.68-270476304915912 `" && echo ansible-tmp-1503412190.68-270476304915912="` echo /root/.ansible/tmp/ansible-tmp-1503412190.68-270476304915912 `" ) && sleep 0'
<n9k-xxx.example.com> PUT /tmp/tmpDBeP34 TO /root/.ansible/tmp/ansible-tmp-1503412190.68-270476304915912/nxos_igmp_interface.py
<n9k-xxx.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1503412190.68-270476304915912/ /root/.ansible/tmp/ansible-tmp-1503412190.68-270476304915912/nxos_igmp_interface.py && sleep 0'
<n9k-xxx.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1503412190.68-270476304915912/nxos_igmp_interface.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1503412190.68-270476304915912/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_5eYN_h/ansible_module_nxos_igmp_interface.py", line 697, in <module>
    main()
  File "/tmp/ansible_5eYN_h/ansible_module_nxos_igmp_interface.py", line 558, in main
    if get_interface_mode(interface, intf_type, module) == 'layer2':
  File "/tmp/ansible_5eYN_h/ansible_module_nxos_igmp_interface.py", line 263, in get_interface_mode
    interface_table = body['TABLE_interface']['ROW_interface'] 
TypeError: string indices must be integers, not str 
FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_5eYN_h/ansible_module_nxos_igmp_interface.py\", line 697, in <module>\n    main()\n  File \"/tmp/ansible_5eYN_h/ansible_module_nxos_igmp_interface.py\", line 558, in main\n    if get_interface_mode(interface, intf_type, module) == 'layer2':\n  File \"/tmp/ansible_5eYN_h/ansible_module_nxos_igmp_interface.py\", line 263, in get_interface_mode\n    interface_table = body['TABLE_interface']['ROW_interface']\nTypeError: string indices must be integers, not str\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
