### ISSUE TITLE
proxmox_kvm: cloning a vm should return new vmid

### ISSUE THREAD

**Issue by nleof** [ansible/ansible#28517]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`modules/cloud/misc/proxmox_kvm.py`

##### ANSIBLE VERSION
```
ansible --version
ansible 2.3.0.0
  config file = /Users/alx/dev/ulule/deployment/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jun 21 2017, 17:05:40) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### SUMMARY
When cloning a vm, proxmox_kvm should return new vmid

##### EXPECTED RESULTS

```yaml
- name: clone vm
  proxmox_kvm:
    name: "lalala"
    node: "mynode"

    clone: "vmtoclone"
    full: yes

  register: proxmox

# proxmox should contains new vmid
```

Like that:

```json
{
"msg": "VM lalala with newid 101 cloned from vm with vmid 100",
"vmid": 101
}
```

##### ACTUAL RESULTS
Now, we have:
```json
{
"msg": "VM lalala with newid 101 cloned from vm with vmid 100"
}
```

##### Quick fix

At https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/proxmox_kvm.py#L1147

Add `**{'vmid': newid}` at the end.

**Comment by ansibot** [comment]
cc @helldorado
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kevinlong206** [comment]
@nleof - just a user here, not a contributor. I'm wondering if this is just so you can start the newly created VM, and if thats the case, can you just it with just the name (not the VMID?) thats how it is with the 'proxmox' module (which creates lxc, not kvm), and the 'hostname' parameter. (but I agree it would be nice to have the VMID in the register)

**Comment by nleof** [comment]
Yes, I could do that but I need the vmid for the `qm` command.
So I would need to start, wait and stop to fetch the vmid.
It's feasible but as we have the information directly after clone, we should use it.
It's more convenient.

Anyway thanks for your idea, I'll keep it in mind o/

**Comment by erikschwalbe** [comment]
There is a section "return values" in the official documentation:
https://docs.ansible.com/ansible/latest/proxmox_kvm_module.html#return-values
How can I use this values? Or is it not implemented yet?

**Comment by nleof** [comment]
It's implemented but only when `state: present` & `update: False` & `clone: False`.
You can access these values with a `register`.

**Comment by helldorado** [comment]
@erikschwalbe here is an short example.

The first task create the host on proxmox node and return values like the `mac` address in the register `qemu`.

In second task we loop over the register `qemu` with the real `mac` and `vmid` returned by the module to create host on foreman. 

```yaml
- name: Manage VM state (absent|current|present|restarted|started|stopped).
  local_action:
    module: proxmox_kvm
    api_user     : "{{ item.proxmox.api_user|default('root@pam') }}"
    api_password : "{{ item.proxmox.api_password|default(omit) }}"
    api_host     : "{{ item.proxmox.api_host }}"
    node         : "{{ item.proxmox.node }}"
    name         : "{{ item.name }}"
    cpu          : "{{ item.cpu|default('host') }}"
    kvm          : "{{ item.kvm|default('yes') }}"
    net          : "{'net0':'virtio,bridge={{ vlan|default(pxe.vlan) }}'}"
    virtio       : '{ {% for virtio,value in item.disks.items() %}"{{virtio}}":"{{value.storage}}:{{ value.size|upper|replace("G","")|default(size) }},format={{value.format|default(format)}}"{% if not loop.last %},{% endif %}{% endfor %} }'
    cores        : "{{ item.cores|default('4') }}"
    sockets      : "{{ item.sockets|default('1') }}"
    vcpus        : "{{ item.vcpus|default(omit) }}"
    memory       : "{{ item.memory|default('2048') }}"
    balloon      : "{{ item.ballon|default(omit) }}"
    hotplug      : "{{ item.hotplug|default('memory,cpu,disk,network') }}"
    numa_enabled : "{{ item.numa_enabled|default('yes') }}"
    keyboard     : "{{ item.keyboard|default('fr') }}"
    state        : "{{ item.state|default('present') }}"
    update       : "{{ item.update|bool|default(omit) }}"
    newid        : "{{ item.newid|default(omit) }}"
    clone        : "{{ item.clone|default(omit) }}"
    vmid         : "{{ item.vmid|default(omit)}}"
    delete       : "{{ item.delete|default(omit) }}"
    cpuunits     : "{{ item.cpuunits|default(omit) }}"
    revert       : "{{ item.revert|default(omit) }}"
    timeout      : "{{ item.timeout|default(omit) }}"
  register    : qemu
  with_items  : "{{ instance }}"
  loop_control:
    label: "{{ item.name }}"

- name: Manage Host state on Foreman (absent|present|rebooted|running).
  local_action:
    module: foreman_host
    foreman_host    : "{{ foreman.api_host }}"
    foreman_user    : "{{ foreman.api_user|default('admin') }}"
    foreman_pass    : "{{ foreman.api_password|default(omit) }}"
    name            : "{{ item.item.name }}"
    hostgroup       : "{{ item.item.hostgroup|default('VIRTUAL') }}"
    state           : "{{ item.item.state|default('present') }}"
    mac             : "{% if item.mac is defined %}{% if item.mac.net0 is defined %}{{ item.mac.net0 }}{% else %}{{ item.mac.net0|default(omit) }}{% endif %}{% else %}{{ item.mac|default(omit) }}{% endif %}"
    architecture    : "{{ architecture }}"
    operatingsystem : "{{ item.item.operatingsystem|default('Jessie') }}"
    subnet          : "{{ item.item.subnet|default('PROVISION') }}"
    domain          : "{{ item.item.domain|default('nexen.net') }}"
    environment     : "{{ build_env }}"
    medium          : "{{ medium }}"
    provision_method: "{{ provision_method }}"
    root_pass       : "{{ item.item.root_pass|default(omit) }}"
    build           : yes
    managed         : yes
    parameters      :
      - name : environment
        value: "{{ item.item.environment|default('production') }}"
      - name : address
        value: "{{ item.item.address|mandatory }}"
      - name : netmask
        value: "{{ item.item.netmask|default('255.255.255.0') }}"
      - name : gateway
        value: "{{ item.item.gateway|mandatory }}"
      - name : proxmox_vm
        value: 'yes'
      - name : client
        value: "{{ item.item.client|mandatory }}"
      - name : archi
        value: "{{ item.item.archi|default('false') }}"
      - name : partman
        value: "{% if item.item.disks['virtio0']['size']|upper|replace('G','')|default(size)|int in range(25,49) %}awh25G{%elif item.item.disks['virtio0']['size']|upper|replace('G','')|default(size)|int in range(50,90) %}awh50G{% elif item.item.disks['virtio0']['size']|upper|replace('G','')|default(size)|int >= 100 %}awh100G{% endif %}"
      - name: hypervisor
        value: "{{ item.item.proxmox.node }}"
      - name: vmid
        value: "{{ item.vmid|default('') }}"
      - name: orchestrator_info
        value: "{{ item.item.orchestrator|default('false') }}"
      - name: api_host
        value: "{{ item.item.proxmox.api_host }}"
  register: foreman_host
  with_items  : "{{ qemu.results }}"
  loop_control:
    label: "{{ item.item.name }}"
  when   : item.changed
  no_log : "{{ nolog }}"
```

**Comment by helldorado** [comment]
@nleof in fact, I will do it in a future commit, I have PR waiting.

**Comment by nleof** [comment]
Very well, closing this issue then. Thank you o/

**Comment by d3pre5s** [comment]
well, how soon it will be released?
i still get 
```
"new_kvm": {
        "changed": true, 
        "failed": false, 
        "msg": "VM test-runner with newid 109 cloned from vm with vmid 100"
    }
```
without any "vmid"

**Comment by helldorado** [comment]
@d3pre5s not implemented yet if `clone is not None`.  But since it's just a slight change to make, I'm going to make a fix tonight or tomorrow.

**Comment by helldorado** [comment]
@d3pre5s Fixed. Please see PR https://github.com/ansible/ansible/pull/42313 and https://github.com/ansible/ansible/pull/42313/commits/26d6faa9ca30c4b5b10f784ff3e40c63f0e77965

When `clone` you can get cloned `mac`, `devices` and `vmid` like:

```yaml
TASK [Debug QEMU] *****************************************************************
ok: [localhost] => {
    "qemu": {
        "changed": true,
        "devices": {
            "virtio0": "ZSF_labhyp1:base-110-disk-1/vm-114-disk-1"
        },
        "mac": {
            "net0": "16:16:F1:E5:28:BB"
        },
        "msg": "VM cloned-zfs-linked2 with newid 114 cloned from vm with vmid 110",
        "vmid": 114
    }
}
```

You can pull this version in your `playbooks/library/` If this fix your issue please feel free to leave comment with **shipit** keyword.
