### ISSUE TITLE
GCE Loadbalancer blocking selected port. Firewall has port open.

### ISSUE THREAD

**Issue by svanschalkwyk** [ansible/ansible#28527]
- Bug Report
##### COMPONENT NAME
gce_lb
##### ANSIBLE VERSION
```
ansible 2.4.0 (devel 6ba49f42c2) last updated 2017/07/14 15:12:03 (GMT -500)
  config file = None
  configured module search path = [u'/home/steph/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/steph/Ansible/ansible/lib/ansible
  executable location = /home/steph/Ansible/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Ubuntu 16.10
4.4.0-62-generic

##### SUMMARY
Create LB, correct port name:
```
Add firewall rule:
allow-all-private-net | Apply to all | IP ranges: 0.0.0.0/0 | all | Allow | 1000 | es-private-net
```
##### STEPS TO REPRODUCE
```
   - name: Create the load-balancer and add members
     gce_lb:
        name: search-loadbalancer
        region: "{{ es_lb_region }}"
        members: "{{ es_lb_members }}"
        httphealthcheck_name: search-healthcheck-80
        httphealthcheck_port: 80
        httphealthcheck_path: "/"
        protocol: http
        port_range: 8080-8080
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"

```
##### EXPECTED RESULTS
Expected to receive lb response.
##### ACTUAL RESULTS
```
Curl external IP:
```
curl: (7) Failed to connect to 35.202.82.112 port 8080: Connection refused
HOWEVER! tcpdump shows packet getting to individual vms:
20:24:11.903692 IP 112.82.202.35.bc.googleusercontent.com.http-alt > xxx-xxx-xxx-xxx.dhcp.stls.mo.charter.com.56238: Flags [R.], seq 0, ack 3792350154, win 0, length 0
```
When I curl to individual instances, there is a response and the vm shows this on tcpdump:
```
20:29:38.692891 IP xxx-xxx-xxx-xxx.dhcp.stls.mo.charter.com.52834 > elastic01.c.rse01-01.internal.http-alt: Flags [.], ack 423, win 237, options [nop,nop,TS val 5543033 ecr 371542924], length 0
```
