### ISSUE TITLE
service reload handlers restart when service state is stopped

### ISSUE THREAD

**Issue by dprittie** [ansible/ansible#28529]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
service module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT
running from: CentOS Linux release 7.2.1511 (Core)
managing: CentOS Linux release 7.3.1611 (Core) & CentOS 6.9 (Final)

##### SUMMARY
When attempting to reload a service that is stopped ansible starts the service.

##### STEPS TO REPRODUCE
```yaml
- hosts: all
  tasks:
    - name: install postfix package
      package:
        name: postfix

    - name: test modify postfix main.cf to trigger handler
      lineinfile:
        path: /etc/postfix/main.cf
        state: present
        regexp: '^#test'
        line: '#test'
      notify: reload postfix

    - name: disable and stop the postfix service
      service:
        enabled: no
        name: postfix
        state: stopped

  handlers:
    - name: reload postfix
      service:
        name: postfix
        state: reloaded
```

##### EXPECTED RESULTS
the postfix service is stopped

##### ACTUAL RESULTS
the postfix service is running
