### ISSUE TITLE
Virtual Network and Subnet from another Resource Group are not supported in `azure_rm_networkinterface` resource provider

### ISSUE THREAD

**Issue by bdmyxgh** [ansible/ansible#28534]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`azure_rm_networkinterface`

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /Users/user/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### SUMMARY
Seems like specifying a Virtual Network from another Resource Group is not supported? Azure supports that case, but Ansible does not seem to..

##### STEPS TO REPRODUCE

```yaml
---
- name: Create Resource group
  azure_rm_resourcegroup:
    name: "{{my_resource_group}}"
    location: "{{location}}"
- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "{{my_resource_group}}"
    name: "{{vnic}}"
    virtual_network: "{{another_rg_vnet}}"
    subnet: "{{another_rg_subnet}}"
    security_group: "{{sec_group}}"
```

##### EXPECTED RESULTS
Virtual interface should be created with a subnet from another RG virtual network

##### ACTUAL RESULTS
```
"msg": "Error: fetching subnet subnet-name in virtual network vnet-name - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Network/virtualNetworks/vnet-name' under resource group 'my-resource-group' was not found."}
```
