### ISSUE TITLE
win_firewall_rule: Corrupted rules on Win7 and Win10

### ISSUE THREAD

**Issue by Manakel166** [ansible/ansible#28555]
Checked on latest Ansible release: v2.3.2.0-1 
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_firewall_rule

##### ANSIBLE VERSION

```

```

##### OS / ENVIRONMENT

OS Managed is windows 10 and windows 7

##### SUMMARY

When you create a firewall rule (port or program authorisation) using ansible, and you dont provide any value for the Service parameter,  the generated rule is not working. You can see it in the firewall and it looks ok in the "Firewall with Advanced security" app but the rule is not applied.

If you take a look in the registry settings, you see than ansible has inserted a Svc=* configuration. 
v2.26|Action=Allow|Active=TRUE|Dir=In|Protocol=6|App=c:\\selenium\iedriverserver.exe|**Svc=***|Name=IEDriver In (TCP)|

But the firewall seems to expect nothing, if there is no Service restriction on the rule.

##### STEPS TO REPRODUCE

On a firewall configured to block inbound connection, unless a rule is matched.
Create a rule to open a port for inbound connection on a port using ansible
Create a rule to open a port for inbound connection on the same port using the Windows with advanced security app.

Disable the manually created rule and ensure the ansible one is enabled.
Try to connect, the connection is refused.

Disable the ansible rule and ensure the manullay created one is enabled
Try to connect , the connection is accepted.

Open the registry editor and look for your rules name . You will see the difference in the data value of the registry key.

Simply remove the Svc:* from the registry data and the ansible rule will work.

```yaml
- name: Allow port 4598 through firewall incoming
   win_firewall_rule:
    name: "IE Node (4598)"
    localport: 4598
    protocol: TCP
    action: allow
    direction: In
   state: present
```

##### ACTUAL RESULTS

```
ww
```

**Comment by ansibot** [comment]
cc @if-meaton
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mikeeaton83** [comment]
Wrong module. should be win_firewall_rule..

**Comment by ansibot** [comment]
cc @TimothyVandenbrande @ar7z1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@Manakel166 Could you please test the refactored module at: https://github.com/ansible/ansible/pull/27381

We like to have more feedback to build confidence in shipping this in Ansible v2.4.

**Comment by ar7z1** [comment]
@Manakel166 Thank you for report!

If the problem is in `Svc=*`, then @dagwieers already fixed it in #23162.

I ran your example:
```yaml
- name: Allow port 4598 through firewall incoming
   win_firewall_rule:
    name: "IE Node (4598)"
    localport: 4598
    protocol: TCP
    action: allow
    direction: In
   state: present
```
on my Windows 10.

Latest published ansible (ansible 2.3.2.0) creates rule with `Svc=*`:
```
v2.27|Action=Allow|Active=TRUE|Dir=In|Protocol=6|LPort=4598|Svc=*|Name=IE Node (4598)|
```

Ansible from `devel` branch (ansible 2.4.0 (devel 6397e68bfd)) creates rule without `Svc`:
```yaml
v2.27|Action=Allow|Active=TRUE|Dir=In|Protocol=6|LPort=4598|Name=IE Node (4598)|
```

And ansible from #27381 branch creates the same rule:
```yaml
v2.27|Action=Allow|Active=TRUE|Dir=In|Protocol=6|LPort=4598|Name=IE Node (4598)|
```

Can you test that your bug is fixed in devel branch and in PR #27381?
