### ISSUE TITLE
Synchronize does not template ansible_remote_user or ansible_ssh_user

### ISSUE THREAD

**Issue by rhpvorderman** [ansible/ansible#28551]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Synchronize

##### ANSIBLE VERSION
ansible 2.3.2.0 
ansible 2.3.0.0
(tested both) 

##### CONFIGURATION
ansible_ssh_pipelining both set to true and false does not matter.

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS

##### STEPS TO REPRODUCE
```yaml
- hosts: test_host
  user: test_user
  become: no
  vars:
    ssh_user: another_user #Also does not work with test_user even though that is the same as the original user
  tasks:
    - debug: 
        var: ssh_user
    - name: test 
      synchronize:
        src: "test.file"
        dest: "/home/{{ssh_user}}/test.file"
      vars: 
        ansible_ssh_user: "{{ssh_user}}" 
```

##### EXPECTED RESULTS

Connecting to the remote machine as `another_user` and transferring the files to directories that `another_user` has unique permissions to.

##### ACTUAL RESULTS

Connection was made as `{{ssh_user}}` instead of `another_user`.
```json
fatal: [test_host]: FAILED! => {
    "changed": false, 
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no --out-format=<<CHANGED>>%i %n%L /home/local_user/test/test.file {{ssh_user}}@test_host:/home/another_user/test.file", 
    "failed": true, 
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync", 
            "_substitute_controller": false, 
            "archive": true, 
            "checksum": false, 
            "compress": true, 
            "copy_links": false, 
            "delete": false, 
            "dest": "{{ssh_user}}@test_host:/home/another_user/test.file", 
            "dest_port": null, 
            "dirs": false, 
            "existing_only": false, 
            "group": null, 
            "links": null, 
            "mode": "push", 
            "owner": null, 
            "partial": false, 
            "perms": null, 
            "private_key": null, 
            "recursive": null, 
            "rsync_opts": null, 
            "rsync_path": null, 
            "rsync_timeout": 0, 
            "set_remote_user": true, 
            "src": "/home/local_user/test/test.file", 
            "ssh_args": null, 
            "times": null, 
            "verify_host": false
        }
    }, 
    "msg": "Received disconnect from (test_host ip): Too many authentication failures for {{ssh_user}}\r\nConnection to test_host closed by remote host.\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]\n", 
    "rc": 255
}
```

**Comment by ansibot** [comment]
cc @tima
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nrwahl2** [comment]
@rhpvorderman Not a bug. Documented, although it's a bit hard to recognize until you know it's there.

> Another important thing to consider (for all versions) is that connection variables override config, command line and play/role/task specific options and directives. For example:
```
ansible -u lola myhost
```
> This will still connect as ramon because ansible_ssh_user is set to ramon in inventory for myhost. For plays/tasks this is also true for remote_user:
```
- hosts: myhost
  tasks:
   - command: i'll connect as ramon still
     remote_user: lola
```
> This is done so host-specific settings can override the general settings. These variables are normally defined per host or group in inventory, but they behave like other variables. If you want to override the remote user globally (even over inventory) you can use extra vars:
```
ansible... -e "ansible_user=<user>"
```
> You can also override as a normal variable in a play:
```
- hosts: all
  vars:
    ansible_user: lola
  tasks:
    - command: i'll connect as lola!
```
(http://docs.ansible.com/ansible/latest/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)

P.S. `ansible_ssh_user` is deprecated. The current format is `ansible_user`.

[Edited to remove a piece of incorrect information.]

**Comment by rhpvorderman** [comment]
Thank you for your answer. However, this is not the problem that I have. As you can see in the example playbook I did manage to override the connection user by specifying it in the `vars:` section of a task. No issues there.

My problem is not that it does not connect as `lola` . My problem is that it connects as 

**`{{ssh_user}}`**  _(The raw variable name. Including the brackets!)_

As you can see here:
```YAML
 "dest": "{{ssh_user}}@test_host:/home/another_user/test.file", 
```
and here:
```YAML
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no --out-format=<<CHANGED>>%i %n%L /home/local_user/test/test.file {{ssh_user}}@test_host:/home/another_user/test.file"
```
and here:
```YAML
    "msg": "Received disconnect from (test_host ip): Too many authentication failures for {{ssh_user}}\r\nConnection to test_host closed by remote host.\r\nrsync: connection unexpectedly closed (0 bytes received so far) [sender]\nrsync error: unexplained error (code 255) at io.c(226) [sender=3.1.1]\n", 
    "rc": 255
```
Obviously raw `{{ssh_user}}` does not exist on the remote host.

edit: extra example

**Comment by rhpvorderman** [comment]
By the way, I already checked `lib/ansible/modules/files/synchronize.py` and could not find the error in there. It is probably somewhere deeper, but I am not knowledgeable enough in ansible architecture to find where that is.

**Comment by nrwahl2** [comment]
Any luck with replacing `ansible_user` with `remote_user`, if that accomplishes what you need?

```
  vars:
    ssh_user: user
  tasks:
    - name: Test variables
      synchronize:
        src: test.file
        dest: '/home/{{ ssh_user }}/test.file'
      vars:
        remote_user: '{{ ssh_user }}'
```
```
TASK [Test variables] **********************************************************************
task path: /home/ansible/test.yml:8
Using module file /home/ansible/ansible/lib/ansible/modules/files/synchronize.py
<nrwahl2> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<nrwahl2> EXEC /bin/sh -c 'echo ~ && sleep 0'
<nrwahl2> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1503564474.08-57861564755826 `" && echo ansible-tmp-1503564474.08-57861564755826="` echo /home/ansible/.ansible/tmp/ansible-tmp-1503564474.08-57861564755826 `" ) && sleep 0'
<nrwahl2> PUT /tmp/tmpcoFZdN TO /home/ansible/.ansible/tmp/ansible-tmp-1503564474.08-57861564755826/synchronize.py
<nrwahl2> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1503564474.08-57861564755826/ /home/ansible/.ansible/tmp/ansible-tmp-1503564474.08-57861564755826/synchronize.py && sleep 0'
<nrwahl2> EXEC /bin/sh -c '/usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1503564474.08-57861564755826/synchronize.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1503564474.08-57861564755826/" > /dev/null 2>&1 && sleep 0'
changed: [nrwahl2] => {
    "changed": true, 
    "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --out-format=<<CHANGED>>%i %n%L /home/ansible/test.file nrwahl2:/home/user/test.file", 
    "failed": false, 
    "invocation": {
        "module_args": {
            "_local_rsync_path": "rsync", 
            "_substitute_controller": false, 
            "archive": true, 
            "checksum": false, 
            "compress": true, 
            "copy_links": false, 
            "delete": false, 
            "dest": "nrwahl2:/home/user/test.file", 
            "dest_port": null, 
            "dirs": false, 
            "existing_only": false, 
            "group": null, 
            "links": null, 
            "mode": "push", 
            "owner": null, 
            "partial": false, 
            "perms": null, 
            "private_key": null, 
            "recursive": null, 
            "rsync_opts": null, 
            "rsync_path": null, 
            "rsync_timeout": 0, 
            "set_remote_user": true, 
            "src": "/home/ansible/test.file", 
            "ssh_args": null, 
            "times": null, 
            "verify_host": false
        }
    }, 
    "msg": "<f+++++++++ test.file\n", 
    "rc": 0, 
    "stdout_lines": [
        "<f+++++++++ test.file"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************
nrwahl2                    : ok=1    changed=1    unreachable=0    failed=0   
```

```
[user@nrwahl2 ~]$ ll test.file
-rw-rw-r--. 1 ansible ansible 5 Aug 23 23:50 test.file
```

**Comment by rhpvorderman** [comment]
No. using `ansible_user` or `remote_user` does not work and gives the same problem.
By the way, I believe that `ansible_ssh_user` is not deprecated. It takes priority over both `ansible_user` and `remote_user`. 
Regardless of choice however, the raw `{{ssh_user}}` text is used instead of the value of ssh_user.

**Comment by dagwieers** [comment]
AFAIK you have to use **remote_user** if you want to influence the connection plugin, but extra variables (set with e.g. `-e ansible_user`) will take precedence over whatever you do with **remote_user**.

**Comment by rhpvorderman** [comment]
Solved the issue thanks to @nrwahl2. It turned out that indeed ansible_ssh_user is deprecated and replacing all instances of `ansible_ssh_user` with `ansible_user` solved the problem while maintaining  the functionality of switching users.
Thanks a lot for your time!
```YAML
- hosts: test_host
  user: test_user
  become: no
  vars:
    ssh_user: another_user #Also does not work with test_user even though that is the same as the original user
  tasks:
    - debug: 
        var: ssh_user
    - name: test 
      synchronize:
        src: "test.file"
        dest: "/home/{{ssh_user}}/test.file"
      vars: 
        ansible_user: "{{ssh_user}}"  #solved the problem
```
