### ISSUE TITLE
Reboot always required executing win_domain_membership

### ISSUE THREAD

**Issue by gregsergeant** [ansible/ansible#28565]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
win_domain_membership

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
No configuration changes

##### OS / ENVIRONMENT
Ubuntu - Linux subsystem for Windows. 
Not supported I know but I don't believe that is at play here.

##### SUMMARY
The return value from the win_domain_membership module always indicates a reboot is always required even if changes aren't made.

##### STEPS TO REPRODUCE
Join a Windows system to a domain, a reboot is required as expected.  Run the same code again, a reboot is required, not expected.

```yaml
- hosts: virtualVM
  tasks:
    - win_domain_membership:
        dns_domain_name: my.domain.com
        hostname: newserver
        domain_admin_user: adm-user
        domain_admin_password: *****
        state: domain
        register: domain_state

    - win_reboot:
        when: domain_state.reboot_required
        shutdown_timeout_sec: 1200
        reboot_timeout_sec: 1200
```

##### EXPECTED RESULTS
Reboot is required on first run, but not on second run.

##### ACTUAL RESULTS
Reboot is required on both runs.

Assuming that I am looking at the correct code in GitHub (https://github.com/nitzmahone/windows-ansible-modules/blob/master/library/win_domain_membership.ps1), I think the problem lies at line 205. 
 This should be moved up into the If and ElseIf statements above.  The result.reboot_required should only be set true if one of these two code paths is executed.  Right now it is being set true regardless if either of these two conditionals is met, even if no domain state change is required...

      # all these changes require a reboot
      $result.reboot_required = $true

```
NA - not sure what to put here.
```

**Comment by ansibot** [comment]
cc @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
You are not looking at the correct code, but the correct code is having the same problem :-)

The correct code is here: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_domain_membership.ps1

And I agree with your assessment. There is an else missing (the part where it's already joined to a domain and doesn't need a name-change). And only the 2 former blocks require a reboot.

BTW You could have proposed your own PR. But in the meantime I fixed it in #28579

@gregsergeant Could you please test this modified module and report back ?

**Comment by jborean93** [comment]
@gregsergeant a PR has been merged to fix this, thanks @dagwieers

**Comment by gregsergeant** [comment]
@dagwieers  I retested.  Your implemented fix seems correct.  However I ran into additional issues with the Get-DomainMembershipMatch function when executing the same code the second time through.  It appears that the call to GetComputerDomain must be made with the domain credentials.  I suggest this change to the Try block in the function Get-DomainMembershipMatch. This makes sure the call to GetComputerDomain is always done with the domain creds no matter how the attachment to winrm is made. 

```powershell
Try {
        $domain_cred = Create-Credential $domain_admin_user $domain_admin_password
        $session = New-PSSession -Credential $domain_cred 

        Write-DebugLog "calling GetComputerDomain()"
        $current_dns_domain = Invoke-Command -Session $session -ScriptBlock{[System.DirectoryServices.ActiveDirectory.Domain]::GetComputerDomain().Name}

        $domain_match = $current_dns_domain -eq $dns_domain_name

        Write-DebugLog ("current domain {0} matches {1}: {2}" -f $current_dns_domain, $dns_domain_name, $domain_match)

        return $domain_match
```
But this only fixes part of the problem.  The other problem I noticed was that the result returned from this module when the computer is already on the domain has result.changed and result.reboot_required set to False, but the reboot still happens.  This seems to indicate a problem with the win_reboot module itself.  However, I can't seem to find the code for this so I can't check it out.  

Sorry, I'm new to the open source community and the best way to do some things.  You mentioned I could have 'proposed your own PR'.  How do I do that?  And any guidance on where to find win_reboot module code is appreciated as well.  I expected to find a win_reboot.ps1 in the Ansible installed files but did not.

Thanks again
Greg

**Comment by dagwieers** [comment]
@gregsergeant If you know what code should be changed, you can provide that fix as part of a PR (pull-request). You don't even need to know how Git works, in Github you can edit the file yourself and it will create a PR for you.

There is a no win_reboot.ps1, because it is implemented as an action-plugin., so you'll find a win_reboot.py. However, this cannot be an issue with win_reboot itself.

**Comment by gregsergeant** [comment]
@dagwieers  Thank you for the clarification and explanation.  That helps me a lot.  

I'm not doubting you with regards to the stability of win_reboot.  The reason it at least appears that way to me, is that I can execute this code and the reboot still occurs...

```yaml
- win_reboot:
        when: false
        shutdown_timeout_sec: 1200
        reboot_timeout_sec: 1200
```

I have also tried things like "when: 0 == 1".  But it always reboots the machine.  Perhaps the when condition check is not functioning correctly here.  There doesn't appear to be any way to conditionally reboot Windows.  

Sorry if this is not the place for such discussion.  I can open a new issue if that is better.

**Comment by dagwieers** [comment]
@gregsergeant The syntax is a bit off, it should be:
```yaml
  - win_reboot:
      shutdown_timeout_sec: 1200
      reboot_timeout_sec: 1200
    when: no
```
(The "no" can be "false", "False", "off", which all translate to a boolean).

Consider this playbook:
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - debug:
      msg: 'This would be the reboot (when=no)'
    when: no

  - debug:
      msg: 'This would be the reboot (when=False)'
    when: False
```

It does this:
```
[dag@moria ansible.testing]$ ansible-playbook test165.yml

PLAY [localhost] ***********************************************************************************

TASK [debug] ***************************************************************************************
skipping: [localhost]

TASK [debug] ***************************************************************************************
skipping: [localhost]

PLAY RECAP *****************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=0   
```

Is it somehow possible that one of the previous tasks causes a reboot ?

What if you simple leave out the win_reboot task ? Does it still reboot ?

**Comment by dagwieers** [comment]
To prove you this is not related to **win_reboot**:

```yaml
- hosts: computers
  gather_facts: no
  tasks:
  - win_reboot:
    when: false

  - wait_for_connection:
```
Results in:
```
[dag@moria crombeen]$ ansible-playbook reboot.yml -l computer27

PLAY [computers] ***********************************************************************************

TASK [win_reboot] **********************************************************************************
skipping: [computer27]

TASK [wait_for_connection] *************************************************************************
ok: [computer27]

PLAY RECAP *****************************************************************************************
computer27                 : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by gregsergeant** [comment]
@dagwieers Yes, my mistake.  Indentation of the when clause got me here.  It should be outdented to match the module name, not indented to match the parameters of the module.  Sorry I'm still new to Ansible.

```yaml
   # reboots - improper indention
    - win_reboot:
        when: false
```

VS

```yaml
   # does not reboot - proper indention
    - win_reboot:
      when: false
```

So in short, your fix to win_domain_membership has addressed the issue.  Thank you!
