### ISSUE TITLE
Unable to execute ansible-galaxy install -r requirements.yml due to CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by jorojas** [ansible/ansible#28570]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible-galaxy install -r requirements.yml 

##### ANSIBLE VERSION

```
2.3.2.0 with Python 3.6.2
```

##### CONFIGURATION

My requirements.yml file:
```yaml
- name: ntp
  src: geerlingguy.ntp
  version: 1.1.0

- name: mysql
  src: geerlingguy.mysql
  version: 2.0.1

- name: composer
  src: geerlingguy.composer
  version: 1.3.0

- name: php
  src: geerlingguy.php
  version: 2.0.1

- src: geerlingguy.daemonize
  version: 1.1.0

- name: mailhog
  src: geerlingguy.mailhog
  version: 1.0.5

- name: nodejs
  src: https://github.com/AnsibleShipyard/ansible-nodejs
  version: 68a38ab02b39576d2c432bb55d7431eb6f23d053

- name: sshd
  src: willshersystems.sshd
  version: 0.4.3

- name: postgresql
  src: ANXS.postgresql
  version: v1.4.0

- name: redis
  src: DavidWittman.redis
  version: 1.0.9

- name: rabbitmq
  src: https://github.com/Mayeu/ansible-playbook-rabbitmq
  version: 49e311e8d99db0775bd43a9b77c2601ec36293bd

- name: newrelic
  src: https://github.com/virtru/ansible-newrelic.git
  version: fb727899bdfbdd05e76600fb3b468cb5029751bd

- name: swapfile
  src: https://github.com/Oefenweb/ansible-swapfile
  version: 175ddb02972977d0341851c4f93170d00374998a

- name: nginx
  src: jdauphant.nginx
  version: v2.0

- name: elasticsearch
  src: https://github.com/Traackr/ansible-elasticsearch
  version: 085bb55f165f2f6b050fae3181b3918a76133874

- name: letsencrypt
  src: https://github.com/thefinn93/ansible-letsencrypt
  version: 061613c445240f5a265648bbe5ec06401d934483

- name: ssl-certs
  src: jdauphant.ssl-certs
  version: v1.2.2
```

##### OS / ENVIRONMENT

MAC OS Sierra
##### SUMMARY

When I execute ansible-galaxy install using my requirements.yml File I get the following error:

**urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)**

##### STEPS TO REPRODUCE

```yaml
ansible-galaxy install -r requirements.yml
```

##### EXPECTED RESULTS

Dependencies installed..

##### ACTUAL RESULTS

```
[WARNING]: - ntp was NOT installed successfully: Failed to get data from the API server (https://galaxy.ansible.com/api/):
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)>

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```
