### ISSUE TITLE
[DEPRECATION WARNING]: None. This feature will be removed in version 2.8.

### ISSUE THREAD

**Issue by basictheprogram** [ansible/ansible#28583]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0 (devel cd8c1c1108) last updated 2017/08/23 22:03:37 (GMT -500)
  config file = None
  configured module search path = [u'/Users/tanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tanner/projects/ansible.git/ansible/lib/ansible
  executable location = /Users/tanner/projects/ansible.git/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

Management host macOS 10.12.5
Managed host Windows 6

##### SUMMARY

[DEPRECATION WARNING]: None.
This feature will be removed in version 2.8.

##### STEPS TO REPRODUCE

Variables 
```yaml
installers:
  - {
      file: "Installer2017-1-2-2.zip",
      url: "http://www.real-time.com/Releases",
      dest: "{{ ansible_env['USERPROFILE'] }}\\Downloads"
    }
  - {
      file: "InstallerDataInterface.zip",
      url: "http://www.real-time.com/Releases",
      dest: "{{ ansible_env['USERPROFILE'] }}\\Downloads" 
    }
```
Play
```yaml
- name: unzip 2017 installers
  win_unzip:
    src: "{{ item.dest }}\\{{ item.file }}"
    dest: "{{ item.dest }}"
  with_items:
    - "{{ installers }}"
```

##### EXPECTED RESULTS

No DEPRECATION warning

##### ACTUAL RESULTS

```
[DEPRECATION WARNING]: None.
This feature will be removed in version 2.8.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.
```
