### ISSUE TITLE
Delegate_to: not honoring ansible_ssh_host

### ISSUE THREAD

**Issue by rubbsdecvik** [ansible/ansible#2858]
When using `delegate_to` in a playbook, the `ansible_ssh_host` variable is not being honoured.

``` YAML
    - name: Print test on Zoltan
      action: command echo "Hi from Zoltan!"
      delegate_to: zoltan
```

With the following inventory entry:

`zoltan ansible_ssh_host=zoltan-4.eyemg.com`

Produces a timeout. The following works correctly:

``` YAML
    - name: Print test on Zoltan
      action: command echo "Hi from Zoltan!"
      delegate_to: zoltan-4.eyemg.com
```

This was tested in both 1.1 and 1.2 devel 736700f350
