### ISSUE TITLE
GCE launch failed : Unexpected response : 'private_key'

### ISSUE THREAD

**Issue by ksingh7** [ansible/ansible#28580]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- Module : gce

##### ANSIBLE VERSION

Tested with 2 differen ansible + apache libcloud versions
- ansible (2.3.1.0) and apache-libcloud (2.1.0) 
- ansible (2.2.2.0) and apache-libcloud (1.5.0)

##### OS / ENVIRONMENT

MacOS Sierra 10.12.6
##### SUMMARY

Unable to create GCE instance using gce module. Playbook fails with the error mentioned below.

##### STEPS TO REPRODUCE

```yaml
---
- name:  Google Compute Platform Resources
  hosts: localhost
  gather_facts: False
  tasks:
    - name: GCE  instance
      gce:
        instance_names: "{{ instance_name }}"
        machine_type: "{{ instance_machine_type }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        tags: "{{ tags }}"
        state: "{{ state }}"
        preemptible: "{{ preemptible }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
      register: gce_instance

    - debug: var=gce_instance.stdout_lines

    - name: GCP disk
      gce_pd:
          name: "{{ disk_name }}"
          instance_name: "{{ instance_name }}"
          size_gb: "{{ disk_size }}"
          disk_type: "{{ disk_type }}"
          zone: "{{ zone }}"
          mode: "{{ mode }}"
          state: "{{ disk_state }}"
          credentials_file: "{{ credentials_file }}"
          service_account_email: "{{ service_account_email }}"

    - name: Waiting for SSH to respond
      wait_for: delay=1 host={{ item.public_ip }} port=22 state=started timeout=30
      with_items: "{{ gce_instance.instance_data }}"

    - name: Save host data for first zone
      add_host: hostname={{ item.public_ip }} groupname=gce_instances
      with_items: "{{ gce_instance.instance_data }}"

```

Also tried to following instructions mentioned in these demo repos , but still the same failure.
- https://github.com/GoogleCloudPlatform/compute-ansible-gluster
- https://github.com/GoogleCloudPlatform/compute-video-demo-ansible
##### EXPECTED RESULTS

- GCE instance should get launched
##### ACTUAL RESULTS

```
TASK [GCE  instance] *****************************************************************************************************************
task path: /Users/karasing/git/provision-gpc-resources.yml:6
Using module file /Library/Python/2.7/site-packages/ansible/modules/cloud/google/gce.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: karasing
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/karasing/.ansible/tmp/ansible-tmp-1503517540.67-216116142493831 `" && echo ansible-tmp-1503517540.67-216116142493831="` echo /Users/karasing/.ansible/tmp/ansible-tmp-1503517540.67-216116142493831 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/y_/2fq7qh8n7qn58ww48rpx297c0000gn/T/tmph5B0n5 TO /Users/karasing/.ansible/tmp/ansible-tmp-1503517540.67-216116142493831/gce.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/karasing/.ansible/tmp/ansible-tmp-1503517540.67-216116142493831/ /Users/karasing/.ansible/tmp/ansible-tmp-1503517540.67-216116142493831/gce.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /Users/karasing/.ansible/tmp/ansible-tmp-1503517540.67-216116142493831/gce.py; rm -rf "/Users/karasing/.ansible/tmp/ansible-tmp-1503517540.67-216116142493831/" > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "credentials_file": "/Users/karasing/.config/gcloud/application_default_credentials.json",
            "disk_auto_delete": true,
            "disk_size": 10,
            "disks": null,
            "external_ip": "ephemeral",
            "image": "centos-7-v20170816",
            "instance_names": "test-instance-1",
            "ip_forward": false,
            "machine_type": "n1-standard-1",
            "metadata": null,
            "name": null,
            "network": "default",
            "num_instances": null,
            "pem_file": null,
            "persistent_boot_disk": false,
            "preemptible": true,
            "project_id": "test-env",
            "service_account_email": "xxxxxxxx@developer.gserviceaccount.com",
            "service_account_permissions": null,
            "state": "present",
            "subnetwork": null,
            "tags": [
                "lamp",
                "node-1"
            ],
            "zone": "us-central1-a"
        }
    },
    "msg": "Unexpected response: ('private_key'). Detail: Traceback (most recent call last):\n  File \"/var/folders/y_/2fq7qh8n7qn58ww48rpx297c0000gn/T/ansible_TAEHO9/ansible_modlib.zip/ansible/module_utils/gcp.py\", line 267, in gcp_connect\n    project=creds['project_id'])\n  File \"/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py\", line 1795, in __init__\n    super(GCENodeDriver, self).__init__(user_id, key, **kwargs)\n  File \"/Library/Python/2.7/site-packages/libcloud/common/base.py\", line 948, in __init__\n    self.connection = self.connectionCls(*args, **conn_kwargs)\n  File \"/Library/Python/2.7/site-packages/libcloud/compute/drivers/gce.py\", line 99, in __init__\n    credential_file=credential_file, **kwargs)\n  File \"/Library/Python/2.7/site-packages/libcloud/common/google.py\", line 767, in __init__\n    user_id, key, auth_type, credential_file, scopes, **kwargs)\n  File \"/Library/Python/2.7/site-packages/libcloud/common/google.py\", line 653, in __init__\n    self.user_id, self.key, self.scopes, **kwargs)\n  File \"/Library/Python/2.7/site-packages/libcloud/common/google.py\", line 500, in __init__\n    key = key['private_key']\nKeyError: 'private_key'\n"
}
```

**Comment by ansibot** [comment]
cc @erjohnso @supertom
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ksingh7** [comment]
The error points to private_keys, I am not sure why and which private keys GCE module is looking for.  

What i know is my SSH public keys are properly set into GCE project metadata and also the GCP credentials JSON file is in the right place with correct auth values. 

If you guys know which private_key the playbook is looking for, pls let me know

**Comment by nrwahl2** [comment]
@ksingh7 Well, here's where it's failing:
```
[reid@laptop /usr/lib/python2.7/site-packages/libcloud/common]$ tail -n +469 google.py | head -32
class GoogleServiceAcctAuthConnection(GoogleBaseAuthConnection):
    """Authentication class for "Service Account" authentication."""
    def __init__(self, user_id, key, *args, **kwargs):
        """
        Check to see if PyCrypto is available, and convert key file path into a
        key string if the key is in a file.

        :param  user_id: Email address to be used for Service Account
                authentication.
        :type   user_id: ``str``

        :param  key: The RSA Key or path to file containing the key.
        :type   key: ``str``
        """
        if SHA256 is None:
            raise GoogleAuthError('PyCrypto library required for '
                                  'Service Account Authentication.')
        # Check to see if 'key' is a file and read the file if it is.
        if key.find("PRIVATE KEY---") == -1:
            # key is a file
            keypath = os.path.expanduser(key)
            is_file_path = os.path.exists(keypath) and os.path.isfile(keypath)
            if not is_file_path:
                raise ValueError("Missing (or not readable) key "
                                 "file: '%s'" % key)
            with open(keypath, 'r') as f:
                contents = f.read()
            try:
                key = json.loads(contents)
                key = key['private_key']
            except ValueError:
                key = contents
```

Based on this, it would appear that there's an issue either with your JSON format or with the `private_key` key. At first glance it looks like it's succeeding at finding and opening your auth file, then loading it's contents into a dictionary and not finding they key `private_key` there.

Of course, it's also possible that arguments are being passed incorrectly to `GoogleServiceAcctAuthConnection.__init__()`. Not immune to bugs. But let's double-check the JSON first.

**Comment by ksingh7** [comment]
@nrwahl2 thanks for taking a look at my issue.

Here are the contents of JSON file
```
$ cat /Users/karasing/.config/gcloud/application_default_credentials.json
{
  "client_id": "xxxxx.apps.googleusercontent.com",
  "client_secret": "xxxxx",
  "refresh_token": "xxxxxx",
  "type": "authorized_user"
}
$
```
Do you think this JSON is missing someting ? 
Also, could you help me understand which ``private_key`` gce module is looking for.

I already have my local SSH keys added into instance metadata. I don't think gce needs my local account's private keys.

**Comment by ksingh7** [comment]
@nrwahl2 
Also if i try like this , it fails with the same error
```
$ ansible-playbook -i hosts provision-gpc-resources.yml --private-key /Users/karasing/.ssh/id_rsa
```
So, confused, which private_key it needs

**Comment by nrwahl2** [comment]
Info might be here:
https://cloud.google.com/docs/authentication/api-keys
https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances

I don't have experience with cloud administration. I'm making sense of the errors you're seeing by looking at the code, as best I can.

**Comment by nrwahl2** [comment]
@ksingh7 : Step-by-step guide from the Ansible docs site. Step 2 especially might point you in the right direction.
https://docs.ansible.com/ansible/latest/guide_gce.html#credentials

> To work with the GCE modules, you’ll first need to get some credentials in the JSON format:

1. [Create a Service Account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#creatinganaccount)
2. [Download JSON credentials](https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts)

> There are three different ways to provide credentials to Ansible so that it can talk with Google Cloud for provisioning and configuration actions:
> 
> Note
> 
> If you would like to use JSON credentials you must have libcloud >= 0.17.0

- by providing to the modules directly
- by populating a secrets.py file
- by setting environment variables

> Calling Modules By Passing Credentials

> For the GCE modules you can specify the credentials as arguments:

- `service_account_email`: email associated with the project
- `credentials_file`: path to the JSON credentials file
- `project_id`: id of the project

> For example, to create a new instance using the cloud module, you can use the following configuration:

```
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: unique-id@developer.gserviceaccount.com
    credentials_file: /path/to/project.json
    project_id: project-id
    machine_type: n1-standard-1
    image: debian-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"
```

> When running Ansible inside a GCE VM you can use the service account credentials from the local metadata server by setting both service_account_email and credentials_file to a blank string.
