### ISSUE TITLE
seport: Mismatch in default value of attribute state between code and docs

### ISSUE THREAD

**Issue by Nosmoht** [ansible/ansible#28653]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

seport

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/ansible/roles/mariadb/tests/cluster/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]
```

##### SUMMARY

The [docu of module seport](http://docs.ansible.com/ansible/latest/seport_module.html) describes that the default value of attribute state is __default__. This default is not used within the code which results in an error if the attribute is omited.

##### STEPS TO REPRODUCE

```ini
[mysql]
mysql.example.com
```

```yaml
---
- hosts: mysql
  tasks:
  - name: Ensure SELinux port
      seport:
        ports: 4567
        proto: tcp
        setype: mysqld_port_t
```

##### EXPECTED RESULTS

Tasks runs without an error

##### ACTUAL RESULTS

```shell
failed: [mysql.example.com] (item={u'setype': u'mysqld_port_t', u'port': 4444, u'proto': u'tcp'}) => {"failed": true, "item": {"port": 4444, "proto": "tcp", "setype": "mysqld_port_t"}, "msg": "missing required arguments: state"}
```

```

```
