### ISSUE TITLE
When `with_items` is used with a set operation it fails.

### ISSUE THREAD

**Issue by karrots** [ansible/ansible#28683]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Set operations in tasks return `set()` instead of item.

##### ANSIBLE VERSION
```
ansible --version
ansible 2.4.0
  config file = /home/username/netcom-network-ansible/ansible.cfg
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Updated to a git release of Ansible

##### OS / ENVIRONMENT
Running ansible on Linux but doesn't seem to be an OS level issue.

##### SUMMARY
When using set operations with `with_items` returns `set()` instead of the item in the loop.

##### STEPS TO REPRODUCE

```yaml
- name: get current configured ntp servers
  set_fact: _servers="{{ ansible_net_config | regex_findall('ntp server (\S+)\\n') }}"

- name: remove old ntp servers
  ios_config:
    lines:
      - "no ntp server {{ ntp_old_server }}"
    match: none
  with_items: "{{ _servers | difference(ntp_servers) }}"
  loop_control:
    loop_var: ntp_old_server
```

##### EXPECTED RESULTS
`with_items` interating over result set of operation and returing single items to `net_old_server` rather than a complete set(). 

##### ACTUAL RESULTS
`ntp_old_server` is filled with the text `set()` instead of IP addresses from the resulting operation. In the end text like ` no ntp server set()` is sent to the switch instead of `no ntp server 127.0.0.1`

```
TASK [ntp : remove old ntp servers] **************************************************************************************************************************
changed: [te-1a-sw1.mgmt.tld] => (item=set())
changed: [su-2b-sw1.mgmt.tld] => (item=set())
```

**Comment by nrwahl2** [comment]
@karrots Is this relevant to your needs? https://stackoverflow.com/questions/43660868/ansible-regex-findall-multiple-sets (which also links to https://stackoverflow.com/questions/43902117/ansible-list-of-lists-flattening)

`with_list` might be your friend here. I don't have my own test case or networking gear to verify right now, so I'm using an artificial one based on those forum posts:

```
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    set1:
      - ['interface GigabitEthernet1/0/35', 'description TEST PHONE']
      - ['interface GigabitEthernet1/0/36', 'description TEST PHONE']
      - ['interface GigabitEthernet1/0/37', 'description *W137']
      - ['interface GigabitEthernet1/0/38', 'description *W138']
      - ['interface GigabitEthernet1/0/39', 'description *W139']
      - ['interface GigabitEthernet1/0/40', 'description *W140']
    set2:
      - ['interface GigabitEthernet1/0/37', 'description *W137']
      - ['interface GigabitEthernet1/0/38', 'description *W138']
  tasks:
    - name: remove old ntp servers
      shell: echo {{ ntp_old_server[0] }} >> tmp.out
      with_list: '{{ set1 | difference(set2) }}'
      loop_control:
        loop_var: ntp_old_server
```
```
PLAY [localhost] ***************************************************************

TASK [remove old ntp servers] **************************************************
changed: [localhost] => (item=[u'interface GigabitEthernet1/0/35', u'description TEST PHONE'])
changed: [localhost] => (item=[u'interface GigabitEthernet1/0/36', u'description TEST PHONE'])
changed: [localhost] => (item=[u'interface GigabitEthernet1/0/39', u'description *W139'])
changed: [localhost] => (item=[u'interface GigabitEthernet1/0/40', u'description *W140'])

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0  
```
```
[reid@laptop ~/git]$ cat tmp.out
interface GigabitEthernet1/0/35
interface GigabitEthernet1/0/36
interface GigabitEthernet1/0/39
interface GigabitEthernet1/0/40
```

**Comment by nrwahl2** [comment]
Everything in `ansible/lib/ansible/plugins/lookup` can be used in a `with_*` construction. Unfortunately, some of them are not yet documented.

**Comment by karrots** [comment]
The SE examples are not quite the same. The regex I use only returns one capture group the examples return two captures per item. This would make them a set. That said your example did get me thinking and I modified it to match my use case more closely. It seems to work which leads me to believe the issue is not with the `difference()` filter but with the `regex_findall()`

My playbooks worked fine with version 2.2 and 2.3 it was only after upgrading to 2.4 that the issue started.

I'll see if I can work up a better test case with dummy data.

**Comment by karrots** [comment]
Forgot to post the closer playbook.

```YAML
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    set1:
      - 127.0.0.1
      - 127.0.0.2
      - 127.0.0.3
      - 127.0.0.4
      - 127.0.0.5
      - 127.0.0.6
    set2:
      - 127.0.0.1
      - 127.0.0.2
  tasks:
    - name: remove old ntp servers
      shell: echo {{ ntp_old_server }} >> tmp.out
      with_items: '{{ set1 | difference(set2) }}'
      loop_control:
        loop_var: ntp_old_server
```

**Comment by karrots** [comment]
This playbook produces the error I am seeing.

```YAML
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    config: 'ntp server 127.0.0.1\nntp server 127.0.0.2\nntp server 127.0.0.3\nntp server 127.0.0.4\nntp server 127.0.0.5\n'
    ntp_servers:
      - 127.0.0.1
      - 127.0.0.2
  tasks:
    - name: get current configured ntp servers
      set_fact: _servers="{{ config | regex_findall('ntp server (\S+)\\n') }}"

    - name: remove old ntp servers
      shell: echo {{ ntp_old_server }} >> tmp.out
      with_items: '{{ _servers | difference(ntp_servers) }}'
      loop_control:
        loop_var: ntp_old_server
```

**Comment by karrots** [comment]
Ok so I am not sure what is going on. I rolled back ansible versions to 2.3 and 2.2 and this example had the same results. I'll have to look in my repo for other changes that may have caused this. Pretty sure none of the affected roles were modified recently.

**Comment by karrots** [comment]
The reason the last playbook fails is the regex is not working quite right in that sample. Unsure why exactly as the config is nearly a straight copy paste. I setup another playbook with non-regex dummy data taken from my failing play. It works fine in the test suite. I guess there is the possibility it's an `ios_config` issue and not a general `with_items` issue.

**Comment by nrwahl2** [comment]
Curious, did you also try it with `with_list`? Both `with_list` and `with_items` work identically for me with our test playbook (the one with `set1` and `set2`). I wish I could play around with `ios_config` to help troubleshoot there. Alas.

**Comment by karrots** [comment]
I did it starts returning single letters from the word `set()`.

On Aug 26, 2017 12:16 AM, "Reid Wahl" <notifications@github.com> wrote:

Curious, did you also try it with with_list? Both with_list and with_items
work identically for me with our test playbook (the one with set1 and set2).
I wish I could play around with ios_config to help troubleshoot there. Alas.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ansible/ansible/issues/28683#issuecomment-325092384>,
or mute the thread

**Comment by nrwahl2** [comment]
This is going to make both of us angry if it works. Try switching your single and double quotes on your `set_fact`, and putting `_servers` on the next line as a dict key. I wasn't seeing the same `item=set()` behavior as you were, but this may be a clue. See my four test cases below.

If this works, I don't know why it's not being parsed correctly when the fact is set inline. Someone with more experience writing playbooks or deeper into the code would need to answer that.

```
[reid@laptop ~/git]$ cat single-inside-sep-line.yml
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    config: 'ntp server 127.0.0.1\nntp server 127.0.0.2\nntp server 127.0.0.3\nntp server 127.0.0.4\nntp server 127.0.0.5\n'
    ntp_servers:
      - 127.0.0.1
      - 127.0.0.2
  tasks:
    - name: get current configured ntp servers
      set_fact:
         _servers: "{{ config | regex_findall('ntp server (\S+)\\n') }}"

    - name: remove old ntp servers
      shell: echo {{ ntp_old_server }} >> tmp.out
      with_items: '{{ _servers | difference(ntp_servers) }}'
      loop_control:
        loop_var: ntp_old_server


[reid@laptop ~/git]$ ansible-playbook single-inside-sep-line.yml -i hosts.ini 
ERROR! Syntax Error while loading YAML.


The error appears to have been in '/home/reid/git/single-inside.yml': line 13, column 60, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      set_fact:
         _servers: "{{ config | regex_findall('ntp server (\S+)\\n') }}"
                                                           ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

exception type: <class 'yaml.scanner.ScannerError'>
exception: while parsing a quoted scalar
  in "<unicode string>", line 13, column 20
found unknown escape character
  in "<unicode string>", line 13, column 60
```


```
[reid@laptop ~/git]$ cat single-outside-sep-line.yml
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    config: 'ntp server 127.0.0.1\nntp server 127.0.0.2\nntp server 127.0.0.3\nntp server 127.0.0.4\nntp server 127.0.0.5\n'
    ntp_servers:
      - 127.0.0.1
      - 127.0.0.2
  tasks:
    - name: get current configured ntp servers
      set_fact:
         _servers: '{{ config | regex_findall("ntp server (\S+)\\n") }}'

    - name: remove old ntp servers
      shell: echo {{ ntp_old_server }} >> tmp.out
      with_items: '{{ _servers | difference(ntp_servers) }}'
      loop_control:
        loop_var: ntp_old_server


[reid@laptop ~/git]$ ansible-playbook single-outside-sep-line.yml -i hosts.ini 

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [get current configured ntp servers] *************************************************************************************************************************************************************************
ok: [localhost]

TASK [remove old ntp servers] *************************************************************************************************************************************************************************************
changed: [localhost] => (item=127.0.0.3)
changed: [localhost] => (item=127.0.0.4)
changed: [localhost] => (item=127.0.0.5)

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   
```

```
[reid@laptop ~/git]$ cat single-inside-same-line.yml 
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    config: 'ntp server 127.0.0.1\nntp server 127.0.0.2\nntp server 127.0.0.3\nntp server 127.0.0.4\nntp server 127.0.0.5\n'
    ntp_servers:
      - 127.0.0.1
      - 127.0.0.2
  tasks:
    - name: get current configured ntp servers
      set_fact: _servers="{{ config | regex_findall('ntp server (\S+)\\n') }}"

    - name: remove old ntp servers
      shell: echo {{ ntp_old_server }} >> tmp.out
      with_items: '{{ _servers | difference(ntp_servers) }}'
      loop_control:
        loop_var: ntp_old_server

[reid@laptop ~/git]$ ansible-playbook single-inside-same-line.yml -i hosts.ini 

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [get current configured ntp servers] *************************************************************************************************************************************************************************
ok: [localhost]

TASK [remove old ntp servers] *************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

```
[reid@laptop ~/git]$ cat single-outside-same-line.yml 
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    config: 'ntp server 127.0.0.1\nntp server 127.0.0.2\nntp server 127.0.0.3\nntp server 127.0.0.4\nntp server 127.0.0.5\n'
    ntp_servers:
      - 127.0.0.1
      - 127.0.0.2
  tasks:
    - name: get current configured ntp servers
      set_fact: _servers="{{ config | regex_findall('ntp server (\S+)\\n') }}"

    - name: remove old ntp servers
      shell: echo {{ ntp_old_server }} >> tmp.out
      with_items: '{{ _servers | difference(ntp_servers) }}'
      loop_control:
        loop_var: ntp_old_server

[reid@laptop ~/git]$ ansible-playbook single-outside-same-line.yml -i hosts.ini 

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [get current configured ntp servers] *************************************************************************************************************************************************************************
ok: [localhost]

TASK [remove old ntp servers] *************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by nrwahl2** [comment]
FWIW I almost always put my dict keys on separate lines just because inline gives me syntax highlighting problems with nested quotes ;)

**Comment by karrots** [comment]
So yeah that change of lines fixes the regex in the test suite. The original way with the `=` works fine in production based on `-vvv` output. The odd thing is the results without `-vvv` are the same in the end. Just one doesn't show any data being inserted into `_server`.

**Comment by nrwahl2** [comment]
To make sure I'm understanding, is the same issue still present in production? If so, could you post the `-vvv` output of the task here (at least for the next person who comes along ;) )?

**Comment by karrots** [comment]
The problem was still in production. I did figure out the issue though with the help of `git bisect`. I believe the issue is because the difference between the two sets is nothing. The test cases always had some result.  Below is a test case which emulates my issue more closely. So this doesn't look like a bug but an issue with my role. Just surprised I haven't run into it yet with my testing as I was building things out.

```YAML
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    config: 'ntp server 127.0.0.1\nntp server 127.0.0.2\nntp server 127.0.0.3\n'
    ntp_servers:
      - 127.0.0.1
      - 127.0.0.2
      - 127.0.0.3
  tasks:
    - name: get current configured ntp servers
      set_fact: _servers='{{ config | regex_findall("ntp server (\S+)\\n") }}'

    - name: remove old ntp servers
      shell: echo {{ ntp_old_server }} >> tmp.out
      with_items: '{{ _servers | difference(ntp_servers) }}'
      loop_control:
        loop_var: ntp_old_server

```

**Comment by nrwahl2** [comment]
I was thinking exactly that while I was lying in bed this morning, and then I forgot by the time I got to the computer. I'm glad you figured it out! Kudos.

**Comment by karrots** [comment]
For posterity, I should say the fix for this is to add the following line to the task.

```YAML
when: ntp_old_server is undefined
```
Not elegant but it works.

**Comment by karrots** [comment]
Actually, I miss typed that fix and it doesn't actually work. I am unsure how to work around this issue.

**Comment by nrwahl2** [comment]
I see in my emails that your initial fix involved `when: ntp_old_server is undefined`. Have you tried `when: ntp_old_server is defined`?

Also, I'm still having to put `_servers` on its own line to make it work on my box.

**Comment by karrots** [comment]
Yea, the trouble is its always defined. I think that's part of the problem. The difference operation is returning an empty set when it should be returning nothing.

**Comment by karrots** [comment]
My issue looks related to this issue #10098

**Comment by karrots** [comment]
The following change seems to have fixed the issue.
```diff
---      with_items: "{{ _servers | difference(ntp_servers)}}"
+++      with_items: "{{ _servers | difference(ntp_servers) | list}}"
```

Full code
```YAML
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    config: "ntp server 127.0.0.1\nntp server 127.0.0.2\nntp server 127.0.0.3\nntp server 127.0.0.4\n"
    ntp_servers:
      - 127.0.0.1
      - 127.0.0.2
      - 127.0.0.3
      - 127.0.0.4
  tasks:
    - name: get current configured ntp servers
      set_fact: _servers='{{ config | regex_findall("ntp server (\S+)\\n") }}'


    - name: remove old ntp servers
      shell: echo {{ ntp_old_server }} >> tmp.out
      with_items: "{{ _servers | difference(ntp_servers) | list}}"
      loop_control:
        loop_var: ntp_old_server
```
