### ISSUE TITLE
junos_config: unable to delete interfaces (UnicodeEncodeError)

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#28681]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_config

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /*****/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### CONFIGURATION

Ansible.cfg:
[defaults]
host_key_checking=False
timeout = 10

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

Easy to reproduce, just launch the following play, the workaround found is to replace line 231 `config = str(match.text)` by `config = match.text.encode('utf-8')` in the junos network module named: junos_config.py (see output error for more details)

```yaml
- name: delete ipv4 address
  block:
    - junos_config:
        lines:
        - delete interfaces lo0 unit 0 family inet address 7.7.7.3/32
        comment: updated by Ansible
        provider: "{{ netconf }}"
      register: result
      notify: changed_config
  rescue:
    - debug: msg='Error removing ipv4 address'

- debug:
    var: result
    verbosity: 4
```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_3ikpwv/ansible_module_junos_config.py", line 349, in <module>
    main()
  File "/tmp/ansible_3ikpwv/ansible_module_junos_config.py", line 339, in main
    diff = configure_device(module, warnings)
  File "/tmp/ansible_3ikpwv/ansible_module_junos_config.py", line 271, in configure_device
    candidate = filter_delete_statements(module, candidate)
  File "/tmp/ansible_3ikpwv/ansible_module_junos_config.py", line 231, in filter_delete_statements
    config = str(match.text)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 43581-43583: ordinal not in range(128)

fatal: [jun]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_3ikpwv/ansible_module_junos_config.py\", line 349, in <module>\n    main()\n  File \"/tmp/ansible_3ikpwv/ansible_module_junos_config.py\", line 339, in main\n    diff = configure_device(module, warnings)\n  File \"/tmp/ansible_3ikpwv/ansible_module_junos_config.py\", line 271, in configure_device\n    candidate = filter_delete_statements(module, candidate)\n  File \"/tmp/ansible_3ikpwv/ansible_module_junos_config.py\", line 231, in filter_delete_statements\n    config = str(match.text)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 43581-43583: ordinal not in range(128)\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
