### ISSUE TITLE
lambda role doesn't accept AWS GovCloud ARNs

### ISSUE THREAD

**Issue by rfrench42** [ansible/ansible#28699]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible/lib/ansible/modules/cloud/amazon/lambda.py

##### ANSIBLE VERSION
ansible 2.3.2.0

##### CONFIGURATION
standard

##### OS / ENVIRONMENT
AWS Ubuntu 16.04
Linux 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

AWS GovCloud (us-gov-west-1)

##### SUMMARY

Attempting to set the role to either just the role name or the full ARN fails the lambda deployment or update because AWS can't find the specified role.

Looking in the lambda.py module, the code assumes the region partition to ever only be 'aws'.  However, the us-gov-west-1 region partition is 'aws-us-gov'.

##### STEPS TO REPRODUCE

```
    tasks:
        - name: Deploy hello world
            lambda:
            name: "run_hello_world"
            runtime: "python27"
            s3_bucket: "my_bucket"
            s3_key: "my_key"
            role: "hello_world_role"

        - name: Deploy hello world Again
            lambda:
                name: "run_hello_world"
                runtime: "python27"
                s3_bucket: "my_bucket"
                s3_key: "my_key"
                role: "arn:aws-us-gov:iam::1234567890:role/hello_world_role"
```

##### EXPECTED RESULTS
Lambda function to be created 

##### ACTUAL RESULTS

```
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "An error occurred (ValidationException) when calling the UpdateFunctionConfiguration operation: 1 validation error detected: Value 'arn:aws:iam::1234567890:role/arn:aws-us-gov:iam::1234567890:role/hello_world_role' at 'role' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:(aws|aws-us-gov):iam::\\d{12}:role/?[a-zA-Z_0-9+=,.@\\-_/]+"}
```
