### ISSUE TITLE
GCE : unable to attach existing Static External IP to Instance during launch

### ISSUE THREAD

**Issue by ksingh7** [ansible/ansible#28707]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- gce
##### ANSIBLE VERSION

```
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

- no change in ansible.cfg

##### OS / ENVIRONMENT

MACos Sierra 10.12.6

##### SUMMARY

- An existing External Static IP is not getting attached to an instance launched using gce ansible module 
##### STEPS TO REPRODUCE

```yaml
    - name: Provision GCE instance
      gce:
        instance_names: "{{ instance_name }}"
        machine_type: "{{ instance_machine_type }}"
        image: "{{ image }}"
        zone: "{{ zone }}"
        tags: "{{ tags }}"
        state: "{{ state }}"
        external_ip: "{{ external_ip }}"
        preemptible: "{{ preemptible }}"
      register: gce_instance
```
```
$ cat group_vars/all | grep -i external_ip | head -1
external_ip: "ks-test-eip-1"
$
```

##### EXPECTED RESULTS

- After creating a fresh instance using ansible gce module, static EIP should get attach to the new instance. 
- The new instance should NOT have ephemeral IP ( when static EIP is provided in module parameter)
- gce module should output static external IP as value for ``public_ip``
##### ACTUAL RESULTS

```
TASK [Provision GCE instance] **************************************************
changed: [127.0.0.1]

TASK [debug] *******************************************************************
ok: [127.0.0.1] => {
    "gce_instance": {
        "changed": true,
        "instance_data": [
            {
                "disks": [
                    "ks-test-instance-3"
                ],
                "image": "centos-7-v20170816",
                "machine_type": "n1-standard-1",
                "metadata": {},
                "name": "ks-test-instance-3",
                "network": "default",
                "private_ip": "10.128.0.4",
                "public_ip": "104.197.11.217",
                "status": "RUNNING",
                "subnetwork": "default",
                "tags": [
                    "lamp",
                    "test"
                ],
                "zone": "us-central1-a"
            }
        ],
        "instance_names": [
            "ks-test-instance-3"
        ],
        "state": "present",
        "zone": "us-central1-a"
    }
}

```
- The ``public_ip`` in the above debug output is ephemeral IP and NOT static External IP. Though I do have static External IP precreated in GCP dashboard with the name ``ks-test-eip-1``
