### ISSUE TITLE
yum task failed for "IOError: [Errno 9] Bad file descriptor"

### ISSUE THREAD

**Issue by karniemi** [ansible/ansible#28720]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

yum or some common libs

##### ANSIBLE VERSION

```
ansible 2.3.1.0-3.el7
python.x86_64 2.7.5-48.el7
```

##### CONFIGURATION

ANSIBLE_STDOUT_CALLBACK=debug
ANISBLE_HOST_KEY_CHECKING=False

##### OS / ENVIRONMENT

RHEL7.3
##### SUMMARY

yum task failed for "IOError: [Errno 9] Bad file descriptor". In our CI we are running a playbook against a cluster of 13 virtual machines. Now in one CI run, two vms had suddenly failed for "IOError: [Errno 9] Bad file descriptor"-error for a yum module task, which installs some packages from a readily configured repo(...so we are only passing a list of packages with "state=present" for the yum module). Error msg was (typed, not copy-pasted):
```
[stdout]: TASK [server-role : ensure packages are installed] ****************
[stderr]: close failed in file object desctructor:
[stderr]: IOError: [Errno 9] Bad file descriptor
[stdout]: An exception occurred during task execution. To see full traceback use -vvv. The error was IOError: [Errno 9] Bad file descriptor
[stdout]: fatal: [ourservername]: FAILED! => {
[stdout]:       "failed": true
[stdout]: }
[stdout]:
[stdout]: MSG:
[stdout]:
[stdout]: Unexpected failure during module execution.
```
We've only seen this one time now, and we are running 10s of CI runs per day, so maybe it's some sort of race condition in running the commands and closing some file descriptors. I could not find anything suspicious in /var/log/messages of the ansible controller/managed nodes at the time of the failure. At the time of the error message, there was no "yum[xxx] Installed: <package name>" messages in the failed nodes either.. 

(We would have wanted to get verbose ansible logs on a file, but leave the console logs at the normal level...that way we would have verbose logs available for cases like this, but still could have the easy-for-eyes-logs at Jenkins console...but there seems to be no means for that.)

##### STEPS TO REPRODUCE

Not known.

```yaml

```

##### EXPECTED RESULTS

Yum task should have successful.
##### ACTUAL RESULTS

Yum task did not succeed, and the error msg is not that good in pointing towards the problem.

```

```

**Comment by alikins** [comment]
What does the bit of playbook defining that task look like?

Is it using 'package' or 'yum' for the task?

Is it using a 'with_*' for looping?

**Comment by alikins** [comment]
The error would be coming from lib/ansible/executor/task_executor.py:162, but the the exception
handling there is very vague and broad, so lots of potential root causes.

(another needs_info, are the tasks using when: conditionals?)
Or the tasks using 'when' conditionals?

**Comment by karniemi** [comment]
Hi, I'll try to summarize our setup... and point out that failed task.

I want to emphasize: it failed only in one round and has succeeded tens of times before and after. As background for the our ansible setup: we have several similar labs, so we've kept the inventory easy for the installation personnel...which has the cost of making the playbooks a bit more complicated. Also, we have tightly roled servers in the cluster, and some of the complication is due to poor parallel installation capabilities of ansible: with our setup below, we are able to act parallel on all the different server_roles. I minimized the example from our real setup, which has lots of more services, roles and servers. 

----
lab1 inventory:
```
[role1_servers]
server1
[role2_servers]
server2

[all_servers:children]
role1_servers
role2_servers
```

playbook:
```
- name: set server_role fact for role1 servers
  hosts: role1_servers
  gather_facts: no
  tasks:
    - set_fact: server_role=role1
- name: set server_role fact for role2 servers
  hosts: role2_servers
  gather_facts: no
  tasks:
    - set_fact: server_role=role2
- name: install role specific services
  hosts: all_servers
  gather_facts: no
  roles:
     - my_sweet_server
```
roles/my_sweet_server/vars/role1.yml:
```
services:
  - service: microservice1
    crm_standard: lsb
    version: "123"
```
roles/my_sweet_server/vars/role2.yml:
```
services:
  - service: microservice2
    crm_standard: lsb
    version: "321"
```

roles/my_sweet_server/tasks/main.yml:
```
- include_vars: roles/my_sweet_server/vars/{server_role}.yml
- name: resolve package names and versions
  set_fact: pacs="{{ pacs|default([])}} + [ '{{item.0 }}-{{item.1 }}' ]"
  with_together:
    - "{{ services|map(attribute='service')|list }}"
    - "{{ services|map(attribute='service')|version }}"

- name: ensure server packages are installed ##### This task had  the (seemingly) random failure! #####
  yum: name={{ item }} state=present
  with_items: "{{ pacs }}"
...
```

I hope this answers the questions :-)...

**Comment by tanshanshan** [comment]
```
- hosts: k8s-cluster:etcd
  any_errors_fatal: true
  gather_facts: true
  vars:
    # Need to disable pipelining for bootstrap-os as some systems have requiretty in sudoers set, which makes pipelining
    # fail. bootstrap-os fixes this on these systems, so in later plays it can be enabled.
    ansible_ssh_pipelining: false
  roles:
    - { role: kargo-defaults}
    - { role: bootstrap-os, tags: bootstrap-os}
```

I got the same problem:
```
TASK [Gathering Facts] *********************************************************
ok: [host.1]
ok: [host.4]
ok: [host.2]
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 9] Bad file descriptor
fatal: [host.3]: FAILED! => {"failed": true, "msg": "Unexpected failure during module execution.", "stdout": ""}

```
