### ISSUE TITLE
Add option to force handlers to run even when no tasks are changed

### ISSUE THREAD

**Issue by marceloslacerda** [ansible/ansible#28722]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
n/a

##### ANSIBLE VERSION
```
ansible 2.2.1.0
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
I explain my problem in detail [here](https://stackoverflow.com/questions/45916911/running-an-ansbile-handler-as-an-one-time-thing/45917807#45917807) but sumarizing:

I wished that there was a way to tell ansible to run a single handler (or many) from a playbook without changing it.

At IRC someone suggested to use tags to force that behavior, and I thought that the idea was pretty cool because you could tag related handlers (or even tasks) and they would run when you need. Sadly I wasn't able to make it work (maybe it's a bug?).

##### STEPS TO REPRODUCE
Here's the playbook that I used to test that behavior.

```yaml
- hosts: 127.0.0.1
  handlers:
  - name: handler a
    shell: echo this
    tags:
      - xtag
  - name: handler b
    shell: echo that
    tags:
      - xtag

```

##### EXPECTED RESULTS
Both **echo this** and **echo that** are run

##### ACTUAL RESULTS
No handlers are run
```
$ ansible-playbook --tag "xtag" test.yml 

PLAY [127.0.0.1] ***************************************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0
```
