### ISSUE TITLE
nxos_config logs your password to syslog in plaintext

### ISSUE THREAD

**Issue by JakeDEvans** [ansible/ansible#28724]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_config by default will log your username and password 

##### ANSIBLE VERSION
```
2.3.0.0
```

##### CONFIGURATION
N/A
##### OS / ENVIRONMENT
N/A

##### SUMMARY
Default logging too verbose, includes data that should not be logged.

##### STEPS TO REPRODUCE

```yaml
- name: Deploy vlan interface config
  nxos_config:
    host: "{{ inventory_hostname }}"
    src: "{{ config_folder }}/vlan_interfaces.j2"
    provider: "{{ nxos_provider_cli }}"

```

##### EXPECTED RESULTS
log without password.

##### ACTUAL RESULTS
```
Aug 28 11:06:58 ansible-control.example.com ansible-nxos_config[16814]: Invoked with force=False replace=line use_ssl=None port=None transport=cli before=None parents=None provider={'username': 'jevans', 'ssh_keyfile': None, 'host': 'nxosdevice.example.com', 'timeout': None, 'use_ssl': None, 'password': 'MySecurePassword', 'validate_certs': None, 'port': None, 'transport': 'cli'} save=False config=None match=line username=None defaults=False after=None host=nxosdevice.example.com password=NOT_LOGGING_PARAMETER src=interface eth1/1-48
```
