### ISSUE TITLE
lineinfile with_items does not insert value of line if it occurred before

### ISSUE THREAD

**Issue by dirks** [ansible/ansible#28721]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lineinfile in combination with_items

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### SUMMARY
Ansible does not insert line if the identical value has been used before in loop, but only if the value of line is different.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
    
  tasks:
    - name: create test file
      copy:
        dest: /tmp/example.txt
        content: |
          1
          
          2
          
          3
          
          4
          

    - name: broken lineinfile
      lineinfile:
        path: /tmp/example.txt
        insertafter: "{{ item.regex }}"
        line: "{{ item.replace }}"
        unsafe_writes: yes
      with_items:
        - { regex: '1', replace: 'bar' }
        - { regex: '2', replace: 'bar' }
        - { regex: '3', replace: 'br' }
        - { regex: '4', replace: 'bar' }

```

##### EXPECTED RESULTS
```
1
bar

2
bar

3
br

4
bar
```

##### ACTUAL RESULTS
```
1
bar

2

3
br

4
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/lineinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/lineinfile.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ahtik @dhozac
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
Can you please test with #33393 to see if that fixes the issue? Thanks!

**Comment by dirks** [comment]
#33393 fixes the issue, thanks. :+1:

**Comment by samdoran** [comment]
Awesome! Thank you for confirming. I'll work on getting this merged. Should make the 2.4.3 release.

**Comment by samdoran** [comment]
I didn't get this in to 2.4.3 (I was out on paternity leave) but this will be in 2.4.4.

**Comment by jsteel44** [comment]
This breaks my config where I use both regexp AND insertafter; the regexp doesn't seem to match any more, so on every subsequent run it inserts duplicate lines:

```
- name: my.cnf options
  lineinfile:
    dest: "{{ mariadb_config }}"
    regexp: "^{{ item.option }}="
    line: "{{ item.option }}={{ item.value }}"
    insertafter: '^\[{{ item.section }}\]'
  with_items:
     - { section: mysqld, option: innodb_log_file_size, value: "{{ innodb_log_file_size }}" }
     - { section: mysqld, option: default-storage-engine, value: innodb }
     - { section: mysqld, option: max_allowed_packet, value: 128M }
```

```
--- before: /etc/my.cnf (content)
+++ after: /etc/my.cnf (content)
@@ -1,4 +1,5 @@
 [mysqld]
+default-storage-engine=innodb
 skip-name-resolve
 max_allowed_packet=128M
 default-storage-engine=innodb
```
