### ISSUE TITLE
win_shortcut: idempotency issues

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#28758]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_shortcut

##### ANSIBLE VERSION
v2.4

##### SUMMARY
Specific shortcuts to *internal* paths are not idempotents.

PS I used to have plenty of more cases that were non-idempotent, but these have all been fixed with the recent updates to **win_shortcut**. This is the only remaining.

##### STEPS TO REPRODUCE
Use the following task:
```yaml
  - name: Add shortcut to Recycle Bin
    win_shortcut:
      desc: Prullenbak
      src: shell:RecycleBinFolder
      dest: '%Public%\Desktop\Prullenbak.lnk'
      icon: ,0
```

##### EXPECTED RESULTS
Causes a change the first time, no change every subsequent run.

##### ACTUAL RESULTS
Always causes a change.
