### ISSUE TITLE
win_regedit: Using dword 0xffffffff displays value -1

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#28759]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_regedit

##### ANSIBLE VERSION
v2.4

##### SUMMARY
This is a small cosmetic issue, where the value provided is not displayed as expected in the --diff output

##### STEPS TO REPRODUCE
Use this playbook
```yaml
- hosts: computer61
  gather_facts: no
  tasks:
  - win_regedit:
      key: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
      value: SMB1
      data: 0xffffffff
      datatype: dword
      
  - win_regedit:
      key: HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters
      value: SMB1
      data: 0x0
      datatype: dword
```

##### EXPECTED RESULTS
I expected to see the value provided in the diff output.

##### ACTUAL RESULTS
```
[dag@moria crombeen]$ ansible-playbook test/test148.yml --diff

PLAY [computer61] **********************************************************************************

TASK [win_regedit] *********************************************************************************
[HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters]
-"SMB1" = "DWord:0"
+"SMB1" = "DWord:-1"               
changed: [computer61]

TASK [win_regedit] *********************************************************************************
[HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters]
-"SMB1" = "DWord:-1"
+"SMB1" = "DWord:0"               
changed: [computer61]

PLAY RECAP *****************************************************************************************
computer61                 : ok=2    changed=2    unreachable=0    failed=0   
```
