### ISSUE TITLE
Bug Fix & Feature Request for Kubernetes Module

### ISSUE THREAD

**Issue by nelson-cf** [ansible/ansible#28788]
##### ISSUE TYPE
- Bug Fix (SSL on GET requests)
&
 - Feature Idea.  ( Supporting something other than Basic Authentication)

##### COMPONENT NAME
Kubernetes
ansible/lib/ansible/modules/clustering/kubernetes.py

##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 6510ed3587) last updated 2017/08/28 10:45:36 (GMT -700)
  config file = None
  configured module search path = [u'/Users/nhernandez/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nhernandez/Documents/repos/ansible/lib/ansible
  executable location = /Users/nhernandez/Documents/repos/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
installed via brew
also attempted via git clone of ansible repository and sourcing ./hacking/env-setup

##### OS / ENVIRONMENT
OSX Sierra 10.12.6

##### SUMMARY

- SSL get requests are not working with python 2.7 on OS X

- Edge release (via git pull) does not work with python3, therefor any progress on this module since last stable release (some of which is critical for an operational kubernetes cluster in production) can not be used from OSX.

- Basic Authentication, is almost all but depreciated within the Kubernetes community.  Every time you ask a Kube developer, they will suggest not using Basic Authentication.  Many existing prod clusters do not have basic auth turned on.  It is not supported by minikube, an important tool for developers running an SOA.  

- Running a cluster insecurely is definitely a depreciated process.

Any of the other authentication methods would be great - bearer token, certificate, etc.

If the above ssl issue was fixed, and another authentication method permitted, Ansible on OS X + Minikube would be an excellent combination for driving developer adaptation of Ansible as part of their every day practices for starting up services.

##### STEPS TO REPRODUCE
brew install ansible
ansible-playbook create-kubernetes-deployment.yaml

where create-kubernetes-deployment.yaml:
```yaml
---
- hosts: localhost
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  gather_facts: false
  tasks:
    - name: Create a kubernetes deployment
      kubernetes:
        api_endpoint: 192.168.99.100:8443
        validate_certs: off
        file_reference: service-deploy.yaml
        state: present
```

##### EXPECTED RESULTS
I expected to get an "unauthorized" response, which would mean Ansible is at least capable of making requests against a local cluster running OS X. If this was at least fixed there is probably another workaround the authentication issues.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "headers": {"Authorization": "Basic YWRtaW46", "Content-Type": "application/json"}, "method": "POST", "msg": "Failed to execute the API request: Request failed: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>", "url": "https://192.168.99.100:8443/apis/extensions/v1beta1/namespaces/default/deployments"}
```
