### ISSUE TITLE
Win_Updates not working with Register

### ISSUE THREAD

**Issue by zachgatesak** [ansible/ansible#28902]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Win_updates

##### ANSIBLE VERSION
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

##### CONFIGURATION
Base configuration

##### OS / ENVIRONMENT
Windows Target: Windows Server 2016 - Datacenter

##### SUMMARY
Unable to register the output from a win_updates: state=searched task

##### STEPS TO REPRODUCE
Simply Run the below playbook

```
---
- hosts: win2 win1
  gather_facts: yes

  tasks:
    - name: Checking for Critical Patches and producing a list of available items
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Application
          - Tools
          - ServicePacks
          - Updates
        state: searched
        register: result
        log_path: C:\ansible.txt
    - debug: var=result

```

##### EXPECTED RESULTS
I'm able to see the output when running the playbook with -vvvv
```
changed: [172.16.1.94] => {
    "changed": true,
    "found_update_count": 1,
    "installed_update_count": 0,
    "reboot_required": false,
    "updates": {
        "fbf6de89-bf23-48b9-aef0-aae76f268708": {
            "id": "fbf6de89-bf23-48b9-aef0-aae76f268708",
            "installed": false,
            "kb": [
                "4034658"
            ],
            "title": "2017-08 Cumulative Update for Windows Server 2016 for x64-based Systems (KB4034658)"
        }
    }
}
```
However in the section where **register** the output for later parsing I get the following:
```
ok: [172.16.1.94] => {
    "result": "VARIABLE IS NOT DEFINED!"
}

```
##### ACTUAL RESULTS

Register tasks outputs: Variable is not defined.

```
ok: [172.16.1.94] => {
    "result": "VARIABLE IS NOT DEFINED!"
}
```

**Comment by zachgatesak** [comment]
Went ahead and tested this against the win_ping module and compared it with the pin module on a normal linux box and it seems isolated to the win_updates module.

```
---
- hosts: self
  gather_facts: no
  tasks:
    - name: Testing Ubuntu
      ping:
      register: output
    - debug: var=output.changed // Works!
- hosts: win2
  gather_facts: no
  tasks:
    - name: testing Windows
      win_ping:
      register: output_win
    - debug: var=output_win.changed // Works!
```
output (truncated)
```
TASK [debug] ok: [self] => {
    "output.changed": false
}
TASK [debug]  ok: [172.16.1.94] => {
    "output_win.changed": false
}
```

**Comment by ansibot** [comment]
cc @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nitzmahone** [comment]
Your `register` is improperly indented and is being sent to the module as an arg. `register` is a task directive and needs to be lined up with the module name, not indented underneath it. This is a known shortcoming of the Windows module_utils right now, since we don't fail on unknown args (if this were a Python module, you would've gotten the error that `register` is not a valid module arg for the module).

**Comment by zachgatesak** [comment]
Thanks for your response @nitzmahone. I haven't seen register used at the ***task*** level before. From the documentation I've only found example of using it as an argument for a module: e.g. 

```
- name: registered variable usage as a with_items list
  hosts: all

  tasks:

      - name: retrieve the list of home directories
        command: ls /home
        register: home_dirs

      - name: add home dirs to the backup spooler
        file: path=/mnt/bkspool/{{ item }} src=/home/{{ item }} state=link
        with_items: "{{ home_dirs.stdout_lines }}"
        # same as with_items: "{{ home_dirs.stdout.split() }}"
# Source -> http://docs.ansible.com/ansible/latest/playbooks_conditionals.html#register-variables
```

I also showed an example of the ping module that seems to be working. Can you provide an example of the win_updates that should work?
