### ISSUE TITLE
issue with ansible connected with aws 

### ISSUE THREAD

**Issue by tianyuan848192** [ansible/ansible#28912]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

goldwind.com.cn
##### ANSIBLE VERSION

```
ansible 2.3.2.0
```

##### CONFIGURATION

ANSIBLE_*
##### OS / ENVIRONMENT

amazonlinux
##### SUMMARY

connect aws with error "No Authentication Handler found" 
##### STEPS TO REPRODUCE

When i try to download my file form aws s3, i have got these error. my ansible is an AWS EC2 with full access EC2ROLE to my bucket. However, when i change my mind and give access key and security key both in playbook and aws configure, and the playbooks work fine. 

So i guess ansible in server side is actually got the keys form playbook or aws configure file within .aws/configure, and send these message to the slave node to execute the action. 

I am not quite sure about my idea, could you help me to verified it, because in the Document i saw the explain of using AK/SK is like: 
"If not set then the value of the AWS_ACCESS_KEY_ID, AWS_ACCESS_KEY or EC2_ACCESS_KEY environment variable is used."

and i suppose using EC2Role is also a kind of environment.

```yaml

    - name: "download file"
      s3:
        bucket: ***************
        object: **********
        dest: **********
        mode: get
        region: ********
```

##### EXPECTED RESULTS

pls help me to check whether i am right, or if there is why to configured access by EC2Roles   
##### ACTUAL RESULTS

```

```
