### ISSUE TITLE
xml module: pretty_print for attributes

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#28920]
_From @Hubbitus on June 21, 2016 18:51_

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
xml

##### ANSIBLE VERSION
unknown

##### SUMMARY
I have tomcat context file which looks like:

```xml
<?xml version='1.0' encoding='utf-8'?>
<Context>

    <Resource type="javax.sql.DataSource"
              name="jdbc/UniDataDataSource"
              description="UniData Database"
              factory="org.apache.tomcat.jdbc.pool.DataSourceFactory"
              driverClassName="org.postgresql.Driver"
              url="jdbc:postgresql://localhost:5432/unidata"
              username="postgres"
              password="postgres"
              initialSize="10"
              maxActive="100"
              maxIdle="50"
              minIdle="10"
              suspectTimeout="60"
              timeBetweenEvictionRunsMillis="30000"
              minEvictableIdleTimeMillis="60000"
              testOnBorrow="true"
              validationQuery="SELECT 1"
              validationInterval="30000"
              removeAbandoned="true"
              removeAbandonedTimeout="180"
              logAbandoned="true"
              abandonWhenPercentageFull="50"
              jdbcInterceptors="ResetAbandonedTimer" />

</Context>
```

I want change their attributes, but do not loose formatting. Is it possible?

My playbook similar to (simplified):

```yaml
    - name: Provide database access to tomcat
      xml:
        file: context.xml.default
        pretty_print: True
        xpath: /Context/Resource[@name='{{item.name}}']
        attribute: "{{item.attribute}}"
        value: "{{item.value}}"
      with_items:
        - { name: 'jdbc/UniDataDataSource', attribute: url, value: 'test_attribute_value' }
```

And result in one string:

```xml
<?xml version='1.0' encoding='UTF-8'?>
<Context>
  <Resource type="javax.sql.DataSource" name="jdbc/UniDataDataSource" description="UniData Database" factory="org.apache.tomcat.jdbc.pool.DataSourceFactory" driverClassName="org.postgresql.Driver" url="test_attribute_value" username="postgres" password="postgres" initialSize="10" maxActive="100" maxIdle="50" minIdle="10" suspectTimeout="60" timeBetweenEvictionRunsMillis="30000" minEvictableIdleTimeMillis="60000" testOnBorrow="true" validationQuery="SELECT 1" validationInterval="30000" removeAbandoned="true" removeAbandonedTimeout="180" logAbandoned="true" abandonWhenPercentageFull="50" jdbcInterceptors="ResetAbandonedTimer"/>
</Context>
```

I understand what it is `Resource` tag with many attributes and no child elements. It there any possibility preserve formatting similar to initial state?

_Copied from original issue: cmprescott/ansible-xml#70_
