### ISSUE TITLE
Redis fact caching fails to handle cache expirations mid-run

### ISSUE THREAD

**Issue by dekimsey** [ansible/ansible#28937]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
redis.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.0.0
  config file = /home/dkimsey/redis/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
```
[defaults]
gathering = smart

# just demo a small amount please
gather_subset = virtual

fact_caching = redis
fact_caching_connection = localhost:6379:1
# 5s
fact_caching_timeout = 5

[privilege_escalation]
become=False
```

##### OS / ENVIRONMENT
RHEL 7/OS X

##### SUMMARY
The redis cache plugin will not return facts when the data expires mid-run. It raises a KeyError but that does not seem to trigger a re-gather-facts for those hosts. 

The jsonfile and in-memory facts appear to return the old, expired data.

I believe the desired behavior should be a KeyError in `smart` mode should trigger a re-gathering of facts for those hosts.

##### STEPS TO REPRODUCE

Using the aforementioned ansible.cfg settings, the following playbook will demo the expiring between plays. Note if one were to use jsonfile or no-cache (in-memory?) it works correctly and maintains the data the entire run.

**Playbook: `demo.yml`:**
```yaml

- hosts: localhost
  connection: local
  tasks:
      - name: Facts gathereed OK
        debug:
            var: ansible_date_time.epoch
      - name: Sleep for a few seconds
        command: sleep 2

- hosts: localhost
  connection: local
  tasks:
      - name: Facts from previous run OK
        debug:
            var: ansible_date_time.epoch
      - name: Sleep for 4s
        command: sleep 4

- hosts: localhost
  connection: local
  tasks:
      - name: Facts from previous run NOT OK
        debug:
            var: ansible_date_time.epoch
```

**Command:**
```
ansible-playbook -i localhost, ./demo.yml
```

##### EXPECTED RESULTS

Either maintain consistency with other fact caching mechanisms and the fact should never change during the run.
OR
A more-correct solution I feel is the third Play should refresh expired facts.

##### ACTUAL RESULTS

```
$ ansible-playbook -i localhost, ./demo.yml

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [Facts gathereed OK] **********************************************************************************************
ok: [localhost] => {
    "ansible_date_time.epoch": "1504289061",
    "changed": false
}

TASK [Sleep for a few seconds] *****************************************************************************************
changed: [localhost]

PLAY [localhost] *******************************************************************************************************

TASK [Facts from previous run OK] **************************************************************************************
ok: [localhost] => {
    "ansible_date_time.epoch": "1504289061",
    "changed": false
}

TASK [Sleep for 4s] ****************************************************************************************************
changed: [localhost]

PLAY [localhost] *******************************************************************************************************

TASK [Facts from previous run NOT OK] **********************************************************************************
ok: [localhost] => {
    "ansible_date_time.epoch": "VARIABLE IS NOT DEFINED!",
    "changed": false
}

PLAY RECAP *************************************************************************************************************
localhost                  : ok=6    changed=2    unreachable=0    failed=0

```
