### ISSUE TITLE
encoding parameter in s3_sync

### ISSUE THREAD

**Issue by benbro** [ansible/ansible#28973]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
s3_sync

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
All

##### OS / ENVIRONMENT
All

##### SUMMARY
Followup to PR https://github.com/ansible/ansible/pull/28969
I suggest adding an optional encoding arg to the mime_map parameter.
Useful for gzipped js and css files (app.js.gz) from s3.
Web browsers need the ContentEncoding header. 

Currently it's only possible to add the mime (example from the docs):
```yml
- name: all the options
  s3_sync:
    bucket: tedder
    file_root: roles/s3/files
    mime_map:
      .yml: application/text
      .js: application/javascript
    key_prefix: config_files/web
    file_change_strategy: force
    permission: public-read
    include: "*"
    exclude: "*.txt,.*"
```
Example with the optional encoding arg (only relevant part is shown):
```yml
    mime_map:
      .yml: application/text
      .js:
        mime: application/javascript
        encoding: gzip
```

Another option is to have a separate encoding_map.
```yml
    mime_map:
      .yml: application/text
      .js.gz: application/javascript 
    encoding_map:
      .gz:
        encoding: gzip
```

Which one is better?

Is it possible to match ".js.gz" with mime_map/encoding_map or only the last part of the extension ".gz" ?
