### ISSUE TITLE
Allow string as src for junos_config module

### ISSUE THREAD

**Issue by sebastianw** [ansible/ansible#28989]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
modules/network/junos/junos_config

##### ANSIBLE VERSION
current devel branch

##### SUMMARY
Allow the `src` parameter in the `junos_config` module to be a string in addition to a config file.

##### STEPS TO REPRODUCE
Currently the `src` parameter in the `junos_config` module is only allowed to be a file. To use the template engine without temporary files it would be nice if the src parameter could also contain the config itself so it can be used with a template lookup like this for example:

```
- name: load configure file into device
  junos_config:
    src: "{{ lookup('template', 'my_junos_config.j2') }}"
    comment: update config
    provider: "{{ netconf }}"
```

##### EXPECTED RESULTS
Parse the template, update the device.

##### ACTUAL RESULTS
Feature currently not available. :)
