### ISSUE TITLE
Allow use of async on blocks

### ISSUE THREAD

**Issue by msl-kabo** [ansible/ansible#28997]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`block` and `async`

##### SUMMARY
It would be awesome if it was possible to use `async` with `block`s. I've got four things to set up, and they can be set up in parallel, but they have internal steps that have to be done in order.

Example use case:

```yaml
- name: build thing1
  async: 300
  poll: 0
  register: build1
  block:
    - name: clone # big repo, takes 30 secs
      git: repo=ssh://git@github.com/org/repo1.git dest=/source/repo1 version="master" accept_hostkey=yes
    - name: npm install # lots to install, takes a minute
      command: chdir=/source/repo1 npm install 
    - name: npm run build # takes 3 minutes
      shell: chdir=/source/repo2 npm run build
- name: build thing2
  async: 300
  poll: 0
  register: build2
  block:
    - name: clone
      git: repo=ssh://git@github.com/org/repo2.git dest=/source/repo2 version="master" accept_hostkey=yes
    - name: npm install
      command: chdir=/source/repo2 npm install 
    - name: npm run build # takes 3 minutes
      shell: chdir=/source/repo2 npm run build

# do other stuff, then at the end:

- name: Wait for build1 to complete
  async_status: jid={{build1.ansible_job_id}}
  register: result
  until: result.finished
  retries: 300
- name: Wait for build2 to complete
  async_status: jid={{build2.ansible_job_id}}
  register: result
  until: result.finished
  retries: 300
```

Obviously I need to clone the repo before I can run `npm i`, and I need to `npm i` before I can `npm build`. But there's no reason these two repos can't be cloned, installed and built in parallel for speed gains. And more speed gains if there are even more repos :)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/blockinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)
* [lib/ansible/modules/utilities/logic/async_status.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/async_status.py)
* [lib/ansible/modules/windows/async_status.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/async_status.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @yaegashi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/blockinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)
* [lib/ansible/modules/utilities/logic/async_status.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/async_status.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/blockinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)
* [lib/ansible/modules/utilities/logic/async_status.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/async_status.py)
* [lib/ansible/modules/windows/async_status.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/async_status.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/blockinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)
* [lib/ansible/modules/utilities/logic/async_status.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/async_status.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/blockinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)
* [lib/ansible/modules/utilities/logic/async_status.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/async_status.py)
* [lib/ansible/modules/windows/async_status.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/async_status.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nbrownus** [comment]
This could potentially fix #32265

**Comment by ansibot** [comment]
cc @if-meaton
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by darkone337** [comment]
bump. This would be a great feature!

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/blockinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)
* [lib/ansible/modules/utilities/logic/async_status.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/async_status.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lanceofwhichwedream** [comment]
Bump. Adding this will make it so that ansible and by proxy ansible tower are capable of handling a situation where a device goes offline during the execution of a playbook.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/files/blockinfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)
* [`lib/ansible/modules/utilities/logic/async_status.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/async_status.py)
* [`lib/ansible/modules/windows/async_status.ps1`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/async_status.ps1)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sadok-f** [comment]
+1

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/async_status.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/async_status.py)
* [`lib/ansible/modules/blockinfile.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/blockinfile.py)
* [`lib/ansible/modules/windows/async_status.ps1`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/async_status.ps1)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by JumaX** [comment]
+1 on this.

**Comment by yashfaizan** [comment]
+1

**Comment by yadavakshay58** [comment]
Would be great to have this feature.

**Comment by andreasnuesslein** [comment]
+1

**Comment by TobiasWinchen** [comment]
+1

**Comment by DaVince** [comment]
Please just use the thumbs up reaction on the first post; the +1 is just spam in my and everyone else's inbox.

**Comment by bcoca** [comment]
If we ever add `async` to blocks it would mainly be for the tasks in the block to inherit and use async themselves, not for the blocks to run in parallel to each other but maintaining linear blocking execution of the tasks. 

For this you should use parallel playbooks executed by a scheduler/workflow engine (awx/tower/controller or similar).

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/async_wrapper.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/async_wrapper.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/devel/ISSUE_HELP.md)

**Comment by brlin-tw** [comment]
Apologies for the notification, however, I'd like to share my use case which is somewhat related.

I have a server information detection playbook that queries information in many aspects of the system(storage, network...etc) and finally renders all the results in a single, template-derived report.

For each aspect of detection, more than one task is run serially, but different aspects are independent with each other and can run simultaneously without order:

```
playbooks/
├─detect-system-information.yml
tasks/
├─main.yml
├── checks/
│   ├── root_crontab.yml
│   ├── ...
│   ├── zombie_processes.yml
```

```yaml
# tasks/main.yml
- name: Check root crontab
  async: 20
  poll: 0
  register: async_job_root_crontab
  import_tasks: checks/root_crontab.yml

- name: Detect zombie processes
  async: 20
  poll: 0
  register: async_job_zombie_processes
  import_tasks: checks/zombie_processes.yml

- name: Wait for all asynchronous checks to be completed
  loop:
    - '{{ async_job_root_crontab }}'
    - '{{ async_job_zombie_processes }}'
  loop_control:
    loop_var: async_job
  async_status:
    jid: '{{ async_job.ansible_job_id }}'

- name: Generate system detection report
  delegate_to: localhost
  become: False
  template:
    src: report-template.md.j2
    dest: "{{ lookup('env', 'PWD') }}/{{ inventory_hostname }}-system-detection-report.md"
    mode: 0644

```

```yaml
# tasks/checks/zombie_processes.yml
- name: Query zombie process information
  changed_when: False
  register: zombie_processes_raw
  failed_when: False
  shell: |
    pgrep \
      --runstates Z \
      --list-full

- name: Set queried zombie process information as a host variable
  set_fact:
    zombie_processes: '{{ zombie_processes_raw.stdout }}'
```

I attempt to implement it using block/import_tasks/include_tasks but all are not successful, are there currently anyways to properly solve/workaround this one?

Thanks in advance!

**Comment by jborean93** [comment]
This is somewhat achievable today by using `async_status` to wait the result of the blocked tasks

```yaml
- block:
  - ping:
    register: task1
    async: 30

  - ping:
    register: task2
    async: 30

- name: wait until tasks are complete
  async_status:
    jid: '{{ item.ansible_job_id }}'
  register: async_status
  until: async_status is finished
  loop:
  - '{{ task1 }}'
  - '{{ task2 }}'
```

This at least gets something working today rather than waiting for this to be implemented.
