### ISSUE TITLE
aci_rest doesnt process postman validated rest calls

### ISSUE THREAD

**Issue by fatred** [ansible/ansible#28994]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aci_rest

##### ANSIBLE VERSION
```
ansible 2.4.0
  config file = /root/git/aci-init/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/git/aci-init/ansible24/lib/python2.7/site-packages/ansible
  executable location = /root/git/aci-init/ansible24/bin/ansible
  python version = 2.7.13 (default, Aug 28 2017, 21:50:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
```ini
[defaults]
inventory=hosts
host_key_checking = False
retry_files_enabled = False
```

##### OS / ENVIRONMENT
CentOS Linux release 7.3.1611 (Core) 
Python 2.7.13 compiled from source with make-alternative
ansible 2.4 running in a virtualenv
ACI 2.2(2j)

##### SUMMARY
Im trying to use aci_rest to plug the gaps in the existing module support.  I have a suite of postman requests against polUni that work, but when I use them within content (and with_items to replicate the csv features of postman), I get failures. I have tried also using direct hits using API Inspector text verbatim - same result. 

More Common objects like tenant and EPGs all work as expected via aci_rest.

##### STEPS TO REPRODUCE
Note: Ensure items do not exist in the fabric (for proof that objects are created.

The first play uses the policy universe endpoint, and requires more verbose json. 
The second play uses literal MO terminology
The third play uses something in between the two (taling to the parent universal object.

All three of these JSON blobs work against the rest endpoint provided.
```yaml
- name: Deploy generic fabric level policies to ACI
  hosts: aci_lab
  vars:
    vmm_domain_name: 'vcenter65'
    phys_domain_name: 'phys'
  gather_facts: no
  connection: local
  tasks:
    - name: Configure Link Level Policies
      aci_rest:
        hostname: '{{ inventory_hostname }}'
        username: '{{ aci_username }}'
        password: '{{ aci_password }}'
        validate_certs: no
        use_proxy: no
        method: post
        path: /api/mo/uni.json
        content: |
          {
            "polUni": {
              "attributes": {},
              "children": [{
                "infraInfra": {
                  "attributes": {},
                  "children": [{
                    "fabricHIfPol": {
                      "attributes": {
                        "dn": "uni/infra/hintfpol-{{ item.name }}",
                        "name": "{{ item.name }}",
                        "descr": "",
                        "speed": "{{ item.speed }}",
                        "autoNeg": "{{ item.auto }}",
                        "fecMode": "inherit",
                        "linkDebounce": "100"
                      },
                      "children": []
                    }
                  }]
                }
              }]
            }
          }
      delegate_to: localhost
      with_items:
        - { name: 'Link-10G-Auto', speed: '10G', auto: "on" }
        - { name: 'Link-10G-NoNegotiate', speed: '10G', auto: "off" }
        - { name: 'Link-1G-Auto', speed: '1G', auto: "on" }
        - { name: 'Link-1G-NoNegotiate', speed: '1G', auto: "off" }

    - name: Configure LLDP Policies
      aci_rest:
        hostname: '{{ inventory_hostname }}'
        username: '{{ aci_username }}'
        password: '{{ aci_password }}'
        validate_certs: no
        use_proxy: no
        method: post
        path: /api/mo/uni/infra/lldpIfP-{{ item.name }}.json
        content: |
          {
            "lldpIfPol": {
              "attributes": {
                "dn": "uni/infra/lldpIfP-{{ item.name }}",
                "rn": "lldpIfP-{{ item.name }}",
                "status": "created",
                "name": "{{ item.name }}",
                "adminRxSt": "{{ item.state }}",
                "adminTxSt": "{{ item.state }}",
                "descr": "",
                "nameAlias": "",
                "ownerKey": "",
                "ownerTag": ""
              },
              "children": []
            }
          }
      delegate_to: localhost
      with_items:
        - { name: 'LLDP-Disabled', state: "disabled" }
        - { name: 'LLDP-Enabled', state: "enabled" }

    - name: Configure CDP Policies
      aci_rest:
        hostname: '{{ inventory_hostname }}'
        username: '{{ aci_username }}'
        password: '{{ aci_password }}'
        validate_certs: no
        use_proxy: no
        method: post
        path: /api/mo/uni/infra.json
        content: |
          {
            "cdpIfPol": {
              "attributes": {
                "adminSt": "{{ item.state }}",
                "descr": "",
                "name": "{{ item.name }}",
                "nameAlias": "",
                "ownerKey": "",
                "ownerTag": ""
              }
            }
          }

      delegate_to: localhost
      with_items:
        - { name: 'CDP-Disabled', state: "disabled" }
        - { name: 'CDP-Enabled', state: "enabled" }
```
##### EXPECTED RESULTS
Policies with setting as found in with_items are created/edited/validated to match the request.

##### ACTUAL RESULTS
- `/api/mo/uni.json` returns Error 400 from endpoint: `unknown managed object class 'polUni`
- `/api/mo/uni/infra/lldpIfP-LLDP-Disabled.json` returns Error 400 from endpoint: `Request failed: 122 unknown managed object class 'lldpIfPol'`
- `/api/mo/uni/infra.json` returns Error 400 from endpoint: `Request failed: 122 unknown managed object class 'lldpIfPol'`

```
TASK [Configure Link Level Policies] ************************************************************************************************************************************************************************
task path: /root/git/aci-init/tasks/deploy-fabric-policies.yaml:9
Using module file /root/git/aci-init/ansible24/lib/python2.7/site-packages/ansible/modules/network/aci/aci_rest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1504546989.77-258093036759195 `" && echo ansible-tmp-1504546989.77-258093036759195="` echo /root/.ansible/tmp/ansible-tmp-1504546989.77-258093036759195 `" ) && sleep 0'
<localhost> PUT /tmp/tmpRDeojy TO /root/.ansible/tmp/ansible-tmp-1504546989.77-258093036759195/aci_rest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1504546989.77-258093036759195/ /root/.ansible/tmp/ansible-tmp-1504546989.77-258093036759195/aci_rest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1504546989.77-258093036759195/aci_rest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1504546989.77-258093036759195/" > /dev/null 2>&1 && sleep 0'
failed: [10.224.244.101 -> localhost] (item={u'auto': u'on', u'speed': u'10G', u'name': u'Link-10G-Auto'}) => {
    "changed": false, 
    "error_code": "122", 
    "error_text": "unknown managed object class 'polUni'", 
    "failed": true, 
    "imdata": [
        {
            "error": {
                "attributes": {
                    "code": "122", 
                    "text": "unknown managed object class 'polUni'"
                }
            }
        }
    ], 
    "invocation": {
        "module_args": {
            "content": "{'polUni': {'attributes': {}, 'children': [{'infraInfra': {'attributes': {}, 'children': [{'fabricHIfPol': {'attributes': {'dn': 'uni/infra/hintfpol-Link-10G-Auto', 'name': 'Link-10G-Auto', 'descr': '', 'fecMode': 'inherit', 'autoNeg': 'on', 'speed': '10G', 'linkDebounce': '100'}, 'children': []}}]}}]}}", 
            "hostname": "10.224.244.101", 
            "method": "post", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "path": "/api/mo/uni.json", 
            "protocol": "https", 
            "src": null, 
            "timeout": 30, 
            "use_proxy": false, 
            "use_ssl": true, 
            "username": "admin", 
            "validate_certs": false
        }
    }, 
    "item": {
        "auto": "on", 
        "name": "Link-10G-Auto", 
        "speed": "10G"
    }, 
    "msg": "Request failed: 122 unknown managed object class 'polUni'", 
    "response": "HTTP Error 400: Bad Request", 
    "status": 400, 
    "totalCount": "1"
}
```

(reorder and rerun)

```
TASK [Configure LLDP Policies] ******************************************************************************************************************************************************************************
task path: /root/git/aci-init/tasks/deploy-fabric-policies.yaml:9
Using module file /root/git/aci-init/ansible24/lib/python2.7/site-packages/ansible/modules/network/aci/aci_rest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1504543541.37-119790404639279 `" && echo ansible-tmp-1504543541.37-119790404639279="` echo /root/.ansible/tmp/ansible-tmp-1504543541.37-119790404639279 `" ) && sleep 0'
<localhost> PUT /tmp/tmpaDw53C TO /root/.ansible/tmp/ansible-tmp-1504543541.37-119790404639279/aci_rest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1504543541.37-119790404639279/ /root/.ansible/tmp/ansible-tmp-1504543541.37-119790404639279/aci_rest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1504543541.37-119790404639279/aci_rest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1504543541.37-119790404639279/" > /dev/null 2>&1 && sleep 0'
failed: [10.224.244.101 -> localhost] (item={u'state': u'disabled', u'name': u'LLDP-Disabled'}) => {
    "changed": false, 
    "error_code": "122", 
    "error_text": "unknown managed object class 'lldpIfPol'", 
    "failed": true, 
    "imdata": [
        {
            "error": {
                "attributes": {
                    "code": "122", 
                    "text": "unknown managed object class 'lldpIfPol'"
                }
            }
        }
    ], 
    "invocation": {
        "module_args": {
            "content": "{'lldpIfPol': {'attributes': {'dn': 'uni/infra/lldpIfP-LLDP-Disabled', 'status': 'created', 'ownerKey': '', 'name': 'LLDP-Disabled', 'descr': '', 'adminTxSt': 'disabled', 'adminRxSt': 'disabled', 'nameAlias': '', 'ownerTag': '', 'rn': 'lldpIfP-LLDP-Disabled'}, 'children': []}}", 
            "hostname": "10.224.244.101", 
            "method": "post", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "path": "/api/mo/uni/infra/lldpIfP-LLDP-Disabled.json", 
            "protocol": "https", 
            "src": null, 
            "timeout": 30, 
            "use_proxy": false, 
            "use_ssl": true, 
            "username": "admin", 
            "validate_certs": false
        }
    }, 
    "item": {
        "name": "LLDP-Disabled", 
        "state": "disabled"
    }, 
    "msg": "Request failed: 122 unknown managed object class 'lldpIfPol'", 
    "response": "HTTP Error 400: Bad Request", 
    "status": 400, 
    "totalCount": "1"
}
```

(reorder and re-run)

```
Using module file /root/git/aci-init/ansible24/lib/python2.7/site-packages/ansible-2.4.0-py2.7.egg/ansible/modules/network/aci/aci_rest.py                                                                           
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'                                                           
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1504494510.87-63962550230072 `" && echo ansible-tmp-1504494510.87-63962550230072="` echo /root/.ansible/tmp/ansible-tmp-1504494510.87-63962550230072 `" ) && sleep 0'                                                                                                                                                                          
<localhost> PUT /tmp/tmpccbpNg TO /root/.ansible/tmp/ansible-tmp-1504494510.87-63962550230072/aci_rest.py 
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1504494510.87-63962550230072/ /root/.ansible/tmp/ansible-tmp-1504494510.87-63962550230072/aci_rest.py && sleep 0'                              
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1504494510.87-63962550230072/aci_rest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1504494510.87-63962550230072/" > /dev/null 2>&1 && sleep 0'                                                                                                                                                                                                                  
failed: [10.224.244.101 -> localhost] (item={u'state': u'enabled', u'name': u'LLDP-Enabled'}) => {        
    "changed": false,                                                                                     
    "error_code": "122",                                                                                  
    "error_text": "unknown managed object class 'lldpIfPol'",                                             
    "failed": true,                                                                                       
    "imdata": [                                                                                           
        {                                                                                                 
            "error": {                                                                                    
                "attributes": {                                                                           
                    "code": "122",                                                                        
                    "text": "unknown managed object class 'lldpIfPol'"                                    
                }                                                                                         
            }                                                                                             
        }                                                                                                 
    ],                                                                                                    
    "invocation": {                                                                                       
        "module_args": {                                                                                  
            "content": "{'lldpIfPol': {'attributes': {'dn': 'uni/infra/lldpIfP-LLDP-Enabled', 'ownerKey': '', 'name': 'LLDP-Enabled', 'descr': '', 'adminTxSt': 'enabled', 'adminRxSt': 'enabled', 'nameAlias': '', 'ownerTag': ''}}}",                                                                                                                                                                                                   
            "hostname": "10.224.244.101",                                                                 
            "method": "post",                                                                             
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",                                            
            "path": "/api/mo/uni/infra.json",                                                             
            "protocol": "https",                                                                          
            "src": null,                                                                                  
            "timeout": 30,                                                                                
            "use_proxy": false,                                                                           
            "use_ssl": true,                                                                              
            "username": "admin",                                                                          
            "validate_certs": false                                                                       
        }                                                                                                 
    },                                                                                                    
    "item": {                                                                                             
        "name": "LLDP-Enabled",                                                                           
        "state": "enabled"                                                                                
    },                                                                                                    
    "msg": "Request failed: 122 unknown managed object class 'lldpIfPol'",                                
    "response": "HTTP Error 400: Bad Request",                                                            
    "status": 400,                                                                                        
    "totalCount": "1"                                                                                     
}                                                                                                         
```

**Comment by ansibot** [comment]
cc @dagwieers @jmcgill298 @schunduri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jmcgill298 @schunduri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jmcgill298** [comment]
I reversed the quotation marks for content to match proper JSON and it worked

**Comment by dagwieers** [comment]
@jmcgill298 Would it help if we parse the provided JSON ourselves, and convert it back to JSON ?

**Comment by dagwieers** [comment]
@fatred I made some changes to **aci_rest** to include idempotency,  YAML input support, better support for JSON input (it now accepts both JSON inline as well as input), and input is now validated (YAML, JSON or XML).

I would be interested to see if it makes a difference, or at least get a better error message.

BTW The new inline YAML input is more convenient than JSON or XML IMO.

**Comment by fatred** [comment]
@jmcgill298 is correct with the quotes of course: 
```yaml
    - name: Configure Link Level Policies
      aci_rest:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        use_proxy: no
        method: post
        path: /api/mo/uni.json
        content: '|
          {
            "polUni": {
              "attributes": {},
              "children": [{
                "infraInfra": {
                  "attributes": {},
                  "children": [{
                    "fabricHIfPol": {
                      "attributes": {
                        "dn": "uni/infra/hintfpol-{{ item.name }}",
                        "name": "{{ item.name }}",
                        "descr": "",
                        "speed": "{{ item.speed }}",
                        "autoNeg": "{{ item.auto }}",
                        "fecMode": "inherit",
                        "linkDebounce": "100"
                      },
                      "children": []
                    }
                  }]
                }
              }]
            }
          }'
```
Note the original one had no quote wrapping on the content blob at all, and I had mixed quote types in with_items (doh!) Perhaps the need to wrap the content in quotes is obvious to some, but a doc edit might help with that ;)

Meantime, ill check all my other stuff works on this basis, and then look at the update to the module.

Thanks!

**Comment by dagwieers** [comment]
So with the latest changes, you can use JSON/YAML syntax inline, which means you don't have to use the multi-line string ' content: |' syntax. I added integration tests for testing all 5 input-forms (inline YAML/JSON, YAML/JSON string and XML string).

The most important reason for me for doing this is that I am expecting a lot of people having issues due to forgetting the '|' token.

I added input validation because it will provide a more straightforward error-message, and I still have to investigate, but normally we could even give an indication on what row/column the syntax error is located in the input. All-in-all I think this is an important improvement, but one that requires a bit more testing (it works for all the playbooks we're having in production).

**Comment by fatred** [comment]
so i was able to fix all my dramas using the correct quoting notation. 

Moving on to the updates, i tried this: 

```yaml
    - name: Configure Link Level Policies
      aci_rest:
        hostname: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        use_proxy: no
        method: post
        path: /api/mo/uni.json
        content:
          polUni:
            attributes: ""
            children:
              infraInfra:
                attributes: ""
                children:
                  fabricHIfPol:
                    attributes:
                      dn: "uni/infra/hintfpol-{{ item.name }}"
                      name: "{{ item.name }}"
                      descr: ""
                      speed: "{{ item.speed }}"
                      autoNeg: "{{ item.auto }}"
                      fecMode: "inherit"
                      linkDebounce: "100"
                    children: ""
      delegate_to: localhost
      with_items:
        - { name: "Link-10G-Auto", speed: "10G", auto: "on" }
        - { name: "Link-10G-NoNegotiate", speed: "10G", auto: "off" }
        - { name: "Link-1G-Auto", speed: "1G", auto: "on" }
        - { name: "Link-1G-NoNegotiate", speed: "1G", auto: "off" }
```

and got this: 

```
Using module file /root/git/aci-init/ansible24/lib/python2.7/site-packages/ansible/modules/network/aci/aci_rest.py
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1504624350.64-212856820749035 `" && echo ansible-tmp-1504624350.64-212856820749035="` echo /root/.ansible/tmp/ansible-tmp-1504624350.64-212856820749035 `" ) && sleep 0'
<localhost> PUT /tmp/tmpYne1Fg TO /root/.ansible/tmp/ansible-tmp-1504624350.64-212856820749035/aci_rest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1504624350.64-212856820749035/ /root/.ansible/tmp/ansible-tmp-1504624350.64-212856820749035/aci_rest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1504624350.64-212856820749035/aci_rest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1504624350.64-212856820749035/" > /dev/null 2>&1 && sleep 0'
failed: [10.224.244.101 -> localhost] (item={u'auto': u'off', u'speed': u'1G', u'name': u'Link-1G-NoNegotiate'}) => {
    "changed": false, 
    "error_code": "400", 
    "error_text": "incomplete node at line '1'", 
    "failed": true, 
    "imdata": [
        {
            "error": {
                "attributes": {
                    "code": "400", 
                    "text": "incomplete node at line '1'"
                }
            }
        }
    ], 
    "invocation": {
        "module_args": {
            "content": {
                "polUni": {
                    "attributes": "", 
                    "children": {
                        "infraInfra": {
                            "attributes": "", 
                            "children": {
                                "fabricHIfPol": {
                                    "attributes": {
                                        "autoNeg": "off", 
                                        "descr": "", 
                                        "dn": "uni/infra/hintfpol-Link-1G-NoNegotiate", 
                                        "fecMode": "inherit", 
                                        "linkDebounce": "100", 
                                        "name": "Link-1G-NoNegotiate", 
                                        "speed": "1G"
                                    }, 
                                    "children": ""
                                }
                            }
                        }
                    }
                }
            }, 
            "hostname": "10.224.244.101", 
            "method": "post", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "path": "/api/mo/uni.json", 
            "protocol": "https", 
            "src": null, 
            "timeout": 30, 
            "use_proxy": false, 
            "use_ssl": true, 
            "username": "admin", 
            "validate_certs": false
        }
    }, 
    "item": {
        "auto": "off", 
        "name": "Link-1G-NoNegotiate", 
        "speed": "1G"
    }, 
    "msg": "Request failed: 400 incomplete node at line '1'", 
    "payload": "{\"polUni\": {\"attributes\": \"\", \"children\": {\"infraInfra\": {\"attributes\": \"\", \"children\": {\"fabricHIfPol\": {\"attributes\": {\"dn\": \"uni/infra/hintfpol-Link-1G-NoNegotiate\", \"name\": \"Link-1G-NoNegotiate\", \"descr\": \"\", \"fecMode\": \"inherit\", \"autoNeg\": \"off\", \"speed\": \"1G\", \"linkDebounce\": \"100\"}, \"children\": \"\"}}}}}}", 
    "response": "HTTP Error 400: Bad Request", 
    "status": 400, 
    "totalCount": "1", 
    "url": "https://10.224.244.101/api/mo/uni.json?rsp-subtree=modified"
}
```
One assumed it would be a verbatim move from JSON to YAML, so I'm guessing I'm missing some simple thing again?

P.S. ++1 for the YAML notation ;)

**Comment by dagwieers** [comment]
So looking at your example, I was wondering if the problem isn't that `attributes` and `children`is a string in your example, but it should be resp. a list and a dictionary. So an empty `[]` and`{}` would be needed IMO.

And I would leave `attributes` off when it's empty since it translates to nothing anyway in XML. (attributes/children are just entries to translate between JSON and XML, so if empty they're not needed).

```yaml
    - name: Configure Link Level Policies
      aci_rest:
        host: "{{ inventory_hostname }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        method: post
        path: /api/mo/uni.json
        use_proxy: no
        validate_certs: no
        content:
          polUni:
            children:
              infraInfra:
                children:
                  fabricHIfPol:
                    attributes:
                      dn: "uni/infra/hintfpol-{{ item.name }}"
                      name: "{{ item.name }}"
                      descr: ""
                      speed: "{{ item.speed }}"
                      autoNeg: "{{ item.auto }}"
                      fecMode: "inherit"
                      linkDebounce: "100"
                   children: []
      with_items:
        - { name: "Link-10G-Auto",         speed: "10G",  auto: "on" }
        - { name: "Link-10G-NoNegotiate",  speed: "10G",  auto: "off" }
        - { name: "Link-1G-Auto",          speed: "1G",   auto: "on" }
        - { name: "Link-1G-NoNegotiate",   speed: "1G",   auto: "off" }
      delegate_to: localhost
```
