### ISSUE TITLE
Add `append` as state to nsupdate module

### ISSUE THREAD

**Issue by artheus** [ansible/ansible#28993]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
nsupdate

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Using nsupdate as a command line tool allows people to use `update add` for multiple SRV records. This has not been considered for this ansible module.
Therefore I think it is necessary to add `append` as a state to the nsupdate module.

##### STEPS TO REPRODUCE
````
- name: Append an srv record to my server
  nsupdate:
    key_name: "mykeyname"
    key_secret: "{{ vault_key_secret }}"
    server: "dns.example.com"
    zone: "example.com."
    record: "_service._tcp.example.com."
    type: 'SRV'
    value: '0 0 2020 myservice01.example.com'
  become: false
  delegate_to: localhost
```
##### EXPECTED RESULTS
I would expect this to append an SRV record to the server.

##### ACTUAL RESULTS
Overwrite/modify for every single host.
