### ISSUE TITLE
More options for module jenkins_job

### ISSUE THREAD

**Issue by tbar74235** [ansible/ansible#29016]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
jenkins_job

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /opt/jboss/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
not relevant

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If you try to create a jenkins job via the ansible module you will get an error if the job is already existing on the jenkins instance you like to create your job on.

##### STEPS TO REPRODUCE
I would expect that the jenkins_job module would provide me an option (for example: ignore_error (true/false) and overwrite_existing (true/false)) where I can decide if I don't want to create a job if it already exists or if I would like to overwrite an already existing job.
The same options are useful for a job deletion.

If ignore_error true the job creation should be skipped if the job already exists without error. If false an error should occur if the job exists.
If overwrite_existing true the job should be created don't mind if it exists or not. If it exists the existing job should be deleted and after that a new job creation should start. If false the job shouldn't be created and if an error occurs in this case should depend on the value of ignore_error.

```
---
- hosts: 127.0.0.1

  tasks:
  - name: "create my_jenkins_job in jenkins"
    jenkins_job:
      config: "{{ lookup('file', 'myjenkinsjobtemplate.xml') }}"
      name: "my_jenkins_job"
      token: "myawesometoken"
      url: "https://myjenkins"
      user: "myUser"
  run_once: true
```

##### EXPECTED RESULTS
I would expect that the jenkins_job module would provide me an option (for example: ignore_error (true/false) and overwrite_existing (true/false)) where I can decide if I don't want to create a job if it already exists or if I would like to overwrite an already existing job.
The same options are useful for a job deletion.

If ignore_error true the job creation should be skipped if the job already exists without error. If false an error should occur if the job exists.
If overwrite_existing true the job should be created don't mind if it exists or not. If it exists the existing job should be deleted and after that a new job creation should start. If false the job shouldn't be created and if an error occurs in this case should depend on the value of ignore_error.

##### ACTUAL RESULTS
Currently in any case you will get an error if you try to create a job which already exists.
And you will get an error if you try to delete a job which doesn't exist.
