### ISSUE TITLE
When using block in an included file, "rescue" doesn't have "ansible_failed_task"/"ansible_failed_result" variables defined

### ISSUE THREAD

**Issue by maxgalbu** [ansible/ansible#29047]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

block

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

none

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When using block in an included file, "rescue" doesn't have "ansible_failed_task"/"ansible_failed_result" variables defined

##### STEPS TO REPRODUCE

playbook.yml
```yaml
---
- hosts: localhost

  tasks:
    - include: localtasks.yml
```

localtasks.yaml
```yaml
---
- block:
    - command: /bin/false
  rescue:
    - name: Handling error on slack
      debug: 
        msg: "Error is: {{ansible_failed_result}}"
  run_once: true
```

##### EXPECTED RESULTS

`ansible_failed_result` should be defined

##### ACTUAL RESULTS

```
fatal: [10.0.10.36]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'ansible_failed_result' is undefined\n\nThe error appears to have been in 'localtasks.yml': line 111, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  rescue:\n    - name: Handling error on slack\n      ^ here\n"}
```
