### ISSUE TITLE
'combine' filter breaks dependencies deduplication

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#29045]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

jinja2
##### ANSIBLE VERSION

```
ansible 2.3.2.0
```

##### CONFIGURATION

hash_behaviour=merge
##### OS / ENVIRONMENT

FreeBSD 11.1
##### SUMMARY

When combine filter is used in a task, role runs multiple times via dependencies
##### STEPS TO REPRODUCE

in 'base' role

```yaml
### defaults:
some_hash:
  any:
    foo: 9
  Linux:
    foo: 1
    bar: 2
  FreeBSD:
    baz: 5

### tasks
- name: place numbers
  copy:
    dest: "/tmp/{{ item.key}}"
    content: "{{ item.value }}"
  with_dict: "{{ some_hash['any'] | combine( some_hash[ansible_system] ) }}"
```
Playbook executes roles 'role1', 'role2', 'role3', all of them depend on 'base'

##### EXPECTED RESULTS

execution sequence: base, role1, role2, role3
##### ACTUAL RESULTS

execution sequence: base, role1, base, role2, base, role3.
The mere presence of 'combine' filter breaks deduplication.
