### ISSUE TITLE
The subject of emails is not encoded to UTF-8

### ISSUE THREAD

**Issue by L-B** [ansible/ansible#29085]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

mail

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.3.2.0
  config file = /work/ansible/configuration/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### OS / ENVIRONMENT

from RHEL7 to RHEL7

##### SUMMARY

An email is sent that contains accented letters in both the body and subject. the mail module charset is set tp utf-8. On reception, the body is shown properly, but the subject is mangled. It appears the subject contains no encoding information.

##### STEPS TO REPRODUCE

```yaml
- name: Email with UTF8 characters
  mail:
    from:    whoever@example.com
    to:      somebody@example.com
    charset: utf-8
    subject: "Création"
    body:    "Création"
```

##### EXPECTED RESULTS

Both the body and subject should be properly encoded to UTF-8 so they can be displayed correctly.
The subject header should be something like:

```
Subject: =?utf-8?B?Q3LDqWF0aW9u?=
```

##### ACTUAL RESULTS

The subject was simply set verbatim in the email, instead of being encoded properly.
From the email headers as shown in the MUA:

```
Subject: Cr??ation
```
