### ISSUE TITLE
xml module: Add ability to handle arrays

### ISSUE THREAD

**Issue by MedicMomcilo** [ansible/ansible#29083]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
xml module

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Sep  1 2017, 16:13:49) [GCC 7.2.1 20170829 (Red Hat 7.2.1-1)]

```

##### CONFIGURATION
No special configuration

##### OS / ENVIRONMENT
N/A

##### SUMMARY
There should be a method of changing arrays within XMLs. Often there is a need to add/remove/change an item in XML that is present on multiple nodes - this is currently not possible.

##### STEPS TO REPRODUCE
Given this XML file:
```
<?xml version='1.0' encoding='UTF-8'?>
<business type="bar">
    <name>Tasty Beverage Co.</name>
    <beers>
        <beer>
            <name>Rochefort 10</name>
        </beer>
        <beer>
            <name>St. Bernardus Abbot 12</name>
        </beer>
        <beer>
            <name>Schlitz</name>
        </beer>
    </beers>
    <rating subjective="true">10</rating>
    <website>
        <mobilefriendly />
        <address>http://tastybeverageco.com</address>
    </website>
</business>
```
There should be simple method of adding ```<type>Ale</type>``` to all ```<beer>``` children of ```<beers>```.
For example:
```yaml
---
- hosts: localhost

  tasks:

  - name: Add beer type for all children
    xml:
      file: /test.xml
      xpath: /business/beers/beer
      add_children:
        - type: Ale
...
```

##### EXPECTED RESULTS
```<type>Ale</type>``` is added to all children under the ```<beers>```.

##### ACTUAL RESULTS
```<type>Ale</type>``` is added only to the last child under the ```<beers>```.
