### ISSUE TITLE
Redshift module does not make any changes to existing cluster

### ISSUE THREAD

**Issue by kasia211** [ansible/ansible#29087]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
module redshift

##### ANSIBLE VERSION
ansible version: 2.3.1.0

##### SUMMARY

I'm trying to resize my redshift cluster using redshift module. First I check if cluster exist and if true I want to resize it. Both tasks pass, and are in changed status, but there is no real result.

##### STEPS TO REPRODUCE

```
- name: Gather facts about clusters
  redshift:
    identifier: "{{ REDSHIFT_NAME }}"
    command: facts
  register: redshift_clusters

- name: Modify cluster
      redshift:
        command: modify
        identifier: "{{ REDSHIFT_NAME }}"
        number_of_nodes: "{{ REDSHIFT_NODES }}"
      when: redshift_clusters.cluster
```

##### EXPECTED RESULTS
Resize existing cluster.

##### ACTUAL RESULTS

The task is in change status, but there is no result on cluster.  

```

```
