### ISSUE TITLE
nxos_bgp currently fails to apply config for nxapi transport

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible#29122]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_bgp
##### ANSIBLE VERSION

```
2.4
```

##### SUMMARY

nxos_bgp currently fails to apply config on nxapi. Passes silently.
##### STEPS TO REPRODUCE

```yaml
  - name: "Enable feature BGP"
    nxos_feature:
      feature: bgp
      state: enabled
      provider: "{{ nxapi }}"

  - name: "Configure BGP defaults"
    nxos_bgp: &configure_default
      asn: 65535
      router_id: 1.1.1.1
      state: present
      provider: "{{ nxapi }}"
    register: result 

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Run show running-config bgp - should pass"
    nxos_command:
      commands:
        - sh running-config bgp
      provider: "{{ nxapi }}"
    register: result

  - assert:
      that:
        - "result.failed == false"
        - "'65535' in result.stdout[0]"
```

##### EXPECTED RESULTS

nxos_bgp should actually configure the device.
##### ACTUAL RESULTS

Even though nxos_bgp is sending the right commands to the host, but not actually applying the config.
`sh running-config bgp` returns empty stdout.

**Comment by ansibot** [comment]
cc @GGabriele @jedelman8 @mikewiebe @privateip @rahushen @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Qalthos** [comment]
`transport: nxapi`, for historical reasons, defaults to json output. `show running-config` does not provide output as json. In order to do what you're trying to do, you need to tell ansible you want the command output as text, such as the following:

```
  - name: "Run show running-config bgp - should pass"
    nxos_command:
      commands:
        - command: sh running-config bgp
          output: text
      provider: "{{ nxapi }}"
    register: result
```
