### ISSUE TITLE
Module lvg did not resize physical volume if needed

### ISSUE THREAD

**Issue by Gehrken** [ansible/ansible#29139]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module: lvg 

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```
##### SUMMARY
lvg Module did not re-size physical volume in case the underlying block device has been changed in size. 

##### STEPS TO REPRODUCE
1. Create a VM with an additional empty block device (/dev/vdb) with size 200GB 
2. Run below tasks => You will have a new fs with the size of 160 GB
3. Extend the additional block device  (/dev/vdb) to 300GB 

```yaml
  - name: create volume group on device
    lvg:
      vg: bitbucketdg
      pvs: /dev/vdb    
      pesize: 32
        
  - name: create data volume on device    
    lvol:
      vg: bitbucketdg
      lv: bitbucketdv
      size: 80%PVS
      state: present
      force: yes

  - name: Format disk
    filesystem:  
      dev: /dev/bitbucketdg/bitbucketdv
      fstype: xfs
      resizefs: yes
      
  - name: mount data disk
    mount:  
      src: /dev/bitbucketdg/bitbucketdv
      path: /var/opt/bitbucket-data
      fstype: xfs
      state: mounted
```

##### EXPECTED RESULTS
The logical volume (and group) should be extended to 80% size of the block device (240GB). 

##### ACTUAL RESULTS
The logical volume (and group) remain in original size (160GB)

```
[root@gittest2 opt]# df -h
Filesystem                                                           Size  Used Avail Use% Mounted on
/dev/mapper/bitbucketdg-bitbucketdv                                  160G   33M  160G   1% /var/opt/bitbucket-data

```
When running pvresize in before: 
```
[root@gittest2 opt]# pvresize /dev/vdb 
  Physical volume "/dev/vdb" changed
  1 physical volume(s) resized / 0 physical volume(s) not resized
```
the resizing works as expected:
```
[root@gittest2 opt]# df -h
Filesystem                                                           Size  Used Avail Use% Mounted on
/dev/mapper/bitbucketdg-bitbucketdv                                  240G   33M  240G   1% /var/opt/bitbucket-data
```
