### ISSUE TITLE
Ansible 2.4.0 devel 3324d0a4b0 - Debug Module - When Conditional Does Not Properly Evaluate Integer Variables Using "with_items" or "with_random_choice"

### ISSUE THREAD

**Issue by ifelsefi** [ansible/ansible#29133]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Debug module, with when conditional, using with_random_choice or with_items
##### ANSIBLE VERSION

```
ansible 2.4.0 (devel 3324d0a4b0) last updated 2017/05/09 16:25:08 (GMT -400)
  config file = /home/douglas/repos/ansible/ansible.cfg
  configured module search path = [u'/home/douglas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/ansible
  executable location = /opt/ansible-2.4.0-latest/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

```

##### CONFIGURATION

Only things related to ssh pipelining and, remote tmpdir, threads, etc.

##### OS / ENVIRONMENT

Linux Mint

##### SUMMARY

I want the task, using debug module, to register file systems which are below a defined quota and utilization threshold.  When conditional would select among items iterated though using with_random_choice.  So only a random file system, meeting the requirements, would be chosen.   Though even when iterating though all, using with_items, the task skips file systems which should pass the conditional check.  I am likely doing it wrong.

##### STEPS TO REPRODUCE

```yaml

- name: populate qusage
  tags: xfs
  set_fact:
    qusage: "{{ qusage + [ { 'homedir': item[0].homedir, 'usage': item[0].usage, 'qpresent': item[1].qpresent } ] }}"
  with_together: 
    - "{{ homedir }}"
    - "{{ qpresent }}"
  delegate_to: file_server

- name: print quotausage
  tags: xfs
  debug: var=item.qpresent
  with_items: "{{ qusage }}"
  delegate_to: file_server

- name: select fs < 7 100g quotas set and < 700GB utilized
  tags: xfs
  debug: var=item.homedir
  when: item.qpresent < 7 and item.usage < 734003200
  with_random_choice: "{{ qusage }}"
  #with_items: "{{ qusage }}"
  register: chosenfs

```
I prefer **with_random_choice** over **with_items** since I want a random file system selected from among those below the quota and utilization threshold

These conditionals all skip using both with_items and with_random_choice:

```yaml
when: item.qpresent < '7' and item.usage < '734003200'
when: "item.qpresent < '7' and item.usage < '734003200'"
when: (item.qpresent < 7 and item.usage < 734003200)
when: "(item.qpresent < '7' and item.usage < '734003200')"
when: "(item.qpresent < '7' and item.usage < '734003200')"
when: "(item.qpresent < 7 and item.usage < 734003200)"
```

All deprecated jinja2, with below as a single example as I don't want to write ever single variation, also seem to fail:

```yaml
when: "{{ item.qpresent < '7' and item.usage < '734003200' }}"
```

Note, adding **item.qpresent|int** and **item.usage|int** with the above does not work, either.

##### EXPECTED RESULTS

The Task would randomly select a home directory among those which have less than 7 quotas present, item.qpresent, and under 734003200 utilized, shown as item.usage.

##### ACTUAL RESULTS

```
TASK [accounts : print quotausage] *************************************************************************************************************************************************************************************************[973/1993]
task path: /home/douglas/repos/ansible/playbooks/roles/accounts/tasks/xfs.yml:57
ok: [login_node -> file_server] => (item={'usage': [u'18299616'], 'homedir': u'/homes042', 'qpresent': [u'1']}) => {
    "item": {
        "homedir": "/homes042", 
        "qpresent": [
            "1"
        ], 
        "usage": [
            "18299616"
        ]
    }, 
    "item.qpresent": [
        "1"
    ]
}
ok: [login_node -> file_server] => (item={'usage': [u'714188'], 'homedir': u'/homes043', 'qpresent': [u'0']}) => {
    "item": {
        "homedir": "/homes043", 
        "qpresent": [
            "0"
        ], 
        "usage": [
            "714188"
        ]
    }, 
    "item.qpresent": [
        "0"
    ]
}
ok: [login_node -> file_server] => (item={'usage': [u'34212'], 'homedir': u'/homes044', 'qpresent': [u'0']}) => {
    "item": {
        "homedir": "/homes044", 
        "qpresent": [
            "0"
        ], 
        "usage": [
            "34212"
        ]
    }, 
    "item.qpresent": [
        "0"
    ]
}
```

```
TASK [accounts : select fs < 7 100g quotas set and < 700GB utilized] ************************************************************************************************************************************************************************$
task path: /home/douglas/repos/ansible/playbooks/roles/accounts/tasks/xfs.yml:67
skipping: [login_node] => (item={'usage': [u'18299616'], 'homedir': u'/homes042', 'qpresent': [u'1']})  => {
    "changed": false, 
    "item": {
        "homedir": "/homes042", 
        "qpresent": [
            "1"
        ], 
        "usage": [
            "18299616"
        ]
    }, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
skipping: [lodin_node] => (item={'usage': [u'714188'], 'homedir': u'/homes043', 'qpresent': [u'0']})  => {
    "changed": false, 
    "item": {
        "homedir": "/homes043", 
        "qpresent": [
            "0"
        ], 
        "usage": [
            "714188"
        ]
    }, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
skipping: [login_node] => (item={'usage': [u'34212'], 'homedir': u'/homes044', 'qpresent': [u'0']})  => {
    "changed": false, 
    "item": {
        "homedir": "/homes044", 
        "qpresent": [
            "0"
        ], 
        "usage": [
            "34212"
        ]
    }, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
```

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ifelsefi** [comment]
Hi @bcoca 

You helped me with #16315

Any idea what's happening now?

**Comment by ifelsefi** [comment]
Hmm

This seems to at least do something like I want:

```yaml

- name: select fs < 7 100g quotas set and < 700GB utilized
  tags: xfs
  debug: var=item
  with_random_choice: "{{ qusage }}"
  register: chosenfs
  retries: 20
  delay: 1
  until: item.qpresent < 7

```


```
TASK [accounts : select fs < 7 100g quotas set and < 700GB utilized] *************************************************************************************************************************************************************************
FAILED - RETRYING: select fs < 7 100g quotas set and < 700GB utilized (20 retries left).Result was: {
    "attempts": 1, 
    "item": {
        "homedir": "/homes055", 
        "qpresent": [
            "15"
        ], 
        "usage": [
            "785833612"
        ]
    }, 
    "retries": 21
}
FAILED - RETRYING: select fs < 7 100g quotas set and < 700GB utilized (19 retries left).Result was: {
    "attempts": 2, 
    "item": {
        "homedir": "/homes055", 
        "qpresent": [
            "15"
        ], 
        "usage": [
            "785833612"
        ]
    }, 
    "retries": 21
}
```

**Comment by ifelsefi** [comment]
Never mind

```yaml
FAILED - RETRYING: select fs < 7 100g quotas set and < 700GB utilized (6 retries left).Result was: {
    "attempts": 15, 
    "item": {
        "homedir": "/homes043", 
        "qpresent": [
            "0"
        ], 
        "usage": [
            "715040"
        ]
    }, 
    "retries": 21
```
