### ISSUE TITLE
Meta task include_role doesn't apply become/sudo flag on task to handlers

### ISSUE THREAD

**Issue by karlmdavis** [ansible/ansible#29159]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`include_role`

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.3.2.0
  config file = /home/karl/workspaces/cms/bluebutton-sandbox.git/ansible.cfg
  configured module search path = [u'/home/karl/.ansible/roles']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
```
$ cat ansible.cfg 
[defaults]

# Look for the Ansible Vault password in this (.gitignore'd) file.
# If you need this password, please contact karl.davis@cms.hhs.gov.
vault_password_file = vault.password

# Automatically accept SSH thumbprints when machines are provisioned.
host_key_checking = False

# Ensures that roles & modules installed from install_roles.yml can be used.
roles_path = ~/.ansible/roles
library = ~/.ansible/roles

# Workaround for https://github.com/ansible/ansible/issues/13278.
timeout = 120

[ssh_connection]
ssh_args=-o ForwardAgent=yes

# Significantly speeds up Ansible processing. Note: RHEL 7 systems have 
# `requiretty` enabled by default, which will prevent this from working until
# it's addressed.
pipelining = true
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Using `include_role` on a role with `become: true` doesn't run handler tasks with `sudo`, causing them to fail.

##### STEPS TO REPRODUCE
Here's the exact play I was using. You should be able to point it at any file and see the issue.
```yaml
- name: Configure Blue Button Data Server
  hosts: backend_fhir_master
  tasks:
    - name: Apply AWS CloudWatch Logs Agent Role
      include_role:
        name: singleplatform-eng.awslogs
      vars:
        awslogs_config:
          - file: /usr/local/bluebutton-data-server/bluebutton-server-app.log
            datetime_format: '%Y-%m-%d %H:%M:%S,%f'
            initial_position: 'start_of_file'
            log_group_name: 'bluebutton-sandbox-backend/data-server/bluebutton-data-server-app.log'
            log_stream_name: '{instance_id}'
            buffer_duration: 5000
      become: true
```

##### EXPECTED RESULTS
I expected it to run all tasks and handlers using `sudo`.

##### ACTUAL RESULTS
Instead, it only ran the tasks with `sudo` -- not the handler(s).

```
... # trimmed to reduce noise

TASK [singleplatform-eng.awslogs : Create logstream configuration] *********************************************************************************************
changed: [backend_fhir_master]

TASK [singleplatform-eng.awslogs : Start and enable awslogs service] *******************************************************************************************
skipping: [backend_fhir_master]

TASK [singleplatform-eng.awslogs : Start and enable awslogs systemd service] ***********************************************************************************
skipping: [backend_fhir_master]

RUNNING HANDLER [singleplatform-eng.awslogs : restart awslogs] *************************************************************************************************
fatal: [backend_fhir_master]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service awslogs: Failed to restart awslogs.service: Interactive authentication required.\n"}
        to retry, use: --limit @/home/karl/workspaces/cms/bluebutton-sandbox.git/sandbox.retry

PLAY RECAP *****************************************************************************************************************************************************
backend_fhir_master        : ok=31   changed=23   unreachable=0    failed=1
```

**Comment by karlmdavis** [comment]
My workaround is to run it in a separate play and not use `include_role`. For example:

```
- name: Configure AWS CloudWatch Logs Agent
  hosts: backend_fhir_master
  become: true
  roles:
    - role: singleplatform-eng.awslogs
      awslogs_config:
        - file: /usr/local/bluebutton-data-server/bluebutton-server-app.log
          datetime_format: '%Y-%m-%d %H:%M:%S,%f'
          initial_position: 'start_of_file'
          log_group_name: 'bluebutton-sandbox-backend/data-server/bluebutton-data-server-app.log'
          log_stream_name: '{instance_id}'
          buffer_duration: 5000
```

This works as expected, where the `include_role` does not.
