### ISSUE TITLE
missing required arguments: db

### ISSUE THREAD

**Issue by magick93** [ansible/ansible#29177]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
http://docs.ansible.com/ansible/latest/postgresql_db_module.html

##### ANSIBLE VERSION
```
ansible --version               
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### OS / ENVIRONMENT
Ubuntu 17.04

##### SUMMARY
Trying to run:

```
    - postgresql_db:
      name: acme
```

Or even

```
    - postgresql_db:
      name: acme
      become: true
      become_user: postgres
```

Results in:

```
TASK [acme] *************************************************************************************************************************************************************
fatal: [88.198.37.183]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: db"}
	to retry, use: --limit @/home/anton/git/hughestech/openshift-material/openshift-server/pg-listenip.retry

PLAY RECAP **************************************************************************************************************************************************************
88.198.37.183              : ok=3    changed=1    unreachable=0    failed=1   
```

##### STEPS TO REPRODUCE
Complete playbook is

```
---
- hosts: prod3

  tasks:


    - copy:
       src: ./setup/files/postgresql.conf
       dest: /var/lib/pgsql/data/postgresql.conf


    - name: restart postgresql
      service: name=postgresql state=restarted

    - postgresql_db:
      name: acme
      become: true
      become_user: postgres


```

##### EXPECTED RESULTS
Expect a postgres database to be created

##### Additional

The error message alludes to a missing `db` argument, yet there is no mention of this in the docs.
