### ISSUE TITLE
AWS Lambda module enhancements for tracing and KMS key setup

### ISSUE THREAD

**Issue by mskarbek** [ansible/ansible#29173]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible/lib/ansible/modules/cloud/amazon/lambda.py

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jun 26 2017, 10:20:05) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

```

##### SUMMARY
Lamda module doesn't allow setting tracing mode nor KMS key for function. It would be a good idea to extend module to cover that functionality.

##### STEPS TO REPRODUCE
```yaml
    - lambda:
        region: us-west-1
        state: present
        name: function-name
        zip_file: file.jar
        runtime: java8
        memory_size: 960
        timeout: 60
        role: arn:aws:iam::111111111111:role/lambda-role
        handler: handler
        kms_key_arn: arn:aws:kms:us-west-1:111111111111:key/3dc35430-924f-4921-a70e-f74e6d57e0e0
        tracing_config: Active
```

##### EXPECTED RESULTS
Module creates/updates Lambda function with appropriate configuration.
