### ISSUE TITLE
github_deploy_key is not working

### ISSUE THREAD

**Issue by ojhaujjwal** [ansible/ansible#29183]
Tested in branch devel and v2.4.0.0-0.1.rc1

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
github_deploy_key

##### ANSIBLE VERSION
ansible 2.5.0 (devel ab7c850360) last updated 2017/09/10 17:24:04 (GMT +575)
  config file = /home/ujjwal/projects/std/infrastructure/ansible.cfg
  configured module search path = [u'/home/ujjwal/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ujjwal/Programs/ansible/lib/ansible
  executable location = /home/ujjwal/Programs/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

##### CONFIGURATION
```
[defaults]
host_key_checking = False
roles_path=./vendor
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
It says ok but, I don't see any deploy key added in repo settings.

##### STEPS TO REPRODUCE
Add the task and run the playbook,

```yaml
  - name: Add deployment key to github
    github_deploy_key:
      owner: "{{ lookup('ini', 'GITHUB_REPO_OWNER file=../local.ini') }}"
      repo: "{{ lookup('ini', 'GITHUB_REPO file=../local.ini') }}"
      name: "std-prod-key" #TODO: deploy key name    
      force: yes
      read_only: yes
      key: "{{ lookup('file', '/home/ujjwal/.ssh/id_rsa.pub') }}"
      token: "{{ lookup('ini', 'GITHUB_TOKEN file=../local.ini') }}"
```

##### EXPECTED RESULTS
Deploy key in repo settings.

##### ACTUAL RESULTS
No deploy key was seen in repo settings.

**Comment by ansibotdev** [comment]
cc @bincyber
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
cc @bincyber

**Comment by ojhaujjwal** [comment]
okay. one mistake I have found from my end is that I was trying to add the pub key of the local machine instead of the target machine and it worked after I fixed my part.
but, the issue is still there with local machine pub key. I tried to run the playbook with `-vvv` and as it turns out, the issue is `key is already in use`. the pub key of my local machine was there in my account and it seems GitHub doesn't accept even when the same key is used as deploy key. 
I think a proper error message needs to be shown here like `key is already in use` so that users are not left confused when it says ok but there's nothing really done.

**Comment by bincyber** [comment]
@ojhaujjwal Thanks for submitting this issue. Help me understand what the problem is a little better. When `force` is set to yes/true, the module should delete the existing key and add a new key. However, you found that this was not the case? The `Deploy key already exists` message is returned when the module tries to add a deploy key, but the GitHub API returns a 422 status code indicating that the deploy key is already associated with the repository.

**Comment by Akasurde** [comment]
@ojhaujjwal Could you please provide required information ? 

needs_info

**Comment by cwilby** [comment]
For those coming from Google, the [Ansible docs](https://docs.ansible.com/ansible/2.4/github_deploy_key_module.html) cover creating an SSH key on the client and copying to the target.  However in my case I wanted to generate a deploy key on the target and add it to a GitHub repo via OAuth2.

Here's how I got around the issue:

Before - Not working due to local scope in `lookup` function.
```yml
- name: Provision keys
  hosts: production
  user: "{{web_user}}"
  tasks:
    - name: Generate SSH keys
      shell: ssh-keygen -b 4096 -t rsa -f ~/.ssh/id_rsa -q -N ""
      args:
        creates: ~/.ssh/id_rsa
    - name: Provision deploy key
      github_deploy_key:
        owner: "cwilby"
        repository: "cisco247"
        name: "cisco247 deploy key"
        key: "{{ lookup('file', '/home/{{web_user}}/.ssh/id_rsa.pub') }}"
        force: yes
        token: "{{github_token}}"
```

After - uses [slurp](https://docs.ansible.com/ansible/2.6/modules/slurp_module.html) to read the pubkey into a variable
```yml
- name: Provision keys
  hosts: production
  user: "{{web_user}}"
  tasks:
    - name: Generate SSH keys
      shell: ssh-keygen -b 4096 -t rsa -f ~/.ssh/id_rsa -q -N ""
      args:
        creates: ~/.ssh/id_rsa
    - name: Read the pub key
      slurp:
        src: "/home/{{web_user}}/.ssh/id_rsa.pub"
      register: pubkey
    - name: Provision deploy key
      github_deploy_key:
        owner: "cwilby"
        repository: "cisco247"
        name: "cisco247 deploy key"
        key: "{{pubkey}}"
        force: yes
        token: "e96083742407600bbc62cef62ec946cdc5373d7b"
```

**Comment by giemsky** [comment]
@cwilby slurp returns read file content as encoded as base64 string, you should decode it before using in `github_deploy_key` task:
```
    - name: Provision deploy key
      github_deploy_key:
        owner: "{{repo_owner}}"
        repository: "{{repo_name}}"
        name: "deploy key"
        key: "{{ pubkey['content'] | b64decode }}"
        force: yes
        token: "{{github_token}}"
```
