### ISSUE TITLE
lxc_container::container_config : python dict ain't gonna work: ordered list

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29218]
From @X-Cli on 2015-08-15T16:56:46Z
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

lxc_container module
##### ANSIBLE VERSION

`container_config` is parsed as a python dict by the ansible **lxc_container module**, at least in current stable version 1.9.
##### SUMMARY

`container_config` is parsed as a Python dict by the ansible **lxc_container module**, at least in current stable version 1.9.

https://github.com/ansible/ansible-modules-extras/blob/stable-1.9/cloud/lxc/lxc_container.py
Lines 1442 to 1444 :

``` python
container_config=dict(
  type='str'
),        
```

Python dict are _unordered_, which may lead to **corrupted config files**. For instance, config directives for LXC network follow _a specific order_, which is overlooked by the module when the config file is written on disk.

As such, the following playbook excerpt

```
  tasks:
    - include_vars: ../vars/lxc_config.yml
    - include_vars: ../globals.yml
    - name: "Create LXC"
      become: yes
      become_method: sudo
      lxc_container: 
        name: "{{ lxc_name }}"
        state: stopped
        lxc_path: /var/lib/lxc
        template: ubuntu
        container_config:
          - "lxc.network.type = veth"
          - "lxc.network.name = internet"
          - "lxc.network.ipv4 = {{ internet_ip }}"
          - "lxc.network.link = internet_br"
          - "lxc.network.flags = up"
          - "lxc.network.type = veth"
          - "lxc.network.name = local"
          - "lxc.network.ipv4 = {{ local_ip }}"
          - "lxc.network.link = local_br"
          - "lxc.network.flags = up"
          - "lxc.network.type = veth"
          - "lxc.network.name = admin"
          - "lxc.network.ipv4 = {{ admin_ip }}"
          - "lxc.network.ipv4.gateway = {{ admin_gateway }}"
          - "lxc.network.link = admin_br"
          - "lxc.network.flags = up"
```

results in the following broken LXC config file

```
# Network configuration
lxc.network.type = veth
lxc.network.type  =  veth
lxc.network.flags = up
lxc.network.flags  =  up
lxc.network.link = lxcbr0
lxc.network.link  =  admin_br
lxc.network.link  =  local_br
lxc.network.link  =  internet_br
lxc.network.hwaddr = 00:16:3e:f1:f5:8e
lxc.network.name  =  internet
lxc.network.name  =  admin
lxc.network.name  =  local
lxc.network.ipv4  =  172.31.0.1
lxc.network.ipv4  =  192.168.0.1
lxc.network.ipv4  =  10.0.0.1
lxc.network.ipv4.gateway  =  192.168.0.254
```

As you can see, parsing in a dict also deduplicates some crucial config lines, which have to be duplicated in a valid LXC config file.

Being completely new to Ansible (this was my very first playbook _sigh_), I am not sure if there is a workaround (except maybe using a templated config file and avoiding `container_config` altogether). Still, if the `container_config` could be handled as an ordered YAML sequence, I believe this could solve the problem.

Thank you.

Copied from original issue: ansible/ansible-modules-extras#836
