### ISSUE TITLE
known_hosts module not removing all matching keys (hashed keys)

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29224]
From @jxn on 2015-09-01T02:29:04Z
##### Issue Type:

Bug Report
##### Component Name:

known_hosts
##### Ansible Version:

`$ ansible --version
ansible 1.9.2`
##### Ansible Configuration:

custom log path, manually enable ssh forwarding
##### Environment:

Host: Ubuntu 15.04
Target: Ubuntu 14.04 LTS
##### Summary:

I've run a task with the known_hosts module on known_hosts files to replace old keys for a host with new keys.  The replacement is not performed.
##### Steps To Reproduce:

Begin with hashed hosts file, e.g.:

``` text
|1|LASKJDFindkslfjdsidfnalskeowjrlkfj...EFJKD=
|1|LASKJDFindkslfjdsidfnalskeowjrlkfj...EFJKD=
```

Run tasks:

``` yaml
- known_hosts: key="example.org" name="|1|LASKJDFindkslfjdsidfnalskeowjrlkfj...EFJKD=" state=absent
- known_hosts: key="example.org" name="|1|DDDDDDDDDDDDlskjdflksjldfkjj...ASDF=" state=present
```

FYI: I am using hashed keys.  I'm not sure if that is relevant.
##### Expected Results:

known_hosts file should read as follows (only one key, the new key):

``` text
1|DDDDDDDDDDDDlskjdflksjldfkjj...ASDF=
```
##### Actual Results:

known_hosts file contains both keys:

``` text
|1|LASKJDFindkslfjdsidfnalskeowjrlkfj...EFJKD=
|1|DDDDDDDDDDDDlskjdflksjldfkjj...ASDF=
```

Subsequent runs give the exact same result.  The state=absent key is never removed for the host.  Note that key has one and two are both for the same host name (the hash has changed for a domain).

Copied from original issue: ansible/ansible-modules-extras#903

**Comment by ansibot** [comment]
From @jxn on 2015-09-01T02:29:04Z

Does it work if you switch your key and name parameters?

```
- known_hosts: name="example.org" key="|1|LASKJDFindkslfjdsidfnalskeowjrlkfj...EFJKD=" state=absent
```

**Comment by ansibot** [comment]
From @jxn on 2015-09-01T02:29:04Z

@mcv21, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @jxn on 2015-09-01T02:29:04Z

@jxn ping, this issue is still waiting on your feedback. We will close the issue if you do not respond.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @jxn on 2015-09-01T02:29:04Z

@abadger I made a mistake in my example (copied out values into vars, but copied them inverted).  In my play they were right and still not removing the key

**Comment by abadger** [comment]
After reading through the module, I've figured out that this bug is actually an unintuitive format for the key parameter.  The key parameter is supposed to be the complete line that belongs in known_hosts (possibly repeating the name).  So the examples should look more like this:

```
- known_hosts:
    name: "example.org"
    key: "|1|8uCDGvRLNXsZOIVt3NrgpsjQbYU=|YpHzFbvVbmS8ur8t/s4uaJAKjGk= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDl28DzBLDWSNrMFgmhnHUTiC3mpdcucjAcP7KV0kqr/ZfAJr3QGwCem548esnlN8NqJe9MIHKMD6mbQJyXQJ8w=
    hash_host: True
    state: absent
- known_hosts:
    name: "example.org"
    key: "|1|8uCDGvRLNXsZOIVt3NrgpsjQbYU=|YpHzFbvVbmS8ur8t/s4uaJAKjGk= ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ=="
    state: present
```

Using keys like that, the first key is removed and the second key is ensured present.
