### ISSUE TITLE
Bug Report: Bower - No such file or directory

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29228]
From @MichielDeMey on 2015-09-10T21:25:09Z
Issue Type: Bug Report
Component Name: bower module
Ansible Version: ansible 1.9.3
Ansible Configuration: Clean (default)
Environment: Ubuntu 14.04.3 LTS, running inside Vagrant

Summary:
The Bower module reports the following error:

```
TASK: [web | Install dependencies (bower)] ************************************
failed: [default] => {"cmd": "bower list --json --config.interactive=false --allow-root", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory: 'docker/astromo.io/html'

FATAL: all hosts have already failed -- aborting
```

and is configured as such

```
- name: "Install dependencies (bower)"
  bower: path=docker/astromo.io/html state=latest
```

That directory however does exist on the machine.
As a workaround I'm using a command with the exact same directory, which seems to work just fine and installs all bower dependencies without any issues.

```
- name: "Install dependencies (bower)"
  command: bower --config.interactive=false install
  args:
    chdir: docker/astromo.io/html
```

I also checked the permissions and they look correct.
It might be that we have to expand the path before we use it like we did in the NPM module: https://github.com/ansible/ansible-modules-extras/commit/a2d440cceab66b0635d008c5b4b15952cb5abab0

Copied from original issue: ansible/ansible-modules-extras#956

**Comment by ansibot** [comment]
From @MichielDeMey on 2015-09-10T21:25:09Z

@MichielDeMey  +1 for the same issue. Facing same problem. Any other solution other than your workaround? because your workaround is not working for me.

**Comment by ansibot** [comment]
From @MichielDeMey on 2015-09-10T21:25:09Z

+1 for the issue, exactly same for me.  I got around it by doing this

```
- name: Install bower globally.
  npm: name=bower global=yes

- name: "Install dependencies (bower)"
  command: bower --config.interactive=false --allow-root install
  args:
    chdir: /var/www/my-server  
```

the --allow-root arg was required because of an error `stderr: bower ESUDO         Cannot be run with sudo`
