### ISSUE TITLE
Npm module gives errors

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29240]
From @frenkel on 2015-11-09T14:01:08Z

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
npm module

##### ANSIBLE VERSION
```
ansible 2.2.0 (devel 3d7a7c1612) last updated 2016/07/08 22:07:24 (GMT +300)
```

##### SUMMARY

I have this role:

```
- name: install node-sass, grunt, grunt-cli
  npm:
    executable: /usr/local/bin/npm
    global: true
    name: '{{ item }}'
    state: present
  with_items:
    - node-sass
    - grunt
    - grunt-cli
```

Using latest ansible 1.9-stable branch,  Node 5.0.0 or Node 0.10.4 I get these errors on some Mac OS systems:

```
failed: [xxx] => (item=node-sass) => {"failed": true, "item": "node-sass", "parsed": false}
Traceback (most recent call last):
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1447077541.45-221529250369756/npm", line 1876, in <module>
    main()
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1447077541.45-221529250369756/npm", line 244, in main
    installed, missing = npm.list()
  File "/Users/xxx/.ansible/tmp/ansible-tmp-1447077541.45-221529250369756/npm", line 168, in list
    data = json.loads(self._exec(cmd, True, False))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338
, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366,
 in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384,
 in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

What am I doing wrong?

Copied from original issue: ansible/ansible-modules-extras#1224

**Comment by ansibot** [comment]
From @frenkel on 2015-11-09T14:01:08Z

Btw, manually running `npm install node-sass grunt grunt-cli` installs without problems. Also running `npm list --json` doesn't seem to give wrong output.

**Comment by ansibot** [comment]
From @frenkel on 2015-11-09T14:01:08Z

[module: packaging/language/npm.py]

**Comment by ansibot** [comment]
From @frenkel on 2015-11-09T14:01:08Z

@frenkel -- Thanks for submitting this bug report.

@chrishoffman -- thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by ansibot** [comment]
From @frenkel on 2015-11-09T14:01:08Z

This issue seems to affect me as well for both:

```
- name: Upgrade npm
  npm:
    name: npm
    global: yes
    state: latest
    executable: "{{ node_path }}/npm"
```

and:

```
- name: Install npm requirements
  npm:
    path: "{{ conf.host_path }}/{{ project }}"
    state: latest
    executable: "{{ node_path }}/npm"
```

Traceback:

```
"module_stdout": "Traceback (most recent call last):
  File \"/tmp/ansible_Fudjxb/ansible_module_npm.py\", line 268, in <module>
    main()
  File \"/tmp/ansible_Fudjxb/ansible_module_npm.py\", line 253, in main
    installed, missing = npm.list()
  File \"/tmp/ansible_Fudjxb/ansible_module_npm.py\", line 172, in list
    data = json.loads(self._exec(cmd, True, False))
  File \"/usr/lib/python2.7/json/__init__.py\", line 326, in loads
    return _default_decoder.decode(s)
  File \"/usr/lib/python2.7/json/decoder.py\", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File \"/usr/lib/python2.7/json/decoder.py\", line 384, in raw_decode
    raise ValueError(\"No JSON object could be decoded\")
ValueError: No JSON object could be decoded
```

Ansible version:

```
ansible 2.2.0 (devel 3d7a7c1612) last updated 2016/07/08 22:07:24 (GMT +300)
```

**Comment by ansibot** [comment]
From @frenkel on 2015-11-09T14:01:08Z

Up. I've reproduced this situation

**Comment by ansibot** [comment]
From @frenkel on 2015-11-09T14:01:08Z

Fails here too, same example. Only workaround is to manually run `npm install` for now?

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rockholla** [comment]
Also ran into this using the following:
```
- name: Get npm executable path
  shell: >
    . ~/.nvm/nvm.sh && which npm
  register: which_npm
  changed_when: false

- name: Ensure configured npm packages are installed globally
  npm:
    executable: "{{ which_npm.stdout }}"
    global: yes
    name: "{{ item }}"
  with_items: "{{ node_npm_global_packages }}"
```

Here's a workaround that seems to be going pretty well for me so far:
```
- name: Ensure configured npm packages are installed globally
  shell: >
    . ~/.nvm/nvm.sh && ((npm list -g | grep " {{ ('@' in item) | ternary(item,item + '@*') }}") || (npm install -g {{ item }} && echo "node-global-package-installed"))
  with_items: "{{ node_npm_global_packages }}"
  register: node_npm_global_package_install
  changed_when: "'node-global-package-installed' in node_npm_global_package_install.stdout"
  failed_when: "'npm ERR!' in node_npm_global_package_install.stderr"
```

**Comment by bertramn** [comment]
Seems to be related to the setting of the environment. It fails when using `executable` but the below works fine:

```yaml
- name: Install Yarn
  npm:
    name: yarn
    global: yes
    production: yes
    state: latest
    #executable: "{{ node_home }}/bin/npm" << does not work
  environment:
    PATH: "{{ node_home }}/bin:{{ ansible_env.PATH }}"
```

**Comment by ansibot** [comment]
cc @xcambar
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by xcambar** [comment]
Hi,
Can the issue be reproduced with a recent ansible (2.4 or devel)?

As the new maintainer of the npm module, I am flooded by year-old issues. So as a triage strategy, any silent issue will be closed after 10 days unless you confirm your issue still exists in recent versions.

**Comment by xcambar** [comment]
Closing for lack of response.

close_me

**Comment by ingnil** [comment]
I can reproduce the bug using a devel version (HEAD cloned today). Task and output follows:

```
- name: Install Node package Mochito
  become: true
  npm:
    name: mochito
    global: yes
    executable: /usr/local/bin/npm
```

Output:

```
Traceback (most recent call last):
  File "/tmp/ansible_wHfn0w/ansible_module_npm.py", line 291, in <module>
    main()
  File "/tmp/ansible_wHfn0w/ansible_module_npm.py", line 268, in main
    installed, missing = npm.list()
  File "/tmp/ansible_wHfn0w/ansible_module_npm.py", line 192, in list
    data = json.loads(self._exec(cmd, True, False))
  File "/usr/lib64/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

On the other hand, just like for bertramn, if I change the task to below, it works fine:

```
- name: Install Node package Mochito
  become: true
  npm:
    name: mochito
    global: yes
#    executable: /usr/local/bin/npm
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
```

**Comment by eugenetaranov** [comment]
me too, version 2.4.2.0
@xcambar could you please reopen the ticket?

**Comment by fabiel-leon** [comment]
tha same issue with ansible version 2.4.3.0 

```
- name: Install forever node.js package globally.
  npm:
    name: "{{ item }}"
    global: yes
    executable: "{{ nvm_root }}/versions/node/{{ node_version }}/bin/npm"
  with_items:
    - forever
```

**Comment by curiousercreative** [comment]
This task failed for me with similar error
Ansible: 2.7.1
macOS: 10.13.6 (17G3025)
Python: 3.7.1
NodeJS: 8.10.0
```
- name: Install gulp-cli globablly
  npm:
    name: gulp-cli
    global: yes
```

After some debugging, this was traced back to a wonky install of `npm` itself. Try uninstalling node/npm and reinstalling and/or trying some tips [here](https://stackoverflow.com/questions/11177954/how-do-i-completely-uninstall-node-js-and-reinstall-from-beginning-mac-os-x) specifically the `brew doctor && brew prune` for Mac users.
