### ISSUE TITLE
User creation always reports 'changed' status on FreeBSD 9.1

### ISSUE THREAD

**Issue by ScottSturdivant** [ansible/ansible#2924]
Given this playbook:

```

---

- hosts: admin
  sudo: True
  user: vagrant
  vars:
    - ansible_python_interpreter: /usr/local/bin/python
  tasks:
    - name: Create server group
      group: name=server gid=1010
    - name: Create server user
      user: name=server uid=1010 comment="Server" home=/usr/home/server groups=server shell=/bin/tcsh
```

Every time I run this, I always get "changed" status on the user action.  The first time I would expect this, as the user is being created initially.  The second time however, I would not expect anything to change.

First run, both the group and user are created properly:
    $ ansible-playbook -i devops/hosts devops/admin.yml

```
PLAY [admin] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [192.168.2.100]

TASK: [Create server group] *************************************************** 
changed: [192.168.2.100]

TASK: [Create server user] **************************************************** 
changed: [192.168.2.100]

PLAY RECAP ******************************************************************** 
192.168.2.100              : ok=3    changed=2    unreachable=0    failed=0   
```

Second run (and subsequent ones as well), group is ok, but user is again changed.
    $ ansible-playbook -i devops/hosts devops/admin.yml

```
PLAY [admin] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [192.168.2.100]

TASK: [Create server group] *************************************************** 
ok: [192.168.2.100]

TASK: [Create server user] **************************************************** 
changed: [192.168.2.100]

PLAY RECAP ******************************************************************** 
192.168.2.100              : ok=3    changed=1    unreachable=0    failed=0   
```

My ansible version info:
$ ansible --version  
ansible 1.2 (devel d29d142a2d) last updated 2013/05/15 10:23:00 (GMT -600)
