### ISSUE TITLE
nmcli reports fail, even though success

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29266]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
`2.0.0.2`

##### SUMMARY
From @larstobi on 2016-02-09T09:27:42Z
_Description:_

When trying to configure a secondary NIC with nmcli, I get an error, but it actually looks like success.

_Task:_

```
- name: "Configure secondary NIC eth1"
  nmcli: conn_name=eth1 type=ethernet mtu=1500 state=present
```

_Error message:_

TASK [network : Configure secondary NIC eth1] ************************
fatal: [terraform0]: FAILED! => {"changed": false, "cmd": [0, "Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/17)\n", ""], "failed": true, "msg": "Argument 'args' to run_command must be list or string", "rc": 257}

_Versions:_
- Ansible 2.0.0.2
- Client OS: Mac OS X Yosemite
- Target OS: CentOS 7 (with latest patches from stable)

Copied from original issue: ansible/ansible-modules-extras#1637

**Comment by ansibot** [comment]
From @gregdek on 2016-02-09T09:27:42Z

@alcamie101 ping -- can you take a look at this issue?

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sedrubal** [comment]
I have the same issue and I want to try to give the required information:

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

*Versions*
    Client OS: Fedora 26 Workstation
    Target OS: Fedora 26 Server Edition (with python3 interpreter)

**Comment by Akasurde** [comment]
@sedrubal Could you please provide your playbook, additional details and error console?

needs_info

**Comment by ansibot** [comment]
@ansibot You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr #31550

**Comment by sedrubal** [comment]
@Akasurde I'm not totally sure, if it was caused by this playbook, because I reported this long time ago.

```yaml
- name: configure dmz network
  nmcli:
    type: ethernet
    conn_name: dmz
    ifname: '{{ network.dmz.ifname }}'
    dns4: '{{ network.dmz.ipv4.dns }}'
    gw4: '{{ network.dmz.ipv4.gateway }}'
    ip4: '{{ network.dmz.ipv4.addresses }}'
    state: present
  tags:
    - common-network-dmz
```

This are the variables

```yaml
---
network:
  dmz:
    ifname: 'enp0s20f2'
    ipv4:
      addresses: '192.168.10.11'
      gateway: ''
      dns: ''
...
```

This is the output of `ansible-playbook --diff`:

```
TASK [common : configure dmz network] *********************************************************************************
fatal: [foo.bar.de]: FAILED! => {"changed": false, "cmd": [0, "Connection successfully activated (D-Bus active path: /org/freedesktop/NetworkManager/ActiveConnection/5)\n", ""], "msg": "Argument 'args' to run_command must be list or string", "rc": 257}
```

When I run `ansible-playbook --diff` again, there is no additional output:

```
TASK [common : configure dmz network] *********************************************************************************
changed: [foo.bar.de]
```
