### ISSUE TITLE
Jira custom fields not accepting integer variables

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29262]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
jira

##### ANSIBLE VERSION
`2.3`

##### SUMMARY

From @hdsiles on 2016-01-27T00:27:43Z
https://github.com/ansible/ansible-modules-extras/blob/devel/web_infrastructure/jira.py

I am running into a problem I don't know how to get past.  I am trying to use the Jira module to create an issue with a custom field.  That field is for story point values which require being an integer to perform math against the value.  As such I am defining a variable from a vars file which is an integer, and appears to remain an integer until it gets passed into the jira module specifically the custom field.

In the first example I have added 'item.story_points' in a predefined option of summary as well the custom field customfield_10008 and the integer type remains consistent as an integer with or without the  'int' jinja2 filter applied but only in the summary option.  The customfield_10008 entry gets converted to a string.
### This will not work

```
- name: Create an issue
  jira: uri={{ url }} username={{ myuser }} password={{ mypass }} project={{ project }} operation=create issuetype=Story description={{ item.description }} summary={{ item.story_points | int }}
  args:
    fields:
      customfield_10008: "{{ item.story_points | int }}"
  with_items: "{{ stories }}"
```

If I change the customfield_10008 field entry to a hard coded number the module interprets the value as a number, and runs successfully. 
### This does work

```
- name: Create an issue
  jira: uri={{ url }} username={{ myuser }} password={{ mypass }} project={{ project }} operation=create issuetype=Story description={{ item.description }} summary={{ item.story_points | int }}
  args:
    fields:
      customfield_10008: 2
  with_items: "{{ stories }}"
```

Perhaps there is another method to enter a value for a custom field, but based on the documentation for this module, I was not sure how that syntax would look.

http://docs.ansible.com/ansible/jira_module.html

Copied from original issue: ansible/ansible-modules-extras#1560
