### ISSUE TITLE
s3_bucket fails when loading JSON policy from a template

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29283]
From @njsaunders on 2016-03-08T15:14:09Z
##### Issue Type:
- Bug Report
##### Component Name:

s3_bucket.py
##### Ansible Version:

```
ansible 2.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

Loading an S3 bucket policy from a file results in failure due to various silent conversions performed by the lookup function, ansible core, and the s3_bucket function itself.
##### Steps To Reproduce:

For bugs, please show exactly how to reproduce the problem. For new
features, show how the feature would be used.

Playbook:

```
  vars:
    domain: "example.com"
    envname: "stage"
    aws_account_number: "12345678"
    region: "us-west-2"
    s3_bucket_name: "{{domain | regex_replace('\\.', '-')}}-{{envname}}-{{aws_account_number}}"
    elb_principal_mappings:
      us-east-1: 127311923021
      us-west-2: 797873946194
      us-west-1: 027434742980
      eu-west-1: 156460612806
      eu-central-1: 054676820928
      ap-southeast-1: 114774131450
      ap-northeast-1: 582318560864
      ap-southeast-2: 783225319266
      ap-northeast-2: 600734575887
      sa-east-1: 507241528517
    - name: Create S3 asset bucket
      s3_bucket:
        name: "{{ s3_bucket_name }}"
        region: "{{ region }}"
        policy: "{{ lookup('template', './s3_bucket_policy.json.j2', convert_data=False) }}"
      register: site_s3_bucket
```

Template (Could be anything but just for completeness):

```
{
  "Id": "AllowELBWriteAccess",
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "Stmt1454671534294",
      "Action": [
        "s3:PutObject"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::{{domain | regex_replace('\.', '-')}}-{{envname}}-{{aws_account_number}}/accesslogs/AWSLogs/{{ aws_account_number }}/*",
      "Principal": {
        "AWS": [
          "{{ elb_principal_mappings[region] }}"
        ]
      }
    }
  ]
}

```
##### Expected Results:

An S3 bucket is created
##### Actual Results:

Failure incorrectly implying that that the JSON is invalid.

```
TASK [Create S3 asset bucket] **************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Policies must be valid JSON and the first byte must be '{'"}
```

Copied from original issue: ansible/ansible-modules-extras#1813

**Comment by ansibot** [comment]
From @wimnat on 2016-03-08T15:14:09Z

I'll have to look further in to this because it wasn't broken in 1.x and possibly 2.0

**Comment by ansibot** [comment]
From @Constantin07 on 2016-03-08T15:14:09Z

Ran into the same issue.
It turns out that the Fix #1813 doesn't solve the problem. Still get the same error.
Using 'file' instead of 'template' in lookup doesn't help too.

```
  - name: Create S3 bucket
    s3_bucket:
      region: "{{ aws_region }}"
      name: "{{ s3_bucket_name }}"
      policy: "{{ lookup('file', './s3_policy.json') }}"
      state: present
```

```
TASK [Create S3 bucket] ********************************************************
task path: /home/endavaMgmt/test_scripts/ansible/s3.yml:13
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Policies must be valid JSON and the first byte must be '{'"}
```

PS: The s3_policy.json policy is valid if I paste it directly in AWS Management Console.

**Comment by ansibot** [comment]
From @wimnat on 2016-03-08T15:14:09Z

@Constantin07 have you managed to test this with 1.9?

**Comment by ansibot** [comment]
From @Constantin07 on 2016-03-08T15:14:09Z

Yeah, just did it.

```
# ansible --version
ansible 1.9.4
  configured module search path = ./library/

# ansible-playbook s3.yml -v

PLAY [localhost] **************************************************************

TASK: [Create S3 bucket] ******************************************************
failed: [127.0.0.1] => {"failed": true}
msg: Policies must be valid JSON and the first byte must be '{'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/tmp/s3.retry

127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1

```

**Comment by ansibot** [comment]
From @fvant on 2016-03-08T15:14:09Z

It works in 2.0.2.0  (from normal pip install) but no longer in devel.

(but i needed devel because stuff was broken in elasticache in 2.0.2)

**Comment by ansibot** [comment]
From @bcoca on 2016-03-08T15:14:09Z

see if this fixes it #2126

**Comment by ansibot** [comment]
From @Constantin07 on 2016-03-08T15:14:09Z

Thanks @bcoca but with #2126 I get:

```
TASK [Create S3 bucket] ********************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "JSON parsing error"}

```

**Comment by ansibot** [comment]
From @wimnat on 2016-03-08T15:14:09Z

I've posted the following question which I think will help us on the way to solving this...

https://groups.google.com/forum/#!topic/ansible-devel/2C7pl2_kxlY

**Comment by ansibot** [comment]
From @bossjones on 2016-03-08T15:14:09Z

Seeing the same issue in 2.1.0 as well.

```
± |persistent {1} U:3 ?:2 ✗| → ansible --version
ansible 2.1.0 (devel 3b667e48ff) last updated 2016/04/01 12:53:28 (GMT -400)
  lib/ansible/modules/core: (detached HEAD 7080dd057b) last updated 2016/04/01 12:53:30 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 7ce47aff79) last updated 2016/04/01 12:53:32 (GMT -400)
  config file = /Users/malcolm/dev/behanceops/ansible/ansible.cfg
  configured module search path = ['/Users/malcolm/dev/ansible/ansible/lib/ansible/modules/core', '/Users/malcolm/dev/ansible/ansible/lib/ansible/modules/extras']
```

**Comment by ansibot** [comment]
From @tjbaker on 2016-03-08T15:14:09Z

Cross ref issue #15603
https://github.com/ansible/ansible/issues/15603

Unfortunately the workaround mentioned that helps with the `policy_json` arg does not help with s3_bucket's `policy` arg.
https://github.com/ansible/ansible/issues/15603#issuecomment-223919120

**Comment by ansibot** [comment]
From @pierreant-p on 2016-03-08T15:14:09Z

+1

**Comment by ansibot** [comment]
From @martinm82 on 2016-03-08T15:14:09Z

I got also hit by this issue now using Ansible 2.1. Any progress on this issue?

**Comment by ansibot** [comment]
From @abondis on 2016-03-08T15:14:09Z

what about using `|to_json` does it help ? https://github.com/ansible/ansible/issues/15603#issuecomment-231202016

**Comment by ansibot** [comment]
From @martinm82 on 2016-03-08T15:14:09Z

Does not work for me. I switched for now to 2.0.2.0

**Comment by ansibot** [comment]
From @borgstrom on 2016-03-08T15:14:09Z

I've just run into this as well.  Any movement on either PR @bcoca or @trinitronx?

Or is there any work around?

**Comment by ansibot** [comment]
From @rsltrifork on 2016-03-08T15:14:09Z

Hit the same issue and haven't found any workarounds. Not even pre-generating the policy as a file and using  `policy: "{{ lookup('file','/tmp/policy.json') }}"` works.
Neither does inlining the policy json in the task. I always get:

"Policies must be valid JSON and the first byte must be '{'"

s3 policy support seems completely broken in 2.1.1.0

**Comment by ansibot** [comment]
From @bcoca on 2016-03-08T15:14:09Z

For 2.2 fixed by 6402d36af3db7cc556cca0dd6fa31e75a8e24013 but it is not backwards compatible. 

I added #2735 as a backport as possible fix for this in 2.1, please test as I don't currently have access to s3.

**Comment by ansibot** [comment]
From @bryanhiestand on 2016-03-08T15:14:09Z

This broke somewhere between 2.0.1.0 and 2.1.1.0

#2735 did not resolve this for me in 2.1.1.0.  I now get "This policy contains invalid Json".  Running the same template and play through 2.0.1 still work.

I am extremely concerned if core back-end behavior in 2.1 caused this to break playbooks that have not changed since 2.0.  Is 2.1 not backward compatible for playbooks and extras modules?

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @yarinkos on 2016-03-08T15:14:09Z

any workaround?

**Comment by ansibot** [comment]
From @avishefi on 2016-03-08T15:14:09Z

+1

**Comment by ansibot** [comment]
From @wimnat on 2016-03-08T15:14:09Z

@yarinkos can you please post your full task to replicate the problem?

**Comment by ansibot** [comment]
From @augusto on 2016-03-08T15:14:09Z

+1 
I get this on 2.0.1.0 even if I paste the raw, minified, escaped (valid) json inside the task.yml file. Here's an example

```
- name: "create bucket with attached policy"
  s3_bucket:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key:  "{{ aws_secret_access_key }}"
    name: "test-bucket"
    policy: "{\"Id\":\"Policy1479482055665\",\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"Stmt1479482052350\",\"Action\":[\"s3:PutObject\"],\"Effect\":\"Allow\",\"Resource\":\"arn:aws:s3:::logs/elb/AWSLogs/111732237172/*\",\"Principal\":{\"AWS\":[\"728223546328\"]}}]}"
    region: "{{ aws_region }}"
```

The error I get back is:
`"msg": "Policies must be valid JSON and the first byte must be '{'"`
