### ISSUE TITLE
Docs: precise example using hash items in loops

### ISSUE THREAD

**Issue by pestrella** [ansible/ansible#2929]
Hello,

just a suggestion: it might be helpful to have a precise example that illustrates how hashes work for the `with_items` property within the context of [loops](http://ansible.cc/docs/playbooks2.html#loops).

Something like this might help:

```

---
- hosts: all
  tasks:
    - name: echo test
      shell: echo "Hello ${item.name} ${item.surname}"
      with_items:
        - { name: "Luke", surname: "Skywalker" }
        - { name: "Han", surname: "Solo" }
```
