### ISSUE TITLE
ec2_vpc_route_table should infer "lookup: id" when "route_table_id" is provided or "lookup" should be mandatory

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29297]
From @dwoodrh on 2016-04-08T13:22:24Z
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_vpc_route_table module
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No modifications to default configuration
##### OS / ENVIRONMENT

Host OS is Arch Linux, I'm building infrastructure in AWS using boto version 2.39.0, and aws-cli version 1.10.17.
##### SUMMARY

When modifying a route table and specifying both tags and route table ID, the module defaults to identifying the route table by tags as specified in the documentation. However, it is a reasonable use-case to want to update tags, subnet associations, and routes in a single operation. If you do not provide "lookup: id" to the module, it ignores the presence of the route_table_id parameter and attempts to match route table based solely on the new tags, which fails and the result is that a new route table is created based on the parameters you have specified. Either "lookup" should be required, or route_table_id should imply "lookup: id"
##### STEPS TO REPRODUCE

Using the playbook pasted below, the module will create a new route table with those properties instead of updating the route table specified in route_table_id. Adding "lookup: id" gives expected behaviour. 

```
    - name: Configure Public Internet routing
      ec2_vpc_route_table:
        vpc_id: "{{ VpcId }}"
        region: "{{ Region }}"
        route_table_id: "{{ RouteTableId }}"
        tags:
          Name: PublicManagementRoute
        subnets:
          - "{{ subnet-id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ gateway_id }}"
      register: pub_int_route

```

##### EXPECTED RESULTS

I expected that the route table specified in route_table_id to be updated with the gateway, subnet association, and default route provided
##### ACTUAL RESULTS

A new route table was created

Copied from original issue: ansible/ansible-modules-extras#1989
