### ISSUE TITLE
Can't set volume options via gluster_volume module

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29296]
From @cu on 2016-04-05T02:29:42Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

gluster_volume
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

I am unable to set options on a volume gluster using the `gluster_volume`'s `options` parameter.
##### STEPS TO REPRODUCE

This example from the documentation...

```
- name: tune
  gluster_volume: state=present name=test1 options='{performance.cache-size: 256MB}'
```

...throws a YAML syntax error.

My modified version of this...

```
- name: authorize specific docker hosts to mount the volume
  gluster_volume:
    name: test1
    state: present
    options:
      auth.allow: "127.0.0.1"
```

...parses correctly but returns this error when the task is run:

```
fatal: [gfs-02.eng.example.net]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/example/.ansible/tmp/ansible-tmp-1459822578.91-3810522444797/gluster_volume\", line 2416, in <module>\r\n    main()\r\n  File \"/home/example/.ansible/tmp/ansible-tmp-1459822578.91-3810522444797/gluster_volume\", line 382, in main\r\n    probe_all_peers(cluster, peers, myhostname)\r\n  File \"/home/example/.ansible/tmp/ansible-tmp-1459822578.91-3810522444797/gluster_volume\", line 259, in probe_all_peers\r\n    for host in hosts:\r\nTypeError: 'NoneType' object is not iterable\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

Copied from original issue: ansible/ansible-modules-extras#1965

**Comment by ansibot** [comment]
From @kamihicouki on 2016-04-05T02:29:42Z

same problemmm...

**Comment by ansibot** [comment]
From @cherouvim on 2016-04-05T02:29:42Z

Have this problem as well. Wasted 20 minutes trying to get it right and ended up using shell:

```
- name: tune gluster volume
  shell: gluster volume set {{ fs_volume_name} network.ping-timeout 5 performance.cache-size 256MB
  run_once: true
  delegate_to: fs-1
```

**Comment by ansibot** [comment]
From @ghost on 2016-04-05T02:29:42Z

Same issue.

**Comment by ansibot** [comment]
From @rosmo on 2016-04-05T02:29:42Z

needs_contributor

**Comment by ansibot** [comment]
cc @devyanikota
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sac** [comment]
This is a issue in playbook. This is how it should be written:

```
 - name: authorize specific docker hosts to mount the volume
  gluster_volume:
    name: test1
    state: present
    options:
      { auth.allow: "127.0.0.1" }

```
Here is another example:

```
- name: Set volume options for SSL
  gluster_volume:
     state: present
     volume: test_volume
     options:
         { client.ssl: 'on',
           server.ssl: 'on',
           auth.ssl-allow: "{{ ssl_allow_list }}" }
  run_once: true

```
Note that options is a dictionary value (Not a list, not a list of dictionaries. A single dictionary.)
