### ISSUE TITLE
Azure Resource Deployment deletes all created resources before completing

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29317]
From @Blackbaud-IanThomas on 2016-05-25T15:01:23Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

azure_rm_deployment module
##### ANSIBLE VERSION

ansible 2.2.0 (devel 650bfdce8f) last updated 2016/05/24 17:23:00 (GMT -400)
  lib/ansible/modules/core: (detached HEAD aa995806b9) last updated 2016/05/24 17:23:14 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD d1a4f703ce) last updated 2016/05/24 17:23:14 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

When creating a template deployment (in particular Azure Container Service), after the deployment succeeds, the deployment then deletes all the resources that were created.
##### STEPS TO REPRODUCE
- Run the play below
- Wait for the deployment to complete (spins for 15-20 minutes)
- During the deployment process, see that all the resources get created
- When all resources are created, observe that the deployment then gets delete events for every resource that was created

Note: If you cancel the playbook execution before it waits for the completion of the deployment, the deployment will succeed in azure without going back and deleting all of the created resources.

```

---
  - name: Deploy Azure Container Service
    azure_rm_deployment:
      state: present
      location: eastus
      subscription_id: xxx-xxx-xxx
      resource_group_name: nautilus-ansible
      deployment_name: dcos
      deployment_mode: complete
      wait_for_deployment_completion: false
      template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-acs-dcos/azuredeploy.json'
      parameters:
        dnsNamePrefix:
          value: nautilus-ansible
        agentCount:
          value: 2
        agentVMSize:
          value: Standard_A1
        linuxAdminUsername:
          value: nautilus
        orchestratorType:
          value: DCOS
        masterCount:
          value: 1
        sshRSAPublicKey: 
          value: ssh-rsa  ...

```
##### EXPECTED RESULTS

I expected my Azure Container Service deployment to succeed and leave me with a usable cluster.
##### ACTUAL RESULTS

The Azure Container Service resources are all deleted as soon as the cluster is created.

Copied from original issue: ansible/ansible-modules-extras#2299
