### ISSUE TITLE
Bug in error handling Librato Annotation module

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29314]
From @casperbakker on 2016-05-19T10:25:48Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

monitoring/librato_annotation
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

Apparently my Librato credentials are incorrect. But the var 'e' at https://github.com/ansible/ansible-modules-extras/blob/2a0c5e2a8fd7ed3ce6d6eedd08e85e01e1617113/monitoring/librato_annotation.py#L136 seems to be not placed right. I have no knowledge about Python, but seems like a bug to me.

Result:

```
fatal: [IP]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1463652618.03-36649702854390/librato_annotation\", line 3003, in <module>\r\n    main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1463652618.03-36649702854390/librato_annotation\", line 157, in main\r\n    post_annotation(module)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1463652618.03-36649702854390/librato_annotation\", line 137, in post_annotation\r\n    module.fail_json(msg=\"Request Failed\", reason=e.reason)\r\nNameError: global name 'e' is not defined\r\n", "msg": "MODULE FAILURE", "parsed": false}
```
##### STEPS TO REPRODUCE

```
- name: Annotate Librato
  librato_annotation:
    user: "{{ secret_librato_username }}"
    api_key: "{{ secret_librato_api_key }}"
    title: New deploy
    name: app-deploys
    source: "{{ application_env }}"
  when: '"production" in group_names'
```
##### EXPECTED RESULTS

I expect a 'normal' error message with "Request Failed"
##### ACTUAL RESULTS

Got a stacktrace about "global name 'e' is not defined"

Copied from original issue: ansible/ansible-modules-extras#2256

**Comment by ansibot** [comment]
From @bcoca on 2016-05-19T10:25:48Z

cc @sedward

**Comment by ansibot** [comment]
From @stevenscg on 2016-05-19T10:25:48Z

I have used this module for several years and I too get the same error that @casperbakker reported with 2.0.2.0 and 2.1.0.0.

I have my CI using 2.0.1.0, which does not seem to exhibit this behavior.

**Comment by ansibot** [comment]
From @stevenscg on 2016-05-19T10:25:48Z

I wanted to add that this is still an issue with ansible 2.1.1.0 but also that I see the error with known good librato credentials vs the OP.

With 2.1.1.0, I get the same error response and corresponding playbook failure, but the annotation is actually created with Librato.

I can revert back to 2.0.1.0 with the same credentials and have no issues and correct operation.

**Comment by ansibot** [comment]
From @casperbakker on 2016-05-19T10:25:48Z

Yep, I also still have this same issue. I disabled the Librato annotations for now, but it is very annoying.

A fix would be welcome.

**Comment by ansibot** [comment]
From @stevenscg on 2016-05-19T10:25:48Z

@casperbakker @bcoca FYI, I still have this issue with Ansible 2.1.2.0.

**Comment by ansibot** [comment]
From @bendavies on 2016-05-19T10:25:48Z

ok, so here's our work around

```
- name: Register Release in Librato
  local_action:
    module: uri
    url: "https://metrics-api.librato.com/v1/annotations/YOUR-ANNOTATION"
    user: "{{ librato_email }}"
    password: "{{ librato_token }}"
    force_basic_auth: yes
    method: POST
    body:
      title: "your title"
      description: "your description"
      source: "{{ inventory_hostname }}"
    body_format: json
    status_code: 201
```
