### ISSUE TITLE
lvol module should not require size if origin is thin

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29326]
From @smemsh on 2016-06-25T21:41:22Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

lvol
##### ANSIBLE VERSION

verified that size requirement still exists in devel branch tip as of today
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When creating a thin snapshot, size is not necessary (this is, in fact, what `lvcreate` uses to differentiate a request to make thin snapshot from a new thick volume in same vg), yet the module requires it anyways for all state=present.  For (only) this reason, creating thin snapshots is not possible.
##### STEPS TO REPRODUCE

```
- name: create_thin_snapshot
  lvol:
    lv: '{{lvname_origin}}'
    vg: '{{vgname}}'
    snapshot: '{{lvname_snap}}'
    state: present

```
##### EXPECTED RESULTS

Should be created without issue.  This corresponds to a simple:

```
lvcreate -sn {{lvname_snap}} {{vgname}}/{{lvname_origin}}
```
##### ACTUAL RESULTS

```
TASK [create_thin_snapshot lv={{lvname_origin}}, state=present, snapshot={{lvname_snap}}, vg={{vgname}}] ***
fatal: [myhost]: FAILED! => {"changed": false, "failed": true, "msg": "No size given."}
```

Copied from original issue: ansible/ansible-modules-extras#2478
