### ISSUE TITLE
Jira module is not sending valid json when operation = edit

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29325]
From @marcinpraczko on 2016-06-21T20:03:48Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

jira (module)
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default configuration - no changes
##### OS / ENVIRONMENT

Tested on Mac OS - however seems be global (not related with local platform)
##### SUMMARY

According documentation jira module should allow create / modify items in Jira. Creating tickets is working fine, adding comments are working fine - however when operation == 'edit', module complain with error. 
##### STEPS TO REPRODUCE

This can be reproduce with `netcat` command and `jira` task. Running `ansible -vvvv` not helps in this case - not displaying outgoing json string which is sending to Jira URL.

Repeat steps:
On console 1 (this allows display json which is sending without sending this to real JIRA url)

```
# Run netcat and listen for connections
nc -l 8080
```

On another console run following playbook:

```
# Playbook:
- name: Updating ticket on Jira (testing)
  hosts: localhost
  gather_facts: no

  vars:
    - soft          : 'Ansible'
    - url           : 'http://127.0.0.1:8080' # Server: nc -l 8080
    - issue_test    : 'Test'

  vars_files:
    # Copy 'common_jira' to 'custom_jira' and adjust with valid credentials
    - [ "custom_jira.yml", "common_jira.yml" ]

  tasks:
     - name: Edit issue - use arguments with fields
       jira:
         username: "{{ jira_user.name }}"
         password: "{{ jira_user.pass }}"
         uri: "{{ url }}"
         operation: "edit"
         issue: "200"
       register: issue_edit
       ignore_errors: yes
       args:
         fields:
           - labels:
             - autocreated
             - ansible
             - yaml

# Create file with variables: custom_jira.yml

---
jira_user: 
  name:    'put_your_login_here'
  pass:    'put_your_pass_here'

# Create basic hosts.txt (Empty - local host will be added automatically)
# Run command

ansible-playbook -i hosts.txt playbook.yml
```
##### EXPECTED RESULTS

After debugging with Jira following Json should be created during sending

```
{"fields": {"labels": ["autocreated", "ansible"]}}
```

Module should connect with JIRA via REST API and edit issue based on above fields.
##### ACTUAL RESULTS

```
TASK [Edit issue - use arguments with fields] **********************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "HTTP Error 400: Bad Request"}

# JSON: Difference of inverted commas. 
{"fields": "{'labels': ['autocreated', 'ansible']}"}
```

Runnning ansible -vvvv not shows outgoing json - this is why netcat was used to see what 'server' is receiving.

Last info:
Result from Jira based on wrong json:

```
HTTP/1.1 400 Bad Request
```

Result from Jira based on valid json:

```
HTTP/1.1 204 No Content
# And Jira issue were updated with valid fields
```

Copied from original issue: ansible/ansible-modules-extras#2460
