### ISSUE TITLE
ec2_vpc_route_table working inconsistently with NAT Gateways

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29330]
From @kaikousa on 2016-06-28T13:41:02Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2_vpc_route_table
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

This, but hardly related to the module.

```
[defaults]
roles_path = ./roles
retry_files_enabled = False
ssh_port = 22
host_key_checking = False
```
##### OS / ENVIRONMENT

Running the scripts from OSX El Capitan 10.11.5
##### SUMMARY

Very briefly: sometimes a route to NAT is created, sometimes not.

Less brief: I have created NAT gateways for my private subnets and now I'm trying to create routes and route table to direct internet traffic towards the NAT instances. When I run the playbook and go check the results I find that the route to NAT Gateway sometimes appears in my route tables and sometimes not. Also if I try to set two route tables (in separate tasks or `with_items`) sometimes the other route table gets the route and the other doesn't and there is no logic how it happens.
##### STEPS TO REPRODUCE

Run this repeatedly and you will observe that it reports as changed everytime (I don't think it should) and that your route table sometimes has the route and sometimes not (check this from your AWS console).

```
- ec2_vpc_route_table:
    region: eu-west-1
    tags:
      Name: private-app-network-1
    state: present
    propagating_vgw_ids: []

    vpc_id: "{{ vpc.vpc_id }}"
    subnets:
      - "{{ private_subnets }}"
    routes:
      - dest: 0.0.0.0/0
         gateway_id: nat-123456
```

##### EXPECTED RESULTS

I expect to see the correct routes displayed in AWS Console after each playbook run. Also if I run the play multiple times, I don't expect the task to report as changed if I haven't changed anything.
##### ACTUAL RESULTS

Routes appear and disappear between runs even though nothing has changed in the playbook.

```

```
#### WORKAROUND

In the end I just used this module to setup an empty route table and then add the routes to NAT with AWS CLI ([create-route](http://docs.aws.amazon.com/cli/latest/reference/ec2/create-route.html)). It works but it's not a very nice solution.

Copied from original issue: ansible/ansible-modules-extras#2493
