### ISSUE TITLE
maven_artifact can't get artifact from local repo.

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29334]
From @chchrist on 2016-07-11T11:55:05Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

maven_artifact
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

maven_artifact can't get artifact from local repo as is looking for maven-metadata.xml and locally is maven-metadata-local.xml
##### STEPS TO REPRODUCE

Just try to point to your local maven repository.

```
- name: get artifact from local repo
  local_action: maven_artifact
  args:
    group_id: acme
    artifact_id: cms
    extension: zip
    classifier: foo
    version: "{{ artifact_version }}"
    repository_url: "~/.m2/repository"
    state: present
    dest: /tmp
  register: artifact
```

##### EXPECTED RESULTS

It should be able to find the maven-metadata-local.xml
##### ACTUAL RESULTS

```
"msg": "unknown url type: ~/.m2/repository/acme/foo/cms/1.10-SNAPSHOT/maven-metadata.xml"}
```

Copied from original issue: ansible/ansible-modules-extras#2547

**Comment by ansibot** [comment]
From @alikins on 2016-07-11T11:55:05Z

Is the behavior any different if repository_url is a file url? like:

```
- name: get artifact from local repo
  local_action: maven_artifact
  args:
    group_id: acme
    artifact_id: cms
    extension: zip
    classifier: foo
    version: "{{ artifact_version }}"
    repository_url: "file:///home/username/.m2/repository"
    state: present
    dest: /tmp
  register: artifact
```
