### ISSUE TITLE
AWS MFA Authentication does not work because Boto2 is broken

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29332]
From @joearasin on 2016-07-07T17:14:57Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
- All AWS
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### SUMMARY

Boto2 does not support Amazon's recommended approach to security configuration. Ergo, it should be either dropped by Ansible. Alternatively, Ansible can take on the responsibility of fixing Boto2 (because I'm not convinced Amazon will devote resources to it).
##### STEPS TO REPRODUCE

In `~/.aws/config`:

```
[default]
region = us-east-1
output = text

[profile admin]
region = us-east-1
role_arn = arn:aws:iam::123456788:role/AdminRole
source_profile = default
mfa_serial = arn:aws:iam::123456788:mfa/a.user.name
```

Then run anything that works in Ansible, setting profile to admin.
##### EXPECTED RESULTS

User is prompted for MFA key, authenticated with appropriate credentials.
##### ACTUAL RESULTS

Profile is not detected.

Copied from original issue: ansible/ansible-modules-extras#2532

**Comment by ansibot** [comment]
From @bcoca on 2016-07-07T17:14:57Z

You CAN use boto3 instead, Ansible just uses the latest version it finds installed when connecting.

We will support boto2 as many have that installed and are not able to upgrade, all new modules and functionality are mandated to use boto3, but we are not eliminating boto2 compatibility of existing code.

PS. we are NOT fixing boto2, I don't think that keeping compatibility means we become responsible for the upstream.

**Comment by ansibot** [comment]
From @joearasin on 2016-07-07T17:14:57Z

This decision means that I will advise my company to migrate away from Ansible, and not go through with our planned purchase of Ansible Tower.

Amazon specifies how to configure profiles. In my book, any deviation from that is a bug. Ansible deviates from that. That it didn't used to deviate doesn't matter to me -- the current state of affairs does. That you're considering this a wontfix means, to me, that Ansible does not care about ensuring AWS users have access to recommended security setups. That makes this product a dead end for the AWS-heavy environment in which we work.

As an alternative solution, there might be a way to use Boto3 to read profiles / generate credentials for Boto2 for users who have boto3 installed, without breaking boto2 compatibility.

**Comment by ansibot** [comment]
From @ryansb on 2016-07-07T17:14:57Z

Is there a specific module you've observed this with? I believe our connection code uses boto3 to connect to AWS when available.

**Comment by ansibot** [comment]
From @joearasin on 2016-07-07T17:14:57Z

I'm pretty sure it's all of them. as an example, using ec2, with a setup as above, and a task that looks like:

``` yaml
- name: Launch Box
  ec2:
    profile: admin
    image: ...
    ....
```

I get:
`boto.provider.ProfileNotFoundError: Profile "admin" not found!`

**Comment by ansibot** [comment]
From @ryansb on 2016-07-07T17:14:57Z

Thanks, I'll check into this and reopen if I can repro it.

**Comment by ansibot** [comment]
From @joearasin on 2016-07-07T17:14:57Z

Thanks :)

**Comment by ansibot** [comment]
From @ryansb on 2016-07-07T17:14:57Z

Yup, I've been able to reproduce this. No fix yet.

**Comment by ansibot** [comment]
From @ryansb on 2016-07-07T17:14:57Z

Alright, so here's the way we currently support using STS for assuming roles. You can either use blocks and set the environment variables AWS uses (in this example) or pass the secret key, access key ID, and session token to each module manually. For this example, assume you have a user `ansible-infra` that has permissions to assume a higher-level role with 2FA. 

```
---
- hosts: localhost
  vars_prompt:
  - name: two_factor_code
    prompt: What is your 2fa code?
    private: yes
  tasks:
  - sts_assume_role:
      mfa_token: "{{ two_factor_code }}"
      mfa_serial_number: arn:aws:iam::1234567890123:mfa/ansible-infra
      role_arn: arn:aws:iam::1234567890123:role/ansible-infra-admin
      role_session_name: ansible-playbook-infra
      region: us-west-2
      profile: ansible-infra
    register: assumed_role
  - block:
    - ec2_vpc_subnet_facts:
        region: us-west-2
    - [other AWS module things]
    environment:
      AWS_SECRET_ACCESS_KEY: "{{ assumed_role.sts_creds.secret_key }}"
      AWS_ACCESS_KEY_ID: "{{ assumed_role.sts_creds.access_key }}"
      AWS_SESSION_TOKEN: "{{ assumed_role.sts_creds.session_token }}"
```

There may be a cleaner way, but at the moment boto doesn't have a way to send a prompt up to the user from a playbook, and if it could that might end up forcing you to enter your MFA code multiple times. Can you try this on your setup and see how it works for you?
