### ISSUE TITLE
blockinfile delete last line in file if marker is set empty

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29340]
From @drabo on 2016-07-22T14:32:17Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

blockinfile
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = ~/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
# ~/.ansible.cfg
[defaults]
host_key_checking = False
timeout = 10
log_path = /var/log/ansible.log
command_warnings = False
[privilege_escalation]
become_method=sudo
become_user=root
[paramiko_connection]
record_host_keys=True
[ssh_connection]
control_path=/tmp
scp_if_ssh = True
[accelerate]
[selinux]
[colors]
```
##### OS / ENVIRONMENT

Manager: either Cygwin or Debian 8.5 running Ansible 2.1 updated
Remote: Redhat 6.8 with python 2.6.6
##### STEPS TO REPRODUCE

If the marker parameter is set empty ("") then the block of text written at EOF will overwrite the last line. The same result is with or without parameter insertafter: EOF

```
  - name: Update history params in /etc/profile
    blockinfile:
      dest: /etc/profile
      marker: ""
      content: |
        export HISTFILESIZE=10000
        export HISTTIMEFORMAT='%F %T '
```

##### EXPECTED RESULTS

A LineFeed should be inserted at EOF and then the block of text should be appended.
##### ACTUAL RESULTS

The block of text is written over the last line in file.

```

```

Copied from original issue: ansible/ansible-modules-extras#2616
