### ISSUE TITLE
known_hosts doesn't support entries with ssh port specified

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29343]
From @rija on 2016-08-02T09:27:00Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

known_hosts
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT
- OS where I run ansible from: Mac OS X 10.11.6 El Capitan
- OS being configured: Ubuntu 16.04 LTS 64-bits on a Digital Ocean Droplet
##### SUMMARY

When the known_hosts file has entries is in the format below,
known_hosts module is unable to remove these entries and it doesn't know how
to write that in that format either.

**[ public-ip]:port ecdsa-sha2-nistp256 key**

It is a problem because I don't want to use default port and I use ssh-keyscan
to discover the host's public key and I need the playbook to be idempotent.

ssh-keyscan can take a -p to specify the port but when doing so,
it creates entries in the format mentioned above.

To keep known_hosts (and my playbook) idempotent, I need to use -p
whether the Sshd is using default port or custom port (first run or subsquent runs respctively)

When I use ssh-keyscan with -p and known_hosts,
it works the first time (changing port from default 22 to custom port)
because ssh-keyscan use the classic form: **public-ip type key**
when it detects that it's called with -p 22.
##### STEPS TO REPRODUCE

Starting point: SSHd port has successfully been changed from port 22
to custom port (and the steps below worked that first time).
Then I run the steps again.

```
- name: first remove the host from our known hosts list as we might have re-spun the hosts
  local_action: known_hosts name={{ansible_host}} state=absent
  tags:
    - sshd.known_hosts.key.remove

- name: retrieve public host key for the host
  local_action: command ssh-keyscan -p {{ansible_port}} -t ecdsa -H {{ansible_host}}
  register: new_host_key
  tags:
    - sshd.known_hosts.key.retrieve

- name: add the new host key for the host to our known hosts list
  local_action: known_hosts name={{ansible_host}} key={{new_host_key.stdout}} state=present
  tags:
    - sshd.known_hosts.key.add

```

(note: the problem is the same whether the public ip is hashed with -H or not)
##### EXPECTED RESULTS

known_hosts entry after first step:

|1|Wo/iD2OG3FQxTJRT0qggIQTx8C0=|fr6pjJDB19AczvlACt6M5HQk1CU= ecdsa-sha2-nistp256 ...
is removed from my known_hosts file

then following entry is appended at the end of the file after the third step:

[|1|YNgaK1Kk3z/J79OgnEcapwmHpXE=|/IWqIMeFwmIKmta/PAH846rpcQ0=]:6547 ecdsa-sha2-nistp256 ...
##### ACTUAL RESULTS

the entry:

|1|Wo/iD2OG3FQxTJRT0qggIQTx8C0=|fr6pjJDB19AczvlACt6M5HQk1CU= ecdsa-sha2-nistp256 ...
is removed from my known_hosts file

but the new entry with port specified is not added to the known_hosts file:

```
fatal: [mydroplet -> localhost]:
FAILED! => {"changed": false,
"cmd": "/usr/bin/ssh-keygen -F public-ip-here -f /var/folders/t9/5tvwz9yn69xfgtqdzq9lbgvr0000gn/T/tmpLOzsBv",
"failed": true,
"invocation": {"module_args": {"key": "[|1|hEXzfBLAh2UefDLbleLkow7HfjI=|wHcBCyoUF8aTkkNIqTqnh5Y6GNw=]:6547 ecdsa-sha2-nistp256 ...",
                "name": "public-ip-here",
                "path": "path/to/my/known_hosts",
                "state": "present"}, "module_name": "known_hosts"},
"msg": "", "rc": 1, "stderr": "", "stdout": "", "stdout_lines": []}
```

I then manually added the entry with the port specified in the known_hosts file,
and after running the steps again, the entry is not removed after the first step:

```
ok:
[mydroplet -> localhost] => {"changed": false, "gid": 20, "group": "staff",
                              "invocation": {"module_args": {"key": null, "name": "public-ip-here",
                              "path": "path/to/my/known_hosts", "state": "absent"},
                              "module_name": "known_hosts"},
"key": null, "mode": "0600", "name": "public-ip-here",
"owner": "xxxx", "path": "path/to/my/known_hosts",
"size": 32259, "state": "file", "uid": 501}
```

Copied from original issue: ansible/ansible-modules-extras#2651
