### ISSUE TITLE
deploy_helper crashes when unfinished_filename is a directory rather than a file

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29347]
From @mgedmin on 2016-08-10T13:29:45Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

deploy_helper
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/mg/src/new-project/deployment/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Linux (Ubuntu 16.04 LTS on the controller, Debian 8 on target)
##### SUMMARY

When you create a directory named "{{ deploy_helper.unfinished_filename }}", deploy helper gets terribly confused when it tries to remove it:
##### STEPS TO REPRODUCE

```
- hosts: all
  tasks:
    - name: initialize deployment
      deploy_helper: path=/opt/app/

    - name: mkdir /opt/app/*
      file: dest={{ deploy_helper.new_release_path }}/{{ item }} state=directory
      with_items:
        - "{{ deploy_helper.unfinished_filename }}"
        - frontend
        - backend

    # ... further build steps irrelevant for this bug ...

    - name: finalize the deployment
      deploy_helper:
        path: "{{ deploy_helper.project_path }}"
        release: "{{ deploy_helper.new_release }}"
        state: finalize
```
##### EXPECTED RESULTS

no crash
##### ACTUAL RESULTS

crash:

```
fatal: [webserver]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_xGKPNM/ansible_module_deploy_helper.py\", line 475, in <module>\r\n    main()\r\n  File \"/tmp/ansible_xGKPNM/ansible_module_deploy_helper.py\", line 446, in main\r\n    changes += deploy_helper.remove_unfinished_file(facts['new_release_path'])\r\n  File \"/tmp/ansible_xGKPNM/ansible_module_deploy_helper.py\", line 341, in remove_unfinished_file\r\n    os.remove(unfinished_file_path)\r\nOSError: [Errno 21] Aplankas: '/opt/app/releases/20160810131940/DEPLOY_UNFINISHED'\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

Copied from original issue: ansible/ansible-modules-extras#2703
