### ISSUE TITLE
Archive with remote_src=yes strips the second / in http://

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29353]
From @zaphinath on 2016-08-22T19:02:53Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

archive
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = 
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Using default
##### OS / ENVIRONMENT

Running ansible on OSX El Capitain and remote host is centos 7
##### SUMMARY

I am trying to download a remote tar and extract it. It appears that I am losing a / in the src
##### STEPS TO REPRODUCE

I am running the following command as one of my roles called zookeeper.

```
- name: extract the file
  unarchive:
    src: http://apache.cs.utah.edu/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz
    dest: /var/zookeeper
    remote_src: yes
```

Then I get the following error:

```
fatal: [10.84.236.95]: FAILED! => {"failed": true, "msg": "file or module does not exist: /Users/dcarr/Projects/bigtreeawsscripts/aws-scripts/src/main/ansible/http:/apache.cs.utah.edu/zookeeper/zookeeper-3.4.8/zookeeper-3.4.8.tar.gz"}
```
##### EXPECTED RESULTS

I would expect with :// in the original and remote_src turned on that I would be able to download it remotely.
##### ACTUAL RESULTS

It looks like http:// is turned into http:/ and it never tries to download remotely. Instead it looks for the file on my local machine.

Copied from original issue: ansible/ansible-modules-extras#2766
