### ISSUE TITLE
lxc_container: incompatible with unprivileged containers

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29356]
From @ludwig-gramberg on 2016-08-28T15:01:53Z
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME
- lxc_container
##### ANSIBLE VERSION

```
ansible 2.0.1.0
```
##### CONFIGURATION
- no changes
##### OS / ENVIRONMENT
- os/x 10.11.6
##### SUMMARY

currently the module only supports managing lxc-containers as root in the global context. it would be great if it would also work in the context of any user.
see for https://myles.sh/configuring-lxc-unprivileged-containers-in-debian-jessie/ reference.
##### STEPS TO REPRODUCE
- prep your system as described here https://myles.sh/configuring-lxc-unprivileged-containers-in-debian-jessie/
- try to start a container as an unprivileged user
##### EXPECTED RESULTS
- container can be managed
- container exists in users home-folder as the default layout suggests
##### ACTUAL RESULTS
- command times out

Copied from original issue: ansible/ansible-modules-extras#2802

**Comment by ansibot** [comment]
From @ansibot on 2016-08-28T15:01:53Z



@cloudnull ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @cloudnull on 2016-08-28T15:01:53Z

I think the issue is caused by the C lib and may require some refactoring to make it go. I will look into this.

**Comment by ansibot** [comment]
From @ludwig-gramberg on 2016-08-28T15:01:53Z

basically what i want to do is this:

```
---

- name: create barebone container
  command: lxc-create --name {{ container_hostname }} --template download -- --release jessie --arch amd64 --dist debian
  args:
    chdir: ~/
    creates: "~/.local/share/lxc/{{ container_hostname }}/config"
  become: true
  become_user: "{{ container_user }}"
```
