### ISSUE TITLE
zabbix_host.py does not update linked templates or groups correctly

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29357]
From @stephen-e-smith on 2016-09-02T11:08:18Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

zabbix_host.py
##### ANSIBLE VERSION

```
ansible 1.9.2
  configured module search path = None
```
##### OS / ENVIRONMENT

CentOS Linux release 7.1.1503 (Core) 
##### SUMMARY

zabbix_host.py seems to remove previous group membership / template linkage
##### STEPS TO REPRODUCE

Steps to reproduce:
With the following inventory:
[groupa]
node-1
[groupb]
node-1
node-2
node-3

And the following playbooks:

```

---
- name: Add nodes to Zabbix
  hosts: groupa
  tags:
    - grpa
  tasks:
    - local_action:
        module: zabbix_host
        server_url: "http://192.168.0.10/zabbix/api_jsonrpc.php"
        login_user: admin
        login_password: zabbix
        host_name: "{{ inventory_hostname }}"
        host_groups:
          - Group A
        link_templates:
          - Custom Template 1
          - Custom Template 2
          - Template OS Linux
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 0
            ip: ""
            dns: "{{ inventory_hostname }}"
            port: 10050

- name: Update group and template association
  hosts: groupb
  tags:
    - grpb
  tasks:
    - local_action:
        module: zabbix_host
        server_url: "http://192.168.0.10/zabbix/api_jsonrpc.php"
        login_user: admin
        login_password: zabbix
        host_name: "{{ inventory_hostname }}"
        host_groups:
          - Group B
        link_templates:
          - Custom Template 3
          - Custom Template 4
          - Template OS Linux
        status: enabled
        state: present
        inventory_mode: automatic
        interfaces:
          - type: 1
            main: 1
            useip: 0
            ip: ""
            dns: "{{ inventory_hostname }}"
            port: 10050

```
##### EXPECTED RESULTS

node-1 is a member of Zabbix "Group A" and "Group B" with custom templates 1-4, and "Template OS Linux" linked to it.
##### ACTUAL RESULTS

node-1 is a member of Zabbix "Group B" only and only has custom templates 3-4 and "Template OS Linux" linked to it.

There's no useful output from -vvvv as the API calls are not logged in -vvvv AFAICT.

Copied from original issue: ansible/ansible-modules-extras#2835
