### ISSUE TITLE
asa_command module does not support with_nested

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29354]
From @atul-ram on 2016-08-25T13:03:00Z

##### ISSUE TYPE

asa_command module does not support with_nested
##### COMPONENT NAME

as_command
##### ANSIBLE VERSION

2.2

```

```
##### CONFIGURATION

vars:

  Obj_port_range:
    - [2007,4007]
    - [5007,6087]
##### OS / ENVIRONMENT

centos , cisco asa
##### STEPS TO REPRODUCE
```yaml
- name: Add port range to object
  asa_command:
    provider: "{{ cli }}"
    commands:
      - config t
      - "object-group service {{ Obj_port_grp }} {{ protocol }}"
      - description "prepared by automation module"
      - "port-object range {{ Obj_port_range.0 }} {{ Obj_port_range.1 }}"
    with_nested: "{{ Obj_port_range }}"
```
##### EXPECTED RESULTS

port-object range 2007 3007
##### ACTUAL RESULTS

 FAILED! => {"changed": false, "failed": true, "msg": "unsupported parameter for module: with_nested"}

```

```

Copied from original issue: ansible/ansible-modules-extras#2792
