### ISSUE TITLE
Pear module not verbose enough while failing

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29368]
From @JulienPalard on 2016-09-28T09:36:55Z
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

pecl
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/[...]/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
$ cat ansible.cfg  | grep -v '^$\|^#'
[defaults]
forks           = 100
vault_password_file = ~/.vault.password
[ssh_connection]
pipelining = False
```
##### OS / ENVIRONMENT

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie
```
##### SUMMARY

I asked for the pecl module to install something but my alternatives pointed /usr/bin/php to php7 which make the module fail without reporting why.
##### STEPS TO REPRODUCE

```
  - name: apt-get install from stretch (testing)
    apt: name={{item}} state=latest default_release=stretch
    with_items:
    - php7.0
    - php-pear

  - name: Use php7 as /usr/bin/php
    alternatives: name=php path=/usr/bin/php7.0

  - name: Install stomp PHP module
    pear: name="pecl/stomp" state=present
```

I'm getting (I tried `-vvv`):

```
failed: [dev] (item=pecl/stomp) => {"failed": true, "invocation": {"module_args": {"name": "pecl/stomp", "state": "present"}, "module_name": "pear"}, "item": "pecl/stomp", "msg": "failed to install pecl/stomp"}
```

Which is not enough to tell why it failed, which looks wrong to hide this.

To diagnose I started with `pecl --help` and boom:

```
$ pecl --help

Parse error: syntax error, unexpected 'new' (T_NEW) in /usr/share/php/PEAR/Frontend.php on line 91
```

This is clearly my issue here, so I updated my alternatives to use php5 and I'm good, that's not really an issue.

BUT I'd liked a lot if ansible told me straight that the PECL module gave a `Parse error: syntax error, unexpected 'new' (T_NEW) in /usr/share/php/PEAR/Frontend.php on line 91`.

Copied from original issue: ansible/ansible-modules-extras#3053
