### ISSUE TITLE
Slack: Broken links with anchor text

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29384]
From @plunchete on 2016-10-13T18:31:29Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Slack module
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

[This PR](https://github.com/ansible/ansible-modules-extras/pull/3032#issuecomment-253554299) sending URLs with defined anchors to Slack broke.

The format for specifying a URL with an anchor on Slack, according to their[ message formatting doc](https://api.slack.com/docs/message-formatting#linking_to_urls), is the following:

```
<https://google.com|anchor text>
```

During my investigation of this issue I've found their [online message builder](https://api.slack.com/docs/messages/builder?msg=%7B%22text%22%3A%22%60%3Chttps%3A%2F%2Fgoogle.com%7Canchor%20text%3E%60%20Foo%20bar%20baz%22%7D) really useful
##### STEPS TO REPRODUCE

``` yaml
- name: Sending slack notification {{ message }}
  local_action:
    module: slack
    channel: "{{ slack_channel }}"
    icon_url: "{{ slack_image }}"
    msg: "`<https://google.com|anchor text>` Foo bar baz"
    username: "{{ slack_name }}"
    token: "{{ slack_token }}"
```

Note: Using color good/warning/danger or normal produce the exact same output, that means that this bug affects to basic formatting and attachments

##### EXPECTED RESULTS

<img width="176" alt="screen shot 2016-10-13 at 11 18 29 am" src="https://cloud.githubusercontent.com/assets/50509/19361501/bad5faf0-9137-11e6-9a55-e3d3c25be836.png">
##### ACTUAL RESULTS

<img width="331" alt="screen shot 2016-10-13 at 11 17 38 am" src="https://cloud.githubusercontent.com/assets/50509/19361480/ad1dbec0-9137-11e6-9883-9f3c442c21a9.png">

Copied from original issue: ansible/ansible-modules-extras#3164
