### ISSUE TITLE
Document for aws_direct_connect_connection is missing some return values

### ISSUE THREAD

**Issue by zhujian0805** [ansible/ansible#29381]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
lib/ansible/modules/cloud/amazon/aws_direct_connect_connection.py

##### ANSIBLE VERSION
devel

##### SUMMARY
ansible-doc aws_direct_connect_connection, shows this
```
  returned: I(state=present)
  contains:
    aws_device:
      description: The endpoint which the physical connection terminates on.
    bandwidth:
      description: The bandwidth of the connection.
    connection_id:
      description: ID of the Direct Connect connection.
    connection_state:
      description: The state of the connection.
    location:
      description: Where the connection is located.
    owner_account:
      description: The owner of the connection.
    region:
      description: The region in which the connection exists.
```

The actual return is the following, we can add those missing return values to the documents, for example, i needed to use connection_name, but the doc doesn't mention it.
```
                        "connection": {
                            "aws_device": "XXXX33h34ndol88t", 
                            "bandwidth": "10Gbps", 
                            "connection_id": "dxcon-XXX", 
                            "connection_name": "XXXX-dx02", 
                            "connection_state": "available", 
                            "loa_issue_time": "2017-08-06T18:06:28+08:00", 
                            "location": "XXX", 
                            "owner_account": "XXXXXXXXXX", 
                            "region": "cn-north-1"
                        }, 
```
