### ISSUE TITLE
Smart quotes in consul_session desc. block cause Ansible to error.

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29380]
From @chiefy on 2016-10-13T13:44:37Z

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

consul_session
##### ANSIBLE VERSION

```
ansible 2.2.0
```
##### CONFIGURATION

n/a
##### OS / ENVIRONMENT

centos 7
##### SUMMARY

[Smart-quotes in module code description block](https://github.com/ansible/ansible-modules-extras/blob/devel/clustering/consul_session.py#L106) causes ansible to barf.
##### STEPS TO REPRODUCE

```
- name: Try to get or create session lock in consul
  consul_session:
    name: ucp_primary_lock
    datacenter: development
    state: present
    validate_certs: False
    register: ucp_consul_session_id
```
##### EXPECTED RESULTS

No errors relating to non-ASCII issue
##### ACTUAL RESULTS

```
{"changed": false, "failed": true, "module_stderr": "  File \"/tmp/ansible_jP41R1/ansible_module_consul_session.py\", line 106\nSyntaxError: Non-ASCII character '\\xe2' in file /tmp/ansible_jP41R1/ansible_module_consul_session.py on line 107, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

Copied from original issue: ansible/ansible-modules-extras#3157
