### ISSUE TITLE
npm always installing even if package is installed already

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29389]
From @shaharmor on 2016-10-26T08:33:04Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

npm
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

When using the npm module to install a package globally, it doesn't check if the module is installed before installing, making it always "change" the module.
##### STEPS TO REPRODUCE

Run the follwing task multiple timesL

```
- name: update npm
  npm:
   name: npm
   global: yes
   state: present
   version: '3.10.8'
   production: yes
```
##### EXPECTED RESULTS

First run: changed
Second run: ok
##### ACTUAL RESULTS

First run: changed
Second run: changed

Copied from original issue: ansible/ansible-modules-extras#3290

**Comment by ansibot** [comment]
From @ansibot on 2016-10-26T08:33:04Z



@shane-walker ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @shaharmor on 2016-10-26T08:33:04Z

I think its due to `production: yes` causing npm to return an error

**Comment by ansibot** [comment]
From @lupupitkanen on 2016-10-26T08:33:04Z

I have tried `production: yes/no`, `state: present/latest` and all combinations. The task status is always `changed` when `global: yes`. Ansible login to host as root without sudo.
- ansible-2.2.0.0-3.el7.noarch
- node: v6.9.1
- npm: 3.10.9
- hosts: CentOS Linux release 7.2.1511 (Core)

**Comment by ansibot** [comment]
cc @chrishoffman
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @xcambar
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by xcambar** [comment]
I've just tried locally with `ansible 2.4.2.0` with the following  configuration:

#### Vagrantfile

```
Vagrant.require_version ">= 1.7.0"
Vagrant.configure(2) do |config|
  config.vm.box = "generic/centos7"
  config.vm.hostname = 'bug.local'
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
  end
end
```

#### playbook.yml

```
---

- hosts: all
  become: true
  roles:
    - geerlingguy.nodejs # This performs the initial node/npm install
  tasks:
    - name: update npm
      npm:
        name: npm
        global: yes
        state: present
        version: '3.10.8'
        production: yes
```

#### requirements.yml

```
- src: geerlingguy.nodejs
  version: 4.1.1
```

Run it with: `$ ansible-galaxy install -r ./requirements.yml && vagrant up`

First run will show `changed: true` on the `npm` task.
Next runs will show `changed: false` on the `npm` task.

As expected.

Can anyone confirm? @shaharmor? @lupupitkanen?
