### ISSUE TITLE
ec2_eni can't gracefully create and/or attach to instance

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29385]
From @mechaxl on 2016-10-21T18:18:38Z
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

ec2_eni
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Projects/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I would like to use Ansible to create an ENI with a predetermined private IP address in AWS if it doesn't already exist, attach it to an particular instance if it's not already attached, and raise an error if the ENI exists but is already attached to a different instance. The current `ec2_eni` module makes this difficult.
##### STEPS TO REPRODUCE

This is what I've currently got to emulate this behavior. It won't error out if the interface is already attached to a different instance, but it will at least handle creating/attaching an available one gracefully.

```
- name: Find existing network interface
  ec2_eni_facts:
    filters:
      private_ip_address: "{{ eni_ip }}"
  register: ec2_eni

- name: Check if existing network interface is already attached.
  ec2_eni_facts:
    filters:
      private_ip_address: "{{ eni_ip }}"
      status: available
  register: ec2_eni_available

- name: Attach existing network interface
  ec2_eni:
    eni_id: "{{ ec2_eni.interfaces[0].id }}"
    instance_id: "{{ instance_id }}"
    private_ip_address: "{{ eni_ip }}"
    subnet_id: subnet-11112222
    state: present
    device_index: 1
  when: ec2_eni.interfaces|length and ec2_eni_available.interfaces|length

- name: Create network interface and attach
  ec2_eni:
    instance_id: "{{ instance_id }}"
    private_ip_address: "{{ eni_ip }}"
    subnet_id: subnet-11112222
    state: present
    device_index: 1
  when: not ec2_eni.interfaces|length
```

It would be really nice to be able to cut that down to just this:

```
- name: Create and/or attach network interface
  ec2_eni:
    instance_id: "{{ instance_id }}"
    private_ip_address: "{{ eni_ip }}"
    subnet_id: subnet-11112222
    state: present
    device_index: 1
```
##### EXPECTED RESULTS

N/A
##### ACTUAL RESULTS

N/A

Copied from original issue: ansible/ansible-modules-extras#3265
