### ISSUE TITLE
Proxmox: set up multiple netif

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29391]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
proxmox

##### ANSIBLE VERSION
`2.3`

##### SUMMARY
From @tchouvince on 2016-10-26T16:29:38Z
Hello,
ISSUE TYPE

```
- needs_info
```

I try to set up multiple netif but I have no success.
I use proxmox4.1-22 and ansible2.1.2.
Create  VMS with once netif run:
```
- name: Create proxmox instances
  proxmox: vmid={{ item.vmid }} node='{{ item.node }}' api_user='{{ item.api_user }}' api_password='{{ item.api_password }}' api_host='{{ item.api_host }}' password='{{ item.password }}' hostname='{{ item.hostname }}' ostemplate='{{ item.tmpl_storage }}:vztmpl/{{ item.tmpl }}' storage={{ item.storage }} swap=2048 cpus={{ item.cpus }} memory={{ item.memory }} disk={{ item.disk_size }} netif='{"net0":"name=eth0,ip={{ item.cidr }},gw={{ item.gateway }},bridge=vmbr2"}' onboot=true searchdomain={{ item.searchdomain }}
  
  with_items:
  - "{{ proxmox_dict }}"
```

For 2 interfaces, i try that but not working:

```
netif='[{"net0":"name=eth0,ip={{ item.cidr }},gw={{ item.gateway }},bridge=vmbr2"},{"net1":"name=eth0,ip={{ item.cidr1 }},gw={{ item.gateway1 }},bridge=vmbr2"}]' 
```
For test, I have also try to add a simple line like:
```
- name: add secondary interfaces
  proxmox: vmid={{ item.vmid }} api_user='{{ item.api_user }}' api_password='{{ item.api_password }}' api_host='{{ item.api_host }}' netif='{"net1":"name=eth1,ip={{ item.cidr1 }},gw={{ item.gateway1 }},bridge=vmbr1"}' 
  
    with_items:
  - "{{ proxmox_dict }}"
```

I have setup variables in host_vars
I have no error, but no change:
```
PLAY RECAP *********************************************************************
preprod-proxmox1           : ok=2    changed=0    unreachable=0    failed=0   
```

Have you an idea ?

Thanks for advance

Best regards

Copied from original issue: ansible/ansible-modules-extras#3296
