### ISSUE TITLE
Using reject_with with a previously defined jump: REJECT results in two Jump statements

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29393]
From @madonius on 2016-10-28T18:57:03Z

##### ISSUE TYPE
- Bug Report
  ##### COMPONENT NAME
  iptables
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### CONFIGURATION

Vanilla
##### OS / ENVIRONMENT

Debian Testing
##### SUMMARY

When using the iptables module with _reject_with_ and _jump: REJECT_ it results in

```
failed: [127.0.0.1] (item=ipv4) => {"cmd": "/sbin/iptables -t filter -A INPUT -p tcp -j REJECT -j REJECT --reject-with tcp-reset", "failed": true, "item": "ipv4", "msg": "iptables v1.6.0: multiple -j flags not allowed\nTry `iptables -h' or 'iptables --help' for more information.", "rc": 2, "stderr": "iptables v1.6.0: multiple -j flags not allowed\nTry `iptables -h' or 'iptables --help' for more information.\n", "stdout": "", "stdout_lines": []}
```
##### STEPS TO REPRODUCE

``` yaml
- name: Reject tcp with tcp-reset
  iptables:
    chain: INPUT
    protocol: tcp
    jump: REJECT
    reject_with: tcp-reset
    ip_version: ipv4
```

##### EXPECTED RESULTS

I expect it to be usable as an iptables statement would be
##### ACTUAL RESULTS

Results in failure

Copied from original issue: ansible/ansible-modules-extras#3315
