### ISSUE TITLE
maven_artifact fails if repository_url not specified

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29406]
From @wshallum on 2016-11-11T05:33:23Z
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
no

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`repository_url` is supposed to default to `http://repo1.maven.org/maven2` if not specified, however the change to support S3 URLs parsed the URL parameter (which defaults to `None`) before it can be changed to the default value.

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  connection: local
  tasks:
    - maven_artifact: group_id=log4j artifact_id=log4j version=1.2.17 dest=/tmp/log4j-1.2.17.jar
```

##### EXPECTED RESULTS

File is downloaded .

##### ACTUAL RESULTS

Error occurs:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "url parsing went wrong 'NoneType' object has no attribute 'find'"}
```

Copied from original issue: ansible/ansible-modules-extras#3429
