### ISSUE TITLE
IPA: modules report failed state when no changes are made

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29417]
From @gelato on 2016-11-21T08:14:57Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ipa
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Linux Mint 18
##### SUMMARY

Instead of doing nothing ansible modules report failed state when no changes are made.
##### STEPS TO REPRODUCE

Run ipa modules imputing cyrilic data multiple times

```
- name: Create needed groups
    ipa_group:
      state: present
      name: "{{ item }}"
      description: "{{ users_to_add | selectattr('group','equalto',item) | map(attribute='group_desc') | list | first }}"
      ipa_host: "{{ global_host }}"
      ipa_user: "{{ global_user }}"
      ipa_pass: "{{ global_pass }}"
      validate_certs: no
      user: "{{ users_to_add | selectattr('group','equalto',item) | map(attribute='login') | list }}"
    with_items: "{{ users_to_add | map(attribute='group') | list | unique }}"
    ignore_errors: true


users_to_add:
    - username: Harley Quinn
      login: 90987264
      cluster_zone: Default
      group: mininform
      group_desc: "Some random data for description"
      personal_data:
        - first_name: Harley
          last_name: Quinn
          mail: harley@gmail.com
          telnum: +79788880132
          jobtitle: Министр
    - username: Vasya Pupkin
      login: 77777777
      cluster_zone: Default
      group: mininform
      group_desc: "Some random data for description"
      personal_data:
        - first_name: Vasya
          last_name: Pupkin
          mail: vasya@gmail.com
          telnum: +7970000805
          jobtitle: Зам. Министра
    - username: Vladimir Putin
      login: 33333333
      cluster_zone: Default
      group: el_presidente
      group_desc: "Русский президент"
      personal_data:
        - first_name: Владимир
          last_name: Путин
          mail: putin@gmail.com
          telnum: +7970000000
          jobtitle: Эль президенте
```

##### EXPECTED RESULTS

Ansible won't report failed state
##### ACTUAL RESULTS

```
ignoring
failed: [ipa.kr3tec2h.loc] (item=({u'username': u'Medvedev', u'login': 88899823, u'cluster_zone': u'Default', u'group': u'el_presidente', u'group_d
esc': u'\u0410\u0432\u0430\u0442\u0430\u0440 \u043f\u0440\u0435\u0437\u0438\u0434\u0435\u043d\u0442\u0430'}, {u'mail': u'aang@gmail.com', u'first
_name': u'\u0410\u0432\u0430\u0442\u0430\u0440', u'last_name': u'\u0410\u0430\u043d\u0433', u'jobtitle': u'\u0410\u0432\u0430\u0442\u0430\u0440',
 u'telnum': 7970000002})) => {"failed": true, "item": [{"cluster_zone": "Default", "group": "el_presidente", "group_desc": "Аватар президента", "
login": 88899823, "username": "Medvedev"}, {"first_name": "Аватар", "jobtitle": "Аватар", "last_name": "Аанг", "mail": "aang@gmail.com", "telnum"
: 7970000002}], "msg": "repsonse user_mod: no modifications to be performed"}
```

Copied from original issue: ansible/ansible-modules-extras#3501
