### ISSUE TITLE
npm "mongodb" package error

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29414]
From @eoli3n on 2016-11-15T08:41:06Z
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
npm

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Installing "mongodb" package with npm module failed with module error

```
ValueError: need more than 1 value to unpack
```

##### STEPS TO REPRODUCE

```
ansible localhost -m npm -a "name=mongodb global=yes executable=/usr/bin/npm state=latest"
```

##### ACTUAL RESULTS
```
Loading callback plugin minimal of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/extras/packaging/language/npm.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1479199216.92-116938239050990 `" && echo ansible-tmp-1479199216.92-116938239050990="` echo $HOME/.ansible/tmp/ansible-tmp-1479199216.92-116938239050990 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpcvkNFw TO /root/.ansible/tmp/ansible-tmp-1479199216.92-116938239050990/npm.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1479199216.92-116938239050990/ /root/.ansible/tmp/ansible-tmp-1479199216.92-116938239050990/npm.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1479199216.92-116938239050990/npm.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1479199216.92-116938239050990/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_BPzD5_/ansible_module_npm.py", line 271, in <module>
    main()
  File "/tmp/ansible_BPzD5_/ansible_module_npm.py", line 254, in main
    outdated = npm.list_outdated()
  File "/tmp/ansible_BPzD5_/ansible_module_npm.py", line 205, in list_outdated
    pkg, other = re.split('\s|@', dep, 1)
ValueError: need more than 1 value to unpack

localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_name": "npm"
    }, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_BPzD5_/ansible_module_npm.py\", line 271, in <module>\n    main()\n  File \"/tmp/ansible_BPzD5_/ansible_module_npm.py\", line 254, in main\n    outdated = npm.list_outdated()\n  File \"/tmp/ansible_BPzD5_/ansible_module_npm.py\", line 205, in list_outdated\n    pkg, other = re.split('\\s|@', dep, 1)\nValueError: need more than 1 value to unpack\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```

Copied from original issue: ansible/ansible-modules-extras#3470

**Comment by ansibot** [comment]
From @ansibot on 2016-11-15T08:41:06Z



@shane-walker ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @eoli3n on 2016-11-15T08:41:06Z

This module is boring... i have soooooooo many errors. Here's a temporary workaround

```
- name: install npm packages
  #npm: name={{item}} global=yes executable=/usr/bin/npm state=latest
  shell: creates={{item.creates}} /usr/bin/npm install -g {{item.pkg}}
  with_items:
       - { creates: '/usr/local/lib/node_modules/express', pkg: 'express' }
       - { creates: '/usr/local/lib/node_modules/mongodb', pkg: 'mongodb' }
       - { creates: '/usr/local/lib/node_modules/fs', pkg: 'fs' }
       - { creates: '/usr/local/lib/node_modules/cordova', pkg: 'cordova' }
       #- express
       #- mongodb
       #- fs
       #- cordova

- name: update npm packages
  shell: npm update -g
```
