### ISSUE TITLE
blockinfile marker is null while replace the last line

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29424]
From @richardweiu on 2016-11-27T08:03:43Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- blockinfile

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

the default setting

##### OS / ENVIRONMENT

ubuntu 14.04 3.16.0-37-generic 
##### SUMMARY

- I don't want inser any marker info,but when I set 

+ `no` , it will inser `False` befor and after the content
+ `null`,it will inser `None` befor and after the content
+ `""`, it will inser space line befor and after the content

- when set it to "",it will replace the last line

##### STEPS TO REPRODUCE

```
        - name: update nrpe config in /etc/nagios
          blockinfile:
                backup: yes
                marker: ""
                dest: /path/to/nrpe_local.cfg
                block: command[check_tomcat_curl]=/usr/local/control/nrpe_check/check_tomcat.sh

```

##### EXPECTED RESULTS

I just don't inser any  marker info

##### ACTUAL RESULTS

befor running playbook the file is
```
123456
123456
```

after running playbook the file is

```
123456

command[check_tomcat_curl]=/usr/local/control/nrpe_check/check_tomcat.sh

```
Copied from original issue: ansible/ansible-modules-extras#3550

**Comment by ansibot** [comment]
From @ansibot on 2016-11-27T08:03:43Z


@yaegashi ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by naisanza** [comment]
This is happening for me as well.

```
  - name: NetBeans IDE
    blockinfile:
      path: /tmp/apps/state.xml
      create: yes
      marker: ''
      block: |
```

Ends up with an empty newline in place of the markers
