### ISSUE TITLE
IPA: can't set password for ipa_user module

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29423]
From @gelato on 2016-11-25T09:31:54Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ipa
##### ANSIBLE VERSION

```
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT
 
Linux Mint 18

##### SUMMARY

Can't add password for ipa user through ipa_user module - password is always empty in IPA
##### STEPS TO REPRODUCE

Run ipa_user module with all required fields and password field filled.

```
- name: Ensure user is present
    ipa_user:
      name: "{{ item.0.login }}"
      state: present
      givenname: "{{ item.1.first_name }}"
      sn: "{{ item.1.last_name }}"
      mail: "{{ item.1.mail }}"
      password: 123321
      telephonenumber: "{{ item.1.telnum }}"
      title: "{{ item.1.jobtitle }}"
      ipa_host: "{{ global_host }}"
      ipa_user: "{{ global_user }}"
      ipa_pass: "{{ global_pass }}"
      validate_certs: no
    with_subelements:
      - "{{ users_to_add }}"
      - personal_data
    ignore_errors: true


users_to_add:
    - username: Harley Quinn
      login: 90987264
      password: "adasdk212masd"
      cluster_zone: Default
      group: mininform
      group_desc: "Some random data for description"
      personal_data:
        - first_name: Harley
          last_name: Quinn
          mail: harley@gmail.com
          telnum: +79788880132
          jobtitle: Minister
    - username: Vasya Pupkin
      login: 77777777
      password: "adasdk212masd"
      cluster_zone: Default
      group: mininform
      group_desc: "Some random data for description"
      personal_data:
        - first_name: Vasya
          last_name: Pupkin
          mail: vasya@gmail.com
          telnum: +7970000805
          jobtitle: Vice minister
```

##### EXPECTED RESULTS

User creation with password expected.
##### ACTUAL RESULTS

User created has no password set. And module does not change user credentials (password) if you change it in playbook.

```
ok: [ipa111.krtech.loc] => (item=({u'username': u'Harley Quinn', u'group': u'mininform', u'cluster_zone': u'Default', u'group_desc': u'Some rando
m data for description', u'login': 90987264, u'password': u'adasdk212masd'}, {u'mail': u'harley@gmail.com', u'first_name': u'Harley', u'last_name
': u'Quinn', u'jobtitle': u'Minister', u'telnum': 79788880132}))
ok: [ipa111.krtech.loc] => (item=({u'username': u'Vasya Pupkin', u'group': u'mininform', u'cluster_zone': u'Default', u'group_desc': u'Some rando
m data for description', u'login': 77777777, u'password': u'adasdk212masd'}, {u'mail': u'vasya@gmail.com', u'first_name': u'Vasya', u'last_name':
 u'Pupkin', u'jobtitle': u'Vice minister', u'telnum': 7970000805}))
```

Copied from original issue: ansible/ansible-modules-extras#3545
