### ISSUE TITLE
ec2_eip does not assign an ip to an eni

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29454]
From @wimnat on 2016-11-29T23:17:02Z
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_eip

##### ANSIBLE VERSION
ansible 2.3.0 (devel a83b00bbc0) last updated 2016/11/29 22:28:22 (GMT +000)

##### CONFIGURATION
standard

##### OS / ENVIRONMENT
centos

##### SUMMARY
If trying to assign an eip to an eni, the task will fail with a boto "MissingParameter" error.

##### STEPS TO REPRODUCE
Run the following task.

```
  ec2_eip:
    region: "{{ aws_region }}"
    device_id: "{{ eni_a.interface.id }}"
    reuse_existing_ip_allowed: yes
    state: present
```

##### EXPECTED RESULTS
The ENI is assigned either a spare EIP or a new EIP

##### ACTUAL RESULTS
Task fails with the following message:

```
"EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>MissingParameter</Code><Message>Either public IP or allocation id must be specified</Message></Error></Errors><RequestID>ab0b561f-47fa-4f43-80e4-8701b6666602</RequestID></Response>"
```
Copied from original issue: ansible/ansible-modules-core#5767
