### ISSUE TITLE
yum: different results on CentOS vs RHEL

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29468]
From @SKSJeffrey on 2016-11-23T15:00:41Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

yum

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### CONFIGURATION

I am calling the ANSIBLE_ROLES_PATH environment variable during execution.

##### OS / ENVIRONMENT

Running from: **Fedora release 23 (Twenty Three)**

Managing:

1. **CentOS Linux release 7.2.1511 (Core)**
2. **Red Hat Enterprise Linux Server release 7.3 (Maipo)**

##### SUMMARY

A playbook, which installs some yum packages, succeeds on **CentOS Linux release 7.2.1511 (Core)** but fails on **Red Hat Enterprise Linux Server release 7.3 (Maipo)**.

I have confirmed that if I run `yum install <packages>` manually on both the CentOS and RHEL machines, the installation works on both machines as expected.

##### STEPS TO REPRODUCE

1. Create the playbook as shown below
2. Run the playbook on a CentOS & RHEL machine
3. Installation will run flawlessly on the CentOS machine
4. Installation will fail on the RHEL machine due to `No package matching <package_name>`

If I remove the following packages from the with_items list

1. libsemanage-python
2. policycoreutils-python
3. setroubleshoot
4. tmux

And run the playbook again on CentOS & RHEL, it will run flawlessly on both of the machines.

Another scenario that works around the problem is is breaking writing the yum module four times, one time for each of the four packages stated above. Installing them individually works on both CentOS & RHEL.

```
--
- name: Install base applications
- hosts: redhat
  yum: name={{ item }} state=present
  with_items:
    - vim-enhanced
    - gcc
    - wget
    - curl
    - chrony
    - bzip2
    - libsemanage-python
    - policycoreutils-python
    - setroubleshoot
    - firewalld
    - tmux
```

##### EXPECTED RESULTS

```
changed: [CentOS7] => (item=[u'epel-release', u'vim-enhanced', u'gcc', u'wget', u'curl', u'chrony', u'bzip2', u'libsemanage-python', u'policycoreutils-python', u'setroubleshoot', u'firewalld', u'tmux'])

changed: [RHEL7] => (item=[u'epel-release', u'vim-enhanced', u'gcc', u'wget', u'curl', u'chrony', u'bzip2', u'libsemanage-python', u'policycoreutils-python', u'setroubleshoot', u'firewalld', u'tmux'])
```

##### ACTUAL RESULTS

```
failed: [RHEL7] (item=[u'vim-enhanced', u'gcc', u'wget', u'curl', u'chrony', u'bzip2', u'libsemanage-python', u'policycoreutils-python', u'setroubleshoot', u'firewalld', u'tmux']) => 
{
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "conf_file": null, 
            "disable_gpg_check": false, 
            "disablerepo": null, 
            "enablerepo": null, 
            "exclude": null, 
            "install_repoquery": true, 
            "list": null, 
            "name": [
                "vim-enhanced", 
                "gcc", 
                "wget", 
                "curl", 
                "chrony", 
                "bzip2", 
                "libsemanage-python", 
                "policycoreutils-python", 
                "setroubleshoot", 
                "firewalld", 
                "tmux"
            ], 
            "state": "present", 
            "update_cache": false, 
            "validate_certs": true
        }, 
        "module_name": "yum"
    }, 
    "item": [
        "vim-enhanced", 
        "gcc", 
        "wget", 
        "curl", 
        "chrony", 
        "bzip2", 
        "libsemanage-python", 
        "policycoreutils-python", 
        "setroubleshoot", 
        "firewalld", 
        "tmux"
    ], 
    "msg": "No package matching 'libsemanage-python' found available, installed or updated", 
    "rc": 126, 
    "results": [
        "vim-enhanced-7.4.160-1.el7.x86_64 providing vim-enhanced is already installed", 
        "gcc-4.8.5-11.el7.x86_64 providing gcc is already installed", 
        "wget-1.14-13.el7.x86_64 providing wget is already installed", 
        "curl-7.29.0-35.el7.x86_64 providing curl is already installed", 
        "chrony-2.1.1-3.el7.x86_64 providing chrony is already installed", 
        "bzip2-1.0.6-13.el7.x86_64 providing bzip2 is already installed", 
        "No package matching 'libsemanage-python' found available, installed or updated"
    ]
}
```

Copied from original issue: ansible/ansible-modules-core#5712

**Comment by ansibot** [comment]
From @ansibot on 2016-11-23T15:00:41Z


@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @gundalow on 2016-11-23T15:00:41Z

Hi,
Thanks for the bug report. This is a strange case. 

1) If after you've manually installed the packages and rerun ansible with all the packages listed do you still get the `"No package matching 'libsemanage-python' found available, installed or updated"` message? 

2) If you run with `yum: name=libsemanage-python state=present` does it work

**Comment by ansibot** [comment]
From @wenindoubt on 2016-11-23T15:00:41Z

@gundalow 

I actually rewrote my entire playbook with the same exact code and it worked this morning.

1. I did not get to try this as I simply rewrote the entire playbook and it worked

```
# Install base applications

- name: Install base applications
  yum: name={{ item }} state=present
  with_items:
    - vim-enhanced
    - gcc
    - wget
    - curl
    - chrony
    - bzip2
    - firewalld
    - libsemanage-python
    - policycoreutils-python
    - setroubleshoot
    - tmux
```

2. If I ran `yum: name=libsemanage-python state=present`, it did work if I installed it individually.

I'm going to do some further tests this week.
