### ISSUE TITLE
Mount nfs to AIX managed host

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29477]
From @markusyou on 2016-11-18T03:28:41Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- mount
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/admin/SA/myou/.ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

Running Ansible from Red Hat Enterprise Linux Server release 6.7 (Santiago)
managing AIX 7.1.0.0

##### SUMMARY

Unable to mount NFS filesystem to managed host.  Tried NFS server on Redhat and NFS server on AIX,

##### STEPS TO REPRODUCE

```
---
- hosts: all
  tasks:
  - name: Mount AIX Filesets
    become: yes
    mount:
      name: /mnt
      src: nfshost:/home/ftp
      fstype: nfs
      state: mounted
```

##### ACTUAL RESULTS

Created a file /etc/fstab file as opposed to adding an entry in /etc/filesystems 

```
TASK [Mount /mnt] **************************************************************
fatal: [is-deva30nb]: FAILED! => {"changed": false, "failed": true, "msg": "Error mounting /mnt: mount: /mnt is not a known file system\n"}

```

Copied from original issue: ansible/ansible-modules-core#5656

**Comment by ansibot** [comment]
From @ansibot on 2016-11-18T03:28:41Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @jctanner on 2016-11-18T03:28:41Z

@markusyou are you saying that it could not mount on the rhel server either?

needs_info

**Comment by ansibot** [comment]
From @markusyou on 2016-11-18T03:28:41Z

@jctanner The issue looks to only be related to mounting to an AIX managed host. Aix uses /etc/filesystems not /etc/fstab

**Comment by ansibot** [comment]
From @chuckyz on 2016-11-18T03:28:41Z

@markusyou have you tried using the `fstab` flag like the following:

```
---
- hosts: all
  tasks:
  - name: Mount AIX Filesets
    become: yes
    mount:
      name: /mnt
      src: nfshost:/home/ftp
      fstype: nfs
      state: mounted
      fstab: /etc/filesystems
```

**Comment by ansibot** [comment]
From @abadger on 2016-11-18T03:28:41Z

needs_info

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
@markusyou Does this issue persist even with the most recent version of Ansible?

**Comment by kairoaraujo** [comment]
I performed the test using a Red Hat 6.3 Enterprise and AIX 7.1 (7100-03-01-1341).
For Ansible, I tried with devel version, playbook. The error is the same.

I went a little bit deep on debugging and I saw that it is trying to create and use /etc/fstab, but on AIX we don't have it.
```
[lpardev:root:/home/root/.ansible/tmp/ansible-tmp-1505643289.720884-49383954523071/debug_dir:] ls -la /etc/fstab
-rw-r--r--    1 root     system           40 Sep 17 11:53 /etc/fstab

[lpardev:root:/home/root/.ansible/tmp/ansible-tmp-1505643289.720884-49383954523071/debug_dir:] cat /etc/fstab
nfshost:/home/ftp /mnt nfs defaults 0 0
```

I could be working in that soon. Would be a pleasure to me include AIX support to this module.
@jtyr may I? :)

**Comment by kairoaraujo** [comment]
It can be fixed using the module aix_filesystem proposed PR #30810 

```yml

---
- hosts: all
  tasks:
  - name: Mount AIX Filesets
    become: yes
    aix_filesystem:
      filesystem: /mnt
      nfs_server: nfshost nfshost:/home/ftp
      device: /home/ftp
      state: present
```
