### ISSUE TITLE
vsphere_guest: provision VM with given resource pool

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29489]
From @KarenTovmasian on 2016-11-15T12:43:51Z

##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

```
ansible 2.2.0.0
```

##### OS / ENVIRONMENT

MacOS X Sierra
##### SUMMARY

vpshere_guest requires to provide esxi hostname and datacenter, but within our organisation we don't have rights to create VM on the host, only in Resource Pool
##### STEPS TO REPRODUCE

ansible-playbook createvm_new.yml

```
---
- name: Create a VM in resource pool
  hosts: localhost
  connection: local
  gather_facts: False
  vars_prompt:
  - name: "user"
    prompt: "Enter your username to virtualcenter"
    private: no
  - name: "password"
    prompt: "Enter your password to virtualcenter"
    private: yes
  - name: "guest"  
    prompt: "Enter you guest VM name: "
    private: no
  tasks:
  - name: create VM
    vsphere_guest:
      vcenter_hostname: virtualcenter.example.com
      validate_certs: no
      username: '{{ user }}'
      password: '{{ password }}'
      guest: '{{ guest }}'
      state: powered_off
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd: yes
        notes: This is a test VM
      vm_disk:
        disk1:
          size_gb: 10
          type: thick
          datastore: my_datastore
      vm_nic:
        nic1:
          type: vmxnet3
          network: GL-Network - Temp
          network_type: standard
      vm_hardware:
        memory_mb: 1024
        num_cpus: 1
        osid: centos64Guest
        scsi: paravirtual
      resource_pool: "/Resources/GL - VMware - Team "
      esxi:
        datacenter: my_site
        hostname: myesxhost.example.com
```

##### EXPECTED RESULTS

I expected that i only provide hardware details and Resource pool to use
##### ACTUAL RESULTS

Ansible threw an exception cause of permission denied.
If i comment out the esxi part it tells about missing key-pair

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: <pysphere.resources.VimService_services_types.NoPermissionFault_Dec_Holder object at 0x10d486a90>
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/sz/xr8xnzbd7v38fsm1kmv3tlpm0000gp/T/ansible_kbb69f/ansible_module_vsphere_guest.py\", line 1879, in <module>\n    main()\n  File \"/var/folders/sz/xr8xnzbd7v38fsm1kmv3tlpm0000gp/T/ansible_kbb69f/ansible_module_vsphere_guest.py\", line 1867, in main\n    state=state\n  File \"/var/folders/sz/xr8xnzbd7v38fsm1kmv3tlpm0000gp/T/ansible_kbb69f/ansible_module_vsphere_guest.py\", line 1414, in create_vm\n    taskmor = vsphere_client._proxy.CreateVM_Task(create_vm_request)._returnval\n  File \"build/bdist.macosx-10.11-x86_64/egg/pysphere/resources/VimService_services.py\", line 1094, in CreateVM_Task\n  File \"build/bdist.macosx-10.11-x86_64/egg/pysphere/ZSI/client.py\", line 545, in Receive\n  File \"build/bdist.macosx-10.11-x86_64/egg/pysphere/ZSI/client.py\", line 464, in Receive\npysphere.ZSI.FaultException: Permission to perform this operation was denied.\n<pysphere.resources.VimService_services_types.NoPermissionFault_Dec_Holder object at 0x10d486a90>\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

Copied from original issue: ansible/ansible-modules-core#5617
