### ISSUE TITLE
ec2_elb_lb misconfigures minimum size, desired size, and maximum size

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29482]
From @peterbsmith2 on 2016-11-16T18:23:01Z

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_elb_lb

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
Operating on: ubuntu 14.04  
Managing: ubuntu 14.04

##### SUMMARY

When updating an existing ELB with min size 2 and max size 10, inevitably sometimes the resulting configuration has a min size of 3 and max size of 11 (as well as a desired size of 3). This doesn't show up anywhere in my playbook (see below). 

##### STEPS TO REPRODUCE
```
---
# roles/auto-scaling/tasks/main.yml

- name: Retrieve current Auto Scaling Group properties
  command: "aws --region {{ region }} autoscaling describe-auto-scaling-groups --auto-scaling-group-names webapp-{{ e }}"
  register: asg_properties_result

- name: Set asg_properties variable from JSON output if the Auto Scaling Group already exists
  set_fact:
    asg_properties: "{{ (asg_properties_result.stdout | from_json).AutoScalingGroups[0] }}"
  when: (asg_properties_result.stdout | from_json).AutoScalingGroups | count

- name: Configure Auto Scaling Group and perform rolling deploy
  ec2_asg:
    region: "{{ region }}"
    name: "webapp-{{ e }}"
    launch_config_name: "{{ ec2_lc.name }}"
    availability_zones: "{{ zone }}"
    health_check_type: ELB
    health_check_period: 300
    tags:
      - Name: "webapp-{{ e }}"
        environment: "{{ e }}"
    desired_capacity: 2
    # desired_capacity: "{{ asg_properties.DesiredCapacity | default(2) }}" # broken due to bug in ansible 2.0.1.0
    replace_all_instances: yes
    replace_batch_size:  1
    # replace_batch_size: "{{ (asg_properties.DesiredCapacity | default(2) / 4) | round(0, 'ceil') | int }}" # broken due to bug in ansible 2.0.1.0
    min_size: 2
    max_size: 10
    load_balancers:
      - "webapp-{{ e }}"
    state: present
    wait_timeout: 420
  register: asg_result

- name: Configure Scaling Policies
  ec2_scaling_policy:
    region: "{{ region }}"
    name: "{{ item.name }}"
    asg_name: "webapp-{{ e }}"
    state: present
    adjustment_type: "{{ item.adjustment_type }}"
    min_adjustment_step: "{{ item.min_adjustment_step }}"
    scaling_adjustment: "{{ item.scaling_adjustment }}"
    cooldown: "{{ item.cooldown }}"
  with_items:
    - name: "Increase Group Size"
      adjustment_type: "ChangeInCapacity"
      scaling_adjustment: +1
      min_adjustment_step: 1
      cooldown: 180
    - name: "Decrease Group Size"
      adjustment_type: "ChangeInCapacity"
      scaling_adjustment: -1
      min_adjustment_step: 1
      cooldown: 300
  register: sp_result

- name: Determine Metric Alarm configuration
  set_fact:
    metric_alarms:
      - name: "{{ asg_name }}-ScaleUp"
        comparison: ">="
        threshold: 50.0
        alarm_actions:
          - "{{ sp_result.results[0].arn }}"
      - name: "{{ asg_name }}-ScaleDown"
        comparison: "<="
        threshold: 20.0
        alarm_actions:
          - "{{ sp_result.results[1].arn }}"

- name: Configure Metric Alarms and link to Scaling Policies
  ec2_metric_alarm:
    region: "{{ region }}"
    name: "{{ item.name }}"
    state: present
    metric: "CPUUtilization"
    namespace: "AWS/EC2"
    statistic: "Average"
    comparison: "{{ item.comparison }}"
    threshold: "{{ item.threshold }}"
    period: 60
    evaluation_periods: 5
    unit: "Percent"
    dimensions:
      AutoScalingGroupName: "webapp-{{ e }}"
    alarm_actions: "{{ item.alarm_actions }}"
  with_items: "{{metric_alarms}}"
  # when: max_size > 1
  register: ma_result
```

##### EXPECTED RESULTS
I expect results that look like the bottom line in the table, instead I get results like the top line.
![alt text](https://i.gyazo.com/031adc4de5340c5361f2821169716fc2.png "Results")

##### ACTUAL RESULTS
I expect results that look like the bottom line in the table, instead I get results like the top line.
![alt text](https://i.gyazo.com/031adc4de5340c5361f2821169716fc2.png "Results")

Copied from original issue: ansible/ansible-modules-core#5637
