### ISSUE TITLE
Ability to stop or start EC2 instances without changing any other settings

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29495]
From @klj613 on 2016-11-11T13:41:37Z

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION
```
ansible 2.0.1.0 (detached HEAD bb6cadefa2) last updated 2016/11/11 12:17:00 (GMT +000)
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Ability to stop or start EC2 instances without changing any other settings.

Currently some settings such as "termination_protection" have a default value which will be applied to the ec2 instance. This causes issues when you have a generic playbook to stop/start EC2 instances and some instances will have termination protection on and some will have termination protection off.

##### STEPS TO REPRODUCE

```
# stop.yml tasks
    - name: gather ec2 facts
      action: ec2_facts
    - name: stop ec2 instance
      become: False
      local_action:
        module: 'ec2'
        instance_ids: '{{ ansible_ec2_instance_id }}'
        region: 'eu-west-1'
        state: stopped
        wait: True
# start.yml tasks
    - name: gather ec2 facts
      action: ec2_facts
    - name: start ec2 instance
      become: False
      local_action:
        module: 'ec2'
        instance_ids: '{{ ansible_ec2_instance_id }}'
        region: 'eu-west-1'
        state: running
        wait: True
```

##### EXPECTED RESULTS

I would expect the ability to start or stop EC2 instances without the module attempting to change other settings.

I guess this edge case exists on multiple cloud modules.

My expectations:

- parameter not defined by me and the relevant setting is not configured yet (e.g. new EC2 instance): use the default
- parameter not defined by me and the relevant setting is already configured (e.g. existing EC2 instance): skip this parameter
- parameter defined by me: configures the relevant setting

##### ACTUAL RESULTS

The module attempted to turn termination protection off (the IAM credentials disallowed this action)

Copied from original issue: ansible/ansible-modules-core#5567
