### ISSUE TITLE
ios_facts: very limited functionality

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29490]
From @maugli13 on 2016-11-15T09:07:20Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

##### OS / ENVIRONMENT

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
##### SUMMARY

looks like ios_facts module covering only cisco routers, but switches running different version of software failing with different commands failure 
##### STEPS TO REPRODUCE

Tried on three different devices:
WS-C4500X-16 - didn't worked bootflash:/cat4500e-universalk9.SPA.03.06.04.E.152-2.E4.bin
WS-C4507R - didn't worked slot0:cat4500-entservicesk9-mz.122-31.SGA7.bin
ISR4451-X/K9 - worked bootflash:/isr4400-universalk9.03.11.01.S.154-1.S1-std.SPA.bin

```
  - name: DEFINE
    set_fact:
      connection:
        host: "{{ inventory_hostname }}"
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"


  - name: FACTS
    ios_facts:
      provider: "{{ connection }}"
      gather_subset: all
```

##### EXPECTED RESULTS

Need to improve functionality or add definition  which type of cisco devices can be used
##### ACTUAL RESULTS

Below you can find example, with problem related to command which not existing in switch envrionment

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: lgb3-wvrtcore-a#
fatal: [lgb3-wvrtcore-a]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_a6NdY9/ansible_module_ios_facts.py\", line 461, in <module>\n    main()\n  File \"/tmp/ansible_a6NdY9/ansible_module_ios_facts.py\", line 443, in main\n    runner.run()\n  File \"/tmp/ansible_a6NdY9/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 170, in run\n  File \"/tmp/ansible_a6NdY9/ansible_modlib.zip/ansible/module_utils/netcli.py\", line 98, in run_commands\n  File \"/tmp/ansible_a6NdY9/ansible_modlib.zip/ansible/module_utils/shell.py\", line 253, in run_commands\n  File \"/tmp/ansible_a6NdY9/ansible_modlib.zip/ansible/module_utils/shell.py\", line 250, in execute\nansible.module_utils.network.NetworkError: matched error in response: show memory statistics | include Processor\r\n                            ^\r\n% Invalid input detected at '^' marker.\r\n\r\nlgb3-wvrtcore-a#\n", "module_stdout": "", "msg": "MODULE FAILURE"}

```

Copied from original issue: ansible/ansible-modules-core#5614
