### ISSUE TITLE
mount module is broken on CentOS 5 in Ansible 2.2

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29491]
From @mkoshelev on 2016-11-14T17:52:43Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

mount

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

controller: Fedora 23
client host: CentOS 5.11

##### SUMMARY

'mount' module in Ansible 2.2 fails on CentOS 5 systems due to lack of /proc/self/mountinfo file. Support for mountinfo was added in kernel 2.6.26, but CentOS 5 is on kernel version 2.6.18.
The issue seems to be introduced by https://github.com/ansible/ansible-modules-core/pull/5055

##### STEPS TO REPRODUCE

Attempt to add any mount on CentOS 5 system via 'mount' module.

```
- name: mount module in Ansible 2.2 is broken on CentOS 5
  hosts: test-centos5
  remote_user: root

  tasks:
  - name: add mount to fstab
    mount: src="nfs.example.com:/SHARE" name="/mnt" fstype="nfs" opts="noauto" state=present
```

##### EXPECTED RESULTS

Mount added to /etc/fstab

##### ACTUAL RESULTS

Playbook fails due to missing /proc/self/mountinfo file.

```
PLAY [mount module in Ansible 2.2 is broken on CentOS 5] ***********************

TASK [setup] *******************************************************************
ok: [test-centos5]

TASK [add mount to fstab] ******************************************************
fatal: [test-centos5]: FAILED! => {"changed": false, "failed": true, "msg": "Cannot open file /proc/self/mountinfo"}

PLAY RECAP *********************************************************************
test-centos5               : ok=1    changed=0    unreachable=0    failed=1   
```

Copied from original issue: ansible/ansible-modules-core#5603
