### ISSUE TITLE
dellos9_command confirm prompt timeout

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29505]
From @ebmarquez on 2016-11-08T19:04:09Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

dellos9_command 
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/emarq/Solutions.Network.Automation/MAS/Ansible/dell/force10/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Linux rr1masdansible 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

copy config to the startup-config on the local flash breaks because of yes/no prompt.

##### STEPS TO REPRODUCE

```
- name: issue delete and copy old config
  dellos9_command:
    provider: "{{ cli }}"
    commands:
      - "delete flash://{{ inventory_hostname }}.conf no-confirm"
      - "delete flash://startup-conifg no-confirm"
      - "copy tftp://10.10.240.253:/{{ inventory_hostname }}.conf flash://{{ inventory_hostname }}.conf"
      - "copy flash://{{ inventory_hostname }}.conf startup-config"
```

##### EXPECTED RESULTS

copy command should have completed and provided a default yes for the os prompt.

rr1-n22-r14-4048hl-5-1a#$sh://rr1-n22-r14-4048hl-5-1a.conf startup-config      
File with same name already exist. 
Proceed to copy the file [confirm yes/no]:
##### ACTUAL RESULTS

```
fatal: [rr1-n22-r14-4048hl-5-1a]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": false,
            "commands": [
                "delete flash://rr1-n22-r14-4048hl-5-1a.conf no-confirm",
                "delete flash://startup-conifg no-confirm",
                "copy tftp://10.10.240.253:/rr1-n22-r14-4048hl-5-1a.conf flash://rr1-n22-r14-4048hl-5-1a.conf",
                "copy flash://rr1-n22-r14-4048hl-5-1a.conf startup-config"
            ],
            "host": "10.10.234.161",
            "interval": 1,
            "password": null,
            "port": null,
            "provider": {
                "host": "10.10.234.161",
                "ssh_keyfile": "/srv/tftpboot/masd-rsa.pub",
                "transport": "cli",
                "username": "admin"
            },
            "retries": 10,
            "ssh_keyfile": "/srv/tftpboot/masd-rsa.pub",
            "timeout": 10,
            "transport": "cli",
            "username": "admin",
            "wait_for": null
        },
        "module_name": "dellos9_command"
    },
    "msg": "timeout trying to send command: copy flash://rr1-n22-r14-4048hl-5-1a.conf startup-config\r"
}
```

Copied from original issue: ansible/ansible-modules-core#5534

**Comment by ansibot** [comment]
From @ansibot on 2016-11-08T19:04:09Z



@dhivyap, @skg-net, @privateip, @gundalow, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @skg-net on 2016-11-08T19:04:09Z

!needs_info.  We will work on this.

@ebmarquez  Please use dellos9_config module as work around. By adding a ‘do’ keyword in front the cli.

```
 -  name: issue delete and copy old config
    dellos9_config:
    provider: "{{ cli }}"
    commands:
      - "do delete flash://{{ inventory_hostname }}.conf no-confirm"
      - "do delete flash://startup-conifg no-confirm"
      - "do copy tftp://10.10.240.253:/{{ inventory_hostname }}.conf flash://{{ inventory_hostname }}.conf"
      - "do copy flash://{{ inventory_hostname }}.conf startup-config"

```
