### ISSUE TITLE
Nxos_reboot ends in timeout error when it's successfull 

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29522]
From @ebmarquez on 2016-11-03T21:32:57Z

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_reboot
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /home/emarq/Solutions.Network.Automation/MAS/Ansible/cisco/nexus/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

[defaults]
hostfile=localstage
#hostfile=mas-b43
ansible_ssh_user=admin
ansible_ssh_private_key_file=/home/emarq/.ssh/masd-rsa
host_key_checking=False

##### OS / ENVIRONMENT

Linux rr1masdansible 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

Switch is rebooted but Ansible errors out.
##### STEPS TO REPRODUCE

```

---
- name: copy configs
  hosts:
    - n35-bmc
    - basebmctemplate
    - n35-tor
    - basetortemplate
    - basetor40gtemplate
    - n35-agg
    - baseaggtemplate
  remote_user: admin
  gather_facts: no
  connection: local
  vars:
    cli:
      host: "{{ ansible_host }}"
      transport: cli
      username: admin
      ssh_keyfile: /srv/tftpboot/my-rsa.pub
  roles:
    - copyfirmware

roles/copyfirmware/tasks/main.yml

---
- nxos_reboot:
    provider: "{{ cli }}"
    confirm: true
    host: "{{ ansible_host }}"
    username: admin
    ssh_keyfile: /srv/tftpboot/my-rsa.pub
```

##### EXPECTED RESULTS

reload switch end with a success value.
##### ACTUAL RESULTS

```
TASK [copyfirmware : nxos_reboot] **********************************************
task path: /home/emarq/Solutions.Network.Automation/MAS/Ansible/cisco/nexus/roles/copyfirmware/tasks/main.yml:23
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/core/network/nxos/nxos_reboot.py
<10.10.228.60> ESTABLISH LOCAL CONNECTION FOR USER: emarq
<10.10.228.60> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478208427.24-135809306234074 `" && echo ansible-tmp-1478208427.24-135809306234074="` echo $HOME/.ansible/tmp/ansible-tmp-1478208427.24-135809306234074 `" ) && sleep 0'
<10.10.228.60> PUT /tmp/tmp31WWF5 TO /home/emarq/.ansible/tmp/ansible-tmp-1478208427.24-135809306234074/nxos_reboot.py
<10.10.228.60> EXEC /bin/sh -c 'chmod u+x /home/emarq/.ansible/tmp/ansible-tmp-1478208427.24-135809306234074/ /home/emarq/.ansible/tmp/ansible-tmp-1478208427.24-135809306234074/nxos_reboot.py && sleep 0'
<10.10.228.60> EXEC /bin/sh -c '/usr/bin/python /home/emarq/.ansible/tmp/ansible-tmp-1478208427.24-135809306234074/nxos_reboot.py; rm -rf "/home/emarq/.ansible/tmp/ansible-tmp-1478208427.24-135809306234074/" > /dev/null 2>&1 && sleep 0'
fatal: [rr1-n22-r09-3132hl-3-1d]: FAILED! => {
    "changed": false,
    "error": "timeout trying to send command: reload\r",
    "failed": true,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": false,
            "config": null,
            "confirm": true,
            "host": "10.10.228.60",
            "include_defaults": "False",
            "password": null,
            "port": null,
            "provider": {
                "host": "10.10.228.60",
                "ssh_keyfile": "/srv/tftpboot/my-rsa.pub",
                "transport": "cli",
                "username": "admin"
            },
            "save": false,
            "ssh_keyfile": "/srv/tftpboot/my-rsa.pub",
            "timeout": 10,
            "transport": "cli",
            "use_ssl": false,
            "username": "admin",
            "validate_certs": true
        },
        "module_name": "nxos_reboot"
    },
    "msg": "Error sending ['reload']"
}
        to retry, use: --limit @/home/emarq/Solutions.Network.Automation/MAS/Ansible/cisco/nexus/nexusbaseconfig.retry
```

Copied from original issue: ansible/ansible-modules-core#5486
