### ISSUE TITLE
Modifying VM with vsphere_guest failing with current_devices is not defined.

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29552]
From @bhudlemeyer on 2016-10-26T16:23:00Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

vsphere_guest 
##### ANSIBLE VERSION

```
[core@bhudcent7 coreos]$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[core@bhudcent7 coreos]
```
##### SUMMARY

When trying to perform reconfigure of exiting vm failing with global name ' current_devices' is not defined
##### STEPS TO REPRODUCE

```

---
- name: Create mesos VMS
  hosts: localhost
  connection: local

  tasks:
   - name: modify master vms
     vsphere_guest:
       vcenter_hostname: IP
       username: USERNAME
       password: PW
       guest: "{{ item }}"
       state: reconfigured
       vm_extra_config:
         vcpu.hotadd: yes
         mem.hotadd:  yes
         notes: Mesos Master
         folder: Mesos
       vm_hardware:
         memory_mb: 16384
         num_cpus: 2
         osid: centos64Guest
         scsi: paravirtual
         vm_cdrom:
           type: "iso"
           iso_path: "CENTOS2/ISO/mesos/configdrive-{{ item }}.iso"
       esxi:
         datacenter: HomeLab
         hostname: 192.168.1.21
     with_items:
         - mesosm01
         - mesosm02
         - mesosm03
```

##### EXPECTED RESULTS

Modify vm ram/cpu and ISO attached to VM
##### ACTUAL RESULTS

496600.14-13851980734504/" > /dev/null 2>&1 && sleep 0'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_gzRBRs/ansible_module_vsphere_guest.py", line 1929, in <module>
    main()
  File "/tmp/ansible_gzRBRs/ansible_module_vsphere_guest.py", line 1856, in main
    force=force
  File "/tmp/ansible_gzRBRs/ansible_module_vsphere_guest.py", line 924, in reconfigure_vm
    for dev in current_devices:
NameError: global name 'current_devices' is not defined

failed: [localhost](item=mesosm03) => {"failed": true, "invocation": {"module_name": "vsphere_guest"}, "item": "mesosm03", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_gzRBRs/ansible_module_vsphere_guest.py\", line 1929, in <module>\n    main()\n  File \"/tmp/ansible_gzRBRs/ansible_module_vsphere_guest.py\", line 1856, in main\n    force=force\n  File \"/tmp/ansible_gzRBRs/ansible_module_vsphere_guest.py\", line 924, in reconfigure_vm\n    for dev in current_devices:\nNameError: global name 'current_devices' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

Copied from original issue: ansible/ansible-modules-core#5393
