### ISSUE TITLE
docker_container networks not working as expected (viz. mac addresses)

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29558]
From @gfarrell on 2016-10-24T17:33:05Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

docker_container
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = 
  configured module search path = Default w/o overrides

```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

[Relevant Docker docs](https://docs.docker.com/engine/reference/run/#/network-settings). Should be able to set mac address for the connected networks (I have my container connected to two networks, but need its mac address set in one of them. Using the `mac_address` configuration option only sets the address in the default bridge network, not in my custom network.
##### STEPS TO REPRODUCE

Try to set mac address on container, fail to do so.

```
- name: start container
  become: false
  docker_container:
    name: blah
    state: started
    restart_policy: always
    image: "{{ blah.image }}"
    env: "{{ blah.environment }}"
    log_opt: "{{ log_opts }}"
    volumes: "{{ blah.volumes }}"
    ports: "{{ blah.ports }}"
    mac_address: "{{ mac_address.stdout }}"
    networks:
        - name: "{{ custom_network_name }}"
          ipv6_address: "{{ blah_ipv6_address }}"
          driver: bridge
```
##### EXPECTED RESULTS

I would expect the custom network to have the mac address specified.
##### ACTUAL RESULTS

Container gets two networks, one being the default bridge, the other being the custom network. Only the former gets the custom mac address.

Copied from original issue: ansible/ansible-modules-core#5371
