### ISSUE TITLE
Azure storage account facts module returns no facts at all

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29550]
From @gvilarino on 2016-10-26T21:22:43Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`azure_rm_storageaccount_facts`
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /usr/src/playbooks/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Ubuntu 14.04 LTS
##### SUMMARY

The module returns no useful information and provides no value. I have to fall back to the `azure-cli` `node.js` module in order to retrieve the storage account keys and manually parse the text output.
##### STEPS TO REPRODUCE

Just run this:

```
- name: Get azure facts
  azure_rm_storageaccount_facts:
    name: "{{ account_name }}"
    resource_group: "{{ resource_group }}"
    client_id: "{{ client_id }}"
    secret: "{{ client_secret }}"
    subscription_id: "{{ subscription_id }}"
    tenant: "{{ tenant_id }}"
```
##### EXPECTED RESULTS

Account access keys, blob/containers if any, etc. Basically, useful information about the storage account, which I could use. I'd expect the exact same capabilities as the official `azure-cli` by Microsoft, buy I'd settle for simple stuff. The fact that this doesn't return anything useful makes the `azure_rm_storageaccount` useless for automation, since you can create/destroy storage accounts but you can't get their access keys.
##### ACTUAL RESULTS

```
ok: [localhost] => {
    "out_account_facts": {
        "ansible_facts": {
            "azure_storageaccounts": [
                {
                    "location": "eastus", 
                    "tags": {}
                }
            ]
        }, 
        "changed": false
    }
}
```

Copied from original issue: ansible/ansible-modules-core#5399
