### ISSUE TITLE
vsphere_guest: index out of range exception while reconfiguring disk size

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29569]
From @LuAmRaTeu on 2016-10-19T08:27:34Z

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ansible_module_vsphere_guest
##### ANSIBLE VERSION

```
ansible 2.1.2.0
```
##### OS / ENVIRONMENT

Centos7
##### SUMMARY

got index out of range exception while configuring vm with vsphere_guest
##### STEPS TO REPRODUCE

```

---
- hosts: localhost
  gather_facts: false
  connection: local
  roles:
   -  vm_create
...

---
# tasks file for vm_create

- name: check for dependency python-pip
  yum: name="{{item}}" state=latest
  with_items:
    - python-pip

- name: check for dependencies
  pip: name="{{item}}" state=latest
  with_items:
    - pysphere
    - pyvmomi 

- name: create vm from template
  vsphere_guest:
    vcenter_hostname: "{{vcenter_hostname}}" 
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    guest: "test_01"
    from_template: yes
    template_src: "{{ vm_template }}"
    cluster: "{{ cluster }}"
    resource_pool: "{{ resource_pool }}"
    power_on_after_clone: "no" 
  tags: 
   - create

- name: reconfigure vm
  vsphere_guest:
    vcenter_hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    guest: "test_01"
    state: reconfigured
    vm_extra_config:
      notes: "created with ansible vsphere"
    vm_disk:
      disk1:
        size_gb: "{{ disk_main }}"
        type: thin
        datastore: "{{ datastore }}"
      disk2:
        size_gb: "{{ disk_var }}"
        type: thin
        datastore: "{{ datastore }}"
      disk3:
        size_gb: "{{ disk_opt }}"
        type: thin
        datastore: "{{ datastore }}"     
      disk4:
        size_gb: "{{ disk_home }}"
        type: thin
        datastore: "{{ datastore }}"     
    vm_nic:
      nic1:
        type: "vmxnet3"
        network: "VM Network"
        network_type: "standard"
    vm_hardware:
      memory_mb: "{{ memory }}"
      num_cpus: "{{ cpucount }}"
      osid: "{{ osid }}"
      scsi: paravirtual
    esxi:
      datacenter: "{{ datacenter }}"
      hostname: "{{ esxi_host }}"    
...

```

##### EXPECTED RESULTS

normal playthrough with reconfigured disk-sizes
##### ACTUAL RESULTS

creating vm from template works fine, but reconfiguring fails with exception

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_BSLEdg/ansible_module_vsphere_guest.py", line 1879, in <module>
    main()
  File "/tmp/ansible_BSLEdg/ansible_module_vsphere_guest.py", line 1806, in main
    force=force
  File "/tmp/ansible_BSLEdg/ansible_module_vsphere_guest.py", line 842, in reconfigure_vm
    module, vm_disk, changes)
  File "/tmp/ansible_BSLEdg/ansible_module_vsphere_guest.py", line 773, in update_disks
    hdd_id = vm._devices[dev_key]['label'].split()[2]
IndexError: list index out of range
```

Copied from original issue: ansible/ansible-modules-core#5309
