### ISSUE TITLE
docker_container - missing cap_drop

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29578]
From @gtirloni on 2016-10-17T15:15:06Z
##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

docker_container module
##### ANSIBLE VERSION

ansible 2.1.2.0
##### SUMMARY

docker_container module does not support removing capabilities (i.e. docker --cap-drop option). 

cap_drop and cap_add were added to the docker module in ansible 2.0 but that module is marked as deprecated now.

Copied from original issue: ansible/ansible-modules-core#5286

**Comment by ansibot** [comment]
From @ansibot on 2016-10-17T15:15:06Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @smuthali on 2016-10-17T15:15:06Z

This affects Ansible 2.2 as well

**Comment by ansibot** [comment]
cc @ThomasSteinbach @cove @dusdanig @jctanner @kassiansun @softzilla @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @joshuaconner
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jstephenson** [comment]
Is there some philosophical basis for supporting cap add but not drop? If not I'll start on a patch ...

**Comment by kassiansun** [comment]
@jstephenson no, just because docker add too many command line options since `docker_container` added...

**Comment by DavidWittman** [comment]
@jstephenson I just [opened a PR](https://github.com/ansible/ansible/pull/36889) which adds the `cap_drop` option... please test it out and report any issues!

**Comment by Akasurde** [comment]
resolved_by_pr #36889

**Comment by jstephenson** [comment]
@DavidWittman Great, thanks, I'll give it a go!

**Comment by Akasurde** [comment]
@jstephenson Can you please check if above mentioned PR works for you ? Thanks.

**Comment by Akasurde** [comment]
needs_info

**Comment by jstephenson** [comment]
@Akasurde Apologies, promptly forgot about this. Will verify later today.

**Comment by Akasurde** [comment]
@jstephenson Thanks.

**Comment by jstephenson** [comment]
Looks good to me (see below). As an aside, wouldn't it be lovely if the incredibly misleading `capabilities` were to be renamed `cap_add`? Not one for this PR I'm sure, but how would that be achieved in the context of Ansible's depreciation policy/other relevant things?

```yaml
- hosts: all
  tasks:
    - docker_container:
        name: capability-test
        image: ubuntu
        recreate: yes
        command: /bin/bash -c 'while true; do echo hello world; sleep 10; done'
```
```
... $ cat /proc/26445/status | grep ^CapEff
CapEff:	00000000a80425fb
... $ capsh --decode=00000000a80425fb
0x00000000a80425fb=cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
```
and then
```yaml
- hosts: all
  tasks:
    - docker_container:
        name: capability-test
        image: ubuntu
        cap_drop:
          - CHOWN
          - DAC_OVERRIDE
        recreate: yes
        command: /bin/bash -c 'while true; do echo hello world; sleep 10; done'
```
```
... $ cat /proc/27378/status | grep ^CapEff
CapEff:	00000000a80425f8
... $ capsh --decode=00000000a80425f8
0x00000000a80425f8=cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_mknod,cap_audit_write,cap_setfcap
```
