### ISSUE TITLE
Copy module takes forever 

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29589]
From @Mihai-CMM on 2016-10-11T13:49:39Z
##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

Copy module
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### OS / ENVIRONMENT

Managing OS: Fedora 22 
Managed node OS: Centos 6.8 VM in Proxmox
##### SUMMARY

Copying one file takes forever. Sometimes ssh connection expires before copy action is finished
##### STEPS TO REPRODUCE

```
- hosts: proxmox
   vars_files:
      - files/configuration/proxcred.yml
      - files/configuration/configuration.yml
    remote_user: root
    tasks:
   - name: copy superadmin.sql function to remote machine
     copy: src="superadmin.sql"  dest="/var/log/superadmin.sql"
```

##### EXPECTED RESULTS

Copy takes a veeeeery long time / ssh connection expires 

Copied from original issue: ansible/ansible-modules-core#5227
