### ISSUE TITLE
'azure_rm_subnet' with 'state: absent' fails when subnet was already not existing

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29593]
From @techraf on 2016-10-10T13:16:21Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

azure_rm_subnet
##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /home/techraf/devops/infra-azure/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Debian Jessie
##### SUMMARY

`azure_rm_subnet` requires the parameter `virtual_network_name` to be provided, otherwise:

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: virtual_network_name"}
```

**But** running the module with `state: absent` fails when the virtual network specified in `virtual_network_name` is non-existent.
##### STEPS TO REPRODUCE

Delete the virtual_network then run the `azure_rm_subnet` task with `state: absent`.

```
- name: Ensure subnet does not exist
  azure_rm_subnet:
    resource_group: Testing
    name: subnet001
    state: absent
    virtual_network_name: testvn001
```
##### EXPECTED RESULTS

```
ok: [localhost]
```
##### ACTUAL RESULTS

```
TASK [Ensure subnet does not exist] ********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error deleting subnet subnet001 - The Resource 'Microsoft.Network/virtualNetworks/testvn001' under resource group 'Testing' was not found."}
```

Copied from original issue: ansible/ansible-modules-core#5211
