### ISSUE TITLE
azure_rm_networkinterface cannot create interface if virtual network is in different resource group

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29607]
From @amz on 2016-10-06T09:59:42Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

azure_rm_networkinterface module
##### ANSIBLE VERSION

ansible 2.1.2.0
  config file = /home/amz/ansible/ansible.cfg
  configured module search path = Default w/o overrides
##### SUMMARY

Cannot create network interface to connect to virtual network in other resource group.
##### STEPS TO REPRODUCE

Create task:

```
- name: Create a network interface with minimal parameters
  azure_rm_networkinterface:
      name: "interfaceName"
      resource_group: "ansibleManaged"
      virtual_network_name: "sharedNetwork"
      subnet_name: default
      location: "northeurope"
```

##### EXPECTED RESULTS

Create network interface. Virtual Network in ARM are restricted to region no to resource group. It should be possible to access Virtual Network in same region.
##### ACTUAL RESULTS

Interface creation task faile because it can't find virtual network in 

```
TASK [azure : Create a network interface with minimal parameters] **************
task path: /home/amz/ansible/roles/azure/tasks/create_azure.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: amz
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441 `" && echo ansible-tmp-1475747675.66-52569430125441="` echo $HOME/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpguR_EI TO /home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/azure_rm_networkinterface
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/ /home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/azure_rm_networkinterface && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'LANG=pl_PL.UTF-8 LC_ALL=pl_PL.UTF-8 LC_MESSAGES=pl_PL.UTF-8 python /home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/azure_rm_networkinterface; rm -rf "/home/amz/.ansible/tmp/ansible-tmp-1475747675.66-52569430125441/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"ad_user": null, "append_tags": true, "client_id": null, "location": "northeurope", "name": "interfaceName", "open_ports": null, "os_type": "Linux", "password": null, "private_ip_address": null, "private_ip_allocation_method": "Dynamic", "profile": null, "public_ip": true, "public_ip_address_name": null, "public_ip_allocation_method": "Dynamic", "resource_group": "ansibleManaged", "secret": null, "security_group_name": null, "state": "present", "subnet_name": "default", "subscription_id": null, "tags": null, "tenant": null, "virtual_network_name": "sharedNetwork"}, "module_name": "azure_rm_networkinterface"}, "msg": "Error: fetching subnet default in virtual network sharedNetwork - The Resource 'Microsoft.Network/virtualNetworks/sharedNetwork' under resource group 'ansibleManaged' was not found."}

```

Copied from original issue: ansible/ansible-modules-core#5172

**Comment by ansibot** [comment]
From @ansibot on 2016-10-06T09:59:42Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @jschwanz on 2016-10-06T09:59:42Z

I'm being impacted by this one as well.

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @tstringer
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pmusolino-rms** [comment]
I am also impacted by this.  In my case, trying to attach a public IP to an existing interface in one resource group, but the vnet/subnets are in a different resource group.
from the CLI, I can do:
`
az network nic ip-config update -g $RG --nic-name $NICNAME -n $NICIPCONFIG --public-ip-address $PUBLICIP
`
whereas the below fails
```
- name: Associate IP with Nic
  azure_rm_networkinterface:
      name: "{{ nicname }}"
      resource_group: "{{ rg }}"
      virtual_network_name: "{{ vnet }}"
      public_ip_address_name: "{{ publicip }}"
      subnet_name: "{{ subnet }}"
```
trying the resource group associated with the networks gives a similar error but stating it cannot find the nic in that RG.

In my case:  ansible 2.4.0

**Comment by ansibot** [comment]
cc @chouseknecht
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @xscript @yaweiw @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MarkRoddick** [comment]
any update on this issue? it also affects azure_rm_virtualmachine if the vnet/subnet is in a different resource group

**Comment by yaweiw** [comment]
@yuwzho @zikalino can you take a look?

**Comment by siaomingjeng** [comment]
I've modified this module, adding the support for net/subnet from a different resource group.
In addition, I also added the support for load balancer backend address pool.

It have been submit. Not sure when will be absorbed.

**Comment by liyaka** [comment]
I also have the same problem - 
I'm trying to create a VM connected to a virtual network in another resource group, and in order to do it I want create an interface in the same resource group with my VM.
I was able to do it manually using Azure management UI, so there shouldn't be a problem to implement it with ansible. 
I believe implementing 'virtual_network_resource_group' parameter for azure_rm_networkinterface will do the job.

**Comment by wjonker85** [comment]
I'am happy that this has been solved :). I manually download the this py file form your fork. Hopefully it wil get soon into the master so I do not need tot do this anymore.

**Comment by yuwzho** [comment]
This feature is included in #32882 . where the virtual network can be referenced as the resource id.

**Comment by ansibot** [comment]
cc @trstringer
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
resolved_by_pr 32882

**Comment by liyaka** [comment]
@yuwzho How is it solved? Is there an option to define virtual_network_resource_group in azure_rm_networkinterface? 
It looks like az cli does not support this option as well, although it can be done from UI

**Comment by yuwzho** [comment]
@liyaka  This module can accept [virtual_network_name or virtual_network](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py#L56) as name or ID. Since the id including the virtual network resource group information, the nic can be created with VN in another resource group. That means if you want to create a NIC with virtualnetwork in another resource group, set the virtual_network_name to virtual_network id. BTW, az-cli has the same usage.

**Comment by liyaka** [comment]
@yuwzho It doesn't work -

My task:
```
- name: Create NIC
  azure_rm_networkinterface:
    resource_group: "devops"
    name: "{{ az_vmname }}001"
    virtual_network_name: "CSRVnet"
    subnet_name: "default"
    public_ip: no
    security_group: "sec1"
```

while CSRVnet network is in different resource group.
Here is the error I get:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error: fetching subnet default in virtual network CSRVnet - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Network/virtualNetworks/CSRVnet' under resource group 'devops' was not found."}
```

**Comment by liyaka** [comment]
@yuwzho 
Same for az cli:
```
az network nic create -g devops -n nnnn001 --subnet default --vnet-name CSRVnet

```
The error:
```
Resource /subscriptions/7ace04f8-fba8-4c0a-abb8-4d4a9377a9dd/resourceGroups/devops/providers/Microsoft.Network/virtualNetworks/CSRVnet/subnets/default referenced by resource /subscriptions/7ace04f8-fba8-4c0a-abb8-4d4a9377a9dd/resourceGroups/devops/providers/Microsoft.Network/networkInterfaces/jenkins-slave-test555 was not found. Please make sure that the referenced resource exists, and that both resources are in the same region.
```

**Comment by yuwzho** [comment]
@liyaka For the az-cli error, you can raise an issue at [Azure/azure-cli](https://github.com/Azure/azure-cli) repo. According to my previous comment, you should use id instead of name in `--subnet` and `--vnet-name`. Or the cli will find the resources under resource group specified in `-g` parameter

**Comment by liyaka** [comment]
@yuwzho doesn't work:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error: fetching subnet default in virtual network /subscriptions/xxxxxx/resourceGroups/CSRVnet/providers/Microsoft.Network/virtualNetworks/CSRVnet - Azure Error: ResourceNotFound\nMessage: The Resource 'Microsoft.Network/virtualNetworks/subscriptions' under resource group 'devops' was not found."}
```

(virtual_network is defined as `/subscriptions/xxxxxx/resourceGroups/CSRVnet/providers/Microsoft.Network/virtualNetworks/CSRVnet`)

**Comment by liyaka** [comment]
@yuwzho another thing - resource group that specified in -g parameter is the resource group where I want to create a network interface, but the virtual network is in another resource group and it is not supported..

**Comment by ljtill** [comment]
Any update on this?

**Comment by yuwzho** [comment]
@liyaka I think the update is not released for ansible yet. But you can try the [`Azure.azure_modules`](https://galaxy.ansible.com/Azure/azure_modules/) ansible role.

* Install the ansible-role by running `ansible-galaxy install Azure.azure_modules`.  
* Run this [playbook](https://github.com/Azure-Samples/ansible-playbooks/blob/master/networkinterface_with_virtualnetwork_in_another_resource_group.yml). You can see the NIC refer virtual network using id instead of name.

**Comment by liyaka** [comment]
@yuwzho Thanks, but it means i need to rewrite my role which is used for other cases as well (and works just fine).
I believe the issue can not be closed till it is released...

**Comment by savishy** [comment]
For those that came late:

As of Ansible 2.5 (released recently) [the solution mentioned above](https://github.com/ansible/ansible/issues/29607#issuecomment-363978444) _does_ work. No need to use the Azure.azure_modules Ansible role. 

i.e if you want to use VNets from other resource groups, _use the full VNet ID instead of the VNet Name._


Here's a simple example of a playbook:

```
---
- name: Test
  hosts: localhost
  connection: local
  tasks:
    - azure_rm_resourcegroup:
        name: testrgvish
        location: northeurope
        state: present
    - name: Create virtual NICs {{nic_name}}
      azure_rm_networkinterface:
        resource_group: testrgvish
        name: testrgnic
        virtual_network: '/subscriptions/XXXXXXXXXXXXXXXX/resourceGroups/Networks/providers/Microsoft.Network/virtualNetworks/AZRVISH-VNET'
        subnet: VishSubnet
        public_ip_name: None
        security_group: AZRVISH-NSG
```
