### ISSUE TITLE
hg: updating to empty changeset (a.k.a. revision -1 or null) doesn't work

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29617]
From @antonv6 on 2016-10-03T06:22:21Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

hg
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /home/argh/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Running from Debian GNU/Linux testing, managing Ubuntu 14.04.5 LTS.
##### SUMMARY

Pulling all changes and updating a Mercurial repo to empty changeset (for backup/mirroring purposes, for example) used to work(?) with `revision: null`, now it doesn't. It also doesn't work with `revision: -1`, but works with `revision: 'null'` (i.e. with quotes).
##### STEPS TO REPRODUCE

``` yaml
- name: Pull an example repo
  hg:
    repo: https://www.mercurial-scm.org/repo/hello/
    dest: /tmp/hello
    revision: null # or -1
```
##### EXPECTED RESULTS

The repo is cloned/pulled, and only contains .hg/ directory with file history, but no files in working directory. At the initial clone the report with -vv should say `{... "before": "", "after": "000000000000 default" ...}`.
##### ACTUAL RESULTS

Cloning/pulling works fine, but there are `Makefile` and `hello.c`, updated to the latest revision. Also, with -vv the report says `{... "before": "", "after": "82e55d328c8c default tip" ...}`.

Copied from original issue: ansible/ansible-modules-core#5127
