### ISSUE TITLE
mysql_user is not idempotent with complex priv

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29625]
From @HanXHX on 2016-09-28T12:43:03Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

mysql_user
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

None.
##### OS / ENVIRONMENT
- Ansible host: Xubuntu 16.04 
- Ansible target: Debian Jessie + MariaDB 10.1 (with galera module activated)
##### SUMMARY

With "complex" privs, _mysql_user_ module is not idempotent. The module should not have a state changed.
##### STEPS TO REPRODUCE

```
- hosts: tag_Db_1
  vars:
    c_mysql_users:
      - name: "monitor"
        password: "1a2b3c"
        priv: '*.*:SHOW DATABASES,REPLICATION CLIENT/mysql.user:SELECT/mysql.db:SELECT/mysql.tables_priv:SELECT'
        host: "%"
      - name: "monitor2"
        password: "1a2b3c"
        priv: '*.*:SHOW DATABASES,REPLICATION CLIENT/mysql.*:SELECT'
        host: "%"
  tasks:
    - block:

      - name: MYSQL_USERS | Create users
        mysql_user: >
          name="{{ item.name }}"
          password="{{ item.password }}"
          host="{{ item.host }}"
          priv='{{ item.priv }}'
        with_items: "{{ c_mysql_users }}"

      run_once: true

```
##### EXPECTED RESULTS

On second launch, mysql_user module should not change.
##### ACTUAL RESULTS

User "monitor2" is not changed but user "monitor" have changed state every time

```
PLAYBOOK: bug.yml **************************************************************
1 plays in bug.yml

PLAY [tag_Db_1] ****************************************************************

TASK [setup] *******************************************************************
ok: [db2]
ok: [db1]

TASK [MYSQL_USERS | Create users] **********************************************
task path: /home/hanx/dev/na/ansible/affil/bug.yml:15
changed: [db1] => (item={u'host': u'%', u'password': u'1a2b3c', u'name': u'monitor', u'priv': u'*.*:SHOW DATABASES,REPLICATION CLIENT/mysql.user:SELECT/mysql.db:SELECT/mysql.tables_priv:SELECT'}) => {"changed": true, "item": {"host": "%", "name": "monitor", "password": "1a2b3c", "priv": "*.*:SHOW DATABASES,REPLICATION CLIENT/mysql.user:SELECT/mysql.db:SELECT/mysql.tables_priv:SELECT"}, "user": "monitor"}
ok: [db1] => (item={u'host': u'%', u'password': u'1a2b3c', u'name': u'monitor2', u'priv': u'*.*:SHOW DATABASES,REPLICATION CLIENT/mysql.*:SELECT'}) => {"changed": false, "item": {"host": "%", "name": "monitor2", "password": "1a2b3c", "priv": "*.*:SHOW DATABASES,REPLICATION CLIENT/mysql.*:SELECT"}, "user": "monitor2"}

PLAY RECAP *********************************************************************
db1                        : ok=2    changed=1    unreachable=0    failed=0   
db2                        : ok=1    changed=0    unreachable=0    failed=0   

```

There is grant output on my server:

```
MariaDB [(none)]> show grants for 'monitor';
+-------------------------------------------------------------------------------------------------------------------------------------+
| Grants for monitor@%                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------+
| GRANT SHOW DATABASES, REPLICATION CLIENT ON *.* TO 'monitor'@'%' IDENTIFIED BY PASSWORD '*09D6E9E852C3A9F6BDC1C52834B361317225F914' |
| GRANT SELECT ON `mysql`.`db` TO 'monitor'@'%'                                                                                       |
| GRANT SELECT ON `mysql`.`user` TO 'monitor'@'%'                                                                                     |
| GRANT SELECT ON `mysql`.`tables_priv` TO 'monitor'@'%'                                                                              |
+-------------------------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)

MariaDB [(none)]> show grants for 'monitor2';
+--------------------------------------------------------------------------------------------------------------------------------------+
| Grants for monitor2@%                                                                                                                |
+--------------------------------------------------------------------------------------------------------------------------------------+
| GRANT SHOW DATABASES, REPLICATION CLIENT ON *.* TO 'monitor2'@'%' IDENTIFIED BY PASSWORD '*09D6E9E852C3A9F6BDC1C52834B361317225F914' |
| GRANT SELECT ON `mysql`.* TO 'monitor2'@'%'                                                                                          |
+--------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)
```

Copied from original issue: ansible/ansible-modules-core#5075
