### ISSUE TITLE
Validation with visudo does not work for lineinfile if 

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29623]
From @yves-vogl on 2016-09-29T14:30:34Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

lineinfile
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

```
CentOS Linux release 7.2.1511 (Core) 
Linux 3.10.0-327.18.2.el7.x86_64 #1 SMP Thu May 12 11:03:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

When trying to create or modify a file in _/etc/sudoers.d_ by using the `lineinfile` module the validation with visudo fails because a temporary file is not found.

http://docs.ansible.com/ansible/lineinfile_module.html
##### STEPS TO REPRODUCE

```
- name: Setup sudoers permissions
  lineinfile: dest=/etc/sudoers.d/icinga2 
              create=yes
              state=present 
              line='icinga ALL=(ALL) NOPASSWD:/usr/bin/find' 
              validate='visudo -cf %s'
```
##### EXPECTED RESULTS

A file created under _/etc/sudoers.d/icinga2_  with the content `icinga ALL=(ALL) NOPASSWD:/usr/bin/find`which passed validation.
##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "cmd": "visudo -cf /tmp/tmpSBsM5A", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2
```

Copied from original issue: ansible/ansible-modules-core#5091

**Comment by ansibot** [comment]
From @ansibot on 2016-09-29T14:30:34Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @lazize on 2016-09-29T14:30:34Z

Facing the same problem here.

**Task:**

```
    - name: Add sudo permisssion and validate the file before save
      lineinfile:
        dest: "/etc/sudoers.{{ansible_hostname}}"
        state: present
        regexp: '^ansible ALL\='
        line: 'ansible ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'
```

**Output:**

```
TASK [Add sudo permisssion and validate the file before save] ******************
fatal: [SERVER_NAME]: FAILED! => {"changed": false, "cmd": "visudo -cf /tmp/tmpBZe5ct", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```

**Version:**

```
$ ansible-playbook --version
ansible-playbook 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

**Comment by ansibot** [comment]
From @mrtg on 2016-09-29T14:30:34Z

Hi,

the error message does not say that it cannot find the temporary file. It says that it cannot find the 'visudo' command. Do you call the module with `become: true`?

**Comment by ansibot** [comment]
From @yves-vogl on 2016-09-29T14:30:34Z

You're right… the module cannot find visudo. Because it's not on the search path when calling with `become:yes`(as I did).

Maybe this could be added to the documentation as a Gotcha.

**Comment by ansibot** [comment]
From @lazize on 2016-09-29T14:30:34Z

With the full path it works fine.
Would be nice to mention it in the documentation.
If possible would be very good to have a more detail error message, like:
'visudo, No such file or directory'
'File visudo not found'

Something that explain more the problem.

**Comment by ansibot** [comment]
From @robredido on 2016-09-29T14:30:34Z

Hi,
I also have the same problem, "No such file or directory". But after adding become: true it showed another error. This time it's "failed": true, "module_stderr": "/bin/sh: sudo: command not found\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 127
I tried searching the Internet for any ideas on what this error means but to no avail.

**Comment by ansibot** [comment]
From @lazize on 2016-09-29T14:30:34Z

@robredido Are you using full path, like `/usr/sbin/visudo`?

**Comment by ansibot** [comment]
From @robredido on 2016-09-29T14:30:34Z

Um I don't think so.
My lines look like this:
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers.d/users
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
      become: true

**Comment by ansibot** [comment]
From @lazize on 2016-09-29T14:30:34Z

@robredido  That is the problem when we use `become: true`, it doesn't find `visudo`, because `PATH` is not set, so please try to use full path for `visudo`. For me it solved the problem.

**Comment by ansibot** [comment]
From @robredido on 2016-09-29T14:30:34Z

Where should I insert the path? I'm sorry, I'm literally new to ansible. I just found out about this today.

**Comment by ansibot** [comment]
From @lazize on 2016-09-29T14:30:34Z

This is my task, I masked some details, but you can get the main usage of it.
I am running on RHEL, so that is the full path for `visudo` on RHEL target.

```
- name: 'Add sudo permission and validate the file before save'
  lineinfile:
    dest: "/etc/sudoers"
    state: present
    regexp: 'XXXXXXXXXX$'
    line: 'XXXXXXXXXXXXX'
    validate: '/usr/sbin/visudo -cf %s'
```

**Comment by ansibot** [comment]
From @robredido on 2016-09-29T14:30:34Z

Thanks! But the error is still there. I may have to research more on this.

**Comment by ansibot** [comment]
From @lazize on 2016-09-29T14:30:34Z

Your error message say "`sudo: command not found\n`", so I believe `become` can't find `sudo` to do it's job. Make use the user you are using to connect on target can find `sudo`. I don't know if is possible to set full path for `sudo`!

**Comment by ansibot** [comment]
cc @ahtik @dhozac
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
This does not appear to be a bug in Ansible. The error is due to the `visudo` command not being found, not the temporary file. The full path on CentOS 7 is `/sbin/visudo`.

The `sudoers` configuration can affect how paths need to be specified. Particularly `secure_path`, which sets `PATH` inside the `sudo` environment.

My reproducer:

```yaml
- name: Test lineinfile
  hosts: lab-centos7
  become: yes
  gather_facts: yes

  tasks:
    - lineinfile:
        dest: /etc/sudoers.d/icinga2
        create: yes
        state: present
        line: 'icinga ALL=(ALL) NOPASSWD:/usr/bin/finditall'
        validate: '/usr/sbin/visudo -cf %s'
```

```
> ansible-playbook test-lineinfile.yml

PLAY [Test lineinfile] **************************************************************************************

TASK [lineinfile] *******************************************************************************************
changed: [lab-centos7]

PLAY RECAP **************************************************************************************************
lab-centos7                : ok=1    changed=1    unreachable=0    failed=0
```

If I set the `validate` field to an incorrect path the `visudo`, I get the same error as reported in the issue:

```yaml
- name: Test lineinfile
  hosts: lab-centos7
  become: yes
  gather_facts: yes

  tasks:
    - lineinfile:
        dest: /etc/sudoers.d/icinga2
        create: yes
        state: present
        line: 'icinga ALL=(ALL) NOPASSWD:/usr/bin/find'
        validate: '/bin/visudo -cf %s'
```

```
> ansible-playbook test-lineinfile.yml

PLAY [Test lineinfile] **************************************************************************************

TASK [lineinfile] *******************************************************************************************
fatal: [lab-centos7]: FAILED! => {
    "changed": false,
    "cmd": "/bin/visudo -cf /tmp/tmpdHqWcg",
    "rc": 2
}

MSG:

[Errno 2] No such file or directory


PLAY RECAP **************************************************************************************************
lab-centos7                : ok=0    changed=0    unreachable=0    failed=1
```

For further help with the issue, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
