### ISSUE TITLE
Adding Namespace as an editable parameter for the docker_login module.

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29628]
From @anton-dealmeida on 2016-09-27T12:48:29Z

##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

lib/ansible/modules/cloud/docker/docker_login.py
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I am trying to log into my organization using the docker_login module. Docker Hub and Cloud now both have Organizations which improve your ability to control who can create, edit or delete Docker Hub repositories.
##### STEPS TO REPRODUCE

```
- name: Log into DockerHub
  docker_login:
    username: docker
    password: rekcod
    email: docker@docker.io
    namespace: docker_organization
```

##### EXPECTED RESULTS

I would expect that Docker now logs into my personal account but uses the organization that I am linked to and not my own personal account for pushing images or doing any tasks Docker related on the machine I used the docker_login module. This way I can effectively work with multiple teams that have their own repositories and I can effectively deploy Docker Images that are private from different teams.
##### ACTUAL RESULTS

This isn't currently possible.

Copied from original issue: ansible/ansible-modules-core#5052
