### ISSUE TITLE
mysql_user: db host wildcard 

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29627]
From @bbaassssiiee on 2016-09-27T13:16:05Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

mysql_user:
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/bas/code/mvp/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

I want to set   host='%' in mysql_user module to be equivalent with:
grant all on _._ to 'my_user'@'%' identified by 'mypassword';

James seems to think a '*' should be used 
https://groups.google.com/forum/#!topic/ansible-project/FgZ0ReK3B-Q

Ansible inserts a user with host='*', but we need host='%' which does not work.
1396, \"Operation CREATE USER failed 
##### STEPS TO REPRODUCE
- name: install mysql
  yum: name=mysql state=present
- name: start mysql
  service: name=mysql state=started
- name: Create remote users
  mysql_user: name={{ user_name }} password={{ user_password }} host='%' state=present login_user=root login_password={{ mysql_root_password }}
##### EXPECTED RESULTS

A user exists that can connect remotely. select Host,User from user; Has a row with % in the host column (% is the SQL wildcard).
##### ACTUAL RESULTS

"msg": "(1396, \"Operation CREATE USER failed for 'my_writer'@'%'\"

Copied from original issue: ansible/ansible-modules-core#5053

**Comment by ansibot** [comment]
From @ansibot on 2016-09-27T13:16:05Z



@Jmainguy ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @nsteinmetz on 2016-09-27T13:16:05Z

Hi,

Weird as it works for me with `10.235.8.%` with this code using the same version as you for Ansible.

```
- name: Create mysql users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host|default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv|default('*.*:USAGE') }}"
    login_host: "{{ mysql_login_host|default(omit) }}"
    login_port: "{{ mysql_login_port|default(omit) }}"
    config_file: "{{ mysql_config_file|default(omit) }}"
    state: present
  with_items: "{{ mysql_users }}"
  no_log: yes
```

It inherits from `host_vars/<environment>`:

```
mysql_users:
  - name: "{{ project_user }}"
    host: "{{ rds_host }}"
    password: "{{ lookup('password', project_passwd) }}"
    priv: "{{ cwf_i15n_user }}.*:SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,INDEX,ALTER,CREATE TEMPORARY TABLES,LOCK TABLES"
```

Which inherits also from host vars (in `hosts/<environment>`):

```
[all:vars]
cwf_i15n_rds_host=10.235.8.%
```

Did not try with `%` only but maybe a yaml syntax instead of `key=value` may help ?

My 2 cents, hope it helps...

**Comment by ansibot** [comment]
From @bbaassssiiee on 2016-09-27T13:16:05Z

@Jmainguy ping, there is a bug in mysql_user: that is waiting for your response. Please take a look at it.

**Comment by ansibot** [comment]
From @Jmainguy on 2016-09-27T13:16:05Z

Can you try using latest devel, looks like it works now

```
[root@phy01 ansible]# ansible --version
ansible 2.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[root@phy01 ansible]# ansible -i hosts all -m mysql_user -a 'name=bilbobaggins host=%'                                                                                                        
centos6.soh.re | SUCCESS => {
    "changed": true, 
    "user": "bilbobaggins"
}
[root@phy01 ansible]# ansible -i hosts all -m mysql_user -a 'name=bilbobaggins host=%'
centos6.soh.re | SUCCESS => {
    "changed": false, 
    "user": "bilbobaggins"
}


mysql> select * from user where User = 'bilbobaggins';
+------+--------------+----------+-------------+-------------+-------------+-------------+-------------+-----------+-------------+---------------+--------------+-----------+------------+-----------------+------------+------------+--------------+------------+-----------------------+------------------+--------------+-----------------+------------------+------------------+----------------+---------------------+--------------------+------------------+------------+--------------+----------+------------+-------------+--------------+---------------+-------------+-----------------+----------------------+
| Host | User         | Password | Select_priv | Insert_priv | Update_priv | Delete_priv | Create_priv | Drop_priv | Reload_priv | Shutdown_priv | Process_priv | File_priv | Grant_priv | References_priv | Index_priv | Alter_priv | Show_db_priv | Super_priv | Create_tmp_table_priv | Lock_tables_priv | Execute_priv | Repl_slave_priv | Repl_client_priv | Create_view_priv | Show_view_priv | Create_routine_priv | Alter_routine_priv | Create_user_priv | Event_priv | Trigger_priv | ssl_type | ssl_cipher | x509_issuer | x509_subject | max_questions | max_updates | max_connections | max_user_connections |
+------+--------------+----------+-------------+-------------+-------------+-------------+-------------+-----------+-------------+---------------+--------------+-----------+------------+-----------------+------------+------------+--------------+------------+-----------------------+------------------+--------------+-----------------+------------------+------------------+----------------+---------------------+--------------------+------------------+------------+--------------+----------+------------+-------------+--------------+---------------+-------------+-----------------+----------------------+
| %    | bilbobaggins |          | N           | N           | N           | N           | N           | N         | N           | N             | N            | N         | N          | N               | N          | N          | N            | N          | N                     | N                | N            | N               | N                | N                | N              | N                   | N                  | N                | N          | N            |          |            |             |              |             0 |           0 |               0 |                    0 |
+------+--------------+----------+-------------+-------------+-------------+-------------+-------------+-----------+-------------+---------------+--------------+-----------+------------+-----------------+------------+------------+--------------+------------+-----------------------+------------------+--------------+-----------------+------------------+------------------+----------------+---------------------+--------------------+------------------+------------+--------------+----------+------------+-------------+--------------+---------------+-------------+-----------------+----------------------+
1 row in set (0.00 sec)
```

**Comment by ansibot** [comment]
From @Jmainguy on 2016-09-27T13:16:05Z

ansibot 'needs_info'

**Comment by ansibot** [comment]
From @ydh on 2016-09-27T13:16:05Z

ansibot 'needs_info'

**Comment by bbaassssiiee** [comment]
Creating a test repo

**Comment by bbaassssiiee** [comment]
I can confirm that this is no longer an issue for me because ansible 2.3.2.0 has the expected behaviour to enter a % wildcard in the Host column of the mysql.user table using the mysql_user module.

Since I opened the original ticket I suggest you may close it.

**Comment by bbaassssiiee** [comment]
I have a couple of default users for testing...

```
mysql_users:
  - name: test
    host: localhost
    password: test
    priv: "test.*:ALL"
  - name: remote
    host: "*"
    password: remote
    priv: "test.*:ALL"
```

my role add these with this action:

```
- name: mysql | Create users
  mysql_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv }}"
    host: "{{ item.host|default('%') }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  when: mysql_server
  no_log: yes
  with_items:
    - "{{ mysql_users }}"
```

When I run a query to test the presence of % in the host column:
```
changed: [base_mysql] => {
    "changed": true, 
    "cmd": [
        "mysql", 
        "-e", 
        "select User,Host from mysql.user;"
    ], 
    "delta": "0:00:00.059422", 
    "end": "2017-09-11 18:32:30.504552", 
    "invocation": {
        "module_args": {
            "_raw_params": "mysql -e 'select User,Host from mysql.user;'", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }
    }, 
    "rc": 0, 
    "start": "2017-09-11 18:32:30.445130", 
    "stderr": "", 
    "stderr_lines": [], 
    "stdout": "User\tHost\nremote\t*\nroot\t127.0.0.1\nroot\t1e204f46a58e\nroot\t::1\nroot\tlocalhost\ntest\tlocalhost", 
    "stdout_lines": [
        "User\tHost", 
        "remote\t*", 
        "root\t127.0.0.1", 
        "root\t1e204f46a58e", 
        "root\t::1", 
        "root\tlocalhost", 
        "test\tlocalhost"
    ]
}

```

**Comment by mivanov93** [comment]
Not fixed, ansible 2.4 still produces an error with

` mysql_user: host=% name={{ user }} password={{ password }} priv={{ database }}.*:ALL state=present`

**Comment by geerlingguy** [comment]
@mivanov93 - I can't reproduce in 2.3 or 2.4 (last tested in 2.4.2 today).

Note that maybe quoting is causing you issues—I noticed you're using the shorthand syntax.

If I quote the `'%'` and use yaml long form syntax to define the options, it seems to work fine:

```yaml
- mysql_user:
  host: '%'
  name: '{{ user }}'
  password: '{{ password }}'
  priv: '{{ database }}.*:ALL'
  state: present
```

**Comment by bbaassssiiee** [comment]
:relieved:

**Comment by cgrigor** [comment]
I'm also having an issue creating a user using host: '%' using yaml long form syntax. I've tried different variations but always seem to get the same error

Operation CREATE USER failed for 'my_random_user'@'%'

Using Versions:
```
ansible 2.5.0rc3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.14 (default, Mar 16 2018, 18:20:07) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```
Task:
```
- name: Creating mysql user
  mysql_user:
    login_user: '{{ remote_db_user }}'
    login_password: '{{ remote_db_pass }}'
    login_host: '{{ remote_db_host }}'
    name: '{{ rds_username }}'
    password: '{{ rds_password }}'
    state: present
    host: '%'
```

**Comment by insideClaw** [comment]
Using [this remote MySQL access topic](https://stackoverflow.com/questions/8348506/grant-remote-access-of-mysql-database-from-any-ip-address) as a base for figuring out what I need and the answer directly above me for the wildcarding that's not documented, I got this syntax to work for me. It ensures a user @'%' (at anywhere) exists with the correct permissions:
```
mysql_users:
  - name: "myname"
    host: "%"
    password: "mypassword"
    priv: "myspecificdatabase.*:ALL"
```
Obvious that's not the "*" syntax that this topic suggests is expected, and I'd say there's a dire need of an update to the [mysql_user Ansible module documentation](https://docs.ansible.com/ansible/latest/modules/mysql_user_module.html) to indicate one or the other.
