### ISSUE TITLE
ios_template src not idempotent

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29624]
From @AnsiNoob on 2016-09-29T04:43:40Z

##### ISSUE TYPE

- Bug Report
- Documentation Report
##### COMPONENT NAME

ios_template & ios_command
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 17c0f52c96) last updated 2016/09/28 16:38:32 (GMT +000)
  lib/ansible/modules/core: (detached HEAD 0f505378c3) last updated 2016/09/23 13:51:09 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 1ade801f65) last updated 2016/09/23 13:51:25 (GMT +000)
  config file = {path-edited}/ansible.cfg
  configured module search path = ['{path-edited}ansible/library']
```
##### CONFIGURATION

ansible.cfg has log_path set so that logs are generated .. 
##### OS / ENVIRONMENT

Running pb on RHEL 6.8 while remote host is Cisco IOS device WS-C3650-48TD.
##### SUMMARY

Ansible is supposed to be idempotent from the start and I love that about ansible. But, something is not write for ios_template and ios_command module.

Here is what I tried:
1. Downloaded template of current running config using ios_config backup option.
2. Edited the template so that it is ready to be pushed out using ios_template src option.
3. Pushed the template using ios_template src option. --> ansible said 'changed' which means change was performed on remote device.
4. Sent the command writemem using ios_command to commit changes to memory. --> ansible said 'ok' even though it did commit changes to remote device --> WHY?
5. I used the same template and re-pushed it. Technically now it should say 'ok' as no change would be performed on remote device but everytime I get same result for step 3 (changed) & 4 (ok) even though I'm reusing the same template over and over. 

This really kills the Ansible idempotent idea. If same config is being pushed over and over then only for the first time we should see changed and rest of the times we should see ok. 

I understand that writemem command makes sure that ios_command isn't idempotent as writemem will work everytime we run it but then it should also not say ok, correct?
##### STEPS TO REPRODUCE

```
- name: This task is just to take backup from remote device to local linux server. This task will religiously return changed only when something had changed in remote device and new backup was taken. This is idempotent.
  ignore_errors: yes
  ios_config:
    timeout: 30
    backup: yes
    authorize: yes
    provider: "{{ cli }}"

- name: After the above task pb does some regex on config file to replace few commands then uses this task to push that updated config to remote host. This task will always say changed even if I use the same template. This is not idempotent.
  ignore_errors: yes
  ios_template:
    timeout: 30
    src: "{{ role_path }}/files/{{ inventory_hostname }}"
    authorize: yes
    provider: "{{ cli }}"

- name: This task is just to commit all updates to memory. This task should always say changed as it always makes some change to memory (at the very least date is updated). But it always returns ok no matter what.
  ignore_errors: yes
  ios_command:
    timeout: 30
    commands:
      - write memory
    authorize: yes
    provider: "{{ cli }}"
```

##### EXPECTED RESULTS

Explained everything above.
##### ACTUAL RESULTS

```

```

Copied from original issue: ansible/ansible-modules-core#5086
