### ISSUE TITLE
`assemble` does not create parent directory

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29632]
From @glatapoui on 2016-09-26T18:44:10Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`assemble`
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### SUMMARY

If a `dest` path contains a folder that is not yet present on the target system, `assemble` will fail.
##### STEPS TO REPRODUCE

If you create an `assemble` task with a `dest` containing a path that is not created on the target system at the moment you execute the task, it will not create it and will therefore fail:

```
    - name: Set up authorized_keys 
      assemble:
        src: files/public_keys
        dest: /home/{{my.user}}/.ssh/authorized_keys
        owner: {{my.user}}
        group: {{my.user}}
        mode: 0600
```
##### ACTUAL RESULTS

The example above will fail because the folder `.ssh` was not present:

```
TASK [Set up authorized_keys] **************************
fatal: [my-host]: FAILED! => {"changed": false, "failed": true, "msg": "Could not replace file: /tmp/tmpJaCmAZ to /home/my.user/.ssh/authorized_keys: [Errno 2] No such file or directory"}
```

Copied from original issue: ansible/ansible-modules-core#5039
