### ISSUE TITLE
Enhancement request: add ability to modify instance user-data after initial launch.

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29643]
From @KpaBap on 2016-09-18T21:06:21Z

##### ISSUE TYPE
- Feature Idea
##### COMPONENT NAME

ec2.py
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel fa5f8a7543) last updated 2016/09/18 02:10:05 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 488f082761) last updated 2016/09/18 02:10:48 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 24da3602c6) last updated 2016/09/18 02:10:57 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Instance user-data cannot be set or updated except on the first launch of an instance.
##### STEPS TO REPRODUCE

This playbook has no effect on user-data whatsoever:

```
    - name: Stop nodes to set user-data
      ec2:
        region: "{{ aws_region }}"
        state: "stopped"
        wait: yes
        instance_ids: "i-12345"

    - name: Start nodes after setting user data
      ec2:
        region: "{{ aws_region }}"
        state: "running"
        user_data: "{{ user_data }}"
        wait: no
        instance_ids: "i-12345"

```

##### EXPECTED RESULTS

I expect the user-data to get updated in EC2 and the instance to start up.
##### ACTUAL RESULTS

The instance starts up but user-data remains unaffected.

Copied from original issue: ansible/ansible-modules-core#4902
