### ISSUE TITLE
vm_nic - vsphere_guest.py -  Not working on reconfigure

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29674]
From @ikkaro on 2016-09-08T10:58:45Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vsphere_guest.py
##### ANSIBLE VERSION

```
2.1.1.0
```
##### CONFIGURATION

Default configuration
##### OS / ENVIRONMENT

N/A
##### SUMMARY

vm_nic is not added on reconfigure
vm_nic is not removed on reconfigure
Just works chaning the network (portgroup)
##### STEPS TO REPRODUCE

CASE1 Add network.
I create a new VM and then I reconfigure it.

```
tasks:
  - name: "Create"
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      guest: "{{ vm_name }}"
      state: powered_off
      cluster: "{{ cluster }}"
      resource_pool: "/Resources"
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_disk:
        disk1:
          size_gb: 10
          type: thin
          datastore: 'Datastore001'
          folder: Ansible
      vm_nic:
        nic1:
          type: vmxnet3
          network: 'dpg1'
          network_type: 'dvs'
      vm_hardware:
        memory_mb: 2048
        num_cpus: 2
        osid: centos64Guest
        scsi: paravirtual
      esxi:
        datacenter: '{{ ddcc01 }}'
        hostname: '{{ host01 }}'


  - name: "Reconfigure"
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      guest: "{{ vm_name }}"
      state: reconfigured
      force: yes
      cluster: "{{ cluster }}"
      resource_pool: "/Resources"
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_nic:
        nic1:
          type: vmxnet3
          network: 'dpg1'
          network_type: 'dvs'
        nic2:
          type: vmxnet3
          network: 'dpg2'
          network_type: 'dvs'
      vm_hardware:
        memory_mb: 2048
        num_cpus: 3
        osid: centos64Guest
        scsi: paravirtual
      esxi:
        datacenter: '{{ ddcc01 }}'
        hostname: '{{ host01 }}'
```

CASE 2:

```
tasks:
  - name: "Create"
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      guest: "{{ vm_name }}"
      state: powered_off
      cluster: "{ cluster }}"
      resource_pool: "/Resources"
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_disk:
        disk1:
          size_gb: 10
          type: thin
          datastore: 'Datastore001'
          folder: Ansible
      vm_nic:
        nic1:
          type: vmxnet3
          network: 'dpg1'
          network_type: 'dvs'
      vm_hardware:
        memory_mb: 2048
        num_cpus: 2
        osid: centos64Guest
        scsi: paravirtual
      esxi:
        datacenter: '{{ ddcc01 }}'
        hostname: '{{ host01 }}'

  - name: "Reconfigure"
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      guest: "{{ vm_name }}"
      state: reconfigured
      force: yes
      cluster: "{{ cluster }}"
      resource_pool: "/Resources"
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_nic:

      vm_hardware:
        memory_mb: 2048
        num_cpus: 3
        osid: centos64Guest
        scsi: paravirtual
      esxi:
        datacenter: '{{ ddcc01 }}'
        hostname: '{{ host01 }}'
```
##### EXPECTED RESULTS

CASE 1: The VM should has two nics, but it just ends with one nic, the playbook is executed correctly. I can send you more information privately because it can contain sensible data.

CASE 2: The VM should has zero nics, but it just ends with one nic, the playbook is executed correctly. I can send you more information privately because it can contain sensible data.
##### ACTUAL RESULTS

CASE 1: The VM just ends with one nic.
CASE 2: The VM just ends with one nic.

I can provide more information privately, and I can make some test easily in order to try solve this issue. I've seen some issues and pull requests but none of them are working well.

https://github.com/ansible/ansible-modules-core/issues/218
https://github.com/ansible/ansible-modules-core/pull/1403
https://github.com/ansible/ansible-modules-core/pull/2409
https://github.com/ansible/ansible-modules-core/issues/335
https://github.com/ansible/ansible-modules-core/issues/980
https://github.com/ansible/ansible-modules-core/pull/1402
https://github.com/ansible/ansible-modules-core/issues/3056
https://github.com/ansible/ansible-modules-core/pull/1402
https://github.com/ansible/ansible-modules-core/pull/1403

Copied from original issue: ansible/ansible-modules-core#4742
