### ISSUE TITLE
vm_disk - vsphere_guest.py - thin disk type

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29673]
From @ikkaro on 2016-09-08T11:19:07Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

```
2.1.1.0
```
##### CONFIGURATION

Default configuration
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Moreover the issue https://github.com/ansible/ansible-modules-core/issues/4249 , when you create a new disk with thin type the disk is created in Thick Lazy Zeroed.
##### STEPS TO REPRODUCE

```
tasks:
  - name: "Create"
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      guest: "{{ vm_name }}"
      state: powered_off
      cluster: "{{ cluster }}"
      resource_pool: "/Resources"
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_disk:
        disk1:
          size_gb: 10
          type: thin
          datastore: 'Datastore001'
          folder: Ansible
      vm_nic:
        nic1:
          type: vmxnet3
          network: 'dpg1'
          network_type: 'dvs'
      vm_hardware:
        memory_mb: 2048
        num_cpus: 2
        osid: centos64Guest
        scsi: paravirtual
      esxi:
        datacenter: '{{ ddcc01 }}'
        hostname: '{{ host01 }}'


  - name: "Reconfigure"
    vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      guest: "{{ vm_name }}"
      state: reconfigured
      force: yes
      cluster: "{{ cluster }}"
      resource_pool: "/Resources"
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: This is a test VM
        folder: Ansible
      vm_nic:
        nic1:
          type: vmxnet3
          network: 'dpg1'
          network_type: 'dvs'
      vm_disk:
        disk1:
          size_gb: 10
          type: 'thin'
          datastore: 'Datastore001'         
        disk2:
          size_gb: 1
          type: 'thin'
          datastore: 'Datastore001'
      vm_hardware:
        memory_mb: 2048
        num_cpus: 3
        osid: centos64Guest
        scsi: paravirtual
      esxi:
        datacenter: '{{ ddcc01 }}'
        hostname: '{{ host01 }}'
```
##### EXPECTED RESULTS

The VM should end with 2 disks in thin provisioned mode.
The second disk is correctly provisioned but the thin type is ignored or change by lazy zeroed.
##### ACTUAL RESULTS

The disk is added but the disk type / format is incorrect.

```
vm_disk": {"disk1": {"datastore": "Datastore001", "size_gb": 10, "type": "thin"}, "disk2": {"datastore": "Datastore001", "size_gb": 1, "type": "thin"}}
```

I can provide more information privately, and I can make some test easily in order to try solve this issue. I've seen some issues and pull requests but none of them are working well.

Copied from original issue: ansible/ansible-modules-core#4743
