### ISSUE TITLE
Update IAM username in AWS succeed however playbook returns with an error

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29679]
From @salfand on 2016-09-05T10:35:43Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

IAM
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

CentOS Linux release 7.2.1511 (Core)
##### SUMMARY

Runs the playbook in order to rename the IAM user in AWS. The IAM user actually renamed in AWS But the playbook returns with an error.
##### STEPS TO REPRODUCE

1. Create IAM user in AWS account
2. Run the playbook in order to rename the IAM user created in Step-1.
   ansible-playbook update_iam.yml --extra-vars "AWSAccessKey=XXXXXXXX AWSSecretKey=XXXXXX old_name=David new_name=david123"

```

---
- name: Create OCCM Server
  hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
# Create boto config file
    - name: Create boto config File
      blockinfile:
        create: yes
        dest: /etc/boto.cfg
        block: |
          [Credentials]
          aws_access_key_id = {{ AWSAccessKey }}
          aws_secret_access_key = {{ AWSSecretKey }}
    - name: Update IAM USerName
      local_action:
        module: iam
        iam_type: user
        name: "{{ old_name }}"
        new_name: "{{ new_name }}"
        state: update
```

##### EXPECTED RESULTS

I expect to have success in the playbook result without any error as the IAM username indeed updated.
##### ACTUAL RESULTS

```
TASK [Update IAM USerName] *****************************************************
fatal: [127.0.0.1 -> localhost]: FAILED! => {"changed": true, "failed": true, "msg": "BotoServerError: 404 Not Found\n<ErrorResponse xmlns=\"https://iam.amazonaws.com/doc/2010-05-08/\">\n  <Error>\n    <Type>Sender</Type>\n    <Code>NoSuchEntity</Code>\n    <Message>The user with name Yaron cannot be found.</Message>\n  </Error>\n  <RequestId>ac913251-7330-11e6-a898-cf1ede838a3b</RequestId>\n</ErrorResponse>\n"}
```

Copied from original issue: ansible/ansible-modules-core#4703
