### ISSUE TITLE
django_manage - Allow additional parameters such as "--noinput"

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29687]
From @neolefty on 2016-08-31T15:19:11Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

django_manage
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### OS / ENVIRONMENT

N/A

##### SUMMARY

Running django tests, I would like to add the parameter "--noinput" which forces interactive queries to choose the default option. For example, if a test failed, it will leave the test database behind and, on the next run, offer (interactively) to delete it. With --noinput, that deletion happens automatically.
##### STEPS TO REPRODUCE

1. Run a django test that fails, but still creates a test database, using django_manage. Or run it with manage.py, for example "manage.py test --settings=test", leaving the test database present.
2. Repeat. django_manage will fail to run tests because there is already a test database. Adding "--noinput" to the manage.py call would fix it. "manage.py test --settings=test --noinput".

```
- name: Run Django unit tests
  become_user: '{{ app_user }}'
  django_manage:
    command: test
    app_path: '{{ app_dir }}'
    settings: settings_testing
    apps: core                  # space-delimited list of apps to test
```

##### ACTUAL RESULTS

```
TASK [Run Django unit tests] ***************************************************
fatal: [test1.example.com]: FAILED! => {"changed": false, "cmd": "./manage.py test --noinput --settings=settings_testing core", "failed": true, "msg": "stdout: Creating test database for alias 'default'...
Destroying old test database 'default'...\nInstalled 21 object(s) from 1 fixture(s)

:stderr: Got an error creating the test database: database \"test_example\" already exists ...
```

Copied from original issue: ansible/ansible-modules-core#4619

**Comment by ansibot** [comment]
From @ansibot on 2016-08-31T15:19:11Z



@tastychutney, @scottanderson42, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Nadeflore** [comment]
I had the same issue, but realized additional parameters can actually be added after the command:
```
- name: Run Django unit tests
  become_user: '{{ app_user }}'
  django_manage:
    command: test --noinput
    app_path: '{{ app_dir }}'
    settings: settings_testing
    apps: core
```

This is not stated in the [documentation](https://docs.ansible.com/ansible/latest/modules/django_manage_module.html)
So this may just be a side effect of the implementation, but this works (Tested with ansible 2.5.4)
