### ISSUE TITLE
unarchive fails with filename too long when downloading URL

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29680]
From @asabil on 2016-09-04T13:47:26Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

files/unarchive
##### ANSIBLE VERSION

Running Git HEAD

```
ansible 2.2.0
  config file =
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Target machine is a Debian Linux 8.0
##### SUMMARY

If the URL contains too many query parameters (the one I am using was generated using the s3 geturl task), the temporary file created ends up with a very long name.
##### STEPS TO REPRODUCE

```
  unarchive:
    src: "https://s3.eu-central-1.amazonaws.com/BUCKET/PATH/PATH/PATH/FILE.tar.xz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&X-Amz-Date=20160904T133433Z&X-Amz-Credential=AAAAAAAAAAAAAAAAAAAA%2F20160904%2Feu-central-1%2Fs3%2Faws4_request"
    dest: /srv/foobar
    copy: no
```
##### EXPECTED RESULTS

I expect it to download the file and extract it
##### ACTUAL RESULTS

```
fatal: [sensorhub.kopera.services]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading https://s3.eu-central-1.amazonaws.com/BUCKET/PATH/PATH/PATH/FILE.tar.xz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&X-Amz-Date=20160904T133433Z&X-Amz-Credential=AAAAAAAAAAAAAAAAAAAA%2F20160904%2Feu-central-1%2Fs3%2Faws4_request, [Errno 36] File name too long: '/tmp/ansible_mXzKJO/FILE.tar.xz?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Expires=600&X-Amz-SignedHeaders=host&X-Amz-Signature=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&X-Amz-Date=20160904T133433Z&X-Amz-Credential=AAAAAAAAAAAAAAAAAAAA%2F20160904%2Feu-central-1%2Fs3%2Faws4_request'"}
```

Copied from original issue: ansible/ansible-modules-core#4700
