### ISSUE TITLE
[synchronize] become_user is not honored in the generated rsync command

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29698]
From @kellytk on 2016-08-23T12:09:20Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

synchronize
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### SUMMARY

"The user and permissions for the synchronize dest are those of the remote_user on the destination host or the become_user if become=yes is active." [1] is not honored.

[1] http://docs.ansible.com/ansible/synchronize_module.html
##### STEPS TO REPRODUCE

```
- name: "Synchronize dir"
  become: yes
  become_user: targetuser
  synchronize:
    archive: no
    recursive: yes
    times: yes
    src: /local/path
    dest: /remote/path
```
##### EXPECTED RESULTS

```
/usr/bin/rsync --delay-updates -F --compress --recursive --times --rsh 'ssh -i key.pri
-S none -o StrictHostKeyChecking=no -o Port=22' --rsync-path=\"sudo -u targetuser rsync\"
--out-format='<<CHANGED>>%i %n%L' \"/local/path/\" \"sshuser@remotemachine:/remote/path/\"
```
##### ACTUAL RESULTS

The problem is the missing `-u targetuser` on sudo.

```
/usr/bin/rsync --delay-updates -F --compress --recursive --times --rsh 'ssh -i key.pri
-S none -o StrictHostKeyChecking=no -o Port=22' --rsync-path=\"sudo rsync\"
--out-format='<<CHANGED>>%i %n%L' \"/local/path/\" \"sshuser@remotemachine:/remote/path/\"
```
##### TEMPORARY WORKAROUND

Specify `rsync_path: "sudo -u targetuser rsync"` to override the generated rsync-path.

Copied from original issue: ansible/ansible-modules-core#4508
