### ISSUE TITLE
RDS read replica both requires and disallows 'subnet' parameter

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29704]
From @adisharoon on 2016-08-19T21:18:17Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

module: rds
##### ANSIBLE VERSION

```
ansible 2.1.1.0
```
##### CONFIGURATION

[defaults]
log_path=~/.ansible/ansible.log
host_key_checking = False
vault_password_file = ~/.ansible_vault
##### OS / ENVIRONMENT

OS X El Capitan 10.11.6
##### SUMMARY

Using the rds module with 'command: replicate' to create a read-replica in a VPC results in a failure stating that the 'subnet' must be specified.  However, when the parameter is provided, a failure results stating that the 'subnet' parameter is not valid.
##### STEPS TO REPRODUCE

```
- name: RDS - Replica
  hosts: localhost
  connection: local
  tasks:
    - name: Create the RDS read replica
      rds:
        command: replicate
        instance_name: "{{ rds_name }}-replica" 
        source_instance: "{{ rds_arn }}"
        publicly_accessible: no
        subnet: "{{ rds_subnet }}"
        vpc_security_groups: "{{ default_security_group_id }}"
        region: "{{ region }}"
        wait: yes
        wait_timeout: 1200
```

OR

```
- name: RDS - Replica
  hosts: localhost
  connection: local
  tasks:
    - name: Create the RDS read replica
      rds:
        command: replicate
        instance_name: "{{ rds_name }}-replica" 
        source_instance: "{{ rds_arn }}"
        publicly_accessible: no
        vpc_security_groups: "{{ default_security_group_id }}"
        region: "{{ region }}"
        wait: yes
        wait_timeout: 1200
```

##### EXPECTED RESULTS

Replica gets created
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Parameter subnet is not valid for replicate command"}
```

OR

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to create replica instance: Cannot create the DB Instance because db subnet group has not been specified which is required for a private DBInstance creation. "}
```

Copied from original issue: ansible/ansible-modules-core#4477

**Comment by ansibot** [comment]
From @ansibot on 2016-08-19T21:18:17Z



@bpennypacker, @willthames, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @nishant704 on 2016-08-19T21:18:17Z

I am also facing the same. I tried creating with just vpc_security_groups

```
- name: Create a Cross-Region read-only replica with Primary tag
  rds:
     command: replicate
     region : '{{ cross_region_name }}'
     instance_name: '{{ source_rds_instance_name }}-primary'
     source_instance: '{{ source_db_arn }}'
#     subnet: '{{ cross_region_subnet_name }}'
     publicly_accessible: no
     vpc_security_groups: '{{ cross_region_vpc_sec_grp }}'
     port: 3306
     wait: yes
     wait_timeout: 1800
```

And i got the ERROR as : 

```
TypeError: create_db_instance_read_replica() got an unexpected keyword argument 'vpc_security_group_ids'
```

P.S , i tested via 1.9.4 and unsure if i can create a Read Replica inside a VPC
