### ISSUE TITLE
timeout: Cannot access NX-OS device with nxos_command in CLI/SSH

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29707]
From @jean-christophe-manciot on 2016-08-18T13:08:35Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

nxos_command
##### ANSIBLE VERSION

```
ansible --version
ansible 2.1.1.0
```
##### CONFIGURATION

```
inventory      = ./hosts
gathering      = explicit
roles_path    = /home/actionmystique/Program-Files/Ubuntu/Ansible/git-Ansible/roles
private_role_vars = yes
log_path = /var/log/ansible.log
###latest release redis server & tools 3.2.3
fact_caching = redis 
fact_caching_timeout = 86400
retry_files_enabled = False
```
##### OS / ENVIRONMENT

**Local host**: Ubuntu 16.04 4.4.0-34
**Target node**: NX-OSv 7.3(0)D1(1)
##### SUMMARY

Cannot configure anything using nxos_command module through CLI/SSH nor NX-API.
Using show commands works fine with nxos_command.
##### STEPS TO REPRODUCE

**Inventory** ./hosts:

```
[spines]
172.21.100.11 ansible_host=NX_OSv_Spine_11 os_family=nx_osv
172.21.100.12 ansible_host=NX_OSv_Spine_12 os_family=nx_osv

[leaves]
172.21.100.13 ansible_host=NX_OSv_Leaf_13 os_family=nx_osv
172.21.100.14 ansible_host=NX_OSv_Leaf_14 os_family=nx_osv
172.21.100.15 ansible_host=NX_OSv_Leaf_15 os_family=nx_osv
172.21.100.16 ansible_host=NX_OSv_Leaf_16 os_family=nx_osv

[nx_osv:children]
spines
leaves
```

Structure passed as **provider**: connections.ssh or connections.nxapi
Defined in group_vars/nx_osv/connections.yml

```
connections:
        compute: local
        protocol: https
        target: cisco
        ssh:
          transport: cli 
          host: "{{ inventory_hostname }}"
          # ansible_port
          port: 22
          # ansible_user
          username: admin
          # ansible_ssh_pass
          password: Cisco2016$
          authorize: yes
          # enable_secret_password
          auth_pass: Cisco2016$
          # private_key_file
          ssh_keyfile: "~/.ssh/id_rsa"
          version: 2
          timeout: 10
        nxapi:
          transport: nxapi
          host: "{{ inventory_hostname }}"
          # ansible_port
          port: "{{ https.port }}"
          # ansible_user
          username: admin
          password: Cisco2016$
          authorize: yes
          # enable_secret_password
          auth_pass: Cisco2016$
          # http or https
          use_ssl: yes
          validate_certs: "{{ https.validate_certs }}"

ansible_connection: "{{ connections.compute }}" 
```

Structures **http & https**
Defined in group_vars/nx_osv/http.yml

```
http:
        # enable_http can be true / false
        service: false
        port: 8080
https:
        # enable_https can be true / false
        service: true
        port: 8181
        # If you do not need to confirm the servers identity but this is unsafe
        validate_certs: false
```

**Role**: nxos_init

```
- include_vars: "{{ role_path }}/../../group_vars/{{ os_family }}/http.yml"
- include_vars: "{{ role_path }}/../../group_vars/{{ os_family }}/connections.yml"

#------------------Buggy https://github.com/ansible/ansible-modules-core/issues/4311
#- name: Enable NX-API
#  nxos_nxapi: 

- name: Set hostname & license grace period
  nxos_command:
      provider: "{{ connections.nxapi }}"
      commands:
        - configure terminal
        - "hostname {{ ansible_host }}"
        - license grace-period
  register: return
...
```

**Playbook**: init.yml

```
- name: Initialize all NX-OS features
  hosts:
    - nx_os
    - nx_osv
  roles:
    - nxos_init
```

**Manually configure nxapi on the targets** since we cannot perform that with ansible (cf. https://github.com/ansible/ansible-modules-core/issues/4311):

```
feature nxapi
nxapi http port 8080
nxapi https port 8181
sh nxapi

NX-API:       Enabled         Sandbox:      Disabled    
HTTP Port:    8080            HTTPS Port:   8181        

Certificate Information:
    Issuer:   /C=US/ST=CA/L=San Jose/O=Cisco Systems Inc./OU=nsstg/CN=nxos     
    Expires:  Dec 19 07:53:19 2015 GMT                                         
    Content:  -----BEGIN CERTIFICATE-----
...
```

**Running** the "init.yml" playbook:

```
ansible-playbook -vvv init.yml --limit leaves
```
##### EXPECTED RESULTS

Successful nxos_command
##### ACTUAL RESULTS

```
fatal: [172.21.100.16]: FAILED! => {"changed": false, "clierror": "**Syntax error while parsing 'configure terminal**  | xml '\n\n\nCmd exec error.\n", "code": "400", "failed": true, "input": "configure terminal", "invocation": {"module_args": {"commands": ["configure terminal", "hostname NX_OSv_Leaf_16", "license grace-period"], "host": "172.21.100.16", "interval": 1, "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": 8181, "provider": {"auth_pass": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "authorize": true, "host": "172.21.100.16", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "port": "8181", "transport": "nxapi", "use_ssl": true, "username": "admin", "validate_certs": false}, "retries": 10, "ssh_keyfile": null, "timeout": 10, "transport": "nxapi", "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "url_username": "admin", "use_ssl": true, "username": "admin", "validate_certs": false, "waitfor": null}, "module_name": "nxos_command"}, "msg": "Input CLI command error"}
```

Copied from original issue: ansible/ansible-modules-core#4464

**Comment by ansibot** [comment]
From @ansibot on 2016-08-18T13:08:35Z



@privateip, @GGabriele, @gundalow, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @gundalow on 2016-08-18T13:08:35Z

We believe this is fixed, @privateip to test to confirm

**Comment by ansibot** [comment]
From @jean-christophe-manciot on 2016-08-18T13:08:35Z

@gundalow @privateip It's not fixed:

1) With ansible **2.1.2.0 RC3**
In **NX-API mode** (-v):

```
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "clierror": "Syntax error while parsing 'configure terminal  | xml '\n\n\nCmd exec error.\n", "code": "400", "failed": true, "input": "configure terminal", "msg": "Input CLI command error"}
```

In SSH mode (-vvv):

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_8p0Ind/ansible_module_nxos_command.py", line 195, in <module>
    main()
  File "/tmp/ansible_8p0Ind/ansible_module_nxos_command.py", line 160, in main
    response = module.execute(commands, **kwargs)
  File "/tmp/ansible_8p0Ind/ansible_modlib.zip/ansible/module_utils/nxos.py", line 253, in execute
  File "/tmp/ansible_8p0Ind/ansible_modlib.zip/ansible/module_utils/nxos.py", line 230, in connect
  File "/tmp/ansible_8p0Ind/ansible_modlib.zip/ansible/module_utils/nxos.py", line 182, in connect
  File "/tmp/ansible_8p0Ind/ansible_modlib.zip/ansible/module_utils/shell.py", line 108, in open
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 305, in connect
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/local/lib/python2.7/dist-packages/paramiko/util.py", line 269, in retry_on_signal
    return function()
  File "/usr/local/lib/python2.7/dist-packages/paramiko/client.py", line 305, in <lambda>
    retry_on_signal(lambda: sock.connect(addr))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.timeout: timed out
```

2) With ansible **2.2.0 commit 8af8eec** (09/15)
In **NX-API and SSH modes** (-v) :

```
fatal: [NX_OSv_Spine_11]: FAILED! => {"changed": false, "failed": true, "msg": "nxos_command does not support running config mode commands.  Please use nxos_config instead"}
```

I would not call it "fixed" when the documentation states that **any** command (not just enable commands) can be passed to **nxos_command** module. Either the fix has been **delayed**, or the **scope of the nxos_command has changed**, which adds a layer of complexity and confusion since other cisco ios_command and iosxr_command have no such restriction.

3) **nxos_config** with ansible **2.2.0 commit 8af8eec** (09/15)
With a modified call:

```
- name: Set hostname & license grace period
  nxos_config:
      provider: "{{ connections.nxapi }}"
      replace: line
      save: yes
      lines:
        - "hostname {{ inventory_hostname }}"
        - "license grace-period"
  register: return
```

I get the following error in **NX-API mode**: 

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Nxapi' object has no attribute 'authorize'
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_9gApIM/ansible_module_nxos_config.py\", line 325, in <module>\n    main()\n  File \"/tmp/ansible_9gApIM/ansible_module_nxos_config.py\", line 317, in main\n    run(module, result)\n  File \"/tmp/ansible_9gApIM/ansible_module_nxos_config.py\", line 237, in run\n    config = get_config(module)\n  File \"/tmp/ansible_9gApIM/ansible_module_nxos_config.py\", line 227, in get_config\n    contents = module.config.get_config(include_defaults=defaults)\n  File \"/tmp/ansible_9gApIM/ansible_modlib.zip/ansible/module_utils/network.py\", line 125, in config\n  File \"/tmp/ansible_9gApIM/ansible_modlib.zip/ansible/module_utils/network.py\", line 149, in connect\nAttributeError: 'Nxapi' object has no attribute 'authorize'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

A different error In **SSH mode**:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.timeout: timed out
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_DNsDkI/ansible_module_nxos_config.py\", line 325, in <module>\n    main()\n  File \"/tmp/ansible_DNsDkI/ansible_module_nxos_config.py\", line 317, in main\n    run(module, result)\n  File \"/tmp/ansible_DNsDkI/ansible_module_nxos_config.py\", line 237, in run\n    config = get_config(module)\n  File \"/tmp/ansible_DNsDkI/ansible_module_nxos_config.py\", line 227, in get_config\n    contents = module.config.get_config(include_defaults=defaults)\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/network.py\", line 125, in config\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/network.py\", line 147, in connect\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 253, in connect\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/shell.py\", line 228, in connect\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/shell.py\", line 100, in open\n  File \"/usr/local/lib/python2.7/dist-packages/paramiko/client.py\", line 305, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/local/lib/python2.7/dist-packages/paramiko/util.py\", line 269, in retry_on_signal\n    return function()\n  File \"/usr/local/lib/python2.7/dist-packages/paramiko/client.py\", line 305, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/lib/python2.7/socket.py\", line 228, in meth\n    return getattr(self._sock,name)(*args)\nsocket.timeout: timed out\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

**Comment by ansibot** [comment]
From @gundalow on 2016-08-18T13:08:35Z

@jean-christophe-manciot Thank you for retesting this and your analysis and comments around documentation.

**Comment by ansibot** [comment]
cc @mikewiebe @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
Hi, can you please retest this on 2.4.0 RC3, we believe it should be fixed.

https://groups.google.com/forum/#!topic/ansible-devel/PjBtOkwbt5I

Thanks
needs_info

**Comment by jean-christophe-manciot** [comment]
This issue has been wrongly reopened by the ansibot as shown here: https://github.com/ansible/ansible/issues/29707#ref-issue-171896622
The real one is already closed.

**Comment by gundalow** [comment]
The original issue (https://github.com/ansible/ansible-modules-core/issues/4464) was still open, 

I believe this was due to questions around documentation

I would not call it "fixed" when the documentation states that **any** command (not just enable commands) can be passed to **nxos_command** module. Either the fix has been **delayed**, or the **scope of the nxos_command has changed**, which adds a layer of complexity and confusion since other cisco ios_command and iosxr_command have no such restriction.

3) **nxos_config** with ansible **2.2.0 commit 8af8eec** (09/15)
With a modified call:

```
- name: Set hostname & license grace period
  nxos_config:
      provider: "{{ connections.nxapi }}"
      replace: line
      save: yes
      lines:
        - "hostname {{ inventory_hostname }}"
        - "license grace-period"
  register: return
```

I get the following error in **NX-API mode**: 

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'Nxapi' object has no attribute 'authorize'
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_9gApIM/ansible_module_nxos_config.py\", line 325, in <module>\n    main()\n  File \"/tmp/ansible_9gApIM/ansible_module_nxos_config.py\", line 317, in main\n    run(module, result)\n  File \"/tmp/ansible_9gApIM/ansible_module_nxos_config.py\", line 237, in run\n    config = get_config(module)\n  File \"/tmp/ansible_9gApIM/ansible_module_nxos_config.py\", line 227, in get_config\n    contents = module.config.get_config(include_defaults=defaults)\n  File \"/tmp/ansible_9gApIM/ansible_modlib.zip/ansible/module_utils/network.py\", line 125, in config\n  File \"/tmp/ansible_9gApIM/ansible_modlib.zip/ansible/module_utils/network.py\", line 149, in connect\nAttributeError: 'Nxapi' object has no attribute 'authorize'\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```

A different error In **SSH mode**:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.timeout: timed out
fatal: [NX_OSv_Spine_12]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_DNsDkI/ansible_module_nxos_config.py\", line 325, in <module>\n    main()\n  File \"/tmp/ansible_DNsDkI/ansible_module_nxos_config.py\", line 317, in main\n    run(module, result)\n  File \"/tmp/ansible_DNsDkI/ansible_module_nxos_config.py\", line 237, in run\n    config = get_config(module)\n  File \"/tmp/ansible_DNsDkI/ansible_module_nxos_config.py\", line 227, in get_config\n    contents = module.config.get_config(include_defaults=defaults)\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/network.py\", line 125, in config\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/network.py\", line 147, in connect\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/nxos.py\", line 253, in connect\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/shell.py\", line 228, in connect\n  File \"/tmp/ansible_DNsDkI/ansible_modlib.zip/ansible/module_utils/shell.py\", line 100, in open\n  File \"/usr/local/lib/python2.7/dist-packages/paramiko/client.py\", line 305, in connect\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/local/lib/python2.7/dist-packages/paramiko/util.py\", line 269, in retry_on_signal\n    return function()\n  File \"/usr/local/lib/python2.7/dist-packages/paramiko/client.py\", line 305, in <lambda>\n    retry_on_signal(lambda: sock.connect(addr))\n  File \"/usr/lib/python2.7/socket.py\", line 228, in meth\n    return getattr(self._sock,name)(*args)\nsocket.timeout: timed out\n", "module_stdout": "", "msg": "MODULE FAILURE"}
```
