### ISSUE TITLE
lineinfile incorrectly writes outer quotes in result.

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29700]
From @simonpie on 2016-08-22T19:28:14Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

- lineinfile
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/simonpie/Documents/WSO2/1.10/Ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

The basic ansible version installed by brew on a fully patch El Capitan Mac controlling an oracle linux vm.
##### SUMMARY

When trying to insert a convoluted line using the lineinfile module, outer quotes are printed in the file whilst they should not be.  I can go around the problem by using variables.
##### STEPS TO REPRODUCE

```
- name: Minimum example of failure for lineinfile module
  hosts: wso2
  vars:
    wso2Home: ~wso2/WSO2API/wso2am-1.10.0
    testString: "    -Djava.util.prefs.userRoot=\"/home/wso2/.java/.userPrefsJijJa\" \x5C"

  become: yes
  become_user: root

  tasks:

      - name: Ajout des repertoires de prefs java Not OK
        lineinfile: dest={{wso2Home}}/bin/test-wso2server.sh line="    -Djava.util.prefs.userRoot=\"/home/wso2/.java/.userPrefs\" \x5C" insertafter='^(\s*)-Djava.util.logging.config.file(.*)'

      - name: Ajout des repertoires de prefs java OK
        lineinfile: dest={{wso2Home}}/bin/test-wso2server.sh line={{testString}} insertafter='^(\s*)-Djava.util.logging.config.file(.*)'
```

Use the following file as destination

```
do
    $JAVACMD \
    -Xbootclasspath/a:"$CARBON_XBOOTCLASSPATH" \
    $JVM_MEM_OPTS \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath="$CARBON_HOME/repository/logs/heap-dump.hprof" \
    $JAVA_OPTS \
    -Djava.util.logging.config.file="$CARBON_HOME/repository/conf/etc/logging-bridge.properties" \
    -DworkerNode=false \
    org.wso2.carbon.bootstrap.Bootstrap $*
    status=$?
done
```

##### EXPECTED RESULTS

As can be seen, the lineinfile using a jinja template worked fine.  But the first insertafter  inserted quotes at the beginning and the end of my line.

```
while [ "$status" = "$START_EXIT_STATUS" ]
do
    $JAVACMD \
    -Xbootclasspath/a:"$CARBON_XBOOTCLASSPATH" \
    $JVM_MEM_OPTS \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath="$CARBON_HOME/repository/logs/heap-dump.hprof" \
    $JAVA_OPTS \
    -Djava.util.logging.config.file="$CARBON_HOME/repository/conf/etc/logging-bridge.properties" \
    -Djava.util.prefs.userRoot="/home/wso2/.java/.userPrefsJijJa" \
"    -Djava.util.prefs.userRoot="/home/wso2/.java/.userPrefs" \"
    -DworkerNode=false \
    org.wso2.carbon.bootstrap.Bootstrap $*
    status=$?
done

```
##### ACTUAL RESULTS

```

```

Copied from original issue: ansible/ansible-modules-core#4499

**Comment by ansibot** [comment]
From @ansibot on 2016-08-22T19:28:14Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @simonpie on 2016-08-22T19:28:14Z

Should I add something ?

**Comment by ansibot** [comment]
cc @ahtik @dhozac
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
I am unable to duplicate this in Ansible 2.3.3, 2.4.5, 2.5.5, or `devel`. If you are still experiencing this issue with recent versions of Ansible, please open another issue with a simple reproducer.

My reproducer:

```yaml
- name: Test lineinfile
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

    - name: Ajout des repertoires de prefs java Not OK
      lineinfile:
        dest: zzz.txt
        line: "    -Djava.util.prefs.userRoot=\"/home/wso2/.java/.userPrefs\" \x5C"
        insertafter: '^(\s*)-Djava.util.logging.config.file(.*)'
```

File before:
```
do
    $JAVACMD \
    -Xbootclasspath/a:"$CARBON_XBOOTCLASSPATH" \
    $JVM_MEM_OPTS \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath="$CARBON_HOME/repository/logs/heap-dump.hprof" \
    $JAVA_OPTS \
    -Djava.util.logging.config.file="$CARBON_HOME/repository/conf/etc/logging-bridge.properties" \
    -DworkerNode=false \
    org.wso2.carbon.bootstrap.Bootstrap $*
    status=$?
done
```

File after:
```
do
    $JAVACMD \
    -Xbootclasspath/a:"$CARBON_XBOOTCLASSPATH" \
    $JVM_MEM_OPTS \
    -XX:+HeapDumpOnOutOfMemoryError \
    -XX:HeapDumpPath="$CARBON_HOME/repository/logs/heap-dump.hprof" \
    $JAVA_OPTS \
    -Djava.util.logging.config.file="$CARBON_HOME/repository/conf/etc/logging-bridge.properties" \
    -Djava.util.prefs.userRoot="/home/wso2/.java/.userPrefs" \
    -DworkerNode=false \
    org.wso2.carbon.bootstrap.Bootstrap $*
    status=$?
done
```
