### ISSUE TITLE
ios_config `replace: block` behaves like `replace: line` when there are no parents

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29716]
From @Zanthras on 2016-08-09T18:06:24Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

networking/ios_config
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Fully default
##### OS / ENVIRONMENT

Ansible is running off a RHEL6.8 system
##### SUMMARY

IOS_config "replace: block" does not replace the block when there are no parents defined.
##### STEPS TO REPRODUCE

Existing config:
access-list 1 remark #### This line will be sent ####
access-list 1 remark ### This line wont be sent ###

```
  tasks:
  - name: Block replace failure
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      replace: block
      match: line
      lines:
        - "access-list 1 remark ### This line will be sent ###"
        - "access-list 1 remark ### This line wont be sent ###"
      before:
        - "no access-list 1"
```
##### EXPECTED RESULTS

access-list 1 remark ### This line will be sent ###
access-list 1 remark ### This line wont be sent ###
##### ACTUAL RESULTS

access-list 1 remark ### This line will be sent ###

Copied from original issue: ansible/ansible-modules-core#4368

**Comment by ansibot** [comment]
From @ansibot on 2016-08-09T18:06:24Z



@privateip, @gundalow, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @gundalow on 2016-08-09T18:06:24Z

We need to look at this a bit more to understand the issue

**Comment by ansibot** [comment]
cc @kedarX @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sdhughes1** [comment]
Is there any update on this issue? It has been stale for quite a while but really is catastrophic when using Ansible to manage access-lists in this format (with no parents)

**Comment by mcoakley** [comment]
I have this issues as well. Below is my Ansible version/config information.

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mcoakl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

I will add that in block replace mode there is also a deduplication bug. Here is an example:

```
- name: ACL 10
  ios_config:
    lines:
      - access-list 10 remark # ACL 10
      - access-list 10 remark #
      - access-list 10 remark # dns01.example.com
      - access-list 10 permit 10.1.1.1
      - access-list 10 remark #
      - access-list 10 remark # dns02.example.com
      - access-list 10 permit 10.2.1.1
    before:
      - no access-list 10
    match: exact
    replace: block
```

In my experience this will ALWAYS replace the access-list because when the access-list is determined that it needs to be replaced (the first time) it will not insert all of the lines above due to the mentioned "deduplication" bug. The following lines will be presented:

```
access-list 10 remark # ACL 10
access-list 10 remark #
access-list 10 remark # dns01.example.com
access-list 10 permit 10.1.1.1
access-list 10 remark # dns02.example.com
access-list 10 permit 10.2.1.1
```
Notice that the second "access-list remark #" is removed from the commands sent to the device.

Moving on from that issue, if I remove the two duplicate remark lines (i.e. "access-list 10 remark #") and run the playbook again it will reapply the corrected access-list. Now the device config matches the Ansible config. Running the playbook thereafter will continue to replace the access-list even though it is an exact match.

**Comment by ikhan2010** [comment]
@justjais you were working on another similar issue.  Can you take a look at this as well, please?

**Comment by justjais** [comment]
@ikhan2010 sure, shall check and update the issue.

**Comment by justjais** [comment]
I have tested the issue in latest ansible version: `2.7.5` and I am unable to reproduce the issue. I have tried with the following play:

```
- host: ios
  connection: network_cli
  tasks:
    - name: Block replace failure
      ios_config:
        provider: "{{ provider }}"
        authorize: yes
        replace: block
        match: line
        lines:
          - "access-list 1 remark ### This line will be sent ###"
          - "access-list 1 remark ### This line wont be sent ###"
        before:
          - "no access-list 1"
```

Expected result:
```
access-list 1 remark ### This line will be sent ###
access-list 1 remark ### This line wont be sent ###
```
Actual result:
```
access-list 1 remark ### This line will be sent ###
access-list 1 remark ### This line wont be sent ###

```

**Comment by sdhughes1** [comment]
@justjais can you confirm what your IOS config was before the play was run? The original issue was that If the device config already contained "access-list 1 remark ### This line wont be sent ###" it wouldn't after the play is run

**Comment by justjais** [comment]
@sdhughes1 I had checked my IOS config before firing the play and no `access-list` was configured. Also, if you check the play mentioned in my comment which's similar to issues play has `before`("no access-list 1") param set which will delete any `access-list 1` that's already configured.

Let me know if you are still facing the respective issue in ansible `2.7.5` version.

**Comment by sdhughes1** [comment]
@justjais  The problem happens when a _partial_ access-list is configured. It deletes the entire existing ACL but only puts back the parts that didn't exist before (instead of the whole block like you'd expect)

In your comment above, try running your sample play on a router which simply has the following preexisting acl. You will find that the preexisting line isn't there anymore after running your play

`access-list 1 remark ### This line wont be sent ###`

**Comment by justjais** [comment]
@sdhughes1 yes, it'll delete the respective preexisting acl(`access-list 1 remark ### This line wont be sent ###`), coz the play has `before: no access-list 1` which means before running the play it'll 1st delete the existing access list 1, and then run the config access-list command(ref: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_config.py#L63).

**Comment by jmcgill298** [comment]
I am using Ansible2.7.9 and I still see this issue
```
ios_command:
  before: ["no ntp access-group peer 10", "no access-list 10"]
  lines: ["access-list 10 permit 10.1.1.1", "access-list 10 permit 10.2.2.2"]
  after: ["ntp access-group peer 10"]
  match: "strict"
  replace: "block"
```
