### ISSUE TITLE
mysql_db dump silently fails if database does not exist

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29722]
From @leedm777 on 2016-08-04T20:57:59Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

mysql_db
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /Users/dlee/prj/bug-report/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

```
[defaults]
host_key_checking = False
gathering = smart
roles_path = ./build/galaxy
vault_password_file = $HOME/.ansible/cloud_automation_vault
inventory = ./inventory/vagrant.ini

[privilege_escalation]
become = True

[ssh_connection]
pipelining = True
# ForwardAgent=yes needed so Ansible can invoke Capistrano deploys
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
```
##### OS / ENVIRONMENT

Running Ansible from OS X 10.11.6, Python 2.7.12.
Database is MariaDB 5.5.50, installed on Ubuntu 12.04 (precise).
##### SUMMARY

When using `state: dump`, if the database to be dumped does not exist, the task does not fail.
##### STEPS TO REPRODUCE

tasks:

``` yaml
- name: drop database
  tags: bug-report
  become: False
  mysql_db:
    state: absent
    name: foobar
    login_host: '{{ mysql_login_host }}'
    login_user: '{{ mysql_root_user }}'
    login_password: '{{ mysql_root_password }}'

- name: dump database
  tags: bug-report
  become: False
  mysql_db:
    state: dump
    name: foobar
    target: /dev/null
    login_host: '{{ mysql_login_host }}'
    login_user: '{{ mysql_root_user }}'
    login_password: '{{ mysql_root_password }}'
```

```
$ ansible-playbook -v bug-report.yml
TASK [X : drop database] ************************************************
ok: [X -> 192.168.98.200] => {"changed": false, "db": "foobar"}

TASK [X : dump database] ************************************************
ok: [X -> 192.168.98.200] => {"changed": false, "db": "foobar"}
```

##### EXPECTED RESULTS

The `dump database` task should have failed.
##### ACTUAL RESULTS

The `dump database` task passes.

```
TASK [X : dump database] ************************************************
task path: /Users/dlee/prj/bug-report/roles/bug-report/tasks/main.yml:55
<192.168.98.200> ESTABLISH SSH CONNECTION FOR USER: None
<192.168.98.200> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/dlee/.ansible/cp/ansible-ssh-%h-%p-%r 192.168.98.200 '/bin/sh -c '"'"'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python && sleep 0'"'"''
ok: [X -> 192.168.98.200] => {"changed": false, "db": "foobar", "invocation": {"module_args": {"collation": "", "config_file": "/home/dlee/.my.cnf", "connect_timeout": 30, "encoding": "", "login_host": "localhost", "login_password": null, "login_port": 3306, "login_unix_socket": null, "login_user": "root", "name": "foobar", "quick": true, "single_transaction": false, "ssl_ca": null, "ssl_cert": null, "ssl_key": null, "state": "dump", "target": "/dev/null"}, "module_name": "mysql_db"}}
```

Copied from original issue: ansible/ansible-modules-core#4329
