### ISSUE TITLE
passing variables in ansible template

### ISSUE THREAD

**Issue by akthodu** [ansible/ansible#29746]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

tempalte

##### ANSIBLE VERSION

```ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov 21 2015, 00:39:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]


```

##### SUMMARY

Hi - I want to pass variable  to  template..  Tried known methods to pass variable to template.

test Playbook :
```yaml
- name: Creating template
   template:
    src:  value1.test.yml.j2
    dest: "/u01/{{ansible_hostname}}.test.yml"
    backup: yes
```    
value1.test.yml.j2
template: 
```jinja2
{% for items in {{var2}} %}
{% for thing1,thing2 in items.iteritems() %}
do
thing1: thing2
{% endfor %}
{% endfor %}
```
loading vars:
```yaml
foo:
 - site: xyz.com
    owner: test
- site: goole.com
    owner: corp
```

##### STEPS TO REPRODUCE

when I run  ansible-playbook test.yml --extra-vars "var2=foo"
gives error:
AnsibleError: template error while templating string: expected token ':', got '}'. 

If I substitute the value of var2 with foo in template  playbook runs successfully.
I tried below things ansible fails throwing same error

a,  with_items: {{foo}} and did {{item}} in playbook  it doesn't work.
b. set_fact
       -var2: foo

```yaml
- name: Creating template
   template:
    src:  value1.test.yml.j2
    dest: "/u01/{{ansible_hostname}}.test.yml"
    backup: yes
```
value1.test.yml.j2
template: 
```jinja2
{% for items in {{var2}} %}
{% for thing1,thing2 in items.iteritems() %}
do
thing1: thing2
{% endfor %}
{% endfor %}
```
loading vars:
```yaml
foo:
 - site: xyz.com
    owner: test
- site: goole.com
    owner: corp

foo2:
 - site: internal.com
    owner: test
- site: external.com
   owner: corp
```

##### EXPECTED RESULTS

Best way to pass variable to template.

If I substitute the value of var2 with foo in template  playbook runs successfully.
I tried below things ansible fails throwing same error

a,  with_items:  "{{var2}}" and did {{item}} in template
b. set_fact
       -var2: foo

##### ACTUAL RESULTS

hostname.yml should contain
```yaml
site: xyz.com
 owner: test
```

```

```
