### ISSUE TITLE
vmware_guest: Cloning from template with DHCP results in fault.NicSettingMismatch.summary

### ISSUE THREAD

**Issue by joshmullis** [ansible/ansible#29749]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
Playbook execution tried on both OSX and RHEL7.
vSphere version is: 6.0

##### SUMMARY
The "fault.NicSettingMismatch.summary" error is encountered when cloning from template with "type: dhcp" with vmware_guest module.
I've tried a template with and without a NIC and get the same result.

##### STEPS TO REPRODUCE

```yaml
  - name: Create/Modify VMs
      vmware_guest:
        state: poweredon
        hostname: "{{ vsphere_hostname }}"
        username: "{{ vsphere_username }}"
        password: "{{ vsphere_password }}"
        validate_certs: no
        datacenter: "{{ vsphere_datacenter }}"
        cluster: "{{ vsphere_cluster }}"
        resource_pool: "{{ vsphere_resource_pool }}"
        name: "{{ vm_name }}"
        template: "{{ vm_template }}"
        folder: "{{ vm_folder }}"
        wait_for_ip_address: yes


        networks:
        - name: "{{ vm_network }}"
          type: dhcp


        disk:
        - autoselect_datastore: true
          datastore: "{{ vm_datastore_filter }}"
          size_gb: 50
          type: thin

        hardware:
          memory_mb: "{{ vm_mem }}"
          num_cpus: "{{ vm_cpus }}"

        customization:
          hostname: "{{ vm_name }}"
          domain: "{{ vm_domain }}"

```

##### EXPECTED RESULTS

Successful VM clone

##### ACTUAL RESULTS

```
failed: [localhost] (item={'_ansible_parsed': True, 'changed': True, '_ansible_no_log': False, u'ansible_job_id': u'486746735116.10398', u'started': 1, '_ansible_item_result': True, 'item': u'ansible-poc-test', u'finished': 0, u'results_file': u'/Users/user1/.ansible_async/486746735116.10398'}) => {"ansible_job_id": "486746735116.10398", "attempts": 79, "changed": true, "failed": true, "finished": 1, "item": {"ansible_job_id": "486746735116.10398", "changed": true, "finished": 0, "item": "josh-ansible-poc-test3001", "results_file": "/Users/user1/.ansible_async/486746735116.10398", "started": 1}, "msg": "fault.NicSettingMismatch.summary"}
```
