### ISSUE TITLE
Module rpm_key not cleaning up after itself

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29755]
From @widyono-cets on 2016-07-11T19:27:44Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

Module rpm_key
##### ANSIBLE VERSION

```ansible 2.1.0.0 (seas_master_2.1 8223b83758) last updated 2016/06/21 14:30:15 (GMT -400)
  lib/ansible/modules/core: (detached HEAD c579014457) last updated 2016/06/21 14:30:46 (GMT -400)
  lib/ansible/modules/extras: (detached HEAD 78088078ea) last updated 2016/06/21 14:30:49 (GMT -400)
  config file = /home/widyono/ansible-widyono.cfg
  configured module search path = ['/ansible/library']

```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
OpenSuSE

##### SUMMARY
tempfiles left around on ansible target system in /tmp

##### STEPS TO REPRODUCE

```
- hosts: target.host.name
  tasks:
  - name: install RPM signing key
    rpm_key:
      state: present
      key: 'http://some/path/to/public-keys.asc'

```

##### EXPECTED RESULTS
RPM key gets installed, tempfile from fetch_key() is unlinked

##### ACTUAL RESULTS
RPM key got installed, tempfile is left around, resulting over time in a flood of files in tmp dir
```

Copied from original issue: ansible/ansible-modules-core#4159
