### ISSUE TITLE
vsphere_guest: Deploy from template receives [NoPermissionFault]

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29757]
From @gkhays on 2016-07-07T01:46:05Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

```
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"
```
##### SUMMARY

When _not_ running as administrator, a permission fault is received when attempting to deploy from template.

```
"module_name": "vsphere_guest"}, "msg": "Could not clone selected machine: [NoPermissionFault]: Permission to perform this operation was denied."
```

Assigned vSphere user the following permissions:
- `Datastore.AllocateSpace`
- `VirtualMachine.Inventory.CreateFromExisting`
- `VirtualMachine.Provisioning.CloneTemplate`

However, `Datastore.AllocateSpace` on the cluster is a violation of our policy.

I was able to abuse the extra config's and feed a datastore in using the following hack:

```
 # if a folder is specified, clone the VM into it
                 cloneArgs["folder"] = vm_extra_config.get("folder")

+            if vm_extra_config.get("datastore") is not None:
+                # if a Datastore is specified, add it to the clone spec
+                datastore_name = vm_extra_config.get("datastore")
+       mor = None
+                for ds_mor, ds_path in vsphere_client.get_datastores().items():
+                    if ds_path == datastore_name: mor = ds_mor; break
+
+                cloneArgs["datastore"] = mor
+
             vmTemplate.clone(guest, **cloneArgs)
             changed = True
         else:
```

Using this playbook snippet.

```
vm_extra_config:
        folder: "myFolder"
    datastore: "my_datastore_01"
```
##### STEPS TO REPRODUCE

`$ ansible-playbook deploy_vm_from_template.yml -vvvv`

```
  - name: Deploy VM from Template
    vsphere_guest:
      validate_certs: no
      vcenter_hostname: "{{vcenter_host}}"
      username: "{{vcenter_user}}"
      password: "{{vcenter_pass}}"
      guest: "{{vm_name}}"
      from_template: yes
      template_src: "SUSE Linux Enterprise 12 (64-bit)"
      cluster: "My-Cluster-01"    
      resource_pool: "/Resources/myResource"
      power_on_after_clone: no
      vm_extra_config:
        folder: "myFolder"
```
##### EXPECTED RESULTS

```
changed: [localhost] => {"changed": true, "invocation": {"module_args": {"cluster": "My-Cluster-01", "esxi": {}, "force": false, "from_template": true, "guest": "MyNewVM", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "power_on_after_clone": true, "resource_pool": "/Resources/myResource", "snapshot_to_clone": null, "state": "present", "template_src": "SUSE Linux Enterprise 12 (64-bit)", "username": "MYDOMAIN\\labuser", "validate_certs": false, "vcenter_hostname": "the.vmware.lab", "vm_disk": {}, "vm_extra_config": {"datastore": "my_datastore_01", "folder": "myFolder", "notes": "First.Last@company.com"}, "vm_hardware": {}, "vm_hw_version": null, "vm_nic": {}, "vmware_guest_facts": null}, "module_name": "vsphere_guest"}}
```
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"cluster": "My-Cluster-01", "esxi": {"datacenter": "Main", "hostname": "the.vmware.lab"}, "force": false, "from_template": true, "guest": "MyNewVM", "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "power_on_after_clone": true, "resource_pool": "/Resources/myResource", "snapshot_to_clone": null, "state": "present", "template_src": "SUSE Linux Enterprise 12 (64-bit)", "username": "MYDOMAIN\\labuser", "validate_certs": false, "vcenter_hostname": "the.vmware.lab", "vm_disk": {}, "vm_extra_config": {"folder": "myFolder", "notes": "First.Last@company.com"}, "vm_hardware": {}, "vm_hw_version": null, "vm_nic": {}, "vmware_guest_facts": null}, "module_name": "vsphere_guest"}, "msg": "Could not clone selected machine: [NoPermissionFault]: Permission to perform this operation was denied."}
```

Copied from original issue: ansible/ansible-modules-core#4126
