### ISSUE TITLE
`apt_repository` module cannot upgrade permission mode of related `.list` file

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29754]
From @jangsutsr on 2016-07-15T14:37:40Z

##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

`apt_repository`
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

No config changes.
##### OS / ENVIRONMENT

Running/Managing: Ubuntu 14.04
##### SUMMARY

See title.
##### STEPS TO REPRODUCE

Run the following playbook against localhost:

```
- hosts: all
  vars:
    repo_file: '/etc/apt/sources.list.d/ppa_jal233_proot_trusty.list'

  tasks:
    - name: 'Remove repo file'
      file:
        path: '{{ repo_file }}'
        state: 'absent'

    - name: 'Install apt repo with mode:0400'
      apt_repository:
        repo: 'ppa:jal233/proot'
        mode: '0400'

    - name: 'stat the repo_file'
      stat:
        path: '{{ repo_file }}'
      register: before_stat

    - name: 'Install apt repo with mode:0644 perms'
      apt_repository:
        repo: 'ppa:jal233/proot'
        mode: '0400'
      register: result

    - name: 'stat the repo_file'
      stat:
        path: '{{ repo_file }}'
      register: after_stat

    - assert:
        that:
          - "'{{ before_stat.stat.mode }}' == '0400'"
          - "'{{ after_stat.stat.mode }}' == '0644'"
          - '{{ result.changed }}'
```
##### EXPECTED RESULTS

The playbook succeeded, meaning that file mode changed.
##### ACTUAL RESULTS

```

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Remove repo file] ********************************************************
ok: [localhost]

TASK [Install apt repo with mode:0400] *****************************************
changed: [localhost]

TASK [stat the repo_file] ******************************************************
ok: [localhost]

TASK [Install apt repo with mode:0644 perms] ***********************************
ok: [localhost]

TASK [stat the repo_file] ******************************************************
ok: [localhost]

TASK [assert] ******************************************************************
fatal: [localhost]: FAILED! => {"assertion": "'0400' == '0644'", "changed": false, "evaluated_to": false, "failed": true}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @troubleshooting.retry

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=1   


```

Copied from original issue: ansible/ansible-modules-core#4194
