### ISSUE TITLE
Unexpected instance termination when try to launch new instance from aws

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29750]
From @dogukansonmez on 2016-07-19T12:26:57Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

ec2 - create, terminate, start or stop an instance in ec2
##### ANSIBLE VERSION

```
ansible 2.1.0.0
```
##### SUMMARY

When you try to launch new aws instance through ec2 module with exact_count=1 and count_tag={} it terminates all vms in connected vpc.

In ec2 module documentation it doesn't mention it might remove all instances when default state is present .

In ansible-module-core cloud/amazon/ec2.py if exact count is present it calls enforce_count function and enforce_count function does not take in consideration that exact count should be only for aws instance I want to create not total instance count in vpc. In ec2 module documentation for cout_tag parameter it says "The specified tag must already exist or be passed in as the 'instance_tags' option" but enforce_count doesn't take instance_tags values if count_tag is empty even though instance_tags has values.
##### STEPS TO REPRODUCE

```
- name: "create new instance"
  ec2:
    key_name: "{{ key_name }}"
    group: "{{ security_groups }}"
    ...
    instance_tags: "new_host"
    wait: yes
    wait_timeout: 500
    exact_count: "1"
    count_tag: "{}"
  register: ec2
```

##### EXPECTED RESULTS

Expected result will be craete new host in aws even though count_tag is empty
##### ACTUAL RESULTS

It terminated all vms in vpc

Copied from original issue: ansible/ansible-modules-core#4212
