### ISSUE TITLE
Unable to stop VM using azure_rm_virtualmachine with ssh key for RHEL VM's created in azure or using azure_rm_deployment

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29768]
From @praneethr on 2016-06-24T18:34:55Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

azure_rm_virtualmachine
##### ANSIBLE VERSION

```
ansible 2.1.0.0

```
##### CONFIGURATION

NO Default
##### OS / ENVIRONMENT

Ubuntu 14 /Linux
##### SUMMARY

Unable to stop VM using azure_rm_virtualmachine with ssh key for RHEL VM's created in azure or using azure_rm_deployment 
##### STEPS TO REPRODUCE

Create a RHEL VM with ssh key authentication, and run below playbook to stop created VM but we get error

```

---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: Power Off and On
    azure_rm_virtualmachine:
      resource_group: RG-APP
      name: "{{ vmName }}"
      started: False

```

##### EXPECTED RESULTS

VM to be stopped
##### ACTUAL RESULTS

```
cd3ans@precise64:~/ansibleplay$ ansible-playbook -vvv stopvm.yml --extra-vars "vmName=POCWEBD001"
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available


PLAYBOOK: stopvm.yml ***********************************************************
1 plays in stopvm.yml

PLAY [localhost] ***************************************************************

TASK [Power Off and On] ********************************************************
task path: /home/cd3ans/ansibleplay/stopvm.yml:6
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: cd3ans
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1466790398.4-178591174693281 `" && echo ansible-tmp-1466790398.4-178591174693281="` echo $HOME/.ansible/tmp/ansible-tmp-1466790398.4-178591174693281 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp3ysraT TO /home/cd3ans/.ansible/tmp/ansible-tmp-1466790398.4-178591174693281/azure_rm_virtualmachine
<127.0.0.1> EXEC /bin/sh -c 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/cd3ans/.ansible/tmp/ansible-tmp-1466790398.4-178591174693281/azure_rm_virtualmachine; rm -rf "/home/cd3ans/.ansible/tmp/ansible-tmp-1466790398.4-178591174693281/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"ad_user": null, "admin_password": null, "admin_username": null, "allocated": false, "append_tags": true, "client_id": null, "image": null, "location": null, "name": "POCWEBD001", "network_interface_names": null, "open_ports": null, "os_disk_caching": "ReadOnly", "os_type": "Linux", "password": null, "profile": null, "public_ip_allocation_method": "Static", "remove_on_absent": ["all"], "resource_group": "RG-APP", "restarted": false, "secret": null, "short_hostname": null, "ssh_password_enabled": true, "ssh_public_keys": null, "started": false, "state": "present", "storage_account_name": null, "storage_blob_name": null, "storage_container_name": "vhds", "subnet_name": null, "subscription_id": null, "tags": null, "tenant": null, "virtual_network_name": null, "vm_size": "Standard_D1"}, "module_name": "azure_rm_virtualmachine"}, "msg": "Error creating or updating virtual machinePOCWEBD001 - Changing property 'linuxConfiguration.ssh.publicKeys' is not allowed."}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @stopvm.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1


```

Copied from original issue: ansible/ansible-modules-core#4035

**Comment by ansibot** [comment]
From @chouseknecht on 2016-06-24T18:34:55Z

I'm not able to reproduce this running from the latest in the devel branch. Here's my playbook:

```
- name: Create VM with defaults
   azure_rm_virtualmachine:
     resource_group: "{{ resource_group }}"
     name: "{{ vmname }}"
     vm_size: Standard_D1
     admin_username: chouseknecht
     ssh_password_enabled: false
     ssh_public_keys: "{{ ssh_keys }}"
     open_ports:
       - "22-23"
     image: "{{ image }}"
     register: output

- name: Power Off
  azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vmname }}"
      started: False
```
