### ISSUE TITLE
ec2_vol does not allow adding all available volume types

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29766]
From @mvk on 2016-06-25T09:27:33Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_vol
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Linux: `CentOS 7.1`, `Ubuntu 14.04`, `Ubuntu 16.04`
arch: `x86_64`
##### SUMMARY

if you want to attach a volume of type not listed in ec2_vol.py explicitly your task fails.
##### STEPS TO REPRODUCE

The following playbook would fail

```
- name: attach new volume
  hosts: localhost
  tasks:
    module: ec2_vol
    instance: '<your instance id>'
    region: '<your region>'
    device_name: '/dev/xvdf' # or whatever
    volume_size: 40
    volume_type: 'st1'
    iops: 100
    delete_on_termination: true

```
##### EXPECTED RESULTS

I would expect the task to succeed :)
##### ACTUAL RESULTS

```
ansible-playbook -i hosts -e <custom params> playbooks/ec2node-provision.yml
TASK [myuser.ec2node : Attach local volumes (storage_type=local)] **************
task path: /home/user/workspace/ansible/ec2/playbooks/roles/myuser.ec2node/tasks/ec2_setup.yml:43
fatal: [localhost]: FAILED! => {"failed": true, "msg": "value of volume_type must be one of: standard,gp2,io1, got: st1"}
to retry, use: --limit @playbooks/ec2node-provision.retry

PLAY RECAP *********************************************************************
```

The code of `ec2_vol.py` clearly limits types in `main()`

Copied from original issue: ansible/ansible-modules-core#4041

**Comment by ansibot** [comment]
From @ansibot on 2016-06-25T09:27:33Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @mvk on 2016-06-25T09:27:33Z

Not clear what is waiting for what.

**Comment by ansibot** [comment]
From @morokin on 2016-06-25T09:27:33Z

Same issue affects Ansible 2.2

**Comment by ansibot** [comment]
From @nudomarinero on 2016-06-25T09:27:33Z

I have found the same issue in old versions of Ansible and in the latest available (2.2)

**Comment by ansibot** [comment]
cc @lwade
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by max-lobur** [comment]
crap

**Comment by max-lobur** [comment]
For ansible 2.2.0.0
```
  - name: fix ansible (https://github.com/ansible/ansible/issues/29766)
    shell: |
      bash -c "cp /usr/local/lib/python2.7/dist-packages/ansible/modules/core/cloud/amazon/ec2_vol.py{,.bak}"
      sed -i "s/\['standard', 'gp2', 'io1'\]/\['standard', 'gp2', 'io1', 'st1'\]/" /usr/local/lib/python2.7/dist-packages/ansible/modules/core/cloud/amazon/ec2_vol.py
    when: volume_type == 'st1'

  - name: create volume
    ec2_vol:
      region: "{{ ansible_ec2_placement_region }}"
      instance: "{{ ansible_ec2_instance_id }}"
      volume_size: "{{ volume_size }}"
      volume_type: "{{ volume_type }}"
      device_name: "/dev/{{ ebs_device_name }}"
      delete_on_termination: "{{ delete_on_termination }}"
```
works
