### ISSUE TITLE
Ansible 2.1.x cloud/docker incompatible with docker-py 1.1.0

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29765]
From @PikachuEXE on 2016-06-27T07:16:46Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

_docker module
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /users/pikachuexe/projects/spacious/spacious-rails/ansible.cfg
  configured module search path = ['./ansible/library']
```
##### CONFIGURATION

```
[defaults]
roles_path      = ./ansible/roles
hostfile        = ./ansible/inventories/localhost

filter_plugins  = ./ansible/filter_plugins
library         = ./ansible/library

error_on_undefined_vars = True

display_skipped_hosts = False
```
##### OS / ENVIRONMENT

"N/A"
##### SUMMARY

Ansible 2.1.x cloud/docker incompatible with docker-py 1.1.0
##### STEPS TO REPRODUCE

I try to update from Ansible 1.8.x
And worked around some issues with `2.0.x` (at least still works with some issue unfixed)

https://docs.ansible.com/ansible/docker_module.html
Declares it works with `docker-py` >= `0.3.0`

So I run my usual deploy playbook which fails at the task below

```

---

- name: pull docker image by creating a tmp container
  sudo: true
  # This is step that fails
  # No label specified
  action:
    module: docker
    image:  "{{ docker_image_name }}:{{ docker_image_tag }}"
    state:  "present"
    pull:   "missing"

    # By using name, the existing container will be stopped automatically
    name: "{{ docker_container_prefix }}.tmp.pull"

    command: "bash"

    detach: yes

    username: "{{ docker_api_username | mandatory }}"
    password: "{{ docker_api_password | mandatory }}"
    email:    "{{ docker_api_email    | mandatory }}"

  register: pull_docker_image_result
  until: pull_docker_image_result|success
  retries: 5
  delay: 3
```

##### EXPECTED RESULTS

Starts container without issue
##### ACTUAL RESULTS

Failed due to docker-py version too old (locked at `1.1.0` for ansible `1.8.x`)
And `labels` keyword is passed without checking the version

```
fatal: [app_server_02]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "docker"}, "module_stderr": "OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011\ndebug1: Reading configuration data /users/pikachuexe/.ssh/config\r\ndebug1: /users/pikachuexe/.ssh/config line 1: Applying options for *\r\ndebug1: /users/pikachuexe/.ssh/config line 17: Applying options for 119.81.*.*\r\ndebug1: Reading configuration data /etc/ssh_config\r\ndebug1: /etc/ssh_config line 20: Applying options for *\r\ndebug1: /etc/ssh_config line 102: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 87565\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 119.81.xxx.xxx closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_q5yEWt/ansible_module_docker.py\", line 1972, in <module>\r\n    main()\r\n  File \"/tmp/ansible_q5yEWt/ansible_module_docker.py\", line 1938, in main\r\n    present(manager, containers, count, name)\r\n  File \"/tmp/ansible_q5yEWt/ansible_module_docker.py\", line 1742, in present\r\n    created = manager.create_containers(delta)\r\n  File \"/tmp/ansible_q5yEWt/ansible_module_docker.py\", line 1660, in create_containers\r\n    containers = do_create(count, params)\r\n  File \"/tmp/ansible_q5yEWt/ansible_module_docker.py\", line 1653, in do_create\r\n    result = self.client.create_container(**params)\r\nTypeError: create_container() got an unexpected keyword argument 'labels'\r\n", "msg": "MODULE FAILURE", "parsed": false}
```

Copied from original issue: ansible/ansible-modules-core#4047
