### ISSUE TITLE
Compute Engine: Provide a way to specify initial boot disk type and size

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29770]
From @lihan on 2016-06-24T11:10:47Z

##### ISSUE TYPE

- Feature Idea
##### COMPONENT NAME

gce module 
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /Users/lihanli/projects/gce/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Mention any settings you have changed/added/removed in ansible.cfg
(or using the ANSIBLE_\* environment variables).
##### OS / ENVIRONMENT

OS X El Capitan
##### SUMMARY

`gce` module cannot specify boot disk size and type.

See http://docs.ansible.com/ansible/gce_module.html
The **disks** parameter
a list of persistent disks to attach to the instance; a string value gives the name of the disk; alternatively, a dictionary value can define 'name' and 'mode' ('READ_ONLY' or 'READ_WRITE'). The first entry will be the boot disk (which must be READ_WRITE).

It does not let you specify the size and the type.
##### STEPS TO REPRODUCE

```

```

Copied from original issue: ansible/ansible-modules-core#4030

**Comment by ansibot** [comment]
From @jensonb on 2016-06-24T11:10:47Z

The gce module cannot do this, but Ansible has more than just one module related to Google Cloud platform. You can use the gce_pd module to manage your persistent disks. You can create a disk with specified type and size, then use the gce module to attach it to your new instance.

[https://docs.ansible.com/ansible/gce_pd_module.html](https://docs.ansible.com/ansible/gce_pd_module.html)

all cloud modules: [https://docs.ansible.com/ansible/list_of_cloud_modules.html](https://docs.ansible.com/ansible/list_of_cloud_modules.html)

One of my playbooks has something like:

```
  tasks:
    - name: Make boot disk
      gce_pd:
          disk_type: pd-standard
          image: "{{ image }}"
          name: custom-boot-disk
          size_gb: 20
          state: present
          zone: "{{ zone }}"

    - name: Launch instance
      gce:
          disk_auto_delete: true
          disks:
            - name: custom-boot-disk
              mode: READ_WRITE
          external_ip: none
          ip_forward: false
          machine_type: "{{ machine_type }}"
          name: gce-test
          network: default
          state: active
          tags: test
          zone: "{{ zone }}"
      register: gce
```

Hope this helps!
