### ISSUE TITLE
lineinfile with regexp writes line when there isn't a match

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29776]
From @jsnshrmn on 2016-06-17T15:03:20Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

lineinfile
##### ANSIBLE VERSION

```
ansible 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

Bone stock
##### OS / ENVIRONMENT

CentOS 7
##### SUMMARY

When lineinfile  with regexp finds a match, it substitutes properly.  When it doesn't find a match (say, on subsequent runs), it just dumps the specified line at the bottom of the file as if you hadn't specified a regexp.  Needless to say, this breaks idempotence. 
##### STEPS TO REPRODUCE
1. Take a look at a file.
2. Run lineinfile with regexp that matches a line
3. See that your line was in fact replaced.
4. Run lineinfile again.
5. See that the specified replacement line is now duplicated at the bottom of the file.

```
- name: Add ops scripts to sudo secure_path
  lineinfile:
    dest: /etc/sudoers
    regexp: >
      ^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin$
    line: 'Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin'
    validate: visudo -cf %s
```
##### EXPECTED RESULTS

Idempotent line replacement after a second run

```
# Refuse to run if unable to disable echo on the tty.
Defaults   !visiblepw

#
# Preserving HOME has security implications since many programs
# use it when searching for configuration files. Note that HOME
# is already set when the the env_reset option is enabled, so
# this option is only effective for configurations where either
# env_reset is disabled or HOME is present in the env_keep list.
#
Defaults    always_set_home

Defaults    env_reset
Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS"
Defaults    env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"

#
# Adding HOME to env_keep may enable a user to run unrestricted
# commands via sudo.
#
# Defaults   env_keep += "HOME"

Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin

## Next comes the main part: which users can run what software on
## which machines (the sudoers file can be shared between multiple
## systems).
## Syntax:
##
##      user    MACHINE=COMMANDS
##
## The COMMANDS section may have other options added to it.
##
## Allow root to run any commands anywhere
root    ALL=(ALL)       ALL

## Allows people in group wheel to run all commands without a password
%wheel        ALL=(ALL)       NOPASSWD: ALL
```
##### ACTUAL RESULTS

Potentially show-stopping garbage at the bottom of a file

```
# Refuse to run if unable to disable echo on the tty.
Defaults   !visiblepw

#
# Preserving HOME has security implications since many programs
# use it when searching for configuration files. Note that HOME
# is already set when the the env_reset option is enabled, so
# this option is only effective for configurations where either
# env_reset is disabled or HOME is present in the env_keep list.
#
Defaults    always_set_home

Defaults    env_reset
Defaults    env_keep =  "COLORS DISPLAY HOSTNAME HISTSIZE INPUTRC KDEDIR LS_COLORS"
Defaults    env_keep += "MAIL PS1 PS2 QTDIR USERNAME LANG LC_ADDRESS LC_CTYPE"
Defaults    env_keep += "LC_COLLATE LC_IDENTIFICATION LC_MEASUREMENT LC_MESSAGES"
Defaults    env_keep += "LC_MONETARY LC_NAME LC_NUMERIC LC_PAPER LC_TELEPHONE"
Defaults    env_keep += "LC_TIME LC_ALL LANGUAGE LINGUAS _XKB_CHARSET XAUTHORITY"

#
# Adding HOME to env_keep may enable a user to run unrestricted
# commands via sudo.
#
# Defaults   env_keep += "HOME"

Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin

## Next comes the main part: which users can run what software on
## which machines (the sudoers file can be shared between multiple
## systems).
## Syntax:
##
##      user    MACHINE=COMMANDS
##
## The COMMANDS section may have other options added to it.
##
## Allow root to run any commands anywhere
root    ALL=(ALL)       ALL

## Allows people in group wheel to run all commands without a password
%wheel        ALL=(ALL)       NOPASSWD: ALL
Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin
```

Copied from original issue: ansible/ansible-modules-core#3975

**Comment by ansibot** [comment]
From @mconlon-academicworks on 2016-06-17T15:03:20Z

I'm also seeing this on ansible 2.0.1.0.

My current workaround is to duplicate the task with `state: absent` for the regexp and `state: present` for the line:

```
- name: Add ops scripts to sudo secure_path
  lineinfile:
    dest: /etc/sudoers
    regexp: >
      ^Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin$
    validate: visudo -cf %s
    state: absent

- name: Add ops scripts to sudo secure_path
  lineinfile:
    dest: /etc/sudoers
    line: 'Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin'
    validate: visudo -cf %s
    state: present
```

This works as expected and maintains idempotency...but yeah, this should be able to run as a single task.

**Comment by ansibot** [comment]
From @wernerflamme on 2016-06-17T15:03:20Z

The lineinfile module seems to work as expected, when you use 'backrefs: yes'. So

```
  backrefs: yes
  regexp: '^(Defaults    secure_path =) (/sbin:/bin:/usr/sbin:/usr/bin)$'
  line: '\1 /opt/d7/bin:\2'
```

might work. Crazy thing, though :-\

**Comment by ansibot** [comment]
From @perchten on 2016-06-17T15:03:20Z

Still happening in ansible 2.1.1.0.

**Comment by ansibot** [comment]
From @perchten on 2016-06-17T15:03:20Z

Looks like commit d9f8fa56d8af9de402ee9f48ea832709b20754a8 collapsed two elif statements into one condition (lines 265 and 274-275).

I think the collapse of the conditions is incorrect. The  `index[1] == -1:` check seems to me to be saying that neither `insertafter` nor `insertbefore` have been set. The change therefore reads as saying that the default _in all cases where no regexp matched_ should be EOF. But, this ignores whether the regexp was actually specified or not. If it was, EOF should not occur. If it wasn't EOF seems a sensible default. 

Therefore I _think_ it should read

```
265   elif insertafter == 'EOF' or (regexp is None and index[1] == -1):
              ...do stuff...
274   elif index[1] == -1
275       pass
```

That way you still get the EOF addition if regexp is not set, but when a regexp is defined the behaviour drops back to how it was before the change.

I tried to run a checkout in hacking mode to confirm all this and generate a proper pull request, but couldn't make changes. I suspect I was checking out the wrong commits or setting up the hacking environment wrong as I have no experience of git submodules. So, this comment is best I could do.

**Comment by ansibot** [comment]
From @wernerflamme on 2016-06-17T15:03:20Z

What kind of "response" is expected? The error still exists in ansible v2.1.1.0 on my host.

**Comment by ansibot** [comment]
From @jsnshrmn on 2016-06-17T15:03:20Z

That ping was directed at the ansible project folks. It's noting that the maintainers haven't touched this yet.

**Comment by ansibot** [comment]
cc @ahtik @dhozac
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jaddison** [comment]
Still running into this with 2.4. Seems kind of critical to fix this?

**Comment by Lewiatan** [comment]
setting backrefs: yes fixes the issue

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by divyangjp** [comment]
Happening with 2.5.1 as well. `backrefs: yes` worked but that's kinda weird!

**Comment by samdoran** [comment]
While this behavior does seem confusing, it is not a bug.

The `regexp` and `line` parameters toggle the matching logic. If `regexp` is specified, then the module looks for a match between existing lines and the `regexp`. Since it does not find a match to the regexp, it inserts the line. It does not compare the specified `line` to existing lines in the file, only to the `regexp`.

If a `regexp` **is not** specified, then the module matches `line` against existing lines.

Setting `backrefs: True` does change this behavior. From the module docs:

>This flag changes the operation of the module slightly; `insertbefore` and `insertafter` will be ignored, and if the `regexp` doesn't match anywhere in the file, the file will be left unchanged. If the `regexp` does match, the last matching line will be replaced by the expanded line parameter.

The most straightforward way to avoid this issue is to write the `regexp` so that it matches the line you wish to replace _as well as_ the inserted line:

```yaml
- name: Add ops scripts to sudo secure_path
  lineinfile:
    dest: /etc/sudoers
    regexp: '^Defaults\s+secure_path(\s+)?=(\s+)?.*$'
    line: 'Defaults    secure_path = /opt/d7/bin:/sbin:/bin:/usr/sbin:/usr/bin'
    validate: visudo -cf %s
```
