### ISSUE TITLE
rds_param_group unable to set long_query_time for MySQL

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29771]
From @jbrockett on 2016-06-23T11:45:44Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

rds_param_group
##### ANSIBLE VERSION

```
ansible 2.0.2.0
  config file = ~/ansible.cfg
  configured module search path = Default w/o overrides

boto (2.40.0)
```
##### CONFIGURATION

[defaults]
ansible_managed = Ansible Managed
display_skipped_hosts = False
forks = 50
gathering = explicit
host_key_checking = False
nocows = 1
retry_files_enabled = False
lookup_plugins = ./lookup_plugins
##### OS / ENVIRONMENT

From: Mac OSX El Capitan
To: N/A (AWS)
##### SUMMARY

I am unable to set the long_query_time rds parameter group setting using the rds_param_grroup module.  I have been able to successfully set many other variables without issue.  The only thing I see different with this parameter is that it is a float data type.  I have tried using the following values without success, "5", "5.000000", "5.0".  The value reported for this variable from MySQL is "5.000000".  From the error below, I believe this may be an issue with boto.  I found someone reporting the same issue in the Google Group back in January 2015 and it said it was an issue with boto: https://groups.google.com/forum/#!msg/ansible-project/iN7cFi2aw98/w1oc2SEFKUcJ.  No solution was posted.
##### STEPS TO REPRODUCE

Create a RDS parameter group for MySQL and try to set the long_query_time parameter.

```
rds_parameter_groups:
  nw_mysql56_default:
    description: "default rds parameter group for - mysql5.6"
    engine: mysql5.6
    immediate: yes
    name: nw-mysql56-default
    params:
      connect_timeout: 100
      general_log: 0
      innodb_flush_log_at_trx_commit: 2
      log_output: FILE
      slow_query_log: 1
      long_query_time: 5.000000
      wait_timeout: 180000
    state: present

- name: create rds parameter groups
  rds_param_group:
    description: "{{ item.value.description }}"
    engine: "{{ item.value.engine }}"
    immediate: "{{ item.value.immediate }}"
    name: "{{ item.value.name }}"
    params: "{{ item.value.params|to_json }}"
    state: "{{ item.value.state }}"
  with_dict: "{{ rds_parameter_groups }}"
```
##### EXPECTED RESULTS

The long_query_time parameter should be set to the value specified.
##### ACTUAL RESULTS

The module reports the error below:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: value must be in 0-31536000
failed: [localhost] (item={'value': {u'engine': u'mysql5.6', u'description': u'default rds parameter group for - mysql5.6', u'immediate': True, u'state': u'present', u'params': {u'general_log': 0, u'slow_query_log': 1, u'connect_timeout': 100, u'wait_timeout': 180000, u'log_output': u'FILE', u'long_query_time': u'5.000000', u'innodb_flush_log_at_trx_commit': 2}, u'name': u'nw-mysql56-default'}, 'key': u'nw_mysql56_default'}) => {"failed": true, "item": {"key": "nw_mysql56_default", "value": {"description": "default rds parameter group for - mysql5.6", "engine": "mysql5.6", "immediate": true, "name": "nw-mysql56-default", "params": {"connect_timeout": 100, "general_log": 0, "innodb_flush_log_at_trx_commit": 2, "log_output": "FILE", "long_query_time": "5.000000", "slow_query_log": 1, "wait_timeout": 180000}, "state": "present"}}, "module_stderr": "Traceback (most recent call last):\n  File \"/Users/jeremy/.ansible/tmp/ansible-tmp-1466681599.29-50297407190710/rds_param_group\", line 2506, in <module>\n    main()\n  File \"/Users/jeremy/.ansible/tmp/ansible-tmp-1466681599.29-50297407190710/rds_param_group\", line 277, in main\n    changed_params, group_params = modify_group(next_group, group_params, immediate)\n  File \"/Users/jeremy/.ansible/tmp/ansible-tmp-1466681599.29-50297407190710/rds_param_group\", line 198, in modify_group\n    set_parameter(param, new_value, immediate)\n  File \"/Users/jeremy/.ansible/tmp/ansible-tmp-1466681599.29-50297407190710/rds_param_group\", line 167, in set_parameter\n    param.value = converted_value\n  File \"/usr/local/lib/python2.7/site-packages/boto/rds/parametergroup.py\", line 169, in set_value\n    self._set_string_value(value)\n  File \"/usr/local/lib/python2.7/site-packages/boto/rds/parametergroup.py\", line 141, in _set_string_value\n    raise ValueError('value must be in %s' % self.allowed_values)\nValueError: value must be in 0-31536000\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
```

Copied from original issue: ansible/ansible-modules-core#4019
