### ISSUE TITLE
sysctl module does not allow adding new keys

### ISSUE THREAD

**Issue by jkleint** [ansible/ansible#2977]
Should `sysctl` be able to create new keys?  Even if I tell it not to check beforehand, I can't get it to.

```

---
# Test creation of new sysctl keys.
- hosts: all
  sudo: True
  gather_facts: False
  tasks:
  - sysctl: name=foo1 value=bar
    ignore_errors: yes
  - sysctl: name=foo2 value=bar checks=after
    ignore_errors: yes
  - sysctl: name=foo3 value=bar checks=none
    ignore_errors: yes
```

All three of these commands fail.  

```
PLAY [all] ******************************************************************** 

TASK: [sysctl name=foo1 value=bar] ******************************************** 
failed: [localhost] => {"failed": true}
msg: checks_before failed with: key_path is not an existing file, key seems invalid
...ignoring

TASK: [sysctl name=foo2 value=bar checks=after] ******************************* 
failed: [localhost] => {"failed": true}
msg: checks_before failed with: key_path is not an existing file, key seems invalid
...ignoring

TASK: [sysctl name=foo3 value=bar checks=none] ******************************** 
failed: [localhost] => {"failed": true}
msg: checks_before failed with: key_path is not an existing file, key seems invalid
...ignoring

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

This is on Red Hat 5 & 6 with Ansible 1.1 and 8f3b2b281f32b9896505dad5c2b5d28a6199243c.
