### ISSUE TITLE
django_manage createsuperuser does not seem idempotent

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29786]
From @westfood on 2016-06-05T18:53:40Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

django_manage
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### OS / ENVIRONMENT

OSX El Captain / 10.11.5, managing CentOS 7.1
##### SUMMARY

Issuing command createsuperuser ends up in error after second invocation.
##### STEPS TO REPRODUCE

Using this task, hard coding username/mail does not yeald in better effect

```
- name: Django add superusers
  django_manage:
    app_path: "{{ seeder_home }}/Seeder"
    virtualenv: "{{ seeder_virtualenv }}"
    command: "createsuperuser --noinput --username={{ item.name }} --email={{ item.mail }}" # Not idempotent, probably bug in django_manage module
  with_items: "{{ seeder_admins }}"
  tags: django
  ignore_errors: yes
```

##### EXPECTED RESULTS

It should not try to create user again
##### ACTUAL RESULTS

```
stderr: Traceback (most recent call last):\n  File \"/opt/virtualenv/seeder/lib/python3.4/site-packages/django/db/backends/utils.py\", line 64, in execute\n    return self.cursor.execute(sql, params)\npsycopg2.IntegrityError: duplicate key value violates unique constraint \"auth_user_username_key\"\nDETAIL:       
Key (username)=(rudolf) already exists.
```

Copied from original issue: ansible/ansible-modules-core#3871

**Comment by ansibot** [comment]
From @ansibot on 2016-06-05T18:53:40Z



@tastychutney, @scottanderson42, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @ambivalentno on 2016-06-05T18:53:40Z

as I've found this ticket while googling (and I'm working on this), here's a sample on how to create superuser in sort-of idempotent way:

```
- name: check if django superuser exists
  shell: 'echo "from django.contrib.auth.models import User; User.objects.filter(is_superuser=True).exists()" | {{project_dir}}/venv/bin/python manage.py shell'
  args:
    chdir: "{{ project_dir }}"
  register: superuser_exists


- name: create superuser if it doesnt exist
  when: superuser_exists.stdout.find("True") == -1
  django_manage:
    app_path: '{{django_app_path}}'
    settings: '{{django_settings|default(omit,true)}}'
    virtualenv: '{{django_virtualenv|default(omit,true)}}'
    command: "createsuperuser --noinput --username={{ bookiebet_admin_django_superuser_login }} --email={{ bookiebet_admin_django_superuser_email }}"
```

I have to note not all people will use default django's user model (django.contrib.auth.models.User). Therefore, sothing like settings.AUTH_USER_MODEL should be used.
Also, it's still not idempotent enough, as update of username, email and password don't process here. 

UPDATE:
found a gist which does everything I've noted: 
https://gist.github.com/elleryq/9c70e08b1b2cecc636d6
