### ISSUE TITLE
nxos_vlan returns "Command does not support JSON output"

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29784]
From @RNanney on 2016-06-06T18:32:28Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

nxos_vlan
##### ANSIBLE VERSION

```
vagrant@precise32:/vagrant$ ansible --version
ansible 2.1.0.0
  config file = /vagrant/ansible.cfg
  configured module search path = Default w/o overrides
```
##### CONFIGURATION

ansible.cfg
ask_pass      = False
gathering = explicit
roles_path    = /vagrant/roles/
##### OS / ENVIRONMENT

Running from vagrant precise32
Managing Cisco Nexus 3172 Chassis; System version: 6.0(2)U5(2)
##### SUMMARY

nxos_vlan module returns "Command does not support JSON output" however the vlans are added to the device
##### STEPS TO REPRODUCE

Example role

```
- name: Vlan configuration
  nxos_vlan:
    admin_state: "{{ item.admin_state | default(omit) }}"
    host: "{{ inventory_hostname }}"
    name: "{{ item.name | default(omit) }}"
    password: "{{ cisco.nexus.password }}"
    port: "{{ item.port | default(omit) }}"
    provider: "{{ provider | default(omit) }}"
    ssh_keyfile: "{{ ssh_keyfile | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    transport: "{{ transport | default('cli') }}"
    use_ssl: "{{ use_ssl | default(omit) }}"
    username: "{{ cisco.nexus.username }}"
    vlan_id: "{{ item.vlan_id | default(omit) }}"
    vlan_range: "{{ item.vlan_range | default(omit) }}"
    vlan_state: "{{ item.vlan_state | default(omit) }}"
  with_items: "{{ vlans }}"
```

Example group_vars:

```
vlans:
  - vlan_id: 500
    name: clbv2_vm_mgmt
    state: present
  - vlan_id: 600
    name: clbv2_vm_snet
    state: present
```

##### EXPECTED RESULTS

I expected the vlans to be added and the module to return 'changed'. Subsequent runs return 'ok'
##### ACTUAL RESULTS

```
vagrant@precise32:/vagrant$ ansible-playbook vlan_test.yml -i inventory/lab

PLAY [all] *********************************************************************

TASK [vlan : Include nxos vlan tasks] ******************************************
included: /vagrant/roles/vlan/tasks/nxos.yml for 10.127.49.31, 10.127.49.32

TASK [vlan : Vlan configuration] ***********************************************
failed: [10.127.49.32] (item={u'state': u'present', u'name': u'clbv2_vm_mgmt', u'vlan_id': 500}) => {"command": "show vlan | json", "failed": true, "item": {"name": "clbv2_vm_mgmt", "state": "present", "vlan_id": 500}, "msg": "Command does not support JSON output"}
failed: [10.127.49.31] (item={u'state': u'present', u'name': u'clbv2_vm_mgmt', u'vlan_id': 500}) => {"command": "show vlan | json", "failed": true, "item": {"name": "clbv2_vm_mgmt", "state": "present", "vlan_id": 500}, "msg": "Command does not support JSON output"}
failed: [10.127.49.32] (item={u'state': u'present', u'name': u'clbv2_vm_snet', u'vlan_id': 600}) => {"command": "show vlan | json", "failed": true, "item": {"name": "clbv2_vm_snet", "state": "present", "vlan_id": 600}, "msg": "Command does not support JSON output"}
changed: [10.127.49.31] => (item={u'state': u'present', u'name': u'clbv2_vm_snet', u'vlan_id': 600})
    to retry, use: --limit @vlan_test.retry

PLAY RECAP *********************************************************************
10.127.49.31               : ok=1    changed=0    unreachable=0    failed=1
10.127.49.32               : ok=1    changed=0    unreachable=0    failed=1

vagrant@precise32:/vagrant$ ansible-playbook vlan_test.yml -i inventory/lab

PLAY [all] *********************************************************************

TASK [vlan : Include nxos vlan tasks] ******************************************
included: /vagrant/roles/vlan/tasks/nxos.yml for 10.127.49.31, 10.127.49.32

TASK [vlan : Vlan configuration] ***********************************************
ok: [10.127.49.32] => (item={u'state': u'present', u'name': u'clbv2_vm_mgmt', u'vlan_id': 500})
ok: [10.127.49.31] => (item={u'state': u'present', u'name': u'clbv2_vm_mgmt', u'vlan_id': 500})
ok: [10.127.49.32] => (item={u'state': u'present', u'name': u'clbv2_vm_snet', u'vlan_id': 600})
ok: [10.127.49.31] => (item={u'state': u'present', u'name': u'clbv2_vm_snet', u'vlan_id': 600})

PLAY RECAP *********************************************************************
10.127.49.31               : ok=2    changed=0    unreachable=0    failed=0
10.127.49.32               : ok=2    changed=0    unreachable=0    failed=0
```

Copied from original issue: ansible/ansible-modules-core#3876
