### ISSUE TITLE
user module fails on SLES11 SP1-SP3

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29789]
From @theballdredge on 2016-05-31T23:17:25Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

user
##### ANSIBLE VERSION

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### OS / ENVIRONMENT

Source: N/A, happens on RHEL, OSX
Target: SLES11 SP1-SP3
##### SUMMARY

user module fails when user does not exist but group does.
##### STEPS TO REPRODUCE

```
- name: configure usergroup
  group:
    name: usergroup
    gid: 60003
    state: present

- name: configure user account
  user:
    name: user
    shell: /bin/bash
    skeleton: /etc/skel
    password: "{{ password }}"
    groups: usergroup
    append: true
  no_log: true
```

##### EXPECTED RESULTS

User is created and added to the indicated group
##### ACTUAL RESULTS

```
fatal: [targethost]: FAILED! => {"changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "append": true,
            "comment": null,
            "createhome": true,
            "expires": null,
            "force": false,
            "generate_ssh_key": null,
            "group": null,
            "groups": "sysadm",
            "home": null,
            "login_class": null,
            "move_home": false,
            "name": "user",
            "non_unique": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "remove": false,
            "shell": "/bin/bash",
            "skeleton": "/etc/skel",
            "ssh_key_bits": "2048",
            "ssh_key_comment": "ansible-generated on sonata",
            "ssh_key_file": null,
            "ssh_key_passphrase": null,
            "ssh_key_type": "rsa",
            "state": "present",
            "system": false,
            "uid": "60004",
            "update_password": "always",
        },
    "module_name": "user",
    },
    "msg": "/usr/sbin/useradd: invalid option -- 'N'\nTry `useradd --help' or `useradd --usage' for more information.\n",
    "name": "sysadm",
    "rc": 2
}
```

see: https://github.com/ansible/ansible-modules-core/blob/76b7de943b065a831fe8639aa0348ebceee1ae02/system/user.py#L345

looks like ansible defaults to appending -N to the useradd command when the system is not redhat, but suse11 sp1-sp3 do not support the -N flag

Copied from original issue: ansible/ansible-modules-core#3808
