### ISSUE TITLE
Docker module: argument memory_limit is of type <type 'str'> and we were unable to convert to int" on Ansible 2.0.2.0-1.el7

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29791]
From @michalzubkowicz on 2016-05-31T06:43:40Z

##### ISSUE TYPE

- Bug Report
##### COMPONENT NAME

_docker
##### ANSIBLE VERSION

```
ansible 2.0.2.0
```
##### OS / ENVIRONMENT

Centos 7
##### SUMMARY

After upgrade to ansible 2.0.2.0 it's not possible to enter memory_limit as human readable string (ie. 265MB) only bytes are accepted. 
##### STEPS TO REPRODUCE

try set memory_limit:  256MB in docker container task

```
- name: sphinx container
  docker:
        name: sphinx
        image: michalzubkowicz/docker-sphinxsearch
        state: started
        restart_policy: always
        memory_limit: 256MB
```
##### EXPECTED RESULTS

Should accept string as in earlier versions 
##### ACTUAL RESULTS

Is showing error

```
argument memory_limit is of type <type 'str'> and we were unable to convert to int
```

Copied from original issue: ansible/ansible-modules-core#3800
