### ISSUE TITLE
ec2_asg module sporadically fails to get async notification

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29801]
From @srkiNZ84 on 2016-05-09T22:40:20Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_asg
##### ANSIBLE VERSION

```
ansible 2.0.0.2
```
##### OS / ENVIRONMENT

Running from: Ubuntu Linux
Managing: Ubuntu Linux
##### SUMMARY

We (seeming randomly) get cases where we'll do a blue/green deploy using the "ec2_asg" module and have an async task waiting for the module to return a result. The task that waits for the result never gets the async notification and therefore fails despite the deploy succeeding.
##### STEPS TO REPRODUCE
- Create a new launch config (our new "blue" deploy)
- Run the "ec2_asg" task with the new launch config (with async set and "poll: 0")
- Have a task later in the playbook waiting on the result
- Confirm that the deploy succeeds in AWS (new instances brought up, old ones terminated)
- See that the "async_status" job never gets the notification that the deploy has happened

```
- name: Create integration tier launch configuration
  ec2_lc:
    name: "{{ environ }}-int-launch-config-{{ current_time }}"
    [OMITTED FOR BREVITY]
  register: int_launch_configuration

- name: Create Integration Autoscaling group
  ec2_asg:
    name: "{{ environ }}-int-asg"
    launch_config_name: "{{ environ }}-int-launch-config-{{ current_time }}"
    vpc_zone_identifier: "{{ int_subnets }}"
    health_check_type: "ELB"
    health_check_period: 400
    termination_policies: "OldestInstance"
    replace_all_instances: yes
    wait_timeout: 2400
    replace_batch_size: "{{ int_replace_batch_size }}"
  async: 1000
  poll: 0
  register: int_asg_sleeper

  - name: 'int ASG - check on fire and forget task'
    async_status: jid={{ int_asg_sleeper.ansible_job_id }}
    register: int_asg_job_result
    until: int_asg_job_result.finished
    retries: 60
    delay: 15
```
##### EXPECTED RESULTS

Expected that when the deploy succeeds and the "old" instances are terminated, the Async job gets the message and reports success.
##### ACTUAL RESULTS

It appears that the "file" mechanism which Python/Ansible use for checking on the status of background jobs fails and the file is never populated, despite the job finishing. Therefore the job polling the file times out eventually.

```
08:03:34.063 TASK [launch-config : int ASG - check on fire and forget task] *****************
08:03:34.130 fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'int_asg_job_result.finished' failed. The error was: ERROR! error while evaluating conditional (int_asg_job_result.finished): ERROR! 'dict object' has no attribute 'finished'"}
```

Copied from original issue: ansible/ansible-modules-core#3625
