### ISSUE TITLE
vsphere_guest: vm_nic should include manual MAC change feature

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29803]
From @SMINT on 2016-05-08T09:16:05Z
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

N/A
##### SUMMARY

Currently during VM reconfiguring following options are supported for vm_nic. 

```
vm_nic:
      nic1:
        type: vmxnet3
        network: VM Network
        network_type: standard
```

I think this should be extended with feature to define MAC address manually, adding  
address_type: manual
address: "00:0c:29:ac:70:96" 

Final look might be like:

```
vm_nic:
      nic1:
        type: vmxnet3
        network: VM Network
        network_type: standard
        address_type: manual
        address: "00:0c:29:ac:70:96" 
```

This functionality looks like might be supported by pysphere, but currently not implemented in Ansible.

This feature might be useful when Ansible is used to rebuild same VMs multiple times and there are static DHCP leases configured for exact MAC addresses.

Copied from original issue: ansible/ansible-modules-core#3615
