### ISSUE TITLE
vsphere_guest: adding vm_disk is failing on 2nd pass of reconfiguration task, if disk is not present in the configuration.

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29802]
From @SMINT on 2016-05-08T13:43:02Z
##### ISSUE TYPE
- Bug Report
- Minor
##### COMPONENT NAME

vsphere_guest
##### ANSIBLE VERSION

```
ansible 2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### ENVIRONMENT

Ansible host - CentOS Linux release 7.2.1511 (Core)
VMWare ESXi - 6.0.0 (Haven't tested on previous).
##### SUMMARY

If disk was successfully attached during re-configuration task and then manually removed, then during Ansible task run, task result will be marked always as failure, even disk will be added.
##### STEPS TO REPRODUCE

(1) Prerequisites, configured variables

```
vms_list:
  - esx_name: TEST
    remove_existing: True
    reconfigure: True
    recreate: True
    template_src: /slow1/images/vmware/VM_TEMPLATE/LAB2_OPERATIONS_NODE.ovf
    cluster: 192.168.10.244
    resource_pool: SLOW1
    type: thin
    nic1:
       address_type: "manual"
       mac: "00:22:33:33:44:55"
    vm_hardware:
       memory_mb: 4096
       num_cpus: 2
    disk2:
       size_gb: 20
       type: thin
       datastore: SLOW1
```

Task:

```
- name: Apply Hardware resource configuration with disks
  vsphere_guest:
    vcenter_hostname: '{{ esx_server }}'
    username: '{{ esx_user }}'
    password: '{{ esx_password }}'
    guest: '{{ item.esx_name }}'
    state: reconfigured
    vm_extra_config:
       vcpu.hotadd: '{{ item.vcpu_hotadd|default("yes") }}'
       mem.hotadd: '{{ item.mem_hotadd|default("yes") }}'
       notes: '{{ item.esx_note|default("") }}'
    vm_disk:
       disk2:
         size_gb: '{{ item.disk2.size_gb }}'
         type: '{{ item.disk2.type}}'
         datastore: '{{ item.disk2.datastore }}'
    vm_hardware:
         memory_mb: '{{ item.vm_hardware.memory_mb }}'
         num_cpus: '{{ item.vm_hardware.num_cpus }}'
  with_items: "{{ vms_list }}"
  when: item.reconfigure == True and item.disk2 is defined
  tags: [reconfigure]
```

(2) Execute command on existing VM without disk2.

`ansible-playbook site.yml --extra-vars "target=localhost role=vmware-esxi-vm-provisioning" --tags "reconfigure"
`
The task will pass:

```
TASK [vmware-esxi-vm-provisioning : Apply Hardware resource configuration with disks] ***
changed: [localhost] => (item={u'resource_pool': u'SLOW1', u'recreate': True, u'esx_name': u'TEST', u'disk2': {u'size_gb': 20, u'type': u'thin', u'datastore': u'SLOW1'}, u'nic1': {u'mac': u'00:22:33:33:44:55', u'address_type': u'manual'}, u'vm_hardware': {u'memory_mb': 4096, u'num_cpus': 2}, u'cluster': u'192.168.10.244', u'reconfigure': True, u'remove_existing': True, u'type': u'thin', u'template_src': u'/slow1/images/vmware/VM_TEMPLATE/LAB2_OPERATIONS_NODE.ovf'})

```

(3) Remove disk2 manually from VM configuration.
(4) Execute reconfiguration step again 
`ansible-playbook site.yml --extra-vars "target=localhost role=vmware-esxi-vm-provisioning" --tags "reconfigure"`

```
TASK [vmware-esxi-vm-provisioning : Apply Hardware resource configuration with disks] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: [Element trace: /SOAP-ENV:Body]
failed: [localhost] => (item={u'resource_pool': u'SLOW1', u'recreate': True, u'esx_name': u'TEST', u'disk2': {u'size_gb': 20, u'type': u'thin', u'datastore': u'SLOW1'}, u'nic1': {u'mac': u'00:22:33:33:44:55', u'address_type': u'manual'}, u'vm_hardware': {u'memory_mb': 4096, u'num_cpus': 2}, u'cluster': u'192.168.10.244', u'reconfigure': True, u'remove_existing': True, u'type': u'thin', u'template_src': u'/slow1/images/vmware/VM_TEMPLATE/LAB2_OPERATIONS_NODE.ovf'}) => {"failed": true, "item": {"cluster": "192.168.10.244", "disk2": {"datastore": "SLOW1", "size_gb": 20, "type": "thin"}, "esx_name": "TEST", "nic1": {"address_type": "manual", "mac": "00:22:33:33:44:55"}, "reconfigure": true, "recreate": true, "remove_existing": true, "resource_pool": "SLOW1", "template_src": "/slow1/images/vmware/VM_TEMPLATE/LAB2_OPERATIONS_NODE.ovf", "type": "thin", "vm_hardware": {"memory_mb": 4096, "num_cpus": 2}}, "parsed": false}
```

Task has failed, but disk was added (!)

If we re-run same task again, it will be marked as successful, as disk2 is attached to the VM.
##### EXPECTED RESULTS

Task result is detected correctly if disk was created.
##### ACTUAL RESULTS

Below same output with -vvvv enabled in failed case.

TASK [vmware-esxi-vm-provisioning : Apply Hardware resource configuration with disks] ***
task path: /root/deployment/git/Ansible/roles/vmware-esxi-vm-provisioning/tasks/main.yml:39
ESTABLISH LOCAL CONNECTION FOR USER: root
127.0.0.1 EXEC /bin/sh -c '( umask 22 && mkdir -p "`echo $HOME/.ansible/tmp/ansible-tmp-1462714406.13-129945642934184`" && echo "`echo $HOME/.ansible/tmp/ansible-tmp-1462714406.13-129945642934184`" )'
127.0.0.1 PUT /tmp/tmp7e5peU TO /root/.ansible/tmp/ansible-tmp-1462714406.13-129945642934184/vsphere_guest
127.0.0.1 EXEC /bin/sh -c 'LANG=en_US.utf-8 LC_ALL=en_US.utf-8 LC_MESSAGES=en_US.utf-8 /usr/bin/env python2 /root/.ansible/tmp/ansible-tmp-1462714406.13-129945642934184/vsphere_guest; rm -rf "/root/.ansible/tmp/ansible-tmp-1462714406.13-129945642934184/" > /dev/null 2>&1'
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1462714406.13-129945642934184/vsphere_guest", line 3819, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1462714406.13-129945642934184/vsphere_guest", line 1702, in main
    force=force
  File "/root/.ansible/tmp/ansible-tmp-1462714406.13-129945642934184/vsphere_guest", line 901, in reconfigure_vm
    ret = vsphere_client._proxy.ReconfigVM_Task(request)._returnval
  File "/usr/lib/python2.7/site-packages/pysphere/resources/VimService_services.py", line 2863, in ReconfigVM_Task
    self.binding.Send(None, None, request, soapaction="urn:vim25/5.0", *_kw)
  File "/usr/lib/python2.7/site-packages/pysphere/ZSI/client.py", line 250, in Send
    sw.serialize(obj, tc)
  File "/usr/lib/python2.7/site-packages/pysphere/ZSI/writer.py", line 141, in serialize
    elt = typecode.serialize(self.body, self, pyobj, *_kw)
  File "/usr/lib/python2.7/site-packages/pysphere/ZSI/TC.py", line 617, in serialize
    pyobj.typecode.serialize(elt, sw, pyobj, *_kw)
  File "/usr/lib/python2.7/site-packages/pysphere/ZSI/TCcompound.py", line 248, in serialize
    self.cb(elt, sw, pyobj, name=name, *_kw)
  File "/usr/lib/python2.7/site-packages/pysphere/ZSI/TCcompound.py", line 410, in cb
    sw.Backtrace(elt))
pysphere.ZSI.EvaluateException: Got None for nillable(False), minOccurs(1) element (urn:vim25,_this), <ns1:ReconfigVM_Task xmlns:SOAP-ENC="http://schemas.xmlsoap.org/soap/encoding/" xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/" xmlns:ZSI="http://www.zolera.com/schemas/ZSI/" xmlns:ns1="urn:vim25" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ns1:ReconfigVMRequestType">/ns1:ReconfigVM_Task
[Element trace: /SOAP-ENV:Body]

failed: [localhost] => (item={u'resource_pool': u'SLOW1', u'recreate': True, u'esx_name': u'TEST', u'disk2': {u'size_gb': 20, u'type': u'thin', u'datastore': u'SLOW1'}, u'nic1': {u'mac': u'00:22:33:33:44:55', u'address_type': u'manual'}, u'vm_hardware': {u'memory_mb': 4096, u'num_cpus': 2}, u'cluster': u'192.168.10.244', u'reconfigure': True, u'remove_existing': True, u'type': u'thin', u'template_src': u'/slow1/images/vmware/VM_TEMPLATE/LAB2_OPERATIONS_NODE.ovf'}) => {"failed": true, "invocation": {"module_name": "vsphere_guest"}, "item": {"cluster": "192.168.10.244", "disk2": {"datastore": "SLOW1", "size_gb": 20, "type": "thin"}, "esx_name": "TEST", "nic1": {"address_type": "manual", "mac": "00:22:33:33:44:55"}, "reconfigure": true, "recreate": true, "remove_existing": true, "resource_pool": "SLOW1", "template_src": "/slow1/images/vmware/VM_TEMPLATE/LAB2_OPERATIONS_NODE.ovf", "type": "thin", "vm_hardware": {"memory_mb": 4096, "num_cpus": 2}}, "parsed": false}

Copied from original issue: ansible/ansible-modules-core#3616
