### ISSUE TITLE
ec2_vpc_net always returns "changed" when state=present

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29804]
From @amenonsen on 2016-05-07T16:06:34Z
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME

ec2_vpc_net
##### ANSIBLE VERSION

```
ansible 2.2.0 (devel 56ba10365c) last updated 2016/05/05 17:12:03 (GMT +550)
```
##### CONFIGURATION

Default
##### OS / ENVIRONMENT

N/A
##### SUMMARY

ec2_vpc_net always sets "changed" when state=present, because the code calls update_vpc_tags() and sets changed if `tags is not None or name is not None`, regardless of whether the vpc exists or not. So if you specify name and cidr_block, the tags are always updated.

cc: @defionscode
##### STEPS TO REPRODUCE

```
- ec2_vpc_net:
    state: present
    name: ExampleVPC
    cidr_block: 192.0.2.0/24
  register: vpc
- fail: msg="I created a VPC"
  when: vpc.changed
```

Copied from original issue: ansible/ansible-modules-core#3613

**Comment by ansibot** [comment]
From @kenwmitchell on 2016-05-07T16:06:34Z

I couldn't duplicate. Running the following:

```
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - ec2_vpc_net:
       state: present
       name: demo2
       cidr_block: 10.0.0.0/16
       region: us-east-1
     register: vpc
   - fail: msg="I created a VPC"
     when: vpc.changed
```

_I added "region"_

The first time I get "changed" and the expected failure, but the next time I get "ok" and no failure.

Looking at the code, even though `update_vpc_tags()` is called when _name_ is specified, _changed_ isn't set unless `update_vpc_tags()` returns "True", which it does not in my case since there are no tags returned from ec2 nor in the task.
- [Setting "changed = True"](https://github.com/ansible/ansible-modules-core/blob/298fd0ae56713e851fda06da13c5662f6be549dc/cloud/amazon/ec2_vpc_net.py#L246-249)
- [Returning True or False](https://github.com/ansible/ansible-modules-core/blob/298fd0ae56713e851fda06da13c5662f6be549dc/cloud/amazon/ec2_vpc_net.py#L147-152)
