### ISSUE TITLE
Docker pull: always and state: reloaded redeploys named containers every time

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29851]
From @MrMMorris on 2016-03-12T00:20:21Z
##### Issue Type:
- Bug Report
##### Component Name:

Docker
##### Ansible Version:

Doesn't work in 1.9.1 to 2.0.0.2
##### Ansible Configuration:

```
[defaults]
host_key_checking=False
display_skipped_hosts=False
force_handlers = True
hostfile = inventory/ec2.py
retry_files_enabled = False

[ssh_connection]
pipelining=True
```
##### Environment:

Ubuntu 14.04 from OSX 10.10
##### Summary:

I'm not sure if it ever worked, or if I just imagined it worked, but according to the documentation: 

`"reloaded" (added in Ansible 1.9) asserts that all matching containers are running and restarts any that have any images or configuration out of date.`

This does not seem to be the case, as named containers that have nothing changed, will be reloaded every time.

I'm almost positive this was properly working at some point so if someone could try it out to see if maybe it's just something with my setup, that would be great :smile: 
##### Steps To Reproduce:

``` yaml
- name: create redis container
  docker:
    name: redis-test
    image: "redis:3.0.3"
    pull: always
    state: reloaded
```
##### Expected Results:

When a container already exists and it has all the same settings except the dynamically assigned name is different, nothing should happen:

**First run:**

```
GATHERING FACTS ***************************************************************
ok: [x.x.x.x]

TASK: [docker | create named redis container] *********************
changed: [x.x.x.x]
```

**Second run:**

```
GATHERING FACTS ***************************************************************
ok: [x.x.x.x]

TASK: [docker | create named redis container] *********************
ok: [x.x.x.x]
```
##### Actual Results:

It will create a new, separate container every time:

**First run:**

```
GATHERING FACTS ***************************************************************
ok: [x.x.x.x]

TASK: [docker | create redis container] *********************
changed: [x.x.x.x]
```

**Second run:**

```
GATHERING FACTS ***************************************************************
ok: [x.x.x.x]

TASK: [docker | create redis container] *********************
changed: [x.x.x.x]
```

**Debug output (v1.9.1):**

``` yaml
changed: [54.209.183.233] => 
{
    "ansible_facts": {
        "docker_containers": [{
            "Id": "ac0311feb2ab0f24de62003197bfe327ee3a46bee416107ccf6df28561b4a50e",
            "Warnings": null
        }]
    },
    "changed": true,
    "containers": [{
        "Id": "ac0311feb2ab0f24de62003197bfe327ee3a46bee416107ccf6df28561b4a50e",
        "Warnings": null
    }],
    "msg": "started 1 container, created 1 container.",
    "reload_reasons": null, <<<---- HUH? if there are no reasons to reload, then why does it happen?
    "summary": {
        "created": 1,
        "killed": 0,
        "pulled": 0,
        "removed": 0,
        "restarted": 0,
        "started": 1,
        "stopped": 0
    }
}
```

**Debug output (v2.0.0.2):**

`"reload_reasons": "net (default => bridge)"` Weird... looking into it

This seems to be very similar to https://github.com/ansible/ansible-modules-core/issues/3219, but it is NOT fixed by removing the relevant commit for that issue

Copied from original issue: ansible/ansible-modules-core#3231
