### ISSUE TITLE
Feature Idea: Clone VM to Template

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29852]
From @vikas027 on 2016-03-11T04:33:54Z
##### Issue Type
- Feature Idea

##### Component Name

vmware_guest

##### Ansible Version
N/A

##### Summary

It would be great if we can get an option to clone an existing VM to template.
![2016-03-11_15-32-10](https://cloud.githubusercontent.com/assets/6998650/13693342/6dd05536-e79e-11e5-840d-5a9843f0e147.png)

Copied from original issue: ansible/ansible-modules-core#3227

**Comment by ansibot** [comment]
From @defionscode on 2016-03-11T04:33:54Z

I think this is satisifed by https://github.com/ansible/ansible-modules-extras/pull/1837

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
This feature is already available.

In order to clone existing VM into a template use playbook similar to - 

```yaml
---
- name: Sample Playbook to clone existing VM into Template
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - set_fact:
        template_name: "TEMPLATE_VM_{{ 1000 | random }}"
    - name: Clone VM to Template
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: DC0
        state: present
        folder: /DC0/vm
        guest_id: centos64Guest
        name: "{{ template_name }}"
        template: EXISTING_VM_SAMPLE_0001
        is_template: True
     register: clone_to_template_result
```
