### ISSUE TITLE
GCE module missing local SSD option

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29869]
From @vincentwoo on 2016-02-29T22:03:21Z
##### Issue Type:

Bug Report
##### Component Name:

gce
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /Users/vwoo/.ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

```
[defaults]
host_key_checking = False
```
##### Environment:

N/A
##### Summary:

Google Compute Engine has supported [local SSD scratch disks](https://cloud.google.com/compute/docs/disks/local-ssd) for a while. These are very useful, high-performance ephemeral disks you can attach to instances _only at create time_. 

Libcloud [supports creating instances with local SSDs](https://github.com/apache/libcloud/blob/trunk/demos/gce_demo.py#L331) already:  (courtesy @erjohnso).

However, the official [ansible gce module](http://docs.ansible.com/ansible/gce_module.html) does not provide a way to attach these local disks.
##### Steps To Reproduce:

Ideally, we would like to be able to say something like:

```
gce:yml
  instance_names: example
  local_ssd:
    - interface: nvme
    - interface: nvme
```

which would create an instance with two local SSDs using the NVMe interface.

Copied from original issue: ansible/ansible-modules-core#3150

**Comment by ansibot** [comment]
From @erjohnso on 2016-02-29T22:03:21Z

Agreed @vincentwoo, would be a great feature to get into the GCE module!

**Comment by ansibot** [comment]
From @erjohnso on 2016-02-29T22:03:21Z

/cc @supertom

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @rambleraptor
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by vincentwoo** [comment]
Somewhat amusing to see ansibot @ itself. Can't update the description myself, but hopefully someone sees this!

**Comment by rambleraptor** [comment]
Hello! We're encouraging users to use the `gcp_compute_instance` module, which has support for local SSDs.

close_me

**Comment by refi64** [comment]
@rambleraptor Apologies for the ping, but could you mention how you would use a local disk with gcp_compute_instance, just for the sake of any who may come across this in the future (including me :sweat_smile:)?

**Comment by rambleraptor** [comment]
^ yeah that! Let me know if there's anything else I can do!

**Comment by lukmanulhakimd** [comment]
Hi @refi64 @rambleraptor I still couldn't find out how. Heres my configuration:
```
       disks:
        - auto_delete: "yes"
          boot: "yes"
          initialize_params:
            disk_name: "{{ vm_name }}-{{ item }}-bdisk"
            disk_size_gb: "10"
            disk_type: "pd-ssd"
            source_image: "projects/debian-cloud/global/images/debian-9-stretch-v20190618"
        - interface: "NVME"
           type: "SCRATCH"
```

> @rambleraptor Apologies for the ping, but could you mention how you would use a local disk with gcp_compute_instance, just for the sake of any who may come across this in the future (including me 😅)?
> 
> **EDIT:** Alas the rubber duck philosophy is true, just realized it's `type: SCRATCH`.
