### ISSUE TITLE
ansible-modules-core/cloud/amazon/ec2_vpc.py tag issue - feature request

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29860]
From @naslanidis on 2016-03-07T01:20:17Z
##### Issue Type:
- Feature Idea
##### Component Name:
- ec2_vpc.py 
##### Ansible Version:

ansible 2.0.0.2
  config file = /home/naslanidis/code/ag-vpc-management/ansible.cfg
  configured module search path = /usr/share/ansible/modules
##### Ansible Configuration:

N/A
##### Environment:

Fedora 22 x64
##### Summary:

When creating VPC's using this module, if any tag is changed or added a completely new VPC is created rather than the tags being added or updated. Looking at the documentation, all tags are used along with the cidr range to uniquely identify an existing VPC. In my opinion this should just be a NAME tag and other tags should be able to be added, changed and removed for an existing VPC
##### Steps To Reproduce:
1. Create a VPC using this module with a number of tags in place
2. Add a new tag (e.g. cost code), and rerun the script
3. A new duplicate VPC is created rather than adding the cost code tag to the existing VPC

```
 - name: test out vpc module 1st run though
    ec2_vpc:
      state: present
      region: ap-southeast-2
      profile: non_prod
      cidr_block: 10.33.0.0/16
      resource_tags:
        Name: AAG-VPC-33
        Owner: ABC
    register: created_vpc
```

```
 - name: test out vpc module 2nd run though
    ec2_vpc:
      state: present
      region: ap-southeast-2
      profile: non_prod
      cidr_block: 10.33.0.0/16
      resource_tags:
        Name: AAG-VPC-33
        Owner: ABC
        Cost_code: 3
    register: created_vpc
```
##### Expected Results:

The existing VPC should be updated with the new Cost_code tag. 
##### Actual Results:

A new VPC is created that duplicates the first VPC.

Copied from original issue: ansible/ansible-modules-core#3194
