### ISSUE TITLE
mount is not idempotent for bind mount (Ubuntu 14.04, ansible 2.0.1.0)

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29870]
From @jberkenbilt on 2016-02-29T21:48:18Z
##### Issue Type:
- Bug Report
##### Plugin Name:

mount
##### Ansible Version:

```
ansible 2.0.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

no changes from default
##### Environment:

Ubuntu 14.04 control host and target host, but see below for exact steps to reproduce
##### Summary:

Using the mount module to set up and mount a bind mount is not idempotent.
##### Steps To Reproduce:

The following playbook illustrates the problem:

```

---
- hosts: all
  tasks:
  - file: path=/tmp/1 state=directory
  - file: path=/tmp/2 state=directory
  - mount: src=/tmp/1 name=/tmp/2 fstype=- opts=bind state=mounted
```

Here's a detailed recipe for reproducing this if you run into trouble.
- Launch an instance in ec2 off the latest ubuntu trusty AMI. A t2.nano is sufficient
- On the AMI:

```
sudo -s
apt-get -y install software-properties-common
apt-add-repository -y ppa:ansible/ansible
apt-get update
apt-get -y install ansible
cd /tmp
cat >a.yml <<EOF

---
- hosts: all
  tasks:
  - file: path=/tmp/1 state=directory
  - file: path=/tmp/2 state=directory
  - mount: src=/tmp/1 name=/tmp/2 fstype=- opts=bind state=mounted
EOF
cat >local <<EOF
[local]
127.0.0.1 ansible_connection=local
EOF
ansible-playbook -i local a.yml
ansible-playbook -i local a.yml
```
##### Expected Results:

The second time, nothing should have changed since /tmp/1 is already mounted on /tmp/2
##### Actual Results:

The directory was mounted again. The line:

```
/tmp/1 on /tmp/2 type none (rw,bind)
```

appears twice in the output of `mount`.

Copied from original issue: ansible/ansible-modules-core#3148

**Comment by ansibot** [comment]
From @ansibot on 2016-02-29T21:48:18Z



@grossws ping, this issue is waiting for your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
@jberkenbilt This should be fixed in the latest Ansible version. Please could you verify?

**Comment by tace** [comment]
Hit his in RedHat and ansible 2.3.2.0

**Comment by jtyr** [comment]
@tace Thanks for reporting this. To better understand what's going on, I would like to ask you to provide me with some more information:

1) Unmount all bind mounts and then store the content of `/proc/self/mountinfo` into a file.
2) Run Ansible to mount the bind mount and then store the content of `/proc/self/mountinfo` into an another file.
3) Run Ansible again and then store the content of `/proc/self/mountinfo` into yet another file.

Then please share these three files with me here somehow.

**Comment by tace** [comment]
@jtyr Here's the files content https://pastebin.com/kMKAisBY

**Comment by tace** [comment]
is this fixed in 2.4?

**Comment by manelclos** [comment]
Hit this in 2.3.2.0, upgraded to 2.4.30, still happening, always shows changed and keeps adding mounts :(

```
- name: Bind folder to user
  mount:
    path: "/home/user/user"
    src: "/data/vhosts/xxx/html"
    opts: bind
    fstype: none
    state: mounted
```

**Comment by manelclos** [comment]
removed all bind mounts and now it works as expected!!

**Comment by martinwilkerson-scisys** [comment]
I am not seeing this issue in 2.5.0, has it been fixed or is my test case wrong? I have the following task:

```yaml
- name: Bind mount folder
  mount:
    fstype: none
    opts: bind
    path: /home/ubuntu/somedir
    src: /mnt/somepartition/someotherdir
    state: mounted
```

Running a second (and beyond) time, the task reports unchanged and there is only one entry in the output of `mount`.
