### ISSUE TITLE
ec2_vpc remove doesn't work as documented

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29875]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

ec2_vpc module

##### ANSIBLE VERSION

ansible 2.0.0.2

##### SUMMARY

Error in documentation: http://docs.ansible.com/ansible/ec2_vpc_module.html#examples

##### STEPS TO REPRODUCE

Documentation states:

```
# Removal of a VPC by id
      ec2_vpc:
        state: absent
        vpc_id: vpc-aaaaaaa
        region: us-west-2
```

However, when run, there is an error:

```
TASK [delete vpc] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "missing required arguments: resource_tags"}
```

So it isn't possible to remove a vpc just by stating its id. 

Copied from original issue: ansible/ansible-modules-core#3126
