### ISSUE TITLE
elasticache module not idempotent: Fails if cluster already exists

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29876]
From @njsaunders on 2016-02-25T15:52:19Z
##### Issue Type:
- Bug Report
##### Component Name:

elasticache
##### Ansible Version:

```
ansible 2.1.0
  config file =
  configured module search path = Default w/o overrides
```
##### Ansible Configuration:

Default
##### Environment:

N/A
##### Summary:

The elasticache module correctly creates an elasticache cluster, but running the same playbook again fails it if the cluster already exists.
##### Steps To Reproduce:

```
    - name: Create Elasticache node
      elasticache:
        name: "my-cluster"
        state: present
        engine: memcached
        node_type: cache.t2.small
        num_nodes: 1
        cache_port: 11112
        wait: no
        hard_modify: no
        region: "us-west-2"
        cache_subnet_group: "my-subnet-group"
        security_group_ids: ["sg-1234567"]
```
##### Expected Results:

Running the above repeatedly should succeed with the first execution creating the cluster and subsequent executions seeing that it exists and moving on
##### Actual Results:

Running the above twice fails with the error:

```
TASK [Create Elasticache node] *************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "Cache cluster already exists"}
```

Copied from original issue: ansible/ansible-modules-core#3119
