### ISSUE TITLE
copy module never copies when force is set to no, even if dest file is missing

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29893]
From @jgrigonis on 2016-02-19T22:12:18Z
##### Issue Type:

Please pick one and delete the rest:
- Bug Report
##### Component Name:

copy module

##### Ansible Version:

```
ansible 2.1.0 (devel 11f081cb99) last updated 2016/02/19 11:21:17 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) last updated 2016/02/11 14:06:38 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f) last updated 2016/02/11 14:06:38 (GMT -700)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```
##### Ansible Configuration:

[defaults]
host_key_checking = False
##### Environment:

running from OS X.
managing CentOS 6.7
##### Summary:

Copy module is not copying when I have set 
force: no
This applies when the destination file does not exist
##### Steps To Reproduce:

For bugs, please show exactly how to reproduce the problem. For new
features, show how the feature would be used.

```

---
- hosts: "infrastructure,testservers,devservers,production"
  remote_user: root
  tasks:
    - name: create nrpe cfg
      copy:
        src: files/nrpe.cfg
        dest: /usr/local/nagios/etc/nrpe.cfg
        owner: nagios
        group: nagios
        force: no
```

You can also paste gist.github.com links for larger files.
##### Expected Results:

I expect a file called nrpe.cfg to appear here:
/usr/local/nagios/etc
##### Actual Results:

What actually happened?
The file does not show up.

```
TASK [create nrpe cfg] *********************************************************
ok: [prodgo1]
ok: [prodgo3]
ok: [prodgo2]
ok: [prodgo4]
```

Copied from original issue: ansible/ansible-modules-core#3080

**Comment by ansibot** [comment]
From @ansibot on 2016-02-19T22:12:18Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @bobsonthegreat on 2016-02-19T22:12:18Z

I am also seeing this issue with ansible 2.1.0.0.

**Comment by ansibot** [comment]
From @PiotrOrzechowski on 2016-02-19T22:12:18Z

The same happens with Ansible 2.0.0.2.

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nchepanov** [comment]
Reproduced with 11f081cb99
```
ansible 2.1.0 (detached HEAD 11f081cb99)
  lib/ansible/modules/core: (detached HEAD 8d126bd877) 
  lib/ansible/modules/extras: (detached HEAD f6c5ed987f)
  config file =
  configured module search path = Default w/o overrides
```

Playbook:
```yaml
---
- hosts: all
  gather_facts: False
  tasks:
   - name: Copy bug
     copy:
       src: "/Users/nchepanov/dev/ansible/ansible/folder/file"
       dest: "/tmp/file"
       force: no
```

However, this appears to work as designed in `devel`: `ansible 2.6.0 (devel 67acffb5f2)`

@abadger
