### ISSUE TITLE
os_router fails on second run instead of skipping an existing router

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29903]
From @dyasny on 2016-02-08T21:35:51Z
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

os_router
##### ANSIBLE VERSION

N/A
##### SUMMARY

I am running a simple playbook to populate my openstack setup
At the first run, it passes. At the second run, it is supposed to skip all the points as there is nothing to change but instead it fails

My task code:

<snip>

```
- name: Create a public network
  os_network:
    state: present
    name: public
    state: present
    external: true

- name: Create a public subnet
  os_subnet:
    state: present
    name: public
    network_name: public
    cidr: 192.168.200.0/24
    dns_nameservers:
      - 10.11.5.19
      - 8.8.8.8
    allocation_pool_start: 192.168.200.100
    allocation_pool_end: 192.168.200.150
    host_routes:
    - destination: 0.0.0.0/0
      nexthop: 192.168.200.1

- name: Create a demo network
  os_network:
    state: present
    name: demo-net
    state: present

- name: Create a demo subnet
  os_subnet:
    state: present
    name: demo-subnet
    network_name: demo-net
    cidr: 192.168.150.0/24
    dns_nameservers:
      - 10.11.5.19
      - 8.8.8.8
    allocation_pool_start: 192.168.150.100
    allocation_pool_end: 192.168.150.150

- name: Create a demo router
  os_router:
    state: present
    name: demo-router
    network: public
    interfaces:
      - demo-subnet

- name: Create a security group
  os_security_group:
    state: present
    name: demo-secgroup
    description: network access for our first instance.

- name: Create a security group rule for SSH access
  os_security_group_rule:
    state: present
    security_group: demo-secgroup
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0

- name: Create a security group rule for ICMP
  os_security_group_rule:
    state: present
    security_group: demo-secgroup
    protocol: icmp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
```

</snip>
All the code: https://github.com/dyasny/ansible-populate-openstack/blob/master/create.yml#L176

Second (and subsequent runs) output:

TASK [Create a demo router] ****************************************************
task path: /home/stack/ansible-populate-openstack/create.yml:176
ESTABLISH LOCAL CONNECTION FOR USER: stack
127.0.0.1 EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1454967213.87-238047877538282 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1454967213.87-238047877538282 )" )
127.0.0.1 PUT /tmp/tmpAOny4E TO /home/stack/.ansible/tmp/ansible-tmp-1454967213.87-238047877538282/os_router
127.0.0.1 EXEC LANG=en_US.utf8 LC_ALL=en_US.utf8 LC_MESSAGES=en_US.utf8 /usr/bin/python /home/stack/.ansible/tmp/ansible-tmp-1454967213.87-238047877538282/os_router; rm -rf "/home/stack/.ansible/tmp/ansible-tmp-1454967213.87-238047877538282/" > /dev/null 2>&1
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"admin_state_up": true, "api_timeout": null, "auth": null, "auth_type": null, "availability_zone": null, "cacert": null, "cert": null, "cloud": null, "enable_snat": true, "endpoint_type": "public", "external_fixed_ips": [{"ip": "192.168.200.102", "subnet": "public"}], "interfaces": ["demo-subnet"], "key": null, "name": "demo-router", "network": "public", "region_name": null, "state": "present", "timeout": 180, "verify": true, "wait": true}, "module_name": "os_router"}, "msg": "Error detaching interface from router 84bd0bb9-3373-4aaa-a268-ee20536ba3a4: Router interface for subnet 1f484093-92dd-46b7-8d58-769cf9015ffb on router 84bd0bb9-3373-4aaa-a268-ee20536ba3a4 cannot be deleted, as it is required by one or more floating IPs."}

PLAY RECAP *********************************************************************
localhost                  : ok=14   changed=1    unreachable=0    failed=1   

At this point the router is already there, so the task should have skipped it instead.

Copied from original issue: ansible/ansible-modules-core#2989
