### ISSUE TITLE
route53 does not honor value order

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29908]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

route53 module

##### ANSIBLE VERSION

ansible 2.1.0 (devel 5144ee226e) last updated 2016/01/19 133246 (GMT -500)
lib/ansible/modules/core (detached HEAD ffea58ee86) last updated 2016/01/19 133250 (GMT -500)
lib/ansible/modules/extras (detached HEAD e9450df878) last updated 2016/01/19 133254 (GMT -500)
config file =
configured module search path = Default w/o overrides

##### OS / ENVIRONMENT

OSX

##### SUMMARY

When adding multiple addresses to an A record via a comma separated `value` parameter, the route53 module sorts the values before sending them to boto/aws.  However order is important to dns and the returned records do not match the desired input `value`.  The sorting prevents creation of the desired (unsorted) entry in route53 dns.

I don't know why the module makes the calls to `sorted` to sort the values.  If there is no reason, I can submit a PR that removes them.  Indeed, when I removed the sorted calls, the A records were created correctly (without forcing a sort.)

##### STEPS TO REPRODUCE

```
    - route53:
        command: create
        private_zone: False
        zone: "example.com"
        type: "A"
        identifier: "my id"
        record: "one.example.com"
        value: "172.30.1.2,172.30.1.1"
        weight: 50
        ttl: 60
```

##### EXPECTED RESULTS

route53 A record for one.example.com that returns 172.30.1.2 and 172.30.1.1 (in that order)

##### ACTUAL RESULTS

route53 A record for one.example.com that returns 172.30.1.1 and 172.30.1.2 (in that order - because the module sorted them before it created the entry in aws.)

Copied from original issue: ansible/ansible-modules-core#2949
