### ISSUE TITLE
ec2_ami_find: owner needs to be string, otherwise boto fails

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29912]
From @gdamjan on 2016-01-30T17:23:34Z
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

ec2_ami_find module
##### ANSIBLE VERSION

2.0.0.2
##### SUMMARY

ansible 2.0.0.2 and python2-boto 2.39.0-1

when using an number for the owner id, like in the docs `owner: 099720109477` boto fails with the following:

```
An exception occurred during task execution. The full traceback is:
Traceback (most recent call last):                                                                         
  File "/home/damjan/.ansible/tmp/ansible-tmp-1454173946.65-5987350817895/ec2_ami_find", line 2582, in <module>                                                                                                       
    main()                                                                                                 
  File "/home/damjan/.ansible/tmp/ansible-tmp-1454173946.65-5987350817895/ec2_ami_find", line 366, in main 
    images_result = ec2.get_all_images(owners=owner, filters=filter)                                       
  File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 181, in get_all_images              
    self.build_list_params(params, owners, 'Owner')                                                        
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1121, in build_list_params              
    for i in range(1, len(items) + 1):                                                                     
TypeError: object of type 'int' has no len()                                                               

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_name": "ec2_ami_find"}, "parsed": false}          
```

either the code needs to be updated or the docs.

Copied from original issue: ansible/ansible-modules-core#2922

**Comment by ansibot** [comment]
From @scottbrown on 2016-01-30T17:23:34Z

@gdamjan I am unable to recreate the stack trace you received.

Here is a sample playbook I created to list AMIs from both "self" and the owner specified in the example.  Both of these work without failure.

I tested what happens when `owner: 099720109477` is loaded by the Yaml parser and it comes into Python as a string, so it's weird that the stack trace you received is referencing an int.  I can also verify that declaring `owner = 099720109477` in Python (to ensure `owner` is an int) fails, because the number is not a proper octal.  Python sees this as an octal number (instead of decimal) because it begins with a `0`.  It's not a valid octal because the number `9` appears, hence why Python would throw a fit at it.

Can you try running the sample playbook below and seeing if you get the same error?

``` Yaml
---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: find AMIs for specific owner
      ec2_ami_find:
        region: 'us-east-1'
        owner: 099720109477
    - name: find AMIs for self
      ec2_ami_find:
        region: 'us-east-1'
        owner: self
```

And here is the output.

```
$ ansible-playbook -i localhost.inventory test.yml

PLAY ***************************************************************************

TASK [find AMIs for specific owner] ********************************************
ok: [localhost]     <<<< Scott: This operation takes 30-60 seconds

TASK [find AMIs for self] ******************************************************
ok: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
From @scottbrown on 2016-01-30T17:23:34Z

Oops, I forgot to add my environment:

```
$ ansible --version | head -1
ansible 2.0.0.2
$ pip freeze | grep boto
boto==2.39.0
boto3==1.2.3
botocore==1.3.15
$ python --version
Python 2.7.11
```

**Comment by ansibot** [comment]
From @gdamjan on 2016-01-30T17:23:34Z

actually, it fails for me for `owner: 379101102735`

**Comment by ansibot** [comment]
From @scottbrown on 2016-01-30T17:23:34Z

Thanks @gdamjan, I was able to replicate the issue with `owner: 379101102735`.  It looks like when Yaml identifies this value as an integer and passes it into the module, that's when the failure happens.

Here is the playbook testing each of the conditions:

``` Yaml
---
- hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: find AMIs for example owner
      ec2_ami_find:
        region: 'us-east-1'
        owner: 099720109477
      register: example_call
    - name: how many were found?
      debug:
        msg: "{{ example_call.results | length }}"
    - name: find AMIs for failing owner
      ec2_ami_find:
        region: 'us-east-1'
        owner: 379101102735
      register: failing_call
    - name: how many were found?
      debug:
        msg: "{{ failing_call.results | length }}"
    - name: find AMIs for self
      ec2_ami_find:
        region: 'us-east-1'
        owner: self
      register: self_call
    - name: how many were found?
      debug:
        msg: "{{ self_call.results | length }}"
```

The issue is that https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_ami_find.py#L365 needs to be coerced to a string.  This **seems** as simple as the following:

```
images_result = ec2.get_all_images(owners=str(owner), filters=filter)
```

and here's the output of the working version.

```
$ ansible-playbook -i localhost.inventory test.yml

PLAY ***************************************************************************

TASK [find AMIs for example owner] *********************************************
ok: [localhost]

TASK [how many were found?] ****************************************************
ok: [localhost] => {
    "msg": "6253"
}

TASK [find AMIs for failing owner] *********************************************
ok: [localhost]

TASK [how many were found?] ****************************************************
ok: [localhost] => {
    "msg": "13"
}

TASK [find AMIs for self] ******************************************************
ok: [localhost]

TASK [how many were found?] ****************************************************
ok: [localhost] => {
    "msg": "63"
}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0
```

However, this solution doesn't work because there's an edge case with using `str()` in python, in that it will view any owner ID that looks like a valid octal number as an octal and will then convert it to an integer then to a string, resulting in the wrong owner being applied.

simple playbook:

``` Yaml
- hosts: all
  tasks:
    - name: find AMIs for octal-looking owner
      ec2_ami_find:
        region: 'us-east-1'
        owner: 044720104477
```

output:

```
TASK [find AMIs for octal-looking owner] ***************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The er
ror was: <Response><Errors><Error><Code>InvalidUserID.Malformed</Code><Message>Invalid u
ser id: "4953508159"</Message></Error></Errors><RequestID>2da5ca2e-50b4-40e3-985a-5020aa
1373a1</RequestID></Response>
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "parsed": false}

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1
```

Note how the owner ID is different in the output (`4953508159`) than in the playbook (`044720104477`).
