### ISSUE TITLE
mount module can't handle nested mountpoints

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29921]
From @ghost on 2016-01-27T13:44:43Z
## Issue Type:

Bug Report
## Component Name:

mount module
## Ansible Version:

ansible 1.9.1
## Ansible Configuration:

No changes
## Environment:

RHEL 6.7 x86_64 (both Ansible master AND target host)
## Summary:

The mount module does not properly order nested filesystems in /etc/fstab even if with_dict dictionary variable has them in the proper order (I believe the dictionary order is executed in the order of the hashed keys).
## Steps to Reproduce:

1.) Create variable YAML file:
```yaml
lvols:
pgdata:
lv_name: pgdata
vg: pgdatavg
lv_size: 100%FREE
fs_type: ext4
mount_point: /var/lib/pgsql/9.4/data
owner: postgres
group: dba
mode: 700
pgwal:
lv_name: pgwal
vg: pgwalvg
lv_size: 100%FREE
fs_type: ext4
mount_point: /var/lib/pgsql/9.4/data/data/pg_xlog
owner: postgres
group: dba
mode: 700
```
2.) Run Playbook:
```
- hosts: newservers
  user: ansible
  sudo: True
  tasks:
- name: mount the new filesystem and add to fstab
  mount: name='{{ item.value.mount_point }}' src=/dev/'{{ item.value.vg }}'/'{{ item.value.lv_name }}' fstype='{{ item.value.fs_type }}' dump=1 passno=2 state=mounted
  with_dict: '{{ lvols }}'
```
## Expected Results:

Filesystem mounted in proper order (this order):
/var/lib/pgsql/9.4/data
/var/lib/pgsql/9.4/data/data/pg_xlog
(and properly defined in that order in /etc/fstab)
## Actual Results:

Filesystem not mounted in proper order. /var/lib/pgsql/9.4/data/data/pg_xlog was mounted first, THEN /var/lib/pgsql/9.4/data was mounted which covered up the first mountpoint.
## Output from Playbook:

(hostname changed in output):

```
changed: [mybox.mydomain.com] => (item={'key': 'pgwal', 'value': {'mount_point': '/var/lib/pgsql/9.4/data/data/pg_xlog', 'group': 'dba', 'lv_name': 'pgwal', 'vg': 'pgwalvg', 'fs_type': 'ext4', 'mode': 700, 'owner': 'postgres', 'lv_size': '100%FREE'}}) => {"changed": true, "dump": "1", "fstab": "/etc/fstab", "fstype": "ext4", "item": {"key": "pgwal", "value": {"fs_type": "ext4", "group": "dba", "lv_name": "pgwal", "lv_size": "100%FREE", "mode": 700, "mount_point": "/var/lib/pgsql/9.4/data/data/pg_xlog", "owner": "postgres", "vg": "pgwalvg"}}, "name": "/var/lib/pgsql/9.4/data/data/pg_xlog", "passno": "2", "src": "/dev/pgwalvg/pgwal"}

changed: [mybox.mydomain.com] => (item={'key': 'pgdata', 'value': {'mount_point': '/var/lib/pgsql/9.4/data', 'group': 'dba', 'lv_name': 'pgdata', 'vg': 'pgdatavg', 'fs_type': 'ext4', 'mode': 700, 'owner': 'postgres', 'lv_size': '100%FREE'}}) => {"changed": true, "dump": "1", "fstab": "/etc/fstab", "fstype": "ext4", "item": {"key": "pgdata", "value": {"fs_type": "ext4", "group": "dba", "lv_name": "pgdata", "lv_size": "100%FREE", "mode": 700, "mount_point": "/var/lib/pgsql/9.4/data", "owner": "postgres", "vg": "pgdatavg"}}, "name": "/var/lib/pgsql/9.4/data", "passno": "2", "src": "/dev/pgdatavg/pgdata"}
```
Copied from original issue: ansible/ansible-modules-core#2898

**Comment by ansibot** [comment]
From @ansibot on 2016-01-27T13:44:43Z



@grossws ping, this issue is waiting for your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
@ghost Please could you test it again with the latest Ansible? There is quite good chance that the issue is gone by now.

**Comment by mkrizek** [comment]
needs_info

**Comment by Akasurde** [comment]
For posterity, 

`with_dict` doesn't guarantee order of the element while iterating, (correct me if I am wrong)

So I came up with a simple solution like 

```yaml
---
- name: With dict sequential example
  hosts: localhost
  vars:
    mount_points:
      "3":
        name: mount3
        path: /tmp/c
      "1":
        name: mount1
        path: /tmp/a
      "2":
        name: mount2
        path: /tmp/b
  tasks:
    - name: Print sequentially over dict
      debug:
        msg: "{{ mount_points[item] }}"
      with_sequence: "{{ mount_points | length }}"
```

Closing this issue as there is no response from user.
