### ISSUE TITLE
Can't launch EC2 instance with ephemeral volume

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29925]
From @rhartkopf on 2016-01-26T01:29:04Z
##### ISSUE TYPE

Documentation Report
##### COMPONENT NAME

ec2 module
##### ANSIBLE VERSION

2.0.0.2
##### SUMMARY

The Ansible docs aren't very clear on how ephemeral volumes are managed on ec2 instance launch, but this configuration is similar to what has worked for others on forums and message boards, such as here: https://groups.google.com/forum/#!msg/ansible-project/nAmQgkiseBs/IFYTFuRSCgkJ

No matter what I try, I only see /dev/xvda on instance launch. I'm happy to contribute this answer to the docs once I know what's wrong.

Thanks!

```
  - name: find or provision ec2 instance
    local_action:
      module: ec2
      key_name: "ansible"
      instance_type: "c3.xlarge"
      image: "ami-f0091d91"
      user_data: "{{ lookup('file', 'userdata_tty') }}"
      wait: yes
      assign_public_ip: yes
      wait_timeout: 300
      group_id: "{{ ec2_security_group_allservers.group_id }}"
      region: "us-west-2"
      volumes:
      - device_name: /dev/xvda
        volume_size: 100
        delete_on_termination: true
      - device_name: /dev/sdb
        ephemeral: ephemeral0
      instance_tags:
        Name: "{{ inventory_hostname }}"
        Subnet: "{{ subnet }}"
      exact_count: 1
      count_tag:
        Name: "{{ inventory_hostname }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
    register: my_instance
```

boto 2.39.0, Ansible 2.0.0.2, Python 2.7.6, Ubuntu 14.04.3

Copied from original issue: ansible/ansible-modules-core#2881

**Comment by ansibot** [comment]
From @jimi-c on 2016-01-26T01:29:04Z

Ran through a lot of these scenarios while talking with another user, however I can't remember what the resolution was beyond the fact that the number/size of the ephemeral disks were was tied to the instance type.

**Comment by ansibot** [comment]
From @rhartkopf on 2016-01-26T01:29:04Z

The c4 series is doing away with ephemeral instances altogether, so I am now using c4.xlarge to avoid this issue. I was not able to find a solution.

**Comment by ansibot** [comment]
From @byoungb on 2016-01-26T01:29:04Z

I think you need volume_type:ephemeral

**Comment by ansibot** [comment]
From @byoungb on 2016-01-26T01:29:04Z

Nevermind that doesn't work Did anyone ever figure this out? 
I have 

```
        ....
        instance_type: c3.xlarge
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 15
            delete_on_termination: true
          - device_name: /dev/sdb
            volume_type: gp2
            ephemeral: ephemeral0
```

I have tried a bunch of variations... but it never attaches

**Comment by ansibot** [comment]
From @byoungb on 2016-01-26T01:29:04Z

figured it out!
this worked for me

```
        volumes:
          - device_name: /dev/xvda
            delete_on_termination: true
            volume_type: gp2
            volume_size: 15
          - device_name: /dev/xvdb
            volume_type: ephemeral
            ephemeral: ephemeral0
```

so I think the real fix was using  /dev/xvdb instead of  /dev/sdb
