### ISSUE TITLE
ec2 module fails to create volume from snapshot

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29933]
From @mnuessler on 2016-01-14T12:18:13Z
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

ec2 module
##### ANSIBLE VERSION

N/A
##### SUMMARY

According to the documentation [documentation](http://docs.ansible.com/ansible/ec2_module.html) and the provided examples I understand that it should be possible to create an EC2 instance with an additional EBS volume from an existing snapshot as follows:

``` yaml
- ec2:
  instance_type: r3.large
  image: ami-47a23a30
  group_id: my_security_group
  region: eu-west-1
  zone: eu-west-1a
  assign_public_ip: no
  volumes:
     - device_name: /dev/sdb
       snapshot: snap-xxxxx
       volume_size: 650
       delete_on_termination: true
  wait: yes
```

However, I am getting the following error message:

```
msg: Instance creation failed => InvalidBlockDeviceMapping: snapshotId can only be modified on EBS devices
```

The same errors also occurs if I add the `volume_type` or `device_type` option. Am I missing something here or is it a bug? Any way to work around this problem?

Versions:
- ansible 1.9.4-1
- boto 2.20.1
- Python 2.7.6

Copied from original issue: ansible/ansible-modules-core#2810
