### ISSUE TITLE
iam module not very useful for managing access keys

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29931]
##### ISSUE TYPE

feature idea

##### COMPONENT NAME

iam module

##### ANSIBLE VERSION

2.0.0.2

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Configuring non-EC2 machines with credentials to access AWS services.

##### SUMMARY

The IAM module is not useful for most management of the access keys belonging to a user because it does not retrieve/output the secret access key in a way that allows one to persist it.  It is impossible to retrieve the secret key after an access key is created,  so any key created by ansible is can't be used.

##### STEPS TO REPRODUCE

A simple task like:

``` yaml
- iam:
    iam_type: user
    name: "my-server-{{ansible_hostname}}"
    state: present
    groups: my-group
    access_key_state: create
  delegate_to: 127.0.0.1
  register: credentials
- debug: var=credentials
```

##### EXPECTED RESULTS

I propose two changes:
- The module should include the created access key and secret access key in the registered output so it can be accessed by later tasks, for example to write to a credentials file.
- Add a new access_key_state called 'rotate' which causes key creation to perform the following logic:
  - If the user has more than `key_count` access keys, delete the oldest until there are `key_count`-1 assigned to the user.
  - Create a new access key and secret access key
  - In the module output, provide output of the new key and old keys like so:

``` python
{
  "changed": true, 
  "groups": [
    "my-group"
  ], 
  "current_key": 
    "access_key_id": "AKIA.......",
    "secret_access_key": "random-aws-output"
  },
  "old_keys": [
    "AKIAIoldkeyid"
  ], 
  "user_name": "my-server-foo"
}
```

Then you could have a set of tasks like...

``` yaml
- iam:
    iam_type: user
    name: "my-server-{{ansible_hostname}}"
    key_count: 2
    state: present
    groups: my-group
    access_key_state: rotate
  delegate_to: 127.0.0.1
  register: credentials
- template: dest=/root/.aws/credentials src=credentials_template
- service: name=some_server state=restarted
- iam:
    iam_type: user
    access_key_ids: "{{credentials.old_keys}}"
    access_key_state: remove
    name: "my-server-{{ansible_hostname}}"
```

...that creates credentials for a server, installs them, restarts a service, and then deletes the old credentials it may have been using, performing a safe rotate.

##### ACTUAL RESULTS

For reference, the current module output when creating an access key is:

``` python
{
        "changed": true, 
        "groups": [
            "groups"
        ], 
        "keys": {
            "AKIAsomekeyid": "Active"
        }, 
        "user_name": "user"
    }
```

Copied from original issue: ansible/ansible-modules-core#2821
