### ISSUE TITLE
Jinja-style variable expansion throws syntax errors in certain contexts

### ISSUE THREAD

**Issue by qjcg** [ansible/ansible#2994]
There seems to be a weird inconsistency with the newly-preferred jinja-style variable syntax---namely, {{ var }}-style variable-expansion in certain contexts will result in a syntax error where ${ var }-style expansion runs without error.

Given the following playbook :

``` yaml

---
- hosts: localhost

  vars:
    foo: example.com
    bar: sample.net
  tasks:
    - name: echo all the things! 
      command: /usr/bin/echo {{ item }} 
      with_items: 
        - ${ foo }
        - {{ bar }}
```

I get the following error on execution :

``` console
$ ansible-playbook var_expansion_weirdness.yml
ERROR: Syntax Error while loading YAML script, vars_bug_test.yml
Note: The error may actually appear before this position: line 14, column 12

        - ${ foo }
        - {{ bar }}
           ^
```

If I then change the syntax inside the with_items: section from {{ bar }} to ${ bar }, the playbook executes without error.

Tested on ansible 1.2 (devel branch rev. 8f3b2b2).

**Comment by qjcg** [comment]
The following also fails with a syntax error : 

``` yaml
vars:
  foo: example.com
  bar: {{ foo }}
```

The same block with bar set to the value of foo in ${}-style syntax runs without issue : 

``` yaml
vars:
  foo: example.com
  bar: ${ foo }
```
