### ISSUE TITLE
openssl_certificate should be able to verify a certificate chain

### ISSUE THREAD

**Issue by MarkusTeufelberger** [ansible/ansible#29951]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

openssl_certificate

##### ANSIBLE VERSION

```
2.4
```

##### SUMMARY

Verifying that a certificate has a valid chain up to a trusted CA certificate is an important check that might be expected to be supported by the openssl_certificate module.

##### EXPECTED RESULTS

There probably needs to be a parameter that takes in a list of paths to certificate files, drop all of these + the "main" certificate in a pyopenssl StoreContext and run https://pyopenssl.org/en/stable/api/crypto.html#OpenSSL.crypto.X509StoreContext.verify_certificate on every single one of them to be able to check if a certificate has a valid path to a CA certificate.

I am not 100% sure how `verify_certificate` is implemented in pyopenssl (does it only check for the existence of a valid parent cert or does it check for a valid chain up to a root cert?), so it might be enough to run it only on the "main" certificate.

Syntax could be something like this:
```
openssl_certificate:
  path: /foo.pem
  parent_certificates:
    - /bar1.pem
    - /bar2.pem
    - /root_ca.pem
```

##### ACTUAL RESULTS

It is currently not possible to check whether a certificate belongs to a certain chain or root CA or not.

**Comment by ansibot** [comment]
cc @Spredzy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by vaivars** [comment]
This could make the module very valuable for the intention of using ansible to monitor certificates

**Comment by dyindude** [comment]
Here's a workaround I use for checking if a ca cert is valid for a certificate:

```
- name: manage host certificate
  block:
    - name: check if cert has expired
      openssl_certificate:
        path: {{ cert_filename }}
        has_expired: False
        valid_at: "{{ cert_valid_at }}"
    - name: check if our ca cert is valid for this cert
      shell: "[[ $(openssl verify -CAfile {{ ca_filename }} {{ cert_filename }} |& grep OK | wc -c) -ne 0 ]]"
      args:
        executable: /bin/bash
      changed_when: False
  rescue:
    - name: generate host certs/keys
...
```
