### ISSUE TITLE
ec2_elb_lb is not idempotent if the elb tags are different

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29965]
From @Giri-Chintala on 2015-12-30T23:24:49Z
### Issue Type:

Bug Report
### Component Name:

ec2_elb_lb
### ansible version:

1.9.4
### Environment:

mac
boto verson 2.38.0
### Summary:

When an ELB is created and add tags using shell module that invokes AWS CLI, it runs well at the first time, but it fails on all subsequent calls.
### Error:

' File "/usr/local/Cellar/ansible/1.9.4/libexec/vendor/lib/python2.7/site-packages/boto/connection.py", line 1208, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 400 Bad Request
DuplicateLoadBalancerName
Load Balancer named XXXXX already exists and it is configured with different tags.

Copied from original issue: ansible/ansible-modules-core#2745

**Comment by ansibot** [comment]
From @ansibot on 2015-12-30T23:24:49Z



@jsdalton, @rickmendes, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by chrisweaver** [comment]
This issue has been around for a very long time.  It first appeared in 2.1:
https://github.com/ansible/ansible-modules-core/issues/3444

I'm still seeing it with 2.4.1 and on RHEL 7.4:

`boto.exception.BotoServerError: BotoServerError: 400 Bad Request
<ErrorResponse xmlns=\"http://elasticloadbalancing.amazonaws.com/doc/2012-06-01/\">
<Error>
<Type>Sender</Type>
    <Code>DuplicateLoadBalancerName</Code>
<Message>Load Balancer named <..> already exists and it is configured with different tags.`

**Comment by ansibot** [comment]
cc @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chrisweaver** [comment]
FYI I am using the following workaround for Tags:

```
- name: "Workaround p1: See if ELB already exists"
  ec2_elb_facts:
    names: "{{ elb_name | d(default_elb_name) }}"
    region: "{{ aws_region }}"
  register: provision_elb_elblist

- block:
    - name: "Workaround p2: Remove all tags on our ELB, if ELB already exists"
      command: >
        aws elb remove-tags --load-balancer-name={{ elb_name | d(default_elb_name) }}
          --tags={{ item.key }}
          --region={{ aws_region }}
      with_dict: "{{ provision_elb_elblist.elbs.0.tags }}"

  when: provision_elb_elblist.elbs
```
