### ISSUE TITLE
variable from "vars:" does not work in "when:"

### ISSUE THREAD

**Issue by glensc** [ansible/ansible#2996]
playbook based on [ansible-examples/language_features/register_logic.yml](https://github.com/ansible/ansible-examples/blob/master/language_features/register_logic.yml):

```
- name: test playbook
  hosts: all
  gather_facts: no

  vars:
    my_matching_var: c87085c0f00b97d50082ed26ff63e1d7
  tasks:
      - action: shell echo c87085c0f00b97d50082ed26ff63e1d7
        ignore_errors: yes
        register: motd_result

      - action: shell echo "motd contains the word hi"
        when: motd_result.stdout.find("{{ my_matching_var }}") != -1
```

this skips second task:

```
TASK: [shell echo "motd contains the word hi"] ******************************** 
skipping: [example.org] 
```

if i replace last line with fixed var, the playbook will not skip second echo action:

```
        when: motd_result.stdout.find('c87085c0f00b97d50082ed26ff63e1d7') != -1
```
