### ISSUE TITLE
Docker module: can't link same container with different aliases

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29971]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

ansible 1.9.1

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I need to link the same docker container with different aliases, but I can't - it will be only linked with the last alias.

##### STEPS TO REPRODUCE

Write a docker task similar to this:
```
- name: run docker container
  docker:
    links:
  - "container1:alias1"
  - "container1:alias2"
```

##### EXPECTED RESULTS

container1 should be linked with "alias1" and "alias2" aliases

##### ACTUAL RESULTS

container1 is linked only with "alias2" alias

Note:

I already opened this ticket once but you categorised it as a feature_idea. As this is a proper feature of docker and docker-compose but it is not working properly through the Ansible module, please categorise it as a bug.

Copied from original issue: ansible/ansible-modules-core#2698
