### ISSUE TITLE
Bug Report. AWS ASG module property wait_for_instances: no errors

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29977]
From @ablack-idguk on 2015-12-08T16:51:37Z
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

ec2_asg module
##### ANSIBLE VERSION

1.9.3
##### SUMMARY

setting wait_for_instances: no

Steps

Using http://docs.ansible.com/ansible/ec2_asg_module.html

I originally had wait_for_instances as unspecified i.e default which is True.

I didn't want this to wait so set it to no as when it waits all subsequent events are blocked and stay in waiting state.

When setting to no i received the error message below (note this is from the latest version of the asg module that i was advised to add to a local library folder - https://github.com/ansible/ansible-modules-core/blob/devel/cloud/amazon/ec2_asg.py by ansible tower support)

TASK: [create auto scaling group] ********************************************\* <localhost> REMOTE_MODULE ec2_asg health_check_type=ELB max_size=2 load_balancers=pca-elb launch_config_name=pca-lc desired_capacity=1 min_size=1 region=eu-west-1 name=pca-asg <localhost> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802 && echo $HOME/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802'] <localhost> PUT /tmp/tmpo7ztax TO /var/lib/awx/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802/ec2_asg <localhost> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802/ec2_asg; rm -rf /var/lib/awx/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802/ >/dev/null 2>&1'] failed: [localhost] => {"failed": true, "parsed": false} Traceback (most recent call last):

  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802/ec2_asg", line 2643, in <module>
    main()
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802/ec2_asg", line 2637, in main
    replace_changed, asg_properties=replace(connection, module)
  File "/var/lib/awx/.ansible/tmp/ansible-tmp-1449579216.61-198415392135802/ec2_asg", line 2371, in replace
    instances = props['instances']
KeyError: 'instances'

FATAL: all hosts have already failed -- aborting

My module definition is....
- name: create auto scaling group
   ec2_asg:
     name: "{{ site_prefix }}-asg"  
     launch_config_name: "{{ site_prefix }}-lc"
     health_check_period: 500 #time before first health check is made
     health_check_type: ELB
     replace_all_instances: yes
     min_size: "{{ server_min_size }}"
     max_size: "{{ server_max_size }}"
     desired_capacity: "{{ server_desired_size }}"
     region: "{{ aws_region }}"
     load_balancers: "{{ site_prefix }}-elb"
# needed if public ip is required

```
   vpc_zone_identifier:
     - 'subnet-xxxx'
   wait_for_instances: no #dont block waiting for instances to become health (blocks all other running tasks in tower)
```

Copied from original issue: ansible/ansible-modules-core#2652

**Comment by ansibot** [comment]
From @ablack-idguk on 2015-12-08T16:51:37Z

See https://support.ansible.com/hc/requests/7018 for full conversation.

**Comment by ansibot** [comment]
From @abhilash80 on 2015-12-08T16:51:37Z

I found this thread while i was trying to resolve a similar issue wherein the auto-scaling-group ansible module (ansible version 2.2.0) would fail with "KeyError: Instances" while provisioning a new ASG even when the wait_for_instances flag was set to FALSE. It appeared that the error was caused waiting for the EC2 instances to finish initializations, because re-executing the script within 10 seconds would result in no errors.

I resolved the issue by using a loop and retrying a few times - snippet below:

I hope this is useful to somebody facing the same issue.

```
  # Provision the Auto Scaling Group now
  - name: "AWS | Auto Scaling Group | Create EC2 Auto Scaling Group"
    ec2_asg:
      name: "{{ aws_ec2_auto_scaling_group_name }}"
      health_check_period: "{{ aws_ec2_auto_scaling_group_health_check_period }}"
      health_check_type: "{{ aws_ec2_auto_scaling_group_health_type }}"
      default_cooldown: "{{ aws_ec2_auto_scaling_group_default_cooldown }}"
      replace_all_instances: "{{ aws_ec2_auto_scaling_group_replace_all_instances }}"
      availability_zones: "{{ aws_ec2_auto_scaling_group_availability_zones }}"
      launch_config_name: "{{ aws_ec2_launch_config_name }}"
      min_size: "{{ aws_ec2_auto_scaling_group_min_size }}"
      max_size: "{{ aws_ec2_auto_scaling_group_max_size }}"
      desired_capacity: "{{ aws_ec2_auto_scaling_group_desired_capacity }}"
      vpc_zone_identifier: "{{ subnet_facts.results|map(attribute='subnets')|list|map('first')|list|map(attribute='id')|list }}"
      tags: "{{ std_asurion_aws_tags_list }}"
      wait_for_instances: "{{ aws_ec2_auto_scaling_group_wait }}"
      load_balancers: "{{aws_ec2_auto_scaling_group_elbs}}"
      region: "{{aws_region}}"
      state: present
    until: (ec2_asg_return is defined) and (ec2_asg_return.viable_instances|int >= aws_ec2_auto_scaling_group_desired_capacity|int)
    retries: 10                       # Number of times to retry to get the desired status
    delay: 10                         # Delay between retries
    register: ec2_asg_return
```
