### ISSUE TITLE
postgresql_user can't create role without database

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29985]
From @cortopy on 2015-11-30T14:49:35Z

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
postgresql_user module

##### ANSIBLE VERSION
N/A

##### SUMMARY
I'm trying to create an admin user for postgresql which is not SUPERUSER but still has access to most admin tasks. For that, I need the user not to be associated with only one database. I'm not sure if this can be achieved with ansible though.

Normally I would do something like:

```
CREATE ROLE admin_role_name CREATEROLE CREATEDB LOGIN;
```

If I try the following to replicate it with ansible, I get an error:

``` yaml
  - name: PSQL ROLE | Create admin role
    postgresql_user: |
                     name={{pgsql_admin_user}}
                     priv=CREATEROLE,CREATEDB,LOGIN
```

The task above generates an error saying that a database is needed. As an experiment I tried `db=*` but this produces the following error:

`__main__.InvalidPrivsError: Invalid privs specified for database: CREATEDB LOGIN CREATEROLE`

Copied from original issue: ansible/ansible-modules-core#2591
