### ISSUE TITLE
add github deploy keys

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29981]
From @jmdh on 2015-12-04T14:22:55Z
##### Issue Type:

Feature Idea
##### Component Name:

new module
##### Ansible Version:

N/A
##### Ansible Configuration:

N/A
##### Environment:

N/A
##### Summary:

Instead of writing:

```
- user: name=blah generate_ssh_key=yes
- pause: prompt="Please add ssh key as deploy key..."
- git: repo=blah 
```

it would be nice to have automation of adding the newly created key to github via the API: https://developer.github.com/v3/repos/keys/

Copied from original issue: ansible/ansible-modules-core#2626

**Comment by ansibot** [comment]
From @bcoca on 2015-12-04T14:22:55Z

The authorized_key module can already do this:

```
- authorized_key: user=charlie key=https://github.com/charlie.keys
```

**Comment by ansibot** [comment]
From @jmdh on 2015-12-04T14:22:55Z

Hi Brian,

The authorized_key module deals with managing ~/.ssh/authorized_keys; I'm talking about adding a key (eg ~/.ssh/id_rsa.pub) as an authorized key on the github service as per the API I quoted (note: that is for deploy keys; a similar functionality could be implemented for user keys - https://developer.github.com/v3/users/keys/)

I'm not aware of this functionality already existing - I'm sorry that I wasn't more explicit in my description of the feature idea.

Best,
Dominc.

**Comment by ansibot** [comment]
From @bcoca on 2015-12-04T14:22:55Z

sorry, misread what you meant, you actually want a github_keys module.

**Comment by ansibot** [comment]
From @calmdev on 2015-12-04T14:22:55Z

This feature would be great. @jmdh did you use curl? Curious if you found a solution you're happy with.

**Comment by ansibot** [comment]
From @jmdh on 2015-12-04T14:22:55Z

I don't remember the exact use case I filed this for - I guess I did it manually.

**Comment by ansibot** [comment]
From @calmdev on 2015-12-04T14:22:55Z

Here are the tasks I'm using that work for me:

``` yml
- name: Generate SSH key.
  shell: ssh-keygen -t rsa -b 4096 -N "" -C $HOSTNAME -f ~/.ssh/id_rsa

- name: Read SSH public key.
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_public_key

- name: Add SSH key to username/repository.
  uri:
    url: https://api.github.com/repos/[username]/[repository]/keys
    method: POST
    status_code: 201
    body:
      read_only: true
      key: "{{ ssh_public_key.stdout }}"
    body_format: json
    headers:
      Content-Type: application/json
      Authorization: token [personal-access-token]
```
