### ISSUE TITLE
Idempotence with EC2 Security Groups

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29986]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

ec2_group module

##### ANSIBLE VERSION

2.3

##### SUMMARY

From @edsonmarquezani on 2015-11-28T16:16:27Z
It seems there's some inconsistency regarding EC2 Secutiry Groups rules idempotence (ec2_group module).

Assume the following task (my real code):

```
- name: "scg-{{ environment_short }}-pub-ec2-{{ group }}-webapp"
  ec2_group:
    name: "scg-{{ environment_short }}-pub-ec2-{{ group }}-webapp"
    vpc_id: "{{ vpc.vpc_id }}"
    region: "{{ aws_region }}"
    description: "Security group for {{ group }} web application servers."
    rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        group_id: "scg-{{ environment_short }}-pub-elb-{{ group }}-webapp"
      - proto: tcp
        from_port: 443
        to_port: 443
        group_id: "scg-{{ environment_short }}-pub-elb-{{ group }}-webapp"
  register: sg3
```

First time I run it, the security group is successfully created. If I run it again, then I get the following error.

**`TASK [scg-prd-pub-ec2-tvk-webapp]  An exception occurred during task execution. To see the full traceback, use -vvv. The error was: <Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: sg-795f0c1f, TCP, from port: 80, to port: 80, ALLOW" already exists</Message></Error></Errors><RequestID>d2916a1d-923d-4182-a528-5863973e7f2e</RequestID></Response>
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "parsed": false}`**

What is weird is that I don't get an error like that for all my security groups, but just some of them. I have other tasks on the playbook with ingress rules like that, which keep working after being created.

I'm using Ansible 2.0.0-0.6.rc1 and Boto 2.38, but I have had the same problem with previous version of Ansible as well.

Thanks.

Copied from original issue: ansible/ansible-modules-core#2576

**Comment by ansibot** [comment]
From @robynbergeron on 2015-11-28T16:16:27Z

[module: cloud/amazon/ec2_group.py]

**Comment by ansibot** [comment]
From @robynbergeron on 2015-11-28T16:16:27Z

@edsonmarquezani -- Thanks for submitting this bug report.

@adq --  thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by ansibot** [comment]
From @klj613 on 2015-11-28T16:16:27Z

Hello,

Just took a look at this and it seems if you use `group_name` instead of `group_id` it would work.

By looking at the module it seems `group_id` will only properly work if its the actual ID of the security group. The list of examples for this module may need updating to reflect this.

**Comment by ansibot** [comment]
From @edsonmarquezani on 2015-11-28T16:16:27Z

@klj613 , you're right. I ended up changing all my references to the actual group IDs and stopped having that problem. I think the problem is that, indeed, documentation says it can be used in different ways (_123412341234/sg-87654321/exact-name-of-sg_). And, when the rule doesn't exist, it does work. So, I think it should be more consistent (it either works fully or not).

Thanks.

**Comment by ansibot** [comment]
From @klj613 on 2015-11-28T16:16:27Z

I agree. Not sure how much work it would be. Might be as simple as if it cant find it by ID then look by name. Will have another look tomorrow or Thursday.

When the docs show `123412341234/sg-87654321/exact-name-of-sg` I don't know what `123412341234` refers to though. The 'Name' tag of the security group perhaps?

**Comment by ansibot** [comment]
From @edsonmarquezani on 2015-11-28T16:16:27Z

Yeah, I don't know either, specially because it's a numeric value, which confuses me even more regarding its source. Anyway, this part of the module would benefit from some revision.

**Comment by ansibot** [comment]
From @Constantin07 on 2015-11-28T16:16:27Z

The problem still persists even when no group_id is referenced in the rule.

```
- name: Create security group
  ec2_group:
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    description: "{{ security_group.description }}"
    name: "{{ security_group.name }}"
    purge_rules: yes
    purge_rules_egress: yes
    rules: "{{ security_group.inbound }}"
    rules_egress: "{{ security_group.outbound }}"
    state: present
  register: sg_res
```

On a second run I get this error:

```
TASK: [Create security group] **********************************
failed: [127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/home/user/.ansible/tmp/ansible-tmp-1467292699.69-182962648293561/ec2_group", line 2284, in <module>
    main()
  File "/home/user/.ansible/tmp/ansible-tmp-1467292699.69-182962648293561/ec2_group", line 369, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], thisip, grantGroup)
  File "/usr/lib/python2.7/site-packages/boto/ec2/securitygroup.py", line 203, in authorize
    dry_run=dry_run)
  File "/usr/lib/python2.7/site-packages/boto/ec2/connection.py", line 3207, in authorize_security_group
    params, verb='POST')
  File "/usr/lib/python2.7/site-packages/boto/connection.py", line 1227, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidPermission.Duplicate</Code><Message>the specified rule "peer: 180.150.151.192/29, TCP, from port: 80, to port: 80, ALLOW" already exists</Message></Error></Errors><RequestID>c0b2e1e8-68c7-4a06-8854-9033d2d717c9</RequestID></Response>
FATAL: all hosts have already failed -- aborting
```
