### ISSUE TITLE
'file' module cannot create private subdirectories more than 2 levels deep

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29999]
From @drybjed on 2015-11-14T17:56:04Z
##### Issue Type:

Bug Report
##### Component Name:

file module
##### Ansible Version:

Ansible devel
##### Ansible Configuration:

Default `ansible.cfg`
##### Environment:

Debian, Ubuntu, unprivileged account
##### Summary:

`file` module cannot create private directories with mode `0600` more than two levels deep.
##### Steps To Reproduce:

```
- hosts: all
  become: False

  tasks:

    - name: Create private directory
      file:
        path: '~/var/lib/private'
        state: 'directory'
        mode: '0600' 
```
##### Expected Results:

Directories are created without issues.
##### Actual Results:

```
PLAY ***************************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [Create private directory] ************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "There was an issue creating /var/local/drybjed/var/lib/private as requested: 'module' object has no attribute 'EEXISTS'", "path": "/var/local/drybjed/var/lib/private", "state": "absent"}

PLAY RECAP *********************************************************************
localhost                      : ok=1    changed=0    unreachable=0    failed=1   
```

Copied from original issue: ansible/ansible-modules-core#2473
