### ISSUE TITLE
docker reloaded mode does not work when 2 ips are assigned to the same port

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#29991]
From @Cactusbone on 2015-11-23T13:53:51Z

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
docker module

##### ANSIBLE VERSION
N/A

##### SUMMARY
with 

```
docker:
 name: etcd
 image: quay.io/coreos/etcd:v2.0.13
 state: reloaded
 ports:
      - 127.0.0.1:4001:4001
      - 1.2.3.4:4001:4001
```

the container is restarted each time the role is executed

using -vvv gives

```
"reload_reasons": "port bindings (
{'4001/tcp': [{'HostPort': '4001', 'HostIp': '127.0.0.1'}, {'HostPort': '4001', 'HostIp': '1.2.3.4'}]}
 => 
{'4001/tcp': [{'HostPort': \"('1.2.3.4', 4001)\", 'HostIp': ('127.0.0.1', 4001)}]}
)
```

I believe there's a problem when comparing ports ...

Copied from original issue: ansible/ansible-modules-core#2523
