### ISSUE TITLE
Unarchive module throws an error on OS X

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30004]
From @anthonygreen on 2015-11-06T10:58:35Z
#### Issue Type:

Bug Report
#### Ansible Version:

2.0.0-0.4.beta2
#### Environment

Running from: OS X 10.9.5
Managing: OSX VM 10.10
#### Summary:

unarchive_module throws an error on OS X
#### Steps to reproduce

This task fails

```
- name: Download a file
  unarchive: 
    src: https://www.dropbox.com/path.to.some/file?raw=1
    dest: /tmp
    copy: no
    creates: /tmp/file
```

results in the error

```
No such file or directory: '/tmp/__MACOSX/._
```

The file has been downloaded to /tmp and appears to unzipped but has thrown an error. 

Copied from original issue: ansible/ansible-modules-core#2423
