### ISSUE TITLE
ec2_asg hits rate limit for DescribeAutoScalingGroups

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30000]
From @rsouthgate on 2015-11-13T19:16:29Z

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
ec2_asg module

##### ANSIBLE VERSION
N/A

##### SUMMARY

When attempting to use ec2_asg to bring new instances into service and terminate old ones (blue/green deploy) we hit a rate limit with AWS on the DescribeAutoScalignGroups service. In this particular scenario we are attempting to scale three ASGs at once so use ec2_asg in async forks.

Would it be possible to make the speed at which it polls the describe service configurable so we could throttle it right back?

Copied from original issue: ansible/ansible-modules-core#2469

**Comment by ansibot** [comment]
From @tartansandal on 2015-11-13T19:16:29Z

I have also seen this rate limit hit when trying to remove a bunch of instances from their load balancers using ec2_elb_lb.  I'm wondering if this might be a more general issue with certain AWS APIs.

**Comment by ansibot** [comment]
From @tartansandal on 2015-11-13T19:16:29Z

Hmmm just saw the same issue with ec2_elb.  Currently getting around the issue by setting `serial` on the play and adding a 1 second `pause` in the task list.  I'm surprised this as not hit us earlier. Maybe its an issue with the `ap-southeast`region.

**Comment by ansibot** [comment]
From @jjshoe on 2015-11-13T19:16:29Z

Save the following tasks in whatever format you'd like, setting the correct subnet for your VPC. The first time you call it will succeed as there are no instances to replace. The second time you call it you will hit the rate limit. 

Steps to reproduce:

```
- name: Make a launch config name
  set_fact:
    launch_config_name: "joels_lc_{{ ansible_date_time.epoch }}"

- name: Create launch config for new instance
  ec2_lc:
    name: "{{ launch_config_name }}"
    image_id: "ami-08111162"
    instance_type: "t2.nano"
    region: "us-east-1"

- name: Update the autoscale group (w/o ELB)
  ec2_asg:
    name: "joels_asg"
    launch_config_name: "{{ launch_config_name }}"
    region: "us-east-1"
    availability_zones:
      - us-east-1d
    vpc_zone_identifier:
      - subnet-xxxxxxx
    min_size: "0"
    max_size: "20"
    desired_capacity: "10"
    replace_all_instances: "True"
    wait_for_instances: "True"
    wait_timeout: "600"
    tags:
      - Name: "joels_asg_test_instance"
    health_check_type: "EC2"
```
