### ISSUE TITLE
Mount module overrides entries when used with 'with_items'

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30027]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

mount module

##### ANSIBLE VERSION

Ansible stable (1.9.4) Ansible devel

##### CONFIGURATION

Default Ansible configuration

##### OS / ENVIRONMENT

Debian Ubuntu

##### SUMMARY

Ansible overrides `/etc/fstab` entry when called with `with_items`.

##### STEPS TO REPRODUCE

```

---

- hosts: localhost

  vars:
    file_list: [ '/aaa', '/bbb' ]
    fstab_file: '/tmp/fstab'

  tasks:
    - mount:
        src: '{{ item }}'
        name: 'none'
        fstype: 'swap'
        opts: 'sw'
        state: 'present'
        fstab: '{{ fstab_file }}'
      with_items: file_list

    - mount:
        src: '{{ item }}'
        name: 'none'
        fstype: 'swap'
        opts: 'sw'
        state: 'present'
        fstab: '{{ fstab_file }}'
      with_items: file_list
```

##### EXPECTED RESULTS

Two entries are created in specified fstab file, there are no changes in the second task.

##### ACTUAL RESULTS

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [mount ] **************************************************************** 
changed: [localhost] => (item=/aaa)
changed: [localhost] => (item=/bbb)

TASK: [mount ] **************************************************************** 
changed: [localhost] => (item=/aaa)
changed: [localhost] => (item=/bbb)

PLAY RECAP ******************************************************************** 
mount  ------------------------------------------------------------------ 0.14s
localhost                  : ok=3    changed=2    unreachable=0    failed=0   
```

Copied from original issue: ansible/ansible-modules-core#2291

**Comment by ansibot** [comment]
From @robynbergeron on 2015-10-16T10:20:38Z

[module: system/mount.py]

**Comment by ansibot** [comment]
From @robynbergeron on 2015-10-16T10:20:38Z

Hi @drybjed -- thanks for submitting this bug report.

@ansible/core team -- pinging you to let you know about this bug report for the mount module.

Thanks!

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
@drybjed Please could you verify this is still an issue in the latest Ansible?

`need_info`

**Comment by drybjed** [comment]
@jtyr: I just checked both on Ansible `stable-2.3` and `devel` branches (`stable-2.4` seems to be currently broken) and the module still changes the entries all the time. You can try with this playbook, it shouldn't do any permanent damage to your system:
```yaml
---

- hosts: localhost

  vars:
    file_list: [ '/aaa', '/bbb' ]
    fstab_file: '/tmp/fstab'

  tasks:
    - mount:
        src: '{{ item }}'
        name: 'none'
        fstype: 'swap'
        opts: 'sw'
        state: 'present'
        fstab: '{{ fstab_file }}'
      with_items: '{{ file_list }}'

    - mount:
        src: '{{ item }}'
        name: 'none'
        fstype: 'swap'
        opts: 'sw'
        state: 'present'
        fstab: '{{ fstab_file }}'
      with_items: '{{ file_list }}'
```
