### ISSUE TITLE
rules_egress empty array not taken into account

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30038]
From @glnds on 2015-09-25T09:44:53Z
##### Issue Type:

Bug Report
##### Component Name:

ec2_group
##### Ansible Version:

1.9.3
##### Summary:

[ec_group module](http://docs.ansible.com/ansible/ec2_group_module.html) empty egress rules array not taken into account

> rules_egress:
> List of firewall outbound rules to enforce in this group (see example). If none are supplied, a default all-out rule is assumed. **If an empty list is supplied, no outbound rules will be enabled.**

If an empty list is supplied there is still a default egress rule created on AWS allowing all outbound traffic.

See also:
http://grokbase.com/t/gg/ansible-project/155c5za9aq/ec2-group-does-not-honour-empty-rules-egress
##### Steps To Reproduce:

```
- name: ensure the rds security group is present
  ec2_group:
    name: RDSSG
    description: RDS security group
    vpc_id: "{{ vpc.vpc_id }}"
    profile: "{{ profile }}"
    region: "{{ region }}"
    rules:
        - proto: tcp
          from_port: 3306
          to_port: 3306
          cidr_ip: 0.0.0.0/0
    rules_egress: []
    purge_rules_egress: true
register: rds_sg
```
##### Expected Results:

No outbound rules in my security group on AWS.
##### Actual Results:

One outbound rule allowing all traffic.

Copied from original issue: ansible/ansible-modules-core#2153

**Comment by ansibot** [comment]
From @lcasey001 on 2015-09-25T09:44:53Z

I submitted this via https://github.com/ansible/ansible/issues/11249 as well.  https://github.com/ansible/ansible/issues/7309 actually prevented this. It adds that default allow all rule. We were forced to create a bogus egress rule to make this work for us.

**Comment by ansibot** [comment]
From @robynbergeron on 2015-09-25T09:44:53Z

Greetings, @glnds -- thanks for submitting this bug report, and thanks to @lcasey001 as well for the additional background.

@adq --  thanks in advance for taking a look at this bug report and for your ongoing work in maintaining this module.

**Comment by ansibot** [comment]
From @robynbergeron on 2015-09-25T09:44:53Z

[module: cloud/amazon/ec_group.py]

**Comment by ansibot** [comment]
cc @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Everspace** [comment]
This is still happening even as of commit  d877c146ab750c0f1505b4180e4170163d854fb5 , and also bizarrely if you remove the rude outbound rule within the console, you get an "ok" on rerun.

```yaml
- name: Create group for office SSH access
  future_ec2_group:
    name: AllowOfficeSSH
    description: Allow SSH access to machines from the office
    region: "{{region}}"
    purge_rules: yes
    purge_rules_egress: yes
    rules:
    - rule_desc: Office SSH Access
      proto: tcp
      ports: 22
      cidr_ip: "{{ips}}"
```

A run:

`changed: [127.0.0.1] =>`
```json
{
    "changed": true,
    "invocation": {
        "module_args": {
            "rules_egress": null,
        }
    },
    "ip_permissions_egress": [
        {
            "ip_protocol": "-1",
            "ip_ranges": [
                {
                    "cidr_ip": "0.0.0.0/0"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "user_id_group_pairs": []
        }
    ]
}
```

Remove the rule in the web console and rerun...

`ok: [127.0.0.1] => `

```json
{
    "changed": false,
    "invocation": {
        "module_args": {
            "rules_egress": null,
        }
    },
    "ip_permissions_egress": []
}
```
