### ISSUE TITLE
lineinfile not insertafter 'EOF' if line presents in file

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30046]
From @nghnam on 2015-09-12T04:42:06Z
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
linefinfile module

##### ANSIBLE VERSION 
1.9.3

##### ANSIBLE CONFIGURATION 
default

##### OS / ENVIRONMENT
Ubuntu 14.04

##### SUMMARY

`lineinfile` won't insert line after EOF if line has presented in file. 

##### STEPS TO REPRODUCE

An example ansible task:

```
- name: test insertafter EOF
  lineinfile:
    dest: /tmp/test.txt
    line: "{{ item.line }}"
    insertafter: 'EOF'
    state: present
  with_items: 
    - { line: Hello Ansible }
```

My /tmp/test.txt:

```
Hello Ansible
=============
```

##### EXPECTED RESULTS

```
Hello Ansible
=============
Hello Ansible
```

##### ACTUAL RESULTS

```
TASK: [test insertafter EOF] ************************************************** 
ok: [localhost] => (item={'line': 'Hello Ansible'}) => {"backup": "", "changed": false, "item": {"line": "Hello Ansible"}, "msg": ""}

PLAY RECAP ******************************************************************** 
localhost                  : ok=1    changed=0    unreachable=0    failed=0 
```

And /tmp/test.txt not changed.

In lineinfile.py,
https://github.com/ansible/ansible-modules-core/blob/devel/files/lineinfile.py#L233

The condition  `if index[0] != -1:` checked regexp matched a line in file, but it did not check regexp is defined or not. 
I changed this line into `if index[0] != -1 and regexp is not None:` and re-executed the playbook.  It worked as expected.

Copied from original issue: ansible/ansible-modules-core#2054
