### ISSUE TITLE
Docker create new container even when state=started

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30058]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

2.1

##### SUMMARY

From @bocharsky-bw on 2015-08-19T13:38:38Z
Try to describe problem with next example.

I create new container manually and name it as `elasticsearch.container`. Then I push some data to elasticsearch index.

When I do `$ docker stop elasticsearch.container` and then `$ docker start elasticsearch.container` - my data in this container restore and I could use it after container starts.

If I do the same things with ansible playbook, ansible recreate new container when it stops. I mean, if I do `$ docker stop elasticsearch.container` and then run playbook with next instructions:

``` yaml
  tasks:
    - name: elasticsearch container
      docker:
        image: elasticsearch:latest
        name: elasticsearch.container
        state: started
        ports:
          - "9200:9200"
          - "9300:9300"
```

I have new container without my previous data. I want to emphasize attention on `state: started`.

Does it normal `docker_module` behavior for this state? And why my data DO NOT lost when I simply execute `$ docker start elasticsearch.container` command?

Copied from original issue: ansible/ansible-modules-core#1938
