### ISSUE TITLE
Docker module will create/stop the container even if when expression is negative

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30063]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

1.9.2

##### SUMMARY

From @dgolja on 2015-08-16T15:05:19Z
Hello,

so I noticed that docker module will always create/stop the image even if the "when" expression is false. That's a problem if you have two similar task using the same container name. 

So for example if we have the below snippet and we run it with storage_type != 'local':

```
- name: Registry container local backend
  sudo: True
  when: storage_type == 'local'
  docker:
    name: registry
    image: "registry:{{ version }}"
    state: started
    ports:
      - "5000:5000"
    restart_policy: always
    volumes:
      - "{{ storage_path }}:/var/lib/registry"
      - /etc/docker-registry/config.yml:/etc/docker/registry/config.yml

- name: Registry container remote backend
  sudo: True
  when: storage_type != 'local'
  docker:
    name: registry
    image: "registry:{{ version }}"
    state: started
    ports:
      - "5000:5000"
    restart_policy: always
    volumes:
      - /etc/docker-registry/config.yml:/etc/docker/registry/config.yml
```

The first task will create the container and stop it, so that means the second task will always fail with something like:

```
failed: [X.X.X.X] => {"changed": false, "failed": true}
msg: Docker API Error: Conflict. The name "registry" is already in use by container fd41405e7458. You have to delete (or rename) that container to be able to reuse that name.
```

I would expect that the container with the first task will never be created, because the task get skipped. 

```
docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

```
ansible --version
ansible 1.9.2
  configured module search path = None
```

```
pip freeze | grep docker
docker-py==1.2.3
```

Copied from original issue: ansible/ansible-modules-core#1919
