### ISSUE TITLE
Docker module fails to create containers with docker 1.7.1 (cannot unmarshal string)

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30066]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

2.1

##### SUMMARY

From @WishCow on 2015-08-10T18:07:23Z
Running ansible 1.9.2 on Arch, trying to create a container with:

```
- name: Ensure the docker container is present
  docker:
    email: "{{ syncthing_registry.email }}"
    password: "{{ syncthing_registry.password }}"
    pull: always
    name: "{{ syncthing_container_name }}"
    image: "{{ syncthing_image_name }}"
    state: reloaded
    command: syncthing
    volumes: "{{ [ syncthing_outer_config ~ ':' ~ syncthing_inner_config ] | union(syncthing_mounts) }}"
    ports: "{{ syncthing_port_mappings }}"
    restart_policy: always
    dns: 8.8.8.8
```

Using docker 1.7.1, this results in:

```
TASK: [syncthing | Ensure the docker container is present] ******************** 
failed: [myhost] => {"changed": true, "failed": true}
msg: Docker API Error: json: cannot unmarshal string into Go value of type []string
```

Looking at the logs of the docker daemon with `systemctl status docker` shows:

```
Aug 10 19:59:26 myhost docker[24054]: time="2015-08-10T19:59:26.179563155+02:00" level=info msg="POST /v1.17/containers/b3f6bc24865825c7c9a42a193a88a361a55a417910c78321fa49cc4074dd734a/start"
Aug 10 19:59:26 myhost docker[24054]: time="2015-08-10T19:59:26.179650069+02:00" level=error msg="Handler for POST /containers/{name:.*}/start returned error: json: cannot unmarshal string into Go value of type []string"
Aug 10 19:59:26 myhost docker[24054]: time="2015-08-10T19:59:26.179676277+02:00" level=error msg="HTTP Error" err="json: cannot unmarshal string into Go value of type []string" statusCode=500
```

Downgrading docker to 1.6.2 fixes the issue.

Copied from original issue: ansible/ansible-modules-core#1896

**Comment by ansibot** [comment]
From @WishCow on 2015-08-10T18:07:23Z

Experiencing this with docker 1.8.1 too.

**Comment by ansibot** [comment]
From @caljess599 on 2015-08-10T18:07:23Z

Running Ansible 1.9.2; can confirm no errors on Docker 1.6.2.
As for the error on 1.7.1, we noticed that the marshaling error actually occurs AFTER the container is started, so that it may be possible (as a temporary workaround!) to ignore errors on these tasks and complete the run of our role without any adverse impact.

**Comment by ansibot** [comment]
From @WishCow on 2015-08-10T18:07:23Z

I can't confirm 100%, but I remember the container not starting at all. Running the playbook, and then inspecting `docker ps` revealed no running containers. It _might_ be possible that the containers were created, just not started, but I haven't checked that.

**Comment by ansibot** [comment]
From @caljess599 on 2015-08-10T18:07:23Z

Yes, sorry--you are right WishCow. It will CREATE the container but it never runs it. Ignoring errors won't help us. For now we have pinned our Docker version at 1.6.2.

**Comment by ansibot** [comment]
From @olvesh on 2015-08-10T18:07:23Z

Anyone found out what exactly triggers this bug? Are there any known workarounds?

I am getting a bit tired with all kinds of paper cuts with the docker module. Some of my playbooks and roles works, but some dont. Performing an attempted upgrade with this bug leaves me with the container deleted. Specifically this fails:

``` yaml
- name: Install Logspout docker image
  docker:
    name:     logspout
    image:    gliderlabs/logspout:master
    pull:     "{{ docker_pull | d('always') }}"
    state:    reloaded
    restart_policy: always
    ports:
      - 8000:80
    command: syslog://syslog.logstash.service.consul:5000

    #Because: https://github.com/gliderlabs/logspout/issues/47 and since we have a consul-agent locally:
    dns: "{{ ansible_docker0['ipv4']['address'] }}"
    env:
      DEBUG: true
      SERVICE_NAME: logspout
    volumes:       
      - /var/run/docker.sock:/tmp/docker.sock
```

**Comment by ansibot** [comment]
From @olvesh on 2015-08-10T18:07:23Z

Workaround is putting the `dns:` setting as array, probably works as well with a vanilla yaml array as well.

The http://docs.ansible.com/ansible/docker_module.html docs says that it is a list, but it has worked with a single value earlier.
Guess some release tweaked how that works.

``` yaml
- name: Install Logspout docker image
  docker:
    name:     logspout
    image:    gliderlabs/logspout:master
    pull:     "{{ docker_pull | d('always') }}"
    state:    reloaded
    restart_policy: always
    ports:
      - 8000:80
    command: syslog://syslog.logstash.service.consul:5000

    #Because: https://github.com/gliderlabs/logspout/issues/47 and since we have a consul-agent locally:
    dns: ["{{ ansible_docker0['ipv4']['address'] }}"]
    env:
      DEBUG: true
      SERVICE_NAME: logspout
    volumes:       
      - /var/run/docker.sock:/tmp/docker.sock
```
