### ISSUE TITLE
iam_policy doesn't update policies

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30071]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

iam_policy module

##### ANSIBLE VERSION

1.9.2

##### SUMMARY

From @garthk on 2015-08-03T03:00:04Z
- Run a playbook using `iam_policy`
- Observe in EC2 IAM console the group has the policy with the correct document
- Edit the policy document a) in EC2 IAM console, OR b) in the local file
- Re-run the playbook
- Observe Ansible reports `ok`, not `changed`
- Observe either a) the local file is not re-applied, OR b) the group policy is not updated

This is with `iam.py` and `iam_policy.py` from around 1268a83eb7 dropped into `library/cloud/amazon` and run under Ansible 1.9.2.

```
- name: "IAM groups"
  iam:
    state: present
    iam_type: group
    name: "{{ item }}"
  with_items:
  - "{{ worker_name }}"
  - "{{ worker_control_name }}"

- name: "IAM policies"
  iam_policy:
    state: present
    iam_type: group
    iam_name: "{{ item.iam_name }}"
    policy_name: "{{ item.policy_name }}"
    policy_document: "{{ item.policy_document }}"
  with_items:
  -
    iam_name: "{{ worker_name }}"
    policy_name: "{{ worker_name }}"
    policy_document: "{{ worker_policy_file }}"
  -
    iam_name: "{{ worker_control_name }}"
    policy_name: "{{ worker_control_name }}"
    policy_document: "{{ worker_control_policy_file }}"
```

Copied from original issue: ansible/ansible-modules-core#1855
