### ISSUE TITLE
Wording of hg module documentation misleading

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30073]
##### ISSUE TYPE

Documentation Report

##### COMPONENT NAME

hg module

##### ANSIBLE VERSION

ansible 2.0.0

##### CONFIGURATION

Not relevant for the ticket.

##### OS / ENVIRONMENT

Ubuntu 14.04 fully updated.

##### SUMMARY

The current documentation for the `hg` module in its synopsis states:

> Manages Mercurial (hg) repositories. Supports SSH, HTTP/S and local address.

I was led to use this module because I saw the following warning in my registered result:

```
"warnings": ["Consider using hg module rather than running hg"]
```

This seems to suggest that I should be able to **push** to a remote repository. However, the documentation only mentions cloning, not pushing or pulling.

##### STEPS TO REPRODUCE

Using the following playbook

```

---
- name: Update repos
  hosts: lxchost
  sudo: True
  connection: local
  gather_facts: False
  tasks:
    - name: Push
      hg: repo="/root/repo" dest="ssh://{{item}}/repo"
      with_items: "{{groups['enabled']}}"
```

and existing repositories on the hosts in group `enabled`, run the playbook.

##### EXPECTED RESULTS

I expected it to push the changes. After all the warning pointed me to the `hg` module as a response to my attempt to push to the hosts using the `command` module.

##### ACTUAL RESULTS

```
TASK: [Push] *******************************************
failed: [lxchost] => (item=machine1) => {"failed": true, "item": "machine1", "playbook": "playbooks/push.yml", "role": null, "task": "Push"}
msg: abort: repository .dotfiles already exists!
abort: could not create remote repo!

failed: [lxchost] => (item=machine2) => {"failed": true, "item": "machine2", "playbook": "playbooks/push.yml", "role": null, "task": "Push"}
msg: abort: repository .dotfiles already exists!
abort: could not create remote repo!
```

Ansible fails, telling me that the remote repo exists. Right, so how do I push changes rather than clone a fresh copy?

PS: accidentally [opened in the ansible repo](https://github.com/ansible/ansible/issues/11824) before.

Copied from original issue: ansible/ansible-modules-core#1851
