### ISSUE TITLE
Mount module is not idempotent when passno and dump are specified as integers

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30070]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

mount module

##### ANSIBLE VERSION

2.1

##### SUMMARY

From @tersmitten on 2015-08-05T09:30:53Z
```
TASK: [swapfile | add swapfile to /etc/fstab] ********************************* 
<127.0.0.1> REMOTE_MODULE mount opts=sw state=present fstype=swap name=none src=/swap
changed: [ubuntu-1404] => {"changed": true, "dump": 0, "fstab": "/etc/fstab", "fstype": "swap", "name": "none", "opts": "sw", "passno": 0, "src": "/swap"}
```

This task is always `changed`. It's probably because of the lack of `name`.

Copied from original issue: ansible/ansible-modules-core#1868

**Comment by ansibot** [comment]
From @sysadmin75 on 2015-08-05T09:30:53Z

I'm not able to reproduce.

ansible version: devel e7b5cb8
Management Host: Centos6  python 2.6.6
Managed Node: Centos6 python 2.6.6

I used your output above to get the task options you used. Forgive me if I have missed some.

```
cat mount.yml
- name: swap file
  hosts: all
  gather_facts: no
  tasks:
    - mount: name=none state=present fstype=swap src=/swapfile dump=0 opts=sw passno=0
```

**Comment by ansibot** [comment]
From @tersmitten on 2015-08-05T09:30:53Z

```
Ansible version: All up to 1.9.2
Management host: Ubuntu 14.04
Managed Node:    Ubuntu (all), Debian (all)
```

I used the `dict` syntax in my playbook, and called it in [this role](https://github.com/Oefenweb/ansible-swapfile).

**Comment by ansibot** [comment]
From @ypid on 2015-08-05T09:30:53Z

I am able to reproduce this as well. Also note that the `/etc/fstab` file does not actually change (tracked with etckeeper).

**Comment by ansibot** [comment]
From @tersmitten on 2015-08-05T09:30:53Z

Changing `passno` and `dump` to strings fixes the problem for me.

```
- name: add swapfile to /etc/fstab
  mount:
    name: none
    src: "{{ swapfile_file }}"
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present
```

I don't mind fixing the problem, but I'm not exactly sure how. Casting `passno` and `dump` in [line 121](https://github.com/ansible/ansible-modules-core/blob/devel/system/mount.py#L121) should fix the problem, but I'm not sure that can be done safely. @bcoca Can you confirm this?

**Comment by ansibot** [comment]
From @clonedagain on 2015-08-05T09:30:53Z

I can reproduce the problem with ext4 mount points so it's not only swap files.
Using strings for `passno` and `dump` fixed it for me too.

**Comment by ansibot** [comment]
From @aocole on 2015-08-05T09:30:53Z

##### Issue Type: Bug Report

##### Ansible Version:

```
ansible 2.0.0 (devel da3087ffc4) last updated 2015/11/04 23:10:01 (GMT +000)
  lib/ansible/modules/core: (detached HEAD e318be30ff) last updated 2015/11/02 19:56:43 (GMT +000)
  lib/ansible/modules/extras: (detached HEAD 80f198a82f) last updated 2015/11/02 19:56:45 (GMT +000)
  config file = /home/ubuntu/ansible.cfg
  configured module search path = None
```

##### Ansible Configuration:

No added config

##### Environment:

Ubuntu 14.04.3 all around

##### Summary:

If 'dump' or 'passno' are specified as integer values in the YAML, the mount module will fail with the error "AttributeError: 'int' object has no attribute 'replace'". I believe this is related/identical to #1861.

##### Steps To Reproduce:

``` yaml
  - mount:
      src: /dev/sdb1
      name: /data
      fstype: ext4
      opts: defaults,usrquota,grpquota
      dump: 0
      passno: 2
      state: mounted
```

##### Expected Results:

```
changed: [hostname]
```

##### Actual Results:

```
fatal: [992e7421-5659-4b44-a977-0d6cd92c27b0]: FAILED! => {"changed": false, "failed": true, "msg": "Traceback (most recent call last):\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1446678707.73-208842130645223/mount\", line 2294, in <module>\r\n    main()\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1446678707.73-208842130645223/mount\", line 354, in main\r\n    name, changed = set_mount(module, **args)\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1446678707.73-208842130645223/mount\", line 134, in set_mount\r\n    escaped_args = dict([(k, _escape_fstab(v)) for k, v in args.iteritems()])\r\n  File \"/home/ubuntu/.ansible/tmp/ansible-tmp-1446678707.73-208842130645223/mount\", line 110, in _escape_fstab\r\n    return v.replace('\\\\', '\\\\134').replace(' ', '\\\\040').replace('&', '\\\\046')\r\nAttributeError: 'int' object has no attribute 'replace'\r\n", "parsed": false}
```

**Comment by ansibot** [comment]
From @Ilyes512 on 2015-08-05T09:30:53Z

I had the fallowing:

``` yaml
- name: Swap | Write swap entry in fstab
  sudo: yes
  mount:
    name: none
    src: "{{ swap_location }}"
    fstype: swap
    opts: sw
    passno: 0
    dump: 0
    state: present
```

The above would always be "changed". Changed it to strings did fix it for me:

``` yaml
- name: Swap | Write swap entry in fstab
  sudo: yes
  mount:
    name: none
    src: "{{ swap_location }}"
    fstype: swap
    opts: sw
    passno: '0'
    dump: '0'
    state: present
```
