### ISSUE TITLE
Error when using Yum to install packages from file

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30074]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

yum module

##### ANSIBLE VERSION

ansible 1.9.2

##### CONFIGURATION

Fresh install.

##### OS / ENVIRONMENT

Tested on an OEL6.6 ansible host and an OEL7.1 host.  Managing a OEL5.11 box. (OEL = Oracles variant of RHEL)

##### SUMMARY

Getting an error when attempting to use the yum module to install a package via a local file.

##### STEPS TO REPRODUCE

Copy a .rpm out in /tmp.  I used the epel repo installer, but I've had it occur with completely different packages.  Then attempt to install it with the yum package and the disk path to the file.

``` yaml
[root@localhost ansible]# cat bugtest.yaml 

---
- name: Bug reproduction
  hosts: all
  tasks: 
  - name: Install new packages
    yum:
      state=present
      name=/tmp/epel-release-latest-5.noarch.rpm

[root@localhost ansible]# ansible-playbook -i dummy.hosts bugtest.yaml

PLAY [Bug reproduction] ******************************************************* 

GATHERING FACTS *************************************************************** 
ok: [dummy]

TASK: [Install new packages] ************************************************** 
failed: [dummy] => {"failed": true, "parsed": false}
{"msg": "warning: rpmts_HdrFromFdno: Header V3 DSA signature: NOKEY, key ID 217521f6\n\n\nPublic key for epel-release-latest-5.noarch.rpm is not installed\n", "changed": true, "results": ["Loaded plugins: security\nSetting up Install Process\nExamining /tmp/epel-release-latest-5.noarch.rpm: epel-release-5-4.noarch\nMarking /tmp/epel-release-latest-5.noarch.rpm to be installed\nResolving Dependencies\n--> Running transaction check\n---> Package epel-release.noarch 0:5-4 set to be updated\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package          Arch       Version    Repository                         Size\n================================================================================\nInstalling:\n epel-release     noarch     5-4        /epel-release-latest-5.noarch      0.0 \n\nTransaction Summary\n================================================================================\nInstall       1 Package(s)\nUpgrade       0 Package(s)\n\nDownloading Packages:\n"], "rc": 1}
Exception exceptions.AttributeError: "'NoneType' object has no attribute 'unshare_data'" in <bound method YumBase.__del__ of <yum.YumBase object at 0xa847c90>> ignored
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to dummy closed.


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/bugtest.yaml.retry

dummy                      : ok=1    changed=0    unreachable=0    failed=1
```

##### EXPECTED RESULTS

Package installed, no error, playbook continuing as normal.

##### ACTUAL RESULTS

The play errors out with `Exception exceptions.AttributeError: "'NoneType' object has no attribute 'unshare_data'" in <bound method YumBase.__del__ of <yum.YumBase object at 0xa847c90>> ignored`, and the package is never installed.  If you have the package already properly installed, it gives a slightly less output, while still including the error.
###### Example with packages already installed on target:

``` yaml
TASK: [Install new packages] ************************************************** 
failed: [dummy] => {"failed": true, "parsed": false}
{"msg": "", "changed": false, "results": [], "rc": 0}
Exception exceptions.AttributeError: "'NoneType' object has no attribute 'unshare_data'" in <bound method YumBase.__del__ of <yum.YumBase object at 0x3fa4c90>> ignored
OpenSSH_6.6.1, OpenSSL 1.0.1e-fips 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to dummy closed.
```

Copied from original issue: ansible/ansible-modules-core#1849
