### ISSUE TITLE
Feature Idea: Allow service module to have more states

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30096]
##### ISSUE TYPE

Feature Idea

##### COMPONENT NAME

service module

##### ANSIBLE VERSION

2.3

##### SUMMARY

From @jerrac on 2015-06-26T17:05:54Z
Many init scripts offer more options than just start/stop/restart/reload. For example:

```
Usage: /etc/init.d/iptables-persistent {start|restart|reload|force-reload|save|flush}
Usage: apache2 {start|stop|graceful-stop|restart|reload|force-reload|start-htcacheclean|stop-htcacheclean}
```

In my iptables role, I really need to be able to run the flush command. But I can't do that with the service module. I'll just use a shell/command task, but it would be nice if I could tell the service module what option to use.

Something like:

```
- name: flush iptables
  service:
    name: iptables-persistent
    state: flushed
    option: flush
    enabled: yes

- name: start htcacheclean
  service:
    name: apache2
    state: started
    option: start-htcacheclean
    enabled: yes
```

Copied from original issue: ansible/ansible-modules-core#1616

**Comment by ansibot** [comment]
From @bcoca on 2015-06-26T17:05:54Z

i'm thinking a state: custom, that just passes the arguments: field blindly and does no existing state checks.

```
- name: flush iptables
  service:
    name: iptables-persistent
    state: custom
    arguments: flush
    enabled: yes
```

no new options, just some new logic for the new state
