### ISSUE TITLE
Unable to mount multiple swap files 

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30090]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

mount module

##### ANSIBLE VERSION

1.9.2

##### CONFIGURATION

[defaults]
inventory = ec2.py
private_key_file = <private_key_path>
remote_user = <remote_user>
roles_path = ./roles
host_key_checking = False
nocows = 1
vault_password_file = <vault_password_path>

##### OS / ENVIRONMENT

Running Ansible from OSX 10.10.1
OS being managed is Amazon Linux 2015.03

##### SUMMARY

When using the mount module to create/mount two separate swap files, only the latter swap file gets written to /etc/fstab

##### STEPS TO REPRODUCE

Run a task file with the following (Note that /root/swapfile1 and /root/swapfile2 should already be configured to be used as swap with dd and mkswap)

```
- mount: name=none
         src=/root/swapfile1
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  sudo: true
- mount: name=none
         src=/root/swapfile2
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  sudo: true
```

##### EXPECTED RESULTS

The following lines in /etc/fstab

```
/root/swapfile1 none swap sw 0 0
/root/swapfile2 none swap sw 0 0
```

##### ACTUAL RESULTS

```
/root/swapfile2 none swap sw 0 0
```

Copied from original issue: ansible/ansible-modules-core#1691

**Comment by ansibot** [comment]
From @mcreenan on 2015-07-09T13:40:10Z

Here is a more complete test case.

For testing, I edited my inventory to contain exactly 1 server which I created for this test case.

_configure-swap-files.yml_

``` yaml
---
- hosts: all
  tasks:
  - include: swap.yml path=/swapfile1 size_in_mb=100
  - include: swap.yml path=/swapfile2 size_in_mb=100
```

_swap.yml_

``` yaml
---
- name: Create empty swap files
  command: dd if=/dev/zero of={{ path }} bs=1M count={{ size_in_mb }}
           creates="{{ path }}"
  sudo: true

- name: Change swap file permissions
  file: path="{{ path }}"
        owner=root
        group=root
        mode=0600
  sudo: true

- name: "Check swap file type"
  command: file {{ path }}
  register: swapfile
  changed_when: false
  sudo: true

- name: Make swap file
  command: "sudo mkswap {{ path }}"
  when: swapfile.stdout.find('swap file') == -1
  sudo: true

- name: Write swap entry in fstab
  mount: name=none
         src={{ path }}
         fstype=swap
         opts=sw
         passno=0
         dump=0
         state=present
  sudo: true

- name: Enable swap
  command: "swapon {{ path }}"
  when: ansible_swaptotal_mb <= 0
  sudo: true
```

Here's the output when I ran the configure-swap-files.yml playbook:

```
╰→ ansible-playbook configure-swap-files.yml

PLAY [all] ********************************************************************

GATHERING FACTS ***************************************************************
ok: [<IP ADDRESS>]

TASK: [Create empty swap files] ***********************************************
changed: [<IP ADDRESS>]

TASK: [Change swap file permissions] ******************************************
changed: [<IP ADDRESS>]

TASK: [Check extra swap file type] ********************************************
ok: [<IP ADDRESS>]

TASK: [Make extra swap file] **************************************************
changed: [<IP ADDRESS>]

TASK: [Write extra swap entry in fstab] ***************************************
changed: [<IP ADDRESS>]

TASK: [Mount extra swap] ******************************************************
changed: [<IP ADDRESS>]

TASK: [Create empty swap files] ***********************************************
changed: [<IP ADDRESS>]

TASK: [Change swap file permissions] ******************************************
changed: [<IP ADDRESS>]

TASK: [Check swap file type] ********************************************
ok: [<IP ADDRESS>]

TASK: [Make swap file] **************************************************
changed: [<IP ADDRESS>]

TASK: [Write swap entry in fstab] ***************************************
changed: [<IP ADDRESS>]

TASK: [Enable swap] ******************************************************
changed: [<IP ADDRESS>]

PLAY RECAP ********************************************************************
<IP ADDRESS>             : ok=13   changed=10   unreachable=0    failed=0
```

Here's the /etc/fstab file:

```
#
LABEL=/     /           ext4    defaults,noatime  1   1
tmpfs       /dev/shm    tmpfs   defaults        0   0
devpts      /dev/pts    devpts  gid=5,mode=620  0   0
sysfs       /sys        sysfs   defaults        0   0
proc        /proc       proc    defaults        0   0
/swapfile2 none swap sw 0 0
```

**Comment by ansibot** [comment]
From @mcreenan on 2015-07-09T13:40:10Z

I'm having trouble running tests locally, but I think a possible fix for this is in system/mount.py, after line 141 (before the code that checks to see if the mount is different):

``` python

        # Swap doesn't have a name, so instead of comparing the name to determine if it is
        # different, compare the swap path
        if ld['fstype'] == 'swap' and ld['src'] != args['src']:
            to_write.append(line)
            continue
```

**Comment by ansibot** [comment]
From @yamatt on 2015-07-09T13:40:10Z

I have a similar issue when adding one swap and removing another. I think this due to the uniqueness of a line being based upon the `name` param. Though haven't tested this.

**Comment by ansibot** [comment]
From @mcreenan on 2015-07-09T13:40:10Z

Any update on this? This is causing issues with our setup where we have servers with multiple swap files.

**Comment by ansibot** [comment]
From @mcreenan on 2015-07-09T13:40:10Z

Any update?  Working around this for now, but it would be nice to not have to.

**Comment by ansibot** [comment]
From @mscherer on 2015-07-09T13:40:10Z

So I had to look at the mount module, and I wonder if this wasn't fixed by 25585937 , could people verify it fix that for them ?

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
@mcreenan Please could you verify this is still an issue in the latest Ansible?

`needs_info`

**Comment by kees-closed** [comment]
@jtyr you tell me if this is resolved :) Or I am doing something wrong or it's still unresolved. I had this code commented for a long while because it didn't work. I enabled it and I came across the following.

The task:
```
- name: insert swap mount line in fstab
  mount: name=swap src=LABEL={{ item }} fstype=swap opts=defaults,nofail,pri=50 state=mounted
  with_items:
    - swap1
    - swap2
  when: ansible_hostname == "server"
  tags:
    - swap
    - mounts
```

Output + errors:
```
TASK [common : insert swap mount line in fstab] *****************************************************************************************
failed: [server.home.lan] (item=swap1) => {"changed": false, "failed": true, "item": "swap1", "msg": "Error mounting swap: mount: unknown filesystem type 'swap'\n"}
failed: [server.home.lan] (item=swap2) => {"changed": false, "failed": true, "item": "swap2", "msg": "Error mounting swap: mount: unknown filesystem type 'swap'\n"}
        to retry, use: --limit @/home/user/git/ansible/playbooks.retry                                                               

PLAY RECAP ******************************************************************************************************************************
server.home.lan           : ok=1    changed=0    unreachable=0    failed=1  

```

It did add only one entry in fstab:
`LABEL=swap2 swap swap defaults,nofail,pri=50 0 0`

There should be 2 of course (swap1 and swap2).

**Comment by ansibot** [comment]
@ansibot This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ansibot This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kees-closed** [comment]
Any progress on this issue?

**Comment by jtyr** [comment]
Please could you try to unmount the swap before running Ansible? If that still doesn't work, please try to mount it manually from the command line:

```shell
mount -L swap1 -t swap - o defaults,nofail,pri=50
```

**Comment by kees-closed** [comment]
@jtyr I get the impression it does work for you? Can you confirm that and share your Ansible code?

It still fails for me... It now even fails with one swap mount. Now using:
```
ansible 2.4.3.0
python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

```
- name: insert swap mount line in fstab
  mount: name=swap src=LABEL=swap2 fstype=swap opts=defaults,nofail,pri=50 state=mounted
  tags:
    - swap
    - mounts

```

`FAILED! => {"changed": false, "msg": "Error mounting swap: mount: unknown filesystem type 'swap'\n"}
`
