### ISSUE TITLE
VMWARE_VM_SHELL not passing along command

### ISSUE THREAD

**Issue by rewilliamso** [ansible/ansible#30109]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_vm_shell
n
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Sep  5 2016, 02:30:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-9)]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Oracle Linux 6.8
##### SUMMARY

I am using the vmware_vm_shell module and passing in a sed command to change the network configuration file. I am not seeing any error when running -vvv mode. The script passes successfully but the ip is not being changed.
##### STEPS TO REPRODUCE

```
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1
  vars:
    app_name: "testvmappsetip"
    server_ip: "10.10.10.245"
    vcenter_username: "user"
    vcenter_hostname: "vsphere.example.com"
    app_datacenter: "Datacenter - City, MO"
    cluster: "Datacenter - Production_Intel"
    vm_root_user: "root"
  vars_prompt:
  - name: "vcenter_password"
    prompt: "Enter Password"
    private: yes
  tasks:
  - name: "PROVISION | Create VM from Template"
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "false"
      datacenter: "{{ app_datacenter }}"
      cluster: "{{ cluster }}"
      state: "poweredon"
      name: "{{ app_name }}"
      template: app_default_official1

  - name: "Network | Change the IP address"
    local_action:
      module: vmware_vm_shell
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username}}"
      password: "{{ vcenter_password }}"
      vm_id: "{{ app_name }}"
      vm_username: "{{ vm_root_user }}"
      vm_password: password@123
      vm_shell: /bin/sed
      vm_shell_args: " -i 's/10.10.10.244/{{ server_ip }}/' /etc/sysconfig/network-scripts/ifcfg-eth0"
      vm_shell: /sbin/reboot

```

##### EXPECTED RESULTS

I expected the sed command to change the necessary line in the interface file.
##### ACTUAL RESULTS

The server boots up with original ip in interface file which is 10.10.10.244. The IP should be 10.10.10.245.

```

```
