### ISSUE TITLE
docker Ansible module does not start properly docker data containers

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30107]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

1.9

##### SUMMARY

From @kpatryk on 2015-06-18T17:03:44Z
Hi,

Trying to start Oracle Data Container from Ansible docker core module. Previously there was no container of such name created in the system. After a while waiting the following error is thrown by Ansible:

`failed: [dev] => {"changed": false, "failed": true}
msg: Docker API Error: Conflict. The name "oracledata" is already in use by container ad653e28b23f. You have to delete (or rename) that container to be able to reuse that name.`

The mentioned container has been created by Ansible docker module during first playbook run that has failed. 

Ansible snippet code: 

```
  name: make sure Oracle Data container exists
  docker:
    name: oracledata
    image: "{{ test_registry_host if test_registry_enabled else registry_snapshot_host }}:{{ test_registry_port if test_registry_enabled else registry_snapshot_port }}/oracledata"
    state: present
    command: /bin/true
    insecure_registry: yes
    volumes:
    - "{{ oracle_tablespace_path }}"
  register: status_oracledata
  tags:
    - oracle
    - db-up
```

Remarks:
- Docker Registry 2.0 has been used to store locally images. Ansible pulls image from the private registry (no SSL configured). After task failure I noticed that still process of copying files to the file system has not been completed (image SHA was created under /var/lib/docker/vfs/dir/ directory). Docker version in provisioned machine: 

```
[vagrant@dev ~]$ docker version 
Client version: 1.6.2.el7
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): c3ca5bb/1.6.2
OS/Arch (client): linux/amd64
Server version: 1.6.2.el7
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): c3ca5bb/1.6.2
OS/Arch (server): linux/amd64
```

and docker info:

```
[vagrant@dev ~]$ docker info 
Containers: 2
Images: 33
Storage Driver: devicemapper
 Pool Name: docker-253:1-68054140-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 16.62 GB
 Data Space Total: 107.4 GB
 Data Space Available: 36.41 GB
 Metadata Space Used: 10.08 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.137 GB
 Udev Sync Supported: true
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.93-RHEL7 (2015-01-28)
Execution Driver: native-0.2
Kernel Version: 3.10.0-229.4.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
CPUs: 2
Total Memory: 2.782 GiB
Name: dev
ID: KEFU:NNQN:YEJF:2C2H:64VH:FYTF:C3OI:62T3:UZZ4:7QUQ:OQ2N:3EVW
```
- Second run has been successful. 
- Ansible version in the local machine: 

```
ansible 1.9.1
  configured module search path = None
```
- Python Docker installed dependencies in remote machine:

```
docker-compose (1.3.0rc2)
docker-py (1.2.2)
dockerpty (0.3.4)
```

Copied from original issue: ansible/ansible-modules-core#1550
