### ISSUE TITLE
Adding parameter password to unarchive module

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30100]
##### ISSUE TYPE

feature idea

##### COMPONENT NAME

unarchive module

##### ANSIBLE VERSION

1.9.1

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Password protected archives are not supported by [unarchive module](http://docs.ansible.com/unarchive_module.html). Parameter password should be added.

##### STEPS TO REPRODUCE

Try to unarchive a password protected archive:

``` yaml
- unarchive: >
    src=foo.zip
    dest=/tmp/foo
```

##### EXPECTED RESULTS

Password protected archives are supported by adding parameter password to [unarchive module](http://docs.ansible.com/unarchive_module.html):

``` yaml
- unarchive: >
    src=foo.zip
    dest=/tmp/foo
    password={{ archive_password }}
```

##### ACTUAL RESULTS

Password protected archives are not supported, because parameter password is not available.

Copied from original issue: ansible/ansible-modules-core#1578

**Comment by ansibot** [comment]
From @ansibot on 2015-06-23T06:52:05Z



@dagwieers, @pileofrogs, ping. This issue is waiting on your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
From @dagwieers on 2015-06-23T06:52:05Z

I agree ! Contributions are welcomed.

needs_contributor

**Comment by ansibot** [comment]
From @ansibot on 2015-06-23T06:52:05Z

@pschirch we are unable to validate that "" is an existing ansible module.

We are expecting a component name that matches something that can be found in:
- http://docs.ansible.com/ansible/list_of_all_modules.html

Please revise the component name in the description.
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Alexander198961** [comment]
I am going to fix this

**Comment by Alexander198961** [comment]
@dagwinter can this pr will be reviewed I added -p (password) options so when this option "-P" is available we can unarchive protected zip

**Comment by bcoca** [comment]
FYI, unarchive already supports vault, it will decrypt the archive transparently.

**Comment by sijis** [comment]
Elaborating on the `vault` usage with an example.

This can be a workaround too.

```
---
- hosts: local
  tasks:
    - name: Include secrets.
      include_vars:
        file: secrets.yaml
    - name: Create directory
      file:
        state: directory
        path: /tmp/test-30100
    - name: Unpack zip file.
      no_log: true
      unarchive:
        src: files/test-30100.zip
        dest: /tmp/test-30100
        copy: no
        mode: 0755
        extra_opts:
          - '-P'
          - "{{zip_secret}}"
```

The `no_log` will prevent the password from being logged during a run.
Be aware that the password is in plain text and could potentially be viewed on the target system if a user is running `ps` and/or capture running processes on the system.
