### ISSUE TITLE
authorized_key fails in check mode if user doesn't exist

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30112]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

authorized_key module

##### ANSIBLE VERSION

1.9.1

##### CONFIGURATION

No changes from defaults

##### OS / ENVIRONMENT

Both manager and managed host are Ubuntu 14.04

##### SUMMARY

:**

I have a set of tasks that create local users and manage their authorized_keys file using the authorized_key module. If I run a play containing these tasks in check mode against a brand-new managed host, the user creation is skipped as expected, but the authorized_key module fails because the user doesn't exist:

**

##### STEPS TO REPRODUCE

**
1. Create a play with the following contents:

``` yaml

---
- hosts: localhost
  become: yes
- tasks
    - name: Manage nonexistent user's ssh keys
      authorized_key:
        user: some_user_that_dont_exist
        key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSxrCsbXg6bXZglxShkbSQoOHAU6/1M+K+jRgv8qvQ3sEYDD1s1Rsjj+M5iBS94ZIGEujkMdKm/DjdymMbyQMYm0z8EfMBF6BCuHCwqP89TmXNd01Su9YajMB7C6E8RsbUh7MsMRuLd7EoXqHwCqUVNo8Pywdgcfnfmxy+O/KdyQNyhct8gjxcESlSys4FJiey5saRW3HOvuYcwlC4YGHD1ikW18p09NAhRR1pZf1AKp4gVsBduzONfj3t4rLi/9WW1SoMJAQ5IynK/856GBRy4HX1BtoHxEQfORCVFtPLprHLTfS7nFMoNMyFvYgJsFh90DQxAtYWXFEaRm7zh/Qt
```
1. Execute the playbook with the following command:

```
> ansible-playbook <play> -vvv --check
```

**

##### EXPECTED RESULTS

**

I'm not 100% sure, but they should be successful.

**

##### ACTUAL RESULTS

:**

```
<localhost> ESTABLISH CONNECTION FOR USER: <user>
<localhost> REMOTE_MODULE authorized_key key='ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSxrCsbXg6bXZglxShkbSQoOHAU6/1M+K+jRgv8qvQ3sEYDD1s1Rsjj+M5iBS94ZIGEujkMdKm/DjdymMbyQMYm0z8EfMBF6BCuHCwqP89TmXNd01Su9YajMB7C6E8RsbUh7MsMRuLd7EoXqHwCqUVNo8Pywdgcfnfmxy+O/KdyQNyhct8gjxcESlSys4FJiey5saRW3HOvuYcwlC4YGHD1ikW18p09NAhRR1pZf1AKp4gVsBduzONfj3t4rLi/9WW1SoMJAQ5IynK/856GBRy4HX1BtoHxEQfORCVFtPLprHLTfS7nFMoNMyFvYgJsFh90DQxAtYWXFEaRm7zh/Qt' user=some_user_that_dont_exist CHECKMODE=True
<localhost> EXEC  /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1434226493.05-198959850076873 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1434226493.05-198959850076873 && echo $HOME/.ansible/tmp/ansible-tmp-1434226493.05-198959850076873'
<localhost> PUT /tmp/tmpX7FWmW TO /home/<user>/.ansible/tmp/ansible-tmp-1434226493.05-198959850076873/authorized_key
<localhost> /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=aibazwkoommurhcmfiulnxkntybmefsg] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-aibazwkoommurhcmfiulnxkntybmefsg; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /home/<user>/.ansible/tmp/ansible-tmp-1434226493.05-198959850076873/authorized_key; rm -rf /home/<user>/.ansible/tmp/ansible-tmp-1434226493.05-198959850076873/ >/dev/null 2>&1'"'"''
failed: [localhost] => (item=({'is_admin': True, 'name': 'some_user_that_dont_exist'}, 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSxrCsbXg6bXZglxShkbSQoOHAU6/1M+K+jRgv8qvQ3sEYDD1s1Rsjj+M5iBS94ZIGEujkMdKm/DjdymMbyQMYm0z8EfMBF6BCuHCwqP89TmXNd01Su9YajMB7C6E8RsbUh7MsMRuLd7EoXqHwCqUVNo8Pywdgcfnfmxy+O/KdyQNyhct8gjxcESlSys4FJiey5saRW3HOvuYcwlC4YGHD1ikW18p09NAhRR1pZf1AKp4gVsBduzONfj3t4rLi/9WW1SoMJAQ5IynK/856GBRy4HX1BtoHxEQfORCVFtPLprHLTfS7nFMoNMyFvYgJsFh90DQxAtYWXFEaRm7zh/Qt')) => {"failed": true, "item": [{"is_admin": true, "name": "some_user_that_dont_exist"}, "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDSxrCsbXg6bXZglxShkbSQoOHAU6/1M+K+jRgv8qvQ3sEYDD1s1Rsjj+M5iBS94ZIGEujkMdKm/DjdymMbyQMYm0z8EfMBF6BCuHCwqP89TmXNd01Su9YajMB7C6E8RsbUh7MsMRuLd7EoXqHwCqUVNo8Pywdgcfnfmxy+O/KdyQNyhct8gjxcESlSys4FJiey5saRW3HOvuYcwlC4YGHD1ikW18p09NAhRR1pZf1AKp4gVsBduzONfj3t4rLi/9WW1SoMJAQ5IynK/856GBRy4HX1BtoHxEQfORCVFtPLprHLTfS7nFMoNMyFvYgJsFh90DQxAtYWXFEaRm7zh/Qt"]}
msg: Failed to lookup user some_user_that_dont_exist: 'getpwnam(): name not found: some_user_that_dont_exist'
```

Copied from original issue: ansible/ansible-modules-core#1515
