### ISSUE TITLE
docker module fails as it appears to start two containers with same name

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30119]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

2.3

##### SUMMARY

From @joshuacox on 2015-05-27T00:01:47Z
Running the following playbook results in failure with docker complaining about another container already named rabbitmq, but there was no such container in the first place, and when I go in and `docker rm` whichever container it is complaining about it still results in the same error.  In fact, if I don't go in and `docker rm` same result in any case.

Of note this is only with the following rabbitmq, I have 14 other containers running happily on this host all using ansible to start and maintain them.  It is only the following playbook that is having issues.

```

---
- name: rabbitmq test
  hosts: testhost
  sudo: True
  tasks:
  - name: rabbitmq test
    docker:
      name: rabbitmq
      hostname: rabbitmq.example.com
      image: rabbitmq:3-management
      state: reloaded
      ports:
      - "5672:5672"
      - "15672:15672"
      volumes:
      - /tmp/rabbitmg:/var/lib/rabbitmq
```

```
ansible-playbook rabbitmq.yml

PLAY [rabbitmq test] ********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [testhost]

TASK: [rabbitmq test] ********************************************************* 
failed: [testhost] => {"changed": true, "failed": true}
msg: Docker API Error: Conflict. The name "rabbitmq" is already in use by container bdef8c4c9d9c. You have to delete (or rename) that container to be able to reuse that name.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/bob/rabbitmq.retry

testhost                    : ok=1    changed=0    unreachable=0    failed=1   
```

uname -a

```
# uname -a
Linux testhost 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

docker version

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

docker info

```
# docker info
Containers: 18
Images: 224
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 274
 Dirperm1 Supported: true
Execution Driver: native-0.2
Kernel Version: 3.16.0-38-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 1
Total Memory: 2.792 GiB
Name: dacksible.webhosting.coop
ID: DUF6:EEKD:3ZFW:ABIL:D2ZR:RBQN:HIFQ:NNOG:OHEV:BJZN:ITYE:FNP7
WARNING: No swap limit support
```

Copied from original issue: ansible/ansible-modules-core#1425

**Comment by ansibot** [comment]
From @joshuacox on 2015-05-27T00:01:47Z

after building on a different host without issue, I began to investigate more.  I noticed some AUFS errors on the host, and decided to pull the trigger and give overlay a shot I upgraded the kernel, and changed the docker opts to include '-s overlay' now the issue has disappeared.  I suspect there is still an issue with the docker module though in that if a docker run command fails on a named container, the module should rm the old container before attempting to run again, or something similar.

**Comment by ansibot** [comment]
From @daviddyball on 2015-05-27T00:01:47Z

I can confirm this behaviour on an Ubuntu 14.04 machine.

Playbook

```
- name: Running Docker Cleanup Container
  docker:
    name: docker-cleaner
    image: meltwater/docker-cleanup:latest
    volumes:
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:rw
    state: reloaded
    restart_policy: always
  ignore_errors: True
  tags:
    - common.docker.containers
```

/etc/lsb-release

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.2 LTS"
```

```
$ unname -r
3.13.0-53-generic
```

Docker:

```
$ docker version
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.4.2
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.4.2
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64

$ docker info
Containers: 6
Images: 92
Storage Driver: devicemapper
 Pool Name: docker-202:1-526601-pool
 Pool Blocksize: 65.54 kB
 Backing Filesystem: extfs
 Data file: /dev/loop2
 Metadata file: /dev/loop3
 Data Space Used: 2.962 GB
 Data Space Total: 107.4 GB
 Data Space Available: 37.02 GB
 Metadata Space Used: 5.124 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.142 GB
 Udev Sync Supported: false
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.82-git (2013-10-04)
Execution Driver: native-0.2
Kernel Version: 3.13.0-53-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.859 GiB
Name: ip-192-168-4-168
ID: PECB:52IU:RQ5Y:WXDI:3AYB:45D2:ACYN:BRWA:MN4B:WAM2:7ABK:SA7O
Username: afdeploy
Registry: [https://index.docker.io/v1/]
WARNING: No swap limit support
```

If I get time I'll dig further into it, but at the moment nothing jumps out as to why this is happening. The only out-of-the-ordinary thing is using volume-mounts from files on the host machine.

**Comment by ansibot** [comment]
From @bandesz on 2015-05-27T00:01:47Z

I also started experience this error today. One additional note is that we just updated to 1.7.1, we did not have this error with 1.5.0.

docker version:

```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

docker info:

```
Containers: 2
Images: 86
Storage Driver: aufs
 Root Dir: /srv/docker/aufs
 Backing Filesystem: extfs
 Dirs: 90
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.16.0-4-amd64
Operating System: Debian GNU/Linux 8 (jessie)
CPUs: 1
Total Memory: 3.687 GiB
Name: xxx
ID: xxx
WARNING: No memory limit support
WARNING: No swap limit support
```

**Comment by ansibot** [comment]
From @ppawiggers on 2015-05-27T00:01:47Z

+1

```
Docker version 1.7.1, build 786b29d

Containers: 13
Images: 262
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 288
 Dirperm1 Supported: false 
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 3.13.0-57-generic
Operating System: Ubuntu 14.04.2 LTS
CPUs: 2
Total Memory: 3.854 GiB
Name: docker01
ID: 2MES:URK6:7JAE:SH32:MY3O:NOVV:ZYQT:D5A4:R7JR:55RH:6CMS:FKIE
WARNING: No swap limit support
```

**Comment by ansibot** [comment]
From @ethinx on 2015-05-27T00:01:47Z

Got the same error, use workaround by specifying the 'docker_api_version' to the one lower than 1.9.

```
# docker version
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

ansible-1.9.2-1.el6.noarch

docker-py==1.3.1
```

**Comment by ansibot** [comment]
From @leedm777 on 2015-05-27T00:01:47Z

I'm seeing this happen when `state: reloaded` and and `volumes` are present.

```
- docker:
    name: registry
    image: 'registry:{{ registry_version }}'
    state: reloaded
    # Need to specify net for reloaded to not always reload
    # See https://github.com/ansible/ansible-modules-core/issues/1885
    net: default
    # Commenting out the volumes; things work
    volumes:
      - /etc/docker/registry/config.yml:/etc/docker/registry/config.yml
```

I'm currently running Ansible 1.9.2, docker-py 1.2.3, Docker 1.8.0 on Ubuntu 14.04. I've set `docker_api_version` as low as `1.12` and it still hit the bug.

I've tried various combinations of Ansible, docker-py and `docker_api_version`, and none of them seem to work.

_follow up_: Just tried v1.9.3-0.1.rc1, and it's behaving differently. Instead of an error, it's always reloading the container, with `"reload_reasons": null`. Will open a new issue.
