### ISSUE TITLE
S3: 'module' object has no attribute 'connect_to_region'

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30110]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

s3 module

##### ANSIBLE VERSION

1.9.1

##### OS / ENVIRONMENT

OSX 10.9.5 and Ubuntu 12.04

##### SUMMARY

Connection to the S3 is failing (we are using eu-west-1 if this matters)

##### STEPS TO REPRODUCE

Run this playbook

```
- hosts: {{Remote_host}}
  tasks:
    - name: 's3'
      s3: bucket=test_bucket object=test_object aws_access_key={{ lookup('env','AWS_ACCESS_KEY') }} aws_secret_key={{ lookup('env','AWS_SECRET_KEY') }} mode=create region=eu-west-1
```

##### EXPECTED RESULTS

The bucket gets created.

##### ACTUAL RESULTS

```
failed: [Remote_host] => {"failed": true}
msg: Failed to connect to S3: 'module' object has no attribute 'connect_to_region'

FATAL: all hosts have already failed -- aborting
```

Copied from original issue: ansible/ansible-modules-core#1544
