### ISSUE TITLE
Bug Report for RDS Params Group example code

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30127]
From @tiyberius on 2015-05-15T19:10:57Z
##### ISSUE TYPE

Documentation Report
##### COMPONENT NAME

rds_param_group module
##### ANSIBLE VERSION

ansible 1.9.1
##### SUMMARY

I'm having trouble creating an RDS Parameter Group. I started with the following example on http://docs.ansible.com/rds_param_group_module.html#examples

```
# Add or change a parameter group, in this case setting auto_increment_increment to 42 * 1024
- rds_param_group:
      state: present
      name: norwegian_blue
      description: 'My Fancy Ex Parrot Group'
      engine: 'mysql5.6'
      params:
          auto_increment_increment: "42K"
```

and since I didn't want to set the `auto_increment_increment parameter`, I removed it, so now my code looks like this

```
# Add or change a parameter group, in this case setting auto_increment_increment to 42 * 1024
- rds_param_group:
      state: present
      name: norwegian_blue
      description: 'My Fancy Ex Parrot Group'
      engine: 'mysql5.6'
```

Instead of creating an RDS Parameter Group as expected, I get the following error

```
TASK: [rds_param_group ] ******************************************************
failed: [localhost] => {"failed": true}
msg: Parameter params required for state='present'

FATAL: all hosts have already failed -- aborting
```

I'm running Ansible 1.9.1 on OS X Yosemite 

```
$ sw_vers -productVersion
10.10.3

$ ansible --version
ansible 1.9.1
```

Copied from original issue: ansible/ansible-modules-core#1340

**Comment by ansibot** [comment]
From @tiyberius on 2015-05-15T19:10:57Z

I also noticed that the code snippet does not work, even when copied and pasted directly into a Playbook. What I've found is that if you run

```
# Add or change a parameter group, in this case setting auto_increment_increment to 42 * 1024
- rds_param_group:
      state: present
      name: norwegian_blue
      description: 'My Fancy Ex Parrot Group'
      engine: 'mysql5.6'
      params:
          auto_increment_increment: "42K"
```

AWS rejects the request to create the Parameter Group because the Parameter Group name in the example includes underscores, which as you can see are not allowed.

```
TASK: [rds_param_group ] ******************************************************
failed: [localhost] => {"failed": true}
msg: The parameter DBParameterGroupName is not a valid identifier. Identifiers must begin with a letter; must contain only ASCII letters, digits, and hyphens; and must not end with a hyphen or contain two consecutive hyphens.
```

The documentation example should be updated to swap out the underscore for a hyphen
