### ISSUE TITLE
S3 lifecycle support (feature request)

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30120]
##### ISSUE TYPE

Feature Idea

##### COMPONENT NAME

s3 module

##### ANSIBLE VERSION

2.3

##### SUMMARY

From @echiu64 on 2015-05-25T21:03:27Z
Looking to implement lifecycle support into the s3 module, thoughts?

Copied from original issue: ansible/ansible-modules-core#1420

**Comment by ansibot** [comment]
From @bcoca on 2015-05-25T21:03:27Z

note: lifecycle controls object archiving and expiration on s3, module should be able to associate preexisting profile.

another issue is creating/managing lifecycle profiles, might be worth another module.

**Comment by ansibot** [comment]
From @echiu64 on 2015-05-25T21:03:27Z

I'll try my hand at writing a different module... i looked at the s3 code, i thought it might be a better idea as well

**Comment by ansibot** [comment]
From @echiu64 on 2015-05-25T21:03:27Z

Here are some proposed YAML examples for how lifecycle would work... i'll work to build out something similar first:

``` yaml
# Add expiration lifecycle rule for entire bucket
s3_lifecycle:
  bucket: mybucket
  lifecycle:
    - rule_id: rule_name
      expiration: days=90
      status: enabled
      state: present

# add expiration lifecycle rule (90 days) for prefix in bucket
s3_lifecycle:
  bucket: mybucket
  lifecycle:
    - rule_id: rule_name
      prefix: myfolder
      expiration: days=90
      status: enabled
      state: present

# add transition to glacier (after 90 days) for bucket
s3_lifecycle:
  bucket: mybucket
  lifecycle:
    - rule_id: rule_name
      transition: storage_class=glacier days=90
      status: enabled
      state: present

# combined rule
s3_lifecycle:
  bucket: mybucket
  lifecycle:
    - rule_id: transition_and_expiry_rule
      transition: storage_class=glacier days=90
      expiration: days=90
      status: enabled
      state: present

# multiple rules
s3_lifecycle:
  bucket: mybucket
  lifecycle:
    - rule_id: rule_myfolder
      prefix: myfolder
      expiration: days=90
      status: enabled
      state: present
    - rule_id: rule_mytemp
      prefix: mytemp
      expiration: days=30
      status: enabled
      state: present
```
