### ISSUE TITLE
ec2_asg fails with AttributeError in 2.5.0 devel branch.

### ISSUE THREAD

**Issue by bndabbs** [ansible/ansible#30121]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_asg.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/redacted/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Sep 11 2017, 09:13:23) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
```
roles_path = roles
retry_files_enabled = False
host_key_checking = False
```

##### OS / ENVIRONMENT
MacOS Sierra 10.12.6

All AWS connections are made via an authenticated corporate proxy over an F5 VPN.

##### SUMMARY
I am using the latest cloud modules to build out some infrastructure in AWS. Most of the modules are working, but ec2_asg is failing with `AttributeError: 'ParamValidationError' object has no attribute 'response'`. 

##### STEPS TO REPRODUCE

Run `ec2_asg` module against localhost.

```yaml
$ cat start.yml
---

- import_playbook: deploy.yml
  vars:
      cluster: a
      region: us-east-1
      subnet_id: subnet-xxxxxx

$ cat deploy.yml
---
- name: Build infrastructure in AWS
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - include_tasks: "{{ item }}"
      with_items:
          - elastic.yml
#          - kafka.yml

$ cat elastic.yml
---
- name: Find and register latest AMI
  ec2_ami_find:
    region: "{{ region }}"
    name: "xxxx-RHEL7*"
    sort: creationDate
    sort_order: descending
    sort_end: 1
  register: ami

<TRUNCATED>

- name: Create Launch config for logstash nodes
  ec2_lc:
    name: "{{ prefix }}-{{ cluster }}-logstash"
    instance_type: m4.xlarge
    image_id: "{{ ami.results[0].ami_id }}"
    security_groups: "{{ group_id }}"
    region: "{{ region }}"
    user_data: "REDACTED"

- name: Create Auto Scaling Group for logstash nodes
  ec2_asg:
    name: "{{ prefix }}-{{ cluster }}-logstash"
    launch_config_name: "{{ prefix }}-{{ cluster }}-logstash"
    load_balancers: "{{ logstash_elb.elb.name }}"
    min_size: 5
    max_size: 12
    vpc_zone_identifier: "{{ subnet_id }}"
    region: "{{ region }}"
    tags:
      - Name: "{{ prefix }}-{{ cluster }}-logstash"
      - project: "{{ project }}"
      - cluster: "{{ cluster }}"
  register: logstash
```

##### EXPECTED RESULTS
AWS Auto Scaling Group should be created with requested parameters.

##### ACTUAL RESULTS

```
ansible-playbook 2.5.0
  config file = /Users/redacted/code/infrastructure/ansible/ansible.cfg
  configured module search path = [u'/Users/redacted/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.13 (default, Sep 11 2017, 09:13:23) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
Using /Users/redacted/code/infrastructure/ansible/ansible.cfg as config file
setting up inventory plugins
statically imported: /Users/redacted/code/infrastructure/ansible/roles/elasticsearch/tasks/java.yml
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

<TRUNCATED>

TASK [Create Auto Scaling Group for logstash nodes] *************************************************************************************************************************************************************************
task path: /Users/redacted/code/infrastructure/ansible/elastic.yml:106
Using module_utils file /usr/local/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/local/lib/python2.7/site-packages/ansible/module_utils/ec2.py
Using module_utils file /usr/local/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/local/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/local/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/local/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/local/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/local/lib/python2.7/site-packages/ansible/module_utils/cloud.py
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/amazon/ec2_asg.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: redacted
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/redacted/.ansible/tmp/ansible-tmp-1505233014.94-265789443111897 `" && echo ansible-tmp-1505233014.94-265789443111897="` echo /Users/redacted/.ansible/tmp/ansible-tmp-1505233014.94-265789443111897 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/dz/8c2jdqws34d0ddwkzp21cq2dqx1h_5/T/tmp6RNZgu TO /Users/redacted/.ansible/tmp/ansible-tmp-1505233014.94-265789443111897/ec2_asg.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/redacted/.ansible/tmp/ansible-tmp-1505233014.94-265789443111897/ /Users/redacted/.ansible/tmp/ansible-tmp-1505233014.94-265789443111897/ec2_asg.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python2.7 /Users/redacted/.ansible/tmp/ansible-tmp-1505233014.94-265789443111897/ec2_asg.py; rm -rf "/Users/redacted/.ansible/tmp/ansible-tmp-1505233014.94-265789443111897/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/dz/8c2jdqws34d0ddwkzp21cq2dqx1h_5/T/ansible_BIe43C/ansible_module_ec2_asg.py", line 1354, in <module>
    main()
  File "/var/folders/dz/8c2jdqws34d0ddwkzp21cq2dqx1h_5/T/ansible_BIe43C/ansible_module_ec2_asg.py", line 1343, in main
    create_changed, asg_properties = create_autoscaling_group(connection, module)
  File "/var/folders/dz/8c2jdqws34d0ddwkzp21cq2dqx1h_5/T/ansible_BIe43C/ansible_modlib.zip/ansible/module_utils/cloud.py", line 153, in retry_func
AttributeError: 'ParamValidationError' object has no attribute 'response'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/dz/8c2jdqws34d0ddwkzp21cq2dqx1h_5/T/ansible_BIe43C/ansible_module_ec2_asg.py\", line 1354, in <module>\n    main()\n  File \"/var/folders/dz/8c2jdqws34d0ddwkzp21cq2dqx1h_5/T/ansible_BIe43C/ansible_module_ec2_asg.py\", line 1343, in main\n    create_changed, asg_properties = create_autoscaling_group(connection, module)\n  File \"/var/folders/dz/8c2jdqws34d0ddwkzp21cq2dqx1h_5/T/ansible_BIe43C/ansible_modlib.zip/ansible/module_utils/cloud.py\", line 153, in retry_func\nAttributeError: 'ParamValidationError' object has no attribute 'response'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

PLAY RECAP ******************************************************************************************************************************************************************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=1
```
