### ISSUE TITLE
Docker Module parameter state=start always replaces the container

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30122]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

1.9.1
Module docker - manage docker containers

##### SUMMARY

:
##### Case1: container with a running process

Start a container, then stop, then start => container is replaced
##### Case2: container with an exiting process

Start a container, start same container again => container is replaced

##### STEPS TO REPRODUCE

:
1. Run this:

```
  - name: start container
    sudo: yes
    docker:
      image: debian:jessie
      name: "deb_001"
      state: "started"
```
1. Run a docker ps to see the container ID:

```
docker ps -a
```
1. Run the task again. Then `docker ps` again and compare conatiner IDs 

Container changes !!!

Copied from original issue: ansible/ansible-modules-core#1416

**Comment by ansibot** [comment]
From @ToBeReplaced on 2015-05-25T11:42:18Z

I was surprised by this today.

Try the following:

```
- hosts: '{{ fqdn }}'
  tasks:
    - name: Create a container
      docker:
        name: test_a
        image: centos:7
        ports:
          - 8080:8080
        state: present
      become: yes
    - name: Start the container
      docker:
        name: test_a
        image: centos:7
        state: started
      become: yes
    - name: Create a container
      docker:
        name: test_b
        image: centos:7
        ports:
          - 8081:8081
        state: present
      become: yes
    - name: Start the container
      command: docker start test_b
      become: yes
```

Then:

```
$ docker inspect --format '{{.HostConfig.PortBindings}}' test_a
map[]
$ docker inspect --format '{{.HostConfig.PortBindings}}' test_b
map[8081/tcp:[{ 8081}]]
```

All of the configuration from the created container is gone if started with the docker module.
