### ISSUE TITLE
Docker module requires image with state=absent

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30138]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

ansible 1.9.1
configured module search path = None

##### OS / ENVIRONMENT

OS X (boot2docker)

##### SUMMARY

Attempting to remove a running docker container without specifying an image results in an error, even though an image name shouldn't be required.

##### STEPS TO REPRODUCE

Failing playbook:

```
- hosts: localhost
  tasks:
    - name: start redis container
      docker: name=redistest image=redis ports=6379:6379

    - name: remove redis container
      docker: name=redistest state=absent
```

##### EXPECTED RESULTS

Output that looks like:

```
TASK: [remove redis container] ************************************************
changed: [localhost]
```

##### ACTUAL RESULTS

Following error:

```
TASK: [remove redis container] ************************************************
failed: [localhost] => {"failed": true}
msg: missing required arguments: image

FATAL: all hosts have already failed -- aborting
```

Copied from original issue: ansible/ansible-modules-core#1239
