### ISSUE TITLE
Docker Module Does Not Start Container with the same as the CLI equivalent params

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30149]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

ansible 1.9.0.1
configured module search path = None

##### OS / ENVIRONMENT

RHEL7 Control Machine targeting RHEL7

##### SUMMARY

Running docker via the module results in a non functional container. Running docker directly with the same 1 for 1 arguments, works.

##### STEPS TO REPRODUCE

First Run This:

``` yml
 - name: docker start latest openam12
   sudo: yes
   docker:
     image: 'ricone/openam12so'
     pull: always
     state: started
     net: none
     ports:
       - 80:8080
       - 443:8443
     volumes:
       - /storage/openam:/openam:rw
     name: openam
```

After a moment or so, run `curl localhost` and `curl localhost:443` and see a Connection Refused error in STERR.

##### EXPECTED RESULTS

curl returns with a zero exit code

##### ACTUAL RESULTS

`curl: (7) Failed connect to localhost:80; Connection refused`

**NOTE:** If you do 
`docker run -d --name=openam12so -p 80:8080 -p 443:8443 -v /storage/openam:/openam ricone/openam12so`

It will pull the image, start the container and curling localhost returns a zero exit code.

Copied from original issue: ansible/ansible-modules-core#1115

**Comment by ansibot** [comment]
From @autotune on 2015-04-09T11:55:50Z

Strangely enough it does not start the networking portion as it does with the command on ansible 2.0.0 (devel 31d06886d5) on CentOS 7.1. After starting with the command we get the following example interface:

41: veth5bacb18: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP
    link/ether 12:34:56:78:90:1a brd ff:ff:ff:ff:ff:ff
    inet6 fe80::0000:00ff:0000:000c/64 scope link
       valid_lft forever preferred_lft forever

From what I can see this uses the docker API that comes with the package rather than the command line itself. If this module is to continue to use the API it's likely going to be a matter of figuring out why that interface is not showing up after the API call.

**Comment by ansibot** [comment]
From @autotune on 2015-04-09T11:55:50Z

@defionscode @bcoca I don't believe this is a bug so much as a configuration error. The ports need to be exposed and networking enabled for the container as in the following config:

```
---
- hosts: localhost
  sudo: true
- tasks:
    - name: data container
      sudo: yes
      docker:
        name: mydata
        image: 'ricone/openam12so'
        state: present
        pull: always
        state: started
        # net: none
        ports:
          - 80:8080
          - 443:8443
        expose:
          - 8080
          - 8443
        volumes:
          - /storage/openam:/openam:rw
        name: ricone-openam12so

[autotune@ansibledev 1115]$ curl localhost
[autotune@ansibledev 1115]$ sudo netstat -tupln|egrep ":80|:443"
tcp6       0      0 :::80                   :::*                    LISTEN      15980/docker-proxy
tcp6       0      0 :::443                  :::*                    LISTEN      15972/docker-proxy
```

@defionscode definitely check out http://docs.ansible.com/ansible/docker_module.html and expose the ports ya need to expose.
