### ISSUE TITLE
Docker 1.6 cannot mount a volume with a single file

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30143]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

1.9.0.1

##### OS / ENVIRONMENT

Ubuntu 14.04

##### SUMMARY

:**
Docker allows mounting volumes specifying a single file, like `docker run -v /etc/profile:/etc/profile:ro busybox`
Starting from Docker version 1.6, Ansible cannot mount such volumes, if the file already exist within an image, but needs to be overwritten by a copy from the host.

This is probably a bug in Docker engine or`docker-py` library, but I can reproduce it only from Ansible.
Docker-compose has a similar issue: https://github.com/docker/compose/issues/424

**

##### STEPS TO REPRODUCE

:**
Run this playbook:

```

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - docker:
        image: busybox
        volumes:
        - "/etc/profile:/etc/profile:ro"
```

**

##### EXPECTED RESULTS

:**
Having Docker 1.5 it applies normally.

**

##### ACTUAL RESULTS

:**
With Docker 1.6 Ansible fails:

```
TASK: [docker ] ***************************************************************
failed: [127.0.0.1] => {"changed": false, "failed": true}
msg: Docker API Error: file exists at /var/lib/docker/aufs/mnt/f2ed605b182792d69c397b6dcc7d7c6c40193e89d49d047b33934f779423c38f/etc/profile, can't create volume there
```

Copied from original issue: ansible/ansible-modules-core#1158
