### ISSUE TITLE
ec2 creates new instance if instance not running when using exact_count

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30168]
From @moorereason on 2015-02-28T01:52:28Z
##### Issue Type:

Bug Report

##### Component Name:
ec2 module

##### Ansible Version:

1.8.2
##### Environment:

Red Hat 7
##### Summary:

When creating an ec2 instance with exact_count, the module creates new instances if the existing instance is not running.
##### Steps To Reproduce:

Given the following example playbook:

``` yaml
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ec2:
        region: "{{ aws_region }}"
        instance_type: "{{ aws_instance_type }}"
        image: "{{ aws_image }}"
        vpc_subnet_id: "{{ aws_vpc_subnet_id }}"
        group: "{{ aws_group }}"
        key_name: "{{ aws_keypair }}"
        exact_count: 1
        count_tag:
          Name: "{{ item.hostname }}"
          Role: "{{ item.role }}"
          Env: "{{ item.env }}"
        instance_tags:
          Name: "{{ item.hostname }}"
          Role: "{{ item.role }}"
          Env: "{{ item.env }}"
        volumes:
          - device_name: /dev/sda1
            volume_size: 10
            device_type: gp2 
        wait: yes
        wait_timeout: 500
      with_items: aws_launch
```

Run the playbook twice, stopping the instance before the second run.
##### Expected Results:

I expect the second run to return OK without creating a new instance.
##### Actual Results:

Module creates a second instance.

Copied from original issue: ansible/ansible-modules-core#871
