### ISSUE TITLE
gem module fails to install new version of a gem when using gem_source

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30162]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

gem module

##### ANSIBLE VERSION

1.8.4

##### OS / ENVIRONMENT

Ubuntu 14.04 host and target

##### SUMMARY

_from the original issue_

If a local .gem file has been installed by setting gem_source, ansible refuses to install a new version of the gem when gem_source is set to the newer .gem file. The version argument for the gem module can't be used as it is mutually exclusive with the gem_source argument.

##### STEPS TO REPRODUCE

_from the original issue_

```
Copy example_1.0.gem to remote host
Install example_1.0.gem using gem module and gem_source`
```

-- LATER --

```
Copy example_1.1.gem to remote host
Attempt to Install example_1.1.gem using gem module and gem_source gem module thinks the gem is already installed and doesn't run {"changed": false
```

##### EXPECTED RESULTS

_from the original issue_

New gem should actually be installed

##### ACTUAL RESULTS

_from the original issue_

gem does not get installed

Copied from original issue: ansible/ansible-modules-core#928

**Comment by ansibot** [comment]
From @ansibot on 2015-03-12T11:50:57Z



@ansible ping, this issue is waiting for your response.
[click here for bot help](https://github.com/jctanner/ansibullbot/blob/ISSUE_TRIAGE_CLASS/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@ansibot Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by steaksauce-** [comment]
Is this still an issue? I see that it affects an older version of ansible, but there have been a lot of changes since then.

**Comment by acky6012** [comment]
Seems to still be a problem. By chance I was attempting the same thing today. The new version of a gem has not been installed when I copied a gemfile over to the target host and then used the gem_source argument. I checked that I was also specifying that user_install = no.

**Comment by alexhogberg** [comment]
Had the same issue myself where I wanted to install local gems for sensu, and got around it by adding some manual tasks in my role:

```
- name: Copy local plugins to dest
  copy: src={{ item.source }} dest=.
  with_items: "{{ local_plugins }}"
  tags:
  - sensu_client
  - install-deps
  - sensu_local_plugins

- name: Check for version change for local gems
  shell: /opt/sensu/embedded/bin/gem list -i -v {{ item.version }} {{ item.name }}
  register: gem_list_result
  changed_when: "'false' in gem_list_result.stdout"
  failed_when: "'ERROR' in gem_list_result.stderr"
  with_items: "{{ local_plugins }}"
  tags:
    - install-deps
    - sensu_local_plugins

- name: Make list of incoming upgrades
  set_fact: upgrade_list="{{ gem_list_result.results | selectattr("changed", "equalto", true) | map(attribute='item') | list }}"
  tags:
  - install-deps
  - sensu_local_plugins

- name: Remove upgradable packages before installing
  gem : name="{{ item.name }}"
      executable=/opt/sensu/embedded/bin/gem
      state=absent
  with_items: "{{ upgrade_list }}"
  tags:
    - install-deps
    - sensu_local_plugins

- name: Install gem for Sensu client.
  gem: name={{ item.name }}
      gem_source={{ item.source }}
      executable=/opt/sensu/embedded/bin/gem
      user_install=no
      state=present
  with_items: "{{ local_plugins }}"
  notify: restart sensu_client
  tags:
    - sensu_local_plugins
    - sensu_client
    - install-deps
```

Where `local_plugins` is a list of objects with keys: `name`, `source` and `version`. Hopefully it can help some people out.
