### ISSUE TITLE
Avahi does not disable properly with systemd on centos 7

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30163]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

service module

##### ANSIBLE VERSION

2.2

##### SUMMARY

From @mattstep on 2015-03-09T22:11:30Z
The following results in a stopped avahi-daemon, however it remains enabled.

```
- name: Disable avahi-daemon.socket
  service: name=avahi-daemon.socket enabled=no state=stopped
- name: Disable avahi-daemon
  service: name=avahi-daemon enabled=no state=stopped
- name: Disable avahi-daemon.service
  service: name=avahi-daemon.service enabled=no state=stopped
```

Copied from original issue: ansible/ansible-modules-core#917

**Comment by ansibot** [comment]
From @dbrgn on 2015-03-09T22:11:30Z

Similar issue here:

``` yaml
- name: Disable graphical target
  service: name=graphical.target enabled=no
- name: Enable multi-user target
  service: name=graphical.target enabled=yes
```

None of these has any effects.
- Ansible version: `ansible 1.9.0.1`
- Host: Arch Linux
- Target: Raspberry Pi with Raspbian and Systemd
