### ISSUE TITLE
Docker: image pull from private secure registry fails when image name contains a number

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30170]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

2.0

##### SUMMARY

From @caljess599 on 2015-02-27T20:42:58Z
This could very well be a docker-py issue, but this is what we've seen:

``` yaml
tasks:
  - name: main.yml | determine Docker Client API Version
    shell: docker version | grep 'Client API version' | cut -d' ' -f4
    register: client_api_version

  - name: main.yml | start database container for sentry
    docker:
      image: postgres93
      name: sentry_db
      registry: 'https://our.registry.com'
      username: "{{ docker_username }}"
      email: "{{ docker_email }}"
      password: "{{ docker_password }}"
      publish_all_ports: yes
      docker_api_version: "{{ client_api_version.stdout }}"
      state: running
```

This task fails, giving me the message `msg: Docker API error: No such image: postgres93 (tag: latest)`

However, when I rename the registry image name from `postgres93` to `postgres`, it works just fine.

Copied from original issue: ansible/ansible-modules-core#866
