### ISSUE TITLE
ec2_group fails to give access to ELB security group (amazon-elb/amazon-elb-sg)

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30176]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

ec2_group module

##### ANSIBLE VERSION

ansible --version
ansible 1.8.2
configured module search path = /usr/share/ansible
boto 2.36.0

##### OS / ENVIRONMENT

CentOS release 6.5
OSX 10.10.1

##### SUMMARY

In Amazon there is a standard Security Group regarding the ELB service that you must give access to the instances in the Load Balancer pool. Ansible ec2_group module will fail to give access to ELB security group as it cannot detect the security group exists and will try to create it giving the error bellow.

##### STEPS TO REPRODUCE

_security_grups.yml_ : 

```
  - name: create Web Security Group
    local_action:
      module: ec2_group
      name: Web
      description: "Web TIER"
      region: us-east-1
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          group_name: "amazon-elb/amazon-elb-sg"
```

##### EXPECTED RESULTS

The Security Group Web should give access to port 80 for the ELB (amazon-elb/amazon-elb-sg).

##### ACTUAL RESULTS

Ansible fails to execute the task and I have to manually add the rule that give access to the ELB.

ansible-playbook security_grups.yml -vvvvvv

```
failed: [localhost -> 127.0.0.1] => {"failed": true}
msg: group amazon-elb/amazon-elb-sg will be automatically created by rule {'to_port': 80, 'from_port': 80, 'group_name': 'amazon-elb/amazon-elb-sg', 'proto': 'tcp'} and no description was provided
```

This happens when ELB and the security group amazon-elb/amazon-elb-sg already exists.

Copied from original issue: ansible/ansible-modules-core#771
