### ISSUE TITLE
docker port mappings not working when host is given

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30188]
##### ISSUE TYPE

bug report

##### COMPONENT NAME

docker module

##### ANSIBLE VERSION

1.7.2

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The ports section allows to specify a bind address on the command line.
The module doesn't and does not even bother to complain.

This is on Docker version 1.3.2, build 39fa2fa, Ansible 1.7.2

##### STEPS TO REPRODUCE

```
- name: running docker-registry container
  docker:
    image: tcurdt/docker-registry
    name: docker-registry
    state: running
    net: host
    ports: "127.0.0.1:5000:5000"
```

##### EXPECTED RESULTS

should be the equivalent of running

```
docker run --name registry -p 127.0.0.1:5000:5000 -d tcurdt/docker-registry
```

but it's not.

##### ACTUAL RESULTS

It seems to ignore the port mapping.

Copied from original issue: ansible/ansible-modules-core#605

**Comment by ansibot** [comment]
From @tcurdt on 2015-01-07T17:11:45Z

originally opened as https://github.com/ansible/ansible/issues/9648

**Comment by ansibot** [comment]
From @tcurdt on 2015-01-07T17:11:45Z

@bcoca why is this now only P3? this pretty essential. it's a blocker on my end.

**Comment by ansibot** [comment]
From @bcoca on 2015-01-07T17:11:45Z

can you check your versions of docker-py? there seems to have been a fix to the library that would take care of similar issue (not sure this is caused by that but same symptoms).

**Comment by ansibot** [comment]
From @daviddyball on 2015-01-07T17:11:45Z

@tcurdt Adding `expose: 80` to the ansible task fixes it... but you are 100% right, the current module doesn't behave like the docker CLI does, which is unintuitive.

I have a WIP branch on https://github.com/daviddyball/ansible-modules-extras where I'm trying to split out the functionality of the current docker module into multiple sub-modules (e.g. `docker_pull`, `docker_exec`, `docker_run` etc.). Feel free to make PR's if you have any ideas.

**Comment by ansibot** [comment]
From @schmeedy on 2015-01-07T17:11:45Z

Actually, I can bind a port exposed in the image to a specific address just fine. If ports are not exposed, you have to expose them explicitly in your task (which is inconsistent with `docker run`) - this is tracked in #147.

**Comment by ansibot** [comment]
From @j0hnsmith on 2015-01-07T17:11:45Z

This bug gets even stranger. I've spent an hour or more trying to set ports, I've tried all kinds of different `ports` syntax, expose etc etc, nothing worked... until I added `name: foo`. WTF. 

Naming a container is completely unrelated to mapping ports.

**Comment by ansibot** [comment]
From @rindek on 2015-01-07T17:11:45Z

Still present in ansible 2.1

```
- name: "run local_proxy postgres ambassador"
  docker:
    name: postgres_local_proxy_ambassador
    image: cpuguy83/docker-grand-ambassador
    state: reloaded
    restart_policy: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:9000:5432"
    command: "-name {{ postgresql_docker_container }}"
```

does not map ports, however new `docker_container` module seems to do the trick and mapping works properly
