### ISSUE TITLE
azure_rm_virtualmachine `allocated` is not idempotent

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#30193]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
2.4.0

##### OS / ENVIRONMENT
NA

##### SUMMARY
Setting `allocated: no` on a running virtual machine toggles the allocated state between yes/no on multiple runs instead of returning when in the correct state.

PS: module UI is not great for this, should probably be a single `power_state` value that supports `running, deallocated, stopped` instead of two mutually exclusive values.

##### STEPS TO REPRODUCE
Run the following task multiple times on an already-created VM- each run will toggle the `allocated` state (restarting the VM) instead of reporting no change once it's been deallocated.

```yaml
  - azure_rm_virtualmachine:
      resource_group: mdrg1
      name: mdtestvm
      state: present
      allocated: no
      vm_size: Standard_DS1_v2

```

##### EXPECTED RESULTS
Running VM is deallocated on first run, stays that way on subsequent runs.

##### ACTUAL RESULTS
Running VM is deallocated, then allocation state is toggled on each subsequent run.

```

```
