### ISSUE TITLE
ec2_group and multiple "default" groups

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30202]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

ec2_group module

##### ANSIBLE VERSION

2.1

##### SUMMARY

From @dudeche on 2014-12-10T16:31:48Z
We have a "default" group associated with classic EC2 and one with a VPC.  Essentially ec2_group throws this message:

```
failed: [localhost] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/Users/danbenson/.ansible/tmp/ansible-tmp-1418227866.07-149574070985412/ec2_group", line 1899, in <module>
    main()
  File "/Users/danbenson/.ansible/tmp/ansible-tmp-1418227866.07-149574070985412/ec2_group", line 272, in main
    group.authorize(rule['proto'], rule['from_port'], rule['to_port'], ip, grantGroup)
  File "/opt/boxen/homebrew/Cellar/ansible/1.7.2/libexec/vendor/lib/python2.7/site-packages/boto/ec2/securitygroup.py", line 204, in authorize
    dry_run=dry_run)
  File "/opt/boxen/homebrew/Cellar/ansible/1.7.2/libexec/vendor/lib/python2.7/site-packages/boto/ec2/connection.py", line 3193, in authorize_security_group
    params, verb='POST')
  File "/opt/boxen/homebrew/Cellar/ansible/1.7.2/libexec/vendor/lib/python2.7/site-packages/boto/connection.py", line 1207, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>You may not define rules between a VPC group and a non-VPC group.</Message></Error></Errors><RequestID>3af22497-9304-4bbf-bb55-15325747c587</RequestID></Response>
```

Assuming I'm not missing something big here...it's conceivable you could have multiple security groups with the group name of "default".  The only way I can think of to handle this is to add a security group ID argument to ec2_group and key off that instead.

Copied from original issue: ansible/ansible-modules-core#487

**Comment by ansibot** [comment]
From @ansibot on 2014-12-10T16:31:48Z

# Can You Help Us Out?

Thanks for filing a ticket! I am the friendly GitHub Ansibot. 

It looks like you might not have filled out the issue description based on our standard issue template.  You might not have known about that, and that's ok too, we'll tell you how to do it.

We have a standard template because Ansible is a really busy project and it helps to have some standard information in each ticket, and GitHub doesn't yet provide a standard facility to do this like some other bug trackers.  We hope you understand as this is really valuable to us!. 

Solving this is simple: please copy the contents of this [template](https://raw.githubusercontent.com/ansible/ansible/devel/ISSUE_TEMPLATE.md) and **paste it into the description** of your ticket.  That's it!

# If You Had A Question To Ask Instead

If you happened to have a "how do I do this in Ansible" type of question, that's probably more of a user-list question than a bug report, and you should probably ask this question on the project mailing list instead.  

However, if you think you have a bug, the report is the way to go!  We definitely want all the bugs filed :)  Just trying to help!

# About Priority Tags

Since you're here, we'll also share some useful information at this time.

In general tickets will be assigned a priority between P1 (highest) and P5, and then worked in priority order. We may also have some follow up questions along the way, so keeping up with follow up comments via GitHub notifications is a good idea.

Due to large interest in Ansible, humans may not comment on your ticket immediately.  

# Mailing Lists

If you have concerns or questions, you're welcome to stop by the ansible-project or ansible-development mailing lists, as appropriate.  Here are the links:
- https://groups.google.com/forum/#!forum/ansible-project - for discussion of bugs and how-to type questions
- https://groups.google.com/forum/#!forum/ansible-devel - for discussion on how to implement a code change, or feature brainstorming among developers

Thanks again for the interest in Ansible!

**Comment by ansibot** [comment]
From @madhakish on 2014-12-10T16:31:48Z

I recently ran into the same issue where we have multiple "default" sg's across several VPC's and can confirm specifying "group: default" enumerates outside of the VPC when a VPC is specified.

Expected behavior: search for sg's named "default" inside/associated to a VPC when one is specified.

Workaround: identify the actual sg ID (sg-########) and supply it via the "group_id" var.

**Comment by ansibot** [comment]
From @dudeche on 2014-12-10T16:31:48Z

I don't see "group_id" as an argument in the source for ec2_group.  Do you mean put the SG id in the name field?

**Comment by ansibot** [comment]
From @madhakish on 2014-12-10T16:31:48Z

sorry, "security_group_id" and is the sg- style name. Use in conjuction with "vpc_subnet_id" using subnet- style.

**Comment by ansibot** [comment]
From @dudeche on 2014-12-10T16:31:48Z

Sorry,  I'm still confused.  Per the source for the ec2_group:

```
argument_spec.update(dict(
            name=dict(required=True),
            description=dict(required=True),
            vpc_id=dict(),
            rules=dict(),
            rules_egress=dict(),
            state = dict(default='present', choices=['present', 'absent']),
            purge_rules=dict(default=True, required=False, type='bool'),
            purge_rules_egress=dict(default=True, required=False, type='bool'),
```

I don't see how you specify an sg id or vpc subnet id.  Or are you suggesting a potential way to solve this problem?

**Comment by ansibot** [comment]
From @lpetre on 2014-12-10T16:31:48Z

@madhakish Do you have an example of your workaround? I'm hitting this now trying to script a complex VPC creation. I'm not sure how to query the new VPC for the default group from ansible.

**Comment by ansibot** [comment]
From @sebest on 2014-12-10T16:31:48Z

one way to bypass this issue is to register the default security group without modifying it:

``` yaml
    - name: SG Default in AP-SOUTHEAST-2
      ec2_group:
        name: default
        description: default
        vpc_id: "{{ vpc_ap_southeast_2.vpc_id }}"
        region: ap-southeast-2
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
      register: sg_default_ap_southeast_2
```

and then you can use it in your instance creation with gorup_id:

``` yaml
    - name: Start the VPN instance in AP-SOUTHEAST-2
      ec2:
        state: present
        region: ap-southeast-2
        ec2_access_key: "{{ ec2_access_key }}"
        ec2_secret_key: "{{ ec2_secret_key }}"
        zone: ap-southeast-2a
        private_ip: 172.27.32.4
        image: ami-d50773ef
        instance_type: t2.small
        key_name: sebest
        group_id:
          - "{{ sg_default_ap_southeast_2.group_id }}"
```

**Comment by ansibot** [comment]
From @dudeche on 2014-12-10T16:31:48Z

I'm not sure that actually helps with the original problem.  We manage our sg rules via ansible....our git repository is the source of truth for our rulesets.  I think it may just be as simple as adding a group_id argument to ec2_group and handle it correctly in the code.  I suppose you could have the code look at some combination of Name and Description.

**Comment by ansibot** [comment]
From @klad325 on 2014-12-10T16:31:48Z

I believe I had the same issue--I have a default security group in classic as well as a default security group in the VPC.  When I tried to interact with the classic security group (no vpc_id specified), the ec2_group module was still picking out the default security group in my vpc.  I hacked the source to fix the line 221 condition.  I changed: 

``` python
if curGroup.name == name and (vpc_id is None or curGroup.vpc_id == vpc_id):
```

to

``` python
if curGroup.name == name and curGroup.vpc_id == vpc_id:
```

to make sure it finds only the correct group.  That allowed me to use the module properly in my use case:

``` yaml
- name: add ec2 security group for datas to default group
  ec2_group:
    name: "default"
    description: "default group"
    region: "{{ aws_region }}"
    purge_rules: "false"
    rules:
    - proto: "tcp"
      from_port: "0"
      to_port: "65535"
      group_name: "{{ cluster_key }}-data"
```

I'm new to open source so not sure how to properly test & merge these changes, but hope this helps.
