### ISSUE TITLE
lineinfile does not expand "\t" when some conditions are met

### ISSUE THREAD

**Issue by ansibot** [ansible/ansible#30225]
From @h2suzuki on 2014-10-12T00:57:29Z
##### Issue Type:

Bug Report

##### Component Name:
lineinfile module

##### Ansible Version:

1.7.2
(1.7.1 does not have this issue)
##### Environment:

CentOS7 x86_64
pip install ansible for 1.7.2
yum install ansible for 1.7.1
##### Summary:

lineinfile fails to expand "\t" when the inserted line has "...'...'..." type of quoting.
##### Steps To Reproduce:

prepare the following playbook and the test data file.

``` yaml
--- # file: lineinfile.yml

- hosts: all

  gather_facts: False

  vars:
    original_file: ./test.txt.org
    target_file: ./test.txt
    fresh_start: yes

  tasks:
    - name: copy the data file
      copy: src={{ original_file }} dest={{ target_file }} force={{ fresh_start }}

    - name: insert the line
      lineinfile: dest={{ target_file }} state=present
        insertafter="\t.*this line"
        line="\ta line with 'tab'"
        regexp="a line with 'tab'"
```

Here is test.txt.org.  Note: the indent is by a tab.

```
# a sample text

        Insert after this line
        the next line
```

Then, run the playbook:

```
$ ansible-playbook -i hosts lineinfile.yml
```
##### Expected Results:

The target machine should have test.txt in the home directory.

```
# a sample text

        Insert after this line
        a line with 'tab'
        the next line
```
##### Actual Results:

The two character string "\t" is inserted instead of a tab.

```
# a sample text

        Insert after this line
\ta line with 'tab'
        the next line
```

Copied from original issue: ansible/ansible-modules-core#174

**Comment by ansibot** [comment]
From @h2suzuki on 2014-10-12T00:57:29Z

Here is the additional information about quoting.  I have tried other mixes of quoting.

The new test data file:

```
# a sample text

        Insert after this line: single-quoted-nomix '...'
        the next line

        Insert after this line: double-quoted-nomix "..."
        the next line

        Insert after this line: single-quoted-mix '"..."'
        the next line

        Insert after this line: double-quoted-mix "'...'"
        the next line

        Insert after this line: single-quoted-jinja2-mix '{{xx}} "..."'
        the next line

        Insert after this line: double-quoted-jinja2-mix "{{xx}} '...'"
        the next line
```

And the playbook:

``` yaml
--- # file: lineinfile.yml

- hosts: all

  gather_facts: False

  vars:
    original_file: ./test.txt.org
    target_file: ./test.txt
    fresh_start: yes

  tasks:
    - name: copy the data file
      copy: src={{ original_file }} dest={{ target_file }}
        force={{ fresh_start }}

    - name: case1 insert the line '...'
      lineinfile: dest={{ target_file }} state=present
        insertafter='\t.*single-quoted-nomix'
        line='\ta line with tab 1'
        regexp='a line with tab 1'

    - name: case2 insert the line "..."
      lineinfile: dest={{ target_file }} state=present
        insertafter="\t.*double-quoted-nomix"
        line="\ta line with tab 2"
        regexp="a line with tab 2"

    - name: case3 insert the line with '"..."'
      lineinfile: dest={{ target_file }} state=present
        insertafter='\t.*single-quoted-mix'
        line='\ta line with "tab" 3'
        regexp='a line with "tab" 3'

    - name: case4 insert the line "'...'"
      lineinfile: dest={{ target_file }} state=present
        insertafter="\t.*double-quoted-mix"
        line="\ta line with 'tab' 4"
        regexp="a line with 'tab' 4"

    - name: case5 insert the line with '"..."' with jinja2
      lineinfile: dest={{ target_file }} state=present
        insertafter='\t.*single-quoted-jinja2-mix'
        line='{{ "\t" }}a line with "tab" 5'
        regexp='a line with "tab" 5'

    - name: case6 insert the line "'...'" with jinja2
      lineinfile: dest={{ target_file }} state=present
        insertafter="\t.*double-quoted-jinja2-mix"
        line="{{ '\t' }}a line with 'tab' 6"
        regexp="a line with 'tab' 6"
```

The actual resulted file is here.

```
# a sample text

        Insert after this line: single-quoted-nomix '...'
        a line with tab 1
        the next line

        Insert after this line: double-quoted-nomix "..."
        a line with tab 2
        the next line

        Insert after this line: single-quoted-mix '"..."'
        a line with "tab" 3
        the next line

        Insert after this line: double-quoted-mix "'...'"
\ta line with 'tab' 4
        the next line

        Insert after this line: single-quoted-jinja2-mix '{{xx}} "..."'
        a line with "tab" 5
        the next line

        Insert after this line: double-quoted-jinja2-mix "{{xx}} '...'"
        a line with 'tab' 6
        the next line
```

You can see only case4 is affected.  Again, Ansible 1.7.1 ends up with all normal results (good)

**Comment by ansibot** [comment]
From @ltoscano-rh on 2014-10-12T00:57:29Z

Not only \t, I can see it also for \1 when backrefs is enabled. Tested on Fedora 20.

**Comment by ansibot** [comment]
From @ltoscano-rh on 2014-10-12T00:57:29Z

As an update to my previous comment, this is another example of broken lineinfile, this time for \1:

``` yaml
---
- hosts: localhost
  connection: local
  gather_facts: False
  vars:
    original_file: ./lineinfile_backref.txt
    target_file: ./lineinfile_backref_test.txt

  tasks:
    - name: copy the data file
      copy: src={{ original_file }} dest={{ target_file }} force=yes

    - name: broken test
      lineinfile: dest={{ target_file }}
                  backrefs=yes regexp="(^[ ]+'values'.*)\),"
                  line="\1 'vn'),"
```

The example file is:

```
    'values': ('v1', 'v2', 'v3',),
```

The commit which introduced the regression is
https://github.com/ansible/ansible/commit/dc9482d54868f7abb1b453f77845a7ab927def00
which solves https://github.com/ansible/ansible/issues/8806.

Reverting the patch (I tested on 1.8.2), the previous behavior is restored. Is it possible to fix that issue without breaking this?
