### ISSUE TITLE
Support volume tagging in ec2 module

### ISSUE THREAD

**Issue by kmasaryk** [ansible/ansible#30240]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ec2.py

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
This is a feature request to add support for providing a list of tags with each volume definition.

##### STEPS TO REPRODUCE
Example usage:

```
- ec2:
    instance_type: c3.medium
    image: ami-123456
    volumes:
      - device_name: /dev/sdb
        volume_type: gp2
        volume_size: 8
        tags:
          tag1: "foo"
          tag2: "bar"
```

##### EXPECTED RESULTS
An arbitrary list of tags will be added to the new volume.

##### ACTUAL RESULTS
N/A
