### ISSUE TITLE
Arista EOS module doesn't properly parse vrfs

### ISSUE THREAD

**Issue by Gelob** [ansible/ansible#30250]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
eos_vrf
eos_eapi

##### ANSIBLE VERSION

```
 19179 1505254263.46765: starting run
ansible 2.5.0
  config file = /home/user/ansible-network/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
ANSIBLE_DEBUG=True
ANSIBLE_LOG_PATH=~/.ansible.log

##### OS / ENVIRONMENT
CentOS 7, I've tried ansible 2.5.0 and v2.3.2.0, EOS 4.16.7M

##### SUMMARY
When trying to specify a vrf in the eos_eapi task, I get the error below:
```
{"msg": "vrf `vrf-mgmt` is not configured on the system", "failed": true,
```
Except the vrf does exist and shows when I run show vrf manually which is what I see is run by the module https://github.com/ansible/ansible/blob/d8b1cb9a634d0e828a7be39d4019a6215410e643/lib/ansible/modules/network/eos/eos_eapi.py#L210

Manual show vrf output:
```
#show vrf
Maximum number of vrfs allowed: 15
  Vrf          RD           Protocols     State            Interfaces
------------ ------------ ------------- ------------------ --------------------
  vrf-ext      65001:1      ipv4,ipv6     v4:routing,      Ethernet45,
                                          v6:no routing    Ethernet46, Vlan100,
                                                           Vlan1213, Vlan136,
                                                           Vlan137, Vlan138,
                                                           Vlan139, Vlan172,
                                                           Vlan174, Vlan200,
                                                           Vlan201, Vlan202,
                                                           Vlan203, Vlan204,
                                                           Vlan205, Vlan206,
                                                           Vlan207, Vlan208,
                                                           Vlan221, Vlan90,
                                                           Vlan96
  vrf-mgmt     65001:10     ipv4,ipv6     v4:routing,      Management1
                                          v6:no routing

```

I imagine something in the "show vrf" output from Arista changed?
##### STEPS TO REPRODUCE

```yaml
---
- name: Arista
  hosts: all
  connection: local
  gather_facts: no

  vars_prompt:
    - name: "username"
      prompt: "username? "
      private: no

    - name: "password"
      prompt: "Password? "
      private: yes

  tasks:
    - name: Enable eAPI with no HTTP, HTTPS at port 443
      eos_eapi:
       host: "{{ inventory_hostname }}"
       vrf: "vrf-mgmt"
       state: started
       http: false
       https: true
       https_port: 443
       local_http: false
       socket: false
       provider: "{{ provider }}"
```

##### EXPECTED RESULTS
I expected it to detect my vrf exists which it does and run the task properly.

##### ACTUAL RESULTS
It returns the above error saying my vrf doesn't exist. DEBUG information shows the same error

```
ansible-playbook -C --limit DEVICE1 -i inventories/site/hosts eapi.yml
fatal: [DEVICE1]: FAILED! => {"changed": false, "failed": true, "msg": "vrf `vrf-ext` is not configured on the system"}
```

##### MORE INFORMATION
The code to parse the "show vrf' output to json in eos_vrf parses the vrf names correctly but it has issues parsing the routing domain and interfaces when there is a large number.

https://github.com/ansible/ansible/blob/340f52ae9646f605310345f875df7985ee978019/lib/ansible/modules/network/eos/eos_vrf.py#L176

```json
[
    {
        "rd": "65001:1",
        "interfaces": [
            "Ethernet45",
            ""
        ],
        "name": "vrf-ext"
    },
    {
        "rd": "Ethernet46, Vlan100,",
        "interfaces": null,
        "name": "v6:no routing"
    },
    {
        "rd": "65001:10",
        "interfaces": [
            "Management1"
        ],
        "name": "vrf-mgmt"
    }
]
```

The code in eos_eapi to parse the vrfs is very different to eos_vrf and something with the regex in configured_vrfs under the validate_vrf function is very wrong.  Debugging shows the only valid VRFs being detected are: ['Vrf', 'Vlan96', 'default']

Testing the regex against my output shows thats is indeed all thats being matched: https://regexr.com/3go3j

I imagine something in the "show vrf" output from Arista maybe changed? I am on version 4.16.7M
