### ISSUE TITLE
Ansible NXOS_Config adding in additional uncalled command failing template implementation

### ISSUE THREAD

**Issue by jmcleroy** [ansible/ansible#30288]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

NXOS_Config adds BFD to a bgp template command causing the command to fail
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

Only disabled hostkeychecking
##### OS / ENVIRONMENT

Rhel 7.3 attempting to change NXOS 7.0.3.I5.1.bin
##### SUMMARY

When submitting a template change for bgp it is adding the command BFD which is not called in the template as it is not part of a bgp neighbor add
##### STEPS TO REPRODUCE

```yaml
 - name: BASE NEIGHBOR CONFIG
      nxos_config:
       src: bgp_spine_neighbor.j2
       provider: "{{ nxos_provider }}" #(nxapi)
      with_items:
        - "{{ bgp_neighbors }}"

bgp_spine_neighbor.j2
router bgp 1
  neighbor {{ item.neighbor }}
  bfd
  inherit peer LEAF
  remote-as {{ item.remote_as }}

vars
bgp_neighbors:
  - { remote_as: 65336, neighbor: 10.88.145.1 }
  - { remote_as: 65336, neighbor: 10.88.145.7 }
  - { remote_as: 65336, neighbor: 10.88.145.13 }
  - { remote_as: 65336, neighbor: 10.88.145.19 }
  - { remote_as: 65336, neighbor: 10.88.145.25 }
  - { remote_as: 65336, neighbor: 10.88.145.31 }
  - { remote_as: 65336, neighbor: 10.88.145.37 }
  - { remote_as: 65336, neighbor: 10.88.145.43 }

```

##### EXPECTED RESULTS

Expected result was 

S03PDC01(config-router)#   neighbor 10.88.145.1
S03PDC01(config-router-neighbor)#   bfd
S03PDC01(config-router-neighbor)#   inherit peer LEAF
S03PDC01(config-router-neighbor)#   remote-as 65336
S03PDC01(config-router-neighbor)#

##### ACTUAL RESULTS

```
{
    "_ansible_parsed": true,
    "changed": false,
    "_ansible_no_log": false,
    "item": {
        "remote_as": 65336,
        "neighbor": "10.88.145.31"
    },
    "_ansible_item_result": true,
    "failed": true,
    "invocation": {
        "module_args": {
            "force": false,
            "replace": "line",
            "use_ssl": null,
            "port": null,
            "transport": "cli",
            "before": null,
            "parents": null,
            "provider": {
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "ssh_keyfile": null,
                "host": null,
                "timeout": null,
                "use_ssl": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": null,
                "port": null,
                "transport": "cli"
            },
            "save": false,
            "config": null,
            "match": "line",
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "defaults": false,
            "after": null,
            "host": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "src": "router bgp 1\n  neighbor 10.88.145.31\n  bfd\n  inherit peer LEAF\n  remote-as 65336",
            "ssh_keyfile": null,
            "validate_certs": null,
            "lines": null,
            "timeout": null,
            "backup": false
        }
    },
    "msg": "bfd\r\r\n                                       ^\r\n% Invalid command at '^' marker.\r\n\rnx-osv9000-2(config-router-neighbor)# "
```
As you can see it entered BFD inbetween for some reason which was not called by the playbook or the variables. Looks like the module might have called it for unknown reasons.
