### ISSUE TITLE
docker_service doesn't respect "pull: no" parameter when building new image.

### ISSUE THREAD

**Issue by ndrewl** [ansible/ansible#30296]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
docker_service

##### ANSIBLE VERSION

```
ansible 2.3.1.0
configured module search path = Default w/o overrides
python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

ansible.cfg:
```ini
[defaults]
host_key_checking = False
private_key_file = files/keys/ansible
remote_user = root
debug=1
```

##### OS / ENVIRONMENT
Host: CentOS Linux release 7.3.1611 (Core)
Managed: CentOS Linux release 7.3.1611 (Core)

##### SUMMARY
docker_service module doesn't respect "pull: no" parameter.
In my docker_service description I use "pull: no" with "build: yes" in order to build some images, that use some local image (FROM: localimg).

##### STEPS TO REPRODUCE
docker_service task description:
```yml
docker_service:
    pull: no
    build: yes
    project_src: /path-to-project
    files:
      - docker-compose.yml
    state: present
    stopped: yes
```
docker-compose.yml:
```yml
  someservice:
    image: serviceimg
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
```
Dockerfile:
```Dockerfile
FROM localimg
```

##### EXPECTED RESULTS
Expected docker_service to build the image "serviceimg".
Locally it builds:
```bash
docker-compose -f docker-compose.yml build
```
completes successfully.

##### ACTUAL RESULTS
The task fails after "Trying to pull repository docker.io/library/localimg".
