### ISSUE TITLE
crypto/openssl_csr module isn't idempotent, depending on 'extendedKeyUsage' value

### ISSUE THREAD

**Issue by pilou-** [ansible/ansible#30316]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
crypto/openssl_csr.py

##### ANSIBLE VERSION
```
ansible-playbook 2.5.0 (devel 2186b04934) last updated 2017/09/13 23:53:25 (GMT +200)
```

##### OS / ENVIRONMENT
Tested on:
- control host: Debian unstable
- managed hosts: Debian unstable and Fedora 25

##### SUMMARY
Module isn't idempotent, depending on `extendedKeyUsage` parameter value.

In the test case below, [_check_extenededKeyUsage](https://github.com/ansible/ansible/blob/b3cba957e0370b2ff81bd304f2684eaeff1d07f9/lib/ansible/modules/crypto/openssl_csr.py#L365) returns `False` (`True` should be returned).

Related: #30128

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  tasks:
    - openssl_privatekey:
        path: /tmp/private_key.pem

    - openssl_csr:
        path: /tmp/csr.csr
        privatekey_path: /tmp/private_key.pem
        subjectAltName:
          - 'DNS:domain.example'
        keyUsage:
          - digitalSignature
          - keyAgreement
        extendedKeyUsage:
          - DVCS

    - openssl_csr:
        path: /tmp/csr.csr
        privatekey_path: /tmp/private_key.pem
        subjectAltName:
          - 'DNS:domain.example'
        keyUsage:
          - digitalSignature
          - keyAgreement
        extendedKeyUsage:
          - DVCS
      register: idempotent

    - assert:
        that:
          - not idempotent|changed
```

##### EXPECTED RESULTS
```
PLAY [localhost] *********************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [openssl_privatekey]
ok: [localhost] => {"changed": false, "failed": false, "filename": "/tmp/private_key.pem", "fingerprint": {}, "size": 4096, "type": "RSA"}

TASK [openssl_csr] 
changed: [localhost] => {"changed": true, "extendedKeyUsage": ["DVCS"], "failed": false, "filename": "/tmp/csr.csr", "keyUsage": ["digitalSignature", "keyAgreement"], "privatekey": "/tmp/private_key.pem", "subject": {}, "subjectAltName": ["DNS:domain.example"]}

TASK [openssl_csr] 
ok: [localhost] => {"changed": false, "extendedKeyUsage": ["DVCS"], "failed": false, "filename": "/tmp/csr.csr", "keyUsage": ["digitalSignature", "keyAgreement"], "privatekey": "/tmp/private_key.pem", "subject": {}, "subjectAltName": ["DNS:domain.example"]}

TASK [assert] 
ok: [localhost] => {
    "changed": false,
    "failed": false,
    "msg": "All assertions passed"
}
```
##### ACTUAL RESULTS

```
PLAY [localhost] 

TASK [Gathering Facts] 
ok: [localhost]

TASK [openssl_privatekey] 
ok: [localhost] => {"changed": false, "failed": false, "filename": "/tmp/private_key.pem", "fingerprint": {}, "size": 4096, "type": "RSA"}

TASK [openssl_csr] 
changed: [localhost] => {"changed": true, "extendedKeyUsage": ["DVCS"], "failed": false, "filename": "/tmp/csr.csr", "keyUsage": ["digitalSignature", "keyAgreement"], "privatekey": "/tmp/private_key.pem", "subject": {}, "subjectAltName": ["DNS:domain.example"]}

TASK [openssl_csr] 
changed: [localhost] => {"changed": true, "extendedKeyUsage": ["DVCS"], "failed": false, "filename": "/tmp/csr.csr", "keyUsage": ["digitalSignature", "keyAgreement"], "privatekey": "/tmp/private_key.pem", "subject": {}, "subjectAltName": ["DNS:domain.example"]}

TASK [assert] 
fatal: [localhost]: FAILED! => {
    "assertion": "not idempotent|changed",
    "changed": false,
    "evaluated_to": false,
    "failed": true
}
```
