### ISSUE TITLE
vmware_guest module: "Failed to find a matching datastore

### ISSUE THREAD

**Issue by aalamil** [ansible/ansible#30327]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

`vmware_guest` module fails to locate the datastore and cannot create a VM. 

```Error: "msg": "Failed to find a matching datastore"```
##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: vcenter > create vms
    vmware_guest:
      name: "anstest001"
      state: present
      disk:
        - size_gb: 40
          type: thin
          datastore: datastore-01
      datacenter: "Prod Datacenter"
      cluster: "Cluster01"
      folder: "/vm"
      guest_id: "'windows8_64Guest'"
      validate_certs: "False"
      hostname: "server.vcenter.local"
      username: "ansible_prod@vcenter.local"
      password: "XXXXXX"
```

##### EXPECTED RESULTS

VM created in the given datastore
##### ACTUAL RESULTS

```
$ ansible-playbook vcenter.yml -vvv
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available

PLAYBOOK: vcenter.yml **********************************************************
1 plays in vcenter.yml

PLAY [localhost] ***************************************************************
META: ran handlers

TASK [vcenter > create vms] ****************************************************
task path: /var/tmp/vcentre/vcenter.yml:7
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1505363022.6-57117833522760 `" && echo ansible-tmp-1505363022.6-57117833522760="` echo /root/.ansible/tmp/ansible-tmp-1505363022.6-57117833522760 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp24a_o8 TO /root/.ansible/tmp/ansible-tmp-1505363022.6-57117833522760/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1505363022.6-57117833522760/ /root/.ansible/tmp/ansible-tmp-1505363022.6-57117833522760/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1505363022.6-57117833522760/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1505363022.6-57117833522760/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "Cluster 01",
            "customization": {},
            "customvalues": [],
            "datacenter": "Prod Datacenter",
            "disk": [
                {
                    "datastore": "datastore-01",
                    "size_gb": 40,
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": "'windows8_64Guest'",
            "hardware": {},
            "hostname": "server.vcenter.local",
            "is_template": false,
            "name": "anstest001",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "state": "present",
            "template_src": null,
            "username": "ansible_prod@vcenter.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "Failed to find a matching datastore"
}
        to retry, use: --limit @/var/tmp/vcentre/vcenter.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

```

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@aalamil Thanks for reporting this issue. Could you please provide output of [govc find /](https://github.com/vmware/govmomi/tree/master/govc) ?

**Comment by coltsixshooter** [comment]
Ran into the same problem with 2.4 and found that the Cluster option is not returning the correct hosts in the cluster. It returned a host that did not have that datastore. Changed to use esxi_hostname and it worked. I need to put in a bug report on just this issue.

**Comment by kerugu** [comment]
Hi,
We have a similar issue, and we raised ticket to RedHat, but we were suggested to put our comments in here.
Summary: We have a problem during VM Termination, Tower throws Error "FAiled To Find a Matching DataStore".
Details:
Initially we had the issue during VM creation in VCenter, then we have modified the vmware_guest.py(modified file attached as a zip), and then we were good and provisioning working fine. Before fixing the issue termination was fine. But since Provisioning had problem we have to fix the module code. Since then we are seeing issue with termination. This is a production blocker for us. Immidiate response is appreciated.

![vmwareterminationfailed_tower](https://user-images.githubusercontent.com/26670070/30887159-21cf4f00-a2e8-11e7-80f7-53b796cd42f0.JPG)
[vmware_guest (2).zip](https://github.com/ansible/ansible/files/1335205/vmware_guest.2.zip)

**Comment by Akasurde** [comment]
@kerugu Could you please provide your playbook used for termination of VM?

**Comment by kerugu** [comment]
Please find attached termination playbook

[termination_playbook.txt](https://github.com/ansible/ansible/files/1341929/termination_playbook.txt)

**Comment by kerugu** [comment]
I didnt hear back anything on this, can you please provide an update, with findings and do we have a fix for this

**Comment by Akasurde** [comment]
@kerugu I am assuming that you are facing issue while VM poweroff operation (screenshot). There is a new module [vmware_guest_powerstate](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_powerstate.py) which can manage powerstate of VMs. Could you please try this module and let me know if it works for you ? Also, let me know if my assumption is wrong.

**Comment by kerugu** [comment]
Hi,
Basically we need to terminate(remove the VM from VCenter), to do that first we do a poweredoff and then we do absent. So obviously if powerdoff we have to go the module, then it will fail in next step, hope you have seen the code i sent there are 2 tasks in it.
For now in VMWARE_GUEST module code itself to remove the VM, its given to use below code snippet, can we go ahead with it Or do you have any other module which can do that. Also please confirm if we are going to use the one below, does the UUID in VCenter database will have index, because the data will be huge in the Production.
module: vmware_guest
        validate_certs: False
        name: 'MQ-NJ09APP10107'
        uuid: '42286d37-96e6-201a-d28a-41089d150970'
        state: poweredoff
Does Poweredoff will also remove the VM from VCenter, as per our test its removing, but need a double confirmation

**Comment by Akasurde** [comment]
@kerugu poweredoff does not remove virtual machine, only 'absent' state will remove the virtual machine. 

If you could run following playbook and provide output. This will help me to find if it actually working in your environment. I am using your machine's UUID.

```yaml
- name: Find Guest's Folder using UUID
  vmware_guest_find:
    hostname: your_esxi_hostname
    username: username
    password: password
    validate_certs: no
    uuid: 42286d37-96e6-201a-d28a-41089d150970
```

**Comment by kerugu** [comment]
In place of hostname is it esxi_hostname or can i place just my hostname which i want to terminate

**Comment by kerugu** [comment]
Hi
Which version of Ansible has the vmware_guest_find. Currently we are using 2.3.0 Ansible, and looks like the module is not present with this version

**Comment by Akasurde** [comment]
It is added in version 2.4. Could you please ping me (akasurde) on #ansible-vmware channel so that  I can help you ?

**Comment by kerugu** [comment]
Is there a way we can get into a call and you can guide me. Shall i send a zoom meeting link after an hour from now? I mean 1.30PM EST

**Comment by Akasurde** [comment]
@kerugu I am not sure about this. Could you please ping me (akasurde) on irc channel #ansible-vmware ? I or someone else will be able to help you out.

**Comment by Akasurde** [comment]
@kerugu hostname in above example is hostname of ESXi server and NOT hostname of VM which you want to terminate.

Can you please run [this](https://github.com/jctanner/ansible-tools/blob/master/vmware/vmware_walk.py) simple script with your environment ? this will give us a better idea about VM.

**Comment by jctanner** [comment]
needs_info

**Comment by ansibot** [comment]
cc @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by karniemi** [comment]
Updated from ansible-2.3.1.0-3.el7.noarch to ansible-2.4.0.0-5.el7.noarch. And here we are. When testing the new version,  the very first task in the very first playbook failed for this issue.  The task tries to use vmware_guest module to set the state of managed VMs to "poweredoff".

**Comment by Akasurde** [comment]
@karniemi Could you please paste your playbook here so that I can take a look?

**Comment by karniemi** [comment]
```yaml
---

- hosts: snapshooted-vms
  gather_facts: no
  serial: "100%"
  vars:
    vcenter:
      hostname: ourvcenterhostname
      username: ouruser@ourdomain
      password: ourpassword
    tasks:
      - name: Power-off vms
        vmware_guest:
          hostname: "{{ vcenter.hostname }}"
          username: "{{ vcenter.username}}"
          password: "{{ vcenter.password}}"
          datacenter: OURDATACENTERNAME
          folder: "/{{ vcenter_folder }}" ##defined per lab in inventory
          name: "{{ inventory_hostname }}"
          state: poweredoff
        delegate_to: localhost
```

Edit: surround code with triple backticks. The Github editor only adds single backticks when pressing "Insert code"...

**Comment by karniemi** [comment]
...hmmm...."insert code" does not seem to be working in github...or I'm not intelligent enough to know how to use it...

**Comment by Akasurde** [comment]
@karniemi Can you paste error message as well ? You can use [vmware_guest_powerstate](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_powerstate.py) to manage powerstate of VMs.

**Comment by karniemi** [comment]
@Akasurde: we added some debug logs to the vmware modules (using proper python logger)...  to pin-point the regression.  In [vmware.py](https://github.com/ansible/ansible/blob/stable-2.4/lib/ansible/module_utils/vmware.py) , in method find_vm_by_id(), in "inventory_path"-code branch, there's the call for "f_obj = si.FindByInventoryPath(searchpath)": it does not work for the playbook I posted above. The playbook did work in ansible-2.3.1.0-3.el7. For example, in one of our inventory "vcenter_folder" is defined as "lab2" which is a folder in our vcenter and contains VMs for that lab. Before upgrading ansible, it was was working fine. By trial and error, we discovered that we can work around this regression by defining the folder as "OURDATACENTERNAME/vm/{{ vcenter_folder }}".

**Comment by john-at-p1technologies** [comment]
Having the same issue.  
Implemented @karniemi work-around (ie defining the folder by prefixing with the _[datacentername]_) and it is working great.

**Comment by jamescassell** [comment]
since @karniemi's workaround was confusing to me, here's the workaround as it worked for me:
```yaml
vmware_guest:
...
    folder: "{{ vmware_datacenter + '/vm/' + vmware_folder }}"
...
```
Previously, I'd had:
```yaml
vmware_guest:
...
    folder: "{{ vmware_folder }}"
...
```

**Comment by jhriv** [comment]
```yaml
  - name: Find the vm
    vmware_guest_find:
      hostname: '{{ vmware_host }}'
      name: '{{ vm_hostname }}'
      password: '{{ vmware_pass }}'
      username: '{{ vmware_user }}'
      datacenter: '{{ vmware_datacenter.name }}'
      validate_certs: false
    register: found
  - debug: var=found

  - name: Query the vm
    vmware_guest:
      hostname: '{{ vmware_host }}'
      name: '{{ vm_hostname }}'
      password: '{{ vmware_pass }}'
      username: '{{ vmware_user }}'
      datacenter: '{{ vmware_datacenter.name }}'
      folder: '{{ vmware_datacenter.name }}/{{ found.folders[0] }}'
      validate_certs: false
    register: out
```
worked for me. Thank you,  @karniemi and @john-at-p1technologies 

Additional note: Ansible 2.4.1.0 lacks any vmware_guest_powerstate module
