### ISSUE TITLE
iam_server_certificate_facts - return value indexing by cert_name is difficult to work with

### ISSUE THREAD

**Issue by JohnVonNeumann** [ansible/ansible#30325]
##### ISSUE TYPE

 - Improvement

##### COMPONENT NAME

aws/ec2/iam_server_certificate_facts

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/lw/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lw/code/work/ansible/venv-27-ans/local/lib/python2.7/site-packages/ansible
  executable location = /home/lw/code/work/ansible/venv-27-ans/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

No changes made to default config.

##### OS / ENVIRONMENT

Linux Ubuntu 16.04 - Running from a virtualenv, installed via
pip install git+git://github.com/ansible/ansible.git@devel

##### SUMMARY

When searching for a valid server_cert with the module, I wish to utilise the returned ARN for downstream use in an Application Load Balancer provisioning task. In many other fact-finding modules, the module would provide return-values indexed by integers or similar generic/non-specific terms. In this module however, it returns by the name you searched by. This feels, and has so far shown to be too circular. If I know the name of the thing I am searching by, chances are, I need further, more detailed information of the item, not the name. 

##### STEPS TO REPRODUCE

The problem here that I see, is that I search by name, then have to search for the index by name. This is too circular. Other modules implement this perfectly, for example, I can search for vpc subnets with ec2_vpc_subnet_facts like so, and receive a more sensible output:

```yaml
# Application load balancer task
- name: gathering and declaring facts about VPC subnets for use by apploadbal creation
  ec2_vpc_subnet_facts:
    region: "{{ aws_region }}"
    filters:
      vpc-id: "{{ aws_vpc }}"
  register: vpc_subnet_list

- debug:
    msg: "{{ vpc_subnet_list }}"

Output:
TASK [aws_elb_create_alb : debug] ****************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false, 
        "failed": false, 
        "subnets": [
            {
                "availability_zone": "ap-southeast-2c", 

#Then to utilise the indexing:
- name: setting vpc_subnet facts for use in playbooks concerning placement of infrastrucutre
  set_fact:
    vpc_subnet_1: "{{ vpc_subnet_list.subnets[0]['id'] }}"
    vpc_subnet_2: "{{ vpc_subnet_list.subnets[1]['id'] }}"
    vpc_subnet_3: "{{ vpc_subnet_list.subnets[2]['id'] }}"

```
As you can see here, I can use the friendly `vpc_subnet_list.subnets[0]['id']` to find the thing I need.

However, in the iam_server_certificate_facts module, finding the thing I need is more troublesome:

```yaml
- name: retrieving and declaring server_certifcate fact
  iam_server_certificate_facts:
  register: server_certs

- debug:
    msg: "{{ server_certs }}" 

TASK [aws_elb_create_alb : debug] ****************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "changed": false, 
        "failed": false, 
        "failed_when_result": false, 
        "results": {
            "terrible-example-name": {
                "arn": "arn:aws:iam::1234567789123:server-certificate/terrible-example-name", 

```

The problem that I see here is two fold, it's redundant, having to search by the name, then include the name in the index, and it's also difficult (from my understanding) to keep secrets out of your playbooks, in order to continue to use this, I need to search securely by using external vars, to find the cert, then use the name in plaintext inside the playbook to index. 

##### EXPECTED RESULTS
What I would expect in this situation is to just receive the JSON field with the information I need to find, with an easy way to navigate into it. I would expect it to work in the same way all other fact finding modules work. 

##### ACTUAL RESULTS
What actually happens is an irregular experience, I have to search for the item by name, then use the same name as an index value to find my way into the JSON dict I want to use. This feels redundant. 

If I have used incorrect language in this issue, please pull me up on it, I wish to be as clear as possible when I write these up. I am still learning.
