### ISSUE TITLE
network modules integration test fail if provider transport value in not set

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#30331]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

eos_*
nxos_*
##### ANSIBLE VERSION

```
2.4
```

##### STEPS TO REPRODUCE

```yaml
- name: Enable Ethernet1 interface and disable switchport
  eos_config:
    lines:
      - no shutdown
      - no switchport
    parents: int Ethernet1
    authorize: yes
```

##### EXPECTED RESULTS

This should run sucessfully
##### ACTUAL RESULTS

```
{
"changed": false, 
"failed": true, 
"msg": "value of transport must be one of: cli,eapi, got: None found in provider"
}
```
