### ISSUE TITLE
os_keypair should allow force update instead of raising error

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#30334]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
os_keypair

##### ANSIBLE VERSION
```
2.4.x
```

##### SUMMARY

Current behaviour of os_keypair is to throw an error if the proposed key has a different signature than the new one. This "safe" behaviour is against automation usages and more inclined for command usage patterns, where you can assume that the user made a mistake.

Now the workaround code for forcing the update of the key looks really ugly and you can see it below. 

We need an option that would tell the module if the key should be removed and readded instead of throwing an error, like an `force` parameter.

##### STEPS TO REPRODUCE

```yaml
- name: Add keypair
  os_keypair:
      cloud: "{{ provision.cloud | default(omit) }}"
      name: "{{ prefix }}{{ provision.key.file | basename }}"
      public_key: "{{ public_key_content.stdout }}"
      state: present
  register: key
  ignore_errors: True

# This block runs only if previous task failed, and forces the key update
- block:
  - name: Remove old keypair
    os_keypair:
        cloud: "{{ provision.cloud | default(omit) }}"
        name: "{{ prefix }}{{ provision.key.file | basename }}"
        public_key: "{{ public_key_content.stdout }}"
        state: absent

  - name: Add updated keypair
    os_keypair:
        cloud: "{{ provision.cloud | default(omit) }}"
        name: "{{ prefix }}{{ provision.key.file | basename }}"
        public_key: "{{ public_key_content.stdout }}"
        state: present
    register: key

  when:
    - key.failed
    - '"present but key hash not the same as offered. Delete key first." in key.msg'
```

##### ACTUAL RESULTS

```

```
