### ISSUE TITLE
How set ansible_ssh_common_args: for delegate_to: 

### ISSUE THREAD

**Issue by LuckySB** [ansible/ansible#30348]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
delegate_to:

##### ANSIBLE VERSION

```
ansible 2.4.0-100.git201708150932.e9c9473819.devel.el7.centos
```

##### OS / ENVIRONMENT
Centos7

##### SUMMARY
playbook.yml:

```yaml
- hosts:
  - all
  vars:
    - ansible_ssh_user: "{{ ansible_user | default('ansible',boolean=True) }}"
    - ansible_ssh_port: "{{ ansible_port | default(48022,boolean=True) }}"
    - ansible_ssh_common_args: "{{ (ansible_ssh_proxy is undefined) | ternary('', '-o ProxyCommand=\"sshpass -p ' ~ ansible_password ~ ' ssh -W %h:%p -q ' ~ ansible_ssh_user ~ '@' ~ ansible_ssh_proxy | default('',boolean=True) ~ ' -p' ~ ansible_ssh_port ~ ' \"') }}"
  roles:
    - init-variables
    - base
```

when i need play ansible on host with gray address i set ansible_ssh_proxy: in inventory
and playbook run on host via ProxyCommand

but on task with delegate_to: another_host ansible uses ansible_ssh_common_args: from playbook
i try set ansible_ssh_common_args to '', but this do not working:

```yaml
- set_fact:
    ansible_ssh_common_args_bak: "{{ ansible_ssh_common_args }}"

- set_fact:
    ansible_ssh_common_args: !!null

- name: test task
  command: pwd
  delegate_to: another.host.com

- set_fact:
    ansible_ssh_common_args: "{{ ansible_ssh_common_args_bak }}"
```

ssh connect to another,host,com try with -o ProxyCommand=
