### ISSUE TITLE
"dellos*" module timeout

### ISSUE THREAD

**Issue by markgoddard** [ansible/ansible#30350]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
dellos*_* network modules

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
CentOS 7.3 control host, executing against Dell OS6 and Dell OS9 switches.

##### SUMMARY
This issue is essentially the same as https://github.com/ansible/ansible/issues/23881, but for Dell switches. I have tested against OS6 and OS9 switches, but don't have access to OS10. It's likely to have the same issue, looking at the code.

##### STEPS TO REPRODUCE

Execute the following playbook, with a Dell OS9 switch in the switches group. For Dell OS6 switches, use the dellos6_command module. This also fails with the dellos*_config modules.

```yaml
---
- hosts: switches
  gather_facts: False                                                                                                                                                                                       
  vars:
    switch_dellos_provider:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      transport: cli
  tasks:
    - dellos9_command:
        provider: "{{ switch_dellos_provider }}"
        commands: 
          - show version 
      delegate_to: localhost
```

##### EXPECTED RESULTS
The command is executed on the switch.

##### ACTUAL RESULTS
```
Loading callback plugin default of type stdout, v2.0 from /opt/alaska/alt-1/kayobe/kayobe-venv/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test-dellos9.yml *********************************************************************************************************************************************************************************
1 plays in ansible/test-dellos9.yml

PLAY [ctl-switches] ****************************************************************************************************************************************************************************************
META: ran handlers

TASK [dellos9_command] *************************************************************************************************************************************************************************************
task path: /opt/alaska/alt-1/kayobe/ansible/test-dellos9.yml:11
<localhost> using connection plugin network_cli
<localhost> socket_path: /home/stack/.ansible/pc/f97e48e6de
<localhost> using connection plugin network_cli
<localhost> socket_path: /home/stack/.ansible/pc/f97e48e6de
open_shell() returned 255  failed to connect to control socket
fatal: [ethsw-b16-u38 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell", 
    "rc": 255
}
open_shell() returned 255  failed to connect to control socket
fatal: [ethsw-b17-u42 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell", 
    "rc": 255
}
        to retry, use: --limit @/opt/alaska/alt-1/kayobe/ansible/test-dellos9.retry

PLAY RECAP *************************************************************************************************************************************************************************************************
ethsw-b16-u38              : ok=0    changed=0    unreachable=0    failed=1   
ethsw-b17-u42              : ok=0    changed=0    unreachable=0    failed=1   

Kayobe playbook(s) ansible/test-dellos9.yml exited 2
```
