### ISSUE TITLE
Using the Jinja2 filter "| int" to convert a string to an integer in PB doesn't work.

### ISSUE THREAD

**Issue by bdlamprecht** [ansible/ansible#30366]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible Filters (based off of Jinja2 "builtin filters")

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0.0 (stable-2.4 2439dc24e9) last updated 2017/09/14 09:12:50 (GMT -600)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /home/bl839s/ansible/lib/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
No configuration changes.

##### OS / ENVIRONMENT
N/A

##### SUMMARY
According to the documentation found [here](http://docs.ansible.com/ansible/latest/playbooks_filters.html), Jinja2 "builtin" filters should work in playbooks as well as templates.  

##### STEPS TO REPRODUCE
Using the `stable-2.4` branch listed above, run the following PB which demonstrates the error:

```yaml
- name: Testing Casting
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    - an_int: '15'

  tasks:

    - debug:
        msg: "{{ an_int | int }}"
```
And when it is run:
```
PLAY [Testing Casting] ********************************************************************

TASK [debug] ******************************************************************************
ok: [localhost] => {
    "msg": "15"
}
```
However, if the PB is altered to create it initially as an `int` and remove the casting:
```
- name: Testing Casting
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    - an_int: 15

  tasks:

    - debug:
        msg: "{{ an_int }}"
```
And when THIS is run:
```
PLAY [Testing Casting] ********************************************************************

TASK [debug] ******************************************************************************
ok: [localhost] => {
    "msg": 15
}
```
Notice the lack of quotes `"`.
This causes issues for me when working with JSON data which I'll provide an example of later today.

##### EXPECTED RESULTS
See above.

##### ACTUAL RESULTS
See above.

**Comment by sivel** [comment]
Unfortunately due to how jinja2 works, it technically only has the ability to return strings.  Any time you use jinja2 templating, the result comes out as a string.  So while `|int` is internally converting the value to an int, the final result from jinja2 is a string.

We have some type guessing capabilities, but that typically only works when there is no jinja2 pipeline in the templating, instead when it is just an individual variable.

I'll still leave this open, as I'm unsure right now how feasible it is to handle this in the current implementation.

**Comment by bdlamprecht** [comment]
In [this](https://gist.github.com/bdlamprecht/9c937547f8f5dad6f92f0e91c29f30fc) GitHub Gist you can see what I'm referring to concerning how failing to cast a string to an integer causes problems when using an API.

---

# Explanation Of Files in Gist:

The `gen_invfacts.yml` is simply the PB that is run with `ansible-playbook`.

The `non_working_main.yml` is the `main.yml` file in the `tasks` of the role `inv_facts` in a non-working state.
And the `non_working_output.txt` is the results of running that role with the error.

The `working_main.yml` is the `main.yml` file in the `tasks` of the role `inv_facts` in a **_working_** state.
Similarly, the `working_output.txt` is the results of running the role **_without_** the error.

# Interpretation of Differences:

The only thing that changed between the two `.yml` files are on line 34 of each.

In the non-working example, `dev_pri_int` is created using the previously defined variable `dev_pri_addr_id` which is created from the JSON data.
In the **_working_** example, `dev_pri_int` created using the exact value from the JSON data.

# Outcome

If this problem isn't resolved, it will cause extremely long lines in `.yml` files as referencing the same JSON data again and again is cumbersome and, in my opinion, not a good practice.

**Comment by dgjustice** [comment]
Try this:
```
selectattr('id', 'equalto', dev_pri_addr_id|int)
```

**Comment by bdlamprecht** [comment]
@dgjustice did fix my problem.

However, but I still think it would be worthwhile to solve the issue in a future release of Ansible?
Perhaps v2.6 since v2.5 is already under development?

**Comment by dgjustice** [comment]
Per comments by @sivel , I believe this is "as-designed" behaviour.  It's not a bug (IMHO), it's simply a matter of using the tools in an appropriate manner.

**Comment by dagwieers** [comment]
There is hope for a better future at: https://github.com/pallets/jinja/pull/708

I am going to close this ticket, because we have plenty of identical tickets open. Currently Jinja2 only returns strings, we are trying to change that for Ansible.

**Comment by bdlamprecht** [comment]
That does look promising, thanks for linking to the discussion.

**Comment by ArtemChekunov** [comment]
Hello there,

maybe my this can help someone else
consul config should have correct json 
so I had same problem with `bootstrap_expect: "{{groups['consul-server']|length}}"`
because bootstrap_expect should be int
so I solve it by this hack

```
  tasks:
    - name: install python-docker
      package:
        name: python-docker

    - name: define consul server list
      set_fact:
        CONSUL_LOCAL_CONFIG: |
          server: true
          ui: true
          skip_leave_on_interrupt: true
          bind_addr: {{ansible_default_ipv4.address}}
          client_addr: {{ansible_default_ipv4.address}}
          retry_join: {{groups['consul-server']|to_json}}
          bootstrap_expect: {{groups['consul-server']|length}}
          ports:
            http: 80
            dns: 53

    - name: consul-server
      docker_container:
        name: consul-server
        image: consul
        pull: yes
        state: started
        restart_policy: always
        network_mode: host
        env:
          CONSUL_ALLOW_PRIVILEGED_PORTS:
          CONSUL_LOCAL_CONFIG: "{{CONSUL_LOCAL_CONFIG|from_yaml|to_json}}"
        command: "agent"
        volumes:
          - /srv/consul:/consul/data
```
