### ISSUE TITLE
docker_container sends exit signal on state: started

### ISSUE THREAD

**Issue by rwaweber** [ansible/ansible#30377]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```
##### SUMMARY

It appears like ^D(control-d) is sent to STDIN once the container has started. 
Apologies in advance for all of the logstash stuff below, just the particular area where I ran into this issue. 

##### STEPS TO REPRODUCE
As the control, I would recommend using the `docker.elastic.co/logstash/logstash:5.6.0` base image, and then build an image using the following Dockerfile and directories I describe below:
```Dockerfile
FROM docker.elastic.co/logstash/logstash:5.6.0
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
RUN logstash-plugin remove x-pack
ADD pipeline/ /usr/share/logstash/pipeline/
ADD config/ /usr/share/logstash/config/
```

I would then recommend creating the above referenced directories and files:
Tried to make the below as copy and paste-able as possible.
```bash
mkdir {pipeline,config}
logstashyml='http.host: 0.0.0.0\npath.config: /usr/share/logstash/pipeline\nlog.level: "debug"'
logstashcfg='input {
  stdin {
  }
}

output {
  stdout { codec => rubydebug }
}'
echo -e $logstashyml > config/logstash.yml
echo -e $logstashcfg > pipeline/logstash.conf
docker build -t rwaweber-issue .
```

##### Control Playbook, run this twice
Second run, nothing should change
```yaml
- name: start logstash container
  docker_container:
    name: issue
    state: started
    image: docker.elastic.co/logstash/logstash:5.6.0
    command: ["/usr/share/logstash/bin/logstash","-f","/usr/share/logstash/pipeline"]
```
##### Experiment Playbook, run this twice
Second run should show that the start step changed
```yaml
- name: start logstash container
  docker_container:
    name: issue
    state: started
    image: rwaweber-issue:latest
    command: ["/usr/share/logstash/bin/logstash","-f","/usr/share/logstash/pipeline"]
```
Retrieving logs(through `docker logs $image_hash` from the above container should have some lines that look like:
```
[2017-09-14T16:03:51,921][INFO ][logstash.pipeline        ] Pipeline main started
[2017-09-14T16:03:51,928][DEBUG][logstash.inputs.stdin    ] stopping {:plugin=>"LogStash::Inputs::Stdin"}
[2017-09-14T16:03:51,944][DEBUG][logstash.inputs.stdin    ] closing {:plugin=>"LogStash::Inputs::Stdin"}
[2017-09-14T16:03:51,947][DEBUG][logstash.pipeline        ] Input plugins stopped! Will shutdown filter/output workers.
```
Specifically, the line at `[2017-09-14T16:03:51,928]` leads me to believe that the stdin input plugin is causing logstash to exit.
 
##### EXPECTED RESULTS
I would expect the experiment container to continue to run with the stdin codec enabled in the logstash container.

##### ACTUAL RESULTS
The experiment container exited with status code 0, seemingly from having ^D sent to STDIN
