### ISSUE TITLE
unarchive, incorrect value in verbose output for 'src' parameter

### ISSUE THREAD

**Issue by mxlan** [ansible/ansible#30375]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
unarchive module

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
This also affects 2.2.1.0, I did not go back any further, the example playbook will only work in 2.3 because it uses archive, replace that with a command call to tar -zcf to run in 2.2.1.0, and replace the lineinfile path parameter with 'dest' instead

##### CONFIGURATION
N/A no ansible.cfg

##### OS / ENVIRONMENT
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

##### SUMMARY
Within the output that ansible generates during a playbook run the unarchive module outputs incorrect information for the 'src' parameter seen when run with high verbosity.

##### STEPS TO REPRODUCE

You can run the following playbook to generate an archive and extracts that archive within your /tmp directory
ansible-playbook test.yml -vvv -t archive,unarchive

```yaml
# Creates Archive in /tmp/test
#
# usage:
# ansible-playbook test.yml -vvv -t archive,unarchive
#
# Should result in txt file back in /tmp/test/somedir
#
# note: only '/tmp/test/somfile.txt' will be removed not the directory
#
# Same issue on error
#
# tags:
# - archive   : generate archive (removes source see above)
# - unarchive : attempt to extract archive
# - clean     : cleanup the directory
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    tmp_dir: "/tmp/test"
    source_dir: "{{tmp_dir}}/somedir"
    file: "somefile.txt"
    line: "This is some text"
    archive: "somefile.tar.gz"
  tasks:
  - block:
    - name: "Create directory"
      file:
        path: "{{source_dir}}"
        state: "directory"
      tags:
      - archive
    - name: "Create file"
      file:
        path: "{{source_dir}}/{{file}}"
        state: touch
      tags:
      - archive
    - name: "Add lines to file"
      lineinfile:
        path: "{{source_dir}}/{{file}}"
        line: "{{line}}"
        state: "present"
      tags:
      - archive
    - name: "Archive directory"
      archive:
        path: "{{source_dir}}"
        dest: "{{tmp_dir}}/{{archive}}"
        format: "gz"
        remove: "yes"
      tags:
      - archive
    - name: "Unarchive"
      unarchive:
        src: "{{tmp_dir}}/{{archive}}"
        dest: "{{tmp_dir}}"
      tags:
      - unarchive
    always:
    - name: "Attempt Cleanup"
      file:
        path: "{{tmp_dir}}"
        state: absent
      tags: clean

```

##### EXPECTED RESULTS

```
I should see within the output something that looks like the following, note the "src" value

changed: [localhost] => {
    "changed": true, 
    "dest": "/tmp/test", 
    "extract_results": {
        "cmd": [
            "/bin/tar", 
            "--extract", 
            "-C", 
            "/tmp/test", 
            "-z", 
            "-f", 
            "/tmp/test/somedir"
        ], 
        "err": "", 
        "out": "", 
        "rc": 0
    }, 
    "gid": 1000, 
    "group": "REDACTED", 
    "handler": "TgzArchive", 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "content": null, 
            "copy": true, 
            "creates": null, 
            "delimiter": null, 
            "dest": "/tmp/test", 
            "directory_mode": null, 
            "exclude": [], 
            "extra_opts": [], 
            "follow": false, 
            "force": null, 
            "group": null, 
            "keep_newer": false, 
            "list_files": false, 
            "mode": null, 
            "original_basename": "somefile.tar.gz", 
            "owner": null, 
            "regexp": null, 
            "remote_src": false, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/tmp/test/somedir", 
            "unsafe_writes": null, 
            "validate_certs": true
        }
    }, 
    "mode": "0775", 
    "owner": "REDACTED", 
    "size": 4096, 
    "src": "/tmp/test/somedir", 
    "state": "directory", 
    "uid": 1000
}
```

##### ACTUAL RESULTS

```
changed: [localhost] => {
    "changed": true, 
    "dest": "/tmp/test", 
    "extract_results": {
        "cmd": [
            "/bin/tar", 
            "--extract", 
            "-C", 
            "/tmp/test", 
            "-z", 
            "-f", 
            "/home/REDACTED/.ansible/tmp/ansible-tmp-1505408941.79-176782471747563/source"
        ], 
        "err": "", 
        "out": "", 
        "rc": 0
    }, 
    "gid": 1000, 
    "group": "REDACTED", 
    "handler": "TgzArchive", 
    "invocation": {
        "module_args": {
            "attributes": null, 
            "backup": null, 
            "content": null, 
            "copy": true, 
            "creates": null, 
            "delimiter": null, 
            "dest": "/tmp/test", 
            "directory_mode": null, 
            "exclude": [], 
            "extra_opts": [], 
            "follow": false, 
            "force": null, 
            "group": null, 
            "keep_newer": false, 
            "list_files": false, 
            "mode": null, 
            "original_basename": "somefile.tar.gz", 
            "owner": null, 
            "regexp": null, 
            "remote_src": false, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": "/home/REDACTED/.ansible/tmp/ansible-tmp-1505408941.79-176782471747563/source", 
            "unsafe_writes": null, 
            "validate_certs": true
        }
    }, 
    "mode": "0775", 
    "owner": "REDACTED", 
    "size": 4096, 
    "src": "/home/REDACTED/.ansible/tmp/ansible-tmp-1505408941.79-176782471747563/source", 
    "state": "directory", 
    "uid": 1000
}

```
