### ISSUE TITLE
should document how to do when_failed equivalent in 1.2, jinja2 filter?

### ISSUE THREAD

**Issue by jhoekx** [ansible/ansible#3039]
One of my playbooks was failing in devel, while it was working fine in 1.1.

This is the simplified case:

```

---

- hosts: firefly
  connection: local
  tasks:
  - action: method_fail
    register: pip_install
    ignore_errors: yes
  - action: ping
    when_failed: ${pip_install}
```

With method_fail:

```
#!/bin/bash

cat <<EOF
{"ansible_facts": {
    "res": "line 152, in setup\n        dist.run_commands()\n",
    "failed": true
}
}
EOF
```

The failure is caused by the checks in safe_eval. There is a python backtrace in pip_install because my previous task failed.

I think the simple regex will give more false positives (and question the security of it with weird quoting rules, but I can't back up that statement).
