### ISSUE TITLE
nmcli does not support 'primary' parameter

### ISSUE THREAD

**Issue by ewigkeit1204** [ansible/ansible#30405]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel c027ad943e) last updated 2017/09/15 11:22:29 (GMT +900)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
nmcli does not support 'primary' parameter documented as usable.

##### STEPS TO REPRODUCE
```yaml
- nmcli:
    type: bond
    conn_name: bond0
    ifname: bond0
    mode: 'active-backup'
    primary: 'ens224'
    ip4: '172.16.10.2'
    gw4: '172.16.10.1'
    state: present
```

##### EXPECTED RESULTS
Task is completed successfully.

##### ACTUAL RESULTS
Error occurs with a following message.

```
TASK [nmcli] ******************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (nmcli) module: primary Supported parameters include: ageingtime,arp_interval,arp_ip_target,autoconnect,conn_name,dns4,dns6,downdelay,egress,flags,forwarddelay,gw4,gw6,hellotime,ifname,ingress,ip4,ip6,mac,master,maxage,miimon,mode,mtu,priority,slavepriority,state,stp,type,updelay,vlandev,vlanid"}
```
