### ISSUE TITLE
win_iis_website module failed without not an essential parameter 'physical_path'

### ISSUE THREAD

**Issue by mikalai-t** [ansible/ansible#30412]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_iis_website

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /home/user/Ansible/ansible.cfg
  configured module search path = [u'./library/']
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT
Ansible-master = Ubuntu 14.04
Inventory host = Windows Server 2016

##### SUMMARY

```win_iis_website``` module fails when only 'name' parameter is specified

##### STEPS TO REPRODUCE

```yaml
---
- hosts: iis_webserver
  gather_facts: False

  tasks:
  - name: get web-site configuration
    win_iis_website:
      name: MyWebSite
    register: webSiteConfig
```

##### EXPECTED RESULTS

```webSiteConfig``` variable contains site's parameters according to the example from module documentation page (http://docs.ansible.com/ansible/latest/win_iis_website_module.html)

##### ACTUAL RESULTS

```
TASK [get web-site configuration] **************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_iis_website.ps1
<iis_webserver> ESTABLISH WINRM CONNECTION FOR USER: ansible@domain on PORT 5986 TO iis_webserver
EXEC (via pipeline wrapper)
fatal: [iis_webserver]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "missing required arguments: physical_path"
}
```
