### ISSUE TITLE
Conditional Logic Causes Module Failure: $name.ToLower is not valid for INT data type

### ISSUE THREAD

**Issue by Axelay-Prime** [ansible/ansible#30431]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

win_regedit.ps1 

##### ANSIBLE VERSION

```
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### OS / ENVIRONMENT
From RHEL7 to Win2k12

##### SUMMARY
If a registry change has value specified as an INT (not surrounded in quotes) the testing logic in the module causes the module to fail when it attempts to use the 'ToLower' method, so it seems that method isn't valid for an INT data type.

It is a very hacky lazy work around, but I was able to test and validate that this works. And I am including it in case it helps to illustrate the issue (not as a fix).

```powershell
if ($name -ne $null) {$name = $name.ToString()}
```

##### STEPS TO REPRODUCE
Here is an example that causes the module to fail:
```yaml
- name: "create key '1'"
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\TrapConfiguration\TEST
    value: 1
    state: present
```

The error message shows that the ToLower test is not valid (INT data type)

```powershell
if ($name -eq \"\" -or ($name -ne $null -and $name.ToLower() -eq \"(default)\"))
```

```python
fatal: [test12]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Method invocation failed because [System.Int32] does not contain a method \r\nnamed 'ToLower'.\r\nAt line:153 char:5\r\n+ if ($name -eq \"\" -or ($name -ne $null -and $name.ToLower() -eq \"(default)\")) \r\n{\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRec \r\n   ordException\r\n    + FullyQualifiedErrorId : MethodNotFound\r\n \r\n\r\n", "module_stdout": "\r\nName           Used (GB)     Free (GB) Provider      Root                      \r\n----           ---------     --------- --------      ----                      \r\nHKCR                                   Registry      HKEY_CLASSES_ROOT         \r\nHKU                                    Registry      HKEY_USERS                \r\nHKCC                                   Registry      HKEY_CURRENT_CONFIG       \r\n\r\n\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

This fails:
```yaml
- name: "create key '1'"
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\TrapConfiguration\TEST
    value: 1
    state: present

This Works:
- name: "create key '1'"
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\TrapConfiguration\TEST
    value: "1"
    state: present
```

##### EXPECTED RESULTS

I believe the "ToLower" should only be used as a test if the data type supports that method.

##### ACTUAL RESULTS

Because the $name is an INT, and the testing logic is trying to change it to lowercase, the entire module errors out because that method isn't available for that data type.

```python
fatal: [test12]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Method invocation failed because [System.Int32] does not contain a method \r\nnamed 'ToLower'.\r\nAt line:153 char:5\r\n+ if ($name -eq \"\" -or ($name -ne $null -and $name.ToLower() -eq \"(default)\")) \r\n{\r\n+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidOperation: (:) [], ParentContainsErrorRec \r\n   ordException\r\n    + FullyQualifiedErrorId : MethodNotFound\r\n \r\n\r\n", "module_stdout": "\r\nName           Used (GB)     Free (GB) Provider      Root                      \r\n----           ---------     --------- --------      ----                      \r\nHKCR                                   Registry      HKEY_CLASSES_ROOT         \r\nHKU                                    Registry      HKEY_USERS                \r\nHKCC                                   Registry      HKEY_CURRENT_CONFIG       \r\n\r\n\r\n", "msg": "MODULE FAILURE", "rc": 1}
```
