### ISSUE TITLE
nxos_igmp_snooping is not idempotent for non-default values on D1 image on N7K.

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#30439]
nxos_igmp_snooping is not idempotent for non-default values on D1 image on N7K.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_igmp_snooping

##### ANSIBLE VERSION

```
ansible 2.4.0.0 (stable-2.4 06a066fe1b) last updated 2017/09/15 15:32:55 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### STEPS TO REPRODUCE

```yaml
    nxos_igmp_snooping: &non-default
      snooping: true
      group_timeout: never
      link_local_grp_supp: true
      report_supp: true
      v3_report_supp: true
      state: present
      provider: "{{ connection }}"
```

##### EXPECTED RESULTS

The above playbook to be idempotent across all platforms and releases

##### ACTUAL RESULTS

The playbook is not idempotent on D1 release of N7K. The reason is that some igmp snoop commands are not nvgened on running config. The real solution here is to move the command that checks the state of igmp snooping from 'sh run all | include igmp.snooping' to 'sh ip igmp snooping | json'.

**Comment by ansibot** [comment]
cc @GGabriele @jedelman8 @mikewiebe @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
@rahushen Thanks for the bug report. This doesn't sounds like a 2.4.0 release blocking issue, so something that can be fixed for `2.4.1`.

Would be good for the integration tests to be updated to defend this.

**Comment by trishnaguha** [comment]
@rahushen Idempotence works for me on devel for NXOS 9K.
Playbook:
```
- name: nxos igmp snooping 
  hosts: nxoshost
  connection: local

  tasks:
  - name: configure igmp snooping
    nxos_igmp_snooping: &non-default
      snooping: true
      group_timeout: never
      link_local_grp_supp: true
      report_supp: true
      v3_report_supp: true
      state: present

  - name: check idempotence
    nxos_igmp_snooping: *non-default
```

Result:
```
PLAY RECAP ********************************************************************************************************************************************************************************************************
nxoshost               : ok=3    changed=1    unreachable=0    failed=0   
```
