### ISSUE TITLE
Copy module isn't creating directories as in documentation being specified

### ISSUE THREAD

**Issue by StalkAlex** [ansible/ansible#30504]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Copy module

##### ANSIBLE VERSION
2.3.2.0
```
  config file = /******/****/app/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Ubuntu Bash on Windows

##### SUMMARY

Copy module is not following its documentation. It's not creating directory as it suppose to.
##### STEPS TO REPRODUCE
My src certs directory contains several folders named after domains with certificates inside them. I want to copy whole folder for specific domain.

```yml
- name: "Update ssl certs: copy certs"
  copy:
    src: "files/certs/{{ inventory_hostname }}"
    dest: "{{ app_dir }}/build/container-files/proxy/files/certs/"
```

##### EXPECTED RESULTS
I expect it will create, for example, production.com directory inside certs in destination path as it doesn't exists. That's why I'm copying this directory from src certs path.

##### ACTUAL RESULTS
But ansible throws error ***Destination directory does not exists***
