### ISSUE TITLE
mysql_db import failed with remote instance and SSL

### ISSUE THREAD

**Issue by k-ogawa-1988** [ansible/ansible#30500]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

mysql_db

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

```
Linux api 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
CentOS Linux release 7.3.1611 (Core) 
```

##### SUMMARY

Using `mysql_db state=import` with host, port (not using socket) and SSL fails with error `Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)`

##### STEPS TO REPRODUCE

```yaml
- name: create tables
  mysql_db:
    login_host: "{{ mysql_host }}"
    login_user: "{{ mysql_username_root }}"
    login_password: "{{ mysql_password_root }}"
    ssl_ca: "{{ mysql_certs_server_ca }}"
    ssl_cert: "{{ mysql_certs_client_cert }}"
    ssl_key: "{{ mysql_certs_client_key }}"
    name: "{{ mysql_database }}"
    state: import
    target: "{{ role_path }}/files/create-tables.sql"
```

##### EXPECTED RESULTS

Connect to MySQL instance with TCP connection (not using UNIX socket).

##### ACTUAL RESULTS

```
TASK [create-database : create tables] *******************************************************************************************************************************************************************
task path: /home/kenichi/environment/ansible/roles/create-database/tasks/main.yml:38
Using module file /usr/lib/python2.7/site-packages/ansible/modules/database/mysql/mysql_db.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: kenichi
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/kenichi/.ansible/tmp/ansible-tmp-1505722194.35-10724801791209 `" && echo ansible-tmp-1505722194.35-10724801791209="` echo /home/kenichi/.ansible/tmp/ansible-tmp-1505722194.35-10724801791209 `" ) && sleep 0'
<localhost> PUT /tmp/tmpyvwdnJ TO /home/kenichi/.ansible/tmp/ansible-tmp-1505722194.35-10724801791209/mysql_db.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/kenichi/.ansible/tmp/ansible-tmp-1505722194.35-10724801791209/ /home/kenichi/.ansible/tmp/ansible-tmp-1505722194.35-10724801791209/mysql_db.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/kenichi/.ansible/tmp/ansible-tmp-1505722194.35-10724801791209/mysql_db.py; rm -rf "/home/kenichi/.ansible/tmp/ansible-tmp-1505722194.35-10724801791209/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "collation": "", 
            "config_file": "/home/kenichi/.my.cnf", 
            "connect_timeout": 30, 
            "encoding": "", 
            "login_host": "SOME_REMOTE_MYSQL_INSTANCE", 
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "login_port": 3306, 
            "login_unix_socket": null, 
            "login_user": "root", 
            "name": "SOME_DB_NAME", 
            "quick": true, 
            "single_transaction": false, 
            "ssl_ca": "/opt/app/db-client-certs/server-ca.pem", 
            "ssl_cert": "/opt/app/db-client-certs/client-cert.pem", 
            "ssl_key": "/opt/app/db-client-certs/client-key.pem", 
            "state": "import", 
            "target": "/home/kenichi/environment/ansible/roles/create-database/files/create-tables.sql"
        }
    }, 
    "msg": "ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\n"
}

```
