### ISSUE TITLE
docker_service: defined `cpus` does not get casted into float

### ISSUE THREAD

**Issue by yajo** [ansible/ansible#30548]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_service

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### CONFIGURATION

Nothing

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Defining a service and trying to calculate the cpus parameter fails with: 

```
Configuration error - The Compose file '/tmp/ansibled30aTJ/docker-compose.yml' is invalid because:
Unsupported config option for services.dind: 'cpus'
```

Possibly related to https://github.com/ansible/ansible/issues/17992.

##### STEPS TO REPRODUCE

```yaml
- docker_service:
    pull: true
    state: present
    project_name: test
    definition:
      version: "2.2"
      services:
        dind:
          image: docker:dind
          cpus: "{{ ansible_processor_cores / 2 }}"
```

##### EXPECTED RESULTS

The `cpus` parameter should get casted to float or Ansible should have a way to force that, as I explained in https://github.com/ansible/ansible/issues/15249#issuecomment-330481415.

##### ACTUAL RESULTS

```
    "msg": "Configuration error - The Compose file '/tmp/ansibled30aTJ/docker-compose.yml' is invalid because:\nUnsupported config option for services.dind: 'cpus'"
```
