### ISSUE TITLE
AnsibleUndefinedVariable - ansible_all_ipv4_addresses is undefined

### ISSUE THREAD

**Issue by PREM1980** [ansible/ansible#30558]
- Bug Report

Name of the module:- template

#### ANSIBLE

ansible version :- ansible 2.3.1.0 

##### CONFIGURATION
```ini
[defaults]
allow_world_readable_tmpfiles=true


[ssh_connection]
ssh_args = -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=200s

[xenials:vars]
ansible_python_interpreter=/usr/bin/python2.7
```
##### OS / ENVIRONMENT
MAC

##### STEPS TO REPRODUCE

playbook.yaml 
```yaml
---
- hosts: all
  sudo: true
  gather_facts: no
  vars:
    document_root: /vagrant
  pre_tasks:    
    - name: install python 2
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

    - name: update apt cache
      apt: update_cache=yes

    - name: installing repo for Java 8 in Ubuntu
      apt_repository: repo='ppa:openjdk-r/ppa'


  roles:    
     - hadoop
     - role: geerlingguy.java
       when: "ansible_os_family == 'Debian'"
       java_packages:
         - openjdk-8-jdk
```
### roles tasks:- 
```yaml
---
- name: create a group called hadoop
  group:
    name: hadoop
    state: present

- name: add user
  user:
    name: hduser
    comment: "Hadoop User"
    shell: /bin/bash
    groups: hadoop
    append: yes
    generate_ssh_key: yes
    password: $6$FJCD6DfRWieE$XEb5U924ydsk8JW0bXhE1VWx5xs3hfQR/yla70Pi/GVdA37XJu36gpW2q3qm7DKJ9hGGuy.RYe6V3XvAa2cN7/
    # ssh_key_type: id_rsa
  register: newuser
- debug:
    var: newuser

- name: copy ssh key
  copy:
    src: /Users/pr/.ssh/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub

- name: add authorized_key
  authorized_key:
    user: hduser
    state: present
    key: "{{ newuser.ssh_public_key }}"

- name: change ssh config
  template:
    src: ./files/ssh-setup.j2
    dest: /etc/ssh/sshd_config
    owner: root
    mode: '0600'
    validate: /usr/sbin/sshd -t -f %s
    backup: yes

- service:
    name: ssh
    state: restarted
```
### Vagrant file:- 
```
Vagrant.require_version ">= 1.4.3"
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  numNodes = 1
  r = numNodes..1
  (r.first).downto(r.last).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.box = "ubuntu/Xenial64"
      node.vm.provider "virtualbox" do |v|
        v.name = "node#{i}"
        v.customize ["modifyvm", :id, "--memory", "1024"]
      end
      if i < 10
        node.vm.network :private_network, ip: "10.211.55.10#{i}"
      else
        node.vm.network :private_network, ip: "10.211.55.1#{i}"
      end
      node.vm.hostname = "node#{i}"
      node.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook.yml"
      end            
    end
  end
end
```

Error:- 
```
TASK [hadoop : change ssh config] **********************************************
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'ansible_all_ipv4_addresses' is undefined"}
```
##### EXPECTED RESULTS
The ubuntu should be created without any issues.

##### ACTUAL RESULTS
```
PLAY [all] *********************************************************************

TASK [install python 2] ********************************************************
changed: [node1]

TASK [update apt cache] ********************************************************
changed: [node1]

TASK [installing repo for Java 8 in Ubuntu] ************************************
changed: [node1]

TASK [hadoop : create a group called hadoop] ***********************************
changed: [node1]

TASK [hadoop : add user] *******************************************************
changed: [node1]

TASK [hadoop : debug] **********************************************************
ok: [node1] => {
    "newuser": {
        "changed": true, 
        "comment": "Hadoop User", 
        "createhome": true, 
        "group": 1002, 
        "groups": "hadoop", 
        "home": "/home/hduser", 
        "name": "hduser", 
        "password": "NOT_LOGGING_PASSWORD", 
        "shell": "/bin/bash", 
        "ssh_fingerprint": "2048 SHA256:zxh2VzqmsvKpYu5shRP+xJoBdq0B+iZYkecBKSiX8F8 ansible-generated on node1 (RSA)", 
        "ssh_key_file": "/home/hduser/.ssh/id_rsa", 
        "ssh_public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIb8iZqrjC11m3RjNlJWhF1Fu2fDDPZby0wlD6ZIBymFT/fvEsdvedXveNANlk3l9MDWIpUvjVsNv0XlnEcBdTSZXfqfSJv+yztEfeLbC0RUwjFDlMqmRoMrZ/D72AcnJZHk7bLDHvf4bViQatyFffPKl87YgP8TXeCtRrPiscnsA4s7qMa8KNgbz+nKc3maXgOCUiJ+3c69xxq/3M4Ca1RZbn62nraHCZQjY1dJ0jdAKUlD8eBZbL+u2M3WfIdJ9S8aGMef/sNaeGfHPs2IoO2WpTr+PDBfgemlwVxIORbnjHqhkH9YIfpZuxHLlt7X9t5oTRGgdfpENOoQ3nD37d ansible-generated on node1", 
        "state": "present", 
        "system": false, 
        "uid": 1001
    }
}

TASK [hadoop : copy ssh key] ***************************************************
changed: [node1]

TASK [hadoop : add authorized_key] *********************************************
changed: [node1]

TASK [hadoop : change ssh config] **********************************************
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'ansible_all_ipv4_addresses' is undefined"}
	to retry, use: --limit @/Users/pr/Documents/ansible-tutorial/hadoop-ansible/hadoop-cluster/playbook.retry

PLAY RECAP *********************************************************************
node1                      : ok=8    changed=7    unreachable=0    failed=1   
```
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
