### ISSUE TITLE
ios_config: entire section detected as changed?

### ISSUE THREAD

**Issue by yaplej** [ansible/ansible#30562]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### OS / ENVIRONMENT
CentOS Linux release 7.3.1611 (Core)

##### SUMMARY
Each run of detects the entire block has changed and re-configures it.

##### STEPS TO REPRODUCE
ansible-playbook -vvvvvv -i production detect-mac.yml --diff

```
---

- hosts: access_switches

  tasks:

  - name: EEM Applet detect-mac
    ios_config:
      lines:
        - 'event mat mac-address ^.*$ type add'
        - 'action 01.00 if $_mat_notification eq add'
        - 'action 01.01  cli command "enable"'
        - 'action 01.02  cli command "show int $_mat_intf_name switchport | inc Administrative Mode:"'
        - 'action 01.03  string match "*trunk*" "$_cli_result"'
        - 'action 01.04  syslog msg "Interface: $_mat_intf_name Result: $_cli_result"'
        - 'action 02.00  if $_string_result eq 0'
        - 'action 02.01   cli command "show ver | i ^Copyright.*by"'
        - 'action 02.02   set i "0"'
        - 'action 03.00   foreach line "$_cli_result" "\n"'
        - 'action 04.00    if $i eq 0'
        - 'action 04.01     regexp "^Copyright.*by\s*(.*)$" $line match manufacturer'
        - 'action 04.02     string trim $manufacturer'
        - 'action 04.03     set manufacturer "$_string_result"'
        - 'action 04.04    end'
        - 'action 04.05    increment i 1'
        - 'action 04.06   end'
        - 'action 05.00   foreach line "$manufacturer" " "'
        - 'action 05.01    append newmanufacturer $line'
        - 'action 05.02    append newmanufacturer "%20"'
        - 'action 05.03   end'
        - 'action 05.04   string trimright $newmanufacturer "%20"'
        - 'action 05.05   set manufacturer "$_string_result"'
        - 'action 05.06   cli command "show ver | i ^Model number"'
        - 'action 05.07   set i "0"'
        - 'action 06.00   foreach line "$_cli_result" "\n"'
        - 'action 07.00    if $i eq 0'
        - 'action 07.01     regexp "^Model number\s*:\s*(.*)" $line match model_num'
        - 'action 07.02     string trim $model_num'
        - 'action 07.03     set model_num "$_string_result"'
        - 'action 07.04    end'
        - 'action 07.05    increment i 1'
        - 'action 07.06   end'
        - 'action 07.07   cli command "show ver | i ^System serial number"'
        - 'action 07.08   set i "0"'
        - 'action 08.00   foreach line "$_cli_result" "\n"'
        - 'action 09.00    if $i eq 0'
        - 'action 09.01     regexp "^System serial number\s*:\s*(.*)" $line match serial_num'
        - 'action 09.02     string trim $serial_num'
        - 'action 09.03     set serial_num "$_string_result"'
        - 'action 09.04    end'
        - 'action 09.05    increment i 1'
        - 'action 09.06   end'
        # Cisco IOS still needs special character ? escaped.
        # Typically this is CTRL+V or also SYN character.
        # HEX ASCII value \x16 is used for SYN.
        # HEX ASCII value \x3f is used for ?.
        - 'action 09.07   cli command "more $identityserver/\x16\x3fman=$manufacturer&mod=$model_num"'
        - 'action 09.08   cli command "more $identityserver/\x16\x3fmod=$model_num&sn=$serial_num"'
        - 'action 09.09   cli command "more $identityserver/\x16\x3fmac=$_mat_mac_address&int=$_mat_intf_name&sn=$serial_num&mod=$model_num"'
        - 'action 09.10   string match "*(I/O error)*" "$_cli_result"'
        - 'action 10.00   if $_string_result eq 0'
        - 'action 10.01    regexp "(.*):" $_cli_result match macro'
        - 'action 10.02    regexp ":(.*)" $_cli_result match description'
        - 'action 11.00   else'
        - 'action 11.01    syslog msg "Call to identity server failed! Result: $_cli_result"'
        - 'action 11.02    cli command "exit"'
        - 'action 11.03    exit 1'
        - 'action 11.04   end'
        - 'action 11.05   cli command "show run | i macro name $macro"'
        - 'action 11.06   string match "*$macro*" "$_cli_result"'
        - 'action 12.00   if $_string_result eq 1'
        - 'action 12.01    cli command "config t"'
        - 'action 12.02    cli command "interface $_mat_intf_name"'
        - 'action 12.03    cli command "macro apply $macro DESCRIPTION $description"'
        - 'action 12.04    cli command "end"'
        - 'action 12.05    syslog msg "Interface: $_mat_intf_name, MAC: $_mat_mac_address, Macro: $macro"'
        - 'action 13.00   else'
        - 'action 13.01    cli command "show run | i macro name $defaultmacro"'
        - 'action 13.02    string match "*$defaultmacro*" "$_cli_result"'
        - 'action 14.00    if $_string_result eq 1'
        - 'action 14.01     cli command "config t"'
        - 'action 14.02     cli command "interface $_mat_intf_name"'
        - 'action 14.03     cli command "macro apply $defaultmacro DESCRIPTION $description"'
        - 'action 14.04     cli command "end"'
        - 'action 14.05    end'
        - 'action 14.06   end'
        - 'action 14.07  end'
        - 'action 14.08  cli command "exit"'
        - 'action 14.09 end'
      parents: event manager applet detect-mac
      before: no event manager applet detect-mac
      after: exit
      match: line
      replace: block
```

https://pastebin.com/7DbtPSGu
https://pastebin.com/r3B0zEY8

##### EXPECTED RESULTS
Skips if the section already exists.

##### ACTUAL RESULTS
Section is deleted and re-created every time.

```
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: detect-mac.yml ********************************************************************************************************************************************************************************************************************
1 plays in detect-mac.yml

PLAY [access_switches] **********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<10.X.XXX.XX> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.X.XXX.XX> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.X.XXX.XX> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1505838428.25-143038149279703 `" && echo ansible-tmp-1505838428.25-143038149279703="` echo /root/.ansible/tmp/ansible-tmp-1505838428.25-143038149279703 `" ) && sleep 0'
<10.X.XXX.XX> PUT /tmp/tmp9uan0I TO /root/.ansible/tmp/ansible-tmp-1505838428.25-143038149279703/setup.py
<10.X.XXX.XX> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1505838428.25-143038149279703/ /root/.ansible/tmp/ansible-tmp-1505838428.25-143038149279703/setup.py && sleep 0'
<10.X.XXX.XX> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1505838428.25-143038149279703/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1505838428.25-143038149279703/" > /dev/null 2>&1 && sleep 0'
ok: [10.X.XXX.XX]
META: ran handlers

TASK [EEM Applet detect-mac] ****************************************************************************************************************************************************************************************************************
task path: /etc/ansible/detect-mac.yml:7
<10.X.XXX.XX> using connection plugin network_cli
<10.X.XXX.XX> socket_path: /root/.ansible/pc/fe2b444b0a
open_shell() returned 0 ok
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/ios/ios_config.py
<10.X.XXX.XX> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.X.XXX.XX> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.X.XXX.XX> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1505838439.26-115926591301229 `" && echo ansible-tmp-1505838439.26-115926591301229="` echo /root/.ansible/tmp/ansible-tmp-1505838439.26-115926591301229 `" ) && sleep 0'
<10.X.XXX.XX> PUT /tmp/tmpC_bnvN TO /root/.ansible/tmp/ansible-tmp-1505838439.26-115926591301229/ios_config.py
<10.X.XXX.XX> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1505838439.26-115926591301229/ /root/.ansible/tmp/ansible-tmp-1505838439.26-115926591301229/ios_config.py && sleep 0'
<10.X.XXX.XX> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1505838439.26-115926591301229/ios_config.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1505838439.26-115926591301229/" > /dev/null 2>&1 && sleep 0'
changed: [10.X.XXX.XX] => {
    "banners": {},
    "changed": true,
    "commands": [
        "no event manager applet detect-mac",
        "event manager applet detect-mac",
        "event mat mac-address ^.*$ type add",
        "action 01.00 if $_mat_notification eq add",
        "action 01.01  cli command \"enable\"",
        "action 01.02  cli command \"show int $_mat_intf_name switchport | inc Administrative Mode:\"",
        "action 01.03  string match \"*trunk*\" \"$_cli_result\"",
        "action 01.04  syslog msg \"Interface: $_mat_intf_name Result: $_cli_result\"",
        "action 02.00  if $_string_result eq 0",
        "action 02.01   cli command \"show ver | i ^Copyright.*by\"",
        "action 02.02   set i \"0\"",
        "action 03.00   foreach line \"$_cli_result\" \"\\n\"",
        "action 04.00    if $i eq 0",
        "action 04.01     regexp \"^Copyright.*by\\s*(.*)$\" $line match manufacturer",
        "action 04.02     string trim $manufacturer",
        "action 04.03     set manufacturer \"$_string_result\"",
        "action 04.04    end",
        "action 04.05    increment i 1",
        "action 04.06   end",
        "action 05.00   foreach line \"$manufacturer\" \" \"",
        "action 05.01    append newmanufacturer $line",
        "action 05.02    append newmanufacturer \"%20\"",
        "action 05.03   end",
        "action 05.04   string trimright $newmanufacturer \"%20\"",
        "action 05.05   set manufacturer \"$_string_result\"",
        "action 05.06   cli command \"show ver | i ^Model number\"",
        "action 05.07   set i \"0\"",
        "action 06.00   foreach line \"$_cli_result\" \"\\n\"",
        "action 07.00    if $i eq 0",
        "action 07.01     regexp \"^Model number\\s*:\\s*(.*)\" $line match model_num",
        "action 07.02     string trim $model_num",
        "action 07.03     set model_num \"$_string_result\"",
        "action 07.04    end",
        "action 07.05    increment i 1",
        "action 07.06   end",
        "action 07.07   cli command \"show ver | i ^System serial number\"",
        "action 07.08   set i \"0\"",
        "action 08.00   foreach line \"$_cli_result\" \"\\n\"",
        "action 09.00    if $i eq 0",
        "action 09.01     regexp \"^System serial number\\s*:\\s*(.*)\" $line match serial_num",
        "action 09.02     string trim $serial_num",
        "action 09.03     set serial_num \"$_string_result\"",
        "action 09.04    end",
        "action 09.05    increment i 1",
        "action 09.06   end",
        "action 09.07   cli command \"more $identityserver/\\x16\\x3fman=$manufacturer&mod=$model_num\"",
        "action 09.08   cli command \"more $identityserver/\\x16\\x3fmod=$model_num&sn=$serial_num\"",
        "action 09.09   cli command \"more $identityserver/\\x16\\x3fmac=$_mat_mac_address&int=$_mat_intf_name&sn=$serial_num&mod=$model_num\"",
        "action 09.10   string match \"*(I/O error)*\" \"$_cli_result\"",
        "action 10.00   if $_string_result eq 0",
        "action 10.01    regexp \"(.*):\" $_cli_result match macro",
        "action 10.02    regexp \":(.*)\" $_cli_result match description",
        "action 11.00   else",
        "action 11.01    syslog msg \"Call to identity server failed! Result: $_cli_result\"",
        "action 11.02    cli command \"exit\"",
        "action 11.03    exit 1",
        "action 11.04   end",
        "action 11.05   cli command \"show run | i macro name $macro\"",
        "action 11.06   string match \"*$macro*\" \"$_cli_result\"",
        "action 12.00   if $_string_result eq 1",
        "action 12.01    cli command \"config t\"",
        "action 12.02    cli command \"interface $_mat_intf_name\"",
        "action 12.03    cli command \"macro apply $macro DESCRIPTION $description\"",
        "action 12.04    cli command \"end\"",
        "action 12.05    syslog msg \"Interface: $_mat_intf_name, MAC: $_mat_mac_address, Macro: $macro\"",
        "action 13.00   else",
        "action 13.01    cli command \"show run | i macro name $defaultmacro\"",
        "action 13.02    string match \"*$defaultmacro*\" \"$_cli_result\"",
        "action 14.00    if $_string_result eq 1",
        "action 14.01     cli command \"config t\"",
        "action 14.02     cli command \"interface $_mat_intf_name\"",
        "action 14.03     cli command \"macro apply $defaultmacro DESCRIPTION $description\"",
        "action 14.04     cli command \"end\"",
        "action 14.05    end",
        "action 14.06   end",
        "action 14.07  end",
        "action 14.08  cli command \"exit\"",
        "action 14.09 end",
        "exit"
    ],
    "invocation": {
        "module_args": {
            "after": [
                "exit"
            ],
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": [
                "no event manager applet detect-mac"
            ],
            "config": null,
            "defaults": false,
            "force": false,
            "host": null,
            "lines": [
                "event mat mac-address ^.*$ type add",
                "action 01.00 if $_mat_notification eq add",
                "action 01.01  cli command \"enable\"",
                "action 01.02  cli command \"show int $_mat_intf_name switchport | inc Administrative Mode:\"",
                "action 01.03  string match \"*trunk*\" \"$_cli_result\"",
                "action 01.04  syslog msg \"Interface: $_mat_intf_name Result: $_cli_result\"",
                "action 02.00  if $_string_result eq 0",
                "action 02.01   cli command \"show ver | i ^Copyright.*by\"",
                "action 02.02   set i \"0\"",
                "action 03.00   foreach line \"$_cli_result\" \"\\n\"",
                "action 04.00    if $i eq 0",
                "action 04.01     regexp \"^Copyright.*by\\s*(.*)$\" $line match manufacturer",
                "action 04.02     string trim $manufacturer",
                "action 04.03     set manufacturer \"$_string_result\"",
                "action 04.04    end",
                "action 04.05    increment i 1",
                "action 04.06   end",
                "action 05.00   foreach line \"$manufacturer\" \" \"",
                "action 05.01    append newmanufacturer $line",
                "action 05.02    append newmanufacturer \"%20\"",
                "action 05.03   end",
                "action 05.04   string trimright $newmanufacturer \"%20\"",
                "action 05.05   set manufacturer \"$_string_result\"",
                "action 05.06   cli command \"show ver | i ^Model number\"",
                "action 05.07   set i \"0\"",
                "action 06.00   foreach line \"$_cli_result\" \"\\n\"",
                "action 07.00    if $i eq 0",
                "action 07.01     regexp \"^Model number\\s*:\\s*(.*)\" $line match model_num",
                "action 07.02     string trim $model_num",
                "action 07.03     set model_num \"$_string_result\"",
                "action 07.04    end",
                "action 07.05    increment i 1",
                "action 07.06   end",
                "action 07.07   cli command \"show ver | i ^System serial number\"",
                "action 07.08   set i \"0\"",
                "action 08.00   foreach line \"$_cli_result\" \"\\n\"",
                "action 09.00    if $i eq 0",
                "action 09.01     regexp \"^System serial number\\s*:\\s*(.*)\" $line match serial_num",
                "action 09.02     string trim $serial_num",
                "action 09.03     set serial_num \"$_string_result\"",
                "action 09.04    end",
                "action 09.05    increment i 1",
                "action 09.06   end",
                "action 09.07   cli command \"more $identityserver/\\x16\\x3fman=$manufacturer&mod=$model_num\"",
                "action 09.08   cli command \"more $identityserver/\\x16\\x3fmod=$model_num&sn=$serial_num\"",
                "action 09.09   cli command \"more $identityserver/\\x16\\x3fmac=$_mat_mac_address&int=$_mat_intf_name&sn=$serial_num&mod=$model_num\"",
                "action 09.10   string match \"*(I/O error)*\" \"$_cli_result\"",
                "action 10.00   if $_string_result eq 0",
                "action 10.01    regexp \"(.*):\" $_cli_result match macro",
                "action 10.02    regexp \":(.*)\" $_cli_result match description",
                "action 11.00   else",
                "action 11.01    syslog msg \"Call to identity server failed! Result: $_cli_result\"",
                "action 11.02    cli command \"exit\"",
                "action 11.03    exit 1",
                "action 11.04   end",
                "action 11.05   cli command \"show run | i macro name $macro\"",
                "action 11.06   string match \"*$macro*\" \"$_cli_result\"",
                "action 12.00   if $_string_result eq 1",
                "action 12.01    cli command \"config t\"",
                "action 12.02    cli command \"interface $_mat_intf_name\"",
                "action 12.03    cli command \"macro apply $macro DESCRIPTION $description\"",
                "action 12.04    cli command \"end\"",
                "action 12.05    syslog msg \"Interface: $_mat_intf_name, MAC: $_mat_mac_address, Macro: $macro\"",
                "action 13.00   else",
                "action 13.01    cli command \"show run | i macro name $defaultmacro\"",
                "action 13.02    string match \"*$defaultmacro*\" \"$_cli_result\"",
                "action 14.00    if $_string_result eq 1",
                "action 14.01     cli command \"config t\"",
                "action 14.02     cli command \"interface $_mat_intf_name\"",
                "action 14.03     cli command \"macro apply $defaultmacro DESCRIPTION $description\"",
                "action 14.04     cli command \"end\"",
                "action 14.05    end",
                "action 14.06   end",
                "action 14.07  end",
                "action 14.08  cli command \"exit\"",
                "action 14.09 end"
            ],
            "match": "line",
            "multiline_delimiter": "@",
            "parents": [
                "event manager applet detect-mac"
            ],
            "password": null,
            "port": null,
            "provider": null,
            "replace": "block",
            "save": false,
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "updates": [
        "no event manager applet detect-mac",
        "event manager applet detect-mac",
        "event mat mac-address ^.*$ type add",
        "action 01.00 if $_mat_notification eq add",
        "action 01.01  cli command \"enable\"",
        "action 01.02  cli command \"show int $_mat_intf_name switchport | inc Administrative Mode:\"",
        "action 01.03  string match \"*trunk*\" \"$_cli_result\"",
        "action 01.04  syslog msg \"Interface: $_mat_intf_name Result: $_cli_result\"",
        "action 02.00  if $_string_result eq 0",
        "action 02.01   cli command \"show ver | i ^Copyright.*by\"",
        "action 02.02   set i \"0\"",
        "action 03.00   foreach line \"$_cli_result\" \"\\n\"",
        "action 04.00    if $i eq 0",
        "action 04.01     regexp \"^Copyright.*by\\s*(.*)$\" $line match manufacturer",
        "action 04.02     string trim $manufacturer",
        "action 04.03     set manufacturer \"$_string_result\"",
        "action 04.04    end",
        "action 04.05    increment i 1",
        "action 04.06   end",
        "action 05.00   foreach line \"$manufacturer\" \" \"",
        "action 05.01    append newmanufacturer $line",
        "action 05.02    append newmanufacturer \"%20\"",
        "action 05.03   end",
        "action 05.04   string trimright $newmanufacturer \"%20\"",
        "action 05.05   set manufacturer \"$_string_result\"",
        "action 05.06   cli command \"show ver | i ^Model number\"",
        "action 05.07   set i \"0\"",
        "action 06.00   foreach line \"$_cli_result\" \"\\n\"",
        "action 07.00    if $i eq 0",
        "action 07.01     regexp \"^Model number\\s*:\\s*(.*)\" $line match model_num",
        "action 07.02     string trim $model_num",
        "action 07.03     set model_num \"$_string_result\"",
        "action 07.04    end",
        "action 07.05    increment i 1",
        "action 07.06   end",
        "action 07.07   cli command \"show ver | i ^System serial number\"",
        "action 07.08   set i \"0\"",
        "action 08.00   foreach line \"$_cli_result\" \"\\n\"",
        "action 09.00    if $i eq 0",
        "action 09.01     regexp \"^System serial number\\s*:\\s*(.*)\" $line match serial_num",
        "action 09.02     string trim $serial_num",
        "action 09.03     set serial_num \"$_string_result\"",
        "action 09.04    end",
        "action 09.05    increment i 1",
        "action 09.06   end",
        "action 09.07   cli command \"more $identityserver/\\x16\\x3fman=$manufacturer&mod=$model_num\"",
        "action 09.08   cli command \"more $identityserver/\\x16\\x3fmod=$model_num&sn=$serial_num\"",
        "action 09.09   cli command \"more $identityserver/\\x16\\x3fmac=$_mat_mac_address&int=$_mat_intf_name&sn=$serial_num&mod=$model_num\"",
        "action 09.10   string match \"*(I/O error)*\" \"$_cli_result\"",
        "action 10.00   if $_string_result eq 0",
        "action 10.01    regexp \"(.*):\" $_cli_result match macro",
        "action 10.02    regexp \":(.*)\" $_cli_result match description",
        "action 11.00   else",
        "action 11.01    syslog msg \"Call to identity server failed! Result: $_cli_result\"",
        "action 11.02    cli command \"exit\"",
        "action 11.03    exit 1",
        "action 11.04   end",
        "action 11.05   cli command \"show run | i macro name $macro\"",
        "action 11.06   string match \"*$macro*\" \"$_cli_result\"",
        "action 12.00   if $_string_result eq 1",
        "action 12.01    cli command \"config t\"",
        "action 12.02    cli command \"interface $_mat_intf_name\"",
        "action 12.03    cli command \"macro apply $macro DESCRIPTION $description\"",
        "action 12.04    cli command \"end\"",
        "action 12.05    syslog msg \"Interface: $_mat_intf_name, MAC: $_mat_mac_address, Macro: $macro\"",
        "action 13.00   else",
        "action 13.01    cli command \"show run | i macro name $defaultmacro\"",
        "action 13.02    string match \"*$defaultmacro*\" \"$_cli_result\"",
        "action 14.00    if $_string_result eq 1",
        "action 14.01     cli command \"config t\"",
        "action 14.02     cli command \"interface $_mat_intf_name\"",
        "action 14.03     cli command \"macro apply $defaultmacro DESCRIPTION $description\"",
        "action 14.04     cli command \"end\"",
        "action 14.05    end",
        "action 14.06   end",
        "action 14.07  end",
        "action 14.08  cli command \"exit\"",
        "action 14.09 end",
        "exit"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
10.X.XXX.XX                : ok=2    changed=1    unreachable=0    failed=0

```

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn @gundalow @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yaplej** [comment]
I updated to 2.4 and have the same problem.
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

**Comment by ansibot** [comment]
cc @kedarX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yaplej** [comment]
I have been working to identify why my config executes on every run.  The only difference between my running configuration and the playbook is that I had to use some ASCII values for ^V and ? representation.  I have event tried to exclude those lines but it still re-configures this on each run.

IOS Config
```
event manager applet detect-mac
 event mat mac-address ^.*$ type add
 action 01.00 if $_mat_notification eq "add"
 action 01.01  cli command "enable"
 action 01.02  cli command "show int $_mat_intf_name switchport | inc Administrative Mode:"
 action 01.03  string match "*trunk*" "$_cli_result"
 action 01.04  syslog msg "Interface: $_mat_intf_name Result: $_cli_result"
 action 02.00  if $_string_result eq "0"
 action 02.01   cli command "show ver | i ^Copyright.*by"
 action 02.02   set i "0"
 action 03.00   foreach line "$_cli_result" "\n"
 action 04.00    if $i eq "0"
 action 04.01     regexp "^Copyright.*by\s*(.*)$" "$line" match manufacturer
 action 04.02     string trim "$manufacturer"
 action 04.03     set manufacturer "$_string_result"
 action 04.04    end
 action 04.05    increment i 1
 action 04.06   end
 action 05.00   foreach line "$manufacturer" " "
 action 05.01    append newmanufacturer "$line"
 action 05.02    append newmanufacturer "%20"
 action 05.03   end
 action 05.04   string trimright "$newmanufacturer" "%20"
 action 05.05   set manufacturer "$_string_result"
 action 05.06   cli command "show ver | i ^Model [Nn]umber"
 action 05.07   set i "0"
 action 06.00   foreach line "$_cli_result" "\n"
 action 07.00    if $i eq "0"
 action 07.01     regexp "^Model [Nn]umber\s*:\s*(.*)" "$line" match model_num
 action 07.02     string trim "$model_num"
 action 07.03     set model_num "$_string_result"
 action 07.04    end
 action 07.05    increment i 1
 action 07.06   end
 action 07.07   cli command "show ver | i ^System [Ss]erial [Nn]umber"
 action 07.08   set i "0"
 action 08.00   foreach line "$_cli_result" "\n"
 action 09.00    if $i eq "0"
 action 09.01     regexp "^System [Ss]erial [Nn]umber\s*:\s*(.*)" "$line" match serial_num
 action 09.02     string trim "$serial_num"
 action 09.03     set serial_num "$_string_result"
 action 09.04    end
 action 09.05    increment i 1
 action 09.06   end
 action 09.07   cli command "more $identityserver/^V?man=$manufacturer&mod=$model_num"
 action 09.08   cli command "more $identityserver/^V?mod=$model_num&sn=$serial_num"
 action 09.09   cli command "more $identityserver/^V?mac=$_mat_mac_address&int=$_mat_intf_name&sn=$serial_num&mod=$model_num"
 action 09.10   string match "*(I/O error)*" "$_cli_result"
 action 10.00   if $_string_result eq "0"
 action 10.01    syslog msg "$_cli_result"
 action 10.02    foreach line "$_cli_result" " "
 action 10.03     string match "*http*" "$line"
 action 11.00     if $_string_result eq "0"
 action 11.01      regexp "(.*:.*)" "$line" match response
 action 12.00      if $_regexp_result eq "1"
 action 12.01       syslog msg "Regexp Result: $_regexp_result Regexp Match: $match Regexp Response: $response"
 action 12.02       regexp "(.*):" "$response" match macro
 action 12.03       regexp ":(.*)" "$response" match description
 action 12.04      end
 action 12.05     end
 action 12.06    end
 action 13.00   else
 action 13.01    syslog msg "Call to identity server failed! Result: $_cli_result"
 action 13.02    cli command "exit"
 action 13.03    exit 1
 action 13.04   end
 action 13.05   cli command "show run | i macro name $macro"
 action 13.06   string match "*$macro*" "$_cli_result"
 action 14.00   if $_string_result eq "1"
 action 14.01    cli command "config t"
 action 14.02    cli command "interface $_mat_intf_name"
 action 14.03    cli command "macro apply $macro DESCRIPTION $description"
 action 14.04    syslog msg "Apply $macro Macro Result: $_cli_result"
 action 14.05    cli command "end"
 action 14.06    syslog msg "Interface: $_mat_intf_name, MAC: $_mat_mac_address, Macro: $macro"
 action 15.00   else
 action 15.01    cli command "show run | i macro name $defaultmacro"
 action 15.02    string match "*$defaultmacro*" "$_cli_result"
 action 16.00    if $_string_result eq "1"
 action 16.01     cli command "config t"
 action 16.02     cli command "interface $_mat_intf_name"
 action 16.03     cli command "macro apply $defaultmacro DESCRIPTION $description"
 action 16.04     cli command "end"
 action 16.05    end
 action 16.06   end
 action 16.07  end
 action 16.08  cli command "exit"
 action 16.09 end
```

Playbook
```
---

- hosts: access_switches

  tasks:

  - name: EEM Applet detect-mac
    ios_config:
      lines:
        - 'event mat mac-address ^.*$ type add'
        - 'action 01.00 if $_mat_notification eq "add"'
        - 'action 01.01  cli command "enable"'
        - 'action 01.02  cli command "show int $_mat_intf_name switchport | inc Administrative Mode:"'
        - 'action 01.03  string match "*trunk*" "$_cli_result"'
        - 'action 01.04  syslog msg "Interface: $_mat_intf_name Result: $_cli_result"'
        - 'action 02.00  if $_string_result eq "0"'
        - 'action 02.01   cli command "show ver | i ^Copyright.*by"'
        - 'action 02.02   set i "0"'
        - 'action 03.00   foreach line "$_cli_result" "\n"'
        - 'action 04.00    if $i eq "0"'
        - 'action 04.01     regexp "^Copyright.*by\s*(.*)$" "$line" match manufacturer'
        - 'action 04.02     string trim "$manufacturer"'
        - 'action 04.03     set manufacturer "$_string_result"'
        - 'action 04.04    end'
        - 'action 04.05    increment i 1'
        - 'action 04.06   end'
        - 'action 05.00   foreach line "$manufacturer" " "'
        - 'action 05.01    append newmanufacturer "$line"'
        - 'action 05.02    append newmanufacturer "%20"'
        - 'action 05.03   end'
        - 'action 05.04   string trimright "$newmanufacturer" "%20"'
        - 'action 05.05   set manufacturer "$_string_result"'
        - 'action 05.06   cli command "show ver | i ^Model [Nn]umber"'
        - 'action 05.07   set i "0"'
        - 'action 06.00   foreach line "$_cli_result" "\n"'
        - 'action 07.00    if $i eq "0"'
        - 'action 07.01     regexp "^Model [Nn]umber\s*:\s*(.*)" "$line" match model_num'
        - 'action 07.02     string trim "$model_num"'
        - 'action 07.03     set model_num "$_string_result"'
        - 'action 07.04    end'
        - 'action 07.05    increment i 1'
        - 'action 07.06   end'
        - 'action 07.07   cli command "show ver | i ^System [Ss]erial [Nn]umber"'
        - 'action 07.08   set i "0"'
        - 'action 08.00   foreach line "$_cli_result" "\n"'
        - 'action 09.00    if $i eq "0"'
        - 'action 09.01     regexp "^System [Ss]erial [Nn]umber\s*:\s*(.*)" "$line" match serial_num'
        - 'action 09.02     string trim "$serial_num"'
        - 'action 09.03     set serial_num "$_string_result"'
        - 'action 09.04    end'
        - 'action 09.05    increment i 1'
        - 'action 09.06   end'
        # Cisco IOS still needs special character ? escaped.
        # Typically this is CTRL+V or also SYN character.
        # HEX ASCII value \x16 is used for SYN.
        # HEX ASCII value \x3f is used for ?.
        - 'action 09.07   cli command "more $identityserver/\x16\x3fman=$manufacturer&mod=$model_num"'
        - 'action 09.08   cli command "more $identityserver/\x16\x3fmod=$model_num&sn=$serial_num"'
        - 'action 09.09   cli command "more $identityserver/\x16\x3fmac=$_mat_mac_address&int=$_mat_intf_name&sn=$serial_num&mod=$model_num"'
        - 'action 09.10   string match "*(I/O error)*" "$_cli_result"'
        - 'action 10.00   if $_string_result eq "0"'
        - 'action 10.01    syslog msg "$_cli_result"'
        - 'action 10.02    foreach line "$_cli_result" " "'
        - 'action 10.03     string match "*http*" "$line"'
        - 'action 11.00     if $_string_result eq "0"'
        - 'action 11.01      regexp "(.*:.*)" "$line" match response'
        - 'action 12.00      if $_regexp_result eq "1"'
        - 'action 12.01       syslog msg "Regexp Result: $_regexp_result Regexp Match: $match Regexp Response: $response"'
        - 'action 12.02       regexp "(.*):" "$response" match macro'
        - 'action 12.03       regexp ":(.*)" "$response" match description'
        - 'action 12.04      end'
        - 'action 12.05     end'
        - 'action 12.06    end'
        - 'action 13.00   else'
        - 'action 13.01    syslog msg "Call to identity server failed! Result: $_cli_result"'
        - 'action 13.02    cli command "exit"'
        - 'action 13.03    exit 1'
        - 'action 13.04   end'
        - 'action 13.05   cli command "show run | i macro name $macro"'
       - 'action 13.06   string match "*$macro*" "$_cli_result"'
        - 'action 14.00   if $_string_result eq "1"'
        - 'action 14.01    cli command "config t"'
        - 'action 14.02    cli command "interface $_mat_intf_name"'
        - 'action 14.03    cli command "macro apply $macro DESCRIPTION $description"'
        - 'action 14.04    syslog msg "Apply $macro Macro Result: $_cli_result"'
        - 'action 14.05    cli command "end"'
        - 'action 14.06    syslog msg "Interface: $_mat_intf_name, MAC: $_mat_mac_address, Macro: $macro"'
        - 'action 15.00   else'
        - 'action 15.01    cli command "show run | i macro name $defaultmacro"'
        - 'action 15.02    string match "*$defaultmacro*" "$_cli_result"'
        - 'action 16.00    if $_string_result eq "1"'
        - 'action 16.01     cli command "config t"'
        - 'action 16.02     cli command "interface $_mat_intf_name"'
        - 'action 16.03     cli command "macro apply $defaultmacro DESCRIPTION $description"'
        - 'action 16.04     cli command "end"'
        - 'action 16.05    end'
        - 'action 16.06   end'
        - 'action 16.07  end'
        - 'action 16.08  cli command "exit"'
        - 'action 16.09 end'
      parents: event manager applet detect-mac
      before: no event manager applet detect-mac
      after: exit
      match: line
      replace: block
      diff_ignore_lines:
        - 'action 09.07.*'
        - 'action 09.08.*'
        - 'action 09.09.*'
```

Is there any way to debug so it shows me the lines that are not matching?
