### ISSUE TITLE
dconf module list manipulation support

### ISSUE THREAD

**Issue by stevenkaras** [ansible/ansible#30561]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
dconf

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /home/steven/.ansible.cfg
  configured module search path = [u'/home/steven/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
Irrelevant

##### OS / ENVIRONMENT
Running from Ubuntu 14.04, managing Ubuntu 14.04, 16.04

##### SUMMARY
The new dconf module is great, but many dconf values are lists.
Specifically, in this case, I'd like to use ansible to disable a plugin in compiz.
First class support of these would allow me to do this without a kludge of regex and string manipulation.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  tasks:
    - name: disable animation compiz plugin
      block:
        - dconf:
            key: "/org/compiz/current-profile"
            state: read
          register: current_compiz_profile
        - dconf:
            key: "/org/compiz/profiles/{{ current_compiz_profile.value[1:-1] }}/plugins/core/active-plugins"
            list-value: animation
            state: absent
```

##### EXPECTED RESULTS
The above should remove the 'animation' value from the active-plugins list.

##### ACTUAL RESULTS
My current solution is an ugly jinja kludge which requires YAML blockquoting (>):

```yaml
---
- hosts: localhost
  tasks:
    - name: disable animation compiz plugin
      block:
        - dconf:
            key: "/org/compiz/current-profile"
            state: read
          register: current_compiz_profile
        - dconf:
            key: "/org/compiz/profiles/{{ current_compiz_profile.value[1:-1] }}/plugins/core/active-plugins"
            state: read
          register: current_active_compiz_plugins
        - dconf:
            key: "/org/compiz/profiles/{{ current_compiz_profile.value[1:-1] }}/plugins/core/active-plugins"
            value: >
              [ {{ current_active_compiz_plugins.value[1:-1].split(',') | map('trim') | difference(["'animation'"]) | join(', ') }} ]
            state: present
```
