### ISSUE TITLE
S3 Module With Addressing Style

### ISSUE THREAD

**Issue by srosenf** [ansible/ansible#30570]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

s3

##### ANSIBLE VERSION

```
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

 RHEL 7.3 (Maipo)

##### SUMMARY

When using the s3 module and a non-aws server I am unable to specify the "address_style=path" parameter that some of the non-aws s3 servers use. I believe this is causing a connection refused error.

My assumption since this is using boto is that it's attempting to use "http://bucket.localhost:8000" when instead the s3 server only understands "http://localhost:8000/bucket". Is it possible to use this type of addressing with the s3 module? 

##### STEPS TO REPRODUCE

```yaml
 - name: Upload to S3
  s3:
    s3_url: "http://localhost:8000" 
    region: us-east-1
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"
    bucket: "{{ bucket }}"
    src: "{{ file.stdout }}"
    object: "{{ s3site }}/{{ ansible_date_time.date }}/{{ file.stdout.split('/')[3] }}"
    mode: put
    validate_certs: no
```

##### EXPECTED RESULTS

Object be should uploaded to the bucket

##### ACTUAL RESULTS

It appears to run as expected but times out with a connection failure

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_696VGZ/ansible_module_s3.py\", line 663, in <module>\r\n    main()\r\n  File \"/tmp/ansible_696VGZ/ansible_module_s3.py\", line 556, in main\r\n    create_bucket(module, s3, bucket, location)\r\n  File \"/tmp/ansible_696VGZ/ansible_module_s3.py\", line 243, in create_bucket\r\n    bucket = s3.create_bucket(bucket, location=location)\r\n  File \"/usr/lib/python2.7/site-packages/boto/s3/connection.py\", line 616, in create_bucket\r\n    data=data)\r\n  File \"/usr/lib/python2.7/site-packages/boto/s3/connection.py\", line 668, in make_request\r\n    retry_handler=retry_handler\r\n  File \"/usr/lib/python2.7/site-packages/boto/connection.py\", line 1071, in make_request\r\n    retry_handler=retry_handler)\r\n  File \"/usr/lib/python2.7/site-packages/boto/connection.py\", line 1030, in _mexe\r\n    raise ex\r\nsocket.error: [Errno 111] Connection refused\r\n", "msg": "MODULE FAILURE"}
```
