### ISSUE TITLE
YAML inventory - Expected key=value host variable assignment

### ISSUE THREAD

**Issue by naisanza** [ansible/ansible#30586]
##### ISSUE TYPE

 - Documentation Report
 - Maybe bug?

##### COMPONENT NAME

Ansible Inventory YAML

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Vanilla ansible.cfg, no changes

##### OS / ENVIRONMENT

Ubuntu 16.04 to -> Proxmox Ubuntu 16.04 LXC

##### SUMMARY

Following the documentation for YAML inventories, the ansible-playbook errors on on the `vars:` syntax. Saying to use `ansible_user=root` instead of the documented `ansible_user: root` format

https://github.com/ansible/ansible/blob/devel/examples/hosts.yaml

##### STEPS TO REPRODUCE

Inventory:
```yaml
all:
  hosts: 
  children: 
    world0: 
      hosts: 
        git.server.com: 
        gui.server.com: 
        keras.server.com: 
        ldap.server.com: 
        awx.server.com: 
        radius.server.com: 
      vars:
        ansible_user: root

```

Playbook:
```
---
# https://gist.github.com/gwillem/4ba393dceb55e5ae276a87300f6b8e6f
- hosts: world0

  tasks:
  - name: install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
```

##### ACTUAL RESULTS

```
eric@ainiml:~/Desktop/ansible$ ansible-playbook -i host-yaml /home/eric/Desktop/github/antsable-tsl/playbooks/python-minimal.yml 
ERROR! Attempted to read "host-yaml" as YAML: 'NoneType' object is not iterable
Attempted to read "host-yaml" as ini file: host-yaml:13: Expected key=value host variable assignment, got: root 
```

**Comment by bcoca** [comment]
Actually, you get 2 errors, 1 when it tried to read as YAML, since that failed, it also tried to read as ini file.

This is the error from the YAML parser .. though not very helpful.
`ERROR! Attempted to read "host-yaml" as YAML: 'NoneType' object is not iterable`

I tested the file posted above and that seems to work fine with 2.4, testing with 2.3

**Comment by bcoca** [comment]
hrmphf, 2.3 does not like the empty 'hosts:' entry, this should work for you:
```yaml
all:
  children: 
    world0: 
      hosts: 
        git.server.com: 
        gui.server.com: 
        keras.server.com: 
        ldap.server.com: 
        awx.server.com: 
        radius.server.com: 
      vars:
        ansible_user: root
```
run with 2.3
```
#> ansible -m debug -a 'var=inventory_hostname' -i ./inv.yml all
keras.server.com | SUCCESS => {
    "inventory_hostname": "keras.server.com"
}
gui.server.com | SUCCESS => {
    "inventory_hostname": "gui.server.com"
}
ldap.server.com | SUCCESS => {
    "inventory_hostname": "ldap.server.com"
}
git.server.com | SUCCESS => {
    "inventory_hostname": "git.server.com"
}
radius.server.com | SUCCESS => {
    "inventory_hostname": "radius.server.com"
}
awx.server.com | SUCCESS => {
    "inventory_hostname": "awx.server.com"
}
```
