### ISSUE TITLE
Group Names with Dashes are Invalid in 2.4 YAML inventories

### ISSUE THREAD

**Issue by lystor** [ansible/ansible#30624]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
2.4.0.0
```

Hello

Group names with dashes are invalid in Ansible 2.4.

Reproducible only in static YAML/JSON inventories.

Dynamic and INI inventories support group names with dashes in 2.4.

**inventory.yml**
```yaml
all:
  children:
    webservers-usa:
      hosts:
        foo.example.com:
    webservers-canada:
      hosts:
        foo.example.com:
```

**test.yml**
```yaml
- hosts: webservers-usa
  connection: local
  gather_facts: no
  tasks:
    - debug: msg='hello'
```

# Ansible 2.4
```shell
# ansible-playbook -i inventory.yml test.yml 
 [WARNING]: Skipping 'webservers-usa' as this is not a valid group name

ERROR! webservers-usa is not a known host nor group
```

# Ansible 2.3
```shell
# ansible-playbook -i inventory.yml test.yml 
ok: [foo.example.com] => {
    "msg": "hello"
}
```
Please fix the ASAP.
Thank you
