### ISSUE TITLE
os_image id option does not work

### ISSUE THREAD

**Issue by jimmymccrory** [ansible/ansible#30634]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
os_image

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /tmp/ants/local/lib/python2.7/site-packages/ansible
  executable location = /tmp/ants/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```
##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Providing an 'id' option to a task using the os_image module does not work.
The glance service returns a 400 bad request error.

##### STEPS TO REPRODUCE

```yaml
---

- hosts: localhost
  gather_facts: no
  tasks:
    - name: Download tempest image
      get_url:
        url: "http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img"
        dest: "/var/tmp/cirros.img"

    - name: Ensure tempest image
      os_image:
        cloud: default
        validate_certs: no
        id: "cirros"
        name: "cirros"
        filename: "/var/tmp/cirros.img"
        container_format: "bare"
        disk_format: "qcow2"
        is_public: True
      register: tempest_image_create
      until: tempest_image_create | success
      retries: 5
      delay: 15
```

##### EXPECTED RESULTS

The given cirros image is uploaded and created with an id of 'cirros'.

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_B1QTMQ/ansible_module_os_image.py", line 190, in main
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/shade/openstackcloud.py", line 3640, in create_image
    **image_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/shade/openstackcloud.py", line 3758, in _upload_image_put
    name, image_data, meta, **image_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/shade/openstackcloud.py", line 3696, in _upload_image_put_v2
    image = self._image_client.post('/images', json=image_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keystoneauth1/adapter.py", line 310, in post
    return self.request(url, 'POST', **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/shade/_adapter.py", line 201, in request
    return self._munch_response(response, error_message=error_message)
  File "/usr/local/lib/python2.7/dist-packages/shade/_adapter.py", line 115, in _munch_response
    exc.raise_from_response(response, error_message=error_message)
  File "/usr/local/lib/python2.7/dist-packages/shade/exc.py", line 161, in raise_from_response
    raise OpenStackCloudBadRequest(msg, response=response)

fatal: [aio1_utility_container-7c896c6a]: FAILED! => {
    "attempts": 5,
    "changed": false,
    "extra_data": null,
    "failed": true,
    "invocation": {
        "module_args": {
            "api_timeout": null,
            "auth": null,
            "auth_type": null,
            "availability_zone": null,
            "cacert": null,
            "cert": null,
            "checksum": null,
            "cloud": "default",
            "container_format": "bare",
            "disk_format": "qcow2",
            "endpoint_type": "public",
            "filename": "/var/tmp/cirros.img",
            "id": "cirros",
            "is_public": true,
            "kernel": null,
            "key": null,
            "min_disk": 0,
            "min_ram": 0,
            "name": "cirros",
            "owner": null,
            "properties": {},
            "ramdisk": null,
            "region_name": null,
            "state": "present",
            "timeout": 180,
            "validate_certs": false,
            "verify": false,
            "wait": true
        }
    },
    "msg": "(400) Client Error for url: https://192.168.1.32:9292/v2/images Bad Request (Inner Exception: Expecting value: line 1 column 1 (char 0))"
}
```
