### ISSUE TITLE
Removing a public IPv4 address fails without warning in ec2 module

### ISSUE THREAD

**Issue by jvf** [ansible/ansible#30679]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/jvf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jvf/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
No changes.

##### OS / ENVIRONMENT
macOS 10.12.6

##### SUMMARY
Changing `assign_public_ip` from `yes` to `no` silently fails

##### STEPS TO REPRODUCE
Create an instance with 
```yaml
      ec2:
         ...
        assign_public_ip: yes
```

Change to 
```yaml
      ec2:
         ...
        assign_public_ip: no
```

Run playbook again. 

##### EXPECTED RESULTS

Print out a warning that unassigning the public IPv4 address is not possible.

##### ACTUAL RESULTS
Nothing. Ansible does not display any warning or similar, running the playbook seems successful. But the instance still has a public IPv4 address assigned.
