### ISSUE TITLE
script executes in check mode

### ISSUE THREAD

**Issue by rafernandez** [ansible/ansible#30676]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module script

##### ANSIBLE VERSION

```
2.3.2.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

In check mode, when a task with module script is executed, script is really executed on the node
##### STEPS TO REPRODUCE

```
cat playbook-test-script.yml 
- hosts: all
  tasks:
  - name: test module script
    script: touchTMP.sh
  - name: test module file
    file: path=/tmp/test-create-fic-with-mode-file state=touch mode=0777
```
```
cat touchTMP.sh 
#!/bin/bash
touch /tmp/test-create-fic-with-module-script
```
```
ansible-playbook -i localhost, -c local --check playbook-test-script.yml 

PLAY [all] ********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [test module script] *****************************************************************************************************************************************************************************************
changed: [localhost]

TASK [test module file] *******************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0
```

##### EXPECTED RESULTS

0 files in /tmp

##### ACTUAL RESULTS

1 file in /tmp :
```
/tmp/test-create-fic-with-module-script
```
