### ISSUE TITLE
eos_config not handling sockets properly

### ISSUE THREAD

**Issue by kromanow94** [ansible/ansible#30698]
Hello!

I've been on this issue for few days, did a lot of network debugging, read a lot of issues contributing to this one, but this seems to be rather not documented.

We have a role that is configuring switches with eos_config. It worked perfectly on ansible 2.1.0.0, but upgrading to 2.3.2.0 creates errors.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

eos_config

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = <...>
  configured module search path = <...>
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```
We can't use 2.4 because it's not compatible with our modules.
(CallbackModule' object has no attribute 'set_options')

##### OS / ENVIRONMENT

The ansible role is run inside container based on openjdk:8-jdk.

In out environment seven switches exists and only some of them (but every time random) are getting problems with sockets.

##### CONFIGURATION

```
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
```
##### ACTUAL RESULTS

Upgrading to 2.3.2.0 produces this problem at first:
```
failed: [...] (item=...) => {"failed": true, "item": "...", "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}
```
So I've came up to solution with configuration shown below.

##### CONFIGURATION

```
[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=1800s -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r

[paramiko_connection]
host_key_auto_add = True
```
Environment:

```
ANSIBLE_HOST_KEY_CHECKING=false
```
##### ACTUAL RESULTS

It works at first run, but for some switches every other run shows error:
```
 "err": "[Errno 111] Connection refused", "failed": true, "item": "<hostname>", "msg": "unable to connect to socket"
```

If I delete the sockets manually and run the playbook again, it works once. Then I have to remove them again.

##### STEPS TO REPRODUCE

1. Have a few switches to configure (seven in our env).
2. Run configure_eos.yml 

configure_eos.yaml
```
- name: enable vlan for control plane nodes
  eos_config:
    auth_pass: "{{ pass }}"
    authorize: yes
    host: "{{ hostvars[item]['switch_host'] }}"
    lines: "{{ ... }}"
    parents: "{{ ... }}"
    password: "{{ another_pass}}"
    username: "{{ user }}"
  with_items:
    - "{{ groups[network_provision_control_plane_group_name] | os_group_switches }}"
  run_once: true
  when: network_provision_configure_control_plane

- name: enable vlan for tenant nodes
  eos_config:
    auth_pass: "{{ pass }}"
    authorize: yes
    host: "{{ hostvars[item]['switch_host'] }}"
    lines: "{{ ... }}"
    parents: "{{ ... }}"
    password: "{{ another_pass }}"
    username: "{{ user }}"
  with_items:
    - "{{ play_hosts | os_group_switches }}"
  run_once: true

```

##### EXPECTED RESULTS

Both tasks are successful for every switch.

##### SUMMARY
For what I did notice is that sockets sometimes are not deleted automatically on abandoning connection (something with EOF possibly?).
Deleting sockets allows to run the playbook
