### ISSUE TITLE
unarchive in combination with tempfile leads to unfindable files

### ISSUE THREAD

**Issue by Bouwdie** [ansible/ansible#30703]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
* unarchive
* tempfile

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The unachive module in combination with the tempfile module leads to file not found error while is does exist. This happens only when the tempfile is created on account of another user than the running user.
The documentation for tempfile does state the following

> Files/directories created by module are accessible only by creator. 

If this scope would true-ly be this strict the archive module should also not be able to access this temporary directory. At least the behaviour across modules seems inconsistent regarding tempfile access 😸 

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  become: True
  tasks:
    - name: create the temp dir
      become: True
      become_user: deployment
      tempfile:
        state: directory
      register: artifact_dir

    - file:
        path: "{{ artifact_dir.path }}/artifact"
        state: touch

    - archive:
        path: "{{ artifact_dir.path }}/artifact"
        dest: "{{ artifact_dir.path }}/artifact.zip"
        remove: True
        format: zip

    - stat:
        path: "{{ artifact_dir.path }}/artifact.zip"
      register: stat_result

    - debug:
        var: stat_result

    - name: unarchive
      unarchive:
        src: "{{ artifact_dir.path }}/artifact.zip"
        dest: "{{ artifact_dir.path }}"
```

##### ACTUAL RESULTS

```
PLAY [localhost] *************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [create the temp dir] ***************************************************************************************************************************************************************************************************************************************************************************************************
 [WARNING]: Using world-readable permissions for temporary files Ansible needs to create when becoming an unprivileged user. This may be insecure. For information on securing this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user

changed: [localhost]

TASK [file] ******************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [archive] ***************************************************************************************************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [stat] ******************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] *****************************************************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "stat_result": {
        "changed": false, 
        "stat": {
            "atime": 1506003166.2916236, 
            "attr_flags": "e", 
            "attributes": [
                "extents"
            ], 
            "block_size": 4096, 
            "blocks": 8, 
            "charset": "binary", 
            "checksum": "ba4d7ccdd15789a39017553f7700246b15bb4375", 
            "ctime": 1506003166.2916236, 
            "dev": 51713, 
            "device_type": 0, 
            "executable": false, 
            "exists": true, 
            "gid": 0, 
            "gr_name": "root", 
            "inode": 15161, 
            "isblk": false, 
            "ischr": false, 
            "isdir": false, 
            "isfifo": false, 
            "isgid": false, 
            "islnk": false, 
            "isreg": true, 
            "issock": false, 
            "isuid": false, 
            "md5": "7fea5c24743d1cfba96aaf55357ddf04", 
            "mimetype": "application/zip", 
            "mode": "0644", 
            "mtime": 1506003166.2916236, 
            "nlink": 1, 
            "path": "/tmp/ansible.vwEU4j/artifact.zip", 
            "pw_name": "root", 
            "readable": true, 
            "rgrp": true, 
            "roth": true, 
            "rusr": true, 
            "size": 116, 
            "uid": 0, 
            "version": "1056917788", 
            "wgrp": false, 
            "woth": false, 
            "writeable": true, 
            "wusr": true, 
            "xgrp": false, 
            "xoth": false, 
            "xusr": false
        }
    }
}

TASK [unarchive] *************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/tmp/ansible.vwEU4j/artifact.zip' in expected paths."}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=3    unreachable=0    failed=1   

```
