### ISSUE TITLE
file transfer failure via cloud-init/cloud-config non-interactive

### ISSUE THREAD

**Issue by caphrim007** [ansible/ansible#30726]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

`ansible-config dump --only-changed` reports nothing when called interactively and non-interactively

##### SUMMARY

I seem to be running into this bug which was fixed and then unfixed according to the comments.

https://github.com/ansible/ansible/issues/20332

Adding Ansible commands to a cloud-config and then executing it in cloud-init on Ubuntu 16.04 results in failure. Curiously, if I am interactively logged in to the same console, it succeeds without  a problem.

##### STEPS TO REPRODUCE

An openstack environment and heat template with (at a minimum) this definition for an instance.
Fill in the params per your environment.

```
  ve_instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key_name }
      networks:
        - port: { get_resource: mgmt_port }
      user_data_format: RAW
      user_data:
        str_replace:
          params:
            wc_notify: { get_attr: [wait_handle, curl_cli] }
          template: |
            #cloud-config
            write_files:
              - path: /tmp/onboard.sh
                permissions: 0755
                owner: root:root
                content: |
                  #!/bin/bash

                  killall apt-get
                  apt-get update
                  apt-get install -y python-pip

                  pip install -r /tmp/requirements.pip.txt
                  ansible-playbook -i notahost, /tmp/onboard.yaml -vvvv
                  wc_notify --insecure --data-binary '{"status": "SUCCESS"}'

              - path: /tmp/requirements.pip.txt
                permissions: 0755
                owner: root:root
                content: |
                  ansible

              - path: /tmp/onboard.yaml
                permissions: 0755
                owner: root:root
                content: |
                  ---
                  - hosts: localhost
                    gather_facts: false
                    connection: local
                    vars:
                      jenkins_hostname: localhost
                    tasks:
                      - name: Install required apt keys
                        apt_key:
                          url: "{{ item }}"
                        with_items:
                          - "https://download.docker.com/linux/ubuntu/gpg"
                          - "https://pkg.jenkins.io/debian-stable/jenkins.io.key"

            runcmd:
             - /tmp/onboard.sh &
```

##### EXPECTED RESULTS

Ansible succeeds and the playbook deploys as expected.

##### ACTUAL RESULTS

```
ansible-playbook 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
No config file found; using defaults
setting up inventory plugins
Parsed notahost, inventory source with host_list plugin
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
statically imported: /root/.ansible/roles/franklinkim.docker-compose/tasks/install.yml
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: onboard.yaml *********************************************************
1 plays in /tmp/onboard.yaml

PLAY [localhost] ***************************************************************
META: ran handlers

TASK [Install required apt keys] ***********************************************
task path: /tmp/onboard.yaml:20
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/packaging/os/apt_key.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1506034504.48-143521434906157 `" && echo ansible-tmp-1506034504.48-143521434906157="` echo ~/.ansible/tmp/ansible-tmp-1506034504.48-143521434906157 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp64UaNJ TO ~/.ansible/tmp/ansible-tmp-1506034504.48-143521434906157/apt_key.py
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "failed to transfer file to ~/.ansible/tmp/ansible-tmp-1506034504.48-143521434906157/apt_key.py: [Errno 2] No such file or directory: '~/.ansible/tmp/ansible-tmp-1506034504.48-143521434906157/apt_key.py'"
}
	to retry, use: --limit @/tmp/onboard.retry

PLAY RECAP *********************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
