### ISSUE TITLE
junos_config commit/rollback not working

### ISSUE THREAD

**Issue by mattlan** [ansible/ansible#30778]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

junos_config

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /virtualenv/ansible23/ansiblenet/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION

[defaults]
forks = 25
host_key_checking = False
remote_tmp = /tmp/${USER}/.ansible/tmp
inventory = ./environments/production
retry_files_enabled = False
filter_plugins = .
callback_whitelist = slack

##### OS / ENVIRONMENT

Control host: Apple macOS 10.12.6 (Sierra)
Remote device: Juniper Junos 15.1R5.5

##### SUMMARY

Want playbook to either commit or rollback config based on tag provided, result is nothing happens on the remote device.  I was able to workaround the commit issue by using the below, though I don't currently have a valid workaround for rollback due to another issue (that I will be opening separately from this as it pertains to the junos_rpc module).
```
- junos_command:
        provider: "{{login}}"
        rpcs: commit-configuration
```

##### STEPS TO REPRODUCE

After making a change to the device and using `commit confirmed`, run the playbook using the below.

`ansible-playbook playbook.yml -t commit -e "host=groupname"`
or
`ansible-playbook playbook.yml -t rollback -e "host=groupname rollback=2"`

```yaml
---
- hosts: "{{host}}"
  connection: local
  gather_facts: no
  vars_prompt:
      - name: "login_pw"
        prompt: "Password"
        private: yes
  vars:
      login:
          host: "{{ansible_host}}"
          username: "{{lookup('env','USER')}}"
          password: "{{login_pw}}"
          transport: netconf
          timeout: 20
  tasks:
      - name: Commit junos config
        junos_config:
            provider: "{{login}}"
            confirm: 0
        tags: commit

      - name: Rollback junos config
        junos_config:
            provider: "{{login}}"
            rollback: "{{rollback | default(1)}}"
        tags: rollback
```

##### EXPECTED RESULTS

The config to rollback or commit, depending on tag used.

##### ACTUAL RESULTS

Ansible outputs either "ok" for commit, or "changed" for rollback -- which is expected.  However, on the device, nothing has actually occurred.

```
TASK [Rollback junos config] ***********************************************************************************************************************************************************************************************************
changed: [device1] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "backup": false,
            "comment": "configured by junos_config",
            "confirm": 0,
            "host": null,
            "lines": null,
            "password": null,
            "port": null,
            "provider": {
                "host": "device1",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": 20,
                "transport": "netconf",
                "username": "test"
            },
            "replace": null,
            "rollback": 2,
            "src": null,
            "src_format": null,
            "ssh_keyfile": null,
            "timeout": 10,
            "transport": null,
            "update": "merge",
            "username": null,
            "zeroize": false
        }
    }
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************
device1                : ok=1    changed=1    unreachable=0    failed=0
```
