### ISSUE TITLE
Git archive is not working if update is set to no

### ISSUE THREAD

**Issue by dimasdanz** [ansible/ansible#30774]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
git

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = [u'/ansible/hosts']
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = [u'/ansible/vendor']
```

##### OS / ENVIRONMENT

Running from: Ubuntu 16.04 (Xenial)
Managing: Ubuntu 16.04 (Xenial)

##### SUMMARY

git archive doesn't do anything if update is set to no

##### STEPS TO REPRODUCE

```yaml
- hosts: testing
  gather_facts: yes

  tasks:
    - name: Git archive
      git:
        repo: https://github.com/ansible/ansible-examples.git
        dest: /src/ansible-examples
        archive: /tmp/build.zip
        update: no
```

##### EXPECTED RESULTS

`build.zip` exists on `/tmp`
##### ACTUAL RESULTS

`build.zip` is not exists on `/tmp` and doesn't throw any error
___
I think it's because this part on `git.py`
```
    elif not update:
        # Just return having found a repo already in the dest path
        # this does no checking that the repo is the actual repo
        # requested.
        result['before'] = get_version(module, git_path, dest)
        result.update(after=result['before'])
        module.exit_json(**result)
```
Making archive part is not executed as setting `update` to `false` force the module to execute `module.exit_json(**result)`
```
    if archive:
        # Git archive is not supported by all git servers, so
        # we will first clone and perform git archive from local directory
        if module.check_mode:
            result.update(changed=True)
            module.exit_json(**result)

        create_archive(git_path, module, dest, archive, version, repo, result)
```
