### ISSUE TITLE
ec2_instance_facts dont show "tags"

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#30800]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_instance_facts

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jjabs/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]
```

##### CONFIGURATION
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Manjaro 17

##### SUMMARY
ec2_remote_facts deliver the instance tags as expected. 
The new module which should replace it (ec2_instance_facts) do not show instance tags.
Easy to reproduce since you can easily switch the module name and use the same params.

##### STEPS TO REPRODUCE
get_ec2_facts.yml

```yaml
---
- ec2_instance_facts:
     region: "your-region"
     aws_access_key: "your-key"
     aws_secret_key: "your-secret-key"
   filters:
     instance-state-name:        running
     "tag:Name": "your-instance-name"
  register: ec2_facts
```

##### EXPECTED RESULTS
```
ok: [localhost] => {
    "ec2_facts": {
     .... bla bla bla
                }, 
                "tags": {
                     "key": "value",
                     "foo": "bar"
                 }, 
            }
        ]
    }

```
##### ACTUAL RESULTS
```
ok: [localhost] => {
    "ec2_facts": {
     .... bla bla bla
                }, 
                "tags": {}, 
            }
        ]
    }

```
