### ISSUE TITLE
The ldap_attr module fails to set indexed attribute (olcAccess)

### ISSUE THREAD

**Issue by karlmdavis** [ansible/ansible#30814]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
The new `ldap_attr` module.

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.0.0
  config file = /home/karl/workspaces/cms/hhsdevcloud-ansible.git/ansible.cfg
  configured module search path = [u'/home/karl/.ansible/roles']
  ansible python module location = /home/karl/workspaces/cms/hhsdevcloud-ansible.git/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/karl/workspaces/cms/hhsdevcloud-ansible.git/venv/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
ANSIBLE_SSH_ARGS(/home/karl/workspaces/cms/hhsdevcloud-ansible.git/ansible.cfg) = -o ForwardAgent=yes
ANSIBLE_SSH_PIPELINING(/home/karl/workspaces/cms/hhsdevcloud-ansible.git/ansible.cfg) = True
DEFAULT_MODULE_PATH(/home/karl/workspaces/cms/hhsdevcloud-ansible.git/ansible.cfg) = [u'/home/karl/.ansible/roles']
DEFAULT_ROLES_PATH(/home/karl/workspaces/cms/hhsdevcloud-ansible.git/ansible.cfg) = [u'/home/karl/.ansible/roles']
DEFAULT_TIMEOUT(/home/karl/workspaces/cms/hhsdevcloud-ansible.git/ansible.cfg) = 120
HOST_KEY_CHECKING(/home/karl/workspaces/cms/hhsdevcloud-ansible.git/ansible.cfg) = False
```

##### OS / ENVIRONMENT
The management system is Ubuntu 14.04, the host being managed is Ubuntu 16.04. Both running Python 2.7.

##### SUMMARY
I've been using the `ldap_attr` module for over a year now, and have always had trouble getting it to work with multivalued and/or indexed attributes -- looking through all of my plays, I don't think I've ever gotten it to work. I was **super** excited to see its inclusion in Ansible 2.4, but unfortunately I'm still having the same troubles.

##### STEPS TO REPRODUCE

Here's a task that's failing, which _looks_ like almost identical to one from the examples.
```yaml
# Ensure that sudo/root and admin group members can modify the directory.
- name: Configure Directory Permissions
  ldap_attr:
    dn: olcDatabase={1}hdb,cn=config
    state: exact
    name: olcAccess
    values:
      - >-
        {0}to attrs=userPassword by self write
        by group.exact="cn=administrators-ldap,ou=groups,dc=hhsdevcloud,dc=us" write
        by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage
        by anonymous auth
        by * none
      - >-
        {1}to attrs=shadowLastChange by self write
        by * read
      - >-
        {2}to * by * read
        by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage
  become: true
```

##### EXPECTED RESULTS
I expected the task to run successfully.

##### ACTUAL RESULTS
The task fails with this error:
```
TASK [ldap-server : Configure Directory Permissions] ***********************************************************************************************************
fatal: [ldap]: FAILED! => {"changed": false, "exc": "Traceback (most recent call last):\n  File \"/tmp/ansible_hnJbW2/ansible_module_ldap_attr.py\", line 166, in main\n    LdapAttr(module).main()\n  File \"/tmp/ansible_hnJbW2/ansible_module_ldap_attr.py\", line 226, in main\n    self.connection.modify_s(self.dn, modlist)\n  File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 402, in modify_s\n    return self.result(msgid,all=1,timeout=self.timeout)\n  File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 503, in result\n    resp_type, resp_data, resp_msgid = self.result2(msgid,all,timeout)\n  File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 507, in result2\n    resp_type, resp_data, resp_msgid, resp_ctrls = self.result3(msgid,all,timeout)\n  File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 514, in result3\n    resp_ctrl_classes=resp_ctrl_classes\n  File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 521, in result4\n    ldap_result = self._ldap_call(self._l.result4,msgid,all,timeout,add_ctrls,add_intermediates,add_extop)\n  File \"/usr/lib/python2.7/dist-packages/ldap/ldapobject.py\", line 106, in _ldap_call\n    result = func(*args,**kwargs)\nOTHER: {'info': '<olcAccess> handler exited with 1', 'desc': 'Other (e.g., implementation specific) error'}\n", "failed": true, "msg": "{'info': '<olcAccess> handler exited with 1', 'desc': 'Other (e.g., implementation specific) error'}"}
```

##### WORKAROUND
The following task does succeed, though it's unfortunately not idempotent:
```yaml
- name: Configure Directory Permissions
  command: /usr/bin/ldapmodify -H ldapi:/// -Y EXTERNAL -D "cn=config"
  args:
    stdin: |
      dn: olcDatabase={1}hdb,cn=config
      changetype: modify
      delete: olcAccess
      -
      add:olcAccess
      olcAccess: {0}to attrs=userPassword by self write
        by group.exact="cn=administrators-ldap,ou=groups,dc=hhsdevcloud,dc=us" write
        by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage
        by anonymous auth
        by * none
      olcAccess: {1}to attrs=shadowLastChange by self write
        by * read
      olcAccess: {2}to * by * read
        by dn.exact=gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth manage
  become: true
```

Here's the (happily very boring) output:

```
TASK [ldap-server : Configure Directory Permissions] ***********************************************************************************************************
changed: [ldap]
```

My apologies if I'm screwing this up somehow, but best as I can tell, this is almost exactly the use case listed in the module's examples. If this is a bug, please note that I have similar issues getting non-indexed multivalued attributes to work, too.
