### ISSUE TITLE
lookup from file function cuts new line at the end of file

### ISSUE THREAD

**Issue by vladimirtiukhtin** [ansible/ansible#30829]
##### ISSUE TYPE
 Bug Report
##### COMPONENT NAME
lookups http://docs.ansible.com/ansible/latest/playbooks_lookups.html
##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.0
  config file = /home/vladimir.tiukhtin/.ansible.cfg
  configured module search path = ['/home/vladimir.tiukhtin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.2 (default, Jul 20 2017, 03:52:27) [GCC 7.1.1 20170630]
```
##### STEPS TO REPRODUCE
create file with any content and take sure there is a new line character at the end of the file, then create an statement like this:
```yaml
    zones:
      - name: example.com
        type: master
        content: "{{ lookup('file', 'zones/example.com') }}"
      - name: example.net
        type: master
        content: "{{ lookup('file', 'zones/example.net') }}"
```
##### EXPECTED RESULTS
lookup function takes file as it is with all characters, spaces and so on
##### ACTUAL RESULTS
lookup function filters new line character at the and of file

**Comment by alikins** [comment]
The file lookup plugin does a .rstrip() on the file contents it reads from the file read from the file, which will remove a trailing newlines. The docs don't mention it, but that has been the behavior since at least 2.0.0. 

For your case, you may need to re-append the trailing new line.

**Comment by vladimirtiukhtin** [comment]
Thanks for your explanation @alikins. Any ideas how to add news line in lookup from file?

**Comment by vladimirtiukhtin** [comment]
Answering my question.... This solves the problem:

```content: "{{ lookup('file', 'zones/example.net') + '\n'}}"```

**Comment by crist2026** [comment]
adding  + '\n' did not worked for me

**Comment by lcarva** [comment]
Also adding `+ '\n'` did not work for me. Possibly because I'm encoding the whole thing in base64?
```
content: "{{ lookup('file', 'my-file') + '\n' | b64encode }}"
```

My workaround was use slurp to load the file into a var:
```
- name: Load file into variable        
  local_action:                            
    module: slurp                          
    src: "my-file"         
  register: _my_file_slurped
```
Then I can use it as:
```
content: "{{ _my_file_slurped.content }}"
```

**Comment by vladimirtiukhtin** [comment]
From my point of view an ideal solution will be to add an additional option to the function like
```
content: "{{ lookup('file', 'zones/example.net') }}"
```
Removes everything from the end and
```
content: "{{ lookup('file', 'zones/example.net', true) }}"
```
Keeps file as it is

**Comment by racke** [comment]
This *breaks* SSL private keys. Also files have final newlines (e.g. looks odd in Git commits and with cat in a shell).

I can't see a point in tampering with existing files. Please fix that.

Cheat tip:

```
copy:
    content: |
      {{ lookup('file', users_inventory_dir + '/files/ssh-keys/' + item.ssh_id ) }}
    dest: "/home/{{ item.username }}/.ssh/id_rsa" 
```
