### ISSUE TITLE
[unarchive module] Unable to find file in expected paths error

### ISSUE THREAD

**Issue by africanzoe** [ansible/ansible#30821]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

The "[unarchive](http://docs.ansible.com/ansible/latest/unarchive_module.html)" module.

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

The default Ansible configuration.

##### OS / ENVIRONMENT

Centos & Redhat 7.2/7.3/7.4

##### SUMMARY

When using the unarchive module, the playbook fails with the following error:
```
FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/tmp/myfile.zip' in expected paths."}
```

##### STEPS TO REPRODUCE

Use one task in the following Playbook:
```yaml
---
- hosts: all
  become: True

  tasks:
     - name: unzip myfile
       unarchive:
          src: "/tmp/myfile.zip"
          dest: "/usr/local/bin"
          remove_src: True
```

##### EXPECTED RESULTS

The zipped file is unzipped and copied to the destination folder.

##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "failed": true, "msg": "Unable to find '/tmp/myfile.zip' in expected paths."}
```
