### ISSUE TITLE
HaProxy drain mode 'bool' object is not callable error

### ISSUE THREAD

**Issue by stewartwebb** [ansible/ansible#30833]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
HaProxy Module

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/stewart/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/2.7/bin/ansible
  python version = 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 12:39:47) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]

```

##### CONFIGURATION
`ansible-config dump --only-changed` returned nothing. I have changed no config.

##### OS / ENVIRONMENT
Running from OSX 10.10.5
Trying to control HaProxy 1.5.8 on Debian 8

##### SUMMARY
I am able to enable and disable HaProxy backends correctly but when I try to use the "drain" state type I get this error. The playbook works when I use enabled and disabled but fails with the below error when I use drain.

It says, `'bool' object is not callable`. I might just be configuring this wrong but I believe I am doing everything correctly and using the correct Ansible version.

##### STEPS TO REPRODUCE

```yaml
- name: Set server to drain
  hosts: haproxy
  sudo: yes
  tasks:
    - name: Set server1 to disabled
      haproxy:
        state: drain
        host: server1
        socket: /var/run/haproxy.sock
        backend: cluster_www
```

##### EXPECTED RESULTS

I expect the HaProxy backend to change to the drain state.

##### ACTUAL RESULTS

```
fatal: [10.5.59.15]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 10.5.59.15 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Xzs48s/ansible_module_haproxy.py\", line 454, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Xzs48s/ansible_module_haproxy.py\", line 450, in main\r\n    ansible_haproxy.act()\r\n  File \"/tmp/ansible_Xzs48s/ansible_module_haproxy.py\", line 410, in act\r\n    self.drain(self.host, self.backend)\r\nTypeError: 'bool' object is not callable\r\n", "msg": "MODULE FAILURE", "rc": 0}
```
