### ISSUE TITLE
redis module: new feature, support  sentinel mode

### ISSUE THREAD

**Issue by themr0c** [ansible/ansible#30835]
##### ISSUE TYPE
 
Feature Idea

##### COMPONENT NAME

redis

##### ANSIBLE VERSION

```
2.4.0
```

##### CONFIGURATION

non relevant

##### OS / ENVIRONMENT

non relevant

##### SUMMARY

It would be a nice feature to support the configuration of redis sentinel with the redis module.

It would be particularly convenient for nodes which are supposed to run only a redis-sentinel, but no redis service.

Do you believe also that this feature could be useful?

##### STEPS TO REPRODUCE

Given https://redis.io/topics/sentinel, the  main command is:

```
sentinel monitor <master-group-name> <ip> <port> <quorum>
```

The same command will fail once the service is already monitoring <master-group-name>, so we have to check that the ip:port ist not already monitored beforehand.

We should also verify that the ip:port is a master, because after a master/slave failover, it is an expected behaviour that the sentinel switches to the new master node. 

##### EXPECTED RESULTS

Call the redis module with:

```
redis:
  command: sentinel
  master_host: <host>
  master_port: <port>
  quorum: <quorum>
```

##### ACTUAL RESULTS

Using the redis module you can configure a redis master or slave, but not a sentinel.

**Comment by ansibot** [comment]
@themr0c Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by themr0c** [comment]
Description updated, is it acceptable like this @ansibot ?

**Comment by ansibot** [comment]
cc @slok
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Sephtex** [comment]
This feature has being written as a separate bash module, would that still be fine to be submitted as a PR?
Since the redis module is written in python, I tried to keep the current parameters as close as possible as the original one:

```
# Playbook example
---
- name: get assets
  hosts: all
  gather_facts: false
  tasks:
    - name: "redis_sentinel | configure sentinel to monitor the master"
      redis_sentinel:
        login_host: yiu-f1-redis01
        login_port: 26380
        master_host: yiu-f1-redis01
        master_port: 6380
        quorum: 2
```

If the above has being approved to be written as a bash script, I would gladly make a pull request about this.
