### ISSUE TITLE
nxos_vpc* : failures seen on N1 images

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#30846]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_vpc
- nxos_vpc_interface

##### ANSIBLE VERSION

```
ansible 2.4.0.0 (detached HEAD d14467b029) last updated 2017/09/22 13:55:10 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04

##### SUMMARY

`show running-config section vpc` is an invalid command on N1 images. The correct command is `show running-config vpc` which works on all tested platforms.

 ##### STEPS TO REPRODUCE

```yaml
  - name: Configure vpc
    nxos_vpc: &conf_vpc
      state: present
      domain: 100
      role_priority: 500
      system_priority: 2000
      pkl_dest: 192.168.100.4
      pkl_src: 10.1.100.20
      pkl_vrf: ntc
      peer_gw: true
      delay_restore: 5
      auto_recovery: true
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "Conf Idempotence"
    nxos_vpc: *conf_vpc
    register: result

  - assert: &false
      that:
        - "result.changed == false"
```

##### ACTUAL RESULTS

```
TASK [nxos_vpc : Conf Idempotence] ************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_vpc/tests/common/sanity.yaml:35
<n5k-xxx.example.com> connection transport is cli
<n5k-xxx.example.com> using connection plugin network_cli
<n5k-xxx.example.com> socket_path: /root/.ansible/pc/1b4e3e6315
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_vpc.py
<n5k-xxx.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n5k-xxx.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n5k-xxx.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1506021693.26-171102847106688 `" && echo ansible-tmp-1506021693.26-171102847106688="` echo /root/.ansible/tmp/ansible-tmp-1506021693.26-171102847106688 `" ) && sleep 0'
<n5k-xxx.example.com> PUT /tmp/tmpFZqODu TO /root/.ansible/tmp/ansible-tmp-1506021693.26-171102847106688/nxos_vpc.py
<n5k-xxx.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1506021693.26-171102847106688/ /root/.ansible/tmp/ansible-tmp-1506021693.26-171102847106688/nxos_vpc.py && sleep 0'
<n5k-xxx.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1506021693.26-171102847106688/nxos_vpc.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1506021693.26-171102847106688/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_8gZfUw/ansible_modlib.zip/ansible/module_utils/nxos.py", line 127, in get_config
    return self._device_configs[cmd]
FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "auto_recovery": true, 
            "delay_restore": "5", 
            "domain": "100",  
            "host": "n5k-xxx.example.com", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "peer_gw": true,  
            "pkl_dest": "192.168.100.4", 
            "pkl_src": "10.1.100.20", 
            "pkl_vrf": "ntc", 
            "port": null, 
            "provider": {
                "host": "n5k-xxx.example.com",               
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "use_ssl": null, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": null
            }, 
            "role_priority": "500", 
            "ssh_keyfile": null, 
            "state": "present", 
            "system_priority": "2000", 
            "timeout": null,  
            "transport": "cli", 
            "use_ssl": null,  
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "validate_certs": null
        }
    }, 
    "msg": "show running-config section vpc\r\r\n                                ^\r\n% Invalid command at '^' marker.\r\n\rn5k-136# "
}
```
