### ISSUE TITLE
ansible mount module doesn't check if fstab and present mount options differ

### ISSUE THREAD

**Issue by pdev77** [ansible/ansible#30848]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
mount module

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
&
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/ybs/u003/home/sysdev/tsg/u25356/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```
##### CONFIGURATION
[privilege_escalation]
become=True
#become_method=sudo
become_user=root
#become_ask_pass=False

[ssh_connection]
scp_if_ssh = True

##### OS / ENVIRONMENT
RHEL6/7

##### SUMMARY
mount module does not check presently mounted options (ie /etc/fstab is correct but someone has remounted for example /tmp manually)

##### STEPS TO REPRODUCE
#cat /etc/fstab | grep tmp
/dev/mapper/vg00-tmplv  /tmp                    xfs     defaults,nodev,noexec,nosuid 0 0

#mount | grep tmp
/dev/mapper/vg00-tmplv on /tmp type xfs (rw,nosuid,nodev,noexec,relatime,seclabel,attr2,inode64,noquota)

#mount -o remount exec /dev/shm
-- invoke ansible mount module with following playbook:

```yaml
Actual playbook in yaml below:
---
- hosts: testserver7
  tasks:

  - mount:
      fstype: tmpfs
      name: "/dev/shm"
      opts: "defaults,nodev,nosuid,noexec"
      src: tmpfs
      state: mounted
    register: output

  - debug: var=output

```

##### EXPECTED RESULTS
Expected that mount would be remounted with desired options (as using the "mounted" option)

##### ACTUAL RESULTS
nothing is changed.

```
TASK [rhel7 : mount] ***********************************************************
task path: /home/ansible/u25356/temp/RHEL7_Build/roles/rhel7/tasks/main.yml:9
ok: [ybsxlxrh7] => {"changed": false, "dump": "0", "fstab": "/etc/fstab", "fstype": "tmpfs", "name": "/dev/shm", "opts": "defaults,nodev,nosuid,noexec", "passno": "0", "src": "tmpfs"}
```
