### ISSUE TITLE
first_available_file doesn't appear to expand variables when using role-based file locations

### ISSUE THREAD

**Issue by mcodd** [ansible/ansible#3084]
I have a task that ALWAYS selects rsyncd.conf.default when I specify it this way:

```
- name: copy rsyncd.conf
  copy: dest=/etc/rsyncd.conf src={{ item }} mode=0644 owner=root group=root
  first_available_file:
    - rsyncd.conf.{{ inventory_hostname }}
    - rsyncd.conf.{{ systype }}
    - rsyncd.conf.default
```

But when I specify it this way it picks up the appropriate rsyncd.conf.{{ inventory_hostname }} and rsyncd.conf.{{ systype }} files:

```
- name: copy rsyncd.conf
  copy: dest=/etc/rsyncd.conf src={{ item }} mode=0644 owner=root group=root
  first_available_file:
    - /ansible/conf/roles/common/files/rsyncd.conf.{{ inventory_hostname }}
    - /ansible/conf/roles/common/files/rsyncd.conf.{{ systype }}
    - rsyncd.conf.default
```

I think this has something to do with the role magic of finding files in $roledir/files/, and that not expanding variables the same way they're expanded when the full path is specified?
