### ISSUE TITLE
Try to update azure_rm_securitygroup : source_address_prefix

### ISSUE THREAD

**Issue by tonnelj** [ansible/ansible#30863]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`azure_rm_securitygroup`

##### ANSIBLE VERSION

```
2.4.0
```

##### OS / ENVIRONMENT

CentOS 7.3

Steps of the Ansible installation
```
sudo yum check-update; sudo yum install -y gcc libffi-devel python-devel openssl-devel epel-release
sudo yum install -y python-pip python-wheel

sudo pip install ansible
sudo pip install ansible[azure]
sudo pip install dnspython
```

##### SUMMARY

Hello,

When I try to update network security group rules for Azure, in fact the option **source_address_prefix**, the value updated in the YML is not updated in Azure. However option like destination_port_range are updated when modified

##### STEPS TO REPRODUCE

Original YML

```yaml

  - name: Create security group that allows SSH and HTTP
    azure_rm_securitygroup: 
      resource_group: '{{ resourceGroup }}'
      name: 'NSG-{{ nsgName }}'
      purge_rules: yes
      state: present
      rules: 
        - name: SSH-Ansible
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
          source_address_prefix: 1.1.1.1


```

Modified YML

```yaml

  - name: Create security group that allows SSH and HTTP
    azure_rm_securitygroup: 
      resource_group: '{{ resourceGroup }}'
      name: 'NSG-{{ nsgName }}'
      purge_rules: yes
      state: present
      rules: 
        - name: SSH-Ansible
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 100
          direction: Inbound
          source_address_prefix: 2.2.2.2


```
_strings in {{ }} are parameters passed with --extra-vars_

##### EXPECTED RESULTS

The IP source has to be updated in Azure.

##### ACTUAL RESULTS

Nothing is updated
