### ISSUE TITLE
Explain, which condition is False, when skipping a task

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#30864]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Executor

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/mi/.ansible/plugins/modules', u'/opt/share/ansible/plugins/modules']
  ansible python module location = /opt/lib/python2.7/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 11:37:53) [GCC 4.2.1 Compatible FreeBSD Clang 5.0.0 (tags/RELEASE_500/final 312559)]
```

##### CONFIGURATION

`# ansible-config dump --only-changed | wc`
       1       0       1

##### OS / ENVIRONMENT

N/A

##### SUMMARY
When a task is skipped because of the `when`-condition(s), it would be extremely helpful, if Ansible cited the condition. Especially, when there are more than one...

##### STEPS TO REPRODUCE

```yaml
- name: Say meow
  debug: msg=Meow
    when:
     - you are a cat
     - you are hungry
     - your human is within an earshot
```

##### EXPECTED RESULTS

```
skipping: [cat1]: Condition 'you are hungry' not met
skipping: [cat2]: Condition 'your human is within an earshot' not met
skipping: [wombat2]: Condition 'you are a cat' not met
```

##### ACTUAL RESULTS
```
skipping: [cat1]
skipping: [cat2]
skipping: [wombat2]
```
If run with `-vvv`, there will be an explanation for the skip, but it will always say only that the `"Conditional result was False"` -- it would seem, spelling out, _which_ condition it was, is an easy thing to add. And not too noisy even for regular (non-verbose) output...

**Comment by UnitedMarsupials-zz** [comment]
Ok, looking into the code, I see, that the current "Conditional result was False" message is generated in `task_executor.py` when the task's `evaluate_conditional` method returns `False`. The executor does not know, which condition was not satisfied...

The `evaluate_conditional` method (in `conditional.py`) needs to be modified to return the text of (or the order-number) of the failed condition and whatever else may be useful -- or `True`, if all conditions were satisfied. The callers of the method would need updating too, of course.

I can, probably, offer a patch of my own -- if the powers deem this feature worth implementing to begin with...

**Comment by alikins** [comment]
https://github.com/ansible/ansible/pull/24254 was a proposed implementation of this.

**Comment by nrwahl2** [comment]
Why was it dropped?

**Comment by UnitedMarsupials-zz** [comment]
@alikins, it seemed in your patch (#24254) the conditions would keep on evaluating (so as to report the result) even after one of them results in `False`. That would not be right -- and could break things in some cases. Consider:
```yaml
 foo:
  when:
    - whatever is defined
    - 'someattribute' in whatever
```
When the first condition is false, trying to evaluate the second will be an _error_... Also, some evaluations may have side-effects...

**Comment by ansibot** [comment]
cc @mattclay
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mtnbikenc** [comment]
This would be very helpful in debugging complex multi-item `when:` conditionals.

**Comment by alikins** [comment]
@UnitedMarsupials I've updated the branch at #24254 to handle 'undefined' vars more like Conditional does now, while also showing a little more info about what exactly was undefined. That branch also will fail a Conditional after the first 'false' result, instead of evaluating all of the when clauses. 

For cases where there is an undefined early, the behavior should be similar to current behavior.

**Comment by MartinVUALTO** [comment]
I am looking forward to this feature, right now debugging cases where tasks are unexpectedly skipped is a pain! However I find the process here very confusing. #24254 seems to be closed but the last comment was it failed CI and a discussion label was added (is this the discussion?). This report remains open with the test label applied. So, nearly ready?

**One thing not covered here is the use of tags**. As far as I can tell tags can also cause a task to be listed as skipped by adding command line options ```--tags``` and/or ```--skip_tags```. i.e.

    --- # caller.yml
    - include_tasks: tasks.yml
      tags: runme

    --- # tasks.yml
    - block:
        - debug:
          msg: Hello
       
    - tags: always

I have something similar to the above Ansible (but obviously with much more besides) and when executed from the command line with ```--tags runme``` I am seeing the tasks in the block listed as skipped. I'm not asking for assistance fixing my issue, I'm just pointing out that tags also cause ```"skip_reason": "Conditional result was False"``` without a when clause in sight and I hope this fix would save me much debugging time.

**Comment by aminancelot** [comment]
Any news on this please? I'm an ansible fan but it still has some big pain points, this clearly is one.

**Comment by cmurray47** [comment]
+1

**Comment by yanivezrach** [comment]
This is a great idea.

**Comment by Raman-Kathpalia** [comment]
This would be a good feature add. And debugging would become easier.

**Comment by wturrell** [comment]
Just to endorse what @MartinVUALTO said - that you can see a bunch of tasks, all with no conditions showing `"skip_reason": "Conditional result was False"` because you accidentally entered the wrong tag name.

**Comment by bcoca** [comment]
A few of things:
 - no one is currently working on adding this feature, that is why this ticket is still open.
 - even if someone comes up with an implementation, the performance hit might be too prohibitive to use.
 - this might not give most people what they need, you might have multiple 'false' conditions

In my case, I avoid complex conditionals, mostly by assigning the parts into variables and then using the variables in the conditional, this allows for much simpler debugging.

```yaml
- name: Say meow
  debug: msg=Meow
  when: cat and hungry and earshot
  vars:
     cat : you are a cat
     hungry: you are hungry
     earshot: your human is within an earshot
```

**Comment by aminancelot** [comment]
@bcoca I have seen this happening with very simple to no conditionals. I unfortunately don't have an example in my hands right now but let's not assume right away it's because of misuse.
On the performance side of things, I'd gladly accept a command line switch to turn this feature on.

**Comment by bcoca** [comment]
An explicit knob to turn it on definitely make performance less of an issue.

Also, I did not mean to imply misuse, sometimes life requires complex conditionals, I was just advising to break them up into smaller and easier to handle chunks.

**Comment by ncoghlan** [comment]
@bcoca Note that even with simple conditionals, the status quo results in very odd double-negative debug output when a `fail` task is skipped:

```
TASK [Exit if sync target does not exist] **************************************
skipping: [10.17.2.103] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}
skipping: [10.17.1.106] => {
    "changed": false,
    "skip_reason": "Conditional check failed",
    "skipped": true
}
```

(That particular use case would likely be well-served by the dedicated "skip_reason" field proposed in https://github.com/ansible/ansible/issues/5449, but having Ansible populate it automatically does seem like a better approach)

**Comment by aminancelot** [comment]
So here's one, NO CONDITIONAL, skipped, can't get any idea why.

swarm.yml
```
- hosts: swarm
  roles:
    - swarm
  vars:
    ansible_python_interpreter: /usr/bin/python3
```

roles/swarm/tasks/main.yml
```
- name: Deploy swarm cron.
  run_once: yes
  docker_stack:
    state: present
    name: swarm_cronjob
    compose:
      - version: '3.7'
        services:
          app:
            image: crazymax/swarm-cronjob
            volumes:
              - "/var/run/docker.sock:/var/run/docker.sock"
            environment:
              - "TZ=Europe/Paris"
              - "LOG_LEVEL=info"
              - "LOG_JSON=false"
            deploy:
              placement:
                constraints:
                  - node.role == manager
```

`ansible-playbook -u user -i inventories/docker_env.hosts swarm.yml --diff -C`
```
Ending to:
...
TASK [swarm : Deploy swarm cron.] *********************************************************************************************************************************************************************************
skipping: [docker1]
```

Seriously, I love ansible but **this** is a strong issue.
