### ISSUE TITLE
vmware_guest - Cluster option stopped working

### ISSUE THREAD

**Issue by coltsixshooter** [ansible/ansible#30879]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

ansible 2.4.0.0
  config file = /Users/xxxx/.ansible.cfg
  configured module search path = [u'/Users/xxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

##### CONFIGURATION

DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/Users/xxx/workspace/devops/platform-roles', u'/Users
HOST_KEY_CHECKING(/Users/xxx/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/xxx/.ansible.cfg) = False
##### OS / ENVIRONMENT

Darwin xxxxx.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
##### SUMMARY

vmware_guest option "Cluster" does not seem to be returning the correct hosts in the specified Cluster. Using esxi-hostname to a specific host does work.

This used to work and may have broken in 2.4

##### STEPS TO REPRODUCE

```
- name: "Create DHCP VM {{ inventory_hostname }}"
  vmware_guest:
    hostname: "{{ vc_hostname }}"
    username: "{{ vc_user }}"
    password: "{{ vc_pass }}"
    cluster: "{{ vc_cluster }}"
    datacenter: "{{ vc_datacenter }}"
    template: "{{ vm_template }}"
    name: "{{ inventory_hostname }}"
    networks:
      - vlan: "{{ vm_vlan }}"
        type: "dhcp"
    annotation: "{{ vm_notes }}"
    folder: "{{ vc_folder }}"
    disk:
      - size_gb: 30
        type: thin
        datastore: "{{ vm_datastore }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpu }}"
    customization:
      hostname: "{{ inventory_hostname }}"  
      domain: "{{ vm_domain }}"
    customvalues:
      - { key: "Created By", value: "Ansible" } 
      - { key: "Department", value: "Engineering" } 
      - { key: "Requested By", value: "Jeff Yates" } 
      - { key: "Date Created", value: "{{ ansible_date_time.date }}" } 
    state: poweredon
    validate_certs: no
    force: yes
    wait_for_ip_address: "{{ vm_wait_for | default('yes') }}"
  register: newvm   
```

##### EXPECTED RESULTS

I expected it to use a host in the specified Cluster.

##### ACTUAL RESULTS

Since "Cluster" is not finding the correct Host with the correct Datastore it fails since it can't find the template. If I use esxi_hostname instead of cluster it works just fine.

Does not find the correct host in the Cluster.
```
fatal: [jaytest]: FAILED! => {
    "changed": true, 
    "clone_method": "Clone", 
    "clonespec": {
        "config": {
            "alternateGuestName": null, 
            "annotation": null, 
            "bootOptions": null, 
            "changeTrackingEnabled": null, 
            "changeVersion": null, 
            "consolePreferences": null, 
            "cpuAffinity": null, 
            "cpuAllocation": null, 
            "cpuFeatureMask": [], 
            "cpuHotAddEnabled": true, 
            "cpuHotRemoveEnabled": null, 
            "crypto": null, 
            "deviceChange": [
                {
                    "backing": null, 
                    "device": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualE1000'>", 
                    "dynamicProperty": [], 
                    "dynamicType": null, 
                    "fileOperation": null, 
                    "operation": "edit", 
                    "profile": []
                }
            ], 
            "dynamicProperty": [], 
            "dynamicType": null, 
            "extraConfig": [], 
            "files": null, 
            "firmware": null, 
            "flags": null, 
            "ftInfo": null, 
            "guestAutoLockEnabled": null, 
            "guestId": null, 
            "instanceUuid": null, 
            "latencySensitivity": null, 
            "locationId": null, 
            "managedBy": null, 
            "maxMksConnections": null, 
            "memoryAffinity": null, 
            "memoryAllocation": null, 
            "memoryHotAddEnabled": true, 
            "memoryMB": 2048, 
            "memoryReservationLockedToMax": null, 
            "messageBusTunnelEnabled": null, 
            "migrateEncryption": null, 
            "name": null, 
            "nestedHVEnabled": null, 
            "networkShaper": null, 
            "npivDesiredNodeWwns": null, 
            "npivDesiredPortWwns": null, 
            "npivNodeWorldWideName": [], 
            "npivOnNonRdmDisks": null, 
            "npivPortWorldWideName": [], 
            "npivTemporaryDisabled": null, 
            "npivWorldWideNameOp": null, 
            "npivWorldWideNameType": null, 
            "numCPUs": 2, 
            "numCoresPerSocket": null, 
            "powerOpInfo": null, 
            "repConfig": null, 
            "scheduledHardwareUpgradeInfo": null, 
            "swapPlacement": null, 
            "tools": null, 
            "uuid": null, 
            "vAppConfig": null, 
            "vAppConfigRemoved": null, 
            "vAssertsEnabled": null, 
            "vPMCEnabled": null, 
            "version": null, 
            "virtualICH7MPresent": null, 
            "virtualSMCPresent": null, 
            "vmProfile": []
        }, 
        "customization": "<class 'pyVmomi.VmomiSupport.vim.vm.customization.Specification'>", 
        "dynamicProperty": [], 
        "dynamicType": null, 
        "location": {
            "datastore": "'vim.Datastore:datastore-1749':Tintri-Anchor", 
            "deviceChange": [], 
            "disk": [], 
            "diskMoveType": null, 
            "dynamicProperty": [], 
            "dynamicType": null, 
            "folder": null, 
            "host": null, 
            "pool": "'vim.ResourcePool:resgroup-716':Resources", 
            "profile": [], 
            "service": null, 
            "transform": null
        }, 
        "memory": null, 
        "powerOn": false, 
        "snapshot": null, 
        "template": false
    }, 
    "configspec": {
        "alternateGuestName": null, 
        "annotation": null, 
        "bootOptions": null, 
        "changeTrackingEnabled": null, 
        "changeVersion": null, 
        "consolePreferences": null, 
        "cpuAffinity": null, 
        "cpuAllocation": null, 
        "cpuFeatureMask": [], 
        "cpuHotAddEnabled": true, 
        "cpuHotRemoveEnabled": null, 
        "crypto": null, 
        "deviceChange": [
            {
                "backing": null, 
                "device": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualE1000'>", 
                "dynamicProperty": [], 
                "dynamicType": null, 
                "fileOperation": null, 
                "operation": "edit", 
                "profile": []
            }
        ], 
        "dynamicProperty": [], 
        "dynamicType": null, 
        "extraConfig": [], 
        "files": null, 
        "firmware": null, 
        "flags": null, 
        "ftInfo": null, 
        "guestAutoLockEnabled": null, 
        "guestId": null, 
        "instanceUuid": null, 
        "latencySensitivity": null, 
        "locationId": null, 
        "managedBy": null, 
        "maxMksConnections": null, 
        "memoryAffinity": null, 
        "memoryAllocation": null, 
        "memoryHotAddEnabled": true, 
        "memoryMB": 2048, 
        "memoryReservationLockedToMax": null, 
        "messageBusTunnelEnabled": null, 
        "migrateEncryption": null, 
        "name": null, 
        "nestedHVEnabled": null, 
        "networkShaper": null, 
        "npivDesiredNodeWwns": null, 
        "npivDesiredPortWwns": null, 
        "npivNodeWorldWideName": [], 
        "npivOnNonRdmDisks": null, 
        "npivPortWorldWideName": [], 
        "npivTemporaryDisabled": null, 
        "npivWorldWideNameOp": null, 
        "npivWorldWideNameType": null, 
        "numCPUs": 2, 
        "numCoresPerSocket": null, 
        "powerOpInfo": null, 
        "repConfig": null, 
        "scheduledHardwareUpgradeInfo": null, 
        "swapPlacement": null, 
        "tools": null, 
        "uuid": null, 
        "vAppConfig": null, 
        "vAppConfigRemoved": null, 
        "vAssertsEnabled": null, 
        "vPMCEnabled": null, 
        "version": null, 
        "virtualICH7MPresent": null, 
        "virtualSMCPresent": null, 
        "vmProfile": []
    }, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "annotation": "Platform Weblogic", 
            "cluster": "RPM", 
            "customization": {
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "customvalues": [
                {
                    "key": "Created By", 
                    "value": "Ansible"
                }, 
                {
                    "key": "Department", 
                    "value": "Engineering"
                }, 
                {
                    "key": "Requested By", 
                    "value": "Jeff"
                }, 
                {
                    "key": "Date Created", 
                    "value": "2017-09-25"
                }
            ], 
            "datacenter": "LV - Prod", 
            "disk": [
                {
                    "datastore": "/Tintri/Tintri-UAT-RPM", 
                    "size_gb": 30, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "/Platform-Uat/rpm", 
            "force": true, 
            "guest_id": null, 
            "hardware": {
                "memory_mb": 2048, 
                "num_cpus": 2
            }, 
            "hostname": "a1vcenter01.********", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "name_match": "first", 
            "networks": [
                {
                    "name": "dvPort-uat-10.10.114", 
                    "type": "dhcp", 
                    "vlan": "dvPort-uat-10.10.114"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "poweredon", 
            "template": "RHMaster7.x-1", 
            "username": "root", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }
    }, 
    "msg": "Unable to access the virtual machine configuration: Unable to access file [Tintri-Anchor] RHMaster7.x-1/RHMaster7.x-1.vmtx"
}
```
