### ISSUE TITLE
EC2 ASG deploy fails "until" loop if current ASG size is 1 instance

### ISSUE THREAD

**Issue by cameronurnes** [ansible/ansible#30899]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_asg module

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/urnes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.11 (default, Jan 22 2016, 08:29:18) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### OS / ENVIRONMENT
OSX 12, Ubuntu 16.04

##### SUMMARY
After this change: https://github.com/ansible/ansible/commit/eb4cc31ae579bd87f7b7f0e309180518f315ad20#diff-da91568af8631cf0905f8dd43410a4d3

The task is no longer able to update an ASG whose current size is one machine.  Reverting the module fixes the issue, and allows deployment to continue.  Groups with multiple active machines do not encounter this issue.  This worked in 2.3, but no longer in 2.4.

##### STEPS TO REPRODUCE

```
- name: Create autoscaling group
  ec2_asg:
    name: "{{ aws.environment }}-{{ lc_type }}-asg"
    health_check_period: 180
    load_balancers: "{{ lc_elb }}"
    health_check_type: ELB
    launch_config_name: "{{ lc_result.name }}"
    min_size: "{{ asg_min_size }}"
    max_size: "{{ asg_max_size }}"
    desired_capacity: "{{ asg_properties.results[0].desired_capacity | default(3) }}"
    region: us-east-1
    replace_all_instances: yes
    replace_batch_size: "{{ (asg_properties.results[0].desired_capacity | default(2) / 2) | round(0, 'ceil') | int }}"
    state: present
    vpc_zone_identifier: "{{ ec2_subnet.subnets | map(attribute='id') | join(',') }}"
    tags:
      - environment: '{{ aws.environment }}'
        propagate_at_launch: yes
      - Name: '{{ lc_type }}'
        propagate_at_launch: yes
      - ASG: True
  until: (asg_result is defined) and (asg_result.viable_instances|int >= asg_min_size|int)
  delay: 10
  retries: 120
  when: asg_properties.results[0] is defined and lc_elb is defined
  register: asg_result
```

##### EXPECTED RESULTS
Normally, the machines in the ASG are replaced by the specified LC.   Groups with any number of active instances should work.

##### ACTUAL RESULTS
Groups with only 1 active machine fail to deploy, even though the (old) machine is healthy and passing checks.  The variable being checked is set by the task checking the variable, using "until".

```
TASK [asg_deploy : Create autoscaling group] ****************************************************************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check '(asg_result is defined) and (asg_result.viable_instances|int >= asg_min_size|int)' failed. The error was: error while evaluating conditional ((asg_result is defined) and (asg_result.viable_instances|int >= asg_min_size|int)): 'dict object' has no attribute 'viable_instances'"}
```
