### ISSUE TITLE
Mount module creates duplicate entries in /etc/fstab

### ISSUE THREAD

**Issue by byronmccollum** [ansible/ansible#3090]
Mount module creates an entry in /etc/fstab every time it runs, causing duplicate entries. Desired result would be to only ad the entry if it doesn't already exist.

**Comment by mpdehaan** [comment]
I'm need more information in this ticket.

Can you please show me your playbook entry where you are creating the mount point?

**Comment by byronmccollum** [comment]
```
- name: Mount Storage Devices
  mount: src=/dev/{{ item }} name=/srv/node/{{ item }} fstype=xfs opts="noatime,nodiratime,nobarrier,logbufs=8 0 0" state=mounted
  with_items:
    - xvdb1
    - xvdb2
    - xvdb3
```
