### ISSUE TITLE
I want to call two json group variable at time on two different hosts

### ISSUE THREAD

**Issue by prabhakarsultane** [ansible/ansible#30925]
Hi,

I have define variable in below json format and i have two hosts as one is database and another one is webserver so want to execute two json group on two different host through ansible, json group will be dyanmic. so can anybody help if it is possible. 

Json:
```json
software: {
  database: [{
          keyserver: "keyserver.ubuntu.com",
          id: "EA312927",
	  repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse",
          package: "mongodb-org"
	 },
         {
          keyserver: "keyserver.ubuntu.com",
          id: "EA312927",
	  repo: "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse",
          package: "mongodb-org"
         }
      ], 
  webserver: [{
          keyserver: "",
          id: "",
	  repo: "",
          package: "nginx"
	 },
         {
          keyserver: "",xxx`
          id: "",
	  repo: "",
          package: "tomcat8"
         }
      ]  
}
```

Ansible:

```yaml
---
- name: Add key for mentioned packages
  apt_key: keyserver="{{ item.keyserver }}" id="{{ item.id }}" state=present
  with_items: "{{ software.webserver }}"
  ignore_errors: yes
  no_log: True
  
- name: add repo
  apt_repository:
   repo: "{{ item.repo }}"
   state: present
  with_items: "{{ software.webserver }}"  
  ignore_errors: yes
  no_log: True

- name: Update APT package cache
  action: apt update_cache=yes
  become: true

- name: install software
  apt: name="{{ item.package }}"
  with_items: "{{ software.webserver }}"
  become: true
```
