### ISSUE TITLE
os_image does not include "tag" parameter

### ISSUE THREAD

**Issue by oridgar** [ansible/ansible#30923]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

os_image

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

default configuration

##### OS / ENVIRONMENT

N/A

##### SUMMARY

when running os_image module, there isn't an option to add a tag to an image.
when running the command through openstack CLI the option is available.
I did not find any other way to tag an image through ansible except running openstack CLI from a shell/command task.
##### STEPS TO REPRODUCE

```
  - name: upload custom image to glance
    os_image:
      filename: "myfile.qcow2"
      name: "test_image"
      disk_format: "qcow2"
      container_format: "bare"
      tag: "experiment"
```

##### EXPECTED RESULTS

image is created in glance with the tag  "experiment"

##### ACTUAL RESULTS

Not possible as this parameter does not exist

```

```
