### ISSUE TITLE
nxos_snmp_user documented auth should be authentication 

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#30941]
##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
nxos_snmp_user_module
http://docs.ansible.com/ansible/latest/nxos_snmp_user_module.html
##### ANSIBLE VERSION
```
[root@localhost ~]# ansible --version
ansible 2.5.0
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
[root@localhost ~]# ansible-config dump --only-changed
DEFAULT_GATHERING(/root/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/root/ansible.cfg) = [u'/root/hosts']
HOST_KEY_CHECKING(/root/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/root/ansible.cfg) = True

##### OS / ENVIRONMENT
CentOS Linux release 7.3.1611 (Core)
##### SUMMARY
`auth` is documented, but it should be `authentication` 

##### STEPS TO REPRODUCE
just the docs are wrong, the following playbook works:

```
---
- hosts: cisco
  connection: local
  tasks:
    - nxos_snmp_user:
        user: example_user
        group: network-admin
        authentication: sha
        pwd: test_password
        provider: "{{login_info}}"
```
