### ISSUE TITLE
lvg- device not found

### ISSUE THREAD

**Issue by shankerrhce** [ansible/ansible#30951]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lvg
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules/']
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### SUMMARY

"/sbin/vgcreate vgma{{dbname}}lf1  /dev/sdd3"
The above shell command create a volume group with sdd3 disk but when i use the lvg module to create a volume create after creation of disk /dev/sdd3 partition.

I have tested same with shell module with above command it works but it gives error with lvg

##### STEPS TO REPRODUCE

```yaml
- name: create a volume group
  lvg:
    vg: "vgma{{dbname}}lf1"
    pvs: "/dev/sdd{{avlpart}}"
    state: present
```

##### ACTUAL RESULTS

```
fatal: [10.8.67.43]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "force": false,
            "pesize": 4,
            "pvs": [
                "/dev/sdd3 "
            ],
            "state": "present",
            "vg": "vgmavobtlf1",
            "vg_options": ""
        }
    },
    "msg": "Device /dev/sdd3  not found."
```

**Comment by ansibot** [comment]
cc @abulimov
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@shankerrhce Thanks for reporting this issue. Could you please check -

```
python -c "import os; print(os.path.exists('/dev/sdd3'))"
```

and also, I notice there is space after "/dev/sdd3"

```
fatal: [10.8.67.43]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "force": false,
            "pesize": 4,
            "pvs": [
                "/dev/sdd3 " # <----------------- space after 3
            ],
            "state": "present",
            "vg": "vgmavobtlf1",
            "vg_options": ""
        }
    },
    "msg": "Device /dev/sdd3  not found." # <----------------- same here, space after 3
```

**Comment by Akasurde** [comment]
needs_info

**Comment by Akasurde** [comment]
I can reproduce the same output if I add space in variable

```
---
- name: sample
  gather_facts: no
  hosts: localhost
  vars:
    - disk: "3 "
  tasks:
    - name: a
      lvg:
        vg: sample_Vg
        pvs: "/dev/sdd{{disk}}"
```

Output:

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "force": false,
            "pesize": 4,
            "pv_options": "",
            "pvs": [
                "/dev/sdd3 "
            ],
            "state": "present",
            "vg": "sample_Vg",
            "vg_options": ""
        }
    },
    "msg": "Device /dev/sdd3  not found."
}
```

**Comment by ansibot** [comment]
@shankerrhce This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by shankerrhce** [comment]
I will recheck and get back to you

**Comment by Akasurde** [comment]
Closing this issue due inactivity of user. Please feel free to re-open if problem persists.

**Comment by Pectojin** [comment]
I'm experiencing this issue on Ansible 2.6.1
``` 
- name: Format disk and create VG "data"
  lvg:
    vg: data
    pvs: "/dev/sdc"
```
Output
```
 FAILED! => {"changed": false, "msg": "Device /dev/sdc not found."}
```
No spaces in mine, though.

`python -c "import os; print(os.path.exists('/dev/sdc'))"` outputs `True`
