### ISSUE TITLE
"winrm send_input failed" "WinRMTransportError: (u'http', u'Bad HTTP response returned from server. Code 500';"

### ISSUE THREAD

**Issue by sanjeevrg473** [ansible/ansible#30950]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
1. WINRM
2. winrm send_input failed

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]

```

##### OS / ENVIRONMENT
SLES 11 - Controller
Win 2012 R2 - Remote Windows Server where playbook is being executed on

##### SUMMARY
I have around 28 tasks inside a play. It is related to pre-server configuration. Making registry entry changes, adding roles and features, copying zip to servers, JRE installation, setting port ranges etc.

Whenever I run the playbook I get the following error. I dont know what exactly is happening with my Windows Server 2012 R2 server.

After 8 tasks are completed, the execution is failing. Its always failing at some or other task.. I dont know if it has something to do with timeout or network drop or ansible WINRM issue etc.

Request you to look into it and help me out.

##### STEPS TO REPRODUCE
    ansible-playbook config.yaml -vvvv

```yaml
tasks:
  - name: Validate if xxxx drive exists or not
    script: files/xxx.bat
    register: output
  - debug: var=output

  - name: Registry Chnages
    win_command: "{{ item.action }}"
    with_items:
      - { action: 'netsh int tcp set global chimney=disabled'}
      - { action: 'netsh interface tcp set global autotuning=disabled'}
      - { action: 'wmic nicconfig where index=8 call SetTcpipNetbios 2'}
    register: output
  - debug: var=output

  - name: Registry changes 
    win_regedit: path={{ item.path }} name={{ item.name }} data={{ item.data }} type={{ item.list }}
      with_items:
        - { path: 'HKLM:\system\currentcontrolset\xxxx', name: 'xxxx', data: 'xx', list: 'dword' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\xxxx\{xxx\xxx', name: 'xxx', data: 'xxx', list: 'dword' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\xxx\{xxxx\xxx', name: 'xxx', data: 'xxx', list: 'dword' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\xxx', name: 'xxx', data: 'xxx', list: 'dword' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\xxxx', name: 'xxx', data: 'xxx', list: 'dword' }
    register: output
  - debug: var=output

  - name: Remove IIS
    win_feature:
      name: Web-Server
      state: absent

  - name: Set dynamic port range
    win_command: netsh.exe int ipv4 set dynamicport tcp start=xxx num=xxxx
    register: output
  - debug: var=output

  - name: Installing Server Roles and features
    win_feature:
      name: Application-Server, AS-NET-Framework, FS-FileServer, Storage-Services, Remote-Desktop-Services, NFS-Client, Telnet-Client, NET-Framework-Core, Desktop-Experience
      state: present
      restart: False
      include_management_tools: True
    register: output
  - debug: var=output

  - name: Add xxx to PATH
    win_environment:
      state: present
      name: PATH
      value: C:\xxx
      level: machine
    register: output
  - debug: var=output

  - name: registry fix
    win_regedit: path={{ item.path }} name={{ item.name }} data={{ item.data }} type={{ item.list }} 
    with_items:
        - { path: 'HKLM:\system\currentcontrolset\xxxx', name: 'xxxx', data: 'xx', list: 'dword' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\xxxx\{xxx\xxx', name: 'xxx', data: 'xxx', list: 'dword' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\xxx\{xxxx\xxx', name: 'xxx', data: 'xxx', list: 'dword' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\xxx', name: 'xxx', data: 'xxx', list: 'dword' }
        - { path: 'HKLM:\SOFTWARE\Microsoft\xxxx', name: 'xxx', data: 'xxx', list: 'dword' }

  - name: Execute command
    win_command: bcdedit /set {current} nx OptIn

  - name: Pagefile allocation
    win_copy:
      src: files/xxx.reg
      dest: c:\temp\xxx.reg

  - name: Execute the registry file to update pagefile allocation
    win_command: regedit.exe /s c:\temp\xxx.reg

  - name: Set timezone to 'Eastern Standard Time'
    win_timezone:
       timezone: Eastern Standard Time
    register: output
  - debug: var=output

  - name: Copy  Zip to server
    win_copy:
      src: files/xxx.zip
      dest: c:\temp\xxx.zip

  - name: xxx
    win_unzip:
      src: xxx
      dest: xxx
      creates: xxx

  - name: Copy  Zip to server
    win_copy:
      src: files/xxx.zip
      dest: c:\temp\xxx.zip

  - name: TLM Manager 1.0 Installation
    win_unzip: 
      src: xxx
      dest: xxx
      creates: xxx

  - name: Copy links to Allusers profile
    win_command: xcopy xxxx\\xxx.lnk  %ALLUSERSPROFILE%\Desktop\  /Y

  - name: Copy xxx.xml
    win_copy: 
      src: files/xx.xml
      dest: xxxx

  - name: Copy Textpad MSI
    win_copy: 
      src: files/textpad.zip
      dest: c:\temp\

  - name: TextPad Unzip
    win_unzip: 
      src: c:\temp\textpad.zip
      dest: c:\temp

  - name: Textpad MSI Installation
    win_msi:
    #path: X:\Product\ADP\textpad\TextPad5.msi
      path: c:\temp\textpad\TextPad5.msi
      wait: True
      state: present

  - name: Textpad license
    win_command: regedit /s c:\temp\textpad\TextPad5.reg

  - name: Instal Notepad++
    win_chocolatey:
      name: notepadplusplus.install
      version: '7.5'

  - name: Copy JRE Zip to temp
    win_copy:
      src: files/jre-8u40-windows-i586.zip
      dest: c:\temp

  - name: Unzip JRE
    win_unzip:
      src: c:\temp\jre-8u40-windows-i586.zip
      dest: c:\temp\jre

  - name: JRE Installation
    win_command: C:\temp\jre\jre-8u40-windows-i586 /s
    args:
      chdir: C:\temp\jre
    register: output
  - debug: var=output

  - name: Copy Links Zip to temp
    win_copy:
       src: xxx
       dest: xxx

  - name: shortcuts
    win_unzip:
      src: xxx
      dest: xx
```

##### EXPECTED RESULTS
It should complete all the tasks

##### ACTUAL RESULTS
```
TASK [registry fix] *************************************************************************************************
task path: /etc/ansible/pre-serverconfig.yaml:58
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_regedit.ps1
<xxx> ESTABLISH WINRM CONNECTION FOR USER: xxxx on PORT 5986 TO xxxx
EXEC (via pipeline wrapper)
 [WARNING]: FATAL ERROR DURING FILE TRANSFER: Traceback (most recent call last):   File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 267, in _winrm_exec
self._winrm_send_input(self.protocol, self.shell_id, command_id, data, eof=is_last)   File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/winrm.py", line 248, in _winrm_send_input
protocol.send_message(xmltodict.unparse(rq))   File "/usr/lib/python2.7/site-packages/winrm/protocol.py", line 207, in send_message     return self.transport.send_message(message)   File "/usr/lib/python2.7
/site-packages/winrm/transport.py", line 202, in send_message     raise WinRMTransportError('http', error_message) WinRMTransportError: (u'http', u'Bad HTTP response returned from server. Code 500')

fatal: [xxx]: FAILED! => {
    "failed": true,
    "msg": "winrm send_input failed"
```

**Comment by dagwieers** [comment]
My guess is that the features you're installing is causing the WinRM service to be temporarily unavailable (at some later time). So it's probably better to make it perform a reboot as suggested by the **win_feature** module.

Could you perform a **win_reboot** after installing new features ?
Simply add after the **win_feature** task this:
```yaml
  - win_reboot:
    when: output.reboot_required
```

PS We are looking at better ways to handle HTTP 500 error messages in pywinrm.

**Comment by jborean93** [comment]
You are pretty much removing everything from `PATH` with

```
  - name: Add xxx to PATH
    win_environment:
      state: present
      name: PATH
      value: C:\xxx
      level: machine
    register: output
```

This will break a lot of things (including WinRM) as Windows no longer knows where the powershell executable (and pretty much anything else) is so it cannot run. Use the [win_path](http://docs.ansible.com/ansible/latest/win_path_module.html) instead to append entries to the path instead of changing the whole thing.
