### ISSUE TITLE
lineinfile: allow insertafter and insertbefore to be used simultaneously as range

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#30963]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lineinfile
##### ANSIBLE VERSION

```
ansible 2.3.2.0
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

`insertbefore` and `insertafter` are mutually exclusive, so it is impossible to limit match to a specific section of a file.
##### STEPS TO REPRODUCE

Try to make a range for line insertion by specifying both `insertbefore` and `insertafter`

```yaml
lineinfile:
  dest: /etc/login.conf
  line: "\t:charset=UTF-8:\\"
  insertafter: '^default:\\'
  insertbefore: '^(?!\t)'
```
The problem is that this line may be present in multiple sections of the file.

##### EXPECTED RESULTS

Line would be searched and placed between two regex matches.
##### ACTUAL RESULTS

Module fails with mutually exclusive parameters.
If `insertbefore` is omitted, another matched line is found later in the file in a completely unrelated section.

```

```
