### ISSUE TITLE
nxos_config should support config replace

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#30979]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
nxos_config
http://docs.ansible.com/ansible/latest/nxos_config_module.html

This module only has line and block, but we should have the ability to replace the entire config with a flat-file.

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The Nexus 9000 series has the config replace option:
```
n9k# config ?
  <CR>
  maintenance  Maintenance profile mode
  profile      Configure profile
  replace      Perform a replace of the running-config
```

##### STEPS TO REPRODUCE
Use a playbook like this->

```yaml
---
- name: configure top level configuration and save it
  nxos_config:
    lines: hostname {{ inventory_hostname }}
    save_when: modified
    replace: config
```
make sure you don't delete Ansible's access to the box (SSH interface, or disable ssh, etc)

##### EXPECTED RESULTS
playbook executes, only config on the box is what you put there (no merge, full replace)

##### ACTUAL RESULTS
N/A, feature request
