### ISSUE TITLE
eos_config: CLI command x of y failed: invalid command

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#30981]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0.0
  config file = 
  configured module search path = [u'/Users/lynchg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lynchg/.virtualenvs/a2x/lib/python2.7/site-packages/ansible
  executable location = /Users/lynchg/.virtualenvs/a2x/bin/ansible-playbook
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### OS / ENVIRONMENT
Mac OSX

##### SUMMARY
When performing a complete config replace using eos_config, and a src file, we are seeing a generic "invalid command" error at a high number in the list of the commands

##### STEPS TO REPRODUCE
Use eos 4.17.5M
If access to a physical switch, use model 7050QX with QSFP and SFP enabled
Build an entire config of more than 800 lines, including
- 10 or more port channels
- configuration for every interface
- 5-10 vlans
- 5-10 vlan interfaces
Use eos_config to apply it, e.g.

```
- name: configure the switch
  eos_config:
    src: "{{ eos_dest_dir }}/startup-config"
    replace: "{{ eos_config_replace | default('config') }}"
    save_when: 'modified'
    provider: "{{ eos_connection }}"
```

##### EXPECTED RESULTS
No error

##### ACTUAL RESULTS
Inconsistent depending on switch and generated config, but generally something like

```
fatal: [switchname]: FAILED! => {"changed": false, "code": 1002, "failed": true, "msg": "CLI command 769 of 884 'ip virtual-router mac-address 00:1c:73:00:00:99' failed: invalid command"}
```

We seem to see the error up around the 800 CLI mark.

**Comment by halberom** [comment]
Discussed this with @privateip in the `#ansible-network` channel

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn @gundalow @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by halberom** [comment]
connection details are
```
eos_connection:
  host: "{{ ansible_host }}"
  username: eapi
  password: REDACTED
  transport: eapi
  use_ssl: True
  validate_certs: False
  timeout: 300
```
