### ISSUE TITLE
Typo in vmware_guest.py size_mb disk attribute

### ISSUE THREAD

**Issue by bbomgardner** [ansible/ansible#30983]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /vagrant/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

ANSIBLE_FORCE_COLOR(/vagrant/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/vagrant/ansible.cfg) = %(directory)s/%%h-%%r
ANSIBLE_SSH_PIPELINING(/vagrant/ansible.cfg) = True
DEFAULT_HOST_LIST(/vagrant/ansible.cfg) = [u'/vagrant/environments/development']
DEFAULT_ROLES_PATH(/vagrant/ansible.cfg) = [u'/vagrant/roles/internal', u'/vagrant/roles/community']
DEFAULT_STDOUT_CALLBACK(/vagrant/ansible.cfg) = debug
HOST_KEY_CHECKING(/vagrant/ansible.cfg) = False
RETRY_FILES_ENABLED(/vagrant/ansible.cfg) = False

##### OS / ENVIRONMENT

N/A

##### SUMMARY

[Typo; space in string on line 928](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py#L928)

##### STEPS TO REPRODUCE

```yaml
    - name: Create vm guest from template
      vmware_guest:
        hostname: "{{ vcenter_fqdn }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter:  "{{ datacenter }}"
        cluster: "{{ cluster }}"
        resource_pool: "{{ resource_pool }}"
        validate_certs: False
        name: "{{ guest_name }}"
        state: poweredon
        template: "{{ template }}"
        folder: "{{ folder }}"
        wait_for_ip_address: yes
        disk:
        - size_mb: 500
          datastore: datastore_01
        - size_gb: 16
          datastore: datastore_01
        annotation: |
          VM guest created by ansible on {{ ansible_date_time.iso8601 }} from {{ template }}
      register: new_guest
```

##### EXPECTED RESULTS

```size_mb``` to be parsed correctly

##### ACTUAL RESULTS

```
TASK [Create vm guest from template] ****************************************************************************************************************************************************************************


fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true
}

MSG:

mb is not a supported unit for disk size. Supported units are kb, mb, gb or tb
```
