### ISSUE TITLE
nxos_config: intended_config diff option seems backwards

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#30992]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_config
http://docs.ansible.com/ansible/latest/nxos_config_module.html

##### ANSIBLE VERSION

```
[root@localhost ~]# ansible --version
ansible 2.5.0
  config file = /root/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/napalm_ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
```
[root@localhost ~]# ansible-config dump --only-changed
DEFAULT_GATHERING(/root/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/root/ansible.cfg) = [u'/root/hosts']
DEFAULT_MODULE_PATH(/root/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/napalm_ansible']
DEPRECATION_WARNINGS(/root/ansible.cfg) = False
HOST_KEY_CHECKING(/root/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/root/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
[root@localhost ~]# cat /etc/*release
CentOS Linux release 7.3.1611 (Core)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core)
CentOS Linux release 7.3.1611 (Core)
```

##### SUMMARY
I have two configs.  There is one local (nxos_base.cfg) and one already running on the N9K (Cisco Nexus box).  The only difference is that the nxos_base.cfg (local file) has an IP address on interface Ethernet1/1

Literally this->
```
 interface Ethernet1/1
  no switchport
  ip address 172.16.10.10/24
```

The problem is the diff I perform seems backwards.  It shows the no switchport and ip address in red with - (minus) signs, as in "if I decided to push this config, it would remove these lines".  In reality if I push this same file with a src= command, it actually appends (adds).  I would think these should be green. 

Here is the picture:
![terminal output](https://i.imgur.com/YjCYxnq.png)

Here is the diff
```
TASK [diff the running-config against a provided config] *************************************************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -36,8 +36,6 @@
   name HADOOP
 vrf context management
 interface Ethernet1/1
-  no switchport
-  ip address 172.16.10.10/24
 interface Ethernet1/2
 interface Ethernet1/3
 interface Ethernet1/4

changed: [n9k]
```

##### STEPS TO REPRODUCE
```yaml
---
- hosts: cisco
  connection: local
  tasks:
    - name: diff the running-config against a provided config
      nxos_config:
        diff_against: intended
        intended_config: "{{ lookup('file', 'nxos_base.cfg') }}"
        provider: "{{login_info}}"

    - name: take user input- Commit changes?  Yes or  No ?
      pause:
        prompt:  Type "y" for yes or "n" for no
      register: user_result

    - name: checking string syntax to becareful
      debug:
        var: user_result
      failed_when: user_result["user_input"] != "n" and user_result["user_input"] != "y"

    - name: commit config when user_result == yes
      nxos_config:
        src: nxos_base.cfg
        save_when: modified
        provider: "{{login_info}}"
      when: user_result["user_input"] == "y"
```

##### EXPECTED RESULTS
I wanted this to happen->
```
TASK [diff the running-config against a provided config] *************************************************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -36,8 +36,6 @@
   name HADOOP
 vrf context management
 interface Ethernet1/1
-  no switchport
-  ip address 172.16.10.10/24
 interface Ethernet1/2
 interface Ethernet1/3
 interface Ethernet1/4

changed: [n9k]
```
##### ACTUAL RESULTS
This is what happened:
```
TASK [diff the running-config against a provided config] *************************************************************************************************************************************************************************************************************************************************************
--- before
+++ after
@@ -36,8 +36,6 @@
   name HADOOP
 vrf context management
 interface Ethernet1/1
+  no switchport
+  ip address 172.16.10.10/24
 interface Ethernet1/2
 interface Ethernet1/3
 interface Ethernet1/4

changed: [n9k]
```

Both prompt_example.yml and nxos_base.cfg are provided in this Github repo:
https://github.com/network-automation/ansible-napalm-samples
