### ISSUE TITLE
nxos_snmp_host: several properties not idempotent for n1 images

### ISSUE THREAD

**Issue by rahushen** [ansible/ansible#30997]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nxos_snmp_host

##### ANSIBLE VERSION

```
ansible 2.4.0.0 (detached HEAD d14467b029) last updated 2017/09/27 14:54:45 (GMT -400)
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/agents-ci/ansible/lib/ansible
  executable location = /root/agents-ci/ansible/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Ubuntu 14.04
##### SUMMARY

`show snmp host | json` output varies for this image.

##### STEPS TO REPRODUCE

```yaml
  - name: Configure snmp host
    nxos_snmp_host: &config
      snmp_host: 3.3.3.3
      community: TESTING
      version: v3
      v3: noauth
      #udp: 55
      snmp_type: inform
      vrf: management
      vrf_filter: management
      src_intf: "{{ intname|default(omit) }}"
      state: present
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: Idempotence Check
    nxos_snmp_host: *config
    register: result

  - assert: &false
      that:
        - "result.changed == false"
```

##### EXPECTED RESULTS

Expected play to be idempotent

##### ACTUAL RESULTS

```
TASK [nxos_snmp_host : Idempotence Check] *****************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_snmp_host/tests/common/sanity.yaml:46
<n5k-xxx.example.com> connection transport is cli
<n5k-xxx.example.com> using connection plugin network_cli
<n5k-xxx.example.com> socket_path: /root/.ansible/pc/1b4e3e6315
Using module file /root/agents-ci/ansible/lib/ansible/modules/network/nxos/nxos_snmp_host.py
<n5k-xxx.example.com> ESTABLISH LOCAL CONNECTION FOR USER: root
<n5k-xxx.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n5k-xxx.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1506022469.74-261728230420672 `" && echo ansible-tmp-1506022469.74-261728230420672="` echo /root/.ansible/tmp/ansible-tmp-1506022469.74-261728230420672 `" ) && sleep 0'
<n5k-xxx.example.com> PUT /tmp/tmpOMKDDk TO /root/.ansible/tmp/ansible-tmp-1506022469.74-261728230420672/nxos_snmp_host.py
<n5k-xxx.example.com> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1506022469.74-261728230420672/ /root/.ansible/tmp/ansible-tmp-1506022469.74-261728230420672/nxos_snmp_host.py && sleep 0'
<n5k-xxx.example.com> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1506022469.74-261728230420672/nxos_snmp_host.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1506022469.74-261728230420672/" > /dev/null 2>&1 && sleep 0'
changed: [n5k-xxx.example.com] => {
    "changed": true, 
    "commands": [
        "snmp-server host 3.3.3.3 inform version 3 noauth TESTING",  
        "snmp-server host 3.3.3.3 filter-vrf management", 
        "snmp-server host 3.3.3.3 source-interface Ethernet1/2", 
        "snmp-server host 3.3.3.3 use-vrf management"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "community": "TESTING", 
            "host": "n5k-xxx.example.com", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": null, 
            "provider": {
                "host": "n5k-xxx.example.com",               
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": null, 
                "ssh_keyfile": null, 
                "timeout": null, 
                "transport": "cli", 
                "use_ssl": null, 
                "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "validate_certs": null
            }, 
            "snmp_host": "3.3.3.3", 
            "snmp_type": "inform", 
            "src_intf": "Ethernet1/2", 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": null,  
            "transport": "cli", 
            "udp": null, 
            "use_ssl": null,  
            "username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "v3": "noauth", 
            "validate_certs": null, 
            "version": "v3",  
            "vrf": "management", 
            "vrf_filter": "management"
        }
    }
}
 
TASK [nxos_snmp_host : assert] ****************************************************************************************************************************
task path: /root/agents-ci/ansible/test/integration/targets/nxos_snmp_host/tests/common/sanity.yaml:50
FAILED! => {
    "assertion": "result.changed == false",    
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}
```
