### ISSUE TITLE
Add suport for yaml configuration

### ISSUE THREAD

**Issue by bcoca** [ansible/ansible#31016]
Add YAML formatted configuration file as alternative to current ini

this will allow for hierarchical config entries i.e
```yaml
 cli:
    timeout: 10
    pull: 
      timeout: 23
```
and easily merge-able configs as well as adding a playbook contextual `meta/` and expanding on the existing one in roles

##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

config
##### ANSIBLE VERSION

```
2.5
```
