### ISSUE TITLE
Executing include tasks that should be skipped when using the --tags CLI flag

### ISSUE THREAD

**Issue by Darrel12** [ansible/ansible#31012]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include, or tags, or maybe it's a problem with the core functionality

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

```
log_path = /var/log/ansible.log

retry_files_enabled = False

connect_timeout = 30

connect_retries = 30

connect_interval = 1
```

##### OS / ENVIRONMENT
RHEL6

##### SUMMARY

When I try to run this playbook with the `--tags` flag, it still executes 'include' tasks that do not have the specified tags. As it should, it skips tasks in the play before and after the include... but not the include itself. I have tested this playbook both with the task in a loop, and with no loop – I get the same results.

Something that may help reveal why this happens: Using the `--skip-tags` directive with the tags associated with the includes – `sql` in this instance – in conjunction with `--tags` will result in the desired behavior, so it's likely that the `--tags` directive is missing something, or the dynamicity of the include may be causing the issue. However, using `static: yes` still doesn't solve the problem, so that's probably not it.

##### STEPS TO REPRODUCE

I created the following directory for this example: `/home/dholt2/testing/Oracle`
Inside of the directory are the files `a.sql`, `b.sql`, `c.sql`, and `rollback.sql`. There are also the actual files being included (`testDeploySql.yml` and `testRollbackSql.yml`) but they shouldn't be executed anyways.

The playbook:
```yaml
---
###   This is the Ansible Playbook to automatically deploy and restart GMS -- Variables are in /etc/ansible/hosts and injected via HTTP-POST/Publish-Over-SSH from GSN -> Jenkins -> Ansible   ###

#:PLAY 2 - PULL REPO (LOCALLY)
- name: Pull Repo to Localhost
  hosts: localhost
  any_errors_fatal: true
  tags:
    - pullRepo
    - main
  gather_facts: no
  tasks:

    # Save the repository to the control machine (this machine) for distribution
    - name: Pulling Git Repo for GMS...
      git: 
        repo: 'https://github.com/ansible/ansible.git'
        dest: '/home/dholt2/ansi'
        accept_hostkey: yes
        force: yes
        recursive: no

# Execute the sql files in the 'Oracle' directory after
## checking if the directory exists
#:PLAY 4 - TEST AND EXECUTE SQL (LOCALLY/LOCALLY)
- name: Test & Execute SQL Scripts
  hosts: localhost
  any_errors_fatal: true
  tags:
    - sql
  gather_facts: no
  tasks:

    # Check if the 'Oracle' directory exists. Save the
    ## output to deploy 'Oracle/*' if it does exist.
    - name: Check for presence of the Oracle directory
      stat:
        path: '/home/dholt2/testing/Oracle'
      register: st3


    # Get a list of all sql scripts (using 'ls -v') to run ONLY if the 'Oracle'
    ## directory exists; exclude the rollback script; -v ensures natural ordering of the scripts
    - name: Capture All Scripts To Run
      shell: 'ls -v home/dholt2/testing/Oracle -I rollback.sql'
      register: f1
      when: st3.stat.isdir is defined

- name: new part
  hosts: localhost
  any_errors_fatal: true
  tags:
    - sql
  gather_facts: no
  tasks:
  
    # Test that the deployment scripts run without error
    - name: Testing SQL Deployment Scripts...
      include: testDeploySql.yml
      any_errors_fatal: true
      register: sqlDepl
      when: st3.stat.isdir is defined
```

the command:
```ansible-playbook deploy2.yml --tags "pullRepo" -vvv```

##### EXPECTED RESULTS
My best guess at what it would look like:
```
PLAYBOOK: deploy2.yml *********************************************************************************************************************************************************************************************************************************************************
3 plays in deploy2.yml

PLAY [Pull Repo to Localhost] *************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Pulling Git Repo for GMS...] ********************************************************************************************************************************************************************************************************************************************
task path: /home/dholt2/test/deploy2.yml:15
Using module file /usr/lib/python2.6/site-packages/ansible/modules/source_control/git.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dholt2
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449 `" && echo ansible-tmp-1506551897.18-36707926445449="` echo /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpVR7YDS TO /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/git.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/ /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/git.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2.6 /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/git.py; rm -rf "/home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "after": "0dd3a61a75c4ca4fc489e56299da2045d3c5722a",
    "before": "0dd3a61a75c4ca4fc489e56299da2045d3c5722a",
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_hostkey": true,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/home/dholt2/ansi",
            "executable": null,
            "force": true,
            "key_file": null,
            "recursive": false,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "https://github.com/ansible/ansible.git",
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        }
    },
    "remote_url_changed": false
}
META: ran handlers
META: ran handlers

PLAY [Test & Execute SQL Scripts] *********************************************************************************************************************************************************************************************************************************************
META: ran handlers
META: ran handlers
META: ran handlers

PLAY [new part] ***************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

```

##### ACTUAL RESULTS

```
PLAYBOOK: deploy2.yml *********************************************************************************************************************************************************************************************************************************************************
3 plays in deploy2.yml

PLAY [Pull Repo to Localhost] *************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Pulling Git Repo for GMS...] ********************************************************************************************************************************************************************************************************************************************
task path: /home/dholt2/test/deploy2.yml:15
Using module file /usr/lib/python2.6/site-packages/ansible/modules/source_control/git.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: dholt2
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449 `" && echo ansible-tmp-1506551897.18-36707926445449="` echo /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpVR7YDS TO /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/git.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/ /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/git.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2.6 /home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/git.py; rm -rf "/home/dholt2/.ansible/tmp/ansible-tmp-1506551897.18-36707926445449/" > /dev/null 2>&1 && sleep 0'
ok: [localhost] => {
    "after": "0dd3a61a75c4ca4fc489e56299da2045d3c5722a",
    "before": "0dd3a61a75c4ca4fc489e56299da2045d3c5722a",
    "changed": false,
    "invocation": {
        "module_args": {
            "accept_hostkey": true,
            "bare": false,
            "clone": true,
            "depth": null,
            "dest": "/home/dholt2/ansi",
            "executable": null,
            "force": true,
            "key_file": null,
            "recursive": false,
            "reference": null,
            "refspec": null,
            "remote": "origin",
            "repo": "https://github.com/ansible/ansible.git",
            "ssh_opts": null,
            "track_submodules": false,
            "umask": null,
            "update": true,
            "verify_commit": false,
            "version": "HEAD"
        }
    },
    "remote_url_changed": false
}
META: ran handlers
META: ran handlers

PLAY [Test & Execute SQL Scripts] *********************************************************************************************************************************************************************************************************************************************
META: ran handlers
META: ran handlers
META: ran handlers

PLAY [new part] ***************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [include] ****************************************************************************************************************************************************************************************************************************************************************
task path: /home/dholt2/test/testDeploySql.yml:11
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "'sh1' is undefined"
}

NO MORE HOSTS LEFT ************************************************************************************************************************************************************************************************************************************************************

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

```
