### ISSUE TITLE
service: Please add option to use rc.conf.d on FreeBSD

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#31034]
##### ISSUE TYPE

 - Feature Idea
##### COMPONENT NAME

service
##### ANSIBLE VERSION

N/A
##### OS / ENVIRONMENT

FreeBSD client
##### SUMMARY

Please add an option to service module to use rc.conf.d/service_name  instead of rc.conf file on FreeBSD to control service enabled/disabled state.
For example this service statement:
```yaml
service:
  name: snmpd
  enable: yes
  bsd_use_rcsubdir: yes
```
would ensure that /etc/rc.conf.d/snmpd exists and has a line in it:
```
snmpd_enable="YES"
```
And also remove `smnpd_enable` parameter from rc.conf for consistency.
