### ISSUE TITLE
problem with conditionals and matching a variable in dictionary

### ISSUE THREAD

**Issue by ioliinykova** [ansible/ansible#31043]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`when` conditional

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

Standard configuration

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

Problem with `when` conditionals when trying to match a variable that makes part of a dictionary. 

Worked perfectly until Ansible version update. 
Since in new version there are the following warnings: `[WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}`, I tried to fix the syntax, but the condition is no longer matched.

Normally it should not have worked even earlier because it must match a value in the following list:
`[{u'name': u'user1'}, {u'name': u'user2'}, {u'name': u'user3'},…]`, so it should have returned an error message type mismatch.

For the moment I cannot find a way to match this variable at all.

##### STEPS TO REPRODUCE

The following play must be executed with `ansible-playbook play.yml -e username=user1`

```yaml
- hosts: testvm

  vars:

    system_users:
      - name : user1
      - name : user2
      - name : user3

  tasks:

  - name: Create new user
    user:
      name: "{{ username }}"
      shell: "/bin/bash"
      state: present
      groups: wheel
    when: '"{{ username }}" in "{{ system_users }}"'
```

This play must create a new user only if this user is listed in system_users. 

When I try to change the syntax as indicated below, this task is skipped:

```yaml
  - name: Create new user
    user:
      name: "{{ username }}"
      shell: "/bin/bash"
      state: present
      groups: wheel
    when: username in system_users
```

##### EXPECTED RESULTS

```
# ansible-playbook play.yml -e username=user1

PLAY [testvm] ******************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************
ok: [testvm]

TASK [testvm] ***********************************************************************************************************************************************************************************************************************

changed: [testvm]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
testvm       : ok=2    changed=1    unreachable=0    failed=0   

```

##### ACTUAL RESULTS

```
TASK [Create new user] ***********************************************************************************************************************************************************************************************************************
task path: /etc/ansible/playbooks/play.yml:15
skipping: [testvm] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
META: ran handlers
META: ran handlers

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
29254.monit.sewan.fr       : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, this has nothing to do with  `{{}}` .. you are using `in`  against a list of dictionaries ... it will never match. You might want to try the following:

```yaml
- name: Create new user
    user:
      name: "{{ username }}"
      shell: "/bin/bash"
      state: present
      groups: wheel
    when: username in item.value
    with_dict: "{{ system_users }}"
```
You can alternatively avoid the loop by using `select` or `selectattr` filters.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
