### ISSUE TITLE
aws_s3_bucket_facts returning xml parsing issue

### ISSUE THREAD

**Issue by amsinha2** [ansible/ansible#31053]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

aws_s3_bucket_facts
##### ANSIBLE VERSION

```
ansible 2.4.0.0
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/opt/internal/networks/ansible_dev/ansible.cfg) = [u'/opt/internal/networks/ansible_dev/inventory/Dev']
DEFAULT_PRIVATE_KEY_FILE(/opt/internal/networks/ansible_dev/ansible.cfg) = /home/netdev/.ssh/id_rsa
DEFAULT_ROLES_PATH(/opt/internal/networks/ansible_dev/ansible.cfg) = [u'/opt/internal/networks/ansible_dev/roles']
HOST_KEY_CHECKING(/opt/internal/networks/ansible_dev/ansible.cfg) = False

##### OS / ENVIRONMENT

RHEL 7
##### SUMMARY

aws_s3_bucket_facts  return xml parsing error unable to retrieve list of s3 containers with this call

##### STEPS TO REPRODUCE

I am able to run the following module with the same AWS connection Params 
The IAM used for access has Admin credentials, how ever the facts module does not run and generates a XML parsing error

```yaml
    tasks:
     - aws_s3_bucket_facts:
          ec2_url: **removed**
          aws_access_key: **removed**
          aws_secret_key: **removed**
          #validate_certs: no
          region: **removed**
       register: s3_buckets
      
     - debug: var=s3_buckets

```

##### EXPECTED RESULTS

List of s3 buckets in VPC
##### ACTUAL RESULTS

botocore.parsers.ResponseParserError: Unable to parse response (not well-formed (invalid token): line 19, column 23), invalid XML received:

```

```
