### ISSUE TITLE
mailto option for cron

### ISSUE THREAD

**Issue by bryanlarsen** [ansible/ansible#3106]
the chef crontab resource allows the setting of the mailto variable, which we found useful.

http://docs.opscode.com/resource_cron.html

It produces output in the form:

```
# Chef Name: backup
MAILTO=web-errors@exocortex.com
* 3 * * *  /srv/ess/bin/backup.sh 
```

I took a quick look at implementing it myself, but the current code assumes that a crontab entry is a single line.

**Comment by mpdehaan** [comment]
Yeah, patches for this would be accepted, even if requires upgrading the way the cron module works a bit.

It is however not something we're going to work on immediately.

I would possibly suggest placing the cron configuration using the template module for the interim (which is how I usually do it anyway).

/etc/cron.d is great for this purpose.

**Comment by piotrze** [comment]
@bryanlarsen You can handle MAILTO with this entry:

```
cron: name="MAILTO section" minute="MAILTO=tech@example.com" hour= day= month= weekday= job= 
```

**Comment by SpenserJ** [comment]
@piotrze Doesn't look like that works in the latest version, at least on Ubuntu 12.04.

**Comment by jacobweber** [comment]
This works for me, on RHEL6.4. But it can add the entry to the end of the file, which means it won't apply to any of the other entries. Is there a way to force it to be added to the top?

**Comment by manuelmeurer** [comment]
This worked for me with Ansible 1.6.2 and Ubuntu 14.04:

``` yaml
- name: set MAILTO in crontab
  cron:
    name: MAILTO
    minute: MAILTO=my@email.com
    hour: ""
    day: ""
    month: ""
    weekday: ""
    job: ""
```
