### ISSUE TITLE
gce doesn't work with libcloud 2.0 (or fails badly) - AttributeError: 'GCEFailedNode' object has no attribute 'extra'

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#31063]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gce

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

nothing special

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY
```
  - name: Launch GCP instances
    gce:
      name: "foo-wheeee"
      num_instances: "{{ gcp_count }}"
      state: present
      zone: us-west1-a
      image_family: centos-7
      machine_type: n1-standard-1
      tags:
      - "foo-wheeee"
    register: gce
```
yields:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'GCEFailedNode' object has no attribute 'extra'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 778, in <module>\n main()\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 738, in main\n module, gce, inames, number, lc_zone)\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 586, in create_instances\n d = get_instance_info(inst)\n File \"/tmp/ansible_jYxrOm/ansible_module_gce.py\", line 356, in get_instance_info\n if 'metadata' in inst.extra and 'items' in inst.extra['metadata']:\nAttributeError: 'GCEFailedNode' object has no attribute 'extra'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

##### STEPS TO REPRODUCE

See above

##### EXPECTED RESULTS

No traceback - either success, or an actual error message if I screwed something up.

**Comment by ansibot** [comment]
cc @erjohnso @supertom
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by erjohnso** [comment]
Sorry for the late reply @wenottingham 

I received a different error trying to reproduce.  The error I saw, which is valid, is that `image_family` is not supported in the `gce` module.  I changed your snippet to `image` instead and I was able to create the instances correctly.  Note that `image_family` *is* supported, but only in the `gce_instance_template` module.

```
erjohnso@ansible$ cat test-issue31063.yml; ansible-playbook -v test-issue31063.yml
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: instance
      gce:
        project_id: graphite-demos
        credentials_file: /home/erjohnso/ansible-demo.json
        name: "foo-wheeee"
        num_instances: 2
        state: present
        zone: us-central1-a
        image: centos-7
        machine_type: n1-standard-1
        tags:
        - "foo-wheeee"
      register: gce

Using /home/erjohnso/.ansible.cfg as config file

PLAY [Create instance(s)] ********************************************************************************************************************************************

TASK [instance] ******************************************************************************************************************************************************
changed: [localhost] => {"changed": true, "failed": false, "instance_data": [{"disks": ["foo-wheeee-000"], "image": "centos-7-v20171003", "machine_type": "n1-standard-1", "metadata": {}, "name": "foo-wheeee-000", "network": "default", "private_ip": "10.240.0.3", "public_ip": "35.194.2.5", "status": "RUNNING", "subnetwork": null, "tags": ["foo-wheeee"], "zone": "us-central1-a"}, {"disks": ["foo-wheeee-001"], "image": "centos-7-v20171003", "machine_type": "n1-standard-1", "metadata": {}, "name": "foo-wheeee-001", "network": "default", "private_ip": "10.240.0.4", "public_ip": "35.184.87.167", "status": "RUNNING", "subnetwork": null, "tags": ["foo-wheeee"], "zone": "us-central1-a"}], "name": "foo-wheeee", "state": "present", "zone": "us-central1-a"}                                                                           

PLAY RECAP ***********************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

I'm also running 2.4,

```
ansible 2.4.0 (devel b818e986b6) last updated 2017/08/17 13:55:22 (GMT +000)
  config file = /home/erjohnso/.ansible.cfg
  configured module search path = [u'/home/erjohnso/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/erjohnso/ansible/lib/ansible
  executable location = /home/erjohnso/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```
