### ISSUE TITLE
Ansible uses the same ssh tunnel for all hosts in group

### ISSUE THREAD

**Issue by Zapeth** [ansible/ansible#31068]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
winrm

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = ~/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug 4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)
```

##### OS / ENVIRONMENT

**managing OS:** CentOS 7
**target OS's:** Windows 8 (in a subnet managed by Linux servers)

##### SUMMARY

In our network we have Windows 8 clients that are in subnets managed by Linux servers and I want to use Ansible to manage those clients, however I was unable to find a clear/"official" solution for this problem.

The most promising one seems to involve local forwarding as described [here](https://stackoverflow.com/questions/34334209/how-to-make-ansible-connect-to-windows-host-behind-linux-jump-server/34721096#34721096), which I used as a template to write my own playbook (provided below).

Most of it seems to work as expected as well, the tunnels get created by ssh with the proper host/port/credential arguments, validation works and no errors are returned from ssh.
However when the actual Windows tasks get executed, it seems that Ansible always uses the same tunnel for the tasks (for every host).
Or in other words, the test task that returns the output of `ipconfig` is the same for all hosts from the `[win_hosts]` group (meaning the task ran on the same host every single time).

```yaml
---
- name: Tunneled configuration of Windows host in a subnet
  hosts: win_hosts
  vars:
    - winrm_port: 5986
    - jump_host: rhel-jump

  connection: local #This is the trick to connect to localhost not actual host
  gather_facts: no
  tasks:
# set the task's host to local and put the actual host in a separate variable (can't be done in a single task?)
    - name: store hosts var
      set_fact:
        actual_host: "{{ ansible_host }}"

    - name: change hosts var to local
      set_fact:
        ansible_host: localhost

    - name: set local port # needs to be unique for each connection?
      set_fact:
        local_port: "{{ winrm_port + ansible_play_hosts.index(inventory_hostname) | int }}"

    - name: setup ssh tunnel
      local_action: command ssh -Nf -o ControlPersist=yes -o ControlMaster=auto -o ControlPath="~/.ssh/mux2win-{{ actual_host }}" -o StrictHostKeyChecking=no -o PasswordAuthentication=no root@{{ jump_host }}  -L {{ local_port }}:{{ actual_host }}:{{ winrm_port }}
      changed_when: False
      register: result

    - debug:
        msg: "stdout: {{ result.stdout }}\n stderr: {{ result.stderr }}\n rc: {{ result.rc }}"

    - name: verify tunnel connection
      local_action: command ssh -O check -S "~/.ssh/mux2win-{{ actual_host }}" root@{{ jump_host }}
      changed_when: False
      register: result
    
    - debug:
        msg: "stdout: {{ result.stdout }}\n stderr: {{ result.stderr }}\n rc: {{ result.rc }}"

# ------- actual windows tasks ------------
    - name: exec ipconfig on targets
      win_shell: ipconfig
      args:
        executable: cmd
      register: result

    - debug:
        msg: "{{ result.stdout }}"
# ------- end of actual windows tasks ------------

    - name: close tunnel
      local_action: command ssh -O exit -S "~/.ssh/mux2win-{{ actual_host }}" root@{{ jump_host }}
      changed_when: False
      register: result

    - debug:
        msg: "stdout: {{ result.stdout }}\n stderr: {{ result.stderr }}\n rc: {{ result.rc }}"
```

##### EXPECTED RESULTS
The tasks for every host should all use their own tunnel (`~/.ssh/mux2win-{{ actual_host }}`), which would result in a varying output from `ipconfig`.

##### ACTUAL RESULTS
The tasks for every host all seem to use the same tunnel, resulting in the same output from `ipconfig`.

I currently don't have access to the host where Ansible is executed from so I can't provide a verbose log now, but if required I can add one later.

Also I don't really need to do it exactly like this, so if there is an easier or more proper way to do this feel free to point me to that instead :)
