### ISSUE TITLE
include_role silently ignores vars

### ISSUE THREAD

**Issue by matt3o** [ansible/ansible#31089]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module: include_role

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, May  1 2017, 09:49:44) [GCC 6.3.0 20170406]

```

##### CONFIGURATION
none

##### OS / ENVIRONMENT
N/A

##### SUMMARY

include_role silently ignores vars defined inside the configuration. See the example below. Very hard to debug as everything seems to work. 

##### STEPS TO REPRODUCE
Below is example code. The first version is how it should look like - the second is what I tried. After 
lots of time spent debugging I found out that include_role does not have a vars parameter but that it had to be defined top level on the task. 

What I did:
```yaml
---
- hosts: localhost
  tasks:
    - name: Create a shell alias
      include_role:
        name: igor_mukhin.bash_aliases
        vars:
          shell_aliases:
            - { alias: 'ttt', command: 'test test test' }
```
How it should look like (notice the differently intended vars):
```yaml
---
- hosts: localhost
  tasks:
    - name: Create a shell alias
      include_role:
        name: igor_mukhin.bash_aliases
      vars:
        shell_aliases:
          - { alias: 'ttt', command: 'test test test' }

```

##### EXPECTED RESULTS
Throw an error as include_role does not a vars parameter. Instead the role does not work as expected becaue the params are not passed to the role. 

##### ACTUAL RESULTS
In my case the role skips the task assuming there is nothing to be done. 

```
PLAY [localhost] ***************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [igor_mukhin.bash_aliases : Bash aliases | Add aliases] *******************************************************************************************************************************************************************
skipping: [localhost] => (item=bash_aliases) 

TASK [igor_mukhin.bash_aliases : Bash aliases | Add extra] *********************************************************************************************************************************************************************
skipping: [localhost] => (item=bash_aliases_extra) 

PLAY RECAP *********************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

```
