### ISSUE TITLE
Bug: Pipelining not working || resulting times between pipelining=True/False are the same

### ISSUE THREAD

**Issue by ralphie02** [ansible/ansible#31091]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pipelining

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /home/my_user/.ansible.cfg
  configured module search path = [u'/home/my_user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/home/my_user/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/my_user/.ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s
ANSIBLE_SSH_CONTROL_PATH(/home/my_user/.ansible.cfg) = /tmp/ansible-ssh-%%h:%%p-%%r
ANSIBLE_SSH_PIPELINING(/home/my_user/.ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/my_user/.ansible.cfg) = ['profile_tasks', 'log_plays_capture', 'actionable', 'skippy', 'task_timer', 'version_recorder']
DEFAULT_HASH_BEHAVIOUR(/home/my_user/.ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/my_user/.ansible.cfg) = [u'/home/my_user/ansible/inventories/stg/hosts']
DEFAULT_REMOTE_USER(/home/my_user/.ansible.cfg) = firstname_lastname
DEFAULT_ROLES_PATH(/home/my_user/.ansible.cfg) = [u'/home/my_user/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/my_user/.ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/home/my_user/.ansible.cfg) = /home/my_user/Dropbox/cb-ansible-secret-key
RETRY_FILES_ENABLED(/home/my_user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
My OS:
Ubuntu 16.04.3 LTS (Xenial Xerus)

Host:
Devuan GNU/Linux 1 (jessie)

##### SUMMARY
I am trying to run my play with pipelining=true but it doesnt seem to be working.

(Test Case 1)
I read somewhere that when pipelining is true, there shouldn't be multiple `SSH: EXEC ssh` connections as mentioned here: https://stackoverflow.com/questions/43438519/check-if-ansible-pipelining-is-enabled-working
But I find multiple ssh connections and I also remember reading somewhere that `PUT`  shouldn't exist in the logs when option -vvv is added (not sure if true)

(Test Case 2)
In addition, I tried `pipelining=False` to test the difference in speed for my playbook, but it doesnt seem to make a difference: ~90s (pipelining=True) vs ~90s(pipelining=False)

##### STEPS TO REPRODUCE
Case 1: 
```
ansible test-server -vvv -m shell -a 'echo ok'
```

Case 2:
```yaml
---
- hosts: test-server
  strategy: free
  gather_facts: no
  become: yes
  become_method: sudo
  roles:
    - frontend

frontend role's only task for now:
- name: Create conf files
  template: src={{item.value.template}} dest=/etc/nginx/sites-available/{{item.key}}.conf
  with_dict: "{{nginx}}"
  when: item.value.active == true
```

##### EXPECTED RESULTS
- Faster execution time when `pipelining=True`
- Only *ONE* `SSH EXEC` without `PUT`

##### ACTUAL RESULTS
- No time difference between `pipelining=True` vs `pipelining=False`
- Multiple `SSH EXEC` per task/loop iteration
- PUT command on log
