### ISSUE TITLE
RFE: flatten/simplify azure fact namespace

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#31105]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine

(probably applies to all azure)

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

nothing of note

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

The Azure fact namespace is needlessly convoluted compared to other fact/return namespaces.

##### STEPS TO REPRODUCE
Take a standard playbook that launches instances and waits for ssh to be available.

EC2 example
```
  - name: Launch AWS instances
    ec2:
      state: present
      count: 3
...
      wait: true
    register: ec2_results

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      state: started
      port: 22
      timeout: 60
    with_items:
      - "{{ ec2_results.instances }}"
```

GCP example:

```
  - name: Launch GCP instances
    gce:
      state: present
      num_instances: 3
...
    register: gce_results

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_ip }}"
      state: started
      port: 22
      timeout: 60
    with_items:
      - "{{ gce_results.instance_data }}"
```

Azure example:

```
  - name: Launch Azure instances
    azure_rm_virtualmachine:
      state: present
...
    with_sequence: count=3
    register: azure_results

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.ansible_facts.azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.publicIPAddress.properties.ipAddress }}"
      state: started
      port: 22
      timeout: 60
    with_items:
      - "{{ azure_results.results }}"
```

The Azure example works... but it's excessively long and prone to error when attempting to write.

##### EXPECTED RESULTS

Azure to be roughly analogous in complexity to other cloud providers.

##### ACTUAL RESULTS

Maximum verbosity of namespace
