### ISSUE TITLE
Pass filenames to `values` option of `helm` module

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#31117]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

[`helm` module](https://docs.ansible.com/ansible/2.4/helm_module.html)

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/jeremie/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Mac OSX El Capitan 10.11.6

##### SUMMARY

`helm install` takes a YAML file as its `--values` argument. From `helm help install`:

```
 -f, --values valueFiles      specify values in a YAML file (can specify multiple) (default [])
```

It would be very useful if that file could be provided as an argument of the `helm` module.
For example, it could help transitioning from `command: helm install --values my-values.yml` to the Ansible module while keeping one's values file separate instead embedded in the tasks.

##### STEPS TO REPRODUCE

Syntax could look as follows. If `values` is a string, treat it as a filename (regular lookup in `files` directory of the role):

```yaml
- helm:
    values: my-values.yml
```

`helm install` also supports multiple files, so that could be:

```yaml
- helm:
    values:
      - my-values1.yml
      - my-values2.yml
```

If a dict is passed, keep the current behavior.

If it is not acceptable to have `values` do both, a separate `value_file(s)` argument would do the trick.

**Comment by ansibot** [comment]
cc @kevensen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @flaper87
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ahmadalli** [comment]
any update on this?

**Comment by xmfreak** [comment]
> any update on this?

It is working. Just started working with this module today. Documentation is not clear, but it works. You should put the values key at the same level as chart key, not inside it. So, as an example:

- name: Install chart
  helm:
    host: localhost
    chart:
      name: chart-name
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
    values:
      value1: "my_value"
      value2: "my other value"
    state: present
    name: chart_name
    namespace: my_namespace

There are a few issues with the module, though. One is addressed in devel branch, I hope it will be shipped in the next release. The other one is that version key is mandatory.

You can easily fix it and use a custom module until the issues are fixed in a future release.

**Comment by xmfreak** [comment]
I started working today with this module and the workaround I found for this is to include the values as a variable in the inventory group_vars to populate the variables in the role where you are using the module. As an example, in group_vars -> all.yml:

```
my_chart_values:
    key1:
        value1: "my_value"
    anotherkey: "my other value"
    key55:
        value: "yet another value"

another_chart_values:
    key2:
        value1: "my_value"
```

Then, from the ansible task:

```
- name: Install chart
  helm:
    host: localhost
    chart:
      name: chart_name
      source:
        type: repo
        location: https://storage.googleapis.com/istio-release/releases/1.2.2/charts/
    values: "{{ my_chart_values }}"
    state: "present"
    name: chart_name
    namespace: my_namespace
```

I guess you can also use include_vars when calling the role with the files you need to use.

**Comment by xmfreak** [comment]
I started working today with this module and the workaround I found for this is to include the values as a variable in the inventory group_vars to populate the variables in the role where you are using the module. As an example, in group_vars -> all.yml:

```
chart_values:
    key1:
        value1: "my_value"
    anotherkey: "my other value"
```

Then, from the ansible task:

```
- name: Install chart
  helm:
    host: localhost
    chart:
      name: chart_name
      source:
        type: repo
        location: https://kubernetes-charts.storage.googleapis.com
    values: "{{ my_chart_values }}"
    state: "present"
    name: chart_name
    namespace: my_namespace
```

I guess you can also use include_vars when calling the role with the files you need to use.
