### ISSUE TITLE
Fetch module does not understand sudo

### ISSUE THREAD

**Issue by rrtj3** [ansible/ansible#3111]
Testing some of the things I do in 1.1 on 1.2 and notice that 'fetch' is failing for me on a playbook where it used to work fine.

``` yaml
- hosts: odb*
  user: username 
  sudo: true
  gather_facts: false
  serial: 20

  tasks:


   - name: Fetch /etc/init.d/dbora
     fetch: src=/etc/init.d/dbora dest=/home/username/fetch/dbora/
```

This is now failing on most hosts whereas it worked fine on all hosts on 1.1. The error I'm getting with -v is:

fatal: [odb27.pvt.hawaii.edu] => failed to transfer file from /etc/init.d/dbora
fatal: [odb39.pvt.hawaii.edu] => failed to transfer file from /etc/init.d/dbora
fatal: [odb41.pvt.hawaii.edu] => failed to transfer file from /etc/init.d/dbora
fatal: [odb42.pvt.hawaii.edu] => failed to transfer file from /etc/init.d/dbora

It seems that fetch is now trying to grab the file before sudoing, or something similar, whereas before this worked fine.
