### ISSUE TITLE
Canary Build Support for CI/CD Pipeline

### ISSUE THREAD

**Issue by winstonsimon** [ansible/ansible#31144]
##### ISSUE TYPE

 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

- Feature

##### ANSIBLE VERSION

```
2.4
```

##### SUMMARY
We use Ansible to host some our products in AWS. With our initial setup, we have dev, stage and production environments.

We use standard asg and elb configuration to host each instances separately based on group_vars. 

```
  - name: "Creating Auto Scaling group"
    ec2_asg:
      region: "{{ region }}"
      name: "{{ group }}-{{ envName }}-asg-{{ subsystem }}-{{ region }}"
      launch_config_name: "{{ lc_result.name }}"
      state: present
      health_check_period: 600
      health_check_type: EC2
      desired_capacity: "{{ desired_capacity }}"
      min_size: "{{ min_size }}"
      max_size: "{{ max_size }}"
      replace_batch_size: "{{ replace_batch_size }}"
      load_balancers: ["{{ envName }}-elb-{{ subsystem }}"]
      vpc_zone_identifier: "{{vpc_facts.subnets | map(attribute='id') | list}}"
      replace_all_instances: yes
      wait_for_instances: yes
      wait_timeout: 600
      tags:
        - Name: "{{ envName }}-asg-{{ subsystem }}-instance"
        - Environment: "{{ envName }}"
          propagate_at_launch: yes
    register: asg_results
  ```

  ```
  - name: "Creating Elastic Load Balancer {{ envName }}-elb-{{ subsystem }} for {{ subsystem }} servers"
    ec2_elb_lb:
      region: "{{ region }}"
      name: "{{ envName }}-elb-{{ subsystem }}"
      state: present
      scheme: internet-facing
      security_group_names: "{{ group }}-{{ envName }}-elb-sg-{{ subsystem }}-{{ region }}"
      subnets: "{{ vpc_facts.subnets | map(attribute='id') | list }}"
      connection_draining_timeout: 60
      cross_az_load_balancing: yes
      listeners:
        - protocol: tcp
          load_balancer_port: 443
          instance_protocol: tcp
          instance_port: 443
      health_check:
        ping_protocol: https
        ping_port: 443
        ping_path: "/status"
        response_timeout: 6
        interval: 30
        unhealthy_threshold: 5
        healthy_threshold: 3
    register: elb_result
  ```

Currently, we are trying to setup Canary build prior to production to catch production issues with % of live production traffic.

I'm trying to see if we can install latest code only to one of the production aws host, run test and send live traffic prior to production deployment.

As I couldn't see any doc to set this environment, could you guide to solve this usecase?

##### EXPECTED RESULTS
We should be able to run canary instance and test which is hosted under same ELB prior to full production deployment

##### ACTUAL RESULTS
No provision to setup Canary build in the build pipeline
