### ISSUE TITLE
When becoming root I need to use: sudo bash 

### ISSUE THREAD

**Issue by xjantoth** [ansible/ansible#31167]
Hi there,

First of all let me tell you that we are about to use **ansible** in a rather 
large and complex  infrastructure.
 
However, I have a very special problem with **ansible** when I need to execute 
any **command as root**. I have a very special corporate restriction so 
I pretty much have like zero flexibility to change it. 

Whenever I want to do something with  **root privileges** - I need to 
run::
  
    sudo bash # (this makes me root obviously)
 
Afterwards, only I can run commands with root privileges.
I tried available configurations and their modifications however,
it seems like **ansible** does not have this function embeded yet.

It occurs to me that really the only way ansible operates right now
is *sudo some_command*

However that is not my case, because 

* I need to swtich to root ***sudo bash** or **sudo csh*** 
* run any command as **regular** root user

I examined options available in **command line** as well in **ansible-playbook**

We are using something called::
     
    which sudo 
    /usr/bin/sudo -> /.../.../.../bin/sesudo     

actually **when I run**::

    sudo bash 

In **fact** I am calling::

    /.../.../.../bin/sesudo bash  

Please advise. Thanks

**Comment by ansibot** [comment]
@xjantoth Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by xjantoth** [comment]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME



    become: yes

##### ANSIBLE VERSION

```


     ansible --version
     ansible 2.3.1.0
     config file = /etc/ansible/ansible.cfg
     configured module search path = Default w/o overrides
     python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)] 


```

##### CONFIGURATION

```
  - name: Todo something
    hosts: elastic_servers
    become: yes
    become_method: sudo
    #  become_user: root
    tasks:
      #- name: Install epel repo
      #  yum_repository:
      #    baseurl: 'https://dl.fedoraproject.org/pub/epel/7Server/x86_64/'
      #    description: "epel release."
      #    name: epel
      #    state: present
      #  become_user: root
      #  environment:
      #    http_proxy: http://proxy.com:80
      #    https_proxy: https://proxy.com:80

      - file:
          path: /root/ansible-test
          state: directory
          owner: root
          group: root
          mode: 755

      - name: Install nmap
        yum: name=nmap state=present
        environment:
          http_proxy: http://proxy.com:80
          https_proxy: https://proxy.com:80

```

##### OS / ENVIRONMENT



    cat /etc/os-release
    NAME="Red Hat Enterprise Linux Server"
    VERSION="7.1 (Maipo)"
    ID="rhel"
    ID_LIKE="fedora"
    VERSION_ID="7.1"
    PRETTY_NAME="Red Hat Enterprise Linux Server 7.1 (Maipo)"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:redhat:enterprise_linux:7.1:GA:server" 
    HOME_URL="https://www.redhat.com/"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"

    REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
    REDHAT_BUGZILLA_PRODUCT_VERSION=7.1
    REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
    REDHAT_SUPPORT_PRODUCT_VERSION="7.1"


Pretty much same issue: https://groups.google.com/forum/#!searchin/ansible-project/sudo%7Csort:relevance/ansible-project/c9n87Ya8-gk/hvxLSFALBAAJ
