### ISSUE TITLE
eos_config - extend intended_config to source from file or just use src param

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#31186]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0.0
  config file = 
  configured module search path = [u'/Users/lynchg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lynchg/.virtualenvs/a2x/lib/python2.7/site-packages/ansible
  executable location = /Users/lynchg/.virtualenvs/a2x/bin/ansible-playbook
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### SUMMARY
Extend `intended_config` to source from a file.  This would allow assembling a file (e.g. on a ZTPS server), and delegating to it to perform a diff against a switch.

##### STEPS TO REPRODUCE
Create a role which generates switch config and assembles it, e.g.
```yaml
- name: Assemble into a configuration file
  assemble:
    src: "{{ eos_temp_dir }}"
    dest: "{{ eos_dest_dir }}/startup-config"
    delimiter: '!'

- name: show the diff of running-config vs intended when using '--diff'
  eos_config:
    diff_against: intended
    intended_config: "{{ eos_dest_dir }}/startup-config"
    provider: "{{ eos_connection }}"
```
Create a playbook that sets up ZTPS, and uses the above role
```
---
- name: configure ztps
  hosts: ztps
  become: True
  become_user: root
  roles:
    - { role: ztps, tags: ztps }

- name: add switch startup-config to ztps
  hosts: switches
  connection: local
  gather_facts: False
  # run in batches, so that we don't overload the ansible box
  serial: 5
  become: True
  become_user: root
  vars:
    eos_dest_dir: /usr/share/ztpserver/files/configs/{{ ztps_node_system_id | default(inventory_hostname) }}

  roles:
    - { role: eos, tags: eos, delegate_to: "{{ groups['ztps'][0] }}" }
```

##### EXPECTED RESULTS
The config on the ZTPS server is diff'd against the that of the switch

##### ACTUAL RESULTS
The example for the `intended_config` uses a lookup to source the content, this runs on the controller and therefore fails in this case.

It makes it necessary to add a pre-task to fetch the config.  Which given the module already supports/uses the `src` param seems unintuitive.

So... does the module actually need a separate `intended_config`, when the `src` param might work?  And if it really does, then maybe it can be extended to support pulling from files?

It's not a big deal if not, but I am finding the params are a bit inconsistent with what they do(-not) take.

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn @gundalow @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
@halberom you can use a lookup to achieve what you are trying to do.  

Here is an updated example:

```
- name: show the diff of running-config vs intended when using '--diff'
  eos_config:
    diff_against: intended
    intended_config: "{{ lookup('file', 'path/to/intended/startup-config') }}"
    provider: "{{ eos_connection }}"
```

**Comment by gundalow** [comment]
@halberom Does the above work for you?
If so we could add that as an example in the module documentation

needs_info

**Comment by halberom** [comment]
Sorry, forgot about this issue.  

So this is more of a feature request.  `lookup` works if the intended_config source is on the ansible controller.  However as mentioned in my description, I'm running the task against a ZTPS box (similar to a kickstart server).  So I'm doing something like

```
- hosts: switches
   roles
    - { role: eos, delegate_to: ztps }
```

In this case, the eos_config task is being run on the ztps server, and the switch config is being built on the ztps server, so a `lookup` will not work.  The reason I raised this ticket is that the `src:` param _will_ work, which makes it somewhat annoying and inconsistent that the intended_config works differently and requires me to do
```
- command: cat /path/to/config
  register: intended_config

- eos_config:
    intended_config: "{{ intended_config.stdout }}"
```
It's workaroundable, but as said, inconsistent and annoying.  Especially as I can't see why you'd ever want to provide both src and intended_config at the same time - so why can't the same param (src) be used for diffing?  Or are there actual use cases for applying config and diffing against a completely different one at the same time?
