### ISSUE TITLE
Fetching large file consumes a lot of memory

### ISSUE THREAD

**Issue by VojtechMyslivec** [ansible/ansible#31194]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module `fetch`

##### ANSIBLE VERSION

```
ansible 2.4.0.0 (detached HEAD d14467b029) last updated 2017/09/22 13:29:24 (GMT +200)
  config file = ./ansible.cfg
  configured module search path = [u'$HOME/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/bin/ansible/lib/ansible
  executable location = $HOME/bin/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(./ansible.cfg) = True
ANSIBLE_SSH_PIPELINING(./ansible.cfg) = True
CACHE_PLUGIN(./ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(./ansible.cfg) = /tmp/ansible_facts_cache
CACHE_PLUGIN_TIMEOUT(./ansible.cfg) = 7200
DEFAULT_CALLBACK_PLUGIN_PATH(./ansible.cfg) = [u'./callbacks']
DEFAULT_FORKS(./ansible.cfg) = 25
DEFAULT_GATHERING(./ansible.cfg) = smart
DEFAULT_HOST_LIST(./ansible.cfg) = [u'./hosts']
DEFAULT_LOCAL_TMP(./ansible.cfg) = /tmp/.ansible/tmp/ansible-local-18383M5QWWd
DEFAULT_REMOTE_TMP(./ansible.cfg) = /tmp/.ansible_$USER/tmp
DEFAULT_ROLES_PATH(./ansible.cfg) = [u'./roles', u'./shared-roles']
DEFAULT_VAULT_PASSWORD_FILE(./ansible.cfg) = ./vault.sh
RETRY_FILES_ENABLED(./ansible.cfg) = False
```

##### OS / ENVIRONMENT

Running from Debian Testing (Buster), managing Ubuntu 16 and 14 LTS.

##### SUMMARY

Fetching larger files consumes too much memory on controller node. I have tried to fetch 411 MB *tar* file with both *Ansible* 2.3 and 2.4 and also with `validate_checksum` parameter set to `false`. RAM consumed by python process rise up to 3-5GB! This causes local system to swap a lot and freezes. Consumed RAM on *controlled host* also rise a lot a cannot provide more details.

Similar problems were reported in #11702.

##### STEPS TO REPRODUCE

```yaml
- name: Migrate LXC container
  hosts: '{{ guest }}'
  gather_facts: no
  tasks:
    - name: Fetch large file to local machine
      fetch:
        src: '/var/lib/lxc/archive/{{ large_file }}'
        dest: 'tmp/{{ large_file }}'
        fail_on_missing: yes
        flat: yes
      delegate_to: '{{ host }}'
```

##### EXPECTED RESULTS

Ansible downloads given file to given path with no extra memory consumption (i.e by few kB or MB blocks).

##### ACTUAL RESULTS

Ansible downloads given file but system freezes and memory rise up to 100 % consumed RAM. I have not tested larger files then few hundred megabytes.

**Comment by sivel** [comment]
Are you running this task with `become`?  Per a note in that modules documentation:

> When running fetch with become, the slurp module will also be used to fetch the contents
> of the file for determining the remote checksum. This effectively doubles the transfer size,
> and depending on the file size can consume all available memory on the remote or local
> hosts causing a MemoryError. Due to this it is advisable to run this module without
> become whenever possible

needs_info

**Comment by VojtechMyslivec** [comment]
Thanks for reply. Yes I do and I read the note you post. But same as [here](https://github.com/ansible/ansible/issues/11702#issuecomment-307656940) it is needed to do so, because the files are accessible by `root` only. 

Also 400 MB * 2 is 0.8 GB, which will not cause 16 GB RAM control node to freeze. And what to do when I need to copy/migrate 20GB file?

**Comment by bcoca** [comment]
You can use `synchronize` in `pull` mode

**Comment by VojtechMyslivec** [comment]
Thanks @bcoca, I have tried. But I wasn't able to run in pull mode while delegating to a another machine.

I have workaround it with:
```yaml
# needs become on the other side...
- name: Fetch the archive to local machine
  shell: |
    ssh '{{ hostvars[run_on].ansible_user }}@{{ run_on }}' 'sudo cat "{{ m_lxc_archive_file }}"' > '{{ m_local_archive_file }}'
  delegate_to: 'localhost'
```

Which is disgusting but it works: it fetches the file in 5 seconds and takes nearly no memory in compare to more than 1 minute with freezing system.

**Comment by scottalan** [comment]
I was having the same issue and this is what worked for me:

Original "fetch":
```
- name: fetch package 
  fetch:
    src:  "{{ path_to_archive }}.tar"
    dest: ../../revert_data.tar
    flat: yes

- name: fetch code
  fetch:
    src:  "{{ docroot_path }}/build/build.tar.gz"
    dest: ../../revert_build.tar.gz
    flat: yes
```
Using "synchronize":

```
- name: Pull database and files archive from {{ inventory_hostname }} to the utility server
  synchronize:
    mode: pull
    src: "{{ path_to_archive }}.tar"
    dest: "{{ jenkins_workspace }}/revert_data.tar"
  when:
    - jenkins_workspace is defined
    - inventory_hostname == groups['web'][0]
  changed_when: false

- name: Pull code archive from {{ inventory_hostname }} to the utility server
  synchronize:
    mode: pull
    src: "{{ docroot_path }}/build/build.tar.gz"
    dest: "{{ jenkins_workspace }}/revert_build.tar.gz"
  when:
    - jenkins_workspace is defined
    - inventory_hostname == groups['web'][0]
  changed_when: false
```
