### ISSUE TITLE
Parallel execution of plays

### ISSUE THREAD

**Issue by JulienPalard** [ansible/ansible#31199]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ansible-playbook

##### SUMMARY

Currently, inside a single play, tasks can run in parallel on different hosts, and the degree of parallelisation can be configured via [plays strategies](http://docs.ansible.com/ansible/latest/playbooks_strategies.html), which is nice.

Now, from a playbook point of view, each plays are executed sequencially, which is nice when one play depend on the previous one, which may not always be the case (should they?). Typically in a "group by roles" model, inspired from the documentation:

```
---
- hosts: webservers
  roles:
    - common
    - webserver

- hosts: dbservers
  roles:
    - common
    - dbserver
```

There's obviously no need to wait for the first play (applying the webserver and common roles to the webservers) to complete before starting the second play (applying the common and dbserver roles to the dbservers), both may be executed simultaneously.

Maybe, after `play stragegies`, `playbook strategies` can be introduced?
