### ISSUE TITLE
oc module extends instead of replaces a list

### ISSUE THREAD

**Issue by LittleChimera** [ansible/ansible#31196]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

oc

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/luka/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]

```

##### CONFIGURATION
default

##### OS / ENVIRONMENT

Linux / Manjaro

##### SUMMARY

oc module with inline definition expands list of triggers.
i.e. when set to empty list, it maintains old configuration, while having some triggers adds duplicate entry on each run.

##### STEPS TO REPRODUCE

```yaml
- name: Create OpenShift resource
  oc:
    host: "{{ inventory_hostname }}"
    validate_certs: false
    state: present
    inline: "{{ lookup('template', openshift_template) | from_yaml }}"
    token: "{{ namespace_token }}"
```

##### EXPECTED RESULTS

replaced list

##### ACTUAL RESULTS

extended list with duplicates / persisting old config

**Comment by ansibot** [comment]
cc @kevensen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kevensen** [comment]
I'm happy to take a look.  Can you please provide an example of the output you see?
needs_info

**Comment by LittleChimera** [comment]
```yaml
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-ci-build-on-merge
      from:
        kind: ImageStreamTag
        name: gitlab-ci-build-on-merge:latest
        namespace: gitlab-ci-runner-test
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-ci-build-on-merge
      from:
        kind: ImageStreamTag
        name: gitlab-ci-build-on-merge:latest
        namespace: gitlab-ci-runner-test
    type: ImageChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - gitlab-ci-build-on-merge
      from:
        kind: ImageStreamTag
        name: gitlab-ci-build-on-merge:latest
        namespace: gitlab-ci-runner-test
    type: ImageChange
```

Template for this deploymentconfig has triggers for image change and config change. After multiple runs of playbook, multiple ImageChange entries are added, while ConfigChange remains only one.

When using template that has explicitly set triggers to empty lists, the triggers remain the same.

As far as I can tell, the issue is [here](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/oc.py#L349-L355) when merging two sets.
Value should probably be overriden if it's defined in new config, and persisted if no new configuration is specified.
