### ISSUE TITLE
Cannot capture yum list output with package names

### ISSUE THREAD

**Issue by Laszlo-JFLMTCO** [ansible/ansible#31211]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`yum`

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/svc-ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

Running on macOS Sierra version 10.12.6.

##### SUMMARY

I was trying to check if packages are available for a specific version of Java.
I capture the output of running the `yum list` task, but it only captures the status of running the command (was running the command successful or not), not its output whether packages are available or not.

##### STEPS TO REPRODUCE

```yaml
- name: Confirm if package for {{ required_version }} is available
  yum:
    list: required_version
  register: package_search
- name: Print package search result
  debug:
    var: package_search
```

##### EXPECTED RESULTS

Output whether packages are available or not.

##### ACTUAL RESULTS

Only captures the status of running the command (was running the command successful or not)

Output running with `ansible-playbook -v <PLAYBOOK_NAME>`
```
TASK [testjavaupdate : Confirm if package for java-1.1* is available] *************************************************************************************************************
ok: [192.168.202.133] => {"changed": false, "failed": false, "results": []}

TASK [testjavaupdate : Print package search result] *******************************************************************************************************************************
ok: [192.168.202.133] => {
    "package_search": {
        "changed": false, 
        "failed": false, 
        "results": []
    }
}
```

**Comment by ansibot** [comment]
cc @berenddeschouwer @mkrizek @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
For this case, is there a match for 'java-1.1*'?

What is the verbose output for running a play with these tasks:

``` yaml

- name: Confirm if kernel package for is available
  yum:
    list: kernel
  register: package_search

- name: Print kernel package search result
  debug:
    var: package_search

- name: Confirm if yum package is available
  yum:
    list: yum
  register: package_search

- name: Print yum package search result
  debug:
    var: package_search

- name: Confirm if thing-that-does-not-exist  is available
  yum:
    list: that-that-does-not-exist
  register: package_search

- name: Print that-that-does-not-exist search result
  debug:
    var: package_search
```
