### ISSUE TITLE
Cannot set cache headers in s3 and aws_s3 module

### ISSUE THREAD

**Issue by pyconsult** [ansible/ansible#31232]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
s3 and aws_s3

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/home/krl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/krl/.virtualenvs/devops/local/lib/python2.7/site-packages/ansible
  executable location = /home/krl/.virtualenvs/devops/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
vanilla

##### OS / ENVIRONMENT
ubuntu 16.04

##### SUMMARY

Setting `Cache-Control` headers in  `metadata` will result in setting the metadata key: `aws_s3 x-amz-meta-cache-control`  on AWS. This makes it impossible to set the `Cache-Control` header on the s3 object. The `Content-Type` was set automatically before. Now it defaults to `binary/octet-stream`

##### STEPS TO REPRODUCE

Try to put a file to s3

```yaml
    - name: Upload images files
      s3:
        bucket: "bucket-name"
        object: "{{ item | basename }}"
        region: "{{ aws_region }}"
        src: "{{ item }}"
        mode: put
        permission: 'public-read'
        metadata: ''Cache-Control='max-age=3600'"
      with_fileglob:
        - "dist/*.png"
```

##### EXPECTED RESULTS
I expect the `Cache-Control` header to be set

##### ACTUAL RESULTS
 `aws_s3 x-amz-meta-cache-control` was set not `Cache-Control`
