### ISSUE TITLE
AnsibleUndefinedVariable:  'dict Object' has no attribute 'ansible_eth0'

### ISSUE THREAD

**Issue by swaapnika-guntaka** [ansible/ansible#31328]
![noattrribute](https://user-images.githubusercontent.com/18042968/31199277-b6193f4e-a90b-11e7-9b1d-a57085308d02.png)

##### ISSUE TYPE
 - Bug Report
AnsibleUndefinedVariable:  'dict Object' has no attribute 'ansible_eth0'`

##### ANSIBLE VERSION

```
Ansible  2.4
```

##### CONFIGURATION

[defaults]
remote_tmp = /tmp/.ansible-${USER}/tmp
##### OS / ENVIRONMENT
CentOS 6.7

##### SUMMARY

I'm trying to provision a 3 node cassandra cluster using ansible and specified the hosts in a master config file. I'm facing the belwo issue on one of the nodes.

```yaml
---
- name: 'Cassandra Playbook'
  hosts: cassandra-cluster-nodes
  vars:
       cassandra-cluster-setup: True
       cassandra_config: true

roles:
 - cassandra


##### EXPECTED RESULTS
Ansible success

##### ACTUAL RESULTS
`AnsibleUndefinedVariable: 'dict Object' has no attribute 'ansible_eth0'`


```

```
