### ISSUE TITLE
docker_container module won't recreate container when environment variables are removed

### ISSUE THREAD

**Issue by jeinwag** [ansible/ansible#31338]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_container module
##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/julian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.4.1.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

The docker_container module doesn't correctly change/recreate containers when environment variables are removed from the specification and the playbook is run again.

PR with a possible fix will follow.

##### STEPS TO REPRODUCE

Make sure there's no container called "testcontainer" on your system and run the following playbook:
```yaml
- name: test docker_container module
  hosts: localhost
  tasks:
    - name: "create container"
      docker_container:
        image: nginx:latest
        name: testcontainer
        env:
          VARIABLE1: true
          VARIABLE2: true

    - name: "remove VARIABLE2"
      docker_container:
        image: nginx:latest
        name: testcontainer
        env:
          VARIABLE1: true

```

##### EXPECTED RESULTS
The second task should recreate the container due to the changed environment.

##### ACTUAL RESULTS
The second task doesn't change anything:

```
PLAY [test docker_container module] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [create container] *********************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [remove VARIABLE2] *********************************************************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0

```

**Comment by ansibot** [comment]
cc @chouseknecht @cove @dusdanig @jctanner @joshuaconner @kassiansun @softzilla @zfil
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chouseknecht** [comment]
As explained on #31340, I don't believe this is a bug.

**Comment by SpComb** [comment]
(reposted from #31340 because that was a PR, and this is a suggestion for a fix for this issue)

Docker seems to also support unsetting envs using `"Env": ["FOO"]` in the API: https://docs.docker.com/engine/api/v1.37/#operation/ContainerCreate

> A list of environment variables to set inside the container in the form ["VAR=value", ...]. A variable without = is removed from the environment, rather than to have an empty value.

This also works for overriding/unsetting envs set in the Docker image: 

```
$ docker image inspect -f '{{ .Config.Env | json }}' openjdk:8
["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","LANG=C.UTF-8","JAVA_HOME=/docker-java-home","JAVA_VERSION=8u181","JAVA_DEBIAN_VERSION=8u181-b13-2~deb9u1"]
$ docker run --name=env-test -it -e JAVA_HOME openjdk:8 env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=2b272321df3a
TERM=xterm
LANG=C.UTF-8
JAVA_VERSION=8u181
JAVA_DEBIAN_VERSION=8u181-b13-2~deb9u1
HOME=/root
$ docker container inspect -f '{{ .Config.Env | json }}' env-test
["JAVA_HOME","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","LANG=C.UTF-8","JAVA_VERSION=8u181","JAVA_DEBIAN_VERSION=8u181-b13-2~deb9u1"]
```

This would be easy to fix in Ansible if passing a env as `None` were to generate the env as `["FOO"]` without the value, but I don't think that's currently possible:

## Broken examples
### Trying to pass explicit list
```yaml
- hosts: localhost
  tasks:
    - docker_container:
        name: env-test
        image: openjdk:8
        state: started
        command: env
        env:
          - JAVA_HOME
```

```
TASK [docker_container] ************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument env is of type <type 'list'> and we were unable to convert to dict: <type 'list'> cannot be converted to a dict"}
	to retry, use: --limit @/home/terom/otm-dev/test.retry
```

### Trying to pass env with null value

```yaml
- hosts: localhost
  tasks:
    - docker_container:
        name: env-test
        image: openjdk:8
        state: started
        command: env
        env:
          JAVA_HOME: 
```

```
$ docker container inspect -f '{{ .Config.Env | json }}' env-test
["JAVA_HOME=None","PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin","LANG=C.UTF-8","JAVA_VERSION=8u181","JAVA_DEBIAN_VERSION=8u181-b13-2~deb9u1"]
$ docker logs env-test
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=1b842508b99a
JAVA_HOME=None
LANG=C.UTF-8
JAVA_VERSION=8u181
JAVA_DEBIAN_VERSION=8u181-b13-2~deb9u1
HOME=/root
```

The null value in the YAML gets converted to a `None` string, which is not useful behavior.
