### ISSUE TITLE
Yum module doesn't allow downgrade using local RPMs

### ISSUE THREAD

**Issue by agenosov** [ansible/ansible#31350]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
yum module

##### ANSIBLE VERSION

```
2.4.0.0
```

##### CONFIGURATION

DEFAULT_KEEP_REMOTE_FILES(env: ANSIBLE_KEEP_REMOTE_FILES) = True
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /home/andrey/.config/deploy/deploy-log-1507199791.log
DEFAULT_TIMEOUT(/tmp/tmp.deploy-2.5.0-206.bundle.jyFznO4WVz/share/ansible.cfg) = 60
HOST_KEY_CHECKING(/tmp/tmp.deploy-2.5.0-206.bundle.jyFznO4WVz//share/ansible.cfg) = False
RETRY_FILES_ENABLED(/tmp/tmp.deploy-2.5.0-206.bundle.jyFznO4WVz/share/ansible.cfg) = False

##### OS / ENVIRONMENT

master host OS: Ubuntu 16.04.3 LTS
target host OS: CentOS 3.10.0-514.16.1.el7.x86_64
Actually it doesn't matter that master host isn't RPM-based - the same behaviour is when deploy occurs locally, i.e. on CentOS.

##### SUMMARY

There is no possibility to downgrade installed packages using local RPM files.

I encountered this problem when deploying our internal software. There was installed the latest version, and I tested a downgrade process, trying to deploy a previous release. The yum module ended up with the error "Error: Nothing to do\n".

##### STEPS TO REPRODUCE

Try do downgrade any installed package using local RPM file using the playbook provided below

```yaml
- hosts: 127.0.0.1
  connection: local

  vars:
#    package_of_your_choice_here: 
#    path_to_local_rpm:

  tasks:
  - name: First install the latest packages
    yum:
      name="{{ package_of_your_choice_here }}"
      state=present
      update_cache=yes
  
  - name: Now try to downgrade the package previously installed 
    yum: 
      name="{{ path_to_local_rpm }}"
      state=present
      update_cache=yes
      allow_downgrade=yes
```

##### EXPECTED RESULTS

The installed package is downgraded gracefully.

##### ACTUAL RESULTS

The yum module ends up with the following error:

```
"msg": "Error: Nothing to do\n",
    "rc": 1,
    "results": [
        "Loaded plugins: fastestmirror\nExamining /tmp/deploy/<MY_PACKAGE_NAME>-1.1.0-3839.x86_64.rpm: MY_PACKAGE_NAME-1.1.0-3839.x86_64\n/tmp/deploy/MY_PACKAGE_NAME-1.1.0-3839.x86_64.rpm: does not update installed package.\n"
    ]
```

**Comment by ansibot** [comment]
cc @akasurde @berenddeschouwer @mkrizek @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by agenosov** [comment]
Consider the patch which works in my case.
[ansible-yum-downgrade.zip](https://github.com/ansible/ansible/files/1359157/ansible-yum-downgrade.zip)

**Comment by seblatre** [comment]
<details><summary>Hide my comment because alrealdy covered by #30991</summary><p>
I have a similar issue on my side but when installing the exact same package (no downgrade). Hope this is the same bug. Otherwise tell me and I will open a new one.

I'm testing a playbook targetting Centos 6.8 with the yum module.
The part of my playbook which is problematic
```yaml
- name: Install RPMs on server
  yum: name="/tmp/{{ item }}" state=present
  with_items:
    - "{{ neo4j_yum_rpm_dep_nss }}"
    - "{{ neo4j_yum_rpm_dep_nss_util }}"
    - "{{ neo4j_yum_rpm_dep_nss_tools }}"
    - "{{ neo4j_yum_rpm_dep_nss_sysinit }}"
    - "{{ neo4j_yum_rpm_dep_nspr }}"
    - "{{ neo4j_yum_rpm_dep_java }}"
    - "{{ neo4j_yum_rpm_dep_cypher }}"
    - "{{ neo4j_yum_rpm_neo4j }}"
```

I tested successfully my playbook on a local VM with the following versions:
```
yum --version
3.2.29
  Installed: rpm-4.8.0-55.el6.x86_64 at 2017-10-02 12:01
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2016-05-10 23:49
  Committed: Lubos Kardos <lkardos@redhat.com> at 2016-03-29

  Installed: yum-3.2.29-73.el6.centos.noarch at 2017-10-02 12:01
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2016-05-11 20:37
  Committed: Johnny Hughes <johnny@centos.org> at 2016-05-10

  Installed: yum-plugin-fastestmirror-1.1.30-37.el6.noarch at 2017-10-02 12:01
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2016-05-10 21:04
  Committed: Valentina Mukhamedzhanova <vmukhame@redhat.com> at 2016-02-10
```

But it fails on the target host with the following versions:
```
yum --version
3.2.29
  Installed: rpm-4.8.0-55.el6.x86_64 at 2017-06-05 19:59
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2016-05-10 23:49
  Committed: Lubos Kardos <lkardos@redhat.com> at 2016-03-29

  Installed: yum-3.2.29-81.el6.centos.noarch at 2017-10-05 18:03
  Built    : CentOS BuildSystem <http://bugs.centos.org> at 2017-03-22 05:32
  Committed: Johnny Hughes <johnny@centos.org> at 2017-03-21

  Installed: yum-rhn-plugin-2.4.6-1.el6.noarch at 2016-12-29 13:56
  Built    : Koji at 2015-09-24 17:46
  Committed: Jan Dobes 2.4.6-1 at 2015-09-24
```

In that case, Ansible output is the following:
```
failed: [xxxxxxxxx] (item=[u'/tmp/nss-3.28.4-4.el6_9.x86_64.rpm', u'/tmp/nss-util-3.28.4-1.el6_9.x86_64.rpm', u'/tmp/nss-tools-3.28.4-4.el6_9.x86_64.rpm', u'/tmp/nss-sysinit-3.28.4-4.el6_9.x86_64.rpm', u'/tmp/nspr-4.13.1-1.el6.x86_64.rpm', u'/tmp/java-1.8.0-openjdk-headless-1.8.0.141-3.b16.el6_9.x86_64.rpm', u'/tmp/cypher-shell-1.1.2-1.noarch.rpm', u'/tmp/neo4j-enterprise-3.2.6-1.noarch.rpm']) => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "conf_file": null,
            "disable_gpg_check": false,
            "disablerepo": null,
            "enablerepo": null,
            "exclude": null,
            "install_repoquery": true,
            "installroot": "/",
            "list": null,
            "name": [
                "/tmp/nss-3.28.4-4.el6_9.x86_64.rpm",
                "/tmp/nss-util-3.28.4-1.el6_9.x86_64.rpm",
                "/tmp/nss-tools-3.28.4-4.el6_9.x86_64.rpm",
                "/tmp/nss-sysinit-3.28.4-4.el6_9.x86_64.rpm",
                "/tmp/nspr-4.13.1-1.el6.x86_64.rpm",
                "/tmp/java-1.8.0-openjdk-headless-1.8.0.141-3.b16.el6_9.x86_64.rpm",
                "/tmp/cypher-shell-1.1.2-1.noarch.rpm",
                "/tmp/neo4j-enterprise-3.2.6-1.noarch.rpm"
            ],
            "security": false,
            "skip_broken": false,
            "state": "present",
            "update_cache": false,
            "validate_certs": true
        }
    },
    "item": [
        "/tmp/nss-3.28.4-4.el6_9.x86_64.rpm",
        "/tmp/nss-util-3.28.4-1.el6_9.x86_64.rpm",
        "/tmp/nss-tools-3.28.4-4.el6_9.x86_64.rpm",
        "/tmp/nss-sysinit-3.28.4-4.el6_9.x86_64.rpm",
        "/tmp/nspr-4.13.1-1.el6.x86_64.rpm",
        "/tmp/java-1.8.0-openjdk-headless-1.8.0.141-3.b16.el6_9.x86_64.rpm",
        "/tmp/cypher-shell-1.1.2-1.noarch.rpm",
        "/tmp/neo4j-enterprise-3.2.6-1.noarch.rpm"
    ],
    "msg": "Error: Nothing to do\n",
    "rc": 1,
    "results": [
        "Loaded plugins: rhnplugin, security\nThis system is receiving updates from RHN Classic or Red Hat Satellite.\nSetting up Install Process\nExamining /tmp/nss-3.28.4-4.el6_9.x86_64.rpm: nss-3.28.4-4.el6_9.x86_64\n/tmp/nss-3.28.4-4.el6_9.x86_64.rpm: does not update installed package.\nExamining /tmp/nss-util-3.28.4-1.el6_9.x86_64.rpm: nss-util-3.28.4-1.el6_9.x86_64\n/tmp/nss-util-3.28.4-1.el6_9.x86_64.rpm: does not update installed package.\nExamining /tmp/nss-tools-3.28.4-4.el6_9.x86_64.rpm: nss-tools-3.28.4-4.el6_9.x86_64\n/tmp/nss-tools-3.28.4-4.el6_9.x86_64.rpm: does not update installed package.\nExamining /tmp/nss-sysinit-3.28.4-4.el6_9.x86_64.rpm: nss-sysinit-3.28.4-4.el6_9.x86_64\n/tmp/nss-sysinit-3.28.4-4.el6_9.x86_64.rpm: does not update installed package.\nExamining /tmp/nspr-4.13.1-1.el6.x86_64.rpm: nspr-4.13.1-1.el6.x86_64\n/tmp/nspr-4.13.1-1.el6.x86_64.rpm: does not update installed package.\nExamining /tmp/java-1.8.0-openjdk-headless-1.8.0.141-3.b16.el6_9.x86_64.rpm: 1:java-1.8.0-openjdk-headless-1.8.0.141-3.b16.el6_9.x86_64\n/tmp/java-1.8.0-openjdk-headless-1.8.0.141-3.b16.el6_9.x86_64.rpm: does not update installed package.\nExamining /tmp/cypher-shell-1.1.2-1.noarch.rpm: cypher-shell-1.1.2-1.noarch\n/tmp/cypher-shell-1.1.2-1.noarch.rpm: does not update installed package.\nExamining /tmp/neo4j-enterprise-3.2.6-1.noarch.rpm: neo4j-enterprise-3.2.6-1.noarch\n/tmp/neo4j-enterprise-3.2.6-1.noarch.rpm: does not update installed package.\n"
    ]
}
```

Here the interesting point is the *rhn-plugin*.
When deactivating it within `/etc/yum/pluginconf.d/rhnplugin.conf`, the playbook works again on my target host
</p></details>
