### ISSUE TITLE
passwordstore lookup prints password in plaintext when used in set_fact

### ISSUE THREAD

**Issue by jficz** [ansible/ansible#31375]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

passwordstore lookup

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION

default
##### OS / ENVIRONMENT

Arch Linux
##### SUMMARY

When using passwordstore lookup in set_fact, the result gets printed on stdout in plaintext if verbose
##### STEPS TO REPRODUCE

```yaml
- name: generate service password
  set_fact:
    service_password: "{{ lookup('passwordstore', 'servers/sites/service create=true ') }}"
```

##### EXPECTED RESULTS

```
ok: [my.server.com] => {"ansible_facts": {"service_password": "***"}, "changed": false, "failed": false}
```
##### ACTUAL RESULTS

```
ok: [my.server.com] => {"ansible_facts": {"service_password": "Dk_9^uG7CXN4KmO^9rLb"}, "changed": false, "failed": false}
```
