### ISSUE TITLE
Add a way to list existing resources in OpenShift by Kind

### ISSUE THREAD

**Issue by lucastheisen** [ansible/ansible#31376]
##### ISSUE TYPE

 - Feature Idea
 
##### COMPONENT NAME

oc

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /home/ltheisen/git/caasd-portal-openshift/ansible.cfg
  configured module search path = [u'library/ansible/modules/clustering', u'./library']
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

From: CentOS 7
To: CentOS 7

##### SUMMARY

I am using ansible to manage my NFS persistent volumes.  Its easy enough to create/remove both NFS volumes and openshift PersistentVolumes using existing modules.  However, in order to clean up volumes that are no longer needed, I need a way to compare what currently exists, with what is desired.  For NFS its a simple `ls -1 /root/nfs/folder/`, but for openshift, the `oc` module does not support a method for listing the existing PersistentVolumes (akin to `oc get pv --output yaml`).  I can work around this by keeping all volumes that ever existed and just switching from `present` to `absent` but seems like a code smell to maintain a list of all the things you _used to have_....

##### STEPS TO REPRODUCE

```yaml
---
- name: mount netapp openshift
  mount:
    path: /mnt/netapp
    src: "{{ pv_manager_nfs_hostname }}:{{ pv_manager_nfs_root_path }}"
    fstype: nfs
    state: mounted
  changed_when: False

- name: ensure persistent volume folders exist
  file:
    path: '/mnt/netapp/{{ item.name }}'
    state: directory
    mode: 0777
    owner: nfsnobody
    group: nfsnobody
  register: persistent_volumes
  with_items: "{{ pv_manager_volumes }}"

- name: ensure persistent volumes exist
  oc:
    host: "{{ groups.masters[0] }}"
    state: present
    inline:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: "{{ item.name }}"
      spec:
        capacity:
          storage: "{{ item.size | default('5Gi') }}"
        accessModes: "{{ item.accessModes | default(['ReadWriteOnce']) }}"
        nfs:
          path: "{{ pv_manager_nfs_root_path }}/{{ item.name }}"
          server: "{{ pv_manager_nfs_hostname }}"
        persistentVolumeReclaimPolicy: Delete
    token: "{{ pv_manager_token }}"
    validate_certs: "{{ pv_manager_validate_certs | default(True) }}"
  with_items: "{{ pv_manager_volumes }}"

# NEED SOMETHING HERE
# - name: gather current persistent volumes
#   oc:
#     host: "{{ groups.masters[0] }}"
#     state: present
#     kind: PersistentVolume
#     token: "{{ pv_manager_token }}"
#     validate_certs: "{{ pv_manager_validate_certs | default(True) }}"
#   register: current_persistent_volumes
#
# - debug:
#     var: current_persistent_volumes

- name: gather current persistent volume folders
  shell: ls -1 /mnt/netapp
  register: current_persistent_volume_folders
  changed_when: False

- name: remove unmanaged persistent volume folders
  file:
    path: '/mnt/netapp/{{ item }}'
    state: absent
  with_items: "{{ current_persistent_volume_folders.stdout_lines }}"
  when: item not in pv_manager_volumes|map(attribute='name')|list

- name: unmount netapp openshift
  mount:
    path: /mnt/netapp
    state: unmounted
  changed_when: False

```
