### ISSUE TITLE
ec2_group doesn't allow for target of prefix list.

### ISSUE THREAD

**Issue by dan-osms** [ansible/ansible#31383]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

Nada

##### OS / ENVIRONMENT

Mac 10.13 (High Sierra)

##### STEPS TO REPRODUCE

```yaml
    - name: Some SG name
      local_action:
        module: ec2_group
        profile: xxxxx
        name: xxxxxxx
        description: xxxxxx
        vpc_id: vpc-xxxxxxxx
        region: some region
        state: present
        rules: []
        rules_egress:
          - proto: tcp
            from_port: 80
            to_port: 80
            prefix_list: pl-xxxxxx
          - proto: tcp
            from_port: 443
            to_port: 443
            prefix_list: pl-xxxxxx
```

##### EXPECTED RESULTS

Feature request would like to apply prefix list to a target within an SG.
##### ACTUAL RESULTS

```

```
