### ISSUE TITLE
GCE_IMG Moduleparamter pem_file is ambiguous

### ISSUE THREAD

**Issue by shithead** [ansible/ansible#31404]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
modules/cloud/google/gce_img.py

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The parameter pem_file is ambiguous, it has to be paramter credentials_file like in all other Google Cloud modules.

https://github.com/ansible/ansible/blob/d8b1cb9a634d0e828a7be39d4019a6215410e643/lib/ansible/modules/cloud/google/gce_img.py#L69-L71

##### STEPS TO REPRODUCE

```yaml
   -  gce_img:
        service_account_email: "{{ service_account_email }}"
        project_id: "{{ project_id }}" 
        pem_file: "{{ pem_file }}" # it has to be a json file not a pem
        zone: "{{ compute_zone }}"
```
##### EXPECTED RESULTS
Ok: 

##### ACTUAL RESULTS
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "RSA key format is not supported"}
