### ISSUE TITLE
bigip_facts against virtual_server fails on 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by narankhetani** [ansible/ansible#31416]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/network/f5

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/naran.khetani/.ansible.cfg
  configured module search path = [u'/Users/naran.khetani/projects/xx/cns-ansible/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### SUMMARY

When trying to get the facts of the list of virtualservers I get this error
##### STEPS TO REPRODUCE

```yaml
---
- name: F5 iRule Verification
  hosts: adc-003.xx.com
  gather_facts: false
  vars:
    customer_vip_rules:
      - { 'priority' : 0, 'rule_name' : '/Common/irule_0' }
      - { 'priority' : 1, 'rule_name' : '/Common/irule_1' }
      - { 'priority' : 2, 'rule_name' : '/Common/irule_2' }

  tasks:
    - name: Query BIG-IP facts for Virtual Servers
      bigip_facts:
        validate_certs: False
        server: "{{inventory_hostname}}"
        user: "admin"
        password: "xx"
        include: "virtual_server"
      delegate_to: localhost
      register: bigip_facts

    - name: Search for relevant Virtual Servers
      set_fact: 
        vip_results: "{{ vip_results|default([]) + [{'vip': {'name': item.key, 'rule': item.value.rule|sort(attribute='priority') }}] }}"
      when: "item.key | search('/Common/vip_public.*.shared_https$') or item.key | search('/Common/vip_c_.*.https$')"
      with_dict: "{{ bigip_facts.ansible_facts.virtual_server }}"

    - name: Check if VIP has correct iRules
      assert:
        that:
          - "item.vip.rule == customer_vip_rules"
      with_items: "{{ vip_results }}"
```

##### EXPECTED RESULTS
I expect it to collect the virtual_servers

##### ACTUAL RESULTS

Could this be causing the failure the description having such a character?:
```
ltm virtual vip_c_1151llc33_https {
    description "11.11° WWC"
}
```

```
ansible-playbook -i inventory f5_irule_verification.yml -vvvvv
ansible-playbook 2.4.0.0
  config file = /Users/naran.khetani/.ansible.cfg
  configured module search path = [u'/Users/naran.khetani/projects/xx/cns-ansible/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.10 (default, Jul 30 2016, 19:40:32) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
Using /Users/naran.khetani/.ansible.cfg as config file
setting up inventory plugins
Parsed /Users/naran.khetani/drive/scripts/projects/xx/cns-ansible/playbooks/audits/inventory/all inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin unnamed of type old, v2.0 from /Library/Python/2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: f5_irule_verification.yml ***********************************************************************************************
1 plays in f5_irule_verification.yml

PLAY [F5 iRule Verification] ******************************************************************************************************
META: ran handlers

TASK [Query BIG-IP facts for Virtual Servers] *************************************************************************************
task path: /Users/naran.khetani/drive/scripts/projects/xx/cns-ansible/playbooks/audits/f5_irule_verification.yml:19
Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/f5_utils.py
Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /Library/Python/2.7/site-packages/ansible/module_utils/six/__init__.py
Using module file /Library/Python/2.7/site-packages/ansible/modules/network/f5/bigip_facts.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: naran.khetani
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/naran.khetani/.ansible/tmp/ansible-tmp-1507295347.61-157506857356724 `" && echo ansible-tmp-1507295347.61-157506857356724="` echo /Users/naran.khetani/.ansible/tmp/ansible-tmp-1507295347.61-157506857356724 `" ) && sleep 0'
<localhost> PUT /var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/tmpIl6inE TO /Users/naran.khetani/.ansible/tmp/ansible-tmp-1507295347.61-157506857356724/bigip_facts.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/naran.khetani/.ansible/tmp/ansible-tmp-1507295347.61-157506857356724/ /Users/naran.khetani/.ansible/tmp/ansible-tmp-1507295347.61-157506857356724/bigip_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /Users/naran.khetani/.ansible/tmp/ansible-tmp-1507295347.61-157506857356724/bigip_facts.py; rm -rf "/Users/naran.khetani/.ansible/tmp/ansible-tmp-1507295347.61-157506857356724/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_XJ8kBE/ansible_module_bigip_facts.py", line 1682, in main
    facts['virtual_server'] = generate_vs_dict(f5, regex)
  File "/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_XJ8kBE/ansible_module_bigip_facts.py", line 1475, in generate_vs_dict
    return generate_dict(virtual_servers, fields)
  File "/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_XJ8kBE/ansible_module_bigip_facts.py", line 1386, in generate_dict
    api_response = getattr(api_obj, "get_" + field)()
  File "/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_XJ8kBE/ansible_module_bigip_facts.py", line 512, in get_description
    return self.api.LocalLB.VirtualServer.get_description(self.virtual_servers)
  File "/Library/Python/2.7/site-packages/bigsuds.py", line 498, in wrapped_method
    return result_processor.process(result)
  File "/Library/Python/2.7/site-packages/bigsuds.py", line 660, in process
    return self._convert_to_native_type(value)
  File "/Library/Python/2.7/site-packages/bigsuds.py", line 664, in _convert_to_native_type
    return [self._convert_to_native_type(x) for x in value]
  File "/Library/Python/2.7/site-packages/bigsuds.py", line 673, in _convert_to_native_type
    return str(value)

fatal: [adc-003.xx.com -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "filter": null,
            "include": [
                "virtual_server"
            ],
            "partition": "Common",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "server": "adc-003.xx.com",
            "server_port": 443,
            "session": false,
            "state": "present",
            "user": "cnsauto",
            "validate_certs": false
        }
    },
    "msg": "received exception: 'ascii' codec can't encode character u'\\xb0' in position 5: ordinal not in range(128)\ntraceback: Traceback (most recent call last):\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_XJ8kBE/ansible_module_bigip_facts.py\", line 1682, in main\n    facts['virtual_server'] = generate_vs_dict(f5, regex)\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_XJ8kBE/ansible_module_bigip_facts.py\", line 1475, in generate_vs_dict\n    return generate_dict(virtual_servers, fields)\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_XJ8kBE/ansible_module_bigip_facts.py\", line 1386, in generate_dict\n    api_response = getattr(api_obj, \"get_\" + field)()\n  File \"/var/folders/ps/5t3ydcjx1771_y9fp80ycg4wv4q8gs/T/ansible_XJ8kBE/ansible_module_bigip_facts.py\", line 512, in get_description\n    return self.api.LocalLB.VirtualServer.get_description(self.virtual_servers)\n  File \"/Library/Python/2.7/site-packages/bigsuds.py\", line 498, in wrapped_method\n    return result_processor.process(result)\n  File \"/Library/Python/2.7/site-packages/bigsuds.py\", line 660, in process\n    return self._convert_to_native_type(value)\n  File \"/Library/Python/2.7/site-packages/bigsuds.py\", line 664, in _convert_to_native_type\n    return [self._convert_to_native_type(x) for x in value]\n  File \"/Library/Python/2.7/site-packages/bigsuds.py\", line 673, in _convert_to_native_type\n    return str(value)\nUnicodeEncodeError: 'ascii' codec can't encode character u'\\xb0' in position 5: ordinal not in range(128)\n"
}
	to retry, use: --limit @/Users/naran.khetani/drive/scripts/projects/xx/cns-ansible/playbooks/audits/f5_irule_verification.retry

PLAY RECAP ************************************************************************************************************************
adc-003.xx.com : ok=0    changed=0    unreachable=0    failed=1
```
