### ISSUE TITLE
yum module doesn't detect package updates anymore

### ISSUE THREAD

**Issue by moss2k13** [ansible/ansible#31412]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

yum module
##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```
##### OS / ENVIRONMENT

```
CentOS Linux release 7.3.1611 (Core)
Linux upgradeVM 3.10.0-514.21.1.el7.x86_64 #1 SMP Thu May 25 17:04:51 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

After updating ansible to 2.4.0 I see that `yum` module is not updating packages anymore

##### STEPS TO REPRODUCE

Using local repos and below test playbook:

```yaml
---
- hosts: controller
  tasks:
    - name:         update ceilometer
      yum:
        name:       openstack-ceilometer-common
        state:      latest
      become:       true
```

##### EXPECTED RESULTS

Using ansible 2.3.2 it works as expected:
```yaml
changed: [node1] => {
    "changed": true,
    "changes": {
        "installed": [],
        "updated": [
            [
                "openstack-ceilometer-common",
                "1:8.1.0-1.el7.noarch from local-repo"
            ]
        ]
    },
    "invocation": {
        "module_args": {
            "conf_file": null,
            "disable_gpg_check": false,
            "disablerepo": null,
            "enablerepo": null,
            "exclude": null,
            "install_repoquery": true,
            "installroot": "/",
            "list": null,
            "name": [
                "openstack-ceilometer-common"
            ],
            "skip_broken": false,
            "state": "latest",
            "update_cache": false,
            "validate_certs": true
        }
    },
    "msg": "",
    "rc": 0,
    "results": []
}
```

##### ACTUAL RESULTS

Using ansible 2.4.0 it doesn't install updates:

```yaml
ok: [node1] => {
    "changed": false,
    "changes": {
        "installed": [],
        "updated": []
    },
    "failed": false,
    "invocation": {
        "module_args": {
            "allow_downgrade": false,
            "conf_file": null,
            "disable_gpg_check": false,
            "disablerepo": null,
            "enablerepo": null,
            "exclude": null,
            "install_repoquery": true,
            "installroot": "/",
            "list": null,
            "name": [
                "openstack-ceilometer-common"
            ],
            "security": false,
            "skip_broken": false,
            "state": "latest",
            "update_cache": true,
            "validate_certs": true
        }
    },
    "msg": "",
    "rc": 0,
    "results": [
        "All packages providing openstack-ceilometer-common are up to date"
    ]
}
```
And I have available updates for the node1 from local repos:
```bash
[root@node1 ~]# yum repolist
repo id                                                                                repo name                                                                                                      status
InstallMedia                                                                           Red Hat Enterprise Linux 7.3                                                                                   4,986
local-repo                                                                             local repostory for simple update                                                                                929
[root@node1 ~]# yum list installed openstack-ceilometer-common
Installed Packages
openstack-ceilometer-common.noarch                                         1:6.1.3-2.el7.mitaka.v2.1.1
[root@node1 ~]# yum check-update openstack-ceilometer-common
openstack-ceilometer-common.noarch                                               1:8.1.0-1.el7
[root@node1 ~]# yum list available openstack-ceilometer-common
Available Packages
openstack-ceilometer-common.noarch                                               1:8.1.0-1.el7
```
