### ISSUE TITLE
meta refresh_inventory does not update dynamic inventory

### ISSUE THREAD

**Issue by aroundthecode** [ansible/ansible#31411]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
task meta: refresh inventory
##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
I'm using a dynamic inventory which insert additional servers only if available to ping 
```
#!/bin/bash

PINGLIST=( "192.168.10.125" )
STATICLIST=( "192.168.10.10" )

HOSTLIST=""

for i in "${STATICLIST[@]}"
do
	HOSTLIST="\"${i}\",${HOSTLIST}"
done

for i in "${PINGLIST[@]}"
do
	ping -c1 -W3 ${i} > /dev/null 2>&1
	if [ "$?" == "0" ]
	then
		HOSTLIST="\"${i}\",${HOSTLIST}"
	fi
done

echo "{\
     \"all\": {\
        \"hosts\": [${HOSTLIST%?}],\
        \"vars\": { \"ansible_ssh_user\":\"fladmin\" }\
    }\
}"
```

##### OS / ENVIRONMENT
CentOS Linux release 7.4.1708 (Core)

##### SUMMARY
I'm running a playbook suing above dynamic inventory and invoking meta/refresh_inventory to forece inventory reload.
This was working fine with ansible 2.1.2.0 and 2.2.2.0.
After updating to 2.3.2.0 it seems that meta/refresh_inventory is no more updating the inventory.

If the server is absent at playbook start, refresh_inventory can't add it and then all subsequent task are skipping.

If the server is present at playbook start all task run propertly

##### STEPS TO REPRODUCE
Can't share since the task before refresh_inventory is connecting to our internal VSphere to create the needed server which should join the inventory afterward.

```yaml
## Reconfigure IP at OS level
- hosts: "192.168.10.125"
  gather_facts: False
  tasks:
    - name: "Check if a template machine is already present"
      ping:
      register: template_running

    - name: "Fail if a template machine is already present"
      fail:
        msg: "Template IP machine detected: stopping procedure!"
      when: template_running|success


## Create the VM on VSphere from template on default IP
- hosts: "localhost"
  connection: local
  roles:
    - { role: vsphere, vm_name: "{{ server_name }}" }
    
  tasks:
    - name: "Refresh inventory to ensure new instaces exist in inventory"
      meta: refresh_inventory

## Reconfigure IP at OS level
- hosts: "192.168.10.125"
  become: True
  roles:
     - { role: hostname_net_change, myip: "{{ server_ip }}", myhostname: "{{ server_name }}" }
```

##### EXPECTED RESULTS
meta/refresh_inventory should re-evaluate dynamic inventory and detect the newly created server

##### ACTUAL RESULTS
 meta/refresh_inventory runs but task on the new server are skipped

```
TASK [vsphere : Virtual Machine Data] ******************************************
ok: [localhost] => {
    "msg": {
        "changed": true, 
        "failed": false, 
        "instance": {
            "annotation": "", 
            "current_snapshot": null, 
            "customvalues": {}, 
            "guest_tools_status": "...", 
            "guest_tools_version": "...", 
            "hw_eth0": {
                "addresstype": "assigned", 
                "ipaddresses": null, 
                "label": "Network adapter 1", 
                "macaddress": "...", 
                "macaddress_dash": "...", 
                "summary": "VM Network"
            }, 
            "hw_guest_full_name": null, 
            "hw_guest_id": null, 
            "hw_interfaces": [
                "..."
            ], 
            "hw_memtotal_mb": .., 
            "hw_name": "...", 
            "hw_power_status": "poweredOn", 
            "hw_processor_count": .., 
            "hw_product_uuid": "...", 
            "ipv4": null, 
            "ipv6": null, 
            "module_hw": true, 
            "snapshots": []
        }
    }
}
META: inventory successfully refreshed
META: ran handlers
META: ran handlers

PLAY [192.168.10.125] **************************************************************
skipping: no hosts matched
```
