### ISSUE TITLE
ansible add_host module ignoring the when condition. Has this been resolved in 2.4 or continues to be same.

### ISSUE THREAD

**Issue by prateekj201** [ansible/ansible#31464]
`<!---`
Verify first that your issue/request is not already reported on GitHub.
Also test if the latest release, and master branch are affected too.
-->
Verified
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

add_host module
##### ANSIBLE VERSION

```
ansible 2.2.0
```

##### CONFIGURATION

No settings changed in ansible.cfg
##### OS / ENVIRONMENT

All environments
##### SUMMARY

Ansible add_host module ignoring the when condition. The task continues to execute in the way as without the when condition. 
##### STEPS TO REPRODUCE

```
    - name: add them to update-host-group
      when: ( environment is defined )
      add_host:
        name: "{{ item }}"
        groupname: update-host-group
      with_items:
          - "{{ asgs.instances[0].public_ip_address }}"

    - name: add them to update-host-group
      when: ( environment == 'production' )
      add_host:
        name: "{{ item }}"
        groupname: update-host-group
      with_items:
          - "{{ asgs.instances[1].public_ip_address }}"

```

##### EXPECTED RESULTS

Skipped
##### ACTUAL RESULTS

Failed

```
fatal: [127.0.0.1]: FAILED! => {
    "failed": true, 
    "msg": "list object has no element 1"
}

```
