### ISSUE TITLE
incompatible change in copy resultset in 2.4

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#31477]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
copy

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/phil/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
Between ansible 2.3.2 to 2.4.0 the `results` array of the `copy` module has changed in an incompatible way regarding `path` and `dest`.

##### STEPS TO REPRODUCE
1. `ansible-playbook copy.yml`

```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: "cleanup"
      command: "rm -rf /tmp/ansibleresults"
      args:
        warn: no

    - name: "create directory structure"
      file: path={{item}} state=directory
      with_items:
        - /tmp/ansibleresults
        - /tmp/ansibleresults/src
        - /tmp/ansibleresults/dest

    - name: "create some dummy files"
      copy: content="I am a dummy file {{item}}" dest=/tmp/ansibleresults/src/myfile{{item}}
      with_items: [ 1,2,3,4 ]

    - name: "pre-copy a file"
      copy: src=/tmp/ansibleresults/src/myfile3 dest=/tmp/ansibleresults/dest/

    - name: "copy all source files"
      copy: src={{item}} dest=/tmp/ansibleresults/dest/
      register: t_copyresults
      with_fileglob:
        - /tmp/ansibleresults/src/*

    - name: "show attribute 'dest'"
      debug: var=item
      with_items:
        - '{{t_copyresults.results|map(attribute="dest")|list}}'
```

##### EXPECTED RESULTS
```
TASK [show attribute 'dest'] ***
ok: [localhost] => (item=/tmp/ansibleresults/dest/myfile4) => {
    "item": "/tmp/ansibleresults/dest/myfile4"
}
ok: [localhost] => (item=/tmp/ansibleresults/dest/myfile3) => {
    "item": "/tmp/ansibleresults/dest/myfile3"
}
ok: [localhost] => (item=/tmp/ansibleresults/dest/myfile2) => {
    "item": "/tmp/ansibleresults/dest/myfile2"
}
ok: [localhost] => (item=/tmp/ansibleresults/dest/myfile1) => {
    "item": "/tmp/ansibleresults/dest/myfile1"
}
```

##### ACTUAL RESULTS
```
TASK [show attribute 'dest'] ***
ok: [localhost] => (item=[u'/tmp/ansibleresults/dest/myfile4', Undefined, u'/tmp/ansibleresults/dest/myfile2', u'/tmp/ansibleresults/dest/myfile1']) => {
    "item": "[u'/tmp/ansibleresults/dest/myfile4', Undefined, u'/tmp/ansibleresults/dest/myfile2', u'/tmp/ansibleresults/dest/myfile1']"
}
```
