### ISSUE TITLE
ldap_attr fails with meaningless error

### ISSUE THREAD

**Issue by Phill93** [ansible/ansible#31475]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ldap_attr
##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/xxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

empty

##### OS / ENVIRONMENT

macOS 10.12 to Debian 8 Vagrant VM

##### STEPS TO REPRODUCE

The following task fails with the message "Cannot search for attribute olcRootDN" but the Attribute exists.

```yaml
- name: "Set rootDN at {{ item.suffix }}"
        ldap_attr:
          dn: "olcDatabase={{ item.olcDatabase }},cn=config"
          name: olcRootDN
          values: "{{ item.rootDN }}"
          state: exact
```

##### EXPECTED RESULTS

Update of the Attribute olcRootDN
##### ACTUAL RESULTS

The Tasks fails with the message "Cannot search for attribute"

```
fatal: [debian]: FAILED! => {
    "changed": false,
    "details": "{'desc': 'No such object'}",
    "failed": true,
    "invocation": {
        "module_args": {
            "bind_dn": null,
            "bind_pw": "",
            "dn": "olcDatabase={0}config,cn=config",
            "name": "olcRootDN",

            "params": null,
            "server_uri": "ldapi:///",
            "start_tls": false,
            "state": "exact",
            "validate_certs": true,
            "values": "cn=admin,cn=config"
        }
    },
    "msg": "Cannot search for attribute olcRootDN"
}
```
