### ISSUE TITLE
datadog_monitor does not parse query 

### ISSUE THREAD

**Issue by tharun-allu** [ansible/ansible#31488]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

datadog_monitor
##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### OS / ENVIRONMENT

x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

When running the playbook with the following query it errors out with query invalid but upon using the upstream api and running the same works with no issues.
##### STEPS TO REPRODUCE

run the playbook every time produces the error

```yaml
 - name: Create DD monitor
    datadog_monitor:
      name: Test Monitor JVM status
      type: "metric alert"
      state: present
      query: "avg(last_1m):avg:jvm.mem.heap_used{*} by {host} == 0"
      message: "Host [[host.name]]  with IP [[host.ip]] was unable to get JVM status."
      api_key: "{{ api_key }}"
      app_key: "{{ app_key }}"
```

##### EXPECTED RESULTS

A monitor being create on datadog

##### ACTUAL RESULTS

```yaml
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "api_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "app_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "escalation_message": null, 
            "id": null, 
            "locked": false, 
            "message": "Host [[host.name]] with IP [[host.ip]] was unable to get JVM status.", 
            "name": "Test Monitor JVM status", 
            "new_host_delay": null, 
            "no_data_timeframe": null, 
            "notify_audit": false, 
            "notify_no_data": false, 
            "query": "avg(last_1m):avg:jvm.mem.heap_used.over{*} ==0  by {host}", 
            "renotify_interval": null, 
            "require_full_window": null, 
            "silenced": null, 
            "state": "present", 
            "tags": null, 
            "thresholds": null, 
            "timeout_h": null, 
            "type": "metric alert"
        }
    }, 
    "msg": "[\"The value provided for parameter 'query' is invalid\"]"
}
```

```

```

This following code works if run directly 

```python
from datadog import initialize, api 

options = { 
    'api_key': 'MyApiKey',
    'app_key': 'MyAppKey'
}

initialize(**options)

api.Monitor.create(type="metric alert", query="avg(last_1m):avg:jvm.mem.heap_used{*} by {host} == 0", name="Test Monitor JVM status", message="Host with name {{host.name}} with IP {{host.ip}} was unable to get JVM status.",options=options)
~                                                                                                              
```
