### ISSUE TITLE
Controlling output for ansible iteration

### ISSUE THREAD

**Issue by nickrusso42518** [ansible/ansible#31503]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
with_* (with_items, with_together, with_nested ... any iterator )

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules/']
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
ansible.cfg modification:
forks = 20
gathering = explicit
host_key_checking = false
timeout = 60
vault_password_file = ~/.ansible/vault-pass.txt
retry_files_enabled = false

##### OS / ENVIRONMENT
AWS AMI Centos7 instance: Linux ip-10-125-0-100.ec2.internal 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY
When iterating over complex data structures, ansible iterators __always__ dump extensive output, often pretty-printing JSON to stdout. This should be controllable in a more granular way than the extreme "no_log" option, which provides no output.

##### STEPS TO REPRODUCE
Suggested fix: Include a `body` option under `loop_control` which operates similarly to `label`. If defined, this `body` variable is written after the ` => ` text. Support for no body should also be available for very terse use-cases. When body is set to no/false, no additional output past the item label should be displayed. The two code examples below detail these two potential cases.

```
# Customize body
- hosts: my_group
  tasks:
  - module_name:
      action: {{ item }}
    with_items: "{{ people }}"
    loop_control:
      label: "{{ item.first }}"
      body: "{{ item.last }}"

# Suppress body entirely
- hosts: my_group
  tasks:
  - module_name:
      action: {{ item }}
    with_items: "{{ people }}"
    loop_control:
      label: "{{ item.first }}"
      body: no
```

##### EXPECTED RESULTS
Outputs are written with respect to the YAML samples above.

```
# Customize body
TASK [module_name] ****************************
ok: [host1] => (item=John) => "Smith"
ok: [host1] => (item=Sam) => "Adams"

# Suppress body entirely
TASK [module_name] ****************************
ok: [host1] => (item=John)
ok: [host1] => (item=Sam)
```

##### ACTUAL RESULTS
No such "body" option exists, and when omitted, the output looks like this.

```
TASK [module_name] ***********************
ok: [host1] => (item=John) => {
    "changed": false, 
    "item": {
        "changed": false, 
        "invocation": {
            "module_args": {
                "auth_pass": null, 
                "authorize": null, 
                (snip, very long JSON output)
```

When `no_log: yes` is applied, the output is too terse to be useful, where even the customized `label` is not visible.

```
TASK [module_name] *******************************
ok: [host1] => (item=(censored due to no_log)) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}
```
