### ISSUE TITLE
subversion module doesn't handle quotes in passwords

### ISSUE THREAD

**Issue by drfickle** [ansible/ansible#3153]
When using an SVN password with a single quote in it, a task such as 
- name: Checkout Repositories
  subversion: repo=${item.repo} dest=${item.dest} username=${MY_SVN_USERNAME} password=${MY_SVN_PASSWORD} 

you get an exception. MY_SVN_\* comes from a vars_files entry.

fatal: [10.0.1.117] => failed to parse: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-1370634928.18-243497240203899/subversion", line 1083, in <module>
    main()
  File "/root/.ansible/tmp/ansible-1370634928.18-243497240203899/subversion", line 147, in main
    supports_check_mode=True
  File "/root/.ansible/tmp/ansible-1370634928.18-243497240203899/subversion", line 338, in **init**
    (self.params, self.args) = self._load_params()
  File "/root/.ansible/tmp/ansible-1370634928.18-243497240203899/subversion", line 820, in _load_params
    items   = shlex.split(args)
  File "/usr/lib/python2.7/shlex.py", line 279, in split
    return list(lex)
  File "/usr/lib/python2.7/shlex.py", line 269, in next
    token = self.get_token()
  File "/usr/lib/python2.7/shlex.py", line 96, in get_token
    raw = self.read_token()
  File "/usr/lib/python2.7/shlex.py", line 172, in read_token
    raise ValueError, "No closing quotation"
ValueError: No closing quotation

**Comment by stoned** [comment]
You should be safe writing something like password={{MY_SVN_PASSWORD|quote}}

**Comment by mpdehaan** [comment]
I think that is going to have to be the solution here when the input can't be split by the shell interpreter.   I am leaving this open in case we can do something cleaner with reporting though to give the end user a hint.

**Comment by drfickle** [comment]
With Ansible 1.2 this doesn't appear to work. It's getting expanded out to 

```
--password '{{MY_SVN_PASSWORD|quote}}'
```

i.e. not processing the variable.

Here's a snippet from my task

```
- name: Ensure All SVN Repos Are Up To Date
  subversion: repo=${item.repo} dest=${item.dest} username=${MY_SVN_USERNAME} password={{MY_SVN_PASSWORD|quote}}
  with_items:
    - repo: ${REPO_URL}branches/foo
      dest: /root/bin
  ...
```
