### ISSUE TITLE
Timezone module crash on Debian

### ISSUE THREAD

**Issue by VojtechMyslivec** [ansible/ansible#31547]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

timezone module

##### ANSIBLE VERSION

```
ansible 2.4.1.0 (detached HEAD 6dab8b7bfa) last updated 2017/10/10 17:22:27 (GMT +200)
  config file = ./ansible.cfg
  configured module search path = [u'~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = ~/bin/ansible/lib/ansible
  executable location = ~/bin/ansible/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(./ansible.cfg) = True
ANSIBLE_PIPELINING(./ansible.cfg) = True
CACHE_PLUGIN(./ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(./ansible.cfg) = /tmp/ansible_facts_cache
CACHE_PLUGIN_TIMEOUT(./ansible.cfg) = 7200
DEFAULT_CALLBACK_PLUGIN_PATH(./ansible.cfg) = [u'./callbacks']
DEFAULT_FORKS(./ansible.cfg) = 25
DEFAULT_GATHERING(./ansible.cfg) = smart
DEFAULT_HOST_LIST(./ansible.cfg) = [u'./hosts']
DEFAULT_LOCAL_TMP(./ansible.cfg) = /tmp/.ansible/tmp/ansible-local-23786Za29YN
DEFAULT_REMOTE_TMP(./ansible.cfg) = /tmp/.ansible_$USER/tmp
DEFAULT_ROLES_PATH(./ansible.cfg) = [u'./roles', u'./shared-roles']
DEFAULT_VAULT_PASSWORD_FILE(./ansible.cfg) = ./vault.sh
RETRY_FILES_ENABLED(./ansible.cfg) = False
```

##### OS / ENVIRONMENT

Running Ansible on Debian Buster (testing) and managing Ubuntu Xenial (16.04 LTS) and Debian Stretch (9.2, stable). 

##### SUMMARY

Timezone module is unable to change and set system timezone.

##### STEPS TO REPRODUCE

```yaml
- name: Configure timezone     
  timezone:
    name: 'Europe/Prague'
```

##### EXPECTED RESULTS

changed / ok

##### ACTUAL RESULTS

```
fatal: [logging.turris.cz]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "hwclock": null, 
            "name": "Europe/Prague"
        }
    }, 
    "msg": "Error message:\nstill not desired state, though changes have made\nOther message(s):\nAdded 1 line and deleted 1 line(s) on /etc/timezone"
}
```

Detail log in the [file](https://github.com/ansible/ansible/files/1373300/ansible.log)

##### REASON AND WORKAROUND

The [module is calling](../blob/v2.4.1.0-0.2.beta2/lib/ansible/modules/system/timezone.py#L329) `dpkg-reconfigure`, but this will overwrite `/etc/timezone` in recent Debian versions.

Based on this [discussion](https://bugs.launchpad.net/ubuntu/+source/tzdata/+bug/1554806) the desired state is achieved by deleting symlink `/etc/localtime` before running `dpkg-reconfigure`.

I can workaround the `timezone` module by following playbook:

```yaml
---
- name: Set timezone on servers
  hosts: all 

  vars:
    timezone: 'Europe/Prague'

  handlers:
    - name: Remove localtime
      file:
        dest: '/etc/localtime'
        state: absent

    - name: Update timezone
      command: |
        dpkg-reconfigure -f noninteractive tzdata

  tasks:
    - name: Configure timezone
      copy:
        content: "{{ timezone }}\n"
        dest: '/etc/timezone'
      notify:
        - Remove localtime
        - Update timezone

...
```
