### ISSUE TITLE
any_errors_fatal ignored if error occurs in block with always

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#31543]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
play_iterator

##### ANSIBLE VERSION
2.4.1

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### SUMMARY
`any_errors_fatal: true` behavior is ignored if the error occurs in a block with an `always` element specified. 

##### STEPS TO REPRODUCE

(repro,yml)
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
  - add_host:
      name: h1
      ansible_connection: local
  - add_host:
      name: h2
      ansible_connection: local
      exitcode: 2

- hosts: h1:h2
  gather_facts: no
  tasks:
  - block:
    - shell: exit {{ exitcode | default(0) }}
    - debug: msg="still executing in block"
    always:
    - debug: msg="executing in always"
    any_errors_fatal: yes

  - debug: msg="still executing outside block"
```

##### EXPECTED RESULTS
Playbook execution stops after `always` block, "still executing in block" debug message not displayed

##### ACTUAL RESULTS
Playbook execution continues normally for hosts that did not fail.
