### ISSUE TITLE
Supporting loading hierarchical config in netcfg module

### ISSUE THREAD

**Issue by paulquack** [ansible/ansible#31568]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- module_utils/netcfg.py +label networking

##### SUMMARY

I'd like to find a way to support either hierarchical yaml structured `lines` parameter or loading of simple space indented config.

##### STEPS TO REPRODUCE

On a platform that I am developing a module for, I have the following configuration snippet that is commonly deployed. Currently this must be matched/configured as a complete block, rather than lines, as the typical config modules do not support such nesting of config commands. 
```
router mpls
 vll TEST123 123
  vll-peer 1.1.1.1
  vlan 10
   tagged ether 1/1
```

```yaml
---
 - name: "ios_config test"
   hosts: "ios"
   gather_facts: no
   connection: local
   tasks:
     - ios_config:
         lines:
            - "vll-peer 1.1.1.1"
            - "vlan 5":
                - "tagged ether 1/1"
         parents: [ "router mpls", "vll TEST123 123" ]
         provider: "{{ cli }}"
```
or 
```yaml
---
 - name: "ios_config test"
   hosts: "ios"
   gather_facts: no
   connection: local
   tasks:
     - ios_config:
         lines:
            - "vll-peer 1.1.1.1"
            - "vlan 5"
            - " tagged ether 1/1"
         parents: [ "router mpls", "vll TEST123 123" ]
         provider: "{{ cli }}"
```
The desired outcome is that, if for example the `tagged ether 1/1` line is missing, the module should deploy the lines:
```
router mpls
vll TEST123 123
vlan 5
tagged ether 1/1
```

I've got some code in mind for this, but wanted to validate the approach first... The follow implements the space intended option, but I feel the yaml structured version is potentially nicer/cleaner.
```python
    def add_load(self, lines, parents=None):
        config = list()
        offset = 0

        # global config command
        if not parents:
            self.load("\n".join(lines))
        else:
            for index, p in enumerate(parents):
                # add parent to config
                offset = index * self._indent
                config.append(p.rjust(len(p) + offset))

            for line in lines:
                # add lines to config
                offset = len(parents) * self._indent
                config.append(line.rjust(len(line) + offset))
            self.load("\n".join(config))
```

This potentially replaces the following function https://github.com/ansible/ansible/blob/88da95bb77cf20f56035e7ba5d0230c0a2785f2b/lib/ansible/module_utils/netcfg.py#L365-L408
