### ISSUE TITLE
Add a special 'all' tag that always matches

### ISSUE THREAD

**Issue by lalinsky** [ansible/ansible#3157]
The problem is that once you have a playbook that uses `group_by`, or possibly some other modules that define hosts or groups, you can't use `--tags` on the command line, because there is no way you can get the `group_by` play match (as far as I can see, maybe I'm wrong).

Let's say I have a playbook like this:

```
- hosts: all
  tasks:
    - name: Create a group of all hosts by operating system
      action: group_by key={{ansible_distribution}}

- hosts: Ubuntu
  tasks:
    - name: Install nginx
      action: apt name=nginx state=installed
      tags: nginx

- hosts: CentOS
  tasks:
    - name: Install nginx
      action: yum name=nginx state=installed
      tags: nginx
```

If I run this command, nothing actually gets executed, because the first play does not match the `nginx` tag:

```
ansible-playbook -i hosts --tags nginx
```

I'd suggest introducing a special syntax `tags: all` that would match any tag specified on the command line:

```
- hosts: all
  tasks:
    - name: Create a group of all hosts by operating system
      action: group_by key={{ansible_distribution}}
      tags: all
```

The only problem is that this is a backward-incompatible change, because people already might be using `all` as a regular tag.
