### ISSUE TITLE
ovirt_templates: wait parameter is ignored

### ISSUE THREAD

**Issue by pkubica** [ansible/ansible#31589]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ovirt_templates

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
rhel 7.4

##### SUMMARY

Importing template from export storage domain with parameter wait: yes
wait parameter is ignored

##### STEPS TO REPRODUCE

```yaml
    - name: import template
      ovirt_templates:
        state: imported
        name: exported_template
        export_domain: export
        storage_domain: storage
        cluster: Default
        auth: "{{ovirt_auth}}"
        wait: yes
```
