### ISSUE TITLE
win_reboot failed due to 'Connection' object has no attribute '_winrm_host'

### ISSUE THREAD

**Issue by taodong** [ansible/ansible#31599]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_reboot

##### ANSIBLE VERSION

```
2.2.1.0
```

##### OS / ENVIRONMENT

OS Sierra 10.12.6
##### SUMMARY

Ansible fails on win_reboot
##### STEPS TO REPRODUCE

```yaml
- name: Reboot windows
  win_reboot:
    pre_reboot_delay: 120
    shutdown_timeout: 120
```

##### EXPECTED RESULTS

Windows reboot
##### ACTUAL RESULTS

```
    amazon-ebs:     winrm_host = self._connection._winrm_host
    amazon-ebs: AttributeError: 'Connection' object has no attribute '_winrm_host'
    amazon-ebs: fatal: [windowsAdmin]: FAILED! => {
    amazon-ebs:     "failed": true,
    amazon-ebs:     "msg": "Unexpected failure during module execution.",
    amazon-ebs:     "stdout": ""
    amazon-ebs: }
```
