### ISSUE TITLE
file: add backup option

### ISSUE THREAD

**Issue by ebarrere** [ansible/ansible#31594]
##### ISSUE TYPE

 - Feature request

##### COMPONENT NAME

File module

##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.0 (devel af558698a0) last updated 2017/08/03 14:28:27 (GMT -600)
  config file = /home/elliott.barrere/dv-ansible/ansible.cfg
  configured module search path = [u'/home/elliott.barrere/dv-ansible/library']
  ansible python module location = /opt/ansible/source/lib/ansible
  executable location = /opt/ansible/source/bin/ansible
  python version = 2.7.9 (default, Nov 18 2015, 13:07:23) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```

##### SUMMARY

File module using `backup=yes` does not back the file up prior to deletion.

##### STEPS TO REPRODUCE

```yaml
- name: remove legacy repo
  file: dest=/etc/yum.repos.d/old.repo state=absent backup=yes
  register: new_conf                                                             
  notify:                                                                       
    - central backup
```

##### EXPECTED RESULTS

File is backed up.

##### ACTUAL RESULTS

File is NOT backed up, however the module appears to recognize the `backup=yes` directive.

```
changed: [bom1pmon01] => {
    "changed": true, 
    "diff": {
        "after": {
            "path": "/etc/yum.repos.d/old.repo", 
            "state": "absent"
        }, 
        "before": {
            "path": "/etc/yum.repos.d/old.repo", 
            "state": "file"
        }
    }, 
    "failed": false, 
    "invocation": {
        "module_args": {
            "attributes": null, 
            **"backup": "yes",** 
            "content": null, 
            "delimiter": null, 
            "dest": "/etc/yum.repos.d/old.repo", 
            "diff_peek": null, 
            "directory_mode": null, 
            "follow": false, 
            "force": false, 
            "group": null, 
            "mode": null, 
            "original_basename": null, 
            "owner": null, 
            "path": "/etc/yum.repos.d/old.repo", 
            "recurse": false, 
            "regexp": null, 
            "remote_src": null, 
            "selevel": null, 
            "serole": null, 
            "setype": null, 
            "seuser": null, 
            "src": null, 
            "state": "absent", 
            "unsafe_writes": null, 
            "validate": null
        }
    }, 
    "path": "/etc/yum.repos.d/old.repo", 
    "state": "absent"
}

# from the host:
[root@impacted_host ~]# ll /etc/yum.repos.d/old.repo.*
ls: cannot access /etc/yum.repos.d/old.repo.*: No such file or directory

```
