### ISSUE TITLE
Kubernetes Module throws errors on all 422 responses, affecting idempotency 

### ISSUE THREAD

**Issue by kevintpeng** [ansible/ansible#31602]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Kubernetes Module

##### ANSIBLE VERSION

```
$ ansible --version                   
ansible 2.2.0.0          
  config file = /home/kevintpeng/ans-playbook/ansible.cfg                                    
  configured module search path = Default w/o override
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Service creation is not idempotent with some valid specifications. In this example, the service is created fine the first time, but when the play is run a second time, the task throws an error.

I am creating a kubernetes service object, asking for `state: present`. [This is the file that I am using](https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/addons/dns/skydns-svc.yaml.sed) for the object creation.

Some create calls return HTTP 422 when an object exists in kubernetes, where the module is expecting an HTTP 409. In my case, this is because I've specified a cluster IP parameter, the API complains that the IP address is already in use (presumably by the existing object created in a prior play). 

Any suggestions for avoiding the 422 in the first place would be appreciated!

##### STEPS TO REPRODUCE

[This is the file that I am using](https://github.com/kubernetes/kubernetes/blob/release-1.5/cluster/addons/dns/skydns-svc.yaml.sed) for the object creation. This is the task:

```yaml
- name: create skydns service                     
  kubernetes:                                     
    api_endpoint: "{{ dns_master }}"              
    insecure: true                                
    inline_data:                                               
      apiVersion: v1                                                       
      kind: Service                               
      metadata:                                   
        name: kube-dns                                          
        namespace: kube-system                    
        labels:                                   
          k8s-app: kube-dns                       
          kubernetes.io/cluster-service: "true"                 
          kubernetes.io/name: "KubeDNS"           
      spec:                                       
        selector:                                 
          k8s-app: kube-dns                       
        clusterIP: "10.254.254.254"               
        ports:                                    
        - name: dns                               
          port: 53                                                                                   
          protocol: UDP                                    
        - name: dns-tcp                           
          port: 53                                
          protocol: TCP                           
    state: present       
```

Running this task twice should reproduce the error.

##### EXPECTED RESULTS

I expect that the task to pass if the service is already present on the system.

##### ACTUAL RESULTS

Instead, the HTTP 422 response to the `create` POST request throws an error from ansible instead of receiving a 409 conflict. Using the URI module to hit the same endpoint yields the error "ip address already allocated".

Result of the play at verbosity vvvv:
```
fatal: [kube-master-01]: FAILED! => {                                                      
    "changed": false,                                                                                                
    "failed": true,                                                                                  
    "invocation": {                                                                                                                                                                                        
        "module_args": {                                                                                                                                                                                   
            "api_endpoint": "127.0.0.1:8080",                                                                                                                                               
            "certificate_authority_data": null,   
            "file_reference": null,               
            "force_basic_auth": "yes",            
            "http_agent": "ansible-k8s-module/0.0.1",                                               
            "inline_data": "{'kind': 'Service', 'spec': {'clusterIP': '10.254.254.254', 'ports': [{'protocol': 'UDP', 'name': 'dns', 'port': 53}, {'protocol': 'TCP', 'name': 'dns-tcp', 'port': 53}], 'selector': {'k8s-app': 'kube-dns'}}, 'apiVersion': 'v1', 'metadata': {'labels': {'k8s-app': 'kube-dns', 'kubernetes.io/name': 'KubeDNS', 'kubernetes.io/cluster-service': 'true'}, 'namespace': 'kube-system', 'name': 'kube-dns'}}", 
            "insecure": true,                     
            "state": "present",                   
            "url_password": "",                   
            "url_username": "admin",              
            "validate_certs": false               
        },               
        "module_name": "kubernetes"               
    },                   
    "msg": "failed to create the resource: HTTP Error 422: Unprocessable Entity",  
    "url": "http://127.0.0.1:8080/api/v1/namespaces/kube-system/services/kube-dns"                   
}  
```

_edit, simplified example_
