### ISSUE TITLE
nxos_vlan issues warning about arguments even though arguments are not used

### ISSUE THREAD

**Issue by ktbyers** [ansible/ansible#31615]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_vlan

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/kbyers/.ansible.cfg
  configured module search path = [u'/home/kbyers/napalm-ansible/library', u'/home/kbyers/ansible-extras/ntc-ansible/library']
  ansible python module location = /home/kbyers/VENV/ans_2_4/local/lib/python2.7/site-packages/ansible
  executable location = /home/kbyers/VENV/ans_2_4/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]

```

##### SUMMARY

nxos_vlan module gives warning about arguments even though arguments not in use:

```
 [WARNING]: argument include_defaults is no longer supported, ignoring value

 [WARNING]: argument save is no longer supported, ignoring value
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Test NXOS VLAN
  hosts: nxos
  tasks:
    - name: Configure NEXUS VLANs
      nxos_vlan:
        provider: "{{ provider_nxapi }}"
        vlan_id: "{{ item.vlan_id }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans }}"

```

The arguments are probably embedded as defaults in the module. My playbook is not referring to them at all.

Module should be fixed so that warnings no longer appear.
