### ISSUE TITLE
Provide state: absent option in asa_config and asa_acl

### ISSUE THREAD

**Issue by Per-Forma** [ansible/ansible#31611]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
asa_config
asa_acl

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12+ (default, Sep 17 2016, 12:08:02) [GCC 6.2.0 20160914]

```

##### CONFIGURATION

root@ansible:/home/bocesadmin/playbooks# ansible-config dump --only-changed
root@ansible:/home/bocesadmin/playbooks#

##### OS / ENVIRONMENT

Running Ansible from Ubuntu 16.10
Running Ansible aganst ASA 9.8(1)

##### SUMMARY

I would like to see a `state:` option in the `asa_config` and `asa_acl` modules similar to some other ansible modules.

##### STEPS TO REPRODUCE

Similar to how the ansible `file` module can be run with a `state: absent` to delete a file, I would like to be able to use that option to delete configuration lines on an ASA. Given the tools available in the `asa_` modules I haven't been able to conceive of a way to do this with the currently available options. It might be possible to do an error handler and catch the error in order to then trigger a task to remove the config line in question. I think this would be messy to execute.

If implemented, the below example should remove the `host {{ inside_ip }}` from the ASA.

```yaml
   - name: Delete Network Object
     asa_config:
      lines:
       - host {{ inside_ip }}
      state: absent
      parents: ['object network {{ object_name }}']
      provider: "{{ cli }}"
     register: cno
```

##### EXPECTED RESULTS

N/A

##### ACTUAL RESULTS

N/A
