### ISSUE TITLE
Jira module in create mode fail with "HTTP Error 400: Bad Request"

### ISSUE THREAD

**Issue by Nir-Tal** [ansible/ansible#31627]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Jira

##### ANSIBLE VERSION
```
2.2.1.0
```

##### CONFIGURATION
```
[defaults]
transport = ssh
retry_files_enabled = False

[ssh_connection]
ssh_args = -o ForwardAgent=yes
```

##### OS / ENVIRONMENT

Debian 8.9
Jira cloud

##### SUMMARY
When running the jira module with create I'm getting "HTTP Error 400: Bad Request"

##### STEPS TO REPRODUCE
create var file with:
```yaml
  jira_server: "https://company.atlassian.net"
  jira_user: "jira user"
  jira_pass: "password"
```
Add the tasks and the var file to a new playbook and when running the playbook limit to a single host.
```yaml
      - name: Calculate due date
        command: "date '+%Y-%m-%d' -d '+182 days'"
        register: duedate
        delegate_to: localhost

      - name: Open Jira ticket to delete backups
        jira:
          uri: "{{ jira_server }}"
          username: "{{ jira_user }}"
          password: "{{ jira_pass }}"
          project: "ArchAssets"
          operation: "create"
          summary: "Finish {{ inventory_hostname }} Decommission"
          description: "Finish {{ inventory_hostname }} Decommission"
          issuetype: "Task"
        args:
          fields:
            customfield_11700: "The Customer has been deleted 6 monthes ago and we can delete all backups and config files"
            customfield_11701: "Delete {{ inventory_hostname }} backups from {{ sup_host_hostname }} and Ansible config files"
            duedate: "{{ duedate.stdout }}"
            components:
              - "DevOps"
            labels:
              - "instance-decomission"
        delegate_to: localhost
```

##### EXPECTED RESULTS

New ticket will be created

##### ACTUAL RESULTS

```
fatal: [host -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "assignee": null, 
            "comment": null, 
            "description": "Finish host Decommission", 
            "fields": {
                "components": [
                    "DevOps"
                ], 
                "customfield_11700": "The Customer has been deleted 6 monthes ago and we can delete all backups and config files", 
                "customfield_11701": "Delete host backups from sup_server and Ansible config files", 
                "duedate": "2018-04-11", 
                "labels": [
                    "instance-decomission"
                ]
            }, 
            "issue": null, 
            "issuetype": "Task", 
            "operation": "create", 
            "password": "%%%%%%%", 
            "project": "%%%%%%", 
            "status": null, 
            "summary": "Finish host Decommission", 
            "uri": "https://company.atlassian.net", 
            "username": "%%%%%%"
        }, 
        "module_name": "jira"
    }, 
    "msg": "HTTP Error 400: Bad Request"
}
```

**Comment by ansibot** [comment]
cc @Slezhuk @tarka
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Slezhuk** [comment]
@Nir-Tal , please verify, that your project allow creation issues with all custom fields you listed:
custom_field_*
component

You can start by creating issue manually, than check all fields at url: https://mycompany.atlassian.net/rest/api/2/issue/{ISSUEKEY}?fields&expand

**Comment by Nir-Tal** [comment]
Hey @Slezhuk, Thanks for the fast reply.
The user that creates the issue got the permissions (created an issue via the web interface) 
I checked that the API does show all the fields as you requested and all fields are present.
Any more ideas?

**Comment by Slezhuk** [comment]
I still think that there is some type mismatch with custom fields. Can you try to run your playbook with disabled fields: components, customfield_11700, customfield_11701, duedate?
Can you try to create issue manually, with all fields filled with same values as via ansible?

**Comment by Nir-Tal** [comment]
@Slezhuk all the fields are mandatory, it would fail for sure if I remove them. If you run it while changing the customfield_X numbers it works for you? 

On the same version of Ansible...

**Comment by Slezhuk** [comment]
I created new instance of jira in public cloud - it does not have custom fields you specified. Without them issue created properly. When i put unexistent field, jira fails with `400 bad request` response.

**Comment by Nir-Tal** [comment]
I'll triple check the fields.
the type is 'Text Field (multi-line)' and fields render is 'Wiki Style Renderer' can it be part of the problem?

**Comment by Nir-Tal** [comment]
@Slezhuk I'm starting to be really sure it's a bug or unsupported option of the Jira module.
```json
            "customfield_11700": {
              "required": true,
              "schema": {
                "type": "string",
                "custom": "com.atlassian.jira.plugin.system.customfieldtypes:textarea",
                "customId": 11700
              },
              "name": "Motivation",
              "key": "customfield_11700",
              "hasDefaultValue": false,
              "operations": [
                "set"
              ]
            },
            "customfield_11701": {
              "required": true,
              "schema": {
                "type": "string",
                "custom": "com.atlassian.jira.plugin.system.customfieldtypes:textarea",
                "customId": 11701
              },
              "name": "Requirements",
              "key": "customfield_11701",
              "hasDefaultValue": false,
              "operations": [
                "set"
              ]
            },
```
When running with curl:
```
curl -D- -u user:pass -X POST --data '{ "fields": { "project": { "key": "AR" }, "summary": "REST test 11111.", "description": "test", "issuetype": { "name": "Task" }, "customfield_11700": "test", "customfield_11701": "test" } }' -H "Content-Type: application/json" https://company.atlassian.net/rest/api/2/issue/
```
It works
```
{"id":"46707","key":"AR-2852","self":"https://company.atlassian.net/rest/api/2/issue/46707"}
```
Running the same task in Ansible fail with "HTTP Error 400: Bad Request"

**Comment by lktslionel** [comment]
Hi, 
I have the same issue when using the field `issuetype: Technical Hitch` in my play : 
```
  tasks:
    - name: "Create JIRA issue"
      jira:
        uri:        '{{ os_jira_server }}'
        username:   '{{ os_jira_user }}'
        password:   '{{ os_jira_pass }}'
        operation:  "create"
        ...
        issuetype: Technical Hitch
        ...
        fields:
          issuetype:
            id: "10800"
```

I looked into the [code](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/jira.py#L282-L283) and I saw that I could override the issuetype with the param `field` as follows : 
```
  tasks:
    - name: "Create JIRA issue"
      jira:
        ...
        fields:
          issuetype:
            id: "10800"
```
But I'm getting the `HTTP Error 400: Bad Request` error as a result of my task execution.

**Comment by enarmontas** [comment]
I have this issue on custom fields that are User Picker or any other non plain text field.

**Comment by jameslcd** [comment]
Hi guys! I would just like to ask if you've already solved this problem? I am also currently using custom fields in Jira and I am now facing the "HTTP Error 400: Bad request". If you've already solve this can you please enlighten me? Thank you very much!

**Comment by Mixer9** [comment]
@maxamillion Hey @tarka or @Slezhuk I am also having this issue, when I attempt to use the custom field added for the Insight plugin to Jira, it is not a plain text field, it is a lookup type field. here is an excerpt from Jira for the field in question:
`"customfield_11502":["VALTXNC01 (GSOC-1368)"]`
this is output of an existing issue.

Here is the output of https://myserver.com:8443/rest/api/2/field
`"id":"customfield_11502","name":"Affected Asset","custom":true,"orderable":true,"navigable":true,"searchable":true,"clauseNames":["Affected Asset","cf[11502]"],"schema":{"type":"any","custom":"com.riadalabs.jira.plugins.insight:rlabs-customfield-object-multi","customId":11502}`

I have tried several options and none seem to work. Here is a snippet of my code.  If I comment out the custom field everything works as expected and a ticket is created, with the custom field I get the HTTP 400 error. See below job info.

``` - name: Create a jira issue
    jira:
      validate_certs: false
      uri: '{{ jira_server }}'
      username: '{{ network.jirauser }}'
      password: '{{ network.jirapass }}'
      operation: create
      project: TPS
      issuetype: 'Change - Normal'
      summary: "{{ mysummary }}"
      description: "{{ mydescription }}"
      assignee: "{{ tower_user_name }}"
    args:
      fields:
        labels:
          - autocreated
          - ansible
        customfield_11502:
          - VALTXNC01
```

**Error 400 output.**
```{
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "username": "ansible",
            "status": null,
            "description": "Created ticket to test from ansible",
            "validate_certs": false,
            "fields": {
                "assignee": {
                    "name": "v683653"
                },
                "customfield_11502": [
                    "VALTXNC01"
                ],
                "labels": [
                    "autocreated",
                    "ansible"
                ]
            },
            "outwardissue": null,
            "uri": "https://soctxsvn02.gsoc.verizon.com:8443",
            "comment": null,
            "summary": "Created ticket to test from ansible",
            "project": "TPS",
            "assignee": "v683653",
            "inwardissue": null,
            "timeout": 10,
            "issuetype": "Change - Normal",
            "linktype": null,
            "operation": "create",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "issue": null
        }
    },
    "msg": "HTTP Error 400: "
}
```

I can provide any other information you may need.

**Comment by dkarakas1** [comment]
I was having a similar issue as @Mixer9 and later realized that I wasn't formatting my 'fields:' section correctly for a multiselect custom field.  

I wonder @Mixer9 if you would have success with this small modification:

```
  args:
      fields:
        labels:
          - autocreated
          - ansible
        customfield_11502:
           value: "VALTXNC01"
```
Note: Its possible the correct key name is not 'value' but rather some other name that has been defined.  To be sure, you'll want to view the entire structure of the custom field customfield_11502.

In my case I ended up dumping the entire Project/Fields JSON structure following guidance from here:

https://confluence.atlassian.com/jirakb/how-to-retrieve-available-options-for-a-multi-select-customfield-via-jira-rest-api-815566715.html

Example:

```curl --user user@domain.com:'PASSWORD' --header 'Accept: application/json' --url 'https://customerdomain.atlassian.net/rest/api/2/issue/createmeta?expand=projects.issuetypes.fields'|jq .|less```

I was then able to see the expected structure I needed to POST via ansible Jira module's 'args->fields'.  I was stumbling around until I realized I needed to include the key in addition to the value.  Literally the key named "value" had to be included based on my object structure.

In my case, this now works for me:

```
  - name: Create Test CM
    jira:
      uri: https://ourdomain.atlassian.net
      username: "{{jira_user}}"
      password: "{{jira_pass}}"
      project: CM
      operation: create
      summary: "Test Ticket Creation via Ansible"
      description: "Test - Ansible Ticket Creation"
      issuetype: 'Change Management'
      assignee: "karakas"
    args:
      fields:
        reporter:
          name: "karakas"
        labels:
          - ansible-tower
          - geoip_update
        customfield_13401:
          value: "All BIG-IPs"
        customfield_10200: "https://ourdomain.atlassian.net/wiki/x/XgANG"
        customfield_10506: "https://ourdomain.atlassian.net/wiki/x/XgANG"
        customfield_11401: "BI/BIT/BIM/BIG Production BIG-IPs in all DataCenters"
    register: jira_issue
```
The 

customfield_13401:
**value:** "All BIG-IPs"

bit is a multi-select custom field that has about 15 valid values users select from a dropdown list.  That curl command will also return the 'allowedValues' of your custom field.  The strings must match in your ansible task.

```
},
"customfield_13401": {
  "required": true,
  "schema": {
    "type": "option",
    "custom": "com.atlassian.jira.plugin.system.customfieldtypes:select",
    "customId": 13401
  },
  "name": "Sub-System",
  "key": "customfield_13401",
  "hasDefaultValue": false,
  "operations": [
    "set"
  ],
  "allowedValues": [
    {
      "self": "https://ourdomain.atlassian.net/rest/api/2/customFieldOption/11800",
      "value": "AAA",
      "id": "11800"
    },
    {
      "self": "https://ourdomain.atlassian.net/rest/api/2/customFieldOption/11811",
      "value": "Adgrex",
      "id": "11811"
    },
    {
      "self": "https://ourdomain.atlassian.net/rest/api/2/customFieldOption/11511",
      "value": "All BIG-IPs",
      "id": "11511"
    },
    {
      "self": "https://ourdomain.atlassian.net/rest/api/2/customFieldOption/11507",
      "value": "Ansible Tower",
      "id": "11507"
    },
    ...

```
You might also notice in my working task, that I've included the field 'reporter'
```
    args:
      fields:
        reporter:
          name: "karakas"
```
Like my multi-select list, this field required the key 'name' be included to be successfully consumed.  Again, this format requirement was discovered using that curl dump of the expected structure.

Hope this helps folks struggling with custom fields.
