### ISSUE TITLE
mysql_* modules don't use credentials supplied in config_file 

### ISSUE THREAD

**Issue by jficz** [ansible/ansible#31626]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

mysql_replication

##### ANSIBLE VERSION

```
ansible-playbook 2.4.0.0
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
Using /home/user/.ansible.cfg as config file
```

##### CONFIGURATION

default

##### OS / ENVIRONMENT

Arch Linux (controller)
CentOS 6 (managed)

##### SUMMARY

mysq_replication module does not use credential supplied in ~/.my.cnf even if the path to config file is explicitly specified

I have observed this behavior on other mysql_* modules as well.

##### STEPS TO REPRODUCE

```yaml
- name: Master-Master
  hosts: all
  vars:
    ansible_user: root
 
  tasks:
      
  - name: Stop Slave on Master
    mysql_replication:
      config_file: /root/.my.cnf
      mode: stopslave

```

##### EXPECTED RESULTS

OK

##### ACTUAL RESULTS

```
fatal: [master]: FAILED! => {"changed": false, "failed": true, "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user 'root'@'localhost' (using password: NO)\")"}
```
