### ISSUE TITLE
replace module numeric value 

### ISSUE THREAD

**Issue by kohonen** [ansible/ansible#31630]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

replace module
##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/local/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory/gce.py']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/opt/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /home/local/.ansible-retry

##### OS / ENVIRONMENT

debian 8.9, running in GCP

##### SUMMARY

when trying to use the replace module, replacing lines with values with numeric values breaks the file. i tried to use the number "3306" with single, double, no quotes, same result.
##### STEPS TO REPRODUCE

```yaml
- hosts: localhost

  vars:
    parameters:
      - name: database_host
        value: db-1

      - name: database_name
        value: mydb

      - name: database_port
        value: "3306"


  tasks:

    - replace:
        path: /var/tmp/test.txt
        regexp: '(\s+{{ item.name }}\:\s)(.*)'
        replace:  '\1{{ item.value }}'
      with_items: '{{ parameters }}'


```
/var/tmp/test.txt
```
    database_host: $DBHOST
    database_port: $DBPORT
    database_name: $DBNAME

```

##### EXPECTED RESULTS

```        
    database_host: db-1
    database_port: 3306
    database_name: mydb
```
##### ACTUAL RESULTS

```
    database_host: db-1[06
    database_name: mydb

```

**Comment by ansibot** [comment]
cc @EvanK
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by EvanK** [comment]
@kohonen  I suspect the problem here is your regular expression, which I'll explode and explain piece by piece:

```
(                 # first capturing group
\s+               # one or more of ANY whitespace (including newlines!)
{{ item.name }}   # parameter name (notably unescaped, so hopefully doesn't contain regex metacharacters)
\:                # literal colon, not a metachar so escaping is not necessary
\s                # one of ANY whitespace (including newlines)
)(                # end of first and start of second capturing group
.*                # zero or more of ANY non-newline characters
)                 # end of second capturing group
```

It's probably matching (and subsequently replacing) more than _just the line with each parameter_. I'd suggest using something like:

```
^                                # start of line
(                                # first capturing group
[ \t\f\v]+                       # one or more of any whitespace EXCEPT newlines or carriage returns
{{ item.name | regex_escape }}   # parameter name, with any regex metacharacters escaped
:                                # literal colon
[ \t\f\v]+                       # one or more of any whitespace EXCEPT newlines or carriage returns
)(?:                             # end of first capturing group and start of non-capturing group
.*?                              # zero or more (non-greedy) of ANY non-newline characters
)                                # end of non-capturing group
$                                # end of line
```

So your task would end up being:

```yml
    - replace:
        path: /var/tmp/test.txt
        regexp: '^([ \t\f\v]+{{ item.name|regex_escape }}:[ \t\f\v]+)(?:.*?)$'
        replace:  '\1{{ item.value }}'
      with_items: '{{ parameters }}'
```

**Comment by kohonen** [comment]
@EvanK thanks for the answer, i have obviously tried other regex options, but no luck. also just tried your suggestion, but it did not do anything at all, it left the txt file untouched.
why i still think it could be a bug of the replace module and not just a wrong regex - if you simply append any character before the the numeric value, it works ok (for example use "a3306" instead of "3306").

**Comment by EvanK** [comment]
Hmm. I will dig into this further, thanks!

**Comment by EvanK** [comment]
Turns out, the problem was not with the regex nor the module itself, but with the replacement string:

```
# what we see in the task (before variable interpolation)
'\1{{ item.value }}'
# what the replace module sees (after variable interpolation)
'\13306'
```

Python's regex lib doesn't know that you mean `the first captured group followed by "3306"`, so instead it seems to be interpreting it as `the char for octal value "133" followed by "06"`.

We just need to be more explicit with the captured group:

```yml
    - replace:
        path: /var/tmp/test.txt
        regexp: '(\s+{{ item.name }}\:\s)(.*)'
        replace:  '\g<1>{{ item.value }}'
      with_items: '{{ parameters }}'
```

See also the improved replace module docs waiting to be merged (#31452), if you're curious

@ansibot notabug
