### ISSUE TITLE
Mail module not able to us us-ascii

### ISSUE THREAD

**Issue by zgould** [ansible/ansible#31649]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible "Mail" module

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/zgould/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

DIFF_ALWAYS(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

##### SUMMARY
Mail module will not work utilizing default "Charset" option. (us-ascii_

I've also tried to statically define -
charset: us-ascii

and hit produces the same results.

charset: utf8

Allows it to work, albeit not in the format that I need.

##### ACTUAL RESULTS
Continue to get this error::

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was:  
> AttributeError: 'list' object has no attribute 'encode'fatal: [slc2-int-sw-01]: FAILED! => {"changed": false, 
> "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Os58XB/ansible_module_mail.py\", line 389, in <module>\n    main()\n  File \"/tmp/ansible_Os58XB/ansible_module_mail.py\", line 317, in main\n    msg.set_charset(charset)\n  File \"/usr/lib/python2.7/email/message.py\", line 268, in set_charset\n    cte(self)\n  File \"/usr/lib/python2.7/email/encoders.py\", line 73, in encode_7or8bit\n    orig.encode('ascii')\nAttributeError: 'list' object has no attribute 'encode'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

Utilizing utf8 as the charset works just fine.

##### PLAYBOOK
```
- name: Running Playbook
  hosts: Junos-switch-1
  serial: 1
  connection: local
  gather_facts: no

  tasks:

  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: JunOS Commands
    junos_command:
     commands:
     - show version
     provider:
      username: zgould
    register: results
    ignore_errors: yes

  - name: send mail
    mail:
     subject: Firmware Upgrade of  Complete
     body: ' Automated upgade of FAILED HORRIBLY'
     charset: utf8
     to: zgould@hotmail.com
```

**Comment by ansibot** [comment]
@zgould Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
Why oh why do people remove the template we provide them.

**Comment by zgould** [comment]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible "Mail" module

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/zgould/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

DIFF_ALWAYS(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False


##### OS / ENVIRONMENT

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"


##### SUMMARY
Mail module will not work utilizing default "Charset" option. (us-ascii_

I've also tried to statically define -
charset: us-ascii

and hit produces the same results.

charset: utf8

Allows it to work, albeit not in the format that I need.

##### ACTUAL RESULTS
Continue to get this error::

> An exception occurred during task execution. To see the full traceback, use -vvv. The error was:  
> AttributeError: 'list' object has no attribute 'encode'fatal: [slc2-int-sw-01]: FAILED! => {"changed": false, 
> "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Os58XB/ansible_module_mail.py\", line 389, in <module>\n    main()\n  File \"/tmp/ansible_Os58XB/ansible_module_mail.py\", line 317, in main\n    msg.set_charset(charset)\n  File \"/usr/lib/python2.7/email/message.py\", line 268, in set_charset\n    cte(self)\n  File \"/usr/lib/python2.7/email/encoders.py\", line 73, in encode_7or8bit\n    orig.encode('ascii')\nAttributeError: 'list' object has no attribute 'encode'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

Utilizing utf8 as the charset works just fine.

##### PLAYBOOK
```
- name: Running Playbook
  hosts: Junos-switch-1
  serial: 1
  connection: local
  gather_facts: no

  tasks:

  - name: Checking NETCONF connectivity
    wait_for: host={{ inventory_hostname }} port=830 timeout=5

  - name: JunOS Commands
    junos_command:
     commands:
     - show version
     provider:
      username: zgould
    register: results
    ignore_errors: yes

  - name: send mail
    mail:
     subject: Firmware Upgrade of  Complete
     body: ' Automated upgade of FAILED HORRIBLY'
     charset: utf8
     to: zgould@hotmail.com
```
