### ISSUE TITLE
tower_* modules not updated for Tower 3.2/ tower_cli 3.2

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#31655]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tower_credential
tower_*

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/notting/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]
```

##### CONFIGURATION
```
ANSIBLE_SSH_PIPELINING(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Fedora 26

##### SUMMARY

With tower_cli 3.2.0 installed, assorted Tower modules fail:

```
[notting@nostromo: ~]$ ansible -m tower_credential localhost -a "kind=ssh username=wow password=wow name=frobozznicate organization=TGP"
[WARNING]: Could not match supplied host pattern, ignoring: all

[WARNING]: provided hosts list is empty, only localhost is available

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: tower_cli.exceptions.BadRequest: Missing required fields: credential-type
localhost | FAILED! => {
   "changed": false,
   "failed": true,
   "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_imDa8H/ansible_module_tower_credential.py\", line 292, in <module>\n    main()\n  File \"/tmp/ansible_imDa8H/ansible_module_tower_credential.py\", line 277, in main\n    result = credential.modify(**params)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/models/base.py\", line 659, in modify\n    return self.write(pk, create_on_missing=create_on_missing, force_on_exists=True, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/models/base.py\", line 357, in write\n    raise exc.BadRequest('Missing required fields: %s' % ', '.join(missing_fields).replace('_', '-'))\ntower_cli.exceptions.BadRequest: Missing required fields: credential-type\n",
   "module_stdout": "",
   "msg": "MODULE FAILURE",
   "rc": 0
}
```

##### STEPS TO REPRODUCE

see above

##### EXPECTED RESULTS

works

##### ACTUAL RESULTS

attempts to use /api/v1 parameters from 3.1 and earlier with tower-cli 3.2's /api/v2 usage. Things go kablooie.

**Comment by ansibot** [comment]
cc @ghjm @jlaska @matburt @wwitzel3
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hanengarcia** [comment]
is there any workaround for this? I'm using tower-cli 3.2.0, Tower  3.2.1 , Ansible 2.4.0

**Comment by leifmadsen** [comment]
@hanengarcia et al

No work around for this, other than to go back to `tower-cli <3.2`.

I've started going through the modules, and there is quite a bit of other work that would be required to update this to api/v2.

For example, in the `tower_credentials.py` module alone, you need to create a couple helper modules that look up the required fields, and the fields needed in the list of `{ "inputs": { "fields": [...] } }` for the `credential-type`. You'll then need to dynamically build up the list of k,v pairs and generate the JSON appropriately.

I started looking at this, and I'm pretty sure I could come up with something, but unfortunately this isn't really a task I should be tackling at work probably...

The other question then lies with if the modules should be backwards compatible with API v1 and v2, or if we just clean break from v1 to v2 in a new Ansible version.

If we need to be backwards compatible, then the modules are going to get a lot more complicated.

I started building (and successfully made work) a new `tower_inventory_source` module, but it requires the use of tower-cli 3.2.0 (because 3.1.8 doesn't have the `inventory_source` resource), so I'm not really sure where to go from here.

**Comment by leifmadsen** [comment]
Actually, there might be a work around :)

First, downgrade to using the v1 API by installing `ansible-tower-cli` to version <3.2.

Then you can pretty much use the existing modules. For the functionality / modules that don't exist yet, I'm going to be consuming the API directly via the `uri` module for now (primarily so that I can create the inventory cloud sources).

**Comment by mpetrive-rh** [comment]
@leifmadsen  I downgraded to ansible-tower-cli 3.1.0 but it still seems to be using the v2 API.  Do I need to back further than that?

**Comment by tbouvet** [comment]
@leifmadsen @mpetrive-rh Same problem. I downgraded to ansible-tower-cli 3.1.7.
An idea please ?

**Comment by leifmadsen** [comment]
`ansible-tower-cli` version 3.1.7 uses API v1 as far as I can tell. I had things working and not working when I was changing environments around. Make sure you're able to communicate with `tower-cli` directly, because all the modules are doing is wrapping that library. If it works with `tower-cli` it should work fine with the modules (assuming you're not using `tower-cli >= 3.2`

**Comment by tbouvet** [comment]
@leifmadsen No I confirm it's not ok. Others errors appear : 
`'tower_verify_ssl' is not a valid field for Machine`
`'state' is not a valid field for Machine`

My versions:
- `Tower 3.2.1` 
- `Ansible 2.4.1.0`
- `tower-cli 3.1.7`

**Comment by leifmadsen** [comment]
Needs more information. I'm not really sure where you're getting that output from.

From the `~/.tower_cli.cfg` file that I have, my setting is `verify_ssl: False`. In the modules I'm using, I have `tower_verify_ssl: False`, like:

```
  tasks:
    - name: Drop demo items
      block:
        - name: Drop demo project
          tower_project:
            name: "Demo Project"
            state: absent
            tower_verify_ssl: False

        - name: Drop demo credential
          tower_credential:
            name: "Demo Credential"
            organization: null
            kind: ssh
            state: absent
            tower_verify_ssl: False

        - name: Drop Demo inventory
          tower_inventory:
            name: "Demo Inventory"
            organization: null
            state: absent
            tower_verify_ssl: False

        - name: Drop Demo job template
          tower_job_template:
            name: "Demo Job Template"
            job_type: run
            playbook: null
            project: null
            state: absent
            tower_verify_ssl: False
```

All of this works against a relatively recent version of AWX, with `tower-cli` version 3.1.8, and Ansible 2.4.1.0.
