### ISSUE TITLE
Incorrect User and Host are being used in Ansible 2.4.0.0

### ISSUE THREAD

**Issue by CorbanR** [ansible/ansible#31661]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/<user>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

```
Tower Enterprise 3.2.1
```

##### CONFIGURATION
```
ansible-config dump --only-changed
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

`ansible.cfg`
```
[defaults]
host_key_checking = False
nocows = 1

allow_world_readable_tmpfiles = True
gather_timeout = 60

[ssh_connection]
timeout = 60
retries = 2
ssh_args = -o ForwardAgent=yes -o ConnectTimeout=60 -o ControlMaster=auto -o ControlPersist=300s -o ServerAliveInterval=60 -F ssh_config
pipelining = True
control_path = ~/.ssh/mux-%%r@%%h:%%p
```

##### OS / ENVIRONMENT
Ansible Tower `2.3.1`

Ubuntu `14.04`

##### SUMMARY
Not entirely sure what is causing the problem. It could be that Ansible is ignoring extra ssh args that are specified in `ansible.cfg`. Might be a problem with `become`, or possibly inventory changes in `2.4.0.0` etc.....

Setup is using Ansible Tower. Jobs are being proxied through bastion hosts using custom ssh args (Example: `-F ssh_config`). The below playbooks work with Ansible `2.3.2.0`.
When using `2.4.0.0` Ansible appears to be ignoring `remote_user` and possibly the custom ssh args. It also ends up using `localhost` and the `awx` user.

##### STEPS TO REPRODUCE
One of the Jobs that Ansible and Ansible Tower is used for is to build multiple AWS AMIs simultaneously. That is accomplished by using `include` to include multiple playbooks and tasks.
Please see comments in the below playbook examples.

**Example: playbook.yml**
```yaml
- name: Gather build information
  hosts: "{{ build_region }}-{{ app_env }}"
  tasks:
    - name: Save facts
      set_fact:
        build_start_time: "{{ ansible_date_time.epoch }}"
        foundation_ami: "{{ base_ami }}"
        env_id: "{{ region_code }}-{{ app_short_env }}"

- include: ami-start-instance.yml ami_env=app-env
  when: (build_region in ['all'] and app_env in ['all'])

- name: Build App AMI
  hosts: launched
  remote_user: custom-user
  gather_facts: no
  become: true
  vars:
    apt_cache_valid_time: 0
  pre_tasks:
    - name: Wait for ssh
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        timeout: 600
        search_regex: OpenSSH
      delegate_to: localhost
      become: false

    ######On Ansible 2.3.2.0 this runs as the custom-users on the remote host. (as expected)######
    ######On Ansible 2.4.0.0 this runs on localhost as the awx user (NOT expected)######
    - name: Get EC2 instance ID
      shell: ec2metadata --instance-id
      register: cmd
      changed_when: false
      become: false

    - name: Record instance ID
      set_fact:
        instance_id: "{{ cmd.stdout }}"
        env_id: "{{ region_code }}-{{ app_short_env }}"

    ######On Ansible 2.3.2.0, this runs on the remote host as the custom-user (as expected)######
    ######On Ansible 2.4.0.0 this runs on localhost as the awx user and fails asking for password (NOT exppected)######
    - name: Gather facts
      setup: {}

  roles:
    - ami-build
```

**Example: ami-start-instance.yml**
```yaml

- name: "Start {{ ami_env }} instance"
  hosts: "{{ ami_env }}"
  gather_facts: no
  tasks:
    - name: "Launch temporary instance for {{ ami_env }}"
      ec2:
        assign_public_ip: yes
        count: 1
        group_id: "['{{ security_group_one }}', '{{ security_group_two }}']"
        image: "{{ custom_base_ami }}"
        instance_profile_name: "{{ some_instance_profile }}"
        instance_tags:
          Name: "tmp-app"
        instance_type: "{{ instance_type }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        volumes:
          - device_name: /dev/sda1
            volume_type: gp2
            volume_size: 20
            delete_on_termination: True
        vpc_subnet_id: "{{ public_subnets.0 }}"
        wait: yes
        wait_timeout: 600
      register: launch_result

    - name: Add instance to inventory groups
      add_host:
        name: "{{ item.public_ip }}"
        groups: "{{ ami_env }}, launched"
      with_items: "{{ launch_result.instances }}"
```

##### EXPECTED RESULTS
Instance starts, gets added to a group via `add_hosts` and tasks are run against remote instance

Example: Output `2.3.2.0`
```
TASK [Get EC2 instance ID] *****************************************************09:35:51
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<remote_ip> ESTABLISH SSH CONNECTION FOR USER: custom-user
<remote_ip> ESTABLISH SSH CONNECTION FOR USER: custom-user
<remote_ip> ESTABLISH SSH CONNECTION FOR USER: custom-user
<remote_ip> SSH: EXEC ssh -o ForwardAgent=yes -o ConnectTimeout=60 -o ControlMaster=auto -o ControlPersist=300s -o ServerAliveInterval=60 -F ssh_config -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=custom-user -o ConnectTimeout=60 -o ControlPath=/tmp/ansible_tower_Wwb58U/cp/%h%p%r <remote_ip> '/bin/sh -c
```

```
TASK [Gather facts] ************************************************************
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/system/setup.py
<remote_ip> ESTABLISH SSH CONNECTION FOR USER: custom-user
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/system/setup.py
<remote_ip> SSH: EXEC ssh -o ForwardAgent=yes -o ConnectTimeout=60 -o ControlMaster=auto -o ControlPersist=300s -o ServerAliveInterval=60 -F ssh_config -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=custom-user -o ConnectTimeout=60 -o ControlPath=/tmp/ansible_tower_Wwb58U/cp/%h%p%r remote_ip '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-xkyws; /usr/bin/python'"'"'"'"'"'"'"'"' && sleep 0'"'"''
```

##### ACTUAL RESULTS
Multiple tasks seem to be running as the `awx` user on `localhost` producing incorrect data and failing.

Example: Output `2.4.0.0`
```
TASK [Get EC2 instance ID] *****************************************************17:59:20
task path: /var/lib/awx/projects/_9__app_deploy/playbook.yml:7717:59:20
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/commands/command.py
<remote_ip> ESTABLISH LOCAL CONNECTION FOR USER: awx
<remote_ip> EXEC /bin/sh -c 'echo ~ && sleep 0'
<remote_ip> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1507766360.54-194921822602879 `" && echo ansible-tmp-1507766360.54-194921822602879="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1507766360.54-194921822602879 `" ) && sleep 0'
<remote_ip> PUT /tmp/tmpkD5qcY TO /var/lib/awx/.ansible/tmp/ansible-tmp-1507766360.54-194921822602879/command.py
<remote_ip> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1507766360.54-194921822602879/ /var/lib/awx/.ansible/tmp/ansible-tmp-1507766360.54-194921822602879/command.py && sleep 0'
<remote_ip> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1507766360.54-194921822602879/command.py; rm -rf "/var/lib/awx/.ansible/tmp/ansible-tmp-1507766360.54-194921822602879/" > /dev/null 2>&1 && sleep 0'
```

```
TASK [Gather facts] ************************************************************17:59:21
task path: /var/lib/awx/projects/_9__app_deploy/playbook.yml:9917:59:21
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/system/setup.py
<remote_ip> ESTABLISH LOCAL CONNECTION FOR USER: awx
<remote_ip> EXEC /bin/sh -c 'echo ~ && sleep 0'
<remote_ip> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1507766361.23-230233323159271 `" && echo ansible-tmp-1507766361.23-230233323159271="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1507766361.23-230233323159271 `" ) && sleep 0'
<remote_ip> PUT /tmp/tmpDOhMKh TO /var/lib/awx/.ansible/tmp/ansible-tmp-1507766361.23-230233323159271/setup.py
<remote_ip> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1507766361.23-230233323159271/ /var/lib/awx/.ansible/tmp/ansible-tmp-1507766361.23-230233323159271/setup.py && sleep 0'
<remote_ip> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-pis; /usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1507766361.23-230233323159271/setup.py; rm -rf "/var/lib/awx/.ansible/tmp/ansible-tmp-1507766361.23-230233323159271/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [remote_ip]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "sudo: a password is required\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```
