### ISSUE TITLE
Playbook hangs on some AIX managed nodes when setting gathering to explicit.

### ISSUE THREAD

**Issue by tinawenqiao** [ansible/ansible#31685]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ssh 

##### ANSIBLE VERSION

```
2.3.3
```

##### CONFIGURATION

defaults]
host_key_checking = False
forks = 100
sudo_flags = -H -S
retry_files_enabled = False
gathering = explicit
allow_world_readable_tmpfiles=True
stdout_callback = json
log_path    = /var/log/ansible.log
#timeout = 60
#[ssh_connection]
#ssh_args=-T
#[persistent_connection]
#connect_timeout = 60
##### OS / ENVIRONMENT

Control Host:Linux version 3.10.0-327.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Nov 19 22:10:57 UTC 2015
Managed Host: AIX 7.1
##### SUMMARY

Playbook hangs on some AIX managed nodes when setting gathering to explicit.
##### STEPS TO REPRODUCE

```yaml
Related files can be downloaded in attachment.
---
- hosts: all

  vars_files:
    - cmbc_os_network_ftp_mget_varfile.yml


  pre_tasks:
    - name: check Action step 1- define
      fail:
        msg: "Error: Action is not specified!"
      when: Action is not defined

    - name: check Action step 2- value
      fail:
        msg: "Error: the Action value must be mget or mput!"
      when: Action != "mget" and Action != "mput"

    - name: check user step 1- sepcify
      fail:
        msg: "Error: the user is not specified!"
      when: ftp_username is not defined

    - name: check passwrod step 1- specify
      fail:
        msg: "Error: the password is not specified!"
      when: ftp_passwd is not defined

    - name: check ftp_dir step 1- sepcify
      fail:
        msg: "Error: the ftp_dir is not specified!"
      when: ftp_dir is not defined

    - name: check local_dir step 2- specify
      fail:
        msg: "Error: the local_dir is not specified!"
      when: local_dir is not defined

    - name: check ftp_mode step 1- binary or ascii
      fail:
        msg: "Error: the ftp_mode must is bin or asc!"
      when: ftp_mode != "binary" and ftp_mode != "ascii"

    - name: check files step 1- specify
      fail:
        msg: "Error: files uploaded and downloaded are not specified"
      when: filename is not defined

    - name: show local-dir file-counts
      raw: echo `ls "{{ local_dir }}" |wc -l`
      register: list_dir_count

    - name: ensure local-dir is empty
      fail:
        msg: "Error: local-dir does not exist or not empty"
      when: list_dir_count.stdout.strip() != "0"

  tasks:
    - name: FTP task
      script: cmbc_os_network_ftp_mget.sh {{ Action }} {{ ftp_ip }} {{ ftp_username }} {{ ftp_passwd }} {{ ftp_dir }} {{ local_dir }} {{ftp_mode}} {{ filename }}
      register: result_ftp
      failed_when: result_ftp.rc != 0
    - debug: msg="{{ result_ftp.rc }},{{ result_ftp.stdout }}"

#  post_tasks:
#    - name: show download
#      raw: ls {{ local_dir }} | xargs -n 1
#      register: result_listdir
#      when: Action == "mget"
#    - debug: msg="{{ result_listdir.stdout_lines }}"
#      when: Action == "mget"

```

##### EXPECTED RESULTS

Running step by step.
##### ACTUAL RESULTS

ansible-playbook --inventory-file='197.1.25.61,' cmbc_os_network_ftp_mget.yml --user=root -vvvv > debug_hang

```
Using /etc/ansible/ansible.cfg as config file
Loading callback plugin json of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible-2.3.0.0-py2.7.egg/ansible/plugins/callback/__init__.pyc
1 plays in cmbc_os_network_ftp_mget.yml
<197.1.25.61> ESTABLISH SSH CONNECTION FOR USER: root
<197.1.25.61> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/8e2566df21 -tt 197.1.25.61 'echo `ls "/tmp/ftp_mget" |wc -l`
```
[Playbook.zip](https://github.com/ansible/ansible/files/1381901/Playbook.zip)

[log.zip](https://github.com/ansible/ansible/files/1381903/log.zip)
