### ISSUE TITLE
Add support for multiple IP configurations in azure_rm_networkinterface

### ISSUE THREAD

**Issue by fchiacchiaretta** [ansible/ansible#31684]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
I'm using Ansible 2.4 from awx docker images

##### SUMMARY
When creating a network interface on Azure using azure_rm_networkinterface module, I can create a vnic with a single IP configuration, while Azure support multiple IP configuration per vnic, as per screenshot below
![screenshot from 2017-10-13 09-45-32](https://user-images.githubusercontent.com/23556082/31535681-3d23ebb4-affc-11e7-8e50-61870abca696.png)

##### STEPS TO REPRODUCE
Now I create a network interface with the following task
```yaml
- name: Create a network interface
  azure_rm_networkinterface:
    name: "{{ vnic_name }}"
    resource_group: "{{ resource_group_name }}"
    virtual_network_name: "{{ vnet_name }}"
    subnet_name: default
    security_group_name: "{{ nsg_name }}"
    private_ip_allocation_method: Static
    private_ip_address: "{{ private_ip }}"
    public_ip_address_name: "{{ pubip_name }}"
```
which creates _default_ entry in screenshow above.

What I suggest is to have an _ip_configurations_ parameter, which is a list of configurations:
```yaml
- name: Create a network interface
  azure_rm_networkinterface:
    name: "{{ vnic_name }}"
    resource_group: "{{ resource_group_name }}"
    virtual_network_name: "{{ vnet_name }}"
    subnet_name: default
    security_group_name: "{{ nsg_name }}"
    ip_configurations:
    - name: default
      private_ip_allocation_method: Static
      private_ip_address: "{{ private_ip_default }}"
      public_ip_address_name: "{{ pubip_name_default }}"
    - name: secondary
      private_ip_allocation_method: Static
      private_ip_address: "{{ private_ip_secondary }}"
      public_ip_address_name: "{{ pubip_name_secondary }}"
```

Regards,
Federico Chiacchiaretta
