### ISSUE TITLE
apt_key module ignores the proxy environment

### ISSUE THREAD

**Issue by mejo-** [ansible/ansible#31691]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

apt_key

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### SUMMARY

The Ansible module `apt_key` doesn't recognize proxy environment settings. This makes it unusable on systems that depend on using a HTTP(S) proxy.

##### STEPS TO REPRODUCE

Set `Acquire::http::Proxy "http://proxy.example.org:3128/";` in `/etc/apt/apt.conf` and set proxy_env variables in Ansible via `set_fact`. Apparently both are ignored:

```yaml
- set_fact:
  proxy_env:
    http_proxy: "http://proxy.example.org:3128/"
    https_proxy: "http://proxy.example.org:3128/"

- name: add debmon apt repository key
  apt_key:
    url: http://debmon.org/debmon/repo.key
    state: present
```
##### ACTUAL RESULTS

The proxy settings are ignored:

```
TASK [monitoring : add debmon apt repository key] *******************************************************
fatal: [ns1]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download key at http://debmon.org/debmon/repo.key: Request failed: <urlopen error [Errno 101] Network is unreachable>"}
	to retry, use: --limit @/home/user/ansible/site.retry
```

This already got reported at ansible/ansible-modules-core#3336, but contrary to the comment in that bugreport it still doesn't work.

**Comment by ansibot** [comment]
cc @jvantuyl
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andreaso** [comment]
Except that you in your example aren't actually passing any environment variables. Try something like this instead.

```yaml
- name: add debmon apt repository key
    environment:
      http_proxy: http://proxy.example.org:3128/
    apt_key:
      url: http://debmon.org/debmon/repo.key
      state: present
```

**Comment by aminancelot** [comment]
@andreaso Proxy settings can be passed at the playbook level.
http://docs.ansible.com/ansible/latest/playbooks_environment.html

Actually, I have the same problem it seems with apt_repository, doing some checking before opening an issue.

**Comment by roumano** [comment]
Bug confirmed for me,

Using this in group_vars env is not working :  
```
proxy_env:
  http_proxy: http://172.31.255.254:8888
  https_proxy: http://172.31.255.254:8888
``` 
But it's work is i use 
```
  - name: Ensure the Sensu APT repo GPG key is present
     apt_key:
       url: https://sensu.global.ssl.fastly.net/apt/pubkey.gpg
       state: present
     environment:
       http_proxy: 'http://172.31.255.254:8888'
       https_proxy: 'http://172.31.255.254:8888'
```

**Comment by lily-mara** [comment]
I'm seeing a similar issue when using a `keyserver` as opposed to a `url` directly. I think that `apt-key adv` requires `--keyserver-options http-proxy=$http_proxy` to be provided on the command line in order to work, and I don't see that in the module file 

https://github.com/ansible/ansible/blob/e9c2546ffeb30a8675740ca276a71b4718813b97/lib/ansible/modules/packaging/os/apt_key.py#L245

**Comment by avoidik** [comment]
I confirm the same, I'm using inline variables with GPG-keys as workaround for now:

```
apt_key:
  data={{ gpgkey_data }}
  state=present
```

```
gpgkey_data: |
    -----BEGIN PGP PUBLIC KEY BLOCK-----
    -----END PGP PUBLIC KEY BLOCK-----
```

**Comment by michalmedvecky** [comment]
It's not a bug, it's just not implemented:

https://github.com/ansible/ansible/blob/ff50b7893cff56707fb45d79c951cbe1e7bc710e/lib/ansible/modules/packaging/os/apt_key.py#L199

:vomit:

**Comment by peterfraedrich** [comment]
Can confirm that this still isn't implemented as of Jun 11, 2018. 

This is 100% breaking node boostrapping for AWS environment.

**Comment by theasp** [comment]
I'm using this as a workaround:
```yaml
- name: APT repository GPG key
  apt_key:
    data: "{{ lookup('url', 'https://repos.influxdata.com/influxdb.key', split_lines=False) }}"
```

**Comment by hangsu-ma** [comment]
HI All, just let you know I have submitted a fix for this:
https://github.com/ansible/ansible/pull/42443

**Comment by DrHashi** [comment]
As of ansible 2.7.9, this is still happening with PPA packages

**Comment by mohag** [comment]
As a workaround you can directly add the HKP URL in the url field instead. e.g to add the Datadog key, you can replace:
```
          apt_key:
            keyserver: hkp://keyserver.ubuntu.com:80
            id: A2923DFF56EDA6E76E55E492D3A80E30382E94DE
            state: present
```

With 
```
          apt_key:
            url: https://keyserver.ubuntu.com/pks/lookup?search=0xA2923DFF56EDA6E76E55E492D3A80E30382E94DE&op=get
            state: present
```

It might differ slightly for other keyservers. I haven't read the [HKP spec](https://tools.ietf.org/html/draft-shaw-openpgp-hkp-00) more than a quick scan.
