### ISSUE TITLE
Vault variable in lists error

### ISSUE THREAD

**Issue by dglinder** [ansible/ansible#31705]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Core functionality involving variable lists and vaulted values.

##### ANSIBLE VERSION
```
$ ansible --version
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting

ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.11 (default, Jan 15 2016, 09:50:41) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
$
```

##### OS / ENVIRONMENT
RedHat 6.8
Ansible installed via ```pip```.

##### CONFIGURATION

```
$ sudo ansible-config dump --only-changed
ACCELERATE_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 5.0
ACCELERATE_DAEMON_TIMEOUT(/etc/ansible/ansible.cfg) = 30
ACCELERATE_PORT(/etc/ansible/ansible.cfg) = 5099
ACCELERATE_TIMEOUT(/etc/ansible/ansible.cfg) = 30
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o UserKnownHostsFile=/dev/null
ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 0
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /etc/ansible/json_fact_cache
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 86400
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_LANG(/etc/ansible/ansible.cfg) = C
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/my_modules']
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = $HOME/.ansible/tmp
DEFAULT_SUDO_EXE(/etc/ansible/ansible.cfg) = sudo
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### SUMMARY
Vaulted variables in lists produce an error, but work in dictionaries.

##### STEPS TO REPRODUCE
Using this playbook:

```yaml
---
- hosts: localhost
  gather_facts: false
  vars:
    userlist:
      - { name: "user1",
          password: "user1pwd"
        }
      - { name: "user2",
          password: !vault |
                    $ANSIBLE_VAULT;1.1;AES256
                    66366265333266666432626431646631356664663262326535346265353939383239626634636331
                    6462666364303539336132346430346432333564346663300a623333613666333330626330643735
                    64613664383733333839313434303433663164363030383663336663656432613965663862656237
                    3631366664646332610a636230616334306232336263313139623264663338613538643163356239
                    3732
        }
      - { name: "user3",
          password: "user3pwd"
        }

  tasks:
  - name: "List variable"
    debug:
      msg: "name: {{ item.name }}, password: {{ item.password }}"
    with_items: "{{ userlist }}"
```

Run it with the `--ask-vault-pass` option:
```
sudo ansible-playbook ./test01.yml --ask-vault-pass
```
Enter "test" when prompted for the password.

##### EXPECTED RESULTS
```
$ sudo ansible-playbook ./test01a.yml --ask-vault-pass
Vault password:
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] **********************************************************************************************************

TASK [List variable] ******************************************************************************************************
ok: [localhost] => (item={u'password': u'user1pwd', u'name': u'user1'}) => {
    "item": {
        "name": "user1",
        "password": "user1pwd"
    },
    "msg": "name: user1, password: user1pwd"
}
ok: [localhost] => (item={u'password': u'user2pwd', u'name': u'user2'}) => {
    "item": {
        "name": "user2",
        "password": "user2pwd"
    },
    "msg": "name: user2, password: user2pwd"
}
ok: [localhost] => (item={u'password': u'user3pwd', u'name': u'user3'}) => {
    "item": {
        "name": "user3",
        "password": "user3pwd"
    },
    "msg": "name: user3, password: user3pwd"
}

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0

$
```

##### ACTUAL RESULTS

```
$ sudo ansible-playbook -vvvv ./test01.yml --ask-vault-pass
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.11 (default, Jan 15 2016, 09:50:41) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
Using /etc/ansible/ansible.cfg as config file
Vault password:
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

ERROR! Syntax Error while loading YAML.


The error appears to have been in '/eit/admin/home/dglinder/tmp/test.vault/test01.yml': line 20, column 28, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - { name: "user2",
          password: !vault |
                           ^ here

exception type: <class 'yaml.scanner.ScannerError'>
exception: while scanning for the next token
found character '|' that cannot start any token
  in "<unicode string>", line 20, column 28:
              password: !vault |
                               ^
$
```
