### ISSUE TITLE
ec2_vpc_subnet TAGS are not idempotent

### ISSUE THREAD

**Issue by MichalTaratuta** [ansible/ansible#31706]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_vpc_subnet
##### ANSIBLE VERSION

```
ansible 2.4.0.0
python version = 2.7.12
```

##### CONFIGURATION

configured module search path = [u'/etc/ansible/modules']
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Module is not idempotent when used with **tags** option. If a tag is present the module reports a change on every run. Without the tag module passes and **OK**.
##### STEPS TO REPRODUCE

```yaml
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vps.vpc.id}}"
        cidr: 10.10.1.16/28
        az: eu-west-1a
        map_public: yes
        tags:
          Name: Subnet_A
      register: subnet_a

```

##### EXPECTED RESULTS

Expected result is status **OK** after the first run.
##### ACTUAL RESULTS

On every run module reports the task as changed even though nothing has chnaged.

```

```
