### ISSUE TITLE
Pacman Module Fails To Achieve Desired Package State

### ISSUE THREAD

**Issue by PatrickMurray** [ansible/ansible#31713]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Pacman

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cnf
  configured module search path = [u'/home/patrick/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION
```
N/A
```

##### OS / ENVIRONMENT
```
Linux thinkpad 4.13.5-1-ARCH #1 SMP PREEMPT Fri Oct 6 09:58:47 CEST 2017 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - pacman:
        name: "{{ item }}"
        state: latest
        update_cache: True
        upgrade: True
      with_items:
        - git
      become: True
```
##### EXPECTED RESULTS
I would expect `git` to be installed to the system.

##### ACTUAL RESULTS
```bash
$ git
-bash: git: command not found
```
