### ISSUE TITLE
Lineinfile module adds incorrect number of lines

### ISSUE THREAD

**Issue by liamfit** [ansible/ansible#31712]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Lineinfile

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file = /ansible/ansible_infrastructure/playbooks/ansible.cfg
  configured module search path = [u'../library']
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
```
[defaults]
ansible_managed = Please do not change this file directly since it is managed by Ansible and will be overwritten
action_plugins = ../plugins/actions
host_key_checking = false
roles_path = ../../ansible_reusable/roles
library = ../library
inventory = inventory
forks = 6
```

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY
When using the lineinfile module to add the IP address of each host in the play to a config file on my proxy server (to allow internet access) I find that I get less lines added than the number of hosts even though the tasks shows a "changed" result for every host.

##### STEPS TO REPRODUCE
Playbook task:
```
- name: configure proxy | modify buildtemp acl on proxy server
  lineinfile:
    dest: /etc/squid/squid.conf
    state: "{{ state }}"
    regexp: "{ ansible_default_ipv4.address }}"
    line: "acl buildtemp src {{ ansible_default_ipv4.address }}/32"
    insertafter: "acl buildtemp src"
  delegate_to: "{{ proxy }}"
```

Excerpt of proxy config file before:
```acl buildtemp src 10.116.16.1/32
acl buildtemp src 10.116.16.2/32
acl buildtemp src 10.116.16.3/32
acl buildtemp src 10.111.174.0/24
acl buildtemp src 10.111.173.0/24

http_access allow windowsupdate our_networks
http_access allow linuxupdate our_networks
http_access allow elasticsearch our_networks
http_access allow all buildtemp
```

##### EXPECTED RESULTS
Expected to see 6 lines added to the proxy config file

##### ACTUAL RESULTS
Playbook output:

```
TASK [configure proxy | modify buildtemp acl on proxy server] *******************************************************************************************************************************************************************************
task path: /ansible/ansible_reusable/tasks/configure_proxy.yml:24
changed: [xxxxxxxxx05 -> 10.111.195.1] => {"backup": "", "changed": true, "msg": "line added"}
changed: [xxxxxxxxx08 -> 10.111.195.1] => {"backup": "", "changed": true, "msg": "line added"}
changed: [xxxxxxxxx07 -> 10.111.195.1] => {"backup": "", "changed": true, "msg": "line added"}
changed: [xxxxxxxxx04 -> 10.111.195.1] => {"backup": "", "changed": true, "msg": "line added"}
changed: [xxxxxxxxx09 -> 10.111.195.1] => {"backup": "", "changed": true, "msg": "line added"}
changed: [xxxxxxxxx06 -> 10.111.195.1] => {"backup": "", "changed": true, "msg": "line added"}
```

Excerpt of config file after:
```
acl buildtemp src 10.116.16.1/32
acl buildtemp src 10.116.16.2/32
acl buildtemp src 10.116.16.3/32
acl buildtemp src 10.111.174.0/24
acl buildtemp src 10.111.173.0/24
acl buildtemp src 10.111.1.86/32
acl buildtemp src 10.111.1.88/32
acl buildtemp src 10.111.1.85/32
acl buildtemp src 10.111.1.87/32

http_access allow windowsupdate our_networks
http_access allow linuxupdate our_networks
http_access allow elasticsearch our_networks
http_access allow all buildtemp
```

I've played around with the regexp and with insertbefore and insertafter and I can get it to add anywhere from 3-5 lines but never 6. If I remove the lines Ansible adds and run the playbook again it will always add the same number of lines but not always the same IP addresses. If I don't remove the lines Ansible adds and I keep running the playbook it will eventually add all the required lines.

**Comment by ansibot** [comment]
cc @ahtik @dhozac
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by torgiren** [comment]
It's because race condition.
try to use template or blockinfile + run_once

**Comment by liamfit** [comment]
I think the problem with template is that I want to preserve the existing contents of the file and I won't necessarily always know what the existing contents are. 

I'm not sure how to get a line in the file for each host if I use blockinfile + run_once - can you give me an example?

If it helps I was previously using run_once and looping through ansible_play_batch using with_items. I stopped that because when I run a play using hosts: localhost then it doesn't work as ansible_play_hosts is empty.

**Comment by torgiren** [comment]
i'm working on fix your problem...
give me 2 days for tests :)
(it's ready, but I need to test one more thing)

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aykay76** [comment]
I am seeing a similar issue using v2.6 so I guess this isn't fixed yet. I create two new VMs and want to add their keys to known_hosts. Sometimes I only get one of them added.

Is there a way to serialise a single task so that it runs sequentially for each host in the inventory?

**Comment by AlexBaranowski** [comment]
Hi,
I want to confirm that `delegate_to` with lineinfile has race condition, even with only 2 hosts it can break. I'm using ansible 2.7.8 on Enterprise Linux 7 clone.

Here is whole "screen":
**there was nice fish prompt**: `ansible-playbook poc.yml --inventory ../inventories/inventory_local`

PLAY [tmp1, tmp2] **************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [10.10.1.137]
ok: [10.10.1.30]

TASK [remove the file] *********************************************************************************************************************
ok: [10.10.1.137]
ok: [10.10.1.30]

TASK [add line about change on host] *******************************************************************************************************
changed: [10.10.1.30 -> localhost]
changed: [10.10.1.137 -> localhost]

PLAY RECAP *********************************************************************************************************************************
10.10.1.137                : ok=3    changed=1    unreachable=0    failed=0   
10.10.1.30                 : ok=3    changed=1    unreachable=0    failed=0   
**there was nice fish prompt**: `cat /tmp/ansible-mailing-tmp123 `
10.10.1.30 has change

The minimalistic POC (actually used)

```yaml
- hosts: tmp1, tmp2
  user: ansible
  become: true
  vars:
    mail_body_file: "/tmp/ansible-mailing-tmp123" 
  tasks:
    - name: remove the file
      file:
        path: "{{mail_body_file}}"
        state: absent

    - name: add line about change on host
      lineinfile:
        path: "{{mail_body_file}}"
        line: "{{inventory_hostname}} has change"
        regexp: "^{{inventory_hostname}} has change"
        create: True
      delegate_to: localhost
```
Note that because it's race it might actually require about more than one invocation, please remove the file before next run. Note also that become on localhost must be available.


It's quite funny, because lineinfile has the `unsafe_writes` option :smile: :).

@aykay76 there is great discussion about serial on tasks https://github.com/ansible/ansible/issues/12170
Bests,
Alex

**Comment by Raman-Kathpalia** [comment]
I got a similar problem with lineinfile and blockinfile. Fully described [here on stackoverflow](https://stackoverflow.com/questions/58827823/ansible-save-registered-variables-to-a-local-file). 
Any ideas?

**Comment by torgiren** [comment]
@Raman-Kathpalia 
Have you tried throttle?
https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html#using-keywords-to-control-execution
it's new feature in ansible 2.9

**Comment by Raman-Kathpalia** [comment]
@torgiren 
Now, I did. I put `throttle: 1` at task level which calls - `lineinfile` module (which is where the problem is). I do see reduction but not elimination.

**Comment by bobross419** [comment]
@Raman-Kathpalia I had the same issue as you, and throttle at task still had problems.  I was able to group the lineinfile in with another task and throttle them at the block level.  Not pretty and might have to be hacked together with something like a pause: seconds=1 if you don't have something else that logically groups there.

**Comment by brammeleman** [comment]
Looks identical to #30413. Which is closed with pull request #52567 . However the pull request does not include the relevant test case with `delegate_to: localhost` and the problem still exists (ansible 2.9.6)

Test case:
``` yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
    - copy: content="" dest=/tmp/test
- hosts: all
  gather_facts: false
  tasks:
    - lineinfile: line="{{inventory_hostname}}" path=/tmp/test
      delegate_to: localhost
- hosts: localhost
  gather_facts: false
  tasks:
    - command: cat /tmp/test
      register: cat
    - debug: var=cat.stdout_lines|sort
    - assert:
        that: groups.all|length == cat.stdout_lines|length
```
Adding `serial: 1` to the playbook (middle part) removes the concurrency and the assertion succeeds.
