### ISSUE TITLE
Roles consisting of skipped tasks only are not deduplicated

### ISSUE THREAD

**Issue by whitequark** [ansible/ansible#31751]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
role

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/whitequark/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
Default.

##### OS / ENVIRONMENT
N/A.

##### SUMMARY
If roles B and C depend on role A, which has at least one task that executes, role A is ran only one time. If all tasks in A are skipped, role A is ran (as visible on stdout) three times.

##### STEPS TO REPRODUCE
```yaml
# ./roles/x/tasks/main.yml
- name: foo
  debug: msg='x called'
  when: false
# ./roles/z/meta/main.yml
dependencies:
- { name: 'x' }
# ./roles/z/tasks/main.yml
- debug: msg='z called'
# ./roles/y/meta/main.yml
dependencies:
- { name: 'x' }
# ./roles/y/tasks/main.yml
- debug: msg='y called'
# ./localhost.yml
---
- hosts: localhost
  roles:
  - { name: 'x' }
  - { name: 'y' }
  - { name: 'z' }
```
or as a [zip archive](https://github.com/ansible/ansible/files/1385264/bug.zip)

##### EXPECTED RESULTS
```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [x : foo] *****************************************************************
skipping: [localhost]

TASK [y : debug] ***************************************************************
ok: [localhost] => {
    "msg": "y called"
}

TASK [z : debug] ***************************************************************
ok: [localhost] => {
    "msg": "z called"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS
```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [x : foo] *****************************************************************
skipping: [localhost]

TASK [x : foo] *****************************************************************
skipping: [localhost]

TASK [y : debug] ***************************************************************
ok: [localhost] => {
    "msg": "y called"
}

TASK [x : foo] *****************************************************************
skipping: [localhost]

TASK [z : debug] ***************************************************************
ok: [localhost] => {
    "msg": "z called"
}

PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
