### ISSUE TITLE
Unable to use access site_facts with $item and 'when'

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#3178]
I'm unable to access site_facts from within a _when_ statement when combined _with_items_.  I'm unclear whether the fault lies with my [library/site_facts](https://gist.github.com/jlaska/5759226), with my _when_ clause, or with ansible.

For example, the following works:

``` yaml
   - name: epel repos
     command: /bin/true
     when: yum_repos['epel'].enabled
```

However, the following does not:

``` yaml
   - name: $item repos
     command: /bin/true
     with_items:
        - epel
     when: yum_repos['$item'].enabled
```

I am testing with [ansible-1.2](https://admin.fedoraproject.org/updates/FEDORA-EPEL-2013-10412/ansible-1.2-1.el6).  My site_facts provides a dictionary, called _yum_repos_, that details the yum.repos.d configuration for the current system.
### library/site_facts

See https://gist.github.com/jlaska/5759226
### playbooks/test.yml

``` yaml

---

- name: test_site_facts
  hosts: local
  connection: local

  tasks:
   - name: gather site specific fact data
     action: site_facts

   - name: epel repos
     command: /bin/true
     when: yum_repos['epel'].enabled

   - name: $item repos
     command: /bin/true
     with_items:
        - epel
     when: yum_repos['$item'].enabled

```
### Actual Results

```
# ansible-playbook playbooks/test.yml  

PLAY [test_site_facts] ******************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [gather site specific fact data] **************************************** 
ok: [127.0.0.1]

TASK: [epel repos] ************************************************************ 
changed: [127.0.0.1]

TASK: [$item repos] *********************************************************** 
fatal: [127.0.0.1] => Conditional expression must evaluate to True or False: {% if yum_repos['epel'].enabled %} True {% else %} False {% endif %}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/tmp/ansible/test.retry

127.0.0.1                  : ok=3    changed=1    unreachable=1    failed=0   
```
