### ISSUE TITLE
VMware: vmware_guest forces size for disk, where only datastore is needed

### ISSUE THREAD

**Issue by bhairav13** [ansible/ansible#31804]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'mypath/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

No output

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

'disk' option requires size attribute even though template is being used.

##### STEPS TO REPRODUCE

``` 
   - name: Create VM from template
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter: "MyDataCenter"
        esxi_hostname: "{{ esxhost }}"
        name: "{{ vmname }}"
        template: "{{ vmtemplate }}"
        disk:
        - datastore: "{{ datastore }}"
 #         size_gb: 30
        networks:
        - name: VM Network
          ip: 192.168.1.100
          netmask: 255.255.255.0
          gateway: 192.168.1.1
        customization:
          hostname: "{{ vmname }}"
      delegate_to: localhost
      register: newvm
```
The only reason to use the disk attribute is to point to a specific datastore for the VM to be deployed.  The sole datastore attribute causes a failure:

FAILED! => {"changed": false, "failed": true, "msg": "No size, size_kb, size_mb, size_gb or size_tb attribute found into disk configuration"}

Since I am deploying from template, it doesn't make sense to have to specify disk size.  I can use the same size as the template, but that means the number needs to be kept track of in case the size is changed later.

For deploying a VM from a template, is it possible to break the dependency on the size if all we want is to specify a particular target datastore for it?

```yaml

```

##### EXPECTED RESULTS

Be able to create the VM to a specific datastore without having to provide the size.

##### ACTUAL RESULTS

```
FAILED! => {"changed": false, "failed": true, "msg": "No size, size_kb, size_mb, size_gb or size_tb attribute found into disk configuration"}
```

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@bhairav13 Thanks for reporting this issue. Could you please try this change (untested) and let me know if it works for you ? 

```
diff lib/ansible/modules/cloud/vmware/vmware_guest.py /tmp/vmware_guest.py
1058,1067c1058,1068
<             kb = self.get_configured_disk_size(expected_disk_spec)
<             # VMWare doesn't allow to reduce disk sizes
<             if kb < diskspec.device.capacityInKB:
<                 self.module.fail_json(
<                     msg="Given disk size is smaller than found (%d < %d). Reducing disks is not allowed." %
<                         (kb, diskspec.device.capacityInKB))
<
<             if kb != diskspec.device.capacityInKB or disk_modified:
<                 diskspec.device.capacityInKB = kb
<                 self.configspec.deviceChange.append(diskspec)
---
>             if not self.params['template']:
>                 kb = self.get_configured_disk_size(expected_disk_spec)
>                 # VMWare doesn't allow to reduce disk sizes
>                 if kb < diskspec.device.capacityInKB:
>                     self.module.fail_json(
>                         msg="Given disk size is smaller than found (%d < %d). Reducing disks is not allowed." %
>                             (kb, diskspec.device.capacityInKB))
>
>                 if kb != diskspec.device.capacityInKB or disk_modified:
>                     diskspec.device.capacityInKB = kb
>                     self.configspec.deviceChange.append(diskspec)
1069c1070
<                 self.change_detected = True
---
>                     self.change_detected = True
```

**Comment by bhairav13** [comment]
Thanks @Akasurde, that works!

Should the change consider both cases:
1) That a template was given with no disk size (the issue being addressed here)
2) That a template was given with an increased disk size (that the new change would possibly not allow)  -- not sure if some other part of the code handles this

Thanks.

**Comment by ansibot** [comment]
cc @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pheitman** [comment]
Still does not seem to be fixed in ansible 2.5.3. Given that if I use vCenter to clone the template to a VM all I have to do is to select a compute host and a datastore, it is confusing to me why that capability is missing from vmware_guest. Note that I have multiple templates that have different disk configurations. To have to mirror those configurations in the ansible script just to select the datastore is truly cumbersome.

**Comment by Akasurde** [comment]
@bhairav13 Could you please try https://github.com/ansible/ansible/pull/35812 and let me know if it works for you ? This PR allows user to specify parent datastore for template to clone. Thanks, 

needs_info

**Comment by bhairav13** [comment]
Sure.  A couple of questions though:
1) Just so I understood correctly, 'datastore' is now at a higher level.  Something like this ... ?

```
     - name: Create VM from template
          vmware_guest:
            validate_certs: False
            hostname: "{{ vcenter_hostname }}"
            username: "{{ vcenter_user }}"
            password: "{{ vcenter_pass }}"
            datacenter: "MyDataCenter"
            esxi_hostname: "{{ esxhost }}"
            name: "{{ vmname }}"
            template: "{{ vmtemplate }}"
            datastore: "{{ datastore }}"
            networks:
            - name: VM Network
              ip: 192.168.1.100
              netmask: 255.255.255.0
              gateway: 192.168.1.1
            customization:
              hostname: "{{ vmname }}"
          delegate_to: localhost
          register: newvm
```

2) Pardon my ignorance as this is my first time doing this, but how do I pick up a non-production build with those changes?  A pointer to the steps would be appreciated.

Thanks.
