### ISSUE TITLE
Strange behavior with '1_' as dict key

### ISSUE THREAD

**Issue by jamesongithub** [ansible/ansible#31815]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = ansible.cfg
  configured module search path = [u'modules']
  python version = 2.7.13 (default, Jun  9 2017, 12:31:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### SUMMARY

Serializer seems to convert 1_ to 1 as a dictionary key

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  tasks:
    - debug:
        var: my_dict
  vars:
    my_dict:
      0_9_2: value
      1_1_0: value1
      0000001: value2
      1_: value3
      12: value4
```

##### EXPECTED RESULTS

```
TASK [debug] *********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "my_dict": {
        "0_9_2": "value"
        "1_1_0": "value1"
        "0000001": "value2"
        "1_": "value3"
        "12": "value4"
    }
}
```
##### ACTUAL RESULTS

keys casted to integers when it contains '1'?

```
TASK [debug] TASK [debug] *********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "my_dict": {
        "1": "value3", 
        "12": "value4", 
        "110": "value1", 
        "0_9_2": "value"
    }
}


```
