### ISSUE TITLE
Vars of include_role task injected before conditional

### ISSUE THREAD

**Issue by FlogFr** [ansible/ansible#31820]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
"vars" injected before conditional of include_role task

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/arkadefr/Projects/peopleinfra/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
```
# ansible.cfg of the project
[defaults]
display_skipped_hosts=False
timeout=30
roles_path=roles
stdout_callback = debug
force_color = True
retry_files_enabled = False

# gathering fact in order to cache them and speedup the run
gathering = smart
gather_subset = all
fact_caching = jsonfile
fact_caching_connection = /tmp/facts_cache.d
```

##### OS / ENVIRONMENT
I'm running ansible 2.3.1 installed by debian package on my debian stretch.

##### SUMMARY
The vars of the include_role task are included before the "when" conditional of the include_role.

##### STEPS TO REPRODUCE
This is the interesting part of my playbook to reproduce the bug:
```yaml
- hosts: all
  gather_facts: True
  tasks:
   - name: Debug variable
     debug:
       var: test_var
   - include_role:
       name: test
     vars:
       test_var: true
     when:
       - test_var is defined and test_var
```
The vars (`test_var = true`) is injected inside ansible before evaluating the conditional `when` of the same task.

##### EXPECTED RESULTS
The vars should be injected only inside the included_role.

##### ACTUAL RESULTS
The vars are injected before the conditional and so the conditional is evaluated to True, instead of False.
