### ISSUE TITLE
changed_when format string

### ISSUE THREAD

**Issue by naisanza** [ansible/ansible#31826]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

`changed_when`

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/eric/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY

I'm trying to use `changed_when` to trigger when the string `from 'canonical' installed` exists.

However, inside the string there are single quotes, which it doesn't like

##### STEPS TO REPRODUCE

```yaml
  - name: Pre-setup - snapd - install lxd
    shell: snap install lxd
    register: result
    changed_when: "'from 'canonical' installed' in result.stdout"
```

This doesn't work:
```yaml
  - name: Pre-setup - snapd - install lxd
    shell: snap install lxd
    register: result
    changed_when: "'from \'canonical\' installed' in result.stdout"
```

This doesn't work either:
```yaml
  - name: Pre-setup - snapd - install lxd
    shell: snap install lxd
    register: result
    changed_when: "'from \\'canonical\\' installed' in result.stdout"
```

The error it returns:
```yaml
TASK [Pre-setup - snapd - install lxd] *****************************************************************
fatal: [10.0.1.211]: FAILED! => {"failed": true, "msg": "The conditional check ''from 'canonical' installed' in result.out' failed. The error was: template error while templating string: expected token 'end of statement block', got 'canonical'. String: {% if 'from 'canonical' installed' in result.out %} True {% else %} False {% endif %}"}
```

**Comment by sivel** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by naisanza** [comment]
@sivel it's not documented on how it needs to be formatted

**Comment by naisanza** [comment]
Triple escaping works

```yaml
  - name: Pre-setup - snapd - install conjure-up
    shell: snap install conjure-up --classic
    register: result
    changed_when: "'from \\\'canonical\\\' installed' in result.stdout"
    ignore_errors: yes
```
