### ISSUE TITLE
Lookup plugin credstash failing

### ISSUE THREAD

**Issue by stijndehaes** [ansible/ansible#31869]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lookup plugin, credstash

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/stijndehaes/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 23:05:11) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

credstash version: 1.13.4
##### CONFIGURATION
empty

##### OS / ENVIRONMENT
Mac OSX High sierra 10.13 (17A405)

##### SUMMARY
When using the lookup plugin for credstash I get the following error:
```
TASK [Test credstash lookup plugin -- get the password with a context defined here] ***********************************************************************************************************************************************************************************************
objc[6763]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[6763]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

##### STEPS TO REPRODUCE

```yaml
- name: Test
  hosts: localhost
  tasks:
    - name: "Test credstash lookup plugin -- get the password with a context defined here"
      debug: msg="credstash {{ lookup('credstash', 'test', region=aws_region) }}"
  vars:
    aws_region: eu-west-1

```

##### EXPECTED RESULTS
It to work

##### ACTUAL RESULTS

```
TASK [Test credstash lookup plugin -- get the password with a context defined here] ***********************************************************************************************************************************************************************************************
objc[6763]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[6763]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```
