### ISSUE TITLE
Ansible does not timeout on get_url where the proxy server is unknown

### ISSUE THREAD

**Issue by snevs** [ansible/ansible#31897]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Ansible's get_url does not timeout if a proxy server is set with the environment, and does not timeout even if the timeout setting is there.
##### STEPS TO REPRODUCE

The proxy server is defined in the vars, but it doesn't resolve.
```yaml
  - name: Reload ansible_local variables
    setup: filter=ansible_local

    - name: DL
      get_url:
        url: "{{ dl_server }}Generic.zip"
        dest: "/var/tmp/"
        url_username: "{{ dl_user }}"
        url_password: "{{ dl_pass }}"
        validate_certs: no
        timeout: 10
        checksum: md5:3500bf8a6083f66a744be3280eba4939d
        use_proxy: "{{ (ansible_local.proxyes.proxy_host is defined)|ternary('yes','no') }}" 
      environment:
        http_proxy: "{{ ansible_local.proxyes.all_proxy }}"
      register: plugin_dw
```

##### EXPECTED RESULTS

Ansible should fail with the error that the CLI returns
##### ACTUAL RESULTS

Ansible just sits there and doesn't timeout, while it is clear that the proxy server cannot be resolved even on the CLI:

```
curl -x proxy.example.com:80 https://$user:$pass@server.example.com/Generic.zip
curl: (5) Couldn't resolve proxy 'proxy.example.com'

```
