### ISSUE TITLE
win_find module failing to find files when it cannot access a single file in a Dicrectory

### ISSUE THREAD

**Issue by vamshideveloper** [ansible/ansible#31898]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_find
##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### OS / ENVIRONMENT

Running ansible from: Linux VM-TOWERFF1.iam.sungard.prod 3.10.0-514.6.1.el7.x86_64 #1 SMP Sat Dec 10 11:15:38 EST 2016 x86_64 x86_64 x86_64 GNU/Linux
managing: windows server 2008 R2 Enterprise
##### SUMMARY

I was trying to find all files from c:\windows\Temp with win_find module and trying to delete them with win_file module but win_find module failing with the following error
But win_find module is working fine with all dir so what i found was, in Temp dir there are some files which ansible user cannot access (delete/move/copy etc) so i think this problem is because of these files but i dont want to touch those files as i want to run win_find on 250 servers. So i just want win_find module to skip the files which it cannot access and find remaining instead of failing whole playbook

##### STEPS TO REPRODUCE

```yaml
- name: finding files  (C:\Windows\Temp)
    win_find:
      paths: C:\\Windows\\Temp    
    register: regi_windir 
    tags: coex_windir    
    
  - name: Cleaning files older than 1 days (C:\Windows\Temp)
    win_file:
      path: "{{ item.path }}"
      state: absent                
    with_items: 
      - "{{ regi_windir.files }}"
    tags: coex_windir 
```

##### EXPECTED RESULTS

Finding all files under Temp dir and registering in regi_windir and deleting the files which were registered
##### ACTUAL RESULTS

```
ERROR:{
    "_ansible_parsed": false,
    "_ansible_no_log": false,
    "module_stderr": "Exception calling \"Open\" with \"4\" argument(s): \"The process cannot access the \r\nfile 'C:\\Windows\\Temp\\hsperfdata_VM-ASPCOEXTSM04$\\2016' because it is being \r\nused by another process.\"\r\nAt line:295 char:13\r\n+             $fp = [System.IO.File]::Open($path, [System.IO.Filemode]::Open, \r\n[Sys ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordE \r\n   xception\r\n    + FullyQualifiedErrorId : IOException\r\n \r\n\r\n",
    "changed": false,
    "module_stdout": "",
    "failed": true,
    "rc": 1,
    "msg": "MODULE FAILURE"
}
```

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
This looks like it is related to https://github.com/ansible/ansible/issues/26885, are you able to run the module with `get_checksum: no` as it seems like it is trying to get a checksum on an open file and then fails.

We should have a better error message but this should solve your issue for now.

**Comment by vamshideveloper** [comment]
So, i added (get_checksum: False) but it fails with the same error above

```
 - name: finding files older than 1 days (C:\Windows\Temp)
    win_find:
      paths: C:\\Windows\\Temp
      get_checksum: False        
    register: regi_windir 
    tags: coex_windir    
     
- name: Cleaning files older than 1 days (C:\Windows\Temp)
   win_file:
     path: "{{ item.path }}"
     state: absent                
   with_items: 
     - "{{ regi_windir.files }}"
   tags: coex_windir
```
