### ISSUE TITLE
XML module can't add element with namespaced attribute

### ISSUE THREAD

**Issue by icb-** [ansible/ansible#31918]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
XML module

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
Nothing changed

##### OS / ENVIRONMENT
CentOS 7 both controlling and controlled

##### SUMMARY
With the new XML module in 2.4, I get a traceback if I try to add namespaced attributes at the same time as I add the element.

##### STEPS TO REPRODUCE
Given this XML file:
```xml
<?xml version='1.0' encoding='UTF-8'?>
<AttributeFilterPolicyGroup xmlns="urn:mace:shibboleth:2.0:afp"
                            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                            id="ShibbolethFilterPolicy"
                            xsi:schemaLocation="urn:mace:shibboleth:2.0:afp http://shibboleth.net/schema/idp/shibboleth-afp.xsd">
  <AttributeFilterPolicy id="UnverifiedRPs" />
</AttributeFilterPolicyGroup>
```

```yaml
---
- hosts: test
  tasks:
  - name: Attribute filter Unverified RPs
    xml:
      path: /tmp/test.xml
      namespaces: &namespaces
        x: "urn:mace:shibboleth:2.0:afp"
        xsi: "http://www.w3.org/2001/XMLSchema-instance"
      xpath: '/x:AttributeFilterPolicyGroup/x:AttributeFilterPolicy[@id = "UnverifiedRPs"]'
      pretty_print: yes
      set_children:
        - PolicyRequirementRule:
            "xsi:type": ANY
        - AttributeRule:
            attributeID: eduPersonPrincipalName
        - AttributeRule:
            attributeID: uid
  - name: Attribute filter Unverified RPs
    xml:
      path: /tmp/test.xml
      namespaces: *namespaces
      xpath: '/x:AttributeFilterPolicyGroup/x:AttributeFilterPolicy[@id = "UnverifiedRPs"]/x:AttributeRule[@attributeID="{{item}}"]'
      pretty_print: yes
      set_children:
        - PermitValueRule:
            "xsi:type": ANY
    with_items:
      - eduPersonPrincipalName
      - uid
```

Setting the attributes individually after making the elements does work, but is much more confusing and error prone. e.g.

```yaml
---
- hosts: test
  tasks:
  - name: Attribute filter Unverified RPs
    xml:
      path: /tmp/test.xml
      namespaces: &namespaces
        x: "urn:mace:shibboleth:2.0:afp"
        xsi: "http://www.w3.org/2001/XMLSchema-instance"
      xpath: '/x:AttributeFilterPolicyGroup/x:AttributeFilterPolicy[@id = "UnverifiedRPs"]'
      pretty_print: yes
      set_children:
        - PolicyRequirementRule: null
        - AttributeRule:
            attributeID: eduPersonPrincipalName
        - AttributeRule:
            attributeID: uid
  - name: Attribute filter Unverified RPs
    xml:
      path: /tmp/test.xml
      namespaces: *namespaces
      xpath: '/x:AttributeFilterPolicyGroup/x:AttributeFilterPolicy[@id = "UnverifiedRPs"]/x:PolicyRequirementRule'
      pretty_print: yes
      attribute: "xsi:type"
      value: "ANY"
```

##### EXPECTED RESULTS
Elements created with namespaced attributes.

##### ACTUAL RESULTS

```
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/centos/idp-ansible/hosts.txt inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: test.yaml **************************************************************************************************************************************************************************************************************************************************************************************************************************
1 plays in test.yaml

PLAY [test] **********************************************************************************************************************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<idp.icb> ESTABLISH LOCAL CONNECTION FOR USER: root
<idp.icb> EXEC /bin/sh -c 'echo ~ && sleep 0'
<idp.icb> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1508362520.43-177885778694475 `" && echo ansible-tmp-1508362520.43-177885778694475="` echo /root/.ansible/tmp/ansible-tmp-1508362520.43-177885778694475 `" ) && sleep 0'
<idp.icb> PUT /tmp/tmpjnZk2M TO /root/.ansible/tmp/ansible-tmp-1508362520.43-177885778694475/setup.py
<idp.icb> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1508362520.43-177885778694475/ /root/.ansible/tmp/ansible-tmp-1508362520.43-177885778694475/setup.py && sleep 0'
<idp.icb> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1508362520.43-177885778694475/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1508362520.43-177885778694475/" > /dev/null 2>&1 && sleep 0'
ok: [idp.icb]
META: ran handlers

TASK [Attribute filter Unverified RPs] *******************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/centos/idp-ansible/test.yaml:4
Using module file /usr/lib/python2.7/site-packages/ansible/modules/files/xml.py
<idp.icb> ESTABLISH LOCAL CONNECTION FOR USER: root
<idp.icb> EXEC /bin/sh -c 'echo ~ && sleep 0'
<idp.icb> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1508362520.99-53486585655555 `" && echo ansible-tmp-1508362520.99-53486585655555="` echo /root/.ansible/tmp/ansible-tmp-1508362520.99-53486585655555 `" ) && sleep 0'
<idp.icb> PUT /tmp/tmpf5K0fK TO /root/.ansible/tmp/ansible-tmp-1508362520.99-53486585655555/xml.py
<idp.icb> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1508362520.99-53486585655555/ /root/.ansible/tmp/ansible-tmp-1508362520.99-53486585655555/xml.py && sleep 0'
<idp.icb> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1508362520.99-53486585655555/xml.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1508362520.99-53486585655555/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_kUrRMQ/ansible_module_xml.py", line 853, in <module>
    main()
  File "/tmp/ansible_kUrRMQ/ansible_module_xml.py", line 829, in main
    set_target_children(module, doc, xpath, namespaces, set_children, input_type)
  File "/tmp/ansible_kUrRMQ/ansible_module_xml.py", line 402, in set_target_children
    changed = set_target_children_inner(module, tree, xpath, namespaces, children, in_type)
  File "/tmp/ansible_kUrRMQ/ansible_module_xml.py", line 380, in set_target_children_inner
    children = children_to_nodes(module, children, in_type)
  File "/tmp/ansible_kUrRMQ/ansible_module_xml.py", line 644, in children_to_nodes
    return [child_to_element(module, child, type) for child in children]
  File "/tmp/ansible_kUrRMQ/ansible_module_xml.py", line 624, in child_to_element
    node = etree.Element(key, value)
  File "lxml.etree.pyx", line 2808, in lxml.etree.Element (src/lxml/lxml.etree.c:61236)
  File "apihelpers.pxi", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:13819)
  File "apihelpers.pxi", line 111, in lxml.etree._makeElement (src/lxml/lxml.etree.c:13693)
  File "apihelpers.pxi", line 263, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:15339)
  File "apihelpers.pxi", line 1529, in lxml.etree._attributeValidOrRaise (src/lxml/lxml.etree.c:26818)
ValueError: Invalid attribute name u'xsi:type'
fatal: [idp.icb]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_kUrRMQ/ansible_module_xml.py\", line 853, in <module>\n    main()\n  File \"/tmp/ansible_kUrRMQ/ansible_module_xml.py\", line 829, in main\n    set_target_children(module, doc, xpath, namespaces, set_children, input_type)\n  File \"/tmp/ansible_kUrRMQ/ansible_module_xml.py\", line 402, in set_target_children\n    changed = set_target_children_inner(module, tree, xpath, namespaces, children, in_type)\n  File \"/tmp/ansible_kUrRMQ/ansible_module_xml.py\", line 380, in set_target_children_inner\n    children = children_to_nodes(module, children, in_type)\n  File \"/tmp/ansible_kUrRMQ/ansible_module_xml.py\", line 644, in children_to_nodes\n    return [child_to_element(module, child, type) for child in children]\n  File \"/tmp/ansible_kUrRMQ/ansible_module_xml.py\", line 624, in child_to_element\n    node = etree.Element(key, value)\n  File \"lxml.etree.pyx\", line 2808, in lxml.etree.Element (src/lxml/lxml.etree.c:61236)\n  File \"apihelpers.pxi\", line 123, in lxml.etree._makeElement (src/lxml/lxml.etree.c:13819)\n  File \"apihelpers.pxi\", line 111, in lxml.etree._makeElement (src/lxml/lxml.etree.c:13693)\n  File \"apihelpers.pxi\", line 263, in lxml.etree._initNodeAttributes (src/lxml/lxml.etree.c:15339)\n  File \"apihelpers.pxi\", line 1529, in lxml.etree._attributeValidOrRaise (src/lxml/lxml.etree.c:26818)\nValueError: Invalid attribute name u'xsi:type'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
        to retry, use: --limit @/home/centos/idp-ansible/test.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************************************************************************
idp.icb       : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by ansibot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sm4rk0** [comment]
Hi @icb- looking [here](https://stackoverflow.com/a/7703144/1990878), I got a clue to try this way:
```
"{http://www.w3.org/2001/XMLSchema-instance}type": ANY
```

The result is:
```xml
<AttributeFilterPolicyGroup xmlns="urn:mace:shibboleth:2.0:afp" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" id="ShibbolethFilterPolicy" xsi:schemaLocation="urn:mace:shibboleth:2.0:afp http://shibboleth.net/schema/idp/shibboleth-afp.xsd">
  <AttributeFilterPolicy id="UnverifiedRPs">
    <PolicyRequirementRule xsi:type="ANY"/>
    <AttributeRule attributeID="eduPersonPrincipalName">
      <PermitValueRule xsi:type="ANY"/>
    </AttributeRule>
    <AttributeRule attributeID="uid">
      <PermitValueRule xsi:type="ANY"/>
    </AttributeRule>
  </AttributeFilterPolicy>
</AttributeFilterPolicyGroup>
```

@dagwieers , @jborean93 Not sure if this is a bug or just a way it should be done. Maybe we could test if attribute contains a colon, and replace the `namespace_prefix:` with `{namespace}` if there is one defined? If we don't change the module, we should at least update its documentation.

**Comment by icb-** [comment]
@sm4rk0 Thanks! That does indeed work.

I think for consistency with how it works when adding just the attribute, it should be made to work with the standard namespace declaration, but this will work for now. Either way I agree the documentation (and test cases) need to be updated.

**Comment by ansibot** [comment]
cc @magnus919
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andrewmcguinness** [comment]
The same seems to apply to add_children, FWIW, for adding child elements with namespaces.

```
 xml:
   namespaces:
       a: "http://www.a.com/ns"
       b: "http://www.b.com/ns"
   xpath: /a:rootel
   add_children:
        - "{http://www.b.com/ns}childel": "somevalue"
```

It would be nicer to be able to insert "b:childel", but that doesn't work

**Comment by UnitedMarsupials** [comment]
The problem, it seems, is with the very search. And the breaks if there ix `xmlns` attribute anywhere on the way to the element the search is supposed to find. For example, consider this:
```yaml
---
- hosts: localhost
  gather_facts: false
  tasks:
  - name: Create test XML
    set_fact:
      xml1: >-
        <Outer xxmlns="http://www.w3.org/1999/xhtml">
        	<inner eaten="mouse"/>
        </Outer>
      xml2: >-
        <Outer xmlns="http://www.w3.org/1999/xhtml">
        	<inner eaten="mouse"/>
        </Outer>
  
  - name: Search for "inner"
    xml:
      xmlstring: "{{ item }}"
      xpath: /Outer/inner
      count: true
    register: counts
    loop:
    - "{{ xml1 }}"
    - "{{ xml2 }}"

  - debug: var=counts
```
As you can see, it find the `inner` element in the first case -- where attribute is (mis)spelled with two "xx" -- but not in the second case.

To answer @sm4rk0's question, most certainly, this is _not_ how things should be. Indeed, searching for the same xpath with `xml_grep` does the right thing regardless of the `xmlns` attribute.

Please, fix soonest -- I'm trying to manipulate XHTML documents with Ansible, and this bug makes it very difficult...
