### ISSUE TITLE
Lookup passwordstore - unable to render tilde (~)

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#31936]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lib/ansible/plugins/lookup/passwordstore.py

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/n3ph/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/home/n3ph/git/reservix/devops/ansible/roles']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Debian Stretch

##### SUMMARY
When setting location of the password store to "~/.password-store" plugin is unable to find it.

##### STEPS TO REPRODUCE
```yaml
  - name: root | build passwordstore command
    set_fact:
      #passwordstore_cmd: "{{ passwordstore_devops_subfolder }}/{{ passwordstore_devops_default_rootpw_path }} passwordstore={{ passwordstore_devops_path }}"
      #passwordstore_cmd: "{{ passwordstore_devops_subfolder }}/{{ passwordstore_devops_default_rootpw_path }} directory={{ passwordstore_devops_path }}"
      passwordstore_cmd: "{{ passwordstore_devops_subfolder }}/{{ passwordstore_devops_default_rootpw_path }} directory=~/.password-store"

  - name: root | get default root password
    set_fact:
      root_password_hash: "{{ lookup('passwordstore', passwordstore_cmd) | password_hash('sha512') }}"
```

##### EXPECTED RESULTS
plugin should render tilde (~) to an absolute path to users home directory

##### ACTUAL RESULTS
```
fatal: [default]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Passwordstore directory '~/.password-store' does not exist"}
```

##### WORKAROUND
```yaml
passwordstore_cmd: "{{ passwordstore_devops_subfolder }}/{{ passwordstore_devops_default_rootpw_path }} directory=/home/{{ lookup('env', 'USER') }}/.password-store"
```
