### ISSUE TITLE
Lookup passwordstore - parameter passwordstore is implemented as directory

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#31934]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
lib/ansible/plugins/lookup/passwordstore.py
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/passwordstore.py#L158-L163

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/n3ph/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/home/n3ph/git/reservix/devops/ansible/roles']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Debian Stretch

##### SUMMARY
The parameter passwordstore is implemented as directory

##### STEPS TO REPRODUCE
```yaml
  - name: root | build passwordstore command
    set_fact:
      #passwordstore_cmd: "{{ passwordstore_devops_subfolder }}/{{ passwordstore_devops_default_rootpw_path }} passwordstore={{ passwordstore_devops_path }}"
      passwordstore_cmd: "{{ passwordstore_devops_subfolder }}/{{ passwordstore_devops_default_rootpw_path }} directory={{ passwordstore_devops_path }}"

  - name: root | get default root password
    set_fact:
      root_password_hash: "{{ lookup('passwordstore', passwordstore_cmd) | password_hash('sha512') }}"
```

##### EXPECTED RESULTS
Should be implemented as documented
https://docs.ansible.com/ansible/devel/plugins/lookup/passwordstore.html#options

##### ACTUAL RESULTS

```
fatal: [default]: FAILED! => {"failed": true, "msg": "An unhandled exception occurred while running the lookup plugin 'passwordstore'. Error was a <class 'ansible.errors.AnsibleError'>, original message: "}
```
