### ISSUE TITLE
ini_file value: true ends up in uppercase True

### ISSUE THREAD

**Issue by akamac** [ansible/ansible#31968]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ini_file
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/amiasoedov/ansible/playbooks/linux/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Sep 14 2017, 22:51:06) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

Setting `value: 'true'` does solve the issue, but I guess it's a work around.
##### STEPS TO REPRODUCE

```yaml
- name: allow users to browse documents
  ini_file:
    backup: yes
    path: "{{ config_file }}"
    section: couch_httpd_auth
    option: users_db_public
    value: true
```

##### EXPECTED RESULTS

[couch_httpd_auth]
users_db_public = true
##### ACTUAL RESULTS

[couch_httpd_auth]
users_db_public = True

```

```
