### ISSUE TITLE
Ansible azure_rm_deployment debug 'instances' missing

### ISSUE THREAD

**Issue by fluffy-cakes** [ansible/ansible#31967]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
azure_rm_deployment

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/home/paulmackinnon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
DEFAULT_VAULT_PASSWORD_FILE(/home/paulmackinnon/.ansible/ansible.cfg) = /home/paulmackinnon/.ansible/

##### OS / ENVIRONMENT
ubuntu 16.04 LTS desktop

##### SUMMARY
I'm deploying an ARM template via the azure_rm_deployment module and wanting to retrieve some output variables that I can then use later in my playbook. However, I am unable to retrieve any details about 'instances', regardless if I debug and/or use -vvvv

##### STEPS TO REPRODUCE
ansible-playbook azure-json-deployD.yml -i azure_rm.py --ask-vault-pass -vvvv

```yaml
---
- name: Deploy Azure ARM template.
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
   - ./vars/vault.yml
   - ./vars/vars.yml

  tasks:
    - include_vars: vault.yml
    - name: Create Azure Deploy
      azure_rm_deployment:
        client_id: "{{ client_id }}"
        secret: "{{ secret }}"
        subscription_id: "{{ subscription_id }}"
        tenant: "{{ tenant }}"
        state: present
        resource_group_name: AnsibleDomain
        location: UK South
        template: "{{ lookup('file', 'WindowsVirtualMachineD.json') }}"
        parameters: "{{ (lookup('file', 'WindowsVirtualMachine.parametersD.json') | from_json).parameters }}"
      register: azure

    - name: Debug
      debug:
        var: azure



Here is the output (minus the JSON of my template):

...(JSON-TEMPLATE-CONT)...
        "template_link": null, 
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "wait_for_deployment_completion": true, 
            "wait_for_deployment_polling_period": 10
        }
    }, 
    "msg": "deployment succeeded"
}
Read vars_file './vars/vault.yml'
Read vars_file './vars/vars.yml'

TASK [Debug] **********************************************************************************************************************************************************************
task path: /home/fluffy/publiccloud/Ansible/azure-json-deployD.yml:26
ok: [localhost] => {
    "azure": {
        "changed": true, 
        "deployment": {
            "group_name": "AnsibleDomain", 
            "id": "/subscriptions/********/resourceGroups/AnsibleDomain/providers/Microsoft.Resources/deployments/ansible-arm", 
            "instances": [], 
            "name": "ansible-arm", 
            "outputs": null
        }, 
        "failed": false, 
        "msg": "deployment succeeded"
    }
}
META: ran handlers
META: ran handlers
```

##### EXPECTED RESULTS

I am missing the output of the all important INSTANCES (located under deployment); it only shows [ ] instead of details, such as what you see here on line 329: https://github.com/lmazuel/azurerm/blob/master/azure_rm_deployment.py

##### ACTUAL RESULTS
I must be missing something. Can anyone please point out to me how to obtain detailed info?

```
msg:
  description: String indicating if the deployment was created or deleted
  returned: always
  type: string
  sample: "deployment created"
deployment:
  description: Deployment details
  type: dict
  returned: always
  sample:{
        "group_name": "Test_Deployment",
        "id": "/subscriptions/3f7e29ba-24e0-42f6-8d9c-5149a14bda37/resourceGroups/Test_Deployment/providers/Microsoft.Resources/deployments/ansible-arm",
        "instances": [
            {
                "ips": [
                    {
                        "dns_settings": {
                            "domain_name_label": "testvm9910001",
                            "fqdn": "testvm9910001.westus.cloudapp.azure.com"
                        },
                        "id": "/subscriptions/3f7e29ba-24e0-42f6-8d9c-5149a14bda37/resourceGroups/Test_Deployment/providers/Microsoft.Network/publicIPAddresses/myPublicIP",
                        "name": "myPublicIP",
                        "public_ip": "13.91.99.232",
                        "public_ip_allocation_method": "IPAllocationMethod.dynamic"
                    }
                ],
                "vm_name": "MyUbuntuVM"
            }
        ],
        "name": "ansible-arm",
        "outputs": {
            "hostname": {
                "type": "String",
                "value": "testvm9910001.westus.cloudapp.azure.com"
            },
            "sshCommand": {
                "type": "String",
```

**Comment by ansibot** [comment]
cc @devigned @lmazuel @obsoleted
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
@zikalino

**Comment by kyliel** [comment]
Assign to @zikalino

**Comment by yaweiw** [comment]
@zikalino thanks.

**Comment by zikalino** [comment]
i am just fixing all deployment issues, so i should handle this one by the end of this week.

**Comment by Fred-sun** [comment]
Hi @zikalino Has the issue been solved? Can you help update the status of the issue or which PR fix? Thanks!

**Comment by Fred-sun** [comment]
@zikalino  Could you help update the comment? Thanks!

**Comment by Fred-sun** [comment]
@zikalino Could you help update the comment? Thanks!

**Comment by Fred-sun** [comment]
@zikalino Has the issue been solved? Can you help update the status of the issue or which PR fix? Thanks!

**Comment by Fred-sun** [comment]
@zikalino Has the issue been solved? Can you help update the status of the issue or which PR fix? Thanks!

**Comment by Fred-sun** [comment]
@zikalino Has the issue been solved? Can you help update the status of the issue or which PR fix? Thanks!

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@zikalino Do you have handle this issue? Could you help take a look this issue? Thanks!

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino Could you help take a look this issue? Thanks!

**Comment by fluffy-cakes** [comment]
I'm so glad I ditched Ansible for another platform. Over a year and this still hasn't been addressed. Awesome.

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino Please help give a fix! Thanks!

**Comment by Fred-sun** [comment]
@zikalino

**Comment by Fred-sun** [comment]
@zikalino Please help take a look this issue when you're available! Thanks!

**Comment by Fred-sun** [comment]
@zikalino

**Comment by zikalino** [comment]
i am just adding facts module:
https://github.com/ansible/ansible/pull/53204
once this is merged, all the deployment details will be available via facts.

**Comment by zikalino** [comment]
I have tried 2 playbooks:
First one I have just taken it from integration tests:

```yaml
- name: Create Azure Deploy
    azure_rm_deployment:
    resource_group: "{{ resource_group }}"
    location: eastus2
    template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/d01a5c06f4f1bc03a049ca17bbbd6e06d62657b3/101-vm-simple-linux/azuredeploy.json'
    deployment_name: "{{ dns_label }}"
    parameters:
        adminUsername:
        value: chouseknecht
        adminPassword:
        value: password123!
        dnsLabelPrefix:
        value: "{{ dns_label }}"
        ubuntuOSVersion:
        value: "16.04.0-LTS"
    register: output

- debug:
    var: output
```

so the output appears to be correct:

```json
{
    "output": {
        "changed": true,
        "deployment": {
            "group_name": "zimsdeployment",
            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/zimsdeployment/providers/Microsoft.Resources/deployments/zimsdeployment",
            "instances": [
                {
                    "ips": [
                        {
                            "dns_settings": {
                                "domain_name_label": "zimsdeployment",
                                "fqdn": "zimsdeployment.eastus2.cloudapp.azure.com"
                            },
                            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/zimsdeployment/providers/Microsoft.Network/publicIPAddresses/myPublicIP",
                            "name": "myPublicIP",
                            "public_ip": "23.100.65.195",
                            "public_ip_allocation_method": "Dynamic"
                        }
                    ],
                    "vm_name": "MyUbuntuVM"
                }
            ],
            "name": "zimsdeployment",
            "outputs": {
                "hostname": {
                    "type": "String",
                    "value": "zimsdeployment.eastus2.cloudapp.azure.com"
                },
                "sshCommand": {
                    "type": "String",
                    "value": "ssh chouseknecht@zimsdeployment.eastus2.cloudapp.azure.com"
                }
            }
        },
        "failed": false,
        "msg": "deployment succeeded"
    }
}
```

So I am changing the template do deploy Windows server:

```yaml
- name: Create Azure Deploy
    azure_rm_deployment:
    resource_group: "{{ resource_group }}"
    location: eastus2
    template_link: 'https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-windows/azuredeploy.json'
    deployment_name: "{{ dns_label }}"
    parameters:
        adminUsername:
        value: chouseknecht
        adminPassword:
        value: password123!
        dnsLabelPrefix:
        value: "{{ dns_label }}"
        windowsOSVersion:
        value: "2016-Datacenter"
    register: output
- debug:
    var: output
```
and also the output looks rather correct:
```json
 {
    "output": {
        "changed": true,
        "deployment": {
            "group_name": "zimsanotherdeployment",
            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/zimsanotherdeployment/providers/Microsoft.Resources/deployments/zimsdplxxxx",
            "instances": [
                {
                    "ips": [
                        {
                            "dns_settings": {
                                "domain_name_label": "zimsdplxxxx",
                                "fqdn": "zimsdplxxxx.eastus2.cloudapp.azure.com"
                            },
                            "id": "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/zimsanotherdeployment/providers/Microsoft.Network/publicIPAddresses/myPublicIP",
                            "name": "myPublicIP",
                            "public_ip": "104.209.244.123",
                            "public_ip_allocation_method": "Dynamic"
                        }
                    ],
                    "vm_name": "SimpleWinVM"
                }
            ],
            "name": "zimsdplxxxx",
            "outputs": {
                "hostname": {
                    "type": "String",
                    "value": "zimsdplxxxx.eastus2.cloudapp.azure.com"
                }
            }
        },
        "failed": false,
        "msg": "deployment succeeded"
    }
}
```
