### ISSUE TITLE
Incoherent items processing

### ISSUE THREAD

**Issue by ymougenel** [ansible/ansible#31975]
- Bug Report

##### COMPONENT NAME
ansible loops (with_items)

##### ANSIBLE VERSION
ansible 2.4.0 (python 2.7.42)

##### OS / ENVIRONMENT
Ubuntu 16.04.3 LTS

##### SUMMARY
When processing numerical items, ansible does not seem to process the last ones correctly.

##### STEPS TO REPRODUCE
When entering multiple numeric items starting with 0, only 8 and 9 are processed as 2 digit values :

```yaml
- file:
    path: "~/tmp/{{ item }}"
    state: directory
  delegate_to: localhost
  with_items:
    - 01
    - 02
    - 03
    - 04
    - 05
    - 06
    - 07
    - 08
    - 09
```

This will 9 produces folders:
1 2 3 4 5 6 7 **08 09**

(I suppose is is due to an octal conversion.)

##### EXPECTED RESULTS
Either all the numeric values are processed as a one digit (eg: 01 -> 1 and 09 -> 9), or all the values keep the 0 prefix.

##### ACTUAL RESULTS
The 2 last values are the only ones starting with 0.

PS: This is my first reporting contribution, please tell me if I forgot anything
