### ISSUE TITLE
lineinfile does not expand "\1" (backrefs) or escaped controls

### ISSUE THREAD

**Issue by rmfrankch** [ansible/ansible#31994]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
no changes.

##### OS / ENVIRONMENT
Ubuntu 16.04.3 LTS

##### SUMMARY
lineinfile line parameter will not expand the escaped terms (\1, \2, \t, ...)

##### STEPS TO REPRODUCE
using a modified /etc/nsswitch.conf with the following contents:
passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

```yaml
- name: "If local users only, make sure passwd,group, and shadow have 'files' only."
  lineinfile:
    path: '/etc/nsswitch.conf'
    regexp: '^({{ item }})\s*:.*'
    line: '\1:\tfiles'
    state: 'present'
  with_items:
    - passwd
    - group
    - shadow
```

##### EXPECTED RESULTS
passwd:         files
group:          files
shadow:         files
gshadow:        files

##### ACTUAL RESULTS
\1 :\tfiles
\1 :\tfiles
\1 :\tfiles
gshadow:        files
