### ISSUE TITLE
Add ability to attach managed IAM policy to IAM user

### ISSUE THREAD

**Issue by nchammas** [ansible/ansible#31999]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - iam_user module
 - iam_managed_policy module

##### ANSIBLE VERSION
```
ansible 2.4.1.0 (detached HEAD de458be1eb) last updated 2017/10/20 11:37:42 (GMT -400)
  config file = .../config/nonprd/ansible.cfg
  configured module search path = [u'.../config/nonprd/library']
  ansible python module location = .../venv/src/ansible/lib/ansible
  executable location = .../venv/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
Settings changed in ansible.cfg:
* host_key_checking
* library
* filter_plugins
* roles_path
* inventory
* ssh_args
* pipelining

##### OS / ENVIRONMENT
macOS

##### SUMMARY
Ansible currently lets you create IAM users and create managed IAM policies. However, it does not let you attach an existing managed IAM policy to an existing IAM user. This seems like a gap in functionality. [Boto3 lets you directly do this](https://boto3.readthedocs.io/en/latest/reference/services/iam.html#IAM.Client.attach_user_policy), for what it's worth.

Prior discussion on this topic: https://github.com/ansible/ansible-modules-core/issues/2688#issuecomment-229769601

##### STEPS TO REPRODUCE
Example usage of this feature would perhaps look like this:

```yaml
- name: Attach managed policy to user
  iam_managed_policy:
    iam_type: user
    iam_name: "{{user_name}}"
    policy_name: "{{policy_name}}"
    state: present
```
