### ISSUE TITLE
vmware_guest : create VM from template playbook fail, but VM is built, but not powered on. Second try is ok.

### ISSUE THREAD

**Issue by mldmld68** [ansible/ansible#31991]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 ansible/lib/ansible/modules/cloud/vmware/vmware_guest.py
##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```
##### CONFIGURATION
No changes in ansible.cfg 

##### OS / ENVIRONMENT
Running ansible on Centos 7
Vcenter 6.5U1
ESXi : 6.0U2

##### SUMMARY
When lanching this ansible playbook, see forward, for the first time , I get this error.
msg": "The number of network adapter settings in the customization specification: 0 does not match the number of network adapters present in the virtual machine: 1.
One can see the same error message in the vcenter.
The VM is created correctly, but not powered on
If I restart the same playbook, it's ok
The template I try to deploy has one network adapter and in the playbook I set        
networks:
        - name: lanope
I tried with a Centos 7 template and a Windows template I buillt. Both of them were made with one vmxnet3 network interface.
##### STEPS TO REPRODUCE

```
[root@AnsibleTst ansible]# cat create-VM-vmware_guest2.yml
---
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1

  tasks:
    - name: Create a VM from a template
      vmware_guest:
        hostname: myvcenter.company.com
        username: xxxxx
        password: xxxxxxx
        validate_certs: no
        cluster: mycluster
        datacenter: mydatacenter
#        guest_id: centos64Guest
#        guest_id: windows8Server64Guest
        name: newansibleWinVM3
        state: poweredon
        folder: /windows
#        template: Centos7.7-Gold-1-TPL
        template: Win2016-Gold-1-TPL
        customization:
          password: toto # Not used by this template
        hardware:
          memory_mb: 2048
          num_cpus: 2
#          scsi: lsilogicsas
#          scsi: paravirtual
        disk:
        - datastore: DS001
          size_gb: 64
#          type: thin
        networks:
        - name: mylan
      delegate_to: localhost
      register: deploy


```

##### EXPECTED RESULTS
I expected create and poweron the VM without ansible error in one time.

##### ACTUAL RESULTS

```
[root@AnsibleTst ansible]#  ansible-playbook -vvvv create-VM-vmware_guest2.yml
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: create-VM-vmware_guest2.yml *****************************************************************************************************************************************************
1 plays in create-VM-vmware_guest2.yml

PLAY [127.0.0.1] **************************************************************************************************************************************************************************
META: ran handlers

TASK [Create a VM from a template] ********************************************************************************************************************************************************
task path: /etc/ansible/create-VM-vmware_guest2.yml:10
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1508509892.22-261908975248372 `" && echo ansible-tmp-1508509892.22-261908975248372="` echo /root/.ansible/tmp/ansible-tmp-1508509892.22-261908975248372 `" ) && sleep 0'
<localhost> PUT /tmp/tmpQm772b TO /root/.ansible/tmp/ansible-tmp-1508509892.22-261908975248372/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1508509892.22-261908975248372/ /root/.ansible/tmp/ansible-tmp-1508509892.22-261908975248372/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1508509892.22-261908975248372/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1508509892.22-261908975248372/" > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "mycluster",
            "customization": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "myDC",
            "disk": [
                {
                    "datastore": "xxxxxxxx",
                    "size_gb": 64
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm/windows",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 2048,
                "num_cpus": 2
            },
            "hostname": "xxxxxxxxxxxx",
            "is_template": false,
            "name": "newansibleWinVM3",
            "name_match": "first",
            "networks": [
                {
                    "name": "mylan"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "state": "poweredon",
            "template": "Win2016-Gold-1-TPL",
            "template_src": "Win2016-Gold-1-TPL",
            "username": "xxxxxxxxx",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "The number of network adapter settings in the customization specification: 0 does not match the number of network adapters present in the virtual machine: 1."
}
        to retry, use: --limit @/etc/ansible/create-VM-vmware_guest2.retry

PLAY RECAP ********************************************************************************************************************************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1

[root@AnsibleTst ansible]# ^C
[root@AnsibleTst ansible]#  ansible-playbook -vvvv create-VM-vmware_guest2.yml
Using /etc/ansible/ansible.cfg as config file
[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default).
This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: create-VM-vmware_guest2.yml *****************************************************************************************************************************************************
1 plays in create-VM-vmware_guest2.yml

PLAY [127.0.0.1] **************************************************************************************************************************************************************************
META: ran handlers

TASK [Create a VM from a template] ********************************************************************************************************************************************************
task path: /etc/ansible/create-VM-vmware_guest2.yml:10
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1508510317.08-278731963355176 `" && echo ansible-tmp-1508510317.08-278731963355176="` echo /root/.ansible/tmp/ansible-tmp-1508510317.08-278731963355176 `" ) && sleep 0'
<localhost> PUT /tmp/tmpkxeuGP TO /root/.ansible/tmp/ansible-tmp-1508510317.08-278731963355176/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1508510317.08-278731963355176/ /root/.ansible/tmp/ansible-tmp-1508510317.08-278731963355176/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1508510317.08-278731963355176/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1508510317.08-278731963355176/" > /dev/null 2>&1 && sleep 0'
changed: [127.0.0.1 -> localhost] => {
    "changed": true,
    "failed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "mycluster",
            "customization": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "mydc",
            "disk": [
                {
                    "datastore": "DS001",
                    "size_gb": 64
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm/windows",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 2048,
                "num_cpus": 2
            },
            "hostname": "xxxxxxxxxxxxxxxxxx",
            "is_template": false,
            "name": "newansibleWinVM3",
            "name_match": "first",
            "networks": [
                {
                    "name": "mylan"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "state": "poweredon",
            "template": "Win2016-Gold-1-TPL",
            "template_src": "Win2016-Gold-1-TPL",
            "username": "xxxxx",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=0

[root@AnsibleTst ansible]#

```

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by shajay12** [comment]
Hi Everyone,
why the script does not uses "esxi_hostname" ??
I ran above script but it gives error while running.

**Comment by Akasurde** [comment]
@shajay12 Could you please paste your playbook and error console here ?

**Comment by shajay12** [comment]
Once you get time, again comment this post, i will send you the code.
Due to privacy, i am not posting the code.

**Comment by shajay12** [comment]
one more question i want to ask. 

do i need to login to the Windows 2012 R2 machine with Ansible where the Vpshere client is installed ??

**Comment by shajay12** [comment]
Thanks In Advance.

**Comment by shajay12** [comment]
Hi Akash,

Can you send me the Ansible code for creating VM from vm template.

**Comment by Akasurde** [comment]
@mldmld68 Could you please retry using latest 2.5Alpha1 and let me know if it works for you ? 

needs_info

**Comment by shajay12** [comment]
i will try this and inform you.

**Comment by shajay12** [comment]
Hi Abhi,
here is the playbook.  The machine is formed in vmware vsphere, but with another folder also named as 

replica-e040a406-2f24-4c53-b719-67f42c1b9115
cloneofwfs

at last i have also give full run output. 

cat us_vm.yaml
```
---
- name: Deploy VM on XXX.XX.2.103
  hosts: localhost
  gather_facts: no
  vars_prompt:
  - name: templatename
    prompt: Supply template name
    default: "CENTOS7-ENT-WWW-APACHE-DEFAULT"
    private: no

  - name: vm_name
    prompt: Supply VM Name to Be Created
    default: "TestMachine"
    private: no
  tasks:
    - name: Create a VM from USA template
      vmware_guest:
        hostname: 172.17.2.103
        username: oshq\ajsharma
        password: oneshield1
        datacenter: OSC-US-Datacenter-Other
        validate_certs: no
        folder: /VMwareViewComposerReplicaFolder
        name: "{{vm_name}}"
        state: poweredon
        template: "{{templatename}}"
        disk:
          - size_gb: 50
            type: thin
            datastore: 3PAR_Datastore01
        hardware:
          memory_mb: 512
          num_cpus: 1
          scsi: paravirtual
        networks:
          - name: "OSC VLAN 4 172.16.9.0"
            type: dhcp
        customization:
         dns_servers:
         - 172.16.XX.XX
         - 172.16.XX.XX
         dns_suffix: OSHQ.oneshield.com
         hostname: "{{vm_name}}"
        wait_for_ip_address: no
      delegate_to: localhost
      register: deploy
[root@OSIANSIBLEIND instance]#
```
full run here. 
https://paste.fedoraproject.org/paste/G2hkExhHUzRkePQ3WlSj7w/deactivate/Me0h8YUrXlc6YhVxIQmPNwt033FQLwsEOtATaY74G9kWZDfSt7YXUfsM8JaOKhC7
