### ISSUE TITLE
vmware_guest fails to create vm with Ansible 2.4

### ISSUE THREAD

**Issue by grumpymatt** [ansible/ansible#32000]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/userid/ansible/vmware-provisioning/ansible.cfg
  configured module search path = [u'/home/userid/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]

```

##### CONFIGURATION

DEFAULT_LOG_PATH(/home/userid/ansible/vmware-provisioning/ansible.cfg) = /home/userid/ansible/vmware-provisioning/ansible.log
DEFAULT_ROLES_PATH(/home/userid/ansible/vmware-provisioning/ansible.cfg) = [u'/home/userid/ansible/vmware-provisioning/roles']
DEFAULT_STDOUT_CALLBACK(/home/userid/ansible/vmware-provisioning/ansible.cfg) = debug
HOST_KEY_CHECKING(/home/userid/ansible/vmware-provisioning/ansible.cfg) = False

##### OS / ENVIRONMENT

N/A

##### SUMMARY

vmware_guest fails to create the vm on ansible 2.4. Same playbook and task works with ansible 2.3

##### STEPS TO REPRODUCE

```yaml
- name: Create VM
  vmware_guest:
    hostname: "{{ vsphere.hostname }}"
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_password }}"
    validate_certs: no
    datacenter: "{{ vsphere.datacenter }}"
    folder: "{{ vsphere.folder }}"
    guest_id: "{{ vsphere_guest_id }}"
    name: "{{ vm_hostname }}"
    state: poweredon
    disk:
      - size_gb: "{{vm_specs.disk_size_gb}}"
        type: thin
        datastore: "{{vsphere.data_store}}"
    networks:
      - "{{ vsphere.build_network_params | combine({'ip': vm_ip}) }}"
    hardware:
      memory_mb: "{{vm_specs.ram_mb}}"
      num_cpus: "{{ vm_specs.cpus }}"
      osid: "{{ vsphere_guest_id }}"
      scsi: paravirtual
    cluster: "{{ vsphere.cluster }}"
    wait_for_ip_address: true

```

##### EXPECTED RESULTS

task should succeed and vm should be created

##### ACTUAL RESULTS

task fails

```
TASK [provision : Create VM] ********************************************************************************************************************************************************************************
task path: /home/userid/ansible/vmware-provisioning/roles/provision/tasks/provision-vm.yml:16
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: userid
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/userid/.ansible/tmp/ansible-tmp-1508526100.44-122451376304848 `" && echo ansible-tmp-1508526100.44-122451376304848="` echo /home/userid/.ansible/tmp/ansible-tmp-1508526100.44-122451376304848 `" ) && sleep 0'
<localhost> PUT /tmp/tmpopJeu6 TO /home/userid/.ansible/tmp/ansible-tmp-1508526100.44-122451376304848/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/userid/.ansible/tmp/ansible-tmp-1508526100.44-122451376304848/ /home/userid/.ansible/tmp/ansible-tmp-1508526100.44-122451376304848/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/userid/.ansible/tmp/ansible-tmp-1508526100.44-122451376304848/vmware_guest.py; rm -rf "/home/userid/.ansible/tmp/ansible-tmp-1508526100.44-122451376304848/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_q5x83he3/ansible_module_vmware_guest.py", line 1503, in <module>
    main()
  File "/tmp/ansible_q5x83he3/ansible_module_vmware_guest.py", line 1494, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_q5x83he3/ansible_module_vmware_guest.py", line 1292, in deploy_vm
    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)
UnboundLocalError: local variable 'resource_pool' referenced before assignment

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_q5x83he3/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible_q5x83he3/ansible_module_vmware_guest.py\", line 1494, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_q5x83he3/ansible_module_vmware_guest.py\", line 1292, in deploy_vm\n    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)\nUnboundLocalError: local variable 'resource_pool' referenced before assignment\n", 
    "module_stdout": "", 
    "rc": 0
}

MSG:

MODULE FAILURE

	to retry, use: --limit @/home/userid/ansible/vmware-provisioning/playbooks/provision-vms.retry

PLAY RECAP **************************************************************************************************************************************************************************************************
localhost                  : ok=25   changed=0    unreachable=0    failed=1   

```

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@grumpymatt Thanks for reporting this issue. Could you please try above patch and let me know if it works for you ?

**Comment by Akasurde** [comment]
resolved_by_pr #32674

**Comment by grumpymatt** [comment]
The patch above does seem to fix the issue with resource_pool. I am now getting a different error. Looks like it is already reported: #32032

**Comment by Akasurde** [comment]
Closing this issue as PR is merged. If issue persists, please re-open.

**Comment by ghost** [comment]
I cannot find how I can re-open this issue. let me know if I need to open another one

unfortunately, the issue is still there when the vm is NOT created from a template 

ansible 2.4.1.0
  config file = /root/svt/ops/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
[root@svt2-ansible ops]#

    - name: Create dummy VMs
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder_name }}"
        name: "{{ dummy_vm_prefix }}-{{ item }}"
        guest_id: "dosGuest"
        state: poweredoff
        hardware:
          memory_mb: "128"
          num_cpus: "1"
        disk:
        - size_gb: 1
          datastore: "{{ item }}"
          type: thin
      with_items: "{{ datastores }}"

failed: [svt2-ucp01] (item=Docker_SVT2) => {
    "changed": false,
    "failed": true,
    "item": "Docker_SVT2",
    "module_stderr": "Shared connection to svt2-ucp01 closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_7bj0T4/ansible_module_vmware_guest.py\", line 1503, in <module>\r\n    main()\r\n  File \"/tmp/ansible_7bj0T4/ansible_module_vmware_guest.py\", line 1494, in main\r\n    result = pyv.deploy_vm()\r\n  File \"/tmp/ansible_7bj0T4/ansible_module_vmware_guest.py\", line 1292, in deploy_vm\r\n    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)\r\nUnboundLocalError: local variable 'resource_pool' referenced before assignment\r\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}

On the other hand, this works

```
    - name: Create VMs without a data drive
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder_name }}"
        name: "{{ inventory_hostname }}"
        template: "{{ vm_template }}"
        state: poweredon
        disk:
          - size_gb:  "{{ disk1_size }}"
            type: thin
            datastore: "{{ datastores | random }}"
        hardware:
          memory_mb: "{{ ram }}"
          num_cpus: "{{ cpus }}"
      when: disk2_size is undefined

```

**Comment by Akasurde** [comment]
@chris7444 You need to use Ansible version 2.4.2.0 or latest version to get the fix. I think you are using 2.4.1.0

**Comment by ghost** [comment]
@Akasurde Yes, it is working with 2.4.2.0/Ubuntu . (2.4.1.0 on my RedHat 7.4 box)

**Comment by Akasurde** [comment]
@chris7444 Cool. Thanks for confirming.

**Comment by ghost** [comment]
well. Here is what happens when I run the following play **a second time** (1st time, the VM is created as expected)

```
\"/tmp/ansible_WELCm7/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 611, in serialize_spec\n  File \"/tmp/ansible_WELCm7/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 611, in serialize_spec\n  File \"/tmp/ansible_WELCm7/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 611, in serialize_spec\n  File \"/tmp/ansible_WELCm7/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 610, in serialize_spec\n  File \"/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py\", line 219, in __getattr__\n    return GetVmodlType(self.__name__ + \".\" +  attr)\n  File \"/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py\", line 1451, in GetVmodlType\n    ns, wsdlName = _GetWsdlInfo(name)\n  File \"/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py\", line 1598, in _GetWsdlInfo\n    return None, None\n  File \"/usr/lib/python2.7/threading.py\", line 216, in __exit__\n    self.release()\n  File \"/usr/lib/python2.7/threading.py\", line 213, in release\n    self._note(\"%s.release(): non-final release\", self)\nRuntimeError: maximum recursion depth exceeded\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```


full ansible.log at : [log](https://gist.github.com/chris7444/89c68c07fde6375b11e02377f6cb128d)

here the playbook
```
- hosts: ucp_main
  gather_facts: false
  become_user: root
  become: true

  vars_files:
    - ../group_vars/vars
    - ../group_vars/vault

  environment: "{{ env }}"

  tasks:
    - name: Create dummy VMs
      local_action:
        module: vmware_guest
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ folder_name }}"
        name: "{{ dummy_vm_prefix }}-{{ item }}"
        guest_id: "dosGuest"
        state: poweredoff
        hardware:
          memory_mb: "128"
          num_cpus: "1"
        disk:
        - size_gb: 1
          datastore: "{{ item }}"
          type: thin
      with_items: "{{ datastores }}"

```                           

and here is the version of ansible
```
root@clh-ubuntu:~/svt/ops# ansible --version
ansible 2.4.2.0
  config file = /root/svt/ops/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]


```

**Comment by merloon** [comment]
Hi, 
I have the same issue. 
Have you got any idea ? 

Regards,

**Comment by Akasurde** [comment]
@merloon Could you please elaborate more on error and playbook ? It will be easy to debug.

**Comment by merloon** [comment]
Hi @Akasurde ,

Sorry for the delay. 

my task: 
```
- name: add new disks on {{ vmware_vm_name }}
  vmware_guest:
    hostname: "{{ vmware_vsphere_server }}"
    username: "{{ vmware_vsphere_user }}"
    password: "{{ vmware_vsphere_pass }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter }}"
    cluster: "{{ vmware_cluster }}"
    guest_id: "{{ vmware_vm_name }}"
    name: "{{ vmware_vm_name }}"
    hardware:
      memory_mb: "{{ vmware_vm_hw_memory }}"
      num_cpus: "{{ vmware_vm_hw_cpu }}"
    disk:
    - size_gb: "{{ item.value.size }}"
      datastore: "{{ item.value.datastore }}"
      type: "{{ item.value.type }}"
  with_dict: "{{ disks }}"
```
My variables: 
```
disks:
  disk1:
      size: '6'
      datastore: LAB_Datastore_1
      type: thin
      usage: product
  disk2:
      size: '8'
      datastore: LAB_Datastore_1
      type: thin
      usage: files
```

Ansible version: 

```
ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
On 
```
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```
You can find logs attach 
[logs.txt](https://github.com/ansible/ansible/files/1667033/logs.txt)

Thanks by advance. 

BR 

Merloon

**Comment by merloon** [comment]
Hi, 

Any news ??

Regards,

Merloon.

**Comment by Akasurde** [comment]
@merloon Could you please open a new issue with your logs and playbook ? it will be easy to track things that way.

**Comment by ghost** [comment]
@merloon I have been working on that yesterday and found out that with 2.3 when willing to create a VM in a folder, I specified /myfolder. Now with 2.4, I should specify <datacenter_name>/vm/myfolder

```yaml
 tasks:
    - name: Create VMs without a data drive
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        esxi_hostname: "{{ esxi_host }}"
        datacenter: "{{ datacenter }}"
        folder: "{{ datacenter }}/vm{{ folder_name }}"
        name: "{{ inventory_hostname }}"
        template: "{{ vm_template }}"
        state: poweredon
        networks:
          - name: "{{ vm_portgroup }}"
            ip: "{{ ip_addr | ipaddr('address') }}"
            netmask: "{{ ip_addr | ipaddr('netmask') }}"
            gateway: "{{ gateway }}"
```
