### ISSUE TITLE
vmware_guest is not setting "customvalues" against vSphere 6.5

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/ansible#32004]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/spollock/ansible/fs-vmw-control/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]


```

##### OS / ENVIRONMENT

Running local on mac OSX
Running against vSphere 6.5 and ESXi 6.5

##### SUMMARY

customvalues are not added, vSphere responds with : " A specified parameter was not correct: key"

##### STEPS TO REPRODUCE

```yaml
- name: Set a custom value
  vmware_guest:
    validate_certs: no
    hostname: "{{ vcenterhostname }}"
    username: "{{ vcusername }}"
    password: "{{ vcpassword }}"
    datacenter: "{{ vcdatacenter }}"
    cluster: "{{ vccluster }}"
    resource_pool: "k{{ vctargetkit }}"
    uuid: 422bf5cb-b3b2-69ab-4053-21bcf7390d23
    name: 1201-pollockkit
    customvalues:
      - key: remotedisplay.vnc.port
        value: "7601"
    #state: poweredoff
  delegate_to: localhost
```

##### EXPECTED RESULTS

Should have set the customvalue for remotedisplay.vnc.port

##### ACTUAL RESULTS

Nothing, error message below

Note: this can be entered manually into vSphere under advanced parameters and it works fine.

```
"msg": "Failed to set custom value for key='remotedisplay.vnc.port' and value='7601'. Error was: (vmodl.fault.InvalidArgument) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'A specified parameter was not correct: key',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   invalidProperty = u'key'\n}"
```

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jacksonp2008** [comment]
I have also verified that this exhibits the same behavior with vCenter 6.0.

There is a workaround however, you can set these values using the older "vsphere_guest" using vm_extra_config:

    - name: using vsphere_guest
      vsphere_guest:
        vcenter_hostname: "{{ vcenterhostname }}"
        username: "{{ vcusername }}"
        password: "{{ vcpassword }}"
        resource_pool: "k{{ vctargetkit }}"
        validate_certs: no
        guest: 6601-pollockkit
        state: reconfigured
        esxi:
          datacenter: "{{ vcdatacenter }}"
        vm_extra_config:
          remotedisplay.vnc.port: "7666"

**Comment by Akasurde** [comment]
@jacksonp2008 I have tried to set values using `pyvmomi` but unable to set it. I have filed an issue against `pyvmomi`,  you can find the details [here](https://github.com/vmware/pyvmomi/issues/622).

**Comment by Akasurde** [comment]
@jacksonp2008 Could you please check above patch and let me know if it works for you ?

**Comment by Akasurde** [comment]
resolved_by_pr #33454

**Comment by Akasurde** [comment]
@jacksonp2008 Any news?

**Comment by nilloBE** [comment]
Is there a fix for this? I have been testing with 2.5 and I can't set the custom attributes with neither vmware_guest nor vsphere_guest. I do not get an error, but it does not work. 

my tests:
```
  - vmware_guest:
       validate_certs: False
       hostname: "{{ vcenter_hostname }}"
       username: "{{ vcenter_user }}"
       password: "{{ vcenter_pass }}"
       datacenter: "{{ datacenter }}"
       cluster: "{{ cluster_01 }}"
       name: "{{ inventory_hostname }}"
       folder: "{{ vm_folder_name }}"
       customvalues:
          - key: app
            value: opencart
       state: present
```
and 
```
  - vsphere_guest:
      vcenter_hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      validate_certs: no
      guest: "{{ inventory_hostname }}"
      state: reconfigured
      esxi:
         datacenter: "{{ datacenter }}"
      vm_extra_config:
         app: "opencart"
```
Can anyone share a working example?

**Comment by jacksonp2008** [comment]
This works for me, haven't had a chance to try the fix mentioned above:

```
vsphere_guest:
    vcenter_hostname: "{{ vcenterhostname }}"
    username: "{{ vcusername }}"
    password: "{{ vcpassword }}"
    resource_pool: "k{{ vcpool }}"
    guest: "{{ guest name}}”
    state: reconfigured
    esxi:
      datacenter: "{{ vcdatacenter }}"
    vm_extra_config:
      remotedisplay.vnc.port: "{{ display port }}"
      remotedisplay.vnc.enabled: "true"
      remotedisplay.vnc.password: “password”
```

**Comment by Akasurde** [comment]
@nilloBE I am not sure about what is "app" in your example. Could you please elaborate more on that ?

**Comment by nilloBE** [comment]
Thanks @jacksonp2008 and @Akasurde for looking into this. I believe I may have miss interpreted what customvalues does. "app" in my example is a Custom Attribute defined in vCenter annotations. There are two options there, Notes, and custom attributes. I am trying to set the latter.

But from your questions, and teh example from @jacksonp2008 I believe customvalues and vm_extra_config cannot configure Custom Attributes, but instead customize the VM values. 

I guess my bad understanding of the scope of the module ... thanks again guys.

**Comment by lukasmrtvy** [comment]
I dont know how to use this. Can anyone help?
```
vmware_guest:
    ...
    customvalues:
      - key: "rtc.diffFromUTC"
        value: "0"
```

```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Failed to set custom value for key='rtc.diffFromUTC' and value='0'. Error was: (vmodl.fault.InvalidArgument) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'A specified parameter was not correct: key',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [],\n   invalidProperty = u'key'\n}"}

```
