### ISSUE TITLE
Variable is set even in skipped block

### ISSUE THREAD

**Issue by gamename** [ansible/ansible#32013]
- Bug Report

##### COMPONENT NAME
playbook

##### ANSIBLE VERSION
```
ok: [localhost] => {
    "ansible_version": {
        "full": "2.4.0.0",
        "major": 2,
        "minor": 4,
        "revision": 0,
        "string": "2.4.0.0"
    }
}
```

##### CONFIGURATION
$ ansible-config dump --only-changed
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False

##### OS / ENVIRONMENT
N/A

##### SUMMARY
A variable is registered even when the block containing it is skipped.  

##### STEPS TO REPRODUCE
Run the playbook pasted below 

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    foo: bar

  tasks:
    - name: get Ansible version
      debug: var=ansible_version

    - name: Block1
      block:
          - name: Block1 shell call
            shell: echo "bar"
            register: block_result
      when: foo == "bar"

    - name: debug1
      debug: var=block_result

    - name: Block2
      block:
          - name: Block2 shell call
            shell: echo "baz"
            register: block_result
      when: foo == "baz"

    - name: debug2
      debug: var=block_result
```

##### EXPECTED RESULTS
The debug output of debug2 should be the same as the output of debug1 because Block2 was skipped. In other words, the variable "block_result" should be set in the block that is not skipped and remain untouched.

##### ACTUAL RESULTS
The variable "block_result" was still touched in the skipped block. The output from debug2 shows the variable was re-registered with new output. 

```
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available


PLAY [localhost] *************************************************************************************************************************************************************************

TASK [get Ansible version] ***************************************************************************************************************************************************************
ok: [localhost] => {
    "ansible_version": {
        "full": "2.4.0.0",
        "major": 2,
        "minor": 4,
        "revision": 0,
        "string": "2.4.0.0"
    }
}

TASK [Block1 shell call] *****************************************************************************************************************************************************************
changed: [localhost]

TASK [debug1 block_result] ***************************************************************************************************************************************************************
ok: [localhost] => {
    "block_result": {
        "changed": true,
        "cmd": "echo \"bar\"",
        "delta": "0:00:00.008565",
        "end": "2017-10-21 16:36:56.454819",
        "failed": false,
        "rc": 0,
        "start": "2017-10-21 16:36:56.446254",
        "stderr": "",
        "stderr_lines": [],
        "stdout": "bar",
        "stdout_lines": [
            "bar"
        ]
    }
}

TASK [Block2 shell call] *****************************************************************************************************************************************************************
skipping: [localhost]

TASK [debug2 block_result] ***************************************************************************************************************************************************************
ok: [localhost] => {
    "block_result": {
        "changed": false,
        "skip_reason": "Conditional result was False",
        "skipped": true
    }
}

PLAY RECAP *******************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0
```
