### ISSUE TITLE
vmware_guest module does not create disks on update

### ISSUE THREAD

**Issue by makesse** [ansible/ansible#32029]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest module

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

No modifications to ansible.cfg have been made, Ansible Tower is used

##### OS / ENVIRONMENT

RHEL 7.4, kernel 3.10.0-693.2.2.el7.x86_64
Ansible Tower 3.1.5
VMWare vSphere 6.5

##### SUMMARY

I would like to be able to add new VMWare disks to a running VM. When I define new disks by modifying the "disks" parameter and run my playbook they are not added. When I delete the machine and re-create the machine with the same playbook the disks are added.

##### STEPS TO REPRODUCE

Create the VM with the following task:

```
- name: Create VM
  delegate_to: localhost
  vmware_guest:
    cluster: "cluster_a"
    customization:
      dns_servers:
        - "192.168.0.1"
      domain: "example.com"
      hostname: "example001"
    datacenter: "dc_a"
    disk:
      - autoselect_datastore: "True"
        datastore: "filter_a"
        size_gb: 60
    folder: "/vm/folder"
    hardware:
      memory_mb: "4096"
      num_cpus: "2"
      scsi: paravirtual
    name: "example001"
    networks:
      - device_type: vmxnet3
        ip: "192.168.0.10"
        gateway: "192.168.0.1"
        name: "vmware_virtual_network"
        netmask: "255.255.255.0"
        type: static
    state: poweredon
    template: "rhel_source_template"
    validate_certs: "False"
    wait_for_ip_address: "yes"
```

Now modify the task to add an additional disk:

```
- name: Create VM
  delegate_to: localhost
  vmware_guest:
    cluster: "cluster_a"
    customization:
      dns_servers:
        - "192.168.0.1"
      domain: "example.com"
      hostname: "example001"
    datacenter: "dc_a"
    disk:
      - autoselect_datastore: "True"
        datastore: "filter_a"
        size_gb: 60
      - autoselect_datastore: "True"
        datastore: "filter_a"
        size_gb: 20
    folder: "/vm/folder"
    hardware:
      memory_mb: "4096"
      num_cpus: "2"
      scsi: paravirtual
    name: "example001"
    networks:
      - device_type: vmxnet3
        ip: "192.168.0.10"
        gateway: "192.168.0.1"
        name: "vmware_virtual_network"
        netmask: "255.255.255.0"
        type: static
    state: poweredon
    template: "rhel_source_template"
    validate_certs: "False"
    wait_for_ip_address: "yes"
```

##### EXPECTED RESULTS

A second disk of size 20GB is added to the running VM

##### ACTUAL RESULTS

The task runs without errors but no additional disks are being added.
