### ISSUE TITLE
vmware_guest - Create vm from template with custom IP settings clean the DNS settings

### ISSUE THREAD

**Issue by jffz** [ansible/ansible#32044]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT
CentOs 7.4

##### STEPS TO REPRODUCE

```yml
 - name: "Create VM from template"
      vmware_guest:
        hostname: "{{ hostname }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: poweredon
        template: "{{ template_name }}"
        guest_id: centos64Guest
        name: "{{ item }}"
        networks:
        - name: "{{ network }}"
          vlan: "{{ vlan }}"
          type: static
          ip: "{{ ip }}"
          netmask: "255.255.192.0"                              
          gateway: "{{ ip.split('.')[0:3] | join('.') }}.35"    
          device_type: vmxnet3
        validate_certs: False
        wait_for_ip_address: yes
      delegate_to: localhost
      with_items: "{{ inventory_hostname }}"
      register: vm_infos
```

##### EXPECTED RESULTS
Don't touch /etc/resolv.conf file if dns_seervers is not set or make it edit the resolv.conf

##### ACTUAL RESULTS
`/etc/resolv.conf` empty after vm creation
