### ISSUE TITLE
vsphere_guest - cdrom configuration crash the plugin (2.3 - 2.4)

### ISSUE THREAD

**Issue by jffz** [ansible/ansible#32043]
##### ISSUE TYPE

 - Trying to use cdrom configuration parameters from the module seems to crash

##### COMPONENT NAME
vsphere_guest

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_PIPELINING(/etc/ansible/ansible.cfg) = True
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /etc/ansible/facts
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = all
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} on {host}
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 22
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
DEFAULT_SQUASH_ACTIONS(/etc/ansible/ansible.cfg) = ['apk', 'apt', 'dnf', 'package', 'pacman', 'pkgng', 'yum', 'zypper']
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /root/.ansible-retry

##### OS / ENVIRONMENT
CentOs 7.4

##### SUMMARY
Using vsphere_guests with cdrom parameters crash the module, using it's parameter without state: reconfigured seems to work but the cdrom drive isn't created into the vm unfortunaly

##### STEPS TO REPRODUCE
Use vmware_guest with ansible 2.4.0.0

```yaml
- name: "Configure VM Params"
      vsphere_guest:
        vcenter_hostname: "{{ vcenter_hostname }}"
        username: "{{ username }}"
        password: "{{ password }}"
        guest: "{{ inventory_hostname }}"
        state: reconfigured
        validate_certs: no
        vm_extra_config:
          vcpu.hotadd: yes
          mem.hotadd:  yes
          notes: "{{ notes }}"
        vm_hardware:
          osid: "{{ osid }}"
          vm_cdrom:
            type: "iso"
            iso_path: "{{ datastore }}/ISO/ipxe/ipxe_vlan{{ vlan }}.iso"
            state: reconfigured 
	  
```

##### EXPECTED RESULTS
Make the module works

##### ACTUAL RESULTS
Ansible 2.3.0.0
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'set_element_backing'
fatal: [testvm]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_I4fVwz/ansible_module_vsphere_guest.py\", line 1918, in <module>\n    main()\n  File \"/tmp/ansible_I4fVwz/ansible_module_vsphere_guest.py\", line 1845, in main\n    force=force\n  File \"/tmp/ansible_I4fVwz/ansible_module_vsphere_guest.py\", line 961, in reconfigure_vm\n    cdrom.set_element_backing(iso)\nAttributeError: 'NoneType' object has no attribute 'set_element_backing'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

```

Ansible 2.4.0.0
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'set_element_backing'
fatal: [testvm]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_pRgDqk/ansible_module_vsphere_guest.py\", line 1937, in <module>\n    main()\n  File \"/tmp/ansible_pRgDqk/ansible_module_vsphere_guest.py\", line 1860, in main\n    force=force\n  File \"/tmp/ansible_pRgDqk/ansible_module_vsphere_guest.py\", line 963, in reconfigure_vm\n    cdrom.set_element_backing(iso)\nAttributeError: 'NoneType' object has no attribute 'set_element_backing'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```
