### ISSUE TITLE
vmware_guest broke in 2.4.0.0

### ISSUE THREAD

**Issue by jffz** [ansible/ansible#32042]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_PIPELINING(/etc/ansible/ansible.cfg) = True
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /etc/ansible/facts
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = all
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} on {host}
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 22
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
DEFAULT_SQUASH_ACTIONS(/etc/ansible/ansible.cfg) = ['apk', 'apt', 'dnf', 'package', 'pacman', 'pkgng', 'yum', 'zypper']
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /root/.ansible-retry

##### OS / ENVIRONMENT
CentOs 7.4

##### SUMMARY
Using vmware_guests on ansible 2.4.0.0 seems to be broken, fixed by downgrading to 2.3.0.0

##### STEPS TO REPRODUCE
Use vmware_guest with ansible 2.4.0.0

```yaml
- name: "Create VM"
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        username: "{{ username }}"
        password: "{{ password }}"
        state: present
        guest_id: centos64Guest
        name: "{{ item }}"
        networks:
        - name: "{{ network }}"
          vlan: "{{ vlan }}"
          type: static
          ip: "{{ ip }}"
          netmask: "255.255.255.0"
          gateway: "{{ ip.split('.')[0:3] | join('.') }}.1"
          dns_servers: "172.20.11.100"
          device_type: vmxnet3
        disk:
        - size_gb: "{{ disk }}"
          type: thin
          autoselect_datastore: True
          #datastore: "{{ datastore }}"
        hardware:
          memory_mb: "{{ memory }}"
          num_cpus: "{{ cpucount }}"
          scsi: paravirtual
        validate_certs: False
      delegate_to: localhost
      with_items: "{{ inventory_hostname }}"
	  
```

##### EXPECTED RESULTS
Make the module works

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'name'
failed: [testvm -> localhost] (item=testvm) => {"changed": false, "failed": true, "item": "testvm", "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py\", line 1503, in <module>\n    main()\n  File \"/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py\", line 1494, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_WVZUZg/ansible_module_vmware_guest.py\", line 1189, in deploy_vm\n    dcpath = compile_folder_path_for_object(datacenter)\n  File \"/tmp/ansible_WVZUZg/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 237, in compile_folder_path_for_object\nAttributeError: 'NoneType' object has no attribute 'name'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

```
