### ISSUE TITLE
When command/shell outputs JSON, its result should be immediately parseable

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#32056]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
command, shell

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /.../ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /opt/lib/python2.7/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 11:37:53) [GCC 4.2.1 Compatible FreeBSD Clang 5.0.0 (tags/RELEASE_500/final 312559)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When the command executed by the `command` (or `shell`) module produces JSON on stdout, it should be immediately available (parsed) within the task.

##### STEPS TO REPRODUCE

```yaml
- name: Upgrade global npm-packages to their latest versions
  command: npm -g install {% if ansible_check_mode %}--dry-run{% endif %} --json
    {% for npm in npms %} {{ npm }}{% endfor %}
  check_mode: ansible_check_mode
  register: npm
  changed_when: |
    npm['dependencies']['added'] | count > 0 or
    npm['dependencies']['removed'] | count > 0 or
    npm['dependencies']['updated'] | count > 0 or
    npm['dependencies']['moved'] | count > 0
```

##### EXPECTED RESULTS
The `npm.changed` set depending on whether or not any of the installed NPMs were updated.

##### ACTUAL RESULTS
An error occurs.

```
fatal: [example.com]: FAILED! => {"failed": true, "msg": "The conditional check 'npm['dependencies']['removed'] | count > 0 or\nnpm['dependencies']['updated'] | count > 0 or\nnpm['dependencies']['moved'] | count > 0\n' failed. The error was: error while evaluating conditional (npm['dependencies']['removed'] | count > 0 or\nnpm['dependencies']['updated'] | count > 0 or\nnpm['dependencies']['moved'] | count > 0\n): 'dict object' has no attribute 'dependencies'"}
```

I know, I can use a separate `setfact`-task to assign the "registered" stdout to some fact:
```yaml
- name: Parse results of npm-upgrade
  setfact:
    npmoutput: "{{ npm.stdout | to_json }}"
```
but it will be too late by then to mark the previous task as unchanged...

Maybe, automatically parsing stdout of _all_ commands is too expensive and useless -- so the flag needs to be added to `command` (and `shell`) module for its stdout (and/or stderr) automatically parsed and available immediately _within the task_ -- such as to be used in `when_changed` as above.
