### ISSUE TITLE
win_scheduled_task: frequency is required

### ISSUE THREAD

**Issue by valerius257** [ansible/ansible#32073]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_scheduled_task

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Ansible Host: CentOS 7
Managing: Windows 2012 R2

##### SUMMARY

win_scheduled_task failed with error "Get-AnsibleParam: Missing required argument: frequency"
but according to the documentation http://docs.ansible.com/ansible/latest/win_scheduled_task_module.html it is not required parameter

##### STEPS TO REPRODUCE

```yaml
- name: add xComputerManagement module to manage scheduler
  win_psmodule:
    name: xComputerManagement
    state: present

- name: Invoke DSC
  win_dsc:
   resource_name: xScheduledTask
   TaskName : newtask
   ScheduleType: AtLogOn
   ActionExecutable: notepad.exe
   MultipleInstances: IgnoreNew
   Priority: 5
   RestartCount: 5

- name: set credentials for task
  win_scheduled_task:
    name: newtask
    user: "{{ WINDOWS_USER }}"
    runlevel: highest
```

##### EXPECTED RESULTS

task 'set credentials for task' should just update credentials for task created by win_dsc

##### ACTUAL RESULTS

win_scheduled_task failed

```
fatal: [host]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Get-AnsibleParam: Missing required argument: frequency"
}
```
