### ISSUE TITLE
vmware_guest cloning from template with two network cards puts missmatched VLAN id

### ISSUE THREAD

**Issue by marcingarstka** [ansible/ansible#32075]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

DEFAULT_GATHERING(/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = [u'/ansible/inventory.yml']
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

vSphere 6.0
CentOS Linux release 7.4.1708 - guest virtual machine
##### SUMMARY

When creating new virtual machine using vmware_guest module from time to time I receive mismatched network name (vlan id). My template which I am cloning from has two network adapters installed by default and I expect from a new virtual machine to have also two network adapters on board. The problem is that first network card receives network name from the second adapter and vice versa.
##### STEPS TO REPRODUCE

To reproduce this issue you have to run playbooks few times in a row to get this unstandard behaviour.

```yaml
- hosts: vc01
  gather_facts: false
  connection: local
  vars_files:
     - /ansible/vars/API.GATEWAY/INT/SRV01_VARS.yml

  tasks:

   - name: DEPLOYING 2-NIC IMAGE ON {{ vCenterCluster }} USING {{ Template }} IN {{ datacenter }}
     vmware_guest:
       hostname: "{{ vCenter }}"
       username: "{{ vuser }}"
       password: "{{ vpass }}"
       validate_certs: no
       datacenter: "{{ datacenter }}"
       cluster: "{{ vCenterCluster }}"
       name: "{{ CompHost }}"
       annotation: "{{ Role }}"
       state: poweredon
       guest_id: "{{ Os }}"
       template: "{{ Template }}"
       hardware:
         memory_mb: "{{ Memory }}"
         num_cpus: "{{ vCPU }}"
       networks:
       - name: "VLAN-{{ vLAN }}"
         device_type: "{{ vNet }}"
         ip: "{{ vIP }}"
         netmask: "{{ vMask }}"
         gateway: "{{ vGateway }}"
       - name: "VLAN-{{ vLAN2 }}"
         device_type: "{{ vNet }}"
         ip: "{{ vIP2 }}"
         netmask: "{{ vMask2 }}"
       wait_for_ip_address: yes
       customization:
         dns_servers:
         - "{{ DNSServer }}"
         - "{{ DNSServer2 }}"
         dns_suffix: "{{ CompDomain }}"
         domain: "{{ CompDomain }}"
     when: vNICs == 2

Additionaly here is vars file:
# NETWORK CONFIGURATION
vNICs: 2
vNet: vmxnet3
vLAN: 701
vIP: 10.208.201.5
vMask: 255.255.255.224
vGateway: 10.208.201.30
vLAN2: 709
vIP2: 10.208.202.5
vMask2: 255.255.255.224
vGateway2: 10.208.202.30

# ACTIVE DIRECTORY, DNS CONFIGURATION
CompHost: srv01
CompDomain: berlin.de
DNSServer: 10.208.218.6
DNSServer2: 10.208.218.7
Role: "TEST image"

# VCENTERC CONFIGURATION
vuser: secretuser@vsphere.local
vpass: "secretpass"
vCenter: vc01.berlin.de
vCenterCluster: BERLINWEST
datacenter: BERLIN
Os: centos64Guest
Template: IMGAPIDEV
vCPU: 2
Memory: 4096
```

##### EXPECTED RESULTS

```yaml
changed: [vc01] => {
    "changed": true,
    "failed": false,
    "instance": {
        "annotation": "TEST image",
        "current_snapshot": null,
        "customvalues": {},
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "2147483647",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": [
                "10.208.201.5",
                "fe80::250:56ff:feb9:1131"
            ],
            "label": "Network adapter 1",
            "macaddress": "00:50:56:b9:11:31",
            "macaddress_dash": "00-50-56-b9-11-31",
            "summary": "VLAN-701"
	 },
        "hw_eth1": {
            "addresstype": "assigned",
            "ipaddresses": [
                "10.208.202.5",
                "fe80::250:56ff:feb9:2af6"
            ],
            "label": "Network adapter 2",
            "macaddress": "00:50:56:b9:2a:f6",
            "macaddress_dash": "00-50-56-b9-2a-f6",
            "summary": "VLAN-709"
        },
        "hw_guest_full_name": "Linux 3.10.0-693.2.2.el7.x86_64 CentOS Linux release 7.4.1708 (Core) ",
        "hw_guest_id": "",
        "hw_interfaces": [
            "eth0",
            "eth1"
        ],
        "hw_memtotal_mb": 4096,
        "hw_name": "srv01",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 2,
        "hw_product_uuid": "42392152-21a9-7e88-bde9-f924608851c0",
        "ipv4": "10.208.201.5",
        "ipv6": "fe80::250:56ff:feb9:1131",
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": "TEST image",
            "cluster": "BERLINWEST",
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "dns_suffix": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "BERLIN",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": "centos64Guest",
            "hardware": {
                "memory_mb": 4096,
                "num_cpus": 2
            },
            "hostname": "vc01.berlin.de",
            "is_template": false,
            "linked_clone": false,
            "name": "srv01",
            "name_match": "first",
            "networks": [
		{
                    "device_type": "vmxnet3",
                    "gateway": "10.208.201.30",
                    "ip": "10.208.201.5",
                    "name": "VLAN-701",
                    "netmask": "255.255.255.224"
                },
                {
                    "device_type": "vmxnet3",
                    "ip": "10.208.202.5",
                    "name": "VLAN-709",
                    "netmask": "255.255.255.224"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "IMGAPIDEV",
            "username": "secretuser@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    }
}
```
##### ACTUAL RESULTS

```yaml
changed: [vc01] => {
    "changed": true,
    "failed": false,
    "instance": {
        "annotation": "TEST image",
        "current_snapshot": null,
        "customvalues": {
            "ClusterInvariantVMMId": "c9801d42-09b2-4e4d-a141-fddd73c0fa9e"
        },
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "2147483647",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": [
                "10.208.201.5",
                "fe80::250:56ff:feb9:4e18"
            ],
            **"label": "Network adapter 1",**
            "macaddress": "00:50:56:b9:4e:18",
            "macaddress_dash": "00-50-56-b9-4e-18",
            **"summary": "VLAN-709"**
        },
        "hw_eth1": {
            "addresstype": "assigned",
            "ipaddresses": [
                "10.208.202.5",
                "fe80::250:56ff:feb9:4f5b"
            ],
            **"label": "Network adapter 2",**
            "macaddress": "00:50:56:b9:4f:5b",
            "macaddress_dash": "00-50-56-b9-4f-5b",
            **"summary": "VLAN-701"**
        },
        "hw_guest_full_name": "Linux 3.10.0-693.2.2.el7.x86_64 CentOS Linux release 7.4.1708 (Core) ",
        "hw_guest_id": "",
        "hw_interfaces": [
            "eth0",
            "eth1"
        ],
	"hw_memtotal_mb": 4096,
        "hw_name": "srv01",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 2,
        "hw_product_uuid": "42395071-8639-0cd2-3fdc-24a26e22f052",
        "ipv4": "10.208.202.5",
        "ipv6": "fe80::250:56ff:feb9:4f5b",
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": "TEST image",
            "cluster": "BERLINWEST",
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "dns_suffix": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "BERLIN",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": "centos64Guest",
            "hardware": {
                "memory_mb": 4096,
                "num_cpus": 2
            },
            "hostname": "vc01.berlin.de",
            "is_template": false,
            "linked_clone": false,
            "name": "srv01",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "gateway": "10.208.201.30",
                    "ip": "10.208.201.5",
                    "name": "VLAN-701",
                    "netmask": "255.255.255.224"
                },
                {
                    "device_type": "vmxnet3",
                    "ip": "10.208.202.5",
                    "name": "VLAN-709",
                    "netmask": "255.255.255.224"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "IMGAPIDEV",
            "username": "secretuser@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    }
}
```
