### ISSUE TITLE
seboolean modules works incorrectly on debian

### ISSUE THREAD

**Issue by vladimirtiukhtin** [ansible/ansible#32081]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
seboolean module

##### ANSIBLE VERSION
```
ansible 2.4.0.0
```

##### OS / ENVIRONMENT

Debian 9.0
Python 3.5

##### SUMMARY
seboolean module doesn not work on debian system. Could be related to https://github.com/ansible/ansible/issues/25112

##### STEPS TO REPRODUCE
Create task like:
```yaml
- name: allow bind to create dynamic zone files
  seboolean:
    name: named_write_master_zones
    state: yes
    persistent: yes
```
apply it on debian system, you will get
```
    "msg": "SELinux boolean named_write_master_zones does not exist."
```

##### EXPECTED RESULTS
boolean applied

##### ACTUAL RESULTS
task fails with:
```
    "msg": "SELinux boolean named_write_master_zones does not exist."
```
