### ISSUE TITLE
jenkins_job module causes the replacement of HTML entities within config.xml of the jenkins job

### ISSUE THREAD

**Issue by tbar74235** [ansible/ansible#32113]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
jenkins_job

##### ANSIBLE VERSION
```
ansible 2.2.2.0
  config file = /opt/jboss/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
not relevant

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The module jenkins_job offers the possibility to handover a xml-File which is going to be the config.xml file for the job in jenkins you like to create. The xml-File I handover to the jenkins_job module via the option "config" contains HTML Entities like 

& q u o t ; 
& a p o s ; 
& g t ; 
& l t ;

If the job is created within jenkins and I have a look at the config.xml within jenkins I see that all the HTML entities are replaced with the real characters " ' > <
This leads to problems sometimes. Especially when I use Active Choices Parameters within a jenkins job. So some parts doesn't appear if I call the job. 
To solve my problem I have to open configure job and save without changing anything. In the background jenkins replaces the characters " ' > < with the HTML entities and everything is fine when I start the job after that.

##### STEPS TO REPRODUCE
- Use the module jenkins_job
- Handover a job xml with html entities to the jenkins_job module
- Let the jenkins_job create your job in jenkins
- Have a look at the config.xml within jenkins (not via GUI). Take a look at the config.xml directly on filesystem

```
---
- hosts: 127.0.0.1

  tasks:
  - name: "create my_jenkins_job in jenkins"
    jenkins_job:
      config: "{{ lookup('file', 'myjenkinsjobtemplate.xml') }}"
      name: "my_jenkins_job"
      token: "myawesometoken"
      url: "https://myjenkins"
      user: "myUser"
  run_once: true
```

##### EXPECTED RESULTS
I would expect that the config.xml within jenkins contains all the HTML Entities like my handed over xml after the job creation via the jenkins_job module.

##### ACTUAL RESULTS
All the HTML Entities are replaced by characters in the config.xml within jenkins after the job creation via the jenkins_job module.

**Comment by ansibot** [comment]
cc @sermilrod
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sermilrod** [comment]
Hi @tbar74235 I am happy to have a look on this issue. Can you provide me more detailed information? 

It would be helpful to have an xml sample that fails for you to reproduce it (as I have been using the module with templates containing html code and I have never seen this issue before) and the exact jenkins version that you are using.

Thanks!

**Comment by gundalow** [comment]
http://docs.ansible.com/ansible/latest/dev_guide/developing_modules_checklist.html#contributing-modules-checklist states
> The shebang must always be `#!/usr/bin/python`. This allows `ansible_python_interpreter` to work

**Comment by cahlchang** [comment]
I think that this issue behaves according to Jenkins' specifications.

These special characters are prohibited characters in XML.
Therefore, Jenkins which defines job in XML may be performing escape processing.

If you use special characters such as HTML, handling using the template module may work.

e.g.
> ansible.cfg

```
jinja2_extensions = jinja2.ext.autoescape
```

> config.xml.j2
```
{% autoescape true %}
{{ any_strings }}
{% endautoescape %}
```

> playbook
```
  - name: register job
    jenkins_job:
      name: my_job_name
      config: "{{ lookup('template', 'config.xml.j2') }}" 
      user: user
      token: token
      state: present
```

Also, I think that putting the option to escape XML is also a solution, but I do not know if it is correct.
