### ISSUE TITLE
consul_kv: Don't get double quoted values when inserting JSON

### ISSUE THREAD

**Issue by adomenech73** [ansible/ansible#32127]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

consul_kv

##### ANSIBLE VERSION

```Bash
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/adomenech/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```
##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When using consul_kv module to store JSON data as string value, double quoted JSON is changes to single quoted one inside consul

##### STEPS TO REPRODUCE

First we add json values to consul like:

```yaml
tasks:
    - name: load configuration to consul
      consul_kv:
        key: {{ item.key }}
        value: "{{ item.value}}"
      with_items:
        - key: key1
          value: ‘{"hosts":["https://host1:80”,”https://host2:80”,”https://host3:80”],”apiVersion":"5"}'
        - key: key2
          value: ‘{"default":{"appenders":["ms","console"],"level":"debug"}}’
```
After we check for values from agent with:

```Bash
consul kv get -recurse
```

##### EXPECTED RESULTS

```Bash
key1:’{“hosts":["https://host1:80”,”https://host2:80”,”https://host3:80”],”apiVersion”:”5”}’
key2:’{"default":{"appenders":["ms","console"],"level":"debug"}}’
```

##### ACTUAL RESULTS

```Bash
key1:”{‘hosts’:[‘https://host1:80','https://host2:80','https://host3:80'],'apiVersion’:'5’}”
key2:”{‘default’:{‘appenders’:[‘ms’,’console’],’level’:’debug’}}”
```

**Comment by ansibot** [comment]
cc @sgargan
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by adomenech73** [comment]
I solved !! I just needed use of a string filter as:

```yaml
- name: add or update the value associated with a key in the key/value store
  consul_kv:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  with_items: "{{ kvs }}"
```
