### ISSUE TITLE
getent - register broken in 2.4 when using with_items

### ISSUE THREAD

**Issue by mj84** [ansible/ansible#32148]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
getent

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
ANSIBLE_SSH_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
Ansible Host: CentOS 7.4
Managed systems: CentOS 7.4 / RHEL 7.4
##### SUMMARY
Since the update to Ansible 2.4, the module getent does not work properly anymore when using it `with_items` and storing the output using `register`.
Previously, results of all iterations could be found in the variable, now only the last item is stored in the variable.

##### STEPS TO REPRODUCE
```yaml
---
- name: Testing the getent module in Ansible 2.4
  hosts: all
  tasks:
    - name: Read shadow entries for all administrative users
      local_action: getent database=shadow key={{ item }}
      with_items:
        - root
        - bin
      run_once: True
      register: getent_shadow
    - name: Show shadow
      local_action: debug var="{{ getent_shadow }}"
      run_once: true
...
```
##### EXPECTED RESULTS
The list getent_shadow contains an entry for each item.

##### ACTUAL RESULTS
The list getent_shadow only contains one entry for the last item:
```
ok: [localhost -> localhost] => (item=getent_shadow) => {
    "getent_shadow": {
        "bin": [
            "*",
            "17110",
            "0",
            "99999",
            "7",
            "",
            "",
            ""
        ]
    },
    "item": "getent_shadow"
}
```
On a side note, when i change the task e.g. like this (in order to use a different module):
```yaml
local_action: debug msg={{ item }}
````
then the problem does not occur.

**Comment by ansibot** [comment]
cc @bcoca
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by onitake** [comment]
Interestingly, this works for me. I use Ansible 2.4.0.0 too.

I suspect that you don't get the expected result because your `register` variable has the same name as the implicit module result variable.
If you change it to something different, you will get the standard `register` result dictionary, and all items are included.

**Comment by onitake** [comment]
On the other hand, I think built-in support for `with_items` would be very useful.
The `register` result is much less convenient to use than `getent_<database>`.

**Comment by bcoca** [comment]
the modules cannot do this itself, as facts get aggregated on the controller side ... we can make it easier for controller to keep the multiple returns .. but it is a breaking change with current documented return

`ansbile_facts['getent']['shadow'][<uid>]`

**Comment by onitake** [comment]
Actually, since the key argument is already part of the return value, this would not be a breaking change.

Passing a list of users would just yield a dictionary with multiple entries. The semantics would stay the same for the single-key case.

**Comment by onitake** [comment]
(or, perhaps I misunderstood you and you were referring to the module code, not the usage)

**Comment by bcoca** [comment]
both, my proposal is BREAKING the currently unified `getent_<key>` in favor of a dictionary that is mergable

**Comment by onitake** [comment]
I'm sorry, I really don't understand.

My impression is that
```
    "getent_shadow": {
        "bin": [
            "*",
            "17110",
            "0",
            "99999",
            "7",
            "",
            "",
            ""
        ]
    }
```
is a subset of
```
    "getent_shadow": {
        "bin": [
            "*",
            "17110",
            "0",
            "99999",
            "7",
            "",
            "",
            ""
        ],
        "root": [
            "*",
            "17110",
            "0",
            "99999",
            "7",
            "",
            "",
            ""
        ]
    }
```

Since the former result already has to be accessed like this:
```
getent_shadow["bin"][0]
```
there wouldn't be any difference in usage if there is a second key besides `"bin"`.

What am I missing?

**Comment by bcoca** [comment]
not really, it is a subkey of ansible_facts .. they just get injected in the top level (changing in 2.5)

**Comment by onitake** [comment]
I really must be thick, I'm not seeing it.

What's the difference in semantics between
```
ansbile_facts['getent']['shadow'] = {
    "bin": [1, 2, 3]
}
```
and
```
ansbile_facts['getent']['shadow'] = {
    "bin": [1, 2, 3],
    "root": [1, 2, 3]
}
```
?

`ansbile_facts['getent']['shadow']['bin']` would work just like before.
There is just another key in the dictionary besides 'bin'.

**Comment by mj84** [comment]
@onitake: Thanks a lot for the hint regarding the internal result variable!
Changing my `register` variable to something else indeed made a difference with 2.4.

I cannot contribute to the rest of the discussion though as it surpasses my Ansible horizon by a few lightyears 😄

**Comment by onitake** [comment]
@mj84 we tackled the issue as follows, by the way:
```
- name: Get Homepaths
  getent:
    database: passwd
    key: "{{ item }}"
  with_items: "{{ managed_users }}"
  register: managed_users_getent
- set_fact:
    managed_users_homepaths: "{{ managed_users_homepaths | default({}) | combine({ item.item: item.ansible_facts.getent_passwd[item.item].4 }) }}"
  with_items: "{{ managed_users_getent.results }}"
```

This nets you a nice dictionary, mapping each entry in `managed_users` to the user's home directory.
As a bonus, `getent` fails the play if the user doesn't exist.

Side note: I know there are filters to query data structures directly (like `json_query`), but in this case, we needed a dictionary, and this approach works even when the `jmespath` Python module isn't installed.
