### ISSUE TITLE
Include statically empty file in block stops playbook without errors or warnings

### ISSUE THREAD

**Issue by nelsg** [ansible/ansible#32145]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Include static file

##### ANSIBLE VERSION
```
ansible 2.3.2.0 (detached HEAD c7052b42c7) last updated 2017/10/25 15:45:21 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

Reproduced with version 2.2.1.0, warning message displayed with Ansible 2.4.0.0

##### CONFIGURATION
Default configuration file

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
When include statically an empty file in a block, playbook execution stops without errors or warnings

##### STEPS TO REPRODUCE

Run following playbook with command:

    ansible-playbook -i localhost, site.yml

* site.yml

```yaml
---
- hosts: all
  connection: local
  tasks:
  - block:
    - include: empty.yml
      static: true
    - include: not_empty.yml
      static: true
    - fail:
        msg: END
```

* empty.yml

```yaml
---
```

* not_empty.yml

```yaml
---
- debug:
    msg: I'm foo
```

##### EXPECTED RESULTS
Final task fails and display 'END'

##### ACTUAL RESULTS
Only tast 'Gathring Facts' are executed and everything seam alright

Notes:

* If I include 'empty.yml' dynamically, playbook works
* If I use ansible 2.4.0.0-1, playbook works and a warning is displayed "[WARNING]: file .../empty.yml is empty and had no tasks to include"
* If I remove block, playbook works
