### ISSUE TITLE
Using cloudformation tasks, multi staging variables not been imported 

### ISSUE THREAD

**Issue by newjones** [ansible/ansible#32150]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- cloudformation

##### ANSIBLE VERSION

```
ansible 2.4.0.0


```

##### CONFIGURATION
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

##### OS / ENVIRONMENT
Ubuntu 16 to AWS

##### SUMMARY
Using the recomendations of best practices for multi staging environments (http://docs.ansible.com/ansible/latest/playbooks_best_practices.html) and a playbook with cloudformation tasks, the related vars for each environment are not imported but if only use tasks with another module, works. 
##### STEPS TO REPRODUCE
 I got the follow structure:

├── ansible.cfg
├── environments
│   ├── int
│   │   ├── group_vars
│   │   │   └── all.yml
│   │   └── inventory
│   └── live
│       ├── group_vars
│       │   └── all.yml
│       └── inventory
├── hosts
├── sample-playbook.yml

THIS WORKS fine
```yaml
---
# sample-playbook.yml

- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
   - name: test 
     debug: msg="reading from {{env_name}}"
     tags: test

```

```yaml
---
# int/group_vars/all.yml
env_name: int
# other vars that appears on playbook
```

```shell
ansible-playbook -i environments/int sample-playbook.yml
```

THIS FAIL

```yaml
   - name: test 
     debug: msg="reading from {{env_name}}"
     tags: test

   - name: launch ansible cloudformation stack
     cloudformation:
       stack_name: "{{stack-name}}"
       state: present
       region: eu-west-1
       disable_rollback: true
       template_url: "{{ template_url_base}}/file.yaml"
     args:
       template_parameters:
         Environment: "{{ env_name }}"
         BucketS3: "{{ template_url_base}}"
         Project: projectname
         IntervalInSeconds: 300
         SizeInMBs: 5
         CompressionFormat: UNCOMPRESSED 
         KinesisRPH: 24 
         KinesisShards: 1
         VpcId: "{{vpcid}}"
         PasswordRDS: "{{ rdspass }}"
         DBSubnetA: "{{ dbsubnetA }}" 
         DBSubnetB: "{{ dbsubnetB }}"
         RDSSG: "{{ rdssg }}"

##### EXPECTED RESULTS
The vars inside environments/int/group_vars/all.yml like "{{ env_name }}" must be imported to playbook.

##### ACTUAL RESULTS

```
```
  config file = /home/username/projects/projectname/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
Using /home/username/projects/projectname/ansible.cfg as config file
setting up inventory plugins
Parsed /home/username/projects/projectname/repo/ansible/environments/int/inventory inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: sample-playbook.yml****************************************************************************************************************************************************************************************************************
2 plays in sample-playbook.yml

PLAY [localhost] ****************************************************************************************************************************************************************************************************************************
ERROR! 'env_name' is undefined
```
