### ISSUE TITLE
vsphere_guest's module with Cluster DRS and / or Cluster SDRS

### ISSUE THREAD

**Issue by DaBeOps** [ansible/ansible#32167]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- vsphere_guest

##### SUMMARY
I try to deploy VMs into a Cluster DRS using vsphere_guest but it seems we have to specify an ESX's name even if we defined a Cluster. May we have a solution for this?

Same idea for the storage with a SDRS Cluster.

Here is my code:

```yaml
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: false
  vars:
    vcenter_values:
      - datacenter: Lyon
        esx:
          - vESXI1
          - vESXI2
          - vESXI3
          - vESXI4
          - vESXI5
        ids:
          vcsa_fqdn: 'vcsa1.lyon.dawan.fr'
          login:   'dabe@formation.lan'
          password:  '**********'
        vm:
          datastore: 'vSAN-01'
          rp:        'RP_Ansible'
          size:      '20'
          disk_type: 'thin'
          nic_name:  'vDs-vDawan'
          nic_type:  'vmxnet3'
          nic_tech:  'dvs'
          mem:       '8192'
          vcpu:      '2'
          iso_path:  "vSAN-01/ISO/VMware-ESXi-6.0U2-3620759-RollupISO1.iso"
          cluster:   'CLT_Lyon-DRS-DPM-HA-FT-VSAN'
          scsi:      'paravirtual'
  tasks:
    - name: "TP [TPS/Balloon]: Deploy VMs with custom VMx to enhance the overcommitement effect using nested vESX"
      vsphere_guest:
        vcenter_hostname: "{{ item.0.ids.vcsa_fqdn }}"
        username: "{{ item.0.ids.login }}"
        password: "{{ item.0.ids.password }}"
        guest: "{{ item.1 }}"
        validate_certs: false
        state: powered_on
        vm_extra_config: {
            "notes": "{{ notes | default('Created by Ansible') }}",
            "vhv.enable": "TRUE",
            "vcpu.hotadd": "TRUE",
            "mem.hotadd": "TRUE",
            "monitor.virtual_mmu": "software",
            "monitor.virtual_exec": "hardware",
            "sched.mem.maxmemctl": "-1",
            "sched.mem.pshare.enable": "TRUE",
            "annotation": "Deployed by Ansible"
        }
        vm_disk:
          disk1:
            size_gb: 20
            type: thin
            datastore: vSAN-01
            # size_gb: "{{ item.0.vm.size }}"
            # type: "{{ item.0.vm.disk_type }}"
            # datastore: "{{ item.0.vm.datastore }}"
        vm_nic:
          # nic4:
          #   type: vmxnet3
          #   network: VM Network
          #   network_type: standard
          nic1:
            type: "{{ item.0.vm.nic_type }}"
            network: "{{ item.0.vm.nic_name }}"
            network_type: "{{ item.0.vm.nic_tech }}"
          nic2:
            type: "{{ item.0.vm.nic_type }}"
            network: "{{ item.0.vm.nic_name }}"
            network_type: "{{ item.0.vm.nic_tech }}"
          nic3:
            type: "{{ item.0.vm.nic_type }}"
            network: "{{ item.0.vm.nic_name }}"
            network_type: "{{ item.0.vm.nic_tech }}"
        vm_hardware:
          memory_mb: "{{ item.0.vm.mem }}"
          num_cpus: "{{ item.0.vm.vcpu }}"
          osid: vmkernel6Guest
          # scsi: lsilogic
          scsi: "{{ item.0.vm.scsi }}"
          vm_cdrom:
            type: "iso"
            iso_path: "{{ item.0.vm.iso_path }}"
        cluster: "{{ item.0.vm.cluster }}"
        
        #esxi:
        #   datacenter: Lyon
        #   hostname: esxi1.lyon.dawan.fr

        resource_pool: "{{ item.0.vm.rp }}"
      with_subelements:
        - "{{ vcenter_values | default([]) }}"
        - esx
```
