### ISSUE TITLE
ec2.py - get_reservations() filtering does not strip vpc_subnet_id var

### ISSUE THREAD

**Issue by cccscdev** [ansible/ansible#32185]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible/lib/ansible/modules/cloud/amazon/ec2.py

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

From: Ubuntu 14.04
Executing task containing ec2 module as local_action
Target: Amazon EC2

##### SUMMARY
When using the ec2 module to create a AWS EC2 instance, where the instance already exists, an error is returned of the form: "Instance creation failed => InvalidIPAddress.InUse: Address x.x.x.x is in use".  This is despite using exact_count and count_tag to check and allow the existing instance.

##### STEPS TO REPRODUCE

Execute the following playbook twice.  On the second run the above error is reported.

```yaml
- name: Provision EC2 Instance(s)
  local_action:
    module: ec2
    aws_access_key: "{{ ec2_access_key }}"
    aws_secret_key: "{{ ec2_secret_key }}"
    key_name: "{{ keyname }}"
    group_id: "{{ sg.group_id }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_ami.results|sort(attribute='creationDate', reverse=True) | map(attribute='ami_id') | first()}}"
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    private_ip: "{{ ec2_private_ip | default(omit) }}"
    region: "{{ ec2_region }}"
    instance_tags: "{{ instance_tags }}"
    exact_count: "{{ exact_count }}"
    count_tag:
      Type: "{{ ec2_tag_type }}"
    assign_public_ip: "{{ assign_public_ip }}"
    user_data: "{{ lookup('template', 'templates/cloud-init.yml.j2') }}"
    wait: true
    ebs_optimized: false
    volumes: "{{ ec2_volumes }}"
```

##### EXPECTED RESULTS

The ec2 module should be idempotent, and should not report the above error when the exact_count and count_tag are used.

##### ACTUAL RESULTS

An error is returned: Instance creation failed => InvalidIPAddress.InUse: Address x.x.x.x is in use

It appears that within the get_reservations() function of ec2.py, the line: vpc_subnet_id = module.params.get('vpc_subnet_id') is returning a vpc_subnet_id that has a newline character appended to it.

For example, if the subnet within AWS VPC is called: subnet-12345678 the following is assigned to the vpc_subnet_id variable (the \n is appended):
['s', 'u', 'b', 'n', 'e', 't', '-', '1', '2', '3', '4', '5', '6', '7', '8', '\n']

This subsequently causes the filtering based on the count_tag to fail to match, and therefore the module proceeds on the basis that the instance does not already exist - resulting in it attempting to create the instance, and the IP address already exists error being returned.

I resolved this by inserting a single line:
Following the line:  vpc_subnet_id = module.params.get('vpc_subnet_id')
I added: vpc_subnet_id = vpc_subnet_id.strip()

This resolved the issue.

```
Instance creation failed => InvalidIPAddress.InUse: Address x.x.x.x is in use
```
