### ISSUE TITLE
Include `timedout` status in asynchronous execution

### ISSUE THREAD

**Issue by sebinjohn** [ansible/ansible#32181]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- async

##### SUMMARY
Currently, the `async` job's output has the following behaviour.
- If the job finishes in the expected time, job status is written properly to ~/.ansible_async/{{jobid}}
- if the job times out, watcher daemon kills the job and the output in ~/.ansible_async/{{jobid}} will be `{"started": 1, "finished": 0, "ansible_job_id": "{{jobid}}"}`. This will cause async_status module to report the status of the job as failed.

There are cases when "time out" of an action can be considered as an Ok state. In such cases, it would be better to have a field `{"timedout": 1}` in ~/.ansible_async/{{jobid}}. The user can then write

```
- name: check status
  async_status:
    jid: "{{ job.ansible_job_id}}"
  register: job_status
  until: job_status.finished or job_status.timedout
```
