### ISSUE TITLE
pam module wipes out pam_listfile.so options

### ISSUE THREAD

**Issue by raspinall** [ansible/ansible#32195]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pamd

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/net/aspinall/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT

RHEL7.4
##### SUMMARY

The pam module wipes out options supplied to pam_listfile.so, even if that module is not directly addressed by a playbook

##### STEPS TO REPRODUCE

In /etc/pam.d/system-auth, have the following line:
account required pam_listfile.so item=user sense=deny file=/etc/denylist.txt onerr=succeed

```
- name: configure hash algorithm for pam_unix.so
  pamd:
      name: system-auth
      type: password
      control: sufficient
      module_path: pam_unix.so
      module_arguments: 'sha512 shadow try_first_pass use_authtok'

```

##### EXPECTED RESULTS

The line containing pam_unix.so should be modified to change 'md5' to 'sha512'

##### ACTUAL RESULTS

The pam_unix.so line is modified, but so is the line with pam_listfile.so.

The new pam_listfile.so line has changed to:
account       required        pam_listfile.so item=user sense=deny file=

```

```
