### ISSUE TITLE
user module with option local fails on Ubuntu

### ISSUE THREAD

**Issue by rmfrankch** [ansible/ansible#32199]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
user module

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Nothing changed.

##### OS / ENVIRONMENT
Ubuntu 16.04LTS
local ansible run (local host only)
libuser 0.60 installed
Using the AD for authentication, users are defined in /etc/passwd => nsswitch.conf does NOT have sss for passwd, group, and shadow.

##### SUMMARY
I tried to create a local user using the user module with the local option (available as of 2.4).
This fails on Ubuntu 16.04LTS with the error:

`Error parsing arguments: unknown option.
 Usage: luseradd [-irMn?] [-i|--interactive] [-r|--reserved] 
        [-c|--gecos=STRING] [-d|--directory=STRING] [-k|--skeleton=STRING]
         [-s|--shell=STRING] [-u|--uid=NUM] [-g|--gid=STRING] 
        [-M|--nocreatehome] [-n|--nocreategroup] [-P|--plainpassword=STRING] 
        [-p|--password=STRING] [--commonname=STRING] [--givenname=STRING] 
        [--surname=STRING] [--roomnumber=STRING] [--telephonenumber=STRING]
         [--homephone=STRING] [-?|--help] [--usage] [OPTION...] user ` 

This works if local is false.

##### STEPS TO REPRODUCE
Install libuser if not installed
Add a new user to the local /etc/passwd file using the user module and the local option set to true.

```yaml
  user:
    comment: "{{ item.gecos }},{{ dmi_users.org_unit }}"
    createhome: true
    group: "{{ item.gid }}"
    groups: "{{ item.groups|join(\",\") }}"
    append: false
    home: "{{ item.home }}"
    name: "{{ item.uid }}"
    password: "KB"
    shell: "{{ item.shell }}"
    state: "present"
    uid: "{{ item.uidnumber }}"
    local: true
  with_items: "{{ users }}"
```
users contains one full user record. This works fine with local: false

##### EXPECTED RESULTS
To add the user just as with local:false.

##### ACTUAL RESULTS
The module fails with the above error message. 

```

```
