### ISSUE TITLE
add 'create' parameter to user module

### ISSUE THREAD

**Issue by igroene** [ansible/ansible#32204]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
user module

##### ANSIBLE VERSION
```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION
no changes

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If trying to add a non-existing user to a group, the user is silently created which might not be one you want. The module should have an option e.g. create=yes/no that allows one to specify if the user is to be created or an error be given.

##### STEPS TO REPRODUCE
Run a playbook to append a user to a group

```yaml
    - name: add os user to group my_group
      become: yes
      user: name=test_user groups=my_group append=yes
```

##### EXPECTED RESULTS
Error due to user not existing

##### ACTUAL RESULTS
User is silently created
