### ISSUE TITLE
elb_target_group.py modify_targets format does not allow items/loops due to execution

### ISSUE THREAD

**Issue by mmercer-apixio** [ansible/ansible#32218]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
elb_target_group

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/mmercer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

```

##### CONFIGURATION
No change

##### OS / ENVIRONMENT
Fedora 26 managing AWS

##### SUMMARY
elb_target_group has a single method for removing existing instances, modify_targets, which is a boolean.  targets accepts a proformated list of items containing id, port, etc.  Because of the way it is written, unless you are hard coding your values, there is no 'ansible like' way of creating multiple targets at once without wiping out all but the last member of exuction.

##### STEPS TO REPRODUCE
Update an existing ALB with multiple items at a time using modify_targets: true

```yaml
  - name: provision the new instance(s) in the ALB target group                           
    elb_target_group:                                                                     
      name: some-alb-name                                         
      port: some-alb-port                                   
      protocol: https                           
      vpc_id: some-vpc-id                                                              
      targets:                                                                            
        - Id: "{{ hostvars[item].facter_ec2_metadata['instance-id'] }}"                   
          Port: some-alb-port                               
      modify_targets: yes                                                                 
      state: present                                                                      
      with_items: "{{ play_hosts }}"                                                      
  connection: local                                                                       
  become: false                                                                           
  run_once: true      
```

with_items will execute 1 time per host contained in play_hosts, which unfortunately triggers the modify_targets: yes,  and as there is no other means to remove targets at this time, you cannot without preconstructing a list, attach multiple targets at once.

##### EXPECTED RESULTS
Each of the members of the play_host set to be added to the 'some-alb-name' ALB

##### ACTUAL RESULTS
The last member of the list set is added to 'some-alb-name' ALB

**Comment by mmercer-apixio** [comment]
@abadger @wimnat As we are currently faced with this, would love a suggestion of a workaround if either of you can come up with one.  Had the idea of setting up a fact for the target set, just not quite sure how to do that in this case.

**Comment by mmercer-apixio** [comment]
Current method around this is to do something along these lines:

```
  - name: Create the custom fact for targets                                       
    set_fact:                                                                      
      target_data: "{{ target_data|default([]) + [{'Id': hostvars[item].facter_ec2_metadata['instance-id'], 'Port': some_port }]}}"
    with_items: "{{ play_hosts }}"   
```
