### ISSUE TITLE
iam_role module doesn't support 'Description' field

### ISSUE THREAD

**Issue by jbscare** [ansible/ansible#32211]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
iam_role module

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jsmift/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
AWS IAM roles support a "Description" field, but the iam_role Ansible module doesn't offer a way to set it.

##### STEPS TO REPRODUCE
Perhaps just a 'description' option, like this:

```yaml
- iam_role:
    name: mynewrole
    description: My new role
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
```

##### EXPECTED RESULTS
The Description field at AWS would be updated with the value of the 'description' option.

##### ACTUAL RESULTS
There is no 'description' option.
