### ISSUE TITLE
Allow to have sub_groups/children with same name for different parents and with different hosts in them

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/ansible#32247]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
feature

##### SUMMARY

Currently the way parent children group works is, once we define a children and have it as a part of parent groups, hosts in the children group will be same for different parents. There is no way to have the same children group across different parent group with different hosts in them.

So for example if I have an inventory like following:
```
[parent1​:children​]
subgroup1
subgroup2

[subgroup1]
1.1.1.1

[subgroup2]
2.2.2.2

[parent2:children]
subgroup1
```
With this both parent1 and parent2 have a children group subgroup1 with same host (1.1.1.1), but there should be a way to have a subgroup1 with different hosts for different parents.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by eubnara** [comment]
same here!


- some.yml
```yml
all:
  children:
   north:
     children:
       old_servers:
         hosts:
           a.example.com:
           b.example.com:
       new_servers:
         hosts:
           c.example.com:
           d.example.com:
   south:
     children:
       old_servers:
         hosts:
           e.example.com:
           f.example.com:
       latest_servers:
         hosts:
           g.example.com:
           h.example.com:
```

- expected result:
```
$ ansible north -i some.yml --list-hosts
  hosts (4):
    a.example.com
    b.example.com
    c.example.com
    d.example.com
```

- actual result:
```
$ ansible north -i some.yml --list-hosts
  hosts (6):
    d.example.com
    c.example.com
    b.example.com
    a.example.com
    e.example.com
    f.example.com
```

**Comment by bcoca** [comment]
This won't work as group names are unique, they are not based on their relationships with other groups.

I recommend creating `parent1_subgroup1` named groups that have the hierarchy you want built in.

**Comment by eubnara** [comment]
@bcoca
thank you for your advice

**Comment by aventrax** [comment]
What I do not expect is ansible doing a trasversal search between different parents once I selected ONE (only) parent with the --limit option!

So, on the example above, launching ansible with `ansible -i some.yaml -l south` I'm expecting to work with only [efgh].example.com, NOT with [abefgh].example.com. This because I'm selecting explicitly the group `south` that is UNIQUE.

At the same time, launching ansible with `ansible -i some.yaml -l old_servers` should list [abef].example.com because I'm selecting  a precise group. Two different parents has the group named `old_servers` so it's expected to obtain the sum of hosts from different parents.

Quite logic, am I missing something?

**Comment by bcoca** [comment]
@aventrax there is only ONE old_servers group, that happens to have 2 parents.

Your logic is based on the groups being defined BY their parents, not that the parent/child relationship is just another attribute for the group, which is defined uniquely by name.

Since both north and south have 'old_servers' as a child, ALL hosts defined under old_servers (no matter when defined) are then part of both north and south.

**Comment by mo18** [comment]
@aventrax 
I came across the same issue. The way I solved it was with inventory files. I split north and south into their own inventory. This allowed me to maintain a single set of playbooks, but target north and south servers separately. 

The drawback is that I would have to run the playbook two times if I wanted to do something against north and south. 

I haven't tested this yet, but I'm guessing an inventory file such as all.yml can be created which imports/includes the inventory from both north and south.

**Comment by mdutton3** [comment]
To make @bcoca 's suggestion more concrete:
```yaml
all:
  children:
    north:
      children:
        north_old_servers:
          hosts:
            a.example.com:
            b.example.com:
        north_new_servers:
          hosts:
            c.example.com:
            d.example.com:
    south:
      children:
        south_old_servers:
          hosts:
            e.example.com:
            f.example.com:
        south_new_servers:
          hosts:
            g.example.com:
            h.example.com:
    old_servers:
      children:
        south_old_servers:
        north_old_servers:
    new_servers:
      children:
        south_new_servers:
        north_new_servers:
```

**Comment by mdutton3** [comment]
Alternatively, you could not nest your groups and use multiple limit statements:

```yaml
all:
  children:
    north:
      children:
        a.example.com:
        b.example.com:
        c.example.com:
        d.example.com:
    south:
      children:
        e.example.com:
        f.example.com:
        g.example.com:
        h.example.com:
    old_servers:
      children:
        a.example.com:
        b.example.com:
        e.example.com:
        f.example.com:
    new_servers:
      children:
        c.example.com:
        d.example.com:
        g.example.com:
        h.example.com:
```
