### ISSUE TITLE
Add async support to Template

### ISSUE THREAD

**Issue by gjedeer** [ansible/ansible#32265]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
Template plugin

##### ANSIBLE VERSION
```
master
```

##### SUMMARY
The template plugin does not support async. It would be nice if it did.

I'm not sure if it's by design or not, maybe I'm overlooking something and there's a possible race condition. As a test, I've added 

```
self._supports_async = True
```

as the first line of the run() method in `plugins/action/template.py` and nothing exploded.

##### STEPS TO REPRODUCE

```yaml
- name: Create site config - {{ item.domain }}
  template: src=apache_site.conf dest="/etc/apache2/sites-enabled/{{ item.domain }}.conf"
  notify: 
    - reload apache
  with_items: "{{ sites }}"
  async: 3600
  poll: 0
  register: apache_conf_wait
  tags: [conf]
```

##### EXPECTED RESULTS
Task works

##### ACTUAL RESULTS

```
{ ..... "msg": "async is not supported for this task."}

```
