### ISSUE TITLE
Please add "cifs" to the default list of special file system types for selinux

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#32288]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

See Issue [#10931](https://github.com/ansible/ansible/issues/10931)

And corresponding Pull Request [#11011](https://github.com/ansible/ansible/pull/11011)

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
PS C:\Users\tonya\Documents\Vagrant\vagrant-ansible> vagrant ssh -c 'ansible-config dump --only-changed'
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
Connection to 192.168.0.198 closed.
```

##### OS / ENVIRONMENT

From Windows 10 Enterprise 1790 Host Hyper-V
To Vagrant Guest Centos 7

##### SUMMARY

get_url and template copy will fail to place files into the /vagrant synced folder under CentOS 7 due to selinux context incompatibility.  This was found way back in 2015 for several FS types, but CIFS was not included in the list.

For Example the following could be put into [lib/ansible/constants.py](https://github.com/ansible/ansible/pull/11011/commits/e2de336a239a64d068f67dd4f22d4ecf0109af2a#diff-b77962b6b54a830ec373de0602918318):
```
DEFAULT_SELINUX_SPECIAL_FS = get_config(p, 'selinux', 'special_context_filesystems', None, 'cifs, fuse, nfs, vboxsf', islist=True)
```

##### STEPS TO REPRODUCE

1. Create Vagrant file with hyper-v provider and centos guest
2. Use eclipse role ansible-role-eclipse
3. Use playbook below:

requirements.yml:
```yaml
# from galaxy
- src: ansiblebit.oracle-java
- src: git+https://github.com/tonyapuzzo/ansible-role-eclipse.git
  version: master
```

playbook.yml:
```yaml

- hosts: all
  gather_facts: yes
  vars:
    java_shell_profile: no
  roles:
    # Install Oracle Java
    - role: ansiblebit.oracle-java
      oracle_java_set_as_default: yes
    # Install Eclipse
    - role: ansible-role-eclipse
      eclipse_distro: oxygen
      eclipse_package: jee
      eclipse_service_release: 1a
```

##### EXPECTED RESULTS

Download & Install Eclipse to /vagrant/downloads folder as configured.

##### ACTUAL RESULTS

Failed to download the file due to selinux context problem.

```
TASK [ansible-role-eclipse : Download eclipse to ansible-master if we don't have it] ***
task path: /vagrant/roles/ansible-role-eclipse/tasks/download_to_master.yml:14
fatal: [default -> localhost]: FAILED! => {"changed": false, "cur_context": ["system_u", "object_r", "cifs_t", "s0"], "f
ailed": true, "gid": 1000, "group": "vagrant", "input_was": ["system_u", "object_r", "default_t", "s0"], "mode": "0755",
 "msg": "invalid selinux context: [Errno 95] Operation not supported", "new_context": ["system_u", "object_r", "default_
t", "s0"], "owner": "vagrant", "path": "/vagrant/downloads/.ansible_tmpLW_0Qyeclipse-jee-oxygen-1a-linux-gtk-x86_64.tar.
gz", "secontext": "system_u:object_r:cifs_t:s0", "size": 343233144, "state": "file", "uid": 1000}
```
