### ISSUE TITLE
registered values assigned even though task is ignored

### ISSUE THREAD

**Issue by Spredzy** [ansible/ansible#32338]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- core

##### ANSIBLE VERSION

- devel
- 2.4.0

##### CONFIGURATION

- N/A

##### OS / ENVIRONMENT

- N/A

##### SUMMARY

Variables register in a skipped tasks are actually registered (emptied) when it should not, as the task is skipped.

##### STEPS TO REPRODUCE

Using the following playbook:

```yaml
---
- hosts: localhost
  tasks:
    - name: echo Ansible
      shell: echo "Ansible"
      register: product
      when: True

    - name: echo AnotherProduct
      shell: echo "AnotherProduct"
      register: product
      when: False

    - name: echo product
      shell: echo "{{ product.stdout }}"
```

Task#1 echo Ansible and register the out to product, Task#2 is ignored, Task#3 echo the registered product.

##### EXPECTED RESULTS

- Ansible to be displayed

##### ACTUAL RESULTS

- The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'
