### ISSUE TITLE
maven_artifact (+ delegate_to) : cannot create intermediate folders anymore

### ISSUE THREAD

**Issue by glatapoui** [ansible/ansible#32345]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
`ansible.cfg`:
```
[defaults]
hostfile = inventories/develop.inv
remote_user = ansible
host_key_checking = False
vault_password_file = vault_pass
callback_whitelist = profile_tasks
roles_path = roles

[privilege_escalation]
become = True

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes
```

##### OS / ENVIRONMENT
Ansible host: Ubuntu 12.04.1
Ansible target: Ubuntu 16.04 

##### SUMMARY
Intermediate folder is not created (and the not found) when using task `maven_artifact` since Ansible 2.4

##### STEPS TO REPRODUCE
When I use the following task, I now get an IO Error, when previously it was working as expected.

```
 maven_artifact:
    group_id: my.company
    artifact_id: product
    classifier: app
    extension: zip
    repository_url: https://our.maven.com/content/groups/COMPANY/
    dest: "/tmp/{{dhs_target_version}}/dhs.zip"
    version: "{{dhs_target_version}}"
  delegate_to: 127.0.0.1
  become: false
```

##### EXPECTED RESULTS

- The folder `/tmp/{{dhs_target_version}}` should be created
- The file located at https://our.maven.com/content/groups/COMPANY/[...] should be downloaded as `/tmp/{{dhs_target_version}}/dhs.zip`

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] No such file or directory: '/tmp/2.8.1-7668/dhs.zip'
fatal: [dhs-local -> 127.0.0.1]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):
  File \"/tmp/ansible_j5wJ9y/ansible_module_maven_artifact.py\", line 499, in <module>
    main()
  File \"/tmp/ansible_j5wJ9y/ansible_module_maven_artifact.py\", line 481, in main
    if downloader.download(artifact, b_dest):
  File \"/tmp/ansible_j5wJ9y/ansible_module_maven_artifact.py\", line 348, in download
    f = open(filename, 'w')
IOError: [Errno 2] No such file or directory: '/tmp/2.8.1-7668/dhs.zip'", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

(I suspect change https://github.com/ansible/ansible/commit/b8da5ee5efa555fcf624297ffd990f3491f7d109?diff=split to have some impact, but I did not bisect it)
