### ISSUE TITLE
Credstash plugin should have a `default` parameter

### ISSUE THREAD

**Issue by gibbsoft** [ansible/ansible#32346]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
credstash plugin

##### ANSIBLE VERSION

```
ansible 2.2.0.0
```
However, all current versions suffer this same issue.

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Whilst using the credstash lookup in a loop with `set_fact` to populate a dictionary, the whole task fails if one of the keys does not exist in credstash.   Attempting to work around the issue using the ansible `|default('')` filter does not help.  Similarly `ignore_errors: yes` results in the fact not being set at all.   Looking at the [source code](ansible/lib/ansible/plugins/lookup/credstash.py) for the plugin, we can see that it raises an error if the key is not found in credstash.  Other plugins, such as the _ini plugin_ have a default option, but from this is missing from the credstash plugin.

##### STEPS TO REPRODUCE
In this simple example below, there are three values in a list called `persistent_envs`, which are used to lookup the specific keys in credstash and populate a dictionary.   One of the secrets does not exist and so it is expected that a specified default should be returned instead.

The credstash keys and values that have been set are:

```
prod/admin_username = foo
prod/admin_password = bar
test/admin_username = moo
test/admin_password = oink
```

> Note above, the keys for `dev` have not been set, and defaults are expected

```yaml
---
- hosts: all
  connection: local
  gather_facts: false
  become: false
  vars:
    persistent_envs:
      - prod
      - dev
      - test
    aws_region: eu-west-2
    credstash_table: credstash_secrets
  tasks:
    - name: set the facts dict for the persistent envs
      set_fact:
        credentials: "{{ credentials |default({}) | combine( {
          item: {
            'database': {
              'login_password': lookup('credstash', [item, 'admin_password'] |join('/'), table=credstash_table, region=aws_region, default=''),
              'login_user': lookup('credstash', [item, 'admin_username'] |join('/'), table=credstash_table, region=aws_region, default='root'),
            }
          }
        } ) }}"
      with_items: "{{ persistent_envs }}"

    - name: dump the contents of the dict
      debug:
        msg: "{{ credentials }}"
```

##### EXPECTED RESULTS
```
$ AWS_PROFILE=myprofile ansible-playbook -clocal -i0, test47.yml

PLAY [all] *********************************************************************

TASK [set the facts dict for the persistent envs] ******************************
Monday 30 October 2017  13:34:52 +0000 (0:00:00.058)       0:00:00.058 ********
ok: [0] => (item=prod)
ok: [0] => (item=dev)
ok: [0] => (item=test)

TASK [dump the contents of the dict] *******************************************
Monday 30 October 2017  13:34:56 +0000 (0:00:03.762)       0:00:03.820 ********
ok: [0] => {
    "msg": {
        "prod": {
            "database": {
                "login_password": "bar",
                "login_user": "foo"
            }
        },
        "dev": {
            "database": {
                "login_password": "",
                "login_user": "root"
            }
        },
        "test": {
            "database": {
                "login_password": "oink",
                "login_user": "moo"
            }
        }
    }
}

PLAY RECAP *********************************************************************
0                          : ok=2    changed=0    unreachable=0    failed=0

Monday 30 October 2017  13:34:56 +0000 (0:00:00.039)       0:00:03.860 ********
===============================================================================
set the facts dict for the persistent envs ------------------------------ 3.76s
dump the contents of the dict ------------------------------------------- 0.04s
```

##### ACTUAL RESULTS
```
$ AWS_PROFILE=myprofile ansible-playbook -clocal -i0, test47.yml

PLAY [all] *********************************************************************

TASK [set the facts dict for the persistent envs] ******************************
Monday 30 October 2017  13:33:02 +0000 (0:00:00.046)       0:00:00.046 ********
ok: [0] => (item=prod)
fatal: [0]: FAILED! => {"failed": true, "msg": "Key dev/admin_username not found"}

PLAY RECAP *********************************************************************
0                          : ok=0    changed=0    unreachable=0    failed=1

Monday 30 October 2017  13:33:03 +0000 (0:00:00.641)       0:00:00.688 ********
===============================================================================
set the facts dict for the persistent envs ------------------------------ 0.64s
```
