### ISSUE TITLE
Subsequent calls to `postgresql_user` with `role_attr_flags` raise an error

### ISSUE THREAD

**Issue by andreyfedoseev** [ansible/ansible#32358]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 15:27:27) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### OS / ENVIRONMENT
MacOS 10.13

##### SUMMARY
When I run `postgresql_user` with `role_attr_flags` parameter it works fine (user is created). Any sub-sequent runs of this command are failing.

##### STEPS TO REPRODUCE
Run the following playbook twice

```yaml
- name: create database user
  postgresql_user:
    name: foo
    password: foo
    role_attr_flags: CREATEDB
    login_host: localhost
    login_user: postgres
    login_password: postgres
```

##### EXPECTED RESULTS
User is created after the first run, nothing is changed after the second run. 

##### ACTUAL RESULTS

```
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_3JaGAq/ansible_module_postgresql_user.py\", line 846, in <module>\r\n    main()\r\n  File \"/tmp/ansible_3JaGAq/ansible_module_postgresql_user.py\", line 805, in main\r\n    role_attr_flags, encrypted, expires, no_password_changes, conn_limit)\r\n  File \"/tmp/ansible_3JaGAq/ansible_module_postgresql_user.py\", line 352, in user_alter\r\n    if current_role_attrs[PRIV_TO_AUTHID_COLUMN[role_attr_name]] != role_attr_value:\r\nTypeError: 'NoneType' object has no attribute '__getitem__'\r\n",
```
