### ISSUE TITLE
Ansible group variables being merged for distinct hosts

### ISSUE THREAD

**Issue by EddyP23** [ansible/ansible#32353]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible inventory variable parsing

##### ANSIBLE VERSION

```ansible 2.4.0.0```

##### CONFIGURATION

None

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS

##### SUMMARY AND STEPS TO REPRODUCE

`inventory.yml`:
```
all:
  children:
    westeu:
      vars:
        location: 'westeu'
      children:
        esNodes:
          hosts:
            host1:
    southcentralus:
      vars:
        location: 'southus'
      children:
        esNodes:
          hosts:
            host2:
```

When I run `ansible -i inventory.yml -m debug -a 'var=location' all` I get `location: westeu` for both hosts! *Please note*, that the main part here is that both location groups (`southcentralus` and `westeu`) share the same subgroup called `esNodes`. If I change `esNodes` to `esNodesEU` and `esNodesUS` everything works as expected. But then I can never just select `esNodes`.

I am aware of this issue [variable issue](https://github.com/ansible/ansible/issues/9065) and there is an explanation there that variables are resolved at the host level, but it seems that they are resolved at a group level as well and then only later pushed down to a host. It clearly sounds like a bug to me.
