### ISSUE TITLE
ansible-playbook displays decrypted vault-encrypted strings

### ISSUE THREAD

**Issue by cpmills1975** [ansible/ansible#32355]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /home/me/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### OS / ENVIRONMENT
RHEL 7.4 - but likely affects all platforms

##### SUMMARY
Using in-place vault-encrypted strings in a playbook and when ansible-playbook runs, these are output
in plain text on the screen. If important, the task is iterative (with_items) and executes multiple times.

##### STEPS TO REPRODUCE
```yaml

- name: Mount host/group defined shares
  become: yes
  mount:
    path: "{{ item['mount_point'] }}"
    src: "//{{ item['host'] }}/{{ item['share'] }}"
    fstype: cifs
    opts: "{{ cifs_options }}"
    dump: 0
    passno: 0
    state: mounted
  with_items: "{{ cifs_mounts }}"

cifs_mounts:
  - host: HOSTNAME.domain.com
    share: SHARENAME$
    mount_point: /path/to/somewhere
    user: "me"
    domain: "MYDOMAIN"
    password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
  62316333243243243243243243237379894374937297394729347932743243639393333396338336
          336436666537383036356535....<truncated for obvious reasons>
```

##### EXPECTED RESULTS
Ansible must above all else recognise a string from a !vault and NEVER under any circumstances output this to the screen.

##### ACTUAL RESULTS

```
TASK [cifs-client : Mount host/group defined shares] ****************************************************************************************
changed: [hostname] => (item={u'domain': u'MYDOMAIN', u'mount_point': u'/path/to/somewhere', u'share': u'SHARENAME$', u'host': u'HOSTNAME.domain.com', u'user': u'me', u'password': u'UNENCRYPTED STRING APPEARS HERE'})
```

**Comment by jborean93** [comment]
Is This A Bug?
==============

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking:

   * Ansible currently does not store any metadata to determine if a vaulted var is being used so it cannot hide the output
   * There is nothing to stop a variable from taking in a vaulted variable and then returning that var as a result and Ansible would never know that happens

Because of these issues, the solution available to you is to use the `no_log: yes` on the task level. This stops Ansible from outputting any information for that particular task. In your case it will change the output to be

```
TASK [cifs-client : Mount host/group defined shares] ****************************************************************************************
changed: [hostname] => (item=None)
```

If this is a bit extreme and you still want some information you can also use loop_control label like the below

```
- module:
  with_items: '{{items}}'
  loop_control:
    label: '{{item.host}}'  
```

This will change your output to be the following

```
TASK [cifs-client : Mount host/group defined shares] ****************************************************************************************
changed: [hostname] => (item=u'HOSTNAME.domain.com')
```

Beware with the loop_control though, as soon as you use `-v` you will still see the full dict being used so it may not be something you can do.

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
   
   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!
