### ISSUE TITLE
match test documentation inaccurate

### ISSUE THREAD

**Issue by ephesused** [ansible/ansible#32366]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

http://docs.ansible.com/ansible/latest/playbooks_tests.html#testing-strings

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

Nothing unusual.

##### OS / ENVIRONMENT

CentOS 7.3

##### SUMMARY

The documentation for the match test states that it "requires a complete match in the string".  That's not accurate;  it requires a match at the start of the string.  If I'm following the code properly (https://github.com/ansible/ansible/blob/2a041d10d26d5746132061da4b874f33cb73ffb0/lib/ansible/plugins/test/core.py#L84), the underlying test is a call to python's re.match (https://docs.python.org/2/library/re.html#re.match), which looks at the start of the string, not the complete string.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - debug:
        msg: "'foo' | match('{{ item }}') is true."
      when: "'foo' | match(item)"
      with_items:
        - ""
        - "f"
        - "fo"
        - "foo"
        - "foo*"
        - "foot*"
        - "oo"
```

##### EXPECTED RESULTS

Based on the current doc, I expected only "foo", "foo*", and "foot*" to be true.

##### ACTUAL RESULTS

The match test acts against the beginning of the string, not the complete string.

```
PLAY [localhost] ******************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [debug] **********************************************************************************************************
ok: [localhost] => (item=) => {
    "item": "",
    "msg": "'foo' | match('') is true."
}
ok: [localhost] => (item=f) => {
    "item": "f",
    "msg": "'foo' | match('f') is true."
}
ok: [localhost] => (item=fo) => {
    "item": "fo",
    "msg": "'foo' | match('fo') is true."
}
ok: [localhost] => (item=foo) => {
    "item": "foo",
    "msg": "'foo' | match('foo') is true."
}
ok: [localhost] => (item=foo*) => {
    "item": "foo*",
    "msg": "'foo' | match('foo*') is true."
}
ok: [localhost] => (item=foot*) => {
    "item": "foot*",
    "msg": "'foo' | match('foot*') is true."
}
skipping: [localhost] => (item=oo)
```
