### ISSUE TITLE
win_service quotes in path to handle spaces

### ISSUE THREAD

**Issue by valerius257** [ansible/ansible#32368]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_service

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
```

##### OS / ENVIRONMENT

Ansible Host: CentOS 7
Managing: Windows 2012 R2

##### SUMMARY

win_service fails to create service when quoted path which is needed to handle spaces in path.

##### STEPS TO REPRODUCE

```yaml
- name: create jenkins slave service
  win_service:
   name: jenkins-slave
   display_name: Jenkins Slave
   start_mode: auto
   path: '"C:\Jenkins Slave\jenkins-slave.exe"'
```

##### EXPECTED RESULTS

windows service created with path being in quotes

##### ACTUAL RESULTS

win_service failed to create service

```
fatal: [host]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "Get-AnsibleParam: Parameter 'path' has an invalid path '\"C:\\Jenkins Slave\\jenkins-slave.exe\"' specified."
}
```
