### ISSUE TITLE
zypper_repository: Fails to import GPG keys when 'name' parameter is missing

### ISSUE THREAD

**Issue by hwoarang** [ansible/ansible#32375]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
zypper_repository module

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mchandras/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
```

However, this also affects the stable 2.3 release too

##### OS / ENVIRONMENT
openSUSE Tumbleweed

##### SUMMARY
When using the `auto_import_keys` parameter in the zypper_repository module, the keys are not imported if the `name` parameter is not set

##### STEPS TO REPRODUCE
Use this playbook

```yaml
- name: foobar                                                                                                                                                                                
  hosts: localhost                                                                                                                                                                            
  become: yes                                                                                                                                                                                 
  tasks:                                                                                                                                                                                      
    - name: Add repo                                                                                                                                                                          
      zypper_repository:                                                                                                                                                                      
        repo: " https://download.opensuse.org/repositories/home:/markoschandras:/sysinstall/openSUSE_Tumbleweed/home:markoschandras:sysinstall.repo"                                                    
        auto_import_keys: yes  
```

##### EXPECTED RESULTS
They gpg key should have been imported

##### ACTUAL RESULTS
Once you add the repository from the 'Configuration' step, try to install 'ipxe'

```
$ sudo zypper in ipxe
Retrieving repository 'home:markoschandras:sysinstall (openSUSE_Tumbleweed)' metadata -----------------------------------------------------------------------------------------------------[\]

New repository or package signing key received:

  Repository:       home:markoschandras:sysinstall (openSUSE_Tumbleweed)                    
  Key Name:         home:markoschandras OBS Project <home:markoschandras@build.opensuse.org>
  Key Fingerprint:  D8E86E1C 3DA78D44 93FDB218 7307D1F1 F0CC0B26                            
  Key Created:      Wed 09 Dec 2015 16:29:25 GMT                                            
  Key Expires:      Fri 16 Feb 2018 16:29:25 GMT                                            
  Rpm Name:         gpg-pubkey-f0cc0b26-566856e5                                            


Do you want to reject the key, trust temporarily, or trust always? [r/t/a/? shows all options] (r): 
```
That should not happen. We use the `auto_import_keys` option so they key should have been imported. However, if you use the following playbook, then everything works.

```yaml
- name: foobar                                                                                                                                                                                
  hosts: localhost                                                                                                                                                                            
  become: yes                                                                                                                                                                                 
  tasks:                                                                                                                                                                                      
    - name: Add repo                                                                                                                                                                          
      zypper_repository:                                                                                                                                                                      
        name: "ipxe"                                                                                                                                                                          
        repo: "https://download.opensuse.org/repositories/home:/markoschandras:/sysinstall/openSUSE_Tumbleweed/"                                                                              
        auto_import_keys: yes
```

The docs do not mention that we need to use the `name` parameter for `auto_import_keys` to work and I don't think that's strictly required anyway.
