### ISSUE TITLE
ignore_errors always ignore failures when variable is used to control it

### ISSUE THREAD

**Issue by guenhter** [ansible/ansible#32384]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible-core

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/guenthgr/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
`ansible-config dump --only-changed` returns nothing, but I just have a vanilla ansible.

##### OS / ENVIRONMENT

4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u5 (2017-09-19) x86_64 GNU/Linux

##### SUMMARY
When I use the 'ignore_errors' options on a task, this works if the boolean is hardcoded like:
```yaml
ignore_errors: false
```

But as soon as the option is set via a variable, that doesn't work any longer:

```yaml
ignore_errors: "{{ ignore_assertion_errors }}"
or
ignore_errors: ignore_assertion_errors
```
In the latter case, this is always handled as `true` so the assertion failures are ignored.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: 127.0.0.1
  vars:
    ignore_assertion_errors: false
  tasks:
    - name: With variable
      assert:
        that: item < 2
        msg: "{{item}} isn't < 2"
      ignore_errors: ignore_assertion_errors
      with_items:
        - 1
        - 2

    - name: With 'false' as hardcoded boolean
      assert:
        that: item < 2
        msg: "{{item}} isn't < 2"
      ignore_errors: false
      with_items:
        - 1
        - 2

```

##### EXPECTED RESULTS
Expect the first task to fail. Second shouldn't even run.

##### ACTUAL RESULTS

First task fails but the failure is ignored.
Second task than fails as expected.

```
TASK [Gathering Facts] **********************************************************************************************************************************
ok: [127.0.0.1]

TASK [With variable] ************************************************************************************************************************************
ok: [127.0.0.1] => (item=1) => {
    "changed": false, 
    "failed": false, 
    "item": 1, 
    "msg": "All assertions passed"
}
failed: [127.0.0.1] (item=2) => {
    "assertion": "item < 2", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "item": 2, 
    "msg": "2 isn't < 2"
}
...ignoring

TASK [With 'false' as hardcoded boolean] ****************************************************************************************************************
ok: [127.0.0.1] => (item=1) => {
    "changed": false, 
    "failed": false, <!--- What did you expect to happen when running the steps above? -->
    "item": 1, 
    "msg": "All assertions passed"
}
failed: [127.0.0.1] (item=2) => {
    "assertion": "item < 2", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true, 
    "item": 2, 
    "msg": "2 isn't < 2"
}

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

You are not using a variable, you are using a string, which is always `True`.
This is what you want:
``` ignore_errors: "{{ignore_assertion_errors|bool}}"```

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by guenhter** [comment]
@bcoca but this also happens when I use:

```
vars:
    ignore_assertion_errors: false

tasks:
   ...
   ignore_errors: ignore_assertion_errors
```

I tried the following combinations:

```
ignore_errors: "{{ignore_assertion_errors}}"
ignore_errors: ignore_assertion_errors
ignore_errors: "{{ignore_assertion_errors|bool}}"
ignore_errors: ignore_assertion_errors|bool
```

Nothing works.
