### ISSUE TITLE
debconf passwords get sent to syslog

### ISSUE THREAD

**Issue by inittab** [ansible/ansible#32386]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
debconf module

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/agi/.ansible.cfg
  configured module search path = [u'/home/agi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 17 2017, 18:50:44) [GCC 7.2.0]

```

##### OS / ENVIRONMENT

Debian unstable/sid

##### SUMMARY

Using debconf module to preseed some passwords will log the passwords to syslog:
Oct 31 14:01:57 fgps01 ansible-debconf: Invoked with unseen=None vtype=password
                     question=tripwire/site-passphrase name=tripwire value=XXXXXXXXXXX

##### STEPS TO REPRODUCE

```yaml
- name: Preconfigure tripwire site passphrase
  debconf:
    name: tripwire
    question: tripwire/site-passphrase
    value: "{{ site_passphrase }}"
    vtype: password

```

##### EXPECTED RESULTS

No password gets printed in system logs.

##### ACTUAL RESULTS

Sensitve data got logged in a plain text file :-)

```

```
