### ISSUE TITLE
net_vlan seems to still require provider transport (needs to default to cli)

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#32405]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
net_vlan networking module
https://docs.ansible.com/ansible/2.4/net_vlan_module.html

##### ANSIBLE VERSION
```
[root@centos ~]# ansible --version
ansible 2.4.0.0
  config file = /root/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/napalm_ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
```bash
[root@centos ~]# ansible-config dump --only-changed
DEFAULT_GATHERING(/root/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/root/ansible.cfg) = [u'/root/hosts']
DEFAULT_MODULE_PATH(/root/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/napalm_ansible']
DEPRECATION_WARNINGS(/root/ansible.cfg) = False
HOST_KEY_CHECKING(/root/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/root/ansible.cfg) = True
```

##### SUMMARY
```bash
TASK [configure vlans neighbor] *****************************************************************************************************************
failed: [n9k] (item={u'name': u'default', u'vlan_id': u'1'}) => {"ansible_facts": {"network_os": "nxos"}, "changed": false, "failed": true, "item": {"name": "default", "vlan_id": "1"}, "msg": "value of transport must be one of: cli,nxapi, got: None found in provider"}
```

##### STEPS TO REPRODUCE
Here is the playbook setup:

```yaml
[root@centos ~]# cat net/net_vlan.yml
---
- hosts: cisco
  connection: local
  vars:
    ansible_network_os: nxos
  tasks:
    - name: configure vlans neighbor
      net_vlan:
        vlan_id: '{{ item.vlan_id }}'
        name: '{{ item.name }}'
        state: '{{ item.state | default("present") }}'
        provider: "{{login_info}}"
      with_items:
        - { vlan_id: '1', name: 'default' }
        - { vlan_id: '2', name: 'Vl2' }
        - { vlan_id: '3', state: 'suspend' }
```
and login_info is here 

```bash
[root@centos ~]# cat group_vars/all
login_info:
  username: admin
  password: Bullf00d
  transport: cli <- this shouldn't be needed
```

and ansible.cfg
```bash
[root@centos ~]# cat ansible.cfg
[defaults]
deprecation_warnings=False
library = /usr/lib/python2.7/site-packages/napalm_ansible
host_key_checking = False
inventory = hosts
gathering = explicit
[paramiko_connection]
host_key_auto_add = True
```

##### EXPECTED RESULTS
It would work identically with provider transport not set to anything, since it should default to cli
##### ACTUAL RESULTS
It only works when provider has transport: cli

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn @gundalow @kedarX @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ganeshrn** [comment]
@IPvSean The issue is fixed in 2.5 as part of PR https://github.com/ansible/ansible/pull/30610
Can you please retest on devel branch and confirm if it still exists.

needs_info

**Comment by ansibot** [comment]
@IPvSean This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @gdpak
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@IPvSean This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
This should be fixed in 2.5.0 could you please retest to confirm?

**Comment by IPvSean** [comment]
@gundalow haha I think this one becomes kind of irrelevant now with 2.5 connection plugins but I retried real quick->

```
---
- hosts: arista
  connection: local
  vars:
    provider:
      username: admin
      password: Bullf00d!
  tasks:
    - name: Create aggregate of vlans
      eos_vlan:
        aggregate:
          - {vlan_id: 100, name: laptops, state: present}
          - {vlan_id: 200, name: printers, state: present}
          - {vlan_id: 300, name: servers, state: present}
        provider: "{{provider}}"
```

it works!->

```
[root@centos ~]# ansible-playbook eos_vlan.yml

PLAY [arista] ***************************************************************************************************************************

TASK [Create aggregate of vlans] ********************************************************************************************************
ok: [eos]

PLAY RECAP ******************************************************************************************************************************
eos                        : ok=1    changed=0    unreachable=0    failed=0
```
