### ISSUE TITLE
lxd_container config always changed

### ISSUE THREAD

**Issue by LordAro** [ansible/ansible#32437]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lxd_container

##### ANSIBLE VERSION
```
ansible 2.4.1.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When changing an existing container's config, the ansible task is always marked as changed

##### STEPS TO REPRODUCE

```yaml
- name: "Set LXD permissions"
  become: yes
  lxd_container:
    name: "{{ inventory_hostname_short }}"
    config:
      security.privileged: "true"
      raw.apparmor: "mount fstype=nfs,"

```

From the looks of things, https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/lxd/lxd_container.py#L493 is related

##### EXPECTED RESULTS
Task would be marked as changed once, then not changed again

##### ACTUAL RESULTS
Task is marked as changed on every run

As an aside, an example in the docs for config usage would be nice
