### ISSUE TITLE
vmware_guest takes action in check mode

### ISSUE THREAD

**Issue by Petro026** [ansible/ansible#32439]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /home/ansible/tower_install/ansible_afsoc/playbooks/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible/tower_install/venv_ansible/lib/python2.7/site-packages/ansible
  executable location = /home/ansible/tower_install/venv_ansible/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

NOTE: also verified issue against 2.5/devel

##### CONFIGURATION
DEFAULT_GATHERING(/home/ansible/tower_install/ansible_afsoc/playbooks/ansible.cfg) = implicit
HOST_KEY_CHECKING(/home/ansible/tower_install/ansible_afsoc/playbooks/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/home/ansible/tower_install/ansible_afsoc/playbooks/ansible.cfg) = 30

##### OS / ENVIRONMENT
RHEL 7.4

##### SUMMARY
When running a playbook in check mode, vmware_guest takes action on a VM.  Specifically I have a playbook using vmware_guest to restart a VM  (state: restarted).  The vmware_guest module takes action on the VM, restarting it, even in check mode

##### STEPS TO REPRODUCE
Run the following task in normal and check mode
```
- name: reboot machine after completion
  vmware_guest:
    name: "{{ inventory_hostname_short }}"
    uuid: "{{ vm_info.uuid }}"
    hostname: "{{ vcenter_host }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: False
    state: restarted
  delegate_to: localhost
  become: False
  tags: linux_patch_reboot
```

##### EXPECTED RESULTS
In check mode, VM is **not** restarted

##### ACTUAL RESULTS
In check mode, VM is restared

```

TASK [linux_update : reboot machine after completion] *******************************************************************************************************
task path: /home/ansible/tower_install/ansible_afsoc/playbooks/roles/linux_update/tasks/main.yml:26
changed: [repo2 -> localhost] => {
    "changed": true,
    "failed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "ha-datacenter",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "172.16.49.17",
            "is_template": false,
            "linked_clone": false,
            "name": "repo2",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "restarted",
            "template": null,
            "username": "svc_ansible@sofpi",
            "uuid": "4238b406-b4b4-3408-b00a-4cfd87d4efff",
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}
```
