### ISSUE TITLE
The combination of delegate_to and with_items drops connection settings

### ISSUE THREAD

**Issue by gintautassulskus** [ansible/ansible#32454]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`delegate_to` and `loop_control` with `loop_var`

##### ANSIBLE VERSION

```
ansible 2.4.1.0
```

##### SUMMARY

The combination of `delegate_to` and `with_items` with `loop_var` drops connection setting `-o 'IdentityFile=....'`.

##### WORKING EXAMPLE

Task example:
```
- setup:
  delegate_to: "{{item}}"
  with_items:
    - "{{groups['server_group']}}"
```
Output:
```
TASK [test : setup] ******************************************************************************************************************************************************************************************
task path: ...ain.yml:3
Using module file ...modules/system/setup.py
<node-1> ESTABLISH SSH CONNECTION FOR USER: core
<node-1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o 'IdentityFile="id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=core -o ConnectTimeout=10 -o ControlPath=3df39a5770 node-1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
...
...
...
ok: [localhost -> node-1] => (item=node-1)
```

##### NOT WORKING EXAMPLE

Task:
```
- setup:
  delegate_to: "{{renamed_item}}"
  loop_control:
    loop_var: renamed_item
  with_items:
    - "{{groups['server_group']}}"
```
Output:
```
TASK [test : setup] ******************************************************************************************************************************************************************************************
task path: ...main.yml:8
Using module file ...setup.py
<node-1> ESTABLISH SSH CONNECTION FOR USER: None
<node-1> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=c5ee03de2f node-1 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<node-1> (255, '', 'Permission denied (publickey).\r\n')
```

```

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
@gintautassulskus it seems this was fixed in version `2.4.2`. Can you try with that version if that fixes your issue? Thanks!

needs_info

**Comment by jasminesource** [comment]
@mkrizek , indeed, it does work.
Thanks very much!

**Comment by gintautassulskus** [comment]
@mkrizek , indeed, it does work.
Thanks very much!

**Comment by JoelFeiner** [comment]
I am on Ansible 2.4.3 and this exact problem is still happening for me.

**Comment by hxtree** [comment]
Wouldn't it be
 `
  with_items: "{{groups['server_group']}}"
`
Instead of:
```
  with_items:
    - "{{groups['server_group']}}"
```
The first example is passing an array, while the second example is passing an array containing an array. I'm using the following on Ansible 2.5.1 and it works:
```
                - name: set SSH public key on host server
                  authorized_key:
                      user: root
                      state: present
                      key: "{{ lookup('file', 'id_rsa.pub') }}"
                      # remove all other SSH keys
                      # exclusive: True
                  delegate_to: "{{ item }}"
                  with_items: "{{ hostvars[inventory_hostname]['backup'] }}"
                  when:  hostvars[inventory_hostname]['backup'] | default([]) | length > 0
```
