### ISSUE TITLE
Cant create or edit user with "vmware_local_user_manager" module

### ISSUE THREAD

**Issue by 405network** [ansible/ansible#32465]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_local_user_manager

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /var/lib/rundeck/ansible/ansible.cfg
  configured module search path = [u'/var/lib/rundeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### SUMMARY

everytime i try to create or edit a user using the "vmware_local_user_manager" module, i receive the following error.
```
The full traceback is:
  File "/tmp/ansible_miBA9L/ansible_module_vmware_local_user_manager.py", line 98, in process_state
    local_account_manager_states[self.state][self.check_local_user_manager_state()]()
  File "/tmp/ansible_miBA9L/ansible_module_vmware_local_user_manager.py", line 136,
▽
in state_create_user
    self.content.accountManager.CreateUser(account_spec)

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "hostname": "vsphere server,
            "local_user_description": null,
            "local_user_name": "test2",
            "local_user_password": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "username": "rundeck",
            "validate_certs": false
        }
    },
    "msg": "'NoneType' object has no attribute 'CreateUser'"

```
Im not sure where/how i can specify, create user, update existing user, list user, etc.

Can you provide a syntax example on listing users, adding users, or editing users?

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - name: Add local user to ESXi
      local_action:
          module: vmware_local_user_manager
          hostname: vsphere server
          username: foo
          password: bar
          validate_certs: false
         # state: present
          local_user_name: test2
```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@405network Thanks for reporting this issue. I am not able to re-produce this issue on my ESXi setup (6.5) and Ansible version 2.4/2.5

I am using following playbook

```yaml
---
- name: create local user
  hosts: localhost
  tasks:
    - name: create a user
      vmware_local_user_manager:
        hostname: 192.168.122.61
        local_user_name: sampleuser1
        local_user_password: Sample@user!123
        username: root
        password: esxi123
        validate_certs: no

```

Output:

```
ansible-playbook test_vmware_local_user.yaml

PLAY [create local user] *******************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************
ok: [localhost]

TASK [create a user] ***********************************************************************************************************
changed: [localhost]

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0   

```

Are you using correct user while connecting to ESXi (e.g. 'foo')?
