### ISSUE TITLE
netscaler_server should allow graceful shutdowns

### ISSUE THREAD

**Issue by stephan2012** [ansible/ansible#32500]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
Module `netscaler_server`

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
RHEL 7.4

##### SUMMARY

Netscaler module `netscaler_server` should provide an option to suspend a server from loadbalancing gracefully, i.e. allow active connections to terminate but do not direct new to it.

##### STEPS TO REPRODUCE

```yaml
- name: "Suspend loadbalancing for server"
  delegate_to: localhost
  run_once: true
  netscaler_server:
    nsip: '{{ nsc_hostname }}'
    nitro_user: '{{ nsc_api_username }}'
    nitro_pass: '{{ nsc_api_password }}'
    nitro_protocol: https
    name: '{{ ansible_nodename }}'
    state: present
    disabled: yes
    graceful: yes
```

Module `netscaler_servicegroup` allows graceful shutdown for services and it was implemented in the old `netscaler` module.

##### EXPECTED RESULTS
Allow active sessions to the upstream server to terminate instead of killing them.

##### ACTUAL RESULTS
N/A
