### ISSUE TITLE
Dellos9_command module prompt issue

### ISSUE THREAD

**Issue by sanraut** [ansible/ansible#32507]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
dellos9_command

##### ANSIBLE VERSION
```
2.2.1
2.3
```

##### SUMMARY

dellos9_command module does not support prompt.

##### STEPS TO REPRODUCE

```yaml

 - name: securely restart the switch with saving the current config
    dellos9_command:
      commands: reload
      provider: "{{ cli }}"

```
System configuration has been modified. Save? [yes/no]: yes
!

Proceed with reload [confirm yes/no]:yes

##### EXPECTED RESULTS

dellos9_command module should support multiple prompts.

**Comment by ansibot** [comment]
cc @dhivyap @skg-net
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by skg-net** [comment]
@sanraut Thanks for reporting the issue. We will get back to you on this.

**Comment by mzi77** [comment]
Reload issue can be skipped with "reload no-confirm"

But same issues with commands needed during upgrade process

upgrade boot bootselector-image stack-unit 1 booted
upgrade boot bootflash-image stack-unit 1 booted
upgrade fpga-image stack-unit 1 booted

etc.

**Comment by ssr8055** [comment]
@mzi77 reload is just an example of command whee dellos9_command module fails.
There are more commands in os9 which prompts for further question.
Problem with dellos9_command module was it does not support prompt in 2.2.1 ans 2.3 version.

**Comment by mzi77** [comment]
I have ansible 2.4, but issue is still there.

**Comment by abirami-n** [comment]
@mzi77 The prompt handling works fine in ansible2.5. Please use the same and get back to us if you have any issues.

**Comment by mzi77** [comment]
It's not fixed, I'm using ansible 2.6.0, still got

fatal: [XXX]: FAILED! => {"changed": false, "msg": "timeout trying to send command: upgrade boot bootselector-image stack-unit 1 booted", "rc": -32603}

timeout set to 6000 and it's working even on long lasting commands such "upgrade system"

**Comment by abirami-n** [comment]
@mzi77 
tasks:
  - name: "Copy running-config to startup-config for the Dell EMC OS9 Device"
    dellos9_config:
      commands:  
        - command: do copy running-config startup-config
          prompt: '\[confirm yes/no\]:\s?$'
          answer: "no"
 Please use the above way to handle prompts at the playbook.

**Comment by mzi77** [comment]
I will try this, why this is not documented on

https://docs.ansible.com/ansible/2.5/modules/dellos9_config_module.html

?

**Comment by abirami-n** [comment]
@mzi77 We have provided these as examples in our Dell-Networking GitHub, https://github.com/Dell-Networking/ansible-dellos-examples/blob/master/handle_prompt_os9.yaml, you can refer the same.

**Comment by mzi77** [comment]
with

```

  - name: "Upgrade bootselector"
    dellos9_config:
      commands: 
        - command: do upgrade boot bootselector-image stack-unit 1 booted
          prompt: '\[yes/no\]:\s$'
          answer: "no"
    register: debug_output

```

I got

```
TASK [Upgrade bootselector] ***************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'issubset'
fatal: [XXX]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_IAG5SV/ansible_module_dellos9_config.py\", line 310, in <module>\n    main()\n  File \"/tmp/ansible_IAG5SV/ansible_module_dellos9_config.py\", line 273, in main\n    ['prompt', 'answer'].issubset(module.params['lines'][0])):\nAttributeError: 'list' object has no attribute 'issubset'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
