### ISSUE TITLE
authorized_key: please support lists

### ISSUE THREAD

**Issue by jaccoh** [ansible/ansible#32534]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
authorized_key module

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg
  configured module search path = [u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/Library', u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/roles/opendj/Library', u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/roles/usermanagement/Library']
  ansible python module location = /Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/.virtualenv/cms/lib/python2.7/site-packages/ansible
  executable location = /Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/.virtualenv/cms/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
```
ANSIBLE_SSH_CONTROL_PATH(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_ASK_SUDO_PASS(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = False
DEFAULT_CALLBACK_WHITELIST(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = ['profile_tasks']
DEFAULT_FILTER_PLUGIN_PATH(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = [u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/roles/*/filters']
DEFAULT_FORKS(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = 5
DEFAULT_HOST_LIST(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = [u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = [u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/lookup_plugins']
DEFAULT_MODULE_LANG(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = C
DEFAULT_MODULE_PATH(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = [u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/Library', u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/roles/opendj/Library', u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/roles/usermanagement/Li
DEFAULT_POLL_INTERVAL(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = 22
DEFAULT_ROLES_PATH(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = [u'/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/roles']
DEFAULT_SCP_IF_SSH(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = True
DEFAULT_SUDO_USER(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = root
DEFAULT_TIMEOUT(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = 120
DEFAULT_TRANSPORT(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = smart
HOST_KEY_CHECKING(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/jhoeve/GitCollection/iWelcome/Tulip/ansible/cms/ansible.cfg) = False
```

##### OS / ENVIRONMENT
MacOS 10.13.1, VirtualEnv

##### SUMMARY
When you have an environment that gets refreshed or reinstalled a lot (eg. in a pipeline), you may want the authorized_key module with the `exclusive: yes` option. However, this forces the use of newline separated keys. That makes your ansible playbook awkwardly more complex. Instead I suggest to just take a normal list as input. Or, support a unique identifier, such that on a reinstall a key gets replaced instead ending up with a super long authorized_key file.

##### STEPS TO REPRODUCE
This first task is another timing related bug by the way. If the file does not exist yet and you delegate from multiple hosts at a time, one of the hosts will say: file already found. Because between detecting the file is not there and actually creating it, another host beat him to it.

Back to the main issue: the 2nd task makes a list and the 3rd is the module itself. I used join and a 'newline' variable (defined in defaults/main.yml of the role.

```yaml
- name: make sure authorized_key file exists
  delegate_to: "{{ backup_host }}"
  file:
    path: "{{ backup_basedir }}/.ssh/authorized_keys"
    state: touch
    mode: "0600"
    owner: "{{ backup_username }}"
    group: "{{ backup_groupname }}"
  changed_when: false

- name: "create list of keys (newline seperated)"
  delegate_to: "{{ backup_host }}"
  delegate_facts: true
  set_fact:
    key_list: "{{ key_list }} + ['{{ hostvars[item]['root_user']['ssh_public_key'] }}']"
  when:
    - hostvars[item]['iwelcome_customer'] == iwelcome_customer
    - vdc_name == hostvars[item]['vdc_name']
    - iw_node == 'primary'
    - inventory_hostname in groups['backend_servers']
  with_items:
    - "{{ groups[iwelcome_customer] }}"

- name: place authorized keys entry on backup_host
  delegate_to: "{{ backup_host }}"
  authorized_key:
    state: present
    exclusive: yes
    user: "{{ backup_username }}"
    key: "{{ hostvars[backup_host]['key_list'] | join(newline) }}"
    key_options: 'no-port-forwarding,no-x11-forwarding,no-agent-forwarding'
  when:
    - iw_node == 'primary'
    - inventory_hostname in groups['backend_servers']
```

##### EXPECTED RESULTS
Not applicable. It works buts it's way too complicated for my liking.
