### ISSUE TITLE
memory leak when using loop_control: label: ""

### ISSUE THREAD

**Issue by poinck** [ansible/ansible#32537]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- **loop_control**
- with_nested

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
The playbook in question uses dynamic inventory. Besides that no special configuration has been done in "ansible.cfg".

##### OS / ENVIRONMENT
- the Ansible-host is a Docker-container based on Ubuntu 16.04 image.
- target (managed) hosts are Ubuntu 14.04 and 16.04

##### SUMMARY
When using `loop_control` in combination with `with_nested` the output for the task is getting really slow and memory usage is rapidly increasing untill OOM-killer kicks in.

##### STEPS TO REPRODUCE
See following files:
- `groups.all` is gathered from a inventory-script inside "./inventory/" (generates a list of about 15 hosts in required json-format)

```yaml
---
- name: assemble
  add_host:
    name: "{{item.2}}"
    group: "{{item.0}}"
  when: item.2 | search(item.1)
  with_nested:
  - "{{dynamic_groups}}"
  - "{{groups.all}}"
  loop_control:
    label: "{{item.2}}"
```

```yaml
dynamic_groups:
- ['dogs', '^a']
- ['cats', '^t']
```

```yaml
---
- name: first play
  hosts: ~^adogserver
  gather_facts: false
  become: false

  include_tasks:
  - "assemble"

  tasks:
  - name: first task should fail
    command: this_program_does_not_exist
    when: inventory_hostname in groups.dogs
```

- run the play "first play" which includes the task "assemble"

##### EXPECTED RESULTS
- it is expected that the task can be completed without beeing killed because of not enough memory

##### ACTUAL RESULTS
- output is very slow
- and finally the tasks fails with **"ERROR! A worker was found in a dead state"**
- all memory and swap space was consumed

##### WORKARROUND
- removing the `loop_control` statement from the tasks prevents the memory leak
- output is faster and task completes as expected.
