### ISSUE TITLE
vmware_guest_find: AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by Tronde** [ansible/ansible#32543]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module name: vmware_guest_find

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tronde/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

~~~
$ ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
~~~

##### OS / ENVIRONMENT

I'm running Ansible on RHEL 7.4 and try to use the module with VMware vSphere 6.0.0. I would like to find the vm folder path by the vm name.

##### SUMMARY
Searching the vm folder path by vm name did not return the vm folder but a error message instead.

##### STEPS TO REPRODUCE

Running the following playbook with the command:
```
ansible-playbook find_vm.yml
```

```yaml
---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: "vc"
      promt: "Enter Virtual Center Server FQDN"
      private: no

    - name: "vc_datacenter"
      promt: "Enter the name of the Datacenter"
      private: no

    - name: "vc_user"
      promt: "Enter username to connect to vCenter Server: Example: bob@foo.example.com"
      private: no

    - name: "vc_passwd"
      promt: "Enter your password"
      privat: yes

  tasks:
    - name: Find VM
      vmware_guest_find:
        hostname: "{{ vc }}"
        username: "{{ vc_user }}"
        password: "{{ vc_passwd }}"
        datacenter: "{{ vc_datacenter }}"
        name: 'Ubuntu-Server-JKA'
        validate_certs: false
      register: vm_folder
```

##### EXPECTED RESULTS

I expect the vm folder path to be returned. While vSphere 6.0 is still supported by VMware I would like to get this module to work with this release.

##### ACTUAL RESULTS

```
$ ansible-playbook -vvvv find_vm.yml 
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tronde/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: find_vm.yml **************************************************************************************************
1 plays in find_vm.yml
vc [vc-test]: 
vc_datacenter [VC-TEST]: 
vc_user: bob@foo.example.com
vc_passwd: 

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tronde
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tronde/.ansible/tmp/ansible-tmp-1509716706.71-110518228841126 `" && echo ansible-tmp-1509716706.71-110518228841126="` echo /home/tronde/.ansible/tmp/ansible-tmp-1509716706.71-110518228841126 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpoqk6hs TO /home/tronde/.ansible/tmp/ansible-tmp-1509716706.71-110518228841126/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/tronde/.ansible/tmp/ansible-tmp-1509716706.71-110518228841126/ /home/tronde/.ansible/tmp/ansible-tmp-1509716706.71-110518228841126/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/tronde/.ansible/tmp/ansible-tmp-1509716706.71-110518228841126/setup.py; rm -rf "/home/tronde/.ansible/tmp/ansible-tmp-1509716706.71-110518228841126/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Find VM] *********************************************************************************************************
task path: /home/tronde/find_vm.yml:24
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest_find.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER:tronde
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tronde/.ansible/tmp/ansible-tmp-1509716708.79-256905694034887 `" && echo ansible-tmp-1509716708.79-256905694034887="` echo /home/tronde/.ansible/tmp/ansible-tmp-1509716708.79-256905694034887 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp1BLcVs TO /home/tronde/.ansible/tmp/ansible-tmp-1509716708.79-256905694034887/vmware_guest_find.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/tronde/.ansible/tmp/ansible-tmp-1509716708.79-256905694034887/ /home/tronde/.ansible/tmp/ansible-tmp-1509716708.79-256905694034887/vmware_guest_find.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/tronde/.ansible/tmp/ansible-tmp-1509716708.79-256905694034887/vmware_guest_find.py; rm -rf "/home/tronde/.ansible/tmp/ansible-tmp-1509716708.79-256905694034887/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ttSY7g/ansible_module_vmware_guest_find.py", line 235, in <module>
    main()
  File "/tmp/ansible_ttSY7g/ansible_module_vmware_guest_find.py", line 216, in main
    uuid=module.params['uuid']
  File "/tmp/ansible_ttSY7g/ansible_module_vmware_guest_find.py", line 123, in getvm_folder_paths
    folderpath = compile_folder_path_for_object(vobj)
  File "/tmp/ansible_ttSY7g/ansible_modlib.zip/ansible/module_utils/vmware.py", line 237, in compile_folder_path_for_object
AttributeError: 'NoneType' object has no attribute 'name'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ttSY7g/ansible_module_vmware_guest_find.py\", line 235, in <module>\n    main()\n  File \"/tmp/ansible_ttSY7g/ansible_module_vmware_guest_find.py\", line 216, in main\n    uuid=module.params['uuid']\n  File \"/tmp/ansible_ttSY7g/ansible_module_vmware_guest_find.py\", line 123, in getvm_folder_paths\n    folderpath = compile_folder_path_for_object(vobj)\n  File \"/tmp/ansible_ttSY7g/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 237, in compile_folder_path_for_object\nAttributeError: 'NoneType' object has no attribute 'name'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
	to retry, use: --limit @/home/tronde/find_vm.retry

PLAY RECAP *************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
