### ISSUE TITLE
json variable returned for launch configuration has wrong name ?

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#32548]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`ec2_lc`

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pkaramol/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

Empty result by: `ansible-config dump --only-changed`

##### OS / ENVIRONMENT

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
```
$ uname -a
Linux pkaramol-pc 4.10.0-37-generic #41~16.04.1-Ubuntu SMP Fri Oct 6 22:42:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

To access the name of a newly created launch configuration, variable `launch_configuration_name` is used (and not just `name`)
##### STEPS TO REPRODUCE

Playbook run:

```yaml
- name: Create a launch configuration
  ec2_lc:
    name: "some_name"
    state: present
    image_id: "some_image_id"
    region: "some_region"
    key_name: "some_key_name"
    security_groups: ["a_security_group_id"]
    instance_type: "an_instance_type"
    assign_public_ip: no
  register: rv_ec2_lc

- name: debug
  debug:
    msg: "{{ rv_ec2_lc.result }}"
```

##### EXPECTED RESULTS

```json
"msg": {
        "associate_public_ip_address": false, 
        "block_device_mappings": [], 
        "classic_link_vpc_security_groups": [], 
        "created_time": "2017-11-03 14:38:29.177000+00:00", 
        "ebs_optimized": false, 
        "image_id": "ami-59098j944", 
        "instance_monitoring": true, 
        "instance_type": "t2.micro", 
        "kernel_id": "", 
        "key_name": "some_key_name", 
        "launch_configuration_arn": "some_arn", 
        "name": "some_name",  # <--
        "placement_tenancy": "default", 
        "ramdisk_id": "", 
        "security_groups": [
            "sg-c4c6f7b6"
        ], 
        "user_data": ""
    }
```
##### ACTUAL RESULTS

```json
"msg": {
        "associate_public_ip_address": false, 
        "block_device_mappings": [], 
        "classic_link_vpc_security_groups": [], 
        "created_time": "2017-11-03 14:38:29.177000+00:00", 
        "ebs_optimized": false, 
        "image_id": "ami-59098j944", 
        "instance_monitoring": true, 
        "instance_type": "t2.micro", 
        "kernel_id": "", 
        "key_name": "some_key_name", 
        "launch_configuration_arn": "some_arn", 
        "launch_configuration_name": "some_name",  # <--
        "placement_tenancy": "default", 
        "ramdisk_id": "", 
        "security_groups": [
            "sg-c4c6f7b6"
        ], 
        "user_data": ""
    }
```

```

```
