### ISSUE TITLE
vmware_guest_snapshot don't find vm by name even if folder is specified

### ISSUE THREAD

**Issue by Tronde** [ansible/ansible#32544]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module name: vmware_guest_snapshot

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tronde/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
~~~
$ ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
~~~

##### OS / ENVIRONMENT
I'm running Ansible on RHEL 7.4 and try to use the module with VMware vSphere 6.0.0.

##### SUMMARY

I would like to take a snapshot from a running vm specifying the folder where the vm is placed in. But the vm cannot be found.

##### STEPS TO REPRODUCE

Running the following playbook with the command:
~~~
$ ansible-playbook take_vm_snapshot.yml
~~~

```yaml
---
- hosts: localhost
  connection: local
  vars_prompt:
    - name: "vc"
      promt: "Enter Virtual Center Server FQDN"
      private: no

    - name: "vc_datacenter"
      promt: "Enter the name of the Datacenter"
      private: no

    - name: "vc_user"
      promt: "Enter username to connect to vCenter Server: Example: bob@foo.example.com"
      private: no

    - name: "vc_passwd"
      promt: "Enter your password"
      privat: yes

  tasks:
    - name: Create snapshot
      vmware_guest_snapshot:
        hostname: "{{ vc }}"
        username: "{{ vc_user }}"
        password: "{{ vc_passwd }}"
        datacenter: "{{ vc_datacenter }}"
        folder: /JKA
        name: 'Ubuntu-Server-JKA'
        state: present
        snapshot_name: snap1
        description: "Fuegen Sie hier Ihre Beschreibung ein"
        validate_certs: false
      delegate_to: localhost
```

##### EXPECTED RESULTS

A snapshot with the name "snap1" should be taken from the vm "Ubuntu-Server-JKA".

##### ACTUAL RESULTS
The vm is not found and an error message stated out that the given vm does not exist.

```
$ ansible-playbook -vvvv take_vm_snapshot.yml 
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tronde/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: take_vm_snapshot.yml *****************************************************************************************
1 plays in take_vm_snapshot.yml
vc [vc-test.foo.example.com]: 
vc_datacenter: VC-TEST
vc_user: bob@foo.example.com
vc_passwd: 

PLAY [localhost] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: tronde
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tronde/.ansible/tmp/ansible-tmp-1509718251.46-219513481483391 `" && echo ansible-tmp-1509718251.46-219513481483391="` echo /home/tronde/.ansible/tmp/ansible-tmp-1509718251.46-219513481483391 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpG54Xyz TO /home/tronde/.ansible/tmp/ansible-tmp-1509718251.46-219513481483391/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/tronde/.ansible/tmp/ansible-tmp-1509718251.46-219513481483391/ /home/tronde/.ansible/tmp/ansible-tmp-1509718251.46-219513481483391/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/tronde/.ansible/tmp/ansible-tmp-1509718251.46-219513481483391/setup.py; rm -rf "/home/tronde/.ansible/tmp/ansible-tmp-1509718251.46-219513481483391/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Create snapshot] *************************************************************************************************
task path: /home/tronde/take_vm_snapshot.yml:23
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest_snapshot.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: tronde
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/tronde/.ansible/tmp/ansible-tmp-1509718253.59-45754752872062 `" && echo ansible-tmp-1509718253.59-45754752872062="` echo /home/tronde/.ansible/tmp/ansible-tmp-1509718253.59-45754752872062 `" ) && sleep 0'
<localhost> PUT /tmp/tmphtpj4h TO /home/tronde/.ansible/tmp/ansible-tmp-1509718253.59-45754752872062/vmware_guest_snapshot.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/tronde/.ansible/tmp/ansible-tmp-1509718253.59-45754752872062/ /home/tronde/.ansible/tmp/ansible-tmp-1509718253.59-45754752872062/vmware_guest_snapshot.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/tronde/.ansible/tmp/ansible-tmp-1509718253.59-45754752872062/vmware_guest_snapshot.py; rm -rf "/home/tronde/.ansible/tmp/ansible-tmp-1509718253.59-45754752872062/" > /dev/null 2>&1 && sleep 0'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "datacenter": "VC-TEST", 
            "description": "Fuegen Sie hier Ihre Beschreibung ein", 
            "folder": "/jka", 
            "hostname": "vc-test.foo.example.com", 
            "memory_dump": false, 
            "name": "Ubuntu-Server-JKA", 
            "name_match": "first", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "quiesce": false, 
            "remove_children": false, 
            "snapshot_name": "snap1", 
            "state": "present", 
            "username": "bob@foo.example.com", 
            "uuid": null, 
            "validate_certs": false
        }
    }, 
    "msg": "Unable to manage snapshots for non-existing VM Ubuntu-Server-JKA"
}
	to retry, use: --limit @/home/tronde/take_vm_snapshot.retry

PLAY RECAP *************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
