### ISSUE TITLE
vmware_guest_powerstate does not change power states as expected

### ISSUE THREAD

**Issue by doubleplush** [ansible/ansible#32552]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest_powerstate
module_utils/vmware.py

##### ANSIBLE VERSION
```
ansible 2.5.0
commit e65045f51fad48780fa7a67b389b4ed4b7bcdd46
```
##### SUMMARY
Due to the hyphenated state names used in the vmware_guest_powerstate module (`shutdown-guest`, `powered-on`, `powered-off`, etc.), the `set_vm_power_state` function is unable to convert the state name into one of its accepted states (`poweredoff`, `poweredon`, etc.).  The function can handle the presence of underscores in the expected_state, but not hyphens, as shown below:

```python 
module_utils/vmware.py, line 663-687:

def set_vm_power_state(content, vm, state, force):
...
    expected_state = state.replace('_', '').lower()
...
            if expected_state == 'poweredoff':
                task = vm.PowerOff()
```

This results in the vmware_guest_powerstate module terminating without actually making any changes to the VM, since it cannot determine the expected state.

The set_vm_power_state() function should also fail the module if an unknown state is provided.

##### STEPS TO REPRODUCE
```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - name: power off vm
      vmware_guest_powerstate:
        hostname: "{{ vcenter_host }}"
        name: test_vm
        state: shutdown-guest (powered-on, powered-off, etc.)
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: false
```
Results in the following output:
```
TASK [power off vm] ************************************************************
ok: [localhost]
```
Regardless of the actual power state of the VM.
