### ISSUE TITLE
The include_role now states that delegate_to is invalid 

### ISSUE THREAD

**Issue by jahickey** [ansible/ansible#32556]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include_role
##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/hickeyj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, May 10 2017, 20:04:28) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]

```
Sorry, I'm not able to test newer versions. Apologies if this has been fixed in newer versions
##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = This file is managed by Ansible. Changes may be overwritten
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
##### OS / ENVIRONMENT

Running Ansible on Fedora 25
Deploying to CentOS 7.x
##### SUMMARY

In previous versions of Ansible, using **delegate_to** worked for the **include_role** module. With an update to version 2.4.0, all my roles that use this are now generating an error
##### STEPS TO REPRODUCE

I have a playbook, and the standard roles hierarchy (roles/role-name/tasks/main.yml)
- playbook.yml

```yaml
- name: "Test the include role module"
  hosts: all
  remote_user: username
  become: yes

  roles:
    - test-include-role

```
- main.yml
```yaml
---
- name: "Test include role"
  include_role:
    name: set-sudo-no-passwd
    delegate_to: '{{ item }}'
  become: yes
  with_items: groups['all']

```

##### EXPECTED RESULTS

When I run the playbook, the role **set-sudo-no-passwd** should run.
Note that commenting out the **delegate_to** and **with_items** lines in the role allows the role to run properly.
##### ACTUAL RESULTS

The playbook fails with the following Error message - note that this is the only output

```
ERROR! Invalid options for include_role: delegate_to
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/role/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
A few things to note here.

1. You had `delegate_to` indented too far, it should have instead been:

    ```
    - name: "Test include role"
      include_role:
        name: set-sudo-no-passwd
      delegate_to: '{{ item }}'
      become: yes
      with_items: groups['all']
    ```
2. In recent versions of ansible, applying `delegate_to` to `include_role` achieves no result, as those task keywords only impact the `include_role` and are no inherited by the tasks within.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
