### ISSUE TITLE
Generate Diffie-Hellman Parameters with openssl module

### ISSUE THREAD

**Issue by thomwiggers** [ansible/ansible#32577]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
module openssl_*

##### SUMMARY

There are various commands to generate keys and certificates. It would be helpful to also be able to easily generate Diffie-Hellman parameters from Ansible.

##### Example

```yaml
- name: Generate DH params
  openssl_dhparam:
    path: /path/dhparam.pem
    bits: 4096
# openssl genpkey -genparam -algorithm DH -out /path/dhparam.pem -pkeyopt dh_paramgen_prime_len:4096
```
