### ISSUE TITLE
Alternative message: FAILED - RETRYING: 

### ISSUE THREAD

**Issue by andersla** [ansible/ansible#32584]
Is it possible to display a user friendlier message when looping waiting for a resource to become available than standard: **FAILED - RETRYING**?
If you want to display output of Ansible process to a user not used to Ansible - this sounds as there is something wrong - when it is actually just part of the planned waiting for a resource to become available after initialization?

If my task name is: "Waiting for server to start - usually takes 1-2 minutes"

Then I would like to customize to:
**RESOURCE NOT AVAILABLE YET - RETRYING:** Waiting for server to start - usually takes 1-2 minutes (43 Retries left)
Or just simply:
**RETRYING:** Waiting for server to start - usually takes 1-2 minutes (43 Retries left)
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION

```
ansible 2.3.0.0
configured module search path = Default w/o overrides
python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
@andersla Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ejade9** [comment]
Hello, is this feature delivered in 2.5?

**Comment by gdloch** [comment]
I also have the same issue with this FAILED message. Is there a way to change it?

**Comment by bcoca** [comment]
a custom callback can easily do this, or overriding the default callback and the `def v2_runner_retry` method. An 'additional' callback can give more information if you don't just want to replace the existing msg.

**Comment by theque5t** [comment]
@andersla @gdloch I recently opened PR #65844 which adds a callback plugin that I believe can assist with this issue. I have included an example below that I believe demonstrates the problem you have described, and the potential solution using the callback plugin. However, this would require using ansible 2.8.5 or higher.

# Example

## Ansible Version
```
ansible 2.8.5
  config file = None
  configured module search path = ['/home/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/root/py35_ansible28/lib/python3.5/site-packages/ansible
  executable location = /home/root/py35_ansible28/bin/ansible
  python version = 3.5.8 (default, Oct 31 2019, 00:57:08) [GCC 7.4.0]
```

## CONFIGURATION
```

```

## OS / ENVIRONMENT
```
Linux TESTBOX 4.4.0-17134-Microsoft #1130-Microsoft Thu Nov 07 15:21:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

## STEPS TO REPRODUCE

1. Create `callback_plugins` directory and add the [diy.py](https://raw.githubusercontent.com/ansible/ansible/781b71e17fc7fa5b3ae09b073c58d5142cceff23/lib/ansible/plugins/callback/diy.py) callback plugin to it

2. Create `playbook.yml`
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Reboot server
      debug:
        msg: mock reboot

    - name: Waiting for server to start - usually takes 1-2 minutes
      debug:
        msg: mock wait
      until: false
      retries: 5
      delay: 1
      failed_when: false
      vars:
        color_reset: "\e[0m"
        yellow: "\e[0m\e[38;5;226m"
        ansible_callback_diy_runner_retry_msg: >-
          {%- set result = ansible_callback_diy.result.output -%}
          {%- set retries_left = result.retries - result.attempts -%}
          RESOURCE NOT AVAILABLE YET - RETRYING: {{ ansible_callback_diy.task.name }} {{ yellow }}({{ retries_left }} Retries left)
        ansible_callback_diy_runner_retry_msg_color: cyan

    - name: Doing something
      debug:
        msg: mock something
```

3. Run the playbook command
```sh
ANSIBLE_STDOUT_CALLBACK=diy ansible-playbook -i localhost, playbook.yml
```

## RESULT
```sh
PLAY [localhost] **************************************************************************************************************************************************************************************************************************************************************

TASK [Reboot server] **********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "mock reboot"
}

TASK [Waiting for server to start - usually takes 1-2 minutes] ****************************************************************************************************************************************************************************************************************
RESOURCE NOT AVAILABLE YET - RETRYING: Waiting for server to start - usually takes 1-2 minutes (5 Retries left)
RESOURCE NOT AVAILABLE YET - RETRYING: Waiting for server to start - usually takes 1-2 minutes (4 Retries left)
RESOURCE NOT AVAILABLE YET - RETRYING: Waiting for server to start - usually takes 1-2 minutes (3 Retries left)
RESOURCE NOT AVAILABLE YET - RETRYING: Waiting for server to start - usually takes 1-2 minutes (2 Retries left)
RESOURCE NOT AVAILABLE YET - RETRYING: Waiting for server to start - usually takes 1-2 minutes (1 Retries left)
ok: [localhost] => {
    "msg": "mock wait"
}

TASK [Doing something] ********************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "mock something"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0

```
The retry message states `RESOURCE NOT AVAILABLE YET - RETRYING: Waiting for server to start - usually takes 1-2 minutes (X Retries left)`. Should you prefer to adjust the message further, I believe this example demonstrated how the plugin can be used to adjust the output to your preference(also, the plugin itself has documentation, which has additional examples).
