### ISSUE TITLE
Conditional roles masks non-conditional subsequent role

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#3261]
Using a play similar to the following

```

---
- hosts: boxes
  roles:
     - { role: foo, when: "0 == 1" }
     - bar
```

I am seeing that both the `foo` and `bar` role tasks are being skipped.
commenting the conditional role allows `bar` to be played as expected.
Is this expected behaviour?

ansible 1.2

**Comment by mpdehaan** [comment]
It is not.

Haven't observed this, I can take a look.

**Comment by mpdehaan** [comment]
can't reproduce this on my end, let me know if you have more info.

**Comment by ghost** [comment]
https://github.com/y-p/ansible_3261_example

```
λ ansible-playbook -i inventory site.yml 

PLAY [mainserver] ************************************************************* 

TASK: [debug msg="a is running"] ********************************************** 
ok: [127.0.0.1] => {"item": "", "msg": "a is running"}

TASK: [debug msg="b is running"] ********************************************** 
skipping: [127.0.0.1]

TASK: [debug msg="c is running"] ********************************************** 
skipping: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   

λ ansible --version
ansible 1.2

```

**Comment by ghost** [comment]
Bump. Would appreciate this issue being reopened.

**Comment by ghost** [comment]
Bump again, would be nice to at least have the issue reopened until 
you've had a chance to look at the repro example repo I created.

**Comment by ghost** [comment]
@mpdehaan: this is OSS, everyone is busy, I totally get it. 
Would you _please_ reopen just so this doesn't get lost?

**Comment by thafreak** [comment]
I'm also running into this issue. Ansible 1.2.2

This doesn't work:

```
---
- hosts: all
  user: root
  connection: ssh
  roles: 
    - { role: ovz-base, when: "ansible_virtualization_type == 'openvz'" }
    - common
```

All tasks in common also get skipped. I did find that this does work however:

```
---
- hosts: all
  user: root
  connection: ssh
  roles: 
    - { role: ovz-base, when: "ansible_virtualization_type == 'openvz'" }
    - { role: common }
```
