### ISSUE TITLE
Embedded modules in role should not be included in module search path when role is skipped in conditional import 

### ISSUE THREAD

**Issue by xscript** [ansible/ansible#32617]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/kevinzha/.ansible.cfg
  configured module search path = [u'/Users/kevinzha/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When conditionally importing roles in playbook, embedded modules in role are always included into module search path, even the role is skipped due to condition check failure.

It also happens when a role has conditionally role dependencies.  

##### STEPS TO REPRODUCE

Use below playbook as an example.
Role `test-1` and `test-2` both have an embedded module called `common_module`, while `test-1` is only imported with Ansible v2.4 and `test-2` is only imported with Ansible v2.5.

```yaml
- hosts: localhost
  roles:
    - { role: test-1, when: ansible_version.major == 2 and ansible_version.minor == 4 }
    - { role: test-2, when: ansible_version.major == 2 and ansible_version.minor == 5 }
  tasks:
    - name: run module
       common_module:
         name: test-name
```

##### EXPECTED RESULTS

When running in Ansible v2.4, `common_module` in `test-1` should be executed.
When running in Ansible v2.5, `common_module` in `test-2` should be executed.

##### ACTUAL RESULTS

`common_module` in `test-1` will always be executed no matter which version playbook is running in. Because both roles are included in module search path. The one in `test-1` will be found first.

```

```

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Imports are NOT conditional, that condition you added to the role signature is applied to the included tasks. not to the act of importing the role itself.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by nitzmahone** [comment]
So we think you could pull this off today with a conditional `include_role` in 2.4+ - that would probably get the behavior you want if run first thing in the play. But conditional plugin inclusion is potentially dangerous- there's been some discussion about killing it in future versions of Ansible because of all the potential for undefined behavior. For now, it'll probably do what you want, though.

**Comment by xscript** [comment]
@nitzmahone I just tried both `include_role` and `import_role`. Looks like it doesn't include the embedded modules into module search path.
My playbook looks like below:
```yaml
- hosts: localhost
  tasks:
    - name: conditionally import child-1
      include_role:
        name: xscript.child-1
      when: ansible_version.major == 2 and ansible_version.minor == 4
    - name: conditionally import child-2
      include_role:
        name: xscript.child-2
      when: ansible_version.major == 2 and ansible_version.minor == 5
    - name: create resource group
      azure_rm_resourcegroup:
        name: "ansible-{{ 65535 | random | string }}"
        location: "westus"
```

Part of the results looks like below. Both `xscript.child-1` and `xscript.child-2` have module `azure_rm_resourcegroup`, which have been modified a little.
My expectation is the last task should pick the module in role `xscript.child-1`. However, it doesn't.
Is this by design? Or do i miss anything?
```
TASK [xscript.child-1 : Print in console] *****************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/kevinzha/.ansible/roles/xscript.child-1/tasks/main.yml:3
...

TASK [xscript.child-2 : Print in console] *****************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/kevinzha/.ansible/roles/xscript.child-2/tasks/main.yml:3
skipping: [localhost] => {
    "changed": false, 
    "skip_reason": "Conditional result was False", 
    "skipped": true
}
...

TASK [create resource group] ******************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/kevinzha/workspace/ansible-role/playbook.yml:15
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_resourcegroup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: kevinzha
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
...
```
