### ISSUE TITLE
kubernetes and oc module should support kubeconfig files

### ISSUE THREAD

**Issue by juanluisvaladas** [ansible/ansible#32618]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
oc module
kubernetes module

##### ANSIBLE VERSION
Master branch, not implemented at all

##### SUMMARY
Kubeconfig files are the standard way to configure OpenShift and Kubernetes clients. They include all the authentication details:
- Url
- Token/x509 certification authentication
- TLS configuration (skip verify)
- etc.

##### EXPECTED RESULTS
I want to be able to do:

```
- name: Obtain an object definition
  oc:
   kubeconfig: /etc/origin/master/admin.kubeconfig
   state: present
   name: myroute
   namespace: mynamespace
   kind: Route
```

##### ACTUAL RESULTS
- Have to specify the host
- Have to specify the token
- Cannot use x509 client certs for authentication.
