### ISSUE TITLE
Support elliptic curves in the crypto modules

### ISSUE THREAD

**Issue by thomwiggers** [ansible/ansible#32626]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

openssl_privatekey
openssl_publickey (?)
openssl_csr (?)

##### SUMMARY

Many applications now support elliptic curve certificates and keys. It would be helpful to also be able to generate elliptic curve keys in Ansible.

This will probably require a major refactor as pyOpenSSL doesn't support this in the 'normal' API, you'd probably need to use  the`openssl._util.lib` C interface. Using the `cryptography` library is quite possibly a lot nicer.

##### DESIRED FUNCTIONALITY

```yaml
- openssl_privatekey:
    type: ec
    curve: secp256k1
    path: some/path.pem
```
