### ISSUE TITLE
authorized_key: path is ignored on 2.4.1

### ISSUE THREAD

**Issue by nblock** [ansible/ansible#32622]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
authorized_key

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.pyenv/versions/2.7.13/envs/apx-ansible/lib/python2.7/site-packages/ansible
  executable location = /home/user/.pyenv/versions/apx-ansible/bin/ansible
  python version = 2.7.13 (default, Aug 26 2017, 10:54:57) [GCC 6.3.0 20170516]

```

##### CONFIGURATION
no changes according to "ansible-config dump --only-changed"

##### OS / ENVIRONMENT
Debian Stretch on Python 2.7.13

##### STEPS TO REPRODUCE

```yaml
- name: Provide keys for root
  authorized_key:
    user: root
    path: /root/.ssh/authorized_keys2
    key: "{{ lookup('file', item) }}"
    state: present
  with_fileglob:
    - public_keys/admins_present/*.pub
```

##### EXPECTED RESULTS
Public keys being deployed to  ```/root/.ssh/authorized_keys2```.

This works on Ansible 2.3.2.0 and fails on Ansible 2.4.1.0

##### ACTUAL RESULTS
Public keys are deployed to the default location: ```/root/.ssh/authorized_keys``` instead.
