### ISSUE TITLE
ansible file module always reports changed when using both mode and ownership

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#32636]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
file
##### ANSIBLE VERSION

```
ansible 2.4.1.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Ansible is always touching files when you use owner/group in combination with mode, causing extra changed tasks when this is not really needed.

##### STEPS TO REPRODUCE

```yaml
- file:
    path: "/tmp/foo/bar/"
    recurse: yes
    state: directory
    owner: root
    group: root
    mode: 0700
```

##### EXPECTED RESULTS
Not reporting task as changed if the file already had correct ownership and correct mode.

##### ACTUAL RESULTS
Task is reported as changed.

**Comment by jborean93** [comment]
I'm unable to replicate this issue on 2.4.1.0 or in the latest devel branch. Are there any more details you can share such as;

* your host configuration
* whether you are running over SSH or on localhost
* the task output with `-vvv`
* Is it only affecting one host, or one type of host
* Does the issue disappear if you set it to a different user/group/path
* Is the file itself actually what it should be before running Ansible or is it failing silently?

**Comment by 0xd3e** [comment]
Same here using Ansible 2.4.2.0.

**Task Definition**

```yaml
- name: Create configuration directory
  file:
    path: /opt/docker-mounts/prometheus/config
    recurse: yes
    state: directory
    mode: u=rwx,g=rx,o=rx
```

**Output with -vvv**

```
changed: [prometheus.test.local] => {
    "changed": true,
    "diff": {
        "after": {
            "path": "/opt/docker-mounts/prometheus/config"
        },
        "before": {
            "path": "/opt/docker-mounts/prometheus/config"
        }
    },
    "gid": 0,
    "group": "root",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "content": null,
            "delimiter": null,
            "diff_peek": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "group": null,
            "mode": "u=rwx,g=rx,o=rx",
            "original_basename": null,
            "owner": null,
            "path": "/opt/docker-mounts/prometheus/config",
            "recurse": true,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "directory",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "mode": "0755",
    "owner": "root",
    "path": "/opt/docker-mounts/prometheus/config",
    "size": 4096,
    "state": "directory",
    "uid": 0
}
```

**Ansible Config**

```ini
[defaults]
host_key_checking = False
transport = ssh
nocows = 1
roles_path = ./roles

[privilege_escalation]
become = true

[ssh_connection]
ssh_args = -o ForwardAgent=yes -o ControlPath=/tmp/ssh-%r@%h:%p -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null

```

This also happens on another host with a similar task definition (only the path is different).

Ansible is running over SSH on some local virtual machines.

**Comment by 0xd3e** [comment]
Maybe I found the cause for this issue.

In another task (runs later), I'm writing a file into this directory with different permissions:

```yaml
- name: Write configuration
  copy:
    dest: /opt/docker-mounts/prometheus/config/prometheus.yml
    content: '{{ prometheus_config|to_nice_yaml }}'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
```

I also wondered why this task always reports that it changed. When running with `-vvv` the diff tells me that the permissions have changed:

```
changed: [localhost] => {
    "changed": true,
    "checksum": "09059686bad11570169252bc3433178a3b85fb7b",
    "diff": {
        "after": {
            "mode": "0644",
            "path": "/opt/docker-mounts/prometheus/config/prometheus.yml"
        },
        "before": {
            "mode": "0755",
            "path": "/opt/docker-mounts/prometheus/config/prometheus.yml"
        }
    },
...
```

So I assume that the task for creating the directory will also set the permissions of the file inside to `0755` and later the file permissions get changed to `0644`.

EDIT: Removing `recurse: yes` from the task specification in the previous comment solved the issue for me.
