### ISSUE TITLE
Change blockinfile behaviour when running two tasks modifying the same file

### ISSUE THREAD

**Issue by srkiNZ84** [ansible/ansible#32667]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
blockinfile module - https://docs.ansible.com/ansible/latest/blockinfile_module.html

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /Users/srdan/code/ansible_play/ansible.cfg
  configured module search path = ['/Users/srdan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.5/bin/ansible
  python version = 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### CONFIGURATION
DEFAULT_HASH_BEHAVIOUR(/Users/srdan/code/ansible_play/ansible.cfg) = merge

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Using "blockinfile" in two tasks, with both accessing the same "dest" file ends up with one task over-writing the others block.

##### STEPS TO REPRODUCE
Run a playbook with two tasks, both of which add different sections to the same file. After running, note that only one block is in the file.

```yaml
- hosts: all
  tasks:
    - name: Append service 2 to file
      connection: local
      blockinfile:
        dest: services.ini
        block: |
          [service2]
          version=bar

    - name: Append service 3 to file
      connection: local
      blockinfile:
        dest: services.ini
        block: |
          [service3]
          version=baz

    - name: Get file contents
      command: cat services.ini
      register: filecontents

    - name: Print out file
      debug: msg="{{ filecontents }}"
```

##### EXPECTED RESULTS
I expected the contents of the file to contain both "blocks" i.e.:
```
# BEGIN ANSIBLE MANAGED BLOCK
[service2]
version=bar
[service3]
version=baz
# END ANSIBLE MANAGED BLOCK
```

##### ACTUAL RESULTS
The file only contained the "service3" block:

```
# BEGIN ANSIBLE MANAGED BLOCK
[service3]
version=baz
# END ANSIBLE MANAGED BLOCK
```

NOTE: after reading the documentation, I can see that it does warn about this (in a round about way) in the bottom "NOTE" section, where it says:

>> When using ‘with_*’ loops be aware that if you do not set a unique mark the block will be overwritten on each iteration.

However, I still believe that this is really bad behaviour and at very least, if there are two "blockinfile" tasks referencing the same dest file, there should be some kind of warning that this could happen.
