### ISSUE TITLE
nmcli can't handle more than one ip for single interface

### ISSUE THREAD

**Issue by ruben-herold** [ansible/ansible#32675]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - nmcli

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT
- Centos 7

##### SUMMARY

nmcli does not allow more than one ip per interface

##### STEPS TO REPRODUCE

The nmcli command on Centos 7 can add multiple addresses for each interface:

nmcli con show lacp01 |grep addre
ipv4.addresses:                         192.168.0.1/28, 172.16.0.1/32
ipv6.addresses:                         2001:db8:1::1/64, 2001:db8:2::1/128

**Comment by ansibot** [comment]
cc @alcamie101
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by amolkahat** [comment]
@ruben-herold  I tested this on the upstream build. I did not see an issue.

##### Paybook
```
---
- name: sample
  hosts: local
  remote_user: root
  tasks:
  - name: Bonding for ethernet
    nmcli:
        type: ethernet
        conn_name: vlan0_1
        ip4: 192.168.0.8/24, 192.168.0.9/24
        gw4: 192.168.0.1
        mode: balance-rr
        state: present
```

##### Result on Remote machine
```
# nmcli con show vlan0_1 | grep ipv4.address
ipv4.addresses:                         192.168.0.8/24, 192.168.0.9/24
#
```
If you are still facing an issue, can you please paste an example? If not then @Akasurde will close this issue.
