### ISSUE TITLE
iSCSI port type is not coherent between ovirt_hosts and ovirt_storage_domains

### ISSUE THREAD

**Issue by tiraboschi** [ansible/ansible#32670]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ovirt_hosts
ovirt_storage_domains

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT
I'm running ansible 2.4 on centos 7.4 connecting to the host in loopback to manage oVirt 4.2 beta.

##### SUMMARY
The iSCSI port type is not coherent between ovirt_hosts and ovirt_storage_domains modules.

ovirt_hosts with state=iscsidiscover or iscsilogin fails with
TASK [iSCSI discover] *********************************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'int' object has no attribute 'isdigit'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "'int' object has no attribute 'isdigit'"}
	to retry, use: --limit @/root/test.retry

if iSCSI port is not a string

while, on opposite side,
ovirt_storage_domains fails with
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1510132120.29-205557456023623/ovirt_storage_domains.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1510132120.29-205557456023623/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ZZOjPn/ansible_module_ovirt_storage_domains.py", line 510, in main
    sd_id = storage_domains_module.create()['id']
  File "/tmp/ansible_ZZOjPn/ansible_modlib.zip/ansible/module_utils/ovirt.py", line 574, in create
    **kwargs
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 21183, in add
    return self._internal_add(storage_domain, headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 213, in _internal_add
    request.body = writer.Writer.write(object, indent=True)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/writer.py", line 189, in write
    writer(obj, cursor, root)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py", line 8767, in write_one
    HostStorageWriter.write_one(obj.storage, writer, 'storage')
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py", line 4177, in write_one
    LogicalUnitWriter.write_many(obj.logical_units, writer, 'logical_unit', 'logical_units')
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py", line 5172, in write_many
    LogicalUnitWriter.write_one(obj, writer, singular)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/writers.py", line 5137, in write_one
    Writer.write_integer(writer, 'port', obj.port)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/writer.py", line 77, in write_integer
    return writer.write_element(name, Writer.render_integer(value))
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/writer.py", line 69, in render_integer
    raise TypeError('The \'value\' parameter must be an integer')
TypeError: The 'value' parameter must be an integer

if port is not an integer

##### STEPS TO REPRODUCE

```yaml
---
- name: STEPS TO REPRODUCE
  hosts: localhost
  connection: local
  tasks:
  - name: iSCSI discover
    ovirt_hosts:
      name: "{{ HOST_NAME }}"
      state: iscsidiscover
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ STORAGE_DOMAIN_ADDR }}"
        port: "{{ ISCSI_PORT }}"
      auth:
        username: admin@internal
        password: "{{ ADMIN_PASSWORD }}"
        url: https://{{ FQDN }}/ovirt-engine/api
        insecure: true
    register: iscsi_targets
  - debug: var=iscsi_targets
  - name: iSCSI login
    ovirt_hosts:
      name: "{{ HOST_NAME }}"
      state: iscsilogin
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ STORAGE_DOMAIN_ADDR }}"
        port: "{{ ISCSI_PORT }}"
        target: "{{ ISCSI_TARGET }}"
      auth:
        username: admin@internal
        password: "{{ ADMIN_PASSWORD }}"
        url: https://{{ FQDN }}/ovirt-engine/api
        insecure: true
  - name: get iSCSI LUNs
    ovirt_host_storage_facts:
      host: "{{ HOST_NAME }}"
      iscsi:
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
        address: "{{ STORAGE_DOMAIN_ADDR }}"
        port: "{{ ISCSI_PORT }}"
        target: "{{ ISCSI_TARGET }}"
      auth:
        username: admin@internal
        password: "{{ ADMIN_PASSWORD }}"
        url: https://{{ FQDN }}/ovirt-engine/api
        insecure: true
    register: iscsi_devices
  - debug: var=iscsi_devices
  - name: add iscsi storage domain
    ovirt_storage_domains:
      name: "{{ STORAGE_DOMAIN_NAME }}"
      host: "{{ HOST_NAME }}"
      data_center: default
      wait: True
      iscsi:
        address: "{{ STORAGE_DOMAIN_ADDR }}"
        port: "{{ ISCSI_PORT }}"
        target: "{{ ISCSI_TARGET }}"
        lun_id: "{{ LUN_ID }}"
        username: "{{ ISCSI_USERNAME }}"
        password: "{{ ISCSI_PASSWORD }}"
      auth:
        username: admin@internal
        password: "{{ ADMIN_PASSWORD }}"
        url: https://{{ FQDN }}/ovirt-engine/api
        insecure: true
    register: storage_domain_details
  - debug: var=storage_domain_details
```
And run it with ISCSI_PORT as a string or as in int

##### EXPECTED RESULTS
Always expect a string or always expect an int but please be consistent.

##### ACTUAL RESULTS
ovirt_storage_domains fails if ISCSI_PORT is a string
ovirt_hosts (with state: iscsidiscover or state: iscsilogin) fails if ISCSI_PORT is an int
