### ISSUE TITLE
ansible_winrm_server_cert_validation=ignore doesn't work when use delegate_to run role in a wodows server

### ISSUE THREAD

**Issue by lsbwant** [ansible/ansible#32673]
ISSUE TYPE:
 - Bug Report

COMPONENT NAME:
delegate_to

ANSIBLE VERSION:
2.1 2.2 2.3 2.4

CONFIGURATION
```
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

OS / ENVIRONMENT:
Redhat7.3 in AWS
python 2.7.5
windows server 2012R2 in AWS

SUMMARY:
ansible_winrm_server_cert_validation=ignore doesn't work when I configure it in an inventory file then use directive "delegate_to" run a role in windows servers. the error message like following:

```
TASK [schema_drop_sqlserver : Database job executing.. please with..] *****************************************************************************************************************************
task path: /home/ec2-user/ShuaibingLi_datapump1.3_sql_2014/roles/schema_drop_sqlserver/tasks/main.yml:5
<52.220.55.74> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 52.220.55.74
fatal: [localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: HTTPSConnectionPool(host='52.220.55.74', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))",
    "unreachable": true
}
```

It will work if I don't use directive "delegate_to", just show a warning in console like following:

```
TASK [schema_drop_sqlserver : Database job executing.. please with..] **************************************************************************
task path: /home/jenkins/colline-ansible/roles/schema_drop_sqlserver/tasks/main.yml:5
<52.220.55.74> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 52.220.55.74
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
EXEC (via pipeline wrapper)
```

Or definite ansible_winrm_server_cert_validation=ignore in playbook rather than inventory file, it is work too

STEPS TO REPRODUCE:

hosts_inventory file:
```
[MSDatabaseServers]
192.168.1.100 ansible_user=Administrator ansible_password=password@111 ansible_port=5986 ansible_connection=winrm ansible_winrm_server_cert_validation=ignore
```

database_server.yml
```
---
db_server_ip: "192.168.1.100"
db_schema_name: "test_110"
```

importDatabase.yml
```
---
- name: Import Database Schema
  vars_files:
    - database_server.yml
  hosts: localhost
  connection: local
  any_errors_fatal: true
  serial: 1

  roles:
    - { role: db_import_sqlserver, delegate_to: "{{db_server_ip}}", when: "db_server_type == 'sqlserver'" }
```

roles/db_import_sqlserver/tasks/main.yml
```
---
  - name: STARTING DATABASE IMPORT FOR SQLSERVER
    debug: msg="ON DATABASE {{ db_server_ip }} with DB SCHEMA {{db_schema_name}}..."

  - name: "Database job executing.. please with.."
    raw: dir
```

ansible-playbook -i hosts_inventory importDatabase.yml

EXPECTED RESULTS:
have no CERTIFICATE_VERIFY_FAILED error

ACTUAL RESULTS:
```
fatal: [localhost]: UNREACHABLE! => {
    "changed": false,
    "msg": "ssl: HTTPSConnectionPool(host='192.168.1.100', port=5986): Max retries exceeded with url: /wsman (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:579)'),))",
    "unreachable": true
}
```

If add ansible_winrm_server_cert_validation: ignore in importDatabase, the yml file will run successful.

importDatabase.yml
```
---
- name: Import Database Schema
  vars_files:
    - database_server.yml
 vars:
    - ansible_winrm_server_cert_validation: ignore

  hosts: localhost
  connection: local
  any_errors_fatal: true
  serial: 1

  roles:
    - { role: db_import_sqlserver, delegate_to: "{{db_server_ip}}", when: "db_server_type == 'sqlserver'" }
```

**Comment by lsbwant** [comment]
Anyone like have a look?

**Comment by jborean93** [comment]
When Ansible has a `delegate_to`, what happens is it replaces the connection vars with the delegated host's connection vars. In the case of WinRM, pretty much all the `ansible_winrm_*` vars are not seen as connection vars and just as host facts. So when it comes to delegating to the Windows hosts, things like `ansible_winrm_server_cert_validation`, `ansible_winrm_transport` are not set as delegate_to uses the host facts/vars of the non delegated hosts.

There is work in the pipeline to fix this up and set all `ansible_winrm_*` vars as connection plugins but unfortunately it is still a WIP so isn't ready yet. In the meantime you can manually set the variables as a task var like so

```
- win_command: hostname
  delegate_to: windows-server
  vars:
    ansible_winrm_server_cert_validation: ignore
```

This way, Ansible will add the `ansible_winrm_server_cert_validation` to that task executation. While more verbose you can also do this as a workaround and source the var from your Windows host setting

```
- win_command: hostname
  delegate_to: windows-server
  vars:
    ansible_winrm_server_cert_validation: "{{hostvars['windows-server']['ansible_winrm_server_cert_validation']|default('ignore')}}"
```

This does the same as the first example but sources the value from the value set on your Windows host and use a default of `ignore` if it isn't set.
