### ISSUE TITLE
async option makes win_package and win_psexec unusable on Windows 7 SP1

### ISSUE THREAD

**Issue by jpalczewski** [ansible/ansible#32699]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_psexec

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jacek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jacek/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

nothing special was changed in ansible.cfg - except fact that I'm running from unique enviroment, see above
##### OS / ENVIRONMENT

Ansible host: debian stretch
Ansible-managed host: Windows 7 SP1 in packer, qemu-based - packer.py connection is used

##### SUMMARY

When async option is set for win_psexec or win_package, building process fails every time because of error:
```
FAILED! => {"changed": true, "failed": true, "module_stderr": "At line:1 char:99\r\n+ ... c_wrapper.ps1' 754360191862 100 \r\n'C:\\Users\\vagrant\\AppData\\Local\\Temp\\ansible-tmp ...\r\n+                    ~~~~~~~~~~~~\r\nUnexpected token '754360191862' in expression or statement.\r\nAt line:1 char:112\r\n+ ... ' 754360191862 100 \r\n'C:\\Users\\vagrant\\AppData\\Local\\Temp\\ansible-tmp-1510158845.5 ...\r\n+                    ~~~\r\nUnexpected token '100' in expression or statement.\r\nAt line:1 char:116\r\n+ 'C:\\Users\\vagrant\\AppData\\Local\\Temp\\ansible-tmp-1510158845.53-25932599520705\r\n0\\a ...\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n~~~\r\nUnexpected token ''C:\\Users\\vagrant\\AppData\\Local\\Temp\\ansible-tmp-1510158845.5\r\n3-259325995207050\\win_psexec.ps1'' in expression or statement.\r\nAt line:1 char:211\r\n+ ... in_psexec.ps1' _\r\n+                    ~\r\nUnexpected token '_' in expression or statement.\r\n    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordEx \r\n   ception\r\n    + FullyQualifiedErrorId : UnexpectedToken\r\n \r\nShared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

It might be related with powershell version(3.0), however - it's bit strange behaviour, because many other things(win_psexec, win_copy or win_package without async) works fine. 

##### STEPS TO REPRODUCE

Unfortunately Windows SP7 ISOs aren't publicly available, however packer script looks like [this one](https://github.com/boxcutter/windows/blob/master/win7x64-pro-ssh.json) - with additional provisioner(ansible) and packer.py file in connection_plugins folder.
And the error-causing part of playbook looks like

```yaml
   - name: Run spice guest tools
      win_psexec:
        command: echo hello world
        system: yes
        interactive: no
        executable: C:\tools\psexec.exe
        async: 100
        poll: 0
```
Steps: 
1. Run building process with `packer build <json_file>`
2. Wait 

##### EXPECTED RESULTS

Task should be executed
##### ACTUAL RESULTS

Fails with error provided beyond, I will add log with verbose flags/produces ps1 files tommorow. 

```

```

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
@jpalczewski I think your indentation isn't correct

try 
```yaml
   - name: Run spice guest tools
     win_psexec:
        command: echo hello world
        system: yes
        interactive: no
        executable: C:\tools\psexec.exe
     async: 100
     poll: 0
```

async isn't a module parameter, its a parameter for the action, so needs to be less indented than the module parameters.

Please try the above and report back.  If it works then I think maybe we should improve the examples here http://docs.ansible.com/ansible/latest/playbooks_async.html
