### ISSUE TITLE
yum_repository: baseurl and pgpkey broken in params option

### ISSUE THREAD

**Issue by stintel** [ansible/ansible#32691]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
yum_repository

##### ANSIBLE VERSION
```
nsible 2.4.0.0
  config file = None
  configured module search path = [u'/home/stijn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python2.7/site-packages/ansible
  executable location = /usr/lib/python-exec/python2.7/ansible
  python version = 2.7.12 (default, Jan  2 2017, 09:38:12) [GCC 4.9.4]
```

##### CONFIGURATION
empty

##### OS / ENVIRONMENT
Gentoo

##### SUMMARY
When using baseurl and gpgkey with the params option of the yum_repository module, a line break is added after each character in the repo file.

##### STEPS TO REPRODUCE
Run the playbook below:
```ansible-playbook yum.yml```

```yaml
---
- vars:
    yum_repos:
      - name: foo
        baseurl: http://some.repo/foo
        description: foo
        gpgkey: file:///tmp/foo.key

  hosts: all
  tasks:
    - name: yum repos
      yum_repository:
        name: "{{ item.name }}"
        params: "{{ item }}"
        reposdir: /tmp
      with_items: "{{ yum_repos }}"
```
Then run ```cat /tmp/foo.repo```

##### EXPECTED RESULTS
```
[foo]
baseurl = http://some.repo/foo
gpgkey = file:///tmp/foo.key
name = foo
```

##### ACTUAL RESULTS
```
[foo]
baseurl = h
        t
        t
        p
        :
        /
        /
        s
        o
        m
        e
        .
        r
        e
        p
        o
        /
        f
        o
        o
gpgkey = f
        i
        l
        e
        :
        /
        /
        /
        t
        m
        p
        /
        f
        o
        o
        .
        k
        e
        y
name = foo
```

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
Thanks for reporting this issue. The problem seems to be introduced in this [commit](https://github.com/ansible/ansible/commit/1b8fe94e5a51f888edededed0278eb7361cbc828#diff-3e0703568828cb54958e276ae5273b3a). I will fix that. In the meantime, you can use this workaround:

```yaml
---

- hosts: all
  connection: local
  gather_facts: no
  vars:
    yum_repos:
      - name: foo
        baseurl:
          - http://some.repo/foo
        description: foo
        gpgkey:
          - file:///tmp/foo.key
  tasks:
    - name: yum repos
      yum_repository:
        name: "{{ item.name }}"
        params: "{{ item }}"
        reposdir: /tmp
      with_items: "{{ yum_repos }}"
```
