### ISSUE TITLE
Using 'when' to include a task file and conditionally play included tasks results in improper jinja

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#3269]
When using a _when_ statement to conditionally include a task file, if the included tasks also rely on a _when_ statement, ansible is unable to evaluate True|False on the aggregate conditional.  See reproducer included below.

Perhaps related to #2592 ...
### Reproducer

_site.yml_

``` yaml

---
- name: reproducer
  hosts: local
  connection: local
  tasks:
   - include: tasks/rhel.yml
     when: ansible_distribution == 'RedHat'
```

_tasks/rhel.yml_

``` yaml

---
- name: rhel | do something
  shell: cat /etc/redhat-release
  when: ansible_lsb.major_version|int >= 6
```

_output_

``` bash
# ansible-playbook --check site.yml 

PLAY [reproducer] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [rhel | do something] **************************************************** 
fatal: [127.0.0.1] => Conditional expression must evaluate to True or False: ({% if ansible_lsb.major_version|int >= 6 %} True {% else %} False {% endif %}) and ({% if ansible_distribution == 'RedHat' %} True {% else %} False {% endif %})

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/tmp/ansible/site.retry

127.0.0.1                  : ok=1    changed=0    unreachable=1    failed=0   
```
### Workaround (ugh)

Move all _when_ statements into the task file.  This bypasses support for the _when_ statement alongside the _include_ statement.  Additionally, this workaround will generate a lot of repeated text throughout any included task files.

_site.yml_

``` yaml

---
- name: reproducer
  hosts: local
  connection: local
  tasks:
   - include: tasks/rhel.yml
```

_tasks/rhel.yml_

``` yaml

---
- name: rhel | do something
  shell: cat /etc/redhat-release
  when: ansible_distribution == 'RedHat' and ansible_lsb.major_version|int >= 6
```

_output_

``` bash
# ansible-playbook --check site.yml 

PLAY [reproducer] ************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [rhel | do something] *************************************************** 
skipping: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   

```
