### ISSUE TITLE
yum_repository includepkgs parameter break repo file

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#32704]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
yum_repository

##### ANSIBLE VERSION
```
2.4.1.0
```

##### CONFIGURATION
N/A
##### OS / ENVIRONMENT
N/A
##### SUMMARY
If you specify multiple packages to include Ansible will write the list as  Python list inside the repo file and make it unreadable by YUM.

##### STEPS TO REPRODUCE

```yaml
  yum_repository:
    name: '{{ item }}'
    includepkgs:
    - foo
    - bar
```

##### EXPECTED RESULTS
repo file should contain this line:
```
includepkgs=foo bar
```
##### ACTUAL RESULTS
repo file will include this invalid line:
```
includepkgs = ['foo', 'bar']
```

Documentation states explicitly that use of YAML lists is accepted but the reality is very different.
