### ISSUE TITLE
Ansible jumps to another role half way through current due to escaping bug

### ISSUE THREAD

**Issue by jamieburchell** [ansible/ansible#32728]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cron

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel 38444bb76c) last updated 2017/11/09 10:53:29 (GMT +100)
  config file = /mnt/d/web/playbooks/utils/ansible.cfg
  configured module search path = [u'/home/jamie/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jamie/ansible/lib/ansible
  executable location = /home/jamie/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/mnt/d/web/playbooks/utils/ansible.cfg) = [u'/mnt/d/web/playbooks/hosts']
DEFAULT_MANAGED_STR(/mnt/d/web/playbooks/utils/ansible.cfg) = Ansible managed
DEFAULT_ROLES_PATH(/mnt/d/web/playbooks/utils/ansible.cfg) = [u'/mnt/d/web/playbooks/galaxy_roles', u'/mnt/d/web/playbooks/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/jamie/.vault_pass.txt
```

##### OS / ENVIRONMENT
Bash on Windows 10

##### SUMMARY
Ansible starts running one role then half way through starts executing part of another role

##### STEPS TO REPRODUCE

Create and run a role containing this task, called goaccess-reports:

```
- name: create cron job
  cron:
    name: goaccess
    user: root
    job: "find /var/log/httpd/access_log* -mtime -35 | xargs grep $(date -d 'last month' '+%b\/%Y'): | goaccess --no-progress -o /var/log/goaccess-$(date -d 'last month' +'%Y%m').html"
    minute: "*/5"
    cron_file: goaccess
    state: present
  notify: reload cron
```

##### EXPECTED RESULTS
Some sort of error message or better handling/escaping

##### ACTUAL RESULTS
Play started running another playbook. This seems to have been caused by the lack of escaping by me on the above `\/` should have been `\\/`

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was:        /mnt/d/web/playbooks/utils/ib3-dynhosts
fatal: [ib3.uk]: FAILED! => {"changed": false, "msg": "Could not find or access 'ib3-dynhosts'\nSearched in:\n\t/mnt/d/web/playbooks/roles/goaccess-reports/files/ib3-dynhosts\n\t/mnt/d/web/playbooks/roles/goaccess-reports/ib3-dynhosts\n\t/mnt/d/web/playbooks/roles/goaccess-reports/tasks/files/ib3-dynhosts\n\t/mnt/d/web/playbooks/roles/goaccess-reports/tasks/ib3-dynhosts\n\t/mnt/d/web/playbooks/utils/files/ib3-dynhosts\n\t/mnt/d/web/playbooks/utils/ib3-dynhosts"}
```

Note that in this case, ib3-dynhosts is a completely unrelated role.
