### ISSUE TITLE
Receiving AnsibleFileNotFound when in fact the file exists

### ISSUE THREAD

**Issue by alexandrubau** [ansible/ansible#32766]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Ansible "copy" module

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
bento/ubuntu-16.04

##### SUMMARY
After cloning a repository from Github using Ansible's **git** module, I would like to copy the `settings-dist.yml` into `settings.yml` file. The problem is that Ansible throws the following error:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AnsibleFileNotFound: Could not find or access '/var/www/workshop/config/settings-dist.yml'
fatal: [workshop]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find or access '/var/www/workshop/config/settings-dist.yml'"}
```

The `settings-dist.yml` file resides in the cloned repository. After running `vagrant provision` again, the playbook runs successfully.

##### STEPS TO REPRODUCE

```yaml
- name: Clone repository
  git:
    repo: git@github.com:alexandrubau/workshop-php.git
    dest: "{{ deploy_path }}"
    version: master
    force: yes
    accept_hostkey: true
    ssh_opts: "-o StrictHostKeyChecking=no"

- name: Install composer packages
  composer:
    command: install
    working_dir: "{{ deploy_path }}"

- name: Scanning for sql files
  find:
    paths: "{{ deploy_path }}/sql"
    patterns: '*.sql'
    recurse: yes
  register: _deploy_sql_scripts

- name: Run sql scripts
  shell: mysql < {{ item.path }}
  with_items: "{{ _deploy_sql_scripts.files }}"

- name: Copy app config
  copy:
    src: "{{ deploy_path }}/config/settings-dist.yml"
    dest: "{{ deploy_path }}/config/settings.yml"
  notify: permissions-apache
```

##### EXPECTED RESULTS
Copy the file
