### ISSUE TITLE
cloudformation_facts vs. cloudformation+register formats are different

### ISSUE THREAD

**Issue by wknapik** [ansible/ansible#32789]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
cloudformation_facts

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### CONFIGURATION
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If you use `clouformation` with `register` and then switch to using `cloudformation_facts` instead, you'll find, that that the format of the data returned is different and you need to change your queries.

The difference is mostly in CamelCase vs. under_score, e.g.:
`json_query("stack_resources[?resource_type=='AWS::EC2::Subnet']")`
has to become
`json_query("stack_resource_list[?ResourceType=='AWS::EC2::Subnet']")`
etc.

That's unexpected, inconvenient and unnecessary.

##### STEPS TO REPRODUCE
```yaml
- cloudformation:
    stack_name: foo
    ...
  register: bar
```
vs.
```yaml
- cloudformation:
    stack_name: foo
    ...
- cloudformation_facts:
    stack_name: foo
    all_facts: true
- set_fact:
    bar: "{{ cloudformation.foo }}"
```
`bar`'s data format is different in those two cases.

##### EXPECTED RESULTS
Same format.

##### ACTUAL RESULTS
Different format.
