### ISSUE TITLE
Kernel initramfs failed to build - module completed successfully

### ISSUE THREAD

**Issue by infrascripting** [ansible/ansible#32791]
##### ISSUE TYPE

 - Feature Request

##### COMPONENT NAME

module: yum

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /ifs/ansible.cfg
  configured module search path = [u'/opt/ansible/ansible_boot/.virtenv/ifs/lib/python2.7/site-packages/ansible/modules', u'/ifs/library']
  python version = 2.7.5 (default, Oct 11 2015, 17:47:16) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
```

##### OS / ENVIRONMENT

RHEL7 & RHEL7
##### SUMMARY

When upgrading the packages, even if yum/dracut can't build the kernel initramfs due to too not enough space in `/boot`, the command completes successfully. This is revealed on reboot, as the kernel panics because no initramfs was built.

##### STEPS TO REPRODUCE

As long as the `/boot` partition is too small to build a new kernel initramfs for the newly installed kernel, yum will show dracut failing, ansible will not fail the task.

```yaml
- hosts: all
  tasks:
        
    - name: (pre_event) Free space in /boot partition is greater than 40MB
      shell: df -P /boot | grep -e "^/dev" | tr -s ' ' | cut -d ' ' -f 4
      register: boot_partition_space
      # 40MB
      failed_when: boot_partition_space.stdout|int >= 40000

    # Kernel has to be an update - else name=kernel
    - name: (pre_event) Update all packages on the system
      yum:
        name: '*'
        state: latest
```

##### EXPECTED RESULTS

The second task should fail when dracut fails to build the kernel initramfs

##### ACTUAL RESULTS

After the following script runs, and a reboot is issued, the server cannot boot up, as it always encounters a kernel panic.

Stdout:
```
[...]
  Cleanup    : ncurses-base-5.9-13.20130511.el7.noarch                1012/1013
  Cleanup    : libgcc-4.8.5-11.el7.x86_64                                          1013/1013
2661 blocks

gzip: stdout: No space left on device
dracut: creation of /boot/initramfs-3.10.0-693.2.2.el7.x86_64.img failed
mkinitrd failed
warning: %posttrans(kernel-3.10.0-693.2.2.el7.x86_64) scriptlet failed, exit status 1
Uploading Package Profile
  Verifying  : zlib-1.2.7-17.el7.i686                                                1/1013
  Verifying  : yum-rhn-plugin-2.0.1-9.el7.noarch                         2/1013
[...]
```

From our custom logging callback plugin:
```
  "changed": true,
  "msg": "Warning: RPMDB altered outside of yum.\n** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:\nkatello-ca-consumer-rhelsatsy01exdu.ent.oclc.org-1.0-12.noarch is a duplicate with katello-ca-consumer-rhelsatsy01exdu.ent.oclc.org-1.0-7.noarch\nNon-fatal POSTTRANS scriptlet failure in rpm package kernel-3.10.0-693.2.2.el7.x86_64\n",
  "rc": 0,
```

So even though the return code is 0 for the yum command, - I would appreciate if the yum module would be able to catch this.
