### ISSUE TITLE
vmware_guest not allowing mac address to be set when there is a duplicate in vCenter

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/ansible#32808]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

It's also possible this is the root issue for this one :  https://github.com/ansible/ansible/issues/21161

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/spollock/ansible/fs-vmw-control/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

```

##### SUMMARY

Although I am setting a static mac address with vmware_guest, it only works if this mac address is not already used somewhere on the vCenter.  I even try to override by setting "force: yes" and it behaves the same.  There is no error message given.

##### STEPS TO REPRODUCE

Try to set the mac using vmware_guest when the mac address already exists, it will change to automatic and assign a random mac.  If it does not exist, it works.

force = yes has no effect.

```yaml

- name: Launching machine "{{vcpreptargetkit}}{{vcprepelement[1:3]}}-{{vcpreptemplate}}"
  vmware_guest:
    validate_certs: no
    hostname: "{{ vcenterhostname }}"
    username: "{{ vcusername }}"
    password: "{{ vcpassword }}"
    datacenter: "{{ vcdatacenter }}"
    cluster: "{{ vccluster }}"
    template: "source template"
    name: "machine name"
    networks: 
        -name: "some port group"
          mac: "00:50:56:00:01:01"
    state: poweredoff
    force: yes
  delegate_to: localhost


```

##### EXPECTED RESULTS

Should have set the mac regardless.

##### ACTUAL RESULTS

Doesn't set the mac

```
No error messages are generated.
```
