### ISSUE TITLE
Multiple Ansible ssh connections block by firewall

### ISSUE THREAD

**Issue by VMois** [ansible/ansible#32823]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Ansible -> ssh connections

##### ANSIBLE VERSION

```
ansible 2.4.1.0
```

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=600s
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT

home host Debian 8, remote host running on Ubuntu

##### SUMMARY

Using Ansible on the remote host cannot connect and make even simple ping/pong (but when login manual using ssh command everything works). After some investigations, it seems that problem in Ansible. Ansible creates a new ssh connection for each command and firewall blocks it. My question, how can I config Ansible to use only one ssh connection for an entire playbook. Thanks!

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

I want to use only one ssh connection for an entire playbook.

##### ACTUAL RESULTS

```

```

**Comment by hvindin** [comment]
I'm not sure what sort of strange firewall config would kill connections if they happen to often (seems like an odd administrative choice) but you should be able to limit the number of connections being made by doing the following:

In your ansible config set:
[ssh_connection]
ssh_args = -C -o ControlMaster=yes -o ControlPersist=yes
control_path = %(directory)s/ansible-ssh-%%h-%%p-%%r
pipelining = True

That will make the ssh connections essentially eternal until you kill them with something like ssh -O exit.

Additionally it will enable pipelining. To make this work universally you will need to run a task like the following before you start connecting to a new host (ie. chuck this at the top of your playbook):

```yaml
hosts: all
become: yes
vars:
  ansible_ssh_pipelining: no
tasks:
  - name: delete requiretty from sudoers config
    lineinfile:
      dest: /etc/sudoers
      line: '^.*requiretty.*$'
      state: absent
      validate: '/usr/sbin/visudo -cf %s'
tags:
  - always
```

Should do it.
