### ISSUE TITLE
Unable to install files on the target 

### ISSUE THREAD

**Issue by tarpanpathak** [ansible/ansible#32820]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
- Unzip 

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'$HOME/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Oct 11 2016, 05:24:00) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

##### CONFIGURATION
- This returns nothing. 
```sh
$ ansible-config dump --only-changed
```
 
##### OS / ENVIRONMENT
- Client: OS X Sierra 
- Target: Amazon EC2 Ubuntu AMI 
- Trying to upgrade binaries on the target using playbooks. 

##### SUMMARY
- Unzip 

##### STEPS TO REPRODUCE
- Task (config) that is failing: 
```yaml 
- name: Unzip Nomad to download directory
  become: true
  unarchive:
    src: "{{ nomad_download_dir }}"
    copy: no
    dest: "{{ nomad_install_dir }}"
  when:
   - installed_nomad_version.stdout | version_compare(nomad_version, operator='lt', strict=True)
  tags:
   - nomad
```

- All tasks: 
```yaml
---
- name: Check if Nomad is already installed
  stat:
    path: "{{ nomad_install_dir }}/nomad"
  register: nomad_bin
  changed_when: false
  tags:
    - nomad

- name: Stop when nomad not installed
  fail:
    msg: 'Nomad not installed'
  when: nomad_bin.stat.exists == False

- name: Get currently installed Nomad version
  shell: "{{ nomad_install_dir }}/nomad version | grep '^Nomad' | cut -d' ' -f2 | sed -e 's/^v//'"
  register: installed_nomad_version
  when: nomad_bin.stat.exists
  changed_when: false
  tags:
   - nomad

- name: Download Nomad
  become: yes
  get_url:
   url: "{{ nomad_url }}/{{ nomad_version }}/{{ nomad_archive }}"
   dest: "{{ nomad_download_dir }}"
   sha256sum: "{{ nomad_linux_sha256sum }}"
  tags:
    - nomad

- name: Remove Nomad files if version is different
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
   - "{{ nomad_install_dir }}/nomad"
  when:
   - not installed_nomad_version | skipped
   - installed_nomad_version.stdout | version_compare(nomad_version, operator='lt', strict=True)
  tags:
   - nomad

- name: install unzip
  become: true
  package:
    name: unzip
    state: present

- name: Unzip Nomad to download directory
  become: true
  unarchive:
    src: "{{ nomad_download_dir }}"
    copy: no
    dest: "{{ nomad_install_dir }}"
  when:
   - installed_nomad_version.stdout | version_compare(nomad_version, operator='lt', strict=True)
  tags:
   - nomad
```

##### EXPECTED RESULTS
- Task should succeed and upgrade the required binary. 

##### ACTUAL RESULTS

```sh
The full traceback is:
  File "/tmp/ansible_BZ3L9Z/ansible_module_unarchive.py", line 141, in <module>
    from shlex import quote

fatal: [172.31.96.55]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": "/usr/local/bin/",
            "directory_mode": null,
            "exclude": [],
            "extra_opts": [],
            "follow": false,
            "force": null,
            "group": null,
            "keep_newer": false,
            "list_files": false,
            "mode": null,
            "original_basename": "tmp",
            "owner": null,
            "regexp": null,
            "remote_src": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": "/tmp",
            "unsafe_writes": null,
            "validate_certs": true
        }
    },
    "msg": "Failed to find handler for \"/tmp\". Make sure the required command to extract the file is installed. Command \"/bin/tar\" could not handle archive. Command \"/usr/bin/unzip\" could not handle archive."
}
```

Is the output telling me to make sure that `tar` and `unzip` are installed on the target node? If so, they are: 
```sh 
$ which tar; which unzip
/bin/tar
/usr/bin/unzip 
```

What am I doing wrong?

**Comment by hvindin** [comment]
I'm pretty sure that if you change you unarchive task to the following it will work:

```yaml
- name: Unzip Nomad to download directory
  become: true
  unarchive:
    src: "{{ nomad_download_dir }}/{{ nomad_archive }}"
    dest: "{{ nomad_install_dir }}"
    remote_src: yes
  when:
   - installed_nomad_version.stdout | version_compare(nomad_version, operator='lt', strict=True)
  tags:
   - nomad
```

It looks like you are trying to unzip "/tmp" which is a directory and therefore invalid.

Also, copy is deprecated in favor of remote_src, but that's just a stylistic thing :)

**Comment by tarpanpathak** [comment]
Thanks for your response @hvindin. I made the recommended changes:

Unzip task: 
```yaml 
- name: Unzip Nomad to download directory
  become: true
  unarchive:
    src: "{{ nomad_download_dir }}/{{ nomad_archive }}"
    dest: "{{ nomad_install_dir }}"
    remote_src: yes
  when:
   - installed_nomad_version.stdout | version_compare(nomad_version, operator='lt', strict=True)
  tags:
   - nomad
```
but am seeing the following error: 
```sh 
fatal: [IP_ADDR]: FAILED! => {
    "failed": true,
    "msg": "The conditional check 'installed_nomad_version.stdout | version_compare(nomad_version, operator='lt', strict=True)' failed. The error was: Version comparison: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in 'nomad_upgrade_linux.yml': line 51, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Unzip Nomad to download directory\n  ^ here\n"
}
```
