### ISSUE TITLE
msg: unsupported parameter for module: credentials_file

### ISSUE THREAD

**Issue by iamriz** [ansible/ansible#32834]
I had the same problem as reported in this issue: https://github.com/ansible/ansible/issues/19978.
It is said that this link: https://github.com/ichundu/gce helped him resolve his issue. But it's now a broken link.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible ver. 1.9.2, libcloud ver. 2.2.1
```

##### CONFIGURATION
Using ansible 1.9.2

##### OS / ENVIRONMENT
Debian GNU/Linux 7 (Debian linux 4.9.50-x86_64-linode86 on Linode)

##### SUMMARY
I provided credentials to Ansible by providing the modules directly so that it can talk with Google Cloud for provisioning and configuration actions.

##### STEPS TO REPRODUCE

```ansible_hosts file
[localhost]
127.0.0.1
```

```yaml (gce.yml)
- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: user-107@....iam.gserviceaccount.com
    credentials_file: "/home/user/compute-video-demo-ansible/gce_vars/user_107.json"
    project_id: project-107
    machine_type: n1-standard-1
    image: debian-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         credentials_file: "{{ credentials_file }}"
         project_id: "{{ project_id }}"

```

##### EXPECTED RESULTS
Instance will be launched.

##### ACTUAL RESULTS

By using the ff. command, 
ansible-playbook --private-key=~/.ssh/google_compute_engine -u user -i ansible_hosts gce.yml -vvvv

I'm getting:
```
PLAY [Create instance(s)] *****************************************************

TASK: [Launch instances] ******************************************************
<127.0.0.1> REMOTE_MODULE gce image=debian-7 project_id=project-107 credentials_file=/home/user/ansible-proj/gce_vars/user_107.json machine_type=n1-standard-1 instance_names=dev service_account_email=
<127.0.0.1> EXEC ['/bin/sh', '-c', 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1510529382.39-175881167651041 && echo $HOME/.ansible/tmp/ansible-tmp-1510529382.39-175881167651041']
<127.0.0.1> PUT /tmp/tmpl6PYdP TO /root/.ansible/tmp/ansible-tmp-1510529382.39-175881167651041/gce
<127.0.0.1> EXEC ['/bin/sh', '-c', u'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python /root/.ansible/tmp/ansible-tmp-1510529382.39-175881167651041/gce; rm -rf /root/.ansible/tmp/ansible-tmp-1510529382.39-175881167651041/ >/dev/null 2>&1']
failed: [127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: credentials_file

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/gce.retry

127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1

```
