### ISSUE TITLE
Fix ios_banner integration test issue

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#32837]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_banner

##### ANSIBLE VERSION

```
2.5
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Setup
  ios_banner:
    banner: login
    text: |
      Junk login banner
      over multiple lines
    state: present
    authorize: yes

- name: remove login
  ios_banner:
    banner: login
    state: absent
    authorize: yes
  register: result

- debug:
    msg: "{{ result }}"

- assert:
    that:
      - "result.changed == true"
      - "'no banner login' in result.commands" # does this break due to "contains?"

- name: remove login (idempotent)
  ios_banner:
    banner: login
    state: absent
    authorize: yes
  register: result

- assert:
    that:
      - "result.changed == false"
      - "result.commands | length == 0"

```

##### EXPECTED RESULTS

Should run sucessfully
##### ACTUAL RESULTS

```
task path: /Users/gnalawad/ansible/ganeshrn/ansible/test/integration/targets/ios_banner/tests/cli/basic-no-login.yaml:33
fatal: [an-ios-02]: FAILED! => {
    "assertion": "result.changed == false",
    "changed": false,
    "evaluated_to": false
}
```
