### ISSUE TITLE
apt_repository does not recognize filename option

### ISSUE THREAD

**Issue by sgutermann** [ansible/ansible#32833]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apt_repository

##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

No special configs, default install via pip

##### OS / ENVIRONMENT
Running ansible on debian jessie.

Deploying to debian stretch.

##### SUMMARY
FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (apt_repository) module: filename. Supported parameters include: install_python_apt,mode,repo,state,update_cache,validate_certs"}

##### STEPS TO REPRODUCE
I simply followed the example in the documentation for apt_repository and added "filename" which should be available since ansible 2.1

```yaml
- name: DOCKER | Add docker repo to apt
  apt_repository:
    repo: https://download.docker.com/linux/debian stretch stable
    state: present
    update_cache: yes
    filename: 'docker'
```

##### EXPECTED RESULTS
I expected to get the apt repo listed under the filename give as described in the documentation.

##### ACTUAL RESULTS

```
TASK [docker : DOCKER | Add docker repo to apt] *********************************************************************************************
fatal: [p4rt098.dip0.t-ipconnect.de]: FAILED! => {"changed": false, "failed": true, "msg": "Unsupported parameters for (apt_repository) module: filename. Supported parameters include: install_python_apt,mode,repo,state,update_cache,validate_certs"}

```
