### ISSUE TITLE
Only first environment is set .

### ISSUE THREAD

**Issue by eromoe** [ansible/ansible#32842]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.4
```

##### OS / ENVIRONMENT

centos 7

##### SUMMARY

vars:

```
bidspy_dist_dir : /data/bidspy/dist
config_dir: '{{ bidspy_dist_dir }}/config'
PRIVATE_REGISTRY: 'host01:5006'
BASIN_SPIDER_CONFIG_PATH: '{{ config_dir }}/spider/basin-spider/config_gpu'
```

hosts:

```
[all:vars]
ansible_user=root 
ansible_pass=vagrant

[registry]
host01

[others]
host02

```

site.yml :

```
- hosts: others
  tags: [others]
  environment:
    PRIVATE_REGISTRY: "{{PRIVATE_REGISTRY}}"
    BASIN_SPIDER_CONFIG_PATH: "{{BASIN_SPIDER_CONFIG_PATH}}"
  roles:
  - role: others
```

Run command `ansible-playbook site.yml -i hosts --tags 'others'` , and go into vagrant vm,  only found `PRIVATE_REGISTRY`  is set.
