### ISSUE TITLE
multiline shell fails on FreeBSD

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#32853]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

shell
##### ANSIBLE VERSION

```
ansible 2.4.0.0
```

##### OS / ENVIRONMENT

FreeBSD 11.1-RELEASE-p1 server 
FreeBSD 11.1-RELEASE-p1 client
##### SUMMARY

quoted multiline shell command is treated as separate commands. 
##### STEPS TO REPRODUCE

```yaml
- name: get server environment
  local_action: shell env
  register: server_env

- name: log play data
  shell: |
    echo "starting new play" | logger -p user.notice -t ansible.logger.new_play
    echo "{{ server_env.stdout }}" | logger -p user.notice -t ansible.logger.server_env

```

##### EXPECTED RESULTS

server_env.stdout multiline content gets piped into logger. This worked fine in ansible 2.3. And stilll works fine in 2.4 on Linux client.

##### ACTUAL RESULTS

Shell module fails.

```
"stderr": "Unmatched '\"'.\nSSH_CONNECTION=1.2.3.4: Command not found.\n_=/usr/bin/env: Command not found.\n... etc.
```
Each line of server_env.stdout is treated as separate command, despite all newlines are inside quotes.
