### ISSUE TITLE
If logged in, docker_login will return the current password in results

### ISSUE THREAD

**Issue by ntwrkguru** [ansible/ansible#32869]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_login

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/foo/Documents/Repos/foo/ansible/ansible.cfg
  configured module search path = [u'/Users/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_RETRIES(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = 3
DEFAULT_HOST_LIST(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = [u'/Users/foo/Documents/Repos/foo/ansible/inventory']
DEFAULT_ROLES_PATH(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = [u'/Users/foo/Documents/Repos/foo/ansible/roles']
HOST_KEY_CHECKING(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS Sierra connecting to Ubuntu 16.04.03 and Docker Server Version: 17.09.0-ce

##### SUMMARY

If already logged in to the Docker Hub on the target machine, running a docker_login task with the wrong credentials will return the actual password in the results.

##### STEPS TO REPRODUCE

1. Run the playbook below, entering the correct password when prompted
2. Run the playbook below, entering the wrong password when prompted

__NOTE that this only seems to work the first run after logging in successfully. Subsequent runs will return `"password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"`__

```yaml
---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: hub_username
      prompt: "Enter your Docker Hub username"
      private: no
    - name: hub_email
      prompt: "Enter your Docker Hub email address"
      private: no
    - name: hub_password
      prompt: "Enter your Docker Hub password"
      private: yes
  tasks:
  - name: login to Docker Hub
    docker_login:
      username: "{{ hub_username }}"
      email: "{{ hub_email }}"
      password: "{{ hub_password }}"
    register: login_results
  - debug: 
      var: login_results
```

##### EXPECTED RESULTS

Failed login attempt

##### ACTUAL RESULTS

```
changed: [node1] => {
    "changed": true,
    "failed": false,
    "invocation": {
        "module_args": {
            "api_version": null,
            "cacert_path": null,
            "cert_path": null,
            "config_path": "~/.docker/config.json",
            "debug": false,
            "docker_host": null,
            "email": "<redacted>",
            "filter_logger": false,
            "key_path": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "reauthorize": false,
            "registry_url": "https://index.docker.io/v1/",
            "ssl_version": null,
            "state": "present",
            "timeout": null,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null,
            "username": "<redacted>"
        }
    },
    "login_result": {
        "email": "<redacted>",
        "password": "<redacted>",
        "serveraddress": "https://index.docker.io/v1/",
        "username": "<redacted>"
    }
}
```

__NOTE that if one adds `reauthorize: yes`, this issue is not present.__
