### ISSUE TITLE
vmware_dvswitch module : add a parameter to set the dvswitch version

### ISSUE THREAD

**Issue by mldmld68** [ansible/ansible#32862]
##### ISSUE TYPE
 - Feature Idea
##### COMPONENT NAME
vmware_dvswitch

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

-->

##### OS / ENVIRONMENT

N/A
control vSphere 6.5 on vcenter and ESXi 6.0 

##### SUMMARY
This module deploys only the latest version of the dvswitch which is equal to the version of the vcenter.
But if the ESXis has not the same version as vcenter, the ESXi cannot join the dvswitch

Please add a parameter to allow the deployment of a specific dvswitch version in this module
This parameter could also be used to upgrade a dvswitch to a new version.
See 
https://docs.vmware.com/en/VMware-vSphere/6.0/com.vmware.vsphere.networking.doc/GUID-330A0689-574A-4589-9462-14CA03F3F2F4.html

##### STEPS TO REPRODUCE
Install vcenter in vSphere 6.5
Install one ESXi in vSphere 6.0
Deploy a dvswitch in a datacenter
Try to add the ESXi hosts to this dvswitch

```
dvSwitches:
  - { name: 'my-dvSwitch', esxi_hostname: 'host1', Nic0: 'vmnic2', Nic1: 'vmnic3', datacenter: 'mydc', dnsdomain: 'my.domain', present: 'present' }
  - { name: 'my-dvSwitch', esxi_hostname: 'host2', Nic0: 'vmnic2', Nic1: 'vmnic3', datacenter: 'mydc', dnsdomain: 'my.domain', present: 'present' }

    - name: Create distributed Virtual Switches
      vmware_dvswitch:
        hostname: "{{ vcenter_name }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        datacenter_name: "{{ item.datacenter }}"
        switch_name: "{{item.name}}"
        mtu: 9000
        uplink_quantity: 2
        discovery_proto: lldp
        discovery_operation: both
        state: "{{item.present}}"
        validate_certs: "{{ vcenter_validate_certs }}"
        state: "{{item.present}}"
      with_items: "{{ dvSwitches }}"

    - name: Add Hosts to dvSwitches and setup uplinks
      vmware_dvs_host:
        hostname: "{{ vcenter_name }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        esxi_hostname: "{{ item.esxi_hostname }}.{{item.dnsdomain}}"
        switch_name: "{{item.name}}"
        vmnics:
        - "{{ item.Nic0 }}"
        - "{{ item.Nic1 }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        state: "{{item.present}}"
      with_items: "{{ dvSwitches }}"


```

##### EXPECTED RESULTS
The possibility to set a dvswitch version could allow to support vcenter/ESXi with not the same version
##### ACTUAL RESULTS
```

    "msg": "(vmodl.fault.NotSupported) {\n   dynamicType = <unset>,\n   dynamicProperty = (vmodl.DynamicProperty) [],\n   msg = 'The operation is not supported on the object.',\n   faultCause = <unset>,\n   faultMessage = (vmodl.LocalizableMessage) [\n      (vmodl.LocalizableMessage) {\n         dynamicType = <unset>,\n         dynamicProperty = (vmodl.DynamicProperty) [],\n         key = 'com.vmware.vim.vpxd.dvs.notSupportedHostVersion.label',\n         arg = (vmodl.KeyAnyValue) [\n            (vmodl.KeyAnyValue) {\n               dynamicType = <unset>,\n               dynamicProperty = (vmodl.DynamicProperty) [],\n               key = 'host',\n               value = 'myhost1.my.domain'\n            },\n            (vmodl.KeyAnyValue) {\n               dynamicType = <unset>,\n               dynamicProperty = (vmodl.DynamicProperty) [],\n               key = 'version',\n               value = '6.5.0'\n            }\n         ],\n         message = 'Host myhost1.my.domain is not compatible with the VDS version 6.5.0'\n      }\n   ]\n}"
```

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jcpowermac @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mldmld68** [comment]
Hi
The feature I need seems to be easy to add : 

According https://github.com/vmware/pyvmomi/blob/master/docs/vim/DistributedVirtualSwitch/CreateSpec.rst
One may read : 
productInfo (vim.dvs.ProductSpec, optional):

    Product information for this switch implementation. If you do not specify this property, the Server will use the latest version to create the DistributedVirtualSwitch .

And here : https://github.com/vmware/pyvmomi/blob/master/docs/vim/dvs/ProductSpec.rst
Attributes:
<..>
       version (str, optional):
        Dot-separated version string. For example, "1.2".

So the key is to add this property. I looked at the code and I see line 151 : 
151 spec.productInfo = vim.dvs.ProductSpec()
152 spec.productInfo.name = "DVS"
153 spec.productInfo.vendor = "VMware"

So the way seems to add
- the parameter in the module
- this statement : spec.productInfo.version = self.version

I'm a former C developper and I don't know python, but I think it's easy to add this feature. I don't know Github very well, so I will try to add this feature myself.
Thanks for any help :-)
Regards

**Comment by Akasurde** [comment]
@mldmld68 Thanks for information, it will be very helpful. Would like to raise PR against this issue ?

**Comment by mldmld68** [comment]
@Akasurde I just send a PR. But I don't know how to test my code yet on my linux box.

**Comment by mldmld68** [comment]
Could someone help me to figure out this error message : 
 ERROR: lib/ansible/modules/cloud/vmware/vmware_dvswitch.py:0:0: E309 version_added for new option (switch_version) should be 2.5. Currently 0.0 (75%)

**Comment by mldmld68** [comment]
I try to test this updated module, but the new parameter switch_version is not taken into account.
I get : 
    "msg": "Unsupported parameters for (vmware_dvswitch) module: switch_version Supported parameters include: datacenter_name,discovery_operation,discovery_proto,hostname,mtu,password,state,switch_name,uplink_quantity,username,validate_certs"

**Comment by mldmld68** [comment]
Found a way : adding a subdirectory named "library" and put the new module in it. The new module is taken into account. The module is ok. Need to update the documentation as the only supported version are 6.5.0, 6.0.0, 5.5.0, 5.1.0, 5.0.0.

**Comment by eegilbert** [comment]
@mldmld68 a little off topic, however do you know of a way to set a port group to Trunk (all vlans, or 0 -4094)?

**Comment by mldmld68** [comment]
@eegilbert : not sure to understand what you mean by Trunk. But here is a code to setup a port group in a dvswitch. 
The network team can tag the ethernet packets with a vlanid, or not tag it (vlanid = 0).
The network configuration must present all the vlanID required to the ESXi. On HPE blades, one can do that in virtual connect profiles, since the vlan are configured in the switches.

```yaml
    - name: Create portgroups of dvswitches
      vmware_dvs_portgroup:
        hostname: "{{ vcenter_name }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        portgroup_name: "{{item.name}}"
        switch_name: "{{item.sw_name}}"
        vlan_id: "{{item.vlan_id}}"
        num_ports: "{{item.num_ports}}"
        portgroup_type: "{{item.pg_type}}"
        validate_certs: "{{ vcenter_validate_certs }}"
        state: "{{item.present}}"
      with_items: "{{ dvSw_PortGroups }}"
```

And you have elsewhere in you playbook a list of portgroups to create. Here I create it with vlan_id 0

```yaml
dvSw_PortGroups:
  - { name: 'myportgroup', sw_name: 'mydvswitch', vlan_id: '0', num_ports: '128', pg_type: 'earlyBinding', present: 'present'}
  - {....}
```
