### ISSUE TITLE
docker_login module returns failed=false even when login fails

### ISSUE THREAD

**Issue by ntwrkguru** [ansible/ansible#32868]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`docker_login`

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/ssteiner/Documents/Repos/foo/ansible/ansible.cfg
  configured module search path = [u'/Users/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_RETRIES(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = 3
DEFAULT_HOST_LIST(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = [u'/Users/foo/Documents/Repos/foo/ansible/inventory']
DEFAULT_ROLES_PATH(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = [u'/Users/foo/Documents/Repos/foo/ansible/roles']
HOST_KEY_CHECKING(/Users/foo/Documents/Repos/foo/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

MacOS Sierra connecting to Ubuntu 16.04.03 and Docker Server Version: 17.09.0-ce

##### SUMMARY

When using `become: true`, the docker_login module returns `"failed" : false` even if bad credentials are passed and login to Docker Hub is unsuccessful.

##### STEPS TO REPRODUCE

Run the playbook below.

```yaml
---
- hosts: all
  become: true
  gather_facts: no
  vars_prompt:
    - name: hub_username
      prompt: "Enter your Docker Hub username"
      private: no
    - name: hub_email
      prompt: "Enter your Docker Hub email address"
      private: no
    - name: hub_password
      prompt: "Enter your Docker Hub password"
      private: yes
  tasks:
  - name: login to Docker Hub
    docker_login:
      username: "{{ hub_username }}"
      email: "{{ hub_email }}"
      password: "{{ hub_password }}"
    register: login_results
  - debug: 
      var: login_results
```

##### EXPECTED RESULTS

```
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "Logging into https://index.docker.io/v1/ for user <redacted> failed - 401 Client Error: Unauthorized (\"Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password\")"}
```

##### ACTUAL RESULTS

```
ok: [node1] => {
    "login_results": {
        "changed": true,
        "failed": false,
        "login_result": {
            "email": "<redacted>",
            "password": "foo", 
            "serveraddress": "https://index.docker.io/v1/",
            "username": "<redacted>"
        }
    }
}
```
Coincidentally, it seems to echo the password back even though it should not.

```
ok: [node1] => {
    "login_results": {
        "changed": true,
        "failed": false,
        "login_result": {
            "email": "<redacted>",
            "password": "foo",
            "serveraddress": "https://index.docker.io/v1/",
            "username": "<redacted>"
        }
    }
}
```

**Comment by ansibot** [comment]
cc @chouseknecht @jctanner @olsaki
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ntwrkguru** [comment]
If the argument `reauthorize: yes` is added to the task, this issue is not observed.

```yaml
---
- hosts: all
  gather_facts: no
  vars_prompt:
    - name: hub_username
      prompt: "Enter your Docker Hub username"
      private: no
    - name: hub_email
      prompt: "Enter your Docker Hub email address"
      private: no
    - name: hub_password
      prompt: "Enter your Docker Hub password"
      private: yes
  tasks:
  - name: login to Docker Hub
    docker_login:
      username: "{{ hub_username }}"
      email: "{{ hub_email }}"
      password: "{{ hub_password }}"
      reauthorize: yes
    register: login_results
  - debug: 
      var: login_results
```

```
The full traceback is:
  File "/tmp/ansible_267Moe/ansible_module_docker_login.py", line 189, in login
    dockercfg_path=self.config_path
  File "/usr/local/lib/python2.7/dist-packages/docker/api/daemon.py", line 148, in login
    return self._result(response, json=True)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 228, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 224, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)

fatal: [node1]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "api_version": null,
            "cacert_path": null,
            "cert_path": null,
            "config_path": "~/.docker/config.json",
            "debug": false,
            "docker_host": null,
            "email": "<redacted>",
            "filter_logger": false,
            "key_path": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "reauthorize": true,
            "registry_url": "https://index.docker.io/v1/",
            "ssl_version": null,
            "state": "present",
            "timeout": null,
            "tls": null,
            "tls_hostname": null,
            "tls_verify": null,
            "username": "<redacted>"
        }
    },
    "msg": "Logging into https://index.docker.io/v1/ for user <redacted> failed - 401 Client Error: Unauthorized (\"Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password\")"
}
```
