### ISSUE TITLE
ecs_task fails with versioned task definition

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#32872]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ecs_task

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /home/will/src/ansible/ansible.cfg
  configured module search path = [u'/home/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  2 2017, 18:42:05) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When passing a versioned task definition to ecs_task, the subsequent call to `list_tasks` will fail because it uses the task definition as the family, and doesn't like the `:` separating task definition name and version.

It's also unclear what the benefit of list tasks is for the `run` operation - running `ecs_task` in `run` mode with the same values should well cause the same task to be repeated (or at least that should be optionally possible)

##### STEPS TO REPRODUCE
Create a task definition and pass the task definition version to ecs_task

```yaml
    - name: create ECS task definition
      ecs_taskdefinition:
        profile: "{{ profile|default(omit) }}"
        region: "{{ region }}"
        containers: "{{ ecs_task_containers }}"
        volumes: "{{ ecs_task_volumes|default(omit) }}"
        family: "{{ ecs_task_name }}"
        task_role_arn: "{{ ecs_task_role_arn|default(omit) }}"
        state: present
      register: task_output

    - name: run ECS task
      ecs_task:
        cluster: "{{ ecs_cluster }}"
        task_definition: "{{ ecs_task_name }}:{{ task_output.taskdefinition.revision }}"
        operation: run
        count: 1
        started_by: "ecs_task {{ service_name }} {{ env }}"
        profile: "{{ profile|default(omit) }}"
        region: "{{ region }}"
```

##### EXPECTED RESULTS
Task runs fine.

##### ACTUAL RESULTS

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_opwony/ansible_module_ecs_task.py", line 322, in <module>
    main()
  File "/tmp/ansible_opwony/ansible_module_ecs_task.py", line 273, in main
    existing = service_mgr.list_tasks(module.params['cluster'], task_to_list, status_type)
  File "/tmp/ansible_opwony/ansible_module_ecs_task.py", line 187, in list_tasks
    desiredStatus=status
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 605, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the ListTasks operation: family must match ^[a-zA-Z0-9\-_]+$
```

**Comment by ansibot** [comment]
cc @Java1Guy @simplesteph
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by BDuelz** [comment]
I'm experiencing the same issue. Any idea when this will be fixed?

**Comment by threewordphrase** [comment]
Me as well. I am happy to contribute a fix if someone can point me in the right direction.

**Comment by bazmera** [comment]
Is there a fix for it?

**Comment by willthames** [comment]
A typical task definition ARN looks like `arn:aws:ec2:us-east-1:{{ aws_account_id }}:task-definition/sleep360:1`

Changing https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ecs_task.py#L315 to be

```
# optionally remove task definition version
task_to_list = ':'.join(module.params['task_definition'].split(':')[:6])
```

**Comment by hmorgado** [comment]
I'm trying to find this piece of code to fix, but I just can't.
Looking everywhere in my `/usr/local/lib/python2.7/dist-packages/ansible` folder and also through the source code in ansible's repository.
All I see is:
```
$ grep -Ri 'task_to_list' * 

ecs_task.py:        task_to_list = module.params['task_definition']
ecs_task.py:        task_to_list = module.params['task']
ecs_task.py:        task_to_list = module.params['task_definition']
ecs_task.py:    existing = service_mgr.list_tasks(module.params['cluster'], task_to_list, status_type)
modules/cloud/amazon/ecs_task.py:        task_to_list = module.params['task_definition']
modules/cloud/amazon/ecs_task.py:        task_to_list = module.params['task']
modules/cloud/amazon/ecs_task.py:        task_to_list = module.params['task_definition']
modules/cloud/amazon/ecs_task.py:    existing = service_mgr.list_tasks(module.params['cluster'], task_to_list, status_type)
```

**Comment by willthames** [comment]
@hmorgado what version are you on?

You can also just use a local version of ecs_task:
https://willthames.github.io/2017/12/12/using-updated-modules-with-stable-ansible.html

**Comment by hmorgado** [comment]
@willthames I tried ansible 2.8 and 2.7.

**Comment by hmorgado** [comment]
Turns out I wasn't passing all the variables I should have. It works now: 
```
 - name: Run task
    ecs_task:
      operation: run
      cluster: logger
      task_definition: logzio
      task: arn:aws:ecs:us-east-1:882244178194:task-definition/logzio:3
      launch_type: FARGATE
      count: 1
      started_by: heitormorgado
      network_configuration:
        subnets:
          - subnet-1111aaaa
```

**Comment by Errol12** [comment]
still facing the same issue

**Comment by calix** [comment]
Have the same issue. Anything new on this?

**Comment by ansibot** [comment]
cc @jillr @s-hertel @tremble
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by peguera-eu** [comment]
I figured out a solution, it's more of a workaround while this bug doesn't get solved but it works:

just leave the task as an empty string when starting or running tasks. My deploy role looks like this:

```yaml
- name: run migration task
  ecs_task:  
    cluster: "{{ env }}"  
    count: 1  
    launch_type: FARGATE  
    task: ""  
    network_configuration:  
      subnets: "{{ service_subnets }}"  
      security_groups: "{{ service_security_groups }}"  
      assign_public_ip: yes  
    operation: run  
    started_by: Ansible  
    region: "{{ aws.default_region }}"  
    task_definition: "{{ env }}-{{ app }}-{{ item.role }}"  
    validate_certs: no  
  when: "item.role == 'migration'"  
  with_items: "{{ containers }}"   
```
