### ISSUE TITLE
lvol fails with ValueError

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#32886]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

lvol

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Jun 17 2014, 18:11:42) [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
```

##### OS / ENVIRONMENT

Linux 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

The lvol module is not idempotent with the size of a partition when it's not exactly an integer

##### STEPS TO REPRODUCE

```yaml
- name: Create infravg volume
  lvg:
     vg: "infravg"
     pvs: "/dev/sdb"

- name: Create logical volumes
  lvol:
    vg: "infravg"
    lv: "myvolume"
    size: "9.8"

- name: Create filesystem
  filesystem:
    fstype: ext4
    dev: /dev/infravg/myvolume

- name: Mount logical volume
  mount:
    name: "/appli"
    src: /dev/infravg/myvolume
    fstype: ext4
    state: mounted

```

##### EXPECTED RESULTS

Works everytime I use it.

##### ACTUAL RESULTS

Works on the first time, fail on the second with the following error

```
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_l98tgx/ansible_module_lvol.py\", line 497, in <module>\r\n    main()\r\n  File \"/tmp/ansible_l98tgx/ansible_module_lvol.py\", line 452, in main\r\n    elif shrink and int(size) < this_lv['size']:\r\nValueError: invalid literal for int() with base 10: '9.8'\r\n",
```
