### ISSUE TITLE
os_floating_ip may throw AttributeError: internal_network

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#32884]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
os_floating_ip

##### ANSIBLE VERSION
```
2.4.1.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When there is no network called `internal_network`, use of os_floating_ip module may throw an error that look like:

```
 
```

##### STEPS TO REPRODUCE

```yaml
- name: Create floating IPs
  os_floating_ip:
      cloud: "some-cloud"
      network: "some_network"
      nat_destination: "some_nat"
      server: "some_server"
      state: present
      wait: yes
```

##### EXPECTED RESULTS

Success.

##### ACTUAL RESULTS

```
"module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/dn/bdsfszyj63569bgkwf1jsrw80000gn/T/ansible_GYIz2Z/ansible_module_os_floating_ip.py\", line 276, in <module>\n    main()\n  File \"/var/folders/dn/bdsfszyj63569bgkwf1jsrw80000gn/T/ansible_GYIz2Z/ansible_module_os_floating_ip.py\", line 215, in main\n    (nat_destination and f_ip.internal_network == fixed_address),\n  File \"/Users/ssbarnea/.pyenv/versions/2.7.13/lib/python2.7/site-packages/munch/__init__.py\", line 103, in __getattr__\n    raise AttributeError(k)\nAttributeError: internal_network\n",
```
