### ISSUE TITLE
Recursive dependencies are run multiple times if using include_role or import_role in the root role

### ISSUE THREAD

**Issue by vbohata** [ansible/ansible#32888]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
include_role, import_role

##### ANSIBLE VERSION

```
at least ansible 2.4.0.0 + ansible 2.4.1.0
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/myuser/ansible/ansible.cfg) = [u'/home/myuser/ansible/hosts']
DEFAULT_MODULE_PATH(/home/myuser/ansible/ansible.cfg) = [u'/home/myuser/ansible/modules']
DEFAULT_MODULE_UTILS_PATH(/home/myuser/Elastic/ansible/ansible.cfg) = [u'/home/myuser/ansible/module_utils']
DEFAULT_ROLES_PATH(/home/myuser/ansible/ansible.cfg) = [u'/home/myuser/ansible/roles']
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If role common has dependency on role common_base in meta/main.yml and myrole1, myrole2 lists common as a dependency in meta/main.yml, the role common_base is executed once as expected. If using include_role or import_role in myrole1, myrole2, the common_base is executed twice (NOT EXPECTED).

##### STEPS TO REPRODUCE

```yaml
roles/myrole1/tasks/main.yml
---

- name: Include common role
  include_role:
    name: common

- name: Include common role
  include_role:
    name: common

roles/common/meta/main.yml
---

allow_duplicates: true
dependencies:
  - { role: common_base }

roles/common/tasks/main.yml
---

- name: dbg
  debug:
    msg:
      - Debug from common


roles/common_base/meta/main.yml
---

allow_duplicates: false

roles/common_base/tasks/main.yml
---

- name: dbg
  debug:
    msg:
      - "Debug message from common_base"
```

##### EXPECTED RESULTS
```
PLAY [Test playbook] ********************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [192.168.56.101]

TASK [myrole1 : Include common role] ****************************************************************************************************************************************

TASK [common_base : dbg] ****************************************************************************************************************************************************
ok: [192.168.56.101] => {
    "msg": [
        "Debug message from common_base"
    ]
}

TASK [common : dbg] *********************************************************************************************************************************************************
ok: [192.168.56.101] => {
    "msg": [
        "Debug from common"
    ]
}

TASK [myrole1 : Include common role] ****************************************************************************************************************************************

TASK [common : dbg] *********************************************************************************************************************************************************
ok: [192.168.56.101] => {
    "msg": [
        "Debug from common"
    ]
}
```

##### ACTUAL RESULTS

```
PLAY [Test playbook] ********************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************
ok: [192.168.56.101]

TASK [myrole1 : Include common role] ****************************************************************************************************************************************

TASK [common_base : dbg] ****************************************************************************************************************************************************
ok: [192.168.56.101] => {
    "msg": [
        "Debug message from common_base"
    ]
}

TASK [common : dbg] *********************************************************************************************************************************************************
ok: [192.168.56.101] => {
    "msg": [
        "Debug from common"
    ]
}

TASK [myrole1 : Include common role] ****************************************************************************************************************************************

TASK [common_base : dbg] ****************************************************************************************************************************************************
ok: [192.168.56.101] => {
    "msg": [
        "Debug message from common_base"
    ]
}

TASK [common : dbg] *********************************************************************************************************************************************************
ok: [192.168.56.101] => {
    "msg": [
        "Debug from common"
    ]
}
```
