### ISSUE TITLE
Ansible 2.4.1.0: synchronize module ignores  'ansible_python_interpreter' variable

### ISSUE THREAD

**Issue by johnreed00** [ansible/ansible#32894]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

synchronize
##### ANSIBLE VERSION
```
ansible 2.4.1.0
```

##### OS / ENVIRONMENT
FreeBSD 11.1-RELEASE-p1 server
FreeBSD 11.1-RELEASE-p1 client

##### SUMMARY
synchronize module ignores  'ansible_python_interpreter' variable and fails trying to use '/us/bin/python' while 'ansible_python_interpreter' variable is set to '/usr/local/bin/python' at group_vars

##### STEPS TO REPRODUCE

```
% cat unixadm/group_vars/all
ansible_user: ansible
ansible_python_interpreter: /usr/local/bin/python
```

```yaml
% cat unixadm/test.yml
---
 - hosts: all
   tasks:
    - debug: msg="ansible_python_interpreter={{ ansible_python_interpreter }}"
    - copy: dest=/tmp/vars.xxx content="{{ vars|to_nice_yaml }}"
    - file: path=/tmp/vars.xxx state=absent
    - synchronize: src=/tmp/usr/ dest=/tmp/usr/ recursive=yes rsync_path="sudo rsync"
```

##### EXPECTED RESULTS
```
% ansible-playbook -i inventories unixadm/test.yml
```
debug module shows the variable 'ansible_python_interpreter':
```
ok: [domain.local] => {
    "msg": "ansible_python_interpreter=/usr/local/bin/python"
}
```
it's normal.
And sychronize would try to copy files from /tmp/usr/

##### ACTUAL RESULTS

```
TASK [synchronize] ********************************************************************************************************************************************************************************************
task path: /data/home/user/ansible/test.yml:10
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/files/synchronize.py
<domain.local> ESTABLISH LOCAL CONNECTION FOR USER: user
<domain.local> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [domain.local]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "/bin/sh: /usr/bin/python: not found\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 127
}

```
So, synchronize module ignores 'ansible_python_interpreter' in group_vars. But if you set "ansible_python_interpreter" via extra_vars or in inventory (all:vars) it works.

**Comment by ansibot** [comment]
cc @tima
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by discostur** [comment]
I'm getting a similar error with ansible 2.4.0:

```
"module_stderr": "/bin/sh: /opt/local/bin/python: No such file or directory\n", 
```

but "/opt/local/bin/python" is my custom set python interpreter. Just trying to sync two folders:

```
- name: sync /opt/test
  synchronize:
    src: mellorimon
    dest: /test/
```

inventory:

```
[all:vars]
        ansible_python_interpreter=/opt/local/bin/python
```
