### ISSUE TITLE
vmware_guest - vm identification using uuid still requires name parameter

### ISSUE THREAD

**Issue by Yinaij** [ansible/ansible#32901]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  python version = 2.7.14 (default, Nov  2 2017, 18:42:05) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]

```
Also tested this on 2.4.0.0.

##### CONFIGURATION

ANSIBLE_SSH_CONTROL_PATH(/media/sf_shared/repos/ansible/ansible.cfg) = ~/%%h‐%%r
DEFAULT_BECOME_METHOD(/media/sf_shared/repos/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/media/sf_shared/repos/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_WHITELIST(/media/sf_shared/repos/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/media/sf_shared/repos/ansible/ansible.cfg) = 50
DEFAULT_REMOTE_USER(/media/sf_shared/repos/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/media/sf_shared/repos/ansible/ansible.cfg) = [u'/media/sf_shared/repos/ansible/roles']
DEFAULT_TIMEOUT(/media/sf_shared/repos/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/media/sf_shared/repos/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/media/sf_shared/repos/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ansible on Fedora release 26 (Twenty Six)
VMware vSphere 6

##### SUMMARY

In the documentation for vmware_guest it says:
"UUID of the instance to manage if known, this is VMware's unique identifier.
This is required if name is not supplied." At the same time it says that parameter "name" is a required parameter.

Also the documentation for vmware_guest has an example which only uses uuid as an identifier.
```
- name: Remove a VM by uuid
  vmware_guest:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    uuid: 421e4592-c069-924d-ce20-7e7533fab926
    state: absent
  delegate_to: localhost
```
In the current state this example does not work.

##### STEPS TO REPRODUCE

```yaml
- name: Check that vm exists using hostname
  vmware_guest_facts:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    datacenter: "{{ vmware_datacenter }}"
    validate_certs: no
    name: "{{ inventory_hostname }}"
    folder: "{{ vmware_datacenter }}/vm/{{ vmware_folder }}"
  become: false
  delegate_to: localhost
  register: vm_facts

- name: Remove vm by uuid.
  vmware_guest:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    datacenter: "{{ vmware_datacenter }}"
    validate_certs: no
    uuid: "{{ vm_facts.instance.hw_product_uuid }}"
    state: absent
  become: false
  delegate_to: localhost
  when: vm_facts.instance.hw_product_uuid is defined
```

##### EXPECTED RESULTS

That the virtual machine would be deleted from the vmware cluster without having to supply an empty name parameter.

##### ACTUAL RESULTS

```
fatal: [wintest-2008.domain -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "XXX", 
            "disk": [], 
            "folder": "/vm", 
            "force": false, 
            "hardware": {}, 
            "hostname": "vcenter-hostname", 
            "is_template": false, 
            "linked_clone": false, 
            "name_match": "first", 
            "networks": [], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "state": "absent", 
            "username": "ansible-vmware", 
            "uuid": "423357e8-ba35-923a-3671-f83151244487", 
            "validate_certs": false, 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "missing required arguments: name"
}

```

A workaround is to supply an empty name parameter.
```
- name: Remove vm by uuid.
  vmware_guest:
    hostname: "{{ vmware_vcenter_hostname }}"
    username: "{{ vmware_username }}"
    password: "{{ vmware_password }}"
    datacenter: "{{ vmware_datacenter }}"
    validate_certs: no
    name: 
    uuid: "{{ vm_facts.instance.hw_product_uuid }}"
    state: absent
  delegate_to: localhost
  when: vm_facts.instance.hw_product_uuid is defined
```
