### ISSUE TITLE
Ansible ios_command module removing passwords from output

### ISSUE THREAD

**Issue by dieherna** [ansible/ansible#32917]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- Network / ios

##### ANSIBLE VERSION

```
ansible 2.4.1.0
```

##### SUMMARY
When running a commands in the "ios_command" module, specifically "show run", Ansible is removing any instances that match the password used to log into the device from the output produced, the password in the output is being replaced with '********'.

##### STEPS TO REPRODUCE

```yaml
---

- name: IOS GET CONFIG
  hosts: VIRL
  gather_facts: no
  connection: local

  vars_prompt:
  - name: "mgmt_username"
    prompt: "Username"
    private: no
  - name: "mgmt_password"
    prompt: "Password"

  tasks:
  - name: SYS | Define Provider
    set_fact:
      provider:
        host: "{{ ansible_host }}"
        username: "{{ mgmt_username }}"
        password: "{{ mgmt_password }}"

  - name: IOS | Show Run
    ios_command:
      provider: "{{ provider }}"
      commands:
        - ter len 0
        - show run
    register: show_run

  - name: LOCAL | Save Configuration File
    local_action: copy content={{ show_run.stdout[1] | regex_search('(?s)version.*') }}
                  dest=~/Python/cisco/Ansible_Configs/VIRL_Configs/{{ inventory_hostname }}.txt

  - name: DEBUG | Print Running-Config
    debug: msg="{{ show_run.stdout_lines[1] }}"
```

##### EXPECTED RESULTS
```
version 15.6
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R2
!
boot-start-marker
boot-end-marker
!
!
vrf definition Mgmt-intf
 !
 address-family ipv4
 exit-address-family
 !
 address-family ipv6
 exit-address-family
!
enable password cisco  <<<<--- This is the password used to log in and the password obtained via vars_prompt. This should remain clear text just as if I had logged into the device and ran the "show ru " command.
!
no aaa new-model
ethernet lmi ce
```

##### ACTUAL RESULTS
```
version 15.6
service timestamps debug datetime msec
service timestamps log datetime msec
no service password-encryption
!
hostname R2
!
boot-start-marker
boot-end-marker
!
!
vrf definition Mgmt-intf
 !
 address-family ipv4
 exit-address-family
 !
 address-family ipv6
 exit-address-family
!
enable password ******** <<<<--- string "cisco" has been replaced, this also occurs in the rest of the configuration where the word "Cisco is seen"
!
no aaa new-model
ethernet lmi ce
```
