### ISSUE TITLE
[Regression] network_cli: indefinite hang if sshkey isn't in known_hosts

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#32931]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
network_cli

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel 43f89004a0) last updated 2017/11/15 11:25:45 (GMT +100)

```

##### SUMMARY
If the fingerprint isn't in `known_hosts` then ansible-playbook will hang

This is a regression as in `stable-2.4` after a timeout we would get `unable to open shell`.

So there seem to be two issues here: 
1) Timeout isn't triggered
2) No message displayed (possibly caused by #1)

##### STEPS TO REPRODUCE
Move known_hosts or use `ssh-keygen -f "/home/johnb/.ssh/known_hosts" -R ios02.example.net`

```
[ios]
ios02.example.net ansible_connection=local ansible_user=ansible ansible_ssh_pass=ansible
```

```yaml
- name: "Download switch configuration"
  hosts: switches
  gather_facts: no

  tasks:
   ###
   # Collect data
    - name: Gather facts (ios)
      ios_facts:
      register: result_ios
      when: "'ios' in group_names"

```

If I use  `connection: network_cli` the same issue

##### EXPECTED RESULTS

Something along the lines of:

```
fatal: [ios02.example.net]: FAILED! => {"msg": "host key not known ios02.example.net"}
```

##### ACTUAL RESULTS

```
TASK [Gather facts (ios)] ************************************************************************************************************************************************************************************************************************
task path: /home/johnb/git/ansible-inc/gundalows-test-cases/net-usecase-1-facts-v4/net-usecase-1-facts.yml:8
skipping: [eos01.example.net] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
skipping: [vyos01.example.net] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
<ios02.example.net> attempting to start connection
<ios02.example.net> using connection plugin network_cli
```
Hangs for minutes
