### ISSUE TITLE
debug with_items prints loop_var even if using labels

### ISSUE THREAD

**Issue by markus-s24** [ansible/ansible#32947]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
debug task

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/markus/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### OS / ENVIRONMENT
MacOS

##### SUMMARY
When using debug with with_items, the loop_var is always printed, even if it is NOT appearing in the msg.

##### STEPS TO REPRODUCE
```yaml
  - name: Echo
    command: echo "Some stdout"
    register: output
    with_items: "{{ customers }}"
    loop_control:
      loop_var: customer
      label: "{{ customer.name }}"

  - name: Debug
    debug: msg="{{ result.stdout_lines }}"
    with_items: "{{ output.results }}"
    loop_control:
      loop_var: result
      label: "{{ result.customer.name }}"
```

##### EXPECTED RESULTS
loop_var ("result") NOT being printed.

##### ACTUAL RESULTS
```
ok: [some host] => (item=xxx) => {
    "msg": [
        "Some stdout"
    ], 
    "result": {
        ...
        "stdout_lines": [
            "Some stdout"
        ]
    }
}
```
