### ISSUE TITLE
hostvars for failed hosts exits and is full of garbage

### ISSUE THREAD

**Issue by aemakeye** [ansible/ansible#32969]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

setup.py
##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /home/makeand/.ansible.cfg
  configured module search path = ['/usr/lib/python3.6/site-packages/ara/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.3 (default, Oct 31 2017, 19:00:36) [GCC 6.4.0]
```

##### OS / ENVIRONMENT
```
$ uname -a
CYGWIN_NT-6.1 DEFRAVD823445 2.9.0(0.318/5/3) 2017-09-12 10:18 x86_64 Cygwin
```

##### SUMMARY

hostvars for failed hosts contains garbage, but exists. 
##### STEPS TO REPRODUCE

```yaml
---
- hosts: mygroup
  gather_facts: False
  pre_tasks:
    - name: "store play hosts in ansible_play_hosts_initial"
      set_fact: 
        ansible_play_hosts_initial: "{{ ansible_play_hosts }}"      

    - name: "debug output"
      debug: 
        var: ansible_play_hosts_initial
        verbosity: 0
  run_once: True

  tasks:      
    - name: "gather facts"
      setup:
      ignore_errors: true
    - name: "dump hostvars"
      debug:
        var: hostvars[item]['ansible_nodename']
        verbosity: 0
      with_items: "{{ ansible_play_hosts_initial }}"

  vars: 
    ansible_play_hosts_initial: []

```

##### EXPECTED RESULTS

```
2017-11-16 15:17:38,518 p=10164 u=makeand |  ok: [goodhost1.example.com] => (item=goodhost1.example.com) => {
    "hostvars[item]['ansible_nodename']": "goodhost1",
    "item": "goodhost1.example.com"
}
2017-11-16 15:17:38,600 p=10164 u=makeand |  ok: [goodhost1.example.com] => (item=goodhost2.example.com) => {
    "hostvars[item]['ansible_nodename']": "goodhost1",
    "item": "goodhost2.example.com"
}
2017-11-16 15:17:38,690 p=10164 u=makeand |  ok: [goodhost1.example.com] => (item=badhost.example.com) => {
    "hostvars[item]['ansible_nodename']": None,
    "item": "badhost.example.com"
}
```

##### ACTUAL RESULTS

```
2017-11-16 15:17:38,518 p=10164 u=makeand |  ok: [goodhost1.example.com] => (item=goodhost1.example.com) => {
    "hostvars[item]['ansible_nodename']": "goodhost1",
    "item": "goodhost1.example.com"
}
2017-11-16 15:17:38,600 p=10164 u=makeand |  ok: [goodhost1.example.com] => (item=goodhost2.example.com) => {
    "hostvars[item]['ansible_nodename']": "goodhost1",
    "item": "goodhost2.example.com"
}
2017-11-16 15:17:38,690 p=10164 u=makeand |  ok: [goodhost1.example.com] => (item=badhost.example.com) => {
    "hostvars[item]['ansible_nodename']": "goodhost1",
    "item": "badhost.example.com"
}
