### ISSUE TITLE
uri module executed twice

### ISSUE THREAD

**Issue by lmilbaum** [ansible/ansible#32978]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
uri

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### OS / ENVIRONMENT
control machine - docker container Ubuntu 16.04

##### SUMMARY

Rest API command executed via uri module is triggered twice although specified in the playbook only once

##### STEPS TO REPRODUCE

```yaml

- name: MedOne | deploy server
  uri:
    method: POST
    url: "https://{{ iaas.cloud_api_url }}/caas/2.6/{{ iaas.org_id }}/server/deployServer"
    body: "{{ lookup('file','/var/tmp/server.json') }}"
    body_format: "json"
    user: "{{ iaas.user_name }}"
    password: "{{ iaas.password }}"
    force_basic_auth: yes
    return_content: yes
    headers:
      Content-Type: "application/json"
   register: deploy_server_response

```

##### EXPECTED RESULTS
The rest API command executed once

##### ACTUAL RESULTS
The rest API command executed twice
