### ISSUE TITLE
Respond to expect prompts in networking modules

### ISSUE THREAD

**Issue by jabelk** [ansible/ansible#32989]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

aireos_command_module
ios_command_module

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /Users/jabelk/.ansible.cfg
  configured module search path = [u'/Users/jabelk/learning_ansible/napalm-ansible', u'/Users/jabelk/learning_ansible/ntc-ansible']
  ansible python module location = /Users/jabelk/myvirtualenvironments/ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/jabelk/myvirtualenvironments/ansible/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### SUMMARY

Some common network commands expect a response (yes/no, y/n, etc.) and since each ansible command is a separate ssh session the prompts cannot be easily answered. Something along these lines would be helpful:

http://docs.ansible.com/ansible/latest/expect_module.html

here are some other google searched examples of the issue:
https://stackoverflow.com/questions/40045342/ansible-cisco-ios-and-reload-command
https://groups.google.com/forum/#!topic/Ansible-project/Sb4EIJIOGY8

In my case I was trying to initiate a file transfer where the initiate transfer command asks for a (y/n) response which was not easy to do. 

##### STEPS TO REPRODUCE

```yaml
---
- name: Upgrade WLC Version Prep
  hosts: wlc
  gather_facts: False
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      timeout: 30

  tasks:
    - name: Prep Upgrade with transfer
      aireos_command:
        provider: "{{ creds }}"
        commands:
            - transfer download filename AIR-CT5500-K9-8-0-152-0.aes
            - transfer download path //
            - transfer download datatype code
            - transfer download mode tftp
            - transfer download tftpmaxRetries 6
            - transfer download tftpPktTimeout 6
            - transfer download serverip 10.0.0.1
            - transfer download start
```

##### EXPECTED RESULTS

Would like something along the lines of 

``` yaml
  aireos_command:
        provider: "{{ creds }}"
        commands:
             - transfer download start
         prompt: "Are you sure you want to start\? \(y\/N\)"
         response: y
         wait_for: response[0] contains "File transfer is successful"

```
prompt: 

##### ACTUAL RESULTS

```

devops@svl-jabelk:~/Projects/wlc-code-upgrade/ansible_upgrade$ ansible-playbook upgrade_wlc.yml -i hosts -vvvv
ansible-playbook 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/devops/learning_ansible/ntc-ansible']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.2 (default, Sep 14 2017, 22:51:06) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/devops/Projects/wlc-code-upgrade/ansible_upgrade/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.5/dist-packages/ansible/plugins/callback/__init__.py

PLAYBOOK: upgrade_wlc.yml *************************************************************************************************************************************
1 plays in upgrade_wlc.yml

PLAY [Upgrade WLC Version Prep] *******************************************************************************************************************************
META: ran handlers

TASK [Prep Upgrade with transfer] *****************************************************************************************************************************
task path: /home/devops/Projects/wlc-code-upgrade/ansible_upgrade/upgrade_wlc.yml:18
<rtp5-itnlab-wl-wlc1> using connection plugin network_cli
<rtp5-itnlab-wl-wlc1> socket_path: /home/devops/.ansible/pc/6dec4dd3b9
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/network/aireos/aireos_command.py
<rtp5-itnlab-wl-wlc1> ESTABLISH LOCAL CONNECTION FOR USER: devops
<rtp5-itnlab-wl-wlc1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<rtp5-itnlab-wl-wlc1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/devops/.ansible/tmp/ansible-tmp-1510859342.262516-137282052033192 `" && echo ansible-tmp-1510859342.262516-137282052033192="` echo /home/devops/.ansible/tmp/ansible-tmp-1510859342.262516-137282052033192 `" ) && sleep 0'
<rtp5-itnlab-wl-wlc1> PUT /tmp/tmp93xe9rtb TO /home/devops/.ansible/tmp/ansible-tmp-1510859342.262516-137282052033192/aireos_command.py
<rtp5-itnlab-wl-wlc1> EXEC /bin/sh -c 'chmod u+x /home/devops/.ansible/tmp/ansible-tmp-1510859342.262516-137282052033192/ /home/devops/.ansible/tmp/ansible-tmp-1510859342.262516-137282052033192/aireos_command.py && sleep 0'
<rtp5-itnlab-wl-wlc1> EXEC /bin/sh -c '/usr/bin/python /home/devops/.ansible/tmp/ansible-tmp-1510859342.262516-137282052033192/aireos_command.py; rm -rf "/home/devops/.ansible/tmp/ansible-tmp-1510859342.262516-137282052033192/" > /dev/null 2>&1 && sleep 0'
fatal: [rtp5-itnlab-wl-wlc1]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "commands": [
                "transfer download filename AIR-CT5500-K9-8-0-152-0.aes",
                "transfer download path //",
                "transfer download datatype code",
                "transfer download mode tftp",
                "transfer download tftpmaxRetries 6",
                "transfer download tftpPktTimeout 6",
                "transfer download serverip 10.0.0.1",
                "transfer download start"
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": {
                "host": "rtp5-itnlab-wl-wlc1",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": 30,
                "username": "jabelk.web"
            },
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null,
            "wait_for": null
        }
    },
    "msg": "timeout trying to send command: b'transfer download start'",
    "rc": 1
}
    to retry, use: --limit @/home/devops/Projects/wlc-code-upgrade/ansible_upgrade/upgrade_wlc.retry

PLAY RECAP ****************************************************************************************************************************************************
rtp5-itnlab-wl-wlc1        : ok=0    changed=0    unreachable=0    failed=1   

devops@svl-jabelk:~/Projects/wlc-code-upgrade/ansible_upgrade$ 

```

**Comment by ansibot** [comment]
cc @sivel
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
@jabelk  This is supported today.  Here is how to properly write the task

```
aireos_command:
  provider: "{{ creds }}"
  commands:
    - command: transfer download start
      prompt:"Are you sure you want to start\? \(y\/N\)"
      response: y
   wait_for: response[0] contains "File transfer is successful"
```

**Comment by ansibot** [comment]
cc @jmighion @kedarX @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by privateip** [comment]
@jabelk can you confirm you were able to get this working?

needs_info

**Comment by jabelk** [comment]
thanks @privateip !

I was looking in the documentation and did not see those options, or the ability to do the prompt per a single command. 

Probably worth updating the examples to show an example with commands: command etc. 

I adapted below:
``` yaml
    - name: Prep Upgrade with transfer
      aireos_command:
        provider: "{{ creds }}"
        commands:
            - transfer download filename AIR-CT5500-K9-8-0-152-0.aes
            - transfer download path //
            - transfer download datatype code
            - transfer download mode tftp
            - transfer download tftpmaxRetries 6
            - transfer download tftpPktTimeout 6
            - transfer download serverip 171.70.168.154
            - command: transfer download start
              prompt: "Are you sure you want to start\\? \\(y\\/N\\)"
              answer: y
        wait_for: result[0] contains "File transfer is successful"
```

but I still don't get it to work because the "are you sure you want to start" requires a wait_for as well, but I don't see that in the module:

```
devops@svl-jabelk:~/Projects/wlc-code-upgrade/ansible_upgrade$ ansible-playbook upgrade_wlc.yml -i hosts -vvvv
ansible-playbook 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/devops/learning_ansible/ntc-ansible']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.2 (default, Sep 14 2017, 22:51:06) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/devops/Projects/wlc-code-upgrade/ansible_upgrade/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python3.5/dist-packages/ansible/plugins/callback/__init__.py

PLAYBOOK: upgrade_wlc.yml *************************************************************************************************************************************
1 plays in upgrade_wlc.yml

PLAY [Upgrade WLC Version Prep] *******************************************************************************************************************************
META: ran handlers

TASK [Prep Upgrade with transfer] *****************************************************************************************************************************
task path: /home/devops/Projects/wlc-code-upgrade/ansible_upgrade/upgrade_wlc.yml:18
<rtp5-itnlab-wl-wlc1> using connection plugin network_cli
<rtp5-itnlab-wl-wlc1> socket_path: /home/devops/.ansible/pc/6dec4dd3b9
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/network/aireos/aireos_command.py
<rtp5-itnlab-wl-wlc1> ESTABLISH LOCAL CONNECTION FOR USER: devops
<rtp5-itnlab-wl-wlc1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<rtp5-itnlab-wl-wlc1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/devops/.ansible/tmp/ansible-tmp-1511920712.0629315-70677946166710 `" && echo ansible-tmp-1511920712.0629315-70677946166710="` echo /home/devops/.ansible/tmp/ansible-tmp-1511920712.0629315-70677946166710 `" ) && sleep 0'
<rtp5-itnlab-wl-wlc1> PUT /tmp/tmp_9acxats TO /home/devops/.ansible/tmp/ansible-tmp-1511920712.0629315-70677946166710/aireos_command.py
<rtp5-itnlab-wl-wlc1> EXEC /bin/sh -c 'chmod u+x /home/devops/.ansible/tmp/ansible-tmp-1511920712.0629315-70677946166710/ /home/devops/.ansible/tmp/ansible-tmp-1511920712.0629315-70677946166710/aireos_command.py && sleep 0'
<rtp5-itnlab-wl-wlc1> EXEC /bin/sh -c '/usr/bin/python /home/devops/.ansible/tmp/ansible-tmp-1511920712.0629315-70677946166710/aireos_command.py; rm -rf "/home/devops/.ansible/tmp/ansible-tmp-1511920712.0629315-70677946166710/" > /dev/null 2>&1 && sleep 0'
fatal: [rtp5-itnlab-wl-wlc1]: FAILED! => {
    "changed": false,
    "failed": true,
    "failed_conditions": [
        "result[0] contains \"Are you sure you want to start\\\\? \\\\(y\\\\/N\\\\)\""
    ],
    "invocation": {
        "module_args": {
            "commands": [
                "transfer download filename AIR-CT5500-K9-8-0-152-0.aes",
                "transfer download path //",
                "transfer download datatype code",
                "transfer download mode tftp",
                "transfer download tftpmaxRetries 6",
                "transfer download tftpPktTimeout 6",
                "transfer download serverip 171.70.168.154"
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": {
                "host": "rtp5-itnlab-wl-wlc1",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": 30,
                "username": "jabelk.web"
            },
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null,
            "wait_for": [
                "result[0] contains \"Are you sure you want to start\\\\? \\\\(y\\\\/N\\\\)\""
            ]
        }
    },
    "msg": "One or more conditional statements have not be satisfied"
}
	to retry, use: --limit @/home/devops/Projects/wlc-code-upgrade/ansible_upgrade/upgrade_wlc.retry

PLAY RECAP ****************************************************************************************************************************************************
rtp5-itnlab-wl-wlc1        : ok=0    changed=0    unreachable=0    failed=1   


```
I think even tweaking the retry and interval timer would have the same result since there is a gap between the question and the prompt like so:
```
 >transfer download start

Mode............................................. TFTP
Data Type........................................ Code
TFTP Server IP................................... 171.70.168.154
TFTP Packet Timeout.............................. 6
TFTP Max Retries................................. 6
TFTP Path........................................ //
TFTP Filename.................................... AIR-CT5500-K9-8-0-152-0.aes

This may take some time.
Are you sure you want to start? (y/N) y
```

**Comment by walidshaari** [comment]
is  that for any platform_command? e.g. ios_command, junos_command, ..etc?

**Comment by jmighion** [comment]
@walidshaari I believe so.

@jabelk Can you separate out the task into 2? The first for everything but the `transfer download start` and the 2nd for just `transfer download start` with the extra prompt and answer options?

I don't see `transfer download start` listed on the commands to be ran, so I'm wondering if there's something causing it to get skipped or not sent. 

Also I'm not sure you need to double escape things in the string.

needs_info

**Comment by ansibot** [comment]
@jabelk This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jabelk This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@jabelk You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sweenig** [comment]
I can get ios_command to respond to a single prompt, but some commands require multiple prompt-responses, depending on the circumstances. The reload example is a perfect one as there are several circumstances that would cause the device to prompt the user about multiple things beyond the default [confirm] prompt.
For example:
- If there are configuration changes that haven't been written to NVRAM, it will prompt to save.
- If there is an onboard service engine (like the embedded wireless access point in the 1941) it will ask if you also want to reload that. 

Write memory is another example of a special circumstance that could cause an additional prompt beyond the confirmation and is the main reason that I can't use the when_changed parameter of the ios_config module. When saving the config, if the config in NVRAM was written by a different version of IOS, it will prompt to make sure you want to overwrite the file in NVRAM.  Since i'm using Ansible to assert that devices are on the right version of IOS, the playbook itself ends up changing the version of the device mid-playbook through a standard reload. However, if after reloading the playbook wants to save the config to NVRAM, I will always see the prompt asking me to overwrite the file created by a different version of the OS. 

Can there be a way of putting in a list of prompt/response dicts into the ios_command module? 
Something like this:

```
- ios_command:
    - command: write memory
      prompts:
        - prompt: confirm
          answer: yes
        - prompt: Are you really sure
          answer: yep
        - prompt: But it was created with a different version of the OS
          answer: I do not care
        - prompt: What do you want me to do
          answer: make it so
    - command: reload
      prompts:
        - prompt: confirm
          answer: yes
        - prompt: I do not thing you are sure
          answer: hell yes I am
        - prompt: yes/no
          answer: yes
        - prompt: Blood type
          answer: O positive
        - prompt: Mother maiden name
          answer: Jones
```
This type of extension would allow any number of prompts from the ios_commands being issued. Ideally, i'd expect the ios_command module to take any prompt and look for the best or first matching prompt and issue the response. If no matching prompt is found in my prompts dictionary, I'd expect the task to fail. If no prompts are given, or if fewer prompts are given than the length of the prompts dictionary, I'd expect the task to succeed and move on.

If this behavior is possible, please show me how. I've been pulling my hair out for weeks. If not, what would it take to get it built in?
