### ISSUE TITLE
file module does not set the right owner when creating nested directories

### ISSUE THREAD

**Issue by universal** [ansible/ansible#3300]
Hello,

When run with `sudo: yes` and creating a nested directory structure: The file module only sets correct owner/group for the last directory in the chain. An example of this can be seen in the simple playbook:

``` yaml

---
- hosts: some_host
  user: some_user
  sudo: yes
  tasks:
    - name: ensure Backup dir is present
      file: state=directory path=/home/git/Backup/models owner=git group=git recurse=yes
```

The /home/git/Backup/models directory is owned by git:git, /home/git/Backup is owned by root:root, where i would expect it to be also owned by git:git.

This happens on a current checkout from the devel branch. If you need any further information, i'm happy to supply whatever is needed.
