### ISSUE TITLE
Ansible bitbucket clone provisioning ssh error

### ISSUE THREAD

**Issue by TheSycamore** [ansible/ansible#33018]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
git module
##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/raf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
4.10.0-38-generic #42~16.04.1-Ubuntu

##### SUMMARY
When provisioning my vagrant box using Ansible, I get thrown a mysterious error when trying to clone my bitbucket private repo using ssh. The error states that the "Host key verification failed".

Yet if I vagrant ssh and then run the 'git clone' command, the private repo is successfully cloned. This indicates that the ssh forward agent is indeed working and the vagrant box can access my private key associated with the bitbucket repo.
##### STEPS TO REPRODUCE
**Vagrantfile**
```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.33.10"
  config.ssh.forward_agent = true

  # Only contains ansible dependencies
  config.vm.provision "shell",
    inline: "sudo apt-get install python-minimal -y"

  # Use ansible for all provisioning:
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end

end
```
**playbook.yml**

```
---

- hosts: all
  become: true

  tasks:
    - name: create /var/www/ directory
      file: dest=/var/www/ state=directory owner=www-data group=www-data mode=0755

    - name: Add the user 'ubuntu' to group 'www-data'
      user:
        name: ubuntu
        shell: /bin/bash
        groups: www-data
        append: yes

    - name: Clone bitbucket repo
      git:
        repo: git@bitbucket.org:gustavmahler/bitcointutorial.com.git
        dest: /var/www/poo
        version: master
        accept_hostkey: yes
```
##### ADDITIONAL INFO

- ssh-add -l on my machine does contain the associated bitbucket repo key.
- ssh-add -l inside the vagrant box does also contain the associated bitbucket repo key (through ssh-forwarding).
**Yet cloning works** if done manually inside the vagrant box **?**:

```
vagrant ssh
git clone git@bitbucket.org:myusername/myprivaterepo.com.git
Then type "yes" to allow the RSA fingerprint to be added to ~/.ssh/known_hosts (as its first connection with bitbucket)
```

##### EXPECTED RESULTS
Have the bitbucket private repo cloned to /var/www/poo

##### ACTUAL RESULTS
Error message from running 'vagrant provision':

```
TASK [common : Clone bitbucket repo] *******************************************

fatal: [default]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin '' /var/www/poo", "failed": true, "msg": "Cloning into '/var/www/poo'...\nWarning: Permanently added the RSA host key for IP address '104.192.143.3' to the list of known hosts.\r\nPermission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "Cloning into '/var/www/poo'...\nWarning: Permanently added the RSA host key for IP address '104.192.143.3' to the list of known hosts.\r\nPermission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stderr_lines": ["Cloning into '/var/www/poo'...", "Warning: Permanently added the RSA host key for IP address '104.192.143.3' to the list of known hosts.", "Permission denied (publickey).", "fatal: Could not read from remote repository.", "", "Please make sure you have the correct access rights", "and the repository exists."], "stdout": "", "stdout_lines": []}
```
##### Possible solution?

I have seen in the Ansible documentation that there is a [key_file](http://docs.ansible.com/ansible/latest/git_module.html#options): option. How would I reference the private key which is located outside the vagrant box and is passed in using ssh forwarding?

I do have multiple ssh keys for different entities inside my ~/.ssh/ Perhaps the git clone command when run by Ansible provisioning isn't selecting the correct key?

Any help is greatly appreciated and thanks for reading my issue.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/source_control/git.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/git.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by TheSycamore** [comment]
**Solution summary:**

- I changed the owner of the /var/www directory from 'www-data' to 'ubuntu' (the username I use to login via ssh).

- I also added "become: false" above the git task.

**Fixed playbook.yml file:**
```
---

- hosts: all
  become: true

  tasks:
    - name: create /var/www/ directory
      file: dest=/var/www/ state=directory owner=ubuntu group=www-data mode=0755

    - name: Add the user 'ubuntu' to group 'www-data'
      user:
        name: ubuntu
        shell: /bin/bash
        groups: www-data
        append: yes

    - name: Clone bitbucket repo
      become: false
      git:
        repo: git@bitbucket.org:gustavmahler/bitcointutorial.com.git
        dest: /var/www/poo
        version: master
        accept_hostkey: yes

```


**Solution Explained:**
As I wrote "become: true" at the top of the playbook.yml, I was attempting the 'git clone' as root user instead of 'ubuntu' user. ssh-add -l comes back empty when logged in as root, but has the expected keys when run by logging in as 'ubuntu'. So executing the ansible git task as the correct user sorted my issue.

For more of an understanding, try the following:
vagrant ssh　・　sudo -i　・　ssh-add -l　・　git clone git@bitbucket.org:myusername/myprivaterepo.com.git
