### ISSUE TITLE
elb_application_lb

### ISSUE THREAD

**Issue by bobobox** [ansible/ansible#33021]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
elb_application_lb

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/rpm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/rpm/sandbox/venv-ansible-2.4.0/lib/python2.7/site-packages/ansible
  executable location = /Users/rpm/sandbox/venv-ansible-2.4.0/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

```

##### SUMMARY
If an Application Load Balancer is created/maintained via Ansible, and the 'SslPolicy' on a listener is not specified (documentation says 'The default is the current predefined security policy.', indicating it can be omitted to use the default), the listener is created successfully along with the ALB, but on subsequent runs the task fails with a KeyError.

##### STEPS TO REPRODUCE
Create ALB using a play like the one shown below, then re-run the same play.

Example play:
```
- name: Maintain ALB
  elb_application_lb:
    name: some-alb
    state: present
    scheme: internet-facing
    region: us-east-1
    subnets: 
      - some-subnet-1
      - some-subnet-2
    security_groups: some-security-group
    listeners:
      - Protocol: HTTPS
        Port: 443
        DefaultActions:
          - Type: forward
            TargetGroupName: some-https-group
        Certificates:
          - CertificateArn: some-cert-arn


```

##### EXPECTED RESULTS
Play succeeds on first as well as subsequent runs.

##### ACTUAL RESULTS
Play fails after first run, due to KeyError when comparing SslPolicy.

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'SslPolicy'
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):
  File \"/var/folders/yy/wlg7s3c143qbvq9vsjjs_1w80000gn/T/ansible_DO7FDQ/ansible_module_elb_application_lb.py\", line 1016, in <module>
    main()
  File \"/var/folders/yy/wlg7s3c143qbvq9vsjjs_1w80000gn/T/ansible_DO7FDQ/ansible_module_elb_application_lb.py\", line 1011, in main
    create_or_update_elb(connection, connection_ec2, module)
  File \"/var/folders/yy/wlg7s3c143qbvq9vsjjs_1w80000gn/T/ansible_DO7FDQ/ansible_module_elb_application_lb.py\", line 906, in create_or_update_elb
    listener_changed = create_or_update_elb_listeners(connection, module, elb)
  File \"/var/folders/yy/wlg7s3c143qbvq9vsjjs_1w80000gn/T/ansible_DO7FDQ/ansible_module_elb_application_lb.py\", line 713, in create_or_update_elb_listeners
    listeners_to_add, listeners_to_modify, listeners_to_delete = compare_listeners(connection, module, current_listeners, deepcopy(listeners), purge_listeners)
  File \"/var/folders/yy/wlg7s3c143qbvq9vsjjs_1w80000gn/T/ansible_DO7FDQ/ansible_module_elb_application_lb.py\", line 636, in compare_listeners
    modified_listener = compare_listener(current_listener, new_listener)
  File \"/var/folders/yy/wlg7s3c143qbvq9vsjjs_1w80000gn/T/ansible_DO7FDQ/ansible_module_elb_application_lb.py\", line 538, in compare_listener
    if current_listener['SslPolicy'] != new_listener['SslPolicy']:
KeyError: 'SslPolicy'
", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

```
