### ISSUE TITLE
ec2_group module indicates boto3 not installed, even though it is installed

### ISSUE THREAD

**Issue by edesz** [ansible/ansible#33052]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`ec2_group`

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /home/username/ansible-proj/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/ansible-proj/.venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/username/ansible-proj/.venv/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### CONFIGURATION
```
DEFAULT_VAULT_PASSWORD_FILE(/home/username/ansible-proj/ansible.cfg) = /home/username/vault_pass.txt
(END)
```

##### OS / ENVIRONMENT
OS running Ansible from: Ubuntu 17.10

##### SUMMARY
I have the following basic Ansible `ec2_group` module-based task to create an AWS ec2 group. The `ec2_group` module has the requirement of `boto` and `boto3`, both of which I have installed. When I run the task below, it indicates that the module requires `boto3`. However, `boto3` is already installed.

##### STEPS TO REPRODUCE
Here is the task, based on the Ansible docs [examples](http://docs.ansible.com/ansible/latest/ec2_group_module.html#examples):

```
- hosts: localhost
  connection: local

  vars:
    region: "us-east-2"
    sg_name: "redhat-ec2"
    sg_desc: "Security group for Ansible RedHat"
    sg_rules:
      - proto: tcp
        from_port: 80
        to_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0

  tasks:
    - name: create security group for redhat ec2 instance(s)
      ec2_group:
      region: "{{ region }}"
      name: "{{ sg_name }}"
      description: "{{ sg_desc }}"
      rules: "{{ sg_rules|list }}"
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0
```

Install relevant packages with:

```
mkdir -p ~/ansible-proj
cd ansible-proj
virtualenv .
source .venv/bin/activate
pip install ansible
pip install awscli boto
pip install boto3
```

Run with `ansible-playbook -i /.hosts mytest.yml`. Here is `hosts`:

```
[localhost]
my_machine ansible_host=127.0.0.1 ansible_become_pass=<mypasswordhere>
```

##### EXPECTED RESULTS
The above task should create an AWS `ec2_group`

##### ACTUAL RESULTS
WITHOUT verbosity

When I run the above Ansible task, I get a message indicating `boto3` is needed - however `boto3` is already installed:

```
PLAY [Initial configuration of AWS CLI on Ansible controller] ****************************

TASK [Gathering Facts] *******************************************************************
ok: [my_machine]

TASK [ansible-test : create security group] ***********
fatal: [my_machine]: FAILED! => {"changed": false, "failed": true, "msg": "boto3 required for this module"}
```

WITH verbosity -vvvv

```
fatal: [my_machine]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "description": "Security group for Ansible RedHat", 
            "ec2_url": null, 
            "group_id": null, 
            "name": "redhat-ec2", 
            "profile": null, 
            "purge_rules": true, 
            "purge_rules_egress": true, 
            "purge_tags": true, 
            "region": "us-east-2", 
            "rules": [
                {
                    "cidr_ip": "0.0.0.0/0", 
                    "from_port": 80, 
                    "proto": "tcp", 
                    "to_port": 80
                }, 
                {
                    "cidr_ip": "0.0.0.0/0", 
                    "from_port": 22, 
                    "proto": "tcp", 
                    "to_port": 22
                }
            ], 
            "rules_egress": [
                {
                    "cidr_ip": "0.0.0.0/0", 
                    "proto": "all"
                }
            ], 
            "security_token": null, 
            "state": "present", 
            "tags": null, 
            "validate_certs": true, 
            "vpc_id": null
        }
    }, 
    "msg": "boto3 required for this module"
}
```

##### OTHER

Here is my `pip freeze` output:

```
ansible==2.4.1.0
.
.
.
boto==2.48.0
boto3==1.4.7
botocore==1.7.47
.
.
.
paramiko==2.4.0
.
.
six==1.11.0
```

The main packages I have installed through `pip` are:

```
ansible
pywinrm
boto
awscli
boto3
sshpass
```
