### ISSUE TITLE
proxmox_template doesn't work because of utils.path_dwim()

### ISSUE THREAD

**Issue by jocelynj** [ansible/ansible#33064]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module proxmox_template

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /home/jocelyn/osm/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### CONFIGURATION
Nothing relevant

##### OS / ENVIRONMENT
Debian Stretch

##### SUMMARY
When launching proxmox_template, I'm getting a failure, because module is using `utils.path_dwin()`, which is no longer present in ansible. I've tried to replace with `module._loader.path_dwim_relative()` as recommended by porting_guide_2.0.rst, but _loader is not present in module.

##### STEPS TO REPRODUCE
yaml extract:
```
- name: upload VM template to cluster
  local_action:
    module: proxmox_template
    timeout: 60
    api_host: "{{ proxmox_var.host }}"
    api_user: "ansible@pve"
    node: "{{ vm_host.split('.')[0] }}"
```

##### EXPECTED RESULTS
Module shouldn't trigger a python error.

##### ACTUAL RESULTS
Launching ansible-playbook -vvv, after fixing exception that is triggered by proxmox_template.py because variable template is not present:
```
TASK [common : upload VM template to cluster] *****************************************
task path: /home/jocelyn/osm/ansible/roles/common/tasks/main.yml:9
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/misc/proxmox_template.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: jocelyn
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [osm148.openstreetmap.fr -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
...
        }
    }, 
    "msg": "uploading of template 'xxx' failed with exception: 'module' object has no attribute 'path_dwim'"
}
```

Do you have a suggestion on how to replace the path_dwim() call ?
