### ISSUE TITLE
Chocolatey occasional issue

### ISSUE THREAD

**Issue by lawrence-c** [ansible/ansible#33087]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /Users/Projects/dev_ansible/ansible_playbook/ansible.cfg
  configured module search path = [u'/Users/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/Projects/py_virtualenvs/venv_ansible_pyvmomi/lib/python2.7/site-packages/ansible
  executable location = /Users/Projects/py_virtualenvs/venv_ansible_pyvmomi/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```
##### OS / ENVIRONMENT
Environment:

- from: MacOSX 10.11
- to: Windows 7 (with SP1)

##### SUMMARY

I am using Packer with Ansible encapsulated within the provision step, to call the `playbook_file`, and have the following `ansible_env_vars`:
```
"ANSIBLE_HOST_KEY_CHECKING=False", "ANSIBLE_SSH_ARGS='-o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30m'"
```

I use `win_chocolatey` to install a list of items, as follows:
```
- name: win | Install chocolatey components
  win_chocolatey:
    name: "{{ item.package_name }}"
    install_args: "{{ item.install_args | default('') }}"
    allow_empty_checksums: yes
  with_items: "{{ chocolately_installed_packages }}"
  become_method: runas
```
```
chocolately_installed_packages:
  - package_name: nsis
  - package_name: git
  - package_name: doxygen.install
```

And quite a lot of times, sometimes randomly, the installation of the item fails with some of the following errors: 
```
failed: [default] (item={u'package_name': u'nsis'}) => {"changed": false, "failed": true, "item": {"package_name": "nsis"}, "msg": "The term 'win_chocolatey.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}
```
or 
```
failed: [default] (item={u'package_name': u'git'}) => {"changed": false, "failed": true, "item": {"package_name": "git"}, "msg": "The term 'C:\\Users\\ultrahaptics\\AppData\\Local\\Temp\\ansible-tmp-1511175420.49-147459407680039\\win_chocolatey.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again."}
```
or

```
failed: [default] (item={u'package_name': u'doxygen.install'}) => {"changed": false, "failed": true, "item": {"package_name": "doxygen.install"}, "module_stderr": "#< CLIXML\r\n\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"1\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">2</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

But then running the playbook again, it succeeds (sometimes...)

I'm not sure if this is a configuration I'm missing, which generates these errors?
