### ISSUE TITLE
asa_command replaces password string in output with asterisks

### ISSUE THREAD

**Issue by pehruby** [ansible/ansible#33097]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

asa_command

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /vagrant/ansible-cpoj/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/vagrant/ansible-cpoj/ansible.cfg) = [u'/vagrant/ansible-cpoj/hosts']
DEFAULT_TIMEOUT(/vagrant/ansible-cpoj/ansible.cfg) = 5
HOST_KEY_CHECKING(/vagrant/ansible-cpoj/ansible.cfg) = False

##### OS / ENVIRONMENT

ubuntu/xenial

##### SUMMARY

asa_command replaces password string in output with asterisks

Although it's clear to me that strong enable password shouldn't be the same as normal configuration commands, I'd  like to obtain "show running" output from the asa_command module without any modifications.

##### STEPS TO REPRODUCE

```yaml
 - name: Grab configuration
    asa_command:
      provider:
        auth_pass: "{{ ansible_ssh_pass }}"    # auth_pass is set to "Admin"
        authorize: yes
      commands: show running
    no_log: false
    register: cfg

  - debug: 
      var: cfg

```

##### EXPECTED RESULTS

```
...
interface Management0/0\n description Admin\n duplex full\n management-only\n nameif mgmt\n security-level 100\n ip address 10.105.139.148 255.255.255.224 \n
...
```
##### ACTUAL RESULTS

```
...
interface Management0/0\n description ********\n duplex full\n management-only\n nameif mgmt\n security-level 100\n ip address 10.105.139.148 255.255.255.224 \n
...

```
