### ISSUE TITLE
Unable to delete default created security group rules in OpenStack

### ISSUE THREAD

**Issue by pritho** [ansible/ansible#33096]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- os_security_group_rule
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /home/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```
##### OS / ENVIRONMENT
CentOS 7.4

##### SUMMARY
Cannot delete auto-created security group rules on OpenStack

##### STEPS TO REPRODUCE
When creating a new security group with os_security_group:
```
- os_security_group:
    state: present
    name: foo
```
--> OpenStack creates a default set of rules allowing any egress traffic:
```
(neutron) security-group-list
+--------------------------------------+--------+----------------------+
| id                                   | name   | security_group_rules |
+--------------------------------------+--------+----------------------+
| 40c9aad8-1ddf-4f62-90d6-34d9bcca636d | test1  | egress, IPv4         |
|                                      |        | egress, IPv6         |

```
--> this means any new instance can communicate to the outside world on any port with any protocol

Now I want to delete these default rules in my ansible playbook, i.e.:
```
- name: Remove Rules from custom security groups
  os_security_group_rule:
    state: absent
    security_group: foo
    direction: egress
    remote_ip_prefix: 0.0.0.0/0
```
The rule still persists. Also using port_min, port_max or protocol with value "any" does not work as the module expects an integer. 

```yaml

```
