### ISSUE TITLE
azure_rm_functionapp module doesn't work

### ISSUE THREAD

**Issue by ZhijunZhao** [ansible/ansible#33120]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_functionapp

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/zhijzhao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

No change at all.

##### OS / ENVIRONMENT

macOS 10.13.1

##### SUMMARY

Exceptions as below when creating azure function.

TASK [create basic function app] ************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'AzureRMFunctionApp' object has no attribute 'base_url'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/0r/_5p333ds2q30tf1pcq6p_wc40000gn/T/ansible_Aun21J/ansible_module_azure_rm_functionapp.py\", line 297, in <module>\n    main()\n  File \"/var/folders/0r/_5p333ds2q30tf1pcq6p_wc40000gn/T/ansible_Aun21J/ansible_module_azure_rm_functionapp.py\", line 294, in main\n    AzureRMFunctionApp()\n  File \"/var/folders/0r/_5p333ds2q30tf1pcq6p_wc40000gn/T/ansible_Aun21J/ansible_module_azure_rm_functionapp.py\", line 156, in __init__\n    required_if=required_if\n  File \"/var/folders/0r/_5p333ds2q30tf1pcq6p_wc40000gn/T/ansible_Aun21J/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 303, in __init__\n  File \"/var/folders/0r/_5p333ds2q30tf1pcq6p_wc40000gn/T/ansible_Aun21J/ansible_module_azure_rm_functionapp.py\", line 174, in exec_module\n    function_app = self.web_client.web_apps.get(\n  File \"/var/folders/0r/_5p333ds2q30tf1pcq6p_wc40000gn/T/ansible_Aun21J/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 783, in web_client\nAttributeError: 'AzureRMFunctionApp' object has no attribute 'base_url'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
  - name: create storage account for function apps
    azure_rm_storageaccount:
      resource_group: zhijzhao
      name: azfunccistor4
      account_type: Standard_LRS

  - name: create basic function app
    azure_rm_functionapp:
      resource_group: zhijzhao
      name: azfuncci
      storage_account: azfunccistor4

```

##### ACTUAL RESULTS

```

```
