### ISSUE TITLE
no_log for specific variables/parameters

### ISSUE THREAD

**Issue by kustodian** [ansible/ansible#33126]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Core

##### SUMMARY
`no_log` is great if you want to hide the output of some task, which is important especially if the task is working with secrets. The problem with `no_log` is that you cannot see what is going on with the task, which is especially important if it fails.

It would be really good if we could somehow mark specific variables not be logged, that way rest of the module would still be logged. To be honest I'm not sure if this is even possible, but my current idea is to have a filter `nolog` which does this. Here is an example:

```yml
---
- hosts: localhost
  vars:
    config:
      u1:
        user: user1
        pass: '{{ "F93EAQm" | nolog }}'
      u2:
        user: user2
        pass: '{{ "d4h6N31" | nolog }}'

  tasks:
    - name: some task
      ...
      with_dict: '{{ config }}''
```
In this example the value of any variable with the `nolog` filter set will not be displayed in the task output.

This is just an idea, which probably cannot work because of how filters work, but maybe there is a better solution to this problem. Any ideas?
