### ISSUE TITLE
vmware_guest - Cluster option stopped working 

### ISSUE THREAD

**Issue by coltsixshooter** [ansible/ansible#33156]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /home/jzimmett/.ansible.cfg
  configured module search path = [u'/home/jzimmett/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/home/xxxx/workspace/devops/platform-roles
HOST_KEY_CHECKING(/home/xxxx/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/xxxx/.ansible.cfg) = False

##### OS / ENVIRONMENT
Red Hat 7.4

##### SUMMARY
Same issue as #30879. vmware_guest is not handling the "cluster" option correctly and fails that it can not find the data store.

I have modified the vmware_guest.py to work properly and will do a pull request.

##### STEPS TO REPRODUCE

```yaml
- name: "Create DHCP VM {{ vm_name }}"
  vmware_guest:
    hostname: "{{ vc_hostname }}"
    username: "{{ vc_user }}"
    password: "{{ vc_pass }}"
    cluster: "{{ vc_cluster }}"
    datacenter: "{{ vc_datacenter }}"
    template: "{{ vm_template }}"
    name: "{{ vm_name }}"
    networks:
      - vlan: "{{ vm_vlan }}"
        type: "dhcp"
    annotation: "{{ vm_notes }}"
    folder: "{{ vc_folder }}"
    disk:
      - size_gb: 30
        type: thin
        datastore: "{{ vm_datastore }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpu }}"
    customization:
      hostname: "{{ vm_name }}"
      domain: "{{ vm_domain }}"
    customvalues:
      - { key: "Created By", value: "Ansible" }
      - { key: "Department", value: "Engineering" }
      - { key: "Requested By", value: "Jeff Yates" }
      - { key: "Date Created", value: "{{ ansible_date_time.date }}" }
    state: poweredon
    validate_certs: no
    force: yes
    wait_for_ip_address: "{{ vm_wait_for | default('yes') }}"
  register: newvm

```

##### EXPECTED RESULTS

Handle the Cluster option properly

##### ACTUAL RESULTS

```
Unable to access the virtual machine configuration: Unable to access file [Tintri-UAT-RPM]

```
