### ISSUE TITLE
hyphen in dictionary key breaks json_query

### ISSUE THREAD

**Issue by narankhetani** [ansible/ansible#33163]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
json_query

##### ANSIBLE VERSION

```
 ansible --version
ansible 2.4.2.0
  config file = /Users/n.khetani/.ansible.cfg
  configured module search path = [u'/Users/n.khetani/projects/sn/cns-ansible-roles']
  ansible python module location = /Users/n.khetani/ansible-env/lib/python2.7/site-packages/ansible-2.4.2.0-py2.7.egg/ansible
  executable location = /Users/n.khetani/ansible-env/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### SUMMARY

When running a json_query to a dictionary with keys that contain "-" hyphen/dash it seems to break.

##### STEPS TO REPRODUCE

```yaml
- name: Audit Juniper
  hosts: cor-001a.sn.com
  gather_facts: no
  connection: local

  vars:
    json_blob: "{{ lookup('file', '{{ playbook_dir }}/{{ inventory_hostname }}.json.bak') | from_json }}"
  - debug: msg="{{ item }}"
    with_items: "{{ json_blob | json_query(query) }}"
    vars:
      query: 'msg.rpc_reply["interface-information"]'
```

Json Blob to test with if needed:
https://gist.github.com/narankhetani/d462a280b0cf5e32d3e82ccd01786680

##### EXPECTED RESULTS

the query to run
##### ACTUAL RESULTS

```
TASK [cns.tasks/audits/interfaces : debug] ***********************************************************************************************************************************************************************************************************************************
fatal: [cor-001a.sn.com]: FAILED! => {"msg": "JMESPathError in json_query filter plugin:\nExpecting: star, got: quoted_identifier: Parse error at column 14, token \"interface-information\" (QUOTED_IDENTIFIER), for expression:\n\"msg.rpc_reply[\"interface-information\"]\"\n               ^"}
```

I also ran this with the latest devel version but still the same error.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/filter/json_query.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/filter/json_query.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@narankhetani Thanks for reporting this issue. I noticed that the query is not correct. `-` is not valid in unquoted identifiers as it is used for negative numbers. You need to quote the query before passing. JMESPath Identifiers' doc [here](http://jmespath.org/specification.html#identifiers).

For posterity, 

```yaml
- name: Audit Juniper
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    json_blob: "{{ lookup('file', '{{ playbook_dir }}/localhost.json') | from_json }}"
    query: 'msg.rpc_reply."interface-information"'
  tasks:
    - debug: msg="{{ item }}"
      with_items: "{{ json_blob | json_query(query) }}"
```

localhost.json

```
{
  "msg": {
    "rpc_reply": {
      "interface-information": [
        {
          "physical-interface": [
            {
              "active-alarms": [
                {
                  "interface-alarms": [
                    {
                      "ethernet-alarm-link-down": [
                        {
                          "data": null
                        }
                      ]
                    }
                  ]
                }
              ]
            },
            {
              "admin-status": [
                {
                  "attributes": {
                    "junos:format": "Enabled"
                  },
                  "data": "up"
                }
              ]
            }
          ]
        }
      ]
    }
  }
}
```

And playbook run

```
ansible-playbook json_query.yaml

PLAY [Audit Juniper] ***********************************************************************************************************

TASK [debug] *******************************************************************************************************************
ok: [localhost] => (item={u'physical-interface': [{u'active-alarms': [{u'interface-alarms': [{u'ethernet-alarm-link-down': [{u'data': None}]}]}]}, {u'admin-status': [{u'attributes': {u'junos:format': u'Enabled'}, u'data': u'up'}]}]}) => {
    "item": {
        "physical-interface": [
            {
                "active-alarms": [
                    {
                        "interface-alarms": [
                            {
                                "ethernet-alarm-link-down": [
                                    {
                                        "data": null
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "admin-status": [
                    {
                        "attributes": {
                            "junos:format": "Enabled"
                        },
                        "data": "up"
                    }
                ]
            }
        ]
    },
    "msg": {
        "physical-interface": [
            {
                "active-alarms": [
                    {
                        "interface-alarms": [
                            {
                                "ethernet-alarm-link-down": [
                                    {
                                        "data": null
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "admin-status": [
                    {
                        "attributes": {
                            "junos:format": "Enabled"
                        },
                        "data": "up"
                    }
                ]
            }
        ]
    }
}

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
