### ISSUE TITLE
Gem module does not work with version constraints / specifiers

### ISSUE THREAD

**Issue by soylent** [ansible/ansible#33179]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- Gem

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /ads_scm/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Jun 29 2016, 08:57:23) [GCC 5.3.0]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

Gem module does not remove gems if a version constraint is specified

Probably, this line should be changed:
https://github.com/ansible/ansible/blob/v2.4.1.0-1/lib/ansible/modules/packaging/language/gem.py#L161

##### STEPS TO REPRODUCE

```yaml
- name: remove unused gem versions
  gem:
    name: foobar
    version: "< 0.5.0"
    state: absent
```

##### EXPECTED RESULTS
Remove all foobar gem versions < 0.5.0

##### ACTUAL RESULTS
No gems were removed
