### ISSUE TITLE
docker_image unauthorized: authentication

### ISSUE THREAD

**Issue by typ431127** [ansible/ansible#33175]
##### SUMMARY
I'm using the docker_image module, there is already docker_login in my yaml file and the execution is successful but the pull images show error
Login to the registry is successful but pull image does not have permission, I hope to solve this problem

##### ANSIBLE VERSION
```
Docker version 17.09.0-ce, build afdb6d4
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### ISSUE TYPE
 - Bug Report

##### STEPS TO REPRODUCE

```
---
- hosts: typ2
  remote_user: root
  vars_files:
      - /data/ansible-playbooks/vars/registry.yaml

  tasks:
  - name: Log into registry.tangsheng.com
    docker_login:
      registry: "{{ registry_url }}"
      username: "{{ registry_user }}"
      password: " {{ registry_pass }}"
      email: " {{ registry_mail }}"

  - name: pull an image
    docker_image:
      name: registry.tangsheng.com/typ/nginx
      tag: 1.5

```

##### ACTUAL RESULTS

error: 

```
[root@node71 ansible-playbooks]# ansible-playbook pull.yaml 

PLAY [typ2] *************************************************************************************************

TASK [Log into registry.tangsheng.com] **********************************************************************
ok: [192.168.31.223]
ok: [192.168.31.221]
ok: [192.168.31.222]

TASK [pull an image] ****************************************************************************************
fatal: [192.168.31.221]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image registry.tangsheng.com/typ/nginx:1.5 - 'module' object has no attribute 'get_config_header'"}
fatal: [192.168.31.223]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image registry.tangsheng.com/typ/nginx:1.5 - 500 Server Error: Internal Server Error (\"unauthorized: authentication required\")"}
fatal: [192.168.31.222]: FAILED! => {"changed": false, "failed": true, "msg": "Error pulling image registry.tangsheng.com/typ/nginx:1.5 - 500 Server Error: Internal Server Error (\"unauthorized: authentication required\")"}
	to retry, use: --limit @/data/ansible-playbooks/pull.retry

PLAY RECAP **************************************************************************************************
192.168.31.221             : ok=1    changed=0    unreachable=0    failed=1   
192.168.31.222             : ok=1    changed=0    unreachable=0    failed=1   
192.168.31.223             : ok=1    changed=0    unreachable=0    failed=1 
```
