### ISSUE TITLE
include_role in a loop: huge memory usage and cpu consumption

### ISSUE THREAD

**Issue by alonsocamaro** [ansible/ansible#33183]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

ansible version included in ansible-tower 3.1.5:

```
(ansible)[root@rhel74-1-ucamaro del-customer-services]# ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION
```
(ansible)[root@rhel74-1-ucamaro del-customer-services]# ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
```

##### OS / ENVIRONMENT

RHEL 7.4

##### SUMMARY

I have a group called, bigip-cluster with 8 hosts. And the following playbook

```
---
- hosts: bigip-cluster
  gather_facts: false
  max_fail_percentage: 0
[...]
  roles:
    - setfacts
    - clean-bigip-auth-tokens
    - del-all-customers-services
    - del-all-customers-networks
    - traffic-groups
    - common-networks
    - ha-config
    - base-network-config
    - sync-to-group
```

When the execution reaches any of the del-all-customer-* roles the memory usage is ridiculously high:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
24130 awx       20   0 2662720 2.172g   6252 R 100.3 18.8   2:48.76 ansible-playboo
24531 awx       20   0 2661360 2.167g   1628 S  49.8 18.7   0:16.53 ansible-playboo
24533 awx       20   0 2661360 2.167g   1592 S  46.5 18.7   0:04.34 ansible-playboo
```

not to mention the slowness... so what does this del-all-customer-services role? Just this:

```
---

- name: "Delete customer services"
  with_dict: "{{ ansible_local.customer_vxlans.vxlans }}"
  loop_control:
    loop_var: outer_item
  include_role: 
    name: del-customer-services
  vars:
    vxlanid: "{{ outer_item.key }}"
    bigip_cluster_member_leaving: True
  tags:
    - del
```

with a dictionary which contains **58** entries. In my box it takes 5 minutes between displaying the task of this role and the first time the del-customer-services role is included. The execution of the role del-customer-services role is seconds.

##### STEPS TO REPRODUCE

The above playbooks reproduce the error deterministally.

##### EXPECTED RESULTS

I would not expect this memory utilization / high cpu utilization /slowness.

##### ACTUAL RESULTS

See above. I don't want to be over-verbose initially. Please let me know if you need anything else.

Many thanks
