### ISSUE TITLE
Add possibility to set up several ips for hostname in module ipa_dnsrecord

### ISSUE THREAD

**Issue by xtoznaxto** [ansible/ansible#33193]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ipa_dnsrecord

##### ANSIBLE VERSION

```
v.2.4.1
```

##### OS / ENVIRONMENT

centOS 7
##### SUMMARY

Please, add possibility to set up several ip-addresses (record_value) for one hostname (record_name) in module ipa_dnsrecord. For now if I will define several record_values - it will replace old value with new one. It is logical and sometimes really needed to have a possibility to define two or more ip-addresses for one hostname and it is possible to do so in free_ipa web-interface.
Thanks in advance!
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/identity/ipa/ipa_dnsrecord.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/identity/ipa/ipa_dnsrecord.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Nosmoht @akasurde
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @fxfitz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fxfitz** [comment]
Are you thinking a format something like:

```
- ipa_dnsrecord:
    ipa_host: spider.example.com
    ipa_pass: Passw0rd!
    state: present
    zone_name: example.com
    record_name: vm-001
    record_type: 'AAAA'
    record_value:
     - '::1'
     - '2007::02'
```

**Comment by worsco** [comment]
Instead of having multiple items in "record_value:", what about having another state in addition to "present" and "absent".  Call the state "append".  This will allow you to "append" additional entries to the "record_value".  If the record does not exist, then "append" it and do not remove any of the other records. If the "record_value" already exists, do not add it again.  The following example could add three SRV entries for the same "_etcd-server-ssl._tcp" key.  For example:

`---
- hosts: localhost

  vars:
    zone_fwd: "ocp4-cluster1.example.local."
    
    dns_srv_records:
      "0 10 2380 etcd-0": _etcd-server-ssl._tcp
      "0 10 2380 etcd-1": _etcd-server-ssl._tcp
      "0 10 2380 etcd-2": _etcd-server-ssl._tcp

  tasks:

  - name: Create SRV records
    ipa_dnsrecord:
      ipa_host: ipa.example.local
      ipa_user: admin
      ipa_timeout: 30
      validate_certs: false
      zone_name: "{{ zone_fwd }}"
      record_value: "{{ item.key }}.{{ zone_fwd }}"
      record_type: 'SRV'
      record_name: "{{ item.value }}"
      state: append
    loop: "{{ lookup('dict', dns_srv_records) }}"
`

**Comment by worsco** [comment]
Another example, instead of a `state` of `append`, an attribute set to true:

```
- name: Create SRV records
    ipa_dnsrecord:
      ipa_host: ipa.example.local
      ipa_user: admin
      ipa_timeout: 30
      validate_certs: false
      zone_name: "{{ zone_fwd }}"
      record_value: "{{ item.key }}.{{ zone_fwd }}"
      record_type: 'SRV'
      record_name: "{{ item.value }}"
      append: yes
      state: present
    loop: "{{ lookup('dict', dns_srv_records) }}"
```
