### ISSUE TITLE
eos_config - output in '--- before' and '+++ after' diff sections round the wrong way

### ISSUE THREAD

**Issue by halberom** [ansible/ansible#33190]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION
```
ansible-playbook 2.4.0.0
  config file = 
  configured module search path = [u'/Users/lynchg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/lynchg/.virtualenvs/a2x/lib/python2.7/site-packages/ansible
  executable location = /Users/lynchg/.virtualenvs/a2x/bin/ansible-playbook
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
NA

##### OS / ENVIRONMENT
NA

##### SUMMARY
When using `eos_config`, `diff_against`, and `--diff` the content of `--- before` and `+++ after` are around the wrong way.

##### STEPS TO REPRODUCE
Create a play
```
--- 
- hosts: switches
  connection: local
  gather_facts: False
  tasks:
    - template:
        src: vlan.j2
        dest: /tmp/vlan

    - eos_config:
         provider: "{{ connection }}"
         diff_against: intended
         intended_config: /tmp/vlan
```

##### EXPECTED RESULTS
The intended config is in the diff section `+++ after`, the running-config is in `--- before`.

##### ACTUAL RESULTS
The intended config is in the diff section `--- before`, the running-config is in `+++ after`.

Think the issue exists in the lines https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/eos/eos_config.py#L457-L462, either the order of the diff should change based on the diff_against logic _or_ the params in the diff should be handle in diff orders.  At present one approach is used for all cases.
