### ISSUE TITLE
nxos_vrf_interface module error: "show run | section interface.Ethernet"

### ISSUE THREAD

**Issue by victorock** [ansible/ansible#33227]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module: nxos_vrf_interface

##### ANSIBLE VERSION
```
ansible-playbook 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT
NXOS: 7.0(3)I7(1)
ENV: Tower/AWX

##### SUMMARY
unable to configure vrf on interfaces

##### STEPS TO REPRODUCE
```yaml
- name: "Ensure state as layer3 on underlay links"
  nxos_interface:
    interface: "ethernet 1/2"
    mode: layer3
    description: "Underlay by Ansible"
    admin_state: "up"
    state: "present"

- name: "Ensure state of vrf on underlay links"
  nxos_vrf_interface:
    interface: "ethernet 1/2"
    state: "present"
    vrf: "control"
```
##### EXPECTED RESULTS

Have interface state as:

```
interface ethernet 1/2
  vrf member control
  no switchport
  no shut
```

##### ACTUAL RESULTS

Failed because of validation of running-configuration adopting "| section":
**show run | section interface.Ethernet 1/2**

```
"show run | section interface.Ethernet 1/2\\r\\r\\n
^\\r\\n% Invalid command at '^' marker.\\r\\n\\rspine01# \", 
\"nxos_vrf_interface_underlay_link\": \"ethernet 1/2\"}\
```
##### POSSIBLE RESOLUTION
Use the command below to get the interface running-configuration in NXOS.

```
show run interface ethernet X/Y
```
