### ISSUE TITLE
Specified --limit does not match any hosts

### ISSUE THREAD

**Issue by lawrence-c** [ansible/ansible#33234]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Ansible core/playbook

##### ANSIBLE VERSION
```
ansible 2.4.1.0
```

##### OS / ENVIRONMENT
Running Ansible on Windows locally

##### SUMMARY
Successfully got Ansible installed on Windows (I think), and trying to run some playbooks locally on the Windows machine - however keep getting the error saying `Specified --limit does not match any hosts`

##### STEPS TO REPRODUCE
`helloworld.yml`

```yaml
- hosts: host1
  tasks:
    - shell: echo "hello world"

- hosts: host2
  tasks:
    - shell: echo "hello world 2"
```

```
ansible-playbook -i "localhost," -c local --limit host1 helloworld.yml
```

##### EXPECTED RESULTS
The task for host1 (and only host1) to succeed

##### ACTUAL RESULTS
```
[WARNING]: Could not match supplied host pattern, ignoring: host1

Error! Specified --limit does not match any hosts
```
