### ISSUE TITLE
nxos_interface_ospf : Passive interface is not supported on loopbacks

### ISSUE THREAD

**Issue by victorock** [ansible/ansible#33245]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_interface_ospf

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 40
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 120

##### OS / ENVIRONMENT

NXOS: 7.0(3)I7(1)

##### SUMMARY

Loopback interface cannot perform OSPF layer2 peering, as they are logical local interfaces.
Therefore, they don't support the configuration "ip ospf passive-interface".

##### STEPS TO REPRODUCE

NOTE: The interface does exists.

```yaml
- name: "Ensure state of ospf on control and exchange interfaces"
  nxos_interface_ospf:
    interface: "loopback0"
    ospf: "UNDERLAY_0"
    area: "0"
    cost: "110"
    state: "present"
```

##### EXPECTED RESULTS

Ignore this "passive" option if interface is loopback.

##### ACTUAL RESULTS

```
Task fails, with the error message:

"ip ospf passive-interface\r\r\n                            ^\r\n% Invalid command at '^' marker.\r\n\rleaf02(config-if)# "

```
