### ISSUE TITLE
Environment keyword does not support 'false' or empty values

### ISSUE THREAD

**Issue by geoffmunn** [ansible/ansible#33240]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

get_url, yum, pip, etc

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The environment keyword supports proxy configuration details, like this:
```yml
environment: "{{ proxy_env }}"
```
where `{{ proxy_env }}` has been previously set, like this:
```yml
  proxy_env: 
    http_proxy: "http://{{ proxy_username }}:{{ proxy_password }}@proxy:80"
    https_proxy: "http://{{ proxy_username }}:{{ proxy_password }}@proxy:80"
```

However, if you are running the playbook across two environments; one where there is a proxy, and one where there is not, then the environment keyword may not be required in some instances.

In these cases, it would be great if the environment value would accept 'false', or empty quotes as a valid value, and ignore it.
Currently it returns this message:
```bash
[WARNING]: could not parse environment value, skipping: [u'{{ proxy_env }}']
```

##### STEPS TO REPRODUCE

```yaml
---

# Set up the ansible-host machine with support for windows connectivity
# This should be run on the ansible-host machine (localhost)

- hosts: localhost
  become: true
  
  vars:
    proxy_env: false
      
  tasks: 

    # First of all, we need to install Pip
    - name: 1/2 Install Pip
      become: true
      yum: 
        name: python-pip
        state: latest
     
    # Now install pyWinRM so we can talk to the Windows server   
    - name: 2/2 Install pyWinRm
      environment: "{{ proxy_env }}"
      become: true
      pip: 
        name: pywinrm
        state: latest

...
```

##### EXPECTED RESULTS

To not see the WARNING message about the proxy value

##### ACTUAL RESULTS

The playbook returns pink warning messages about the proxy value

```
PLAY [localhost] **************************************************************************************************************

TASK [1/2 Install Pip] ********************************************************************************************************
Thursday 23 November 2017  21:00:31 +0000 (0:00:00.069)       0:00:00.069 *****
ok: [localhost]

TASK [2/2 Install pyWinRm] ****************************************************************************************************
Thursday 23 November 2017  21:00:39 +0000 (0:00:07.786)       0:00:07.855 *****
 [WARNING]: could not parse environment value, skipping: [u'{{ proxy_env }}']

ok: [localhost]

PLAY RECAP ********************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

Thursday 23 November 2017  21:00:41 +0000 (0:00:01.815)       0:00:09.670 *****
===============================================================================
1/2 Install Pip -------------------------------------------------------------------------------------------------------- 7.79s
2/2 Install pyWinRm ---------------------------------------------------------------------------------------------------- 1.82s
```
