### ISSUE TITLE
Redshift return values (url, public_ip_address, and port) are missing

### ISSUE THREAD

**Issue by bchamby** [ansible/ansible#33279]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

redshift

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/brad.chamberlain/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

<no output / empty>

##### OS / ENVIRONMENT

Running from macOS High Sierra 10.13.1

Running against AWS Redshift

##### SUMMARY

The redshift module creates the Redshift instance as expected, but the "cluster" dict return value is missing the "url", "public_ip_address", and "port" key/value pairs.

##### STEPS TO REPRODUCE

Running this in a role (with or without the "wait" parameters) will create the Redshift instance, but the aforementioned key/value pairs are missing from the "cluster" dict return value.

```yaml
- name: redshift
  redshift:
    command: create
    wait: yes
    wait_timeout: 600
    region: "{{ redshift_region }}"
    node_type: "{{ redshift_node_type }}"
    identifier: "{{ redshift_name }}"
    availability_zone: "{{ redshift_az }}"
    cluster_type: single-node
    db_name: "{{ redshift_db_name }}"
    username: "{{ redshift_username }}"
    password: "{{ redshift_password }}"
    publicly_accessible: yes
    vpc_security_group_ids: "{{ redshift_sg_id }}"
    skip_final_cluster_snapshot: yes
  register: redshift_instance

- debug: var=redshift_instance
```

##### EXPECTED RESULTS

I would expect to see the "url", "public_ip_address", and "port" key/value pairs in the "cluster" dict return value.

##### ACTUAL RESULTS

The "cluster" dict return value is missing the aforementioned key/value pairs. As expected, I can see key/value pairs for status, availability_zone, db_name, create_time, private_ip_address, identifier, and maintenance_window. I also see "username", though that is not mentioned in the list of return values on http://docs.ansible.com/ansible/latest/redshift_module.html.

```
TASK [listener : redshift] *******************************************************************************************************************************************************************************
changed: [localhost]

TASK [listener : debug] **********************************************************************************************************************************************************************************
ok: [localhost] => {
    "redshift_instance": {
        "changed": true,
        "cluster": {
            "availability_zone": "us-east-1b",
            "create_time": 1511629400.256,
            "db_name": "dbname",
            "identifier": "id",
            "maintenance_window": "tue:03:00-tue:03:30",
            "private_ip_address": "172.31.2.250",
            "status": "available",
            "username": "admin"
        },
        "failed": false
    }
}
```
