### ISSUE TITLE
VMware: vmware_guest fails to create VM when the network is a Portgroup of a  vSphere distributed virtual switch

### ISSUE THREAD

**Issue by mowntan** [ansible/ansible#33284]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /Users/jyoung/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
MacOS 10.13.1
GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)

##### SUMMARY
Vmware creation fails when the network is a Portgroup of a  vSphere distributed virtual switch. Using a standard switch network is ok. The vsphere_guest module has the option to specify the network_type, like: network_type: dvs. This option does not exist in vmware_guest.

##### STEPS TO REPRODUCE
Create a new guest using a portgroup from a distributed virtual switch

```yaml
   - name: create new vmware guest
      vmware_guest:
        validate_certs: False
        hostname: "{{ vmware_vcenter_server }}"
        username: "{{ vmware_vcenter_user }}"
        password: "{{ vmware_vcenter_pass }}"
        datacenter: "{{ vmware_datacenter }}"
        cluster: "{{ vmware_cluster }}"
        name: "{{ hostname }}"
        guest_id: "{{ vmware_guest_id }}"
        # https://www.vmware.com/support/developer/converter-sdk/conv55_apireference/vim.vm.GuestOsDescriptor.GuestOsIdentifier.html
        disk:
          - size_gb: "{{ vmware_os_disk_gb }}"
            type: "{{ vmware_disk_type }}"
            datastore: "{{ vmware_datastore }}"
            autoselect_datastore: true
        networks:
          - name: "{{ vmware_build_vlan }}"
            #type: "{{ vmware_network_type}}"
            #ip: "{{ ipaddress }}"
            #netmask: "255.255.255.0"
        hardware:
          num_cpus: "{{ vmware_cpu_sockets }}"
          memory_mb: "{{ vmware_memory_mb }}"
          scsi: "{{ vmware_scsi_type }}"
        state: present
      register: newvm
```

##### EXPECTED RESULTS
Expected vmware_guest to be created

##### ACTUAL RESULTS
```
fatal: [localhost]: FAILED! => {
    "changed": true,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "DEV",
            "customization": {},
            "customvalues": [],
            "datacenter": "DC",
            "disk": [
                {
                    "autoselect_datastore": true,
                    "datastore": "DATASTORE",
                    "size_gb": "60",
                    "type": "thick"
                }
            ],
            "esxi_hostname": null,
            "folder": "/vm",
            "force": false,
            "guest_id": "rhel7_64Guest",
            "hardware": {
                "memory_mb": "8192",
                "num_cpus": "4",
                "scsi": "paravirtual"
            },
            "hostname": "vcserver",
            "is_template": false,
            "name": "new-guest",
            "name_match": "first",
            "networks": [
                {
                    "name": "DIST~PORT~GROUP"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "state": "present",
            "template_src": null,
            "username": "ansible-admin",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "A specified parameter was not correct. \nspec.deviceChange.device.port.switchUuid"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@mowntan Thanks for reporting this issue.

**Comment by mowntan** [comment]
Looking at the vmware_guest code, I see references to dvs as a configuration, so my assumption is that it should be supported.
https://github.com/ansible/ansible/blob/88a14465b7816f384d915f7dfc0c2c5a2fe08aaa/lib/ansible/modules/cloud/vmware/vmware_guest.py#L785

**Comment by mowntan** [comment]
Another update: this looks to be caused by our DVS/Network naming convention. We (ciscoACI) actually use the same network_name/Portgroup across multiple Distributed switches. So our config looks like the following

#DVS -> PortGroup
DEV -> LINUX_BUILD
QA -> LINUX_BUILD
PROD -> LINUX_BUILD

When using the ansible vmware_guest module is there a way that I can indicate the DVS and portgroup in the name? Like a KEY?

eg
```
    "networks": [
                {
                    "name": "DVS ~ PORTGROUP"
                }
            ],
```

**Comment by mowntan** [comment]
Tested with ansible 2.4 and 2.5, both are affected.

**Comment by cdelgehier** [comment]
same observation for me
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cdelgehier/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7.14/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Dec  7 2017, 15:02:34) [GCC 4.8.4]
```
I got a ` File \"/usr/local/lib/python2.7.14/lib/python2.7/threading.py\", line 213, in release\n    self._note(\"%s.release(): non-final release\", self)\nRuntimeError: maximum recursion depth exceeded`

If the name is a portgroup on a vswitch (like  "VM Network"), it s ok.
If the name is a non existing portgroup (like "foo"), it s ok => `"Network 'foo' does not exists"`
If the name match a portgroup on a DVS ... 

```
File \"/tmp/ansible_Ydz06f/ansible_module_vmware_guest.py\", line 1512, in <module>\n    main()\n  File \"/tm
p/ansible_Ydz06f/ansible_module_vmware_guest.py\", line 1503, in main\n    result = pyv.deploy_vm()\n  File \"/tmp/ansible_Ydz06f/ansible_module_vmware_guest.py\", line 1313, in deploy_vm\n    configspec_json = serialize_spec(self.config
spec)\n  File \"/tmp/ansible_Ydz06f/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 626, in serialize_spec\n  File \"/tmp/ansible_Ydz06f/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 611, in serialize_spec\n  File \
"/tmp/ansible_Ydz06f/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 611, in serialize_spec\n  File \"/tmp/ansible_Ydz06f/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 611, in serialize_spec\n  File \"/tmp/ansible_Y
dz06f/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 611, in serialize_spec\n  File \"/tmp/ansible_Ydz06f/ansible_modlib.zip/ansible/module_utils/vmware.py\" ...```

**Comment by Akasurde** [comment]
@cdelgehier Could you please paste your playbook ?

**Comment by cdelgehier** [comment]
https://github.com/ansible/ansible/issues/33760#issue-280931491 you find it here

**Comment by Akasurde** [comment]
@mowntan I am not sure how you created same name DV Portgroups into different DVS. I tried to create same environment but failed to create same name DV PG on two differenet DVS. Let me know if I am missing anything.

**Comment by Akasurde** [comment]
@mowntan @cdelgehier Could you please retry using latest 2.5alpha1 and let me know if it works for you ?

**Comment by Akasurde** [comment]
@mowntan @cdelgehier Any news ?

**Comment by Akasurde** [comment]
@mowntan While debugging https://github.com/ansible/ansible/issues/36835 I found that there are two types of virtual switches. And UUID returned by them are also different. Also, found that if host on which VM is going to be deployed should be part of that DVSPortgroup + DVSwitch, else you will always get this error.

Could you please check if the host / cluster member host are part of that DVSPortgroup + DVSwitch ?

**Comment by ansibot** [comment]
@mowntan This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@mowntan You have not responded to information requests in this issue so we will assume it no longer affects you. If you are still interested in this, please create a new issue with the requested information.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mowntan** [comment]
@Akasurde, confirmed that the host / cluster member host are part of the DVSPortgroup + DVSwitch that I am trying to deploy. I believe, in order to resolve this issue we would need to reference the DVSwitch in the network name. (or possibly provide a lookup method). The current module doesn't allow for this, but it looks like the previous vsphere_guest module was aware of the difference between a standard network and a DVS/Portgroup:
https://github.com/ansible-provisioning/ansible-provisioning/blob/8b2f4c4fdb98b941f61c20393d28be1cf2d2f427/library/vsphere_guest#L276

It had two helper methods to find the portgroup_key, and then find the associated dvswitch_uuid. Are these methods available in the vmware_guest module, I couldnt find them.

**Comment by mowntan** [comment]
I've also attempted with ansible 2.5.0a, 2.5.0rc, and final 2.5.0. I will note that the error has changed slightly, it now doesn't complain about an incorrect switchUUID.

```
"msg": "Failed to create a virtual machine : A component of the virtual machine is not accessible on the host."
```

I think this is still the same issue, just being represented a little differently. The vmware call is getting the first network with the given name, and its not the network that is attached to this cluster. In order to properly identify the correct network name, it would need to have the correct DVSwitch that is attached to the cluster because the network name is being reused across all the clusters.

**Comment by Akasurde** [comment]
bot_skip

**Comment by Akasurde** [comment]
@mowntan Do you have multiple Datacenters ?

**Comment by mowntan** [comment]
We have One VC, One Datacenter, and 7 Clusters. Each cluster has a "BUILD" Network that is attached to a specific DVS on each cluster.

**Comment by Akasurde** [comment]
@mowntan Can you please check this patch https://github.com/ansible/ansible/pull/38369 and let me know if it works for you ?

**Comment by Akasurde** [comment]
needs_info

**Comment by mc-meta** [comment]
Hello,

we seem to have a similar problem with ansible-2.7.0-1.201805312246git.5228b939fe.el7.ans.noarch
(so including #38369) towards Vsphere 5.5 update 3, pyvmomi-6.7.0.

Module invocation:
```yaml
     vmware_guest:
       hostname: "{{ vcenter_host }}"
       username: "{{ vcenter_username }}"
       password: "{{ vcenter_password }}"
       validate_certs: no
       datacenter: "{{ vcenter_dc }}"
       esxi_hostname: mid1-vc1-1.example.com
       name: {{ vm_name }}
       template: ansible-template
       folder: /Devel/Devel_124
       disk:
       - size_gb: 30
         type: thin
         datastore: DS-VC1-DEV-VNX-01
       cdrom:
         type: "none"
       networks:
         - name: "PreProd_Rserver_192.168.xxx.0_23"
         device_type: vmxnet3
       state: poweredon
       wait_for_ip_address: no
     delegate_to: localhost
     register: deploy
```
we got:
```
ansible-playbook play-test-vmware.yml -vvv
ansible-playbook 2.7.0.dev0
  config file = /opt/ansible-controller-vmware/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
Using /opt/ansible-controller-vmware/ansible.cfg as config file
Parsed /opt/ansible-controller-vmware/hosts inventory source with ini plugin

PLAYBOOK: play-test-vmware.yml ***********************************************************************************
1 plays in play-test-vmware.yml
Enter password:

PLAY [Check Mounts] **********************************************************************************************

TASK [Gathering Facts] *******************************************************************************************
task path: /opt/ansible-controller-vmware/play-test-vmware.yml:3
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
ok: [localhost]
META: ran handlers

TASK [Clone a VM from Template and customize] ********************************************************************
task path: /opt/ansible-controller-vmware/play-test-vmware.yml:10
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {
                "type": "none"
            },
            "cluster": null,
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "DC1",
            "disk": [
                {
                    "datastore": "DS-VC1-DEV-VNX-01",
                    "size_gb": 30,
                    "type": "thin"
                }
            ],
            "esxi_hostname": "mid1-vc1-1.example.com",
            "folder": "/Devel/Devel_124",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "xx.xxx.xx.xx",
            "is_template": false,
            "linked_clone": false,
            "name": "ansibledeploy-test",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "name": "PreProd_Rserver_192.168.xxx.0_23",
                    "type": "dhcp"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": "ansible-template",
            "username": "ansible-test",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_ip_address": false
        }
    },
    "msg": "It seems that host system 'mid1-vc1-1.example.com' is not associated with distributed virtual portgroup 'PreProd_Rserver_192.168.xxx.0_23'. Please make sure host system is associated with given distributed virtual portgroup"
}

PLAY RECAP *******************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
As you may check virtual port group is associated with that very host system.

![capture3](https://user-images.githubusercontent.com/34809553/40849579-9a114a02-65c2-11e8-8d3d-778516923d45.PNG)

Our vcenter is currently managing 3 virtual clusters each one with his own distributed virtual switch.

All network labels are named consistently (the same) on each distributed virtual switch.

This is for us a priority matter, so we are available to share more info or test new code.

Thanks!

-m

**Comment by Akasurde** [comment]
@mc-meta Thanks. Could you please open a new issue, so that it will be easy for tracking purposes ? 

ping me on irc channel #ansible-vmware hosted on irc.freenode.net.

**Comment by RemcoKomduurDUO** [comment]
Hi,

Just tested this code but it doesn't work for us.

We have standard port groups and vds port groups behind 1 vds. The port group names in both are the same. After clone from template the standard port group name is used instead of the vds one. The standard ones aren't used at the moment so the network isn't connected.

We would like the option added to force the vds by being able to add it as a property on the network. So something like vds_name: vDS-LAB

**Comment by marcobellaccini** [comment]
I think this can now be solved by using the *dvswitch_name* parameter introduced by https://github.com/ansible/ansible/pull/41899

**Comment by jctanner** [comment]
@mowntan please confirm @marcobellaccini's comment.

needs_info

**Comment by Akasurde** [comment]
@mowntan Any news ?

**Comment by Akasurde** [comment]
@mowntan Any news?

**Comment by Kreeblah** [comment]
I believe I'm running into what @mowntan was describing as well.  I have a test playbook that I've been testing with which looks like this:

```
---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a VM on stgvc01
      vmware_guest:
        hostname: "{{ vsphere_host }}"
        username: "{{ vsphere_user }}"
        password: "{{ vsphere_password }}"
        datacenter: "{{ vm_datacenter }}"
        folder: "{{ vm_folder }}"
        validate_certs: no
        name: "{{ vm_name }}"
        cluster: "{{ vm_cluster }}"
        state: poweredoff
        guest_id: centos64Guest
        disk:
        - size_gb: "{{ vm_os_size }}"
          type: thin
          datastore: "{{ vm_os_datastore }}"
        - size_gb: "{{ vm_log_size }}"
          type: thin
          datastore: "{{ vm_log_datastore }}"
        - size_gb: "{{ vm_swap_size }}"
          type: thin
          datastore: "{{ vm_swap_datastore }}"
        hardware:
          memory_mb: "{{ vm_memory_mb }}"
          mem_reservation: "{{ vm_memory_mb }}"
          boot_firmware: efi
          num_cpus: "{{ vm_cpus }}"
          num_cpu_cores_per_socket: "{{ vm_cpus }}"
          hotadd_cpu: false
          hotremove_cpu: false
          hotadd_memory: false
          scsi: lsilogic
        networks:
        - name: "{{ vm_build_network }}"
          device_type: vmxnet3
          dvswitch_name: "{{ vm_build_network_dvswitch }}"
          start_connected: true
```

When I attempt to run that with Ansible 2.9.7, I get the following:

```
fatal: [localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": [], 
            "cluster": "VMCLUSTER", 
            "convert": null, 
            "customization": {}, 
            "customization_spec": null, 
            "customvalues": [], 
            "datacenter": "VMDATACENTER", 
            "datastore": null, 
            "disk": [
                {
                    "datastore": "VMOSDATASTORE", 
                    "size_gb": 10, 
                    "type": "thin"
                }, 
                {
                    "datastore": "VMLOGDATASTORE", 
                    "size_gb": 20, 
                    "type": "thin"
                }, 
                {
                    "datastore": "VMSWAPDATASTORE", 
                    "size_gb": 4, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "VMFOLDER", 
            "force": false, 
            "guest_id": "centos64Guest", 
            "hardware": {
                "boot_firmware": "efi", 
                "hotadd_cpu": false, 
                "hotadd_memory": false, 
                "hotremove_cpu": false, 
                "mem_reservation": 2048, 
                "memory_mb": 2048, 
                "num_cpu_cores_per_socket": 2, 
                "num_cpus": 2, 
                "scsi": "lsilogic"
            }, 
            "hostname": "VSPHEREHOST", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "VMHOSTNAME", 
            "name_match": "first", 
            "networks": [
                {
                    "device_type": "vmxnet3", 
                    "dvswitch_name": "VMWAREVSWITCH", 
                    "name": "VMWARENETWORK", 
                    "start_connected": true, 
                    "type": "dhcp"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "proxy_host": null, 
            "proxy_port": null, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "poweredoff", 
            "state_change_timeout": 0, 
            "template": null, 
            "use_instance_uuid": false, 
            "username": "VMWAREUSERNAME", 
            "uuid": null, 
            "validate_certs": false, 
            "vapp_properties": [], 
            "wait_for_customization": false, 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "Failed to create a virtual machine : A component of the virtual machine is not accessible on the host."
}

```
