### ISSUE TITLE
Redshift module doesn't allow dc2.large node type

### ISSUE THREAD

**Issue by bchamby** [ansible/ansible#33280]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

redshift

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/brad.chamberlain/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

<no output / empty>

##### OS / ENVIRONMENT

Running from macOS High Sierra 10.13.1

Running against AWS Redshift

##### SUMMARY

The Redshift module doesn't allow dc2.large as a node type option, but this is the default node type in Redshift. The AWS console says, "The ds2 and dc2 node types replace the ds1 and dc1 node types, respectively. The newer ds2 and dc2 node types provide higher performance than ds1 and dc1 at no extra cost." so it sounds like dc2.large is replacing the older dc1.large node type.

##### STEPS TO REPRODUCE

Run the following in a role.

```yaml
- name: redshift
  redshift:
    command: create
    region: "{{ redshift_region }}"
    node_type: dc2.large
    identifier: "{{ redshift_name }}"
    availability_zone: "{{ redshift_az }}"
    cluster_type: single-node
    db_name: "{{ redshift_db_name }}"
    username: "{{ redshift_username }}"
    password: "{{ redshift_password }}"
    publicly_accessible: yes
    vpc_security_group_ids: "{{ redshift_sg_id }}"
    skip_final_cluster_snapshot: yes
```

##### EXPECTED RESULTS

Redshift single-node cluster with dc2.large node type.

##### ACTUAL RESULTS

Got the following error message:

TASK [listener : redshift] *******************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "value of node_type must be one of: ds1.xlarge,ds1.8xlarge,ds2.xlarge,ds2.8xlarge,dc1.large,dc1.8xlarge,dw1.xlarge,dw1.8xlarge,dw2.large,dw2.8xlarge, got: dc2.large"}

```
TASK [listener : redshift] *******************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "value of node_type must be one of: ds1.xlarge,ds1.8xlarge,ds2.xlarge,ds2.8xlarge,dc1.large,dc1.8xlarge,dw1.xlarge,dw1.8xlarge,dw2.large,dw2.8xlarge, got: dc2.large"}
```
