### ISSUE TITLE
apt_key retries GPG key download but apt_repository seems not retry

### ISSUE THREAD

**Issue by saiya** [ansible/ansible#33287]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

apt_repository

##### ANSIBLE VERSION

`2.4.1.0` (and I looked latest `devel` branch source code)

##### OS / ENVIRONMENT

Ubuntu 16.04 (Xenial)

##### SUMMARY

Hi, I encounterd GPG key download issue as same as https://github.com/ansible/ansible-modules-core/pull/3987 when using `apt_repository`.

As show in above Pull Requst, `apt_key` can retry when GPG key download failed. But `apt_repository` seems not.

Here is source code that I looked:
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt_repository.py#L432
https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt_repository.py#L469-L471

In contrast, `apt_key` retries `apt-key adv` command 5 times: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt_key.py#L218-L232

Sorry in advance if I'm wrong. I am not familiar with Python.

##### STEPS TO REPRODUCE

I found this issue with following playbook:

```yaml
  - name: Add golang-backports ppa (to get newer golang binary)
    apt_repository:
      repo: 'ppa:longsleep/golang-backports'
```

Sometimes, above playbook fails due to `keyserver receive failed: unknown pubkey algorithm` error (as same as https://github.com/ansible/ansible-modules-core/issues/3986 ).

Since it failed, below way mitigated this issue:

```yaml
  - name: Download an apt key of ppa:longsleep/golang-backports
    # (workaround) `apt_key` can retry GPG key download error, thus I invoke `apt_key` beforehand
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: 52B59B1571A79DBC054901C0F6BC817356A3D45E
  - name: Add golang-backports ppa (to get newer golang binary)
    apt_repository:
      repo: 'ppa:longsleep/golang-backports'
```

##### EXPECTED RESULTS

`apt_repository` also retries GPG key download.

##### ACTUAL RESULTS

`apt_repository` seem not to retry.

I really enjoy using Ansible. Thank you in advance.
