### ISSUE TITLE
IOS_STATIC_ROUTE: admin_distance overwrites existing configuration when not provided in the task

### ISSUE THREAD

**Issue by jmcgill298** [ansible/ansible#33290]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_static_route
##### ANSIBLE VERSION

```
2.4.1
```

##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

Module overwrites existing configuration for `admin_distance` when parameter is not provided in the task.
##### STEPS TO REPRODUCE

```yaml
---
- name: DEMONSTRATE USING OMIT FILTER
  hosts: ios
  connection: local
  gather_facts: no
  tasks:
    - name: ENSURE VLAN EXISTS
      ios_static_route:
        state: "present"
        prefix: "{{ item.prefix }}"
        mask: "{{ item.mask }}"
        next_hop: "{{ item.next_hop }}"
        admin_distance: "{{ item.admin_distance | default(omit) }}"
      with_items:
        - {"prefix": "192.168.10.0", "mask": "255.255.255.0", "next_hop": "192.168.1.1", "admin_distance": 5}
        - {"prefix": "192.168.10.0", "mask": "255.255.255.0", "next_hop": "192.168.1.1"}
```

##### EXPECTED RESULTS

I expected the route on the end device to have `ip route 192.168.10.0 255.255.255.0 192.168.1.1 5`
##### ACTUAL RESULTS

end device has `ip route 192.168.10.0 255.255.255.0 192.168.1.1`

The reason this is happening is because the `admin_distance` parameter has a default of `1` in the module. Defaulting configuration parameters in modules is dangerous as the end users expect only arguments passed to the module are in consideration for changes (a very reasonable assumption).

I suspect this was done in order to handle idempotency (which ironically doesn't work for my test machine since the default of `1` is omitted). A better approach would be to parse existing routes and only validate the parameters that are passed in the task match an existing route (not spread across multiple routes). This approach would account for discrepancy across OS versions, since some versions include the default admin_distance of `1` in the configuration, and some do not. This approach would also account for idempotency when additional parameters such as vrf, interface, comment, tag, track, etc. are added.
