### ISSUE TITLE
IOS_STATIC_ROUTE: module is not idempotent

### ISSUE THREAD

**Issue by jmcgill298** [ansible/ansible#33291]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_static_route
##### ANSIBLE VERSION

```
2.4.1
```

##### OS / ENVIRONMENT

Ubuntu 16.04
IOS Version 12.2(44)SE2
##### SUMMARY

module is not idempotent
##### STEPS TO REPRODUCE

```yaml
---
- name: DEMONSTRATE USING OMIT FILTER
  hosts: ios
  connection: local
  gather_facts: no
  tasks:
    - name: ENSURE VLAN EXISTS
      ios_static_route:
        state: "present"
        prefix: "{{ item.prefix }}"
        mask: "{{ item.mask }}"
        next_hop: "{{ item.next_hop }}"
        admin_distance: "{{ item.admin_distance | default(omit) }}"
      with_items:
        - {"prefix": "192.168.10.0", "mask": "255.255.255.0", "next_hop": "192.168.1.1"}
        - {"prefix": "192.168.10.0", "mask": "255.255.255.0", "next_hop": "192.168.1.1"}
```

##### EXPECTED RESULTS

I expected the second iteration to have `changed: false`
##### ACTUAL RESULTS

Configuration was resent to the device.

My test machine does not include the `admin_distance` in the configuration when it is the defaultof `1`. The module is defaulting `admin_distance` to `1`, which turns my request into `ip route 192.168.10.0 255.255.255.0 192.168.1.1 1` but my device only shows `ip route 192.168.10.0 255.255.255.0 192.168.1.1`. 

I suggest parsing routing configurations and only validating parameters that are passed to the task against the routes and not comparing CLI config lines. Comparing configuration lines will only work for matching exact configuration sequences, which has 2 problems:

1. Discrepancies across end device versions is difficult to support
2. Unable to validate a subset of a line's configuration is present (how would adding support for vrf, tag, comments work in this model?)

#33290
