### ISSUE TITLE
aws ec2 component returns "public_ip": null if aws c5 instance type

### ISSUE THREAD

**Issue by rauldelperal** [ansible/ansible#33305]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION
ansible 2.4.1.0
ansible python module location = /home/myhome/.local/lib/python3.5/site-packages/ansible
executable location = /home/myhome/.local/bin/ansible
python version = 3.5.2 (default, Sep 14 2017, 22:51:06) [GCC 5.4.0 20160609]

##### CONFIGURATION
ACCELERATE_CONNECT_TIMEOUT(/home/buccaneer/Documents/ansible/ansible.cfg) = 5.0
ACCELERATE_PORT(/home/buccaneer/Documents/ansible/ansible.cfg) = 5099
ACCELERATE_TIMEOUT(/home/buccaneer/Documents/ansible/ansible.cfg) = 30
ANSIBLE_SSH_ARGS(/home/buccaneer/Documents/ansible/ansible.cfg) = -o ControlMaster=no
DEFAULT_ACTION_PLUGIN_PATH(/home/buccaneer/Documents/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/buccaneer/Documents/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/home/buccaneer/Documents/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/home/buccaneer/Documents/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/home/buccaneer/Documents/ansible/ansible.cfg) = 5
DEFAULT_HOST_LIST(/home/buccaneer/Documents/ansible/ansible.cfg) = ['/etc/ansible/hosts']
DEFAULT_LOG_PATH(/home/buccaneer/Documents/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/buccaneer/Documents/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/home/buccaneer/Documents/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_PATH(/home/buccaneer/Documents/ansible/ansible.cfg) = ['/usr/share/ansible']
DEFAULT_POLL_INTERVAL(/home/buccaneer/Documents/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/home/buccaneer/Documents/ansible/ansible.cfg) = 22
DEFAULT_REMOTE_TMP(/home/buccaneer/Documents/ansible/ansible.cfg) = $HOME/.ansible/tmp
DEFAULT_SUDO_EXE(/home/buccaneer/Documents/ansible/ansible.cfg) = sudo
DEFAULT_SUDO_USER(/home/buccaneer/Documents/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/home/buccaneer/Documents/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/home/buccaneer/Documents/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/home/buccaneer/Documents/ansible/ansible.cfg) = ['/usr/share/ansible_plugins/vars_plugins']
RETRY_FILES_ENABLED(/home/buccaneer/Documents/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Ubuntu 16.04 LTS

##### SUMMARY
When creates a ec2 instance type c5, public_ip variable is null. If select another instance type public_ip is setted:

    "instances": [
        {
            "ami_launch_index": "0",
            "architecture": "x86_64",
            "block_device_mapping": {
                "/dev/xvda": {
                    "delete_on_termination": true,
                    "status": "attached",
                    "volume_id": "vol-xxxxxxxxxx"
                }
            },
            "dns_name": "",
            "ebs_optimized": false,
            "groups": {
            },
            "hypervisor": "xen",
            "id": "i-xxxxxxxxxx",
            "image_id": "ami-xxxxxx",
            "instance_type": "c5.large",
            "kernel": null,
            "key_name": null,
            "launch_time": "2017-11-27T13:15:45.000Z",
            "placement": "eu-west-1c",
            "private_dns_name": "ip-XXX-XX-XX-XX.eu-west-1.compute.internal",
            "private_ip": "172.31.43.73",
            "public_dns_name": "",
            "public_ip": null,
            "ramdisk": null,
            "region": "eu-west-1",
            "root_device_name": "/dev/xvda",
            "root_device_type": "ebs",
            "state": "running",
            "state_code": 16,
            "tags": {
            },
            "tenancy": "default",
            "virtualization_type": "hvm"
        }
    ],

##### STEPS TO REPRODUCE

```
# tasks file for deployEC2
- name: Deploying instance
  ec2:
    aws_access_key: "{{ aws_akey }}"
    aws_secret_key: "{{ aws_skey }}"
    image: "{{ aws_amiid }}"
    instance_type: "{{ aws_size }}"
    region: "{{ aws_region }}"
    group_id: "{{ aws_secgroup }}"
    vpc_subnet_id: "{{ aws_subnet }}"
    instance_tags:
      Client: "{{ client_name }}"
      Product: "{{ product_standard }}"
      GUIDTicket: "{{ task_id }}"
    assign_public_ip: yes
    wait: true
    wait_timeout: 300
    state: present
  register: vm
```

##### EXPECTED RESULTS
I would need public_ip variable in the response. If you open your AWS web interface console, you can see the Public IP as expected.

##### ACTUAL RESULTS
public_ip and  public_dns_name variables are not setted.
