### ISSUE TITLE
The FirewallD module should support adding a zone

### ISSUE THREAD

**Issue by dcode** [ansible/ansible#33307]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
firewalld

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = <REDACTED>/ansible.cfg
  configured module search path = [u'/<REDACTED>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
No changed settings

##### OS / ENVIRONMENT

I'm trying to manage CentOS 7 / RHEL 7 systems with firewalld enabled.

##### SUMMARY
I use FirewallD to manage my system firewalls for various services. Some services should only be reachable by specific IP subnets. The current `firewalld` module allows me to specify a source IP range, but I have to choose an existing zone. The problem with this, is that most of these zones have "side effects" of existing rules and it limits the number of unique source ranges to ports I would give access to. 

I'd like to be able to do the equivalent of the following using Ansible.

```
sudo firewall-cmd --new-zone=kafka_consumers --permanent
sudo firewall-cmd --zone=kafka_consumers --add-source=192.0.2.0/24 --permanent
sudo firewall-cmd --zone=kafka_consumers --add-port=9092/tcp --permanent
sudo firewall-cmd --reload
```

##### STEPS TO REPRODUCE
I think using the module and only specifying the zone with a state of `present` makes sense as an atomic change. Then the rules could be applied.

```yaml
- name: Ensure kafka_consumers zone exists
  firewalld:
    zone: kafka_consumers
    state: present
    permanent: yes
    immediate: yes
- name: Add TEST-NET-1 to zone
  firewalld:
    zone: kafka_consumers
    source: 192.0.2.0/24
    permanent: yes
    immediate: yes
    state: present
- name: Add kafka port to zone
  firewalld:
    zone: kafka_consumers
    port: 9092/tcp
    permanent: yes
    immediate: yes
    state: present
```

##### EXPECTED RESULTS
The zone would be created, then the rules would be applied

##### ACTUAL RESULTS
The `firewalld` module execution fails due to zone not existing.
