### ISSUE TITLE
Request failed: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>"

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/ansible#33312]
##### ISSUE TYPE

 - Bug Report

Appears to be similar to 32053 which is closed:
https://github.com/ansible/ansible/pull/32053

##### COMPONENT NAME

URI

##### ANSIBLE VERSION

```
ca-spollockmb1:fs-skytap-control spollock$ ansible --version
ansible 2.5.0
  config file = /Users/spollock/ansible/fs-skytap-control/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
ca-spollockmb1:fs-skytap-control spollock$ python --version
Python 2.7.10

```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_REMOTE_PORT(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = spollock
DEFAULT_TIMEOUT(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = 30
RETRY_FILES_ENABLED(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = False
##### OS / ENVIRONMENT

OSX 10.11.6

##### SUMMARY

Throwing an error when connecting to an HTTPS site.

##### STEPS TO REPRODUCE

```yaml

- name: Generate the Report
  uri:
    url: https://cloud.skytap.com/auditing/exports.json
    method: POST
    user: "{{ skytapuser }}"
    password: "{{ skytapapitoken }}"
    force_basic_auth: yes
    body_format: json
    validate_certs: no


```

##### EXPECTED RESULTS

Should have returned status = 200

Tested exact same config with POSTMAN and it works fine.

##### ACTUAL RESULTS

```

atal: [localhost]: FAILED! => {"changed": false, "content": "", "msg": "Status code was not [200]: Request failed: <urlopen error [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>", "redirected": false, "status": -1, "url": "https://cloud.skytap.com/auditing/exports.json"}


```
