### ISSUE TITLE
uri module doesn’t handle multiple cookies with same name

### ISSUE THREAD

**Issue by haneefarkin** [ansible/ansible#33325]
##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

    module : uri
##### ANSIBLE VERSION

```
Current master
```

##### STEPS TO REPRODUCE

```yaml
- name: Platform login request
      uri :
        url:  "{{ platform_url }}/login"
        method: POST
        headers:
           Content-Type: "application/json"
        body: "{{ platform_login_request | to_json }}"
        status_code: 200
        validate_certs: no
        timeout: 20
      register: login_result

    - name: Get Pairing Info
      uri :
        url:  "{{ platform_url }}//nodes"
        method: GET
        headers:
           cookie: "{{ login_result.set_cookie}}"
        status_code: 200
        timeout: 20
        validate_certs: no
      
```

##### EXPECTED RESULTS

I'm getting 
set_cookie": “X-JSESSIONID=e80e63ec-defa-44d7-bd6d-b42991d8e1d8; Path=/; Secure; HttpOnly, X-JSESSIONID=deleteMe; Path=/; Max-Age=0; Expires=Sun, 26-Nov-2017 19:35:20 GMT; Secure, X-JSESSIONI=58051d1d-bf80-486c-96ff-2b8fe4dab4ce; Path=/; Secure; HttpOnly, rememberMe=deleteMe; Path=/; Max-Age=0; Expires=Sun, 26-Nov-2017 19:35:21 GMT",

If the server sends the same cookie with same name, the last one should take precedence, but URI module keeps both of them. This behavior is different from that of CURL/python request or urllib2 

##### ACTUAL RESULTS

```

```
