### ISSUE TITLE
Option to change file permissions/attributes in sysctl module

### ISSUE THREAD

**Issue by jainnikhil30** [ansible/ansible#33331]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

sysctl
##### ANSIBLE VERSION

```
2.4.1
```

##### SUMMARY

There should be an option in sysctl module to change/set the owner, group & mode of the file updated/created. Currently it uses default owner/umask

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/sysctl.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/sysctl.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @davixx
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@jainnikhil30 Thanks for reporting this issue. The [file](https://docs.ansible.com/ansible/latest/modules/file_module.html) module can be used to set permission and ownership of a file. So I think this is duplicate efforts. 

Thanks for the feature request.

**Comment by jainnikhil30** [comment]
@Akasurde Thanks for taking a look at this. I totally understand that this can be done via file module. But since sysctl module also creates the file, if it doesnt exist via "sysctl_file" parameter, I think it would be a good feature to allow setting owner, group & mode options so the file permissions can be set for the newly created file. Could you please reconsider the request ?

**Comment by gundalow** [comment]
One of the design principals of Ansible is every plugin (module) should do only one thing and one thing well. This follows the Linux principal "Do One Thing and Do It Well". In this case we already have the `file` whose purpose is for setting permissions and ownership.

**Comment by abadger** [comment]
If you want to make sure that the file always has explicitly set permissions, use either the file or the copy module prior to running the sysctl module like this:

```
# Using file to do this.
- file:
    state: "touch"
    mode: "0600"
    owner: "root"
    group: "root"
    dest: "/srv/my/local/sysctl.conf"
    # In Ansible 2.7, you'll likely want to specify these as well so that touch is idempotent:
    #modification_time: "preserve"
    #access_time: preserve"

# Using copy content, this works around the fact that file in Ansible prior to version 2.7 has no way to create a file idempotently
- copy:
    content: ""
    mode: "0600"
    owner: "root"
    group: "root"
    dest: "/srv/my/local/sysctl.conf"
```

Many different modules, both maintained by ansible and maintained by the community, will create a file if it does not exist.  If we didn't follow the Unix principle of doing one thing well, here, then we'd have  to maintain a lot more code with a lot more opportunities for bugs to occur.
