### ISSUE TITLE
Upgrade / Downgrade ec2 type on the fly

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#33373]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/pkaramol/.ansible.cfg
  configured module search path = [u'/home/pkaramol/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/pkaramol/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/pkaramol/.ansible.cfg) = -F ssh.cfg
ANSIBLE_SSH_PIPELINING(/home/pkaramol/.ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/pkaramol/.ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/pkaramol/.ansible.cfg) = 50
DEFAULT_GATHERING(/home/pkaramol/.ansible.cfg) = explicit
HOST_KEY_CHECKING(/home/pkaramol/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/pkaramol/.ansible.cfg) = False

```

##### OS / ENVIRONMENT
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

```
$ uname -a
Linux pkara-pc01 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY
Enable on-the-fly instance type change (upgrade / downgrade).

Currently when running a script that creates `ec2` instance(s), there is no way to perform a type change (e.g. from `t2.micro` to `t2.small`).

##### STEPS TO REPRODUCE
Using vars from below

```
     my_instances:
     - instance_type: "t2.micro"
       exact_count: "1"
       assign_public_ip: "no"
     - instance_type: "t2.micro"
       exact_count: "1"
       assign_public_ip: "no"
```

and running the following task based on those vars:

```
    - name: Create my instances
      ec2:
        instance_type: "{{ item.ec2_instance_type }}"
        region: "us-east-1"
        image: "some-image"
        group_id: "some-group-id"
        vpc_subnet_id: "some-subnet-id"
        instance_tags:
      with_items: "{{ my_instances }}"
```

if those instances are there and running and one wants to re-run the script, having one of the instance types changed (from `t2.micro` --> `t2.small`), e.g. as follows:

     - instance_type: "t2.small"

the script runs idempotently again, although the output yields:

    ok: [localhost] => (item={instance_type': u't2.small'})

(output trimmed).

The instance type remains `t2.micro`

Insance type change seems to be supported by the __[aws cli](http://docs.aws.amazon.com/cli/latest/reference/ec2/modify-instance-attribute.html)__
