### ISSUE TITLE
Erratic behavior of ec2_asg module when running on top of existing asg

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#33384]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ec2_asg

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/pkaramol/.ansible.cfg
  configured module search path = [u'/home/pkaramol/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/pkaramol/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/pkaramol/.ansible.cfg) = -F ssh.cfg
ANSIBLE_SSH_PIPELINING(/home/pkaramol/.ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/home/pkaramol/.ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/pkaramol/.ansible.cfg) = 50
DEFAULT_GATHERING(/home/pkaramol/.ansible.cfg) = explicit
HOST_KEY_CHECKING(/home/pkaramol/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/pkaramol/.ansible.cfg) = False

```

##### OS / ENVIRONMENT
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

```
$ uname -a
Linux pkara-pc01 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY
When running an asg creation task, on top of an existing asg, momentarily, the values for min/max/desired increase by one

##### STEPS TO REPRODUCE
Create an asg with e.g. 

```
min_size=1
max_size=5
desired_capacity=1
```

Run the following task, __on top__ of the existing asg:

```
- name: Create auto scaling group
  ec2_asg:
    name: "asg-name"
    launch_config_name: "launch_configuration_name"
    region: "{{ VPC_REGION }}"
    min_size: 1
    max_size: 5
    desired_capacity: 1
    vpc_zone_identifier: "some_subnet_id"
    load_balancers: "some_elb_name"
    notification_topic: "some_sns_identifier"
    replace_all_instances: yes 
    tags:
      - Name: "my_asg"

```

During the (re?)creation of the asg, and if you keep refreshing on the ec2 web console, I get

Desired: 2
Min: 2
Max: 6

What is more, due to a relevant sns subscription, I get an email saying among others:

> Cause: At 2017-11-22T10:23:14Z a user request update of AutoScalingGroup constraints to min: 2, max: 6, desired: 2 changing the desired capacity from 1 to 2.  At 2017-11-22T10:23:33Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 2.

After a while, the reverse process takes place and the min/max/desired attributes get their expected values (1/5/1) which also causes automatic termination of redundant instances.
