### ISSUE TITLE
vmware_guest fails to set IP

### ISSUE THREAD

**Issue by marukka** [ansible/ansible#33380]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.4.1.0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Oct  5 2017, 19:02:54) [GCC 5.3.0]
```

##### CONFIGURATION
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /mnt/sofs.my.domain/Ansible/retry

##### OS / ENVIRONMENT
VMware Photon Linux
VMware vCenter 6.5 Build 6816762

##### SUMMARY
When creating a new VMware Photon Linux VM from a template, vmware_guest is unable to set the guest's ip address. 

##### STEPS TO REPRODUCE
Run the following playbook

```
- name: Create VM
  hosts: localhost
  gather_facts: no

  vars_prompt:
  - name: vcenter_password
    prompt: Password for administrator@my.domain
    private: yes

  - name: vm_name
    prompt: Name
    private: no

  - name: vm_folder
    prompt: Folder Path
    default: /Tests
    private: no

  tasks:
  - name: Create guest
    vmware_guest:
      hostname: vcenter.my.domain
      username: administrator@my.domain
      password: '{{ vcenter_password }}'
      validate_certs: no
      datacenter: Home
      cluster: Cluster
      name: '{{ vm_name }}'
      template: VMware Photon
      folder: '{{ vm_folder }}'
      state: poweredon
      hardware:
        memory_mb: 1024
      networks:
      - name: Intranet
        type: static
        ip: 10.1.105.105
        netmask: 255.255.0.0
        gateway: 10.1.0.1
```

The following packages are installed on the guest if that matters - https://gist.github.com/marukka/23e01fafd679cd55a154a82cf6d47cdb

##### EXPECTED RESULTS
Set the guest's IP to 10.1.105.105/16

##### ACTUAL RESULTS
Instead it just deletes the default systemd-networkd network profile leaving the guest without any network configuration.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@marukka Thanks for reporting this issue. Could you please provide `-vvvv` logs of this PB?

**Comment by marukka** [comment]
@Akasurde 

Here you go https://gist.github.com/marukka/bc137ad53deebb36e3fd7da7a0f6ae05

**Comment by lukasmrtvy** [comment]
@marukka  Do you have perl installed in template?

**Comment by Akasurde** [comment]
@marukka Do you have `open-vm-tools` service enabled and Perl installed in your template ?

**Comment by Akasurde** [comment]
needs_info

**Comment by Akasurde** [comment]
Could you please try with 2.5 version, there were several changes added in 2.5?

**Comment by imjoseangel** [comment]
Same happening on Windows VM Creation. Tested the following:

```yaml
  tasks:
    - name: Clone a VM from Template and customize
      vmware_guest:
        hostname: "{{ vmware_vsphere_host }}"
        username: "{{ vmware_vsphere_username }}"
        password: "{{ vmware_vsphere_password }}"
        validate_certs: no
        datacenter: DataCenter
        name: testvm-2
        folder: /folder
        template: mytemplate
        state: poweredon
        networks:
        - name: VM Network
          ip: 10.10.10.10
          netmask: 255.255.255.0
          gateway: 10.10.10.1
          dns_servers:
          - 10.10.10.1
          - 10.10.10.2
          type: static
          start_connected: True
      delegate_to: localhost
```

This has been tested under Ansible 2.5.0. 

We have proven with different configration options (DNS, no DNS, state:create, state:poweredon). Different Template Configurations (With and without NIC)
