### ISSUE TITLE
elb_application_lb does not add/remove listeners after its first creation

### ISSUE THREAD

**Issue by lfventura** [ansible/ansible#33391]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/lucas.ventura/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Apr 28 2017, 15:32:36) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### STEPS TO REPRODUCE

```yaml
  - name: Create Load Balancer {{ alb_name }}
    elb_application_lb:
      name: "{{ alb_name }}"
      state: present
      security_groups: "{{ security_group_id_list}}"
      subnets: "{{ ( internal ) | ternary(private_elb_subnets_ids, public_elb_subnets_ids) }}"
      listeners: "{{ alb_listeners }}"
      scheme: "{{ alb_scheme }}"
```

##### EXPECTED RESULTS
Application Load Balancer updated

##### ACTUAL RESULTS
Application Load Balancer remains as it was before the new run
```

```
