### ISSUE TITLE
get_url: Failed to validate the SSL certificate

### ISSUE THREAD

**Issue by bjoernalbers** [ansible/ansible#33417]
##### ISSUE TYPE

Bug Report

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/bjoern/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

NONE (`ansible-config dump --only-changed` returns nothing)

##### OS / ENVIRONMENT

ProductName:    Mac OS X
ProductVersion: 10.12.6
BuildVersion:   16G1036

##### SUMMARY

`get_url` returns an error when trying to download a file: `[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)`

##### STEPS TO REPRODUCE

```yaml
---
- name: test get_url
  hosts: server
  tasks:
    - name: download file
      get_url:
        url: https://repositories.sensuapp.org/osx/10.12/x86_64/sensu-1.1.1-1.dmg
        dest: /tmp/sensu-1.1.1-1.dmg
```

##### EXPECTED RESULTS

The file should be downloaded.

##### ACTUAL RESULTS

```
fatal: [server]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for repositories.sensuapp.org:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl. The exception msg was: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)."}
```

With `validate_certs=False` I also get an error:

```
fatal: [server]: FAILED! => {"changed": false, "dest": "/tmp/sensu-1.1.1-1.dmg", "failed": true, "msg": "Request failed: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>", "state": "absent", "url": "https://repositories.sensuapp.org/osx/10.12/x86_64/sensu-1.1.1-1.dmg"} 
```

The problem occurs when the remote host OS is macOS 10.12 or older. When it is the latest macOS 10.13 High Sierra the problem disappears.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/get_url.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/get_url.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chuckyz** [comment]
@bjoernalbers can you make sure you have the latest version of openssl and python2 from brew?

`python --version; python -c "import ssl; print ssl.OPENSSL_VERSION"`

may also be helpful here

**Comment by bjoernalbers** [comment]
Looks like there is some problem with OpenSSL...

On the host where it fails:

```
$ python --version; python -c "import ssl; print ssl.OPENSSL_VERSION"
Python 2.7.5
OpenSSL 0.9.8zg 14 July 2015

$ openssl s_client -connect repositories.sensuapp.org:443
CONNECTED(00000003)
47759:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:/SourceCache/OpenSSL098/OpenSSL098-52.8.4/src/ssl/s23_clnt.c:593:
```

On the host where it works:

```
$ python --version; python -c "import ssl; print ssl.OPENSSL_VERSION"
Python 2.7.10
LibreSSL 2.2.7

$ openssl s_client -connect repositories.sensuapp.org:443
CONNECTED(00000005)
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign Organization Validation CA - SHA256 - G2
verify error:num=20:unable to get local issuer certificate
verify return:0
---
Certificate chain
 0 s:/C=US/ST=California/L=San Francisco/O=Fastly, Inc./CN=c.sni.fastly.net
   i:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - SHA256 - G2
 1 s:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - SHA256 - G2
   i:/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFOzCCBCOgAwIBAgIMO4pgQymgER+m0k6OMA0GCSqGSIb3DQEBCwUAMGYxCzAJ
BgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMTwwOgYDVQQDEzNH
bG9iYWxTaWduIE9yZ2FuaXphdGlvbiBWYWxpZGF0aW9uIENBIC0gU0hBMjU2IC0g
RzIwHhcNMTcwMjA3MjI0MTA0WhcNMTkwMjA4MjI0MTA0WjBsMQswCQYDVQQGEwJV
UzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEV
MBMGA1UEChMMRmFzdGx5LCBJbmMuMRkwFwYDVQQDExBjLnNuaS5mYXN0bHkubmV0
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApbUevfFREAfvUH18oW27
BVLbkWJnbZ69dQCCchcuaXJ8Jq/I6plgKwW2yWUG/ynp7dp+0BwoWnzbiQHqZTsW
6Pqf0le2uENc8sSxLyILATG2Ct/s36XxXNfuH8388uOfiVvwoEAoDBD1VEXcI/4r
ei2KGwVx8PGLb60jitLDPLYOXW/kMu+WNg/+btjJ4khs30UeHh10UUrXjuRO3iga
6hOgKpvbkX03nfHH/+zc+sDfJerH0bmTwvZLwWupRW5x65hx2O2voUVbb27nnbqZ
zR57FZATEHyvqQghHsHjI8bwBI1azDuCz7vXIIKyYkXNO1eRrXzT46Tx7mHtanOL
bwIDAQABo4IB4TCCAd0wDgYDVR0PAQH/BAQDAgWgMIGgBggrBgEFBQcBAQSBkzCB
kDBNBggrBgEFBQcwAoZBaHR0cDovL3NlY3VyZS5nbG9iYWxzaWduLmNvbS9jYWNl
cnQvZ3Nvcmdhbml6YXRpb252YWxzaGEyZzJyMS5jcnQwPwYIKwYBBQUHMAGGM2h0
dHA6Ly9vY3NwMi5nbG9iYWxzaWduLmNvbS9nc29yZ2FuaXphdGlvbnZhbHNoYTJn
MjBWBgNVHSAETzBNMEEGCSsGAQQBoDIBFDA0MDIGCCsGAQUFBwIBFiZodHRwczov
L3d3dy5nbG9iYWxzaWduLmNvbS9yZXBvc2l0b3J5LzAIBgZngQwBAgIwCQYDVR0T
BAIwADBJBgNVHR8EQjBAMD6gPKA6hjhodHRwOi8vY3JsLmdsb2JhbHNpZ24uY29t
L2dzL2dzb3JnYW5pemF0aW9udmFsc2hhMmcyLmNybDAbBgNVHREEFDASghBjLnNu
aS5mYXN0bHkubmV0MB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAdBgNV
HQ4EFgQUtKi05Nur72AEab/ueagsP+smrGAwHwYDVR0jBBgwFoAUlt5h8b0cFilT
HMDMfTuDAEDmGnwwDQYJKoZIhvcNAQELBQADggEBAIO4QcnKsWyMvfjZj4QMg1ao
31XuY7jRiG2/a+S39JYEIS+16GXiTRfKJMk5dNKK30kRU+uPxBal5HS/i43ZRmY2
0iQG/tMLoVoTPUzxbgiIvgFIvjNG6vefiza+C83AY1Vz8HOcAAE3AM7efqYo0XdV
xlvOkdinqGDwERkZyKQ4mIDqEeU6wPHLTKf+wLnqcYxyeA4DK6Cd7v0NHMBm02L2
ZMf8iW1OZSy+uKswqSIedmmyko/tuO6gNA7Zs/pS5rjs6VH0OE6TlMIxvH/w0dj7
n8F/e1mhjp73CMV77MAIyxnnorM/Z58reWF/VGgOU89y4OdUugHIZ4F7fDTfpTU=
-----END CERTIFICATE-----
subject=/C=US/ST=California/L=San Francisco/O=Fastly, Inc./CN=c.sni.fastly.net
issuer=/C=BE/O=GlobalSign nv-sa/CN=GlobalSign Organization Validation CA - SHA256 - G2
---
No client certificate CA names sent
---
SSL handshake has read 3133 bytes and written 444 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES128-GCM-SHA256
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES128-GCM-SHA256
    Session-ID: 121F8DE0BB674CBFD769C9F58D95C82B445DF3DB2C09B8165B0737E8633C7C41
    Session-ID-ctx: 
    Master-Key: F565E8B8A2C6C02BF7A0343B4BEFFAFCCC59E05AE1F639DBCBF06BA38C5D0335C55D27055CCAF0670B595C425251E04E
    TLS session ticket lifetime hint: 1200 (seconds)
    TLS session ticket:
    0000 - 67 5f 37 e4 74 38 4e 3e-d4 ab 77 21 ea e1 f3 1c   g_7.t8N>..w!....
    0010 - 33 2d ce 5f 52 c3 06 4a-9b 1c 6b 0d 71 20 63 ca   3-._R..J..k.q c.
    0020 - 1a 30 9c 42 b2 c1 66 27-72 a1 fc f6 6f b6 14 16   .0.B..f'r...o...
    0030 - 17 ea 04 3a fa bf ea 1e-be 7b 6f 2b 6d aa f3 5e   ...:.....{o+m..^
    0040 - 65 8a 92 7b 3a ea 94 51-51 a4 84 fa 05 bf c8 8b   e..{:..QQ.......
    0050 - a8 da 0a 54 fc 40 d2 98-48 67 96 5f 64 93 bf 55   ...T.@..Hg._d..U
    0060 - 1c 59 13 d9 38 16 67 3f-44 82 9e 43 5f 65 9f 1b   .Y..8.g?D..C_e..
    0070 - 63 fc 12 c0 39 a9 be 75-10 70 ce 2e 4c 1d fe 25   c...9..u.p..L..%
    0080 - e8 7c fe 0b 64 36 6a 56-a2 18 bb 52 1a 99 37 1b   .|..d6jV...R..7.
    0090 - f0 c3 cc 29 27 b3 04 9d-5e 65 5c b3 fb 51 1c ca   ...)'...^e\..Q..

    Start Time: 1512407933
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
^C
```

**Comment by mikestankavich** [comment]
I've been having the same problem with releases.hashicorp.com from my dev macbook running El Cap 10.11.6. I noted that if I use a full path referring to the version of openssl installed by brew the openssl client connect test works. Maybe that's a clue? 

```
$ python --version; python -c "import ssl; print ssl.OPENSSL_VERSION"
Python 2.7.14
OpenSSL 1.0.2n  7 Dec 2017

$ openssl s_client -connect releases.hashicorp.com:443
CONNECTED(00000003)
51666:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:/BuildRoot/Library/Caches/com.apple.xbs/Sources/OpenSSL098/OpenSSL098-59.60.2/src/ssl/s23_clnt.c:593:

$ /usr/local/opt/openssl/bin/openssl s_client -connect releases.hashicorp.com:443
CONNECTED(00000003)
depth=2 C = BE, O = GlobalSign nv-sa, OU = Root CA, CN = GlobalSign Root CA
verify return:1
depth=1 C = BE, O = GlobalSign nv-sa, CN = GlobalSign CloudSSL CA - SHA256 - G3
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "Fastly, Inc", CN = s.ssl.fastly.net
verify return:1
---
Certificate chain
 0 s:/C=US/ST=California/L=San Francisco/O=Fastly, Inc/CN=s.ssl.fastly.net
   i:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign CloudSSL CA - SHA256 - G3
 1 s:/C=BE/O=GlobalSign nv-sa/CN=GlobalSign CloudSSL CA - SHA256 - G3
   i:/C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA
---
```

FWIW I also found that if I use a task var to set the python interpreter to python3 for the get_url in question it works. 
```
 - name: download terraform...
  get_url:
    url: '{{terraform_url}}'
    dest: '{{ role_path }}/files/{{ terraform_zip }}'
    checksum: '{{terraform_checksum}}'
  become: no
  delegate_to: localhost
  # this is an exceptionally annoying and stupid workaround for TLS1 errors on osx el cap
  # https://github.com/ansible/ansible/issues/33417
  # todo: find a better way to solve this!
  vars:
    ansible_python_interpreter: python3
```

**Comment by chuckyz** [comment]
That's.... annoying!

This is kinda outside of Ansible though, but for reference sake, just running `brew link openssl` *might* work?

**Comment by mikestankavich** [comment]
I suspect that you're right that brew link would work if brew didn't block it from being linked :( And no, --force doesn't override that block. 
```
$ brew link --force openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

As you say, this is kind of outside Ansible. I'm OK with continuing to use workarounds until I can upgrade my OS.

**Comment by bjoernalbers** [comment]
Ok, I'm gonna close this issue since its outside of Ansible.

**Comment by 1ambda** [comment]
This is brew version of ansible's problem.

I am using OSX and had the same error in ansible 2.4.3.0 (installed via `brew install ansible`)
After switching ansible installed by `pip install ansible`, it works.

Hope this would be helpful

**Comment by a0s** [comment]
Unfortunately pip's version not working properly too. An error is still here

```
- hosts: localhost
  connection: local
```

For python2
```yaml
- name: Fetch last commit in mobile branch {{ mobile_branch }}
      uri:
        url: "https://api.github.com/repos/{{ mobile_repo }}/git/refs/heads/{{ mobile_branch }}?access_token={{ github_token }}"
        status_code: 200
        validate_certs: false
      register: github_mobile_branch
```

fatal: [127.0.0.1]: FAILED! => {"changed": false, "content": "", "msg": "Status code was not [200]: Request failed: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>", "redirected": false, "status": -1, "url": "blablabla"}


For python3: 
```yaml
- name: Fetch last commit in mobile branch {{ mobile_branch }}
      uri:
        url: "https://api.github.com/repos/{{ mobile_repo }}/git/refs/heads/{{ mobile_branch }}?access_token={{ github_token }}"
        status_code: 200
        validate_certs: false
      register: github_mobile_branch      
      vars:
        ansible_python_interpreter: python3
```

fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for api.github.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl. The exception msg was: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)."}

```sh
> brew list | grep ansible
> pip list | grep ansible
ansible (2.4.3.0)
> which ansible
/usr/local/bin/ansible
> /usr/local/bin/ansible --version
ansible 2.4.3.0
  config file = /Users/a0s/.ansible.cfg
  configured module search path = [u'/Users/a0s/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Feb  6 2018, 20:03:31) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```
