### ISSUE TITLE
The module ios_vlan always assume the interface is in access mode

### ISSUE THREAD

**Issue by kefiras** [ansible/ansible#33415]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ios_vlan

##### ANSIBLE VERSION
```
ansible 2.4.1.0                                                                                                   
  config file = /home/root/Public_scripts/Ansible/ansible.cfg                                                     
  configured module search path = [u'/home/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules'] 
  ansible python module location = /usr/lib/python2.7/site-packages/ansible                                       
  executable location = /usr/bin/ansible                                                                          
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]                 

```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/root/Public_scripts/Ansible/ansible.cfg) = [u'/home/root/.ansible/hosts']  
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/root/Public_scripts/Ansible/ansible.cfg) = True                
DEFAULT_STDOUT_CALLBACK(/home/root/Public_scripts/Ansible/ansible.cfg) = skippy                    
HOST_KEY_CHECKING(/home/root/Public_scripts/Ansible/ansible.cfg) = False                           
```

OS / ENVIRONMENT
OS: RH 7.4
Trying to manage Cisco 3750E with IOS 15.0(2)SE10a

##### SUMMARY
The module always assumes the port is in access mode. I believe it should be at least option to choose a trunk ('switchport mode trunk') and add/remove vlans to it.

##### STEPS TO REPRODUCE
Run the playbook below

```
---                                         
- hosts: ios                                
  gather_facts: False                       
  connection: local                         
  vars:                                     
    cli:                                    
      username: root                        
                                            
  tasks:                                    
    - name: add vlan                        
      ios_vlan:                             
        vlan_id: 333                        
        name: testvlan                      
        state: present                      
    - name: add interface to vlan           
      ios_vlan:                             
        vlan_id: 333                        
        interfaces:                         
          - GigabitEthernet1/0/41           


```

##### EXPECTED RESULTS

It should be able to choose the port type (access or trunk)

##### ACTUAL RESULTS
The module always configure the port in access mode , ie.
```
Current configuration : 154 bytes       
!                                       
interface GigabitEthernet1/0/41         
 switchport access vlan 333             
 switchport trunk encapsulation dot1q   
 switchport mode access                 
 shutdown                               
 no cdp enable                          
end                                     
                                        

```
