### ISSUE TITLE
user:  fails if group already exists (non-idempotent behaviour)

### ISSUE THREAD

**Issue by dch** [ansible/ansible#3341]
This example fails using devel branch as of 20130625:

Obviously re-ordering this specific playlist can avoid the issue, but if these are in separate playlists, then this would not be an option.

``` yaml
#

---
- hosts: azure
  user: ubuntu
  sudo: yes
  tasks:  
    - name: ensure system groups are present
      group: name=$item state=present
      with_items:
         - admin
         - ansible

    - name: ensure sudoers.d is enabled
      lineinfile: dest=/etc/sudoers state=present backup=yes regexp='^#includedir /etc/sudoers.d' line='#includedir /etc/sudoers.d'

    - name: set up password-less sudo for admin users
      copy: content='%ansible ALL=(ALL) NOPASSWD:ALL' dest=/etc/sudoers.d/ansible owner=root group=root mode=0440

    - name: create ansible user if missing
      user: name=ansible password=* createhome=yes system=yes state=present groups=ansible uid=999
```

output is similar to the below:

``` ansible
ansible-playbook playbooks/azure.yml -vK                                                                            master✭  ✭ ✚ ✱
sudo password:
 ______________
< PLAY [azure] >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


 _________________
< GATHERING FACTS >
 -----------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [fubaa.cloudapp.net]
 ________________________________________
< TASK: ensure system groups are present >
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [fubaa.cloudapp.net] => (item=admin) => {"changed": false, "gid": 111, "item": "admin", "name": "admin", "state": "present", "system": false}
changed: [fubaa.cloudapp.net] => (item=ansible) => {"changed": true, "gid": 1001, "item": "ansible", "name": "ansible", "state": "present", "system": false}
 ___________________________________
< TASK: ensure sudoers.d is enabled >
 -----------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


ok: [fubaa.cloudapp.net] => {"changed": false, "msg": ""}
 _________________________________________________
< TASK: set up password-less sudo for admin users >
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


changed: [fubaa.cloudapp.net] => {"changed": true, "dest": "/etc/sudoers.d/fubaa", "gid": 0, "group": "root", "md5sum": "14a7e578a5019c7507aae16d7a33782a", "mode": "0440", "owner": "root", "size": 31, "src": "/home/ubuntu/.ansible/tmp/ansible-1372177506.53-197186445607964/source", "state": "file", "uid": 0}
 ______________________________________
< TASK: create ansible user if missing >
 --------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [fubaa.cloudapp.net] => {"failed": true, "name": "ansible", "rc": 9}
msg: useradd: group ansible exists - if you want to add this user to that group, use -g.


FATAL: all hosts have already failed -- aborting
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


           to retry, use: --limit @/var/tmp/ansible/azure.retry

fubaa.cloudapp.net     : ok=4    changed=2    unreachable=0    failed=1
```
