### ISSUE TITLE
templating not allowed in roles:

### ISSUE THREAD

**Issue by iffy** [ansible/ansible#3342]
I have two files:

``` yaml
# oneoff.yml
# to use me, do:
#
#   ansible-playbook oneoff.yml -e "my_role=rolethatyouwant"
#

---
- hosts: all
  sudo: True
  roles:
    - "{{ my_role }}"
```

``` yaml
# main.yml
- name: do stuff
  action: command /bin/echo {{ my_role }}
```

When I run this: `ansible-playbook oneoff.yml -i hosts -e my_role=webv3 -v`
I get this:

```
(venv)[vagrant@localhost ansible]$ ansible-playbook oneoff.yml -i hosts -e my_role=webv3 -v
ERROR: cannot find role in /vagrant/ansible/roles/{{my_role}} or /vagrant/ansible/{{my_role}}
```
