### ISSUE TITLE
ec2_lc does not work on 2.4.2.0 with adding volumes

### ISSUE THREAD

**Issue by Sdhowell3** [ansible/ansible#33445]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

```
2.4.2.0
```

##### OS / ENVIRONMENT

OSX 10.13.1

##### SUMMARY

Not able to add volumes nor user data to launch configuration

##### STEPS TO REPRODUCE

```yaml
  - name: Set current date and time
    shell: 'date +%Y%m%d-%H%M'
    register: current_timestamp

  - set_fact: 
      current_run_timestamp: "{{ current_timestamp.stdout }}"

  - debug:
      msg: "fit-formula11-rtb-{{current_run_timestamp}}"

  #- debug:
  #   msg: "{{ asg_facts.results[0].instances[0].instance_id }}"

  - name: Find Latest ec2 ami
    ec2_ami_find:
      region: us-east-1
      owner: 'redacted'
      name: 'fit-formula11-rtb-*'
      sort: 'creationDate'
      sort_order: descending
      sort_end: 1 
      no_result_action: fail 
    register: ami_find

  - debug:
      msg: "{{ ami_find.results[0].ami_id }}"

  - name: Create Launch Configuration
    ec2_lc:
      region: "us-east-1" 
      name: "fit-formula11-rtb-{{ current_run_timestamp }}" 
      image_id: "{{ ami_find.results[0].ami_id }}"
      instance_type: "c3.xlarge"
      security_groups: "sg-1c4a8166,sg-65e52e1f" 
      key_name: "pro-aws-devops"
      instance_profile_name: "fit-formula11"
      #assign_public_ip: "{{ ec2_lc_public_ip }}"
      instance_monitoring: yes
      volumes:
      - device_name: "/dev/sda1"
        volume_type: "gp2"
        volume_size: 30
        iops: 3000
        delete_on_termination: true
      user_data: '{
                    "autoScalingGroup": "fit-formula11-events"
                  s}"'
    register: ec2_lc.name
```

##### EXPECTED RESULTS

I am expecting a volume added to the launch configuration along with the user data 

##### ACTUAL RESULTS

```
changed: [localhost] => {
    "arn": "arn:aws:autoscaling:us-east-1:816075724885:launchConfiguration:9de1ecb8-ea5a-4991-93c4-2633aed62fca:launchConfigurationName/fit-formula11-events-20171201-0007",
    "changed": true,
    "created_time": "2017-12-01 06:07:48.355000+00:00",
    "image_id": "ami-bd62ffc7",
    "instance_type": "c3.xlarge",
    "invocation": {
        "module_args": {
           ,
            "security_token": null,
            "spot_price": null,
            "state": "present",
            "user_data": null,
            "user_data_path": null,
            "validate_certs": true,
            "volumes": null,
            "vpc_id": null
        }
    }
```
I edited out the information that isn't needed but as you can see the "volumes" is null even though I have it listed above in my task.
