### ISSUE TITLE
Task register is different when using with_dict

### ISSUE THREAD

**Issue by MrMMorris** [ansible/ansible#33449]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Stat module

##### ANSIBLE VERSION

```
ansible 2.0.0.2
```

##### CONFIGURATION
```
[defaults]
host_key_checking=False
display_skipped_hosts=False
force_handlers=True
hostfile=inventory/ec2.py
retry_files_enabled=False
deprecation_warnings=False
ansible_managed = This file is managed by ansible, don't make changes here - they will be overwritten.
timeout = 20

[ssh_connection]
pipelining=True
ssh_args = -o ForwardAgent=yes -o ControlMaster=no -o StrictHostKeyChecking=no

[privilege_escalation]
become=yes
become_method=sudo
```

##### OS / ENVIRONMENT
OSX 10.10.5

##### SUMMARY
The `register` dict is not the same without using `with_dict` on the task as it is with using it. 

##### STEPS TO REPRODUCE
Dict:
```yaml
sandbox_devs:
  testserver2:
    revision: blah
```

Using `with_dict`:
```yaml
- stat:
    path: "/opt/consumer/{{ item.key }}/.git"
  with_dict: "{{ sandbox_devs }}"
  register: chkfile
  tags:
    - sandbox

- debug: var=chkfile

- name: remove local modifications
  command: "git reset --hard"
  args:
    chdir: "/opt/consumer/{{ item.key }}"
  with_dict: "{{ sandbox_devs }}"
  when: chkfile.stat.exists
```

Not using `with_dict`:
```yaml
- stat:
    path: "/opt/consumer/testserver2/.git"
  register: chkfile

- debug: var=chkfile

- name: remove local modifications
  command: "git reset --hard"
  args:
    chdir: "/opt/consumer/testserver2"
  when: chkfile.stat.exists
```

##### EXPECTED RESULTS
Using `with_dict` runs without error

##### ACTUAL RESULTS

Using `with_dict`:
```
TASK [consumer : stat] *****************************************************
ok: [107.23.11.55] => (item={'value': {u'revision': u'blah'}, 'key': u'testserver2'})

TASK [consumer : debug] ****************************************************
ok: [107.23.11.55] => {
    "msg": {
        "changed": false,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_no_log": false,
                "changed": false,
                "invocation": {
                    "module_args": {
                        "checksum_algorithm": "sha1",
                        "follow": false,
                        "get_checksum": true,
                        "get_md5": true,
                        "path": "/opt/consumer/testserver2/.git"
                    },
                    "module_name": "stat"
                },
                "item": {
                    "key": "testserver2",
                    "value": {
                        "revision": "blah"
                    }
                },
                "stat": {
                    "exists": false
                }
            }
        ]
    }
}

TASK [consumer : remove local modifications] *******************************
fatal: [107.23.11.55]: FAILED! => {"failed": true, "msg": "ERROR! The conditional check 'chkfile.stat.exists' failed. The error was: ERROR! error while evaluating conditional (chkfile.stat.exists): ERROR! 'dict object' has no attribute 'stat'\n\nThe error appears to have been in '/Users/mmorris/Work/ansible/roles/consumer/tasks/sandbox.yml': line 42, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: remove local modifications\n  ^ here\n"}
```

Not using `with_dict`:
```
TASK [consumer : stat] *****************************************************
ok: [107.23.11.55]

TASK [consumer : debug] ****************************************************
ok: [107.23.11.55] => {
    "msg": {
        "changed": false,
        "stat": {
            "exists": false
        }
    }
}

TASK [consumer : remove local modifications] *******************************

PLAY RECAP *********************************************************************
107.23.11.55              : ok=2
```
