### ISSUE TITLE
openssl_certificate should return assertion result

### ISSUE THREAD

**Issue by krissi** [ansible/ansible#33457]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

openssl_certificate

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/chaase/repos/ansible/ansible.cfg
  configured module search path = [u'/home/chaase/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

openssl_certificate in with assertonly provider does not return an explicit assertion result which can be used to e.g. renew the certificate

##### STEPS TO REPRODUCE

```yaml
- name: Verify certificate
  openssl_certificate:
    provider: assertonly
    path: /etc/ssl/{{inventory_hostname}}.cert.pem
    state: present
    subject:
     CN: "{{inventory_hostname}}"
    subject_alt_name:
      - "DNS:{{inventory_hostname}}"
      - "DNS:{{inventory_hostname_short}}"
    valid_in: 604800 # 7 days
    issuer:
      O: ACME Corp
  register: cert_verify
  failed_when: false

- debug: "msg={{cert_verify}}"
```

##### EXPECTED RESULTS

```yaml
ok: [somehost.example.com] => {
    "msg": {
        "changed": false, 
        "failed": false, 
        "failed_when_result": false, 
        "assertion_fulfilled": false, 
        "msg": "Invalid subjectAltName component (got ['DNS:somehost.example.com'], expected all of ['DNS:somehost.example.com', 'DNS:somehost'] to be present)"
    }
}
```
(added `assertion_fulfilled`)
##### ACTUAL RESULTS

```yaml
ok: [somehost.example.com] => {
    "msg": {
        "changed": false, 
        "failed": false, 
        "failed_when_result": false, 
        "msg": "Invalid subjectAltName component (got ['DNS:somehost.example.com'], expected all of ['DNS:somehost.example.com', 'DNS:somehost'] to be present)"
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/crypto/openssl_certificate.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssl_certificate.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @MarkusTeufelberger @Spredzy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MarkusTeufelberger** [comment]
The `"failed": true` part is not enough? That's what I wrote this provider for...

Why would you need a custom field in the output additionally to the module failing?

**Comment by krissi** [comment]
It does not have the `failed` attribute set to `true`, maybe because I override using `failed_when: false`. I need to do this because I only want to capture the module output and not abort the play

Here is the output of an fulfilled and an unfulfilled assertion:

```yaml
ok: [foo.example.com] => {
    "msg": {
        "changed": false, 
        "csr": null, 
        "failed": false, 
        "failed_when_result": false, 
        "filename": "/etc/ssl/foo.example.com.cert.pem", 
        "privatekey": null
    }
}
```

```yaml
ok: [foo.example.com] => {
    "msg": {
        "changed": false, 
        "failed": false, 
        "failed_when_result": false, 
        "msg": "Certificate is not valid in 55604800 seconds from now (20190909000706Z) - notBefore: 20171204101452Z - notAfter: 20171218101452Z"
    }
}
```

**Comment by MarkusTeufelberger** [comment]
Yes, you are overriding the "failed" attribute to always be False instead of setting `ignore_errors: true`, which seems like the more appropriate thing to do to me (this would continue the play with a failed task).

**Comment by krissi** [comment]
I see. 
In my scenario (checking if a certificate needs renew and renew it based on this result), it is not an error if a renew is needed. When using `ignore_errors`, the output is red which is distracting.

I grant that the current behaviour of erroring matches the name `assertonly`, which is not "verify" or alike. But I and probably many others will abuse this module to verify the current cert and act on the result and hide the error in some way.

Maybe it would be better for these users to have a verify provider which does the same but does not fail when the assertion is not met but for system errors like "No such file or directory" or OpenSSL/python errors which adds a benefit itself I guess. When having a explicit `assertion_fulfilled` (or alike) one can use failed_when to recreate the old behaviour.

Instead of adding an extra variable, maybe the `changed` variable could be used for this. This leaves the `failed` state clear for non-assertion errors.

What do you think of this?

**Comment by MarkusTeufelberger** [comment]
I don't agree.

The certificate not following spec (e.g. because it needs to be renewed) is something that should trigger an action and since "assertonly" isn't capable of actually performing an action, the only thing left to do for the module is to fail. Hiding this behaviour away is not something that I want to encourage. If you still want to trigger further actions down the line, you need to allow failures, do the necessary action(s) and then maybe have a second openssl_certificate call which then would succeed or actually fail (because your action(s) afterwards were not sufficient or went wrong).

I don't want to invent new output parameters when there is a clear and standard solution to this issue (fail hard or ignore_errors and act on the foo.failed attribute of the openssl_certificate task).

Alternatively you could write a provider for your renewal process and (if you want to) also commit it to Ansible upstream. I'm more than willing to review code or help you with your PR. Selfsigned and letsencrypt were just the two that seemed the most obvious (and that @spredzy already had written), there could (and maybe should) be more.

Initially I also though about a "changed_instead_of_failed" boolean parameter to assertonly (or however it would end up being named), but I decided against it since there is a clear meaning what "changed" and "failed" mean in Ansible (an expired certificate isn't "changed") and just getting a line printed in yellow or red in a log is not enough to break this contract with the user in my opinion.

**Comment by krissi** [comment]
After digging a bit deeper I decided to use `check_mode: yes` for this. This offers a nice way to get the needed result without hacks (and without panic reactions on renewal day ;-) )
I also thought about pushing the all methods of `AssertOnlyCertificate` except `generate` into a superclass and creating another subclass with `AssertOnlyCertificate`'s `check` method as `generate`. I think we don't want this either.
If we can agree on the current check behavior as expected I am happy to open a PR for documentation.

**Comment by MarkusTeufelberger** [comment]
What exactly are you meaning with "agree on the current check behavior as expected"? Currently it does not fail the module in check mode if a check fails. This is intended (for the non-"assertonly" providers) because it can't know if they would succeed or fail to get a new certificate. A better behavior would be to fail in check mode too if the assertonly provider is used, because it is nearly impossible to recover from this situation with this provider in non-check mode.

All these workarounds just to not see red colors going by which are ignored and acted upon anyways? :astonished:

**Comment by krissi** [comment]
> A better behavior would be to fail in check mode too if the assertonly provider is used, because it is nearly impossible to recover from this situation with this provider in non-check mode.
The opposite of this I meaned with "agree on the current check behavior as expected" ;) 

The workarounds are not about the red colors but about making failure a standard non-exceptional status. Lets take your code example, first assert on the existing certificate and when the assertion (or anything else) fails, renew the certificate:

```yaml

# How to use the assertonly provider to implement and trigger your own custom certificate generation workflow:
- name: Check if a certificate is currently still valid, ignoring failures
  openssl_certificate:
    path: ./test.cert.pem
    provider: assertonly
    has_expired: False
  ignore_errors: True
  register: validity_check

- name: Run custom task(s) to get a new, valid certificate in case the initial check failed
  command: touch test.cert.pem
  when: validity_check.failed
```

This works when everything works as expected. But if an error occurs there is no way for `openssl_certificate` to fail which does not mean "please issue a new cert".

Just uninstall `pyopenssl` or run `chmod -r test.cert.pem`:

```                                                                                                                              
PLAY [Test] *********************************************************************************************************************************************************************************************************

TASK [Gathering Facts gather_subset=all, gather_timeout=10] *********************************************************************************************************************************************************
ok: [localhost]

TASK [Check if a certificate is currently still valid, ignoring failures has_expired=True, path=./test.cert.pem, provider=assertonly] *******************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "The python pyOpenSSL library is required"}
...ignoring

TASK [Run custom task(s) to get a new, valid certificate in case the initial check failed _raw_params=touch test.cert.pem] ******************************************************************************************
 [WARNING]: Consider using file module with state=touch rather than running touch

changed: [localhost]

PLAY RECAP **********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

When using ACME to issue a new cert, this setup will trigger some rate limiting pretty quickly. When automatically buying certificates this can get even worse. While the latter is not a thing now, I hope the latter will be in the near future.

**Comment by MarkusTeufelberger** [comment]
You'd need to add another task afterwards:

````
# How to use the assertonly provider to implement and trigger your own custom certificate generation workflow:
- name: Check if a certificate is currently still valid, ignoring failures
  openssl_certificate:
    path: ./test.cert.pem
    provider: assertonly
    has_expired: False
  ignore_errors: True
  register: validity_check

- name: Run custom task(s) to get a new, valid certificate in case the initial check failed
  command: touch test.cert.pem
  when: validity_check.failed

- name: Make sure the certificate is correct now
  openssl_certificate:
    path: ./test.cert.pem
    provider: assertonly
    has_expired: False
````

**Comment by krissi** [comment]
That does not solve the problem. After renewing the certificate (which not necessarily needs `pyopenssl` to stick to my example) the certificate will be renewed and valid. Of course step 3 fails aswell, but the damage is already done at that point. 
If we take the example with `chmod -r test.cert.pem` which is maybe set daily in some faulty cronjob, step 3 might be successful if the renewal process resets the file permissions.
These are only two examples, there might be "Too many open files" errors, IO errors, etc. As long the module output to act on means "Hey, the certificate needs renewal. Or maybe something went wrong, not sure what to do, just issue a new cert", I have a bad feeling on trusting its output.

**Comment by MarkusTeufelberger** [comment]
Hm, ok I understand the problem now and I agree with you - risking to issue a certificate if something else is broken in your module is not the best way forward.

I would still fail the module, but something like `checks_failed: true` in the output of any provider might be a reasonable field to have, so one knows why the module failed.

**Comment by krissi** [comment]
So something like the following is needed after the assertion? I think this is unintuitive and not very ansible-esqe.

```yaml
    - fail:
       msg: "{{validity_check.msg}}"
       when: not validity_check.checks_failed
```

Maybe it would better to add a parameter like `on_assertion_failed: fail|change|ok` or `fail_mode: True|False` or `assertion_mode: hard|soft` or something like it. When deprecating `None` for this parameter there is an migration path for current users as well.

**Comment by MarkusTeufelberger** [comment]
No, it would be

````
# How to use the assertonly provider to implement and trigger your own custom certificate generation workflow:
- name: Check if a certificate is currently still valid, ignoring failures
  openssl_certificate:
    path: ./test.cert.pem
    provider: assertonly
    has_expired: False
  ignore_errors: True
  register: validity_check

- name: Run custom task(s) to get a new, valid certificate in case the initial check failed
  command: touch test.cert.pem
  when: not validity_check.checks_failed

- name: Make sure the certificate is correct now
  openssl_certificate:
    path: ./test.cert.pem
    provider: assertonly
    has_expired: False
````
