### ISSUE TITLE
digital_ocean_tag has stopped working

### ISSUE THREAD

**Issue by herkyl** [ansible/ansible#33459]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
digital_ocean_tag

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
```
[defaults]
inventory    = ./inventory/hosts
hostfile     = ./inventory/hosts
remote_port  = 9222
ask_sudo_pass= True
# Required so `sudo: yes` does not lose the environment variables, which hold the ssh-agent socket
sudo_flags   = -HE
ansible_managed = This file is managed by ansible, don't make changes here - they will be overwritten.
gathering = smart
gather_subset = !all
retry_files_enabled = False
roles_path = ~/ansible_galaxy_roles

[ssh_connection]
ssh_args     = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ssh-%r@%h:%p
```

##### OS / ENVIRONMENT
Tried on OSX and Ubuntu

##### SUMMARY
When trying to tag a droplet I get this error:
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "error tagging resource 'xxxxxxx': param is missing or the value is empty: resources"}
```

##### STEPS TO REPRODUCE
```yaml
- name: creating a new DigitalOcean droplet
  digital_ocean:
    state: present
    command: droplet
    name: "{{ droplet_name }}"
    api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    size_id: "{{ size_id }}"
    region_id: "{{ region_id }}"
    image_id: "{{ image_id }}"
    wait_timeout: 300
    private_networking: yes
    ssh_key_ids: "{{ lookup('pipe', 'python digitalocean/get_public_ssh_key_ids.py') }}"
  register: new_droplet

- name: tagging droplet
  digital_ocean_tag:
    api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
    name: general
    resource_id: "{{new_droplet.droplet.id}}"
    state: present
```

##### EXPECTED RESULTS
I expected it to tag my new droplet, it has been working for a while (a week ago as well).
The `api_token` and `resource_id` both are valid parameters.

##### ACTUAL RESULTS
I get an error:
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "error tagging resource 'xxxxxxx': param is missing or the value is empty: resources"}
```
