### ISSUE TITLE
Add server or dns_domain_name option to win_domain_group

### ISSUE THREAD

**Issue by candonov** [ansible/ansible#33467]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
win_domain_group

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /home/<user>/ansible/inventory/ansible.cfg
  configured module search path = [u'/home/<user>/ansible/library']
  ansible python module location = /home/<user>/.pyenv/versions/2.7.9/lib/python2.7/site-packages/ansible
  executable location = /home/<user>/.pyenv/versions/2.7.9/bin/ansible
  python version = 2.7.9 (default, Oct 19 2017, 10:30:31) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Ubuntu 16.04  -> Windows Server 2012 R2
##### SUMMARY

Need the ability to specify server/dns_domain_name for win_domain_group module

Trying to add win_domain_group from a Windows Server which has joined the domain.
Using Ansible manage user - Administrator on the Server but not an AD user.
On Windows Server on command line, logged in with the same Admin user:
this fails: Get-ADDomain -Credential (Get-Credential) 
this succeeds: Get-ADDomain -Server <MyDomainController> -Credential (Get-Credential)

##### STEPS TO REPRODUCE

```yaml
- name: Add group to the domain
  win_domain_group:
    name: "{{ my_groupname }}"
    domain_admin_password: "{{ encrypted_password }}"
    domain_admin_user: 'domain\user'
    path: 'OU=Groups,DC=domain ,DC=net'
    scope: domainlocal
```

##### EXPECTED RESULTS

Add the group to AD

##### ACTUAL RESULTS

```
fatal: [10.1.10.1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "failed to retrieve initial details for group <my_group>: Unable to contact the server. This may be because this server does not exist, it is currently down, or it does not have the Active Directory Web Services running."
}

```
