### ISSUE TITLE
Multiply and divide with // = 0

### ISSUE THREAD

**Issue by publicarray** [ansible/ansible#33506]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
Jinja2

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /Users/seb/git/dns-resolver/ansible.cfg
  configured module search path = [u'/Users/seb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

The jinja `//` operator always returns 0 when a number was first multiplied:

```
{{ 4 * 5 // 7 }} # returns 0
```

From: http://jinja.pocoo.org/docs/2.10/templates/#math
```
//
Divide two numbers and return the truncated integer result. {{ 20 // 7 }} is 2.
```
##### STEPS TO REPRODUCE

```yaml
---
- name: Multiply/Divide Test
  hosts: localhost
  tasks:
  - name: example use case
    command: echo "{{ansible_memtotal_mb|default(512, true) * unbound_optimise_memory|default(100, true) // 100 // 4 * 0.75}}"
    register: output
  - name: get result
    debug:
      var: output
  - name: minimal example
    command: echo "{{4 * 5 // 7}}"
    register: output
  - name: get result
    debug:
      var: output
  - name: actual results
    command: echo "{{4 * 5 / 7}}"
    register: output
  - name: get result
    debug:
      var: output
  - name: expected results
    command: echo "{{(4 * 5 / 7)|int}}"
    register: output
  - name: get result
    debug:
      var: output
```

##### EXPECTED RESULTS
```
{{4 * 5 // 7}} = 2
{{4 * 5 / 7}} = 2.85714285714
```
##### ACTUAL RESULTS

```
{{4 * 5 // 7}} = 0
{{4 * 5 / 7}} = 2.85714285714 # as expected
```
