### ISSUE TITLE
get_url doesn't remove temp file when force=yes and changed=no

### ISSUE THREAD

**Issue by ericcitaire** [ansible/ansible#33521]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
get_url

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /path/to/virtualenv/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /path/to/virtualenv/ansible/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Default configuration

##### OS / ENVIRONMENT
Ansible run on Ubuntu 16.04, managing RedHat 6.6

##### SUMMARY

get_url doesn't remove temporary file when `force=yes` and destination file checksum is equal to downloaded file checksum.

##### STEPS TO REPRODUCE
Just run this playbook:

```yaml
---
- hosts: all
  tasks:
  - get_url:
      url: http://www.acme.com/file.txt
      dest: /path/to/file.txt
      force: yes
```

##### EXPECTED RESULTS
Temporary file should be removed.

##### ACTUAL RESULTS
Temporary file is not removed.
