### ISSUE TITLE
Recreate docker volume in case if driver options were changed 

### ISSUE THREAD

**Issue by dpavlov** [ansible/ansible#33534]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker_volume

```
ansible 2.4.2.0
```

##### CONFIGURATION

ANSIBLE_SSH_CONTROL_PATH(/vagrant/ansible/ansible.cfg) = %(directory)s/%%h-%%p-%%r
CACHE_PLUGIN(/vagrant/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/vagrant/ansible/ansible.cfg) = ./cache/
CACHE_PLUGIN_TIMEOUT(/vagrant/ansible/ansible.cfg) = 7200
DEFAULT_BECOME(/vagrant/ansible/ansible.cfg) = True
DEFAULT_BECOME_USER(/vagrant/ansible/ansible.cfg) = root
DEFAULT_GATHERING(/vagrant/ansible/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/vagrant/ansible/ansible.cfg) = merge
DEFAULT_LOG_PATH(/vagrant/ansible/ansible.cfg) = /vagrant/ansible/ansible.log
DEFAULT_REMOTE_USER(/vagrant/ansible/ansible.cfg) = robot
DEFAULT_TIMEOUT(/vagrant/ansible/ansible.cfg) = 15
DEFAULT_VAULT_PASSWORD_FILE(/vagrant/ansible/ansible.cfg) = /vagrant/ansible/vault_password
HOST_KEY_CHECKING(/vagrant/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/vagrant/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

##### SUMMARY

Ansible does not update docker volume in case if driver options were changed
 
##### STEPS TO REPRODUCE

1. Create a role with single task which create a volume with driver options:
```yaml
---
- name: Create docker volume
  docker_volume:
    name: "test-volume"
    driver: vieux/sshfs
    driver_options:
      sshcmd: 'robot@host:/dir-original'
```
2 Run it

3 Update driver_options in task and run it again
```yaml
---
- name: Create docker volume
  docker_volume:
    name: "test-volume"
    driver: vieux/sshfs
    driver_options:
      sshcmd: 'robot@host:/dir-updated'
```

```yaml

```

##### EXPECTED RESULTS

Volume is recreated according to new options
##### ACTUAL RESULTS

Volume was not changed 

```

```
