### ISSUE TITLE
npm module is not installing dependencies locally from package.json

### ISSUE THREAD

**Issue by johnslay** [ansible/ansible#33555]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
npm

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 10

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
The task passes without installing node modules.

##### STEPS TO REPRODUCE

```yaml
---
# Install Node js
- name: add apt key for nodesource
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: add key for mongodb
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0C49F3730359A14518585931BC711F9BA15703C6

- name: add node repo
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_8.x {{ ansible_distribution_release }} main'
    update_cache: yes

- name: add mongo repo
  apt_repository:
    repo: 'deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse'
    update_cache: yes

- name: install packages
  apt: name={{ item }} state=present
  with_items:
    - nodejs
    - git
    - mongodb-org


#Clone Project
- name: Clone Project
  become: yes
  become_user: test
  git:
    repo: git@bitbucket.org:myproject/project.git
    dest: ~/project
    version: develop
    depth: 1
    force: true

#Install npm packages
- name: Install npm packages 
  npm: path=/home/test/project executable=/usr/bin/npm
 
#Start mongod
- name: start mongod
  service: name=mongod state=started
```

##### EXPECTED RESULTS
I expect to have a node_modules folder within the `project` directory where my `package.json` is located.

##### ACTUAL RESULTS

```
TASK [common : Install npm packages] **********************************************************************************
ok: [192.168.26.40] => {"changed": false, "failed": false}
```
