### ISSUE TITLE
Reuse the SSH connection for all tasks in a single playbook running

### ISSUE THREAD

**Issue by mingrammer** [ansible/ansible#33571]
##### ISSUE TYPE

 Feature Idea

##### COMPONENT NAME
SSH connection

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = ['/Users/ming/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.2 (default, Jul 17 2017, 16:44:45) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/Users/ming/go/src/github.com/sundaytoz/sql-notebook/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/ming/go/src/github.com/sundaytoz/sql-notebook/ansible.cfg) = ['/Users/ming/go/src/github.com/sundaytoz/sql-notebook/environments/local']

##### OS / ENVIRONMENT
macOS Sierra

##### SUMMARY
Is there a way of that reuse the SSH connection for all tasks? I have several tasks which need to connect to remote server via SSH. So, If I run the my playbook, I have to type the passwords for my ssh keys several times. (they have same SSH key) So, I'm finding a way for reusing the SSH connection across all tasks in a single playbook.

##### STEPS TO REPRODUCE
```yaml
...
  tasks:
    - name: upload static files
      synchronize:
        src: static,
        dest: "{{ ansible_env.HOME }}/sql-notebook"
        copy_links: yes

    - name: upload template files
      synchronize:
        src: template
        dest: "{{ ansible_env.HOME }}/sql-notebook"
    
    - name: upload SQL notebook binary
      synchronize:
        src: "{{ appname }}"
        dest: "{{ ansible_env.HOME }}/sql-notebook"
        
  post_tasks:
    - name: run SQL notebook web server
      args:
        chdir: "{{ ansible_env.HOME }}/sql-notebook"
      register: run_app
    - debug: msg="{{ run_app }}"
```

Please let me know a way for reducing the redundant tasks.
