### ISSUE TITLE
sefcontext doesn't change the context value

### ISSUE THREAD

**Issue by Ompragash** [ansible/ansible#33577]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

sefcontext

##### ANSIBLE VERSION

```
ansible 2.4.1.0

```

##### OS / ENVIRONMENT

Running Ansible on Fedora 25
Deploying to RHEL 7/Fedora 25

##### SUMMARY

When the playbook is executed it shows the particular task which uses `sefcontext` module is changed, but when the context value of the particular directory is unchanged(checked with `ls -Zd directory_path`).

##### STEPS TO REPRODUCE

```yaml
---
- hosts: hostname 
  become: True
  tasks:
  - name: Create a directory
    file:
      state: directory
      path: /tmp/vhost
  - name: Change context value
    sefcontext:
      target: '/tmp/vhost(/.*)?'
      setype: httpd_sys_content_t
      state: present
```

##### EXPECTED RESULTS

The context value of /tmp/vhost should be changed to httpd_sys_content_t
##### ACTUAL RESULTS

Context value remains unchanged

```
unconfined_u:object_r:user_tmp_t:s0 /tmp/vhost
```
