### ISSUE TITLE
SSLContext Error while creating a vmware_dvswitch.

### ISSUE THREAD

**Issue by 1NoOne1** [ansible/ansible#33602]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

- vmware_dvswitch

##### ANSIBLE VERSION

```
ansible --version
ansible 2.3.1.0
  config file = /home/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Jun 17 2014, 18:11:42) [GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
```

##### CONFIGURATION

- Nothing customized. I am using the default CFG settings.

##### OS / ENVIRONMENT

- CentOS Linux release 7.0.1406 (Core)

##### STEPS TO REPRODUCE

Trying to create a Virtual Distributed Switch in Vcenter using Module `vmware_dvswitch`. However, I am seeing the errors as below.

- I have the following setup in my environment.
```
1.  I have a Datacenter (aus6), and I am trying to create a vDS using ansible vmware module.

However, I am getting the errors.
```

```yaml
----
- name: VC
  hosts: local
  gather_facts: False
  user: root
  become: yes
  vars:
    vcenter: '10.70.200.10'
    user_vc: 'administrator@local.local'
    pass_vc: 'Vmware1!'


  tasks:
    - name: Create dvswitch
      local_action:
        module: vmware_dvswitch
        hostname: "{ vcenter }}"
        username: "{{ user_vc }}"
        password: "{{ pass_vc }}"
        datacenter_name: aus6
        switch_name: dvSwitch_test
        mtu: 1500
        uplink_quantity: 2
        discovery_proto: cdp
        discovery_operation: both
        #validate_certs: False
        state: present

```

##### EXPECTED RESULTS

- It should see a vDS gets created in the given Vcetner.
##### ACTUAL RESULTS
```yaml
ansible-playbook -i inventory/hosts playbooks/vc.yml -vvvv
Using /home/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: vc.yml ********************************************************************************************************************************************************************************************************************
1 plays in playbooks/vc.yml

PLAY [VC] ***************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create dvswitch] **************************************************************************************************************************************************************************************************************
task path: /home/ansible/playbooks/vc.yml:14
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_dvswitch.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1512519149.46-149882083193949 `" && echo ansible-tmp-1512519149.46-149882083193949="` echo /home/ansible/.ansible/tmp/ansible-tmp-1512519149.46-149882083193949 `" ) && sleep 0'
<localhost> PUT /tmp/tmpz1khb5 TO /home/ansible/.ansible/tmp/ansible-tmp-1512519149.46-149882083193949/vmware_dvswitch.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1512519149.46-149882083193949/ /home/ansible/.ansible/tmp/ansible-tmp-1512519149.46-149882083193949/vmware_dvswitch.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-lmoyerhltrfixspwzrhegdbconifnphc; /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1512519149.46-149882083193949/vmware_dvswitch.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1512519149.46-149882083193949/" > /dev/null 2>&1'"'"' && sleep 0'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "datacenter_name": "aus6",
            "discovery_operation": "both",
            "discovery_proto": "cdp",
            "hostname": "{ vcenter }}",
            "mtu": 1500,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "state": "present",
            "switch_name": "dvSwitch_test",
            "uplink_quantity": 2,
            "username": "administrator@local.local",
            "validate_certs": true
        }
    },
    "msg": "pyVim does not support changing verification mode with python < 2.7.9. Either update python or or use validate_certs=false"
}
        to retry, use: --limit @/home/ansible/playbooks/vc.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**I tried putting validate_certs: false, then I am seeing the SSLContext errors.** 

```yaml
ansible-playbook -i inventory/hosts playbooks/vc.yml -vvvv
Using /home/ansible/ansible.cfg as config file
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: vc.yml ********************************************************************************************************************************************************************************************************************
1 plays in playbooks/vc.yml

PLAY [VC] ***************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [Create dvswitch] **************************************************************************************************************************************************************************************************************
task path: /home/ansible/playbooks/vc.yml:14
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_dvswitch.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ansible
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ansible/.ansible/tmp/ansible-tmp-1512519112.09-18863385067008 `" && echo ansible-tmp-1512519112.09-18863385067008="` echo /home/ansible/.ansible/tmp/ansible-tmp-1512519112.09-18863385067008 `" ) && sleep 0'
<localhost> PUT /tmp/tmpX1g0q_ TO /home/ansible/.ansible/tmp/ansible-tmp-1512519112.09-18863385067008/vmware_dvswitch.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ansible/.ansible/tmp/ansible-tmp-1512519112.09-18863385067008/ /home/ansible/.ansible/tmp/ansible-tmp-1512519112.09-18863385067008/vmware_dvswitch.py && sleep 0'
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-uhhzttoiratrhuwnwyqzjxcjoildtquh; /usr/bin/python /home/ansible/.ansible/tmp/ansible-tmp-1512519112.09-18863385067008/vmware_dvswitch.py; rm -rf "/home/ansible/.ansible/tmp/ansible-tmp-1512519112.09-18863385067008/" > /dev/null 2>&1'"'"' && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_gnhTqb/ansible_module_vmware_dvswitch.py", line 214, in <module>
    main()
  File "/tmp/ansible_gnhTqb/ansible_module_vmware_dvswitch.py", line 207, in main
    vmware_dvswitch = VMwareDVSwitch(module)
  File "/tmp/ansible_gnhTqb/ansible_module_vmware_dvswitch.py", line 115, in __init__
    self.content = connect_to_api(module)
  File "/tmp/ansible_gnhTqb/ansible_modlib.zip/ansible/module_utils/vmware.py", line 331, in connect_to_api
AttributeError: 'module' object has no attribute 'SSLContext'

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_gnhTqb/ansible_module_vmware_dvswitch.py\", line 214, in <module>\n    main()\n  File \"/tmp/ansible_gnhTqb/ansible_module_vmware_dvswitch.py\", line 207, in main\n    vmware_dvswitch = VMwareDVSwitch(module)\n  File \"/tmp/ansible_gnhTqb/ansible_module_vmware_dvswitch.py\", line 115, in __init__\n    self.content = connect_to_api(module)\n  File \"/tmp/ansible_gnhTqb/ansible_modlib.zip/ansible/module_utils/vmware.py\", line 331, in connect_to_api\nAttributeError: 'module' object has no attribute 'SSLContext'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
        to retry, use: --limit @/home/ansible/playbooks/vc.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

```
