### ISSUE TITLE
[feature] jenkins_plugin: return plugin version when performing plugin install or upgrade

### ISSUE THREAD

**Issue by ham-360** [ansible/ansible#33605]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
jenkins_plugin

##### ANSIBLE VERSION
n/a

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT
n/a

##### SUMMARY
After using ansible to install a jenkins plugin, naturally you'd like to use ansible to configure that plugin.  All plugin config files require both the name of the plugin and the version, e.g. $JENKINS_HOME/credentials.xml :
```xml
<com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey plugin="ssh-credentials@2.1.16">
```
If you've installed the 'latest' plugin, you do not know this version.  The module responds only with plugin name and state 

##### STEPS TO REPRODUCE
```yaml
- name: ensure jenkins git plugin is installed
  jenkins_plugin:
    name: git
  register: git_plugin 

- name: configure git plugin
  debug:
    msg: "you are using git plugin version {{ git_plugin.version }}"
```

##### EXPECTED RESULTS
The version of the git plugin 

##### ACTUAL RESULTS
version not returned.  only name and state are returned
https://github.com/ansible/ansible-modules-extras/blob/devel/web_infrastructure/jenkins_job.py
