### ISSUE TITLE
Ansible Facts report wrong PVS free size

### ISSUE THREAD

**Issue by Riccardo1976** [ansible/ansible#33617]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
ansible 2.4.2.0
  config file = /home/ucm/AWX/common/ansible.cfg
  configured module search path = [u'/home/ucm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ucm/virtual/lib/python2.7/site-packages/ansible
  executable location = /home/ucm/virtual/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/ucm/AWX/common/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ucm/AWX/common/ansible.cfg) = -o StrictHostKeyChecking=no -o ControlMaster=auto -o ControlPersist=60s
CACHE_PLUGIN(/home/ucm/AWX/common/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/ucm/AWX/common/ansible.cfg) = /home/ucm/AWX/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/ucm/AWX/common/ansible.cfg) = 3600
DEFAULT_BECOME(/home/ucm/AWX/common/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/ucm/AWX/common/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/ucm/AWX/common/ansible.cfg) = root
DEFAULT_FORKS(/home/ucm/AWX/common/ansible.cfg) = 5
DEFAULT_GATHERING(/home/ucm/AWX/common/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/ucm/AWX/common/ansible.cfg) = [u'/home/ucm/AWX/inventory']
DEFAULT_LOG_PATH(/home/ucm/AWX/common/ansible.cfg) = /tmp/ansible/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/home/ucm/AWX/common/ansible.cfg) = /home/ucm/.ssh/id_rsa
DEFAULT_REMOTE_USER(/home/ucm/AWX/common/ansible.cfg) = ucm
DEFAULT_ROLES_PATH(/home/ucm/AWX/common/ansible.cfg) = [u'/home/ucm/AWX/common/roles']
DEFAULT_SCP_IF_SSH(/home/ucm/AWX/common/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/home/ucm/AWX/common/ansible.cfg) = skippy
DEFAULT_SUDO_USER(/home/ucm/AWX/common/ansible.cfg) = root
DEFAULT_VAULT_PASSWORD_FILE(/home/ucm/AWX/common/ansible.cfg) = /home/ucm/.vault_pass.txt
DEPRECATION_WARNINGS(/home/ucm/AWX/common/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/ucm/AWX/common/ansible.cfg) = /tmp/ansible
```

##### OS / ENVIRONMENT

RedHat Enterprise Linux 7
##### SUMMARY

While gathering info about available 'disk' space on lvm's i noticed a lot of them reporting 51(gb) free while this couldnt be.
##### STEPS TO REPRODUCE
Reproducable always (from RH6 to latest RH7) all machines report the same basically.

ansible -m setup all --limit=XXX -a 'filter=ansible_lvm'
```yaml
 {
    "ansible_facts": {
        "ansible_lvm": {
            "lvs": {
                "lvdata": {
                    "size_g": "45",
                    "vg": "XX849vg01"
                },
                "lvdocker": {
                    "size_g": "9",
                    "vg": "rootvg"
                },
                "lvhome": {
                    "size_g": "2",
                    "vg": "rootvg"
                },
                "lvroot": {
                    "size_g": "4",
                    "vg": "rootvg"
                },
                "lvswap": {
                    "size_g": "8",
                    "vg": "swapvg"
                },
                "lvtmp": {
                    "size_g": "2",
                    "vg": "rootvg"
                },
                "lvvar": {
                    "size_g": "2",
                    "vg": "rootvg"
                }
            },
            "pvs": {
                "/dev/sda2": {
                    "free_g": "51",
                    "size_g": "19",
                    "vg": "rootvg"
                },
                "/dev/sdb1": {
                    "free_g": "00",
                    "size_g": "8",
                    "vg": "swapvg"
                },
                "/dev/sdc1": {
                    "free_g": "00",
                    "size_g": "100",
                    "vg": "XX849vg01"
                }
            },
            "vgs": {
                "XX849vg01": {
                    "free_g": "00",
                    "num_lvs": "1",
                    "num_pvs": "1",
                    "size_g": "55"
                },
                "rootvg": {
                    "free_g": "0",
                    "num_lvs": "5",
                    "num_pvs": "1",
                    "size_g": "51"
                },
                "swapvg": {
                    "free_g": "0",
                    "num_lvs": "1",
                    "num_pvs": "1",
                    "size_g": "00"
                }
            }
        }
    },
    "changed": false
}


```

##### EXPECTED RESULTS

at ansible_lvm['pvs']['/dev/sda2']['free_g'] it reports 51. It should be

```
]$ sudo pvs
  PV         VG        Fmt  Attr PSize    PFree
  /dev/sda2  rootvg    lvm2 a--   <19,51g <1,51g
  /dev/sdb1  swapvg    lvm2 a--    <8,00g      0
  /dev/sdc1  XX849vg01 lvm2 a--  <100,00g <55,00g
```
at ansible_lvm['vgs']['XX849vg01']['free_g'] it reports 0 It should be
```
 sudo vgs
  VG        #PV #LV #SN Attr   VSize    VFree
  XX849vg01   1   1   0 wz--n- <100,00g <55,00g
  rootvg      1   5   0 wz--n-  <19,51g      0
  swapvg      1   1   0 wz--n-   <8,00g      0
```

##### ACTUAL RESULTS

As mentioned above, it reports whatever it finds behind the ','. 55,00 (vg) becomes 00. The 1.51g becomes 51g in case of the pv.
```

```
