### ISSUE TITLE
ec2: module ignores `count_tag` and creates new instances if subnets differ

### ISSUE THREAD

**Issue by bobobox** [ansible/ansible#33642]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/rpm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/rpm/sandbox/venv-ansible-2.4.0/lib/python2.7/site-packages/ansible
  executable location = /Users/rpm/sandbox/venv-ansible-2.4.0/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
All defaults

##### OS / ENVIRONMENT
Issue not platform specific

##### SUMMARY
The `count_tag` parameter on the ec2 module should maintain the `exact_count` number of ec2 instances which match the supplied tags, _wherever these ec2 instances are found within the account and region_. This was the behavior until version 2.4. 

As of version 2.4, the behavior changed, so that the match is no longer on 'count_tag' alone (as documented), but also on the `vpc_subnet_id`. Any instances with matching tags but in different subnets (even within the same VPC) are no longer counted as matching, and new instances are created. 

This is a serious bug for people maintaining EC2 infrastructure.

##### STEPS TO REPRODUCE

Create instance, like so:

```yaml
---

- hosts: localhost
  vars:
    subnet_id: subnet-1111111
  tasks:
    - ec2:
        count_tag: 
          Name: duplicate-test-1
          Department: FooBar
          Application: Baz
        exact_count: 1
        group_id: sg-000000
        image: ami-3bdd502c
        instance_tags:
          Name: duplicate-test-1
          Department: FooBar
          Application: Baz
        instance_type: t2.nano
        key_name: some.key.name
        region: us-east-1
        vpc_subnet_id: "{{ subnet_id }}"

```
Later, re-run playbook but use different subnet ID:

```yaml
---

- hosts: localhost
  vars:
    subnet_id: subnet-2222222
  tasks:
    - ec2:
        count_tag: 
          Name: duplicate-test-1
          Department: FooBar
          Application: Baz
        exact_count: 1
        group_id: sg-000000
        image: ami-3bdd502c
        instance_tags:
          Name: duplicate-test-1
          Department: FooBar
          Application: Baz
        instance_type: t2.nano
        key_name: some.key.name
        region: us-east-1
        vpc_subnet_id: "{{ subnet_id }}"

```

##### EXPECTED RESULTS
The `count_tags` and `exact_count` parameter should be respected, based on tags alone, and the running instance created in the first playbook run should be recognized as matching those parameters during the second playbook run.

##### ACTUAL RESULTS
As of version 2.4, the running instance with matching tags is no longer counted because it is in a different subnet, and a redundant instance is created.

##### COMMENTS
This behavior change was introduced without documentation, and is very problematic - the point of using `count_tags` and `exact_count` is to be able to maintain an instance or set of instances based on a tagging strategy - subnets may change over time, and often multiple instances will be distributed across subnets for resiliency. Silently including the subnet as an additional criterion for tag matching doesn't make a lot of sense, and breaks the expected behavior. 

If matching on tags + subnet is actually useful to someone, it would make more sense to make it an explicit parameter (although at that point, offering matching on VPCs, or instance types, or AMIs, or various other attributes which are not currently matched on should maybe come into consideration... and personally I feel that if that's necessary, then one's EC2 tagging strategy needs a revisit).

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @tgerla @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ryansb** [comment]
The behavior change was to make count_tags better handle AZ sensitive users, and to better protect against accidental termination. 

For your use case where you don't care about the subnet used, there are a few options like using `ec2_instance_facts` to check that the *total* instances matching those filters match as you expect. Alternately, if you need precisely one instance but it can be in any AZ, an autoscaling group (using ec2_asg/ec2_lc) of size one is another good option for maintaining across AZs.

**Comment by bobobox** [comment]
@ryansb It seems kind of user-hostile to suddenly change a behavior like this that can have serious effects on infrastructure. If the behavior is to be changed to benefit a specific set of users, it seems like it would make sense to make that a non-default option. I doubt that we're the only organization that has a lot of infrastructure which was built and is maintained based on the original behavior of the module...

**Comment by bkrubnzi** [comment]
I used `ec2-instance-facts` as suggested:
```
  - ec2_instance_facts:
      filters:
        "tag:Name": "{{ role1_instance_name }}"
        "tag:Space": "{{ Space }}"
        "instance-state-name": "running"
    register: found

  - name: Create the role_1 host group
    add_host: hostname={{ item.private_ip_address }} groupname=role1_nodes
    with_items: "{{ found.instances }}"
    when: found.instances|length == role1_instance_count|int

  - name: Provision the role1 nodes
    import_playbook: role1-ec2-instance/tasks/provision.yml
    when:
      - hostvars.localhost.found is defined
      - hostvars.localhost.found.instances|length < hostvars.localhost.role1_instance_count|int
````
But that's pretty clunky.  Does anyone have a better solution?

**Comment by woodcoder** [comment]
Hi, I was bitten by this change too.  I ended up using a variation on @bkrubnzi 's solution that is similar to how `exact_count`+`count_tags` used to work before it became sensitive to the availability zone (at least, when scaling up).

```
- ec2_instance_facts:
    filters:
      "tag:role": "{{ role_name }}"
      "instance-state-name": "running"
  register: running

- ec2:
    :
    count: "{{ exact_count|int - running.instances|length }}"
    instance_tags:
      role: "{{ role_name }}"
  register: ec2_info
  notify: refresh inventory
```
