### ISSUE TITLE
nmcli: Allow "generic" type for connections

### ISSUE THREAD

**Issue by MedicMomcilo** [ansible/ansible#33648]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/momcilo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  2 2017, 19:02:24) [GCC 7.2.1 20170829 (Red Hat 7.2.1-1)]
```

##### CONFIGURATION
No changes.

##### OS / ENVIRONMENT
Fedora/Centos

##### SUMMARY
Allow setting type "generic" for connections configuration.

##### STEPS TO REPRODUCE
One would be able to set connection type to "generic"

```yaml
- hosts: localhost

  tasks:

  - name: Configure new connection
    nmcli:
     state: present
     conn_name: lan
     autoconnect: yes
     ifname: ovs-lan
     type: generic
     ip4: 192.168.1.100/24
     gw4: 192.168.1.1
     dns4: 192.168.1.1
```

##### EXPECTED RESULTS
Connection of "generic" type gets created.

##### ACTUAL RESULTS
Not yet implemented.
