### ISSUE TITLE
nmcli: Add support for setting IP address to disabled/ignore for IPv4 and IPv6 retrospectively.

### ISSUE THREAD

**Issue by MedicMomcilo** [ansible/ansible#33647]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/momcilo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  2 2017, 19:02:24) [GCC 7.2.1 20170829 (Red Hat 7.2.1-1)]
```

##### CONFIGURATION
No changes.

##### OS / ENVIRONMENT
Fedora/Centos

##### SUMMARY
Add support for setting IP address to disabled/ignore for IPv4 and IPv6 retrospectively.

##### STEPS TO REPRODUCE
Use special keyword 'disabled' to set new ip4 or ip6 to none.

```yaml
- hosts: localhost

  tasks:

  - name: Configure ethernet bridge to OVS
    nmcli:
     state: present
     conn_name: enp1s0f0
     ip4: disabled
```

##### EXPECTED RESULTS
Connection gets altered so any IP addresses are removed.

##### ACTUAL RESULTS
Not yet implemented.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/nmcli.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nmcli.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @alcamie101
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@MedicMomcilo Thanks for reporting this issue. Could you please try following - 

```yaml
- name: Configure ethernet bridge to OVS
  nmcli:
     state: present
     conn_name: enp1s0f0
     ip4: ''

```

needs_info
