### ISSUE TITLE
apache2_module fails to enable dump_io

### ISSUE THREAD

**Issue by mmolinac** [ansible/ansible#33669]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
apache2_module

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/mmolinac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

[defaults]
allow_world_readable_tmpfiles=True

##### OS / ENVIRONMENT
macOS High Sierra 10.13.1
Darwin xxxxxxxxx.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

##### SUMMARY
I'm using apache2_module to enable / disable properly some Apache2 servers.
It seems that certain modules doesn't work because of the naming conventions they use.
If you try to work a module with underscores in it, but apache2ctl doesn't report it with underscores in its name, apache2_module fails (because IMHO, as it is expected, a special case).

##### STEPS TO REPRODUCE
With the following command, you'll get an error with the last module (dump_io):

```
- name: Apache2 modules
  apache2_module:
    name:  "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { name: 'headers', state: present }
    - { name: 'proxy', state: present }
    - { name: 'proxy_http', state: present }
    - { name: 'rewrite', state: present }
    - { name: 'ssl', state: present }
    - { name: 'dump_io', state: present }
```

##### EXPECTED RESULTS
There should be no errors, as the module is working fine

##### ACTUAL RESULTS
The output are something like:

```
TASK [profile_apache : Apache2 modules] ****************************************
ok: [deployment03] => (item={u'state': u'present', u'name': u'headers'})
ok: [deployment03] => (item={u'state': u'present', u'name': u'proxy'})
ok: [deployment03] => (item={u'state': u'present', u'name': u'proxy_http'})
ok: [deployment03] => (item={u'state': u'present', u'name': u'rewrite'})
ok: [deployment03] => (item={u'state': u'present', u'name': u'ssl'})
failed: [deployment03] (item={u'state': u'present', u'name': u'dump_io'}) => {"changed": false, "item": {"name": "dump_io", "state": "present"}, "msg": "Failed to set module dump_io to enabled: Module dump_io already enabled\n", "rc": 0, "stderr": "", "stderr_lines": [], "stdout": "Module dump_io already enabled\n", "stdout_lines": ["Module dump_io already enabled"]}
```

And I think this is because of apache2ctl not reporting the installed module name adequately (mind the lack of underscores in the following output):

```
# apache2ctl -M | egrep "(dump|proxy_http)"
 dumpio_module (shared)
 proxy_http_module (shared)
```

As you can see, proxy_http keeps its underscore in the report, but dump_io doesn't, and I think that's the problem.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/apache2_module.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/apache2_module.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @berendt @n0trax @robinro
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andreaso** [comment]
Yepp, looks like you are right in your diagnosis. The _apache2_module.py_ helper method `_module_is_enabled` does indeed parse the output of `apache2ctl -M`.

Except that I don't see _apache2ctl_ reporting anything wrong, the module's internal name really being _dumpio_. One could maybe argue that the file _/etc/apache2/mods-available/dump_io.load_ is improperly named. One could maybe also argue that the Ansible *apache2_module* module is making unwarranted assumptions.

In any case, I have no idea about the best/proper way for the Ansible *apache2_module* module in dealing with these kind of special cases.

Unless it's already what you are doing, I would suggest something like this as a workaround for now.

```yaml
- name: Enable dump_io module
  command: a2enmod dump_io
  args:
    creates: /etc/apache2/mods-enabled/dump_io.load
```

**Comment by robinro** [comment]
@mmolinac 
Thanks for this bug report!

As you already pointed out, there is a mismatch between the module name used for loading and the one displayed by `apache2ctl -M`. I consider this mismatch a bug in the upstream apache code and would like to ask you to open a bugreport and have them use the same module name in both places.

Anyhow we should be able to play the hand dealt to us and this is not the first module to break the naming convention. We already have several workarounds defined and we could add an additional one for `dump_io`.

Have a look at
https://github.com/ansible/ansible/blob/ba99e44b423f64227b94e0f201c4c340a989dc11/lib/ansible/modules/web_infrastructure/apache2_module.py#L145-L161
Most likely adding `('dump_io', 'dumpio_module'),` to `text_workarounds` will fix the issue.
@mmolinac Can you try this and open a PR?

**Comment by robinro** [comment]
Thanks @andreaso for pointing to the workaround.

**Comment by robinro** [comment]
@mmolinac I opened a PR to add a new `identifier` option, which allows you to add the dumpio module as
```
apache2_module:
    name: dump_io
    identifier: dumpio_module
    state: present
```
