### ISSUE TITLE
dns_subject_alt_name in openssl_csr

### ISSUE THREAD

**Issue by ryanerwin** [ansible/ansible#33676]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
openssl_csr module

##### ANSIBLE VERSION
```
 % ansible --version
ansible 2.4.1.0
config file = /home/ryan/Git/Ansible/ansible.cfg
configured module search path = [u'/home/ryan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/dist-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Currently the `openssl_csr` module's `subject_alt_name:` requires items in the format: "DNS:my.domain.name", yet any data stuctures we use to define environments would not have "DNS:" already appended to the domain name...

Unfortunately, it's going to be very difficult to do something along the lines of:
```
openssl_csr:
   ...
   subject_alt_name: "{{ item.key }}"
with_dict: "{{ some_varriable }}"
```

Since you'll need to prepend "DNS:" to each of the values in `item.key`.

I suggest that you create `dns_subject_alt_name` that takes a list of domain names and prepends "DNS:". If `subject_alt_name` is also used, those values could be appended to the result of `dns_subject_alt_name`, though realistically can probably be mutually exclusive..

If there is significant enough usage of the other SAN values (Email addresses, IP addresses, URIs...) it could be worth adding those, though I suspect they aren't used enough to be worthwhile.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/crypto/openssl_csr.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssl_csr.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Spredzy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Spredzy** [comment]
Hi @ryanerwin, could you please paste an example of data structure you'd be passing in ? Like how (list, dict, etc...) the hostnames would be passed?

**Comment by ryanerwin** [comment]
In my `roles/common/defaults/main.yml` I have something like:
(exact names changed for example)

```yaml
domains:
    example:
      - host.example.com
      - two.example.com
      - san.example.com
    beta:
      - si.beta.com
      - wu.beta.com
    gamma:
      - hostX.gamma.com
      - hostY.gamma.com
    foo:
      - z.foo.org
      - z.foo.net
    bar:
      - mail.bar.com
      - beta.bar.com
      - candy.bar.com
      - snickers.bar.com
```

Then, in my playbook I have:
```yaml
- name: Generate an OpenSSL CSR
  openssl_csr:
    path: /etc/letsencrypt/live/{{ item.value | first }}/csr.csr
    privatekey_path: /etc/letsencrypt/live/{{ item.value | first }}/privkey.pem
    common_name: "{{ item.value | first }}"
    subject_alt_name: "{{ item.value }}"
  with_dict: "{{domains}}"
  loop_control:
    label: "Certificate Signing Request (CSR) for /etc/letsencrypt/live/{{ item.value | first }}"
```

Unfortunately, this won't work because SAN (Subject_Alt_Name) needs to be passed to this module in the format `DNS:host.example.com`

If you don't have any variables in a loop, it's not too big of an issue, but for any Ansible users that have the DNS host names in variables, requiring the "DNS:" prefix on each hostname seems sub-optimal, especially since this sort of string manipulation is very difficult in Ansible compared to say directly in Python.

For a single certificate, I would suggest that an interface like:
```yaml
  - name: Generate an OpenSSL private key
    openssl_privatekey:
      path: /tmp/privkey.pem

  - name: Generate an OpenSSL CSR
    openssl_csr:
      path: /tmp/csr.csr
      privatekey_path: /tmp/privkey.pem
      common_name: host.example.com
      dns_subject_alt_name:   # Currently it's just "subject_alt_name"
        - "www.example.com"   # and you have to prepend "DNS:
        - "m.example.com"     # like:
        - "mail.example.com"  # DNS:mail.example.com

  - name: Generate a Self Signed OpenSSL certificate.
    openssl_certificate:
      path: /tmp/fullchain.pem
      privatekey_path: /tmp/privkey.pem
      csr_path: /tmp/csr.csr
      provider: selfsigned
```
