### ISSUE TITLE
Support aggregate on nxos_vlan

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#33686]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
nxos_vlan

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /root/aggregate_resources/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/napalm_ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
```
DEFAULT_GATHERING(/root/aggregate_resources/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/root/aggregate_resources/ansible.cfg) = [u'/root/aggregate_resources/hosts']
DEFAULT_MODULE_PATH(/root/aggregate_resources/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/napal
DEPRECATION_WARNINGS(/root/aggregate_resources/ansible.cfg) = False
HOST_KEY_CHECKING(/root/aggregate_resources/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/root/aggregate_resources/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
CentOS Linux release 7.3.1611 (Core)
```

##### SUMMARY
aggregate feature is missing on nxos_vlan

##### STEPS TO REPRODUCE
```yaml
---
- hosts: cisco
  connection: local
  vars:
    ansible_network_os: "nxos"
  tasks:
    - net_vlan:
        provider: "{{ login_info }}"
        state: active
        aggregate:
          - { vlan_id: 1, name: default }
          - { vlan_id: 2, name: Vl2 }
          - { vlan_id: 3, state: suspend }
```

##### EXPECTED RESULTS
playbook will function

##### ACTUAL RESULTS
playbook fails
```
TASK [net_vlan] **************************************************************************************
fatal: [n9k]: FAILED! => {"ansible_facts": {"network_os": "nxos"}, "changed": false, "msg": "Unsupported parameters for (nxos_vlan) module: aggregate Supported parameters include: admin_state,config,host,include_defaults,mapped_vni,mode,name,password,port,provider,save,ssh_keyfile,state,timeout,transport,use_ssl,username,validate_certs,vlan_id,vlan_range,vlan_state"}
```
