### ISSUE TITLE
module github_release returns "ok" when it changed something, "skipped" when no change is required.

### ISSUE THREAD

**Issue by robertdebock** [ansible/ansible#33687]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
github_release

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /Users/yf30lg/Documents/ansible/roles/tools/create-releases/ansible.cfg
  configured module search path = [u'/Users/yf30lg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(/Users/USERNAME/Documents/ansible/roles/tools/create-releases/ansible.cfg) = [u'/Users/USERNAME/Documents/ansible/roles/tools/
RETRY_FILES_ENABLED(/Users/USERNAME/Documents/ansible/roles/tools/create-releases/ansible.cfg) = False
```

##### OS / ENVIRONMENT
N/A (Because I'm trying to manage github, not an operating system.)

##### SUMMARY
When creating a release with this code:
```
    - name: create a new release
      github_release:
        user: USERNAME
        token: SECRETTOKEN
        repo: REPOSITORY
        action: create_release
        tag: "{{ ansible_date_time.year }}.{{ ansible_date_time.month }}.{{ ansible_date_time.day }}"
        name: A NAME FOR THE RELEASE
        body: CONTENT FOR THE RELEASE
```

The state is a unexpected:
- When the release already exists: "skipped"
- When the release is created: "ok"

##### STEPS TO REPRODUCE
With the code above:

```
ansible-playbook playbook.yml
```

##### EXPECTED RESULTS
I would have expected:
- When the release already exists: "ok"
- When the release is created: "changed"

##### ACTUAL RESULTS
- When the release already exists: "skipped"
- When the release is created: "ok"
