### ISSUE TITLE
FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}

### ISSUE THREAD

**Issue by rafecolton** [ansible/ansible#33699]
##### SUMMARY

Tasks will sporadically fail due to the error message `FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}`. It's hard to reproduce consistently, and retries of playbooks that fail usually succeed.

I've seen various reports of this error and various fixes, but I'm still encountering it fairly regularly.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Ansible SSH connections

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /Users/rafe/workspace/platform/ansible/ansible.cfg
  configured module search path = ['/Users/rafe/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/rafe/workspace/platform/ansible/.venv/lib/python3.6/site-packages/ansible
  executable location = /Users/rafe/workspace/platform/ansible/.venv/bin/ansible
  python version = 3.6.3 (default, Nov  2 2017, 09:26:55) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/Users/rafe/workspace/platform/ansible/ansible.cfg) = False
ANSIBLE_SSH_ARGS(/Users/rafe/workspace/platform/ansible/ansible.cfg) = -F .ssh/config -o ControlMaster=auto -o ControlPersist=30m -o ControlPath=.ssh/ansible-control-path-%r@%h:%p
DEFAULT_HOST_LIST(/Users/rafe/workspace/platform/ansible/ansible.cfg) = ['/Users/rafe/workspace/platform/ansible/hosts/ec2.py']
DEFAULT_VAULT_PASSWORD_FILE(/Users/rafe/workspace/platform/ansible/ansible.cfg) = /Users/rafe/workspace/platform/ansible/.vault-pass
HOST_KEY_CHECKING(/Users/rafe/workspace/platform/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/Users/rafe/workspace/platform/ansible/ansible.cfg) = /Users/rafe/.ansible/retry-files
```

##### OS / ENVIRONMENT

macOS 10.12.6 managing Canonical Ubuntu 16.04.03 LTS

##### DEPENDENCY PROBLEMS

(none)

##### STEPS TO REPRODUCE

As mentioned above, this is not consistently reproducible. Following is an excerpt from a role that installs docker. It often fails on the `install docker` task.

```yaml
- name: install prereq packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

- name: add docker GPG key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    state: present

- name: get lsb_release -cs
  command: lsb_release -cs
  register: lsb_release
  changed_when: lsb_release.rc > 0

- name: add docker apt repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"

- name: install docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes
```

##### EXPECTED RESULTS

Install docker

##### ACTUAL RESULTS

```
Failed with `FAILED! => {"msg": "Timeout (12s) waiting for privilege escalation prompt: "}`
```
