### ISSUE TITLE
vmware_guest :  RuntimeError (maximum recursion depth exceeded)

### ISSUE THREAD

**Issue by cdelgehier** [ansible/ansible#33760]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/cdelgehier/git/my_project/ansible.cfg
  configured module search path = [u'/home/cdelgehier/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7.14/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Dec  7 2017, 15:02:34) [GCC 4.8.4]
```

##### CONFIGURATION
DEFAULT_CALLBACK_PLUGIN_PATH(/home/cdelgehier/git/my_project/ansible.cfg) = [u'/home/cdelgehier/git/my_project/plugins/callback']
DEFAULT_HOST_LIST(/home/cdelgehier/git/my_project/ansible.cfg) = [u'/home/cdelgehier/git/my_project/inventory']
RETRY_FILES_ENABLED(/home/cdelgehier/git/my_project/ansible.cfg) = False

##### OS / ENVIRONMENT

Ubuntu 14.04.5 LTS

##### SUMMARY

I get a `maximum recursion depth exceeded` when the network is a portgroup of a DVswitch 

##### STEPS TO REPRODUCE
```yaml
- name: Create a VM
  hosts: vmware
  gather_facts: no
  connection: local
  
  tasks:
      - name : VM Creation 
        vmware_guest:
          hostname: "{{ vmware_vcenterhost }}"
          username: "{{ vmware_user }}"
          password: "{{ vmware_password }}"
          validate_certs: False
          datacenter: "{{ vmware_dc }}"
          cluster: "{{ vmware_cluster }}"
          folder: "{{ vmware_dc }}/vm/LAB/Project1"
          name: "{{ inventory_hostname }}"
          annotation: "test"
          state: present
          guest_id: "centos64Guest"
          disk: 
            - size_gb: 10
              type: thin
              datastore: mydatastore
              autoselect_datastore: True
          hardware:
            memory_mb: 2048
            num_cpus: 1
            scsi: paravirtual
          networks: 
            - name: 'my_portgroup_on_a_dvs'
            #- name: 'VM Network'
          wait_for_ip_address: no
        register: deploy
```
With a `networks: []` or without with part, it works.
It works too on a the standard portgroup `VM Network`

But with a NIC plugged on a DVS, i got a `RuntimeError: maximum recursion depth exceeded` 

##### EXPECTED RESULTS
A VM plugged to my portgroup on my DVSwitch

##### ACTUAL RESULTS
https://pastebin.com/eqzSn4jD

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@cdelgehier Thanks for reporting this issue. I will try to reproduce this issue in my local environment.

**Comment by cdelgehier** [comment]
Same loop with this setup (on a centos with python 2.7.5)

```
$ ansible --version
ansible 2.4.2.0
  config file = /home/jack/venv/ansible/project/ansible.cfg
  configured module search path = [u'/home/jack/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jack/venv/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/jack/venv/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

$ python --version
Python 2.7.5
```

**Comment by cdelgehier** [comment]
@Akasurde my playbook works with this setup
```
(ansible23) [jack@laptop ansible23]$ ansible --version
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

(ansible23) [jack@laptop ansible23]$ python --version
Python 2.7.5
```

**Comment by arthfl** [comment]
Same behaviour for me.

>ansible --version
>ansible 2.4.2.0
>  config file = /etc/ansible/ansible.cfg
>  configured module search path = [u'/home/flart/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
>  ansible python module location = /usr/lib/python2.7/site-packages/ansible
>  executable location = /bin/ansible
>  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]

**Comment by Akasurde** [comment]
@arthfl @cdelgehier I am not able to reproduce this issue is my env, so as a workaround - can you try this patch - https://github.com/akasurde/ansible/commit/958fa23243ca7b72d697c909bf89f2f083c3a462 ?

needs_info

**Comment by Kevin-De-Koninck** [comment]
Hi,
I have the same error when creating a VM.

the detailed error:

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_aB9L9Y/ansible_module_vmware_guest.py", line 1512, in <module>
    main()
  File "/tmp/ansible_aB9L9Y/ansible_module_vmware_guest.py", line 1503, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_aB9L9Y/ansible_module_vmware_guest.py", line 1313, in deploy_vm
    configspec_json = serialize_spec(self.configspec)
  File "/tmp/ansible_aB9L9Y/ansible_modlib.zip/ansible/module_utils/vmware.py", line 626, in serialize_spec
  File "/tmp/ansible_aB9L9Y/ansible_modlib.zip/ansible/module_utils/vmware.py", line 611, in serialize_spec
  File "/tmp/ansible_aB9L9Y/ansible_modlib.zip/ansible/module_utils/vmware.py", line 611, in serialize_spec
  File "/tmp/ansible_aB9L9Y/ansible_modlib.zip/ansible/module_utils/vmware.py", line 611, in serialize_spec
  File "/tmp/ansible_aB9L9Y/ansible_modlib.zip/ansible/module_utils/vmware.py", line 611, in serialize_spec

...
```

My task:
``` yml
- name: create vm
  vmware_guest:
    hostname:  '{{ vmware.hostname }}'
    username: '{{ vmware.username }}'
    password: '{{ vmware.password }}'
    validate_certs: '{{ vmware.validate_certs }}'
    datacenter: '{{ item.datacenter }}'
    esxi_hostname: '{{ item.host.ip }}'
    state: present
    name: '{{ item.name }}'
    guest_id:  '{{ item.guest_id}}'
    hardware:
      memory_mb: '{{ item.memory }}'
      num_cpus: '{{ item.cpu }}'
    disk:
      - size_gb: '{{ item.disk }}'
        datastore: '{{ item.host.datastore }}'
    networks: '{{ item.networks }}'
  with_items: '{{ guests }}'

```

My ansible version:

```
ansible 2.4.2.0
config file = /root/ANSIBLE/sky-on-prem/ansible.cfg
configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python2.7/site-packages/ansible
executable location = /usr/bin/ansible
python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

When I try [this](https://github.com/Akasurde/ansible/commit/958fa23243ca7b72d697c909bf89f2f083c3a462) patch, proposed by @Akasurde, I get the following error message: 
```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_ZgmwAC/ansible_module_vmware_guest.py", line 1512, in <module>
    main()
  File "/tmp/ansible_ZgmwAC/ansible_module_vmware_guest.py", line 1503, in main
    result = pyv.deploy_vm()
  File "/tmp/ansible_ZgmwAC/ansible_module_vmware_guest.py", line 1312, in deploy_vm
    clonespec_json = vars(clonespec) #serialize_spec(clonespec)
TypeError: vars() argument must have __dict__ attribute
```
