### ISSUE TITLE
Issue in stopping IIS Web Application pool

### ISSUE THREAD

**Issue by Gianlu** [ansible/ansible#33771]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_iis_webapppool

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = False
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/modules']

##### OS / ENVIRONMENT

ansible host: debian 8.10
target system: Windows 2012 R2

##### SUMMARY
Error in stopping Web application pool

##### STEPS TO REPRODUCE

Try to stop an application pool.

```yaml
- name: Stop My Application
  hosts: webservers
  serial: "100%"
  tasks:
    - name: Stop Application pool
      win_iis_webapppool:
        name: myapplicationpool
        state: stopped
```

##### EXPECTED RESULTS

Application pool stopped.

##### ACTUAL RESULTS

Ansible raises an  exception in stopping application pool

```
fatal: [mywebserver]: FAILED! => {"attributes": {}, "changed": true, "info": {"attributes": {}, "cpu": {}, "failure": {}, "name": "myapplicationpool", "processModel": {}, "recycling": {"periodicRestart": {}}, "state": "stopped"}, "msg": "Failed to stop Web App Pool myapplicationpool: The service cannot accept control messages at this time. (Exception from HRESULT: 0x80070425)"}

```
