### ISSUE TITLE
shell module ignores the proxy environment

### ISSUE THREAD

**Issue by roumano** [ansible/ansible#33815]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
The shell module is ignoring  proxy environment
I'm working on some server with limited internet connexion (need to use proxy settings)

On some module, i need to set environment otherwise i get a timeout.
It's a main issue for me as i don't want to have duplication code and/or specific code for limited internet machine (just need to specifigy http_proxy on them) 

##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.14 (default, Nov  3 2017, 10:55:25) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]

```

##### OS / ENVIRONMENT
Tested on remote server Ubuntu 14.04.4 LTS 

##### SUMMARY
Same kinf of issue as for module apt_key  (  https://github.com/ansible/ansible/issues/31691 ) 

##### STEPS TO REPRODUCE
groups_var.yml : 

```yaml
environment:
  http_proxy: "http://172.31.255.254:8888"
  https_proxy: "http://172.31.255.254:8888"

```
This tast is going in timeout : 
```
  - name: Ensure any remote plugins defined are present
    shell: umask 0022; sensu-install -p ftp
```
If set this environment in tasks it's working as expected :  
```
  - name: Ensure any remote plugins defined are present
    shell: umask 0022; sensu-install -p ftp
    environment:
      http_proxy: 'http://172.31.255.254:8888'
      https_proxy: 'http://172.31.255.254:8888'

```

##### EXPECTED RESULTS
Pass thought proxy

##### ACTUAL RESULTS
Timeout as it's not use the proxy environment
