### ISSUE TITLE
ini_file: Support multiple option=value pairs

### ISSUE THREAD

**Issue by smurfix** [ansible/ansible#33856]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ini_file

##### ANSIBLE VERSION

2.4

##### SUMMARY

The ini_file module is nice for updating single entries but very slow when inserting a whole section. This is especially important when the system may reboot for no good reason and the program analysing the .ini file dies or severely misbehaves when a section is incomplete.

Thus I propose that, when there is no `option` parameter, the `value` may be a dict of option/value pairs which are all set at once, in a single Ansible transaction.

##### EXPECTED RESULTS

```
ini_file:
    path: /tmp/test.ini
    section: plugh
    value:
        foo: bar
        baz: quux
```
results in
```
$ cat /tmp/test/ini
[plugh]
foo = bar
baz = quux
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/ini_file.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/ini_file.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @noseka1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by noseka1** [comment]
Thanks for the feature request.

I think that the "atomic" update of multiple ini options could be achieved this way:
1. Copy /tmp/test/ini to /tmp/test/ini_temp
2. Update the options in /tmp/test/ini_temp using the ini_file Ansible module (slow)
3. Move the /tmp/test/ini_temp back to /tmp/test/ini

The suggested feature would be much more convenient but perhaps people can use this method as a workaround.

**Comment by m-u-xyz** [comment]
Correct. However, the "slow" part is somewhat exacerbated with this method since you now need two more Ansible transactions. :-P

**Comment by ipatalas** [comment]
Hi,

I use `with_items` to achieve that. It's pretty quick for multiple values.

Example:
```YAML
- name: Update configuration
  ini_file:
    path: /etc/influxdb/influxdb.conf
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  with_items:
    - { section: "monitor", option: "store-interval", value: '"30s"' }
    - { section: "http", option: "log-enabled", value: "false" }
    - { section: "continuous_queries", option: "enabled", value: "false" }
```

Have you tried that approach?
