### ISSUE TITLE
win_lineinfile: windows paths have \r and \n stripped

### ISSUE THREAD

**Issue by dannietjoh** [ansible/ansible#33858]
##### ISSUE TYPE
 Bug Report

##### COMPONENT NAME
win_lineinfile

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/none/of/your/business', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### SUMMARY
this:
https://github.com/ansible/ansible/blob/e76e8aed902f44b71ec52dacc0d2a4e2ffe5bbd3/lib/ansible/modules/windows/win_lineinfile.ps1#L348

butchers any windows path and also makes regexes fail and destroys idempotency

##### STEPS TO REPRODUCE
use win_lineinefile to add a windows path containing \r or \n

```yaml
- win_lineinfile:
    path: C:\temp\testfile.txt
    line: 'C:\path\returning\from\nowhere'
```
OR
```yaml
- win_lineinfile:
    path: C:\temp\testfile.txt
    line: "C:\\path\\returning\\from\\nowhere"
```

##### EXPECTED RESULTS
file C:\temp\testfile.tx contains C:\path\returning\from\nowhere

##### ACTUAL RESULTS
file C:\temp\testfile.tx contains C:\patheturning\fromowhere

Current workaround is to use forward slashes, but that requires forward slash compatibility in any program that uses this file
