### ISSUE TITLE
Template create files by mv, fail ACL

### ISSUE THREAD

**Issue by maxgorovenko** [ansible/ansible#33865]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /Users/max/Projects/wrk/ansible-devops/ansible.cfg
  configured module search path = [u'/usr/share/ansible', u'/Users/max/Projects/wrk/ansible-devops/library']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/Users/max/Projects/wrk/ansible-devops/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/max/Projects/wrk/ansible-devops/ansible.cfg) = [u'/Users/max/Projects/wrk/ansible-devops/library/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/Users/max/Projects/wrk/ansible-devops/ansible.cfg) = ['human_log update_hosts']
DEFAULT_HOST_LIST(/Users/max/Projects/wrk/ansible-devops/ansible.cfg) = [u'/Users/max/Projects/wrk/ansible-devops/inventory/hosts']
DEFAULT_MODULE_PATH(/Users/max/Projects/wrk/ansible-devops/ansible.cfg) = [u'/usr/share/ansible', u'/Users/max/Projects/wrk/ansible-devops/library']
DEFAULT_ROLES_PATH(/Users/max/Projects/wrk/ansible-devops/ansible.cfg) = [u'/Users/max/Projects/wrk/ansible-devops/roles']
HOST_KEY_CHECKING(/Users/max/Projects/wrk/ansible-devops/ansible.cfg) = False

##### OS / ENVIRONMENT
My os is macOS High Sierra 10.13.1
Provision CentOS Linux release 7.1

##### SUMMARY
Got dir with ACL defaults and SGID, put there file via template module. File doesn't have ACL permissions.

The problem is at the way template create files. They don't creates at dest dir, but they moved there later from tmp. But ACL doesn't work at moved files.

But for me, I guess, template module will create file from template. As user, I don't know about file render mechanics, I just create file at dest from template. File should have ACL as it was created there.

##### STEPS TO REPRODUCE

Bash example:
```bash
mkdir test
getfacl test
setfacl --set=d:g::rwX,d:g:nobody:rwX test
getfacl test
touch test/test1
touch test2
mv test2 test/
ls -la test
getfacl test/test1
getfacl test/test2
```
See the difference of output for two last commands. ACL says it is normal, because file test2 was not created, but moved.

So at playbook I have:

```yaml
- file: name=test state=directory group=team-sys mode="u=rwX,g=rwXs,o=rX"
  become: yes
- acl:
    default: "{{ item[0] }}"
    name: test
    entity: "{{ item[1] }}"
    etype: group
    state: present
    permissions: rwX
  with_nested:
    -
      - yes
      - no
    -
      - team-search
      - team-sys
  become: yes
- template: dest=test src=local.yml
```

##### EXPECTED RESULTS
test/local.yml has parent dir's ACL

##### ACTUAL RESULTS
test/local.yml miss parent dir's ACL

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/template.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/template.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chernomor** [comment]
It seems module template via module copy put content to temporary file and then rename temporary file to destination. So default ACL rules does not apply to destination file as it created not in destination directory.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/template.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/template.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
As to avoid data corruption we try to update files via atomic operations, in the case of template the file is generated at the controller and copied to the remote (to remote_tmp, to where normally the module code itself is copied) from there we attempt a 'rename' and if that succeeds we go no further, this is why the ACL is failing. 

If you set the remote_tmp to a different partition the rename will fail and we will attempt to copy to tmp file in the same directory and then rename.  the only time we write directly to file is if all this fails and `unsafe_writes: true` is used.

One workaround is to force remote_tmp to the directory with the ACL or the same ACL in a temp dir.

Currently we don't have a solution that will both work with the ACL automatically and ensure data integrity.

**Comment by Vladimir-csp** [comment]
Idempotency also suffers if file is deployed with `copy` or `template`, and ACLs are applied later. Both tasks always reported as changed, and ACLs are lost until `acl` task runs.

**Comment by milkpirate** [comment]
> One workaround is to force remote_tmp to the directory with the ACL or the same ACL in a temp dir.
Does not seem to work:
```yaml
# folder tree has been created previously, no problem with ACLs there
    - ansible.builtin.template:
        src: "{{ file.src }}"
        dest: "/some/path/{{ file.path }}"
      vars:
        ansible_remote_tmp: "/some/path/.ansible_tmp"
      loop_control:
        loop_var: file
      with_filetree: templates/local-dir/
```
```bash
$ ls -la /some/path/
-rw-rw-r--   1 stack stack  604 Jan 28 17:44 foo
...
```
Notice the missing `+` at the end of the permissions, indicating no ACL for this file.

Is there anything I can do except ACL-ing everything again?

```bash
$ poetry run ansible --version
ansible [core 2.13.7]
  config file = /home/pschroeder/repos/ansible-hosts/ansible.cfg
  configured module search path = ['/home/pschroeder/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/pschroeder/.cache/pypoetry/virtualenvs/ansible-hosts-649A4hF8-py3.8/lib/python3.8/site-packages/ansible
  ansible collection location = /home/pschroeder/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/pschroeder/.cache/pypoetry/virtualenvs/ansible-hosts-649A4hF8-py3.8/bin/ansible
  python version = 3.8.10 (default, Jun 22 2022, 20:18:18) [GCC 9.4.0]
  jinja version = 3.1.2
  libyaml = True
```
