### ISSUE TITLE
skeleton option of user module does not copy skeleton directory contents

### ISSUE THREAD

**Issue by georgberky** [ansible/ansible#33871]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - module name:  user

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
nothing changed

##### OS / ENVIRONMENT

- host: OSX High Sierra all patches

remote machines using Vagrant:
- config.vm.box = "centos/7"
- config.vm.box = "geerlingguy/ubuntu1604"

##### SUMMARY
I tried to create a user via the user module and set the skeleton option to /etc/skel . The module did not copy the contents of /etc/skel to the user's home directory.

##### STEPS TO REPRODUCE
```yaml
      - name: Create Jenkins user
        user:
            name: jenkins
            comment: "Jenkins slave user"
            system: yes
            createhome: yes
            skeleton: /etc/skel
            home: /data/jenkins
            shell: /bin/bash
```

##### EXPECTED RESULTS
The contents of /etc/skel should be copied to /data/jenkins

##### ACTUAL RESULTS
Nothing happened. The files were not copied. No errors were reported when running Ansible playbook.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @sfromm
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
I cannot duplicate this.  I tested on centos 7.4 with the provided task.

```
/data/jenkins/:
total 12
drwx------. 2 jenkins jenkins  75 Dec 13 16:24 .
drwxr-xr-x. 3 root    root     21 Dec 13 16:24 ..
-rw-r--r--. 1 jenkins jenkins  18 Sep  6 16:25 .bash_logout
-rw-r--r--. 1 jenkins jenkins 193 Sep  6 16:25 .bash_profile
-rw-r--r--. 1 jenkins jenkins 231 Sep  6 16:25 .bashrc
-rw-r--r--. 1 jenkins jenkins   0 Dec 13 16:21 puppy

/etc/skel/:
total 24
drwxr-xr-x.  2 root root   75 Dec 13 16:21 .
drwxr-xr-x. 78 root root 8192 Dec 13 16:24 ..
-rw-r--r--.  1 root root   18 Sep  6 16:25 .bash_logout
-rw-r--r--.  1 root root  193 Sep  6 16:25 .bash_profile
-rw-r--r--.  1 root root  231 Sep  6 16:25 .bashrc
-rw-r--r--.  1 root root    0 Dec 13 16:21 puppy
```

```
changed: [172.16.0.129] => {
    "changed": true,
    "comment": "Jenkins slave user",
    "create_home": true,
    "group": 994,
    "home": "/data/jenkins",
    "invocation": {
        "module_args": {
            "append": false,
            "comment": "Jenkins slave user",
            "create_home": true,
            "createhome": true,
            "expires": null,
            "force": false,
            "generate_ssh_key": null,
            "group": null,
            "groups": null,
            "home": "/data/jenkins",
            "local": null,
            "login_class": null,
            "move_home": false,
            "name": "jenkins",
            "non_unique": false,
            "password": null,
            "remove": false,
            "seuser": null,
            "shell": "/bin/bash",
            "skeleton": "/etc/skel",
            "ssh_key_bits": 0,
            "ssh_key_comment": "ansible-generated on localhost.localdomain",
            "ssh_key_file": null,
            "ssh_key_passphrase": null,
            "ssh_key_type": "rsa",
            "state": "present",
            "system": true,
            "uid": null,
            "update_password": "always"
        }
    },
    "name": "jenkins",
    "shell": "/bin/bash",
    "state": "present",
    "system": true,
    "uid": 997
}
```

needs_info

**Comment by sparsick** [comment]
If I run following playbook script
```yaml
- hosts: jenkins-slaves
  become: true
  become_method: sudo
  tasks:
      - name: Create Jenkins user
        user:
            name: jenkins
            comment: "Jenkins slave user"
            system: yes
            skeleton: /etc/skel
            createhome: yes
            home: /data/jenkins
            shell: /bin/bash

```
I get the following error message by Ansible

```
< TASK [Create Jenkins user] >
 ----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [192.168.33.10]: FAILED! => {"changed": false, "msg": "useradd: cannot create directory /data/jenkins\n", "name": "jenkins", "rc": 12}

```
So I adjusted the playbook with an additional step:
```yaml
      - name: Create Jenkins user home
        file:
            path: /data/jenkins
            state: directory

      - name: Create Jenkins user
        user:
            name: jenkins
            comment: "Jenkins slave user"
            system: yes
            skeleton: /etc/skel
            createhome: yes
            home: /data/jenkins
            shell: /bin/bash
```
Then Ansible runs successfully, but the content of `/etc/skel` isn't copied to `/data/jenkins`.
