### ISSUE TITLE
VMware: assigning ip and other variables

### ISSUE THREAD

**Issue by LiginGeorge** [ansible/ansible#33903]
##### ISSUE TYPE

  - Feature Idea
##### COMPONENT NAME

```
ansible 2.4.0.0
```

##### OS / ENVIRONMENT

Redhat 7. 2 OS.
##### SUMMARY

1. i would like to provision VM from template with new IP/hostname/datastore/network label and son..
i am able to provision VM from template, but IP assigning/data store renaming all needs to do manually. 
how do i can automate all in a single play book.
##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: create the VM
    vmware_guest:
      hostname: vcunix-jlt
      username: *******
      password: *******
      validate_certs: no
      esxi_hostname: 10.155.20.142
      datacenter: jl-Floor
      folder: /template
      name: testvm_2
      state: poweredon
      template: RHEL7
    register: deploy
```

##### EXPECTED RESULTS

 Need to provide guest OS IP/new data store/ network label and son on 
##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
@LiginGeorge Thanks for reporting this issue. Could you please use `networks` argument for specifying IP and network details ? You can find more details about all parameters [here](http://docs.ansible.com/ansible/latest/vmware_guest_module.html)

Also, could you please elaborate about "providing new datastore" ?

needs_info

**Comment by LiginGeorge** [comment]
Hi ,

Can you please let me know an example for specifying network argument, hope
this also can be taken care via single play book which i mentioned  in the
ticket..

**Comment by Akasurde** [comment]
@LiginGeorge Please find the snippet from documentation 

```yaml
- name: Create a VM from a template
  vmware_guest:
    hostname: 192.0.2.44
    username: administrator@vsphere.local
    password: vmware
    validate_certs: no
    folder: /datacenter/vm/folder
    name: testvm_2
    state: poweredon
    template: template_el7
    disk:
    - size_gb: 10
      type: thin
      datastore: g73_datastore
    hardware:
      memory_mb: 512
      num_cpus: 1
      scsi: paravirtual
    networks:
    - name: VM Network
      mac: aa:bb:dd:aa:00:14
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy
```

Hope this works.
