### ISSUE TITLE
file module does not honour follow when hard linking

### ISSUE THREAD

**Issue by afrittoli** [ansible/ansible#33911]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
file

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Ubuntu 16.04.3

##### SUMMARY
The file module does not honour the "follow" parameter when hard linking.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  tasks:
    - name: Create a folder
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /tmp/foo
        - /tmp/foo2
    - name: Touch a file in it
      file:
        path: /tmp/foo/bar
        state: touch
    - name: Create a symlink
      file:
        src: /tmp/foo/bar
        dest: /tmp/foo2/bar
        state: link
    - name: Create an hard link with follow to the sym link
      file:
        src: /tmp/foo2/bar
        dest: bar
        state: hard
        follow: yes
    - name: Check the file created
      stat:
        path: bar
      register: bar_stat
      failed_when: bar_stat.stat.islnk
```

##### EXPECTED RESULTS
Success

##### ACTUAL RESULTS
Failed

```
root@9c7f1fadfc24:/local_test# ansible-playbook test2.yaml -c local

PLAY [localhost] ***********************************************************************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create a folder] *****************************************************************************************************************************************************************************************
ok: [localhost] => (item=/tmp/foo)
ok: [localhost] => (item=/tmp/foo2)

TASK [Touch a file in it] **************************************************************************************************************************************************************************************
changed: [localhost]

TASK [Create a symlink] ****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [Create an hard link with follow to the sym link] *********************************************************************************************************************************************************
changed: [localhost]

TASK [Check the file created] **********************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed_when_result": true, "stat": {"atime": 1513257483.4632897, "attr_flags": "", "attributes": [], "block_size": 4096, "blocks": 0, "charset": "binary", "ctime": 1513257664.0708885, "dev": 49, "device_type": 0, "executable": false, "exists": true, "gid": 0, "gr_name": "root", "inode": 10319, "isblk": false, "ischr": false, "isdir": false, "isfifo": false, "isgid": false, "islnk": true, "isreg": false, "issock": false, "isuid": false, "lnk_source": "/tmp/foo/bar", "lnk_target": "/tmp/foo/bar", "mimetype": "inode/symlink", "mode": "0777", "mtime": 1513257483.4632897, "nlink": 6, "path": "bar", "pw_name": "root", "readable": true, "rgrp": true, "roth": true, "rusr": true, "size": 12, "uid": 0, "version": null, "wgrp": true, "woth": true, "writeable": true, "wusr": true, "xgrp": true, "xoth": true, "xusr": true}}
	to retry, use: --limit @/local_test/test2.retry

PLAY RECAP *****************************************************************************************************************************************************************************************************
localhost                  : ok=5    changed=2    unreachable=0    failed=1   
```
