### ISSUE TITLE
Protected argument with no_log=True isn't censored when using iterator 

### ISSUE THREAD

**Issue by pkubica** [ansible/ansible#33912]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

no_log
##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pkubica/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  2 2017, 18:42:05) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]

```

##### SUMMARY

When using a module, which has no_log=True protected argument, with iterator with_items (and I think that issue is affecting all iteration methods) the sensitive information will be leaked:

example with ovirt_host module:
(it has no_log=True in password argument https://github.com/ansible/ansible/blob/v2.4.2.0-1/lib/ansible/modules/cloud/ovirt/ovirt_hosts.py#L403) 

TASK [Add hosts] **************************************************************************************************************************************************************************************************
changed: [192.168.0.200] => (item={u'ip': u'192.168.0.200', u'password': u'123456', u'name': u'myhost1'})
changed: [192.168.0.201] => (item={u'ip': u'192.168.0.201', u'password': u'123456', u'name': u'myhost2'})

##### STEPS TO REPRODUCE

```yaml
   - name: Add hosts
     ovirt_hosts:
       auth: "{{ ovirt_auth }}"
       name: "{{ item.name }}"
       address: "{{ item.ip }}"
       cluster: "Default"
       password: "{{ item.password }}"
     with_items:
       - "{{ ovirt_hosts }}"
```

##### EXPECTED RESULTS

Should be displayed as censored.
##### ACTUAL RESULTS

Leaked password into output.

```

```

**Comment by machacekondra** [comment]
@machacekondra

**Comment by ansibot** [comment]
Files identified in the description:
* [test/integration/targets/no_log/aliases](https://github.com/ansible/ansible/blob/devel/test/integration/targets/no_log/aliases)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
There is no direct correlation to what arguments a module marks as `no_log` and the values of variables used in a loop.

If you wish to ensure that sensitive variables are not leaked in a loop, you will need to either apply `no_log: true` onto the task in full, or look at using `loop_control` such as the following to suppress that output.

```
   - name: Add hosts
     ovirt_hosts:
       auth: "{{ ovirt_auth }}"
       name: "{{ item.name }}"
       address: "{{ item.ip }}"
       cluster: "Default"
       password: "{{ item.password }}"
     with_items:
       - "{{ ovirt_hosts }}"
     loop_control
       label: "{{ item.name }}"
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by texdc** [comment]
@sivel We're still using `2.4` and I tried the `label` property. However, the loop item structure was still rendered in verbose output.
```yaml
  with_items:
    - name: foo
      pass: "{{ foo_password | kms_decrypt(region) }}"
    - name: bar
      pass: "{{ bar_password | kms_decrypt(region) }}"
  loop_control:
    loop_var: my_user
    label: "{{ my_user.name }}"
```
