### ISSUE TITLE
gce: error with non-ascii image names

### ISSUE THREAD

**Issue by wenottingham** [ansible/ansible#33923]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

gce

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
none

##### OS / ENVIRONMENT

CentOS 7
apache-libcloud==2.2.1

##### SUMMARY

unicode-out-of-nowhere causes error in GCE module

##### STEPS TO REPRODUCE
```
  - name: terminate GCP hosts
    gce:
      name: "gcp-{{ project_name }}-00{{ item }}"
      state: absent
      zone: "{{ gcp_region }}"
    with_sequence: start=0 end=9
```

run with:

```
ansible-playbook -i inventory -e gcp_region=us-west-1a -e project_name=🐙🐙
```

##### EXPECTED RESULTS

"no instances found" or similar

##### ACTUAL RESULTS

```
failed: [localhost] (item=0) => {"changed": false, "failed": true, "item": "0", "msg": "Unexpected response: ('ascii' codec can't decode byte 0xf0 in position 4: ordinal not in range(128)). Detail: Traceback (most recent call last):\n  File \"/tmp/ansible_8undFf/ansible_module_gce.py\", line 619, in change_instance_state\n    inst = gce.ex_get_node(name, zone)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py\", line 7022, in ex_get_node\n    request = '/zones/%s/instances/%s' % (zone.name, name)\nUnicodeDecodeError: 'ascii' codec can't decode byte 0xf0 in position 4: ordinal not in range(128)\n"}
```
