### ISSUE TITLE
win_mapped_drive yields mapped but "Unavailable" drive

### ISSUE THREAD

**Issue by fligi7** [ansible/ansible#33929]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
(Updated per https://github.com/ansible/ansible/issues/33929#issuecomment-351854964)
[lib/ansible/modules/windows/win_mapped_drive.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_mapped_drive.ps1)

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.5/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.5.3 (default, May 11 2017, 09:10:41) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
```
##### CONFIGURATION
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible/ansible.log

##### OS / ENVIRONMENT
Ansible Controller: Fedora 24
Ansible Target System: Win 7 Enterprise

##### SUMMARY
Running the following task in a playbook yields a mapped but "Unavailable" (as reported by "net use" on the target) drive, and thus ensuing actions relying on this mapping fail.

##### STEPS TO REPRODUCE
```yaml
  - name: Delete Previously Mapped Z (if present)
    win_mapped_drive:
      letter: Z
      state: absent
  - name: Map Z Drive
    win_mapped_drive:
      letter: Z
      path: \\path\to\share
      username: '{{ DOMAIN }}\{{ smb_username }}'
      password: "{{ smb_password }}"
      state: present
  - name: Z Dir
    win_command: dir
    args:
      chdir: Z:\
    register: dir_out
  - debug:
      var: dir_out
```

##### EXPECTED RESULTS
Drive mapped to Z: on Windows target system.

##### ACTUAL RESULTS
On Ansible Host:
```
TASK [Delete Previously Mapped Z (if present)] **********************************************************************************************************************************************************************************************************
ok: [WIN7] => {"changed": false, "failed": false}

TASK [Map Z Drive] **************************************************************************************************************************************************************************************************************************************
changed: [WIN7] => {"changed": true, "failed": false}

TASK [Quick Dir of Mapped Drive] ************************************************************************************************************************************************************************************************************************
fatal: [WIN7]: FAILED! => {"changed": false, "cmd": "dir", "failed": true, "msg": "invalid working directory path 'Z:\\'", "rc": 2}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************************
WIN7             : ok=6    changed=1    unreachable=0    failed=1

```

On Ansible Target:
````
>net use
New connections will be remembered.


Status       Local     Remote                    Network

-------------------------------------------------------------------------------
Unavailable  Z:        \\path\to\share Microsoft Windows Network
````

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_mapped_drive.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_mapped_drive.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
I don't think you will be able to do what you are looking for, this module is designed to create a mapped drive for a user and due to the security implementation of Windows it is per session. When using `win_mapped_drive` it will create a mapped drive so that a user can see the mapped drive when logging in but the session isolation that occurs with Windows means they are not visible within a WinRM session. This is the same issue where an elevated user cannot see a mapped drive as a process run under a higher privilege has a different token assigned.

This is not a simple process and I don't think it is easily done, I'll update the docs for the module so it is clearer for it is for and how this scenario won't work.

**Comment by ansibot** [comment]
cc @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fligi7** [comment]
That's rather unfortunate that you can't do anything with the drive you just mapped. It will definitely help to have that much clearer in the docs.

In the same vein, does Ansible provide any capability otherwise to utilize (read from/write to) a mapped drive through WinRM in any fashion?

**Comment by jborean93** [comment]
No it does not, as I said mapped drives are isolated per session and Windows will not allow access to them in an WinRM session by design. The best bet is to use a UNC path and either use become or an auth method that delegates your credential to the network path.

**Comment by fligi7** [comment]
I'm already specifying a UNC path as you can see if my post. How would I use it differently?

Currently, I'm connecting to the remote machine via the following at the beginning of my playbook:

```yaml
- hosts: "{{ Target }}"
  gather_facts: yes
  remote_user: USER1
```

To clarify, you are suggesting that I instead use the following which should fix this issue?

```yaml
- hosts: "{{ Target }}"
  gather_facts: yes
  become: USER1
```

I understand Windows credential delegation, just trying to understand it WRT what Ansible is doing here.

**Comment by jborean93** [comment]
@fligi7 sorry I didn't see your response to now as we usually don't monitor closed issues. You are specifying a UNC path to create the mapped drive but that doesn't solve the issue around mapped drives being unavailable to a WinRM session. What I meant by that was if you need to access a network resource in a module or command, you use the UNC path for that module, e.g.

```
- name: this is not the way
  win_copy:
    src: Z:\folder
    dest: C:\temp

- name: this would be the way
  win_copy:
    src: \\server\share\folder
    dest: C:\temp
```

There are many rules that govern if you can access the network path in a WinRM session, in short you won't be able to access if unless you do one of the following;

* Use CredSSP or Kerberos with the `ansible_winrm_kerberos_credential_delegation: yes` is set and supported by your domain controller
* Use become on the task so the WinRM process has access to the credentials required to access the network path
