### ISSUE TITLE
at_module "now"

### ISSUE THREAD

**Issue by ryanerwin** [ansible/ansible#33936]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
at

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ryan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The `at` command supports fairly complex time specifications, like `4pm + 3 days` or most useful to me `now`. 

Would at least like a way to execute `at now` for jobs that we want to completely background (different from the results of `poll: 0`.

Ideally would like to use the full timespec typically found at `/usr/share/doc/at/timespec`

Currently the `at_module` only supports:

* count: 10 # an integer number of units in the future
* units: minutes # or hours | days | weeks

Could add an option (mutually exclusive with `count / units`) perhaps called `timespec` or `time`...

For example, I have a task:

```
- name: Restart Network
  at:
    command: "service network stop; sleep 3; service network start"
    count: 1
    units: minutes
  when: ifcfg_result.changed
```

That I would like to change to:

```
at:
  command: "service network stop; sleep 3; service network start"
  timespec: now
when: ifcfg_result.changed
```

Adding timespec could also be very useful for ad-hoc commands:

```
ansible -m at -a "command=/big/CPU/killing/job timespec=6pm" all
```
