### ISSUE TITLE
Module docker_service seems to create variables at runtime

### ISSUE THREAD

**Issue by marioprudhomme** [ansible/ansible#33960]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_service

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/env/dev/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
```

##### CONFIGURATION
DEFAULT_HOST_LIST(/etc/ansible/env/dev/ansible.cfg) = [u'/etc/ansible/env/dev/inventory.yml']

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Not sure if this is an intended feature by the owner or a bug.

When using the docker_service module with `state: present`,  a new variable is created in the ansible runtime for each services defined in the docker-compose.yml file, containing the output of `docker-compose up`. This potentially overwrites variables already defined in ansible.

This also means that if i edit the docker-compose.yml file (oblivious of ansible), it can potentially break the ansible build when there are name conflicts between ansible variables and the name of services present in the docker-compose.yml file.

##### STEPS TO REPRODUCE
```
- name: Up formio container
  docker_service:
      project_src: /srv/formio
      state: present
```

##### EXPECTED RESULTS
No variables created by the module

##### ACTUAL RESULTS
A new `formio` variable gets created and overwrites the current `formio` variable, becausee the docker-compose.yml file has a service named `formio`.

```
version: '2.1'

volumes:
    mongodb_data:
        driver: local

    formio_data:
        driver: local

services:
    mongodb:
        image: mongo:3.4.3
        volumes:
            - mongodb_data:/data/db
        healthcheck:
            test: ['CMD-SHELL', 'echo "db.stats().ok" | mongo localhost/formioapp --quiet']
            interval: 5s
            timeout: 1s
            retries: 10

    *formio*:
        build: .
        depends_on:
            mongodb:
                condition: service_healthy
                ...
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_service.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Ref: https://github.com/ansible/ansible/blob/4c0889e8fcee6c8be9fef33887480747c227725d/lib/ansible/modules/cloud/docker/docker_service.py#L768

**Comment by marioprudhomme** [comment]
Potential fix: 

Keep the current behavior for backward compatibility. Introduce a new optional attribute to allow the user to `register` a new fact name instead of assuming the compose service names.

```
- name: Up formio container
  docker_service:
      project_src: /srv/formio
      state: present
      fact: results
```

results would contain:

```
{
    "mongodb": {  as usual... },
    "formio": { as usual... }
}
```
