### ISSUE TITLE
resizefs option in filesystem module fails with xfsprogs-4.12 (fedora 27 atomic)

### ISSUE THREAD

**Issue by trammel** [ansible/ansible#33979]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
filesystem (resizefs, xfs)

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /Users/asdf/ansible/ansible.cfg
  configured module search path = [u'/Users/asdf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
DEFAULT_PRIVATE_KEY_FILE(/Users/asdf/ansible/ansible.cfg) = /Users/jonpad/git/adsf/ansible/roles/asdf/private_keys/asdf.rsa

##### OS / ENVIRONMENT
management: Mac OS 10.12.6 (management)
Fedora 27 (Atomic Host)

##### SUMMARY
The resizefs functionality for xfs in the filesystem module worked fine on Fedora 26 (Atomic Host), is broken in Fedora 27 (Atomic Host), probably because of this change https://bugzilla.redhat.com/show_bug.cgi?id=1477192

Basically, xfs_info was deliberately changed to only work on the mount points of mounted partitions, not device names. The filesystem module expects device names as arguments, and xfs_growfs now fails with a device name.

##### STEPS TO REPRODUCE
```yaml
---

- name: Enlarge the root partition
  lvol:
    vg: fedora-atomic
    lv: root
    size: 5G

- name: Grow the root filesystem
  filesystem:
    fstype: xfs
    dev: /dev/mapper/fedora--atomic-root
    resizefs: yes
```

##### EXPECTED RESULTS
Command completes with OK.

##### ACTUAL RESULTS
```
fatal: [atomic01]: FAILED! => {"changed": false, "err": "xfs_growfs: /dev/mapper/fedora--atomic-root is not a mounted XFS filesystem\n", "failed": true, "msg": "Failed to get block count and block size of /dev/mapper/fedora--atomic-root with /usr/sbin/xfs_growfs", "rc": 1}
```
