### ISSUE TITLE
vmware_guest_facts or   vmware_vm_facts does not return snapshot information

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/ansible#33971]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

vmware_guest_facts

##### ANSIBLE VERSION

```
ca-spollockmb1:fs-skytap-control spollock$ ansible --version
ansible 2.5.0
  config file = /Users/spollock/ansible/fs-skytap-control/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
ca-spollockmb1:fs-skytap-control spollock$ python --version
Python 2.7.10
```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_REMOTE_PORT(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = spollock
DEFAULT_TIMEOUT(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = 30
RETRY_FILES_ENABLED(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = False

##### OS / ENVIRONMENT

OSX 10.11.6

##### SUMMARY

vmware_guest_facts does not return snapshot information, I would like to obtain a dict of all snapshots for a VM

##### STEPS TO REPRODUCE

doesn't exist

```yaml
- name: Gather facts from standalone ESXi server having datacenter as 'ha-datacenter'
  vmware_guest_facts:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    datacenter: ha-datacenter
    validate_certs: no
    uuid: 421e4592-c069-924d-ce20-7e7533fab926
  delegate_to: localhost
  register: facts
```

##### ACTUAL RESULTS

```

```
