### ISSUE TITLE
vmware_guest_facts or   vmware_vm_facts  does not return ESX server that it is running on.

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/ansible#33972]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

vmware_guest_facts

##### ANSIBLE VERSION

```
ca-spollockmb1:fs-skytap-control spollock$ ansible --version
ansible 2.5.0
  config file = /Users/spollock/ansible/fs-skytap-control/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
ca-spollockmb1:fs-skytap-control spollock$ python --version
Python 2.7.10
```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_REMOTE_PORT(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = spollock
DEFAULT_TIMEOUT(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = 30
RETRY_FILES_ENABLED(/Users/spollock/ansible/fs-skytap-control/ansible.cfg) = False

##### OS / ENVIRONMENT

OSX 10.11.6

##### SUMMARY

vmware_guest_facts does not return ESX server that it is running on.  I need to be able to obtain the ESX server that a VM is running on in a cluster.  (maybe vsphere modules is a better location)

##### STEPS TO REPRODUCE

doesn't exist

```yaml
- name: Gather facts from standalone ESXi server having datacenter as 'ha-datacenter'
  vmware_guest_facts:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    datacenter: ha-datacenter
    validate_certs: no
    uuid: 421e4592-c069-924d-ce20-7e7533fab926
  delegate_to: localhost
  register: facts
```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@jacksonp2008 Thanks for reporting this issue.
~~VMware does not restrict user from creating VM with already existing name. It is confusing if we return multiple ESXi hostname for such VM with same name.In case UUID, it is will be easy to return name of ESXi but question remains the same for multiple VMs with same name.
Let me know if you have any suggestion.~~

needs_info

**Comment by Akasurde** [comment]
@jctanner @dagwieers What do you think about this RFE ?

**Comment by Akasurde** [comment]
vmware_guest_facts does return ESXi hostname on which it is running 

```yaml
- name: get name of esxi server on which vm is running
  vmware_guest_facts:
    validate_certs: False
    hostname: 192.168.10.1
    username: user
    password: pass
    datacenter: ha-datacenter
    name: sample_0001
    folder: /ha-datacenter/vm/
  register: guest_facts_0001

- debug: msg="{{ guest_facts_0001['instance']['hw_esxi_host'] }}"
```

Output of above PB: 

```
TASK [vmware_guest_facts : debug] **********************************************************************************************
ok: [localhost] => {
    "msg": "DC0_H0"
}
```
Which is actual host on which this VM is running.
