### ISSUE TITLE
vsphere_guest fails to create a new vm on esxi (2.4.1 and 2.4.2)

### ISSUE THREAD

**Issue by vyyal** [ansible/ansible#33976]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vsphere_guest

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['timer']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

CentOS Linux release 7.3.1611 (Core)

##### SUMMARY

vsphere_guest  fails to create a new vm on ESXi (5.5 U2), it gives msg: "vm AUTO_gw not present".
This happens with versions 2.4.1 and 2.4.2. If I use version 2.3.1 or 2.3.2, there is no problem.

There is only the ESXI server in use. There is no vCenter in use.

##### STEPS TO REPRODUCE

```yaml

- vsphere_guest:
    vcenter_hostname: "{{ esxi_name }}"
    username: "{{ esxi_user_name }}"
    password: "{{ esxi_user_pwd }}"
    guest: "{{ server_name_prefix }}{{ inventory_hostname }}"
    resource_pool: "{{ esxi_resource_pool }}"
    state: powered_on
    vm_disk: "{{ vms_disks[inventory_hostname] }}"
    vm_nic: "{{ vms[inventory_hostname].nics }}"
    vm_hardware:
      memory_mb: "{{ vms[inventory_hostname].base.mem }}"
      num_cpus: "{{ vms[inventory_hostname].base.cpu }}"
      osid: "{{ esxi_osid }}"
      scsi: lsi
    vm_hw_version: "{{ esxi_vm_version}}"
    esxi:
      datacenter: "{{ esxi_datacenter }}"
      hostname: "{{ esxi_name }}"
    validate_certs: no
  delegate_to: localhost
```

##### EXPECTED RESULTS

I expect the vm to be created just like before, with versions 2.3.1 or 2.3.2.

##### ACTUAL RESULTS

```
TASK [esxi-vm-create : vsphere_guest] *************************************************************************************************************************************************************************
task path: /home/oper/ansible/roles/esxi-vm-create/tasks/main.yml:28
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vsphere_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1513330992.48-193957299267266 `" && echo ansible-tmp-1513330992.48-193957299267266="` echo /root/.ansible/tmp/ansible-tmp-1513330992.48-193957299267266 `" ) && sleep 0'
<localhost> PUT /tmp/tmpQE4lQg TO /root/.ansible/tmp/ansible-tmp-1513330992.48-193957299267266/vsphere_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1513330992.48-193957299267266/ /root/.ansible/tmp/ansible-tmp-1513330992.48-193957299267266/vsphere_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1513330992.48-193957299267266/vsphere_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1513330992.48-193957299267266/" > /dev/null 2>&1 && sleep 0'
ok: [gw -> localhost] => {
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "cluster": null,
            "esxi": {
                "datacenter": "ha-datacenter",
                "hostname": "Esx6.devnet.local"
            },
            "force": false,
            "from_template": null,
            "guest": "AUTO_gw",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "power_on_after_clone": true,
            "resource_pool": "/Resources/ITSTO/AUTO",
            "snapshot_to_clone": null,
            "state": "powered_on",
            "template_src": null,
            "username": "root",
            "validate_certs": false,
            "vcenter_hostname": "Esx6.devnet.local",
            "vm_disk": {
                "disk1": {
                    "datastore": "datastore1",
                    "size_gb": "16",
                    "type": "thin"
                }
            },
            "vm_extra_config": {},
            "vm_hardware": {
                "memory_mb": "4096",
                "num_cpus": "1",
                "osid": "centos64Guest",
                "scsi": "lsi"
            },
            "vm_hw_version": "vmx-08",
            "vm_nic": {
                "nic1": {
                    "network": "AUTO",
                    "network_type": "standard",
                    "type": "vmxnet3"
                },
                "nic2": {
                    "network": "VM Network",
                    "network_type": "standard",
                    "type": "vmxnet3"
                }
            },
            "vmware_guest_facts": null
        }
    },
    "msg": "vm AUTO_gw not present"
}
```
