### ISSUE TITLE
Handling of when conditional with debug and items/with_items

### ISSUE THREAD

**Issue by offlinehoster** [ansible/ansible#33985]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
debug

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### CONFIGURATION
nothing changed

##### OS / ENVIRONMENT
Ubuntu 17.10 64bit

##### SUMMARY
When using when conditional on a debug output with items/with_items it fails

##### STEPS TO REPRODUCE
mitarbeiter_list is a json output by an http api from an earlier task
username is a variable inside vars.yml which is empty like "username: '' "

```yaml
- name: show all usernames
  debug: msg={{ item }}
  with_items: "{{mitarbeiter_list|json_query('json.members.*.uid')|sort}}"
  when: not(
           (username is undefined)
           or
           (username is none)
           or
           (username | trim == '')
         )
```
##### EXPECTED RESULTS
Expected that the task will be skipped because the username var was not empty inside the vars.yml
Every other task inside this playbook is working with this when conditional fine, only the debug tasks fail.

##### ACTUAL RESULTS
```
fatal: [127.0.0.1]: FAILED! => {
    "msg": "Unexpected templating type error occurred on ({{mitarbeiter_list|json_query('json.members.*.uid')|sort}}): 'NoneType' object is not iterable"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/debug.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/debug.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by offlinehoster** [comment]
It also fails with the uri module

So maybe a general issue with "when" conditional?

```yaml
- name: Fetching JSON
  uri:
    url: https://website/{{item}}.json
    user: '{{admin_account}}'
    password: '{{admin_password}}'
    method: GET
    return_content: yes
  with_items: "{{mitarbeiter_list|json_query('json.members.*.uid')|sort}}"
  register: list
  when: not(
           (username is undefined)
           or
           (username is none)
           or
           (username | trim == '')
         )


```

```yaml
fatal: [127.0.0.1]: FAILED! => {"msg": "Unexpected templating type error occurred on ({{mitarbeiter_list|json_query('json.members.*.uid')|sort}}): 'NoneType' object is not iterable"}
```
