### ISSUE TITLE
authorized_keys fails when no permission on directory

### ISSUE THREAD

**Issue by plup** [ansible/ansible#34001]
I would like to point something out concerning the `authorized_keys` module. It's not a bug but I would appreciate if somebody knows a workaround. 

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
authorized_keys module

##### ANSIBLE VERSION
all version

##### CONFIGURATION

Nothing specific

##### OS / ENVIRONMENT
debian

##### SUMMARY

In my configuration (shared hosting) the `authorized_keys` file is kept in `/etc/ssh/authorized_keys/` folder. Let's say `/etc/ssh/authorized_keys/test` for a `test` user. 

```
$ ls -la /etc/ssh/authorized_keys/
drwxr-xr-x 2 root        root        4096 Dec 18 16:28 .
drwxr-xr-x 3 root        root        4096 Dec 12 11:51 ..
-rw------- 1 test        test         391 Dec 18 18:23 test
```

So I have the right to write new keys in the file only if I sudo in `test` first (I can't be `root`). 
```
$ echo 'smurf' | sudo -u test tee  /etc/ssh/authorized_keys/test 
smurf
```

##### STEPS TO REPRODUCE

And this is how I try to do the same thing with ansible : 

```
- name: Allow client pubkeys on the account
  become: True
  become_user: '{{appuser_user}}'
  authorized_key:
      path: '/etc/ssh/authorized_keys/{{appuser_user}}'
      manage_dir: False
      user: '{{appuser_user}}'
      key: "{{ lookup('file', '../secrets/users/' + item + '.pubkey') }}"
  with_items: '{{appuser_allowed_users}}'
```

##### EXPECTED RESULTS

So this code should write all the new keys inside the file. 

##### ACTUAL RESULTS

But instead it sends me this error : 

```
 File \"/tmp/ansible_TnFwWH/ansible_module_authorized_key.py\", line 473, in writefile
    fd, tmp_path = tempfile.mkstemp('', 'tmp', os.path.dirname(filename))
  File \"/usr/lib/python2.7/tempfile.py\", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File \"/usr/lib/python2.7/tempfile.py\", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/etc/ssh/authorized_keys/tmpHSAgh5'\r\n", "msg": "MODULE FAILURE", "rc": 1}
```

Which makes perfect sens if we look in the code : https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/authorized_key.py#L471

First a temp file is created and then it's moved to the final file. But in my case the running user has no right to create the temp file. 

What would be the way to address this "bug" or "feature" properly ? I could make a merge request if I have some guidelines.
