### ISSUE TITLE
Feature Request: vmware_guest enable portmirroring between two vms/nics

### ISSUE THREAD

**Issue by EcHoOfInSaNiTy** [ansible/ansible#34010]
##### ISSUE TYPE

 - Feature Idea

##### ANSIBLE VERSION

```
"2.5"
```

##### SUMMARY
"It would be nice to be able to create a portmirror on dvswitches, for example if I had two vms and I added them both to the same port group then I wanted a nic on one vm to be portmirrored to the other vm on a specific nic"

##### STEPS TO REPRODUCE
```
networks:
  - name: "{{portgroup}}"
    portmirror: true
    destination ""{{portid}}
    vlan: "{{vlanid}}"
    type: static
```
