### ISSUE TITLE
support xz format in archive module

### ISSUE THREAD

**Issue by pschiffe** [ansible/ansible#34037]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
archive

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/pschiffe/work/websignal/infra/ansible/ansible.cfg
  configured module search path = [u'/home/pschiffe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  3 2017, 10:55:25) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Fedora release 27 (Twenty Seven)

##### SUMMARY
Archive module should support xz format when creating archives.

##### STEPS TO REPRODUCE
```yaml
# Create a xz archive of multiple files, rooted at /path
- archive:
    path:
        - /path/to/foo
        - /path/wong/foo
    dest: /path/file.tar.xz
    format: xz
```

##### EXPECTED RESULTS
Newly created .tar.xz archive.

##### ACTUAL RESULTS
Not implemented.
