### ISSUE TITLE
False flag for recursive loop

### ISSUE THREAD

**Issue by gintautassulskus** [ansible/ansible#34034]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
variables, defaults

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### SUMMARY
Ansible cannot handle dictionary value cross-referencing.

##### STEPS TO REPRODUCE

dictionary:
```yaml
items:
  sub_item_1: value
  sub_item_2: "{{items.sub_item_1}}"
```

task:
```yaml
- debug:
    var: items.sub_item_2
```

##### EXPECTED RESULTS
debug prints out `value`

##### ACTUAL RESULTS
```
...recursive loop detected in template string: {{items.sub_item_1}}"}
```
