### ISSUE TITLE
User module and include directive : parsing problem ?

### ISSUE THREAD

**Issue by jbd** [ansible/ansible#3404]
Hello,

I'm testing with the HEAD of the day (25aaee4c38f339b4c). Same append with 1.1 and 1.2 release.

I'm trying to use the include directive with the User module but no luck, I've got a weird error which looks like a bad parsing :

```
TASK: [configure user testuser] *********************************************** 
failed: [localhost] => {"failed": true, "item": ""}
msg: Group {'ungrouped': [] does not exist

FATAL: all hosts have already failed -- aborting
```

Here is my playbook.yml file (use group that exists on your system for the value of group and groups) :

```

---
- hosts: localhost
  user: root
  tasks:
      - include: tasks/useradd.yml name=testuser uid=1234 state=present group=users groups=dialout append=yes password="799999999aSLY"
```

Here is the tasks/useradd.yml :

```

---
- name: configure user $name
  user: name="$name" uid="$uid" state="$state" group="$group" groups="$groups" append="$append" password="$password"
```

If I don't use an include directive, like that, everything is ok :

```

---
- hosts: localhost
  user: root
  tasks:
     - user: name=testuser uid=1234 state=present group=users groups=dialout append=yes password="799999999aSLY"
```
