### ISSUE TITLE
support -C, --directory=DIR in archive module, or enable a way to provide custom options

### ISSUE THREAD

**Issue by pschiffe** [ansible/ansible#34043]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
archive

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/pschiffe/work/websignal/infra/ansible/ansible.cfg
  configured module search path = [u'/home/pschiffe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  3 2017, 10:55:25) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Fedora release 27 (Twenty Seven)

##### SUMMARY
When created archive can contain only specific path to archived files (or no path, just the file) `-C, --directory=DIR` tar option has to be used. This may be tricky to implement with `extra_opts` as `path` in that case doesn't have to be absolute.

##### STEPS TO REPRODUCE
```yaml
# Compress directory /path/to/foo/ into /path/to/foo.tar.gz
- archive:
    path: foo
    dest: /path/to/foo.tar.gz
    directory: /path/to
```

Alternatively:
```yaml
# Compress directory /path/to/foo/ into /path/to/foo.tar.gz
- archive:
    path: foo
    dest: /path/to/foo.tar.gz
    extra_opts:
        - '--directory=/path/to'
```

##### EXPECTED RESULTS
Archive produced by tar with specific options.

##### ACTUAL RESULTS
Not implemented.
