### ISSUE TITLE
module: openssl_certificate unusable on RHEL 7

### ISSUE THREAD

**Issue by jsumners** [ansible/ansible#34054]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openssl_certificate

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/jsumners/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin//ansible
  python version = 2.7.14 (default, Sep 27 2017, 12:15:00) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### OS / ENVIRONMENT
Running: macOS 10.13
Target: RHEL 7.4

##### SUMMARY
This task is impossible on RHEL 7:

```
 - name: check cert expiration
   openssl_certificate:
     path: /path/to/some.crt
     provider: assertonly
     valid_in: 1209600
   register: cert_check
```

This is due to `pyOpenSSL` being a package required by default system utilities and is only available at version 0.13.1. Thus, it isn't possible to install a later version of `pyopenssl` to meet the required check without conflicting with a system package. The required check is:

https://github.com/ansible/ansible/blob/ded4e6ac0f350f2c8de9f801fc1905726c736a94/lib/ansible/modules/crypto/openssl_certificate.py#L788-L792

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/crypto/openssl_certificate.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/crypto/openssl_certificate.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @MarkusTeufelberger @Spredzy
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MarkusTeufelberger** [comment]
The 2 options here are:

* Check for every single option of that module how outdated pyOpenSSL can be to still support it and fail on various module parameters depending on the version installed
* Keep the hard requirement on 0.15+ and tell users to update (pyOpenSSL by the way is already not really maintained/developed by upstream any more, but getting a recent version of python-cryptography on RHEL would probably be an even more unrealistic scenario)

@Spredzy - It would by the way be useful if stuff like this would at least be cought or pointed out by the integration tests, as far as I understand them, they are just not run on platforms where pyOpenSSL is too old.

On topic:

In this exact use case it might be possible to get it to run, however it would also not really be supported and if you add other checks, some might simply not be possible on RHEL7 with that old version (e.g. anything that has to do with extensions). Would this help?

PS:

Set `ignore_errors: True` too and then check for `cert_check.failed`, otherwise your whole play will fail if the cert is outdated.

**Comment by jsumners** [comment]
@MarkusTeufelberger I have a solution in place:

```yaml
- name: check cert expiration
  command: openssl x509 -checkend 1209600 -noout -in /path/to/some.crt
  register: cert_check
  changed_when: cert_check.rc != 0
  failed_when: cert_check.stdout_lines|length > 0
```
