### ISSUE TITLE
support parallel composite uploads in gc_storage module, or enable a way to provide custom options

### ISSUE THREAD

**Issue by pschiffe** [ansible/ansible#34052]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
gc_storage

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/pschiffe/work/websignal/infra/ansible/ansible.cfg
  configured module search path = [u'/home/pschiffe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  3 2017, 10:55:25) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Fedora release 27 (Twenty Seven)

##### SUMMARY
When uploading large files, it's beneficial to use parallel composite upload for better speed: `gsutil -o GSUtil:parallel_composite_upload_threshold=150M cp file bucket`

##### STEPS TO REPRODUCE
```yaml
- name: Upload some content
  gc_storage:
    bucket: mybucket
    object: key.txt
    src: /usr/local/myfile.txt
    mode: put
    permission: public-read
    parallel_composite_upload_threshold: 150M
```

Alternatively:
```yaml
- name: Upload some content
  gc_storage:
    bucket: mybucket
    object: key.txt
    src: /usr/local/myfile.txt
    mode: put
    permission: public-read
    extra_opts:
        - 'GSUtil:parallel_composite_upload_threshold=150M'
```

##### EXPECTED RESULTS
It works.

##### ACTUAL RESULTS
Not implemented.
