### ISSUE TITLE
rds module's security_groups should support array type

### ISSUE THREAD

**Issue by Everspace** [ansible/ansible#34067]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
rds

##### SUMMARY

It's a little discordant that the security_groups and vpc_groups are string delineated instead of the more natural array type for this sort of thing. [Especially when they're just split apart anyway](https://github.com/ansible/ansible/blob/cc7a5228b02344658dac69c38ccb7d6580d2b4c6/lib/ansible/modules/cloud/amazon/rds.py#L1289).

##### STEPS TO REPRODUCE

```yaml
  - name: Launch DB
    rds:
      command: create
      db_name: super-honk
      security_groups:
      - AllowOfficeDB
      - AllowLocalDBAccess
      - Super-Honk-SG
```
