### ISSUE TITLE
jenkins_plugin tries to authorize to updates_url

### ISSUE THREAD

**Issue by kostiantyntravis** [ansible/ansible#34093]
Greetings,

##### ISSUE TYPE
 - Bug Report

##### Ansible version
```
ansible version 2.2.2.0
```
##### Component name
```
component name: jenkins_plugin
```
##### Summary
I'm working on migration our codebase from installing jenkins plugins with jenkins-cli to jenkins_plugin module usage. We have plenty of official plugins and few custom that located in our local Artifactory.   
We also have a username and password both for Jenkins instance and for Artifactory(allows anonymous to read packages).  
While Ansible runs plays on plugins from official source all works fine, but when i'm specifying `updates_url` for custom plugins lookup it seems that plugin tries to authorize on our Artifactory, instead of Anonymous user usage.
 
Part that uses default `updates_url` is working fine
```yaml
- name: Install versioned plugins

  jenkins_plugin:
    name        : "{{ item.name }}"
    version     : "{{ item.version }}"
    url_username: "{{ jenkins_login }}"
    url_password: "{{ jenkins_password}}"

  register: jenkins_plugins_versioned

  when: >
    item.version
    and item.download_base is not defined

  with_items: "{{ jenkins_plugins }}"
```
```json
ok: [jenkins] => (item={u'pinned': False, u'version': u'1.1', u'enabled': True, u'name': u'ace-editor'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": true,
            "group": "jenkins",
            "http_agent": "ansible-httpget",
            "jenkins_home": "/var/lib/jenkins",
            "mode": "0644",
            "name": "ace-editor",
            "owner": "jenkins",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "timeout": 30.0,
            "unsafe_writes": null,
            "updates_expiration": 86400,
            "updates_url": "https://updates.jenkins-ci.org",
            "url": "http://localhost:8080",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "use_proxy": true,
            "validate_certs": true,
            "version": "1.1",
            "with_dependencies": true
        },
        "module_name": "jenkins_plugin"
    },
    "item": {
        "enabled": true,
        "name": "ace-editor",
        "pinned": false,
        "version": "1.1"
    },
    "plugin": "ace-editor",
    "state": "present"
}
```
But when I specify our local Artifactory url like that:
```yaml
- name: Install custom plugins

  jenkins_plugin:
    name        : "{{ item.name          }}"
    updates_url : "{{ item.download_base }}"
    version     : "{{ item.version       }}"
    url_username: "{{ jenkins_login }}"
    url_password: "{{ jenkins_password}}"

  register: jenkins_plugins_custom

  when: >
    item.download_base is defined

  with_items: "{{ jenkins_plugins }}"
```
I'm getting next error:
```json
failed: [jenkins] (item={u'pinned': False, u'version': u'v1.1', u'enabled': True, u'name': u'cucumber-testresult-plugin', u'download_base': u'http://download_base:8080/artifactory/jenkins-ci'}) => {
    "details": "HTTP Error 401: Unauthorized",
    "failed": true,
    "invocation": {
        "module_args": {
            "backup": null,
            "content": null,
            "delimiter": null,
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": true,
            "group": "jenkins",
            "http_agent": "ansible-httpget",
            "jenkins_home": "/var/lib/jenkins",
            "mode": "0644",
            "name": "cucumber-testresult-plugin",
            "owner": "jenkins",
            "params": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "timeout": 30.0,
            "unsafe_writes": null,
            "updates_expiration": 86400,
            "updates_url": "http://download_base:8080/artifactory/jenkins-ci",
            "url": "http://localhost:8080",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "use_proxy": true,
            "validate_certs": true,
            "version": "v1.1",
            "with_dependencies": true
        },
        "module_name": "jenkins_plugin"
    },
    "item": {
        "download_base": "download_base:8080/artifactory/jenkins-ci",
        "enabled": true,
        "name": "cucumber-testresult-plugin",
        "pinned": false,
        "version": "v1.1"
    },
    "msg": "Plugin not found."
}
```
Here is what I see in Artifactory log
```log
20171220153609|0|REQUEST|Jenkins_instance_ip|jenkins_login|GET|/jenkins-ci/download/plugins/cucumber-testresult-plugin/v1.1/cucumber-testresult-plugin.hpi|HTTP/1.1|401|0
```
Below is an output of `curl` from jenkins instance
```
curl -I download_base:8080/artifactory/jenkins-ci/download/plugins/cucumber-testresult-plugin/v1.1/cucumber-testresult-plugin.hpi
```
```
HTTP/1.1 200 OK
Server: Artifactory/4.1.3
X-Artifactory-Id: ccf1be6ca749d915:46bf8b83:1606177180e:-8000
Last-Modified: Wed, 26 Jul 2017 13:15:08 GMT
ETag: 50ea56a2d1f91ce2ab53989db47ebb7e80c99a7c
X-Checksum-Sha1: 50ea56a2d1f91ce2ab53989db47ebb7e80c99a7c
Accept-Ranges: bytes
X-Checksum-Md5: c71fea18ad2aaa7d9e982024cb7b2bd7
X-Artifactory-Filename: cucumber-testresult-plugin.hpi
Content-Disposition: attachment; filename="cucumber-testresult-plugin.hpi"; filename*=UTF-8''cucumber-testresult-plugin.hpi
Content-Type: application/java-archive
Content-Length: 3174525
Date: Wed, 20 Dec 2017 16:01:46 GMT
```
I don't want to use jenkins-cli for just few custom plugins, because whole migration to jenkins_plugin module will be meaningless in our case. Maybe it's not a bug and I'm doing something wrong?
