### ISSUE TITLE
Roles with duplicate invocation are only executed once

### ISSUE THREAD

**Issue by velotraveler** [ansible/ansible#34115]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME
role inclusion

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/ansible/lib/python2.7/site-packages/ansible
  executable location = /home/user/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

```

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/home/user/.ansible.cfg) = -o Protocol=2

##### OS / ENVIRONMENT
Manager host is RHEL 7.3

##### SUMMARY
Playbook has a list of roles to execute. If a role is repeated multiple times in the list, it is only executed the first time. If I use dict syntax to invoke the role, and add parameters to the role so that the duplicate invocations are slightly different, then the role gets executed as expected provided there are no exact duplicates in the role arguments.

##### STEPS TO REPRODUCE
* Create a role that just prints some debug output.  Sample role below.
* Invoke the role multiple times from a play
* The role only executes once.
* Edit the playbook to disambiguate the role invocations (see WORKAROUND below)
* The role now executes once for each unique invocation

Sample role used in test:
$ cat roles/do-nothing/tasks/main.yml
```yaml
---

- name: do nothing
  debug:
    var: ansible_version
```

Sample playbook used to reproduce:
$ cat nothing1.yml

```yaml
---

 - hosts: "{{ host_to_upgrade }}"

   gather_facts: false

   roles:
     - do-nothing
     - do-nothing
     - do-nothing

```

##### EXPECTED RESULTS
We should see the role "do-nothing" get run three times.

##### ACTUAL RESULTS
```
$ ansible-playbook -i ../hosts.test -e host_to_upgrade=njwdev1 nothing1.yml 

PLAY [njwdev1] *****************************************************************

TASK [do-nothing : do nothing] *************************************************
ok: [njwdev1] => {
    "ansible_version": {
        "full": "2.4.2.0", 
        "major": 2, 
        "minor": 4, 
        "revision": 2, 
        "string": "2.4.2.0"
    }
}

PLAY RECAP *********************************************************************
njwdev1                    : ok=1    changed=0    unreachable=0    failed=0   
```

#### WORKAROUND
This playbook shows how I'm working around the problem:
```yaml
---

 - hosts: "{{ host_to_upgrade }}"

   gather_facts: false

   roles:
     - do-nothing
     - { role: do-nothing, disambiguate_kludge: 1 }
     - { role: do-nothing, disambiguate_kludge: 2 }
```
* Note: If "disambiguate_kludge" is set to "1" instead of "2" in the 3rd role line above, then the role only executes twice.
