### ISSUE TITLE
copy module destroys selinux contexts

### ISSUE THREAD

**Issue by candlerb** [ansible/ansible#3412]
The following happened after upgrading to ansible 1.2 from Ubuntu PPA - ansible machine is ubuntu 12.04, target is CentOS 6.4. I don't think anything like this happened with 1.1, but I have not tried to replicate it with 1.1

Issue: pushing out configurations to a fresh CentOS 6.4 box using the "copy"
module, I had serious breakage due to files losing their selinux markings.

The relevant ansible configs are:

```
tasks:
  - name: install /etc/security/limits.conf
    action: copy src=files/limits.conf dest=/etc/security/limits.conf mode=644

tasks:
  - action: copy src=files/storage/centos/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600
    notify: restart iptables
handlers:
  - name: restart iptables
    action: service name=iptables state=restarted~~~
```
### Updating /etc/security/limits.conf

After updating, ansible-playbook stopped at this point:

```
TASK: [install /etc/security/limits.conf]
*************************************
changed: [storage6.int.example.com]

TASK: [yum name=strace state=installed]
***************************************
fatal: [storage6.int.example.com] => failed to open a SFTP connection
(EOF during negotiation)

FATAL: all hosts have already failed -- aborting

PLAY RECAP
********************************************************************
           to retry, use: --limit
@/var/tmp/ansible/storage-centos.yaml.retry

storage6.int.example.com : ok=23   changed=17   unreachable=1    failed=0
```

After this, I was completely unable to login to the target box either by ssh
or at the console, even after a reboot, either as a normal user or root.

Logging in at the console, I briefly saw a flash of

"Error in service module"

before the screen cleared and showed the login prompt again.

I was able to fix the problem by rebooting into single-user mode and running

```
restorecon -v /etc/security/limits.conf
```
### Updating /etc/sysconfig/iptables

Restarting the playbook after fixing the above, another problem arose:

```
TASK: [copy src=files/storage/centos/iptables dest=/etc/sysconfig/iptables owner=root group=root mode=600] ***
changed: [storage6.int.example.com]

...

NOTIFIED: [restart iptables]
**************************************************
failed: [storage6.int.example.com] => {"failed": true, "item": ""}
msg: Can't open /etc/sysconfig/iptables: Permission denied
```

Again I was able to fix the problem using restorecon. This time I took a
note of the selinux tags before and after:

```
[root@storage6 ~]# ls -Z /etc/sysconfig/iptables
-rw-------. root root unconfined_u:object_r:admin_home_t:s0 /etc/sysconfig/iptables
[root@storage6 ~]# restorecon -v /etc/sysconfig/iptables
restorecon reset /etc/sysconfig/iptables context unconfined_u:object_r:admin_home_t:s0->unconfined_u:object_r:system_conf_t:s0
[root@storage6 ~]# ls -Z /etc/sysconfig/iptables
-rw-------. root root unconfined_u:object_r:system_conf_t:s0 /etc/sysconfig/iptables
```

My guess is that ansible's copy module is copying the file under a new name
and mv'ing it into place, and so it is losing the selinux tagging of the
original file.
