### ISSUE TITLE
until loop counter not available for tests

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#34139]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

task executor
##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Task with `until` loop can not be evaluated by `attempts`
##### STEPS TO REPRODUCE

Run this playbook several times

```yaml
- hosts: localhost
  tasks:
    - name: test shell
      shell: "head -c 100 /dev/urandom | grep -o '[0-9]' | head -c 1"
      register: sh_res
      until: sh_res.stdout|int > 5
      retries: 10
      delay: 1
      changed_when: sh_res.attempts > 1
```

##### EXPECTED RESULTS

`attempts` attribute is accessible in `changed_when` test, task reports changed if it took more than 1 attempt.
##### ACTUAL RESULTS

`attempts` attribute is not defined in `changed_when` test

```
The conditional check 'sh_res.attempts > 1' failed. The error was: error while evaluating conditional (sh_res.attempts > 1): 'dict object' has no attribute 'attempts'
```
