### ISSUE TITLE
Ovirt_vms creates vm with thin provisioned disk from a preallocated disk template

### ISSUE THREAD

**Issue by mkrish004c** [ansible/ansible#34154]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
```
ovirt_vms
```

##### ANSIBLE VERSION
```
ansible 2.3.1.0
```

##### CONFIGURATION
Default ansible configuration

##### OS / ENVIRONMENT
```
RHEL 7.3
```
##### SUMMARY
When creating a VM from a template that has preallocated disk in it results in a VM with thin provisioned disk by default.

##### STEPS TO REPRODUCE

1. Make sure you have the template in place with a preallocated disk attached to it.
2. Template disk information as below,

```
Alias        Virtual Size Actual Size Status Allocation Policy   Interface        Type  Creation Date
aio_disk_0    60 GB	   60 GB	OK  	Preallocated	 VirtIO-SCSI	  Image	  12/20/17    
```
3. Create the VM using the template
```
- name: Creating VM
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: stopped
    cluster: "PE-LAB1"
    name: "test-vm1"
    template: "template1"
```

##### EXPECTED RESULTS
When you create manually from GUI, it creates a new VM with a "preallocated" copy of the disk.

##### ACTUAL RESULTS
It results in a new VM with a "thin provisioned" copy of the disk.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/ovirt/ovirt_vms.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_vms.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @machacekondra @mwperina
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrish004c** [comment]
Also, tried the below one on Ansible version 2.4.0.0

```
- name: Creating VM
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: stopped
    cluster: "PE-LAB1"
    name: "test-vm1"
    template: "template1"
    storage_domain: "VM_DATA"
    disk_format: "raw"
```

Actual result 
```
"msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot add VM. Thin provisioned template disks can not be defined as Raw.]\". HTTP response code is 400."
```

the template disk is "preallocated" but it gives wrong error!

**Comment by machacekondra** [comment]
@mkrish004c All the templates disks are `preallocated`? Or just some of them?

**Comment by mkrish004c** [comment]
@machacekondra, All the templates are pre-allocated, not sure about the error message 
```"msg": "Fault reason is \"Operation Failed\". Fault detail is \"[Cannot add VM. Thin provisioned template disks can not be defined as Raw.]\". HTTP response code is 400."```

but i can clone a template disk with the disk property by enabling clone flag in ovirt_vms as below.

```
- name: Creating VM
  ovirt_vms:
    auth: "{{ ovirt_auth }}"
    state: stopped
    cluster: "PE-LAB1"
    name: "test-vm1"
    template: "template1"
    clone: true
```
