### ISSUE TITLE
gconftool2 module fails to update gconf.xml.mandatory with default values

### ISSUE THREAD

**Issue by jenglish** [ansible/ansible#34161]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gconftool2 module

##### ANSIBLE VERSION
ansible 2.3.2.0
  config file = /home/people/joe/prj/ssp/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

##### CONFIGURATION
Stock configuration from ansible-2.3.2.0-1.el6.noarch RPM (CentOS 6, EPEL)

##### OS / ENVIRONMENTansible-2.3.2.0-1.el6.noarch
CentOS 6

##### SUMMARY
The gconftool2 module checks the current value of a key and skips setting it if the value already matches; however it does not pay attention to 'config_source' or 'direct' when getting the key.

Consequently, trying to make a default value mandatory has no effect.

##### STEPS TO REPRODUCE
```
- name: Do not allow users to turn off screensaver
  gconftool2:
    config_source: xml:readwrite:/etc/gconf/gconf.xml.mandatory
    direct: yes 
    state: present
    key: /apps/gnome-screensaver/lock_enabled
    value: true
    value_type: bool
```

##### EXPECTED RESULTS
This should add an element like:
```
        <entry name="idle_activation_enabled" mtime="1513883572" type="bool" value="true"/>
```
to /etc/gconf/gconf.xml.mandatory/apps/gnome-screensaver/%gconf.xml

##### ACTUAL RESULTS

`ansible-playbook` reports "ok",  and gconf.xml.mandatory tree is not updated.
