### ISSUE TITLE
aci_rest: Attributes are missing, tag 'attributes' must be specified first, before any other tag

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#34175]
_From @dagwieers on October 25, 2017 12:38_

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aci_

##### ANSIBLE VERSION
v2.5

##### SUMMARY
When you use the YAML or JSON payload format, ACI requires an `attributes` entry even when there are no attributes needed. It will complain with:
```
Attributes are missing, tag 'attributes' must be specified first, before any other tag
```
You can add an empty attributes entry by doing `attributes: {}` like the example below:
```yaml
 - name: Create a switch profile
    aci_rest:
      <<: *aci_login
      path: /api/policymgr/mo/uni.json
      method: post
      content:
        infraInfra:
          attributes: {}
          children:
          - infraNodeP:
-cut-
```

We could make aci_rest add empty attributes-entries if they are missing.

_Copied from original issue: datacenter/aci-ansible#167_

**Comment by dagwieers** [comment]
So this change ought to go into xmljson as well.

**Comment by dagwieers** [comment]
The implementation in xmljson was already correct. So the question is, should we be rewriting the user's payload, or do we expect the user knows what he's doing.

I prefer not to rewrite the payload, but add a note to the aci_rest module.

**Comment by ogenstad** [comment]
I ran into this while testing, would almost consider this to be a but within ACI.

**Comment by dagwieers** [comment]
Yeah, it would be better if the APIC would be more liberal to what it accepts, however the documentation explicitly mentions this, so I doubt the vendor will be fixing this.

**Comment by dagwieers** [comment]
@ogenstad I wanted to document this issue better and tried to reproduce this, but no longer can with the examples I come up with. Would you happen to have a reproducer for this ?

**Comment by dagwieers** [comment]
I improved the documentation for the case where `children` was provided, but no (empty) `attributes` was set. I also fixed an issue with the **aci_rest** error handling that was recently introduced.

**Comment by ogenstad** [comment]
Ok, I hear you perhaps just a strange design choice.

>I prefer not to rewrite the payload, but add a note to the aci_rest module.

I would say just fail with a more meaningful error message.

**Comment by ogenstad** [comment]
@dagwieers, got an email with a request for an example playbook. Can't find it here now..

Anyway with this playbook:
```yaml
---
- name: Create VRF
  aci_rest:
    path: '/api/node/mo/uni/tn-{{ tenant }}.json'
    hostname: '{{ hostname }}'
    username: '{{ username }}'
    password: '{{ password }}'
    validate_certs: '{{ validate_certs }}'
    method: post
    content: 
      "{{ vrf_data }}"
```

The VRF data variable looks like this:
```yaml
vrf_data:
  fvTenant:
    attributes: {}
    children:
      - fvCtx:
          attributes:
            name: REST_VRF_21
      - fvCtx:
          attributes:
            name: REST_VRF_22
```

Removing the attribute key makes it fail.
