### ISSUE TITLE
delegate_facts does not work with include_role

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#34187]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible

##### ANSIBLE VERSION

```ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/amarao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14+ (default, Dec  5 2017, 15:17:02) [GCC 7.2.1 20171205]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 16
DEFAULT_SUDO_FLAGS(/etc/ansible/ansible.cfg) = -H -S
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
If delegate_facts used together with include_role, all facts set in that role are not delegated to hosts (they are set to original host).

##### STEPS TO REPRODUCE
role1/tasks/main.yaml:
```yaml
---
- set_fact:
    AFOO: BAR
```
play1.yaml
```yaml
---
- hosts: 127.0.0.1
  gather_facts: no
  tasks:
  - include_role:
      name: role1
    delegate_to: localhost
    delegate_facts: yes

  - debug: var=hostvars
```

command-line:

ansible-playbook -i localhost,127.0.0.1 play.yaml

(I've checked it with normal different hosts, 'double localhost' does not change anything))

##### EXPECTED RESULTS
AFOO=Bar for localhost (host whom role was delegated)

##### ACTUAL RESULTS
AFOO=BAR for 127.0.0.1 (original host)
