### ISSUE TITLE
vmware_guest: state poweredon is not done when task is async and vm doesn't exist

### ISSUE THREAD

**Issue by balonik** [ansible/ansible#34191]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT
RHEL 7.4
pyvmomi (6.5.0.2017.5-1)
vCenter 6.0

##### SUMMARY
vmware_guest param state: powerdon is not working when async task is used and vm needs to be created.
module works as expected when the "async" and "poll" are omitted.

##### STEPS TO REPRODUCE
1. make sure VM doesn't exist, deleting it from esx/vmware
2. run playbook including task below

```yaml
vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"
      datacenter: "{{ datacenter }}"
      folder: "{{datacenter}}/vm/{{ folder }}"
      name: "{{name}}"
      state: poweredon
      template: "{{template}}"
      cluster: "{{cluster}}"
      networks:
      - type: static
        name: "{{portgroup}}"
        ip: "{{ip}}"
        netmask: "{{netmask}}"
        gateway: "{{gateway}}"
        domain: "{{domain}}"
      wait_for_ip_address: yes
      customization:
        dns_servers: "{{dns_servers}}"
        domain: "{{domain}}"
    register: deploy
    delegate_to: localhost
    when: not ansible_check_mode
    async: 1
    poll: 0
```
##### EXPECTED RESULTS
VM is created and in Powered On state

##### ACTUAL RESULTS
VM is created, but in Powered Off state

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by balonik** [comment]
Hi,
I have also tried to get around it by using async_status, waiting for the task to finish and powering VM in another task. I never get past the async_status task. It seems the vmware_guest task never finishes, even after 1 minute the async task cache was still
{"started": 1, "finished": 0, "ansible_job_id": "150814510047.14804"}
and the async_status failed.

Tasks:
```
-  name: create vm even if poweredoff state
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"
      datacenter: "{{ datacenter }}"
      folder: "{{datacenter}}/vm/{{ folder }}"
      name: "{{name}}"
      state: poweredon
      template: "{{template}}"
      cluster: "{{cluster}}"
      networks:
      - type: static
        name: "{{portgroup}}"
        ip: "{{ip}}"
        netmask: "{{netmask}}"
        gateway: "{{gateway}}"
        domain: "{{domain}}"
      wait_for_ip_address: yes
      customization:
        dns_servers: "{{dns_servers}}"
        domain: "{{domain}}"
    register: deploy
    delegate_to: localhost
    when: not ansible_check_mode
    async: 1
    poll: 0
- name: Wait for the VM creation to finish
   async_status: jid={{ deploy.ansible_job_id }}
   register: deploy_result
   until: deploy_result.finished
   retries: 60
   delegate_to: localhost
- name: Poweron the VM
   vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: "{{ validate_certs }}"
      datacenter: "{{ datacenter }}"
      folder: "{{ datacenter }}/vm/{{ folder }}"
      name: "{{vm_name}}"
      state: poweredon
      cluster: "{{cluster}}"
   delegate_to: localhost
   when: not ansible_check_mode
```
