### ISSUE TITLE
vmware_guest: cannot relocate VM to a different datastore on the same vHost

### ISSUE THREAD

**Issue by nikitakazantsev12** [ansible/ansible#34195]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
```
vmware_guest
```

##### ANSIBLE VERSION

```
ansible 2.3.2.0
```

##### OS / ENVIRONMENT
```
RHEL 6.9
```

##### SUMMARY
```
 vmware_guest module won't move VM to a different datastore on the same vHost
```

##### STEPS TO REPRODUCE
```
Run vmware_guest module pointing to an existing VM and to a different datastore on the same ESXi Host under disk configuration.
```

```yaml
- name: change datastore
  vmware_guest:
    hostname: vcenter_host
    username: vcenter_user
    password: vcenter_pass
    datacenter: datacenter
   esxi_hostname: esxi_host
    validate_certs: false
    name: vm_name
    disk:
      - size_gb: 50
        datastore: new_datastore
```

##### EXPECTED RESULTS
```
VM is moved to another datastore
```

##### ACTUAL RESULTS
```
VM stays on the datastore where it was located initially. The task run reports no changes, all green.
```
