### ISSUE TITLE
include_role: does not respect tags

### ISSUE THREAD

**Issue by ocervell** [ansible/ansible#34196]
**ISSUE TYPE**
Bug Report

**COMPONENT NAME**
`include_role`

**ANSIBLE VERSION**
ansible 2.5.0

**OS / ENVIRONMENT**

Centos 7

**SUMMARY**
`include_role` does not respect tags and overrides tasks tags when `tags` is passed.

**STEPS TO REPRODUCE**

***roles/common/tasks/main.yml***
```
- name: Task 1
  debug: name="task no.1"
  tags:
    - task_1

- name: Task 2
  debug: name="task no.2"
  tags:
    - task_2

- name: Task 3
  debug: name="task no.3"
  tags:
    - task_3
```

***play.yml***
```
- name: test playbook
  hosts: localhost
  tasks:
    - include_role:
         name: common
```

***command***
`ansible-playbook play.yml --tags task_1`

**EXPECTED RESULT**
The playbook should execute `Task 1` when running the above command.

**ACTUAL RESULTS**
The `include_role` statement is being skipped.

**TEMPORARY FIXES**

***Solution 1***
I was able to make this work was by explicitly listing all the tags used by the tasks within my role  in the `include_role` statement, like so:

```
- name: test playbook
  hosts: localhost
  tasks:
    - include_role:
         name: common
      tags:
         - task_1
         - task_2
         - task_3
```

... but this feels hacky because ***you have to go through every task in the role and list them*** ... This can be problematic when you have tons of tasks, each with different tags.

***Solution 2***
IMHO, another thing that ***should*** work in this case is specifying 'always' tags and expect the respective tasks in the role to honour their own tags:

***play.yml***
```
- name: test playbook
  hosts: localhost
  tasks:
    - include_role:
         name: common
      tags: always
```
... but with this, **all the tasks within the role will run ignoring whatever tags are passed on the CLI.**

***Solution 3***
Use the old `include` statement ...

The following playbook works fine (but unfortunately it is ***deprecated*** and ***doesn't honour role default variables***):

```
- name: test playbook
  hosts: localhost
  tasks:
    - include: roles/common/tasks/main.yml
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/role/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ymagriso** [comment]
I am also experiencing a similar issue in this area.
I need to use include_role for running the role multiple times (in a loop).
The role includes several tags and I want to skip some of them using "--skip-tags tag1,tag2" (where tag1 and tag2 are defined on some of the role's tasks).
Unfortunately, the "--skip-tags tag1,tag2" does not have an effect on the playbook's execution.
When I run the ansible-playbook command with "--list-tags", only the playbook's tags are listed and the tags defined under the role executed via include_role are not.

Execute the following command on the same playbook provided in this issue's details:
```
ansible-playbook --list-tags play.yml
```

### Expected
All playbook's tags along with all roles tags are listed and respected (including roles' tags for roles executed via 'include_role').

### Actual
Only tags defined in the playbook are listed (and respected).

**Comment by ymagriso** [comment]
@ocervell thanks for the workaround (solution 1) provided in the issue's details.
It is working, but as you mentioned, a permanent solution for the issue should be provided.

**Comment by grassyknolling** [comment]
To expand on the workarounds from @ocervell, if you want to execute only a subset of tasks from a role then you would need to use a different tag on the role...

**roles/common/tasks/main.yml**
```
- name: Task 1
  debug: name="task no.1"
  tags:
    - task_1

- name: Task 2
  debug: name="task no.2"
  tags:
    - task_2

- name: Task 3
  debug: name="task no.3"
  tags:
    - task_3
```
**play.yml**
```
- name: test playbook
  hosts: localhost
  tasks:
    - include_role:
         name: common
      tags:
        - role_1
```
**command**
```
ansible-playbook play.yml --tags role_1,task_1
```
...otherwise you will always include or skip all included tasks.

**Comment by dss010101** [comment]
it seems to be that 'include' suffers from the same problem.  if you try to include a task from file and filter by tags, it will still run all the tasks, ignoring the task.

**Comment by miguelfito** [comment]
Same here with ansible 2.4.3.0

**Comment by ckotte** [comment]
I use Ansible 2.4.3.0 and non of the workarounds work for me. All tasks of the imported role are executed..

**Comment by jmighion** [comment]
Have the same problem with include_tasks. Using the old include works for now, but is deprecated.

No tags from within the included tasks are picked up
```
include_tasks: "{{ device_os }}.yml"
```

Currently works but is deprecated
```
include: "{{ device_os }}.yml"
```

**Comment by sivel** [comment]
This is working as expected.  However in ansible 2.5 changes have been made to make this more predictable.

tags inside of an include do not bubble up to the include itself.  In 2.5 tags applied to an include do not merge down onto the tasks within.

It is the intention that tags and arguments applied to an include affect the include itself, and not the tasks within.

Using a task like the following in 2.5 works as expected:

```
    - include_role:
        name: include_role
      tags:
        - always
```

The `always` tag is only applied to the `include_role` allowing it to always be included.  So if `include_role` had a task within tagged as `include_role_task1` and you executed your playbook with just `-t include_role_task1`, then that `include_role` would act as expected.

```
TASK [include_role] **************************************************************************************************************************************************************************************************************************

TASK [include_role : debug] ******************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "include_role"
}
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by vdweij** [comment]
This behavior for Ansible version 2.4.3.0 is very problematic. Tags applied to an include_role apply to every task within that role. So adding an always tag to the include_role results in Ansible executing every tasks within that role.

As @ckotte mentioned none of the mentioned workaround work. Basically it is impossible in this version of Ansible to only execute tagged tasks within a role that are included within the playbook via include_role.

But using import_role does solve this.

**Comment by ckotte** [comment]
@vdweij: 

You can upgrade to Ansible 2.5 and do this:

Use always tag for all include_roles which basically means the role will always be included.

**playbook.yml**
```- { include_role: name=base, tags: always }```

Tag all tasks with a role tag and more specific tags if you want.

**role/main.yml**
```
- name: Set the hostname
  tags: base, hostname
  [...]

- name: Set timezone and clock
  tags: base, time, clock
  [...]
```

**command**
Execute all tasks of base role:
`ansible-playbook playbook.yml --tags base`

Execute all tasks tagged with time:
`ansible-playbook playbook.yml --tags time`

**Comment by eburgueno** [comment]
@sivel I'm sorry, can you please clarify what is the intended behaviour? I understand tags inside the included role not bubbling up to the one that is including it. But the syntax below does not work as expected.

**roles/common/tasks/main.yml**
```
- block:
  - name: Include some role
    include_role:
      name: another role
  tags: mytag
```

**playbook.yml**
```
---
- hosts: host1
  roles:
    - common
```
**result**
```
$ ansible-playbook --tags=mytag playbook.yml
PLAY [host1] 

TASK [Gathering Facts] 
ok: [host1]

TASK [common : Include some role]

PLAY RECAP 
host1                   : ok=1    changed=0    unreachable=0    failed=0   
```

**Comment by sivel** [comment]
@eburgueno that block syntax only works as of v2.5.2.  Previous versions had a bug that prevented that from working.

**Comment by eburgueno** [comment]
@sivel thank you!  I forgot to mention I'm on 2.5.0. Will upgrade.

**Comment by willthames** [comment]
Using 2.5.6 or 2.6.1, I still encounter this problem

Playbook
```
- hosts: localhost
  connection: local

  tasks:
    - block:
      - include_role:
          name: common
      tags: always
```

Role:

```
$ cat roles/common/tasks/main.yml 
- block:
  - name: Try mytag task
    debug:
      msg: my tag
  tags: mytag

- block:
  - name: Try anothertag task
    debug:
      msg: another tag
  tags: anothertag
```

include_role appears to respond to the `tags: always` rather than the `--tags=anothertag`

```
$ ansible-playbook playbook.yml -vv -t anothertag
ansible-playbook 2.6.1
  config file = None
  configured module search path = [u'/Users/will/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /Users/will/src/opensource/ansible/bin/ansible-playbook
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
No config file found; using defaults
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: playbook.yml ************************************************************************************************************************************************************************************************************************
1 plays in playbook.yml

PLAY [localhost] ******************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************************************************
task path: /Users/will/tmp/ansible/issue-34196/playbook.yml:1
ok: [localhost]
META: ran handlers

TASK [include_role : common] ******************************************************************************************************************************************************************************************************************
task path: /Users/will/tmp/ansible/issue-34196/playbook.yml:6

TASK [common : Try mytag task] ****************************************************************************************************************************************************************************************************************
task path: /Users/will/tmp/ansible/issue-34196/roles/common/tasks/main.yml:2
ok: [localhost] => {
    "msg": "my tag"
}

TASK [common : Try anothertag task] ***********************************************************************************************************************************************************************************************************
task path: /Users/will/tmp/ansible/issue-34196/roles/common/tasks/main.yml:8
ok: [localhost] => {
    "msg": "another tag"
}
META: ran handlers
META: ran handlers

PLAY RECAP ************************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

I'd like to use include_role with tags.

I'm pretty sure `ansible_run_tags` variable could help with this but there's a minor bug that I'll raise separately.

**Comment by willthames** [comment]
https://github.com/ansible/ansible/issues/42492 raised for the problem of using `ansible_run_tags` variable with `include_role`

**Comment by willthames** [comment]
So,

```
    - block:
      - include_role:
          name: common
        tags: always
```

works, but

```
    - block:
      - include_role:
          name: common
      tags: always
```

does not (which I think is what @sivel was suggesting was fixed from 2.5.2 onwards)

**Comment by GMartinez-Sisti** [comment]
I'm having the same issue with 2.6.1. I'm trying to include a role that has a tag named "config", but the role either runs all the tasks within, when the tag provided is part of the include_role statement, or it doesn't run at all.

Can we get some more clarity on this issue please?

**Comment by willthames** [comment]
@GMartinez-Sisti as long as you have your `include_role` have `tags: always` and not inside a `block` with `tags` set, it should work. So it should look my first example just above, not like my second example.

If you're still stuck, post the bit of your playbook you're having problems with and I'll take another look

**Comment by GMartinez-Sisti** [comment]
Thanks @willthames, I'm trying to call the `elastic.elasticsearch` role (https://github.com/elastic/ansible-elasticsearch) which has the tags:
- [always, config, install, java, plugins, scripts, templates, xpack]

Here is my setup:

**playbook.yml**
```
---
- hosts: localhost
  roles:
    - custom_role
```
**custom_role/tasks/main.yml**
```
[...]

- name: App Elasticsearch
  include: app_elasticsearch.yml
  tags: elasticsearch
```

**custom_role/tasks/app_elasticsearch.yml**
```
---
- name: Include elastic
  include_role:
    name: elastic.elasticsearch
  vars:
    [...]
  tags:
    - always
```

I'm calling the playbook with:
- `ansible-playbook -i "localhost," --connection=local --become --tags=elasticsearch,config playbook.yml`

With this config the `elastic.elasticsearch` role plays the file `elasticsearch.yml` which has a tag named `install`. Unless I'm missing something, this file should be skipped.

**Comment by willthames** [comment]
In this instance, the `tags: elasticsearch` applies the `elasticsearch` tag to everything in the included tasks file. 

The quickest fix is to remove `tags: always` from your custom_role/tasks/main.yml. 

However, `include` is being replaced by `include_tasks`, and `include_tasks` seems to have the same rules as `include_role`, so to be future proof, use `include_tasks` with `tags: always`.

**Comment by MaesterZ** [comment]
I am still encountering this issue in ansible `2.6.3`, I used @ckotte trick as workaround.

**Comment by systematicguy** [comment]
@david-dumas I just had this issue 20 minutes ago with 2.6.2 and tagging the include_role with always was enough to resolve it as @sivel presented. Maybe I can help you as fate brought us together working with the same feature. What is the skeleton of your layout?

UPDATE: Never mind, I rechecked and saw that ckotte and sivel had the same solution.

**Comment by deoren** [comment]
> @sivel: tags inside of an include

Do you mean the deprecated `include` statement or *any* of the `include_` statements (e.g., `include_role`, `include_tasks`)? 

> @sivel: do not bubble up to the include itself.

Could you elaborate on this? 

My understanding when reading the documentation is that `include_tasks` statements without any tags applied would still be executed if tags are specified on the command-line with the intent of limiting which tasks run inside the included files. I thought that tasks within those include files that have tags specified could still be toggled from the command-line, even if the `include_roles` and `include_tasks` statements do not specify tags at that level.

I found this remark in the [Tags](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html) documentation, but it's not clear to me:

> There is no way to ‘import only these tags’; you probably want to split into smaller roles/includes if you find yourself looking for such a feature.

Is this what you are referring to by "bubbling up"?

## Background

I have been learning and heavily refactoring a playbook and role for some time. Initially I tested by specifying tags, but continued refactoring and testing just by limiting specific test hosts to run the plays against. Now that I've converted the main playbook and role to use `include_role` and `include_tasks` statements I found that I am also affected by the bug noted here and on #30882: the tasks with tags specified within included role/tasks file no longer run when I specify a tag at the command-line (e.g., `--tags TAG_NAME_HERE`)

I encountered this with Ansible 2.7.1, but updated to 2.7.2 and confirmed that the issue is still present.

I've attempted to strip the playbook/role down to the essentials, but still clearly convey the intent.

## Example playbook and role snippets

The files below demonstrate the issue. They are also available in a repo here:

- https://github.com/deoren/ansible-examples/commits/i34196

### main file

```yaml
# mass-updates.yml

- name: Login to all hosts (in inventory) in order to collect Ansible Facts
  hosts: all
  gather_facts: yes
  tasks:
    - name: Create dynamic host groups based on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

- name: Update shared database servers
  hosts: dbs
  become: yes
  gather_facts: no
  serial: 1
  vars:
    systems_to_reboot: []

    # Disallow rebooting by default since this db server provides service
    # for multiple systems
    allow_reboot: false
  tasks:
    - name: Apply mass-updates role
      include_role:
        name: mass-updates

- name: Update test systems, exclude key systems
  hosts: testing:!monitoring:!dbs
  become: yes
  gather_facts: no
  vars:
    systems_to_reboot: []

    # rebooting these systems should be safe enough, provided
    # that we do not run this playbook during prime business hours
    allow_reboot: true
  tasks:
    - name: Apply mass-updates role
      include_role:
        name: mass-updates

- name: Update core systems (skip groups already processed)
  hosts: tier1:!monitoring:!dbs
  become: yes
  gather_facts: no
  vars:
    systems_to_reboot: []

    # rebooting these systems should ideally only be done during scheduled
    # maintenance windows
    allow_reboot: false
    update_core_servers: false
  tasks:
    - name: Apply mass-updates role
      include_role:
        name: mass-updates
      # Defaults to false. This has to be overriden at command-line to run.
      when: update_core_servers

```

### role - main file

```yaml

# roles/mass-updates/main.yml

- name: Check for patches, send in report to ticketing system of available updates
  include_tasks: prep.yml
```

### role - included file

```yaml
# roles/mass-updates/prep.yml

# Fetch scripts needed for patching work
- name: Task 1
  debug:
    msg: Task 1
  changed_when: False
    # Tagging with "check", "report" since this script is needed for those tasks
  tags:
    - fetch
    - check
    - report

- name: Task 2
  debug:
    msg: Task 2
  changed_when: False
    # Tagging with "check", "report" since this script is needed for those tasks
  tags:
    - fetch
    - check
    - report

- name: Task 3
  debug:
    msg: Task 3
  changed_when: False
    # Tagging with "check", "report" since this script is needed for those tasks
  tags:
    - fetch
    - check
    - report
```

## Required changes

Once these changes are made then the playbook *appears* to function as intended:

```diff
diff --git a/mass-updates.yml b/mass-updates.yml
index 1a43e47..7e96412 100644
--- a/mass-updates.yml
+++ b/mass-updates.yml
@@ -21,7 +21,7 @@
     allow_reboot: false
   tasks:
     - name: Apply mass-updates role
-      include_role:
+      import_role:
         name: mass-updates

 - name: Update test systems, exclude key systems
@@ -36,7 +36,7 @@
     allow_reboot: true
   tasks:
     - name: Apply mass-updates role
-      include_role:
+      import_role:
         name: mass-updates

 - name: Update core systems (skip groups already processed)
diff --git a/roles/mass-updates/tasks/main.yml b/roles/mass-updates/tasks/main.yml
index 5dd67cf..89f3ac3 100644
--- a/roles/mass-updates/tasks/main.yml
+++ b/roles/mass-updates/tasks/main.yml
@@ -1,6 +1,6 @@
 ---

 - name: Check for patches, send in report to ticketing system of available updates
-  include_tasks: prep.yml
+  import_tasks: prep.yml
```

## Example output

This is before the changes:

```shell
$ ansible-playbook mass-updates.yml -e "update_core_servers=true" --list-tags --list-hosts

playbook: mass-updates.yml

  play #1 (all): Login to all hosts (in inventory) in order to collect Ansible Facts	TAGS: []
    pattern: [u'all']
    hosts (5):
      db1
      db2
      localbox
      important1
      nag1
      TASK TAGS: []

  play #2 (dbs): Update shared database servers	TAGS: []
    pattern: [u'dbs']
    hosts (2):
      db1
      db2
      TASK TAGS: []

  play #3 (testing:!monitoring:!dbs): Update test systems, exclude key systems	TAGS: []
    pattern: [u'testing:!monitoring:!dbs']
    hosts (1):
      localbox
      TASK TAGS: []

  play #4 (tier1:!monitoring:!dbs): Update core systems (skip groups already processed)	TAGS: []
    pattern: [u'tier1:!monitoring:!dbs']
    hosts (1):
      important1
      TASK TAGS: []
```

This is after:

```shell
$ ansible-playbook mass-updates.yml -e "update_core_servers=true" --list-tags --list-hosts

playbook: mass-updates.yml

  play #1 (all): Login to all hosts (in inventory) in order to collect Ansible Facts	TAGS: []
    pattern: [u'all']
    hosts (5):
      db1
      db2
      localbox
      important1
      nag1
      TASK TAGS: []

  play #2 (dbs): Update shared database servers	TAGS: []
    pattern: [u'dbs']
    hosts (2):
      db1
      db2
      TASK TAGS: [check, fetch, report]

  play #3 (testing:!monitoring:!dbs): Update test systems, exclude key systems	TAGS: []
    pattern: [u'testing:!monitoring:!dbs']
    hosts (1):
      localbox
      TASK TAGS: [check, fetch, report]

  play #4 (tier1:!monitoring:!dbs): Update core systems (skip groups already processed)	TAGS: []
    pattern: [u'tier1:!monitoring:!dbs']
    hosts (1):
      important1
      TASK TAGS: []
```

## Addendum

After writing all of this up, I looked back over the [Tags](https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html) documentation and saw what I likely missed the last few times I looked over the docs:

> To use tags with tasks and roles intended for dynamic inclusions, all needed tasks should be explicitly tagged at the task level; or block: may be used to tag more than one task at once. The include itself should also be tagged.

Does this mean that the tag(s) for the outer `include_` statement need to be specified along with any tags specific to the *included* task(s)? Light testing (deoren/ansible-examples@b25baed052f8544c90706beadaaa22de01194138) seems to indicate this is so:

```shell
$ ansible-playbook mass-updates.yml -e "update_core_servers=true" --list-hosts --list-tasks --tags "report, testing, core"

playbook: mass-updates.yml

  play #1 (all): Login to all hosts (in inventory) in order to collect Ansible Facts	TAGS: []
    pattern: [u'all']
    hosts (5):
      db1
      db2
      localbox
      important1
      nag1
    tasks:

  play #2 (dbs): Update shared database servers	TAGS: []
    pattern: [u'dbs']
    hosts (2):
      db1
      db2
    tasks:
      mass-updates : Check for patches, send in report to ticketing system of available updates	TAGS: [testing]

  play #3 (testing:!monitoring:!dbs): Update test systems, exclude key systems	TAGS: []
    pattern: [u'testing:!monitoring:!dbs']
    hosts (1):
      localbox
    tasks:
      mass-updates : Check for patches, send in report to ticketing system of available updates	TAGS: [testing]

  play #4 (tier1:!monitoring:!dbs): Update core systems (skip groups already processed)	TAGS: []
    pattern: [u'tier1:!monitoring:!dbs']
    hosts (1):
      important1
    tasks:
      Apply mass-updates role	TAGS: [core]
```
