### ISSUE TITLE
loadkey command doesn't work with the module

### ISSUE THREAD

**Issue by qxmips** [ansible/ansible#34190]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
 
python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT
vyos 1.1.7

##### SUMMARY

```
 - name: add user
   connection: local
   vyos_config:
     lines:
# omited
#       - loadkeys {{ item.username }} ~/{{ item.username }}.pub
   with_items: '{{users}}'
```
returns an  exeption in 'try': "'line must start with either `set` or `delete`" .  how can i use loadkeys with ansible please? 

```yaml
---
# tasks file for vyos-add-user


 - name: copy key
   copy: 
     src={{ item.username }}.pub
     dest=~/{{ item.username }}.pub
     mode=0760
   with_items: '{{users}}'
   
 - name: add user
   connection: local
   vyos_config:
     lines:
       - set system login user {{ item.username }} full-name {{ item.desription | default('"created with ansible"') }}
       - set system login user {{ item.username }} level {{ item.level | default('admin')}}
#       - loadkeys {{ item.username }} ~/{{ item.username }}.pub
   with_items: '{{users}}'
```

##### ACTUAL RESULTS

```

```
