### ISSUE TITLE
would be nice if -v showed conditional expressions

### ISSUE THREAD

**Issue by wgj** [ansible/ansible#3422]
ansible 1.2 (epel repo)

It would be nice if `ansible-playbook --verbose` showed the evaluated expressions used in the playbook.

For instance, my playbook uses (the commented out lines are failed guesses):

``` yaml
  - file: src=files/iptables.XenServer5 dest=/etc/sysconfig/iptables owner=root group=root mode=0600
    #when: ansible_distribution_version|int >= 5 and ansible_distribution_version|int < 6
    #when: ansible_distribution_version|float >= 5.0 and ansible_distribution_version|float < 6.0
    #when: ansible_distribution_version > 5 and ansible_distribution_version < 6   
    #when: ansible_distribution_version|int == 5
    when: ansible_distribution_version > '5' and ansible_distribution_version < '6' # Winner!
```

The action was skipped, I'm stumped as to why, and --verbose (and -vvv for that matter) didn't share any more details then without.
