### ISSUE TITLE
Unable to connect the server post reboot and wait playbook

### ISSUE THREAD

**Issue by kailashrtm** [ansible/ansible#34231]
I am getting error while executing the playbook for reboot and wait for 30 seconds,

Server is getting reboot but at the same time I am loosing my ansible connection as well.

Below is my yml file and error output

```yaml
---
- name: Reboot a host and wait for it to return
  hosts: all
  remote_user: root
  tasks:
    # Send the reboot command
    - shell: shutdown -r now

    # This pause is mandatory, otherwise the existing control connection gets reused!
    - pause: seconds=30

    # Now we will run a local 'ansible -m ping' on this host until it returns.
    # This works with the existing ansible hosts inventory and so any custom ansible_ssh_hosts definitions are being used
    - local_action: shell ansible -m ping ccmeloimldrapp2
      register: result
      until: result.rc == 0
      retries: 30
      delay: 10

    # And finally, execute 'uptime' when the host is back.
    - shell: uptime
```

Error output
```
----------------

PLAY [Reboot a host and wait for it to return] *********************************

TASK [Gathering Facts] *********************************************************
fatal: [ccmeloimldrapp2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host ccmeloimldrapp2 port 22: Connection timed out\r\n", "unreachable": true}
        to retry, use: --limit @/var/ansible/roles/reboot/tasks/main.retry

PLAY RECAP *********************************************************************
ccmeloimldrapp2            : ok=0    changed=0    unreachable=1    failed=0

```

**Comment by ansibot** [comment]
@kailashrtm Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
Hi @kailashrtm !

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by Akasurde** [comment]
You can try 

```yaml
- name: restart machine
  shell: 'sleep 2 && shutdown -r now "Ansible updates triggered"'
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for
    host="{{ inventory_hostname }}"
    port=22
    delay=10
    timeout=120
```
