### ISSUE TITLE
URI module to check the status 

### ISSUE THREAD

**Issue by jai1824** [ansible/ansible#34245]
I am trying to check the status of a page ad seeing error. Below are the details

```
[user]$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```
#### component name:
URI

#### Description 

```yaml
Playbook:
- hosts: localhost
  tasks:
       - uri: 
       url: "https://www.exapmple.com"
       register: result
       - debug: msg="{{ result.status }}"
```

Error:

```
failed: [localhost] (item=<meta property="og:description" content="Click here to check out Kroger Digital coupons - you'll find storewide savings on some of your favorite brands." />) => {"content": "", "failed": true, "item": "<meta property=\"og:description\" content=\"Click here to check out  - you'll find storewide savings on some of your favorite brands.\" />", "msg": "Status code was not [200]: An unknown error occurred: 'NoneType' object has no attribute 'find'", "redirected": false, "status": -1, "url": null}

Seeing multiple errors of same type ""msg": "Status code was not [200]: An unknown error occurred: 'NoneType' object has no attribute 'find'", "redirected": false, "status": -1, "url": null}"
```
Please suggest
