### ISSUE TITLE
Module authorized_key.py may lead IO contention when using “delegate_to”

### ISSUE THREAD

**Issue by Songzr** [ansible/ansible#34254]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

authorized_key
##### ANSIBLE VERSION

```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

```
[default]
host_key_checking = False
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Module authorized_key.py may lead IO contention when using “delegate_to”

##### STEPS TO REPRODUCE

- execute the command below
```shell
ansible-playbook ssh_keys.yml -k
```
- playbooks/ssh_keys.yml
```yaml
---
- hosts: test_group
  tasks:
  - name: Sync /etc/hosts
    copy:
        src: /etc/hosts
        dest: /etc/hosts


- hosts: test_group
  roles:
        - ssh_key

```
- role/ssh_keys/tasks/main.yml
```yaml
---
# author: lework

- name: Generate SSH keys.
  shell: ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
  args:
    creates: ~/.ssh/id_rsa

- name: fetch all public ssh keys.
  shell: cat ~/.ssh/id_rsa.pub
  register: ssh_keys
  when: ((ssh_keys_host is defined and ansible_default_ipv4.address == ssh_keys_host) or (ssh_keys_host is undefined))

- name: Ensure run host  is in the known_hosts file.
  shell: "ssh-keyscan -t rsa {{ ansible_hostname }},{{ansible_default_ipv4.address}} >> ~/.ssh/known_hosts" 
  delegate_to: "{{ item }}"
  with_items:
   - "{{ play_hosts | symmetric_difference([ansible_default_ipv4.address]) }}"

- name: Deploy keys on all servers.
  authorized_key: 
    user: "root" 
    key: "{{ ssh_keys.stdout }}" 
    state: present
  delegate_to: "{{ item }}"
  with_items:
   - "{{ play_hosts | symmetric_difference([ansible_default_ipv4.address]) }}"
  when: ssh_keys_host is undefined

- name: Deploy keys on all servers.
  authorized_key: 
    user: "root" 
    key: "{{ ssh_keys.stdout }}" 
    state: present
  delegate_to: "{{ item }}"
  with_items:
   - "{{ play_hosts | symmetric_difference([ansible_default_ipv4.address]) }}"
  when: ssh_keys_host is defined and ansible_default_ipv4.address == ssh_keys_host
  
  
```

https://github.com/kuailemy123/Ansible-roles/tree/master/ssh-keys
##### EXPECTED RESULTS

Write all public keys of the nodes  into authorized_keys file each other.
```shell
[root@dsj01 log]# more ~/.ssh/authorized_keys 
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA2oPC2u2Ksu/6t/jXSqX/8yg5zHGblrVDs5crEjJd6Noec7gnWqXo6LfqFEVcuZVNiUYaVKoVmUX1yITUI6Kwwj2oLYmMoCAbxQjtNPw4Q3jfeqnqpHixxA0/0MBgaYu1qq00mKsY4xGTBNaT//p5PflFfmBHpQbMATKTl5Onj7SGhDp3i3j4lqtHuOSAV2eZLBzw5U4q+YakEXcW8lGUiIq0d1omg/BQZ8f9SQ9ae0
CifwKZLLJmAHszEjw9aZDXRyw5OZIYSPspS+3ezSCyKazPe43cddpGwEc2wFleQ26SJ8V/XDV+cRaN/aZ5D7zF/hqoR/XxgytUDkpVR3CaOw== root@dsj01
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAtLVvmwwatj1sz9sCHxBSX/HbMfvCWhMaBRLRI6jsMmI4zeU+4jpyFXEjsGBn3AIL5RBynXWoO59sqJg0MmZJzfZN8h2BY75nBbedMiJXbaqwy6VKkSBkK8CUVIRd17K4su4Zma8pRU4HEi4URVFb6z3c5qBqDnWYXByQ+k4HiwHnhamEuKXc9Rbx78TjalUBumkqeSXoyZBxbhMAgF5s51h+7TBClE7B/yDtP/qxYn
FTne2jnNMy+DL2GOhQgquNZem79IIR0y6ekFlCFYjrcvR379hBxiUB8usOapUkAlWngc1df9fnEuSpk7zLnz4KC2LCro0batjT1qlgcWLCqQ== root@dsj02
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEArlcIHW6csof1gU2txnJ+QyWm5LtSFkxdsq9RrA7l+r/ZdS5IC8I9//oBloJU+QqpFjLQEGJaIh4dFLJ0uK04LRVXikigDfo0eT3m00+hMiBNIPavFERu9iRQUSGMcgJvXRZTScm3kP8MtkKptt5CEImcHyQDU9cu9x9Ol0A97QnPncAPo8sbxCWj0oTXzsstOHD8fz/l9sOepEKRAy4RToEww6GrilX2l/zXpO+Yp+
5mAQl4CuzgmHJeRBgIrUmY2OXyWM7ElaTRHY4hlZfhZfMQB3cLaIw8yhPkahRSZDR3kthsnkiCN6iQvk3SX3gnVRiIwrszQcPBI23Vc5xJdQ== root@dsj03
```
##### ACTUAL RESULTS

Some of the public keys may lose.

```shell
[root@dsj01 log]# more ~/.ssh/authorized_keys 
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6f33JImSblIX+h7tGVpMV3nYfHe3wU2rl1sfcZA7jcasdpVgHKFLoaCGn82gXTtu+ILHGR/gm9R5y7Ua2EQ2+OgliXPBrHvgP1MZwczi+3zYg9/9g5XX77voDmt+pSNz9sxK4+osv7k5FvwgvPLGNDNz6F2kMBX3+EPCSij2156GVp9lIFyKWaJwfq5w0PCSWUOWFPYIBdr5/npUrqoQSLWDGGtmLyR06WuQb7nNqp
O9tfuOXBEpBgL8XiPd1Z5gNotaOtm4p3f4ecnQmVbekIloZ0UdKNHk9gry7qobkfOezRAeaT+l17vOaEmwb5RU7+0MnC50vvJa2tJvqdie8w== root@dsj01

```

##### Suggested solution
- Solution 1
Tried to avoid parallel write on the file *authorized_keys* by using magic_variables in the role:
```yaml
- name: "Deploy {{ ssh_keys_host }} key on all servers."
  authorized_key: 
    user: "root" 
    key: "{{ hostvars[item]['ssh_keys']['stdout'] }}" 
    state: present
  with_items:
    - "{{ play_hosts }}"
  when: ssh_keys_host is undefined

```
- Solution 2
Using parameter *-f 1* to avoid parallel write.
```shell
ansible-playbook ssh_keys.yml -k -f 1
```

- Solution 3
Change the open() mode from 'w' to 'a+' in the module file authorized_keys.py

...line 351
```python
if not os.path.exists(keysfile):
        basedir = os.path.dirname(keysfile)
        if not os.path.exists(basedir):
            os.makedirs(basedir)
        try:
            f = open(keysfile, "w") #touches file so we can set ownership and perms
        finally:
            f.close()
        if module.selinux_enabled():
            module.set_default_selinux_context(keysfile, False)
```
