### ISSUE TITLE
authorized_key concurrent write questions

### ISSUE THREAD

**Issue by lework** [ansible/ansible#34257]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
authorized_key module

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
[test]
192.168.77.128
192.168.77.129
192.168.77.130

[all:vars]
ansible_ssh_pass=123456

##### OS / ENVIRONMENT
OS: centos 7.2 X64

#####  PLAYBOOK
```
---
 - hosts: test
   tasks:
     - name: Deploy keys on all servers.
      authorized_key:
        user: "root"
        key: "{{ item }}"
        state: present
      delegate_to: "{{ item }}"
      with_items:
       - "{{ play_hosts  }}"
```
##### SUMMARY
`~/.ssh/authorized_keys` sometimes have a item, or two item. Guessing due to concurrency causes writing to be overwritten so the data in the `~/.ssh/authorized_keys` file is reduced. Limit the fork to 1, there is no such problem.

##### My solution
`/usr/lib/python2.7/site-packages/ansible/modules/system/authorized_key.py`
```
347     f = open(keysfile, "w")  # touches file so we can set ownership and perms
474     f = open(tmp_path, "w")

Change into

347     f = open(keysfile, "a+")  # touches file so we can set ownership and perms
474     f = open(tmp_path, ["a+")](url)
```
Run playbook again, no problem.
