### ISSUE TITLE
Invalid params. Incorrect argument passed to function while sending

### ISSUE THREAD

**Issue by mantri-govind** [ansible/ansible#34288]
##### ISSUE TYPE
  - Bug Report

##### COMPONENT NAME

Zabbix Host Addition
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python2.7/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

No change 
##### OS / ENVIRONMENT

Ubuntu 16.04 LTS
##### SUMMARY

Trying to register hosts from ansible , I'm using few variables from ansible host file like host name, visible name etc. When I run the playbook it gives following error 
```
fatal: [10.10.140.9 -> localhost]: FAILED! => {"changed": false, "msg": "Failed to create host MY-PD-CT10: (u'Error -32602: Invalid params., Incorrect arguments passed to function. while sending {\"params\": {\"status\": 0, \"host\": \"MY-PD-CT10\", \"interfaces\": [{\"ip\": \"10.10.140.6\", \"main\": 1, \"type\": 1, \"useip\": 0}], \"groups\": [{\"groupid\": \"8\"}], \"name\": \"MY-PD-CT10\"}, \"jsonrpc\": \"2.0\", \"method\": \"host.create\", \"auth\": \"841578d0a278e720c0aa11820f8ee2b8\", \"id\": 4}', -32602)"}
fatal: [10.10.140.6 -> localhost]: FAILED! => {"changed": false, "msg": "Failed to create host MY-PD-CT07: (u'Error -32602: Invalid params., Incorrect arguments passed to function. while sending {\"params\": {\"status\": 0, \"host\": \"MY-PD-CT07\", \"interfaces\": [{\"ip\": \"10.10.140.6\", \"main\": 1, \"type\": 1, \"useip\": 0}], \"groups\": [{\"groupid\": \"8\"}], \"name\": \"MY-PD-CT07\"}, \"jsonrpc\": \"2.0\", \"method\": \"host.create\", \"auth\": \"dd9000292d17d06f3de872d58a2b4952\", \"id\": 4}', -32602)"}
```
##### STEPS TO REPRODUCE

```yaml

---
- hosts: containers
  remote_user: daedalus
  vars:
    ipAdd: "{{inventory_hostname}}"
  tasks:
   - name: Create a new host or update an existing host's info
     local_action:
        module: zabbix_host
        server_url: http://10.10.140.18/zabbix
        login_user: Admin
        login_password: zabbix
        host_name: "{{ctHostname}}"
        visible_name: "{{ctHostname}}"
        host_groups:
         - Home-vLAN
        interfaces:
         - type: 1
           main: 1
           useip: 0
           ip: '10.10.140.6'
        proxy: ""


```

##### EXPECTED RESULTS

It should have added the host in zabbix
