### ISSUE TITLE
maven_artifact fails to download from local Maven repository

### ISSUE THREAD

**Issue by tvendelin** [ansible/ansible#34309]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /Users/tom/projects/ansible/sandbox/playbooks/ansible.cfg
  configured module search path = [u'/Users/tom/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 05:35:35) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
maven_artifact fails to download from local Maven repository, looking for maven-metadata.xml only and ignoring maven-metadata-local.xml

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  tasks:
  - name: 'Get WAR file from local repository'
    maven_artifact:
      group_id: 'com.tere'
      artifact_id: 'springDummy'
      version: latest
      keep_name: no
      repository_url: 'file:///Users/tom/.m2/repository'
      dest: '/tmp/'
    register: _maven

  - debug: var=_maven
```
##### EXPECTED RESULTS
WAR artifact being downloaded from local repo.

##### ACTUAL RESULTS

```
$ ansible-playbook maven_bug_report.yml 

PLAY [localhost] ***********************************************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************************************
ok: [localhost]

TASK [Get WAR file from local repository] **********************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

Failed to download maven-metadata.xml because of Request failed: <urlopen error [Errno 2] No such file or directory: '/Users/tom/.m2/repository/com/tere/springDummy/maven-metadata.xml'>for URL file:///Users/tom/.m2/repository/com/tere/springDummy/maven-metadata.xml

	to retry, use: --limit @/Users/tom/projects/ansible/sandbox/playbooks/maven_bug_report.retry

PLAY RECAP *****************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  

$ls /Users/tom/.m2/repository/com/tere/springDummy/
1.0-SNAPSHOT			maven-metadata-local.xml

```
Moving maven-metadata-local.xml to maven-metadata.xml and then running the same playbook results in rather hilarious message:
```
TASK [Get WAR file from local repository] **********************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

Failed to download maven-metadata.xml because of OK (277 bytes)for URL file:///Users/tom/.m2/repository/com/tere/springDummy/maven-metadata.xml
```
