### ISSUE TITLE
XML module: set_children: [] should remove children but doesnt

### ISSUE THREAD

**Issue by ham-360** [ansible/ansible#34313]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
XML module

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /usr/local/ansible/projects/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/etc/ansible/hosts']
DEFAULT_ROLES_PATH(/usr/local/ansible/projects/ansible.cfg) = [u'/usr/local/ansible/projects/.imported_roles', u'/usr/local/ansible/projects/roles']
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

Cannot use set_children to remove children from an xml node.

##### STEPS TO REPRODUCE

```yaml
- name: Remove all children from the test element
  xml:
    xmlstring: "<test><child/></test>"
    xpath: /test
    set_children: []
```

##### EXPECTED RESULTS

The child node is removed
```
"xmlstring": "<?xml version='1.0' encoding='UTF-8'?>\n<test></test>"
```

##### ACTUAL RESULTS

The child nodes are not removed

```
ok: [ansible-target] => {
    "actions": {
        "namespaces": {},
        "state": "present",
        "xpath": "/test"
    },
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "add_children": null,
            "attribute": null,
            "backup": false,
            "content": null,
            "count": false,
            "input_type": "yaml",
            "namespaces": {},
            "path": null,
            "pretty_print": false,
            "print_match": false,
            "set_children": [],
            "state": "present",
            "value": null,
            "xmlstring": "<test><child/></test>",
            "xpath": "/test"
        }
    },
    "xmlstring": "<?xml version='1.0' encoding='UTF-8'?>\n<test><child/></test>"
}
```

##### NOTE:
The ansible documentation for the XML module (https://docs.ansible.com/ansible/2.4/xml_module.html) includes the following example:

```
- name: Remove all children from the website element (option 2)
  xml:
    path: /foo/bar.xml
    xpath: /business/website
    children: []
```
But use of 'children' over 'set_children' gives the error:
```
fatal: [ansible-target]: FAILED! => {
    ...
    "msg": "Unsupported parameters for (xml) module: children Supported parameters include: add_children,attribute,backup,content,count,input_type,namespaces,path,pretty_print,print_match,set_children,state,value,xmlstring,xpath"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/xml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/xml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by apisyurga** [comment]
Hi,

For those ending up here with the same issue, Option 1 from the example in https://docs.ansible.com/ansible/2.4/xml_module.html is valid and works:
```yaml
- name: Remove all children from the website element (option 1)
  xml:
    path: /foo/bar.xml
    xpath: /business/website/*
    state: absent
```
