### ISSUE TITLE
XML module feature request: proceed with 0 results/changes

### ISSUE THREAD

**Issue by ham-360** [ansible/ansible#34314]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

XML Module

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /usr/local/ansible/projects/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/etc/ansible/hosts']
DEFAULT_ROLES_PATH(/usr/local/ansible/projects/ansible.cfg) = [u'/usr/local/ansible/projects/.imported_roles', u'/usr/local/ansible/projects/roles']
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
RETRY_FILES_ENABLED(env: ANSIBLE_RETRY_FILES_ENABLED) = False

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY
When developing idempotent ansible scripts, I want to be able to specify "find me anything matching xpath" or "update anything matching xpath" and i don't care whether the xpath given matches 1 or more nodes or not.

Currently commands other than 'count' within the xml module will produce a failure if the xpath matches 0 nodes and it is up to the user work around this.

I propose a new flag e.g. 'ignore_zero_results' with a default value of false, but when set to true, means that the following commands will not fail when the xpath given fails to resolve to anything in the file or xml string given:
 - add_children
 - set_children
 - value
 - content
 - state
 - print_match
 - ...etc

##### STEPS TO REPRODUCE

```yaml
- name: Get all values in bar elements in a foo parent
  xml:
    xmlstring: "<foo></foo>"
    xpath: /foo/bar
    content: text
    (ignore_zero_results: yes)
```

##### EXPECTED RESULTS

A success with 0 results
```
=> {
    "actions": {
        "namespaces": {}, 
        "state": "present", 
        "xpath": "/foo/bar"
    }, 
    "changed": false, 
    "count": 1, 
    "failed": false, 
    "invocation": {
        "module_args": {
            "add_children": null, 
            "attribute": null, 
            "backup": false, 
            "content": "text", 
            "count": false, 
            "input_type": "yaml", 
            "namespaces": {}, 
            "path": null, 
            "pretty_print": false, 
            "print_match": false, 
            "set_children": null, 
            "state": "present", 
            "value": null, 
            "xmlstring": "<foo></foo>", 
            "xpath": "/foo/bar"
        }
    }, 
    "matches": [], 
    "msg": 0
}
```

##### ACTUAL RESULTS

```
fatal: [ansible-target]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "add_children": null,
            "attribute": null,
            "backup": false,
            "content": "text",
            "count": false,
            "input_type": "yaml",
            "namespaces": {},
            "path": null,
            "pretty_print": false,
            "print_match": false,
            "set_children": null,
            "state": "present",
            "value": null,
            "xmlstring": "<foo></foo>",
            "xpath": "/foo/bar"
        }
    },
    "msg": "Xpath /foo/bar does not reference a node!"
```

##### CURRENT WORKAROUND
I am currently getting around this deficiency by manually narrowing the definition of failed to exclude error conditions that 

```yaml
- name: Get all values in bar elements in a foo parent
  xml:
    xmlstring: "<foo></foo>"
    xpath: /foo/bar
    content: text
  register: result
  failed_when:
    - result.failed is defined and result.failed
    - not (result.msg | search(" does not reference a node!$"))
    - not (result.msg | search(" in order to spawn nodes! tree is "))
```
