### ISSUE TITLE
uri module, header options not working

### ISSUE THREAD

**Issue by benjdudas** [ansible/ansible#34321]
ISSUE TYPE:

 - Bug Report

COMPONENT NAME:

- uri module

ANSIBLE VERSION:

```
$ ansible --version
ansible 2.4.2.0

$ ansible --version
ansible 2.5.0

```

CONFIGURATION:

```
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/alf/Desktop/token/ansible.cfg) = [u'/home/alf/Desktop/token/hosts'

```

OS / ENVIRONMENT:
`Ubuntu 16.04`

SUMMARY:
uri module is not handling header options when authenticating with a token. Testing the headers using Curl is successful.  

STEPS TO REPRODUCE:

Playbook:
```
 - name: api auth with token 
      uri:
        method: PATCH
        headers:
           Authorization: "Token xxxxxxxx"
           Content-Type: "application/json"
        url: https://tower/api/v2/projects/422/
        validate_certs: no

```
Verify the header/token using curl:

```
curl -H "Authorization: Token xxxxxxxxx" https://tower/api/v2/projects/422/ -k -X PATCH | json_pp

```

EXPECTED RESULTS:

Authenticate with API Token
 
ACTUAL RESULTS:

401 Response 

```
"headers": {
                "Authorization": "Token xxxxxxxxxx",
                "Content-Type": "application/json"
            }

<snip>

}, 
    "json": {
        "detail": "Authentication credentials were not provided."
    }, 
 "msg": "Status code was not [200]: HTTP Error 401: UNAUTHORIZED", 
    "redirected": false, 
    "server": "nginx/1.12.2", 
    "status": 401, 
    "transfer_encoding": "chunked", 
    "url": "https://tower/api/v2/projects/422/", 
    "vary": "Accept, Accept-Language, Cookie", 
    "www_authenticate": "Token", 
    "x_api_node": "localhost", 
    "x_api_time": "0.052s", 
    "x_api_total_time": "0.057s"
}


```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/uri.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/uri.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @romeotheriault
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pari-** [comment]
Hi,

thanks for your report, unfortunately, I am not capable of reproducing this:

```yaml
---

- hosts: "localhost"
  tasks:
    - uri:
        method: "PATCH"
        headers:
          Authorization: "Token xxxxxxxx"
          Content-Type: "application/json"
        url: "http://httpbin.org/patch"
      register: "_uri_result"

    - assert:
        that: "{{ item }}"
      with_items:
        - "_uri_result['json']['headers']['Authorization'] == 'Token xxxxxxxx'"
        - "_uri_result['json']['headers']['Content-Type'] == 'application/json'"
```

```
PLAY [localhost] ******************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************
ok: [localhost]

TASK [uri] ************************************************************************************************************************************
ok: [localhost]

TASK [assert] *********************************************************************************************************************************
ok: [localhost] => (item=_uri_result['json']['headers']['Authorization'] == 'Token xxxxxxxx') => {
    "attempts": 1,
    "changed": false,
    "item": "_uri_result['json']['headers']['Authorization'] == 'Token xxxxxxxx'",
    "msg": "All assertions passed"
}
ok: [localhost] => (item=_uri_result['json']['headers']['Content-Type'] == 'application/json') => {
    "attempts": 1,
    "changed": false,
    "item": "_uri_result['json']['headers']['Content-Type'] == 'application/json'",
    "msg": "All assertions passed"
}

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

.. While not being familiar with Tower, I just found something in the docs that *might* help you:

`The auth token is only valid when used from the same remote address and user agent that originally obtained it.` *[1]*

Therefor: if the Token was generated with curl, you'll either have to get one via Ansible or, alternatively, inject the same `User-Agent` as header, as when you retrieved the token with curl.

*[1]* - http://docs.ansible.com/ansible-tower/latest/html/towerapi/auth_token.html

**Comment by Rajendra-Jonnalagadda** [comment]
@ansibot @pari- 
I have run into the same issue. Please help me out 
```
  - name: "Creating Github repo "
    uri:
      url: https://api.github.com/orgs/:orgs/repos
      method: "POST"
      user: "<USER>"
      password: "<key>"
      body_format: json
      force_basic_auth: yes
      body: '{"name=repo-from-Api1"}'
```
Please let me know if I am missing something here.
