### ISSUE TITLE
bigip_config merge_content parameter does not make changes to the device

### ISSUE THREAD

**Issue by termlen0** [ansible/ansible#34355]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

f5/bigip_config/merge_content parameter

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/home/ajay/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ajay/venv2/local/lib/python2.7/site-packages/ansible
  executable location = /home/ajay/venv2/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

' '
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Using the merge_content parameter to change the ltm's configuration does not work. The task comes back as changed successfully, but the config does not take effect.
##### STEPS TO REPRODUCE

I've tried using 2 options to try and merge configuration. Both do not work. This same config snippet works fine from the device's command line.

**OPTION1**
```yaml
- name: CONFIGURE SNMP
      bigip_config:
        merge_content: |
          sys snmp {
          communities {
          comm-public {
          community-name public
          source default
          }
          }
          }
        server: "{{ inventory_hostname }}"
        user: "{{ un }}"
        password: "{{ pwd }}"
        validate_certs: no
        save: True
      tags: snmp
```

**OPTION 2**
```yaml
- name: CONFIGURE SNMP
      bigip_config:
        merge_content: "{{ lookup('file', './files/snmp.cfg') }}"
        server: "{{ inventory_hostname }}"
        user: "{{ un }}"
        password: "{{ pwd }}"
        validate_certs: no
        save: True
      tags: snmp
```

##### EXPECTED RESULTS

Expected the configuration to take effect

##### ACTUAL RESULTS

```
TASK [CONFIGURE SNMP] *************************************************************************************************************************************************************************************************************************************************
task path: /home/ajay/Projects/misc/f5-playbooks/pb1.yml:39
Using module_utils file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/module_utils/f5_utils.py
Using module_utils file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module file /home/ajay/venv2/local/lib/python2.7/site-packages/ansible/modules/network/f5/bigip_config.py
<10.1.100.204> ESTABLISH LOCAL CONNECTION FOR USER: ajay
<10.1.100.204> EXEC /bin/sh -c 'echo ~ && sleep 0'
<10.1.100.204> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ajay/.ansible/tmp/ansible-tmp-1514911584.33-169425673421411 `" && echo ansible-tmp-1514911584.33-169425673421411="` echo /home/ajay/.ansible/tmp/ansible-tmp-1514911584.33-169425673421411 `" ) && sleep 0'
<10.1.100.204> PUT /tmp/tmp.FgwduiCtgX/tmpH1KrNi TO /home/ajay/.ansible/tmp/ansible-tmp-1514911584.33-169425673421411/bigip_config.py
<10.1.100.204> EXEC /bin/sh -c 'chmod u+x /home/ajay/.ansible/tmp/ansible-tmp-1514911584.33-169425673421411/ /home/ajay/.ansible/tmp/ansible-tmp-1514911584.33-169425673421411/bigip_config.py && sleep 0'
<10.1.100.204> EXEC /bin/sh -c 'python /home/ajay/.ansible/tmp/ansible-tmp-1514911584.33-169425673421411/bigip_config.py; rm -rf "/home/ajay/.ansible/tmp/ansible-tmp-1514911584.33-169425673421411/" > /dev/null 2>&1 && sleep 0'
changed: [10.1.100.204] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "merge_content": "sys snmp {\ncommunities {\ncomm-public {\ncommunity-name public\nsource default\n}\n}\n}\n", 
            "partition": "Common", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "reset": false, 
            "save": true, 
            "server": "10.1.100.204", 
            "server_port": 443, 
            "state": "present", 
            "user": "admin", 
            "validate_certs": false, 
            "verify": true
        }
    }, 
    "stdout": [
        "Validating configuration...\n  /tmp/5pXVDX\n", 
        "Saving running configuration...\n  /config/bigip.conf\n  /config/bigip_base.conf\n  /config/bigip_user.conf\nSaving Ethernet mapping...done\n"
    ], 
    "stdout_lines": [
        [
            "Validating configuration...", 
            "  /tmp/5pXVDX", 
            ""
        ], 
        [
            "Saving running configuration...", 
            "  /config/bigip.conf", 
            "  /config/bigip_base.conf", 
            "  /config/bigip_user.conf", 
            "Saving Ethernet mapping...done", 
            ""
        ]
    ]
}
META: ran handlers
META: ran handlers

```
