### ISSUE TITLE
Consider starting up a file server for the life of file serving, http(s)://, raw module calls wget.

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#344]
This would be an option to the "copy" module, for high speed file transfer.

Maybe it is something we use for moving all content, I don't know.

Based on proposal to list, something to be explored.   Should not happen if it increases complexity too much.

**Comment by mpdehaan** [comment]
This could be usable for all module xfer as well, which would have very nice performance implications for sudo mode.

**Comment by jkleint** [comment]
I'm probably not testing what you intend, but I can't seem to find a difference between normal and sudo mode.  Do you have a playbook that illustrates a performance gap?  I tried this:

```
---
- hosts: 32_node_cluster
  tasks:
  - action: copy src=/etc/issue dest=/tmp/issue
    with_items: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
```

In nomal mode:

```
$ time ansible-playbook test-copy.yml -u$USER -f32
[ snip ]
real    0m45.174s
user    0m42.230s
sys     1m16.927s
```

And in sudo mode:

```
$ time ansible-playbook test-copy.yml -u$USER -f32 -K
sudo password:
[ snip ]
real    0m50.273s
user    0m43.802s
sys     1m17.667s
```

The difference is the time it takes to type my password.
