### ISSUE TITLE
stat.exists is not working

### ISSUE THREAD

**Issue by 3j0s** [ansible/ansible#34407]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible-playbook 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### CONFIGURATION

Default
##### SUMMARY

It seem that the module **stat** is not working, i tried to downgrade my ansible from 2.3.2.0 till 2.1.1.0 and i get the same error.

##### STEPS TO REPRODUCE

ansible-playbook -i inventory/ check_user_exist.yaml -e vars/users.yml  -vvvvvv 

```yaml
---
- hosts: web
  become: yes
  pre_tasks:
    - shell: echo "Revoking Access Support.."
  vars_files:
    - vars/users.yml
  tasks:

    - stat:
        path: "/home/{{ item.name }}/.ssh/authorized_keys"
      with_items: "{{ users }}"
      register: hm
      tags:
         - checking_file_exists

    - name: Deleting authorization key
      command: " rm -f /home/{{ item.name }}/.ssh/authorized_keys"
      when: hm.stat.exists == True
      with_items: "{{ users }}"
      tags:
         - deleting_auth_file
```

##### EXPECTED RESULTS

I expect that remove the file if exists
##### ACTUAL RESULTS

fatal: [192.168.100.22]: FAILED! => {
    "failed": true,
    "msg": "The conditional check 'hm.stat.exists == True' failed. The error was: error while evaluating conditional (hm.stat.exists == True): 'dict object' has no attribute 'stat'\n\nThe error appears to have been in '/opt/ansible/check_user_exist.yaml': line 17, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Deleting authorization key\n      ^ here\n"
}

```

```
