### ISSUE TITLE
new module for managing projects in Google Cloud

### ISSUE THREAD

**Issue by pschiffe** [ansible/ansible#34405]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
google

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/pschiffe/work/websignal/infra/ansible/ansible.cfg
  configured module search path = [u'/home/pschiffe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Nov  3 2017, 10:55:25) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
```

##### OS / ENVIRONMENT
Fedora release 27 (Twenty Seven)

##### SUMMARY
Create a new module to manage projects in the Google Cloud Platform with support to manage iam policy bindings. It should be possible to also add a new policy binding, not only to overwrite all. API:
https://cloud.google.com/resource-manager/reference/rest/v1/projects

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/google/__init__.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/__init__.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pschiffe** [comment]
Support for project metadata would by also more than welcome, mainly for managing SSH keys. Currently it looks horrible when done with Ansible:
```yaml
- name: get current ssh keys in the gcp project
  command: gcloud --project {{ gcloud_project }} compute project-info describe --format='value(commonInstanceMetadata.items.key.sshKeys.value)'
  register: project_ssh_keys
  changed_when: false

- block:
  - name: create variable with our public key for gcp metadata, when there are no other public keys
    set_fact:
      ssh_public_key_metadata: 'cloud-user:{{ public_ssh_key.content | b64decode | trim }}'
    when: "'ssh-rsa' not in project_ssh_keys.stdout"

  - name: create variable with our public key for gcp metadata, when there are other public keys
    set_fact:
      ssh_public_key_metadata: "{{ project_ssh_keys.stdout }}\ncloud-user:{{ public_ssh_key.content | b64decode | trim }}"
    when: "'ssh-rsa' in project_ssh_keys.stdout"

  - name: add our ssh key to the project
    command: gcloud --project {{ gcloud_project }} compute project-info add-metadata --metadata='sshKeys={{ ssh_public_key_metadata }}'
  when: public_ssh_key.content | b64decode | regex_replace('ssh-rsa (.*) cloud-user', '\\1') | trim not in project_ssh_keys.stdout
```
