### ISSUE TITLE
hosts vars should precede roles vars

### ISSUE THREAD

**Issue by kafeinnet** [ansible/ansible#3441]
Hi,

Roles vars (roles/x/vars/main.yml) are preceding hosts vars (host_vars/x). And, if I understand correctly, roles are meant to allow code sharing and reutilization.

So roles should define some default variables and hosts vars should be used to override those variables with specific ones. Actually, there is no way to change roles behavior through variables without modifying a playbook. No good for sharing.

Example:

``` yaml
# File roles/mailserver/tasks/main.yml
# *snip*
- name: Postfix ClamAV installation
  apt: pkg=$item state=latest
  with_items:
    - clamsmtp
    - clamav-freshclam
    - clamav-daemon
  only_if: "{{ mx_clamav_enabled }}"
  tags:
    - postfix
# *snip*
```

``` yaml
# File roles/mailserver/vars/main.yml

---
mx_clamav_enabled: True
```

``` yaml
# File host_vars/muscat

---
mx_clamav_enabled: False
```

``` yaml
# File mailserver.yml

---
- hosts: mailservers
  roles:
    - mailserver
```

At the execution, ClamAV is installed and I don't want to. I could use parametized roles but there is about 50 variables in my mailserver playbook. Using a YAML by host to define vars is must easier than defining them in a dict with a condition "when: ansible_hostname == 'muscat'".

I think hosts vars should precede roles vars.

Thx,

Fab.

**Comment by kafeinnet** [comment]
Answering to myself, there is a workaround : 

``` yaml
# File mailserver.yml
---
- hosts: mailservers
  vars_files:
    - host_vars/{{ inventory_hostname }}
  roles:
    - mailserver
```
