### ISSUE TITLE
ec2_eip support for 'name' parameter (and improved idempotency)

### ISSUE THREAD

**Issue by jxn** [ansible/ansible#34422]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ec2_eip module

##### SUMMARY
Now that eip's can be named (inside vpc), we should enable assigning a name when creating them.

Longer-term, this name could be used in a lookup to improve it idempotency story for aws configuration.

##### STEPS TO REPRODUCE

Create a new EIP with name:
```
- name: assign eip with a name
  ec2_eip:
    region: us-west-2
    in_vpc: yes
    state: present
    name: my_cool_eip
```

##### EXPECTED RESULTS
if in_vpc parameter is 'yes', create new EIP and assign name.  If in_vpc parameter is 'no', error "EIP's outside of vpc cannot have a name specified".  All other module behavior is the same.

Someday, we could add a lookup to be used with eip name:
```
- route53_record: record=my.dnsname.com value="{{ lookup('eip_by_name', region='us-west-2', name='my_cool_eip' ) }}"
