### ISSUE TITLE
ec2_group: boto profile gets overwritten by $AWS_DEFAULT_PROFILE

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#34421]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /Users/hryamzik/Documents/Work/Delux/repos/owf-ansible/infrastructure/ansible.cfg
  configured module search path = [u'/Users/hryamzik/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```
[defaults]
inventory = inventory
retry_files_save_path = retry
ansible_managed = Ansible managed: file modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
nocows = 1
callback_whitelist = timer
stdout_callback = skippy
display_skipped_hosts = False
force_handlers = True
# vault_password_file = vaultkeychain

[ssh_connection]
pipelining = False
# control_path = %(directory)s/%%h-%%p-%%r
control_path = %(directory)s/%%h-%%p
```

##### OS / ENVIRONMENT

Mac OS 10.13

##### SUMMARY

When both `AWS_DEFAULT_PROFILE` environment variable and `profile` option is specified for `ec2_group` environment one is used. It's different for `ec2` module and this behaviour is very counterintuitive.

##### STEPS TO REPRODUCE

Setup at least one profile in `~/.aws/`. Specify `AWS_DEFAULT_PROFILE` variable to another profile (may not exist): `export AWS_DEFAULT_PROFILE=bloody_hell`.

```yaml
        ec2_group:
            profile: my_working_profile
            name: ssh
            description: ssh
            rules:
              - proto: tcp
                from_port: 22
                to_port: 22
                cidr_ip: 0.0.0.0/0
```

##### EXPECTED RESULTS

Get group created under `my_working_profile`.

##### ACTUAL RESULTS

Group created under `bloody_hell` profile.
