### ISSUE TITLE
Allow shell args creates/removes to support lists

### ISSUE THREAD

**Issue by juan-vg** [ansible/ansible#34454]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

- Shell
- Maybe other similar modules like 'command'

##### ANSIBLE VERSION

```
ansible 2.4.2.0
    [...]
    python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Sometimes when running a **single shell command** the output is **more than one** file/directory. There should be a way to check if all of them are present via the 'creates' option. I mean, looping the entire task is not applicable here because it is a 'run once' command that requires to check if there is more than one file in order to perform -or not- the task (as the 'creates' option does for a single file/directory).

##### HOW THE FEATURE WOULD BE USED

Having 'vars/main.yml' as follows:
```yaml
domain_names:
  - "example.com"
  - "www.example.com"
```
One example could be:
```yaml
  - name: create certs
    shell: certbot certonly -n --agree-tos -d {{ domain_names | join(",") }}
    args:
      creates: /etc/letsencrypt/live/{{ item }}
      with_items: "{{ domain_names }}"
```
_Notice the 'with_items' indentation. It is 'creates' related._

Another example:
```yaml
  - name: create certs
    shell: certbot certonly -n --agree-tos -d {{ domain_names | join(",") }}
    args:
      creates: {{ domain_names | map('regex_replace', '^(.*)$', '/etc/letsencrypt/live/\\1') | list | join(" ") }}
```

##### EXPECTED RESULTS

The main idea is to iterate around the 'creates' option, not the entire task

##### ACTUAL RESULTS

The 'creates' option is intended for just a single file/directory

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/commands/command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/command.py)
* [lib/ansible/modules/commands/shell.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/shell.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
Some vaguely related issues:
- https://github.com/ansible/ansible/issues/19378 - file module should have a 'creates' parameter
- https://github.com/ansible/ansible/issues/15828 - Modules with creates= / removes= could support check mode

**Comment by sdiepend** [comment]
I would very much like this feature! But would the command or shell not run when one the listed files/directories exists or when all the listed files/directories exist? Or should you add a parameter to specify this?

**Comment by juan-vg** [comment]
@sdiepend From my point of view the only consistent state is in which all the listed files/directories are present. Any other situation should run the command.

**Comment by fgimian** [comment]
This is my workaround for now 😄 

```yaml
- name: Check whether the files exist
  stat:
    path: '{{ item }}'
  loop:
    - a
    - b
    - c
  register: files_stat
- name: Create the files
  shell: touch a b c
  when: files_stat.results | rejectattr('stat.exists') | list
```

Hope this helps someone 😄 
Fotis

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/command.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/command.py)
* [`lib/ansible/modules/shell.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/shell.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by elfringham** [comment]
Yes please. I would very much like to be able to simply check that all needed paths are created.

**Comment by keks24** [comment]
+1

It would be nice, if the following could be made possible:

```yml
- name: <some_task_name>
  shell: "touch /tmp/some_file1 && touch /tmp/some_file2"
  args:
    creates:
      - "<some_file1>"
      - "<some_file2>"
```

The yml list should be an `OR-link` as default. I currently have no clue how to indicate, that the list should be an `AND-link`.

**Comment by thunder-spb** [comment]
Any updates on this?

**Comment by g00nix** [comment]
This still looks like a good idea:
```yaml
    creates:
      - "/tmp/some_file1"
      - "/tmp/some_file2"
```

**Comment by rbq** [comment]
> Currently I have no clue how to indicate, that the list should be an `AND-link`.

I think the usual approach for YAML-based formats is using nesting objects for and/or conditions, e.g:

```yaml
- name: Create and enable vhost for the installed web-server
  include: vhost.yml # yes, I know ...
  args:
    creates:
    - - /etc/apache2/sites-available/mysite.conf
      - /etc/apache2/sites-enabled/mysite.conf
    - - /etc/nginx/sites-available/mysite.conf
      - /etc/nginx/sites-enabled/mysite.conf

```
