### ISSUE TITLE
scp and sftp support for large config transfer on os_config network modules

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#34460]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ios_config
nxos_config
iosxr_config
eos_config
junos_config
vyos_config

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
For devices that support the config replace option (`replace: config`) like this->

```yml
- name: replace whole device config
  eos_config:
    config: "{{ lookup('file', 'master.cfg') }}"
    replace: config
```
Sometimes the provided configuration are too large and devices will take a long time to accept them, error out, or need timeout value modification (or all of the above).  NAPALM has solved this at least some networking platforms by allowing scp to be used where it copies the configuration over as a file, then merges the local file. (source: http://napalm.readthedocs.io/en/latest/support/nxos.html)

It could be helpful in certain situations to allow the user to use scp or sftp to copy the configuration file over with the os_config module itself rather than having to use multiple os_command tasks.  For example (this is done as demonstration purposes only, and is not a requirement for the implementation at all, by merely provided as an example for a way to implement):

```yml
- name: replace whole device config
  eos_config:
    config: "{{ lookup('file', 'master.cfg') }}"
    replace: config
    replace_mode: scp
```

```yml
- name: replace whole device config
  eos_config:
    config: "{{ lookup('file', 'master.cfg') }}"
    replace: config
    replace_mode: sftp
```

Instead of using nxapi or cli method to push the config, the replace_mode would temporarily allow the config to be copied over via specified method (scp, sftp, etc) and then merged locally with nxapi or cli.  Again the goal is to *support scp and sftp for configuration replacement* the implementation provided here is just to help demonstrate what that *could* potentially look like and this may not make sense or be appropriate. 

From hslabbert on ntc slack:
>Does it still push up the flat candidate config file via nxapi or the cli transport? I believe the napalm way is to scp the file to the target device's file system then do the load that way. We'd had some issues with pushing large sets of config via nxapi and the cli transports for nxos_config before and needing to bump timeouts up a lot to compensate, with mixed success.

Talking about how we use the transport, he responded with specific issues hit

>Yea, we hit this previously: https://quickview.cloudapps.cisco.com/quickview/bug/CSCvc74591
As well as other cases where the task would return and show completed, but it simply didn't apply all the config.
VPC'd N9236C VTEPs, just lots of things for nxos_config to apply (couple hundred VLANs or so, VNI things, EVPN config for them, etc.). Lots of fun.

This issue is not unique to hslabbert as our own consultants are having to tweak timeouts for larger config sets.  This could provide a valuable alternative when the user demands pushing the config in one large chunk rather than breaking it up.

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
