### ISSUE TITLE
Windows become on action plugin copy/template does not use correct temp path

### ISSUE THREAD

**Issue by lucastheisen** [ansible/ansible#34470]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_template

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg
  configured module search path = [u'/home/ltheisen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s
ANSIBLE_SSH_CONTROL_PATH(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = %(directory)s/%%h-%%r
CACHE_PLUGIN(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = $HOME/ansible/asiasetl/facts
CACHE_PLUGIN_TIMEOUT(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = 600
DEFAULT_CALLBACK_WHITELIST(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = 20
DEFAULT_GATHERING(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = [u'/home/ltheisen/git/asiasetl-asias-etl-ansible/inventory/production/hosts']
DEFAULT_REMOTE_USER(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = root
HOST_KEY_CHECKING(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg) = /home/ltheisen/ansible-installer-retries
```
##### OS / ENVIRONMENT

running from: `CentOS Linux release 7.4.1708 (Core)`
managing: `Windows Server 2016 Standard`

##### SUMMARY

I have a single administrative user `ansible` which does all of the privileged actions, and generate application users for each application.  The application(s) themselves have configuration files that are stored as templates in my ansible project, but need to be owned by the application user.  So i need to use `win_template` to inject the settings (secrets and such), but when i try using `become` it fails with an _Access is denied_ error.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: etl
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  vars:
    automation_username: "autotest"
    automation_password: "notsafe4YOU!"

  tasks:
  - name: Create automation user
    win_user:
      name: "{{ automation_username }}"
      password: "{{ automation_password }}"
      groups:
        - Users
      password_never_expires: yes
      state: present

  - name: Copy credentials
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    win_template:
      src: ./credentials.j2
      dest: "C:/Users/{{ automation_username }}/credentials"
```

With a template file (`./credentials.j2`):
```
{
    "username": "{{ automation_username }}",
    "password": "{{ automation_password }}"
}
```

##### EXPECTED RESULTS

The file `C:\Users\autotest\credentials` is created on the managed system with the proper templated values, owned by the `autotest` user.

##### ACTUAL RESULTS

```
ansible-playbook 2.4.2.0
  config file = /home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg
  configured module search path = [u'/home/ltheisen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /home/ltheisen/git/asiasetl-asias-etl-ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/ltheisen/git/asiasetl-asias-etl-ansible/inventory/production/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc
Loading callback plugin profile_tasks of type aggregate, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: win-template.yml **************************************************************************************************************************************************************************************
1 plays in win-template.yml

PLAY [etl] ******************************************************************************************************************************************************************************************************
META: ran handlers
Trying secret FileVaultSecret(filename='/home/ltheisen/.developer/asiasetl-automation-ansible-vault.pass') for vault_id=default
Trying secret FileVaultSecret(filename='/home/ltheisen/.developer/asiasetl-automation-ansible-vault.pass') for vault_id=default

TASK [Create automation user] ***********************************************************************************************************************************************************************************
task path: /home/ltheisen/git/asiasetl-asias-etl-ansible/win-template.yml:12
Thursday 04 January 2018  13:40:55 -0500 (0:00:00.161)       0:00:00.161 ******
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_user.ps1
<asias-etl-auto.mitre.org> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO asias-etl-auto.mitre.org
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
EXEC (via pipeline wrapper)
ok: [asias-etl-auto.mitre.org] => {
    "account_disabled": false,
    "account_locked": false,
    "changed": false,
    "description": "",
    "fullname": "autotest",
    "groups": [
        {
            "name": "Users",
            "path": "WinNT://MITRE/ASIAS-ETL-AUTO/Users"
        }
    ],
    "name": "autotest",
    "password_expired": false,
    "password_never_expires": true,
    "path": "WinNT://MITRE/ASIAS-ETL-AUTO/autotest",
    "sid": "S-1-5-21-435669658-2316640754-613951654-1004",
    "state": "present",
    "user_cannot_change_password": false
}

TASK [Copy credentials] *****************************************************************************************************************************************************************************************
task path: /home/ltheisen/git/asiasetl-asias-etl-ansible/win-template.yml:21
Thursday 04 January 2018  13:40:59 -0500 (0:00:03.797)       0:00:03.958 ******
<asias-etl-auto.mitre.org> ESTABLISH WINRM CONNECTION FOR USER: ansible on PORT 5986 TO asias-etl-auto.mitre.org
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_stat.ps1
 [WARNING]: The Windows 'runas' become method is experimental, and may change significantly in future Ansible releases.

EXEC (via pipeline wrapper)
 [WARNING]: Module invocation had junk after the JSON data: True True

<asias-etl-auto.mitre.org> PUT "/tmp/tmpxOxepb/credentials.j2" TO "C:\Users\ansible\AppData\Local\Temp\ansible-tmp-1515091259.52-82343558372292\source"
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_copy.ps1
EXEC (via pipeline wrapper)
EXEC (via pipeline wrapper)
fatal: [asias-etl-auto.mitre.org]: FAILED! => {
    "changed": false,
    "checksum": "b7c5dd1c24163d22b4bfea8793df638f60334a7d",
    "diff": [],
    "module_stderr": "An error occurred while creating the pipeline.\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : RuntimeException\r\n \r\nException calling \"Run\" with \"1\" argument(s): \"Exception calling \"Invoke\" with \"0\" argument(s): \r\n\"The running command stopped because the preference variable \"ErrorActionPreference\" or common \r\nparameter is set to Stop: Access is denied\"\"\r\nAt C:\\Users\\ansible\\AppData\\Local\\Temp\\txxn4xvl.1rv.ps1:51 char:1\r\n+ $output = $entrypoint.Run($payload)\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : ScriptMethodRuntimeException\r\n",
    "module_stdout": "\r\nTrue\r\nTrue\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}

PLAY RECAP ******************************************************************************************************************************************************************************************************
asias-etl-auto.mitre.org   : ok=1    changed=0    unreachable=0    failed=1

Thursday 04 January 2018  13:41:06 -0500 (0:00:07.199)       0:00:11.158 ******
===============================================================================
Copy credentials ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 7.20s
/home/ltheisen/git/asiasetl-asias-etl-ansible/win-template.yml:21 ----------------------------------------------------------------------------------------------------------------------------------------------
Create automation user ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 3.80s
/home/ltheisen/git/asiasetl-asias-etl-ansible/win-template.yml:12 ----------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_template.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_template.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
@lucastheisen does the directory "C:/Users/{{ automation_username }}" exist at the time you are running the win_template command?  If not I think that might explain why you are getting access denied.
I suggest setting
export ANSIBLE_KEEP_REMOTE_FILES=1
and re-running your playbook, then looking to see what is at ine 51 (or wherever the .ps1 script that is being run fails - something like C:\\Users\\ansible\\AppData\\Local\\Temp\\txxn4xvl.1rv.ps1 

needs_info

**Comment by lucastheisen** [comment]
@jhawkesworth , 

> does the directory "C:/Users/{{ automation_username }}" exist at the time you are running the win_template command?

Yes, though in my example it actually gets created at the beginning of the become, so to separate it out and show that it exists prior, this is a better example yaml:
```
---
- hosts: etl
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  vars:
    automation_username: "autotest"
    automation_password: "notsafe4YOU!"

  tasks:
  - name: Create automation user
    win_user:
      name: "{{ automation_username }}"
      password: "{{ automation_password }}"
      groups:
        - Users
      password_never_expires: yes
      state: present

  - name: Check home dir
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    win_stat:
      path: "C:/Users/{{ automation_username }}"
    register: check_home_dir

  - name: Copy credentials
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    win_template:
      src: ./credentials.j2
      dest: "C:/Users/{{ automation_username }}/credentials"
```
Notice that the `win_stat` command will `become` the user in question thus causing the directory to be created (and return a stat on the folder showing it exists).

>I suggest setting `export ANSIBLE_KEEP_REMOTE_FILES=1` and re-running your playbook, then looking to see what is at ine 51

I tried that...  not particularly helpful because the saved `win_copy.ps1` is:
```
  1
  2 #Requires -Version 3.0
  3 begin {
  4     $DebugPreference = "Continue"
  5     $ErrorActionPreference = "Stop"
  6     Set-StrictMode -Version 2
  7
  8     function ConvertTo-HashtableFromPsCustomObject ($myPsObject){
  9         $output = @{};
 10         $myPsObject | Get-Member -MemberType *Property | % {
 11             $val = $myPsObject.($_.name);
 12             If ($val -is [psobject]) {
 13                 $val = ConvertTo-HashtableFromPsCustomObject $val
 14             }
 15             $output.($_.name) = $val
 16         }
 17         return $output;
 18     }
 19     # stream JSON including become_pw, ps_module_payload, bin_module_payload, become_payload, write_payload_path, p>
 20     # exec runspace, capture output, cleanup, return module output
 21
 22     # NB: do not adjust the following line- it is replaced when doing non-streamed module output
 23     $json_raw = @'
 24 ############### OMITTED ######################
 25 '@
 26 }
 27 process {
 28     $input_as_string = [string]$input
 29
 30     $json_raw += $input_as_string
 31 }
 32 end {
 33     If (-not $json_raw) {
 34         Write-Error "no input given" -Category InvalidArgument
 35     }
 36     $payload = ConvertTo-HashtableFromPsCustomObject (ConvertFrom-Json $json_raw)
 37
 38     # TODO: handle binary modules
 39     # TODO: handle persistence
 40
 41     $actions = $payload.actions
 42
 43     # pop 0th action as entrypoint
 44     $entrypoint = $payload.($actions[0])
 45     $payload.actions = $payload.actions[1..99]
 46
 47     $entrypoint = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($entrypoint))
 48
 49     # load the current action entrypoint as a module custom object with a Run method
 50     $entrypoint = New-Module -ScriptBlock ([scriptblock]::Create($entrypoint)) -AsCustomObject
 51
 52     Set-Variable -Scope global -Name complex_args -Value $payload["module_args"] | Out-Null
 53
 54     # dynamically create/load modules
 55     ForEach ($mod in $payload.powershell_modules.GetEnumerator()) {
 56         $decoded_module = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($mod.Value))
 57         New-Module -ScriptBlock ([scriptblock]::Create($decoded_module)) -Name $mod.Key | Import-Module -WarningAct>
 58     }
 59
 60     $output = $entrypoint.Run($payload)
 61
 62     Write-Output $output
 63 }
```
I omitted the raw JSON because it probably encodes some creds somewhere, but as you can see, line 51 is empty... 

If I assume the line 51 part was coming from the script resulting from decoding the `$json_raw`, i get this:
```
  1
  2 Set-StrictMode -Version 2
  3 $ErrorActionPreference = "Stop"
  4
  5 $helper_def = @"
  6 using System;
  7 using System.Diagnostics;
  8 using System.IO;
  9 using System.Text;
 10 using System.Threading;
 11 using System.Security;
 12 using System.Security.AccessControl;
 13 using System.Security.Principal;
 14 using System.Runtime.InteropServices;
 15
 16 namespace Ansible.Shell
 17 {
 18     public class NativeProcessUtil
 19     {
 20         public static void GetProcessOutput(StreamReader stdoutStream, StreamReader stderrStream, out string stdout>
 21         {
 22             var sowait = new EventWaitHandle(false, EventResetMode.ManualReset);
 23             var sewait = new EventWaitHandle(false, EventResetMode.ManualReset);
 24
 25             string so = null, se = null;
 26
 27             ThreadPool.QueueUserWorkItem((s) =>
 28             {
 29                 so = stdoutStream.ReadToEnd();
 30                 sowait.Set();
 31             });
 32
 33             ThreadPool.QueueUserWorkItem((s) =>
 34             {
 35                 se = stderrStream.ReadToEnd();
 36                 sewait.Set();
 37             });
 38
 39             foreach (var wh in new WaitHandle[] { sowait, sewait })
 40                 wh.WaitOne();
 41
 42             stdout = so;
 43             stderr = se;
 44         }
 45
 46         public static IntPtr GetElevatedToken(IntPtr hToken)
 47         {
 48             uint requestedLength;
 49
 50             IntPtr pTokenInfo = Marshal.AllocHGlobal(sizeof(int));
 51
 52             try
 53             {
 54                 if(!GetTokenInformation(hToken, TOKEN_INFORMATION_CLASS.TokenElevationType, pTokenInfo, sizeof(int)>
 55                     throw new Win32Exception("Unable to get TokenElevationType");
 56
 57                 var tet = (TOKEN_ELEVATION_TYPE)Marshal.ReadInt32(pTokenInfo);
 58
 59                 // we already have the best token we can get, just use it
...
```
Which also has an empty line 51....  So it looks like the line number is a red herring.

**Comment by jhawkesworth** [comment]
Sorry, the keep remote files advice wasn't any help.

I think perhaps the issue might be that the user's temp dir doesn't yet exist.  You might be able to create this with a

```
- name: ensure temp dir
   win_file: 
      state: present
      path: AppData\Local\Temp
```

I haven't checked the code though, so its possible win_file also needs the tempdir to exist as well.
If so you might be able to use raw to create it (perhaps in combination with a 'when' clause if this playbook will be re-run)

```
- name: make temp dir using raw
  raw: "New-Item -ItemType Directory -Force -Path C:\\Users\\{{ automation_username }}\AppData\Local\Temp"
```

**Comment by lucastheisen** [comment]
@jhawkesworth , I updated my example yaml per your suggestion:

>you might be able to use raw to create it (perhaps in combination with a 'when' clause if this playbook will be re-run)

```
---
- hosts: etl
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  vars:
    automation_username: "autotest"
    automation_password: "notsafe4YOU!"

  tasks:
  - name: Create automation user
    win_user:
      name: "{{ automation_username }}"
      password: "{{ automation_password }}"
      groups:
        - Users
      password_never_expires: yes
      state: present

  - name: Make temp dir using raw
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    raw: "New-Item -ItemType Directory -Force -Path C:/Users/{{ automation_username }}/AppData/Local/Temp"
    register: check_home_dir

  - name: Check temp dir
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    win_stat:
      path: "C:/Users/{{ automation_username }}/AppData/Local/Temp"
    register: check_home_dir

  - name: Copy credentials
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    win_template:
      src: ./credentials.j2
      dest: "C:/Users/{{ automation_username }}/credentials"
```

Still no dice:
```
...
ok: [asias-etl-auto.mitre.org] => {
    "changed": false,
    "stat": {
        "attributes": "Directory",
        "creationtime": 1515500293.9635859,
        "exists": true,
        "filename": "Temp",
        "isarchive": false,
        "isdir": true,
        "ishidden": false,
        "islnk": false,
        "isreadonly": false,
        "isreg": false,
        "isshared": false,
        "lastaccesstime": 1515500293.9635859,
        "lastwritetime": 1515500293.9635859,
        "owner": "BUILTIN\\Administrators",
        "path": "C:\\Users\\autotest\\AppData\\Local\\Temp",
        "size": 0
    }
}
...
fatal: [asias-etl-auto.mitre.org]: FAILED! => {
    "changed": false,
    "checksum": "b7c5dd1c24163d22b4bfea8793df638f60334a7d",
    "diff": [],
    "module_stderr": "#< CLIXML\r\nException calling \"Run\" with \"1\" argument(s): \"Exception calling \"Invoke\" with \"0\" argument(s): \r\n\"The running command stopped because the preference variable \"ErrorActionPreference\" or common \r\nparameter is set to Stop: Access is denied\"\"\r\nAt C:\\Users\\ansible\\AppData\\Local\\Temp\\xe3yzios.osu.ps1:51 char:1\r\n+ $output = $entrypoint.Run($payload)\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : ScriptMethodRuntimeException\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"1\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"2\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>",
    "module_stdout": "\r\nTrue\r\nTrue\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

**Comment by jhawkesworth** [comment]
I think ansible is using $env:tmp when it needs a remote tmp dir on windows.  I would be surprised if anything works without this environment variable being present for the automation user on the machine though.

If you use --step and run your playbook as far as just after running win_user, then you log in manually as the new user, then continue the playbook, does it complete successfully?

**Comment by lucastheisen** [comment]
@jhawkesworth , I tried the `--step`, then logged in as `autotest` after and manually checked for `$env:tmp`.  It was there, but the process failed in exactly the same fashion.  I also updated my example to check the env before attempting the `win_template` thusly:
```
---
- hosts: etl
  environment:
    http_proxy: "{{ http_proxy }}"
    https_proxy: "{{ https_proxy }}"
    no_proxy: "{{ no_proxy }}"
  vars:
    automation_username: "autotest"
    automation_password: "notsafe4YOU!"

  tasks:
  - name: Create automation user
    win_user:
      name: "{{ automation_username }}"
      password: "{{ automation_password }}"
      groups:
        - Users
      password_never_expires: yes
      state: present

  - name: Make temp dir using raw
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    raw: "New-Item -ItemType Directory -Force -Path C:/Users/{{ automation_username }}/AppData/Local/Temp"
    register: check_home_dir

  - name: Check temp dir
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    win_stat:
      path: "C:/Users/{{ automation_username }}/AppData/Local/Temp"
    register: check_home_dir

  - name: Check env for temp
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    raw: "Get-ChildItem env:"
    register: check_env_for_temp

  - name: Copy credentials
    become: True
    become_method: runas
    become_user: "{{ automation_username }}"
    vars:
      ansible_become_pass: "{{ automation_password }}"
    win_template:
      src: ./credentials.j2
      dest: "C:/Users/{{ automation_username }}/credentials"
```
Which resulted in the following:
```
...
    "stdout_lines": [
        "",
        "Name                           Value                                                                                   ",
        "----                           -----                                                                                   ",
        "ALLUSERSPROFILE                C:\\ProgramData                                                                          ",
        "APPDATA                        C:\\Users\\ansible\\AppData\\Roaming                                                        ",
        "ChocolateyInstall              C:\\ProgramData\\chocolatey                                                               ",
        "ChocolateyLastPathUpdate       Mon Dec 11 16:21:10 2017                                                                ",
        "ChocolateyToolsLocation        C:\\tools                                                                                ",
        "CommonProgramFiles             C:\\Program Files\\Common Files                                                           ",
        "CommonProgramFiles(x86)        C:\\Program Files (x86)\\Common Files                                                     ",
        "CommonProgramW6432             C:\\Program Files\\Common Files                                                           ",
        "COMPUTERNAME                   ASIAS-ETL-AUTO                                                                          ",
        "ComSpec                        C:\\Windows\\system32\\cmd.exe                                                             ",
        "LOCALAPPDATA                   C:\\Users\\ansible\\AppData\\Local                                                          ",
        "NUMBER_OF_PROCESSORS           8                                                                                       ",
        "OS                             Windows_NT                                                                              ",
        "Path                           C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPo...",
        "PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL                              ",
        "PROCESSOR_ARCHITECTURE         AMD64                                                                                   ",
        "PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 42 Stepping 1, GenuineIntel                                      ",
        "PROCESSOR_LEVEL                6                                                                                       ",
        "PROCESSOR_REVISION             2a01                                                                                    ",
        "ProgramData                    C:\\ProgramData                                                                          ",
        "ProgramFiles                   C:\\Program Files                                                                        ",
        "ProgramFiles(x86)              C:\\Program Files (x86)                                                                  ",
        "ProgramW6432                   C:\\Program Files                                                                        ",
        "PROMPT                         $P$G                                                                                    ",
        "PSExecutionPolicyPreference    Unrestricted                                                                            ",
        "PSModulePath                   C:\\Users\\ansible\\Documents\\WindowsPowerShell\\Modules;C:\\Program Files\\WindowsPowerShe...",
        "PUBLIC                         C:\\Users\\Public                                                                         ",
        "SystemDrive                    C:                                                                                      ",
        "SystemRoot                     C:\\Windows                                                                              ",
        "TEMP                           C:\\Users\\ansible\\AppData\\Local\\Temp                                                     ",
        "TMP                            C:\\Users\\ansible\\AppData\\Local\\Temp                                                     ",
        "USERDOMAIN                     ASIAS-ETL-AUTO                                                                          ",
        "USERNAME                       ansible                                                                                 ",
        "USERPROFILE                    C:\\Users\\ansible                                                                        ",
        "windir                         C:\\Windows                                                                              ",
        "",
        ""
    ]
...
fatal: [asias-etl-auto.mitre.org]: FAILED! => {
    "changed": false,
    "checksum": "b7c5dd1c24163d22b4bfea8793df638f60334a7d",
    "diff": [],
    "module_stderr": "#< CLIXML\r\nException calling \"Run\" with \"1\" argument(s): \"Exception calling \"Invoke\" with \"0\" argument(s): \r\n\"The running command stopped because the preference variable \"ErrorActionPreference\" or common \r\nparameter is set to Stop: Access is denied\"\"\r\nAt C:\\Users\\ansible\\AppData\\Local\\Temp\\3iahrtli.tys.ps1:51 char:1\r\n+ $output = $entrypoint.Run($payload)\r\n+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : ScriptMethodRuntimeException\r\n<Objs Version=\"1.1.0.1\" xmlns=\"http://schemas.microsoft.com/powershell/2004/04\"><Obj S=\"progress\" RefId=\"0\"><TN RefId=\"0\"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"1\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S=\"progress\" RefId=\"2\"><TNRef RefId=\"0\" /><MS><I64 N=\"SourceId\">1</I64><PR N=\"Record\"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>",
    "module_stdout": "\r\nTrue\r\nTrue\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```
As you can see, `$env:TMP` (as well as `$env:TEMP`) is present and set correctly...

**Comment by jborean93** [comment]
There is a long and complicated reason why this is happening but I'll try and sum it up

* When Ansible goes to get the temp dir for an action, it just get's the value of `$env:temp` for the connection user - this case would be `C:\Users\ansible\AppData\Local\Temp`
* Your new user is not an admin so won't have rights to read from that temp folder , hence the access is denied when it tries to copy the template file from the ansible user's temp path
* Even those you are running it on become, the mktemp/get temp is run without become due to various limitations so the temp path won't change. I believe this is different from non-Windows as become is done on the connection plugin compared to the shell plugin

From 2.5 you can customise the temp path of Windows by setting the `ansible_remote_tmp` variable to a common location accessible by both users. Your template task would look like this

```
- name: Copy credentials
  become: True
  become_method: runas
  become_user: "{{ automation_username }}"
  vars:
    ansible_become_pass: "{{ ansible_password }}"
    ansible_remote_tmp: C:\temp  # this needs to exist and accessible by both the conn user and the become user
  win_template:
    src: ./credentials.j2
    dest: "C:/Users/{{ automation_username }}/credentials"
```

Unfortunately for previous versions there isn't much you can do apart from changing `TEMP` of the connection user before the template task and then changing it back but that can get tricky.

I'm going to change the issue title to correctly reflect the issue at hand. I'm not even 100% sure we can change this anyway due to the differences in the become mechanism between runas and the others but will look into it.
