### ISSUE TITLE
mysql_db module should use option `--defaults-file` instead of `--defaults-extra-file`

### ISSUE THREAD

**Issue by iredmail** [ansible/ansible#34488]
##### ISSUE TYPE

- Bug Report

##### COMPONENT NAME

* module: `mysql_db`

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/zhb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible-2.4.1.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

None.

##### OS / ENVIRONMENT

macOS 10.13.2

##### SUMMARY

`mysql_db` module uses mysql command line option `--defaults-extra-file=` instead of `--defaults-file`, if file `~/.my.cnf` exists, but we use another `.my.cnf` file in `mysql_db` module with `state=import`, sql connection will fail.

##### STEPS TO REPRODUCE

* ~/.my.cnf:
```
[client]
user=root
password="xxxx"
host=xxxx.rds.amazonaws.com
port=3306
```

* ~/.my.cnf-myuser
```
[client]
user="myuser"
password="yyyy"
host="xxxx.rds.amazonaws.com"
port=3306
```

Task:

```
    - name: "test"
      mysql_db:
          state: import
          name: mydb
          target: /tmp/check_sql_db.sql
          login_host: xxxx.rds.amazonaws.com
          login_port: 3306
          login_user: myuser
          config_file: /root/.my.cnf-myuser
```

Error message:

```
    "msg": "ERROR 1045 (28000): Access denied for user 'root'@'172.31.2.83' (using password: YES)\n"
```

##### EXPECTED RESULTS

Expect Ansible to use `/root/.my.cnf-myuser` and do not load any other `.my.cnf` file.

I replaced `--defaults-extra-file=` by `--defaults-file=` in `mysql_db` module source file, run same task, it works fine.
