### ISSUE TITLE
Failed to connect to the host via ssh: shared connection to x.x.x.x. closed. \r\n", unreachable true

### ISSUE THREAD

**Issue by akarsht0812** [ansible/ansible#34485]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/os-deploy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

it did not produce anything and i didn't change anything in ansible config file
##### OS / ENVIRONMENT

os- centos
##### SUMMARY

I am trying to deploy a package using playbook, I am able to connect to the remote host using ssh and command "ansible all -i hosts -m ping"gives the output as success and my playbook is working good for first two steps like PLAY, GATHERING FACTS, and for a task to create folder in destination, but the error occurs when it is trying to unarchive the package on the destination server.

BTW, build is a variable that I am passing while executing the playbook. 
The command I run is ansible-playbook -i hosts deploy.yml -e "BUILD=XYZ" where hosts is my inventory file.
##### STEPS TO REPRODUCE

```yaml

---

- hosts: deploy
  become: yes
  become_user: root
  become_method: su

  tasks:

   - name: create destination folder
     file:
       path: /virtuals/releases/{{BUILD}}
       state: directory

   - name: extract the archive
     unarchive:
       src: /virtuals/releases/workspace/{{BUILD}}/xyz.tar.gz
       dest: /virtuals/releases/{{BUILD}}
       owner: nginx
       group: users

```
```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? --
untar the package on the destination servers
##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->
fatal: [x.x.x.x]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to x.x.x.x closed.\r\n", "unreachable": true}
fatal: [x.x.x.x]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to x.x.x.x closed.\r\n", "unreachable": true}
<!--- Paste verbatim command output between quotes below -->
```
