### ISSUE TITLE
`with_fileglob` always looks up files on localhost

### ISSUE THREAD

**Issue by riccardomurri** [ansible/ansible#34497]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
`with_fileglob` core built-in looping feature.

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### CONFIGURATION
Empty `ansible.cfg` file.

##### OS / ENVIRONMENT
```
 $ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:    17.10
Codename:   artful
```

##### SUMMARY
Looping over existing files with `with_fileglob` always looks up
filesystem entries on the *controller* host where Ansible is running,
and not on the target host.

##### STEPS TO REPRODUCE
Use the following playbook to reproduce:
```yaml
---

- name:
  hosts: all
  gather_facts: yes

  tasks:
    - name: Make test files
      file:
        name: '/tmp/issue-test.{{item}}'
        state: touch
      with_items:
        - foo
        - bar
        - baz

    - name: List results of `with_fileglob`
      debug:
        msg: 'path={{ item }}'
      with_fileglob: '/tmp/issue-test.*'

```

1. Remove any local files matching the glob pattern:

        rm -f /tmp/issue-test.*

2. Run the playbook targeting any remote host -- files `/tmp/issue-test.{foo.bar.baz}` will be created but not listed.

##### EXPECTED RESULTS
I would expect `with_fileglob` to look up files remotely.

If this is not the intended behavior, it should be clearly stated in the docs.
(Still, I would like a way to do file globs with remote files.)

##### ACTUAL RESULTS
Ansible expands `with_fileglob` with contents of a local file lookup.
This can be seen by running the above playbook:

```bash
# ensure that no test files exist locally
$ rm /tmp/issue-test.*

# now run ansible targeting a remote host -- no files are listed
$ ansible-playbook -i "ubuntu@172.23.28.106," /tmp/issue.yml

PLAY [all] ***************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [ubuntu@172.23.28.106]

TASK [Make test files] ***************************************************************************************************************************************
changed: [ubuntu@172.23.28.106] => (item=foo)
changed: [ubuntu@172.23.28.106] => (item=bar)
changed: [ubuntu@172.23.28.106] => (item=baz)

TASK [List results of `with_fileglob`] ***********************************************************************************************************************

PLAY RECAP ***************************************************************************************************************************************************
ubuntu@172.23.28.106       : ok=2    changed=1    unreachable=0    failed=0
```
