### ISSUE TITLE
loop over items or variables dont work

### ISSUE THREAD

**Issue by coffee-driven** [ansible/ansible#34502]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/m/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Linux host 4.10.0-42-generic #46~16.04.1-Ubuntu SMP Mon Dec 4 15:57:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

now testing ansible configuration in vagrant/
Linux workstation 3.10.0-123.20.1.el7.x86_64 #1 SMP Thu Jan 29 18:05:33 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

i have problem loop over variables or items

shortly i want to dynamically edit db users. My idea is have a yml file with setup and yml file with variables.
expected result is to have tasks/main.yml as template for editing users etc. and vars/main.yml as list of variables. 

example:
```yaml
- postgresql_user:
     db: "{{ item.db }}"
     name: "{{ item.name }}"
     password: secret        
     priv: "{{ item.priv }}"
     with_items:                  
       - { name: test66, db: test44, priv: ALL }
```
after running this playbook it return item i undefined. I dont understand where is problem with this easy task..
```
task path: /home/m/Documents/Vagrant/postgresql/tests/roles/psql/tasks/main.yml:1
fatal: [default]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'item' is undefined\n\nThe error appears to have been in '/home/m/Documents/Vagrant/postgresql/tests/roles/psql/tasks/main.yml': line 1, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- postgresql_user:\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'item' is undefined"}
```

i tried to fill variables with /roles/name/vars/main.yml - it works but only for one user. I need to fill bunch o users. 
this easy example is working.
role/name/tasks/main.yml

```
 postgresql_user:
    db: "{{ db }}"
    password: secret          
    name: "{{ name }}"
    port: "{{ port }}"
```

/role/name/vars/main.yml
```
name: test66   
password: secret 
port: 5432 
db: test44
```
I tried to, fill variables for more users like this(also work):
/role/name/vars/main.yml
```
user1:
 name: test65  
 password: secret
 port: 5432
 db: test44 

user2:
 name: test100
 port: 5432
 db: test44
```
in the case above i always need to specify variable to fill from it is not ideal. 
exmp:
```
- postgresql_user:
    db: "{{ user2.db }}"
    password: secret          
    name: "{{ user2.name }}"
    port: "{{ user2.port }}"
```
what i want i only add new user to vars file and dont specify variable in tasks/main.yml file.

I tried loops and with_items (example above) but it doesnt work even if the items are listed in tasks/main.yml file.
```
my structure:
  hosts_vars/
  hosts
  playbook.yml
  roles/
    -pgsql/
       -defaults/
       -tasks/
          - main.yml
       -vars/
          -main.yml
```
cat playbook.yml 
```
- hosts: all
  remote_user: root
  gather_facts: no
  any_errors_fatal: True
  roles:
    - psql
```
thanks for help.

**Comment by Akasurde** [comment]
@gitm1993 identation of  `with_items` seems to be odd to me. Is it typo ?

It should look like this - 

```yaml
- postgresql_user:
     db: "{{ item.db }}"
     name: "{{ item.name }}"
     password: secret        
     priv: "{{ item.priv }}"
  with_items:                  
       - { name: test66, db: test44, priv: ALL }
```
