### ISSUE TITLE
win_iis_website always changed with parameter logExtFileFlags

### ISSUE THREAD

**Issue by jn-bedag** [ansible/ansible#34500]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_iis_website.ps1

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### SUMMARY
The module win_iis_website is not working as expexted. If we set the logfile.logExtFileFlags with a parameter, the module is always reported as "changed".
Other parameters might be affected as well.

##### STEPS TO REPRODUCE
```yaml
---
- name: testweb
  hosts: all
  gather_facts: no

  tasks:

    - name: create website
      win_iis_website:
        name: "testwebsite"
        application_pool: "DefaultAppPool"
        physical_path: "c:\\temp"
        port: "999"
        parameters: logfile.directory:C:\iislogs\testwebsite|logfile.logExtFileFlags:Date,Time,ClientIP,UserName,ServerIP,Method,UriStem,UriQuery,HttpStatus,Win32Status,TimeTaken,ServerPort,UserAgent,HttpSubStatus
```
Module is always reported as "changed".
If we delete the logfile.logExtFileFlags parameter and keep the logfile.directory, then the module is correctly reported as "ok".

##### EXPECTED RESULTS
Module should be reported as "ok".
```
ok=1 changed=0
```

##### ACTUAL RESULTS
```
changed=1
```
##### ANALYSIS

There are different types of IIS configuration attributes with Get-ItemProperty.
```
PS C:\> (Get-ItemProperty "IIS:\Sites\testwebsite" logfile.directory).gettype()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    ConfigurationAttribute                   System.Object


PS C:\> (Get-ItemProperty "IIS:\Sites\testwebsite" logfile.logExtFileFlags).gettype()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String                                   System.Object
```
Therefore in win_iis_website.ps1, the following if statement seems not correct, because of a wrong combination of ".value" and the conditions:
```
if((-not $parameter_value) -or ($parameter_value.Value -as [String]) -ne $_[1]) {
```
If the attribute is a "String", the second condition is always true.
