### ISSUE TITLE
Ansible conditionals cannot handle decimals requiring overly complex workarounds

### ISSUE THREAD

**Issue by Routhinator** [ansible/ansible#34511]
Took me a bit to figure this one out, not sure if this is Jinja or Ansible.

I've recently gone through the pain of trying to write a cookbook to conditionally install VMWare tools or open VM tools based on the `ansible_distribution_version` and found it wasn't possible. Ansible cannot tell the difference between 6.2, 6.8 or 6.9 in conditional comparisons.

These do not work:
```
---
- name: Add Extra Packages for Enterprise Linux repository
  yum_repository:
    name: epel
    description: EPEL-{{ ansible_distribution_version }} - Extra Packages for Enterprise Linux
    baseurl: http://software.global.prv/epel/{{ ansible_distribution_major_version }}/$basearch/
    gpgkey: http://software.global.prv/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    gpgcheck: yes
    enabled: yes

- name: Install vmware-tools repository.
  yum: name={{ vmwaretools_yum_server }}{{ vmwaretools_yum_path }}/esx/{{ vmwaretools_tools_version }}/repos/vmware-tools-repo-RHEL{{ ansible_distribution_major_version }}-{{ vmwaretools_repo_version }}.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm state=present
  when: ansible_distribution_version <= 6.8

- name: Install vmware-tools gpg key
  shell: yum clean all && yum makecache -y

- name: Install openvm-tools
  package:
    name: open-vm-tools
    state: latest
  when: ansible_distribution_version > 6.8

- name: Install vmware-tools.
  yum: name={{ item }} state=present
  with_items:
    - vmware-tools-esx-nox
    - vmware-tools-esx-kmods
  update_cache: yes
  when: ansible_distribution_version <= 6.8

- name: Start vmtoolsd and enable vmtoolsd to start during boot for CentOS/RHEL 6.9 and higher.
  service: name=vmtoolsd state=started enabled=yes
  failed_when: false
  when: ansible_distribution_version > 6.8

- name: Start and enable vmware-tools-services during boot for CentOS/RHEL 6.8 and lower.
  service: name=vmware-tools-services state=started enabled=yes
  failed_when: false
  when: ansible_distribution_version <= 6.8
```

These do work: 
```
- name: Add Extra Packages for Enterprise Linux repository
  yum_repository:
    name: epel
    description: EPEL-{{ ansible_distribution_version }} - Extra Packages for Enterprise Linux
    baseurl: http://software.global.prv/epel/{{ ansible_distribution_major_version }}/$basearch/
    gpgkey: http://software.global.prv/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
    gpgcheck: yes
    enabled: yes

- name: Install vmware-tools repository.
  yum: name={{ vmwaretools_yum_server }}{{ vmwaretools_yum_path }}/esx/{{ vmwaretools_tools_version }}/repos/vmware-tools-repo-RHEL{{ ansible_distribution_major_version }}-{{ vmwaretools_repo_version }}.el{{ ansible_distribution_major_version }}.{{ ansible_architecture }}.rpm state=present
  when: ansible_distribution_major_version == 6 and ansible_distribution_minor_version <= 8

- name: Install vmware-tools gpg key
  shell: yum clean all && yum makecache -y

- name: Install openvm-tools
  package:
    name: open-vm-tools
    state: latest
  when: ansible_distribution_major_version == 7 or (ansible_distribution_major_version == 6 and ansible_distribution_minor_version > 8)

- name: Install vmware-tools.
  yum: name={{ item }} state=present
  with_items:
    - vmware-tools-esx-nox
    - vmware-tools-esx-kmods
  update_cache: yes
  when: ansible_distribution_major_version == 6 and ansible_distribution_minor_version <= 8

- name: Start vmtoolsd and enable vmtoolsd to start during boot for CentOS/RHEL 6.9 and higher.
  service: name=vmtoolsd state=started enabled=yes
  failed_when: false
  when: ansible_distribution_major_version == 7 or (ansible_distribution_major_version == 6 and ansible_distribution_minor_version > 8)

- name: Start and enable vmware-tools-services during boot for CentOS/RHEL 6.8 and lower.
  service: name=vmware-tools-services state=started enabled=yes
  failed_when: false
  when: ansible_distribution_major_version == 6 and ansible_distribution_minor_version <= 8
```

Expected behaviour is that ansible should be able to work with decimal numbers for simple comparisons.
