### ISSUE TITLE
java_cert module: Certificates are only compared by alias, not content.

### ISSUE THREAD

**Issue by chrisgavin** [ansible/ansible#34557]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
java_cert

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When importing a certificate from a PKCS12 keystore into a Java keystore, the import does not happen if a certificate already exists with the same alias, regardless of whether that certificate is actually the same as the one being imported.

This is very annoying if you are trying to replace an automatically generated certificate with your own trusted one.

##### STEPS TO REPRODUCE
Have two different certificates at `/tmp/certificate.p12` and `/tmp/someothercertificate.p12`.

```yaml
- java_cert:
    keystore_pass: keystorepass
    keystore_path: /tmp/mykeystore.jks
    keystore_create: true
    cert_alias: somealias
    pkcs12_path: /tmp/certificate.p12
    state: present
- java_cert:
    keystore_pass: keystorepass
    keystore_path: /tmp/mykeystore.jks
    cert_alias: somealias
    pkcs12_path: /tmp/someothercertificate.p12
    state: present
```
##### EXPECTED RESULTS
Both tasks should report as changed and `/tmp/someothercertificate.p12` should be in `/tmp/mykeystore.jks`.

##### ACTUAL RESULTS
Only the first task reports as changed and the only thing in the Java keystore is `/tmp/certificate.p12`.
