### ISSUE TITLE
aci: Ability to assign a static port to an EPG is missing

### ISSUE THREAD

**Issue by JamesNesta** [ansible/ansible#34587]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- aci_epg_to_domain

##### SUMMARY
The Cisco ACI module has recently been integrated into the core Ansible repository. This is fantastic! However, it does not seem to be currently possible to add a static port to an EPG (end-point group). This is a very common task - can this be added as well to core?

Here is a screenshot of me doing this manually in the Cisco APIC web GUI by right clicking a test EPG.

![image](https://user-images.githubusercontent.com/35046300/34683720-e5c8ec70-f470-11e7-8820-5a6043c23344.png)

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by JamesNesta** [comment]
!component https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/aci/aci_epg_to_domain.py
!component https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/aci/aci.py

**Comment by alikins** [comment]
cc @GGabriele @jedelman8 @kedarX @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/module_utils/network/aci/aci.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/network/aci/aci.py)
* [lib/ansible/modules/network/aci/aci_epg_to_domain.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/aci/aci_epg_to_domain.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Qalthos @brunocalogero @dagwieers @ganeshrn @gundalow @jmcgill298 @schunduri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by JamesNesta** [comment]
Oh! And furthermore, here is the JSON call for this as reported from the web GUI:
(I created a test static port and the right-clicked it and did "Save As" and exported it as JSON)

```
{"totalCount":"1","imdata":[{"fvRsPathAtt":{"attributes":{"descr":"","dn":"uni/tn-USTCAG/ap-USTCAG_AP/epg-USTCAG_Inside_EPG/rspathAtt-[topology/pod-1/paths-101/pathep-[eth1/44]]","encap":"vlan-4011","instrImedcy":"lazy","mode":"regular","primaryEncap":"unknown","tDn":"topology/pod-1/paths-101/pathep-[eth1/44]"}}}]}
```

**Comment by dagwieers** [comment]
We have a list of stuff we would like to do (preferably before v2.5 is released), you can find it here: https://github.com/ansible/community/wiki/Network:-ACI

Contributions are welcomed too.

**Comment by dagwieers** [comment]
Let me also add that this is already possible using the **aci_rest** module.

```yaml
  - name: Add static binding to EPG
    aci_rest:
      hostname: <apic>
      username: <admin>
      password: <password>
      method: post
      path: /api/node/mo/uni/tn-USTCAG/ap-USTCAG_AP/epg-USTCAG_Inside_EPG/rspathAtt-[topology/pod-1/paths-101/pathep-[eth1/44]].json
      content:
        fvRsPathAtt: 
          attributes:
            encap: vlan-4011
            instrImedcy: lazy
            mode: regular
            primaryEncap: unknown
            tDn: topology/pod-1/paths-101/pathep-[eth1/44]
```

But we do have **aci_static_binding_to_epg** on the roadmap.
