### ISSUE TITLE
gce module state started returns no useful information and requires a 2nd task with state present to gather information

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#34580]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gce

##### ANSIBLE VERSION
```
seans-mbp:provisionner sean$ ansible --version
ansible 2.5.0
  config file = /Users/sean/Documents/GitHub/IPvSean/darkbulb/provisionner/ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT
macOS High Sierra Version 10.13.2

##### SUMMARY
The state `started` and state `present` are not well documented on the Ansible module page.  But from testing it is odd.... the `state: started` works fine but the return values is almost useless, so you have to call the gce module again with the `state: present` to get any info out of it (like private and public IP information).
##### STEPS TO REPRODUCE

This task
```yaml
- name: "Create student instance"
  gce:
    instance_names: "{{ student }}"
    zone: "{{ gce_cloud_instance_zone }}"
    machine_type: "{{ gce_cloud_instance_machine_type }}"
    image: "{{ gce_cloud_instance_image }}"
    service_account_email: "{{ gce_cloud_instance_service_account_email }}"
    credentials_file: "{{ gce_cloud_instance_credentials_file }}"
    project_id: "{{ gce_cloud_instance_project_id }}"
    tags: "{{ gce_cloud_instance_tags }}"
    state: started
  tags:
    - create
```
only returns this->
```
ok: [localhost] => {
    "return_gce_cloud_instance": {
        "changed": true, 
        "failed": false, 
        "instance_names": [
            "student01"
        ], 
        "state": "started", 
        "zone": "us-east1-d"
    }
}
```

##### EXPECTED RESULTS
I would hope I would get identical results from the `state: present`
```
- name: "grab student instance public ip address"
  gce:
    instance_names: "{{ student }}"
    zone: "{{ gce_cloud_instance_zone }}"
    service_account_email: "{{ gce_cloud_instance_service_account_email }}"
    credentials_file: "{{ gce_cloud_instance_credentials_file }}"
    project_id: "{{ gce_cloud_instance_project_id }}"
    state: present
  register: return_gce_cloud_instance
```

 which yields this->
```yml
    "return_gce_cloud_instance": {
        "changed": false, 
        "failed": false, 
        "instance_data": [
            {
                "disks": [
                    "student01"
                ], 
                "image": "nested-vm-image", 
                "machine_type": "n1-highmem-4", 
                "metadata": {}, 
                "name": "student01", 
                "network": "default", 
                "private_ip": "10.142.0.2", 
                "public_ip": 10.3.2.1, 
                "status": "TERMINATED", 
                "subnetwork": "default", 
                "tags": [
                    "darkbulb", 
                    "http-server", 
                    "https-server"
                ], 
                "zone": "us-east1-d"
            }
        ], 
        "instance_names": [
            "student01"
        ], 
        "state": "present", 
        "zone": "us-east1-d"
    }
}
```
##### ACTUAL RESULTS
This is listed above, but `state: started` only does this->
```
ok: [localhost] => {
    "return_gce_cloud_instance": {
        "changed": true, 
        "failed": false, 
        "instance_names": [
            "student01"
        ], 
        "state": "started", 
        "zone": "us-east1-d"
    }
}
```
The information I want to gather is the public ip address (`public_ip`) which is only found with state set to present.  The problem is that present does not actually start the VM, just checks to see if it exists... so I can get a playbook working but it requires two tasks.
