### ISSUE TITLE
gce_instance_template won't select image for centos-7

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#34588]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gce_instance_template

##### ANSIBLE VERSION
```
seans-mbp:provisionner sean$ ansible --version
ansible 2.5.0
  config file = /Users/sean/Documents/GitHub/IPvSean/darkbulb/provisionner/ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT
macOS High Sierra Version 10.13.2

##### SUMMARY
using the gce_instance_template to set the image as `centos-7` or image_family as `centos-7` will result in nothing being selected for the image type.  The only way I could get it to work was to create one through the webGUI, copy the exact image (in my case it used `centos-7-v20180104`) and then copy that value into my playbook and pass it in as a sourceImage.  This would allow me to actually create a vm from the instance template.  Every other way would error out.
##### STEPS TO REPRODUCE
```yaml
---
- name: create instance template named foo
  gce_instance_template:
    name: foo
    size: "{{ gce_cloud_instance_machine_type }}"
    state: present
    project_id: "{{ gce_cloud_instance_project_id }}"
    image_family: centos-7
    credentials_file: "{{ gce_cloud_instance_credentials_file }}"
    service_account_email: "{{ gce_cloud_instance_service_account_email }}"
    disks_gce_struct:
      - device_name: /dev/sda
        boot: true
        autoDelete: true
        initializeParams:
          diskSizeGb: 30
          diskType: pd-standard
```

##### EXPECTED RESULTS
It would create the VM instance.  Under the Instance templates page, the image column is just blank  if you use `image_family` or `image` with just `centos-7`.  This should point to the newest `centos-7` image (which will have the date in it...)

##### ACTUAL RESULTS
This was the only playbook I could use to make it work:
```
---
- name: create instance template named foo
  gce_instance_template:
    name: foo
    size: "{{ gce_cloud_instance_machine_type }}"
    state: present
    project_id: "{{ gce_cloud_instance_project_id }}"
    credentials_file: "{{ gce_cloud_instance_credentials_file }}"
    service_account_email: "{{ gce_cloud_instance_service_account_email }}"
    disks_gce_struct:
      - device_name: /dev/sda
        boot: true
        autoDelete: true
        initializeParams:
          diskSizeGb: 30
          diskType: pd-standard
          sourceImage: projects/centos-cloud/global/images/centos-7-v20180104
```
I should be able to somehow grab latest instead of having to specify the v20180104 part.
