### ISSUE TITLE
Win_dns_client doesn't properly detect/change order of DNS resolvers.

### ISSUE THREAD

**Issue by chriskarel** [ansible/ansible#34651]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_dns_client
(lib/ansible/modules/windows/win_dns_client.ps1)

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 29 2017, 20:42:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

Defaults

##### OS / ENVIRONMENT

Ansible is running on an OEL7.4 machine, managing a Windows 2012R2 machine.

##### STEPS TO REPRODUCE

Use win_dns_client to attempt to change the order of DNS resolvers.  If the resolver IP addresses are the same (but in a different order), the module will fail to notice the order changing, and not make any changes.

```yaml
- name: configure DNS on Windows
  hosts: all
  tasks:
  - name: reconfigure DNS
    win_dns_client:
      adapter_names: "*"
      ipv4_addresses:
        - 8.8.8.8
        - 8.8.4.4

  - name: Re-order DNS entries
    win_dns_client:
      adapter_names: "*"
      ipv4_addresses:
        - 8.8.4.4
        - 8.8.8.8

```

##### EXPECTED RESULTS

I would expect the second play, "Re-order DNS entries" to be marked as 'changed'.  Likewise, I would expect the DNS resolvers on the Windows machine to have its order changed accordingly.

##### ACTUAL RESULTS

The second run is not marked as changed. And no changes are made on the Windows host.

```
# ansible-playbook change_dns.yaml -i test.hosts

PLAY [configure DNS on Windows] ****************************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************************************
ok: [testbox]

TASK [reconfigure DNS] *************************************************************************************************************************************************************************************************
ok: [testbox]

TASK [Re-order DNS entries] ********************************************************************************************************************************************************************************************
ok: [testbox]

PLAY RECAP *************************************************************************************************************************************************************************************************************
testbox       : ok=3    changed=0    unreachable=0    failed=0   
```
