### ISSUE TITLE
Add option to win_domain to include management tools during install

### ISSUE THREAD

**Issue by Chiggins** [ansible/ansible#34675]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
win_domain

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/chiggins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Dec 21 2016, 07:16:46) [GCC 6.2.1 20160830]
```

##### CONFIGURATION
```
Not applicable 
```

##### OS / ENVIRONMENT
Arch Linux

##### SUMMARY
When creating a new Active Directory domain, it is more often than not useful to have the management tools installed on the domain controller. I'm proposing adding an option to the `win_domain` module that would include installation of the AD DS management tools when installing the AD DS Windows feature. Documentation can be found [here](https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/deploy/install-active-directory-domain-services--level-100-).

##### STEPS TO REPRODUCE
Ideally, before [installing the Windows feature](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_domain.ps1#L33), a check can be done on the `include_management_tools` options. If it's yes, tack on `-IncludeManagementTools` to include the tools.

```yaml
win_domain:
    dns_domain_name: lab.local
    safe_mode_password: Password123!
    include_management_tools: yes
```

##### EXPECTED RESULTS
The AD DS management tools, such as the Active Directory Administration Center, will be installed.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_domain.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_domain.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_domain.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_domain.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
I am not in favor of this, we already have a **win_feature** module for this, and we don't need additional functionality to the **win_domain** module. One can create a role to have a more advanced AD setup routine.

```yaml
- win_feature:
    name: '{{ item }}'
    include_management_tools: yes
  with_items:
  - AD-domain-services
  - DNS

- win_domain:
    dns_domain_name: lab.local
    safe_mode_password: Password123!
```
