### ISSUE TITLE
lvm modules - lvg and lvol-  failing on SLES11 SP1-SP3 maybe SP4

### ISSUE THREAD

**Issue by jottschi** [ansible/ansible#34686]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lvg

##### ANSIBLE VERSION

```
config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### SUMMARY
When creating a VG and a LV inside in this it disappears after rebooting. On SLES 11.
##### STEPS TO REPRODUCE

```yaml
---
- name: Add LVM-DISKS and filesystem
  hosts: ZEN-REMOTE
  gather_facts: true

  tasks:
    - name: check for device
      stat: path=/dev/mapper/vgNEW-lvNEW
      register: NEWdisk

    - name: rescanning for new disks
      command: /usr/bin/rescan-scsi-bus.sh
      when:  not NEWdisk.stat.exists

    - name: create pysical Volume for zen
      lvg:
       vg: vgNEW
       pvs: /dev/sdc
       state: present
      register: pvcreate.changed
      when: not NEWdisk.stat.exists

    - name: create ZEN LVM l-vol
      lvol:
       vg: vgNEW
       lv: lvNEW
       size: 100%FREE
       state: present
      when: not NEWdisk.stat.exists


    - name: create XFS-Filesystem
      filesystem:
       fstype: xfs
       dev: /dev/mapper/vgNEW-lvNEW
       opts: -L newLV
      ignore_errors: true
      when: not NEWdisk.stat.exists

    - name: Mount new device by label
	  # creates fstab entry
      mount:
       path: /mnt/newLV
       src: LABEL=newLV
       fstype: xfs
       opts: noatime
       state: mounted
```

##### EXPECTED RESULTS
After running this playbook I can access the new filesystem.
##### ACTUAL RESULTS
After reboot it is not accessible.

Solution: toggle in  /etc/sysconfig/lvm 
LVM_ACTIVATED_ON_DISCOVERED="disable"
to
LVM_ACTIVATED_ON_DISCOVERED="enable"

```

```
