### ISSUE TITLE
lineinfile with regexp is not idempotent

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#34690]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lineinfile

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

lineinflile with regex is inconsistent

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - name: place file
      copy:
        dest: /tmp/test
        content: |
          first line
          replace
          third line

    - name: replace line
      lineinfile:
        path: /tmp/test
        regexp: replace
        line: REPLACED
      with_sequence: start=0  end=4
```

##### EXPECTED RESULTS

First iteration `changed`, subsequent iterations `ok`
```
first line
REPLACED
third line
```
##### ACTUAL RESULTS

First iteration does correct replace, subsequent iterations add new line to the end of the file.

```
first line
REPLACED
third line
REPLACED
REPLACED
REPLACED
REPLACED
```
