### ISSUE TITLE
junos_vlan missing DI parameter interface 

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#34709]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
junos_vlan

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The eos_vlan module can check if interfaces have operational state or declarative intent (DI) of carrying the vlan (e.g. `show vlan`) ->
```yaml
---
- hosts: eos
  connection: network_cli
  remote_user: admin
  become: yes
  become_method: enable
  vars:
    ansible_network_os: "eos"
  tasks:
    - eos_vlan:
        state: active
        purge: yes
        aggregate:
          - { vlan_id: 1, name: default }
          - { vlan_id: 2, name: Vl2 }
          - { vlan_id: 3, state: suspend }
        interfaces:
          - Ethernet1
          - Ethernet2
```
This playbook will error and fail (by default) if the interface does not carry the VLAN
```fatal: [eos]: FAILED! => {"attempts": 1, "changed": false, "msg": "Interface Ethernet1 not configured on vlan 2"}```

This is correct because this is not configure as shown by the `show vlan`
```yml
localhost#show vlan
VLAN  Name                             Status    Ports
----- -------------------------------- --------- -------------------------------
1     default                          active    Et1, Et2, Et3
2     Vl2                              active
3     VLAN0003                         suspended
```

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A FR to match eos_vlan

##### ACTUAL RESULTS
N/A FR to match eos_vlan
