### ISSUE TITLE
ios_user: issue attempting to remove multiple users

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#34701]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
--> ios_user

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /opt/isv/netflow/venvs/alsible/ansible/ansible.cfg
  configured module search path = ['/home/<user>/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/isv/netflow/pyenv/versions/3.6.2/envs/py3ansible/lib/python3.6/site-packages/ansible
  executable location = /opt/isv/netflow/pyenv/versions/py3ansible/bin/ansible
  python version = 3.6.2 (default, Aug 19 2017, 16:48:59) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
```

##### CONFIGURATION
```
DEFAULT_FORKS(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = 15
DEFAULT_HOST_LIST(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = ['/opt/isv/netflow/venvs/alsible/ansible/m
DEFAULT_LOCAL_TMP(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = /opt/isv/netflow/temp/ansible/ansible-loca
DEFAULT_LOG_PATH(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = ['/opt/isv/netflow/venvs/alsible/ansible/
DEFAULT_VAULT_PASSWORD_FILE(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = /home/<user>/vault_pass.txt
HOST_KEY_CHECKING(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = False
PARAMIKO_RECORD_HOST_KEYS(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/opt/isv/netflow/venvs/alsible/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
--> Red Hat 4.4.7-18

##### SUMMARY
When attempting to remove multiple users on c2951, the module doesn't account for the confirmation message from the IOS and reply.

##### STEPS TO REPRODUCE
 

```- name: Delete users with aggregate
  ios_user:
    aggregate:
      - name: ansibletest1
      - name: ansibletest2
      - name: ansibletest3
    state: absent
```

##### EXPECTED RESULTS
--> Expected the user accounts to be deleted

##### ACTUAL RESULTS

[git_issue_ios_user.txt](https://github.com/ansible/ansible/files/1623933/git_issue_ios_user.txt)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/ios/ios_user.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_user.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kedarX @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Qalthos** [comment]
Well, I can't reproduce this. Prompts are definitely a thing that should be handled properly already. This _looks_ like the output one would expect if the users are already removed from the device.

That said, if you're sure the users are there, could you please show me the full `-vvv` output of the following playbook (adapted to your environment):

```
---
- hosts: ios
  gather_facts: no
  connection: local

  vars:
    - userlist:
        - name: ansibletest1
        - name: ansibletest2
        - name: ansibletest3

  tasks:
    - name: Create users
      ios_user:
        aggregate: "{{ userlist }}"
        nopassword: yes
        state: present

    - name: Remove users
      ios_user: &remove
        aggregate: "{{ userlist }}"
        state: absent
      register: result

    - name: Check that users are removed
      ios_user: *remove
```

That should give me a better idea of where things are going wrong.
