### ISSUE TITLE
iosxr_interface missing DI content, neighbors

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#34711]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
iosxr_interface

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The iosxr_interface needs feature parity with the eos_interface module.  Specifically we are missing the neighbors parameter->
```yml
  neighbors:
    description:
      - Check the operational state of given interface C(name) for LLDP neighbor.
      - The following suboptions are available.
    suboptions:
        host:
          description:
            - "LLDP neighbor host for given interface C(name)."
        port:
          description:
            - "LLDP neighbor port to which given interface C(name) is connected."
```

and we are also missing tx_rate and rx_rate
```yml 
  tx_rate:
    description:
      - Transmit rate in bits per second (bps) for the interface given in C(name) option.
  rx_rate:
    description:
      - Receiver rate in bits per second (bps) for the interface given in C(name) option.
```

an example eos playbook:
```yml
---
- hosts: eos
  connection: network_cli
  remote_user: admin
  become: yes
  become_method: enable
  vars:
    ansible_network_os: "eos"
  tasks:
    - eos_interface:
        name: ethernet1
        enabled: False
        tx_rate: 100
        neighbors:
         - port: eth0
           host: netdev
```

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A feature parity request 

##### ACTUAL RESULTS
N/A
