### ISSUE TITLE
shell: async & poll break removes condition

### ISSUE THREAD

**Issue by DSpeichert** [ansible/ansible#34720]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
shell

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = ['/Users/d/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/d/code/upgrades/venv/lib/python3.6/site-packages/ansible
  executable location = /Users/d/code/upgrades/venv/bin/ansible
  python version = 3.6.4 (default, Dec 25 2017, 14:57:56) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
```
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/d/.vault_password
```

##### OS / ENVIRONMENT
OSX 10.13.2 (17C205) with Python 3 from Homebrew

##### SUMMARY
shell module ignores `removes` arg when `sync: 1` AND `poll: 0`.

##### STEPS TO REPRODUCE
This doesn't work:
```yaml
    - name: Reboot server if necessary
      shell: sleep 2 && shutdown -r now "Rebooting because of updated packages"
      args:
        removes: /var/run/reboot-required
      async: 1
      poll: 0
      register: reboot
      when: allow_reboot
```

Commenting out other `async` or `poll` line makes it skip the command execution. Obviously it breaks the task when the reboot is actually executed.

##### EXPECTED RESULTS
Fire & forget should not unconditionally force shell command to be executed. Status should be `ok`.

##### ACTUAL RESULTS
The command is always executed even when file specified in `removes` doesn't exist. Status is `changed`.

```
TASK [Reboot server if necessary] *****************************************************************
changed: [ostest.local]
```
