### ISSUE TITLE
AWS direct connect modules are unable to create direct connect resources when 'ec2_url' is specified.

### ISSUE THREAD

**Issue by Madhura-CSI** [ansible/ansible#34732]
AWS Direct Connect modules cannot create required resources like direct connect connection or gateway when 'ec2_url' parameter is specified in a playbook run.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
aws_direct_connect_connection
aws_direct_connect_gateway
aws_direct_connect_link_aggregation_group

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos-dev/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT
Centos 7.4

##### SUMMARY
Above mentioned AWS direct connect modules have issue when ec2 endpoint url gets specified in ansible playbook run. The module fails to create AWS direct connect resource and throws 'DirectConnectError'.

##### STEPS TO REPRODUCE
1. Have task to create a VPC in playbook where EC2_URL environment variable is specified.
2. Include task to create direct connect playbook in same playbook. Following is the sample playbook.

```yaml
---
- hosts: localhost
  tasks:
    - ec2_vpc_net:
        state: present
        cidr_block: "10.107.0.0/16"
        name: testvpc
    - name: dc create
      aws_direct_connect_connection:
        name: madhuradc1
        state: present
        location: SFY52
        bandwidth: 1Gbps
  environment:
    EC2_URL: "https://ec2.ap-south-1.amazonaws.com"
  connection: local
```

##### EXPECTED RESULTS
VPC and direct connect connection both should get created successfully.

##### ACTUAL RESULTS
VPC creation is successful but direct connect connection is not created. Error is as below.

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_esgsXG/ansible_module_aws_direct_connect_connection.py", line 304, in <module>
    main()
  File "/tmp/ansible_esgsXG/ansible_module_aws_direct_connect_connection.py", line 274, in main
    connection_name=module.params.get('name'))
  File "/tmp/ansible_esgsXG/ansible_modlib.zip/ansible/module_utils/cloud.py", line 153, in retry_func
ansible.module_utils.aws.direct_connect.DirectConnectError

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_esgsXG/ansible_module_aws_direct_connect_connection.py\", line 304, in <module>\n    main()\n  File \"/tmp/ansible_esgsXG/ansible_module_aws_direct_connect_connection.py\", line 274, in main\n    connection_name=module.params.get('name'))\n  File \"/tmp/ansible_esgsXG/ansible_modlib.zip/ansible/module_utils/cloud.py\", line 153, in retry_func\nansible.module_utils.aws.direct_connect.DirectConnectError\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}

```

This happens due to the following lines of code in aws_direct_connect modules.
```
connection = boto3_conn(module, conn_type='client',
                            resource='directconnect', region=region,
                            endpoint=ec2_url, **aws_connect_kwargs)
```
In general, ec2_url is used as endpoint URL for boto3 ec2 clients. Hence, modules referring to ec2 clients will function correctly. But same is not the case with direct connect. Direct connect url is in format 'directconnect.region-name.amazonaws.com' which is not handled in boto3_conn and in botocore.

Hence, the above lines should be changed to:
```
connection = boto3_conn(module, conn_type='client',
                            resource='directconnect', region=region,
                            **aws_connect_kwargs)
```
This will work in all the cases. i.e. with and without ec2_url.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/aws_direct_connect_connection.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_direct_connect_connection.py)
* [lib/ansible/modules/cloud/amazon/aws_direct_connect_gateway.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_direct_connect_gateway.py)
* [lib/ansible/modules/cloud/amazon/aws_direct_connect_link_aggregation_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_direct_connect_link_aggregation_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @s-hertel @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by willthames** [comment]
What is the use case for using ec2_url with directconnect?

My understanding is that ec2_url allows people to use the ec2 modules with non-AWS services (euca etc) but my understanding might be incorrect or incomplete. I'm not sure we do any testing or have changed much to do with ec2_url in years and I thought it was a legacy parameter.

**Comment by Madhura-CSI** [comment]
Yes. ec2_url is legacy parameter and it can be avoided for standard AWS module calls. But since this is still allowed(as required by other non-AWS services), if we specify that explicitly and invoke 'aws_direct_connect*' modules, the endpoint_url becomes wrong in the below boto3_conn.
connection = boto3_conn(module, conn_type='client',
                            resource='directconnect', region=region,
                            **endpoint=ec2_url,** **aws_connect_kwargs)
So, this is a kind of minor bug or say endpoint parameter in boto3_conn is not required.
Hence, this call can be simply modified as below by removing endpoint parameter.
connection = boto3_conn(module, conn_type='client',
                            resource='directconnect', region=region,
                            **aws_connect_kwargs)

Please let me know if you have any further queries.

**Comment by s-hertel** [comment]
If you tried to run a s3 module with ec2_url set like above it would also fail because it isn't in the format `s3.region.amazonaws.com`. This is true for any other service really (see https://docs.aws.amazon.com/general/latest/gr/rande.html for all the varying endpoints by service), so I don't think removing ec2_url is a good option in case anyone else is using it.

Perhaps you can group your tasks and instantiate the right environment per service.
```
tasks:
  - name: ec2 resources
    environment:
      EC2_URL: "https://ec2.ap-south-1.amazonaws.com"
    block:
      - name: create vpc
        ec2_vpc_net:
          state: present
          cidr_block: "10.107.0.0/16"
          name: testvpc
  - name: directconnect resources
    block:
      - name: create directconnect connection
        aws_direct_connect_connection:
          name: madhuradc1
          state: present
          location: SFY52
          bandwidth: 1Gbps
```
