### ISSUE TITLE
vmware_guest module doesn't allow creation of vm under specific DataCenter folder & DataStore folder

### ISSUE THREAD

**Issue by dkirrane** [ansible/ansible#34746]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = //ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Apr 20 2017, 12:13:37) [GCC 6.3.0]
```

##### CONFIGURATION
```
CACHE_PLUGIN(//ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(//ansible.cfg) = /fact_cache
CACHE_PLUGIN_TIMEOUT(//ansible.cfg) = 86400
DEFAULT_CALLBACK_WHITELIST(//ansible.cfg) = ['profile_tasks']
DEFAULT_GATHERING(//ansible.cfg) = smart
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT
CentOS 7

##### SUMMARY
vmware_guest module doesn't allow creation of the VM under a datacenter folder and datastore folder

##### STEPS TO REPRODUCE

Settings folders in the module like below do not work for VM creation

```yaml
  vmware_guest:
:
          datacenter: "Europe"
          folder: "Europe/dev/joe"
          disk:
            - size_gb: 20
              type: thin
              datastore: "SANDatastore1"
              folder: "/dev/joe"
:
;
```

##### EXPECTED RESULTS
The VMs should appear under folders dev/joe on the Europe DataCenter
And the VM files show be created under the /dev/joe folder of the SANDatastore1 DataStore

##### ACTUAL RESULTS
Fails if DataCenter folder does not exist. If DataCenter folder exists it is ignored
DataStore folder is ingored. It's not a supported field at all.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@dkirrane Thanks for reporting this issue. 

You have specified 'folder' in disk section which is not a valid option. Could you please re-try after removing this option? also, could you please paste `-vvvv` output after failure?

needs_info

**Comment by dkirrane** [comment]
- I get the below error when I specify a Datacenter folder. I assumed vmware_guest would create the folder structure `/Europe/dev/joe` for me
- However, I also manually created the `/Europe/dev/joe` folder using vSphere Client and re-ran. But I get the same error.

```
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1516017073.7-231192548257636 `" && echo ansible-tmp-1516017073.7-231192548257636="` echo /root/.ansible/tmp/ansible-tmp-1516017073.7-231192548257636 `" ) && sleep 0'
<localhost> PUT /tmp/tmpIiGJ_r TO /root/.ansible/tmp/ansible-tmp-1516017073.7-231192548257636/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1516017073.7-231192548257636/ /root/.ansible/tmp/ansible-tmp-1516017073.7-231192548257636/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1516017073.7-231192548257636/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1516017073.7-231192548257636/" > /dev/null 2>&1 && sleep 0'
fatal: [master1 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": null,
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "Europe",
            "disk": [
                {
                    "datastore": "SANDatastore1",
                    "size_gb": 20,
                    "type": "thin"
                }
            ],
            "esxi_hostname": "10.123.45.6",
            "folder": "/Europe/dev/joe",
            "force": false,
            "guest_id": "centos64Guest",
            "hardware": {
                "memory_mb": 2048,
                "num_cpus": 2,
                "scsi": "paravirtual"
            },
            "hostname": "10.123.45.7",
            "is_template": false,
            "linked_clone": false,
            "name": "********-dev",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "dns_servers": [
                        "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                        "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                    ],
                    "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "gateway": "10.321.54.8",
                    "ip": "10.123.45.111",
                    "name": "Vlan Range 45.x",
                    "netmask": "255.255.255.0",
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "template_centos",
            "username": "root",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    },
    "msg": "No folder matched the path: /Europe/dev/joe"
```


The Ansible task:

```
- name: Create the VM
  vmware_guest:
          hostname: "{{ vCenter_host }}"
          username: "{{ vCenter_username }}"
          password: "{{ vCenter_password }}"
          name: "{{ inventory_hostname }}-{{ env }}"
          state: poweredon
          validate_certs: no
          guest_id: centos64Guest
          wait_for_ip_address: true
          template: "{{ template }}"
          esxi_hostname: "{{ esxi_host }}"
          datacenter: "{{ datacenter }}"
          folder: "{{ datacenter }}/dev/joe/"
          disk:
            - size_gb: 20
              type: thin
              datastore: "{{ datastore }}"
          hardware:
            memory_mb: 2048
            num_cpus: 2
            scsi: paravirtual
          networks:
            - name: "{{ vlan }}"
              device_type: vmxnet3
              type: static
              ip: "{{ ansible_host }}"
              netmask: "{{ netmask }}"
              gateway: "{{ gateway }}"
              dns_servers: "{{ dns_servers }}"
              domain: "{{ domain }}"
          customization:
            dns_servers: "{{ dns_servers }}"
            domain: "{{ domain }}"
            hostname: "{{ inventory_hostname }}"
  delegate_to: localhost
```
