### ISSUE TITLE
route53_zone ignores 'comment' parameter if zone already exists

### ISSUE THREAD

**Issue by danmoz** [ansible/ansible#34767]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
route53_zone

##### ANSIBLE VERSION

```
ansible 2.4.2.0
python version = 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/###/ansible.cfg) = True
DEFAULT_MODULE_LANG(/###/ansible.cfg) = en_US.UTF-8
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /###/.vault_password

##### OS / ENVIRONMENT

MacOS 10.13.2

##### SUMMARY
Ansible will only update the AWS zone comment with value of the route53_zone 'comment' parameter if the zone is being created. If the zone already exists, 'comment' is ignored and the task returns 'ok'

##### STEPS TO REPRODUCE
Run route53_zone against an existing AWS zone, where "comment" parameter differs from the current AWS zone comment.

##### EXPECTED RESULTS
AWS zone comment should be updated with the route53_zone comment parameter value passed

##### ACTUAL RESULTS
route53_zone comment parameter value is ignored.

Task to create a new zone:

```yaml
- route53_zone:
    zone: example.com
    comment: the new zone will be created with this comment
```
Zone is created, ansible returns
```
changed: [localhost]
```
Alter the comment parameter and re-run the task:
```yaml
- route53_zone:
    zone: example.com
    comment: foo bar baz
```
Task returns OK, AWS zone remains unchanged
```
ok: [localhost]
```
