### ISSUE TITLE
Create --from-tags options for ansible-playbook

### ISSUE THREAD

**Issue by saiterio** [ansible/ansible#34786]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ansible-playbook
lib/ansible/playbook/taggable.py
lib/ansible/playbook/play.py
lib/ansible/cli/playbook.py

##### ANSIBLE VERSION
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/damien/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
It could be useful to be able to start to run playbook from a specific tag

##### DETAILS

**With following playbook (myplaybook.yml):**
```
- hosts: developer
  gather_facts: no
  pre_tasks:
    - name: initialize ssh connection
      include_role:
        name: ssh
      tags: always
    - name: Gathering facts 
      setup:
      tags: always
    - name: cleanup
      include_role:
        name: cleanup
      tags: always
  
  post_tasks:
    - name: cleanup
      include_role:
        name: cleanup
      tags: always
    - name: Restart server
      include_role:
        name: common/restart
      tags: always
  roles:
    - {role: role1, tags: "first"}
    - {role: role2, tags: "second"}
    - {role: role3, tags: "third"}
    - {role: role4, tags: "fourth"}
```
**Command**
ansible-playbook -i my_inventory myplaybook.yml --from-tag "third"

##### EXPECTED RESULT
All the pre/post-tasks are executed, but only role 3 and role4 are executed.
