### ISSUE TITLE
ec2_asg module causes 'AssociatePublicIpAddress field can not be specified without a subnet id' error

### ISSUE THREAD

**Issue by sravan1265** [ansible/ansible#34794]
i am getting below error while creating sample auto scaling group.

TASK [Configure Auto Scaling Group] ********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (ValidationError) when calling the CreateAutoScalingGroup operation: AssociatePublicIpAddress field can not be specified without a subnet id
fatal: [ip address]: FAILED! => {"changed": false, "error": {"code": "ValidationError", "message": "AssociatePublicIpAddress field can not be specified without a subnet id", "type": "Sender"}, "msg": "Failed to create Autoscaling Group.", "response_metadata": {"http_headers": {"connection": "close", "content-length": "325", "content-type": "text/xml", "date": "Fri, 12 Jan 2018 10:45:54 GMT", "x-amzn-requestid": "c3cb979c-f785-11e7-ac00-c7ffa1d889e0"}, "http_status_code": 400, "request_id": "c3cb979c-f785-11e7-ac00-c7ffa1d889e0", "retry_attempts": 0}}

##### STEPS TO REPRODUCE

``` yaml
 ---
- name: spin up the load balancer and add the servers to it
  hosts: webserver
  connection: local
  gather_facts: False
  tasks:
    - name: setup a simple load balancer
      ec2_elb_lb:
        name: aws-blog-elb
        state: present
        region: ap-southeast-1
        zones:
          - ap-southeast-1a
        listeners:
          - protocol: http
            load_balancer_port: 80
            instance_port: 80
      register: aws-elb
    - name: create launch config
      ec2_lc:
        name: my_new_lc
        image_id: ami-84a6f3e7
        key_name: VCX Keypair
        region: ap-southeast-1
        security_groups: sg-173f0971
        instance_type: t2.micro
        assign_public_ip: yes
    - name: Configure Auto Scaling Group
      ec2_asg:
        name: myasg
        launch_config_name: my_new_lc
        availability_zones: ap-southeast-1a
        health_check_type: ELB
        health_check_period: 60
        min_size: 1
        max_size: 3
        desired_capacity: 2
        region: ap-southeast-1
        state: present
      register: asg_result
```
