### ISSUE TITLE
bigip_command show command

### ISSUE THREAD

**Issue by hemskgren** [ansible/ansible#34799]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

````
network module: bigip_command.py
```` 
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Oct 19 2015, 10:36:53) [GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]
```

##### CONFIGURATION

```
ACCELERATE_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 5.0
ACCELERATE_DAEMON_TIMEOUT(/etc/ansible/ansible.cfg) = 30
ACCELERATE_PORT(/etc/ansible/ansible.cfg) = 5099
ACCELERATE_TIMEOUT(/etc/ansible/ansible.cfg) = 30
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_LANG(/etc/ansible/ansible.cfg) = C
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible']
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = $HOME/.ansible/tmp
DEFAULT_SUDO_EXE(/etc/ansible/ansible.cfg) = sudo
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/etc/ansible/ansible.cfg) = False
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

```
centos
```
##### SUMMARY

```
show command shuld not display as changed.
```
##### STEPS TO REPRODUCE

```yaml

    - name: verify > show sys cluster | inc State enable and available
      bigip_command:
        commands:
          - show sys cluster
        wait_for:
          - result[0] contains 'Availability            available'
          - result[0] contains 'State                   enabled'
        server: "{{ inventory_hostname }}"
        user: "admin"
        password: "adminpwd"
        validate_certs: "no"
      delegate_to: localhost
```

##### EXPECTED RESULTS

```
TASK [verify > show sys cluster | inc State enable and available] **********************************************************************************************
ok: [p0-lb03-guest01.local -> localhost]
ok: [p0-lb04-guest01.local -> localhost]
```
##### ACTUAL RESULTS

```
TASK [verify > show sys cluster | inc State enable and available] **********************************************************************************************
changed: [p0-lb03-guest01.local -> localhost]
changed: [p0-lb04-guest01.local -> localhost]
```
