### ISSUE TITLE
vmware_guest ignores 'cluster' option when creating VM

### ISSUE THREAD

**Issue by balonik** [ansible/ansible#34801]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.1.0
```

##### OS / ENVIRONMENT
VMware vCenter environment:
1 Datacenter 'DC'
2 Host clusters under that DC called 'clusterA' and 'clusterB'
1 ESXi 6.0U3 host under each cluster (2 total)
There are some VMs running on clusterA-ESX.
clusterB-ESX is empty.

##### SUMMARY
While using vmware_guest to create new VM the option 'cluster' is ignored.

##### STEPS TO REPRODUCE
Build the VMware environment described above.

```yaml
...
- tasks:
 - name: Create VM from template
     vmware_guest:
       hostname: vcenter
       username: username
       password: password
       validate_certs: no
       datacenter: DC
       folder: DC/vm/"
       name: some_linux
       state: poweredon
       template: some_template
       cluster: "clusterA"
     register: deploy
     delegate_to: localhost
```

##### EXPECTED RESULTS
VM gets created on clusterA-ESX.

##### ACTUAL RESULTS
VM gets always created on clusterB-ESX (propably, because it has more free resources?)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@balonik Thanks for reporting issue.

**Comment by Akasurde** [comment]
You have specified `cluster` value as "clusterA", try using "clusterB" as `cluster` value. 

needs_info

**Comment by coltsixshooter** [comment]
in the function deploy_vm change this line

if self.params['esxi_hostname']

to this line

 if self.params['esxi_hostname'] or self.params['cluster']:

Which seems to fix the problem.

Problem is still in version 2.5.0

**Comment by ansibot** [comment]
cc @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kirikae** [comment]
I have also come across this issue.

Attempting to deploy a number of VMs into different Clusters within a single DataCenter:

Rough heirarchy of vCenter as follows:

```
vCenter 6.5.11000
ESXi 6.5.0, 5969303
DC┐
     ├ CLUSTER-10
     │     ├ CL-ESX-11
     │     ├ CL-ESX-12
     │     └ CL-ESX-13
     ├ CLUSTER-20
     │     ├ CL-ESX-21
     │     ├ CL-ESX-22
     │     └ CL-ESX-23
     └ CLUSTER-30
            ├ CL-ESX-31
            ├ CL-ESX-32
            └ CL-ESX-33
```
Ansible version 2.4.2.0
RHEL 7.3

I have a playbook as follows:
```yaml
---
- name: Deploy VM's
  hosts: group-vms-to-deploy
  gather_facts: false

  tasks:
  - name: Create VM on {{ vcenter_cluster }}
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vault.vcenter_password }}"
      validate_certs: no
      cluster: CLUSTER-02
      datacenter: DC
      folder: "{{ vcenter_datacenter + '/vm/' + folder }}"
      name: "{{ inventory_hostname }}"
      state: poweredon
      guest_id: "{{ guest_id }}"
      template: "{{ template + guest_id }}"
      disk:
      - size_gb: "{{ vm.disk.size }}"
        type: "{{ vm.disk.type }}"
        datastore: "{{ cluster_datastore }}"
      networks:
      - name: DPG-CL02-NET01
        ip: "{{ ansible_host }}"
        netmask: "{{ vm.net.mask }}"
        gateway: "{{ vm.net.gateway }}"
      hardware:
        memory_mb: "{{ vm.hardware.mem }}"
        num_cpus: "{{ vm.hardware.cpus }}"
      customization:
        hostname: "{{ guest_hostname }}"
    delegate_to: localhost
```

This works on any of my environments when deploying directly to an ESXi Host instead of to a Cluster. It also works whenever I deploy to a vCenter Datacenter with a single Cluster. However in my above setup, with multiple clusters, the deployment fails under all but one circumstance.

If I have a Datastore shared amoungst ALL the Clusters in the Datacenter, and tell the VM to deploy to that Datastore, the VM gets deployed to CLUSTER-01, even when it is directed to be deployed on CLUSTER-03 or CLUSTER-03.

If the the VM is directed to deploy onto CLUSTER-02 or CLUSTER-03's Datastore, not the shared Datastore, then the VM fails with the following msg:
`MSG: Unable to access the virtual machine configuration: Unable to access file [CLUSTER-02-Datastore]`

In following the suggestion above by @coltsixshooter, I have edited the following file `lib/ansible/modules/cloud/vmware/vmware_guest.py` which appears to resolve the issue and find the correct Cluster for deployment.

```python
# Specifically edited line 1173, the section now looks as follows:
def get_resource_pool(self):
    resource_pool = None
    if self.params['esxi_hostname'] or self.params['cluster']:
        host = self.select_host()
        resource_pool = self.select_resource_pool_by_host(host)
    else:
        resource_pool = self.select_resource_pool_by_name(self.params['resource_pool'])
    if resource_pool is None:
        self.module.fail_json(msg='Unable to find resource pool "%(resource_pool)s"' % self.params)
    return resource_pool
```
