### ISSUE TITLE
Juniper unable to open shell

### ISSUE THREAD

**Issue by Zalek-Git** [ansible/ansible#34812]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
junos_config

##### ANSIBLE VERSION
2.3.1

##### OS / ENVIRONMENT
Ubuntu
JunOS

##### SUMMARY
When I try to edit Juniper SRX300, I get unable to connect to shell problem. I had no problem with junos_get_facts module, but junos_config module is unable to connect to shell

##### STEPS TO REPRODUCE
```yaml
---
- name: get facts
  hosts: all
  connection: local
  gather_facts: no
  vars_prompt:
    - name: passwd
      prompt: "Password"
 
  vars:
    credential: 
      host: "{{ inventory_hostname }}"
      username: ozzy
      password: Password
      timeout: 30

  roles:
    - /etc/ansible/roles/Juniper.junos
  tasks:
    - name: Checking NETCONF connectivity
      wait_for: host={{ inventory_hostname }} port=830  timeout=5
      
    - name: gather facts
      junos_get_facts: host={{ inventory_hostname }} passwd={{ passwd }}
      register: junos
      
    - name: return version
      debug: msg="{{ junos.facts.version }}"
      
    - name: Configure device
      junos_config:
        prodiver: "{{ credential }}"
        lines: 
          - set interfaces ge-0/0/0 description Ansible-TEST
          - set interfaces ge-0/0/1 description Ansible-TEST
        comment: Update config
```

##### EXPECTED RESULTS
The playbook to configure my interfaces

##### ACTUAL RESULTS
```
TASK [Checking NETCONF connectivity] *******************************************************************************
task path: /home/ozzy/automation/Ansible/junos_playbook-1.yaml:20
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/utilities/logic/wait_for.py
<srx300-1> ESTABLISH LOCAL CONNECTION FOR USER: ozzy
<srx300-1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<srx300-1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ozzy/.ansible/tmp/ansible-tmp-1515776980.51-63965219858833 `" && echo ansible-tmp-1515776980.51-63965219858833="` echo /home/ozzy/.ansible/tmp/ansible-tmp-1515776980.51-63965219858833 `" ) && sleep 0'
<srx300-1> PUT /tmp/tmpKM3GYt TO /home/ozzy/.ansible/tmp/ansible-tmp-1515776980.51-63965219858833/wait_for.py
<srx300-1> EXEC /bin/sh -c 'chmod u+x /home/ozzy/.ansible/tmp/ansible-tmp-1515776980.51-63965219858833/ /home/ozzy/.ansible/tmp/ansible-tmp-1515776980.51-63965219858833/wait_for.py && sleep 0'
<srx300-1> EXEC /bin/sh -c '/usr/bin/python /home/ozzy/.ansible/tmp/ansible-tmp-1515776980.51-63965219858833/wait_for.py; rm -rf "/home/ozzy/.ansible/tmp/ansible-tmp-1515776980.51-63965219858833/" > /dev/null 2>&1 && sleep 0'
ok: [srx300-1] => {
    "changed": false, 
    "elapsed": 0, 
    "invocation": {
        "module_args": {
            "active_connection_states": [
                "ESTABLISHED", 
                "SYN_SENT", 
                "SYN_RECV", 
                "FIN_WAIT1", 
                "FIN_WAIT2", 
                "TIME_WAIT"
            ], 
            "connect_timeout": 5, 
            "delay": 0, 
            "exclude_hosts": null, 
            "host": "srx300-1", 
            "path": null, 
            "port": 830, 
            "search_regex": null, 
            "sleep": 1, 
            "state": "started", 
            "timeout": 5
        }
    }, 
    "path": null, 
    "port": 830, 
    "search_regex": null, 
    "state": "started"
}

TASK [Configure device] ********************************************************************************************
task path: /home/ozzy/automation/Ansible/junos_playbook-1.yaml:30
<srx300-1> using connection plugin netconf
<srx300-1> socket_path: /home/ozzy/.ansible/pc/d81fd8ccba
open_session() returned 255  failed to connect to control socket
fatal: [srx300-1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell", 
    "rc": 255
```
