### ISSUE TITLE
apt_repository does not add a second repository where add-apt-repository does

### ISSUE THREAD

**Issue by absoludity** [ansible/ansible#3484]
If I do the following:

```
$ add-apt-repository 'deb http://example.com/ubuntu precise main'
$ add-apt-repository 'deb http://example.com/ubuntu precise-updates main'

```

I'll see the following in the sources.list:

```
deb http://example.com/ubuntu precise main 
deb-src http://example.com/ubuntu precise main 
deb http://example.com/ubuntu precise-staging main 
deb-src http://example.com/ubuntu precise-staging main
```

Yet, if I apply the following playbook:

``` yaml
# Setup dependencies

---
- hosts: localhost
  user: root

  tasks:
    - apt_repository: repo='deb http://example.com/ubuntu precise main'
    - apt_repository: repo='deb http://example.com/ubuntu precise-updates main'                                                  
```

then only the first deb-line is added. The output shows that ansible determines (in ...) that the second one already exists based on the url onl:

```
PLAY [localhost] ************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [localhost]

TASK: [apt_repository repo='deb http://example.com/ubuntu precise main'] ****** 
changed: [localhost]

TASK: [apt_repository repo='deb http://example.com/ubuntu precise-updates main'] *** 
ok: [localhost]

PLAY RECAP ******************************************************************** 
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

Looking at packaging/apt_repository:repo_exists seems to confirm that it's only checking the url of the debline.
