### ISSUE TITLE
docker_network does not support ipv6 networks

### ISSUE THREAD

**Issue by smueller18** [ansible/ansible#34855]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
docker_network

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/sm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0]
```

##### SUMMARY
The docker_network module does not support defining an ipv6 network. There is no `enable_ipv6` parameter. Furthermore, a new strategy must be chosen to allow defining custom ipv4 and ipv6 options.
At the moment an ipv6 subnet could be defined with
```yml
- name: Create ipv6 network
  docker_network:
    name: ipv6
    ipam_options:
      subnet: 'a:b:c:d::/80'
```
but without setting `enable_ipv6`, containers don't get an ipv6 address. Furthermore, if the task definition does not change on further runs, the task outputs that the network changed, because it does not expect an ipv6 subnet.

To implement ipv6 network definitions, two changes are required.
First, a parameter to enable ipv6 must be introduced. Maybe with the name `enable_ipv6` which is not required and defaults to no.
Second, the `ipam_options` directive must be extended to allow multiple config entries. I would suggest a list:
```yml
- name: Create ipv6 network
  docker_network:
    name: ipv6
    enable_ipv6: yes
    ipam_options:
      - subnet: '172.3.26.0/16'
        gateway: 172.3.26.1
      - subnet: 'a:b:c:d::/80'
```
