### ISSUE TITLE
When selecting groups, subgroups from other groups with matching group names get incorporated

### ISSUE THREAD

**Issue by wfaulk** [ansible/ansible#34898]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

inventory

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/wfaulk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

none; default config

##### OS / ENVIRONMENT

running from MacOS 10.12.6
managing: N/A

##### SUMMARY

If you have groups with subgroups, and select one of the upper-level groups, hosts from within the other upper-level groups that are within subgroups that have the same name as the subgroups from within the selected upper-level group get incorporated into the selected hosts.

##### STEPS TO REPRODUCE

Run `ansible groupa --list-hosts` against this inventory file:

```yaml
all:
  children:
    groupa:
      children:
        subgroupa:
          hosts:
            hosta:
    groupb:
      children:
        subgroupa:
          hosts:
            hostb:
        subgroupb:
          hosts:
            hostc:
          children:
            subgroupa:
              hosts:
                hostd:
```

##### EXPECTED RESULTS

```
  hosts (1):
    hosta
```

##### ACTUAL RESULTS

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/wfaulk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
No config file found; using defaults
setting up inventory plugins
Parsed <redacted>/j.yml inventory source with yaml plugin
  hosts (3):
    hosta
    hostb
    hostd
```
