### ISSUE TITLE
eos_vlan and eos_vrf modules not idempotent if interface parameter is given as input

### ISSUE THREAD

**Issue by ganeshrn** [ansible/ansible#34917]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

eos_vlan
eos_vrf

##### ANSIBLE VERSION

```
2.4
```

##### STEPS TO REPRODUCE

```yaml
- name: Manage interface
  eos_vlan:
    vlan_id: 30
    name: vlan:30
    interfaces:
    - Ethernet 2
```

##### EXPECTED RESULTS

Ansible run should be successful

##### ACTUAL RESULTS

Fails with error

```
fatal: [veos01]: FAILED! => {
	<—snip—>
    },
    "msg": "Interface Ethernet 2 not configured on vlan 30"
}

```
