### ISSUE TITLE
Ansible ansible_group_priority variable is not passed down to child groups

### ISSUE THREAD

**Issue by boxrick** [ansible/ansible#34949]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Inventory

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/rickb/ansible-mist-old/ansible.cfg
  configured module search path = [u'/home/rickb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609
```

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/home/rickb/ansible-mist-old/ansible.cfg) = ['profile_tasks']
DEFAULT_CONNECTION_PLUGIN_PATH(/home/rickb/ansible-mist-old/ansible.cfg) = [u'/home/rickb/ansible-mist-old/plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/home/rickb/ansible-mist-old/ansible.cfg) = [u'/home/rickb/ansible-mist-old/plugins/filter']
DEFAULT_FORCE_HANDLERS(/home/rickb/ansible-mist-old/ansible.cfg) = True
DEFAULT_HASH_BEHAVIOUR(/home/rickb/ansible-mist-old/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/rickb/ansible-mist-old/ansible.cfg) = [u'/home/rickb/ansible-mist-old/inventory/deploy.mist']
DEFAULT_ROLES_PATH(/home/rickb/ansible-mist-old/ansible.cfg) = [u'/home/rickb/ansible-mist-old/roles-dev', u'/home/rickb/ansible-mist-old/roles', u'/home/rickb/ansible-mist-old/base-roles']
DEFAULT_STRATEGY_PLUGIN_PATH(/home/rickb/ansible-mist-old/ansible.cfg) = [u'/home/rickb/ansible-mist-old/plugins/strategy']
HOST_KEY_CHECKING(/home/rickb/ansible-mist-old/ansible.cfg) = False
INVENTORY_UNPARSED_IS_FAILED(/home/rickb/ansible-mist-old/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/rickb/ansible-mist-old/ansible.cfg) = False
```
##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

When using ansible_group_priority in inventory file, it is not passed down from group to child group

##### STEPS TO REPRODUCE

```yaml
---
all:
  hosts:
    mist0.deploy:
      ansible_host: 10.0.128.13
    mist1.deploy:
      ansible_host: 10.0.128.14

  children:
  # All top level groups

    networking:
      children:
        networking_container-hosts:
          hosts:
            mist[0:1].deploy:
      vars:
        ansible_group_priority: 5

    hardware:
      children:
        hardware_SYS-5039MS-H8TRF:
          hosts:
            mist[0:1].deploy:
      vars:
        ansible_group_priority: 10
```

##### RESULTS
`ansible_group_priority` is set to higher, which should mean that `hardware_SYS-5039MS-H8TRF` runs after `networking_container-hosts`. Instead this is ignored unless explicitly set at the actual group level.
