### ISSUE TITLE
win_dns_client fails when specifying an empty list of addresses

### ISSUE THREAD

**Issue by steaksauce-** [ansible/ansible#34956]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_dns_client

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

Default configuration (config dump returns nothing)

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core)

##### SUMMARY

When running the win_dns_client example to configure all adapters whose names begin with Ethernet to use DHCP-assigned DNS values, I get an error, resulting in a module failure.

##### STEPS TO REPRODUCE

- Create and run a playbook file with the following:
```
---
- name: Configure DNS to pull from DHCP
  hosts: windows
  tasks:
    - win_dns_client:
        adapter_names: "Ethernet*"
        ipv4_addresses: []
```
Please note, the above task is an example from [the documentation](http://docs.ansible.com/ansible/latest/win_dns_client_module.html#examples)

```
---
- name: Configure DNS to pull from DHCP
  hosts: windows
  tasks:
    - win_dns_client:
        adapter_names: "Ethernet*"
        ipv4_addresses: []
```

##### EXPECTED RESULTS

Per the documentation, I would expect the above to set the adapter to use DHCP values for DNS, or disable DNS lookup on static connections.

##### ACTUAL RESULTS

```
TASK [win_dns_client] ***********************************************************************************************************************************************************************************************************************
task path: /root/playbooks/win-dhcp.yml:9
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_dns_client.ps1
<10.2.1.80> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 10.2.1.80
EXEC (via pipeline wrapper)
fatal: [10.2.1.80]: FAILED! => {
    "changed": false,
    "module_stderr": "An error occurred while creating the pipeline.\r\n    + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : RuntimeException\r\n \r\nCompare-Object : Cannot bind argument to parameter 'DifferenceObject' because it is null.\r\nAt line:143 char:54\r\n+ ...  $v4_match = @(Compare-Object $current_dns_v4 $ipv4_addresses).Count  ...\r\n+                                                   ~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : InvalidData: (:) [Compare-Object], ParentContainsErrorRecordException\r\n    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.CompareObje \r\n   ctCommand\r\n \r\n\r\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
        to retry, use: --limit @/root/playbooks/win-dhcp.retry

```
