### ISSUE TITLE
Unable to use retries in uri_module 

### ISSUE THREAD

**Issue by kachkaev** [ansible/ansible#34989]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
uri module

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

`"ansible-config dump --only-changed` -> empty

##### OS / ENVIRONMENT

macos <-> any web server

##### SUMMARY

I'm checking if one of my playbooks is successful by crawling the status code of a webpage:

```yaml
    - name: Wait for HTTP 200 or 401
      command: curl --head --silent https://example.com/
      register: result
      until: result.stdout.find("200 OK") != -1 or result.stdout.find("401 Unauthorized") != -1
      retries: 30
      delay: 5
      changed_when: false
```

This has been working well for a while, however, I've started seeing a warning since recently:
```
[WARNING]: Consider using get_url or uri module rather than running curl
```

Unfortunately, none of my attempts to switch to `uri` module have been successful. Here are the examples of what I've been trying, but with no luck:

```yaml
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://example.com/
      retries: 30
      delay: 5
      register: result
      until: result.status == 200 or result.status == 401
      changed_when: false
```
```yaml
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://example.com/
        status_code: 200,401
      retries: 30
      delay: 5
      changed_when: false
```

##### STEPS TO REPRODUCE

Run the above tasks against a resource that does not return the expected status code.

##### EXPECTED RESULTS

Something like:

```
FAILED - RETRYING: Wait for HTTP 200 or 401 (42 retries left).
FAILED - RETRYING: Wait for HTTP 200 or 401 (41 retries left).
FAILED - RETRYING: Wait for HTTP 200 or 401 (40 retries left).
...
TASK FAILED / SUCCESS
```

##### ACTUAL RESULTS

When the returned status code does not match uri's `status_code` option (200 by default), the task fails despite that there are `retries` defined. The error output contains `"msg"="Status code was not [200, 401]: Not Found (unknown bytes)"` (it depends on what status code was returned by the server, 404 in this case).

How can `uri_module` be used to check the server's status code, e.g. after a redeploy? If there is already a way of achieving what I'm up and I'm just misusing this module, it'd be great to see a new example in the docs.

---
PS: Starting this issue after https://github.com/ansible/ansible/issues/28078#issuecomment-358095643

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/uri.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/uri.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @romeotheriault
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
What specific error are you getting when it isn't working?  Seeing a playbook run with at least `-v` would help, if not a higher verbosity.

needs_info

**Comment by kachkaev** [comment]
Here's the output for this specific task:

```yaml
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://google.com/404
        status_code: 200,401
      retries: 30
      delay: 5
      changed_when: false
```

```
fatal: [my-server]: FAILED! => {"alt_svc": "hq=\":443\"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic
=\":443\"; ma=2592000; v=\"41,39,38,37,35\"", "changed": false, "connection": "close", "content": "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <met
a name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}
html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}
* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-
decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.go
ogle.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:u
rl(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/
googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/go
oglelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href
=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <ins>That’s an error.</ins>\n  <p>The requested URL <code>/404</code> was not fou
nd on this server.  <ins>That’s all we know.</ins>\n", "content_length": "1564", "content_type": "text/html; charset=UTF-8", "date": "Wed, 17 Jan 2018 15:41:11 GM
T", "msg": "Status code was not [200, 401]: HTTP Error 404: Not Found", "redirected": false, "referrer_policy": "no-referrer", "status": 404, "url": "https://goog
le.com/404"}
```

Same for `-v` and `-vv`. And here's what I see when adding `-vvv`:

```

TASK [Wait for HTTP 200 or 401] **********************************************************************************************************************************
task path: /path/to/task.yaml:93
Using module file /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible/modules/net_tools/basics/uri.py
<my-server> ESTABLISH SSH CONNECTION FOR USER: None
<my-server> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with
-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/me/.ansible/cp/fc476702f3 my-server '
/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<my-server> (0, '/root\n', '')
<my-server> ESTABLISH SSH CONNECTION FOR USER: None
<my-server> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with
-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/me/.ansible/cp/fc476702f3 my-server '
/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1516203858.86-48996515290261 `" && echo ansible-tmp-1516203858.86-48996515290261="` echo /tmp/ansi
ble-tmp-1516203858.86-48996515290261 `" ) && sleep 0'"'"''
<my-server> (0, 'ansible-tmp-1516203858.86-48996515290261=/tmp/ansible-tmp-1516203858.86-48996515290261\n', '')
<my-server> PUT /var/folders/vp/cg66j_sj5_ncxlgvgt7pjn2h0000gn/T/tmpRor9_N TO /tmp/ansible-tmp-1516203858.86-48996515290261/uri.py
<my-server> SSH: EXEC sftp -b - -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssap
i-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/me/.ansible/cp/fc476702f3 '[my-server]'
<my-server> (0, 'sftp> put /var/folders/vp/cg66j_sj5_ncxlgvgt7pjn2h0000gn/T/tmpRor9_N /tmp/ansible-tmp-1516203858.86-48996515290261/uri.py\n', '')
<my-server> ESTABLISH SSH CONNECTION FOR USER: None
<my-server> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with
-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/me/.ansible/cp/fc476702f3 my-server '
/bin/sh -c '"'"'setfacl -m u:me:r-x /tmp/ansible-tmp-1516203858.86-48996515290261/ /tmp/ansible-tmp-1516203858.86-48996515290261/uri.py && sleep 0'"'"''
<my-server> (127, '', '/bin/sh: 1: setfacl: not found\n')
<my-server> ESTABLISH SSH CONNECTION FOR USER: None
<my-server> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with
-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/me/.ansible/cp/fc476702f3 my-server '
/bin/sh -c '"'"'chmod u+x /tmp/ansible-tmp-1516203858.86-48996515290261/ /tmp/ansible-tmp-1516203858.86-48996515290261/uri.py && sleep 0'"'"''
<my-server> (0, '', '')
<my-server> ESTABLISH SSH CONNECTION FOR USER: None
<my-server> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with
-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/me/.ansible/cp/fc476702f3 my-server '
/bin/sh -c '"'"'chown me /tmp/ansible-tmp-1516203858.86-48996515290261/ /tmp/ansible-tmp-1516203858.86-48996515290261/uri.py && sleep 0'"'"''
<my-server> (0, '', '')
<my-server> ESTABLISH SSH CONNECTION FOR USER: None
<my-server> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with
-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/me/.ansible/cp/fc476702f3 -tt my-server '/bin/sh -c '"'"'sudo -H -S -n -u me /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-yizwnnryflmoymfamzdiuswleafbsumv; /usr/bin/python /tmp/ansible-tmp-151620
3858.86-48996515290261/uri.py'"'"'"'"'"'"'"'"' && sleep 0'"'"''
<my-server> (1, '\r\n{"status": 404, "content_length": "1564", "exception": "  File \\"/tmp/ansible_UQwiI4/ansible_module_uri.py\\", line 468, in m
ain\\n    uresp[\'location\'] = absolute_location(url, uresp[\'location\'])\\n", "referrer_policy": "no-referrer", "url": "https://google.com/404", "content": "<!
DOCTYPE html>\\n<html lang=en>\\n  <meta charset=utf-8>\\n  <meta name=viewport content=\\"initial-scale=1, minimum-scale=1, width=device-width\\">\\n  <title>Err
or 404 (Not Found)!!1</title>\\n  <style>\\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{m
argin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-
right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margi
n-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-
5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0%
 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pi
xel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo
{display:inline-block;height:54px;width:150px}\\n  </style>\\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\\n  <p><b>404.</b> <ins>That
\\u2019s an error.</ins>\\n  <p>The requested URL <code>/404</code> was not found on this server.  <ins>That\\u2019s all we know.</ins>\\n", "failed": true, "conn
ection": "close", "alt_svc": "hq=\\":443\\"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=\\":443\\"; ma=2592000; v=
\\"41,39,38,37,35\\"", "content_type": "text/html; charset=UTF-8", "invocation": {"module_args": {"directory_mode": null, "force": false, "remote_src": null, "sta
tus_code": ["200", "401"], "body_format": "raw", "owner": null, "follow": false, "client_key": null, "group": null, "use_proxy": true, "unsafe_writes": null, "set
ype": null, "content": null, "serole": null, "follow_redirects": "safe", "return_content": false, "method": "GET", "body": null, "timeout": 30, "src": null, "dest
": null, "selevel": null, "force_basic_auth": false, "removes": null, "http_agent": "ansible-httpget", "regexp": null, "url_password": null, "url": "https://googl
e.com/404", "validate_certs": true, "seuser": null, "client_cert": null, "creates": null, "headers": {}, "delimiter": null, "mode": null, "url_username": null, "a
ttributes": null, "backup": null}}, "date": "Wed, 17 Jan 2018 15:44:23 GMT", "redirected": false, "msg": "Status code was not [200, 401]: HTTP Error 404: Not Foun
d"}\r\n', 'Shared connection to 188.120.243.197 closed.\r\n')
<my-server> ESTABLISH SSH CONNECTION FOR USER: None
<my-server> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with
-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/me/.ansible/cp/fc476702f3 my-server '
/bin/sh -c '"'"'rm -f -r /tmp/ansible-tmp-1516203858.86-48996515290261/ > /dev/null 2>&1 && sleep 0'"'"''
<my-server> (0, '', '')
The full traceback is:
  File "/tmp/ansible_UQwiI4/ansible_module_uri.py", line 468, in main
    uresp['location'] = absolute_location(url, uresp['location'])

fatal: [my-server]: FAILED! => {
    "alt_svc": "hq=\":443\"; ma=2592000; quic=51303431; quic=51303339; quic=51303338; quic=51303337; quic=51303335,quic=\":443\"; ma=2592000; v=\"41,39,38,37,35\"
",
    "changed": false,
    "connection": "close",
    "content": "<!DOCTYPE html>\n<html lang=en>\n  <meta charset=utf-8>\n  <meta name=viewport content=\"initial-scale=1, minimum-scale=1, width=device-width\">\n
  <title>Error 404 (Not Found)!!1</title>\n  <style>\n    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:1
5px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repea
t;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:
none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;mar
gin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no
-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min
-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 1
00%}}#logo{display:inline-block;height:54px;width:150px}\n  </style>\n  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>\n  <p><b>404.</b> <i
ns>That’s an error.</ins>\n  <p>The requested URL <code>/404</code> was not found on this server.  <ins>That’s all we know.</ins>\n",
    "content_length": "1564",
    "content_type": "text/html; charset=UTF-8",
    "date": "Wed, 17 Jan 2018 15:44:23 GMT",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {},
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": false,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "200",
                "401"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "https://google.com/404",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "Status code was not [200, 401]: HTTP Error 404: Not Found",
    "redirected": false,
    "referrer_policy": "no-referrer",
    "status": 404,
    "url": "https://google.com/404"
}
        to retry, use: --limit @/path/to/task.retry
```

**Comment by sivel** [comment]
Per the documentation at http://docs.ansible.com/ansible/latest/playbooks_loops.html#do-until-loops you need to include `until`:

> Note:
> If the “until” parameter isn’t defined, the value for the “retries” parameter is forced to 1.

Which means that it will not retry at all.

Try using the following instead:

```
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://example.com/
        status_code: 200,401
      register: result
      until: result is not failed
      retries: 30
      delay: 5
      changed_when: false
```

needs_info

**Comment by kachkaev** [comment]
One of the options I tried above did contain `until`, but it still was not working perfectly:

```yaml
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://example.com/
      retries: 30
      delay: 5
      register: result
      until: result.status == 200 or result.status == 401
      changed_when: false
```
The problem occurred when the server was temporary unreachable, and I was thus getting a fatal error instead of seeing a retry:
```
FAILED! => {"msg": "The conditional check 'result.status == 200 or result.status == 401' failed. The error was: error while eva
luating conditional (result.status == 200 or result.status == 401): 'dict object' has no attribute 'status'"}
```

The solution ended up being this:
```yaml
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://some-unreachable-server.com/
      retries: 30
      delay: 5
      register: result
      until: ('status' in result) and (result.status == 200 or result.status == 401)
      changed_when: false
```

Turns out the module itself is OK, just the task setup is not straightforward. How about adding a couple of examples with `retries` to [`uri_module.html`](http://docs.ansible.com/ansible/latest/uri_module.html)?

**Comment by sivel** [comment]
Feel free to open a docs pull requests with additional examples.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by kachkaev** [comment]
Actually my working example above is not complete, one line is missing:

```yaml
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://example.com/
        status_code: 200,401 # <------------------------------------------- this one
      retries: 30
      delay: 5
      register: result
      until: ('status' in result) and (result.status == 200 or result.status == 401)
      changed_when: false
```

Because `status_code` option is 200 by default, the task fails when the 'right' status is not 200 and this is only mentioned in `until`. Turns out like too much stuff to write for such a small check IMO, especially given the fact that we need to mention the same status codes twice.

How about introducing something like `result.success = true / false` to make it possible to write just this?

```yaml
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://example.com/
        status_code: 200,401
      retries: 30
      delay: 5
      register: result
      until: result.success # <---------------------------------------- much shorter
      changed_when: false
```

In any case, it might be necessary to update the [Return values](http://docs.ansible.com/ansible/latest/uri_module.html#return-values) table in uri_module.html, because `status` is only returned when the server is reachable and not _always_ as this is stated. Checking `('status' in result)` would not be necessary otherwise.

**Comment by giovannisciortino** [comment]
@kachkaev I'm not sure if you have observed that there is already a variable failed in result dictionary. 

I report below an example of its use:
```
$ cat /tmp/uri_example.yml
- hosts: localhost
  tasks:
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://example.com/
        status_code: 200,401 
      retries: 30
      delay: 5
      register: result
      until: result.failed is defined
      changed_when: false

    - name: Wait for HTTP 200 or 401 
      uri:
        url: https://example.com/not_valid_url
        status_code: 200,401 # 
      retries: 30
      delay: 5
      register: result
      until: result.failed is defined
      changed_when: false
```

Does it fit your requirements? If yes, I'm agree with you that using it to increase the readability of the playbook and I don't think that adding a new return value "success" is useful.

**Comment by kachkaev** [comment]
Thanks for your response @giovannisciortino – that's what I've been looking for! The only minor bit to note is that there should be a `not` in `until`, i.e.: `until: result.failed is not defined`  🎉

**Comment by kachkaev** [comment]
@giovannisciortino  not sure why, but after upgrading to Ansible 2.5 (2.5.3), your trick is no longer working. Here's my task:

```yaml
    - name: Wait for HTTP 200 or 401
      uri:
        url: https://example.com/
        status_code: 200,401
      retries: 30
      delay: 5
      register: result
      until: result.failed is not defined
      changed_when: false
```

It Fails indefinitely until all retries are exhausted and the task failes.

```
...
FAILED - RETRYING: Wait for HTTP 200 or 401 (4 retries left).
FAILED - RETRYING: Wait for HTTP 200 or 401 (3 retries left).
FAILED - RETRYING: Wait for HTTP 200 or 401 (2 retries left).
FAILED - RETRYING: Wait for HTTP 200 or 401 (1 retries left).
fatal: [my-srv]: FAILED! => {"attempts": 10, "cache_control": "max-age=0, must-revalidate, private", "changed": false, "connection": "close", "content_type": "text/html; charset=UTF-8", "cookies": {"v": "1"}, "date": "Thu, 31 May 2018 11:58:22 GMT", "last_modified": "Thu, 08 Mar 2018 22:10:55 GMT", "msg": "OK (unknown bytes)", "redirected": false, "server": "nginx/1.10.3 (Ubuntu)", "set_cookie": "v=1; expires=Tue,01-Jan-2030 00:00:00 GMT; Max-Age=365688098; path=/", "status": 200, "transfer_encoding": "chunked", "url": "https://example.com/"}
```

What could break the behaviour?
