### ISSUE TITLE
nso_config fails to set leaf-list values

### ISSUE THREAD

**Issue by cnasten** [ansible/ansible#34985]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nso_config

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel f67f8c7bc9) last updated 2018/01/09 18:52:16 (GMT +200)
  config file = None
  configured module search path = [u'/home/cnasten/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cnasten/dev/ansible/lib/ansible
  executable location = /home/cnasten/dev/ansible/bin/ansible
  python version = 2.7.14+ (default, Dec  5 2017, 15:17:02) [GCC 7.2.0]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT
Debian GNU/Linux Buster controlling NSO 4.4.4

##### SUMMARY
Setting leaf-list values does not currently work with nso_config due to the handling of types.

##### STEPS TO REPRODUCE
Use the provided YAML together with the YANG below.

YAML:
```yaml
- name: Test leaf-list set
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Set leaf-list
    nso_config:
      url: "http://localhost:8080/jsonrpc"
      username: "username"
      password: "password"
      data:
        test:test:
          test:device-list:
            - one
            - two
```

YANG:
```yang
module test {
    namespace "urn:test";
    prefix test;

    container test {
        leaf-list device {
            type string;
        }
    }
}
```
##### EXPECTED RESULTS
The device leaf list should be set with the two elements one and two.

##### ACTUAL RESULTS
nso_config fails executing the Python code.
