### ISSUE TITLE
azure_rm_networkinterface and azure_rm_virtualmachine inconsistent "location" param

### ISSUE THREAD

**Issue by kwanlowe** [ansible/ansible#34992]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_networkinterface

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/home/108752/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/108752/bin/p27_venv/lib/python2.7/site-packages/ansible
  executable location = /home/108752/bin/p27_venv/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION

[defaults]
hostfile = inventory
become=True
become_user=root
deprecation_warnings=False
system_warnings=False
host_key_checking=False

##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7.4
##### SUMMARY

The "location" parameter between azure_rm_networkinterface and azure_rm_virtualmachine is inconsistent. 

azure_rm_networkinterface accepts:
   location: "East US 2"

azure_rm_virtualmachine accepts:
   location: "eastus2"

Using "East US 2" in azure_rm_virtualmachine returns an error about invalid characters.

##### STEPS TO REPRODUCE

```yaml

- name: Create NIC
  azure_rm_networkinterface:
    name: "vm-klltest01-nic"
    resource_group: "klltest-rg"
    virtual_network_name: "{{ virtual_network }}"
    location: "East US 2"
    subnet_name: "{{ private_subnet }}"
    security_group_name: "{{ security_group }}"
    public_ip: no

- name: Create virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group }}"
    name: "{{ machine_name }}"
    vm_size: Basic_A0
    admin_username: deploy
    ssh_password_enabled: false
    ssh_public_keys:
      - path: /home/deploy/.ssh/authorized_keys
        key_data: "{{ public_key }}"
    network_interfaces: "{{ machine_name }}-nic"
    location: "East US 2"
    image:
      offer: "CentOS"
      publisher: "OpenLogic"
      sku: "7.4"
      version: "latest"

```

##### EXPECTED RESULTS

Both azure_rm_networkinterface and azure_rm_virtualmachine should accept the same "location" format. Either use the short version or the long to be consistent.

##### ACTUAL RESULTS

```
(p27_venv)[108752@rhldakll075 baseline]$ ansible-playbook playbooks/ansible_feature.yml -e "machine_name=rhldaklltest902"

PLAY [Azure instance] ****************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Create NIC] ********************************************************************************************************************************************
changed: [localhost]

TASK [Create virtual machine] ********************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: msrest.exceptions.ValidationError: Parameter 'location' must conform to the following pattern: '^[-\\w\\._]+$'.
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_xePoUi/ansible_module_azure_rm_virtualmachine.py\", line 1554, in <module>\n    main()\n  File \"/tmp/ansible_xePoUi/ansible_module_azure_rm_virtualmachine.py\", line 1551, in main\n    AzureRMVirtualMachine()\n  File \"/tmp/ansible_xePoUi/ansible_module_azure_rm_virtualmachine.py\", line 651, in __init__\n    supports_check_mode=True)\n  File \"/tmp/ansible_xePoUi/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 285, in __init__\n  File \"/tmp/ansible_xePoUi/ansible_module_azure_rm_virtualmachine.py\", line 679, in exec_module\n    if self.vm_size and not self.vm_size_is_valid():\n  File \"/tmp/ansible_xePoUi/ansible_module_azure_rm_virtualmachine.py\", line 1368, in vm_size_is_valid\n    for size in sizes:\n  File \"/home/108752/bin/p27_venv/lib/python2.7/site-packages/msrest/paging.py\", line 109, in __next__\n    self.advance_page()\n  File \"/home/108752/bin/p27_venv/lib/python2.7/site-packages/msrest/paging.py\", line 95, in advance_page\n    self._response = self._get_next(self.next_link)\n  File \"/home/108752/bin/p27_venv/lib/python2.7/site-packages/azure/mgmt/compute/compute/v2017_03_30/operations/virtual_machine_sizes_operations.py\", line 63, in internal_paging\n    'location': self._serialize.url(\"location\", location, 'str', pattern=r'^[-\\w\\._]+$'),\n  File \"/home/108752/bin/p27_venv/lib/python2.7/site-packages/msrest/serialization.py\", line 487, in url\n    data = self.validate(data, name, required=True, **kwargs)\n  File \"/home/108752/bin/p27_venv/lib/python2.7/site-packages/msrest/serialization.py\", line 567, in validate\n    raise ValidationError(key, name, value)\nmsrest.exceptions.ValidationError: Parameter 'location' must conform to the following pattern: '^[-\\\\w\\\\._]+$'.\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
        to retry, use: --limit @/home/108752/src/ansible/baseline/playbooks/ansible_feature.retry

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1


```
