### ISSUE TITLE
vmware_guest Error : Unable to access the virtual machine configuration: Unable to access file 

### ISSUE THREAD

**Issue by SaranrajMG** [ansible/ansible#35012]
##### ISSUE TYPE
 - Bug Report
##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible
  executable location = /opt/rh/python27/root/usr/bin/ansible
  python version = 2.7.13 (default, Feb  8 2017, 06:30:30) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
[root@ansible user12]#
```

##### OS / ENVIRONMENT
RHEL6.8

##### STEPS TO REPRODUCE
Running the module vmware_guest to create a VM from a template gives the following error:
```
"msg": "Unable to access the virtual machine configuration: Unable to access file [LUN-NPRD-OS-08] 
```

I have the following setup in my environment.
1.  I have a Datacenter (ex: DC1) in my vCenter, under the data center there are 8 clusters. 
2.  Each Cluster has 8 Esxi hosts placed in them.
3.  I created a Template and I placed it in Cluster : last cluster(Host8)
4.  From this template, I am trying to create a VM into same cluster: " Host8 ".
5.  Out of 8 Cluster , i have restricted access to deploy vm in single cluster and its associated datastores.

I have tried manually deployed the vm using template and it worked, but when i tried from ansible it gives above error.
Im Specifying Cluster and Datastore Cluster details in "disk" option.

In github i have read some issue related to the same issue. But it couldnt help me.

```
---
- name: Create VMware guest
  hosts: localhost
  gather_facts: False

  vars_prompt:
    - name: "vcenter"
      prompt: "vCenter hostname?"
      private: no
      default: "winvcserver"
    - name: "user"
      prompt: "Enter username"
      private: no
    - name: "pass"
      prompt: "Enter password"
      private: yes
    - name: "template"
      prompt: "Template?"
      private: no
      default: "Linux-Test-Template"
    - name: "guest"
      prompt: "New VM HOstname?"
      private: no
    - name: "cluster"
      prompt: "Cluster?"
      private: no
      default: "Host8"

  tasks:
  - name: Deploy guest from template
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false
      cluster: "{{ cluster }}"
      datacenter: sDatacenter
      state: poweredon
      name: "{{ guest }}"
      template: "{{ template }}"
      folder: "LINAUTTST"
      disk:
       - size_gb: 64
         datastore: LUN-NPRD-OS-SCLU-08  <--- Datastore Cluster Name
         type: thick
         autoselect_datastore: yes
       - size_gb: 64
         datastore: LUN-NPRD-DATA-SCLU-08  <--- Datastore Cluster Name
         type: thick
         autoselect_datastore: yes
      hardware:
        memory_mb: 2048
        num_cpus: 1
      networks:
       - name: VLAN 3007 TST
         device_type: vmxnet3
         type: static
         ip: xxx.xxx.xxx.xxx
         netmask: xxx.xxx.xxx.xxx
         gateway: xxx.xxx.xxx.xxx
      customization:
         autologon: yes
         dns_servers:
           - xxx.xxx.xxx.xxx
           - xxx.xxx.xxx.xxx
         hostname: "{{ guest }}"
    delegate_to: localhost
```

##### EXPECTED RESULTS
It should Deploy a VM into the given location ( Folder and Cluster) without any issues.

##### ACTUAL RESULTS
```
fatal: [localhost -> localhost]: FAILED! => {
    "changed": true,
    "clone_method": "Clone",
    "clonespec": {
        "config": {
            "alternateGuestName": null,
            "annotation": null,
            "bootOptions": null,
            "changeTrackingEnabled": null,
            "changeVersion": null,
            "consolePreferences": null,
            "cpuAffinity": null,
            "cpuAllocation": null,
            "cpuFeatureMask": [],
            "cpuHotAddEnabled": true,
            "cpuHotRemoveEnabled": null,
            "crypto": null,
            "deviceChange": [
                {
                    "backing": null,
                    "device": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualVmxnet3'>",
                    "dynamicProperty": [],
                    "dynamicType": null,
                    "fileOperation": null,
                    "operation": "edit",
                    "profile": []
                }
            ],
            "dynamicProperty": [],
            "dynamicType": null,
            "extraConfig": [],
            "files": null,
            "firmware": null,
            "flags": null,
            "ftInfo": null,
            "guestAutoLockEnabled": null,
            "guestId": null,
            "instanceUuid": null,
            "latencySensitivity": null,
            "locationId": null,
            "managedBy": null,
            "maxMksConnections": null,
            "memoryAffinity": null,
            "memoryAllocation": null,
            "memoryHotAddEnabled": true,
            "memoryMB": 2048,
            "memoryReservationLockedToMax": null,
            "messageBusTunnelEnabled": null,
            "migrateEncryption": null,
            "name": null,
            "nestedHVEnabled": null,
            "networkShaper": null,
            "npivDesiredNodeWwns": null,
            "npivDesiredPortWwns": null,
            "npivNodeWorldWideName": [],
            "npivOnNonRdmDisks": null,
            "npivPortWorldWideName": [],
            "npivTemporaryDisabled": null,
            "npivWorldWideNameOp": null,
            "npivWorldWideNameType": null,
            "numCPUs": 1,
            "numCoresPerSocket": null,
            "powerOpInfo": null,
            "repConfig": null,
            "scheduledHardwareUpgradeInfo": null,
            "swapPlacement": null,
            "tools": null,
            "uuid": null,
            "vAppConfig": null,
            "vAppConfigRemoved": null,
            "vAssertsEnabled": null,
            "vPMCEnabled": null,
            "version": null,
            "virtualICH7MPresent": null,
            "virtualSMCPresent": null,
            "vmProfile": []
        },
        "customization": "<class 'pyVmomi.VmomiSupport.vim.vm.customization.Specification'>",
        "dynamicProperty": [],
        "dynamicType": null,
        "location": {
            "datastore": "'vim.Datastore:datastore-4125':LUN-NPRD-OS-08",   <-- Actual Datastore
            "deviceChange": [],
            "disk": [],
            "diskMoveType": null,
            "dynamicProperty": [],
            "dynamicType": null,
            "folder": null,
            "host": null,
            "pool": "'vim.ResourcePool:resgroup-8':Resources",
            "profile": [],
            "service": null,
            "transform": null
        },
        "memory": null,
        "powerOn": false,
        "snapshot": null,
        "template": false
    },
    "configspec": {
        "alternateGuestName": null,
        "annotation": null,
        "bootOptions": null,
        "changeTrackingEnabled": null,
        "changeVersion": null,
        "consolePreferences": null,
        "cpuAffinity": null,
        "cpuAllocation": null,
        "cpuFeatureMask": [],
        "cpuHotAddEnabled": true,
        "cpuHotRemoveEnabled": null,
        "crypto": null,
        "deviceChange": [
            {
                "backing": null,
                "device": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualVmxnet3'>",
                "dynamicProperty": [],
                "dynamicType": null,
                "fileOperation": null,
                "operation": "edit",
                "profile": []
            }
        ],
        "dynamicProperty": [],
        "dynamicType": null,
        "extraConfig": [],
        "files": null,
        "firmware": null,
        "flags": null,
        "ftInfo": null,
        "guestAutoLockEnabled": null,
        "guestId": null,
        "instanceUuid": null,
        "latencySensitivity": null,
        "locationId": null,
        "managedBy": null,
        "maxMksConnections": null,
        "memoryAffinity": null,
        "memoryAllocation": null,
        "memoryHotAddEnabled": true,
        "memoryMB": 2048,
        "memoryReservationLockedToMax": null,
        "messageBusTunnelEnabled": null,
        "migrateEncryption": null,
        "name": null,
        "nestedHVEnabled": null,
        "networkShaper": null,
        "npivDesiredNodeWwns": null,
        "npivDesiredPortWwns": null,
        "npivNodeWorldWideName": [],
        "npivOnNonRdmDisks": null,
        "npivPortWorldWideName": [],
        "npivTemporaryDisabled": null,
        "npivWorldWideNameOp": null,
        "npivWorldWideNameType": null,
        "numCPUs": 1,
        "numCoresPerSocket": null,
        "powerOpInfo": null,
        "repConfig": null,
        "scheduledHardwareUpgradeInfo": null,
        "swapPlacement": null,
        "tools": null,
        "uuid": null,
        "vAppConfig": null,
        "vAppConfigRemoved": null,
        "vAssertsEnabled": null,
        "vPMCEnabled": null,
        "version": null,
        "virtualICH7MPresent": null,
        "virtualSMCPresent": null,
        "vmProfile": []
    },
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "Host8",
            "customization": {
                "autologon": true,
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "sDatacenter",
            "disk": [
                {
                    "autoselect_datastore": true,
                    "datastore": "LUN-NPRD-OS-SCLU-08",
                    "size_gb": 64,
                    "type": "thick"
                },
                {
                    "autoselect_datastore": true,
                    "datastore": "LUN-NPRD-DATA-SCLU-08",
                    "size_gb": 64,
                    "type": "thick"
                }
            ],
            "esxi_hostname": null,
            "folder": "/LINAUTTST",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 2048,
                "num_cpus": 1
            },
            "hostname": "winvcserver.********",
            "is_template": false,
            "linked_clone": false,
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "gateway": "XXX.XXX.XXX.XXX",
                    "ip": "XXX.XXX.XXX.XXX",
                    "name": "VLAN 3007 TST",
                    "netmask": "XXX.XXX.XXX.XXX",
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "Linux-Test-Template",
            "username": "admin",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "Unable to access the virtual machine configuration: Unable to access file [LUN-NPRD-OS-08]"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@SaranrajMG Thanks for reporting this issue. I will try to reproduce this issue in my environment.

**Comment by SaranrajMG** [comment]
@Akasurde : Do you have any update on this? or if you required any details , please let me know.

**Comment by talhajilal** [comment]
I have same issue with my lab environment while i was trying to write sample playbook with vmware_guest module for vm creation automate playbook. 


My sample playbook , 
cat site.yml 
```
- name: sample playbook create new vm
  hosts: localhost
  gather_facts: no
  become: yes
  roles:
       - vmware
```
cat vmware/tasks/main.yml
```
- name: Create a VM from a template
  vmware_guest:
    hostname: x.x.x.x.x
    username: xxxx
    password: xxxx
    datacenter: datacenter
    validate_certs: no
    #folder: /folder
    name: testvm_2
    state: poweredon
    template: centos-7-template
    disk:
    - size_gb: 20
      type: thin
      datastore: datastore1
    hardware:
      memory_mb: 1024
      num_cpus: 1
      scsi: paravirtual
    networks:
    - name: VM Network
      ip: xxx.x.xx.xx
      netmask: 255.255.255.0
      #mac: aa:bb:dd:aa:00:20
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy
```

ansible-playbook site.yml


Error : 

```
fatal: [localhost -> localhost]: FAILED! => {"changed": true, "clone_method": "Clone", "clonespec": {"config": {"alternateGuestName": null, "annotation": null, "bootOptions": null, "changeTrackingEnabled": null, "changeVersion": null, "consolePreferences": null, "cpuAffinity": null, "cpuAllocation": null, "cpuFeatureMask": [], "cpuHotAddEnabled": "<type 'bool'>", "cpuHotRemoveEnabled": null, "crypto": null, "deviceChange": [], "dynamicProperty": [], "dynamicType": null, "extraConfig": [], "files": null, "firmware": null, "flags": null, "ftInfo": null, "guestAutoLockEnabled": null, "guestId": null, "instanceUuid": null, "latencySensitivity": null, "locationId": null, "managedBy": null, "maxMksConnections": null, "memoryAffinity": null, "memoryAllocation": null, "memoryHotAddEnabled": "<type 'bool'>", "memoryMB": "<type 'int'>", "memoryReservationLockedToMax": null, "messageBusTunnelEnabled": null, "migrateEncryption": null, "name": null, "nestedHVEnabled": null, "networkShaper": null, "npivDesiredNodeWwns": null, "npivDesiredPortWwns": null, "npivNodeWorldWideName": [], "npivOnNonRdmDisks": null, "npivPortWorldWideName": [], "npivTemporaryDisabled": null, "npivWorldWideNameOp": null, "npivWorldWideNameType": null, "numCPUs": "<type 'int'>", "numCoresPerSocket": null, "powerOpInfo": null, "repConfig": null, "scheduledHardwareUpgradeInfo": null, "swapPlacement": null, "tools": null, "uuid": null, "vAppConfig": null, "vAppConfigRemoved": null, "vAssertsEnabled": null, "vPMCEnabled": null, "version": null, "virtualICH7MPresent": null, "virtualSMCPresent": null, "vmProfile": []}, "customization": "<class 'pyVmomi.VmomiSupport.vim.vm.customization.Specification'>", "dynamicProperty": [], "dynamicType": null, "location": {"datastore": "'vim.Datastore:datastore-26':datastore1", "deviceChange": [], "disk": [], "diskMoveType": null, "dynamicProperty": [], "dynamicType": null, "folder": null, "host": null, "pool": "'vim.ResourcePool:resgroup-22':Resources", "profile": [], "service": null, "transform": null}, "memory": null, "powerOn": "<type 'bool'>", "snapshot": null, "template": "<type 'bool'>"}, "configspec": {"alternateGuestName": null, "annotation": null, "bootOptions": null, "changeTrackingEnabled": null, "changeVersion": null, "consolePreferences": null, "cpuAffinity": null, "cpuAllocation": null, "cpuFeatureMask": [], "cpuHotAddEnabled": "<type 'bool'>", "cpuHotRemoveEnabled": null, "crypto": null, "deviceChange": [], "dynamicProperty": [], "dynamicType": null, "extraConfig": [], "files": null, "firmware": null, "flags": null, "ftInfo": null, "guestAutoLockEnabled": null, "guestId": null, "instanceUuid": null, "latencySensitivity": null, "locationId": null, "managedBy": null, "maxMksConnections": null, "memoryAffinity": null, "memoryAllocation": null, "memoryHotAddEnabled": "<type 'bool'>", "memoryMB": "<type 'int'>", "memoryReservationLockedToMax": null, "messageBusTunnelEnabled": null, "migrateEncryption": null, "name": null, "nestedHVEnabled": null, "networkShaper": null, "npivDesiredNodeWwns": null, "npivDesiredPortWwns": null, "npivNodeWorldWideName": [], "npivOnNonRdmDisks": null, "npivPortWorldWideName": [], "npivTemporaryDisabled": null, "npivWorldWideNameOp": null, "npivWorldWideNameType": null, "numCPUs": "<type 'int'>", "numCoresPerSocket": null, "powerOpInfo": null, "repConfig": null, "scheduledHardwareUpgradeInfo": null, "swapPlacement": null, "tools": null, "uuid": null, "vAppConfig": null, "vAppConfigRemoved": null, "vAssertsEnabled": null, "vPMCEnabled": null, "version": null, "virtualICH7MPresent": null, "virtualSMCPresent": null, "vmProfile": []}, "msg": "A specified parameter was not correct. \nspec.identity.hostName"}
```

Results : Vm was created successfully but no ip has been assigned to network interface. 

Thanks  !

**Comment by Akasurde** [comment]
@SaranrajMG Could you please try with latest Ansible version ? Datastore cluster support is not available in 2.4 version. Also, does your datastore cluster enabled with Storage DRS ?

**Comment by Akasurde** [comment]
@talhajilal Your issue is different than @SaranrajMG issue. Could you please a new issue for you situation?

**Comment by SaranrajMG** [comment]
Thanks for your reply.

Yes. In all my datastore DRS enable.

Which version to be used?

**Comment by talhajilal** [comment]
Sorry for interruption and adding my issue at wrong place. 

I also fine the solution Ip was going to iffy-ether file that I handle with first-boot script

**Comment by Akasurde** [comment]
@SaranrajMG Thanks for providing information. Try latest devel version (i.e. 2.5) and let me know if it works for you.

**Comment by SaranrajMG** [comment]
@Akasurde  Thanks for version details. I have tried using datastore cluster name in the disk options but still i get the same error.  If i use specific data-store then im able to deploy the VM but not with data-store cluster name.

Please let me know if you have any other suggestion.

**Comment by Akasurde** [comment]
@SaranrajMG Would you be interested in testing this [patch]( https://github.com/ansible/ansible/compare/devel...Akasurde:datastore_fix). 

If you are using this patch, you need to modify your playbook by specific additional parameter called `datastore` outside disks specification.

Something like

```yaml
  - name: Deploy guest from template
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false
      cluster: "{{ cluster }}"
      datacenter: sDatacenter
      state: poweredon
      name: "{{ guest }}"
      template: "{{ template }}"
      folder: "LINAUTTST"
      datastore:  LUN-NPRD-OS-SCLU-08 # <---- This can be datastore or datastore cluster
      disk:
       - size_gb: 64
         datastore: LUN-NPRD-OS-SCLU-08
         type: thick
         autoselect_datastore: yes
       - size_gb: 64
         datastore: LUN-NPRD-DATA-SCLU-08
         type: thick
         autoselect_datastore: yes
      hardware:
        memory_mb: 2048
        num_cpus: 1
```

You need to have storage DRS enabled on Datastore cluster to work with this patch.
