### ISSUE TITLE
Problem resolving variables in 'when' statement within included task

### ISSUE THREAD

**Issue by jlaska** [ansible/ansible#3504]
Apologies in advance if this turns out to be a syntax error in my reproducer (ala #3269).  I've done my best to eliminate that possibility.  However, if this turns out to be an error in my reproducer, please add an additional $50 to my tab.
### Summary

I have a task file that conditionally runs tasks if a variable has been defined (and is a string).  For readability, I like to provide default values for all variables in `group_vars/all` (which seems to be part of the problem).  In the reproducer below, I define the variable directly in site.yml for simplicity.  

I'm experiencing a problem when the variable is not defined (and/or empty).  It appears that a `when` statement in the included file is not properly assembling the jinja?
### File `site.yml`

``` yaml

---
- hosts: local
  vars:
    - vmware_vddk_url:
  tasks:
    - include: tasks/vmware_vddk.yml
      when: vmware_vddk_url is string
```
### File `inventory`

``` ini
[local]
127.0.0.1 ansible_connection=local
```
### File `tasks/vmware_vddk.yml`

``` yaml

---

- name: vmware_vddk | download
  get_url: url={{vmware_vddk_url}} dest=/tmp mode=0440
  register: vmware_vddk_file

- name: vmware_vddk | tar -zxvf
  shell: tar -zxvf {{vmware_vddk_file.dest}}
         chdir=/tmp
         creates=vmware-vix-disklib-distrib

- name: vmware_vddk | vmware-install.pl
  shell: perl vmware-install.pl EULA_AGREED=yes --default
         chdir=/tmp/vmware-vix-disklib-distrib
         creates=/usr/bin/vmware-uninstall-vix-disklib.pl

- name: vmware_vddk | ldconfig --print-cache
  shell: ldconfig --print-cache
  register: ldconfig_output

- name: vmware_vddk | ldconfig
  shell: ldconfig
  when: ldconfig_output is defined and ldconfig_output.stdout.find('libvixDiskLib') == -1
```
### Actual Results

When not overriding `-e vmware_vddk_url` on the command-line, I expect all tasks to skip.

``` bash
# ansible-playbook -i inventory site.yml 

PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [vmware_vddk | download] ************************************************ 
skipping: [127.0.0.1]

TASK: [vmware_vddk | tar -zxvf] *********************************************** 
skipping: [127.0.0.1]

TASK: [vmware_vddk | vmware-install.pl] *************************************** 
skipping: [127.0.0.1]

TASK: [vmware_vddk | ldconfig --print-cache] ********************************** 
skipping: [127.0.0.1]

TASK: [vmware_vddk | ldconfig] ************************************************ 
fatal: [127.0.0.1] => Conditional expression must evaluate to True or False: ({% if ldconfig_output is defined and ldconfig_output.stdout.find('libvixDiskLib') == -1 %} True {% else %} False {% endif %}) and ({% if vmware_vddk_url is string %} True {% else %} False {% endif %})

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/var/tmp/ansible/site.retry

127.0.0.1                  : ok=1    changed=0    unreachable=1    failed=0   
```
### Workaround

The following change resolves the problem.  However, it seems incorrect to reference the same variable in and out of the included task file.

``` diff
--- tasks/vmware_vddk.bad   2013-07-11 15:25:54.609697479 -0400
+++ tasks/vmware_vddk.yml   2013-07-11 15:26:03.489677001 -0400
@@ -23 +23 @@
-  when: ldconfig_output is defined and ldconfig_output.stdout.find('libvixDiskLib') == -1
+  when: vmware_vddk_url is string and ldconfig_output is defined and ldconfig_output.stdout.find('libvixDiskLib') == -1
```
### Expected Results

When not overriding `-e vmware_vddk_url` on the command-line, I expect all tasks to skip.  With the above workaround, they indeed skip.

``` bash
# ansible-playbook -i inventory site.yml 

PLAY [local] ****************************************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [vmware_vddk | download] ************************************************ 
skipping: [127.0.0.1]

TASK: [vmware_vddk | tar -zxvf] *********************************************** 
skipping: [127.0.0.1]

TASK: [vmware_vddk | vmware-install.pl] *************************************** 
skipping: [127.0.0.1]

TASK: [vmware_vddk | ldconfig --print-cache] ********************************** 
skipping: [127.0.0.1]

TASK: [vmware_vddk | ldconfig] ************************************************ 
skipping: [127.0.0.1]

PLAY RECAP ******************************************************************** 
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=0   
```
