### ISSUE TITLE
Add exclusion list to filetree plugin

### ISSUE THREAD

**Issue by yamenk** [ansible/ansible#35042]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
  - Filetree plugin

##### SUMMARY
When using the filetree plugin in combination with the template module, I would like to exclude some subdirectories under the root path as these sub-directories contain many files that I don't want to process with the template module.

```
root
  |_ directory1
  |_ directory2
              |_ include-subdir
              |_ exclude-subdir
```

It is possible to specify the subdirectories separately, however their relative path to the root is lost, when running:

```
- name: Create directories
  file:
    path: /root/{{ item.path }}
    state: directory
    mode: '{{ item.mode }}'
  with_filetree: root/
  when: item.state == 'directory'

- name: Template files
  template:
    src: '{{ item.src }}'
    dest: /root/{{ item.path }}
    mode: '{{ item.mode }}'
  with_filetree:
     - /root/directory1
     - /root/directory2/include-subdir
  when: item.state == 'file'
```

##### EXPECTED RESULTS
Allow for an exclusion list for filetree plugin.
