### ISSUE TITLE
yum module support query

### ISSUE THREAD

**Issue by JakeDEvans** [ansible/ansible#35056]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
yum

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### CONFIGURATION
any

##### OS / ENVIRONMENT
redhat/centos

##### SUMMARY
yum support `queryformat` and `query` function 

##### STEPS TO REPRODUCE
```yaml
- name: install the latest version of Apache
  yum:
    name: httpd
    state: query
    query: VERSION
  register: httpd_version
```

##### EXPECTED RESULTS
Same output as `rpm -qa httpd --queryformat %{VERSION}`
