### ISSUE TITLE
docker_container does not recreate the container if dns_servers is removed

### ISSUE THREAD

**Issue by bjornicus** [ansible/ansible#35070]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.1.0
  config file = /home/ubuntu/.ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/home/ubuntu/.ansible.cfg) = -o StrictHostKeyChecking=no
DEFAULT_REMOTE_USER(/home/ubuntu/.ansible.cfg) = hoylu
DEFAULT_ROLES_PATH(/home/ubuntu/.ansible.cfg) = [u'/home/ubuntu/ansible-roles']
DEFAULT_SCP_IF_SSH(/home/ubuntu/.ansible.cfg) = True
DEFAULT_TRANSPORT(/home/ubuntu/.ansible.cfg) = ssh

##### OS / ENVIRONMENT
NA

##### SUMMARY
when a container is started with the 'dns_servers' parameter set, and then the parameter is . removed and the task is run again, one would expect that the container gets re-created with the Docker Dns parameter set to null.

##### STEPS TO REPRODUCE

```yaml
- name: "test docker containerr recreate with server_dns"
  hosts:  localhost
  tasks:
    - name: start the test container
      docker_container:
        name: tester
        image: redis
    - name: this should restart the test container
      docker_container:
        name: tester
        image: redis
        dns_servers: "8.8.8.8"
    - name: this should also restart the test container
      docker_container:
        name: tester
        image: redis
```

##### EXPECTED RESULTS
Expected a `changed` on the task 'this should also restart the container'

##### ACTUAL RESULTS
Got an `ok` on the task. The container was not restarted despite the configuration being different. Running it in -vvvv mode shows `module_args:dns_servers` set to null, but that is not applied to the container.

```
PLAY [test docker containerr recreate with server_dns] ********************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************
ok: [localhost]

TASK [start the test container] *******************************************************************************************************************************
changed: [localhost]

TASK [this should restart the test container] *****************************************************************************************************************
changed: [localhost]

TASK [this should also restart the test container] ************************************************************************************************************
ok: [localhost]

PLAY RECAP ****************************************************************************************************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0
```
