### ISSUE TITLE
win_scheduled_task module requires argument 'time'; documentation states 'time' is not a required argument

### ISSUE THREAD

**Issue by ajmora7** [ansible/ansible#35072]
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/ansible@sollab.local/solutionslab_2018-01-18/ansible/ansible.cfg
  configured module search path = [u'/home/ansible@sollab.local/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

ANSIBLE_SSH_ARGS(/home/ansible@sollab.local/solutionslab_2018-01-18/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=10
ANSIBLE_SSH_CONTROL_PATH(/home/ansible@sollab.local/solutionslab_2018-01-18/ansible/ansible.cfg) = %(directory)s/%%h-%%r
HOST_KEY_CHECKING(/home/ansible@sollab.local/solutionslab_2018-01-18/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ansible on CentOS 7
Managing Windows Server 2012

##### SUMMARY
When running the 'win_scheduled_task' module and omitting the 'time' parameter, ansible fails on the task stating that it's missing 'time' as a required argument, however the documentation for the module states that 'time' is not a required argument

##### STEPS TO REPRODUCE

```yaml
- name                          : Set scheduled task for script
  win_scheduled_task            :
    name                        : Install
    executable                  : C:\Python27\python.exe
    arguments                   : "{{ansible_dir}}\\install.py"
    frequency                   : once
    runlevel                    : highest
    user                        : "{{user}}"
    password                    : "{{_password}}"
    state                       : present
  register                      : install
- debug                         : var=install
```

##### EXPECTED RESULTS

The task should have been created and appeared in Task Scheduler.

##### ACTUAL RESULTS

```
TASK [Install : Set scheduled task for script] ******************************************************************************************
task path: /home/ansible/test/ansible/roles/install/tasks/new_install.yml:148
Using module file /usr/lib/python2.7/site-packages/ansible/modules/windows/win_scheduled_task.ps1
<test-machine> ESTABLISH WINRM CONNECTION FOR USER: Ansible@test-machine on PORT 5986 TO test-machine
EXEC (via pipeline wrapper)
fatal: [test-machine]: FAILED! => {
    "changed": false,
    "msg": "Get-AnsibleParam: Missing required argument: time"
}
        to retry, use: --limit @/home/ansible/test/ansible/new_install.retry

PLAY RECAP *************************************************************************************************************************$
test-machine : ok=32   changed=4    unreachable=0    failed=1
```
