### ISSUE TITLE
clear_host_errors causes unexpected behaviour with unreachable hosts

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#35086]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
meta

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = redis
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 86400
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/root/scripts/get_inventory.py']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_SAVE_PATH(/etc/ansible/ansible.cfg) = /root/.ansible-retry

##### OS / ENVIRONMENT
N/A

##### SUMMARY
I'm using Ansible to generate configuration files for physical nodes, not all of which might be present when the script runs. Using `meta: clear_host_errors` I want to create the configuration file regardless, however this appears to misbehave the more hosts are present (running against a group of ~50).

##### STEPS TO REPRODUCE
This playbook demonstrates the unexpected behaviour.

```yaml
- hosts: all
  tasks:
    - set_fact:
        was_accessible: "up"

    - meta: clear_host_errors

    - debug:
        msg: "Hello"

    - when:
        - was_accessible is defined
      debug:
        msg: "Hello again, I am up."
```

##### EXPECTED RESULTS
The fact `was_accessible` should only be set for hosts that were reachable. The first debug message should have appeared for every host, and the second message only for running hosts.

Admittedly, this might be misuse of clear_host_errors, but this behaviour still seems highly suspect.

##### ACTUAL RESULTS
Tasks appear to move between each other, and the messages appear explicitly for the nodes that they shouldn't. Additionally one of the tasks runs for the exact nodes it shouldn't.

```
PLAY [all] ****************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
fatal: [node1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host node1.domain.org port 22: Connection timed out\r\n", "unreachable": true}
fatal: [node2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host node2.domain.org port 22: Connection timed out\r\n", "unreachable": true}
fatal: [node3]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host node3.domain.org port 22: Connection timed out\r\n", "unreachable": true}
ok: [node4]
ok: [node5]
ok: [node6]
META: ran handlers

TASK [set_fact] *****************************************************************************************************************
task path: debug.yml:4
ok: [node4] => {
    "ansible_facts": {
        "was_accessible": "up"
    },
    "changed": false
}
ok: [node5] => {
    "ansible_facts": {
        "was_accessible": "up"
    },
    "changed": false
}
ok: [node6] => {
    "ansible_facts": {
        "was_accessible": "up"
    },
    "changed": false
}
META: cleared host errors
META: ran handlers

TASK [set_fact] *****************************************************************************************************************
task path: debug.yml:4
ok: [node1] => {
    "ansible_facts": {
        "was_accessible": "up"
    },
    "changed": false
}
ok: [node2] => {
    "ansible_facts": {
        "was_accessible": "up"
    },
    "changed": false
}
ok: [node3] => {
    "ansible_facts": {
        "was_accessible": "up"
    },
    "changed": false
}
ok: [node4] => {
    "msg": "Hello."
}
ok: [node5] => {
    "msg": "Hello."
}
ok: [node6] => {
    "msg": "Hello."
}
META: cleared host errors

TASK [debug] ********************************************************************************************************************
task path: debug.yml:9
META: noop
META: noop
META: noop
ok: [node1] => {
    "msg": "Hello."
}
ok: [node2] => {
    "msg": "Hello."
}
ok: [node3] => {
    "msg": "Hello."
}

TASK [debug] ********************************************************************************************************************
task path: debug.yml:12
META: noop
META: noop
META: noop
ok: [node1] => {
    "msg": "Hello again"
}
ok: [node2] => {
    "msg": "Hello again"
}
ok: [node3] => {
    "msg": "Hello again"
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************
node1                    : ok=3    changed=0    unreachable=1    failed=0
node2                    : ok=3    changed=0    unreachable=1    failed=0
node3                    : ok=3    changed=0    unreachable=1    failed=0
node4                   : ok=3    changed=0    unreachable=0    failed=0
node5                   : ok=3    changed=0    unreachable=0    failed=0
node6                   : ok=3    changed=0    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/helper/meta.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/helper/meta.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by TylerKerrACG** [comment]
Ansible 2.5.4 still has this issue. Cannot handle unreachable errors even for notifications. How has this not been looked at as it has existed for over a year?

**Comment by lassizci** [comment]
Also happens with 2.7.10

**Comment by ssbarnea** [comment]
It seems that there is no way to safely clear host errors from unreachable hosts because this would clear even other errors with reachable hosts:

```
- name: Converge
  hosts: localhost,foobar
  gather_facts: false
  tasks:

    - block:

        - name: this does nothing
          shell: exit 1

      always:
        - name: ignore host errors
          when: inventory_hostname != 'missing'
          meta: clear_host_errors
```
The example above is expected to return failure exit code 1 due to localhost task (the foobar being unreable and ignored). Instead the playbook will return success.

If we disable clear_host_errors the playbook will fail even if we put exit 0 as the task. 

I guess this happens because clear_host_errors resets all errors. I currently have no idea on how to ignore any errors with specific hosts while not affecting the playbook result on the other ones.

**Comment by wainaxman** [comment]
Duplicate of #26227

**Comment by wainaxman** [comment]
Using ignore_unreachable as propsed by @kinwolfqc in 26227 does the trick for me.

I have replicated the clear_host_errors issue with ansible 2.9.0-dev on python 2 and 3. In my case the apparently working stack would leave out arbitrary hosts leading us into a time consuming investigation. The symptom looks very weird (some tasks fire multiple times, host facts set on one host may jump to another(!!!)) and after briefly looking at the source I dont think clear_host_errors can be easily fixed.

 If we would have known about ignore_unreachable we would not have used clear_host_errors. 

 I've come to believe that clear_host_errors(introduced with 2.1) may have become obsolete due ignore_unreachable(introduced 2.7). If you agree I propose a PR removing clear_host_errors for 2.9 - Objections? @ssbarnea

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/meta.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/meta.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
This will be fixed by #59605

**Comment by BartOpitz** [comment]
I can confirm the same behaviour, when using clear_host_errors to skip a group of tasks on unreachable hosts.
My playbook looks more or less like this:
```
- name: playbook
  gather_facts: false
  tasks:
    - name: get info from host
      ansible.builtin.shell: xxxx
      register: info1
    - name:  get more info from host
      ansible.builtin.shell: xxxx
      register: info2
    - name:  get more info from host
      ansible.builtin.shell: xxxx
      register: info3
    - name: reset status of unreachable hosts
      meta: clear_host_errors
    - name: render collected facts
      local_action:
        module: ansible.builtin.copy
        dest: "/path-on-controller/{{ inventory_hostname }}"
        contents: "{{ info1.stdout | d('') }} : {{ info2.stdout | d('') }} : {{ info3.stdout | d('missing') }}"
```
Expected behaviour was - reachable hosts would dollect info1, info2 and info3. Unreachable hosts would go into unreachable on info1 task. Then, after resetting as the only module is local_action I would not expect this playbook to end with an error (exit code >0) as the last task should not fail and render files for each host regardless whether it was reachable or not.

What actually happens is - after meta Task those hosts that were unreachable seem to continue with info2 task (so practically where they left off) running again into unreachable error. Finally playbook exits with exit code 4 meaning there were unreachable hosts.

I could set ignore_unreachable to true to achieve expected result, but this would not list unreachable tasks in AWX task summary, as none of the tasks would report unreachable. Having just one task that can fail due to unreachable before ignoring host errors produces expected results as there is nothing to continue afterwards.

I use currently a silly workaround with extra play, that has only one task to check reachability, then clear_host_errors and based on the first task output I add all reachable hosts via ansible.builtin.group_by to a temporary group that I execute all the remaining tasks in second play against:

```
- name: check reachability
  hosts: "{{ target_hosts }}"
  gather_facts: false
  tasks:
    - name: check reachability
      ansible.builtin.ping:
      register: test_reachable
    - meta: clear_host_errors
    - ansible.builtin.group_by:
         key: reachable_hosts
      when: test_reachable is not unreachable

- name: main play
  hosts: reachable_hosts
...
```
