### ISSUE TITLE
s3_bucket default encryption upon bucket create and http mode in same module

### ISSUE THREAD

**Issue by dan-osms** [ansible/ansible#35110]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

s3_bucket and s3_website as one with capability for standard encryption option during bucket launch.
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/dgirard/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

MacOs 10.13.2
##### STEPS TO REPRODUCE

```yaml
      s3_bucket:
        name: "{{ somevar }}"
        policy: "{{ lookup('template', '{{ somevar }}' )}}"
        profile: "{{ somevar }}"
        state: "{{ somevar }}"
        region: "{{ somevar }}"
        encrypt: Yes
        versioning: "{{ somevar }}"
```

##### ACTUAL RESULTS

```

```
