### ISSUE TITLE
with_items & include error

### ISSUE THREAD

**Issue by kirillzlds** [ansible/ansible#3512]
I'm trying to do something like this:

``` yaml
- include: bootstrap.yml role=$item #or ${item} or even {{ item }}
  vars:
    env: development
    instance_groups: [default, sshable, app-servers, dns-clients]
  with_items:
    - test
```

But it does not work. $item is undefined, so variable _role_ assignd to string "$item" instead of value of that variable which is supposed to be "test". This code doesn't work too:

``` yaml
- include: app-server.yml role=${item}
  with_items:
    - test
```

I'm using build of current master of ansible repo, ubuntu 12.04 x64

**Comment by mpdehaan** [comment]
Before we continue I should point out that with_items + include is essentially deprecrated and not documented for a reason, because it caused so much user confusion when we accepted the patch for it.   The day we added it it generated ginormous tons of IRC questions.   It does not work with inventory variables, for instance, which is what almost everyone wants to do with it :)  This is because tasks must have the same number for all hosts in the system.

I would have to see how you are trying to use the value of "role" here to know for sure whether the with_items include operational support has issues in your case with the sourcing it from a plain list, to see if we've got a bug here.

Can you please show me how you are diagnosing the absense of "role" being defined as a variable from within bootstrap.yml?

Thanks!

**Comment by mpdehaan** [comment]
(BTW, the recommended behavior is to loop from _within_ the included task file instead)

**Comment by kirillzlds** [comment]
Yes, I know. And I read all comments on google groups and here, on github. So, I know you don't like this idea. But it looks quite logical for me to be able to define abstract tasks and few concrete layers over it.
Diagnosis is simple: bootstrap.yml creates ec2 instance with tag 'role' and value $role which is in this case "$role". While I expect it to be "test".
If I pass "test" directly into role inclusion it works well. So this code works as expected:

``` yaml
- include: app-server.yml role="test-role"
  with_items:
    - test
```

The sctructure of the system looks like this:
development.yml->system.yml->app-server.yml->bootstrap.yml
where system.yml includes not only app-server but other playbooks too. The idea is leave some abstraction on each stage, so I can have production.yml and testing.yml defining only environment for the ec2 instances. While system.yml defines which types of servers system should include: app-server defines server-specific variable such as security groups and bootstrap.yml does not define anything but creates instances on ec2.

Here is another example:
_test.yml:_

``` yaml
---
- hosts: local
  connection: local
  tasks:
    - name: test
      command: echo ${message}
```

_test_of_test.yml:_

``` yaml
---
# works
- include: test.yml message="this is the message"

#doesn't work
- include: test.yml message=${item}
  with_items:
    - hello world
```

_localhost:_

``` ini
[local]
localhost
```

and command line:

```
ansible-playbook test_of_test.yml -i ./localhost -vvv
```
