### ISSUE TITLE
with_nested should take variable names

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3513]
The following:

```
with_nested:
    - listvar1
    - [ 1,2,3 ]
```

Should be operational, no {{ }} needed

Will eliminate the need to do ${foo.x} for references here.

**Comment by candeira** [comment]
I was looking for something to do, I just tested this and it does work already:

The playbook:

```
- hosts: all
  vars:
    listvar1:
    - 'a'
    - 'b'
    - 'c'
  tasks:
    - shell: echo "nested test a={{ item[0] }} b={{ item[1] }}"
      with_nested:
        - listvar1
        - [ 1, 2, 3 ]
```

And the output:

```
TASK: [shell echo "nested test a={{item[0]}} b={{item[1]}}"] ****************** 
changed: [mofo_local] => (item=['a', 1])
changed: [mofo_local] => (item=['a', 2])
changed: [mofo_local] => (item=['a', 3])
changed: [mofo_local] => (item=['b', 1])
changed: [mofo_local] => (item=['b', 2])
changed: [mofo_local] => (item=['b', 3])
changed: [mofo_local] => (item=['c', 1])
changed: [mofo_local] => (item=['c', 2])
changed: [mofo_local] => (item=['c', 3])
```

There is a patch from you on May 5 with message: "Allow variables to be used raw in with_nested", but I can't find documentation about it, and the example needs updating:
https://github.com/candeira/ansible-examples/blob/master/language_features/loop_nested.yml

I'm making two PRs, one on the ansible repo and another on the ansible-examples repo, to close this issue:
- https://github.com/ansible/ansible/pull/3530
- https://github.com/ansible/ansible-examples/pull/18
