### ISSUE TITLE
aci_contract_subject_to_filter must support common tenant

### ISSUE THREAD

**Issue by nilloBE** [ansible/ansible#35185]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
aci_contract_subject_to_filter

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
[root@ansible-server vars]# ansible-config dump --only-change
[root@ansible-server vars]#

##### OS / ENVIRONMENT
Ansible server running on CentOS 7.3, ACI running 3.1(1i).

##### SUMMARY
The aci_contract_subject_to_filter currently assigns a filter to a subject for a given contract. The module takes the tenant name as input and configures the filter on the given subject for the contract on that tenant.

However in ACI it is possible, and desirable, to consume filters from the common tenant. Therefore, this module should allow specifying tenant name in two different ways:
- tenant where the contract is configured
- tenant where the filter is configured

I suggest we keep the 'tenant' attribute as it is now, meaning it represents the tenant where the contract object exists. And then we add another attribute 'filter_in_common' with value 'yes' or 'no'. If filter_in_common is yes, we pick the filter entry from common tenant. If filter_in_common is 'no', we pick the filter entry from the contract tenant.

**Comment by nilloBE** [comment]
CC: @dagwieers

**Comment by ansibot** [comment]
cc @brunocalogero @jmcgill298 @schunduri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@nilloBE You don't have to put me in cc everytime, @ansibot is there to do that ;-)

**Comment by jmcgill298** [comment]
@nilloBE in my testing, the contract selection process chooses local tenant contract, and defaults to common tenant if contract does not exist in local tenant.

**Comment by nilloBE** [comment]
@jmcgill298 yes, but the point here is not about the contract, but about the filter. If contract exists in tenant, we select that contract. but then how do we specify a filter from common tenant?
- contract in tenant 'pepsi'
- filter in tenant 'common'

This allows sharing a filter for multiple contracts regardless of tenants. At the moment I do not see how to configure that with this module.

**Comment by jmcgill298** [comment]
sorry, I wasn't paying enough attention this morning. I do believe the contract to filter relationship behaved the same way though. I can retest later and validate.

**Comment by jmcgill298** [comment]
@nilloBE I tested and it does behave as I mentioned. I am pretty sure that is general behavior for relationship objects in the APIC; first look in the local tenant, and look in the `common` tenant if it is not found.

Also, I am pretty sure that these objects to do not even provide a way to specify the Tenant, and I remember looking at this because the consequence of creating an identically named object in the local tenant when there is an exiting relationship with an object in common could have disastrous consequences.

Here is the object config properties:
```json
{
    "vzRsSubjFiltAtt": {
        "attributes": {
            "directives": "",
            "dn": "uni/tn-anstest/brc-anscontractdoesnotexist/subj-anscontractsubjectdoenotexist/rssubjFiltAtt-ansfilterdoenotexist",
            "tnVzFilterName": "ansfilterdoenotexist"
        }
    }
}
``` 

Here is a playbook you can use to test yourself:
```yaml
- name: DEMONSTRATE DEFAULT RELATIONSHIP BEHAVIOR
  hosts: aci
  connection: local
  gather_facts: no
  tasks:
    - name: "ENSURE TENANT EXISTS"
      aci_tenant:
        host: "{{ ansbile_host }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh pass }}"
        validate_certs: no
        state: present
        tenant: "anstest"
      tags: ten

    - name: "ENSURE FILTER EXISTS IN COMMON TENANT"
      aci_filter:
        hostname: "{{ ansbile_host }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh pass }}"
        validate_certs: no
        tenant: "common"
        filter: "ansfilterdoenotexist"

    - name: "ENSURE CONTRACT EXISTS IN TEST TENANT"
      aci_contract:
        hostname: "{{ ansbile_host }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh pass }}"
        validate_certs: no
        tenant: "anstest"
        contract: "anscontractdoesnotexist"

    - name: "ENSURE CONTRACT SUBJECT EXISTS IN TEST TENANT"
      aci_contract_subject:
        hostname: "{{ ansbile_host }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh pass }}"
        validate_certs: no
        tenant: "anstest"
        contract: "anscontractdoesnotexist"
        contract_subject: "anscontractsubjectdoenotexist"

    - name: "ENSURE TEST TENANT CONTRACT SUBJECT BINDS WITH COMMON TENANT FILTER"
      aci_contract_subject_to_filter:
        hostname: "{{ ansbile_host }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh pass }}"
        validate_certs: no
        tenant: "anstest"
        contract: "anscontractdoesnotexist"
        contract_subject: "anscontractsubjectdoenotexist"
        filter: "ansfilterdoenotexist"

    - name: "VALIDATE THAT BINDING IS BETWEEN TENANTS WITHOUT SPECIFYING COMMON TENANT"
      aci_rest:
        hostname: "{{ ansbile_host }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh pass }}"
        validate_certs: no
        method: "get"
        path: "api/mo/uni/tn-anstest/brc-anscontractdoesnotexist/subj-anscontractsubjectdoenotexist/rssubjFiltAtt-ansfilterdoenotexist.json"
      register: contract_query

    - name: "DEBUG QUERY RESULTS FOR EASY VIEWING"
      debug:
        msg: |
          OBJECT DN: {{ contract_query.imdata.0.vzRsSubjFiltAtt.attributes.dn }}
          FILTER DN: {{ contract_query.imdata.0.vzRsSubjFiltAtt.attributes.tDn }}

    - name: "CREATE FILTER WITH IDENTICAL NAME TEST TENANT"
      aci_filter:
        hostname: "{{ ansbile_host }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh pass }}"
        validate_certs: no
        tenant: "anstest"
        filter: "ansfilterdoenotexist"

    - name: "QUERY CONTRACT FILTER RELATIONSHIP SHOWING THAT BINDING IS NOW POINTING AT TEST TENANT"
      aci_rest:
        hostname: "{{ ansbile_host }}" 
        username: "{{ ansible_user }}"
        password: "{{ ansible_ssh pass }}"
        validate_certs: no
        method: "get"
        path: "api/mo/uni/tn-anstest/brc-anscontractdoesnotexist/subj-anscontractsubjectdoenotexist/rssubjFiltAtt-ansfilterdoenotexist.json"
      register: contract_requery

    - name: "DEBUG QUERY RESULTS FOR EASY VIEWING"
      debug:
        msg: |
          OBJECT DN: {{ contract_requery.imdata.0.vzRsSubjFiltAtt.attributes.dn }}
          FILTER DN: {{ contract_requery.imdata.0.vzRsSubjFiltAtt.attributes.tDn }}

```
