### ISSUE TITLE
meta module not working with refresh_inventory

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#35195]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
meta

##### ANSIBLE VERSION
```
SEANs-MacBook-Pro:~ sean$ ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
```
SEANs-MacBook-Pro:~ sean$ ansible-config dump --only-changed
SEANs-MacBook-Pro:~ sean$
```
nothing changed

##### OS / ENVIRONMENT
```
macOS High Sierra 10.13.2
```
##### SUMMARY
The [meta module](http://docs.ansible.com/ansible/latest/meta_module.html) does not seem to refresh the inventory within a role/play using the `refresh_inventory`.  I am unable to use hosts from add_host until I am onto the next playbook or role.

##### STEPS TO REPRODUCE
Here is a simple playbook that I made to replicate the issue I am seeing in a much larger one.  My goal is to have a role be able to up ec2_instances in amazon, then use wait_for_connection task to make sure they are actually up and able to connect to.  Right now it works if the wait_for_connection is in another play within the playbook (I tested with another role).

```yaml
---
- hosts: localhost
  tasks:
  - add_host:
      name: "testhost"
      ansible_host: "1.2.3.4"
      ansible_user: "testuser"
      groups:
        - lab_hosts
        - control_nodes

  - name: Refresh inventory to ensure new instaces exist in inventory
    meta: refresh_inventory

  - debug:
      msg: "item: {{ item }}"
    with_items: groups['all']
```

##### EXPECTED RESULTS
I expected something like:
```
ok: [localhost] => (item=groups['all']) => {
    "attempts": 1,
    "changed": false,
    "failed": false,
    "item": "'localhost",
    "msg": "item localhost"
}
ok: [localhost] => (item=groups['all']) => {
    "attempts": 1,
    "changed": false,
    "failed": false,
    "item": "testhost",
    "msg": "item testhost"
}
```
somehow... there would be 2 above... not sure how to loop through the groups... was looking at thread here-> https://github.com/ansible/ansible/issues/5451

##### ACTUAL RESULTS

```
PLAY [localhost] *************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [add_host] **************************************************************************************************************************************************************************************************************************
changed: [localhost]

TASK [debug] *****************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=groups['all']) => {
    "attempts": 1,
    "changed": false,
    "failed": false,
    "item": "groups['all']",
    "msg": "item: groups['all']"
}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/helper/meta.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/helper/meta.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by IPvSean** [comment]
tagging hero @bcoca

**Comment by sivel** [comment]
There seems to be a few things happening here.  The `refresh_inventory` is purposefully emptying the cache which removes the dynamically added hosts, and refreshing inventory from the inventory source.

It also appears as though your `with_items` syntax is a little off.

`with_items` now requires jinja2 delimiters for variables, such as:

```
  - debug:
      msg: "item: {{ item }}"
    with_items: "{{ groups['all'] }}"
```

I think what you need is to remove the `refresh_inventory` and to update your `with_items` syntax.  Does that resolve your problem?

needs_info

**Comment by IPvSean** [comment]
changed the playbook to->

```yml
SEANs-MacBook-Pro:~ sean$ cat test.yml
---
- hosts: localhost
  tasks:
  - add_host:
      name: "testhost"
      ansible_host: "1.2.3.4"
      ansible_user: "testuser"
      groups:
        - lab_hosts
        - control_nodes

  - add_host:
      name: "testhost2"
      ansible_host: "4.3.2.1"
      ansible_user: "testuser"
      groups:
        - lab_hosts
        - control_nodes

#  - name: Refresh inventory to ensure new instaces exist in inventory
#    meta: refresh_inventory

  - debug:
      msg: "item: {{ item }}"
    with_items: "{{ groups['all'] }}"
```

the results now are what I expect... except the localhost doesn't show... but I think that is just a result of how localhost works...

so unfortunately this doesn't fix my issue... in my REAL playbook (not this simplified one) I add_host based on ec2 module output, then I do a wait_for_connection module... but it just fails with 

```
<control_nodes> SSH: EXEC ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/Users/sean/.ansible/cp/d227dee234 control_nodes '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<control_nodes> (255, '', 'OpenSSH_7.6p1, LibreSSL 2.6.2\r\ndebug1: Reading configuration data /Users/sean/.ssh/config\r\ndebug1: /Users/sean/.ssh/config line 1: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 48: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/Users/sean/.ansible/cp/d227dee234" does not exist\r\ndebug2: resolving "control_nodes" port 22\r\nssh: Could not resolve hostname control_nodes: nodename nor servname provided, or not known\r\n')
wait_for_connection: attempting ping module test
```

let me see if I can simplify this down a bunch and update the ticket... 

it sounds like refresh_inventory needs some updated documentation, should i open a ticket

**Comment by sivel** [comment]
In that output, it looks like it is attempting to use a group name `control_nodes` as a hostname:

```
Could not resolve hostname control_nodes: nodename nor servname provided, or not known
```

Without seeing more of the "REAL" playbook, I'm not sure.  I'd probably have something like:

```yaml
---
- hosts: localhost
  tasks:
  - add_host:
      name: "testhost"
      ansible_host: "1.2.3.4"
      ansible_user: "testuser"
      groups:
        - lab_hosts
        - control_nodes

- hosts: control_nodes
  gather_facts: false
  pre_tasks:
    - wait_for_connection:
    - setup:
  tasks:
    [...]
```

As for `refresh_inventory`, I'm guessing you are referencing the fact that it clears the cache which includes hosts added via `add_host` or `group_by`.  In which case, additional docs would likely be useful there.
