### ISSUE TITLE
elb_target_group module does not support "traffic-port" as value for health_check_port (aws cli does)

### ISSUE THREAD

**Issue by ramonamis** [ansible/ansible#35228]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
elb_target_group

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/ramonamis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ramonamis/.virtualenvs/devops/lib/python2.7/site-packages/ansible
  executable location = /Users/ramonamis/.virtualenvs/devops/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
```yaml
[defaults]
display_args_to_stdout = False
host_key_checking = False
inventory-file = inventory/ec2.py
become = yes
force_color = 1

# Enable task profiling
callback_whitelist = profile_tasks
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When creating a target group for the new load balancers, I can not specify traffic-port as a value for the healthcheck port.

##### STEPS TO REPRODUCE

```
health_check_port: "traffic-port"
```

Ansible error:
```yaml
TASK [lb-route53-create : Create lb target group] ******************************
Tuesday 23 January 2018  14:15:39 +0000 (0:00:00.751)       0:08:03.021 ******* 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument health_check_port is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: 'traffic-port'"}
```
This works on the aws cli
```yaml
$ aws elbv2 create-target-group --name my-targets --protocol HTTP --port 80 --health-check-port traffic-port --vpc-id vpc-xxx
{
    "TargetGroups": [
        {
            "HealthCheckPath": "/",
            "HealthCheckIntervalSeconds": 30,
            "VpcId": "vpc-xxx",
            "Protocol": "HTTP",
            "HealthCheckTimeoutSeconds": 5,
            "TargetType": "instance",
            "HealthCheckProtocol": "HTTP",
            "UnhealthyThresholdCount": 2,
            "HealthyThresholdCount": 5,
            "TargetGroupArn": "xxx",
            "Matcher": {
                "HttpCode": "200"
            },
            "HealthCheckPort": "traffic-port",
            "Port": 80,
            "TargetGroupName": "my-targets"
        }
    ]
}
```

##### EXPECTED RESULTS

I would expect to be able to specify the "traffic-port" as a value to the health check port. This is assumed to be the default value if the health_check_port is not assigned a value, but it makes migrating from a defined port to the traffic port impossible without downtime.

##### ACTUAL RESULTS

```yaml
TASK [lb-route53-create : Create lb target group] ******************************
Tuesday 23 January 2018  14:15:39 +0000 (0:00:00.751)       0:08:03.021 ******* 
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument health_check_port is of type <type 'str'> and we were unable to convert to int: invalid literal for int() with base 10: 'traffic-port'"}
```
