### ISSUE TITLE
Unable to use variable inside the json body of ansible script.

### ISSUE THREAD

**Issue by lelight** [ansible/ansible#35227]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT
!component =/lib/ansible/modules/net_tools/basics/uri.py

##### ANSIBLE VERSION
```
ansible 2.0.0.2

```

##### CONFIGURATION
```
---

- name: Search Filter for http-status-code 500
  hosts: kibana
  tasks:
  - name: Install httplib2
    yum: 
      name: python-httplib2 
      state: present
  - name: Create http-status-code
    vars:
      watch1: '{ "title": "http-response-500", "description": "", "hits": 0,  "columns": ["_source"], "sort": ["@timestamp","desc"],  "version": 1, "kibanaSavedObjectMeta": {"searchSourceJSON": "{\"index\":\"packetbeat-*\",\"highlightAll\":true,\"version\":true,\"query\":{\"query_string\":{\"query\":\"beat.hostname: "{{ ansible_hostname }}" AND http.response.code: 500\", \"analyze_wildcard\":true}},\"filter\":[]}"} }'     
    uri:
      url: http://localhost:9200/.kibana/search/http-response-500
      method: PUT
      force_basic_auth: yes
      body: "{{ watch1 }}"
      body_format: json
      headers:
        Content-Type: "application/json"

...
```

##### OS / ENVIRONMENT
Running from: Ubuntu 16.04
The managed Machine: Centos 6.9

##### PROBLEM
My goal is to create a search filter in kibana using curl request. I tried to include the hostname variable inside the json body as shown below. The hostname will be changing everytime.  The changed hostname will replace the below query.
```
beat.hostname: "{{ ansible_hostname }}" AND http.response.code: 500
```
I ran the below command to run 
`ansible-playbook yy.yml -i hosts -vvv
`
And my query should not go like this to the kibana
`"beat.hostname: \"local-10-110\" AND http.response.code: 500\\\"
`
But it should go like this
`"beat.hostname: local-10-110 AND http.response.code: 500\\\"`
##### ERROR
I got this error
```
fatal: [some_IP]: FAILED! => {"_content_encoding": "gzip", "changed": false, "content": "{\"error\":{\"root_cause\":[{\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\"}],\"type\":\"mapper_parsing_exception\",\"reason\":\"failed to parse\",\"caused_by\":{\"type\":\"not_x_content_exception\",\"reason\":\"Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes\"}},\"status\":400}", "content_length": "313", "content_type": "application/json; charset=UTF-8", "failed": true, "invocation": {"module_args": {"backup": null, "body": "{ \"title\": \"http-response-500\", \"description\": \"\", \"hits\": 0,  \"columns\": [\"_source\"], \"sort\": [\"@timestamp\",\"desc\"],  \"version\": 1, \"kibanaSavedObjectMeta\": {\"searchSourceJSON\": \"{\\\"index\\\":\\\"packetbeat-*\\\",\\\"highlightAll\\\":true,\\\"version\\\":true,\\\"query\\\":{\\\"query_string\\\":{\\\"query\\\":\\\"beat.hostname: \"local-10-110\" AND http.response.code: 500\\\", \\\"analyze_wildcard\\\":true}},\\\"filter\\\":[]}\"} }", "body_format": "json", "content": null, "creates": null, "delimiter": null, "dest": null, "directory_mode": null, "follow": false, "follow_redirects": "safe", "force": null, "force_basic_auth": true, "group": null, "headers": {"Content-Type": "application/json"}, "method": "PUT", "mode": null, "owner": null, "password": null, "regexp": null, "remote_src": null, "removes": null, "return_content": false, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": null, "status_code": [200], "timeout": 30, "url": "http://localhost:9200/.kibana/search/http-response-500", "user": null, "validate_certs": true}, "module_name": "uri"}, "json": {"error": {"caused_by": {"reason": "Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes", "type": "not_x_content_exception"}, "reason": "failed to parse", "root_cause": [{"reason": "failed to parse", "type": "mapper_parsing_exception"}], "type": "mapper_parsing_exception"}, "status": 400}, "msg": "Status code was not [200]", "redirected": false, "status": 400, "transfer_encoding": "chunked"}

```
