### ISSUE TITLE
win_chocolatey - args. quotes

### ISSUE THREAD

**Issue by mvorisek** [ansible/ansible#35238]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
2.4.2.0

##### SUMMARY
A single double quotes are ignored:
```
- name: Install ImageMagick
  win_chocolatey:
    name: imagemagick.app
    install_args: "/DIR=\"{{ ansible_env['ProgramFiles'] }}\\ImageMagick\""
```

A working workaround is:
```
- name: Install ImageMagick
  win_chocolatey:
    name: imagemagick.app
    install_args: "/DIR=\"\"{{ ansible_env['ProgramFiles'] }}\\ImageMagick\"\""
```

This seems like a bug as single double quotes are ignored (checked against chocolatey log), but they should be probably double somewhere in the module.

**Comment by ansibot** [comment]
@mvorisek Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @elventear @jborean93 @jhawkesworth @nitzmahone @petemounce @ptemplier @smadam813 @trondhindenes
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mvorisek** [comment]
Try typical command line usage is this (source https://chocolatey.org/packages/php ):
--params '"/ThreadSafe ""/InstallDir:C:\PHP"""'

So this module should double all double quotes and wrap the result in double quotes.

**Comment by mvorisek** [comment]
Chocolatey design, closing...

**Comment by jborean93** [comment]
@mvorisek not sure if it should be, how would you install this through the normal chocolatey command line (with 1 or 2 double quotes). If it is with 2 then it sounds like the php package is an outlier and we don't want to change anything but if it is 1 then yes maybe we need to look into it further.

I am wary of adding in a function to automatically duplicate double quotes as it could lead to all sorts of other issues. On top of that `""` is not an escape character for `"` and is interpreted as 1 argument that is empty from a Windows perspective https://msdn.microsoft.com/en-us/library/17w5ykft.aspx?f=255&MSPPError=-2147217396. This is a bit different when it comes to cmd which has it's own parser on top of that but win_chocolatey does not interact with this shell at all.

Finally, what makes this even more confusing is the various levels of escaping that is going on, yaml/json -> powershell -> chocolatey -> installer process. Taking it step by step you have defined  the args in yaml as

`"/DIR=\"\"{{ ansible_env['ProgramFiles'] }}\\ImageMagick\"\""`

which results in an unescaped string of

`/Dir=""{{ ansible_env['ProgramFiles'] }}\ImageMagick""`

This then get's sent to Powershell as a single argument and called under

`&choco.exe @("--installargs", '/Dir=""{{ ansible_env['ProgramFiles'] }}\ImageMagick""')`

Chocolatey then does it's own stuff to parse those install args and finally use them when calling the php exectuable (which then interpretets them in some way). I believe it is this step where chocolatey may require the `""` and I am under the belief that we shouldn't attempt to try and parse things for chocolatey, e.g. if Chocolatey normally expects `""` when calling it outside Ansible then Ansible should be the same.

**Comment by dschmidt** [comment]
I'm trying to install openssh with the `/SSHServerFeature` enabled, but I can't seem to find out how to properly pass the param to the `install_args` of the `win_chocolatey` module:

does not work:
```  - name: Install sshd server
    win_chocolatey:
      force: yes
      name: openssh
      install_args: /SSHServerFeature
```
I also tried several variations of `"` and `\"` around it. Also with `-params`. What works though is:
```
  - name: Install sshd server
    win_command: choco install -f -y openssh -params '"/SSHServerFeature"' -confirm
```

Am I using the module incorrectly or does this issue make this impossible right now indeed?

**Comment by jborean93** [comment]
@dschmidt you want to use `params` install of `install_args`. I believe the latter is only used when initially installing Chocolatey while `params` is for installing individual packages.

**Comment by dschmidt** [comment]
@jborean93 That makes sense :man_facepalming: 
That's what I get for not reading the documentation till the end. But even now the documentation does not seem to be super explicit about it. Anyway thanks a lot for this super quick response! 

It indeed works and in hope that it might be useful to anyone, even setting the default shell works like a charm:
```
  - name: Install openssh
    win_chocolatey:
      name: openssh
      params: /SSHServerFeature /PathSpecsToProbeForShellEXEString:$env:programfiles\PowerShell\*\pwsh.exe;$env:programfiles\PowerShell\*\Powershell.exe;c:\windows\system32\windowspowershell\v1.0\powershell.exe /AllowInsecureShellEXE
```
