### ISSUE TITLE
azure_rm_virtualmachine fails to add tags to existing vm

### ISSUE THREAD

**Issue by liyaka** [ansible/ansible#35235]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
```
2.4.2.0
```
Azure modules:
```
azure-cli-core (2.0.24)
azure-cli-nspkg (3.0.1)
azure-common (1.1.8)
azure-graphrbac (0.30.0)
azure-mgmt (1.0.0)
azure-mgmt-authorization (0.30.0)
azure-mgmt-batch (4.1.0)
azure-mgmt-cdn (0.30.3)
azure-mgmt-cognitiveservices (1.0.0)
azure-mgmt-compute (2.1.0)
azure-mgmt-containerregistry (0.2.1)
azure-mgmt-containerservice (1.0.0)
azure-mgmt-datalake-analytics (0.1.6)
azure-mgmt-datalake-nspkg (2.0.0)
azure-mgmt-datalake-store (0.1.6)
azure-mgmt-devtestlabs (2.0.0)
azure-mgmt-dns (1.0.1)
azure-mgmt-documentdb (0.1.3)
azure-mgmt-iothub (0.2.2)
azure-mgmt-keyvault (0.40.0)
azure-mgmt-logic (2.1.0)
azure-mgmt-monitor (0.2.1)
azure-mgmt-network (1.7.1)
azure-mgmt-nspkg (2.0.0)
azure-mgmt-rdbms (0.1.0)
azure-mgmt-redis (4.1.1)
azure-mgmt-resource (1.1.0)
azure-mgmt-scheduler (1.1.3)
azure-mgmt-sql (0.7.1)
azure-mgmt-storage (1.5.0)
azure-mgmt-trafficmanager (0.30.0)
azure-mgmt-web (0.32.0)
azure-nspkg (2.0.0)
azure-servicebus (0.21.1)
azure-servicemanagement-legacy (0.20.6)
azure-storage (0.35.1)
```
##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/data/jenkins/workspace/ttt/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_CALLBACK_PLUGIN_PATH(/data/jenkins/workspace/ttt/ansible.cfg) = [u'/data/jenkins/workspace/ttt/plugins']
DEFAULT_FORKS(/data/jenkins/workspace/ttt/ansible.cfg) = 50
DEFAULT_ROLES_PATH(/data/jenkins/workspace/ttt/ansible.cfg) = [u'/data/jenkins/workspace/ttt/roles']
DEFAULT_TIMEOUT(/data/jenkins/workspace/ttt/ansible.cfg) = 4
DEPRECATION_WARNINGS(/data/jenkins/workspace/ttt/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/data/jenkins/workspace/ttt/ansible.cfg) = False
HOST_KEY_CHECKING(/data/jenkins/workspace/ttt/ansible.cfg) = False
PARAMIKO_RECORD_HOST_KEYS(/data/jenkins/workspace/ttt/ansible.cfg) = False
RETRY_FILES_ENABLED(/data/jenkins/workspace/ttt/ansible.cfg) = False

```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
Running ansible playbook that suppose to add tag to existing vm and get this error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine vs-liyatest777 - Unable to build a model: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get'"}
```

##### STEPS TO REPRODUCE
My ansible code:
```
- name: Add stopped_on tag
  azure_rm_virtualmachine:
    resource_group: "{{ az_resource_group }}"
    name: "{{ az_vmname }}"
    state: present
    append_tags: True
    tags:
       stopped_on: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"
```
The VM exists in the correct resource group, other action, like stopping or restarting the instance work as expected
##### EXPECTED RESULTS

The new tag is added

##### ACTUAL RESULTS
Error:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine vs-liyatest777 - Unable to build a model: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get'"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by liyaka** [comment]
Works fine using azure cli as workaround:
```
- name: Add stopped_on tag (workaround)
  shell: "az vm update --resource-group {{ az_resource_group }} --name {{ az_vmname }} --set tags.stopped_on={{ ansible_date_time.date }}"
```
Waiting for ansible solution...

**Comment by kyliel** [comment]
Thank you for reporting it. @yuwzho, we need someone help take a look.

**Comment by yuwzho** [comment]
I will take a look.

**Comment by yuwzho** [comment]
I cannot reproduce it issue, @liyaka, can you show your whole playbook?

**Comment by liyaka** [comment]
@yuwzho 
This is my playbook:
```
- hosts: "{{ target_host }}"

  tasks:
   - name: Stop a VM
     azure_rm_virtualmachine:
        resource_group: "{{ az_resource_group }}"
        name: "{{ az_vmname }}"
        state: present
        started: no
       append_tags: True
        tags:
           stopped_on: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"`
```


Since it didn't work, I've separated stopping and adding the tag:
```
- hosts: "{{ target_host }}"

  tasks:
   - name: Stop a VM
     azure_rm_virtualmachine:
        resource_group: "{{ az_resource_group }}"
        name: "{{ az_vmname }}"
        state: present
        started: no

    - name: Add stopped_on tag
      azure_rm_virtualmachine:
        resource_group: "{{ az_resource_group }}"
        name: "{{ az_vmname }}"
        state: present
        append_tags: True
        tags:
           stopped_on: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"
```

And since it still fails on the tag creation, now it looks like this and it works:
```
- hosts: "{{ target_host }}"

  tasks:
   - name: Stop a VM
     azure_rm_virtualmachine:
        resource_group: "{{ az_resource_group }}"
        name: "{{ az_vmname }}"
        state: present
        started: no

    # - name: Add stopped_on tag
    #   azure_rm_virtualmachine:    #     resource_group: "{{ az_resource_group }}"
    #     name: "{{ az_vmname }}"
    #     state: present
    #     append_tags: True
    #     tags:
    #        stopped_on: "{{ ansible_date_time.date }} {{ ansible_date_time.time }}"

# https://github.com/ansible/ansible/issues/35235#issuecomment-359852399
- name: Add stopped_on tag (workaround)
  shell: "az vm update --resource-group {{ az_resource_group }} --name {{ az_vmname }} --set tags.stopped_on={{ ansible_date_time.date }}"
```
