### ISSUE TITLE
Fail when doesn't seem to work properly

### ISSUE THREAD

**Issue by hemna** [ansible/ansible#35256]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
fail

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/waboring/.ansible.cfg
  configured module search path = [u'/home/waboring/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/waboring/test/ansible-vagrant-ceph/.venv/lib/python2.7/site-packages/ansible
  executable location = /home/waboring/test/ansible-vagrant-ceph/.venv/bin/ansible
  python version = 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
```

##### SUMMARY
fail: when doesn't work.  Fail shouldn't fail when the condition of the when clause isn't met.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost

  tasks:
    - name: Fail shouldn't fail when a condition isn't met
      fail:
        msg: "this is a failure we shouldn't see"
        when: 1 == 2
```

##### ACTUAL RESULTS

```
PLAYBOOK: test.yml ****************************************************************************************************************************************************
1 plays in test.yml

PLAY [localhost] ******************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************
ok: [localhost]
META: ran handlers

TASK [Fail shouldn't fail when a condition isn't met] *****************************************************************************************************************
task path: /home/waboring/test/ansible-vagrant-ceph/test.yml:6
fatal: [localhost]: FAILED! => {"changed": false, "msg": "this is a failure we shouldn't see"}
	to retry, use: --limit @/home/waboring/test/ansible-vagrant-ceph/test.retry

PLAY RECAP ************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/fail.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/fail.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
You have `when:` wrongly indented, it is not a parameter to the module, but instead a directive to your task.
So you have to do:
```yaml
---
- hosts: localhost

  tasks:
    - name: Fail shouldn't fail when a condition isn't met
      fail:
        msg: "this is a failure we shouldn't see"
      when: 1 == 2
```

The devil is in the details.
