### ISSUE TITLE
nso_config fails to set nested list in one transaction with NSO 4.5.2

### ISSUE THREAD

**Issue by cnasten** [ansible/ansible#35264]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nso_config

##### ANSIBLE VERSION
```
ansible 2.5.0 (nso_config_exists 669a86174f) last updated 2018/01/24 09:12:10 (GMT +200)
  config file = None
  configured module search path = [u'/home/cnasten/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cnasten/dev/ansible/lib/ansible
  executable location = /home/cnasten/dev/ansible/bin/ansible
  python version = 2.7.14+ (default, Dec  5 2017, 15:17:02) [GCC 7.2.0]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT
Debian GNU/Linux Buster controlling NSO 4.5.2

##### SUMMARY
Creating configuration for nested lists will fail when checking for existence on the child list due to changed behavior of the exists call in NSO.

##### STEPS TO REPRODUCE
Use the provided YAML together with the YANG below.

YAML:
```yaml
- name: Test leaf-list set
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
  - name: Set leaf-list
    nso_config:
      url: "http://localhost:8080/jsonrpc"
      username: "username"
      password: "password"
      data:
        test:parent:
        - name: k1
          child:
          - name: k2
```

YANG:
```yang
module test {
    namespace "urn:test";
    prefix test;

    list parent {
        key name;
        leaf name {
            type string;
        }

        list child {
            key name;
            leaf name {
                type string;
            }
        }
    }
}
```

##### EXPECTED RESULTS
The parent and child list should be created with one entry each.

##### ACTUAL RESULTS
nso_config fails executing the Python code.
