### ISSUE TITLE
gce_snapshot module fails to create snapshot.

### ISSUE THREAD

**Issue by Rahul-CSI** [ansible/ansible#35266]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gce_snapshot

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
[centos@localhost ~]$ ansible-config dump --only-changed
[centos@localhost ~]$

##### OS / ENVIRONMENT
[centos@localhost ~]$ cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[centos@localhost ~]$ uname -a
Linux localhost.localdomain 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[centos@localhost ~]$

##### STEPS TO REPRODUCE
1. Create google cloud instance with gce module.
Below is the gce module call to create an instance with persistent boot disk.
```
  gce:
    machine_type: n1-standard-1
    name: test-machine
    image: centos-7
    network: test-network
    subnetwork: test-subnetwork
    state: present
    external_ip: ephemeral
    ip_forward: true
    zone: us-central1-a
    num_instances: 1
    service_account_permissions: compute-rw,storage-full
    preemptible: false
    disk_auto_delete: false
    persistent_boot_disk: True
```
2. Create snapshot with gce_snapshot module.
```
    gce_snapshot:
      instance_name: test-machine
      snapshot_name: test-machine-snapshot
```
The gce_snapshot module fails with error,
libcloud.common.google.ResourceNotFoundError: u"Volume name: 'persistent-disk-0' not found. Zone: None"

The full traceback is:
```
Traceback (most recent call last):
  File "/tmp/ansible_WSkjjs/ansible_module_gce_snapshot.py", line 225, in <module>
    main()
  File "/tmp/ansible_WSkjjs/ansible_module_gce_snapshot.py", line 197, in main
    volume_obj = gce.ex_get_volume(device_name)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7126, in ex_get_volume
    return self._ex_lookup_volume(name, zone)
  File "/usr/lib/python2.7/site-packages/libcloud/compute/drivers/gce.py", line 7432, in _ex_lookup_volume
    volume_name, zone), None, None)
libcloud.common.google.ResourceNotFoundError: u"Volume name: 'persistent-disk-0' not found. Zone: None"
```

3. The boot disk name in REST response is returned as "persistent-disk-0"
The Google UI interface shows correct disk name as "test-disk-000"
Below is the REST response of get request for instance information:
```
  "disks": [
    {
      "autoDelete": true,
      "boot": true,
      "deviceName": "persistent-disk-0",
      "index": 0,
      "interface": "SCSI",
      "kind": "compute#attachedDisk",
      "licenses": [
        "projects/centos-cloud/global/licenses/centos-7"
      ],
      "mode": "READ_WRITE",
      "source": "projects/cloud-sandbox-1162/zones/us-central1-a/disks/test-disk-000",
      "type": "PERSISTENT"
    }
  ]
```
Due to this the gce_snapshot module fails.

##### EXPECTED RESULTS
Snapshot should get created.

##### ACTUAL RESULTS
We receive error as "Volume name: 'persistent-disk-0' not found"

```

```
