### ISSUE TITLE
service state=started fails when nginx is already running

### ISSUE THREAD

**Issue by titanous** [ansible/ansible#3526]
Running ansible v1.2.2 against an Ubuntu 12.04 server.

I have a playbook that runs these tasks:

``` yaml
- name: add nginx repo key
  apt_key: id=7BD9BF62 url=http://nginx.org/keys/nginx_signing.key

- name: add nginx repo
  apt_repository: repo='deb http://nginx.org/packages/ubuntu/ precise nginx'
  register: nginx_repo

- name: apt-get update
  action: apt update_cache=yes
  when_boolean: ${nginx_repo.changed}

- name: install nginx
  action: apt pkg=nginx state=installed

- name: ensure nginx is running and enabled
  action: service name=nginx state=started enabled=true
```

When nginx is already running the last task fails with no useful error message:

```
TASK: [ensure nginx is running] ***********************************************
failed: [192.168.50.2] => {"failed": true}
```

When nginx is not running, the task does not fail.
