### ISSUE TITLE
get_url should support NTLM

### ISSUE THREAD

**Issue by Tux12Fun** [ansible/ansible#35277]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible_role/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 300
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS
Linux ********* 4.4.0-101-generic #124-Ubuntu SMP Fri Nov 10 18:29:59 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

I have to use curl in my playbook because get_url dosn't support NTLM. 
I like to fech a file from a Windows PKI Server

##### STEPS TO REPRODUCE

```yaml
  - name:                            Download CA Certifacte
    get_url:
       url:                          '{{CE_PKI_SERVER_PROTO}}://{{CE_PKI_SERVER_IP}}/{{CE_PKI_URL}}/certnew.p7b?ReqID=CACert&Renewal=0&Mode=inst&Enc=b64'
       dest:                         '{{CE_PKI_SSLDIR}}/PKI-CHAIN.p7b'
       force_basic_auth:             yes
       url_username:                 'Cert_Ansible'
       url_password:                 '*******'
       force:                            yes
       validate_certs:               no
```

##### EXPECTED RESULTS

File should be downloaded, as curl does.

##### ACTUAL RESULTS

```
TASK [ce.pki_ssl : Download CA Certifacte] **********************************************************************************************************************************************************
task path: /etc/ansible/roles/ce.pki_ssl/tasks/JAVA-KEYSTORE.yml:43
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/net_tools/basics/get_url.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: *******
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/******/.ansible/tmp/ansible-tmp-1516799017.2-59471723919608 `" && echo ansible-tmp-1516799017.2-59471723919608="` echo /home/*********/.ansible/tmp/ansible-tmp-1516799017.2-59471723919608 `" ) && sleep 0'
<localhost> PUT /tmp/tmp_yFyx0 TO /home/*********/.ansible/tmp/ansible-tmp-1516799017.2-59471723919608/get_url.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/********/.ansible/tmp/ansible-tmp-1516799017.2-59471723919608/ /home/*********/.ansible/tmp/ansible-tmp-1516799017.2-59471723919608/get_url.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/********/.ansible/tmp/ansible-tmp-1516799017.2-59471723919608/get_url.py; rm -rf "/home/*******/.ansible/tmp/ansible-tmp-1516799017.2-59471723919608/" > /dev/null 2>&1 && sleep 0'
fatal: [xxxx-ci2.xxxxxx.local -> localhost]: FAILED! => {
    "changed": false,
    "dest": "/etc/ansible/inventories/*******/abc/files/xxxxxx-ci2.xxxxxx.local/ssl/PKI-CHAIN.p7b",
    "failed": true,
    "gid": 1102,
    "group": "*********",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/etc/ansible/inventories/*******/xxxxx/files/xxxxx-ci2.xxxxxx.local/ssl/PKI-CHAIN.p7b",
            "directory_mode": null,
            "follow": false,
            "force": true,
            "force_basic_auth": true,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "https://10.1.3.96/certsrv/certnew.p7b?ReqID=CACert&Renewal=0&Mode=inst&Enc=b64",
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "url_username": "Cert_Ansible",
            "use_proxy": true,
            "validate_certs": false
        }
    },
    "mode": "0664",
    "msg": "Request failed",
    "owner": "*******",
    "response": "HTTP Error 401: Unauthorized",
    "size": 8402,
    "state": "file",
    "status_code": 401,
    "uid": 1101,
    "url": "https://10.1.3.96/certsrv/certnew.p7b?ReqID=CACert&Renewal=0&Mode=inst&Enc=b64"
}
```
