### ISSUE TITLE
os_nova_flavor module missing ability to update existing flavors

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#35284]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

os_nova_flavor

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/hccdev/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The os_nova_flavor module currently misses the ability to update existing flavors [[1]](https://groups.google.com/forum/#!topic/ansible-project/3lcvd61SvoM).

Horizon implements in by simply deleting the old flavor and creating a new one [[2]](https://github.com/openstack/horizon/blob/b0f3ec3ace531c110f328d208cded302d2617f88/openstack_dashboard/dashboards/admin/flavors/workflows.py#L304-L309).
It would be great to have this ability in the module as well.  

##### STEPS TO REPRODUCE

```yaml
   - name: Update flavor
     os_nova_flavor:
       name: existing_flavor
       vcpus: 1
       ram: 512
       disk: 10
       ephemeral: 0
       is_public: true
       state: present
```

##### EXPECTED RESULTS

The flavor `existing_flavor` should get updated with the new configuration.

##### ACTUAL RESULTS

The flavor `existing_flavor` is unchanged.
