### ISSUE TITLE
ovirt_networks: management network modification fails, API complains about unsetting management property

### ISSUE THREAD

**Issue by djasa** [ansible/ansible#35286]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ovirt_networks module

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/djasa/$PROJECT_DIR/ansible.cfg
  configured module search path = [u'/home/djasa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan 11 2018, 14:45:11) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/djasa/$PROJECT_DIR/ansible.cfg) = [u'/home/djasa/$PROJECT_DIR/inventory/hosts']
DEFAULT_ROLES_PATH(/home/djasa/$PROJECT_DIR/ansible.cfg) = [u'/home/djasa/$PROJECT_DIR/roles']
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

ovirt_networks: management network modification fails, API complains about unsetting management property

##### STEPS TO REPRODUCE

Playbook that sets up network:
```yaml
  - name: set up networks
    ovirt_networks:
      auth: "{{ ovirt_auth }}"
      name: "{{ item.name }}"
      data_center: "{{ item.data_center }}"
      state: "{{ item.state | default('present') }}"
      clusters: "{{ item.clusters }}"
      mtu: "{{ item.mtu | default('9000') }}"
      vlan_tag: "{{ item.vlan_tag | default(omit) }}"
      vm_network: "{{ item.vm_network | default(omit) }}"
    with_items: "{{ logical_networks }}"
```
is fed with this configuration file:
```yaml
- name: ovirtmgmt
  data_center: Default
  clusters:
  - name: Default
    assigned: True
    required: True
    display: True
    migration: True
  mtu: 1500
  vm_network: no
```
In other words, playbook doesn't intend to change network's management status, nor does module documentation state that such thing is possible, so…

##### EXPECTED RESULTS

I expected this module would just have vm_network set to False and be noop otherwise. But…

##### ACTUAL RESULTS

I keep getting this error (with -vvvv). Maybe the module should and maybe expose the management network setting?

```
TASK [set up networks] *****************************************************************************************************************************
task path: /home/djasa/$PROJECT_DIR/playbooks/rhv_setup.yml:84
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_networks.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: djasa
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/djasa/.ansible/tmp/ansible-tmp-1516804483.42-158332527802812 `" && echo ansible-tmp-1516804483.42-158332527802812="` echo /home/djasa/.ansible/tmp/ansible-tmp-1516804483.42-158332527802812 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp4CY5hD TO /home/djasa/.ansible/tmp/ansible-tmp-1516804483.42-158332527802812/ovirt_networks.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/djasa/.ansible/tmp/ansible-tmp-1516804483.42-158332527802812/ /home/djasa/.ansible/tmp/ansible-tmp-1516804483.42-158332527802812/ovirt_networks.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/djasa/.ansible/tmp/ansible-tmp-1516804483.42-158332527802812/ovirt_networks.py; rm -rf "/home/djasa/.ansible/tmp/ansible-tmp-1516804483.42-158332527802812/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_xNLAwT/ansible_module_ovirt_networks.py", line 254, in main
    ret = cluster_networks_module.create()
  File "/tmp/ansible_xNLAwT/ansible_modlib.zip/ansible/module_utils/ovirt.py", line 550, in create
    **update_params
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/services.py", line 3620, in update
    return self._internal_update(network, headers, query, wait)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 244, in _internal_update
    return future.wait() if wait else future
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 53, in wait
    return self._code(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 241, in callback
    self._check_fault(response)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 123, in _check_fault
    self._raise_error(response, body)
  File "/usr/lib64/python2.7/site-packages/ovirtsdk4/service.py", line 109, in _raise_error
    raise error
Error: Fault reason is "Operation Failed". Fault detail is "[Cannot edit Network. Unsetting management network property is not allowed. It is done automatically when moving the role to another network.]". HTTP response code is 400.

failed: [localhost] (item={u'clusters': [{u'assigned': True, u'required': True, u'display': True, u'name': u'Default', u'migration': True}], u'data_center': u'Default', u'name': u'ovirtmgmt', u'vm_network': False, u'mtu': 1500}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "clusters": [
                {
                    "assigned": true, 
                    "display": true, 
                    "migration": true, 
                    "name": "Default", 
                    "required": true
                }
            ], 
            "comment": null, 
            "data_center": "Default", 
            "description": null, 
            "fetch_nested": false, 
            "mtu": 1500, 
            "name": "ovirtmgmt", 
            "nested_attributes": [], 
            "poll_interval": 3, 
            "state": "present", 
            "timeout": 180, 
            "vlan_tag": null, 
            "vm_network": false, 
            "wait": true
        }
    }, 
    "item": {
        "clusters": [
            {
                "assigned": true, 
                "display": true, 
                "migration": true, 
                "name": "Default", 
                "required": true
            }
        ], 
        "data_center": "Default", 
        "mtu": 1500, 
        "name": "ovirtmgmt", 
        "vm_network": false
    }
}

MSG:

Fault reason is "Operation Failed". Fault detail is "[Cannot edit Network. Unsetting management network property is not allowed. It is done automatically when moving the role to another network.]". HTTP response code is 400.
```
