### ISSUE TITLE
template validation fails with isc-dhcp-server

### ISSUE THREAD

**Issue by pete-webpagetech** [ansible/ansible#35323]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template
copy

##### ANSIBLE VERSION
```
ansible 2.4.2.0
executable location = /opt/local/bin/ansible
python version = 3.6.3 (default, Oct  5 2017, 23:34:28) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### OS / ENVIRONMENT
ansible host = macOS Sierra 10.12.6   or same results from other hosts
ansible target = ubuntu server 16.04.3

##### SUMMARY
While using the template or copy modules validation fails on valid config files.

using ANSIBLE_KEEP_REMOTE_FILES=1 and then testing the config file on the server always failed no matter what I changed the file permissions/ownership to or even ran the validation as root.  Eventually I found out that the validation will only return 0 if the file that dhcpd is testing is in the /etc/dhcp directory.

We need a option in the template module to cp the test file to a specific directory instead of in ~/.ansible/tmp/ansible-tmp-.../source

error:
Can't open ~/.ansible/tmp/ansible-tmp-.../source: Permission denied

##### STEPS TO REPRODUCE

```yaml
- name: Template - dhcpd.conf
  template: 
    src: dhcpd.conf.j2
    dest: /etc/dhcp/dhcpd.conf
    owner: root
    group: root
    mode:  0644
    validate: /usr/sbin/dhcpd -t -cf %s
    backup: yes
```

##### EXPECTED RESULTS
validation works and file is replaced in /etc/dhcp/

##### ACTUAL RESULTS
validation error
