### ISSUE TITLE
Q: ec2 module: pass item with all key:vals to RunInstances

### ISSUE THREAD

**Issue by Eduard3000** [ansible/ansible#35336]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ec2
##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 14 2017, 15:45:21) [GCC 6.4.0]

```

##### CONFIGURATION
"[]"

##### OS / ENVIRONMENT
Linux ccdae8094455 4.14.14-041414-generic #201801201219 SMP Sat Jan 20 12:20:41 UTC 2018 x86_64 Linux
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.7.0
PRETTY_NAME="Alpine Linux v3.7"
HOME_URL="http://alpinelinux.org"
BUG_REPORT_URL="http://bugs.alpinelinux.org"
running inside 
Docker version 1.13.1, build 092cba3

##### SUMMARY
I would like to do the following:

    - name: ec2 create loop
      ec2: 
        - "{{ item }}"
      with_items: "{{ dat.ecs }}"

where dat.ecs is and array of hashes [{},{},...] with all the key value pairs needed/required to create a new ec2 instance.

##### STEPS TO REPRODUCE
its prob a feature request, the basic idea, seperate config from code, or the what from the how

```yaml
    - name: ec2 create loop
      ec2: 
        - "{{ item }}"
      with_items: "{{ dat.ecs }}"
```

##### EXPECTED RESULTS
create all ec instances defined found in the []

##### ACTUAL RESULTS
```
The offending line appears to be:


    - name: ec2 create loop
      ^ here

exception type: <class 'ansible.errors.AnsibleParserError'>
exception: unexpected parameter type in action: <class 'ansible.parsing.yaml.objects.AnsibleSequence'>

```
any insight would be appreciated, the docs dont show this case

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @tgerla @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Here are the docs for loops: http://docs.ansible.com/ansible/latest/playbooks_loops.html#looping-over-hashes

You probably just need to remove the `-` in front of the dictionary. Ansible can do this:
```
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    instance_hash:
      region: us-east-1
      key_name: mykey
      group_id: sg-xxxxxxxx
      instance_type: t2.micro
      image: ami-0b33d91d
      vpc_subnet_id: subnet-xxxxxxxx
      private_ip: 172.31.74.159
      instance_tags:
        Type: Test
      exact_count: 1
      count_tag:
        Type: Test
      assign_public_ip: true
      volumes: []
      wait: true
      ebs_optimized: false
  tasks:
    - name: Provision EC2 instances
      ec2:
        "{{ item }}"
      with_items:
        - "{{ instance_hash }}"
```
__but__ using variables for task parameters is unsafe and this feature will be removed in version 2.6.

A better way to do it would be:
```
  vars:
    instance_hash:
      key_name: mykey
      group_id: sg-xxxxxxxx
      instance_type: t2.micro
      image: ami-0b33d91d
      vpc_subnet_id: subnet-xxxxxxxx
      private_ip: 172.31.74.159
      instance_tags:
        Type: Test
      exact_count: 1
      count_tag:
        Type: Test
      assign_public_ip: true
      volumes: []
      wait: true
      ebs_optimized: false
  tasks:
    - name: Provision EC2 instances
      ec2:
        region: us-east-1
        key_name: "{{ item.key_name }}"
        group_id: "{{ item.group_id }}"
        instance_type: "{{ item.instance_type }}"
        image: "{{ item.image }}"
        vpc_subnet_id: "{{ item.vpc_subnet_id }}"
        private_ip: "{{ item.private_ip }}"
        instance_tags: "{{ item.instance_tags }}"
        exact_count: "{{ item.exact_count }}"
        count_tag: "{{ item.count_tag }}"
        assign_public_ip: "{{ item.assign_public_ip }}"
        volumes: "{{ item.volumes }}"
        wait: "{{ item.wait }}"
        ebs_optimized: "{{ item.ebs_optimized }}"
      with_items:
        - "{{ instance_hash }}"
```
where you hardcode the input parameters.
