### ISSUE TITLE
ecs_service_facts failed with python3

### ISSUE THREAD

**Issue by Geronimmo** [ansible/ansible#35334]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- Python 3.5.2
- boto 2.48.0
- boto3 1.5.19
- botocore 1.8.33

- module: ecs_service_facts 

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

ubuntu 16.04

##### SUMMARY

Module can`t get detail info. if use "ansible_python_interpreter: '/usr/bin/python3' ", module ecs_service_facts failed. But with python 2.7.12 no problem.

##### STEPS TO REPRODUCE

```
  - name: get cluster service details
    ecs_service_facts:
      region: "us-east-1"
      cluster: "my-cluster"
      service: "my-service"
      details: true
    register: service_facts
    ignore_errors: yes
```

##### ACTUAL RESULTS

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_tse6m3il/ansible_module_ecs_service_facts.py\", line 234, in <module>\n    main()\n  File \"/tmp/ansible_tse6m3il/ansible_module_ecs_service_facts.py\", line 230, in main\n    module.exit_json(**ecs_facts_result)\n  File \"/tmp/ansible_tse6m3il/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2279, in exit_json\n  File \"/tmp/ansible_tse6m3il/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2272, in _return_formatted\n  File \"/tmp/ansible_tse6m3il/ansible_modlib.zip/ansible/module_utils/basic.py\", line 514, in remove_values\n  File \"/tmp/ansible_tse6m3il/ansible_modlib.zip/ansible/module_utils/basic.py\", line 497, in _remove_values_conditions\nTypeError: Value of unknown type: <class 'map'>, <map object at 0x7fe2757557b8>\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```

```
