### ISSUE TITLE
Allow the definition of a fallback value when loading of include_vars fails.

### ISSUE THREAD

**Issue by funkyfuture** [ansible/ansible#35347]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
`include_vars`

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = [u'/home/user/ansible/hosts']
DEFAULT_REMOTE_USER(/home/user/.ansible.cfg) = janitor
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /obfuscated
```

##### OS / ENVIRONMENT
`N/A`

##### SUMMARY
it seems unnecessary complicated to define a fallback value when variable could not be loaded from a file (e.g. it doesn't exist) with an `include_vars` directive.

##### STEPS TO REPRODUCE

instead of this example:

```yaml
- include_vars:
    file: "redirects/{{ domain }}.yml"
    name: redirects
  ignore_errors: true
  register: load
- include_vars:
    file: empty.yml
    name: redirects
  when: load.failed
```

this would be much simpler:

```yaml
- include_vars:
    file: "redirects/{{ domain }}.yml"
    name: redirects
    on_error: {}
```

the usage of `set_fact` is ruled out as these variables are immutable. the usage of `include_vars` in conjunction with `with_first_found` didn't work as the latter didn't seem to pick any file (with prefixes for various possible search paths).

if approved, i can submit a patch for this.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/include_vars.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include_vars.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @linuxdynasty
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/include_vars.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/include_vars.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@funkyfuture I think this can be achieved using setting default for all variables in a separate file called `default.yaml` like - 

```yaml
- name: Load a variable file based on the OS type, or a default if not found. Using free-form to specify the file.
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yaml'
        - '{{ansible_os_family}}.yaml'
        - default.yaml
      paths:
        - 'vars'
```

Also, you can always use [`default`](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html#defaulting-undefined-variables) for undefined variables.

Closing this as per. Thanks.
