### ISSUE TITLE
ACI module to add static paths to EPG

### ISSUE THREAD

**Issue by nilloBE** [ansible/ansible#35340]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
aci_epg_to_domain

##### ANSIBLE VERSION
2.4

##### OS / ENVIRONMENT
Ansible 2.4 and ACI 3.1(1) or earlier releases.

##### SUMMARY
Currently aci_epg_to_domain allows the user to specify a VMM domain, and then APIC will take care of configuring the EPG and the right VLAN or VXLAN encapsulation on the right ACI switch ports.

It is also possible to select a Physical Domain. In that case, the user needs to specify a VLAN encapsulation and assign it to the ACI switch ports. Currently this is only possible via aci_rest. For instance, like this where we map EPG1 to  some vPC ports with an encapsulation provided in a variable (phys_encap):

```yaml
- name: adding static paths to EPG2
  aci_rest:
     hostname: "{{ inventory_hostname }}"
     username: "{{ user }}"
     private_key: /root/admin.key
     validate_certs: no
     use_proxy: no
     method: post
     path: api/mo/uni.json
     content:
        fvTenant:
           attributes:
              name: "AcmeTenant"
           children:
           - fvAp:
              attributes:
                 name: "AcmeNetworks"
              children:
              - fvAEPg:
                 attributes:
                    name: "EPG1"
                 children:
                 - fvRsPathAtt:
                    attributes:
                       encap: "{{ phys_encap }}"
                       instrImedcy: immediate
                       tDn: "{{ item }}"
  with_items:
      - "topology/pod-1/protpaths-105-106/pathep-[centos-vPC-1-27]"
      - "topology/pod-2/protpaths-2101-2102/pathep-[RHVH-02-vPC-1-5]"
  when: state == "present"
```
We should provide a way to do this in a module. This could be on aci_epg_to_domain, or perhaps better on a new module 'aci_epg_to_path".

We should take:
```yaml
epg: <epg-name>
encapsulation: <integer from 0-4096>
instrImedcy: < immediate |  on-demand>
tDn: <string with the Dn of the path>
```
This would be beneficial for customers using pure network centric mode without VMM integration or providing hosting services for physical services.
