### ISSUE TITLE
ERROR! A worker was found in a dead state

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#35344]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
v2.5

##### CONFIGURATION
```ini
[dag@moria crombeen]$ ansible-config dump --only-changed
CACHE_PLUGIN(/home/dag/home-made/crombeen/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/dag/home-made/crombeen/ansible.cfg) = ~/.ansible/crombeen.cache
CACHE_PLUGIN_TIMEOUT(/home/dag/home-made/crombeen/ansible.cfg) = 60480000
DEFAULT_CALLBACK_WHITELIST(/home/dag/home-made/crombeen/ansible.cfg) = ['mail']
DEFAULT_FORKS(/home/dag/home-made/crombeen/ansible.cfg) = 25
DEFAULT_GATHERING(/home/dag/home-made/crombeen/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/dag/home-made/crombeen/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/dag/home-made/crombeen/ansible.cfg) = [u'/home/dag/home-made/crombeen/hosts.ini']
DEFAULT_REMOTE_USER(/home/dag/home-made/crombeen/ansible.cfg) = ictadmin
DEFAULT_SSH_TRANSFER_METHOD(/home/dag/home-made/crombeen/ansible.cfg) = piped
DEFAULT_TRANSPORT(/home/dag/home-made/crombeen/ansible.cfg) = winrm
RETRY_FILES_ENABLED(/home/dag/home-made/crombeen/ansible.cfg) = False
```

##### SUMMARY
The following playbook suddenly (after a few smaller changes)

```yaml
- hosts: computers
  gather_facts: no

  tasks:
  - name: Update facts cache
    setup:

  - name: Update product info
    win_product_facts:

  - name: Update disk info
    win_disk_facts:

  - name: Create CSV log entry
    set_fact:
      csv_entry: '{{ ansible_date_time.date }} {{ ansible_date_time.time }};{{ hostname }};{{ ansible_system_description }};{{ ansible_fqdn }};{{ ansible_os_name }};{{ ansible_distribution_version }};{{ ansible_architecture }};{{ macaddress }};{{ ip_address }};{{ ansible_processor[1] }};{{ memory }};{{ disk.bus_type }};{{ disk.model }};{{ disk_size }};"{{ ansible_system_vendor }}";{{ ansible_product_name }};{{ ansible_product_serial }};{{ ansible_bios_version }};{{ ansible_bios_date }};{{ product_id }};{{ product_key }};{{ ansible_lastboot }};{{ ansible_win_rm_certificate_expires }};'
    vars:
      hostname: '{{ ansible_hostname|upper }}'
      ip_address: '{{ ansible_ip_addresses|first }}'
      macaddress: '{{ (ansible_interfaces|first).macaddress|default(mac|default(""))|upper }}'
      disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
      disk_size: '{{ disk.size|filesizeformat }}'
      memory: '{{ ansible_memtotal_mb*1024*1024|filesizeformat }}'
      product_id: '{{ ansible_os_product_id|default("") }}'
      product_key: '{{ ansible_os_product_key|default("") }}'
```

result in this error:
```
[dag@moria crombeen]$ ansible-playbook collect.yml -l computer90,computer91

PLAY [computers] ***********************************************************************************
TASK [Update facts cache] **************************************************************************
ok: [computer91]
ok: [computer90]

TASK [Update product info] *************************************************************************
ok: [computer91]
ok: [computer90]

TASK [Update disk info] ****************************************************************************
ok: [computer90]
ok: [computer91]

TASK [Create CSV log entry] ************************************************************************
ERROR! A worker was found in a dead state
```

This is the output when running using `ANSIBLE_DEBUG=1`
```
 14510 1516882385.41567: running TaskExecutor() for computer91/TASK: Create CSV log entry
 14510 1516882385.41620: in run() - task 52540068-b24c-6ecd-9dae-000000000079
 14510 1516882385.41676: calling self._execute()
 14510 1516882385.42103: Loading FilterModule 'core' from /opt/anvers/default/lib/ansible/plugins/filter/core.py (found_in_cache=True, class_only=False)
 14510 1516882385.42135: Loading FilterModule 'ipaddr' from /opt/anvers/default/lib/ansible/plugins/filter/ipaddr.py (found_in_cache=True, class_only=False)
 14510 1516882385.42148: Loading FilterModule 'json_query' from /opt/anvers/default/lib/ansible/plugins/filter/json_query.py (found_in_cache=True, class_only=False)
 14510 1516882385.42163: Loading FilterModule 'mathstuff' from /opt/anvers/default/lib/ansible/plugins/filter/mathstuff.py (found_in_cache=True, class_only=False)
 14510 1516882385.42178: Loading FilterModule 'network' from /opt/anvers/default/lib/ansible/plugins/filter/network.py (found_in_cache=True, class_only=False)
 14510 1516882385.42189: Loading FilterModule 'urlsplit' from /opt/anvers/default/lib/ansible/plugins/filter/urlsplit.py (found_in_cache=True, class_only=False)
 14510 1516882385.42341: Loading TestModule 'core' from /opt/anvers/default/lib/ansible/plugins/test/core.py (found_in_cache=True, class_only=False)
 14510 1516882385.42351: Loading TestModule 'files' from /opt/anvers/default/lib/ansible/plugins/test/files.py (found_in_cache=True, class_only=False)
 14510 1516882385.42359: Loading TestModule 'mathstuff' from /opt/anvers/default/lib/ansible/plugins/test/mathstuff.py (found_in_cache=True, class_only=False)
 14510 1516882385.43839: Loading FilterModule 'core' from /opt/anvers/default/lib/ansible/plugins/filter/core.py (found_in_cache=True, class_only=False)
 14510 1516882385.43859: Loading FilterModule 'ipaddr' from /opt/anvers/default/lib/ansible/plugins/filter/ipaddr.py (found_in_cache=True, class_only=False)
 14510 1516882385.43869: Loading FilterModule 'json_query' from /opt/anvers/default/lib/ansible/plugins/filter/json_query.py (found_in_cache=True, class_only=False)
 14510 1516882385.43877: Loading FilterModule 'mathstuff' from /opt/anvers/default/lib/ansible/plugins/filter/mathstuff.py (found_in_cache=True, class_only=False)
 14510 1516882385.43884: Loading FilterModule 'network' from /opt/anvers/default/lib/ansible/plugins/filter/network.py (found_in_cache=True, class_only=False)
 14510 1516882385.43891: Loading FilterModule 'urlsplit' from /opt/anvers/default/lib/ansible/plugins/filter/urlsplit.py (found_in_cache=True, class_only=False)
 14510 1516882385.43922: Loading TestModule 'core' from /opt/anvers/default/lib/ansible/plugins/test/core.py (found_in_cache=True, class_only=False)
 14510 1516882385.43932: Loading TestModule 'files' from /opt/anvers/default/lib/ansible/plugins/test/files.py (found_in_cache=True, class_only=False)
 14510 1516882385.43940: Loading TestModule 'mathstuff' from /opt/anvers/default/lib/ansible/plugins/test/mathstuff.py (found_in_cache=True, class_only=False)
 14509 1516882387.17305: Loading Connection 'winrm' from /opt/anvers/default/lib/ansible/plugins/connection/winrm.py
 14509 1516882387.17368: Loading ShellModule 'powershell' from /opt/anvers/default/lib/ansible/plugins/shell/powershell.py
 14509 1516882387.17952: assigned :doc
 14509 1516882387.18143: Loaded config def from plugin (shell/powershell)
 14510 1516882387.19545: Loading Connection 'winrm' from /opt/anvers/default/lib/ansible/plugins/connection/winrm.py
 14510 1516882387.19758: Loading ShellModule 'powershell' from /opt/anvers/default/lib/ansible/plugins/shell/powershell.py
 14509 1516882387.20339: assigned :doc
 14509 1516882387.20426: Loaded config def from plugin (connection/winrm)
 14510 1516882387.20534: assigned :doc
 14509 1516882387.20542: Loading ActionModule 'set_fact' from /opt/anvers/default/lib/ansible/plugins/action/set_fact.py (found_in_cache=True, class_only=False)
 14510 1516882387.20579: Loaded config def from plugin (shell/powershell)
 14510 1516882387.22138: assigned :doc
 14510 1516882387.22231: Loaded config def from plugin (connection/winrm)
 14510 1516882387.22351: Loading ActionModule 'set_fact' from /opt/anvers/default/lib/ansible/plugins/action/set_fact.py (found_in_cache=True, class_only=False)
 14509 1516882387.51196: starting attempt loop
 14509 1516882387.51205: running the handler
 14510 1516882387.52182: starting attempt loop
 14510 1516882387.52195: running the handler
 14509 1516882388.23157: handler run complete
 14510 1516882388.23387: handler run complete
 14470 1516882393.16150: RUNNING CLEANUP
ERROR! A worker was found in a dead state
```

**Comment by dagwieers** [comment]
So it appears that the proccesses are being killed by the OOM killer, which is weird because the system has 5GB of physical memory free. I can tell it is being eaten up very quickly.

Now the below task does work:
```yaml
  - name: Create CSV log entry
    set_fact:
      csv_entry: '{{ ansible_date_time.date }} {{ ansible_date_time.time }};{{ ansible_hostname|upper }};{{ ansible_system_description }};{{ ansible_fqdn }};{{ ansible_os_name }};{{ ansible_distribution_version }};{{ ansible_architecture }};{{ macaddress }};{{ ansible_ip_addresses|first }};{{ ansible_processor[1] }};{{       memory: '{{ ansible_memtotal_mb }}' }};{{ disk.bus_type }};{{ disk.model }};{{ disk_size }};"{{ ansible_system_vendor }}";{{ ansible_product_name }};{{ ansible_product_serial }};{{ ansible_bios_version }};{{ ansible_bios_date }};{{ ansible_os_product_id|default("") }};{{ ansible_os_product_key|default("") }};{{ ansible_lastboot }};{{ ansible_win_rm_certificate_expires }};'                                                                     
    vars:
      macaddress: '{{ (ansible_interfaces|first).macaddress|default(mac|default(""))|upper }}'
      disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
      disk_size: '{{ disk.size|filesizeformat }}'
```

So going from 9 task vars to 3 task vars fixes this weird behavior.
