### ISSUE TITLE
meta module does not work for add_host module

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#35352]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
meta

##### ANSIBLE VERSION
N/A

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The module page http://docs.ansible.com/ansible/latest/meta_module.html is often mistaken for being able to refresh inventory.  The original problem I had on another bug (https://github.com/ansible/ansible/issues/35195) was that I would do something like this->
playbook.yml->
    - role1 (this role adds hosts via the add_host module)
    - role2 (this role simply checks for reachability of the newly added add_host hosts using the wait_for_connection)

The secondary role that tested connection seemed overly complicated (but it worked).  When I tried to combine the task wait_for_connection to the newly added hosts in `role1` it would not work.  The meta module was used as an attempt to figure out the problem.  The real problem is that you can't use delegate_to on a group.  The only way we could make this work would be a with_items, but that would serialize the playbook.  The original way I had it, where the wait_for_connection was on another role (or play) so could be applied to the group was the correct way.

It would have saved time if I knew meta module refresh_inventory is NOT for add_host.  The add_host will work immediately after you use it, however you can't use the `group` that those hosts are within the same play, which can be confusing.

##### STEPS TO REPRODUCE
See bug: https://github.com/ansible/ansible/issues/35195

##### EXPECTED RESULTS
add_host CAN work with delegate_to, but delegate_to won't work for a group

I thought I could do something like this
```
- add_host:
    name: "{{ ip_address }}"
    groups: just_created
    foo: 42
- add_host:
    name: "{{ ip_address2 }}"
    groups: just_created
    foo: 42
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
  delegate_to: just_created
```

This is NOT possible.  I then tried to use the meta module between the add_host and the wait_for_connection and that is also NOT helpful because its not for the add_host module.

##### ACTUAL RESULTS
The delegate_to didn't ever work because you can't delegate to a group.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/helper/meta.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/helper/meta.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

In any case, the meta: refresh_inventory is designed to REMOVE any add_hosts/group_by in the play and go back to the original inventory and reread it.

As for the `delegate_to` limitation:
```
- name: Wait 600 seconds for target connection to become reachable/usable
  wait_for_connection:
  delegate_to:  '{{item}}'
  with_items: "{{groups['just_created']}}"
```
