### ISSUE TITLE
hpilo_facts and hpilo_boot modules broken with new python-hpilo Python module

### ISSUE THREAD

**Issue by rsevilla87** [ansible/ansible#35373]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
hpilo_boot and hpilo_facts modules

##### ANSIBLE VERSION
2.4.2.0

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/ansible-ssh-%%C
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']

##### OS / ENVIRONMENT
From Fedora release 27 (Twenty Seven)
Managing RHEL 7.4

##### SUMMARY
hpilo_boot and hpilo_facts modules does not work with the current version of python-hpilo module. 

Taking a look to this underlying module, seems like it's interface has changed and the Ilo class needs to be instantiated in other way since it uses ssl_context to detect the SSL version.

##### STEPS TO REPRODUCE
Use hpilo_boot or hpilo_facts with python-hpilo >= 4.1

```yaml
- hosts: all                                        
  gather_facts: no                                  
  tasks:                                            
    - name: Task to boot a system using an ISO from an HP iLO interface only if the system is an HP server
      hpilo_boot:                                                                                        
        host: ilo.example.com                       
        login: admin
        password: password
        media: cdrom
        image: http://some-web-server/iso/boot.iso


```

##### EXPECTED RESULTS
The module works properly

##### ACTUAL RESULTS
```
TASK [Task to boot a system using an ISO from an HP iLO interface only if the system is an HP server] *************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: __init__() got an unexpected keyword argument 'ssl_version'
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_eb9u8b/ansible_module_hpilo_boot.py\", line 208, in <module>\n    main()
\n  File \"/tmp/ansible_eb9u8b/ansible_module_hpilo_boot.py\", line 149, in main\n    ilo = hpilo.Ilo(host, login=login, password=password, ssl_version=ssl_version)\nTypeError: __init__() got an unexpected keywo
rd argument 'ssl_version'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```
