### ISSUE TITLE
delegate_to not propagated to include_role

### ISSUE THREAD

**Issue by marcindulak** [ansible/ansible#35398]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

delegate_to
include_role

##### ANSIBLE VERSION

Ansible devel https://github.com/ansible/ansible/commit/f849dc9cad93f512554823fe3f26f171b45dfcf9
```
ansible 2.5.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

default

##### OS / ENVIRONMENT

CentOS7

##### SUMMARY

This issue is maybe related to https://github.com/ansible/ansible/issues/18315

CentOS7 ansible-2.4.2.0-1.el7.noarch does not have this problem

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

```
# tree .
.
├── failed_role
│   └── tasks
│       └── output.yml
└── playbook.yml
```

```
# cat failed_role/tasks/output.yml 
- name: output from role
  shell: hostname&& ls /tmp/failed_role
```

```
# cat playbook.yml 
- hosts: all

  tasks:

  - name: output from playbook
    shell: hostname&& ls /tmp/failed_role
    delegate_to: localhost

  - name: delegate to task_from
    include_role:
      name: failed_role
      private: yes
      tasks_from: output.yml
    delegate_to: localhost
```

##### EXPECTED RESULTS

Actually I'm not sure if the result below is really expected.

```
# hostname
localhost
```

```
# touch /tmp/failed_role
```

```
# ansible-playbook playbook.yml --limit remote1 -v
Using /etc/ansible/ansible.cfg as config file

PLAY [all] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [remote1]

TASK [output from playbook] *******************************************************************************************************************************************************************
changed: [remote1 -> localhost] => {"changed": true, "cmd": "hostname&& ls /tmp/failed_role", "delta": "0:00:00.004367", "end": "2018-01-26 15:11:33.617182", "rc": 0, "start": "2018-01-26 15:11:33.612815", "stderr": "", "stderr_lines": [], "stdout": "remote1\n/tmp/failed_role", "stdout_lines": ["remote1", "/tmp/failed_role"]}

TASK [delegate to task_from] ******************************************************************************************************************************************************************

TASK [failed_role : output from role] *********************************************************************************************************************************************************
changed: [remote1 -> localhost] => {"changed": true, "cmd": "hostname&& ls /tmp/failed_role", "delta": "0:00:00.004503", "end": "2018-01-26 15:11:33.857299", "rc": 0, "start": "2018-01-26 15:11:33.852796", "stderr": "", "stderr_lines": [], "stdout": "remote1\n/tmp/failed_role", "stdout_lines": ["remote1", "/tmp/failed_role"]}

PLAY RECAP ************************************************************************************************************************************************************************************
remote1           : ok=3    changed=2    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

```
# hostname
localhost
```

```
# touch /tmp/failed_role
```

```
# ansible-playbook playbook.yml --limit remote1 -v
Using /etc/ansible/ansible.cfg as config file

PLAY [all] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [remote1]

TASK [output from playbook] *******************************************************************************************************************************************************************
changed: [remote1 -> localhost] => {"attempts": 1, "changed": true, "cmd": "hostname&& ls /tmp/failed_role", "delta": "0:00:00.004970", "end": "2018-01-26 15:13:01.661383", "failed": false, "rc": 0, "start": "2018-01-26 15:13:01.656413", "stderr": "", "stderr_lines": [], "stdout": "localhost\n/tmp/failed_role", "stdout_lines": ["localhost", "/tmp/failed_role"]}

TASK [delegate to task_from] ******************************************************************************************************************************************************************

TASK [failed_role : output from role] *********************************************************************************************************************************************************
fatal: [remote1]: FAILED! => {"attempts": 1, "changed": true, "cmd": "hostname&& ls /tmp/failed_role", "delta": "0:00:00.004670", "end": "2018-01-26 15:13:01.988267", "failed": true, "msg": "non-zero return code", "rc": 2, "start": "2018-01-26 15:13:01.983597", "stderr": "ls: cannot access /tmp/failed_role: No such file or directory", "stderr_lines": ["ls: cannot access /tmp/failed_role: No such file or directory"], "stdout": "remote1", "stdout_lines": ["remote1"]}
	to retry, use: --limit @/delegate_to_not_propagated/playbook.retry

PLAY RECAP ************************************************************************************************************************************************************************************
remote1           : ok=2    changed=1    unreachable=0    failed=1 
```

Is there a standard way to prepare and submit such cases so they get included in Ansible's CI in order to avoid regressions?

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/role/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)
* [lib/ansible/playbook/task.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by marcindulak** [comment]
**a comment providing incorrect information removed**

**Comment by marcindulak** [comment]
Well, or maybe I leave it open and let you decide

**Comment by sivel** [comment]
This is the expected behavior in 2.5.  In 2.5 attributes applied to a dynamic include are only applied to the include itself, and not to the tasks within.

See https://github.com/ansible/ansible/pull/35199

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by AndiDog** [comment]
As I understand this, the `delegate_to` attribute for dynamic includes (`include_*`) is simply swallowed and ignored. That's pretty annoying to debug, and probably should lead to a warning to help developers.

**Comment by amarao** [comment]
I would say this is a huge issue. If Ansible would have raised an error for combination of `delegate_to` and `include_role`, that would be sad, but normal. But Ansible after upgrade from 2.4 to 2.5 silently ignores `delegate_to` and makes changes on a wrong server. It's like surgeon whom amputates a leg for a wrong patient. If the patient complains afterwards, surgeon answers, 'this is expected behavior'.

There is  literally nothing in changelog for such a huge change. Moreover, even in the documentation for delegation and `include_role` there is not a single word about this.

**Comment by fabrizio2210** [comment]
My role now is broken for this issue.
Is there any workaround?
[EDIT]
I found, I have to use import_role and then it works as before

**Comment by amarao** [comment]
Import_role does not support with loops.

For loops and include_role and delegate combined, there is a workaround: https://medium.com/opsops/ansible-2-5-delegate-to-and-include-role-20cd7e67008e

(use loop+include, then delegate+import)

**Comment by BarbzYHOOL** [comment]
But what is the reason for this? The workaround is obvious but it's damn stupid to be forced to do that.

Could add an option "inherit: yes"

**Comment by LukeShortCloud** [comment]
It looks like the future Ansible 2.7 (currently devel) partially has this feature implemented. You still have to manually re-apply become/tags/etc. settings.

```
apply (added in 2.7) |   | Accepts a hash of task keywords (e.g. tags, become) that will be applied to the tasks within the include.
```

https://docs.ansible.com/ansible/devel/modules/include_role_module.html

**Comment by rene1977** [comment]
Very unprofessional behavior to make silent such kind of changes. And even not logical because i guess someone puting attributes there expects that they get applied for this include.

**Comment by rhino5oh** [comment]
@ekultails have you figured out how to solve this issue with 'apply'? I've tried a few things and was not able to get it to work with ansible 2.7.0a1

One thing I attempted was:

```
- name: "Running geerlingguy.kubernetes role"
  include_role:
    name: geerlingguy.kubernetes
    apply:
      delegate_to: "{{ item }}"
  with_items:
    - "{{ groups['cluster_group'] }}"
```

Also tried nesting the with_items under apply and got an error.

Ideally, I would think that this should work.  No special 'apply' or anything.  Just trying to delegate the task to multiple hosts.  But this does not work either:

```
 - name: "Running geerlingguy.kubernetes role"
   include_role:
     name: geerlingguy.kubernetes
   delegate_to: "{{ item }}"
   with_items:
     - "{{ groups['cluster_group'] }}"
```

**Comment by geerlingguy** [comment]
@rhino5oh - Funny that I hit the same issue doing something almost identical to what you're doing.

I agree with others above that it's weird that it works fine with `import_role`, but doesn't with `include_role`, and it's not obvious (a) why it works with one and not the other, and (b) why it doesn't throw an error. I've spent an hour trying to debug it before I finally came to this issue :P

**Comment by BarbzYHOOL** [comment]
> I've spent an hour trying to debug it before I finally came to this issue :P

seems like a recurring pattern with ansible xD (still i love it)

**Comment by sivel** [comment]
@geerlingguy This has been resolved for the 2.8 release as part of https://github.com/ansible/ansible/pull/46177

Also note that `include_X` and `import_X` are still in tech preview, and we are working towards getting these features ready to become stable. This is one of those changes necessary to get us there.

```
ERROR! 'delegate_to' is not a valid attribute for a TaskInclude

The error appears to be in '/Users/matt/projects/ansibledev/playbooks/include_delegate.yml': line 4, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  tasks:
    - include_tasks: include_me.yml
      ^ here
```

**Comment by rhino5oh** [comment]
@sivel I just want to make sure I understand.  So you're saying that this should work in 2.8?  (assume cluster_group is a properly defined host group)


```
 - name: "Running geerlingguy.kubernetes role"
   include_role:
     name: geerlingguy.kubernetes
   delegate_to: "{{ item }}"
   with_items:
     - "{{ groups['cluster_group'] }}"
```

**Comment by bcoca** [comment]
@rhino5oh no, but it will give you a proper error, you want the following instead:
```
 - name: "Running geerlingguy.kubernetes role"
   include_role:
     name: geerlingguy.kubernetes
     apply:
        delegate_to: "{{ item }}"
   with_items:
     - "{{ groups['cluster_group'] }}"
```

**Comment by sivel** [comment]
> So you're saying that this should work in 2.8?

No, I am saying that in 2.8 you will properly result in an error, as `delegate_to` has no use on an `include_role` and is disallowed.

Instead what you want on 2.7+ is:

```
 - name: "Running geerlingguy.kubernetes role"
   include_role:
     name: geerlingguy.kubernetes
     apply:
       delegate_to: "{{ item }}"
   with_items:
     - "{{ groups['cluster_group'] }}"
```

In 2.5 we made a distinction between `include_X` and `import_X` in how attributes worked (This is discussed further above and in more detail at https://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#dynamic-includes-and-attribute-inheritance).  On `import_X` attributes are applied down onto the tasks within, on `include_X` they only apply to the include, and `delegate_to` on just the `include_X` makes no sense. In 2.7 we added a way to also impact the tasks within using the `apply` argument.

**Comment by geerlingguy** [comment]
> On import_X attributes are applied down onto the tasks within, on include_X they only apply to the include, and delegate_to on just the include_X makes no sense. In 2.7 we added a way to also impact the tasks within using the apply argument.

I think I finally understand the distinction. Took long enough :D

**Comment by sivel** [comment]
> I think I finally understand the distinction

It's no doubt complicated, and we have been working towards outlining it better and delineating functionality in a way that should help. Hopefully the new errors in 2.8 will help.  We're moving from a "magical" implementation of "include" to something that will be easier to describe, but it hasn't been the most smooth transition.

If I can clarify anything further, feel free to swing by IRC and ping me there.

Some additional reading:

https://docs.ansible.com/ansible/latest/user_guide/playbooks_reuse.html

**Comment by rhino5oh** [comment]
This still does not work completely in the way I would expect it to when it comes to passing in vars.  For example, I have this:

```
  - name: "Running geerlingguy.docker role"
    include_role:
      name: geerlingguy.docker
      apply:
        delegate_to: "{{ item }}"
    vars:
      docker_package: "{{ docker_version }}"
    with_items:
      - "{{ groups['cluster_group'] }}"
```

So, I'm trying to pass in vars to geerlingguy.docker.  More specifically, the docker version.  When doing delegate_to, it appears to be attempting to apply the task to the original host as well as the hosts I'm delegating to.  I'm getting this error:

![screen shot 2019-02-04 at 3 59 06 pm](https://user-images.githubusercontent.com/4404630/52236968-518e5a80-2896-11e9-9bc4-2503a06c0a7e.png)

Notice the 127.0.0.1 -> [blacked out host im delegating to]

On the Install Docker task, it cannot find the package 'docker-ce-17.03.3*' on my local machine, which makes sense.  Install docker is doing this:

```
- name: Install Docker.
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
notify: restart docker
```

And I'm on MacOS.  The host I'm delegating_to however, is CentOS7.  If I do not do a delegate_to, and run directly against my host, it finds the package correctly.  So it appears that, even though I'm delegating to, its doing something on my local machine still.  Unless I have some syntax wrong?
