### ISSUE TITLE
os_server module does not create Floating IP when wait is set to no

### ISSUE THREAD

**Issue by pritho** [ansible/ansible#35392]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

os_server

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### OS / ENVIRONMENT

CentOS 7.4

##### SUMMARY

os_server module does not create Floating IP (based upon param auto_ip) when wait is set to no
##### STEPS TO REPRODUCE

use module os_server with param wait: no and auto_ip: yes
--> instance is being created, but no floating IP is being assigned; 
      the floating ip is then assigned in a second run of the playbook
if wait is set to yes, the floating IP is being assigned, but this increases time for larger deployments significantly

```yaml
- name: "Launch OpenStack compute instance"
  os_server:
    state: "present"
    name: "test"
    availability_zone: "{{ availability_zone }}"
    image: "{{ image }}"
    key_name: "{{ ssh_keypair }}"
    flavor: "m1.small"
    delete_fip: yes
    auto_ip: yes
    network: "{{ net_name }}"
    security_groups: default
    wait: no
```

##### ACTUAL RESULTS

```

```
