### ISSUE TITLE
infoblox dynamic inventory truncates extensible attributes

### ISSUE THREAD

**Issue by clementtrebuchet** [ansible/ansible#35409]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel_infoblox_exattrs 01091cddf6) last updated 2018/01/26 21:41:03 (GMT +200)
  config file = /home/clement/Documents/PROJECTS/ansible_env_setup/ansible/ansible.cfg
  configured module search path = ['/home/clement/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/clement/Documents/PROJECTS/ansible_env_setup/ansible/lib/ansible
  executable location = /home/clement/Documents/PROJECTS/ansible_env_setup/ansible/bin/ansible
  python version = 3.6.3 (default, Oct  9 2017, 12:07:10) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### OS / ENVIRONMENT

Fedora release 27 (Twenty Seven)
##### SUMMARY

As a network engineer, I need to be able to have the complete list of extensible attributes in my inventory and not a truncated list

The inventory produced by the infoblox inventory script is incomplete. Indeed, we should have the list of complete extensible attributes for each record, a minor bug overwrites the extensible attributes dictionary, the result is in the extensible attributes dictionary with only one entry.
##### STEPS TO REPRODUCE

python infoblox.py --list

```yaml
---
# This file provides the configuration information for the Infoblox dynamic
# inventory script that is used to dynamically pull host information from NIOS.
# This file should be copied to /etc/ansible/infoblox.yaml in order for the
# dynamic script to find it.

# Sets the provider arguments for authenticating to the Infoblox server to
# retrieve inventory hosts.  Provider arguments can also be set using
# environment variables.  Supported environment variables all start with
# INFOBLOX_{{ name }}.  For instance, to set the host provider value, the
# environment variable would be INFOBLOX_HOST.
provider:
  host: <SERVER_IP>
  username: <USERNAME>
  password: <PASSWORD>

# Filters allow the dynamic inventory script to restrict the set of hosts that
# are returned from the Infoblox server.
filters:
  # restrict returned hosts by extensible attributes
  extattrs: {'IN_DeviceType': 'ACCESS', 'IN_Service': 'CAMPUS', 'IN_Country': FR', 'IN_Owner': 'LAN'}, 

  # restrict returned hosts to a specified DNS view
  view: default
```

##### EXPECTED RESULTS

```json
"XXXX.XXXXX.com": {

                "extattrs": {

                    "IN_Vendor": "XXX",

                    "IN_Country": "XXX",

                    "IN_Service": "XXX",

                    "IN_Site": "XXX",

                    "IN_DeviceType": "XXX",

                    "IN_Owner": "XXX"

                },

                "view": "default"
```
##### ACTUAL RESULTS

```json
 "XXXX.XXXXX.com": {
        "extattrs": {
            "IN_Owner": "XXX"
        }, 
        "view": "default"
    }, 
```

```

```
