### ISSUE TITLE
service module doesn't take into account use option nor ansible_service_mgr override

### ISSUE THREAD

**Issue by ksmets** [ansible/ansible#35418]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
service module, docker connection

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = ['/home/ksmets/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ksmets/.virtualenvs/ansible/lib/python3.5/site-packages/ansible
  executable location = /home/ksmets/.virtualenvs/ansible/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Ubuntu 16.04.3 LTS

##### SUMMARY
As part of a CI/CD pipeline, I'm testing my ansible roles using docker containers via `ansible_connection=docker`. However, I can't trick the service module  to (re)start, reload or stop services in tasks or handlers.

This definitely related to #30192, but until that issue is resolved the service module should act like the documentation prescribes, e.g. allow override of ansible_service_mgr variable. 

In `modules/system/service.py` the documentation refers to both `use` option or `ansible_service_mgr` variable, but nowhere these are used in the code.

The problem is that when for example using the current ubuntu docker image. The following part of the code is executed.

``` python
elif location.get('initctl', False) and os.path.exists("/etc/init/%s.conf" % self.name):
            # service is managed by upstart
            self.enable_cmd = location['initctl']
            # set the upstart version based on the output of 'initctl version'
            self.upstart_version = LooseVersion('0.0.0')
            try:
                version_re = re.compile(r'\(upstart (.*)\)')
                rc,stdout,stderr = self.module.run_command('%s version' % location['initctl'])
                if rc == 0:
                    res = version_re.search(stdout)
                    if res:
                        self.upstart_version = LooseVersion(res.groups()[0])
            except:
                pass  # we'll use the default of 0.0.0

            self.svc_cmd = location['initctl']
```

After that `self.svc_cmd` refers to the `initctl` binary (useless in container). My problem would be solved if I would be able to force to set `self.svc_cmd = location['service']` either by specifying use option or preferably by setting ansible_service_mgr so service in the inventory file.

##### STEPS TO REPRODUCE

My `inventory` files look like:
```
localhost ansible_connection=local
ansible_nginx ansible_connection=docker

[all:vars]
ansible_python_interpreter='/usr/bin/env python3'
```

My `test.yml` playbooks look like
```yaml
---
- hosts: localhost
  pre_tasks:
  - name: install required python packages for Ansible
    pip: name={{ item }} state=latest
    with_items:
    - docker-compose
  tasks:
  - name: start container
    docker_container:
      name: ansible_nginx
      image: ubuntu
      command: /bin/bash
      state: started
      interactive: yes
      tty: yes

- hosts: ansible_nginx
  gather_facts: False  # otherwise it will fail on docker images without python3 installed
  tasks:
  - name: ensure python is installed
    raw: test -e /usr/bin/python3 || (apt -y update && apt install -y python3-minimal)
    register: result
    changed_when: result.stdout != ''
   
  - name: install required packages
    apt: pkg=nginx state=installed
  
  - name: enable nginx server
    service: name=nginx enabled=yes

  - name: start nginx server
    service: name=nginx state=started

- hosts: localhost
  tasks:
  - name: remove container
    docker_container:
      name: ansible_nginx
      state: absent
```

If I change the playbook to use the service command directly it works.
```yaml

- name: start nginx server
  service: name=nginx state=started
  when: ansible_connection != 'docker'

- name: start nginx server
  command: service nginx start
  when: ansible_connection == 'docker'
  args:
    warn: no
```

##### EXPECTED RESULTS
service started

##### ACTUAL RESULTS
service not started
