### ISSUE TITLE
win_uri: The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#35413]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_uri

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /<sensored>/ansible.cfg
  configured module search path = [u'/<sensored>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/<sensored>/ansible.cfg) = True
ANSIBLE_PIPELINING(/<sensored>/ansible.cfg) = False
ANSIBLE_SSH_CONTROL_PATH(/<sensored>/ansible.cfg) = %(directory)s/%%h-%%p
DEFAULT_CALLBACK_WHITELIST(/<sensored>/ansible.cfg) = ['timer']
DEFAULT_FORCE_HANDLERS(/<sensored>/ansible.cfg) = True
DEFAULT_MANAGED_STR(/<sensored>/ansible.cfg) = Ansible managed: file modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_STDOUT_CALLBACK(/<sensored>/ansible.cfg) = skippy
DISPLAY_SKIPPED_HOSTS(/<sensored>/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/<sensored>/ansible.cfg) = /<sensored>/retry
```

##### OS / ENVIRONMENT

Mac OS 10.13 => Microsoft Windows Server 2012 R2 Standard, `"ansible_powershell_version": 4`

##### SUMMARY

Module fails.

##### STEPS TO REPRODUCE

```yml
- name: get download page
  win_uri:
      url: "https://www.consul.io/downloads.html"
      method: GET
      return_content: yes
  register: download_html
  when: consul_version == 'latest'

- debug: var=download_html
  
<!--- You can also paste gist.github.com links for larger files -->

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->

<!--- Paste verbatim command output between quotes below -->

```
TASK [win_consul : get download page] *****************************************************************************************************************************************************************************************************
task path: /<sensored>/roles/win_consul/tasks/main.yml:1
Using module file /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible/modules/windows/win_uri.ps1
<winhost> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO winhost
EXEC (via pipeline wrapper)
fatal: [winhost]: FAILED! => {
    "changed": false, 
    "content_type": null, 
    "method": "GET", 
    "msg": "The request was aborted: Could not create SSL/TLS secure channel.", 
    "url": "https://www.consul.io/downloads.html", 
    "use_basic_parsing": true
}
```
