### ISSUE TITLE
unarchive module doesn't apply owner/group to top folder

### ISSUE THREAD

**Issue by pescobar** [ansible/ansible#35426]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
unarchive module

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### CONFIGURATION
`ansible-config dump --only-changed` reports no changes

##### OS / ENVIRONMENT
Centos7 python 2.7.5

##### SUMMARY

The owner/group is properly applied for all the files inside the tarball but not for the top folder

```
- name: Uncompress the tarball to {{ install_foder }} . By default /opt
  unarchive:
    src: "{{ tarball_path }}"
    dest: "{{ tomcat_install_folder }}"
    remote_src: yes
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
```

but notice that the top folder `.` is still owned by root

```
[vagrant@centos7 ~]$ ls -la /opt/apache-tomcat-8.5.27
total 92
drwxr-xr-x. 9 root   root     160 Jan 28 11:29 .
drwxr-xr-x. 4 root   root     149 Jan 28 11:29 ..
drwxr-x---. 2 tomcat tomcat  4096 Jan 28 11:29 bin
drwx------. 3 tomcat tomcat   254 Jan 28 11:29 conf
drwxr-x---. 2 tomcat tomcat  4096 Jan 28 11:29 lib
-rw-r-----. 1 tomcat tomcat 57092 Jan 18 20:15 LICENSE
drwxr-x---. 2 tomcat tomcat   197 Jan 28 11:29 logs
-rw-r-----. 1 tomcat tomcat  1723 Jan 18 20:15 NOTICE
-rw-r-----. 1 tomcat tomcat  7138 Jan 18 20:15 RELEASE-NOTES
-rw-r-----. 1 tomcat tomcat 16246 Jan 18 20:15 RUNNING.txt
drwxr-x---. 2 tomcat tomcat    48 Jan 28 11:29 temp
drwxr-x---. 7 tomcat tomcat    81 Jan 18 20:13 webapps
drwxr-x---. 3 tomcat tomcat    22 Jan 28 11:29 work
```

##### STEPS TO REPRODUCE
This playbook can reproduce the error

```yaml

---

- name: Test the unarchive owner/group bug
  hosts: "{{ hostsvar | default('all') }}"
  gather_facts: True
  remote_user: root

  tasks:

  - name: Add local group for tomcat
    group:
      name: "tomcat"
      state: present

  - name: Add local user for tomcat
    user:
      name: "tomcat"
      group: "tomcat"
      state: present
      system: yes

  - name: Download the tomcat tarball
    get_url:
      url: "http://apache.rediris.es/tomcat/tomcat-8/v8.5.27/bin/apache-tomcat-8.5.27.tar.gz"
      dest: "/tmp"
    register: download

  - name: set a variable with the full path of the downloaded .tar.gz file
    set_fact:
      tarball_path: "{{ download.dest }}"

  - name: Uncompress the tarball to /tmp
    unarchive:
      src: "{{ tarball_path }}"
      dest: "/tmp"
      remote_src: yes
      owner: "tomcat"
      group: "tomcat"

  - name: Find the folder where the tomcat tarball has been uncompressed
    find:
      paths: "/tmp/"
      patterns: 'apache-tomcat*'
      file_type: directory
    register: find_result

   # [files] is a list of dicts with the info of all the directories starting by apache-tomcat*
   # we fetch the path of last element in the list
  - name: set a variable with the path where the tarball has been uncompressed
    set_fact:
      tomcat_path: "{{ find_result['files'][-1]['path'] }}"

  - name: List the contents of the tomcat folder
    shell: "ls -la {{ tomcat_path }}"
    register: ls_output

  - name: print the output of shell. Notice that parent folder "." is owned by root
    debug:
      var: ls_output.stdout_lines

```
##### EXPECTED RESULTS
All the files should be owned by the same user. Also parent folder

##### ACTUAL RESULTS
Parent folder is owned by root. Everything below has the right permissions.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/unarchive.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/unarchive.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pileofrogs
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
This is an issue with the archive you are referring to. The top-folder is not part of the archive, while the other files are. Since the ownership and permissions are part of the archive as well, what would the ownership/permissions be of the folder that is **not** part of the archive ?

It is very simple, we cannot assume or invent the ownership/permissions of a folder that is missing from the archive. I guess you have to report this to the project in order to get this changed...

**Comment by pescobar** [comment]
hi @dagwieers 

I am not sure if I am missing something but I haven't created the top folder. The top folder is automatically created when I extract the tarball so I assume it is part of the archive.

You can see here that the top folder `apache-tomcat-8.5.27` is listed when inspecting the contents of the tarball:

```
[root@host ~]# tar -tvf /opt/apache-tomcat-8.5.27.tar.gz | head
drwx------ 0/0               0 2018-01-18 21:15 apache-tomcat-8.5.27/conf/
-rw------- 0/0           13824 2018-01-18 21:15 apache-tomcat-8.5.27/conf/catalina.policy
-rw------- 0/0            7376 2018-01-18 21:15 apache-tomcat-8.5.27/conf/catalina.properties
-rw------- 0/0            1338 2018-01-18 21:15 apache-tomcat-8.5.27/conf/context.xml
-rw------- 0/0            1149 2018-01-18 21:15 apache-tomcat-8.5.27/conf/jaspic-providers.xml
-rw------- 0/0            2313 2018-01-18 21:15 apache-tomcat-8.5.27/conf/jaspic-providers.xsd
```

**Comment by dagwieers** [comment]
The top-directory is not listed. The conf/ sub-directory _is_ included. So Ansible cannot  just make up ownership/permission. This must be fixed in the archive.

**Comment by Benny-Git** [comment]
Hi @dagwieers 

I understand what you mean: The top-directory is not listed in the archive. However it is "contained" in the archive _implicitly_, if not _explicitly_.

In my scenario with unpacking [logstash](https://www.elastic.co/de/downloads/logstash) this gets even more complicated, as the root dir (`logstash-6.2.1`) is not explicitly included, while the (empty) `logstash-6.2.1/data` directory is included, and the (not empty) `logstash-6.2.1/bin` directory is not explicitly included again.

For me the _expected_ behavior when using the unarchive module with the owner and group parameter set would be that all content I unpacked, including not-explicitly-packaged directories, would be owned by that user/group. I cannot go around fixing elastic's tar balls, and I would want to avoid a separate chown.

I understand that if you extract a tar ball over an existing structure, and some directories exist already (owned by a different user), you might not want to change ownership for those. But we could possibly catch that scenario of unpacking non-existing directories? Or we could divert the expected behavior by explicitly mentioning that scenario in the documentation?

**Comment by pescobar** [comment]
I also find more realistic that ansible could handle the different possible situations instead of expecting that everyone out there "fixes their archives". That's not realistic.

**Comment by dagwieers** [comment]
What you expect is one thing, how it is implemented is completely different. You see **unarchive** is a wrapper around **unzip** and **gtar**. So the module does not really create anything, it hands it off to another tool. Only for the sake of testing the state it knows about the content of an archive.

So what you want requires a proper module that does the extraction itself and has complete control. Now, I have been saying for years now that we need a newer module, but people keep complaining about the existing module and nobody is remotely interested to fix the real problem. (And I don't have the time, and am no longer interested in supporting a growing number of users complaining).

I explained why it behaves as it does, up to you or someone else to dig in and fix whatever you think needs fixing. Good luck.

https://github.com/ansible/community/wiki/Module%3A-unarchive

**Comment by b-long** [comment]
@dagwieers I can appreciate that there is no time to address this bug, I'm sorry to hear that.  The Ansible team and community are fantastic, and very I'm happy to have it.

I do want to add my support for counting this as a bug.  Also, unless I missed it, I'm interested in the canonical workaround.  Given the example provided by @pescobar , I'd guess this is the approach preferred, inserted just before the task to "_List the contents of the tomcat folder_"

```yaml
# Necessary, given https://github.com/ansible/ansible/issues/35426
- name: Fix permissions on the extract directory and sub-directories
  file:
    path: "{{ tomcat_path }}"
    owner: "tomcat"
    group: "tomcat"
    recurse: yes
```
Is this correct?

**Comment by pescobar** [comment]
@b-long the problem I see with your suggested solution is that it breaks idempotence. 

I guess as workaround you could add `changed_when: False` to your task `Fix permissions on the extract directory and sub-directories`. 

If you add extra files to the extracted folder you would also override the ownership in future executions of the playbook

**Comment by Redsandro** [comment]
This issue looks similar to the one I just encountered. 

For me, ansible did not apply `user:group` to **any** directory extracted from a `.tar.gz` file.

I can understand that this is not technically a bug, but in reality there are directories created for which I specified `owner:group`. I can't do much more than that. So I would vote for counting this as a bug.

The solution by @b-long works for me. I would suggest automatically running this if group and user are specified in the unarchive command. :+1: 

---

`tar -tvf /opt/apache-tomcat-8.5.27.tar.gz | head`:

```
$ tar -tvf robo3t-1.2.1-linux-x86_64-3e50a65.tar.gz | head
-rw-r--r-- julia/julia   35147 2016-06-28 23:10 robo3t-1.2.1-linux-x86_64-3e50a65/LICENSE
-rw-r--r-- julia/julia   27362 2018-02-08 09:40 robo3t-1.2.1-linux-x86_64-3e50a65/CHANGELOG
-rw-r--r-- julia/julia     175 2017-05-20 12:34 robo3t-1.2.1-linux-x86_64-3e50a65/DESCRIPTION
-rw-r--r-- julia/julia   71032 2017-11-21 14:00 robo3t-1.2.1-linux-x86_64-3e50a65/lib/libicuio.so.56.1
lrwxrwxrwx julia/julia       0 2018-02-08 09:46 robo3t-1.2.1-linux-x86_64-3e50a65/lib/libiculx.so.56 -> libiculx.so.56.1
lrwxrwxrwx julia/julia       0 2018-02-08 09:46 robo3t-1.2.1-linux-x86_64-3e50a65/lib/libQt5Gui.so.5 -> libQt5Gui.so.5.9.3
lrwxrwxrwx julia/julia       0 2018-02-08 09:46 robo3t-1.2.1-linux-x86_64-3e50a65/lib/libicudata.so -> libicudata.so.56.1
-rw-r--r-- julia/julia 1110280 2016-09-04 19:38 robo3t-1.2.1-linux-x86_64-3e50a65/lib/libstdc++.so.6.0.22
lrwxrwxrwx julia/julia       0 2018-02-08 09:46 robo3t-1.2.1-linux-x86_64-3e50a65/lib/libicule.so.56 -> libicule.so.56.1
lrwxrwxrwx julia/julia       0 2018-02-08 09:46 robo3t-1.2.1-linux-x86_64-3e50a65/lib/libicuuc.so.56 -> libicuuc.so.56.1
```

Expected `owner:group` to be set on every file/directory created:

```
  unarchive:
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: '{{user}}'
    group: '{{user}}'
```

This is the offending ansible task: [ansible-ubuntu-software/roles/packages/tasks/robo3t.yml](https://github.com/Redsandro/ansible-ubuntu-software/blob/c4aaa51f4ebf24f2676c281bb15e7845c1fb7110/roles/packages/tasks/robo3t.yml#L30-L48)

Could technically be ran as local user, but the idea is to provision the entire machine in one go, so tasks are ran as root.
