### ISSUE TITLE
win_nssm: service doesn't start

### ISSUE THREAD

**Issue by hryamzik** [ansible/ansible#35442]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_nssm

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /<sensored>/ansible.cfg
  configured module search path = [u'/<sensored>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/<sensored>/ansible.cfg) = True
ANSIBLE_PIPELINING(/<sensored>/ansible.cfg) = False
ANSIBLE_SSH_CONTROL_PATH(/<sensored>/ansible.cfg) = %(directory)s/%%h-%%p
DEFAULT_CALLBACK_WHITELIST(/<sensored>/ansible.cfg) = ['timer']
DEFAULT_FORCE_HANDLERS(/<sensored>/ansible.cfg) = True
DEFAULT_MANAGED_STR(/<sensored>/ansible.cfg) = Ansible managed: file modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_STDOUT_CALLBACK(/<sensored>/ansible.cfg) = skippy
DISPLAY_SKIPPED_HOSTS(/<sensored>/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/<sensored>/ansible.cfg) = /<sensored>/retry
```

##### OS / ENVIRONMENT

Mac OS 10.13 => Microsoft Windows Server 2012 R2 Standard, `"ansible_powershell_version": 4`

##### SUMMARY

Service got registered but doesn't start

##### STEPS TO REPRODUCE

```yaml
- name: get download page
  uri: # win_uri fails: https://github.com/ansible/ansible/issues/35413
      url: "https://www.consul.io/downloads.html"
      method: GET
      return_content: yes
  register: download_html
  when: consul_version == 'latest'
  delegate_to: localhost

- name: define consul_download_version
  set_fact: consul_download_version="{{ (download_html|replace('\n','')|regex_replace('.*(https://github\.com/hashicorp/consul/blob/v([0-9,.]+)/CHANGELOG\.md).*', '\2')) if consul_version == 'latest' else consul_version }}"
  when: consul_version == 'latest'

- name: define consul_archive and consul_download vars
  set_fact:
    consul_archive: "consul_{{ consul_download_version }}_{{ (ansible_os_family|lower) if ansible_os_family == 'Windows' else (ansible_system|lower) }}_{{ hashicorp_arch_mappings[ansible_architecture] }}.zip"
    consul_download: "https://releases.hashicorp.com/consul/{{ consul_download_version }}/consul_{{ consul_download_version }}_{{ (ansible_os_family|lower) if ansible_os_family == 'Windows' else (ansible_system|lower) }}_{{ hashicorp_arch_mappings[ansible_architecture] }}.zip"

- name: download consul
  win_get_url:
      url: "{{ consul_download }}"
      dest: "{{ ansible_env.TMP }}\\{{ consul_archive }}"

- name: create consul directories
  win_file:
      path: "{{ item }}"
      state: directory
  with_items:
      - "{{ consul_dir }}"
      - "{{ consul_data_dir }}"
      - "{{ consul_cfg_dir }}"

- name: unzip consul archive
  win_unzip:
      src: "{{ ansible_env.TMP }}\\{{ consul_archive }}"
      dest: "{{ consul_dir }}"

- name: deploy consul config
  win_template:
    src: config.json
    dest: "{{ consul_cfg_dir }}\\config.json"

- name: install nssm
  win_chocolatey: name=nssm

- name: run consul
  win_nssm:
    name: consul
    application: C:\opt\consul\consul.exe
    app_parameters_free_form: "agent -config-file {{ consul_cfg_dir }}\\config.jsoni"
    state: started
```

##### EXPECTED RESULTS

consul service started

##### ACTUAL RESULTS

consul service stopped

```
TASK [win_consul : run consul] ************************************************************************************************************************************************************************************************************
task path: /rolepath/tasks/main.yml:52
Using module file /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible/modules/windows/win_nssm.ps1
<winhost> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO winhost
EXEC (via pipeline wrapper)
changed: [winhost] => {
    "application": "C:\\opt\\consul\\consul.exe", 
    "changed": true, 
    "changed_by": "start_mode", 
    "nssm_app_parameters": "", 
    "nssm_app_parameters_free_form": "agent -config-file C:\\opt\\consul\\config\\config.json -ui", 
    "nssm_single_line_app_parameters": "agent -config-file C:\\opt\\consul\\config\\config.json -ui"
}
META: ran handlers
```

##### WORKAROUND

```yml
- name: check consul service status
  raw: nssm status consul
  register: result

- name: start consul service
  raw: nssm start consul
  when: "'SERVICE_STOPPED' in result.stdout_lines"
```
