### ISSUE TITLE
docker_container: Always recreates container when mac_address is used

### ISSUE THREAD

**Issue by codidex** [ansible/ansible#35463]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
* Source Host : Debian 8
* Target Host : Debian 8
* Target docker:
```
Docker version 17.12.0-ce, build c97c6d6
```
* Target docker-py:
```
docker-py (1.10.6)
docker-pycreds (0.2.1)
```

##### SUMMARY
When mac_address is specified, ansible always recreates the container on the target host.

##### STEPS TO REPRODUCE

Run this task twice:

```yaml
        -
            docker_container:
                name: test
                image: "debian:8"
                command: "sleep infinity"
                mac_address: "02-00-00-00-00-01"
```

##### EXPECTED RESULTS
Container is created on first run, no changes made on second run.

##### ACTUAL RESULTS

Container is recreated on the second run, which is not the case if i remove mac_address configuration field.
