### ISSUE TITLE
apt error message doesn't align with documentation

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible#35474]
##### ISSUE TYPE
 - Bug  Report

##### COMPONENT NAME
apt

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### SUMMARY
Documentation phrasing doesn't match Ansible error

##### STEPS TO REPRODUCE

```yaml
- name: Update and upgrade using apt
  apt:
    update_cache: yes
    cache_valid_time: 3600
    name: "*"
    upgrade: safe
  become: True
```

##### EXPECTED RESULTS
The result should say 'name' and not 'package'. Alternatively, documentation should refer to 'package' and package should be the primary command in documentation. This inconsistency happens because the documentation refers to 'name' as the primary command and 'package' as the alias. But the code views 'package' as the primary command. Updating documentation to have 'package' as the primary may require some thought, because similar packages (ex. yum) often use 'name'.

##### ACTUAL RESULTS
```
*
fatal: [ansible.kb-lab.net]: FAILED! => {"changed": false, "msg": "parameters are mutually exclusive: ['package', 'upgrade', 'deb']"}

```
