### ISSUE TITLE
loop order on dictionary with ansible_tasks is random

### ISSUE THREAD

**Issue by dusty73** [ansible/ansible#35495]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
include_tasks

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### OS / ENVIRONMENT
Centos

##### SUMMARY
The order of dictionary items when looping in an ansible_tasks directive is unpredictable. Given a dictionary of the form:
```yaml
 packages:
      aaaa:
        name: test1
      zzzz:
        name: test2
      cxxx:
        name: test3
      test4:
        name: test4
      test5:
        name: test5
      test6:
        name: test6
```
I would expect that the included tasks work on dictionary item in the order of definition, instead the order is random.

##### STEPS TO REPRODUCE

```yaml
--- # test.yml
- hosts: all

  vars:
    packages:
      aaaa:
        name: test1
      zzzz:
        name: test2
      cxxx:
        name: test3
      test4:
        name: test4
      test5:
        name: test5
      test6:
        name: test6
  tasks:
  - name: "Include tasks with loop"
    include_tasks: test2.yml
    vars:
      im_package: "{{item}}"
    with_dict:
      "{{ packages }}"

--- # test2.yml
- name: Test inner
  debug:
    msg: "{{ im_package.key }} {{ im_package.value.name }}"
```

Run a test:
```
ansible-playbook test.yml -c local -i localhost,
```

##### EXPECTED RESULTS

```
PLAY [all] ***************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************
ok: [localhost]

TASK [Include tasks with loop] *******************************************************************************************
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "aaaa test1"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "zzzz test2"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "cxxx test3"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test4 test4"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test5 test5"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test6 test6"
}

PLAY RECAP ***************************************************************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=0

```

##### ACTUAL RESULTS

```
PLAY [all] ***************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************
ok: [localhost]

TASK [Include tasks with loop] *******************************************************************************************
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost
included: /home/vagrant/projects/ansible/test/test2.yml for localhost

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test5 test5"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test4 test4"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "test6 test6"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "zzzz test2"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "aaaa test1"
}

TASK [Test inner] ********************************************************************************************************
ok: [localhost] => {
    "msg": "cxxx test3"
}

PLAY RECAP ***************************************************************************************************************
localhost                  : ok=13   changed=0    unreachable=0    failed=0

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/include_tasks.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/include_tasks.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by maxamillion** [comment]
This is because the Python `dict` type is not ordered so the iteration is not guaranteed to be in-order. A solution for this would be to use the `|dictsort` [jinja2 filter](http://jinja.pocoo.org/docs/2.9/templates/#dictsort) which will sort the dict by key value by default or by value at your discretion. Do note that that `|dictsort` filter returns a `list`.

Here's an adaptation of your example.
```
--- # test.yml                      
- hosts: localhost                  
  gather_facts: false               

  vars:                             
    packages:                       
      aaaa:                         
        name: test1                 
      zzzz:                         
        name: test2                 
      cxxx:                         
        name: test3                 
      test4:                        
        name: test4                 
      test5:                        
        name: test5                 
      test6:                        
        name: test6                 
  tasks:                            
  - name: "Include tasks with loop" 
    include_tasks: test2.yml        
    vars:                           
      im_package: "{{item}}"        
    with_list:                      
      "{{ packages|dictsort }}"[09:48:29|admiller@pseudogen(0) /tmp]    
```

```       
--- # test2.yml                     
- name: Test inner                  
  debug:                            
    msg: "{{ im_package[0] }} - {{ im_package[1].name }}"
```

The execution output of this will always be in-order, sorted by key value:
```
PLAY [localhost] ***************************************************************

TASK [Include tasks with loop] *************************************************
included: /tmp/test2.yml for localhost
included: /tmp/test2.yml for localhost
included: /tmp/test2.yml for localhost
included: /tmp/test2.yml for localhost
included: /tmp/test2.yml for localhost
included: /tmp/test2.yml for localhost

TASK [Test inner] **************************************************************
ok: [localhost] => {
    "msg": "aaaa - test1"
}

TASK [Test inner] **************************************************************
ok: [localhost] => {
    "msg": "cxxx - test3"
}

TASK [Test inner] **************************************************************
ok: [localhost] => {
    "msg": "test4 - test4"
}

TASK [Test inner] **************************************************************
ok: [localhost] => {
    "msg": "test5 - test5"
}

TASK [Test inner] **************************************************************
ok: [localhost] => {
    "msg": "test6 - test6"
}

TASK [Test inner] **************************************************************
ok: [localhost] => {
    "msg": "zzzz - test2"
}

PLAY RECAP *********************************************************************
localhost                  : ok=12   changed=0    unreachable=0    failed=0  
```
