### ISSUE TITLE
ios_config fails when user confirmation is needed

### ISSUE THREAD

**Issue by MichalTaratuta** [ansible/ansible#35494]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### CONFIGURATION
```
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/modules']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY

Module fails to execute commands which require confirmation from the user.
```
LAB2960SF(config)#no crypto pki trustpoint TP-self-signed-1665464064
% Removing an enrolled trustpoint will destroy all certificates
 received from the related Certificate Authority.

Are you sure you want to do this? [yes/no]: 
% Please answer 'yes' or 'no'.
```

Ideally there would be an option to force the configuration.
##### STEPS TO REPRODUCE

```yaml
    - name: remove crypto pki certificate chain
      ios_config:
        lines:
          - no crypto pki certificate chain TP-self-signed-1665464064
        provider: "{{cli}}"
```

##### EXPECTED RESULTS

Task to complete successfuly 
```"rc": 0```
##### ACTUAL RESULTS

Task fails due to a timeout. 
Changing the timeout value doesn't change the situation.

```
"msg": "timeout trying to send command: no crypto pki certificate chain TP-self-signed-1665464064", 
    "rc": 1

```
