### ISSUE TITLE
LetsEncrypt fails to recognise Account Key

### ISSUE THREAD

**Issue by byrneo** [ansible/ansible#35496]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /Users/obyrne/aws/aws-automation/aws-infra/ansible/ansible.cfg
  configured module search path = [u'/Users/obyrne/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/obyrne/.virtualenvs/ansible2.5/lib/python2.7/site-packages/ansible
  executable location = /Users/obyrne/.virtualenvs/ansible2.5/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

MacOS 10.13.2

Name: pyOpenSSL
Version: 17.5.0
Summary: Python wrapper module around the OpenSSL library
Home-page: https://pyopenssl.org/
Author: Hynek Schlawack
Author-email: hs@ox.cx
License: Apache License, Version 2.0
Location: /Users/obyrne/.virtualenvs/ansible2.5/lib/python2.7/site-packages
Requires: cryptography, six

Name: cryptography
Version: 2.1.4
Summary: cryptography is a package which provides cryptographic recipes and primitives to Python developers.

Name: six
Version: 1.11.0
Summary: Python 2 and 3 compatibility utilities

##### SUMMARY

LetsEncrypt request fails with: "error while parsing account key: unknown key type \"%s\" % account_key_type".

This succeeds with Ansible2.4

##### STEPS TO REPRODUCE

```yaml
- name: "Create LetsEncrypt Signing Key"
    openssl_privatekey:
      path: "{{ letsencrypt.private_dir }}/lets_encrypt.key"
    tags:
      - letsencrypt

  - name: "Formulating LetsEncrypt API Call"
    letsencrypt:
      remaining_days: "{{ letsencrypt.renewal_days }}" 
      acme_directory: "{{ api_url }}"
      account_email: "{{ letsencrypt.account_email }}"
      account_key_src: "{{ letsencrypt.private_dir }}/lets_encrypt.key"
      challenge: "{{ letsencrypt.challenge_type }}"
      agreement: "{{ letsencrypt.agreement }}"
      csr: "{{ letsencrypt.requests_dir }}/{{ lets_encrypt_resource_name }}.csr"
      dest: "{{ letsencrypt.certs_dir }}/{{ lets_encrypt_resource_name }}.crt"
    register: acme_data
    tags:
      - letsencrypt
```

##### EXPECTED RESULTS

TASK [Formulating LetsEncrypt API Call] **********************************************************************************************************************************************************************************************************************************
changed: [localhost]

##### ACTUAL RESULTS

```
TASK [Formulating LetsEncrypt API Call] **********************************************************************************************************************************************************************************************************************************
task path: /Users/obyrne/aws/aws-automation/aws-infra/ansible/ssl_certs.yml:191
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "error while parsing account key: unknown key type \"%s\" % account_key_type"}
        to retry, use: --limit @/Users/obyrne/aws/aws-automation/aws-infra/ansible/ssl_certs.retry
```
