### ISSUE TITLE
getting error while creating vmkernel interface using vmware_vmkernel module

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#35491]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_vmkernel

##### ANSIBLE VERSION

```
2.4.2.0 and dev 2.5
```

##### SUMMARY
 I am using below playbook to create vmware vmkernel interface on ESXIhost under my virtual switch.All parameters i am specifyinh here are right and i am able to create interface through vsphere webclient with same parameter values.

but when i run my playbook i get error as  "msg": "A specified parameter was not correct: "

Below is stack trace for the same.

##### STEPS TO REPRODUCE

```yaml
---

with dev ansible 2.5


- hosts: 127.0.0.1
  connection: local
  tasks:
    -  name: Add Management vmkernel port using dhcp network type
       local_action:
         module: vmware_vmkernel
         hostname: 10.243.1.43
         username: root
         password: PASSW0RD
         vswitch_name: vSwitch1
         portgroup_name: test1
         vlan_id: 0
         network:
           type: 'dhcp'
         enable_mgmt: True
         enable_vmotion: True
         validate_certs: no

with ansible 2.4.2.0

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add Management vmkernel port (vmk1)
      local_action:
        module: vmware_vmkernel
        hostname:  10.243.1.43
        username:  root
        password:  PASSW0RD
        vswitch_name:  vSwitch1
        portgroup_name:  test1
        vlan_id: 0
        ip_address:  10.243.9.1
        subnet_mask:  255.255.255.0
        enable_mgmt:  True
        enable_vmotion:  True
        validate_certs:  no
```

##### EXPECTED RESULTS

```
    expect vmkernel interface getting added
```
##### ACTUAL RESULTS

```
  The full traceback is:
  File "/tmp/ansible_EMdqRm/ansible_module_vmware_vmkernel.py", line 236, in main
    changed = pyv.create_vmkernel_adapter()
  File "/tmp/ansible_EMdqRm/ansible_module_vmware_vmkernel.py", line 186, in create_vmkernel_adapter
    host_network_config_result = host_network_system.UpdateNetworkConfig(config, "modify")
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "enable_ft": null, 
            "enable_mgmt": true, 
            "enable_vmotion": true, 
            "enable_vsan": null, 
            "hostname": "10.243.1.43", 
            "ip_address": null, 
            "mtu": null, 
            "network": {
                "ip_address": null, 
                "subnet_mask": null, 
                "type": "dhcp"
            }, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "portgroup_name": "test1", 
            "subnet_mask": null, 
            "username": "root", 
            "validate_certs": false, 
            "vlan_id": 0, 
            "vswitch_name": "vSwitch1"
        }
    }, 
    "msg": "A specified parameter was not correct: "
}
```

```
 "msg": "A specified parameter was not correct: "
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_vmkernel.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_vmkernel.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @akasurde @dav1x @jcpowermac @jctanner @mtnbikenc @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr #35531

**Comment by Akasurde** [comment]
@umrikar Could you please try with above patch and let me know if it works for you?

**Comment by Akasurde** [comment]
needs_info

**Comment by umrikar** [comment]
Hi,
    i pulled your fix and updated playbook as below but i am getting error "msg": "ESXi '10.243.1.43' not found"
[test1.txt](https://github.com/ansible/ansible/files/1691232/test1.txt)

**Comment by Akasurde** [comment]
@umrikar Could you please paste output of `-vvvv` ?

**Comment by umrikar** [comment]
Hi,
   below is output with -vvvv
```
fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "enable_ft": null, 
            "enable_mgmt": true, 
            "enable_vmotion": true, 
            "enable_vsan": null, 
            "esxi_hostname": "10.243.1.43", 
            "hostname": "10.243.1.43", 
            "ip_address": null, 
            "mtu": 1500, 
            "network": {
                "ip_address": null, 
                "subnet_mask": null, 
                "type": "dhcp"
            }, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "portgroup_name": "test1", 
            "state": "present", 
            "subnet_mask": null, 
            "username": "root", 
            "validate_certs": false, 
            "vlan_id": 0, 
            "vswitch_name": "vSwitch1"
        }
    }, 
    "msg": "ESXi '10.243.1.43' not found"
}
```

**Comment by umrikar** [comment]
Hi Abhijeet,
   As discussed I have updated playbook as below and it worked 

```
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    -  name: Add Management vmkernel port using dhcp network type
       local_action:
         module: vmware_vmkernel
         esxi_hostname: esxi01.test.com
         hostname: 10.243.1.43
         username: root
         password: PASSW0RD
         vswitch_name: vSwitch1
         portgroup_name: test1
         vlan_id: 0
         network:
           type: 'dhcp'
         enable_mgmt: True
         enable_vmotion: True
         validate_certs: no
```
