### ISSUE TITLE
nxos_vlan fails configuring vlans using transport cli

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#35517]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_vlan

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel 942d98ed17) last updated 2018/01/29 14:54:55 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### OS / ENVIRONMENT
macOS
NXOS: version 7.0(3)I7(2)

##### SUMMARY
Applying a playbook to configure vlans on nxos fails and generates a traceback for transport cli.  The same playbook succeeds for transport nxapi.

##### STEPS TO REPRODUCE
Playbook from targets/nxos_l2_interface/tests/common/sanity.yaml
```yaml
---
- debug: msg="START connection={{ ansible_connection }} nxos_l2_interface sanity test"
- debug: msg="Using provider={{ connection.transport }}"
  when: ansible_connection == "local"

# Select interface for test
- set_fact: intname="{{ nxos_int1 }}"

- name: "Interface selected for this test"
  debug: msg="{{ intname }}"

- name: "Setup interface"
  nxos_config: &default
    lines:
      - "default interface {{ intname }}"
    provider: "{{ connection }}"
  ignore_errors: yes

- name: Setup - Ensure interface is layer2
  nxos_interface:
    interface: "{{ intname }}"
    mode: layer2

- name: "Setup vlans"
  nxos_vlan:
    vlan_range: "5-10,20"
    provider: "{{ connection }}"

- block:
  - name: Ensure interface is in its default switchport state
    nxos_l2_interface: &def_swi
      name: "{{ intname }}"
      state: unconfigured
      provider: "{{ connection }}"

  - name: Ensure interface is configured for access vlan 20
    nxos_l2_interface: &acc_vl
      name: "{{ intname }}"
      mode: access
      access_vlan: 20
      provider: "{{ connection }}"
    register: result

  - assert: &true
      that:
        - "result.changed == true"

  - name: "access vlan Idempotence"
    nxos_l2_interface: *acc_vl
    register: result

  - assert: &false
      that:
        - "result.changed == false"

  - name: Ensure interface only has vlans 5-10 as trunk vlans
    nxos_l2_interface: &tr_vl
      name: "{{ intname }}"
      mode: trunk
      native_vlan: 10
      trunk_allowed_vlans: 5-10
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: "trunk vlan Idempotence"
    nxos_l2_interface: *tr_vl
    register: result

  - assert: *false

  - name: Ensure interface is a trunk port and ensure 2-50 are being tagged (doesn't mean others aren't also being tagged)
    nxos_l2_interface: &tag
      name: "{{ intname }}"
      mode: trunk
      native_vlan: 10
      trunk_vlans: 2-50
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: "tag vlan Idempotence"
    nxos_l2_interface: *tag
    register: result

  - assert: *false

  - name: Ensure these VLANs are not being tagged on the trunk
    nxos_l2_interface: &no_tag
      name: "{{ intname }}"
      mode: trunk
      trunk_vlans: 30-4094
      state: absent
      provider: "{{ connection }}"
    register: result

  - assert: *true

  - name: "no tag vlan Idempotence"
    nxos_l2_interface: *no_tag
    register: result

  - assert: *false

  - name: put interface default state
    nxos_l2_interface: *def_swi
    register: result

  - assert: *true

  - name: "default state idempotence"
    nxos_l2_interface: *def_swi
    register: result

  - assert: *false

  always:
  - name: "remove vlans"
    nxos_vlan:
      vlan_range: "5-10,20"
      state: absent
      provider: "{{ connection }}"
    ignore_errors: yes

  - name: "default interface"
    nxos_config: *default
    ignore_errors: yes

- debug: msg="END connection={{ ansible_connection }} nxos_l2_interface sanity test"
```

##### ACTUAL RESULTS
```
TASK [nxos_l2_interface : Setup vlans] **************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_l2_interface/tests/common/sanity.yaml:24
<n9k.example.com> attempting to start connection
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> found existing local domain socket, using it!
<n9k.example.com> updating play_context for connection
<n9k.example.com> 
<n9k.example.com> local domain socket path is /Users/mwiebe/.ansible/pc/351688cc74
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_vlan.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1517336665.05-60551152859800 `" && echo ansible-tmp-1517336665.05-60551152859800="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1517336665.05-60551152859800 `" ) && sleep 0'
<n9k.example.com> PUT /Users/mwiebe/.ansible/tmp/ansible-local-31740vNIr34/tmpAfL577 TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1517336665.05-60551152859800/nxos_vlan.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1517336665.05-60551152859800/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1517336665.05-60551152859800/nxos_vlan.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1517336665.05-60551152859800/nxos_vlan.py && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py", line 535, in <module>
    main()
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py", line 514, in main
    have = map_config_to_obj(module, os_platform)
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py", line 448, in map_config_to_obj
    obj = parse_vlan_options(module, os_platform, output, vlans)
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py", line 429, in parse_vlan_options
    obj['interfaces'] = parse_interfaces(module, vlan)
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py", line 409, in parse_interfaces
    stop = int((int_range)[1])
ValueError: invalid literal for int() with base 10: 'channel10'

fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py\", line 535, in <module>\n    main()\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py\", line 514, in main\n    have = map_config_to_obj(module, os_platform)\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py\", line 448, in map_config_to_obj\n    obj = parse_vlan_options(module, os_platform, output, vlans)\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py\", line 429, in parse_vlan_options\n    obj['interfaces'] = parse_interfaces(module, vlan)\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_3pxmTt/ansible_module_nxos_vlan.py\", line 409, in parse_interfaces\n    stop = int((int_range)[1])\nValueError: invalid literal for int() with base 10: 'channel10'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
	to retry, use: --limit @/Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/nxos.retry

PLAY RECAP ******************************************************************************************************************************************************************************************************************
n9k.example.com        : ok=26   changed=2    unreachable=0    failed=1   
```
