### ISSUE TITLE
ios_config does not treat text files and template files differently

### ISSUE THREAD

**Issue by jmcgill298** [ansible/ansible#35523]
##### ISSUE TYPE

 - Feature Request

(changed by Gundalow)

##### COMPONENT NAME

ios_config, presumably several other modules

##### ANSIBLE VERSION

```
2.4
```

##### SUMMARY

Using `src` treats the file as jinja template, thus restricting the sequence of characters allowed in the file to sequences not reserved by jinja (ie, `{{ text }}` is treated as a variable instead of a string). This puts unnecessary burden on users to find and implement escape sequences and also renders the `src` file useless as a comparison against actual configuration files (it will necessarily report a diff due to escape sequences).

##### STEPS TO REPRODUCE

```yaml
- ios_config:
    src: "/path/to/file"

file contains characters reserved by jinja such as `{{ text }}`
```

##### EXPECTED RESULTS

The file is treated as text string and the config is added to the running config as needed.
##### ACTUAL RESULTS

```
fatal: [hostname]: FAILED! => {"msg": "'text' is undefined"}
```
