### ISSUE TITLE
Syntax for "when:" when testing an array of registered results

### ISSUE THREAD

**Issue by rubbsdecvik** [ansible/ansible#3552]
When registering variables with `with_items:` the variable is an array which includes all the normal registered pieces as each element in the array. This makes it very difficult to use in the next task using the `when:` clause.

I'm asking for a nice way to test the output of all of the elements in the array at once.

For example:

``` yml
- name: Rsync each directory to backup_server
  action: command rsync -aq --delete --delete-excluded --exclude-from=/tmp/exclude.list --link-dest={{ backup_root_dir }}/{{ ansible_fqdn }}/1/{{ item }} {{ ansible_fqdn }}:{{ item }} {{ backup_root_dir }}/{{ ansible_fqdn }}/0/{{ item }}
  with_items: backup_dirs
  delegate_to: "{{ backup_server }}"
  ignore_errors: yes
  register: rsync_result

- name: throw things into a template
  action: template src=../../templates/rsync.j2 dest=/tmp/rsync.txt owner=root group=root mode=0644
```

returns: 

``` json
{
    "changed": true, 
    "msg": "All items completed", 
    "results": [
        {
            "changed": true, 
            "cmd": [
                "rsync", 
                "-aq", 
                "--delete", 
                "--delete-excluded", 
                "--exclude-from=/tmp/exclude.list", 
                "--link-dest=/srv/backup/ansible-backup//machine.example.com/1//usr/lib/perl5/site_perl/", 
                "machine.example.com:/usr/lib/perl5/site_perl/", 
                "/srv/backup/ansible-backup//machine.example.com/0//usr/lib/perl5/site_perl/"
            ], 
            "delta": "0:00:06.403226", 
            "end": "2013-07-16 13:15:57.634358", 
            "invocation": {
                "module_args": "rsync -aq --delete --delete-excluded --exclude-from=/tmp/exclude.list --link-dest=/srv/backup/ansible-backup//machine.example.com/1//usr/lib/perl5/site_perl/ machine.example.com:/usr/lib/perl5/site_perl/ /srv/backup/ansible-backup//machine.example.com/0//usr/lib/perl5/site_perl/", 
                "module_name": "command"
            }, 
            "item": "/usr/lib/perl5/site_perl/", 
            "rc": 0, 
            "start": "2013-07-16 13:15:51.231132", 
            "stderr": "--link-dest arg does not exist: /srv/backup/ansible-backup//machine.example.com/1//usr/lib/perl5/site_perl/", 
            "stdout": ""
        }, 
        {
            "changed": true, 
            "cmd": [
                "rsync", 
                "-aq", 
                "--delete", 
                "--delete-excluded", 
                "--exclude-from=/tmp/exclude.list", 
                "--link-dest=/srv/backup/ansible-backup//machine.example.com/1//usr/lib/perl5/vendor_perl/", 
                "machine.example.com:/usr/lib/perl5/vendor_perl/", 
                "/srv/backup/ansible-backup//machine.example.com/0//usr/lib/perl5/vendor_perl/"
            ], 
            "delta": "0:00:05.974580", 
            "end": "2013-07-16 13:16:03.879065", 
            "invocation": {
                "module_args": "rsync -aq --delete --delete-excluded --exclude-from=/tmp/exclude.list --link-dest=/srv/backup/ansible-backup//machine.example.com/1//usr/lib/perl5/vendor_perl/ machine.example.com:/usr/lib/perl5/vendor_perl/ /srv/backup/ansible-backup//machine.example.com/0//usr/lib/perl5/vendor_perl/", 
                "module_name": "command"
            }, 
            "item": "/usr/lib/perl5/vendor_perl/", 
            "rc": 0, 
            "start": "2013-07-16 13:15:57.904485", 
            "stderr": "--link-dest arg does not exist: /srv/backup/ansible-backup//machine.example.com/1//usr/lib/perl5/vendor_perl/", 
            "stdout": ""
        }
    ]
}
```

Trying to run tests against that result using `when:` results in the following:

```
Conditional expression must evaluate to True or False: {% if rsync_result.rc != 0 and rsync_result.rc != 24 %} True {% else %} False {% endif %}
```

Discussions on the IRC channel discuss something similar to `|any`, `|all`, or `| only_values('rc',[0,24])`. 

I'm not sure of the best syntax, but something like this would be very helpful.
