### ISSUE TITLE
Add option to unarchive module to be quietly

### ISSUE THREAD

**Issue by cesarjorgemartinez** [ansible/ansible#35537]
##### ISSUE TYPE
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
http://docs.ansible.com/ansible/latest/unarchive_module.html

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/user/sw/iot_ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/venv-ansible-2.4.2.0/lib/python2.7/site-packages/ansible
  executable location = /home/user/venv-ansible-2.4.2.0/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Add option to unarchive module to be quietly (as unzip -qq does) when use zip file with a large number of files. Example adding quiet: yes

##### STEPS TO REPRODUCE
```yaml
- name: Extract file with unarchive
  unarchive:
    src: "/opt/filewithalargenumberoffiles.zip"
    dest: "/opt"
    copy: no
```

##### EXPECTED RESULTS
```
changed: ok
```

##### ACTUAL RESULTS
```
changed: ....... very huge output
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/unarchive.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/unarchive.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pileofrogs
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
Those changes are in here: #19015

**Comment by sijis** [comment]
I think you can probably just add the options you want in `extra_opts` parameter.

This seems to work using a `centos:7` docker container
```
[root@0df32e44ec62 /]# ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
[root@0df32e44ec62 /]# 
```

The playbook used to recreate:
```
---
- hosts: localhost
  vars:
    issue: 35537
  tasks:
    - name: Create directory
      file:
        state: directory
        path: "{{item}}"
      with_items:
        - "/tmp/test-{{issue}}"
        - "files/test-{{issue}}"
    - name: Create zip
      shell: "touch files/test-{{issue}}/{0..100} && zip -qq -r files/test-{{issue}}.zip files/test-{{issue}}"
    - name: Unpack zip file
      unarchive:
        src: "files/test-{{issue}}.zip"
        dest: "/tmp/test-{{issue}}"
        copy: no
        extra_opts:
          - "-qq"
      register: testing
```
