### ISSUE TITLE
issue with azure_rm_deployment module 

### ISSUE THREAD

**Issue by bhismnarayan** [ansible/ansible#35539]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
azure_rm_deployment
##### ANSIBLE VERSION

```
ansible 2.4.2.0

```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### SUMMARY
When I try run playbook to create resource using arm template I get below error.
fatal: [localhost]: FAILED! => {"changed": false, "failed_deployment_operations": [], "msg": "Deployment failed with status code: 400 and message: Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 7, position 1.'."}

I am able to run the same azure template from visual studio. 

##### STEPS TO REPRODUCE

```
- hosts: localhost
  connection: local
  tasks:
    - name: Create Azure Deploy
      azure_rm_deployment:
        resource_group_name: Ansible_ARMTesting
        state: present
        wait_for_deployment_completion: false
        template_link: 'https://github.com/bhismnarayan/ARM/blob/master/ARM1.json'
        parameters_link: 'https://github.com/bhismnarayan/ARM/blob/master/TestArmParameter.json'
      register: azure


```
##### EXPECTED RESULTS
The playbook should run and create two resources in a resource group on azure

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_bCk4Di/ansible_module_azure_rm_deployment.py", line 509, in deploy_template
    deploy_parameter)
  File "/usr/lib/python2.7/site-packages/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py", line 282, in create_or_update
    get_long_running_status, long_running_operation_timeout)
  File "/usr/lib/python2.7/site-packages/msrestazure/azure_operation.py", line 350, in __init__
    raise CloudError(self._response)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed_deployment_operations": [],
    "invocation": {
        "module_args": {
            "ad_user": null,
            "append_tags": true,
            "cli_default_profile": null,
            "client_id": null,
            "cloud_environment": null,
            "deployment_mode": "incremental",
            "deployment_name": "ansible-arm",
            "location": "westus",
            "parameters": null,
            "parameters_link": "https://github.com/bhismnarayan/ARM/blob/master/TestArmParameter.json",
            "password": null,
            "profile": null,
            "resource_group_name": "Ansible_ARMTesting",
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "template": null,
            "template_link": "https://github.com/bhismnarayan/ARM/blob/master/ARM1.json",
            "tenant": null,
            "wait_for_deployment_completion": false,
            "wait_for_deployment_polling_period": 10
        }
    },
    "msg": "Deployment failed with status code: 400 and message: Deployment template parse failed: 'Unexpected character encountered while parsing value: <. Path '', line 7, position 1.'."
}

```
