### ISSUE TITLE
Files created by the copy and template modules should belong to root when  'sudo: true' and 'sudo_user: root' are set

### ISSUE THREAD

**Issue by jlund** [ansible/ansible#3554]
Here's a sample Playbook that demonstrates the issue:

```

---
- hosts: debian7

  sudo: true
  sudo_user: root

  vars:
    name: "foo"

  tasks:
    - name: Copy a file
      copy: src=copy-test
            dest=/tmp/copy-test

    - name: Generate a file from a template
      template: src=template-test.j2
                dest=/tmp/template-test

    - name: Touch a file
      command: touch /tmp/touch-test
```

This playbook is run with the following command:

```
ansible-playbook -u deploy -K -i inventory playbook.yml
```

This creates the following files on the target system:

```
root@debian7:/tmp# ls -al
total 16
drwxrwxrwt  2 root   root   4096 Jul 16 23:49 .
drwxr-xr-x 23 root   root   4096 May  3 20:55 ..
-rw-r--r--  1 deploy deploy   20 Jul 16 23:48 copy-test
-rw-------  1 deploy deploy   10 Jul 16 23:48 template-test
-rw-r--r--  1 root   root      0 Jul 16 23:49 touch-test
```

The 'copy-test' and 'template-test' files both incorrectly belong to the connecting deploy user instead of root, even though the tasks that created them ran as root. One solution is to explicitly set the 'owner' and 'group' arguments, but it would be nice to not have to place these arguments in every file module task when working with systems where direct root logins are not possible.
