### ISSUE TITLE
mysql_user needs extra privileges to grant privs

### ISSUE THREAD

**Issue by michalmedvecky** [ansible/ansible#35552]
##### ISSUE TYPE
 
- Bug Report

##### COMPONENT NAME

modules/database/mysql/mysql_user.py

##### ANSIBLE VERSION
```
ansible 2.3.3.0
  config file = /home/ubuntu/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

ubuntu16.04 + pip

##### SUMMARY

When trying to set up `privs` using `login_user`, this user needs unnecessary privileges:

a) it has to be root (or other kind of super privileges)
b) it needs SELECT privs on `mysql.*` (what we consider dangerous from the security perspective)

The module always does `SELECT` on `mysql.user` to verify the desired user exists ([src](https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql/mysql_user.py#L266-L269)) and `SHOW GRANTS` to check the actual grants ([src](https://github.com/ansible/ansible-modules-core/blob/devel/database/mysql/mysql_user.py#L425)). For the first operation, `SELECT(User,Host)` on `mysql.user` would suffice, but for the latter, `SELECT` on `mysql.*` is necessary:

_SHOW GRANTS requires the SELECT privilege for the mysql database, except to display privileges for the current user._([source](https://dev.mysql.com/doc/refman/5.7/en/show-grants.html))

If the user which we're trying to modify `priv` for previously exists, it automatically has the `USAGE` (== no) grant so this can be assumed by the module if `SHOW GRANTS` fails.

If the user did not previously exist, `GRANT` command will fail anyway (`Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation`); what I consider as expected behavior.

##### STEPS TO REPRODUCE

- Log in to your mysql database as root
- `create database sample;`
- `CREATE TABLE sample.a (c CHAR(20) CHARACTER SET utf8 COLLATE utf8_bin);`
- `create user sample_owner;`
- `create user donald;`
- `GRANT ALL PRIVILEGES ON sample.* TO 'sample_owner'@'%' identified by 'blah' WITH GRANT OPTION;`
- Log out
- create sample playbook:
```
- hosts: localhost
  gather_facts: no
  tasks:
    - mysql_user:
        login_user: "sample_owner"
        login_password: "blah"
        login_host: "<your-mysql-server-address>"
        append_privs: false
        name: "donald"
        priv: "sample.a:SELECT"
        host: "%"
        state: present
```

##### EXPECTED RESULTS

grant privileges

##### ACTUAL RESULTS
```
TASK [mysql_user] ***********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "(1044, \"Access denied for user 'sample_owner'@'%' to database 'mysql'\")"}
	to retry, use: --limit @/home/ubuntu/sqltest/dbtest.retry
```
