### ISSUE TITLE
eos_vlan: Interfaces assigned to vlan do not show up if port is not live

### ISSUE THREAD

**Issue by legit-ninja** [ansible/ansible#35567]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_vlan
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/jlee/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

```
DEFAULT_DEBUG(env: ANSIBLE_DEBUG) = True
```
##### OS / ENVIRONMENT

N/A
##### SUMMARY

If a cable is not plugged into an interface on the switch, when attempting to assign the interface to vlan, the interface will not show up as an assigned interface on the vlan.

##### STEPS TO REPRODUCE

Ensure that nothing is connected to interface 5.
Assign interface 5 to vlan 1234
Playbook fails with error "Interface x does not exist

```
    - eos_vlan:
        authorize: yes
        vlan_id: 1234
        name: "example_vlan"
        state: present
        provider: "{{ cli }}"
        interfaces:
          - Ethernet1
          - Ethernet2
          - Ethernet3
          - Ethernet4
          - Ethernet5

```

##### EXPECTED RESULTS

Interface should successfully be assigned to a vlan

##### ACTUAL RESULTS

ansible playbook error "interface x not assigned to vlan"

```

```
