### ISSUE TITLE
Format/filesystem option doesnt' works with volume ec2

### ISSUE THREAD

**Issue by rmsys** [ansible/ansible#35580]
##### ISSUE TYPE
 - Bug Report
 
##### COMPONENT NAME
- ec2

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Sep  1 2016, 22:14:00) [GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
 
```

##### CONFIGURATION
```
"ansible-config dump --only-changed" --> nothing happens
```

##### OS / ENVIRONMENT
- Amazon Linux 4.9.38-16.33.amzn1.x86_64

##### SUMMARY
- I tried create + format/filesystem + mount a additional volume. I got create volume but the others steps doesnt' works

##### STEPS TO REPRODUCE

- Account AWS/permissions to launch new instance EC2

```
    tasks:
    - name: Launch instance
      ec2:
        keypair: "{{ keypair }}"
        group_id: "{{ security_group }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image }}"
        wait: yes
        region: "{{ region }}"
        vpc_subnet_id: subnet-12345678
        assign_public_ip: yes
        spot_price: "{{ spot_price }}"
        spot_wait_timeout: 300000
        instance_profile_name: aws-ec2-lab
        instance_tags:
           Name: lab-{{ node }}

# Option 01: ERRO*

        volumes:
          - device_name: /dev/sdb
            volume_type: 20
            volume_size: gp2
            delete_on_termination: true

    - filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: Mount /lab
      mount:
        path: /lab
        src:  /dev/sdb
        fstype: ext4
        state: present
        
        
# Option 02: ERRO* 

        volumes:
          - device_name: /dev/sdb
            volume_type: 20
            volume_size: gp2
            delete_on_termination: true

    - filesystem:
        fstype: ext4
        dev: /dev/xvdb
        
    - name: Mount /lab
      mount:
        path: /lab
        src:  /dev/xbdb
        fstype: ext4
        state: present


# *ERRO:         

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "dev": "/dev/sdb",
            "force": false,
            "fstype": "ext4",
            "opts": null,
            "resizefs": false
        }
    },
    "msg": "Device /dev/sdb not found."
    
    or 
    
    "msg": "Device /dev/xvdb not found."


# Option without filesystem: the volume is created, but only this.
```

##### EXPECTED RESULTS
- I need format and mount the volume   

##### ACTUAL RESULTS
- Error the volume is not found

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @tgerla @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wufpack00** [comment]
The steps to reproduce don't indicate what host you are executing on, but since ec2 module uses a local connection I would bet that is your issue.

Be sure you are executing the filesystem and mount module on the ec2 instance itself, not on localhost.

**Comment by ryansb** [comment]
needs_info

**Comment by ansibot** [comment]
@rmsys This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rmsys** [comment]
Hey guys, thanks attention. 

But, how to confirm this "Be sure you are executing the filesystem and mount module on the ec2 instance itself, not on localhost." ?

**Comment by tux-b** [comment]
Hello Guys, 
Do we have a resolution here, I seem to be facing similar issue. 

```
# ansible --version
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Jul 13 2018, 13:06:57) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```


My playbook is the following one;

```
---
# Attach EBS, Create Filesystem and remote mount

- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: False
  user: ec2-user
  sudo: yes
#  debugger: on_failed
  vars:
    aws_access_key: "xxxxxxxxxxx"
    aws_secret_key: "xxxxxxxxxxxxxxx"
    region: "ap-south-1"

  tasks:

  - name: Creating a Volume
    ec2_vol:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "{{ region }}"
      instance: 'i-0ed9d8c8f754ff521'
      volume_size: 5
      device_name: /dev/xvdf
      volume_type: gp2
    register: ec2_vol

  - name: Create a ext4 filesystem on /dev/xvdf
    filesystem:
      fstype: ext4
      dev: /dev/xvdf

  - name: mounting the volume
    mount:
      name=/mnt
      fstype=ext4
      state=mounted
      src=/dev/xvdf
```
It is able to attach a Volume to the instance but task fails on Filesytem creation step with the following Error msg;

```
TASK [Create a ext4 filesystem on /dev/xvdf] ********************************************************************************************************
fatal: [172.16.1.5]: FAILED! => {"changed": false, "msg": "**Device /dev/xvdf not found.**"}
        to retry, use: --limit @/etc/ansible/custom/ansible-aws/playbooks/test-vol.retry

```

Any information here would be appreciated.

Regards,

**Comment by cristidas** [comment]
@tux-b @rmsys 

In the first message there is the failure output, showing that the task was executed on the localhost

`fatal: [localhost]: FAILED! =>`

The difference in a verbose output (-vvv on the command line) would be that a task executed on the localhost will start with something like this:
`TASK [filesystem : ] *********************
changed: [localhost] => (item=`

...while one executed on a remote host will start similar to this:
`TASK [filesystem : ] *********************
changed: [localhost -> 39.121.169.22] => (item=`

The `ec2_vol` task is running fine on the localhost because it executes commands against the AWS API, like all the other Ansible AWS cloud modules. 
The `filesystem` and `mount` modules are failing because they are executing commands against an actual host, which if not explicitly defined (in a hosts file or on the command line) will leave these to be executed against localhost.

To achieve your goals, you need to delegate to the newly created EC2 instance the specific OS level system tasks, similar to this:
```
- block:
    - name: Ensure mount directory exists
      file:
        path: /mnt
        state: directory

    - name: Create an ext4 filesystem
      filesystem:
        fstype: ext4
        dev: /dev/xvdf

    - name: Mount up device by label
      mount:
        path: /mnt
        src: /dev/xvdf
        fstype: ext4
        state: mounted
 
  become: yes
  delegate_to: "{{ ec2_facts.instances[0].public_ip_address }}"
```
