### ISSUE TITLE
openssl_certificate module doesn't set Issuer correctly

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#35599]
##### ISSUE TYPE
- Bug Report
##### COMPONENT NAME
openssl_certificate
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'./.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(./ansible.cfg) = True
ANSIBLE_SSH_ARGS(./ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -F ssh_config
ANSIBLE_SSH_CONTROL_PATH(./ansible.cfg) = %(directory)s/ansible-ssh-%%h-%%p-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(./ansible.cfg) = ~/.ansible/cp
DEFAULT_FORKS(./ansible.cfg) = 10
DEFAULT_MODULE_PATH(./ansible.cfg) = [u'./ansible/libraries']
DEFAULT_ROLES_PATH(./ansible.cfg) = [u'./ansible/roles']
DEFAULT_TIMEOUT(./ansible.cfg) = 60
HOST_KEY_CHECKING(./ansible.cfg) = False
RETRY_FILES_ENABLED(./ansible.cfg) = False
##### OS / ENVIRONMENT
macOS High Sierra - Version 10.13.2
 
##### SUMMARY
The generation of any openssl_certificate will be without an valid certificate issuer. This is a big problem, because X509 certificates don't allow self-signed certificates without issuer.

##### STEPS TO REPRODUCE
```yaml
- name: "generate ssl private key file"
  become: yes
  openssl_privatekey:
    path: "/etc/ssl/default.key"
    force: True

- name: "generate ssl certificate request file"
  become: yes
  openssl_csr:
    path: "/etc/ssl/default.csr"
    privatekey_path: "/etc/ssl/default.key"
    subject_alt_name: "DNS:localhost"
    C: "US"
    ST: "AwesomeState"
    L: "BigCity"
    O: "CrazyIT Inc."
    OU: "IT"
    CN: "localhost"
    force: True

- name: "generate ssl certificate"
  become: yes
  openssl_certificate:
    path: "/etc/ssl/default.crt"
    privatekey_path: "/etc/ssl/default.key"
    csr_path: "/etc/ssl/default.csr"
    force: True
    provider: selfsigned
```

##### EXPECTED RESULTS
The certificate should have a valid issuer.

##### ACTUAL RESULTS
```$ openssl s_client -connect localhost:443```
CONNECTED(00000003)
depth=0 C = US, CN = localhost, L = BigCity, O = CrazyIT Inc., ST = AwesomeState, OU = IT
verify error:num=20:unable to get local issuer certificate
verify return:1
