### ISSUE TITLE
vmware_guest: disk size gets not increased

### ISSUE THREAD

**Issue by thorus90** [ansible/ansible#35597]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jrottmann/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 20 2017, 01:25:59) [GCC 7.2.0]
```

##### OS / ENVIRONMENT

running ansible on arch, managing a vcenter on version 5.5

##### SUMMARY

The Disksize gets not increased after changing the values.

EDIT: same happens when trying to add additional disks

##### STEPS TO REPRODUCE

1. Create playbook to deploy vm from a template.
2. Run playbook for the first time, the machine gets created with the disk size from the template, or the size you specified.
3. Increase the disk size specified in your playbook
4. Rerun the playbook.

```yaml
- name: VMware Deployment
  vmware_guest:
    hostname: "srvvcenter01.master.dns"
    datacenter: "itnovum"
    validate_certs: "false"
    username: "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
    password: "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
    resource_pool: "EIM"
    folder: "itnovum/vm/intern/Dev-Testing/ECM"
    wait_for_ip_address: "True"
    template: "ubuntu-16.04-template"
    name: "test01"
    state: "poweredon"
    networks:
      - ip: "XXX"
        gateway: "XXX"
        netmask: "XXX"
        name: "XXX"
        type: "static"
        vlan: 69
    disk: 
      - datastore: "SATA_EIM"
        size_gb: 100
        type: "thin"
  register: machine_deploy_status
```

##### EXPECTED RESULTS

At the first run create the virtual machine with disk specified, this works! So in my example, my template has one disk with a size of 20GB, if I run the playbook without the parameter disk specified, it gets created with a disk with a size of 20GB, if I run the playbook with i.e. one disk 80GB, the vm gets created with one disk with a size of 80GB.

Now when I increase the disk size to 100GB it should increase the disk in vmware.

##### ACTUAL RESULTS

It did not change the disk size and reported back changed: false.
```
TASK [deployment_vmware : VMware Deployment] *****************************************************************************************************************
task path: /home/jrottmann/Dokumente/git/ansible-root/roles/deployment_vmware/tasks/main.yml:35
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/vmware.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/urls.py
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<172.16.43.100> ESTABLISH LOCAL CONNECTION FOR USER: jrottmann
<172.16.43.100> EXEC /bin/sh -c 'echo ~ && sleep 0'
<172.16.43.100> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jrottmann/.ansible/tmp/ansible-tmp-1517475561.07-130892148119437 `" && echo ansible-tmp-1517475561.07-130892148119437="` echo /home/jrottmann/.ansible/tmp/ansible-tmp-1517475561.07-130892148119437 `" ) && sleep 0'
<172.16.43.100> PUT /tmp/tmpWorUmS TO /home/jrottmann/.ansible/tmp/ansible-tmp-1517475561.07-130892148119437/vmware_guest.py
<172.16.43.100> EXEC /bin/sh -c 'chmod u+x /home/jrottmann/.ansible/tmp/ansible-tmp-1517475561.07-130892148119437/ /home/jrottmann/.ansible/tmp/ansible-tmp-1517475561.07-130892148119437/vmware_guest.py && sleep 0'
<172.16.43.100> EXEC /bin/sh -c '/usr/bin/python /home/jrottmann/.ansible/tmp/ansible-tmp-1517475561.07-130892148119437/vmware_guest.py; rm -rf "/home/jrottmann/.ansible/tmp/ansible-tmp-1517475561.07-130892148119437/" > /dev/null 2>&1 && sleep 0'
ok: [172.16.43.100] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "itnovum", 
            "disk": [
                {
                    "datastore": "SATA_EIM", 
                    "size_gb": 100, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "itnovum/vm/intern/Dev-Testing/ECM", 
            "force": false, 
            "guest_id": null, 
            "hardware": {}, 
            "hostname": "srvvcenter01.master.dns", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "test01", 
            "name_match": "first", 
            "networks": [
                {
                    "gateway": "172.16.43.254", 
                    "ip": "172.16.43.100", 
                    "name": "VLAN_69_ECM-Server", 
                    "netmask": "255.255.255.0", 
                    "type": "static", 
                    "vlan": 69
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": "EIM", 
            "snapshot_src": null, 
            "state": "poweredon", 
            "template": "ubuntu-16.04-template", 
            "username": "SAPDOM\\jrottmann", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }
    }
}
```
