### ISSUE TITLE
ACI Modules single call to the API instead of one per item

### ISSUE THREAD

**Issue by spidernik84** [ansible/ansible#35605]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
aci_* (all modules related to Cisco ACI)

##### ANSIBLE VERSION

```
ansible 2.5.0
  python version = 2.7.14 (default, Dec 11 2017, 16:08:01) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### SUMMARY

The ACI modules expect a list of dictionaries and iterate through each item of the list. Each item pass triggers an API call to the APIC, causing significant delay (authenticate, run call, close session, repeat). This proves particularly inefficient with frequently changing deployments that contain many objects (EPGs, BDs, APs, etc.).

I am not sure of where this should be implemented (module? playbook?), hence I am creating this feature idea. 
Keeping the idempotency is particularly interesting, in that case.

##### STEPS TO REPRODUCE

Part of the playbook:
```yaml
  - name: Bind EPGs to domains
    aci_epg_to_domain:
      <<: *aci_login
      tenant: '{{ item.tenant }}'
      app_profile: '{{ item.app }}'
      epg: '{{ item.epg }}'
      domain: '{{ item.domain }}'
      domain_type: '{{ item.domain_type }}'
    with_items: '{{ epg_to_domain| default([]) }}'

```
`group_vars` file:
```yaml
epg_to_domain:
 - tenant: example_tenant
   app: APP-example1
   epg: net-example1
   domain: Legacy_net_PhysDom
   domain_type: phys
 - tenant: example_tenant
   app: APP-example2
   epg: net-example2
   domain: Legacy_net_PhysDom
   domain_type: phys
 - tenant: example_tenant
   app: APP-example3
   epg: net-example3
   domain: Legacy_net_PhysDom
   domain_type: phys
 - tenant: example_tenant
   app: APP-example4
   epg: net-example4
   domain: Legacy_net_PhysDom
   domain_type: phys
 - tenant: example_tenant
   app: APP-example5
   epg: net-example5
   domain: Legacy_net_PhysDom
   domain_type: phys

```

##### EXPECTED RESULTS

The module goes through the list of items, assembles a single json file, and pushes it to the APIC in a single API call.

##### ACTUAL RESULTS

An API call is run for every item
