### ISSUE TITLE
Add launch_type parameter for ecs_service module

### ISSUE THREAD

**Issue by ramonamis** [ansible/ansible#35607]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

ecs_service

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/ramonamis/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ramonamis/.virtualenvs/devops/lib/python2.7/site-packages/ansible
  executable location = /Users/ramonamis/.virtualenvs/devops/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

By default, the ecs_service module is launching services with launch_type EC2. At the moment it is impossible to use launch_type: "FARGATE" in order to migrate to fargate.

For more details you can check: https://docs.aws.amazon.com/cli/latest/reference/ecs/create-service.html

##### STEPS TO REPRODUCE

It could look something like this: 
```yaml
          - name: deploy service
            ecs_service:
              region: "{{ aws_region }}"
              name: "{{ ecs_task_family }}"
              load_balancers: "{{ ecs_task_load_balancers }}"
              launch_type: "FARGATE"
              state: present
              task_definition: "{{ ecs_task_family  }}"
              cluster: "{{ ecs_cluster_name }}"
              desired_count: "{{ ecs_task_desired_count }}"
```

##### EXPECTED RESULTS

Be able to deploy ecs services to fargate
##### ACTUAL RESULTS

I am not able to deploy ecs services with fargate

```
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": false, "msg": "Unsupported parameters for (ecs_service) module: launch_type Supported parameters include: aws_access_key,aws_secret_key,client_token,cluster,delay,deployment_configuration,desired_count,ec2_url,load_balancers,name,placement_constraints,placement_strategy,profile,region,repeat,role,security_token,state,task_definition,validate_certs"}
```
