### ISSUE TITLE
RFE: Add an option to automatically remove temporary 

### ISSUE THREAD

**Issue by L-B** [ansible/ansible#35611]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

tempfile
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/export/home/laurent/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The `tempfile` module creates temporary files that can be easily forgotten or left dangling if a run was interrupted. It would be useful For Ansible to keep track of the created files and to have a `delete` option or similar (default: `no`) to have them removed automatically at the end of the run.  

##### STEPS TO REPRODUCE

Use the `tempfile` module to create temporary files.

```yaml

```

##### EXPECTED RESULTS

Have the temporary files deleted at the end of the run.

##### ACTUAL RESULTS

Temporary files are left alone and must be deleted by a separate task or handler.

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/tempfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/tempfile.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by imjoseangel** [comment]
Hi! Is it not enough managing it within a block? (Just asking)

**Example:**

```
- name: Main
block:
    - name: Create temporary directory
    tempfile:
        state: directory
        prefix: "{{ path|basename }}"
    register: _tmp

    - name: Set temporary working directory
    set_fact:
        work_dir: "{{ _tmp.path }}"

always:

    - name: Remove temporary directory
    file:
        path         : "{{ work_dir }}"
        state        : absent
    delegate_to    : localhost
    delegate_facts : true
```

**Comment by ansibot** [comment]
cc @krzysztof-magosa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by marcemv** [comment]
Hello,

Solution provided by @imjoseangel may work if some cases, but If a task is tagged as "always", it will be executed as soon as all the play is not failing, but if a previous task fails, next tasks won't be executed, even if they are tagged as "always".


**Example:**
```yaml
---
- hosts: localhost

  tasks:

    - name: "Force failing to check whether next task is executed or not"
      fail:

    - debug:
        msg: "This task is tagged as always, but is not executed because play crashed before."
      tags: always
```

What I do to workaround this is to register the task that creates the temporary file and use a handler to remove those files at the end, and use `force_handlers: True` to ensure that handler is always executed, even if the playbook fails.


**Workaround**
```yaml
- hosts: all
  force_handlers: True
    tasks: 
      - name: Create temporary file
        tempfile:
          state: file
          prefix: "temp_"
        register: temporary

    handlers:
      - name: "Delete temporary"
        file:
          path: "{{ temporary.path }}"
          state: absent
```

Note that `force_handlers: True` is set to ensure that temporary files are deleted, even if the playbook fails at some point.

I hope this help you :)

Regards.
