### ISSUE TITLE
Ansible URI module is removing character from the post data

### ISSUE THREAD

**Issue by gothiyag** [ansible/ansible#35631]
#### component name
URI

#### Description
There is a problem with SSH private_key direct posting. when i post it with ssh private key, it is removing "+" sign from the content. Am using ansible for this.

```yaml
name: configure ssh credential
uri:
url: "https://{{ host_ip }}/credentials/store/system/domain/_/createCredentials"
method: POST
headers:
Content-Type: "application/x-www-form-urlencoded"
Accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8"
Accept-Encoding: "gzip, deflate, br"
others: "--data-urlencode"
body: 'json={"": "6",
"credentials": {
"scope": "GLOBAL",
"username": "{{ ssh_cred.value.username }}",
"privateKeySource": {
"value": "0",
"privateKey": "-----BEGIN RSA PRIVATE KEY-----
/abbhsshsnne +bbbebe
----END RSA PRIVATE KEY-----",
"stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey$DirectEntryPrivateKeySource"
},
"passphrase": "{{ ssh_cred.value.passphrase }}",
"id": "{{ ssh_cred.value.id }}",
"description": "{{ ssh_cred.value.description }}",
"stapler-class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey",
"$class": "com.cloudbees.jenkins.plugins.sshcredentials.impl.BasicSSHUserPrivateKey"
}
}'
validate_certs: no
follow_redirects: yes
register: login
return_content: yes
with_dict: "{{ ssh_credentials }}"
loop_control:
loop_var: ssh_cred
```

This is removing + sign which in the private key. also if you read the key from any variable, it is adding 'u[ private key]'
am i doing anything wrong ?
