### ISSUE TITLE
vmware_guest: fails when using underscore in name of VM

### ISSUE THREAD

**Issue by Koleon** [ansible/ansible#35646]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/koleon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

No changes

##### OS / ENVIRONMENT

Ansible running from Ubuntu 16.04
Managing CentOS 7.4
vCenter 6.5
pyvmomi==6.5.0.2017.5.post1

##### SUMMARY

Using a VM name with underscore e.g. "05_awx" via vmware_guest when creating a VM from a template, the create fails. For example, specifying "05_awx" results in:

"msg": "A specified parameter was not correct: spec.identity.hostName"

##### STEPS TO REPRODUCE

```yaml
- name: Create a VM from a template
  vmware_guest:
    hostname: "{{ vCenter_hostname }}"
    username: "{{ vCenter_username }}"
    password: "{{ vCenter_password }}"
    validate_certs: no
    datacenter: BM-LAB
    name: 05_awx
    state: poweredon
    template: "{{vmware_template }}"
    folder: "{{ folder }}"
    disk:
    - size_gb: 20
      type: thin
      datastore: "{{ datastore }}"
    hardware:
      memory_mb: "{{ RAM }}"
      num_cpus: "{{ vCPU }}"
    networks:
    - name: "{{ portgroup_name }}"
      type: static
      ip: "{{ ip_addr }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gtw }}"
```

##### EXPECTED RESULTS

VM created and customized with name "05_awx"

##### ACTUAL RESULTS

"msg": "A specified parameter was not correct: spec.identity.hostName"

```
fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": true, 
    "clone_method": "Clone", 
    "clonespec": {
        "config": {
            "alternateGuestName": null, 
            "annotation": null, 
            "bootOptions": null, 
            "changeTrackingEnabled": null, 
            "changeVersion": null, 
            "consolePreferences": null, 
            "cpuAffinity": null, 
            "cpuAllocation": null, 
            "cpuFeatureMask": [], 
            "cpuHotAddEnabled": "<type 'bool'>", 
            "cpuHotRemoveEnabled": null, 
            "crypto": null, 
            "deviceChange": [
                {
                    "backing": null, 
                    "device": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualVmxnet3'>", 
                    "dynamicProperty": [], 
                    "dynamicType": null, 
                    "fileOperation": null, 
                    "operation": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualDeviceSpec.Operation'>", 
                    "profile": []
                }
            ], 
            "dynamicProperty": [], 
            "dynamicType": null, 
            "extraConfig": [], 
            "files": null, 
            "firmware": null, 
            "flags": null, 
            "ftInfo": null, 
            "guestAutoLockEnabled": null, 
            "guestId": null, 
            "instanceUuid": null, 
            "latencySensitivity": null, 
            "locationId": null, 
            "managedBy": null, 
            "maxMksConnections": null, 
            "memoryAffinity": null, 
            "memoryAllocation": null, 
            "memoryHotAddEnabled": "<type 'bool'>", 
            "memoryMB": "<type 'int'>", 
            "memoryReservationLockedToMax": null, 
            "messageBusTunnelEnabled": null, 
            "migrateEncryption": null, 
            "name": null, 
            "nestedHVEnabled": null, 
            "networkShaper": null, 
            "npivDesiredNodeWwns": null, 
            "npivDesiredPortWwns": null, 
            "npivNodeWorldWideName": [], 
            "npivOnNonRdmDisks": null, 
            "npivPortWorldWideName": [], 
            "npivTemporaryDisabled": null, 
            "npivWorldWideNameOp": null, 
            "npivWorldWideNameType": null, 
            "numCPUs": "<type 'int'>", 
            "numCoresPerSocket": null, 
            "powerOpInfo": null, 
            "repConfig": null, 
            "scheduledHardwareUpgradeInfo": null, 
            "swapPlacement": null, 
            "tools": null, 
            "uuid": null, 
            "vAppConfig": null, 
            "vAppConfigRemoved": null, 
            "vAssertsEnabled": null, 
            "vPMCEnabled": null, 
            "version": null, 
            "virtualICH7MPresent": null, 
            "virtualSMCPresent": null, 
            "vmProfile": []
        }, 
        "customization": "<class 'pyVmomi.VmomiSupport.vim.vm.customization.Specification'>", 
        "dynamicProperty": [], 
        "dynamicType": null, 
        "location": {
            "datastore": "'vim.Datastore:datastore-180':lun_b_vmware", 
            "deviceChange": [], 
            "disk": [], 
            "diskMoveType": null, 
            "dynamicProperty": [], 
            "dynamicType": null, 
            "folder": null, 
            "host": null, 
            "pool": "'vim.ResourcePool:resgroup-173':Resources", 
            "profile": [], 
            "service": null, 
            "transform": null
        }, 
        "memory": null, 
        "powerOn": "<type 'bool'>", 
        "snapshot": null, 
        "template": "<type 'bool'>"
    }, 
    "configspec": {
        "alternateGuestName": null, 
        "annotation": null, 
        "bootOptions": null, 
        "changeTrackingEnabled": null, 
        "changeVersion": null, 
        "consolePreferences": null, 
        "cpuAffinity": null, 
        "cpuAllocation": null, 
        "cpuFeatureMask": [], 
        "cpuHotAddEnabled": "<type 'bool'>", 
        "cpuHotRemoveEnabled": null, 
        "crypto": null, 
        "deviceChange": [
            {
                "backing": null, 
                "device": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualVmxnet3'>", 
                "dynamicProperty": [], 
                "dynamicType": null, 
                "fileOperation": null, 
                "operation": "<class 'pyVmomi.VmomiSupport.vim.vm.device.VirtualDeviceSpec.Operation'>", 
                "profile": []
            }
        ], 
        "dynamicProperty": [], 
        "dynamicType": null, 
        "extraConfig": [], 
        "files": null, 
        "firmware": null, 
        "flags": null, 
        "ftInfo": null, 
        "guestAutoLockEnabled": null, 
        "guestId": null, 
        "instanceUuid": null, 
        "latencySensitivity": null, 
        "locationId": null, 
        "managedBy": null, 
        "maxMksConnections": null, 
        "memoryAffinity": null, 
        "memoryAllocation": null, 
        "memoryHotAddEnabled": "<type 'bool'>", 
        "memoryMB": "<type 'int'>", 
        "memoryReservationLockedToMax": null, 
        "messageBusTunnelEnabled": null, 
        "migrateEncryption": null, 
        "name": null, 
        "nestedHVEnabled": null, 
        "networkShaper": null, 
        "npivDesiredNodeWwns": null, 
        "npivDesiredPortWwns": null, 
        "npivNodeWorldWideName": [], 
        "npivOnNonRdmDisks": null, 
        "npivPortWorldWideName": [], 
        "npivTemporaryDisabled": null, 
        "npivWorldWideNameOp": null, 
        "npivWorldWideNameType": null, 
        "numCPUs": "<type 'int'>", 
        "numCoresPerSocket": null, 
        "powerOpInfo": null, 
        "repConfig": null, 
        "scheduledHardwareUpgradeInfo": null, 
        "swapPlacement": null, 
        "tools": null, 
        "uuid": null, 
        "vAppConfig": null, 
        "vAppConfigRemoved": null, 
        "vAssertsEnabled": null, 
        "vPMCEnabled": null, 
        "version": null, 
        "virtualICH7MPresent": null, 
        "virtualSMCPresent": null, 
        "vmProfile": []
    }, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "BM-LAB", 
            "disk": [
                {
                    "datastore": "lun_b_vmware", 
                    "size_gb": 20, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "/vm/05_Tools/Kolo", 
            "force": false, 
            "guest_id": null, 
            "hardware": {
                "memory_mb": 1024, 
                "num_cpus": 2
            }, 
            "hostname": "192.168.1.100", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "05_awx", 
            "name_match": "first", 
            "networks": [
                {
                    "gateway": "10.5.0.1", 
                    "ip": "10.5.0.12", 
                    "name": "LAB-Tools_vxw-dvs-176-virtualwire-11-sid-5008-b5008", 
                    "netmask": "255.255.255.0", 
                    "type": "static"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "poweredon", 
            "template": "T_centos-7.4", 
            "username": "test_user@vsphere.local", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "A specified parameter was not correct: spec.identity.hostName"
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@Koleon Thanks for reporting this issue. I am able to create VM with '_' in name

```
$ govc find / |grep 08_VM_
/DC0/vm/Sample/08_VM_7609
```

Could you please check if template that you are using, does not contain FQDN as hostname?

**Comment by Koleon** [comment]
@Akasurde Hello, thanks for the prompt response! 
I am not able to run govc unfortunately, so I manually deployed another VM via vSphere GUI "New VM From This Template..." and after that I did:
```
# cat /etc/hostname
localhost.localdomain
```
**EDIT:** Could you please post version of your pyvmomi?

**Comment by Akasurde** [comment]
@Koleon I am not using govc to deploy VM. I used `vmware_guest` to deploy VM with following playbook 

```yaml
---
- name: Sample
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  hosts: localhost
  tasks:
    - set_fact:
        vm_name: "08_VM_{{ 10000 | random }}"
    - name: deploy vm
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: DC0
        state: present
        folder: /Sample
        guest_id: centos64Guest
        hardware:
          num_cpus: 1
          memory_mb: 1024
        name: "{{ vm_name }}"
        disk:
          - size: 10mb
            datastore: datastore1
```

And my Pyvmomi version - 

```
pyvmomi==6.5.0.2017.5.post1
```

**Comment by Koleon** [comment]
@Akasurde Hurey! I find it out. Please try to add to your playbook network configuration similar to this:
```
networks:
  - name: LAB-Tools_portgroup
    type: static
    ip: 10.5.0.12
    netmask: 255.255.255.0
    gateway: 10.5.0.1
```
With this added configuration I get the error msg from above. Might be similar linked with #24193 and #24768 ??
Btw It's interesting that something like ```size: 10mb``` works for you. Because I got ```"msg": "mb is not a supported unit for disk size. Supported units are kb, mb, gb or tb"``` Seems like it happens when the template has fixed size bigger than newly create VM.
