### ISSUE TITLE
The `azure_rm_networkinterface` is no longer idempotent when creating with old-style ip definition

### ISSUE THREAD

**Issue by maxamillion** [ansible/ansible#35656]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_networkinterface

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 1717444f18) last updated 2018/02/01 20:58:46 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admiller/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/admiller/src/dev/ansible/lib/ansible
  executable location = /home/admiller/src/dev/ansible/bin/ansible
  python version = 2.7.14 (default, Jan 17 2018, 14:28:32) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION

$ ansible-config dump --only-changed

##### OS / ENVIRONMENT

Fedora 27

##### SUMMARY
The `azure_rm_networkinterface` module is not longer idempotent when using the old-style ip configuration definition.

##### STEPS TO REPRODUCE

```yml
- name: Create Azure VM             
  hosts: localhost                  
  connection: local                 
  gather_facts: false               
  tasks:                            
  - name: Create a resource group   
    azure_rm_resourcegroup:         
      name: admillerTestRG          
      location: eastus              
  - name: Create virtual network    
    azure_rm_virtualnetwork:        
      resource_group: admillerTestRG                                    
      name: admillerTestVNet        
      address_prefixes: "10.0.0.0/16"                                   
  - name: Add subnet                
    azure_rm_subnet:                
      resource_group: admillerTestRG                                    
      name: admillerTestSubnet      
      address_prefix: "10.0.1.0/24" 
      virtual_network: admillerTestVNet                                 
  - name: Create public IP address  
    azure_rm_publicipaddress:       
      resource_group: admillerTestRG                                    
      allocation_method: Static     
      name: admillerTestPublicIP    
  - name: Create Network Security Group that allows SSH                 
    azure_rm_securitygroup:         
      resource_group: admillerTestRG                                    
      name: admillerTestNetSecGroup 
      rules:                        
        - name: SSH                 
          protocol: Tcp             
          destination_port_range: 22                                    
          access: Allow             
          priority: 1001            
          direction: Inbound        
  - name: Create virtual network inteface card                          
    azure_rm_networkinterface:      
      resource_group: admillerTestRG                                    
      name: admillerTestNIC         
      virtual_network: admillerTestVNet                                 
      subnet: admillerTestSubnet    
      public_ip_name: admillerTestPublicIP                              
      security_group: admillerTestNetSecGroup                           
  - name: Create VM                 
    azure_rm_virtualmachine:        
      resource_group: admillerTestRG                                    
      name: admillerTestCentOSVM    
      vm_size: Standard_DS1_v2      
      admin_username: azureuser     
      ssh_password_enabled: false   
      managed_disk_type: Premium_LRS                                    
      network_interfaces: admillerTestNIC                               
      ssh_public_keys:              
        - path: /home/azureuser/.ssh/authorized_keys                    
          key_data: "ssh-rsa AAAA...."
      image:                        
        offer: CentOS               
        publisher: OpenLogic        
        sku: '7.4'                  
        version: latest  
```

##### EXPECTED RESULTS

The `azure_rm_networkinterface` task to be idempotent between playbook runs.

##### ACTUAL RESULTS
Before:
```
$(ansible)  ansible-playbook createvm.yml                               
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'                    


PLAY [Create Azure VM] *************************************************************************************************************************

TASK [Create a resource group] *****************************************************************************************************************
changed: [localhost]                

TASK [Create virtual network] ******************************************************************************************************************
changed: [localhost]                

TASK [Add subnet] ******************************************************************************************************************************
changed: [localhost]                

TASK [Create public IP address] ****************************************************************************************************************
changed: [localhost]                

TASK [Create Network Security Group that allows SSH] *******************************************************************************************
changed: [localhost]                

TASK [Create virtual network inteface card] ****************************************************************************************************
[DEPRECATION WARNING]: Setting ip_configuration flatten is deprecated and will be removed. Using ip_configurations list to define the ip        
configuration. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in       
ansible.cfg.                        
changed: [localhost]                

TASK [Create VM] *******************************************************************************************************************************
changed: [localhost]                

PLAY RECAP *************************************************************************************************************************************
localhost                  : ok=7    changed=7    unreachable=0    failed=0                                                                     

$(ansible)  ansible-playbook createvm.yml                               
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'                    


PLAY [Create Azure VM] *************************************************************************************************************************

TASK [Create a resource group] *****************************************************************************************************************
ok: [localhost]                     

TASK [Create virtual network] ******************************************************************************************************************
ok: [localhost]                     

TASK [Add subnet] ******************************************************************************************************************************
ok: [localhost]                     

TASK [Create public IP address] ****************************************************************************************************************
ok: [localhost]                     

TASK [Create Network Security Group that allows SSH] *******************************************************************************************
ok: [localhost]                     

TASK [Create virtual network inteface card] ****************************************************************************************************
[DEPRECATION WARNING]: Setting ip_configuration flatten is deprecated and will be removed. Using ip_configurations list to define the ip        
configuration. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in       
ansible.cfg.                        
changed: [localhost]                

TASK [Create VM] *******************************************************************************************************************************
ok: [localhost]                     

PLAY RECAP *************************************************************************************************************************************
localhost                  : ok=7    changed=1    unreachable=0    failed=0    
```
