### ISSUE TITLE
VMware: Assign network adapter in promisc mode

### ISSUE THREAD

**Issue by machard84** [ansible/ansible#35657]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

vmware_guest 

##### ANSIBLE VERSION

```
ansible 2.4.2.0 from CentOS extras repository
```

##### OS / ENVIRONMENT

CentOS 7 template
Ubuntu => 14.04 Template
VCSA => 6.0
ESXI => 6.0
VMFS => 5.0
VSwitch

##### SUMMARY

Please impliment a Promisc option when configuring interfaces using the vmware_guest module.

##### STEPS TO REPRODUCE

```yaml
<code yaml>
---
- name:
  vmware_guest:
  ... 
    hardware:
      vm_nic2: 
        type: vmxnet3                                 ### 1. add a second nic with type vmxnet3
    networks:
      - name: "{{ network }}"
        ip: "{{ ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
      - name: "{{ sniff_network }}"             ### configure the new nic to sit on a preconfigured vlan
        (ip|promisc): (promisc|yes)          ### 2. do not assign IP address to this nic, put it in promisc mode
  ...
</code>
```

##### EXPECTED RESULTS

1. Network interface is added 
and 
2. Instead of IP address being applied it is put into promisc mode

Current results and conversations with akasurde and jtanner show that this is currently not supported by this fantastic module so feature request has been made.

##### ACTUAL RESULTS

```

```
