### ISSUE TITLE
vmware_guest: vm_cdrom + kickstart installation

### ISSUE THREAD

**Issue by dkirrane** [ansible/ansible#35665]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible-playbook 2.5.0
  config file = //ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/lib/ansible
  executable location = /opt/ansible/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

CentOS 7 64-bit

##### SUMMARY

I want to create a VM from an ISO and provide a Kickstart file in order to bypass the CentOS Installer UI.

Currently, I can create the VM from an ISO as per https://github.com/ansible/ansible/issues/21112
However, I have to then manually open up the vSphere Client UI and Open Console and use the OS Installer in order to install the OS on the VM.

##### STEPS TO REPRODUCE

```yaml
    hardware:
      memory_mb: 2048
      num_cpus: 2
      scsi: paravirtual
    vm_cdrom:
        type: "iso"
        iso_path: "DatastoreName/cd-image.iso"
```

Possibly add an option for a kicktstart file
```yaml
      vm_cdrom:
        type: "iso"
        iso_path: "DatastoreName/cd-image.iso"
        kickstart: "DatastoreName/kickstart/anaconda-ks.cfg"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cigamit** [comment]
I don't believe this is possible via the VMWare API (or even in the VMWare UI).  I would recommend that you remaster your ISOs to include the kickstart script itself.  Granted, doing ISO installs every time kinda defeats the purpose of templates.

**Comment by dagwieers** [comment]
Look at https://github.com/ansible-provisioning/ansible-provisioning for a small playbook that creates a custom ISO per target node with a custom templated kickstart file baked into the ISO (so you don't rely on a working network for stage 2).

This process works for every RHEL version, using a different kickstart template for each major release (e.g. to tweak the package list or use newer kickstart directives) and possibly using a different isolinux.cfg (because you may want to add different boot parameters to the kernel).

**Comment by dagwieers** [comment]
That said, an OOB solution to read from and write to the console (like is possible with iLO, UCS, RSA, etc...) would be useful for automating certain things that are impossible to automate otherwise because the device is isolated, or the installation process is proprietary and interactive.

It would enable a vmware_expect module to interact with it (if it was console-based).

**Comment by phemmer** [comment]
I was also trying to do this same thing. I don't like the idea of modifying an ISO as it's complex, sucks up a lot of temporary space, and sucks up a ton of network having to transfer the ISO to the ansible box, and then from ansible box to vSphere.

So I came up with an alternative solution.

I've put up 2 pull requests for ansible 2.5 ([one bug fix](https://github.com/ansible/ansible/pull/37868), [one feature](https://github.com/ansible/ansible/pull/37869)), and I can now automatically kickstart a VM using ansible.

The playbook basically looks like this:

```yaml
- name: generate kickstart file
  template:
    src: kickstart.cfg.j2
    dest: '{{role_path}}/files/kickstart.cfg'

- name: build kickstart iso
  command: python '{{role_path}}/files/kickstart-iso.py' '{{role_path}}/files/kickstart.cfg' '{{role_path}}/files/kickstart.iso'

- name: upload kickstart ISO to vSphere
  vsphere_copy:
    host: '{{vsphere_host}}'
    validate_certs: false
    login: '{{vsphere_user}}'
    password: '{{vsphere_password}}'
    datacenter: '{{vsphere_datacenter}}'
    datastore: '{{vsphere_datastore}}'
    src: '{{role_path}}/files/kickstart.iso'
    path: '{{vsphere_kickstart_iso_path}}'

- name: launch vm
  vmware_guest:
    hostname: '{{vsphere_host}}'
    validate_certs: false
    username: '{{vsphere_user}}'
    password: '{{vsphere_password}}'
    datacenter: '{{vsphere_datacenter}}'
    folder: /Templates
    name: '{{vsphere_installer_iso_name}}'
    guest_id: centos64Guest
    hardware:
      memory_mb: 8192
      num_cpus: 3
    disk:
    - autoselect_datastore: true
      type: thin
      size_gb: 16
    networks:
    - name: '{{vsphere_network}}'
    cdrom:
    - type: iso
      iso_path: '[{{vsphere_datastore}}] {{vsphere_installer_iso_path}}'
    - type: iso
      iso_path: '[{{vsphere_datastore}}] {{vsphere_kickstart_iso_path}}'
```
With the `kickstart-iso.py` being:
```python
#!/usr/bin/env python
import sys
import pycdlib

iso = pycdlib.PyCdlib()
iso.new(vol_ident="OEMDRV", rock_ridge="1.09")

iso.add_file(sys.argv[1], "/KS.CFG;1", rr_name="ks.cfg")
iso.write(sys.argv[2])
iso.close()
```
