### ISSUE TITLE
Ansible returns error in Yum module with state=absent and package is not installed

### ISSUE THREAD

**Issue by jeroenjacobs79** [ansible/ansible#35672]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Yum

##### ANSIBLE VERSION

```
2.4.3.0
```

##### OS / ENVIRONMENT
Linux 

##### SUMMARY

Yum fails when it shouldn't

##### STEPS TO REPRODUCE

Given the following tasks:

```
- name: install elrepo gpg key
  rpm_key: key=" https://www.elrepo.org/RPM-GPG-KEY-elrepo.org" state=present

- name: install elrepo repository
  yum: name=" http://www.elrepo.org/elrepo-release-{{ elrepo_version }}.el7.elrepo.noarch.rpm" state=present

# for concourse to work correctly, kernel > 4.10 is required.

- name: uninstall default kernel and tools
  yum: name="{{ item }}" state=absent
  with_items:
    - kernel
    - kernel-tools
    - kernel-devel
    - kernel-tools-libs

- name: install elrepo mainline kernel
  yum: name="{{ item }}" state=present enablerepo="elrepo-kernel" update_cache=yes
  register: mainline_installed
  with_items:
    - kernel-ml
    - kernel-ml-tools
    - kernel-ml-devel
    - kernel-ml-tools-libs
```

Will result in an error when uninstalling kernel, kernel-tools, kernels-devel, and kernel-tools-libs

```
failed: [jeroen-k8-test-lb-01] (item=[u'kernel', u'kernel-tools', u'kernel-devel', u'kernel-tools-libs']) => {"changed": false, "failed": true, "item": ["kernel", "kernel-tools", "kernel-devel", "kernel-tools-libs"], "msg": "", "rc": 0, "results": ["kernel-devel is not installed", "Loaded plugins: fastestmirror, remove-with-leaves\nResolving Dependencies\n--> Running transaction check\n---> Package kernel.x86_64 0:3.10.0-514.26.2.el7 will be erased\n---> Package kernel-tools.x86_64 0:3.10.0-693.11.6.el7 will be erased\n---> Package kernel-tools-libs.x86_64 0:3.10.0-693.11.6.el7 will be erased\n--> Finished Dependency Resolution\n\nDependencies Resolved\n\n================================================================================\n Package               Arch       Version                    Repository    Size\n================================================================================\nRemoving:\n kernel                x86_64     3.10.0-514.26.2.el7        @updates     148 M\n kernel-tools          x86_64     3.10.0-693.11.6.el7        @updates     259 k\n kernel-tools-libs     x86_64     3.10.0-693.11.6.el7        @updates      18 k\n\nTransaction Summary\n================================================================================\nRemove  3 Packages\n\nInstalled size: 148 M\nDownloading packages:\nRunning transaction check\nRunning transaction test\nTransaction test succeeded\nRunning transaction\n  Erasing    : kernel-tools-3.10.0-693.11.6.el7.x86_64                      1/3 \n  Erasing    : kernel-3.10.0-514.26.2.el7.x86_64                            2/3 \n  Erasing    : kernel-tools-libs-3.10.0-693.11.6.el7.x86_64                 3/3 \n  Verifying  : kernel-tools-libs-3.10.0-693.11.6.el7.x86_64                 1/3 \n  Verifying  : kernel-tools-3.10.0-693.11.6.el7.x86_64                      2/3 \n  Verifying  : kernel-3.10.0-514.26.2.el7.x86_64                            3/3 \n\nRemoved:\n  kernel.x86_64 0:3.10.0-514.26.2.el7                                           \n  kernel-tools.x86_64 0:3.10.0-693.11.6.el7                                     \n  kernel-tools-libs.x86_64 0:3.10.0-693.11.6.el7                                \n\nComplete!\n"]}
```

If I understand correctly, it fails because kernel-devel is not installed. Since this matches the condition of being "absent", why is this considered an error?
