### ISSUE TITLE
Allow roles to be interpolated from --extra-vars

### ISSUE THREAD

**Issue by ralph-tice** [ansible/ansible#3567]
Given a playbook of the form:

```
#ansible-playbook this.yml --extra-vars "rolevar=myrole"

---
- name: Configure instance(s)
  hosts: launched
  sudo: True
  roles: 
    - role: "{{ rolevar }}"
```

but instead I get:    
# ERROR: cannot find role in /ansible/roles/{{rolevar}}

Extra brownie points if you get vars_prompt to function similarly:

```
#ansible-playbook this.yml 

---
- name: Configure instance(s)
  hosts: launched
  sudo: True
  vars_prompt:
    rolevar: "enter role to configure"
  roles: 
    - role: "{{ rolevar }}"
```
# ERROR: cannot find role in /ansible/roles/{{rolevar}} or /ansible/{{rolevar}}
