### ISSUE TITLE
socket_path: None Win10 Linux Emulator

### ISSUE THREAD

**Issue by ajayreddy28390** [ansible/ansible#35707]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /mnt/c/Users/ajayr/Documents/overall_example/ansible.cfg
  configured module search path = [u'/home/ajayreddy28390/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ajayreddy28390/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ajayreddy28390/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/mnt/c/Users/ajayr/Documents/overall_example/ansible.cfg) = [u'/mnt/c/Users/ajayr/Documents/overall_example/hosts']
DEFAULT_TIMEOUT(/mnt/c/Users/ajayr/Documents/overall_example/ansible.cfg) = 5
DEFAULT_TRANSPORT(/mnt/c/Users/ajayr/Documents/overall_example/ansible.cfg) = paramiko
HOST_KEY_CHECKING(/mnt/c/Users/ajayr/Documents/overall_example/ansible.cfg) = False

##### OS / ENVIRONMENT

Windows 10 Linux Emulator
##### SUMMARY

Ansible unable connect to hosts using SSH
##### STEPS TO REPRODUCE

```yaml
cat ansible.cfg
[defaults]
transport = paramiko
hostfile = ./hosts
host_key_checking = false
timeout = 5
ajayreddy28390@DESKTOP-0KSKK6B:/mnt/c/Users/ajayr/Documents/overall_example$ cat IOS_test.yml
---
- name: show version
  hosts: "ios-devices"
  gather_facts: false
  connection: local

  vars:
   cli:
     host: "{{ inventory_hostname }}"
     username: cisco
     password: Qazwsx12

  tasks:
    - name: show version
      ios_command:
        commands: show version
        provider: "{{ cli }}"

      register: output

    - name: show output
      debug:
        var: output.stdout

    - name: copy output to file
      copy: content="{{ output }}" dest=./output/{{ inventory_hostname }}.txt
[overall_example.zip](https://github.com/ansible/ansible/files/1693025/overall_example.zip)

```

##### ACTUAL RESULTS

```
/mnt/c/Users/ajayr/Documents/overall_example$ ansible-playbook IOS_test.yml -vvvv
ansible-playbook 2.4.3.0
  config file = /mnt/c/Users/ajayr/Documents/overall_example/ansible.cfg
  configured module search path = [u'/home/ajayreddy28390/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ajayreddy28390/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ajayreddy28390/.local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /mnt/c/Users/ajayr/Documents/overall_example/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]hostfile option, The key is misleading as it can also be a list of hosts, a directory or a list of paths . This
feature will be removed in version 2.8. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
setting up inventory plugins
Parsed /mnt/c/Users/ajayr/Documents/overall_example/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/ajayreddy28390/.local/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: IOS_test.yml *******************************************************************************************************************************
1 plays in IOS_test.yml

PLAY [show version] **********************************************************************************************************************************
META: ran handlers

TASK [show version] **********************************************************************************************************************************
task path: /mnt/c/Users/ajayr/Documents/overall_example/IOS_test.yml:14
<192.168.24.250.xip.io> using connection plugin network_cli
<192.168.24.254.xip.io> using connection plugin network_cli
<192.168.24.250.xip.io> socket_path: None
fatal: [192.168.24.250.xip.io]: FAILED! => {
    "changed": false,
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}
<192.168.24.254.xip.io> socket_path: None
fatal: [192.168.24.254.xip.io]: FAILED! => {
    "changed": false,
    "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"
}
        to retry, use: --limit @/mnt/c/Users/ajayr/Documents/overall_example/IOS_test.retry

PLAY RECAP *******************************************************************************************************************************************
192.168.24.250.xip.io      : ok=0    changed=0    unreachable=0    failed=1
192.168.24.254.xip.io      : ok=0    changed=0    unreachable=0    failed=1
```
