### ISSUE TITLE
not work! ec2_eni: Remove any secondary IP addresses from an existing ENI 

### ISSUE THREAD

**Issue by ptux** [ansible/ansible#35711]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME
ec2_eni

##### ANSIBLE VERSION

```
2.3.2.0
```

##### SUMMARY

this sample written on doc is not work!!!

```yaml
- ec2_eni:
    subnet_id: subnet-xxxxxxxx
    eni_id: eni-yyyyyyyy
    state: present
    secondary_private_ip_addresses:
      -
```

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Value (None) for parameter privateIpAddress is invalid. Not a valid IP address"}
```
##### FIX

This works!!!
Cloud you fix the doc?

```yaml
        - ec2_eni:
          region: "ap-northeast-1"
          subnet_id: subnet-xxxxxxxx
          private_ip_address: xxx.xxx.xxx.xxx
          state: present
          secondary_private_ip_address_count: 0
```
