### ISSUE TITLE
Serialization issue with vmware_guest 

### ISSUE THREAD

**Issue by merloon** [ansible/ansible#35721]
Hi, 

I have troubles with vmware_guest plugin when I want to add disks to a Virtual machine.

See informations below: 

- Component Name: 
vmware_guest

- task: 
```
- name: add new disks on {{ vmware_vm_name }}
  vmware_guest:
    hostname: "{{ vmware_vsphere_server }}"
    username: "{{ vmware_vsphere_user }}"
    password: "{{ vmware_vsphere_pass }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter }}"
    cluster: "{{ vmware_cluster }}"
    guest_id: "{{ vmware_vm_name }}"
    name: "{{ vmware_vm_name }}"
    hardware:
      memory_mb: "{{ vmware_vm_hw_memory }}"
      num_cpus: "{{ vmware_vm_hw_cpu }}"
    disk:
    - size_gb: "{{ item.value.size }}"
      datastore: "{{ item.value.datastore }}"
      type: "{{ item.value.type }}"
  with_dict: "{{ disks }}"
```
- My variables: 
```
disks:
  disk1:
      size: '6'
      datastore: LAB_Datastore_1
      type: thin
      usage: product
  disk2:
      size: '8'
      datastore: LAB_Datastore_1
      type: thin
      usage: files
```

- Ansible version: 

```
ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```
- OS Version:
```
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```
You can find logs attach 
[logs.txt](https://github.com/ansible/ansible/files/1667033/logs.txt)

Thanks by advance. 

BR 

Merloon

**Comment by ansibot** [comment]
@merloon Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @akasurde @alikins @dagwieers @dav1x @jctanner @nerzhul @pdellaert @saito-hideki
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@merloon Thanks for reporting this issue. I am working on this.

**Comment by Akasurde** [comment]
@merloon Could you please check this PR and let me know if it works for you ? 

needs_info

**Comment by Akasurde** [comment]
resolved_by_pr #35727

**Comment by merloon** [comment]
Hi, 

Changing the vmware.py file, the error disapear. 
But it don't want to create the vm with 2 additionnal disks. 
I've got this error: 
Given disk size is smaller than found (6291456 < 36700160). Reducing disks is not allowed

```
changed: [localhost] => (item={'value': {u'usage': u'system', u'datastore': u'LAB_Datastore_1', u'type': u'thin', u'size': u'35'}, 'key': u'disk0'}) => {"changed": true, "instance": {"annotation": "", "current_snapshot": null, "customvalues": {}, "guest_tools_status": "guestToolsNotRunning", "guest_tools_version": "10245", "hw_eth0": {"addresstype": "assigned", "ipaddresses": null, "label": "Network adapter 1", "macaddress": "00:50:56:9c:c0:77", "macaddress_dash": "00-50-56-9c-c0-77", "summary": "DVSwitch: 50 1c 60 5b cb 5e 30 ed-6f 48 34 d3 68 df fa 5f"}, "hw_guest_full_name": null, "hw_guest_id": null, "hw_interfaces": ["eth0"], "hw_memtotal_mb": 1024, "hw_name": "dcttstvllp01", "hw_power_status": "poweredOn", "hw_processor_count": 1, "hw_product_uuid": "421c286c-3ff1-18ba-2f6f-d9d3db2a3908", "ipv4": null, "ipv6": null, "module_hw": true, "snapshots": []}, "item": {"key": "disk0", "value": {"datastore": "LAB_Datastore_1", "size": "35", "type": "thin", "usage": "system"}}}
failed: [localhost] (item={'value': {u'usage': u'product', u'datastore': u'LAB_Datastore_1', u'type': u'thin', u'size': u'6'}, 'key': u'disk1'}) => {"changed": false, "item": {"key": "disk1", "value": {"datastore": "LAB_Datastore_1", "size": "6", "type": "thin", "usage": "product"}}, "msg": "Given disk size is smaller than found (6291456 < 36700160). Reducing disks is not allowed."}
failed: [localhost] (item={'value': {u'usage': u'files', u'datastore': u'LAB_Datastore_1', u'type': u'thin', u'size': u'8'}, 'key': u'disk2'}) => {"changed": false, "item": {"key": "disk2", "value": {"datastore": "LAB_Datastore_1", "size": "8", "type": "thin", "usage": "files"}}, "msg": "Given disk size is smaller than found (8388608 < 36700160). Reducing disks is not allowed."}
```

**Comment by Akasurde** [comment]
@merloon Thats great. Could you please paste the playbook and `-vvv` output so that we can debug it ? 

Also, could you please mark "shipit" on PR ?

**Comment by merloon** [comment]
Hi, 

Find informations below: 
- task
```
---

- name: Create VM {{ vmware_vm_name }}
  vmware_guest:
    hostname: "{{ vmware_vsphere_server }}"
    username: "{{ vmware_vsphere_user }}"
    password: "{{ vmware_vsphere_pass }}"
    validate_certs: no
    datacenter: "{{ vmware_datacenter }}"
    cluster: "{{ vmware_cluster }}"
    name: "{{ vmware_vm_name }}"
    template: "{{ vmware_vm_template }}"
    folder: "{{ vmware_vm_folder }}"
    networks:
    - name: "{{ vmware_vm_network }}"
      ip: "{{ vmware_vm_ip }}"
      netmask: "{{ vmware_vm_mask }}"
      gateway: "{{ vmware_vm_gw }}"
      domain: "{{ vmware_vm_domain }}"
      dns_servers:
        - "{{ vmware_vm_dns }}"
    hardware:
      memory_mb: "{{ vmware_vm_hw_memory }}"
      num_cpus: "{{ vmware_vm_hw_cpu }}"
    state: poweredon
    disk:
    - size_gb: "{{ item.value.size }}"
      datastore: "{{ item.value.datastore }}"
      type: "{{ item.value.type }}"
  with_dict: "{{ disks }}"
  register: deploy
  tags: deployvm
```
- Variables used
```
disks:
  disk0:
      size: '35'
      datastore: LAB_Datastore_1
      type: thin
      usage: system
  disk1:
      size: '6'
      datastore: LAB_Datastore_1
      type: thin
      usage: product
  disk2:
      size: '8'
      datastore: LAB_Datastore_1
      type: thin
      usage: files
```

- output

```
ansible-playbook -vvvv main.yml -e ext_layer=lab -e vm_name=dcttstvllp01
ansible-playbook 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
Trying secret FileVaultSecret(filename='/etc/ansible/.vaultpass') for vault_id=default
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Read vars_file 'vars/{{ vm_name }}_disks.yml'
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: main.yml *******************************************************************************************************************************************************************************************************
2 plays in main.yml
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Read vars_file 'vars/{{ vm_name }}_disks.yml'
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Read vars_file 'vars/{{ vm_name }}_disks.yml'

PLAY [localhost] *********************************************************************************************************************************************************************************************************
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Read vars_file 'vars/{{ vm_name }}_disks.yml'

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1517915466.88-274179234889594 `" && echo ansible-tmp-1517915466.88-274179234889594="` echo /root/.ansible/tmp/ansible-tmp-1517915466.88-274179234889594 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp02AI2m TO /root/.ansible/tmp/ansible-tmp-1517915466.88-274179234889594/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1517915466.88-274179234889594/ /root/.ansible/tmp/ansible-tmp-1517915466.88-274179234889594/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1517915466.88-274179234889594/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1517915466.88-274179234889594/" > /dev/null 2>&1 && sleep 0'
ok: [localhost]
META: ran handlers
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Read vars_file 'vars/{{ vm_name }}_disks.yml'

TASK [include_tasks] *****************************************************************************************************************************************************************************************************
task path: /etc/ansible/roles/deploy_server/main.yml:15
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Read vars_file 'vars/{{ vm_name }}_disks.yml'
included: /etc/ansible/roles/deploy_server/create_vm.yml for localhost
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Read vars_file 'vars/{{ vm_name }}_disks.yml'
Read vars_file 'group_vars/vsphere.yml'
Read vars_file 'group_vars/default.yml'
Read vars_file 'group_vars/{{ layer }}.yml'
Read vars_file 'group_vars/vm_to_create.yml'
Read vars_file 'vars/{{ vm_name }}_disks.yml'

TASK [Create VM dcttstvllp01] ********************************************************************************************************************************************************************************************
task path: /etc/ansible/roles/deploy_server/create_vm.yml:3
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1517915475.51-153538233152092 `" && echo ansible-tmp-1517915475.51-153538233152092="` echo /root/.ansible/tmp/ansible-tmp-1517915475.51-153538233152092 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpzblRSG TO /root/.ansible/tmp/ansible-tmp-1517915475.51-153538233152092/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1517915475.51-153538233152092/ /root/.ansible/tmp/ansible-tmp-1517915475.51-153538233152092/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1517915475.51-153538233152092/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1517915475.51-153538233152092/" > /dev/null 2>&1 && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1517915650.32-47989134246025 `" && echo ansible-tmp-1517915650.32-47989134246025="` echo /root/.ansible/tmp/ansible-tmp-1517915650.32-47989134246025 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp0DsHYM TO /root/.ansible/tmp/ansible-tmp-1517915650.32-47989134246025/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1517915650.32-47989134246025/ /root/.ansible/tmp/ansible-tmp-1517915650.32-47989134246025/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1517915650.32-47989134246025/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1517915650.32-47989134246025/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => (item={'value': {u'usage': u'system', u'datastore': u'LAB_Datastore_1', u'type': u'thin', u'size': u'35'}, 'key': u'disk0'}) => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "10245",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": null,
            "label": "Network adapter 1",
            "macaddress": "00:50:56:9c:87:da",
            "macaddress_dash": "00-50-56-9c-87-da",
            "summary": "DVSwitch: 50 1c 60 5b cb 5e 30 ed-6f 48 34 d3 68 df fa 5f"
        },
        "hw_guest_full_name": null,
        "hw_guest_id": null,
        "hw_interfaces": [
            "eth0"
        ],
        "hw_memtotal_mb": 1024,
        "hw_name": "dcttstvllp01",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 1,
        "hw_product_uuid": "421c23b9-c5a7-08ea-d40e-3faff7cbb81d",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "LAB_Cluster",
            "customization": {},
            "customvalues": [],
            "datacenter": "LAB_ToursDC",
            "disk": [
                {
                    "datastore": "LAB_Datastore_1",
                    "size_gb": "35",
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/test/deploy",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 1024,
                "num_cpus": 1
            },
            "hostname": "dctvcrvll02.dctlab.com",
            "is_template": false,
            "linked_clone": false,
            "name": "dcttstvllp01",
            "name_match": "first",
            "networks": [
                {
                    "dns_servers": [
                        "10.9.96.18"
                    ],
                    "domain": "dctlab.com",
                    "gateway": "10.9.97.129",
                    "ip": "10.9.97.156",
                    "name": "SIEM 1 LAB",
                    "netmask": "255.255.255.224"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "template_RedHat_7_DCT_LAB",
            "username": "fmerle@dctlab.com",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "item": {
        "key": "disk0",
        "value": {
            "datastore": "LAB_Datastore_1",
            "size": "35",
            "type": "thin",
            "usage": "system"
        }
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1517915658.26-270096794570259 `" && echo ansible-tmp-1517915658.26-270096794570259="` echo /root/.ansible/tmp/ansible-tmp-1517915658.26-270096794570259 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpBoxFLH TO /root/.ansible/tmp/ansible-tmp-1517915658.26-270096794570259/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1517915658.26-270096794570259/ /root/.ansible/tmp/ansible-tmp-1517915658.26-270096794570259/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /root/.ansible/tmp/ansible-tmp-1517915658.26-270096794570259/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1517915658.26-270096794570259/" > /dev/null 2>&1 && sleep 0'
failed: [localhost] (item={'value': {u'usage': u'product', u'datastore': u'LAB_Datastore_1', u'type': u'thin', u'size': u'6'}, 'key': u'disk1'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "LAB_Cluster",
            "customization": {},
            "customvalues": [],
            "datacenter": "LAB_ToursDC",
            "disk": [
                {
                    "datastore": "LAB_Datastore_1",
                    "size_gb": "6",
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/test/deploy",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 1024,
                "num_cpus": 1
            },
            "hostname": "dctvcrvll02.dctlab.com",
            "is_template": false,
            "linked_clone": false,
            "name": "dcttstvllp01",
            "name_match": "first",
            "networks": [
                {
                    "dns_servers": [
                        "10.9.96.18"
                    ],
                    "domain": "dctlab.com",
                    "gateway": "10.9.97.129",
                    "ip": "10.9.97.156",
                    "name": "SIEM 1 LAB",
                    "netmask": "255.255.255.224"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "template_RedHat_7_DCT_LAB",
            "username": "fmerle@dctlab.com",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "item": {
        "key": "disk1",
        "value": {
            "datastore": "LAB_Datastore_1",
            "size": "6",
            "type": "thin",
            "usage": "product"
        }
    },
    "msg": "Given disk size is smaller than found (6291456 < 36700160). Reducing disks is not allowed."
}
failed: [localhost] (item={'value': {u'usage': u'files', u'datastore': u'LAB_Datastore_1', u'type': u'thin', u'size': u'8'}, 'key': u'disk2'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "LAB_Cluster",
            "customization": {},
            "customvalues": [],
            "datacenter": "LAB_ToursDC",
            "disk": [
                {
                    "datastore": "LAB_Datastore_1",
                    "size_gb": "8",
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "/test/deploy",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 1024,
                "num_cpus": 1
            },
            "hostname": "dctvcrvll02.dctlab.com",
            "is_template": false,
            "linked_clone": false,
            "name": "dcttstvllp01",
            "name_match": "first",
            "networks": [
                {
                    "dns_servers": [
                        "10.9.96.18"
                    ],
                    "domain": "dctlab.com",
                    "gateway": "10.9.97.129",
                    "ip": "10.9.97.156",
                    "name": "SIEM 1 LAB",
                    "netmask": "255.255.255.224"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "template_RedHat_7_DCT_LAB",
            "username": "fmerle@dctlab.com",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "item": {
        "key": "disk2",
        "value": {
            "datastore": "LAB_Datastore_1",
            "size": "8",
            "type": "thin",
            "usage": "files"
        }
    },
    "msg": "Given disk size is smaller than found (8388608 < 36700160). Reducing disks is not allowed."
}
        to retry, use: --limit @/etc/ansible/roles/deploy_server/main.retry

PLAY RECAP ***************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1


```

**Comment by Akasurde** [comment]
@merloon Reducing disk's size is not allowed as this may give inadvertent results. 

Closing this issue as original issue is resolved by #35727. Please feel free to re-open if problem persists.

**Comment by merloon** [comment]
@Akasurde I don't whant to reduce disk but add disks on the vm based on variables. 

- with this: 
```
    disk:
    - size_gb: "{{ item.value.size }}"
      datastore: "{{ item.value.datastore }}"
      type: "{{ item.value.type }}
 with_dict: "{{ disks }}"
```
and I whant to use this array

```
disks:
  disk0:
      size: '35'
      datastore: LAB_Datastore_1
      type: thin
      usage: system
  disk1:
      size: '6'
      datastore: LAB_Datastore_1
      type: thin
      usage: product
  disk2:
      size: '8'
      datastore: LAB_Datastore_1
      type: thin
      usage: files
```

Is it clear ? if not please let me know ? 

BR 

Merloon
