### ISSUE TITLE
ec2_tag Docs need updated.

### ISSUE THREAD

**Issue by jseiser** [ansible/ansible#35738]
##### ISSUE TYPE

 - Documentation Report

##### SUMMARY

https://docs.ansible.com/ansible/latest/ec2_tag_module.html

The excample for a tagging all volumes no longer works. 

##### STEPS TO REPRODUCE

```yaml
- name: Ensure all volumes are tagged
  ec2_tag:
    region:  eu-west-1
    resource: '{{ item.id }}'
    state: present
    tags:
      Name: dbserver
      Env: production
  with_items:
    - ec2_vol.volumes

```

##### EXPECTED RESULTS

Expected to tag all volumes.

##### ACTUAL RESULTS
[localhost]: FAILED! => {     "msg": "The task includes an option with an undefined variable. The error was: 'ansible.utils.unsafe_proxy.AnsibleUnsafeText object' has no attribute 'id'

In IRC I was informed the syntax should now be.

    - '{{ ec2_vol.volumes }}'
