### ISSUE TITLE
ecs volumes

### ISSUE THREAD

**Issue by JoshuaSeidel** [ansible/ansible#35751]
##### ANSIBLE VERSION
2.4

##### COMPONENT NAME
ecs_taskdefinition

having a issune with the following Anisble 2.4 and ecs_taskdefinition module 
```
containers:
- name: "acoms-{{ app_name }}"
  cpu: 50
  essential: true
  image: "harbor.****.******.io/3rdparty/{{ app_name }}:{{ container_ver }}"
  memoryReservation: 1024
  portMappings:
  - containerPort: 3000
    hostPort: 3000
  logConfiguration:
    logDriver: splunk
    options:
      splunk-insecureskipverify: "{{ splunk_insecureskipverify }}"
      splunk-token: "{{ splunk_token }}"
      splunk-url: "{{ splunk_url }}"
      tag: "{{ ecs_task_name }}"
  mountPoints:
  - containerPath: /rootfs
    sourceVolume: root-RO
    readOnly: true
  - containerPath: /sys
    sourceVolume: sys-ro
    readOnly: true
  - containerPath: /dk_data
    sourceVolume: dk_data
    readOnly: true
volumes:
- name: root-RO
  sourcePath: /
- name: sys-ro
  sourcePath: /sys
- name: dk_data
  sourcePath: /dk_data

```

im getting 

```
fatal: [localhost]: FAILED! => {"changed": false, "error": {"code": "ClientException", "message": "Unknown volume 'root-RO'."}, "msg": "An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Unknown volume 'root-RO'.", "response_metadata": {"http_headers": {"connection": "keep-alive", "content-length": "66", "content-type": "application/x-amz-json-1.1", "date": "Mon, 05 Feb 2018 20:26:17 GMT", "server": "Server", "x-amzn-requestid": "d1c0f429-0ab2-11e8-84a3-410c1119db6b"}, "http_status_code": 400, "request_id": "d1c0f429-0ab2-11e8-84a3-410c1119db6b", "retry_attempts": 0}}
```

can anyone tell me what im missing?
