### ISSUE TITLE
"vars" section: use of keys with '-' (minus) in their names makes some problem

### ISSUE THREAD

**Issue by gmaurice** [ansible/ansible#3575]
Hello all,

I'm using ansible on the release1.2 branch and i have a problem in "vars" section when using keys with '-' (minus) in their names. Is it normal ? Because i make it working elsewhere in playbooks and in templates. Thank you.

Here is an example of the problem :
test0 **OK** -> "stdout": "0.1"
test1 **OK** -> "stdout": "0.1"
test2 **NOK** -> "stdout": "${app1.version}"
test3 **NOK** -> TypeError: string indices must be integers

just_for_test.yml

``` yaml

---
just_for_test:
  app-test:
    version: 0.1
```

playbook.yml

``` yaml

---
- hosts: $hosts
  gather_facts: false
  vars_files:
    - just_for_test.yml

  vars:
    app_key: "app-test"
    app: ${just_for_test.$app_key}
    app1: ${just_for_test['app-test']}
    app2: "{{ just_for_test['app-test'] }}"

  tasks:
    - name: test0
      command: echo ${app.version}
    - name: test1
      command: echo {{ just_for_test['app-test'].version }}
    - name: test2
      command: echo ${app1.version}
    - name: test3
      command: echo ${app2.version}
```
