### ISSUE TITLE
URL to Nuage ClassName full list in type option documentation is broken

### ISSUE THREAD

**Issue by iverona** [ansible/ansible#35766]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

nuage_vspk

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/ignacio/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
None

##### SUMMARY
The link under type option is wrong:

file:  ansible/lib/ansible/modules/network/nuage/nuage_vspk.py

Extract:
```
type:
        description:
            - The type of entity you want to work on (example Enterprise).
            - This should match the objects CamelCase class name in VSPK-Python.
            - This Class name can be found on U(https://nuagenetworks.github.io/vspkdoc/html/index.html).
        required: true
        default: null
```
##### STEPS TO REPRODUCE
None
