### ISSUE TITLE
ECS taskdefinition module volumes

### ISSUE THREAD

**Issue by JoshuaSeidel** [ansible/ansible#35777]
having a issue with the following Anisble 2.4 and ecs_taskdefinition module

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ecs_taskdefinition

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/jseidel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT
Linux

##### SUMMARY

Volume is not getting created, erroring out that its missing information

##### STEPS TO REPRODUCE

```yaml

 - name: "Create the new task definition"
   ecs_taskdefinition:
     family: "{{ ecs_task_name }}"
     state: present
     containers: "{{ containers }}"
     task_role_arn: "{{ container_role_arn }}"
   register: ecs_task


---
containers:
- name: "acoms-{{ env }}-{{ app_name }}"
  cpu: 50
  essential: true
  image: "*****-harbor.*****.*****.io/3rdparty/{{ app_name }}:{{ container_ver }}"
  memoryReservation: 1024
  portMappings:
  - containerPort: 9100
    hostPort: 9100
  logConfiguration:
    logDriver: splunk
    options:
      splunk-insecureskipverify: "{{ splunk_insecureskipverify }}"
      splunk-token: "{{ splunk_token }}"
      splunk-url: "{{ splunk_url }}"
      tag: "{{ ecs_task_name }}"
  mountPoints:
  - containerPath: /rootfs
    sourceVolume: root-RO
    readOnly: true
  - containerPath: /var/run
    sourceVolume: var_run-rw
  - containerPath: /sys
    sourceVolume: sys-ro
    readOnly: true
  - containerPath: /var/lib/docker
    sourceVolume: var_lib_docker-ro
    readOnly: true
  volumes:
  - name: root-RO
    sourcePath: /
  - name: var_run-rw
    sourcePath: /var/run
  - name: sys-ro
    sourcePath: /sys
  - name: var_lib_docker-ro
    sourcePath: /var/lib/docker
container_count: 2
    ecs_cluster_name: ****-{{ env }}-{{ cms_zone }}
    ecs_task_name: ****-{{ env }}-{{ app_name }}
    ecs_service_name: "{{ app_name }}"
    ecs_iam_role: ecsServiceRole
    container_role_arn: ssm_ecs_task-{{ env }}
    minimum_healthy_percent: 50
    maximum_percent: 200
    validate_certs: False
```

##### EXPECTED RESULTS

based on documentation it should create the task definition

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "error": {"code": "ClientException", "message": "Unknown volume 'root-RO'."}, "msg": "An error occurred (ClientException) when calling the RegisterTaskDefinition operation: Unknown volume 'root-RO'.", "response_metadata": {"http_headers": {"connection": "keep-alive", "content-length": "66", "content-type": "application/x-amz-json-1.1", "date": "Mon, 05 Feb 2018 20:26:17 GMT", "server": "Server", "x-amzn-requestid": "d1c0f429-0ab2-11e8-84a3-410c1119db6b"}, "http_status_code": 400, "request_id": "d1c0f429-0ab2-11e8-84a3-410c1119db6b", "retry_attempts": 0}}
```

can anyone tell me what im missing?

**Comment by ansibot** [comment]
@JoshuaSeidel Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by maxamillion** [comment]
@JoshuaSeidel can you please post that again with the pasted in output surrounded by ``` quotes as per [GitHub Markdown](https://help.github.com/articles/basic-writing-and-formatting-syntax/). Right now it's difficult to sort out because of the whitespace being syntax in yaml. Also, please fill out the templated information that the bot is asking for. Thank you.

**Comment by ansibot** [comment]
cc @Java1Guy @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by JoshuaSeidel** [comment]
@maxamillion i updated it.

**Comment by willthames** [comment]
@JoshuaSeidel - the volumes shouldn't be part of the containers definition, it's just part of the task definition. Basically your current volumes are being ignored, so the mountPoints don't work.

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/create-task-definition.html

**Comment by JoshuaSeidel** [comment]
@willthames 

i fixed that, but now its giving this error

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Unknown parameter in volumes[2]: "sourcePath", must be one of: name, host
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ck/p_tmhlyx1xqgq1z2gmzrxpxh0000gp/T/ansible_7KElXt/ansible_module_ecs_taskdefinition.py\", line 396, in <module>\n    main()\n  File \"/var/folders/ck/p_tmhlyx1xqgq1z2gmzrxpxh0000gp/T/ansible_7KElXt/ansible_module_ecs_taskdefinition.py\", line 365, in main\n    volumes)\n  File \"/var/folders/ck/p_tmhlyx1xqgq1z2gmzrxpxh0000gp/T/ansible_7KElXt/ansible_module_ecs_taskdefinition.py\", line 176, in register_task\n    volumes=volumes)\n  File \"/Library/Python/2.7/site-packages/botocore/client.py\", line 317, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"/Library/Python/2.7/site-packages/botocore/client.py\", line 589, in _make_api_call\n    api_params, operation_model, context=request_context)\n  File \"/Library/Python/2.7/site-packages/botocore/client.py\", line 644, in _convert_to_request_dict\n    api_params, operation_model)\n  File \"/Library/Python/2.7/site-packages/botocore/validate.py\", line 291, in serialize_to_request\n    raise ParamValidationError(report=report.generate_report())\nbotocore.exceptions.ParamValidationError: Parameter validation failed:\nUnknown parameter in volumes[0]: \"sourcePath\", must be one of: name, host\nUnknown parameter in volumes[1]: \"sourcePath\", must be one of: name, host\nUnknown parameter in volumes[2]: \"sourcePath\", must be one of: name, host\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by JoshuaSeidel** [comment]
@willthames the documentation is wrong it should be

```yaml
name: var_lib_docker-ro
  host:
    sourcePath: /var/lib/docker
```
