### ISSUE TITLE
Not able to modify the name of existing host record with "nios_host_record" module

### ISSUE THREAD

**Issue by lkanthinfoblox** [ansible/ansible#35774]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nios_host_record

##### ANSIBLE VERSION

- ansible==2.5.0

##### OS / ENVIRONMENT

- Ubuntu

##### SUMMARY

- Not able to modify the name of existing host record when running a playbook with "nios_host_record" module.

##### STEPS TO REPRODUCE

- Run a playbook to create Host record with name as 'abc' in 'test.com' zone

```
  tasks:
    - name: Create Host record with name as 'abc' in 'test.com' zone 
      nios_host_record:
        name: abc.test.com
        ipv4:
          - address: 1.0.0.2
        comment: testing
        provider: "{{ provider }}"
        state: present

```

- Now run again playbook by modifying Host record name from 'abc' to 'xyz' in 'test.com' zone

```
  tasks:
    - name: Modify Host record name from 'abc' to 'xyz' in 'test.com' zone
      nios_host_record:
        name: xyz.test.com
        ipv4:
          - address: 1.0.0.2
        comment: testing
        provider: "{{ provider }}"
        state: present

```

##### EXPECTED RESULTS

- Expecting name of the host record will change from 'abc' to 'xyz'

##### ACTUAL RESULTS

- Name of the host record didn't change from 'abc' to 'xyz', instead it got created new host record.

- Able to update the IPv4 address or Comment, but not able to update only the Name of host record.

- Using Infoblox RESTful Web API, we can modify the name of existing host record by specifying reference returned from an earlier call.
