### ISSUE TITLE
nxos_l2_interface idempotence issue

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#35797]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_l2_interface

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel 7d721c1ec5) last updated 2018/02/06 12:04:24 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets']
PARAMIKO_HOST_KEY_AUTO_ADD(env: ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD) = True
PERSISTENT_COMMAND_TIMEOUT(env: ANSIBLE_PERSISTENT_COMMAND_TIMEOUT) = 600
PERSISTENT_CONNECT_TIMEOUT(env: ANSIBLE_PERSISTENT_CONNECT_TIMEOUT) = 600
```

##### OS / ENVIRONMENT
MAC OS
NXOS: version 7.0(3)I7(2)

##### SUMMARY
Using the `integration/targets/nxos_l2_interface/tests/common/agg.yaml` test exposes the idempotence issue.

Idempotence problem is only present for transport `nxapi`

##### STEPS TO REPRODUCE
Execute the `integration/targets/nxos_l2_interface/tests/common/agg.yaml` integration test.

```yaml
---
- debug: msg="START connection={{ ansible_connection }} nxos_l2_interface aggregate test"
- debug: msg="Using provider={{ connection.transport }}"
  when: ansible_connection == "local"

# Select interface for test
- set_fact: intname1="{{ nxos_int1 }}"
- set_fact: intname2="{{ nxos_int2 }}"

- name: "Setup vlans"
  nxos_vlan:
    vlan_range: "6,15"
    provider: "{{ connection }}"

- name: Setup - Ensure interfaces are layer2
  nxos_interface:
    aggregate:
      - { name: "{{ intname1 }}" }
      - { name: "{{ intname2 }}" }
    mode: layer2

- name: Setup - Remove interface aggregate before testing
  nxos_l2_interface:
    aggregate:
      - { name: "{{ intname1 }}", mode: access, access_vlan: 6 }
      - { name: "{{ intname2 }}", mode: access, access_vlan: 15 }
    state: absent
    provider: "{{ connection }}"

- block:
  - name: Configure interface for access_vlan aggregate
    nxos_l2_interface: &conf_agg
      aggregate:
        - { name: "{{ intname1 }}", mode: access, access_vlan: 6 }
        - { name: "{{ intname2 }}", mode: access, access_vlan: 15 }
      provider: "{{ connection }}"
    register: result

  - assert:
      that:
        - "result.changed == true"

  - name: Configure interface for access_vlan aggregate(Idempotence)
    nxos_l2_interface: *conf_agg
    register: result

  - assert:
      that:
        - "result.changed == false"

  - name: Remove interface aggregate
    nxos_l2_interface: &rm_agg
      aggregate:
        - { name: "{{ intname1 }}", mode: access, access_vlan: 6 }
        - { name: "{{ intname2 }}", mode: access, access_vlan: 15 }
      provider: "{{ connection }}"
      state: absent
    register: result

  - assert:
      that:
        - "result.changed == true"

  - name: Remove interface aggregate(Idempotence)
    nxos_l2_interface: *rm_agg
    register: result

  - assert:
      that:
        - "result.changed == false"

  always:
  - name: "remove vlans"
    nxos_vlan:
      vlan_range: "6,15"
      state: absent
      provider: "{{ connection }}"
    ignore_errors: yes

- debug: msg="END connection={{ ansible_connection }} nxos_l2_interface aggregate test"

```

##### ACTUAL RESULTS
```
TASK [nxos_l2_interface : Configure interface for access_vlan aggregate(Idempotence)] *********************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_l2_interface/tests/common/agg.yaml:43
<n9k.example.com> connection transport is nxapi
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_l2_interface.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945498.58-229036022029409 `" && echo ansible-tmp-1517945498.58-229036022029409="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945498.58-229036022029409 `" ) && sleep 0'
<n9k.example.com> PUT /Users/mwiebe/.ansible/tmp/ansible-local-92507oyYO40/tmpnKv9oo TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945498.58-229036022029409/nxos_l2_interface.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945498.58-229036022029409/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945498.58-229036022029409/nxos_l2_interface.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945498.58-229036022029409/nxos_l2_interface.py && sleep 0'
changed: [n9k.example.com] => {
    "changed": true, 
    "commands": [
        "interface ethernet1/1", 
        "switchport access vlan 6", 
        "interface ethernet1/2", 
        "switchport access vlan 15"
    ], 
    "failed": false, 
    "invocation": {
        "module_args": {
            "access_vlan": null, 
            "aggregate": [
                {
                    "access_vlan": "6", 
                    "mode": "access", 
                    "name": "Ethernet1/1", 
                    "native_vlan": null, 
                    "state": "present", 
                    "trunk_allowed_vlans": null, 
                    "trunk_vlans": null
                }, 
                {
                    "access_vlan": "15", 
                    "mode": "access", 
                    "name": "Ethernet1/2", 
                    "native_vlan": null, 
                    "state": "present", 
                    "trunk_allowed_vlans": null, 
                    "trunk_vlans": null
                }
            ], 
            "host": "n9k.example.com", 
            "mode": null, 
            "name": null, 
            "native_vlan": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 80, 
            "provider": {
                "host": "n9k.example.com", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 80, 
                "ssh_keyfile": null, 
                "timeout": 600, 
                "transport": "nxapi", 
                "use_proxy": true, 
                "use_ssl": false, 
                "username": "admin", 
                "validate_certs": true
            }, 
            "ssh_keyfile": null, 
            "state": "present", 
            "timeout": 600, 
            "transport": "nxapi", 
            "trunk_allowed_vlans": null, 
            "trunk_vlans": null, 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "admin", 
            "use_proxy": true, 
            "use_ssl": false, 
            "username": "admin", 
            "validate_certs": true
        }
    }
}

TASK [nxos_l2_interface : assert] *************************************************************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_l2_interface/tests/common/agg.yaml:47
fatal: [n9k.example.com]: FAILED! => {
    "assertion": "result.changed == false", 
    "changed": false, 
    "evaluated_to": false, 
    "failed": true
}

```
