### ISSUE TITLE
nxos_l2_interface errors out for transport cli

### ISSUE THREAD

**Issue by mikewiebe** [ansible/ansible#35799]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_l2_interface

##### ANSIBLE VERSION
```
ansible 2.5.0 (devel 7d721c1ec5) last updated 2018/02/06 12:04:24 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/mwiebe/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible
  executable location = /Users/mwiebe/Projects/nxos_ansible/fix_ansible/bin/ansible
  python version = 2.7.13 (default, Apr  4 2017, 08:47:57) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)]
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets']
PARAMIKO_HOST_KEY_AUTO_ADD(env: ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD) = True
PERSISTENT_COMMAND_TIMEOUT(env: ANSIBLE_PERSISTENT_COMMAND_TIMEOUT) = 600
PERSISTENT_CONNECT_TIMEOUT(env: ANSIBLE_PERSISTENT_CONNECT_TIMEOUT) = 600
```

##### OS / ENVIRONMENT
MAC OS
NXOS: version 7.0(3)I7(2)

##### SUMMARY
Using the `integration/targets/nxos_l2_interface/tests/common/agg.yaml` test exposes the crash issue.

Problem is only present for transport `cli`

##### STEPS TO REPRODUCE
Execute the `integration/targets/nxos_l2_interface/tests/common/agg.yaml` integration test.

```yaml
---
- debug: msg="START connection={{ ansible_connection }} nxos_l2_interface aggregate test"
- debug: msg="Using provider={{ connection.transport }}"
  when: ansible_connection == "local"

# Select interface for test
- set_fact: intname1="{{ nxos_int1 }}"
- set_fact: intname2="{{ nxos_int2 }}"

- name: "Setup vlans"
  nxos_vlan:
    vlan_range: "6,15"
    provider: "{{ connection }}"

- name: Setup - Ensure interfaces are layer2
  nxos_interface:
    aggregate:
      - { name: "{{ intname1 }}" }
      - { name: "{{ intname2 }}" }
    mode: layer2

- name: Setup - Remove interface aggregate before testing
  nxos_l2_interface:
    aggregate:
      - { name: "{{ intname1 }}", mode: access, access_vlan: 6 }
      - { name: "{{ intname2 }}", mode: access, access_vlan: 15 }
    state: absent
    provider: "{{ connection }}"

- block:
  - name: Configure interface for access_vlan aggregate
    nxos_l2_interface: &conf_agg
      aggregate:
        - { name: "{{ intname1 }}", mode: access, access_vlan: 6 }
        - { name: "{{ intname2 }}", mode: access, access_vlan: 15 }
      provider: "{{ connection }}"
    register: result

  - assert:
      that:
        - "result.changed == true"

  - name: Configure interface for access_vlan aggregate(Idempotence)
    nxos_l2_interface: *conf_agg
    register: result

  - assert:
      that:
        - "result.changed == false"

  - name: Remove interface aggregate
    nxos_l2_interface: &rm_agg
      aggregate:
        - { name: "{{ intname1 }}", mode: access, access_vlan: 6 }
        - { name: "{{ intname2 }}", mode: access, access_vlan: 15 }
      provider: "{{ connection }}"
      state: absent
    register: result

  - assert:
      that:
        - "result.changed == true"

  - name: Remove interface aggregate(Idempotence)
    nxos_l2_interface: *rm_agg
    register: result

  - assert:
      that:
        - "result.changed == false"

  always:
  - name: "remove vlans"
    nxos_vlan:
      vlan_range: "6,15"
      state: absent
      provider: "{{ connection }}"
    ignore_errors: yes

- debug: msg="END connection={{ ansible_connection }} nxos_l2_interface aggregate test"

```

##### ACTUAL RESULTS
```
TASK [nxos_l2_interface : Setup - Remove interface aggregate before testing] ******************************************************************************************************************************************************************
task path: /Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/targets/nxos_l2_interface/tests/common/agg.yaml:22
<n9k.example.com> attempting to start connection
<n9k.example.com> using connection plugin network_cli
<n9k.example.com> found existing local domain socket, using it!
<n9k.example.com> updating play_context for connection
<n9k.example.com> 
<n9k.example.com> local domain socket path is /Users/mwiebe/.ansible/pc/534c1e1de6
Using module file /Users/mwiebe/Projects/nxos_ansible/fix_ansible/lib/ansible/modules/network/nxos/nxos_l2_interface.py
<n9k.example.com> ESTABLISH LOCAL CONNECTION FOR USER: mwiebe
<n9k.example.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945704.84-257547534537935 `" && echo ansible-tmp-1517945704.84-257547534537935="` echo /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945704.84-257547534537935 `" ) && sleep 0'
<n9k.example.com> PUT /Users/mwiebe/.ansible/tmp/ansible-local-93936U7OiVr/tmppzA0bQ TO /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945704.84-257547534537935/nxos_l2_interface.py
<n9k.example.com> EXEC /bin/sh -c 'chmod u+x /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945704.84-257547534537935/ /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945704.84-257547534537935/nxos_l2_interface.py && sleep 0'
<n9k.example.com> EXEC /bin/sh -c '/Users/mwiebe/Virtualenvs/py2-ansible/bin/python /Users/mwiebe/.ansible/tmp/ansible-tmp-1517945704.84-257547534537935/nxos_l2_interface.py && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_l18c_8/ansible_module_nxos_l2_interface.py", line 596, in <module>
    main()
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_l18c_8/ansible_module_nxos_l2_interface.py", line 519, in main
    current_mode = get_interface_mode(name, module)
  File "/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_l18c_8/ansible_module_nxos_l2_interface.py", line 163, in get_interface_mode
    interface_table = body['TABLE_interface']['ROW_interface']
TypeError: string indices must be integers

fatal: [n9k.example.com]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_l18c_8/ansible_module_nxos_l2_interface.py\", line 596, in <module>\n    main()\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_l18c_8/ansible_module_nxos_l2_interface.py\", line 519, in main\n    current_mode = get_interface_mode(name, module)\n  File \"/var/folders/ww/538d42ys18l5tjyz0l1yk1rc0000gn/T/ansible_l18c_8/ansible_module_nxos_l2_interface.py\", line 163, in get_interface_mode\n    interface_table = body['TABLE_interface']['ROW_interface']\nTypeError: string indices must be integers\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
	to retry, use: --limit @/Users/mwiebe/Projects/nxos_ansible/fix_ansible/test/integration/nxos.retry


```
