### ISSUE TITLE
ec2_group module fails in creating access to 0.0.0.0/0 port 443 and port 80

### ISSUE THREAD

**Issue by kclausen-tm** [ansible/ansible#35811]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_group

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kclausen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov  2 2017, 19:20:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

$ ansible-config dump --only-changed
$

##### OS / ENVIRONMENT

n/a
##### SUMMARY

I have a group_vars file that defines my VPC and when I try to create a new VPC it fails to create my edge security group with the correct permissions.

It's supposed to create a group that gives public access to port 443 and port 80, but instead creates a security group with access to ALL ports!

##### STEPS TO REPRODUCE

From group_vars/all

```
# VPC Security Groups list
vpc_security_group_all:
  - "{{ vpc_security_group['public_edge_sg'] }}"
# and a bunch more security groups

# VPC Security Groups definitions
vpc_security_group:
  public_edge_sg:
    - name: '{{ vpc_name }} - Public Edge SG'
      description: 'Security Group for {{ vpc_name }} Public Edge Loadbalancers'
      rules:
        - "{{ vpc_sg_access_rule['all_tcp_443'] }}"
        - "{{ vpc_sg_access_rule['all_tcp_80'] }}"

# VPC Security Group access rules
vpc_sg_access_rule:
# Full access
  all:
    cidr_ip: 0.0.0.0/0
    from_port: all
    proto: all
    to_port: all

# Public access port 443
  all_tcp_443:
    cidr_ip: 0.0.0.0/0
    from_port: 443
    proto: all
    to_port: 443

# Public access port 80
  all_tcp_80:
    cidr_ip: 0.0.0.0/0
    from_port: 80
    proto: all
    to_port: 80

```

From the playbook:
```
- name: Create Security Groups
  ec2_group:
    description: '{{ item.description }}'
    name: '{{ item.name }}'
    region: '{{ vpc_region }}'
    rules: '{{ item.rules }}'
    vpc_id: '{{ vpc_id }}'
  with_items: '{{ vpc_security_group_all }}'
```

##### EXPECTED RESULTS

A security group gets created with public access to port 80 and port 443 over TCP

##### ACTUAL RESULTS

A security group gets created with public access to ALL ports, ALL protocols

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (InvalidPermission.Duplicate) when calling the AuthorizeSecurityGroupIngress operation: the specified rule "peer: 0.0.0.0/0, ALL, ALLOW" already exists
failed: [localhost] (item={u'rules': [{u'to_port': 443, u'from_port': 443, u'cidr_ip': u'0.0.0.0/0', u'proto': u'all'}, {u'to_port': 80, u'from_port': 80, u'cidr_ip': u'0.0.0.0/0', u'proto': u'all'}], u'name': u'XXXXXXX  - Public Edge SG', u'description': u'Security Group for XXXXXXX  Public Edge Loadbalancers'}) => {"changed": false, "error": {"code": "InvalidPermission.Duplicate", "message": "the specified rule \"peer: 0.0.0.0/0, ALL, ALLOW\" already exists"}, "item": {"description": "Security Group for XXXXXXX  Public Edge Loadbalancers", "name": "XXXXXXX  - Public Edge SG", "rules": [{"cidr_ip": "0.0.0.0/0", "from_port": 443, "proto": "all", "to_port": 443}, {"cidr_ip": "0.0.0.0/0", "from_port": 80, "proto": "all", "to_port": 80}]}, "msg": "Unable to authorize in for ip 0.0.0.0/0 security group 'XXXXXXX - Public Edge SG' - An error occurred (InvalidPermission.Duplicate) when calling the AuthorizeSecurityGroupIngress operation: the specified rule \"peer: 0.0.0.0/0, ALL, ALLOW\" already exists", "response_metadata": {"http_headers": {"connection": "close", "date": "Tue, 06 Feb 2018 21:15:45 GMT", "server": "AmazonEC2", "transfer-encoding": "chunked"}, "http_status_code": 400, "request_id": "4cb58287-f6ee-43ee-bf8c-c17c3eb27294", "retry_attempts": 0}}
```
