### ISSUE TITLE
do-until on vmware_guest_snapshot does not read resgistered var

### ISSUE THREAD

**Issue by kennethkmp** [ansible/ansible#35827]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

until
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/modregk_bga/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```
(Also tested on 2.4.3 and 2.5)
##### CONFIGURATION

DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 200
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/opt/ansible_infra/inventory']
DEFAULT_MANAGED_STR(/etc/ansible/ansible.cfg) = Ansible managed. DO NOT EDIT
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = /tmp/.ansible_$USER/tmp
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
DISPLAY_SKIPPED_HOSTS(env: DISPLAY_SKIPPED_HOSTS) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
INVENTORY_IGNORE_EXTS(/etc/ansible/ansible.cfg) = ['~', '.orig', '.bak', '.ini', '.cfg', '.retry', '.pyc', '.pyo', '.yml']
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
##### OS / ENVIRONMENT

Linux .10.0-693.11.6.el7.x86_64
##### SUMMARY
until command isn't able to evaluate the registered variable on first run

##### STEPS TO REPRODUCE

The playbook is supposed to delete a snapshot, and continue doing so until no snapshots are available (changed == False).

```yaml
- hosts: all 
  gather_facts: True
  serial: 5 
  strategy: debug
  vars_files:
    - vm_vars.yml

  vars_prompt:
   - name: "vcenter_user"
     prompt: "Enter Vcenter User" 
     private: no
     when: vcenter_user is not defined 
   - name: "vcenter_pass"
     prompt: "Enter Vcenter password" 
     private: yes
     when: vcenter_pass is not defined
  tasks:

    - include_tasks: vm_common.yml 
      when: ansible_virtualization_type|default("") == "VMware"

    - block: 
      - name: Delete  all AdHoc snapshots
        vmware_guest_snapshot:
          hostname:  "{{ vcenter_hostname }}"
          username: "{{ domain }}{{ vcenter_user }}"
          password:  "{{ vcenter_pass }}"
          datacenter: "{{vm_datacenter}}"
          folder: "{{vm_folder}}"
          name:  "{{ inventory_hostname }}"
          validate_certs: False
          state: absent
          snapshot_name: "Ansible_Adhoc"
        delegate_to: localhost
        register: vmresult
        retries: 2
        delay: 1 
        until: vmresult.changed != True 

      - debug: var=vmresult

      when: 
        - ansible_virtualization_type|default("") == "VMware"
        - LOC in ( "rom", "enf", "lux" )
```

##### EXPECTED RESULTS
task should end on first try (or last if it does find any snapshots to delete) as vmresult.changed == False

##### ACTUAL RESULTS

```
PLAY [all] **************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [loncinftstl001]

TASK [include_tasks] ****************************************************************************************************************************************
included: /home/modregk_bga/ansible/playbooks/esx/vm_common.yml for loncinftstl001

TASK [Set VCENTER Server based on tier] *********************************************************************************************************************
ok: [loncinftstl001]

TASK [Set VCENTER Server based on env when dmz] *************************************************************************************************************

TASK [Set  Datacenter env when dmz] *************************************************************************************************************************

TASK [Set vcenter user domain when deploying in Lux] ********************************************************************************************************

TASK [Set vcenter user domain when not  deploying in Lux] ***************************************************************************************************
ok: [loncinftstl001]

TASK [Check for vsphere access parameters] ******************************************************************************************************************

TASK [Se folder for DMZ servers] ****************************************************************************************************************************

TASK [Collect all VM defailts] ******************************************************************************************************************************
ok: [loncinftstl001]

TASK [VM details] *******************************************************************************************************************************************
ok: [loncinftstl001] => {
    "details": "{'Datacenter': u'ENF', 'Hostname': u'loncinftstl001', 'Disks': [{u'disk1': None, u'size_gb': 50, u'type': u'thin', u'datastore': u'ENF_LONDESXC04_DS_CLUSTER_001'}], 'DC': u'lon', 'CPUs': 2, 'Cluster': Undefined, 'vcenter_user': u'modregkx2', 'Env': u'c_b', 'Memory': 8, 'Tier': u'c_b', 'Vcenter Host': u'lonpinfvcsa007.london.schroders.com', 'Folder': u'/LON/ENF/vm/UNIX/'}"
}

TASK [Delete  all AdHoc snapshots] **************************************************************************************************************************
fatal: [loncinftstl001]: FAILED! => {"msg": "The conditional check 'vmresult.changed != True' failed. The error was: error while evaluating conditional (vmresult.changed != True): 'dict object' has no attribute 'changed'"}
Debugger invoked
(debug) p result
{'failed': True,
 'msg': u"The conditional check 'vmresult.changed != True' failed. The error was: error while evaluating conditional (vmresult.changed != True): 'dict object' has no attribute 'changed'"}
(debug) p vars['vmresult']
***KeyError:KeyError('vmresult',)
(debug) 
```

The above run had no snapshots to delete, creating a snapshot with that name produces the following output

```

PLAY [all] **************************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [loncinftstl001]

TASK [include_tasks] ****************************************************************************************************************************************
included: /home/modregk_bga/ansible/playbooks/esx/vm_common.yml for loncinftstl001

TASK [Set VCENTER Server based on tier] *********************************************************************************************************************
ok: [loncinftstl001]

TASK [Set VCENTER Server based on env when dmz] *************************************************************************************************************

TASK [Set  Datacenter env when dmz] *************************************************************************************************************************

TASK [Set vcenter user domain when deploying in Lux] ********************************************************************************************************

TASK [Set vcenter user domain when not  deploying in Lux] ***************************************************************************************************
ok: [loncinftstl001]

TASK [Check for vsphere access parameters] ******************************************************************************************************************

TASK [Se folder for DMZ servers] ****************************************************************************************************************************

TASK [Collect all VM defailts] ******************************************************************************************************************************
ok: [loncinftstl001]

TASK [VM details] *******************************************************************************************************************************************
ok: [loncinftstl001] => {
    "details": "{'Datacenter': u'ENF', 'Hostname': u'loncinftstl001', 'Disks': [{u'disk1': None, u'size_gb': 50, u'type': u'thin', u'datastore': u'ENF_LONDESXC04_DS_CLUSTER_001'}], 'DC': u'lon', 'CPUs': 2, 'Cluster': Undefined, 'vcenter_user': u'modregkx2', 'Env': u'c_b', 'Memory': 8, 'Tier': u'c_b', 'Vcenter Host': u'lonpinfvcsa007.london.schroders.com', 'Folder': u'/LON/ENF/vm/UNIX/'}"
}

TASK [Delete  all AdHoc snapshots] **************************************************************************************************************************
FAILED - RETRYING: Delete  all AdHoc snapshots (2 retries left).
fatal: [loncinftstl001]: FAILED! => {"msg": "The conditional check 'vmresult.changed != True' failed. The error was: error while evaluating conditional (vmresult.changed != True): 'dict object' has no attribute 'changed'"}
Debugger invoked
(debug)
```

Here is an example of the vmresult variable if the "until" code is removed and no snapshots are available

```yaml
      - name: Delete  all AdHoc snapshots
        vmware_guest_snapshot:
          hostname:  "{{ vcenter_hostname }}"
          username: "{{ domain }}{{ vcenter_user }}"
          password:  "{{ vcenter_pass }}"
          datacenter: "{{vm_datacenter}}"
          folder: "{{vm_folder}}"
          name:  "{{ inventory_hostname }}"
          validate_certs: False
          state: absent
          snapshot_name: "Ansible_Adhoc"
        delegate_to: localhost
        register: vmresult

      - debug: var=vmresult
```

Results: 

```
ok: [loncinftstl001] => {
    "vmresult": {
        "changed": false, 
        "failed": false, 
        "msg": "VM - loncinftstl001 doesn't have any snapshots"
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [test/integration/targets/until/aliases](https://github.com/ansible/ansible/blob/devel/test/integration/targets/until/aliases)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@akamez Thanks for reporting. Could you please re-try with following 

```yaml
- block: 
      - name: Delete  all AdHoc snapshots
        vmware_guest_snapshot:
          hostname:  "{{ vcenter_hostname }}"
          username: "{{ domain }}{{ vcenter_user }}"
          password:  "{{ vcenter_pass }}"
          datacenter: "{{vm_datacenter}}"
          folder: "{{vm_folder}}"
          name:  "{{ inventory_hostname }}"
          validate_certs: False
          state: absent
          snapshot_name: "Ansible_Adhoc"
        delegate_to: localhost
        register: vmresult
        retries: 2
        delay: 1 
        until: not vmresult.changed # <--- Change this condition

      - debug: var=vmresult

      when: 
        - ansible_virtualization_type|default("") == "VMware"
        - LOC in ( "rom", "enf", "lux" )

```

needs_info
