### ISSUE TITLE
Run all precheck task before real tasks in role

### ISSUE THREAD

**Issue by liubog2008** [ansible/ansible#35825]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

role

##### ANSIBLE VERSION

```
2.x
```
##### SUMMARY

I hope to run all precheck tasks before real tasks in role while import many roles.

##### STEPS TO REPRODUCE

```yaml
# playbook
- hosts: all
  roles:
  - first
  - second

# roles/first/tasks/main.yaml
- name: "precheck for first role"

- name: "first role"
  command: echo "first role"

# roles/second/tasks/main.yaml
- name: "precheck for second role"

- name: "second role"
  command: echo "second role"
```

##### EXPECTED RESULTS

```
order:
- precheck for first role
- precheck for second role
- first role
- second role 
```
##### ACTUAL RESULTS

```
order:
- precheck for first role
- first role
- precheck for second role
- second role 
```

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/role](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
There are several ways you could do this. One way would be to put all your pre-check tasks into a `pre-check.yml` file in each role. Then use `tasks` rather than `roles` to run just those tasks for each role before running each role entirely.

```yaml
- hosts: all
  tasks:
    - name: Run pre-check for all roles
      import_role: "{{ item }}"
      tasks_from: pre-check.yml
      loop:
        - role1
        - role1

    - name: Run roles
      import_role: "{{ item }}"
      loop:
        - role1
        - role1
```


For further help, please stop by `#ansible` on irc.freenode.net
