### ISSUE TITLE
Source bucket cannot be found - S3

### ISSUE THREAD

**Issue by windowsansiblernew** [ansible/ansible#35826]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`s3.py`

##### ANSIBLE VERSION

```
ansible 2.3.0.0

```

##### SUMMARY

Trying to download files from S3 , but it is not working
##### STEPS TO REPRODUCE

```yaml
  - name: get s3_bucket_items
    s3:
     profile=update 
     mode=list
     bucket=reg.releases
     prefix=buckspace/
    register: s3_bucket_items
    tags: gets3
    delegate_to: localhost
  - name: download s3_bucket_items
    s3:
     mode=get
     bucket=reg.releases
     object={{ item }}
     dest=/home/ec2-user/testservers/froms3/
     with_items=s3_bucket_items.s3_keys
    tags: downloads3
    delegate_to: localhost
```

##### EXPECTED RESULTS
Files should be downloaded 

##### ACTUAL RESULTS

```
localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Source bucket cannot be found."}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/_s3.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/_s3.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @s-hertel @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by windowsansiblernew** [comment]
fixed it myself by using it like below

```
     s3: 
       profile: update 
       region: ap-southeast-1
       bucket: reg.releases
       object: "/pacess/{{ item }}"     
       dest: /location/{{ item }}
       mode: get     
     with_items: 
         - "{{ ud }}"
```
