### ISSUE TITLE
Parse XML with nested objects

### ISSUE THREAD

**Issue by narankhetani** [ansible/ansible#35849]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
parse_xml

##### ANSIBLE VERSION
```
#> ansible --version
ansible 2.5.0
  config file = /Users/drive/scripts/projects/cns-ansible/ansible.cfg
  configured module search path = [u'/Users/env/ansible-dev/lib/python2.7/site-packages/ara/plugins/modules']
  ansible python module location = /Users/env/ansible-dev/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /Users/env/ansible-dev/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
Mac OSX

##### SUMMARY
How does one parse nested xml nodes to an object?

## Playbook:
```yaml
    - debug: var=item
      with_items: "{{ interface_data_json.interfaces }}"
      when:
        - item.phy_ifname is match("vlan")
      vars:
        data: "{{ lookup('file', 'interfaces.tor.xml') }}"
        interface_data_json: "{{ data | parse_xml('get_interface_information.spec.yml') }}"
```
## Parser Spec file
```yaml
---
vars:
  interface:
    phy_ifname: "{{ item.get('phy_ifname', '') }}"
    phy_description: "{{ item.get('phy_description', '') }}"
    status_oper: "{{ item.get('status_oper', '') }}"
    status_admin: "{{ item.get('status_admin', '') }}"

keys:
  interfaces:
    value: "{{ interface }}"
    top: interface-information/physical-interface
    items:
      phy_ifname: name
      phy_description: description
      status_oper: oper-status
      status_admin: admin-status
      keys:
        logical_interfaces:
          value: "{{ logical_interface }}"
          top: logical-interface
          items:
            ifname: name
            description: description
```
## XML File
```xml
<rpc-reply xmlns:junos="http://xml.juniper.net/junos/12.3R12/junos">
    <interface-information xmlns="http://xml.juniper.net/junos/12.3R12/junos-interface" junos:style="normal">
        <physical-interface>
            <name>xe-0/0/0</name>
            <admin-status junos:format="Enabled">up</admin-status>
            <oper-status>up</oper-status>
            <local-index>193</local-index>
            <snmp-index>503</snmp-index>
            <description>[type=UL]</description>
            <link-level-type>Ethernet</link-level-type>
            <mtu>1514</mtu>
            <source-filtering>disabled</source-filtering>
            <speed>10Gbps</speed>
            <duplex>Full-Duplex</duplex>
            <bpdu-error>none</bpdu-error>
            <l2pt-error>none</l2pt-error>
            <loopback>disabled</loopback>
            <if-flow-control>enabled</if-flow-control>
            <if-media-type>Fiber</if-media-type>
            <if-device-flags>
                <ifdf-present/>
                <ifdf-running/>
            </if-device-flags>
            <if-config-flags>
                <iff-snmp-traps/>
                <internal-flags>0x0</internal-flags>
            </if-config-flags>
            <if-media-flags>
                <ifmf-none/>
            </if-media-flags>
            <physical-interface-cos-information>
                <physical-interface-cos-hw-max-queues>8</physical-interface-cos-hw-max-queues>
                <physical-interface-cos-use-max-queues>8</physical-interface-cos-use-max-queues>
            </physical-interface-cos-information>
            <current-physical-address>cc:e1:7f:21:d2:03</current-physical-address>
            <hardware-physical-address>cc:e1:7f:21:d2:03</hardware-physical-address>
            <interface-flapped junos:seconds="1212">2018-01-29 16:52:37 UTC (00:20:12 ago)</interface-flapped>
            <traffic-statistics junos:style="brief">
                <input-bps>11397920</input-bps>
                <input-pps>3810</input-pps>
                <output-bps>3073896</output-bps>
                <output-pps>1876</output-pps>
            </traffic-statistics>
            <active-alarms>
                <interface-alarms>
                    <alarm-not-present/>
                </interface-alarms>
            </active-alarms>
            <active-defects>
                <interface-alarms>
                    <alarm-not-present/>
                </interface-alarms>
            </active-defects>
            <interface-transmit-statistics>Disabled</interface-transmit-statistics>
            <logical-interface>
                <name>xe-0/0/0.0</name>
                <local-index>69</local-index>
                <snmp-index>504</snmp-index>
                <description>[type=UL]</description>
                <if-config-flags>
                    <iff-up/>
                    <iff-snmp-traps/>
                    <internal-flags>0x0</internal-flags>
                </if-config-flags>
                <encapsulation>ENET2</encapsulation>
                <traffic-statistics junos:style="brief">
                    <input-packets>18409460</input-packets>
                    <output-packets>45084301</output-packets>
                </traffic-statistics>
                <filter-information>
                </filter-information>
                <address-family>
                    <address-family-name>inet</address-family-name>
                    <mtu>1500</mtu>
                    <address-family-flags>
                        <ifff-none/>
                    </address-family-flags>
                    <interface-address>
                        <ifa-flags>
                            <ifaf-current-preferred/>
                            <ifaf-current-primary/>
                        </ifa-flags>
                        <ifa-destination>10.22.1.2/31</ifa-destination>
                        <ifa-local>10.22.1.3</ifa-local>
                    </interface-address>
                </address-family>
            </logical-interface>
        </physical-interface>
    </interface-information>
    <cli>
        <banner>{master:0}</banner>
    </cli>
</rpc-reply>
```

##### EXPECTED RESULTS
Trying to get the inner object logical-interface as a list of objects as there would be cases where there would be more than 1 node in the logical-interface.
