### ISSUE TITLE
Deprecation warning received with Jira Module when passing args:

### ISSUE THREAD

**Issue by msilmser** [ansible/ansible#35857]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Jira Module

##### ANSIBLE VERSION
2.2.1

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Client is receiving the following deprecation warning when using passing `args:` to the Jira module:
```
[DEPRECATION WARNING]: Using variables for task params is unsafe, especially if the variables come from an external source like facts.
```
##### STEPS TO REPRODUCE

1. Create a playbook calling the JIRA module similar to:
```
- name: Create Jira Task
  jira:
    uri: "{{ uri_variable }}"
    username: "{{ un_variable }}"
    password: "{{ pw_variable }}"
    project: "{{ project_variable }}"
    operation: create
    summary: "{{ summary_variable }}"
    description: "{{ descript_variable }}"
    issuetype: Task
  args: "{{ arg_variable }}"
  register: jira_create_output
  delegate_to: localhost
  run_once: true
```
2. Run the playbook

##### EXPECTED RESULTS
Playbook runs successfully with no warnings/errors

##### ACTUAL RESULTS
Playbook runs successfully, the the deprecation warning above populates. When the `args` module is commented out, the warning does not appear. 

```
[DEPRECATION WARNING]: Using variables for task params is unsafe, especially if the variables come from an external source like facts
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/jira.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/jira.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Slezhuk @tarka
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
!component =lib/ansible/executor/task_executor.py

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/executor/task_executor.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/executor/task_executor.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jctanner** [comment]
The error is coming from https://github.com/ansible/ansible/blob/stable-2.4/lib/ansible/executor/task_executor.py#L489-L497

```
        # Now we do final validation on the task, which sets all fields to their final values.
        self._task.post_validate(templar=templar)
        if '_variable_params' in self._task.args:
            variable_params = self._task.args.pop('_variable_params')
            if isinstance(variable_params, dict):
                display.deprecated("Using variables for task params is unsafe, especially if the variables come from an external source like facts",
version="2.6")
```

The way to trigger it is to using something like this for the arg_variable value from the example:

```
  vars:
      arg_variable:
          key1: val1
          key2: val2
```

The block of code originally comes from https://github.com/ansible/ansible/commit/e526743b4f91a571f48bff4280ce5e441f72a292

We have discussed this on the mailing list and in irc a few times, but the most recent thread on ansible-project has a comment from @jimi-c explaining the problem.

https://groups.google.com/forum/#!searchin/ansible-project/Why$20is$20using$20args$20from$20variables$20considered$20unsave%7Csort:date/ansible-project/Qrq76VLIqKg/ZnRpTwQ_AQAJ

> We consider this unsafe due to the fact that, if the variable is based on a fact of some kind, your tasks could start doing unexpected or malicious things (in the event that the remote system is compromised in some way).

We will not remove the warning and still plan to remove the feature in 2.6.
