### ISSUE TITLE
Meta doesn't pickup With_item in "When" conditional

### ISSUE THREAD

**Issue by arkaraung1993** [ansible/ansible#35890]
Hey guys, I want to terminate All remaining task in playbook with success. I found meta can use. But Meta doesn't pickup "item" in when conditional. Please follow playbook and kindly assist.
```
---
- hosts: ciscoasa:pafw
  connection: local
  gather_facts: False
  
  vars:
    adm:
        authorize: yes
        auth_pass: "{{ ansible_ssh_pass }}"
    DP_IP_ADDR: [10.0.0.10]

  tasks:

    - name: Verify IPv4 Format Valid or Not and check IP Address for 10.x.x.x Internal Range
      run_once: True
      fail:
        msg: "IP Address specified is not valid. Please double-check against the Service Request."
      with_items: "{{ DP_IP_ADDR }}"
      when: not( item | ipaddr('10.0.0.0/8') )

    - meta: end_play
      with_items: "{{ DP_IP_ADDR }}"
      when: not( 'item' | ipaddr('10.0.0.0/24') )        
      run_once: True
```

##### ISSUE TYPE

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME

meta tasks

##### ANSIBLE VERSION

```
2.5
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
