### ISSUE TITLE
In the apt module the upgrade parameter cannot be used together with the autoremove in the same task

### ISSUE THREAD

**Issue by Harosgr** [ansible/ansible#35900]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

apt module

##### ANSIBLE VERSION

```
2.4.2
```

##### OS / ENVIRONMENT

RHEL 7.4

##### SUMMARY

APT autoremove parameter cannot be used with upgrade in the same task. If upgrade and autoremove are used in two separate tasks they both work fine. Maybe this is not a bug but a lack of documentation (?) that these two parameters cannot be used together.

##### STEPS TO REPRODUCE

Run a playbook with the apt module which include the upgrade parameter and also the autoremove parameter in the same task. Autoremove gets ignored and only the upgrade procedure runs.

```yaml

---
- name: apt upgrade and autoremove
  apt: 
    force_apt_get: yes
    update_cache: yes
    upgrade: dist
    autoremove: yes
--

```

##### EXPECTED RESULTS

The upgrade should work and the autoremove too

##### ACTUAL RESULTS

Only upgrade works. autoremove gets ignored.

```

```
