### ISSUE TITLE
ansible_python_interpreter ignored in Ansible 2.4 for eos* that use network_cli module

### ISSUE THREAD

**Issue by dathelen** [ansible/ansible#35902]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_command

##### ANSIBLE VERSION
```
[user@xcrlxsie02p ansible]$ ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Nov 21 2013, 10:50:32) [GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
```

##### OS / ENVIRONMENT
This host running Ansible has both python2.6 and 2.7

##### SUMMARY
The eos modules that use the network_cli plugin seem to ignore the ansible_python_interpreter variable

##### STEPS TO REPRODUCE
Launch the  playbook below  on a host where python2.7 isnt the default and set the ansible_python_interpreter variable

```yaml

user@xcrlxsie02p ansible]$ cat playbooks/test.yml
---
- name: Search for unused SFPs
  hosts: "{{ device }}"
  connection: local

  tasks:
    - name: Run "show interface" command on the switch
      eos_command:
        commands: "show interfaces status"
        provider: '{{ eos_connection_cli }}'

  vars:
    eos_connection_cli:
      host: "{{ inventory_hostname }}"
      username: <user>
      password: <pass>
      transport: cli

[user@xcrlxsie02p ansible]$ cat hosts
[hosts]
10.125.167.130

[all:vars]
ansible_python_interpreter=/opt/rh/python27/root/usr/bin/python2.7

```

##### EXPECTED RESULTS

It would use the python environment pointed to by ansible_python_interpreter=/opt/rh/python27/root/usr/bin/python2.7

##### ACTUAL RESULTS

user@xcrlxsie02p ansible]$ ansible-playbook -i hosts playbooks/test.yml -e device=10.125.167.130

PLAY [Search for unused SFPs] ***********************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************
ok: [10.125.167.130]

TASK [Run "show interface" command on the switch] ***************************************************************************************
fatal: [10.125.167.130]: FAILED! => {"changed": false, "msg": "unable to open shell. Please see: https://docs.ansible.com/ansible/network_debug_troubleshooting.html#unable-to-open-shell"}
        to retry, use: --limit @/home/user/automation/ansible/playbooks/test.retry

PLAY RECAP ******************************************************************************************************************************
10.125.167.130             : ok=1    changed=0    unreachable=0    failed=1

It fails because there is no paramiko installed on python2.6

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/eos/eos_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/eos/eos_command.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @privateip @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
Does this work on `devel` or the `stable-2.5` branches?

**Comment by gundalow** [comment]
Also if you change to `connection: network_cli` is it any different?

**Comment by Qalthos** [comment]
The issue here seems to be that `ansible-connection` is getting called using `#!/usr/bin/env python` rather than respecting `ansible_python_interpreter`. Fixing this is more complicated than regular modules as we don't have the opportunity to rewrite the shebang in this case.

**Comment by gundalow** [comment]
Maybe we need to document this as a limitation?
Can we detect and set a meaningful error message?

**Comment by bcoca** [comment]
We set it to 'system.python'  for localhost to match the python that Ansible is using, you might need to do something similar.

Maybe execute Ptyhon and give it ansible-connection as a script vs relying on the shebang.

**Comment by elmiliu** [comment]
network_cli does not help, still getting the same error. From the comments above I understand that the issue is acknowledged and will either get fixed or marked as a limitation.

**Comment by Qalthos** [comment]
> Maybe execute Ptyhon and give it ansible-connection as a script vs relying on the shebang.

That was my first thought, but AFAIU, `Popen()` with `shell=False` only searches $PATH for the first parameter, so we'd have to locate and provide the full path to `ansible-connection`. There doesn't seem to be a built-in way to search $PATH, but I might be missing something

**Comment by bcoca** [comment]
you do know the path to the 'current cli executable' which we can assume is the same path to ansible-connection, we do this elsewhere with pull/playbook iirc,

**Comment by Qalthos** [comment]
That sounds real promising, but I'm not having any success in finding such a thing. Could you point me in the right direction?

**Comment by ozlevka-work** [comment]
Occur  for me with apt:
``` yaml
 - name: Install docker dependencies
      apt:
        name: "{{ ','.join(docker_deps) }}"
        update_cache: true
        state: latest
      async: 3600
      poll: 0
```
```
fatal: [first]: FAILED! => {"changed": true, "module_stderr": "Shared connection to 10.0.0.56 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 127}
```
I have in inventory file: 
ansible_python_interpreter=/usr/bin/python3

ansible --version
ansible 2.4.3.0
  config file = /home/ozlevka/tmp/terraform/ansible.cfg
  configured module search path = ['/home/ozlevka/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ozlevka/.virtualenv/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/ozlevka/.virtualenv/ansible/bin/ansible
  python version = 3.6.3 (default, Nov 17 2017, 17:34:18) [GCC 5.4.0 20160609]
