### ISSUE TITLE
vmware_guest - Unable to clone VM when adding additionnal vnics

### ISSUE THREAD

**Issue by lrivallain** [ansible/ansible#35946]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0 (devel 03c73e2bbb) last updated 2018/02/08 10:14:52 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/suser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/suser/wd/ansible2/lib/ansible
  executable location = /home/suser/wd/ansible2/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
n/a

##### OS / ENVIRONMENT

* OS: Ubuntu 16.04
* pyvmomi  6.5.0.2017.5.post1
* Python 3.5.2
* vSphere Version 6.5u1
* vmware_guest.py and vmware.py are latest from devel

##### SUMMARY
When attempting to clone a virtual machine using the vmware_guest module, the playbook fails with the below message if adding more vNic in specifications than the current template has.

> *Failed to create a virtual machine : Incompatible device backing specified for device '1'.*

##### STEPS TO REPRODUCE

Having an existing template or VM with 1 network adapter.

Running a playbook that contains a clone of the existing tpl/vm and an additionnal network adapter:

```yaml
  tasks:
    - name: Deploy frontweb nodes
      vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        name: "{{ inventory_hostname }}"
        datacenter: "{{ datacenter }}"
        cluster: "{{ cluster }}"
        state: poweredon
        template: '{{ template }}'
        resource_pool: '{{ respool }}'
        validate_certs: no
        folder: "{{ datacenter }}/vm/{{ folder }}"
        networks:
        - name: "pg_frontweb"
          ip: "{{ ip1 }}"
          netmask: "{{ netmask1 }}"
          gateway: "{{ gateway }}"
          device_type: "vmxnet3"
          dns_servers:
          - "{{ dns_server }}"
        - name: "{{ network2 }}"
          ip: "{{ ip2 }}"
          netmask: "{{ netmask2 }}"
          device_type: "vmxnet3"
        snapshot_src: "{{ snapshot_name }}"
        linked_clone: yes
        customization:
          dns_servers:
            - "{{ dns_server }}"
          domain: "{{ dns_domain }}"
          dns_suffix: "{{ dns_domain }}"
          password: "{{ os_password }}"
        wait_for_ip_address: yes
```

##### EXPECTED RESULTS
The template is successfully cloned to a new virtual machine with 2 network adapters.

##### ACTUAL RESULTS

```json
   {
  "msg": "Failed to create a virtual machine : Incompatible device backing specified for device '1'.",
  "failed": true,
  "invocation": {
    "module_args": {
      "wait_for_ip_address": true,
      "linked_clone": true,
      "hardware": {},
      "esxi_hostname": null,
      "cluster": "Cust01",
      "template": "LinkedCloneRef_Ubuntu16.04",
      "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
      "customvalues": [],
      "uuid": null,
      "validate_certs": false,
      "snapshot_src": "20180129",
      "force": false,
      "disk": [],
      "customization": {
        "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "dns_servers": [
          "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
        ],
        "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
        "dns_suffix": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
      },
      "hostname": "vcsa01-back.********",
      "cdrom": {},
      "datacenter": "DC01",
      "username": "administrator@vsphere.local",
      "name_match": "first",
      "guest_id": null,
      "is_template": false,
      "state": "poweredon",
      "name": "web02",
      "port": 443,
      "networks": [
        {
          "device_type": "vmxnet3",
          "name": "pg_frontweb",
          "gateway": "10.10.107.254",
          "dns_servers": [
            "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
          ],
          "netmask": "255.255.255.0",
          "ip": "10.10.107.2"
        },
        {
          "device_type": "vmxnet3",
          "name": "pg_backend",
          "netmask": "255.255.255.0",
          "ip": "10.10.108.102"
        }
      ],
      "folder": "DC01/vm/app01",
      "annotation": null,
      "resource_pool": "prod"
    }
  }
}
```

vDevices specifications look complete at this steps but logs from the target ESXi about the virtual device specs are not complete, thats results in invalid backing error: https://gist.github.com/lrivallain/6905bb6efbba369b7dd3a5651d09bf13#file-vpxa-log

I will push a patch that looks to fix this use case in a PR during the current day.
