### ISSUE TITLE
Digital Ocean Tagging Error

### ISSUE THREAD

**Issue by wolfthefallen** [ansible/ansible#35986]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
digital_ocean_tag

##### ANSIBLE VERSION

```
ansible 2.4.3.0
python 3.6.3
```

##### CONFIGURATION
no changes

##### OS / ENVIRONMENT
n/a trying to tag a digital ocean droplet

##### SUMMARY
When trying to tag a digtial ocean droplet I get the following error message
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "error tagging resource '111111111': your request is malformed, please check your syntax: json: cannot unmarshal number into Go struct field Resource.resource_id of type string"}
```

##### STEPS TO REPRODUCE

Create a new droplet and try to tag it using the `digital_ocean_tag` module

```yaml
  - name: add  tag
    digital_ocean_tag:
      api_token: "{{ do_api_key }}"
      name: new-tag
      state: present
      resource_id: "{{ new_droplet.droplet.id }}"
```

##### EXPECTED RESULTS
It tags the droplet in digital ocean
