### ISSUE TITLE
ec2_asg terminates an instance before creating a replacement

### ISSUE THREAD

**Issue by 2rs2ts** [ansible/ansible#35993]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

ec2_asg

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /home/admin/.ansible.cfg
  configured module search path = [u'/home/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

Debian Jessie

##### SUMMARY

When I use `ec2_asg` to replace a single instance in an existing ASG, the old instance is terminated before a new one is created. This would be fine except that `ec2_asg` has classically worked by increasing the capacity of the ASG by 1 to first create a new instance. So now you get two new instances, and when `ec2_asg` scales the capacity back, you're at the mercy of the termination policy.

##### STEPS TO REPRODUCE

In my case I was working with an ASG with 3 instances. I suspect this will work with any number of instances though.

Assuming you have an AWS region, ASG, LC, and instance ID in mind:

```yaml
- ec2_asg:
    lc_check: no
    replace_batch_size: 1
    replace_instances: "{{ instance_to_cycle }}"
    name: "{{ asg_name }}"
    min_size: "3"
    max_size: "3"
    desired_capacity: "3"
    launch_config_name: "{{ lc_name }}"
    region: "{{ region }}"
    wait_timeout: 480
  register: ec2_asg_result
```

##### EXPECTED RESULTS

The ASG's min, max, and desired counts will all raise by 1. A new instance will start to be created. Once that happens, _then_ the min/desired counts will decrease so an old instance will be terminated.

##### ACTUAL RESULTS

An instance is terminated before a new instance is created. (I determined this just by repeatedly hitting the refresh button on the AWS console.)

Using `debug` on the result you can see that `ec2_asg_result.instances` has 4 IDs in it it.

~~I tried downgrading to 2.1.2.0 and did not see this behavior.~~ Never mind, I see this on that version too, it's just not consistent.
