### ISSUE TITLE
find module is unable to process lists received as paths parameter

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#35990]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
find module

##### ANSIBLE VERSION

```
ansible 2.4.3.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Despite the fact that documentation of file module states that paths parameter is a list of paths, the reality is that it fails to process lists received via variables, something that other modules process without problems.

##### STEPS TO REPRODUCE

```yaml
- hosts: 'localhost'
  #localhost
  vars:
      mylist:
        - aaa
        - bbb
  tasks:

  - find:
      paths:
      - "{{ mylist }}"
      - "~/logs/"
    patterns: "*.log,*.tar.gz"
    file_type: file
```

##### EXPECTED RESULTS
Process all 3 paths.

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'startswith'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/br/99tfdvcs3vvfwdk69z7f0xmc0000gn/T/ansible_6kcUps/ansible_module_find.py\", line 366, in <module>\n    main()\n  File \"/var/folders/br/99tfdvcs3vvfwdk69z7f0xmc0000gn/T/ansible_6kcUps/ansible_module_find.py\", line 312, in main\n    npath = os.path.expanduser(os.path.expandvars(npath))\n  File \"/Users/ssbarnea/.pyenv/versions/2.7.14/lib/python2.7/posixpath.py\", line 254, in expanduser\n    if not path.startswith('~'):\nAttributeError: 'list' object has no attribute 'startswith'\n",
    "module_stdout": "",
    "rc": 0
}

MSG:

MODULE FAILURE
```
