### ISSUE TITLE
Unable to delete vswitch using vmware_vswitch

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#36009]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_vswitch

##### ANSIBLE VERSION

```
ansible 2.5.0a1
```

##### OS / ENVIRONMENT

```
N/A
```
##### STEPS TO REPRODUCE

```
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Delete a VMware vSwitch
      action:
        module: vmware_vswitch
        hostname: 10.243.1.43
        username: root
        password: PASSW0RD
        switch: vSwitch0
        nics: vmnic0
        mtu: 1500
        validate_certs: no
        state: absent


```

##### EXPECTED RESULTS

```
Expect vswitch vSwitch0 to be deleted from ESXI host
```
##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_u4aPP7/ansible_module_vmware_vswitch.py", line 152, in process_state
    vswitch_states[self.state][self.check_vswitch_configuration()]()
  File "/tmp/ansible_u4aPP7/ansible_module_vmware_vswitch.py", line 191, in state_destroy_vswitch
    self.host_system.configManager.networkSystem.UpdateNetworkConfig(config, "modify")
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "esxi_hostname": null, 
            "hostname": "10.243.1.43", 
            "mtu": 1500, 
            "nics": [
                "vmnic0"
            ], 
            "number_of_ports": 128, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "state": "absent", 
            "switch": "vSwitch0", 
            "username": "root", 
            "validate_certs": false
        }
    }, 
    "msg": "A specified parameter was not correct: "
}

```
