### ISSUE TITLE
vmware module does not accept IP address as parameter

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#36010]
when trying to configure ESXI host, i am forced to give hostname for esxi. parameter esxi_hostname is not accepting ESXI host Ip address. 

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
vmware_portgroup
vmware_vmkernel
vmware_maintenancemode

```
##### ANSIBLE VERSION

```
ansible 2.5.0a1 + patch  #35531(https://github.com/ansible/ansible/pull/35531)
```

##### OS / ENVIRONMENT

```
N/A
```
##### SUMMARY

```
For operations like 
1) adding vmkernel port to ESXI host (esxi_hostname parameter is mandatory and it forces to give hostname doesnt accept IP pf esxi host)
2) puting ESXI host in maintenance mode (esxi_hostname parameter is mandatory and it forces to give hostname doesnt accept IP pf esxi host)
3) adding portgroup to vswitch on ESXI host (hosts parameter is mandatory nd it forces to give hostname doesnt accept IP pf esxi host)
```
##### STEPS TO REPRODUCE

```
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    -  name: Add Management vmkernel port using dhcp network type
       local_action:
         module: vmware_vmkernel
         esxi_hostname: 10.243.1.43
         hostname: 10.243.1.43
         username: root
         password: PASSW0RD
         vswitch_name: vSwitch0
         portgroup_name: vmotion               
         vlan_id: 0
         network:
           type: dhcp
           ip_address: ""
           subnet_mask: ""
         enable_mgmt: False
         enable_vmotion: True
         enable_vsan: False
         validate_certs: no

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Enter host in Maintenance Mode
      vmware_maintenancemode:
          hostname: 10.243.1.43
          username: root
          password: PASSW0RD
          esxi_hostname: 10.243.1.43
          state: present
          vsan: ensureObjectAccessibility
          evacuate: yes
          timeout: 3600
          validate_certs: False
      tags:
        - test1

---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add Management Network VM Portgroup
      local_action:
        module: vmware_portgroup
        hostname: 10.243.1.43
        hosts: 10.243.1.43
        username: root
        password: PASSW0RD
        switch_name: vSwitch1
        portgroup_name: vm12
        vlan_id: 0
        validate_certs: no




```

##### EXPECTED RESULTS

```
expect vmkernel interface to be created on vswitch
expect esxi host to be in maintenance mode
expect portgroup to be added on esxi hosts vswitch
```
##### ACTUAL RESULTS

```
for vmware_maintenace get error as Host 10.243.1.43 not found in vCenter

for vmware_vmkernel get error as ESXi 10.243.1.43 not found
```
