### ISSUE TITLE
"No folder matched the path" with deploy of a VM from the template

### ISSUE THREAD

**Issue by Tclemento** [ansible/ansible#36027]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

##### OS / ENVIRONMENT

RHEL7
Python 2.7.5

##### STEPS TO REPRODUCE

```yaml
 tasks:
   - name: Create the VM
     delegate_to: localhost
     vmware_guest:
       hostname: VCENTERNAME
       username: USERNAME
       password: PASSWORD
       validate_certs: no
       esxi_hostname: ESXINAME
       name: vmtestdeploytemplate
       datacenter: SYSINSTALL
       folder: SYSINSTALL/INSTALL_LINUX/vm/test
       template: VMTEMPLATE
```

Command
```
ansible localhost -m vmware_guest_find -a '... name=VMTEMPLATE datacenter=SYSINSTALL'
localhost | SUCCESS => {
    "changed": false,
    "folders": [
        "/INSTALL_LINUX/vm/test"
    ]
```
##### ACTUAL RESULTS
When I deploy, I have the error:
```
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "No folder matched the path: /SYSINSTALL/INSTALL_LINUX/vm/test"}
```
It's a bug reported but no news?
Thx
