### ISSUE TITLE
xml module,  "state: present" does not work properly

### ISSUE THREAD

**Issue by hammersoft** [ansible/ansible#36031]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

xml

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = ['/home/v.polyakov/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.5/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.5/ansible
  python version = 3.5.4 (default, Jan  9 2018, 03:20:28) [GCC 6.4.0]
```

##### CONFIGURATION

default config

##### OS / ENVIRONMENT

Centos 6.8, python-lxml-2.3.0

##### SUMMARY

"state: present" command does not work poperly

##### STEPS TO REPRODUCE

I am using this xml
```
<tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">
<!-- 
...
 -->
</tomcat-users>
```
and next ansible task

```yaml
- stat:
    path: "{{ destination_dir }}/{{ tomcat_name }}/conf/tomcat-users.xml"
  register: users_config

- name: "Add tomcat manager-script role"
  xml:
    pretty_print: true
    path: "{{ users_config.stat.path }}"
    xpath: /tomcat-users/role[@rolename="tomcat-script"]
    state: present
  when: users_config.stat.isreg

```

##### EXPECTED RESULTS

According to documentation
```
state:
   description:
   - Set or remove an xpath selection (node(s), attribute(s))
```
expecting to add node into xml file, like this 
```
  <tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">
<!-- 
...
 -->
<role rolename="tomcat-script" />
</tomcat-users>
```

##### ACTUAL RESULTS

Module fails to evaluate xpath, assume module does not validate path recursively.

```
fatal: [server_name]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to server_name closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_MjPdT1/ansible_module_xml.py\", line 853, in <module>\r\n    main()\r\n  File \"/tmp/ansible_MjPdT1/ansible_module_xml.py\", line 843, in main\r\n    ensure_xpath_exists(module, doc, xpath, namespaces)\r\n  File \"/tmp/ansible_MjPdT1/ansible_module_xml.py\", line 536, in ensure_xpath_exists\r\n    changed = check_or_make_target(module, tree, xpath, namespaces)\r\n  File \"/tmp/ansible_MjPdT1/ansible_module_xml.py\", line 474, in check_or_make_target\r\n    changed = check_or_make_target(module, tree, inner_xpath, namespaces)\r\n  File \"/tmp/ansible_MjPdT1/ansible_module_xml.py\", line 473, in check_or_make_target\r\n    if not is_node(tree, inner_xpath, namespaces):\r\n  File \"/tmp/ansible_MjPdT1/ansible_module_xml.py\", line 318, in is_node\r\n    if xpath_matches(tree, xpath, namespaces):\r\n  File \"/tmp/ansible_MjPdT1/ansible_module_xml.py\", line 342, in xpath_matches\r\n    if tree.xpath(xpath, namespaces=namespaces):\r\n  File \"lxml.etree.pyx\", line 2029, in lxml.etree._ElementTree.xpath (src/lxml/lxml.etree.c:45934)\r\n  File \"xpath.pxi\", line 379, in lxml.etree.XPathDocumentEvaluator.__call__ (src/lxml/lxml.etree.c:114389)\r\n  File \"xpath.pxi\", line 242, in lxml.etree._XPathEvaluatorBase._handle_result (src/lxml/lxml.etree.c:113063)\r\n  File \"xpath.pxi\", line 228, in lxml.etree._XPathEvaluatorBase._raise_eval_error (src/lxml/lxml.etree.c:112935)\r\nlxml.etree.XPathEvalError: Invalid expression\r\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/xml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/xml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by hammersoft** [comment]
same as #29078, need to specify xml namespace in xpath. 
This works fine.  
```
- name: "Add tomcat manager-script role"
  xml:
    pretty_print: true
    path: "{{ users_config.stat.path }}"
    xpath: /t:tomcat-users/role[@rolename='tomcat-script']
    namespaces:
      t: http://tomcat.apache.org/xml
    state: present
  when: users_config.stat.isreg
```
