### ISSUE TITLE
Refactor vmware_vswitch is required

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#36030]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
vmware_vswitch
```
##### ANSIBLE VERSION

```
2.5.0a1
```

##### SUMMARY

```
when i have switch created on certain nic and trying to create another switch with same name on another nic i should get error but ansible module didnt return error instead returned success
```
##### STEPS TO REPRODUCE

```
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add a VMware vSwitch
      action:
        module: vmware_vswitch
        hostname: 10.243.1.43
        username: root
        password: PASSW0RD
        switch: vSwitch0
        nics: vmnic0
        mtu: 1500
        validate_certs: no
        state: present
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add a VMware vSwitch
      action:
        module: vmware_vswitch
        hostname: 10.243.1.43
        username: root
        password: PASSW0RD
        switch: vSwitch0
        nics: vmnic1
        mtu: 1500
        validate_certs: no
        state: present


```

##### EXPECTED RESULTS

```
expect error as switch is already attached to vmnic0 or at end of script switch should get attached to both nics
```
##### ACTUAL RESULTS

```
 playbook executed successfully and Vswitch0 is still attached to only vmnic0
```

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_vswitch.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_vswitch.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@umrikar Thanks for reporting this issue. Could you please provide output of `-vvvv` ?

needs_info

**Comment by Akasurde** [comment]
resolved_by_pr #36091

**Comment by Akasurde** [comment]
@umrikar Could you please check above patch and let me know if it works for you ?

**Comment by umrikar** [comment]
fixed with #36091...Thanks

**Comment by umrikar** [comment]
Thanks..issue resolved with https://github.com/ansible/ansible/pull/36091

**Comment by umrikar** [comment]
Hi,
  after rerunning playbook i observed that available_vswitch.pnic is changing for every run of same playbook. Its becoming empty and next run it pics the nic for corresponding switch
reproducible with below playbook run twince..it will not have any vmics attached to it.

```yaml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add a VMware vSwitch
      action:
        module: vmware_vswitch
        hostname: <ESXI host ip>
        username: root
        password: PASSW0RD
        switch: vSwitch0
        nics: vmnic0
        mtu: 1500
        validate_certs: no
        state: present
```

**Comment by umrikar** [comment]
@Akasurde i am seeing many failure scenarios

**Comment by umrikar** [comment]
i could see some more failure scenarios

if i rerun playbook...it gets detached from vmnic on any network

- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add a VMware vSwitch
      action:
        module: vmware_vswitch
        hostname: 10.243.1.43
        username: root
        password: PASSW0RD
        switch: vSwitch1
        nics: vmnic1
        mtu: 1500
        validate_certs: no
        state: present
if i run first time..it creates switch next run for same playbook..it updates vswitch and switch looses its uplink

**Comment by umrikar** [comment]
network_manager.networkInfo.vswitch 
available_vswitch.pnic is changing for every run of same playbook

**Comment by Akasurde** [comment]
@umrikar Could you please elaborate the scenario that you are trying to do with `-vvvv` logs and whole playbook ? 

needs_info

**Comment by umrikar** [comment]
@Akasurde when i run below playbook.At first run it creates switch ,when i run same playbook again it updates switch and its vmnics becomes null.that is switch loses its nics.I have debugged code and found that value for "available_vswitch.pnic" is changing for switch for every run.even though we dont update anything.To reproduce this scenario
please run below playbook twice.observer result after every run.you could see after second run.your switch doesnt have any uplink

```yaml
 ---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add a VMware vSwitch
      action:
        module: vmware_vswitch
        hostname: <ESXI host ip>
        username: root
        password: PASSW0RD
        switch: vSwitch1
        nics: vmnic1
        mtu: 1500
        validate_certs: no
        state: present
```

**Comment by Akasurde** [comment]
@umrikar Can you check updated PR ? 

With new Patch, 

```
TASK [Create a vswitch] ********************************************************************************************************
task path: /vmware/vmware_vswitch.yml:8
changed: [localhost] => {"changed": true, "result": "vSwitch 'vSwitch_0012' is created successfully"}

TASK [Update a vswitch] ********************************************************************************************************
task path: /vmware/vmware_vswitch.yml:20
ok: [localhost] => {"changed": false, "result": "No change in vSwitch 'vSwitch_0012'"}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by umrikar** [comment]
@Akasurde new patch is failing for couple of scenarios i tested 
if i try to update mtu size, if i try to change nic(vmic1 to vmnic0)

to reproduce update mtu size.Follow below steps

```yaml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add a VMware vSwitch
      action:
        module: vmware_vswitch
        esxi_hostname: <ESXI-IP>
        hostname: <ESXI-IP>
        username: root
        password: PASSW0RD
        switch: vSwitch1
        nics: [vmnic1]
        mtu: 1500
        validate_certs: no
        state: present


---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add a VMware vSwitch
      action:
        module: vmware_vswitch
        esxi_hostname: <ESXI-IP>
        hostname: <ESXI-IP>
        username: root
        password: PASSW0RD
        switch: vSwitch1
        nics: [vmnic1]
        mtu: 9000
        validate_certs: no
        state: present
```

Failure log:- 

```
The full traceback is:
  File "/tmp/ansible_nGOLO5/ansible_module_vmware_vswitch.py", line 324, in state_update_vswitch
    spec=vss_spec)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "failed": true, 
    "invocation": {
        "module_args": {
            "esxi_hostname": "10.243.1.46", 
            "hostname": "10.243.1.46", 
            "mtu": 9000, 
            "nics": [
                "vmnic1"
            ], 
            "number_of_ports": 128, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "state": "present", 
            "switch": "vSwitch1", 
            "username": "root", 
            "validate_certs": false
        }
    }, 
    "msg": "Failed to update vSwitch 'vSwitch1', this can be due to either of following : 1. vSwitch Name exceeds the maximum allowed length, 2. Number of ports specified falls out of valid range, 3. Network policy is invalid, 4. Beacon configuration is invalid : A specified parameter was not correct: "
}
	to retry, use: --limit @/home/lenovo/create_switch.retry

PLAY RECAP ***********************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1   
```
