### ISSUE TITLE
Kubernetes: module doesn't update deployment definition 

### ISSUE THREAD

**Issue by sebastianlach** [ansible/ansible#36047]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

kubernetes

##### ANSIBLE VERSION

```
ansible==2.4.0.0
```

##### CONFIGURATION

PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT

Arch Linux
Python 2/3

##### SUMMARY

I would expect the module to behave like `kubectl` command however it doesn't seem so.

##### STEPS TO REPRODUCE

Let's take under consideration following playbook:

```yaml
---

- hosts: [all]
  tasks:
  - debug: var=kubernetes_api_endpoint
  - kubernetes:
      api_endpoint: "{{ kubernetes_api_endpoint }}"
      url_username: "{{ kubernetes_url_username or omit }}"
      url_password: "{{ kubernetes_url_password or omit }}"
      insecure: "{{ kubernetes_insecure or omit }}"
      file_reference: myapp.yaml

```

And kubernetes definition `myapp.yaml`:

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: library/alpine:3.7
        command: ["sleep", "3600"]
```

During first run Kubernetes deployment will be created. However changes in `myapp.yaml` won't be applied to deployment (for example:  image: library/alpine:3.6).

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: myapp
spec:
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: library/alpine:3.6
        command: ["sleep", "3600"]
```

##### EXPECTED RESULTS

```
PLAY [all] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] **********************************************************************************************************************************************************************************
ok: [localhost] => {
    "kubernetes_api_endpoint": "XXX.XXX.XXX.XXX"
}

TASK [kubernetes] *****************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

Deployment definition is not updated.

```
PLAY [all] ************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************
ok: [localhost]

TASK [debug] **********************************************************************************************************************************************************************************
ok: [localhost] => {
    "kubernetes_api_endpoint": "35.187.118.206"
}

TASK [kubernetes] *****************************************************************************************************************************************************************************
ok: [localhost]

PLAY RECAP ************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

##### NOTES
Using `state: update` instead of `state: present` provides desired behavior of modules during second run however it's not satisfying solution because it leads to boilerplate code (for example checking if deployment already exists in cluster) and unwanted complexity.
