### ISSUE TITLE
win_iis_virtualdirectory does not work with network path

### ISSUE THREAD

**Issue by toneill818** [ansible/ansible#36060]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_iis_virtualdirectory

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/toneill/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT
MacOS 10.12.6

##### SUMMARY
When using a network directories it errors saying "specified folder must already exist: physical_path". Using Powershell I checked the provided path with the Test-Path command and it returns true.

##### STEPS TO REPRODUCE

Run the following on a remote directory
```yaml
iis_virtual_directories:
  - {name: virtDir, path: '\\computerName\Path\Folder'}

- name: Create root virtual directories
  win_iis_virtualdirectory:
    name: '{{ item.name }}'
    physical_path: '{{ item.path }}'
    site: '{{ iis_website_name }}'
  with_items: " {{ iis_virtual_directories }}"
```

##### EXPECTED RESULTS
A virtual directory to be created in IIS.

##### ACTUAL RESULTS

```
failed: [10.102.2.116] (item={u'path': u'\\\\computerName\\Path\\Folder', u'name': Folder}) => {
    "changed": false,
    "item": {
        "name": Folder,
        "path": "\\\\computerName\\Path\\Folder"
    },
    "msg": "specified folder must already exist: physical_path"
}
```
