### ISSUE TITLE
How do you declare host variables in YAML inventory

### ISSUE THREAD

**Issue by grantcurell** [ansible/ansible#36061]
##### ISSUE TYPE
 - Bug Report
- Question really?

##### COMPONENT NAME
inventory.yml

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /root/rock/playbooks/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT
CentOS 7.4

##### SUMMARY
I'm trying to declare host-specific variables in a YAML inventory file. See the sensors group at the bottom - variable is bro_interface:

```
---
# The inventory defines which hosts belong to which groups and what variables are applied to them. The playbooks
# themselves in our scheme do not define any variables. The names you see on the far left here correspond to the limit
# function you can run with the ansible-playbook command. For example ansible-playbook site.yml --limit sensor would
# look at this inventory file and see the hosts that are part of the sensor group. When site.yml imports the sensors.yml
# file, sensor.yml will only apply itself to the servers listed in the sensors group in this inventory file.

all:

  children:

    # Role specific breakout

    kubernetes:
      children:
        master-servers:
        nodes:

    gluster:
      children:
        master-servers:
        nodes:

    kibana:
      children:
        master-servers:

    elasticsearch:
      children:
        master-servers:

    logstash:
      children:
        master-servers:

    suricata:
      children:
        sensors:

    filebeat:
      children:
        sensors:

    kafka:
      children:
        master-servers:

    bro:
      children:
        master-servers:

    master-servers:

      vars:
        data_disk_devices:
        - /dev/sdb

      hosts:
        rockserver1.lan:
          ansible_hostname: rockserver1.lan
          ansible_user: root
          ansible_connection: ssh

    nodes:

      children:

        sensors:

          hosts:
            rocksensor1.lan:
              ansible_hostname: rocksensor1.lan
              ansible_connection: ssh
              data_disk_devices:
              - /dev/sdb
              home_net: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
              bro_interface: ens224

        servers:

          vars:
            data_disk_devices:
            - /dev/sdb

          hosts:
            rockserver3.lan:
              ansible_hostname: rockserver3.lan
              ansible_user: root
              ansible_connection: ssh

```

I have a bro role with a default value of eth0, which seems to be winning out. I know I'm missing something. I see the example here: http://docs.ansible.com/ansible/latest/intro_inventory.html#id7, but there is no example for the YAML version. How do you do that, but with a YAML inventory?

##### EXPECTED RESULTS
I expected bro_interface to take precedence in my bro role over the bro_interface variable in defaults.

##### ACTUAL RESULTS
It doesn't seem that my bro role sees the variable from the inventory file at all.
