### ISSUE TITLE
security_group_name parameter is ignored by azure_rm_networkinterface

### ISSUE THREAD

**Issue by zwindler** [ansible/ansible#36093]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION
```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/dgermain/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
(empty)
```

##### OS / ENVIRONMENT
Ansible running on WSL (Ubuntu) on Windows 10

##### SUMMARY
Given network security group is ignored when specified, even if it exists. A new default security group is created at the same time the network interface is created

##### STEPS TO REPRODUCE
Create a network security group, create a public ip address, create a network interface with the network security group specified

```
cat issue_nsg.yml
---
- name: "Reproduce issue"
  hosts: all
  vars:
    - resourcegroup_name: "my-existing-rg"
    - virtualnetwork_name: "my-existing-network"
    - subnet_name: "my-existing-subnet"
  tasks:
    - name: "Create Public IP address"
      azure_rm_publicipaddress:
        name: "my_ip"
        resource_group: "{{resourcegroup_name}}"
        allocation_method: Static
        domain_name: "mydomainname"

    - name: "Create security rules"
      azure_rm_securitygroup:
        name: "my_nsg"
        resource_group: "{{resourcegroup_name}}"
        purge_rules: yes
        rules:
          - name: 'DenyInbound'
            protocol: 'Tcp'
            access: Deny
            priority: 1000
            direction: Inbound

    - name: "Create a network interface for each VM"
      azure_rm_networkinterface:
        name: "my_ni"
        resource_group: "{{resourcegroup_name}}"
        virtual_network_name: "{{virtualnetwork_name}}"
        subnet_name: "{{subnet_name}}"
        security_group_name: "my_nsg"
        ip_configurations:
        - name: "ipconfig"
          public_ip_address_name: "my_ip"
          primary: True
```

##### EXPECTED RESULTS
A network interface should be created and associated with the given network security group (my_nsg)

##### ACTUAL RESULTS
A new security group (my_ni) is created with the same name as the interface (my_ni). The interface is associated with this newly create network security group and not the wanted one (my_nsg).
