### ISSUE TITLE
elb_application_lb: "There is an issue in the code of the module. You must specify either both, resource or client to the conn_type parameter in the boto3_conn function call"

### ISSUE THREAD

**Issue by ilangrs** [ansible/ansible#36115]
##### SUMMARY
When I am running "elb_application_lb" module I am getting the following error message:

"There is an issue in the code of the module. You must specify either both, resource or client to the conn_type parameter in the boto3_conn function call"

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`elb_application_lb.py`

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Nothing has changed

##### OS / ENVIRONMENT
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

##### STEPS TO REPRODUCE
```yaml
- elb_application_lb:
    name: myelb
    region:
       - us-east-1a
    security_groups:
       - VA_Stage_BE_LB
    subnets:
       - Staging_BE_Servers_e
       - Staging_BE_Servers_d
    listeners:
      - Protocol: HTTPS
        Port: 80
        SslPolicy: ELBSecurityPolicy-2016-08
        Certificates:
          - CertificateArn: arn:aws:iam::743434360758:server-certificate/Wildcard-2019
        DefaultActions:
          - Type: forward
            TargetGroupName: STAGE-FE-LB
    state: present
```

##### EXPECTED RESULTS
New elb will be created in AWS.

##### ACTUAL RESULTS
```
The full traceback is:
  File "/tmp/ansible_lMmIfk/ansible_modlib.zip/ansible/module_utils/ec2.py", line 99, in boto3_conn
    return _boto3_conn(conn_type=conn_type, resource=resource, region=region, endpoint=endpoint, **params)
  File "/tmp/ansible_lMmIfk/ansible_modlib.zip/ansible/module_utils/ec2.py", line 118, in _boto3_conn
    client = boto3.session.Session(profile_name=profile).client(resource, region_name=region, endpoint_url=endpoint, **params)
  File "/usr/local/lib/python2.7/dist-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python2.7/dist-packages/botocore/session.py", line 861, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 76, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 295, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python2.7/dist-packages/botocore/args.py", line 79, in get_client_args
    timeout=(new_config.connect_timeout, new_config.read_timeout))
  File "/usr/local/lib/python2.7/dist-packages/botocore/endpoint.py", line 289, in create_endpoint
    raise ValueError("Invalid endpoint: %s" % endpoint_url)

fatal: [192.168.100.248]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "access_logs_enabled": null,
            "access_logs_s3_bucket": null,
            "access_logs_s3_prefix": null,
            "aws_access_key": null,
            "aws_secret_key": null,
            "deletion_protection": false,
            "ec2_url": null,
            "idle_timeout": null,
            "listeners": [
                {
                    "Certificates": [
                        {
                            "CertificateArn": "arn:aws:iam::743434360758:server-certificate/Wildcard-2019"
                        }
                    ],
                    "DefaultActions": [
                        {
                            "TargetGroupName": "STAGE-FE-LB",
                            "Type": "forward"
                        }
                    ],
                    "Port": 443,
                    "Protocol": "HTTPS",
                    "SslPolicy": "ELBSecurityPolicy-2016-08"
                }
            ],
            "name": "myelb",
            "profile": null,
            "purge_listeners": true,
            "purge_tags": true,
            "region": "['us-east-1a']",
            "scheme": "internet-facing",
            "security_groups": [
                "VA_Stage_BE_LB"
            ],
            "security_token": null,
            "state": "present",
            "subnets": [
                "Staging_BE_Servers_e",
                "Staging_BE_Servers_d"
            ],
            "tags": {},
            "validate_certs": true,
            "wait": null,
            "wait_timeout": null
        }
    },
    "msg": "There is an issue in the code of the module. You must specify either both, resource or client to the conn_type parameter in the boto3_conn function call"
}
        to retry, use: --limit @/home/jenkins/playbooks/insights-install/elb_test.retry
```
