### ISSUE TITLE
lineinfile ignore some of my lines insertions

### ISSUE THREAD

**Issue by yaniveliash** [ansible/ansible#36136]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/x/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT
Centos 7.4

##### SUMMARY
I'm using lineinfile to populate a new empty configuration file for logstash pipeline
however ansible ignore last 2 lines that contain only curly brackets.

##### STEPS TO REPRODUCE
```
  - name: add filebeat support to logstash
    lineinfile:
      path: /etc/logstash/conf.d/filebeat.conf
      line: "{{ item.line }}"
    with_items:
        - { line: 'input {' }
        - { line: '  beats {' }
        - { line: '    port => 5044' }
        - { line: '  }' }
        - { line: '}' }
        - { line: '' }
        - { line: 'output {' }
        - { line: '  elasticsearch {' }
        - { line: '    hosts => "localhost:9200"' }
        - { line: '    manage_template => false' }
        - { line: '    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"' }
        - { line: '    document_type => "%{[@metadata][type]}"' }
        - { line: '  }' }
        - { line: '}' }
    become: true
```

##### EXPECTED RESULTS
```
input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => "localhost:9200"
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
  }
}
```
##### ACTUAL RESULTS
```
input {
  beats {
    port => 5044
  }
}

output {
  elasticsearch {
    hosts => "localhost:9200"
    manage_template => false
    index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
    document_type => "%{[@metadata][type]}"
```
