### ISSUE TITLE
Add ability to define filter macros

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#36130]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
filters

##### SUMMARY
Ansible filters in chains are really powerful. But when having a long chain of filters, it "pollutes" your playbooks with long or multi-line expressions. Moreover, it is counter-productive to modify a repeating filter chain if need be. It would also add context to what you filter chain does by naming it.

Example of a long filter chain:
```yaml
nextcloud_app_store_json                                                                     
| selectattr('id', 'equalto', item.name)                                                                                                                                         
| map(attribute='releases')                                                                  
| first                                                                                      
| regex_replace(...)
| b64encode
```
Imagine having to repeat this throughout your playbook.

An option could be to have sth like:
```yaml
- set_macro:
    macro_name: >-
      repeat here the previous example

- name: Use macro
  set_fact: "{{ variable | macro_name }}"
```
