### ISSUE TITLE
Ansible not able to expand Windows vars from %PATH%

### ISSUE THREAD

**Issue by pontusanderssonXD** [ansible/ansible#36187]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_path

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/Users/Pontus/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

Running Ansible from macOS High Sierra version 10.13.3

Controling a Windows Server 2012 R2 machine

##### SUMMARY

When adding a Windows enviroment variable containg another Windows enviroment variable to PATH, Ansible seems to not be able to interpret the actual value from PATH.
##### STEPS TO REPRODUCE

```yaml
- name: Create M2_HOME enviroment variable
  win_environment:
    name: M2_HOME
    value: C:\Program Files\Maven
    level: machine
    state: present

- name: Create M2 enviroment variable
  win_path:
    name: M2
    elements: '%M2_HOME%\bin'
    state: present

- name: Add M2 to PATH
  win_path:
    name: PATH
    elements: '%M2%'
    state: present

- win_shell: mvn -version; echo $env:M2_HOME; echo $env:M2; echo $env:PATH
  register: maven_return
```

##### EXPECTED RESULTS

```
TASK [maven : win_shell] ***************************************************************************************************************************
task path: /Users/Pontus/Ansible/Mule/roles/maven/tasks/main.yml:50
Using module file /Library/Python/2.7/site-packages/ansible/modules/windows/win_shell.ps1
<192.168.220.131> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 192.168.220.131
EXEC (via pipeline wrapper)
changed: [192.168.220.131] => {
    "changed": true, 
    "cmd": "mvn -version; echo $env:M2_HOME; echo $env:M2; echo $env:PATH", 
    "delta": "0:00:00.421876", 
    "end": "2018-02-14 04:44:11.074695", 
    "failed": false, 
    "rc": 0, 
    "start": "2018-02-14 04:44:10.652818", 
    "stderr": "The JAVA_HOME environment variable is not defined correctly \r\nThis environment variable is needed to run this program \r\nNB: JAVA_HOME should point to a JDK not a JRE \r\n", 
    "stderr_lines": [
        "The JAVA_HOME environment variable is not defined correctly ", 
        "This environment variable is needed to run this program ", 
        "NB: JAVA_HOME should point to a JDK not a JRE "
    ], 
    "stdout": "C:\\Program Files\\Maven\r\nC:\\Program Files\\Maven\\bin\r\nC:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Maven\\bin\r\n", 
    "stdout_lines": [
        "C:\\Program Files\\Maven", 
        "C:\\Program Files\\Maven\\bin", 
        "C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;C:\\Program Files\\Maven\\bin"
    ]
}
```

##### ACTUAL RESULTS

```
TASK [maven : win_shell] ***************************************************************************************************************************
task path: /Users/Pontus/Ansible/Mule/roles/maven/tasks/main.yml:50
Using module file /Library/Python/2.7/site-packages/ansible/modules/windows/win_shell.ps1
<192.168.220.131> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 192.168.220.131
EXEC (via pipeline wrapper)
changed: [192.168.220.131] => {
    "changed": true, 
    "cmd": "mvn -version; echo $env:M2_HOME; echo $env:M2; echo $env:PATH", 
    "delta": "0:00:00.656254", 
    "end": "2018-02-14 04:47:28.489649", 
    "failed": false, 
    "rc": 0, 
    "start": "2018-02-14 04:47:27.833395", 
    "stderr": "mvn : The term 'mvn' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s\r\npelling of the name, or if a path was included, verify that the path is correct and try again.\r\nAt line:1 char:65\r\n+ [Console]::InputEncoding = New-Object Text.UTF8Encoding $false; mvn -version; ec ...\r\n+                                                                 ~~~\r\n    + CategoryInfo          : ObjectNotFound: (mvn:String) [], CommandNotFoundException\r\n    + FullyQualifiedErrorId : CommandNotFoundException", 
    "stderr_lines": [
        "mvn : The term 'mvn' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the s", 
        "pelling of the name, or if a path was included, verify that the path is correct and try again.", 
        "At line:1 char:65", 
        "+ [Console]::InputEncoding = New-Object Text.UTF8Encoding $false; mvn -version; ec ...", 
        "+                                                                 ~~~", 
        "    + CategoryInfo          : ObjectNotFound: (mvn:String) [], CommandNotFoundException", 
        "    + FullyQualifiedErrorId : CommandNotFoundException"
    ], 
    "stdout": "C:\\Program Files\\Maven\r\nC:\\Program Files\\Maven\\bin\r\nC:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;%M2%\r\n", 
    "stdout_lines": [
        "C:\\Program Files\\Maven", 
        "C:\\Program Files\\Maven\\bin", 
        "C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\ProgramData\\chocolatey\\bin;%M2%"
    ]
}
```
The %M2% variable is not expanded to the actual path but when I run "echo %PATH%" manually I get the full path.

I have found a work around that makes it work, if i add another value to %PATH% with powershell, through the win_shell modul and then remove it again Ansible is able to read the value of %M2%, and I get the expected result:

```yaml
- name: Create M2_HOME enviroment variable
  win_environment:
    name: M2_HOME
    value: C:\Program Files\Maven
    level: machine
    state: present

- name: Create M2 enviroment variable
  win_path:
    name: M2
    elements: '%M2_HOME%\bin'
    state: present

- name: Add M2 to PATH variable
  win_path:
    name: PATH
    elements: '%M2%'
    state: present

#Add C:\tmp to PATH temporarily
- win_shell: '$AddedLocation ="C:\\tmp"; $Reg = "Registry::HKLM\System\CurrentControlSet\Control\Session Manager\Environment"; $OldPath = (Get-ItemProperty -Path "$Reg" -Name PATH).Path; $NewPath= $OldPath + ’;’ + $AddedLocation; Set-ItemProperty -Path "$Reg" -Name PATH –Value $NewPath'

- name: Remove tmp from PATH
  win_path:
    name: PATH
    elements: C:\tmp
    state: absent
```

I does not work if I add the temp-value to PATH from the win_path module, that gives the same result as the "Actual result" above.
