### ISSUE TITLE
ec2_asg_facts throws errors with AutoScalingReadOnly Policy

### ISSUE THREAD

**Issue by petewilcock** [ansible/ansible#36192]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_asg_facts

##### ANSIBLE VERSION
```
ansible 2.4.3.0
```

##### CONFIGURATION
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
When attaching the AWS Managed Policy 'AutoScalingReadOnlyAccess', ec2_asg_facts throws the error that the result dict is empty. 

When attaching ''AutoScalingFullAccess', no error occurs. 

One assumes that a facts module would require only Describe*/Read Only CLI commands for AWS, rather than anything which might require an update. 

##### STEPS TO REPRODUCE

```yaml
- ec2_asg_facts:
        name: "{{ service_name }}-AutoScalingGroup"
        region: "us-east-1"
      register: asgs
      failed_when: "{{ asgs.results | length > 1 }}"
```
##### EXPECTED RESULTS
A populated asgs variable with the described list of autoscaling groups as per the filter.  

##### ACTUAL RESULTS
Error is thrown, presumably because the ReadOnly role lacks the required permissions. 

--

If this behaviour is intended, clarify documentation with example minimal IAM policy required for the module to function as expected?
