### ISSUE TITLE
Ansible Cisco IOS - Telnet

### ISSUE THREAD

**Issue by ajayreddy28390** [ansible/ansible#36199]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /home/am/test_cswt/ansible.cfg
  configured module search path = ['/home/am/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/am/env2/lib/python3.6/site-packages/ansible
  executable location = /home/am/env2/bin/ansible
  python version = 3.6.3 (default, Feb  8 2018, 12:39:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

[defaults]
transport = paramiko
hostfile = ./hosts
host_key_checking = false
timeout = 5
log_path = ./ansible.log

##### OS / ENVIRONMENT

Linux  3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
##### STEPS TO REPRODUCE

```yaml
---
- name: show version
  hosts: "ios_devices"
  gather_facts: false
  connection: local
  serial: 6
  tasks:
   - telnet:
      user: cisco
      password: cisco
      login_prompt: "Username: "
      prompts:
        - "[>|#]"
      command:
        - show version
```

##### EXPECTED RESULTS

Expect to logon to device and run command: show version
##### ACTUAL RESULTS

```
ansible-playbook telnet_test.yml  -vvvv
ansible-playbook 2.4.3.0
  config file = /home/am/test_cswt/ansible.cfg
  configured module search path = ['/home/am/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/am/env2/lib/python3.6/site-packages/ansible
  executable location = /home/am/env2/bin/ansible-playbook
  python version = 3.6.3 (default, Feb  8 2018, 12:39:01) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /home/am/test_cswt/ansible.cfg as config file
[DEPRECATION WARNING]: [defaults]hostfile option, The key is misleading as it can also be a list of hosts, a directory or a list of paths . This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
setting up inventory plugins
Parsed /home/am/test_cswt/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/am/env2/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: telnet_test.yml ******************************************************************************************************************************************************************************************************************
1 plays in telnet_test.yml

PLAY [show version] ************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [telnet] ******************************************************************************************************************************************************************************************************************************
task path: /home/am/test_cswt/telnet_test.yml:8
The full traceback is:
Traceback (most recent call last):
  File "/home/am/env2/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 130, in run
    res = self._execute()
  File "/home/am/env2/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 528, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/am/env2/lib/python3.6/site-packages/ansible/plugins/action/telnet.py", line 57, in run
    tn.read_until(login_prompt)
  File "/usr/local/lib/python3.6/telnetlib.py", line 302, in read_until
    i = self.cookedq.find(match)
TypeError: a bytes-like object is required, not 'AnsibleUnicode'
fatal: [x.x.x.x]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
        to retry, use: --limit @/home/xxxx/test_cswt/telnet_test.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
x.x.x.x              : ok=0    changed=0    unreachable=0    failed=1   

```

**Comment by gundalow** [comment]
Not sure if you are aware though we have some great `ios_` modules that run over SSH that would be much better, http://docs.ansible.com/ansible/latest/ios_command_module.html

We've got some new Getting Started guide as part of Ansible 2.5 which can be found at http://docs.ansible.com/ansible/devel/network/

**Comment by horseinthesky** [comment]
I'm trying to use telnet module to do Zero Touch Provisioning for Juniper vRR and also get into this issue:
```
- name: Configure management interface via telnet
  telnet:
    port: 3517
    user: root
    pause: 1
    login_prompt: 'login: '
    prompts:
      - "[>|#]"
    command:
      - cli
      - edit
      - set system services ssh
      - set system root-authentication plain-text-password
      - Juniper
      - Juniper
      - set system services netconf rfc-compliant ssh port 830
      - set intermface em0 unit 0 familt inet address 192.168.0.111/24
      - commit
```

Result
```
The full traceback is:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/usr/local/lib/python3.6/dist-packages/ansible/executor/task_executor.py", line 576, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/local/lib/python3.6/dist-packages/ansible/plugins/action/telnet.py", line 58, in run
    tn.read_until(login_prompt)
  File "/usr/lib/python3.6/telnetlib.py", line 302, in read_until
    i = self.cookedq.find(match)
TypeError: a bytes-like object is required, not 'AnsibleUnicode'

fatal: [192.168.0.95]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
````

Ansible 2.6.0
Python 3.6.5
Ubuntu 18.04
