### ISSUE TITLE
Docs: Bad sysctl comment?

### ISSUE THREAD

**Issue by jamiejackson** [ansible/ansible#36197]
https://github.com/ansible/ansible/blob/2610b521bc1cc3578061be12bb20d33ae6f867b7/lib/ansible/modules/system/sysctl.py#L91

```yml
# Set kernel.panic to 3 in /tmp/test_sysctl.conf
- sysctl:
    name: kernel.panic
    value: 3
    sysctl_file: /tmp/test_sysctl.conf
    reload: no

# Set ip forwarding on in /proc and do not reload the sysctl file
- sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
```

Referring to the second task: It says "do not reload the sysctl file", but according to the docs `reload` defaults to `yes`.  Maybe "don't no reload the sysct file" was supposed to go in the first task's comment?
