### ISSUE TITLE
LD_LIBRARY_PATH can't be set using the environment keyword

### ISSUE THREAD

**Issue by ag0r** [ansible/ansible#36202]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

environment keyword
##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /Users/zthomas/ansible.cfg
  configured module search path = ['/Users/zthomas/gitRepos/ansible_tower/library/']
```

##### OS / ENVIRONMENT

OS X High Sierra

##### SUMMARY

Using the environment keyword does not allow setting the LD_LIBRARY_PATH environment variable.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: "{{ target_hosts }}"
  gather_facts: False
 
  vars:
    - target_hosts: 'localhost'
 
  tasks:
  - name: testy
    shell: env | grep -i lib
    environment:
      test_var: 'test'
      TEST_VAR_PATH: 'test'
      ld_library_path: /Users/zthomas/Downloads/instantclient_11_2/
      Ld_library_path: /Users/zthomas/Downloads/instantclient_11_2/
      LD_LIBRARY_PATH: /Users/zthomas/Downloads/instantclient_11_2/
      L_LIBRARY_PATH: /Users/zthomas/Downloads/instantclient_11_2/
      LD_LIBRAR_PATH: /Users/zthomas/Downloads/instantclient_11_2/
```

##### EXPECTED RESULTS

All variables set using environment keyword get set (including LD_LIBRARY_PATH)

##### ACTUAL RESULTS

```
TASK [testy] ************************************************************************************************************************
task path: /Users/rmccue/Desktop/Stash/ansible_tower/playbooks/test.yml:9
Using module file /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible/modules/commands/command.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: rmccue
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1518638843.07-243768356827584 `" && echo ansible-tmp-1518638843.07-243768356827584="` echo $HOME/.ansible/tmp/ansible-tmp-1518638843.07-243768356827584 `" ) && sleep 0'
<127.0.0.1> PUT /var/folders/rp/xnq_hb355qgb8kc3l4dj8gx92vppx_/T/tmpVz_Pxs TO /Users/rmccue/.ansible/tmp/ansible-tmp-1518638843.07-243768356827584/command.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/rmccue/.ansible/tmp/ansible-tmp-1518638843.07-243768356827584/ /Users/rmccue/.ansible/tmp/ansible-tmp-1518638843.07-243768356827584/command.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'ld_library_path=/Users/zthomas/Downloads/instantclient_11_2/ LD_LIBRARY_PATH=/Users/zthomas/Downloads/instantclient_11_2/ TEST_VAR_PATH=test test_var=test L_LIBRARY_PATH=/Users/zthomas/Downloads/instantclient_11_2/ LD_LIBRAR_PATH=/Users/zthomas/Downloads/instantclient_11_2/ Ld_library_path=/Users/zthomas/Downloads/instantclient_11_2/ /usr/local/Cellar/ansible/2.4.2.0_2/libexec/bin/python /Users/rmccue/.ansible/tmp/ansible-tmp-1518638843.07-243768356827584/command.py; rm -rf "/Users/rmccue/.ansible/tmp/ansible-tmp-1518638843.07-243768356827584/" > /dev/null 2>&1 && sleep 0'
changed: [localhost] => {
    "changed": true,
    "cmd": "env | grep -i lib",
    "delta": "0:00:00.008791",
    "end": "2018-02-14 14:07:23.211155",
    "invocation": {
        "module_args": {
            "_raw_params": "env | grep -i lib",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2018-02-14 14:07:23.202364",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "Ld_library_path=/Users/zthomas/Downloads/instantclient_11_2/\nJAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home\nLD_LIBRAR_PATH=/Users/zthomas/Downloads/instantclient_11_2/\nL_LIBRARY_PATH=/Users/zthomas/Downloads/instantclient_11_2/\nld_library_path=/Users/zthomas/Downloads/instantclient_11_2/",
    "stdout_lines": [
        "Ld_library_path=/Users/zthomas/Downloads/instantclient_11_2/",
        "JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_65.jdk/Contents/Home",
        "LD_LIBRAR_PATH=/Users/zthomas/Downloads/instantclient_11_2/",
        "L_LIBRARY_PATH=/Users/zthomas/Downloads/instantclient_11_2/",
        "ld_library_path=/Users/zthomas/Downloads/instantclient_11_2/"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
I've just done some digging here, and it seems that System Integrity Protection on macOS is responsible for this.

https://developer.apple.com/library/content/documentation/Security/Conceptual/System_Integrity_Protection_Guide/RuntimeProtections/RuntimeProtections.html

> When a process is started, the kernel checks to see whether the main executable is protected on disk or is signed with an special system entitlement
> ...
> Any dynamic linker (dyld) environment variables, such as DYLD_LIBRARY_PATH, are purged when launching protected processes.

This seems to include `LD_LIBRARY_PATH`.

If you were to install `bash` from homebrew, and then specify `executable=/usr/local/Cellar/bash/4.4.19/bin/bash` then `LD_LIBRARY_PATH` is available as expected:

```
---
- hosts: localhost
  gather_facts: False
  tasks:
    - shell: echo "LD_LIBRARY_PATH=${LD_LIBRARY_PATH}"
      args:
        executable: /usr/local/Cellar/bash/4.4.19/bin/bash
      environment:
        LD_LIBRARY_PATH: /Users/zthomas/Downloads/instantclient_11_2/
```

```
changed: [localhost] => {
    "changed": true,
    "cmd": "echo \"LD_LIBRARY_PATH=${LD_LIBRARY_PATH}\"",
    "delta": "0:00:00.005454",
    "end": "2018-02-14 14:44:37.111049",
    "failed": false,
    "invocation": {
        "module_args": {
            "_raw_params": "echo \"LD_LIBRARY_PATH=${LD_LIBRARY_PATH}\"",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": "/usr/local/Cellar/bash/4.4.19/bin/bash",
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "rc": 0,
    "start": "2018-02-14 14:44:37.105595",
    "stderr": "",
    "stderr_lines": [],
    "stdout": "LD_LIBRARY_PATH=/Users/zthomas/Downloads/instantclient_11_2/",
    "stdout_lines": [
        "LD_LIBRARY_PATH=/Users/zthomas/Downloads/instantclient_11_2/"
    ]
}
```

The other option is disabling System Integrity Protection.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
