### ISSUE TITLE
azure_rm_virtualmachine fails with DeserializationError

### ISSUE THREAD

**Issue by jigarjian-brian** [ansible/ansible#36206]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/anuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

Azure Components:

azure==2.0.0
azure-batch==3.0.0
azure-cli-core==2.0.24
azure-cli-nspkg==3.0.1
azure-common==1.1.8
azure-datalake-store==0.0.17
azure-graphrbac==0.30.0
azure-keyvault==0.3.7
azure-mgmt==1.0.0
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==4.1.0
azure-mgmt-cdn==0.30.3
azure-mgmt-cognitiveservices==1.0.0
azure-mgmt-compute==2.1.0
azure-mgmt-containerregistry==0.2.1
azure-mgmt-containerservice==1.0.0
azure-mgmt-datalake-analytics==0.1.6
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.1.6
azure-mgmt-devtestlabs==2.0.0
azure-mgmt-dns==1.2.0
azure-mgmt-documentdb==0.1.3
azure-mgmt-iothub==0.2.2
azure-mgmt-keyvault==0.40.0
azure-mgmt-logic==2.1.0
azure-mgmt-monitor==0.2.1
azure-mgmt-network==1.7.1
azure-mgmt-nspkg==2.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-redis==4.1.1
azure-mgmt-resource==1.2.2
azure-mgmt-scheduler==1.1.3
azure-mgmt-sql==0.7.1
azure-mgmt-storage==1.5.0
azure-mgmt-trafficmanager==0.30.0
azure-mgmt-web==0.32.0
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==5.6.130
azure-servicemanagement-legacy==0.20.6
azure-storage==0.35.1
msrestazure==0.4.20

##### OS / ENVIRONMENT

RHEL 7.4

##### SUMMARY
Trying to boot a vm in azure using the azure_rm_virtualmachine module, but am getting the following error when trying to boot this particular vm. 

Error creating or updating virtual machine clappetlavm001 - Unable to build a model: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get'"

We are seeing this error with a couple of vms, but not all vms. We are seeing this on both linux and windows vms and have been able to successfully boot windows and linux vms using the same playbook. The resource group and vm name are correct.

##### STEPS TO REPRODUCE

This is my playbook.
```yaml
---
- name: Test
  hosts: localhost
  connection: local
  tasks:

  - name: Power On if boot is on
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
    when: boot == true
```

##### EXPECTED RESULTS
VM in azure is expected to start. 

##### ACTUAL RESULTS
Full output of the error
```
{
    "_ansible_parsed": true,
    "exception": "  File \"/tmp/ansible_U5QWrH/ansible_module_azure_rm_virtualmachine.py\", line 1353, in create_or_update_vm\n    poller = self.compute_client.virtual_machines.create_or_update(self.resource_group, self.name, params)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/azure/mgmt/compute/compute/v2017_03_30/operations/virtual_machines_operations.py\", line 186, in create_or_update\n    body_content = self._serialize.body(parameters, 'VirtualMachine')\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrest/serialization.py\", line 469, in body\n    SerializationError, \"Unable to build a model: \"+str(err), err)\n  File \"/var/lib/awx/venv/ansible/lib/python2.7/site-packages/msrest/exceptions.py\", line 48, in raise_with_traceback\n    raise error\n",
    "_ansible_no_log": false,
    "changed": false,
    "invocation": {
        "module_args": {
            "virtual_network_resource_group": null,
            "resource_group": "resourcegroupname",
            "public_ip_allocation_method": "Static",
            "image": null,
            "managed_disk_type": null,
            "ssh_public_keys": null,
            "storage_container_name": "vhds",
            "allocated": true,
            "ssh_password_enabled": true,
            "storage_blob_name": null,
            "remove_on_absent": [
                "all"
            ],
            "append_tags": true,
            "cloud_environment": null,
            "secret": null,
            "short_hostname": null,
            "started": true,
            "state": "present",
            "subnet_name": null,
            "location": null,
            "network_interface_names": null,
            "subscription_id": null,
            "admin_password": null,
            "profile": null,
            "cli_default_profile": null,
            "tags": null,
            "virtual_network_name": null,
            "open_ports": null,
            "client_id": null,
            "vm_size": null,
            "password": null,
            "tenant": null,
            "name": "clappetlavm001",
            "ad_user": null,
            "restarted": false,
            "admin_username": null,
            "os_type": "Linux",
            "storage_account_name": null,
            "data_disks": null,
            "os_disk_caching": "ReadOnly"
        }
    },
    "msg": "Error creating or updating virtual machine clappetlavm001 - Unable to build a model: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'unicode' object has no attribute 'get'"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by kyliel** [comment]
@zikalino , could you please take a look? Thanks.

**Comment by kyliel** [comment]
@jigarjian-brian double confirm. Do you mean you could get some VMs boot up with the same playbook and some failed? Thanks.

**Comment by zikalino** [comment]
@jigarjian-brian i am going to try to reproduce this. in a meanwhile quick question: how was this vm created in first place?

**Comment by zikalino** [comment]
i have tried to reproduce this, and it works for me:
- created standard Ubuntu VM
- stopped VM
- tried your playbook
- VM powered up

That suggests there must be some difference in case of VMs which are failing. Are you able how these machines differ from successful ones?

**Comment by jigarjian-brian** [comment]
Yes we are able to use this same playbook to start and stop other vms. The vms that we are able to start and stop seem to be ones that have been created through ansible or through the Azure portal recently. This particular vm was actually created manually, but is approximately 1.5 years old which is why I am tentative to say that all vms created manually through the portal work. 

The vms that fail are ones that have been created through another automation platform. I believe I have found the difference between the calls from each platform to azure for various commands (start, stop, provision, etc). The difference is in the "aud" field under claims in the json of the activity log for successful jobs. 
For successful jobs from sensible this is the audience field. 

"claims": {
        "aud": "https://management.core.windows.net/",

For successful jobs from the other automation platform the field is as follows:

    "claims": {
        "aud": "https://management.azure.com/",

After a quick search I found that "Azure Resource Manager provider APIs use https://management.azure.com/, and Azure classic deployment model uses https://management.core.windows.net/". So it seems to me that the issue we are running into is that ansible is using the classic api instead of the arm api for some reason.

**Comment by ghoelzer-aws** [comment]
I just came across the same issue testing the new Ansible integration with the Azure Cloud Shell using the simple playbook below:
```
#Ansible Automation Script to start Bastion VM
- hosts: localhost
  tasks:
  - name: Power On
    azure_rm_virtualmachine:
      resource_group: redhatocpdemo
      name: ocpcluster-bastion
```
I'm an App Dev Solutions Specialist on the MS Azure team, and would really like to start promoting Ansible, as I'm a big fan from my time at Red Hat.  The sooner this can be corrected the better, as we are really starting to promote our Open Source partnerships, as demonstrated by including Ansible as part of the Azure Cloud Shell.

**Comment by jigarjian-brian** [comment]
There is an issue from a few months ago that has a similar error message although not exactly the same. 

https://github.com/Azure/msrest-for-python/issues/75

It seems that this issue was resolved by using a newer version of msrest (0.4.23). However, we are currently using version 0.4.25 so this might not be the issue in our case.

**Comment by zikalino** [comment]
@jigarjian-brian i don't think it's the same issue. I have still failed to reproduce this issue, but i think we should get to bottom of that. In my next comment I will paste a playbook that uses REST API directly to power up / down virtual machine. Could you try it with your VMs? If it fails we will see more details why it failed.

**Comment by zikalino** [comment]
```
---
- name: Stop / Start virtual machine using REST API
  hosts: localhost
  connection: local
  vars:
    resource_group: zimsdemorg
    vm_name: zimstestvm
  tasks:

  - name: Authorization
    uri:
      url: https://login.windows.net/{{ lookup('env','AZURE_TENANT') }}/oauth2/token
      method: POST
      body: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id={{ lookup('env','AZURE_CLIENT_ID') }}&grant_type=client_credentials&client_secret={{ lookup('env','AZURE_SECRET') }}
      return_content: yes
      headers:
        Content-Type: application/x-www-form-urlencoded
    register: authresp

  - name: Power up Virtual Machine
    uri:
      method: POST
      url: https://management.azure.com/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/virtualMachines/{{ vm_name }}/start?api-version=2017-12-01
      headers:
        Authorization: "Bearer {{ authresp.json.access_token }}"
      status_code: 200,202
    register: output

  - name: Output from powering up VM
    debug:
      msg: "{{ output }}"

  - name: Power off Virtual Machine
    uri:
      method: POST
      url: https://management.azure.com/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Compute/virtualMachines/{{ vm_name }}/powerOff?api-version=2017-12-01
      headers:
        Authorization: "Bearer {{ authresp.json.access_token }}"
      status_code: 200,202
    register: output

  - name: Output from powering down VM
    debug:
      msg: "{{ output }}"
```

**Comment by zikalino** [comment]
Ok, I think i have finally managed to reproduce this issue:

- I have created Classic VM using Azure Portal
- then used playbook above and it failed with following error:

{"code": "ResourceNotFound", "message": "The Resource 'Microsoft.Compute/virtualMachines/classdepmod' under resource group 'zimsdemorg' was not found."}

I have checked VM properties and resource id:

/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/zimsdemorg/providers/Microsoft.ClassicCompute/virtualMachines/classdepmod

Note that provider in resource id is **ClassicCompute**, not **Compute**

Then I have tried to change URL and replace Compute with ClassicCompute, got following error:

{"code": "NoRegisteredProviderFound", "message": "No registered resource provider found for location 'eastus' and API version '2017-12-01' for type 'virtualMachines'. The supported api-versions are '2014-01-01, 2014-04-01, 2014-06-01, 2015-06-01, 2015-10-01, 2015-12-01, 2016-04-01, 2016-11-01, 2017-04-01'

**Comment by zikalino** [comment]
Finally I had to change URL to:

      url: https://management.azure.com/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.ClassicCompute/virtualMachines/{{ vm_name }}/start?api-version=2017-04-01

It required changing:
  Microsoft.Compute --> Microsoft.ClassicCompute
  api-version=2017-12-01 --> api-version=2017-04-01

After this change i was able to "start" VM, but "powerOff" was not available (got 404 error) -- i will dig deeper here.

**Comment by zikalino** [comment]
seems like "powerOff" is not available in API for classic deployment, instead i had to use "start"

**Comment by zikalino** [comment]
Below is the playbook I used to successfully start/stop VM in deployed in classic mode. I think this can be used as a workaround for classic VMs.

I have checked Azure Python SDK and it doesn't provide any support for classic VMs. I have searched for "ClassicCompute", found a few references, but not related to VM implementation. So it seems adding support for classic VM is not possible at the moment without introducing serious hacks.

@jigarjian-brian  Please let me know if the workaround works for you and if it's ok to close this issue.

```
---
- name: Stop / Start virtual machine using REST API (Classic deployment)
  hosts: localhost
  connection: local
  vars:
    resource_group: zimsdemorg
    vm_name: classdepmod
  tasks:

  - name: Authorization
    uri:
      url: https://login.windows.net/{{ lookup('env','AZURE_TENANT') }}/oauth2/token
      method: POST
      body: resource=https%3A%2F%2Fmanagement.core.windows.net%2F&client_id={{ lookup('env','AZURE_CLIENT_ID') }}&grant_type=client_credentials&client_secret={{ lookup('env','AZURE_SECRET') }}
      return_content: yes
      headers:
        Content-Type: application/x-www-form-urlencoded
    register: authresp

  - name: Power on Virtual Machine
    uri:
      method: POST
      url: https://management.azure.com/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.ClassicCompute/virtualMachines/{{ vm_name }}/start?api-version=2017-04-01
      headers:
        Authorization: "Bearer {{ authresp.json.access_token }}"
      status_code: 200,202
    register: output

  - name: Power off Virtual Machine
    uri:
      method: POST
      url: https://management.azure.com/subscriptions/{{ lookup('env','AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.ClassicCompute/virtualMachines/{{ vm_name }}/stop?api-version=2017-04-01
      headers:
        Authorization: "Bearer {{ authresp.json.access_token }}"
      status_code: 200,202
    register: output
```
