### ISSUE TITLE
group_by broken (?)

### ISSUE THREAD

**Issue by oheinz** [ansible/ansible#3620]
Current version from git revision e3f213e030556706c0735a72804c1e915614567b  seems to break (at least) group_by module.

The docs group_by example at http://www.ansibleworks.com/docs/bestpractices.html gives the following output on an Ubuntu 12.04 system:

root@ansible:~/ansible/playbooks# ansible-playbook -l localhost -i hosts playbooks/test.yml 

PLAY [all] *******************************************************************\* 

GATHERING FACTS **************************************************************\* 
ok: [localhost]

TASK: [group_by key=${ansible_distribution}] *********************************\* 
fatal: [localhost] => Conditional expression must evaluate to True or False: playbooks

FATAL: all hosts have already failed -- aborting

PLAY RECAP *******************************************************************\* 
           to retry, use: --limit @/var/tmp/ansible/test.retry

localhost                  : ok=1    changed=0    unreachable=0    failed=1  

btw: Changing it to the new syntax
      - group_by: key="{{ ansible_distribution }}"
still gives the same error.

TIA,
Oliver

**Comment by mpdehaan** [comment]
I don't think it's that particular revision, but I am happy to reproduce your test.

Can you paste the exact playbook you are using?  I'm curious how "playbooks" got in there.

Thanks!

**Comment by oheinz** [comment]
```
root@ansible:~/ansible/playbooks# cat playbooks/test.yml 
---
# talk to all hosts just so we can learn about them

- hosts: all
  tasks:
     - group_by: key="{{ ansible_distribution }}"

# now just on the CentOS hosts...

- hosts: CentOS
  gather_facts: False
  tasks:
     - name: sample task
       action: debug msg="{{ ansible_hostname }}"
```
