### ISSUE TITLE
wait_for does not catch exception thrown by socket.recv

### ISSUE THREAD

**Issue by jannsuom** [ansible/ansible#36223]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
wait_for

##### ANSIBLE VERSION
ansible 2.3.0.0

##### CONFIGURATION
Vanilla

##### OS / ENVIRONMENT
CentOS Linux release 7.3

##### SUMMARY
When using wait_for if socket dies during the socket.recv it will throw socket.error exception failing the module.
This is an occasional problem. The workaround is to use register, until, and retries. 

##### STEPS TO REPRODUCE
```
- name: Test connection
  hosts: localhost
  pre_tasks:
      - set_fact:
            conn_details: "{{ [{'node_name': 'node', 'node_ip': '192.168.0.23'}]}}"
      - name: waiting
        wait_for:
            host: "{{ item.node_ip }}"
            port: 22
            search_regex: OpenSSH
            sleep: 5
            timeout: 600
        with_items: "{{ conn_details }}"
```

##### EXPECTED RESULTS
Retry until the connection is successful or fail with timeout if no connection

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.error: [Errno 104] Connection reset by peer
failed: [localhost] (item={'node_name': u'node, 'node_ip': [u'192.168.0.23']}) => {"failed": true, "item": {"node_ip": ["192.168.0.23"], "node_name": "node"}, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_PUqxyp/ansible_module_wait_for.py\", line 585, in <module>\n    main()\n  File \"/tmp/ansible_PUqxyp/ansible_module_wait_for.py\", line 525, in main\n    response = s.recv(1024)\nsocket.error: [Errno 104] Connection reset by peer\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
