### ISSUE TITLE
Allow shell args removes to support lists

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#36298]
##### ISSUE TYPE

- Feature Request
~~- Bug  Report~~
##### COMPONENT NAME
shell

##### ANSIBLE VERSION

```
2.4.3.0
```

##### OS / ENVIRONMENT
NA

##### SUMMARY
It seems that shell module fails to correctly evaluate the removes parameter when this one is either a list or a glob pattern, it always evaluates it a single string.

This behaviour introduces bugs and the workarounds are ugly.

##### STEPS TO REPRODUCE

```yaml
shell: echo "yep!"
  args:
    removes: 
    - "/tmp"
    - "/home"
```

##### EXPECTED RESULTS

Run the task because at least one of these files exists.

##### ACTUAL RESULTS

```
skipped, since ['/tmp', '/home'] does not exist
```
