### ISSUE TITLE
force_handlers does not work when max_fail_percentage or any_errors_fatal is set

### ISSUE THREAD

**Issue by nerlion** [ansible/ansible#36308]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

force_handlers
##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ans/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles', u'/home/ans/ansgit/build/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.3
##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  become: yes
  gather_facts: yes
  become_user: root
  any_errors_fatal: true
  become_method: sudo
  force_handlers: True

  tasks:
  - shell: "echo TEST"
    notify:
    - handl
  - fail:
      msg: "TEST fail"
  - shell: "echo TEST"

  handlers:
  - name: handl
    shell: "echo TTTT"
```

##### EXPECTED RESULTS

TASK [fail] *********************************************************************************************************************************************************************
fatal: [kserver3]: FAILED! => {"changed": false, "msg": "TEST fail"}

RUNNING HANDLER [handl] *********************************************************************************************************************************************************
changed: [kserver3]
        to retry, use: --limit @/home/ans/ansgit/pb/test1.retry

PLAY RECAP
.....
##### ACTUAL RESULTS

```
TASK [fail] *********************************************************************************************************************************************************************
fatal: [kserver3]: FAILED! => {"changed": false, "msg": "TEST fail"}

NO MORE HOSTS LEFT **************************************************************************************************************************************************************
        to retry, use: --limit @/home/ans/ansgit/pb/test1.retry

PLAY RECAP
```
