### ISSUE TITLE
xml module: add an option to manage the xml declaration

### ISSUE THREAD

**Issue by miniwark** [ansible/ansible#36305]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
- xml module

##### ANSIBLE VERSION
```
2.4.3.0
```

##### CONFIGURATION
```
DEFAULT_ASK_PASS(/home/miniwark/Documents/Developpement/Ansible-playbooks/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/miniwark/Documents/Developpement/Ansible-playbooks/ansible.cfg) = [u'/home/miniwark/Documents/Developpement/Ansible-playbooks/hosts']
```
##### OS / ENVIRONMENT
- From: Ubuntu 16.04
- Manage: Debian 9.2

##### SUMMARY
By default the xml module add the XML declaration line at the top of the managed file if this line is missing. This is probably a default behavior inherited from the `lxml` Python module.
The default added line is:
```xml
<?xml version='1.0' encoding='UTF-8'?>
```
This behavior is the recommended one for XML files, but may not bode well with legacy applications. 

In my case, i also use the xml module to manage .jnlp files (witch are a XML variant used by some Java web apps), but my legacy Java apps do not like the presence of the XML declaration on top of the .jnlp files. 

Some people mays also need to set another character encoding.

The proposal is to add an option (or `tostring` args) to the xml module to :
-  tell to NOT add (or to remove) the XML declaration line
-  choice the character encoding
- set standalone to "yes"

The `lxml` Python module seem to have a  way to do all this with `etree.tostring()`. 
For example:
```python
etree.tostring(xml_declaration = False, encoding='UTF-16', standalone="yes")
```

##### STEPS TO REPRODUCE
This is the actual default behavior.

```yaml
- name: Set foo in /opt/myapp/myapp.jnlp
  xml:
    path: /opt/myapp/myapp.jnlp
    xpath: /jnlp
    attribute: foo
    value: bar
```
Will add the XML declaration line to any file without it, if the task is performed.

My actual workaround with the `lineinfile` module after the previous task:
```yaml
- name: Remove the xml declaration in /opt/myapp/myapp.jnlp
  lineinfile:
    dest: /opt/myapp/myapp.jnlp
    regexp: "^<[?]xml .*[?]>"
    state:  absent
```
