### ISSUE TITLE
os_server_group module fails

### ISSUE THREAD

**Issue by tux-84** [ansible/ansible#36301]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

os_server_group

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]

```

##### OS / ENVIRONMENT

Running playbook on: Linux 3.16.0-77-generic #99~14.04.1-Ubuntu
Module running on: Linux 4.4.0-112-generic #135-Ubuntu
##### SUMMARY

When running a playbook for creating a server-group using anti-affinity policy in an openstack enviroment, the module fails.

##### STEPS TO REPRODUCE

Running playbook

```yaml
  - name: setting Cloud connection variables
    set_fact:
      cloud_ssh_key: "{{ lookup('env','OS_SSH_KEY') }}"
      openstack_auth:
        auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
        username: "{{ lookup('env','OS_USERNAME') }}"
        password: "{{ lookup('env','OS_PASSWORD') }}"
        project_name: "{{ lookup('env','OS_TENANT_NAME') }}"

- name: Creating server group ag_cl17fwp01
    os_server_group:
      state: present
      auth: "{{ openstack_auth }}"
      name: mygroup01
      policies:
        - anti-affinity
    register: servergroup

```

##### EXPECTED RESULTS
new server group with anti-affinity policy called "mygroup01"

##### ACTUAL RESULTS

The described error appears during execution of the playbook.

```
fatal: [jumphost]: FAILED! => {
    "changed": false,
    "module_stderr": "Connection to jumphost closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_rCvm5U/ansible_module_os_server_group.py\", line 190, in <module>\r\n    main()\r\n  File \"/tmp/ansible_rCvm5U/ansible_module_os_server_group.py\", line 153, in main\r\n    server_group = cloud.get_server_group(name)\r\nAttributeError: 'OpenStackCloud' object has no attribute 'get_server_group'\r\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```
