### ISSUE TITLE
Feature Request: ec2_vpc_route_table creating a nat_gateway_id: nat-gw field in routes similar to gateway_id: igw

### ISSUE THREAD

**Issue by thalesac** [ansible/ansible#36324]
##### ISSUE TYPE

 - Feature Idea
##### COMPONENT NAME

ec2_vpc_route_table 

##### SUMMARY

Currently we have a convenient way for setting up a route to `0.0.0.0/0` and pointing to the default VPC internet gateway like:
```
- name: Set up route tables for environment vpc
  ec2_vpc_route_table:
    vpc_id: vpc-id
    region: "us-east-1"
    route_table_id: "rt1-"
    lookup: id
    routes:
      - dest: 0.0.0.0/0
        gateway_id: igw
```
You can find the relevant code that search for the igw at 
https://github.com/ansible/ansible/blob/fd33dc6cd124d4c3e2fa8d0bed02b8379cf7e8b8/lib/ansible/modules/cloud/amazon/ec2_vpc_route_table.py#L305

My proposal is to have a similar code, but for NAT Gateways instead. Currently the documentation states this options but it doesn't work.

##### EXPECTED RESULTS

something like:
```
    routes:
      - dest: 0.0.0.0/0
        nat_gateway_id: nat-gw

```
