### ISSUE TITLE
AWS Cloud EFS module creates additional instances even if ID is specified

### ISSUE THREAD

**Issue by jwitko** [ansible/ansible#36321]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
efs

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /home/jwitkowski/throtle-ansible/ansible.cfg
  configured module search path = [u'/home/jwitkowski/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jwitkowski/throtle-ansible-venv/lib/python2.7/site-packages/ansible
  executable location = /home/jwitkowski/throtle-ansible-venv/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/jwitkowski/throtle-ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/jwitkowski/throtle-ansible/ansible.cfg) = -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o ForwardAgent=yes
DEFAULT_CALLBACK_PLUGIN_PATH(/home/jwitkowski/throtle-ansible/ansible.cfg) = [u'/home/jwitkowski/throtle-ansible/library/callback']
DEFAULT_FILTER_PLUGIN_PATH(/home/jwitkowski/throtle-ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/filter_plugins', u'/home/jwitkowski/throtle-ansible/library/plugins']
DEFAULT_FORKS(/home/jwitkowski/throtle-ansible/ansible.cfg) = 15
DEFAULT_GATHERING(/home/jwitkowski/throtle-ansible/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/home/jwitkowski/throtle-ansible/ansible.cfg) = !hardware,!ohai,!facter
DEFAULT_HOST_LIST(/home/jwitkowski/throtle-ansible/ansible.cfg) = [u'/home/jwitkowski/throtle-ansible/inventory']
DEFAULT_MANAGED_STR(/home/jwitkowski/throtle-ansible/ansible.cfg) = Created by Ansible
DEFAULT_PRIVATE_KEY_FILE(/home/jwitkowski/throtle-ansible/ansible.cfg) = /home/jwitkowski/.ssh/throtle-ansible.key
DEFAULT_REMOTE_TMP(/home/jwitkowski/throtle-ansible/ansible.cfg) = /tmp/ansible-$USER/tmp
DEFAULT_ROLES_PATH(/home/jwitkowski/throtle-ansible/ansible.cfg) = [u'/home/jwitkowski/throtle-ansible/roles']
DEFAULT_SCP_IF_SSH(/home/jwitkowski/throtle-ansible/ansible.cfg) = True
DEFAULT_VAULT_PASSWORD_FILE(/home/jwitkowski/throtle-ansible/ansible.cfg) = /home/jwitkowski/throtle-ansible/.vault
DISPLAY_ARGS_TO_STDOUT(/home/jwitkowski/throtle-ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/jwitkowski/throtle-ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/jwitkowski/throtle-ansible/ansible.cfg) = /home/jwitkowski/.ansible/retry-files
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When creating EFS instances the EFS module seems to be going exclusively on the `creation_token` fact, comparing it to the `name` parameter in the EFS module.  If I have an EFS instance that exists already and I specify a non-identical name but I also specify an instance ID, the module will create a new EFS instance ignoring the instance ID specified with a `creation_token` value of the `name` parameter.

##### STEPS TO REPRODUCE
```yaml
- name: EFS | Get EFS facts
  efs_facts:
    tags:
      name: "{{ region }}-{{ deploy_env }}-{{ efs_name|default(service) }}"
      purpose: "{{ service }}"
      deploy_env: "{{ deploy_env }}"
      vpc: "{{ vpc_id }}"
  register: efsfacts

- name: EFS | Confirm single EFS has been found
  fail:
    msg: "Multiple matching EFS instances found.  Please investigate!"
  when: efsfacts.ansible_facts.efs|length > 1

- name: EFS | Create EFS Instance
  run_once: True
  efs:
    state: present
    name: "{{ region }}-{{ efs_name|default(service) }}"
    id: "{{ efsfacts.ansible_facts.efs[0].file_system_id }}"
    wait: yes
    tags:
        name: "{{ region }}-{{ deploy_env }}-{{ efs_name|default(service) }}"
        purpose: "{{ service }}"
        deploy_env: "{{ deploy_env }}"
        vpc: "{{ vpc_id }}"
    targets: "{{ lookup('template', 'efs_targets.yml.j2') | from_yaml }}"
  register: ec2_efs
```
The above should give a clear enough idea of what I'm doing and why different behavior is expected.  If it does not then please let me know what else I can provide.

##### EXPECTED RESULTS
I expected that it would apply new tags to the instance ID specified if they did not already exist and would simply return OK/green if everything was as expected.  I don't believe the `name:` parameter (note: not the name Tag) can be modified once the EFS instance is created so I'm not sure how that would be handled if a new name was specified but an existing instance ID.

##### ACTUAL RESULTS
A new EFS instance is created instead of modifying the instance ID provided.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/efs.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/efs.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akazakov @ryansydnor @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by julienvey** [comment]
Ansible's behaviour is actually quite consistent with [AWS documentation](https://docs.aws.amazon.com/efs/latest/ug/API_CreateFileSystem.html)

> * CreationToken 
String of up to 64 ASCII characters. Amazon EFS uses this to ensure **idempotent** creation.

So it seems logical ansible also makes use of this parameter to update an EFS (Not really sure what is the point from the AWS side to have both `creation_token` and `file_system_id`)

In your case what you can do is use the `creation_token` instead of the id when you want to update the stack

```yaml
- name: EFS | Create EFS Instance
    efs:
      state: present
      name: "{{ efsfacts.ansible_facts.efs[0].creation_token }}"
      wait: yes
      tags:
        name: "test-env-name"
```

However, the module documentation should clearly say the `name` attribute is required for update. I'll send a proposal for this
