### ISSUE TITLE
ec2 instance_tags entry mechanism is suboptimal

### ISSUE THREAD

**Issue by mpdehaan** [ansible/ansible#3635]
Instance tags have to be specified in JSON, which is hard for lots of folks.

We should be able to pass them via complex args and recognize if the data type is a dictionary, and then update the examples to support the JSON way or the new way.

Furthermore, we should probably support a simple key=value mode as well if it were a string.

**Comment by ches** [comment]
Totally agree, the boto `create_tags` method simply takes a dict so it was frustrating to have to come up with gymnastics like:

``` yaml
vars:
  instance_tags:
    Environment: staging
    App: foo-app

tasks:
  - name: Launch instances
    delegate_to: localhost
    ec2: >
      instance_tags='{{ instance_tags|to_json }}'
      # etc.
    register: ec2
```

when I would expect `instance_tags={{ instance_tags }}` to DWIM, and as you mention, it'd be convenient if complex args were an option instead. I'll try to take a stab at this.

I saw [this thread](https://groups.google.com/forum/#!topic/ansible-project/YYVvCqg5ydM) -- can start with a naive `startswith('{')` for distinguishing the old JSON way from `"key=value"` and go from there if there are any foreseen issues. Are there any other modules that accept such "nested" key=value configuration that I might refer to?
