### ISSUE TITLE
uri module should skip task when precondition are not met

### ISSUE THREAD

**Issue by oupala** [ansible/ansible#36353]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

uri

##### ANSIBLE VERSION

```
ansible 2.2.1.0
```

##### CONFIGURATION

nothing specific

##### OS / ENVIRONMENT

from debian (stretch) to raspbian (jessie), but should not be platform-specific

##### SUMMARY

I'm trying to call an url, and I want to call the url only if a file does not exists (because calling the url creates the file, and the call should only happen once).

When the file exists, the tasj is executed, and displayed as **ok**, while internal debug shows that the task has been skipped. The behavior is consistent, but the status displayed is not consistent with the real action.

##### STEPS TO REPRODUCE

```yaml
- name: delete file test-200
  file:
    path: /home/user/test-200
    state: absent

- name: test 200 call 1
  uri:
    url: https://httpstat.us/200
    creates: /home/user/test-200

- name: create file test-200
  file:
    path: /home/user/test-200
    state: touch

- name: test 200 call 2
  uri:
    url: https://httpstat.us/200
    creates: /home/user/test-200
```

##### EXPECTED RESULTS

- `call 1` should be a real call with `ok` status for a successful read method/verb: **get**, **head**, **options**, **trace**
- `call 1` should be a real call with `changed` status for a successful write method/verb: **put**, **post**, **delete**, **patch**
- `call 2` should be skipped, and displayed as `skipped`

##### ACTUAL RESULTS

- `call 1` is executed, and status is always `ok` even if the call changed anything...
- `call 2` is displayed as ok, but internal result shows that the task has internally been skipped

```
TASK [test-uri-module : test 200] **********************************************
task path: /home/user/.../test-uri-module/tasks/main.yml:26
Saturday 17 February 2018  19:20:45 +0100 (0:00:02.344)       0:00:23.589 ***** 
ok: [hostname => {"changed": false, "rc": 0, "stderr": false, "stdout": "skipped, since /home/user/test-200 exists", "stdout_lines": ["skipped, since /home/user/test-200 exists"]}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/uri.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/uri.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @romeotheriault
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
This is working as expected.  All modules that accept a `creates` argument, return `ok` rather than `skipped`.

This is for the same reason that creating a file, doesn't say `skipped` on the 2nd execution.  That is due to the fact that the desired state has been validated to exist.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by oupala** [comment]
If this is normal, this causes another problem.

```yaml
- name: create file test-200
  file:
    path: /home/user/test-200
    state: touch

- name: test 200 that should be skipped
  uri:
    url: https://httpstat.us/200
    creates: /home/user/test-200
  register: callResp
  changed_when: callResp.status == 200
```

If the task is skipped, it has no `status` and hence the `changed_when` condition cannot be evaluated:

```log
TASK [test-uri-module : create file test-200] **********************************
Monday 19 February 2018  21:14:54 +0100 (0:00:02.420)       0:00:07.605 ******* 
changed: [hostname]

TASK [test-uri-module : test 200 call that should be skipped] ***********************
Monday 19 February 2018  21:14:57 +0100 (0:00:02.296)       0:00:09.902 ******* 
fatal: [hostname]: FAILED! => {"failed": true, "msg": "The conditional check 'callResp.status == 200' failed. The error was: error while evaluating conditional (callResp.status == 200): 'dict object' has no attribute 'status'"}
```

Does anyone see a way to fix this bug?

And please tell me if I need to open a new issue.

**Comment by sivel** [comment]
`changed_when: callResp.status|default(0) == 200`

**Comment by oupala** [comment]
This does not mark the task as `changed` but as `ok`:

```log
TASK [test-uri-module : test 200 that should be skipped] ***********************
Monday 19 February 2018  21:59:11 +0100 (0:00:02.443)       0:00:07.540 ******* 
ok: [hostname]
```

**Comment by sivel** [comment]
That change marks the status with a default of `0`.  So if it did nothing, no request was made, so it is set as `status=0`.

It will only report `changed` in the case that the request was actually made, and the status was set as `200`.

In your example, the file is being created via the file module immediately before, so it never has to make the request, and thus would never report as changed.

**Comment by oupala** [comment]
You're completely right, thank you @sivel.

Here is a complete test case for archiving purposes:

```yaml
- name: delete file test-200
  file:
    path: /home/user/test-200
    state: absent

- name: test 200 that should be executed
  uri:
    url: https://httpstat.us/200
    creates: /home/user/test-200
  register: callResp1
  changed_when: callResp1.status|default(0) == 200

- name: create file test-200
  file:
    path: /home/user/test-200
    state: touch

- name: test 200 that should be skipped
  uri:
    url: https://httpstat.us/200
    creates: /home/user/test-200
  register: callResp2
  changed_when: callResp2.status|default(0) == 200
```

And here are the executions logs:

```log
TASK [test-uri-module : delete file test-200] **********************************
Monday 19 February 2018  22:28:17 +0100 (0:00:05.086)       0:00:05.128 ******* 
changed: [hostname]

TASK [test-uri-module : test 200 that should be executed] **********************
Monday 19 February 2018  22:28:19 +0100 (0:00:02.459)       0:00:07.588 ******* 
changed: [hostname]

TASK [test-uri-module : create file test-200] **********************************
Monday 19 February 2018  22:28:32 +0100 (0:00:12.681)       0:00:20.269 ******* 
changed: [hostname]

TASK [test-uri-module : test 200 that should be skipped] ***********************
Monday 19 February 2018  22:28:34 +0100 (0:00:02.277)       0:00:22.547 ******* 
ok: [hostname]
```

As you can see, the first api call is `changed` while the second one is `ok`.
