### ISSUE TITLE
Add mindepth, maxdepth parameters to find module

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#36369]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
find

##### ANSIBLE VERSION

```
ansible 2.4.3.0
```
##### SUMMARY
It would be nice if find module had parameters `mindepth` and `maxdepth`, behaving like the ones in `find` command from findutils.

##### STEPS TO REPRODUCE
```yaml
- name: Find /var/log first level sub-directories not including the directory itself
- find:
    paths: /var/log
    file_type: directory
    mindepth: 1
    maxdepth: 1
```

##### EXPECTED RESULTS
Get all `/var/log` level 1 sub-directories, not including the directory itself.
