### ISSUE TITLE
RHEL reboot & Playbook Pause

### ISSUE THREAD

**Issue by pratikkava1189** [ansible/ansible#36382]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Reboot & Pause

##### ANSIBLE VERSION
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

##### CONFIGURATION
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
Red Hat Enterprise Linux v7.4

##### SUMMARY
We are trying to reboot the machine and pausing the ansible playbook, but after executing of reboot, playbook immediately exits without executing "pause"

##### STEPS TO REPRODUCE
```yaml
---
- hosts: linuxtest

  vars_prompt:
   - name: "confirmation"
     prompt: "Are you sure want to reboot the machine?"
     private: no
  tasks:

# This task will reboot machine only if we give "yes" #
  - name: Rebooting the machine
    command: /sbin/shutdown -r now
    when: confirmation=="yes"

# This pause is mandatory, otherwise the existing control connection gets reused #
  - pause: seconds=60

# It will try to ping server after 60 seconds and tries 30 times untill server gets up #
  - local_action: shell ansible -m ping puppettest
    register: result
    until: result.rc==0
    retries: 30
    delay: 10

# This will check the uptime of server after reboot #
  - shell: uptime
```
##### EXPECTED RESULTS
Playbook should paused after executing reboot. It was working fine in earlier version but somehow its not working in this current version.

##### ACTUAL RESULTS
```
SSH password:
Are you sure want to reboot the machine?: yes

PLAY [linuxtest] *******************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [puppettest]

TASK [Rebooting the machine] *******************************************************************************************************************************************
fatal: [puppettest]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to puppettest closed.\r\n", "unreachable": true}
        to retry, use: --limit @/home/mansukhl/playbooks/patching/reboot.retry

PLAY RECAP *************************************************************************************************************************************************************
puppettest  : ok=1    changed=0    unreachable=1    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/pause.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/pause.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pratikkava1189** [comment]
@Akasurde @tbielawa  Is it bug?

**Comment by aoyawale** [comment]
getting something similar using  wait_for_connection after a reboot.
```
- name: restart system to reboot to newest kernel
        shell: "sleep 5 && reboot"
        async: 0
        poll: 0
        ignore_errors: yes

- name: wait for the system to reboot
        wait_for_connection:
          connect_timeout: 20
          sleep: 20
          delay: 60
          timeout: 60
```
only works if I add a sleep before the reboot.
using 2.4.0 and 2.4.3.0

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
This is not a bug. The playbook is exiting because the reboot task is failing. The reboot task is failing because Ansible is expecting the connection to be maintained while that task is executing.

What you want is a ['fire and forget'](https://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html) task, which tells Ansible it is ok for the connection to be severed.

```yaml
- name: Reboot the system
  shell: shutdown -r now && sleep 5
  async: 45
  poll: 0

- pause:
    seconds: 60
```
