### ISSUE TITLE
Unable to modify first blockinfile module output

### ISSUE THREAD

**Issue by espressobeanies** [ansible/ansible#36410]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Blockinfile module

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Not changed from initial Ubuntu package install

##### OS / ENVIRONMENT
Ubuntu 16.04.3 (Xenial)

##### SUMMARY
After running the below Ansible playbook, the lineinfile commands to replace text generated by the blockinfile commands will only work with the second blockinfile command and not touch the first.

##### STEPS TO REPRODUCE
Run the pasted playbook below:

```yaml
---
- hosts: 127.0.0.1
  connection: local
  become: yes
  become_user: root
  become_method: sudo

  vars_prompt:
   - name: "parameter1"
     prompt: "Set filename?"
     private: no

   - name: "parameter2"
     prompt: "Set param2 (y/n)"
     private: no

   - name: "parameter3"
     prompt: "Set param3 (y/n)"
     private: no

   - name: "parameter4"
     prompt: "Set param4 (y/n)"
     private: no

  tasks:
   - name: Create new monitoring config file
     file:
       state: touch
       path: "/home/user/testing/{{ parameter1 }}.cfg"
       owner: root
       group: root
       mode: 0644

   - name: Build the config file and begin inputting variables
     blockinfile:
       dest: "/home/user/testing/{{ parameter1 }}.cfg"
       marker: "#{mark} BLOCK GROUP 1"
       block: |
                variable1
                variable2          32x
                }

   - name: Build the config file and begin inputting variables
     blockinfile:
       dest: "/home/user/testing/{{ parameter1 }}.cfg"
       marker: "#{mark} BLOCK GROUP 2"
       block: |
                 variable1
                 variable2          32x
                 }

   - name: Set param3 actions
     when: parameter3 == "y"
     lineinfile:
       dest: "/home/user/testing/{{ parameter1 }}.cfg"
       regexp: 'variable1(.*(?<!insert1))'
       line: '\tvariable1\tinsert1'
       backrefs: yes

   - name: Set param2 actions
     when: parameter2 == "y"
     lineinfile:
       dest: "/home/user/testing/{{ parameter1 }}.cfg"
       regexp: 'variable1(.*(?<!insert1optional))'
       line: '\tvariable1\tinsert1optional'
       backrefs: yes

   - name: Set param4 actions
     when: parameter4 == "y"
     replace:
       path: "/home/user/testing/{{ parameter1 }}.cfg"
       regexp: '\b32x'
       replace: '\b32x\n\tparam4_output\t0'
       after: '\b32x'
       backup: no

   - name: Set param4 alt actions
     when: parameter4 == "n"
     replace:
       path: "/home/user/testing/{{ parameter1 }}.cfg"
       regexp: '\b32x'
       replace: '\b32x\n\talt_param4_output\t0'
       after: '\b32x'
       backup: no
```

##### EXPECTED RESULTS
The expected results should show that the same text being modified in "BLOCK GROUP 2" is mirrored in "BLOCK GROUP 1".

##### ACTUAL RESULTS
Text in "BLOCK GROUP 2" only gets modified and "BLOCK GROUP 1" is not touched.

```
 [WARNING]: Could not match supplied host pattern, ignoring: all

 [WARNING]: provided hosts list is empty, only localhost is available

Set filename?: test
Set param2 (y/n): y
Set param3 (y/n): y
Set param4 (y/n): y

PLAY [127.0.0.1] ****************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [Create new monitoring config file] ****************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Build the config file and begin inputting variables] **********************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Build the config file and begin inputting variables] **********************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Set param3 actions] *******************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Set param2 actions] *******************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Set param4 actions] *******************************************************************************************************************************************************************************************************************
changed: [127.0.0.1]

TASK [Set param4 alt actions] ***************************************************************************************************************************************************************************************************************
skipping: [127.0.0.1]

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=7    changed=6    unreachable=0    failed=0
```
