### ISSUE TITLE
nxos_snmp_host v3 typo

### ISSUE THREAD

**Issue by ossark** [ansible/ansible#36421]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
nxos_snmp_host

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = /Users/johndoe/.ansible.cfg
  configured module search path = [u'/Users/johndoe/repos/ansible/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
DEFAULT_HOST_LIST(/Users/johndoe/.ansible.cfg) = [u'/Users/johndoe/repos/ansible/inventory']
DEFAULT_LOG_PATH(/Users/johndoe/.ansible.cfg) = /Users/johndoe/.ansible.log
DEFAULT_MANAGED_STR(/Users/johndoe/.ansible.cfg) = Ansible managed: modified on %Y-%m-%d by {uid} on {host}
DEFAULT_MODULE_PATH(/Users/johndoe/.ansible.cfg) = [u'/Users/johndoe/repos/ansible/library']
DEFAULT_VAULT_PASSWORD_FILE(/Users/johndoe/.ansible.cfg) = /Users/johndoe/.ssh/vault

##### OS / ENVIRONMENT
N/A

##### SUMMARY
There seems to be a bug in nxos_snmp_host module that tries to use keyword "trap" instead of "traps".

##### STEPS TO REPRODUCE

```
---
- hosts: nexus
  gather_facts: false
  connection: local

  tasks:
    - name: configure SNMP hosts
      nxos_snmp_host:
        snmp_host: 1.2.3.4
        version: v3
        v3: priv
        state: present
```

##### EXPECTED RESULTS
SNMP host set with version v3 and priv

##### ACTUAL RESULTS
```
fatal: [10.1.240.201]: FAILED! => {"changed": false, "failed": true, "msg": "snmp-server host 1.2.3.4 trap version 3 priv\r\r\n                       ^\r\n% Invalid command at '^' marker.\r\n\rnexus9k-1(config)# "}
```
