### ISSUE TITLE
nxos_bgp_neighbor_af not idempotent

### ISSUE THREAD

**Issue by victorock** [ansible/ansible#36435]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

nxos_bgp_neighbor_af

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /Users/jdacosta/Devel/ansible-netops/cisco/nxos/applications/fabric/europe-central-fr1/ansible.cfg
  configured module search path = [u'/Users/jdacosta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

N/A
nxos.7.0.3.I7.1

##### STEPS TO REPRODUCE

```yaml
- name: "nxos_bgp_neighbor: leaf01"
  nxos_bgp_neighbor:
    asn: "65001"
    neighbor: "1.1.1.21"
    remote_as: "65001"
    update_source: "1.1.1.1"
    state: "present"

- name: "nxos_bgp_neighbor: leaf02"
  nxos_bgp_neighbor:
    asn: "65001"
    neighbor: "1.1.1.22"
    remote_as: "65001"
    update_source: "1.1.1.1"
    state: "present"

- name: "nxos_bgp_neighbor_af: leaf01"
  nxos_bgp_neighbor_af:
    asn: "65001"
    neighbor: "1.1.1.21"
    afi: ipv4
    safi: unicast
    send_community: both
    state: "present"

- name: "nxos_bgp_neighbor_af: leaf02"
  nxos_bgp_neighbor_af:
    asn: "65001"
    neighbor: "1.1.1.22"
    afi: ipv4
    safi: unicast
    send_community: both
    state: "present"
```

##### ACTUAL RESULTS

```

```
