### ISSUE TITLE
Seport: support list input for ports

### ISSUE THREAD

**Issue by rwaweber** [ansible/ansible#36466]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

seport

##### ANSIBLE VERSION

```
ansible 2.4.3.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

It would be nice if the `ports` option allowed for a list of strings instead of just a string.

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/seport.py#L234

##### EXPECTED RESULTS
```yaml
- seport:
    ports: 
    - "10000-10100"
    - "10112"
    proto: tcp
    setype: memcache_port_t
    state: present
```

##### ACTUAL RESULTS
```yaml
- seport:
    ports: 10000-10100,10112
    proto: tcp
    setype: memcache_port_t
    state: present
```
