### ISSUE TITLE
Need ansible to report MB values in actual MB and not MiB

### ISSUE THREAD

**Issue by Routhinator** [ansible/ansible#36463]
##### ISSUE TYPE

 - Bug Report/Documentation Report

##### COMPONENT NAME

ansible 
##### ANSIBLE VERSION

```
ansible 2.4.3.0
```
##### SUMMARY

Anisible misleadingly marks it's variables as being in MB, however they are in fact in MiB which is affecting a lot of calculations we do for calculating Postgresql buffer and memory parameters. How do I correct the units? I cannot find anything in the docs, so if there is a way this is a documentation issue. If it's not possible then I view this as a bug since the units should indicate MiB if they are reporting MiB, not MB.

**Comment by dagwieers** [comment]
If your question is related to the default memory facts, then you are right. In my opinion we should return the number of bytes, rather than values in kB, MB or GB. Leave those calculations up to the user (Jinja2 already includes a filter for getting human-readable output).

PS For backward compatibility we cannot touch the existing facts.

**Comment by samdoran** [comment]
From digging through various `facts` files , we definitely are reporting numbers in base 2. I can add a note to the `setup` module docs clarifying this.

Adding another field that provides bytes is probably best way to solve this since we can't modify the existing field for backwards, as @dagwieers noted.

cc @alikins

**Comment by dagwieers** [comment]
Please look at the Windows facts, because IIRC we are already doing it there.

**Comment by alikins** [comment]
@Routhinator which facts in particular?

ansible_memory_mb
ansible_memfree_mb
ansible_memtotal_mb
ansible_swapfree_mb
ansible_swaptotal_mb

for linux, those are are in bytes / 1024 /1024 so, MiB rounded to nearest MiB.
osx and bsd seem to be same.

The unit or the facts names are not going to be changed, so converting desired
unit in jinja is most practical work around. 

I would tend to agree that eventually adding a new fact fact that returns bytes
would be the most consistent.

**Comment by dagwieers** [comment]
To clarify, the default Windows memory size is still in MB:
```
[dag@moria crombeen]$ ansible -m setup computer80 | grep _mb
        "ansible_memtotal_mb": 6127, 
        "ansible_swaptotal_mb": 0, 
```
And I would definitely add `ansible_memtotal` and `ansible_swaptotal`. But maybe we should take this opportunity to put these new values in a better hierarchy/structure, like: `ansible_memory.total` and `ansible_swap.total` so that we can add free, used, etc. And later we can hopefully access it as 
`facts.memory.total` and `facts.swap.total`.

My point was that the **[win_disk_facts](https://docs.ansible.com/ansible/devel/modules/win_disk_facts_module.html)** module was modified to only show real values in bytes: #35326

The included examples show how to convert easily using the **filesizeformat** jinja2 filter:
```yaml
- name: Convert first system disk into various formats
  debug:
    msg: '{{ disksize_gib }} vs {{ disksize_gib_human }}'
  vars:
    # Get first system disk
    disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'

    # Show disk size in Gibibytes
    disksize_gib_human: '{{ disk.size|filesizeformat(True) }}'   # returns "223.6 GiB" (human readable)
    disksize_gib: '{{ (disk.size/1024|pow(3))|round|int }} GiB'  # returns "224 GiB" (value in GiB)

    # Show disk size in Gigabytes
    disksize_gb_human: '{{ disk.size|filesizeformat }}'        # returns "240.1 GB" (human readable)
    disksize_gb: '{{ (disk.size/1000|pow(3))|round|int }} GB'  # returns "240 GB" (value in GB)
```
