### ISSUE TITLE
Named block directives do not work in handlers

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#36480]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/selivan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
Ansible host: Ubuntu GNU/Linux 16.04 Xenial
Managed host: Ubuntu GNU/Linux 16.04 Xenial

##### SUMMARY
Named block statements (http://docs.ansible.com/ansible/latest/playbooks_blocks.html) do not work in handlers. Ansible does not see that handler at all.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  become: yes
  tasks:
    - name: install nginx config
      template: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644
      notify: reload nginx
  handlers:
    - name: reload nginx
      block:
        - shell: nginx -t
        - service: name=nginx state=reloaded
```

##### EXPECTED RESULTS
Handler `reload nginx` should run and execute both modules: first `shell`, then, if `shell` returned success, execute `service`.

##### ACTUAL RESULTS

```
ERROR! The requested handler 'reload nginx' was not found in either the main handlers list nor in the listening handlers list
```
