### ISSUE TITLE
Ansible gitlab module should fail if importing the repo of url_import is failing

### ISSUE THREAD

**Issue by zoobab** [ansible/ansible#36495]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

gitlab_project

##### ANSIBLE VERSION

```
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.2 (Maipo)

##### SUMMARY

I have this task which creates a GIT repo:
```yaml
- name: Create Git repo
  gitlab_project:
    server_url: "http://myhost.com/gitlab"
    validate_certs: True
    login_user: "my_git_user }}"
    login_password: "{{ my_git_password }}"
    name: "{{ my_repo_name }}"
    group: "{{ my_repo_group }}"
    public: True
    visibility_level: 20
    issues_enabled: False
    wiki_enabled: True
    snippets_enabled: True
    import_url: "http://myhost.com/gitlab/gitrepothatdoesnotexist.git"
    state: present
```

Then ansible succeeds in the step, but when I go to the gitlab web interface at the URL of the created git repo, it throws an error like:

" Import repository
The repository could not be imported.

Error importing repository http://myhost.com/gitlab/gitrepothatdoesnotexist.git into my_git_repo - Cloning into bare repository '[REPOS PATH]/mygitrepo.git'...
fatal: repository 'http://myhost.com/gitlab/gitrepothatdoesnotexist.git' not found

"

##### STEPS TO REPRODUCE

```yaml
- name: Create Git repo
  gitlab_project:
    server_url: "http://myhost.com/gitlab"
    validate_certs: True
    login_user: "{{ my_git_user }}"
    login_password: "{{ my_git_password }}"
    name: "{{ my_repo_name }}"
    group: "{{ my_repo_group }}"
    public: True
    visibility_level: 20
    issues_enabled: False
    wiki_enabled: True
    snippets_enabled: True
    import_url: "http://myhost.com/gitlab/gitrepothatdoesnotexist.git"
    state: present
```

##### EXPECTED RESULTS

Gitlab should show an error when you visit the URL of the created repo.

##### ACTUAL RESULTS

```

```
