### ISSUE TITLE
import_role with delegate_to does not run handlers on the delegated to host

### ISSUE THREAD

**Issue by nkakouros** [ansible/ansible#36518]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
import_role

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 8743b20c8e) last updated 2018/02/13 17:38:47 (GMT +200)
  config file = /home/nikos/Projects/ansible-demo/ansible.cfg
  configured module search path = ['/home/nikos/Projects/ansible-demo/ansible/lib/modules']
  ansible python module location = /home/nikos/Projects/ansible/lib/ansible
  executable location = /home/nikos/Projects/ansible/bin/ansible
  python version = 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
```

##### SUMMARY
I am running import_role against a just-above created instance on google cloud. The role runs fine on the distant host, but the role handlers (just a win_reboot task), runs against my localhost.

##### STEPS TO REPRODUCE
This is the tasks that I use:

```yaml
- gce:
    name: custom-windows-image
    disk_auto_delete: no
    disk_size: "{{ win_server.disk_size }}"
    external_ip: ephemeral
    image_family: windows-2016
    ip_forward: yes
    machine_type: n1-highcpu-4
    metadata: {}
    # TODO change this to 'default'
    network: "{{ project_facts.network.name }}"
    subnetwork: "{{ win_server.subnet }}"
    zone: "{{ win_server.zone }}"
    tags: custom-windows-image
  register: win_instance
- command: >-
    gcloud beta compute reset-windows-password
      --quiet
      --user="{{ win_server.user }}"
      --zone="{{ win_server.zone }}"
      custom-windows-image
  register: win_instance_password
  until: win_instance_password.rc != 1
  failed_when: false
  retries: 5
- add_host: &winrm
    hostname: win_instance
    ansible_host: "{{ win_instance.instance_data[0].public_ip }}"
    ansible_connection: winrm
    ansible_port: 5986
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_transport: ntlm
    ansible_user: "{{ win_server.user }}"
    ansible_password: "{{ win_instance_password.stdout_lines[1] | regex_replace('password:[\\s]*([^s]*)', '\\1') }}"
- gce_firewall:
    name: custom-windows-image
    network: "{{ project_facts.network.name }}"
    allowed: udp:3389;tcp:3389;tcp:5986;icmp
    src_ranges: "{{ project_facts.local.address }}/32"
    target_tags: custom-windows-image
- wait_for_connection:
  delegate_to: custom-windows-image
  vars: *winrm
- import_role:
    name: ansible-windows-setup
    private: yes
  vars:
    windows_setup_hostname: "{{ win_server.name }}"
  delegate_to: win_instance
```

##### EXPECTED RESULTS
The role handler should be executed against the windows instance and reboot it.

##### ACTUAL RESULTS

```
RUNNING HANDLER [ansible-windows-setup : Reboot windows] ************************************
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: nikos
<127.0.0.1> EXEC (Get-WmiObject -ClassName Win32_OperatingSystem).LastBootUpTime
fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "msg": "win_reboot: failed to get host uptime info, rc: 1, stdout: b'', stderr: b\"/bin/bash: -c: line 0: syntax error near unexpected token `.LastBootUpTime'\\n/bin/bash: -c: line 0: `(Get-WmiObject -ClassName Win32_OperatingSystem).LastBootUpTime'\\n\"",
    "reboot": false
}
META: ran handlers
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/import_role.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/import_role.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
More simplistic reproducer:

```
.
├── 36518.yml
└── roles
    └── foo
        ├── handlers
        │   └── main.yml
        └── tasks
            └── main.yml
```

36518.yml
```
---
- hosts: all
  gather_facts: false
  tasks:
    - import_role:
        name: foo
      delegate_to: localhost
```

roles/foo/handlers/main.yml
```
- name: foo handler
  command: hostname
```

roles/foo/tasks/main.yml
```
---
- command: hostname
  notify:
    - foo handler
```

The handler is not delegated.
