### ISSUE TITLE
ansible_python_interpreter ignored in Ansible 2.4 for apt module when use async parameter

### ISSUE THREAD

**Issue by ozlevka-work** [ansible/ansible#36536]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
apt module

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /home/ozlevka/tmp/terraform/ansible.cfg
  configured module search path = ['/home/ozlevka/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ozlevka/.virtualenv/ansible/lib/python3.6/site-packages/ansible
  executable location = /home/ozlevka/.virtualenv/ansible/bin/ansible
  python version = 3.6.3 (default, Nov 17 2017, 17:34:18) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Linux ubuntu-server 4.4.0-87-generic #110-Ubuntu SMP Tue Jul 18 12:55:35 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
##### SUMMARY

The apt module ignore the ansible_python_interpreter variable when use async parameter
##### STEPS TO REPRODUCE

configure ansible_python_interpreter=/usr/bin/python3 in inventory
default python interpreter in Ubuntu 16.04
Run playbook

``` yaml
 - name: Install docker dependencies
      apt:
        name: software-properties-common
        update_cache: true
        state: latest
      async: 3600
      poll: 0
```

##### EXPECTED RESULTS

Playbook install desired package
##### ACTUAL RESULTS

```
fatal: [first]: FAILED! => {"changed": true, "module_stderr": "Shared connection to 10.0.0.56 closed.\r\n", "module_stdout": "/bin/sh: 1: /usr/bin/python: not found\r\n", "msg": "MODULE FAILURE", "rc": 127}
```
