### ISSUE TITLE
nios_zone: Unable to update comment for an existing Zone

### ISSUE THREAD

**Issue by Sunil788** [ansible/ansible#36563]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nios_zone

##### ANSIBLE VERSION

```
ansible 2.5.0b2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0b2-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

- Ubuntu 16.04.3 LTS

##### SUMMARY

Unable to update comment for an existing Zone

##### STEPS TO REPRODUCE

- Run a playbook to create Zone with Comment

```yaml
    - name: Create Zone with Comment
      nios_zone:
        name: ansibletest.com
        comment: testing
        view: ansibledv1
        provider: "{{ provider }}"
        state: present
```
Zone created with comment Successfully

- Now run again playbook to update the Comment for the created Zone
```yaml
    - name: Update Zone with Comment
      nios_zone:
        name: ansibletest.com
        comment: testing-update
        view: ansibledv1
        provider: "{{ provider }}"
        state: present
```

##### EXPECTED RESULTS

- Comment should be updated for the Zone successfully
##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_yUCSRd/ansible_modlib.zip/ansible/module_utils/net_tools/nios/api.py", line 146, in _invoke_method
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/********_client/connector.py", line 41, in callee
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/********_client/connector.py", line 430, in update_object
    code=r.status_code)

fatal: [10.35.2.77]: FAILED! => {
    "changed": false,
    "code": "Client.Ibap.Proto",
    "failed": true,
    "invocation": {
        "module_args": {
            "comment": "testing-update",
            "extattrs": null,
            "fqdn": "ansibletest.com",
            "grid_primary": null,
            "grid_secondaries": null,
            "name": "ansibletest.com",
            "provider": {
                "host": "10.35.2.77",
                "http_pool_connections": 10,
                "http_pool_maxsize": 10,
                "http_request_timeout": 10,
                "max_results": 1000,
                "max_retries": 3,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "silent_ssl_warnings": true,
                "ssl_verify": false,
                "username": "admin",
                "wapi_version": "1.4"
            },
            "state": "present",
            "view": "ansibledv1"
        }
    },
    "msg": "Field is not allowed for update: fqdn",
    "operation": "update_object",
    "type": "AdmConProtoError"
}
        to retry, use: --limit @/root/Ansible_Tests/zone-testcases.retry

```
