### ISSUE TITLE
Notification executed too many times

### ISSUE THREAD

**Issue by analytically** [ansible/ansible#3656]
```

---
# file: roles/kibana3/tasks/main.yml

- name: Make sure Kibana 3 is cloned under /var/www/kibana
  git: repo=https://github.com/elasticsearch/kibana.git dest=/var/www/kibana
  tags: kibana
  notify:
    - restart apache2
```

```

---
# file: roles/kibana3/handlers/main.yml

- name: restart apache2
  service: name=apache2 state=restarted
```

When running:
ansible-playbook -i hosts site.yml --tags "kibana"  

I get:

```
PLAY [monitors[0]] ************************************************************ 

GATHERING FACTS *************************************************************** 
ok: [vagrant]

TASK: [Make sure Kibana 3 is cloned under /var/www/kibana] ******************** 
changed: [vagrant]

NOTIFIED: [restart apache2] *************************************************** 
changed: [vagrant]

NOTIFIED: [restart apache2] *************************************************** 
changed: [vagrant]

PLAY RECAP ******************************************************************** 
vagrant                    : ok=4    changed=3    unreachable=0    failed=0   
```

Apache should only have been restarted once.
