### ISSUE TITLE
No option to update an existing NIOS Network View name

### ISSUE THREAD

**Issue by Sunil788** [ansible/ansible#36574]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- nios_network_view

##### ANSIBLE VERSION

```
ansible 2.5.0b2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.0b2-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

- Ubuntu 16.04.3 LTS

##### SUMMARY

- Updating an existing NIOS network view name will create a new Network View instead of updating the existing ones.
 
##### STEPS TO REPRODUCE

- Run a playbook to create Network view 

```yaml
    - name: Create Network View
      nios_network_view:
        name: ansible1
        extattrs:
          Site: India
        provider: "{{ provider }}"
        state: present
```
There is no reference for network view "ansible1" name to be updated. If I try to update the Network View name with extattrs as reference (which is not correct in my opinion) it will create a new Network view

##### EXPECTED RESULTS

There should be an option to update Network view name

##### ACTUAL RESULTS
It is creating a new Network view instead of updating the exiting Network View name
