### ISSUE TITLE
shallow git: supporting more than one refspec

### ISSUE THREAD

**Issue by robocoder** [ansible/ansible#36596]
# ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
source_control/git

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/var/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

Ansible Host: MacOS High Sierra; Python 2.7
Managed Host: Linux - Ubuntu 16.04 LTS (Xenial); git 2.16.2

##### SUMMARY
Doesn't handle multiple [refspec](https://git-scm.com/book/en/v2/Git-Internals-The-Refspec).

##### STEPS TO REPRODUCE

```yaml
- name: Example
  git:
    repo: "https://github.com/lukas2511/dehydrated.gitt"
    dest: "/opt/dehydrated"
    version: "v0.5.0"
    force: yes
    accept_hostkey: yes
    remote: "origin"
    refspec:
      - "+refs/heads/*:refs/remotes/origin/*"
      - "+refs/tags/*:refs/tags/*"
    depth: 1
    update: yes
```

##### EXPECTED RESULTS

Success ... allowing for switch_version between branches and tags.

##### ACTUAL RESULTS

```
[bdr] failed: [bdr02] (item={'value': {u'repo': u'lukas2511/dehydrated', u'version': u'v0.5.0'}, 'key': u'dehydrated'}) => {"changed": false, "cmd": "/usr/bin/git fetch --depth 1 origin '['\"'\"'+refs/heads/*:refs/remotes/origin/*'\"'\"', '\"'\"'+refs/tags/*:refs/tags/*'\"'\"']'", "item": {"key": "dehydrated", "value": {"repo": "lukas2511/dehydrated", "version": "v0.5.0"}}, "msg": "fatal: Invalid refspec '['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*']'", "rc": 128, "stderr": "fatal: Invalid refspec '['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*']'\n", "stderr_lines": ["fatal: Invalid refspec '['+refs/heads/*:refs/remotes/origin/*', '+refs/tags/*:refs/tags/*']'"], "stdout": "", "stdout_lines": []}
```
