### ISSUE TITLE
nmcli does not set ipv4.method to manual when IP address is specified, no way to make it do so

### ISSUE THREAD

**Issue by jikamens** [ansible/ansible#36615]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
nmcli

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jik/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### CONFIGURATION
Nothing is changed.

##### OS / ENVIRONMENT
Ubuntu 17.10 64-bit

##### SUMMARY
Assigning static IP with `nmcli` module doesn't have any effect unless `ipv4.method` is set to `manual`, and there's no way to do that with the module.

##### STEPS TO REPRODUCE
I tried to use the task shown below to configure a static IP address for one of the machines on my network after doing an initial install on it during which it was assigned an address by DHCP:

The parameters I specified were indeed updated (as confirmed by doing `nmcli c show "Wired connection 2"` in a shell window), but the IP address of the connection didn't change even after I restarted NetworkManager, because the `ipv4.method` parameter on the connection was still set to `auto`.

I had to add a separate ansible task to run `nmcli c modify "Wired connection 2" ipv4.method manual` explicitly for the changes I specified in the `nmcli` task to have any effect.

```yaml
  - nmcli:
      conn_name: "Wired connection 2"
      type: ethernet
      dns4: "192.168.4.17"
      gw4: "192.168.4.1"
      ifname: "enp6s1"
      ip4: "192.168.4.12/24"
      state: present
```

##### EXPECTED RESULTS
I expect either configuring a connection with a hard-coded IP address to automatically switch `ipv4.method` to `manual`, or for there to be a way to set that parameter explicitly within the module.

##### ACTUAL RESULTS
I can't do what I need.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/nmcli.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nmcli.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @alcamie101
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rydevops** [comment]
+1

Be wonderful to have this fixed (or an option added to set this). This is still present in 2.5 and 2.6. I was able to get the manual method set by adding  'ipv4.method': 'manual' to the  options dictionary in create_connection_ethernet() and modify_connection_ethernet() in nmcli.py. If this is not set, the static IP still works however the interface will also have a DHCP IP address if a DHCP server is present in the network.

**Comment by ansibot** [comment]
cc @Qalthos @brampling @ganeshrn @gdpak @gundalow @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by cocampbe** [comment]
Well. I just ran into this. This really needs to be added to 2.5 as that is usually whats on epel.

**Comment by friendlypenguin** [comment]
Have the same issue. setting ip should really disable dhcp.

**Comment by louwrentius** [comment]
I have the same issue when setting up a bond interface. This is my simple work-around:

```
- name: ansible bug fix for static ip
  replace:
     path: /etc/sysconfig/network-scripts/ifcfg-bonding
     regexp: 'BOOTPROTO=dhcp'
     replace: 'BOOTPROTO=static'
     backup: yes
```

Unfortunately I now also notice that the slave interfaces are not enabled on boot. (ONBOOT=no).

Fixed that with a similar trick.
