### ISSUE TITLE
Increase Azure network interface provisioning flexibility

### ISSUE THREAD

**Issue by ingokofler** [ansible/ansible#36624]
##### ISSUE TYPE
Feature Idea

 - Bug Report
 - Feature Idea
 - Documentation Report

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION

```
N/A
```

##### SUMMARY
The current implementation of the azure_rm_networkinterface does not allow to create a NIC in a resource group R and connect it to a virtual network in a different resource group X. The implementation is assuming that both are in the same resource group and lacks configuration of a separate resource group where the virtual network lives in.

In contrast to that this is already possible with the azure_rm_virtualmachine module which offers a dedicated option `virtual_network_resource_group` for that purpose

##### STEPS TO REPRODUCE

```yaml
- name: Create a network interface that connects to a vnet in a different resource group
  azure_rm_networkinterface:
        name: nic001
        resource_group: Testing
        virtual_network_name: vnet001
        virtual_network_resource_group: TestingNet
        subnet_name: subnet001
```

##### EXPECTED RESULTS

Once implemented, it should be possible to connect NICs to virtual networks in different resource groups, as it's currently already possible with the azure_rm_virtualmachine module

##### ACTUAL RESULTS

```

```
