### ISSUE TITLE
Provision Azure VMs without allocating public IPs

### ISSUE THREAD

**Issue by ingokofler** [ansible/ansible#36622]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine_module

##### ANSIBLE VERSION

```
N/A
```

##### SUMMARY

The current implementation of the VM provisioning module always tries to allocate a public IP for the VM. There is no simple way to turn of this via a setting. The only workaround that exists is to first create a NIC first and re-use that NIC for the VM. Depending on company policies the allocation of public IP addresses may be restricted for subscriptions that are solely used for running CI workloads.

##### STEPS TO REPRODUCE

```yaml
- name: Create VM with defaults
  azure_rm_virtualmachine:
    resource_group: Testing
    name: testvm10   
    admin_username: adm
    admin_password: <your password here>
    allocate_public_ip: false
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: '7.1'
      version: latest
```

##### EXPECTED RESULTS
Depending on the paramater allocate_public_ip the feature of allocating a public IP can be turned on or off.
