### ISSUE TITLE
cs_sshkeypair.py return FAILED when renaming a key

### ISSUE THREAD

**Issue by nbari** [ansible/ansible#36631]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
cs_sshkeypair

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /Users/nbari/projects/ansible/ansible.cfg
  configured module search path = [u'/Users/nbari/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nbari/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/nbari/Library/Python/2.7/bin/ansible
  python version = 2.7.14 (default, Feb  6 2018, 20:04:00) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  tasks:
    - name: ensure my ssh public key
      cs_sshkeypair:
        name: my-key
        public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        api_region: my-region
```

Change name to: `my-key-2` or something different and run again the playbook:

    ansible-playbook name-of-the-pb.yml

It will only work for the 2nd time, but the first one will get an error.

##### EXPECTED RESULTS
No error or message specifying changed=1

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: 'NoneType' object has no attribute '__getitem__'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_P78L9S/ansible_module_cs_sshkeypair.py\", line 276, in <module>\n    main()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_P78L9S/ansible_module_cs_sshkeypair.py\", line 267, in main\n    ssh_key = acs_sshkey.register_ssh_key(public_key)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_P78L9S/ansible_module_cs_sshkeypair.py\", line 172, in register_ssh_key\n    if ssh_key['fingerprint'] != fingerprint:\nTypeError: 'NoneType' object has no attribute '__getitem__'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

```
