### ISSUE TITLE
"any_errors_fatal" does not work when "flush_handlers" used

### ISSUE THREAD

**Issue by azhurbilo** [ansible/ansible#36649]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
any_errors_fatal

##### ANSIBLE VERSION

ansible 2.4.3.0

##### SUMMARY

With "any_errors_fatal: yes" playbook continue to run after "flush_handlers" block despite of failed handler 

##### STEPS TO REPRODUCE

have 2 machines in target group:
- 01host
- 02host

```yaml
---

- hosts: all
  any_errors_fatal: yes
  tasks:
    - shell: echo 1
      notify: failed_handler

    - meta: flush_handlers

    - shell: echo 2
  
  handlers:
    # failed handler only on 1 host
    - name: failed_handler
      shell: hostname | grep -v '01host'
```

##### EXPECTED RESULTS

"failed_handler" return error on one host, other hosts don't continue to execute next tasks

##### ACTUAL RESULTS

```
TASK [command] ********************************************************************************************************************************************************************************************************************
changed: [01host]
changed: [02host]

RUNNING HANDLER [failed_handler] **************************************************************************************************************************************************************************************************
changed: [02host]
fatal: [01host]: FAILED! => {
    "changed": true, 
    "cmd": "hostname | grep -v '01.stg'", 
    "delta": "0:00:00.003207", 
    "end": "2018-02-23 17:33:28.588487", 
    "rc": 1, 
    "start": "2018-02-23 17:33:28.585280"
}

MSG:

non-zero return code


TASK [command] ********************************************************************************************************************************************************************************************************************
changed: [01host]
changed: [02host]

PLAY RECAP ************************************************************************************************************************************************************************************************************************
01host : ok=2    changed=1    unreachable=0    failed=1   
02host : ok=4    changed=3    unreachable=0    failed=0   
```
