### ISSUE TITLE
Hosts added to a group with add_host don't work in included playbooks

### ISSUE THREAD

**Issue by boosh** [ansible/ansible#3664]
If I have a play like:

``` yml
- name: Launch an instance then delegate to the reprovision play
  hosts: localhost
  user: ubuntu
  gather_facts: False
  vars:
    keypair: mykey
    image: ami-ce7b6fba
  tasks:
    - name: Launch instance
      local_action: 
        module: ec2 
        keypair: $keypair 
        image: $image 
        wait: true 
      register: ec2
    - name: Add new instance to host group
      local_action: add_host hostname=${item.public_ip} groupname=launched
      with_items: ${ec2.instances}
    - name: Wait for SSH to come up
      local_action: wait_for host=${item.public_dns_name} port=22 delay=10 timeout=320 state=started
      with_items: ${ec2.instances}

- include: reprovision.yml {hosts=launched}
```

and have the following in `reprovision.yml`:

``` yml
- name: Configure instance(s)
  hosts: ${hosts}
  user: ubuntu
  sudo: True
  gather_facts: True
  roles:  
    - webserver
```

then no hosts match in reprovision.yml and the new instance isn't provisioned as a web server.

If this is intended, is there a workaround I can use?
