### ISSUE TITLE
ios_command not escalating if prompt ends in #

### ISSUE THREAD

**Issue by visualne** [ansible/ansible#36656]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel c3523cdd60) last updated 2018/02/09
```
##### SUMMARY

Upon initial login to a cisco device if the prompt ends in # the authorize and auth_pass variables will be ignored by the task.

##### STEPS TO REPRODUCE

```yaml
- name: Get privilege level
    ios_command:
        provider:
            username: 'phonyusername'
            password: 'phonypassword'
            authorize: yes
            auth_pass: 'phonyenablepassword'
        commands: show priv
    register: commandoutput

```

##### EXPECTED RESULTS

I expected the output of commandoutput to be privilege level 15

##### ACTUAL RESULTS

The output of commandoutput is privilege level 2
