### ISSUE TITLE
Azure load balancer - failed to create - <type 'dict'> cannot be converted to a list

### ISSUE THREAD

**Issue by jluyckx93** [ansible/ansible#36697]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_loadbalancer

##### ANSIBLE VERSION
```ansible 2.6.0
  config file = None
  configured module search path = [u'/home/jef/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
```

##### CONFIGURATION
ansible-config dump --only-changed

##### OS / ENVIRONMENT
```Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
```
##### SUMMARY
Creating a Azure load balancer doesn't work. Hitting the same error for each "list" argument.

`  "msg": "argument frontend_ip_configurations is of type <type 'dict'> and we were unable to convert to list: <type 'dict'> cannot be converted to a list"`

used documentation:
[http://docs.ansible.com/ansible/devel/modules/azure_rm_loadbalancer_module.html](http://docs.ansible.com/ansible/devel/modules/azure_rm_loadbalancer_module.html)
(No example available yet for this version)

Is this a bug or a config error on my side ? 

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  vars:
    region: westeurope
    resourcegroup_name: AnsibleOCP
    master_availabilityset_name: MasterAvailabilitySet
    virtualnetwork_name: ocpvnet
    master_subnet_name: ocpmastersubnet
    node_subnet_name: ocpnodesubnet
    lb_external_public_ip_name: LbExternalPublicIP
    master_loadbalancer_name: MasterLB
    master_loadbalancer_frontend_pool_name: mafrendpool
    master_frontend_ip_config_name: mafrendipconf
    master_loadbalancer_backend_pool_name: mabaendpool
    master_loadbalancer_rule_name: malbrule
    master_loadbalancer_probe_name: masterprobe
    master_networkinterface_name: manic
    master_securitygroup_name: masterNSG
    master_virtualmachine_name: master
    adminuser_name: cloud-user
    master_node_count: 3
  tasks:

  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resourcegroup_name }}"
      location: "{{ region }}"

  - name: Create private virtual network
    azure_rm_virtualnetwork:
      name: "{{ virtualnetwork_name }}"
      resource_group: "{{ resourcegroup_name }}"
      address_prefixes_cidr:
          - "10.0.0.0/8"

  - name: Create master subnet
    azure_rm_subnet:
      name: "{{ master_subnet_name }}"
      virtual_network_name: "{{ virtualnetwork_name }}"
      resource_group: "{{ resourcegroup_name }}"
      address_prefix_cidr: "10.1.0.0/16"

  - name: Create node subnet
    azure_rm_subnet:
      name: "{{ node_subnet_name }}"
      virtual_network_name: "{{ virtualnetwork_name }}"
      resource_group: "{{ resourcegroup_name }}"
      address_prefix_cidr: "10.2.0.0/16"

  - name: Create public ip for external loadbalancer
    azure_rm_publicipaddress:
      resource_group: "{{ resourcegroup_name }}"
      allocation_method: Static
      name: "{{ lb_external_public_ip_name }}"

  - name: create master loadbalancer
    azure_rm_loadbalancer:
      name: "{{ master_loadbalancer_name }}"
      location: westeurope
      resource_group: "{{ resourcegroup_name }}"
      frontend_ip_configurations:
        name: "{{ master_loadbalancer_frontend_pool_name }}"
        public_ip_address: "{{ lb_external_public_ip_name }}"
      backend_address_pools:
        name: "{{ master_loadbalancer_backend_pool_name }}"
      probes:
        name: "{{ master_loadbalancer_probe_name }}"
        fail_count: 2
        protocol: tcp
        port: 8443
      load_balancing_rules:
        load_distribution: sourceip
        name: "{{ master_loadbalancer_rule_name }}"
        frontend_ip_configuration: "{{ master_frontend_ip_config_name }}"
        probe: "{{ master_loadbalancer_probe_name }}"
        protocol: tcp
        backend_address_pool: "{{ master_loadbalancer_backend_pool_name }}"
        frontend_port: 8443
        backend_port: 8443

```

##### EXPECTED RESULTS
Succesfully create a Azure load balancer

##### ACTUAL RESULTS

```

TASK [create master loadbalancer] ****************************************************
task path: /home/jef/Ansible_Openshift_Azure_install/testplaybook.yaml:66
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/azure/a                                                                                                                        zure_rm_loadbalancer.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jef
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jef/.ansible/tmp/ans                                                                                                                        ible-tmp-1519588975.48-278183594467782 `" && echo ansible-tmp-1519588975.48-2781835944                                                                                                                        67782="` echo /home/jef/.ansible/tmp/ansible-tmp-1519588975.48-278183594467782 `" ) &&                                                                                                                         sleep 0'
<127.0.0.1> PUT /home/jef/.ansible/tmp/ansible-local-14296dBNIhK/tmpIHLQxc TO /home/je                                                                                                                        f/.ansible/tmp/ansible-tmp-1519588975.48-278183594467782/azure_rm_loadbalancer.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jef/.ansible/tmp/ansible-tmp-1519588975.4                                                                                                                        8-278183594467782/ /home/jef/.ansible/tmp/ansible-tmp-1519588975.48-278183594467782/az                                                                                                                        ure_rm_loadbalancer.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/jef/.ansible/tmp/ansible-tmp-151958                                                                                                                        8975.48-278183594467782/azure_rm_loadbalancer.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/jef/.ansible/tmp/ansible-tmp-1519588975.48                                                                                                                        -278183594467782/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_b52ibz/ansible_modlib.zip/ansible/module_utils/basic.py", line 20                                                                                                                        56, in _check_argument_types
    param[k] = type_checker(value)
  File "/tmp/ansible_b52ibz/ansible_modlib.zip/ansible/module_utils/basic.py", line 18                                                                                                                        64, in _check_type_list
    raise TypeError('%s cannot be converted to a list' % type(value))

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_profile": "latest",
            "append_tags": true,
            "backend_address_pools": {
                "name": "mabaendpool"
            },
            "frontend_ip_configurations": {
                "name": "mafrendpool",
                "public_ip_address": "LbExternalPublicIP"
            },
            "idle_timeout": 4,
            "load_balancing_rules": {
                "backend_address_pool": "mabaendpool",
                "backend_port": 8443,
                "frontend_ip_configuration": "mafrendipconf",
                "frontend_port": 8443,
                "load_distribution": "sourceip",
                "name": "malbrule",
                "probe": "masterprobe",
                "protocol": "tcp"
            },
            "location": "westeurope",
            "name": "MasterLB",
            "probe_fail_count": 3,
            "probe_interval": 15,
            "probes": {
                "fail_count": 2,
                "name": "masterprobe",
                "port": 8443,
                "protocol": "tcp"
            },
            "resource_group": "AnsibleOCP",
            "state": "present"
        }
    },
    "msg": "argument load_balancing_rules is of type <type 'dict'> and we were unable                                                                                                                         to convert to list: <type 'dict'> cannot be converted to a list"

```

Commented the load_balancing_rules list and executed the playbook again, got the same error for another list.

```
TASK [create master loadbalancer] ****************************************************
task path: /home/jef/Ansible_Openshift_Azure_install/testplaybook.yaml:66
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/azure/a                                                                                                                        zure_rm_loadbalancer.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jef
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/jef/.ansible/tmp/ans                                                                                                                        ible-tmp-1519589141.85-253303156571558 `" && echo ansible-tmp-1519589141.85-2533031565                                                                                                                        71558="` echo /home/jef/.ansible/tmp/ansible-tmp-1519589141.85-253303156571558 `" ) &&                                                                                                                         sleep 0'
<127.0.0.1> PUT /home/jef/.ansible/tmp/ansible-local-14705jngB0J/tmpaoNRcK TO /home/je                                                                                                                        f/.ansible/tmp/ansible-tmp-1519589141.85-253303156571558/azure_rm_loadbalancer.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/jef/.ansible/tmp/ansible-tmp-1519589141.8                                                                                                                        5-253303156571558/ /home/jef/.ansible/tmp/ansible-tmp-1519589141.85-253303156571558/az                                                                                                                        ure_rm_loadbalancer.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/jef/.ansible/tmp/ansible-tmp-151958                                                                                                                        9141.85-253303156571558/azure_rm_loadbalancer.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/jef/.ansible/tmp/ansible-tmp-1519589141.85                                                                                                                        -253303156571558/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_aIoxlD/ansible_modlib.zip/ansible/module_utils/basic.py", line 20                                                                                                                        56, in _check_argument_types
    param[k] = type_checker(value)
  File "/tmp/ansible_aIoxlD/ansible_modlib.zip/ansible/module_utils/basic.py", line 18                                                                                                                        64, in _check_type_list
    raise TypeError('%s cannot be converted to a list' % type(value))

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_profile": "latest",
            "append_tags": true,
            "backend_address_pools": {
                "name": "mabaendpool"
            },
            "frontend_ip_configurations": {
                "name": "mafrendpool",
                "public_ip_address": "LbExternalPublicIP"
            },
            "idle_timeout": 4,
            "location": "westeurope",
            "name": "MasterLB",
            "probe_fail_count": 3,
            "probe_interval": 15,
            "probes": {
                "fail_count": 2,
                "name": "masterprobe",
                "port": 8443,
                "protocol": "tcp"
            },
            "resource_group": "AnsibleOCP",
            "state": "present"
        }
    },
    "msg": "argument frontend_ip_configurations is of type <type 'dict'> and we were u                                                                                                                        nable to convert to list: <type 'dict'> cannot be converted to a list"

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_loadbalancer.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_loadbalancer.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @tstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rusik69** [comment]
did you tried something like this:
frontend_ip_configurations:
        - name: "{{ master_loadbalancer_frontend_pool_name }}"
          public_ip_address: "{{ lb_external_public_ip_name }}"

**Comment by flowerysong** [comment]
I haven't used the module myself, but you're passing in plain dicts for arguments where the documentation calls for a list (of dicts).

```
  - name: create master loadbalancer
    azure_rm_loadbalancer:
      name: "{{ master_loadbalancer_name }}"
      location: westeurope
      resource_group: "{{ resourcegroup_name }}"
      frontend_ip_configurations:
        - name: "{{ master_loadbalancer_frontend_pool_name }}"
          public_ip_address: "{{ lb_external_public_ip_name }}"
      backend_address_pools:
        - name: "{{ master_loadbalancer_backend_pool_name }}"
      probes:
        - name: "{{ master_loadbalancer_probe_name }}"
          fail_count: 2
          protocol: tcp
          port: 8443
      load_balancing_rules:
        - load_distribution: sourceip
          name: "{{ master_loadbalancer_rule_name }}"
          frontend_ip_configuration: "{{ master_frontend_ip_config_name }}"
          probe: "{{ master_loadbalancer_probe_name }}"
          protocol: tcp
          backend_address_pool: "{{ master_loadbalancer_backend_pool_name }}"
          frontend_port: 8443
          backend_port: 8443
```

**Comment by yuwzho** [comment]
@jluyckx93 The load_balancing_rules should be accepted as a list. Could you have a try like the previous comment? I will update the document's example to avoid misunderstanding.

**Comment by jluyckx93** [comment]
@flowerysong @yuwzho Many Thanks ! It is working now !
Also changed the load_balancing_rules: frontend_ip_configuration value to the frontend_ip_configurations name. It should be renamed to frontend_ip_configuration_name like in the inbound_nat_pools. 2 times same value, different names ....
```
  - name: create master loadbalancer
    azure_rm_loadbalancer:
      name: "{{ master_loadbalancer_name }}"
      location: westeurope
      resource_group: "{{ resourcegroup_name }}"
      frontend_ip_configurations:
        - name: "{{ master_loadbalancer_frontend_pool_name }}"
          public_ip_address: "{{ lb_external_public_ip_name }}"
      backend_address_pools:
        - name: "{{ master_loadbalancer_backend_pool_name }}"
      probes:
        - name: "{{ master_loadbalancer_probe_name }}"
          fail_count: 2
          protocol: Tcp
          port: 8443
      load_balancing_rules:
        - load_distribution: SourceIP
          name: "{{ master_loadbalancer_rule_name }}"
          frontend_ip_configuration: "{{ master_loadbalancer_frontend_pool_name }}"
          probe: "{{ master_loadbalancer_probe_name }}"
          protocol: Tcp
          backend_address_pool: "{{ master_loadbalancer_backend_pool_name }}"
          frontend_port: 8443
          backend_port: 8443

```
