### ISSUE TITLE
docker connection to remote containers is broken (probably due to a race condition)

### ISSUE THREAD

**Issue by curldivergence** [ansible/ansible#36698]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

docker connection
##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/home/andrew/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.6.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

No changes. 
##### OS / ENVIRONMENT

Arch Linux
Debian Stretch
Docker version 17.12.0-ce, build c97c6d6
Docker version 18.02.0-ce, build fc4de447b5
##### SUMMARY

When trying to run a simple playbook that creates a docker container on the remote host, adds it to the dynamic inventory and then runs some commands (e. g. facts gathering or apt module) in that container, playbook fails with MODULE_ERROR and quite non-informative output (return code 0, empty stdout/stderr).
A couple of notes that came out after some investigation efforts:
1. The issue emerges only when newly added host is mentioned in a new play (see example below), I didn't manage to reproduce it with the equivalent delegate_to module invocation.
2. It seems that some kind of race condition takes place, because when I run the playbook in pdb, the issue disappears (without any changes made neither to the OS, nor to the playbook, nor ansible itself).
3. I've managed to localize the issue to some extent: in the file "ansible/plugins/connection/docker.py" there is a function exec_command(), which calls subprocess.Popen/communicate. When running the playbook 'as is', communicate() returns empty stdout/stderr (despite having the actual container modifications done), and that is why playbook fails. If something like time.sleep() or p.wait() is inserted between calls to Popen constructor and communicate(), the issue disappears, and the actual stdout is returned and then successfully parsed:
```
215         p = subprocess.Popen(local_cmd, shell=False, stdin=subprocess.PIPE,
216                              stdout=subprocess.PIPE, stderr=subprocess.PIPE)
217         p.wait() # somehow hides the issue
218         stdout, stderr = p.communicate(in_data)

```
##### STEPS TO REPRODUCE

```yaml
---
- hosts: target_machine
  tasks:
  - name: create jenkins container
    docker_container:
      docker_host: 192.168.1.51:4080
      name: my_jenkins
      image: jenkins 
      detach: yes
      tty: yes # needed to keep container running

  - name: add container to inventory
    add_host:
      name: my_jenkins
      groups: my_group
      ansible_connection: docker
      ansible_docker_extra_args: "-H=tcp://192.168.1.51:4080"
      ansible_user: jenkins
    changed_when: false

  # - name: create directory for ssh keys
  #   delegate_to: my_jenkins
  #   file:
  #     path: "/tmp/test_dir"
  #     state: directory

# This section seems to be equivalent to the previous task,
# but if I switch to it instead of 'delegate_to' module,
# the playbook fails
- hosts: my_group
  gather_facts: yes
  connection: docker
  tasks:
    - name: create directory for ssh keys
      file:
        path: "/tmp/test_dir"
        state: directory
```

##### EXPECTED RESULTS

I expect the playbook to succeed (and that happens with the dirty fake fix above):
```
PLAY [target_machine] *********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
 ok: [192.168.1.51]

TASK [create jenkins container] ***********************************************************************************************************************************************************************************
changed: [192.168.1.51]

TASK [add container to inventory] *********************************************************************************************************************************************************************************
ok: [192.168.1.51]

PLAY [my_group] ***************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [my_jenkins]

TASK [create directory for ssh keys] ******************************************************************************************************************************************************************************
changed: [my_jenkins]

PLAY RECAP ********************************************************************************************************************************************************************************************************
192.168.1.51               : ok=3    changed=1    unreachable=0    failed=0   
my_jenkins                 : ok=2    changed=1    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

```
PLAY [target_machine] *********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [192.168.1.51]

TASK [create jenkins container] ***********************************************************************************************************************************************************************************
ok: [192.168.1.51]

TASK [add container to inventory] *********************************************************************************************************************************************************************************
ok: [192.168.1.51]

PLAY [my_group] ***************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
fatal: [my_jenkins]: FAILED! => {"changed": false, "module_stderr": "", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
	to retry, use: --limit @/home/andrew/test.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
192.168.1.51               : ok=3    changed=0    unreachable=0    failed=0   
my_jenkins                 : ok=0    changed=0    unreachable=0    failed=1   

```
