### ISSUE TITLE
Cloudflare DNS does not allow for tls protocol type

### ISSUE THREAD

**Issue by DennisGlindhart** [ansible/ansible#36708]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudflare_dns

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  python version = 2.7.14 (default, Feb 17 2018, 10:42:17) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Cloudflare DNS module does not allow for SRV-records of type tls - only tcp and udp are allowed. Cloudflare also supports tls-type.

##### STEPS TO REPRODUCE

```yaml
- cloudflare_dns:
    domain: my.com
    service: foo
    proto: tls
    port: 3500
    priority: 10
    weight: 20
    type: SRV
    value: fooserver.my.com
```

##### EXPECTED RESULTS
Not failing

##### ACTUAL RESULTS
```
TASK [dns : cloudflare_dns] ***********************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of proto must be one of: tcp,udp, got: tls"}
```
