### ISSUE TITLE
Using gce module, new VM root is formatted ext2 and mounted readonly

### ISSUE THREAD

**Issue by skyler** [ansible/ansible#36703]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`gce`

##### ANSIBLE VERSION
```bash
ansible 2.4.3.0
  config file = /Users/skyler/workspace/ansible/ansible.cfg
  configured module search path = [u'/Users/skyler/dev/ansible/library']
  ansible python module location = /Users/skyler/workspace/ansible/.venv/lib/python2.7/site-packages/ansible
  executable location = /Users/skyler/workspace/ansible/.venv/bin/ansible
  python version = 2.7.12 (default, Oct 23 2016, 11:41:51) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

##### CONFIGURATION
```
[DEPRECATION WARNING]: ACCELERATE_TIMEOUT option, Removing accelerate as a connection method, settings not needed either. . This feature will be removed in version 2.5. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ACCELERATE_DAEMON_TIMEOUT option, Removing accelerate as a connection method, settings not needed either. . This feature will be removed in version 2.5.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ACCELERATE_CONNECT_TIMEOUT option, Removing accelerate as a connection method, settings not needed either. . This feature will be removed in version 2.5.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_SUDO_EXE option, In favor of become which is a generic framework . This feature will be removed in version 2.8. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: DEFAULT_SUDO_USER option, In favor of become which is a generic framework . This feature will be removed in version 2.8. Deprecation warnings can be disabled by
setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: ACCELERATE_PORT option, Removing accelerate as a connection method, settings not needed either. . This feature will be removed in version 2.5. Deprecation warnings
 can be disabled by setting deprecation_warnings=False in ansible.cfg.
ACCELERATE_CONNECT_TIMEOUT(/Users/skyler/workspace/ansible/ansible.cfg) = 5.0
ACCELERATE_DAEMON_TIMEOUT(/Users/skyler/workspace/ansible/ansible.cfg) = 30
ACCELERATE_PORT(/Users/skyler/workspace/ansible/ansible.cfg) = 5099
ACCELERATE_TIMEOUT(/Users/skyler/workspace/ansible/ansible.cfg) = 30
ANSIBLE_NOCOWS(/Users/skyler/workspace/ansible/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/skyler/workspace/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/skyler/workspace/ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o GSSAPIAuthentication=no
CACHE_PLUGIN(/Users/skyler/workspace/ansible/ansible.cfg) = memory
DEFAULT_ACTION_PLUGIN_PATH(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/action_plugins']
DEFAULT_BECOME_METHOD(/Users/skyler/workspace/ansible/ansible.cfg) = sudo
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CALLBACK_WHITELIST(/Users/skyler/workspace/ansible/ansible.cfg) = ['timer', 'profile_tasks']
DEFAULT_CONNECTION_PLUGIN_PATH(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/Users/skyler/workspace/ansible/filter_plugins']
DEFAULT_FORKS(/Users/skyler/workspace/ansible/ansible.cfg) = 15
DEFAULT_GATHERING(/Users/skyler/workspace/ansible/ansible.cfg) = implicit
DEFAULT_HASH_BEHAVIOUR(/Users/skyler/workspace/ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/Users/skyler/workspace/ansible/inventory']
DEFAULT_JINJA2_EXTENSIONS(/Users/skyler/workspace/ansible/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_LOOKUP_PLUGIN_PATH(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/Users/skyler/workspace/ansible/ansible.cfg) = Ansible managed: {file} on {host}
DEFAULT_MODULE_LANG(/Users/skyler/workspace/ansible/ansible.cfg) = C
DEFAULT_MODULE_PATH(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/Users/skyler/dev/ansible/library']
DEFAULT_POLL_INTERVAL(/Users/skyler/workspace/ansible/ansible.cfg) = 15
DEFAULT_PRIVATE_KEY_FILE(/Users/skyler/workspace/ansible/ansible.cfg) = /Users/skyler/workspace/ansible/ansible_key
DEFAULT_REMOTE_TMP(/Users/skyler/workspace/ansible/ansible.cfg) = $HOME/.ansible/tmp
DEFAULT_REMOTE_USER(/Users/skyler/workspace/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/Users/skyler/dev/ansible/roles']
DEFAULT_SUDO_EXE(/Users/skyler/workspace/ansible/ansible.cfg) = sudo
DEFAULT_SUDO_USER(/Users/skyler/workspace/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/Users/skyler/workspace/ansible/ansible.cfg) = 10
DEFAULT_TRANSPORT(/Users/skyler/workspace/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/Users/skyler/workspace/ansible/ansible.cfg) = [u'/usr/share/ansible_plugins/vars_plugins']
DEFAULT_VAULT_PASSWORD_FILE(/Users/skyler/workspace/ansible/ansible.cfg) = /Users/skyler/workspace/ansible/vault_password
RETRY_FILES_ENABLED(/Users/skyler/workspace/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT
``` bash
(.venv) ~/workspace/ansible $ which python
/Users/skyler/workspace/ansible/.venv/bin/python
(.venv) ~/workspace/ansible $ python --version
Python 2.7.12
```

macOS High Sierra 10.13.3 (17D47)

##### SUMMARY
When I create a new GCE VM using the `gce` module, `/` (root) is formatted ext2 and mounted readonly. For example:
```bash
# relevant output of mount:
/dev/dm-0 on / type ext2 (ro,relatime,block_validity,barrier,user_xattr,acl)

$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda       8:0    0   200G  0 disk
├─sda1    8:1    0 195.9G  0 part /mnt/stateful_partition
├─sda2    8:2    0    16M  0 part
├─sda3    8:3    0     2G  0 part
├─sda4    8:4    0    16M  0 part
├─sda5    8:5    0     2G  0 part
├─sda6    8:6    0   512B  0 part
├─sda7    8:7    0   512B  0 part
├─sda8    8:8    0    16M  0 part /usr/share/oem
├─sda9    8:9    0   512B  0 part
├─sda10   8:10   0   512B  0 part
├─sda11   8:11   0     8M  0 part
└─sda12   8:12   0    32M  0 part
sdb       8:16   0    10G  1 disk
```

However, when I create a VM using `gcloud`, using the same image, `/` is formatted ext4 and mounted readwrite, as expected:
```bash
gcloud compute instances create my-cool-vm \
    --project my-cool-project \
    --zone us-east1-d \
    --machine-type n1-standard-16 \
    --image-project=coreos-cloud \
    --image=coreos-stable-1632-3-0-v20180215 \
    --labels foo=bar \
    --tags foo \
    --network default \
    --scopes logging-write,monitoring-write,storage-ro \
    --boot-disk-type pd-ssd \
    --boot-disk-size 200GB \
    --no-boot-disk-auto-delete \
    --metadata environment=production
```
```bash
# relevant output of mount
/dev/sda9 on / type ext4 (rw,relatime,seclabel,data=ordered)
```

##### STEPS TO REPRODUCE
`roles/provision-mariadb/vars/main.yaml`
```yaml
---
gce_vm_metadata: '{"environment": "production"}'
gce_vm_network: default

gce_vm_image_project: coreos-cloud
gce_vm_image: coreos-stable-1632-3-0-v20180215

gce_vm_machine_type: n1-standard-16
gce_vm_boot_disk_size_gb: 200

gce_vm_labels:
  role: mariadb

gce_vm_network_tags: "mariadb"

gce_vm_scopes:
  - logging-write
  - monitoring-write
  - storage-ro
```
`roles/provision-mariadb/tasks/main.yaml`
```yaml
- name: Create a new GCE VM
  gce:
    service_account_email: "{{ gcp_service_account_email }}"
    credentials_file: "{{ gcp_service_account_file }}"
    project_id: "{{ gcp_project_id }}"
    name: "{{ instance_name }}"
    zone: "{{ zone }}"
    metadata: "{{ gce_vm_metadata }}"
    machine_type: "{{ gce_vm_machine_type }}"
    external_projects: "{{ gce_vm_image_project }}"
    image: "{{ gce_vm_image }}"
    tags: "{{ gce_vm_network_tags }}"
    network: "{{ gce_vm_network }}"
    service_account_permissions: "{{ gce_vm_scopes }}"
    persistent_boot_disk: true
    disk_size: "{{ gce_vm_boot_disk_size_gb }}"
    disk_auto_delete: no
    state: present
  register: new_gce
```

##### EXPECTED RESULTS
I expected `/` to be formatted ext4, mounted read/write (`rw`), as is the case when I create a new VM using the `gcloud` program.

##### ACTUAL RESULTS
`/` was formatted ext2, and mounted readonly (`ro`):
```bash
/dev/dm-0 on / type ext2 (ro,relatime,block_validity,barrier,user_xattr,acl)
```
Also, I've no idea what `/dev/dm-0` is.

```bash
me@my-host ~ $ ls -la /dev/dm-0
brw-rw---- 1 root disk 254, 0 Feb 26 03:16 /dev/dm-0
me@my-host ~ $ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda       8:0    0   200G  0 disk
├─sda1    8:1    0 195.9G  0 part /mnt/stateful_partition
├─sda2    8:2    0    16M  0 part
├─sda3    8:3    0     2G  0 part
├─sda4    8:4    0    16M  0 part
├─sda5    8:5    0     2G  0 part
├─sda6    8:6    0   512B  0 part
├─sda7    8:7    0   512B  0 part
├─sda8    8:8    0    16M  0 part /usr/share/oem
├─sda9    8:9    0   512B  0 part
├─sda10   8:10   0   512B  0 part
├─sda11   8:11   0     8M  0 part
└─sda12   8:12   0    32M  0 part
sdb       8:16   0    10G  1 disk
# Is this an LVM volume?
me@my-host ~ $ sudo su
my-host skyler # whoami
root
my-host me # lvs
bash: lvs: command not found
```
