### ISSUE TITLE
pamd list index out of range

### ISSUE THREAD

**Issue by schaten** [ansible/ansible#36700]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
pamd

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
```

##### CONFIGURATION
no changes
##### OS / ENVIRONMENT
I tested this on arch and fedora 27.
##### SUMMARY
Inserting a rule after another rule that happens to be the last one in the pam.d-file causes a list index out of range error.
##### STEPS TO REPRODUCE
- `session   optional  pam_permit.so` is the last line in /etc/pam.d/system-auth
- Run the following playbook:
```
- name: produce an error
  hosts: localhost
  tasks:
    - pamd:
        name: system-auth
        type: session
        control: optional
        module_path: pam_permit.so
        state: after
        new_type: session
        new_control: optional
        new_module_path: pam_sss.so
```
I originally tried to insert a rule after a pam_unix.so - line..
##### EXPECTED RESULTS
New rule ``session         optional        pam_sss.so`` gets inserted at the end of /etc/pam.d/system-auth
##### ACTUAL RESULTS
Big fat error message:
```
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/pamd.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: test
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/test/.ansible/tmp/ansible-tmp-1519600860.51-249642782020219 `" && echo ansible-tmp-1519600860.51-249642782020219="` echo /home/test/.ansible/tmp/ansible-tmp-1519600860.51-249642782020219 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmp6glv1n TO /home/test/.ansible/tmp/ansible-tmp-1519600860.51-249642782020219/pamd.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/test/.ansible/tmp/ansible-tmp-1519600860.51-249642782020219/ /home/test/.ansible/tmp/ansible-tmp-1519600860.51-249642782020219/pamd.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2 /home/test/.ansible/tmp/ansible-tmp-1519600860.51-249642782020219/pamd.py; rm -rf "/home/test/.ansible/tmp/ansible-tmp-1519600860.51-249642782020219/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_BzP49B/ansible_module_pamd.py", line 651, in <module>
    main()
  File "/tmp/ansible_BzP49B/ansible_module_pamd.py", line 627, in main
    new_rule)
  File "/tmp/ansible_BzP49B/ansible_module_pamd.py", line 463, in insert_after_rule
    if (new_rule.rule_type != service.rules[index + 1].rule_type or
IndexError: list index out of range

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_BzP49B/ansible_module_pamd.py\", line 651, in <module>\n    main()\n  File \"/tmp/ansible_BzP49B/ansible_module_pamd.py\", line 627, in main\n    new_rule)\n  File \"/tmp/ansible_BzP49B/ansible_module_pamd.py\", line 463, in insert_after_rule\n    if (new_rule.rule_type != service.rules[index + 1].rule_type or\nIndexError: list index out of range\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
Best,
Philip

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/pamd.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/pamd.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kevensen
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by aboe76** [comment]
I can confirm this error on ansible 2.4.3.0 on RHEL 7.4
```
- hosts: all
  gather_facts: False
  tasks:
    # enforce tty logging pam
    - name: ensure tty logging
      pamd:
        name: password-auth-ac
        type: session
        control: required
        module_path: pam_unix.so
        state: after
        new_type: session
        new_control: required
        new_module_path: pam_tty_audit.so
        module_arguments: 'enable=*'
      tags: pam_tty_audit
```
```
fatal: [XXXXX]: FAILED! => {
    "changed": false, 
    "module_stderr": "Shared connection to xxx.xxx.xx closed.\r\n", 
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/tmp/ansible_Pszwy1/ansible_module_pamd.py\", line 651, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Pszwy1/ansible_module_pamd.py\", line 627, in main\r\n    new_rule)\r\n  File \"/tmp/ansible_Pszwy1/ansible_module_pamd.py\", line 463, in insert_after_rule\r\n    if (new_rule.rule_type != service.rules[index + 1].rule_type or\r\nIndexError: list index out of range\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
