### ISSUE TITLE
postgresql_privs: trace "'str' object is not callable" on errors from postgres

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#36716]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
modules/database/postgresql/postgresql_privs.py
##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/amarao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14+ (default, Feb  6 2018, 19:12:18) [GCC 7.3.0]

```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=10s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%r
DEFAULT_SUDO_FLAGS(/etc/ansible/ansible.cfg) = -H -S
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
Ubuntu 18.04 x86_64.

##### SUMMARY
If postgres complains that schema not exist (postgres message: "schema "opt" does not exist"), module traces with following backtrace:

##### STEPS TO REPRODUCE
It's hard to reproduce, you need to try to set permissions for non-existing schema in postgres.

Snippet of my code:
```yaml
- name: Granting schema priveleges
  become: yes
  become_user: postgres
  postgresql_privs:
    state: present
    role: "oheruser"
    privs: "USAGE"
    type: schema
    objs: "common, opts"
    database: 'somedatabase'
```
##### EXPECTED RESULTS
Normal error message: `schema "opt" does not exist`.

##### ACTUAL RESULTS

```
Traceback (most recent call last):
  File "/tmp/ansible_WYVFOi/ansible_module_postgresql_privs.py", line 673, in <module>
    main()
  File "/tmp/ansible_WYVFOi/ansible_module_postgresql_privs.py", line 662, in main
    msg = to_text(e.message(encoding=conn.encoding))
TypeError: 'str' object is not callable
```

I belive it happens in this piece of code:
```
    except psycopg2.Error as e:
        conn.rollback()
        # psycopg2 errors come in connection encoding
        msg = to_text(e.message(encoding=conn.encoding))
        module.fail_json(msg=msg)
```
`e.message` is a str, not an object to call.
