### ISSUE TITLE
with_nested doesn't support more than one variable...

### ISSUE THREAD

**Issue by seanosh** [ansible/ansible#3671]
Attempted against `devel` and tag `v1.2.1`... 

``` yaml
- hosts: web
  vars:
    - nested_list_1:
      - alpha
      - bravo
      - charlie
    - nested_listed_2:
      - delta
      - echo
      - foxtrot
  tasks: 
    - name: print my nested lists!
      shell: >
        echo "nested test a={{ item[0] }} b={{ item[1] }}"
      with_nested:
        - nested_list_1
        - nested_list_2
```

Ends up outputting:

```
changed: [myhost.com] => (item=['alpha', 'n'])
changed: [myhost.com] => (item=['alpha', 'e'])
changed: [myhost.com] => (item=['alpha', 's'])
changed: [myhost.com] => (item=['alpha', 't'])
changed: [myhost.com] => (item=['alpha', 'e'])
changed: [myhost.com] => (item=['alpha', 'd'])
changed: [myhost.com] => (item=['alpha', '_'])
changed: [myhost.com] => (item=['alpha', 'l'])
changed: [myhost.com] => (item=['alpha', 'i'])
changed: [myhost.com] => (item=['alpha', 's'])
changed: [myhost.com] => (item=['alpha', 't'])
changed: [myhost.com] => (item=['alpha', '_'])
changed: [myhost.com] => (item=['alpha', '2'])
changed: [myhost.com] => (item=['bravo', 'n'])
changed: [myhost.com] => (item=['bravo', 'e'])
changed: [myhost.com] => (item=['bravo', 's'])
changed: [myhost.com] => (item=['bravo', 't'])
```

Almost as if the 2nd list in `with_nested` is being treated as a literal string instead of a var...
