### ISSUE TITLE
ansible tasks continue to run when both any_errors_fatal and force_handlers are set to True and a task in handler has failed

### ISSUE THREAD

**Issue by qduxiaoliang** [ansible/ansible#36772]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

any_errors_fatal
force_handlers

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]

```

##### CONFIGURATION

# ansible-config dump --only-changed
[root@sui kvm]# ansible-config dump --only-changed
ANSIBLE_SSH_CONTROL_PATH(/opt/test/ansible.cfg) = %(direct
DEFAULT_FORCE_HANDLERS(/opt/test/ansible.cfg) = False
DEFAULT_GATHERING(/opt/test/ansible.cfg) = explicit
DEFAULT_LOG_PATH(/opt/test/ansible.cfg) = /opt/PlexView/EL
DEFAULT_REMOTE_USER(/opt/test/ansible.cfg) = root
DEFAULT_TIMEOUT(/opt/test/ansible.cfg) = 30
DEPRECATION_WARNINGS(/opt/test/ansible.cfg) = False
HOST_KEY_CHECKING(/opt/test/ansible.cfg) = False

##### OS / ENVIRONMENT

# rpm -qa | grep release
redhat-release-server-6Server-6.9.0.4.el6.x86_64

##### SUMMARY

when any_errors_fatal and force_handlers are both set to True, the task in play after the failed task continues to run even if the task in handler failed

##### STEPS TO REPRODUCE

1. prepare two Linux hosts A and B
2. create the file '/tmp/handlers.sh' with file permission mode 0755 in host A

#!/bin/bash
/bin/true

3. create the file '/tmp/handlers.sh' with file permission mode 0755 in host b

#!/bin/bash
/bin/false

4. run the below command using the yaml snippet below:
ansible-playbook -c paramiko -i inventory/hosts dd.yml

```yaml
# cat dd.yml
---
- name: play one
  hosts: allvm
  remote_user: root
  any_errors_fatal: True
  force_handlers: True
  tasks:
    - name: task one
      command: /bin/true
      notify: handler one
  handlers:
    - name: handler one
      command: /tmp/handler.sh
    - name: handler two
      command: /bin/true

- name: play two
  hosts: allvm
  remote_user: root
  any_errors_fatal: True
  force_handlers: True
  tasks:
    - name: task two
      command: /bin/true

```

##### EXPECTED RESULTS

the task named 'task two' stops to run

##### ACTUAL RESULTS

the task named 'task two' continued to run

```

# ansible-playbook -c paramiko -i ../../inventory/hosts dd.yml

PLAY [play one] ***************************************************************************************************************

TASK [task one] ***************************************************************************************************************
changed: [3501::7:200:yyyy]
changed: [3501::7:200:xxxx]

RUNNING HANDLER [handler one] *************************************************************************************************
changed: [3501::7:200:yyyy]
fatal: [3501::7:200:xxxx]: FAILED! => {"changed": true, "cmd": ["/tmp/handler.sh"], "delta": "0:00:00.004729", "end": "2018-02-27 15:56:54.562564", "msg": "non-zero return code", "rc": 1, "start": "2018-02-27 15:56:54.557835", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

PLAY [play two] ***************************************************************************************************************

TASK [task two] ***************************************************************************************************************
changed: [3501::7:200:yyyy]

        to retry, use: --limit @/opt/test/dd.retry

PLAY RECAP ********************************************************************************************************************
3501::7:200:xxxx           : ok=3    changed=3    unreachable=0    failed=0
3501::7:200:xxxx           : ok=1    changed=1    unreachable=0    failed=1

```

**Comment by ansibot** [comment]
Files identified in the description:
* [test/integration/targets/any_errors_fatal/18602.yml](https://github.com/ansible/ansible/blob/devel/test/integration/targets/any_errors_fatal/18602.yml)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
My local setup seems to be fine, here is what I used to run it

```
# inventory.ini
[group]
host1  ansible_host=127.0.0.1  ansible_connection=local skip_fail=True
host2  ansible_host=127.0.0.1 ansible_connection=local skip_fail=False

# playbook
---
- hosts: group
  gather_facts: no
  any_errors_fatal: yes
  force_handlers: yes
  handlers:
  - name: handler one
    shell: exit 0

  tasks:
  - name: ok command
    shell: exit 0
    notify: handler one

  - shell: exit 1
    when: not skip_fail

- hosts: group
  gather_facts: no
  tasks:
  - name: 2nd play command
    shell: exit 0
```

When running on 2.4.2.0 here is the results

```
(ansible-py36) jborean:~/dev/module-tester$ ansible-playbook adhoc.yml -i test-ini.ini -vv
ansible-playbook 2.4.2.0
  config file = /Users/jborean/dev/module-tester/ansible.cfg
  configured module search path = ['/Users/jborean/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jborean/venvs/ansible-py36/lib/python3.6/site-packages/ansible
  executable location = /Users/jborean/venvs/ansible-py36/bin/ansible-playbook
  python version = 3.6.4 (default, Jan 18 2018, 12:35:18) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Using /Users/jborean/dev/module-tester/ansible.cfg as config file

PLAYBOOK: adhoc.yml **************************************************************************************************************************************************************************************************************************************************************************************************
2 plays in adhoc.yml

PLAY [group] *********************************************************************************************************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [ok command] ****************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/jborean/dev/module-tester/adhoc.yml:11
NOTIFIED HANDLER handler one
changed: [host1] => {"changed": true, "cmd": "exit 0", "delta": "0:00:00.173103", "end": "2018-03-01 08:13:24.966267", "rc": 0, "start": "2018-03-01 08:13:24.793164", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
NOTIFIED HANDLER handler one
changed: [host2] => {"changed": true, "cmd": "exit 0", "delta": "0:00:00.173003", "end": "2018-03-01 08:13:24.966244", "rc": 0, "start": "2018-03-01 08:13:24.793241", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [command] *******************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/jborean/dev/module-tester/adhoc.yml:15
skipping: [host1] => {"changed": false, "skip_reason": "Conditional result was False"}
fatal: [host2]: FAILED! => {"changed": true, "cmd": "exit 1", "delta": "0:00:00.161506", "end": "2018-03-01 08:13:25.463765", "msg": "non-zero return code", "rc": 1, "start": "2018-03-01 08:13:25.302259", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

NO MORE HOSTS LEFT ***************************************************************************************************************************************************************************************************************************************************************************************************

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************************************************
host1                      : ok=1    changed=1    unreachable=0    failed=0   
host2                      : ok=1    changed=1    unreachable=0    failed=1 
```

This is what I would expect, after the 2nd shell task fails on host2, the play and any subsequent plays stops due to the presence of `any_errors_fatal: yes`. Even the handlers are not run because the play is seen as fatal.

Are you able to try out my repro and see if the issue may only occur when dealing with remote hosts?

needs_info

**Comment by alikins** [comment]
Similar to https://github.com/ansible/ansible/issues/18602

**Comment by qduxiaoliang** [comment]
`[root@sun kvm]# cat inventory/hosts
[allvm]
10.223.0.232
10.223.0.233
[root@sun kvm]# cat dd.yml
---
- name: play one
  hosts: allvm
  remote_user: root
  any_errors_fatal: True
  force_handlers: True
  tasks:
    - name: task one
      command: /bin/true
      notify: handler one
  handlers:
    - name: handler one
      command: /tmp/handler.sh
    - name: handler two
      command: /bin/true

- name: play two
  hosts: allvm
  remote_user: root
  any_errors_fatal: True
  force_handlers: True
  tasks:
    - name: task two
      command: /bin/true
`

**Comment by qduxiaoliang** [comment]
``
[root@sun kvm]# cat inventory/hosts
[allvm]
10.223.0.232
10.223.0.233
[root@sun kvm]# cat dd.yml
---
- name: play one
  hosts: allvm
  remote_user: root
  any_errors_fatal: True
  force_handlers: True
  tasks:
    - name: task one
      command: /bin/true
      notify: handler one
  handlers:
    - name: handler one
      command: /tmp/handler.sh
    - name: handler two
      command: /bin/true

- name: play two
  hosts: allvm
  remote_user: root
  any_errors_fatal: True
  force_handlers: True
  tasks:
    - name: task two
      command: /bin/true
``

**Comment by qduxiaoliang** [comment]
```
# cat inventory/hosts
[allvm]
10.223.0.232
10.223.0.233
# cat dd.yml
---
- name: play one
  hosts: allvm
  remote_user: root
  any_errors_fatal: True
  force_handlers: True
  tasks:
    - name: task one
      command: /bin/true
      notify: handler one
  handlers:
    - name: handler one
      command: /tmp/handler.sh
    - name: handler two
      command: /bin/true

- name: play two
  hosts: allvm
  remote_user: root
  any_errors_fatal: True
  force_handlers: True
  tasks:
    - name: task two
      command: /bin/true
```
