### ISSUE TITLE
vmware_vsan_cluster:host cannot communicate with one or more another hosts in the vSAN enabled  cluster 

### ISSUE THREAD

**Issue by arjunprakashn** [ansible/ansible#36776]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

vmware_vsan_cluster

##### ANSIBLE VERSION

```
ansible 2.5.0a1
```

##### STEPS TO REPRODUCE

```
    - name: Configure VSAN on first host
      vmware_vsan_cluster:
         hostname: 10.243.1.43
         username: root
         password: PASSW0RD
         validate_certs: no
      register: vsan_cluster

    - name: Configure VSAN on remaining hosts
      vmware_vsan_cluster:
         hostname: '{{item}}'
         username: root
         password: PASSW0RD
#         cluster_uuid: "{{ vsan_cluster.cluster_uuid }}"
         validate_certs: no
      with_items: ['10.243.1.44','10.243.1.45','10.243.1.46']




```

##### EXPECTED RESULTS

vsan configuration successfully configured on all hosts

##### ACTUAL RESULTS

host cannot communicate with one or more another hosts in the  vSAN enabled  cluster

```
 TASK [Configure VSAN on first host] **********************************************************************************************************
changed: [127.0.0.1] => {"changed": true, "cluster_uuid": "52ddbe77-5988-9b0f-01a7-0749f56985b3", "failed": false, "result": null}

TASK [Configure VSAN on remaining hosts] *****************************************************************************************************
changed: [127.0.0.1] => (item=10.243.1.44) => {"changed": true, "cluster_uuid": "5228427f-f9e9-10c2-6d11-a5c395b79c4b", "failed": false, "item": "10.243.1.44", "result": null}
changed: [127.0.0.1] => (item=10.243.1.45) => {"changed": true, "cluster_uuid": "5228427f-f9e9-10c2-6d11-a5c395b79c4b", "failed": false, "item": "10.243.1.45", "result": null}
changed: [127.0.0.1] => (item=10.243.1.46) => {"changed": true, "cluster_uuid": "5228427f-f9e9-10c2-6d11-a5c395b79c4b", "failed": false, "item": "10.243.1.46", "result": null}

PLAY RECAP ***********************************************************************************************************************************
127.0.0.1                  : ok=2    changed=2    unreachable=0    failed=0     

```
