### ISSUE TITLE
unable to specify NIC teaming type while creating port group on vswitch on ESXI host

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#36773]
##### ISSUE TYPE

 - Bug Report
 

##### COMPONENT NAME

```
vmware_portgroup
```
##### ANSIBLE VERSION

```
2.5.0a1
```

##### SUMMARY

```
  while creating portgroup on vswitch i want specify NIC teaming policy but current module implementation doesnt have that facility, same facility is present for vmware_dvs_portgroup module
```
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by Akasurde** [comment]
@umrikar Thanks for reporting this issue.

**Comment by ansibot** [comment]
cc @akasurde @dav1x @jctanner @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr #36778

**Comment by umrikar** [comment]
@Akasurde...  Thanks, Its resolved_by_pr #36778

**Comment by umrikar** [comment]
will it be integrated in ansible 2.6

**Comment by umrikar** [comment]
i am able to create port group with patch but idem potency is lost..if i try to create same port group i get below error
 "msg": "Failed to update Portgroup as VLAN id was not correct as per specifications: A specified parameter was not correct: Vim.Host.PortGroup.Specification.name

**Comment by Akasurde** [comment]
@umrikar Could you please provide playbook details and `-vvvv` output ? 

needs_info

**Comment by umrikar** [comment]
Hi,
 when i try to updated vlanid for created port group.i am getting below error

```
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [127.0.0.1] *****************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [127.0.0.1]

TASK [Add Management Network VM Portgroup] ***************************************************************************************************
fatal: [127.0.0.1 -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to update Portgroup as VLAN id was not correct as per specifications: A specified parameter was not correct: Vim.Host.PortGroup.Specification.name"}
	to retry, use: --limit @/home/lenovo/create_portgroup.retry

PLAY RECAP ***********************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by umrikar** [comment]
i created portgroup with vlan_id as 1 earlier and tried to update it with  vlan_id=2 . below is playbook

```yaml
---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Add Management Network VM Portgroup
      local_action:
        module: vmware_portgroup
        hostname: 10.243.1.45
        hosts: 10.243.1.45
        username: root
        password: PASSW0RD
        switch_name: vSwitch0
        portgroup_name: vmtest4
        teaming_policy:
            load_balance_policy: 'loadbalance_srcmac'
        vlan_id: 2
        validate_certs: no
```
