### ISSUE TITLE
ERROR! 'yum_repository' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by kg4giy** [ansible/ansible#36794]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

yum_respository command

##### ANSIBLE VERSION

```

[ec2-user@ip-172-31-57-185 packer]$ ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

[ec2-user@ip-172-31-57-185 packer]$ ansible-config dump --only-changed
[DEPRECATION WARNING]: ANSIBLE_HOSTS option, The variable is misleading as it can be a list of hosts and/or paths to
inventory sources . This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
DEFAULT_HOST_LIST(env: ANSIBLE_HOSTS) = [u'/etc/ansible/ec2.py']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
##### OS / ENVIRONMENT

Linux ip-172-31-57-185.ec2.internal 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

Error:

[ec2-user@ip-172-31-57-185 packer]$ ansible-playbook ec2docker-add.yml --check
[DEPRECATION WARNING]: ANSIBLE_HOSTS option, The variable is misleading as it can be a list of hosts and/or paths to
inventory sources . This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ERROR! 'yum_repository' is not a valid attribute for a Play

The error appears to have been in '/home/ec2-user/packer/ec2docker-add.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Add repository
  ^ here

YML:

[ec2-user@ip-172-31-57-185 packer]$ cat ec2docker-add.yml
---

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/

Yes, this is the default YML from: http://docs.ansible.com/ansible/latest/yum_repository_module.html what I had before was also throwing errors. 

##### STEPS TO REPRODUCE

Pretty straight forward. It does not pass the check and is listed as invalid. But using it anywhere also come with the same error. 

```yaml
---

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#    - copy:
#        content: |
#                 https://storebits.docker.com/ee/centos/sub-f2e4cbac-de13-47ab-a2ad-28d676b44a4a
#        dest: /etc/yum/vars/dockerurl
#
#     - name: install docker support packages
#       yum:
#         name: yum-utils device-mapper-persistent-data lvm2
#
#    - name: upgrade all packages
#      yum:
#        name: '*'
#        state: latest

```

##### EXPECTED RESULTS

I expect to pass the check.

##### ACTUAL RESULTS

```
[ec2-user@ip-172-31-57-185 packer]$ ansible-playbook ec2docker-add.yml --check
[DEPRECATION WARNING]: ANSIBLE_HOSTS option, The variable is misleading as it can be a list of hosts and/or paths to
inventory sources . This feature will be removed in version 2.8. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
ERROR! 'yum_repository' is not a valid attribute for a Play

The error appears to have been in '/home/ec2-user/packer/ec2docker-add.yml': line 3, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Add repository
  ^ here
```
