### ISSUE TITLE
Failed to validate the SSL certificate (SSL: CERTIFICATE_VERIFY_FAILED)

### ISSUE THREAD

**Issue by artmatsak** [ansible/ansible#36791]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

digital_ocean_tag

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /Users/amatsak/.ansible.cfg
  configured module search path = [u'/Users/amatsak/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/ansible
  executable location = /opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/ansible
  python version = 2.7.14 (default, Sep 27 2017, 12:15:00) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/Users/amatsak/.ansible.cfg) = [u'/Users/amatsak/hosts']
HOST_KEY_CHECKING(/Users/amatsak/.ansible.cfg) = False

##### OS / ENVIRONMENT

Running from macOS 10.13.3, command delegated to localhost

##### SUMMARY

The command fails with a CERTIFICATE_VERIFY_FAILED error. I'm also experiencing the same error with other commands, e.g. `uri`, no matter which URL I'm trying to connect to.

The "paths checked for this platform" are weird. I don't have CA certificates in any of /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl.

##### STEPS TO REPRODUCE

```yaml
- name: launch a new droplet
  hosts: localhost
  connection: local
  #...

  tasks:
    #...
    - name: tag the new droplet
      digital_ocean_tag:
        name: "{{ item }}"
        state: present
        resource_id: "{{ droplet.droplet.id }}"
        api_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
      with_items:
        - ansible
        - "{{ role }}"
```

##### EXPECTED RESULTS

The command is executed successfully.

##### ACTUAL RESULTS

```
failed: [localhost] (item=ansible) => {"changed": false, "item": "ansible", "msg": "Failed to validate the SSL certificate for api.digitalocean.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)."}
```
