### ISSUE TITLE
Support vars_files when using import_playbook

### ISSUE THREAD

**Issue by juzsal** [ansible/ansible#36806]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

import_playbook

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /opt/rhel-ansible/ansible.cfg
  configured module search path = [u'/home/jsalmon/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/opt/rhel-ansible/ansible.cfg) = [u'/opt/rhel-ansible/inventory/dev/hosts.base']
DEFAULT_ROLES_PATH(/opt/rhel-ansible/ansible.cfg) = [u'/opt/rhel-ansible/roles']
```

##### OS / ENVIRONMENT

RHEL 7.4

##### SUMMARY

Currently it is not possible to use `vars_files` to import variables when using `import_playbook`. It would be useful for my use case to be able to do this, as I am combining a third-party playbook with a custom inventory file, where the custom inventory file contains placeholders for common variables.

I can use `vars` with `import_playbook`, but this means that I cannot leverage my existing common variables and would need to duplicate them.

##### STEPS TO REPRODUCE

```yaml
$ cat inventory/common_variables.yml
... snip ...
env_http_proxy: 'http://proxy.example.org'
... snip ...

$ cat playbooks/openshift/deploy-cluster.yml
---
- import_playbook: ../third-party/openshift-ansible/playbooks/byo/config.yml
  vars_files:
   - ../../inventory/common_variables.yml

$ cat inventory/dev/hosts.openshift
... snip ...
openshift_http_proxy={{ env_http_proxy }}
... snip ...
```

##### EXPECTED RESULTS

I would expect that the above should be possible.

##### ACTUAL RESULTS

```
$ sudo ansible-playbook playbooks/openshift/deploy-cluster.yml -i inventory/dev/hosts.openshift
[sudo] password for jsalmon:
ERROR! 'vars_files' is not a valid attribute for a PlaybookInclude

The error appears to have been in '/opt/rhel-ansible/playbooks/openshift/deploy-cluster.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- import_playbook: ../third-party/openshift-ansible/playbooks/byo/config.yml
  ^ here
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/import_playbook.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/import_playbook.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by naphta** [comment]
Any update on this issue? Is there something core blocking the implementation of this feature?

I'm happy to have a look at implementing it if there's nothing specific holding it back which I'm unaware of.

**Comment by stawii** [comment]
I would love to see this also in `include_role` and maybe for all other tasks/actions.
I don't see a reason why is this feature is limited only for plays.
There are many vars that are global enough to pass them here and there without need to copy-paste, but not so generic to put them inside inventory itself or extra_vars.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/import_playbook.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/import_playbook.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Ramblurr** [comment]
There definitely seems to be an inconsistency that `vars` is allowed but not `vars_files`

**Comment by NonLogicalDev** [comment]
I would also second this, I feel like `import_roles/playbooks/tasks` allowing `vars_files` would make a huge quality of life improvement, as they will allow users to treat `import_*` as sort of function like blocks.

For example, you could then easily do: (somewhat contrived example)
```
- name: Setup telegraf service
   import_role: name="example/telegraf"
   vars_files:
     - vars/telegraf.yml
- name: Setup telegraf auxillary service
  import_role: name="example/telegraf"
  vars_files:
    - vars/telegraf-aux.yml
```

At the moment the closest you can come to that simplicity is (if you want the tags to work correctly)
```
    - name: TELEGRAF | Install and Configure Telegraf
      tags: [ telegraf, sometag ]
      block:
        - include_vars: telegraf.yml
           tags: [ telegraf, sometag ]
        - include_role: name="example/telegraf"
           tags: [ telegraf, sometag ]
           apply:
             tags: [ telegraf, sometag ]
```
