### ISSUE TITLE
openssl_certificate fails to write Let's Encrypt signed cert with Python 3

### ISSUE THREAD

**Issue by jdoss** [ansible/ansible#36825]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openssl_certificate

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = ./ansible.cfg
  configured module search path = [u'~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan 17 2018, 14:28:32) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### OS / ENVIRONMENT

Fedora 27 Workstation 
Fedora 27 Server (Target)

##### SUMMARY
Generating a Let's Encrypt cert fail when using `ansible_python_interpreter=/usr/bin/python3`

##### STEPS TO REPRODUCE
Generate a Let's Encrypt Certificate 

```yaml
- name: Generate a Let's Encrypt Certificate
  openssl_certificate:
    path: /etc/ssl/crt/ansible.com.crt
    csr_path: /etc/ssl/csr/ansible.com.csr
    provider: acme
    acme_accountkey: /etc/ssl/private/ansible.com.pem
    acme_challenge_path: /etc/ssl/challenges/ansible.com/

```

##### EXPECTED RESULTS

A signed SSL cert written to a file. 

##### ACTUAL RESULTS
```

fatal: [server]: FAILED! => {"changed": false, "module_stderr": "Parsing account key...\nParsing CSR...\nRegistering account...\nAlready registered!\nVerifying cdn1.transistor.fm...\ncdn1.transistor.fm verified!\nSigning certificate...\nCertificate signed!\nTraceback (most recent call last):\n  File \"/tmp/ansible_1ezavkpq/ansible_module_openssl_certificate.py\", line 808, in <module>\n    main()\n  File \"/tmp/ansible_1ezavkpq/ansible_module_openssl_certificate.py\", line 787, in main\n    certificate.generate(module)\n  File \"/tmp/ansible_1ezavkpq/ansible_module_openssl_certificate.py\", line 692, in generate\n    certfile.write(str(crt))\nTypeError: a bytes-like object is required, not 'str'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

```

Installing Python 2 and the following modules on the target server fixes the issue.

`dnf install -y python2 python2-dnf libselinux-python python-pyOpenSSL`
