### ISSUE TITLE
Complex vars_files aren't merged

### ISSUE THREAD

**Issue by boosh** [ansible/ansible#3683]
I have a play with:

``` yml
  vars_files:
    - vars/all.yml
    - vars/$env.yml           # include the env-specific variables (e.g. dev01.yml)
```

vars/all.yml contains:

``` yml
# defaults for all envs
aws:
  region: eu-west-1
  instance_type: t1.micro
```

and vars/dev01.yml contains:

``` yml
aws:
  keypair: dev01
```

It seems ansible doesn't merge the two 'aws' dicts together to produce a larger dict as I'd expect, but instead overwrites it completely, so in my play I can't reference `${aws.region}` after loading vars/dev01.yml.
