### ISSUE TITLE
High memory consumption in loops and includes

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#36849]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core - Loops

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/agil/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/agil/Envs/iluvatar/local/lib/python2.7/site-packages/ansible
  executable location = /home/agil/Envs/iluvatar/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
All by default

##### OS / ENVIRONMENT
Linux agil 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY
We've detected a very high memory usage when mixing includes and loops. In a real production situation with more than 200 hosts this memory issue can consume up to 100GB (including swap memory).  

##### STEPS TO REPRODUCE
`test.yml`:
```yaml
- hosts: localhost
  connection: local
  vars:
    mega_list: "{{ range(200) | list }}"
  tasks:
    - include_tasks: print.yml
      vars:
        message: "{{ item }}"
      with_items: "{{ mega_list }}"

    - include_tasks: print.yml
      vars:
        message: "{{ item }}"
      with_items: "{{ mega_list }}"
```

`print.yml`:
```yaml
- shell: echo "{{ message }}"
  register: echo_msg

- debug: msg="{{ echo_msg.stdout }}"

```

##### EXPECTED RESULTS
Same memory consumption in both include_tasks.

##### ACTUAL RESULTS
![memory_usage](https://user-images.githubusercontent.com/19267950/36790976-cd1602fa-1c96-11e8-9f08-1cc227f8d460.jpg)
Memory consume up to 2GB doing basic tasks.
gif: https://gifs.com/gif/BLvXX2

#### Workaround

This doesn't increase memory consumption:
```yaml
- hosts: localhost
  connection: local
  vars:
    mega_list: "{{ range(200) | list }}"
  tasks:
    - include_tasks: print.yml
      vars:
        message: "{{ item }}"
      with_items: "{{ mega_list }}"

- hosts: localhost
  connection: local
  vars:
    mega_list: "{{ range(200) | list }}"
  tasks:
    - include_tasks: print.yml
      vars:
        message: "{{ item }}"
      with_items: "{{ mega_list }}"
```
