### ISSUE TITLE
Network facts return documentation

### ISSUE THREAD

**Issue by jmcgill298** [ansible/ansible#36867]
##### ISSUE TYPE
 - Documentation Report

##### ANSIBLE VERSION

```
N/A
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Documentation does not explain that return values are nested under `ansible_facts`

##### STEPS TO REPRODUCE

N/A

```yaml
N/A
```

##### EXPECTED RESULTS

I expected to have to register the results and then access the key/value pairs directly under my register value.
Expected:
```yaml
- ios_facts:
    register: "facts_data"

- debug:
    var: ios_facts.ansible_net_config
```
The above debug var actually requires `ios_facts.ansible_facts.ansible_net_config`, but is also not needed as the facts module adds the key/value pairs to hostvars. The Ansible way would be to just use `ansible_net_config`.

Suggest adding documentation that explains the return values are part of `ansible_facts` and how `ansible_facts` behaves:
```
"Common return values are documented here Return Values, the following are the fields are returned as part of ansible_facts, which do not require registering returns and automatically added to hostvars:
```

Suggest updating examples to include an example of using the return data:
```
- name: GATHER CONFIG DATA
  ios_facts:
    gather_subset:
      - "config"

- name: ENSURE OUTPUT DIRECTORY EXISTS
  file:
    state: "direcotry"
    path: "./project/output/configs"

- name: WRITE BACKUP TO FILE
  copy:
        content: "{{ ansible_net_config }}"
        dest: ""./project/output/configs/{{ inventory_hostname }}.cfg"
```
##### ACTUAL RESULTS

```

```
