### ISSUE TITLE
Network docs: network_working_with_command_output interface speed example

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#36906]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
ios_interface

##### ANSIBLE VERSION
```
2.5.0
```

##### SUMMARY

On http://docs.ansible.com/ansible/devel/network/user_guide/network_working_with_command_output.html @IPvSean suggested we should add some examples of `gt` with `rt_rate` & `tx_rate`

```yaml
- name: Ensure interface is up and link speed has been negotiated
  eos_interface:
    name: ethernet1
    state: up
    tx_rate: ge(0)
    rx_rate: ge(0)
```

Can be post-2.5, though once done should be cherry-picked into `stable-2.5`
