### ISSUE TITLE
Cannot create openshift template instances "the server could not find the requested resource"

### ISSUE THREAD

**Issue by twhiston** [ansible/ansible#36900]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openshift_raw

##### ANSIBLE VERSION
```
ansible 2.5.0rc1 (stable-2.5 a275a39299) last updated 2018/03/01 10:17:36 (GMT +200)
  config file = /Users/twhiston/.ansible.cfg
  configured module search path = [u'/Users/twhiston/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/devel/lib/ansible
  executable location = /usr/local/Cellar/ansible/devel/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Template instances cannot be created due to the error `"Failed to create object: the server could not find the requested resource"`

##### STEPS TO REPRODUCE
```yaml
- name: Create Template Instance
  openshift_raw:
    host: "{{ openshift_host }}"
    api_key: "{{ oc_token }}"
    verify_ssl: "{{ verify_ssl }}"
    state: present
    namespace: "{{ project_name }}"
    name: stunnel
    definition: "{{ lookup('template', '../files/template_instance.yml') | from_yaml }}"
```
template_instance.yml
```yaml
kind: TemplateInstance
apiVersion: "v1"
metadata:
  name: "{{ service_name }}"
  namespace: "{{ project_name }}"
spec:
  secret:
    name: "{{ service_name }}-settings"
  template: {{ lookup('file', 'template.yml') | from_yaml }}
```

The actual template file that is included can be as simple as you like, even a single basic object such as a secret will cause the error to occur

##### EXPECTED RESULTS
Template instance is created

##### ACTUAL RESULTS

```
The full traceback is:
  File "/var/folders/fs/8mwd9rjn6rn3sh22s9tqf4qc0000gp/T/ansible_NAIM1H/ansible_modlib.zip/ansible/module_utils/k8s/raw.py", line 168, in _create
    k8s_obj = self.helper.create_object(namespace, body=request_body)
  File "/Users/twhiston/Library/Python/2.7/lib/python/site-packages/openshift/helper/base.py", line 272, in create_object
    raise self.get_exception_class()(msg, status=exc.status)

...
"msg": "Failed to create object: the server could not find the requested resource"

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/openshift/openshift_raw.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/openshift/openshift_raw.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @sdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by chouseknecht** [comment]
@twhiston 

I encountered the same error until I upgraded to `minishift 1.13.1`, which includes `OpenShift 3.7.1`.  `TemplateInstance` was introduced in `3.7`

Now I'm getting the same error reported on https://github.com/kubernetes-client/python/issues/464, where it fails to deserialize the API response.

The exact error is:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: Invalid value for `raw`, must not be `None`
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/k2/6n02wx653dx3d028jfjkc1tc0000gn/T/ansible_6lIO4v/ansible_module_openshift_raw.py\", line 204, in <module>\n    main()\n  File \"/var/folders/k2/6n02wx653dx3d028jfjkc1tc0000gn/T/ansible_6lIO4v/ansible_module_openshift_raw.py\", line 200, in main\n    OpenShiftRawModule().execute_module()\n  File \"/var/folders/k2/6n02wx653dx3d028jfjkc1tc0000gn/T/ansible_6lIO4v/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 122, in execute_module\n  File \"/var/folders/k2/6n02wx653dx3d028jfjkc1tc0000gn/T/ansible_6lIO4v/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 198, in _create\n  File \"/var/folders/k2/6n02wx653dx3d028jfjkc1tc0000gn/T/ansible_6lIO4v/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 171, in _create\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/openshift/helper/base.py\", line 264, in create_object\n    create_method(namespace, body=body)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/openshift/client/apis/template_openshift_io_v1_api.py\", line 265, in create_namespaced_template_instance\n    (data) = self.create_namespaced_template_instance_with_http_info(namespace, body, **kwargs)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/openshift/client/apis/template_openshift_io_v1_api.py\", line 350, in create_namespaced_template_instance_with_http_info\n    collection_formats=collection_formats)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 321, in call_api\n    _return_http_data_only, collection_formats, _preload_content, _request_timeout)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 163, in __call_api\n    return_data = self.deserialize(response_data, response_type)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 236, in deserialize\n    return self.__deserialize(data, response_type)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/openshift/client/api_client.py\", line 17, in _ApiClient__deserialize\n    return super(ApiClient, self).__deserialize_model(data, klass)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 620, in __deserialize_model\n    kwargs[attr] = self.__deserialize(value, attr_type)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/openshift/client/api_client.py\", line 17, in _ApiClient__deserialize\n    return super(ApiClient, self).__deserialize_model(data, klass)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 620, in __deserialize_model\n    kwargs[attr] = self.__deserialize(value, attr_type)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/openshift/client/api_client.py\", line 17, in _ApiClient__deserialize\n    return super(ApiClient, self).__deserialize_model(data, klass)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 620, in __deserialize_model\n    kwargs[attr] = self.__deserialize(value, attr_type)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/openshift/client/api_client.py\", line 11, in _ApiClient__deserialize\n    return super(ApiClient, self).__deserialize(data, klass)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 254, in __deserialize\n    for sub_data in data]\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/openshift/client/api_client.py\", line 11, in _ApiClient__deserialize\n    return super(ApiClient, self).__deserialize(data, klass)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 276, in __deserialize\n    return self.__deserialize_model(data, klass)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 622, in __deserialize_model\n    instance = klass(**kwargs)\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/models/runtime_raw_extension.py\", line 49, in __init__\n    self.raw = raw\n  File \"/Users/chouseknecht/.pyenv/versions/venv27/lib/python2.7/site-packages/kubernetes/client/models/runtime_raw_extension.py\", line 72, in raw\n    raise ValueError(\"Invalid value for `raw`, must not be `None`\")\nValueError: Invalid value for `raw`, must not be `None`\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

FWIW, here's my test playbook:

```
- name: Create template
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:

  - name: Create instance
    openshift_raw:
      state: present
      definition:
        kind: TemplateInstance
        apiVersion: "v1"
        metadata:
          name: foo
          namespace: testing
        spec:
          secret:
            name: foosettings
          template:
            kind: "Template"
            apiVersion: "v1"
            metadata:
              name: my-template
            objects:
            - kind: "Service"
              apiVersion: "v1"
              metadata:
                name: "cakephp-mysql-example"
                annotations:
                description: "Exposes and load balances the application pods"
              spec:
                ports:
                - name: "web"
                  port: 8080
                  targetPort: 8080
                selector:
                  name: "cakephp-mysql-example"
```
