### ISSUE TITLE
parted fails to create empty partion table on a new disk, says the number argument is missing

### ISSUE THREAD

**Issue by jszigetvari** [ansible/ansible#36905]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
parted

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /home/janos/b/drbd-test/ansible.cfg
  configured module search path = [u'/home/janos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/home/janos/b/drbd-test/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/janos/b/drbd-test/ansible.cfg) = [u'/home/janos/b/drbd-test/inventory']
DEFAULT_MANAGED_STR(/home/janos/b/drbd-test/ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}.
DEFAULT_REMOTE_USER(/home/janos/b/drbd-test/ansible.cfg) = vagrant
HOST_KEY_CHECKING(/home/janos/b/drbd-test/ansible.cfg) = False
```

##### OS / ENVIRONMENT
```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
```

##### SUMMARY
Creating a disk label/empty partition table does not work with Ansible 2.4.3.0

Documentation says that the number argument is not mandatory, but in its latest version, Ansible seems to expect it.

##### STEPS TO REPRODUCE

```yaml
  - name: workaround for parted not being idempotent
    stat: path="/dev/{{ ansible_local.drbd.disk.device }}1"
    register: result

  - name: create disklabel on the empty disk
    parted: >
      device="/dev/{{ ansible_local.drbd.disk.device }}"
      label="gpt"
      state="present"
    when: not result.stat.exists
```

##### EXPECTED RESULTS
With ansible 2.3.1.0+dfsg-2 (from Ubuntu Atrful's repo) this task worked without problem, but after upgrading to 2.4.3.0, it broke my playbook.

##### ACTUAL RESULTS
The module fails at the phase of examining the arguments.

```
TASK [create disklabel on the empty disk] *********************************************************************
fatal: [node1]: FAILED! => {"changed": false, "msg": "state is present but the following are missing: number"}
fatal: [node2]: FAILED! => {"changed": false, "msg": "state is present but the following are missing: number"}
```
