### ISSUE TITLE
eos_interface intent fails on eapi

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#36919]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

eos_interface

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel b12e90311f) last updated 2018/03/01 12:39:16 (GMT -400)
  config file = None
  configured module search path = [u'/Users/david/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/david/code/ansible/lib/ansible
  executable location = /Users/david/code/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### SUMMARY

eos_interface produces a stack track when run using eapi

##### STEPS TO REPRODUCE

`ansible-playbook -i eos.inv eos.yaml -vvvv`

```yaml
---
- hosts: eos
  tasks:
  - name: Set test interface
    set_fact:
      test_interface_1: ethernet1

  - name: Check intent arguments
    eos_interface:
      name: "{{ test_interface_1 }}"
      state: up
      tx_rate: ge(0)
      rx_rate: ge(0)
      authorize: yes
      provider: "{{ eapi }}"
    register: result

```

group_vars/eos.yaml:
```yaml
ansible_connection: local
ansible_network_os: eos
ansible_user: PASSWORD
ansible_ssh_pass: USER
eapi:
  host: "{{ inventory_hostname }}"
  transport: eapi
  authorize: yes
  validate_certs: false
```

##### EXPECTED RESULTS

task should pass

##### ACTUAL RESULTS

```
TASK [Check intent arguments] **********************************************************************************
task path: /Users/david/code/test/eos.yaml:8
<eos02> connection transport is eapi
Using module file /Users/david/code/ansible/lib/ansible/modules/network/eos/eos_interface.py
<eos02> ESTABLISH LOCAL CONNECTION FOR USER: david
<eos02> EXEC /bin/sh -c 'echo ~ && sleep 0'
<eos02> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/david/.ansible/tmp/ansible-tmp-1519930473.54-89724812253350 `" && echo ansible-tmp-1519930473.54-89724812253350="` echo /Users/david/.ansible/tmp/ansible-tmp-1519930473.54-89724812253350 `" ) && sleep 0'
<eos02> PUT /Users/david/.ansible/tmp/ansible-local-199917TML_E/tmpgccdUR TO /Users/david/.ansible/tmp/ansible-tmp-1519930473.54-89724812253350/eos_interface.py
<eos02> EXEC /bin/sh -c 'chmod u+x /Users/david/.ansible/tmp/ansible-tmp-1519930473.54-89724812253350/ /Users/david/.ansible/tmp/ansible-tmp-1519930473.54-89724812253350/eos_interface.py && sleep 0'
<eos02> EXEC /bin/sh -c '/usr/bin/python /Users/david/.ansible/tmp/ansible-tmp-1519930473.54-89724812253350/eos_interface.py && sleep 0'
<eos02> EXEC /bin/sh -c 'rm -f -r /Users/david/.ansible/tmp/ansible-tmp-1519930473.54-89724812253350/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/x6/l9cfl1bs7x9_h9_v5sn94z640000gn/T/ansible_Glr2s3/ansible_module_eos_interface.py", line 466, in <module>
    main()
  File "/var/folders/x6/l9cfl1bs7x9_h9_v5sn94z640000gn/T/ansible_Glr2s3/ansible_module_eos_interface.py", line 456, in main
    failed_conditions = check_declarative_intent_params(module, want, result)
  File "/var/folders/x6/l9cfl1bs7x9_h9_v5sn94z640000gn/T/ansible_Glr2s3/ansible_module_eos_interface.py", line 337, in check_declarative_intent_params
    match = re.search(r'%s (\w+)' % 'line protocol is', output[0], re.M)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 146, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer

fatal: [eos02]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/x6/l9cfl1bs7x9_h9_v5sn94z640000gn/T/ansible_Glr2s3/ansible_module_eos_interface.py\", line 466, in <module>\n    main()\n  File \"/var/folders/x6/l9cfl1bs7x9_h9_v5sn94z640000gn/T/ansible_Glr2s3/ansible_module_eos_interface.py\", line 456, in main\n    failed_conditions = check_declarative_intent_params(module, want, result)\n  File \"/var/folders/x6/l9cfl1bs7x9_h9_v5sn94z640000gn/T/ansible_Glr2s3/ansible_module_eos_interface.py\", line 337, in check_declarative_intent_params\n    match = re.search(r'%s (\\w+)' % 'line protocol is', output[0], re.M)\n  File \"/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py\", line 146, in search\n    return _compile(pattern, flags).search(string)\nTypeError: expected string or buffer\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}

```
