### ISSUE TITLE
FR: Allow git option archive to use remote repository without cloning

### ISSUE THREAD

**Issue by danowar2k** [ansible/ansible#36925]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
git

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /home/vagrant/playbooks/playbook-moodle/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = True
COLOR_VERBOSE(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = bright blue
DEFAULT_BECOME_METHOD(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = sudo
DEFAULT_HOST_LIST(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = [u'/home/vagrant/playbooks/playbook-moodle/inventory/debug_ho
DEFAULT_STDOUT_CALLBACK(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = debug
DEFAULT_TIMEOUT(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = 30
DIFF_ALWAYS(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/home/vagrant/playbooks/playbook-moodle/ansible.cfg) = 60

##### OS / ENVIRONMENT
N/A

##### SUMMARY
At the moment one can only create an archive of a locally cloned repository (**dest** must be given).
git-archive provides an option to create an archive of a remote repository (--remote) so that the local clone isn't needed. Please enable the git module to download archives of remote repositories.

##### STEPS TO REPRODUCE

```yaml
- name: Locally download the archive of the chosen git repository version
  local_action:
    module: git
    repo: "git@github.com:moodle/moodle.git"
    clone: no
    archive: "~/downloads/official-v3.2.7.tar.gz"
    version: "v3.2.7"
```

##### EXPECTED RESULTS
Downloads an archive of the commit from the remote repository.

##### ACTUAL RESULTS
Doesn't work at the moment. Needs a locally cloned repo.
