### ISSUE TITLE
Creating RoleBindings in Openshift returns a response that generates an error

### ISSUE THREAD

**Issue by twhiston** [ansible/ansible#36939]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openshift_raw

##### ANSIBLE VERSION
```
ansible 2.5.0rc1 (stable-2.5 3f8377c2d9) last updated 2018/03/02 09:52:05 (GMT +200)
  config file = /Users/twhiston/.ansible.cfg
  configured module search path = [u'/Users/twhiston/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/devel/lib/ansible
  executable location = /usr/local/Cellar/ansible/devel/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
For context see #36845 

When creating a RoleBinding in openshift the response returned causes an error to be thrown due to a missing key

Tested with the following openshift versions, all return an error
```
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://openshift-staging.nine.ch:8443
openshift v3.6.173.0.96
kubernetes v1.6.1+5115d708d7
```

and
```
oc v3.7.1+ab0f056
kubernetes v1.7.6+a08f5eeb62
features: Basic-Auth

Server https://127.0.0.1:8443
openshift v3.7.1+a8deba5-34
kubernetes v1.7.6+a08f5eeb62
```
##### STEPS TO REPRODUCE

```yaml
- name: Bind roles to groups
  ignore_errors: yes
  openshift_raw:
    host: "{{ openshift_host }}"
    api_version: v1
    api_key: "{{ oc_token }}"
    verify_ssl: "{{ verify_ssl }}"
    definition: "{{ lookup('template', '../files/rolebinding.yml') | from_yaml }}"
    state: present
  with_items:
    - admin
    - edit
    - view
```

```yaml
apiVersion: v1
groupNames:
- "{{ project_name }}-{{ item }}"
kind: RoleBinding
metadata:
  name: "{{ item }}"
  namespace: "{{ project_name }}"
roleRef:
  name: "{{ item }}"
subjects:
- kind: Group
  name: "{{ project_name }}-{{ item }}"
userNames: null
```

##### EXPECTED RESULTS
The RoleBinding is created and no error is produced by the return value from openshift

##### ACTUAL RESULTS

The Rolebinding is created but an error is triggered due to the return value from openshift

This output is the same in both openshift 3.6 and 3.7
```
ailed: [localhost] (item=admin) => {"changed": false, "item": "admin", "module_stderr": "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/var/folders/fs/8mwd9rjn6rn3sh22s9tqf4qc0000gp/T/ansible_HaQ2Nx/ansible_module_openshift_raw.py\", line 204, in <module>\n    main()\n  File \"/var/folders/fs/8mwd9rjn6rn3sh22s9tqf4qc0000gp/T/ansible_HaQ2Nx/ansible_module_openshift_raw.py\", line 200, in main\n    OpenShiftRawModule().execute_module()\n  File \"/var/folders/fs/8mwd9rjn6rn3sh22s9tqf4qc0000gp/T/ansible_HaQ2Nx/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 100, in execute_module\n  File \"/Users/twhiston/Library/Python/2.7/lib/python/site-packages/openshift/helper/base.py\", line 203, in get_object\n    k8s_obj = get_method(name, namespace)\n  File \"/Users/twhiston/Library/Python/2.7/lib/python/site-packages/openshift/client/apis/oapi_api.py\", line 24802, in read_namespaced_role_binding\n    (data) = self.read_namespaced_role_binding_with_http_info(name, namespace, **kwargs)\n  File \"/Users/twhiston/Library/Python/2.7/lib/python/site-packages/openshift/client/apis/oapi_api.py\", line 24887, in read_namespaced_role_binding_with_http_info\n    collection_formats=collection_formats)\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 321, in call_api\n    _return_http_data_only, collection_formats, _preload_content, _request_timeout)\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 163, in __call_api\n    return_data = self.deserialize(response_data, response_type)\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 236, in deserialize\n    return self.__deserialize(data, response_type)\n  File \"/Users/twhiston/Library/Python/2.7/lib/python/site-packages/openshift/client/api_client.py\", line 11, in _ApiClient__deserialize\n    return super(ApiClient, self).__deserialize(data, klass)\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 276, in __deserialize\n    return self.__deserialize_model(data, klass)\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 620, in __deserialize_model\n    kwargs[attr] = self.__deserialize(value, attr_type)\n  File \"/Users/twhiston/Library/Python/2.7/lib/python/site-packages/openshift/client/api_client.py\", line 11, in _ApiClient__deserialize\n    return super(ApiClient, self).__deserialize(data, klass)\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 276, in __deserialize\n    return self.__deserialize_model(data, klass)\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 622, in __deserialize_model\n    instance = klass(**kwargs)\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/models/v1_role_ref.py\", line 55, in __init__\n    self.api_group = api_group\n  File \"/usr/local/lib/python2.7/site-packages/kubernetes/client/models/v1_role_ref.py\", line 80, in api_group\n    raise ValueError(\"Invalid value for `api_group`, must not be `None`\")\nValueError: Invalid value for `api_group`, must not be `None`\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

```
