### ISSUE TITLE
New module cloudfront_distribution should allow to use an existing identity

### ISSUE THREAD

**Issue by ricardoklein** [ansible/ansible#36958]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Module: cloudfront_distribution.py

##### ANSIBLE VERSION
```
ansible 2.5.0rc1
  config file = None
  configured module search path = [u'/Users/szq5297/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
Using ansible 2.5.0rc1

##### OS / ENVIRONMENT
MacOS managing Amazon Web Services

##### SUMMARY
When creating a new origin on CloudFront, I should be able to select an existing identity, since we have a single identity for all behaviors on the dev environment for example.

##### STEPS TO REPRODUCE
Create a new CloudFront with an S3 Origin with an existing IDENTITY

```yaml
- name: Create CloudFronts
      cloudfront_distribution:
        state: present
        ipv6_enabled: true
        purge_origins: True
        purge_cache_behaviors: True
        purge_aliases: True
        alias: cdn.mydomain
        comment: Managed By Ansible
        tags:
          Environment: 'HML'
          Product: 'MySite'
        viewer_certificate:
          acm_certificate_arn: arn:aws:acm:<certarn>
          certificate: arn:aws:acm:us-east-1:<certname>
          ssl_support_method: sni-only
          certificate_source: acm
          minimum_protocol_version: TLSv1
        origins:
          - id: 'S3-mysite'
            domain_name: 'mysite.s3.amazonaws.com'
            s3_origin_access_identity_enabled:
              **- origin_access_identity: <IDENTITY>** <== Add an extra option here
        default_cache_behavior:
            target_origin_id: 'S3-mysite'
            viewer_protocol_policy: redirect-to-https
            allowed_methods:
              items:
                - GET
                - HEAD
              cached_methods:
                - GET
                - HEAD
            min_ttl: 3600
            default_ttl: 3600
            max_ttl: 3600
            compress: True
```

##### EXPECTED RESULTS
Use an existing IDENTITY

##### ACTUAL RESULTS
Creates a new identity for every new origin
