### ISSUE TITLE
Bootstrapping PIP for Python 3 is using wrong PREFIX

### ISSUE THREAD

**Issue by Vascko** [ansible/ansible#36956]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

command

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.3 (default, Jan  4 2018, 16:40:53) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/ansible/ansible.cfg) = True
DEFAULT_FORCE_HANDLERS(/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = ['/ansible/inventory/development']
DEFAULT_PRIVATE_KEY_FILE(/ansible/ansible.cfg) = /root/.ssh/ansible.key
DEFAULT_ROLES_PATH(/ansible/ansible.cfg) = ['/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/ansible/ansible.cfg) = /root/.vaults/.ansible_vault_pass
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

Running CentOS 7.4 on managing and managed host: `Linux 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Jan 4 01:06:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

##### SUMMARY

Python's (2 and 3) install prefix on CentOS is "/usr" which makes 64bit components reside in "/usr/lib64" and non-64bit components reside in "/usr/lib".
When using get-pip.py (https://bootstrap.pypa.io/get-pip.py) to bootstrap PIP using below tasks, PIP for Python 3 is getting installed with the wrong PREFIX (/usr/local) while PIP for Python 2 is getting installed with the correct PREFIX (/usr).

##### STEPS TO REPRODUCE

```yaml
- name: Install Python 3
  package:
    name: python36
    state: present

- name: Link Python 3
  file:
    src: /usr/bin/python3.6
    dest: /usr/bin/python3
    state: link

- name: Check to see if PIP (Python 2.7) is already installed
  command: "pip2 --version"
  failed_when: False
  changed_when: False
  register: pip2_installed

- name: Check to see if PIP (Python 3) is already installed
  command: "pip3 --version"
  failed_when: False
  changed_when: False
  register: pip3_installed

- name: Copy get-pip.py
  copy:
    src: get-pip.py
    dest: /tmp
  when: pip2_installed.rc != 0 and pip3_installed != 0

- name: Install PIP (Python 2)
  command: "python2 /tmp/get-pip.py"
  when: pip2_installed.rc != 0

- name: Install PIP (Python 3)
  command: "python3 /tmp/get-pip.py"
  when: pip3_installed.rc != 0

- name: Delete get-pip.py
  file:
    path: /tmp/get-pip.py
    state: absent
```

##### EXPECTED RESULTS

PIP for Python 3 should get installed in "/usr/lib/python3.6/site-packages"

##### ACTUAL RESULTS

PIP for Python 3 gets wrongly installed in "/usr/local/lib/python3.6/site-packages" and PIP for Python 2 is getting correctly installed into "/usr/lib/python2.7/site-packages".

##### ADDITIONAL INFORMATION
**!!! When bootstrapping PIP from the command line manually using the same procedure, none of these issues occur !!!**

Changing the PIP install task to this:
```
- name: Install PIP (Python 3)
  command: "python3 /tmp/get-pip.py --prefix=/usr"
  when: pip3_installed.rc != 0
```
will get PIP for Python 3 installed with the correct PREFIX. However, ANY package installed via PIP for Python 3 (doesn't matter if through Ansible or manually) is getting installed with PREFIX "/usr/local" now instead of "/usr" which makes Python 3 not find the modules when trying to import them. This also doesn't happen when installing PIP manually
