### ISSUE TITLE
cloudfront_distribution module throws error on geolocation update

### ISSUE THREAD

**Issue by ashokdudhade** [ansible/ansible#36959]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudfront_distribution

##### ANSIBLE VERSION
Ansible: 2.4.3.0

##### OS / ENVIRONMENT
 alpine:3.7

##### SUMMARY
We have copied cloudfront_distribution and related module utils into library directory. 
When trying to update cloudfront with geolocation restriction it throws below error.

```
Request body:
            "restrictions": {
                "geo_restriction": {
                    "items": [
                        "US"
                    ],
                    "restriction_type": "whitelist"
                }
            },
            


Error updating distribution to {u'Comment': '', u'Restrictions': {'Items': ['US'], 'RestrictionType': 'whitelist', 'Quantity': 1}, u'Logging': {u'Bucke
....
Parameter validation failed:\nMissing required parameter in DistributionConfig.Restrictions: \"GeoRestriction\"\nUnknown parameter in DistributionConfig.Restrictions: \"Items\", must be one of: GeoRestriction\nUnknown parameter in DistributionConfig.Restrictions: \"RestrictionType\", must be one of: GeoRestriction\nUnknown parameter in DistributionConfig.Restrictions: \"Quantity\", must be one of: GeoRestriction
```
##### STEPS TO REPRODUCE

```yaml
- name: Add restriction geo location
  cloudfront_distribution:
    state: present
    distribution_id: "{{ cloudfront_distribution_id }}"
    restrictions:
      geo_restriction:
        restriction_type: "whitelist"
        items:
          - "US"
```
