### ISSUE TITLE
nxos_config: 'invalid command' on existing bgp configuration

### ISSUE THREAD

**Issue by indivisiblewalrus** [ansible/ansible#36960]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_config

##### ANSIBLE VERSION
ansible 2.5.0rc1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pete/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

##### CONFIGURATION
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
PARAMIKO_HOST_KEY_AUTO_ADD(env: ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD) = True

##### OS / ENVIRONMENT
debian
Python 2.7.5

##### SUMMARY
nxos_config being used to apply a jinja template, failing on second playbook run.  indempotency issue?

Template applies without issue on the first attempt.  
On the second attempt(same configuration), application fails with:
            "clierror": "% Invalid command\n", 
            "code": "400", 
            "msg": "CLI execution error"

##### STEPS TO REPRODUCE
```
vars:
bgp_neighbors:
  - { remote_as: 65001, neighbor: 1.1.1.1, vrf: default, description: spine00 }
  - { remote_as: 65001, neighbor: 1.1.1.2, vrf: default, description: spine01 }
  - { remote_as: 65001, neighbor: 1.1.1.3, vrf: default, description: spine02 }

  bgp_neighbor
    - name: BASE NEIGHBOR CONFIG
      nxos_config:
       src: bgp_leaf_neighbor.j2
       provider: "{{ nxos_provider }}"
      with_items:
        - "{{ bgp_neighbors }}"

bgp_neighbor.j2:
     router bgp {{ bgp_asn }}
       neighbor {{ item.neighbor }}
       inherit peer SPINE
       remote-as {{ item.remote_as }}
```

##### EXPECTED RESULTS
application/indempotent check of configuration:   
    router bgp 65001
       neighbor 1.1.1.1
       inherit peer SPINE
       remote-as 65001
    router bgp 65001
       neighbor 1.1.1.2
       inherit peer SPINE
       remote-as 65001
    router bgp 65001
       neighbor 1.1.1.3
       inherit peer SPINE
       remote-as 65001

##### ACTUAL RESULTS
This occurs on each item in the list...

```
failed: [leaf07] (item={u'remote_as': 65001, u'vrf': u'default', u'neighbor': u'1.1.1.3', u'description': u'spine02'}) => {
    "changed": false, 
    "clierror": "% Invalid command\n", 
    "code": "400", 
    "invocation": {
        "module_args": {
            "after": null, 
            "backup": false, 
            "before": null, 
            "defaults": false, 
            "diff_against": null, 
            "diff_ignore_lines": null, 
            "force": false, 
            "host": "leaf07", 
            "intended_config": null, 
            "lines": null, 
            "match": "line", 
            "parents": null, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "provider": {
                "host": "leaf07", 
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "port": 443, 
                "ssh_keyfile": null, 
                "timeout": 60, 
                "transport": "nxapi", 
                "use_proxy": true, 
                "use_ssl": true, 
                "username": "admin", 
                "validate_certs": false
            }, 
            "replace": "line", 
            "replace_src": null, 
            "running_config": null, 
            "save": false, 
            "save_when": "never", 
            "src": "router bgp 65333\n  neighbor 1.1.1.3\n  inherit peer SPINE\n  remote-as 65001\n", 
            "ssh_keyfile": null, 
            "timeout": 60, 
            "transport": "nxapi", 
            "url_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "url_username": "admin", 
            "use_proxy": true, 
            "use_ssl": true, 
            "username": "admin", 
            "validate_certs": false
        }
    }, 
    "item": {
        "description": "spine02", 
        "neighbor": "1.1.1.3", 
        "remote_as": 65001, 
        "vrf": "default"
    }, 
    "msg": "CLI execution error", 
    "output": [
        {
            "body": {}, 
            "code": "200", 
            "msg": "Success"
        }, 
        {
            "clierror": "% Invalid command\n", 
            "code": "400", 
            "msg": "CLI execution error"
        }
    ], 
    "url": "https://leaf07:443/ins"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nxos/nxos_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @kedarX @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
@indivisiblewalrus You need to follow 2-spaces indentation in src file. The module works for me after I fixed the indentation.
```
$ cat bgp_neighbors.j2 
router bgp {{ bgp_asn }}
  neighbor {{ item.neighbor }}
    inherit peer SPINE
    remote-as {{ item.remote_as }}
```

**Comment by indivisiblewalrus** [comment]
nxos doesn't care about indentation

'router bgp 12345
neighbor 1.1.1.1
remote-as 54321'

 is equivalent to:

'     router bgp 12345
 neighbor 1.1.1.1
         remote-as 54321'

But this isn't necessarily a great workaround for larger jinja 2 files when
you want a readable syntax for the control structure which adds variable
whitespace/indentation.  e.g following also failed:

router bgp {{bgp_asn}}
 {% for peer in bgp_ext_neighbors %}

   {% for tenant in tenants %}
     {% if peer.vrf == tenant.name %}
       vrf {{ peer.vrf }}
        {% if peer.state == 'present' %}
          neighbor {{ peer.peer_ip }}
           description {{ peer.peer_name }}
           inherit peer {{ peer.vrf }}-ext-peer
           remote-as {{ peer.peer_as }}
           {% if peer.admin_state == 'down' %}
             shutdown
           {% endif %}
           {% if peer.admin_state == 'up' %}
             no shutdown
           {% endif %}
        {% endif %}
        {% if peer.state == 'absent' %}
          no neighbor {{ peer.peer_ip }}
        {% endif %}
     {% endif %}
   {% endfor %}
 {% endfor %}

**Comment by indivisiblewalrus** [comment]
Additionally, this exact template worked in 2.4, and did work in an early 2.5dev, and the template does work again in 2.6dev.  Seems something changed with the 2.5rc1?

**Comment by trishnaguha** [comment]
The error is expected. When it comes to indentation, the indentation must match the indentation produced by the NX-OS `show running-config` command. If the indentation does not match, we may get unexpected results.
I can reproduce this on devel, stable-2.5 and stable-2.4.

**Comment by trishnaguha** [comment]
On addition to the above, the correct way to do this is using `lines` option. however we do not guarantee idempotence when `lines` option is used.
```
nxos_config:
  lines:
    - remote-as {{ item.remote_as }}
    - inherit peer SPINE
  parents: neighbor {{ item.neighbor }}
  before: router bgp 65001
with_items:
  - "{{ bgp_neighbors }}"
```
