### ISSUE TITLE
elb_application_lb module throwing KeyError when updating/rotating SSL certificates

### ISSUE THREAD

**Issue by srkiNZ84** [ansible/ansible#36983]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
elb_application_lb

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
```

##### CONFIGURATION
All defaults

##### OS / ENVIRONMENT
From: Ubuntu 14.04
Managing: AWS resources

##### SUMMARY
Trying to update the SSL certificate used by an AWS Application Load Balancer throws a "KeyError" when assigning the variable following a comparison.

##### STEPS TO REPRODUCE
Basically have an existing ALB with existing HTTP/HTTPS Listeners. Then modify the "CertificateArn" field to use a different certificate.

```yaml
- hosts: all
  gather_facts: False
  tasks:
    - name: Define Public application load balancer listeners
      set_fact:
        vpc_pub_application_lb_listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:001152111111:listener/app/env-pub-application-lb/bbbb61beaaaaaaaa/12345678d736aaaa"
          - Protocol: HTTPS
            Port: 443
            DefaultActions:
              - Type: forward
                TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:001152111111:listener/app/env-pub-application-lb/bbbb61beaaaaaaaa/12345678d736aaaa"
            SslPolicy: "ELBSecurityPolicy-TLS-1-2-2017-01"
            Certificates:
              - CertificateArn: "arn:aws:iam::001152111111:server-certificate/devtest-2019-04-11.cert"

    - name: Ensure that the public facing application load balancer is there
      elb_application_lb:
        access_logs_enabled: yes
        access_logs_s3_bucket: "env-lb-logs"
        name: "env-pub-application-lb"
        ec2_access_key: "FOO"
        ec2_secret_key: "BAR"
        region: "us-east-1"
        security_groups: "sg-12345678"
        subnets:
          - subnet-00000000
          - subnet-22222222
        listeners: "{{ vpc_pub_application_lb_listeners }}"
        idle_timeout: 300
        state: present
```
Then run with the inventory file just set to "localhost":
```shell
ansible-playbook -i hosts elb_application_ssl.yml -vvvv
```

##### EXPECTED RESULTS
That the ALB Listener was updated to use the new certificate.

##### ACTUAL RESULTS
The task to Ensure that the ALB was there failed with a "KeyError" referring to the "Certificate" field.

```shell
$ ansible-playbook -i hosts elb_application_ssl.yml -vvvv
ansible-playbook 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Set default localhost to localhost
Parsed /tmp/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/__init__.pyc

PLAYBOOK: elb_application_ssl.yml ************************************************************************************************************************************************
1 plays in elb_application_ssl.yml

PLAY [all] ***********************************************************************************************************************************************************************
META: ran handlers

TASK [Define Public application load balancer listeners] *************************************************************************************************************************
task path: /tmp/elb_application_ssl.yml:4
ok: [localhost] => {
    "ansible_facts": {
        "vpc_pub_application_lb_listeners": [
            {
                "DefaultActions": [
                    {
                        "TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:001152111111:listener/app/env-pub-application-lb/bbbb61beaaaaaaaa/12345678d736aaaa",
                        "Type": "forward"
                    }
                ],
                "Port": 80,
                "Protocol": "HTTP"
            },
            {
                "Certificates": [
                    {
                        "CertificateArn": "arn:aws:iam::001152111111:server-certificate/devtest-2019-04-11.cert"
                    }
                ],
                "DefaultActions": [
                    {
                        "TargetGroupArn": "arn:aws:elasticloadbalancing:us-east-1:001152111111:listener/app/env-pub-application-lb/bbbb61beaaaaaaaa/12345678d736aaaa",
                        "Type": "forward"
                    }
                ],
                "Port": 443,
                "Protocol": "HTTPS",
                "SslPolicy": "ELBSecurityPolicy-TLS-1-2-2017-01"
            }
        ]
    },
    "changed": false,
    "failed": false
}

TASK [Create public facing application load balancer] ****************************************************************************************************************************
task path: /tmp/elb_application_ssl.yml:22
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/amazon/elb_application_lb.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1520202916.17-257149765529121 `" && echo ansible-tmp-1520202916.17-257149765529121="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1520202916.17-257149765529121 `" ) && sleep 0'
<localhost> PUT /tmp/tmpcFlGDX TO /home/ubuntu/.ansible/tmp/ansible-tmp-1520202916.17-257149765529121/elb_application_lb.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1520202916.17-257149765529121/ /home/ubuntu/.ansible/tmp/ansible-tmp-1520202916.17-257149765529121/elb_application_lb.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1520202916.17-257149765529121/elb_application_lb.py; rm -rf "/home/ubuntu/.ansible/tmp/ansible-tmp-1520202916.17-257149765529121/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py", line 1024, in <module>
    main()
  File "/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py", line 1019, in main
    create_or_update_elb(connection, connection_ec2, module)
  File "/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py", line 911, in create_or_update_elb
    listener_changed = create_or_update_elb_listeners(connection, module, elb)
  File "/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py", line 718, in create_or_update_elb_listeners
    listeners_to_add, listeners_to_modify, listeners_to_delete = compare_listeners(connection, module, current_listeners, deepcopy(listeners), purge_listeners)
  File "/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py", line 638, in compare_listeners
    modified_listener = compare_listener(current_listener, new_listener)
  File "/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py", line 541, in compare_listener
    modified_listener['Certificates'][0]['CertificateArn'] = new_listener['Certificates'][0]['CertificateArn']
KeyError: 'Certificates'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py\", line 1024, in <module>\n    main()\n  File \"/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py\", line 1019, in main\n    create_or_update_elb(connection, connection_ec2, module)\n  File \"/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py\", line 911, in create_or_update_elb\n    listener_changed = create_or_update_elb_listeners(connection, module, elb)\n  File \"/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py\", line 718, in create_or_update_elb_listeners\n    listeners_to_add, listeners_to_modify, listeners_to_delete = compare_listeners(connection, module, current_listeners, deepcopy(listeners), purge_listeners)\n  File \"/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py\", line 638, in compare_listeners\n    modified_listener = compare_listener(current_listener, new_listener)\n  File \"/tmp/ansible_eWpUlz/ansible_module_elb_application_lb.py\", line 541, in compare_listener\n    modified_listener['Certificates'][0]['CertificateArn'] = new_listener['Certificates'][0]['CertificateArn']\nKeyError: 'Certificates'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 0
}
	to retry, use: --limit @/tmp/elb_application_ssl.retry

PLAY RECAP ***********************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

```
