### ISSUE TITLE
EC2 module not return created instances at second run

### ISSUE THREAD

**Issue by stormit-vn** [ansible/ansible#36987]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2

##### ANSIBLE VERSION

```
2.4.2.0
```

##### CONFIGURATION

I am using ec2 module to launch ec2 instances, my task configuration as below:
```yaml
- name: Launch Neo4j cluster instances in az1
      ec2:
        key_name: '{{ keypair }}'
        group_id: '{{ security_group }}'
        instance_type: '{{ instance_type }}'
        image: '{{ image }}'
        vpc_subnet_id: '{{ vpc_az1_subnet_id }}'
        wait: true
        exact_count: '{{ az1_node_count }}'
        volumes:
          - device_name: /dev/xvda
            volume_type: gp2
            volume_size: 100
            delete_on_termination: true
        monitoring: yes
        instance_tags:
          Name: '{{ instance_name_tag_az1 }}'
          NeoAZ1: '{{ instance_name_tag_az1 }}'
        count_tag: NeoAZ1
        ec2_url: '{{ ec2_url }}'
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        assign_public_ip: '{{ allow_public_access|bool }}'
        region: '{{ region }}'
      register: ec2_az1
```

Here is the variable file
```yaml
ec2_url: https://ec2.us-east-2.amazonaws.com
instance_type: t2.nano
instance_name_tag_az1: emmar-neo4j-az1
instance_name_tag_az2: emmar-neo4j-az2
haproxy_instance_name_tag: emmar-neo4j-ha-proxy

# Neo4j HA pull interval (in seconds)
pull_interval: 5

# Specify a number of nodes for Neo4j cluster, master will be auto elected
az1_node_count: 2
az2_node_count: 1

# Allow public access on Neo54j nodes or not
allow_public_access: yes
```

With this configuration, I expected ansible only created exac_count instances (i.e. 2 instances) and assign to register variable ec2_az1. This configuration work perfectly at the first time. Howerver, when I retest the playbook with the same configuration. Currently, the ec2_az1 does not contain created instances information at the first time, but I expected 2 instances information is available in the ec2_az1 even more instances if i increase the az1_node_count variable.

Does anyone know how to fix this issue? I am not sure whether ec2 module supports this kind of feature.
