### ISSUE TITLE
tower_role module fails with error "Role has no field named 'state'"

### ISSUE THREAD

**Issue by IshwarKanse** [ansible/ansible#36991]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tower_role module.

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /home/ikanse/Ansible/ansible-tower-manage-playbook/ansible.cfg
  configured module search path = [u'/home/ikanse/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Feb 17 2018, 10:42:17) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
[ikanse@ansible ansible-tower-manage-playbook
```

##### OS / ENVIRONMENT
Fedora 27
Ansible Tower and Tower CLI version:
Tower CLI 3.2.1
API v2
Ansible Tower 3.2.3
Ansible 2.4.2.0

##### SUMMARY
tower_role module fails with error "Role has no field named 'state'"

##### STEPS TO REPRODUCE
```
- name: Create tower organization
  tower_organization:
    name: "startrek"
    description: "Star trek organization"
    state: present

- name: Create tower team
  tower_team:
    name: ussr
    description: Team ussr of star trek
    organization: "startrek"
    state: present

- name: Add tower user
  tower_user:
    username: kirk
    password: "K!rkK!rk@"
    email: "kirk@startrek.com"
    first_name: Kirk
    last_name: Kirk
    state: present

- name: Add user to team
  tower_role:
    user: kirk
    target_team: "ussr"
    role: member
    state: present
```

##### EXPECTED RESULTS
Task completes successfully.

##### ACTUAL RESULTS
```
TASK [tower-manage : Add user to team] *************************************************************************
task path: /home/ikanse/Ansible/ansible-tower-manage-playbook/roles/tower-manage/tasks/main.yml:24
Using module file /usr/lib/python2.7/site-packages/ansible/modules/web_infrastructure/ansible_tower/tower_role.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ikanse
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ikanse/.ansible/tmp/ansible-tmp-1520232438.17-217702889247684 `" && echo ansible-tmp-1520232438.17-217702889247684="` echo /home/ikanse/.ansible/tmp/ansible-tmp-1520232438.17-217702889247684 `" ) && sleep 0'
<localhost> PUT /tmp/tmpxkOOCO TO /home/ikanse/.ansible/tmp/ansible-tmp-1520232438.17-217702889247684/tower_role.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ikanse/.ansible/tmp/ansible-tmp-1520232438.17-217702889247684/ /home/ikanse/.ansible/tmp/ansible-tmp-1520232438.17-217702889247684/tower_role.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/ikanse/.ansible/tmp/ansible-tmp-1520232438.17-217702889247684/tower_role.py; rm -rf "/home/ikanse/.ansible/tmp/ansible-tmp-1520232438.17-217702889247684/" > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_9eTSgJ/ansible_module_tower_role.py", line 220, in <module>
    main()
  File "/tmp/ansible_9eTSgJ/ansible_module_tower_role.py", line 207, in main
    result = role.grant(**params)
  File "/usr/lib/python2.7/site-packages/tower_cli/resources/role.py", line 359, in grant
    return self.role_write(fail_on_found=fail_on_found, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/resources/role.py", line 236, in role_write
    fail_on_multiple_results=True, **data)
  File "/usr/lib/python2.7/site-packages/tower_cli/models/base.py", line 286, in read
    r = client.get(url, params=kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/tower_cli/api.py", line 236, in request
    kwargs.get('data', None), r.content.decode('utf8'))
tower_cli.exceptions.BadRequest: The Tower server claims it was sent a bad request.

GET https://13.126.199.60/api/v2/teams/1/object_roles/
Params: {'state': 'present', 'tower_verify_ssl': True, 'role_field': 'member_role'}
Data: None

Response: {"detail":"Role has no field named 'state'"}

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_9eTSgJ/ansible_module_tower_role.py\", line 220, in <module>\n    main()\n  File \"/tmp/ansible_9eTSgJ/ansible_module_tower_role.py\", line 207, in main\n    result = role.grant(**params)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/resources/role.py\", line 359, in grant\n    return self.role_write(fail_on_found=fail_on_found, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/resources/role.py\", line 236, in role_write\n    fail_on_multiple_results=True, **data)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/models/base.py\", line 286, in read\n    r = client.get(url, params=kwargs)\n  File \"/usr/lib/python2.7/site-packages/requests/sessions.py\", line 521, in get\n    return self.request('GET', url, **kwargs)\n  File \"/usr/lib/python2.7/site-packages/tower_cli/api.py\", line 236, in request\n    kwargs.get('data', None), r.content.decode('utf8'))\ntower_cli.exceptions.BadRequest: The Tower server claims it was sent a bad request.\n\nGET https://13.126.199.60/api/v2/teams/1/object_roles/\nParams: {'state': 'present', 'tower_verify_ssl': True, 'role_field': 'member_role'}\nData: None\n\nResponse: {\"detail\":\"Role has no field named 'state'\"}\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/ansible_tower/tower_role.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/ansible_tower/tower_role.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @AlanCoding @ghjm @jlaska @matburt @rooftopcellist @ryanpetrello @simfarm @wwitzel3
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by giovannisciortino** [comment]
I reproduced the error using:
- Fedora 26
- ansible branch devel
- Ansible Tower 3.2.3-1 (latest stable release)
- ansible-tower-cli-3.2.1

The same problem disappears when ansible-tower-cli 3.2.0 is used ( pip install 'ansible-tower-cli == 3.2.0' )

Playbook used for the test:
```
- hosts: towerlab
  tasks:
    - name: Create tower organization
      tower_organization:
        name: "startrek"
        description: "Star trek organization"
        state: present

    - name: Create tower team
      tower_team:
        name: ussr
        description: Team ussr of star trek
        organization: "startrek"
        state: present

    - name: Add tower user
      tower_user:
        username: kirk
        password: "K!rkK!rk@"
        email: "kirk@startrek.com"
        first_name: Kirk
        last_name: Kirk
        state: present

    - name: Add user to team
      tower_role:
        user: kirk
        target_team: "ussr"
        role: member
        state: present

```
