### ISSUE TITLE
vmware_guest : Could not find template in Content Library

### ISSUE THREAD

**Issue by SaranrajMG** [ansible/ansible#37007]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /opt/rh/python27/root/usr/bin/ansible
  python version = 2.7.13 (default, Feb  8 2017, 06:30:30) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

##### OS / ENVIRONMENT
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory.yml']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 5
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### SUMMARY
I'm able to deploy VM from a template which resides in the normal datastore. Recently I have moved a template to VMware Content Library then tried to deploy VM where it got failed with error

COULD NOT FIND THE TEMPLATE

##### EXPECTED RESULTS
Ansible script should have cloned a VM from template VMWare Content Library.

##### ACTUAL RESULTS
COULD NOT FIND THE TEMPLATE

**Comment by SaranrajMG** [comment]
My template reside under "VMware Content Library"

**Comment by Akasurde** [comment]
@SaranrajMG Thanks for reporting this issue. Could you please add `-vvvv` logs and the playbook you are using for this ?

**Comment by Akasurde** [comment]
needs_info

**Comment by SaranrajMG** [comment]
@Akasurde : Please find the request information. let me know if you required more info.

```
ansible-playbook 2.5.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /opt/rh/python27/root/usr/bin/ansible-playbook
  python version = 2.7.13 (default, Feb  8 2017, 06:30:30) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
No config file found; using defaults
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAYBOOK: create_dev_vms-old.yml *************************************************************************************************************************************************************
1 plays in create_dev_vms.yml
vCenter hostname? [XXXXXXXXXXXXXXXXX]: XXXXXXXXXXXXXXXXXXX
Enter username: XXXXXXXXXXXXXXXX
Enter password:
Template? [Linux-Test-Template]: RHEL7u4
New VM HOstname?: ansiblecontrolserver
Cluster? [sHosts08]:

PLAY [Create VMware guest] *******************************************************************************************************************************************************************
META: ran handlers

TASK [Deploy guest from template] ************************************************************************************************************************************************************
task path: /home/wf12/create_dev_vms-old.yml:31
Using module file /opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-23791n8Mn0v/ansible-tmp-1520356508.18-93279817668863 `" && echo ansible-tmp-1520356508.18-93279817668863="` echo /root/.ansible/tmp/ansible-local-23791n8Mn0v/ansible-tmp-1520356508.18-93279817668863 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-23791n8Mn0v/tmpevVrP3 TO /root/.ansible/tmp/ansible-local-23791n8Mn0v/ansible-tmp-1520356508.18-93279817668863/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-23791n8Mn0v/ansible-tmp-1520356508.18-93279817668863/ /root/.ansible/tmp/ansible-local-23791n8Mn0v/ansible-tmp-1520356508.18-93279817668863/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/opt/rh/python27/root/usr/bin/python /root/.ansible/tmp/ansible-local-23791n8Mn0v/ansible-tmp-1520356508.18-93279817668863/vmware_guest.py && sleep 0'
fatal: [localhost -> localhost]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": "Hosts10",
            "customization": {
                "autologon": true,
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "sDatacenter",
            "datastore": "LUN-NPRD-OS-08",
            "disk": [
                {
                    "size_gb": 64,
                    "type": "eagerzeroedthick"
                },
                {
                    "datastore": "LUN-NPRD-OS-08",
                    "size_gb": 64,
                    "type": "eagerzeroedthick"
                }
            ],
            "esxi_hostname": null,
            "folder": "LINAUTTST",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 2048,
                "num_cpus": 1
            },
            "hostname": "***********.********",
            "is_template": false,
            "linked_clone": false,
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "gateway": "XXX.XXX.XXX.XXX",
                    "ip": "XXX.XXX.XXX.XXX",
                    "name": "109",
                    "netmask": "XXX.XXX.XXX.XXX",
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "RHEL7u4",
            "username": "XXXXXXXXX",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "Could not find a template named RHEL7u4"
}
        to retry, use: --limit @/home/test/create_dev_vms.retry

PLAY RECAP ***********************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1

```

**Comment by SaranrajMG** [comment]
@Akasurde : Please find the below playbook.
```
---
- name: Create VMware guest
  hosts: localhost
  gather_facts: False

  vars_prompt:
    - name: "vcenter"
      prompt: "vCenter hostname?"
      private: no
    - name: "user"
      prompt: "Enter username"
      private: no
    - name: "pass"
      prompt: "Enter password"
      private: yes
    - name: "template"
      prompt: "Template?"
      private: no
      default: "Linux-Test-Template"
    - name: "guest"
      prompt: "New VM HOstname?"
      private: no
    - name: "cluster"
      prompt: "Cluster?"
      private: no
      default: "Hosts8"

  tasks:
  - name: Deploy guest from template
    vmware_guest:
      hostname: "{{ vcenter }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: false
      cluster: "{{ cluster }}"
      datacenter: sDatacenter
      state: poweredon
      name: "{{ guest }}"
      template: "{{ template }}"
      folder: LINAUTTST
      datastore: LUN-NPRD-OS-08
      disk:
      - size_gb: 64
        type: eagerzeroedthick
      hardware:
        memory_mb: 2048
        num_cpus: 1
      networks:
       - name: 109
         device_type: vmxnet3
         type: static
         ip: XXX.XXX.XXX.XXX
         netmask: XXX.XXX.XXX.XXX
         gateway: XXX.XXX.XXX.XXX
    delegate_to: localhost
```

**Comment by Akasurde** [comment]
Content Library is a new feature and is not supported by pyvmomi library. I am investigating in REST API calls (vsphere Automation SDK) where 'CL' is supported.

**Comment by SaranrajMG** [comment]
@Akasurde: Thanks for updating.  Please let me know if you found a way to use it.

**Comment by Akasurde** [comment]
@SaranrajMG Deploying VM from template hosted in on-premise content library is not supported, yet. Please see this comment - https://github.com/vmware/vsphere-automation-sdk-python/issues/55#issuecomment-380876470

**Comment by brysonshepherd** [comment]
Has there been any work on this in the last year?

**Comment by Akasurde** [comment]
@brysonshepherd Yes, I did investigate on this. But like I said - deploying VM from template hosted in on-premise content library is not supported, yet.

**Comment by smnsjas** [comment]
This is no longer true with vCenter 6.7 update 2:  
https://blogs.vmware.com/vsphere/2019/04/vcenter-server-6-7-update-2-whats-new.html

**Comment by brysonshepherd** [comment]
I don't see in that article where it says that this will be supported.
Where are you looking?

**Comment by smnsjas** [comment]
> I don't see in that article where it says that this will be supported. Where are you looking?
> […](#)
The feature was added in vCenter 6.7 Update 1, but it was somewhat incomplete.  Update 2 seems to fix this.  Here’s the section of the article that talks about how this was added in update 1:

Content Library
The addition of storing Virtual Machine Template (VMTX) files in Content Library was introduced in vSphere 6.7 Update 1. This enables deploying a virtual machine from native VM templates alongside OVF/OVA templates within Content Library.

**Comment by Akasurde** [comment]
@pgbidkar Since you are looking into tagging and REST API, would like to implement this feature ? Let me know. Thanks.

**Comment by Spreadcat** [comment]
I can confirm this is not working for v2.8

**Comment by Akasurde** [comment]
@pgbidkar is currently working on this issue and will be submitting patch in upcoming days. Thanks.

**Comment by teadur** [comment]
Any updates on this, would love to deploy vm's from content library templates with Ansible ?

**Comment by Akasurde** [comment]
@teadur @pgbidkar is working on this and submitted PR - https://github.com/ansible/ansible/pull/58666

**Comment by pgbidkar** [comment]
> @teadur @pgbidkar is working on this and submitted PR - #58666

Thanks Anhijeet.
Hi @teadur , I have created PR for 2 use cases of content library. In Weeks time I will create new module for your use case. I have closed https://github.com/ansible/ansible/pull/58666, 2 modules are not allowed in single commit. I will create new ones for both

Thanks

**Comment by pgbidkar** [comment]
Hi @teadur , I have pushed basic template deploy module to my repo https://github.com/pgbidkar/ansible/commit/9009afc391ee12e2b16ed55144f90d966c22563f.  Module still needs to be refined.
Please try the module and provide the feedback to improve.

My playbook looks like 
```
---
- name: Deploy VM from template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Deploy Virtual Machine from template in content library
    vmware_content_deploy_template:
      hostname: 'VCIP'
      username: 'VC_Username'
      password: 'VC_Password'
      template: test_vm_temp
      datastore: Shared_NFS_Volume
      folder: vm
      datacenter: Sample_DC_1
      vm_name: 'Test_Content_deploy'
      resourcepool: test_rp
      validate_certs: False
    register: content_deploy_vm
```
