### ISSUE TITLE
Failed to import docker-py although it is installed when building AWX

### ISSUE THREAD

**Issue by jean-christophe-manciot** [ansible/ansible#37006]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 docker_container

##### SUMMARY
cf. title

##### ENVIRONMENT
* AWX version: tag 1.0.4
* AWX install method: docker on linux
* Ansible version: v2.4.3.0-1
* Operating System: Ubuntu 17.10
* Web Browser: chrome

##### STEPS TO REPRODUCE

```
        git clone https://github.com/ansible/awx .
        git checkout 1.0.4
        sed -i 's|postgres_data_dir=/tmp/pgdocker|postgres_data_dir=/var/lib/pgdocker|g' installer/inventory
        sed -i 's|host_port=80|host_port=8080|g' installer/inventory
        export PYTHONPATH=${PYTHONPATH}/usr/local/lib/python2.7/dist-packages
        echo "PYTHONPATH ${PYTHONPATH}"
        cd installer
        ansible-playbook -i inventory install.yml
```

Failing task:
```
- name: Activate postgres container
  docker_container:
    name: postgres
    state: started
    restart_policy: unless-stopped
    image: postgres:9.6
    volumes:
      - "{{ postgres_data_dir }}:/var/lib/postgresql/data:Z"
    env:
      POSTGRES_USER: "{{ pg_username }}"
      POSTGRES_PASSWORD: "{{ pg_password }}"
      POSTGRES_DB: "{{ pg_database }}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
  when: pg_hostname is not defined or pg_hostname == ''
  register: postgres_container_activate
```

##### EXPECTED RESULTS

Correct build

##### ACTUAL RESULTS

```
< TASK [local_docker : Set DockerHub Image Paths] >
 -------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 ___________________________________________________
< TASK [local_docker : Activate postgres container] >
 ---------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to import docker-py - No module named ssl_match_hostname. Try `pip install docker-py`"}
```

##### ADDITIONAL INFORMATION
```
# pip install docker-py
Requirement already satisfied: docker-py in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: docker-pycreds>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from docker-py)
Requirement already satisfied: backports.ssl-match-hostname>=3.5; python_version < "3.5" in /usr/local/lib/python2.7/dist-packages (from docker-py)
Requirement already satisfied: ipaddress>=1.0.16; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from docker-py)
Requirement already satisfied: requests!=2.11.0,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from docker-py)
Requirement already satisfied: six>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from docker-py)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python2.7/dist-packages (from docker-py)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests!=2.11.0,>=2.5.2->docker-py)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests!=2.11.0,>=2.5.2->docker-py)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests!=2.11.0,>=2.5.2->docker-py)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests!=2.11.0,>=2.5.2->docker-py)
```
