### ISSUE TITLE
nxos_config idempotency issue with FEX on Nexus 5K 

### ISSUE THREAD

**Issue by johncapobianco** [ansible/ansible#37022]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nxos_config

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/capobj/DC/Lab-Infrastructure/playbooks/data_centre/ansible.cfg
  configured module search path = [u'/home/capobj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### SUMMARY
The following lines do not appear to be idempotent 

fex 110
  hardware N2348UPQ qos-policy-offload
fex 112
  hardware N2348UPQ qos-policy-offload
fex 113
  hardware N2348UPQ qos-policy-offload
fex 131
  hardware N2248TP-E qos-policy-offload
fex 132
  hardware N2248TP-E qos-policy-offload

##### STEPS TO REPRODUCE

```
---
- hosts: LAB-DC
    - import_tasks: ../../tasks/configurations/nxos/configure_nxos_interface.yml

---

- name: Create NXOS Interface configuration 
  nxos_config: 
    src: ../../templates/configurations/nxos/06_nxos_interface.j2
    provider: "{{ nxoscli }}" 
  tags: vlan 
  register: interface_config_results 

```

##### EXPECTED RESULTS
Expected no changes / idempotency 

##### ACTUAL RESULTS
```
 {"changed": true, "commands": "fex 110", "hardware N2348UPQ qos-policy-offload", "fex 112", "hardware N2348UPQ qos-policy-offload", "fex 113", "hardware N2348UPQ qos-policy-offload", "fex 131", "hardware N2248TP-E qos-policy-offload", "fex 132", "hardware N2248TP-E qos-policy-offload" "updates": "fex 110", "hardware N2348UPQ qos-policy-offload", "fex 112", "hardware N2348UPQ qos-policy-offload", "fex 113", "hardware N2348UPQ qos-policy-offload", "fex 131", "hardware N2248TP-E qos-policy-offload", "fex 132", "hardware N2248TP-E qos-policy-offload"
```
