### ISSUE TITLE
infoblox nios argument ipv4addrs error

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#37032]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nios_host_record

##### ANSIBLE VERSION
```
SEANs-MacBook-Pro:infoblox_ansible sean$ ansible --version
ansible 2.6.0
  config file = /Users/sean/Documents/GitHub/infoblox_ansible/ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
```
SEANs-MacBook-Pro:infoblox_ansible sean$ ansible-config dump --only-changed
DEFAULT_GATHERING(/Users/sean/Documents/GitHub/infoblox_ansible/ansible.cfg) = explicit
DEFAULT_HOST_LIST(/Users/sean/Documents/GitHub/infoblox_ansible/ansible.cfg) = [u'/Users/sean/Documents/GitHub/infobl
DEPRECATION_WARNINGS(/Users/sean/Documents/GitHub/infoblox_ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/sean/Documents/GitHub/infoblox_ansible/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/Users/sean/Documents/GitHub/infoblox_ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
macOS High Sierra 10.13.3

##### SUMMARY
error using default example in docs (could be doc error)
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument ipv4addrs is of type <type 'dict'> and we were unable to convert to list: <type 'dict'> cannot be converted to a list"}
```

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  connection: local
  vars:
    ansible_network_os: "eos"
  tasks:
    - name: configure an ipv4 host record
      nios_host_record:
        name: automated-host-test
        ipv4:
          address: 192.168.10.200
        state: present
        provider:
          host: 52.86.5.20
          username: admin
          password: REMOVED
      connection: local
```

##### EXPECTED RESULTS
adding host record, finishes playbook

##### ACTUAL RESULTS
```
SEANs-MacBook-Pro:infoblox_ansible sean$ ansible-playbook host_record.yml

PLAY [localhost] ****************************************************************************************************

TASK [configure an ipv4 host record] ********************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument ipv4addrs is of type <type 'dict'> and we were unable to convert to list: <type 'dict'> cannot be converted to a list"}
	to retry, use: --limit @/Users/sean/Documents/GitHub/infoblox_ansible/host_record.retry

PLAY RECAP **********************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```
