### ISSUE TITLE
ec2_lc does not correctly support no_device

### ISSUE THREAD

**Issue by tzejohn** [ansible/ansible#37042]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_lc

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Jun 22 2015, 17:58:13) [GCC 4.8.2]

```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Linux

##### SUMMARY
The `no_device` attribute defined for a volume is getting ignored, and is not correctly represented in the generated `BlockDeviceMappings` for the created launch configuration.

##### STEPS TO REPRODUCE

```yaml
    - name: Create Launch Configurations
      ec2_lc:
        name: "{{ cluster_name }}-lc-{{ item }}"
        region: "{{ ec2_region }}"
        key_name: "{{ key_name }}"
        security_groups:
          - "{{ ec2_group.group_id }}"
        instance_type: "{{ ec2_instance_type }}"
        image_id: "{{ ec2_image }}"
        instance_profile_name: "{{marklogic_role_profile_arn}}"
        volumes:
          - device_name: /dev/sdf
            no_device: true
```

##### EXPECTED RESULTS
The generated launch configuration would ignore the /dev/sdf device that is included in the AMI image.

##### ACTUAL RESULTS
The /dev/sdf device is not ignored and is mounted when the instance is created.
