### ISSUE TITLE
Module vmware_guest is not powering-on VM

### ISSUE THREAD

**Issue by yasa1987** [ansible/ansible#37056]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module **vmware_guest**

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /home/say/ansible/ansible.cfg
  configured module search path = ['/home/say/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
DEFAULT_ASK_PASS(/home/say/ansible/ansible.cfg) = True
DEFAULT_ASK_VAULT_PASS(/home/say/ansible/ansible.cfg) = True
DEFAULT_BECOME(/home/say/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/say/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/say/ansible/ansible.cfg) = ['/home/say/ansible/hosts']
```
##### OS / ENVIRONMENT
Ubuntu 16.04 on Linux Subsystem for Windows 10
`Linux say-laptop 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux`

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial
```

vCenter version : 6.5, latest update

##### SUMMARY
I'm trying to power-on my test VM with _vmware_guest_ and the VM is not powered-on. The module returns a success but nothing happened at all in VMware (there should be a "VM startup" task).

##### STEPS TO REPRODUCE

```yaml
    - name: Start VM
      delegate_to: localhost
      become: false
      vmware_guest:
        hostname: "{{ vsphere_vcenter }}"
        username: "{{ vsphere_user }}"
        password: "{{ vsphere_pass }}"
        name: "{{ inventory_hostname }}"
        datacenter: {{ vsphere_dc_name }}
        folder: "{{ vsphere_dc_name }}{{ vm_folder.folders[0] }}"
        state: poweredon
        force: true
        validate_certs: false
```

##### EXPECTED RESULTS
VM powered-on

##### ACTUAL RESULTS
Nothing happens but the module returns a success
```
TASK [Start VM] *************************************************************************************************
task path: /home/say/ansible/upgrade_process.yml:35
Using module file /usr/local/lib/python3.5/dist-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: say
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/say/.ansible/tmp/ansible-tmp-1520263728.1638055-128656900998967 `" && echo ansible-tmp-1520263728.1638055-128656900998967="` echo /home/say/.ansible/tmp/ansible-tmp-1520263728.1638055-128656900998967 `" ) && sleep 0'
<localhost> PUT /tmp/tmp__3zrrxb TO /home/say/.ansible/tmp/ansible-tmp-1520263728.1638055-128656900998967/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/say/.ansible/tmp/ansible-tmp-1520263728.1638055-128656900998967/ /home/say/.ansible/tmp/ansible-tmp-1520263728.1638055-128656900998967/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python3 /home/say/.ansible/tmp/ansible-tmp-1520263728.1638055-128656900998967/vmware_guest.py; rm -rf "/home/say/.ansible/tmp/ansible-tmp-1520263728.1638055-128656900998967/" > /dev/null 2>&1 && sleep 0'
ok: [********** -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "******",
            "disk": [],
            "esxi_hostname": null,
            "folder": "******",
            "force": true,
            "guest_id": null,
            "hardware": {},
            "hostname": "*********",
            "is_template": false,
            "linked_clone": false,
            "name": "********",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": null,
            "username": "ansible@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}

```
