### ISSUE TITLE
Discrepancy in project_name field of docker_service

### ISSUE THREAD

**Issue by simonszu** [ansible/ansible#37059]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

docker_service

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /home/simonszu/.ansible.cfg
  configured module search path = [u'/home/simonszu/ansile/library,/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]

```

##### OS / ENVIRONMENT

Ansible running on Arch Linux, managed node is Debian Stretch

##### SUMMARY

Documentation of docker_service says: `project_name` is not required. Required when no `definition` is provided.

A module call with a `definition` and no specified `project_name` results in `Parameter error - project_name required when providing definition.`

##### STEPS TO REPRODUCE

Execute the module like described here:

```yaml
- name: Start the container
  docker_service:
    pull: yes
    definition:
      version: '2'
      services:
        geemusic:
          container_name: geemusic
          restart: unless-stopped
          image: 'simonszu/geemusic'
          ports:
          - "5000:5000"
          environment:
          - GOOGLE_EMAIL={{ geemusic_google_login }}
          - GOOGLE_PASSWORD={{ geemusic_google_password }}
          - APP_URL={{ geemusic_app_url }}
          - LANGUAGE={{ geemusic_language }}
```
Notice, `definition` is present, but no `project_name`, like it is not necessary according to the documentation.

##### EXPECTED RESULTS

The playbook/role running without any errors. 

##### ACTUAL RESULTS

```
fatal: [tharan]: FAILED! => {"changed": false, "msg": "Parameter error - project_name required when providing definition."}

```

So i think there is a discrepancy between the module and it's documentation.
