### ISSUE TITLE
rabbitmq_parameter throws ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by mgibula** [ansible/ansible#37066]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
rabbitmq_parameter

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/sh/my-ansible/ansible.cfg
  configured module search path = [u'/home/sh/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

```

##### CONFIGURATION
```
DEFAULT_ACTION_PLUGIN_PATH(/home/sh/my-ansible/ansible.cfg) = [u'/home/sh/my-ansible/plugins/actions']
DEFAULT_FORKS(/home/sh/my-ansible/ansible.cfg) = 50
DEFAULT_HASH_BEHAVIOUR(/home/sh/my-ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/sh/my-ansible/ansible.cfg) = [u'/home/sh/my-ansible/hosts.ini']
DEFAULT_ROLES_PATH(/home/sh/my-ansible/ansible.cfg) = [u'/home/sh/.ansible.roles']
DEFAULT_SUDO_FLAGS(/home/sh/my-ansible/ansible.cfg) = -H -S
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/sh/.vault-pass.txt
```

##### OS / ENVIRONMENT
```
Distributor ID: Ubuntu
Description:    Ubuntu 17.04
Release:        17.04
Codename:       zesty
```

##### SUMMARY
When trying to set rabbitmq federation policy, the error is thrown.

##### STEPS TO REPRODUCE

```yaml
---
- hosts:
    - test-host
  become: yes
  tasks:
    - name: Setting up federation upstream
      rabbitmq_parameter:
        component: federation-upstream
        name: "test-upstream"
        vhost: /
        value: '{"uri":"amqp://server-name","expires":3600000}'
```

##### EXPECTED RESULTS
Works without an error.

##### ACTUAL RESULTS

```
fatal: [test-host]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.11.129.20 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/user/0/ansible_niH3aO/ansible_module_rabbitmq_parameter.py\", line 163, in <module>\r\n    main()\r\n  File \"/tmp/user/0/ansible_niH3aO/ansible_module_rabbitmq_parameter.py\", line 144, in main\r\n    if rabbitmq_parameter.get():\r\n  File \"/tmp/user/0/ansible_niH3aO/ansible_module_rabbitmq_parameter.py\", line 96, in get\r\n    component, name, value = param_item.split('\\t')\r\nValueError: need more than 1 value to unpack\r\n", "msg": "MODULE FAILURE", "rc": 0}
```
