### ISSUE TITLE
with_fileglob should support multiple source and destination while coping like with_items

### ISSUE THREAD

**Issue by liyaka** [ansible/ansible#37088]
##### ISSUE TYPE
 - Bug Report/ Feature Idea

##### COMPONENT NAME
`fileglob.py`

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /xxx/ansible.cfg
  configured module search path = [u'/var/lib/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]```

```

##### CONFIGURATION
```
ANSIBLE_SSH_ARGS(/xxx/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_CALLBACK_PLUGIN_PATH(/xxx/ansible.cfg) = [u'/xxx/plugins']
DEFAULT_FORKS(/xxx/ansible.cfg) = 50
DEFAULT_ROLES_PATH(/xxx/ansible.cfg) = [u'/xxx/roles']
DEFAULT_TIMEOUT(/xxx/ansible.cfg) = 4
DEPRECATION_WARNINGS(/xxx/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/xxx/ansible.cfg) = False
HOST_KEY_CHECKING(/xxx/ansible.cfg) = False
PARAMIKO_RECORD_HOST_KEYS(/xxx/ansible.cfg) = False
RETRY_FILES_ENABLED(/xxx/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ubuntu 16.04

##### SUMMARY
**with_fileglob** should support multiple source and destination while coping like **with_items**
For example:
**This works perfectly**
```
- name: Copy configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ installation_path }}/{{ item.dest }}"
    directory_mode: yes
  with_items:
    - { src: "xxx/templates/slack.tmpl" , dest: "xxx/templates/slack.tmpl" }
    - { src: "yyy/" , dest: "yyy" }
    - { src: "zzz/alert.rules.{{ installation_type }}.yml" , dest: "zzz/alert.rules.yml" }
    - { src: "docker-compose.{{ installation_type }}.yml" , dest: "docker-compose.yml" }
```
**This**:
```
- name: Copy configuration
  copy:
    src: "{{ item.src }}"
    dest: "{{ installation_path }}/{{ item.dest }}"
  with_fileglob:
     - { src: "xxx/*" , dest: "xxx" }
    - { src: "yyy/*" , dest: "yyy" }
    - { src: "zzz/alert.rules.{{ installation_type }}.yml" , dest: "zzz/alert.rules.yml" }
    - { src: "docker-compose.{{ installation_type }}.yml" , dest: "docker-compose.yml" }
```
fails with error:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'dict' object has no attribute 'rfind'
fatal: [sim]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```
##### STEPS TO REPRODUCE
See above

##### EXPECTED RESULTS
Should work the same like **with_items**

##### ACTUAL RESULTS
Fails with error
