### ISSUE TITLE
vmware_guest: add source template scope capability

### ISSUE THREAD

**Issue by jonbenning** [ansible/ansible#37087]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.6.0
```

##### CONFIGURATION
Defaults

##### OS / ENVIRONMENT
Running Ansible on RHEL7, Deploying CentOS

##### SUMMARY
There is currently no way to scope templates for deployment to a datacenter, folder, etc.
If a template exists in multiple Datacenters with the same name (i.e. separate geographic locations, but the same base template), vmware_guest will find multiple copies and fail.

Defaulting to the template in the current datacenter might not be preferable if you have numerous "datacenters" at a physical location - could we implement one of the following:

1) NEW parameter "template_datacenter", which would be the datacenter containing the target template
2) extend the template parameter to accept a folder-like path specification, which could contain the datacenter

##### STEPS TO REPRODUCE

vCenter folder structure:
```
vCenter.domain.com
├─ NorthAmerica
│  ├─ NA-DC1
│  │  ├─ NA-Cluster1
│  │  ├─ ...
│  │  └─ NA-Cluster4
│  │     ├─ VMs
│  │     ├─ ...
│  │     └─ Templates
│  │        └─ CENTOS-TEMPLATE
│  │
│  └─ NA-DC2
│     └─ NA-Cluster5
│        ├─ VMs
│        ├─ ...
│        └─ Templates
│           └─ CENTOS-TEMPLATE
│
└─ Europe
   └─ EU-DC1
      └─ EU-Cluster1
         ├─ VMs
         ├─ ...
         └─ Templates
            └─ CENTOS-TEMPLATE
```

Example Playbook
```
---
- vmware_guest:
    hostname: "{{ vcenter }}"
    username: "{{ username }}"
    password: "{{ password }}"
    datacenter: "{{ datacenter }}"
    cluster: "{{ cluster }}"
    validate_certs: no
    folder: "{{ folder | default('Servers') }}"
    name: "{{ new_hostname }}"
    state: poweredon
    template: "rhel-template"
    wait_for_ip_address: yes

    disk:
    - size_gb: 80
      type: thin
      autoselect_datastore: True

    networks:
    - name: "{{ network}}"
      ip: "{{ ipaddress }}"
      netmask: "{{ netmask }}"
      gateway: "{{ gateway }}"

    customization:
      hostname: "{{ new_host }}"
      domain: " {{ domain }}"
      dns_servers: "{{ dns_server }}"

```

##### EXPECTED RESULTS

Expected successful build
##### ACTUAL RESULTS

Build failure with:

```
 "msg": "Multiple virtual machines or templates with same name [CENTOS-TEMPLATE] found."
```
