### ISSUE TITLE
Include task loop control does not work in ansible 2.3 that ships with Ubuntu 17.10

### ISSUE THREAD

**Issue by nextgenthemes** [ansible/ansible#37097]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
loop control, include task?

##### ANSIBLE VERSION
```
2.3.1.0+dfsg-2
```

##### OS / ENVIRONMENT
Kubuntu 17.10

##### SUMMARY
I just tried my luck with the PPA version after trying to get out of trail and error hell trying to reproduce the simple example below. The docs say "New in version 2.1", Ubuntu comes with 2.3 but I could not get this to work. I got a not syntax error that was not helping at all for whatever i has on the first line after the dash. If I used `- name:` it pointed at the n, if I used `- include_tasks` it pointed at the i.

But after installing the current ppa version 2.4.3.0 that also installed a bunch of python and other packages I finally got it to work. It would be helpful to people if the docs reflect this.

```yaml
# main.yml
- include_tasks: inner.yml
  with_items:
    - 1
    - 2
    - 3
  loop_control:
    loop_var: outer_item

# inner.yml
- debug:
    msg: "outer item={{ outer_item }} inner item={{ item }}"
  with_items:
    - a
    - b
    - c
```

##### EXPECTED RESULTS
Above example to work with the ansible that ships with Ubuntu 17.10 or the docs to tell me that I need the ppa version.
