### ISSUE TITLE
The bug of the module 'lvol'

### ISSUE THREAD

**Issue by QiuMP** [ansible/ansible#37103]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
lvol

##### ANSIBLE VERSION
```
ansible 2.4.0.0
  config file = None
  configured module search path = ['/home/dumbo/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```

##### CONFIGURATION
```
    'ANSIBLE_PIPELINING': 'True',
    'ANSIBLE_HOST_KEY_CHECKING': 'False',
    'ANSIBLE_SCP_IF_SSH': 'True',
    'ANSIBLE_RETRY_FILES_ENABLED': 'False',
```

##### OS / ENVIRONMENT
Debian 9

##### SUMMARY
- The module `lvol` does not support `pvs` when creating a snapshot.
- The module `lvol` dose not get the real path of `pvs` like the module `lvg` when creating a lv.

##### STEPS TO REPRODUCE
The code of creating a snapshot with parameter `pvs`
```yaml
lvol:
  vg: vg
  lv: lv
  pvs: /dev/sdb  # no effect
  size: 10g
  snapshot: lv_snapshot
```

The code of creating a lv with a path error. The path will be recognized as '/dev/disk/by-path/pci-0000', which is different from the module `lvg`.
```yaml
lvol:
  vg: vg
  lv: lv
  pvs: /dev/disk/by-path/pci-0000:03:00.0-scsi-0:2:0:0-part5
  size: 10g
```
