### ISSUE TITLE
digital_ocean module: unique_name does not work on Python 3

### ISSUE THREAD

**Issue by FooBarWidget** [ansible/ansible#37114]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
digital_ocean

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/hongli/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar  1 2018, 19:24:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
I set the following as a var so that Ansible uses the 'python' in PATH instead of /usr/bin/python. 
```
ansible_python_interpreter: python
```

##### OS / ENVIRONMENT
macOS Sierra, Ansible installed via Homebrew.
The 'python' in PATH is Python 3 installed via Homebrew.

##### SUMMARY
The digital_ocean module's "unique_name: true" option does not work as expected on Python 3. If there is already a droplet with the given name, then the module still proceeds to create a droplet with the same name, so that I end up with duplicate droplets.

On Python 2, everything is fine.

##### STEPS TO REPRODUCE

The following playbook expects the user to set the DO_API_TOKEN environment variable first.

```yaml
- hosts: all
  gather_facts: false
  connection: local
  vars:
    # On macOS, use 'python' in PATH instead of /usr/bin/python
    # so that on Homebrew-enabled systems 'pip install dopy' (which
    # the Digital Ocean module requires, and which invokes the Homebrew
    # Python's pip) works as expected.
    ansible_python_interpreter: python
  tasks:
    - digital_ocean:
        name: foo
        unique_name: true
        region_id: ams3
        size_id: 1gb
        image_id: ubuntu-16-04-x64

    - digital_ocean:
        name: foo
        unique_name: true
        region_id: ams3
        size_id: 1gb
        image_id: ubuntu-16-04-x64
```

##### EXPECTED RESULTS
I end up with 1 droplet named "foo".

##### ACTUAL RESULTS
I end up with 2 droplets named "foo".

##### ANALYSIS
The problem is caused by the Droplet.find method in digital_ocean.py. That method calls list_all(), which returns a map. It then iterates over that map 2 times.

In Python 3, map() returns an iterator. When the function loops over the map the first time, the end of the iterator is reached, so that the second loop effectively does nothing.

This is solved by changing the list_all() function so that the resulting map is wrapped in a list(). Change from:

~~~python
    @classmethod
    def list_all(cls):
        json = cls.manager.all_active_droplets()
        return map(cls, json)
~~~

to:

~~~python
    @classmethod
    def list_all(cls):
        json = cls.manager.all_active_droplets()
        return list(map(cls, json))
~~~
