### ISSUE TITLE
cs_instance "user_data" error only when using python3 working in python2

### ISSUE THREAD

**Issue by nbari** [ansible/ansible#37112]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

cs_instance

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /Users/nbari/projects/ansible/ansible.cfg
  configured module search path = ['/Users/nbari/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nbari/Library/Python/3.6/lib/python/site-packages/ansible
  executable location = /Users/nbari/Library/Python/3.6/bin/ansible
  python version = 3.6.4 (default, Mar  1 2018, 18:36:50) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

##### OS / ENVIRONMENT

macOS High Sierra, brew instal python

##### SUMMARY

Error when running the playbook only using python3

##### STEPS TO REPRODUCE

Run playbook using python 3 ` ansible-playbook play.yml`

```yaml
 - name: Creat VM
      cs_instance:
        name: cloudinit-test
        template: Linux CentOS 7.4 64-bit 10G Disk (2018-01-08-d617dd)
        service_offering: Micro
        ssh_key: devops
        api_region: exoscale
        state: started
        tags:
          - key: provisioner
            value: ansible
        user_data: |
            #cloud-config
            package_upgrade: true
            packages:
              - tmux
```

##### EXPECTED RESULTS

no error

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: a bytes-like object is required, not 'str'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 1088, in <module>\n    main()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 1068, in main\n    acs_instance.present_instance()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 668, in present_instance\n    instance = self.update_instance(instance=instance, start_vm=start_vm)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 765, in update_instance\n    args_instance_update['userdata'] = self.get_user_data()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_j03a0m9f/ansible_module_cs_instance.py\", line 682, in get_user_data\n    user_data = base64.b64encode(str(user_data))\n  File \"/usr/local/Cellar/python/3.6.4_3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/base64.py\", line 58, in b64encode\n    encoded = binascii.b2a_base64(s, newline=False)\nTypeError: a bytes-like object is required, not 'str'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
