### ISSUE TITLE
Race condition in password lookup

### ISSUE THREAD

**Issue by dchirikov** [ansible/ansible#37116]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
password lookup module

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.4.2.0
  config file = /root/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
```
# ansible-config dump --only-changed
DEFAULT_HOST_LIST(/root/ansible.cfg) = [u'/root/hosts', u'/etc/ansible/hosts']
RETRY_FILES_SAVE_PATH(/root/ansible.cfg) = /root/.ansible/retry-files
```

##### OS / ENVIRONMENT
Centos 7.4
ansible-2.4.2.0-2.el7.noarch

##### SUMMARY
Race condition in paswword lookup module if task is being run for multiple hosts. As a workaround it's possible to use 2 steps of acquiring passwords: generate first and then fill the variable to store in playbook
Example output:
```
TASK [mongodb : Generate root password for MongoDB and save it to /etc/trinity/passwords] ***
ok: [controller1] => {"ansible_facts": {"tmp_pwd": "2f6eEfb6SoEmp76QCK9S"}, "changed": false}
ok: [controller2] => {"ansible_facts": {"tmp_pwd": "F9UwFND06kdK89CiaGP3"}, "changed": false}

TASK [mongodb : Get root password for MongoDB from /etc/trinity/passwords] *****
ok: [controller1] => {"ansible_facts": {"mongo_root_pwd": "2f6eEfb6SoEmp76QCK9S"}, "changed": false}
ok: [controller2] => {"ansible_facts": {"mongo_root_pwd": "2f6eEfb6SoEmp76QCK9S"}, "changed": false}
```
As it's seen `tmp_pwd` differs and only one var is being stored on disk.

##### STEPS TO REPRODUCE
Run playbook with password lookup with several target hosts.

```yaml
- name: Generate root password for MongoDB and save it to /etc/trinity/passwords
  set_fact:
    tmp_pwd: "{{ lookup('password',
                          '/etc/trinity/passwords/mongo/root.txt
                           chars=ascii_letters,digits,hexdigits') }}"

- name: Get root password for MongoDB from /etc/trinity/passwords
  set_fact:
    mongo_root_pwd: "{{ lookup('password',
                          '/etc/trinity/passwords/mongo/root.txt
                           chars=ascii_letters,digits,hexdigits') }}"
```

##### EXPECTED RESULTS
Passwords should be consistent

##### ACTUAL RESULTS
See above

##### MAIN SUSPECT
https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/password.py#L280

Steps of reading and checking if password is available in file and generating/saving one are split witch opens door for race condition on concurrent runs.

I think it's worth to use `f = os.open(b_path, os.O_CREAT | os.O_EXCL)` and use f as global var or wrap it in the class
