### ISSUE TITLE
Unexpected warning when using template and delegate_to within role

### ISSUE THREAD

**Issue by epilif1017a** [ansible/ansible#37132]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template, with_fileglob, delegate_to

##### ANSIBLE VERSION
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

##### CONFIGURATION
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT
centos-release-7-4.1708.el7.centos.x86_64 

##### SUMMARY
When using the template module within a role, together with fileglob and delegate_to the playbook outputs a warning (see actual results section), but the files are present within the roles' templates folder and are actually sent to the server. If I do not use delegate_to everything works perfectly.

##### STEPS TO REPRODUCE
create role with:
```
- name: sends SQL template files to mysql host(s)
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item | basename | regex_replace('.j2','') }}"
    mode: "0700"
  with_fileglob: ../templates/*.j2
  delegate_to: "{{ groups['mysql-servers'][0] }}"
  tags: configure-databases-users
```
create playbook including this role and execute

##### EXPECTED RESULTS
No warnings

##### ACTUAL RESULTS
[WARNING]: Unable to find '../templates' in expected paths.
