### ISSUE TITLE
lvg module needs additional PATH environment to work with -K (sudo)

### ISSUE THREAD

**Issue by pol** [ansible/ansible#3713]
When running this example task:

``` yaml
- name: remove legacy store volume group if present
  lvg: vg=store state=absent
  environment: 
    PATH: $PATH:/sbin
```

using the following command:

```
ansible-playbook lvm.yml -i development -K 
```

You get the following response:

```
failed: [hostname] => {"err": "/bin/sh: vgs: command not found\n", "failed": true, "rc": 127}
msg: Failed executing vgs command.
```

If you update the task with additional PATH information, like this:

``` yaml
- name: remove legacy store volume group if present
  lvg: vg=store state=absent
  environment: 
    PATH: $PATH:/sbin
```

It then works.  After consulting with the IRC channel, it seems that this is a bug in the module.  The response was "it should call get_bin_path first for path information and then call run_command" (though I am not entirely clear on what that means).
