### ISSUE TITLE
cs_instance "user_data"  and "state: destroyed" return  An exception occurred during task execution 

### ISSUE THREAD

**Issue by nbari** [ansible/ansible#37138]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /Users/nbari/ansible/ansible.cfg
  configured module search path = [u'/Users/nbari/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/nbari/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/nbari/Library/Python/2.7/bin/ansible
  python version = 2.7.14 (default, Mar  1 2018, 19:24:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

##### OS / ENVIRONMENT

macOS High Sierra, brew install python2

##### SUMMARY

when using the `state: destroyed` and using/having `user_data` the instance is destroyed but an error 
is displayed

##### STEPS TO REPRODUCE

`ansible-playbook play.yml`

The first time will return an error but after running it the second time it will just work fine ( no error)

```yaml
 - name: Creat VM
      cs_instance:
        name: cloudinit-test
        template: Linux CentOS 7.4 64-bit 10G Disk (2018-01-08-d617dd)
        service_offering: Micro
        ssh_key: devops
        api_region: exoscale
        state: destroyed
        tags:
          - key: provisioner
            value: ansible
        user_data: |
            #cloud-config
            package_upgrade: true
            packages:
              - tmux
```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'id'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_b9HigX/ansible_module_cs_instance.py\", line 1088, in <module>\n    main()\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_b9HigX/ansible_module_cs_instance.py\", line 1078, in main\n    result = acs_instance.get_result(instance)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_b9HigX/ansible_module_cs_instance.py\", line 973, in get_result\n    self.result['user_data'] = self._get_instance_user_data(instance)\n  File \"/var/folders/75/8jzhscr56j13rv6tj6805ch40000gn/T/ansible_b9HigX/ansible_module_cs_instance.py\", line 544, in _get_instance_user_data\n    res = self.cs.getVirtualMachineUserData(virtualmachineid=instance['id'])\nKeyError: 'id'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
