### ISSUE TITLE
psycopg2 is installed but postgresql_user gives error "the python psycopg2 module is required". 

### ISSUE THREAD

**Issue by gearoidibm** [ansible/ansible#37147]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
postgresql_user

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [<redacted>']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
default, no changes made

##### OS / ENVIRONMENT
from: macOS 10.13.3 
managed: RHEL 7.4: 3.10.0-693.5.2.el7.x86_64

##### SUMMARY
The postgresql_user command fails with the error message
`FAILED! => {"changed": false, "msg": "the python psycopg2 module is required"}`

psycog2 module was installed using ansible pip module on the managed system
```
bash-4.2$ pip list | grep psycopg2
psycopg2 (2.7.4)
```
##### STEPS TO REPRODUCE
run task as below.

```yaml
- hosts: dbs
  become: yes

  # add the replication user to postgres
  tasks:
  - name: create rep postgres user
    postgresql_user:
      name: rep
      password:  notthepassword
      role_attr_flags: REPLICATION, LOGIN
```

##### EXPECTED RESULTS
user is created

##### ACTUAL RESULTS

task fails

```
The full traceback is:
  File "/tmp/ansible_Jd0XzG/ansible_module_postgresql_user.py", line 213, in <module>
    import psycopg2

fatal: [<hostname>]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "conn_limit": null,
            "db": "",
            "encrypted": false,
            "expires": null,
            "fail_on_user": true,
            "login_host": "",
            "login_password": "",
            "login_unix_socket": "",
            "login_user": "postgres",
            "name": "rep",
            "no_password_changes": false,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": "5432",
            "priv": null,
            "role_attr_flags": "REPLICATION, LOGIN",
            "ssl_mode": "prefer",
            "ssl_rootcert": null,
            "state": "present",
            "user": "rep"
        }
    },
    "msg": "the python psycopg2 module is required"
```
