### ISSUE TITLE
Missing support for virtualmachine generlize process in azure_rm_image

### ISSUE THREAD

**Issue by kwoodson** [ansible/ansible#37158]
When attempting to run the azure_rm_image module to create an image from a vm, it fails stating the vm needs to be generalized.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_image

##### ANSIBLE VERSION
```
ansible 2.5.0rc1 (stable-2.5 fccb6962fe) last updated 2018/03/06 09:55:16 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kwoodson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kwoodson/git/ansible/lib/ansible
  executable location = /home/kwoodson/git/ansible/bin/ansible
  python version = 2.7.14 (default, Dec 11 2017, 16:08:01) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
# returns empty
```

##### OS / ENVIRONMENT
Fedora release 26 (Twenty Six)

##### SUMMARY
When attempting to create an image from a vm using azure_rm_image it fails with the error message:
```
 "msg": "Error creating image rhel7.4_base-1520453225 - Azure Error: OperationNotAllowed\nMessage: The operation 'Create Image' requires the Virtual Machine 'opstest' to be Generalized."
```

##### STEPS TO REPRODUCE
1. Create a public ip address
```
azure_rm_publicipaddress
```
2. Create a  network interface
```
azure_rm_networkinterface:
```
3. Create a virtualmachine using a custom image.
```
  azure_rm_virtualmachine:
    resource_group: "{{ openshift_azure_resource_group_name }}"
    name: "{{ openshift_azure_vm_name }}"
    vm_size: "{{ openshift_azure_vm_size }}"
    storage_account_name: "{{ openshift_azure_storage_account_name }}"
    admin_username: "{{ openshift_azure_vm_admin_username }}"
    admin_password: "{{ openshift_azure_vm_admin_password | default(omit) }}"
    ssh_password_enabled: "{{ openshift_azure_vm_ssh_pw_enabled }}"
    network_interfaces: "{{ openshift_azure_virtual_network_name }}"
    ssh_public_keys: "{{ openshift_azure_vm_ssh_public_keys if openshift_azure_vm_ssh_public_keys != [] else omit }}"
    os_type: Linux
    image: "{{ openshift_azure_vm_base_image }}"
  register: azurevm
```
4. De-allocate virtualmachine
```
azure_rm_virtualmachine:
  allocate: no
   ...
```
5. Create an image from the virtual machine.
```
azure_rm_image:
    resource_group: "{{ openshift_azure_resource_group_name }}"
    source: "{{ openshift_azure_vm_name }}"
    name: "{{ openshift_azure_image_name }}-{{ ansible_date_time.epoch }}"
    os_type: Linux
```

##### EXPECTED RESULTS
The image would get created.

##### ACTUAL RESULTS
It failed telling me that my virtual machine needs to be generalized.
```
   "msg": "Error creating image rhel7.4_base-1520453225 - Azure Error: OperationNotAllowed\nMessage: The operation 'Create Image' requires the Virtual Machine 'opstest' to be Generalized."
```

Add module support to generalize images:
```yaml
- name: generalize the vm
  command: "az vm generalize --resource-group {{ openshift_azure_resource_group_name }} --name {{ openshift_azure_vm_name }}"
```
Once I ran the above command before step 5 in the steps above I was successfully able to create my image.

Currently there is no support or at least I could not find documented support for virtual machine generalization.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_image.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_image.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @yuwzho
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
@kwoodson  You can refer [this integration](https://github.com/ansible/ansible/blob/devel/test/integration/targets/azure_rm_image/tasks/main.yml#L62) test to deallocate the VM and create an image

**Comment by kwoodson** [comment]
@yuwzho,

Thanks for the reply.  I found that documentation and was attempting that same procedure except the referenced example is not creating an image from a virtual machine as far as I can tell.  It looks like it is creating an image from a disk.  See below:
```
- name: Create an image from VM (check mode)
  azure_rm_image:
      resource_group: "{{ resource_group }}"
      source: "https://{{ storage_account }}.blob.core.windows.net/testvm001/testvm001.vhd"
      name: testimage001
      os_type: Linux
  check_mode: yes
  register: output
```
Notice the source is the path to a `vhd`.  This is not a virtual machine but a virtual machine's disk.  The example code works fine if you are using a virtual machine's disk.  It does _not_ work when using a virtual machine.

Here is my code https://github.com/kwoodson/openshift-ansible/blob/azure_provisioning/roles/openshift_azure/tasks/create_image_from_vm.yml#L32-L37

Notice the parameters are pointing to a virtual machine.  With this code I was able to create an image from a virtual machine.

If you have a better way of creating an image from a virtual machine I'd love the assistance or if you have another method of performing the `generalize`  required by the `az vm generalize` then that'd be great too.

Thanks again!

**Comment by Fred-sun** [comment]
@yuwzho About this issue, do you have any other view?

**Comment by Fred-sun** [comment]
@yuwzho Could you help update the comment? Thanks!

**Comment by Fred-sun** [comment]
@yuwzho Could you help update the comment? Thanks!

**Comment by Fred-sun** [comment]
@yuwzho Could you help update the comment? Thanks!

**Comment by Fred-sun** [comment]
@kwoodson Thanks for the contribution, if you want create VM image from virtual machine, don't need to generalize and allocate, you can use azure_rm_image module create image . just like follow YML. Could you try it( I have try and get successful result)? thanks!
You also can upgrade your ansible version to latest (sudo pip install ansible[auzre] --upgrade)
```e.g.
- name: Create an image from VM
  azure_rm_image:
      resource_group: "{{ resource_group }}"
      source: "resource ID"
      name: image_name
      os_type: Linux

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by zikalino** [comment]
use this:
```
  - name: Call REST API - VirtualMachines_Generalize
    azure_rm_resource:
      api_version: '2017-12-01'
      method: POST
      resource_group: "{{ resource_group }}"
      provider: compute
      resource_type: virtualmachines
      resource_name: "{{ vm_name }}"
      subresource:
        - type: generalize
  ```
