### ISSUE TITLE
Module package: Please add "allow_unauthenticated" option.

### ISSUE THREAD

**Issue by robertdebock** [ansible/ansible#37169]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
package

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/yf30lg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /Users/yf30lg/Library/Python/2.7/bin/ansible
  python version = 2.7.14 (default, Feb  6 2018, 20:04:00) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT
Control node:: Mac OS X
Managed node: Debian & Ubuntu

##### SUMMARY
The module `apt` [allows an option](http://docs.ansible.com/ansible/latest/apt_module.html#options) `allow_unauthenticated` to be set.
It would be great if the `package` module would support this option.

##### STEPS TO REPRODUCE
When installing packages to multiple distributions, a split has to be created to set the apt option `allow_unauthenticated`:

```yaml
- name: install mysoftware (package)
  package:
    name: mysoftware
  when:
    - ansible_pkg_mgr != "apt"

- name: install mysoftware (apt)
  apt:
    name: mysoftware
    allow_unauthenticated: yes
  when:
    - ansible_pkg_mgr == "apt"
```

##### EXPECTED RESULTS
The following (pseudo) code could be used after this feature is implemented:
```
- name: install mysoftware (package)
  package:
    name: mysoftware
    allow_unauthenticated: yes
```

The option `allow_unauthenticated` can be ignored for any other `ansible_pkg_mgr` than `apt`.

##### ACTUAL RESULTS
```
WARNING: The following packages cannot be authenticated!
```

I've seen this error when building an Ansible Role [mssql](https://github.com/robertdebock/ansible-role-mssql). The code that [showed this error](https://travis-ci.org/robertdebock/ansible-role-mssql/jobs/347155438) is found [in this commit](https://github.com/robertdebock/ansible-role-mssql/commit/40d2915a07e10b258d1c6ecbcf6c98b74a4758b3).
