### ISSUE TITLE
Exception is raised while accessing to a dictionnary as src in a template

### ISSUE THREAD

**Issue by jbarotin** [ansible/ansible#37193]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  [...]
  python version = 2.7.14 (default, Jan  3 2018, 12:57:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT
OSX 

##### STEPS TO REPRODUCE
See at the playbook below :
```yaml
- name: test
  hosts: myhost
  remote_user: auser
  vars:
    a_dictionary:
      myhost:
        file: "myfile.txt"
  tasks:
    - template:
        src: "{{ a_dictionary[ inventory_hostname] }}"
        dest: /home/auser/myfile.txt

```

##### EXPECTED RESULTS
I need a comprehensive error message, when I execute this playbook.

##### ACTUAL RESULTS
```
PLAY [test] *************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************
ok: [myhost]

TASK [template] *********************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'dict' object has no attribute 'startswith'
fatal: [myhost]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}

PLAY RECAP **************************************************************************************************************************
paul101.preprod.s4e.fr     : ok=1    changed=0    unreachable=0    failed=1
```
ps: big thanks to the ansible team for this beautiful piece of software !!!
