### ISSUE TITLE
vmware_guest - Create VM from template with IP settings

### ISSUE THREAD

**Issue by Gaby033** [ansible/ansible#37198]
This looks like this issue : #33380 but there was no activity since 2 months there, so I decided to open my own issue (hope I did well :D)

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
No changes

##### OS / ENVIRONMENT
AWX version: 1.0.4.57
AWX install method: docker on linux
Operating System: Centos 7.4

Inside docker container ansible/awx_task  (latest) : 
pip version : 9.0.1
pyvmomi==6.5.0.2017.5.post1

##### SUMMARY
I'm trying to clone a VM template in one of my esxi (VMware ESXi 5.5.0) in the vcenter and edit the network configuration. Which means : ip, netmask, gateway, dns servers.

##### STEPS TO REPRODUCE
I'm running my playbook via AWX giving some parameters.

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  
  tasks:
  - name: Create a VM from a template
    vmware_guest:
      hostname: my.vcenter.com
      username: '{{ vsphere_user }}'
      password: '{{ vsphere_password }}'
      validate_certs: no
      name: '{{ vm_name }}'
      state: poweredon
      template: Debian7.8
      datacenter: MyDataCenterName
      esxi_hostname: '{{ esxi }}'
      hardware:
        memory_mb: '{{ ram }}'
        num_cpus: '{{ cpu }}'
        scsi: lsilogic
      customization:
        autologon: yes
        dns_servers:
        - X.X.X.1
        - X.X.X.2
        domain: domain.com
        password: '{{ vm_password }}'
      networks:
      - name: VLAN_NAME
        ip: '{{ ip }}'
        netmask: '{{ netmask }}'
        gateway: '{{ gateway }}'
        vlan: 10
        type: static
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
```

On the template VM (Debian 7.8) : 
```
open-vm-tools : 10.1.5-5055683-1 (start on boot)
perl : 5.14.2
```

##### EXPECTED RESULTS
Create the VM with the correct network configuration.

##### ACTUAL RESULTS
https://gist.github.com/Gaby033/99bcbe60a463ecf7491cccfd8e310fb7

No error, **the VM is correctly cloned**, but the /etc/resolv.conf file of the newly created VM isn't overwritten and same goes for /etc/network/interfaces.
