### ISSUE TITLE
consul_kv cas opertation broken

### ISSUE THREAD

**Issue by freeseacher** [ansible/ansible#37224]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
consul_kv

##### ANSIBLE VERSION
```
ansible 2.5.0rc1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/tower/lib/python2.7/site-packages/ansible
  executable location = /opt/tower/bin/ansible
  python version = 2.7.14 (default, Jan 10 2018, 05:38:41) [GCC 6.3.0]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(env: ANSIBLE_SSH_PIPELINING) = True
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/opt/tower/var/tower/playbooks/NOC/additional_roles', u'/opt/tower/var/tower/playbooks/NOC/system_roles', u'/opt/tower/var/tower/playbooks/NOC/noc_roles']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Cas operation require read than update if changed. last ansible version fails with

##### STEPS TO REPRODUCE
```
# Read default value.
- name: Read key/value pair for key {{consul_service_key}}
  consul_kv:
    key: "{{consul_service_key}}"
    cas: 0
    #token: "{{consul_service_token}}"
register: consul_key_response
```
full file: https://github.com/nocproject/ansible_deploy/blob/microservices/system_roles/consul/tasks/service_config_update.yml

##### EXPECTED RESULTS
Read operation completed ok. as on 2.4.3

##### ACTUAL RESULTS
```
TASK [consul : Read key/value pair for key noc/slots/discovery-default/manifest] ***
fatal: [node1]: FAILED! => {
    "changed": false
}

MSG:

state is present but all of the following are missing: value
```

Also no changes mention to that module in changelog

**Comment by freeseacher** [comment]
As far as i can see changes made in https://github.com/ansible/ansible/pull/32340 by @dagwieers 
Dag can you please made value not required as it was before.

**Comment by ansibot** [comment]
cc @sgargan
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by freeseacher** [comment]
@dagwieers

**Comment by freeseacher** [comment]
@dagwieers @sgargan is 2.5 will be broken for consul_kv ?

**Comment by freeseacher** [comment]
bump

**Comment by ansibot** [comment]
cc @colin-nolan
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by freeseacher** [comment]
@nitzmahone What for are you releasing rc versions if release comes with introduced broken modules ?

**Comment by colin-nolan** [comment]
I don't think this issue is actually related to CAS operations - if you just want to read a value, CAS is irrelevant. The problem is that you're trying to retrieve a value (which is a reasonable thing to want to do!) but such an operation was not actually supported.

In #37837 I've added support to retrieve values. Does this make the module work as you expect?

**Comment by freeseacher** [comment]
Nope. 
debug result 
```
{
    "consul_key_response": {
        "changed": true, 
        "data": {
            "CreateIndex": 4716, 
            "Flags": 0, 
            "Key": "noc/slots/discovery-default/manifest", 
            "LockIndex": 0, 
            "ModifyIndex": 4716, 
            "Value": "<object object at 0x7f47773ba970>"
        }, 
        "failed": false, 
        "index": "4716", 
        "key": "noc/slots/discovery-default/manifest"
    }
}
```

**Comment by freeseacher** [comment]
if not module.params.get('value'):
            get_value(module)
        else:
            add_value(module)

**Comment by freeseacher** [comment]
```
        if not module.params.get('value'):
            get_value(module)
        else:
            add_value(module)
```
went to add_value(module). cause of wrong check with NOT_SET object

**Comment by colin-nolan** [comment]
@freeseacher I don't understand where the conditional you show above is coming from? In [the PR the conditional looks like this](https://github.com/wtsi-hgi/ansible/blob/cfa1b654f225498cd59df1edbea0e8229009a915/lib/ansible/modules/clustering/consul_kv.py#L168-L171):
```python
if module.params.get('value') == NOT_SET:
    get_value(module)
else:
    add_value(module)
```
 
Is there some other code that I'm missing here?

**Comment by freeseacher** [comment]
nope. 
i just replace it with
            value=dict(type='str', default=None),
and check as above. 
and it works.

**Comment by colin-nolan** [comment]
It would be great if you could test the [code in the pull request](https://github.com/ansible/ansible/pull/37837), opposed to a variation of it, as it is this what will end up merged.

**Comment by freeseacher** [comment]
code in pull request is not work. insted of reading we are going to `add_value(module)` function. so there have  `"Value": "<object object at 0x7f47773ba970>"`in value after read request

**Comment by colin-nolan** [comment]
Thanks for confirming. I can only assume that the `AnsibleModule` constructor is converting the `NOT_SET` value to a string. Oddly, I couldn't replicate the problem though but it does seem reasonable for this to happen, given the type _is_ defined as a string.

As you did, I've gone with setting the default value to `None`. I was reluctant to do this initially as the [python-consul library documentation](https://python-consul.readthedocs.io/en/latest/#consul-kv) implies that `None` has a special meaning; looking at the code, it omits the request data when the value is set to `None`. However, the [Consul API documentation](https://www.consul.io/api/kv.html#create-update-key) states that the value defaults to empty string if this is the case and hence `None` is not so special after all.

@freeseacher it would be great to know if it's now good on your end :)

**Comment by freeseacher** [comment]
@colin-nolan 
my use case is to init value in consul during deploy. if it is changed in inventory i want to update it in consul
i have such task in the play
```
- name: call consul to setup discovery
  run_once: "True"
  include_role:
    name: consul
    tasks_from: service_config_update
  vars:
    consul_service_key: "noc/slots/discovery-{{item}}/manifest"
    consul_service_internal_key: "Limit"
    consul_service_value: "...."
  with_items: "..."
```

in consul role i have `service_config_update`
```
# Read default value.
- name: Read key/value pair for key {{consul_service_key}}
  consul_kv:
    key: "{{consul_service_key}}"
    state: read_only
  vars:
    ansible_python_interpreter: "{{consul_control_python}}"
  register: consul_key_response
  check_mode: "False"
```
that will fail if no key. with 
```
fatal: [node1]: FAILED! => {
    "changed": false
}

MSG:

No key(s) found in specified path!
```
so i can't check if it is already there. i think that can be fixed pretty simple.
then if value is unset i have to create templated json and put it there. of cause with cas operation. 
```
- name: init default if unset
  consul_kv:
    key: "{{consul_service_key}}"
    value: "{{ service_tmpl | to_nice_json }}"
    cas: "{{consul_key_response.index}}"
  vars:
    service_tmpl:
      Holders: []
      Limit: "{{consul_service_value | int}}"
    ansible_python_interpreter: "{{consul_control_python}}"
  when:
????????????????
```
and if it is already there i have to update value to new one. 
```
- name: Update a key/value pair for key {{consul_service_key}}
  consul_kv:
    key: "{{consul_service_key}}"
    value: "{{ consul_key_response.data.Value
            | from_json
            | combine({ consul_service_internal_key: consul_service_value })
            | to_nice_json
            }}"
    cas: "{{consul_key_response.index}}"
    #token: "{{consul_service_token}}"
  vars:
    ansible_python_interpreter: "{{consul_control_python}}"
  when: 
???????????????
```

semantic were exists in 2.4.3 with cas 0 and state: present works exactly as expected. how should i do it in new one ?

**Comment by freeseacher** [comment]
of cause there were an error. 
The key was created during the very first 'Read' request. but i can live with it and handle it well. 
current code i really can't understand how to adapt

**Comment by colin-nolan** [comment]
With https://github.com/ansible/ansible/pull/37837 you would do:
```yml
- name: Read key/value pair for key {{consul_service_key}}
  consul_kv:
    key: "{{consul_service_key}}"
  vars:
    ansible_python_interpreter: "{{consul_control_python}}"
  register: consul_key_response
```
which won't fail if the key isn't there, rather it will return something that looks like this:
```
{"index": "432454", "changed": False, "data": None, "failed": False}
```

Then your conditionals are based on the values of `data`, e.g.:
```yml
when: consul_key_response["data"] is None
```
