### ISSUE TITLE
NX_OS ignoring save_snapshot_locally.

### ISSUE THREAD

**Issue by rogerscuall** [ansible/ansible#37227]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
nxos_snapshot

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = /Users/naruto/Documents/GitHub/customers/uhcs/uhcs-core-refresh/ansible/ansible.cfg
  configured module search path = [u'/Users/naruto/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
```
[defaults]
deprecation_warnings = False
host_key_checking = False
inventory = inventory/network
gathering = explicit
callback_whitelist = profile_tasks
[paramiko_connection]
host_key_auto_add = True
```

##### OS / ENVIRONMENT
NX-OS nxos.7.0.3.I2.2d.bin

##### SUMMARY
The module is creating the snapshot but is not saving the snapshot locally.

##### STEPS TO REPRODUCE
Using this:
```
- name: save configuration for nxos
  nxos_snapshot:
    action: create
    snapshot_name: "{{ inventory_hostname }}-{{ timestamp }}"
    description: "snapshot-{{ timestamp }}"
    save_snapshot_locally: true
    path: "{{ playbook_dir }}/nexus-snapshots/"
  when: inventory_hostname in groups['nxos']
```

##### EXPECTED RESULTS
One or more files under the folder **nexus-snapshots**.

##### ACTUAL RESULTS
The snapshot is created but is not copied locally.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nxos/nxos_snapshot.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_snapshot.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @GGabriele @kedarX @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rogerscuall** [comment]
Also if the `action=compare` the result is not copied locally either, although it looks like the comparison is happening.

**Comment by rogerscuall** [comment]
I also found that using this:
```
  nxos_snapshot:
    action: compare
    snapshot2: n9k-leaf1-20180308182236Z
    snapshot1: n9k-leaf1-20180308182052Z
    compare_option: summary
```
Will return an error:
```
fatal: [n9k-leaf1]: FAILED! => {"changed": false, "failed": true, "msg": "snapshot1 and snapshot2 are required when action=create"}
```
That should be another problem, snapshot1 and snapshot2 is only for `action=compare`.
Thanks.

**Comment by trishnaguha** [comment]
@rogerscuall I am unable to reproduce your issue with `action:create`. It works fine for me.
For `action: compare`, `comparison_results_file` is a required option.
Fixed the doc, and required option check in the PR https://github.com/ansible/ansible/pull/37232.

Can you please try the module on devel branch?
To test on devel branch:
```
git clone https://github.com/ansible/ansible.git
cd ansible
source hacking/env-setup
```
`ansible --version` should return `devel 2.6.0`.

I tried this playbook:
```
  - name: create snapshot1
    nxos_snapshot:
      action: create
      snapshot_name: test_snapshot1
      description: Ansible
      save_snapshot_locally: true
      path: "{{ playbook_dir }}/nexus/"

  - name: create snapshot2
    nxos_snapshot:
      action: create
      snapshot_name: test_snapshot2
      description: row
      section: myshow
      show_command: show ip interface brief
      row_id: ROW_intf
      element_key1: intf-name
      path: "{{ playbook_dir }}/nexus/"

  - name: compare snapshots
    nxos_snapshot:
      action: compare
      snapshot1: test_snapshot1
      snapshot2: test_snapshot2
      comparison_results_file: compare_snapshots.txt
      compare_option: summary
      path: "{{ playbook_dir }}/nexus/"
```
