### ISSUE TITLE
Could not match supplied host pattern, ignoring while provisioning with vagrant

### ISSUE THREAD

**Issue by bentcoder** [ansible/ansible#37221]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
inventory

##### ANSIBLE VERSION
```
ansible 2.4.3.0
```

##### CONFIGURATION
```
ansible-config 2.4.3.0
  config file = None
  configured module search path = [u'/Users/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-config
  python version = 2.7.14 (default, Mar  6 2018, 19:44:24) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
No config file found; using defaults
```

##### OS / ENVIRONMENT
Mac Os 10.10.5

##### SUMMARY
Getting `[WARNING]: Could not match supplied host pattern, ignoring: webservers` message while running provisioning with vagrant up.

##### STEPS TO REPRODUCE

**demo/hosts**
```
[webservers]
web1
```

**demo/site.yml**
```
---

- name: Apply common configuration to "all" hosts
  hosts: all
  remote_user: root
  roles:
    - common

- name: Apply web configuration to "webservers" hosts
  hosts: webservers
  remote_user: root
  roles:
    - web
```

**demo/provisioning/roles/common/tasks/main.yml**
```
---

- name: Update apt packages
  apt:
    update_cache: yes
  become: yes
  tags:
    - system

- name: Set time zone to Europe/London
  timezone:
    name: Europe/London
  become: yes
  tags:
    - system
```

**demo/provisioning/roles/web/tasks/main.yml**
```
---

- name: Install nano
  apt:
    name: nano
    state: present
  tags:
    - nano
```

**demo/Vagrantfile**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    N = 2
    (1..N).each do |machine_id|
        config.vm.define "machine#{machine_id}" do |machine|
            machine.vm.hostname = "machine#{machine_id}"
            machine.vm.network "private_network", ip: "192.168.77.#{20+machine_id}"
            machine.vm.synced_folder "www#{machine_id}", "/srv/www", create: true

            machine.vm.provider :virtualbox do |virtualbox|
                virtualbox.name = "demo#{machine_id} - 192.168.77.#{20+machine_id} - 16.04"
            end

            if machine_id == N
                machine.vm.provision :ansible do |ansible|
                    ansible.limit = "all"
                    ansible.playbook = "provisioning/site.yml"
                end
            end
        end
    end

end
```

##### EXPECTED RESULTS
I expect not to see warning message if it is not related to my config :)

##### ACTUAL RESULTS
```
demo$ vagrant up
```

```
...
...

PLAY [Apply common configuration to "all" hosts] *******************************

TASK [Gathering Facts] *********************************************************
ok: [machine1]
ok: [machine2]

TASK [common : Update apt packages] ********************************************
changed: [machine2]
changed: [machine1]

TASK [common : Set time zone to Europe/London] *********************************
changed: [machine2]
changed: [machine1]

 [WARNING]: Could not match supplied host pattern, ignoring: webservers


PLAY [Apply web configuration to "webservers" hosts] ***************************
skipping: no hosts matched

PLAY RECAP *********************************************************************
machine1                   : ok=2    changed=2    unreachable=0    failed=0   
machine2                   : ok=2    changed=2    unreachable=0    failed=0
```

![oracle](https://user-images.githubusercontent.com/8837278/37177928-d4cdc608-2318-11e8-9f47-22cb3ca204d2.png)
