### ISSUE TITLE
cloudfront_distribution changes forwarded headers order again and again

### ISSUE THREAD

**Issue by gevial** [ansible/ansible#37239]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
cloudfront_distribution

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/gennadii_aleksandrov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gennadii_aleksandrov/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /Users/Gennadii_Aleksandrov/Library/Python/2.7/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### SUMMARY
Ansible always trying to change CloudFront distribution's forwarded headers order.

##### STEPS TO REPRODUCE

1. Create CloudFront distribution with forwarded headers as shown below:

```yaml
        default_cache_behavior:
            headers:
              - X-HTTP-Forwarded-For
              - CloudFront-Forwarded-Proto
              - Host
              - Origin
              - Referer
```
2. Run playbook again

##### EXPECTED RESULTS

CloudFront distribution should bot be changed.
##### ACTUAL RESULTS

CloudFront distribution has been changed:
```
TASK [Create CloudFront distribution] ********************************************************************************************************************************
--- before
+++ after
@@ -3,11 +3,11 @@
         "ForwardedValues": {
             "Headers": {
                 "Items": [
+                    "X-HTTP-Forwarded-For",

                     "CloudFront-Forwarded-Proto",
                     "Host",
                     "Origin",
-                    "Referer",
-                    "X-HTTP-Forwarded-For"
+                    "Referer"
                 ]
             }
         }

changed: [localhost]
```
