### ISSUE TITLE
Display terraform stdout interactively

### ISSUE THREAD

**Issue by okgolove** [ansible/ansible#37247]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

terraform

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/venv/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/ubuntu/venv/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

I want to see stdout from terraform interactively

##### STEPS TO REPRODUCE

Just run terraform applying

```yaml
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Deploy infrastructure
      terraform:
        project_path: ./terraform
        force_init: true
        state: absent
        variables:
          aws_access_key: <access key>
          aws_secret_key: <secret key>
          cluster_tag: ansible-test
          aws_region: us-east-2
~

```

##### EXPECTED RESULTS

Dynamic stdout from terraform
##### ACTUAL RESULTS

I don't know what's happening during `terraform apply` or `terraform destroy`.
