### ISSUE TITLE
Got stuck on raw module for Aix machine

### ISSUE THREAD

**Issue by arsh9295** [ansible/ansible#37240]
##### ISSUE TYPE

 - Bug Report
##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### SUMMARY
Using row module for python, it is fine when not using AIX machine, but it got stuck on raw module with AIX machine 

##### STEPS TO REPRODUCE

main.yaml

# tasks file for abcd
```
- pause:
    prompt: "Select From Below Options:\n1. install \n2. uninstall\n3. status\n"
  register: optn1
  run_once: true
- set_fact: "{{ optn1 }}"
- name: including variable
  include_vars: ../vars/variables.yml
- block:
    - raw: dnf install -y python2 python2-dnf libselinux-python
      failed_when: false
      no_log: true
      #ignore_errors: yes
    - raw: yum -y install python-simplejson
      failed_when: false
      no_log: true
      #ignore_errors: yes
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      failed_when: false
      no_log: true
      #ignore_errors: yes
 - setup:
- include_tasks: "{{ optn1.user_input }}.yml"
  when: ( optn1.user_input == "install" ) or ( optn1.user_input == "uninstall" )  or (optn1.user_input == "status"
```
# Inventory

```
--------------------------------------------------------------------------
hosts
[redhat]
redhat1
redhat2
centos1

[Ubuntu]
utkarsh-ubuntu

[AIX]
utkarsh-aix
```

##### ACTUAL RESULTS

Got sucked

**Comment by arsh9295** [comment]
Please update status of this bug.

**Comment by arsh9295** [comment]
@rcarrillocruz you need any info from my side ?, Please let me know.

**Comment by willtome** [comment]
@arsh9295 I have seen similar behavior before but would like to try and reproduce. Can you run a few additional tests and provide the results?
1) ad-hoc command with raw module `ansible AIX -i inventory -m raw -a uptime -vvvv`
2) a playbook with a single task using raw module 
```
---
- hosts: AIX
  gather_facts: no
  tasks:
  - raw: uptime
```
3) a playbook with 2 tasks using the raw module
```
---
- hosts: AIX
  gather_facts: no
  tasks:
  - raw: uptime
  - raw: uptime
```

Please run playbooks with full connection verbosity `-vvvv`
