### ISSUE TITLE
maven_artifact should support check mode and return URL

### ISSUE THREAD

**Issue by ericcitaire** [ansible/ansible#37242]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
maven_artifact

##### ANSIBLE VERSION

```
ansible 2.4.1.0
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
N/A

##### SUMMARY
`maven_artifact` should support check mode and return artifact URL. Or have a state `resolve`.

This could be useful, for example, to resolve an artifact URL and use it with `unarchive` without having to download the artifact in a temporary location (see an example in steps to reproduce).

I could work on this if needed. Just not right now, maybe in a week or two. Let me know.

##### STEPS TO REPRODUCE
```yaml
---
- hosts: tomcat
  tasks:
    - name: Resolve Tomcat URL
      maven_artifact:
        group_id: org.apache.tomcat
        artifact_id: tomcat
        version: 9.0.5
        extension: tar.gz
        dest: /dev/null
      check_mode: yes
      register: tarball

    - name: Install Tomcat
      unarchive:
        src: "{{ tarball.url }}"
        dest: /opt/tomcat
        remote_src: yes
```

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
