### ISSUE TITLE
Common handlers get applied to ONLY single machine when provisioning more than one machines

### ISSUE THREAD

**Issue by bentcoder** [ansible/ansible#37266]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
inventory

##### ANSIBLE VERSION
```
ansible 2.4.3.0
```

##### CONFIGURATION
```
ansible-config 2.4.3.0
  config file = None
  configured module search path = [u'/Users/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-config
  python version = 2.7.14 (default, Mar  6 2018, 19:44:24) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
No config file found; using **defaults**
```

##### OS / ENVIRONMENT
Mac Os 10.10.5

##### SUMMARY
When one machine is provisioned, NTP is synchronized on it. However, when two machines are provisioned, NTP is synchronized on `linux2` but not on the `linux1`.

##### STEPS TO REPRODUCE

Run `$ vagrant up` to reproduce the issue.

**demo/Vagrantfile**
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/xenial64"

    config.vm.define :linux1 do |linux1|
        linux1.vm.synced_folder "linux1", "/srv/www", create: true, nfs: true, mount_options: ["actimeo=2"]

        linux1.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "linux1 - 192.168.99.31"
        end

        linux1.vm.hostname = "linux1"
        linux1.vm.network "private_network", ip: "192.168.99.31"

        linux1.vm.provision :ansible do |ansible|
            ansible.verbose = "-vv"
            ansible.inventory_path = "provisioning/hosts.yml"
            ansible.playbook = "provisioning/site.yml"
        end
    end

    config.vm.define :linux2 do |linux2|
        linux2.vm.synced_folder "linux2", "/srv/www", create: true, nfs: true, mount_options: ["actimeo=2"]

        linux2.vm.provider :virtualbox do |virtualbox|
            virtualbox.name = "linux2 - 192.168.99.32"
        end

        linux2.vm.hostname = "linux2"
        linux2.vm.network "private_network", ip: "192.168.99.32"

        linux2.vm.provision :ansible do |ansible|
            ansible.verbose = "-vv"
            ansible.inventory_path = "provisioning/hosts.yml"
            ansible.playbook = "provisioning/site.yml"
        end
    end
end
```

**demo/provisioning/hosts.yml**

```
all:
  children:
    servers:
      hosts:
        linux1:
          ansible_host: 192.168.99.31
        linux2:
          ansible_host: 192.168.99.32
```

**demo/provisioning/site.yml**

```
---
# This playbook sets up whole stack.

- name: Apply common configuration to "server" hosts
  hosts: servers
  remote_user: root
  roles:
    - server
```

**demo/provisioning/roles/server/handlers/main.yml**

```
---

- name: Start ntp
  service:
    name: ntp
    enabled: yes
    state: started

- name: Restart ntp
  service:
    name: ntp
    enabled: yes
    state: restarted
  become: yes
```

**demo/provisioning/roles/server/tasks/main.yml**

```
---

- name: Update apt packages
  apt:
    update_cache: yes
  become: yes
  tags:
    - system

- name: Set time zone to Europe/London
  timezone:
    name: Europe/London
  become: yes
  tags:
    - system

- name: Install ntp then start
  apt:
    name: ntp
    state: present
  become: yes
  notify: Start ntp
  tags:
    - ntp

- name: Configure ntp file and restart
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  become: yes
  notify: Restart ntp
  tags:
    - ntp

- name: Install nano
  apt:
    name: nano
    state: present
  tags:
    - nano

- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  become: yes
  tags:
    - system

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes
  tags:
    - system
```

**demo/provisioning/roles/server/templates/ntp.conf.j2**
```
driftfile /var/lib/ntp/drift

# Specify UK NTP servers.
server 0.uk.pool.ntp.org
server 1.uk.pool.ntp.org
server 2.uk.pool.ntp.org
server 3.uk.pool.ntp.org

# Use Ubuntu's NTP server as a fallback.
server ntp.ubuntu.com

# Local users may obtain data from NTP servers.
restrict 127.0.0.1
restrict ::1

includefile /etc/ntp/crypto/pw

keys /etc/ntp/keys
```
##### PROVISIONING OUTPUT

[linux1](https://pastebin.com/imWseGyw) machine
[linux2](https://pastebin.com/MPaEfSQD) machine

##### EXPECTED RESULTS

**linux1**
```
ubuntu@linux1:~$ timedatectl
      Local time: Sat 2018-03-10 00:07:26 GMT
  Universal time: Sat 2018-03-10 00:07:26 UTC
        RTC time: Sat 2018-03-10 00:07:24
       Time zone: Europe/London (GMT, +0000)
 Network time on: yes
NTP synchronized: yes   # EXPECTING THIS ONE TO BE "yes" AS WELL
 RTC in local TZ: no
```

**linux2**
```
ubuntu@linux2:~$ timedatectl
      Local time: Sat 2018-03-10 00:07:41 GMT
  Universal time: Sat 2018-03-10 00:07:41 UTC
        RTC time: Sat 2018-03-10 00:07:42
       Time zone: Europe/London (GMT, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```

##### ACTUAL RESULTS

**linux1**
```
ubuntu@linux1:~$ timedatectl
      Local time: Sat 2018-03-10 00:07:26 GMT
  Universal time: Sat 2018-03-10 00:07:26 UTC
        RTC time: Sat 2018-03-10 00:07:24
       Time zone: Europe/London (GMT, +0000)
 Network time on: yes
NTP synchronized: no
 RTC in local TZ: no
```

**linux2**
```
ubuntu@linux2:~$ timedatectl
      Local time: Sat 2018-03-10 00:07:41 GMT
  Universal time: Sat 2018-03-10 00:07:41 UTC
        RTC time: Sat 2018-03-10 00:07:42
       Time zone: Europe/London (GMT, +0000)
 Network time on: yes
NTP synchronized: yes
 RTC in local TZ: no
```
