### ISSUE TITLE
ASG rolling update ignores lifecycle hooks

### ISSUE THREAD

**Issue by aarnone** [ansible/ansible#37281]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_asg

##### ANSIBLE VERSION
```
ansible 2.4.3.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When replacing instances, ASG lifecycle hooks are ignored.
The consequence is that it moves on to the next replacement before the hooks are completed.
It's more evident when the lifecycle hooks take a significant time to complete.

##### STEPS TO REPRODUCE
1. Create an ASG with a lifecycle hooks that take few minutes to complete
2. Update the launch configuration
3. Run a rolling deployment
```yaml
- name: Update launch configuration
  ec2_asg:
    name: test_asg
    launch_config_name: new_test_asg_lc
    desired_capacity: 10
    min_size: 3
    max_size: 20
    wait_for_instances: yes
    replace_all_instances: yes
    replace_batch_size: 2
```

##### EXPECTED RESULTS
There are no more than 2 instances at any time in any of these states:
- Terminating
- Terminating:Wait
- Terminating:Proceed

##### ACTUAL RESULTS
As soon as the instances are in Terminating:Wait module move on to the next batch.
More than 2 instances are in Terminating:Wait or Terminating:Proceed state.
