### ISSUE TITLE
"Unknown column 'password' in 'field list'")

### ISSUE THREAD

**Issue by MikeiLL** [ansible/ansible#37286]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`Module -> Database -> Mysql -> mysql_user.py`

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /Users/mikekilmer/Documents/Clients/Metropolitian/NYDems/nydems.org/trellis/ansible.cfg
  configured module search path = [u'/Users/mikekilmer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

```

##### CONFIGURATION

```
ANSIBLE_FORCE_COLOR(/Users/mike/rest/of/path/trellis/ansible.cfg) = True
ANSIBLE_NOCOWS(/Users/mike/rest/of/path/trellis/ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/mike/rest/of/path/trellis/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/mike/rest/of/path/trellis/ansible.cfg) = -o ForwardAg
ANSIBLE_SSH_RETRIES(/Users/mike/rest/of/path/trellis/ansible.cfg) = 1
DEFAULT_CALLBACK_PLUGIN_PATH(/Users/mike/rest/of/path/trellis/ansible.cfg) = 
DEFAULT_FILTER_PLUGIN_PATH(/Users/mike/rest/of/path/trellis/ansible.cfg) = [u
DEFAULT_FORCE_HANDLERS(/Users/mike/rest/of/path/trellis/ansible.cfg) = True
DEFAULT_HOST_LIST(/Users/mike/rest/of/path/trellis/ansible.cfg) = [u'/Users/m
DEFAULT_ROLES_PATH(/Users/mike/rest/of/path/trellis/ansible.cfg) = [u'/Users/
DEFAULT_STDOUT_CALLBACK(/Users/mike/rest/of/path/trellis/ansible.cfg) = outpu
DEFAULT_VARS_PLUGIN_PATH(/Users/mike/rest/of/path/trellis/ansible.cfg) = [u'/
DEFAULT_VAULT_PASSWORD_FILE(/Users/mike/rest/of/path/trellis/ansible.cfg) = /
(END)
```

##### OS / ENVIRONMENT

OSX 10.12.6 Sierra

##### SUMMARY
When Ansible tries to create the root user accounts, it runs the `server_version_check`, which is returning `False` even though the version of MariaDB is `10.2.13-mariadb-10.2.13+maria~xenial`.

This is the test that returns true:

`if 'mariadb' in version_str.lower():`

I don't know if most newer versions of MariaDB don't have the name MariaDB in the result of `"SELECT VERSION()"`. I'm tempted to just change the return value of this function to `True` for the time being, but fear that that might break other things down the line. I'm not a terribly adept SysAdmin.

##### STEPS TO REPRODUCE
I'm running a very simple configuration of [https://github.com/roots/trellis](https://github.com/roots/trellis) with playbooks:

```
---
- import_playbook: variable-check.yml
  vars:
    playbook: server.yml

- name: Test Connection and Determine Remote User
  hosts: web:&{{ env }}
  gather_facts: false
  roles:
    - { role: connection, tags: [connection, always] }

- name: Install prerequisites
  hosts: web:&{{ env }}
  gather_facts: false
  become: yes
  tasks:
    - name: Install Python 2.x
      raw: which python || sudo apt-get update && sudo apt-get install -qq -y python-simplejson
      register: python_check
      changed_when: not python_check.stdout | search('/usr/bin/python')

- name: WordPress Server - Install LEMP Stack with PHP 7.2 and MariaDB MySQL
  hosts: web:&{{ env }}
  become: yes
  roles:
    - { role: common, tags: [common] }
    - { role: swapfile, swapfile_size: 1GB, tags: [swapfile] }
    - { role: fail2ban, tags: [fail2ban] }
    - { role: ferm, tags: [ferm] }
    - { role: ntp, tags: [ntp] }
    - { role: users, tags: [users] }
    - { role: sshd, tags: [sshd] }
    - { role: mariadb, tags: [mariadb] }
    - { role: ssmtp, tags: [ssmtp, mail] }
    - { role: php, tags: [php] }
    - { role: memcached, tags: [memcached] }
    - { role: nginx, tags: [nginx] }
    - { role: logrotate, tags: [logrotate] }
    - { role: composer, tags: [composer] }
    - { role: wp-cli, tags: [wp-cli] }
    - { role: letsencrypt, tags: [letsencrypt], when: sites_using_letsencrypt | count }
    - { role: wordpress-setup, tags: [wordpress, wordpress-setup, letsencrypt] }
```
This the failing task being

```
  - name: Set root user password
    mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      state: present
    with_items:
      - "{{ inventory_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost
```

##### EXPECTED RESULTS
I was hoping to see GREEN instead of RED. And for the root password to be set at for four specified hosts.

##### ACTUAL RESULTS

Ansible is trying to use `password` as opposed to `authentication_string` field, which is what we need for this version of MariaDB. At least it seems that way.

```
(1054, "Unknown column 'password' in 'field list'")
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_h0S4Hn/ansible_module_mysql_user.py", line 638, in main
    changed = user_mod(cursor, user, host, host_all, password, encrypted, priv, append_privs, module)
  File "/tmp/ansible_h0S4Hn/ansible_module_mysql_user.py", line 335, in user_mod
    cursor.execute("SELECT password FROM user WHERE user = %s AND host = %s", (user, host))
  File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
OperationalError: (1054, "Unknown column 'password' in 'field list'")

failed: [ip.address.in.here] (item=localhost) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "append_privs": false, 
            "check_implicit_admin": true, 
            "config_file": "/root/.my.cnf", 
            "connect_timeout": 30, 
            "encrypted": false, 
            "host": "localhost", 
            "host_all": false, 
            "login_host": "localhost", 
            "login_password": null, 
            "login_port": 3306, 
            "login_unix_socket": null, 
            "login_user": null, 
            "name": "root", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "priv": null, 
            "sql_log_bin": true, 
            "ssl_ca": null, 
            "ssl_cert": null, 
            "ssl_key": null, 
            "state": "present", 
            "update_password": "always", 
            "user": "root"
        }
    }, 
    "item": "localhost"
}
```
Thanks for this wonderful tool, by the way. You rock.
