### ISSUE TITLE
Firewalld: ipset support/integration

### ISSUE THREAD

**Issue by rwaweber** [ansible/ansible#37319]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

firewalld
##### ANSIBLE VERSION

```
ansible 2.4.3.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Not sure if it's been discussed before, but I feel like having [ipset](http://www.firewalld.org/documentation/man-pages/firewalld.ipset.html) support in the firewalld module would be pretty cool. I know that for *my* use-case it would definitely reduce my need to use firewalld with a `with_items` clause.

Unfortunately, I haven't spent much time looking at the structure of the firewalld module to be able to gauge the amount of work necessary to get it implemented. Just an idea at this point.

##### STEPS TO REPRODUCE

Definitely open to change the idea of how this would look, more or less just a first pass at thinking about it:

```yaml
- firewalld:
    service: https
    permanent: true
    state: enabled
    ipset:
      - 192.168.0.1
      - 192.168.0.13
      - 192.168.0.18
      - 192.168.0.20
```

Though since you can create named ipsets, maybe it would make more sense to have a separate ansible module to create and manage ipsets, then maybe we could add support to this module to interface with those created ipsets? That could look like this:

```yaml
- firewalld_ipset:
    name: nameserver_clients
    description: an ipset of my name servers
    sources:
      - 192.168.0.1
      - 192.168.0.13
      - 192.168.0.18
      - 192.168.0.20

- firewalld:
    service: dns
    permanent: true
    state: enabled
    ipset: nameserver_clients
```

Just some thoughts to kick around, very open to changing or adapting them. Also happy to draft a PR for it
