### ISSUE TITLE
No RabbitMQ Dynamic Shovel Module exists

### ISSUE THREAD

**Issue by washingtoneg** [ansible/ansible#37315]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
`rabbitmq_dynamic_shovel`

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/elenawashington/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = ./bin/ansible
  python version = 2.7.14 (default, Jan  6 2018, 12:15:00) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Given that a **`rabbitmq_dynamic_shovel` module exists** and its implementation uses Rabbitmq's default connection options and a [sane set of shovel defaults](https://www.rabbitmq.com/shovel-dynamic.html)... 

If you have a RabbitMQ server running locally with the `rabbitmq-management` and `rabbitmq_shovel_management` plugins enabled, the following playbook, role, and `ansible-playbook` command will create dynamic shovel on the RabbitMQ server:

```yaml
# playbooks/rabbitmq-shovel.yml

- hosts: localhost
  name: RabbitMQ Shovel Playbook
  gather_facts: false

  roles:
    - roles/create-rabbitmq-dynamic-shovel
```

```yaml
# playbooks/roles/create-rabbitmq-dynamic-shovel/tasks/main.yml

  - name: set up shovel
    rabbitmq_dynamic_shovel:
      name: my-shovel
      source: my-queue
      source_uri: 'amqp://'
      source_type: queue
      destination: my-exchange
      destination_uri: 'amqp://'
      destination_type: exchange
```

```
$ ansible-playbook playbooks/create-rabbitmq-dynamic-shovel.yml
```

##### EXPECTED RESULTS
```
$ ansible-playbook playbooks/create-rabbitmq-dynamic-shovel.yml -vvv
...
TASK [roles/rabbitmq-test : set up shovel] ********************************************************************************************
task path: /private/tmp/ansible/playbooks/roles/rabbitmq-test/tasks/main.yml:9
Using module file /private/tmp/ansible/library/rabbitmq_dynamic_shovel.py
...
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "ack_mode": "on_confirm",
            "add_forward_headers": false,
            "delete_after": "never",
            "destination": "my-exchange",
            "destination_type": "exchange",
            "destination_uri": [
                "amqp://"
            ],
            "login_host": "localhost",
            "login_password": "guest",
            "login_port": "15672",
            "login_user": "guest",
            "name": "my-shovel",
            "prefetch_count": 1000,
            "reconnect_delay": 1,
            "source": "my-queue",
            "source_type": "queue",
            "source_uri": "amqp://",
            "state": "present",
            "vhost": "/"
        }
    },
    "name": "my-shovel",
    "shovel": {
        "ack-mode": "on-confirm",
        "add-forward-headers": false,
        "delete-after": "never",
        "dest-exchange": "my-exchange",
        "dest-uri": [
            "amqp://"
        ],
        "prefetch-count": 1000,
        "reconnect-delay": 1,
        "src-queue": "my-queue",
        "src-uri": "amqp://"
    }
}

```

##### ACTUAL RESULTS

```
$ ansible-playbook playbooks/create-rabbitmq-dynamic-shovel.yml
...

ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
```
