### ISSUE TITLE
Error while loading YAML on $schema

### ISSUE THREAD

**Issue by dealkk** [ansible/ansible#37321]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
"azure_rm_deployment"

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/home/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /opt/ansible/bin/ansible
  python version = 2.7.12 
```

##### SUMMARY
Keep getting syntax error here trying to use inline template 
$schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"

i

##### STEPS TO REPRODUCE

```yaml

- name: Enable winRM
    azure_rm_deployment:
      state: present
      resource_group_name: MyAzureRS
      
      variables: 
        location: "South Central US"
      template:
        $schema: "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#"
        contentVersion: "1.0.0.0"
        parameters:
          mymachine: 
            type: "string"
            metadata: "window param"      

      resources: 
        - type: "Microsoft.Compute/virtualMachines/extensions"
          name: "[concat(parameters('mymachine'),'/ConfigureRemotingForAnsible')]"
          apiVersion: "2015-06-15"
          location: "[resourceGroup().location]"
          properties:
            publisher: "Microsoft.Compute"
            type: "CustomScriptExtension"
            typeHandlerVersion: "1.8"
            autoUpgradeMinorVersion: true
            settings: 
              fileUris: "https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"
              commandToExecute: "powershell.exe -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"


```

##### EXPECTED RESULTS
success run

##### ACTUAL RESULTS

syntax error

```

```
