### ISSUE TITLE
Issue with module var overwriting var in file

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#37322]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ec2_elb

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION

ANSIBLE_PIPELINING=True

##### OS / ENVIRONMENT

N/A

##### SUMMARY

I have a var in a var file called ec2_elbs
in the module ec2_elb you define a var for it ec2_elbs
When the var for the module is defined it overwrites the var from the var file

##### STEPS TO REPRODUCE

Create var called ec2_elbs
Output var ec2_elbs
Run ec2_elb module and define ec2_elbs for the module
Output var ec2_elbs

```yaml
testing.yml
---
ec2_elbs:
  generalapi_elb:
    elb_name: generalapi-int-dev
    elb_type: classic_elb

playbook-test.yml
---
- hosts: tag_testing_test
   user: ec2-user
   become: yes
   vars_files:
     - testing.yml

   tasks:
     - name: Set fact for the load balancer to be used
       set_fact:
         elb_name: "{{ ec2_elbs['genericapi_elb']['elb_name'] }}"
     - debug: var=ec2_elbs
     - name: Add ec2 instance to classic load balancer
       become: no
       local_action:
         module: ec2_elb
         instance_id: "{{ ec2_id }}"
         state: "present"
         ec2_elbs: "{{ elb_name }}"
         region: "{{ region }}"
     - debug: var=ec2_elbs
```

##### EXPECTED RESULTS

I expect the first debug to match the 2nd debug

##### ACTUAL RESULTS

The first debug outputs the var
ec2_elbs:
  generalapi_elb:
    elb_name: generalapi-int-dev
    elb_type: classic_elb

The second debug just outputs elb_name
ec2_elbs: "generalapi-int-dev"

```

```
