### ISSUE TITLE
Cannot assign NSG from other resource group when creating subnet

### ISSUE THREAD

**Issue by alexpilon666** [ansible/ansible#37330]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_subnet

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/admindig/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /etc/ansible/fact_caching
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 86400
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory.yaml']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/username/.ssh/id_rsa
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/.vault_pass

##### OS / ENVIRONMENT
N/A

##### SUMMARY
There is currently no way, when using azure_rm_subnet, to assign a network security group (NSG) that isn't in the same resource group as the subnet, though this is possible through the Azure GUI.

##### STEPS TO REPRODUCE
This below is my yaml currently being using to create a subnet.
The `resource_group` argument is valid for the subnet, the vnet and the NSG (network security group).
What I would like to see implemented would be a separate argument _a la_ `security_resource_group` or `nsg_resource_group`, that would be used to specify the NSG's resource group, while not impacting where the vnet is gathered from, and where the subnet is created/gathered.

```yaml
- name: Create new subnet if not existent
  azure_rm_subnet:
    address_prefix_cidr: "{{ vnet_cidr_prefix }}"
    name: "{{ subnet_name }}"
    profile: "{{ azure_profile }}"
    resource_group: "{{ resource_group }}"
    state: present
    virtual_network_name: "{{ vnet_name }}"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_subnet.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_subnet.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
@alexpilon666 I think this should be a feature request for NSG module rather than subnet module. My proposal is add a `subnets` parameter filed in the NSG module to specify the Virtual Network name and subnet name. Like this:
```
azure_rm_securitygroup:
  name: test01
  resource_group: test01
  subnets:
  - resource_group: test02  # None means the same as security group
    virtual_network: test02
    subnet: test02
  - virtual_network test01
    subnet: test01
```

How do you think about it?
