### ISSUE TITLE
Cron module is not idempotent until name option is set

### ISSUE THREAD

**Issue by zbikmarc** [ansible/ansible#37355]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
cron_module

##### ANSIBLE VERSION
```
ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### CONFIGURATION
Everything standard

##### OS / ENVIRONMENT
RedHat Enterprise Linux 7

##### SUMMARY
I am expecting every playbook to be idempotent, however cron module will just add new entry to crontab each time Ansible playbook was executed.  It can be idempotent only when `name` option is set. In my opinion, `name` option should be required or at least there should be warning informing about such, not obvious, behavior. 

##### STEPS TO REPRODUCE
1. Create playbook with content pasted below
1. Run playbook on server
1. Check `crontab -l`
1. Run playbook again
1. Check `crontab -l` again

```yaml
- name: "Testing cron module idempotency"
  cron:
    state: present
    minute: 0
    job: "/bin/bash echo test >> /tmp/test.txt"
```

##### EXPECTED RESULTS
Job entry should not be duplicated.

##### ACTUAL RESULTS
Job entry is duplicated.

**Comment by giovannisciortino** [comment]
Probably this is a feature request and not a bug. This behaviour is described in the documentation of the module[1]:

> name: Description of a crontab entry or, if env is set, the name of environment variable. Required if state=absent. Note that if name is not set and state=present, then a new crontab entry will always be created, regardless of existing ones.

[1] http://docs.ansible.com/ansible/latest/cron_module.html

**Comment by zbikmarc** [comment]
Changed type to `Feature Idea`. To me this is still a bug, even though it’s documented.

**Comment by ansibot** [comment]
cc @EvanK @dsummersl @lberruti
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jpmens** [comment]
IMNSHO this is not a feature request but a bug. The `name` attribute ought to be mandatory in order to default to idempotency. What we should do is to deprecate the non-mandatory `name` in a future version and then make `name` mandatory.

**Comment by bcoca** [comment]
idempotence is not a requirement .. otherwise shell/raw would not exist. 
The user should have the option to do this in any manner they wish. 

That said, the documentation should be very clear on the expectations when 'name' is not included.

**Comment by jpmens** [comment]
I find it doubtful that making `name` mandatory will hurt anybody, and it'll prevent people from mistakenly shooting themselves in the foot in future. I see no harm in preventing that.

**Comment by funkyfuture** [comment]
i'm experiencing that Ansible 2.6 is adding redundant entries to the crontab even when a `name` is provided.

```yaml
- set_fact:
    daily_reboot_hour: "{{ daily_reboot_time.split(':')[0] }}"
    daily_reboot_minute: "{{ daily_reboot_time.split(':')[1] }}"
- name: set daily reboot time
  cron:
    hour: "{{ daily_reboot_hour }}"
    minute: "{{ daily_reboot_minute }}"
    job: reboot
  when: daily_reboot_time != ''
```

repeated executions result in:

```
#Ansible: None
04 04 * * * reboot
#Ansible: None
04 04 * * * reboot
#Ansible: None
04 04 * * * reboot
```

**Comment by zbikmarc** [comment]
@funkyfuture 
IIRC It is different name.
You provided task name, not crontab entry name. So in your case it would be rather:

```yaml
- set_fact:
    daily_reboot_hour: "{{ daily_reboot_time.split(':')[0] }}"
    daily_reboot_minute: "{{ daily_reboot_time.split(':')[1] }}"
- name: set daily reboot time
  cron:
    name: entry name
    hour: "{{ daily_reboot_hour }}"
    minute: "{{ daily_reboot_minute }}"
    job: reboot
  when: daily_reboot_time != ''
```
