### ISSUE TITLE
Unsupported parameters for (os_subnets_facts) module: subnet

### ISSUE THREAD

**Issue by dyasny** [ansible/ansible#37352]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
os_subnets_facts

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dyasny/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Feb 27 2018, 20:43:24) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]

```

##### CONFIGURATION
No changes from defaults

##### OS / ENVIRONMENT
Fedora 27

##### SUMMARY
Documentation at http://docs.ansible.com/ansible/latest/os_subnets_facts_module.html says to specify "subnet" as name or ID for the sought subnet, actually, when I do that I get 

```
TASK [ Gather facts about previously created subnet] ****************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (os_subnets_facts) module: subnet Supported parameters include: api_timeout,auth,auth_type,availability_zone,cacert,cert,cloud,endpoint_type,filters,key,name,region_name,timeout,verify,wait"}
```
Changing "subnet" to "name" works as expected

##### STEPS TO REPRODUCE
```yaml
- name: Gather facts about previously created subnet
  os_subnets_facts:
    cloud: "{{ cloud_name }}"
    subnet: "{{ subnet }}"

```
this fails

```yaml
- name: Gather facts about previously created subnet
  os_subnets_facts:
    cloud: "{{ cloud_name }}"
    name: "{{ subnet }}"
```

this works

##### EXPECTED RESULTS

openstack_subnets should be registered with the data on my subnet

##### ACTUAL RESULTS

```
TASK [ Gather facts about previously created subnet] ****************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (os_subnets_facts) module: subnet Supported parameters include: api_timeout,auth,auth_type,availability_zone,cacert,cert,cloud,endpoint_type,filters,key,name,region_name,timeout,verify,wait"}

```

Either the module or documentation needs to be fixed
