### ISSUE TITLE
ansible-playbook --list-tasks and include_role don't work together

### ISSUE THREAD

**Issue by tchia04** [ansible/ansible#37364]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

include_role 
ansible-playbook cli --list-tasks

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/XXXXX/YYYY/Ansible/playbooks/BOS/ansible.cfg
  configured module search path = [u'/home/XXXXX/YYYY/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### OS / ENVIRONMENT

Rehat7
##### SUMMARY

When using role in a playbook in the old fashion way. ansible-playbook --list-tasks is able to display the tasks. However using the include_role in a task will break the --list-tasks command and shows nothing. 

##### STEPS TO REPRODUCE

```yaml
working example
=================
playbook:
  roles:
    - role: rabbitmq


Output from ansible-playbook --list-tasks
playbook: RabbitMQ_playbook.yml

  play #1 (rabbitmq): RabbitMQ Servers     TAGS: []
    tasks:
      rabbitmq : Include some common Linux packages     TAGS: []
      rabbitmq : install the rabbitmq binary    TAGS: [install]
      rabbitmq : configure rabbitmq     TAGS: [basic_configure]
      rabbitmq : add rabbitmq cluster hosts     TAGS: [add_cluster_hosts]
      rabbitmq : set erlang cookie      TAGS: [add_cluster_hosts]
      rabbitmq : start rabbitmq server  TAGS: []



non-working example
===================
playbook:
  tasks:
  - name: Install and Configure RabbitMQ
    include_role:
      name: rabbitmq



Output from ansible-playbook --list-tasks
playbook: RabbitMQ_playbook.yml.org

  play #1 (rabbitmq): RabbitMQ Servers     TAGS: []
    tasks:
      Install and Configure RabbitMQ    TAGS: []

```

##### EXPECTED RESULTS

The details of the included role should be displayed when using --list-tasks

##### ACTUAL RESULTS

The details of the included role is not displayed when using --list-tasks

```
playbook:
  tasks:
  - name: Install and Configure RabbitMQ
    include_role:
      name: rabbitmq



Output from ansible-playbook --list-tasks
playbook: RabbitMQ_playbook.yml.org

  play #1 (rabbitmq): RabbitMQ Servers     TAGS: []
    tasks:
      Install and Configure RabbitMQ    TAGS: []

```
