### ISSUE TITLE
import_role / include_role fail with "<role> was not found" with when: false

### ISSUE THREAD

**Issue by drzraf** [ansible/ansible#37365]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
import_role
include_role

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = ~/.ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### SUMMARY
I'm writing a container-enabled role.
It imports another (custom) role only on "bare-metal" deployment (if `baremetal: True`).
It must ignore this role if called with `baremetal: False` (eg: from `container.yml`)
If initially found that `meta/main.yml` was considered independently of the `vars` passed to the role; but then also found that even `(import/include)_role` would be somewhat `treated` without regard for `when:`

##### STEPS TO REPRODUCE
$ `rm -rf roles/ae.lamp`
```yaml roles/ae.container-enabled-role/tasks/main.yml
- include_role:
    name: ae.lamp
  when: baremetal
```
```yaml container.yml
services:
  wordpress:
    from: alpine:latest
    roles:
      - { role: ae.container-enabled-role, baremetal: True }
```

##### EXPECTED RESULTS
`ae.lamp` role is ignored (even if absent).
playbook run / container build

##### ACTUAL RESULTS
```
ERROR! the role 'ae.lamp' was not found in /tmp/tmpteki23/roles:/src/roles:/etc/ansible/roles:/tmp/tmpteki23

The error appears to have been in '/src/ae.container-enabled-role/tasks/main.yml': line 8, column 11, but may be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- include_role:
    name: ae.lamp
          ^ here
```
