### ISSUE TITLE
elb_target_group, if the TG does not already exists, does not hand off target port correctly 

### ISSUE THREAD

**Issue by maxgio92** [ansible/ansible#37368]
##### ISSUE TYPE
- Bug report

##### COMPONENT NAME
elb_target_group

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'***/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = ***/venv/lib/python2.7/site-packages/ansible
  executable location = ***/venv/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]

```

##### CONFIGURATION
No output from ansible-config dump --only-changed

##### OS / ENVIRONMENT
Mac OS 10.13.3
AWS Application type ELB 

##### SUMMARY
Attempting to create an ELB Target Group from scratch and passing parameters from variables results in a module failure. The cause is that the Port of the targets variable is expected to be int.

##### STEPS TO REPRODUCE
Executing this task as below I'm trying to create and config a new target group:
```yaml
--------------
vars/main.yml
--------------
target_group_name: my-elb-tg
target_group_protocol: HTTP
target_group_port: 8000

---------------
tasks/main.yml
---------------
- name: Setup ELB Target group
  elb_target_group:
    name: "{{ target_group_name }}"
    protocol: "{{ target_group_protocol }}"
    port: "{{ target_group_port }}"
    vpc_id: "{{ vpc.id }}"
    targets:
      - Id: "{{ target_instance_id }}"
        Port: "{{ target_group_port }}"
    state: present
```

##### EXPECTED RESULTS
That the module casts the parameters to expected types, in this case str to int.

##### ACTUAL RESULTS
Module failure:
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter Targets[0].Port, value: 8000 | int , type: <type 'str'>, valid types: <type 'int'>, <type 'long'>
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/r4/6j10517j6x386p09ppsytz180000gn/T/ansible_YZBI78/ansible_module_elb_target_group.py\", line 672, in <module>\n    main()\n  File \"/var/folders/r4/6j10517j6x386p09ppsytz180000gn/T/ansible_YZBI78/ansible_module_elb_target_group.py\", line 667, in main\n    create_or_update_target_group(connection, module)\n  File \"/var/folders/r4/6j10517j6x386p09ppsytz180000gn/T/ansible_YZBI78/ansible_module_elb_target_group.py\", line 528, in create_or_update_target_group\n    connection.register_targets(TargetGroupArn=tg['TargetGroupArn'], Targets=params['Targets'])\n  File \"***/venv/lib/python2.7/site-packages/botocore/client.py\", line 314, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n  File \"***/venv/lib/python2.7/site-packages/botocore/client.py\", line 586, in _make_api_call\n    api_params, operation_model, context=request_context)\n  File \"***/venv/lib/python2.7/site-packages/botocore/client.py\", line 621, in _convert_to_request_dict\n    api_params, operation_model)\n  File \"***/venv/lib/python2.7/site-packages/botocore/validate.py\", line 291, in serialize_to_request\n    raise ParamValidationError(report=report.generate_report())\nbotocore.exceptions.ParamValidationError: Parameter validation failed:\nInvalid type for parameter Targets[0].Port, value: 8000 | int , type: <type 'str'>, valid types: <type 'int'>, <type 'long'>\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 0}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/elb_target_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/elb_target_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @willthames @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by maxgio92** [comment]
It seems that entering in the else from line 515 (when attempting to create new target group from scratch) of the module, the Targets list does not contain casted-to-int Port field, because are directly taken from module params.

**Comment by julienvey** [comment]
This should be fixed in the future 2.5 release by #32202 (original issue #32098)

Can you try with the latest rc `2.5.0rc2` ?

**Comment by maxgio92** [comment]
Hi @julienvey , ok, I'm going to try it as soon as possible.
Thank you

Actually, as a workaround, I'm obtaining the desired with two tasks: creating from scratch the Target Group without Targets and later updating it with the Targets.

**Comment by willthames** [comment]
2.5 is now released with the fix for this issue.

**Comment by AngryLuke** [comment]
Hi all, I have the same error on Ansible 2.6.2

##### ANSIBLE VERSION

```
ansible 2.6.2
  config file = /home/ubuntu/ansible-deploy/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
##### CONFIGURATION

DEFAULT_ROLES_PATH(/home/ubuntu/ansible-deploy/ansible.cfg) = [u'/home/ubuntu/ansible-deploy/roles/common', u'/home/ubuntu/ansible-deploy/roles/docker', u'/home/ubuntu/ansible-deploy/roles/infrastructure', u'/home/ubuntu/ansible-deploy/ro
HOST_KEY_CHECKING(/home/ubuntu/ansible-deploy/ansible.cfg) = False

##### OS / ENVIRONMENT

Description:	Ubuntu 16.04.5 LTS
Codename:	xenial
AWS Application type ELB


##### STEPS TO REPRODUCE



```yaml
----- vars -----
target_group_name: "01035310414-staging"
available_http_port: 10095

----- tasks -----
- name: set http_port for create_target_group
  set_fact:
    http_port: "{{ available_http_port }}"
  delegate_to: localhost

- name: create target group
  elb_target_group:
    name: "{{ target_group_name }}"
    region: "{{ aws_region }}"
    vpc_id: "{{ vpc_id }}"
    port: "{{ http_port | int }}"
    health_check_path: /
    successful_response_codes: "200"
    stickiness_enabled: yes
    state: present
    protocol: http
    targets: 
      - Id: "{{ ec2_resource_id }}"
        Port: "{{ http_port }}"
  register: target_group
  delegate_to: localhost
```
##### EXPECTED RESULTS

Expected task create target group without error, and the module cast variable http_port from str to int.

##### ACTUAL RESULTS



```
TASK [create_target_group : create target group] *********************************************************************************************************************************************************************************************
task path: /home/ubuntu/ansible-deploy/roles/common/create_target_group/tasks/main.yml:7
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ubuntu
<localhost> EXEC /bin/sh -c 'echo ~ubuntu && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1534773004.06-174948973669312 `" && echo ansible-tmp-1534773004.06-174948973669312="` echo /home/ubuntu/.ansible/tmp/ansible-tmp-1534773004.06-174948973669312 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/amazon/elb_target_group.py
<localhost> PUT /home/ubuntu/.ansible/tmp/ansible-local-12225Ovbqqh/tmpsQwKyx TO /home/ubuntu/.ansible/tmp/ansible-tmp-1534773004.06-174948973669312/elb_target_group.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ubuntu/.ansible/tmp/ansible-tmp-1534773004.06-174948973669312/ /home/ubuntu/.ansible/tmp/ansible-tmp-1534773004.06-174948973669312/elb_target_group.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/ubuntu/.ansible/tmp/ansible-tmp-1534773004.06-174948973669312/elb_target_group.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ubuntu/.ansible/tmp/ansible-tmp-1534773004.06-174948973669312/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_5bX2yS/ansible_module_elb_target_group.py", line 574, in create_or_update_target_group
    connection.register_targets(TargetGroupArn=tg['TargetGroupArn'], Targets=params['Targets'])
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 586, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/client.py", line 621, in _convert_to_request_dict
    api_params, operation_model)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Invalid type for parameter Targets[0].Port, value: 10095, type: <type 'str'>, valid types: <type 'int'>, <type 'long'>

fatal: [172.10.31.237 -> localhost]: FAILED! => {
    "boto3_version": "1.7.62", 
    "botocore_version": "1.10.70", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "deregistration_delay_timeout": null, 
            "ec2_url": null, 
            "health_check_interval": null, 
            "health_check_path": "/", 
            "health_check_port": null, 
            "health_check_protocol": null, 
            "health_check_timeout": null, 
            "healthy_threshold_count": null, 
            "modify_targets": true, 
            "name": "01035310414-staging", 
            "port": 10095, 
            "profile": null, 
            "protocol": "http", 
            "purge_tags": true, 
            "region": "eu-west-1", 
            "security_token": null, 
            "state": "present", 
            "stickiness_enabled": true, 
            "stickiness_lb_cookie_duration": null, 
            "stickiness_type": "lb_cookie", 
            "successful_response_codes": "200", 
            "tags": {}, 
            "target_type": "instance", 
            "targets": [
                {
                    "Id": "i-0c1c80fee9a5287e4", 
                    "Port": "10095"
                }
            ], 
            "unhealthy_threshold_count": null, 
            "validate_certs": true, 
            "vpc_id": "vpc-8c0671eb", 
            "wait": null, 
            "wait_timeout": null
        }
    }, 
    "msg": "Couldn't register targets: Parameter validation failed:\nInvalid type for parameter Targets[0].Port, value: 10095, type: <type 'str'>, valid types: <type 'int'>, <type 'long'>"
}

```
