### ISSUE TITLE
ios_l2_interface doesn't remove trunk vlans

### ISSUE THREAD

**Issue by trishnaguha** [ansible/ansible#37388]
- Removing trunk_vlan range doesn't work on ios_l2_interface module.
- Also When removing vlan's from allowed vlan list of a trunk interface with `loop`, it will not remove the vlan if it is the last remaining vlan on the interface trunk.
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

modules/network/ios/ios_l2_interface.py
##### ANSIBLE VERSION

```
devel, 2.5
```

##### STEPS TO REPRODUCE

```yaml

an-iosl2-01#show run | section interface.GigabitEthernet0/2
interface GigabitEthernet0/2
 description to ios01
 switchport trunk allowed vlan 998-1002,2000

    ios_l2_interface:
      name: GigabitEthernet0/2
      mode: trunk
      trunk_vlans: "998-1002,2000"
      state: absent
This doesn't do anything.


    ios_l2_interface:
      name: GigabitEthernet0/2
      mode: trunk
      trunk_vlans: "{{ item.vlan_id }}"
      state: absent
      with_items:
         - "{{ L2_VLAN_ID }}"
This deletes all the vlans, but doesn't delete the last remaining one.

L2_VLAN_ID:
  - { vlan_id: 998 }
  - { vlan_id: 999 }
  - { vlan_id: 1000 }
  - { vlan_id: 1001 }
  - { vlan_id: 1002 }
  - { vlan_id: 2000 }
```

`show int GigabitEthernet0/2 switchport` should return `Trunking VLANs Enabled: NONE`
