### ISSUE TITLE
a10_service_group, if 'enabled' is specified for 'servers.status', the value of "priority" is reset.

### ISSUE THREAD

**Issue by ShimpeiIto** [ansible/ansible#37380]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
a10_service_group

##### ANSIBLE VERSION

```
ansible 2.4.1.0
  config file = None
  configured module search path = [u'/export/home/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/auto_release/lib/python2.7/site-packages/ansible
  executable location = /opt/auto_release/bin/ansible
  python version = 2.7.14 (default, Jan 24 2018, 11:37:21) [GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
```

##### CONFIGURATION
No output from ansible-config dump --only-changed

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 6.4 (Santiago)

##### SUMMARY
method : a10_service_group has set "priority" to 1 (defalut value).
If 'enabled' is specified for 'servers.status', the value of "priority" is reset.

##### STEPS TO REPRODUCE
step1:
Executing this task as below I'm trying to change the status of server"XXX.XX.XXX.10" to "disable".

```yaml
  a10_service_group:
    host: "{{ lb_act_ip }}"
    username: "{{ lb_username }}"
    password: "{{ lb_password }}"
    service_group: "{{ lb.info.service_groups_name }}"
    service_group_method: "{{ lb.info.service_group_method | d('roundrobin')}}"
    validate_certs: no
    write_config: no
    servers:
     - { server: "XXX.XX.XXX.10",  port: "80",  status: "disable" }
     - { server: "XXX.XX.XXX.11",  port: "80",  status: "enabled" }
```

As shown in the following ansible.log,
The value of "status" is 0(disable), and the value of "priority" is 16.(keep as is)
```
"member_list": [
{"port": 80, "priority": 16, "server": "XXX.XX.XXX.10", "stats_data": 1, "status": 0, "template": "default"},
{"port": 80, "priority": 1,  "server": "XXX.XX.XXX.11", "stats_data": 1, "status": 1, "template": "default"}], 
```

step2:
Executing this task as below I'm trying to change the status of server"XXX.XX.XXX.10" to "enabled".

```yaml
  a10_service_group:
    host: "{{ lb_act_ip }}"
    username: "{{ lb_username }}"
    password: "{{ lb_password }}"
    service_group: "{{ lb.info.service_groups_name }}"
    service_group_method: "{{ lb.info.service_group_method | d('roundrobin')}}"
    validate_certs: no
    write_config: no
    servers:
     - { server: "XXX.XX.XXX.10",  port: "80",  status: "enabled" }
     - { server: "XXX.XX.XXX.11",  port: "80",  status: "enabled" }
```

As shown in the following ansible.log,
The value of "status" has been changed to 1(enabled), but the value of "priority" is 1.
```
"member_list": [
{"port": 80, "priority": 1, "server": "XXX.XX.XXX.10", "stats_data": 1, "status": 1, "template": "default"}, 
{"port": 80, "priority": 1, "server": "XXX.XX.XXX.11", "stats_data": 1, "status": 1, "template": "default"}], 
```

##### EXPECTED RESULTS
When 'enabled' is specified for 'servers.status',
the value of "priority" is not reset and is kept as it is.

##### ACTUAL RESULTS
The value of "priority" has been changed.
