### ISSUE TITLE
Command line flags don't override playbook values.

### ISSUE THREAD

**Issue by xamox** [ansible/ansible#3738]
If I do something like:

```
ansible-playbook install-software.yml -i "your.host.name," --user=ubuntu --extra-vars=user=ubuntu
```

For this playbook:

```
- hosts: all
  connection: ssh
  user: sm
  sudo: yes
  sudo_user: root
  gather_facts: true
  vars:
    - user: sm
    - code_directory: Code

  tasks:
  - name: update package list
    action: apt update_cache=yes
```

It still tries to use the user 'sm' instead of overriding with 'ubuntu'.
