### ISSUE TITLE
apache2_module fails to activate ssl module on ubuntu xenial64

### ISSUE THREAD

**Issue by olivier-bezet** [ansible/ansible#37399]
ISSUE TYPE
Bug Report

COMPONENT NAME

apache2_module

ANSIBLE VERSION
ansible 2.4.2.0
  config file = /Users/.../Documents/git/devops/dev_ob/ansible.cfg
  configured module search path = [u'/Users/.../.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/.../.pyenv/versions/2.7.10/envs/ansible2.7.10/lib/python2.7/site-packages/ansible
  executable location = /Users/olivier/.pyenv/versions/ansible2.7.10/bin/ansible
  python version = 2.7.10 (default, Jan 31 2018, 16:46:03) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]

CONFIGURATION
Not modified

OS / ENVIRONMENT
Master: MAC OS X Yosemit
Slave1: UBUNTU 16.04 xenial64

SUMMARY
I am using ansible on mac to provision ubuntu 16.04 xenial64 with vagrant.

When I connect to the target, "a2enmod ssl" enables ssl, "a2dismod ssl" removes ssl.
When enabled and restarting apache2, https connection works well.

However, with ssl previously disabled, when I activate ssl via apache2_module, nothing happens: the verbose mode says that ssl module is already enabled and https does not work. Even when forcing apache2 to restart, https does not work.

Ansible task extract:

```
- name: enable apache2 ssl
  apache2_module:
    name: ssl
    state: present
  notify:
    - restart apache2
```

Result:

ok: [10.0.0.100] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "force": false, 
            "ignore_configcheck": false, 
            "name": "ssl", 
            "state": "present"
        }
    }, 
    "result": "Module ssl enabled"
}

Then, when I test with "state: absent", it fails: "msg": "Failed to set module ssl to disabled: Module ssl already disabled\n"

Ansible task extract:

```
- name: enable apache2 ssl
  apache2_module:
    name: ssl
    state: absent
  notify:
    - restart apache2
```

Has anyone the same bug ?
Thanks
