### ISSUE TITLE
`user` module with `local: true` fail to change group for existing user

### ISSUE THREAD

**Issue by Arano-kai** [ansible/ansible#37396]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`user` module

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

Not modified
##### OS / ENVIRONMENT

Master: Debian GNU/Linux 9.3 (stretch)
Slave1: CentOS Linux release 7.4.1708 (Core)
Slave2: Debian GNU/Linux 9.3 (stretch)
##### SUMMARY

When change group of existing user, `user` module with `local: true` use group name, and `lusermod` supports only group id.
When define group for nonexistent user, group id is used.
##### STEPS TO REPRODUCE

Install `libuser`.

```yaml
---
- hosts: all
  vars:
    username: 'testuser'
  become: true
  tasks:
    - name: 'create some user'
      user:
        name: '{{ username }}'
        createhome: false
        local: true

    - block:
        - name: 'try to set goup'
          user:
            name: '{{ username }}'
            group: '{%- if ansible_os_family == "Debian" -%}sudo{%- else -%}wheel{%- endif -%}'
            local: true

      always:
        - name: 'remove user'
          user:
            name: '{{ username }}'
            state: 'absent'
            local: true
```

##### EXPECTED RESULTS
Group changed

##### ACTUAL RESULTS

```
ansible-playbook 2.4.3.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
No config file found; using defaults

PLAYBOOK: local_user_fails_on_group_set.yml **************************************************************************************************
1 plays in local_user_fails_on_group_set.yml

PLAY [all] ***********************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [Slave1]
ok: [Slave2]
META: ran handlers

TASK [create some user] **********************************************************************************************************************
task path: /home/user/ansible/ansible_bugs/local_user_fails_on_group_set/local_user_fails_on_group_set.yml:7
changed: [Slave2] => {"changed": true, "comment": "testuser", "createhome": false, "failed": false, "group": 1001, "home": "/home/testuser", "name": "testuser", "shell": "/bin/sh", "state": "present", "system": false, "uid": 1001}
changed: [Slave1] => {"changed": true, "comment": "testuser", "createhome": false, "failed": false, "group": 1001, "home": "/home/testuser", "name": "testuser", "shell": "/bin/bash", "state": "present", "system": false, "uid": 1001}

TASK [try to set goup] ***********************************************************************************************************************
task path: /home/user/ansible/ansible_bugs/local_user_fails_on_group_set/local_user_fails_on_group_set.yml:14
fatal: [Slave2]: FAILED! => {"changed": false, "failed": true, "msg": "Invalid group ID sudo\nUsage: lusermod [-imLU?] [-i|--interactive] [-c|--gecos STRING]\n        [-d|--directory STRING] [-m|--movedirectory] [-s|--shell STRING]\n        [-u|--uid NUM] [-g|--gid NUM] [-l|--login STRING]\n        [-P|--plainpassword STRING] [-p|--password STRING] [-L|--lock]\n        [-U|--unlock] [--commonname=STRING] [--givenname=STRING]\n        [--surname=STRING] [--roomnumber=STRING] [--telephonenumber=STRING]\n        [--homephone=STRING] [-?|--help] [--usage] [OPTION...] user\n", "name": "testuser", "rc": 1}
fatal: [Slave1]: FAILED! => {"changed": false, "failed": true, "msg": "Invalid group ID wheel\nUsage: lusermod [-imLU?] [-i|--interactive] [-c|--gecos STRING]\n        [-d|--directory STRING] [-m|--movedirectory] [-s|--shell STRING]\n        [-u|--uid NUM] [-g|--gid NUM] [-l|--login STRING]\n        [-P|--plainpassword STRING] [-p|--password STRING] [-L|--lock]\n        [-U|--unlock] [--commonname=STRING] [--givenname=STRING]\n        [--surname=STRING] [--roomnumber=STRING] [--telephonenumber=STRING]\n        [--homephone=STRING] [-?|--help] [--usage] [OPTION...] user\n", "name": "testuser", "rc": 1}

TASK [remove user] ***************************************************************************************************************************
task path: /home/user/ansible/ansible_bugs/local_user_fails_on_group_set/local_user_fails_on_group_set.yml:21
changed: [Slave2] => {"changed": true, "failed": false, "force": false, "name": "testuser", "remove": false, "state": "absent"}
changed: [Slave1] => {"changed": true, "failed": false, "force": false, "name": "testuser", "remove": false, "state": "absent"}
        to retry, use: --limit @/home/user/ansible/ansible_bugs/local_user_fails_on_group_set/local_user_fails_on_group_set.retry

PLAY RECAP ***********************************************************************************************************************************
Slave1              : ok=3    changed=2    unreachable=0    failed=1
Slave2               : ok=3    changed=2    unreachable=0    failed=1
```
