### ISSUE TITLE
constructed inventory does not use group variables from previous inventory

### ISSUE THREAD

**Issue by lufik** [ansible/ansible#37397]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
constructed

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The constructed inventory plugin doesn't take group variables from previous inventory into account.

##### STEPS TO REPRODUCE
yaml inventory:
```yaml
group:
  hosts:
    host1:
    host2:
  vars:
    enabled: true
```

constructed inventory:
```yaml
plugin: constructed
strict: False

groups:
  group_enabled: enabled | default(false)
```

```
ANSIBLE_INVENTORY_ENABLED=yaml,constructed ansible group_enabled --list-hosts
```

##### EXPECTED RESULTS
I expect output from above ansible command:
```
  hosts (2):
    host1
    host2
```

##### ACTUAL RESULTS
With current version (also the one from git master HEAD) the output is:
```
  hosts (0):
```

##### FEATURE/FIX
Change ansible/plugins/inventory/constructed.py this way.

Add line:
```
from ansible.inventory.helpers import sort_groups, get_group_vars
```

Replace line(s):
```
hostvars = inventory.hosts[host].get_vars()
```
with:
```
hostvars = combine_vars(get_group_vars(inventory.hosts[host].get_groups()), inventory.hosts[host].get_vars())
```
