### ISSUE TITLE
`user` module with `local: true` fail to move nonexistent user home dir despite that `createhome: true` is set

### ISSUE THREAD

**Issue by Arano-kai** [ansible/ansible#37398]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`user` module

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

Not modified
##### OS / ENVIRONMENT

Master: Debian GNU/Linux 9.3 (stretch)
Slave1: CentOS Linux release 7.4.1708 (Core)
Slave2: Debian GNU/Linux 9.3 (stretch)
##### SUMMARY
As title say.
Also, removing user with nonexistent home and `local: true` lead to fail, while with `local: false` just complain on absent dir.

##### STEPS TO REPRODUCE

Install `libuser`.
Do not use any IPA engine, since it is interfere with `useradd/mod` and provided play may behave differently.

```yaml
---
- hosts: all
  vars:
    username: 'testuser'
  become: true
  tasks:
    - name: 'create some user with `local: false`'
      user:
        name: '{{ username }}'
        createhome: false
        local: false
      register: s

    - fail:
        msg: 'Please specify nonexistent user in vars'
      when: 'not s["changed"]'

    - block:
        - name: 'try to move/create home with `local: false`'
          user:
            name: '{{ username }}'
            home: '/home/{{ username }}_move_create_test'
            createhome: true
            move_home: true
            local: false

      always:
        - name: 'list homes'
          command: 'ls -ld /home/{{ username }}_move_create_test'
          failed_when: false

        - name: 'remove user with `local: false`'
          user:
            name: '{{ username }}'
            state: 'absent'
            remove: true
            local: false

    - name: 'create some user with `local: true`'
      user:
        name: '{{ username }}'
        createhome: false
        local: true
      register: s

    - fail:
        msg: 'Please specify nonexistent user in vars'
      when: 'not s["changed"]'

    - block:
        - name: 'try to move/create home with `local: true`'
          user:
            name: '{{ username }}'
            home: '/home/{{ username }}_move_create_test'
            createhome: true
            move_home: true
            local: true

      always:
        - name: 'list homes'
          command: 'ls -ld /home/{{ username }}_move_create_test'
          failed_when: false

        - name: 'remove user with `local: true`'
          user:
            name: '{{ username }}'
            state: 'absent'
            remove: true
            local: true
```

##### EXPECTED RESULTS
Since `user` module create missed home while move with `local: false`, `move_home: true` and `createhome: true`, that is expected same behavior with `local: true` option.

##### ACTUAL RESULTS

```
ansible-playbook 2.4.3.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
No config file found; using defaults

PLAYBOOK: move_nonexistent_home.yml **********************************************************************************************************
1 plays in move_nonexistent_home.yml

PLAY [all] ***********************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [Slave2]
ok: [Slave1]
META: ran handlers

TASK [create some user with `local: false`] **************************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:7
changed: [Slave2] => {"changed": true, "comment": "", "createhome": false, "failed": false, "group": 1001, "home": "/home/testuser", "name": "testuser", "shell": "", "state": "present", "system": false, "uid": 1001}
changed: [Slave1] => {"changed": true, "comment": "", "createhome": false, "failed": false, "group": 1003, "home": "/home/testuser", "name": "testuser", "shell": "/bin/bash", "state": "present", "system": false, "uid": 1003}

TASK [fail] **********************************************************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:14
skipping: [Slave2] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
skipping: [Slave1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [try to move/create home with `local: false`] *******************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:19
changed: [Slave2] => {"append": false, "changed": true, "comment": "", "failed": false, "group": 1001, "home": "/home/testuser_move_create_test", "move_home": true, "name": "testuser", "shell": "", "state": "present", "uid": 1001}
changed: [Slave1] => {"append": false, "changed": true, "comment": "", "failed": false, "group": 1003, "home": "/home/testuser_move_create_test", "move_home": true, "name": "testuser", "shell": "/bin/bash", "state": "present", "stderr": "usermod: The previous home directory (/home/testuser) does not exist or is inaccessible. Move cannot be completed.\n", "stderr_lines": ["usermod: The previous home directory (/home/testuser) does not exist or is inaccessible. Move cannot be completed."], "uid": 1003}

TASK [list homes] ****************************************************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:28
changed: [Slave2] => {"changed": true, "cmd": ["ls", "-ld", "/home/testuser_move_create_test"], "delta": "0:00:00.002390", "end": "2018-03-14 12:17:41.297689", "failed": false, "failed_when_result": false, "rc": 0, "start": "2018-03-14 12:17:41.295299", "stderr": "", "stderr_lines": [], "stdout": "drwxr-xr-x 1 testuser testuser 54 Мар  2 14:52 /home/testuser_move_create_test", "stdout_lines": ["drwxr-xr-x 1 testuser testuser 54 Мар  2 14:52 /home/testuser_move_create_test"]}
changed: [Slave1] => {"changed": true, "cmd": ["ls", "-ld", "/home/testuser_move_create_test"], "delta": "0:00:00.002985", "end": "2018-03-14 12:17:41.449650", "failed": false, "failed_when_result": false, "rc": 0, "start": "2018-03-14 12:17:41.446665", "stderr": "", "stderr_lines": [], "stdout": "drwxr-xr-x. 1 testuser testuser 64 Mar  3 10:28 /home/testuser_move_create_test", "stdout_lines": ["drwxr-xr-x. 1 testuser testuser 64 Mar  3 10:28 /home/testuser_move_create_test"]}

TASK [remove user with `local: false`] *******************************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:32
changed: [Slave2] => {"changed": true, "failed": false, "force": false, "name": "testuser", "remove": true, "state": "absent", "stderr": "userdel: testuser mail spool (/var/mail/testuser) not found\n", "stderr_lines": ["userdel: testuser mail spool (/var/mail/testuser) not found"]}
changed: [Slave1] => {"changed": true, "failed": false, "force": false, "name": "testuser", "remove": true, "state": "absent"}

TASK [create some user with `local: true`] ***************************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:39
changed: [Slave2] => {"changed": true, "comment": "testuser", "createhome": false, "failed": false, "group": 1001, "home": "/home/testuser", "name": "testuser", "shell": "/bin/sh", "state": "present", "system": false, "uid": 1001}
changed: [Slave1] => {"changed": true, "comment": "testuser", "createhome": false, "failed": false, "group": 1001, "home": "/home/testuser", "name": "testuser", "shell": "/bin/bash", "state": "present", "system": false, "uid": 1001}

TASK [fail] **********************************************************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:46
skipping: [Slave2] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}
skipping: [Slave1] => {"changed": false, "skip_reason": "Conditional result was False", "skipped": true}

TASK [try to move/create home with `local: true`] ********************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:51
fatal: [Slave2]: FAILED! => {"changed": false, "failed": true, "msg": "Error moving /home/testuser to /home/testuser_move_create_test: Error opening `/home/testuser': No such file or directory.\n", "name": "testuser", "rc": 12}
fatal: [Slave1]: FAILED! => {"changed": false, "failed": true, "msg": "Error moving /home/testuser to /home/testuser_move_create_test: Error opening `/home/testuser': No such file or directory.\n", "name": "testuser", "rc": 12}

TASK [list homes] ****************************************************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:60
changed: [Slave2] => {"changed": true, "cmd": ["ls", "-ld", "/home/testuser_move_create_test"], "delta": "0:00:00.002260", "end": "2018-03-14 12:17:43.788060", "failed": false, "failed_when_result": false, "msg": "non-zero return code", "rc": 2, "start": "2018-03-14 12:17:43.785800", "stderr": "ls: cannot access /home/testuser_move_create_test: No such file or directory", "stderr_lines": ["ls: cannot access /home/testuser_move_create_test: No such file or directory"], "stdout": "", "stdout_lines": []}
changed: [Slave1] => {"changed": true, "cmd": ["ls", "-ld", "/home/testuser_move_create_test"], "delta": "0:00:00.004337", "end": "2018-03-14 12:17:43.958333", "failed": false, "failed_when_result": false, "msg": "non-zero return code", "rc": 2, "start": "2018-03-14 12:17:43.953996", "stderr": "ls: cannot access /home/testuser_move_create_test: No such file or directory", "stderr_lines": ["ls: cannot access /home/testuser_move_create_test: No such file or directory"], "stdout": "", "stdout_lines": []}

TASK [remove user with `local: true`] ********************************************************************************************************
task path: /home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.yml:64
fatal: [Slave1]: FAILED! => {"changed": false, "failed": true, "msg": "Error removing home directory: Error opening `/home/testuser_move_create_test': No such file or directory.\n", "name": "testuser", "rc": 9}
fatal: [Slave2]: FAILED! => {"changed": false, "failed": true, "msg": "Error removing home directory: Error opening `/home/testuser_move_create_test': No such file or directory.\n", "name": "testuser", "rc": 9}
        to retry, use: --limit @/home/user/ansible/ansible_bugs/move_nonexistent_home/move_nonexistent_home.retry

PLAY RECAP ***********************************************************************************************************************************
Slave1              : ok=7    changed=6    unreachable=0    failed=2
Slave2               : ok=7    changed=6    unreachable=0    failed=2
```
