### ISSUE TITLE
xml module reports changes even when no changes are performed

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#37404]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
xml

##### ANSIBLE VERSION

```
ansible 2.4.3.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It seems that the XML module reports ``changed: true`` even when no changes are performed into the XML file. 

The backup file being created is identical with the final file.

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/xml.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/xml.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @cmprescott @dagwieers @sm4rk0 @tbielawa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sm4rk0** [comment]
Could you give some steps to reproduce in order to find the error in module?
Hint for debugging:
There's `changed` argument to the `finish` method, but it's never used.

**Comment by aoyawale** [comment]
in my case I'm modifying a AMQ broker.xml after being created.
```
- name: clustering - add static connectors
  xml:
    path: "{{ amq_broker_dir }}/{{ amq_broker_name }}/etc/broker.xml"
    xpath: /conf:configuration/core:core/core:connectors
    add_children:
      - connector:
          name: "{{ item.name }}"
    namespaces:
      conf: urn:activemq
      core: urn:activemq:core
    pretty_print: yes
```
Here are the results:
```
< TASK [amq : clustering - add static connectors] >
 -------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|search` instead use `result is search`. This feature will be removed in version 2.9. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [0.0.0.0] => (item={u'name': u'broker2', u'value': u'tcp://0.0.0.0'})
changed: [0.0.0.0] => (item={u'name': u'broker2', u'value': u'tcp://0.0.0.0'})
changed: [0.0.0.0] => (item={u'name': u'broker1', u'value': u'tcp://0.0.0.0'})
```
