### ISSUE TITLE
Implementation of additional options for gce_lb needed

### ISSUE THREAD

**Issue by mmolinac** [ansible/ansible#37412]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
gce_lb

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/mmolinac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0_3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
[defaults]
allow_world_readable_tmpfiles=True
host_key_checking = False
retry_files_enabled = False
[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s
control_path_dir = /tmp/.ansible/cp

##### OS / ENVIRONMENT
Ansible running on MacOS High Sierra 10.13.3, Darwin Kernel Version 17.4.0
Managing: Debian GNU/Linux 9.3, x86_64

##### SUMMARY
The module gce_lb is able to create layer-4 load balancer elements in Google Cloud.
The elements that you can create now with gce_lb are described here:

https://cloud.google.com/compute/docs/load-balancing/network/?hl=en_US

However, **GCE also has layer-7 load balancer resources available, and there's no way to create them through gce_lb**.

The mentioned product is described here:
https://cloud.google.com/compute/docs/load-balancing/http/?hl=en_US

In the latter, you are able to add SSL certificates and so.

##### STEPS TO REPRODUCE

```yaml
    - name: Load balancer for Frontend production instances
      gce_lb:
        name:     'frontend-lb'
        region:   "{{ region }}"
        members:  "['europe-west1-b/frontend01', 'europe-west1-b/frontend02']"
        protocol: tcp
        httphealthcheck_name: frontend-hc
        httphealthcheck_port: 80
        httphealthcheck_host: ui.domain.com
        httphealthcheck_path: /my/login
        port_range:           '443-443'
        httphealthcheck_healthy_count: 2
        httphealthcheck_unhealthy_count: 3
        service_account_email: "{{ service_account_email }}"
        credentials_file:      "{{ credentials_file }}"
        project_id:            "{{ project_id }}"
        state:                 present

```
This example currently creates a layer-4 load balancer without SSL certificates involved, but there's no way to provide them to create layer-7 load balancers.

##### EXPECTED RESULTS

I was expecting to be able to create a layer-7 load balancer.

##### ACTUAL RESULTS

Actually, we're only able to create layer-4 load balancers.

```

```
