### ISSUE TITLE
ovirt_cluster, failing with the "TypeError" on the ovirtsdk4 library

### ISSUE THREAD

**Issue by mkrish004c** [ansible/ansible#37425]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ovirt_cluster:

##### ANSIBLE VERSION
```
Ansible 2.4.1.0 
```

##### CONFIGURATION
```
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ansible/plugins/callback']
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['logstash']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
SYSTEM_WARNINGS(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL 7.3

##### SUMMARY
Ovirt_cluster module is failing every time with python "TypeError" on ovirtsdk4 modules.

##### STEPS TO REPRODUCE

```
- name: set cluster policies
  ovirt_cluster:
    auth: "{{ ovirt_auth }}"
    name: "{{ rhv_cluster_name }}"
    data_center: "{{ rhv_datacenter_name }}"
    cpu_arch: x86_64
    cpu_type: Intel Broadwell-noTSX Family
    mac_pool: Default
    scheduling_policy: evenly_distributed
    threads_as_cores: true
```

##### EXPECTED RESULTS

Expect the Cluster should be created.

##### ACTUAL RESULTS

But ends with below TypeError from the module library,

```
{
    "_ansible_parsed": true,
    "exception": "Traceback (most recent call last):\n  File \"/tmp/ansible_9Sutik/ansible_module_ovirt_cluster.py\", line 594, in main\n    ret = clusters_module.create()\n  File \"/tmp/ansible_9Sutik/ansible_modlib.zip/ansible/module_utils/ovirt.py\", line 545, in create\n    new_entity = self.build_entity()\n  File \"/tmp/ansible_9Sutik/ansible_module_ovirt_cluster.py\", line 460, in build_entity\n    self.param('cpu_arch') or self.param('cpu_type')\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/types.py\", line 804, in __init__\n    self.architecture = architecture\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/types.py\", line 913, in architecture\n    Struct._check_type('architecture', value, Architecture)\n  File \"/usr/lib64/python2.7/site-packages/ovirtsdk4/__init__.py\", line 128, in _check_type\n    expected=expected.__name__,\nTypeError: The type 'str' isn't valid for attribute 'architecture', it must be 'Architecture'\n",
    "_ansible_no_log": false,
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": ""
    },
    "msg": "The type 'str' isn't valid for attribute 'architecture', it must be 'Architecture'"
}
```
