### ISSUE TITLE
lineinfile ignores regex match and inserts line which contains \n

### ISSUE THREAD

**Issue by den-is** [ansible/ansible#37448]
- Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /home/den/.ansible.cfg
  configured module search path = [u'/home/den/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/den/.local/lib/python2.7/site-packages/ansible
  executable location = /home/den/.local/bin/ansible
  python version = 2.7.14 (default, Feb 27 2018, 20:43:24) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
```

##### OS / ENVIRONMENT
```
host: fedora 27 x64
target: centos7 1708
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  remote_user: root
  vars:
    extra_config:
      - regex: ^export EDITOR=vim
        line: |
          export EDITOR=vim
          export VISUAL=$EDITOR

  tasks:
  - name: ZSH custom config
    lineinfile:
      path: ~/.zshrc
      regexp: '{{ item.regex }}'
      line: '{{ item.line }}'
    with_items: '{{ extra_config }}'
```

##### EXPECTED RESULTS
Don't change resource as it already exists

##### ACTUAL RESULTS
lineinfile always appends line after `\n`
```
TASK [ohmyzsh : ZSH custom config] ********************************************************************************************************************************************************************************
changed: [10.66.150.43] => (item={u'regex': u'^export EDITOR=vim', u'line': u'export EDITOR=vim\nexport VISUAL=$EDITOR\n'})

PLAY RECAP ********************************************************************************************************************************************************************************************************
10.66.150.43               : ok=7    changed=1    unreachable=0    failed=0
```
```
export EDITOR=vim
export VISUAL=$EDITOR
export VISUAL=$EDITOR
export VISUAL=$EDITOR
export VISUAL=$EDITOR
```

I have tried different regex patterns for match
```
EDITOR=vim
export EDITOR=vim
^export EDITOR=vim
^export EDITOR=vim\n
```
