### ISSUE TITLE
docker_service's container_name conflicts with scale

### ISSUE THREAD

**Issue by sergeyjsg** [ansible/ansible#37471]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_service

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /Users/sergey/.ansible.cfg
  configured module search path = [u'/Users/sergey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
RETRY_FILES_ENABLED(/Users/sergey/.ansible.cfg) = False

##### OS / ENVIRONMENT
OS X (master) vs Ubuntu (slave)

##### SUMMARY
docker_service's container_name option conflicts with scale option. When both specified and scale >= 1, for service name `hohoho` dummy error is thrown: `"msg": "Error scaling hohoho - "`

##### STEPS TO REPRODUCE
```yaml
- hosts: apps
   tasks:
   - name: Run
      docker_service:
        project_name: workers
        definition:
          version: '2'
          services:
            hohoho:
              container_name: hohoho_hoho
              image: <<>>
      recreate: always
      state: present
      scale:
          hohoho: 2
```

##### EXPECTED RESULTS
Service scaled

##### ACTUAL RESULTS
Container name was not properly modified. As far as I understand, index should be added to container name like `contaner_name - 1`, `contaner_name - 2`, `contaner_name - 3`. But this not happening. Which is confirmed by verbose output: 
 ```ERROR: for hohoho_hoho  Cannot create container for service hohoho: Conflict. The container name "/hohoho_hoho" is already in use by container "a7f885e5048aa84f7f8f3baa9361e824610c2cc07b7cca3ea2104308a767a94f". You have to remove (or rename) that container to be able to reuse that name.\r\n\r\n{"msg": "Error scaling hohoho - ", "failed": true,```
