### ISSUE TITLE
consul function 'script' depreciated by Consul

### ISSUE THREAD

**Issue by cryptmin** [ansible/ansible#37472]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

consul
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/ash/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ash/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ash/.local/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

```
##### CONSUL VERSION
```
Consul v1.0.6
Protocol 2 spoken by default, understands 2 to 3 (agent will automatically use protocol >2 when speaking to compatible agents)
```
##### CONFIGURATION

ANSIBLE_COW_SELECTION(env: ANSIBLE_COW_SELECTION) = duck
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = False

##### OS / ENVIRONMENT

host = Ubuntu 17.10
remote_host = Ubuntu 16.04.4 LTS
##### STEPS TO REPRODUCE

To reproduce use the 'script' function of the 'consul' ansible module. To verify check consul log and poll the Consul Health API.

```yaml
- name: Check google.com with ICMP
  consul:
    service_name: google
    service_address: google.com
    script: "fping -c 2 google.com"
    interval: 60s
```

##### EXPECTED RESULTS

Health check added to consul
##### ACTUAL RESULTS

```
Consul Error: 2018/03/14 17:28:18 [WARN] agent: check "service:google" has the 'script' field, which has been deprecated and replaced with the 'args' field. See https://www.consul.io/docs/agent/checks.html
```

```

```
