### ISSUE TITLE
win_copy breaks if dest value contains a quoted path

### ISSUE THREAD

**Issue by drewmullen** [ansible/ansible#37486]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_copy

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible', u'/opt/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### OS / ENVIRONMENT
RHEL 7.4

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['foreman']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 200
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = implicit
DEFAULT_GATHER_SUBSET(/etc/ansible/ansible.cfg) = all,!ohai,!hardware,!virtual,!network
DEFAULT_GATHER_TIMEOUT(/etc/ansible/ansible.cfg) = 20
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible', u'/opt/ansible/library']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/linux_eng/.ssh/id_rsa.ansible
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = linux_eng
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/opt/ansible/roles', u'/opt/ansible/atrium/roles']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### SUMMARY
if you attempt to copy a file from ansible localhost to a windows remote host and you have the destination value quoted, ansible throws a syntax error

##### STEPS TO REPRODUCE

the following code **DOES NOT** work
```yaml
  - name: copy - add custom facts to hosts
      win_copy:
        src: ../files/custom_fact
        dest: "C:\programdata\puppetlabs\facter\facts.d\payx_custom_fact.ps1"
```

the following code **DOES** work
```yaml
  - name: copy - add custom facts to hosts
      win_copy:
        src: ../files/custom_fact
        dest: C:\programdata\puppetlabs\facter\facts.d\payx_custom_fact.ps1
```

I found this because i was attempting to use a var in the dest name. It throws the error whether or not you use a var in the quote.

##### EXPECTED RESULTS
expect it to copy the file

##### ACTUAL RESULTS

error
```
The offending line appears to be:

        src: test.log
        dest: "C:\programdata\puppetlabs\facter\facts.d\test.log"
                 ^ here
This one looks easy to fix.  It seems that there is a value started
with a quote, and the YAML parser is expecting to see the line ended
with the same kind of quote.  For instance:

    when: "ok" in result.stdout

Could be written as:

   when: '"ok" in result.stdout'

Or equivalently:

   when: "'ok' in result.stdout"

```
