### ISSUE TITLE
Ansible Skips tasks unless task put in between

### ISSUE THREAD

**Issue by Zodzie** [ansible/ansible#37495]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

service

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = None
  configured module search path = [u'/Users/rrosado/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

##### OS / ENVIRONMENT

MacOS Sierra
##### SUMMARY

Task in role does not get played

##### STEPS TO REPRODUCE

playbook.yml > import_role > import_tasks configure.yml > configure.yml contains:

```yaml
- name: template
  template:
    src: "haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
    backup: yes

- service:
    name: haproxy
    state: restarted
```

service does not play.  If I setup configure.yml like this:

```yaml
- name: template
  template:
    src: "haproxy.cfg.j2"
    dest: /etc/haproxy/haproxy.cfg
    backup: yes

- name: test
  debug:
    var: result
    verbosity: 2

- service:
    name: haproxy
    state: restarted
```
Then it does work.

```yaml
ansible-playbook -i inventory playbook.yml --extra-vars "action=configure"
```

##### EXPECTED RESULTS

expect "service" task to run

##### ACTUAL RESULTS

service task is skipped until i put a task in between template and service.

```
PLAY [haproxy] ***********************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************
ok: [208.94.242.250]

TASK [haproxy : template] ************************************************************************************************************
ok: [208.94.242.250]

PLAY RECAP ***************************************************************************************************************************
208.94.242.250             : ok=2    changed=0    unreachable=0    failed=0
```

As you can see, service skipped
