### ISSUE TITLE
nxos_bgp_af.py local variable 'command' referenced before assignment

### ISSUE THREAD

**Issue by indivisiblewalrus** [ansible/ansible#37494]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nxos_bgp_af

##### ANSIBLE VERSION

```
2.5.0rc2
```

##### CONFIGURATION
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
PARAMIKO_HOST_KEY_AUTO_ADD(env: ANSIBLE_PARAMIKO_HOST_KEY_AUTO_ADD) = True

##### OS / ENVIRONMENT
debian9
nxos 7.0.3(I7)

##### STEPS TO REPRODUCE

```yaml
    vars: 
       bgp_asn: 65333
       l3_interfaces: 
          - { interface: eth1/1, addr: 1.1.1.1/31}
          - { interface: eth1/2, addr: 2.2.2.1/31}
          - { interface: eth1/3, addr: 3.3.3.1/31}
       loopbacks: 
          - { interface: loop1, addr: 1.1.1.11/32}
          - { interface: loop2, addr: 2.2.2.22/32}

    - name: Building underlay network list
      set_fact:
        underlay_networks: "{{ underlay_networks|default([]) + [[item.addr|ipaddr('network/prefix'),'']] }}"
      with_items:
        - "{{ l3_interfaces }}"
        - "{{ loopbacks }}"
      when: item.vrf is undefined
      tags: test

    - name: print variable
      debug:
        msg: "{{ underlay_networks }}"
      tags: test

    - name: Advertise Underlay Prefixes
      nxos_bgp_af:
        asn: "{{ bgp_asn }}"
        afi: ipv4
        safi: unicast
        vrf: default
        networks:
          - "{{ underlay_networks }}"
        provider: "{{ nxos_provider }}"
      with_items:
        - "{{ l3_interfaces }}"
      when: item.vrf is undefined
      tags: test
```

##### EXPECTED RESULTS
Expected configuration to be applied:
router bgp 65333
  address-family ipv4 unicast
    network 1.1.1.0/31
    network 1.1.1.11/32
    network 2.2.2.0/31
    network 2.2.2.22/32
    network 3.3.3.0/31
     

##### ACTUAL RESULTS
```
TASK [leaf : print variable] ******************************************************************************************************************************
task path: /home/pete/ansible/playbooks/Lab/POD3/roles/leaf/tasks/main.yml:622
ok: [switch01] => {
    "msg": [
        [
            "1.1.1.0/31", 
            ""
        ], 
        [
            "2.2.2.0/31", 
            ""
        ], 
        [
            "3.3.3.0/31", 
            ""
        ], 
        [
            "1.1.1.11/32", 
            ""
        ], 
        [
            "2.2.2.22/32", 
            ""
        ]
    ]
}

===================================================================
===================================================================
TASK [leaf : Advertise Underlay Prefixes] ****************************************************************************************************
task path: /home/pete/ansible/playbooks/Lab/POD3/roles/leaf/tasks/main.yml:627
<switch01> connection transport is nxapi
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/network/nxos/nxos_bgp_af.py
<switch01> ESTABLISH LOCAL CONNECTION FOR USER: pete
<switch01> EXEC /bin/sh -c 'echo ~ && sleep 0'
<switch01> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/pete/.ansible/tmp/ansible-tmp-1521146182.45-168292732118639 `" && echo ansible-tmp-1521146182.45-168292732118639="` echo /home/pete/.ansible/tmp/ansible-tmp-1521146182.45-168292732118639 `" ) && sleep 0'
<switch01> PUT /home/pete/.ansible/tmp/ansible-local-14439mQqkUA/tmpfKCVRG TO /home/pete/.ansible/tmp/ansible-tmp-1521146182.45-168292732118639/nxos_bgp_af.py
<switch01> EXEC /bin/sh -c 'chmod u+x /home/pete/.ansible/tmp/ansible-tmp-1521146182.45-168292732118639/ /home/pete/.ansible/tmp/ansible-tmp-1521146182.45-168292732118639/nxos_bgp_af.py && sleep 0'
<switch01> EXEC /bin/sh -c '/usr/bin/python /home/pete/.ansible/tmp/ansible-tmp-1521146182.45-168292732118639/nxos_bgp_af.py && sleep 0'
<switch01> EXEC /bin/sh -c 'rm -f -r /home/pete/.ansible/tmp/ansible-tmp-1521146182.45-168292732118639/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_pyrSvZ/ansible_module_nxos_bgp_af.py", line 825, in <module>
    main()
  File "/tmp/ansible_pyrSvZ/ansible_module_nxos_bgp_af.py", line 809, in main
    state_present(module, existing, proposed, candidate)
  File "/tmp/ansible_pyrSvZ/ansible_module_nxos_bgp_af.py", line 669, in state_present
    network_commands = get_network_command(existing, key, value)
  File "/tmp/ansible_pyrSvZ/ansible_module_nxos_bgp_af.py", line 546, in get_network_command
    commands.append(command)
UnboundLocalError: local variable 'command' referenced before assignment

fatal: [switch01]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_pyrSvZ/ansible_module_nxos_bgp_af.py\", line 825, in <module>\n    main()\n  File \"/tmp/ansible_pyrSvZ/ansible_module_nxos_bgp_af.py\", line 809, in main\n    state_present(module, existing, proposed, candidate)\n  File \"/tmp/ansible_pyrSvZ/ansible_module_nxos_bgp_af.py\", line 669, in state_present\n    network_commands = get_network_command(existing, key, value)\n  File \"/tmp/ansible_pyrSvZ/ansible_module_nxos_bgp_af.py\", line 546, in get_network_command\n    commands.append(command)\nUnboundLocalError: local variable 'command' referenced before assignment\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```
