### ISSUE TITLE
AWX throws templating error when using a template to set a variable value under set_fact method

### ISSUE THREAD

**Issue by AMHAnsible9** [ansible/ansible#37509]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log

##### OS / ENVIRONMENT

Operating System: Red Hat 4.8.5-16
Cisco ASA version: asa841-k8.bin

##### SUMMARY

When using the set_fact method and the variable to set involves using a template, Ansible intermittently throws the following templating error:

`"msg": "Unexpected templating type error occurred on ({{ ((dir_output.stdout_lines[0])[-1] | regex_search(regexp,'\\\\g<fs>') | list)[0] | int }}): 'NoneType' object is not iterable"`

##### STEPS TO REPRODUCE

To reproduce, use the set_fact method and try to set the variable value based upon the result of a regular expression using a template:

For example:

```yaml
   - name: Check flash directory free space
      asa_command:
        commands:
          - command: "dir {{ new_image.filesystem }}"
      register: dir_output
    - name: Record number of bytes free within Flash
      set_fact:
        flash_free_space: "{{ ((dir_output.stdout_lines[0])[-1] | regex_search(regexp,'\\g<fs>') | list)[0] | int }}"
      vars:
        regexp: '(?P<fs>[0-9]*) bytes free'`

```

The code snippet above looks to record the number of bytes free within the flash directory of a Cisco ASA device by looking at the end of the output and locating the value next to "bytes free".

##### EXPECTED RESULTS

The following result is expected:

`"ansible_facts": {
        "flash_free_space": "154906624"
    }`

##### ACTUAL RESULTS

The following result is observed, albeit intermittently:

```

"msg": "Unexpected templating type error occurred on ({{ ((dir_output.stdout_lines[0])[-1] | regex_search(regexp,'\\\\g<fs>') | list)[0] | int }}): 'NoneType' object is not iterable"

```
