### ISSUE TITLE
[parted] Parted module uses different format of unit 

### ISSUE THREAD

**Issue by qk4l** [ansible/ansible#37522]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
* parted

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Parted module uses different format of `unit` for different states
`info` state return unit in  in low case but `present` requests to provide its in same format as GNU parted returns.

So we can not use `info` state for dumping disk partitions and restore them lately.

##### STEPS TO REPRODUCE
```yaml
    - name: Get partitions info
      parted:
        device: /dev/{{ devname }}
        unit: MiB
      register: parted_info

##   ... some actions or time 

  - name: Restore partitions to disk
    become: True
    parted:
      device: /dev/{{ devname }}
      number: "{{ item.num }}"
      part_start: "{{ item.begin }}{{ item.unit }}"
      part_end: "{{ item.end }}{{ item.unit }}"
      flags: "{{ item.flags }}"
      unit: "{{ item.unit }}"
      state: present
    with_items:
     - "{{ parted_info.partitions }}"
```

##### EXPECTED RESULTS
Created partitions based on dump info

##### ACTUAL RESULTS
Failed
```
{u'module_args': {u'part_start': u'121743.0', u'part_end': u'476938.0', u'align': u'optimal', u'number': 3, u'state': u'present', u'part_type': u'primary', u'flags': [u'type=83'], u'device': u'/dev/sdb', u'unit': u'mib'}}, u'msg': u'value of unit must be one of: B,KB,MB,GB,TB,B,KiB,MiB,GiB,TiB,s,%,cyl,chs,compact, got: mib'}
```
