### ISSUE TITLE
Add a object/map/dict form of !vault vault encrypted variables

### ISSUE THREAD

**Issue by alikins** [ansible/ansible#37536]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
lib/ansible/parsing/vault/__init__.py
lib/ansible/parsing/yaml/objects.py
lib/ansible/parsing/yaml/constructor.py

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 93d2761551) last updated 2018/03/16 11:53:02 (GMT -400)
  config file = None
  configured module search path = [u'/home/adrian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/adrian/src/ansible/lib/ansible
  executable location = /home/adrian/src/ansible/bin/ansible
  python version = 2.7.14 (default, Feb 27 2018, 20:43:24) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]

```

##### SUMMARY

In addition to supporting vault encrypted strings in yaml via the custom !vault yaml tag, it
would be useful to have a way to use a yaml object/map to describe a encrypted vault variable.

reasons:

1) Support loading of the data without requiring support for the ansible custom !vault yaml tag

2) If we add support for vault vars in JSON (see https://github.com/ansible/ansible/issues/37531) then this format would mirror the JSON approach

3) Would provide a more extensible format for describing vault vars in the future. If we add support for PKI, or more cipher types, or if we make params like the number of key stretching rounds tuneable, this
would provide a mechanism to provide that info and context.

For example, something like:

``` yaml
 some_var: !vault-plaintext:
                     vault_id: 'dev'
                     vault_text: |
                                    $ANSIBLE_VAULT;1.1;AES256                  
        66393964663765613335633461643334393234346231666665306635323635333137306339356232
```

Or possibly, a variant with out a custom yaml tag at all, possibly using a meaningful var or key name to identify it.

``` yaml
some_var:
   _ansible_type: 'AnsibleVaultEncryptedUnicode'
   'vault_text':  |
                       $ANSIBLE_VAULT;1.1;AES256                 
       66393964663765613335633461643334393234346231666665306635323635333137306339356232
```
or

``` yaml
some_var:
   _vault_encrypted:
        vault_text: |
                       $ANSIBLE_VAULT;1.1;AES256                 
       66393964663765613335633461643334393234346231666665306635323635333137306339356232
```

Related:
https://github.com/ansible/ansible/issues/37531

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
