### ISSUE TITLE
Accessing the Ansible vars inside a Python script

### ISSUE THREAD

**Issue by bytebandit007** [ansible/ansible#37589]
Hi,

##### ISSUE TYPE
 - Documentation Report
##### ANSIBLE VERSION
```
2.4.3.0
```
##### COMPONENT NAME
comand
##### SUMMARY
I am trying to have access to the Ansible vars inside the python script. However, the behavior is not similar to the bash files.

Is there any best practice for this purpose without sending them as args to the script?

##### STEPS TO REPRODUCE
My simplified playbook:
- name: Exec python
  hosts: master
  vars:
    VERSION: "2.7"
  become: yes
  become_user: root
  tasks:
    - name: copy script
      copy:
        src: ./files/print_version.py
        dest: /home/ccloud/print_version.py
        owner: ccloud
        mode: 0775

    - name: run a python command!
      command: python /home/ccloud/print_version.py

Simplified print_version.py:
print {{ VERSION }}

##### ACTUAL RESULTS
```
NameError: name 'VERSION' is not defined
```

Thanks and best regards,
Milad

**Comment by ansibot** [comment]
@Milad-Irani Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- issue type
- ansible version
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by alikins** [comment]
@Milad-Irani 

Is there any best practice for this purpose without sending them as args to the script?

STEPS TO REPRODUCE
My simplified playbook:

``` yaml
- name: Exec python
  hosts: master
  vars:
    VERSION: "2.7"
  become: yes
  become_user: root
  tasks:
    - name: copy script
      copy:
        src: ./files/print_version.py
        dest: /home/ccloud/print_version.py
        owner: ccloud
        mode: 0775

    - name: run a python command!
      command: python /home/ccloud/print_version.py
```

```
Simplified print_version.py:
print {{ VERSION }}
```

> Is there any best practice for this purpose without sending them as args to the script?

The ansible vars are not environment variables and are not shared with processes started with 'command:'.  The ansible vars are only known to the ansible controller (the 'ansible-playbook'
process) unless passed to tasks (like 'command:') as task args.

 ```
Simplified print_version.py:
print {{ VERSION }}
```

That is not valid python.  '{{ VERSION }}' is a jinja template expression and only makes sense to reference from playbook yaml.

The `print_version.py' executed via command: is running on the remote system ('master') and does not have access to any ansible_vars unless passed to it as part of the task args. The ansible vars are replaced with there values before passing it to the remote task.

``` yaml
    - name: run a python command!
      command: echo {{ VERSION }}
```
would eval {{ VERSION }} before passing the result to the remote task. The command that
gets sent to the remote in that case would be 'echo 2.7'. 


This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

 This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.
