### ISSUE TITLE
HAProxy Drain mode then MAINT not working as expected.

### ISSUE THREAD

**Issue by guldil** [ansible/ansible#37591]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

haproxy
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Ubuntu 16.04
##### STEPS TO REPRODUCE

```  - name: drain mode
    haproxy:
      state: disabled
      host: 'web01'
      socket: /var/run/haproxy/admin.sock
      backend: 'my_backend'
      wait: yes
      drain: yes
      wait_interval: 1
      wait_retries: 60
```

##### EXPECTED RESULTS
ansible has to put web01 in DRAIN Mode, check every second "current session" and when session equal to 0, ansible has to put web01 in MAINT.

##### ACTUAL RESULTS

it always stay in DRAIN 

```
PLAY [haproxy02] ***************************************************************
TASK [Gathering Facts] *********************************************************
ok: [haproxy02]
TASK [drain mode] **************************************************************
fatal: [haproxy02]: FAILED! => {"changed": false, "msg": "server my_backend/web01 not status 'DRAIN' after 60 retries. Aborting."}
        to retry, use: --limit @/etc/ansible/playbooks/drain-mode-haproxy.retry

PLAY RECAP *********************************************************************
haproxy02                  : ok=1    changed=0    unreachable=0    failed=1
```

Show stat from socket : 
```
my_backend,web01,0,0,0,0,,0,0,0,,0,,0,0,0,0,DRAIN,1,1,0,0,9,225,62500,,1,19,1,,0,,2,0,,0,L7OK,200,19,0,0,0,0,0,0,0,,,,0,0,,,,,-1,HTTP content check matched,,0,0,0,0,
```

Documentation : 
```
# Place server in drain mode, providing a socket file.  Then check the server's
# status every minute to see if it changes to maintenance mode, continuing if it
# does in an hour and failing otherwise.
- haproxy:
    state: disabled
    host: '{{ inventory_hostname }}'
    socket: /var/run/haproxy.sock
    backend: www
    wait: yes
    drain: yes
    wait_interval: 1
    wait_retries: 60
```

I'm using a PHP script doing the same action, look like something is  misunderstood by developper, DRAIN to MAINT is not automatic feature in HAPROXY, you have to send 2 socket commands.

Thanks

Guldil
