### ISSUE TITLE
Openshift admin Rolebinding not added correctly

### ISSUE THREAD

**Issue by twhiston** [ansible/ansible#37600]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openshift_raw

##### ANSIBLE VERSION
```
ansible 2.6.0 (devel d3df0249af) last updated 2018/03/15 12:07:45 (GMT +200)
  config file = /Users/twhiston/.ansible.cfg
  configured module search path = [u'/Users/twhiston/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/devel/lib/ansible
  executable location = /usr/local/Cellar/ansible/devel/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When performing an openshift rolebinding action the admin group is not added correctly, and instead the logged in user (who's token ansible uses) is added.
All other roles are bound properly and produce the expected result.

##### STEPS TO REPRODUCE

Rolebinding action, which is performed after the groups are created (that steps works as intended). Ignore errors is necessary due to an issue with the result keys #36939

```yaml
- name: Bind roles to groups
  ignore_errors: yes
  openshift_raw:
    host: "{{ openshift_host }}"
    api_version: v1
    api_key: "{{ oc_token }}"
    verify_ssl: "{{ verify_ssl }}"
    definition: "{{ lookup('template', '../files/rolebinding.yml') | from_yaml }}"
    state: present
  with_items:
    - admin
    - edit
    - view
```

rolebinding.yml
```yaml
apiVersion: v1
groupNames:
- "{{ project_name }}-{{ item }}"
kind: RoleBinding
metadata:
  name: "{{ item }}"
  namespace: "{{ project_name }}"
roleRef:
  name: "{{ item }}"
subjects:
- kind: Group
  name: "{{ project_name }}-{{ item }}"
userNames: null
```

##### EXPECTED RESULTS

```
NAME                    ROLE                    USERS          GROUPS                                                 SERVICE ACCOUNTS   SUBJECTS
admin                   /admin                                 openshift-test-admin                                       
edit                    /edit                                  openshift-test-edit                                        
system:deployers        /system:deployer                                                                              deployer           
system:image-builders   /system:image-builder                                                                         builder            
system:image-pullers    /system:image-puller                   system:serviceaccounts:openshift-test                      
rolebinding "admin" editediew                                  openshift-test-view       
```

##### ACTUAL RESULTS

```
NAME                    ROLE                    USERS          GROUPS                                                 SERVICE ACCOUNTS   SUBJECTS
admin                   /admin                  tomw@nine.ch                                                                             
edit                    /edit                                  openshift-test-edit                                        
system:deployers        /system:deployer                                                                              deployer           
system:image-builders   /system:image-builder                                                                         builder            
system:image-pullers    /system:image-puller                   system:serviceaccounts:openshift-test                      
view                    /view                                 openshift-test-view                                        
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/openshift/openshift_raw.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/openshift/openshift_raw.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @sdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by twhiston** [comment]
I did some more research on this and it seems like when it is posted to the api it does not update the admin RoleBinding properly because it already exists. The openshift_raw module states that it should act like a patch if the object exists, but this clearly doesn't happen in this case. As soon as I change the RoleBinding name to something else (project-admin for example), it works properly, and can bind to the admin role successfully. So I guess the workaround is 'dont call your RoleBinding admin' for now.

**Comment by aioue** [comment]
Found the same for `edit` and the other roles. So you don't wipe out any existing bindings, make the `metadata->name` something unique.

**Comment by fabianvf** [comment]
Hmm, I'm surprised to still see this behavior, 
@aioue do you have an example failing playbook?

**Comment by aioue** [comment]
I've deleted all my test code from earlier. Didn't expect a fix as `openshift_raw` is warning as deprecated now. It's possible it was a user error on my part, not understanding the module/OSh API.

Untested:

#### Unexpected action. Altered an existing other user (bob) with edit role applied and overwrote their permission, instead of just assigning edit role to a specific new user (alice):
```
- name: add permission to OSh user
  openshift_raw:
    definition:
      apiVersion: authorization.openshift.io/v1
      kind: RoleBinding
      metadata:
        name: edit
        namespace: "{{ client }}-{{ env }}"
      roleRef:
        name: edit
      subjects:
      - kind: User
        name: alice
```

#### Does what was actually intended and assigns edit role to a specific user:
```
- name: add permission to OSh user
  openshift_raw:
    definition:
      apiVersion: authorization.openshift.io/v1
      kind: RoleBinding
      metadata:
        name: alice
        namespace: "{{ client }}-{{ env }}"
      roleRef:
        name: edit
      subjects:
      - kind: User
        name: alice
```

Only difference was the metadata->name value not being named the same as a role.
