### ISSUE TITLE
Uri integration test fail on pyopenssl installation

### ISSUE THREAD

**Issue by zopar** [ansible/ansible#37613]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
uri integration test 

##### ANSIBLE VERSION

```
Related to shippable test environment
Related also to ansible devel
```

##### SUMMARY

Uri integration test fail, reference
https://app.shippable.com/github/ansible/ansible/runs/58252/
/root/ansible/test/integration/targets/uri/tasks/main.yml:284 / [testhost] testhost: uri : install urllib3 and pyopenssl via pip state=latest, name={{ item }}

The problem is that in the test server the version of pip is too old

A possible fix is to add pip on the task to force the system to upgrade pip and setuptools
```
- name: install urllib3 and pyopenssl via pip
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - pip
    - urllib3
    - PyOpenSSL
  when: not ansible_python.has_sslcontext and not is_ubuntu_precise|bool
```

##### STEPS TO REPRODUCE

Run this command
ansible-test integration --color -v uri --docker centos6

This is the task that fail
```
- name: install urllib3 and pyopenssl via pip
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - urllib3
    - PyOpenSSL
  when: not ansible_python.has_sslcontext and not is_ubuntu_precise|bool

```

##### EXPECTED RESULTS

Correct installation of PyOpenSSL

##### ACTUAL RESULTS

```
2018-03-19 05:14:43 failed: [testhost] (item=PyOpenSSL) => {"changed": false, "cmd": "/usr/bin/pip2 install -U PyOpenSSL", "item": "PyOpenSSL", "msg": "stdout: Collecting PyOpenSSL\n  Downloading pyOpenSSL-17.5.0-py2.py3-none-any.whl (53kB)\nCollecting six>=1.5.2 (from PyOpenSSL)\n  Downloading six-1.11.0-py2.py3-none-any.whl\nCollecting cryptography>=2.1.4 (from PyOpenSSL)\n  Downloading cryptography-2.2.tar.gz (443kB)\n    Complete output from command python setup.py egg_info:\n    Traceback (most recent call last):\n      File \"<string>\", line 20, in <module>\n      File \"/tmp/pip-build-ybgg6G/cryptography/setup.py\", line 28, in <module>\n        \"cryptography requires setuptools 18.5 or newer, please upgrade to a \"\n    RuntimeError: cryptography requires setuptools 18.5 or newer, please upgrade to a newer version of setuptools\n    \n    ----------------------------------------\n\n:stderr: You are using pip version 7.1.0, however version 9.0.2 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\n/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.\n  InsecurePlatformWarning\nCommand \"python setup.py egg_info\" failed with error code 1 in /tmp/pip-build-ybgg6G/cryptography\n"}
```
