### ISSUE TITLE
ipa_hostgroup module has undesired results

### ISSUE THREAD

**Issue by krispayne** [ansible/ansible#37620]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ipa_hostgroup module

##### ANSIBLE VERSION

```
2.3.2.0
```

##### CONFIGURATION

stock

##### OS / ENVIRONMENT

centos 6.9

##### SUMMARY

when testing the ability to add a host to a hostgroup using the ipa_hostgroup module, the entire contents of the group is overwritten by the single host being added. No option to append the group is mentioned in documentation.

Documentation says `If option is passed all assigned hosts that are not passed will be unassigned from the group.` This is not desirable for creating re-usable playbooks (i.e. having to list the entire contents of a group when adding a single host)

##### STEPS TO REPRODUCE

create a playbook that uses the module, assume the host will be added to the group, along with the hosts already in the group. 

```yaml
- name: Add to main hostgroup
  ipa_hostgroup:
    name: ldap-test
    state: present
    host:
    - "{{ ansible_fqdn }}"
    hostgroup:
      - ldap-test
    ipa_host: "{{ ipa_server }}"
    ipa_user: "{{ ipa_admin }}"
    ipa_pass: "{{ ipa_pass }}"
  when: ansible_domain == "main.net"
  tags: hostgroup
```

##### EXPECTED RESULTS

The host is added to the group, and all other hosts remain untouched (and stay in the group)

##### ACTUAL RESULTS

the host is added, and all other hosts are removed.

```
TASK [Add to main hostgroup]
****************************************************************************************************
changed: [ldap-test] => {"changed": true, "hostgroup": {"cn": ["ldap-test"], "dn": "cn=ldap-test,cn=hostgroups,cn=accounts,dc=main,dc=net", "ipauniqueid": ["truncated"], "member_host": ["ldap-test.main.net"], "mepmanagedentry": ["cn=ldap-test,cn=ng,cn=alt,dc=main,dc=net"], "objectclass": ["ipaobject", "mepOriginEntry", "top", "ipahostgroup", "groupOfNames", "nestedGroup"]}}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/identity/ipa/ipa_hostgroup.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/identity/ipa/ipa_hostgroup.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Nosmoht @akasurde
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by krispayne** [comment]
This may be a feature request, depending on point of view.

**Comment by Akasurde** [comment]
@krispayne Thanks for reporting this issue. `ipa_hostgroup` adds and removes hosts from hostgroup but module does it by creating diff of existing hosts and user provided hosts. So maybe providing list of all host will change results. 

```
# ipa hostgroup-show samplegrp
  Host-group: samplegrp
  Member hosts: sample1.ipa.text
# cat ipahostgrp.yml
---
- name: Hostgroup
  hosts: localhost
  tasks:
    - name: ipa add host in hostgroup
      ipa_hostgroup:
        ipa_pass: Secret123
        ipa_host: master.ipa.test
        ipa_user: admin
        validate_certs: false
        name: samplegrp
        host:
        - sample1.ipa.text
        - sample.ipa.text
        state: present
# ansible-playbook ipahostgrp.yml -v
Using /root/ansible_playbook/ansible.cfg as config file

PLAY [Hostgroup] ***************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************
ok: [localhost]

TASK [ipa add host in hostgroup] ***********************************************************************************************
changed: [localhost] => {"changed": true, "hostgroup": {"cn": ["samplegrp"], "dn": "cn=samplegrp,cn=hostgroups,cn=accounts,dc=testrelm,dc=test", "ipauniqueid": ["30047842-2bb5-11e8-9f55-0800278c2fc4"], "member_host": ["sample1.ipa.text", "sample.ipa.text"], "mepmanagedentry": ["cn=samplegrp,cn=ng,cn=alt,dc=testrelm,dc=test"], "objectclass": ["ipaobject", "ipahostgroup", "nestedGroup", "groupOfNames", "top", "mepOriginEntry"]}}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0

# ipa hostgroup-show samplegrp
  Host-group: samplegrp
  Member hosts: sample1.ipa.text, sample.ipa.text
```

I agree that there should be a module to provide facts about IPA hostgroup members which can be consumed by `ipa_hostgroup` module.
