### ISSUE TITLE
Ignore the -l(--limit) in the play

### ISSUE THREAD

**Issue by chenzhiwei** [ansible/ansible#37633]
## ISSUE TYPE

 - Feature Idea

## ANSIBLE VERSION

```
2.3.0.0
```

## COMPONENT NAME

group_by

## SUMMARY

I'm trying to use dynamic host groups, if one host group does not exist then use default host group instead, such as:

```
- name: Deploying custom package
  host: master|default('default')
```

If there is no `master` group in inventory file, then use `default` group instead. But this does not work.

<hr>

My currently implementation is:

```
- name: Ad-hoc group
  hosts: default
  gather_facts: false

  tasks:
    - group_by: key=master
      when: ('master' not in groups.keys)
```

This play will dynamically create the `master` group. But when using `-l` in the command line, this play will not be executed.

<hr>

So I want to ask, is there another way to implement this? Thanks.
