### ISSUE TITLE
have the ios_interface module include CDP when checking neighbors

### ISSUE THREAD

**Issue by orgito** [ansible/ansible#37655]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
ios_interface

##### ANSIBLE VERSION
```
ansible 2.6
```

##### SUMMARY

Currently `ios_interface` only check for neighbors using the LLDP protocol. Many environments only have the CDP protocol enabled. 

The suggestion is to also include CDP neighbors when cheking neighbors intent. It could be done with a different option if you think is more appropriate. IMO using both protocols would be simpler.
 

##### STEPS TO REPRODUCE
Run a simple playbook using neighbors intent parameters
```
- name: Check neighbors intent arguments
  ios_interface:
    name: Gi0/0
    neighbors:
    - port: eth0
      host: netdev
```

##### EXPECTED RESULTS
Should check CDP and LLDP neighbors

##### ACTUAL RESULTS
Only checks LLDP neighbors
