### ISSUE TITLE
jenkins_plugin silently converts list of plugins to string

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#37705]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME
jenkins_plugin

##### ANSIBLE VERSION

```
ansible 2.6.0
ansible 2.5.0
ansible 2.4.3
```

##### OS / ENVIRONMENT
N/A
##### SUMMARY
It seems that jenkins_plugin is not able to load list of plugins from variables and fails to install plugins because it converts the list to a string which is evaluated as a plugin name.

##### STEPS TO REPRODUCE

```yaml
- jenkins_plugin:
  name: "{{ my_list }}"
- jenkins_plugin:
  name:
  - foo
  - bar
- jenkins_plugin:
  name: "{{ item }}"
  with_items:
  - foo
  - bar
```

Please note that with_items workaround works but is not equal, is at least 10x slower than passing the list of plugins to the plugin directly. Is not uncommon to have over 100 plugins on Jenkins.

I tested and with 123 plugins, it took more than **7 minutes** just to check that there were installed when using with_items. Same operation done without with_items took 5-10 seconds.

##### EXPECTED RESULTS
Fails to install plugin

##### ACTUAL RESULTS
Be able to install plugins from list.
