### ISSUE TITLE
jenkins_plugin with state=present fails to install plugin and reports success all times

### ISSUE THREAD

**Issue by ssbarnea** [ansible/ansible#37704]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
jenkins_plugin

##### ANSIBLE VERSION
```
ansible 2.4.3.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It seems that jenkins_plugin does nothing but reports any plugin as installed, even if the plugin name is bogus.

This happens only when user uses `state: present`, once you change `state: latest` it seems to try to do the right thing.

##### STEPS TO REPRODUCE

```yaml
- name: "install jenkins plugins"
      jenkins_plugin:
        name: xxx-that-does-not-exists
        state: latest
        url: "{{ jenkins_url }}"
        url_username: "{{ jenkins_username | default('admin') }}"
        url_password: "{{ jenkins_password | default(omit) }}"
```

##### EXPECTED RESULTS

```
FAILED! => {
    "changed": false,
    "details": "HTTP Error 404: Not Found"
}
```
##### ACTUAL RESULTS

```
changed: [j.sbarnea.com] => {
    "changed": true,
    "plugin": "xxx-that-does-not-exists",
    "state": "present"
}
```
