### ISSUE TITLE
vault strings cannot contain jinja templating

### ISSUE THREAD

**Issue by Jean-Daniel** [ansible/ansible#37710]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vault

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = ['~/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = …/lib/python3.5/site-packages/ansible
  executable location = …/bin/ansible
  python version = 3.5.5 (default, Feb  5 2018, 07:16:23) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

encrypted vault variables does not behave like standard variable when they contains templates pattern.

When a variable contains a template pattern '{{ other_var }}', ansible automatically expands the nested var.
When an encrypted variable contains such construct, ansible don't expand it when needed. 

For instance, if you have a variable `foo` that contains "{{ ansible_host }}", wherever you use foo, it will be replace by the `ansible_host` value.

If you now encrypt `foo` and store it as a vault string, ansible will not expand the variable content, and wherever you use it, it will output `{{ ansible_host }}` literally instead of the `ansible_host` value.

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: False
  vars:
    ansible_host: localhost
    key1: '{{ansible_host|upper}}'
    key2: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61663562343234643761616637613864666262383739343961396462636137323061646564623762
          3739303130663934616332343463343463636237646535370a383739623461656537646332303362
          32373164643337663137326634313263386434366234376162323331643435613765303736396164
          3832306131613239300a346366356166316366326662383764386561363330356333303833663262
          33303764303738346330313665313763393436656462373261616431386262383561
  tasks:
    - debug:
        msg: 'value of key1 => {{ key1 }}'
    - debug:
        msg: 'value of key2 => {{ key2 }}'
```

key1 and key2 contains the very same value.

Run the playbook using password foo to decrypt the content:

`ansible-playbook vaultstr.yml --vault-id=prompt`

##### EXPECTED RESULTS

```
PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "value of key1 => LOCALHOST"
}

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "value of key2 => LOCALHOST"
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0 
```

##### ACTUAL RESULTS

```
PLAY [localhost] ***********************************************************************************************************************************************************************************************************************************************************************

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "value of key1 => LOCALHOST"
}

TASK [debug] ***************************************************************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "value of key2 => {{ansible_host|upper}}"
}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0   
```
