### ISSUE TITLE
Possibility to create Internal Loadbalancers with azure_rm_loadbalancer

### ISSUE THREAD

**Issue by zwindler** [ansible/ansible#37731]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_loadbalancer

##### ANSIBLE VERSION
```
ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dgermain/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
#empty return
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
In azure console, you can create type "Public" loadbalancers with a public IP or type "Interal" loadbalancers using private IP address generated within a virtual network/subnet pair.

##### STEPS TO REPRODUCE
As far as I can tell, you don't have this "type" option in the ansible module

##### EXPECTED RESULTS
Have an option (or another module if the code is too much different) to allow internal loadbalancer creation

##### ACTUAL RESULTS
No option to do so

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_loadbalancer.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_loadbalancer.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @tstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
@zwindler You are right, for now, load balancer can be only created with public ip. I will add this feature request in my backlog. But looking into the SDK interface, I will modify the ansible parameter as following, you can find different in the `frontend_ip_configurations` field

Public IP version
```yml
azure_rm_loadbalancer:
        resource_group: yuwzhorg
        name: lbtestfromansible
        frontend_ip_configurations:
          - name: frontendipconf0
            public_ip_address: ansiblepip3
        backend_address_pools:
          - name: backendaddrpool0
        probes:
          - name: prob0
            port: 80
        inbound_nat_pools:
          - name: inboundnatpool0
            frontend_ip_configuration_name: frontendipconf0
            protocol: Tcp
            frontend_port_range_start: 80
            frontend_port_range_end: 81
            backend_port: 8080
        load_balancing_rules:
          - name: lbrbalancingrule0
            frontend_ip_configuration: frontendipconf0
            backend_address_pool: backendaddrpool0
            frontend_port: 80
            backend_port: 80
            probe: prob0
```

Private IP version
```yml
azure_rm_loadbalancer:
        resource_group: yuwzhorg
        name: lbtestfromansible
        frontend_ip_configurations:
          - name: frontendipconf0
            subnet: subnetid
            private_ip_address: 192.168.0.3
            private_ip_allocation_method: Static
        backend_address_pools:
          - name: backendaddrpool0
        probes:
          - name: prob0
            port: 80
        inbound_nat_pools:
          - name: inboundnatpool0
            frontend_ip_configuration_name: frontendipconf0
            protocol: Tcp
            frontend_port_range_start: 80
            frontend_port_range_end: 81
            backend_port: 8080
        load_balancing_rules:
          - name: lbrbalancingrule0
            frontend_ip_configuration: frontendipconf0
            backend_address_pool: backendaddrpool0
            frontend_port: 80
            backend_port: 80
            probe: prob0
```
