### ISSUE TITLE
Support multiple keys for ssh_public_key in azure_rm_virtualmachine

### ISSUE THREAD

**Issue by henti** [ansible/ansible#37738]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /home/henti/src/ansible/ansible.cfg
  configured module search path = [u'/home/henti/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_FORKS(/home/henti/src/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/home/henti/src/ansible/ansible.cfg) = [u'/home/henti/src/ansible/inventory.d']
DEFAULT_JINJA2_EXTENSIONS(/home/henti/src/ansible/ansible.cfg) = jinja2.ext.do
DEFAULT_LOG_PATH(/home/henti/src/ansible/ansible.cfg) = /home/henti/logs/ansible.log
DEFAULT_MANAGED_STR(/home/henti/src/ansible/ansible.cfg) = Ansible managed
DEFAULT_ROLES_PATH(/home/henti/src/ansible/ansible.cfg) = [u'/home/henti/src/ansible/roles', u'/home/henti/src/ansible/ext_repos/lgtm-ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/henti/src/ansible/ansible.cfg) = /home/henti/src/ansible/scripts/get_vault_password.sh
INVENTORY_IGNORE_EXTS(/home/henti/src/ansible/ansible.cfg) = ['.ini']
```

##### OS / ENVIRONMENT
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18.3
DISTRIB_CODENAME=sylvia
DISTRIB_DESCRIPTION="Linux Mint 18.3 Sylvia"
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial
```
##### SUMMARY
Busy creating ansible playbooks to create a new linux VM in azure. Tested using ssh_public_key and key_data with var `key_data: "{{ lookup('file', 'ssh_keys/henti-henti-rsa') }}"` works as expected, however we have a team of admin that will be deploying machines to I attempted to add multiple keys using a var
```
    key_data: |
      {{ lookup('file', 'ssh_keys/dom-desktop-rsa') }}
      {{ lookup('file', 'ssh_keys/henti-desktop-rsa') }}
```
The VM is created, but only the first valid key is added to authorized_keys, so only Dom can log into the server, Any additional users cannot. 

##### STEPS TO REPRODUCE
create VM with multiple ssh keys

```yaml
- name: Create Linux image
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    key_data: |
      {{ lookup('file', 'ssh_keys/dom-desktop-rsa') }}
      {{ lookup('file', 'ssh_keys/henti-desktop-rsa') }}
  vars_files: 
    - vars/azure-resources.yml
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{resourcegroups.name}}"
      allocation_method: Dynamic
      name: "lin-ip-{{ ansible_date_time.date }}"
      domain_name_label: az-lin-img-01
  - name: Create virtual network inteface card
    azure_rm_networkinterface:
      resource_group: "{{resourcegroups.name}}"
      name: "lin-nic-{{ ansible_date_time.date }}"
      virtual_network: "{{virtualnetworks.name}}"
      subnet: "{{virtualsubnets.name}}"
      public_ip_name: "lin-ip-{{ ansible_date_time.date }}"
      security_group: "{{securitygroups.name}}"
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{resourcegroups.name}}"
      name: "lin-vm-{{ ansible_date_time.date }}"
      vm_size: Standard_F8s_v2
      admin_username: semmle
      ssh_password_enabled: false
      ssh_public_keys: 
        - path: /home/semmle/.ssh/authorized_keys
          key_data: "{{ key_data }}"
      network_interfaces: "lin-nic-{{ ansible_date_time.date }}"
      image:
        offer: Debian
        publisher: credativ
        sku: '9'
        version: latest
```

##### EXPECTED RESULTS
```
TASK [CreateVM]**************************************************************************************************
ok: [localhost]
henti@henti:~$ ssh azure-test-vm
henti@azure-test-vm:~$ 
```

##### ACTUAL RESULTS
```
TASK [CreateVM]**************************************************************************************************
ok: [localhost]
henti@henti:~$ ssh azure-test-vm
Permission denied (publickey).
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@hentisemmle I ran your YML , meet same question, I not sure when create VM to set more than one public key to login this VM , I need confirm it. Thanks!
@yuwzho Could you help confirm it, I don't find any way to support it in ansible2.5 document. , I am not sure it is a question or not, Thanks !

**Comment by henti** [comment]
Can somebody confirm that this is behaviour is expected or not. Is there is way to add multiple ssk keys to azure_rm_virtualmachine?

**Comment by yuwzho** [comment]
notabug

Hi @hentisemmle , write the `ssh_public_keys` as a list of dict, which contains the `authorized_keys` path and the `key_data` will solve your problem.

```yml
ssh_public_keys: 
        - path: /home/semmle/.ssh/authorized_keys
          key_data: "{{ lookup('file', 'ssh_keys/dom-desktop-rsa') }}"
        - path: /home/semmle/.ssh/authorized_keys
          key_data: "{{ lookup('file', 'ssh_keys/henti-desktop-rsa') }}"
```
