### ISSUE TITLE
with_file doesn't check relative to playbook when using a role

### ISSUE THREAD

**Issue by lorin** [ansible/ansible#3774]
When using `with_file` with a relative path inside of a role, e.g.:

```
 - name: add key
   authorized_key: "user=lorin key={{ item }}"
   with_file:
    - keys/lorin.pub

```

ansible won't look relative to the playbook, only relative to the role. So, if I have a playbook at `/Users/lorin/ansible-playbooks/test.yaml` and a public key file at `/Users/lorin/ansible-playbooks/keys/lorin.pub`

Running `ansible-playbook test.yaml` gives me:

```
TASK: [add key] ************************************************************
fatal: [localhost] => /Users/lorin/ansible-playbooks/roles/myrole/tasks/keys/lorin.pub does not exist
```

On the other hand, if I specify that task outside of a role, it works fine.
