### ISSUE TITLE
ERROR! 'telnet' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by vickman2006** [ansible/ansible#37744]
[ansible.log](https://github.com/ansible/ansible/files/1834753/ansible.log)

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

**Telnet Module**
 telnet - Executes a low-down and dirty telnet command

##### ANSIBLE VERSION

```

ansible 2.4.3.0
  config file = /home/eve/ansible/ansible.cfg
  configured module search path = [u'/home/eve/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
eve@ubuntu-server:~/ansible$


```

##### CONFIGURATION

**cat ansible.cfg**
[defaults]
inventory = ./hosts
host_key_checking = false
timeout = 10
log_path=./ansible.log
eve@ubuntu-server:~/ansible$

**cat hosts**
[telnet_hosts]
192.168.174.154

##### OS / ENVIRONMENT

uname -a
Linux ubuntu-server 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

Trying to connect to cisco IOS device through telnet. There is no option to switch to ssh connection (we have about 200 devices with telnet)

When trying to run the playbook on 

[http://docs.ansible.com/ansible/2.4/telnet_module.html](http://docs.ansible.com/ansible/2.4/telnet_module.html)

It sends an error.

##### STEPS TO REPRODUCE

```yaml
**cat dirty-telnet.yml**
---
- name: run show commands
  hosts: telnet_hosts
  telnet:
    user: cisco
    password: cisco
    login_prompt: "Username: "
    prompts:
      - "[>|#]"
    command:
      - terminal length 0
      - show version

```

##### EXPECTED RESULTS

To establish a telnet connection and return show version command output

##### ACTUAL RESULTS

```
eve@ubuntu-server:~/ansible$ ansible-playbook dirty-telnet.yml -vvvv
ansible-playbook 2.4.3.0
  config file = /home/eve/ansible/ansible.cfg
  configured module search path = [u'/home/eve/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /home/eve/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/eve/ansible/hosts inventory source with ini plugin
ERROR! 'telnet' is not a valid attribute for a Play

The error appears to have been in '/home/eve/ansible/dirty-telnet.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: run show commands
  ^ here

eve@ubuntu-server:~/ansible$
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/commands/command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/command.py)
* [lib/ansible/modules/commands/telnet.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/commands/telnet.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case it seems you just have a incorrectly constructed play:

```
- name: run show commands
  hosts: telnet_hosts
  gather_facts: False
  tasks:
    - telnet:
        user: cisco
        password: cisco
        login_prompt: "Username: "
        prompts:
          - "[>|#]"
        command:
          - terminal length 0
          - show version
```
Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
