### ISSUE TITLE
parse_cli does not render nested items

### ISSUE THREAD

**Issue by atnoslen** [ansible/ansible#37755]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

parse_cli
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/home/anelson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/anelson/virtualenv/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/anelson/virtualenv/ansible/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

##### OS / ENVIRONMENT

Windows 10 WSL

##### SUMMARY

When using a nested dictionary as a values with parse_cli, sub items are not rendered.

##### STEPS TO REPRODUCE

parser.yml
```yaml
---
vars:
  neighbor:
    key: "{{ item.neighbor_id }}"
    values:
      id: "{{ item.neighbor_id }}"
      messages:
        received: "{{ item.msgrcvd }}"
        sent: "{{ item.msgsent }}"

keys:
  neighbors:
    type: list
    value: "{{ neighbor }}"
    items: "^(?P<neighbor_id>\\d+)\\s+(?P<msgrcvd>\\d+)\\s+(?P<msgsent>\\d+)"
```

main.yml
```yaml
---
- hosts: localhost
  vars:
    output: |
      1 2 3
      4 5 6
  tasks:
    - debug: msg={{ output | parse_cli('parser.yml') }}
```

##### EXPECTED RESULTS

```
TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "neighbors": {
            "1": {
                "id": 1,
                "messages": {
                    "received": 2,
                    "sent": 3
                }
            },
            "4": {
                "id": 4,
                "messages": {
                    "received": 5,
                    "sent": 6
                }
            }
        }
    }
}
```
##### ACTUAL RESULTS

```
TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "neighbors": {
            "1": {
                "id": 1,
                "messages": {
                    "received": "{{ item.msgrcvd }}",
                    "sent": "{{ item.msgsent }}"
                }
            },
            "4": {
                "id": 4,
                "messages": {
                    "received": "{{ item.msgrcvd }}",
                    "sent": "{{ item.msgsent }}"
                }
            }
        }
    }
}
```

```
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] ***************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [localhost]

TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "msg": {
        "neighbors": {
            "1": {
                "id": 1,
                "messages": {
                    "received": "{{ item.msgrcvd }}",
                    "sent": "{{ item.msgsent }}"
                }
            },
            "4": {
                "id": 4,
                "messages": {
                    "received": "{{ item.msgrcvd }}",
                    "sent": "{{ item.msgsent }}"
                }
            }
        }
    }
}
```
