### ISSUE TITLE
ios_config times out

### ISSUE THREAD

**Issue by haught** [ansible/ansible#37758]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True

##### OS / ENVIRONMENT

AWX 1.0.4.2

##### SUMMARY

When running ios_config with a long running before, it times out. The crypto key generate will take a long time on a switch and there doesn't appear to be a way to increase the timeout. It takes only about 15 seconds on a WS-C3560-48TS but that seems too long for ansible.

##### STEPS TO REPRODUCE

```yaml
    - name: GET SSH CONFIGURATION
      register: get_ssh_config
      ios_command:
        commands:
          - "show ip ssh"
    - name: SET SSH V2
      when: "(get_ssh_config.stdout_lines[0][0] != 'SSH Enabled - version 2.0')"
      register: set_ssh_v2
      ios_config:
        lines:
          - ip ssh version 2
        before: crypto key generate rsa general-keys modulus 2048
        timeout: 10000

```

##### EXPECTED RESULTS

The command will execute without such a short timeout and the timeout argument would actually do something

##### ACTUAL RESULTS

Playbook task timeout.

```
{
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "changed": false,
    "invocation": {
        "module_args": {
            "multiline_delimiter": "@",
            "authorize": null,
            "force": false,
            "diff_against": null,
            "replace": "line",
            "running_config": null,
            "port": null,
            "before": [
                "crypto key generate rsa general-keys modulus 2048"
            ],
            "save": false,
            "auth_pass": null,
            "parents": null,
            "provider": null,
            "save_when": "never",
            "match": "line",
            "username": null,
            "timeout": 10000,
            "after": null,
            "host": null,
            "password": null,
            "diff_ignore_lines": null,
            "src": null,
            "ssh_keyfile": null,
            "lines": [
                "ip ssh version 2"
            ],
            "intended_config": null,
            "defaults": false,
            "backup": false
        }
    },
    "command": "crypto key generate rsa general-keys modulus 2048",
    "rc": 1,
    "msg": "timeout trying to send command: crypto key generate rsa general-keys modulus 2048"
}
```
