### ISSUE TITLE
win_certificate_store does not allow certificate import from store in ansible 2.5.0rc3

### ISSUE THREAD

**Issue by flomedja** [ansible/ansible#37789]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_certificate_store
##### ANSIBLE VERSION

```
ansible 2.5.0rc3
```

##### SUMMARY

I upload a certificate in LocalMachine Store with this code : 

```
- name: Add certificate to MY store
    win_certificate_store:
      path: "certificate.pfx"
      password: "{{certificate_password}}"
      state: present
      location: LocalMachine
      store_name: 'MY'
    register: certificate_stdout
```
The certificate is effectively add in the LocalMachine\My store but when It came to bind the certificate with a site in IIS i got the following error : 

**Failed to set new SSL certificate - A specified logon session does not exist. It may already have been terminated. (Exception from HRESULT: 0x80070520).**

I Already have the same error previously and resolve it by used this approch to load the certificate : 
`Import-PfxCertificate -FilePath $pfx_file -CertStoreLocation $store_path -Password (ConvertTo-SecureString $password -AsPlainText -Force)  -Exportable `
This ensure that the certificate is exportable.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_certificate_store.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_certificate_store.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
I think the issue is that the IIS worker account is unable to see the private key that is stored by Windows. When we go to import a pfx certificate, we set the following https://msdn.microsoft.com/en-us/library/system.security.cryptography.x509certificates.x509keystorageflags.aspx?f=255&MSPPError=-2147217396 flags by default

* `DefaultKeySet`: Is controlled with `key_storage` but the default value is `default`
* `Exportable`: Is controlled by `key_exportable` but the default is `True`
* `PersistKeySet`: no way to control this but it effectively means the private key isn't lost after we loose the import handle in the module

According to those docs, `DefaultKeySet` means

> The default key set is used. The user key set is usually the default.

When the key is only accessible by the user who imported it, other accounts like the IIS worker will be unable to access that private key for their purposes. Are you able to set `key_storage: machine` to your task and see if that works, e.g.

```
- name: Add certificate to MY store
   win_certificate_store:
     path: "certificate.pfx"
     password: "{{certificate_password}}"
     state: present
     location: LocalMachine
     store_name: 'MY'
     key_storage: machine
   register: certificate_stdout
```

Thanks
