### ISSUE TITLE
template: mode doesn't set correct permissions

### ISSUE THREAD

**Issue by varunchopra** [ansible/ansible#37781]
##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /workspace/satellite/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/workspace/satellite/ansible.cfg) = [u'/workspace/satellite/inventory']
HOST_KEY_CHECKING(/workspace/satellite/ansible.cfg) = False
```

##### OS / ENVIRONMENT
RHEL 7.4

##### SUMMARY
I'm using the template module to copy templates but the permissions aren't being set properly.

##### STEPS TO REPRODUCE
```yaml
    - name: "Copy files required for a capsule."
      template:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items:
        - { src: './files/a', dest: '{{ ansible_env.HOME }}/a', mode: 0400 } # 256
        - { src: './files/b', dest: '{{ ansible_env.HOME }}/b', mode: 0644 } # 420
```

##### EXPECTED RESULTS
0400 should've set: `-r--------.`
0644 should've set: `-rw-r--r--.`

##### ACTUAL RESULTS
```
changed: [tower-01] => (item={u'dest': u'/root/a', u'src': u'./files/tower/a', u'mode': 256})
changed: [tower-01] => (item={u'dest': u'/root/capsule/b', u'src': u'./files/capsule/b', u'mode': 420})
```
