### ISSUE TITLE
ovirt_snapshots_facts module does not show nested attributes

### ISSUE THREAD

**Issue by dyasny** [ansible/ansible#37796]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ovirt_snapshots_facts

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT

CentOS 7.4, Fedora27, oVirt 4.2.1

##### SUMMARY

In order to dig into https://engine.example.com/ovirt-engine/api/vms/VMUUID/snapshots/SNAPUUID/disks I have to issue curl manually. 

I tried to use 
```yaml
      ovirt_snapshots_facts:
        auth: "{{ ovirt_auth }}"
        vm: "{{ target_vm }}"
        fetch_nested: yes
        nested_attributes:
          - disks
        description: my_snapshot
```
but got the same results

##### STEPS TO REPRODUCE

Use the code from above

##### EXPECTED RESULTS

A larger JSON output which included the disks under the snapshot

##### ACTUAL RESULTS

nothing

I have seen this on other commands that are supposed to be able to fetch_nested, but managed to work around the issue, here the only w/a I found was to run shell: curl which isn't the best solution.
