### ISSUE TITLE
win_iis_webbinding does not remove binding

### ISSUE THREAD

**Issue by flomedja** [ansible/ansible#37795]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_iis_webbinding
##### ANSIBLE VERSION

```
ansible 2.5.0rc3
```
##### OS / ENVIRONMENT

Running Ansible on ubuntu xenial 64bits and targeted a windows server core 2016 for deployment
##### SUMMARY

I Created a site in iss on port 80 with [win_iis_website](https://github.com/ansible/ansible/blob/v2.5.0rc3/lib/ansible/modules/windows/win_iis_website.ps1) :  
```
- name: Create/modify web site
  win_iis_website:
    name: "{{site_name}}"
    application_pool: "{{app_pool_name}}"
    physical_path: "{{site_install_root}}"
    state: stopped
    hostname: "{{proxy_hostname}}"
    port: "{{ http_port }}"
```
Output : 

```
changed: [windows-host1] => {
    "changed": true,
    "site": {
        "ApplicationPool": "patient-search-local",
        "Bindings": [
            "*:80:patient-search-local.logibec.com"
        ],
        "ID": 1421097937,
        "Name": "patient-search-local",
        "PhysicalPath": "C:\\inetpub\\ipo-patient-search-local",
        "State": "Stopped"
    }
}
```

and added a binding on port 443 with [win_iis_webbinding](https://github.com/ansible/ansible/blob/v2.5.0rc3/lib/ansible/modules/windows/win_iis_webbinding.ps1)  ( Because win_iis_website don't work for create a site on 443 with https directly)  : 
```
- name: Add HTTPS bindings
  win_iis_webbinding:
    name: "{{ site_name }}"
    port: "{{ https_port }}"
    host_header: "{{ proxy_hostname }}"
    protocol: "{{ protocol }}"
    certificate_hash: "{{certificate_hash }}"
  when: protocol == "https"
```

Output : 

```
changed: [windows-host1] => {
    "binding_info": {
        "bindingInformation": "*:443:patient-search-local.logibec.com",
        "certificateHash": "EBCF06C05314592EB562BC99126FF7ACE68F2B9F",
        "certificateStoreName": "MY",
        "hostheader": "patient-search-local.logibec.com",
        "ip": "*",
        "port": 443,
        "protocol": "https",
        "sslFlags": 0
    },
    "changed": true,
    "operation_type": "added",
    "website_state": "Stopped"
}
```
. After that i tried to remove my http binding like this : 

```
- name: Remove HTTP bindings
  win_iis_webbinding:
    name: "{{ site_name }}"
    port: 80
    protocol: http
    state: absent
when: protocol == "https"
```

Output : 

```
TASK [patient-search-core : Remove HTTP bindings] *************************************************************************************************************************************************************

task path: patient_search_playbook/roles/ipo-patient-search-core/tasks/web_site.yml:110
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/windows/win_iis_webbinding.ps1
<192.168.235.20> ESTABLISH WINRM CONNECTION FOR USER: vagrant on PORT 5985 TO 192.168.235.20
checking if winrm_host 192.168.235.20 is an IPv6 address
EXEC (via pipeline wrapper)
ok: [windows-host1] => {
    "changed": false
}
```

The binding is not removed. Just mention this worked in ansible 2.4. 
Thanks :)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_iis_webbinding.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_iis_webbinding.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone @nwsparks
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nwsparks** [comment]
Can you please fill out OS/Environment and output from actual results with -vvvv as it asks in the issue form?

I tested this and am unable to reproduce.

**Comment by flomedja** [comment]
@nwsparks  Sorry i add some details to the summary

**Comment by nwsparks** [comment]
Thanks. Sorry for the delay. Based on the output it looks like you're defining a host header for the default 80 binding. Can you please specify the host header when removing the binding, like below and let me know if this resolves it? The module now matches on all 3 fields, whereas previously it did not.

````
- name: Remove HTTP bindings
  win_iis_webbinding:
    name: "{{ site_name }}"
    port: 80
    protocol: http
    state: absent
    host_header: patient-search-local.logibec.com
````
