### ISSUE TITLE
Show more information in returned value of sl_vm

### ISSUE THREAD

**Issue by mmolinac** [ansible/ansible#37827]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

sl_vm

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/mmolinac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

[defaults]
allow_world_readable_tmpfiles=True
host_key_checking = False
retry_files_enabled = False
[ssh_connection]
ssh_args = -C -o ControlMaster=auto -o ControlPersist=60s
control_path_dir = /tmp/.ansible/cp

##### OS / ENVIRONMENT

Ansible running on MacOS High Sierra 10.13.3, Darwin Kernel Version 17.4.0
Managing: Debian GNU/Linux 9.3, x86_64

##### SUMMARY

The module sl_vm works well, to some extent, but I've been unable to get additional information registering the output of the actions we make it do, as I can with other cloud modules (Google or Azure for instance).

##### STEPS TO REPRODUCE

You can create a virtual machine, and check the virtual inventory with its softlayer.py script, but you can't use the return values registered with "register", because they need to be filled in by the module mentioned above.

```yaml
- name: Create Softlayer items for John Doe instances
  hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - include_vars: Commonvars.yml
    - name: Launch John Doe instances
      sl_vm:
        hostname:     host02
        domain:       domain.com
        datacenter:   "{{ sl_datacenter }}"
        dedicated:    "{{ sl_dedicated }}"
        cpus:         "{{ sl_cores }}"
        hourly:       "{{ sl_hourly }}"
        memory:       "{{ sl_memory }}"
        os_code:      "{{ sl_os_code }}"
        private:      "{{ sl_private }}"
        public_vlan:  "{{ sl_public_vlan }}"
        private_vlan: "{{ sl_private_vlan }}"
        ssh_keys:     "{{ sl_ssh_keys }}"
        disks:        "{{ sl_disks }}"
      register:         sl_bu
    - name: "Registered content"
      debug:
        msg: "Content of sl_bu: {{ sl_bu }}"
```

##### EXPECTED RESULTS

I expect something like Google cloud module returns:

(taken from gce module)
```
TASK [Registered content] ****************************************************************************************************
ok: [localhost] => {
    "msg": "Content of gce_redis: {u'instance_data': [{u'status': u'RUNNING', u'name': u'redis01', u'zone': u'europe-west1-b', u'tags': [u'redis'], u'image': u'debian-9-stretch-v20180307', u'disks': [u'redis01'], u'public_ip': u'11.22.33.44', u'network': u'default', u'private_ip': u'1.2.3.4', u'machine_type': u'g1-small', u'subnetwork': u'default', u'metadata': {}}], u'zone': u'europe-west1-b', u'instance_names': [u'redis01'], u'changed': False, 'failed': False, u'state': u'present'}"
}

```
##### ACTUAL RESULTS

As you can see, there's some returned information, but is not complete at all.

```
PLAY [Create Softlayer items for Backup instances] ***************************************************************************

TASK [include_vars] **********************************************************************************************************
ok: [localhost]

TASK [Launch Backup instances] ***********************************************************************************************
ok: [localhost]

TASK [Registered content] ****************************************************************************************************
ok: [localhost] => {
    "msg": "Content of sl_bu: {u'instance': None, u'changed': False, 'failed': False}"
}

```
