### ISSUE TITLE
Ansible 2.5 include_role - pass variables

### ISSUE THREAD

**Issue by smuthali** [ansible/ansible#37865]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
include_roles directive
#####  VERSION

```
ansible 2.5.0
  config file =<REDACTED>/ansible.cfg
  configured module search path = [u'<REDACTED>/ansible-lib/library']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

##### OS / ENVIRONMENT
```
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E190a
```

##### SUMMARY
Invoking ``` include_role```  by passing vars is completely ignored in Ansible 2.5

```
  include_role:
    name: create_dirs
  vars:
    dirs: "{{ dir_structure }}"
    dir_owner: "{{ log_owner }}"
    dir_group_owner: "{{ log_group }}"

```
