### ISSUE TITLE
openssl_certificate on Ansible 2.5 fails: 'NoneType' object has no attribute 'get_notBefore'

### ISSUE THREAD

**Issue by robertdebock** [ansible/ansible#37867]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
openssl_certificate

##### ANSIBLE VERSION
```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.4 (default, Mar 14 2018, 17:49:05) [GCC 4.9.2]
```

##### CONFIGURATION
```
ansible-config dump --only-changed
[empty]
```

##### OS / ENVIRONMENT
Multiple:
- archlinux
- alpine
- centos
- debian
- fedora
- opensuse
- ubuntu

##### SUMMARY
When using openssl_certificate in Ansible 2.5, an error occurs:
```
AttributeError: 'NoneType' object has no attribute 'get_notBefore
```

##### STEPS TO REPRODUCE
See [the code](https://github.com/robertdebock/ansible-role-httpd) and [the build](https://travis-ci.org/robertdebock/ansible-role-phpmyadmin/builds/357693716) and [the specific line](https://travis-ci.org/robertdebock/ansible-role-phpmyadmin/jobs/357693742#L1116) for details.

```
- name: create ssl key
  openssl_privatekey:
    path: "/tmp/some.key"
  register: key

- name: create ssl csr
  openssl_csr:
    path: "/tmp/some.csr"
    privatekey_path: "{{ key.filename }}"
    common_name: "{{ ansible_fqdn }}"
  register: csr

- name: create ssl certificates
  openssl_certificate:    # <<============ This is the module giving errors.
    path: "/tmp/some.crt"
    privatekey_path: "{{ csr.privatekey }}"
    csr_path: "{{ csr.filename }}"
    provider: selfsigned
```

##### EXPECTED RESULTS
Similar behaviour as Ansible 2.4.

##### ACTUAL RESULTS
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'NoneType' object has no attribute 'get_notBefore'

fatal: [phpmyadmin-ubuntu-artful]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_wTx0Xq/ansible_module_openssl_certificate.py\", line 888, in <module>\n    main()\n  File \"/tmp/ansible_wTx0Xq/ansible_module_openssl_certificate.py\", line 862, in main\n    result = certificate.dump()\n  File \"/tmp/ansible_wTx0Xq/ansible_module_openssl_certificate.py\", line 484, in dump\n    'notBefore': self.cert.get_notBefore(),\nAttributeError: 'NoneType' object has no attribute 'get_notBefore'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
