### ISSUE TITLE
Ansible 2.5: azure_rm_networkinterface strange omit behavior

### ISSUE THREAD

**Issue by IvanovOleg** [ansible/ansible#37873]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_networkinterface
##### ANSIBLE VERSION

```
2.5.0
```

##### OS / ENVIRONMENT

Centos 7
##### STEPS TO REPRODUCE

```
- name: Create a network interface
  local_action:
    module: azure_rm_networkinterface
    resource_group: "{{ resource_group_name }}"
    name: "{{ network_interface }}"
    virtual_network: "{{ virtual_network_name }}"
    subnet: "{{ network_subnet_name }}"
    security_group_name: "{{ security_group_name }}"
    ip_configurations:
      - name: enp0s0
        primary: True
        public_ip_address_name: "{{ public_ip | ternary(public_ip_name, omit) }}"
  register: nic_info

```

##### EXPECTED RESULTS

NIC has been created
##### ACTUAL RESULTS

`fatal: [k8s-agentpool1-1 -> localhost]: FAILED! => {"changed": false, "msg": "Error creating __omit_place_holder__cfb875d9f57631a0987a965ba654e3880f0f024b - Azure Error: InvalidResourceName\nMessage: Resource name __omit_place_holder__cfb875d9f57631a0987a965ba654e3880f0f024b is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'."}`

It works fine if `public_ip: True`

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by IvanovOleg** [comment]
If I remove `public_ip_address_name: "{{ public_ip | ternary(public_ip_name, omit) }}"` I get:
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: msrest.exceptions.ValidationError: Parameter 'public_ip_address_name' can not be None. ` that can be None according to the documentation.

**Comment by zikalino** [comment]
@IvanovOleg this problem should be fixed by pr#36824
could you check if that fix works for you?

**Comment by IvanovOleg** [comment]
@zikalino I will download this PR code and patch my ansible manually. I'll notify you about results.

**Comment by IvanovOleg** [comment]
@zikalino ok, I've updated  /usr/local/lib/python2.7/site-packages/ansible/modules/azure/azure_rm_networkinterface.py file with the code provided in the PR, run playbook and got the same "omit" error.

**Comment by IvanovOleg** [comment]
`public_ip_address_name: "{{ public_ip | ternary(public_ip_name, omit) }}"` doesn't work
`public_ip_address_name: "{{ public_ip | ternary(public_ip_name, '') }}"` works

**Comment by zikalino** [comment]
@IvanovOleg thanks for checking this. i will fix this addional scenario soon!

**Comment by yuwzho** [comment]
-label azure

Seems this is not an azure module error, but a playbook syntax problem.

**Comment by yuwzho** [comment]
@mattclay Do you know who is the right person should assign to?

**Comment by unfii** [comment]
For some reason module azure_rm_networkinterface again create own security group and not attach exist or seems just ignore

```
--
- name: Create a public ip address (Linux machine)
  azure_rm_publicipaddress:
    resource_group: "{{ resource_group }}"
    name: "{{ env | replace('-', '')}}tab"
    allocation_method: Static
    domain_name: "{{ env | replace('-', '')}}tab"

- name: Create network security group for machine
  azure_rm_securitygroup:
    resource_group: "{{ resource_group }}"
    name: "{{ env | replace('-', '')}}tab-nsg"
    rules:
        - name: 'AllowHTTP'
          protocol: Tcp
          source_address_prefix: '*'
          destination_port_range: 80
          access: Allow
          priority: 100
          direction: Inbound
        - name: 'AllowSSH'
          protocol: Tcp
          source_address_prefix: '*'
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound

- name: Create a network interface using existing security group and public IP
  azure_rm_networkinterface:
    name: "{{ env | replace('-', '')}}tab"
    resource_group: "{{ resource_group }}"
    virtual_network_name: "{{ env }}"
    subnet_name: "test_subnet"
    security_group_name: "{{ env | replace('-', '')}}tab-nsg"
    ip_configurations:
      - name: ipconfig1
        public_ip_name: "{{ env | replace('-', '')}}tab"
        primary: True
```
