### ISSUE TITLE
Ansible 2.5: azure_rm_networkinterface ignores security_group_name parameter

### ISSUE THREAD

**Issue by IvanovOleg** [ansible/ansible#37872]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_networkinterface

##### ANSIBLE VERSION

```
2.5.0
```

##### OS / ENVIRONMENT

Centos 7
##### SUMMARY

The azure_rm_networkinterface module ignores security_group_name parameter and creates a security group with a default name.
##### STEPS TO REPRODUCE

```
- name: Create a network interface
  local_action:
    module: azure_rm_networkinterface
    resource_group: "{{ resource_group_name }}"
    name: "{{ network_interface }}"
    virtual_network: "{{ virtual_network_name }}"
    subnet: "{{ network_subnet_name }}"
    security_group_name: "{{ security_group_name }}"
    ip_configurations:
      - name: enp0s0
        primary: True
        public_ip_address_name: "{{ public_ip | ternary(public_ip_name, omit) }}"
  register: nic_info

```

##### EXPECTED RESULTS

The azure_rm_networkinterface module accepts security_group_name parameter and uses an existing security group.
##### ACTUAL RESULTS

A security group with a default name has been created

```

```
