### ISSUE TITLE
IOS Config - \ No newline at end of file (compare running v saved config)

### ISSUE THREAD

**Issue by billyblue52** [ansible/ansible#37874]
##### ISSUE TYPE

 - Documentation Report

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### SUMMARY
no newline at the end of file, the documentation doesn't say how the master.cfg file should be formatted. 

##### STEPS TO REPRODUCE

```yaml

```

**Comment by alikins** [comment]
@billyblue52 Could you elaborate? I'm not sure what this refers to.

> no newline at the end of file

Which file?

> the documentation doesn't say how the master.cfg file should be formatted.

Are you referring to the docs at https://docs.ansible.com/ansible/2.4/ios_config_module.html ? 
In particular, the example in the Examples section:

```
- name: check the running-config against master config
  ios_config:
    diff_config: intended
    intended_config: "{{ lookup('file', 'master.cfg') }}"
```
