### ISSUE TITLE
win_dsc in Ansible 2.5.0 breaks in certain situations

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#37882]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_Dsc
##### ANSIBLE VERSION
```
2.5.0
```

##### SUMMARY
During upgrade testing I noticed that win_dsc in Ansible 2.5.0 fails with the following message in some situations:
`Failed to serialize properties into CimInstance`. This is not the case when running a legacy (the originally merged) version.

##### STEPS TO REPRODUCE
Create a win_dsc task with the following params:
```
  dsc_attributes:
    AutoStart: true
    Enable32BitAppOnWin64: false
    IdentityType: ApplicationPoolIdentity
    IdleTimeout: 00:00:00
    ManagedPipelineMode: Integrated
    ManagedRuntimeVersion: v4.0
    Name: Api
    RestartSchedule: null
    RestartTimeLimit: 00:00:00
  module_version: 1.19.0.0
  reboot_required: null
  resource_name: xWebAppPool
```
##### EXPECTED RESULTS
This works fine on older win_dsc versions (tho I'm not sure about the exact version I've been running on), but fails on Ansible 2.5.0

##### ACTUAL RESULTS
See error above

**Comment by trondhindenes** [comment]
Here's the exact task for testing:
```
  - name: "Create app-pool using DSC for MyAppPool using using defined username"
    win_dsc:
      resource_name: xWebAppPool
      Name: MyAppPool
      AutoStart: yes
      ManagedPipelineMode: Integrated
      ManagedRuntimeVersion: v4.0
      IdentityType: ApplicationPoolIdentity
      Enable32BitAppOnWin64: no
      RestartSchedule: null
      IdleTimeout: "00:00:00"  # overriding "00:20:00"
      RestartTimeLimit: "00:00:00"
```

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
We did change how CimInstance properties are marshaled from before for a few reasons;

* The previous state used some custom string format where you continued to define the CimInstance as you would in DSC and not as a plain dict which was more Ansible like
* We couldn't find any examples of it in action apart from the original PR that added it in your original repo
* We decided native list/dicts were a lot easier to define and show as an example, because the module was community and preview we decided not to try and keep support for the previous version

In saying that I have briefly looked at the `xWebAppPool` resource and can't find where this is happening and we should definitely improve the error message. I'll look into this further on Monday, thanks for the bug report.

**Comment by trondhindenes** [comment]
Gotcha, thanks. Gut feeling is that the problem is in one of the "time" attributes, as the rest is essentially simple strings and bools. I'll have a closer look at it too.

**Comment by jborean93** [comment]
The issue is actually the `RestartScheduled` being `null`, looking at the code right now there is no extra handling when the value is null https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_dsc.ps1#L243 compared to before where it would try and cast the value to the type even if it were null. We could remove the special case for `$null` handling here and just try and cast it to the type but I have 2 concerns;

* It would probably cause issues down the track when trying to cast `$null` to a string or int, what is the value we want, `$null` or `"null"` and so on
* It works for things like arrays as it just adds `$null` to the array that has 1 entry
* If a user wanted `$null` then they probably really wanted to omit the entry in their yaml definition so the value isn't actually passed along to the DSC invocation

I'm happy to be persuaded otherwise as that last point can make it go either way but would like to hear from some others before making the change.

As for a better error message, I don't see a better way out, The exception that is thrown by `Invoke-DscResource` didn't contain any more info any it as a plain exception looks like

```
Failed to serialize properties into CimInstance.
At C:\temp\win_dsc.ps1:276 char:19
+ ... estResult = Invoke-DscResource @Config -Method Test -ModuleName $Modu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Invoke-DscResource], SerializationException
    + FullyQualifiedErrorId : System.Runtime.Serialization.SerializationException,Microsoft.PowerShell.DesiredStateConfiguration.Commands.InvokeDscResourceMethodCommand
```

Because the exception itself didn't tell us what field failed to serialise, I'm not sure what else we can do there.

**Comment by trondhindenes** [comment]
Thanks, 
As far as error messages go, I would argue that we should spit the "parsed" parameters back out (this seems to have been removed, as I'm pretty sure it was in the first version) - maybe only in "vv" mode (are powershell modules able to pick up the verbosity from one of the "internal" params?)

**Comment by trondhindenes** [comment]
Regarding parsing null: Hm, thinking out loud.
If we have a dsc resource that takes a param "name", which can be "string" but defaults to `$null` (controlled internally by the dsc resource). Imho we need to send in that. The alternative is to have to use set_fact / dict joining in the playbook prior to calling the dsc resource in order to build up a dynamic object which is then passed down to the resource, which I at least want to avoid as much as possible. Which is why I'm thinking that we should pass "null" values on to the underlying resource. `null` in the yaml spec means `None` (py) / `$null` (ps) so imho they map perfectly fine.

Example:
```
role: stuff
defaults/main.yml:
firstname: null

tasks/main.yml:
- name: doit
  win_dsc:
    resource_name: thestuff
    FirstName "{{ firstname }}"
```
if we require custom logic to do "null checks" prior to calling win_dsc then roles likes these suddenly become 3x their original size because of all the handling logic.

**Comment by jborean93** [comment]
> I would argue that we should spit the "parsed" parameters back out (this seems to have been removed, as I'm pretty sure it was in the first version)

We are trying to move away from returning values that are passed into the module from Ansible (within the module itself), there is an outstanding issue to return the method invocation args when running with `-vvv` but that's been pushed back for a few different reasons. Returning the "dsc parsed" values may be something we want to add back in but I'm not sure how well the `ConvertTo-Json` cmdlet works with complex args like `CimInstance`. I'll bring this up at the next WWG to talk about because I can see the value when it comes to debugging but TBH the value is limited.

> If we have a dsc resource that takes a param "name", which can be "string" but defaults to $null (controlled internally by the dsc resource). Imho we need to send in that.

You can do that right now, if the value takes in null and we pass in `null`, the property being set with `Invoke-DscResource` is actually `$null`. In the win_dsc5 iteration, there was some code to convert `$null` to `[$null]` for `string[]` properties which IMO is not the same. If someone want's that, they can either set an empy list or a list with `null` as the only value like so;

```
- win_dsc:
    resource_name: dscResource
    Example1: []  # in powershell this is @()
    Example2:  # in powershell this is @($null) and is what win_dsc5 did for Example2: null
    - null
    Example3: null  # in powershell this is $null
```

The issue you have is in the old logic, xWebAppPool saw `@($null)` as a valid value for `RestartSchedule` and when win_dsc5 parsed `null`, it parsed it as `@($null)` which is not the same.

> The alternative is to have to use set_fact / dict joining in the playbook prior to calling the dsc resource in order to build up a dynamic object which is then passed down to the resource

If someone wants to dynamically build parameters and conditionally send them through to the module, the`omit` value with the `default` filter should be used like so;

```
- win_dsc:
    resource_name: dscResource
    Name: '{{ resource_name|default(omit) }}`
```

What happens there is `Name` would be set to `resource_name` value if that variable is defined, if it isn't then Ansible will not send anything for `Name` making sure DSC uses the default value.

> Which is why I'm thinking that we should pass "null" values on to the underlying resource. null in the yaml spec means None (py) / $null (ps) so imho they map perfectly fine.

That's what is happening right now, `null` is being passed as `$null` to the module and `Invoke-DscResource` is not able to handle this for the `RestartSchedule` attribute.
