### ISSUE TITLE
bogus ec2 warning in Ansible 2.5.0

### ISSUE THREAD

**Issue by n267** [ansible/ansible#37895]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
ec2 module

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### CONFIGURATION

ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 7
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 300

##### OS / ENVIRONMENT

Ubuntu 16.04.4 LTS

##### SUMMARY

ec2 module (http://docs.ansible.com/ansible/latest/ec2_module.html) is showing the following warning:

 [WARNING]: Unable to modify public ip assignment to False for instance i-xxxxxxxx. Whether or not to assign a public IP is determined during instance creation.

assign_public_ip parameter was not specified, so this warning should not be showing. The warning did not show prior to Ansible 2.5.0.

##### STEPS TO REPRODUCE

ec2 is called twice in my situation. First to create the instance, and then later to trigger a reboot.

```yaml
  ec2:
    instance_tags:
      Name:           xxxxxx
    aws_access_key:   xxxxxx
    aws_secret_key:   xxxxxx
    region:           xxxxxx
    instance_type:    xxxxxx
    image:            xxxxxx
    wait:             yes
    key_name:         xxxxxx
    network_interface: [xxxxxx, xxxxxx, xxxxxx]

.....

  ec2:
    aws_access_key:   xxxxxx
    aws_secret_key:   xxxxxx
    region:           xxxxxx
    instance_ids:     xxxxxx
    wait:             yes
    state:            restarted


```

##### EXPECTED RESULTS

No warnings, errors, etc.

##### ACTUAL RESULTS

This warning is displayed:

 [WARNING]: Unable to modify public ip assignment to False for instance i-xxxxxxxx. Whether or not to assign a public IP is determined during instance creation.

```

```
