### ISSUE TITLE
pip module broken

### ISSUE THREAD

**Issue by tonal** [ansible/ansible#37912]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pip

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/user/projects/remains/deploy/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
[defaults]
inventory = deploy_hosts.lst
callback_plugins = /home/user/lib/ansible/callback_plugins
pipelining = True
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Error for upgrade pip in remote python virtual environment

##### STEPS TO REPRODUCE

 1. Configure public key access to the remote server
 2. Create remote virtual environment by pyenv
 3. Link virtual environment to project subdir `venv`
 3. run ansible playbook for upgrade pip
```
$ ansible-playbook upgrade_pip.yaml
```

```yaml
- name: Pip upgrade test
  hosts: all
  vars:
    proj_name: pip_upgrade_test
    proj_dir: '/opt/{{ proj_name }}'
  tasks:
  - name: Pip upgrade pip
    pip:
      chdir: '{{ proj_dir }}'
      executable: '{{ proj_dir }}/venv/bin/pip3'
      state: latest
      name: pip
```

##### EXPECTED RESULTS

```
TASK [Pip upgrade pip] ********************************************************************************
ok: [test_host]
```
##### ACTUAL RESULTS

```
TASK [Pip upgrade pip] ********************************************************************************
fatal: [test_host]: FAILED! => {"changed": false, "module_stderr": "Shared connection to test_host.com closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_rXLLtA/ansible_module_pip.py\", line 562, in <module>\r\n    main()\r\n  File \"/tmp/ansible_rXLLtA/ansible_module_pip.py\", line 387, in main\r\n    env = os.path.join(chdir, env)\r\n  File \"/usr/lib/python2.7/posixpath.py\", line 75, in join\r\n    if b.startswith('/'):\r\nAttributeError: 'NoneType' object has no attribute 'startswith'\r\n", "msg": "MODULE FAILURE", "rc": 1}
```
