### ISSUE TITLE
Ansible 2.5.0 - create encrypted efs share fails

### ISSUE THREAD

**Issue by ReinerNippes** [ansible/ansible#37924]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

efs module
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/centos/sap4cloud/ansible.cfg
  configured module search path = [u'/home/centos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

CentOS7
##### SUMMARY

Try to create a crypted efs share fails.

##### STEPS TO REPRODUCE

Use the module "efs" 

```yaml
  - name: create (if needed) efs
    efs:
      name: "{{ item.key }}"
      state: "{{ item.value.state }}"
      tags: "{{ item.value.tags }}"
      encrypt: true
      kms_key_id: arn:aws:kms:eu-central-1:<account-id>:key/<cmk key id>
      region: "{{ region }}"
      targets:
        - subnet_id: "{{ subnet_ids[0] }}"
          security_groups: "{{ item.value.security_groups }}"
        - subnet_id: "{{ subnet_ids[1] }}"
          security_groups: "{{ item.value.security_groups }}"
    with_dict: "{{ efs_list }}"
    register: efs

```

##### EXPECTED RESULTS

A crypted efs share.
##### ACTUAL RESULTS

The task fails.

```
    "exception": "Traceback (most recent call last):
  File \"/tmp/ansible_N2H1Cs/ansible_module_efs.py\", line 379, in create_file_system
    self.connection.create_file_system(**params)
  File \"/usr/lib/python2.7/site-packages/botocore/client.py\", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File \"/usr/lib/python2.7/site-packages/botocore/client.py\", line 575, in _make_api_call
    api_params, operation_model, context=request_context)
  File \"/usr/lib/python2.7/site-packages/botocore/client.py\", line 630, in _convert_to_request_dict
    api_params, operation_model)
  File \"/usr/lib/python2.7/site-packages/botocore/validate.py\", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Unknown parameter in input: \"Encrypted\", must be one of: CreationToken, PerformanceMode
Unknown parameter in input: \"KmsKeyId\", must be one of: CreationToken, PerformanceMode
", 
```
