### ISSUE TITLE
azure_rm_storageaccount doesn't show or allow showing connectionstring

### ISSUE THREAD

**Issue by kwoodson** [ansible/ansible#37934]
##### ISSUE TYPE
 - Bug Report
 - Feature Idea

##### COMPONENT NAME
azure_rm_storageaccount_facts

##### ANSIBLE VERSION
```
ansible 2.5.0rc1 (stable-2.5 fccb6962fe) last updated 2018/03/06 09:55:16 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kwoodson/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kwoodson/git/ansible/lib/ansible
  executable location = /home/kwoodson/git/ansible/bin/ansible
  python version = 2.7.14 (default, Dec 11 2017, 16:08:01) [GCC 7.2.1 20170915 (Red Hat 7.2.1-2)]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
$
```

##### OS / ENVIRONMENT
fedora 26

##### SUMMARY
I want to fetch the storageaccount connection string by querying the storage account.  This can be accomplished by running the following command from the python client:

```
az storage account show-connection-string --name <storage account name> --resource-group <resource group name> --output=json
```

##### STEPS TO REPRODUCE

```yaml
- name: fetch connection string for storage account
  azure_rm_storageaccount_facts:
    resource_group: "{{ openshift_azure_resource_group_name }}"
    name: "{{ openshift_azure_storage_account_name }}"
  register: storageout

- debug: var=storageout
```

##### EXPECTED RESULTS
I expected to see the connection string for this storage account.

##### ACTUAL RESULTS
```yaml
    "storageout": {
        "ansible_facts": {
            "azure_storageaccounts": [
                {
                    "id": "/subscriptions/<subscription id>/resourceGroups/<resource group name>/providers/Microsoft.Storage/storageAccounts/<storage account name>", 
                    "kind": "Storage", 
                    "location": "eastus", 
                    "name": "<storage account name>", 
                    "properties": {
                        "creationTime": "2018-03-05T22:07:04.601348Z", 
                        "encryption": {
                            "keySource": "Microsoft.Storage", 
                            "services": {
                                "blob": {
                                    "enabled": true, 
                                    "lastEnabledTime": "2018-03-05T22:07:04.632542Z"
                                }, 
                                "file": {
                                    "enabled": true, 
                                    "lastEnabledTime": "2018-03-05T22:07:04.632542Z"
                                }
                            }
                        }, 
                        "networkAcls": {
                            "bypass": "AzureServices", 
                            "defaultAction": "Allow", 
                            "ipRules": [], 
                            "virtualNetworkRules": []
                        }, 
                        "primaryEndpoints": {
                            "blob": "https://<storageaccountname>.blob.core.windows.net/", 
                            "file": "https://<storageaccountname>.file.core.windows.net/", 
                            "queue": "https://<storageaccountname>.queue.core.windows.net/", 
                            "table": "https://<storageaccountname>.table.core.windows.net/"
                        }, 
                        "primaryLocation": "eastus", 
                        "provisioningState": "Succeeded", 
                        "statusOfPrimary": "available", 
                        "supportsHttpsTrafficOnly": false
                    }, 
                    "sku": {
                        "name": "Standard_LRS", 
                        "tier": "Standard"
                    }, 
                    "tags": {}, 
                    "type": "Microsoft.Storage/storageAccounts"
                }
            ]
        }, 
        "changed": false, 
        "failed": false
    }
}
```

The connection string is missing.
