### ISSUE TITLE
NIOS:  View Not Found

### ISSUE THREAD

**Issue by realged13** [ansible/ansible#37949]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nios

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/e116173@xyz.com/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/e116173@xyz.com/venv/infoblox-test/lib/python2.7/site-packages/ansible
  executable location = /home/e116173@xyz.com/venv/infoblox-test/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

[all:vars]
ansible_python_interpreter=python

##### OS / ENVIRONMENT

Centos 7

##### SUMMARY

Trying to create a host dns record in the default view.  Getting several errors about unknown dns view.

##### STEPS TO REPRODUCE

```
FAILED! => {"changed": false, "code": "Client.Ibap.Data.NotFound", "msg": "View Inmar.com not found", "operation": "create_object", "type": "AdmConDataNotFoundError"}

{"changed": false, "code": "Client.Ibap.Data.NotFound", "msg": "View default not found", "operation": "create_object", "type": "AdmConDataNotFoundError"}
```

```
---

  - name: Create Infoblox Host Record (A & PTR)
    hosts: infoblox
    connection: local
    gather_facts: no

    tasks:

      - name: Create xyz.com host record.
        nios_host_record:
          name: TC-4A-SWSTK1.xyz.com
          dns_view: xyz.com
          ipv4:
            - address: 10.100.4.10
          state: present
          provider:
            host: 10.1.20.149
            username: admin
            password: admin
            ssl_verify: no

```

##### EXPECTED RESULTS

DNS record in the xyz.com zone with value of 10.100.4.10

##### ACTUAL RESULTS

```
(infoblox-test) [e116173@pwslnetseccp001 staging]$ ansible-playbook -i infoblox create_host.yaml -vvvv
ansible-playbook 2.5.0
  config file = None
  configured module search path = [u'/home/e116173@xyz.com/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/e116173@xyz.com/venv/infoblox-test/lib/python2.7/site-packages/ansible
  executable location = /home/e116173@xyz.com/venv/infoblox-test/bin/ansible-playbook
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
No config file found; using defaults
setting up inventory plugins
Parsed /home/e116173@xyz.com/venv/infoblox-test/staging/infoblox inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /home/e116173@xyz.com/venv/infoblox-test/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: create_host.yaml *************************************************************************************************************************************************************************************
1 plays in create_host.yaml

PLAY [Create Infoblox Host Record (A & PTR)] *******************************************************************************************************************************************************************
META: ran handlers

TASK [Create xyz.com host record.] ***************************************************************************************************************************************************************************
task path: /home/e116173@xyz.com/venv/infoblox-test/staging/create_host.yaml:10
Using module file /home/e116173@xyz.com/venv/infoblox-test/lib/python2.7/site-packages/ansible/modules/net_tools/nios/nios_host_record.py
<corp-infoblox01.xyz.com> ESTABLISH LOCAL CONNECTION FOR USER: e116173
<corp-infoblox01.xyz.com> EXEC /bin/sh -c 'echo ~ && sleep 0'
<corp-infoblox01.xyz.com> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/e116173@xyz.com/.ansible/tmp/ansible-tmp-1522091856.77-109708754751087 `" && echo ansible-tmp-1522091856.77-109708754751087="` echo /home/e116173@xyz.com/.ansible/tmp/ansible-tmp-1522091856.77-109708754751087 `" ) && sleep 0'
<corp-infoblox01.xyz.com> PUT /home/e116173@xyz.com/.ansible/tmp/ansible-local-4615FkLYIE/tmpPqgYLm TO /home/e116173@xyz.com/.ansible/tmp/ansible-tmp-1522091856.77-109708754751087/nios_host_record.py
<corp-infoblox01.xyz.com> EXEC /bin/sh -c 'chmod u+x /home/e116173@xyz.com/.ansible/tmp/ansible-tmp-1522091856.77-109708754751087/ /home/e116173@xyz.com/.ansible/tmp/ansible-tmp-1522091856.77-109708754751087/nios_host_record.py && sleep 0'
<corp-infoblox01.xyz.com> EXEC /bin/sh -c 'python /home/e116173@xyz.com/.ansible/tmp/ansible-tmp-1522091856.77-109708754751087/nios_host_record.py && sleep 0'
<corp-infoblox01.xyz.com> EXEC /bin/sh -c 'rm -f -r /home/e116173@xyz.com/.ansible/tmp/ansible-tmp-1522091856.77-109708754751087/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_NO7ZB0/ansible_modlib.zip/ansible/module_utils/net_tools/nios/api.py", line 146, in _invoke_method
    return method(*args, **kwargs)
  File "/home/e116173@xyz.com/venv/infoblox-test/lib/python2.7/site-packages/infoblox_client/connector.py", line 41, in callee
    return func(*args, **kwargs)
  File "/home/e116173@xyz.com/venv/infoblox-test/lib/python2.7/site-packages/infoblox_client/connector.py", line 364, in create_object
    code=r.status_code)

fatal: [corp-infoblox01.xyz.com]: FAILED! => {
    "changed": false,
    "code": "Client.Ibap.Data.NotFound",
    "invocation": {
        "module_args": {
            "comment": null,
            "dns_view": "xyz.com",
            "extattrs": null,
            "ipv4": [
                {
                    "address": "10.100.4.10",
                    "ipv4addr": "10.100.4.10",
                    "mac": null
                }
            ],
            "ipv4addrs": [
                {
                    "address": "10.100.4.10",
                    "ipv4addr": "10.100.4.10",
                    "mac": null
                }
            ],
            "ipv6addrs": null,
            "name": "TC-4A-SWSTK1.xyz.com",
            "provider": {
                "host": "10.1.20.149",
                "http_pool_connections": 10,
                "http_pool_maxsize": 10,
                "http_request_timeout": 10,
                "max_results": 1000,
                "max_retries": 3,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "silent_ssl_warnings": true,
                "ssl_verify": false,
                "username": "admin",
                "wapi_version": "1.4"
            },
            "state": "present",
            "ttl": null,
            "view": "xyz.com"
        }
    },
    "msg": "View xyz.com not found",
    "operation": "create_object",
    "type": "AdmConDataNotFoundError"

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/lookup/nios.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/nios.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Qalthos @ganeshrn @gdpak @gundalow @privateip @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by realged13** [comment]
For people who might wanted to know, make sure when doing host records, do choose the view under `Data Management > DNS`.  Do not use network view, which is entirely different.

**Comment by theodotos** [comment]
@realged13 your last comment saved me some endless hours of troubleshooting. Thanks!

Also the examples at *nios_host_record.py* are incomplete. Here's a complete example:

```
---
- hosts: localhost
  connection: local

  tasks:

  - name: configure an ipv4 host record
    nios_host_record:
      name: test.example.com
      view: "MY DNS VIEW"
      ipv4:
        - address: 10.10.20.34
      state: present
      comment: "Testing Infoblox Ansible integration"
      provider:
        host: "10.10.10.10"
        username: niosadmin
        password: MySecretCombination
```
