### ISSUE TITLE
Ansible 2.5.0, ios_facts not showing stacked models/serials against 3850 running 16.6.2

### ISSUE THREAD

**Issue by zztopping** [ansible/ansible#37948]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/vagrant/.ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

PARAMIKO_HOST_KEY_AUTO_ADD(/home/vagrant/.ansible.cfg) = True
RETRY_FILES_ENABLED(/home/vagrant/.ansible.cfg) = False

##### OS / ENVIRONMENT

N/A

##### SUMMARY

New ios_facts module in 2.5 reports serials and models of Cisco Switches contained in a "stack". Reports on some other switches fine, but this variable not seen in the JSON dump of a 2-switch 3850 stack running IOS-XE 16.6.2

##### STEPS TO REPRODUCE

```yaml
---
  - name: IOS FACTS
    hosts: ios
    connection: network_cli
    become: yes
    become_method: enable
    gather_facts: no
    
    tasks:
      - name: GATHER FACTS
        ios_facts:
          gather_subset: hardware
        register: facts
      
      - debug: var=facts
```

##### EXPECTED RESULTS

I expected the ansible_net_stacked_models and ansible_net_stacked_serialnums to be returned for this switch, as it is done with others

##### ACTUAL RESULTS

All other facts are returned, just missing stack variables. Its as if the module is not "sensing" that this inventory item is actually a stack

```
ok: [<snipped_for_privacy>] => {
    "facts": {
        "ansible_facts": {
            "ansible_net_filesystems": [
                "flash:"
            ],
            "ansible_net_gather_subset": [
                "hardware",
                "default"
            ],
            "ansible_net_hostname": "hqcoresw1",
            "ansible_net_image": "flash:packages.conf",
            "ansible_net_memfree_mb": 546806,
            "ansible_net_memtotal_mb": 853266,
            "ansible_net_model": "WS-C3850-12X48U",
            "ansible_net_serialnum": "<snipped_for_privacy>",
            "ansible_net_version": "16.06.02"
        },
        "changed": false,
        "failed": false
    }
}
```
