### ISSUE TITLE
s3_sync module unidentified error

### ISSUE THREAD

**Issue by 1efty** [ansible/ansible#37959]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

s3_sync module

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = $project_dir/ansible.cfg
  configured module search path = [u'$HOME/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = $HOME/.local/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS = -C -o ControlMaster=auto -o ControlPersist=60s -o ServerAliveInterval=60
CACHE_PLUGIN = memory
DEFAULT_BECOME_METHOD = sudo
DEFAULT_BECOME_USER = root
DEFAULT_HOST_LIST = $PROJECT_DIR/inventories/development
DEFAULT_MANAGED_STR = Ansible Managed - ANY CHANGES WILL NOT PERSIST
DEFAULT_PRIVATE_ROLE_VARS = True
DEFAULT_ROLES_PATH = $PROJECT_DIR/roles
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = $HOME/.vault_pass.txt
HOST_KEY_CHECKING = False
INVENTORY_ENABLED = ['ini', 'aws_ec2', 'constructed']
RETRY_FILES_ENABLED = False
```

##### OS / ENVIRONMENT

Running from: Fedora 27
Running on: CentOS 7

##### SUMMARY

We want to ensure our file server is backed up to S3.  The volume is roughly 2.9TB and has hundreds of thousands if not millions of files.  The module works fine for our smaller backups.  

##### STEPS TO REPRODUCE

```yaml
 name: Sync Directories to S3
  s3_sync:
    bucket: "{{ s3backup_bucket | default(item.bucket, True) }}"
    file_root: "{{ item.file_root | mandatory }}"
    key_prefix: "{{ item.key_prefix | default(omit) }}"
    exclude: "{{ item.excludes | default(omit) }}"
    include: "{{ item.includes | default(omit) }}"
    file_change_strategy: "{{ item.file_change_strategy | default(omit) }}"
    permission: "{{ item.permission | default('private') }}"
  with_items: "{{ s3backups }}"
  loop_control:
    label: "{{ item.file_root }} -> s3://{{ s3backup_bucket | default(item.bucket, True) }}/{{ item.key_prefix }}"

```

##### EXPECTED RESULTS

For the files to be pushed to S3.  

##### ACTUAL RESULTS

The module failed, with no explanation.  However, after looking at the verbose output, it looks like a connection issue.  

```
failed: [files.d1d] (item=/storage -> s3bucket) => {
    "changed": false, 
    "item": {
        "file_root": "/storage", 
        "key_prefix": "dev/files/2018-03", 
        "lifecycle": {
            "expiration_days": 60, 
            "prefix": "dev/files/", 
            "rule_id": "dev/files-backup-lifecycle", 
            "transition_days": 30
        }
    }, 
    "module_stderr": "OpenSSH_7.6p1, OpenSSL 1.1.0g-fips  2 Nov 2017\r\ndebug1: Reading configuration data $HOME/.ssh/config\r\ndebug1:$HOME/.ssh/config line 5: Applying options for *\r\ndebug1: $HOME/.ssh/config line 60: Applying options for *.d1d\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug3: /etc/ssh/ssh_config line 52: Including file /etc/ssh/ssh_config.d/05-redhat.conf depth 0\r\ndebug1: Reading configuration data /etc/ssh/ssh_config.d/05-redhat.conf\r\ndebug3: /etc/ssh/ssh_config.d/05-redhat.conf line 2: Including file /etc/crypto-policies/back-ends/openssh.config depth 1\r\ndebug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config\r\ndebug3: gss kex names ok: [gss-gex-sha1-,gss-group14-sha1-]\r\ndebug3: kex names ok: [curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1]\r\ndebug1: /etc/ssh/ssh_config.d/05-redhat.conf line 8: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 4 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 23276\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 247\r\nShared connection to files.d1d closed.\r\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 247
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/s3_sync.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/s3_sync.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @tedder @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ryansb** [comment]
needs_info 

It looks like there's an issue in the network connection, indicated by the "broken pipe" on the SSH connection. Is there a way you can connect to that host without Ansible and test the stability/accessibility of the host?

**Comment by 1efty** [comment]
I can, how do you suggest I test the stability?  
  
Some more information:

I am connecting through a bastion host.

Edit:

Same results when bypassing bastion host.

**Comment by tedder** [comment]
I'd suggest using [async-and-polling or async-and-forget](http://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html); Ansible (or ssh, rather) isn't really designed for running many hours, especially if you are bouncing across the public interwebs.

**Comment by 1efty** [comment]
I took your suggestion.

```yaml
- name: Sync Directories to S3
  s3_sync:
    bucket: "{{ s3backup_bucket | default(item.bucket, True) }}"
    file_root: "{{ item.file_root | mandatory }}"
    key_prefix: "{{ item.key_prefix | default(omit) }}"
    exclude: "{{ item.excludes | default(omit) }}"
    include: "{{ item.includes | default(omit) }}"
    file_change_strategy: "{{ item.file_change_strategy | default(omit) }}"
    permission: "{{ item.permission | default('private') }}"
  with_items: "{{ s3backups }}"
  async: 10000
  poll: 10
  loop_control:
    label: "{{ item.file_root }} -> s3://{{ s3backup_bucket | default(item.bucket, True) }}/{{ item.key_prefix }}"
```

This is the result after ~ 10 polls:
```
failed: [files] (item=/storage -> ) => {
    "ansible_job_id": "834959226599.14036", 
    "changed": false, 
    "cmd": "$HOME.ansible/tmp/ansible-tmp-1522245782.2-2033598974287/s3_sync.py", 
    "data": "", 
    "finished": 1, 
    "invocation": {
        "module_args": {
            "jid": "834959226599.14036", 
            "mode": "status"
        }
    }, 
    "item": {
        "file_root": "/storage", 
        "key_prefix": "dev/files/2018-03", 
        "lifecycle": {
            "expiration_days": 60, 
            "prefix": "dev/files/", 
            "rule_id": "dev/files-backup-lifecycle", 
            "transition_days": 30
        }
    }, 
    "msg": "Traceback (most recent call last):\n  File \"$HOME.ansible/tmp/ansible-tmp-1522245782.2-2033598974287/async_wrapper.py\", line 150, in _run_module\n    (filtered_outdata, json_warnings) = _filter_non_json_lines(outdata)\n  File \"$HOME/.ansible/tmp/ansible-tmp-1522245782.2-2033598974287/async_wrapper.py\", line 91, in _filter_non_json_lines\n    raise ValueError('No start of json char found')\nValueError: No start of json char found\n", 
    "stderr": "", 
    "stderr_lines": []
}

```
