### ISSUE TITLE
Creating a security group with none rules_egress doesn't create default all-out rule

### ISSUE THREAD

**Issue by bmamouri** [ansible/ansible#37963]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /Users/baqer/deployment/ansible.cfg
  configured module search path = [u'/Users/baqer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/baqer/Library/Python/2.7/lib/python/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/Users/baqer/deployment/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-s
HOST_KEY_CHECKING(/Users/baqer/deployment/ansible.cfg) = False

##### OS / ENVIRONMENT
N/A

##### SUMMARY
If none `rules_egress` is specified, a default all-out rule is **not** assumed. The [docs](http://docs.ansible.com/ansible/latest/ec2_group_module.html) indicates the contrary.

##### STEPS TO REPRODUCE
1. Create a simple playbook that creates an EC2 security group
```yaml
- name: Create a security group for EC2 instances
  ec2_group:
    name: "test"
    description: "Test"

    region: "ap-southeast-2"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
```

2. Run the following command:
```
$ aws ec2 describe-security-groups --group-name test --region ap-southeast-2
```

##### EXPECTED RESULTS
```
{
    "SecurityGroups": [
        {
            "IpPermissionsEgress": [
                {
                    "PrefixListIds": [],
                    "FromPort": 0,
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ],
                    "ToPort": 65535,
                    "IpProtocol": "tcp",
                    "UserIdGroupPairs": [],
                    "Ipv6Ranges": []
                }
            ],
            "Description": "Test",
            "IpPermissions": [
                {
                    "PrefixListIds": [],
                    "FromPort": 22,
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ],
                    "ToPort": 22,
                    "IpProtocol": "tcp",
                    "UserIdGroupPairs": [],
                    "Ipv6Ranges": []
                }
            ],
            "GroupName": "test",
            "VpcId": "REDACTED",
            "OwnerId": "REDACTED",
            "GroupId": "REDACTED"
        }
    ]
}
```

##### ACTUAL RESULTS
```
{
    "SecurityGroups": [
        {
            "IpPermissionsEgress": [],
            "Description": "Test",
            "IpPermissions": [
                {
                    "PrefixListIds": [],
                    "FromPort": 22,
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ],
                    "ToPort": 22,
                    "IpProtocol": "tcp",
                    "UserIdGroupPairs": [],
                    "Ipv6Ranges": []
                }
            ],
            "GroupName": "test",
            "VpcId": "REDACTED",
            "OwnerId": "REDACTED",
            "GroupId": "REDACTED"
        }
    ]
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @adq @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ryansb** [comment]
Thanks for raising this with all this info - I'll try to repro this on 2.5.

**Comment by ryansb** [comment]
It looks like this group is being created outside a VPC (no VPC ID in the task) - my test here:

```
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - ec2_group:
        name: foo-test-group
        description: test
        vpc_id: vpc-be10f2d9
        rules:
        - proto: tcp 
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
    - pause: minutes=2
    - ec2_group:
        state: absent
        name: foo-test-group
        vpc_id: vpc-be10f2d9
```

Results in a group with the default egress rule:

```
        {
            "IpPermissionsEgress": [
                {
                    "IpProtocol": "-1", 
                    "PrefixListIds": [], 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "UserIdGroupPairs": [], 
                    "Ipv6Ranges": []
                }
            ], 
            "Description": "test", 
            "IpPermissions": [
                {
                    "PrefixListIds": [], 
                    "FromPort": 22, 
                    "IpRanges": [
                        {
                            "CidrIp": "0.0.0.0/0"
                        }
                    ], 
                    "ToPort": 22, 
                    "IpProtocol": "tcp", 
                    "UserIdGroupPairs": [], 
                    "Ipv6Ranges": []
                }
            ], 
            "GroupName": "foo-test-group", 
            "VpcId": "vpc-be10f2d9", 
            "OwnerId": "REDACTED", 
            "GroupId": "sg-5dda2123"
        }, 
```

My best guess is that it's to do with your default VPC or account EC2 Classic support. Can you run `aws ec2 describe-account-attributes` and look at the value of `supported-platforms`? It will either just say "VPC" or "VPC, EC2-Classic".
