### ISSUE TITLE
variable for hosts from vars_prompt no longer accepted

### ISSUE THREAD

**Issue by zubfatal** [ansible/ansible#37984]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

playbook

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

##### OS / ENVIRONMENT

Running from: Debian GNU/Linux 8.10 (jessie)

##### SUMMARY

hosts no longer accepts a variable from vars_prompt
This worked fine prior to version 2.5.0

##### STEPS TO REPRODUCE

```yaml
---
- hosts: "{{ target }}"
  vars_prompt:
    - name: target
      prompt: "Enter target(s) (separate by ',')"
      private: no
      when: target == ""
```

##### EXPECTED RESULTS

To be prompted for "targets" before execution, unless provided with -e "target=something"

##### ACTUAL RESULTS

```
ansible-playbook 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: upgrade-packages.yml ********************************************************************************************************************************************************************************
1 plays in playbooks/upgrade-packages.yml
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'target' is undefined

The error appears to have been in '/root/playbooks/upgrade-packages.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- hosts: "{{ target }}"
  ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/cli/playbook.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/playbook.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
@zubfatal Please test with #38000 and see if that fixes this issue. Thank you for reporting this.

**Comment by zubfatal** [comment]
Nice work @samdoran I can confirm this fixes the issue :)

**Comment by jorti** [comment]
This commit fixes the issue for me. Please, add the fix in the next release.

Thanks!

**Comment by kladiv** [comment]
+1

**Comment by zubfatal** [comment]
Yes please, it would be great to have this added - thanks!

**Comment by dbpiv** [comment]
Git terminology is probably incorrect....  But when will this fix be incorporated.  2.5.5. still has the same issue (fortunately the fix is easy enough to apply)

**Comment by samdoran** [comment]
The fix I came up with is a unsafe because it's not doing any type validation. After some discussion with others, it seems I need to rewrite `post_validate` which is more involved and I have not gotten to it.

**Comment by dbpiv** [comment]
So are you going to re-open https://github.com/ansible/ansible/pull/38000 again or create a new num?  Just trying to watch for the fix.  Vars_Prompt is extremely important to us (at least until we get Tower installed).

**Comment by samdoran** [comment]
@dbpiv I'll open a new PR with a fix. I actually closed that by accident when I was renaming branches.

**Comment by Sher-Chowdhury** [comment]
+1

**Comment by coom** [comment]
Hi everyone,

Is it normal that this does not work anymore with ansible 2.6.1 ?

I'm trying this simple playbook :

```text
- name: "Test playbook"
- hosts: "{{ hosts }}"
  vars_prompt:
    - name: "hosts"
      prompt: "Which hosts would you like to setup?"
      private: no
  tasks:
    - name: Just a simple test
      service:
        name: ssh
        state: restarted
```

But it result in an error :
```text
ERROR! the field 'hosts' is required but was not set
```

**Comment by abadger** [comment]
@coom: I think your issue is the extra "-" at the top of your sample playbook.  It should be
```
- name: "Test playbook"
  hosts: "{{ hosts }}"
```

**Comment by coom** [comment]
@abadger Tried with this modified playbook (as suggested) :

```yaml
- name: "Test playbook"
  hosts: "{{ cible }}"
  vars_prompt:
    - name: "cible"
      prompt: "Which hosts would you like to setup?"
      private: no
      when: cible == ""
  tasks:
    - name: Just a simple test
      service:
        name: ssh
        state: restarted
```

Still no luck :

```text
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'cible' is undefined

The error appears to have been in '/home/ansible/Test/GTR/ssh.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "Test playbook"
  ^ here
```

**Comment by abadger** [comment]
@coom.  Right.  Now you have the error that this issue is about :-)

**Comment by coom** [comment]
@abadger: Allright, thank you :)

**Comment by mickael-ange** [comment]
I confirm I have the same issue with Ansible 2.6.1
```
---
- hosts:
    - vagrant:&core
    - tag_aws_cloudformation_stack_name_{{ core_stack | regex_replace('-' , '_') }}:&core
  strategy: "{{ extravars_ansible_strategy | default('linear') }}"
  vars_prompt:
  - name: "core_stack"
    prompt: "What Core AutoScalingGroup do you wish to provision?"
    default: "core-dev-stack-blue"
    private: no
  roles:
    - role: core
 [..]
```

```
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'core_stack' is undefined

The error appears to have been in 'ansible/playbooks/core.yml': line 9, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- hosts:
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
(ansible-2.6.1) $ ansible-playbook --version
ansible-playbook 2.6.1
  config file = /home/mickael/git/devops/ansible/ansible.cfg
  configured module search path = [u'/home/mickael/git/devops/ansible/modules']
  ansible python module location = /home/mickael/ansible-2.6.1/local/lib/python2.7/site-packages/ansible
  executable location = /home/mickael/ansible-2.6.1/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

**Comment by samdoran** [comment]
I have a working fix (plus tests!). Took me down a long rabbit hole, but it was enlightening. I would appreciate testing/feedback with #39304. I want to get this out in the next 2.5 and 2.6 releases.

**Comment by priyankaprabhune26** [comment]
Can you please let us know what need to change here for the ansible v2.5.4?
---
- hosts: "{{ hosts }}"
  vars_prompt:
    - name: "hosts"
      private: no

**Comment by priyankaprabhune26** [comment]
Can you please suggest what needs to do to get this fix for the ansible v2.6.2?

```yaml
- hosts: "{{ hosts }}"
  vars_prompt:
    - name: "hosts"
      private: no
```

**Comment by dbpiv** [comment]
I commented on #39304 directly.... But for thoroughness, I will reply here as well. 

At this point, I have used the updated version 70+ times with various combinations of --extra-vars and vars_prompts.  So far I have had no issues.

Thanks for the patch @samdoran .

**Comment by dsofeir** [comment]
While people are waiting for the #39304 to be included in a release a simple fix to get a playbook to run is to use the `--extra-vars` option :

```
ansible-playbook upgrade-packages.yml --extra-vars="target=host.example.com"
```

__Note:__

1.`target` is the name of the variable which provides the host to the playbook, you may have a different name. Look for `hosts: " {{ example }}"` in your playbook where `example` is your variable name.

2.`host.example.com` is the host which you would like the playbook to operate on

----

@samdoran Is there any way I can help to get #39304 in to the next 2.5 and 2.6 releases?

**Comment by dbpiv** [comment]
Thanks @dsofeir ...  That was established as the work around early on, however in our environment 90+% of the playbooks are manually run.  The vars_prompt just provides a method which works better for our folks who are running the playbooks on demand.  

But I whole heartedly agree with your question to @samdoran.  Is there anything else we can do to help?

**Comment by AfolabiOlaoluwa** [comment]
The image below is the error am getting. Its just frustrating. Can someone help me?

**playbook.yml**
```
---
- name: Hosted Services API
  hosts: api
  vars_prompt:
    name: "hosts"
    private: no
  vars:
    py_version: "2.7.10"
```

**inventory file**
```
[all:vars]
ansible_python_interpreter = /usr/bin/python3

[api]
XXX.XXX.XXX.XXX
```

<img width="873" alt="screen shot 2018-08-12 at 17 13 19" src="https://user-images.githubusercontent.com/15254043/44004774-20157ed6-9e60-11e8-8a7c-0b8faf3ecd52.png">
