### ISSUE TITLE
certain conditionals cannot be used in the until loop in 2.5

### ISSUE THREAD

**Issue by IvanovOleg** [ansible/ansible#37980]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

until loop
##### ANSIBLE VERSION

```
2.5.0
```

##### OS / ENVIRONMENT

Centos 7.4
##### SUMMARY

If all packages are up to date, yum module throws an error.
##### STEPS TO REPRODUCE

**install_packages.yml**
```
---

- name: Install a yum packages
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items: "{{ yum_packages }}"
  register: result
  until: '"failed" not in result'
  retries: 10
  delay: 10

```
**install.yml**

```
- name: Install the the yum packages
  become: True
  import_tasks: ../../../tasks/install_packages.yml
  vars:
    yum_packages:
      - "@Development tools"
      - gmp-devel
      - python-devel
      - zlib-devel
      - bzip2-devel
      - openssl-devel
      - ncurses-devel
      - sqlite-devel
      - readline-devel
      - tk-devel
      - gdbm-devel
      - libpcap-devel
      - xz-devel
      - expat-devel
      - libcurl-devel
      - perl-devel
      - libunwind.x86_64
      - icu
```

##### EXPECTED RESULTS

`ok: [hostname]`
##### ACTUAL RESULTS

```
failed: [hostname] (item=[u'@Development tools', u'gmp-devel', u'python-devel', u'zlib-devel', u'bzip2-devel', u'openssl-devel', u'ncurses-devel', u'sqlite-devel', u'readline-devel', u'tk-devel', u'gdbm-devel', u'libpcap-devel', u'xz-devel', u'expat-devel', u'libcurl-devel', u'perl-devel', u'libunwind.x86_64', u'icu']) => {"attempts": 10, "changed": false, "item": ["@Development tools", "gmp-devel", "python-devel", "zlib-devel", "bzip2-devel", "openssl-devel", "ncurses-devel", "sqlite-devel", "readline-devel", "tk-devel", "gdbm-devel", "libpcap-devel", "xz-devel", "expat-devel", "libcurl-devel", "perl-devel", "libunwind.x86_64", "icu"], "msg": "", "rc": 0, "results": ["All packages providing gmp-devel are up to date", "All packages providing python-devel are up to date", "All packages providing zlib-devel are up to date", "All packages providing bzip2-devel are up to date", "All packages providing openssl-devel are up to date", "All packages providing ncurses-devel are up to date", "All packages providing sqlite-devel are up to date", "All packages providing readline-devel are up to date", "All packages providing tk-devel are up to date", "All packages providing gdbm-devel are up to date", "All packages providing libpcap-devel are up to date", "All packages providing xz-devel are up to date", "All packages providing expat-devel are up to date", "All packages providing libcurl-devel are up to date", "All packages providing perl-devel are up to date", "All packages providing libunwind.x86_64 are up to date", "All packages providing icu are up to date", "Loaded plugins: fastestmirror, langpacks\nLoading mirror speeds from cached hostfile\nPackage 1:gmp-devel-6.0.0-15.el7.x86_64 already installed and latest version\nPackage python-devel-2.7.5-58.el7.x86_64 already installed and latest version\nPackage zlib-devel-1.2.7-17.el7.x86_64 already installed and latest version\nPackage bzip2-devel-1.0.6-13.el7.x86_64 already installed and latest version\nPackage 1:openssl-devel-1.0.2k-8.el7.x86_64 already installed and latest version\nPackage ncurses-devel-5.9-14.20130511.el7_4.x86_64 already installed and latest version\nPackage sqlite-devel-3.7.17-8.el7.x86_64 already installed and latest version\nPackage readline-devel-6.2-10.el7.x86_64 already installed and latest version\nPackage 1:tk-devel-8.5.13-6.el7.x86_64 already installed and latest version\nPackage gdbm-devel-1.10-8.el7.x86_64 already installed and latest version\nPackage 14:libpcap-devel-1.5.3-9.el7.x86_64 already installed and latest version\nPackage xz-devel-5.2.2-1.el7.x86_64 already installed and latest version\nPackage expat-devel-2.1.0-10.el7_3.x86_64 already installed and latest version\nPackage libcurl-devel-7.29.0-42.el7_4.1.x86_64 already installed and latest version\nPackage 4:perl-devel-5.16.3-292.el7.x86_64 already installed and latest version\nPackage 2:libunwind-1.2-2.el7.x86_64 already installed and latest version\nPackage icu-50.1.2-15.el7.x86_64 already installed and latest version\nNothing to do\n"]}
```

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/yum.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @berenddeschouwer @mkrizek @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
@IvanovOleg Thanks for the bug report! Has this worked in the earlier versions of Ansible?

**Comment by IvanovOleg** [comment]
@mkrizek , yes

**Comment by mkrizek** [comment]
@IvanovOleg okay, I can reproduce the issue. Note: when I remove this part:
```
until: '"failed" not in result'
retries: 10
delay: 10
```
then it works for me. In any case, looking into the issue. Not sure it's `yum` issue.

**Comment by mkrizek** [comment]
@IvanovOleg As a workaround, would changing the condition to `until: "result is success"` work for you?

**Comment by IvanovOleg** [comment]
@mkrizek yes, it does! Thanks!

**Comment by mkrizek** [comment]
To demonstrate the actual "issue":
```
- hosts: localhost
  gather_facts: no
  tasks:
    - name: works on 2.4 and 2.5
      command: /bin/true
      register: result
      until: "result is success"
      retries: 1
      delay: 1

    - name: works on 2.4 and fails on 2.5
      command: /bin/true
      register: result
      until: "'failed' not in result"
      retries: 1
      delay: 1
```

`git bisect`'ed to https://github.com/ansible/ansible/pull/34148

cc @sivel
