### ISSUE TITLE
IOS XE timeout trying to send command: wr

### ISSUE THREAD

**Issue by koladiya** [ansible/ansible#37991]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_config or ios_command

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### CONFIGURATION

None
##### OS / ENVIRONMENT

Cisco C3650 Switch
Cisco IOS-XE Software catalyst L3 Switch software, version 03.07.05E

##### STEPS TO REPRODUCE

```yaml



  - name: save running to startup when modified
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      save_when: modified
OR
  - name: save running to startup when modified
    ios_command:
      provider: "{{ provider }}"
      authorize: yes
      commands:
        - wr 


```
NOTE: These both tasks are working properly on IOS but not working on IOS XE.
I have also tried with different timeout.
```
timeout: 100
```

##### EXPECTED RESULTS
I expected the running-config to be saved as the starting-config

##### ACTUAL RESULTS

```
timeout trying to send command: copy running-config startup-config
OR
timeout trying to send command: wr
```
##### NOTE:

Everything else is working fine.
for example:

```
- name: Change Hostname...
    ios_config:
      provider: "{{ provider }}"
      authorize: yes
      lines:
        hostname ansible_switch
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/ios/ios_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_command.py)
* [lib/ansible/modules/network/ios/ios_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @privateip @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by koladiya** [comment]
any update?
Could you please help me out how to push the "copy running-config startup-config " or "write memory" command into IOS-XE devices?

**Comment by tyler-8** [comment]
@koladiya Try the command `wr` and `copy running-config startup-config` manually on your device. What output do you see? Are you getting any prompts? Could you paste the output here? To me it sounds like something unexpected is happening and Ansible isn't getting the prompt it expects.

**Comment by koladiya** [comment]
@tyler-8  
**IOS XE cat3650 Switch (example)**

**_prompted with "copy running-config startup-config"_**
> #copy running-config startup-config 
> **Destination filename [startup-config]?** 

 press enter
> Building configuration...
> [OK]

**_didn't prompt with "wr"_**

> #wr
> Building configuration...
> Compressed configuration from 14363 bytes to 6063 bytes[OK]

**Comment by Noname2244** [comment]
I have a similar problem with 3.7.5 when Issuing a ios_command: verify /md5 flash:image.bin

I have timeout: 900
but the command seems to timeout after about 30s.

**Comment by Noname2244** [comment]
I did some more testing and it works fine against 16.3.6 but not any 3. ios xe releases


` tasks:
    - name: Verify file checksum
      ios_command:
        provider: "{{ CREDS_IOS_T1 }}"
        timeout: 900
        commands: verify /md5 flash:cat3k_caa-universalk9.16.03.06.SPA.bin
        wait_for: result[0] contains a65a6308ec728a92f8463e5bfb6b79f0 `

**Comment by Noname2244** [comment]
ansible --version
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/krifag/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

**Comment by ganeshrn** [comment]
@Noname2244 How are you setting the timeout value? You can set command_timeout and connect_timeout value in the configuration file under `persistent_connection` section.

https://docs.ansible.com/ansible/latest/network/user_guide/network_debug_troubleshooting.html#timeout-issues

@koladiya Can you please increase the command timeout value and check.

Also for sake of testing the commands works through Ansible you can copy the configuration using `ios_command` module.
```
    ios_command:
      commands:
        - command: 'copy running-config startup-config'
          prompt: 'Destination filename'
          answer: ''
``` 

needs_info
