### ISSUE TITLE
Tags not works in 2.5 as in 2.4 

### ISSUE THREAD

**Issue by jbarotin** [ansible/ansible#37994]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tags

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /Users/mylogin/.ansible.cfg
  configured module search path = ['/Users/mylogin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.4 (default, Jan  6 2018, 11:51:59) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT
OSX 

##### STEPS TO REPRODUCE

Here the following playbook test.yml
```yaml
- name: test
  hosts: myhost  remote_user: mylogin
  tasks:
    - include_role:
        name=test-role1
      tags: role1
    - include_role:
        name=test-role2
      tags: role2
```
Role files are the following : 
roles/test-role1/tasks/main.yml
```yaml
---
- name: first line
  debug:
    msg: "this the first line"
```

roles/test-role2/tasks/main.yml
```yaml
---
- name: first line
  debug:
    msg: "this the second line"
```

##### EXPECTED RESULTS
The following command :
`ansible-playbook test.yml --tags=role2`

Should give the following result :
```
PLAY [test] *************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************
ok: [myhost]

TASK [include_role] *****************************************************************************************************************

TASK [test-role2 : first line] ******************************************************************************************************
ok: [myhost] => {
    "msg": "this the second line"
}

PLAY RECAP **************************************************************************************************************************
myhost     : ok=2    changed=0    unreachable=0    failed=0
```

##### ACTUAL RESULTS

```
PLAY [test] *************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************
ok: [myhost]

TASK [include_role] *****************************************************************************************************************

PLAY RECAP **************************************************************************************************************************
myhost    : ok=1    changed=0    unreachable=0    failed=0
```

**Comment by sivel** [comment]
This is an expected change in v2.5.

See http://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.5.html#dynamic-includes-and-attribute-inheritance

`tags` will only apply to whether or not the `include_role` is executed, the tasks within do not inherit the tags applied to `include_role`.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by jbarotin** [comment]
Thanks for the link, for those who came here with the same mistake. I fix my issue while using import_role :

```
- name: test
  hosts: myhost
  remote_user: mylogin
  tasks:
    - import_role:
        name=test-role1
      tags: role1
    - import_role:
        name=test-role2
      tags: role2
```
