### ISSUE TITLE
Mysql_db import failed with more than 5GB database.

### ISSUE THREAD

**Issue by kalaisubbiah** [ansible/ansible#38024]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

mysql_db

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_REMOTE_TMP(/etc/ansible/ansible.cfg) = ~/ansible/tmp
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ansible server= Red Hat Enterprise Linux Server release 7.4
Host: Red Hat Enterprise Linux Server release 6.8 with mysql-community-server-5.7.21-1.el6.x86_64

##### SUMMARY

I'm trying to upgrade mysql from 5.1 to 5.7.
built 3 ansible playbook as follow.
   1.backup the mysql
   2.install and intialize mysql-5.7
   3. import mysql-5.1 data dump to mysql-5.7 database.
Playbooks 1 & 3 are successfully completed, but playbook 3 is not exiting from the playbook after import the databases. I could see that all the databases are successfully imported,but the problem is playbook is not marking the tasks as finished and not proceeding with next tasks.
i tried with ignore_error: yes also doesn't help.

NOTE: the problem is reoccurring only for the database has more than 5GB. below 5GB databases are successfully imported.

##### STEPS TO REPRODUCE

Backup database has more than 5GB from mysql-5.1
restore it to mysql-5.7 using mysql_db module.

```yaml
---
- hosts: testvm
  gather_facts: no
  remote_user: itops
  become_user: root
  become_method: sudo
  become: yes
  vars:
    backup_path: /srv/backups/mysql_DB_Upgrade/DB_Dump
  tasks:

    - name: Importing DB backup to MySQL-5.7
      mysql_db:
        name: all
        state: import
        target: "{{ backup_path }}/All_Databases_Backup_Except_default_databases_{{ inventory_hostname }}.sql.gz"
        login_user: root
        login_password: ***

    - name: User_Grant_backup_after_upgrade
      shell: mysql -uroot -p*** -e source "{{ backup_path }}/First_User_Grant_backup_after_upgrade_to_execute.txt" >> "{{ backup_path }}/Final_Import_Log.txt"

    - name: mysql_upgrade command execution
      shell: mysql_upgrade -uroot -p*** --socket=/var/lib/mysql/mysql.sock >> "{{ backup_path }}/Final_Import_Log.txt"

    - name: Running mysqlcheck for all databases
      shell: mysqlcheck -uroot -p*** --all-databases >> "{{ backup_path }}/Final_Import_Log.txt"

```

##### EXPECTED RESULTS

      dump should be completed and go proceeding with next tasks.
##### ACTUAL RESULTS

```
[itops@sn1ylvx1f0001 kalai]$ ansible-playbook -i iplist mysql_import.yml --ask-pass --ask-sudo-pass
SSH password:
SUDO password[defaults to SSH password]:

PLAY [testvm] ******************************************************************************************************************************

TASK [Importing DB backup to MySQL-5.7] ****************************************************************************************************

fatal: [10.28.51.203]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Shared connection to 10.28.51.203 closed.\r\n", "unreachable": true}
        to retry, use: --limit @/home/itops/kalai/mysql_import.retry

PLAY RECAP *********************************************************************************************************************************
10.28.51.203               : ok=0    changed=0    unreachable=1    failed=0

[itops@sn1ylvx1f0001 kalai]$
```
