### ISSUE TITLE
Bug with two resource pools with same name in different clusters

### ISSUE THREAD

**Issue by tassdevops** [ansible/ansible#38043]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/ansible-ssh-%%h-%%p-%%r
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 30
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/home/user/git/ansible/hosts']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/home/user/git/ansible/roles']
DIFF_ALWAYS(/etc/ansible/ansible.cfg) = True
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
OpenSUSE 43.3
```

##### SUMMARY

I have 2 clusers (HA01 and HA02) in one datacenter. I have a resource pool with name "ID" in both datacenters. When Ansible try create VM, it's select only HA02/ID resource pool, regardless on variable "cluster" value.

##### STEPS TO REPRODUCE

createvm.yml
```yaml
- name: Create VM
  hosts: all
  remote_user: root
  connection: local

  vars_files:
    - cloud_login.yml

  roles:
    - createvm
```
```yaml
VCenterUsername: "user"
VCenterPassword: "password"
VCenterHostname: "cloud.local"
```
host_vars/172.28.16.15
```
VMName: "{{ Hostname }}.{{ Domain }}"
Domain: "local"
Hostname: "test01"
VMFolderName: "Test"
VMFolderParent: "/ID"
VMFolder: "{{ VMFolderParent }}/{{ VMFolderName }}"
Cluster: "HA01"
Datastore: "vnx-b01"

CPU: 16
RAMSize: 16384

IPAddress: "172.28.16.15"
```
roles/createvm/defaults/main.yml
```yaml
Datacenter: "MAIN"
Cluster: "HA01"
ResourcePool: "ID"
VMName: "test_vm"
Domain: "local"
Hostname: "test_vm"
GuestID: "rhel7_64Guest"
VMFolder: "/ID/Test"
VMTemplate: "TemplateCentOS7"
Datastore: "san-dl01"

# Hardware settings
HDDList:
    - { size_gb: "18", type: "thin", datastore: "{{ Datastore }}" }
RAMSize: 4096
CPU: 4

# Network settings
Vlan: "server244"
IPAddress: "172.28.16.200"
Netmask: "255.255.255.0"
Gateway: "172.28.16.1"
DNSServers:
    - "172.28.16.10"
    - "172.28.16.11"
```
roles/createvm/tasks/main.yml
```yaml
- name: Check for required variables
  fail:
      msg: "Must set VM name!"
  when: VMName is not defined
  tags:
    - createvm

- name: Check for vSphere access parameters
  fail:
      msg: "Must set VCenterUser and VCenterPass in a Vault"
  when: (VCenterUsername is not defined) or (VCenterPassword is not defined)
  tags:
    - createvm

- name: Create VM from template
  vmware_guest:
      validate_certs: False
      hostname: "{{ VCenterHostname }}"
      username: "{{ VCenterUsername }}"
      password: "{{ VCenterPassword }}"
      datacenter: "{{ Datacenter }}"
      cluster: "{{ Cluster }}"
      resource_pool: "{{ ResourcePool }}"
      name: "{{ VMName }}"
      guest_id: "{{ GuestID }}"
      folder: "{{ VMFolder }}"
      template: "{{ VMTemplate }}"
      disk: "{{ HDDList }}"
      networks:
          - name: "{{ Vlan }}"
            ip: "{{ IPAddress }}"
            netmask: "{{ Netmask }}"
            gateway: "{{ Gateway }}"
      hardware:
          memory_mb: "{{ RAMSize }}"
          num_cups: "{{ CPU }}"
      customization:
          domain: "{{ Domain }}"
          hostname: "{{ Hostname }}"
          dns_servers: "{{ DNSServers }}"
      wait_for_ip_address: True
      state: present
  register: newvm
  tags:
    - createvm

- name: IP address info
  debug:
      msg: "{{ newvm.instance.ipv4 }} {{ VMName }}"
  ignore_errors: yes
  tags:
    - createvm
```

##### EXPECTED RESULTS

Create VM with configuration described above

##### ACTUAL RESULTS

ansible-playbook createvm.yml --limit 172.28.16.15 -vvvvvv      

```
ansible-playbook 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /home/user/git/ansible/hosts inventory source with ini plugin
Read vars_file 'cloud_login.yml'
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/site-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: createvm.yml *******************************************************************************************
2 plays in createvm.yml
Read vars_file 'cloud_login.yml'
Read vars_file 'cloud_login.yml'

PLAY [Create VM] *************************************************************************************************
Read vars_file 'cloud_login.yml'

TASK [Gathering Facts] *******************************************************************************************
task path: /home/user/git/ansible/createvm.yml:2
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/namespace.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/ansible_collector.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/default_collectors.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/compat.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/timeout.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/collector.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/freebsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/openbsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/base.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/dragonfly.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/dragonfly.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/aix.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/aix.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/linux.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/platform.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/hpux.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/user.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/hurd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/other/facter.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/sunos.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/hpux.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/distribution.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/freebsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/openbsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/darwin.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/linux.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/sunos.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/sunos.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/chroot.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/apparmor.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/openbsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/local.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/other/ohai.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/other/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/service_mgr.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/hurd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/hpux.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/fips.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/selinux.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/pkg_mgr.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/dns.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/base.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/darwin.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/dragonfly.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/ssh_pub_keys.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/lsb.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/date_time.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/netbsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/base.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/cmdline.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/freebsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/netbsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/hardware/netbsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/caps.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/env.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/linux.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/system/python.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/network/generic_bsd.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/virtual/sysctl.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/utils.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/facts/sysctl.py
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<172.28.43.15> ESTABLISH LOCAL CONNECTION FOR USER: user
<172.28.43.15> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [172.28.43.15]
META: ran handlers
Read vars_file 'cloud_login.yml'

TASK [createvm : Check for required variables] ***************************************************************
task path: /home/user/git/ansible/roles/createvm/tasks/main.yml:1
skipping: [172.28.16.15] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
Read vars_file 'cloud_login.yml'

TASK [createvm : Check for vSphere access parameters] ***************************************************
task path: /home/user/git/ansible/roles/createvm/tasks/main.yml:8
skipping: [172.28.16.15] => {
    "changed": false, 
    "skip_reason": "Conditional result was False"
}
Read vars_file 'cloud_login.yml'

TASK [common/vmware/createvm : Create VM from template] **********************************************************
task path: /home/user/git/ansible/roles/createvm/tasks/main.yml:27
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/_text.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/basic.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/vmware.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/six/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/convert_bool.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/parsing/__init__.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/pycompat24.py
Using module_utils file /usr/lib/python2.7/site-packages/ansible/module_utils/urls.py
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<172.28.43.15> ESTABLISH LOCAL CONNECTION FOR USER: user
<172.28.43.15> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
fatal: [172.28.43.15]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": "HA01", 
            "customization": {
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ], 
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            }, 
            "customvalues": [], 
            "datacenter": "MAIN", 
            "disk": [
                {
                    "datastore": "vnx-b01", 
                    "size_gb": "18", 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "/ID/Test", 
            "force": false, 
            "guest_id": "rhel7_64Guest", 
            "hardware": {
                "memory_mb": 16384, 
                "num_cups": 16
            }, 
            "hostname": "cloud.local", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "********.********", 
            "name_match": "first", 
            "networks": [
                {
                    "gateway": "172.28.16.1", 
                    "ip": "172.28.16.15", 
                    "name": "server244", 
                    "netmask": "255.255.255.0", 
                    "type": "static"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "resource_pool": "ID", 
            "snapshot_src": null, 
            "state": "present", 
            "template": "TemplateCentOS7", 
            "username": "user", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }
    }, 
    "msg": "Failed to create a virtual machine : Unable to access the virtual machine configuration: Unable to access file [san-dl02] TemplateCentOS7/TemplateCentOS7.vmtx"
}

PLAY RECAP *******************************************************************************************************
172.28.16.15               : ok=1    changed=0    unreachable=0    failed=1   
```
