### ISSUE TITLE
 MemoryError when fetch file from server

### ISSUE THREAD

**Issue by Ankur012** [ansible/ansible#38062]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.4.3.0
```

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  remote_user: ubuntu
  tasks:
   - name: get ec2_instance_facts
     local_action:
       module: ec2_instance_facts
       aws_access_key: XXXXX
       aws_secret_key: XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
       region: us-west-XX
       filters:
          ip-address: XX.XX.XX.XX
     register: vm_info
 - name: fetch swupgrade logs
     local_action: command ansible -i {{ vm_info.instances[0].network_interfaces[0].private_ip_address }}, -u ec2-user -b -m fetch -a "src=/tmp/jre8-1.8.0_144-1.x86_64.rpm dest=/tmp " all
```

##### ACTUAL RESULTS

```

```
