### ISSUE TITLE
RDS module not allowing upgrade of engine_version due to missing AllowMajorVersionUpgrade flag

### ISSUE THREAD

**Issue by srkiNZ84** [ansible/ansible#38073]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
AWS RDS module: https://docs.ansible.com/ansible/latest/modules/rds_module.html

##### ANSIBLE VERSION
```
ansible 2.4.1.0
  config file = /Users/srdan/.../ansible.cfg
  configured module search path = ['/Users/srdan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.5/bin/ansible
  python version = 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### CONFIGURATION
Default configuration.

##### OS / ENVIRONMENT
From: OS X 10.13.3
To: N/A (AWS API)

##### SUMMARY
I'm trying to upgrade an RDS database by running a playbook with an RDS task and modifying the "engine_version" parameter. Specifically, I'm trying to upgrade MySQL from version "5.5.53" to version "5.6.37".

##### STEPS TO REPRODUCE
Run the playbook below against a "minimal" localhost inventory file and make sure you have an RDS instance that matches the parameters below, except for the engine_version number.

```bash
$ cat hosts
localhost ansible_connection=local
```

```bash
ansible-playbook -i hosts db-upgrade.yml
```

```yaml
- hosts: all
  tasks:

    - name: Modify the master database
      rds:
        aws_access_key: "REDACTED"
        aws_secret_key: "REDACTED"
        region: "us-east-1"
        command: modify
        upgrade: yes
        instance_name: "db8-core"
        instance_type: "db.m3.medium"
        username: "foo"
        password: "barbaz123"
        backup_retention: "0"
        vpc_security_groups: ['sg-abcd6ffe']
        parameter_group: "mysql5-6"
        engine_version: "5.6.37"
        apply_immediately: yes
        wait: yes
```

##### EXPECTED RESULTS
I would expect that the DB engine version would be modified and that the instance would be rebooted for the upgrade to take effect. Same as if you were to perform the actions manually through the AWS web console.

##### ACTUAL RESULTS
The task throws an error, complaining about a missing "AllowMajorVersionUpgrade" flag:

```
 ___________________________________
< TASK [Modify the master database] >
 -----------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "The AllowMajorVersionUpgrade flag must be present when upgrading to a new major version."}
	to retry, use: --limit @/Users/srdan/code/gdt-applications/platform/gdt-aws-ansible-infrastructure/db_upgrade.retry
```

The flag is documented somewhat in the AWS CLI documentation: https://docs.aws.amazon.com/cli/latest/reference/rds/modify-db-instance.html
