### ISSUE TITLE
issue using args and with_items

### ISSUE THREAD

**Issue by steverweber** [ansible/ansible#3807]
This example shows that when auth_user_list2 items are passed to args: the password is not set,,, but in auth_user_list3 since the item that has a password is passed before the shorter list of arguments it works.

```
- hosts: auth
  sudo: yes
  vars:
    auth_shadow_s8weber: "$1$salty$111111."
    auth_user_list1:
       - { name: s8weber, append: yes, groups: wheel, password: $auth_shadow_s8weber }

    auth_shadow_s8weber2: "$1$salty$22222."
    auth_user_list2:
      - { system: yes, name: root }
      - { name: s8weber, append: yes, groups: wheel, password: $auth_shadow_s8weber2 }

    auth_user_list3:
      - { name: s8weber, append: yes, groups: wheel, password: $auth_shadow_s8weber2 }
      - { system: yes, name: root }

  tasks:

    - user: 
      args: item
      with_items: auth_user_list1

    - name: 'this task should change the password but it dont!!!'
      user: 
      args: item
      with_items: auth_user_list2

    - name: 'this task with the items in a different order /fixed/ thie problem'
      user: 
      args: item
      with_items: auth_user_list3

    - user: name=s8weber password="$1$salty$NONE."
```

output

```
PLAY [auth] ******************************************************************* 

GATHERING FACTS *************************************************************** 
ok: [libdev.uwaterloo.ca]

TASK: [user ] ***************************************************************** 
changed: [libdev.uwaterloo.ca] => (item={'append': True, 'password': u'$1$salty$111111.', 'name': 's8weber', 'groups': 'wheel'})

TASK: [this task should change the password but it dont!!!] ******************* 
ok: [libdev.uwaterloo.ca] => (item={'system': True, 'name': 'root'})
ok: [libdev.uwaterloo.ca] => (item={'append': True, 'password': u'$1$salty$22222.', 'name': 's8weber', 'groups': 'wheel'})

TASK: [this task with the items in a different order /fixed/ thie problem] **** 
changed: [libdev.uwaterloo.ca] => (item={'append': True, 'password': u'$1$salty$22222.', 'name': 's8weber', 'groups': 'wheel'})
ok: [libdev.uwaterloo.ca] => (item={'system': True, 'name': 'root'})

TASK: [user name=s8weber password="$1$salty$NONE."] *************************** 
changed: [libdev.uwaterloo.ca]
```

It seems that args: is only evaluating the arg list once.  When it should be doing this for each item.

**Comment by mpdehaan** [comment]
This doesn't appear to have anything to do with with_items at all based on the output of the above statements.

Returning non-changed is expected for that one user because you specified the same password.

If you have questions, perhaps start a thread on the mailing list.

**Comment by steverweber** [comment]
I think you need to give this a second look.

Task#2 should change the password,,, but it dont.
Task#3 manages to change it only when the order is changed,

I didn't use the same password in all the tasks.
I only reused the same password on the 3rd task to show a point that the order of the auth_user_list items is important.

**Comment by steverweber** [comment]
Task#3 should be the task that has No change.  But this example play shows Task#2 didnt do the job.

**Comment by mpdehaan** [comment]
You need to pass the update_password=yes flag to change the password if you
do not want to just set it for new users.

**Comment by steverweber** [comment]
update_password defaults to always

**Comment by lberruti** [comment]
It seems a problem with "with_items" and "args":

```
# vars:
link_list:
  - { src: /etc/fstab, dest: /tmp/1, state: link }
  - { src: /etc/hosts, dest: /tmp/2, state: link }
  - { src: /etc/hostname, dest: /tmp/3, state: link }
  - { src: /etc/resolv.conf, dest: /tmp/4, state: link }
# tasks:
- file:
  args: item
  with_items: link_list
```

only the first item is executed (changed), other ones are always listed ok (and links are not created):

```
TASK: [file ] *****************************************************************
changed: [deb7.inter.nos] => (item={'dest': '/tmp/1', 'src': '/etc/fstab', 'state': 'link'})
ok: [deb7.inter.nos] => (item={'dest': '/tmp/2', 'src': '/etc/hosts', 'state': 'link'})
ok: [deb7.inter.nos] => (item={'dest': '/tmp/3', 'src': '/etc/hostname', 'state': 'link'})
ok: [deb7.inter.nos] => (item={'dest': '/tmp/4', 'src': '/etc/resolv.conf', 'state': 'link'})
```
