### ISSUE TITLE
set_fact won't update a fact while looping (breaking change)

### ISSUE THREAD

**Issue by willthames** [ansible/ansible#38075]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
set_fact

##### ANSIBLE VERSION
```
ansible 2.6.0 (devel a19a21d715) last updated 2018/03/29 10:44:45 (GMT +1000)
  config file = /home/will/src/xvt-dpe-cloud-infrastructure-stream2/ansible.cfg
  configured module search path = [u'/home/will/src/xvt-dpe-cloud-infrastructure-stream2/library']
  ansible python module location = /home/will/src/ansible/lib/ansible
  executable location = /home/will/src/ansible/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

set_fact no longer seems able to update a fact while looping. This might no longer be desired behaviour but should be noted in a porting guide with an alternative approach.

This change of behaviour was introduced in 3bec76fc856

##### STEPS TO REPRODUCE

```yaml
- hosts: host-in-multiple-groups
  connection: local
  gather_facts: no

  tasks:
  - set_fact:
      host_groups: "{{ (host_groups | default([])) + [item.key] }}"
    with_dict: "{{ groups }}"
    when: ansible_host in item.value

  - debug:
      var: host_groups

```

##### EXPECTED RESULTS
host_groups contains a list of all the groups containing the host

##### ACTUAL RESULTS
host_groups contains the last group in the list of groups containing the host
