### ISSUE TITLE
Mount not support nfs4 after upgrading ansible

### ISSUE THREAD

**Issue by BigBen8** [ansible/ansible#38089]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

mount

##### ANSIBLE VERSION

```
2.5
```
![image](https://user-images.githubusercontent.com/28532554/38082205-45a9f134-3346-11e8-8656-d37cde790540.png)

##### CONFIGURATION

CACHE_PLUGIN(/home/centos/dbe-devops/ansible.cfg) = redis
CACHE_PLUGIN_CONNECTION(/home/centos/dbe-devops/ansible.cfg) = localhost:6379:0
CACHE_PLUGIN_TIMEOUT(/home/centos/dbe-devops/ansible.cfg) = 3600
DEFAULT_FILTER_PLUGIN_PATH(/home/centos/dbe-devops/ansible.cfg) = [u'/home/centos/dbe-devops/plugins/filters']
DEFAULT_HOST_LIST(/home/centos/dbe-devops/ansible.cfg) = [u'/home/centos/dbe-devops/environments/inventory']
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/centos/dbe-devops/ansible.cfg) = True
DEFAULT_LOCAL_TMP(/home/centos/dbe-devops/ansible.cfg) = /home/centos/.ansible/tmp/ansible-local-6632o7gKtb
DEFAULT_LOG_PATH(/home/centos/dbe-devops/ansible.cfg) = /home/centos/dbe-devops/portal/logs/ansible.log
DEFAULT_PRIVATE_KEY_FILE(/home/centos/dbe-devops/ansible.cfg) = xxx.pem
DEFAULT_REMOTE_USER(/home/centos/dbe-devops/ansible.cfg) = ansible
DEFAULT_TIMEOUT(/home/centos/dbe-devops/ansible.cfg) = 60
HOST_KEY_CHECKING(/home/centos/dbe-devops/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/centos/dbe-devops/ansible.cfg) = False

##### OS / ENVIRONMENT

CentOS7

##### SUMMARY

After upgrading ansible to 2.5 we get an error mounting amazon efs shares 
![image](https://user-images.githubusercontent.com/28532554/38082350-b0337fa2-3346-11e8-9476-fe4ed4af5f7d.png)

Installing 2.6 (devel) and trying with the same result.

Going back to 2.4 solved the issue but 2.5 is needed because of efs encryption

##### STEPS TO REPRODUCE

```yaml

- hosts: <linux host>
  gather_facts: TRUE
  become: TRUE
  vars:
   mounts:
    mount04:
      path: "/var/app/twix16/data"
      src: <some efs source>
      fstype: nfs4
      fs_opts: ""
      mount_opts: nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev
      owner: <some user>
      group: <some group>
      passno: 2
      state: mounted

  tasks:

  - name: create directories
    file:
      path: "{{ item.value.path }}"
      owner: "{{ item.value.owner }}"
      group: "{{ item.value.group }}"
      state: directory
    with_dict: "{{ mounts }}"
    when: mounts is defined

  - name: make filesystem on logical volume
    filesystem:
      fstype: "{{ item.value.fstype }}"
      dev: "{{ item.value.src }}"
      opts: "{{ item.value.fs_opts }}"
    when: item.value.fstype != "nfs4"
    with_dict: "{{ mounts }}"
    when: mounts is defined

  - name: mount volumes
    mount:
      path: "{{ item.value.path }}"
      src: "{{ item.value.src}}"
      fstype: "{{ item.value.fstype}}"
      opts: "{{ item.value.mount_opts }}"
      passno: "{{ item.value.passno }}"
      state: "{{ item.value.state }}"
    with_dict: "{{ mounts }}"
    when:  mounts is defined

  - name: correct owner ship after mount
    file:
      path: "{{ item.value.path }}"
      owner: "{{ item.value.owner }}"
      group: "{{ item.value.group }}"
      state: directory
    with_dict: "{{ mounts }}"
    when: mounts is defined
```

##### EXPECTED RESULTS

create directory /var/app/twix16/data
and mount the efs share

##### ACTUAL RESULTS

```
 [WARNING]: While constructing a mapping from /home/centos/dbe-devops/connect_linux.yml, line 28, column 5, found a duplicate dict key (when). Using last defined value only.


PLAY [localhost] **********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************************************************************************************
ok: [localhost]

TASK [create directories] *************************************************************************************************************************************************************************************
changed: [localhost] => (item={'value': {u'src': u'efs-dbe.dbe-test.comp.db.de:/', u'group': u'centos', u'passno': 2, u'fstype': u'nfs4', u'fs_opts': u'', u'state': u'mounted', u'mount_opts': u'nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev', u'owner': u'centos', u'path': u'/var/app/twix16/data'}, 'key': u'mount04'})

TASK [make filesystem on logical volume] **********************************************************************************************************************************************************************
failed: [localhost] (item={'value': {u'src': u'efs-dbe.dbe-test.comp.db.de:/', u'group': u'centos', u'passno': 2, u'fstype': u'nfs4', u'fs_opts': u'', u'state': u'mounted', u'mount_opts': u'nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev', u'owner': u'centos', u'path': u'/var/app/twix16/data'}, 'key': u'mount04'}) => {"changed": false, "item": {"key": "mount04", "value": {"fs_opts": "", "fstype": "nfs4", "group": "centos", "mount_opts": "nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev", "owner": "centos", "passno": 2, "path": "/var/app/twix16/data", "src": "efs-dbe.dbe-test.comp.db.de:/", "state": "mounted"}}, "msg": "value of fstype must be one of: ext4, ext3, ext2, btrfs, vfat, ext4dev, reiserfs, lvm, xfs, got: nfs4"}

PLAY RECAP ****************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1
```
