### ISSUE TITLE
ansible-config ignore plugins parameters

### ISSUE THREAD

**Issue by pilou-** [ansible/ansible#38100]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-config

##### ANSIBLE VERSION
```
devel
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

`ansible-config list` and `ansible-config dump` commands ignore plugins parameters.

##### STEPS TO REPRODUCE
Parameters of `kubectl` connection plugin aren't displayed:
```
$ ansible-config list | grep -i kubectl
```
or
```
$ ansible-config dump | grep -i kubectl
```

##### EXPECTED RESULTS
`ansible-config list` and `ansible-config dump` should include plugins parameters.

##### ACTUAL RESULTS

`ansible-config list` and `ansible-config dump` don't display plugins parameters.

**Comment by ansibot** [comment]
Files identified in the description:
* [bin/ansible-config](https://github.com/ansible/ansible/blob/devel/bin/ansible-config)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pilou-** [comment]
I am willing to fix that but what should be the behavior ? Should `ansible-config` always display plugins parameters ? Or should a new switch (`--plugin-type`) be added ? Should plugin type and name be mentioned for each plugin parameter ? Should uppercase be used for parameter names ? In the samples below, a 'regular' parameter (`DEFAULT_FORKS`) and a plugin parameter (`oc_cert_file`) are displayed:

  ```yaml
  DEFAULT_FORKS:
    default: 5
    description: Maximum number of forks Ansible will use to execute tasks on target
    hosts.
    env:
    - {name: ANSIBLE_FORKS}
    ini:
    - {key: forks, section: defaults}
    name: Number of task forks
    type: integer
  oc_cert_file:
    default: ''
    description: [Path to a certificate used to authenticate with the API.]
    env:
    - {name: K8S_AUTH_CERT_FILE}
    vars:
    - {name: ansible_oc_cert_file}
  ```
  Uppercase used for parameter name:
  ```yaml
  DEFAULT_FORKS:
    default: 5
    description: Maximum number of forks Ansible will use to execute tasks on target
    hosts.
    env:
    - {name: ANSIBLE_FORKS}
    ini:
    - {key: forks, section: defaults}
    name: Number of task forks
    type: integer
  OC_CERT_FILE:
    default: ''
    description: [Path to a certificate used to authenticate with the API.]
    env:
    - {name: K8S_AUTH_CERT_FILE}
    vars:
    - {name: ansible_oc_cert_file}
  ```
  Plugin type and name added:
  ```yaml
  DEFAULT_FORKS:
    default: 5
    description: Maximum number of forks Ansible will use to execute tasks on target
    hosts.
    env:
    - {name: ANSIBLE_FORKS}
    ini:
    - {key: forks, section: defaults}
    name: Number of task forks
    type: integer
  oc_cert_file:
    plugin_type: connection
    plugin_name: oc
    default: ''
    description: [Path to a certificate used to authenticate with the API.]
    env:
    - {name: K8S_AUTH_CERT_FILE}
    vars:
    - {name: ansible_oc_cert_file}
  ```
