### ISSUE TITLE
postgresql_user module: task is always changed when use conn_limit parameter

### ISSUE THREAD

**Issue by fridlik** [ansible/ansible#38118]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

postgresql_user module

##### ANSIBLE VERSION

```
2.4.3.0
```

##### SUMMARY

When I use _conn_limit_ parameter in this module, the task is always changed.

##### STEPS TO REPRODUCE

```yaml
- name: create replication user
  postgresql_user:
    name: '{{ replication.user }}'
    conn_limit: 2
```

##### HOW TO RESOLVE
The problem is on this line: https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/postgresql/postgresql_user.py#L356

The solution is to retype conn_limit to int
```
conn_limit_changing = (conn_limit is not None and int(conn_limit) != current_role_attrs['rolconnlimit'])
```
