### ISSUE TITLE
include_role only includes one item from list

### ISSUE THREAD

**Issue by tim-moody** [ansible/ansible#38128]
##### ISSUE TYPE
 - Bug Report
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /opt/iiab/iiab/ansible.cfg
  configured module search path = [u'/usr/share/ansible']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```

##### SUMMARY
In the code below I expected a list of roles to be included and only one was.

##### STEPS TO REPRODUCE

```
---
- hosts: all
  become: yes

  vars:
    role_list: ["kiwix", "kalite"]

  vars_files:
  - vars/default_vars.yml
  - vars/{{ ansible_local.local_facts.os_ver }}.yml
  - vars/local_vars.yml
  - /etc/iiab/config_vars.yml

  tasks:
  - name: Run Roles
    include_role:
      name: "{{ item }}"
    loop: "{{ role_list }}"

ansible-playbook -i ansible_hosts runroles.yml --connection=local
```

##### EXPECTED RESULTS
both kiwix and kalite roles are executed

##### ACTUAL RESULTS
only role kalite is executed
