### ISSUE TITLE
aws_ec2 inventory plugin not following groups rule

### ISSUE THREAD

**Issue by strus38** [ansible/ansible#38139]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

aws_ec2

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/ec2-user/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

INVENTORY_ENABLED(/home/ec2-user/ansible.cfg) = ['aws_ec2', 'constructed']

##### OS / ENVIRONMENT

Linux ip-10-xxx.xxx 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

Using the new inventory plugin for ec2, and trying to build dynamic groups from it based on some specific tags do not seem to work (or the doc is not correct).
No groups are created based on the 'groups' using:
groups:
    ansible-java: "'ansible-java' in (ec2_tags|list)"

##### STEPS TO REPRODUCE

command:
```ansible-inventory -i inventory/test.aws_ec2.yml --list```

```yaml
plugin: aws_ec2
regions: # populate inventory with instances in these regions
    - eu-west-1
filters:
    instance-state-name: running

compose:
    var_sum: var1 + var2
    server_type: "ansible_hostname | regex_replace ('(.{6})(.{2}).*', '\\2')"

groups:
    ansible-java: "'ansible-java' in (ec2_tags|list)"

strict: False
keyed_groups:
    - prefix: arch
      key: 'architecture'
      value:
          'x86_64'
    - prefix: distro
      key: 'ansible_distribution'
```

Actual output

```json
{
    "_meta": {
        "hostvars": {
            "ec2-5xxxxxxx.eu-west-1.compute.amazonaws.com": {
                "ami_launch_index": 0, 
                "architecture": "x86_64", 
                ...
                "tags": {
                    "Name": "ping-cm", 
                    "ansible-java": "ansible-java"
                }, 
                ....
            }
        }
    }, 
    "all": {
        "children": [
            "arch_x86_64", 
            "aws_ec2", 
            "ungrouped"
        ]
    }, 
    "arch_x86_64": {
        "hosts": [
            "ec2-xxxxx.eu-west-1.compute.amazonaws.com"
        ]
    }, 
    "aws_ec2": {
        "hosts": [
            "ec2-xxxx.eu-west-1.compute.amazonaws.com"
        ]
    }, 
    "ungrouped": {}
}
```

##### EXPECTED RESULTS

I expected a group for the selected tag:

```json
...
"ansible-java": {
        "hosts": [
            "ec2-xxxx.eu-west-1.compute.amazonaws.com"
        ]
    }, 
...
```
##### ACTUAL RESULTS

```
ansible-inventory 2.5.0
  config file = /home/ec2-user/ansible.cfg
  configured module search path = [u'/home/ec2-user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-inventory
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /home/ec2-user/ansible.cfg as config file
setting up inventory plugins
Parsed /home/ec2-user/inventory/test.aws_ec2.yml inventory source with aws_ec2 plugin
```

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/inventory/aws_ec2.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/aws_ec2.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by strus38** [comment]
Ok, I find out how to achieve what I needed. IT would be good to add this example in the documentation since it is not so obvious.

Tag your EC2 instances like this:
```json
     "tags": {
               "Name": "ping-cm", 
               "ansible-java": "java-servers"
       }, 
```
write your config file like this:

```yaml
plugin: aws_ec2
regions: # populate inventory with instances in these regions
    - eu-west-1
filters:
    instance-state-name: running

strict: False
keyed_groups:
    - prefix: arch
      key: architecture
      value:
          'x86_64'
    - prefix: distro
      key: ansible_distribution
    - prefix: tag
      key: tags['ansible-java']
      value:
          'ansible-java': 'java-servers'
```

and you will get:

```json
"all": {
        "children": [
            "arch_x86_64", 
            "aws_ec2", 
            "tag_java_servers", 
            "ungrouped"
        ]
    }, 
    "arch_x86_64": {
        "hosts": [
            "ec2-xxx.eu-west-1.compute.amazonaws.com"
        ]
    }, 
    "aws_ec2": {
        "hosts": [
            "ec2-xxx.eu-west-1.compute.amazonaws.com"
        ]
    }, 
    "tag_java_servers": {
        "hosts": [
            "ec2-xxx.eu-west-1.compute.amazonaws.com"
        ]
    }, 
    "ungrouped": {}
```

Brilliant :-)
