### ISSUE TITLE
vmware_guest not connecting networks at poweron

### ISSUE THREAD

**Issue by junglie85** [ansible/ansible#38143]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = ['/Users/ashley/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ashley/Development/k8s/typhoon-vsphere/venv/lib/python3.6/site-packages/ansible
  executable location = /Users/ashley/Development/k8s/typhoon-vsphere/venv/bin/ansible
  python version = 3.6.4 (default, Mar  1 2018, 18:36:50) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

Nothing

##### OS / ENVIRONMENT

macOS 10.13.3, trying to provision Ubuntu Bionic beta guest VM on vSphere ESXi 6.5.

##### SUMMARY

Does not connect network interfaces when VM is powered on. Need to manually connect networks via vCenter web UI.

##### STEPS TO REPRODUCE

```yaml
- name: PROVISION | Create a VM folder in {{ vcenter_datacenter }} datacenter
  vcenter_folder:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    folder_name: "{{ bastion_vm_name }}"
    folder_type: vm
    state: present
  register: vm_folder_creation_result
  delegate_to: localhost

- name: PROVISION | Clone a VM from Ubuntu 18 template
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ bastion_vm_name }}"
    resource_pool: "{{ vcenter_resource_pool }}"
    name: "{{ bastion_vm_name }}"
    template: "{{ bastion_vm_template }}"
    networks:
    - name: "{{ external_network_name }}"
      type: static
      ip: "{{ external_bastion_ip }}"
      netmask: 255.255.255.0
      mac: "{{ external_bastion_mac }}"
      start_connected: true
    - name: "{{ internal_network_name }}"
      type: static
      ip: "{{ internal_bastion_ip }}"
      netmask: 255.255.255.0
      mac: "{{ internal_bastion_mac }}"
      start_connected: true
    state: present
    # wait_for_ip_address: yes
  register: bastion_facts
  delegate_to: localhost

- name: PROVISION | Power on the {{ bastion_vm_name }} VM
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ bastion_vm_name }}"
    resource_pool: "{{ vcenter_resource_pool }}"
    name: "{{ bastion_vm_name }}"
    state: poweredon
    wait_for_ip_address: yes
  # register: bastion_facts
  delegate_to: localhost

- debug:
    var: bastion_facts
```

##### EXPECTED RESULTS

I expected a VM to power on and be connected to its networks

##### ACTUAL RESULTS

VM powers on but networks are not connected.

```
ansible-playbook 2.5.0
  config file = None
  configured module search path = ['/Users/ashley/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ashley/Development/k8s/typhoon-vsphere/venv/lib/python3.6/site-packages/ansible
  executable location = /Users/ashley/Development/k8s/typhoon-vsphere/venv/bin/ansible-playbook
  python version = 3.6.4 (default, Mar  1 2018, 18:36:50) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
No config file found; using defaults
setting up inventory plugins
Parsed /Users/ashley/Development/k8s/typhoon-vsphere/inventory/cluster.yml inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /Users/ashley/Development/k8s/typhoon-vsphere/venv/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: cluster.yml *************************************************************************************************
1 plays in cluster.yml

PLAY [bastion] ********************************************************************************************************
META: ran handlers

TASK [vsphere/provision : PROVISION | Create a VM folder in datacenter1 datacenter] *************************************
task path: /Users/ashley/Development/k8s/typhoon-vsphere/roles/vsphere/provision/tasks/main.yml:3
Using module file /Users/ashley/Development/k8s/typhoon-vsphere/venv/lib/python3.6/site-packages/ansible/modules/cloud/vmware/vcenter_folder.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ashley
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/ashley/.ansible/tmp/ansible-tmp-1522422788.214359-127998515688966 `" && echo ansible-tmp-1522422788.214359-127998515688966="` echo /Users/ashley/.ansible/tmp/ansible-tmp-1522422788.214359-127998515688966 `" ) && sleep 0'
<localhost> PUT /Users/ashley/.ansible/tmp/ansible-local-66072f8uk779u/tmpmtd1ad8v TO /Users/ashley/.ansible/tmp/ansible-tmp-1522422788.214359-127998515688966/vcenter_folder.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/ashley/.ansible/tmp/ansible-tmp-1522422788.214359-127998515688966/ /Users/ashley/.ansible/tmp/ansible-tmp-1522422788.214359-127998515688966/vcenter_folder.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Users/ashley/Development/k8s/typhoon-vsphere/venv/bin/python /Users/ashley/.ansible/tmp/ansible-tmp-1522422788.214359-127998515688966/vcenter_folder.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/ashley/.ansible/tmp/ansible-tmp-1522422788.214359-127998515688966/ > /dev/null 2>&1 && sleep 0'
ok: [192.168.160.2 -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "datacenter": "datacenter1",
            "folder_name": "typhoon-bastion",
            "folder_type": "vm",
            "hostname": "vc.vsphere.local",
            "parent_folder": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "ashley.bye@outlook.com",
            "validate_certs": false
        }
    },
    "result": "Failed to create folder as another object has same name in the same target folder : The name 'typhoon-bastion' already exists."
}

TASK [vsphere/provision : PROVISION | Clone a VM from Ubuntu 18 template] *********************************************
task path: /Users/ashley/Development/k8s/typhoon-vsphere/roles/vsphere/provision/tasks/main.yml:16
Using module file /Users/ashley/Development/k8s/typhoon-vsphere/venv/lib/python3.6/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ashley
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/ashley/.ansible/tmp/ansible-tmp-1522422790.147404-159235283035236 `" && echo ansible-tmp-1522422790.147404-159235283035236="` echo /Users/ashley/.ansible/tmp/ansible-tmp-1522422790.147404-159235283035236 `" ) && sleep 0'
<localhost> PUT /Users/ashley/.ansible/tmp/ansible-local-66072f8uk779u/tmpbv5wg64a TO /Users/ashley/.ansible/tmp/ansible-tmp-1522422790.147404-159235283035236/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/ashley/.ansible/tmp/ansible-tmp-1522422790.147404-159235283035236/ /Users/ashley/.ansible/tmp/ansible-tmp-1522422790.147404-159235283035236/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Users/ashley/Development/k8s/typhoon-vsphere/venv/bin/python /Users/ashley/.ansible/tmp/ansible-tmp-1522422790.147404-159235283035236/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/ashley/.ansible/tmp/ansible-tmp-1522422790.147404-159235283035236/ > /dev/null 2>&1 && sleep 0'
changed: [192.168.160.2 -> localhost] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "10304",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "vsanDatastore"
        ],
        "hw_esxi_host": "host1.vsphere.local",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": [],
            "label": "Network adapter 1",
            "macaddress": "00:50:56:84:b7:a4",
            "macaddress_dash": "00-50-56-84-b7-a4",
            "summary": "DVSwitch: 50 04 eb c6 53 2a 88 3c-07 3d b1 67 e7 35 89 e4"
        },
        "hw_eth1": {
            "addresstype": "assigned",
            "ipaddresses": [],
            "label": "Network adapter 2",
            "macaddress": "00:50:56:84:ae:ac",
            "macaddress_dash": "00-50-56-84-ae-ac",
            "summary": "DVSwitch: 50 04 eb c6 53 2a 88 3c-07 3d b1 67 e7 35 89 e4"
        },
        "hw_files": [
            "[vsanDatastore] fb52be5a-d2c8-e554-7e61-7845c4f90b9c/typhoon-bastion.vmx",
            "[vsanDatastore] fb52be5a-d2c8-e554-7e61-7845c4f90b9c/typhoon-bastion.nvram",
            "[vsanDatastore] fb52be5a-d2c8-e554-7e61-7845c4f90b9c/typhoon-bastion.vmsd",
            "[vsanDatastore] fb52be5a-d2c8-e554-7e61-7845c4f90b9c/typhoon-bastion.vmdk"
        ],
        "hw_folder": "/datacenter1/vm/typhoon-bastion",
        "hw_guest_full_name": "Ubuntu Linux (64-bit)",
        "hw_guest_ha_state": true,
        "hw_guest_id": "ubuntu64Guest",
        "hw_interfaces": [
            "eth0",
            "eth1"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 4096,
        "hw_name": "typhoon-bastion",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 2,
        "hw_product_uuid": "420499ce-d449-3ae3-2e86-14d284753b5e",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": "cluster1",
            "customization": {},
            "customvalues": [],
            "datacenter": "datacenter1",
            "disk": [],
            "esxi_hostname": null,
            "folder": "typhoon-bastion",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "vc.vsphere.local",
            "is_template": false,
            "linked_clone": false,
            "name": "typhoon-bastion",
            "name_match": "first",
            "networks": [
                {
                    "ip": "192.168.160.2",
                    "mac": "00:50:56:84:c7:43",
                    "name": "guest-network",
                    "netmask": "255.255.255.0",
                    "start_connected": true,
                    "type": "static"
                },
                {
                    "ip": "10.240.0.241",
                    "mac": "00:50:56:84:9f:bb",
                    "name": "k8s-network",
                    "netmask": "255.255.255.0",
                    "start_connected": true,
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": "Ashley-RP",
            "snapshot_src": null,
            "state": "present",
            "template": "bionic-2CPU-4GB-30GB",
            "username": "ashley.bye@outlook.com",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}

TASK [vsphere/provision : PROVISION | Power on the typhoon-bastion VM] ************************************************
task path: /Users/ashley/Development/k8s/typhoon-vsphere/roles/vsphere/provision/tasks/main.yml:46
Using module file /Users/ashley/Development/k8s/typhoon-vsphere/venv/lib/python3.6/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ashley
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/ashley/.ansible/tmp/ansible-tmp-1522422796.4871511-50228362046361 `" && echo ansible-tmp-1522422796.4871511-50228362046361="` echo /Users/ashley/.ansible/tmp/ansible-tmp-1522422796.4871511-50228362046361 `" ) && sleep 0'
<localhost> PUT /Users/ashley/.ansible/tmp/ansible-local-66072f8uk779u/tmpq3lz8ov_ TO /Users/ashley/.ansible/tmp/ansible-tmp-1522422796.4871511-50228362046361/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/ashley/.ansible/tmp/ansible-tmp-1522422796.4871511-50228362046361/ /Users/ashley/.ansible/tmp/ansible-tmp-1522422796.4871511-50228362046361/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/Users/ashley/Development/k8s/typhoon-vsphere/venv/bin/python /Users/ashley/.ansible/tmp/ansible-tmp-1522422796.4871511-50228362046361/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/ashley/.ansible/tmp/ansible-tmp-1522422796.4871511-50228362046361/ > /dev/null 2>&1 && sleep 0'
ok: [192.168.160.2 -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": "cluster1",
            "customization": {},
            "customvalues": [],
            "datacenter": "datacenter1",
            "disk": [],
            "esxi_hostname": null,
            "folder": "typhoon-bastion",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "vc.vsphere.local",
            "is_template": false,
            "linked_clone": false,
            "name": "typhoon-bastion",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": "Ashley-RP",
            "snapshot_src": null,
            "state": "poweredon",
            "template": null,
            "username": "ashley.bye@outlook.com",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    }
}

TASK [vsphere/provision : debug] **************************************************************************************
task path: /Users/ashley/Development/k8s/typhoon-vsphere/roles/vsphere/provision/tasks/main.yml:62
ok: [192.168.160.2] => {
    "bastion_facts": {
        "changed": true,
        "failed": false,
        "instance": {
            "annotation": "",
            "current_snapshot": null,
            "customvalues": {},
            "guest_consolidation_needed": false,
            "guest_question": null,
            "guest_tools_status": "guestToolsRunning",
            "guest_tools_version": "10304",
            "hw_cores_per_socket": 1,
            "hw_datastores": [
                "vsanDatastore"
            ],
            "hw_esxi_host": "host1.vsphere.local",
            "hw_eth0": {
                "addresstype": "assigned",
                "ipaddresses": [],
                "label": "Network adapter 1",
                "macaddress": "00:50:56:84:b7:a4",
                "macaddress_dash": "00-50-56-84-b7-a4",
                "summary": "DVSwitch: 50 04 eb c6 53 2a 88 3c-07 3d b1 67 e7 35 89 e4"
            },
            "hw_eth1": {
                "addresstype": "assigned",
                "ipaddresses": [],
                "label": "Network adapter 2",
                "macaddress": "00:50:56:84:ae:ac",
                "macaddress_dash": "00-50-56-84-ae-ac",
                "summary": "DVSwitch: 50 04 eb c6 53 2a 88 3c-07 3d b1 67 e7 35 89 e4"
            },
            "hw_files": [
                "[vsanDatastore] fb52be5a-d2c8-e554-7e61-7845c4f90b9c/typhoon-bastion.vmx",
                "[vsanDatastore] fb52be5a-d2c8-e554-7e61-7845c4f90b9c/typhoon-bastion.nvram",
                "[vsanDatastore] fb52be5a-d2c8-e554-7e61-7845c4f90b9c/typhoon-bastion.vmsd",
                "[vsanDatastore] fb52be5a-d2c8-e554-7e61-7845c4f90b9c/typhoon-bastion.vmdk"
            ],
            "hw_folder": "/datacenter1/vm/typhoon-bastion",
            "hw_guest_full_name": "Ubuntu Linux (64-bit)",
            "hw_guest_ha_state": true,
            "hw_guest_id": "ubuntu64Guest",
            "hw_interfaces": [
                "eth0",
                "eth1"
            ],
            "hw_is_template": false,
            "hw_memtotal_mb": 4096,
            "hw_name": "typhoon-bastion",
            "hw_power_status": "poweredOn",
            "hw_processor_count": 2,
            "hw_product_uuid": "420499ce-d449-3ae3-2e86-14d284753b5e",
            "ipv4": null,
            "ipv6": null,
            "module_hw": true,
            "snapshots": []
        }
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by junglie85** [comment]
By way of update, cloning a VM from a template in one task and then making changes to the network and powering on in a second task allows the network to connect at start. However, the MAC addresses do not get their manual setting and resort to the vSphere automatic option.

```
- name: PROVISION | Clone {{ bastion_vm_name }} from {{ bastion_vm_template }}
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "/"
    resource_pool: "{{ vcenter_resource_pool }}"
    name: "{{ bastion_vm_name }}"
    template: "{{ bastion_vm_template }}"
    state: present
  delegate_to: localhost

- name: PROVISION | Power on {{ bastion_vm_name }}
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ bastion_vm_name }}"
    resource_pool: "{{ vcenter_resource_pool }}"
    name: "{{ bastion_vm_name }}"
    networks:
    - name: "{{ external_network_name }}"
      type: dhcp
      mac: "{{ external_bastion_mac }}"
      start_connected: true
    - name: "{{ internal_network_name }}"
      type: dhcp
      mac: "{{ internal_bastion_mac }}"
      start_connected: true
    state: poweredon
    wait_for_ip_address: yes
  delegate_to: localhost
```

**Comment by Akasurde** [comment]
@AshleyByeUK Did you re-run the last playbook with same VM name ? 

`state: poweredon` will only change powerstate of VM if VM already exists, it does not change any hardware related changes.

needs_info

**Comment by junglie85** [comment]
Thanks. I guess the problem is in the cloning task then.

**Comment by junglie85** [comment]
Tried this with a VM with no NIC's configured in the template (a suggestion in another issue, can't remember the number nor find it now, sorry) and the network interfaces are still not being connected after cloning from a template.

```
---
- name: Get facts
  vmware_guest_facts:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vcenter_vm_prefix }}{{ inventory_hostname }}"
  register: vsphere_facts
  failed_when: vsphere_facts.changed == true
  delegate_to: localhost

- name: Provision {{ inventory_hostname }}
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: "{{ vcenter_validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "/"
    resource_pool: "{{ vcenter_resource_pool }}"
    name: "{{ vcenter_vm_prefix }}{{ inventory_hostname }}"
    template: "{{ vcenter_vm_template }}"
    networks:
    - name: "{{ vcenter_external_network }}"
      type: static
      ip: "{{ ansible_host }}"
      netmask: 255.255.255.0
      start_connected: true
    - name: "{{ vcenter_internal_network }}"
      type: static
      ip: "{{ internal_ip }}"
      netmask: 255.255.255.0
      start_connected: true
    state: present
  register: vm_facts
  when: vsphere_facts.instance is not defined
  delegate_to: localhost
```

And here are the `vm_facts`:

```
ok: [bastion] => {
    "vm_facts": {
        "changed": true,
        "failed": false,
        "instance": {
            "annotation": "",
            "current_snapshot": null,
            "customvalues": {},
            "guest_consolidation_needed": false,
            "guest_question": null,
            "guest_tools_status": "guestToolsNotRunning",
            "guest_tools_version": "10304",
            "hw_cores_per_socket": 1,
            "hw_datastores": [
                "vsanDatastore"
            ],
            "hw_esxi_host": "host.outerrim.vsphere.company.net",
            "hw_eth0": {
                "addresstype": "assigned",
                "ipaddresses": null,
                "label": "Network adapter 1",
                "macaddress": "00:50:56:84:16:3c",
                "macaddress_dash": "00-50-56-84-16-3c",
                "summary": "DVSwitch: 50 04 eb c6 53 2a 88 3c-07 3d b1 67 e7 35 89 e4"
            },
            "hw_eth1": {
                "addresstype": "assigned",
                "ipaddresses": null,
                "label": "Network adapter 2",
                "macaddress": "00:50:56:84:80:46",
                "macaddress_dash": "00-50-56-84-80-46",
                "summary": "DVSwitch: 50 04 eb c6 53 2a 88 3c-07 3d b1 67 e7 35 89 e4"
            },
            "hw_files": [
                "[vsanDatastore] ad51ca5a-76f8-41cf-3c1c-7845c4f90b9c/ash-k8s-bastion.vmx",
                "[vsanDatastore] ad51ca5a-76f8-41cf-3c1c-7845c4f90b9c/ash-k8s-bastion.vmsd",
                "[vsanDatastore] ad51ca5a-76f8-41cf-3c1c-7845c4f90b9c/ash-k8s-bastion.vmdk"
            ],
            "hw_folder": "/Outer Rim/vm",
            "hw_guest_full_name": null,
            "hw_guest_ha_state": null,
            "hw_guest_id": null,
            "hw_interfaces": [
                "eth0",
                "eth1"
            ],
            "hw_is_template": false,
            "hw_memtotal_mb": 4096,
            "hw_name": "ash-k8s-bastion",
            "hw_power_status": "poweredOff",
            "hw_processor_count": 1,
            "hw_product_uuid": "42043e6f-d6d7-6078-3efe-e925b5489c8c",
            "ipv4": null,
            "ipv6": null,
            "module_hw": true,
            "snapshots": []
        }
    }
}
```

Any ideas what's going on?
