### ISSUE TITLE
Ansible 2.5: azure_rm_loadbalancer_facts module requires the packaging module even if it is installed

### ISSUE THREAD

**Issue by IvanovOleg** [ansible/ansible#38141]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_loadbalancer_facts

##### ANSIBLE VERSION

```
2.5.0
```

##### OS / ENVIRONMENT

Centos 7, pip install ansible[azure]
##### STEPS TO REPRODUCE

Use

```
- name: Get loadbalancer facts
  azure_rm_loadbalancer_facts:
    name: "{{ load_balancer_name }}"
    resource_group: "{{ resource_group_name }}"
  register: lb_info
  when: load_balancer_name is defined
```

##### EXPECTED RESULTS

Get load balancer facts

##### ACTUAL RESULTS

error

```
fatal: [hostname]: FAILED! => {"changed": false, "msg": "Do you have packaging installed? Try `pip install packaging`- No module named packaging.version"}

```
