### ISSUE TITLE
rds_subnet_group subnets invalid input?

### ISSUE THREAD

**Issue by johnscancella** [ansible/ansible#38147]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rds_subnet_group

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /Users/jscancella/development/repos/chronam-deployment/ansible.cfg
  configured module search path = [u'/Users/jscancella/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/Users/jscancella/development/repos/chronam-deployment/ansible.cfg) = True
DEFAULT_TIMEOUT(/Users/jscancella/development/repos/chronam-deployment/ansible.cfg) = 30
HOST_KEY_CHECKING(/Users/jscancella/development/repos/chronam-deployment/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/jscancella/development/repos/chronam-deployment/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Mac os 10.13.3

##### SUMMARY
passing in list variable to subnets results in error

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  vars:
    ec2_subnet_ids: ["subnet-26ab606c", "subnet-c021269d", "subnet-e3e6fe87", "subnet-4492946b", "subnet-f34175cc", "subnet-082a8307"]
  tasks:
    - name: create rds stage subnet
      rds_subnet_group:
        region: "us-east-1"
        name: "chronam-stage-vpc"
        state: present
        subnets: ec2_subnet_ids
        description: "chronam database vpc for stage"
```

##### EXPECTED RESULTS
`chronam-stage-vpc` rds subgroup is created with all ec2 subnets listed

##### ACTUAL RESULTS
```
TASK [create rds stage subnet] **********************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Some input subnets in :[ec2_subnet_ids] are invalid."}
```
