### ISSUE TITLE
Ansible with_items loop doesn't work as intended

### ISSUE THREAD

**Issue by harekrishna0** [ansible/ansible#38154]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_config
ios_command

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /home/kneupane/ansible.cfg
  configured module search path = ['/Users/kneupane/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.4 (default, Jan 25 2018, 00:12:50) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
```
##### CONFIGURATION

HOST_KEY_CHECKING(/home/kneupane/ansible.cfg) = False

##### OS / ENVIRONMENT

Red Hat

##### SUMMARY

I have a variable list of syslog that needs to be configured on the ios device. I am planning to delete all the logging-host IPs that are not used from the device.

```yaml
---
# Purpose: Find and replace all syslog servers

- hosts: ios_devices
  gather_facts: no
  connection: local

  vars_prompt:
  -  name: "Username"
     prompt: "TACACS Username"
  -  name: "Password"
     prompt: "TACACS Password"

  tasks:

  - name: SYS | Define provider
    set_fact:
      provider:
        host: "{{ inventory_hostname }}"
        username: "{{ Username }}"
        password: "{{ Password }}"

  - name: Current Syslog servers
    ios_command:
      provider: "{{ provider }}"
      commands:
        - sh run | include logging host
    register: runconfsyslog

  - debug:
      var: runconfsyslog

  - name: Set Syslog servers
    when: "(item not in runconfsyslog.stdout)"
    with_items: "{{ syslog_server }}"
    register: setsyslogserver
    ios_config:
      provider: "{{ provider }}"
      lines:
        - "{{ item }}"

  - name: Remove the rest syslog servers
    with_items: "{{ runconfsyslog.stdout_lines }}"
    when: "(item not in syslog_server)"
    ios_config:
      provider: "{{ provider }}"
      lines:
        - "no {{ item }}"

Contents of group_vars/all.yml:
syslog_server:
- "logging host 192.168.1.1"
- "logging host 192.168.1.2"
- "logging host 192.168.1.3"
- "logging host 192.168.1.4"
```
When I try the same playbook for ntp servers, it works as expected but not on syslogs - all these ones gets deleted rather than comparing the ones in the switch itself.

##### STEPS TO REPRODUCE

```
ansible-playbook playbookname.yml -i hosts
```

##### EXPECTED RESULTS

logging host IP changed to only one provided in the variable file

##### ACTUAL RESULTS

Everything gets deleted.
