### ISSUE TITLE
Improvement in documentation on waiting for a long async task .

### ISSUE THREAD

**Issue by jobevers** [ansible/ansible#38164]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
http://docs.ansible.com/ansible/latest/user_guide/playbooks_async.html

##### ANSIBLE VERSION
2.5

##### SUMMARY
The docs say:

If you would like to perform a task asynchroniusly and check on it later you can perform a task similar to the following:
```
---
# Requires ansible 1.8+
- name: 'YUM - async task'
  yum:
    name: docker-io
    state: installed
  async: 1000
  poll: 0
  register: yum_sleeper

- name: 'YUM - check on async task'
  async_status:
    jid: "{{ yum_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 30
```

With a default delay of 5 seconds, the second task, the one that is checking, will only allow 150 seconds for the async task to complete. I think the values should be changed so that the async: 1000 matches up with retries * delay.  For example:

```
---
# Requires ansible 1.8+
- name: 'YUM - async task'
  yum:
    name: docker-io
    state: installed
  async: 1000
  poll: 0
  register: yum_sleeper

- name: 'YUM - check on async task'
  async_status:
    jid: "{{ yum_sleeper.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 100
  delay: 10
```
