### ISSUE TITLE
never tag does not show up with --list-tags

### ISSUE THREAD

**Issue by SimplySeth** [ansible/ansible#38176]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
lib/ansible/playbook/taggable.py
lib/ansible/playbook/base.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /Users/nunya/ecs_pipeline/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules', '/Users/nunya/ecs_pipeline/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Mar 30 2018, 06:42:10) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/Users/nunya/ecs_pipeline/ansible.cfg) = -o StrictHostKeyChecking=no -o ConnectTimeout=3 -o UserKnownHostsFile=/dev/null
DEFAULT_CALLBACK_WHITELIST(/Users/nunya/ecs_pipeline/ansible.cfg) = ['full_skip']
DEFAULT_HOST_LIST(/Users/nunya/ecs_pipeline/ansible.cfg) = ['/Users/nunya/ecs_pipeline/inventory']
DEFAULT_MANAGED_STR(/Users/nunya/ecs_pipeline/ansible.cfg) = "#############################
***      Ansible      ***
Modified on: %Y-%m-%d %H:%M:%S
By: {uid} on {host}
Using template: {file}
DEFAULT_MODULE_PATH(/Users/nunya/ecs_pipeline/ansible.cfg) = ['/usr/share/ansible/plugins/modules', '/Users/nunya/ecs_pipeline/library']
DEFAULT_ROLES_PATH(/Users/nunya/ecs_pipeline/ansible.cfg) = ['/Users/nunya/ecs_pipeline/roles']
DEFAULT_STDOUT_CALLBACK(/Users/nunya/ecs_pipeline/ansible.cfg) = full_skip
DEFAULT_VAULT_PASSWORD_FILE(/Users/nunya/ecs_pipeline/ansible.cfg) = /Users/nunya/ecs_pipeline/.vpw
HOST_KEY_CHECKING(/Users/nunya/ecs_pipeline/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/nunya/ecs_pipeline/ansible.cfg) = False
```
##### OS / ENVIRONMENT
MacOSX

##### SUMMARY
never tag hides other tags

##### STEPS TO REPRODUCE
attach `never` tag to a task
ansible-playbook playbook.yml --list-tags

```yaml
# --list-tags doesn't show 'container_definition' nor 'never' tag
- include_tasks: "container_definition.yml"
  tags:
    - container_definition
    - never
```

```yaml
# --list-tags shows 'container_definition'
- include_tasks: "container_definition.yml"
  tags:
    - container_definition
```

##### EXPECTED RESULTS
All tags including `container_definition` and `never` would show

##### ACTUAL RESULTS

`container_definition` tag does not show 
`never` tag does not show
```
ansible-playbook 2.5.0
  config file = /Users/reinose/ecs_pipeline/ansible.cfg
  configured module search path = ['/usr/share/ansible/plugins/modules', '/Users/reinose/ecs_pipeline/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.6.5 (default, Mar 30 2018, 06:42:10) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Using /Users/reinose/ecs_pipeline/ansible.cfg as config file
setting up inventory plugins
Parsed /Users/reinose/ecs_pipeline/inventory/hosts.inv inventory source with ini plugin
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

1 plays in playbooks/ecs_service.yml

playbook: playbooks/ecs_service.yml

  play #1 (localhost): localhost	TAGS: []
      TASK TAGS: [always]
```

**Comment by ansibot** [comment]
Files identified in the description:
* [test/integration/targets/tags/aliases](https://github.com/ansible/ansible/blob/devel/test/integration/targets/tags/aliases)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/cli/playbook.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/cli/playbook.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by SimplySeth** [comment]
also .... the never tag causes previous tasks to not run when running 
```
ansible-playbook playbooks/ecs_service.yml -e@args.yml --tags=make_repo

```

```yaml

# tasks file for ecs_service

# all tasks in the below includes fail when 'never' tag is used in the **later**  task
- include_tasks: "var_checks.yml"
  tags:
    - always
- include_tasks: "set_facts.yml"
  tags:
    - always

- name: "Environment component block ..."
  block:
    - include_tasks: "make_security_group.yml"
      tags:
        - security_group
    - include_tasks: "make_repo.yml"
      tags:
        - make_repo
        - never
```
