### ISSUE TITLE
subelements plugins returns a dict if only one subelements match

### ISSUE THREAD

**Issue by bobsaintcool** [ansible/ansible#38183]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
subelements

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]

```

##### CONFIGURATION
Nothing output

##### OS / ENVIRONMENT
Arch Linux (manager and managed) from distribution package.

##### SUMMARY
Using the new loop merged feature with the subelement plugins seems to not works when the later match only one subelement from the given list of dict. However, when at least two subkeys match a list is returned by the plugin leaving loop in an expected case.

##### STEPS TO REPRODUCE
```yaml
---
- name: Subelement
  hosts: localhost
  gather_facts: False
  vars:
    ansible_connection: local
    users:
      - name: alice
        authorized:
          - /tmp/alice/onekey.pub
          - /tmp/alice/twokey.pub
        mysql:
            password: mysql-password
            hosts:
              - "%"
              - "127.0.0.1"
              - "::1"
              - "localhost"
            privs:
              - "*.*:SELECT"
              - "DB1.*:ALL"
        groups:
          - wheel
      - name: bob
        authorized:
          - /tmp/bob/id_rsa.pub
        mysql:
            password: other-mysql-password
            hosts:
              - "db1"
            privs:
              - "*.*:SELECT"
              - "DB2.*:ALL"
      # - name: charly
      #   authorized:
      #     - /tmp/charly/id_rsa.pub
      #   groups:
      #     - ifixit
      #   mysql:
      #       password: other-mysql-password
      #       hosts:
      #         - "db1"
      #       privs:
      #         - "*.*:SELECT"
      #         - "DB2.*:ALL"
  tasks:
    - name: "list groups for user that have them, dont error if they don't"
      debug:
        var: item[0]
      loop: "{{ lookup('subelements', users, 'groups', {'skip_missing': True}) }}"
```
##### EXPECTED RESULTS
List Alice's groups

##### ACTUAL RESULTS
```
PLAY [Subelement] ****************************************************************************************************************************************************************************************************************************************************************

TASK [list groups for user that have them, dont error if they don't] *************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop' it requires a list, got this instead: ({u'authorized': [u'/tmp/alice/onekey.pub', u'/tmp/alice/twokey.pub'], u'name': u'alice', u'mysql': {u'password': u'mysql-password', u'hosts': [u'%', u'127.0.0.1', u'::1', u'localhost'], u'privs': [u'*.*:SELECT', u'DB1.*:ALL']}}, u'wheel')"}
        to retry, use: --limit @/home/user/ansible_dummy/loop/subelt_doc.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```
