### ISSUE TITLE
subelements plugin document is missleading on optional flags

### ISSUE THREAD

**Issue by bobsaintcool** [ansible/ansible#38182]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

subelements

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]

```

##### CONFIGURATION
Nothing special

##### OS / ENVIRONMENT
Arch Linux (manager and managed) from distribution package.

##### SUMMARY
Looking at the document its seems that the subelements plugins can get a third flag telling if it could stop on error or not if the subkey is not found for a given element. The plugin doc seems to say that the third element could be given as a string, whereas it seems to me that only a dict should be used here.

##### STEPS TO REPRODUCE

```yaml
---
- name: Subelement
  hosts: localhost
  gather_facts: False
  vars:
    ansible_connection: local
    users:
      - name: alice
        authorized:
          - /tmp/alice/onekey.pub
          - /tmp/alice/twokey.pub
        mysql:
            password: mysql-password
            hosts:
              - "%"
              - "127.0.0.1"
              - "::1"
              - "localhost"
            privs:
              - "*.*:SELECT"
              - "DB1.*:ALL"
        groups:
          - wheel
      - name: bob
        authorized:
          - /tmp/bob/id_rsa.pub
        mysql:
            password: other-mysql-password
            hosts:
              - "db1"
            privs:
              - "*.*:SELECT"
              - "DB2.*:ALL"
  tasks:
    # this should not raised an error according to doc
    - name: "list groups for user that have them, dont error if they don't"
      debug: var=item
      with_list: "{{lookup('subelements', users, 'groups', 'skip_missing=True')}}"
    # this should works according to code
    - name: "list groups for user that have them, dont error if they don't"
      debug: var=item[0]
      loop: "{{ lookup('subelements', users, 'groups', {'skip_missing': True}) }}"
```
##### EXPECTED RESULTS
List of group for alice

##### ACTUAL RESULTS
```
PLAY [Subelement] ****************************************************************************************************************************************************************************************************************************************************************

TASK [list groups for user that have them, dont error if they don't] *************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'subelements'. Error was a <class 'ansible.errors.AnsibleError'>, original message: subelements lookup expects a list of two or three items, the optional third item must be a dict with flags skip_missing"}
        to retry, use: --limit @/home/user/ansible_dummy/doc/subelt_doc.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   
```
