### ISSUE TITLE
libvirt module - `command: status` should not fail when `name:` is undefined.

### ISSUE THREAD

**Issue by civik** [ansible/ansible#38189]
##### ISSUE TYPE

 - Bug Report
 - Enhancement

##### COMPONENT NAME

virt

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 15:04:47) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

null

##### OS / ENVIRONMENT

OSX 10.12.6 

##### SUMMARY

Virt module should not throw error when using `command: status` on a `name:` that doesn't exist.  This makes it really cumbersome to use by having to add extra checking and conditionals to check for the VM name in the `list_vms` output any time you want to use the output of `status`.  

##### STEPS TO REPRODUCE

```yaml

[all]
1.1.1.1
1.1.1.2
1.1.1.3 

vmname: myvm-{{ ansible_inventory_name }}

# I will fail if there is a vmname that doesn't exist
- name: Discover current VM state
  virt:
    command: status
    name: "{{ vmname }}"
  register: current_vm_status
  ignore_errors: True

- name: Destroy existing VM if there is a new image
....
  when: 
    - (image_download.changed)
    - (current_vm_status.status == "running")  # <-- conditional fails where vm was undefined

```

##### EXPECTED RESULTS

I would think it would be more ideal to perhaps return `undefined` if the VM didn't exist on the hypervisor. Allowing for cases where the VM didn't exist when asking for status would make this module much more user friendly.
