### ISSUE TITLE
azure_rm_securitygroup cannot create rules that allow comma-separated IP address prefixes

### ISSUE THREAD

**Issue by savishy** [ansible/ansible#38198]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`azure_rm_securitygroup`

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vish/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible/ansible.log
```

##### OS / ENVIRONMENT

Control Machine Details:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
```

##### SUMMARY

The `azure_rm_securitygroup` module is unable to set security rules where the `source_address_prefix` is a sequence of IP addresses. It _is able to set security rules_ when the `source_address_prefix` is a _single IP address_.

##### STEPS TO REPRODUCE

* Save the playbook below e.g. `bug.yml`.
* Replace IP addresses with a valid set of IPs of your own. 
* Run playbook `ansible-playbook bug.yml`

```yaml
---
- name: Reproducing a Bug
  hosts: localhost
  connection: local
  tasks:
  - name: Ensure resource group exists
    azure_rm_resourcegroup:
      name: "TESTRG"
      location: "westeurope"
    state: present
  - name: Set Rules for NSG 
    azure_rm_securitygroup:
      resource_group: "TESTRG"
      name: "TESTNSG"
      purge_rules: yes
      rules: 
      - name: WinRM-Secure
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 1021
        direction: Inbound
        source_address_prefix: "X.X.X.X,Y.Y.Y.Y,Z.Z.Z.Z"

```

##### EXPECTED RESULTS

* Create an Azure NSG Security Group `TESTNSG`
* Security group should have one rule "WinRM-Secure". 
* The Source IP Addresses field should have 3 IP addresses added.

An example screenshot. The Security Rule here was created manually from Azure GUI. 

![image](https://user-images.githubusercontent.com/13379978/38228641-0f244b26-36f4-11e8-9a52-24efbdc36170.png)

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_8WSk8C/ansible_module_azure_rm_securitygroup.py", line 707, in create_or_update
    parameters=parameters)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/network/v2017_11_01/operations/network_security_groups_operations.py", line 278, in create_or_update
    get_long_running_status, long_running_operation_timeout)
  File "/usr/local/lib/python2.7/dist-packages/msrestazure/azure_operation.py", line 360, in __init__
    raise CloudError(self._response)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": null,
            "default_rules": null,
            "location": null,
            "name": "TESTNSG",
            "password": null,
            "profile": null,
            "purge_default_rules": false,
            "purge_rules": true,
            "resource_group": "TESTRG",
            "rules": [
                {
                    "access": "Allow",
                    "destination_address_prefix": "*",
                    "destination_port_range": 5986,
                    "direction": "Inbound",
                    "name": "WinRM-Secure",
                    "priority": 1021,
                    "protocol": "Tcp",
                    "source_address_prefix": "X.X.X.X,Y.Y.Y.Y,Z.Z.Z.Z",
                    "source_port_range": "*"
                }
            ],
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "msg": "Error creating/updating security group TESTNSG - Azure Error: SecurityRuleInvalidAddressPrefix\nMessage: Security rule /subscriptions/XXXXXXXXXXXXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG/securityRules/WinRM-Secure has invalid Address prefix. Value provided: X.X.X.X,Y.Y.Y.Y,Z.Z.Z.Z"
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_securitygroup.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_securitygroup.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
@savishy Please try the following playbook

```yaml
---
- name: Reproducing a Bug
  hosts: localhost
  connection: local
  tasks:
  - name: Ensure resource group exists
    azure_rm_resourcegroup:
      name: "TESTRG"
      location: "westeurope"
    state: present
  - name: Set Rules for NSG 
    azure_rm_securitygroup:
      resource_group: "TESTRG"
      name: "TESTNSG"
      purge_rules: yes
      rules: 
      - name: WinRM-Secure
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 1021
        direction: Inbound
        source_address_prefixes:
        - 52.100.120.240
        - 53.100.250.190
        - 54.110.200.200
```

**Comment by yuwzho** [comment]
@savishy Please try the following playbook

```yaml
---
- name: Reproducing a Bug
  hosts: localhost
  connection: local
  tasks:
  - name: Ensure resource group exists
    azure_rm_resourcegroup:
      name: "TESTRG"
      location: "westeurope"
    state: present
  - name: Set Rules for NSG 
    azure_rm_securitygroup:
      resource_group: "TESTRG"
      name: "TESTNSG"
      purge_rules: yes
      rules: 
      - name: WinRM-Secure
        protocol: Tcp
        destination_port_range: 5986
        access: Allow
        priority: 1021
        direction: Inbound
        source_address_prefixes:
        - 52.100.120.240
        - 53.100.250.190
        - 54.110.200.200
```

**Comment by savishy** [comment]
@yuwzho  Could I request this issue be reopened?

* I ran the playbook again, making note of the parameter name: `source_address_prefixes` instead of `source_address_prefix`.
* It seems this parameter was silently ignored. In the invocation I see it has passed in `"source_address_prefix": "*"` 
* This causes the NSG to be created with no `source_address_prefix` i.e. it is open to the world. (This is a serious security risk and raises automated alarms at my organization, which I really want to avoid :)  )

```
changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": null,
            "default_rules": null,
            "location": null,
            "name": "TESTNSG",
            "password": null,
            "profile": null,
            "purge_default_rules": false,
            "purge_rules": true,
            "resource_group": "TESTRG",
            "rules": [
                {
                    "access": "Allow",
                    "destination_address_prefix": "*",
                    "destination_port_range": 5986,
                    "direction": "Inbound",
                    "name": "WinRM-Secure",
                    "priority": 1021,
                    "protocol": "Tcp",
                    "source_address_prefix": "*",
                    "source_address_prefixes": [
                        "52.138.X.X",
                        "52.164.X.X",
                        "52.138.X.X"
                    ],
                    "source_port_range": "*"
                }
            ],
            "secret": null,
            "state": "present",
            "subscription_id": null,
            "tags": null,
            "tenant": null
        }
    },
    "state": {
        "default_rules": [
            {
                "access": "Allow",
                "description": "Allow inbound traffic from all VMs in VNET",
                "destination_address_prefix": "VirtualNetwork",
                "destination_port_range": "*",
                "direction": "Inbound",
                "etag": "W/\"01de6124-c502-45ed-XXXX-b969X78fa5574\"",
                "id": "/subscriptions/XXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG/defaultSecurityRules/AllowVnetInBound",
                "name": "AllowVnetInBound",
                "priority": 65000,
                "protocol": "*",
                "provisioning_state": "Succeeded",
                "source_address_prefix": "VirtualNetwork",
                "source_port_range": "*"
            },
            {
                "access": "Allow",
                "description": "Allow inbound traffic from azure load balancer",
                "destination_address_prefix": "*",
                "destination_port_range": "*",
                "direction": "Inbound",
                "etag": "W/\"01de6124-c502-XX-87f9-XCXC\"",
                "id": "/subscriptions/XXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG/defaultSecurityRules/AllowAzureLoadBalancerInBound",
                "name": "AllowAzureLoadBalancerInBound",
                "priority": 65001,
                "protocol": "*",
                "provisioning_state": "Succeeded",
                "source_address_prefix": "AzureLoadBalancer",
                "source_port_range": "*"
            },
            {
                "access": "Deny",
                "description": "Deny all inbound traffic",
                "destination_address_prefix": "*",
                "destination_port_range": "*",
                "direction": "Inbound",
                "etag": "W/\"X-c502-45ed-87f9-X\"",
                "id": "/subscriptions/XXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG/defaultSecurityRules/DenyAllInBound",
                "name": "DenyAllInBound",
                "priority": 65500,
                "protocol": "*",
                "provisioning_state": "Succeeded",
                "source_address_prefix": "*",
                "source_port_range": "*"
            },
            {
                "access": "Allow",
                "description": "Allow outbound traffic from all VMs to all VMs in VNET",
                "destination_address_prefix": "VirtualNetwork",
                "destination_port_range": "*",
                "direction": "Outbound",
                "etag": "W/\"01de6124-c502-45ed-87f9-XX\"",
                "id": "/subscriptions/XXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG/defaultSecurityRules/AllowVnetOutBound",
                "name": "AllowVnetOutBound",
                "priority": 65000,
                "protocol": "*",
                "provisioning_state": "Succeeded",
                "source_address_prefix": "VirtualNetwork",
                "source_port_range": "*"
            },
            {
                "access": "Allow",
                "description": "Allow outbound traffic from all VMs to Internet",
                "destination_address_prefix": "Internet",
                "destination_port_range": "*",
                "direction": "Outbound",
                "etag": "W/\"01de6124-c502-45ed-87f9-XX\"",
                "id": "/subscriptions/XXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG/defaultSecurityRules/AllowInternetOutBound",
                "name": "AllowInternetOutBound",
                "priority": 65001,
                "protocol": "*",
                "provisioning_state": "Succeeded",
                "source_address_prefix": "*",
                "source_port_range": "*"
            },
            {
                "access": "Deny",
                "description": "Deny all outbound traffic",
                "destination_address_prefix": "*",
                "destination_port_range": "*",
                "direction": "Outbound",
                "etag": "W/\"01de6124-c502-45ed-87f9-X\"",
                "id": "/subscriptions/XXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG/defaultSecurityRules/DenyAllOutBound",
                "name": "DenyAllOutBound",
                "priority": 65500,
                "protocol": "*",
                "provisioning_state": "Succeeded",
                "source_address_prefix": "*",
                "source_port_range": "*"
            }
        ],
        "id": "/subscriptions/XXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG",
        "location": "westeurope",
        "name": "TESTNSG",
        "network_interfaces": [],
        "rules": [
            {
                "access": "Allow",
                "description": null,
                "destination_address_prefix": "*",
                "destination_port_range": "5986",
                "direction": "Inbound",
                "etag": "W/\"01de6124-c502-45ed-87f9-X\"",
                "id": "/subscriptions/XXXXXXXXXXX/resourceGroups/TESTRG/providers/Microsoft.Network/networkSecurityGroups/TESTNSG/securityRules/WinRM-Secure",
                "name": "WinRM-Secure",
                "priority": 1021,
                "protocol": "Tcp",
                "provisioning_state": "Succeeded",
                "source_address_prefix": "*",
                "source_port_range": "*"
            }
        ],
        "subnets": [],
        "tags": {},
        "type": "Microsoft.Network/networkSecurityGroups"
    }
}
```

**Comment by yuwzho** [comment]
@savishy Sure, I get your question, please reopen it and I will add it to my backlog

**Comment by savishy** [comment]
@yuwzho I don't see a Reopen option. Just an option to comment. Perhaps you can reopen from your side.

**Comment by yuwzho** [comment]
I also don't have the reopen button...

**Comment by abadger** [comment]
bot_skip

**Comment by savishy** [comment]
@yuwzho I got the issue reopened (thanks @abadger ) - could you take a look at this now please?

**Comment by yuwzho** [comment]
@savishy I already add this to my backlog, but I don't think I have bandwidth this three weeks. I can know the problem is the following two line: 

https://github.com/ansible/ansible/blob/6300e71903ef02212f792b09c9b6720a55bfdf24/lib/ansible/modules/cloud/azure/azure_rm_securitygroup.py#L372-L373

It should also check whether the `source_address_prefixes` is none. Besides these lines, there also need document modification and full test. I add `easyfix` here, to see if someone volunteer can help to solve this problem before I get time.

+label easyfix

**Comment by savishy** [comment]
@yuwzho take your time, this isn't urgent. I'll let you know if I have some bandwidth, perhaps I can make a PR with your assistance.

**Comment by yuwzho** [comment]
working on it

**Comment by yuwzho** [comment]
@savishy You can try my PR now, there is instruction in the PR to show how to install the changes 😄

**Comment by nicolaibaralmueller** [comment]
What is the status here? Also cannot add comma separated lists of IPs

**Comment by guenoledc** [comment]
Hi, I had the same problem and twisted the mind to create a rule for each item in my comma separated list (until the bug is fixed) - Here is my role:
```yaml
- azure_rm_securitygroup:
    resource_group: '{{ resource_group_name }}'
    name: '{{ network_security_group_name }}'
    purge_rules: no
    rules:
      - name: '{{ rule_name }}{{ item.0 }}'
        protocol: Tcp
        source_address_prefix: '{{ item.1 }}'
        destination_address_prefix: '{{ target }}'
        destination_port_range: '{{ port_range }}'
        access: '{{ access }}'
        priority: '{{ (priority+item.0)|int }}'
        direction: Inbound
  with_indexed_items: '{{ source.split(",") }}'
```
And can then be used :
```yaml
    - role: network-security-group-add-rule
      rule_name: AllowApp
      source: '{{ proxy_addresses }}' # comma separated list of ip address
      target: '{{azure_vm.properties.networkProfile.networkInterfaces[0].properties.ipConfigurations[0].properties.privateIPAddress}}'
      port_range: 443
      access: Allow
      priority: 200
```
