### ISSUE TITLE
ovirt: facts modules with fetch_nested return id as list

### ISSUE THREAD

**Issue by machacekondra** [ansible/ansible#38203]
Description of problem:
Ansible module ovirt_cluster_facts with 'fetch_nested: True' return id value as list. Id is unique so it should be only string.
Other get facts modules return list also.

Version-Release number of selected component (if applicable):
ovirt-engine-4.2.2.2-0.1.el7.noarch
ansible-2.4.3.0-1.fc27.noarch

How reproducible: always

Steps to Reproduce:
1. run ansible playbook
```yaml
---
- hosts:
    - engine
  tasks:
    - name: collect cluster facts
      ovirt_cluster_facts:
        auth:
          username: admin@internal
          password: xxx
          url: https://engine/ovirt-engine/api
          insecure: true
        pattern: name=Default
        fetch_nested: True
        nested_attributes:
          - name
    - debug:
        var: ovirt_clusters
```

2. see the cluster facts

Actual results:
```json
            "networks": [
                {
                    "id": [
                        "00000000-0000-0000-0000-000000000009"
                    ], 
                    "name": "ovirtmgmt"
                }
            ], 
            "permissions": [
                {
                    "id": [
                        "2aad1892-1baa-11e8-a581-001a4aa43000"
                    ]
                }, 
                {
                    "id": [
                        "58ca605c-010d-0307-0224-0000000001a9"
                    ]
                }
            ], 
```

Expected results:
```json
            "networks": [
                {
                    "id": "00000000-0000-0000-0000-000000000009", 
                    "name": "ovirtmgmt"
                }
            ], 
            "permissions": [
                {
                    "id": "2aad1892-1baa-11e8-a581-001a4aa43000"
                }, 
                {
                    "id": "58ca605c-010d-0307-0224-0000000001a9"
                }
            ],
```

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ovirt

##### ANSIBLE VERSION

```
2.4.2.
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```
