### ISSUE TITLE
Ansible loop reveals passwords on failure in output even with loop_control: label

### ISSUE THREAD

**Issue by sekharvajjula** [ansible/ansible#38214]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

loop_control

##### ANSIBLE VERSION

```
2.3.0.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Ansible loops (with_dict, with_nested, with_items, etc...) reveals passwords on failure, in output even with "loop_control: label". 

Using loop_control http://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#loop-control we can nicely choose certain fields to display. But on failure loop_control reveals all the contents in failed item, which sometimes have passwords 

One WA is to use "no_log: True" but this suppresses everything and makes life difficult for debugging during failures.

Passwords are revealed in loops even when used with Ansible modules where they have explicitly disabled revealing passwords. eg:- Ansible uri module (ansible/modules/network/basics/uri.py)
>url_password = dict(required=False, default=None, aliases=['password'], no_log=True)

##### STEPS TO REPRODUCE

Run the below playbook with:
> ansible-playbook test.yaml (to see the error with password revealed on failure)
> ansible-playbook --skip-tags node_loop test.yaml (runs without loop, so password is not revealed on failure)

```yaml
- name: Test loop
  hosts: localhost
  vars:
    nodes_details:
      controller-2:
        hwmgmt:
          address: 10.207.242.211
          user: 'admin'
          password: 'admin123'
  tasks:
    - name: Get details of all nodes.
      uri:
        url: "https://{{item.value['hwmgmt']['address']}}/redfish/v1/Systems/1"
        method: GET
        body_format: json
        body: '{"Reset_Type": "forceoff"}'
        validate_certs: no
        user: "{{item.value['hwmgmt']['user']}}"
        url_password: "{{item.value['hwmgmt']['password']}}"
      with_dict: "{{nodes_details}}"
      loop_control:
        label: "{{item.key}}"
      tags: node_loop

    - name: Get node details.
      uri:
        url: "https://{{nodes_details['controller-2']['hwmgmt']['address']}}/redfish/v1/Systems/1"
        method: GET
        body_format: json
        body: '{"Reset_Type": "forceoff"}'
        validate_certs: no
        user: "{{nodes_details['controller-2']['hwmgmt']['user']}}"
        url_password: "{{nodes_details['controller-2']['hwmgmt']['password']}}"
      tags: one_node
```

##### EXPECTED RESULTS

TASK [Get details of all nodes.] ************************************************************************************************************************************
failed: [localhost] (item=controller-2) => {"content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error timed out>", "redirected": false, "status": -1, "url": "https://10.207.242.211/redfish/v1/Systems/1"}
##### ACTUAL RESULTS

TASK [Get details of all nodes.] ************************************************************************************************************************************
failed: [localhost] (item=controller-2) => {"content": "", "failed": true, "item": {"key": "controller-2", "value": {"hwmgmt": {"address": "10.207.242.211", "password": "admin123", "user": "admin"}}}, "msg": "Status code was not [200]: Request failed: <urlopen error timed out>", "redirected": false, "status": -1, "url": "https://10.207.242.211/redfish/v1/Systems/1"}

```

```
