### ISSUE TITLE
with_all_found lookup

### ISSUE THREAD

**Issue by szhem** [ansible/ansible#38227]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

!component

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  python version = 2.7.3
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

From time to time it's necessary to include OS-specific variables overriding more generic ones with more specific ones, e.g.
###### ubuntu.yml
```yaml
packages:
  - ethtool
  - iproute
```
###### ubuntu-16.yml
```yaml
packages:
  - ethtool
  - iproute2
```
In case there are a lot of variables and you need to change just one of them, you have to copy the whole list of vars even if you don't need it.

The idea is to implement lookup `with_all_found` similar to `with_first_found`, but that returns all the found items.

##### STEPS TO REPRODUCE

```yaml
- name: Collect OS variables
  include_vars: "{{ vars_item }}"
  with_all_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.replace('.', '-') | lower }}.yml"
      paths:
        - defaults/os
        - defaults
        - vars/os
        - vars
      skip: true
  loop_control:
    loop_var: vars_item
```

##### EXPECTED RESULTS

```bash
TASK [role-template : Collect OS variables] 
ok: [localhost] => (item=/home/szhem/.../role-template/defaults/os/debian.yml)
ok: [localhost] => (item=/home/szhem/.../role-template/defaults/os/ubuntu-16.yml)
ok: [localhost] => (item=/home/szhem/.../role-template/defaults/os/ubuntu-16-04.yml)
```
There is a single task that includes all the variables and overrides more generic ones with more specific ones.

##### ACTUAL RESULTS

Currently it's hardly possible to include multiple files with variables using a single task.  
The workaround could be the following, but it's to verbose
```yaml
- name: Collect OS family variables
  include_vars: "{{ vars_item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - defaults/os
        - defaults
        - vars/os
        - vars
      skip: true
  loop_control:
    loop_var: vars_item

- name: Collect OS distribution variables
  include_vars: "{{ vars_item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}.yml"
      paths:
        - defaults/os
        - defaults
        - vars/os
        - vars
      skip: true
  loop_control:
    loop_var: vars_item

- name: Collect OS distribution major version variables
  include_vars: "{{ vars_item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
      paths:
        - defaults/os
        - defaults
        - vars/os
        - vars
      skip: true
  loop_control:
    loop_var: vars_item

- name: Collect OS distribution version variables
  include_vars: "{{ vars_item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.replace('.', '-') | lower }}.yml"
      paths:
        - defaults/os
        - defaults
        - vars/os
        - vars
      skip: true
  loop_control:
    loop_var: vars_item
```
```bash
TASK [role-template : Collect OS family variables] 
ok: [localhost] => (item=/home/szhem/.../role-template/defaults/os/debian.yml)

TASK [role-template : Collect OS distribution variables] 

TASK [role-template : Collect OS distribution major version variables] 
ok: [localhost] => (item=/home/szhem/.../role-template/defaults/os/ubuntu-16.yml)

TASK [role-template : Collect OS distribution version variables] 
ok: [localhost] => (item=/home/szhem/.../role-template/defaults/os/ubuntu-16-04.yml)
```

I can implement a PR for this feature request if it will be accepted.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/module_utils/k8s/lookup.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/k8s/lookup.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by flowerysong** [comment]
You can do this in a single task with existing functionality by looping:

```
- name: Collect OS variables
  include_vars: "{{ vars_item }}"
  when: vars_item | length
  vars:
    vars_item: "{{ lookup('first_found', vars_search) }}"
    vars_search:
      files: "{{ item }}"
      paths:
        - defaults/os
        - defaults
        - vars/os
        - vars
      skip: true
  loop:
    - "{{ ansible_os_family | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.replace('.', '-') | lower }}.yml"
```

(Ansible <2.5 would need `with_list` instead of `loop`, but should otherwise work identically.)

```
TASK [Debug OS variables] ****************************************************
ok: [localhost] => (item=None) => {
    "msg": "/home/ec2-user/files/defaults/os/redhat.yml"
}
skipping: [localhost] => (item=amazon.yml) 
skipping: [localhost] => (item=amazon-na.yml) 
skipping: [localhost] => (item=amazon-candidate.yml)

TASK [Collect OS variables] ****************************************************
ok: [localhost] => (item=redhat.yml)
skipping: [localhost] => (item=amazon.yml) 
skipping: [localhost] => (item=amazon-na.yml) 
skipping: [localhost] => (item=amazon-candidate.yml) 
```

**Comment by szhem** [comment]
@flowerysong, that's great! thanks a lot! Then I'm closing this issue.

**Comment by ssbarnea** [comment]
I think we need to reopen this issue because the stated workaround is  ugly, hard to read and too verbose (still very useful, and for this reason I am making a PR to add it to the documentation).

I see no reason why we should not have a `with_all_found` lookup that avoids the need to use it.

**Comment by bcoca** [comment]
We don't normally see closed issues but @ssbarnea brought this to my attention, a simpler way:

```yaml
 -  name: include all found files
    include_vars: "{{ item }}"
    when: lookup('pipe', '[ -f ' ~ item ~ ' ]; echo $?') == '0'
    loop:
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.replace('.', '-') | lower }}.yml"
```

**Comment by ssbarnea** [comment]
Thanks, that is starting to look better! ... now we only need to add `with_all_found` alias so we would not have to spend a countless number of hours tying to explain what the `when` line does on each place where we want to introduce it.... that line reminded me of my perl days.

I am not joking about spending time explaining, I was trying to improve this piece of code https://review.openstack.org/#/c/617118/ --- but I doubt I will pass review only because of the when link: while the code may be correct, it is clearly not easy to read/understand.

I assume that ansible team struggles with the attempt to fiight entropy and feature creeping,... but maybe we should just implement with_all_found instead.

**Comment by bcoca** [comment]
actually, much simpler:
```
  - include_vars: "{{item}}"
    failed_when: false
    loop:
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.replace('.', '-') | lower }}.yml"
```

**Comment by ssbarnea** [comment]
@bcoca I think is time to create a new bug as your example while it looks correct fails to load any variable at all. It seems tha loop loading via include_vars is deeply broken.

How to reproduce:
Create `one.yml` with:
```
foo: bar
```
Now try to run this with ansible:
```
- include_vars: "{{item}}"
    failed_when: false
    loop:
        - "one.yml"
        - "two.yml"
- debug: var=foo
```
What you will get is:
```
ok: [localhost] => {
    "foo": "VARIABLE IS NOT DEFINED!"
}
```

As you can see this is really dangereus as it stops loading any variables once you add the loop.

This happens regardless `ignore_errors` value, as long one file is missing no variable will be loaded.

If all files do exists, the variables are loaded correctly.

**Comment by bcoca** [comment]
I don't get the same results
```
PLAY [localhost] ******************************************************************************************************************************************

TASK [include_vars] ***************************************************************************************************************************************
ok: [localhost] => (item=one.yml)
ok: [localhost] => (item=two.yml)

TASK [debug] **********************************************************************************************************************************************
ok: [localhost] => {
    "foo": "bar"
}

PLAY RECAP ************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0
```

**Comment by ssbarnea** [comment]
I raised it at https://github.com/ansible/ansible/issues/48683 -- Please be sure that two.yaml does **not** exist on disk, also run with ANSIBLE_VERBOSITY=1 to see what happens.

Because I see "ok" on the line with two.yml I suppose that file existed on disk.

**Comment by bcoca** [comment]
remove `failed_when: false` from the play and you'll see the error, the whole point of that line is to 'make it have no errors'.

**Comment by bcoca** [comment]
w/o `failed_when`
```
ok: [localhost] => (item=one.yml)
failed: [localhost] (item=two.yml) => {"ansible_facts": {}, "ansible_included_var_files": [], "changed": false, "item": "two.yml", "message": "Could not find or access 'two.yml'\nSearched in:\n\t/home/bcoca/work/ansible/vars/two.yml\n\t/home/bcoca/work/ansible/two.yml\n\t/home/bcoca/work/ansible/vars/two.yml\n\t/home/bcoca/work/ansible/two.yml on the Ansible Controller.\nIf you are using a module and expect the file to exist on the remote, see the remote_src option"}
```

**Comment by abedwardsw** [comment]
also think with_all_found would be a cleaner implementation.

**Comment by manumeter** [comment]
Thanks @bcoca / @ssbarnea for the solution to this. Since I wanted to make it a bit "better readable", I've written a small lookup-plugin for this (hope it helps someone).

With your example:

```yaml
-  name: include all found files
    include_vars: "{{ item }}"
    when: lookup('file_exists', 'vars/' ~ item)
    loop:
        - "{{ ansible_os_family | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version.replace('.', '-') | lower }}.yml"
```

with: https://github.com/isginf/ansible/blob/master/plugins/lookup/file_exists.py
