### ISSUE TITLE
State changed to "absent" when attempting to create directory

### ISSUE THREAD

**Issue by AjG1tHub** [ansible/ansible#38234]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/anthonyletizia/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/anthonyletizia/python/projects/ansible-role-java/lib/python2.7/site-packages/ansible
  executable location = /Users/anthonyletizia/python/projects/ansible-role-java/bin/ansible
  python version = 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Using: OSX
Creating box: Ubuntu14.04
##### SUMMARY

I'm attempting to create an ansible box using docker, and preinstall a .tgz java file. When trying to create the directory, I get the following error
```
"msg": "There was an issue creating /usr/java as requested: [Errno 1] Operation not permitted: '/usr/java'",
        "path": "/usr/java",
        "state": "absent"
```
##### STEPS TO REPRODUCE

```yaml
  - name: Creates directory
      file:
        state: directory
        path: /usr/java
        mode: 0775
        recurse: yes

    - name: copy java folder
      copy:
        src: files/ibm-java-sdk-8.0-5.10-linux-s390x.tgz
        dest: /usr/java/
```

##### EXPECTED RESULTS

Directory should be created and java file should be inserted into it, even when using the "become: yes" tag it states a password is required.

**Comment by ansibot** [comment]
@AjG1tHub Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by maxamillion** [comment]
!component +=./lib/ansible/plugins/action/copy.py
!component +=./lib/ansible/modules/files/copy.py

**Comment by maxamillion** [comment]
I'm unable to reproduce here with the information provided, I'm guessing I'm not setting something I should or I am setting something I shouldn't but either way I think there's a variance in our test scenarios. Can you please share a full playbook as the command you're running that causes the issue?

**Comment by maxamillion** [comment]
needs_info

**Comment by AjG1tHub** [comment]
I'm attempting a test via molecule, the error read out is what appears when I run the molecule --debug create. These steps are in the prepare.yml file. 
```yaml
---
- name: Prepare
  hosts: all
  gather_facts: false
  tasks:
    - name: Creates directory
      file:
        state: directory
        path: /usr/java
        mode: 0775
        recurse: yes

    - name: copy java folder
      copy:
        src: files/ibm-java-sdk-8.0-5.10-linux-s390x.tgz
        dest: /usr/java/

```
I'd like to note, as of rerunning it this morning, its now functioning without error
