### ISSUE TITLE
`win_updates` module fails with keyerror `changed`

### ISSUE THREAD

**Issue by poiriermike** [ansible/ansible#38232]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = ['/home/local/USER/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/local/USER/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/ansible
  executable location = /home/local/USER/.local/share/virtualenvs/ansible/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

win_updates module fails in ansible 2.5
##### STEPS TO REPRODUCE

Attempt to use the win_updates module with ansible 2.5 against a windows host. Bug happens both when state is `installed` or `searched`.

```yaml
---
- name: Playbook that does things
  hosts: all
  gather_facts: yes
  tasks:
    - debug:
        var: ansible_distribution
    - block:
      - name: Echo
        raw: "echo Hello, World!"
        args:
          executable: powershell
        register: hello
      - debug:
          var: hello.stdout
      - name: Check for Windows Updates
        win_updates:
          # Only check, do not apply
          state: searched
          category_names:
            - Application
            - Connectors
            - CriticalUpdates
            - DefinitionUpdates
            - DeveloperKits
            - FeaturePacks
            - Guidance
            - SecurityUpdates
            - ServicePacks
            - Tools
            - UpdateRollups
            - Updates
        register: updates
      - name: Print updates
        debug:
          var: updates
      when: ansible_os_family == 'Windows'

```

##### EXPECTED RESULTS

Module runs without error 

##### ACTUAL RESULTS

Module fails with keyerror "changed" 

```
TASK [Check for Windows Updates] **********************************************************************************************************************************************************************************
task path: /home/local/USER/Projects/GitHub/ansible_example_playbook/example.yml:16
win_updates: running win_updates module
Using module file /home/local/USER/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/ansible/modules/windows/win_updates.ps1
<HOST> ESTABLISH WINRM CONNECTION FOR USER:  on PORT 5986 TO HOST
checking if winrm_host HOST is an IPv6 address
calling kinit with subprocess for principal 
EXEC (via pipeline wrapper)
The full traceback is:
Traceback (most recent call last):
  File "/home/local/USER/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/home/local/USER/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/ansible/executor/task_executor.py", line 554, in _execute
    result = self._handler.run(task_vars=variables)
  File "/home/local/USER/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/ansible/plugins/action/win_updates.py", line 189, in run
    changed = result['changed']
KeyError: 'changed'

fatal: [HOST]: FAILED! => {
    "msg": "Unexpected failure during module execution.",
    "stdout": ""
}
	to retry, use: --limit @/home/local/USER/Projects/GitHub/ansible_example_playbook/example.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
HOST   : ok=4    changed=1    unreachable=0    failed=1
```
