### ISSUE TITLE
vmware_portgroup always fails with 'NoneType' object has no attribute 'policy'

### ISSUE THREAD

**Issue by corbinstuard** [ansible/ansible#38255]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_portgroup

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 873a9ddf8d) last updated 2018/04/03 16:23:46 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/seit31/ansible/lib/ansible
  executable location = /home/seit31/ansible/bin/ansible
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = False
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=2000s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%p-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = /tmp
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/filter_plugins']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
N/A

##### SUMMARY
vmware_portgroup always fails with 'NoneType' object has no attribute 'policy'

##### STEPS TO REPRODUCE

```yaml
- name: create portgroups and assign to vswitches
    vmware_portgroup:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      esxi_hostname: "{{ esxi_ip }}"
      portgroup_name: "{{ item.portgroup }}"
      vlan_id: 0
      switch_name: "{{ item.vswitch }}"
      network_policy:
        promiscuous_mode: "{{ item.promiscuous | default(false) }}"
      validate_certs: false
    with_items: "{{ hostvars[inventory_hostname].network }}"
```

##### ACTUAL RESULTS
```
The full traceback is:
  File "/tmp/ansible_lFxOyA/ansible_module_vmware_portgroup.py", line 483, in main
    pyv.process_state()
  File "/tmp/ansible_lFxOyA/ansible_module_vmware_portgroup.py", line 214, in process_state
    self.add_hosts_port_group()
  File "/tmp/ansible_lFxOyA/ansible_module_vmware_portgroup.py", line 271, in add_hosts_port_group
    change = self.create_host_port_group(host, self.portgroup_name, self.vlan_id, self.switch_name, self.network_policy)
  File "/tmp/ansible_lFxOyA/ansible_module_vmware_portgroup.py", line 327, in create_host_port_group
    if self.check_network_policy_diff(desired_pgs[0].spec.policy, network_policy) or \
  File "/tmp/ansible_lFxOyA/ansible_module_vmware_portgroup.py", line 252, in check_network_policy_diff
    (current_policy.nicTeaming.policy != desired_policy.nicTeaming.policy) or \

failed: [router-test] (item={u'ip': u'192.168.5.254', u'nic': u'eth5', u'vswitch': u'L2MLX', u'portgroup': u'192.168.5.0'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "cluster_name": null,
            "esxi_hostname": "10.1.0.76",
            "hostname": "10.1.0.22",
            "hosts": [
                "10.1.0.76"
            ],
            "network_policy": {
                "forged_transmits": null,
                "mac_changes": null,
                "promiscuous_mode": false
            },
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "portgroup_name": "192.168.5.0",
            "state": "present",
            "switch_name": "L2MLX",
            "teaming_policy": {
                "inbound_policy": false,
                "load_balance_policy": "loadbalance_srcid",
                "notify_switches": true,
                "rolling_order": false
            },
            "username": "administrator@vsphere.local",
            "validate_certs": false,
            "vlan_id": 0
        }
    },
    "item": {
        "ip": "192.168.5.254",
        "nic": "eth5",
        "portgroup": "192.168.5.0",
        "vswitch": "L2MLX"
    },
    "msg": "'NoneType' object has no attribute 'policy'"
}



```
