### ISSUE TITLE
Playbook hangs while connecting to Windows Host(in Gathering Facts) but works fine pinged using win_ping

### ISSUE THREAD

**Issue by guptajiten** [ansible/ansible#38257]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

/etc/ansible/modules/windows/setup.ps1

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 29 2017, 20:42:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = True
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/action']
DEFAULT_CACHE_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/cache']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/callback']
DEFAULT_CONNECTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/connection']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/filter']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_INVENTORY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/inventory']
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/lookup']
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible']
DEFAULT_MODULE_UTILS_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/module_utils']
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 22
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles']
DEFAULT_STRATEGY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/strategy']
DEFAULT_TEST_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/test']
DEFAULT_TRANSPORT(/etc/ansible/ansible.cfg) = smart
DEFAULT_VARS_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/plugins/vars']

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.1 (Maipo)

##### SUMMARY

When i am trying to run the command as mentioned

It hangs after:

TASK [Gathering Facts] **********************************************************************************************************************************************************************
Using module file /etc/ansible/modules/windows/setup.ps1

But when I ping using win_ping it works fine.  Windows host has been setup according to guides in Ansible.

##### STEPS TO REPRODUCE

1. Run below command

```
/usr/bin/ansible-playbook /etc/ansible/playbooks/servicestartstop.yml -l abc -f 5 -e actiontype=stopped -e servicename=AbcService -vvvvvvvvvvv
```

##### EXPECTED RESULTS

Should get connected to Windows Host

##### ACTUAL RESULTS

```
<192.168.0.1> ESTABLISH WINRM CONNECTION FOR USER: administrator on PORT 5986 TO 192.168.0.1
<172.50.32.187> WINRM CONNECT: transport=ssl endpoint=https://172.50.32.187:5986/wsman
<192.168.0.1> WINRM OPEN SHELL: 38C8E0FB-75DD-4BDA-A85B-0ED9407BEC1F
EXEC (via pipeline wrapper)
<192.168.0.1> WINRM EXEC 'PowerShell' ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'Unrestricted', '-']
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/setup.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/setup.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
@jlohiya - please paste your /etc/ansible/playbooks/servicestartstop.yml  playbook here.
Also please advise - 1/ target windows operating system version
                                 2/ powershell version on target windows operating system.

needs_info

**Comment by guptajiten** [comment]
@jhawkesworth Thanks alot to respond.
Here are details asked:
servicestartstop.yml
```
---
- name: Start Stop Service
  hosts: all
  vars:
   actiontype: "{{actiontype}}"
   servicename: "{{servicename}}"
  tasks:
  - name: check service is installed
    win_service:
     name: "{{vars.servicename}}"
     register: result
  - name: enable manual service ...
    win_service:
     name: "{{vars.servicename}}"
     when: result|true
     state_mode: manual
  - name: Start Stop service if installed...
    win_service:
     name: "{{vars.servicename}}"
     state: "{{vars.actiontype}}"
  - name: enable back to auto  service...
    win_service:
     name: "{{vars.servicename}}"
     state_mode: auto
```
```
---------------------------------------------------------------------------
Windows Host: Windows 2012 R2
---------------------------------------------------------------------------
Powershell version:
Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
-----------------------------------------------------------------------------
```
