### ISSUE TITLE
get_url downloads corrupt files when run behind proxy

### ISSUE THREAD

**Issue by sayantandas** [ansible/ansible#38254]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

get_url

##### ANSIBLE VERSION

```
 ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```
ansible-config dump --only-changed
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/%%h-%%p-%%r
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/callback_plugins']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 600
```
##### OS / ENVIRONMENT

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"

##### SUMMARY

using get_url behind proxy downloads corrupt files. Below is the playbook used to download and run jenkins. when jenkins is started we get error in logs 
##### STEPS TO REPRODUCE

Playbook
```

- name: "Install Jenkins Master"
  hosts: "{{ target }}"
  gather_facts: true
  environment:
     http_proxy: "http://127.0.0.1:3128"
```
Role
```
 - name: get jenkins
   get_url:
      url: "http://mirrors.jenkins.io/war-stable/{{ version }}/jenkins.war"
       dest: "{{ jenkins_dest }}/jenkins.war"
       owner: jenkins
       group: jenkins
       mode: 0755
       use_proxy: yes
```

##### EXPECTED RESULTS

It should start Jenkins successfully.
##### ACTUAL RESULTS

Jenkins fails to start

jenkins download output
```
changed: [servername] => {
    "changed": true,
    "checksum_dest": null,
    "checksum_src": "bb38c845b1738467f8d25f614434a804ad456bb7",
    "dest": "/opt/jenkins/jenkins.war",
    "gid": 1003,
    "group": "jenkins",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/opt/jenkins/jenkins.war",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": "jenkins",
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": 493,
            "owner": "jenkins",
            "path": "/opt/jenkins/jenkins.war",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "http://mirrors.jenkins.io/war-stable/2.107.1/jenkins.war",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "md5sum": "d5fee7ef0c53ea8fcfdb6b7641172cf4",
    "mode": "0755",
    "msg": "OK (74525235 bytes)",
    "owner": "jenkins",
    "size": 74509916,
    "src": "/tmp/tmpVDEGYu",
    "state": "file",
    "status_code": 200,
    "uid": 1002,
    "url": "http://mirrors.jenkins.io/war-stable/2.107.1/jenkins.war"
```

failure output
```
fatal: [servername]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "daemon_reload": false,
            "enabled": null,
            "masked": null,
            "name": "jenkins",
            "no_block": false,
            "state": "started",
            "user": false
        }
    },
    "msg": "Unable to start service jenkins: Job for jenkins.service failed because the control process exited with error code. See \"systemctl status jenkins.service\" and \"journalctl -xe\" for details.\n"

```

**Jenkins log output**
```
Apr 04, 2018 6:51:43 AM winstone.Logger logInternal
INFO: JVM is terminating. Shutting down Winstone
Error: Invalid or corrupt jarfile /opt/jenkins/jenkins.war
```

**Comment by sayantandas** [comment]
when I downloaded with with checksum enabled in get_url , it failed the check

```
fatal: [servername]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "checksum": "sha256:cec74c80190ed1f6ce55d705d2f649ddb2eaf8aba3ae26796152921d46b31280",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "delimiter": null,
            "dest": "/opt/jenkins/jenkins.war",
            "directory_mode": null,
            "follow": false,
            "force": false,
            "force_basic_auth": false,
            "group": "jenkins",
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": 493,
            "owner": "jenkins",
            "regexp": null,
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "src": null,
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": null,
            "url": "http://mirrors.jenkins.io/war-stable/2.107.1/jenkins.war",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "The checksum for /opt/jenkins/jenkins.war did not match cec74c80190ed1f6ce55d705d2f649ddb2eaf8aba3ae26796152921d46b31280; it was 5840c13b57f7b0291dddade45021e86d827fddd0df43a7bf06b4359a5c3d9ffd."
}
 
```

**Comment by ansibot** [comment]
cc @jpmens
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by croensch** [comment]
I've seen some anti-virus proxy plugins delete files from inside war/jar files (because they are basically ZIPs). You could check if you can open the war with 7zip and "find" missing files by comparing it with the original.

**Comment by sayantandas** [comment]
These are headless Linux servers with no antivirus running in them

**Comment by ansibot** [comment]
cc @ptux
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bmillemathias** [comment]
This bug should be closed

**Comment by jzielke84** [comment]
I'm also experiencing the Issue when running the following block:

```yaml
- name: check md5
  hosts: localhost

  tasks:
    - name: Download nexus_package with proxy
      get_url:
        use_proxy: yes
        url: https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.28.1-01-unix.tar.gz
        dest: /Users/julian/Desktop/nexus-3.28.1-01-unix.tar.gz
        force: yes
      environment:
        http_proxy: apt-cacher.local:3142
        https_proxy: apt-cacher.local:3142
      register: download

    - debug:
        msg: "{{ download.md5sum }}"

    - name: Download nexus_package without proxy
      get_url:
        use_proxy: no
        url: https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.28.1-01-unix.tar.gz
        dest: /Users/julian/Desktop/nexus-3.28.1-01-unix.tar.gz
        force: yes
      register: download

    - debug:
        msg: "{{ download.md5sum }}"

    - name: Download nexus_package with proxy using wget
      shell: |
        wget -e \
          use_proxy=yes \
          -e https_proxy=apt-cacher.local:3142 \
          -v \
          -O /Users/julian/Desktop/nexus-3.28.1-01-unix.tar.gz \
          https://download.sonatype.com/nexus/3/nexus-3.28.1-01-unix.tar.gz
      args:
        warn: false

    - name: get md5sum
      shell: md5sum /Users/julian/Desktop/nexus-3.28.1-01-unix.tar.gz
      register: download

    - debug:
        msg: "{{ download.stdout }}"
```

Output is:

```shell

TASK [Gathering Facts] *************************************************************************************************************************************************************
ok: [localhost]

TASK [Download nexus_package with proxy] *******************************************************************************************************************************************
changed: [localhost]

TASK [debug] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "219b9be5c783b9a33c13799cfb35421b"
}

TASK [Download nexus_package without proxy] ****************************************************************************************************************************************
changed: [localhost]

TASK [debug] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "e3396e7e8b0a281f485d8166d2e4cd2b"
}

TASK [Download nexus_package with proxy using wget] ********************************************************************************************************************************
changed: [localhost]

TASK [get md5sum] ******************************************************************************************************************************************************************
changed: [localhost]

TASK [debug] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": "e3396e7e8b0a281f485d8166d2e4cd2b  /Users/julian/Desktop/nexus-3.28.1-01-unix.tar.gz"
}

PLAY RECAP *************************************************************************************************************************************************************************
localhost                  : ok=8    changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```

Correct md5 sum link: https://sonatype-download.global.ssl.fastly.net/repository/downloads-prod-group/3/nexus-3.28.1-01-unix.tar.gz.md5

So it's not the proxy itself neither my network. It'd the combination which @sayantandas described.

So @bmillemathias @croensch this bug report should be analyzed and not be close.
