### ISSUE TITLE
Better handling of tags inside dynamic includes

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#38262]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

core
##### ANSIBLE VERSION

```
2.5
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### SUMMARY

With ansible 2.5 tags on dynamic includes no longer inherited by tasks inside dynamic includes.
I think there is a better non-disruptive solution:
1. Keep `tags:` inheritable, so it would not be a behavioral exception limited to dynamic includes. 
2. Add new parameter to attach tags non-inheritantly, like this:
```
- name: some dynamic stuff
  include_tasks: "base_config_{{ ansible_distribution }}.yaml"
  # these tags will be inherited by all underlying tasks
  tags:
    - base
  # these tags inform ansible-playbook that it may find some of them inside
  lookup_tags:
    - logind
    - systemd
    - rcd
```

**Comment by bcoca** [comment]
We are looking at a feature that would set keywords for the included tasks to inherit, not just for tags:

```
- include_task: 
     file: whtvr.yml
     inherit: #let the bikeshed begin
          tags: ['other']
          become: false
          delegate_to: localhost
          when: whytorunincludedtasks|bool
  tags: ['doinclude']
  when: whytoruntheinclude|bool
```
