### ISSUE TITLE
dellos6_config fails with `"err": "socket_path does not exist or cannot be found"` 

### ISSUE THREAD

**Issue by squeeb** [ansible/ansible#38265]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

dellos6_config

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/squeeb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 10 2018, 00:01:04) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/Users/squeeb/Code/ansible/routers/ansible.cfg) =
[u'/Users/squeeb/Code/ansible/routers/hosts']
DEFAULT_TIMEOUT(/Users/squeeb/Code/ansible/routers/ansible.cfg) = 60
HOST_KEY_CHECKING(/Users/squeeb/Code/ansible/routers/ansible.cfg) = False
```
##### OS / ENVIRONMENT

```
Darwin Clegg.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
```

##### SUMMARY

using the existing `connection: local` or the new `connection: network_cli`, tasks involving the `dellos9_config` module appear to yield the following errors: 

```
TASK [dnos6_switch : configure vlans] ****************************************************************************************************
failed: [some-dellos6-switch] (item={u'name': u'lights-out-management', u'vid': 2}) => {"changed": false, "err": "socket_path does not exist or cannot be found", "item": {"name": "lights-out-management", "vid": 2}, "msg": "unable to enter configuration mode"}
```
##### STEPS TO REPRODUCE

The task involved is: 

```yaml
- name: 'set the terminal length to 0'
  dellos6_command:
    commands:
      - 'terminal length 0'

- name: 'configure vlans'
  dellos6_config:
    parents:
      - 'vlan {{ item.vid }}'
    lines:
      - 'name {{ item.name }}'
  with_items: '{{ vlans }}'
  when:
    - 'vlans is defined'
  changed_when: false
  tags: 'vlans'
```
with the following variables:
```yaml
vlans:
  - name: 'lights-out-management'
    vid: 2
```

This doesn't appear to affect `dellos6_command` which still remains responsive. 
Also, small commands such as: 
```yaml
- name: 'configure hostname'
  dellos6_config:
    lines:
      - 'hostname "{{ inventory_hostname_short }}"'
      - 'ip domain-name "{{ domain_name }}"'
    save: true
```
appear to run, although they take _much_ longer to complete. 

```
$ ansible-playbook oob-switches.yml -u username -k
SSH password: *****
PLAY [oob-switches] **********************************************************************************************************************

TASK [dellos6_switch : set the terminal length to 0]
ok: [some-dellos6-switch]

TASK [dnos6_switch : configure hostname] *************************************************************************************************
changed: [some-dellos6-switch]

TASK [dnos6_switch : configure vlans] ****************************************************************************************************
failed: [some-dellos6-switch] (item={u'name': u'lights-out-management', u'vid': 2}) => {"changed": false, "err": "socket_path does not exist or cannot be found", "item": {"name": "lights-out-management", "vid": 2}, "msg": "unable to enter configuration mode"}

PLAY RECAP *******************************************************************************************************************************
some-dellos6-switch      : ok=1    changed=1    unreachable=0    failed=1
```

##### EXPECTED RESULTS
configuration to complete

##### ACTUAL RESULTS

See above

```

```
This may have something to do with parsing terminal output when terminal length isn't set to 0. 

For instance, if I add the following task right before the failing task: 
```
- name: 'set the terminal length to 0'
  dellos6_command:
    commands:
      - 'terminal length 0'
```
The task completes. 
This appears to have to be done before each task involving a configuration.
