### ISSUE TITLE
 Unarchive takes too much time

### ISSUE THREAD

**Issue by Alexhha** [ansible/ansible#38267]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Unarchive

##### ANSIBLE VERSION
```
# ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
All defaults

##### OS / ENVIRONMENT
Ubuntu: 16.04

##### SUMMARY
Unarchive takes too much time, 10x more than plain unzip command

##### STEPS TO REPRODUCE
1. Create archive with 200k+ files
2. Run the following command ```ansible-playbook -i hosts.ini unzip.yml```

```yaml
- name: EXTRACT TEST ZIP
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Start extracting
      shell: date -u '+%Y.%m.%d %H:%M:%S'
      register: start_time

    - debug: msg="{{ start_time.stdout }}"

    - name: Extract test zip
      unarchive:
        src: /opt/250k.zip
        dest: /opt/dst/
        remote_src: yes

    - name: End extracting
      shell: date -u '+%Y.%m.%d %H:%M:%S'
      register: end_time

    - debug: msg="{{ end_time.stdout }}"
```

##### EXPECTED RESULTS
The task should take approximate the same time as unzip command, but it doesn't. It takes much more. For e.g.
```bash
$ du -h 250k.zip 
1,1G	     250k.zip

$ unzip -l 250k.zip | grep -v -E '/$' -c
253535

$ time unzip -q 250k.zip 

real	0m53.728s
user	0m13.272s
sys	0m23.924s
```

The same thing with simple python script
```python
# -*- coding: utf-8 -*-
from zipfile import ZipFile

zip_file = ZipFile('./250k.zip', 'r')
zip_file.extractall('./')
zip_file.close()
```

```bash
$ time python unzip.py

real	0m57.786s
user	0m24.548s
sys	0m22.212s
```

##### ACTUAL RESULTS
As you can see - it took about 40 minutes
```bash
$ ansible-playbook -i hosts.ini unzip.yml

PLAY [EXTRACT TEST ZIP] ****************************************************************

TASK [Start extracting] ****************************************************************
changed: [localhost]

TASK [debug] ***************************************************************************
ok: [localhost] => {
    "msg": "2018.04.04 10:33:05"
}

TASK [Extract test zip] ****************************************************************
changed: [localhost]

TASK [End extracting] ******************************************************************
changed: [localhost]

TASK [debug] ***************************************************************************
ok: [localhost] => {
    "msg": "2018.04.04 11:12:53"
}

PLAY RECAP *****************************************************************************
localhost                  : ok=5    changed=3    unreachable=0    failed=0
```
