### ISSUE TITLE
ansible 2.5: lineinfile broken

### ISSUE THREAD

**Issue by philfry** [ansible/ansible#38274]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### OS / ENVIRONMENT
CentOS 7.4 x86_64 and Fedora 27 x86_64

##### SUMMARY
lineinfile throws an error when operating either on an empty file or a file only containing the requested line.

##### STEPS TO REPRODUCE
```yaml
---         
- hosts: local                                                                             
  gather_facts: no
  tasks:   
    - file: path=/tmp/foo state=absent
    - lineinfile:
        path: /tmp/foo
        create: yes
        insertbefore: BOF
        line: "# mimimi"
      with_items: [1,2]
```
##### EXPECTED RESULTS
```
TASK [lineinfile] *************************************************************************
--- before: /tmp/foo (content)
+++ after: /tmp/foo (content)
@@ -0,0 +1 @@
+# mimimi
TASK [lineinfile] *************************************************************************
ok: [localhost]
```

##### ACTUAL RESULTS
```
Traceback (most recent call last):
File "/tmp/ansible_t3LN0N/ansible_module_lineinfile.py", line 512, in <module>
    main()
  File "/tmp/ansible_t3LN0N/ansible_module_lineinfile.py", line 503, in main
    ins_aft, ins_bef, create, backup, backrefs, firstmatch)
  File "/tmp/ansible_t3LN0N/ansible_module_lineinfile.py", line 337, in present
    elif b_lines[index[1] - 1].rstrip(b('\r\n')) != b_line:
IndexError: list index out of range
```
