### ISSUE TITLE
set_fact and with_items broken

### ISSUE THREAD

**Issue by NomAnor** [ansible/ansible#38271]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
set_fact

##### ANSIBLE VERSION
```
ansible 2.6.0 (detached HEAD 3bec76fc85) last updated 2018/04/04 14:21:07 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [' /xxx/src/ansible/library']
  ansible python module location =   #xxx/src/ansible/lib/ansible
  executable location = xxx/src/ansible/bin/ansible
  python version = 3.6.4 (default, Jan  5 2018, 02:35:40) [GCC 7.2.1 20171224]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Appending to a list in set_fact using with_items is broken.

##### STEPS TO REPRODUCE
Run this playbook.

```yaml
---
- name: test set_fact bug
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    - dig_list:
      - one

    - digits:
      - two
      - three
      - four
  tasks:

    - name: test bug
      set_fact:
        dig_list: "{{ dig_list + [ digit ] }}"
      with_items: "{{ digits }}"
      loop_control:
        loop_var: digit

    - debug: msg="{{ dig_list }}"

```
##### EXPECTED RESULTS
An Array `['one', ..., 'four']`

##### ACTUAL RESULTS
An Array `['one', 'four']`

See also #23624. This breaks one of my roles.
Git bisect shows me that #37538 breaks this.
