### ISSUE TITLE
"become: no" doesn't work on eos modules with "connection=local"

### ISSUE THREAD

**Issue by newswangerd** [ansible/ansible#38284]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

eos_terminal

##### ANSIBLE VERSION

```
ansible 2.6.0 (eos_smoke f068f69e02) last updated 2018/04/04 11:19:03 (GMT -400)
  config file = None
  configured module search path = [u'/Users/david/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/david/code/ansible/lib/ansible
  executable location = /Users/david/code/ansible/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### STEPS TO REPRODUCE

Run the following playbook using connection=local or eapi. 

```yaml
- name: command that does require become (should fail)
  eos_command:
    commands: show running-config
    provider: "{{ eapi }}"
  become: no
  ignore_errors: yes
  register: result

- assert:
    that:
      - 'result.failed == true'
      - '"privileged mode required" in result.module_stderr'
```

##### EXPECTED RESULTS

`show running-config` should require enable and return a priviledge escalation error. 

##### ACTUAL RESULTS

The command runs as though it was in priviledge mode, when in reality it should fail.

```

```
