### ISSUE TITLE
vmware_guest_find has required, deprecated parameter

### ISSUE THREAD

**Issue by jhriv** [ansible/ansible#38290]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest_find

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/jhriv/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jhriv/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/jhriv/ansible/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### OS / ENVIRONMENT

Distributor ID:	Debian
Description:	Debian GNU/Linux 9.4 (stretch)
Release:	9.4
Codename:	stretch

##### SUMMARY

`vmware_gest_find` with datacenter: parameter:
>DEPRECATION WARNING]: Param 'datacenter' is deprecated. See the module docs for more information. This feature will
be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

`vmware_gest_find` without datacenter: parameter:
> fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: datacenter"}

##### STEPS TO REPRODUCE

Follow the example on http://docs.ansible.com/ansible/latest/modules/vmware_guest_find_module.html

The "datacenter:" parameter is missing

```yaml
# From upstream documentation
- name: Find Guest's Folder using name
  vmware_guest_find:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    validate_certs: no
    name: testvm
  register: vm_folder

- name: Find Guest's Folder using UUID
  vmware_guest_find:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    validate_certs: no
    uuid: 38c4c89c-b3d7-4ae6-ae4e-43c5118eae49
  register: vm_folder
```

##### EXPECTED RESULTS

```
 _______________________________________
< TASK [Find Guest's Folder using name] >
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
```
##### ACTUAL RESULTS

Error

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: datacenter"}
```
