### ISSUE TITLE
jinja2 combine fails when become: true

### ISSUE THREAD

**Issue by yvmori1** [ansible/ansible#38294]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

jinja2 combine

##### ANSIBLE VERSION

```
ansible 2.4.0.0
  config file = /home/txt21674/.ansible.cfg
  configured module search path = [u'/home/txt21674/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

ansible 2.4.0.0
  config file = /home/txt21674/.ansible.cfg
  configured module search path = [u'/home/txt21674/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
[txt21674@mtl-ptcdev01d CN_streams]$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/home/txt21674/.ansible.cfg) = [u'/home/txt21674/inventory/hosts']

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Joining hashes while using the jinja2 combine fails when become: true

##### STEPS TO REPRODUCE

```yaml
---

- hosts: localhost
  connection: local
  become: true
  become_method: sudo
  become_user: root
  gather_facts: yes

  tasks:
  - set_fact:
      base_vgs:
        'rootvg':
          size: '30'
          sd: 'sda'
        'datavg':
          size: '30'
          sd: 'sdb'
      apps_vgs:
        'app1vg':
          size: '30'
          sd: 'sdc'
        'app2vg':
          size: '40'
          sd: 'sdd'
        'app3vg':
          size: '50'
          sd: 'sde'

  - set_fact:
      dir_list: {}
      pattern: '.*_vgs$'
      
  - name: Join hases
    set_fact:
      dir_list: "{{ dir_list | combine(hostvars[inventory_hostname][item], recursive=true) }}"
    with_items: "{{ hostvars[inventory_hostname].keys() | map('regex_search', pattern) | select('string') | list }}"
   
  # Just printing result here...
  - debug:
      msg: "{{ dir_list }}"
```

##### EXPECTED RESULTS

I expect base_vgs and apps_vgs to be combined into dir_list

##### ACTUAL RESULTS

```
ansible-playbook 2.4.0.0
  config file = /home/txt21674/.ansible.cfg
  configured module search path = [u'/home/txt21674/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /home/txt21674/.ansible.cfg as config file
Parsed /cnunix/integ/txt11688/phoenix/CN_streams/inventory/local.yml inventory source with ini plugin

PLAYBOOK: group_membership.yml *************************************************************************************************************************************************************************************************************
1 plays in group_membership.yml

PLAY [localhost] ***************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************************************************************************************************************
Using module file /usr/lib/python2.7/site-packages/ansible/modules/system/setup.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: txt21674
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/txt21674/.ansible/tmp/ansible-tmp-1522865581.18-124389062229947 `" && echo ansible-tmp-1522865581.18-124389062229947="` echo /home/txt21674/.ansible/tmp/ansible-tmp-1522865581.18-124389062229947 `" ) && sleep 0'
<127.0.0.1> PUT /tmp/tmpUt84wr TO /home/txt21674/.ansible/tmp/ansible-tmp-1522865581.18-124389062229947/setup.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/txt21674/.ansible/tmp/ansible-tmp-1522865581.18-124389062229947/ /home/txt21674/.ansible/tmp/ansible-tmp-1522865581.18-124389062229947/setup.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-keofqzsdqoxjmdtbxlivmkpqtphlgirb; /usr/bin/python2 /home/txt21674/.ansible/tmp/ansible-tmp-1522865581.18-124389062229947/setup.py; rm -rf "/home/txt21674/.ansible/tmp/ansible-tmp-1522865581.18-124389062229947/" > /dev/null 2>&1'"'"' && sleep 0'
ok: [localhost]
META: ran handlers

TASK [set_fact] ****************************************************************************************************************************************************************************************************************************
task path: /cnunix/integ/txt11688/phoenix/CN_streams/group_membership.yml:11
ok: [localhost] => {
    "ansible_facts": {
        "apps_vgs": {
            "app1vg": {
                "sd": "sdc",
                "size": "30"
            },
            "app2vg": {
                "sd": "sdd",
                "size": "40"
            },
            "app3vg": {
                "sd": "sde",
                "size": "50"
            }
        },
        "base_vgs": {
            "datavg": {
                "sd": "sdb",
                "size": "30"
            },
            "rootvg": {
                "sd": "sda",
                "size": "30"
            }
        }
    },
    "changed": false,
    "failed": false
}

TASK [set_fact] ****************************************************************************************************************************************************************************************************************************
task path: /cnunix/integ/txt11688/phoenix/CN_streams/group_membership.yml:30
ok: [localhost] => {
    "ansible_facts": {
        "dir_list": {},
        "pattern": ".*_vgs$"
    },
    "changed": false,
    "failed": false
}

TASK [Join hases] **************************************************************************************************************************************************************************************************************************
task path: /cnunix/integ/txt11688/phoenix/CN_streams/group_membership.yml:34
ok: [localhost] => (item=base_vgs) => {
    "ansible_facts": {
        "dir_list": {
            "datavg": {
                "sd": "sdb",
                "size": "30"
            },
            "rootvg": {
                "sd": "sda",
                "size": "30"
            }
        }
    },
    "ansible_facts_cacheable": false,
    "changed": false,
    "failed": false,
    "item": "base_vgs"
}
ok: [localhost] => (item=apps_vgs) => {
    "ansible_facts": {
        "dir_list": {
            "app1vg": {
                "sd": "sdc",
                "size": "30"
            },
            "app2vg": {
                "sd": "sdd",
                "size": "40"
            },
            "app3vg": {
                "sd": "sde",
                "size": "50"
            },
            "datavg": {
                "sd": "sdb",
                "size": "30"
            },
            "rootvg": {
                "sd": "sda",
                "size": "30"
            }
        }
    },
    "ansible_facts_cacheable": false,
    "changed": false,
    "failed": false,
    "item": "apps_vgs"
}
fatal: [localhost]: FAILED! => {
    "failed": true,
    "msg": "|combine expects dictionaries, got 2"
}
        to retry, use: --limit @/cnunix/integ/txt11688/phoenix/CN_streams/group_membership.retry

PLAY RECAP *********************************************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=1
```
