### ISSUE TITLE
VMware: vmware_resource_pool: cluster_name should not be required

### ISSUE THREAD

**Issue by corbinstuard** [ansible/ansible#38300]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_host
vmware_resource_pool

##### ANSIBLE VERSION
```
ansible 2.6.0 (devel 873a9ddf8d) last updated 2018/04/03 16:23:46 (GMT -400)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/seit31/ansible/lib/ansible
  executable location = /home/seit31/ansible/bin/ansible
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = False
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=2000s
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = /tmp/%%h-%%p-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR(/etc/ansible/ansible.cfg) = /tmp
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/filter_plugins']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
N/A

##### SUMMARY
A cluster is not required for creating a resource pool or adding a host to vcenter.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_host.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dagwieers @dav1x @jctanner @tchernomax
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by corbinstuard** [comment]
The same issue is present in vmware_resource_pool

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_host.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host.py)
* [lib/ansible/modules/cloud/vmware/vmware_resource_pool.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_resource_pool.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
- [x] vmware_host - #39490
- [ ] vmware_resource_pool

**Comment by Akasurde** [comment]
@corbinstuard Can you check if above PR works for you ? also, can you please explain use case of resource_pool module without cluster ?

**Comment by corbinstuard** [comment]
@Akasurde i shouldnt need to specify a folder either, datacenter and esxi host should be enough. cluster_name should be optional for when your hosts are part of a cluster. i can add hosts directly to a datacenter and resource pools to those hosts, without any cluster existing in the first place. something like this:

```yaml
vmware_host:
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_user }}"
      password: "{{ vcenter_pass }}"
      esxi_hostname: "{{ esxi_host }}"
      esxi_username: "{{ esxi_user }}"
      esxi_password: "{{ esxi_pass }}"
      datacenter_name: "{{ vcenter_datacenter }}"
```

**Comment by corbinstuard** [comment]
upon review, this change looks fine

**Comment by ansibot** [comment]
cc @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by corbinstuard** [comment]
Please reopen, this is a partial fix for one of the modules specified.

**Comment by ckotte** [comment]
@corbinstuard 

Do you want to create resource pools for standalone hosts or what's the exact issue you have?

What's the problem with specifying the datacenter and the folder?

For example:
```
datacenter_name: "{{ vcenter_datacenter }}"
folder_name: "/{{ vcenter_datacenter }}/host"
```

**Comment by corbinstuard** [comment]
@ckotte 

Nothing is wrong with that, it sounds perfect for vmware_host since the folder_name parameter would dictate where the new vm's are placed in vCenter, correct?  I'm unsure how the folder_name parameter would interface with the vmware_resource_pool module though, as I don't think resource pools exist in vCenter folders.

**Comment by ckotte** [comment]
@corbinstuard 
 
> Nothing is wrong with that, it sounds perfect for vmware_host since the folder_name parameter would dictate where the new vm's are placed in vCenter, correct? I'm unsure how the folder_name parameter would interface with the vmware_resource_pool module though, as I don't think resource pools exist in vCenter folders.

Sorry, I made a mistake. You were asking about `cluster_name`. I use `vmware_host` to connect ESXi hosts to staging folders...

You need to specify either `folder_name` or `cluster_name`. Is this ok? I just ask because I have a PR open and I could make some additional changes to fix this issue. 

Looks like you only have an issue with the resource pool module and you want to be able to create a resource pool for a standalone host, right? Something like this?:
```
- name: Add resource pool to vCenter
  vmware_resource_pool:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ datacenter_name }}'
    esxi_hostname: '{{ esxi_name }}'
    resource_pool: '{{ resource_pool_name }}'
    mem_shares: normal
    mem_limit: -1
    mem_reservation: 0
    mem_expandable_reservations: yes
    cpu_shares: normal
    cpu_limit: -1
    cpu_reservation: 0
    cpu_expandable_reservations: yes
    state: present
  delegate_to: localhost
```
The module currently only supports creating resource pools at cluster-level.
