### ISSUE TITLE
ios_system idempotency issues with several domain commands

### ISSUE THREAD

**Issue by EricThiel** [ansible/ansible#38301]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_system

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /nas/ansible/lab/ansible.cfg
  configured module search path = [u'/home/cisco/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

DEFAULT_HOST_LIST(/nas/ansible/lab/ansible.cfg) = [u'/nas/ansible/lab/hosts']
DEFAULT_ROLES_PATH(/nas/ansible/lab/ansible.cfg) = [u'/nas/ansible/lab']
HOST_KEY_CHECKING(/nas/ansible/lab/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/nas/ansible/lab/ansible.cfg) = 50
PERSISTENT_CONNECT_TIMEOUT(/nas/ansible/lab/ansible.cfg) = 60

##### OS / ENVIRONMENT

N/A
Cisco IOS Software, IOS-XE Software, Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 03.03.05SE RELEASE SOFTWARE (fc1)
Catalyst 3850

##### SUMMARY

Module is not always idempotent for domain_name, domain_search, lookup_source, and lookup_enabled due to multiple syntax options for those commands.
 
##### STEPS TO REPRODUCE

Running any playbook with lookup_enabled: no, or with domain_name, domain_search, or lookup_source defined will falsely detect changes with each run. 

```yaml
tasks:
  - name: Configure system domain details
    ios_system:
      domain_name: test.mylab.com
      lookup_source: "Vlan100"
      domain_search: "test.com"
      lookup_enabled: no

  - name: Configure system domain details again
    ios_system:
      domain_name: test.mylab.com
      lookup_source: "Vlan100"
      domain_search: "test.com"
      lookup_enabled: no

```

##### EXPECTED RESULTS

The second and subsequent runs should not apply the same config again. 

##### ACTUAL RESULTS

Module does not detect the existing config because it only checks one of two ways to set that configuration. For example, when it applies "no ip domain lookup" the switch converts it to "no ip domain-lookup". 

```
PLAY [Enforce base Lab config] ****************************************************************************************************************************************************

TASK [ios_baseline_3850 : Configure system domain details] ************************************************************************************************************************
changed: [1.2.3.4] => {"changed": true, "commands": ["ip domain lookup source-interface Vlan100", "no ip domain lookup", "ip domain name test.mylab.com", "ip domain list test.com"]}

TASK [ios_baseline_3850 : Configure system domain details again] ******************************************************************************************************************
changed: [1.2.3.4] => {"changed": true, "commands": ["ip domain lookup source-interface Vlan100", "no ip domain lookup", "ip domain name test.mylab.com", "ip domain list test.com"]}


```
