### ISSUE TITLE
Loop over lookup('dict', variable) fails when variable denotes a dictionary with only one (key, value) pair

### ISSUE THREAD

**Issue by mjpalacios** [ansible/ansible#38306]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

dict plugin

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/nolo/.ansible.cfg
  configured module search path = [u'/home/nolo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
DEFAULT_FORKS(/home/nolo/.ansible.cfg) = 50 
DEFAULT_GATHERING(/home/nolo/.ansible.cfg) = smart
DEFAULT_LOG_PATH(/home/nolo/.ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/home/nolo/.ansible.cfg) = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_ROLES_PATH(/home/nolo/.ansible.cfg) = [u'/home/nolo/prj/devops/ansible/roles']
DEFAULT_SCP_IF_SSH(/home/nolo/.ansible.cfg) = true
HOST_KEY_CHECKING(/home/nolo/.ansible.cfg) = False
RETRY_FILES_ENABLED(/home/nolo/.ansible.cfg) = True

##### OS / ENVIRONMENT
Linux silmaril 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

Loop over lookup('dict', variable) fails when variable denotes a dictionary with only one (key, value) pair

##### STEPS TO REPRODUCE

```yaml
#
# PLAYBOOK:
#
# pb_loop_dict.yml - Sample playbook showing Ansible bug when looping over dictionary with only one key-value

- hosts: localhost
  vars:
    single_key_dict:
      key-1: "value-1"
    multi_key_dict:
      key-1: "value-1"
      key-2: "value-2"
  tasks:
  - name: Iterate over multiple-key dictionary using loop with 'dict' lookup - succeeds
    vars:
      cur_item: "key={{current_item.key}} value={{current_item.value}}"
    debug: var=cur_item
    loop:
      "{{lookup('dict', multi_key_dict)}}"
    loop_control:
      loop_var: current_item
  - name: Iterate over single-key dictionary using loop with 'dict' lookup - fails
    vars:
      cur_item: "key={{current_item.key}} value={{current_item.value}}"
    debug: var=cur_item
    loop:
      "{{lookup('dict', single_key_dict)}}"
    loop_control:
      loop_var: current_item

#
#COMMAND:
#
ansible-playbook -v pb_loop_dict.yml

```

##### EXPECTED RESULTS

Using /home/nolo/.ansible.cfg as config file

PLAY [localhost] **************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************
ok: [localhost]

TASK [Iterate over multiple-key dictionary using loop with 'dict' lookup] **************************************************************************************************************
ok: [localhost] => (item={'key': u'key-2', 'value': u'value-2'}) => {
    "cur_item": "key=key-2 value=value-2", 
    "current_item": {
        "key": "key-2", 
        "value": "value-2"
    }
}
ok: [localhost] => (item={'key': u'key-1', 'value': u'value-1'}) => {
    "cur_item": "key=key-1 value=value-1", 
    "current_item": {
        "key": "key-1", 
        "value": "value-1"
    }
}

TASK [Iterate over single-key dictionary using loop with 'dict' lookup] **************************************************************************************************************
ok: [localhost] => (item={'key': u'key-1', 'value': u'value-1'}) => {
    "cur_item": "key=key-1 value=value-1", 
    "current_item": {
        "key": "key-1", 
        "value": "value-1"
    }
}

##### ACTUAL RESULTS

```
Using /home/nolo/.ansible.cfg as config file

PLAY [localhost] **************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************
ok: [localhost]

TASK [Iterate over multiple-key dictionary using loop with 'dict' lookup] **************************************************************************************************************
ok: [localhost] => (item={'key': u'key-2', 'value': u'value-2'}) => {
    "cur_item": "key=key-2 value=value-2", 
    "current_item": {
        "key": "key-2", 
        "value": "value-2"
    }
}
ok: [localhost] => (item={'key': u'key-1', 'value': u'value-1'}) => {
    "cur_item": "key=key-1 value=value-1", 
    "current_item": {
        "key": "key-1", 
        "value": "value-1"
    }
}

TASK [Iterate over single-key dictionary using loop with 'dict' lookup] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Invalid data passed to 'loop' it requires a list, got this instead: {'key': u'key-1', 'value': u'value-1'}"}
	to retry, use: --limit @/home/nolo/prj/devops/ansible/pb_loop_dict.retry

PLAY RECAP **************************************************************************************************************llocalhost                  : ok=2    changed=0    unreachable=0    failed=1   

```
