### ISSUE TITLE
Ansible 2.5: azure_rm_publicip_facts doesn't work

### ISSUE THREAD

**Issue by IvanovOleg** [ansible/ansible#38317]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
2.5.0
```

##### OS / ENVIRONMENT

Centos 7, pip install ansible[azure]
##### STEPS TO REPRODUCE

```
- name: Get facts for one Public IP
  local_action:
    module: azure_rm_publicip_facts
    resource_group: "{{ resource_group_name }}"
    name: "{{ public_ip_name }}"
```

##### EXPECTED RESULTS

Get public ip facts
##### ACTUAL RESULTS

```
fatal: [hostname]: FAILED! => {"msg": "The module azure_rm_publicip_facts was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git pull --rebase' to correct this problem."}
```

```

```
