### ISSUE TITLE
manageiq_provider fails while adding an OCP provider

### ISSUE THREAD

**Issue by vestival** [ansible/ansible#38331]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

manageiq_provider

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/remote_management/manageiq/manageiq_provider.py

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/victor/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 15:04:47) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

Nothing changed
##### OS / ENVIRONMENT

N/A
##### SUMMARY

While adding a provider with the type Openshift it fails with the message 
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "failed to create provider OpenShift: Api::BadRequestError: Could not create the new provider - OpenShift api_version cannot be modified"}
```

When you comment (or delete) the api_version from the code, everything works. "api_version" should only be used for OpenStack providers

##### STEPS TO REPRODUCE

Try to add a Openshift provider into your ManageIQ environment.

```yaml
---
- hosts: localhost
  connection: local
  vars: 
    manageiq_user: admin
  vars_prompt:
    - name: "manageiq_url" 
    - name: "ocp_auth_key"
    - name: "manageiq_password"
  tasks:
  - name: Create a new provider in ManageIQ ('Hawkular' metrics)
    manageiq_provider:
      name: 'OpenShift'
      type: 'Openshift'
      provider:
        auth_key: "{{ ocp_auth_key }}"
        hostname: 'ose.example.com'
        port: 8443
        verify_ssl: False
      metrics:
        role: 'hawkular'
        hostname: 'hawkular-metrics.example.com'
        port: 443
        verify_ssl: False
      manageiq_connection:
        url: "{{ manageiq_url }}"
        username: "{{ manageiq_user }}"
        password: "{{ manageiq_password }}" 
        verify_ssl: False
```

##### EXPECTED RESULTS

Task OK

```
PLAY RECAP ********************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
task path: /Users/victor/summit-fy19/playbooks/createOCP.yml:11
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/remote_management/manageiq/manageiq_provider.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: victor
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/victor/.ansible/tmp/ansible-tmp-1522927554.79-120799432528931 `" && echo ansible-tmp-1522927554.79-120799432528931="` echo /Users/victor/.ansible/tmp/ansible-tmp-1522927554.79-120799432528931 `" ) && sleep 0'
<127.0.0.1> PUT /Users/victor/.ansible/tmp/ansible-local-75002Ws618f/tmpPHFbIV TO /Users/victor/.ansible/tmp/ansible-tmp-1522927554.79-120799432528931/manageiq_provider.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/victor/.ansible/tmp/ansible-tmp-1522927554.79-120799432528931/ /Users/victor/.ansible/tmp/ansible-tmp-1522927554.79-120799432528931/manageiq_provider.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python@2/bin/python2.7 /Users/victor/.ansible/tmp/ansible-tmp-1522927554.79-120799432528931/manageiq_provider.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/victor/.ansible/tmp/ansible-tmp-1522927554.79-120799432528931/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/hv/zq6vmgxs7nn29_4ztjz2vggh0000gn/T/ansible_G6eG2I/ansible_module_manageiq_provider.py", line 826, in create_provider
    connection_configurations=endpoints,
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/manageiq_client/api.py", line 119, in post
    return self._result_processor(data)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/manageiq_client/api.py", line 87, in _result_processor
    "{}: {}".format(result_json["error"]["klass"], result_json["error"]["message"]))

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "alerts": null,
            "api_version": null,
            "azure_tenant_id": null,
            "host_default_vnc_port_end": null,
            "host_default_vnc_port_start": null,
            "manageiq_connection": {
                "ca_bundle_path": null,
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "token": null,
                "url": "https://1cfme46-summitrhpdsl1077l1-vwmoc4gz.srv.ravcloud.com",
                "username": "admin",
                "verify_ssl": false
            },
            "metrics": {
                "auth_key": null,
                "certificate_authority": null,
                "hostname": "hawkular-metrics.example.com",
                "password": null,
                "path": null,
                "port": 443,
                "project": null,
                "role": "hawkular",
                "security_protocol": null,
                "subscription": null,
                "uid_ems": null,
                "userid": null,
                "verify_ssl": false
            },
            "name": "OpenShift",
            "project": null,
            "provider": {
                "auth_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "certificate_authority": null,
                "hostname": "ose.example.com",
                "password": null,
                "path": null,
                "port": 8443,
                "project": null,
                "role": null,
                "security_protocol": null,
                "subscription": null,
                "uid_ems": null,
                "userid": null,
                "verify_ssl": false
            },
            "provider_region": null,
            "ssh_keypair": null,
            "state": "present",
            "subscription": null,
            "tenant_mapping_enabled": false,
            "type": "Openshift",
            "zone": "default"
        }
    },
    "msg": "failed to create provider OpenShift: Api::BadRequestError: Could not create the new provider - OpenShift api_version cannot be modified"
}
```
