### ISSUE TITLE
when clause for block does not execute all tasks if conditional changed within block

### ISSUE THREAD

**Issue by amarao** [ansible/ansible#38335]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
block

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/amarao/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14+ (default, Mar 13 2018, 15:23:44) [GCC 7.3.0]
```

##### CONFIGURATION
irrelevant

##### OS / ENVIRONMENT
Ubuntu 18.04

##### SUMMARY
If variable in `when` clause was changed within block, block can be executed only partially.

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  gather_facts: no
  tasks:
   - block:
      - set_fact:
          foo: bar
      - debug: var=foo
     when: foo is not defined
```

`ansible-playbook -i localhost, play.yaml`

##### EXPECTED RESULTS
debug task is expected it be executed.

##### ACTUAL RESULTS
```
TASK [set_fact] ****************************************************************
ok: [localhost]

TASK [debug] *******************************************************************
skipping: [localhost]
```
