### ISSUE TITLE
VMware_guest module requires Folder path for deploying VM

### ISSUE THREAD

**Issue by jamesmarshall24** [ansible/ansible#38358]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.0
```

##### SUMMARY

vmware_guest.py checks the folder path when deploying a new vm:
[vmware_guest.py ln:1741](https://github.com/ansible/ansible/blob/b4debfad9a19da2d28aa58b93897445531c8f886/lib/ansible/modules/cloud/vmware/vmware_guest.py#L1741)

This is not mentioned under within the [vmware_guest_module documentation](http://docs.ansible.com/ansible/latest/modules/vmware_guest_module.html)

##### STEPS TO REPRODUCE

```yaml
- name: Create VM via a template clone
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    validate_certs: "{{ vcenter_cert_validation }}"
    datacenter: "{{ vsphere_datacenter }}"
    cluster: "{{ vsphere_esxi_cluster }}"
    resource_pool: "{{ vsphere_resource_pool }}"
    annotation: "{{ vsphere_annotation }}"
    template: "{{ vshpere_vm_template }}"
    name: "{{ custSpec_vm_hostname }}"
    hardware:
      memory_mb: "{{ vm_memory_mb }}"
      num_cpus: "{{ vm_num_cpus }}"
    networks:
    - name: "{{ vsphere_network_name }}"
      device_type: vmxnet3
      ip: "{{ infoblox_ip }}"
      netmask: "{{ infoblox_netmask }}"
      gateway: "{{ infoblox_gateway }}"
      dns_servers: "{{ dns_servers }}"
    disk:
    - datastore: "{{ vsphere_datastore }}"
      size_gb: "{{ vm_disk_size_gb }}"
      type: thin
    state: poweredon
    wait_for_ip_address: yes
```

##### EXPECTED RESULTS

VM is deployed without an error

##### ACTUAL RESULTS

```
"msg": "Folder is required parameter while deploying new virtual machine"
```
