### ISSUE TITLE
Using old data from cache even after updating file

### ISSUE THREAD

**Issue by imshyam** [ansible/ansible#38394]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

set_fact, vars, lineinfile

##### ANSIBLE VERSION

```
2.4.1
```

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY

Old cache data is being used in the next task, even when value is updated.

##### STEPS TO REPRODUCE

my_playbook.yml: 
```yaml
- hosts: localhost
  vars_files:
    - ./vars/main.yml
  tasks:
    - debug: msg={{ VAR }}
    - lineinfile:
        path: ./vars/main.yml
        regexp: '^VAR:.*'
        line: 'VAR: "newval"'

- hosts: localhost
  vars_files:
    - ./vars/main.yml
  tasks:
    - debug: msg={{ VAR }}
```

vars/main.yml:
```yml
VAR: "oldval"
```

##### EXPECTED RESULTS

```
PLAY [localhost] ****************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************
ok: [localhost] => {
    "msg": "oldval"
}

TASK [lineinfile] ***************************************************************************************
changed: [localhost]

PLAY [localhost] ****************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************
ok: [localhost] => {
    "msg": "newval"
}

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->
PLAY [localhost] ****************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************
ok: [localhost] => {
    "msg": "oldval"
}

TASK [lineinfile] ***************************************************************************************
changed: [localhost]

PLAY [localhost] ****************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [localhost]

TASK [debug] ********************************************************************************************
ok: [localhost] => {
    "msg": "oldval"
}
```

```
ansible-playbook my_playbook.yml
```

The value in the vars/main.yml file is updated but it's not updated for the task.
