### ISSUE TITLE
bigip_pool_member "provider" dictionary doesn't work

### ISSUE THREAD

**Issue by rlueckl** [ansible/ansible#38392]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Module: bigip_pool_member (possibly other bigip_* modules)

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

Other versions:
```
bigsuds 1.0.4
bigsuds 1.0.6
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Linux Mint 18 Sarah

##### SUMMARY
Using the `provider` dict for bigip_pool_member (new in 2.5.0) doesn't work with bigsuds 1.0.4 or 1.0.6 (latest). Using "old-style" config works.

##### STEPS TO REPRODUCE
Run the following playbook(s) against any F5 setup (with correct values of course).

Works in 2.5.0, but gives deprecation warnings (see below):
```yaml
  - name: disable node in F5
    local_action:
      module: bigip_pool_member
      server: "{{ f5_lb_host[dc] }}"
      user: "{{ f5_user }}"
      password: "{{ f5_pass }}"
      session_state: "disabled"
      monitor_state: "disabled"
      pool: "{{ item['name'] }}"
      partition: "{{ f5_partition }}"
      host: "{{ ansible_fqdn }}"
      port: "{{ item['port'] }}"
      validate_certs: False
    with_items: "{{ f5_service_pool }}"
```

Result:
```
TASK [deploy-host : disable node in F5] ******
changed: [myhostname01 -> localhost] => (item={u'name': u'pool_https_mypool.int.lan', u'port': 443})
[DEPRECATION WARNING]: Param 'user' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'password' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'server' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: Param 'validate_certs' is deprecated. See the module docs for more information. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

Doesn't work in 2.5.0, but according to docs it should:
```yaml
  - name: disable node in F5
    local_action:
      module: bigip_pool_member
      provider:
        server: "{{ f5_lb_host[dc] }}"
        user: "{{ f5_user }}"
        password: "{{ f5_pass }}"
        validate_certs: False
        transport: "rest"
      session_state: "disabled"
      monitor_state: "disabled"
      pool: "{{ item['name'] }}"
      partition: "{{ f5_partition }}"
      host: "{{ ansible_fqdn }}"
      port: "{{ item['port'] }}"
    with_items: "{{ f5_service_pool }}"
```

Result:
```
TASK [deploy-host : disable node in F5] ******
failed: [myhostname01 -> localhost] (item={u'name': u'pool_https_mypool.int.lan', u'port': 443}) => {"changed": false, "item": {"name": "pool_https_mypool.int.lan", "port": 443}, "msg": "received exception: <urlopen error [Errno -3] Temporary failure in name resolution>"}
```

##### EXPECTED RESULTS
The second playbook should work, too.

##### ACTUAL RESULTS
Got the error "Temporary failure in name resolution".

```
TASK [deploy-host : disable node in F5] ************************************************************************************************************************************************************************************************************************************
task path: /home/myuser/git/ansible-tools/roles/deploy-singletc/tasks/balancing_disable_f5lb.yaml:2
<localhost> connection transport is rest
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/f5/bigip_pool_member.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: myuser
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/myuser/.ansible/tmp/ansible-tmp-1523012416.04-206350433138521 `" && echo ansible-tmp-1523012416.04-206350433138521="` echo /home/myuser/.ansible/tmp/ansible-tmp-1523012416.04-206350433138521 `" ) && sleep 0'
<localhost> PUT /home/myuser/.ansible/tmp/ansible-local-11987TDg7Yx/tmpABYFLj TO /home/myuser/.ansible/tmp/ansible-tmp-1523012416.04-206350433138521/bigip_pool_member.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/myuser/.ansible/tmp/ansible-tmp-1523012416.04-206350433138521/ /home/myuser/.ansible/tmp/ansible-tmp-1523012416.04-206350433138521/bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/myuser/.ansible/tmp/ansible-tmp-1523012416.04-206350433138521/bigip_pool_member.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/myuser/.ansible/tmp/ansible-tmp-1523012416.04-206350433138521/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_XEeE29/ansible_module_bigip_pool_member.py", line 467, in main
    if not pool_exists(api, pool):
  File "/tmp/ansible_XEeE29/ansible_module_bigip_pool_member.py", line 211, in pool_exists
    api.LocalLB.Pool.get_object_status(pool_names=[pool])
  File "/usr/local/lib/python2.7/dist-packages/bigsuds.py", line 360, in __getattr__
    client = self._client_creator('%s.%s' % (self._name, attr))
  File "/usr/local/lib/python2.7/dist-packages/bigsuds.py", line 170, in _create_client
    raise ConnectionError(str(e))

failed: [myhostname01 -> localhost] (item={u'name': u'pool_https_mypool.int.lan', u'port': 443}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "connection_limit": null, 
            "description": null, 
            "host": "myhostname01.int.lan",           
            "monitor_state": "disabled", 
            "partition": "mypartition",
            "password": null, 
            "pool": "pool_https_mypool.int.lan",             
            "port": 443, 
            "preserve_node": false, 
            "priority_group": null, 
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
                "server": "F5_HOSTNAME_RESOLVED_CORRECTLY_FROM_VARIABLE",
                "server_port": 443, 
                "ssh_keyfile": null, 
                "timeout": 10, 
                "transport": "rest", 
                "user": "F5_USERNAME_RESOLVED_CORRECTLY_FROM_VARIABLE",
                "validate_certs": false
            }, 
            "rate_limit": null, 
            "ratio": null, 
            "server": null, 
            "server_port": 443, 
            "session_state": "disabled", 
            "state": "present", 
            "transport": "rest", 
            "user": null, 
            "validate_certs": null
        }
    }, 
    "item": {
        "name": "pool_https_mypool.int.lan",             
        "port": 443
    }, 
    "msg": "received exception: <urlopen error [Errno -3] Temporary failure in name resolution>"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/f5/bigip_pool_member.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/f5/bigip_pool_member.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @caphrim007
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rlueckl** [comment]
It seems to me that `module.params` in **lib/ansible/modules/network/f5/bigip_pool_member.py** wasn't updated to reflect the changes in configuration. Basically `module_args` is correct, but `module.params` doesn't use it.

Starting with line 438 you have:
`server = module.params['server']`
which would be correct for the "old-style" config, but it should read:
`server = module.params['provider']['server']`
for the "new-style".

Actually both, because the old style is only deprecated but won't be removed until 2.9

**Comment by caphrim007** [comment]
@rlueckl yes, provider in 2.5.0 was broken. Though, I believe it is fixed in the side-band repo where F5 does their work here

https://github.com/F5Networks/f5-ansible

We upstream that work for major releases of Ansible. Note that the module you see in that repo is not a drop-in replacement. To use it, you need to tell Ansible about it as well as the module_utils and action plugins (the bug you see is actually not in the module, but in the supporting code).

There are instructions for telling ansible how to use that repo here

http://clouddocs.f5.com/products/orchestration/ansible/devel/usage/installing-modules.html#method-1-install-in-a-relative-location-recommended

**Comment by rlueckl** [comment]
Thanks for the information! I'll try it out.

Otherwise I think I'll wait for 2.6, no rush to upgrade from 2.4
I just wanted to see what new stuff there is in 2.5

**Comment by MichalTaratuta** [comment]
@caphrim007 any chance to push a fix with a **minor** release?

Additionlly I don't belive that the `validate_certs` is working correctly for this module. i.e the module works without `validate_certs: false` which is needed in my setup, all other F5 modules breake down without it.

**Comment by AndreasDavour** [comment]
This is still broken in 2.6

**Comment by caphrim007** [comment]
@AndreasDavour, if something is not working, providing a reproduction of the problem, relevant to your environment, is helpful

**Comment by rlueckl** [comment]
@AndreasDavour Can't confirm with 2.6.1 - works fine for me. Did you change your playbook according to the new configuration? ("provider" dict with server/user/password)

**Comment by AndreasDavour** [comment]
I did indeed. I will try to construct a sanitized example.

**Comment by AndreasDavour** [comment]
It turns out I did most of my testing using the bigip_facts module. I kind of expect the code to use the authentication process to be shared, but maybe it's not the case?

**Comment by rlueckl** [comment]
Sorry, I've only used the bigip_pool_member so far. Didn't need bigip_facts until now. This is my code, it's included in another playbook with "include_tasks":

```
---
  - name: disable node in F5
    local_action:
      module: bigip_pool_member
      provider:
        server: "{{ f5_lb_host[dc] }}"
        user: "{{ f5_user }}"
        password: "{{ f5_pass }}"
      state: "disabled"
      pool: "{{ item['name'] }}"
      partition: "{{ f5_partition }}"
      host: "{{ ansible_fqdn }}"
      port: "{{ item['port'] }}"
    with_items: "{{ f5_service_pool }}"
```

Tested & works with Ansible 2.6.1

**Comment by AndreasDavour** [comment]
@rlueckl how did you define your f5_service_pool ?

**Comment by rlueckl** [comment]
This is the "config.yml" of one of the applications I'm deploying:

```
f5_lb_host:
  dc1: 'fqdn-of-f5lb.intern.lan'
f5_partition: 'f5_partiton_name'
f5_service_pool:
  - name: 'poolname_in_f5'
    port: 443
  - name: 'another_pool_with_same_hosts'
    port: 8043
```

The config.yml is loaded by the playbook which includes this F5-playbook:
```
  - name: checkout configrepo
    local_action: git repo=ssh://git@******.lan/******/configrepo.git dest=/var/tmp/configrepo
    run_once: true

  - name: include deploy config
    include_vars: /var/tmp/configrepo/{{ configpath }}/config.yml
```

Basically f5_service_pool is a list of poolnames and ports, and it loops over this and sets *item['name']* and *item['port']*.

The "dc" in *f5_lb_host[dc]* is defined in the hosts file like this:

```
[hostgroup-live1]
hostnames[01:04]
[hostgroup-live1:vars]
dc=dc1
```

I hope this helps.
