### ISSUE TITLE
vmware_guest "msg": "VLAN 'XX' does not exist."

### ISSUE THREAD

**Issue by thorus90** [ansible/ansible#38398]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/jrottmann/Dokumente/ansible/ansible-root/ansible.cfg
  configured module search path = [u'/home/jrottmann/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
```

##### CONFIGURATION

DEFAULT_HASH_BEHAVIOUR(/home/jrottmann/Dokumente/ansible/ansible-root/ansible.cfg) = merge
DEFAULT_REMOTE_USER(/home/jrottmann/Dokumente/ansible/ansible-root/ansible.cfg) = root
DEFAULT_SCP_IF_SSH(/home/jrottmann/Dokumente/ansible/ansible-root/ansible.cfg) = True
##### OS / ENVIRONMENT

arch linux
##### SUMMARY

After Upgrading from 2.4.3 to 2.5.0 my playbook fails with "msg": "VLAN 'XX' does not exist." . This VLAN definitely exists and I have access to it( 2.4.3 works)
##### STEPS TO REPRODUCE

Get Playbook to work in 2.4.3 and upgrade to 2.5.0. Execute one time with state: present and with state: poweredon

```yaml
- name: VMware Deployment
  vmware_guest:
    hostname: "{{ deployment_vmware.vmwarehost }}"
    datacenter: "{{ deployment_vmware.datacenter }}"
    validate_certs: "{{ deployment_vmware.validate_certs }}"
    username: "{{ deployment_vmware.username }}"
    password: "{{ deployment_vmware.password }}"
    resource_pool: "{{ deployment_vmware.resource_pool }}"
    folder: "{{ deployment_vmware.folder }}"
    wait_for_ip_address: "{{ deployment_vmware.wait_for_ip_address }}"
    template: "{{ deployment_vmware.template }}"
    name: "{{ deployment.name | default(inventory_hostname) }}"
    state: "present"
    networks: "{{ tmp_networks_final }}"
    disk: "{{ tmp_disks_final }}"
  register: vm_config
```

##### EXPECTED RESULTS

Deploy VM, and adjust it if needed.
##### ACTUAL RESULTS

If the vm does not exist yet it exits with the error message.
If the vm does already exist(i.e. deployed with ansible 2.4.3), with state: poweredon it runs successfully(as this state does not check configuration of vm), with state: present it exits with the same error message. This happens for both VLANs I'm using.

```
fatal: [mi-ci]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "XXX", 
            "disk": [
                {
                    "datastore": "SATA_XXX", 
                    "size_gb": 20, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": null, 
            "folder": "XXX/vm/intern/Dev-Testing/XX", 
            "force": false, 
            "guest_id": null, 
            "hardware": {}, 
            "hostname": "XXX", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "mi-ci", 
            "name_match": "first", 
            "networks": [
                {
                    "gateway": "XXX", 
                    "ip": "XXX", 
                    "name": "VLAN_69_XXX-Server", 
                    "netmask": "255.255.255.0", 
                    "type": "static", 
                    "vlan": 69
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "resource_pool": "XXX", 
            "snapshot_src": null, 
            "state": "present", 
            "template": "ubuntu-16.04-template", 
            "username": "SAPDOM\\XXX", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }
    }, 
    "msg": "VLAN '69' does not exist."
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@thorus90 Thanks for reporting this issue.

**Comment by Akasurde** [comment]
As a workaround, can you just use name in network parameter ? Let me know if it works for you.

**Comment by Akasurde** [comment]
@thorus90 Can you check Distributed Virtual Portgroup `VLAN_69_XXX-Server` is associated with hostsystem on which you are trying to deploy VM ?

I am only able to reproduce this error if host system is not associated with dvpg specified in networks.

needs_info

**Comment by thorus90** [comment]
I'm on a business trip this week, will test this as soon as I can.

**Comment by johnjelinek** [comment]
I'm running into this in ansible 2.5.1.
Here's my task:
```
  tasks:
  - name: Change VLANs
    vmware_guest:
      hostname: "{{ hostname }}"
      username: "{{ user }}"
      password: "{{ password }}"
      uuid: "{{ uuid }}"
      validate_certs: no
      networks:
      - vlan: {{ vlan }}
        ip: {{ ip }}
        netmask: 255.255.255.0
        gateway: {{ gateway }}
    register: vm_config
    delegate_to: localhost
```

Here's my debug output:
```
"msg": {
  "changed": false,
  "failed": false,
  "instance": {
    "annotation": "",
    "current_snapshot": null,
    "customvalues": {},
    "guest_consolidation_needed": false,
    "guest_question": null,
    "guest_tools_status": "guestToolsRunning",
    "guest_tools_version": "10277",
    "hw_cores_per_socket": 1,
    "hw_datastores": [
      "datastore1"
    ],
    "hw_esxi_host": "host.example.com",
    "hw_eth0": {
      "addresstype": "assigned",
      "ipaddresses": [
        "172.20.10.181"
      ],
      "label": "Network adapter 1",
      "macaddress": "00:50:56:84:47:d7",
      "macaddress_dash": "00-50-56-84-47-d7",
      "summary": "VLAN10"
    },
    "hw_files": [
      "[datastore1] dfwccdas2/dfwccdas2.vmx",
      "[datastore1] dfwccdas2/dfwccdas2.vmsd",
      "[datastore1] dfwccdas2/dfwccdas2.nvram",
      "[datastore1] dfwccdas2/dfwccdas2.vmdk"
    ],
    "hw_folder": "/DFW/vm",
    "hw_guest_full_name": "CentOS 7 (64-bit)",
    "hw_guest_ha_state": null,
    "hw_guest_id": "centos7_64Guest",
    "hw_interfaces": [
      "eth0"
    ],
    "hw_is_template": false,
    "hw_memtotal_mb": 12228,
    "hw_name": "dfwccdas2",
    "hw_power_status": "poweredOn",
    "hw_processor_count": 4,
    "hw_product_uuid": "4204ecae-d1c8-1bb1-80cd-08696f2d3e1d",
    "instance_uuid": "50045324-342b-bd78-72c3-ee682c76a47f",
    "ipv4": "172.20.10.181",
    "ipv6": null,
    "module_hw": true,
    "snapshots": []
  }
}
```
I can't seem to find a name to associate with the network adapter and I get the same error: `VLAN 'XX' does not exist.`
