### ISSUE TITLE
A multiline marker may cause blockinfile to add the block anew

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [ansible/ansible#38417]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
blockinfile

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /mi/A/ansible.cfg
  configured module search path = ['/mi/.ansible/plugins/modules', '/opt/share/ansible/plugins/modules']
  ansible python module location = /opt/lib/python3.6/site-packages/ansible
  executable location = /opt/bin/ansible
  python version = 3.6.4 (default, Dec 22 2017, 10:28:34) [GCC 4.2.1 Compatible FreeBSD Clang 5.0.0 (tags/RELEASE_500/final 312559)]
```

##### CONFIGURATION
ALLOW_WORLD_READABLE_TMPFILES(/mi/A/ansible.cfg) = True
DEFAULT_FORKS(/mi/A/ansible.cfg) = 53
DEFAULT_TIMEOUT(/mi/A/ansible.cfg) = 23

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When the `marker` verb contains multiple lines, `blockinfile` will keep on inserting the block over and over, every time Ansible runs.

##### STEPS TO REPRODUCE

```yaml
- name: Add an entry in ~/.ssh/config
  blockinfile:
    create: true
    path: ~/.ssh/config
    marker: |-
      
      # {mark} Ansible-managed block
      
    block: |-
      Host {{ item.value.targets | join(", ") }}
      	IdentityFile	~/.ssh/{{ item.key }}
        {% if item.value.remuser is defined -%}
      	User	{{ item.value.remuser }}
        {%- endif -%}
  with_dict: "{{ private_keys }}"
```

##### EXPECTED RESULTS
The block inserted on the first application of the role. The block not inserted again on subsequent applications.

##### ACTUAL RESULTS
The block is inserted into the file repeatedly, every time the role is applied.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/blockinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/blockinfile.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @yaegashi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by techtonik** [comment]
I confirm this on Ubuntu 18.04 with Ansible 2.5.1

    ansible-playbook ansible/i3config.yml

```
- hosts: localhost
  tasks:
  - name: enable volume control with multimedia keys
    blockinfile:
      path: "{{ lookup('env', 'HOME') }}/.config/i3/config"
      block: |
        # enable volume control with multimedia keys
        bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume 0 -5%
        bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume 0 +5%

      marker: "\n# {mark} --- custom settings (ansible) ---"
```

**Comment by techtonik** [comment]
bot_status

**Comment by techtonik** [comment]
A [workaround was](https://github.com/techtonik/workstation/blob/fa1da33e2256e9e8454760fcd18245f44c2d11c8/ansible/i3config.yml) was to check that config contains the block with when filter.
```
- hosts: localhost
  vars:
    configpath: "{{ lookup('env', 'HOME') }}/.config/i3/config"
    configtext: "{{ lookup('file', configpath) }}"
    blocktext: |
        # enable volume control with multimedia keys
        bindsym XF86AudioLowerVolume exec --no-startup-id pactl set-sink-volume 0 -5%
        bindsym XF86AudioRaiseVolume exec --no-startup-id pactl set-sink-volume 0 +5%

  tasks:
  - name: enable volume control with multimedia keys
    blockinfile:
      path: "{{ configpath }}"
      block: "{{ blocktext }}"
      marker: "{mark}"
      marker_begin: "\n# --- custom settings (ansible) ---"
      marker_end: "# /-- custom settings ---\n"
    # a workaround for blockinfile not detecting marker with newline
    # https://github.com/ansible/ansible/issues/38417
    when: blocktext not in configtext
```
The downside is that if block text is changed, it will be still added anew and old one will not be removed.

This issue still requires a proper fix.
