### ISSUE TITLE
jira: add ability to create subtasks or document how this is already accomplished

### ISSUE THREAD

**Issue by gregseb** [ansible/ansible#38421]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

jira

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /Users/gsebastian/.ansible.cfg
  configured module search path = [u'/Users/gsebastian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

ANSIBLE_SSH_ARGS(/Users/gsebastian/.ansible.cfg) = -o ForwardAgent=yes
DEFAULT_HOST_LIST(/Users/gsebastian/.ansible.cfg) = [u'/Users/gsebastian/.ansible/hosts']
DEFAULT_ROLES_PATH(/Users/gsebastian/.ansible.cfg) = [u'/Users/gsebastian/.ansible/roles']
DEFAULT_STDOUT_CALLBACK(/Users/gsebastian/.ansible.cfg) = debug

##### OS / ENVIRONMENT

macOS 10.13.4

##### SUMMARY

When running a playbook it would be nice to be able to auto-generate a parent issue then create subtasks of that issue for each host.  As far as I can see the jira module supports creating linked issues but has no support for creating subtasks.

JIRA docs on creating a subtask via the API: https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#creating-a-sub-task 

##### STEPS TO REPRODUCE

Did not see any documentation on how to do this in the [ansible jira_module docs](http://docs.ansible.com/ansible/latest/modules/jira_module.html).  I also didn't see any reference the the "parent" parameter used to accomplish this in [modules/web_infrastructure/jira.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/jira.py)

I imagine something like this:

```yaml
# Create a new issue and add a subtask to it:
- name: Create an issue
  jira:
    uri: '{{ server }}'
    username: '{{ user }}'
    password: '{{ pass }}'
    project: ANS
    operation: create
    summary: Example Issue
    description: Created using Ansible
    issuetype: Task
  register: issue

# issueType must correspond to a sub-task issue type
# (you can use /issue/createmeta to discover sub-task issue types)
- name: Create a subtask
  jira:
    uri: '{{ server }}'
    username: '{{ user }}'
    password: '{{ pass }}'
    project: ANS
    parent: '{{ issue.meta.key }}'
    operation: create
    summary: Example Issue
    description: Created using Ansible
    issuetype: Sub-task
```

##### EXPECTED RESULTS

Expect a way to create a subtask by simply providing a parent and an applicable issuetype.

##### ACTUAL RESULTS

Currently no support for subtasks that I have found.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/jira.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/jira.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Slezhuk @tarka
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gregseb** [comment]
I see now that this possible via the fields argument.

```yaml
# Create a new issue and add a subtask to it:
- name: Create an issue
  jira:
    uri: '{{ server }}'
    username: '{{ user }}'
    password: '{{ pass }}'
    project: ANS
    operation: create
    summary: Example Issue
    description: Created using Ansible
    issuetype: Task
  register: issue

# issueType must correspond to a sub-task issue type
# (you can use /issue/createmeta to discover sub-task issue types)
- name: Create a subtask
  jira:
    uri: '{{ server }}'
    username: '{{ user }}'
    password: '{{ pass }}'
    project: ANS
    operation: create
    summary: Example Issue
    description: Created using Ansible
    issuetype: Sub-task
  args:
    fields:
      parent:
        key: '{{ issue.meta.key }}'
```

I believe that is how it would work.  I haven't had time to test it yet.
