### ISSUE TITLE
terraform module fails missing required argument project_path

### ISSUE THREAD

**Issue by junglie85** [ansible/ansible#38433]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

terraform module

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = ['/Users/ashley/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ashley/Development/k8s/typhoon-vsphere/venv/lib/python3.6/site-packages/ansible
  executable location = /Users/ashley/Development/k8s/typhoon-vsphere/venv/bin/ansible
  python version = 3.6.4 (default, Mar  1 2018, 18:36:50) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

macOS managing Ubuntu 18.04

##### SUMMARY

When providing `project_path` module fails with `missing required arguments: project_path`

##### STEPS TO REPRODUCE

```yaml
- hosts: bastion
  tasks:
  - name: TEAR DOWN | remove terraform project
    terraform:
      project_path: "./infra/cluster"
      state: absent
```

##### EXPECTED RESULTS

module to run successfully

##### ACTUAL RESULTS

```
fatal: [bastion]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "lock": true,
            "state": "present",
            "targets": []
        }
    },
    "msg": "missing required arguments: project_path"
}
```

I'm not using the module to apply the terraform project as I need the `force_init` option in 2.6.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/misc/terraform.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/misc/terraform.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ryansb
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@AshleyByeUK Thanks for reporting this issue. Are you sure that you are using correct playbook as I can see no `project_path` in `"module_args"` in actual output provided, while it is available in playbook provided?

needs_info

**Comment by junglie85** [comment]
@Akasurde thanks. As far as I am aware, yes. Here is the full playbook, `tear-down.yml`:
```
---
- hosts: bastion
  tasks:
   - name: TEAR DOWN | remove terraform project
     terraform:
       project_path: "./infra/cluster"
       state: absent

  - name: TEAR DOWN | clean-up
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - ./infra
      - ./.secrets

- hosts: k8s-cluster
  gather_facts: false
  tasks:
  - name: TEAR DOWN | Force delete all nodes
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: "{{ vcenter_validate_certs }}"
      datacenter: "{{ vcenter_datacenter }}"
      cluster: "{{ vcenter_cluster }}"
      folder: "/"
      resource_pool: "{{ vcenter_resource_pool }}"
      name: "{{ vcenter_vm_prefix }}{{ inventory_hostname }}"
      state: absent
      force: yes
    delegate_to: localhost
```

And I am running it like so:
`ansible-playbook -i inventory/cluster.yml tear-down.yml`
