### ISSUE TITLE
Handler not executing 

### ISSUE THREAD

**Issue by Ankur012** [ansible/ansible#38450]
##### ISSUE TYPE

 - Bug Report
 ##### COMPONENT NAME

Handler

##### ANSIBLE VERSION

ansible 2.5.0
  config file = /home/ubuntu/ankur_data/upload/0904/upaas-ansible-master/upaas/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
##### SUMMARY
I am trying to execute a task when a condition is failed and notify handler to perform some more task on failed condition. a task is executing on failed condition but handler, not execution.

##### STEPS TO REPRODUCE

pre-check/handlers/main.yml
```yaml
---
- name: stage failed
  local_action: lineinfile path={{ LOG_FILE_PATH }} insertafter=EOF  line={{ STAGE_FAILED_LOG }}
  become: yes

- name: upload logs in bucket
  local_action:
     module: aws_s3
     bucket: logs.dev
     object: /{{ JOB_ID }}/{{ JOB_ID }}-{{ role_name|basename }}.log
     src: "{{ LOG_FILE_PATH }}"
     aws_access_key: "{{ abc_aws_access_key }}"
     aws_secret_key: "{{ abc_aws_secret_key }}"
     mode: put
- name: end playbook
  meta: end_play

```

pre-check/task/main.yml
```yaml
- name: register sub job id
  local_action: shell date|sha256sum|base64|head -c 16
  ignore_errors: yes
  register: SUB_JOB_ID


- name: Task |create  {{ JOB_ID }} folder
  local_action: file path={{ LOG_PATH }}{{ JOB_ID }} state=directory
  register: job_folder
  ignore_errors: yes



- name: Log file|create {{ JOB_ID }}_{{ role_name|basename }} logfile
  local_action: file path={{ LOG_FILE_PATH }} state=touch
  register: stage_file
  failed_when: stage_file.rc == 0
  ignore_errors: yes
- name: Log file | start pre-check
  local_action: lineinfile path={{ LOG_FILE_PATH }} insertafter=EOF  line={{ STAGE_START_LOG }}
  register: stage_log
  ignore_errors: yes
  when: job_folder is succeeded and stage_file is succeeded

- name: Log | log file creation failed
  local_action: lineinfile path={{ LOG_FILE_PATH }} insertafter=EOF  line='log file creation check failed]'
  ignore_errors: yes
#  when: (job_folder is failed) or (stage_file is failed)
  notify:
   - stage failed
   - upload logs in bucket
   - end playbook
  when: (job_folder is failed) or (stage_file is failed)
```

##### ACTUAL RESULTS

```
ansible-playbook -i hosts site.yml  --extra-vars="JOB_ID=19 TO_VERSION=16.10.00.02-1  FROM_VERSION=15.11.00.04-1  abc_aws_region=us-west-2 LOG_PATH=/home/ubuntu/logs/ COMPONENT_NAME=httpd" --vault-password-file password  -vv
ansible-playbook 2.5.0

PLAYBOOK: site.yml *********************************************************************************************************************
1 plays in site.yml

PLAY [httpd] ***********************************************************************************************************************

TASK [Gathering Facts] *****************************************************************************************************************
task path: /home/ubuntu/X/X/X/site.yml:11
ok: [X.X.X.X]
META: ran handlers

TASK [common/pre-check : register sub job id] ******************************************************************************************
task path: /home/ubuntu/X/X/X/main.yml:19
changed: [X.X.X.X -> localhost] => {"changed": true, "cmd": "date|sha256sum|base64|head -c 16", "delta": "0:00:00.004146", "end": "2018-04-08 16:46:27.218186", "rc": 0, "start": "2018-04-08 16:46:27.214040", "stderr": "", "stderr_lines": [], "stdout": "MDJkODJjODFmNTM1", "stdout_lines": ["MDJkODJjODFmNTM1"]}

TASK [common/pre-check : Task |create  19 folder] **************************************************************************************
task path: /home/ubuntu/X/X/X//main.yml:25
changed: [X.X.X.X -> localhost] => {"changed": true, "gid": 1000, "group": "ubuntu", "mode": "0775", "owner": "ubuntu", "path": "/home/ubuntu/logs/19", "size": 4096, "state": "directory", "uid": 1000}

TASK [common/pre-check : Log file|create 19_pre-check logfile] *************************************************************************
task path: /home/ubuntu/X/X/X/main.yml:32
fatal: [X.X.X.X]: FAILED! => {"msg": "The conditional check 'stage_file.rc == 0' failed. The error was: error while evaluating conditional (stage_file.rc == 0): 'dict object' has no attribute 'rc'"}
...ignoring

TASK [common/pre-check : Log file | start pre-check] ***********************************************************************************
task path: //home/ubuntu/X/X/X//main.yml:39
skipping: [X.X.X.X] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [common/pre-check : Log | log file creation failed] *******************************************************************************
task path: /home/ubuntu/ankur_data/upload/0904/upaas-ansible-master/upaas/common/pre-check/tasks/main.yml:45
NOTIFIED HANDLER common/pre-check : stage failed for X.X.X.X
NOTIFIED HANDLER common/pre-check : upload logs in bucket for X.X.X.X
NOTIFIED HANDLER common/pre-check : end playbook for X.X.X.X
changed: [X.X.X.X -> localhost] => {"backup": "", "changed": true, "msg": "line added"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/handler.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/handler.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
I could not reproduce the issue with the following reproducer that should be a minimal version of what you have provided:
```yaml
- hosts: localhost
  gather_facts: no
  tasks:
    - fail:
      ignore_errors: yes
      register: failed_job1

    - fail:
      ignore_errors: yes
      register: failed_job2

    - command: echo 'running command'
      ignore_errors: yes
      notify:
        - handler1
        - handler2
        - handler3
      when:
        - (failed_job1 is failed) or (failed_job2 is failed)
  handlers:
    - name: handler1
      debug:
        msg: handler1
    - name: handler2
      debug:
        msg: handler2
    - name: handler3
      meta: end_play
```

Can you try with the current version of ansible to see if it is still an issue? If so, can you please provide a minimal reproducer that we can copy&paste and run? Thanks!

needs_info
