### ISSUE TITLE
template module does not respect Jinja2  conditional check

### ISSUE THREAD

**Issue by drew1kun** [ansible/ansible#38454]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

jinja2 templating (template module)

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /Users/drew/SynologyDrive/rpi-scripts/ansible/ansible.cfg
  configured module search path = [u'/Users/drew/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/Users/drew/SynologyDrive/rpi-scripts/ansible/ansible.cfg) = [u'/Users/drew/SynologyDrive/rpi-scripts/ansible/hosts']
DEFAULT_SCP_IF_SSH(/Users/drew/SynologyDrive/rpi-scripts/ansible/ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(/Users/drew/SynologyDrive/rpi-scripts/ansible/ansible.cfg) = skippy
DEFAULT_VAULT_PASSWORD_FILE(/Users/drew/SynologyDrive/rpi-scripts/ansible/ansible.cfg) = /Users/drew/SynologyDrive/rpi-scripts/ansible/.vault.key
##### OS / ENVIRONMENT
```

##### SUMMARY

template module does not respect Jinja2  conditional check
##### STEPS TO REPRODUCE

Vars:
```yaml
rpi3_network_wifi_APs:
  - id_str: "unsecured_wifi"
    essid: "free_wifi"
    passphrase: ""

  - id_str: "{{ vault_rpi3_network_wifi_APs[1].id_str }}"
    essid: "{{ vault_rpi3_network_wifi_APs[1].essid }}"
    passphrase: "{{ vault_rpi3_network_wifi_APs[1].passphrase }}"
```

Tasks:

```yaml
- name: "[wpa_supplicant] Encode passphrases to 254 bit PSK"
   shell: echo '{{ item.passphrase }}' | wpa_passphrase '{{ item.essid }}'
   register: rpi3_network_psk
   with_items: "{{ rpi3_network_wifi_APs }}"
   changed_when: false
   when:
   - item.passphrase != None
   - item.passphrase != ''

- name:  Generate /etc/wpa_supplicant/wpa_supplicant.conf 
   template:
     src: wpa_supplicant.conf.j2
     dest: /etc/wpa_supplicant/wpa_supplicant.conf
     mode: 0644
     owner: root
     group: root
   become: yes
```
wpa_supplicant.conf.j2:
```jinja
{% for AP in rpi3_network_psk.results %}
  {#{% if 'stdout_lines' in AP %}#}
  {#{% if AP.stdout_lines %}#}
{% if AP.stdout_lines is defined %}
{{ AP.stdout_lines[1] }}
{{ AP.stdout_lines[2] }}
{{ AP.stdout_lines[4] }}
        {% if AP.item.id_str != None and AP.item.id_str != '' %}
        id_str="{{ AP.item.id_str }}"
        {% endif %}
{% endif %}
{{ AP.stdout_lines[5] }}
{% endfor %}
```

Also tried to use `{% if 'stdout_lines' in AP %}` or `{% if AP.stdout_lines %}` instead of `{% if AP.stdout_lines is defined %}`

I even tried a different parameter as a check point: `{% if AP.item.passphrase != None and AP.item.passphrase != '' %}` - still getting the same error output.

##### EXPECTED RESULTS

IF `AP` dictionary object has `'stdout_lines'` property, then generate the text block out of it's items during for loop iteration. Otherwise - skip iteration.

##### ACTUAL RESULTS

```
TASK [drew-kun.network : Generate /etc/wpa_supplicant/wpa_supplicant.conf] ****************************************************************************************
task path: /Users/drew/.ansible/roles/drew-kun.rpi3_network/tasks/wpa_supplicant.yml:21
fatal: [rpi]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'stdout_lines'"
}
        to retry, use: --limit @/Users/drew-kun/SynologyDrive/rpi-scripts/ansible/bootstrap.linux.retry

PLAY RECAP ******************************************************************************************************************************************************************************
rpi                        : ok=7    changed=0    unreachable=0    failed=1


```
