### ISSUE TITLE
vmware_guest network ip not working

### ISSUE THREAD

**Issue by mprahlkamps** [ansible/ansible#38466]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
2.5.0
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/aut/Dokumente/ansible.cfg) = [u'/home/aut/Dokumente/hosts']
```

##### OS / ENVIRONMENT

Running ansible on Debian GNU/Linux 9.4 (stretch)
And managing Debian GNU/Linux 9.4 (stretch) machines.

##### SUMMARY

networks ip command is not accepted. 

##### STEPS TO REPRODUCE

Just run this playbook. If you get an error that the network does not exist, just retry or add a pause command between portgroup and clone commands. (Maybe this is worth an issue on its own?)

```yaml
---
- hosts: localhost
  become_user: root
  become_method: sudo
  gather_facts: false
  serial: 1

  tasks:
   - name: Add Portgroups
     vmware_portgroup:
       validate_certs: no
       hostname: ***
       username: ***
       password: ***
       hosts: ***
       portgroup_name: "emunet-test-1-5"
       switch_name: "vSwitch1"
       vlan_id: 1501
       state: present

   - name: Clone VM Templates
     vmware_guest:
       validate_certs: no
       hostname: ***
       username: ***
       password: ***
       datacenter: Datacenter
       name: "aut-linux-test-1"
       template: "debian-scaling-template"
       cluster: ***
       resource_pool: "AuT Scaling VMs"
       folder: "/"
       state: poweredon
       networks:
         - name: "Int. Mgmt"
         - name: "emunet-test-1-5"
           ip: 169.254.105.11
           netmask: 255.255.0.0
```

##### ACTUAL RESULTS

```
TASK [Clone VM Templates] ******************************************************************************
task path: /home/aut/Dokumente/minmal-ip-test.yml:21
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1523267942.14-182018859669654 `" && echo ansible-tmp-1523267942.14-182018859669654="` echo /root/.ansible/tmp/ansible-tmp-1523267942.14-182018859669654 `" ) && sleep 0'
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-22834X371XJ/tmpW8msT9 TO /root/.ansible/tmp/ansible-tmp-1523267942.14-182018859669654/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1523267942.14-182018859669654/ /root/.ansible/tmp/ansible-tmp-1523267942.14-182018859669654/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1523267942.14-182018859669654/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1523267942.14-182018859669654/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_O66Qb4/ansible_module_vmware_guest.py", line 1674, in deploy_vm
    task = vm_obj.Clone(folder=destfolder, name=self.params['name'], spec=clonespec)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 1314, in InvokeMethod
    req = self.SerializeRequest(mo, info, args)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 938, in SerializeRequest
    result.append(_SerializeToUnicode(arg, param, self.version, nsMap))
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 180, in _SerializeToUnicode
    SoapSerializer(writer, version, nsMap).Serialize(val, info)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 255, in Serialize
    self._Serialize(val, info, self.defaultNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 387, in _Serialize
    self._Serialize(it, itemInfo, defNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 340, in _Serialize
    self._SerializeDataObject(val, info, attr, currDefNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 483, in _SerializeDataObject
    self._Serialize(getattr(val, prop.name), prop, currDefNS)
  File "/usr/local/lib/python2.7/dist-packages/pyVmomi/SoapAdapter.py", line 305, in _Serialize
    raise TypeError('Field "{0}" is not optional'.format(info.name))

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": ***,
            "customization": {},
            "customvalues": [],
            "datacenter": "Datacenter",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": ***,
            "is_template": false,
            "linked_clone": false,
            "name": "aut-linux-test-1",
            "name_match": "first",
            "networks": [
                {
                    "name": "Int. Mgmt"
                },
                {
                    "ip": "169.254.105.11",
                    "name": "emunet-test-1-5",
                    "netmask": "255.255.0.0",
                    "type": "static"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": "AuT Scaling VMs",
            "snapshot_src": null,
            "state": "poweredon",
            "template": "debian-scaling-template",
            "username": ***,
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "TypeError was returned, please ensure to give correct inputs. Field \"ip\" is not optional"
}

```
