### ISSUE TITLE
Display invertion in full_skip callback

### ISSUE THREAD

**Issue by Tsuna77** [ansible/ansible#38485]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

full_skip callback plugin

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /appli/workspaces/ansible_vra/ansible/ansible.cfg
  configured module search path = [u'/home/rricordeau/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### CONFIGURATION

ANSIBLE_NOCOWS(/appli/workspaces/ansible_vra/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/appli/workspaces/ansible_vra/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o ControlPersist=10 -o ControlPath=/tmp/ssh_mux_%h_%p_%r
DEFAULT_BECOME_FLAGS(/appli/workspaces/ansible_vra/ansible/ansible.cfg) = -H -S -n -i
DEFAULT_CALLBACK_WHITELIST(/appli/workspaces/ansible_vra/ansible/ansible.cfg) = ['timer']
DEFAULT_HOST_LIST(/appli/workspaces/ansible_vra/ansible/ansible.cfg) = [u'/appli/workspaces/ansible_vra/inventaires/commun', u'/appli/workspaces/ansible_vra/inventaires/rricordeau']
DEFAULT_ROLES_PATH(/appli/workspaces/ansible_vra/ansible/ansible.cfg) = [u'/appli/workspaces/ansible_vra/ansible_generique/roles']
DEFAULT_STDOUT_CALLBACK(/appli/workspaces/ansible_vra/ansible/ansible.cfg) = full_skip
RETRY_FILES_ENABLED(/appli/workspaces/ansible_vra/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Fedora 27
##### STEPS TO REPRODUCE

In a role, put a debug message with a verbosity.
Put a second debug without verbosity

```yaml

- uri:
    url:  https://{{vra.server}}/catalog-service/api/consumer/entitledCatalogItemViews
    method: GET
    headers:
      Accept: "application/json"
      Authorization: "Bearer {{vra_auth_token.id}}"
    validate_certs: no
  register: blueprint_list


- debug:
    var: blueprint_list
    verbosity: 1

- name: Liste des blueprints
  debug:
    msg: "{{item.name}}"
  with_items: "{{blueprint_list.json.content}}"
```

##### EXPECTED RESULTS

title uri then OK, title debug then message

##### ACTUAL RESULTS

title uri then OK, message the title debug (title and message inversed)

```
PLAY [Get IP from VRA] **********************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [localhost]

TASK [vra_auth : uri] ***********************************************************************************
ok: [localhost]

TASK [vra_auth : set_fact] ******************************************************************************
ok: [localhost]

TASK [vra_catalog_list : uri] ***************************************************************************
ok: [localhost]
ok: [localhost] => (item=None) => {
    "msg": "RHEL7-Mono VM-NSX-NAT on demand"
}
ok: [localhost] => (item=None) => {
    "msg": "RHEL7-Multi VM SES"
}
ok: [localhost] => (item=None) => {
    "msg": "RHEL7-Multiples VMs-NSX-NAT on demand-One vlan"
}
ok: [localhost] => (item=None) => {
    "msg": "RHEL7-Multiples VMs-NSX-NAT on demand"
}
ok: [localhost] => (item=None) => {
    "msg": "Netsync-Multiples VMs-NSX-NAT on demand-One vlan"
}

TASK [vra_catalog_list : Liste des blueprints] **********************************************************

TASK [vra_logout : uri] *********************************************************************************
ok: [localhost]

PLAY RECAP **********************************************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=0   

Playbook run took 0 days, 0 hours, 0 minutes, 1 seconds

```
