### ISSUE TITLE
add_host module called second time with second host should modify the host 

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#3848]
When adding multiple add_host: ansible fails to set the correct port and/or ssh key.

**Example:**

_List of tasks:_

```
- name: Add new instance to common host group
  local_action: add_host hostname=${item.public_dns_name} ansible_ssh_port=22     ansible_ssh_private_key_file=/home/user/.ssh/webserver.pem groupname=common
 with_items: ${ec2.instances}

- name: Add new instance to secondary host group
  local_action: add_host hostname=${item.public_dns_name} ansible_ssh_port=29977 ansible_ssh_private_key_file=/home/user/.ssh/user__key groupname=webserver
  with_items: ${ec2.instances}
```

_Roles:_

```
- hosts: common 
  user: root
  roles: 
    - common 

- hosts: webserver
  user: myuser
  sudo: true
  sudo_user: myuser
  roles: 
    - webserver__role
```

When ansible tries to connect to the first host, 'common', everything works.  Ansible uses the correct port and ssh key.  In this case it's port 22 and key of home/user/.ssh/webserver.pem

However, when Ansible tries to connect to the second host 'webserver', ansible fails to pick up the correct port and ssh key.  Ansible attempts to use port 22 instead of the correct port 29977 and Ansible attempts to use the ssh key /home/user/.ssh/webserver.pem instead of the correct ssh key /home/user/.ssh/user__key
