### ISSUE TITLE
Loop crash when skipping tasks with undefined dict

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#38525]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
loop

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/agil/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609
```

##### CONFIGURATION
Default

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Loop crash when skipping tasks with undefined dict.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  connection: local
  tasks:
  - name: When boo
    block:
    - debug:
        msg: "foo"
      loop: "{{ lookup('dict', boo) }}"
    when: boo is defined

```

##### EXPECTED RESULTS
```
PLAY [localhost] ******************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [debug] **********************************************************************************************************
skipping: [localhost]

PLAY RECAP ************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

```
PLAY [localhost] ******************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************
ok: [localhost]

TASK [debug] **********************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'dict'. Error was a <class 'ansible.errors.AnsibleError'>, original message: with_dict expects a dict"}
	to retry, use: --limit @/home/agil/ansible-loop_dict/loop.retry

PLAY RECAP ************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1  
```

##### Workaround

Old with_dict work as expected:

```yaml
- hosts: localhost
  connection: local
  tasks:
  - name: When boo
    block:
    - debug:
        msg: "foo"
      with_dict: "{{ boo }}"
    when: boo is defined
```
