### ISSUE TITLE
Pinning win_chocolatey packages

### ISSUE THREAD

**Issue by Gianlu** [ansible/ansible#38526]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_chocolatey
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = False
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/modules']

##### SUMMARY
I think that will be useful add the capability to pin chocolatey packages.

##### STEPS TO REPRODUCE

```yaml
---
- name: Pin 7zip
  hosts: windows
  serial: "100%"

  tasks:
    - name: pin 7zip
      win_chocolatey:
         name: "7zip"
         state: "present"
         pinned: true
```

##### EXPECTED RESULTS
The package has been pinned.

##### ACTUAL RESULTS

The feature is non available

```

```
