### ISSUE TITLE
Allow side-by-side installs in win_chocolatey

### ISSUE THREAD

**Issue by NetForce1** [ansible/ansible#38535]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

win_chocolatey

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/daan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

To ease migration I want to be able to install multiple versions of a package. Chocolatey provides a flag to install version side-by-side. This flag should be available from ansible too.

##### STEPS TO REPRODUCE

```yaml
- name: Install old JDK
  win_chocolatey:
    name: jdk8
    version: 8.0.152
    sidebyside: true

- name: Install new JDK
  win_chocolatey:
    name: jdk8
    version: 8.0.162
    sidebyside: true
```

##### EXPECTED RESULTS

Both version are installed

##### ACTUAL RESULTS

```

```
