### ISSUE TITLE
nxos_command, unexpected behavior when passing show commands. Declarative Intent.

### ISSUE THREAD

**Issue by Leggggg** [ansible/ansible#38548]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_command

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/*user_ommitted*/.ansible.cfg
  configured module search path = [u'/home/*user_ommitted/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

[all:vars]
ansible_connection=network_cli
ansible_network_os=nxos

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### SUMMARY

Prior to ansible 2.5.0, I had written a pre-check validation to ensure L2 VLAN's did not exist prior to pushing configuration. The pre-check utilized nxos_commands, pushing show commands to cli and waiting for results.

```yaml
#FUNCTIONALITY BASELINE: VERIFY VLAN DOES NOT EXIST
 - name: L2_VLAN_IMEPLEMENTATION_PRE-CHECK
   nxos_command:
     commands:
       - command: "show vlan id {{ item.vlan_id }}"
         output: text
     wait_for:
       - result[0] contains "VLAN {{ item.vlan_id }} not found in current VLAN database"
   with_items:
     - "{{ L2_VLAN }}"
   register: show_vlan
   tags: L2-VLAN-PRE-CHECK_ROLLBACK
```

```
N3064-01# show vlan id 2000
VLAN 2000 not found in current VLAN database
```

This previously was reported as normal CLI output, I could register it and compare to make decisions. With the introduction of 2.5.0, it appears to issue a failure, recognizing the vlan does not exist in the vlan database. I've also noticed the playbook run time is considerably longer when configuring L2 VLAN. I believe this has to do with how it is determining whether it should apply the new configuration or not, possibly validating against nxos_facts...but never the less it is seems drastically slower.

I'm guessing this is something introduced to aid declarative intent modules. My stance would be, ansible should not produce a failure when pushing a line of code to a router that does not actually generate a CLI error. The output from the router is expected, and normal behavior and can be useful for manual pre-check tasks. It appears that in 2.5, ansible is smart enough to know it should not overwrite L2 VLAN configuration for a vlan that already exists in the vlan database, but it will however still remove that vlan from the vlan database when issuing a rollback.

##### STEPS TO REPRODUCE

```yaml

###HOST INI FILE###

[all:vars]
ansible_connection=network_cli
ansible_network_os=nxos

[n3k]
3064-01 ansible_host=*IP OMITTED*
3064-02 ansible_host=*IP OMITTED*

###HOST VARIABLE FILE EXAMPLE##

hostname: 3064-01

#LIST OF VLANS AND CORRESPONDING NAMES
L2_VLAN:
  - { vlan_id: 1997, vlan_name: "3064-01-02_PRIVATE-VLAN-1997", int_trunk: "port-channel111"}
  - { vlan_id: 1998, vlan_name: "3064-01-02_PRIVATE-VLAN-1998", int_trunk: "port-channel111"}
  - { vlan_id: 1999, vlan_name: "3064-01-02_PRIVATE-VLAN-1999", int_trunk: "port-channel111"}

###MASTER PLAYBOOK###

#LIST OF ROLES ASSOCIATED WITH L2-VLAN_Configure
- hosts: n3k
  gather_facts: no

  #PRE-CHECK BLOCK
  tasks:
    - name: PRE-CHECK BLOCK
      block:
      - import_role:
          name: Device-Health
      - import_role:
          name: Device-Model
      - import_role:
          name: L2-Vlan-Pre-Check_Configure
      #RESCUE EXITS PLAYBOOK IF PRE-CHECK FAILS
      rescue:
      - import_role:
          name: L2-Vlan-Post-Check_Configure
      - fail:
          msg: "Pre-Check Validation Failed, Exiting Playbook"

    #IMPLEMENTATION BLOCK RUNS ALL TASKS IN THE BLOCK IF ABOVE PRE-CHECK BLOCK DOES NOT FAIL
    - name: IMPLEMENTATION BLOCK
      block:
      - debug:
          msg: "Pre-Check Validation Passed"
      - import_role:
          name: L2-Vlan_Configure
      - import_role:
          name: L2-Po111_Configure
      #RESCUE RUNS ROLLBACK IF IMPLEMENTATION FAILS, THEN EXITS PLAYBOOK
      rescue:
      - debug:
          msg: "Implementation Failed, Running Rollback"
      - import_role:
          name: L2-Vlan_Rollback
      - import_role:
          name: L2-Po111_Rollback
      - import_role:
          name: L2-Vlan-Post-Check_Rollback
      - fail:
          msg: "Rollback Successful"

    #IF IMPLEMENTATION BLOCK DOES NOT FAIL, RUN POST CHECK BLOCK
    - name: POST-CHECK BLOCK
      block:
      - import_role:
          name: L2-Vlan-Post-Check_Configure
      #RESCUE EXITS PLAYBOOK IF POST CHECK FAILS
      rescue:
      - fail:
          msg: "Implementation Post-Check Validation Failed, Manual Intervention Required"
    
    - debug:
        msg: "Implementation Successful"

###ROLES###

**L2-Vlan-Pre-Check_Configure**
#FUNCTIONALITY BASELINE: VERIFY VLAN DOES NOT EXIST
 - name: L2_VLAN_IMEPLEMENTATION_PRE-CHECK
   nxos_command:
     commands:
       - command: "show vlan id {{ item.vlan_id }}"
         output: text
     wait_for:
       - result[0] contains "VLAN {{ item.vlan_id }} not found in current VLAN database"
   with_items:
     - "{{ L2_VLAN }}"
   register: show_vlan
   tags: L2-VLAN-PRE-CHECK_ROLLBACK

**L2-Vlan_Configure**
#ADD L2 VLAN TO VLAN DATABASE
 - name: ADD L2 VLAN TO VLAN DATABASE
   nxos_vlan:
     vlan_id: "{{ item.vlan_id }}"
     name: "{{ item.vlan_name }}"
     state: present
     # interfaces: "{{ item.int_trunk }}"
     # associated_interfaces: "{{ item.int_trunk }}"
     admin_state: up
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-VLAN_CONFIGURE

**L2-Po111_Configure**
#ADD L2 VLAN TO PO111 INTERFACE TRUNK
 - name: ADD L2 VLAN TO PO111 INTERFACE TRUNK
   nxos_l2_interface:
     name: "{{ item.int_trunk }}"
     mode: "trunk"
     trunk_vlans: "{{ item.vlan_id }}"
     state: "present"
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-PO111_CONFIGURE

**L2-Vlan-Post-Check_Configure**
#FUNCTIONALITY BASELINE: VERIFY VLAN IS NOT ALREADY IN USE
 - name: L2_VLAN_IMPLEMENTATION_POST-CHECK
   nxos_command:
     commands:
       - command: "show vlan id {{ item.vlan_id }}"
         output: text
     wait_for:
       - result[0] contains "active"
   with_items:
     - "{{ L2_VLAN }}"
   register: show_vlan
   tags: L2-VLAN-POST-CHECK_CONFIGURE

**L2-Po111_Rollback**
#REMOVE L2 VLAN FROM PO111 INTERFACE TRUNK
 - name: REMOVE L2 VLAN FROM PO111 INTERFACE TRUNK
   nxos_l2_interface:
     name: "{{ item.int_trunk }}"
     mode: "trunk"
     trunk_vlans: "{{ item.vlan_id }}"
     state: "absent"
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-PO111_ROLLBACK

**L2-Vlan_Rollback**
#REMOVE L2 VLAN FROM VLAN DATABASE
 - name: REMOVE L2 VLAN FROM VLAN DATABASE
   nxos_vlan:
     vlan_id: "{{ item.vlan_id }}"
     name: "{{ item.vlan_name }}"
     # interfaces: "{{ item.int_trunk }}"
     # associated_interfaces: "{{ item.int_trunk }}"
     state: absent
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-VLAN_ROLLBACK

**L2-Vlan-Post-Check_Rollback**
#FUNCTIONALITY BASELINE: VERIFY VLAN IS NOT ALREADY IN USE
 - name: L2_VLAN_ROLLBACK_POST-CHECK
   nxos_command:
     commands:
       - command: "show vlan id {{ item.vlan_id }}"
         output: text
     # wait_for:
     #   - result[0] contains "VLAN {{ item.vlan_id }} not found in current VLAN database"
   with_items:
     - "{{ L2_VLAN }}"
   register: show_vlan
   tags: L2-VLAN-POST-CHECK_ROLLBACK
```

##### EXPECTED RESULTS

This is 2 parts expected results.

1. I expect that ansible should not throw an failure when pushing commands to cli that are valid, and receive a response. I would expect this behavior from nxos_vlan itself, where it can cross check against the vlan_list from facts...but not from nxos_commands pushing show commands.

2. With the introduction of 2.5, it appears intelligent enough to not overwrite existing configuration when involving L2 VLAN's. I would expect when trying to remove a VLAN from the vlan database, if any of the parameters I'm passing don't match (i.e. vlan name), it would skip that vlan when trying to remove from the vlan database.

##### ACTUAL RESULTS

```
TASK [L2-Vlan-Pre-Check_Configure : L2_VLAN_IMEPLEMENTATION_PRE-CHECK] ****************************************************************************
task path: /home/*USER_OMITTED*/GIT_CLONE/sips_development/roles/L2-Vlan-Pre-Check_Configure/tasks/main.yml:14
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *USER_OMITTED*
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *USER_OMITTED*
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_AjojUt/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_AjojUt/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-01] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1997, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1997'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1997",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"VLAN 1997 not found in current VLAN database\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1997,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1997"
    },
    "msg": "show vlan id 1997\r\r\nVLAN 1997 not found in current VLAN database\r\n\r\n\r\n\rN3064-01# "
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_ZJrwWb/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_ZJrwWb/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-02] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1997, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1997'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1997",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"VLAN 1997 not found in current VLAN database\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1997,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1997"
    },
    "msg": "show vlan id 1997\r\r\nVLAN 1997 not found in current VLAN database\r\n\r\n\r\n\rN3064-02# "
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_a8VpZ8/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_a8VpZ8/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-01] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1998, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1998'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1998",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"VLAN 1998 not found in current VLAN database\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1998,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1998"
    },
    "msg": "show vlan id 1998\r\r\nVLAN 1998 not found in current VLAN database\r\n\r\n\r\n\rN3064-01# "
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_r5J9xo/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_r5J9xo/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-02] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1998, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1998'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1998",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"VLAN 1998 not found in current VLAN database\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1998,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1998"
    },
    "msg": "show vlan id 1998\r\r\nVLAN 1998 not found in current VLAN database\r\n\r\n\r\n\rN3064-02# "
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_799u5b/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_799u5b/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-01] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1999, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1999'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1999",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"VLAN 1999 not found in current VLAN database\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1999,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1999"
    },
    "msg": "show vlan id 1999\r\r\nVLAN 1999 not found in current VLAN database\r\n\r\n\r\n\rN3064-01# "
}
The full traceback is:
  File "/tmp/ansible_qphbTR/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_qphbTR/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-02] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1999, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1999'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1999",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"VLAN 1999 not found in current VLAN database\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1999,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1999"
    },
    "msg": "show vlan id 1999\r\r\nVLAN 1999 not found in current VLAN database\r\n\r\n\r\n\rN3064-02# "
}

TASK [L2-Vlan-Post-Check_Configure : L2_VLAN_IMPLEMENTATION_POST-CHECK] ***************************************************************************
task path: /home/*USER_OMITTED*/GIT_CLONE/sips_development/roles/L2-Vlan-Post-Check_Configure/tasks/main.yml:14
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *USER_OMITTED*
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *USER_OMITTED*
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_ReIegD/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_ReIegD/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-01] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1997, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1997'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1997",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"active\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1997,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1997"
    },
    "msg": "show vlan id 1997\r\r\nVLAN 1997 not found in current VLAN database\r\n\r\n\r\n\rN3064-01# "
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_HhlDwj/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_HhlDwj/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-02] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1997, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1997'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1997",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"active\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1997,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1997"
    },
    "msg": "show vlan id 1997\r\r\nVLAN 1997 not found in current VLAN database\r\n\r\n\r\n\rN3064-02# "
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_93W2AB/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_93W2AB/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-01] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1998, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1998'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1998",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"active\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1998,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1998"
    },
    "msg": "show vlan id 1998\r\r\nVLAN 1998 not found in current VLAN database\r\n\r\n\r\n\rN3064-01# "
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_B7DaFu/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_B7DaFu/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-02] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1998, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1998'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1998",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"active\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1998,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1998"
    },
    "msg": "show vlan id 1998\r\r\nVLAN 1998 not found in current VLAN database\r\n\r\n\r\n\rN3064-02# "
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_command.py
<*IP_OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
  File "/tmp/ansible_0VPGGA/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_0VPGGA/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-01] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1999, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1999'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1999",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"active\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1999,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1999"
    },
    "msg": "show vlan id 1999\r\r\nVLAN 1999 not found in current VLAN database\r\n\r\n\r\n\rN3064-01# "
}
The full traceback is:
  File "/tmp/ansible_beMdUI/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py", line 156, in run_commands
    out = connection.get(cmd)
  File "/tmp/ansible_beMdUI/ansible_modlib.zip/ansible/module_utils/connection.py", line 146, in __rpc__
    raise ConnectionError(to_text(msg, errors='surrogate_then_replace'), code=code)

failed: [3064-02] (item={u'int_trunk': u'port-channel111', u'vlan_id': 1999, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1999'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "commands": [
                {
                    "answer": null,
                    "command": "show vlan id 1999",
                    "output": "text",
                    "prompt": null
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": null,
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "wait_for": [
                "result[0] contains \"active\""
            ]
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1999,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1999"
    },
    "msg": "show vlan id 1999\r\r\nVLAN 1999 not found in current VLAN database\r\n\r\n\r\n\rN3064-02# "
}
        to retry, use: --limit @/home/*USER_OMITTED*/GIT_CLONE/sips_development/L2-Vlan_Configure.retry

PLAY RECAP ****************************************************************************************************************************************
3064-01                    : ok=2    changed=0    unreachable=0    failed=2
3064-02                    : ok=2    changed=0    unreachable=0    failed=2


```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nxos/nxos_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_command.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gdpak** [comment]
Hi @Leggggg 

1. I see your point that ansible is returning error when show vlan command does not find a vlan. Actually vlan database is not par of ansible_facts. It is returning error because “not found” regex pattern was present in command output of “show vlan id <>”  It seems to be the same behaviour from long time . Some customers might have written their rollback/error-recovery based on this as normally “not found” returned in show command would be an exception. Having said that, ansible provides flexibility to handle error as per your requirement. e.g. You can use "failed_when" check as below code which will let you go through to step of “L2-Vlan_Configure” even if vlan does not exist-
  
        **L2-Vlan-Pre-Check_Configure**
#FUNCTIONALITY BASELINE: VERIFY VLAN DOES NOT EXIST
 - name: L2_VLAN_IMEPLEMENTATION_PRE-CHECK
   nxos_command:
     commands:
       - command: "show vlan id {{ item.vlan_id }}"
         output: text
     wait_for:
       - result[0] contains "VLAN {{ item.vlan_id }} not found in current VLAN database"
   with_items:
     - "{{ L2_VLAN }}"
   register: show_vlan
   failed_when: " 'not found' not in show_vlan.msg" 
   tags: L2-VLAN-PRE-CHECK_ROLLBACK

2. If a vlan is already present on system and you try to configure it then it does not return any error so I am not sure why rollback is getting called ? on nxos, while deleting a vlan only vlan-id is the key so ansible ‘nxos_vlan’ module  mirrors same behaviour for deleting vlan id and ignoring name. Anyway let us understand why rollback was called and we should work out a solution from there.

Hope it helps.

Thanks,

**Comment by Leggggg** [comment]
Hi!

Thanks for the response. Helpful feedback about "not found" forcing a failure...although I am a bit concerned about that. It still seems odd to me to force a failure for output that is normal behavior from Cisco. I resolved this using vlan_list, which is an item of nxos_facts of subset legacy.

I agree with you about the pre-check and rollback. My initial intent with my pre-check was to configure as much as I could. The way I intended it to work was, configure anything that isn't already in the vlan database. If in the post check, or using declarative intent variables it wasn't configured as I expected, issue a rollback. The problem I saw at the time being, even if I passed over a vlan that was already in the database during implementation, my rollback would remove it from the database.

I was hopeful that if a given vlan_id's name didn't match what was configured, that setting the state to absent would not remove it from the database. As opposed to simply passing state as absent without any other parameters. Meaning, we are not removing configuration unless it matches on all parameters set (in this case, when the vlan name doesn't match).

```yaml
#REMOVE L2 VLAN FROM VLAN DATABASE
 - name: REMOVE L2 VLAN FROM VLAN DATABASE
   nxos_vlan:
     vlan_id: "{{ item.vlan_id }}"
     state: absent
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-VLAN_ROLLBACK
```
vs

```yaml
#REMOVE L2 VLAN FROM VLAN DATABASE
 - name: REMOVE L2 VLAN FROM VLAN DATABASE
   nxos_vlan:
     vlan_id: "{{ item.vlan_id }}"
     #VLAN_NAME HAS NO APPARENT CONTROL OVER WHETHER VLAN IS REMOVED OR NOT
     name: "{{ item.vlan_name }}"
     state: absent
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-VLAN_ROLLBACK
```

Take care,

Matt
