### ISSUE TITLE
nxos_l2_interface fails to remove vlan from both physical and logical trunk interfaces

### ISSUE THREAD

**Issue by Leggggg** [ansible/ansible#38547]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_l2_interface

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/*user_ommitted*/.ansible.cfg
  configured module search path = [u'/home/*user_ommitted/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

[all:vars]
ansible_connection=network_cli
ansible_network_os=nxos

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### SUMMARY

I have a simple playbook to add a set of L2 VLAN to a NXOS router. After creating the VLAN, I call nxos_l2_interface to add the VLAN to a INTERFACE TRUNK (in my case a port channel). Formerly, this was fully functional using nxos_switchport (trunk_vlans parameter). In upgrading our ansible version to 2.5, I noticed nxos_switchport was deprecated and have tried to replace it with nxos_l2_interface unsuccessfully.

I pass the vlan as variables, but have tried static assignment for both the interface and the trunk_vlan's as single physical and logical interfaces, as well as single vlan id's and vlan range. None have been successful in removal, but are successful in configuration.

##### STEPS TO REPRODUCE

```yaml

###HOST INI FILE###

[all:vars]
ansible_connection=network_cli
ansible_network_os=nxos

[n3k]
3064-01 ansible_host=*IP OMITTED*
3064-02 ansible_host=*IP OMITTED*

###HOST VARIABLE FILE EXAMPLE##

hostname: 3064-01

#LIST OF VLANS AND CORRESPONDING NAMES
L2_VLAN:
  - { vlan_id: 1997, vlan_name: "3064-01-02_PRIVATE-VLAN-1997", int_trunk: "port-channel111"}
  - { vlan_id: 1998, vlan_name: "3064-01-02_PRIVATE-VLAN-1998", int_trunk: "port-channel111"}
  - { vlan_id: 1999, vlan_name: "3064-01-02_PRIVATE-VLAN-1999", int_trunk: "port-channel111"}

###CONFIGURATION###

#ADD L2 VLAN TO VLAN DATABASE
 - name: ADD L2 VLAN TO VLAN DATABASE
   nxos_vlan:
     vlan_id: "{{ item.vlan_id }}"
     name: "{{ item.vlan_name }}"
     state: present
     # interfaces: "{{ item.int_trunk }}"
     # associated_interfaces: "{{ item.int_trunk }}"
     admin_state: up
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-VLAN_CONFIGURE

#ADD L2 VLAN TO PO111 INTERFACE TRUNK
 - name: ADD L2 VLAN TO PO111 INTERFACE TRUNK
   nxos_l2_interface:
     name: "{{ item.int_trunk }}"
     mode: "trunk"
     trunk_vlans: "{{ item.vlan_id }}"
     state: "present"
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-PO111_CONFIGURE

###ROLLBACK###

#REMOVE L2 VLAN FROM PO111 INTERFACE TRUNK
 - name: REMOVE L2 VLAN FROM PO111 INTERFACE TRUNK
   nxos_l2_interface:
     name: "{{ item.int_trunk }}"
     mode: "trunk"
     trunk_vlans: "{{ item.vlan_id }}"
     state: "absent"
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-PO111_ROLLBACK

#REMOVE L2 VLAN FROM VLAN DATABASE
 - name: REMOVE L2 VLAN FROM VLAN DATABASE
   nxos_vlan:
     vlan_id: "{{ item.vlan_id }}"
     name: "{{ item.vlan_name }}"
     # interfaces: "{{ item.int_trunk }}"
     # associated_interfaces: "{{ item.int_trunk }}"
     state: absent
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-VLAN_ROLLBACK
```

##### EXPECTED RESULTS

The expected results is for module nxos_l2_interface to remove vlan from an interface (physical or logical, as long as it is L2 switchport trunk) when using the following parameters as shown in the documentation example:

**documentation example**
```yaml
- name: Ensure these VLANs are not being tagged on the trunk
  nxos_l2_interface:
    name: Ethernet1/5
    mode: trunk
    trunk_vlans: 51-4094
    state: absent
```

**my test case**
```yaml
 - name: REMOVE L2 VLAN FROM PO111 INTERFACE TRUNK
   nxos_l2_interface:
     name: "{{ item.int_trunk }}"
     mode: "trunk"
     trunk_vlans: "{{ item.vlan_id }}"
     state: "absent"
   with_items:
     - "{{ L2_VLAN }}"
   tags: L2-PO111_ROLLBACK
```

##### ACTUAL RESULTS

```
[*user_ommitted@niddserver01 sips_development]$ ansible-playbook -i hosts L2-Vlan_Rollback.yml -u *user_ommitted-k -vvv
ansible-playbook 2.5.0
  config file = /home/*user_ommitted/.ansible.cfg
  configured module search path = [u'/home/*user_ommitted/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
Using /home/*user_ommitted/.ansible.cfg as config file
SSH password:
Parsed /home/*user_ommitted/GIT_CLONE/sips_development/hosts inventory source with ini plugin

PLAYBOOK: L2-Vlan_Rollback.yml ********************************************************************************************************************
1 plays in L2-Vlan_Rollback.yml

PLAY [n3k] ****************************************************************************************************************************************
META: ran handlers

TASK [L2-Po111_Rollback : REMOVE L2 VLAN FROM PO111 INTERFACE TRUNK] ******************************************************************************
task path: /home/*user_ommitted/GIT_CLONE/sips_development/roles/L2-Po111_Rollback/tasks/main.yml:14
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_l2_interface.py
<*IP OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *user_ommitted
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_l2_interface.py
<*IP OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *user_ommitted
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [3064-02] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1997, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1997'}) => {
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "access_vlan": null,
            "aggregate": null,
            "host": null,
            "mode": "trunk",
            "name": "port-channel111",
            "native_vlan": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "trunk_allowed_vlans": null,
            "trunk_vlans": "1997",
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1997,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1997"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_l2_interface.py
<*IP OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *user_ommitted
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [3064-01] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1997, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1997'}) => {
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "access_vlan": null,
            "aggregate": null,
            "host": null,
            "mode": "trunk",
            "name": "port-channel111",
            "native_vlan": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "trunk_allowed_vlans": null,
            "trunk_vlans": "1997",
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1997,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1997"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_l2_interface.py
<*IP OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *user_ommitted
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [3064-02] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1998, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1998'}) => {
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "access_vlan": null,
            "aggregate": null,
            "host": null,
            "mode": "trunk",
            "name": "port-channel111",
            "native_vlan": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "trunk_allowed_vlans": null,
            "trunk_vlans": "1998",
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1998,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1998"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_l2_interface.py
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [3064-01] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1998, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1998'}) => {
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "access_vlan": null,
            "aggregate": null,
            "host": null,
            "mode": "trunk",
            "name": "port-channel111",
            "native_vlan": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "trunk_allowed_vlans": null,
            "trunk_vlans": "1998",
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1998,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1998"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_l2_interface.py
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [3064-02] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1999, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1999'}) => {
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "access_vlan": null,
            "aggregate": null,
            "host": null,
            "mode": "trunk",
            "name": "port-channel111",
            "native_vlan": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "trunk_allowed_vlans": null,
            "trunk_vlans": "1999",
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1999,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1999"
    }
}
ok: [3064-01] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1999, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1999'}) => {
    "changed": false,
    "commands": [],
    "invocation": {
        "module_args": {
            "access_vlan": null,
            "aggregate": null,
            "host": null,
            "mode": "trunk",
            "name": "port-channel111",
            "native_vlan": null,
            "password": null,
            "port": null,
            "provider": null,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "trunk_allowed_vlans": null,
            "trunk_vlans": "1999",
            "use_ssl": null,
            "username": null,
            "validate_certs": null
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1999,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1999"
    }
}

TASK [L2-Vlan_Rollback : REMOVE L2 VLAN FROM VLAN DATABASE] ***************************************************************************************
task path: /home/*user_ommitted/GIT_CLONE/sips_development/roles/L2-Vlan_Rollback/tasks/main.yml:14
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_vlan.py
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_vlan.py
<*IP OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *user_ommitted
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<*IP OMITTED*> ESTABLISH LOCAL CONNECTION FOR USER: *user_ommitted
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [3064-02] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1997, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1997'}) => {
    "changed": true,
    "commands": [
        "no vlan 1997"
    ],
    "invocation": {
        "module_args": {
            "admin_state": "up",
            "aggregate": null,
            "associated_interfaces": null,
            "delay": 10,
            "host": null,
            "interfaces": null,
            "mapped_vni": null,
            "mode": "ce",
            "name": "3064-01-02_PRIVATE-VLAN-1997",
            "password": null,
            "port": null,
            "provider": null,
            "purge": false,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "vlan_id": 1997,
            "vlan_range": null,
            "vlan_state": "active"
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1997,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1997"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_vlan.py
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [3064-01] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1997, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1997'}) => {
    "changed": true,
    "commands": [
        "no vlan 1997"
    ],
    "invocation": {
        "module_args": {
            "admin_state": "up",
            "aggregate": null,
            "associated_interfaces": null,
            "delay": 10,
            "host": null,
            "interfaces": null,
            "mapped_vni": null,
            "mode": "ce",
            "name": "3064-01-02_PRIVATE-VLAN-1997",
            "password": null,
            "port": null,
            "provider": null,
            "purge": false,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "vlan_id": 1997,
            "vlan_range": null,
            "vlan_state": "active"
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1997,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1997"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_vlan.py
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [3064-02] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1998, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1998'}) => {
    "changed": true,
    "commands": [
        "no vlan 1998"
    ],
    "invocation": {
        "module_args": {
            "admin_state": "up",
            "aggregate": null,
            "associated_interfaces": null,
            "delay": 10,
            "host": null,
            "interfaces": null,
            "mapped_vni": null,
            "mode": "ce",
            "name": "3064-01-02_PRIVATE-VLAN-1998",
            "password": null,
            "port": null,
            "provider": null,
            "purge": false,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "vlan_id": 1998,
            "vlan_range": null,
            "vlan_state": "active"
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1998,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1998"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_vlan.py
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [3064-02] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1999, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1999'}) => {
    "changed": true,
    "commands": [
        "no vlan 1999"
    ],
    "invocation": {
        "module_args": {
            "admin_state": "up",
            "aggregate": null,
            "associated_interfaces": null,
            "delay": 10,
            "host": null,
            "interfaces": null,
            "mapped_vni": null,
            "mode": "ce",
            "name": "3064-01-02_PRIVATE-VLAN-1999",
            "password": null,
            "port": null,
            "provider": null,
            "purge": false,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "vlan_id": 1999,
            "vlan_range": null,
            "vlan_state": "active"
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1999,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1999"
    }
}
changed: [3064-01] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1998, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1998'}) => {
    "changed": true,
    "commands": [
        "no vlan 1998"
    ],
    "invocation": {
        "module_args": {
            "admin_state": "up",
            "aggregate": null,
            "associated_interfaces": null,
            "delay": 10,
            "host": null,
            "interfaces": null,
            "mapped_vni": null,
            "mode": "ce",
            "name": "3064-01-02_PRIVATE-VLAN-1998",
            "password": null,
            "port": null,
            "provider": null,
            "purge": false,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "vlan_id": 1998,
            "vlan_range": null,
            "vlan_state": "active"
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1998,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1998"
    }
}
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/nxos/nxos_vlan.py
<*IP OMITTED*> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
changed: [3064-01] => (item={u'int_trunk': u'port-channel111', u'vlan_id': 1999, u'vlan_name': u'3064-01-02_PRIVATE-VLAN-1999'}) => {
    "changed": true,
    "commands": [
        "no vlan 1999"
    ],
    "invocation": {
        "module_args": {
            "admin_state": "up",
            "aggregate": null,
            "associated_interfaces": null,
            "delay": 10,
            "host": null,
            "interfaces": null,
            "mapped_vni": null,
            "mode": "ce",
            "name": "3064-01-02_PRIVATE-VLAN-1999",
            "password": null,
            "port": null,
            "provider": null,
            "purge": false,
            "ssh_keyfile": null,
            "state": "absent",
            "timeout": null,
            "transport": null,
            "use_ssl": null,
            "username": null,
            "validate_certs": null,
            "vlan_id": 1999,
            "vlan_range": null,
            "vlan_state": "active"
        }
    },
    "item": {
        "int_trunk": "port-channel111",
        "vlan_id": 1999,
        "vlan_name": "3064-01-02_PRIVATE-VLAN-1999"
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP ****************************************************************************************************************************************
3064-01                    : ok=2    changed=1    unreachable=0    failed=0
3064-02                    : ok=2    changed=1    unreachable=0    failed=0

```
