### ISSUE TITLE
Unable to install service via win_nssm. 

### ISSUE THREAD

**Issue by sangtraceur** [ansible/ansible#38557]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_nssm module
##### ANSIBLE VERSION

```
2.5
```

##### CONFIGURATION

generally no config changes

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS control machine, Windows 7 SP1 target machine
##### SUMMARY

During service installation via win_nssm it is impossible to set console output encoding to Unicode, that causes general error and execution breaks.

##### STEPS TO REPRODUCE

Using module win_nssm

```yaml
  - name: Install Spring Boot app as Windows service (via nssm), if not already there - but remain stopped to configure Application directory
    win_nssm:
      name: "{{spring_boot_app_name}}"
      application: "{{path_to_java_exe}}"
      app_parameters_free_form: "-jar {{spring_boot_app_path}}\\{{spring_boot_app_name}}.jar"
      state: stopped
```

##### EXPECTED RESULTS
Installation of windows service

##### ACTUAL RESULTS

TASK [Install Spring Boot app as Windows service (via nssm), if not already there - but remain stopped to configure Application directory] ***
fatal: [192.168.0.106]: FAILED! => {"changed": false, "msg": "an exception occurred when invoking NSSM: Exception setting \"OutputEncoding\": \"Parametr jest niepoprawny.\r\n\""}

I have identified that https://github.com/ansible/ansible/blob/608d30ba9b989b5474c8cd9b537eaeac9bafc544/lib/ansible/modules/windows/win_nssm.ps1#L63
causes problem. Currently setting "Unicode" is not possible on Windows 7, trying to set UTF8 instead of unicode works fine
