### ISSUE TITLE
Go module to install packages

### ISSUE THREAD

**Issue by kenorb** [ansible/ansible#38568]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

Go module

##### ANSIBLE VERSION
```
Ansible 2.5.0
```

##### CONFIGURATION

Default.

##### OS / ENVIRONMENT

Docker OS: Ubuntu
Host OS: macOS

##### SUMMARY

I'd like to see `go` module to handle package installation, similar to `apt` or `pip`.
```
  tasks:
    - name: Install pup (CLI HTML processor)
      go: name=pup state=present
```

which would be equivalent to `go get github.com/ericchiang/pup` command.

##### STEPS TO REPRODUCE

`provision.yml`

```yaml
- hosts: localhost
  tasks:
    - name: Install GO (Google's Programming Language)
      apt: name=golang state=present
    - name: Install pup (CLI HTML processor)
      go: name=pup state=present
```

##### EXPECTED RESULTS

> Step 4/9 : RUN go get github.com/ericchiang/pup

##### ACTUAL RESULTS

> ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
