### ISSUE TITLE
Ansible Doc Linter does not allow suboptions more than one level deep

### ISSUE THREAD

**Issue by rambleraptor** [ansible/ansible#38567]
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
validate_modules

##### ANSIBLE VERSION
```
2.5
```

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE
```python
DOCUMENTATION='''
---
...
property:
  description:
      - Test property
  suboptions:
      nested_one_level:
          description: Something
'''
```

##### EXPECTED RESULTS
I expected validate_modules to work without issue.
##### ACTUAL RESULTS
validate_modules complained that ...['property']['suboptions'] had extra keys.

**Comment by ansibot** [comment]
Files identified in the description:
* [test/runner/lib/sanity/validate_modules.py](https://github.com/ansible/ansible/blob/devel/test/runner/lib/sanity/validate_modules.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mattclay
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
Are you using `validate-modules` from the 2.5. release?

`validate-modules` from the 2.5 release does not support this, but it is however supported in the devel branch (https://github.com/ansible/ansible/pull/37206).

All new modules should be developed against the devel branch of ansible as new modules are only accepted in major releases.

From v2.5:

```
test.py:0:0: E305 DOCUMENTATION.options.property.suboptions.nested_one_level.suboptions: extra keys not allowed @ data['options']['property']['suboptions']['nested_one_level']['suboptions']. Got {'nested_two_levels': {'description': 'foo'}}
```

Using 2.6 (devel) this does not happen.

Test data:

```
DOCUMENTATION = '''
module: test
short_description: This is a sentence describing the module
description:
    - Longer description of the module.
version_added: "X.Y"
author: "Your AWESOME name (@awesome-github-id)"
options:
    property:
        description:
            - Test property
        suboptions:
            nested_one_level:
                description: Something
                suboptions:
                    nested_two_levels:
                        description: foo
'''
```

needs_info
