### ISSUE TITLE
finding a phrase through ansible script

### ISSUE THREAD

**Issue by bisshwajitsamanta** [ansible/ansible#38576]
i am having a problem in finding solution. I have a piece of file which contains data in below format (json type with quotes)::-
```yaml
hostinfo:
  'host001':
    ip: x.x.x.x
    hostclass: 'puppet'
  'host002':
    ip: y.y.y.y
    hostclass: 'ess'
  'host003':
    ip: z.z.z.z
    hostclass: 'mdb'
```

Now my task is to find out the hostname of the system belong to hostclass 'ess' , which in this case the answer in host002. I have to write an ansible script to find out the result. Can anyone help me in finding out, or any idea to approach for the problem.

Issue Type:: Finding a phrase through ansible
Ansible Version:: Ansible 2.4.0
Component Name:: It looks similar to json type file.
