### ISSUE TITLE
aci_static_binding_to_epg module prepending "eth" to interface_type: port_channel

### ISSUE THREAD

**Issue by mtorelli** [ansible/ansible#38595]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

aci_static_binding_to_epg
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/u/mtorelli/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /u/mtorelli/gitlab/gdl2_refresh/venv_2_5/lib/python2.7/site-packages/ansible
  executable location = /u/mtorelli/gitlab/gdl2_refresh/venv_2_5/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)
Cisco APIC version 3.1(2m)
##### SUMMARY

In the INTERFACE_TYPE_MAPPING dictionary, for interface type port_channel, the code is prepending 'eth' to the interface parameter (i.e., the policy-group name) 

port_channel='topology/pod-{0}/paths-{1}/pathep-[eth{2}]'.format(pod_id, leafs, interface), 
##### STEPS TO REPRODUCE

Just run the playbook task below after creating the tenant, app profile and epg on the apic.

```yaml
---

- name: Adding static path for port TEST-POLICY-GROUP (vlan-2690) on node 217 in TENANT/DATA/Vlan2690
  aci_static_binding_to_epg:
    hostname: "{{ apic_hostname }}"
    username: "{{ apic_username }}"
    password: "{{ apic_password }}"
    use_ssl: yes
    validate_certs: no
    tenant: TENANT
    ap: DATA
    epg: Vlan2690
    leafs: 217
    pod_id: 1
    interface: TEST-POLICY-GROUP
    interface_type: port_channel
    interface_mode: untagged
    encap_id: 2690
    state: present
```

##### EXPECTED RESULTS

the module should create  the static port 
Pod1/Node-217/TEST-POLICY-GROUP
##### ACTUAL RESULTS

the module creates the static port 
Pod1/Node-217/ethTEST-POLICY-GROUP

```

```
