### ISSUE TITLE
HAProxy with_items and async causes exception

### ISSUE THREAD

**Issue by agronick** [ansible/ansible#38599]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
HAProxy

##### ANSIBLE VERSION
Github devel branch cc1c7c63db77b38f7a5276f61a7f7897ce6217f4

##### CONFIGURATION
ansible-config dump --only-changed is empty

##### OS / ENVIRONMENT 
Linux OpenSuse Leap 42.3

##### SUMMARY
This is the same symptom as #12254. If you use async and with_items on HAProxy, waiting for the async task to finish throws `dict object' has no attribute 'ansible_job_id'`.

##### STEPS TO REPRODUCE
I had to take the changes from #30947 because of #30833 ('bool' object is not callable')

HA Proxy module is very buggy. This is the 3rd exception I had to deal with trying to do this.  The other exception I got was a str/bytes error with Python 3.

This is the tasks that are causing this issue of 
```

    - name: Disable old backends
      haproxy:
        backend: nodes
        socket: /var/lib/haproxy/stats
        host: 'sl{{ last_active.stdout }}{{ item }}'
        state: draining   
        wait: yes
        wait_interval: 10
        wait_retries: 60
      async: 1000
      poll: 0
      register: drain_complete
      with_sequence: "{{ worker_count }}"

    - name: Wait for switch backends
      async_status:
        jid: "{{ drain_complete.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
```

##### EXPECTED RESULTS
Waits for task to finish

##### ACTUAL RESULTS
Exception is thrown

```
fatal: [myhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'ansible_job_id'\n\nThe error appears to have been in '/homeprojects/ansible/setup.yaml': line 83, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Wait for switch backends 1\n      ^ here\n"} 
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/haproxy.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/haproxy.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ravibhure
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:

   * Waiting for an item to finish when using with_items and async fails

However, however what is happening is that:

   * You are trying to access the variable `ansible_job_id` on the variable `drain_complete`

Normally this is ok but the `with_sequence` is adding these variables in a results child because there are multiple task results being registered. Using this basic playbook you can see how it works

```
---
- hosts: localhost
  gather_facts: no
  tasks:
  - command: echo {{ item }}
    with_sequence: count=2
    register: cmd_result
    async: 1000
    poll: 0

  - debug:
      var: cmd_result
```

The output looks like this

```
PLAY [localhost] ***************************************************************************************************************************

TASK [command] *****************************************************************************************************************************
changed: [127.0.0.1] => (item=1)
changed: [127.0.0.1] => (item=2)

TASK [debug] *******************************************************************************************************************************
ok: [127.0.0.1] => {
    "cmd_result": {
        "changed": true,
        "msg": "All items completed",
        "results": [
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "ansible_job_id": "722220686794.20885",
                "changed": true,
                "failed": false,
                "finished": 0,
                "item": "1",
                "results_file": "/Users/jborean/.ansible_async/722220686794.20885",
                "started": 1
            },
            {
                "_ansible_ignore_errors": null,
                "_ansible_item_result": true,
                "_ansible_no_log": false,
                "_ansible_parsed": true,
                "ansible_job_id": "614953304393.20906",
                "changed": true,
                "failed": false,
                "finished": 0,
                "item": "2",
                "results_file": "/Users/jborean/.ansible_async/614953304393.20906",
                "started": 1
            }
        ]
    }
}

PLAY RECAP *********************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
```

As you can see, the var `cmd_result`, has an key called `results` which is a list of results per sequence that was run. It is within each entry that you can use the `ansible_job_id` variable.

We would suggest:

Just set your async_status job to be the following

```
- async_status:
    jid: '{{ item.ansible_job_id }}'
  with_items: '{{ drain_complete }}'
  register: job_result
  until: job_result.finished
  retries: 30
```

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
