### ISSUE TITLE
templated vars_files name not evaluating when job executed by cron

### ISSUE THREAD

**Issue by drewmullen** [ansible/ansible#38592]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vars_files

##### ANSIBLE VERSION
```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible', u'/opt/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### OS / ENVIRONMENT
RHEL 7.4

##### SUMMARY

my playbook calls for a vars_files based on a lookup function. this allows me to run the same playbook and have my vars selected based on the domain of the ansible server (we maintain a diff ansible server per env). Ansible is not able to resolve the lookup function when the job is executed by cron. 

```
vars_files:
    - "/opt/ansible/group_vars/{{ lookup('env', 'HOSTNAME') | regex_search('prod|dev') }}.yml"
```

**Error**
```ERROR! vars file /opt/ansible/group_vars/{{ lookup('env', 'HOSTNAME') | regex_search('prod|dev') }}.yml was not found```

# example of ansible hostname = ansible1.prod.com

##### STEPS TO REPRODUCE
**playbook**:
```yaml
- hosts: "{{ target_hosts | default('all') }}"
  become: true
  gather_facts: false
  vars_files:
    - "/opt/ansible/group_vars/{{ lookup('env', 'HOSTNAME') | regex_search('prod|dev') }}.yml"

  tasks:
    - name: output var value
      debug:
         msg: "{{ test }}"
```

**prod.yml:**
```yaml
test: exists!
```

**cron job**
```
55   02  *   *   *    root   ansible-playbook -i /opt/ansible/localhost /opt/ansible/debug.yml > /tmp/debug.log 2>&1
```

##### EXPECTED RESULTS
successful execution

**AD-HOC EXECUTION WORKS FINE:**
`ansible-playbook -i /opt/ansible/localhost /opt/ansible/debug.yml`

##### ACTUAL RESULTS

```
ERROR! vars file /opt/ansible/group_vars/{{ lookup('env', 'HOSTNAME') | regex_search('prod|dev') }}.yml was not found
```
