### ISSUE TITLE
ios_config: Error if `#macro` is specified

### ISSUE THREAD

**Issue by gundalow** [ansible/ansible#38591]
##### ISSUE TYPE
 - Bug Report
 - Documentation Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION
```
2.5.0
```

##### SUMMARY

Following on from https://github.com/ansible/ansible/issues/38420

`ios_config` should detect if one of the `lines:` starts with `#macro` and fail the task with a message stating the macros are not supported. The work around is detailed in https://github.com/ansible/ansible/issues/38420 which should be part of message.

Should also update module docs

##### STEPS TO REPRODUCE
```yaml
---

- hosts: access_switches

  tasks:

  - name: MACRO PHONE
    ios_config:
      lines:
      - 'switchport voice vlan 60'
      - 'switchport port-security maximum 2'
      - 'spanning-tree portfast'
      - 'no cdp enable'
      - 'no macro desc'
      - '#macro keywords $DESCRIPTION'
      - '@'
      parents: macro name PHONE
      before: no macro name PHONE
      after: exit
      match: line
      replace: block

```

##### EXPECTED RESULTS

Meaningful message stating this isn't supported

##### ACTUAL RESULTS
```

```
