### ISSUE TITLE
ansible parted module overwrites label and squashes existing partitions

### ISSUE THREAD

**Issue by dustinblack** [ansible/ansible#38594]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

parted

##### ANSIBLE VERSION

```
ansible-2.4.2.0-1.el7.noarch
apologies, I don't have immediate access to the system
```

##### OS / ENVIRONMENT

RHEL 7.4

##### SUMMARY

Given two parted plays where the first play sets a gpt label and the second play does not explicitly set this value, the second play defaults to msdos, overwriting the label and squashing the partition created by the first play.

##### STEPS TO REPRODUCE

```yaml
tasks:
  - name: Create first partition
    parted:
      label: gpt
      state: present
      device: /dev/sdc
      number: 1
      name: p1
      flags: [ lvm ]
      part_start: 0%
      part_end: 10%
      unit: '%'

  - name: Create second partition
    parted:
      state: present
      device: /dev/sdc
      number: 2
      name: p2
      flags: [ lvm ]
      part_start: 11%
      part_end: 100%
      unit: '%'
```

##### EXPECTED RESULTS

The gpt disk label is retained and the second partition is created successfully without overwriting the first.

##### ACTUAL RESULTS

First created partition is squashed and disk label changed from gpt to msdos

This problem does not exist on ansible-2.3.2.0-1.el7.noarch. This _can_ be worked around by adding 'label: gpt' to the second play, but this regression breaks existing playbooks.

```

```
