### ISSUE TITLE
[vmware_guest] Cannot unattach ISO mount automatically

### ISSUE THREAD

**Issue by aguynamedjoetoo** [ansible/ansible#38606]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jengel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jengel/Envs/ansible-2.5/lib/python2.7/site-packages/ansible
  executable location = /Users/jengel/Envs/ansible-2.5/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
```
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /Users/jengel/.vault_pass.txt
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
macOS 10.13.3
vSphere 5.5

##### SUMMARY
When trying to unattach a CD ROM, even using the `force: yes` option, the `vmware_guest` module will hang awaiting a response input from vSphere. This was not the case with the `vsphere_guest` module.

##### STEPS TO REPRODUCE
Given the following plays

```yaml
- name: Create the VM instance
  vmware_guest:
    cdrom:
      iso_path: "{{ iso_path }}"
      type: iso
    cluster: "{{ cluster }}"
    customization:
      hostname: "{{ item.vm_name }}"
    datacenter: "{{ datacenter }}"
    disk:
      - size_gb: "{{ item.storage_gb }}"
        type: thin
        datastore: "{{ datastore }}"
    folder: "{{ folder }}"
    guest_id: "ubuntu64Guest"
    hardware:
      memory_mb: "{{ item.memory }}"
      num_cpus: "{{ item.num_cpus }}"
    hostname: "{{ vcenter_hostname }}"
    name: "{{ item.vm_name }}"
    networks:
      - name: "PG-VM"
        device_type: "e1000"
    password: "{{ ad_password }}"
    state: present
    username: {{ ad_username }}
    validate_certs: no
    wait_for_ip_address: yes
  register: vm
  with_items:
    - "{{ vms }}"

- name: Unattach the ISO mount from the VM
  vmware_guest:
    cdrom:
      type: none
    force: yes
    hostname: "{{ vcenter_hostname }}"
    name: "{{ item.vm_name }}"
    password: "{{ ad_password }}"
    username: {{ ad_username }}
    validate_certs: no
  with_items:
    - "{{ vms }}"
```

The latter play will fail to unattach the ISO unless you click 'yes' in vSphere

<img width="532" alt="screen shot 2018-04-11 at 10 43 01 am" src="https://user-images.githubusercontent.com/4296375/38633654-3064d6ac-3d75-11e8-8419-a1f8da2a4ffc.png">

##### EXPECTED RESULTS
The cd-rom is reconfigured to unattach

##### ACTUAL RESULTS
Here's the result from when I click "no". If I don't click anything the playbook hangs until I click yes or no.

```
TASK [ansible-vsphere : Unattach the ISO mount from the VM] **************************************************************************************************************************
task path: /Users/jengel/devops/ansible/ansible-vsphere/tasks/main.yml:45
Using module file /Users/jengel/Envs/ansible-2.5/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jengel
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/jengel/.ansible/tmp/ansible-tmp-1523468551.9-206061254787841 `" && echo ansible-tmp-1523468551.9-206061254787841="` echo /Users/jengel/.ansible/tmp/ansible-tmp-1523468551.9-206061254787841 `" ) && sleep 0'
<127.0.0.1> PUT /Users/jengel/.ansible/tmp/ansible-local-13836WImLE_/tmpI90xtv TO /Users/jengel/.ansible/tmp/ansible-tmp-1523468551.9-206061254787841/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/jengel/.ansible/tmp/ansible-tmp-1523468551.9-206061254787841/ /Users/jengel/.ansible/tmp/ansible-tmp-1523468551.9-206061254787841/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/jengel/Envs/ansible-2.5/bin/python /Users/jengel/.ansible/tmp/ansible-tmp-1523468551.9-206061254787841/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/jengel/.ansible/tmp/ansible-tmp-1523468551.9-206061254787841/ > /dev/null 2>&1 && sleep 0'
failed: [localhost] (item={u'vm_name': u'ansible_25_test', u'num_cpus': 1, u'storage_gb': 40, u'memory': 1024}) => {
    "changed": true,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {
                "type": "none"
            },
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "REDACTED",
            "disk": [],
            "esxi_hostname": null,
            "folder": null,
            "force": true,
            "guest_id": null,
            "hardware": {},
            "hostname": "REDACTED",
            "is_template": false,
            "linked_clone": false,
            "name": "ansible_25_test",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "template": null,
            "username": "REDACTED",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "item": {
        "memory": 1024,
        "num_cpus": 1,
        "storage_gb": 40,
        "vm_name": "ansible_25_test"
    },
    "msg": "Connection control operation failed for disk 'ide0:1' (203)."
}

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1
```
