### ISSUE TITLE
[vmware_guest] Networks field is not idempotent

### ISSUE THREAD

**Issue by aguynamedjoetoo** [ansible/ansible#38605]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jengel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jengel/Envs/ansible-2.5/lib/python2.7/site-packages/ansible
  executable location = /Users/jengel/Envs/ansible-2.5/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
```
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /Users/jengel/.vault_pass.txt
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
macOS 10.13.3
vSphere 5.5

##### SUMMARY
When running a playbook to create a VMware guest, the play will fail if the VM already exists when you specify the network field:

```
"msg": "Changing the device type is not possible when interface is already present. The failing device type is e1000"
```

The first creation of the VM works just fine, but if you need to run the playbook again (e.g. for compliance checking) it will fail. If you remove the network field from the play and re-run it, it will return as expected.

##### STEPS TO REPRODUCE
Given the following play

```yaml
- name: Create the VM instance
  vmware_guest:
    cdrom:
      iso_path: "{{ iso_path }}"
      type: iso
    cluster: "{{ cluster }}"
    customization:
      hostname: "{{ item.vm_name }}"
    datacenter: "{{ datacenter }}"
    disk:
      - size_gb: "{{ item.storage_gb }}"
        type: thin
        datastore: "{{ datastore }}"
    folder: "{{ folder }}"
    guest_id: "ubuntu64Guest"
    hardware:
      memory_mb: "{{ item.memory }}"
      num_cpus: "{{ item.num_cpus }}"
    hostname: "{{ vcenter_hostname }}"
    name: "{{ item.vm_name }}"
    networks:
      - name: "PG-VM"
        device_type: "e1000"
    password: "{{ ad_password }}"
    state: present
    username: {{ ad_username }}
    validate_certs: no
    wait_for_ip_address: yes
  register: vm
  with_items:
    - "{{ vms }}"
```

Create a new VMware guest. Once the VM is created, attempt to re-run the play.

##### EXPECTED RESULTS
The play runs successfully and returns the VM object

##### ACTUAL RESULTS

```
PLAYBOOK: vsphere.yml ****************************************************************************************************************************************************************
1 plays in vsphere.yml

PLAY [localhost] *********************************************************************************************************************************************************************
META: ran handlers

TASK [ansible-vsphere : Create the VM instance] **************************************************************************************************************************************
task path: /Users/jengel/devops/ansible/ansible-vsphere/tasks/main.yml:1
Using module file /Users/jengel/Envs/ansible-2.5/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jengel
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/jengel/.ansible/tmp/ansible-tmp-1523467334.09-249699336747962 `" && echo ansible-tmp-1523467334.09-249699336747962="` echo /Users/jengel/.ansible/tmp/ansible-tmp-1523467334.09-249699336747962 `" ) && sleep 0'
<127.0.0.1> PUT /Users/jengel/.ansible/tmp/ansible-local-135727il1Wr/tmpHxhwVB TO /Users/jengel/.ansible/tmp/ansible-tmp-1523467334.09-249699336747962/vmware_guest.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/jengel/.ansible/tmp/ansible-tmp-1523467334.09-249699336747962/ /Users/jengel/.ansible/tmp/ansible-tmp-1523467334.09-249699336747962/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/jengel/Envs/ansible-2.5/bin/python /Users/jengel/.ansible/tmp/ansible-tmp-1523467334.09-249699336747962/vmware_guest.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/jengel/.ansible/tmp/ansible-tmp-1523467334.09-249699336747962/ > /dev/null 2>&1 && sleep 0'
failed: [localhost] (item={u'vm_name': u'ansible_25_test', u'num_cpus': 1, u'storage_gb': 40, u'memory': 1024}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {
                "iso_path": "REDACTED",
                "type": "iso"
            },
            "cluster": "REDACTED",
            "customization": {
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "customvalues": [],
            "datacenter": "REDACTED",
            "disk": [
                {
                    "datastore": "REDACTED",
                    "size_gb": "40",
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "REDACTED",
            "force": false,
            "guest_id": "ubuntu64Guest",
            "hardware": {
                "memory_mb": "1024",
                "num_cpus": "1"
            },
            "hostname": "REDACTED",
            "is_template": false,
            "linked_clone": false,
            "name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "e1000",
                    "name": "PG-VM"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "template": null,
            "username": "REDACTED",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    },
    "item": {
        "memory": 1024,
        "num_cpus": 1,
        "storage_gb": 40,
        "vm_name": "ansible_25_test"
    },
    "msg": "Changing the device type is not possible when interface is already present. The failing device type is e1000"
}

PLAY RECAP ***************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
resolved_by_pr #38729

**Comment by Akasurde** [comment]
@Joeskyyy Can you please check above PR and let me know if it works for you ?

needs_info

**Comment by aguynamedjoetoo** [comment]
@Akasurde that seems to at least partially fix the issue. It looks like the module now reports back as changed, even if nothing changed, however. But now  it looks like some variables aren't available on the initial creation of a VM now?

When trying to register the following to my inventory after the initial creation this is now failing (it wasn't before this commit)

```
- name: Add hosts to ansible inventory
  add_host:
    name: "{{ item.item.vm_name }}"
    ansible_ssh_host: "{{ item.instance.hw_eth0.ipaddresses[0] }}"
    ansible_user: {{ some_user }}
    ansible_ssh_pass: "{{ some_ssh_pass }}"
    ansible_become: yes
    ansible_become_pass: "{{ some_ssh_pass }}"
    groups: vsphere
  with_items:
    - "{{ vm.results }}"
```

Returns an error:

```
The task includes an option with an undefined variable. The error was: None has no element 0
``` 

Which looks to be an issue now with `item.instance.hw_eth0.ipaddresses[0]`

Interestingly enough, if I run the playbook again, that play runs just fine.

**Comment by Akasurde** [comment]
@Joeskyyy Can you please paste whole playbook so that I can reproduce this issue in my environment?

**Comment by aguynamedjoetoo** [comment]
```
- name: Create the VM instance
  vmware_guest:
    cdrom:
      iso_path: "{{ iso_path }}"
      type: iso
    cluster: "{{ cluster_name }}"
    customization:
      hostname: "{{ item.vm_name }}"
    datacenter: "{{ datacenter }}"
    disk:
      - size_gb: "{{ item.storage_gb }}"
        type: thin
        datastore: "{{ item.datastore }}"
    folder: "{{ folder_name }}"
    guest_id: "ubuntu64Guest"
    hardware:
      memory_mb: "{{ item.memory }}"
      num_cpus: "{{ item.num_cpus }}"
    hostname: "{{ vcenter_hostname }}"
    name: "{{ item.vm_name }}"
    networks:
      - name: "PG-VM"
        device_type: "e1000"
    password: "{{ ad_password }}"
    state: present
    username: "{{ ad_username }}"
    validate_certs: no
    wait_for_ip_address: yes
  register: vm
  with_items:
    - "{{ vms }}"

- name: Add hosts to ansible inventory
  add_host:
    name: "{{ item.item.vm_name }}"
    ansible_ssh_host: "{{ item.instance.hw_eth0.ipaddresses[0] }}"
    ansible_user: "{{ some_user }}"
    ansible_ssh_pass: "{{ some_pass }}"
    ansible_become: yes
    ansible_become_pass: "{{ some_pass }}"
    groups: vsphere
  with_items:
    - "{{ vm.results }}"
```

**Comment by Akasurde** [comment]
@Joeskyyy Can you please check if vm tools is installed and started on given machine. VMware API and ultimately Ansible uses VM tools to gather network related facts from given VM.

**Comment by aguynamedjoetoo** [comment]
@Akasurde VM tools are indeed installed on the machine.

**Comment by ansibot** [comment]
cc @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
reopen

**Comment by Akasurde** [comment]
!bot_skip

**Comment by Akasurde** [comment]
bot_skip

**Comment by Akasurde** [comment]
bot_skip

**Comment by aguynamedjoetoo** [comment]
@Akasurde looks like this may have been fixed in ansible 2.6?

**Comment by wilmardo** [comment]
The issue that @Joeskyyy might be fixed but the network field still doesn't seem idempotent. I ran it with a portgroup and always reports changed:

```yaml
  networks:
    - name: dv-PROD-RD
      dvswitch_name: dvSwitch_Prod
      type: static
      ip: 172.35.10.21
      gateway: 172.35.10.1
      netmask: 255.255.255.0
```

It also seems an untested case for which I opened a PR #51598
Will look into the root issue today :)

**Comment by wilmardo** [comment]
@Akasurde Looked into this but gave up, I opened the VMware docs of the [VirtualVmxnet3](https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/index.html#link844b21dd141dd45f710d7635484598132cf0692d;vim.vm.device.VirtualVmxnet3.html) object to see if there was something that matches with the network_name. But the docs aren't that friendly to read to say the least.
Is there something more readable? Otherwise I would like to pass this issue on to some of the maintainers?
@Akasurde @ckotte @dav1x @nerzhul @pdellaert @warthog9

**Comment by intrand** [comment]
Still getting this *exact* same issue on Ubuntu with ansible 2.7.10 & pyvmomi 6.5.0.2017.5-0ubuntu1.

I'm using the vmware_guest module to connect to vCenter 6.7 Update 2 to configure our VMs to use a port group on a distributed switch.

Whenever I include "networks" in the vmware_guest configuration, the task says "changed" every play, even when the VMs didn't really change -- no VM reconfiguration task triggers in vCenter.

It seems to behave correctly, but the status of the task is misleading.

For new people, it has become just another one of those "oh, it just does that. Some things are quirky. You get used to it" things.

**Comment by bociankruk** [comment]
Plus on vCenter server, in events we can see what is being changed:
`Reconfigured VM_NAME on ESXi_HOST in DATACENTER_NAME. 
Modified: 
config.hardware.device(4000).backing.port.portKey: "1569" -> "1573"; 
config.hardware.device(4000).backing.port.connectionCookie: 2125120497 -> 1396048833; 
Added: 
Deleted:`

Fortunately, this change is not disrupting connection to the VM. But still, it changes something when it shouldn't.

**Comment by Inanias** [comment]
I ran into the same Issue with ansible 2.8.4 and pyvmomi 6.5.0.2017.5-0ubuntu1.

Not so nice to see a "Reconfigure virtual machine" task when nothing should be changed.
VM events show the same as @bociankruk has posted.

**Comment by angystardust** [comment]
Using Ansible 2.8.6 I still have a "changed" status on every playbook launch:

```
[Wed Oct 30 14:36:44 2019] [info] Task: Reconfigure virtual machine (target=VirtualMachine mycustomer-vm01)
[Wed Oct 30 14:36:46 2019] [info] Reconfigured mycustomer-vm01 on mycluster.example.int in MYCLUSTER.  
 
Modified:  
 
config.hardware.device(4000).backing.port.portKey: "39" -> "45"; 

config.hardware.device(4000).backing.port.connectionCookie: 1239579402 -> 1392461662; 

 Added:  
 
 Deleted:
```


@Akasurde imho with the removal of the `vsphere_guest` module in 2.9, the priority of this issue should be definitely increased

**Comment by toennito** [comment]
I ran into the same issue today. Is there any hope on a fix?

**Comment by angystardust** [comment]
@Tomorrow9 @pgbidkar Can you help here, please?

**Comment by DE110283** [comment]
Facing the same issue (ansible 2.8.2, CentOS 7 (3.10.0-957.el7.x86_64)). It is not only the issue, that the play is listed as "changed" although nothing changed. We have a reboot handler in place which fires every time although nothing has really changed on the network setting. Please provide a fix asap.

**Comment by farflungfish** [comment]
Also facing the same issue CentOS Linux release 7.6.1810 (Core), ansible 2.9.3, pyvmomi (6.7.3)

``` yaml
- name: create VMs
  vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        cluster: "{{ vmware_cluster }}"
        validate_certs: no
        datacenter: "{{ vcenter_datacenter }}"
        datastore: "{{ vmware_datastore }}"
        template: "{{ vcenter_template }}"
        cdrom:
          type: 'none'
        disk:
          - size_gb: "{{ vmware_os_disksize }}"
            type: "{{ vmware_disktype }}"
          - size_gb: "{{ vmware_data_disksize }}"
            type: "{{ vmware_disktype }}"
        folder: "{{ vmware_folder }}"
        hardware:
          boot_firmware: "{{ vmware_firmware }}"
          scsi: "{{ vmware_scsi }}"
          memory_mb: "{{ (vmware_mem * 1024) }}"
          num_cpus: "{{ vmware_cpus}}"
          version: "{{ vmware_hw_vers }}"
        name: "{{ item.vlan_id }}{{ vmware_name_postfix }}"
        networks:
          - name: "{{ vcenter_network_prefix }}{{ item.vlan_id }}"
            device_type: "{{ vmware_netdev }}"
            start_connected: true
            ip: "{{ item.ip }}"
            netmask: "{{ item.netmask }}"
            gateway: "{{ item.gateway }}"
            type: static
            
        customization:
         autologon: yes
         password: "{{ xxx }}"
         timezone: 085
         existing_vm: false

         dns_servers: 
          - "{{xxx}}"
          - "{{xxx}}"
         dns_suffix:
          - "{{xxx}}"
         domain: "{{ item.vlan_id }}{{ vmware_name_postfix }}"
         domainadmin: "{{xxx}}"
         domainadminpassword: "{{xxx}}"
         joindomain: "{{xxx}}"
         orgname: "xxx"

         runonce:
          - powershell.exe -ExecutionPolicy Unrestricted -File C:\Temp\ConfigureRemotingForAnsible.ps1
        state: present
        guest_id: "{{ vmware_guest_id }}"
  with_items: "{{ network_definition }}"
  register: vms_deployed
  delegate_to: localhost
```
**Output:**
```bash
changed: [xxx -> localhost] => (item={u'ip': u'xxx', u'netmask': u'255.255.255.240', u'gateway': u'xxx', u'vlan_id': 2039}) => changed=true
  ansible_loop_var: item
  instance:
    annotation: ''
    current_snapshot: null
    customvalues: {}
    guest_consolidation_needed: false
    guest_question: null
    guest_tools_status: guestToolsRunning
    guest_tools_version: '11265'
    hw_cluster: xxx
    hw_cores_per_socket: 4
    hw_datastores:
    - xxx
    hw_esxi_host: xxx
    hw_eth0:
      addresstype: assigned
      ipaddresses:
      - xxx
      label: Network adapter 1
      macaddress: xxx
      macaddress_dash: xxx
      portgroup_key: dvportgroup-4866
      portgroup_portkey: '335'
      summary: 'DVSwitch: 50 30 d7 3d 16 c7 a1 76-e3 0c e4 d0 d3 50 6a 68'
    hw_files:
    - 'xxx 69d2605e-322c-78be-8a78-b0262816a09c/********.vmx'
    - 'xxx 69d2605e-322c-78be-8a78-b0262816a09c/********.vmxf'
    - 'xxx 69d2605e-322c-78be-8a78-b0262816a09c/********.nvram'
    - 'xxx 69d2605e-322c-78be-8a78-b0262816a09c/********.vmsd'
    - 'xxx 69d2605e-322c-78be-8a78-b0262816a09c/vmware.log'
    - 'xxx 69d2605e-322c-78be-8a78-b0262816a09c/********.vmdk'
    - 'xxx 69d2605e-322c-78be-8a78-b0262816a09c/********_1.vmdk'
    hw_folder: xxx
    hw_guest_full_name: Microsoft Windows Server 2012 (64-bit)
    hw_guest_ha_state: true
    hw_guest_id: windows8Server64Guest
    hw_interfaces:
    - eth0
    hw_is_template: false
    hw_memtotal_mb: 16384
    hw_name: VALUE_SPECIFIED_IN_NO_LOG_PARAMETER
    hw_power_status: poweredOn
    hw_processor_count: 4
    hw_product_uuid: 4230a198-fa64-b081-43c6-11bcfd3097ef
    hw_version: vmx-14
    instance_uuid: 5030fe06-7092-2ec9-7656-d787f03d3cda
    ipv4: xxx
    ipv6: null
    module_hw: true
    moid: vm-10413
    snapshots: []
    vimref: vim.VirtualMachine:vm-10413
    vnc: {}
  item:
    gateway: xxx
    ip: xx
    netmask: xxx
    vlan_id: xx
```
