### ISSUE TITLE
Including handlers-files multiple times results in the handlers running that many times.

### ISSUE THREAD

**Issue by jimbocoder** [ansible/ansible#3863]
### Directory structure

```
./hosts.ini
./roles
./roles/common
./roles/common/handlers
./roles/common/handlers/main.yml
./roles/common/tasks
./roles/common/tasks/main.yml
./handlers
./handlers/shared.yml
./handlercity.yml
```
### roles/common/handlers/main.yml

```

---
- include: /home/jim/src/fgt/handlercity/handlers/shared.yml
- include: /home/jim/src/fgt/handlercity/handlers/shared.yml
- include: /home/jim/src/fgt/handlercity/handlers/shared.yml
- include: /home/jim/src/fgt/handlercity/handlers/shared.yml
- include: /home/jim/src/fgt/handlercity/handlers/shared.yml
- include: /home/jim/src/fgt/handlercity/handlers/shared.yml
```
### roles/common/tasks/main.yml:

```

---

- name: "Trigger handler"
  shell: echo Whatever
  notify:
    - "shared: restart rsyslog"
```
### handlers/shared.yml:

```

---
- name: "shared: restart rsyslog"
  service: name=rsyslog state=restarted enabled=yes
```
### handlercity.yml:

```
---                                                                                                                                                               

- hosts: fgt00                                                                                                                                                    
  sudo: yes                                                                                                                                                       
  gather_facts: no                                                                                                                                                
  roles:                                                                                                                                                          
    - { role: common }                                                                                                                                            
```
#### ansible-playbook  -i hosts.ini  --limit=fgt00 -u ansible handlercity.yml

```
PLAY [fgt00] ****************************************************************** 

TASK: [Trigger handler] ******************************************************* 
changed: [fgt00]

NOTIFIED: [shared: restart rsyslog] ******************************************* 
changed: [fgt00]

NOTIFIED: [shared: restart rsyslog] ******************************************* 
changed: [fgt00]

NOTIFIED: [shared: restart rsyslog] ******************************************* 
changed: [fgt00]

NOTIFIED: [shared: restart rsyslog] ******************************************* 
changed: [fgt00]

NOTIFIED: [shared: restart rsyslog] ******************************************* 
changed: [fgt00]

NOTIFIED: [shared: restart rsyslog] ******************************************* 
changed: [fgt00]

PLAY RECAP ******************************************************************** 
fgt00                      : ok=7    changed=7    unreachable=0    failed=0
```

This behavior is on `1.2.2` and `1.3 (devel ad595eadea)`
