### ISSUE TITLE
vmware_guest Assigns Resource Pool when Undefined

### ISSUE THREAD

**Issue by seifer44** [ansible/ansible#38634]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/XXXXX/gitrepos/rhel_bootstrapper/ansible.cfg
  configured module search path = [u'/home/XXXXX/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

RHEL 7.4

##### SUMMARY

When building a virtual machine, and a resource pool is not specified, a resource pool is associated with a newly built machine, anyway. This is undesirable.

This may be related to issue #22706.

##### STEPS TO REPRODUCE

Create a virtual machine:

```yaml
- name: Create virtual machine
  vmware_guest:
    hostname: "{{ vsphere.fqdn }}"
    port: "{{ vsphere.port }}"
    username: "{{ vsphere.username }}"
    password: "{{ vsphere_password }}"
    template: "{% if hostvars[item].os_distribution|lower() == 'redhat' %}\
        {% if hostvars[item].os_version|int == 7 %}\
        rhel7core_template\
        {% elif hostvars[item].os_version|int == 6 %}\
        rhel6template\
        {% endif %}\
      {% elif hostvars[item].os_distribution|lower() == 'centos' %}\
        {% if hostvars[item].os_version|int == 7 %}\
        centos7_template\
        {% endif %}\
      {% endif %}"
    folder: "{% if hostvars[item].os_distribution|lower() == 'redhat' %}\
      RHEL\
      {% elif hostvars[item].os_distribution|lower() == 'centos' %}\
      CentOS\
      {% endif %}"
    customization:
      hostname: "{{ item | regex_replace('\\..*') }}"
      domain: "{{ item | regex_replace('^[\\d\\w]+\\.') }}"
    networks:
      - name: "{{ vsphere.network_name }}"
        type: dhcp
    datacenter: "{{ vsphere.datacenter }}"
    esxi_hostname: "{{ vsphere.starter_host }}"
    validate_certs: no
    state: present
    name: "{{ item | regex_replace('\\..*') }}"
    hardware:
      memory_mb: "{{ hostvars[item].memory_gb|int * 1024 }}"
      num_cpus: "{{ hostvars[item].cpus }}"
      num_cpu_cores_per_socket: "{{ (hostvars[item].cpus|int / 2) | int }}"
  with_inventory_hostnames:
    - deployhosts
```

##### EXPECTED RESULTS

A virtual machine to have been built un-associated with a resource pool.

##### ACTUAL RESULTS

The virtual machine is built with a resource pool used elsewhere in the vSphere environment.

```
PLAY [local] *****************************************************************************************************************************************************************************************************************************

TASK [deploy-vms : Create virtual machine] ***********************************************************************************************************************************************************************************************
changed: [127.0.0.1] => (item=testvm123.XXXXXXXX) => {"changed": true, "instance": {"annotation": "", "current_snapshot": null, "customvalues": {}, "guest_consolidation_needed": false, "guest_question": null, "guest_tools_status": "guestToolsNotRunning", "guest_tools_version": null, "hw_cores_per_socket": 2, "hw_datastores": ["SVMW_STG_TEMPLATES_01"], "hw_esxi_host": "s-vmware81.********", "hw_eth0": {"addresstype": "assigned", "ipaddresses": null, "label": "Network adapter 1", "macaddress": "00:50:56:b8:62:f8", "macaddress_dash": "00-50-56-b8-62-f8", "summary": "DVSwitch: 46 0e 38 50 fd ab bb 28-a0 0a 5a df c5 03 44 b6"}, "hw_files": ["[SVMW_STG_TEMPLATES_01] ********/********.vmx", "[SVMW_STG_TEMPLATES_01] ********/********.nvram", "[SVMW_STG_TEMPLATES_01] ********/********.vmsd", "[SVMW_STG_TEMPLATES_01] ********/********.vmdk"], "hw_folder": "/DevStage Datacenter/vm/RHEL", "hw_guest_full_name": null, "hw_guest_ha_state": null, "hw_guest_id": null, "hw_interfaces": ["eth0"], "hw_is_template": false, "hw_memtotal_mb": 8192, "hw_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "hw_power_status": "poweredOff", "hw_processor_count": 4, "hw_product_uuid": "42380006-5d2e-3cd3-28c4-20393274dc84", "ipv4": null, "ipv6": null, "module_hw": true, "snapshots": []}, "item": "testvm123.XXXXXXXX"}
changed: [127.0.0.1] => (item=testvm456.XXXXXXXX) => {"changed": true, "instance": {"annotation": "", "current_snapshot": null, "customvalues": {}, "guest_consolidation_needed": false, "guest_question": null, "guest_tools_status": "guestToolsNotRunning", "guest_tools_version": null, "hw_cores_per_socket": 3, "hw_datastores": ["SVMW_STG_TEMPLATES_01"], "hw_esxi_host": "s-vmware81.********", "hw_eth0": {"addresstype": "assigned", "ipaddresses": null, "label": "Network adapter 1", "macaddress": "00:50:56:b8:0f:7b", "macaddress_dash": "00-50-56-b8-0f-7b", "summary": "DVSwitch: 46 0e 38 50 fd ab bb 28-a0 0a 5a df c5 03 44 b6"}, "hw_files": ["[SVMW_STG_TEMPLATES_01] ********/********.vmx", "[SVMW_STG_TEMPLATES_01] ********/********.nvram", "[SVMW_STG_TEMPLATES_01] ********/********.vmsd", "[SVMW_STG_TEMPLATES_01] ********/********.vmdk"], "hw_folder": "/DevStage Datacenter/vm/RHEL", "hw_guest_full_name": null, "hw_guest_ha_state": null, "hw_guest_id": null, "hw_interfaces": ["eth0"], "hw_is_template": false, "hw_memtotal_mb": 12288, "hw_name": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", "hw_power_status": "poweredOff", "hw_processor_count": 6, "hw_product_uuid": "42381ecf-0974-bb32-f5a2-b2dd7c080cb4", "ipv4": null, "ipv6": null, "module_hw": true, "snapshots": []}, "item": "testvm456.XXXXXXXX"}

PLAY RECAP *******************************************************************************************************************************************************************************************************************************
127.0.0.1                  : ok=1    changed=1    unreachable=0    failed=0
```

![vmware-resource-pool](https://user-images.githubusercontent.com/9002783/38639040-4f0adf30-3d8d-11e8-84c8-5f587dbb7d1d.png)
