### ISSUE TITLE
aws_s3: "src" always looking locally for files.

### ISSUE THREAD

**Issue by marcnil815** [ansible/ansible#38656]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aws_s3

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
##### OS / ENVIRONMENT

Ansible host: Ubuntu 16.04 TLS
Remote host: Ubuntu 16.04 TLS

##### SUMMARY
The aws_s3 PUT mode used in a playbook looks for the src file locally, not remote.

##### STEPS TO REPRODUCE

Create file on remote machine: /home/ansible-user/test.txt

```
- name: s3_upload_of_test_file
   hosts: remote_host
   gather_facts: no
   tasks:
     - name: upload_to_s3
       bucket: my_bucket
       object: test.txt
       src: /home/ansible-user/test.txt
       mode: put
```
##### EXPECTED RESULTS
test.txt gets uploaded to bucket.

##### ACTUAL RESULTS
"File cannot be found or accessed."

Creating the file **locally** in the same location results in the file being found.

This does not happen with the deprecated "s3". Some old entries hint at a setting called something along the lines of "src_remote: true" in terms of aws modules, but nothing in the current documentation seems to corroborate that point.
