### ISSUE TITLE
lineinfile adds lines which already exist in the file

### ISSUE THREAD

**Issue by dktodorov** [ansible/ansible#38655]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lineinfile

##### ANSIBLE VERSION
```
ansible 2.4.4.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dtodorov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dtodorov/Tools/.venv/lib/python2.7/site-packages/ansible
  executable location = /home/dtodorov/Tools/.venv/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### OS / ENVIRONMENT
host: fedora 27 x64
target: fedora 27 x64

##### SUMMARY
Module 'lineinfile'  adds lines, which are already in the file. Problem appears with 2.4.4.0, it is working properly in 2.4.3

##### STEPS TO REPRODUCE
```yaml
- hosts: localhost
  vars:
      items_list:
          - item1
          - item2
          - item3
  tasks:
      - name: "append all items"
        lineinfile:
            dest: "test.txt"
            line: '-e {{ item }} \'
            insertbefore: "^--log-file.*"
        with_items: "{{ items_list }}"

      - name: "append all items"
        lineinfile:
            dest: "test.txt"
            line: '-e {{ item }} \'
            insertbefore: "^--log-file.*"
        with_items: "{{ items_list }}"

```

##### EXPECTED RESULTS
To not append items several times.

##### ACTUAL RESULTS
```
PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [append all items] *******************************************************************************************************************************************************************************************
changed: [localhost] => (item=item1)
changed: [localhost] => (item=item2)
changed: [localhost] => (item=item3)

TASK [append all items] *******************************************************************************************************************************************************************************************
changed: [localhost] => (item=item1)
changed: [localhost] => (item=item2)
changed: [localhost] => (item=item3)

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=0   

$ cat test.txt
-e item1 \
-e item2 \
-e item3 \
-e item1 \
-e item2 \
-e item3 \
-e item1 \
-e item2 \
-e item3 \
--log-file test.log
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/lineinfile.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/lineinfile.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ahtik @dhozac
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by simleo** [comment]
Been hit by this as well. In corner cases it seems to crash the module altogether. Here is a shorter path to trigger the bug:

```
$ rm -fv /tmp/junk; touch /tmp/junk
$ ansible localhost -m lineinfile -a "path=/tmp/junk line='hello' state=present insertbefore=BOF"
localhost | SUCCESS => {
    "backup": "", 
    "changed": true, 
    "failed": false, 
    "msg": "line added"
}
$ cat /tmp/junk 
hello
$ ansible localhost -m lineinfile -a "path=/tmp/junk line='hello' state=present insertbefore=BOF"
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IndexError: list index out of range
localhost | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ejpdaI/ansible_module_lineinfile.py\", line 501, in <module>\n    main()\n  File \"/tmp/ansible_ejpdaI/ansible_module_lineinfile.py\", line 492, in main\n    ins_aft, ins_bef, create, backup, backrefs)\n  File \"/tmp/ansible_ejpdaI/ansible_module_lineinfile.py\", line 328, in present\n    elif b_lines[index[1] - 1].rstrip(b('\\r\\n')) != b_line:\nIndexError: list index out of range\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```

Again, lineinfile from ansible 2.4.3 is not affected.

**Comment by ppanczyk** [comment]
I also have this issue and I strongly disagree that #28721 was a bug. The docs states that "This module ensures a particular line **is in a file**", not **in the specific place of a file**. The latter is just another functionality, which should have been implemented in the module using a new option, not by changing the default behaviour.
In fact, there are at least three scenarios worth being covered by the module (in combination with insertafter/insertbefore options):
1. The old default one - inserting a line in the specific place only if it's not already present anywhere in the file (matched by "line" or "regexp");
2. The one from #33393, currently present in the module as the default - inserting a line in the specific place, if it is not already there (regardless whether it is present anywhere else in the file or not);
3. The one that I proposed in #24058 - moving the line to the specified place, if it is already present somewhere else in the file.

To fix this issue, I suggest to add a new option (maybe "place", with possible values "anywhere" (default, case 1 above), "specified" (case 2) and "move" (case 3)?). Ansible Team, what do you think about it? I could merge this with my PR #24058, if you would like me to do so.

**Comment by LukeDRussell** [comment]
I agree that behaviour 1. by @ppanczyk above should be the default. 2. is new functionality in my opinion.

**Comment by jlecour** [comment]
I've had this issue with Ansible 2.5.2 but not with 2.2.

The line is inserted **even if already present** when using "insertbefore" or "insertafter", but inserted only if needed without them.

**Comment by christonog** [comment]
@jlecour I've found the issue to occur on my ansible 2.5.2 even without using "insertbefore" or "insertafter." It always seems to add a line.

```
ansible 2.5.4
  config file = /Users/me/Documents/ansible/ansible.cfg
  configured module search path = ['/Users/me/Documents/ansible/library']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.3 (default, Oct  4 2017, 06:09:15) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```
```
- hosts: localhost
  tasks:
    - lineinfile:
        path: /Users/me/Documents/test/test.txt
        regexp: '^  - use_mount: no'
        line: '  - use_mount: yes'
```

Output:

```
TASK [lineinfile] **********************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /Users/me/Documents/ansible/test.yml:22
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/files/lineinfile.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: me
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python3/bin/python3.6 && sleep 0'
changed: [localhost] => {
    "backup": "",
    "changed": true,
    "diff": [
        {
            "after": "",
            "after_header": "/Users/me/Documents/datadog/test.txt (content)",
            "before": "",
            "before_header": "/Users/me/Documents/datadog/test.txt (content)"
        },
        {
            "after_header": "/Users/me/Documents/datadog/test.txt (file attributes)",
            "before_header": "/Users/me/Documents/datadog/test.txt (file attributes)"
        }
    ],
    "invocation": {
        "module_args": {
            "attributes": null,
            "backrefs": false,
            "backup": false,
            "content": null,
            "create": false,
            "delimiter": null,
            "directory_mode": null,
            "firstmatch": false,
            "follow": false,
            "force": null,
            "group": null,
            "insertafter": null,
            "insertbefore": null,
            "line": "  - use_mount: yes",
            "mode": null,
            "owner": null,
            "path": "/Users/me/Documents/test/test.txt",
            "regexp": "^  - use_mount: no",
            "remote_src": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "state": "present",
            "unsafe_writes": null,
            "validate": null
        }
    },
    "msg": "line added"
}
META: ran handlers
META: ran handlers

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```

**Comment by FatmanUK** [comment]
I'm getting this issue with ansible 2.6.3 on Void Linux x64.

```
ansible 2.6.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fatman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Jul 16 2018, 08:54:52) [GCC 7.3.0]
```

Here's a minimal playbook which demonstrates the problem:
```
---
- name: configure rsyslog
  hosts: ajr-hcs-log-01 ajr-hcs-log-02
  gather_facts: false
  become: yes
  become_user: root
  tasks:
  - name: configure main options
    blockinfile:
      dest: /etc/rsyslog.conf-test-me
      create: yes
      insertbefore: BOF
      block: |
        $ModLoad imuxsock
        some lines snipped
        $UDPServerRun 514
  - name: configure filter rules
    lineinfile:
      dest: /etc/rsyslog.conf-test-me
      line: "\n:{{ item.type }}, {{ item.function }}, \"{{ item.match }}\" {{ item.file }}\n& stop"
    with_items:
    - type: msg
      function: regex
      match: "IPTABLES:"
      file: "-/var/log/iptables"
    - type: programname
      function: isequal
      match: "smtpd"
      file: "/var/log/maillog"
    - type: syslogpriority-text
      function: isequal
      match: "emerg"
      file: ".*"
```

Expected output file:
```
# BEGIN ANSIBLE MANAGED BLOCK
$ModLoad imuxsock
some lines snipped
$UDPServerRun 514
# END ANSIBLE MANAGED BLOCK

:msg, regex, "IPTABLES:" -/var/log/iptables
& stop

:programname, isequal, "smtpd" /var/log/maillog
& stop

:syslogpriority-text, isequal, "emerg" .*
& stop
```
Actual output file (after two runs):
```
# BEGIN ANSIBLE MANAGED BLOCK
$ModLoad imuxsock
some lines snipped
$UDPServerRun 514
# END ANSIBLE MANAGED BLOCK

:msg, regex, "IPTABLES:" -/var/log/iptables
& stop

:programname, isequal, "smtpd" /var/log/maillog
& stop

:syslogpriority-text, isequal, "emerg" .*
& stop

:msg, regex, "IPTABLES:" -/var/log/iptables
& stop

:programname, isequal, "smtpd" /var/log/maillog
& stop

:syslogpriority-text, isequal, "emerg" .*
& stop
```

I hope this report helps to track down and annihilate this bug.

**Comment by samdoran** [comment]
@simleo That bug was fixed by #46071. It will be in 2.6.5 and 2.7.1.

**Comment by samdoran** [comment]
@christonog The reason the line is inserted each time is because `regexp` does not match the line that is inserted. This will give you the desired behaviour:

```yaml
- hosts: localhost
  tasks:
    - lineinfile:
        path: /Users/me/Documents/test/test.txt
        regexp: '^  - use_mount: (yes|no)'
        line: '  - use_mount: yes'
```

**Comment by samdoran** [comment]
@FatmanUK The reason you're seeing multiple insertion is because `lineinfile` matches on _lines_ and therefore will never see anything past newlines when looking for matches. The module does _insert_ lines which contain newlines, though.

Since no lines in the file match the contents of the `line` parameter, the line is always inserted.

`blockinfile` is the appropriate module to use for matching across multiple lines.

```yaml
  tasks:
    - name: configure main options
      blockinfile:
        dest: /etc/rsyslog.conf-test-me
        create: yes
        insertbefore: BOF
        marker: '# {mark} MAIN OPTIONS'
        block: |
          $ModLoad imuxsock
          some lines snipped
          $UDPServerRun 514

    - name: configure filter rules
      blockinfile:
        dest: /etc/rsyslog.conf-test-me
        marker: '# {mark} {{ item.type | upper }} RULES'
        block: |
          :{{ item.type }}, {{ item.function }}, \"{{ item.match }}\" {{ item.file }}
          & stop
      with_items:
        - type: msg
          function: regex
          match: "IPTABLES:"
          file: "-/var/log/iptables"
        - type: programname
          function: isequal
          match: "smtpd"
          file: "/var/log/maillog"
        - type: syslogpriority-text
          function: isequal
          match: "emerg"
          file: ".*"
```

**Comment by samdoran** [comment]
When combining `line` with `insertbefore`, `lineinfile` looks for the exact `line` _immediately_ before `insertbefore`. It does not look everywhere in the file for the presence of the line. To get that behavior, add `regexp` to the task.


```yaml
tasks:
    - name: "append all items"
      lineinfile:
          dest: "test.txt"
          line: '-e {{ item }} \'
          insertbefore: "^--log-file.*"
          regexp: '-e {{ item }} \\'
      with_items: "{{ items_list }}"

    - name: "append all items"
      lineinfile:
          dest: "test.txt"
          line: '-e {{ item }} \'
          insertbefore: "^--log-file.*"
          regexp: '-e {{ item }} \\'
      with_items: "{{ items_list }}"
```

Now for the long explanation.

When inserting multiple lines with a loop, it works fine on the first pass, but subsequent runs trigger more insertions.

This happens because the task says to insert `item1` immediately before `^--log-file.*` and the file looks like this:

```
item1
item2
item3
--log-file test.log
```

Since `item1` is not immediately before `--log-file.*` and no `regexp` is specified, another insertion is triggered.
```
item1
item2
item3      <= This line was found immediately before --log-file test.*
item1
--log-file test.log
```

And again for `item2`.

```
item1
item2
item3
item1      <= This line was found immediately before --log-file test.*
item2
--log-file test.log
```

And again for `item3`.

```
item1
item2
item3
item1
item2      <= This line was found immediately before --log-file test.*
item3
--log-file test.log
```

Maybe the documentation could be improved to clarify this behavior.

needs_info
