### ISSUE TITLE
uri: return_content should identify HAL JSON as JSON

### ISSUE THREAD

**Issue by zjpeterson** [ansible/ansible#38677]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
uri

##### ANSIBLE VERSION

```
ansible 2.4.2.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### SUMMARY
When using the ```uri``` module with a REST API that is using Hypertext Application Language (HAL), it will respond to GET requests with a ```Content-Type``` header of ```application/hal+json```. The ```uri``` module is supposed to detect JSON and load it into a "json" key when ```return_content``` is set to "yes" and the ```Content-Type``` header comes back as ```application/json```. This does not happen when ```Content-Type``` comes back as ```application/hal+json```, even though it's valid JSON.

##### STEPS TO REPRODUCE
Run a GET query against an API which returns responses with ```Content-Type: application/hal+json```. In this example I'm running a query against Aruba ClearPass Policy Manager.

```yaml
- name: Example GET
  uri:
    url: "https://{{ inventory_hostname }}/api/network-device-group/name/example-group"
    method: GET
    return_content: yes
    headers:
      Authorization: "Bearer {{ api_token }}"
      Accept: "application/json"
```

##### EXPECTED RESULTS

The dictionary result should contain a key "json" with the returned data.

##### ACTUAL RESULTS

No such key exists in the result dictionary.

```

```
