### ISSUE TITLE
vmware_guest: Multiple disks and cdrom fails to create

### ISSUE THREAD

**Issue by mooninite** [ansible/ansible#38679]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/custom_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT

RHEL 7.5

##### SUMMARY
The new vmware_guest module does not allow me to create a VM with more than 1 disk and a cdrom attached.

##### STEPS TO REPRODUCE

```yaml
- name: Build Current vSphere guest virtual machine
  delegate_to: localhost
  vmware_guest:
    validate_certs: no
    hostname: "{{ vcenter_server }}"
    username: "{{ vcenter_user }}"
    password: "{{ vcenter_pass }}"
    cluster: "{{ cluster_region }}"
    datacenter: "{{ datacenter }}"
    name: "{{ inventory_hostname }}"
    state: present
    annotation: "{{ inventory_hostname }}"
    folder: "{{ vsphere_guest_folder }}"
    guest_id: "{{ vsphere_guest_osid }}"
    hardware:
      hotadd_cpu: true
      hotremove_cpu: true
      hotadd_memory: true
      memory_mb: "{{ vsphere_guest_memory }}"
      num_cpus: "{{ vsphere_guest_cpu }}"
      scsi: paravirtual
    cdrom:
      type: iso
      iso_path: "[{{ vsphere_isilon }}] ISOs/{{ vsphere_guest_iso }}"
    disk:
    - size_gb: "{{ vsphere_guest_disk }}"
      type: thin
      datastore: "{{ vsphere_guest_datastore }}"
    - size_gb: "{{ vsphere_data_disk }}"
      type: thin
      datastore: "{{ vsphere_guest_datastore }}"
    networks:
    - name: "{{ vsphere_guest_network }}"
      device_type: vmxnet3
```

##### EXPECTED RESULTS

VM created with two hard disks and a CD-ROM attached with my ISO. vsphere_guest successfully creates a VM with two drives and a cdrom attached.

##### ACTUAL RESULTS

Using two disks fails:
"Failed to create a virtual machine : Number of virtual devices exceeds the maximum for a given controller."

I have to create my desired VM this way:

1. Create VM with 1 disk and cdrom
2. With state: present, specify all disks (2 disk list). Trying to use state: poweredon ignores disks list.
3. With state: poweredon, power on VM. VM has 2 drives and cdrom
