### ISSUE TITLE
nmcli: default for autoconnect is no, should be yes

### ISSUE THREAD

**Issue by morxa** [ansible/ansible#38671]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME

nmcli

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/thofmann/.ansible.cfg
  configured module search path = [u'/home/thofmann/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/home/thofmann/.ansible.cfg) = [u'/home/thofmann/.ansible/roles']
```
##### OS / ENVIRONMENT

Fedora 27
##### SUMMARY

The documentation says that the default value for autoconnect is `true`, but it is actually `false`.
Either the documentation is wrong, or the default is wrong. I'd prefer the default to be `autoconnect: yes`.

##### STEPS TO REPRODUCE

Run the playbook below.

```yaml
---
- hosts: localhost
  tasks:
  - name: add a test connection
    nmcli:
      conn_name: test_conn
      type: ethernet
      state: present
```

##### EXPECTED RESULTS

```
$ nmcli con show test_conn | grep 'connection.autoconnect:'
connection.autoconnect:                 yes
```
##### ACTUAL RESULTS

```
$ nmcli con show test_conn | grep 'connection.autoconnect:'
connection.autoconnect:                 no
```
