### ISSUE TITLE
aws_s3: Could not find or access 'src'

### ISSUE THREAD

**Issue by hamza-tumturk** [ansible/ansible#38680]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

aws_s3

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = **
  configured module search path = **
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 19 2018, 11:43:51) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

N/A (Ubuntu 16.04.5, OSX 10.13.4)

##### SUMMARY

Since upgrading from Ansible v2.4.3.0 to v2.5.0 the aws_s3 module fails with "Could not find or access ...", even though the file exists on the host with 777 permissions. Running the ansible as become does not make a difference.

##### STEPS TO REPRODUCE

```yaml
- name: Create temporary file
  tempfile:
    state: file
  register: tmp_file

- name: Set temp file permissions
  file:
    path: "{{ tmp_file.path }}"
    mode: 0777

- name: Check if tmp_file exists
  stat:
    path: "{{ tmp_file.path }}"
  register: stat_result

- name: Store to aws
  aws_s3:
    src: "{{ tmp_file.path }}"
    aws_access_key: "{{ cassandra_backup_aws_id }}"
    aws_secret_key: "{{ cassandra_backup_aws_key }}"
    region: "{{ aws_region }}"
    bucket: "{{ s3_bucket }}"
    object: "/{{ s3_path }}/{{ ansible_date_time.date }}"
    mode: put
  when: stat_result.stat.exists
```

##### EXPECTED RESULTS

In Ansible v2.4.3.0
```
TASK [Store to aws] ****************************
changed: [id79672]
```
The temp file should be uploaded to S3 successfully.

##### ACTUAL RESULTS

In ansible v2.5.0

```
TASK [Store to aws] ****************************
FAILED! => {"changed": false, "msg": "Could not find or access '/tmp/ansible.GaZ5Fw'"}
```
