### ISSUE TITLE
interfaces_file: misplaced option source-directory /etc/network/interfaces.d\n in line 7

### ISSUE THREAD

**Issue by gthieleb** [ansible/ansible#38691]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
interfaces_file

##### ANSIBLE VERSION
```
ansible-playbook 2.5.0 (devel 43cbcbcc75) last updated 2018/03/15 23:05:39 (GMT +200)
  config file = /home/gt0015/.ansible.cfg
  configured module search path = ['/home/gt0015/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /data/development/ansible/src/lib/ansible
  executable location = /data/python/envs/ansible/bin/ansible-playbook
  python version = 3.6.4 (default, Mar 25 2018, 13:14:42) [GCC 8.0.1 20180222 (Red Hat 8.0.1-0.16)]
```

##### CONFIGURATION
```
[default]
stdout_callback = full_skip
display_skipped_hosts = False
```
##### OS / ENVIRONMENT
```
Linux rpi-1 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
```
##### SUMMARY
Run ansible-playbook network.yml yml file against rpi with Raspbian (Debian Jessie)
##### STEPS TO REPRODUCE
```
      - interfaces_file: 
            backup: yes
            iface: "{{ iface }}"
            option: "address"
            value: "{{ ip }}"
      - interfaces_file: 
            iface: "{{ iface }}"
            option: "netmask"
            value: "255.255.255.0"
```
and an inventory file containing:
```
[rpi]
rpi-1 ip=192.168.178.111 iface=eth0
```
##### EXPECTED RESULTS
add static ip address for iface
/etc/network/interfaces:
```
       iface eth0 inet static
            address 192.168.178.111
            netmask 255.255.255.0
```
 
##### ACTUAL RESULTS
TASK [interfaces_file] ****************************************************************************************************************************************************************************
```
fatal: [rpi-1]: FAILED! => {"changed": false, "failed": true, "msg": "misplaced option source-directory /etc/network/interfaces.d\n in line 7"}
```
