### ISSUE TITLE
Enabled change detection in check_mode for command module is creates argument is defined

### ISSUE THREAD

**Issue by theorun** [ansible/ansible#38701]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

command

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### SUMMARY

If the creates argument is specified for the command module, use the file state to check if the command would cause a change event when ran in check mode.

##### STEPS TO REPRODUCE

```yaml
- command: touch /tmp/file
  args:
    creates: /tmp/file

# Current
skipping: [localhost]

# Proposed if /tmp/file exists
ok: [localhost]

# Proposed if /tmp/file does not exist
changed: [localhost]
```
