### ISSUE TITLE
vmware_guest - Failed to set Fixed IP - VCenter 6.5 - Windows VM

### ISSUE THREAD

**Issue by imjoseangel** [ansible/ansible#38715]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/imjoseangel/.ansible/library']
  ansible python module location = /home/imjoseangel/.local/lib/python2.7/site-packages/ansible
  executable location = /home/imjoseangel/.local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

ANSIBLE_COW_SELECTION(env: ANSIBLE_COW_SELECTION) = tux
ANSIBLE_NOCOLOR(env: ANSIBLE_NOCOLOR) = False
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/home/imjoseangel/.ansible/library']
DEFAULT_STRATEGY(env: ANSIBLE_STRATEGY) = debug
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/imjoseangel/.vault_pass.txt
##### OS / ENVIRONMENT

Linux (CentOS 7.4)
##### SUMMARY

Fix IP Assignment not working when deploying VM from Template
##### STEPS TO REPRODUCE

Just run a new Windows from Template.

VMware ESXi, 6.5.0, 5310538
Windows Server 2012 R2
VCenter 6.5.0 7515524

```yaml
  tasks:
    - name: Clone a VM from Template and customize
      vmware_guest:
        hostname: "{{ vmware_vsphere_host }}"
        username: "{{ vmware_vsphere_username }}"
        password: "{{ vmware_vsphere_password }}"
        validate_certs: no
        datacenter: DataCenter
        name: testvm-2
        folder: /folder
        template: mytemplate
        state: poweredon
        networks:
        - name: VM Network
          ip: 10.10.10.10
          netmask: 255.255.255.0
          gateway: 10.10.10.1
          dns_servers:
          - 10.10.10.1
          - 10.10.10.2
          type: static
          start_connected: True
      delegate_to: localhost
```

##### EXPECTED RESULTS

Fixed IP on VM
##### ACTUAL RESULTS

No IP or DHCP IP Address. We have proven with different configration options (DNS, no DNS, state:create, state:poweredon). Different Template Configurations (With and without NIC).

Reference - #33380 

```
TASK [provision-vm : Build template list] *********************************15:52:30
ok: [localhost] => (item={u'size_gb': 40, u'autoselect_datastore': True})
TASK [provision-vm : Merge Two Lists] *************************************15:52:30
ok: [localhost]
TASK [provision-vm : Set the default size of machine if it's not define in Config] ***15:52:30
skipping: [localhost]
TASK [provision-vm : Set the size of machine if it's define in Config] ***15:52:30
ok: [localhost]
TASK [provision-vm : Assert VmWare VM name length] ************************15:52:30
skipping: [localhost]
TASK [provision-vm : Assert VmWare VM name length] ************************15:52:30
ok: [localhost] => {
    "changed": false, 
    "msg": "All assertions passed"
}
TASK [provision-vm : vmware_guest | Manage VMs] ***************************15:52:30
ok: [localhost] => (item=NEW-VM)
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @akasurde @dagwieers @dav1x @jctanner @nerzhul @pdellaert
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@imjoseangel Thanks for reporting this issue.

**Comment by cigamit** [comment]
Is VMWare tools installed on the template, and did the template already have sysprep ran on it already?

**Comment by imjoseangel** [comment]
Hi! 

VMWare Tools are installed but not sysprep. I will test with sysprep ASAP. Is it mandatory?

**Comment by cigamit** [comment]
No, it should not be sysprepped first, because VMWare will force a sysprep to do the customization.  I was just making sure that you didn't, as the original sysprep will always win over the VMWare attempt.

**Comment by cigamit** [comment]
Can you watch the machine as it boots up and see if VMWare attempts its sysprep.  You might also try putting in a customization like this to see if that helps.  If so, that may help us narrow down.
```
    customization:
      autologon: True
      dns_servers:
      - 10.10.10.1
      - 10.10.10.2
```

**Comment by imjoseangel** [comment]
Hi!

When doing customization you neeed to specify first network configuration like this:

```yaml
      vmware_guest:
        hostname: "{{ vmware_vsphere_host }}"
        username: "{{ vmware_vsphere_username }}"
        password: "{{ vmware_vsphere_password }}"
        validate_certs: no
        networks:
        - name: VM Network
          ip: 10.100.10.10
          netmask: 255.255.255.0
          gateway: 10.100.10.1
        customization:
          autologon: True
          dns_servers:
          - 10.100.10.11
          - 10.100.10.12
        datacenter: DataCenter
        name: testvm-2
        folder: /folder
        template: mytemplate
        state: poweredon
```
When doing this way, the VM is created but not poweredon and you get the message:

` "msg": "Failed to create a virtual machine : Cannot complete customization."`

When doing only customization, of course it expects a network device and the error is:

`    "msg": "Failed to create a virtual machine : The number of network adapter settings in the customization specification: 0 does not match the number of network adapters present in the virtual machine: 1."`

If relaunched, the VM changes its status:

```
TASK [Clone a VM from Template and customize] **********************************************************************************
changed: [host] => {"changed": true}
```

Unfortunately the customization at this point is not acting

**Comment by ansibot** [comment]
cc @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dealkk** [comment]
I have similar issue.
- name: change ip address of existing vm
  vmware_guest:
    datacenter: "{{ VCenter_DataCenter }}"
    validate_certs: no
    folder: "{{ VCenter_FolderPath }}"
    name: "{{ Server_Name }}"
    state: present
    networks:
    - name:  "{{ Server_Nic.Name }}"
      type: static
      ip: 172.16.1.25
      netmask: "{{ Server_Nic.NetMask }}"
      gateway: "{{ Server_Nic.GateWay }}"
      dns_servers:
      - 172.16.1.11
    wait_for_ip_address: yes
  delegate_to: localhost

result: log show it change and successful ,but actual not change. it remain same configuration
expected: vm change to new ip : 172.16.1.25

**Comment by cigamit** [comment]
@dealkk Did the VM itself already exist?  I believe VMWare customization (changing IPs, etc..) will only work at provisioning time.

**Comment by dealkk** [comment]
yes, vm already exist. base on documentation if the state is present, it ensure all setting set
"If state is set to present and VM exists, ensure the VM configuration conforms to task arguments."
Anyway to change/set static  ip on existing machine, it currently set to hdcp.

**Comment by larrybg** [comment]
I'm facing the same issue - cloning Windows 2010/12 VM from a template doesn't set the static IP.
I use ansible v2.6.1. Are there any updates?

**Comment by 5t4rdu5t** [comment]
Same issue, using ansible-playbook 2.6.2 and Debian9 guest, pyvmomi 5.5.0, VMware vCenter Server 6.0, API type:     VirtualCenter

```
# Deploy a guest from a template*
- hosts: 127.0.0.1
  tasks:
  - name: Create a virtual machine
    vmware_guest:
      datacenter: xxx
      hostname: vcenter1.foobar.tld
      username: xxxx
      password: xxxx
      validate_certs: False
      folder: xxx/yyy/zzz
      name: TEST-01
      template: TEMPLATE-DEBIAN9
      cluster: cluster1
      state: poweredon
      hardware:
        memory_mb: 1024
        num_cpus: 1
      networks:
      - name: LAN_394_FOOBAR
        nic1:
          type: vmxnet3
          network_type: standard
      - name: WAN_432_FOOBAR
        nic2:
          type: vmxnet3
          network_type: standard
          ip: x.x.x.x
          netmask: 255.255.255.0
          gateway: x.x.x.x
          domain: foobar.tld
          dns_servers:
          - x.x.x.x
          - x.x.x.y
```

The VM is created, but no ip set
