### ISSUE TITLE
Allow alternative variable names for items when using "with_items"

### ISSUE THREAD

**Issue by wilsaj** [ansible/ansible#3872]
When iterating over a collection of items with `with_items:` (and `with_nested:`, `with_index_items:`), it would be nice to have the option of specifying an alternative variable name to hold items ('item' would still be the default). This would allow for arbitrary nesting and could also improve readability of tasks.

As an example, this is something I'm actually trying to do (sorry if it's a bit long):

```
# vars file
apps:
  - {
      python_modules: ['moduleA', 'moduleB'],
      virtualenv: /var/www/app1/env,
    }
  - {
      python_modules: ['moduleA', 'moduleC', 'moduleQ'],
      virtualenv: /var/www/app2/env,
    }
...
```

```
# main tasks file

---
  - include: deploy_python_modules.yml
    vars:
      python_modules: ${item.python_modules}
      virtualenv: ${item.virtualenv}
    with_items: apps
```

```
# deploy_python_modules.yml tasks file

---
  - include: deploy_package.yml
    vars:
      dist: ${item}-0.1.tar.gz
    with_items: ${python_modules}
```

```
# deploy_package.yml tasks file

---
  - name: Push package ${dist} to remote machine
    copy: src=build/{{ dist }} dest=/tmp/{{ dist }}
    tags:
      - deploy

  - name: Install package ${dist} on remote machine in ${virtualenv}
    pip: name=/tmp/{{ dist }} virtualenv={{ virtualenv }} state=latest
    tags:
      - deploy
```

This doesn't work because at the time that the bottom tasks' templates are evaluated, `{{ virtualenv }}` resolves to `${item.virtualenv}` and that fails to resolve to anything. The 'item' variable from the outer `with_items:` loop (which iterated over the 'apps' variable) has been replaced by the inner `with_items:` loop which iterated over the 'python_modules' variable.

Here's the same example, using `items_as:` as a way of specifying an alternative variable name to use instead of "item":

```
# vars file
apps:
  - {
      python_modules: ['moduleA', 'moduleB'],
      virtualenv: /var/www/app1/env,
    }
  - {
      python_modules: ['moduleA', 'moduleC', 'moduleQ'],
      virtualenv: /var/www/app2/env,
    }
...
```

```
# main tasks file

---
  - include: deploy_python_modules.yml
    with_items: apps
    items_as: app
```

```
# deploy_python_modules.yml tasks file

---
  - include: deploy_package.yml
    vars:
      dist: ${module}-0.1.tar.gz
    with_items: app.python_modules
    items_as: module
```

```
# deploy_package.yml tasks file

---
  - name: Push package ${dist} to remote machine
    copy: src=build/{{ dist }} dest=/tmp/{{ dist }}
    tags:
      - deploy

  - name: Install package ${dist} on remote machine in ${app.virtualenv}
    pip: name=/tmp/{{ dist }} virtualenv={{ app.virtualenv }} state=latest
    tags:
      - deploy
```

If this sounds good, I can work on a PR.
