### ISSUE TITLE
Module openshift_raw doesn't seem to respect CA-certificates

### ISSUE THREAD

**Issue by pritho** [ansible/ansible#38722]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

openshift_raw
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### OS / ENVIRONMENT

CentOS 7.4

##### SUMMARY

Module openshift_raw doesn't seem to respect own CA-certificates, getting error:
"msg": "Failed to retrieve requested object: (\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",)"

I'm logged in to the openshift-API using the oc-tools, which work fine with the implemented SSL-certificate signed by our internal root-CA. Also trying a curl against the API does not drop any SSL-error.
Also tried to debug using the urllib2-test.py from here: https://access.redhat.com/articles/2039753
--> also works fine.

##### STEPS TO REPRODUCE

Use a custom root-CA certificate and enable ssl-verification.

```yaml
- name: Create new project
  openshift_raw:
    state: present
    api_version: v1
    kind: Project
    name: "{{ project_name }}"
    description: "{{ project_description }}"
    display_name: "{{ project_display_name }}"
```

##### ACTUAL RESULTS

Playbook fails with SSL-error: 
"msg": "Failed to retrieve requested object: (\"bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)\",)"

```

```
