### ISSUE TITLE
nsupdate cant insert multiple A records with the same name for different IPs (no DNS loadbalancing possible)

### ISSUE THREAD

**Issue by CayoM** [ansible/ansible#38736]
##### ISSUE TYPE
not really sure if this is a bug or more a feature request

##### COMPONENT NAME
nsupdate

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT
Ubuntu 16.04.4 LTS

##### SUMMARY
im setting up a DNS server and setting DNS records dynamically using the module nsupdate. Everything is working as supposed to, however when i want to create multiple A records with the same name for different IP addresses, the A record gets overwritten every time. With this behavior im not able to DNS loadbalancing.

##### STEPS TO REPRODUCE

```yaml
task/main.yml

---
- name: Add A records for DNS loadbalancing
  nsupdate:
    key_algorithm: "{{ dns_key_algorithm }}"
    key_name: "{{ dns_key_name }}"
    key_secret: "{{ dns_key_secret }}"
    type: "A"
    server: "{{ dns_server_ip }}"
    zone: "{{ dns_zone }}"
    record: "{{ item.split('-')[0] }}"
    value: "{{ item.split('-')[1] }}"
    state: present
  delegate_to: "{{ dns_server_ip }}"
  notify: rndc sync
  with_items: "{{ loadbalancing }}"



vars/mail.yml

---
loadbalancing:
  - ldap-10.6.111.10
  - ldap-10.5.111.10
  - dns-10.6.111.8
  - dns-10.5.111.8


```

##### EXPECTED RESULTS
i would expect to have multiple identical records with different values. Maybe a new "type" can be introduced... something like "loadbalancer" which would not fall into "record_exists" and update the existing record.

##### ACTUAL RESULTS
the records get overwritten.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/nsupdate.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nsupdate.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @nerzhul
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Nothing4You** [comment]
Try something like this:
```yaml
- nsupdate:
    record: "{{ item.name }}"
    type: "a"
    value: "{{ item.records }}"
  with_items:
    - name: ldap
      records:
      - 127.0.0.1
      - 127.0.0.2
    - name: dns
      records:
      - 127.0.0.3
      - 127.0.0.4
```
