### ISSUE TITLE
s3_bucket Statement is missing required element

### ISSUE THREAD

**Issue by adrianrise** [ansible/ansible#38741]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

s3_bucket

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### CONFIGURATION

Empty.

##### OS / ENVIRONMENT

macOS High Sierra

##### SUMMARY

Well, I am trying to update a current policy in a bucket and I get the following error:

```
The full traceback is:
  File "/var/folders/j5/89mh9jqs1pb84c866ltkrgdc0000gn/T/ansible_oKE3vJ/ansible_module_s3_bucket.py", line 226, in _create_or_update_bucket
    bucket.set_policy(json.dumps(policy))
  File "/usr/local/lib/python2.7/site-packages/boto/s3/bucket.py", line 1594, in set_policy
    response.status, response.reason, body)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "ceph": false,
            "ec2_url": null,
            "force": false,
            "name": "whatever",
            "policy": "whatever,
            "profile": "default",
            "region": "us-east-1",
            "requester_pays": false,
            "s3_url": null,
            "security_token": null,
            "state": "present",
            "tags": null,
            "validate_certs": true,
            "versioning": null
        }
    },
    "msg": "Statement is missing required element"
```
And this is what I have in the playbook:

```
  - name: Update S3 source code policy for us-east-1.
    s3_bucket:
      name: whatever
      profile: default
      region: us-east-1
      policy: "{{ lookup('file','./templates/s3sourcecode_policy.json') }}"
```

##### STEPS TO REPRODUCE

ansible-playbook -i inventory/hosts create_infra.yaml

####

So this is what I am getting when using the module with those few options.
I do not know why, because the only required parameter is the name...

Any idea?
