### ISSUE TITLE
validate does not set user/group on temp file

### ISSUE THREAD

**Issue by bartekbrzezinski** [ansible/ansible#38745]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

copy

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/bbrzezinski@pracuj.local/ansible/ansible.cfg
  configured module search path = [u'/home/bbrzezinski@pracuj.local/ansible/custom_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```
##### CONFIGURATION

```
DEFAULT_ASK_VAULT_PASS = True
DEFAULT_CALLBACK_WHITELIST = ['profile_tasks']
RETRY_FILES_ENABLED = False
```
##### OS / ENVIRONMENT

N/A, reproductible on any version of Ansible
##### SUMMARY

This is similar to #3319 - validate in template module does not set user/group on temporary templated file, it's owned by the user ansible is run as. If validating command expects different user/group than the ansible user, such command will fail. 

This is rather easy to fix, I'll create PR shortly.
##### STEPS TO REPRODUCE

Run ansible as non-root and non-filebeat user.

```yaml
- name: "Template filebeat config"
  template:
    src: "filebeat.yml.j2"
    dest: "/etc/filebeat/filebeat.yml"
    owner: root
    group: root
    validate: "/usr/share/filebeat/bin/filebeat -configtest -c %s"
```

##### EXPECTED RESULTS

Templated file gets validated.
##### ACTUAL RESULTS

Validating binary complains about file ownership.

```
Exiting: error loading config file: config file ("filebeat.yml") must be
owned by the beat user (uid=501) or root
```
