### ISSUE TITLE
sqlite sql runner for inserting or upserting simple configuration into a database

### ISSUE THREAD

**Issue by michaelkaye** [ansible/ansible#38754]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
sqlite_runner

##### SUMMARY

When provisioning some software which uses a sqlite database to store configuration, it would be beneficial to be able to execute queries against that database to commit information as part of the provisioning process.

Additionally, it would be beneficial to have the difference between "changed" and "ok" if re-provisioning similar statements.

##### STEPS TO REPRODUCE

```yaml
- name: upsert configuration information into database
  sqlite_runner:
      file: "sqlite.db"
      statements: [
           "INSERT OR IGNORE INTO <table> (a, b, c) VALUES ("a-value", "b-value", "{{ c-value ]}");"
           "UPDATE <table> set c = "{{ c-value }}" where a = a-value and b= b-value;"
      ]
     register: sqlite_config

- name: restart service
  service:
     name: service
     state: restarted
  when: sqlite_config.changed
```

##### EXPECTED RESULTS

Having run the above we would be able to ensure that a certain set of rows in a sqlite database were in sync with configuration information. 

The result of using this module would include a "rows_changed" value, summed over the two SQL statements we ran.

If equal to "0" this would also result in the module returning "ok", otherwise we would return "changed". Errors would report as "error" and stop the build.

The pair of statements are required for my use case - just one isn't enough. The first ensures a row exists if it's not present; the second updates the row to be 'correct' where it differs from the configuration.

##### ACTUAL RESULTS

At the moment, running 'sqlite' in a command or script works, but it's always "changed". I'm planning on writing a private module for my specific use case (so it would be "provision-my-configuration-in-sqlite", taking just my parameter values and hiding the actual SQL statements) which would be very custom to my usecase.

However, I was hoping that there's a desire for a generic "run repeatable sqlite statements and report their success" module that would be suitable for general use.

Longer term I see a set of similar named modules with identical interfaces that also run against mysql , postgresql, etc, possibly also taking a script as an alternative to a set of inline commands to run.
