### ISSUE TITLE
win_group_membership NetBIOS domain lookup makes invalid assumptions

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#38757]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_group_membership

##### ANSIBLE VERSION

```
2.4.2.0
```

##### CONFIGURATION

N/A -- issue in Windows PowerShell module
##### OS / ENVIRONMENT

Windows - specific version, and environment of Ansible control node, N/A
##### SUMMARY

The win_group_membership module attempts to look up the NetBIOS name of a domain if an FQDN is passed in.

https://github.com/ansible/ansible/blob/d639d5dc96dce5eb50cf4c8baf8154d79d02e2ee/lib/ansible/modules/windows/win_group_membership.ps1#L80

However if the forest name is not the same as the domain name, the module fails and users cannot be added to/removed from groups.

For example if the domain "FABRIKAM" (FQDN fabrikam.com) is in a forest called "acme.com" this will fail.
##### STEPS TO REPRODUCE

In a Windows/AD environment, set up a domain which has an FQDN that is not equal to the forest name.

```yaml
  - name: Add local administrators
    win_group_membership:
      name: Administrators
      members:
        - "AdminGroup@fabrikam.com"
        - "User@fabrikam.com"
      state: present
```

##### EXPECTED RESULTS

Expected to add user/group to the local administrators group
##### ACTUAL RESULTS

```
"Could not resolve NetBIOS name for domain fabrikam.com"
```

**Comment by ansibot** [comment]
@tswanson27 Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ghost** [comment]
Updated to include correct template and more info

**Comment by ansibot** [comment]
cc @andrewsaraceni @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by andrewsaraceni** [comment]
Hey @tswanson27, using the example you provided, could you confirm if the following syntax would succeed in adding the users to the group, i.e. using DOMAIN\username (but not FQDN)?

```yaml
  - name: Add local administrators
    win_group_membership:
      name: Administrators
      members:
        - fabrikam\AdminGroup
        - fabrikam\User
      state: present
```

The WMI query you reference, and that entire bit of code surrounding it (lines 78-86), is mostly designed as a convenience translation for cases where an FQDN is provided, as the domain name is what's ultimately needed to do the actual additions/removals via ADSI.  If you provide that from the outset, I believe that'll bypass the check altogether, and would then accommodate mismatched domain and forest names.  I'm not aware of any other method to get the proper domain name back in that scenario, without other complications or dependencies.
