### ISSUE TITLE
lambda_policy is complaining about invalid characters that should be accepted.

### ISSUE THREAD

**Issue by dumblerod** [ansible/ansible#38769]
- Bug Report

##### COMPONENT NAME
lambda_policy

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/custom_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT
Ansible is on Redhat

##### SUMMARY
lambda_policy module is being called and I'm passing in a ARN to the function_name attribute.  Getting an error:
Function name arn:aws:lambda:us-east-1:999999999999:function:startinstance:1 is invalid. Names must contain only alphanumeric characters and hyphens.

##### STEPS TO REPRODUCE
Here is the function definition and the policy definition:
```
- name: Create lambda function for starting and stopping EC2 instances
  lambda:
    name: "{{ item.name }}"
    state: present
    zip_file: "/tmp/ec2_cycle/ec2_cycle.zip"
    runtime: python2.7
    role: "{{ lambdarole.iam_role.arn }}"
    handler: "{{ item.handler }}"
    timeout: 10
  with_items:
    - name: start_instance
      handler: ec2_cycle.ec2_start
    - name: start_rds_instance
      handler: ec2_cycle.rds_start
    - name: stop_instance
      handler: ec2_cycle.stop
  register: lambdafunction

- name: Create Lambda policy to allow CloudWatch event to trigger startEC2Instance function
  lambda_policy:
    function_name: "{{ lambdafunction.results[0].configuration.function_arn }}"
    statement_id: "startInstanceStatementId"
    action: "lambda:InvokeFunction"
    principal: "events.amazonaws.com"
    region: "{{ region }}"
    state: present
```

##### EXPECTED RESULTS
This configuration has worked for many runs in the past.  It broke after moving to Ansible 2.5.

##### ACTUAL RESULTS
```
See above error description.  Command output:
Function name arn:aws:lambda:us-east-1:999999999999:function:startinstance:1 is invalid. Names must contain only alphanumeric characters and hyphens.
```
