### ISSUE TITLE
ios_command module bug with IOS software installation command

### ISSUE THREAD

**Issue by awilki01** [ansible/ansible#38768]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ios_command

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/dw1054/.ansible.cfg
  configured module search path = [u'/home/dw1054/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
```
[DEPRECATION WARNING]: [defaults]hostfile option, The key is misleading as it can also be a list 
of hosts, a directory or a list of paths . This feature will be removed in version 2.8. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
DEFAULT_HOST_LIST(/home/dw1054/.ansible.cfg) = [u'/ansible/training/ansible-hosts']
```

##### OS / ENVIRONMENT

Ansible Control Server: Red Hat Enterprise Linux Server release 7.4 (Maipo)
Cisco IOS version: Cisco IOS Software, IOS-XE Software, Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 03.07.04E RELEASE SOFTWARE (fc1)

##### STEPS TO REPRODUCE

```yaml
- name: Install software to flash of switch(es)                             
     ios_command:                                                              
       provider: "{{ creds_ssh_10min }}"                                       
       commands: "software install file flash:{{ image }} new force on-reboot"
     when: ansible_net_version != standard_version                             
     tags: install_software      
```

##### ACTUAL RESULTS

When executing the command directly on the switch using manual CLI:
```
Test3650#software install file flash:cat3k_caa-universalk9.16.03.05b.SPA.bin new force on-reboot 
Preparing install operation ...
[1]: Starting install operation 
[1]: Expanding bundle flash:cat3k_caa-universalk9.16.03.05b.SPA.bin
[1]: Copying package files
[1]: Package files copied
[1]: Finished expanding bundle flash:cat3k_caa-universalk9.16.03.05b.SPA.bin
[1]: Verifying and copying expanded package files to flash:
[1]: Verified and copied expanded package files to flash:
[1]: Starting compatibility checks
[1]: Bypassing peer package compatibility checks due to 'force' command option
[1]: Finished compatibility checks
[1]: Starting application pre-installation processing
[1]: No old package files removed
[1]: No new package files added
[1]: Creating pending provisioning file
[1]: Finished installing software.  New software will load on reboot.


Test3650#
```

**Comment by salman1485** [comment]
what issue do you get when you run through ansible? 

I've used below setup plenty of times (but not with 2.4.2) and it has worked.

```
- name: Upgrade IOS
  ios_command:
    commands:
      - "software install file flash:{{ upgrade_file }} on-reboot"
    timeout: 1200
    provider: "{{ cli }}"
  register: softwareinstall
```

```
- name: Reboot Device
  ios_command:
    commands:
      - "write mem\ny"
      - "reload in 1\ny"
    timeout: 300
    retries: 1
    provider: "{{ cli }}"
```
