### ISSUE TITLE
win_deploy_helper module for Windows

### ISSUE THREAD

**Issue by poiriermike** [ansible/ansible#38770]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

deploy_helper

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/local/AD/mi0630796/.ansible.cfg
  configured module search path = ['/home/local/AD/mi0630796/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/local/AD/mi0630796/.local/share/virtualenvs/ansible/lib/python3.5/site-packages/ansible
  executable location = /home/local/AD/mi0630796/.local/share/virtualenvs/ansible/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Host
Ubuntu 16.04
Target
Windows

##### SUMMARY

Add support for deploy helper in a windows environment.
##### STEPS TO REPRODUCE

```yaml

- name: Deploy me
  hosts: all
  vars:
    release_dir: c:\ansible\releases
  tasks:
    - name: make releases folder
      win_file:
        state: directory
        path: "{{ release_dir }}"

    - name: Init Deploy Helper
      deploy_helper:
        path: "{{ release_dir }}"
        state: present
    - debug:
        msg: "{{ deploy_helper }}"

    - name: "Deploy"
      file:
        state: touch
        path: "{{ deploy_helper.new_release_path }}\\supersecretwebapp"

    - name: Add unfinished deploy file
      win_file:
        state: touch
        path: "{{ deploy_helper.new_release_path }}\\{{ deploy_helper.unfinished_filename }}"

    - name: do the deploy
      win_command: "echo hello"

    - name: Clean up release
      deploy_helper:
        path: "{{ release_dir }}"
        release: "{{ deploy_helper.new_release }}"
        state: finalize


```

##### ACTUAL RESULTS

```

```
