### ISSUE TITLE
Ansible 2.4.4.0 : loop_control label keep repeating the first item

### ISSUE THREAD

**Issue by Daryes** [ansible/ansible#38780]
Didn't saw this issue while searching

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
loop_control

##### ANSIBLE VERSION

```
ansible 2.4.4.0
  config file = /server/ansible/conf/ansible.cfg
  configured module search path = [u'/server/ansible/conf/home/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /server/ansible/ansible/lib/python2.7/site-packages/ansible-2.4.4.0-py2.7.egg/ansible
  executable location = /server/ansible/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Ubuntu 16.04 Kernel 4.4.0-21-generic x86_64

##### SUMMARY

With Ansible 2.4.4, the loop_control statement doesn't work properly and will always repeat the first item at each iteration.

##### STEPS TO REPRODUCE

```yaml
- name: loop control bug
  hosts: localhost

  tasks:
    - name: basic structure
      debug:
        msg: "{{ item }}"
      with_items:
        - test1
        - test2
        - test3
      loop_control:
        label: "loop control ouput : {{ item }}"

    - name: complex structure
      debug:
        msg: "{{ item.name }} - {{ item.arg }}"
      with_items:
        - { name: test1, arg: arg1 }
        - { name: test2, arg: arg2 }
        - { name: test3, arg: arg3 }
      loop_control:
        label: "loop control ouput : {{ item.name }} | {{ item.arg }}"
```

The playbook use both msg and loop_control, allowing each entry to be printed 2 times on the screen, one for msg and one for loop_control

##### EXPECTED RESULTS

This is the result on Ansible v2.4.2 (using a symlink to keep multiples versions, can be swapped at will ) :
```
PLAY [loop control bug] **************************************************************************************************************************************************************

TASK [basic structure] **********************************************************************************************************************************************************
ok: [localhost] => (item=loop control ouput : test1) => {
    "changed": false,
    "item": "test1",
    "msg": "test1"
}
ok: [localhost] => (item=loop control ouput : test2) => {
    "changed": false,
    "item": "test2",
    "msg": "test2"
}
ok: [localhost] => (item=loop control ouput : test3) => {
    "changed": false,
    "item": "test3",
    "msg": "test3"
}

TASK [complex structure] ********************************************************************************************************************************************************
ok: [localhost] => (item=loop control ouput : test1 | arg1) => {
    "changed": false,
    "item": {
        "arg": "arg1",
        "name": "test1"
    },
    "msg": "test1 - arg1"
}
ok: [localhost] => (item=loop control ouput : test2 | arg2) => {
    "changed": false,
    "item": {
        "arg": "arg2",
        "name": "test2"
    },
    "msg": "test2 - arg2"
}
ok: [localhost] => (item=loop control ouput : test3 | arg3) => {
    "changed": false,
    "item": {
        "arg": "arg3",
        "name": "test3"
    },
    "msg": "test3 - arg3"
}

PLAY RECAP **********************************************************************************************************************************************************************
localhost                 : ok=2    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

This is the result on Ansible v2.4.4. 
Note the "loop control ouput" message doesn't change at all when looping on each element.

```
PLAY [loop control bug] **************************************************************************************************************************************************************

TASK [basic structure] **********************************************************************************************************************************************************
ok: [localhost] => (item=loop control ouput : test1) => {
    "msg": "test1"
}
ok: [localhost] => (item=loop control ouput : test1) => {
    "msg": "test2"
}
ok: [localhost] => (item=loop control ouput : test1) => {
    "msg": "test3"
}

TASK [complex structure] ********************************************************************************************************************************************************
ok: [localhost] => (item=loop control ouput : test1 | arg1) => {
    "msg": "test1 - arg1"
}
ok: [localhost] => (item=loop control ouput : test1 | arg1) => {
    "msg": "test2 - arg2"
}
ok: [localhost] => (item=loop control ouput : test1 | arg1) => {
    "msg": "test3 - arg3"
}

PLAY RECAP **********************************************************************************************************************************************************************
localhost                 : ok=2    changed=0    unreachable=0    failed=0
```

Preparing the test case also shown a discrepancy with the debug: msg module between the 2 versions. Didn't check if this was expected or not.

This aside, it's not extremely critical as only the printed output is false, while the loop behind use the correct value, but it can be very disturbing when checking the logs of previous executions.
