### ISSUE TITLE
Pip module with empty names list

### ISSUE THREAD

**Issue by kbiernat** [ansible/ansible#38785]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pip

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/kbiernat/X/ansible/ansible.cfg
  configured module search path = ['/home/kbiernat/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.3 (default, Oct  3 2017, 21:45:48) [GCC 7.2.0]
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

This isn't purely Ansible problem, but I think handling of this is purely Ansible side.
After recent release of pip10, it's behaviour changed when list of packages is not provided.
Throws an error with empty list.

##### STEPS TO REPRODUCE

```yaml
  - name: Install extra requirements bypassing project requirements
    pip:
      name: '{{ pip_requirements|default([]) }}'
```

The problem emerges when trying to do normal `pip install`.
It used to exit 0 with warning. Now it exits 1 with error.
I'm guessing pip command shouldn't even be invoked when requirements is None and name is None, or empty.

##### EXPECTED RESULTS

Playbook passes, with `ok` status, as nothing should change with empty package list.

##### ACTUAL RESULTS

```
TASK [watchdogpolska.django.deploy : Install extra requirements bypassing project requirements] **********************************
Saturday 14 April 2018  19:24:00 +0200 (0:02:13.537)       0:02:41.144 ******** 
fatal: [X]: FAILED! => {"changed": false, "cmd": "/home/Y/env/bin/pip install", "msg": "\n:stderr: ERROR: You must give at least one requirement to install (see \"pip help install\")\n"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/language/pip.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/language/pip.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lujeni @mattupstate @robinro
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by robinro** [comment]
@kbiernat Thanks for this bug report.
I opened a PR with a fix: #38789. Please try whether this works for you.

As a best practice I would recommend to not run the module at all, if you can determine this is not necessary, so instead of your example above use
```
  - name: Install extra requirements bypassing project requirements
    pip:
      name: '{{ pip_requirements }}'
    when: pip_requirements is defined
```
