### ISSUE TITLE
azure_rm_resourcegroup idempotency broke when specifying location

### ISSUE THREAD

**Issue by tijmenvandenbrink** [ansible/ansible#38787]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_resourcegroup

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/tijmen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

`
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/home/tijmen/ansible/roles']
`
##### OS / ENVIRONMENT

`
Ansible control node: "16.04.4 LTS (Xenial Xerus)"
Trying to create/update resource_group in Azure
`
##### SUMMARY

When running the below task it will create the resource group. However, when you run it again it will fail because the location will now be "westeurope". 

```yaml
- name: Create a resource group
  azure_rm_resourcegroup:
    name: SomeResourceGroup
    location: "West Europe"
    state: present
```
Failure message:

```
TASK [azure-vm : Create a resource group] ***********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Resource group 'SomeResourceGroup' already exists in location 'westeurope' and cannot be moved."}
```

##### STEPS TO REPRODUCE

```yaml
- name: Create a resource group
  azure_rm_resourcegroup:
    name: SomeResourceGroup
    location: "West Europe"
    state: present
```

##### EXPECTED RESULTS

I'd expect that if "West Europe" is a valid value for creating a resource group in West Europe idempotence will not break. 

##### ACTUAL RESULTS

The playbook fails

```
TASK [azure-vm : Create a resource group] ***********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Resource group 'SomeResourceGroup' already exists in location 'westeurope' and cannot be moved."}
```
