### ISSUE TITLE
become causes syntax error with failed_when

### ISSUE THREAD

**Issue by strarsis** [ansible/ansible#38795]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
command

##### ANSIBLE VERSION
```
ansible 2.4.3.0
config file = [...]/trellis/ansible.cfg
configured module search path = [u'/home/build/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
executable location = /usr/local/bin/ansible
python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
````
ANSIBLE_FORCE_COLOR([...]/trellis/ansible.cfg) = True
ANSIBLE_NOCOWS([...]/trellis/ansible.cfg) = True
ANSIBLE_PIPELINING([...]/trellis/ansible.cfg) = True
ANSIBLE_SSH_ARGS([...]/trellis/ansible.cfg) = -o RemoteForward="localhost:5454 localhost:5454" -o ForwardAgent=yes -o ExitOnForwardFailure=True -o ControlMaster=auto -o ControlPersist=30
ANSIBLE_SSH_RETRIES([...]/trellis/ansible.cfg) = 1
DEFAULT_CALLBACK_PLUGIN_PATH([...]/trellis/ansible.cfg) = [u'/home/build/.ansible/plugins/callback', u'/usr/share/ansible/plugins/callback', u'[...]/trellis/lib/trellis/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH([...]/trellis/ansible.cfg) = [u'/home/build/.ansible/plugins/filter', u'/usr/share/ansible/plugins/filter', u'[...]/trellis/lib/trellis/plugins/filter']
DEFAULT_FORCE_HANDLERS([...]/trellis/ansible.cfg) = True
DEFAULT_HOST_LIST([...]/trellis/ansible.cfg) = [u'[...]/trellis/hosts']
DEFAULT_ROLES_PATH([...]/trellis/ansible.cfg) = [u'[...]/trellis/vendor/roles']
DEFAULT_STDOUT_CALLBACK([...]/trellis/ansible.cfg) = output
DEFAULT_VARS_PLUGIN_PATH([...]/trellis/ansible.cfg) = [u'/home/build/.ansible/plugins/vars', u'/usr/share/ansible/plugins/vars', u'[...]/trellis/lib/trellis/plugins/vars']
````

##### OS / ENVIRONMENT
WSL (Bash on Windows)

##### SUMMARY
Adding `become: yes` to command task results in syntax error.

##### STEPS TO REPRODUCE
```yaml
 - name: Mount directory from client
   command: mount -t cifs //localhost/share-application /share/application -o port=5454,username=build,password=test
   register: command_result
   failed_when: 
    - "'mountpoint is not empty' not in command_result.stderr"
    - "command_result.rc != 0"
    # skip, when already mounted (non-empty mount point)
   become: yes
```

##### EXPECTED RESULTS
Command is run as root, result is correctly evaluated.

##### ACTUAL RESULTS
````
---------------------------------------------------
The conditional check ''mountpoint is not empty' not in
command_result.stderr' failed. The error was: error while evaluating
conditional ('mountpoint is not empty' not in command_result.stderr): Unable
to look up a name or access an attribute in template string ({% if
'mountpoint is not empty' not in command_result.stderr %} True {% else %}
False {% endif %}).
Make sure your variable name does not contain invalid characters like '-':
argument of type 'StrictUndefined' is not iterable
````
