### ISSUE TITLE
vsan datastore is getting partitioned, multiple vsandatastores getting created for every ESXI hosts

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#38799]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
vmware_vsan_cluster
``` 

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### SUMMARY
```
  i want to configure VSAN clustering on ESXI host which is part of vcenter
  when i use creds of vcenter username/password and ip address of ESXI host
  and run my playbook i get error as Unable to log on to vCenter or ESXi API at ...
 Cannot complete login due to an incorrect user name or password.
```

##### STEPS TO REPRODUCE

```
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
    - name: Configure VSAN on first host
      vmware_vsan_cluster:
          hostname: 10.243.1.44
          username: root
          password: PASSW0RD
          validate_certs: no
      register: vsan_cluster
      tags:
        - vsan_configure

  - name: Configure VSAN on second host
      vmware_vsan_cluster:
          hostname: 10.243.1.45
          username: root
          password: PASSW0RD
          validate_certs: no
      register: vsan_cluster
      tags:
        - vsan_configure


```

##### ACTUAL RESULTS

```
two different vsan data stores got created.why two different data stores got created.After executing first task, why second hots esxi disks are not added as part of same datastore. vsandatastore is partitioned
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_vsan_cluster.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_vsan_cluster.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akasurde @dav1x @jctanner
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@umrikar Thanks for reporting this issue. You are not specifying `cluster_uuid` in second task which will identify vsan cluster id (This value is returned by first task). Please take a look into `vmware_vsan_cluster` example.

needs_info

**Comment by umrikar** [comment]
@Akasurde those are 2 independent task if i want to increase capacity of existing datastore. how can i retrive cluster_uuid of existing vsan cluster.

**Comment by ansibot** [comment]
cc @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by umrikar** [comment]
hi @warthog9 @Akasurde  any update on it

**Comment by Akasurde** [comment]
@umrikar You can use https://github.com/ansible/ansible/pull/40456 enhancement to get `cluster_uuid` from given host system. 

After merge, you can use playbook like -

```yaml
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  - name: Configure VSAN on first host
    vmware_vsan_cluster:
        hostname: 10.243.1.44
        username: root
        password: PASSW0RD
        validate_certs: no
    register: vsan_cluster
    tags:
      - vsan_configure

  - name: Get Cluster UUID
    vmware_host_facts:
      hostname: 10.243.1.44
      username: root
      password: PASSW0RD
      validate_certs: no
    register: host_facts

  - set_fact:
      cluster_uuid: "{{ host_facts['ansible_facts']['vsan_cluster_uuid'] }}"

  - debug:
      var: cluster_uuid

 # Add check here, if cluster_uuid is defined.

  - name: Configure VSAN on second host
    vmware_vsan_cluster:
      hostname: 10.243.1.45
      username: root
      password: PASSW0RD
      validate_certs: no
      cluster_uuid: "{{ cluster_uuid }}"    
    register: vsan_cluster
    tags:
      - vsan_configure
```

**Comment by umrikar** [comment]
@Akasurde  Thanks

**Comment by Akasurde** [comment]
@umrikar Does the patch works for you ? Let me know so that I can merge it after review.

**Comment by umrikar** [comment]
@Akasurde  one correction in above playbook
```
 - set_fact:
      cluster_uuid: "{{ host_facts['ansible_facts']['vsan_cluster_**uuid**'] }}"

and for below playbook i am getting error
  - name: Configure VSAN on second host
    vmware_vsan_cluster:
      hostname: 10.243.1.45
      username: root
      password: PASSW0RD
      validate_certs: no
      cluster_uuid: "{{ cluster_uuid }}"    
    register: vsan_cluster
    tags:
      - vsan_configure

fatal: [127.0.0.1]: FAILED! => {
    "failed": true, 
    "msg": "The task includes an option with an undefined variable. The error was: 'cluster_uuid' is undefined\n\nThe error appears to have been in '/home/lenovo/test.yaml': line 6, column 6, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n  tasks:\n   - name: Configure VSAN on second host\n     ^ here\n"
}
```

**Comment by Akasurde** [comment]
@umrikar Could you please paste whole playbook ?

**Comment by Akasurde** [comment]
ping me on #ansible-vmware on irc.freenode.net

**Comment by Akasurde** [comment]
@umrikar Could you please verify if this works for you ? needs_info

**Comment by umrikar** [comment]
@Akasurde Yes its working.

**Comment by umrikar** [comment]
@Akasurde 

Used beow playbook to create vsan cluster
```
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  - name: Configure VSAN on first host
    vmware_vsan_cluster:
        hostname: 10.243.1.44
        username: root
        password: PASSW0RD
        validate_certs: no
    register: vsan_cluster
    tags:
      - vsan_configure
```
Used below playbook to add new ESXI host disks to existing vsan cluster
```
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
  - name: Get Cluster UUID
    vmware_host_facts:
      hostname: 10.243.1.44
      username: root
      password: PASSW0RD
      validate_certs: no
    register: host_facts

  - set_fact:
      cluster_uuid: "{{ host_facts['ansible_facts']['vsan_cluster_uuid'] }}"

  - debug:
      var: cluster_uuid

  - name: Configure VSAN on second host
     vmware_vsan_cluster:
        hostname: 10.243.1.45
        username: root
        password: PASSW0RD
        validate_certs: no
        cluster_uuid: "{{ cluster_uuid }}"    
     register: vsan_cluster
     tags:
        - vsan_configure
```
