### ISSUE TITLE
lxd_container: Manage devices separately

### ISSUE THREAD

**Issue by yurikhan** [ansible/ansible#38807]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
lxd_container

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/khan/.ansible.cfg
  configured module search path = [redacted/not relevant]
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

(not relevant)

##### OS / ENVIRONMENT

Running on Ubuntu 16.04, controlling LXD 2.21 installed from xenial-backports

##### SUMMARY

The `lxd_container` module accepts a `devices` option. This makes it possible to mount host directories into the container:

```
- name: Mount local directory
  delegate_to: localhost
  lxd_container:
    name: '{{ inventory_hostname }}'
    devices:
      my-local-dir:
        type: disk
        path: /path/in/the/container
        source: /path/on/the/host
```

However, the dictionary that is passed as the value of `devices` replaces the `devices` subkey in the container configuration. If two roles try to mount two separate, independent directories into the same container, the last one to apply wins.

It would be nice if elements of `devices` were treated separately, with a suboption such as `state` on each to specify the desired result on that device (`present` or `absent`).

The real-world use case for this is:

* One role mounts a local directory containing Debian packages, adds that as an APT repository, and installs several packages.
* Another role mounts a local directory containing test files and runs tests.

(Copying files instead of mounting directories would be too time-consuming to run this on every compilation, hurting development productivity.)

##### STEPS TO REPRODUCE

```yaml
- name: Mount one local directory
  delegate_to: localhost
  lxd_container:
    name: '{{ inventory_hostname }}'
    devices:
      home-user-foo:
        state: present
        type: disk
        path: /home/user/foo
        source: /home/user/foo

- name: Mount another local directory
  delegate_to: localhost
  lxd_container:
    name: '{{ inventory_hostname }}'
    devices:
      home-user-bar:
        state: present
        type: disk
        path: /home/user/bar
        source: /home/user/bar

- name: Unmount the first directory
  delegate_to: localhost
  lxd_container:
    name: '{{ inventory_hostname }}'
    devices:
      home-user-foo:
        state: absent
```

(The exact syntax is up for discussion. The one presented here has the advantage of being very backward-compatible, but raises a possibility of name conflict in case LXD later defines a `state` subkey in devices. Alternatively, LXD-specific keys could be moved down into a subdictionary, avoiding future conflicts but requiring users to adapt their playbooks after the first release implementing this.)

##### EXPECTED RESULTS

* After the first play, /home/user/foo in the container maps to /home/user/foo on the host.
* After the second play, /home/user/foo in the container still maps to /home/user/foo on the host; additionally, /home/user/bar in the container maps to /home/user/bar on the host.
* After the third play, only /home/user/bar in the container maps to /home/user/bar on the host.

##### ACTUAL RESULTS

Currently, the `state` subkey would be passed to LXD which would probably  complain. Removing this subkey from each play would yield the following results:

* After the first play, /home/user/foo in the container maps to /home/user/foo on the host.
* After the second play, /home/user/foo is no longer mounted. /home/user/bar in the container maps to /home/user/bar on the host.
