### ISSUE TITLE
ansible-vault: inline yaml encrypt / decrypt 

### ISSUE THREAD

**Issue by sylr** [ansible/ansible#38808]
##### ISSUE TYPE
Feature Idea

##### COMPONENT NAME
ansible vault

##### SUMMARY

Create new encrypt_yaml/decrypt_yaml function for vault (or ideally overload encrypt/decrypt)  which will encrypt/decrypt all keys that have a `!vault` tag.

##### EXPECTED RESULTS

prod.yml:
```yaml
ip: 1.0.0.0
ssh_user: robert
ssh_pass: !vault |
  ThisIsRobertPassword
mysql:
  port: 3306
  password: !vault |
    MysqlPassword45
```
encrypt:
```bash
shell$ export ANSIBLE_VAULT_PASSWORD_FILE=~/.ansible_vault_pass
shell$ ansible-vault encrypt_yaml prod.yml
```
prod.yml:
```
ip: 1.0.0.0
ssh_user: robert
ssh_pass: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  333137323130633733313030373231663536323333656333663635633636
  333137323130633733313030373231663536323333656333663635633636
  333137323130633733313030373231663536323333656333663635633636
mysql:
  port: 3306
  password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    333137323130633733313030373231663536323333656333663635633636
    333137323130633733313030373231663536323333656333663635633636
    333137323130633733313030373231663536323333656333663635633636
```
decrypt:
```bash
shell$ export ANSIBLE_VAULT_PASSWORD_FILE=~/.ansible_vault_pass
shell$ ansible-vault decrypt_yaml prod.yml
```
prod.yml:
```yaml
ip: 1.0.0.0
ssh_user: robert
ssh_pass: !vault |
  ThisIsRobertPassword
mysql:
  port: 3306
  password: !vault |
    MysqlPassword45
```
