### ISSUE TITLE
vmware_guest is not setting "customvalues" against vSphere 6.5 on Ansible 2.5

### ISSUE THREAD

**Issue by jervislam0911** [ansible/ansible#38810]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/jervis/.ansible.cfg
  configured module search path = [u'/etc/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### OS / ENVIRONMENT
Running on Red Hat Enterprise Linux Server 7.4
Running against vSphere 6.5 and ESXi 6.5

##### SUMMARY
Tasks run successfully and debug with no error. However, "**customvalues**" are not added even vSphere responds with: " Reconfigure virtual machine - Completed " 

##### STEPS TO REPRODUCE

```yaml
---
- hosts: "{{ remote_host }}"
  gather_facts: False
  tasks:
    - name: add attribute to vm
      vmware_guest:
        hostname: "{{ hostname }}"
        username: "{{ ansible_user }}"
        password: "{{ ansible_password }}"
        name: "{{ vm_name }}"
        customvalues:
          - key: "Windows"
            value: "Testing"
        annotation: "testing"
        validate_certs: False
      delegate_to: localhost
```

##### EXPECTED RESULTS
Should have set the attributes as "Windowns": "Testing"

##### ACTUAL RESULTS

Tasks completed normally with no error, annotation added sccessfully, but attributes did not get set.

```
changed: [VSP-TA81 -> localhost] => {
    "changed": true,
    "instance": {
        "annotation": "testing",
        "current_snapshot": null,
        "customvalues": {
            "Last Backup": "4/14/2018 19:21:37 PM"
        },
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "10279",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "vsandts"
        ],
        "hw_esxi_host": "xxx-hyp1",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": [
                "f242::701a5315:1321:411a",
                "192.168.3.2"
            ],
            "label": "Network adapter 1",
            "macaddress": "10:52:52:c3:a1:b3",
            "macaddress_dash": "10-52-25-c3-e1-16",
            "summary": "DVSwitch: 51 23 na 19 18 11 51 4d-71 1h 30 67 4b 46 44 1c
        },
        "hw_folder": "/113421/vm",
        "hw_guest_full_name": "Microsoft Windows Server 2012 (64-bit)",
        "hw_guest_ha_state": true,
        "hw_guest_id": "windows10Server64Guest",
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 4096,
        "hw_name": "VSP-TA81",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 4,
        "hw_product_uuid": "424115-9a87-cf12-73c1-h5124987g1h3",
        "ipv4": "192.168.3.2",
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": "testing",
            "cdrom": {},
            "cluster": null,
            "customization": {},
            "customvalues": [
                {
                    "key": "Windows",
                    "value": "Testing"
                }
            ],
            "disk": [],
            "esxi_hostname": null,
            "folder": null,
            "force": true,
            "guest_id": null,
            "hardware": {},
            "is_template": false,
            "linked_clone": false,
            "name": "VSP-TA81",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "template": null,
            "username": "xxxx",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}
```
