### ISSUE TITLE
wait_for module can't find regex in a file that is being written non-stop

### ISSUE THREAD

**Issue by ArthurSens** [ansible/ansible#38826]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

wait_for

##### ANSIBLE VERSION

```
-bash-4.2$ ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/rundeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

-bash-4.2$ ansible-config dump --only-changed
-bash-4.2$

###### OS running ansible and also the one that is being managed
```
-bash-4.2$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

##### SUMMARY

wait_for module can't find regex in a file that is being written non-stop

##### STEPS TO REPRODUCE

When starting a jboss4, it writes a certain line when the startup is completed, here is an example:

`2018-04-16 11:31:09,462 INFO  [org.jboss.system.server.Server] JBoss (MX MicroKernel) [4.3.0.GA_CP10 (build: SVNTag=JBPAPP_4_3_0_GA_CP10 date=201209180908)] Started in 4m:31s:388ms`

I've tried copying this line in a separated file and then my ansible script worked just as expected for that new file.
So I imagine that Ansible gets lost somehow when the file that I search the regex is being written non-stop

```yaml
- hosts: myserver
  tasks:
    - name: start jboss
       command: /etc/init.d/myJboss4 start

    - name: Jboss is starting... wait a sec... go get some coffee
      wait_for:
        path: /path/to/log/server.log
        search_regex: .*SVNTag.*
        timeout: 3600
        msg: "JBOSS didn't start properly"

    - name: looking for deployment failures
      command: grep "DeploymentException" /path/to/log/server.log
      ignore_errors: yes
      register: deploymentException

    - debug:
        msg: "We found Deployment failures in the log file, you should have a better look at it at: mylogserver"
        when: deploymentException.rc == 0

    - debug:
        msg: "JBoss started"
```

##### EXPECTED RESULTS

When my jboss writes the SVNTag in the log file, go to the next step(look for DeploymentExceptions)

##### ACTUAL RESULTS

Couldn't find regex and fails with timeout

Even though when I try:
`grep ".*SVNTag.*" /path/to/log/server.log` I actually get the result I was expecting

```
The full traceback is:
  File "/tmp/ansible_O00RY0/ansible_module_wait_for.py", line 517, in main
    os.stat(path)

fatal: [myserver]: FAILED! => {
    "changed": false,
    "elapsed": 3600,
    "invocation": {
        "module_args": {
            "active_connection_states": [
                "ESTABLISHED",
                "FIN_WAIT1",
                "FIN_WAIT2",
                "SYN_RECV",
                "SYN_SENT",
                "TIME_WAIT"
            ],
            "connect_timeout": 5,
            "delay": 0,
            "exclude_hosts": null,
            "host": "myserver",
            "msg": "JBOSS didn't start properly",
            "path": "/path/to/log/server.log",
            "port": null,
            "search_regex": ".*SVNTag.*",
            "sleep": 1,
            "state": "started",
            "timeout": 3600
        }
    },
    "msg": "JBOSS didn't start properly"
}
        to retry, use: --limit @/tmp/update_artifact.retry

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/wait_for.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/wait_for.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @AnderEnder @gregswift @jarv @jhoekx
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ArthurSens** [comment]
Some new tests for better understading


```yaml
$ cat wait_for.yml
- hosts: myserver
  tasks:
    - name: looking for SVNTag
      command: grep "^.*SVNTag" /path/to/log/server.log
      ignore_errors: yes
      register: svnTag

    - debug:
        msg: "We found SVNTag"
      when: svnTag.rc == 0

    - name: Jboss is starting... wait a sec... go get some coffee
      wait_for:
        path: /path/to/log/server.log
        search_regex: ^.*SVNTag
        timeout: 3600
        msg: "JBOSS didn't start properly"

```

Result:

```
-bash-4.2$ ansible-playbook wait_for.yml -i myserver, -vv
ansible-playbook 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/rundeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file

PLAYBOOK: wait_for.yml ******************************************************************************************************************************************************************************
1 plays in wait_for.yml

PLAY [myserver] *****************************************************************************************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************************************************************************************************
task path: /var/lib/rundeck/wait_for.yml:1
ok: [myserver]
META: ran handlers

TASK [looking for SVNTag] ***************************************************************************************************************************************************************************
task path: /var/lib/rundeck/wait_for.yml:3
changed: [myserver] => {"changed": true, "cmd": ["grep", "^.*SVNTag", "path/to/log/server.log"], "delta": "0:00:00.014468", "end": "2018-04-23 12:29:01.628826", "rc": 0, "start": "2018-04-23 12:29:01.614358", "stderr": "", "stderr_lines": [], "stdout": "2018-04-23 12:04:02,294 INFO  [org.jboss.system.server.Server] JBoss (MX MicroKernel) [4.3.0.GA_CP10 (build: SVNTag=JBPAPP_4_3_0_GA_CP10 date=201209180908)] Started in 4m:9s:459ms", "stdout_lines": ["2018-04-23 12:04:02,294 INFO  [org.jboss.system.server.Server] JBoss (MX MicroKernel) [4.3.0.GA_CP10 (build: SVNTag=JBPAPP_4_3_0_GA_CP10 date=201209180908)] Started in 4m:9s:459ms"]}

TASK [debug] ****************************************************************************************************************************************************************************************
task path: /var/lib/rundeck/wait_for.yml:8
ok: [myserver] => {
    "msg": "We found SVNTag"
}

TASK [Jboss is starting... wait a sec... go get some coffee] ****************************************************************************************************************************************
task path: /var/lib/rundeck/wait_for.yml:12
fatal: [myserver]: FAILED! => {"changed": false, "elapsed": 3600, "msg": "JBOSS didn't start properly"}
        to retry, use: --limit @/var/lib/rundeck/wait_for.retry

PLAY RECAP ******************************************************************************************************************************************************************************************
myserver           : ok=3    changed=1    unreachable=0    failed=1

```
