### ISSUE TITLE
File module recurse isn't idempotent

### ISSUE THREAD

**Issue by sdot257** [ansible/ansible#38839]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
- File

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

This code will show that the task "changed" even though nothing has changed. If I remove the `recurse` option, it runs fine and is idempotent.

```
consul_install_directory = /etc/consul.d

- name: Create Consul directory structure
  file:
    path: "{{ consul_install_directory }}"
    state: directory
    recurse: true
    mode: 0775
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
```
