### ISSUE TITLE
onyx_bgp - Support purge option to not delete existing bgp neighbors

### ISSUE THREAD

**Issue by eddies1985** [ansible/ansible#38837]
##### ISSUE TYPE

 - Feature Idea
 

##### COMPONENT NAME

onyx_bgp 
Adding neighbor(s) is a useful common task, adding a purge flag in the module and only if true will remove other neighbors, 
##### ANSIBLE VERSION

```
ansible 2.6.0 (devel db80504839) last updated 2018/04/12 16:53:04 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/ansible/ansible/lib/ansible
  executable location = /root/ansible/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION

HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 300

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

add the purge flag for the onyx_bgp module

```yaml
---
- name: bgp neighbors
  onyx_bgp:
     as_number: 65000
     router_id: 192.168.168.168
     neighbors:
        - remote_as: 65002
          neighbor: 192.168.255.3
     purge: no
     state: present
     networks:
       - 192.168.168.168/32
       -  192.168.100.0/24
```

##### EXPECTED RESULTS

when purge is set to no , the task won't delete the existing bgp neighbors on the Onyx device
##### ACTUAL RESULTS

```

```
