### ISSUE TITLE
azure_rm_managed_disk cannot update existing os disk

### ISSUE THREAD

**Issue by PiotrMejer** [ansible/ansible#38883]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

azure_rm_managed_disk

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Ubuntu 16.04.4

##### SUMMARY

We have been using 'azure_rm_virtualmachine' to create vm. After stopping the machine we would like to increase created os disk size using azure_rm_managed_disk, but updating task is failing:
```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating the managed disk: Azure Error: PropertyChangeNotAllowed\nMessage: Changing property 'creationData' is not allowed.\nTarget: creationData"}
```
##### STEPS TO REPRODUCE

1. Create vm instance with azure_rm_virtualmachine
2. Stop the instance (creating the machine with azure_rm_virtualmachine and 'started' parameter set to 'no' doesn't work.)
3. Update created os disk with azure_rm_managed_disk

```yaml

- name: "Create VM"
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    virtual_network_name: "{{ virtual_network_name }}"
    network_interface_names: "{{ network_interface_name }}"
    storage_account_name: "{{ storage_account_name }}"
    name: "{{vm_name}}"
    vm_size: "{{ vm_size_sku }}"
    image:
      offer: "{{ os_image_offer }}"
      sku: "{{ os_image_sku }}"
      publisher: "{{ os_image_publisher }}"
      version: "{{ os_image_version }}"
    managed_disk_type: Standard_LRS
    started: no

- name: "Power off the machine"
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    name: "{{vm_name}}"
    allocated: no

- name: "Increase disk size"
  azure_rm_managed_disk:
    name: "{{ vm_name }}"
    resource_group: "{{ resource_group_name }}"
    disk_size_gb: "{{ azure_disk_size }}"
    managed_by: "{{ vm_name }}"

```

##### EXPECTED RESULTS

We expect that the task will update existing disk.

##### ACTUAL RESULTS

```
"msg": "Error creating the managed disk: Azure Error: PropertyChangeNotAllowed\nMessage: Changing property 'creationData' is not allowed.\nTarget: creationData"
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_managed_disk.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_managed_disk.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @brusMX
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@PiotrMejer Perform the following YML file , did not meet you describe problem, when removing azure_rm_managed_disk location parameters, it will be prompted similar mistake as you report. could you add location parameter in you YML file , retest , Look to whether can have this problem . Thanks !
``` e.g.
---
# Resource_group and image has create before excute
- name: For Azure learn
  hosts: localhost
  connection: local
  vars:
    resource_group: myRG03
    location: westeurope
    storageaccount: sssaaa04
    virtualnetwork: virtualnetwork04
    subnet: subnet04
    public_ip: public_ip04
    security_ssh: security_ssh04
    test_nic: test_nic04
    vm_name: myVM04
  tasks:
  - name: create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storageaccount }}"
      account_type: Standard_LRS

  - name: create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtualnetwork }}"
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtualnetwork }}"

  - name: create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip }}"
  
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_ssh }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
  
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ test_nic }}"
      virtual_network: "{{ virtualnetwork }}"
      subnet: "{{ subnet }}"
      public_ip_name: "{{ public_ip}}"
      security_group: "{{ security_ssh }}"

  - name: create virtual machine
    azure_rm_virtualmachine: 
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      state: present
      vm_size: Standard_A0
      managed_disk_type: Standard_LRS
      admin_username: azureuser
      admin_password: Password@0329
      virtual_network_name: "{{ virtualnetwork }}"
      network_interface_names: "{{ test_nic }}"
      storage_account_name: "{{ storageaccount }}"
      image: 
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS 
        version: latest 
      started: no

  - name: "Power off the machine"
    azure_rm_virtualmachine:
     resource_group:  "{{ resource_group }}"
     name: "{{vm_name}}"
     allocated: no

  - name: "Increase disk size"
    azure_rm_managed_disk:
      name: mymanagedisk
      location: westeurope
      resource_group: "{{ resource_group }}"
      disk_size_gb: 4
      managed_by: "{{ vm_name }}"

**Comment by PiotrMejer** [comment]
@Fred-sun  thanks for Your reply. I suppose that the attached YML creates vm and os disk with the same name ("{{ vm_name }}"), last task do not update size of existing (created with vm) disk (named {{vm_name}}) but creates new disk (with name = mymanagedisk).

**Comment by Fred-sun** [comment]
@PiotrMejer Thanks for Your verified, You are right, But when use same name "{{vm_name}}", it will meet error, error message as bellow:
``` e.g.
K [create virtual machine] **************************************************
changed: [127.0.0.1]

TASK [Power off the machine] ***************************************************
changed: [127.0.0.1]

TASK [Increase disk size] ******************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error creating the managed disk: Azure Error: BadRequest\nMessage: Disks or snapshot cannot be resized down."}
	to retry, use: --limit @/home/fred/task/azure_rm_virtualmachine_NSG01.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=10   changed=3    unreachable=0    failed=1

**Comment by Fred-sun** [comment]
@PiotrMejer  Yes , I meet same error as your describe.  if disk_disk_size value greater than or equal the source's size, will meet the same error. Thanks !

**Comment by unfii** [comment]
Also reproduce issue, so how we could increase os disk size? Any idea?

**Comment by unfii** [comment]
Any solution for this issue?

**Comment by Fred-sun** [comment]
@unfii Thank you for your still tracking this, I think we can't increase Create OS disk by using azure_rm_managed_disk. But it can expand disk by mount method, YML as below, I will confirm with development personnel Thanks!
@zikalino  Could you help confirm azure_rm_managed_disk moudule feature and how to fix this issue ? Thanks a lot!

Expand VM disk by mount method
``` e.g.
  - name: "Mount the managed disk to VM"
    azure_rm_managed_disk:
      name: mymnageddisk
      location: westeurope
      resource_group: "{{ resource_group }}"
      disk_size_gb: 32
      managed_by: "{{ vm_name }}"

**Comment by unfii** [comment]
@Fred-sun Yep, this disk will be attach only to special vm, but how to automate mount disk inside vm?

**Comment by Fred-sun** [comment]
@unfii I have try if mount disk to the VM ,it will not unmount by reboot or power off the VM. So we can use this method to expand disk. anyway, I cannot modify /etc/fstab  method to auto mount disk like Linux, But I will think other method , Thanks!

@zikalino  Could you help check this , How to automate mount disk inside VM? Thanks!

**Comment by spmp** [comment]
Did anyone find a method that works?
You can specify the os disk size in an RM template so I assume you can do it via the Python API too.

Ideally we should be able to specify `os_disk_size` in `azure_rm_virtualmachine`

**Comment by Fred-sun** [comment]
Hi @spmp , Do you want create  data disk when create VM , I am not sure it meet your means. just like:
``` e.g.
  - name: create virtual machine
    azure_rm_virtualmachine: 
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      state: present
      vm_size: Standard_A0
      managed_disk_type: Standard_LRS
      admin_username: azureuser
      admin_password: Password@0329
      virtual_network_name: "{{ virtualnetwork }}"
      network_interface_names: "{{ test_nic }}"
      storage_account_name: "{{ storageaccount }}"
      image: 
        offer: UbuntuServer
        publisher: Canonical
        sku: 16.04-LTS 
        version: latest 
      started: no
      data_disks:
      - lun: 0
        disk_size_gb: 128
        managed_disk_type: Standard_LRS

**Comment by spmp** [comment]
@Fred-sun I do create data disks as well, but I need a large os disk.

**Comment by Fred-sun** [comment]
Hi @spmp , Let me summary this issue, I have confirm with our developer member, Cannot increase created OS disk size,  but it will be fixed on later Ansible version, Now we can use mount and create data disks method to expand the VM disk size, when this question be fixed,  You can by latest Ansible version to try. Thanks a lot!

**Comment by spmp** [comment]
I really have to have this unfortunately. 
Rather than rewriting the module in its most basic cut down form, is it possible to be connected with the developer of `azure_rm_virtualmachine` to help me add this functionality? It can be a brutal hack, and I would keep it in the local `library` directory of the project.

Cheers

**Comment by Fred-sun** [comment]
I feel very sorry to you, Change a parameter relation more than one module, it need develop and test these modules, not a easy job, So it need time to finish this job, Thanks a lot!

**Comment by spmp** [comment]
I have resolved this problem in my branch:
https://github.com/spmp/ansible/tree/feature/os_disk_size

I am unlikely to have time to create tests etc. at this stage, but will open a PR soon pending comments.

**Comment by ghost** [comment]
workaround: use Azure CLI
```
- name: expand OS disk
  shell: az disk update -g {{ resource_group }} -n {{ item }} --size-gb {{ dev_os_disk_size }}
  with_sequence: start=1 end="{{ vm_count }}" format="{{ vm_name }}-%02u"
```

**Comment by spmp** [comment]
I modified the module, was a relativity simple fix. I believe I have
referenced my branch in the comments. I can do a pr if someone is willing
to write the tests. I am too busy ATM.

On 1/06/2018 7:45 PM, "royzeng-ericsson" <notifications@github.com> wrote:

workaround: use Azure CLI

- name: expand OS disk
  shell: az disk update -g {{ resource_group }} -n {{ item }}
--size-gb {{ dev_os_disk_size }}
  with_sequence: start=1 end="{{ vm_count }}" format="{{ vm_name }}-%02u"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ansible/ansible/issues/38883#issuecomment-393795271>,
or mute the thread

**Comment by zikalino** [comment]
@spmp please create pr, i will take care of merging it

**Comment by spmp** [comment]
@zikalino you have push rights to my repo, thank you for volunteering to see this PR merged. It needs documentation and tests at a minimum. I hope that is all.

**Comment by yuwzho** [comment]
For the managed_disk update, here need to send the `create_option`, otherwise the `managed_disk` will  think you want to change this cannot-be-updated field.

Besides the `create_option`, the `storage_account` is also needed. All these parameters can be get from facts module. Here is my example.

Before you try the playbook, you need to install  the latest bit by:

```bash
sudo pip install git+https://github.com/ansible/ansible.git@devel
```

```yml
- name: "Create VM"
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    virtual_network_name: "{{ virtual_network_name }}"
    network_interface_names: "{{ network_interface_name }}"
    storage_account_name: "{{ storage_account_name }}"
    name: "{{vm_name}}"
    vm_size: "{{ vm_size_sku }}"
    image:
      offer: "{{ os_image_offer }}"
      sku: "{{ os_image_sku }}"
      publisher: "{{ os_image_publisher }}"
      version: "{{ os_image_version }}"
    managed_disk_type: Standard_LRS
    started: no

- name: "Power off the machine"
  azure_rm_virtualmachine:
    resource_group: "{{ resource_group_name }}"
    name: "{{vm_name}}"
    allocated: no

- name: get facts
  azure_rm_managed_disk_facts:
    resource_group: "{{ resource_group_name }}"
    name: "{{ vm_name }}"
  register: facts

- set_fact:
      parameter: "{{ parameter | default({'resource_group': resource_group_name}) | combine({item.key: item.value}) }}"
  when: "{{ item.key not in ['id', 'changed'] and item.value != None }}"
  with_dict: "{{ facts.ansible_facts.azure_managed_disk[0] }}"

- set_fact:
      parameter: "{{ parameter | combine({item.key: item.value}) }}"
  with_dict:
      disk_size_gb: "{{ azure_disk_size }}" 

- name: "Increase disk size"
  azure_rm_managed_disk: "{{ parameter }}"
```
