### ISSUE TITLE
k8s_raw Changed Secret Keys From 'this_style' to 'thisStyle'

### ISSUE THREAD

**Issue by dgoodwin** [ansible/ansible#38895]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

k8s_raw

##### ANSIBLE VERSION

```
ansible 2.5.0               
  config file = /etc/ansible/ansible.cfg                 
  configured module search path = [u'/home/dgoodwin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible                                        
  executable location = /usr/bin/ansible                 
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### CONFIGURATION

ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = %(directory)s/ansible-ssh-%%C
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /home/dgoodwin/go/src/github.com/openshift/cluster-operator/ansible.log

##### OS / ENVIRONMENT

Running Ansible on Fedora 27, and playbook against localhost.

##### SUMMARY

The k8s_raw module appears to automatically flip secret data keys from this_var_format to thisVarFormat.

##### STEPS TO REPRODUCE

```yaml
 - name: create AWS credentials secret
    k8s_raw:
      state: present
      definition:
        apiVersion: v1
        kind: Secret
        metadata:
          name: aws-credentials
          namespace: openshift-cluster-operator
        type: Opaque
        data:
          aws_access_key_id: "{{ l_aws_access_key_id }}"
          aws_secret_access_key: "{{ l_aws_secret_access_key }}"
```

##### EXPECTED RESULTS

The original name of the secret data keys should be preserved.

##### ACTUAL RESULTS

Looking at the secret in Kubernetes we see the data keys were changed on us, from aws_access_key_id to awsAccessKeyId:

```

$ kubectl get secret aws-credentials -o yaml
apiVersion: v1
data:
  awsAccessKeyId: REDACTED
  awsSecretAccessKey: REDACTED
kind: Secret
metadata:
  creationTimestamp: 2018-04-17T18:02:26Z
  labels:
    app: cluster-operator
  name: aws-credentials
  namespace: openshift-cluster-operator
  resourceVersion: "46918"
  selfLink: /api/v1/namespaces/openshift-cluster-operator/secrets/aws-credentials
  uid: 7c63e78c-4269-11e8-b35b-989096de63cb
type: Opaque
```
