### ISSUE TITLE
Network Modules Running Slower at Scale After Upgrading to Ansible 2.5

### ISSUE THREAD

**Issue by harrytruman** [ansible/ansible#38892]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_config, ios_command

##### ANSIBLE VERSION
```
ansible 2.5.0
  configured module search path = [u'/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
```
# Tested without callback and strategy
DEFAULT_CALLBACK_WHITELIST(ansible/ansible.cfg) = ['timer', 'mail', 'skippy', 'profile_tasks']
DEFAULT_STRATEGY(ansible/ansible.cfg) = free
DEFAULT_TIMEOUT(ansible/ansible.cfg) = 20
PERSISTENT_CONNECT_TIMEOUT(ansible/ansible.cfg) = 90
```

##### OS / ENVIRONMENT
RHEL 7.4
3.10.0-693.11.1.el7.x86_64

##### SUMMARY
Testing indicates this is affecting all network modules for all device families. E.g., ios, ios-xr, nxos, eos, etc...

There's a significant difference in speed/performance after upgrading from 2.4.3 to 2.5. I've tested most of our roles so far, and I've verified performance is consistent across all our environments running 2.5. Disabling the free strategy and callbacks we normally run doesn't offer improvements. Processor and memory utilization gradually lowers with scale, and is consistent with the increase in run times.

Simply put, all network roles are running significantly slower in 2.5:

##### STEPS TO REPRODUCE
Example fact playbook for IOS:

```
---
- name: collect output from ios device
  ios_command:
    commands:
      - show version
      - show running-config
      - show ip interface brief | include {{ ansible_host }}
    authorize: yes
    provider: "{{ cli }}"
  register: output

# Just the Facts

- name: set version fact
  set_fact:
    version: "{{ output.stdout[0] | regex_search('Version (\\S+)', '\\1') | first }}"

- name: set model number
  set_fact:
    model_number: "{{ output.stdout[0] | regex_search('[cC]isco\\s+(\\S+).+?with .+? bytes of.+?memory', '\\1') | first | regex_search('(\\d+)') }}"

- name: set config fact
  set_fact:
    config: "{{ output.stdout[1] }}"

- name: set config_lines fact
  set_fact:
    config_lines: "{{ output.stdout_lines[1] }}"

- name: set management interface name fact
  set_fact:
    mgmt_interface_name: "{{ output.stdout[2].split()[0] }}"
```

Below are the commands/results from this fact playbook, and another example result from a password change role.
Facts: 
```ansible-playbook facts.yml -l cisco-ios[1:500] --forks 100```

Passwords:: 
```ansible-playbook password.yml -l cisco-ios[1:100] --forks 100 ```

##### EXPECTED RESULTS

Facts:
```
network_facts : collect output from ios device ------------------------- 41.10s
network_facts : set config_lines fact ---------------------------------- 33.16s
debug ------------------------------------------------------------------- 5.31s
network_facts : include cisco-ios tasks --------------------------------- 2.66s
network_facts : set config fact ----------------------------------------- 0.46s
network_facts : set version fact ---------------------------------------- 0.41s
network_facts : set model number ---------------------------------------- 0.41s
network_facts : set management interface name fact ---------------------- 0.40s
Playbook run took 0 days, 0 hours, 4 minutes, 24 seconds
```

Passwords:
```
config_localpw : Update line passwords -------------------------------- 111.60s
network_facts : collect output from ios device -------------------------- 6.12s
config_localpw : Update line passwords ---------------------------------- 0.91s
network_facts : include cisco-ios tasks --------------------------------- 0.51s
config_localpw : Update line passwords ---------------------------------- 0.50s
config_localpw : Update terminal server username doorbell --------------- 0.28s
config_localpw : debug -------------------------------------------------- 0.22s
config_localpw : Update terminal server username doorbell --------------- 0.19s
config_localpw : set_fact - Modem slot 3 -------------------------------- 0.16s
config_localpw : Update enable and username config lines ---------------- 0.16s
config_localpw : debug -------------------------------------------------- 0.13s
config_localpw : Identify if it has a modem ----------------------------- 0.13s
config_localpw : Update enable and username config lines ---------------- 0.13s
config_localpw : Update terminal server username doorbell --------------- 0.12s
config_localpw : debug -------------------------------------------------- 0.12s
config_localpw : Update terminal server username doorbell --------------- 0.11s
config_localpw : Update terminal server username doorbell --------------- 0.08s
config_localpw : Update enable and username config lines ---------------- 0.07s
config_localpw : debug -------------------------------------------------- 0.07s
config_localpw : Update line passwords ---------------------------------- 0.07s
Playbook run took 0 days, 0 hours, 3 minutes, 12 seconds
```

##### ACTUAL RESULTS
Facts:
```
network_facts : collect output from ios device ------------------------- 27.77s
network_facts : include cisco-ios tasks --------------------------------- 2.83s
debug ------------------------------------------------------------------- 0.26s
network_facts : set config fact ----------------------------------------- 0.12s
network_facts : set management interface name fact ---------------------- 0.12s
network_facts : set model number ---------------------------------------- 0.06s
network_facts : set version fact ---------------------------------------- 0.04s
network_facts : set config_lines fact ----------------------------------- 0.04s
Playbook run took 0 days, 0 hours, 26 minutes, 33 seconds
```

Passwords:
```
config_localpw : Update line passwords ---------------------------------- 40.38s
config_localpw : Update line passwords ---------------------------------- 26.52s
config_localpw : Update terminal server username doorbell --------------- 22.32s
config_localpw : Update enable and username config lines ---------------- 21.04s
config_localpw : Update terminal server username doorbell --------------- 16.96s
config_localpw : Update line passwords ---------------------------------- 16.87s
config_localpw : Update line passwords ---------------------------------- 16.86s
config_localpw : Update line passwords ---------------------------------- 16.68s
config_localpw : Update line passwords ---------------------------------- 15.75s
config_localpw : Update terminal server username doorbell --------------- 15.39s
config_localpw : Update line passwords ---------------------------------- 15.25s
config_localpw : Update line passwords ---------------------------------- 15.12s
config_localpw : Update line passwords ---------------------------------- 14.62s
config_localpw : Identify if it has a modem ----------------------------- 14.52s
config_localpw : Update terminal server username doorbell --------------- 13.94s
config_localpw : Update line passwords ---------------------------------- 13.78s
config_localpw : Update line passwords ---------------------------------- 13.47s
config_localpw : Identify if and where the modem is --------------------- 13.03s
config_localpw : Update enable and username config lines ---------------- 12.82s
config_localpw : Update line passwords ---------------------------------- 12.07s
Playbook run took 0 days, 0 hours, 17 minutes, 38 seconds
```
