### ISSUE TITLE
locale_gen fails if specified target does not exist in `/etc/locale.gen`

### ISSUE THREAD

**Issue by sudoforge** [ansible/ansible#38931]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

locale_gen

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/sbin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

I'm running Ansible in a Docker image running Arch Linux who has the following minimal`/etc/locale.gen`:

```
en_US.UTF-8 UTF-8
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Showcase ansible issue#38931
  hosts: localhost
  tasks:
    - name: Generate locales
      locale_gen:
        name: "{{ item }}"
        state: present
      with_items:
        - en_US.UTF-8
        - en_GB.UTF-8
```

Save the above as `locale_gen.yml` in your current directory. Next, run the docker image, and add the playbook to the running container:

```
$ docker run --rm --detach --tmpfs /tmp --tmpfs /run --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --cap-add SYS_ADMIN --security-opt=seccomp:unconfined --name archlinux terencewestphal/archlinux:latest
$ docker cp locale_gen.yml archlinux:/root/locale_gen.yml
$ docker exec -it archlinux zsh
$ pacman -S ansible
$ ansible-playbook /root/locale_gen.yml
``` 

If you add the additional localizations to the `locale.gen` file (`en_US.UTF-8 UTF-8` in our test's example), and re-run the playbook, the module works successfully.

##### EXPECTED RESULTS

I would expect the `locale_gen` module to ensure both items exist and are uncommented in `/etc/locale.gen`, adding them to the file if necessary, and then successfully execute the `locale-gen` binary.

##### ACTUAL RESULTS

[locale_gen__output.txt](https://github.com/ansible/ansible/files/1922723/locale_gen__output.txt)
