### ISSUE TITLE
vmware_guest: valid request fails with "Access to resource settings is restricted"

### ISSUE THREAD

**Issue by piotrplazienski** [ansible/ansible#38941]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
  config file = None
  configured module search path = [u'/home/app021/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]
```

##### CONFIGURATION

Default.

##### OS / ENVIRONMENT

Ubuntu Server 17.10
ESXi 6.0.0/vCenter Server 6.0.0

##### SUMMARY
When ESXi/vCenter is configured in particular way, valid change in vm configuration fails. 
Same change works with Ansible 2.4.x.
##### STEPS TO REPRODUCE

ESXi must allow direct access, and resource allocation must be controlled by vCenter (so it is not possible to change it on ESXi, must be changed on vCenter)
Run vmware_guest module to change vm properties other than resource allocation (cpu/mem in this case). Use ESXi address/credentials to connect, **NOT** vCenter ones. Example playbook listed below.
It also fails same way when module is called directly with ansible args:
python /usr/local/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_guest.py ansible_args.json
(Example Ansible args also pasted below)

```yaml
- hosts: localhost
  gather_facts: false
  tasks:
    - vmware_guest:
        username: root
        password: apassword
        hostname: <esxi address>
        name: "a-vm-name"
        hardware:
          memory_mb: 4096
          num_cpus: 6
        state: present
```

```
{
    "ANSIBLE_MODULE_ARGS": {
        "datacenter": "ha-datacenter",
        "hardware": {
            "memory_mb": "4096",
            "num_cpus": "4"
        },
        "hostname": "<esxi address>",
        "name": "a-vm-name",
        "password": "apassword",
        "state": "present",
        "username": "root"
    }
}
```

##### EXPECTED RESULTS

Configuration is changed properly. It works this way with Ansible 2.4
##### ACTUAL RESULTS

Fails with:

```
 "Access to resource settings on the host is restricted to the server that is managing it: '<vcenter address>'."
```
This is caused by adding empty `vim.ResourceAllocationInfo()` and `vim.ResourceAllocationInfo()` to `vim.vm.ConfigSpec()` used for requesting change in cpu/mem, even though there is no resource configuration specified in vmware_guest call. 
It is empty request but it seems to trigger permission check anyway, failing whole request.
I have altered the code by removing empty requests and it works.
