### ISSUE TITLE
vpshere_guest/vmware_guest: vm_nic/network options is not applied on reconfigure

### ISSUE THREAD

**Issue by SaranrajMG** [ansible/ansible#38953]
An issue raised already but not resolved #19106

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest
vsphere_guest

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/python27/root/usr/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /opt/rh/python27/root/usr/bin/ansible
  python version = 2.7.13 (default, Feb  8 2017, 06:30:30) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]

```

##### CONFIGURATION
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = False
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory.yml']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 5
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
Control server: RHEL 6

##### SUMMARY
I'm trying to change the network type on existing and running VM. I have tried using vsphere_guest and vmware_guest to change the adapter type and even tried to create new network adapter on the existing VM. But both didn't work for me. Please let me know if there is a solution to change the adapter type via ansible.

When I use vmware_guest module its show 2 network adapter in the verbose output but an adapter is not created at the VM level.

##### STEPS TO REPRODUCE

```
vsphere_guest playbook
---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: "pass"
      prompt: "Enter password"
      private: yes
  tasks:
  - name: Reconfigure the existing vmnic type
    vsphere_guest:
      vcenter_hostname: XXX.XXX.XXX.XXX
      username: "XXX.XXX.XXX.XXX"
      password: XXX.XXX.XXX.XXX
      validate_certs: no
      guest: XXX.XXX.XXX.XXX
      state: reconfigured
      esxi:
        datacenter: XXX.XXX.XXX.XXX
      vm_nic:
        nic1:
          type: vmxnet3
          network: "VLAN 326"
          network_type: dvs
          state: connected

          
vmware_guest playbook          
---
- hosts: localhost
  gather_facts: false
  vars_prompt:
    - name: "pass"
      prompt: "Enter password"
      private: yes
  tasks:
  - name: Try to reconfigure the vmnic device type
    vmware_guest:
      hostname: XXX.XXX.XXX.XXX
      username: XXX.XXX.XXX.XXX
      password: XXX.XXX.XXX.XXX
      validate_certs: false
      datacenter: XXX.XXX.XXX.XXX
      state: poweredon
      name: XXX.XXX.XXX.XXX
      networks:
       - name: "VLAN 326"
         device_type: vmxnet3
       - name: "VLAN 326"
         device_type: vmxnet3
```
##### EXPECTED RESULTS
Network adapter type of the VM could have changed and reflected in the VM

##### ACTUAL RESULTS
```
ok: [localhost -> localhost] => {
    "changed": false,
    "failed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "XXX.XXX.XXX.XXX",
            "datastore": null,
            "disk": [],
            "esxi_hostname": null,
            "folder": null,
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "XXX.XXX.XXX.XXX",
            "is_template": false,
            "linked_clone": false,
            "name": "XXX.XXX.XXX.XXX",
            "name_match": "first",
            "networks": [
                {
                    "device_type": "vmxnet3",
                    "name": "VLAN 326"
                },
                {
                    "device_type": "vmxnet3",
                    "name": "VLAN 326"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": null,
            "username": "XXX.XXX.XXX.XXX",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    }
}

```
