### ISSUE TITLE
Ansible needs to handle Azure image `accept-terms` for marketplace vm images

### ISSUE THREAD

**Issue by spmp** [ansible/ansible#38973]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
```
2.6.0
```

##### CONFIGURATION
COLOR_ERROR = purple
COLOR_VERBOSE = white

##### OS / ENVIRONMENT
N/A (Ubuntu 14.04)

##### SUMMARY
Some Azure Marketplace OS images, for example Paoloalto Firewalls, require  terms to be accepted before VM's using these images can be deployed.
 As Ansible aims to programatically deploy infrastructure this aught to happen in a non interactive manner.
 Luckily the azure cli has been recently updated to accept the term as:
```
az vm image accept-term --urn <publisher:offer:sku:version>
```
For example with a PaloAlto Firewall image which can be viewed as:
```
az vm image list --all --publisher paloalto --offer vmseries1 --sku bundle2
[
  {
    "offer": "vmseries1",
    "publisher": "paloaltonetworks",
    "sku": "bundle2",
    "urn": "paloaltonetworks:vmseries1:bundle2:7.1.1",
    "version": "7.1.1"
  },
  {
    "offer": "vmseries1",
    "publisher": "paloaltonetworks",
    "sku": "bundle2",
    "urn": "paloaltonetworks:vmseries1:bundle2:8.0.0",
    "version": "8.0.0"
  },
  {
    "offer": "vmseries1",
    "publisher": "paloaltonetworks",
    "sku": "bundle2",
    "urn": "paloaltonetworks:vmseries1:bundle2:8.1.0",
    "version": "8.1.0"
  }
]
```
So the above Azure command for the `8.1.0` version would be:
```
az vm image accept-term --urn paloalto:vmseries1:bundle2:8.1.0
```
If this step is note performed, attempting to provision a VM with the above image will fail.

See
https://github.com/Azure/azure-cli/issues/3411
and
https://github.com/Azure/azure-cli/pull/5378/files

##### STEPS TO REPRODUCE
Attempt to provision an Azure Marketplace image that requires terms to be accepted when the afore mentioned azure commands have not been run will fail. I cannot give you the failure as I cannot unnacept the terms to run again .
```yaml
- name: Create Firewall VMs
  azure_rm_virtualmachine:
    auth_source:          cli
    resource_group:       "{{ resgroup_net }}"
    name:                 "{{ firewall.firewallName }}"
    admin_username:       "{{ fw_common.fwAdminUserName }}"
    availability_set:     "{{ fw_common.fwAvailabilitySet }}"
    image:
      offer:              vmseries1
      publisher:          paloaltonetworks
      sku:                bundle2
      version:            '8.1.0'
    plan:
      publisher:          paloaltonetworks
      product :           vmseries1
      name:               bundle2
    managed_disk_type:    Standard_LRS
    network_interface_names: "{{ firewall.firewallNics | map(attribute='nicName') | list}}"
    ssh_password_enabled: false
    ssh_public_keys:
      - path:             "/home/{{ fw_common.fwAdminUserName }}/.ssh/authorized_keys"
        key_data:         "{{ sshkeydata }}"
    vm_size:              "{{ fw_common.fwHarwareSize }}"
```

##### EXPECTED RESULTS
VM is successfully provisioned

##### ACTUAL RESULTS
VM is not provisioned as the Azure Marketplace image terms have not been accepted.

**Comment by ansibot** [comment]
@spmp Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @devigned @haroldwongms @lmazuel @nitzmahone @obsoleted @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
@spmp Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information.
Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md
if I get the reproduce method , I will try and push issue effectively to solve.

**Comment by spmp** [comment]
@Fred-sun issue description updated. I cannot provide exact error messages sorry.

**Comment by Fred-sun** [comment]
@spmp Thanks for you updated, I ran following YML file , but fail, does these fail info like you report issue ? Thanks!
``` e.g.
---
# Resource_group and image has create before excute
- name: For Azure learn
  hosts: localhost
  connection: local
  vars:
    resource_group: myRG06  
    location: westeurope
    virtualnetwork: virtualnetwork
    subnet: subnet
    public_ip: public_ip
    storageaccount: sssaaa02
    security_ssh: security_ssh
    test_nic: test_nic
    vm_name: myVM
  tasks:
  - name: create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"

  - name: create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storageaccount }}"
      account_type: Standard_LRS

  - name: create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtualnetwork }}"
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.0.1.0/24"
      virtual_network: "{{ virtualnetwork }}"

  - name: create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ public_ip }}"
  
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_ssh }}"
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 101
          direction: Inbound
  
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ test_nic }}"
      virtual_network: "{{ virtualnetwork }}"
      subnet: "{{ subnet }}"
      public_ip_name: "{{ public_ip}}"
      security_group: "{{ security_ssh }}"

  - name: create an availability set with default options 
    azure_rm_availabilityset:
      name: availability_set
      location: "{{ location }}"
      resource_group: "{{ resource_group }}"
#      platform_update_domain_count: 5
#      platform_fault_domain_count: 3
      sku: Aligned
  - name: create virtual machine
    azure_rm_virtualmachine: 
      resource_group: "{{ resource_group }}"
      name: "{{ vm_name }}"
      auth_source: cli
      availability_set: availability_set
      vm_size: Standard_A0
      managed_disk_type: Standard_LRS
      storage_account: "{{ storageaccount }}"
      admin_username: azureuser
      admin_password: Password@0329
      network_interface_names: "{{ test_nic }}"
#      state: present
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "/home/azureuser/.ssh/authorized_keys"
          key_data: "ssh-rsa************************Machine"
      image: 
        offer: vmseries1
        publisher: paloaltonetworks
        sku: bundle2
        version: '8.1.0'
      plan:
        publisher: paloaltonetwords
        product: vmseries1
        name: bundle2


Ran result as below:
TASK [create an availability set with default options] ************************************
ok: [127.0.0.1]

TASK [create virtual machine] *************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "Error myVM has a provisioning state of Failed. Expecting state to be Succeeded."}
	to retry, use: --limit @/home/fred/task/accept_terms.retry

PLAY RECAP ********************************************************************************
127.0.0.1                  : ok=9    changed=2    unreachable=0    failed=1

**Comment by gustavomcarmo** [comment]
@kyliel @yuwzho @zikalino I think this issue deserves attention. I've faced the same problem, while automating the deployment of the Gitlab Community Edition image. Take a look:

```txt
TASK [Create the Gitlab VM] *********************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine gitlab - Azure Error: ResourcePurchaseValidationFailed
Message: User failed validation to purchase resources. Error message: 'Legal terms have not been accepted for this item on this subscription. To accept legal terms using PowerShell, please use Get-AzureRmMarketplaceTerms and Set-AzureRmMarketplaceTerms API(https://go.microsoft.com/fwlink/?linkid=862451) or deploy via the Azure portal to accept the terms'"}
```

**Comment by spmp** [comment]
I have a solution in place which is a bit of a hack but works for now:

```
- name: Accept terms for image deployment
  shell: az vm image accept-terms --urn {{ fw_firewalls.common.urn }}
  tags:
    - fw
```
Where the `urn` is:
```
urn:                            "{{ firewall_image_reference.publisher }}:{{ firewall_image_reference.offer }}:{{ firewall_image_reference.sku }}:{{ firewall_image_reference.version }}"
```
You get the idea - all those references separated by colon
