### ISSUE TITLE
ec2_elb_lb module - "ProxyProtocol-policy" is not actually being created

### ISSUE THREAD

**Issue by ServerNinja** [ansible/ansible#38970]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_elb_lb module

##### ANSIBLE VERSION
```
ansible 2.3.2.0
  config file = /Users/johnr/src/bluescape/ansible-inventory/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Sep 18 2017, 12:16:42) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
```
[defaults]
roles_path = roles/:galaxy_roles/
nocows=1
inventory = ./inventory
vault_password_file = /etc/ansible/.vault_pass
host_key_checking=False
retry_files_save_path = ~/.ansible-retry
ansible_managed = This file is managed by Ansible. Do NOT edit this file manually!
become = true

[ssh_connection]
ssh_args = -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes -o UserKnownHostsFile=/dev/null
control_path = %(directory)s/%%h-%%p-%%r
```

##### OS / ENVIRONMENT
Mac OS 10.13.2

##### SUMMARY
Creating a classic ELB using ansible with `proxy_protocol: true` doesn't actually create the ProxyProtocol-policy object (doesn't show up when I run `aws elb describe-load-balancer-policies`). However, it is showing up in the JSON for `aws elb describe-load-balancers` as an attached policy:

```
            "Policies": {
                "LBCookieStickinessPolicies": [],
                "AppCookieStickinessPolicies": [],
                "OtherPolicies": [
                    "ProxyProtocol-policy"
                ]
            },
```

##### STEPS TO REPRODUCE
```
    ### EC2 ELB ###
    - name: Create ELB
      local_action:
        module: ec2_elb_lb
        region: '{{ region }}'
        state: present
        subnets: '{{ vpc_subnet_list }}'
        name: 'my_elb'
        security_group_names: "my_elb_sg"
        listeners:
          - protocol: tcp
            load_balancer_port: 443
            instance_port: 443
            instance_protocol: tcp
            proxy_protocol: True
          - protocol: tcp
            load_balancer_port: 80
            instance_port: 80
            instance_protocol: tcp
            proxy_protocol: True
        health_check:
            ping_protocol: tcp
            ping_port: 1936
            interval: 30
            path: /healthz
            response_timeout: 5
            unhealthy_threshold: 2
            healthy_threshold: 10
      register: elb_info
```
##### EXPECTED RESULTS
I would expect that the `ProxyProtocol-policy` ELB policy would show up when I run `aws elb describe-load-balancer-policies`. 

##### ACTUAL RESULTS
It shows up in the JSON for the load balancer as being attached but its as if this policy doesn't exist. 

In summary my ELB that was created works as expected, I just need to understand what actually is being created and what is going on in the background. The ansible code for this module suggests that the policy is to be created if it doesn't exist. However, I don't think its actually creating it.

Also, how is it that the policy is assigned to the ELB under "OtherPolicies", yet the policy is missing? How does this even work?

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_elb_lb.py#L1109-L1110

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_elb_lb.py#L1137-L1147
