### ISSUE TITLE
Work with XML files exported from Zabbix interface for zabbix_template module.

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#38986]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
zabbix_template

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
It would be very convenient it `zabbix_template` module could import templates from XML files, exported from Zabbix interface.

Writing file for Zabbix template manually is almost impossible: it's very large and verbose. The only way to get it is to configure it in Zabbix interface and then export. Now the only way to export is to use this module with `state: dump` for required template. Not convenient at all.

Ability to import XML files exported from Zabbix interface will make work much easier.

##### STEPS TO REPRODUCE

```yaml
- name: Import Zabbix json template configuration from xml file
  local_action:
    module: zabbix_template
    server_url: http://127.0.0.1
    login_user: username
    login_password: password
    template_name: Apache2
    template_xml: "{{ lookup('file', 'zabbix_apache2.xml') }}"
    template_groups:
      - Webservers
    state: present
```

##### EXPECTED RESULTS
Be able to configure templates in Zabbix interface, export them into XML files and easy integrate with ansible.

##### ACTUAL RESULTS
Now you have to create special playbook to export template in json. That is not convenient at all.
