### ISSUE TITLE
set_fact with with_items does not work properly on 2.5.1

### ISSUE THREAD

**Issue by slnowak** [ansible/ansible#39004]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 18:21:57) [GCC 4.9.2]

```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE
Run the following playbook on 2.5.0 and 2.5.1:

```yaml
- hosts: localhost
  connection: local

  vars:
    example_list:
      - foo
      - bar
      - baz

  tasks:
    - set_fact:
        jsonized: []

    - set_fact:
        jsonized: "{{ jsonized + [{'name': item}] }}"
      with_items: "{{ example_list }}"

    - debug:
        var: jsonized
```

##### EXPECTED RESULTS
```
"jsonized": [
        {
            "name": "foo"
        }, 
        {
            "name": "bar"
        }, 
        {
            "name": "baz"
        }
    ]

```

##### ACTUAL RESULTS
```
"jsonized": [
        {
            "name": "baz"
        }
    ]

```

it used to work on 2.4.2 and 2.5.0.
