### ISSUE TITLE
Cannot install .deb using package module

### ISSUE THREAD

**Issue by sodle** [ansible/ansible#39046]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

package

##### ANSIBLE VERSION

```
ansible 2.0.0.2
  config file = /home/spunker/ansible_linux_uf/ansible.cfg
  configured module search path = Default w/o overrides
```

##### CONFIGURATION

```ini
[privilege_escalation]
become_ask_pass=true

[defaults]
inventory=inventory/hosts
```

##### OS / ENVIRONMENT

Managing Ubuntu 16.04.4 LTS (xenial) from localhost. Apt version 1.2.26 (amd64).

##### SUMMARY

When attempting to install a package via...
```yaml
- name: Install the Splunk UF package file
  package:
    name: /tmp/splunk_uf.deb
    state: present
```
the play fails with error...
```
No package matching '/tmp/splunk_uf.deb' is available
```
The equivalent on Red Hat succeeds:
```yaml
- name: Install the Splunk UF package file
  package:
    name: /tmp/splunk_uf.rpm
    state: present
```

##### STEPS TO REPRODUCE

Place a .deb package on your target machine and run
```yaml
- name: Reproduce package bug
  package:
    name: /path/to/package.deb
    state: present
```

##### EXPECTED RESULTS

Package should be installed from the .deb file

##### ACTUAL RESULTS

```No package matching '/path/to/package.deb' is available```

```
TASK [Reproduce package bug] ***************************************************
task path: /home/spunker/ansible_linux_uf/repro.yaml:5
Running apt
ESTABLISH LOCAL CONNECTION FOR USER: spunker
localhost EXEC ( umask 22 && mkdir -p "$( echo $HOME/.ansible/tmp/ansible-tmp-1524191707.39-149458311115615 )" && echo "$( echo $HOME/.ansible/tmp/ansible-tmp-1524191707.39-149458311115615 )" )
localhost PUT /tmp/tmpe8_RP3 TO /home/spunker/.ansible/tmp/ansible-tmp-1524191707.39-149458311115615/apt
localhost EXEC /bin/sh -c 'sudo -H -S  -p "[sudo via ansible, key=nwtqlqahecglrcwzotqeewshvxkganxk] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-nwtqlqahecglrcwzotqeewshvxkganxk; LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python /home/spunker/.ansible/tmp/ansible-tmp-1524191707.39-149458311115615/apt; rm -rf "/home/spunker/.ansible/tmp/ansible-tmp-1524191707.39-149458311115615/" > /dev/null 2>&1'"'"''
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"cache_valid_time": null, "deb": null, "default_release": null, "dpkg_options": "force-confdef,force-confold", "force": false, "install_recommends": null, "name": "/path/to/package.deb", "package": ["/path/to/package.deb"], "purge": false, "state": "present", "update_cache": false, "upgrade": null}}, "msg": "No package matching '/path/to/package.deb' is available"}
```
