### ISSUE TITLE
set_fact only registers the last change to a variable when used in a with_items loop

### ISSUE THREAD

**Issue by zdw** [ansible/ansible#39049]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`set_fact` module, when used in a `with_items` loop to set the same fact multiple times. 

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/users/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Between 2.5.0 and 2.5.1, the behavior of `set_fact` changed when used in a ` with_items` loop (and possibly other kinds of loops) when setting the same value multiple times.

Only the last loop value is added to the list. 

##### STEPS TO REPRODUCE

Run the following playbook, which iterates over lists and adds them to a destination list, printing out the final list.  This is a simplified and artificial example ( using the `union` set operator would make more sense in this case) but it clearly shows the issue:

```yaml
---
- name: set_fact in a with_items loop
  hosts: localhost
  connection: local
  gather_facts: False

  vars:
    dest_list: []
    list_1:
      - alice
      - bob
    list_2:
      - charlie
      - dora

  tasks:

    - name: Add list_1 to dest_list
      set_fact:
        dest_list: "{{ dest_list }} + ['{{ item }}']"
      with_items: "{{ list_1 }}"

    - name: Add list_2 to dest_list
      set_fact:
        dest_list: "{{ dest_list }} + ['{{ item }}']"
      with_items: "{{ list_2 }}"

    - name: debug dest_list
      debug:
        var: dest_list
```

##### EXPECTED RESULTS

Output from 2.5.0 and earlier versions of ansible:

```
PLAY [set_fact in a with_items loop] **********************************************************************************************************

TASK [Add list_1 to dest_list] ****************************************************************************************************************
ok: [localhost] => (item=alice)
ok: [localhost] => (item=bob)

TASK [Add list_2 to dest_list] ****************************************************************************************************************
ok: [localhost] => (item=charlie)
ok: [localhost] => (item=dora)

TASK [debug dest_list] ************************************************************************************************************************
ok: [localhost] => {
    "dest_list": [
        "alice", 
        "bob", 
        "charlie", 
        "dora"
    ]
}

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```

##### ACTUAL RESULTS

Output from 2.5.1

```
PLAY [set_fact in a with_items loop] **********************************************************************************************************

TASK [Add list_1 to dest_list] ****************************************************************************************************************
ok: [localhost] => (item=alice)
ok: [localhost] => (item=bob)

TASK [Add list_2 to dest_list] ****************************************************************************************************************
ok: [localhost] => (item=charlie)
ok: [localhost] => (item=dora)

TASK [debug dest_list] ************************************************************************************************************************
ok: [localhost] => {
    "dest_list": [
        "bob", 
        "dora"
    ]
}

PLAY RECAP ************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0   
```
