### ISSUE TITLE
delegate_to and user switching

### ISSUE THREAD

**Issue by FlorianHeigl** [ansible/ansible#3904]
You get an error from delegate_to if you use i.e. "user" to specify a different user for a single task.

Tested on 
ansible 1.3 (devel ae98a025bb) last updated 2013/08/21 12:41:15 (GMT +200)

```
~/ansi-test$ ansible-playbook -vvv -K -i inventory bla.yml 
sudo password: 
ERROR: multiple actions specified in task iterate and delegate
```

From what I understand, this isn't really an issue about supporting user or sudo switching with delegate but just mis-interpretation - there's only one command statement.

```

---
- hosts: myhost
  user: floh
  connection: ssh

  vars:
    foo:
     - eins
     - zwei

  tasks:
  - name: iterate
    command: echo $item
    with_items: foo

  - name: iterate and delegate
    user: root
    sudo: yes
    delegate_to: localhost
    command: echo $item
    with_items: foo
```

It's quite a problem since, doing a different task on a different server, you might easily have a different account, too.
