### ISSUE TITLE
Version 2.5.1 break union filter

### ISSUE THREAD

**Issue by mowgli** [ansible/ansible#39053]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
union filter

##### ANSIBLE VERSION
```
2.5.1 (not installed anymore as it breaks stuff)
```

##### CONFIGURATION
```
- name: Build hostkey algorithms list
  set_fact:
    ssh_hostkey_algorithms: "{{ ssh_hostkey_algorithms|d([]) | union([item.algo]) }}"
  with_items:
    - {key: ed25519, algo: ssh-ed25519-cert-v01@openssh.com}
    - {key: rsa, algo: ssh-rsa-cert-v01@openssh.com}
    - {key: ed25519, algo: ssh-ed25519}
    - {key: rsa, algo: ssh-rsa}
    - {key: ecdsa, algo: ecdsa-sha2-nistp521-cert-v01@openssh.com}
    - {key: ecdsa, algo: ecdsa-sha2-nistp384-cert-v01@openssh.com}
    - {key: ecdsa, algo: ecdsa-sha2-nistp256-cert-v01@openssh.com}
    - {key: ecdsa, algo: ecdsa-sha2-nistp521}
    - {key: ecdsa, algo: ecdsa-sha2-nistp384}
    - {key: ecdsa, algo: ecdsa-sha2-nistp256}
    - {key: dsa, algo: ssh-dss-cert-v01@openssh.com}
    - {key: dsa, algo: ssh-dss}
  when: item.key in ssh_hostkeys
```

##### OS / ENVIRONMENT
Debian/Devuan

##### SUMMARY
The above sniplet generates ssh_hostkey_algorithms depending on ssh_hostkeys. With version 2.5.0 and below, it was the union of all selected hostkey algorithms. With version 2.5.1 it is only the last one with dropped all others. (In my case ssh-rsa)

##### STEPS TO REPRODUCE
Run it...

```yaml
- name: Build hostkey algorithms list
  set_fact:
    ssh_hostkey_algorithms: "{{ ssh_hostkey_algorithms|d([]) | union([item.algo]) }}"
  with_items:
    - {key: ed25519, algo: ssh-ed25519-cert-v01@openssh.com}
    - {key: rsa, algo: ssh-rsa-cert-v01@openssh.com}
    - {key: ed25519, algo: ssh-ed25519}
    - {key: rsa, algo: ssh-rsa}
    - {key: ecdsa, algo: ecdsa-sha2-nistp521-cert-v01@openssh.com}
    - {key: ecdsa, algo: ecdsa-sha2-nistp384-cert-v01@openssh.com}
    - {key: ecdsa, algo: ecdsa-sha2-nistp256-cert-v01@openssh.com}
    - {key: ecdsa, algo: ecdsa-sha2-nistp521}
    - {key: ecdsa, algo: ecdsa-sha2-nistp384}
    - {key: ecdsa, algo: ecdsa-sha2-nistp256}
    - {key: dsa, algo: ssh-dss-cert-v01@openssh.com}
    - {key: dsa, algo: ssh-dss}
```

##### EXPECTED RESULTS
ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,ssh-rsa

##### ACTUAL RESULTS
ssh-rsa
