### ISSUE TITLE
Filter by host var fail

### ISSUE THREAD

**Issue by Nir-Tal** [ansible/ansible#39055]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- Filter by host var
##### ANSIBLE VERSION

```
2.4.0.0 (checked as well with 2.5.0.0)
```

##### CONFIGURATION

ANSIBLE_SSH_ARGS(ansible/ansible.cfg) = -o UserKnownHostsFile=/dev/null -o StrictHost
DEFAULT_MODULE_PATH(ansible/ansible.cfg) = [u'/home/nir/ArchAssets/var/ansible/module
DEFAULT_TRANSPORT(ansible/ansible.cfg) = ssh
RETRY_FILES_ENABLED(ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ansible host: Debian 8.10
target host: Debian 8.10

##### SUMMARY
Using host var to filter roles not working.
Before moving to host/group vars we used to load host specific var files and using those vars to filter what roles to run and it worked.  

##### STEPS TO REPRODUCE

inventory/hosts:
```yaml
test.domain.com
```
inventory/host_vars/test.domain.com/vars.yml
```yaml
backup_enabled: false
```
playbook.yml
```yaml
- hosts: test.domain.com
  gather_facts: false
  pre_tasks:
  ...
  - setup

  roles:
  - { role: backup, when: backup_enabled, tags: ['backup'] }
```

##### EXPECTED RESULTS

The backup role should be skiped

##### ACTUAL RESULTS

The backup role is running

```

```
