### ISSUE TITLE
Nested include_role in a playbook not working in 2.5.1

### ISSUE THREAD

**Issue by panticz** [ansible/ansible#39065]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

include_role

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### STEPS TO REPRODUCE

```
# vm1.yml
- hosts: vm1
  roles:
    - role1

# ../roles/role1/tasks/main.yml
- import_tasks: deploy-ear.yml
  tags:
    - ear

# ../role1/tasks/deploy-ear.yml
- include_role:
    name: archive-deploy
```

##### ACTUAL RESULTS

Role archive-deploy is not included. After downgrade to 2.4.2.0 include_role works as expected.

```

```
