### ISSUE TITLE
combine() replaces instead of combining when trying to accumulate k/v-pairs in a loop in 2.5.1

### ISSUE THREAD

**Issue by blubberdiblub** [ansible/ansible#39062]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

`filter/core.py` (supposedly)

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/boehm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/boehm/core/venv/lib/python3.6/site-packages/ansible
  executable location = /home/boehm/core/venv/bin/ansible
  python version = 3.6.4 (default, Jan  5 2018, 02:13:53) [GCC 7.2.0]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/etc/ansible/hosts.yml']
```

##### OS / ENVIRONMENT

- Ubuntu 18.04
- CentOS 7.2.1511

##### SUMMARY

`combine()` completely replaces contents of the former dictionary when accumulating items inside a `loop` or `with_items` loop.

This happens both with Python 2.7.x and Python 3.6.x.

It does not appear to happen with a lone `set_fact` and `combine` outside a loop.

It worked fine with Ansible 2.5.0 and earlier.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost

  tasks:

    - set_fact:
        some_dict: {}

    - loop:
        - {k: 'first item', v: 'some content'}
        - {k: 'second item', v: 'more content'}
      set_fact:
        some_dict: >-
          {{
            some_dict
            | combine({
                item['k']: item['v']
            })
          }}
    
    - debug:
        var: some_dict
```

##### EXPECTED RESULTS

```
TASK [debug] ************************************************************************************************************************
ok: [localhost] => {
    "some_dict": {
        "first item": "some content",
        "second item": "more content"
    }
}
```

##### ACTUAL RESULTS

```
TASK [debug] ************************************************************************************************************************
ok: [localhost] => {
    "some_dict": {
        "second item": "more content"
    }
}
```
