### ISSUE TITLE
Loop-then-fail pattern seems broken in Ansible 2.5.0

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#39068]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
2.5.1
```

##### SUMMARY
On earlier versions of ansible, this was a valid pattern:
```
- name: Wait until site responds (max 10 minutes)
  win_uri:
    url: http://localhost:8000/healthz
    method: GET
  register: local_healthz_test_result
  ignore_errors: true
  until: local_healthz_test_result | success
  retries: 3
  delay: 2
```

This would retry the loop, but if the "until" statement wasnt met, the task would report failed.
In Ansible 2.5.0 the behavior has changed: As long as "ignore errors" is configured, ansible will simply ignore the fact that the "until" statement isn't met and continues. This makes it impossible to construct "retry-then-fail" logic in a concise manner.

##### STEPS TO REPRODUCE
See the above playbook

##### EXPECTED RESULTS
If the "until" statement isn't met after the retry, fail the task

##### ACTUAL RESULTS
Ansible ignores the failure even if the "until" statement isn't met.

**Comment by trondhindenes** [comment]
btw I totally see the logic in this (we did specify ignore_errors after all), but I'm still worried because:
1. the behavior is different from before (we upgraded from 2.3 so the new behavior may have been the case for 2.4 as well)
2. Its difficult to constrult loop-then-fail statements in Ansible since we now longer have separate error control of the loop as a whole and the result of the "inner" task being looped.

**Comment by trondhindenes** [comment]
it seems that the intented can be obtained using `failed_when` to control the overall result of the task, while `ignore_errors` controls the inner loop. This should probably be documented somewhere...

**Comment by jimi-c** [comment]
@trondhindenes I'm not quite sure I understand the problem here. Looking at the code, ignore_errors isn't really used at all inside the inner loop (`_execute()`), which is where the retry/until loop is done. That inner method only sets a flag using the task's value of ignore_errors, and that's checked per-item after `_run_loop()` is done iterating over items. Beyond that, ignore_errors is only then checked in `_process_pending_results()`, which is after the task is completely done executing.

**Comment by trondhindenes** [comment]
I don't know enough about the internals of Ansible to be able to process your response, but:
on 2.3.2 we could do this:

```
- name: Wait until responds (max 10 minutes)
  win_uri:
    url: http://localhost:8000/healthz
    method: GET
  register: local_healthz_test_result
  ignore_errors: true
  until: local_healthz_test_result is success
  retries: 20
  delay: 30
```

On 2.5.1 we have to do this in two steps:
```
- name: Wait (max 10 minutes)
  win_uri:
    url: http://localhost:8000/healthz
    method: GET
  register: local_healthz_test_result
  ignore_errors: true
  until: local_healthz_test_result is success
  retries: 20
  delay: 30

- name: check output
  set_fact:
    dummy: dummy
  failed_when: not local_healthz_test_result is success
```
