### ISSUE TITLE
cannot use ${item} in handler when using notify/with_items in the task?

### ISSUE THREAD

**Issue by YAmikep** [ansible/ansible#3910]
It looks like you cannot use the ${item} variable in an handler when you use notify/with_items on a task ? Is that made on purpose?
Thanks

See for further details: http://stackoverflow.com/questions/18368427/ansible-how-to-use-the-variable-item-from-with-items-in-notify

**Comment by srgvg** [comment]
Handlers are flagged for execution only once, when at least one of the itemized sub tasks requests it (changed: yes). So I expect a handler to not know about the itemized loop, and this being as expected.

**Comment by srgvg** [comment]
A possible solution is not with a handler but with an extra task + conditional. Something like

``` yaml
- hosts: all 
  gather_facts: false
  tasks:
  - action: shell echo {{item}}
    with_items:
    - 1 
    - 2 
    - 3 
    - 4 
    - 5 
    register: task
  - debug: msg="{{item.item}}"
    with_items: task.results
    when: item.changed == True
```
