### ISSUE TITLE
issues while running playbook for  : nxos-feature-module

### ISSUE THREAD

**Issue by dhakalanis** [ansible/ansible#39103]
##### ISSUE TYPE
 - Bug Report
I'm not sure if this is a bug but am now reporting as the closest issue type.

##### COMPONENT NAME
nxos-feature-module

##### ANSIBLE VERSION

vagrant@acs:/etc/ansible$ ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]
vagrant@acs:/etc/ansible$ 

##### CONFIGURATION
vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ ansible-config dump --only-changed
vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ ansible-config dump --only-changed
vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ 

##### OS / ENVIRONMENT

vagrant@acs:/etc/ansible$ 
vagrant@acs:/etc/ansible$ uname -a
Linux acs 3.13.0-128-generic #177-Ubuntu SMP Tue Aug 8 11:40:23 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
vagrant@acs:/etc/ansible$ 

##### SUMMARY
issues while running playbook for  : nxos-feature-module
Please see details yaml file and execution of the ansible-playbook

##### STEPS TO REPRODUCE

```yaml

vagrant@acs:/etc/ansible$ cat playbook_nxos_feature.yaml 
---
- hosts: lab_nxos
  gather_facts: no
  connection: local


  tasks:
  - name: GET CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE CONNECTION
    set_fact:
       connection:
          authorize: yes
          host: "{{ inventory_hostname }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
  
  - name: Show feature | grep vpc
    nxos_command:
     commands: show feature | grep vpc
    register: pre_check_show_feature

  - debug: var=pre_check_show_feature.stdout_lines

  - name: Feature enable / disable
    nxos_feature:
     feature: vpc
     state: disabled

  - name: POst Check show feature | grep vpc
    nxos_command:
      commands: show feature | grep vpc
  - debug: var=post_check_show_feature.stdout_lines


vagrant@acs:/etc/ansible$ 


```

##### ACTUAL RESULTS

```


vagrant@acs:/etc/ansible$ ansible-playbook playbook_nxos_feature.yaml

PLAY [lab_nxos] *********************************************************************************************************************************************************************

TASK [GET CREDENTIALS] **************************************************************************************************************************************************************
ok: [ANS-SPINE2]

TASK [DEFINE CONNECTION] ************************************************************************************************************************************************************
ok: [ANS-SPINE2]

TASK [Show feature | grep vpc] ******************************************************************************************************************************************************
ok: [ANS-SPINE2]

TASK [debug] ************************************************************************************************************************************************************************
ok: [ANS-SPINE2] => {
    "pre_check_show_feature.stdout_lines": [
        [
            "vpc                   1         enabled"
        ]
    ]
}

TASK [Feature enable / disable] *****************************************************************************************************************************************************
ANS-SPINE2#n occurred during task execution. To see the full traceback, use -vvv. The error was: 
fatal: [ANS-SPINE2]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible__QRLaF/ansible_module_nxos_feature.py\", line 251, in <module>\n    main()\n  File \"/tmp/ansible__QRLaF/ansible_module_nxos_feature.py\", line 220, in main\n    feature = validate_feature(module)\n  File \"/tmp/ansible__QRLaF/ansible_module_nxos_feature.py\", line 133, in validate_feature\n    info = get_capabilities(module).get('device_info', {})\n  File \"/tmp/ansible__QRLaF/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py\", line 474, in get_capabilities\n  File \"/tmp/ansible__QRLaF/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py\", line 225, in get_capabilities\n  File \"/tmp/ansible__QRLaF/ansible_modlib.zip/ansible/module_utils/connection.py\", line 146, in __rpc__\nansible.module_utils.connection.ConnectionError: show version | json\r\r\n                           ^\r\n% Invalid command at '^' marker.\r\n\rANS-SPINE2# \n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
 [WARNING]: Could not create retry file '/etc/ansible/playbook_nxos_feature.retry'.         [Errno 13] Permission denied: u'/etc/ansible/playbook_nxos_feature.retry'


PLAY RECAP **************************************************************************************************************************************************************************
ANS-SPINE2                 : ok=4    changed=0    unreachable=0    failed=1   

vagrant@acs:/etc/ansible$ 


```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nxos/nxos_feature.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_feature.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @GGabriele @jedelman8 @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by trishnaguha** [comment]
@dhakalanis Is json structured output supported on your nxos device? Can you please check and let us know?
Thanks.

**Comment by dhakalanis** [comment]
Thanks @trishnaguha for taking ownership of this.

 The main issue when i reported was for :
 - Device name: ANS-SPINE2
-  Device type: N5K-C5596UP-SUP
-  Version: n5000-uk9.7.1.4.N1.1c.bin
 

I checked the device and the NXOS version does not support feature nxapi. AFAIK, its pre-requisite for a device to have this feature enabled for running Ansible related playbooks.
Action item for me: 
1. Try to upgrade this device to latest NXOS code and reproduce the issue.
2. Check similar behavior on other device type with nxapi feature enabled.

2a. Hence, to avoid confusion, I am using below device which supports nxapi.
- Device name: ANS-SPINE1
- Device type: N5K-C5596UP-SUP
- Version: n5000-uk9.7.3.2.N1.1.bin


I'm still getting similar error. Below are screenshots of the ansible plays:

*********************
Ansible Playbook content:
*********************
```yaml

vagrant@acs:/etc/ansible$ cat playbook_nxos_feature.yaml 
---
- hosts: lab_nxos
  gather_facts: no
  connection: local


  tasks:
  - name: GET CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE CONNECTION
    set_fact:
       connection:
          authorize: yes
          host: "{{ inventory_hostname }}"
          username: "{{ creds['username'] }}"
          password: "{{ creds['password'] }}"
          auth_pass: "{{ creds['auth_pass'] }}"
  
  - name: Show feature | grep enabled
    nxos_command:
     commands: show feature | grep enabled
    register: pre_check_show_feature

  - debug: var=pre_check_show_feature.stdout_lines

  - name: Feature enable / disable
    nxos_feature:
     feature: vpc
     state: disabled

  - name: POst Check show feature | grep enabled
    nxos_command:
      commands: show feature | grep enabled
  - debug: var=post_check_show_feature.stdout_lines
```
*********************
Ansible Playbook execution:
*********************
``` yaml

vagrant@acs:/etc/ansible$ ansible-playbook playbook_nxos_feature.yaml

PLAY [lab_nxos] *********************************************************************************************************************************************************************

TASK [GET CREDENTIALS] **************************************************************************************************************************************************************
ok: [ANS-SPINE1]

TASK [DEFINE CONNECTION] ************************************************************************************************************************************************************
ok: [ANS-SPINE1]

TASK [Show feature | grep enabled] **************************************************************************************************************************************************
ok: [ANS-SPINE1]

TASK [debug] ************************************************************************************************************************************************************************
ok: [ANS-SPINE1] => {
    "pre_check_show_feature.stdout_lines": [
        [
            "lacp                  1         enabled ", 
            "lldp                  1         enabled ", 
            "nxapi                 1         enabled ", 
            "sshServer             1         enabled ", 
            "tacacs                1         enabled ", 
            "udld                  1         enabled ", 
            "vpc                   1         enabled"
        ]
    ]
}

TASK [Feature enable / disable] *****************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: No JSON object could be decoded
fatal: [ANS-SPINE1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_uHwaCu/ansible_module_nxos_feature.py\", line 251, in <module>\n    main()\n  File \"/tmp/ansible_uHwaCu/ansible_module_nxos_feature.py\", line 220, in main\n    feature = validate_feature(module)\n  File \"/tmp/ansible_uHwaCu/ansible_module_nxos_feature.py\", line 133, in validate_feature\n    info = get_capabilities(module).get('device_info', {})\n  File \"/tmp/ansible_uHwaCu/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py\", line 474, in get_capabilities\n  File \"/tmp/ansible_uHwaCu/ansible_modlib.zip/ansible/module_utils/network/nxos/nxos.py\", line 225, in get_capabilities\n  File \"/tmp/ansible_uHwaCu/ansible_modlib.zip/ansible/module_utils/connection.py\", line 146, in __rpc__\nansible.module_utils.connection.ConnectionError: No JSON object could be decoded\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
 [WARNING]: Could not create retry file '/etc/ansible/playbook_nxos_feature.retry'.         [Errno 13] Permission denied: u'/etc/ansible/playbook_nxos_feature.retry'


PLAY RECAP **************************************************************************************************************************************************************************
ANS-SPINE1                 : ok=4    changed=0    unreachable=0    failed=1   

vagrant@acs:/etc/ansible$ 


```
