### ISSUE TITLE
systemD not enabling service on boot

### ISSUE THREAD

**Issue by minac** [ansible/ansible#39116]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
systemd

##### ANSIBLE VERSION
```bash
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/myuser/Documents/myproject/pythonvirtualenv/lib/python2.7/site-packages/ansible
  executable location = /Users/myuser/Documents/myproject/pythonvirtualenv/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION
```bash
cat ansible.cfg
[defaults]
host_key_checking = False
callback_whitelist = profile_tasks
ansible_managed = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
retry_files_enabled = False
squash_actions = apk,apt,dnf,package,pacman,pkgng,yum,zypper
log_path=ansible.log

[ssh_connection]
ssh_args=-o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p-%r -o ForwardAgent=yes
```

##### OS / ENVIRONMENT
macOS High Sierra 10.13.4 and Ubuntu 16.04

##### SUMMARY
When doing this:
```yaml
- name: Nginx - Start and Enable service
  systemd:
    name: nginx
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
```

The daemon does not get started on reboot. The module "service" also has the same issue.

Doing the following works:
```yaml
- name: Nginx - Enable service not through ansible
  shell: systemctl enable nginx.service

- name: Nginx - Enable service not through ansible
  shell: systemctl start nginx.service
```

##### STEPS TO REPRODUCE
```yaml
# Systemd does not seem to add the service
- name: Nginx - Start and Enable service
  systemd:
    name: nginx
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
```

##### EXPECTED RESULTS
Nginx to start on reboot of server.

##### ACTUAL RESULTS
No error happened on Ansible side, however on the server systemD does not show nginx on the modules to be loaded.

```bash
ubuntu@ip-111-111-111-111:/var/log$ sudo systemctl --failed
0 loaded units listed. Pass --all to see loaded but inactive units, too.
To show all installed unit files use 'systemctl list-unit-files'.
ubuntu@ip-111-111-111-111:/var/log$ sudo systemctl --all | grep nginx
ubuntu@ip-111-111-111-111:/var/log$
```
