### ISSUE TITLE
Slack channel webhook SSL validate error

### ISSUE THREAD

**Issue by camdixon** [ansible/ansible#39126]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
Slack Module

##### ANSIBLE VERSION
```
ansible 2.5.1
```

##### CONFIGURATION

```
---
- hosts: all
  
  tasks:
  - name: Send notification message via Slack
    local_action:
      module: slack
      channel: "#devops"
      token: <TOKEN_HERE>
      msg: <{{ ansible_env.USER }}> ran updates to {{ ansible_hostname }} and are complete.
      validate_certs: 'yes'
```

##### EXPECTED RESULTS
I expect to see a successful connection to Slack Channel

##### ACTUAL RESULTS
Validation of the SSL Cert fails, and provides error message about reporting to slack channel.  If I set `validate_certs: 'no'` then it does report successfully.  I did verify this in my slack channel.

```
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/camdixon/.ansible/tmp/ansible-tmp-1524401970.946153-266884385175812/ > /dev/null 2>&1 && sleep 0'
fatal: [sc-cbs-hub01 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "attachments": null,
            "channel": "#devops",
            "color": "normal",
            "domain": null,
            "icon_emoji": null,
            "icon_url": "https://www.ansible.com/favicon.ico",
            "link_names": 1,
            "msg": "<cdixon> ran updates to sc-cbs-hub01 and are complete.",
            "parse": null,
            "token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "username": "Ansible",
            "validate_certs": true
        }
    },
    "msg": " failed to send {\"text\": \"<cdixon> ran updates to sc-cbs-hub01 and are complete.\", \"channel\": \"#devops\", \"username\": \"Ansible\", \"icon_url\": \"https://www.ansible.com/favicon.ico\", \"link_names\": 1} to https://hooks.slack.com/services/[obscured]: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)>"
}
```
