### ISSUE TITLE
synchronize module copies wrong files when ran with empty rsync_opts

### ISSUE THREAD

**Issue by nesanton** [ansible/ansible#39144]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

module: synchronize

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/confbot/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True

##### OS / ENVIRONMENT

control: CentOS Linux release 7.4.1708
controlled: CentOS Linux release 7.4.1708; rsync  version 3.0.9  protocol version 30

##### SUMMARY

When copying files, the resulting CMD may incorporate an extra src argument when passing an empty option in rsync_opts. Reproduced both when src and dest are on different hosts and on the same host with delegate_to: "{{ inventory_hostname }}"

E.g. the following piece
```yaml
- name: Copy files locally on remote host
  synchronize:
    src: /tmp/src/
    dest: /tmp/dst
    rsync_opts:
      - "--exclude=*.conf"
      - "{{ some_rsync_options_formed_earlier_in_playbook | default('') }}"
```
will result in command:
```
/usr/bin/rsync --delay-updates -F --compress --archive '--rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null' '--exclude=*.conf' '' '--out-format=<<CHANGED>>%i %n%L'  /tmp/src /tmp/dst
```

This little ```''``` between --exclude and --out-format acts as another src argument, copying everything from the current dir (additionally to /tmp/src) to /tmp/dst

When adding rsync_opts option to cmd in this line:
https://github.com/ansible/ansible/blob/fafceb989599f523decb73877db8cfbcbed9b8f5/lib/ansible/modules/files/synchronize.py#L493
in my case the condition "if rsync_opts:" will evaluate to True (rsync_opts=['--exclude=*.conf', ''] or without --exclude still True with rsync_opts = ['', ]). 

This line can be blamed too, because this is where the empty arg gets quoted: https://github.com/ansible/ansible/blob/fd5024846337a05dac50079d823ed10d5e2e06c0/lib/ansible/module_utils/basic.py#L2698
shlex_quote happily quotes this empty rsync_opts arg and adds to the CMD

I know that I can write the playbook in many different ways, so there's no need to pass an empty option in rsync_opts. But this seems to be a bit of unsafe code anyway.

##### STEPS TO REPRODUCE

use the following task:

```yaml
- name: Copy files locally on remote host
  synchronize:
    src: /tmp/src/
    dest: /tmp/dst
    rsync_opts:
      - ""
```
or 

```yaml
- name: Copy files locally on remote host
  synchronize:
    src: /tmp/src/
    dest: /tmp/dst
    rsync_opts:
      - "--exclude=whatever"
      - ""
```

##### EXPECTED RESULTS

only contents of /tmp/src are copied to /tmp/dst

##### ACTUAL RESULTS

everything from $PWD and from /tmp/src to /tmp/dst

```

```
