### ISSUE TITLE
"hostTypeIndex" is not being set correctly while a new host is created.

### ISSUE THREAD

**Issue by shanumondal** [ansible/ansible#39143]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

netapp_e_host.py
##### ANSIBLE VERSION

```
ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT

cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"

##### STEPS TO REPRODUCE

```yaml
 tasks:
   - name: Create Host Info
     netapp_e_host:
       ssid: "{{ ssid }}"
       api_url: "{{ netapp_api_url }}"
       api_username: "{{ netapp_api_username }}"
       api_password: "{{ netapp_api_password }}"
       name: host_test
       host_type_index: 7
       state: present
       group: hostgroup_test
```

##### EXPECTED RESULTS

The hostTypeIndex should have been set to 7.
##### ACTUAL RESULTS

 hostTypeIndex  is set to 0.

Detail output of the newly created host:

curl -X GET --header 'Accept: application/json' 'http://10.193.115.51:8080/devmgr/v2/storage-systems/controller1/hosts' 
```
  {
    "hostRef": "84000000600A09800060776B003010165ADC80C7",
    "clusterRef": "85000000600A09800060776B003610085AD7A5D7",
    "label": "host_test",
    "isSAControlled": true,
    "confirmLUNMappingCreation": false,
    "hostTypeIndex": 0,
    "protectionInformationCapableAccessMethod": true,
    "isLargeBlockFormatHost": false,
    "ports": [],
    "initiators": [],
    "hostSidePorts": [],
    "id": "84000000600A09800060776B003010165ADC80C7",
    "name": "host_test"
  }
```
