### ISSUE TITLE
Using set_fact and with_items yields unexpected result

### ISSUE THREAD

**Issue by jellevandehaterd** [ansible/ansible#39145]
##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = None
  configured module search path = [u'/Users/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/myuser/venv/lib/python2.7/site-packages/ansible
  executable location = /Users/myuser/Projects/ing/ansible-training-lab/tests/venv/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

"N/A"

##### OS / ENVIRONMENT

"N/A"

##### SUMMARY
Using set_fact and with_items to build up a new list does not work anymore, it results in only the last item of the with_items as a result. 

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  gather_facts: no
  connection: local
  vars:
    my_items:
      results:
        - { a: 1, b: x}
        - { a: 2, b: y}
        - { a: 3, b: z}
  tasks:
  - set_fact:
      myfact: "{{ myfact | default([]) + [ item.b ] }}"
    with_items: "{{ my_items.results }}"
  - debug:
      var: myfact
```

##### EXPECTED RESULTS
```
ok: [localhost] => {
    "myfact": [
        "x", 
        "y", 
        "z"
    ]
}
```

##### ACTUAL RESULTS
```
ok: [localhost] => {
    "myfact": [
        "z"
    ]
}
```
