### ISSUE TITLE
Adding strings to an array broken in 2.5.1

### ISSUE THREAD

**Issue by imjoseangel** [ansible/ansible#39156]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

set_fact module, array list creation

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /mnt/c/Users/JoseMar/Documents/Source/voyager-ops-infra/ansible.cfg
  configured module search path = [u'/home/imjoseangel/.ansible/library']
  ansible python module location = /home/imjoseangel/.local/lib/python2.7/site-packages/ansible
  executable location = /home/imjoseangel/.local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

ANSIBLE_COW_SELECTION(env: ANSIBLE_COW_SELECTION) = tux
ANSIBLE_NOCOLOR(env: ANSIBLE_NOCOLOR) = False
ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
ANSIBLE_SSH_ARGS(ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_CALLBACK_PLUGIN_PATH(ansible.cfg) = [u'plugins/callback', u'/home/imjoseangel/.ansible/plugins/callback', u'/usr/share/ansible/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH(ansible.cfg) = [u'plugins/filter', u'/home/imjoseangel/.ansible/plugins/filter', u'/usr/share/ansible/plugins/filter']
DEFAULT_GATHERING(ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(ansible.cfg) = merge
DEFAULT_HOST_LIST(ansible.cfg) = [u'inventories/local/hosts']
DEFAULT_LOOKUP_PLUGIN_PATH(ansible.cfg) = [u'plugins/lookup', u'/home/imjoseangel/.ansible/plugins/lookup', u'/usr/share/ansible/plugins/lookup']
DEFAULT_MANAGED_STR(ansible.cfg) = This file is managed by Ansible.%n
template: {file}
date: %Y-%m-%d %H:%M:%S
user: {uid}
host: {host}
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = [u'/home/imjoseangel/.ansible/library']
DEFAULT_ROLES_PATH(ansible.cfg) = [u'roles', u'/home/imjoseangel/.ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_STRATEGY(env: ANSIBLE_STRATEGY) = debug
DEFAULT_TRANSPORT(ansible.cfg) = smart
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/imjoseangel/.vault_pass.txt
HOST_KEY_CHECKING(ansible.cfg) = False
RETRY_FILES_ENABLED(ansible.cfg) = False

##### OS / ENVIRONMENT

Centos7

##### SUMMARY

Adding Array List strings replacing instead of merging

##### STEPS TO REPRODUCE

With this code, in 2.5.0 you got a list of roles. In 2.5.1, you get only the last one.

```yaml
          - name: Get the folders under roles path
            find:
              paths: "{{ base_dir }}/roles"
              file_type: directory
            register: _directories_stat

          - name: Include configure role
            debug:
              var: _directories_stat.files

          - name: Build roles folder list
            set_fact:
              roles_folder: "{{ roles_folder | default([]) + [ item.path | regex_replace(base_dir + '/roles/','') ] }}"
            with_items: "{{ _directories_stat.files }}"

```
Also check - https://www.jeffgeerling.com/blog/2017/adding-strings-array-ansible

##### EXPECTED RESULTS

A list of roles
##### ACTUAL RESULTS

Only the latest role

```
TASK [Set fact of the raet role name] *******************************************************************************************************************************************************************************************************
ok: [localhost -> localhost]

TASK [Set fact to apply the role] ***********************************************************************************************************************************************************************************************************
ok: [localhost -> localhost]

TASK [Include raet configure role] **********************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "roles_folder": [
        "wsus-client"
    ]
}
```
