### ISSUE TITLE
loop function can't process a list, treat it like string, with_items process it fine.  

### ISSUE THREAD

**Issue by alex-left** [ansible/ansible#39158]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

ansible, loop

##### ANSIBLE VERSION

```
ansible-playbook 2.5.0
  config file = /workdir/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Mar 14 2018, 18:16:04) [GCC 6.3.0 20170516]

```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

according to docs in 2.5 version, module loop accepts a list as argument, but process it like a string. using "with_items" as classical way, works fine

##### STEPS TO REPRODUCE

use a list in a variable: 

```yaml
  - debug: msg="{{ appservers_ids | type_debug }}"

  - debug: msg="{{ item }}"
    loop: "{{ appservers_ids }}"

  - debug: msg="{{ item }}"
    with_items: "{{ appservers_ids }}"
```
this is the output of the play:

```
TASK [debug] *********************************************************************************************************************************************************************************************************************************
task path: /workdir/utils/create-instances.yml:54
ok: [awsadmin] => {
    "msg": "list"
}

TASK [debug] *********************************************************************************************************************************************************************************************************************************
task path: /workdir/utils/create-instances.yml:56
ok: [awsadmin] => (item=None) => {
    "msg": [
        "i-023e1230d0827f403", 
        "i-078b4c28cba55bfab"
    ]
}

TASK [debug] *********************************************************************************************************************************************************************************************************************************
task path: /workdir/utils/create-instances.yml:59
ok: [awsadmin] => (item=None) => {
    "msg": "i-023e1230d0827f403"
}
ok: [awsadmin] => (item=None) => {
    "msg": "i-078b4c28cba55bfab"
}

```

##### EXPECTED RESULTS

loop must treat the variable as a list. 

##### ACTUAL RESULTS

fail in any task using the loop function. for example:

```
TASK [add instances to  target group] ************************************************************************************************************************************************************************************************
task path: /workdir/utils/create-instances.yml:57
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/amazon/elb_target.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_DrtjDT/ansible_module_elb_target.py", line 146, in describe_targets
    targets = connection.describe_target_health(TargetGroupArn=tg_arn, Targets=target)['TargetHealthDescriptions']
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (ValidationError) when calling the DescribeTargetHealth operation: Target ID '['i-023e1230d0827f403', 'i-078b4c28cba55bfab']' is not valid

failed: [awsadmin] (item=[u'i-023e1230d0827f403', u'i-078b4c28cba55bfab']) => {
    "changed": false, 
    "error": {
        "code": "ValidationError", 
        "message": "Target ID '['i-023e1230d0827f403', 'i-078b4c28cba55bfab']' is not valid", 
        "type": "Sender"
    }, 
    "invocation": {
        "module_args": {
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "deregister_unused": false, 
            "ec2_url": null, 
            "region": "eu-west-1", 
            "security_token": null, 
            "state": "present", 
            "target_az": null, 
            "target_group_arn": null, 
            "target_group_name": "staging-appservers", 
            "target_id": "['i-023e1230d0827f403', 'i-078b4c28cba55bfab']", 
            "target_port": null, 
            "target_status": null, 
            "target_status_timeout": 60, 
            "validate_certs": true
        }
    }, 
    "item": [
        "i-023e1230d0827f403", 
        "i-078b4c28cba55bfab"
    ], 
    "msg": "Unable to describe target health for target [{'Id': \"['i-023e1230d0827f403', 'i-078b4c28cba55bfab']\"}]: An error occurred (ValidationError) when calling the DescribeTargetHealth operation: Target ID '['i-023e1230d0827f403', 'i-078b4c28cba55bfab']' is not valid", 
    "response_metadata": {
        "http_headers": {
            "connection": "close", 
            "content-length": "334", 
            "content-type": "text/xml", 
            "date": "Mon, 23 Apr 2018 13:40:32 GMT", 
            "x-amzn-requestid": "e4e134c4-46fb-11e8-8b7b-4f3b7f383e5b"
        }, 
        "http_status_code": 400, 
        "request_id": "e4e134c4-46fb-11e8-8b7b-4f3b7f383e5b", 
        "retry_attempts": 0
    }
}


```

**Comment by sivel** [comment]
How is `appservers_ids` created?

I cannot duplicate this using a statically defined list.

needs_info

**Comment by bcoca** [comment]
note that `with_items` has an implied flatten, `with_list` and `loop` do not.

**Comment by alex-left** [comment]
@bcoca I don't know what do you want to mean. what's the difference between both? can you give me an example?
@sivel ```appservers_ids``` are created from the json result of a previous task using ec2 module, the intention in this case is create some instances and after add them into target group. I paste you how make this:

```yaml

## this is the instances creator (this task works fine) and store the result:
  - name: launch instances
    register: instance_amibuilder
    with_items:
    - "{{ instances }}"
    ec2:
      region: "{{ aws_region }}"
      profile: "{{ aws_profile }}"
      key_name: "{{ aws_keypair }}"
      instance_type: "{{ item.type }}"
      image: "{{ ami_base_latest.results[0].ami_id }}"
      wait: yes
      monitoring: "{{ item.enabled_monitoring | default('no') }}"
      private_ip: "{{ item.private_ip | default(omit) }}"
      group: "{{ item.secgroups }}"
      count_tag: "{{ item.count_tag }}"
      exact_count: "{{ item.count }}"
      vpc_subnet_id: "{{ vpc_subnet_id }}"
      assign_public_ip: yes
      instance_tags: "{{ item.tags }}"
      volumes: "{{ item.volumes | default(omit) }}"
 
# now I use the json query filter to extract the needed values from the result, this return a list with instances ids, as you can check in my first message:
  - set_fact:
      appservers_ids: "{{ instance_amibuilder | json_query(appservers_pattern) }}"
```

You say you can't reproduce with a statically defined list. Are you tried to define it in json format or only yaml? The question is (I think) why the variable is treated like a literal string instead a list??  Maybe the problem is in the json filter in place of the loop function?

**Comment by sivel** [comment]
I am still unable to reproduce.  Here is my test playbook:

```yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    thing:
       - i-023e1230d0827f403
       - i-078b4c28cba55bfab
    diff_thing:
      - key: i-023e1230d0827f403
      - key: i-078b4c28cba55bfab
  tasks:
    - debug: msg={{item}}
      loop: "{{ thing }}"

    - set_fact:
        loop_thing: "{{ diff_thing | json_query('[].key') }}"

    - debug: msg={{item}}
      loop: "{{ loop_thing }}"
```

The above defines both a static list, and a static list of dicts.  I utilized `json_query` to turn the list of dicts into just a list.

In both scenarios I get:

```
TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=None) => {
    "msg": "i-023e1230d0827f403"
}
ok: [localhost] => (item=None) => {
    "msg": "i-078b4c28cba55bfab"
}

TASK [set_fact] ******************************************************************************************************************************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"loop_thing": ["i-023e1230d0827f403", "i-078b4c28cba55bfab"]}, "changed": false}

TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => (item=None) => {
    "msg": "i-023e1230d0827f403"
}
ok: [localhost] => (item=None) => {
    "msg": "i-078b4c28cba55bfab"
}
```

Is it possible you can test with my playbook from above?

needs_info

**Comment by bcoca** [comment]
`with_items: '{{mylist}}'` == `loop: {{mylist|flatten(1)}}` == `with_list: '{{mylist|flatten(1)}}'`

`loop` is not the equivalent of `with_items` but of `with_list`, `lookup('items')` does 1 level of 'flattening'

@sivel you can reproduce with:
```
   thing:
     - [i-023e1230d0827f403, i-078b4c28cba55bfab]
     - [i-024e1230d0827f403, i-34543c28cba55bfab]
```

**Comment by sivel** [comment]
@alex-left also, please provide us with the output of:

```
- debug:
    var: appservers_ids
```

needs_info

**Comment by alex-left** [comment]
ok, with flatten filter seems work it fine. 
But... this is a workaround or is the expected behavior?

**Comment by sivel** [comment]
> ok, with flatten filter seems work it fine.
> But... this is a workaround or is the expected behavior?

This is the expected behavior.  `with_items` contains implicit flattening.

`loop` is more comparable to `with_list`.  To loop and flatten a list, you will need to use `flatten` as @bcoca points out

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

**Comment by alex-left** [comment]
hi @sivel @bcoca  this is the output of last proposed task:
```
TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [awsadmin] => {
    "appservers_ids": [
        [
            "i-023e1230d0827f403", 
            "i-078b4c28cba55bfab"
        ]
    ]
}
```
I understand the problem, after use of json_query filter, I expected a list, but received a list into a list. with_items keywords can operate with that because haves implicit a flatten, but "loop" doesn't have it, that difference confused me. 

Anyway, I think is a good idea mention that in docs. 

thanks to both.

**Comment by Testicule** [comment]
OMG yeah thanks a hell of a lot to whoever decided to get rid of with_items and so on, and replace with "loop".

Now we have a completely undocumented new way of doing loops in ansible.

There might be some info out there, other people bashing their brains out against the brick wall this has put in everyone's way. But it's impossible to google. Try googling for "loop" in relation to anything and see what you get - it's a mess of unusable results. Before, there was a distinction between the various with_ flavours, and you could tease out what you were after from the google results. Now... impossible. Now everything is a "loop", noone will ever be able to make sense of it.

I've just been trying to convert some of my with_items loops to "loop" loops, and have been pulling my hair out, until i discovered loop seems utterly worthless at multiple lists. 

Where i had blah1 and blah2 being lists of dicts, i was able to do:
  with_items:
     - blah1
     - blah2
it works.

When i try to switch to:
  loop:
   - blah1 
   - blah2
it fails utterly, no matter what i do, trying to flatten those lists/dicts, whether i use flatten, json_query, dict2items, whatever. Nothing worked, until i gave up trying to work with 2 lists, and switched to just one list, on same line as loop, ie this is no good:

loop:
   - blah

it has to be:

loop: blah

Thanks everyone. Great work. Well done.

**Comment by AdamGoldsmith** [comment]
@Testicule I too feel your pain to a degree. In your example above where you resorted back to one single list, I was able to overcome this with the following code, but I do not like how it looks, I would prefer each referenced list on a newline as it is when using `with_items` :

```
with_items:
  - "{{ blah1 }}"
  - "{{ blah2 }}"
```
replaced by
```
loop:
  "{{ blah1 + blah2 }}"
```

**Comment by bcoca** [comment]
This would be the equivalent of `with_items`

```yaml
loop: '{{mydicts|flatten(1)}}'
vars:
  mydicts:
     - blah1
      - blah2
```
