### ISSUE TITLE
Conditional with colon in quoted text throws unclear error

### ISSUE THREAD

**Issue by gtirloni** [ansible/ansible#39154]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
conditionals

##### ANSIBLE VERSION
2.5.1

##### OS / ENVIRONMENT
CentOS 7.4

##### SUMMARY
If a conditional has a colon character in quotes, it throws the following cryptic error:

```
ERROR! Syntax Error while loading YAML.
  mapping values are not allowed here

The error appears to have been in '/path/to/role/tasks/main.yml': line 36, column 63, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  failed_when: false
  changed_when: yum_lock_output.stdout.find('versionlock added: 1') == 1
                                                              ^ here
```

##### STEPS TO REPRODUCE
```yaml
- name: Unlock package version
  command: yum versionlock delete nginx
  failed_when: false
  changed_when: yum_lock_output.stdout.find('versionlock added: 1') == 1
  register: yum_lock_output
  args:
    warn: false
```

Double-quoting the whole conditional fix the issue:

```yaml
- name: Unlock package version
  command: yum versionlock delete nginx
  failed_when: false
  changed_when: "yum_lock_output.stdout.find('versionlock added: 1') == 1"
  register: yum_lock_output
  args:
    warn: false
```

Additionally, the documentation doesn't mention conditional needs to be quoted and all examples are unquoted (http://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html)
