### ISSUE TITLE
Bug in win_get_url

### ISSUE THREAD

**Issue by Gianlu** [ansible/ansible#39151]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
win_get_url

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = False
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/modules']
##### SUMMARY
Win_get_url module downloads and modifies a file also when force=no and specific conditions stated in documentation are met.

##### STEPS TO REPRODUCE

```yaml
---
- name: deploy file
  hosts: windows
  serial: "{{ parallelism | default(100)  }}"
  gather_facts: yes
  vars:
     targetdir: "{{ ansible_env.windir }}\\mydir"
     scripturl: "http://myserver/configurations/myfile.txt"
     scriptfile: "myfile.txt"

  tasks:
    - name: Create directory
      win_file:
         state: directory
         path: "{{ targetdir }}"

    - name: Download script file
      win_get_url:
        url: "{{ scripturl }}"
        dest: "{{ targetdir }}\\{{ scriptfile }}"
        force: no
```

##### EXPECTED RESULTS

remote timestamp: 2018/04/23 10:13:00
local lastwritetime: 2018/04/23 12.11:00
the module doesn't download the file

##### ACTUAL RESULTS

the module downloads the file

```
changed: true
```
