### ISSUE TITLE
Passing environment not working with include_role

### ISSUE THREAD

**Issue by joaogbcravo** [ansible/ansible#39185]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
ansible 2.5.1
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
Passing environment vars when using "include_role" does not work.
This worked before, in version 2.4.1.0 for example.
With "import_role" also works.

##### STEPS TO REPRODUCE

Create a directory with the following structure:
```
.
├── playbook.yml
└── simple_role
    └── tasks
        └── main.yml
```

playbook.yml
```yaml
- hosts: localhost
  gather_facts: False
  tasks:
    - shell: ansible --version
      register: ansible

    - debug: var=ansible.stdout_lines[0]

    - import_role:
        name: simple_role
      environment:
        import_works: Foo

    - include_role:
        name: simple_role
      environment:
        include_works: Bar
```

simple_role/tasks/main.yml
```
- debug: msg="{{ environment }}"
```

##### EXPECTED RESULTS

Should print environment variables with "include_task", like "import_task".

```
ok: [localhost] => {
    "msg": [
        {
            "include_works": "Bar"
        }
    ]
}
```

##### ACTUAL RESULTS
It prints an empty list instead

```
PLAY [localhost] **************************************************************************

TASK [shell] ******************************************************************************
changed: [localhost]

TASK [debug] ******************************************************************************
ok: [localhost] => {
    "ansible.stdout_lines[0]": "ansible 2.5.1"
}

TASK [simple_role : debug] ******************************************************************
ok: [localhost] => {
    "msg": [
        {
            "import_works": "Foo"
        }
    ]
}

TASK [include_role] *************************************************************************

TASK [simple_role : debug] ******************************************************************
ok: [localhost] => {
    "msg": []
}

PLAY RECAP *******************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0

```
