### ISSUE TITLE
Windows10-Ubuntu - Ansible doesn't recognize variables defined in vars_prompt.

### ISSUE THREAD

**Issue by eregimbald** [ansible/ansible#39184]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vars_prompt

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/eregimbald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
[defaults]
display_skipped_hosts = false
log_path=/var/log/ansible
roles_path=/etc/ansible/roles
inventory=my.hosts
retry_files_enabled = False
```
##### OS / ENVIRONMENT

Windows 10 - Version 10.0.16299 Build 16299

Ubuntu from the Windows App store:
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

##### SUMMARY

I can't prompt the user for a hostname or group name, then use this variable as the host "targets" for the playbook. When I try, I get an error telling me that the "target" variable is undefined.

However, I've tried this method on Mac OSX, native Ubuntu and Centos and it works.

##### STEPS TO REPRODUCE

```
---
- name: Configure Network
  gather_facts: no
  connection: local
    
  vars_prompt:
    - name: "target"
      prompt: "Enter host or inventory group"
      private: no

  hosts: "{{target}}"
  tasks:
      debug: msg="hello"
```

##### EXPECTED RESULTS

I expected the playbook to run on the host I typed it when I was prompted.

##### ACTUAL RESULTS

```
ansible-playbook 2.5.0
  config file = /mnt/c/Users/eregimbald/Documents/github/network-ansible/ansible.cfg
  configured module search path = [u'/home/eregimbald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /mnt/c/Users/eregimbald/Documents/github/network-ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /mnt/c/Users/eregimbald/Documents/github/network-ansible/my.hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: configure-network.yml ****************************************************************************************
1 plays in configure-network.yml
ERROR! The field 'hosts' has an invalid value, which includes an undefined variable. The error was: 'target' is undefined

The error appears to have been in '/mnt/c/Users/eregimbald/Documents/github/network-ansible/configure-network.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Configure Network
  ^ here
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by webknjaz** [comment]
-label needs_triage

**Comment by carslen** [comment]
Noticed the same problem with 2.5.0 why I had a rollback to Ansible 2.4. 
Ansible Controlhost = CentOS 7.4

```yaml
- name: Deploy TM1 Perfomance Monitor
  hosts: "{{ inventory }}"

  vars_prompt:
    - name: "inventory"
      prompt: "For what hosts?"
      private: no
    - name: "role"
      prompt: "Which role to execute?"
      private: no
  
  tasks:
    - include_role:
        name: "{{ role }}"
```

**Comment by eregimbald** [comment]
I rolled back to 2.4, now the host prompter works but the role prompter is broken.

```
---
- name: Configure Network
  gather_facts: no
  connection: local
  vars:
    playbook: Configure Network

  vars_prompt:
    - name: "target"
      prompt: "Enter host or inventory group"
      private: no
    - name: "commit"
      prompt: "Do you want to commit? (True or False)"
      default: "False"
      private: no
    - name: "role"
      prompt: "Enter configuration role (Commit-False only)"
      private: no
      default: "next-gen/interfaces"
    - name: "comment"
      prompt: "Enter a commit comment"
      private: no

  hosts: "{{target}}"

  tasks:
    - block:
      - include_role:
          name: Juniper.junos
      - include_role:
          name: base/workcomplete
      - include_role:
          name: base/cleanup-create
      - include_role:
          name: "{{role}}"
      - include_role:
          name: junos/junos-assemble-apply
      - include_role:
          name: base/show-compare
      rescue:
      - include_role:
          name: base/workfailed
```

CLI:

```
eregimbald@eregimbald-m1:~/github/network-ansible$ ansible-playbook configure-network.yml -vvvv
ansible-playbook 2.4.0.0
  config file = /mnt/c/Users/eregimbald/Documents/github/network-ansible/ansible.cfg
  configured module search path = [u'/home/eregimbald/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /mnt/c/Users/eregimbald/Documents/github/network-ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /mnt/c/Users/eregimbald/Documents/github/network-ansible/fuze.hosts inventory source with ini plugin
ERROR! 'role' is undefined
eregimbald@eregimbald-m1:~/github/network-ansible$
```
