### ISSUE TITLE
List appending stopped working

### ISSUE THREAD

**Issue by jreisinger** [ansible/ansible#39214]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /home/user/.ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/home/user/.ansible.cfg) = [u'/home/user/inventory']
DEFAULT_ROLES_PATH(/home/user/.ansible.cfg) = [u'/home/user/ansible-roles']
DEFAULT_STDOUT_CALLBACK(/home/user/.ansible.cfg) = debug
DEPRECATION_WARNINGS(/home/user/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/user/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
Linux host 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### SUMMARY
I can't append items to a list. It used to work in the previous versions.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost
  gather_facts: no
  tasks:

    - name: Declare variable - an empty list
      set_fact:
        ports: []

    - name: Append items to list
      set_fact:
        ports: "{{ ports }} + [ '{{ item }}' ]"
        #ports: "{{ ports  + [ item ] }}"
      with_items:
        - 22
        - 23
        - 24

    - debug:
        msg: "{{ ports  }}"
```

##### EXPECTED RESULTS

```
TASK [debug] ******************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false, 
    "msg": [
        "22", 
        "23", 
        "24"
    ]
}
```
##### ACTUAL RESULTS

```
TASK [debug] *********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "msg": [
        24
    ]
}
```
