### ISSUE TITLE
zabbix_template: import XML files exported from Zabbix web interface

### ISSUE THREAD

**Issue by selivan** [ansible/ansible#39220]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

zabbix_template

##### ANSIBLE VERSION

```
ansible 2.5.1
```
##### SUMMARY

zabbix_template module can import templates from json files, exported by the same module.

It would be much more convenient, if it could also import templates from xml files, exported from Zabbix web interface.

##### STEPS TO REPRODUCE

```yaml
- name: Import Zabbix json template configuration
  local_action:
    module: zabbix_template
    server_url: http://127.0.0.1
    login_user: username
    login_password: password
    template_name: Apache2
    template_xml: "{{ lookup('file', 'zabbix_apache2.xml') }}"
    template_groups:
      - Webservers
    state: present
```

##### EXPECTED RESULTS

Ability to import templates from Zabbix web interface and use them with Ansible.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/zabbix/zabbix_template.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/zabbix/zabbix_template.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Logan2211 @eikef @logan2211 @sookido
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @D3DeFi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by D3DeFi** [comment]
Hi @selivan, would you be interested in contributing this feature via PR? I prolly won't have a time for its implementation in the near future. `state: dump` should still be reserved for returning a JSON object tho

Btw can we close your older issue #38986 as it is duplicate of this one?

**Comment by selivan** [comment]
Hi @D3DeFi, I do not have time for it now, but it may be an interesting task to refresh my python knowledge. I'll try to do it when I have time.

Yes, #38986 is a duplicate, I forgot that I already reported this :) Closed it.

**Comment by ansibot** [comment]
cc @rubentsirunyan
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by D3DeFi** [comment]
Good thing ansibot brought this back to our attention. If I remember correctly, we had one PR and one new module for this functionality proposed in the past, but both things missed some finishing touches and got closed with information that they will be reopened shortly as new PRs from their original authors. 

I can now see that it unfortunately did not happen. I will try to find some additional time to implement this in the upcoming days.

**Comment by D3DeFi** [comment]
@selivan @vzabawski would you mind giving #59040 a quick test to see if import/export works for you as well?

**Comment by selivan** [comment]
@D3DeFi  I check it out. It has an error. Test playbook:

```yaml
- hosts: localhost
  vars:
    export: no
  tasks:
    - name: test export
      zabbix_template:
        server_url: http://127.0.0.1/zabbix
        login_user: admin
        login_password: zabbix
        template_name: "Template OS Linux"
        state: dump
        dump_format: xml
      register: dump
      when: export | bool
    - name: write to file
      copy: dest=/home/vagrant/dump.xml content="{{ dump.template_xml }}"
      when: export | bool
    - name: test import
      zabbix_template:
        server_url: http://127.0.0.1/zabbix
        login_user: admin
        login_password: zabbix
        template_xml: "{{ lookup('file', '/home/vagrant/dump.xml') }}"
        template_groups:
          - "Templates/Operating Systems"
        state: present
```

Exported XML file looks like this:

```xml
<?xml version="1.0" ?>
<********_export>
    <version>4.2</version>

...

</********_export>
```

So import doesn't work. When I manually change `********` to `zabbix`, import works.

Great job! After fixing this bug it can be merged.

**Comment by D3DeFi** [comment]
First of all, thank you very much for testing @selivan . Behavior you're seeing should be caused by `login_password`, specifically enabled option `no_log=True`, which then as it seems hides such string from every output presented to user or system logs.

This is usually not a problem as passwords are strings composed from random characters, numbers, etc.. , but in this case it is just plain word 'zabbix'. I've tried to search other modules on how this is handled, but there seems to be no such option to make an exception for a specific output. 

This logic resides in both common methods for exiting out of modules (`exit_json`, `fail_json`). They make a call to method `_return_formatted()`, which then **always** calls `remove_values(kwargs, self.no_log_values)` without any condition (this [link ](https://github.com/ansible/ansible/blob/8d6f1846a6ff96ef7ea9caf3868e8cb86e9ac9a0/lib/ansible/module_utils/basic.py#L2039)for reference).

Using `no_log: False` on the ansible task itself may be one way to fix it. I, unfortunately, don't have a time right now to start my testing env and dive into this:
```yaml
- name: test export
  zabbix_template:
    server_url: http://127.0.0.1/zabbix
    login_user: admin
    login_password: zabbix
    template_name: "Template OS Linux"
    state: dump       
    dump_format: xml
  register: dump

- copy:
    content: '{{ dump }}'
    dest: /tmp/dump
  no_log: False
```

Or better solution is not to use `zabbix` as a password for Admin, but I am using that pass as well for testing, because I am too lazy to change it every time :)

Btw, here is an example how it affects module failure too:
```bash
fatal: [zbx-dev-node002]: FAILED! => changed=false
  msg: 'Missing required ********-api module (check docs or install with: pip install ********-api)'
```
My guess is that it does not affect `template_json`, beacause it is `type=json`, which probably gets some kind of immunity. This unfortunately cannot be the case for xml as it is not recognized as a standalone argument type in AnsibleModule `argument_spec`.

I will try to search for some other solutions later.

**Comment by selivan** [comment]
@D3DeFi Now that's a funny error :)

I don't think it is easy to fix without changing a lot of things inside ansible. Though I can suggest improvement, that might help with this problem as well.

I suppose in 99% of using `zabbix_template` with `state=dump` output is saved to file. Now it requires additional steps: save module execution result, call copy or template module to write it to file. Would be nice to have an option like `dest` to provide direct path to save the output. This will make plays shoter, and this file won't be affected by any ansible filters.

:beetle: Here is another bug: export does not work with non-ASCII(cyrillic) text. 

Test playbook:

```yaml
- hosts: localhost
  vars:
    export: yes
  tasks:
    - name: test export
      zabbix_template:
        server_url: http://127.0.0.1/zabbix
        login_user: Admin
        login_password: qwerty
        template_name: "Template OS Linux"
        state: dump
        dump_format: xml
      register: dump
      when: export | bool
    - name: write to file
      copy: dest=/home/vagrant/dump.xml content="{{ dump.template_xml }}"
      when: export | bool
    - name: test import
      zabbix_template:
        server_url: http://127.0.0.1/zabbix
        login_user: Admin
        login_password: qwerty
        template_xml: "{{ lookup('file', '/home/vagrant/dump.xml') }}"
        template_groups:
          - "Templates"
        state: present
```

Trigger "/etc/passwd has been changed on {HOST.NAME}" was renamed to "/etc/passwd has been changed on {HOST.NAME} тест тест".

Error:

```
TASK [test export] *******************************************************************************************************************************************
task path: /home/vagrant/test.yml:5
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: UnicodeEncodeError: 'ascii' codec can't encode characters in position 57566-57569: ordinal not in range(128)
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1563091875.3-61801651525881/AnsiballZ_zabbix_template.py\", line 125, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1563091875.3-61801651525881/AnsiballZ_zabbix_template.py\", line 117, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1563091875.3-61801651525881/AnsiballZ_zabbix_template.py\", line 54, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_zabbix_template_payload_FW5Rr3/__main__.py\", line 742, in <module>\n  File \"/tmp/ansible_zabbix_template_payload_FW5Rr3/__main__.py\", line 689, in main\n  File \"/tmp/ansible_zabbix_template_payload_FW5Rr3/__main__.py\", line 458, in dump_template\n  File \"/usr/lib/python2.7/xml/dom/minidom.py\", line 1928, in parseString\n    return expatbuilder.parseString(string)\n  File \"/usr/lib/python2.7/xml/dom/expatbuilder.py\", line 940, in parseString\n    return builder.parseString(string)\n  File \"/usr/lib/python2.7/xml/dom/expatbuilder.py\", line 223, in parseString\n    parser.Parse(string, True)\nUnicodeEncodeError: 'ascii' codec can't encode characters in position 57566-57569: ordinal not in range(128)\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Here is readable gist with fixed newlines: https://gist.github.com/selivan/a2522e9b11bb5c8133d0a34c6af80b6d

To be fair, json export works with serious bug for non-ASCII characters(https://github.com/ansible/ansible/issues/55439), but at least it does not fail and you can fix incorrect characters by other tools.
