### ISSUE TITLE
Combine filter doesn't work with_items in version 2.5.1

### ISSUE THREAD

**Issue by sidorm01** [ansible/ansible#39226]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

combine

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/xxx/git/ansiblemodules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 26 2018, 11:16:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A
##### SUMMARY
Combine filter change its behaviour with version 2.5.1 when using with_items. 

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  vars:
    some_value: 12345
    dict: {}
  tasks:
  - set_fact:
      dict: "{{ dict | combine( { item: some_value } ) }}"
    with_items:
      - 1
      - 2
      - 3
  - debug: msg="{{ dict }}"
```

##### EXPECTED RESULTS

TASK [debug]
*******************************************************************
ok: [localhost] => {
    "msg": {
        "1": "12345",
        "2": "12345",
        "3": "12345"
    }
}
##### ACTUAL RESULTS

```
TASK [debug]
*******************************************************************
ok: [localhost] => {
    "msg": {
        "3": "12345"
    }
}
```
