### ISSUE TITLE
Have option to create Network Interface without NSG rule changes

### ISSUE THREAD

**Issue by vogon1** [ansible/ansible#39231]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### SUMMARY
In the default case, when creating a NIC the module tries to manage NSG rules. We already have a NSG with the correct rules in place, so it should just use the NSG given, and not try to add or change rules.

So, maybe a flag should be added like

  manage_nsg_rules: false

ion order to prevent changing the content of a NSG.

##### ACTUAL RESULTS
```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
@vogon1 As my understanding, you want to add a feature to attach an existing NSG to NIC? There is a PR just been merged, you can have a try according to the instruction in this PR #39213 , to see whether it is the feature you want.

Maybe your playbook should like this
```yaml
- name: Create NIC with existing NSG
  azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: testnic001rg
      virtual_network: testnic001
      subnet: testnic001
      public_ip_name: testnic001
      public_ip_allocation_method: Static
      security_group: "{{ your_existing_nsg_name }}"
```

**Comment by vogon1** [comment]
@yuwzho Thanks for your response.
I am already using the code from pr #39213 and I am happy with that.

However, the module still tries to do something with the security group. As I have no rights on the security group, I get a permission denied. My guess is it tries to add port 22 to the NSG for my linux VM; the only way to prevent that is to define open_ports, but then it wants to add those ports to the NSG. In my case, I don't want it to access the security group, it should just use it.

To get it to work, I commented out the following section in azure_rm_networkinterface.py:

```
#                nsg = nsg or self.create_default_securitygroup(self.resource_group,
#                                                               self.location,
#                                                               self.security_group_name or self.name,
#                                                               self.os_type,
#                                                               self.open_ports)
```

That makes it work for me.

That is why I requested a flag to prevent making changes to the NSG.

**Comment by yuwzho** [comment]
@vogon1 Why your code looks different with the devel branch?

If you want to try the latest bit, you can run the following command:

```bash
pip install git+https://github.com/ansible/ansible.git@devel
```

and my playbook is as following, the NSG will not be updated when I create NIC.

```yml
---
- hosts: localhost
  vars:
    resource_group: yuwzhotest
  tasks:
   - name: create resource_group
     azure_rm_resourcegroup:
       name: "{{ resource_group }}"
       location: eastus
   - name: Create security group
     azure_rm_securitygroup:
       resource_group: "{{ resource_group }}"
       name: mysecgroup
       tags:
          testing: testing
          delete: on-exit
          foo: bar
       purge_rules: yes
       rules:
          - name: DenySSH
            protocol: Tcp
            destination_port_range: 22
            access: Deny
            priority: 100
            direction: Inbound
          - name: AllowSSH
            protocol: Tcp
            source_address_prefix: 174.109.158.0/24
            destination_port_range: 22
            access: Allow
            priority: 101
            direction: Inbound
   - name: Create network interface
     azure_rm_networkinterface:
        resource_group: "{{ resource_group }}"
        name: testnic001rg
        virtual_network: testnic001
        subnet: testnic001
        public_ip_name: testnic001
        public_ip_allocation_method: Static
        security_group: mysecgroup
```

**Comment by vogon1** [comment]
@yuwzho 

After updating to the devel version, the problem still occurs. 
New version:

```
ansible@azansible:/etc/ansible$ ansible --version
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

This is the response I get when creating a NIC (ID's replaced by xx yy zz):

TASK [azure_vm : Create virtual network interface card] ***************************************************************************************************************
- fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating default security rule NSG-D01-WE-RHD-BACK - Azure Error: AuthorizationFailed\nMessage: The client 'xx' with object id 'yy' does not have authorization to perform action 'Microsoft.Network/networkSecurityGroups/write' over scope '/subscriptions/zz/resourceGroups/RG-D01-APP-RHD-002/providers/Microsoft.Network/networkSecurityGroups/NSG-D01-WE-RHD-BACK'."}

When removing the create_default_securitygroup call in azure_rm_networkinterface.py it works:

```
#                nsg = self.create_default_securitygroup(self.resource_group,
#                                                        self.location,
#                                                        self.security_group_name,
#                                                        self.os_type,
#                                                        self.open_ports)
```

This is the task:

```
- name: Create virtual network interface card
  azure_rm_networkinterface:
    security_group_name: "{{ nsg_name }}"
    resource_group: "{{ rg_name }}"
    name: "{{ vm_name }}"
    virtual_network_resource_group: "{{ vnet_rg }}"
    virtual_network: "{{ vnet_name }}"
    subnet_name: "{{ subnet_name }}"
    public_ip: false
    ip_configurations:
    - name: "{{ vm_name }}_private"
      private_ip_allocation_method: "{{ private_ip_allocation_method }}"
      private_ip_address: "{{ private_ip_address }}"

```
