### ISSUE TITLE
replace argument for nso_config module

### ISSUE THREAD

**Issue by kecorbin** [ansible/ansible#39278]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

nso_config

##### ANSIBLE VERSION
```
ansible 2.5.0
```

##### CONFIGURATION

Default Configuration

##### OS / ENVIRONMENT

Ansible running on Mac controlling NSO 4.5.3

##### SUMMARY
nso_config module does not appear to have the ability to completely replace configuration that is in the CDB. instead,  data that is sent through the module is patched in with config that exists in the NSO CDB.  

In some scenarios, it may be desirable for the playbook to represent the source of truth. And replace NSO config atomically.

##### STEPS TO REPRODUCE

Assume the following config is in the CDB
```yaml
  tailf-ned-cisco-ios-xr:interface:
    Loopback:
    - description: router id
      id: 0
      ipv4:
        address:
          ip: 192.168.255.1
          mask: 255.255.255.255
    - description: bgp network
      id: 1
      ipv4:
        address:
          ip: 10.0.1.1
          mask: 255.255.255.0

```

##### EXPECTED RESULTS

it would be desirable for a flag in which running nso_config with the following data should remove loopback1 from the cdb. 

```yaml
   tasks:
    - name: Device configuration
      nso_config:
        data:
          tailf-ncs:devices:
            device:
            - name: "{{ inventory_hostname }}"
              tailf-ncs:config:
                tailf-ned-cisco-ios-xr:interface:
                  Loopback:
                  - description: router id
                    id: 0
                    ipv4:
                      address:
                        ip: 192.168.255.1
                        mask: 255.255.255.255         
```

##### ACTUAL RESULTS

Loopback1 remains
