### ISSUE TITLE
aws_s3 is automaticly decrypting ansible-vault encrypted files before put

### ISSUE THREAD

**Issue by glisha** [ansible/ansible#39287]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aws_s3

##### ANSIBLE VERSION

```
2.5.1
```

##### SUMMARY
- I'm trying to upload an ansible-vault encrypted file with aws_s3. But aws_s3 decrypts the src: file before uploading it to S3. 
- aws_s3 in 2.4 didn't decrypt the src: parameter.
- The documentation for aws_s3 doesn't mention that the src: parameter is autodecrypted.
- The aws_s3 module doesn't accept the decrypt: argument.

##### STEPS TO REPRODUCE

```yaml
- name: upload vault to s3
  aws_s3:
    bucket: "the bucket"
    object: "file.txt"
    src: "file.txt"
    mode: put
```
1. The file.txt is encrypted with ansible-vault. 
2. The playbook that runs this task is invoked with --vault-password and is able to decrypt the file because other tasks need the file decrypted.

##### EXPECTED RESULTS
Don't autodecrypt the src: argument or be able to specify decrypt: no.

##### ACTUAL RESULTS
The src: argument to aws_s3 is automagicly decrypted without documentation or a way to disable the feature like other modules (ex. copy).
