### ISSUE TITLE
Grafana_dashboard error when trying to import

### ISSUE THREAD

**Issue by shanep2300** [ansible/ansible#39295]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

grafana_dashboard

##### ANSIBLE VERSION

```
2.5.1
```

##### OS / ENVIRONMENT

CentOS

##### SUMMARY

Module error when trying to import dashboard into Grafana.

##### STEPS TO REPRODUCE

```yaml
- name: Import dashboard into Grafana
  grafana_dashboard:
    grafana_url: http://localhost:8086
    grafana_user: "{{ grafana_admin_user|quote }}"
    grafana_password: "{{ grafana_admin_password|quote }}"
    state: present
    message: Updated by ansible
    overwrite: yes
    path: /home/centos/grafana-dashboards/JMeter_Results_by_Project.json
```

##### EXPECTED RESULTS

Json file gets imported into Grafana.

##### ACTUAL RESULTS

See error below.

```
amazon-ebs: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: send() got multiple values for keyword argument 'MESSAGE'

    amazon-ebs: fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_e_tueC/ansible_module_grafana_dashboard.py\", line 335, in <module>\n    main()\n  File \"/tmp/ansible_e_tueC/ansible_module_grafana_dashboard.py\", line 299, in main\n    mutually_exclusive=[['grafana_user', 'grafana_api_key']],\n  File \"/tmp/ansible_e_tueC/ansible_modlib.zip/ansible/module_utils/basic.py\", line 909, in __init__\n  File \"/tmp/ansible_e_tueC/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2191, in _log_invocation\n  File \"/tmp/ansible_e_tueC/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2152, in log\nTypeError: send() got multiple values for keyword argument 'MESSAGE'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/grafana_dashboard.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/grafana_dashboard.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @tsalle
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rrey** [comment]
Hi @shanep2300,

Can you specify the Grafana version you are using ?
I checked the error message and the code, the problem comes from this snippet in `module_utils/basic.py` :

```
            if has_journal:
                journal_args = [("MODULE", os.path.basename(__file__))]
                for arg in log_args:
                    journal_args.append((arg.upper(), str(log_args[arg])))
                try:
                    journal.send(u"%s %s" % (module, journal_msg), **dict(journal_args))
                except IOError:
                    # fall back to syslog since logging to journal failed
                    self._log_to_syslog(syslog_msg)
```

I didn't reproduce the issue, but based on the code, I wonder if the `message` parameter from the grafana_dashboard module is not conflicting with another `MESSAGE` variable when being updated to uppercase during the iteration over `log_args`.

cc @bcoca author of the code portion.

**Comment by shanep2300** [comment]
grafana-5.1.2-1.x86_64

We found a workaround by using provisioning.
http://docs.grafana.org/administration/provisioning/

**Comment by gotojeffray** [comment]
Hi There, I got the same problem here:
CentOS 7
ansible  2.6
Grafana: 5.2.1

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_O7AaWn/ansible_module_grafana_dashboard.py", line 335, in <module>
    main()
  File "/tmp/ansible_O7AaWn/ansible_module_grafana_dashboard.py", line 299, in main
    mutually_exclusive=[['grafana_user', 'grafana_api_key']],
  File "/tmp/ansible_O7AaWn/ansible_modlib.zip/ansible/module_utils/basic.py", line 921, in __init__
  File "/tmp/ansible_O7AaWn/ansible_modlib.zip/ansible/module_utils/basic.py", line 2231, in _log_invocation
  File "/tmp/ansible_O7AaWn/ansible_modlib.zip/ansible/module_utils/basic.py", line 2192, in log
TypeError: send() got multiple values for keyword argument 'MESSAGE'

failed: [prometheus -> localhost] (item=/tmp/dashboards/oracledb.json) => {
    "changed": false, 
    "item": "/tmp/dashboards/oracledb.json", 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_O7AaWn/ansible_module_grafana_dashboard.py\", line 335, in <module>\n    main()\n  File \"/tmp/ansible_O7AaWn/ansible_module_grafana_dashboard.py\", line 299, in main\n    mutually_exclusive=[['grafana_user', 'grafana_api_key']],\n  File \"/tmp/ansible_O7AaWn/ansible_modlib.zip/ansible/module_utils/basic.py\", line 921, in __init__\n  File \"/tmp/ansible_O7AaWn/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2231, in _log_invocation\n  File \"/tmp/ansible_O7AaWn/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2192, in log\nTypeError: send() got multiple values for keyword argument 'MESSAGE'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1

**Comment by ansibot** [comment]
cc @seuf
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by parberge** [comment]
I get the same error when using `state: export`:

```
- name: Export dashboard
  grafana_dashboard:
    grafana_url: http://my_grafana
    grafana_password: "{{ grafana_admin_password }}"
    state: export
    path: /tmp/test
```

Result:
```
fatal: [my_grafana]: FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to my_grafana closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_j1cRZp/ansible_module_grafana_dashboard.py\", line 335, in <module>\r\n    main()\r\n  File \"/tmp/ansible_j1cRZp/ansible_module_grafana_dashboard.py\", line 299, in main\r\n    mutually_exclusive=[['grafana_user', 'grafana_api_key']],\r\n  File \"/tmp/ansible_j1cRZp/ansible_modlib.zip/ansible/module_utils/basic.py\", line 921, in __init__\r\n  File \"/tmp/ansible_j1cRZp/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2246, in _log_invocation\r\n  File \"/tmp/ansible_j1cRZp/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2207, in log\r\nTypeError: send() got multiple values for keyword argument 'MESSAGE'\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

Using grafana `5.2.4` on centOS 7 and ansible version `2.6.2`

**Comment by seuf** [comment]
I remember having this bug too.
I suggest you to use `connection: local` to fix this. (? don't know why it don"t wokrs with a remote connection ???)
```
- hosts: localhost
  connection: local
  tasks:
    - name: Import Grafana dashboard foo
      grafana_dashboard:
        grafana_url: http://grafana.company.com
        grafana_api_key: "{{ grafana_api_key }}"
        state: present
        message: Updated by ansible
        overwrite: yes
        path: /path/to/dashboards/foo.json
```
