### ISSUE TITLE
IOS_COMMAND/IOS_Config/NXOS_config/NXOS_command timeout deprecated? what's the alternative.. this should not be deprecated.

### ISSUE THREAD

**Issue by jopaik** [ansible/ansible#39319]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

ios_command
ios_config
nxos_command
nxos_config
##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### SUMMARY

timeout is required for the playbook to run correctly against cisco devices.
I got a depredicated error message, what is the new method of timeout otherwise this should not be deprecated and message removed.
##### STEPS TO REPRODUCE

```yaml
---
- name: Validate current config for no ip domain lookup
  ios_command:
    timeout: 25
    commands:
      - show running-config | i domain
    wait_for:
      - result[0] contains 'no ip domain lookup'
```

##### EXPECTED RESULTS

Timeout is required otherwise some devices fail with default timeout of 10secs.
Timeout should not be deprecated.
##### ACTUAL RESULTS

```

```

**Comment by jopaik** [comment]
DEPRECATION WARNING]: Param 'timeout' is deprecated. See the module docs for more information. This feature will be removed in version 2.9.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by sivel** [comment]
This is covered by the porting guide documentation located at http://docs.ansible.com/ansible/latest/porting_guides/porting_guide_2.5.html#top-level-connection-arguments-will-be-removed-in-2-9

Instead of using a top level `timeout`, you will instead need to use:

```
- ios_command:
    provider:
      timeout: 25
    commands:
      - show running-config | i domain
    wait_for:
      - result[0] contains 'no ip domain lookup'
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
