### ISSUE TITLE
win_iis_website: "Cannot create a file when that file already exists. (Exception from HRESULT: 0x800700B7)"

### ISSUE THREAD

**Issue by stintel** [ansible/ansible#39332]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_iis_website

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = None
  configured module search path = ['/home/stijn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.5/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.5/ansible
  python version = 3.5.5 (default, Apr 18 2018, 23:34:57) [GCC 6.4.0]
```

##### OS / ENVIRONMENT
N/A
Managed device is running Windows Server 2016 Datacenter

##### SUMMARY
The documentation for win_iis_website says physical_path has to exists.

##### STEPS TO REPRODUCE
`ansible-playbook -i inv bug.yml  -D`

```yaml
- name: bug
  hosts: win2k16
  vars:
    webdir: "C:\inetpub\test"
    win_features:
      - Net-Framework-45-Core
      - Web-Asp-Net45
      - Web-Mgmt-Console
      - Web-Mgmt-Service
      - Web-Server

  tasks:
    - name: install Windows Features
      win_feature:
        name: "{{ win_features | join(',') }}"
        state: present
      when: win_features | length > 0

    - name: create webdir
      win_file:
        path: "{{ webdir }}"
        state: directory

    - name: create IIS website
      win_iis_website:
        name: test
        port: 80
        physical_path: "{{ webdir }}"
        state: started
```

##### EXPECTED RESULTS
IIS website should be created.

##### ACTUAL RESULTS
```
ansible-playbook 2.5.1
  config file = None
  configured module search path = ['/home/stijn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.5/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.5/ansible-playbook
  python version = 3.5.5 (default, Apr 18 2018, 23:34:57) [GCC 6.4.0]
No config file found; using defaults
setting up inventory plugins
Parsed /home/stijn/tmp/ansible_bug/inv inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib64/python3.5/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: bug.yml ***************************************************************************************************************************************************************************************************************************
1 plays in bug.yml

PLAY [bug] **********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /home/stijn/tmp/ansible_bug/bug.yml:2
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/windows/setup.ps1
<10.12.1.7> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 10.12.1.7
checking if winrm_host 10.12.1.7 is an IPv6 address
EXEC (via pipeline wrapper)
ok: [win2k16]
META: ran handlers

TASK [install Windows Features] *************************************************************************************************************************************************************************************************************
task path: /home/stijn/tmp/ansible_bug/bug.yml:14
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/windows/win_feature.ps1
<10.12.1.7> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 10.12.1.7
checking if winrm_host 10.12.1.7 is an IPv6 address
EXEC (via pipeline wrapper)
ok: [win2k16] => {
    "changed": false,
    "exitcode": "NoChangeNeeded",
    "feature_result": [],
    "reboot_required": false,
    "restart_needed": false,
    "success": true
}

TASK [create webdir] ************************************************************************************************************************************************************************************************************************
task path: /home/stijn/tmp/ansible_bug/bug.yml:20
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/windows/win_file.ps1
<10.12.1.7> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 10.12.1.7
checking if winrm_host 10.12.1.7 is an IPv6 address
EXEC (via pipeline wrapper)
ok: [win2k16] => {
    "changed": false
}

TASK [create IIS website] *******************************************************************************************************************************************************************************************************************
task path: /home/stijn/tmp/ansible_bug/bug.yml:25
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/windows/win_iis_website.ps1
<10.12.1.7> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 10.12.1.7
checking if winrm_host 10.12.1.7 is an IPv6 address
EXEC (via pipeline wrapper)
fatal: [win2k16]: FAILED! => {
    "changed": false,
    "msg": "Cannot create a file when that file already exists. (Exception from HRESULT: 0x800700B7)"
}
        to retry, use: --limit @/home/stijn/tmp/ansible_bug/bug.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
win2k16                    : ok=3    changed=0    unreachable=0    failed=1
```

**Comment by stintel** [comment]
When changing the playbook to remove the directory there is a different error, so this module is currently unusable:

```yaml
---
- name: bug
  hosts: win2k16
  vars:
    webdir: 'C:\inetpub\test'
    win_features:
      - Net-Framework-45-Core
      - Web-Asp-Net45
      - Web-Mgmt-Console
      - Web-Mgmt-Service
      - Web-Server

  tasks:
    - name: install Windows Features
      win_feature:
        name: "{{ win_features | join(',') }}"
        state: present
      when: win_features | length > 0

    - name: create webdir
      win_file:
        path: "{{ webdir }}"
        state: absent

    - name: create IIS website
      win_iis_website:
        name: test
        port: 80
        physical_path: "{{ webdir }}"
        state: started
```

Result:
```
ansible-playbook 2.5.1
  config file = None
  configured module search path = ['/home/stijn/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.5/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.5/ansible-playbook
  python version = 3.5.5 (default, Apr 18 2018, 23:34:57) [GCC 6.4.0]
No config file found; using defaults
setting up inventory plugins
Parsed /home/stijn/tmp/ansible_bug/inv inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib64/python3.5/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: bug.yml ***************************************************************************************************************************************************************************************************************************
1 plays in bug.yml

PLAY [bug] **********************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************************************************************
task path: /home/stijn/tmp/ansible_bug/bug.yml:2
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/windows/setup.ps1
<10.12.1.7> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 10.12.1.7
checking if winrm_host 10.12.1.7 is an IPv6 address
EXEC (via pipeline wrapper)
ok: [win2k16]
META: ran handlers

TASK [install Windows Features] *************************************************************************************************************************************************************************************************************
task path: /home/stijn/tmp/ansible_bug/bug.yml:14
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/windows/win_feature.ps1
<10.12.1.7> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 10.12.1.7
checking if winrm_host 10.12.1.7 is an IPv6 address
EXEC (via pipeline wrapper)
ok: [win2k16] => {
    "changed": false,
    "exitcode": "NoChangeNeeded",
    "feature_result": [],
    "reboot_required": false,
    "restart_needed": false,
    "success": true
}

TASK [create webdir] ************************************************************************************************************************************************************************************************************************
task path: /home/stijn/tmp/ansible_bug/bug.yml:20
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/windows/win_file.ps1
<10.12.1.7> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 10.12.1.7
checking if winrm_host 10.12.1.7 is an IPv6 address
EXEC (via pipeline wrapper)
changed: [win2k16] => {
    "changed": true
}

TASK [create IIS website] *******************************************************************************************************************************************************************************************************************
task path: /home/stijn/tmp/ansible_bug/bug.yml:25
Using module file /usr/lib64/python3.5/site-packages/ansible/modules/windows/win_iis_website.ps1
<10.12.1.7> ESTABLISH WINRM CONNECTION FOR USER: admin on PORT 5986 TO 10.12.1.7
checking if winrm_host 10.12.1.7 is an IPv6 address
EXEC (via pipeline wrapper)
fatal: [win2k16]: FAILED! => {
    "changed": false,
    "msg": "specified folder must already exist: physical_path"
}
        to retry, use: --limit @/home/stijn/tmp/ansible_bug/bug.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
win2k16                    : ok=3    changed=1    unreachable=0    failed=1   
```

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by stintel** [comment]
Should have done more testing, the problem is not related to the web directory. The error comes from a port conflict with the default website.

Adding a task like this solves my problem:
```
    - name: delete default IIS website
      win_iis_website:
        name: "Default Web Site"
        state: absent
```

Changing a port after a site was created doesn't seem to work however, but I'll create a new bug for this tomorrow.
