### ISSUE TITLE
Appending to dict broken in Ansible 2.5.1

### ISSUE THREAD

**Issue by quulah** [ansible/ansible#39346]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
"set_fact"

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = None
  configured module search path = ['/Users/kuula/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kuula/.pyenv/versions/3.6.4/lib/python3.6/site-packages/ansible
  executable location = /Users/kuula/.pyenv/versions/3.6.4/bin/ansible
  python version = 3.6.4 (default, Apr 21 2018, 11:22:34) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION
```
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/Users/kuula/.ansible/roles']
```

##### OS / ENVIRONMENT
"N/A"

##### SUMMARY
Appending to dict in a loop is broken with Ansible 2.5.1 and Python 3.

This works with Ansible 2.4.2.0 in Python 2.

##### STEPS TO REPRODUCE
```yaml
---
- name: Testing
  hosts: localhost
  tasks:
    - name: Create dict
      set_fact:
        my_dict: {}

    - name: Test dict append
      set_fact:
        my_dict: "{{ my_dict | combine({item.key: item.value}) }}"
      with_dict:
        one: 1
        two: 2
        three: 3

    - debug: var=my_dict
```

##### EXPECTED RESULTS
```
TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "my_dict": {
        "one": 1, 
        "three": 3, 
        "two": 2
    }
}
```
##### ACTUAL RESULTS
```
TASK [debug] *******************************************************************************************************************************
ok: [localhost] => {
    "my_dict": {
        "three": 3
    }
}
```

**Comment by quulah** [comment]
This doesn't actually seem to be related to Python 3. This doesn't work either:

```
ansible 2.5.1
  config file = None
  configured module search path = [u'/Users/kuula/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kuula/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansible
  executable location = /Users/kuula/.pyenv/versions/2.7.14/bin/ansible
  python version = 2.7.14 (default, Nov 24 2017, 22:58:10) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.38)]
```

```
TASK [Test dict append] ********************************************************************************************************************
task path: /Users/kuula/testi/playbook.yml:9
ok: [localhost] => (item={'value': 1, 'key': u'one'}) => {
    "ansible_facts": {
        "my_dict": {
            "one": 1
        }
    }, 
    "changed": false, 
    "item": {
        "key": "one", 
        "value": 1
    }
}
ok: [localhost] => (item={'value': 3, 'key': u'three'}) => {
    "ansible_facts": {
        "my_dict": {
            "three": 3
        }
    }, 
    "changed": false, 
    "item": {
        "key": "three", 
        "value": 3
    }
}
ok: [localhost] => (item={'value': 2, 'key': u'two'}) => {
    "ansible_facts": {
        "my_dict": {
            "two": 2
        }
    }, 
    "changed": false, 
    "item": {
        "key": "two", 
        "value": 2
    }
}

TASK [debug] *******************************************************************************************************************************
task path: /Users/kuula/testi/playbook.yml:17
ok: [localhost] => {
    "my_dict": {
        "two": 2
    }
}
```

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by msaladna** [comment]
Broken for lists and strings too in 2.5.1. Works fine in 2.4.2. 

```yaml
---
- hosts: localhost  
  tasks:
    - set_fact:
        str: "foo"
    - name: Append
      set_fact:
        str: "{{ str + item }}"
      with_items: 
        - bar
        - baz
    - debug: msg="{{ str }}"
```

2.4.2 produces "foobarbaz". 2.5.1 produces "foobaz".
