### ISSUE TITLE
win_nssm should accept commands for application as well

### ISSUE THREAD

**Issue by chanond-w** [ansible/ansible#39349]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_nssm

##### ANSIBLE VERSION

```
ansible 2.5.1
```

##### CONFIGURATION

None
##### OS / ENVIRONMENT

Windows 10 control machine, Windows Server 2016 
##### SUMMARY

`win_nssm` keeps returning `Application does not exists on the host` because the way `win_nssm` check the application parameter is to check if the executable file exists. However, it is possible to use just command for `nssm` to work.
##### STEPS TO REPRODUCE

```yaml
    - name: Install Syncthing
      win_chocolatey:
        name: syncthing
        state: latest
    - name: Install NSSM
      win_chocolatey:
        name: nssm
        state: latest
    - name: Setup Syncthing as NSSM
      win_nssm:
        name: syncthing
        application: syncthing
        app_parameters:
          _: "-no-browser -no-console -home={{ syncthing_home_dir }}"
        state: started
        start_mode: auto
```

##### EXPECTED RESULTS

`win_nssm` should complete successfully.
##### ACTUAL RESULTS

Failed with message "syncthing does not exist on the host"

```
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_nssm.ps1
<xxx.xxx.xxx.xxx> ESTABLISH WINRM CONNECTION FOR USER: xxxx on PORT xxxx TO xxx.xxx.xxx.xxx
checking if winrm_host xxx.xxx.xxx.xxx is an IPv6 address
EXEC (via pipeline wrapper)
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {
    "changed": false,
    "msg": "syncthing does not exist on the host"
}
```
