### ISSUE TITLE
IIS AppPool Attribute managedRuntimeVersion not working

### ISSUE THREAD

**Issue by Thorbenn** [ansible/ansible#39357]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_iis_webapppool

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/xxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
##### CONFIGURATION
```
ANSIBLE_NOCOWS(/etc/ansible/ansible.cfg) = True
DEFAULT_NO_TARGET_SYSLOG(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT
Running Ansible on: Ubuntu 16.04 LTS
Managing: Windows Server 2016 and 2012 R2 (German System Language)

##### SUMMARY
When trying to set the Attribute managedRuntimeVersion of the ApplicationPool to "No managed Code" (in german "Kein verwalteter Code"), the Attribute is never set correctly. Instead of setting it to the value, it always creates a new entry in the ApplicationPool for this value and this causes the ApplicationPool to crash. I have tried setting it to No managed Code (diverse spellings and in the Playbook with single quotes and double) and it still happens. Even when using the german definition i get the same results.

##### STEPS TO REPRODUCE

```
- name: Create Test AppPool
       win_iis_webapppool:
         name: "Test"
         state: started
         attributes:
           managedRuntimeVersion: 'Kein verwalteter Code'
           processModel.loadUserProfile: True
           processModel.identityType: 3
           processModel.userName: 'Bob'
           processModel.password: 'Bobs_SuperSecretPassword'
```

##### EXPECTED RESULTS
The AppPool is set to No Managed Code

##### ACTUAL RESULTS
The AppPool crashes because a new value is created
