### ISSUE TITLE
with_items in combination with set_facts does not work

### ISSUE THREAD

**Issue by DaspawnW** [ansible/ansible#39354]
#### ISSUE TYPE
Bug Report

##### COMPONENT NAME
* set_fact
* loop | with_items

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = /Users/bjoernwenzel/src/ecosystem/deployment/ansible.cfg
  configured module search path = [u'/Users/bjoernwenzel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:54:19) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION
ansible.cfg:
```
[defaults]
lookup_plugins = external/ansible-vault
stdout_callback = debug
roles_path = external
```

##### OS / ENVIRONMENT
MacOSX 10.13.4

##### SUMMARY

A loop over set_facts to append to a variable returns only the last item. In the past it was possible to append dynamically to a variable.

##### STEPS TO REPRODUCE

```yaml
- name: setup ecosystem stage environment
  hosts: localhost
  gather_facts: no
  tasks:
    - name: this should generate a variable with multiple values in it
      set_fact:
        taglist: "{{ taglist | default('') }} -var {{ item.key }}={{ item.value }}"
      loop:
        - {key: "Hello", value: "World"}
        - {key: "Sun", value: "Set"}

    - debug:
        msg: "{{ taglist }}"

    - name: loop over debug seems to work
      debug:
        msg: "{{ item.key }}={{ item.value }}"
      with_items:
        - {key: "Hello", value: "World"}
        - {key: "Sun", value: "Set"}

```

Produces output:
```bash
PLAY [setup test environment] ****************************************************************************************************************************************************************************************

TASK [this should generate a variable with multiple values in it] ****************************************************************************************************************************************************
ok: [localhost] => (item={u'key': u'Hello', u'value': u'World'})
ok: [localhost] => (item={u'key': u'Sun', u'value': u'Set'})

TASK [debug] *********************************************************************************************************************************************************************************************************
ok: [localhost] => {}

MSG:

 -var Sun=Set


TASK [loop over debug seems to work] *********************************************************************************************************************************************************************************
ok: [localhost] => (item=None) => {}

MSG:

Hello=World

ok: [localhost] => (item=None) => {}

MSG:

Sun=Set


PLAY RECAP ***********************************************************************************************************************************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```

##### EXPECTED RESULTS

The taglist should be in format:
 -var Hello=World -var Sun=Set

##### ACTUAL RESULTS

```
ASK [this should generate a variable with multiple values in it] ****************************************************************************************************************************************************
task path: /Users/bjoernwenzel/src/ecosystem/deployment/test.yaml:5
ok: [localhost] => (item={u'key': u'Hello', u'value': u'World'}) => {
    "ansible_facts": {
        "taglist": " -var Hello=World"
    },
    "changed": false,
    "item": {
        "key": "Hello",
        "value": "World"
    }
}
ok: [localhost] => (item={u'key': u'Sun', u'value': u'Set'}) => {
    "ansible_facts": {
        "taglist": " -var Sun=Set"
    },
    "changed": false,
    "item": {
        "key": "Sun",
        "value": "Set"
    }
}
```
