### ISSUE TITLE
yum_repository module: file param ignored

### ISSUE THREAD

**Issue by aturetta** [ansible/ansible#39379]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
yum_repository

##### ANSIBLE VERSION
```
ansible 2.3.0.0
  config file = /******/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### SUMMARY
Parameter 'file' is ignored when using module yum_repository

I think this is due to 'file' string missing from the allowed_params array, inside the module .py

##### STEPS TO REPRODUCE

```yaml
- name: 'create repo'
  yum_repository:
    name: 'elastic-6.x'
    gpgkey: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
    enabled: False
    baseurl:  'https://artifacts.elastic.co/packages/6.x/yum'
    file: 'elastic'
    gpgcheck: 1
    description: 'Elastic repository for 6.x packages'
```

##### EXPECTED RESULTS
Should create file /etc/yum.repos.d/elastic.repo

##### ACTUAL RESULTS
Creates file /etc/yum.repos.d/elastic-6.x.repo
as if 'file' was not present

```

```
