### ISSUE TITLE
'openshift_raw' is not a valid attribute for a Play on Fedora 27

### ISSUE THREAD

**Issue by gbaufake** [ansible/ansible#39393]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

"openshift_raw"

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gbaufake/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### OS / ENVIRONMENT

* Fedora 27

##### SUMMARY

Openshift_raw (http://docs.ansible.com/ansible/2.5/modules/openshift_raw_module.html?highlight=openshift_raw) can't be used on playbook

##### STEPS TO REPRODUCE
* Create a simple playbook (`playbook.yml`) with openshift_raw
like 
```
  - name: Create a project
    openshift_raw:
      api_version: v1
      kind: Project
      name: testing
      description: Testing
      display_name: "This is a test project."
      state: present
```

```yaml
ansible-playbook playbook.yml 
```

##### EXPECTED RESULTS

- Execute the commands on the playbook

##### ACTUAL RESULTS

- Message saying "'openshift_raw' is not a valid attribute for a Play "

```
ansible-playbook playbook.yml -e username=user -e password=password                                                                                   
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
ERROR! 'openshift_raw' is not a valid attribute for a Play

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/openshift/openshift_raw.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/openshift/openshift_raw.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
The error indicates that your playbook looks only like:

```
  - name: Create a project
    openshift_raw:
      api_version: v1
      kind: Project
      name: testing
      description: Testing
      display_name: "This is a test project."
      state: present
```

This is not a valid playbook.

A valid playbook must include a `hosts:` key, and any tasks must live under a `tasks:` header, such as:

```
- hosts: all
  tasks:
    - name: Create a project
      openshift_raw:
        api_version: v1
        kind: Project
        name: testing
        description: Testing
        display_name: "This is a test project."
        state: present
```

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
