### ISSUE TITLE
Bug with static binding of EPG to VPC (aci_static_binding_to_epg)

### ISSUE THREAD

**Issue by micruzz82** [ansible/ansible#39401]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
aci_static_binding_to_epg

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
Release:        16.04
Codename:       xenial

Cisco APIC version 3.1(2m)

##### SUMMARY
When trying to configure static binding under epg of type Virtual Port Channel (VPC) the ansible playbook keeps giving the error as below:

TASK [Deploy Static Path binding for given EPG] *********************************************************************************
failed: [10.255.193.234 -> localhost] (item={u'ap': u'test-ap-1', u'encapid': 100, u'leafs': u'101-102', u'interface': u'vPC_TESTSVR777', u'epg': u'WEB-1', u'tenant': u'test-tn-1'}) => {"changed": false, "item": {"ap": "test-ap-1", "encapid": 100, "epg": "WEB-1", "interface": "vPC_TESTSVR777", "leafs": "101-102", "tenant": "test-tn-1"}, "msg": "A interface_type of \"vpc\" requires 2 leafs"}

"msg": "A interface_type of \"vpc\" requires 2 leafs"

This is even after specifying: "leafs": "101-102"

##### STEPS TO REPRODUCE

Create a normal ACI playbook after creating a tenant/VRF/BD/AP/EPG

Run the static binding module as below.

```yaml

  - name: Deploy Static Path binding for given EPG
    aci_static_binding_to_epg:
        <<: *aci_login
        tenant: "{{ item.tenant }}"
        ap: "{{ item.ap }}"
        epg: "{{ item.epg }}"
        encap_id: "{{ item.encapid }}"
        deploy_immediacy: lazy
        interface_mode: trunk
        interface_type: vpc
        pod_id: 1
        leafs: "{{ item.leafs }}"
        interface: "{{ item.interface }}"
        state: present
    delegate_to: localhost
    with_items:
      - tenant: test-tn-1
        ap: test-ap-1
        epg: WEB-1
        encapid: 100
        leafs: 101-102
        interface: 'vPC_TESTSVR777'


```

##### EXPECTED RESULTS
Configuration should have been successfully sent to the APIC controlller for the static binding for EPG.

##### ACTUAL RESULTS

```
TASK [Deploy Static Path binding for given EPG] *********************************************************************************
task path: /etc/ansible/playbooks/create-epgbindings.yml:31
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/network/aci/aci_static_binding_to_epg.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1524788666.41-61846862726450 `" && echo ansible-tmp-1524788666.41-61846862726450="` echo /root/.ansible/tmp/ansible-tmp-1524788666.41-61846862726450 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-115400jLATn/tmpatys4S TO /root/.ansible/tmp/ansible-tmp-1524788666.41-61846862726450/aci_static_binding_to_epg.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1524788666.41-61846862726450/ /root/.ansible/tmp/ansible-tmp-1524788666.41-61846862726450/aci_static_binding_to_epg.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1524788666.41-61846862726450/aci_static_binding_to_epg.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1524788666.41-61846862726450/ > /dev/null 2>&1 && sleep 0'
failed: [10.1.1.1 -> localhost] (item={u'ap': u'test-ap-1', u'encapid': 100, u'leafs': u'101-102', u'interface': u'vPC_TESTSVR777', u'epg': u'WEB-1', u'tenant': u'test-tn-1'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ap": "test-ap-1",
            "certificate_name": null,
            "deploy_immediacy": "lazy",
            "encap_id": 100,
            "epg": "WEB-1",
            "extpaths": null,
            "host": "10.1.1.1",
            "hostname": "10.1.1.1",
            "interface": "vPC_TESTSVR777",
            "interface_mode": "trunk",
            "interface_type": "vpc",
            "leafs": [
                "101-102"
            ],
            "output_level": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "pod_id": 1,
            "port": null,
            "primary_encap_id": null,
            "private_key": null,
            "state": "present",
            "tenant": "test-tn-1",
            "timeout": 30,
            "use_proxy": true,
            "use_ssl": true,
            "username": "test-ans",
            "validate_certs": false
        }
    },
    "item": {
        "ap": "test-ap-1",
        "encapid": 100,
        "epg": "WEB-1",
        "interface": "vPC_TESTSVR777",
        "leafs": "101-102",
        "tenant": "test-tn-1"
    },
    "msg": "A interface_type of \"vpc\" requires 2 leafs"
}
        to retry, use: --limit @/etc/ansible/playbooks/create-epgbindings.retry

PLAY RECAP **********************************************************************************************************************
10.1.1.1             : ok=1    changed=0    unreachable=0    failed=1


```
