### ISSUE TITLE
nxos_linkagg is not consistent

### ISSUE THREAD

**Issue by ossark** [ansible/ansible#39408]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_linkagg

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.0
  config file = /Users/johndoe/.ansible.cfg
  configured module search path = [u'/Library/Python/2.7/site-packages/napalm_ansible/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/Users/johndoe/.ansible.cfg) = [u'/Users/johndoe/repos/ansible/inventory']
DEFAULT_LOG_PATH(/Users/johndoe/.ansible.cfg) = /Users/johndoe/.ansible.log
DEFAULT_MANAGED_STR(/Users/johndoe/.ansible.cfg) = Ansible managed: modified on %Y-%m-%d by {uid} on {host}
DEFAULT_MODULE_PATH(/Users/johndoe/.ansible.cfg) = [u'/Library/Python/2.7/site-packages/napalm_ansible/modules']
DEFAULT_VAULT_PASSWORD_FILE(/Users/johndoe/.ansible.cfg) = /Users/johndoe/.ssh/vault
```
##### OS / ENVIRONMENT

MacOS High Sierra

##### SUMMARY

nxos_linkagg sets the correct parameters and reports "changed" but running the same task again also reports as "changed" but reverts the change.

##### STEPS TO REPRODUCE

```
---
- hosts: nexus0
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure local host portchannels
      nxos_linkagg:
        group: 1002
        mode: active
        members: ['Eth1/10', 'Eth1/11']
```

```
$ ansible-playbook nexus-test.yaml 

PLAY [nexus0] ********************************************************************************************************************************************************************************************************************************

TASK [Configure local host portchannels] *****************************************************************************************************************************************************************************************************
changed: [nexus0]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
nexus0                     : ok=1    changed=1    unreachable=0    failed=0 
```

```
nexus0# sh port-channel summary | i 1002
1002  Po1002(SD)  Eth      LACP      Eth1/10(D)   Eth1/11(D)   
```

```
$ ansible-playbook nexus-test.yaml 

PLAY [nexus0] ********************************************************************************************************************************************************************************************************************************

TASK [Configure local host portchannels] *****************************************************************************************************************************************************************************************************
changed: [nexus0]

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
nexus0                     : ok=1    changed=1    unreachable=0    failed=0   
```

```
nexus0# sh port-channel summary | i 1002
1002  Po1002(SD)  Eth      NONE      --
```

##### EXPECTED RESULTS

The first run of the playbook would det the linkagg members correctly and report as "changed". The second run would not change anything and report "ok".

##### ACTUAL RESULTS

See above.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/nxos/nxos_linkagg.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/nxos/nxos_linkagg.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @mikewiebe @privateip @rahushen @rcarrillocruz @trishnaguha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ossark** [comment]
Ok I figured it out. Not sure if it is a nxos bug or ansible. Probably ansible not matching interface names correctly in certain circumstances.

This works
```
---
- hosts: nexus0
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure local host portchannels
      nxos_linkagg:
        group: 1002
        mode: active
        members: ['Ethernet1/10', 'Ethernet1/11']
```

This does not work
```
---
- hosts: nexus0
  connection: network_cli
  gather_facts: no

  tasks:
    - name: Configure local host portchannels
      nxos_linkagg:
        group: 1002
        mode: active
        members: ['Eth1/10', 'Eth1/11']
```
