### ISSUE TITLE
ssh connection with delegate_to checks wrong variable

### ISSUE THREAD

**Issue by kudrevatykh** [ansible/ansible#39413]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

delegate_to

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/kudrale/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kudrale/ansible-2.5.2/lib/ansible
  executable location = /home/kudrale/ansible-2.5.2/bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### OS / ENVIRONMENT

N/A
##### SUMMARY

delegate_to checks wrong variable before connection
##### STEPS TO REPRODUCE

setup one host with not ssh connection (for example ansible_connection: local) and one ssh with password that uses variable subsitution and run any task with `delegate_to`

```yaml
---
- hosts: localhost
  tasks:
    - name: gether facts
      ping:
      delegate_to: local_ssh
```

```yaml
---
all:
  hosts:
    localhost:
      ansible_connection: local
    local_ssh:
      ansible_host: 127.0.0.1
      ansible_ssh_pass: "{{ansible_ssh_pass_vault}}"
      ansible_ssh_pass_vault: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61636166343335393163306665653363306135396136353764363964303064323436363136333939
          3933386635376463393733643933313739313431643464360a653065323030316162313332653333
          31626161656432636362613530393364346166333466633838393937373833333361656330373666
          6636663565633235350a313765303665643232303437363930616438383232363035643031316666
          3630
      ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
```

##### EXPECTED RESULTS

task executed successfully
##### ACTUAL RESULTS

ansible reports error with undefined variable

```
# inventory is fine
$ ansible all -i hosts -m ping --ask-vault-pass
Vault password:
localhost | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
local_ssh | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
$ ansible-playbook -i hosts --ask-vault-pass play.yml
Vault password:

PLAY [localhost] **************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
ok: [localhost]

TASK [gether facts] ***********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The field 'password' has an invalid value, which includes an undefined variable. The error was: 'ansible_ssh_pass_vault' is undefined\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'ansible_ssh_pass_vault' is undefined"}
        to retry, use: --limit @/home/kudrale/example/play.retry

PLAY RECAP ********************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

```

ugly workaround for this bug - define variable `ansible_ssh_pass_vault` with any value for `localhost`
