### ISSUE TITLE
Add a Network Tips and Tricks page?

### ISSUE THREAD

**Issue by acozine** [ansible/ansible#39431]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
docs.ansible.com/ansible/network

##### ANSIBLE VERSION
2.5

##### SUMMARY
The field teams have a lot of great tips and tricks for handling common network challenges. Create a page to document these.

The first one, from Steven Carter, is:

When rebooting a switch, you may need to issue a command and respond 'yes' to the network OS's request for confirmation. This can also occur when you apply a COPP - the network OS asks for confirmation before applying because the change can create a momentary packet loss. To handle situations like this, try:
```
nxos_command:
   command:
      - command: foo
         prompt: question
         response: yes
```
This task provides 'yes' as an answer to the first question the network OS asks after the command 'foo' gets executed.
