### ISSUE TITLE
Recursive permissions change on a directory fails when directory contains a broken symlink

### ISSUE THREAD

**Issue by zdw** [ansible/ansible#39456]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
file

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/users/zdw/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY

The file module in 2.5.2 fails when trying to change permissions recursively and encounters a symlink that points to something that that doesn't exist. 

This error also occurs in the devel 2.6.0 branch.

This failure does not occur in 2.5.1 and earlier.

##### STEPS TO REPRODUCE

Example playbook that shows the problem:

```yaml
---
- hosts: localhost
  connection: local

  tasks:
    - name: Create a directory for testing
      file:
        path: "{{ playbook_dir }}/test"
        state: directory

    - name: Create a symlink from a nonexistant file
      command: "ln -s /doesnt_exist {{ playbook_dir }}/test/doesnt_exist"

    - name: Attempt to change ownership on directory
      file:
        path: "{{ playbook_dir }}/test"
        state: directory
        recurse: yes
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
```

##### EXPECTED RESULTS

From Ansible 2.5.1:

```
$ ansible-playbook -i localhost, symlink_to_nowhere-playbook.yaml 

PLAY [localhost] *****************************************************************

TASK [Gathering Facts] ***********************************************************
ok: [localhost]

TASK [Create a directory for testing] ********************************************
changed: [localhost]

TASK [Create a symlink from a nonexistant file] **********************************
 [WARNING]: Consider using the file module with state=link rather than running
ln.  If you need to use command because file is insufficient you can add
warn=False to this command task or set command_warnings=False in ansible.cfg to
get rid of this message.

changed: [localhost]

TASK [Attempt to change ownership on directory] **********************************
ok: [localhost]

PLAY RECAP ***********************************************************************
localhost                  : ok=4    changed=2    unreachable=0    failed=0   
```
##### ACTUAL RESULTS

Error in 2.5.2 when trying to recursively set permissions:

```
$ ansible-playbook -i localhost, symlink_to_nowhere-playbook.yaml 

PLAY [localhost] *****************************************************************

TASK [Gathering Facts] ***********************************************************
ok: [localhost]

TASK [Create a directory for testing] ********************************************
changed: [localhost]

TASK [Create a symlink from a nonexistant file] **********************************
 [WARNING]: Consider using the file module with state=link rather than running
ln.  If you need to use command because file is insufficient you can add
warn=False to this command task or set command_warnings=False in ansible.cfg to
get rid of this message.

changed: [localhost]

TASK [Attempt to change ownership on directory] **********************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/doesnt_exist'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_ZOFwo4/ansible_module_file.py\", line 473, in <module>\n    main()\n  File \"/tmp/ansible_ZOFwo4/ansible_module_file.py\", line 350, in main\n    changed |= recursive_set_attributes(module, to_bytes(file_args['path'], errors='surrogate_or_strict'), follow, file_args)\n  File \"/tmp/ansible_ZOFwo4/ansible_module_file.py\", line 172, in recursive_set_attributes\n    changed |= module.set_fs_attributes_if_different(tmp_file_args, changed, expand=False)\n  File \"/tmp/ansible_ZOFwo4/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1507, in set_fs_attributes_if_different\n  File \"/tmp/ansible_ZOFwo4/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1164, in set_owner_if_different\n  File \"/tmp/ansible_ZOFwo4/ansible_modlib.zip/ansible/module_utils/basic.py\", line 1059, in user_and_group\nOSError: [Errno 2] No such file or directory: '/doesnt_exist'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/users/zdw/foo/symlink_to_nowhere-playbook.retry

PLAY RECAP ***********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1   
```
