### ISSUE TITLE
gce_lb: Not idempotent

### ISSUE THREAD

**Issue by victorock** [ansible/ansible#39458]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

gce_lb

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /Users/jdacosta/Devel/ansible-devops/applications/freeipa/ansible.cfg
  configured module search path = [u'/Users/jdacosta/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/jdacosta/Devel/python/lib/python2.7/site-packages/ansible
  executable location = /Users/jdacosta/Devel/python/bin/ansible
  python version = 2.7.14 (default, Mar 10 2018, 00:01:04) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

```

##### CONFIGURATION

DEFAULT_CALLBACK_WHITELIST(/Users/jdacosta/Devel/ansible-devops/applications/freeipa/ansible.cfg) = ['profile_tasks']
DEFAULT_HASH_BEHAVIOUR(/Users/jdacosta/Devel/ansible-devops/applications/freeipa/ansible.cfg) = merge

##### OS / ENVIRONMENT

N/A

##### SUMMARY

The following:
- When the instance do not exist the module says that configurations where applied successfully.
- When doing the second run, now with instances created, it doesn't not change/update the load-balance configuration (append).
- When only new entries are defined in the member list with state: present, no changes/updates are applied to the load-balance configuration (append).

##### STEPS TO REPRODUCE

```yaml
- name: "task1: loadbalance instance1"
  gce_lb:
    name: "loadbalance1"
    region: "europe-west1"
    external_ip: "myapp"
    port_range: "80"
    protocol: "tcp"
    members: [ 'europe-west1-d/instance1' ] 
    httphealthcheck_name: "simple-http"
    httphealthcheck_path: "/"
    httphealthcheck_port: "80"
    state: "present"

- name: "task2: loadbalance instance2"
  gce_lb:
    name: "loadbalance1"
    region: "europe-west1"
    external_ip: "myapp"
    port_range: "80"
    protocol: "tcp"
    members: [ 'europe-west1-d/instance2' ] 
    httphealthcheck_name: "simple-http"
    httphealthcheck_path: "/"
    httphealthcheck_port: "80"
    state: "present"

- name: "task3: loadbalance instance2"
  gce_lb:
    name: "loadbalance1"
    region: "europe-west1"
    external_ip: "myapp"
    port_range: "80"
    protocol: "tcp"
    members: [ 'europe-west1-d/instance1', 'europe-west1-d/instance2'  ] 
    httphealthcheck_name: "simple-http"
    httphealthcheck_path: "/"
    httphealthcheck_port: "80"
    state: "present"


```

##### EXPECTED RESULTS

- Task1: Add instance1 if it exists
- Task1: Fail if instance2 do not exist.
- Task2: Add instance2 if it exists.
- Task2: Fail if instance2 do not exist.
- Task3: Add instance2 if it exists.
- Task3: Fail if instance2 do not exist.

##### ACTUAL RESULTS

Configuration state of loadbalance is inconsistent and cannot be updated.
No new members can be added to existing loadbalance. 

```

```
