### ISSUE TITLE
nsupdate doesn't check for ttl changes

### ISSUE THREAD

**Issue by Nothing4You** [ansible/ansible#39465]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
nsupdate

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /home/user/project/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/home/user/project/ansible.cfg) = [u'/home/user/project/inventory.yml']
HOST_KEY_CHECKING(/home/user/project/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/user/project/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ansible running on Arch Linux, managed host is Debian Stretch.

##### SUMMARY
The module does not check for the ttl when it checks whether a change is required.

##### STEPS TO REPRODUCE
```yaml
- nsupdate:
    server: "{{ dns_server}}"
    ttl: "{{ item }}"
    zone: "example.com"
    record: "test"
    type: "a"
    value: "127.0.0.1"
  with_items:
    - 100
    - 200
```

##### EXPECTED RESULTS
The task should first create the record with 100s ttl, then change it to 200s ttl. This should at least cause 1 change on the first run, later runs should always cause 2 changes.

##### ACTUAL RESULTS
```
TASK [dnsrecords : Configure dns records] **********************************************************************************************
ok: [dnshost] => (item=100)
ok: [dnshost] => (item=200)

PLAY RECAP *****************************************************************************************************************************
dnshost                    : ok=2    changed=0    unreachable=0    failed=0   
```
