### ISSUE TITLE
Changing follow default parameter for file command can be dangerous

### ISSUE THREAD

**Issue by longwave** [ansible/ansible#39489]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

file

##### ANSIBLE VERSION

```
ansible 2.5.2
```

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

Changing the follow default is dangerous if previously your playbook removed a symlink; now it removes the destination of the symlink instead - this can cause data loss!

##### STEPS TO REPRODUCE

```yaml
      file:
        path: "/var/www/somedir/index.php"
        state: absent
```

##### EXPECTED RESULTS

index.php, which was a symlink, was removed.

##### ACTUAL RESULTS

The target of the index.php symlink was removed.

```

```
