### ISSUE TITLE
set_fact fails to generate a list in 2.5 but works fine in 2.4

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#39496]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```
# ansible --version
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:29:26) [GCC 7.3.1 20180130 (Red Hat 7.3.1-2)]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/root/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/root/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=6000s
ANSIBLE_SSH_CONTROL_PATH_DIR(/root/ansible.cfg) = /tmp/.ansible
CACHE_PLUGIN(/root/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/root/ansible.cfg) = ~/.ansible/tmp
CACHE_PLUGIN_TIMEOUT(/root/ansible.cfg) = 86400
DEFAULT_FACT_PATH(/root/ansible.cfg) = /root/.ansible/tmp
DEFAULT_FORKS(/root/ansible.cfg) = 5
DEFAULT_GATHERING(/root/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/root/ansible.cfg) = network
DEFAULT_PRIVATE_KEY_FILE(/root/ansible.cfg) = /root/.ssh/id_ed25519
DEFAULT_SFTP_BATCH_MODE(/root/ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/root/ansible.cfg) = False
RETRY_FILES_ENABLED(/root/ansible.cfg) = False

##### OS / ENVIRONMENT

Fedora release 26 (Twenty Six)

##### SUMMARY

After we upgraded from ansible 2.4.3 to 2.5.1, the set_fact command fails to generate a list from a CSV output. Rolling back to 2.4.3 and set_fact works properly as before. Just for kicks, I installed ansible 2.3.1 and I can confirm that 2.3.1 works the same way as 2.4.3, so the broken output appears only in 2.5.1.

##### STEPS TO REPRODUCE

```yaml
---
# file: ./bug.yml

- name: Bug report
  hosts: localhost

  tasks:

  - name: CSV variable
    set_fact:
      mycsv: ["1,one,","2,two","3,three"]

  - name: Convert CSV to list format
    set_fact:
      mylist: "{{ mylist|default([]) + [item.split(',')] }}"
    with_items: "{{ mycsv }}"

  - debug:
      var: mylist
```

##### EXPECTED RESULTS

Expected results, as seen when running the above with ansible 2.4.3:
```
 ______________
< TASK [debug] >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost] => {
    "mylist": [
        [
            "1", 
            "one", 
            ""
        ], 
        [
            "2", 
            "two"
        ], 
        [
            "3", 
            "three"
        ]
    ]
}
```

##### ACTUAL RESULTS

Results, as seen when running with ansible 2.5.1:
```
 ______________
< TASK [debug] >
 --------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost] => {
    "mylist": [
        [
            "3", 
            "three"
        ]
    ]
}

```
