### ISSUE TITLE
dynamic conditionals for each item of loops.

### ISSUE THREAD

**Issue by Raffaello** [ansible/ansible#39497]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`when:` ansible conditionals and `with_items:` loops

##### ANSIBLE VERSION

```
2.4.4.0
```

##### SUMMARY
```yaml
- name: check lines in a file are present
  become: true
  register: checks
  command: "grep -Fxq {{ item }} /tmp/file.txt"
  with_items:
    -  hello
    - world
  ignore_errors: true
  changed_when: false

- debug:
    msg: "checks = {{ check_systemd.results[0].rc }}  --- {{ check_systemd.results[1].rc }}"

### Doesn't work if 1 of the 2 lines is already present
- name: adding line(s) to a file
  become: true
  lineinfile:
    path: /tmp/file.txt
    insertafter: last
    line: "{{ item }}"
    state: present
    backup: true
  with_items:
    - hello
    - world
  when:
   - check_systemd.results[0].rc != 0
   - check_systemd.results[1].rc != 0

```

##### STEPS TO REPRODUCE
create just a file in `/tmp/file.txt` with 1 line `hello`

##### EXPECTED RESULTS
As a feature request it would be nice to have a loop that can have a specific conditional for each items.

##### ACTUAL RESULTS
the when list condition is applying a logical AND to each items of the list and so it is required to have 2 different tasks roughly doing the same operation of inserting 1 line (unroll the loop).
