### ISSUE TITLE
Cisco ios_config always backups running-config all

### ISSUE THREAD

**Issue by ciscler** [ansible/ansible#39504]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/drohlman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
##### OS / ENVIRONMENT
```
Ubuntu 16.04
Linux emea-mgm-s06p 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY
The ansible ios_config backups the cisco configs with the command "running-config all" But it should only backup the config with the normal running-config command. Before the upgrade to ansible 2.5 everything worked. 

This is the yml:

```
- hosts: switches
  gather_facts: true
  connection: local

  tasks:
  - name: OBTAIN LOGIN CREDENTIALS
    include_vars: secrets.yaml

  - name: DEFINE PROVIDER
    set_fact:
      provider:
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"
        auth_pass: "{{ creds['auth_pass'] }}"

  - name: RUN 'SET HOSTNAME'
    ios_config:
      provider: "{{ provider }}"
      defaults: yes
      backup: yes
```
