### ISSUE TITLE
win_service module no longer accepts wildcards 

### ISSUE THREAD

**Issue by JuChang91** [ansible/ansible#39517]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_service

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/home/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### OS / ENVIRONMENT

Ansible Control = RHEL7.4
Ansible Managed = Windows Server 2016 Standard

##### SUMMARY

win_service module no longer finds services with the wildcard character. 

i.e. my service name is my_service_2017
win_service:
  name: my_service* 

used to work in versions 2.4, but no longer work in 2.5.  Now nothing is returned. 

##### STEPS TO REPRODUCE

1. Install Ansible 2.5.1 or 2.5.2 
2. Run the win_service module with a wildcard in the name to search for a specific service (i.e. name: EventLo* )
3. The service is not found and is marked non-existent.
4. Install Ansible version 2.4.3
5. Repeat step 2.
6. Service is found and returned

```yaml
  - name: Check for existing Hub services
    win_service:
        name: Service_Version_1_*
    register: hub_service_check_stop

  - name: Stop Hub
    win_service:
        name: Service_Version_1_*
        state: stopped
    when: hub_service_check_stop.exists == true
```

##### EXPECTED RESULTS

The service Service_Version_1_102 is found and stopped.

##### ACTUAL RESULTS

The service Service_Version_1_102 was not found and nothing was done.

```
fatal: [uwreg005]: FAILED! => {"changed": false, "exists": false, "msg": "Service 'Service_Version_1_*' is not installed, need to set 'path' to create a new service"}
```

There was a recent change to win_service:
  win_service: fix when dealing with paths with special chars and chang…
  …e WMI to CIM cmdlets (#37897)
  * win_service: fix when dealing with paths with special chars and change WMI to CIM cmdlets

Where the line 
$svc = Get-Service -Name $name

Was changed to 
$svc = Get-Service | Where-Object { $_.Name -eq $name -or $_.DisplayName -eq $name }

This is causing the problem, as Where-Object does not accept wildcards.  
A solution would be reverting the change, or creating a special case when a wildcard is in the $name.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_service.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chrishoffman @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
This was done on purpose as win_service was/is never designed to support wildcards as part of the process. While it may have worked in the past there wasn't ever any guarantees that we would continue supporting it that way.

You would find that the idempotency would be broken as well in that case as each action only runs in case it was required, e.g. you had 2 services `service1` and `service2` where `service1` is running and `service2` is not. If you had the following task it would have reported no change as it only checked the service details from the first service

```
- win_service:
    name: service*
    state: running
```

What you should be doing is either one of the following

```
- win_shell: Stop-Service -Name Service_Version_1_*

# or
- name: get all services that match the wildcard Service_Version_1_*
  win_shell: (Get-Service -name Service_Version_1_*).Name
  register: services
  changed_when: no

- name: ensure all services are stopped
  win_service:
    name: '{{item}}'
    state: stopped
  with_items: '{{services.stdout_lines}}'
```

The 2nd option would occur a bit more overhead but it gives you the idempotency and better service stat information on return.
