### ISSUE TITLE
Module - proxmox_kvm - Creating clone with new mac address not possible

### ISSUE THREAD

**Issue by mxkle** [ansible/ansible#39519]
##### ISSUE TYPE
 - Bug Report
 
##### COMPONENT NAME
proxmox_kvm

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /mnt/it/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```
ANSIBLE_NOCOWS(/mnt/it/ansible/ansible.cfg) = True
DEFAULT_HOST_LIST(/mnt/it/ansible/ansible.cfg) = [u'/mnt/it/ansible/inventory/inventory.yml']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /mnt/it/ansible/inventory/.vault_pass
HOST_KEY_CHECKING(/mnt/it/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/mnt/it/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/mnt/it/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
ansible control machine:
```
Linux ubuntu 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
ansible managed machine:
```
Linux pve 4.13.16-1-pve #1 SMP PVE 4.13.16-45 (Wed, 28 Mar 2018 15:47:11 +0200) x86_64 GNU/Linux
pve-manager/5.1-46/ae8241d4 (running kernel: 4.13.16-1-pve)
```
##### SUMMARY
Using the clone function while also specifiying a new mac address results in a random mac.

##### STEPS TO REPRODUCE

```yaml
 - name: clone vm
    proxmox_kvm:
      api_user: "{{api_user}}"
      api_password: "{{api_password}}"
      api_host: "{{api_host}}"
      clone: "{{clone}}"
      #vmid: "{{vmid}}"
      newid: "{{newid | default(ommit)}}"
      name: "{{hostname}}"
      node: "{{node | default('pve')}}"
      net: '{"net0":"virtio=02:7D:52:B0:5F:59,bridge=vmbr2"}'
      storage: "{{storage}}"
      format: "{{format | default ('raw')}}"
      timeout: "{{timeout | default('120')}}"
```

##### EXPECTED RESULTS
net0 of new vm should have mac address 02:7D:52:B0:5F:59

##### ACTUAL RESULTS
net0 of new vm gets random mac assigned
gist of verbose output:
https://gist.github.com/mxkle/d88abac0ca5dc1c51cde633908b8fe5c
