### ISSUE TITLE
Won't run second play when getting host unreachable error in the first play within single playbook YAML file.

### ISSUE THREAD

**Issue by masaki-furuta** [ansible/ansible#39527]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/masaki/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 16:45:33) [GCC 8.0.1 20180222 (Red Hat 8.0.1-0.16)]

```

##### CONFIGURATION

```
$ ansible-config dump --only-changed
(no output)
```

##### OS / ENVIRONMENT

Fedora 28

##### SUMMARY

- I have an ansible playbook YAML file which contains 2 plays.
- First play has 1 or 2 target hosts and when the first play failed with error of all of remote hosts unreachable, then the second play won't run.
- If one of two can be reached, then the second play will run.
- Is this expected behaviour (documented) or (well-known) bug?

##### STEPS TO REPRODUCE

Failed case (second play won't run):

```yaml

$ cat ~/tmp/test.yml                                 
- name: first play
  hosts:
  - dummy1
  ignore_errors: yes
  tasks:
  - shell: uname

- name: second play
  hosts:
  - localhost
  ignore_errors: yes
  tasks:
  - shell: uname

$ ansible-playbook -i dummy1,localhost ~/tmp/test.yml

PLAY [first play] **************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [dummy1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname dummy1: Name or service not known\r\n", "unreachable": true}
	to retry, use: --limit @/home/masaki/tmp/test.retry

PLAY RECAP *********************************************************************
dummy1                     : ok=0    changed=0    unreachable=1    failed=0 
```

The second play will run, if the first play includes reachable hosts.
```
$ cat ~/tmp/test.yml                                 
- name: first play
  hosts:
  - dummy1
  - localhost
  ignore_errors: yes
  tasks:
  - shell: uname

- name: second play
  hosts:
  - localhost
  ignore_errors: yes
  tasks:
  - shell: uname

$ ansible-playbook -i dummy1,localhost ~/tmp/test.yml

PLAY [first play] **************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [dummy1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname dummy1: Name or service not known\r\n", "unreachable": true}
ok: [localhost]

TASK [shell] *******************************************************************
changed: [localhost]

PLAY [second play] *************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [shell] *******************************************************************
changed: [localhost]
	to retry, use: --limit @/home/masaki/tmp/test.retry

PLAY RECAP *********************************************************************
dummy1                     : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=4    changed=2    unreachable=0    failed=0 
```

##### EXPECTED RESULTS

The second play should run regardless of unreachable host error in the first play (?)

```
$ cat ~/tmp/test.yml                                 
- name: first play
  hosts:
  - dummy1
  ignore_errors: yes
  tasks:
  - shell: uname

- name: second play
  hosts:
  - localhost
  ignore_errors: yes
  tasks:
  - shell: uname

$ ansible-playbook -i dummy1,localhost ~/tmp/test.yml

PLAY [first play] **************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [dummy1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname dummy1: Name or service not known\r\n", "unreachable": true}
ok: [localhost]

PLAY [second play] *************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [shell] *******************************************************************
changed: [localhost]
	to retry, use: --limit @/home/masaki/tmp/test.retry

PLAY RECAP *********************************************************************
dummy1                     : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=2    changed=1    unreachable=0    failed=0 
```
##### ACTUAL RESULTS

```
ansible-playbook -i dummy1,localhost ~/tmp/test.yml

PLAY [first play] **************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [dummy1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname dummy1: Name or service not known\r\n", "unreachable": true}
	to retry, use: --limit @/home/masaki/tmp/test.retry

PLAY RECAP *********************************************************************
dummy1                     : ok=0    changed=0    unreachable=1    failed=0 
```
