### ISSUE TITLE
RabbitMQ - idempotency broken for queues when specifying arguments

### ISSUE THREAD

**Issue by greggilbert** [ansible/ansible#39522]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

rabbitmq_queue

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = ['/Users/gilbert/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/gilbert/REDACTED/ansible/_venv/lib/python3.6/site-packages/ansible
  executable location = /Users/gilbert/REDACTED/ansible/_venv/bin/ansible
  python version = 3.6.5 (default, Apr  3 2018, 19:14:47) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION

(none)

##### OS / ENVIRONMENT

OSX 10.13.4 connecting to Ubuntu 16.04

##### SUMMARY

When defining a queue, I include arguments for prioritization. Running the playbook command more than once throws this error: `RabbitMQ RESTAPI doesn't support attribute changes for existing queues`

##### STEPS TO REPRODUCE

```yaml
    - name: Setup queue
      rabbitmq_queue:
        login_user: guest
        login_password: guest
        name: my_ansible_queue
        state: present
        durable: yes
        arguments:
          x-max-priority: 10
```

##### EXPECTED RESULTS

Queue should be skipped since it already exists.

##### ACTUAL RESULTS

Error: 

```
fatal: [10.100.1.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "arguments": {
                "x-max-priority": 10
            },
            "auto_delete": false,
            "auto_expires": null,
            "dead_letter_exchange": null,
            "dead_letter_routing_key": null,
            "durable": true,
            "login_host": "localhost",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": "15672",
            "login_user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "max_length": null,
            "max_priority": null,
            "message_ttl": null,
            "name": "my_ansible_queue",
            "state": "present",
            "vhost": "/"
        }
    },
    "msg": "RabbitMQ RESTAPI doesn't support attribute changes for existing queues"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/messaging/rabbitmq_queue.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/messaging/rabbitmq_queue.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chrishoffman @hyperized @manuel-sousa
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by seeforschauer** [comment]
@greggilbert, please, try to use `max_priority` as specified in http://docs.ansible.com/ansible/latest/modules/rabbitmq_queue_module.html:

``` yaml
- name: Setup queue
      rabbitmq_queue:
        login_user: guest
        login_password: guest
        name: my_ansible_queue
        state: present
        durable: yes
        max_priority: 10
```

**Comment by jqueuniet** [comment]
I'm having the same issue with other arguments.

```- name: Setup queue
      rabbitmq_queue:
        login_user: guest
        login_password: guest
        name: my_ansible_queue
        state: present
        durable: yes
        x-dead-letter-exchange: qwertyuiop
        x-message-ttl: 20000
        ha-mode: all
```

```failed: [rabbitmq-infra-001] (item={'queue_name': 'my_ansible_queue', 'arguments': {'x-dead-letter-exchange': 'qwertyuiop', 'x-message-ttl': 20000, 'ha-mode': 'all'}}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "arguments": {
                "ha-mode": "all",
                "x-dead-letter-exchange": "qwertyuiop",
                "x-message-ttl": 20000
            },
            "auto_delete": false,
            "auto_expires": null,
            "dead_letter_exchange": null,
            "dead_letter_routing_key": null,
            "durable": true,
            "login_host": "hostname",
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_port": "15672",
            "login_user": "guest",
            "max_length": null,
            "max_priority": null,
            "message_ttl": null,
            "name": "my_ansible_queue",
            "state": "present",
            "vhost": "/"
        }
    },
    "msg": "RabbitMQ RESTAPI doesn't support attribute changes for existing queues"
}
```

**Comment by George-Yanev** [comment]
Adding 

- **x-message-ttl**
- **x-dead-letter-exchange**
- **x-dead-letter-routing-key** 

inside arguments parameter produced the observed behavior - `RabbitMQ RESTAPI doesn't support attribute changes for existing queues`.

Moving them to 3 separate parameters makes the task run idempotently.

Code tested with Ansible 2.6.4

**Second run will generate the attribute changes error:**

```
  - name: Set Queues
      rabbitmq_queue:
        name: test.queue
        arguments:
          { "x-dead-letter-exchage": "test.queue.dead",
            "x-dead-letter-routing-key": "test_key",
            "x-message-ttl": "300000" }

```
**Idempotent code:**

```
    - name: Set Queues
      rabbitmq_queue:
        name: test.queue
        dead_letter_exchange: test.queue.dead
        dead_letter_routing_key: test_key
        message_ttl: 300000
```
