### ISSUE TITLE
dynamodb_table does not support new aws encryption and other features

### ISSUE THREAD

**Issue by jpowers-j2** [ansible/ansible#39538]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

dynamodb_table

##### ANSIBLE VERSION

```
ansible 2.5.0
```
##### SUMMARY
Existing Dynamodb module lacks features that AWS provides via API at this point. We need support for following features:

Create global tables
enable dynamodb streams
Enable encryption at rest

alternately just the ability to pass generic extra options might allow these features to work

##### STEPS TO REPRODUCE

```yaml
  dynamodb_table:
    name:             "users"
    hash_key_name:    "userId"
    hash_key_type:    "STRING"
    read_capacity:    "5"
    write_capacity:   "5"
    # also needs:
    sse_specification: Enabled|Disabled
```

##### EXPECTED RESULTS

```
presently I can use aws cli to direct this json and make a table, where the SSESpecification item is a new feature of AWS that encrypts the data in the table

working json passed to aws cli:
{
        "AttributeDefinitions": [
            {
                "AttributeName": "UserId",
                "AttributeType": "S"
            }
        ],
        "TableName": "users",
        "KeySchema": [
            {
                "AttributeName": "UserId",
                "KeyType": "HASH"
            }
        ],
        "ProvisionedThroughput": {
            "ReadCapacityUnits": 5,
            "WriteCapacityUnits": 5
        },
        "SSESpecification": {
                "Enabled": true
        }
}
```

##### ACTUAL RESULTS

```
Ansible dynamodb_table doesn't know to pass the SSESpecification item to boto (which supports it) so nothing happens.
```
