### ISSUE TITLE
ec2: templating error 

### ISSUE THREAD

**Issue by Vaibhavarora08** [ansible/ansible#39545]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2

##### SUMMARY
I am trying to run an ansible playbook to create an ec2 instance but getting the error:-
WARNING]: provided hosts list is empty, only localhost is available
Output:--
```
PLAY [Create tomcat AWS infrastructure] ****************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [tomcat_aws : include] ****************************************************
included: /opt/devops/ansible/e2eproject/roles/tomcat_aws/tasks/aws-ec2.yml for localhost

TASK [tomcat_aws : Create an ec2 instance] *************************************
fatal: [localhost]: FAILED! => {"failed": true, "msg": "ERROR! template error while templating string: unexpected char u'c' at 54"}

PLAY RECAP *********************************************************************
localhost : ok=2 changed=0 unreachable=0 failed=1
```
The content of the file which is throwing error is :---####aws-ec2.yml#######
```yaml
name: Create an ec2 instance
ec2:
key_name: "{{ keypair }}"
aws_access_key: "REDACTED"
aws_secret_key: "REDACTED"
group: launch-wizard-4 # security group name
instance_type: "{{ t2.micro}}"
image: "{{ amzn-ami-hvm-2018.03.0.20180412-x86_64-gp2 (ami-467ca739)}}"
wait: true
region: "{{ region }}"
count: 1 # default
count_tag:
Name: "Demo"
instance_tags:
Name: "Demo"
vpc_subnet_id: "subnet-6285694c"
assign_public_ip: yes
register: ec2

debug:
msg: "{{ item['private_ip'] }}"
with_items: "{{ ec2.instances }}"

name: Add all web instance IPs to host group
add_host:
hostname: "{{ item.private_ip }}"
groupname: webservers
ansible_user: ec2-user
with_items: "{{ ec2.instances }}"

name: Wait for SSH to come up
wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
with_items: "{{ ec2.instances }}"
```
