### ISSUE TITLE
os_user failing to asign Default Project

### ISSUE THREAD

**Issue by geoffhigginbottom** [ansible/ansible#39554]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

os_user

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /ansible/ansible.cfg
  configured module search path = [u'/ansible/my_modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

CACHE_PLUGIN(/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/ansible/ansible.cfg) = /tmp/facts_cache
CACHE_PLUGIN_TIMEOUT(/ansible/ansible.cfg) = 300
DEFAULT_BECOME(/ansible/ansible.cfg) = True
DEFAULT_FORKS(/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = [u'/ansible/inventory']
DEFAULT_LOG_PATH(/ansible/ansible.cfg) = /ansible/log/ansible.log
DEFAULT_MODULE_PATH(/ansible/ansible.cfg) = [u'/ansible/my_modules']
DEFAULT_POLL_INTERVAL(/ansible/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/ansible/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/ansible/ansible.cfg) = 15
DEFAULT_TRANSPORT(/ansible/ansible.cfg) = smart
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
OpenStack deployed using OSA 16.0.10

##### SUMMARY

os_user module fails to set the "Primary Project ID" when adding a new user.  Output of play reports "default_project_id": null even though "default_project:" is populated with the name of the project.  If an invalid project name is used it throws an error so it is checking the projects, but failing to fetch the ID of the project.

##### STEPS TO REPRODUCE

Add a new user using the os_user module with the settings as per example below

```
I used the following settings in my playbook 

- name: Create '{{ username }}'
  os_user:
    cloud: '{{ my_cloud_name }}'
    endpoint_type: admin
    state: present
    name: '{{ username }}'
    password: '{{ password }}'
    update_password: on_create
    default_project: UI_Demo


My clouds.yaml has the following:

clouds:

  osa_test_env:
    auth:
      auth_url: http://n.n.n.n:5000/v3
      username: admin
      password: xxxxxxxxxxx
      project_name: admin
      tenant_name: admin
      user_domain_name: Default
      project_domain_name: Default
    region_name: RegionOne
    interface: internal

ansible:
  use_hostnames: True
  expand_hostvars: False
  fail_on_errors: True

```

##### EXPECTED RESULTS

User is added with a "Default Project" assinged

##### ACTUAL RESULTS

User is added but has no Default Project assigned

```
changed: [localhost] => {"changed": true, "user": {"default_project_id": null, "description": null, "domain_id": null, "email": null, "enabled": true, "id": "35b1ffb013544456a7f04bda37710520", "name": "demo-user1", "username": "demo-user1"}}
```
