### ISSUE TITLE
include_role with 'when' is always called if the variable is undefined

### ISSUE THREAD

**Issue by dkorel-copperleaf** [ansible/ansible#39565]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

include_role
##### ANSIBLE VERSION

```
2.5.2
```

##### CONFIGURATION

host_key_checking = False
retry_files_enabled = False
timeout = 30

##### OS / ENVIRONMENT

Ubuntu 16.04

##### SUMMARY
Using include_role with the when clause will always run if the variable is undefined

##### STEPS TO REPRODUCE

```yaml
  include_role:
    name: test
  when: foo == "bar"

ansible-playbook test.yml
```

##### EXPECTED RESULTS

The role should not be included if foo does not equal bar, and also if foo is undefined

##### ACTUAL RESULTS

the role is included when foo is undefined
