### ISSUE TITLE
All azure modules supporting tags ignore the append_tags parameter

### ISSUE THREAD

**Issue by melmorabity** [ansible/ansible#39574]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_common

##### ANSIBLE VERSION
```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/mohamed/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### OS / ENVIRONMENT
Fedora 27

```
$ pip list | grep -E "azure|adal"
adal (0.5.1)
azure (3.0.0)
azure-batch (4.1.3)
azure-cli-core (2.0.31)
azure-cli-nspkg (3.0.2)
azure-common (1.1.10)
azure-cosmosdb-nspkg (2.0.2)
azure-cosmosdb-table (1.0.2)
azure-datalake-store (0.0.19)
azure-eventgrid (0.1.0)
azure-graphrbac (0.40.0)
azure-keyvault (0.3.7)
azure-mgmt (2.0.0)
azure-mgmt-advisor (1.0.1)
azure-mgmt-applicationinsights (0.1.1)
azure-mgmt-authorization (0.30.0)
azure-mgmt-batch (4.1.0)
azure-mgmt-batchai (0.2.0)
azure-mgmt-billing (0.1.0)
azure-mgmt-cdn (2.0.0)
azure-mgmt-cognitiveservices (2.0.0)
azure-mgmt-commerce (1.0.1)
azure-mgmt-compute (2.1.0)
azure-mgmt-consumption (2.0.0)
azure-mgmt-containerinstance (0.3.1)
azure-mgmt-containerregistry (1.0.1)
azure-mgmt-containerservice (2.0.0)
azure-mgmt-cosmosdb (0.3.1)
azure-mgmt-datafactory (0.4.0)
azure-mgmt-datalake-analytics (0.3.0)
azure-mgmt-datalake-nspkg (2.0.0)
azure-mgmt-datalake-store (0.3.0)
azure-mgmt-devtestlabs (2.2.0)
azure-mgmt-dns (1.2.0)
azure-mgmt-eventgrid (0.4.0)
azure-mgmt-eventhub (1.2.0)
azure-mgmt-hanaonazure (0.1.0)
azure-mgmt-iothub (0.4.0)
azure-mgmt-iothubprovisioningservices (0.1.0)
azure-mgmt-keyvault (0.40.0)
azure-mgmt-loganalytics (0.1.0)
azure-mgmt-logic (2.1.0)
azure-mgmt-machinelearningcompute (0.4.0)
azure-mgmt-managementpartner (0.1.0)
azure-mgmt-marketplaceordering (0.1.0)
azure-mgmt-media (0.2.0)
azure-mgmt-monitor (0.4.0)
azure-mgmt-msi (0.1.0)
azure-mgmt-network (1.7.1)
azure-mgmt-notificationhubs (1.0.0)
azure-mgmt-nspkg (2.0.0)
azure-mgmt-powerbiembedded (1.0.0)
azure-mgmt-rdbms (0.2.0rc1)
azure-mgmt-recoveryservices (0.2.0)
azure-mgmt-recoveryservicesbackup (0.1.1)
azure-mgmt-redis (5.0.0)
azure-mgmt-relay (0.1.0)
azure-mgmt-reservations (0.1.0)
azure-mgmt-resource (1.2.2)
azure-mgmt-scheduler (1.1.3)
azure-mgmt-search (1.0.0)
azure-mgmt-servermanager (1.2.0)
azure-mgmt-servicebus (0.4.0)
azure-mgmt-servicefabric (0.1.0)
azure-mgmt-sql (0.7.1)
azure-mgmt-storage (1.5.0)
azure-mgmt-subscription (0.1.0)
azure-mgmt-trafficmanager (0.40.0)
azure-mgmt-web (0.32.0)
azure-nspkg (2.0.0)
azure-servicebus (0.21.1)
azure-servicefabric (6.1.2.9)
azure-servicemanagement-legacy (0.20.6)
azure-storage (0.35.1)
azure-storage-blob (1.1.0)
azure-storage-common (1.1.0)
azure-storage-file (1.1.0)
azure-storage-nspkg (3.0.0)
azure-storage-queue (1.1.0)
msrestazure (0.4.29)
```

##### SUMMARY
All Azure modules supporting tags seem to ignore the `append_tags` parameter. When updating a resource with new tags and `append_tags=True`, new tags completely override the current ones. Not the expected behaviour according to the modules' documentation.
Impacted modules:
* azure_rm_acs
* azure_rm_availabilityset
* azure_rm_dnszone
* azure_rm_image
* azure_rm_networkinterface
* azure_rm_publicipaddress
* azure_rm_resourcegroup
* azure_rm_securitygroup
* azure_rm_storageaccount
* azure_rm_storageblob
* azure_rm_virtualmachine
* azure_rm_virtualmachine_scaleset
* azure_rm_virtualnetwork

##### STEPS TO REPRODUCE

MWE playbook test.yml:
```
- hosts: localhost

  tasks:
    - name: delete RG
      azure_rm_resourcegroup:
        name: to_be_deleted
        location: westeurope
        state: absent
        subscription_id: XXXXX
        client_id: XXXXX
        secret: XXXXX
        tenant: XXXXX

    - name: create a new RG
      azure_rm_resourcegroup:
        name: to_be_deleted
        location: westeurope
        tags:
          first_tag: nothing
          second_tag: to_be_updated
        subscription_id: XXXXX
        client_id: XXXXX
        secret: XXXXX
        tenant: XXXXX

    - name: update RG tags
      azure_rm_resourcegroup:
        name: to_be_deleted
        location: westeurope
        append_tags: True
        tags:
          second_tag: updated
          third_tag: new
        subscription_id: XXXXX
        client_id: XXXXX
        secret: XXXXX
        tenant: XXXXX
```

##### EXPECTED RESULTS

After running the above playbook, tags for the to_be_deleted RG should be the following:
```
{
    "first_tag": "nothing",
    "second_tag": "updated",
    "third_tag": "new"
}
```

##### ACTUAL RESULTS
The to_be_deleted resource group tags are overriden by the update (confirmed by checking the RG on the Azure portal):
```
{
    "second_tag": "updated",
    "third_tag": "new"
}
```

Any Azure resource supported by Ansible Azure module have the same bug.

```
$ ansible-playbook -v test.yml
Using /etc/ansible/ansible.cfg as config file
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost
does not match 'all'


PLAY [localhost] ****************************************************************************************

TASK [Gathering Facts] **********************************************************************************
ok: [localhost]

TASK [delete RG] ****************************************************************************************
changed: [localhost] => {"changed": true, "contains_resources": false, "state": {"id": "/subscriptions/********/resourceGroups/to_be_deleted", "location": "westeurope", "name": "to_be_deleted", "provisioning_state": "Deleting", "status": "Deleted", "tags": {"second_tag": "updated", "third_tag": "new"}}}

TASK [create a new RG] **********************************************************************************
changed: [localhost] => {"changed": true, "contains_resources": false, "state": {"id": "/subscriptions/********/resourceGroups/to_be_deleted", "location": "westeurope", "name": "to_be_deleted", "provisioning_state": "Succeeded", "tags": {"first_tag": "nothing", "second_tag": "to_be_updated"}}}

TASK [update RG tags] ***********************************************************************************
changed: [localhost] => {"changed": true, "contains_resources": false, "state": {"id": "/subscriptions/********/resourceGroups/to_be_deleted", "location": "westeurope", "name": "to_be_deleted", "provisioning_state": "Succeeded", "tags": {"second_tag": "updated", "third_tag": "new"}}}

PLAY RECAP **********************************************************************************************
localhost                  : ok=4    changed=3    unreachable=0    failed=0
```
