### ISSUE TITLE
ansible win_psmodule version parameter

### ISSUE THREAD

**Issue by robcwaldron** [ansible/ansible#39583]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

win_psmodule

##### ANSIBLE VERSION

```
ansible 2.5.0
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY
Currently there is no way to set the PowerShell Module version. 

##### STEPS TO REPRODUCE

```yaml
- win_psmodule:
    name: xTimeZone
    state: present
    version: 1.6.0.0
```

##### EXPECTED RESULTS

Install the specified version of the powershell module from powershell gallery

##### ACTUAL RESULTS

There is no way to set the version of a powershell module. Only installing the latest, and then not having a way to update either. Once a module has been downloaded, the only way to update is remove the module and install again.

```

```
