### ISSUE TITLE
Hang when running as sudo/user for supervisorctl

### ISSUE THREAD

**Issue by brianmhunt** [ansible/ansible#3961]
I have a playbook with something like this:

``` yaml
- hosts: daemon
  port: 65268
  user: daemon
  tasks:
   # this task could do anything, but it gives a little flavour
   # of what's going on
    - name: Pull daemon from Github
      action: >
        git repo=ssh://git@github.com/brianmhunt/Daemon.git
        version={{ git_version|default("HEAD") }}
        dest=~daemon/daemon
      environment:
        GIT_SSH: /home/daemon/git_ssh.sh
      notify:
        - restart daemon

  handlers:
   # the following always hangs;
   # supervisorctl must be run as root.
    - name: restart daemon
      supervisorctl: name=daemon state=restarted
      sudo: yes
      # sudo_user: root does nothing
```

Note that the `Daemon.git` repository does not exist. The above is how I pull from a private repository.

When run it always hangs with something like this:

```
NOTIFIED: [restart daemon] ****************************
```

The playbook does not require a password at any point.

One would not expect a hang at this point. I suspect the problem is related to `supervisorctl` being run & called as root.

One workaround of course is to run `supervisord` as non-root, but I wanted to post this here in case others experienced a problem and there might be some straightforward solution.

Cheers.
