### ISSUE TITLE
mssql_db fatal error

### ISSUE THREAD

**Issue by bogski87** [ansible/ansible#39612]
##### ISSUE TYPE

 - Bug Report
##### COMPONENT NAME

mssql_db
##### ANSIBLE VERSION

```
2.5.0
```

##### CONFIGURATION

Main ansible config is unchanged. I copy the /etc/ansible directory for each project and change the config in there. 

The only changed part of the config in this is the hosts section. It was updated to look for host instead of /etc/ansible/host
##### OS / ENVIRONMENT

Ansible controller - Ubuntu 16.04 
Target machine - Windows 2016
##### SUMMARY

When running my playbook to set up a mssql database i get a fatal error followed by a long list of powershell errors.
##### STEPS TO REPRODUCE

```yaml
---
- name: Copy the SQL files over to temporary location and import them
  win_copy:
    src: files/sql/
    dest: c:\temp\deploy\
 

- name: Create MSSQL database for Database
  mssql_db:
    name: "{{database_name}}"
    login_user: "{{ sql_user }}"
    login_password: "{{ sql_password }}"
    state: import
    target: c:\temp\deploy\Database_Create.sql

- name: Create  User for Database
  mssql_db: 
    name: "{{database_name}}"
    login_user: "{{sql_user}}"
    login_password: "{{ sql_password }}"
    state: import
    target: c:\temp\deploy\Create_User.sql
```

##### EXPECTED RESULTS

I expected the sql script to be run and the database is created. If i run the script from SQL management tools it works.
##### ACTUAL RESULTS

TASK [sql-server : Copy the SQL files over to temporary location and import them] ************************************************************************************************************************************************************

task path: /home/philb/deploy-pph/roles/sql-server/tasks/main.yml:2
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/windows/win_copy.ps1
<192.168.1.64> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 192.168.1.64
checking if winrm_host 192.168.1.64 is an IPv6 address
EXEC (via pipeline wrapper)
ok: [192.168.1.64] => {
    "changed": false,
    "dest": "c:\\temp\\deploy\\",
    "operation": "folder_copy",
    "src": "files/sql/"
}

TASK [sql-server : Create MSSQL database for PPH Advertising Database] ***********************************************************************************************************************************************************************

task path: /home/philb/deploy-pph/roles/sql-server/tasks/main.yml:8
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/database/mssql/mssql_db.py
<192.168.1.64> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5985 TO 192.168.1.64
checking if winrm_host 192.168.1.64 is an IPv6 address
EXEC (via pipeline wrapper)
 [WARNING]: FATAL ERROR DURING FILE TRANSFER:

There is a lot of Powershell looking errors. I haven't pasted them i didnt want to break the formatting and couldn't find an attach option. I can upload it though and link to it.

What could be causing this to happen? the files are copied over and exist on the server when i look there but the task fails. 

Thanks
Phil

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/database/mssql/mssql_db.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/mssql/mssql_db.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Jmainguy @kenichi-ogawa-1988 @vedit
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by vedit** [comment]
Hello @bogski87,
This module was written to be executed on a linux machine. So if you'd add 
`delegate_to: 127.0.0.1` 
to your 2nd and 3rd tasks, and also fix your SQL file pathing, I believe you will achieve what you want.

**Comment by bogski87** [comment]
Hi @vedit 

Thanks for your reply. I tried as you suggested and added delegate_to: 127.0.0.1 but this didn't work. I tried with 'localhost' as well just to be sure. I've  commented out the other tasks for now until the DB creation part works. you said about sql file pathing so i removed the win_copy and changed the target to files/sql/Database_Create.sql, was this what you meant by that?

This is the task currently, it hasn't really changed all that much. 

```
- name: Create MSSQL database for Database
  mssql_db:
    delegate_to: 127.0.0.1
    name: "{{database_name}}"
    login_user: "{{ sql_user }}"
    login_password: "{{ sql_password }}"
    state: import
    target: files/sql/Database_Create.sql
```

The application/database i'm provisioning with this runs on a windows machine so it would be awesome if i could get this working. 

Thanks,

PhilB

**Comment by vedit** [comment]
Hello @bogski87,
Can you try it like the following:
```
- name: Create MSSQL database for Database
  mssql_db:
    name: "{{database_name}}"
    login_user: "{{ sql_user }}"
    login_password: "{{ sql_password }}"
    state: import
    target: files/sql/Database_Create.sql
  delegate_to: 127.0.0.1
```
