### ISSUE TITLE
Add LGPO support

### ISSUE THREAD

**Issue by maxnh** [ansible/ansible#39633]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

Possibility to set Local Group Policy objects.

##### OS / ENVIRONMENT

Microsoft Windows

##### SUMMARY

It would be nice if I could add some Group Policy Settings to a machine via an Ansible playbook. E.g. salt has implemented such a feature:
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_lgpo.html
This would allow me to use Ansible to configure Windows clients without the need of having a central Windows Domain Server.

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
I agree this would be nice to have, unfortunately it would require a lot of work with mapping values to how they need to be applied. Just having a quick glance at Salt's implementation and it is over 6000 lines of code!

In saying that it is definitely a nice thing to have as it removes the requirement of the end user knowing how to apply that specific policy.

**Comment by daBONDi** [comment]
Found something maybe worth investigating using this base .Net Class for it

https://github.com/dlwyatt/PolicyFileEditor

Or you could try to use the win_dsc module and use this dsc resource for it, i never tryed it out but maybe you can go forward on it with this

**Comment by dagwieers** [comment]
Looking at [Salt's implementation](https://github.com/saltstack/salt/blob/develop/salt/modules/win_lgpo.py), they do have a mapping between policy and API, but I expect a PowerShell implementation to be much easier to write than what they have to do in Python. Less than 6000 lines of PowerShell I would hope.

But maybe all we need is [a wrapper for **lgpo.exe**](http://www.brookspeppin.com/blog/how-to-individually-modify-and-deploy-local-gpo-settings-lgpo) ?

**Comment by maxnh** [comment]
I have now also taken a look at Salt's implementation. It looks like this is only supporting Group Policy Objects that are included in the Salt code. I think this is not a good path to follow since this will require a lot of maintenance with each change done by Microsoft. The LGPO.EXE ([Microsoft Blog](https://blogs.technet.microsoft.com/secguide/2016/01/21/lgpo-exe-local-group-policy-object-utility-v1-0/)) looks like it could do the job. First, one would call LGPO to export a TXT file of the current policy. Then this file has to be parsed by Ansible and compared against the desired configuration. Afterwards, the (potentially) corrected file is written to disk by Ansible and then applied by LGPO.

It looks like LGPO.EXE supports both Computer and User configuration. However, I am not sure whether LGPO can also handle Security policies for the registry. 
The PDF included in the [ZIP-Download of LGPO.EXE](https://www.microsoft.com/en-us/download/details.aspx?id=55319) shows nicely the possibilities of LGPO.exe. It is basically a detailed documentation,

**Comment by jborean93** [comment]
I'm not sure lgpo.exe is a good choice, the trouble with Salt's implementation is that it has manually defined the process for the majority of the group policy objects on the host which is a massive maintenance burden. Personally it would be great to have this but the cost of implementing and supporting it is a massive turn off.

**Comment by ShachafGoldstein** [comment]
A snippet I wrote and checked a bit that might help, notice that it only works for settings originating from admx files.

Security settings come from security templates

```
$src = $null
$src = "Windows Components\BitLocker Drive Encryption\Operating System Drives\Configure use of hardware-based encryption for operating system drives"

$adml = $null
$admx = $null

# Get lang to check against
$adml = Get-ChildItem -Path C:\Windows\PolicyDefinitions -Filter *.adml -Recurse
$admx = Get-ChildItem -Path C:\Windows\PolicyDefinitions -Filter *.admx -Recurse

$res = $null
$res = $adml | % {Select-String -Pattern (Split-Path $src -Leaf) -Path $_.fullname}

$m = $null
$m = [regex]::Matches($res.line,'id=(.*?)>').groups[1].value.replace('"','')

$res2 = $null
$res2 = $admx | % {Select-String -Pattern $m -Path $_.fullname}

$cont = [XML](get-content $res2.path)

$node = $null
$node = (Select-Xml -Xml $cont -XPath "//*[@name='$m']").Node

# Make sure path is ok - maybe should be recursive ?
$cat = $null
$cat =  $node.parentCategory.ref

$cat_res = $null
$cat_res = $adml | % {Select-String -Pattern "$cat" -Path $_.fullname}

$cat_str = $null
$cat_str = [regex]::Matches($cat_res.line,'>(.*?)<').groups[1].value.replace('"','')

if ($cat_str -ieq (Split-Path (Split-Path $src) -Leaf))
{
 $node
}
```

**Comment by cwegener** [comment]
I just found out about this discussion and wanted to share my experience.

I have recently started using the PowerShell module and DSC resource that
@daBONDi is referring to in his comment above.

In my experience the PolicyFileEditor DSC resource is able to cover a very
large percentage of my use cases.

The only LGPO items that I have found not to be manageable via the
PolicyFileEditor so far are the 'Site to Zone Assignment List' setting, which
seems to require some additional manual work in order to take effect.

I'm sure that the PolicyFileEditor PS module has a few more gaps that don't
work.

But I am going to stick with it since it is a very workable solution that can
be implemented in my Ansible roles right now.

**Comment by jborean93** [comment]
Closing as while this would be nice, the overhead of maintaining all this in an Ansible module is not something we are wanting to really do. As mentioned there are DSC resources available and we are happy to have a module that manipulates certain policy sections that are grouped together (like win_user_right) but having a catch all will just become too complex and hard to document properly.

**Comment by so87** [comment]
@cwegener can you post an example?

**Comment by jamescassell** [comment]
Even just a simple wrapper around LGPO.EXE would be quite helpful...

**Comment by cwegener** [comment]
@so87 

User policies (NonAdmins):

```yaml
- name: Ensure Local Policy Settings are set . User
  # Search for relevant GP settings here
  # https://gpsearch.azurewebsites.net/
  win_dsc:
    resource_name: "cAdministrativeTemplateSetting"
    policytype: "NonAdministrators"
    keyvaluename: "Software\\Policies\\Microsoft\\Windows\\System\\DisableCMD"
    data: "2"
    type: "Dword"
```

Machine Policy:

```yaml
- name: Ensure Local Policy Settings are set . Computer
  # Search for relevant GP settings here
  # https://gpsearch.azurewebsites.net/
  win_dsc:
    resource_name: "cAdministrativeTemplateSetting"
    policytype: "Machine"
    keyvaluename: "Software\\Policies\\Microsoft\\Windows\\Server\\ServerManager\\DoNotOpenAtLogon"
    data: "1"
    type: "Dword"
```
