### ISSUE TITLE
templated tag variable is undefined in include_tasks when used in a loop

### ISSUE THREAD

**Issue by hinrikus** [ansible/ansible#39637]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

- include_tasks
- with_items

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/hinrikus/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
```

##### CONFIGURATION

```
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

In a loop, e.g. `with_items`, we are using `include_tasks`. 
In the included task, we want to use dynamic tags depending on `item`.
Ansible outputs the error:
```
ERROR! 'item' is undefined
```
That is unexpected behaviour because it works with "normal" variables. 

##### STEPS TO REPRODUCE

```yaml
#file: roles/foo/tasks/main.yml
---
- include_tasks: app.yml
  with_items: 
    - item1
    - item2

#file: roles/foo/tasks/app.yml
---
- debug:
    msg: "item = {{ item }}"
  tags:
    - "{{ item }}"
```

##### EXPECTED RESULTS

We would expect to see the debug message.

##### ACTUAL RESULTS

The mentioned error message above and nothing else.

```
TASK [foo : include_tasks] ******************************************************************
task path: /tmp/ansible_test/roles/foo/tasks/main.yml:3
included: /tmp/ansible_test/roles/foo/tasks/app.yml for localhost
ERROR! 'item' is undefined
```
