### ISSUE TITLE
Python3 support for github_deploy_key

### ISSUE THREAD

**Issue by Denubis** [ansible/ansible#39651]
##### ISSUE TYPE

 - Bug Report
 - Documentation Report

##### COMPONENT NAME

github_deploy_key

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/brian/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

```

##### OS / ENVIRONMENT

Host: Ubuntu 17.10
Managed host: Ubuntu 16.04

In my /etc/ansible/hosts I am invoking python3: 
[jekyll:vars]
ansible_python_interpreter=/usr/bin/python3

(because it fails on python2)

##### SUMMARY

When trying to add a deploy key to a github repo, there are two issues.
1 (documentation): Your documentation does not note that the deploy-key account needs admin permissions on the repo it is adding keys to
2 (python3 bug): when using the github_deploy_key module, I get a JSON object must be str error.

##### STEPS TO REPRODUCE

```yaml

# This works

#    - name: Update github with the deploy key
#      uri:
#        url: "https://api.github.com/repos/mqAncientHistory/mqancienthistory.github.io/keys"
#        headers:
#          Content-Type: application/json
#          authorization: token {{github_access_token}}
#        method:         POST
#        body_format:    json
#        status_code:    201
#        return_content: yes
#        body:
#          title:        "ansible-deploy-key-{{machine}}"
#          key:          "{{ ssh_pub_key.stdout }}"
#          read_only:    "true"
#          force:        "true"

# This does not
    - name: 'Push key to github '
      github_deploy_key: 
        owner: "mqAncientHistory"
        repo: "mqancienthistory.github.io"
        name: "ansible-deploy-key-{{machine}}"
        key: "{{ ssh_pub_key.stdout }}"
        read_only: yes
        force: yes
        token: "{{github_access_token}}"
```

##### EXPECTED RESULTS

For the key to be added.

##### ACTUAL RESULTS

```
fatal: [REDACTED]: FAILED! => {
    "changed": false, 
    "module_stderr": "OpenSSH_7.5p1 Ubuntu-10ubuntu0.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /home/brian/.ssh/config\r\ndebug1: /home/brian/.ssh/config line 160: Applying options for *\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 1 remote\r\ndebug1: Requesting forwarding of remote forward LOCALHOST:52698 -> 127.0.0.1:52698\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 6876\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 1\r\nShared connection to REDACTED closed.\r\n", 
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_6mtd2yew/ansible_module_github_deploy_key.py\", line 318, in <module>\r\n    main()\r\n  File \"/tmp/ansible_6mtd2yew/ansible_module_github_deploy_key.py\", line 309, in main\r\n    key_id = deploy_key.get_existing_key(key, name, force)\r\n  File \"/tmp/ansible_6mtd2yew/ansible_module_github_deploy_key.py\", line 203, in get_existing_key\r\n    response_body = json.loads(resp.read())\r\n  File \"/usr/lib/python3.5/json/__init__.py\", line 312, in loads\r\n    s.__class__.__name__))\r\nTypeError: the JSON object must be str, not 'bytes'\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

```
