### ISSUE TITLE
digital_ocean_block_storage stopped working

### ISSUE THREAD

**Issue by CarlosEspejo** [ansible/ansible#39655]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

digital_ocean_block_storage

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /Users/carlos/.ansible.cfg
  configured module search path = [u'/Users/carlos/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION

ALLOW_WORLD_READABLE_TMPFILES(/Users/carlos/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/Users/carlos/.ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = [u'/Users/carlos/playbooks/roles']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/carlos/.vault.txt
HOST_KEY_CHECKING(/Users/carlos/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/carlos/.ansible.cfg) = False

##### OS / ENVIRONMENT

Running Ansible on MacOS High Sierra to manage Ubuntu 16.04 
##### SUMMARY

When I try to create a DigitalOcean Block store using the digital_ocean_block_storage module I get this error
```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: KeyError: 'message'
failed: [localhost] (item={u'owner': u'ubuntu', u'fstype': u'xfs', u'mount_name': u'backup', u'name': u'archive-staging-backup3', u'size': 100}) => {"changed": false, "item": {"fstype": "xfs", "mount_name": "backup", "name": "archive-staging-backup3", "owner": "ubuntu", "size": 100}, "msg": "Unable to load message"}
```
##### STEPS TO REPRODUCE

```yaml
- name: Create block storage
  digital_ocean_block_storage:
    state: present
    command: create
    region: "{{ do_region }}"
    block_size: "{{ item.size }}"
    volume_name: "{{ item.name }}"
  with_items: "{{ do_blocks }}"
  register: do_blocks_created

- name: Attach block storage
  digital_ocean_block_storage:
    state: present
    command: attach
    region: "{{ do_region }}"
    volume_name: "{{ item.name }}"
    droplet_id: "{{ do.droplet.id }}"
  with_items: "{{ do_blocks }}"
  when: do_blocks_created is defined
```

##### EXPECTED RESULTS

It should create the volume and register do_blocks_created then in the next step it should attach the volume to the droplet.
##### ACTUAL RESULTS

So the volume does get created but the error below is thrown. If you re-run the play at this point it doesn't recognize that the volume already exists and throws "failed to create volume".

```
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/p5/m7r6p0795rg49s603ry355780000gn/T/ansible_cFlE1K/ansible_module_digital_ocean_block_storage.py", line 285, in main
    handle_request(module)
  File "/var/folders/p5/m7r6p0795rg49s603ry355780000gn/T/ansible_cFlE1K/ansible_module_digital_ocean_block_storage.py", line 259, in handle_request
    block_storage.create_block_storage()
  File "/var/folders/p5/m7r6p0795rg49s603ry355780000gn/T/ansible_cFlE1K/ansible_module_digital_ocean_block_storage.py", line 213, in create_block_storage
    raise DOBlockStorageException(json['message'])
KeyError: 'message'

failed: [localhost] (item={u'owner': u'ubuntu', u'fstype': u'xfs', u'mount_name': u'backup', u'name': u'archive-staging-backup3', u'size': 100}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_token": null,
            "block_size": 100,
            "command": "create",
            "description": null,
            "droplet_id": null,
            "region": "sfo2",
            "snapshot_id": null,
            "state": "present",
            "timeout": 10,
            "volume_name": "archive-staging-backup3"
        }
    },
    "item": {
        "fstype": "xfs",
        "mount_name": "backup",
        "name": "archive-staging-backup3",
        "owner": "ubuntu",
        "size": 100
    },
    "msg": "Unable to load message"
}
```
