### ISSUE TITLE
grafana_dashboard fails with Grafana v5.0

### ISSUE THREAD

**Issue by rrey** [ansible/ansible#39663]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
grafana_dashboard

##### ANSIBLE VERSION
```
ansible 2.5.0
  config file = /Users/remirey/dev/grtgas/avignon/ansible.cfg
  configured module search path = [u'/Users/remirey/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/remirey/.virtualenvs/avignon/lib/python2.7/site-packages/ansible
  executable location = /Users/remirey/.virtualenvs/avignon/bin/ansible
  python version = 2.7.13 (default, Jul 18 2017, 09:17:00) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

##### CONFIGURATION
```
DEFAULT_GATHERING(/Users/remirey/dev/grtgas/avignon/ansible.cfg) = explicit
DEFAULT_HASH_BEHAVIOUR(/Users/remirey/dev/grtgas/avignon/ansible.cfg) = replace
DEFAULT_MANAGED_STR(/Users/remirey/dev/grtgas/avignon/ansible.cfg) = Please do not change this file directly since it is managed by Ansible and will be overwritten
DEFAULT_VAULT_PASSWORD_FILE(/Users/remirey/dev/grtgas/avignon/ansible.cfg) = /Users/remirey/dev/grtgas/avignon/ansible_vault_password
HOST_KEY_CHECKING(/Users/remirey/dev/grtgas/avignon/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/remirey/dev/grtgas/avignon/ansible.cfg) = False
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY

When executing a dashboard creation to test idempotency, the second execution fails with the following error:

```
The full traceback is:
  File "/var/folders/nx/br96pdj13gd30xmz81_fpsw00000gn/T/ansible_NgOhbA/ansible_module_grafana_dashboard.py", line 307, in main
    result = grafana_create_dashboard(module, module.params)
  File "/var/folders/nx/br96pdj13gd30xmz81_fpsw00000gn/T/ansible_NgOhbA/ansible_module_grafana_dashboard.py", line 215, in grafana_create_dashboard
    raise GrafanaAPIException('Unable to create the new dashboard %s : %s - %s.' % (slug, info['status'], info))

failed: [localhost] (item={u'path': u'aws_ecs.json', u'slug': u'aws_ecs'}) => {
    "changed": false,
    "invocation": {
        "module_args": {
            "grafana_api_key": null,
            "grafana_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "grafana_url": "<some_url>",
            "grafana_user": "<some_user>",
            "message": "Updated by ansible",
            "org_id": 1,
            "overwrite": true,
            "path": "files/grafana/dashboards/aws_ecs.json",
            "slug": "aws_ecs",
            "state": "present",
            "validate_certs": true
        }
    },
    "item": {
        "path": "aws_ecs.json",
        "slug": "aws_ecs"
    },
    "msg": "error : Unable to create the new dashboard aws_ecs : 412 - {'body': '{\"message\":\"The dashboard has been changed by someone else\",\"status\":\"version-mismatch\"}', 'date': 'Thu, 03 May 2018 09:37:05 GMT', 'content-length': '88', 'status': 412, 'url': '<some_url>/api/dashboards/db', Expires=Thu, 10 May 2018 09:37:05 GMT; Path=/', 'content-type': 'application/json', 'connection': 'close', 'msg': 'HTTP Error 412: Precondition Failed'}."
```

##### STEPS TO REPRODUCE

```
    - name: Import the Grafana dashboards
      grafana_dashboard:
        grafana_url: <some_url>
        grafana_user: "{{ grafana_admin_user }}"
        grafana_password: "{{ grafana_admin_password }}"
        state: present
        message: Updated by ansible
        overwrite: yes
        path: "files/grafana/dashboards/{{ item.path }}"
        slug: "{{ item.slug }}"
      with_items:
        - path: aws_ecs.json
          slug: aws_ecs
```

The meta section was added manually in the dashboard json to have the import work in the first place.

##### EXPECTED RESULTS
Idempotency works and second execution marks the task "ok" and not "changed".

##### ACTUAL RESULTS
Exception

```
The full traceback is:
  File "/var/folders/nx/br96pdj13gd30xmz81_fpsw00000gn/T/ansible_NgOhbA/ansible_module_grafana_dashboard.py", line 307, in main
    result = grafana_create_dashboard(module, module.params)
  File "/var/folders/nx/br96pdj13gd30xmz81_fpsw00000gn/T/ansible_NgOhbA/ansible_module_grafana_dashboard.py", line 215, in grafana_create_dashboard
    raise GrafanaAPIException('Unable to create the new dashboard %s : %s - %s.' % (slug, info['status'], info))
```
