### ISSUE TITLE
Check_mode must be explicitely disabled in a task using execute_lambda

### ISSUE THREAD

**Issue by teamhanded** [ansible/ansible#39679]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

execute_lambda

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = None
  configured module search path = [u'/Users/aux-admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Jan  6 2018, 12:16:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

Mac OS High Sierra v10.13.4

##### SUMMARY

execute_lambda returns HTTP 204 status code when check_mode is **NOT** explicitely set to false, and disregards execute_lambda's **dry_run** parameter, which should return 204 if set, according to AWS SDK.

##### STEPS TO REPRODUCE

```
---
- hosts: localhost
  tasks:
  - name: "Run AWS Lambda function"
    check_mode: no
    execute_lambda:
      name: functionName
      wait: true
      payload:
        firstParameter: "1"
    register: variable
```

If you remove **check_mode: no**, it will return 204 status code.

##### EXPECTED RESULTS

    "result": {
        "logs": "",
        "output": "output here",
        "status": 200
##### ACTUAL RESULTS

    "result": {
        "logs": "",
        "output": "",
        "status": 204

```

```
