### ISSUE TITLE
import_role docs shows example with a loop, which doesn't work

### ISSUE THREAD

**Issue by agaffney** [ansible/ansible#39672]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
import_role

##### ANSIBLE VERSION
```
ansible 2.5.2
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
The docs for `import_role` show an example of using it in a loop. This doesn't actually work. With a task like the following:

```yaml
    - import_role:
        name: foo
      with_sequence: start=1 count=5
```

you get:

```
ERROR! You cannot use 'static' on an include_role with a loop
```

##### STEPS TO REPRODUCE
N/A

##### EXPECTED RESULTS
N/A

##### ACTUAL RESULTS
N/A
