### ISSUE TITLE
copy is Failed to connect to the host via ssh

### ISSUE THREAD

**Issue by meteorice** [ansible/ansible#39680]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

copy
##### ANSIBLE VERSION

```
ansible 2.3.1.0
  config file = /data/amc/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

[defaults]
inventory=~/ansible_hosts
remote_port=22
host_key_checking=False
forks=50
timeout = 10
stdout_callback = json
retry_files_enabled = False
callback_plugins = /data/amc/script/callback
[ssh_connection]
pipelining = True
##### OS / ENVIRONMENT

NAME="CentOS Linux"
VERSION="7 (Core)"
##### SUMMARY

i use copy module ,something is ok,but  this is Failed. what happen?why
##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  remote_user: '{{ user }}'
  gather_facts: False
  tasks:
      - name: reload crm3 config
        copy: 'src={{srcpath}} dest={{destpath}} backup=Yes mode=0755'
        remote_user: '{{ user }}'
      - name: reload nginx
        shell: "~/bin/reloadnx.sh"
        remote_user: '{{ user }}'
        args:
            executable: /bin/bash

```

##### ACTUAL RESULTS

```json
{
    "plays": [
        {
            "play": {
                "id": "005056a3-195d-6c74-6f53-000000000002", 
                "name": "all"
            }, 
            "tasks": [
                {
                    "hosts": {
                        "133.38.38.11": {
                            "changed": false, 
                            "msg": "Failed to connect to the host via ssh: OpenSSH_7.5p1, OpenSSL 1.0.2k  26 Jan 2017\r\ndebug1: Reading configuration data /usr/etc/ssh_config\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 139454\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 127\r\nConnection closed\r\n", 
                            "unreachable": true
                        }
                    }, 
                    "task": {
                        "id": "005056a3-195d-6c74-6f53-000000000004", 
                        "name": "reload crm3 config"
                    }
                }
            ]
        }
    ], 
    "stats": {
        "133.38.38.11": {
            "changed": 0, 
            "failures": 0, 
            "ok": 0, 
            "skipped": 0, 
            "unreachable": 1
        }
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/copy.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/copy.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
The relevant error message is in the SSH connection: `debug3: mux_client_read_packet: read header failed: Broken pipe`. [This article](https://access.redhat.com/solutions/3191222) suggests updating OpenSSH may help.

Duplicate of #32585

Are you able to use the `ping` module against the host just to verify the SSH connection is working? Have you tried with a newer version of Ansible?

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

needs_info

**Comment by meteorice** [comment]
@samdoran 
shell and ping module is working.  
i find the sftp is fail in this machine. copy module is depend on sftp?

**Comment by samdoran** [comment]
Please ask questions like this on IRC or the mailing list as you'll get a must faster response.

From `ansible-config list`:

```
DEFAULT_SCP_IF_SSH:
  default: smart
  description: [Prefered method to use when transfering files over ssh, 'When set
      to smart, Ansible will try them until one succeeds or they all fail', 'If set
      to True, it will force ''scp'', if False it will use ''sftp''']
  env:
  - {name: ANSIBLE_SCP_IF_SSH}
  ini:
  - {key: scp_if_ssh, section: ssh_connection}
```
