### ISSUE TITLE
Unable to set hostnames using only a tag's value

### ISSUE THREAD

**Issue by cignul9** [ansible/ansible#39697]
##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME
aws_ec2 inventory plugin

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = ~/ansible/ansible.cfg
  configured module search path = [u'~/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/env/lib/python2.7/site-packages/ansible
  executable location = /opt/env/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING = True
ANSIBLE_SSH_ARGS = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
ANSIBLE_SSH_CONTROL_PATH = %(directory)s/ansible-ssh-%%h-%%p-%%r
ANSIBLE_SSH_CONTROL_PATH_DIR = /tmp/.ansible/cp
CACHE_PLUGIN = memory
DEFAULT_ACTION_PLUGIN_PATH = [u'~/ansible/plugins/action_plugins']
DEFAULT_BECOME = True
DEFAULT_BECOME_ASK_PASS = False
DEFAULT_BECOME_METHOD = sudo
DEFAULT_CALLBACK_PLUGIN_PATH = [u'~/ansible/plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH = [u'~/ansible/plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH = [u'~/ansible/plugins/filter_plugins']
DEFAULT_FORKS = 5
DEFAULT_GATHERING = implicit
DEFAULT_HASH_BEHAVIOUR = merge
DEFAULT_HOST_LIST = [u'~/ansible/inventory', u'~/ansible/plugins/inventory/useast1.aws_ec2.yml']
DEFAULT_JINJA2_EXTENSIONS = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_LOG_PATH = ~/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH = [u'~/ansible/plugins/lookup_plugins']
DEFAULT_MANAGED_STR = Ansible managed: {file} modified on %Y-%m-%d %H:%M:%S by {uid} on {host}
DEFAULT_MODULE_LANG = C
DEFAULT_POLL_INTERVAL = 15
DEFAULT_PRIVATE_KEY_FILE = ~/identities/ansible.pem
DEFAULT_SCP_IF_SSH = true
DEFAULT_STDOUT_CALLBACK = skippy
DEFAULT_TIMEOUT = 10
DEFAULT_TRANSPORT = smart
DEFAULT_VARS_PLUGIN_PATH = [u'~/ansible/plugins/vars_plugins']
DEFAULT_VAULT_PASSWORD_FILE = ~/vault-pass.txt
DEPRECATION_WARNINGS = False
HOST_KEY_CHECKING = False
INVENTORY_ENABLED = ['host_list', 'script', 'yaml', 'ini', 'aws_ec2']
RETRY_FILES_ENABLED = False
```
##### OS / ENVIRONMENT
CentOS 7.4.1708

##### SUMMARY
Greetings, dev_Ansible.  devops_I am very pleased with this latest version of software_Ansible, version 2.5 which features the feature_ability to mix and match inventory data_sources, or perhaps this all started with an earlier software_version.  In any case I was telling my boss, boss_Stacy, how this would make adopting a dynamic data_inventories much easier for devops_me.  However, the info_docs are a little sparse and while attempting to understand the examples (given link_here: https://docs.ansible.com/ansible/2.5/plugins/inventory/aws_ec2.html) for creating meta_hostnames from data_variables, devops_I had what I'm sure is a novel abstract_idea:

What if meta_hostnames, and meta_groups could be more easily created without an underscore-delimited useless_prefix?  Forget about meta_groups for now and let's just talk about meta_hostnames.  devops_I would like to demonstrate what devops_I mean, so from here on out devops_I'll omit them.

Your example for generating DYNAMIC inventories ironically requires us to specify the tag key AND value to form a hostname.  These are mangled together to form "Name_Tag1" and "Name_Tag2" in your example.  For the life of me I can't figure out how this is useful.  Can you please explain here, and maybe in some updated documentation, how I might set the hostname by simply fetching the value of a tag having a given key, say "Name"?  I have tried testing variations on tag-key and I'm shot down for violating syntax with every attempt.  What's the secret sauce please?  Does this capability exist?  If not, will you please add it?

##### STEPS TO REPRODUCE
```yaml
---
plugin:                                             aws_ec2
boto_profile:                                       default
regions:                                            [us-east-1]
strict_permissions:                                 False
filters:
  instance-state-name:                              running
hostnames:
  -                                                 <some unknown configuration here>
  -                                                 private-ip-address
groups:
# It would be nice to have the same kind of functionality I'm describing for hostnames, only for groups too, so that this kind of config isn't also necessary for each group I want to use.
  useast1_scc:                                      tags['Provisioning Group'] == 'useast1_scc'
  useast1_com:                                      tags['Provisioning Group'] == 'useast1_com'
```
##### EXPECTED RESULTS
When I configure a list item in the hostnames section with some kind of filter-y goodness the hostname of the instance is set with the value in the tag having the specified key name(!)

##### ACTUAL RESULTS
No useful example is given that generates an inventory with dynamically derived hostnames.  Instead the tag values must be known and configured in advance if we're to believe the example.
