### ISSUE TITLE
Block when overriden by internal register

### ISSUE THREAD

**Issue by common-cranberry** [ansible/ansible#39713]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

block

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:		16.04
Codename:	xenial
```

##### STEPS TO REPRODUCE

```yaml
- name: <installer> detect:{{process}}
  shell: which {{process}}
  register: result
  changed_when: false
  failed_when: false
- when: result.rc == 1
  block:
  - name: <installer> location:{{process}}
    tempfile:
      state: file
      suffix: installer
    register: result
  - name: <installer> download:{{process}}
    get_url:
      url: "{{installer}}"
      dest: "{{result.path}}"
      mode: 0700
  - name: <installer> install:{{process}}
    shell: "{{result.path}}"
```

##### EXPECTED RESULTS

```
TASK [<installer> detect:helm] ************************************************************************************************
ok: [localhost]

TASK [<installer> location:helm] **********************************************************************************************
skipping: [localhost]

TASK [<installer> download:helm] **********************************************************************************************
skipping: [localhost]
```
##### ACTUAL RESULTS

```
TASK [<installer> detect:helm] ************************************************************************************************
ok: [localhost]

TASK [<installer> location:helm] **********************************************************************************************
skipping: [localhost]

TASK [<installer> download:helm] **********************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The conditional check 'result.rc == 1' failed. The error was: error while evaluating conditional (result.rc == 1): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/root/playbooks/util-installer.yml': line 14, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    register: result\n  - name: <installer> download:{{process}}\n    ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
```
