### ISSUE TITLE
ec2 module doesn't auto assign IPv6 even if subnet is configured to.

### ISSUE THREAD

**Issue by rwky** [ansible/ansible#39734]
<!---
Verify first that your issue/request is not already reported on GitHub.
THIS FORM WILL BE READ BY A MACHINE, COMPLETE ALL SECTIONS AS DESCRIBED.
Also test if the latest release, and devel branch are affected too.
ALWAYS add information AFTER (OUTSIDE) these html comments.
Otherwise it may end up being automatically closed by our bot. -->

##### ISSUE TYPE
<!--- Pick one below and delete the rest -->
 - Bug Report

##### COMPONENT NAME
<!--- Insert, BELOW THIS COMMENT, the name of the module, plugin, task or feature.
Do not include extra details here, e.g. "vyos_command" not "the network module vyos_command" or the full path-->
ec2

##### ANSIBLE VERSION
<!--- Paste, BELOW THIS COMMENT, verbatim output from "ansible --version" between quotes below -->
```
ansible 2.5.2
  config file = /home/rowan/projects/ivoryresearch/ansible/ansible.cfg
  configured module search path = [u'/home/rowan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rowan/projects/ivoryresearch/ansible/local/lib/python2.7/site-packages/ansible
  executable location = /home/rowan/projects/ivoryresearch/ansible/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
<!--- If using Ansible 2.4 or above, paste, BELOW THIS COMMENT, the results of "ansible-config dump --only-changed"
Otherwise, mention any settings you have changed/added/removed in ansible.cfg
(or using the ANSIBLE_* environment variables).-->
N/A

##### OS / ENVIRONMENT
<!--- Mention, BELOW THIS COMMENT, the OS you are running Ansible from, and the OS you are
managing, or say "N/A" for anything that is not platform-specific.
Also mention the specific version of what you are trying to control,
e.g. if this is a network bug the version of firmware on the network device.-->
N/A

##### SUMMARY
<!--- Explain the problem briefly -->
When creating an instance using the ec2 module in a VPC where all subnets have IPv6 addresses auto assigned no IPv6 address is assigned

##### STEPS TO REPRODUCE
<!--- For bugs, show exactly how to reproduce the problem, using a minimal test-case.
For new features, show how the feature would be used. -->

Create a VPC with auto assigning IPv6 subnets then create an instance.

<!--- Paste example playbooks or commands between quotes below -->
```yaml
  ec2:                                                                                                                                                            
      instance_type: m5.large                                                                       
      image: "ami-0b91bd72"
      region: eu-west-1                                                                           
      count: 1                                                                                                                                                                                                                                          
```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->
An  IPv6 address to be assigned
##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->
An IPv6 address is not assigned
<!--- Paste verbatim command output between quotes below -->
