### ISSUE TITLE
ec2_ami_facts missing query options

### ISSUE THREAD

**Issue by neilhwatson** [ansible/ansible#39756]
##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
ec2_ami_facts

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Apr 27 2018, 10:06:51) [GCC 5.3.0]
```

##### OS / ENVIRONMENT
N/A

##### SUMMARY
When gathering AMI facts there is a filter options, but the CLI equivalent of --query is not documented. Filtering is limited, query is needed to truly narrow down results.

##### STEPS TO REPRODUCE

```yaml
- hosts: localhost

  tasks:
   - name: Get AMI
     ec2_ami_facts:
        owner: amazon
        filters:
           architecture: x86_64
           root-device-type: ebs
     register: ami

   - debug:
      msg: "{{ ami }}"

     # How to match this command below?
     # aws --region ca-central-1 ec2 describe-images --filters "Name=architecture,Values=x86_64 ,Name=owner-alias,Values=amazon,Name=root-device-type,Values=ebs" --query 'reverse(sort_by(Images, &CreationDate))[?Description!=`null`] |[?CreationDate>=`2018-03-01` && starts_with(Description,`Amazon Linux`) && ends_with(Description, `GP2`) && contains(Description, ` Candidate `) == `false`]|[0].[ImageId]' --output text
```

##### EXPECTED RESULTS

N/A
##### ACTUAL RESULTS

N/A

```

```
