### ISSUE TITLE
iam_role module doesn't update 'Description' field of existing roles

### ISSUE THREAD

**Issue by ichekaldin** [ansible/ansible#39771]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

iam_role module

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

#32582 added support for Description parameter to iam_role module. However, this parameter is only set when new role is created. The module does not update Description parameter when the IAM role already exists.

##### STEPS TO REPRODUCE

Create an IAM role, with or without description:
```yaml
- iam_role:
    name: myrole
    description: My role description
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
```
Then try to update the description:
```yaml
- iam_role:
    name: myrole
    description: My new role description
    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
    state: present
```

##### EXPECTED RESULTS

Role description is updated to the new value

##### ACTUAL RESULTS

Role description does not change
