### ISSUE TITLE
Permission denied using mount

### ISSUE THREAD

**Issue by strarsis** [ansible/ansible#39770]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
mount

##### ANSIBLE VERSION

```
ansible 2.4.3.0
config file = [...]/trellis/ansible.cfg
configured module search path = [u'/home/build/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
executable location = /usr/local/bin/ansible
python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
````
ANSIBLE_FORCE_COLOR([...]/trellis/ansible.cfg) = True
ANSIBLE_NOCOWS([...]/trellis/ansible.cfg) = True
ANSIBLE_PIPELINING([...]/trellis/ansible.cfg) = True
ANSIBLE_SSH_ARGS([...]/trellis/ansible.cfg) = -o RemoteForward="127.0.0.1:5454 127.0.0.1:5454" -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=30
ANSIBLE_SSH_RETRIES([...]/trellis/ansible.cfg) = 1
DEFAULT_CALLBACK_PLUGIN_PATH([...]/trellis/ansible.cfg) = [u'/home/build/.ansible/plugins/callback', u'/usr/share/ansible/plugins/callback', u'[...]/trellis/lib/trellis/plugins/callback']
DEFAULT_FILTER_PLUGIN_PATH([...]/trellis/ansible.cfg) = [u'/home/build/.ansible/plugins/filter', u'/usr/share/ansible/plugins/filter', u'[...]/trellis/lib/trellis/plugins/filter']
DEFAULT_FORCE_HANDLERS([...]/trellis/ansible.cfg) = True
DEFAULT_HOST_LIST([...]/trellis/ansible.cfg) = [u'[...]/trellis/hosts']
DEFAULT_ROLES_PATH([...]/trellis/ansible.cfg) = [u'[...]/trellis/vendor/roles']
DEFAULT_STDOUT_CALLBACK([...]/trellis/ansible.cfg) = output
DEFAULT_VARS_PLUGIN_PATH([...]/trellis/ansible.cfg) = [u'/home/build/.ansible/plugins/vars', u'/usr/share/ansible/plugins/vars', u'[...]/trellis/lib/trellis/plugins/vars']
````

##### OS / ENVIRONMENT
WSL (Bash on Windows), this issue is probably not platform-specific.

##### SUMMARY
Mount fails with `permission denied` though manual mounting works using same user and `sudo`.

Manually mounting as user `admin`:
````
$ sudo mount -t cifs //127.0.0.1/share-application /share/application -o port=5454,username=deploy,password=test123
````

##### STEPS TO REPRODUCE
```yaml
 - name: Mount CIFS/SMB share directory from client
   mount:
     name: /share/application
     src: //127.0.0.1/share-application
     opts: "port=5454,username='deploy',password='test123'"
     fstype: cifs
     state: mounted
     boot: no
   remote_user: admin
   become: yes
```

##### EXPECTED RESULTS
Successful mount by ansible.

##### ACTUAL RESULTS
```
{"msg": "Error mounting /share/application: mount error(13): Permission denied\\nRefer to the mount.cifs(8) manual page (e.g. man mount.cifs)\\n", "failed": true, "invocation": {"module_args": {"src": "//127.0.0.1/share-application", "name": "/share/application", "dump": null, "boot": "no", "fstab": null, "passno": null, "fstype": "cifs", "state": "mounted", "path": "/share/application", "opts": "port=5454,username=\'build\',password=\'test123\'"}}}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/mount.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/mount.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
Please try to use `become_user: admin` instead of `remote_user: admin`.

**Comment by strarsis** [comment]
@jtyr:
````
Sorry, user web is not allowed to execute '/bin/sh -c echo BECOME-SUCCESS-
nvcdnhbzxtqljvxiaodacfvepegcpths; /usr/bin/python' as admin on
localhost.localdomain.
````

User `web` is used for deploying but for this particular task (mounting something) it 
must be done as root user. Only user `admin` can use `sudo` to become root.

**Comment by strarsis** [comment]
Any workarounds for this? Currently I have to manually log into the target machine, issue the mount command myself, disconnect and then proceed with applying the playbook.

**Comment by jtyr** [comment]
If user `admin` can use `sudo` them you should be able to use `become_user: root`.

**Comment by strarsis** [comment]
@jtyr: I can manually log in as user `admin` and can also use `sudo` to run `mount` as root and this works.
This is probably an ansible bug because manually invoking `sudo` as user `admin` works but ansible fails.

**Comment by jtyr** [comment]
Please try this playbook:

```yaml
---

- hosts: all
  become: yes
  tasks:
    - mount:
        name: /share/application
        src: //127.0.0.1/share-application
        opts: "port=5454,username='deploy',password='test123'"
        fstype: cifs
        state: mounted
        boot: no
```

Run is like this:

```shell
ansible-playbook -u admin -i hosts -vvvv site.yaml
```

If that doesn't work, then please share your inventory file (`hosts`) and the output of the above command.
