### ISSUE TITLE
supervisorctl module fails when already started?

### ISSUE THREAD

**Issue by devoncrouse** [ansible/ansible#3977]
I would expect an "ok" result from the following, but instead get an error.

``` yaml
# file roles/<role>/tasks/main.yml
- name: "Start Zookeeper"
  supervisorctl: name="zookeeper" state=started
```

Result:
TASK: [Start Zookeeper] *******************************************************
failed: [10.248.203.201] => {"failed": true, "item": ""}
msg: zookeeper: ERROR (already started)
