### ISSUE TITLE
kubernetes module broken in Ansible 2.5: one of the following is required: f, i, l, e, _, r, e, f, e, r, e, n, c, e"

### ISSUE THREAD

**Issue by stephan2012** [ansible/ansible#39786]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

kubernetes

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /root/.vault_pass.txt
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux 7.5

##### SUMMARY

Ansible module `kubernetes` is broken in Ansible 2.5 while the new `k8s_raw` module is not yet fully functional (see #39674 and others).

##### STEPS TO REPRODUCE

```yaml
- name: "Deploy Hazelcast"
  delegate_to: localhost
  run_once: yes
  kubernetes:
    state: present
    api_endpoint: '{{ dynenv_k8s_endpoint }}'
    inline_data:
      apiVersion: extensions/v1beta1
      kind: Deployment
      metadata:
        name: hazelcast
        namespace: 'dynenv-{{ dynenv_name }}'
        annotations:
          description: Hazelcast
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              name: hazelcast
              app_version: '{{ dynenv_hazelcast_version |string }}'
            annotations:
              prometheus.io/port: '1234'
              prometheus.io/scrape: 'true'
          spec:
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                      - key: "name"
                        operator: In
                        values:
                        - hazelcast
                    topologyKey: "kubernetes.io/hostname"
            imagePullSecrets:
            - name: dcr
            initContainers:
            - name: wait-for-etcd
              image: dcr.intern.hse24.de/hse24/rhel7
              command: ['sh', '-c', 'until curl --silent --fail http://etcd:2379/health ; do echo waiting for etcd; sleep 2; done;']
            containers:
            - name: hazelcast
              image: '{{ dynenv_hazelcast_image }}:{{ dynenv_hazelcast_version }}'
              args:
                - -d
                - -p
                - "5701"
                - -e
                - "http://etcd:2379"
                - -j
                - "-javaagent:/usr/java/default/lib/ext/jmx_prometheus_javaagent.jar=1234:/etc/jmx_exporter/default.yml -Xms{{ dynenv_hazelcast_heap_size_mb }}m -Xmx{{ dynenv_hazelcast_heap_size_mb }}m -XX:+AlwaysPreTouch -Dhazelcast.http.healthcheck.enabled=true"
              imagePullPolicy: Always
              env:
              - name: LANG
                value: en_US.UTF-8
              - name: TZ
                value: '{{ dynenv_timezone }}'
              resources:
                requests:
                  memory: "{{ dynenv_hazelcast_heap_size_mb }}Mi"
                  # CPU is in "milli-cpu"
                  cpu: "100m"
              ports:
                - containerPort: 80
            restartPolicy: Always
            readinessProbe:
              failureThreshold: 5
              httpGet:
                path: /hazelcast/health
                port: 5701
                scheme: HTTP
              initialDelaySeconds: 15
              timeoutSeconds: 5
            livenessProbe:
              failureThreshold: 5
              httpGet:
                path: /hazelcast/health
                port: 5701
                scheme: HTTP
              initialDelaySeconds: 15
              timeoutSeconds: 5
```

##### EXPECTED RESULTS

Although deprecated, the `kubernetes` module should continue to work as in Ansible 2.4.

##### ACTUAL RESULTS

Playbook failed:

```
TASK [dynenv-hazelcast : Setup Kubernetes service for Hazelcast] **********************************************************************************************************************************************
fatal: [server -> localhost]: FAILED! => {"changed": false, "msg": "one of the following is required: f, i, l, e, _, r, e, f, e, r, e, n, c, e"}
```
