### ISSUE TITLE
Ansible not substituting hostvars variables in template when using variables with hostvars inside

### ISSUE THREAD

**Issue by mbialozor** [ansible/ansible#39797]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Template/Jinja2

##### ANSIBLE VERSION

```
ansible 2.5.2
  python version = 2.7.14 (default, Mar 14 2018, 13:36:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### CONFIGURATION

```
DEFAULT_BECOME_ASK_PASS(/home/work/ansible-appsrv/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/work/ansible-appsrv/ansible.cfg) = sudo
DEFAULT_HOST_LIST(/home/work/ansible-appsrv/ansible.cfg) = [u'/home/work/ansible-appsrv/hosts']
DEFAULT_JINJA2_EXTENSIONS(/home/work/ansible-appsrv/ansible.cfg) = jinja2.ext.with_
DEFAULT_SQUASH_ACTIONS(/home/work/ansible-appsrv/ansible.cfg) = ['apk', 'apt', 'dnf', 'homebrew', 'pacman', 'pip', 'pkgng', 'yum', 'zypper']
```

##### OS / ENVIRONMENT

```
Fedora release 27 (Twenty Seven)
```

##### SUMMARY

I'm trying to generate load balancer configuration on balancer host (lb) using template and vars configured for two appservers (srv1 and srv2). What I need is to have unique application node naming on each appserver. My idea is to use some index, that can be count automatically (based on group index - default option) or configured via dedicated variable. In second scenario variable with node name is not substituted with correct value. Actually it is treated as a plain text.

Simplified example is shown below.

**INVENTORY:**
```yaml
[appservers]
srv1.example.aero jboss_cluster_index=1
srv2.example.aero jboss_cluster_index=2

[lb]
lb.example.aero
```

**GROUP VARS (group_vars/appservers):**
```yaml
jboss_nodes:
  - name: 'app1_node{{ hostvars[inventory_hostname]["jboss_cluster_index"] | default(groups.appservers.index(inventory_hostname) + 1) }}'
    group: app1-group
  - name: 'app2_node{{ hostvars[inventory_hostname]["jboss_cluster_index"] | default(groups.appservers.index(inventory_hostname) + 1) }}'
    group: app2-group
```

**TEMPLATE:**
```yaml
{% for host in groups['appservers'] %}
{% for node in hostvars[host]['jboss_nodes'] %}
BalancerMember http://{{ host }}:{% if node.port_offset is defined %}{{ 8080 + node.port_offset }}{% else %}{{ 8080 + loop.index * 100 }}{% endif %} route={{ node.name }}
{% endfor %}
{% endfor %}
```

##### STEPS TO REPRODUCE

no

##### EXPECTED RESULTS

```
BalancerMember http://srv1.example.aero:8180 route=app1_node1
BalancerMember http://srv2.example.aero:8180 route=app1_node2
BalancerMember http://srv1.example.aero:8280 route=app2_node1
BalancerMember http://srv2.example.aero:8280 route=app2_node2
```

##### ACTUAL RESULTS

```
BalancerMember http://srv1.example.aero:8180 route=app1_node{{ hostvars[inventory_hostname]["jboss_cluster_index"] | default(groups.appservers.index(inventory_hostname) + 1) }}
BalancerMember http://srv2.example.aero:8180 route=app1_node{{ hostvars[inventory_hostname]["jboss_cluster_index"] | default(groups.appservers.index(inventory_hostname) + 1) }}
BalancerMember http://srv1.example.aero:8280 route=app2_node{{ hostvars[inventory_hostname]["jboss_cluster_index"] | default(groups.appservers.index(inventory_hostname) + 1) }}
BalancerMember http://srv2.example.aero:8280 route=app2_node{{ hostvars[inventory_hostname]["jboss_cluster_index"] | default(groups.appservers.index(inventory_hostname) + 1) }}
```
