### ISSUE TITLE
How to work with with_items

### ISSUE THREAD

**Issue by miiraheart** [ansible/ansible#39831]
##### ISSUE TYPE

 - Bug Report
 
##### COMPONENT NAME

with_items module

##### ANSIBLE VERSION

```
Ansible 2.4.1
```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']

##### OS / ENVIRONMENT

RHEL 7
MariaDB 
##### SUMMARY

Hi everyone,
I’m trying to figure out how to separate my input values for Cloudforms to be used in an Ansible Playbook. I have a textbox where I need to specify multiple usernames to be created for MariaDB. The problem is I tried separating them with ‘,’ and ’ '. but I end up getting this: userone,usertwo or userone usertwo

I don’t know if the issue is in my textbox or I should try another ansible method when trying to create multiple users at the same time.

##### STEPS TO REPRODUCE

```yaml
   mysql_user:
       name: "{{ item }}"
       password: "{{ user_passwd }}"
       host: 'localhost'
       login_user: root
       login_password: "{{ root_passwd }}"
       state: present
     with_items: "{{ mariadb_users }}"
```

##### EXPECTED RESULTS
```
userone
usertwo
```
##### ACTUAL RESULTS

```
userone,usertwo
userone usertwo
```
