### ISSUE TITLE
ios_config fails intermittently

### ISSUE THREAD

**Issue by sk1988** [ansible/ansible#39842]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
The Ansible control host is Centos 7.2

The Cisco IOS is on version 15.2(2)E3.

##### SUMMARY
Pushing changes to Cisco IOS 2960 switch is failing intermittently with below error.  It goes through normally during other times.

fatal: [c205wz01 -> localhost]: FAILED! => {"changed": false, "msg": "unable to retrieve current config", "stderr": "show running-config\r\n                   ^\r\n% Invalid input detected at '^' marker.\r\n\r\nc205wz01>", "stderr_lines": ["show running-config", "                   ^", "% Invalid input detected at '^' marker.", "", "c205wz01>"]}

##### STEPS TO REPRODUCE

```yaml
---
 - name: DEPLOY RUNNING CONFIG FOR DEVICE
   hosts: ios
   gather_facts: False
   connection: local
   vars_files:
   - creds.yml

   tasks:

      - name: configure provider
        set_fact:
         provider:
           username: "{{username}}"
           password: "{{password}}"
           host: "{{inventory_hostname}}"

      - name: GENERATE SNMP CONFIG FILE
        template: src=snmp.j2 dest=CONFIGS/snmp-auto.cfg
        tags: build-snmp

      - name: DEPLOY SNMP FROM AUTO-GENERATED-FILE
        delegate_to: localhost
        ios_config:
           src: "./CONFIGS/snmp-auto.cfg"
           provider: "{{ provider }}"
           host: "{{ inventory_hostname }}"
        tags: deploy-snmp

```

##### EXPECTED RESULTS
The playbook should succeed everytime.

##### ACTUAL RESULTS
ansible-playbook cisco-ios-deploy-config.yml

PLAY [DEPLOY RUNNING CONFIG FOR DEVICE] ******************************************************************************************************************************************************************************************************

TASK [configure provider] ********************************************************************************************************************************************************************************************************************
ok: [c205wz01]

TASK [GENERATE SNMP CONFIG FILE] *************************************************************************************************************************************************************************************************************
ok: [c205wz01]

TASK [DEPLOY SNMP FROM AUTO-GENERATED-FILE] **************************************************************************************************************************************************************************************************
fatal: [c205wz01 -> localhost]: FAILED! => {"changed": false, "msg": "unable to retrieve current config", "stderr": "show running-config\r\n                   ^\r\n% Invalid input detected at '^' marker.\r\n\r\nc205wz01>", "stderr_lines": ["show running-config", "                   ^", "% Invalid input detected at '^' marker.", "", "c205wz01>"]}
        to retry, use: --limit @/etc/ansible/cisco-ios-deploy-config.retry

PLAY RECAP ***********************************************************************************************************************************************************************************************************************************
c205wz01               : ok=2    changed=0    unreachable=0    failed=1

```
**When it failed:**

The full traceback is:
  File "/tmp/ansible_oz5s3b/ansible_modlib.zip/ansible/module_utils/ios.py", line 86, in get_config
    return _DEVICE_CONFIGS[cmd]

fatal: [c205wz01 -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "force": false,
            "host": "c205wz01",
            "intended_config": null,
            "lines": null,
            "match": "line",
            "multiline_delimiter": "@",
            "parents": null,
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": null,
                "host": "c205wz01",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "username": "xxxxx"
            },
            "replace": "line",
            "running_config": null,
            "save": false,
            "save_when": "never",
            "src": \n\n",
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "msg": "unable to retrieve current config",
    "stderr": "show running-config\r\n                   ^\r\n% Invalid input detected at '^' marker.\r\n\r\nc205wz01>",
    "stderr_lines": [
        "show running-config",
        "                   ^",
        "% Invalid input detected at '^' marker.",
        "",
        "c205wz01>"

**When it succeeded:**

ok: [c205wz01 -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "force": false,
            "host": "c205wz01",
            "intended_config": null,
            "lines": null,
            "match": "line",
            "multiline_delimiter": "@",
            "parents": null,
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": null,
                "host": "c205wz01",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "username": "xxxxx"
            },
            "replace": "line",
            "running_config": null,
            "save": false,
            "save_when": "never",
            "src": "\n\n",
            "ssh_keyfile": null,
            "timeout": null,
            "username": null

    ]
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/ios/ios_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_config.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @privateip @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by eakman** [comment]
Just a thought. From the stderr output, it seems like ansible is logging in "User EXEC" mode. I say this because your prompt ends with the `>` symbol (`nc205wz01>`). Typically, you need to be in "Privileged EXEC" (the `#` prompt) to run `show running-config`, which seems to be part of the `ios_config` module's default behavior. Have you tried setting the `authorize` parameter to yes?

Something like:
```
...
      - name: DEPLOY SNMP FROM AUTO-GENERATED-FILE
        delegate_to: localhost
        ios_config:
           provider:
              authorize: yes
           src: "./CONFIGS/snmp-auto.cfg"
           provider: "{{ provider }}"
           host: "{{ inventory_hostname }}"
        tags: deploy-snmp
...
```
See the description of authorize here: http://docs.ansible.com/ansible/latest/modules/ios_config_module.html
