### ISSUE TITLE
iosxr_command module - Commands that prompt are not sending an answer

### ISSUE THREAD

**Issue by AdamSmith-Mtl** [ansible/ansible#39856]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

iosxr_command

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/asmith/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/home/asmith/SMInetinfra/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/asmith/SMInetinfra/ansible.cfg) = -o UserKnownHostsFile=/dev/null
DEFAULT_CALLBACK_WHITELIST(/home/asmith/SMInetinfra/ansible.cfg) = ['syslog_boss', 'profile_tasks']
DEFAULT_HOST_LIST(/home/asmith/SMInetinfra/ansible.cfg) = [u'/home/asmith/SMInetinfra/hosts']
DEFAULT_JINJA2_EXTENSIONS(/home/asmith/SMInetinfra/ansible.cfg) = jinja2.ext.do,jinja2.ext.i18n
DEFAULT_LOG_PATH(/home/asmith/SMInetinfra/ansible.cfg) = /dev/null
DEFAULT_MODULE_PATH(/home/asmith/SMInetinfra/ansible.cfg) = [u'/home/asmith/SMInetinfra/library', u'/usr/share/my_modules/smi-n
DEFAULT_REMOTE_USER(/home/asmith/SMInetinfra/ansible.cfg) = ansible
HOST_KEY_CHECKING(/home/asmith/SMInetinfra/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/asmith/SMInetinfra/ansible.cfg) = False

##### OS / ENVIRONMENT

N/A

##### SUMMARY

When using the iosxr_command module to send commands that prompt, the answer never gets sent.

##### STEPS TO REPRODUCE

Run one of the following playbooks. The command will not be run past the prompt since the answer never gets sent.

**First example playbook:**
```yaml
- name: "Reboot equipment"
  iosxr_command:
    provider:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      timeout: 120
    commands:
      - command: "reload location all"
        prompt: '[confirm]'
        answer: 'y'
```

**Second example playbook:**
```yaml
- name: "Install base image file"
  iosxr_command:
    provider:
      host: "{{ ansible_host }}"
      username: "{{ ansible_user }}"
      password: "{{ ansible_ssh_pass }}"
      timeout: 120
    commands:
      - command: "install add source sftp://ansible@10.199.255.220/usr/local/packages-cisco/6.3.2/packages/ ncs5500-mpls-te-rsvp-2.2.0.0-r632.x86_64.rpm"
        prompt: 'password:'
        answer: 'MyPassword'
  when: base_image_file is defined
  register: result
  changed_when: result is succeeded
```

##### EXPECTED RESULTS

I am expecting the commands to run as if I had entered the prompt answer manually.

##### ACTUAL RESULTS

The command hangs while waiting for user input.

For instance, when running the first playbook from the example playbooks, the reboot never happens because the command is waiting for the answer to get sent. 

When running the second playbook from the example playbooks, we can see in the log that the command times out.

Here is the log on the equipment when running the following command after the second playbook has timed out: 

> show install log [install_id]

```
May 08 05:55:39 Install operation 131 started by ansible:
 install add source sftp://ansible@10.199.255.220/usr/local/packages-cisco/6.3.2/packages/ ncs5500-mpls-te-rsvp-2.2.0.0-r632.x86_64.rpm 
May 08 05:55:41 Action 1: install add action started
May 08 05:55:41 password:******
May 08 05:56:41 Timeout while waiting for password from user
May 08 05:56:42 
May 08 05:56:44 Install operation 131 aborted
May 08 05:56:44 Ending operation 131
```

```
reload location all
Tue May  8 14:04:53.444 UTC

Standby card not present or not Ready for failover. Proceed? [confirm]
```
```
install add source sftp://ansible@10.199.255.220/usr/local/packages-cisco/6.3.2/packages/ ncs5500-mpls-te-rsvp-2.2.0.0-r632.x86_64.rpm 
Tue May  8 14:03:54.018 UTC
May 08 14:03:55 Install operation 133 started by ansible:
 install add source sftp://ansible@10.199.255.220/usr/local/packages-cisco/6.3.2/packages/ ncs5500-mpls-te-rsvp-2.2.0.0-r632.x86_64.rpm 
password:
```

I included what is shown when running the playbook commands manually on the equipment for reference purposes in case the "prompt" line is what is causing the problem.
