### ISSUE TITLE
Ansible hostvars['target_machine']['hostname'] variable creating two directories

### ISSUE THREAD

**Issue by jorbrown90** [ansible/ansible#39876]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

copy module, dest field

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/opt/splunk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

no change
##### OS / ENVIRONMENT

redhat linux 7.x

##### SUMMARY

when using the hostvars['target_machine']['hostname'] variable in the destination field of the copy module, the destination is creating two directories. One with the hostname and the other with the fqdn. The hostname directory has the files requested in the copy module. The fqdn directory is left empty.
##### STEPS TO REPRODUCE

Two systems, copy module any file from system A to system B using the host variable from system A to copy to system B.

```yaml
- hosts: indexers
  connection: ssh
  gather_facts: yes
  become: yes
  tasks:

    - name: debug host vars
      debug:
        var: hostvars['splunk_searchhead']

    - name: adding distkeys to search peers
      copy:
        src: /tmp/localhost/opt/splunk/etc/auth/distServerKeys/trusted.pem
        dest: /opt/splunk/etc/auth/distServerKeys/{{ hostvars['splunk_searchhead']['ansible_hostname'] }}/
        owner: splunk
        group: splunk
        mode: 0660

```

##### EXPECTED RESULTS

For one directory to be created with the splunk_searchhead hostname and the trusted.pem file in the folder.
##### ACTUAL RESULTS

The expected result happened, but there was another folder created in the same directory with the splunk_fqdn.

```
There is too much proprietary information in the output to copy directly into here.
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/copy.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/copy.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
List Information
================

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

I have done a quick test anyway and can't replicate your setup

Here is the test playbook
```
---
- hosts: '2016'
- hosts: localhost
  tasks:
  - copy:
      src: ~/dev/module-tester/adhoc.yml
      dest: ~/dev/module-tester/tmp/{{ hostvars['SERVER2016.domain.local']['ansible_hostname'] }}/
```

Here is the output of the run

```
PLAY [2016] *********************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************
ok: [SERVER2016.domain.local]

PLAY [localhost] ****************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************
ok: [127.0.0.1]

TASK [copy] *********************************************************************************************************************************
changed: [127.0.0.1] => {"changed": true, "checksum": "4c03311412481629a4d1defe5a8893bbe86f386c", "dest": "/Users/jborean/dev/module-tester/tmp/SERVER2016/adhoc.yml", "gid": 20, "group": "staff", "md5sum": "c270a1cd66790294a5817eaacfe4aef3", "mode": "0644", "owner": "jborean", "size": 198, "src": "/Users/jborean/.ansible/tmp/ansible-tmp-1525921818.754865-122573424313410/source", "state": "file", "uid": 501}

PLAY RECAP **********************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0   
SERVER2016.domain.local    : ok=1    changed=0    unreachable=0    failed=0 
```

Here is the tree output of the tmp directory

```
(ansible-py36) jborean:~/dev/module-tester$ tree tmp
tmp
└── SERVER2016
    └── adhoc.yml

1 directory, 1 file
```

When asking the question on one of those sources, please supply some more info, you can obfuscate the hostnames but at least give the output of the run so we can at least see what the module is reporting.
