### ISSUE TITLE
The libselinux is renamed, ansible could not found the new package

### ISSUE THREAD

**Issue by hsmj1412** [ansible/ansible#39897]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
selinux
##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/junlive/lib/python2.7/site-packages/ansible
  executable location = /root/junlive/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
None

##### OS / ENVIRONMENT
Fedora 28
##### SUMMARY
The libselinux is renamed, ansible could not found the new package.
* Thu Aug 10 2017 Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl> - 2.7-2
- Python 2 binary package renamed to python2-libselinux
  See https://fedoraproject.org/wiki/FinalizingFedoraSwitchtoPython3
- Python 3 binary package renamed to python3-libselinux
##### STEPS TO REPRODUCE

```yaml
- name: Collect worker variables
  local_action: lineinfile
  args:
      dest: "example.txt"
      regexp: "^{{ item.key }}="
      line: "{{ item.key }}={{ item.value }}"
  with_items:
      - key: "WORKER_HOSTNAME"
        value: "{{ hostvars[groups['worker'][0]]['ansible_nodename'] }}"
      - key: "WORKER_IFACE"
        value: "{{ hostvars[groups['worker'][0]]['ansible_default_ipv4']['interface'] }}"
      - key: "WORKER_IPV4ADDR"
        value: "{{ hostvars[groups['worker'][0]]['ansible_default_ipv4']['address'] }}"
      - key: "WORKER_IPV6ADDR"
        value: "{{ worker_ipv6_addr }}"
```

##### EXPECTED RESULTS
Pass
##### ACTUAL RESULTS
```
Aborting, target uses selinux but python bindings (libselinux-python) aren't installed!
```
