### ISSUE TITLE
Add support for ssl connections to remaining postgresql modules

### ISSUE THREAD

**Issue by andytom** [ansible/ansible#39906]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
~~postgresql_schema~~ (complete  #44482)
~~postgresql_ext~~ (complete #48538)
~~postgresql_lang~~ (complete  #49221)

##### ANSIBLE VERSION
```
2.5.0
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### SUMMARY
There are 6 modules for managing PostgreSQL, of these 6 modules 3 of them support SSL connections (`postgresql_db`, `postgresql_privs` and `postgresql_user`) while the remaining 3 (`postgresql_ext`, `postgresql_lang` and `postgresql_schema`) do not support SSL connection.

The feature idea is to add SSL support to the remaining 3 modules so that all the `postgres_*` modules are consistent.

##### STEPS TO REPRODUCE

I would suggest using the same `ssl_*` arguments as the existing 3 modules that support SSL. Below is an example for use of the `postgresql_schema` module, however the usage for the other two modules would be similar.

```yaml
- name: Ensure bob owns the acme schema
  postgresql_schema:
    login_host: psql.example.com
    login_user: example_user
    login_password: super-secret-password
    ssl_rootcert: /path/to/ssl/cert
    ssl_mode: verify-full

    name: acme
    owner: bob
```

##### EXPECTED RESULTS

In the above example I would expect Ansible to connect to the PostgreSQL server using ssl to secure the connection and ensure the schema `acme` is owned by `bob`.

##### ACTUAL RESULTS

Currently the above example fails because the `ssl_rootcert` and `ssl_mode` parameters are not supported. 

```
fatal: [psql.example.com]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (postgresql_schema) module: ssl_mode, ssl_rootcert Supported parameters include: database, login_host, login_password, login_unix_socket, login_user, owner, port, schema, state"}
```
