### ISSUE TITLE
Find Module Not Registering Variable

### ISSUE THREAD

**Issue by AjG1tHub** [ansible/ansible#39962]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

Find module
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/anthonyletizia/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/anthonyletizia/python/projects/ansible-role-java/lib/python2.7/site-packages/ansible
  executable location = /Users/anthonyletizia/python/projects/ansible-role-java/bin/ansible
  python version = 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]
```

##### OS / ENVIRONMENT

OSX, No configuration changes
##### SUMMARY

Register not taking any variable from the find module 
##### STEPS TO REPRODUCE

```yaml
  - name: import java folder
      copy:
        src: ../../files/
        dest: /root/tmp
        force: "yes"
        mode: 0644
        backup: "yes"
      environment:
        LANG: C
        LC_ALL: C
        LC_MESSAGES: C

    - name: finds java folder and grabs name
      find:
        path: /root/tmp/
        pattern: 'java.*'
      register: foo

    - debug: msg="{{ foo.stdout }}"
```

##### EXPECTED RESULTS

Variable java_full should print 
##### ACTUAL RESULTS

It doesn't recognize the variable

```
 TASK [finds java folder and grabs name] ****************************************
    ok: [trusty]
    ok: [xenial]

    TASK [debug] *******************************************************************
    fatal: [trusty]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'stdout'\n\nThe error appears to have been in '/Users/anthonyletizia/Documents/GitHub/ansible-role-java/ansible-role-base-java/molecule/default/prepare.yml': line 36, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - debug: msg=\"{{ foo.stdout }}\"\n      ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes.  Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}

```
