### ISSUE TITLE
handle concatenated image ID in azure virtualmachine creation

### ISSUE THREAD

**Issue by christopherkeller** [ansible/ansible#39977]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

azure_rm_virtualmachine
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/Users/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/test/.pyenv/versions/2.7.14/lib/python2.7/site-packages/ansible
  executable location = /Users/test/.pyenv/versions/2.7.14/bin/ansible
  python version = 2.7.14 (default, May  2 2018, 20:56:27) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### SUMMARY

Would like the azure_rm_virtualmachine module to handle concatenated strings for the image type, eg `OpenLogic:CentOS:7.4:latest`. This reflects what is handled by the azure CLI using the `--image` option.

##### STEPS TO REPRODUCE

```yaml
 -set_fact:
    image:  'OpenLogic:CentOS:7.4:latest'

- azure_rm_virtualmachine:
    resource_group: "{{ specified_resourcegroup.name }}"
    location: "{{ region }}"
    name: "{{ project }}-{{ application }}"
    network_interface_names: 
      - "{{ project }}_{{ application }}_external"
      - "{{ project }}_{{ application }}_internal" 
    vm_size: "{{ type }}"
    admin_username: "{{ user }}"
    ssh_password_enabled: False
    ssh_public_keys:
      - path: "/home/{{ user }}/.ssh/authorized_keys"
        key_data: "{{ key_contents }}"
    image: "{{ image }}"

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_virtualmachine.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @haroldwongms @nitzmahone @trstringer @xscript @yuwzho @zikalino
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by yuwzho** [comment]
+label easyfix

Add easyfix label to attract contributor before we have bandwidth working on this issue

**Comment by Fred-sun** [comment]
hi @christopherkeller Before it been fixed, you can use variables method to define the image info, such as : image:  {publisher: 'OpenLogic', offer: 'CentOS', sku: '7.4', version: 'latest' }

**Comment by christopherkeller** [comment]
Thanks @Fred-sun , I'll give that a go. Appreciated.

**Comment by Fred-sun** [comment]
Thanks @christopherkeller ,Do you have any update ?

**Comment by christopherkeller** [comment]
Going to test today in conjunction with some other Azure fixes, I'll have an update in a few hours.

Update:

I tested both the following formats under the Ansible 2.6 developer branch.

`image: {publisher: 'OpenLogic', offer: 'CentOS', sku: '7.4', version: 'latest' }`

and 
```
image:
  publisher: 'OpenLogic'
  offer: 'CentOS'
  sku: '7.4'
  version: 'latest'
```

As expected, no issues with either format. While I think it would be great to support the exact same string as the azure CLI, it's certainly more of a nice to have, rather than a strong want at this point. Happy with this work around.

**Comment by Fred-sun** [comment]
@christopherkeller  Thanks for your confirm.

**Comment by yungezz** [comment]
hello @christopherkeller  is there any update on the issue?

**Comment by christopherkeller** [comment]
I've heard nothing on implementing the concatenated id to match the CLI format.

**Comment by Fred-sun** [comment]
@yungezz Could you help recheck this Issue? Thanks!

**Comment by Fred-sun** [comment]
@yungezz Could you help update the issue status? Thanks!

**Comment by Fred-sun** [comment]
@yungezz Do you have any update about this issue (--image format match the CLI)? Thanks!

**Comment by Fred-sun** [comment]
@yungezz do you have handled this issue? could you help give a fix for this issue? Thanks!

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz  Could you help give a fix for this request? Thanks!

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
@yungezz

**Comment by Fred-sun** [comment]
ping

**Comment by Fred-sun** [comment]
@zikalino When you add this feature, please in this update links, thanks!

**Comment by Fred-sun** [comment]
@zikalino If the Image name is a string, can I add the following code to split it by split?  Thanks!
```e.g.
                if len(self.image.split(':')) > 3:
                    target = self.image.split(':')
                    self.image = {}
                    self.image['publisher'] = target[0]
                    self.image['offer'] = target[1]
                    self.image['sku'] = target[2]
                    self.image['version'] = target[3]
                    marketplace_image = self.get_marketplace_image_version()
                    if self.image['version'] == 'latest':
                        self.image['version'] = marketplace_image.name
                        self.log("Using image version {0}".format(self.image['version']))
                    image_reference = self.compute_models.ImageReference(
                        publisher=self.image['publisher'],
                        offer=self.image['offer'],
                        sku=self.image['sku'],
                        version=self.image['version']
                    )
                else:
                    custom_image = True
                    image_reference = self.get_custom_image_reference(self.image)

**Comment by yuwzho** [comment]
Actually my concern is whether should we support the concatenated image ID, which is not in an Ansible way to get the parameter.

If you only have the concatenated string, I do encourage put the tokenize logic into playbook rather than module code. For example:

```yml
---
- hosts: localhost
  vars:
       id: "a:b:c"
  tasks:
     - set_fact:
          id_list: "{{ id.split(':') }}"
     - debug:
          var: id_list
```
