### ISSUE TITLE
azure_rm_virtualmachine dosn't use virtual_network_resource_group value when validating resource groups on VM create

### ISSUE THREAD

**Issue by devops-raj** [ansible/ansible#39998]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rprasad34/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION

DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 100
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Linux RHEL 7.5
##### SUMMARY

When creating a VM machine using an existing network interface in a different resource group and supplying   "virtual_network_resource_group" and  "virtual_network_name" to azure_rm_virtualmachine. The machine fails to create with the following error:
````
Error fetching network interface mynetworkinterface123 - Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/networkInterfaces/mynetworkinterface123' under resource group 'MyComputeResourceGroup' was not found.
````
The  "def get_network_interface" function in azure_rm_virtualmachine.py  assumes it's under the same resource group.

##### STEPS TO REPRODUCE

```yaml
  tasks:
  - name: Create a network interface using existing security group and disable public IP
    azure_rm_networkinterface:
      name: mynetworkinterface123
      resource_group: myNetWorkResourceGroup
      virtual_network_name: MyVNet
      subnet_name:  MySubnet
      security_group_name: MyNSG
      public_ip: false      

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: MyComputeResourceGroup
      location: somewhere
      virtual_network_resource_group: myNetWorkResourceGroup
      virtual_network_name: MyVNet
      network_interface_names: mynetworkinterface123
      subnet_name:  MySubnet
      name: MyHostName123

```

##### EXPECTED RESULTS

success

##### ACTUAL RESULTS

```
Error fetching network interface mynetworkinterface123 - Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/networkInterfaces/mynetworkinterface123' under resource group 'MyComputeResourceGroup' was not found.
```
The following patch fixes the issue:
````
--- /usr/lib/python2.7/site-packages/ansible/modules/cloud/azure/azure_rm_virtualmachine.py     2018-04-27 03:48:29.000000000 +1000
+++ azure_rm_virtualmachine.py  2018-05-10 11:21:45.469600851 +1000
@@ -1377,8 +1377,12 @@
         return True

     def get_network_interface(self, name):
+        virtual_network_resource_group = self.resource_group
+        if self.virtual_network_resource_group:
+            virtual_network_resource_group = self.virtual_network_resource_group
         try:
-            nic = self.network_client.network_interfaces.get(self.resource_group, name)
+            nic = self.network_client.network_interfaces.get(virtual_network_resource_group, name)
             return nic
         except Exception as exc:
             self.fail("Error fetching network interface {0} - {1}".format(name, str(exc)))

````
