### ISSUE TITLE
ios_command - run command that requires answering a prompt in Network modules

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#40016]
Very similar to `Support commands with multiple interactive operation in Network modules #17950`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_command

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg
  configured module search path = [u'/home/li-axe2960/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/isv/netflow/venvs/alsible/lib/python2.7/site-packages/ansible
  executable location = /opt/isv/netflow/venvs/alsible/bin/ansible
  python version = 2.7.13 (default, Jun  1 2017, 14:19:42) [GCC 4.4.7 20120313 (Red Hat 4.4.7-18)]
```

##### CONFIGURATION

$ ansible-config dump --only-changed
DEFAULT_FORKS(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = 15
DEFAULT_HOST_LIST(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = [u'/opt/isv/netflow/venvs/
DEFAULT_LOCAL_TMP(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = /opt/isv/netflow/temp/ansi
DEFAULT_LOG_PATH(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = /var/log/ansible.log
DEFAULT_ROLES_PATH(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = [u'/opt/isv/netflow/venvs
DEFAULT_VAULT_PASSWORD_FILE(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = /home/li-axe2960
HOST_KEY_CHECKING(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = False
PARAMIKO_RECORD_HOST_KEYS(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = False
RETRY_FILES_ENABLED(/opt/isv/netflow/venvs/alsible/ansible-SNE/ansible.cfg) = False
(END)

##### OS / ENVIRONMENT

Linux 2.6.32-696.23.1.el6.x86_64 #1 SMP Sat Feb 10 11:10:31 EST 2018 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

timeout trying to send command: clear counters Port-channel 1
##### STEPS TO REPRODUCE

See example playbook below:

```yaml
--
- name: Gather Login Information
  set_fact:
    connection:
      authorize: yes
      host: "{{ inventory_hostname }}"
      username: "{{ rtr_lab_user }}"
      password: "{{ rtr_lab_pass }}"
      timeout: 20
  tags: connection

- name: run command that requires answering a prompt
  ios_command:
    provider: "{{ connection }}"
    commands:
      - command: 'clear counters Port-channel 1'
        prompt: 'Clear "show interface" counters on this interface [confirm]'
        answer: y
  tags: clear

```

##### EXPECTED RESULTS

Expected the interface counters to clear. Tried on Gig0/1, Fa0, never worked.

##### ACTUAL RESULTS

```

fatal: [rtr1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "auth_pass": null,
            "authorize": null,
            "commands": [
                {
                    "answer": "y",
                    "command": "clear counters Port-channel 1",
                    "prompt": "Clear \"show interface\" counters on this interface [confirm]"
                }
            ],
            "host": null,
            "interval": 1,
            "match": "all",
            "password": null,
            "port": null,
            "provider": {
                "auth_pass": null,
                "authorize": true,
                "host": "rtr1l",
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "port": null,
                "ssh_keyfile": null,
                "timeout": 20,
                "username": "user"
            },
            "retries": 10,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null,
            "wait_for": null
        }
    },
    "msg": "timeout trying to send command: clear counters Port-channel 1",
    "rc": 1
}

PLAY RECAP *******************************************************************************************
rtr1           : ok=1    changed=0    unreachable=0    failed=1


```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/ios/ios_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/ios/ios_command.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @privateip @rcarrillocruz
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ghost** [comment]
The example recommends:
```
    commands:
      - command: 'clear counters GigabitEthernet0/2'
        prompt: 'Clear "show interface" counters on this interface [confirm]' <-- see below:
        answer: c <--- this should be 'y'. The 'c' doesn't execute the command on the c2951 
```
I changed the prompt to:
 `prompt: '[confirm]'`
and the command executed properly. Not sure this is a fix, or what the final fix should be, but it worked with Cisco IOS 15-4.
