### ISSUE TITLE
docker_image: build fails if tag contains a slash

### ISSUE THREAD

**Issue by niko** [ansible/ansible#40015]
##### ISSUE TYPE
When trying to build a docker image where the tag contains a slash the build fails with the message `APIError: 500 Server Error: Internal Server Error {"message":"invalid reference format"}`. When removing the slash it works.

This is the playbook:

```yaml
---
- name: "build deb"
  tags: [build]
  gather_facts: no
  remote_user: ansible
  hosts: docker-build
  tasks:
    - name: "deb | build image"
      docker_image:
        path: "/home/ansible/build/deb"
        name: "deb"
        tag: 'foo/bar'
```

##### COMPONENT NAME
docker_image

##### ANSIBLE VERSION
```sh
$ ansible --version
ansible 2.5.2
  config file = /home/niko/Laut/ansible/ansible.cfg
  configured module search path = ['/home/niko/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.4 (default, Apr  6 2018, 05:23:32) [GCC 6.4.0]
```

##### CONFIGURATION
```sh
[DEPRECATION WARNING]: ANSIBLE_HOSTS option, The variable is misleading as it can be a list of hosts and/or paths to inventory
 sources , use ANSIBLE_INVENTORY instead. This feature will be removed in version 2.8. Deprecation warnings can be disabled by
 setting deprecation_warnings=False in ansible.cfg.
DEFAULT_CALLBACK_PLUGIN_PATH(/home/niko/Laut/ansible/ansible.cfg) = ['/usr/lib/python2.7/site-packages/ansible/plugins/callbac>
DEFAULT_HOST_LIST(env: ANSIBLE_HOSTS) = ['/home/niko/.ansible_hosts']
DEFAULT_STDOUT_CALLBACK(/home/niko/Laut/ansible/ansible.cfg) = minimal
```

##### OS / ENVIRONMENT
Host:
```sh
$ uname -a
Alpine Linux 4.14.39-0-vanilla #1-Alpine SMP Mon May 7 12:26:32 UTC 2018 x86_64 GNU/Linux
```
Remote:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```

##### SUMMARY
Building a docker image with docker_image module fails if tag contains a slash.

##### STEPS TO REPRODUCE
Running this playbook fails:
```yaml
---
- name: "build deb"
  tags: [build]
  gather_facts: no
  remote_user: ansible
  hosts: docker-build
  tasks:
    - name: "deb | build image"
      docker_image:
        path: "/home/ansible/build/deb"
        name: "deb"
        tag: 'foo/bar'
```

Running this playbook works:
```yaml
---
- name: "build deb"
  tags: [build]
  gather_facts: no
  remote_user: ansible
  hosts: docker-build
  tasks:
    - name: "deb | build image"
      docker_image:
        path: "/home/ansible/build/deb"
        name: "deb"
        tag: 'foo-bar'
```

##### EXPECTED RESULTS
I expect to be able to build images with tags with slashes.

##### ACTUAL RESULTS
```
infra | FAILED! => {
    "changed": false,
    "module_stderr": "Shared connection to lautfm-infrastruktur closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_TRC7R4/ansible_module_docker_image.py\", line 607, in <module>\r\n    main()\r\n  File \"/tmp/ansible_TRC7R4/ansible_module_docker_image.py\", line 602, in main\r\n    ImageManager(client, results)\r\n  File \"/tmp/ansible_TRC7R4/ansible_module_docker_image.py\", line 295, in __init__\r\n    self.present()\r\n  File \"/tmp/ansible_TRC7R4/ansible_module_docker_image.py\", line 323, in present\r\n    self.results['image'] = self.build_image()\r\n  File \"/tmp/ansible_TRC7R4/ansible_module_docker_image.py\", line 525, in build_image\r\n    for line in self.client.build(**params):\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/client.py\", line 268, in _stream_helper\r\n    yield self._result(response, json=decode)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/client.py\", line 178, in _result\r\n    self._raise_for_status(response)\r\n  File \"/usr/local/lib/python2.7/dist-packages/docker/client.py\", line 174, in _raise_for_status\r\n    raise errors.APIError(e, response, explanation=explanation)\r\ndocker.errors.APIError: 500 Server Error: Internal Server Error (\"{\"message\":\"invalid reference format\"}\")\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}

```
