### ISSUE TITLE
Add an 'apt_options' Parameter to apt_module

### ISSUE THREAD

**Issue by shawing** [ansible/ansible#40023]
##### ISSUE TYPE
 - Feature Idea

// Add the parameter to be able to specify apt options to playbooks.  i.e. -o Dir::Etc::SourceList=/etc/apt/security.sources.list

##### COMPONENT NAME

apt_module

##### ANSIBLE VERSION

```
(venv-ansible) kens-mbp:ansible ken$ ansible --version
ansible 2.5.1
  config file = None
  configured module search path = [u'/Users/ken/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ken/python-virtualenvs/venv-ansible/lib/python2.7/site-packages/ansible
  executable location = /Users/ken/python-virtualenvs/venv-ansible/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
(venv-ansible) kens-mbp:ansible ken$
```

##### CONFIGURATION

(venv-ansible) kens-mbp:ansible ken$ ansible-config dump --only-changed
(venv-ansible) kens-mbp:ansible ken$

##### OS / ENVIRONMENT

Running from:  OSX 10.13.4
Managing: Ubuntu 16.04 and Ubuntu 14.04

##### SUMMARY

I would like to write a playbook that applies only security-level patches to Ubuntu servers.  To do this, I need to pass an apt option "-o" that specifies the path to the apt sources list file.  I can duplicate this functionality with command_module but would like to see it in apt_module.  This could be done very close to how the existing dpkg_options is now.

##### STEPS TO REPRODUCE

apt_options: "Dir::Etc::SourceList=/etc/apt/security.sources.list"

```yaml
- name: Ubuntu - Install the security updates
  apt:
    force_apt_get: yes
    state: latest
    upgrade: yes
    apt_options: "Dir::Etc::SourceList=/etc/apt/security.sources.list"
  register: apt_output
```

##### ACTUAL RESULTS

```

```
