### ISSUE TITLE
debug/var doesn't see item in a loop

### ISSUE THREAD

**Issue by x-yuri** [ansible/ansible#40046]
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /path/to/prj/ansible.cfg
  configured module search path = [u'/home/yuri/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/path/to/prj/ansible.cfg) = True
DEFAULT_LOG_PATH(/path/to/prj/ansible.cfg) = /path/to/prj/ansible.log
RETRY_FILES_ENABLED(/path/to/prj/ansible.cfg) = False
```

##### OS / ENVIRONMENT

N/A

##### SUMMARY

`debug: var: item` doesn't print value if in a loop

##### STEPS TO REPRODUCE

```yaml
- hosts: all
  vars:
    arr: [1]
  tasks:
    - name: ...
      debug:
        var: item
      with_items: "{{ arr }}"

    - name: ...
      debug:
        var: item2
      with_items: "{{ arr }}"
      loop_control:
        loop_var: item2
```

```yaml

```

##### EXPECTED RESULTS

```
TASK [...] ************************************************************************************
task path: /path/to/prj/2.yml:3
ok: [host] => (item=1) => {
    "item": 1
}

TASK [...] ************************************************************************************
task path: /path/to/prj/2.yml:8
ok: [host] => (item=1) => {
    "item2": 1
}
```

##### ACTUAL RESULTS

```
TASK [...] ************************************************************************************
task path: /path/to/prj/2.yml:3
ok: [host] => (item=None) => {}

TASK [...] ************************************************************************************
task path: /path/to/prj/2.yml:8
ok: [host] => (item=1) => {
    "item2": 1
}
```

[Here's][omit-keys-1] [the][omit-keys-2] [reason][omit-keys-3].

[omit-keys-1]: https://github.com/ansible/ansible/blob/v2.5.0/lib/ansible/plugins/callback/default.py#L193
[omit-keys-2]: https://github.com/ansible/ansible/blob/v2.5.0/lib/ansible/plugins/callback/__init__.py#L240
[omit-keys-3]: https://github.com/ansible/ansible/blob/v2.5.0/lib/ansible/plugins/callback/__init__.py#L80

It's probably questionable if it's a bug, but certainly got me confused.
