### ISSUE TITLE
os_recordset not working properly on Openstack Pike

### ISSUE THREAD

**Issue by mfms** [ansible/ansible#40072]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

os.recordset
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/Users/marcosilva/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/Users/marcosilva/Documents/ansible']
##### OS / ENVIRONMENT

macOS Sierra V 10.12.6, Ubuntu Xenial
##### SUMMARY

Attempting to add a record to a zone results in failure in Openstack Pike.
##### STEPS TO REPRODUCE

```yaml
  - name: Create DNS entry for Broker
    os_recordset:
        state: present
        zone: project.example.
        name: broker
        recordset_type: primary
        records: ['{{ broker.openstack.private_v4 }}']
        description: Broker recordset
        ttl: 3600
    register: broker_dns
```

##### EXPECTED RESULTS

For the record to actually be created
##### ACTUAL RESULTS

"Error fetching recordsets list. (400) Client Error for url: http://<ip_hidden>:9001/v2/zones/project.example./recordsets"

```

```
