### ISSUE TITLE
Allow with_items to trigger notifies

### ISSUE THREAD

**Issue by linsomniac** [ansible/ansible#40086]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
handlers

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = <path_to>/ansible.cfg
  configured module search path = [u'/home/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

```
CACHE_PLUGIN(<path_to>/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(<path_to>/ansible.cfg) = .ansible-fact-cache
CACHE_PLUGIN_TIMEOUT(<path_to>/ansible.cfg) = 864000
DEFAULT_GATHERING(<path_to>/ansible.cfg) = smart
DEFAULT_HOST_LIST(<path_to>/ansible.cfg) = [u'<path_to>/hosts']
DEFAULT_STDOUT_CALLBACK(<path_to>/ansible.cfg) = actionable
DEFAULT_VAULT_PASSWORD_FILE(<path_to>/ansible.cfg) = <path_to>/bin/vault_password
RETRY_FILES_ENABLED(<path_to>/ansible.cfg) = False
```
##### OS / ENVIRONMENT

N/A

##### SUMMARY
"notify:" is per task, as explained in #15421.  In many if not most of my roles I try to consolidate my template: delivery into a single task that uses with_items, but I often have to split them into two or three or four tasks with different sets of notifies.  This leads to ~50 lines of boilerplate that is copy/pasted that could be ~15.

##### STEPS TO REPRODUCE

```yaml

- name: Example Notify
  template:
    src: "{{ item.src | default(item.dest | basename + '.j2') }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default('a=rX,u+w') }}"
  notify:
    "{{ item.notify | default(omit) }}"
  with_items:
    - dest: /tmp/f1
      notify:
        - Reload systemd
        - Restart rsyslog
    - dest: /tmp/f2
      notify:
        - Reload systemd
    - dest: /tmp/f3
      notify:
        - Restart rsyslog
    - dest: /tmp/f4
  tags:
    - rsyslog

```

##### EXPECTED RESULTS

It would be ideal if there were a way to trigger a notify on a specific changed item.

##### ACTUAL RESULTS

It seems to collect all the notifies that get injected from the items, and then if any item is changed all the mentioned notifies are triggered.  I'm guessing that in the code there is something that collects the notifies in this with_items loop, so perhaps it would be possible to only collect them when the specific item results in changed?  I say that not because I'm familiar with the code, but just based on the behavior.

If the user wants just a static set of notifies for the with_items task, they could list them right there, or list them in another var for notifies on the task.  It seems like the only case where a user would use the items in notify is where they want different notifies for different changed files.

It seems like what I'm proposing is the least surprising behavior, but I'm sure someone relies on this behavior so thought will have to be given to how it is implemented.

```

```
