### ISSUE TITLE
vmware_guest_file_operation reports that file copied although incomplete file transferred previously

### ISSUE THREAD

**Issue by wojciechkopciewicz** [ansible/ansible#40112]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest_file_operation

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/wojtek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### SUMMARY

If a copy operation is ceased, the next run of the playbook reports "ok" although incomplete file was transferred previously. As a result transfer is never finished.

##### STEPS TO REPRODUCE

Start a transfer of a big file to vm and cease it in the middle. Retry the playbook. Verify the size/contents of the file in destination.

```yaml
    - name: copy file to vm
      vmware_guest_file_operation:
        copy:
          src: /tmp/sample
          dest: /tmp/sample
        hostname: 192.168.0.51  # this is esxi ip
        password: xxxxxxx
        username: root
        vm_username: root
        vm_id: test_vm
        vm_password: xxxxxxx
        validate_certs: false
```

##### EXPECTED RESULTS

The first run should not create incomplete file. File should be fully transferred during second run.
##### ACTUAL RESULTS

First run creates file with proper name but wrong size/content in the destination. Second run reports that task is already done.

```

```
