### ISSUE TITLE
aws_ec2_net unable to remove default VPC 

### ISSUE THREAD

**Issue by lukegriffith** [ansible/ansible#40153]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aws_ec2_net

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /opt/bootstrap/src/aws-infrastructure/Config/ansible.cfg
  configured module search path = [u'/opt/bootstrap/src/aws-infrastructure/Config/library']
  ansible python module location = /opt/bootstrap/ans1/lib/python2.7/site-packages/ansible
  executable location = /opt/bootstrap/ans1/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/opt/bootstrap/src/aws-infrastructure/Config/ansible.cfg) = [u'/opt/bootstrap/src/aws-infrastructure/Config/accounts.yml']
DEFAULT_LOG_PATH(/opt/bootstrap/src/aws-infrastructure/Config/ansible.cfg) = /home/administrator/ansible_logs
DEFAULT_MODULE_PATH(/opt/bootstrap/src/aws-infrastructure/Config/ansible.cfg) = [u'/opt/bootstrap/src/aws-infrastructure/Config/library']
DEFAULT_ROLES_PATH(/opt/bootstrap/src/aws-infrastructure/Config/ansible.cfg) = [u'/opt/bootstrap/src/aws-infrastructure/Config/roles']

```

##### OS / ENVIRONMENT

Linux localhost.localdomain 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### SUMMARY

Resource is unable to remove default VPC

##### STEPS TO REPRODUCE

Resource returns OK, is unable to remove the default instance, this is functionality ec2_vpc had, migrating over to the new version has caused these problems. 

```yaml
- name: "remove default VPC - {{ region }}"
  ec2_vpc_net:
    region: "{{region}}"
    state: absent
    cidr_block: "{{vpc_cidr_block}}"
    name: ""
    tenancy: "default"
```

##### EXPECTED RESULTS

Have the default VPC removed from my region

##### ACTUAL RESULTS

default VPC remains, and ansible reports OK 

```

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by lukegriffith** [comment]
Further detail on this, appears to be due to the following line  https://github.com/ansible/ansible/blob/44eaa2c007b53459eb675089e259fc616cb91c43/lib/ansible/modules/cloud/amazon/ec2_vpc_net.py#L180


As 'name' is a required parameter its expecting a VPC to have a name tag, but the default VPC does not have this tag assigned.

**Comment by lukegriffith** [comment]
Work around on this, I tag the default VPC before removal.

**Comment by manchuck** [comment]
:+1:

**Comment by manchuck** [comment]
@lukemgriffith  How are you tagging the default instance? I cannot set the tag because the default VPC does not have a name

**Comment by lukegriffith** [comment]
Took a fair bit of hacking, but managed it with json queries. 

```yaml
# Query all VPC's in the region
- name: "query VPC - {{ region }}"
  ec2_vpc_net_facts:
    region: "{{region}}"
  register: vpc

# Tag the default VPC
- name: "Tag default VPC - {{ region }}"
  ec2_tag:
    region: "{{region}}"
    resource: "{{vpc_id}}"
    state: present
    tags:
      Name: default-vpc
    validate_certs: "{{ validate_ssl }}"

  # Use a json query, to identify the default VPC and extract the id.
  # Use the looping contruct to run it on ec2_tag.
  with_items: "{{ vpc | json_query('vpcs[?is_default].id')}}"
  loop_control:
    loop_var: vpc_id

# Remove the default VPC, now we have a tag set we just need to provide the cidr_block
- name: "remove default VPC - {{ region }}"
  ec2_vpc_net:
    region: "{{region}}"
    state: absent
    cidr_block: "{{vpc_cidr_block}}"
    name: "default-vpc"
    tenancy: "default"
    validate_certs: "{{ validate_ssl }}"

  # Use a json query once again to identify the default VPC this time extracting the cidr_block.
  # Use the looping construct on ec2_vpc_net.
  with_items: "{{ vpc | json_query('vpcs[?is_default].cidr_block | [0]')}}"
  loop_control:
    loop_var: vpc_cidr_block

```
