### ISSUE TITLE
win_domain_membership: The RPC server is unavailable.

### ISSUE THREAD

**Issue by dagwieers** [ansible/ansible#40159]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_domain_membership

##### ANSIBLE VERSION
v2.6 and earlier

##### OS / ENVIRONMENT
- RHEL7 as Ansible host.
- Windows 2012R2 as target nodes.

##### SUMMARY
This is likely not a problem with the module, but may be something we could avoid in the module ?

So we build a complete virtualized AD environment with MSSQL and SCVMM using templates, all works well. This task about 30 minutes to complete.

Then we build HyperV servers using MDT to connect to SCVMM. Often joining this HyperV server to the domain fails with error:
```
failed to join domain: Computer 'c220m4-3' failed to join domain 'pod51vmm.aci.lab' from its current workgroup 'WORKGROUP' with following error message: The RPC server is unavailable.
```

The Windows event log shows this error:
```
The machine c220m4-3 attempted to join the domain pod51vmm.aci.lab but failed. The error code was 1722.
```

Since the AD environment is up and running, and has no issues joining VM's, the problem does not seem to relate to the AD environment itself, but is caused internally in this newly-built HyperV. And it must be a timing issue, as it sometimes works, sometimes fails. The task we use is:
```yaml
- name: Join system to the domain
  win_domain_membership:
    dns_domain_name: '{{ local_domain }}'
    hostname: '{{ windows_shortname }}'
    domain_admin_user: '{{ windows_domain }}\{{ windows_admin_user }}'
    domain_admin_password: '{{ windows_admin_password }}'
    log_path: C:\Windows\Temp\ad_join_log.txt
    state: domain
  register: domain_state
```

I think we can avoid this from the module, but first I need to figure out why it sometimes works, but sometimes fails.
