### ISSUE TITLE
MODULE FAILURE: basic.py tmpdir function

### ISSUE THREAD

**Issue by mtnbikenc** [ansible/ansible#40168]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible/module_utils/basic.py

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel f04c876ecd) last updated 2018/05/15 11:58:44 (GMT -400)
  config file = /home/rteague/git/clusters/aws-c1/ansible.cfg
  configured module search path = [u'/home/rteague/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/rteague/git/clusters/aws-c1/ansible/lib/ansible
  executable location = /home/rteague/git/clusters/aws-c1/ansible/bin/ansible
  python version = 2.7.15 (default, May  9 2018, 11:18:37) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### CONFIGURATION

None
##### OS / ENVIRONMENT

N/A

##### SUMMARY

Since commit 44ab948e5d3c33b1f24c368da9aaee776d98f512, the tmpdir function has been failing. 
##### STEPS TO REPRODUCE

Working on creating a limited reproducer.

```yaml

```

##### ACTUAL RESULTS

```
  File \"/tmp/ansible_zbTOHZ/ansible_modlib.zip/ansible/module_utils/urls.py\", line 1029, in fetch_url  
  File \"/tmp/ansible_zbTOHZ/ansible_modlib.zip/ansible/module_utils/basic.py\", line 942, in tmpdir
  File \"/usr/lib64/python2.7/tempfile.py\", line 329, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 2] No such file or directory: '/root/.ansible/tmp/ansible-moduletmp-1526388195.31-7kles8'
", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}

```
/cc @maxamillion

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/module_utils/basic.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/basic.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jborean93** [comment]
Thanks @mtnbikenc for the issue, I think I know what is happening, the default tmp dir is to use `~/.ansible/tmp` but the folder `~/.ansible/tmp` does not exist on your remote host so it failed to create the sub temporary folder. I'll look into adding a fix for it.

**Comment by jborean93** [comment]
A simple reproducer

```
---
- hosts: fedora
  gather_facts: no
  vars:
    ansible_ssh_pipelining: yes
  tasks:
  - file:
      path: ~/.fake-ansible-tmp
      state: absent

  - file:
      path: ~/test.txt
      state: absent

  - get_url:
      url: https://google.com
      dest: ~/test.txt
    vars:
      ansible_remote_tmp: ~/.fake-ansible-tmp
```

This will make sure the tempdir does not exists and try out get_url (which uses basic.py tmpdir) with that tmpdir specified.
