### ISSUE TITLE
VMware module for vmware_host_config_manager failing for certain parameters. 

### ISSUE THREAD

**Issue by sat1121** [ansible/ansible#40180]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

vmware_host_config_manager

##### ANSIBLE VERSION

```
ansible 2.5.2
```

##### SUMMARY

Using vmware_host_config_manager for certain parameters failing. 

##### STEPS TO REPRODUCE

```yaml
---
- hosts: testgroup
  gather_facts: no
  
  tasks:
  - name: Applying ESXi setting
    delegate_to: localhost
    vmware_host_config_manager:
      esxi_hostname: hostname
      hostname: vcentername
      username: '{{vcenter_username}}'
      password: '{{vcenter_password}}'
      validate_certs: no
      options:
        "UserVars.ESXiShellInteractiveTimeOut": 50
        "UserVars.ESXiShellTimeOut": 50
```

##### EXPECTED RESULTS

When i use any other parameters instead of the ones above it works just fine, The playbook declare the setting and gets back with the result if the parameter is changed or not, only with the above and also with the set of any other user / time out settings the output verberose returns with the error message "Invalid parameter"

##### ACTUAL RESULTS

```
The full traceback is:
  File "/var/folders/7g/<>/T/ansible_WyhOVN/ansible_module_vmware_host_config_manager.py", line 127, in set_host_configuration_facts
    option_manager.UpdateOptions(changedValue=change_option_list)
  File "/usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [s<> -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "cluster_name": null, 
            "esxi_hostname": "<>", 
            "hostname": "<>", 
            "options": {
                "UserVars.ESXiShellInteractiveTimeOut": 0, 
                "UserVars.ESXiShellTimeOut": 0
            }, 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "username": "<>", 
            "validate_certs": false
        }
    }, 
    "msg": "Failed to update option/s as one or more OptionValue contains an invalid value: A specified parameter was not correct: "
}
```
As I said, this is not happening for all the parameters, so far from what i tested, it is only happening to the parameters that are specific to Users/timeout values, is there an exception of set of host configs that are not supported? I also tried the "vmware_host_config_facts" Module to verify if the name of the parameter is same when we "get" the value from host, the names are same.
