### ISSUE TITLE
Task does not fail after the configuration error, using the EAPI connection in eos_config

### ISSUE THREAD

**Issue by indirakas** [ansible/ansible#40187]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 eos_config

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/etc/ansible/virtualenv']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jul 13 2017, 21:39:32) [GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]
```

##### CONFIGURATION

ESC[0;33mANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -s -p 830 netconfESC[0m
ESC[0;33mDEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']ESC[0m
ESC[0;33mDEFAULT_LOCAL_TMP(/etc/ansible/ansible.cfg) = /local/rootik/.ansible/tmp/ansible-local-4659WZR81GESC[0m
ESC[0;33mDEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.logESC[0m
ESC[0;33mDEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/virtualenv']ESC[0m
ESC[0;33mPERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 600ESC[0m

##### OS / ENVIRONMENT

Software image version: 4.20.3F

##### SUMMARY

The playbook task doesn't fail, when using "eos_config" with EAPI as a transport, after the configuration, which brings up the following error:
% Subnet aa00::/64 overlaps with existing subnet aa00::10:8:20:6/127 of interface Ethernetx/x/x.y

##### STEPS TO REPRODUCE

```yaml
Task:
    - name: configure an interface
      eos_config:
       provider: '{{ eapi }}'
       lines:
        - description "dwcarder playground interface 3"
        - ipv6 address aa00::d:a:1:e/64
        - shutdown
       parents: "interface Ethernet4/24/1"
       replace: block

The IP address above should bring this error on Arista router:
(config)#int e4/24/1
(config-if-Et4/24/1)#no switchport 
(config-if-Et4/24/1)#ipv6 address aa00::d:a:1:e/64
% Subnet aa00::/64 overlaps with existing subnet aa00::10:8:20:6/127 of interface Ethernet4/2/2.100

```

##### EXPECTED RESULTS

TASK [...] ******************************************************************************************************************************
fatal: [x.x.x.x]: FAILED!

##### ACTUAL RESULTS

TASK [...] ***************************************************************************************************************************
changed: 

```

```
