### ISSUE TITLE
k8s_raw and openshift_raw support a nonexistent username/password auth option

### ISSUE THREAD

**Issue by marwatk** [ansible/ansible#40195]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

k8s_raw
openshift_raw

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 868c2630dd) last updated 2018/05/10 13:48:52 (GMT +000)
  config file = /home/mwatkins/git/caasd-containerland-config/deployment/ansible.cfg
  configured module search path = [u'/home/mwatkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mwatkins/git/ansible/lib/ansible
  executable location = /home/mwatkins/git/ansible/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/home/.../deployment/ansible.cfg) = [u'/home/.../deployment/inventory']

##### OS / ENVIRONMENT

CentOS 7.4.1708

##### SUMMARY

openshift_raw and k8s_raw docs show they support a username/password authentication option but the openshift python library [doesn't seem to support those options](https://github.com/openshift/openshift-restclient-python/blob/2a798cd7f2a9d6d36c8d4a50f21f6f780ef860dd/openshift/helper/base.py#L99). Additionally the modules both reference `K8S_AUTH_USERNAME` and `K8S_AUTH_PASSWORD` environment variables, but neither seems to work and I can't find a reference for those outside ansible.

If this is just a case of cruft that doesn't work anymore I'm happy to craft a PR to fix the docs and remove the references, if not, let me know what I'm doing wrong. Thanks!

##### STEPS TO REPRODUCE

```yaml
  - name: Create project
    openshift_raw:
      host: "https://{{ ansible_host }}:8443"
      state: present
      username: "{{ openshift_username }}"
      password: "{{ openshift_password }}"
      verify_ssl: no
      api_version: v1
      kind: Project
      name: test-project
      description: Test Project
      display_name: Test Project
```

##### EXPECTED RESULTS
Creates a project

##### ACTUAL RESULTS

```
The full traceback is:
  File "/tmp/ansible_2PQFwB/ansible_modlib.zip/ansible/module_utils/k8s/raw.py", line 207, in _create_project
    description=self.params.get('description'))
  File "/usr/lib/python2.7/site-packages/openshift/helper/openshift.py", line 68, in create_project
    raise OpenShiftException(msg, status=exc.status)

fatal: [openshift.pd.labs.mitre.org]: FAILED! => {
    "changed": false,
    "error": 403,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "description": "Test Project",
            "display_name": "Test Project",
            "host": "https://...:8443",
            "key_file": null,
            "kubeconfig": null,
            "name": "test-project",
            "namespace": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ssl_ca_cert": null,
            "username": "mwatkins",
            "verify_ssl": false
        }
    },
    "msg": "Failed to retrieve requested object"
}
```
