### ISSUE TITLE
nic_gce_struct is not processed in gce_instance_template.py

### ISSUE THREAD

**Issue by grarvind** [ansible/ansible#40219]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

gce_instance_template

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

No changes
##### OS / ENVIRONMENT

Ubuntu 16.04.4 LTS

##### SUMMARY

In the python file gce_instance_template.py the nic_gce_struct for creating instance templates on GCP is not handled. As a result, the template is always created with a single NIC configuration.
##### STEPS TO REPRODUCE

Create any template with more than 1NIC using the nic_gce_struct parameter.

```yaml
---
- name: "Create an instance template with 3 NICs"
  gce_instance_template:
    service_account_email: "{{ client_email }}"
    credentials_file: "{{ auth_file }}"
    project_id: "{{ project_id }}"
    description: "{{ template_description }}"
    disk_auto_delete: "yes"
    image: "{{ image_name }}"
    image_family: "{{ image_family }}"
    name: "{{ template_name }}"
    service_account_permissions:
      - compute-rw
      - datastore
      - storage-full
    size: "{{ instance_type }}"
    state: present
    nic_gce_struct:
      - network: "{{ compute_base_url }}projects/{{ project_id }}/global/networks/{{ network1 }}"
        subnetwork: "{{ compute_base_url }}projects/{{ project_id }}/regions/{{ gcp_region }}/subnetworks/{{ subnet1 }}"
        accessConfig:
          - name: "External NAT"
            type: "ONE_TO_ONE_NAT"
      - network: "{{ compute_base_url }}projects/{{ project_id }}/global/networks/{{ network2 }}"
        subnetwork: "{{ compute_base_url }}projects/{{ project_id }}/regions/{{ gcp_region }}/subnetworks/{{ subnet2 }}"
      - network: "{{ compute_base_url }}projects/{{ project_id }}/global/networks/{{ network3 }}"
        subnetwork: "{{ compute_base_url }}projects/{{ project_id }}/regions/{{ gcp_region }}/subnetworks/{{ subnet3 }}"
    tags:
      - "{{ network_tags }}"
    metadata: "{'ssh-keys': '{{ public_key }}'}"
  register: var_template
```

##### EXPECTED RESULTS

An instance template with 3 NIC configuration is supposed to be created.
##### ACTUAL RESULTS

The template that is being created using the above configuration does not process the values under nic_gce_struct and populates the network and subnetwork with the 'default' values. The result is that  a template with a single NIC configuration is always created.

```

```
