### ISSUE TITLE
nxos_vlan mode issue on N5k

### ISSUE THREAD

**Issue by hemskgren** [ansible/ansible#40236]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nxos_vlan
##### ANSIBLE VERSION

```
2.5.2
```

##### CONFIGURATION

default from pip
##### OS / ENVIRONMENT

centos6 and nxos 7.3 on nexus 5500.
##### SUMMARY

nxos_vlan mode fabricpath issue on n5k with nxapi
I can see in the module about network_os_platform for option mode. 
##### STEPS TO REPRODUCE

```yaml
- name: add vlan in pod
  hosts: ix1-test
  connection: local
  any_errors_fatal: true
  gather_facts: false
  vars:
    ansible_user: "{{ tower_user_name }}"
    ansible_password: "{{ password }}"
    nxapi:
      username: "{{ tower_user_name }}"
      password: "{{ password }}"
      transport: nxapi
      use_ssl: yes
      validate_certs: no
      port: 10443
      timeout: 15
      host: "{{ inventory_hostname }}"
  tasks:
    - name: create vlan in switches
      nxos_vlan:
        vlan_id: "{{ vlan_id }}"
        state: present
        name: "{{ vlan_name }}"
        admin_state: up
        mode: fabricpath
        provider: "{{ nxapi }}"
```

##### EXPECTED RESULTS

```
# from switch
#sh vlan id 16

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
16   ABC-10.10.16.0_25                active    Po1, Po11, Po34, Eth1/4
                                                Eth1/32

VLAN Type  Vlan-mode
---- ----- ----------
16   enet  FABRICPATH

Primary  Secondary  Type             Ports
-------  ---------  ---------------  -------------------------------------------

```
##### ACTUAL RESULTS

```
PLAY [add vlan in pod] **************************************************************************************************************************

TASK [create vlan in switches] ******************************************************************************************************************
changed: [ix1-test-s101a.net.dcinf.se] => {"changed": true, "commands": ["vlan 16", "name ABC-10.10.16.0_25", "state active", "no shutdown", "exit"]

# from switch
# sh vlan id 16

VLAN Name                             Status    Ports
---- -------------------------------- --------- -------------------------------
16   ABC-10.10.16.0_25                active    Po1, Po11, Po34, Eth1/4
                                                Eth1/32

VLAN Type  Vlan-mode
---- ----- ----------
16   enet  CE

Primary  Secondary  Type             Ports
-------  ---------  ---------------  -------------------------------------------

```
