### ISSUE TITLE
aws_application_scaling_policy.py needs register scalable target!

### ISSUE THREAD

**Issue by adrianrise** [ansible/ansible#40237]
##### ISSUE TYPE
 - Ability to register-scalable-target.

##### COMPONENT NAME
aws_application_scaling_policy.py 

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /Users/username/repos/ansible/ansible.cfg
  configured module search path = [u'/Users/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```
##### OS / ENVIRONMENT

OSX High Sierra 10.13.4

##### SUMMARY

I have been searching for a while but I think it would be a good feature also to add the ability to register scalable targets in this plugin.
Otherwise you have to do it from other way or you'll get this error:

```
    "msg": "An error occurred (ObjectNotFoundException) when calling the PutScalingPolicy operation: No scalable target registered for service namespace: dynamodb, resource ID: tablename, scalable dimension: dynamodb:table:ReadCapacityUnits"
```
So, I do not know if I am missing something but I think it would be a good feature to be together with this module.

##### STEPS TO REPRODUCE

```
  - name: Set AutoScaling in Dynamodb tables.
    aws_application_scaling_policy:
      state: present
      region: "{{ variables.region }}"
      profile: "{{ variables.profile }}"
      policy_name: DynamoDBScalingPolicyRead
      policy_type: TargetTrackingScaling
      resource_id: "{{ variables.customer }}.{{ item }}"
      scalable_dimension: dynamodb:table:ReadCapacityUnits
      service_namespace: dynamodb
      target_tracking_scaling_policy_configuration:
        TargetValue: 60
        PredefinedMetricSpecification:
          PredefinedMetricType: DynamoDBReadCapacityUtilization
        ScaleOutCooldown: 60
        ScaleInCooldown: 60
    with_items:
      - table
      - table2
```
