### ISSUE TITLE
Set_fact cannot access facts that were already set in the same step (2.5.2)

### ISSUE THREAD

**Issue by pantaoran** [ansible/ansible#40239]
##### ISSUE TYPE
 - ~Bug  Report~
- Feature Idea

##### COMPONENT NAME

set_fact

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /home/mypath/ansible.cfg
  configured module search path = [u'/home/mypath/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
CACHE_PLUGIN(/home/mypath/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/mypath/ansible.cfg) = /tmp/ansibleFactCache.json
CACHE_PLUGIN_TIMEOUT(/home/mypath/ansible.cfg) = 86400
DEFAULT_GATHERING(/home/mypath/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/mypath/ansible.cfg) = [u'/home/mypath/inventories/staging']
DEFAULT_REMOTE_USER(/home/mypath/ansible.cfg) = {{ ansible_user }}
DEFAULT_TIMEOUT(/home/mypath/ansible.cfg) = 50
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /etc/ansible/vault-passwd
DISPLAY_SKIPPED_HOSTS(/home/mypath/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/mypath/ansible.cfg) = False
```

##### OS / ENVIRONMENT

RHEL 7, in a docker container

##### SUMMARY

When setting several facts "at once", later facts cannot access the values of facts defined before them.
I've seen recent bug reports such as https://github.com/ansible/ansible/issues/38271 which could also be related to this. That one was fixed in 2.5.2 but mine is not.

##### STEPS TO REPRODUCE

```yaml
---
- name: test set_fact bug
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:

    - name: test bug
      set_fact:
        first: "world"
        second: "Hello {{ first }}"

    - debug: msg="{{ second }}"

```

##### EXPECTED RESULTS

I expect the debug output to be "Hello world", wihtout fatal error

##### ACTUAL RESULTS

```
PLAY [test set_fact bug] ***********************************************************************************************************************************************************************************

TASK [test bug] ********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'first' is undefined\n\nThe error appears to have been in '/home/mypath/test.yml': line 9, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: test bug\n      ^ here\n"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/utilities/logic/set_fact.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/utilities/logic/set_fact.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by GhostPratt** [comment]
A task cannot reference a fact that is to be set within itself.  When set_task is used it will set all of those variables at once at the end of the task.  So for your example it would require 2 separate tasks in order to create the 2nd fact.  Something like:

```
- name: test set_fact bug
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
          - name: test bug
            set_fact:
                    first="world"

          - set_fact:
                    second="Hello {{ first }}

          - debug:
                    msg={{second}}
```

**Comment by dagwieers** [comment]
Agreed, and I think this would be a very nice feature to have.
As a work-around you could use play-vars or task-vars, or use a vars-file.

**Comment by pantaoran** [comment]
So you're saying that this works as designed then?
I can also live with that, since the workaround is obvious and simple.

**Comment by dagwieers** [comment]
@pantaroran Nope, I never said it was designed like this. It simply never worked this way, and maybe it should. I don't see any downsides to allow this.

**Comment by bcoca** [comment]
reclassified, as @dagwieers says, this works as intended, but that does not mean we cannot alter it to allow for this.

**Comment by IPvSean** [comment]
hitting this issue as welll

this works fine
```
- name: print out the output
  debug:
    msg: 'BGP STATUS FOR {{peer}} IS {{status}}'
  vars:
    peer: "{{ ansible_facts.cisco_ios.vrf.DEFAULT.protocols.bgp.neighbors | first }}"
    status: "{{ 'Established' if ':' in ansible_facts.cisco_ios.vrf.DEFAULT.protocols.bgp.neighbors[peer].timer else 'Down' }}"
```

but trying to set_fact fails :(

**Comment by ryanmerolle** [comment]
Anyway we can scope the work required to address this?  I just hit it and there is a simple workaround to separate tasks, but it’s ideal or efficient.

**Comment by sumkincpp** [comment]
The idea itself is great, but I see a significant problem here - passed task args(_task.args) should have an order(OrderedDict), otherwise we can't be sure if the variable we are currently templating need to use old fact value or a new one.

**Comment by bcoca** [comment]
FYI, in Python dictionaries are 'unordered', depending on python version that order might be consistent or not. so as @sumkincpp states, this would require OrdreredDict, which is not available in Python 2.6

**Comment by karniemi** [comment]
bumped to this problem as well. I used the vars-workaround, too, for one task. Maybe(?) that workaround could be combined with set_fact-module if the facts/vars are needed for multiple tasks/plays.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/set_fact.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/set_fact.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by crazyhouse33** [comment]
Hello, what is the workaround for this then?
- name: List names of sites to enable
```
- name: List names of sites to enable
  set_fact:
    item_name: "{{ item | basename | regex_replace('.j2','') }}"
    to_enable_sites_names: "{{ to_enable_sites_names | default([]) + [ item_name ] }}"
  with_fileglob: "{{ role_path }}/templates/{{ object_type }}/sites-enabled/*"
```

**Comment by bcoca** [comment]
@crazyhouse33 see @dagwieers comment about `vars:`

**Comment by tfmark** [comment]
> 

Can't you do this?
```yaml
- name: List names of sites to enable
  set_fact:
    to_enable_sites_names: "{{ to_enable_sites_names | default([]) + [ item | basename | regex_replace('.j2','') ] }}"
  with_fileglob: "{{ role_path }}/templates/{{ object_type }}/sites-enabled/*"
```
