### ISSUE TITLE
User and Password while using the uri_modul

### ISSUE THREAD

**Issue by huiminzeng** [ansible/ansible#40232]
##### ISSUE TYPE
 - Documentation Report

uri modul
parameter user and modul

##### ANSIBLE VERSION

```
ansible version: 2.5.2
```

##### CONFIGURATION

default configuration

##### OS / ENVIRONMENT

ubuntu 16.04
##### SUMMARY

Is there any possibility create a user for an application, for instance Rocket.Chat, via ansible? I tried to get the system info with ansible-playbook, which worked just fine.
But once i tried to log in or create a new user, error happened. 
I am not sure, if i understood the term "user" and "password". and i don't know the value of the parameters?  Are they the coded token something or just the account information of Rocketchat?
Thanks!
##### STEPS TO REPRODUCE

```
---
- name: uri test
  hosts: local
  connection: loc
  tasks:
   - name: system info
     uri:
       url: http://localhost:3000/api/v1/info
       method: GET

   - name: login
     uri:
       url: http://localhost:3000/api/v1/login
       method: POST
       user: 7HZbmGjYLkkSW7nFC
       password: pfq2uujnSHUM0xgb1uXl0IYp_8y1eZ8PYhejPA1322T
```

https://github.com/RocketChat/Rocket.Chat.Ansible/issues/86
##### EXPECTED RESULTS

i can log in or create a user
##### ACTUAL RESULTS

failed

```
ansible-playbook test.yml -i hosts.ini
```
