### ISSUE TITLE
Copy creates only directory when notify handler doesn't exist

### ISSUE THREAD

**Issue by ilevd** [ansible/ansible#40249]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

copy
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/igor/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

Copy module only creates folders, without copying files, it there is 'notify' which handler doesn't exist.
##### STEPS TO REPRODUCE

```yaml
# playbook.yml
- name: Playbook
  hosts: export-server
  remote_user: root
  roles: 
    - role: copytest
# roles/copytest/tasks/main.yml
- name: Copy Nginx config files
  copy:
    src: static/data/
    dest: /app/ansible-test
    notify:
      - restart nginx # handler doesn't exist

```

##### EXPECTED RESULTS

Copy entire files or error message that handler doesn't exist
##### ACTUAL RESULTS

Creating only folders without copying files

```

PLAY [Playbook] *************************************************************************************************

TASK [Gathering Facts] ******************************************************************************************
ok: [export-server]

TASK [copytest : Copy Nginx config files] ***********************************************************************
changed: [export-server]

PLAY RECAP ******************************************************************************************************
export-server              : ok=2    changed=1    unreachable=0    failed=0   

```
