### ISSUE TITLE
nxos_command - wait_for - operator negation support

### ISSUE THREAD

**Issue by Leggggg** [ansible/ansible#40264]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

nxos_command

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /home/username/.ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/username/.ansible.cfg) = True
DEFAULT_GATHERING(/home/username/.ansible.cfg) = implicit
DEFAULT_HOST_LIST(/home/username/.ansible.cfg) = [u'/home/username/testing/hosts']
DEFAULT_LOCAL_TMP(/home/username/.ansible.cfg) = /home/username/.ansible/tmp/ansible-local-32724OYYNUS
DEFAULT_LOG_PATH(/home/username/.ansible.cfg) = /home/username/session2.log
DEFAULT_NO_LOG(/home/username/.ansible.cfg) = False
DEFAULT_REMOTE_PORT(/home/username/.ansible.cfg) = 22
DEFAULT_ROLES_PATH(/home/username/.ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_STDOUT_CALLBACK(/home/username/.ansible.cfg) = skippy
DEFAULT_TIMEOUT(/home/username/.ansible.cfg) = 30
DEFAULT_TRANSPORT(/home/username/.ansible.cfg) = smart
DEPRECATION_WARNINGS(/home/username/.ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/username/.ansible.cfg) = False
HOST_KEY_CHECKING(/home/username/.ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/home/username/.ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/home/username/.ansible.cfg) = 30
```

##### OS / ENVIRONMENT

`Red Hat Enterprise Linux Server release 7.4 (Maipo)`

##### SUMMARY

nxos_command's wait_for is limiting, and does not support negation or multiple operators when parsing conditionals.

- It uses its own boolean logic keywords (contains, etc) and appears to converts them to standard logic (in, !=, etc) but it does not support negation ( ! contains, not in, etc).

-  It seems to be unable to be subverted because it converts to standard python logic and passes it through SHLEX such that only one conditional operator can be parsed at once. (SHLEX may or may not be able to parse nested conditionals but whether it can or not the module is hard coded to their exact use of it)

##### STEPS TO REPRODUCE

**EXAMPLE OF PORT LIST CONTAINS LIST OF INTERFACES**
```yaml
 - name: VALIDATE VLAN ADDED TO TRUNK
   nxos_command:
     commands:
       - command: "show vlan id {{ item[0].vlan_id }}"
         output: json
     wait_for:
       - "result[0]['TABLE_vlanbriefid']['ROW_vlanbriefid']['vlanshowplist-ifidx'] contains {{ item[1] }}"
   with_nested:
     - "{{ L2_VLAN }}"
     - "{{ INT_TRUNK }}"
   when: INT_TRUNK is defined
```

**EXAMPLE(s) OF PORT LIST DOES NOT CONTAIN LIST OF INTERFACES**
```yaml
 - name: VALIDATE VLAN ADDED TO TRUNK
   nxos_command:
     commands:
       - command: "show vlan id {{ item[0].vlan_id }}"
         output: json
     wait_for:
       - "result[0]['TABLE_vlanbriefid']['ROW_vlanbriefid']['vlanshowplist-ifidx'] not contains {{ item[1] }}"
   with_nested:
     - "{{ L2_VLAN }}"
     - "{{ INT_TRUNK }}"
   when: INT_TRUNK is defined
```
```yaml
 - name: VALIDATE VLAN ADDED TO TRUNK
   nxos_command:
     commands:
       - command: "show vlan id {{ item[0].vlan_id }}"
         output: json
     wait_for:
       - "result[0]['TABLE_vlanbriefid']['ROW_vlanbriefid']['vlanshowplist-ifidx'] not in {{ item[1] }}"
   with_nested:
     - "{{ L2_VLAN }}"
     - "{{ INT_TRUNK }}"
   when: INT_TRUNK is defined
```
```yaml
 - name: VALIDATE VLAN ADDED TO TRUNK
   nxos_command:
     commands:
       - command: "show vlan id {{ item[0].vlan_id }}"
         output: json
     wait_for:
       - "(result[0]['TABLE_vlanbriefid']['ROW_vlanbriefid']['vlanshowplist-ifidx'] contains {{ item[1] }}) != True"
   with_nested:
     - "{{ L2_VLAN }}"
     - "{{ INT_TRUNK }}"
   when: INT_TRUNK is defined
```

##### EXPECTED RESULTS

I expected to be able to utilize wait_for to affirm something is true, and also affirm something isn't true.

##### ACTUAL RESULTS

I am limited to a very specific set of operators, which in of themself limit the modules usability to validate items that can't be gleaned from nxos_facts such as vlan associations to interfaces.

```

TASK [L2-Trunk-Vlan_Configure-Pre-Check : VALIDATE VLAN DOES NOT EXIST ON TRUNK] ******************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ValueError: failed to parse conditional
failed: [3064-01] (item=[{u'vlan_name': u'PRIVATE-VLAN-2001', u'vlan_id': u'2001'}, u'port-channel111']) => {"changed": false, "item": [{"vlan_id": "2001", "vlan_name": "PRIVATE-VLAN-2001"}, "port-channel111"], "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_jKA7Qc/ansible_module_nxos_command.py\", line 248, in <module>\n    main()\n  File \"/tmp/ansible_jKA7Qc/ansible_module_nxos_command.py\", line 207, in main\n    conditionals = [Conditional(c) for c in wait_for]\n  File \"/tmp/ansible_jKA7Qc/ansible_modlib.zip/ansible/module_utils/network/common/parsing.py\", line 212, in __init__\nValueError: failed to parse conditional\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
