### ISSUE TITLE
URI module and cookies handling: lost "set_cookie" property (shown in docs).

### ISSUE THREAD

**Issue by Canta** [ansible/ansible#40278]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

uri
##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = 
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = explicit
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
DEFAULT_SUDO_FLAGS(/etc/ansible/ansible.cfg) = -H -S -n
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 20
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

N/A
##### SUMMARY

In two different servers, with different ansible versions, I get different output from the same uri call.
There's a difference in the cookies handling. v2.4 gives us the "cookies" property, while v2.3 returns "set_cookie".

The code involved is taken directly from the docs themselves: http://docs.ansible.com/ansible/latest/modules/uri_module.html#examples
It's working so far, for about 2y. But when we installed a new server recently, we found out the output pasted below. 

If it's an intended change, then the docs are wrong. Otherwise, something happened with "set_cookie".

##### STEPS TO REPRODUCE

Run the example tasks with ansible 2.3 and ansible 2.4

```yaml
- name: create authentication cookie for later requests (improves speed)
  uri:
    url: "{{ non_public_host }}/stuff"
    validate_certs: no
    user: "{{ user }}"
    password: "{{ pass }}"
    method: GET
    headers:
      Accept: "application/stuff+json"
  register: login

# and then we use later the login fact, this way:

- name: get stuff
  uri:
    url: "{{ non_public_host }}/stuff/list"
    validate_certs: no
    method: GET
    return_content: yes
    headers:
      Cookie: "{{ login.set_cookie }}"
  register: stuff_list

```

##### EXPECTED RESULTS

Same output. Specially the way cookies are handled.

##### ACTUAL RESULTS

v2.3 returns `set_cookie` property, while v2.4 returns `cookies` property. This way, expecting the `set_cookie` property (as the docs suggests) fails.

```
# This is the output with ansible 2.4, with some strings edited for privacy reasons:
TASK [roles/stuff : debugging login] ****************************************
ok: [127.0.0.1] => {
    "msg": {
       "cache_control": "max-age=0, private, must-revalidate", 
       "changed": false, 
       "connection": "close", 
       "content_type": "application/stuff+json; charset=utf-8", 
       "cookies": {
           "JSESSIONID": "ui74vbyaobr68mj22nmr8ggl"
       }, 
       "date": "Tue, 15 May 2018 15:01:53 GMT", 
       "etag": "\"7a9c36bb30d647628294fb324a7c0e1f\"", 
       "failed": false, 
       "msg": "OK (unknown bytes)", 
       "redirected": false, 
       "status": 200, 
       "url": "https://non-public-url/stuff", 
       "vary": "Accept-Encoding, User-Agent", 
       "x_content_type_options": "nosniff", 
       "x_frame_options": "SAMEORIGIN", 
       "x_request_id": "62f27c01-aa91-4bd8-8979-05430a1c38c4", 
       "x_runtime": "0.020000", 
       "x_ua_compatible": "chrome=1", 
       "x_xss_protection": "1; mode=block"
   }
}

# This is the output with ansible 2.3, using the same role with the same url:
TASK [roles/stuff : debugging login] ****************************************
ok: [localhost] => {
   "msg": {
       "cache_control": "max-age=0, private, must-revalidate", 
       "changed": false, 
       "connection": "close", 
       "content_type": "application/stuff+json; charset=utf-8", 
       "date": "Tue, 15 May 2018 15:05:17 GMT", 
       "etag": "\"5ce7ca165672c9ac77e47d0c3617abb2\"", 
       "expires": "Thu, 01 Jan 1970 00:00:00 GMT", 
       "msg": "OK (unknown bytes)", 
       "redirected": false, 
       "set_cookie": "JSESSIONID=q5z2ud6gpvkh1cw3x6g5wf3ku;Path=/stuff;Expires=Tue, 29-May-2018 15:05:19 GMT;Secure;HttpOnly", 
       "status": 200, 
       "url": "https://non-public-url/stuff", 
       "vary": "Accept-Encoding, User-Agent", 
       "x_content_type_options": "nosniff", 
       "x_frame_options": "SAMEORIGIN", 
       "x_request_id": "105e228f-b356-4bc6-87dd-37c459dc008a", 
       "x_runtime": "0.025000", 
       "x_ua_compatible": "chrome=1", 
       "x_xss_protection": "1; mode=block"
   }
}
```
