### ISSUE TITLE
Terraform module targeting

### ISSUE THREAD

**Issue by gomker** [ansible/ansible#40273]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

terraform
##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
  
```
Running latest devel branch for testing terraform in a separate virtual environment
```

/var/lib/awx/venv/devel_branch/bin/pip install git+https://github.com/ansible/ansible.git@devel -U

```

##### CONFIGURATION

No output was displayed from this command
##### OS / ENVIRONMENT

N/A
##### SUMMARY

Targeting a specific module seems to still load the entire plan
##### STEPS TO REPRODUCE

```yaml

- name: run terraform - aws base
  terraform:
    project_path : '../terraform/plans/awx'
    force_init: true
    variables:
      account_id: "{{ cloud_account }}"
      access_key: "{{ access_key }}"
      secret_key: "{{ secret_key }}"
      token: "{{ token }}"
      key_name: "{{ cloud_key }}"
      cidr_bock: "{{ cidr_block }}"
      region: "{{ cloud_region }}"
      repository_uri: "{{ repository_uri }}"
      rds_master_username: 'awxmaster'
      rds_master_password: "{{ rds_master_password }}"
      awx_db_username: 'awxdb'
      awx_db_password: "{{ awx_db_password }}"
    targets: module.aws_base

```

Terraform plan setup

```

module "aws_base" {
  source             = "../../modules/aws_base"
  name               = "ras-vpc"
  region             = "${var.region}"
  cidr_block         = "${var.cidr_block}"
  availability_zones = "${lookup(var.availability_zones, "${var.region}")}"
  environment        = "${var.environment}"
  account_id         = "${var.account_id}"
  dns_support        = true
  dns_hostnames      = true
}
...

module "next_module"
{
....
}
```

##### EXPECTED RESULTS

Only run the specified targeted module from the terraform plan.
Instead of running only `module.aws_base` it attempted to run `module.next_module` as well
##### ACTUAL RESULTS

The entire plan was run.

```

```

I have to run the plan in stages 
* aws_base
* rds
* postgres

Due to limitations in Terraform
