### ISSUE TITLE
vmware_vmkernel unable to update existing vmk

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#40299]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

```
vmware_vmkernel
```
##### ANSIBLE VERSION

```
2.5
```

##### STEPS TO REPRODUCE

```
---
- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  tasks:
       -  name: Add Management vmkernel Interface to ESXI host
          vmware_vmkernel:
            esxi_hostname: mran03.thinkagile.com
            hostname: 10.243.1.45
            username: root
            password: PASSW0RD
            vswitch_name: vSwitch0
            portgroup_name: "Management Network"
            vlan_id: 0
            network:
               type: dhcp
               ip_address: ""
               subnet_mask: ""
            enable_mgmt: True
            enable_vmotion: True
            enable_vsan: True
            validate_certs: False

Here Management Network portgroup is attached to vmnic0, and vmk is vmk0.This vmk is already created i am trying to update it with service vsan. Ip address of vmk0 is also 10.243.1.45.

```

##### EXPECTED RESULTS

```
expecting vmk0 get updated with vsan service
```
##### ACTUAL RESULTS

```
ansible-playbook test.yaml -vvvv
ansible-playbook 2.5.0
  config file = None
  configured module search path = [u'/home/lenovo/.ansible/plugins/modules', u'/                                                                                        usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansibl                                                                                        e-2.5.0-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
No config file found; using defaults
setting up inventory plugins
[WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

[WARNING]: No inventory was parsed, only implicit localhost is available

[WARNING]: provided hosts list is empty, only localhost is available. Note
that the implicit localhost does not match 'all'

Loading callback plugin default of type stdout, v2.0 from /usr/local/lib/python2                                                                                        .7/dist-packages/ansible-2.5.0-py2.7.egg/ansible/plugins/callback/default.pyc

PLAYBOOK: test.yaml ************************************************************
1 plays in test.yaml

PLAY [127.0.0.1] ***************************************************************
META: ran handlers

TASK [Add Management vmkernel Interface to ESXI host] **************************
task path: /home/lenovo/test.yaml:6
Using module file /usr/local/lib/python2.7/dist-packages/ansible-2.5.0-py2.7.egg                                                                                        /ansible/modules/cloud/vmware/vmware_vmkernel.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: lenovo
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/lenovo/.ansibl                                                                                        e/tmp/ansible-local-909904hwH0/ansible-tmp-1526481547.77-242758496922807 `" && e                                                                                        cho ansible-tmp-1526481547.77-242758496922807="` echo /home/lenovo/.ansible/tmp/                                                                                        ansible-local-909904hwH0/ansible-tmp-1526481547.77-242758496922807 `" ) && sleep                                                                                         0'
<127.0.0.1> PUT /home/lenovo/.ansible/tmp/ansible-local-909904hwH0/tmpfPKV0x TO                                                                                         /home/lenovo/.ansible/tmp/ansible-local-909904hwH0/ansible-tmp-1526481547.77-242                                                                                        758496922807/vmware_vmkernel.py
09904hwH0/ansible-tmp-1526481547.77-242758496922807/ /home/lenovo/.ansible/tmp/a                                                                                        nsible-local-909904hwH0/ansible-tmp-1526481547.77-242758496922807/vmware_vmkerne                                                                                        l.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /home/lenovo/.ansible/tmp/ansible-l                                                                                        ocal-909904hwH0/ansible-tmp-1526481547.77-242758496922807/vmware_vmkernel.py &&                                                                                         sleep 0'
The full traceback is:
  File "/tmp/ansible_n_7Uqm/ansible_module_vmware_vmkernel.py", line 540, in query_service_type_for_vmks
    query = self.esxi_host_obj.configManager.virtualNicManager.QueryNetConfig(service_type)
  File "/home/lenovo/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/home/lenovo/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/home/lenovo/.local/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/home/lenovo/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/home/lenovo/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/home/lenovo/.local/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1320, in InvokeMethod
    resp = conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1136, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 417, in _read_status
    raise BadStatusLine(line)

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "failed": true,
    "invocation": {
        "module_args": {
            "enable_ft": null,
            "enable_mgmt": true,
            "enable_vmotion": true,
            "enable_vsan": true,
            "esxi_hostname": "mran03.thinkagile.com",
            "hostname": "10.243.1.45",
            "ip_address": null,
            "mtu": 1500,
            "network": {
                "ip_address": "",
                "subnet_mask": "",
                "type": "dhcp"
            },
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "portgroup_name": "Management Network",
            "state": "present",
            "subnet_mask": null,
            "username": "root",
            "validate_certs": false,
            "vlan_id": 0,
            "vswitch_name": "vSwitch0"
        }
    },
    "msg": "Failed to get all VMKs for service type management due to''"
}

```
