### ISSUE TITLE
ovh_ip_loadbalancing_backend outdated

### ISSUE THREAD

**Issue by P4ndaFR** [ansible/ansible#40305]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

ovh_ip_loadbalancing_backend
##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/antoine/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 23 2017, 16:37:01) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -F /home/antoine/.ssh/ssh_config -o ForwardAgent=yes -o StrictHostKeyChecking=no
ANSIBLE_SSH_CONTROL_PATH(/etc/ansible/ansible.cfg) = ~/.ssh/mux-%r@%h:%p
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Client : Ubuntu 16.04.4 LTS , Target : N/A
##### SUMMARY

This module doesn't support some of the OVH API options : 
- SSL ( activate SSL between the server and the LB )
- chain ( Certificate chain )
- cookie ( cookie stickiness )
- port ( the port attached to the server )
- proxyProtocolVersion ( send ProxyProtocole Header )
- backup: set the server as  a backup server

In my opinion it is sometimes hard to catch with a cloud provider development, so a more viable solution could be to use a dict ( let's says "options" ), that contains all the options ( body of the request ) to send to the OVH API: users would refer to the OVH API to know what options they should use: this method would require less work to maintain and should allow to keep up with the latest API changes.

If you think it is a good idea, i can work on it and submit a PR ASAP.
##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/ovh/ovh_ip_loadbalancing_backend.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovh/ovh_ip_loadbalancing_backend.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @pascalheraud
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pascalheraud** [comment]
This module was intended to only manage backends for an ip loadbalancer.
Thus it is possible to implement an ansible module that is compliant with Ansible's model (dry run using -C, checks state and does nothing if nothing different)

If you want to provide a generic service accessing the API, I think it should be a different module, maybe one module for all OVH API ? It could be useful to manage stuff not existing yet into a dedicated module.

**Comment by P4ndaFR** [comment]
Sorry, I might have been a bit confusing here: I'm talking about the same thing; manage backends for IPLB: if you look at the current documentation, there are new parameters: https://api.ovh.com/console/#/ipLoadbalancing/%7BserviceName%7D/http/farm/%7BfarmId%7D/server#POST

**Comment by pascalheraud** [comment]
Ok got it. You're not pointing to the same API this module is using, it's using the previous version of the load balancer (https://api.ovh.com/console/#/ip/loadBalancing/%7BserviceName%7D/backend#POST). 

I think the previous version is not working at all anymore because all OVH's load balancers have been migrated to the new one. So this module is probably not working anymore, if you want to implement new API, feel free. The question is :  do we still support old version of the old balancer ? Maybe, you should propose a new module (beware that merging a new module is a long process, I still have modules waiting since 4 month)

**Comment by P4ndaFR** [comment]
I am going to work on a new module, that supports the current ipLoadBalancing registering for now, so we have something working here. I think supporting the old LBs is not really helpful : 
- As you said: all LBs have been migrated to a new version
- the ovh python support does not seem to take the API version as a parameter: https://github.com/ovh/python-ovh#configuration, it means that it needs to be done the old HTTP fashion way, with signing etc.

**Comment by Nephylhim** [comment]
Hi!

IPLB techie here =)
the /ip/loadBalancing/ endpoint isn't supported anymore. The correct one is https://api.ovh.com/console/#/ipLoadbalancing
This endpoint support all lb (old and new ones). IPLB's API documentation is available here: https://docs.ovh.com/fr/load-balancer/api-details/

If you need some help, you might find some on our community too (mostly french): https://community.ovh.com/c/cloud/solution-reseau-et-securite

Bests

**Comment by P4ndaFR** [comment]
Hello @pascalheraud ,
I'm currently working on a PR for the ovh_ip_loadbalancing_backend : 

Do you think that handling parameters this way could be a good idea:
```                                                                                                       
- ovh_ip_loadbalancing:                                                                               
    state: present                                                                                    
    endpoint: ovh-eu                                                                                  
    application_key: yourkey                                                                          
    application_secret: yoursecret                                                                    
    consumer_key: yourconsumerkey                                                                     
    service_name: yourservicename                                                                     
    farm_id: yourfarmid                                                                               
    display_name: yourbackendname                                                                                
    options: (dict)  see https://api.ovh.com/console/#/ipLoadbalancing/%7BserviceName%7D/http/farm/%7BfarmId%7D/server#POST for available options
                                                                                                                                                                                                                 
# Removes a backend '212.1.1.1' from a loadbalancing 'ip-1.1.1.1'                                     
- ovh_ip_loadbalancing:
    state: absent
    endpoint: ovh-eu                                                                                  
    application_key: yourkey
    application_secret: yoursecret                                                                    
    consumer_key: yourconsumerkey
    service_name: yourservicename                                                                     
    display_name: yourbackendname
```
where options is a dict containing the options send to OVH, that way people would refer directly to 
https://api.ovh.com/console/#/ipLoadbalancing/%7BserviceName%7D/http/farm/%7BfarmId%7D/server#POST except for the displayName ( the backend name ) that would be the key to have idempotency : if a backend already exists with this name, then do nothing ( if state = present ).
this way, if a field change in body of the ipLoadbalancing/{serviceName}/http/farm/{farmId}/server#POST route, we don't need to maintain it.

Bests.
