### ISSUE TITLE
ansible2.4  win_shell got no effect when exec on mount disk

### ISSUE THREAD

**Issue by wjainiya** [ansible/ansible#40302]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_shell
win_disk_image

##### ANSIBLE VERSION
`2.4.1`

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
windows server 2016 standard

##### SUMMARY
When i try to install huflt8 from hulft-windows-ne-v813.iso with silent mode ,  i write playbook like this

```
- name: mount install packages
  win_disk_image:
    image_path: "C:\\Temp\\hulft-windows-ne-v813.iso"
    state: present
  register: ret

- set_fact:
    setup_exe_path: "{{ ret.mount_path }}"

- win_shell: '{{ setup_exe_path }}setup.exe -s -f1"C:\\Temp\\setup.iss"'
```

and the result is ok ,nothing error happened. but on windows server ,nothing installed, but have mounted  iso images on E:\\

I tried use  hulft-windows-ne-v813.zip , i changed playbook like this

```
- name: mount install packages
  win_unzip:
    src: "C:\\Temp\\hulft-windows-ne-v813.zip"
    dest: "C:\\Temp\\hulft-windows-ne-v813"

- win_shell: 'C:\\Temp\\hulft-windows-ne-v813\\setup.exe -s -f1"C:\\Temp\\setup.iss"'
```

and the result is ok , installed hulft8 on windows server .
so ,i wonder if the problem is  ansible cannot exec powershell command on mounted disk ?

##### EXPECTED RESULTS
should installed hulf8 on windows server

##### ACTUAL RESULTS
nothing installed

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_disk_image.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_disk_image.py)
* [lib/ansible/modules/windows/win_shell.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_shell.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth @nitzmahone
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jhawkesworth** [comment]
What happens if you run with  -v ?

Also please add a 

```
 - name: show path
    debug:
         var: setup_exe_path
```
after the

```
- set_fact:
    setup_exe_path: "{{ ret.mount_path }}"
```

To see what is being stored in 'setup_exe_path'
I suspect what is happening is the windows path separator is getting mangled due to use of double quotes.

I think if you code it like the example (use return value directly, inside _single_ quotes), it will do the right thing.

```
- name: mount install packages
  win_disk_image:
    image_path: "C:\\Temp\\hulft-windows-ne-v813.iso"
    state: present
  register: ret

- win_shell: '{{  ret.mount_path }}setup.exe -s -f1"C:\\Temp\\setup.iss"'
```

I thoroughly recommend reading this documentation about constructing windows paths as it will help you avoid some of the issues where windows paths and yaml don't fit together particularly well.

https://docs.ansible.com/ansible/2.5/user_guide/windows_usage.html#path-formatting-for-windows
