### ISSUE TITLE
Handling errors not working?

### ISSUE THREAD

**Issue by adrianrise** [ansible/ansible#40328]
##### ISSUE TYPE
Hi there,

I was handling an error in a task but I noticed it is not working...

##### COMPONENT NAME
Handling errors.

failed_when
changed_when

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /Users/username/repos/Ansible/ansible.cfg
  configured module search path = [u'/Users/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### OS / ENVIRONMENT

MAC OSX High Sierra

##### SUMMARY
The handling errors are not working as expected.

##### STEPS TO REPRODUCE

```
  - name: AWS task
    shell: >
      aws dynamodb update-table --table-name "{{ item }}" --stream-specification StreamEnabled=true,StreamViewType="NEW_AND_OLD_IMAGES" --profile "{{ variables.profile }}" --region "{{ variables.region_dr }}"
    with_items:
      - table1
      - table2
    register: result2
    changed_when: result2.rc == 0 or result2.rc == 255
```

Same for failed_when

```
  - name: AWS task
    shell: >
      aws dynamodb update-table --table-name "{{ item }}" --stream-specification StreamEnabled=true,StreamViewType="NEW_AND_OLD_IMAGES" --profile "{{ variables.profile }}" --region "{{ variables.region_dr }}"
    with_items:
      - table1
      - table2
    register: result2
    failed_when: result2.rc != 0 or result2.rc != 255
```

##### EXPECTED RESULTS
To get a changed instead of failed.

##### ACTUAL RESULTS

```
failed: [localhost] (item=BF_USER) => {
    "changed": true,
    "cmd": "aws dynamodb update-table --table-name \"devel-test.BF_USER\" --stream-specification StreamEnabled=true,StreamViewType=\"NEW_AND_OLD_IMAGES\" --profile \"devel\" --region \"us-west-1\"",
    "delta": "0:00:03.647563",
    "end": "2018-05-17 17:02:26.636427",
    "invocation": {
        "module_args": {
            "_raw_params": "aws dynamodb update-table --table-name \"table1\" --stream-specification StreamEnabled=true,StreamViewType=\"NEW_AND_OLD_IMAGES\" --profile \"default\" --region \"us-west-1\"",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "item": "table1",
    "msg": "non-zero return code",
    "rc": 255,
    "start": "2018-05-17 17:02:22.988864",
    "stderr": "\nAn error occurred (ValidationException) when calling the UpdateTable operation: Table already has an enabled stream: TableName: default.table1",
    "stderr_lines": [
        "",
        "An error occurred (ValidationException) when calling the UpdateTable operation: Table already has an enabled stream: TableName: default.table1"
    ],
    "stdout": "",
    "stdout_lines": []
}
```

And the same when result code is 0.

```
failed: [localhost] (item=table1) => {
    "changed": true,
    "cmd": "aws dynamodb update-table --table-name \"default.table1\" --stream-specification StreamEnabled=true,StreamViewType=\"NEW_AND_OLD_IMAGES\" --profile \"default\" --region \"us-west-1\"",
    "delta": "0:00:01.411326",
    "end": "2018-05-17 16:52:20.840013",
    "failed_when_result": true,
    "invocation": {
        "module_args": {
            "_raw_params": "aws dynamodb update-table --table-name \"default.table1\" --stream-specification StreamEnabled=true,StreamViewType=\"NEW_AND_OLD_IMAGES\" --profile \"default\" --region \"us-west-1\"",
            "_uses_shell": true,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "warn": true
        }
    },
    "item": "table1",
    "rc": 0,
    "start": "2018-05-17 16:52:19.428687",
    "stderr": "",
    "stderr_lines": [],
    "stdout": " JSON OUTPUT RETURNED.
        "    }",
        "}"
    ]
}
```
