### ISSUE TITLE
When LOCALE is not English, rhsm_repository failed with message <repoId> is not a valid repository ID

### ISSUE THREAD

**Issue by Arsou33** [ansible/ansible#40332]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rhsm_repository

##### ANSIBLE VERSION
```
ansible 2.6.0 (devel 4c0ceaea3d) last updated 2018/05/17 13:44:37 (GMT +200)
  config file = None
  configured module search path = [u'/Users/arsouille/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/arsouille/Documents/onepoint/redhat/sources/ansible/lib/ansible
  executable location = /Users/arsouille/Documents/onepoint/redhat/sources/ansible/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### OS / ENVIRONMENT
MacOs

##### SUMMARY
When Locale is not english, rhsm_repository failed with message :
```
failed: [netool] (item=rhel-7-server-ansible-2.4-rpms) => 
{
  "changed": false,
  "item": "rhel-7-server-ansible-2.4-rpms",
  "msg": "rhel-7-server-ansible-2.4-rpms is not a valid repository ID",
  "results": [
    "rhel-7-server-ansible-2.4-rpms is not a valid repository ID"
  ]
}
```

Problem has been similar to : https://github.com/ansible/ansible/issues/40057
Problem is localized at : https://github.com/ansible/ansible/blob/57f6abdb8460f8501eb9668004f4d7722bda5570/lib/ansible/modules/packaging/os/rhsm_repository.py#L117 as in french the field title is not 'Repo Id'

##### STEPS TO REPRODUCE
unset LC_ALL
set LANG=fr_FR.UTF-8

Extract of problematic playbook :

```yaml
    - name: Activate needed repo
      rhsm_repository:
        name: "{{ item }}"
        state: enabled
      with_items:
      - rhel-7-server-ansible-2.4-rpms
      - rhel-7-server-ose-3.9-rpms
```

Start the play

##### EXPECTED RESULTS
Should don't return error

##### ACTUAL RESULTS
cf Summary
