### ISSUE TITLE
role fonctionnal with ansibe installed via package manager but not with pip install

### ISSUE THREAD

**Issue by rockandska** [ansible/ansible#40331]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ansible-playbook

##### ANSIBLE VERSION
```
$ ansible --version
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ypanier/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ypanier/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ypanier/.local/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
```
$ ansible-config dump --only-changed
$ 
```

##### OS / ENVIRONMENT
```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
but same error with 16.04

#### SUMMARY
It seems than the install via pip and the install via the ansible repository doesn't install the same things or works differently.

I have a role who only works with ansible installed via package manager but not works with pip installed version

##### STEPS TO REPRODUCE
Start from a fresh OS install to reproduce the bug.
Bellow is the part who throw the bug

test_play.yml
```yaml
---
- hosts: localhost

  tasks:
  - name: Master | Clean up previous zone
    file:
      state: absent
      path: "/var/lib/icinga2/api/zones/{{ item }}"
    with_items: "{{ (icinga2_satellite_groups_name | length > 0) |ternary( (hostvars[primary_master_node].icinga2_zones_presence.stdout_lines|difference(['global-templates', icinga2_master_group_name, '(icinga2_satellite_groups_name|unique|join('\', \''))' ])), (hostvars[primary_master_node].icinga2_zones_presence.stdout_lines|difference(['global-templates', icinga2_master_group_name])) ) }}"
```
```
$ sudo apt-get install python-pip
$ pip install --user ansible
```
If I remove ansible installed via pip in my environment and install it from ansible repository , everything are fine.

This could by reproduce with docker too : 

Non functional:
```
$ docker run --rm -it -v /tmp/test_play.yml:/tmp/test_play.yml ubuntu bash -c 'apt-get update &> /dev/null && apt-get install -y python-pip &> /dev/null && pip install ansible &> /dev/null && ansible --version && ansible-playbook /tmp/test_play.yml'
```
Functional: 
```
$ docker run --rm -it -v /tmp/test_play.yml:/tmp/test_play.yml ubuntu bash -c 'apt-get update &> /dev/null && apt-get stall -y software-properties-common &> /dev/null && apt-add-repository -y ppa:ansible/ansible &> /dev/null && apt-get update &> /dev/null && apt-get install -y ansible &> /dev/null && ansible --version && ansible-playbook /tmp/test_play.yml'
```

##### EXPECTED RESULTS
```
$ ansible-playbook test_play.yml 
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [localhost] *****************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************
ok: [localhost]

TASK [Master | Clean up previous zone] *******************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "'icinga2_satellite_groups_name' is undefined"}
	to retry, use: --limit @/tmp/test_play.retry

PLAY RECAP ***********************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   

```

##### ACTUAL RESULTS
```
$ ansible-playbook test_play.yml 
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

ERROR! Syntax Error while loading YAML.
  found unknown escape character "'"

The error appears to have been in '/tmp/test_play.yml': line 9, column 248, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      path: "/var/lib/icinga2/api/zones/{{ item }}"
    with_items: "{{ (icinga2_satellite_groups_name | length > 0) |ternary( (hostvars[primary_master_node].icinga2_zones_presence.stdout_lines|difference(['global-templates', icinga2_master_group_name, '(icinga2_satellite_groups_name|unique|join('\', \''))' ])), (hostvars[primary_master_node].icinga2_zones_presence.stdout_lines|difference(['global-templates', icinga2_master_group_name])) ) }}"
                                                                                                                                                                                                                                                       ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"
```
