### ISSUE TITLE
ios_config times out over high latency links when sending lots of lines

### ISSUE THREAD

**Issue by ibarrere** [ansible/ansible#40342]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_config

##### ANSIBLE VERSION

```
ansible 2.6.0 (pr/39204 0fe0cd7492) last updated 2018/04/26 10:49:00 (GMT -600)
  config file = /home/ibarrere/git/ansible/ansible.cfg
  configured module search path = [u'/home/ibarrere/git/ansible/library']
  ansible python module location = /opt/ansible/source/lib/ansible
  executable location = /opt/ansible/source/bin/ansible
  python version = 2.7.9 (default, Nov 18 2015, 13:07:23) [GCC 4.4.7 20120313 (Red Hat 4.4.7-16)]
```

##### CONFIGURATION

ANSIBLE_NOCOWS(/home/ibarrere/git/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/ibarrere/git/ansible/ansible.cfg) = -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s
CACHE_PLUGIN(/home/ibarrere/git/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/ibarrere/git/ansible/ansible.cfg) = ./cache
CACHE_PLUGIN_TIMEOUT(/home/ibarrere/git/ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/home/ibarrere/git/ansible/ansible.cfg) = 25
DEFAULT_GATHERING(/home/ibarrere/git/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/ibarrere/git/ansible/ansible.cfg) = [u'/home/ibarrere/git/ansible/inventory/production']
DEFAULT_LOG_PATH(/home/ibarrere/git/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/home/ibarrere/git/ansible/ansible.cfg) = Ansible managed from {host}
DEFAULT_MODULE_PATH(/home/ibarrere/git/ansible/ansible.cfg) = [u'/home/ibarrere/git/ansible/library']
DEFAULT_POLL_INTERVAL(/home/ibarrere/git/ansible/ansible.cfg) = 7
DEFAULT_ROLES_PATH(/home/ibarrere/git/ansible/ansible.cfg) = [u'/home/ibarrere/git/ansible/roles']
DEFAULT_TIMEOUT(/home/ibarrere/git/ansible/ansible.cfg) = 20
DEFAULT_VAULT_PASSWORD_FILE(/home/ibarrere/git/ansible/ansible.cfg) = /home/ibarrere/git/ansible/open_the_vault.sh
DISPLAY_SKIPPED_HOSTS(/home/ibarrere/git/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/ibarrere/git/ansible/ansible.cfg) = False
RETRY_FILES_SAVE_PATH(/home/ibarrere/git/ansible/ansible.cfg) = /home/ibarrere/.ansible-retry

##### OS / ENVIRONMENT

CentOS release 6.9 (Final)

##### SUMMARY

When using ios_config to reconfigure an access-list, sending of access-lists beyond a certain number of lines fails over high latency links (more than around 200ms). A potential workaround is splitting the access-list up into several parts, each configured in independent tasks, which succeeds. It looks like it can send ~17 lines to this particular router (230ms) before it fails. Configuring the same access-list on devices over less latent connections succeeds as well.

I tried fiddling with the timeout values (both connection and command), but had no luck. At this point I'm just breaking it up into smaller groups of code and sending independently, but I thought it would be good to get a report out there anyway.

##### STEPS TO REPRODUCE

```yaml
- name: compile access-list permit pairs
  set_fact:
    compiled_pairs: "{{ compiled_pairs | default([]) }} + [ 'permit {{ item.prot }} {{ item.src_address }} {{ item.src_port|default() }}{{ item.dest_address }} {{ item.dest_port|default() }}']"
  loop: "{{ permit_pairs }}"

- name: compile access-list template
  set_fact:
    template:
      - deny   ip any object-group LOCAL_IPS log
      - deny   ip 127.0.0.0 0.255.255.255 any log
      - deny   ip 10.0.0.0 0.255.255.255 any log
      - deny   ip 172.16.0.0 0.15.255.255 any log
      - deny   ip 192.168.0.0 0.0.255.255 any log
      - deny   ip 224.0.0.0 31.255.255.255 224.0.0.0 31.255.255.255 log
      - deny   ip 169.254.0.0 0.0.255.255 any log
      - permit icmp any any time-exceeded
      - permit icmp any any echo
      - permit icmp any any echo-reply
      - permit icmp any any unreachable
      - permit icmp any any source-quench
      - permit icmp any any parameter-problem
      - deny   icmp any any log
      - permit esp any any
      - permit ahp any any
      - permit gre any any
      - permit ip any any
  when: permit_pairs is defined

- name: configure access-list
    ios_config:
      parents: "ip access-list extended OUTSIDE_IN"
     lines: "{{ compiled_pairs + template }}" 
     before: "no ip access-list extended OUTSIDE_IN"
      match: line
      replace: block
    notify: "write"
```

##### EXPECTED RESULTS

The config above loops through some host variables to get host-specific permit statements, then joins them to the basic template, then sends them both to the router. The expected result is for the access-list to be configured accordingly on the router.

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ansible.module_utils.connection.ConnectionError: timeout trying to send command: permit icmp any any time-exceeded
fatal: [hyd1ertr01]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_TF2HH9/ansible_module_ios_config.py\", line 560, in <module>\n    main()\n  File \"/tmp/ansible_TF2HH9/ansible_module_ios_config.py\", line 489, in main\n    load_config(module, commands)\n  File \"/tmp/ansible_TF2HH9/ansible_modlib.zip/ansible/module_utils/network/ios/ios.py\", line 162, in load_config\n  File \"/tmp/ansible_TF2HH9/ansible_modlib.zip/ansible/module_utils/connection.py\", line 149, in __rpc__\nansible.module_utils.connection.ConnectionError: timeout trying to send command: permit icmp any any time-exceeded\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
