### ISSUE TITLE
support TargetTrackingScaling autoscaling policy type

### ISSUE THREAD

**Issue by adpjay** [ansible/ansible#40356]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

ec2_scaling_policy

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = [u'/Users/erbj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/erbj/views/git/nasben/aws/ansibleenv/lib/python2.7/site-packages/ansible
  executable location = /Users/erbj/views/git/nasben/aws/ansibleenv/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

macos
running virtualenv

##### SUMMARY

AWS supports autoscaling groups of EC2 instances that scale up and down according to  cpu utilization. The AWS CLI and boto3 support this:
http://boto3.readthedocs.io/en/latest/reference/services/autoscaling.html#AutoScaling.Client.put_scaling_policy
Here is an example of an aws cli-input-json file:
{
    "AutoScalingGroupName": "container-dtr-asg",
    "PolicyName": "ScaleGroupSize",
    "PolicyType": "TargetTrackingScaling",
    "Cooldown": 300,
    "EstimatedInstanceWarmup": 120,
    "TargetTrackingConfiguration": {
        "PredefinedMetricSpecification": {
            "PredefinedMetricType": "ASGAverageCPUUtilization"
        },
        "TargetValue": 60.0,
        "DisableScaleIn": false
    }
}
##### STEPS TO REPRODUCE

```yaml
    - name: Scaling Policy for the AutoScaling group
      ec2_scaling_policy:
        state: present
        policy_name: "ScaleGroupSize"
        asg_name: container-dtr-asg
        policy_type: TargetTrackingScaling
        target_tracking_scaling_policy_configuration: 
          TargetValue: 60.0
          PredefinedMetricSpecification:
            PredefinedMetricType: ASGAverageCPUUtilization
          DisableScaleIn: false
```

##### EXPECTED RESULTS

An auto-scaling policy would have been attached to the container-dtr-asg auto-scaling group previously created.
##### ACTUAL RESULTS

```

```
