### ISSUE TITLE
to_nice_yaml filter not work as expected

### ISSUE THREAD

**Issue by zacker330** [ansible/ansible#40367]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template or to_nice_yaml filter

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Dec 18 2016, 07:03:34) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION

DEFAULT_FILTER_PLUGIN_PATH(/Users/jack/.ansible.cfg) = [u'/usr/share/ansible_plugins/filter_plugins']

##### OS / ENVIRONMENT

N/A

##### SUMMARY

when to_nice_yaml filter a big number that begain with 0 like `020101805000086`, to_nice_yaml don't output a string, even though I use !!str front of `020101805000086`

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  gather_facts: no
  vars:
    other_number: "!!str 020101805000086"
    other_number1: !!str _020101805000086
    testvar:
      number: "020101805000086"
    testvar1:
      number: !!str "020101805000086"
    testvar2:
      number: !!str 020101805000086
    testvar3:
      number: "{{ other_number }}"
    testvar4:
      number: "{{ other_number1 }}"
    testvar5:
      number: "1020101805000086"
  tasks:
    - name: test
      template:
        src: test.yml
        dest: "./out/"

```

test.yml
```yaml
{{ testvar | to_nice_yaml }}
------ testva1
{{ testvar1 | to_nice_yaml }}
{{ testvar1.number }}
------ testva2
{{ testvar2 | to_nice_yaml }}
------ testva3
{{ testvar3 | to_nice_yaml }}

------ testva4
{{ testvar4 | to_nice_yaml }}

------ testva5
{{ testvar5 | to_nice_yaml }}
```

##### EXPECTED RESULTS

number: '020101805000086'

##### ACTUAL RESULTS

```
number: 020101805000086

------ testva1
number: 020101805000086

020101805000086

------ testva2
number: 020101805000086

------ testva3
number: '!!str 020101805000086'


------ testva4
number: _020101805000086

------ testva5
number: '1020101805000086'

```
