### ISSUE TITLE
Copy Operation Failing

### ISSUE THREAD

**Issue by gowthamnakulan** [ansible/ansible#40377]
##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

vmware_guest_file_operation

##### ANSIBLE VERSION

```
ansible 2.5.2
```

##### OS / ENVIRONMENT

Ubuntu

##### STEPS TO REPRODUCE

```yaml
- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1

  tasks:
   - vmware_guest_file_operation:
        hostname: (vsphere hostname)
        username: (vsphere username)
        password: (vsphere password)
        datacenter: (Data Centre)
        validate_certs: no
        vm_id: vRO_Software_Appliance
        vm_username: (VM Username)
        vm_password: (VM Password)
        copy:
           src: "/tmp/networkfile" (file which is available in my Ubuntu Machine)
           dest: "/opt/test1"  (Destination folder in my remote Machine)

		   
		   
```

##### EXPECTED RESULTS

File from my Local machine should have created at the remote destination folder.
##### ACTUAL RESULTS

TASK [vmware_guest_file_operation] 
**********************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "msg": "FileFault:The object /opt/test1 is not a file.", "uuid": "423c8e68-6928-fd98-8a89-2fa0584556eb"}
        to retry, use: --limit @/opt/work/ansible/playbooks/gowtham/filecopytovm.retry

```

```
