### ISSUE TITLE
module datadog_monitor needs dummy name even if id is set

### ISSUE THREAD

**Issue by mtgto** [ansible/ansible#40375]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

datadog_monitor

##### ANSIBLE VERSION

```
ansible 2.5.2
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### SUMMARY

Ansible 2.3 or later, module datadog_monitor has `id` parameter instead of `name`.

The document of datadog_monitor says:
```
The id of the alert. If set, will be used instead of the name to locate the alert.
```
http://docs.ansible.com/ansible/latest/modules/datadog_monitor_module.html

If `name` is not defined, causes an error.
So, I set empty string to `name`, it works fine.

I think It would be worked either `id` or `name` set.

##### STEPS TO REPRODUCE

1. Create the task using `datadog_monitor`.
2. Set `id` .
3. Unset `name`.

```yaml
- hosts: web
  tasks:
  - name: Mute the Datadog monitor
    datadog_monitor:
      id: 123456
      state: "mute"
      api_key: "{{ datadog_api_key or '' }}"
      app_key: "{{ datadog_app_key or '' }}"
    delegate_to: localhost
    run_once: yes
```

##### EXPECTED RESULTS

It works.

##### ACTUAL RESULTS

```
TASK [Mute the Datadog monitor] ****************************************************************************************************************************************************
fatal: [web01 -> localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: name"}
```

```
ansible-playbook datadog_mute_alert.yml --inventory inventories/production/hosts \
--extra-vars "datadog_api_key=***" \
--extra-vars "datadog_app_key=***"
```
