### ISSUE TITLE
convert a template to vm using vmware_guest

### ISSUE THREAD

**Issue by sayantandas** [ansible/ansible#40380]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

using the module from the commit https://raw.githubusercontent.com/balonik/ansible/a11787648c132cf4a4dbf53d076ad9021b0d34f3/lib/ansible/modules/cloud/vmware/vmware_guest.py

##### ANSIBLE VERSION

```
ansible --version
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

Ansible Server: Ubuntu 16.04.2
Template : Ubuntu 16.04.3

##### SUMMARY

I am trying to convert a VMware template into a VM (not clone). This is a feature available in VMware vshpere as shown in the screenshot below - 2nd option.

![image](https://user-images.githubusercontent.com/1985863/40219922-162346ba-5a95-11e8-9fef-61d3f565163b.png)

##### STEPS TO REPRODUCE

```
- name: convert template to vm
  vmware_guest:
    hostname: "{{ vcenter_hostname }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    validate_certs: no
    folder: "{{ vcenter_templates_folder }}"
    cluster: "{{ vcenter_cluster }}"
    datacenter: "{{ vcenter_datacenter }}"
    name: "{{ vm_template }}"
    state: "present"
    template: "{{ vm_template }}"
    is_template: no
  delegate_to: "localhost"
  register: convert_to_template

```

##### EXPECTED RESULTS

I expect the template to be converted into a VM
##### ACTUAL RESULTS

The template is not converted to VM. It just continues as if the VM is already present. output is below

```
Using module file /home/username/code/library/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: username
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/username/.ansible/tmp/ansible-tmp-1526625576.8-99117654190934 `" && echo ansible-tmp-1526625576.8-99117654190934="` echo /home/username/.ansible/tmp/ansible-tmp-1526625576.8-99117654190934 `" ) && sleep 0'
<localhost> PUT /tmp/tmpDww0pT TO /home/username/.ansible/tmp/ansible-tmp-1526625576.8-99117654190934/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/username/.ansible/tmp/ansible-tmp-1526625576.8-99117654190934/ /home/username/.ansible/tmp/ansible-tmp-1526625576.8-99117654190934/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/username/.ansible/tmp/ansible-tmp-1526625576.8-99117654190934/vmware_guest.py; rm -rf "/home/username/.ansible/tmp/ansible-tmp-1526625576.8-99117654190934/" > /dev/null 2>&1 && sleep 0'
ok: [ubuntu16.local.com -> localhost] => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cluster": "Cluster1",
            "customization": {},
            "customvalues": [],
            "datacenter": "NL-CDC01",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/Templates",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "vcenter.local.com",
            "is_template": false,
            "linked_clone": false,
            "name": “ubuntu16",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "template": "lsvtu05ub16",
            "username": “admin@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@sayantandas I am not sure which commit ID is being used for vmware_guest, so can't comment on version. 

I am able to convert template to vm using 

```yaml

---
- name: i40380
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  hosts: localhost
  tasks:
    - set_fact:
        vm_name: "VM_0001"
        datacenter: "DC2"

    - name: "Convert {{ vm_name }} to vm"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        state: present
        folder: "/{{datacenter}}/vm"
        name: "{{ vm_name }}"
        is_template: False
        resource_pool: Resources
```

Console - 
```
changed: [localhost] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsNotRunning",
        "guest_tools_version": "0",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "datastore2"
        ],
        "hw_esxi_host": "xx.xx.33.208",
        "hw_files": [
            "[datastore2] VM_0001/VM_0001.vmx",
            "[datastore2] VM_0001/VM_0001.vmsd",
            "[datastore2] VM_0001/VM_0001.vmdk",
            "[datastore2] VM_0001/VM_0001_1.vmdk",
            "[datastore2] VM_0001/VM_0001_2.vmdk",
            "[datastore2] VM_0001/VM_0001_3.vmdk"
        ],
        "hw_folder": "/DC2/vm",
        "hw_guest_full_name": null,
        "hw_guest_ha_state": null,
        "hw_guest_id": null,
        "hw_interfaces": [],
        "hw_is_template": false,
        "hw_memtotal_mb": 512,
        "hw_name": "VM_0001",
        "hw_power_status": "poweredOff",
        "hw_processor_count": 1,
        "hw_product_uuid": "422f7dc6-dec1-f141-9ae7-af48fd23e28c",
        "hw_version": "vmx-13",
        "instance_uuid": "502f7e4e-e2f1-5b98-39cd-ffd0480aacd4",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": null,
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "DC2",
            "disk": [],
            "esxi_hostname": null,
            "folder": "/DC2/vm",
            "force": false,
            "guest_id": null,
            "hardware": {},
            "hostname": "xx.xx.xx.31",
            "is_template": false,
            "linked_clone": false,
            "name": "VM_0001",
            "name_match": "first",
            "networks": [],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": "Resources",
            "snapshot_src": null,
            "state": "present",
            "state_change_timeout": 0,
            "template": null,
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "vapp_properties": [],
            "wait_for_ip_address": false
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=0
```

btw, I am using Ansible 2.5.2
