### ISSUE TITLE
fail to use "include_vars" for loop list

### ISSUE THREAD

**Issue by huiminzeng** [ansible/ansible#40395]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

loop
##### ANSIBLE VERSION

```
ansible version:  2.7.12
```

##### CONFIGURATION

Default configuration
##### OS / ENVIRONMENT

Ubuntu 16.04
##### SUMMARY

Hello everyone! I just want to make the size of the master playbook smaller. So i tired to use loop and import/include-related modules of ansible.  However, i couldn't get the loop part right.

If i put the loop list and the q module together in one file:
<img width="343" alt="5" src="https://user-images.githubusercontent.com/38716719/40235511-d536bdec-5aaa-11e8-8519-ebb1255dd92f.PNG">

everything works just fine. 
<img width="355" alt="1" src="https://user-images.githubusercontent.com/38716719/40235570-02a4b356-5aab-11e8-9c02-9e5216c5038c.PNG">

However, if i put the loop list into another file and then include_vars, like this:
test.yml (master file):
<img width="343" alt="3" src="https://user-images.githubusercontent.com/38716719/40235546-eabab204-5aaa-11e8-9863-0baedb89b9e2.PNG">
test2.yml (loop list):
<img width="256" alt="4" src="https://user-images.githubusercontent.com/38716719/40235562-f6bf3aa2-5aaa-11e8-9891-d0b436802180.PNG">

And then error occurred. 
<img width="542" alt="2" src="https://user-images.githubusercontent.com/38716719/40235582-0c88021a-5aab-11e8-8a91-352a0781f335.PNG">

I don't know why. 
Moreover, i have tried other methods, such as import_playbook or vars_files. They didn't work.
Do you have any suggestions for me? 
thx!
##### STEPS TO REPRODUCE

```yaml
---
- name: system construction
  hosts: local
  connection: local
  vars:
    aloop:
      alice:
         name: Alice Appleworth
         telephone: 123-456-7890
      bob:
         name: Bob Bananarama
         telephone: 987-654-3210
  tasks:     
  - name: Print phone records
    debug:
      msg: "User {{ item.key }} is {{ item.value.name }} ({{ item.value.telephone }})"
    loop: "{{ q('dict', aloop) }}"

```

##### EXPECTED RESULTS

<img width="355" alt="1" src="https://user-images.githubusercontent.com/38716719/40235417-7dc2a8fa-5aaa-11e8-8fd7-0be70463e3f7.PNG">

##### ACTUAL RESULTS

<img width="542" alt="2" src="https://user-images.githubusercontent.com/38716719/40235398-6d8c595e-5aaa-11e8-9b7f-f7d5093975ef.PNG">

```

```
