### ISSUE TITLE
Error while running custom module

### ISSUE THREAD

**Issue by anis016** [ansible/ansible#40394]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.6.0 (devel 03194880c1) last updated 2018/05/11 16:32:18 (GMT +200)
  config file = None
  configured module search path = [u'/home/sayed/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sayed/Python_Workspace/ansible/ansible-dev/lib/ansible
  executable location = /home/sayed/Python_Workspace/ansible/ansible-dev/bin/ansible
  python version = 2.6.9 (default, Mar  6 2016, 02:31:36) [GCC 5.3.1 20160225]
```

##### CONFIGURATION

* results of "ansible-config dump --only-changed" outputs nothing
* no configurations/settings added.

##### OS / ENVIRONMENT

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.2 LTS
Release:        16.04
Codename:       xenial

##### SUMMARY

I am working on a module that can list all the files in the hdfs path. I tested it and it works fine.
module file: https://gist.github.com/anis016/bc09e340ae5c93bb1a70d3f37cbd4ace

However, I always get this below module_stderror along with the listed hdfs files

"module_stderr": "Shared connection to 127.0.0.1 closed.\r\n",
"module_stdout": "[u'HADAT-EXLIMI-GR1-201607-19', u'dqjob', u'hbase-sayed', u'kernel_cleaner.sh']

##### STEPS TO REPRODUCE

run the playbook as below:

```
ansible-playbook -i src/inventory src/play.yml --user=sayed --extra-vars "ansible_sudo_pass=XXXXX"
```

```yaml
-
  name: hdfs playbook
  hosts: ubuntu_hosts

  # create tasks
  tasks:
    # Install hdfs python library
    - name: Install hdfs python HDFS client
      become: yes
      pip:
        name: hdfs
        state: latest

    - name: hdfs list directory
      hdfs_ansible:
        webhdfs_host: http://127.0.0.1
        webhdfs_port: 50070
        effective_user: sayed
        hdfsPath: /tmp/
        recurse: False
        command: ls
      register: result

    - debug: msg=result.stdout_lines
```

##### EXPECTED RESULTS

It should properly run without any "module_stdedrr"

##### ACTUAL RESULTS

```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "module_stderr": "OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug2: mux_client_hello_exchange: master version 4\r\ndebug3: mux_client_forwards: request forwardings: 0 local, 0 remote\r\ndebug3: mux_client_request_session: entering\r\ndebug3: mux_client_request_alive: entering\r\ndebug3: mux_client_request_alive: done pid = 26544\r\ndebug3: mux_client_request_session: session request sent\r\ndebug1: mux_client_request_session: master session id: 2\r\ndebug3: mux_client_read_packet: read header failed: Broken pipe\r\ndebug2: Received exit status from master 0\r\nShared connection to 127.0.0.1 closed.\r\n", 
    "module_stdout": "[u'HADAT-EXLIMI-GR1-201607-19', u'dqjob', u'hbase-sayed', u'kernel_cleaner.sh']\r\n", 
    "msg": "MODULE FAILURE", 
    "rc": 0
}
```
Please check the gist for more with "-vvvv"

https://gist.github.com/anis016/eb43ba7b5e23a10a4175010274f30590

```

```
