### ISSUE TITLE
Add support for f2fs to filesystems

### ISSUE THREAD

**Issue by bwlang** [ansible/ansible#40418]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

filesystem

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/langhorst/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

no output

##### OS / ENVIRONMENT

linux

##### SUMMARY

cannot make an f2fs filesystem from ansible
```
failed: [seq-flash] (item={u'name': u'md0', u'level': 0, u'devices': [u'/dev/nvme0n1p5', u'/dev/nvme1n1p1'], u'state': u'present', u'filesystem': u'f2fs', u'mountpoint': u'/seq_data'}) => {"changed": false, "item": {"devices": ["/dev/nvme0n1p5", "/dev/nvme1n1p1"], "filesystem": "f2fs", "level": 0, "mountpoint": "/seq_data", "name": "md0", "state": "present"}, "msg": "value of fstype must be one of: ext4, ext3, ext2, btrfs, vfat, ext4dev, reiserfs, lvm, xfs, got: f2fs"}
```
##### STEPS TO REPRODUCE

```yaml
  - include_role:
      name: mrlesmithjr.mdadm
    vars:
      mdadm_arrays:
       - name: md0
         devices: [/dev/nvme0n1p5, /dev/nvme1n1p1]
         filesystem: f2fs
         level: 0
         mountpoint: /seq_data
         state: present
```
