### ISSUE TITLE
glusterfs_module doesn't modify options

### ISSUE THREAD

**Issue by nerzhul** [ansible/ansible#40410]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

glusterfs_volume module

##### ANSIBLE VERSION

```
2.5.3.0
```

##### CONFIGURATION

not relevant

##### OS / ENVIRONMENT

Archlinux testing (up to date)

##### SUMMARY

glusterfs_volume module is not idempotent when modifying volume options. They are not changed after creation. It seems it doesn't work at creation too.

Here is the output if i change an option
```
ok: [scw-aaaaaa] => (item={'name': 'rabbitmq-main', 'bricks': ['/bricks/1/rabbitmq-main', '/bricks/2/rabbitmq-main'], 'options': {'performance.cache-size': '32MB'}, 'force': True}) (0.451731s)
```

Note: the following command works correctly:
```
glusterfs volume set rabbitmq-main performance.cache-size 32MB
```

##### STEPS TO REPRODUCE

Create a gluster fs volume

```yaml
- name: "Create gluster volumes"
  gluster_volume:
    state: "{{ item.state | default('present') }}"
    name: "{{ item.name }}"
    bricks: "{{ item.bricks | join(',') }}"
    rebalance: "{{ item.rebalance | default(True) }}"
    cluster: "{{ item.gluster_nodes | default(glusterfs_nodes) }}"
    quota: "{{ item.quota | default(omit) }}"
    force: "{{ item.force | default(False) }}"
    replicas: "{{ item.replicas | default(glusterfs_default_replicas) }}"
    arbiters: "{{ item.arbiters | default(glusterfs_default_arbiters) }}"
  vars:
    glusterfs_default_replicas: 3
    glusterfs_default_arbiters: 1
    glusterfs_nodes: [hidden1, hidden2, hidden3]
  with_items:
    - name: "rabbitmq-main"
      bricks:
        - '/bricks/1/rabbitmq-main'
        - '/bricks/2/rabbitmq-main'
      options:
        performance.cache-size: 32MB
      force: yes
  run_once: true
```

##### EXPECTED RESULTS

Options must be changed on the volume. Expected output is (glusterfs volume info [volumename])

```
Options Reconfigured:
performance.cache-size: 32MB
transport.address-family: inet
performance.readdir-ahead: on
nfs.disable: on
```

##### ACTUAL RESULTS

Here is the volume output after execution
```
Options Reconfigured:
transport.address-family: inet
performance.readdir-ahead: on
nfs.disable: on

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/gluster_volume.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/gluster_volume.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @rosmo
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by nerzhul** [comment]
!component lib/ansible/modules/system/gluster_volume.py

**Comment by Akasurde** [comment]
similar to https://github.com/ansible/ansible/issues/40438

**Comment by sac** [comment]
@nerzhul setting the options works while creating the volume. Your playbook does not include the `options: "{{ item.options }}" ' 

The below playbook worked just fine for me:

```   
    - name: "Create gluster volumes"
      gluster_volume:
        state: "{{ item.state | default('present') }}"
        name: "{{ item.name }}"
        bricks: "{{ item.bricks | join(',') }}"
        rebalance: "{{ item.rebalance | default(True) }}"
        cluster: "{{ item.gluster_nodes | default(glusterfs_nodes) }}"
        quota: "{{ item.quota | default(omit) }}"
        force: "{{ item.force | default(False) }}"
        replicas: "{{ item.replicas | default(glusterfs_default_replicas) }}"
        arbiters: "{{ item.arbiters | default(glusterfs_default_arbiters) }}"
        options: "{{ item.options }}"                       # <==== Include this line
      vars:
        glusterfs_default_replicas: 3
        glusterfs_default_arbiters: 1
        glusterfs_nodes: ['server1', 'server2', 'server3']
      with_items:
      - name: "rabbitmq-main"
        bricks:
          - '/bricks/1/rabbitmq-main'
          - '/bricks/2/rabbitmq-main'
        options:
          performance.cache-size: 32MB
        force: yes
      run_once: true

```
