### ISSUE TITLE
1&1 Server - Server creation fails

### ISSUE THREAD

**Issue by mbuiro** [ansible/ansible#40425]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

oneandone_server.py

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /etc/ansible/roles/Development/graylog/dev-graylog/ansible.cfg
  configured module search path = [u'/home/mezebuiro/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May  9 2018, 11:18:37) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
```

##### CONFIGURATION

```
DEFAULT_ROLES_PATH(/etc/ansible/roles/Development/graylog/dev-graylog/ansible.cfg) = [u'/etc/ansible/roles/Development/graylog/dev-graylog/.imported_roles', u'/etc/ansible/roles/Development/graylog/dev-graylog/roles']
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/roles/Development/graylog/dev-graylog/ansible.cfg) = /etc/ansible/roles/Development/graylog/dev-graylog/secret.txt
RETRY_FILES_ENABLED(/etc/ansible/roles/Development/graylog/dev-graylog/ansible.cfg) = False
```
##### OS / ENVIRONMENT

Control Machine:
```
Linux workstation001 4.16.7-200.fc27.x86_64 #1 SMP Wed May 2 20:33:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
##### SUMMARY

Unable to create server using oneandone_server module due to python error:
```
The full traceback is:
  File "/tmp/ansible_vJT7Oi/ansible_module_oneandone_server.py", line 709, in main
    (changed, servers) = create_server(module, oneandone_conn)
  File "/tmp/ansible_vJT7Oi/ansible_module_oneandone_server.py", line 426, in create_server
    descriptions = _auto_increment_description(count, description)
  File "/tmp/ansible_vJT7Oi/ansible_module_oneandone_server.py", line 616, in _auto_increment_description
    if '%' in description:

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "api_url": null,
            "appliance": "753E3C1F859874AA74EB63B3302601F5",
            "auth_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "auto_increment": true,
            "cores_per_processor": null,
            "count": 1,
            "datacenter": "US",
            "description": null,
            "firewall_policy": "Linux_Logging",
            "fixed_instance_size": "XL",
            "hdds": null,
            "hostname": "logging.testing.com",
            "load_balancer": null,
            "monitoring_policy": null,
            "private_network": null,
            "ram": null,
            "server": null,
            "server_type": "cloud",
            "ssh_key": null,
            "state": "present",
            "vcore": null,
            "wait": true,
            "wait_interval": 5,
            "wait_timeout": 600
        }
    },
    "msg": "argument of type 'NoneType' is not iterable"
}
```
##### STEPS TO REPRODUCE

Run below playbook using ```ansible-playbook test.yml```
```
-
  name: test
  hosts: localhost
  vars:
    - client_auth_token: "supersekret"
    - client_firewall_name: "ansible-test"
    - client_hostname_fqdn: "logging.testing.com"
    - client_datacenter: "US"
    - client_instance_size: "XL"
    - client_appliance_id: "753E3C1F859874AA74EB63B3302601F5"
  tasks:
    - name: Server should be created
      oneandone_server:
        auth_token: "{{ client_auth_token }}"
        hostname: "{{ client_hostname_fqdn }}"
        firewall_policy: "{{ client_firewall_name }}"
        datacenter: "{{ client_datacenter }}"
        fixed_instance_size: "{{ client_instance_size }}"
        appliance: "{{ client_appliance_id }}"
        state: present
```

##### EXPECTED RESULTS

```
TASK [oneandone : Server should be created] PLAY [localhost] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [oneandone : Server should be created] ******************************************************************************************************************************************************************************************
changed: [localhost]

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
PLAY [localhost] *********************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [oneandone : Server should be created] ******************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "argument of type 'NoneType' is not iterable"}

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
