### ISSUE TITLE
gluster_volume: volume options are not working

### ISSUE THREAD

**Issue by sac** [ansible/ansible#40438]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
gluter_volume

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/sac/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May  9 2018, 11:18:37) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### CONFIGURATION

[sac@dhcp35-44 roles]$ ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/home/sac/work']

##### OS / ENVIRONMENT
GNU/Linux (any distribution)

##### SUMMARY

On an existing GlusterFS volume we try to set the volume options the volume set fails with usage command. 

Referred the example at: http://docs.ansible.com/ansible/latest/modules/gluster_volume_module.html
```
- name: tune
  gluster_volume:
    state: present
    name: test1
    options:
      performance.cache-size: 256MB
```

##### STEPS TO REPRODUCE

```yaml
tasks:
  - name: Set the option
    gluster_volume:
        state: present
        name: foo
        options:
                performance.readdir-ahead: off
```
If the above above yaml is used with state as present the playbook fails with usage command. 

##### EXPECTED RESULTS

The volume options should be set.

##### ACTUAL RESULTS

```
[sac@dhcp35-44 ~]$ ansible-playbook -i /tmp/inv /tmp/vol_set.yml 

PLAY [Set nfs.ganesha on] ***************************************************************************************************

TASK [Set the option] *******************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: None
fatal: [10.70.42.25]: FAILED! => {"changed": false, "msg": "error running gluster (/usr/sbin/gluster --mode=script volume add-brick samba dhcp42-25.lab.eng.blr.redhat.com:None) command (rc=1): Wrong brick type: dhcp42-25.lab.eng.blr.redhat.com:None, use <HOSTNAME>:<export-dir-abs-path>\nUsage: volume add-brick <VOLNAME> [<stripe|replica> <COUNT> [arbiter <COUNT>]] <NEW-BRICK> ... [force]\n"}
        to retry, use: --limit @/tmp/vol_set.retry

PLAY RECAP ******************************************************************************************************************
10.70.42.25                : ok=0    changed=0    unreachable=0    failed=1   

```

It should not try to add brick, <hostname>:export-dir is parsed when add-brick or create is tried.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/gluster_volume.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/gluster_volume.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @rosmo
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gothicx** [comment]
Hi,

Have you tried to put a dash in the option ?

```
tasks:
  - name: Set the option
    gluster_volume:
        state: present
        name: foo
        options:
              - performance.readdir-ahead: off
```
