### ISSUE TITLE
edgeos_config command diff only considers router's active config

### ISSUE THREAD

**Issue by F1rst-Unicorn** [ansible/ansible#40437]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

edgeos_config

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/jan/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]

```

##### CONFIGURATION

```
CACHE_PLUGIN(/home/jan/Programme/Ansible/Schumacherweg/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/jan/Programme/Ansible/Schumacherweg/ansible.cfg) = cache
CACHE_PLUGIN_TIMEOUT(/home/jan/Programme/Ansible/Schumacherweg/ansible.cfg) = 86400
DEFAULT_GATHERING(/home/jan/Programme/Ansible/Schumacherweg/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/jan/Programme/Ansible/Schumacherweg/ansible.cfg) = ['/home/jan/P>
DEFAULT_VAULT_PASSWORD_FILE(/home/jan/Programme/Ansible/Schumacherweg/ansible.cfg) = /ho>
RETRY_FILES_ENABLED(/home/jan/Programme/Ansible/Schumacherweg/ansible.cfg) = False
```

##### OS / ENVIRONMENT

Running on Arch Linux, managing EdgeOS v1.10.1 router 

##### SUMMARY

When comparing the active config with the desired commands, effects of previously scheduled desired commands is not taken into account.

##### STEPS TO REPRODUCE

Make sure no dhcp-server is present. 
Create a command chain to set up some config, starting from a clean state. Example set-style config:

```yaml
delete service dhcp-server
set service dhcp-server shared-network-name test
# ... possibly more instructions
```
Roll out with
```yaml
- edgeos_config:
    src: config-set.j2
```
Then roll out the playbook for a second time. 

##### EXPECTED RESULTS

When rolling out the playbook for the second time, no changes are applied to the system and no services are restarted. 

##### ACTUAL RESULTS

When rolling out for the second time, only the `delete` command is executed, leaving the router without any configured dhcp-server. 

-vvv output of the first run:
```yaml
changed: [ubnt01] => {
    "backup_path": "/home/jan/Programme/Ansible/Schumacherweg/roles/edgeos_dhcp_server/backup/ubnt01_config.2018-05-19@15:34:58",                                                 
    "changed": true,
    "commands": [
        "set service dhcp-server shared-network-name test"                                               
    ],
    "filtered": [],
    "invocation": {
        "module_args": {
            "backup": false,
            "comment": "configured by edgeos_config",
            "config": null,
            "lines": null,
            "match": "line",
            "save": false,
            "src": "delete service dhcp-server\nset service dhcp-server shared-network-name test"
        }
    }
}

```

-vvv output of the second run: 
```yaml
changed: [ubnt01] => {
    "backup_path": "/home/jan/Programme/Ansible/Schumacherweg/roles/edgeos_dhcp_server/backup/ubnt01_config.2018-05-19@15:34:09",                                                 
    "changed": true,
    "commands": [
        "delete service dhcp-server"
    ],
    "filtered": [],
    "invocation": {
        "module_args": {
            "backup": false,
            "comment": "configured by edgeos_config",
            "config": null,
            "lines": null,
            "match": "line",
            "save": false,
            "src": "delete service dhcp-server\nset service dhcp-server shared-network-name test"                        
        }
    }
}
```
