### ISSUE TITLE
Module archive: Add "create" parameter that creates destpath if not exists.

### ISSUE THREAD

**Issue by filicivi** [ansible/ansible#40440]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
* archive [module]

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /Users/joeyrs/.ansible.cfg
  configured module search path = [u'/Users/joeyrs/.ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Apr 25 2018, 15:22:05) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION

ANSIBLE_NOCOWS(/Users/joeyrs/.ansible.cfg) = True
DEFAULT_LOG_PATH(/Users/joeyrs/.ansible.cfg) = /Users/joeyrs/.ansible/ansible.log
DEPRECATION_WARNINGS(/Users/joeyrs/.ansible.cfg) = True
DISPLAY_SKIPPED_HOSTS(/Users/joeyrs/.ansible.cfg) = True
ERROR_ON_MISSING_HANDLER(/Users/joeyrs/.ansible.cfg) = True
HOST_KEY_CHECKING(/Users/joeyrs/.ansible.cfg) = True
RETRY_FILES_ENABLED(/Users/joeyrs/.ansible.cfg) = False

##### OS / ENVIRONMENT

N/A
##### SUMMARY

If the destination path not exists, the module exit with an exception.
Might be useful if the archive module had a boolean "createdest" parameter that creates the destination path if not exists.

##### STEPS TO REPRODUCE

```yaml
---
- name: "Testing Archive Module"
  hosts: localhost
  become: no
  gather_facts: no
  force_handlers: no
  ignore_errors: no
  
  tasks:
    - archive:
        path: "/Users/joeyrs/Documents"
        dest: "/Users/joeyrs/non_existing_dir/documents.tgz"
...
```

##### EXPECTED RESULTS

Task completed successfully when "createdest: yes" parameter is specified.

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 2] No such file or directory: '/Users/joeyrs/non_existing_dir/documents.tgz'
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error when writing tar.gz archive at /Users/joeyrs/non_existing_dir/documents.tgz: [Errno 2] No such file or directory: '/Users/joeyrs/non_existing_dir/documents.tgz'"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/archive.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/archive.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @bendoh
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gothicx** [comment]
Hi,

This kind of features will require the user, group and modes to be defined in the module in order to achieve the correct result.

You may need to check if the directory exists first with the module stat.

```
tasks:
 - name: Ansible check if archive folder exists
   stat:
     path: '/Users/joeyrs/non_existing_dir'
   register: archive_folder

 - name: Do archive if folder exists
   archive:
     path: '/Users/joeyrs/Documents'
     dest: '/Users/joeyrs/non_existing_dir/documents.tgz'
   when: archive_folder.stat.exists
```
