### ISSUE TITLE
Arista eos_config interface configuration (through file) indentation issue

### ISSUE THREAD

**Issue by sk1988** [ansible/ansible#40472]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
eos_config

##### ANSIBLE VERSION
ansible 2.4.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

##### CONFIGURATION
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 10
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/inventory']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/etc/ansible/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 30

##### OS / ENVIRONMENT
Running this from Centos 7.3.1611
Trying to control Arista switch running software version 4.19.5M

##### SUMMARY
Interface configuration for the Arista switch is being pushed to the device, but tries to do again on subsequent tries.

##### STEPS TO REPRODUCE

Configuration I am trying to push to device, the below config is in a file and being referenced in playbook which is also provided below:

interface Ethernet15/1
   switchport trunk allowed vlan 10
   switchport mode trunk
   priority-flow-control mode on
   priority-flow-control priority 3 no-drop
   !
   tx-queue 1
      no priority
      bandwidth percent 40
   !
   tx-queue 3
      no priority
      bandwidth percent 40
   spanning-tree portfast
!

```
      - name: Deploy from auto generated file
        delegate_to: localhost
        eos_config:
           src: "./CONFIGS/{{ inventory_hostname }}.cfg"
           provider: "{{ provider }}"
           host: "{{ inventory_hostname }}"
           diff_against: running
           save_when: modified
        tags: deploy-eosconfig

```

Ansible is trying to push the below section of configuration even though it has successfully pushed it to the device already.

**tx-queue 1
      no priority
      bandwidth percent 40
   !
   tx-queue 3
      no priority
      bandwidth percent 40**

##### EXPECTED RESULTS
Ansible should push the interface configuration on the first run and the idempotency nature of Ansible should avoid making changes on subsequent tries.

##### ACTUAL RESULTS
Only pasting the section of output which is showing error behavior:

```
changed: [qa-001.mgmt -> localhost] => {
    "changed": true,
    "commands": [
        "interface Ethernet15/1",
        "tx-queue 1",
        "no priority",
        "bandwidth percent 40",
        "tx-queue 3",
        "no priority",
        "bandwidth percent 40",
```
