### ISSUE TITLE
lxd_container : cannot specify LXD cluster host on which a container is created

### ISSUE THREAD

**Issue by AlexandreGohier** [ansible/ansible#40479]
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

lxd_container

##### ANSIBLE VERSION

```

> ansible 2.5.3
>   config file = /etc/ansible/ansible.cfg
>   configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
>   ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
>   executable location = /usr/local/bin/ansible
>   python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]

```

##### CONFIGURATION

CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = /opt/scripts/ansible
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 86400
DEFAULT_GATHERING(/etc/ansible/ansible.cfg) = smart

##### OS / ENVIRONMENT

"N/A" for OS, LXD v3.0

##### SUMMARY

Module lxd_container doesn't allow to specify a target host when creating a container on a LXD cluster. If, for instance, the LXD cluster is intended to span multiple AZ, it's important to be able to create a given container on a given cluster host.

##### STEPS TO REPRODUCE

```
- hosts: localhost
  tasks:
  - name: Create LXD Containers
    connection: local
    become: false
    lxd_container:
      name: container1
      state: stopped
      source:
        type: image
        mode: pull
        server: https://cloud-images.ubuntu.com/releases
        protocol: simplestreams
        alias: 18.04/amd64
      profiles: ['default']
```

##### EXPECTED RESULTS

Control the LXD cluster host on which the container is created

##### ACTUAL RESULTS

The container is created on the cluster host with the least amount of existing containers

```
The container is created on the cluster host with the least amount of existing containers

```
