### ISSUE TITLE
Unable to enable replication,provisioning while creating vmk on ESXI host

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#40529]
##### SUMMARY

At present vmware_vmkernel module cant enable replication, provisioning services while creating vmk. These services can be enabled when creating vmk through ESXI UI

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

```
vmware_vmkernel
```
##### ANSIBLE VERSION

```
2.5
```

##### STEPS TO REPRODUCE

```yaml
-  name: Add Management vmkernel port using static network type
   vmware_vmkernel:
      hostname: 192.168.127.9
      username: admin
      password: supersecret123
      vswitch_name: vSwitch0
      portgroup_name: PG_0001
      vlan_id: vlan_id
      network:
        type: 'static'
        ip_address: 192.168.127.10
        subnet_mask: 255.255.255.0
      state: present
      enable_mgmt: True
      ****enable_replication: True****  ->> this is missing
     ****enable_provisioning: True****  ->> this is missing
```
