### ISSUE TITLE
group_by lumping all hosts into one group

### ISSUE THREAD

**Issue by jsmartin** [ansible/ansible#4055]
For some reason group_by isn't working properly.  All of my hosts are getting thrown into the same group.  This does not happen with 1.2.3.  This does happen with 1.3 (devel b65cefe893) .

playbook

```
- hosts: riak_cluster
  sudo: True
  tasks:
  - name: Create a group based on riak node type.
    group_by: key={{ node_type }}

- hosts: localhost
  connection: local
  tasks:
  - name: debug shit
    template: src=/tmp/in dest=/tmp/out
```

hosts file

```
[localhost]
127.0.0.1

[riak_cluster]
10.42.0.6 node_type=primary
10.42.0.7 node_type=middle
10.42.0.8 node_type=last
```

output

```
PLAY [riak_cluster] *********************************************************** 

GATHERING FACTS *************************************************************** 
ok: [10.42.0.8]
ok: [10.42.0.6]
ok: [10.42.0.7]

TASK: [Create a group based on riak node type.] ******************************* 
changed: [10.42.0.6] => {"changed": true, "groups": {"primary": ["10.42.0.6", "10.42.0.7", "10.42.0.8"]}}
```

dump of groups to json in a template:

```
cat /tmp/out 
{"all": ["10.42.0.8", "10.42.0.6", "127.0.0.1", "10.42.0.7"], "riak_cluster": ["10.42.0.8", "10.42.0.6", "10.42.0.7"], "primary": ["10.42.0.8", "10.42.0.6", "10.42.0.7"], "riak_servers": ["10.42.0.8", "10.42.0.6", "10.42.0.7"], "ungrouped": [], "localhost": ["127.0.0.1"]}
```
