### ISSUE TITLE
vmware_guest disconnect NICs when cloning from template (ref #38143)

### ISSUE THREAD

**Issue by Straevaras** [ansible/ansible#40564]
##### SUMMARY

When creating a new VM clone from an existing template with Ansible 2.5, the virtual NICs are not connected in VM configuration and the VM will not be able to obtain any network connection when creating clones.  This issue was previously reported in #38143 but the ticket opener self-closed the ticket.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible-2.5.2
ansible-2.5.3
```
This issue is NOT present in ansible-2.4.4.0.

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/home/<user>/ansible/ansible.cfg) = ['profile_tasks', 'timer']
HOST_KEY_CHECKING(/home/<user>/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

CentOS 7, kernel 3.10.0-693.17.1.el7.x86_64 (running ansible)
VMWare ESXi 6.5.0 - Build number 5969303
VMWare vCenter 6.5.0 - Build number 7515524

##### STEPS TO REPRODUCE

These steps assume you have an ESXi system managed by a vCenter.  Deploying a VM from a Template via API (ansible in this case) requires a certain license on the ESXi server.  This assumes that the datastore on the ESX server is named "RAID1" and the vCenter Datacenter is named "Devel".

1. Create a CentOS 7 VM named "CentOS - Vanilla" in vCenter using a CentOS 7 Minimal-1804 ISO, all default options.
2. Ensure the VM has a single NIC with the "VM Network" port group (create port group and vSwitch if needed).
3. Install VMWare tools (`yum install open-vm-tools`) and confirm ESXi sees it running.  Reboot if necessary.
4. Power off VM and convert the VM to a Template in vCenter.
5. Create the following files and run `ansible-playbook -i localhost, bug.yml`

```yaml
# bug_vms.yml
vms:
- name: Test VM
  annotation: Test VM
  hostname: centos-test
  type: test
  cpu: 2
  ram: 4
  disks:
    - size_gb: 30
      type: thick
      datastore: "RAID1"
  networks:
    - name: VM Network
```

```yaml
# bug.yml - Main playbook
---
- hosts: localhost
  gather_facts: no
  vars_files:
    - vars/bug_vms.yml
  vars:
    - vcenter_hostname: <vcenter hostname/ip>
    - vcenter_username: <vcenter username>
    - vcenter_password: <vcenter password>
    - vcenter_datacenter: <vcenter datacenter>
    - esx_hostname: <esx ip>
  tasks:
    - name: Create a VM from a template
      vmware_guest:
        hostname: "{{vcenter_hostname}}"
        username: "{{vcenter_username}}"
        password: "{{vcenter_password}}"
        datacenter: "{{vcenter_datacenter}}"
        validate_certs: no
        folder: /{{vcenter_datacenter}}/vm
        esxi_hostname: "{{esx_hostname}}"
        name: "{{ item.name }}"
        state: poweredon
        template: "CentOS - Vanilla"
        annotation: "{{item.annotation}}"
        wait_for_ip_address: yes
        disk: "{{item.disks}}"
        hardware:
          memory_mb: "{{(item.ram * 1024)|int}}"
          num_cpus: "{{item.cpu}}"
        networks: "{{item.networks}}"
      delegate_to: localhost
      with_items: "{{ vms }}"
      async: 7200
      poll: 0
      register: new_vms
      
    - debug:
        var: new_vms

    - name: wait for vms
      async_status: jid={{ item.ansible_job_id }}
      delegate_to: localhost
      register: jobs
      until: jobs.finished
      retries: 300
      with_items: "{{ new_vms.results }}"
```

##### EXPECTED RESULTS

I expected the VM to acquire a DHCP address from our DHCP server and the ansible script to complete.

##### ACTUAL RESULTS

The ansible script does not complete as it is waiting for the VM to come up, but can't determine that it has since the VM acquires no network address.  Additionally, when right-clicking on the VM and Editing the Settings, the `Connected` checkboxes for the NICs are all unchecked.
