### ISSUE TITLE
VyOS and EdgeOS modules stack trace during execution

### ISSUE THREAD

**Issue by samdoran** [ansible/ansible#40566]
##### SUMMARY
When trying to run `vyos_facts`, `edgeos_facts` as well as other modules for those operation systems, Ansible shows a stack trace.

Bisected to 483df136266c6e7600e7f02ee718a8b1be803461 as the first failing commit.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`vyos_facts`
`vyos_command`
`edgeos_facts`
`edgeos_command`
`edgeos_config`

##### ANSIBLE VERSION

```
ansible 2.6.0dev0 (devel 7145dd05b6) last updated 2018/05/22 17:01:10 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = [u'/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 05:51:27) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

##### CONFIGURATION

```
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /Users/sdoran/.ansible/ansible.log
DEFAULT_MODULE_PATH(env: ANSIBLE_LIBRARY) = ['/Users/sdoran/Source/ansible/library']
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/Users/sdoran/Projects', '/Users/sdoran/Projects/Vagrant/Ansible Lab/roles', '/Users/sdoran/Projects/Ansible/roles']
DEFAULT_STDOUT_CALLBACK(env: ANSIBLE_STDOUT_CALLBACK) = debug
```

##### OS / ENVIRONMENT
```
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202

```
##### STEPS TO REPRODUCE
Run the following playbook:

```yaml
- name: VyOS stuff
  hosts: vyos
  gather_facts: no
  become: no
  connection: network_cli

  tasks:
    - vyos_facts:
```

##### EXPECTED RESULTS
Facts will be gathered on the device

##### ACTUAL RESULTS

Ansible fails to connect and shows a stack trace.

```
> ansible-playbook vyos.yml -i inventory/hosts.yml -vvv
ansible-playbook 2.6.0dev0 (devel 7145dd05b6) last updated 2018/05/22 17:01:10 (GMT -400)
  config file = None
  configured module search path = ['/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible-playbook
  python version = 3.6.4 (default, Mar 19 2018, 12:20:18) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
No config file found; using defaults
Parsed /Users/sdoran/Projects/Vagrant/Ansible Lab/inventory/hosts.yml inventory source with yaml plugin

PLAYBOOK: vyos.yml ***************************************************************************************
1 plays in vyos.yml

PLAY [VyOS stuff] ****************************************************************************************
META: ran handlers

TASK [vyos_facts] ****************************************************************************************
task path: /Users/sdoran/Projects/Vagrant/Ansible Lab/vyos.yml:8
The full traceback is:
Traceback (most recent call last):
  File "/Users/sdoran/Source/ansible/lib/ansible/executor/task_executor.py", line 138, in run
    res = self._execute()
  File "/Users/sdoran/Source/ansible/lib/ansible/executor/task_executor.py", line 517, in _execute
    self._connection = self._get_connection(variables=variables, templar=templar)
  File "/Users/sdoran/Source/ansible/lib/ansible/executor/task_executor.py", line 818, in _get_connection
    socket_path = self._start_connection(filtered_vars)
  File "/Users/sdoran/Source/ansible/lib/ansible/executor/task_executor.py", line 927, in _start_connection
    stdin.write(b'\n#END_VARS#\n')
OSError: [Errno 5] Input/output error

fatal: [r1]: FAILED! => {}

MSG:

Unexpected failure during module execution.

	to retry, use: --limit @/Users/sdoran/Projects/Vagrant/Ansible Lab/vyos.retry

PLAY RECAP ***********************************************************************************************
r1                         : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/edgeos/edgeos_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/edgeos/edgeos_command.py)
* [lib/ansible/modules/network/edgeos/edgeos_config.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/edgeos/edgeos_config.py)
* [lib/ansible/modules/network/edgeos/edgeos_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/edgeos/edgeos_facts.py)
* [lib/ansible/modules/network/vyos/vyos_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/vyos/vyos_command.py)
* [lib/ansible/modules/network/vyos/vyos_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/vyos/vyos_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @BeardyMcBeards @Qalthos @qalthos
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
Here are the host_vars:

```
vyos:
  hosts:
    r1:
      ansible_host: 192.168.1.30
      ansible_ssh_user: vagrant
      ansible_password: vagrant
      ansible_ssh_port: 22
      ansible_network_os: vyos

edgeos:
  hosts:
    router.acme.com:
      ansible_python_interpreter: /usr/bin/env python
      ansible_user: ansible
      ansible_network_os: edgeos
      ansible_password: not-the-real-password
```

**Comment by Qalthos** [comment]
When you get a chance, can you retest with #43885?

**Comment by samdoran** [comment]
Sure thing!

**Comment by samdoran** [comment]
I tested with f2211058826944a4e8e9e9b678d26615a29977b3 and the playbook run hangs indefinitely now. Also, I do not see any connection opened to the router.

```
> ansible --version
ansible 2.7.0.dev0 (detached HEAD 77bff99f3c) last updated 2018/08/13 17:04:10 (GMT -400)
  config file = /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg
  configured module search path = ['/Users/sdoran/Source/ansible/library']
  ansible python module location = /Users/sdoran/Source/ansible/lib/ansible
  executable location = /Users/sdoran/Source/ansible/bin/ansible
  python version = 3.7.0 (default, Jun 28 2018, 11:03:27) [Clang 9.1.0 (clang-902.0.39.2)]
```

Test playbook:

```yaml
- name: VyOS stuff
  hosts: vyos
  gather_facts: no
  become: no
  connection: network_cli

  tasks:
    - vyos_facts:

    - debug:
        var: ansible_facts

    - vyos_command:
        commands:
          - show date
          - show interfaces
          - show hardware cpu
      register: output

    - debug:
        var: output.stdout_lines

    - vyos_config:
        lines:
          - delete service snmp
          - set service snmp community TEST authorization ro
```

```
> ansible-playbook vyos.yml
...
TASK [vyos_facts] ******************************************************************************************************
 27675 1534194371.87309: sending task start callback
 27675 1534194371.87320: entering _queue_task() for r1/vyos_facts
 27675 1534194371.87331: Creating lock for vyos_facts
 27675 1534194371.87577: worker is 1 (out of 1 available)
 27675 1534194371.87763: exiting _queue_task() for r1/vyos_facts
 27675 1534194371.87809: done queuing things up, now waiting for results queue to drain
 27675 1534194371.87829: waiting for pending results...
 27695 1534194371.88285: running TaskExecutor() for r1/TASK: vyos_facts
 27695 1534194371.88477: in run() - task f45c89b5-0efd-3454-b303-000000000021
 27695 1534194371.88606: calling self._execute()
 27695 1534194371.89766: Loading Connection 'network_cli' from /Users/sdoran/Source/ansible/lib/ansible/plugins/connection/network_cli.py
 27695 1534194371.89965: Loading ShellModule 'sh' from /Users/sdoran/Source/ansible/lib/ansible/plugins/shell/sh.py
 27695 1534194371.90147: assigned :doc
 27695 1534194371.90279: Loading ModuleDocFragment 'shell_common' from /Users/sdoran/Source/ansible/lib/ansible/utils/module_docs_fragments/shell_common.py
 27695 1534194371.90453: Loaded config def from plugin (shell/sh)
 27695 1534194371.90496: Loading ShellModule 'sh' from /Users/sdoran/Source/ansible/lib/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 27695 1534194371.90848: Loading Connection 'local' from /Users/sdoran/Source/ansible/lib/ansible/plugins/connection/local.py
 27695 1534194371.90892: Loading ShellModule 'sh' from /Users/sdoran/Source/ansible/lib/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 27695 1534194371.90937: Loading ShellModule 'sh' from /Users/sdoran/Source/ansible/lib/ansible/plugins/shell/sh.py (found_in_cache=True, class_only=False)
 27695 1534194371.91134: assigned :doc
 27695 1534194371.91800: Loading Connection 'ssh' from /Users/sdoran/Source/ansible/lib/ansible/plugins/connection/ssh.py (found_in_cache=False, class_only=True)
 27695 1534194371.92849: assigned :doc
 27695 1534194371.92916: Loaded config def from plugin (connection/ssh)
 27695 1534194371.93372: assigned :doc
 27695 1534194371.93423: Loaded config def from plugin (connection/network_cli)
```
