### ISSUE TITLE
Allow vars_files to be specified from a role

### ISSUE THREAD

**Issue by jsdalton** [ansible/ansible#4057]
This is a feature request.

Right now it's possible to set variables when listing out roles in a playbook. For example, pretend we're installing two Wordpress blogs on the same host:

``` yaml
- host: all
  roles:
    - { role: wordpress, location: /var/www/foo, db: foo, db_user: bob, db_password: blob}
    - { role: wordpress, location: /var/www/bar, db: bar, db_user: mary, db_password: blib}
```

Roles work great for this, and the ability to pass variables to the roles is a great way to make specific tweaks to each installation.

However:
- This starts to break down when you have more than a handful of variables
- Variable files are a better place than a playbook to be defining/overriding variables
- I purposefully used "db_password" above as an example of the kind of variable that it's ideal to set/include in a separate file and that's a very bad idea to put in a place like a playbook. It's also exactly the kind of thing that gets overridden on a per installation basis.

The workaround for now is to use very specific roles (e.g. wordpress-foo, wordpress-bar) that include a wordpress role as a dependency. The vars set in the specific roles can override the defaults set in the wordpress dependency. This is okay but a bit cumbersome. Also, you're a bit more limited than you are with vars_files because you're only allowed one vars file per role (i.e. vars/main.yml).

Ideally I'd love to be able to specify vars_files for each role that are brought in for that role, e.g.:

``` yaml
- host: all
  roles:
    - { role: wordpress, vars_files: [vars/foo.yml]}
    - { role: wordpress, vars_files: [vars/bar.yml]}
```

The files could live under the vars/ directory in the role, which for now only holds a main.yml.

It's a feature request, but it's in the spirit of existing functionality so hopefully it's a sensible one.

**Comment by mpdehaan** [comment]
I can see that being useful, though this can currently be done with a reference:

```
- hosts: all
  vars_files:  [ 'vars/foo.yml', 'vars/bar.yml' ]
  roles:
       - { role: foo, x:  $from_foo }
       - { role: bar, x: $from_bar }
```

That's not quite what you were after, but I think it achieves the necessary ends without adding more code to support an option that I suspect not too many people would use, though I definitely see how that would be useful in some use cases.

Let me know what you think!
