### ISSUE TITLE
Implement replace_dash_in_groups option in aws_ec2 inventory plugin

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#40581]
##### SUMMARY

Implement replace_dash_in_groups in aws_ec2 inventory plugin
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

aws_ec2 inventory plugin
##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /home/cam-fulcrum/ansible/ansible.cfg
  configured module search path = [u'/home/cam-fulcrum/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/cam-fulcrum/.local/share/virtualenvs/ansible-SHoMHdXE/local/lib/python2.7/site-packages/ansible
  executable location = /home/cam-fulcrum/.local/share/virtualenvs/ansible-SHoMHdXE/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

```

##### CONFIGURATION

```
enable_plugins = aws_ec2, advanced_host_list
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

So at the moment, if I have this in my `hosts.aws_ec2.yml`

```
plugin: aws_ec2
boto_profile: aws_profile
regions: 
  - ap-southeast-2
filters:
    instance-state-name: running
hostnames:
  - private-ip-address
strict: False
  - key: tags['Name']
    separator: ''
```

##### EXPECTED RESULTS

For instances with the name `foo-bar`, the group is turned into `foo-bar`
##### ACTUAL RESULTS

For instances with the name `foo-bar`, the group is turned into `foo_bar`
I'd like there to be a setting in the in the `hosts.aws_ec2.yml` file on whether to replace the dash with an underscore, like whats in [ec2.ini](https://github.com/ansible/ansible/blob/devel/contrib/inventory/ec2.ini#L123)

**Comment by bcoca** [comment]
like: ` - key: tags['Name'].replace('-', '_')` ?

**Comment by ghost** [comment]
Yeah! Thanks! I believe its `- key: tags['Name'].replace('_', '-')` although I've just tried that and it doesn't work (it works for other characters though)

**Comment by ericpfisher** [comment]
Having the same issue as @cam-fulcrum, looks like the [default behavior is to replace anything that's not `A-Za-z0-9_` with an underscore](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/__init__.py#L43-L49). 

Since [`to_safe_group_name()` gets called on the group name after `replace()` is evaluated](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/inventory/__init__.py#L329), any non-`A-Za-z0-9_` characters will be converted to `_`'s regardless of whatever magic we try until we gain a configuration setting to toggle the behavior, either on a per-inventory-plugin basis (with monkey patching?) or globally for any inventory source.

**Comment by mariomarin** [comment]
I used this workaround

```
...
groups:
  # Workaround to add hosts to the group k8s-master and k8s-node since the
  # Ansible inventory plugin aws_ec2 replaces anything different than A-Za-z
  # with an underscore. Therefore, we'll get the desired group k8s-master
   # instead of k8s_master.
  k8s-master: "'k8s-master' == tags.component"
  k8s-node: "'k8s-node' == tags.component"
...
```

**Comment by bcoca** [comment]
this is done because group-with-hyphen is an invalid name and can break things when used in the play

i.e ` {{ groups.with-hyphen}} `

Even if the plugin would create groups with invalid name, we validate against it in core code.

**Comment by AlanCoding** [comment]
To help me keep these all straight, I am going to put some links and notes here.

The issue seems to have some syntax errors. I think it should have used the `keyed_groups` parmeter

```yaml
keyed_groups:
  - key: tags['Name']
    separator: ''
```

The feature this issue is asking to have restored is this configuration option:

https://github.com/ansible/ansible/blob/1c3fa2b07f92ef81c6831762bf9d79ffc121acc0/contrib/inventory/ec2.py#L475

I have tested this, and I believe it to be broken for the "True" case. This is a bug which has not been filed to my knowledge. In other words, there is no way to run the script with the "-" -> "_" conversion happening. If this bug had not existed, this might not be a problem today.

The automatic conversion of group names to replace "-" with "_" (and other conversions) was originally implemented here:

https://github.com/ansible/ansible/pull/28578

I agree this is saying the same thing as https://github.com/ansible/ansible/issues/51844, because:

> For instances with the name `foo-bar`, the group is turned into `foo_bar`

It is desired to have a way to _not_ do this. The default behavior is fine (it's already released, after all), but a simple toggle is needed.

For an isolated example of implementation of such a toggle, see: https://github.com/ansible/ansible/pull/51958/files
