### ISSUE TITLE
Creating VM from Template is Failing

### ISSUE THREAD

**Issue by gowthamnakulan** [ansible/ansible#40582]
##### SUMMARY

We are trying to create VM from template.
I am  facing issue at assigning ip line.

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

vsphere_guest:
##### ANSIBLE VERSION

```
ansible 2.5.2
```

##### OS / ENVIRONMENT

Ubuntu
##### STEPS TO REPRODUCE

```yaml
---

- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1

  tasks:
  - name: Importing Variables
    include_vars: main.yml
  - debug: var=hostname_var
  - debug: var=username_var
  - debug: var=password_var

  - vsphere_guest:
       vcenter_hostname: "{{hostname_var}}"
       username: "{{username_var}}"
       password: "{{password_var}}"
       guest: vmfromtemplate
       from_template: yes
       template_src: Ubuntu VM
       cluster: t1k1-cluster
    networks:
      - name: "vcesys_esx_mgmt"
         ip: "10.1.1.10"
        netmask: "255.255.255.0"
        gateway: "10.0.0.1"
    wait_for_ip_address: yes
~

```

##### EXPECTED RESULTS

VMshould be created from template and assigned the ip for the interface which i am giving at the ntework line.

##### ACTUAL RESULTS

```
ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to have been in '/opt/work/ansible/playbooks/gowtham/vmfromtem                                                                                                             plate.yml': line 27, column 10, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

      - name: "vcesys_esx_mgmt"
         ip: "10.1.1.10"
         ^ here



```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/_vsphere_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/_vsphere_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @rhoop @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@gowthamnakulan Thanks for reporting this issue. I see three potential issues here - 

1. vsphere_guest is a deprecated module, I would recommend you to use `vmware_guest` module instead,

2. You have wrong indentation in your Playbook yaml at `ip`. You can use `--syntax-check` option in Ansible command to check syntax of the pb before hand.

3. There is no parameter called `networks` in vsphere_guest. 

needs_info

**Comment by gowthamnakulan** [comment]
@Akasurde  Thanks for the input. Have fixed the issue using vmware_gyest module.

Working Playbook below:-

```yaml
---

- hosts: 127.0.0.1
  connection: local
  user: root
  sudo: false
  gather_facts: false
  serial: 1

  tasks:
  - name: Importing Variables
    include_vars: main.yml
  - debug: var=hostname_var
  - debug: var=username_var
  - debug: var=password_var

  - vmware_guest:
       hostname: "{{hostname_var}}"
       username: "{{username_var}}"
       password: "{{password_var}}"
       validate_certs: no
       name: VMTemplate
       template: yes
       template_src: Ubuntu VM
       cluster: t1k1-cluster
       folder: Opt_mgmt
       datacenter: t1k1-core
       state: poweredon
       networks:
       - name: vcesys_esx_mgmt
         ip: 10.1.1.10
         netmask: 255.255.255.0
         gateway: 10.1.1.1
         type: static
         start_connected: true

```
