### ISSUE TITLE
azure availability zone feature

### ISSUE THREAD

**Issue by apendragon** [ansible/ansible#40596]
##### SUMMARY

Azure availability zone feature is missing in azure_rm_virtualmachine
##### ISSUE TYPE
 - It would be very useful to add an option to manage [availability zones](https://docs.microsoft.com/en-us/azure/availability-zones/az-overview) in azure_rm_virtualmachine

##### COMPONENT NAME

azure_rm_virtualmachine

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = None
  configured module search path = ['/home/xxxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/xxxxxx/venv/azure/lib64/python3.5/site-packages/ansible
  executable location = /home/xxxxxx/venv/azure/bin/ansible
  python version = 3.5.5 (default, Apr 25 2018, 22:45:38) [GCC 6.4.0]
```

##### CONFIGURATION

_none_
##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
- name: Create virtual machine
  azure_rm_virtualmachine:
    resource_group: "{{ az_rg }}"
    name: "{{ az_vm_name }}"
    vm_size: "{{ az_vm_size }}"
    availability_zone: "{{ az_avz }}"
    admin_username: "{{ vm_admin }}" 
    network_interfaces: "{{ az_vm_name_nic }}"
    image:
      offer: "{{ az_offer }}"
      publisher: "{{ az_publisher }}"
      sku: "{{ az_image_sku }}"
      version: latest
    client_id: "{{ az_client_id }}"
    secret: "{{ az_secret }}"
    tenant: "{{ az_tenant }}"
    subscription_id: "{{ az_subscription_id }}"

```

##### EXPECTED RESULTS

The VM provisioning will be done in the "{{ az_avz }}" availability zone

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "admin_username": "xxxxxx",
            "availability_zone": "test",
            "client_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "data_disks": [

                {
                    "disk_size_gb": 4095,
                    "lun": 0,
                    "managed_disk_type": "Standard_LRS"
                }
            ],
            "image": {
                "offer": "Debian",
                "publisher": "credativ",
                "sku": "9",
                "version": "latest"
            },
            "managed_disk_type": "Premium_LRS",
            "name": "lxxxxxxxx",
            "network_interface_names": "lxxxxxxxx-nic1",
            "network_interfaces": "lxxxxxxxx-nic1",
            "resource_group": "yyyyyy",
            "secret": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "ssh_password_enabled": false,
            "ssh_public_keys": [
                {
                    "key_data": "ssh-rsa XXXXXXXXXXXXXXXX",
                    "path": "/home/xxxxx/.ssh/authorized_keys"
                }
            ],
            "subscription_id": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "tenant": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "vm_size": "Standard_DS2_v2"
        }
    },
    "msg": "Unsupported parameters for (azure_rm_virtualmachine) module: availability_zone Supported parameters include: ad_user,admin_password,admin_username,allocated,append_tags,cli_default_profile,client_id,cloud_environment,data_disks,image,location,managed_disk_type,name,network_interface_names,open_ports,os_disk_caching,os_type,password,profile,public_ip_allocation_method,remove_on_absent,resource_group,restarted,secret,short_hostname,ssh_password_enabled,ssh_public_keys,started,state,storage_account_name,storage_blob_name,storage_container_name,subnet_name,subscription_id,tags,tenant,virtual_network_name,virtual_network_resource_group,vm_size"
}
```
