### ISSUE TITLE
Nesting lookup plugins in with_items constructs

### ISSUE THREAD

**Issue by srgvg** [ansible/ansible#4060]
A per IRC and list discussion https://groups.google.com/d/msg/ansible-project/tpCqDRKFsZc/G0BjE3gaHdYJ

Combining with_items and task includes are not supported, and will get removed.
To be able to keep similar features however, we need a way to nest lookup plugins in with_items constructs.

We could get the output of a lookup plugin as a complex var, a list, and not a flattened string, on a with_ construct:

``` yaml
  vars:
    users:
    - foo
    - bar

  tasks:
  - debug: 'msg="{{ item.0, item.1 }}"'
    with_nested:
    - users
    - lookup('fileglob', 'files/*')
```

We would need to make sure it was implemented for "with_items" and the various other appropriate "with_" statements as well.
