### ISSUE TITLE
JunOs commit confirmed instant rollback

### ISSUE THREAD

**Issue by bcavns01** [ansible/ansible#40626]
##### SUMMARY

`confirm` option of the `junos_config ` module does not work as expected.  Commits are immediately rolled back.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

junos_config
##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = [u'/path/to/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True
##### OS / ENVIRONMENT

OS running ansible:
Ubuntu 16.04.3 LTS

OS being managed:
Model: qfx5100-48s-6q
Junos: 17.3R1.10

##### STEPS TO REPRODUCE

Create and run a task to apply config changes to a juniper switch:

```
  - name: Apply - Generated config
    junos_config:
      host: "{{ juniper_ssh_host }}"
      port: "{{ juniper_ssh_port }}"
      username: "{{ juniper_ssh_user }}"
      ssh_keyfile: "{{ juniper_ssh_key_file }}"
      src: "path/to/juniper-full-config.set"
      src_format: set
      confirm: 20
```

##### EXPECTED RESULTS

I expected the commit to have a timeout of 20 minutes before being rolled back.
##### ACTUAL RESULTS

The commit is immediately rolled back.

##### ADDITIONAL
This is an issue with the ncclient library being used by the ansible junos_* modules, which is detailed in the following relevant github links.
https://github.com/NetworkAutomation/jaide/issues/6
https://github.com/ncclient/ncclient/pull/37/files

TL;DR: Junos expects the xml tree for a commit RPC to have `commit-configuration` as the top level node, not `commit`, but ncclient continues to use the incorrect top level node name.

##### SUGGESTED FIX
Remove the dependency on `ncclient` or fork it, or shift to using vendor-provided libraries, such as https://github.com/Juniper/ansible-junos-stdlib
