### ISSUE TITLE
vmware_guest tries to customize the VM when using the networks parameter.

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#40637]
##### SUMMARY
vmware_guest tries to customize the VM when using the networks parameter even without optionnal parameters used for OS customization.
The error that appears is "Failed to create a virtual machine : Customization of the guest operating system 'rhel7_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations."

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest 

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

Installed via pip on CentOS Linux release 7.4.1708 (Core)

##### STEPS TO REPRODUCE

```yaml
- name: "Cloning the template"
  vmware_guest:
    hostname: "vcenter.lab"
    username: "user@lab"
    password: ""
    validate_certs: no
    esxi_hostname: "esx.lab"
    datacenter: "DCLAB"
    folder: "/folder"
    name: "test"
    template: "RHEL_tpl"
    hardware:
      memory_mb: "1024"
      num_cpus: "1"
    networks:
    - name: "DPG_Network"
    disk:
    - size_gb: 32
      type: thick
      autoselect_datastore: yes
    - size_gb: 16
      type: thick
      autoselect_datastore: yes
    - size_gb: 32
      type: thick
      autoselect_datastore: yes
    state: present
```

##### EXPECTED RESULTS

The cloned VM with the good network, and no errors.

##### ACTUAL RESULTS

The VM is cloned and the network is good, but Ansible fails when trying to customize the OS.

The error is located at vmware_guest.py, lines 940 to 947, in the sanitize_network_params function.

```python
 else:
     # Type is optional parameter, if user provided IP or Subnet assume
     # network type as 'static'
     if 'ip' in network or 'netmask' in network:
         network['type'] = 'static'
     else:
         # User wants network type as 'dhcp'
         network['type'] = 'dhcp'
```

Whatever happens before, the network['type'] is still setted at 'dhcp', even if I only use "name" or "vlan". You can see below the request sent to the vCenter contains the type 'dhcp' :

```
            "networks": [
                {
                    "name": "DPG_Network",
                    "type": "dhcp"
                }
```

And then when network['type'] is not null, customize_vm is called and tries to do it's job on my template which doesn't want to be customized :)

Lines 1639 => 1648 :

```python
network_changes = False
for nw in self.params['networks']:
    for key in nw:
        # We don't need customizations for these keys
        if key not in ('device_type', 'mac', 'name', 'vlan'):
            network_changes = True
            break

if len(self.params['customization']) > 0 or network_changes is True:
    self.customize_vm(vm_obj=vm_obj)
```

```
fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "DCLAB",
            "disk": [
                {
                    "autoselect_datastore": true,
                    "size_gb": 32,
                    "type": "thick"
                },
                {
                    "autoselect_datastore": true,
                    "size_gb": 16,
                    "type": "thick"
                },
                {
                    "autoselect_datastore": true,
                    "size_gb": 32,
                    "type": "thick"
                }
            ],
            "esxi_hostname": "esx.lab",
            "folder": "/folder",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": "1024",
                "num_cpus": "1"
            },
            "hostname": "vcenter.lab",
            "is_template": false,
            "linked_clone": false,
            "name": "test",
            "name_match": "first",
            "networks": [
                {
                    "name": "DPG_Network",
                    "type": "dhcp"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": null,
            "state": "present",
            "template": "RHEL_tpl",
            "username": "user@lab",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": false
        }
    },
    "msg": "Failed to create a virtual machine : Customization of the guest operating system 'rhel7_64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations."
}
```
