### ISSUE TITLE
Action plugin doesn't pass environment to script

### ISSUE THREAD

**Issue by 514amir** [ansible/ansible#40630]
##### SUMMARY
If we add some environment to a specific action task it seems that the action called (a python script) doesn't get that set as it's environment. We are using ansible tower too.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

action

##### ANSIBLE VERSION

ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

##### CONFIGURATION

ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
GALAXY_IGNORE_CERTS(/etc/ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Ubuntu 16.04.4 LTS \n \l

##### STEPS TO REPRODUCE

```yaml
- name: Register to Endpoint
  action: register_to_action
  environment: "    http_proxy: "someproxy:8888"
    https_proxy: "someproxy:8888"
    HTTP_PROXY: "someproxy:8888"
    HTTPS_PROXY: "someproxy:8888"  "

```

##### EXPECTED RESULTS

I expected the script being called by the action plugin to respect the environment variable (in this case the proxy) and run the action set with the environment of the proxy
##### ACTUAL RESULTS

Instead the script was called with the OS environment variables using the system proxy.

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/action/__init__.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/action/__init__.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
I cannot duplicate this.  I created the following module:

library/register_to_action.py
```
#!/usr/bin/python

import os
import json

print(json.dumps(dict(os.environ)))
```

And updated the playbook to look like:

```
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Register to Endpoint
      action: register_to_action
      environment:
        https_proxy: "someproxy:8888"
        HTTP_PROXY: "someproxy:8888"
        HTTPS_PROXY: "someproxy:8888"
      register: env

    - assert:
        that:
          - env['https_proxy'] == "someproxy:8888"
          - env['HTTP_PROXY'] == "someproxy:8888"
          - env['HTTPS_PROXY'] == "someproxy:8888"
```

Which results in the following output:

```
TASK [Register to Endpoint] ******************************************************************************************************************************************************************************************************************
ok: [localhost]

TASK [assert] ********************************************************************************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}
```

This indicates that the environment is correctly passed to the custom module executed via `action`.

Please provide the contents of your `register_to_action` file, and verbose output of ansible-playbook utilizing `-vvv`.

needs_info
