### ISSUE TITLE
aci_contract: No JSON object could be decoded error 

### ISSUE THREAD

**Issue by joelwking** [ansible/ansible#40636]
##### ISSUE TYPE
 - Informational

##### COMPONENT NAME

aci_contract

##### ANSIBLE VERSION

```
Observed in Ansible 2.5.1, 2.5.2 and 2.5.3, with Ansible Tower 3.2.4.
```

##### CONFIGURATION

DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plu
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible']

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Following APIC upgrade to Version: 3.1(2o), the ACI playbook demonstrated (https://youtu.be/Fs8STriMqTM?t=8m24s) began to intermittently fail when when adding contracts to the APIC. Running the same playbook against an APIC simulator on 3.0(1k) has not encountered errors, using the same playbook and the same instance of Ansible Tower. Only the target APIC was changed.

Enabling debug level 3 (-vvv) appears to reduce or eliminate the frequency of the problem, suggesting it may be load or timing related.  I suspect the fault is with the APIC controller on release 3.1(2o). This is an informational issue only.

```yaml
    - name: Add (or delete) the contract
      aci_contract:
        hostname: '{{ inventory_hostname }}'
        username: '{{ apic.username }}'
        password: '{{ apic.password }}'
        validate_certs: '{{ validate_certs }}'
        state: '{{ desired_state }}'
        #
        contract: '{{ item.contract_name }}'
        description: '{{ item.contract_descr }}'
        tenant: '{{ tenant }}'
        scope: '{{ scope }}'  
      with_items: '{{ tpe }}'
      tags: contract
```

##### EXPECTED RESULTS

The contract would be added to the APIC.

##### ACTUAL RESULTS

```json
{
    "changed": false,
    "error": {
        "code": -1,
        "text": "Unable to parse output as JSON, see 'raw' output. No JSON object could be decoded"
    }
}
```

```json
failed: [aci-demo.sandbox.wwtatc.local] (item={u'contract_name': u'QA_Bling_Enterprise-to-Prod_Qualys', u'dst_port_start': u'4445', u'dst_port_end': u'4445', u'ip_protocol': u'tcp', u'contract_subject_name': u'sub-QA_Bling_Enterprise-to-Prod_Qualys', u'contract_descr': u'WorkOrder6756', u'entry_name': u'tcp-port_4445', u'filter_name': u'tcp-4445', u'contract_subject_descr': u'WorkOrder6756', u'filter_descr': u'WorkOrder6756', u'filter_entry_descr': u'ent_descr', u'ether_type': u'ip'}) => {
    "changed": false,
    "error": {
        "code": -1,
        "text": "Unable to parse output as JSON, see 'raw' output. No JSON object could be decoded"
    },
    "item": {
        "contract_descr": "WorkOrder6756",
        "contract_name": "QA_Bling_Enterprise-to-Prod_Qualys",
        "contract_subject_descr": "WorkOrder6756",
        "contract_subject_name": "sub-QA_Bling_Enterprise-to-Prod_Qualys",
        "dst_port_end": "4445",
        "dst_port_start": "4445",
        "entry_name": "tcp-port_4445",
        "ether_type": "ip",
        "filter_descr": "WorkOrder6756",
        "filter_entry_descr": "ent_descr",
-snip-
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/aci/aci_contract.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/aci/aci_contract.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @brunocalogero @dagwieers @jmcgill298 @schunduri
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@joelwking Thanks for reporting. I have a few questions:
1. Did you already try using [Signature-based authentication](https://docs.ansible.com/ansible/devel/scenario_guides/guide_aci.html#signature-based-authentication-using-certificates) ? This is to avoid [too many consecutive API calls result in connection throttling](https://docs.ansible.com/ansible/devel/scenario_guides/guide_aci.html#known-issues)
2. I did not see the 'raw' key in the output from the module. Did the call to the APIC return any information at all ? I would expect something is returned, if not JSON.
3. If this problem only started to show after upgrading to 3.1(2o), did you already open a ticket with Cisco support ?

**Comment by rsmeyers** [comment]
This most likely is DDOS protection which was added as per APIC 3.1, please switch to cert based auth.
See also https://docs.ansible.com/ansible/devel/scenario_guides/guide_aci.html#signature-based-authentication-using-certificates

**Comment by dagwieers** [comment]
@joelwking So if you could confirm this is related to the anti-DDOS measures in ACI v3.1, we can start looking at improving the error-message to make this more straightforward.

The long-term strategy here (for Ansible v2.7) is a full-blown ACI connection plugin (#36100), which would be more efficient (no need to authenticate for every task) and would make playbooks more concise (no need to repeat login information). Additionally we can make the connection cluster-aware as well.

**Comment by joelwking** [comment]
@dagwieers I will test using certificates in 3.1 and report back.

**Comment by joelwking** [comment]
@dagwieers Using cert based authentication against APIC 3.1(2o) has eliminated the issue. I agree that improving the error message would be most helpful! Obviously reading the APIC release notes may have shortened the debugging time. In this instance another engineer did the APIC upgrade and I was not aware of the anti-DDOS feature.

Could I suggest you consider accepting the `private_key` and `certificate_name` as variables rather than file names? My playbooks must run under Ansible Tower using an SCM and don't store files locally on Tower. Looking for suggestions on a better solution.

passwords.yml is encrypted using ansible-vault, for example:
```yaml
     ---
     apic:
       username: kingjoe
       ssl_private_key: |
         -----BEGIN PRIVATE KEY-----
         MIIC....
         -----END PRIVATE KEY-----

       ssl_certificate: |
         -----BEGIN CERTIFICATE-----
         MIIC....
         -----END CERTIFICATE-----
```
The files are then created at playbook execution and file names provided to aci_contract, for example:
```yaml
tasks:

    - name: Include credentials from an encrypted password.yml file
      include_vars: '{{ playbook_dir }}/files/passwords.yml'
      no_log: True

    - name: The private_key and certificate files are in passwords.yml
      copy:
        content: '{{ item.value }}'
        dest:  '{{ playbook_dir }}/files/{{ item.name }}'
        mode: 0600
      no_log: True
      with_items:
        - {'value': '{{ apic.ssl_private_key }}', 'name': '{{apic.username}}.key' }
        - {'value': '{{ apic.ssl_certificate }}', 'name': '{{apic.username}}.crt' }
     
    - name: Get facts from CSV file
      csv_to_facts:
        src: '{{ csv_file }}'
        table: tpe                                         # This is a namespace to contain the rows of the spreadsheet
#
#   Contract and contract subject section
#
    - name: Add (or delete) the contract
      aci_contract:
        hostname: '{{ inventory_hostname }}'
        username: '{{ apic.username }}'
        private_key: '{{ playbook_dir }}/files/{{ apic.username }}.key'
        certificate_name:   '{{ apic.username }}'           # Optional, default based on private_key
        validate_certs: '{{ validate_certs }}'
        state: '{{ desired_state }}'
        #
        contract: '{{ item.contract_name }}'
        description: '{{ item.contract_descr }}'
        tenant: '{{ tenant }}'
        scope: '{{ scope }}'  
      with_items: '{{ tpe }}'
      tags: contract
```
Thanks for the help.
