### ISSUE TITLE
F5 bigip_pool_member reports change needs to be made when there's no change

### ISSUE THREAD

**Issue by eoprede** [ansible/ansible#40631]
##### SUMMARY
When running playbook with bigip_pool_member module with state: present against live device, each run results in change being made when in reality there's no need for a change.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_pool_member
##### ANSIBLE VERSION

```
ansible 2.6.0a1
  config file = None
  configured module search path = [u'/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
```

##### OS / ENVIRONMENT

Running Ansible within container as described here: http://ruleoftech.com/2017/dockerizing-all-the-things-running-ansible-inside-docker-container
##### STEPS TO REPRODUCE

The following playbook will result in changes made every time it is run.
```yaml
- name: Create Pool
      bigip_pool_member:
        provider: "{{ test_f5 }}"
        pool: abc_log
        state: present
        host: "10.0.0.100"
        port: 50002
        partition: Common
      delegate_to: localhost
```
However this playbook (state: absent) will run as expected.
```yaml
- name: Create Pool
      bigip_pool_member:
        provider: "{{ test_f5 }}"
        pool: abc_log
        state: absent
        host: "10.0.0.100"
        port: 50002
        partition: Common
      delegate_to: localhost
```

##### EXPECTED RESULTS

I would expect the playbook to change config only once, not every time it is run.
##### ACTUAL RESULTS

```
Config gets applied every run instead of just once.
```

**Comment by eoprede** [comment]
@caphrim007 This doesn't affect functionality and is mostly cosmetic.

**Comment by caphrim007** [comment]
@eoprede using the stable-2.6 branch, I cannot reproduce this. Here is my own test that works fine on stable-2.6

https://github.com/F5Networks/f5-ansible/blob/devel/test/integration/targets/bigip_pool_member/tasks/provider/issue-00743.yaml

**Comment by eoprede** [comment]
@caphrim007 
Here's the example playbook that fails:
```
- name: Create Pool
      tags: test
      bigip_pool_member:
        provider: "{{ test_f5 }}"
        pool: "{{item.0.name}}"
        state: "{{item.1.state | default(omit)}}"
        host: "{{item.1.host}}"
        port: "{{item.1.port}}"
        partition: "{{item.1.partition | default(omit)}}"
      with_subelements:
        - "{{pools}}"
        - members
      delegate_to: localhost
```
Here's the -vvv example:
```
changed: [localhost -> localhost] => (item=({u'monitor_type': u'single', u'state': u'present', u'lb_method': u'least-connections-node', u'monitors': [u'HIPPO_Health'], u'name': u'f'}, {u'host': u'10.0.8.102', u'port': u'55000'})) => {
    "changed": true,
    "invocation": {
        "module_args": {
            "address": "10.0.8.102",
            "connection_limit": null,
            "description": null,
            "fqdn": null,
            "fqdn_auto_populate": null,
            "host": "10.0.8.102",
            "monitor_state": null,
            "name": null,
            "partition": "Common",
            "password": null,
            "pool": "f",
            "port": 55000,
            "preserve_node": null,
            "priority_group": null,
            "provider": {
                "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "server": "10.98.255.84",
                "server_port": null,
                "ssh_keyfile": null,
                "timeout": null,
                "transport": "rest",
                "user": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "validate_certs": false
            },
            "rate_limit": null,
            "ratio": null,
            "reuse_nodes": true,
            "server": null,
            "server_port": null,
            "session_state": null,
            "state": "present",
            "transport": null,
            "user": null,
            "validate_certs": null
        }
    },
    "item": [
        {
            "lb_method": "least-connections-node",
            "monitor_type": "single",
            "monitors": [
                "HIPPO_Health"
            ],
            "name": "f",
            "state": "present"
        },
        {
            "host": "10.0.8.102",
            "port": "55000"
        }
    ],
    "session": "user-enabled",
    "state": "present"
}
```
And the ansible that I am running:
```
ansible-playbook 2.6.0a2
  config file = None
  configured module search path = [u'/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
```

**Comment by eoprede** [comment]
And the actual object as displayed in the CLI:
```
ltm pool f {
    load-balancing-mode least-connections-node
    members {
        10.0.8.102:55000 {
            address 10.0.8.102
            session monitor-enabled
            state down
        }
       [....many more members...]
    
    }
    monitor HIPPO_Health
}
```

**Comment by caphrim007** [comment]
@eoprede these are my tasks


```
- name: Issue 00743 - Set fact for testing
  set_fact:
    pools:
      - name: f
        members:
          - host: 3.3.3.3
            port: 80
          - host: 4.4.4.4
            port: 8080
          - host: 5.5.5.5
            port: 443
      - name: g
        members:
          - host: 6.6.6.6
            port: 80
          - host: 7.7.7.7
            port: 8080
          - host: 8.8.8.8
            port: 443

- name: Issue 00743 - Create Pool members with_subelements
  bigip_pool_member:
    provider:
      password: "{{ bigip_password }}"
      server: "{{ ansible_host }}"
      server_port: "{{ bigip_port }}"
      user: "{{ bigip_username }}"
      validate_certs: "{{ validate_certs }}"
    pool: "{{item.0.name}}"
    state: "{{item.1.state | default(omit)}}"
    host: "{{item.1.host}}"
    port: "{{item.1.port}}"
    partition: "{{item.1.partition | default(omit)}}"
  with_subelements:
    - "{{ pools }}"
    - members
```

The first time I run it, I get this

```
TASK [bigip_pool_member : Issue 00743 - Create Pool members with_subelements] ***************************************************************
changed: [bigip1.local] => (item=({'name': 'f'}, {'host': '3.3.3.3', 'port': 80}))
changed: [bigip1.local] => (item=({'name': 'f'}, {'host': '4.4.4.4', 'port': 8080}))
changed: [bigip1.local] => (item=({'name': 'f'}, {'host': '5.5.5.5', 'port': 443}))
changed: [bigip1.local] => (item=({'name': 'g'}, {'host': '6.6.6.6', 'port': 80}))
changed: [bigip1.local] => (item=({'name': 'g'}, {'host': '7.7.7.7', 'port': 8080}))
changed: [bigip1.local] => (item=({'name': 'g'}, {'host': '8.8.8.8', 'port': 443}))
```

The second time I run it and all times afterwards, I get this

```
TASK [bigip_pool_member : Issue 00743 - Create Pool members with_subelements] ***************************************************************
ok: [bigip1.local] => (item=({'name': 'f'}, {'host': '3.3.3.3', 'port': 80}))
ok: [bigip1.local] => (item=({'name': 'f'}, {'host': '4.4.4.4', 'port': 8080}))
ok: [bigip1.local] => (item=({'name': 'f'}, {'host': '5.5.5.5', 'port': 443}))
ok: [bigip1.local] => (item=({'name': 'g'}, {'host': '6.6.6.6', 'port': 80}))
ok: [bigip1.local] => (item=({'name': 'g'}, {'host': '7.7.7.7', 'port': 8080}))
ok: [bigip1.local] => (item=({'name': 'g'}, {'host': '8.8.8.8', 'port': 443}))
```

No change is happening. Do you get the same effect with my tasks?

**Comment by eoprede** [comment]
@caphrim007 
It looks like adding monitor does the trick:
```
tasks:
    - name: Issue 00743 - Set fact for testing
      set_fact:
        pools:
          - name: a
            monitor_type: single
            monitors:
              - HIPPO_Health
            members:
              - host: 3.3.3.3
                port: 80
              - host: 4.4.4.4
                port: 8080
              - host: 5.5.5.5
                port: 443
          - name: b
            members:
              - host: 6.6.6.6
                port: 80
              - host: 7.7.7.7
                port: 8080
              - host: 8.8.8.8
                port: 443
        monitor_http:
          - name: HIPPO_Health
            interval: 10
            timeout: 31
            receive: UP
            send: GET /rest/server/ping\\r\\n
    - name: Create HTTP monitors
      bigip_monitor_http:
        provider: "{{ test_f5 }}"
        name: "{{item.name}}"
        state: "{{item.state | default(omit) }}"
        interval: "{{item.interval}}"
        timeout: "{{item.timeout}}"
        receive: "{{item.receive}}"
        receive_disable: "{{item.receive_disable | default(omit)}}"
        send: "{{item.send}}"
      loop: "{{ monitor_http }}"
      delegate_to: localhost
    - name: Create Pool
      bigip_pool:
        provider: "{{ test_f5 }}"
        name: "{{item.name}}"
        state: "{{item.state | default(omit) }}"
        lb_method: "{{item.lb_method | default(omit)}}"
        monitor_type: "{{item.monitor_type | default(omit) }}"
        monitors: "{{item.monitors | default(omit) }}"
        service_down_action: "{{item.service_down_action | default(omit)}}"
      loop: "{{ pools }}"
      delegate_to: localhost
    - name: Issue 00743 - Create Pool members with_subelements
      bigip_pool_member:
        provider: "{{ test_f5 }}"
        pool: "{{item.0.name}}"
        state: "{{item.1.state | default(omit)}}"
        host: "{{item.1.host}}"
        port: "{{item.1.port}}"
        partition: "{{item.1.partition | default(omit)}}"
      with_subelements:
        - "{{ pools }}"
        - members
```

And here's the output of all of the runs after the 1st one:
```
TASK [Issue 00743 - Set fact for testing] *******************************************************************************************************************
ok: [localhost]

TASK [Create HTTP monitors] *********************************************************************************************************************************
ok: [localhost -> localhost] => (item={u'receive': u'UP', u'interval': 10, u'name': u'HIPPO_Health', u'timeout': 31, u'send': u'GET /rest/server/ping\\\\r\\\\n'})

TASK [Create Pool] ******************************************************************************************************************************************
ok: [localhost -> localhost] => (item={u'name': u'a', u'monitor_type': u'single', u'members': [{u'host': u'3.3.3.3', u'port': 80}, {u'host': u'4.4.4.4', u'port': 8080}, {u'host': u'5.5.5.5', u'port': 443}], u'monitors': [u'HIPPO_Health']})
ok: [localhost -> localhost] => (item={u'name': u'b', u'members': [{u'host': u'6.6.6.6', u'port': 80}, {u'host': u'7.7.7.7', u'port': 8080}, {u'host': u'8.8.8.8', u'port': 443}]})

TASK [Issue 00743 - Create Pool members with_subelements] ***************************************************************************************************
changed: [localhost] => (item=({u'monitors': [u'HIPPO_Health'], u'monitor_type': u'single', u'name': u'a'}, {u'host': u'3.3.3.3', u'port': 80}))
changed: [localhost] => (item=({u'monitors': [u'HIPPO_Health'], u'monitor_type': u'single', u'name': u'a'}, {u'host': u'4.4.4.4', u'port': 8080}))
changed: [localhost] => (item=({u'monitors': [u'HIPPO_Health'], u'monitor_type': u'single', u'name': u'a'}, {u'host': u'5.5.5.5', u'port': 443}))
ok: [localhost] => (item=({u'name': u'b'}, {u'host': u'6.6.6.6', u'port': 80}))
ok: [localhost] => (item=({u'name': u'b'}, {u'host': u'7.7.7.7', u'port': 8080}))
ok: [localhost] => (item=({u'name': u'b'}, {u'host': u'8.8.8.8', u'port': 443}))

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=0
```
