### ISSUE TITLE
azure_rm_virtualmachine: Azure Error - Multiple NICs: NetworkInterfaceMustHavePrimaryPropertySet, Message: Network interface must have Primary property set.

### ISSUE THREAD

**Issue by the1bit** [ansible/ansible#40648]
##### SUMMARY

Hi,

I would like to create VMs with 2 NICs. During I execute the playbook I am facing the following error:
```
TASK [Create VM - 2 NICs] *******************************************************************************************************************************************************************
fatal: [myvm02]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine myvm02 - Azure Error: NetworkInterfaceMustHavePrimaryPropertySet\nMessage: Network interface myvm02-nic-fe must have Primary property set."}
```

Although I saw this issue was solved in the past I cannot find how can I set the Primary parameter.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
azure_rm_virtualmachine

##### ANSIBLE VERSION
```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
```
DEFAULT_HASH_BEHAVIOUR(/etc/ansible/ansible.cfg) = merge
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
```
##### OS / ENVIRONMENT
```
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

##### STEPS TO REPRODUCE
Playbook
```yaml
  - name: Create virtual network inteface card - FE
    azure_rm_networkinterface:
      resource_group: myresourcegroup
      name: "{{vm_name}}-nic-fe"
      virtual_network: my-vnet
      subnet: my-subnet-fe
      security_group: my-nsg-fe
      ip_configurations:
        - name: ipconfig1
          public_ip_address_name: "{{vm_name}}-pip"
          primary: true
  - name: Create virtual network inteface card - BE
    azure_rm_networkinterface:
      resource_group: myresourcegroup
      name: "{{vm_name}}-nic-be"
      virtual_network: my-vnet
      subnet: my-subnet-be
      security_group: my-nsg-be
      ip_configurations:
        - name: ipconfig1
  - name: Create an availability set with UD - 5, FD - 3
    azure_rm_availabilityset:
      name: my-availabilityset-custom
      resource_group: myresourcegroup
      platform_update_domain_count: 5
      platform_fault_domain_count: 3
      sku: Aligned
  - name: Create VM - 2 NICs
    azure_rm_virtualmachine:
      resource_group: myresourcegroup
      name: "{{vm_name}}"
      vm_size: Standard_DS12_v2
      availability_set: my-availabilityset-custom
      managed_disk_type: Standard_LRS
      admin_username: localadmin
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/localadmin/.ssh/authorized_keys
          key_data: "ssh-rsa aaaa"
      network_interface_names:
      - "{{vm_name}}-nic-fe"
      - "{{vm_name}}-nic-be"
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.3'
        version: latest
      data_disks:
        - lun: 0
          disk_size_gb: 128
          managed_disk_type: Premium_LRS
```

Command
```yaml
ansible-playbook -i inventory/ azure_create_vm.yml
```

##### EXPECTED RESULTS
```
TASK [Create VM - 2 NICs] *******************************************************************************************************************************************************************
ok: [myvm02]
```

##### ACTUAL RESULTS
```
TASK [Create VM - 2 NICs] *******************************************************************************************************************************************************************
fatal: [myvm02]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual machine myvm02 - Azure Error: NetworkInterfaceMustHavePrimaryPropertySet\nMessage: Network interface myvm02-nic-fe must have Primary property set."}
```

Thank you for your support in this matter.
