### ISSUE TITLE
k8s_raw StatefulSet confuses same containerPort for TCP and UDP

### ISSUE THREAD

**Issue by ctrox** [ansible/ansible#40654]
##### SUMMARY
When creating a StatefulSet with k8s_raw which uses the same containerPort for TCP and UDP (ordering is also important, see note at the bottom), a second apply will do a faulty patch resulting in both ports to listen on UDP. This works with Ansible 2.5, and was probably introduced with https://github.com/ansible/ansible/pull/39632.

It is a bit of an edge case but I don't think something should break because of the ordering.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
k8s_raw

##### ANSIBLE VERSION

```
ansible --version
ansible 2.6.0dev0 (devel 160bf82544) last updated 2018/05/24 12:30:21 (GMT +200)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cyrill/git/ansible/library']
  ansible python module location = /home/cyrill/git/ansible/lib/ansible
  executable location = /home/cyrill/git/ansible/bin/ansible
  python version = 2.7.15 (default, May  2 2018, 14:12:52) [GCC 8.0.1 20180324 (Red Hat 8.0.1-0.20)]
```

##### CONFIGURATION

Default ansible.cfg.

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE
Task:
```yaml
---
- hosts: localhost
  tasks:
  - name: Create Test StatefulSet
    k8s_raw:
      state: present
      definition:
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: statefulset-test
          namespace: default
        spec:
          selector:
            matchLabels:
              app: nginx
          serviceName: "nginx"
          replicas: 1
          template:
            metadata:
              labels:
                app: nginx
            spec:
              terminationGracePeriodSeconds: 10
              containers:
              - name: nginx
                image: nginx
                imagePullPolicy: Always
                ports:
                - containerPort: 80
                  protocol: TCP
                  name: web-tcp
                - containerPort: 80
                  protocol: UDP
                  name: web-udp
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
```

##### EXPECTED RESULTS
* First apply creation of the StatefulSet, containerPorts are correct
Result output from ansible:
```
"ports": [
    {
        "containerPort": 80,
        "name": "web-tcp",
        "protocol": "TCP"
    }, 
    {
        "containerPort": 80,
        "name": "web-udp", 
        "protocol": "UDP"
    }
]
```
* Second apply no changes.

##### ACTUAL RESULTS

* First apply creation of the StatefulSet
* Second apply patches the first containerPort to be the same as the second

```
"ports": [
    {
        "containerPort": 80, 
        "name": "web-udp", 
        "protocol": "UDP"
    }, 
    {
        "containerPort": 80, 
        "name": "web-udp", 
        "protocol": "UDP"
    }
]
```

Note: This only goes wrong when the TCP Port comes before the UDP Port **and** Ansible can find something to patch first. So for example by adding `resources: {}` to the container spec it will not detect any changes and will not break the containerPorts.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/_k8s_raw.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/_k8s_raw.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
This one actually seems like a kubernetes bug, I saw the same behavior with the following:
```bash
cat <<EOF > test.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: nginx
  serviceName: "nginx"
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
          name: web-tcp
        - containerPort: 80
          protocol: UDP
          name: web-udp
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
EOF

kubectl create -f test.yaml
kubectl get sts statefulset-test -o go-template --template='{{range .spec.template.spec.containers}}{{range .ports}}[port: {{.containerPort}}, name:{{.name}}], {{end}}{{end}}'
echo

kubectl patch -f test.yaml -p "$(cat test.yaml)"
kubectl get sts statefulset-test -o go-template --template='{{range .spec.template.spec.containers}}{{range .ports}}[port: {{.containerPort}}, name:{{.name}}], {{end}}{{end}}'
```
For me that output 
```
statefulset "statefulset-test" created
[port: 80, name:web-tcp], [port: 80, name:web-udp], 
statefulset "statefulset-test" patched
[port: 80, name:web-udp], [port: 80, name:web-udp],
```

**Comment by ctrox** [comment]
Huh, you are right it seems to be related to this: https://github.com/kubernetes/kubernetes/issues/39188

**Comment by fabianvf** [comment]
@CTrox In the meantime, I think if you pass in `force: True` when invoking the module it will do a replace instead of a patch, and should let you avoid this issue.

**Comment by fabianvf** [comment]
@CTrox It looks like you can also override this behavior by adding `$patch: replace` as the first element of your  port list. This overrides the default merge strategy and sets it to replace instead:
```yaml
- hosts: localhost
  tasks:
  - name: Create Test StatefulSet
    k8s_raw:
      state: present
      definition:
        apiVersion: apps/v1
        kind: StatefulSet
        metadata:
          name: statefulset-test
          namespace: default
        spec:
          selector:
            matchLabels:
              app: nginx
          serviceName: "nginx"
          replicas: 1
          template:
            metadata:
              labels:
                app: nginx
            spec:
              terminationGracePeriodSeconds: 10
              containers:
              - name: nginx
                image: nginx
                imagePullPolicy: Always
                ports:
                - $patch: replace
                - containerPort: 80
                  protocol: TCP
                  name: web-tcp
                - containerPort: 80
                  protocol: UDP
                  name: web-udp
                terminationMessagePath: /dev/termination-log
                terminationMessagePolicy: File
```
