### ISSUE TITLE
VM Deployement with dhcp and ip, netmask, gateway empty params

### ISSUE THREAD

**Issue by kizz1337** [ansible/ansible#40652]
##### SUMMARY
When using "static" as network type ip, mask, gateway are mandatory so no problem, when using dhcp if ip, mask, gateway line are present there is an error and playbook fail.
"msg": "Static IP information provided for network \"VM Network\", but \"type\" is set to \"dhcp\"."

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION
```
ansible 2.5.0
```

##### STEPS TO REPRODUCE

```yaml
- name: create the VM
  vmware_guest:
    hostname: '{{ vmware_vcenter_hostname }}'
    username: '{{ vmware_vcenter_username }}'
    password: '{{ vmware_vcenter_password }}'
    validate_certs: no
    esxi_hostname: '{{ esxi_host }}'
    datacenter: '{{ vsphere_datacenter }}'
    folder: /{{ vsphere_datacenter }}/vm/{{ vsphere_folder }}
    name: '{{ inventory_hostname }}'
    state: poweredon
    networks:
    - name: '{{ guest_network }}'
      type: '{{ guest_network_type }}'
      ip: '{% if guest_custom_ip is defined and guest_network_type is defined and guest_network_type == "static" %}{{ guest_custom_ip }}{% endif %}'
      netmask: '{% if guest_netmask is defined and guest_network_type is defined and guest_network_type == "static" %}{{ guest_netmask }}{% endif %}'
      gateway: '{% if guest_gateway is defined and guest_network_type is defined and guest_network_type == "static" %}{{ guest_gateway }}{% endif %}'
```

##### EXPECTED RESULTS

When guest_network_type = static and ip, mask, gateway are prsent, the deployement work fine,
when guest_network_type = dhcp expect ignoring ip, mask, gateway params

##### ACTUAL RESULTS

When guest_network_type = static and ip, mask, gateway are prsent, the deployement work fine,
when guest_network_type = dhcp error "Static IP information provided for network \"VM Network\", but \"type\" is set to \"dhcp\".

```
[root@localhost ~]# ansible-playbook -i deploy.yml deploy-vms.yml -vvv
ansible-playbook 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/deploy.yml inventory source with yaml plugin

PLAYBOOK: deploy-vms.yml ********************************************************************************************************************************************************************************************************************
1 plays in /etc/ansible/deploy-vms.yml

PLAY [hosts_to_deploy] **********************************************************************************************************************************************************************************************************************
META: ran handlers

TASK [deploy-vmware-guest : set_fact] *******************************************************************************************************************************************************************************************************
task path: /etc/ansible/git/roles/deploy-vmware-guest/tasks/main.yml:3
ok: [spacewalk] => {
    "ansible_facts": {
        "creationdate": "2018/05/24 12:44"
    },
    "changed": false
}

TASK [deploy-vmware-guest : create the VM] **************************************************************************************************************************************************************************************************
task path: /etc/ansible//roles/deploy-vmware-guest/tasks/main.yml:6
Using module file /usr/lib/python2.7/site-packages/ansible-2.5.0-py2.7.egg/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1527158654.15-89789620185228 `" && echo ansible-tmp-1527158654.15-89789620185228="` echo /root/.ansible/tmp/ansible-tmp-1527158654.15-89789620185228 `" ) && sleep 0'
<localhost> PUT /tmp/tmpUvuKnY TO /root/.ansible/tmp/ansible-tmp-1527158654.15-89789620185228/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1527158654.15-89789620185228/ /root/.ansible/tmp/ansible-tmp-1527158654.15-89789620185228/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1527158654.15-89789620185228/vmware_guest.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1527158654.15-89789620185228/" > /dev/null 2>&1 && sleep 0'
fatal: [spacewalk -> localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "annotation": "Created from Ansiblei - 2018/05/24 12:44",
            "cdrom": {},
            "cluster": null,
            "customization": {},
            "customvalues": [],
            "datacenter": "Datacenter",
            "disk": [],
            "esxi_hostname": "esx1",
            "folder": "/Datacenter/vm/Deploy",
            "force": true,
            "guest_id": null,
            "hardware": {},
            "hostname": "vcenter",
            "is_template": false,
            "linked_clone": false,
            "name": "spacewalk",
            "name_match": "first",
            "networks": [
                {
                    "gateway": "",
                    "ip": "",
                    "name": "VM Network",
                    "netmask": "",
                    "type": "dhcp"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",
            "template": "tempalte",
            "username": "administrator@vsphere.local",
            "uuid": null,
            "validate_certs": false,
            "wait_for_ip_address": true
        }
    },
    "msg": "Static IP information provided for network \"VM Network\", but \"type\" is set to \"dhcp\"."
}
        to retry, use: --limit @/etc/ansible/deploy-vms.retry

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
spacewalk                  : ok=1    changed=0    unreachable=0    failed=1
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@kizz1337 Thanks for reporting this issue. This is an additional input checks added to avoid wrong inputs and wrong assumptions.

You can do as following - 

```yaml
    - set_fact:
        my_network:
          - name: "{{ network }}"

    - set_fact:
        static_network: "{{ my_network[0]  | combine({ 'type': guest_network_type, 'ip': guest_custom_ip, 'netmask': guest_netmask, 'gateway': guest_gateway }) }}"
      when: guest_network_type is defined and guest_network_type == "static"

    - set_fact:
        static_network: "{{ my_network[0]  | combine({ 'type': guest_network_type }) }}"
      when: guest_network_type is defined and guest_network_type == "dhcp"

    - debug:
        msg: "{{ static_network }}"
```

Let me know your inputs on this.

**Comment by kizz1337** [comment]
Hello,

thanks for you time,

First, i've try with dhcp variable and network name 
```yaml
TASK [deploy-vmware-guest : set_fact] ******************************************
task path: /etc/ansible/git/roles/deploy-vmware-guest/tasks/main.yml:13
ok: [spacewalk] => {
    "ansible_facts": {
        "static_network": {
            "name": "Backbone",
            "type": "dhcp"
        }
    },
    "changed": false
}
```

Then try with static variables
```yaml
TASK [deploy-vmware-guest : set_fact] ******************************************
task path: /etc/ansible/git/roles/deploy-vmware-guest/tasks/main.yml:9
ok: [spacewalk] => {
    "ansible_facts": {
        "static_network": {
            "gateway": "192.168.1.1",
            "ip": "192.168.1.5",
            "name": "Backbone",
            "netmask": "255.255.255.0",
            "type": "static"
        }
    },
    "changed": false
}
```

This workarroud seem to work fine :)
Thanks you very much

For understanding, "combine" permit to create an array of variables and add them to the first variable "my_network", right ?
For deploying, network must be "static_network" ?
`````yaml
- name: create the VM
  vmware_guest:
    hostname: '{{ vmware_vcenter_hostname }}'
    username: '{{ vmware_vcenter_username }}'
    password: '{{ vmware_vcenter_password }}'
    validate_certs: no
    esxi_hostname: '{{ esxi_host }}'
    datacenter: '{{ vsphere_datacenter }}'
    folder: /{{ vsphere_datacenter }}/vm/{{ vsphere_folder }}
    name: '{{ inventory_hostname }}'
    state: poweredon
    networks: "{{ static_network }}"
```

**Comment by Akasurde** [comment]
@kizz1337 Yes. `combine` filter will allow you to merge or update existing hash/dictionary with new data. Yes, you can directly use `static_network` but `networks` requires list so your playbook will be - 

```yaml
- name: create the VM
  vmware_guest:
    hostname: '{{ vmware_vcenter_hostname }}'
    username: '{{ vmware_vcenter_username }}'
    password: '{{ vmware_vcenter_password }}'
    validate_certs: no
    esxi_hostname: '{{ esxi_host }}'
    datacenter: '{{ vsphere_datacenter }}'
    folder: /{{ vsphere_datacenter }}/vm/{{ vsphere_folder }}
    name: '{{ inventory_hostname }}'
    state: poweredon
    networks: 
      - "{{ static_network }}"
```
