### ISSUE TITLE
first_found lookup plugin does not resolve path to existing file

### ISSUE THREAD

**Issue by archf** [ansible/ansible#40685]
##### SUMMARY

The `first_found` lookup plugin does not expand to existing filepath.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

[first_found](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/first_found.py) lookup plugin.

##### ANSIBLE VERSION

```
archf@ltp > ansible --version
ansible 2.5.3
  config file = /home/archf/.ansible.cfg
  configured module search path = ['/home/archf/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
```

##### CONFIGURATION

```
archf@ltp > ansible-config dump --only-changed
ANSIBLE_NOCOWS(/home/archf/.ansible.cfg) = True
ANSIBLE_PIPELINING(/home/archf/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/archf/.ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=90s
CACHE_PLUGIN(/home/archf/.ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/archf/.ansible.cfg) = /tmp/facts.d
DEFAULT_GATHERING(/home/archf/.ansible.cfg) = smart
DEFAULT_MANAGED_STR(/home/archf/.ansible.cfg) = Ansible managed: {file} on {host}
DEFAULT_ROLES_PATH(/home/archf/.ansible.cfg) = ['/home/archf/w/gpb/roles']
RETRY_FILES_ENABLED(/home/archf/.ansible.cfg) = False
```

##### OS / ENVIRONMENT

```
archf@ltp > lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04 LTS
Release:        18.04
Codename:       bionic
```

##### STEPS TO REPRODUCE

I run this command given the `test_with_first_found.yml` playbook below.

`ansible-playbok -i "localhost," -c local test_with_first_found.yml`

```yaml
---
- hosts: all

  vars:
    user:
      name: archf
      authorized_keys:
        - id_rsa.pub

  tasks:

    - debug: msg={{item}}
      loop: "{{user['authorized_keys']|default([])}}"
      vars:
        key_dirs:
          - "/home/archf/.ssh"

    - debug: msg={{lookup('first_found', [item], key_dirs)}}
      loop: "{{user['authorized_keys']|default([])}}"
      vars:
        key_dirs:
          - "/home/archf/.ssh"

```

##### EXPECTED RESULTS

I expect the plugin to return the path to the file given it does exist.

```
archf@ltp ~ > l /home/archf/.ssh/id_rsa.pub
-rw-r--r-- 1 archf sysadm 400 Aug  9  2017 /home/archf/.ssh/id_rsa.pub
```

```
archf@ltp ~/r/i/ansible_2.5.0 > ap -i "localhost," -c local test_with_first_found.yml

PLAY [all] **********************************************************************************************

TASK [debug] ********************************************************************************************
ok: [localhost] => (item=None) => {
    "msg": "id_rsa.pub"
}

TASK [debug] ********************************************************************************************
ok: [localhost] => (item=None) => {
    "msg": "/home/archf/.ssh/id_rsa.pub"
}

TASK [debug] ********************************************************************************************
ok: [localhost] => (item=None) => {
    "msg": "/home/archf/.ssh/id_rsa.pub"
}

PLAY RECAP **********************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
##### ACTUAL RESULTS

```
archf@ltp ~/r/i/ansible_2.5.0 > ap -i "localhost," -c local test_with_first_found.yml

PLAY [all] **********************************************************************************************

TASK [debug] ********************************************************************************************
ok: [localhost] => (item=None) => {
    "msg": "id_rsa.pub"
}

TASK [debug] ********************************************************************************************
ok: [localhost] => (item=None) => {
    "msg": "/home/archf/.ssh"
}

TASK [debug] ********************************************************************************************
ok: [localhost] => (item=None) => {
    "msg": "/home/archf/.ssh"
}

PLAY RECAP **********************************************************************************************
localhost                  : ok=3    changed=0    unreachable=0    failed=0
```
