### ISSUE TITLE
k8s_raw module does not allow multiple Kubernetes objects in one file

### ISSUE THREAD

**Issue by geerlingguy** [ansible/ansible#40684]
##### SUMMARY

When using the `k8s_raw` module, if you feed it a document with multiple Kubernetes objects (e.g. a `Service` _and_ a `Deployment`, separated by the YAML document separator `---`), then the module will error out with `Error loading resource_definition: expected a single document in the stream`.

In the [Kubernetes Configuration Best Practices docs](https://kubernetes.io/docs/concepts/configuration/overview/), it's recommended to group all related objects in one file if possible:

> Group related objects into a single file whenever it makes sense. One file is often easier to manage than several. See the guestbook-all-in-one.yaml file as an example of this syntax.

The k8s_raw module should support deploying definition files with more than one object.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

k8s_raw

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/jeff.geerling/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

macOS 10.13.4 High Sierra - host
Raspbian 'Stretch' Lite - managed server

##### STEPS TO REPRODUCE

Kubernetes definition file, `files/drupal8.yml`:

```yaml
# Drupal 8 Service definition.
apiVersion: v1
kind: Service
metadata:
  name: drupal8
  labels:
    app: drupal8
spec:
  ports:
    - port: 80
  selector:
    app: drupal8
    tier: frontend
  type: NodePort
---
# Drupal 8 Deployment definition.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drupal8
  labels:
    app: drupal8
spec:
  selector:
    matchLabels:
      app: drupal8
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: drupal8
        tier: frontend
    spec:
      containers:
        - image: drupal:8
          name: drupal8
          env:
            - name: DRUPAL_DB_HOST
              value: drupal8-mysql
            - name: DRUPAL_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: drupal8-mysql-pass
                  key: password
          ports:
            - containerPort: 80
              name: drupal8
```

Playbook:

```yaml
- hosts: kubernetes
  become: yes

  tasks:
    ...
    - name: Deploy Drupal 8 K8s service to the cluster.
      k8s_raw:
        definition: "{{ lookup('file', 'files/drupal8.yml') | from_yaml }}"
        state: present
    ...
```

##### EXPECTED RESULTS

The `k8s_raw` module should apply all the definitions in the file, just like running `kubectl -f drupal8.yml` would do on the cluster itself using `kubectl`.

##### ACTUAL RESULTS

The module fails with the following message:

```
TASK [Deploy Drupal 8 Kubernetes services to the cluster.] *************************************************************
failed: [10.0.100.44] (item=drupal8.yml) => changed=false 
  item: drupal8.yml
  msg: |-
    Error loading resource_definition: expected a single document in the stream
      in "/root/drupal8.yml", line 2, column 1
    but found another document
      in "/root/drupal8.yml", line 15, column 1
```

The same failure happens if I:

  1. Copy the definition files to the server.
  2. Run the task using `src` instead of `definition` and a lookup (e.g. `src: "path/to/drupal8.yml"`).

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/_k8s_raw.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/_k8s_raw.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion @samdoran
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by geerlingguy** [comment]
Deprecated?

Workaround I'm using for now is:

```yaml
- name: Copy Kubernetes definition files to the cluster.
  copy:
    src: "files/{{ item }}"
    dest: "~/{{ item }}"
  with_items:
    - drupal8.yml
    - ...

- name: Apply Drupal 8 Kubernetes services to the cluster.
  command: kubectl apply -f ~/{{ item }}
  with_items:
    - drupal8.yml
    - ...
  register: drupal8_result
  changed_when: "'created' in drupal8_result.stdout"
  run_once: True
```

**Comment by fabianvf** [comment]
In Ansible 2.6 the k8s_raw (now k8s) module had a significant rewrite, it will support multiple documents in a file passed with `src`. I think the template lookup method still fails (looks like failure is from `from_yaml`, not the module), I'll look into allowing it as a string and working around it that way.

**Comment by geerlingguy** [comment]
@fabianvf - Ah, that explains it!

Hopefully we can stabilize on `k8s` for the foreseeable future ;)

I think the YAML library doesn't support reading in the file with multiple documents... but that's based on some fuzzy memory from searching around over the past day, so could be incorrect. If we can use it as a string that would be ideal (IMHO).

**Comment by fabianvf** [comment]
@geerlingguy yeah, some people interpreted `_raw` as "internal and dangerous", so we figured we'd make it more clear. `k8s_raw` and `openshift_raw` will still work, they're just aliased to `k8s`. I'll try to get a PR in tomorrow for the string thing.

**Comment by geerlingguy** [comment]
See related: https://github.com/ansible/ansible/issues/42476 — you still can't read a file in directly from the Ansible control machine with multiple definitions and feed it to the `k8s` module; you still get an error like:

```
ComposerError: expected a single document in the stream
  in "<unicode string>", line 2, column 1:
    apiVersion: v1
    ^
but found another document
  in "<unicode string>", line 7, column 1:
    ---
    ^

fatal: [master]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}

```

Therefore, Ansible 2.7 will introduce a new filter, `from_yaml_all`, which can be used like:

```yaml
- k8s:
    src: "{{ item }}"
  loop: "{{ lookup('template', 'path/to/template.yml') | from_yaml_all }}"
```

(At least I think.) For now, I'm just copying all the files with multiple definitions to the kubernetes master and running them there instead of parsing/passing the definition(s). It's just easier that way :(
