### ISSUE TITLE
to_yaml and to_nice_yaml has unexpected output and isn't maintaining var types

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#40687]
##### SUMMARY

If I use the to_yaml filter it will change some of my strings into ints and some strings dont have quotes around them.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

to_yaml
to_nice_yaml
##### ANSIBLE VERSION

```
ansible 2.4.3.0
  python version = 2.7.14 (default, Mar 21 2018, 16:45:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

vars file
```yaml
---
time_options:
        - name: "lifetime_hrs"
          description: "Number of hours the cluster will be up for"
          value: "06"
          values:
            - "01"
            - "02"
            - "03"
            - "04"
            - "05"
            - "06"
            - "07"
            - "08"
            - "09"
            - "10"
            - "11"
            - "12"
            - "13"
            - "14"
            - "15"
            - "16"
            - "17"
            - "18"
            - "19"
            - "20"
            - "21"
            - "22"
            - "23"
            - "24"
          enforced: "true"
```
template below
```yaml
{{ time_options|to_nice_yaml }}
```

##### EXPECTED RESULTS

```
-   description: 'Number of hours the cluster will be up for'
    enforced: 'true'
    name: 'lifetime_hrs'
    value: '06'
    values:
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    - '07'
    - '08'
    - '09'
    - '10'
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
    - '22'
    - '23'
    - '24'
```
##### ACTUAL RESULTS

Note that 08 and 09 dont have quotes around them.

```
-   description: Number of hours the cluster will be up for
    enforced: 'true'
    name: lifetime_hrs
    value: '06'
    values:
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    - '07'
    - 08
    - 09
    - '10'
    - '11'
    - '12'
    - '13'
    - '14'
    - '15'
    - '16'
    - '17'
    - '18'
    - '19'
    - '20'
    - '21'
    - '22'
    - '23'
    - '24'
```
