### ISSUE TITLE
"file" module should allow to set "content"

### ISSUE THREAD

**Issue by cjeanner** [ansible/ansible#40699]
##### SUMMARY

Currently, Ansible doesn't have a straight and easy way to set a file content: either template, or copy. It would be great if we could just set its content through the "file" module

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

file

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cjeanner/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

```

##### CONFIGURATION

"vanilla" ansible

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

This feature could be handy when we want to set file content from fact without having to make a template for a plain file.

```yaml
file:
  path: /tmp/foo
  content: "blahblah"
  group: bar
  mode: 0440
  owher: bar

file:
  path: /tmp/foo2
  content:
    - "{{fact1}}"
    - "{{fact2}}"
    - "well this is great isn't it?"
  group: bar
  mode: 0440
  owher: bar
```

##### EXPECTED RESULTS

in the first example, a file located in /tmp/foo shoud be created with the rights/ownership, and contain only "blahblah" with a new line.
In the second example, a file located in /tmp/foo2 should be created with the rights/ownership, and contain:
```
fact1_value
fact2_value
well this is great isn't it?
```

##### ACTUAL RESULTS

N/A

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/file.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/file.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
I am failing to see why is `copy` not sufficient http://docs.ansible.com/ansible/latest/modules/copy_module.html:
```
- name: Copy using the 'content' for inline data
  copy:
    content: '# This file was moved to /etc/other.conf'
    dest: /etc/mine.conf'
```

needs_info
