### ISSUE TITLE
nxos_vlan - failed to create VLAN in N5K without FabricPath

### ISSUE THREAD

**Issue by jguirlinger** [ansible/ansible#40705]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nxos_vlan

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/srv/home/guirlinger_j/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/ansible
  executable location = /opt/rh/rh-python36/root/usr/bin/ansible
  python version = 3.6.3 (default, Jan  9 2018, 10:19:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

Default
##### OS / ENVIRONMENT

Ansible run from : Red Hat Enterprise Linux Server release 7.4 (Maipo)
Target device : cisco Nexus 5696 runnning NXOS 7.2(1)N1(1) **with no FabricPath feature**

##### STEPS TO REPRODUCE

Simple playbook for creating VLANs on Nexus 5596 switches

```yaml
---
- hosts: nexus5596-lab
  gather_facts: False

vars:
    VLANs :
      - { vlan_id: 1, name: "default" }
      - { vlan_id: 3504, name: "test_ansible1" }
      - { vlan_id: 3505, name: "test_ansible2" }
      - { vlan_id: 3506, name: "test_ansible3" }  

  tasks:
    - name: create VLANs on lab Switches
      nxos_vlan:
        aggregate:
          "{{ VLANs }}"
        purge: yes
```

##### EXPECTED RESULTS

VLANs should be created on switches

##### ACTUAL RESULTS

The playbook fails on first attempt, because nxos_vlan try to pass the command *mode ce* under the vlan

```
TASK [create VLANs on lab Switches] **********************************************************************************************************************************************************************************************
fatal: [labswitch2]: FAILED! => {"changed": false, "msg": "mode ce\r\r\n                                 ^\r\n% Invalid command at '^' marker.\r\n\rlabswitch2(config-vlan)# "}
fatal: [labswitch1]: FAILED! => {"changed": false, "msg": "mode ce\r\r\n                                 ^\r\n% Invalid command at '^' marker.\r\n\rlabswitch1(config-vlan)# "}

```

Only the first VLAN is created and then the play fails because of the commande "mode ce" which is not supported.

The problem is that nxos_vlan only check if the plateform is either 5k or 7k to know if the command *mode ce* is supported

```python
    if any(i in os_platform for i in ['5K', '7K']):
        mode = w['mode']
    else:
        w['mode'] = None
```

But this is not sufficient, as far as i know, you must have the feature-set fabricpath installed

IMO, there is no need to execute *mode ce* on VLAN creation, especially when this value is not specified in the playbook.
CE is the default mode on Cisco switches when creating a VLAN
