### ISSUE TITLE
command module declares `delta` attributes to be always returned, but it is not

### ISSUE THREAD

**Issue by gtema** [ansible/ansible#40711]
##### SUMMARY
The command module declares `delta` attributes to be always returned, but it is not filled, if due to the internal logic execution was skipped ('creates' exists or 'removes' does not). This leads to problems in callback modules, which assume permanent presence of this attribute. The same is valid for `start` and `end`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
command

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/gtema/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
---
- name: test command i/f
  hosts: localhost
  tasks:
    - name: create temp file
      file:
        path: test
        state: touch
....
    - name: invoke command module
      command: touch test
      args:
        creates: test
      register: output
....
    - name: validate the result
      assert:
        that:
          - output.delta is defined
```

##### EXPECTED RESULTS

playbook does not fail and command module return delta as declared in the i/f documentation always

##### ACTUAL RESULTS

```
...
TASK [validate the result] ******************************************************************************************************************************************************************************************************************
task path: /home/gtema/workspace/test.yaml:16
fatal: [localhost]: FAILED! => {
    "assertion": "output.delta is defined", 
    "changed": false, 
    "evaluated_to": false
}

```

As an outcome of discussion in ansible-devel IRC I'm opening the bug with intention to fix the issue by returning `delta`, `start`, `end` instead of changing interface as returning: changed
