### ISSUE TITLE
yum: add diff mode

### ISSUE THREAD

**Issue by wookietreiber** [ansible/ansible#40710]
##### SUMMARY

**yum** module has no diff mode.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

yum

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /home/user/projects/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

```
ANSIBLE_NOCOWS(/home/user/projects/ansible/ansible.cfg) = True
CACHE_PLUGIN(/home/user/projects/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/home/user/projects/ansible/ansible.cfg) = ~/.ansible-cache
CACHE_PLUGIN_TIMEOUT(/home/user/projects/ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/home/user/projects/ansible/ansible.cfg) = 50
DEFAULT_GATHERING(/home/user/projects/ansible/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/user/projects/ansible/ansible.cfg) = [u'/home/user/projects/ansible/hosts']
DEFAULT_ROLES_PATH(/home/user/projects/ansible/ansible.cfg) = [u'/home/user/projects/ansible/roles']
MAX_FILE_SIZE_FOR_DIFF(/home/user/projects/ansible/ansible.cfg) = 0
RETRY_FILES_ENABLED(/home/user/projects/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

- CentOS release 6.9 (Final)
- Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### STEPS TO REPRODUCE

**yum** module with diff mode `-D` enabled on the **ansible** or **ansible-playbook** command line.

An ad-hoc playbook to update ansible and related packages:

```yaml
---

- name: update ansible distro packages
  hosts: managers
  remote_user: root

  tasks:

    - name: update ansible
      yum:
        pkg: '{{ os_update_ansible_packages | join(",") }}'
        state: latest

  vars:
    os_update_ansible_packages:
      - ansible
      - ansible-doc
      - ansible-lint
      - ansible-inventory-grapher

...
```

##### EXPECTED RESULTS

I expected the **yum** module to show the versions of the old packages and the versions of the new packages. Also, the module should show packages that have been removed and packages that have been added. This could look like:

```console
$ ansible-playbook -CD ad-hoc/update-ansible.yml
...
TASK [update ansible] ****************************************************************
ansible-2.5.1 -> ansible-2.5.2
ansible-doc-2.5.1 -> ansible-doc-2.5.2
changed: [a]
ansible-2.5.1 -> ansible-2.5.2
ansible-doc-2.5.1 -> ansible-doc-2.5.2
changed: [b]
ansible-2.5.1 -> ansible-2.5.2
ansible-doc-2.5.1 -> ansible-doc-2.5.2
changed: [c]
ansible-2.5.1 -> ansible-2.5.2
ansible-doc-2.5.1 -> ansible-doc-2.5.2
changed: [d]
...
```

##### ACTUAL RESULTS

```console
$ ansible-playbook -CD ad-hoc/update-ansible.yml
...
TASK [update ansible] ****************************************************************
changed: [a]
changed: [b]
changed: [c]
changed: [d]
...
```

---

**Note:** I can confirm this feature is not in HEAD yet, because I checked the source code and `diff` is not set in `exit_json`.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/yum.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @berenddeschouwer @kustodian @mkrizek @verm666
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jeff-cook** [comment]
Having the same issue. I want to see what will change when running --check and --diff. 

Here is my work around. 

```yaml
- name: update ansible distro packages
  hosts: managers
  remote_user: root

  tasks:
    - name: update ansible
      yum:
        pkg: ansible
        state: latest
      register: yum_diff
     notify: display yum diff
 
  handlers:
  - name: display yum diff
    debug:
      var: yum_diff.changes
    changed_when: yum_diff.changed
```
