### ISSUE TITLE
wait_for causes high CPU usage

### ISSUE THREAD

**Issue by protondrift** [ansible/ansible#40714]
##### SUMMARY

Hi guys, i was getting 100% percent CPU usage while using wait_for to wait until hosts port avalible, anything wrong with my scripts? 
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Nov 20 2015, 02:00:19) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### CONFIGURATION
`default config, nothing add`

##### OS / ENVIRONMENT
CENTOS 7.2

##### STEPS TO REPRODUCE

```
  handlers:
    - name: check app
      wait_for:
        host: '{{ instance_Id }}'
        port: '{{ app_port }}'
        state: started         # Port should be open
        delay: 30               # No wait before first check (sec)
        timeout: 60             # Stop checking after timeout (sec)
```

##### ACTUAL RESULTS

![image](https://user-images.githubusercontent.com/3354662/40548485-789f11d4-6067-11e8-88bf-ee993c0af269.png)
