### ISSUE TITLE
cloudfront_distribution_module fails on new required parameter

### ISSUE THREAD

**Issue by kenwdelong** [ansible/ansible#40724]
It appears that AWS has added a new required parameter to the cloudfront APIs.

##### SUMMARY

Running a playbook with the cloudfront_distribution_module fails.  It was working as recently as May 14.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

cloudfront_distribution_module

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /home/kdelong/hatch-devops/ansible/ansible.cfg
  configured module search path = [u'/home/kdelong/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Jan 31 2018, 00:17:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

no env vars: `env | grep ANSIBLE` is empty

##### OS / ENVIRONMENT

Amazon Linux 2017.09

##### STEPS TO REPRODUCE

```yaml
    - name: create Cloudfront distribution
      cloudfront_distribution:
        state: present
        alias: "{{ item.alias }}"
        default_root_object: index.html
        origins:
            - id: "{{ item.origin_id }}"
              domain_name: "{{ item.domain_name }}"
              origin_path: ''
              s3_origin_access_identity_enabled: yes
        default_cache_behavior:
          target_origin_id: "{{ item.origin_id }}"
          viewer_protocol_policy: redirect-to-https
          allowed_methods:
            items:
              - GET
              - HEAD
            cached_methods:
              - GET
              - HEAD
          forwarded_values:
            query_string: false
            cookies:
              forward: none
          smooth_streaming: false
          compress: false
        custom_error_responses:
          - error_code: 403
            response_page_path: '/index.html' 
            response_code: 200
            error_caching_min_ttl: 300
        logging:
          enabled: true
          include_cookies: false
          bucket: hatch-logs.s3.amazonaws.com
          prefix: "{{ item.log_prefix }}"
        enabled: true
        price_class: PriceClass_100
        viewer_certificate:
          acm_certificate_arn: arn:aws:acm:us-east-1:1234567890:certificate/XXX
          minimum_protocol_version: TLSv1.1_2016
          ssl_support_method: sni-only
        http_version: http2
        ipv6_enabled: yes
      register: cf
      loop:
        - alias: ourdomain.ourco.com
          origin_id: S3-our-origin
          domain_name: our-bucket.s3.amazonaws.com
          log_prefix: sub-web-cloudfront/prod/
```
Etc, there are more items in the loop, they all fail with the identical message

##### EXPECTED RESULTS

Task should succeed. It was working on May 14, which is when I wrote and tested this playbook.

##### ACTUAL RESULTS

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: InvalidArgument: An error occurred (InvalidArgument) when calling the UpdateDistribution operation: The parameter Field level encryption id is required.
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/cloud/amazon/cloudfront_distribution.py
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/kdelong/.ansible/tmp/ansible-tmp-1527269181.25-141910903271774 `" && echo ansible-tmp-1527269181.25
-141910903271774="` echo /home/kdelong/.ansible/tmp/ansible-tmp-1527269181.25-141910903271774 `" ) && sleep 0'
<127.0.0.1> PUT /home/kdelong/.ansible/tmp/ansible-local-316195O2hYZ/tmptVNofO TO /home/kdelong/.ansible/tmp/ansible-tmp-1527269181.25-141910903271774/cloudfront_dis
tribution.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/kdelong/.ansible/tmp/ansible-tmp-1527269181.25-141910903271774/ /home/kdelong/.ansible/tmp/ansible-tmp-1527269181.25-141
910903271774/cloudfront_distribution.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python2.7 /home/kdelong/.ansible/tmp/ansible-tmp-1527269181.25-141910903271774/cloudfront_distribution.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /home/kdelong/.ansible/tmp/ansible-tmp-1527269181.25-141910903271774/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_OmI3VZ/ansible_module_cloudfront_distribution.py", line 1190, in update_distribution
    return client.update_distribution(DistributionConfig=config, Id=distribution_id, IfMatch=e_tag)['Distribution']
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
InvalidArgument: An error occurred (InvalidArgument) when calling the UpdateDistribution operation: The parameter Field level encryption id is required.

failed: [localhost] (item={u'alias': u'ourdomain.ourco.com', u'log_prefix': u'sub-web-cloudfront/prod/', u'domain_name': u'our-bucket.s3.amazonaws.com', u'
origin_id': u'S3-our-origin'}) => {
    "changed": false,
    "error": {
        "code": "InvalidArgument",
        "message": "The parameter Field level encryption id is required.",
        "type": "Sender"
    },
    "invocation": {
        "module_args": {
            "alias": "ourdomain.ourco.com",
            "aliases": [
                "ourdomain.ourco.com"
            ],
            "aws_access_key": null,
            "aws_secret_key": null,
            "cache_behaviors": null,
            "caller_reference": null,
            "comment": null,
            "custom_error_responses": [
                {
                    "error_caching_min_t_t_l": 300,
                    "error_code": 403,
                    "response_code": "200",
                    "response_page_path": "/index.html"
                }
            ],
            "default_cache_behavior": {
                "allowed_methods": {
                    "cached_methods": {
                        "items": [
                            "HEAD",
                            "GET"
                        ],
                        "quantity": 2
                    },
                    "items": [
                        "HEAD",
                        "GET"
                    ],
                    "quantity": 2
                },
                "compress": false,
                "default_t_t_l": 86400,
                "forwarded_values": {
                    "cookies": {
                        "forward": "none"
                    },
                    "headers": {
                        "quantity": 0
                    },
                    "query_string": false,
                    "query_string_cache_keys": {
                        "quantity": 0
                    }
                },
                "lambda_function_associations": {
                    "quantity": 0
                },
                "max_t_t_l": 31536000,
                "min_t_t_l": 0,
                "smooth_streaming": false,
                "target_origin_id": "S3-my-bucket",
                "trusted_signers": {
                    "enabled": false,
                    "quantity": 0
                },
                "viewer_protocol_policy": "redirect-to-https"
            },
            "default_origin_domain_name": null,
            "default_origin_path": null,
            "default_root_object": "index.html",
            "distribution_id": null,
            "e_tag": null,
            "ec2_url": null,
            "enabled": true,
            "http_version": "http2",
            "ipv6_enabled": true,
            "logging": {
                "bucket": "our-logs.s3.amazonaws.com",
                "enabled": true,
                "include_cookies": false,
                "prefix": "sub-web-cloudfront/prod/"
            },
            "origins": [
                {
                    "custom_headers": {
                        "quantity": 0
                    },
                    "domain_name": "our-bucket.s3.amazonaws.com",
                    "id": "S3-our-origin",
                    "origin_path": "",
                    "s3_origin_config": {
                        "origin_access_identity": "origin-access-identity/cloudfront/XXX"
                    }
                }
            ],
            "price_class": "PriceClass_100",
            "profile": null,
            "purge_aliases": false,
            "purge_cache_behaviors": false,
            "purge_custom_error_responses": false,
            "purge_origins": false,
            "purge_tags": false,
            "region": null,
            "restrictions": null,
            "security_token": null,
            "state": "present",
            "tags": {},
            "validate_certs": true,
            "viewer_certificate": {
                "a_c_m_certificate_arn": "arn:aws:acm:us-east-1:1234567890:certificate/XXX",
                "minimum_protocol_version": "TLSv1.1_2016",
                "s_s_l_support_method": "sni-only"
            },
            "wait": false,
            "wait_timeout": 1800,
            "web_acl_id": null
        }
    },
    "item": {
        "alias": "ourdomain.ourco.com",
        "domain_name": "our-bucket.s3.amazonaws.com",
        "log_prefix": "sub-web-cloudfront/prod/",
        "origin_id": "S3-our-origin"
    },
    "msg": "Error updating distribution to {u'Comment': '', u'Restrictions': {u'GeoRestriction': {u'RestrictionType': 'none', u'Quantity': 0}}, u'Logging': {'Enabled': True, 'Prefix': 'sub-web-cloudfront/prod/', 'Bucket': 'our-logs.s3.amazonaws.com', 'IncludeCookies': False}, u'WebACLId': '', u'Origins': {'Items': [{'OriginPath': '', 'CustomHeaders': {'Quantity': 0}, 'S3OriginConfig': {'OriginAccessIdentity': 'origin-access-identity/cloudfront/XXX'}, 'Id': 'S3-our-origin', 'DomainName': 'our-bucket.s3.amazonaws.com'}], 'Quantity': 1}, u'PriceClass': 'PriceClass_100', u'DefaultRootObject': 'index.html', u'Enabled': True, u'DefaultCacheBehavior': {'TrustedSigners': {'Enabled': False, 'Quantity': 0}, 'LambdaFunctionAssociations': {u'Quantity': 0}, 'TargetOriginId': 'S3-our-origin', 'ViewerProtocolPolicy': 'redirect-to-https', 'ForwardedValues': {'Headers': {'Quantity': 0}, 'Cookies': {'Forward': 'none'}, 'QueryStringCacheKeys': {'Quantity': 0}, 'QueryString': False}, 'MaxTTL': 31536000, 'SmoothStreaming': False, 'DefaultTTL': 86400, 'AllowedMethods': {u'Items': ['HEAD', 'GET'], u'Quantity': 2, u'CachedMethods': {u'Items': ['HEAD', 'GET'], u'Quantity': 2}}, 'MinTTL': 0, 'Compress': False}, u'IsIPV6Enabled': True, u'ViewerCertificate': {u'SSLSupportMethod': 'sni-only', u'MinimumProtocolVersion': 'TLSv1.1_2016', u'ACMCertificateArn': 'arn:aws:acm:us-east-1:1234567890:certificate/XXX', u'Certificate': 'arn:aws:acm:us-east-1:1234567890:certificate/XXX', u'CertificateSource': 'acm'}, u'CustomErrorResponses': {'Items': [{'ErrorCode': 403, 'ResponsePagePath': '/index.html', 'ResponseCode': '200', 'ErrorCachingMinTTL': 300}], 'Quantity': 1}, u'Aliases': {'Items': ['ourdomain.ourco.com'], 'Quantity': 1}, u'CallerReference': '1519340531311', u'CacheBehaviors': {'Quantity': 0}, u'HttpVersion': 'http2'}: An error occurred (InvalidArgument) when calling the UpdateDistribution operation: The parameter Field level encryption id is required.",
    "response_metadata": {
        "http_headers": {
            "connection": "close",
            "content-length": "301",
            "content-type": "text/xml",
            "date": "Fri, 25 May 2018 17:26:22 GMT",
            "x-amzn-requestid": "be68c1fd-6040-11e8-b867-bd8b2f06ee63"
        },
        "http_status_code": 400,
        "request_id": "be68c1fd-6040-11e8-b867-bd8b2f06ee63",
        "retry_attempts": 0
    }
}
```

I have also opened an issue with AWS: this is actually their bug for adding a new required parameter to the API.
