### ISSUE TITLE
Ansible proxy handling seems buggy

### ISSUE THREAD

**Issue by cfasnacht** [ansible/ansible#40827]
##### SUMMARY

Ansible no_proxy variable is buggy

##### ISSUE TYPE
If a http_proxy is set Ansible always uses this proxy to connect to URLs even if it should not because the domain is in the no_proxy list. 

Linux environment variable are the following:
http_proxy=http://x.x.x.x:8080
https_proxy=http://x.x.x.x:8080
no_proxy=localhost,127.0.0.1,localaddress,.localdomain.com,.example.com

Curl works in both cases:
curl http://repo.example.com/aptly_pubkey.msc
curl --noproxy "*" http://repo.example.com/aptly_pubkey.msc

##### COMPONENT NAME

I have the same issue with: apt_key, uri and get_url

##### ANSIBLE VERSION

Affects all Ansible versions I tested from 2.4 to 2.7 dev.
```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/taafach5/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
```
ansible 2.7.0dev0
  config file = /home/taafach5/code/ansible-infra-services/ansible.cfg
  configured module search path = [u'/home/taafach5/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/home/user/code/ansible-infra-services/ansible.cfg) = True
DEFAULT_FORKS(/home/user/code/ansible-infra-services/ansible.cfg) = 5
DEFAULT_HOST_LIST(/home/user/code/ansible-infra-services/ansible.cfg) = [u'/home/user/code/ansible-infra-services/inventory']
DEFAULT_ROLES_PATH(/home/user/code/ansible-infra-services/ansible.cfg) = [u'/home/user/code/ansible-infra-services/roles', u'/home/user/code/ansible-infra-services/galaxy']
DEFAULT_TRANSPORT(/home/user/code/ansible-infra-services/ansible.cfg) = smart
HOST_KEY_CHECKING(/home/user/code/ansible-infra-services/ansible.cfg) = False

##### OS / ENVIRONMENT

Ubuntu 16.04 and 18.04

##### STEPS TO REPRODUCE

```yaml
  tasks:
    - name: add repo key
      apt_key:
        id: 76B3F85E
        url: http://repo.example.com/aptly_pubkey.msc
        state: present
      environment:
        no_proxy: .example.com
        http_proxy: 'http://x.x.x.x:8080'
```
Correctly working are the following examples:
```yaml
      environment:
        no_proxy: repo.example.com
```
```yaml
      environment:
        http_proxy: ""
```

##### EXPECTED RESULTS

That Ansible connects to the URL without going through the proxy.

##### ACTUAL RESULTS

```
fatal: [testserver.example.com]: FAILED! => {"changed": false, "msg": "Failed to download key at http://repo.example.com/aptly_pubkey.msc: HTTP Error 403: Forbidden"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/get_url.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/get_url.py)
* [lib/ansible/modules/packaging/os/apt_key.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/apt_key.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jpmens @jvantuyl
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @ptux
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ptux** [comment]
This is NOT a bug.

You'd better check following.
>  HTTP Error 403: Forbidden

## my test

 ansible-playbook i40827.yml -i host
```
PLAY [t1-malts-231] ********************

TASK [download] ************************
changed: [t1-malts-231]
```

-  i40827.yml

```
- hosts: t1-malts-231
  become: true
  gather_facts: false
  tasks:
      - name: download
        get_url:
          url: https://geturl.malts.tk/index.html
          dest: /tmp/index.html
          mode: 0744
        environment:
          no_proxy: .malts.tk
          https_proxy: 'http://example.com:3128'
```

**Comment by cjeanner** [comment]
Hello,
So, I have the same kind of issue, using the [uri](https://docs.ansible.com/ansible/latest/modules/uri_module.html#uri-module) module.

Here's what I'm doing:
- have a squid proxy on some computer
- run ansible-playbook with ```http_proxy```, ```https_proxy``` and ```no_proxy``` exported in my user env
- in a role included by this playbook, just call the ```uri``` module hitting an address listed in the no_proxy

Current result: ```uri``` uses the proxy sets in http_proxy (or https_proxy), and doesn't comply to the no_proxy

Intended result: ```uri``` should comply to the no_proxy directive exporter in the user env

An example:
```Bash
export http_proxy="http://10.10.0.134:3128"
export https_proxy="http://10.10.0.134:3128"
export no_proxy="127.0.0.0/8,192.168.0.0/16,localhost"
ansible-playbook -i <inventory> foo.yaml
```
foo.yaml:
```YAML
- hosts: all
  roles:
    - uri_proxy
```
uri_proxy/main.yaml:
```YAML
- name: blah
  uri:
    url: http://127.0.0.1:8080/
```

If you run this (with some web server listening on 8080), you will see in your squid logs entries showing the ```uri``` actually uses the proxy, while the host is listed in the no_proxy directive…
