### ISSUE TITLE
ios_facts: Tunnel interface MAC address shows IP address/Prefix

### ISSUE THREAD

**Issue by jvanderaa** [ansible/ansible#40829]
##### SUMMARY

When running ios_facts to gather information on interfaces, a tunnel interface MAC address shows up as a IP address/prefix, such as `10.10.10.1/30` instead of null

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_facts

##### ANSIBLE VERSION

```
ansible --version
ansible 2.5.3
  config file = ../Documents/Ansible/ansible.cfg
  configured module search path = [u'../Documents/Ansible/library']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(../Documents/Ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=
DEFAULT_MODULE_PATH(/Users/jvanderaa/Documents/Ansible/ansible.cfg) = [u'../Documents/Ansible/library']
HOST_KEY_CHECKING(../Documents/Ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

MacOS --> IOS

##### STEPS TO REPRODUCE

```yaml
- name: Check facts
  connection: network_cli
  hosts: ios
  gather_facts: no
  become: yes
  become_method: enable

  tasks:
    - name: IOS>> Get facts
      ios_facts:
        gather_subset: all

    - name: DEBUG>> Print facts
      debug:
        msg: "{{ ansible_net_interfaces }}"
```

##### EXPECTED RESULTS

The information looks correct on physical interfaces. Virtual tunnel interfaces (`interface tunnel`) shows information that shouldn't be there.

##### ACTUAL RESULTS

```
        "GigabitEthernet0/2": {
            "bandwidth": 1000000,
            "description": "Trunk to sw01 (Gi1/0/48)",
            "duplex": "Full",
            "ipv4": [],
            "lineprotocol": "up ",
            "macaddress": "a0e0.afbe.cf82",
            "mediatype": "RJ45",
            "mtu": 1500,
            "operstatus": "up",
            "type": "CN Gigabit Ethernet"
        },
        "Tunnel1110": {
            "bandwidth": 100,
            "description": "IPSec VTI",
            "duplex": null,
            "ipv4": [
                {
                    "address": "10.10.10.2",
                    "subnet": "30"
                }
            ],
            "lineprotocol": "up ",
            "macaddress": "10.10.10.2/30",
            "mediatype": null,
            "mtu": 17878,
            "operstatus": "up",
            "type": null
        }

```
