### ISSUE TITLE
Azure azure_rm_functionapp and FUNCTIONS_EXTENSION_VERSION

### ISSUE THREAD

**Issue by vpopescu** [ansible/ansible#40857]
##### SUMMARY
Need to support setting runtime version. Currently it defaults to runtime ~1, and should be able to select runtime beta as well (and in the future, additional runtimes)

Using the playbook below causes a 409/Conflict error. But I don't think this is the right way of doing it anyway, Microsoft seems to suggest that the app needs to be fully created, then the runtime changed from ~1 to beta using 'az functionapp config appsettings' So the creation would have to be followed by an update. https://docs.microsoft.com/en-us/azure/azure-functions/set-runtime-version

So we need probably a runtime: playbook entry that would translate into a az functionapp config when the functionapp is succesfully created.

But I am very new at ansible so I may be missing something obvious?

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_functionapp

##### ANSIBLE VERSION

```
2.5.2
```

##### OS / ENVIRONMENT

Windows, with Ubuntu subsystem.

##### STEPS TO REPRODUCE

Create a new resource group in azure.
Create a resource group mygrouptest123
Create a storage account mystorageaccount123
Attempt to create a function app, using the playbook entry below.

```yaml
- name: "Bad example, since probably cannot set runtime at creation time"
      azure_rm_functionapp:
        resource_group: mygrouptest123
        name: myfunctionapptest123
        storage_account: "mystorageaccount123
        app_settings:
             FUNCTIONS_EXTENSION_VERSION: beta
```

##### EXPECTED RESULTS
The function app is created, and the runtime is set to 'beta'.
Incidentally, rm_azure_functionapp_facts should also query the runtime

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating web app: 409 Client 
Error: Conflict for url: https://management.azure.com/subscriptions/...redacted.../resourceGroups/mygrouptest123/providers/Microsoft.Web/sites/myfunctionapptest123?api-version=2016-08-01"}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/azure/azure_rm_functionapp.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/azure/azure_rm_functionapp.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @tstringer
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Fred-sun** [comment]
Hi @vpopescu ,I have tried your YML, Meet same problem. Your mean, we need add FUNCTIONS_EXTENSION_VERSION option at azure_rm_functionapp, We can use this option to control the app version .Please confirm,  Thanks a lot!

**Comment by vpopescu** [comment]
Keep in mind I'm a beginer with Ansible, soI may not be able to make the best suggestions.

I imagine a field, something like:

```yaml
- name: create a function app with app settings
  azure_rm_functionapp:
      ...
      runtime: ~1   
     ...
```
Anyway, I think your understanding is basically correct, you need to control the runtime via FUNCTION_EXTENSION_VERSION, as discussed in the microsoft link I put in the bug report. The problem was that you cannot set FUNCTION_EXTENSION_VERSION at creation time, you need to set it after creation.

But maybe the REST API doesn't have that limitation. Where is the documentation for the Azure REST API?
