### ISSUE TITLE
Support SID in win_user_right module to handle localized Windows versions

### ISSUE THREAD

**Issue by jamessemai** [ansible/ansible#40867]
##### SUMMARY
The current win_user_right module requires users to be specified by name.
This is a problem when managing a mix of localized and non-localized Windows versions, where these names might be different. E.g. 'Administrator' vs 'Administrateur'. 

Compare https://support.microsoft.com/en-us/help/243330/well-known-security-identifiers-in-windows-operating-systems and https://support.microsoft.com/fr-fr/help/243330/well-known-security-identifiers-in-windows-operating-systems for more examples.

##### ISSUE TYPE
I propose to support specifying the user security identifier (SID) directly, since this one is independent of any localization.

##### COMPONENT NAME
win_user_right

##### ANSIBLE VERSION
```
ansible 2.5.2
  config file = /home_local/ansible/automation/ansible.cfg
  configured module search path = [u'/home_local/ansible/automation/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]`
```

##### EXAMPLE

```yaml
- name: replace the entries of Deny log on locally
  win_user_right:
    name: SeDenyInteractiveLogonRight
    users:
    - S-1-5-21
    - S-1-5-32-545
    action: set
```

Above has the same results as the following task, but also supports localized Windows versions:

```yaml
- name: replace the entries of Deny log on locally
  win_user_right:
    name: SeDenyInteractiveLogonRight
    users:
    - Guest
    - Users
    action: set
```
