### ISSUE TITLE
lxd_container do not contain addresses in results

### ISSUE THREAD

**Issue by vikrantrathore** [ansible/ansible#40868]
##### SUMMARY
When launching a lxd container using lxd_container module with registered variable. In the results it should contain addresses, but it does not. I checked the created container it does have ipv4 address.

##### ISSUE TYPE
- Bug report
##### COMPONENT NAME

lxd_container

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/x/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
ansible python module location = /Users/x/.local/share/virtualenvs/infrastructure-Tqtsi3VA/lib/python2.7/site-packages/ansible
  executable location = /Users/x/.local/share/virtualenvs/infrastructure-Tqtsi3VA/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### OS / ENVIRONMENT
GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)
##### STEPS TO REPRODUCE
```yaml
- name: Start a new base container
      lxd_container:
        name: basecontainer
        state: started
        url: unix:/var/snap/lxd/common/lxd/unix.socket
        source:
          type: image
          alias: "ubuntu"
        profiles: ['default']
        wait_for_ipv4_addresses: True
      register: basecontainer
- name: Test information
      debug:
        msg:
           "System working its details are {% for key, value in basecontainer.iteritems() %} {{ key }} - {{ value }}  {% endfor %}"
```

##### EXPECTED RESULTS
The result should contain **addresses** in the output

##### ACTUAL RESULTS
It does not have **addresses** in the output. Only has 
```
ok: [testhost] => {
    "msg": "System working its details are  old_state - absent  failed - False  changed - True   actions - [u'create', u'start']   log_verbosity - 0  "
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/lxd/lxd_container.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/lxd/lxd_container.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @hnakamur
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by atomlab** [comment]
I have the same issue but only if inside LXD container running another LXD container

**Comment by atomlab** [comment]
I do direct request to LXD API. And all it's ok.

*containers/<container_name>/metadata*

> curl --cert /root/snap/lxd/12317/.config/lxc/client.crt --key /root/snap/lxd/12317/.config/lxc/client.key  -k https://localhost:9999/1.0/containers/jenkins-slave-01/metadata

output

> {"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"architecture":"amd64","creation_date":1571471548,"expiry_date":1574063548,"properties":{"architecture":"amd64","description":"Ubuntu bionic amd64 (cloud) (20191019_07:42)","name":"ubuntu-bionic-amd64-cloud-20191019_07:42","os":"ubuntu","release":"bionic","serial":"20191019_07:42","variant":"cloud"},"templates":{"/etc/hostname":{"when":["create","copy"],"create_only":false,"template":"hostname.tpl","properties":{}},"/etc/hosts":{"when":["create","copy"],"create_only":false,"template":"hosts.tpl","properties":{}},"/var/lib/cloud/seed/nocloud-net/meta-data":{"when":["create","copy"],"create_only":false,"template":"cloud-init-meta-data.tpl","properties":{}},"/var/lib/cloud/seed/nocloud-net/network-config":{"when":["create","copy"],"create_only":false,"template":"cloud-init-network-config.tpl","properties":{}},"/var/lib/cloud/seed/nocloud-net/user-data":{"when":["create","copy"],"create_only":false,"template":"cloud-init-user-data.tpl","properties":{"default":"#cloud-config\n{}"}},"/var/lib/cloud/seed/nocloud-net/vendor-data":{"when":["create","copy"],"create_only":false,"template":"cloud-init-vendor-data.tpl","properties":{"default":"#cloud-config\n{}"}}}}}


*containers/<container_name>/state*

> curl --cert /root/snap/lxd/12317/.config/lxc/client.crt --key /root/snap/lxd/12317/.config/lxc/client.key  -k https://localhost:9999/1.0/containers/jenkins-slave-01/state

output

>  {"type":"sync","status":"Success","status_code":200,"operation":"","error_code":0,"error":"","metadata":{"status":"Running","status_code":103,"disk":{},"memory":{"usage":8241532928,"usage_peak":16000000000,"swap_usage":0,"swap_usage_peak":0},"network":{"eth0":{"addresses":[{"family":"inet","address":"10.0.7.107","netmask":"24","scope":"global"},{"family":"inet6","address":"fe80::216:3eff:fed9:55b4","netmask":"64","scope":"link"}],"counters":{"bytes_received":75680840808,"bytes_sent":18629216639,"packets_received":13556459,"packets_sent":9037453},"hwaddr":"00:16:3e:d9:55:b4","host_name":"veth7fad15f4","mtu":1500,"state":"up","type":"broadcast"},"lo":{"addresses":[{"family":"inet","address":"127.0.0.1","netmask":"8","scope":"local"},{"family":"inet6","address":"::1","netmask":"128","scope":"local"}],"counters":{"bytes_received":4107583,"bytes_sent":4107583,"packets_received":48125,"packets_sent":48125},"hwaddr":"","host_name":"","mtu":65536,"state":"up","type":"loopback"},"lxdbr0":{"addresses":[{"family":"inet","address":"10.182.176.1","netmask":"24","scope":"global"},{"family":"inet6","address":"fe80::a094:32ff:fe25:de84","netmask":"64","scope":"link"}],"counters":{"bytes_received":626867744,"bytes_sent":62674978136,"packets_received":6731323,"packets_sent":10473058},"hwaddr":"26:34:e7:ac:a1:e9","host_name":"","mtu":1500,"state":"up","type":"broadcast"},"veth2c21ec59":{"addresses":[{"family":"inet6","address":"fe80::cc4b:8aff:fe32:d5b","netmask":"64","scope":"link"}],"counters":{"bytes_received":5070394,"bytes_sent":717665322,"packets_received":48422,"packets_sent":98828},"hwaddr":"ce:4b:8a:32:0d:5b","host_name":"","mtu":1500,"state":"up","type":"broadcast"},"veth4ecb798f":{"addresses":[{"family":"inet6","address":"fe80::7cf2:4ff:fe97:96f","netmask":"64","scope":"link"}],"counters":{"bytes_received":5970627,"bytes_sent":604276589,"packets_received":49576,"packets_sent":84910},"hwaddr":"7e:f2:04:97:09:6f","host_name":"","mtu":1500,"state":"up","type":"broadcast"},"veth96be650e":{"addresses":[{"family":"inet6","address":"fe80::5837:33ff:febe:ee7b","netmask":"64","scope":"link"}],"counters":{"bytes_received":855515,"bytes_sent":17469903,"packets_received":4588,"packets_sent":13519},"hwaddr":"5a:37:33:be:ee:7b","host_name":"","mtu":1500,"state":"up","type":"broadcast"},"vetha03712c1":{"addresses":[{"family":"inet6","address":"fe80::3cc7:70ff:fe63:bd6f","netmask":"64","scope":"link"}],"counters":{"bytes_received":619948,"bytes_sent":17959,"packets_received":8520,"packets_sent":161},"hwaddr":"3e:c7:70:63:bd:6f","host_name":"","mtu":1500,"state":"up","type":"broadcast"},"vethb742a912":{"addresses":[{"family":"inet6","address":"fe80::2434:e7ff:feac:a1e9","netmask":"64","scope":"link"}],"counters":{"bytes_received":213138532,"bytes_sent":5422624926,"packets_received":2048313,"packets_sent":2875576},"hwaddr":"26:34:e7:ac:a1:e9","host_name":"","mtu":1500,"state":"up","type":"broadcast"},"vethc53752a6":{"addresses":[{"family":"inet6","address":"fe80::6cab:dcff:fe19:d6ef","netmask":"64","scope":"link"}],"counters":{"bytes_received":4250441,"bytes_sent":625969479,"packets_received":42201,"packets_sent":99079},"hwaddr":"6e:ab:dc:19:d6:ef","host_name":"","mtu":1500,"state":"up","type":"broadcast"}},"pid":25124,"processes":260,"cpu":{"usage":125767747632708}}}


**Ansible task**

```
- name: lxd | deploy/manage LXD container 
  lxd_container:
        name: "{{ item.name }}"
        state: started
        source:
            type: image
            mode: pull
            server: https://images.linuxcontainers.org
            protocol: simplestreams 
            alias: "{{ item.os_release | default (os_release) }}"
        profiles: ["default"]
        config: 
            limits.cpu: "{{ item.vcpu | default (ansible_processor_vcpus) }}"
            limits.memory: "{{ item.mem | default (hv_total_memory) }}"
            security.nesting: "{{ item.nesting | default ('false') }}"
            security.privileged: "{{ item.privileged | default ('false') }}"
        wait_for_ipv4_addresses: true
        timeout: 60
  register: container_data
```

But ansible is return incomplete data. Ansible waiting to response 60 sec.

```
TASK [lxd/deploy : lxd | deploy/manage LXD container] *******************************************
ok: [hypervisor] => (item={'name': 'jenkins-slave-01', 'vcpu': 8, 'mem': '16GB', 'os_release': 'ubuntu/18.04/cloud', 'nesting': 'true', 'privileged': 'true'}) => {
    "actions": [],
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "architecture": null,
            "client_cert": "/root/.config/lxc/client.crt",
            "client_key": "/root/.config/lxc/client.key",
            "config": {
                "limits.cpu": "8",
                "limits.memory": "16GB",
                "security.nesting": "true",
                "security.privileged": "true"
            },
            "devices": null,
            "ephemeral": null,
            "force_stop": false,
            "name": "jenkins-slave-01",
            "profiles": [
                "default"
            ],
            "snap_url": "unix:/var/snap/lxd/common/lxd/unix.socket",
            "source": {
                "alias": "ubuntu/18.04/cloud",
                "mode": "pull",
                "protocol": "simplestreams",
                "server": "https://images.linuxcontainers.org",
                "type": "image"
            },
            "state": "started",
            "timeout": 60,
            "trust_password": null,
            "url": "unix:/var/lib/lxd/unix.socket",
            "wait_for_ipv4_addresses": true
        }
    },
    "item": {
        "mem": "16GB",
        "name": "jenkins-slave-01",
        "nesting": "true",
        "os_release": "ubuntu/18.04/cloud",
        "privileged": "true",
        "vcpu": 8
    },
    "log_verbosity": 3,
    "old_state": "started"
}
```
