### ISSUE TITLE
Label parameter on loop_control does not work with list of dictionaries

### ISSUE THREAD

**Issue by hwoarang** [ansible/ansible#40876]
##### SUMMARY
`loop_control/label` does not work with list of dictionaries

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.4.4.0
  config file = None
  configured module search path = ['/home/test/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/foobar/lib/python3.6/site-packages/ansible
  executable location = /home/test/foobar/bin/ansible
  python version = 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
```

##### OS / ENVIRONMENT
``openSUSE Tumbleweed`` but Ansible is installed in a virtualenv using pip

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  become: no
  gather_facts: no
  vars:
  tasks:
    - debug: 
        msg: "{{ item.src }}"
      with_items:
        - { src: 'FIRST ITEM', dest: 'none' }
        - { src: 'SECOND ITEM', dest: 'none' }
      loop_control:
        label: "{{ item.src }}
```

##### EXPECTED RESULTS
```
TASK [debug] ****************************************************************************************************************************************************************
ok: [localhost] => (item=FIRST ITEM) => {
    "msg": "FIRST ITEM"
}
ok: [localhost] => (item=SECOND ITEM) => {
    "msg": "SECOND ITEM"
}
```
##### ACTUAL RESULTS
```
TASK [debug] ****************************************************************************************************************************************************************
ok: [localhost] => (item=FIRST ITEM) => {
    "msg": "FIRST ITEM"
}
ok: [localhost] => (item=FIRST ITEM) => {
    "msg": "SECOND ITEM"
}
```
As you can see, the label for each iteration is constantly set to `item=FIRST ITEM` instead of actually using the "{{ item.src }}" value for each item
