### ISSUE TITLE
Galaxy - separate dependencies from execution

### ISSUE THREAD

**Issue by profhase** [ansible/ansible#40890]
##### SUMMARY
For now, role dependencies in `meta/main.yml` are both installed and executed before the role execution.
This is a mashup of the two concerns:
1. Install a role dependency (`galaxy`)
2. execute the role prior to the role execution (`ansible`)

The problems occur, when `roleX` needs `roleY` to be installed (for an `include_role`) but **not** being executed prior to it. 

*Example*:

```
# playbook.yml

- hosts: myhost
  roles:
    - {role: java, tags: ['java']}

# java/tasks/main.yml -> Installs java
- include_tasks: do_install_java_and_more.yml
- import_role:
    name: certificates

# java/meta/main.yml -> Always needs the Certificates to be installed *after* java
  galaxy_info:
  author: Me
  description: Role to install java

  dependencies:
    - name: certificates
      src: myserver/certificates.git
      version: master
```
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
galaxy

##### ANSIBLE VERSION
```
2.5.1
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
```yaml
#meta/main.yml

dependencies:
   - name: myrole
     src: mygit
     version: master
     execute: False  #Tells ansible not to execute the role automatically
```

##### EXPECTED RESULTS
---

##### ACTUAL RESULTS
```
---
```

**Comment by profhase** [comment]
!component -lib/ansible/galaxy

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by rsjethani** [comment]
I would really like this feature to become a part of ansible

**Comment by jcheroske** [comment]
@profhase, I just ran into this issue, and your description is spot on. A quick workaround is to pass a var to the dependent role which causes it to be a no-op during `meta/main.yml` load. This of course does not work when using 3rd-party roles. An example:

`some_role/tasks/main.yml`:
```
- block:
    - role_task_1:

    - role_task_2:
  when: some_role_loading is not defined
```

`some_role/meta/main.yml`:
```
dependencies:
  - { role: some_role, some_role_loading: yes }
```
This is just a hack. Your suggestion that these two concerns be separated would make the dependency syntax actually useful.
