### ISSUE TITLE
ios_l3_interface add support for other interface parameters

### ISSUE THREAD

**Issue by hemskgren** [ansible/ansible#40920]
##### SUMMARY

ios_l3_interface add support for other interface parameters like description, vrf, encapsulation, hsrp/standby, state(enable /disable) etc
Suggested prio: vrf, description, state, hsrp/standby
##### ISSUE TYPE
 - Feature Idea

##### ANSIBLE VERSION

```
2.5.3
```

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

```
- name: Set GigabitEthernet0/3 IPv4 and IPv6 address
  ios_l3_interface:
    name: GigabitEthernet0/3.100
    encapsulation: dot1q 100
    state: shutdown
    vrf: my-prod-vrf
    description: my-prod-traffic
    ipv4: 10.0.0.253/24
    standby_version: 2
    standby_ipv4:     10.0.0.254
    ipv6: "fd5d:12c9:2201:2::1/64"
    standby_ipv6: standby 6 ipv6 autoconfig
#
# ios config
interface GigabitEthernet0/3.100
  description my-prod-traffic
  encapsulation dot1q 100
  vrf forwarding my-prod-vrf
  shutdown
  ip address 10.0.0.253 255.255.255.0
  standby version 2
  standby 4 ip 10.0.0.254
  standby 4 priority 105
  standby 4 preempt delay minimum 10
  ipv6 address fd5d:12c9:2201:2::1/64
  standby 6 ipv6 autoconfig  
```
##### ACTUAL RESULTS

```
- name: Set GigabitEthernet0/3 IPv4 and IPv6 address
  ios_l3_interface:
    name: GigabitEthernet0/3.100
    ipv4: 192.168.0.2/24
    ipv6: "fd5d:12c9:2201:2::1/64"

```
