### ISSUE TITLE
Error in starting new container using lxd 3.0

### ISSUE THREAD

**Issue by vikrantrathore** [ansible/ansible#40949]
##### SUMMARY
Using lxd_container to launch a container takes over 10 minutes. On the command line using lxd launch it takes only few seconds. Using lxd 3.0

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

lxd_container

##### ANSIBLE VERSION
```
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/x/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/x/.local/share/virtualenvs/infrastructure-Tqtsi3VA/lib/python2.7/site-packages/ansible
  executable location = /Users/x/.local/share/virtualenvs/infrastructure-Tqtsi3VA/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### STEPS TO REPRODUCE
```yaml
- name: Start a new base container
   lxd_container:
           name: base
           state: started
           url: unix:/var/snap/lxd/common/lxd/unix.socket
           source:
              type: image
              mode: pull
              server: https://cloud-images.ubuntu.com/releases
              protocol: simplestreams
              auto_update: True
              alias: "18.04"
           profiles: ['default']
           wait_for_ipv4_addresses: True
           timeout: 600
```

##### EXPECTED RESULTS
Start a container quickly

##### ACTUAL RESULTS

Takes fairly long time to start. Also the error might be due to lxd cluster as it might start the container in any of the server within the farm and lxd_container still use old api's.
