### ISSUE TITLE
gcp_compute_disk.py documentation has wrong auth_kind

### ISSUE THREAD

**Issue by rameshvenk** [ansible/ansible#40967]
##### SUMMARY
In the  [gcp_compute_instance.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/google/gcp_compute_instance.py#L408) the example within the code has `auth_kind` listed as `service_account`, but the code looks for `serviceaccount` instead.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

google/gcp_compute_instance

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel 0fd7d7500a) last updated 2018/05/31 10:51:53 (GMT -500)
  config file = None
  configured module search path = ['/Users/tkmaikc/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/tkmaikc/Build/ansible/lib/ansible
  executable location = /Users/tkmaikc/Build/ansible/bin/ansible
  python version = 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

##### OS / ENVIRONMENT

OS Running ansible - Mac OSX 10.12.6
OS managing: N/A

##### STEPS TO REPRODUCE

- Checkout the `devel` branch from git
- Run `source/env-setup`
- Run example playbook below (based on the example in the doc in `gcp_compute_instance.py`

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    project_id: "GCP_PROJECT"
    credentials_file: "PATH/TO/GCP/CREDS.json"
    machine_type: n1-standard-1
    image: debian-7
    zone: us-central1-a
  tasks:
    - name: create disk
      gcp_compute_disk:
        name: "testing-disk-1"
        size_gb: 50
        source_image: "{{ image }}"
        zone: "{{ zone }}"
        project: "{{ project_id }}"
        auth_kind: service_account
        service_account_file: "{{ credentials_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: disk
```

##### EXPECTED RESULTS

Disk should be created

##### ACTUAL RESULTS

Invalid `auth_kind`

```
TASK [create disk] ***********************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of auth_kind must be one of: machineaccount, serviceaccount, application, got: service_account"}
```
