### ISSUE TITLE
vmware_guest tries to customize the VM when setting start_connected

### ISSUE THREAD

**Issue by EricThiel** [ansible/ansible#40989]
##### SUMMARY

vmware_guest should not attempt customizations for "start_connected" Parameter.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /home/myuser/ansible/ansible.cfg
  configured module search path = [u'/home/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

DEFAULT_HOST_LIST(/home/myuser/ansible/ansible.cfg) = [u'/home/myuser/ansible/hosts']
DEFAULT_ROLES_PATH(/home/myuser/ansible/ansible.cfg) = [u'/home/myuser/ansible']
DEPRECATION_WARNINGS(/home/myuser/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/myuser/ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/myuser/ansible/ansible.cfg) = 40
PERSISTENT_CONNECT_TIMEOUT(/home/myuser/ansible/ansible.cfg) = 50

##### OS / ENVIRONMENT

N/A, but for documentation purposes:
CentOS Linux release 7.4.1708 (Core)
managing ESXI 6.0
##### STEPS TO REPRODUCE

```yaml
---
- name: Create hosts
  hosts: master
  gather_facts: no
  connection: local

  vars:
    vcenter_hostname: hostname
    esxhost: esxhost
    datastore: datastore1
    network: "VMnetwork"
    vmtemplate: mytemplate
    vmcluster: Cluster
    dumpfacts: False
    hostlist:
      - "01"

  tasks:
    - name: Create VM from template
      with_items: "{{hostlist}}"
      delegate_to: localhost
      vmware_guest:
        validate_certs: False
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"

        esxi_hostname: "{{ esxhost }}"
        datacenter: Datacenter
        folder: /hostfarm
        name: "host{{ item }}"
        template: "{{ vmtemplate }}"
        networks:
          - name: "{{ network }}"
            start_connected: True
          - name: "{{ network }}"
            start_connected: True
          - name: "{{ network }}"
            start_connected: True
        state: present

~
```

##### EXPECTED RESULTS

I expected ansible to create 3 NICs on my template, which has 0 currently, and then complete. "start_connected" should not require running the customization process.

##### ACTUAL RESULTS

Ansible created 3 new NICs, but then attempted a customization execution and errored out because IP was not defined.

*As a footnote, this issue is currently masked by https://github.com/ansible/ansible/issues/40637, but I have manually reverted the code from https://github.com/ansible/ansible/pull/38755 and now encounter this issue.

```
TASK [Create VM from template] *******************************************************************************************************************************************************************************
failed: [1.1.1.1 -> localhost] (item=98) => {"changed": false, "item": "98", "msg": "TypeError was returned, please ensure to give correct inputs. Field \"ip\" is not optional"}
        to retry, use: --limit @/home/myuser/ansible/mkcsr.retry

```
