### ISSUE TITLE
win_scheduled_task parameter execution_time_limit fails in windows 7

### ISSUE THREAD

**Issue by erik-saarts** [ansible/ansible#40998]
##### SUMMARY

win_scheduled_task module parameter 'execution_time_limit' fails under windows 7.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

win_scheduled_task

##### ANSIBLE VERSION

```
ansible 2.5.5.dev0 (stable-2.5 456af458fc) last updated 2018/06/01 10:27:52 (GMT +300)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /root/tmp/2.5/ansible/lib/ansible
  executable location = /root/tmp/2.5/ansible/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```
Same behaviour under 2.6 and 2.7

##### CONFIGURATION

DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 15
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/root/windows/hosts']

##### OS / ENVIRONMENT

Ansible running Debian 9.3
Managed OS-es: win10pro, win10home, win7pro

##### STEPS TO REPRODUCE

```yaml
 - name: Test
   win_scheduled_task:
     name: Testing_execution_limit
     description: Dummy1
     allow_demand_start: yes
     multiple_instances: 2
     run_level: highest
     update_password: no
     actions:
     - path: c:\test\run_test.bat
       working_directory: C:\test
     enabled: yes
     triggers:
     - type: time
       start_boundary: '2018-01-01T00:00:01'
       enabled: yes
     state: present
     user: "{{ myuser }}"
     execution_time_limit: P0Y0M0DT0H0M0S
     logon_type: interactive_token
```

##### EXPECTED RESULTS

Task should be created with no limit to execution time.

Module documentation (http://docs.ansible.com/ansible/latest/modules/win_scheduled_task_module.html#win-scheduled-task-module) states that "In Ansible 2.4 and earlier, this could only be run on Server 2012/Windows 8 or newer. Since 2.5 this restriction has been lifted." This leaves me puzzled if it's feature or bug.

##### ACTUAL RESULTS

Task creation fails under windows 7, works fine for windows 10.

```
TASK [testing : test execution_time_limit] **********************************************************************************************************
task path: /root/roles/test/tasks/main.yml:31
Using module file /root/tmp/2.5/ansible/lib/ansible/modules/windows/win_scheduled_task.ps1
<192.168.0.135> ESTABLISH WINRM CONNECTION FOR USER: Administrator on PORT 5986 TO 192.168.0.135
EXEC (via pipeline wrapper)
fatal: [192.168.0.135]: FAILED! => {
    "changed": false,
    "msg": "failed to modify scheduled task: Exception calling \"RegisterTaskDefinition\" with \"6\" argument(s): \"(38,42):ExecutionTimeLimit:P0Y0M0DT0H1M0S\""
}
```
