### ISSUE TITLE
parse_sources and parse_source between them mishandle INVENTORY_UNPARSED_IS_FAILED

### ISSUE THREAD

**Issue by amenonsen** [ansible/ansible#40996]
##### SUMMARY
Setting ANSIBLE_INVENTORY_UNPARSED_FAILED=True in the environment or inventory.unparsed_is_failed=True in the configuration is supposed to turn failures into fatal errors:

```
INVENTORY_UNPARSED_IS_FAILED:
  name: Unparsed Inventory failure
  default: False
  description: If 'true' unparsed inventory sources become fatal errors, they are warnings otherwise.
  env: [{name: ANSIBLE_INVENTORY_UNPARSED_FAILED}]
  ini:
  - {key: unparsed_is_failed, section: inventory}
  type: bool
```

However, this works as intended only if the inventory contains a single source. If you have an inventory with multiple sources, ``parse_source`` will fail and return a failure to ``parse_sources``, but the latter tests and acts on ``C.INVENTORY_UNPARSED_IS_FAILED`` only if **ALL** invocations of ``parse_source`` failed to parse correctly.

So for an inventory with a static ini file and ec2.py, if ec2.py fails, execution continues blithely onwards regardless of the configuration.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
HEAD
```

##### CONFIGURATION

``inventory.unparsed_is_failed=True``

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

One needs and inventory directory that contains multiple sources (in my case, one static ini-format source file, and one script source: ec2.py), and cause the script to fail somehow (e.g., kill it while it's running, or firewall away AWS and wait for a timeout).

##### EXPECTED RESULTS

Execution should stop after script failure.

##### ACTUAL RESULTS

Execution continues after script failure.
