### ISSUE TITLE
Azure vm module needs higher role for first start/stop action

### ISSUE THREAD

**Issue by guillemsola** [ansible/ansible#41003]
##### SUMMARY

The basic role to start/stop a machine in Azure is _DevTest Labs User_. With the Ansible module the first time a machine is started a _Contributor_ role is needed. Notice that after this "first time" the _DevTest Labs User_ can be used.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vmadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

```
azure-cli-core               2.0.33
azure-cli-nspkg              3.0.2
azure-common                 1.1.11
azure-mgmt-batch             4.1.0
azure-mgmt-compute           2.1.0
azure-mgmt-containerinstance 0.4.0
azure-mgmt-containerregistry 2.0.0
azure-mgmt-containerservice  2.0.0
azure-mgmt-dns               1.2.0
azure-mgmt-keyvault          0.40.0
azure-mgmt-network           1.7.1
azure-mgmt-nspkg             2.0.0
azure-mgmt-rdbms             0.2.0rc1
azure-mgmt-resource          1.2.2
azure-mgmt-sql               0.7.1
azure-mgmt-storage           1.5.0
azure-mgmt-web               0.32.0
azure-nspkg                  2.0.0
azure-storage                0.35.1
```

##### OS / ENVIRONMENT
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
```

##### STEPS TO REPRODUCE

- Deploy  a machine using the Azure portal
- Create a service principal account `az ad sp create-for-rbac --role "DevTest Labs User"`
- Machine is stopped
- Try to open machine with 
```
---
- hosts: localhost
  connection: local
  gather_facts: false

  tasks:
  - name: Scenario 1
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ item.name }}"
      allocated: "{{ item.status }}"
    loop:
      - { name: WSLBack-1, status: yes }
```

##### EXPECTED RESULTS

The _DevTest Labs User_ role selected is able to start the machine the first time machine it is started.

##### ACTUAL RESULTS

The first time the machine is started the principal user using it needs a user '_Contributor_' role. After it has been started the _DevTest Labs User_ is enough to start the machine.

**Comment by guillemsola** [comment]
We found this issue while doing tests for #39958. It seems that there are some weird behaviors that happens only once using Ansible and Azure. Maybe they have some kind relation under the hoods.

**Comment by jeffmatts** [comment]
Hello. I'm having a similar issue as in [#39958](https://github.com/ansible/ansible/issues/39958) with Ansible 2.5.5. The below error occurs regardless of which role my service principal has. I've tried both Contributor and Owner. 

>  fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger
 \"msrestazure.azure_active_directory\"\nTraceback (most recent call last):\n  File \"/tmp/ansible_zX2JPz
/ansible_module_azure_rm_virtualmachine.py\", line 1694, in <module>\n    main()\n  File \"/tmp/ansible_z
X2JPz/ansible_module_azure_rm_virtualmachine.py\", line 1690, in main\n    AzureRMVirtualMachine()\n  Fil
e \"/tmp/ansible_zX2JPz/ansible_module_azure_rm_virtualmachine.py\", line 714, in __init__\n    supports_
check_mode=True)\n  File \"/tmp/ansible_zX2JPz/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py
\", line 345, in __init__\n  File \"/tmp/ansible_zX2JPz/ansible_module_azure_rm_virtualmachine.py\", line
 1076, in exec_module\n    storage_account_type=vm_dict['properties']['storageProfile']['osDisk']['manage
dDisk']['storageAccountType']\nKeyError: 'storageAccountType'\n", "module_stdout": "", "msg": "MODULE FAI
LURE", "rc": 1} 

```
- name: VM State
      azure_rm_virtualmachine:
        resource_group: test
        name: VM1
        allocated: yes
```
