### ISSUE TITLE
archive module creates empty archives given certain paths

### ISSUE THREAD

**Issue by silverdr** [ansible/ansible#41001]
##### SUMMARY

`archive` module creates empty archives when given certain paths. Possibly caused by inadequate escaping of the path string.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

archive

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/silverdr/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:14) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

##### OS / ENVIRONMENT

Running from OS X 10.11.6, managing GNU/Linux 4.4.0-127-generic #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
##### STEPS TO REPRODUCE

```yaml
    - name: find directories in previous versions directory
      become: yes
      find:
        paths: "{{previous_versions_directory}}"
        recurse: no
        file_type: directory
      register: dirs_to_archive
      tags:
        - update_backup
        - update_backup_archive

    - name: debug variable
      debug:
        var: dirs_to_archive
      tags:
        - update_backup
        - update_backup_archive

    - name: archive backup files
      become: yes
      archive:
        path: "{{item.path}}"
        dest: "{{item.path}}.tar.bz2"
        format: bz2
        remove: no
      with_items:
        - "{{dirs_to_archive.files}}"
      tags:
        - update_backup
        - update_backup_archive
```

##### EXPECTED RESULTS

Directory with all its content gets archived into bzipped tar archive file.
##### ACTUAL RESULTS

Created archive file is empty.

```
TASK [debug variable] **************************************************************************************************************
ok: [staging.host.com] => {
    "dirs_to_archive": {
        "changed": false, 
        "examined": 3, 
        "failed": false, 
        "files": [
            {
                "atime": 1527851228.2896943, 
                "ctime": 1527851231.573694, 
                "dev": 64769, 
                "gid": 1000, 
                "gr_name": "teamcity", 
                "inode": 1536088, 
                "isblk": false, 
                "ischr": false, 
                "isdir": true, 
                "isfifo": false, 
                "isgid": false, 
                "islnk": false, 
                "isreg": false, 
                "issock": false, 
                "isuid": false, 
                "mode": "0755", 
                "mtime": 1527851231.573694, 
                "nlink": 3, 
                "path": "/home/teamcity/aria_main-previous_versions/2018-06-01T11:07:06,797112829+00:00", 
                "pw_name": "teamcity", 
                "rgrp": true, 
                "roth": true, 
                "rusr": true, 
                "size": 4096, 
                "uid": 1000, 
                "wgrp": false, 
                "woth": false, 
                "wusr": true, 
                "xgrp": true, 
                "xoth": true, 
                "xusr": true
            }
        ], 
        "matched": 1, 
        "msg": ""
    }
}

TASK [archive previous versions] ***************************************************************************************************
changed: [staging.host.com] => (item={u'uid': 1000, u'woth': False, u'mtime': 1527851231.573694, u'inode': 1536088, u'isgid': False, u'size': 4096, u'roth': True, u'isuid': False, u'isreg': False, u'pw_name': u'teamcity', u'gid': 1000, u'ischr': False, u'wusr': True, u'xoth': True, u'rusr': True, u'nlink': 3, u'issock': False, u'rgrp': True, u'gr_name': u'teamcity', u'path': u'/home/teamcity/aria_main-previous_versions/2018-06-01T11:07:06,797112829+00:00', u'xusr': True, u'atime': 1527851228.2896943, u'isdir': True, u'ctime': 1527851231.573694, u'wgrp': False, u'xgrp': True, u'dev': 64769, u'isblk': False, u'isfifo': False, u'mode': u'0755', u'islnk': False})
```
