### ISSUE TITLE
register command: dict_object has no attribute 'rc'

### ISSUE THREAD

**Issue by shibumi** [ansible/ansible#41011]
##### SUMMARY

There is no `rc` value after executing the `command` module with the commands: `dpkg-query -W frr`

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

command

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /home/chris/ansible-vxlan/ansible.cfg
  configured module search path = ['/home/chris/ansible-vxlan/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]

```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/chris/ansible-vxlan/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/chris/ansible-vxlan/ansible.cfg) = ['/home/chris/ansible-vxlan/hosts']
DEFAULT_MODULE_PATH(/home/chris/ansible-vxlan/ansible.cfg) = ['/home/chris/ansible-vxlan/library']
DEFAULT_ROLES_PATH(/home/chris/ansible-vxlan/ansible.cfg) = ['/home/chris/ansible-vxlan/roles']
DEFAULT_SCP_IF_SSH(/home/chris/ansible-vxlan/ansible.cfg) = True
RETRY_FILES_ENABLED(/home/chris/ansible-vxlan/ansible.cfg) = False
```
##### OS / ENVIRONMENT

Host running Ansible: Arch Linux
Host that I want to manage with Ansible: Ubuntu 18.04

##### STEPS TO REPRODUCE

Fire the following role on on a Ubuntu 18.04 machine with user `root`.

```yaml
- name: Install dependencies for FRR
  package: name=libc-ares2,libc6,libcap2,libjson-c3,libpam0g,libreadline7,libsystemd0,logrotate,iproute2 state=present

- name: Check if FRR is already installed
  command: dpkg-query -W frr
  register: frr_check_deb
  failed_when: frr_check_deb.rc > 1
  changed_when: frr_check_deb.rc == 1

- name: Copy .deb file to host and install it
  copy: src=frr.deb dest=/root/frr.deb owner=root group=root mode=0644
  when: frr_check_deb.rc == 1

- name: install the deb file via apt
  apt: deb="/root/frr.deb"
  when: frr_check_deb.rc == 1
```

##### EXPECTED RESULTS

`register` should register a variable **with** return codes for the command that got executed by the `command` module.

##### ACTUAL RESULTS

The `rc` dictionary has no member `rc`, although the `command` module has been used.

```
TASK [frr : Copy .deb file to host and install it] *********************************************************************************************************
fatal: [REDACTED]: FAILED! => {"msg": "The conditional check 'frr_check_deb.rc == 1' failed. The error was: error while evaluating conditional (frr_check_deb.rc == 1): 'dict object' has no attribute 'rc'\n\nThe error appears to have been in '/home/chris/ansible-vxlan/roles/frr/tasks/main.yml': line 12, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Copy .deb file to host and install it\n  ^ here\n"}
```
