### ISSUE TITLE
apt_key ignores expired keys

### ISSUE THREAD

**Issue by LunNova** [ansible/ansible#41020]
##### SUMMARY
apt_key does not handle expired keys well.

If a key has expired, adding it will fail with 'key does not seem to have been added', even though the key has actually been added.
Trying to remove the expired key shows ok, even though the key is still there. The key is not removed.

Caused/relates to https://github.com/DataDog/ansible-datadog/issues/103

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

apt_key

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /mnt/c/Users/nallar/Home/Ansible/pve/ansible.cfg
  configured module search path = [u'/home/nallar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
DEFAULT_HOST_LIST(/mnt/c/Users/nallar/Home/Ansible/pve/ansible.cfg) = [u'/mnt/c/Users/nallar/Home/Ansible/pve/hosts']
DEFAULT_REMOTE_USER(/mnt/c/Users/nallar/Home/Ansible/pve/ansible.cfg) = root
```

##### OS / ENVIRONMENT

Ubuntu 16.04 on windows subsystem for linux

##### STEPS TO REPRODUCE

Add key:

```yaml
- name: Add HPE apt signing keys
  apt_key:
    id: '{{ item.id }}'
    url: '{{ item.url }}'
    state: present
  with_items:
    - { id: FB410E68CEDF95D066811E95527BC53A2689B887, url: 'https://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub' }
```

Remove key:
```
- name: Remove HPE apt signing keys
  apt_key:
    id: '{{ item.id }}'
    state: absent
  with_items:
  - { id: FB410E68CEDF95D066811E95527BC53A2689B887, url: 'https://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub' }
```

##### EXPECTED RESULTS

Adding the key should succeed (changed=1)

Removing the key should succeed (changed=1)

##### ACTUAL RESULTS

Adding the key:
```
failed: [node-x.pve.allan.scot] (item={u'url': u'https://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub', u'id': u'FB410E68CEDF95D066811E95527BC53A2689B887'}) => {"changed": false, "id": "FB410E68CEDF95D066811E95527BC53A2689B887", "item": {"id": "FB410E68CEDF95D066811E95527BC53A2689B887", "url": "https://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub"}, "msg": "key does not seem to have been added"}
```

Removing the key:
```
ok: [node-x.pve.allan.scot] => (item={u'url': u'https://downloads.linux.hpe.com/SDR/hpPublicKey1024.pub', u'id': u'FB410E68CEDF95D066811E95527BC53A2689B887'})
```
