### ISSUE TITLE
template + {% raw %} + register = failures

### ISSUE THREAD

**Issue by 0xDEC0DE** [ansible/ansible#41031]
##### SUMMARY
Using the `template` module to emit a file with Jinja2-like strings in it, protected by `{% raw %}` tags, and using `register` to capture/inspect the result, causes failures when the template is changed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
template

##### ANSIBLE VERSION
```
ansible 2.2.1.0
  config file = /Users/nisimond/work/ansible-systems/ansible.cfg
  configured module search path = ['./library', '$ANSIBLE_HOME/library']
```

##### CONFIGURATION
Stock configuration

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
A small test case is attached.  The first deployment will fail, subsequent deployments will report success.

Test case YAML:
```yaml
---
- name: Template register bug test case
  hosts: all
  tasks:
    - name: Write out template with protected raw tags
      template: src=derp.j2
                dest=/tmp/derp.txt
      register: _register_bug
      when: cleanup is not defined

    - name: Run a conditional check against the registered var
      debug:
        msg: This is a debug message
      when: _register_bug is changed

    - name: Cleanup test file
      file: name=/tmp/derp.txt
            state=absent
      when: cleanup is defined
```

Test case template:
```
Test template.  It contains {{ '{%' }} raw %} tags to protect Jinja-like
strings.  The initial run of the task will fail, but subsequent
runs will complete successfully

{% raw %}
This is "protected text"
Jinja2 really shouldn't care that this looks like the start of a
tag: {% herpa derpa doo %}
{% endraw %}

...and it doesn't, until you try to look at the registered result

{# uncomment the following line if you'd like it to fail every time #}
{# {{ 'abcdefghijklmnopqrstuvwxyz' | list | shuffle | join }} #}
```
##### EXPECTED RESULTS
The playbook to run successfully every time

##### ACTUAL RESULTS
The initial run fails, all subsequent runs succeed.  There is a commented-out "random string" in the template that can be uncommented to trigger failures on every run

```
Fri 01 Jun 13:33:55.520611 -0700: fatal: [mhv1.dev23.mc.metacloud.in]: FAILED! => {"failed": true, "msg": "The conditional check '_register_bug is changed' failed. The error was: {'changed': True, u'uid': 0, u'dest': u'/tmp/derp.txt', u'owner': u'root', 'diff': {'after': u'Test template.  It contains {% raw %} tags to protect Jinja-like\\nstrings.  The initial run of the task will fail, but subsequent\\nruns will complete successfully\\n\\n\\nThis is \"protected text\"\\nJinja2 really shouldn\\'t care that this looks like the start of a\\ntag: {% herpa derpa doo %}\\n\\n...and it doesn\\'t, until you try to look at the registered result\\n\\n', 'after_header': u'dynamically generated', 'before': u''}, u'size': 348, u'src': u'/home/nic/.ansible/tmp/ansible-tmp-1527885232.46-39406642689721/source', u'group': u'root', u'checksum': u'a2f35d844aa6d802b86bff7f28a3570829d51a6e', u'md5sum': u'031e3e0557be601069791ffb8549c46f', u'state': u'file', u'gid': 0, u'mode': u'0644'}: template error while templating string: Missing end of raw directive. String: Test template.  It contains {% raw %} tags to protect Jinja-like\nstrings.  The initial run of the task will fail, but subsequent\nruns will complete successfully\n\n\nThis is \"protected text\"\nJinja2 really shouldn't care that this looks like the start of a\ntag: {% herpa derpa doo %}\n\n...and it doesn't, until you try to look at the registered result\n\n\n\nThe error appears to have been in '/Users/nisimond/work/ansible-systems/derp.yml': line 11, column 7, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n    - name: Run a conditional check against the registered var\n      ^ here\n"}
```
