### ISSUE TITLE
Changing case size in local_action shell

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#41046]
##### SUMMARY

When I setting variable as name of azure subscription like azure_sub_name: "Microsoft Sponsorship" and calling this variable in task as local_action: shell "az account set - - subscription {{ azure_sub_name}}" I'm getting an error: No subscription "microsoft sponsorship" available. Task somehow changing upper case to lower case. 

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

General playbook usage?

##### ANSIBLE VERSION

```
2.5.0
```

##### OS / ENVIRONMENT

RedHat 
Azure 

##### STEPS TO REPRODUCE

```yaml
 vars: 
    subscriptionName: "Microsoft Sponsorship"

- name: Set subscription
  shell: az account set --subscription "{{ subscriptionName }}"

```

##### EXPECTED RESULTS

Subscription set.

##### ACTUAL RESULTS

```
No subscription "microsoft sponsorship" available
```
