### ISSUE TITLE
VMWARE_GUEST module, creating multiple VM by looping VM name mentioned in the list

### ISSUE THREAD

**Issue by bstarandeep** [ansible/ansible#41051]
Hello Team,

I am getting below error. I try to achieve the looping of VM name which is mentioned in the separate list. 

```
TASK [Clone a VM from Template and customize] **************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (vmware_guest) module: with_items Supported parameters include: annotation, cdrom, cluster, customization, customvalues, datacenter, disk, esxi_hostname, folder, force, guest_id, hardware, hostname, is_template, linked_clone, name, name_match, networks, password, port, resource_pool, snapshot_src, state, template, username, uuid, validate_certs, wait_for_ip_address"}
        to retry, use: --limit @/etc/ansible/clone_vm_from_template.retry
```
My playbook details.

```yaml
- hosts:
    localhost
  connection: local
  become: true
  vars:
#    ansible_python_interpreter: /usr/local/bin/python2.7
    ansible_python_interpreter: /usr/bin/python
    vmname_list: /etc/ansible/vmlist

  tasks:
  - name: Clone a VM from Template and customize
    vmware_guest:
      annotation: This is a test VM deployment from Ansible
      hostname: "abcl"
      username: 
      password: 
      validate_certs: no
      folder: /vm
      datacenter: ""
#      cluster: ""
      esxi_hostname: ""
      template: CentOS68-tmplt-01
      state:  poweredon
      name: "{{ vmname_list }}"
      with_items :  "{{vmname_list}}"
      disk:
      - size_gb: 40
        type: thin
        datastore: torsav_esx_ds209
      hardware:
        memory_mb: 4096
        num_cpus: 2
        scsi: paravirtual
      networks:
      - name: app
        ip: 10.81.2.172
        netmask: 255.255.255.0
        gateway: 10.177.91.1
      customization:
        #autologon: yes
```

**Comment by ansibot** [comment]
@bstarandeep Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bstarandeep** [comment]
TASK [Clone a VM from Template and customize] **************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (vmware_guest) module: with_items Supported parameters include: annotation, cdrom, cluster, customization, customvalues, datacenter, disk, esxi_hostname, folder, force, guest_id, hardware, hostname, is_template, linked_clone, name, name_match, networks, password, port, resource_pool, snapshot_src, state, template, username, uuid, validate_certs, wait_for_ip_address"}
        to retry, use: --limit @/etc/ansible/clone_vm_from_template.retry

**Comment by Akasurde** [comment]
@bstarandeep Thanks for reporting this issue. `with_items` is task level parameter just like `register`, error message suggest correctly about this.

Your PB should look like - 

```yaml
- hosts:
    localhost
  connection: local
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python
    vmname_list: /etc/ansible/vmlist
  tasks:
  - name: Clone a VM from Template and customize
    vmware_guest:
      annotation: This is a test VM deployment from Ansible
      hostname: "abcl"
      username: 
      password: 
      validate_certs: no
      folder: /vm
      datacenter: ""
      esxi_hostname: ""
      template: CentOS68-tmplt-01
      state:  poweredon
      name: "{{ vmname_list }}"
      disk:
      - size_gb: 40
        type: thin
        datastore: torsav_esx_ds209
      hardware:
        memory_mb: 4096
        num_cpus: 2
        scsi: paravirtual
      networks:
      - name: app
        ip: 10.81.2.172
        netmask: 255.255.255.0
        gateway: 10.177.91.1
      customization:
        #autologon: yes
    with_items :  "{{vmname_list}}"  # <<<---- This is task level key
```

We think this is a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!
