### ISSUE TITLE
add working example to docs

### ISSUE THREAD

**Issue by lastsky** [ansible/ansible#41065]
##### SUMMARY
there are no examples for module `user`

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME
`user`

##### ANSIBLE VERSION
```
not depends
```

##### CONFIGURATION
 - not depends

##### OS / ENVIRONMENT
 - not depends

##### STEPS TO REPRODUCE
1) go to http://docs.ansible.com/ansible/latest/modules/user_module.html
2) find no working and nice example

##### EXPECTED RESULTS
1) go to http://docs.ansible.com/ansible/latest/modules/user_module.html
2) find working and nice example:

```yaml
---
- hosts: all
  vars:
    users:
      - username: "alice"
        password: "secret_word"
      - username: "bob"
        password: "i_love_alice"

  tasks:
  - name: add users
    user:
      name: "{{ item.username }}"
      group: "{{ item.username }}"
      password: "{{ item.password | password_hash('sha512') }}"
      createhome: no
      state: present
      shell: "/bin/bash"
      update_password: on_create
    with_items: "{{ users }}"
    no_log: true
```

##### ACTUAL RESULTS
http://docs.ansible.com/ansible/latest/modules/user_module.html#examples

a lot of non-working examples in blogs written by pseudo-technicans and hours of googling without any working result, with pip, passlib and other python-related not IaC ways.
