### ISSUE TITLE
Unrendered variables in new 'loop' iterators

### ISSUE THREAD

**Issue by Vladimir-csp** [ansible/ansible#41086]
##### SUMMARY
I replaced `with_dict: "{{ dictname }}` iterators with `loop: "{{ lookup('dict', dictname) }}"`. Data from `dictname` now contains literal `{{ vairable }}` strings instead of rendered values.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

core

##### ANSIBLE VERSION

```
ansible 2.5.3
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```yaml
# group_vars/CenOS:
snmp_user: snmp

# group_vars/Debian:
snmp_user: Debian-snmp

# group_vars/monitored:
accounts:
  "{{ snmp_user }}":
    uid: 161

# tasks.yml:
- hosts: monitored
  tasks:

    - name: working iteration
      debug:
        msg: "{{ item.key }}"
      with_dict: "{{ accounts }}"

    - name: faulty iteration
      debug:
        msg: "{{ item.key }}"
      loop: "{{ query('dict', accounts) }}"

```

##### EXPECTED RESULTS

keys are rendered as `snmp` or `Debian-snmp`
```
TASK [working iteration] **********************************************************
ok: [debhost] => (item=None) => {
     "msg": "Debian-snmp"
}
ok: [coshost] => (item=None) => {
     "msg": "snmp"
}
TASK [faulty iteration] ***********************************************************
ok: [debhost] => (item=None) => {
     "msg": "Debian-snmp"
}
ok: [coshost] => (item=None) => {
     "msg": "snmp"
}

```

##### ACTUAL RESULTS

keys are rendered as literal `{{ snmp_user }}`. If `with_*` iterators are going to be deprecated, this would break stuff.

```
TASK [working iteration] **********************************************************
ok: [debhost] => (item=None) => {
     "msg": "Debian-snmp"
}
ok: [coshost] => (item=None) => {
     "msg": "snmp"
}
TASK [faulty iteration] ***********************************************************
ok: [debhost] => (item=None) => {
     "msg": "{{ snmp_user }}"
}
ok: [coshost] => (item=None) => {
     "msg": "{{ snmp_user }}"
}

```
