### ISSUE TITLE
F5 can not add enabled vlan with bigip_virtual_server

### ISSUE THREAD

**Issue by eoprede** [ansible/ansible#41099]
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_virtual_server
##### ANSIBLE VERSION

```
ansible 2.6.0a2
  config file = None
  configured module search path = [u'/ansible/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]
```

##### CONFIGURATION

NA
##### OS / ENVIRONMENT

NA
##### STEPS TO REPRODUCE

```yaml
  tasks:
    - name: set facts
      set_fact:
        virtual:
          - name: test_https
            destination: 192.168.9.9
            port: '443'
            ip_protocol: tcp
            profiles:
            - tcp
            address_translation: '1'
            port_translation: '1'
            enabled_vlans:
            - FW-LB
    - name: Create test virtual
      bigip_virtual_server:
        provider: "{{ test_f5 }}"
        name: "{{item.name}}"
        state: "{{item.state | default(omit)}}"
        port: "{{item.port | default(omit)}}"
        source: "{{item.source | default(omit)}}"
        destination: "{{item.destination | default(omit)}}"
        profiles: "{{item.profiles | default(omit)}}"
        snat: "{{item.snat | default(omit)}}"
        ip_protocol: "{{item.ip_protocol | default(omit)}}"
        type: "{{item.type | default(omit)}}"
        pool: "{{item.pool | default(omit)}}"
        address_translation: "{{item.address_translation | default(omit)}}"
        port_translation: "{{item.port_translation | default(omit)}}"
        default_persistence_profile: "{{item.default_persistence_profile | default(omit)}}"
        irules: "{{item.irules | default(omit)}}"
      loop: "{{ virtual }}"
      delegate_to: localhost
```

##### EXPECTED RESULTS

```
ltm virtual test_https {
    destination 192.168.9.9:https
    ip-protocol tcp
    mask 255.255.255.255
    profiles {
        tcp { }
    }
    source 0.0.0.0/0
    translate-address enabled
    translate-port enabled
    vlans {
        /Common/external
    }
    vlans-enabled
}
```
##### ACTUAL RESULTS

```
ltm virtual test_https {
    destination 192.168.9.9:https
    ip-protocol tcp
    mask 255.255.255.255
    profiles {
        tcp { }
    }
    source 0.0.0.0/0
    translate-address enabled
    translate-port enabled
    vs-index 35
}
```
