### ISSUE TITLE
URI module can not cope with key variables in Headers

### ISSUE THREAD

**Issue by Yannick91** [ansible/ansible#41096]
##### SUMMARY

The issue I have is that when we use the URI module (which is a very practical module to have a clear overview of the rest calls) is that we can not use variables replacing the key's in headers (an example to clear this out):
```yaml
headers:
       Accept: 'application/json'  
       Accept-API-Version: 'protocol=1.0, resource=1.0'
       "{{am_cookie_name}}": "{{TOKENADMINVALUE}}"
```
= {{am_cookie_name}} is not being read out as this is a key ... value of key's are fine. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

URI module

##### ANSIBLE VERSION

```
"ansible 2.4.1.0
  ansible python module location = /export/data/ansible/lib/python2.7/site-packages/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]"
```

##### CONFIGURATION

"ANSIBLE_SSH_ARGS(/export/data/ciams_ansible/IIAMS_ANSIBLE/ansible.cfg) = -o ControlMaster=no -o StrictHostKeyChecking=no
DEFAULT_LOG_PATH(/export/data/ciams_ansible/IIAMS_ANSIBLE/ansible.cfg) = /export/data/logs/ansible_logs
DEFAULT_TRANSPORT(/export/data/ciams_ansible/IIAMS_ANSIBLE/ansible.cfg) = ssh
DEFAULT_VAULT_PASSWORD_FILE(/export/data/ciams_ansible/IIAMS_ANSIBLE/ansible.cfg) = /export/data/.password_ansible_vault
HOST_KEY_CHECKING(/export/data/ciams_ansible/IIAMS_ANSIBLE/ansible.cfg) = False"

##### OS / ENVIRONMENT

"Red Hat Enterprise Linux Server 7.5"

##### STEPS TO REPRODUCE

I think the easiest way of reproducing this is to do a rest call to a web service and try to make variables of key & values in headers as in the following example:

```yaml
"- name: "List all realms"
  uri:
    url: 'http://{{inventory_hostname}}:{{port}}/{{instance}}/json/global-config/realms?_queryFilter=true'
    method: GET
    headers:
       Accept: 'application/json'  
       Accept-API-Version: 'protocol=1.0, resource=1.0'
       "{{am_cookie_name}}": "{{TOKENADMINVALUE}}"
  register: get_realms"
```

##### EXPECTED RESULTS

Just that it authenticates as it should be and read out the value of that specific variable. 

##### ACTUAL RESULTS

When you execute the following, you will probably get unauthorized because it will print out literally {{am_cookie_name}} instead of its' value. When you run the variable in a debug msg, you will get the correct output. However, in the URI module it does not work. 

```
" FAILED! => {"cache_control": "no-cache", "changed": false, "connection": "close", "content": "{\"code\":401,\"reason\":\"Unauthorized\",\"message\":\"Access Denied\"}", "content_type": "application/json;charset
=UTF-8", "date": "Mon, 04 Jun 2018 14:00:19 GMT", "failed": true, "json": {"code": 401, "message": "Access Denied", "reason": "Unauthorized"}, "msg": "Status code was not [200]: HTTP Error 401: Unauthorized", "redirected": false, "server
": "Apache-Coyote/1.1", "status": 401, "url": "http://xxxxxx:xxxx/auth/json/global-config/realms?_queryFilter=true", "x_frame_options": "SAMEORIGIN"}"
```
