### ISSUE TITLE
connection keyword no longer works with include_role

### ISSUE THREAD

**Issue by rhopfer** [ansible/ansible#41108]
##### SUMMARY
connection keyword no longer works with include_role

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
include_role

##### ANSIBLE VERSION
```
ansible 2.5.3
  config file = /home/rhopfer/.ansible.cfg
  configured module search path = ['/home/rhoper/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, Apr 14 2018, 13:17:30) [GCC 7.3.1 20180406]
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
connection-test.yml:
```yaml
- hosts: remotehost
  tasks:
    - command: hostname
      connection: local
      register: result
    - debug: var=result.stdout_lines
    - include_role: name=echo-hostname
    - include_role: name=echo-hostname
      connection: local
```
roles/echo-hostname/tasks/main.yml
```yaml
- command: hostname
  register: result
- debug: var=result.stdout_lines
```

##### EXPECTED RESULTS
The output of the last task shoul be 'localhost'.
- https://docs.ansible.com/ansible/2.5/plugins/connection.html
- https://docs.ansible.com/ansible/2.5/reference_appendices/playbooks_keywords.html#role

##### ACTUAL RESULTS
````
PLAY [remotehost] **************************************************************

TASK [Gathering Facts] *********************************************************
ok: [remotehost]

TASK [command] *****************************************************************
changed: [remotehost]

TASK [debug] *******************************************************************
ok: [remotehost] => {
    "result.stdout_lines": [
        "localhost"
    ]
}

TASK [include_role] ************************************************************

TASK [hostname_echo : command] *************************************************
changed: [remotehost]

TASK [hostname_echo : debug] ***************************************************
ok: [remotehost] => {
    "result.stdout_lines": [
        "remotehost"
    ]
}

TASK [include_role] ************************************************************

TASK [hostname_echo : command] *************************************************
changed: [remotehost]

TASK [hostname_echo : debug] ***************************************************
ok: [remotehost] => {
    "result.stdout_lines": [
        "remotehost"
    ]
}

PLAY RECAP *********************************************************************
remotehost                      : ok=7    changed=3    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/role/include.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/role/include.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by HD650** [comment]
Still happen in ansible 2.6, I'm now tracking the reason.

**Comment by bcoca** [comment]
the reason is that it applies to `include_role` not to the tasks, there is a new `apply` option to include role to  allow for this in newer versions, for older versions use a block to give keywords to inherit.

**Comment by HD650** [comment]
@bcoca so no need to fix `include_role`?

**Comment by bcoca** [comment]
no, same for include_tasks, import_role/import_tasks have keywords 'inherited' by the tasks , but include_X have keywords applied to THEM, not the tasks

**Comment by HD650** [comment]
For ansible 2.7 or newer you can do:
```
- name: role with connection plugin
  include_role:
    name: test_role
    apply:
      connection: local
```
For older version you can do:
```
- name: role with connection use block
  block:
    - include_role:
        name: test_role
  connection: local
```
