### ISSUE TITLE
mysql_user: MySQL 8.0/CentOS 7 - unable to connect to database

### ISSUE THREAD

**Issue by dungdm93** [ansible/ansible#41116]
##### SUMMARY
I'm install **MySQL 8.0** on **CentOS**, but I can't change root password.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dungdm93/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### COMPONENT NAME
lib/ansible/modules/database/mysql/mysql_user.py

##### OS / ENVIRONMENT
```
16.04.4 LTS (Xenial Xerus)
```

##### STEPS TO REPRODUCE
MySQL config:
```ini
# {{ ansible_managed }}

[mysqld]
pid-file    = /var/run/mysqld/mysqld.pid
socket      = /var/run/mysqld/mysqld.sock
datadir     = /var/lib/mysql
log-error   = /var/log/mysql/error.log

[client]
port        = 3306
socket      = /var/run/mysqld/mysqld.sock
```

and ansible tasks:
```yaml
- name: Catch temporary password
  when: ansible_os_family == 'RedHat'  and
        mysql_new_installation is changed and
        mysql_version is version('5.7', '>=')
  block:
  - command: >
      awk -F : '/temporary password/ {gsub(/ /, "", $NF); print $NF}' /var/log/mysql/error.log
    register: temporary_password

  - set_fact:
      mysql_old_password: "{{ temporary_password.stdout }}"

- name: Change MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password}}"
    check_implicit_admin: true
    login_user:     "root"
    login_password: "{{ mysql_old_password }}"
```

As you can see, I config socket dir from `/var/lib/mysql/mysql.sock` (default on CentOS) to `/var/run/mysqld/mysqld.sock`. But `mysql_user` don't recognize new location:
```log
TASK [mysql-server : command] ******************************************************************************************************************************************************************************
changed: [srv-centos]

TASK [mysql-server : set_fact] *****************************************************************************************************************************************************************************
ok: [srv-centos]

TASK [mysql-server : Change MySQL root password] ***********************************************************************************************************************************************************
fatal: [srv-centos]: FAILED! => {
  "changed": false, 
  "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials. 
        Exception message: (2002, \"Can't connect to local MySQL server through socket '/var/lib/mysql/mysql.sock' (2)\")"
}
``` 
Second time, when i specify `login_unix_socket: /var/run/mysqld/mysqld.sock` on `mysql_user`, I got following error:
```log
TASK [mysql-server : Change MySQL root password] ***********************************************************************************************************************************************************
fatal: [srv-centos]: FAILED! => {
    "changed": false,
    "msg": "unable to connect to database, check login_user and login_password are correct or /root/.my.cnf has the credentials.
        Exception message: (2059, \"Authentication plugin 'caching_sha2_password' cannot be loaded: /usr/lib64/mysql/plugin/caching_sha2_password.so: cannot open shared object file: No such file or directory\")"
}
```
