### ISSUE TITLE
option --start-at-task does not support multiple tasks with the same name

### ISSUE THREAD

**Issue by xp-1000** [ansible/ansible#41122]
##### SUMMARY
The option `--start-at-task` does not support multiple tasks with the same name and only use the first one found.

##### ISSUE TYPE
 - ~Bug  Report~
- Feature Idea

##### COMPONENT NAME
core

##### ANSIBLE VERSION
```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/qmanfroi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]

```

##### CONFIGURATION
```
allow_world_readable_tmpfiles=True
roles_path=roles
log_path=ansible.log
remote_tmp=$HOME/.ansible/tmp
local_tmp=$HOME/.ansible/tmp
```

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
main.yml
```yaml
- include: debian.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
```

debian.yml
```yaml
- name: debug 1
  debug:
    var: test

- name: Create package manager configuration file
  template:
    src: apt.conf.j2
    dest: /etc/apt/apt.conf.d/10-custom
```

redhat.yml
```yaml
- name: debug 2
  debug:
    var: test

- name: Create package manager configuration file
  template:
    src: yum.conf.j2
    dest: /etc/yum.conf
```

then, run `ansible-playbook -i localhost, -c local --start-at-task='Create package manager configuration file' playbook.yml`

##### EXPECTED RESULTS
as for `debug 1` task, `debug 2` task should also be skipped by the option `--start-at-task`.

##### ACTUAL RESULTS
Imagine we are on redhat based distro. 
Ansible will jump `debug 1` task to do the apt version of the `Create package manager configuration file` task.
Ansible will "skip" this task because we are not on debian.
So it works as expected for the first match (debian as `d` is before `r`).
Then ansible will run all tasks from `redhat.yml` file including `debug 2` task.
