### ISSUE TITLE
Module zabbix_host doesn't work for zabbix 2.2

### ISSUE THREAD

**Issue by aleksandpetrov** [ansible/ansible#41135]
##### SUMMARY

Module zabbix_host has settings for tls after version 2.5, but zabbix hasn't their before version 3.0. I have zabbix of version 2.2 and this module doesn't work for it.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

zabbix_host
##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /Users/admin/.ansible.cfg
  configured module search path = [u'/Users/admin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION

ANSIBLE_NOCOWS(/Users/admin/.ansible.cfg) = True
ANSIBLE_PIPELINING(/Users/admin/.ansible.cfg) = True
DEFAULT_FORKS(/Users/admin/.ansible.cfg) = 10
DEFAULT_REMOTE_USER(/Users/admin/.ansible.cfg) = petrov
DEFAULT_ROLES_PATH(/Users/admin/.ansible.cfg) = [u'/Users/admin/ansible_local/roles']
DEFAULT_VAULT_PASSWORD_FILE(/Users/admin/.ansible.cfg) = /Users/admin/ansible_local/.vault_vars_password_file
DISPLAY_ARGS_TO_STDOUT(/Users/admin/.ansible.cfg) = True
HOST_KEY_CHECKING(/Users/admin/.ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/admin/.ansible.cfg) = False
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```
- name: Add new host in zabbix
  local_action:
    module: zabbix_host
    server_url: "http://hostname"
    login_user: "{{ zabbix_api_user }}"
    login_password: "{{ zabbix_api_password }}"
    host_name: "{{ inventory_hostname }}"
    visible_name: "{{ inventory_hostname }}"
    force: no
    host_groups:
      - Some Groups
    link_templates:
      - some_templates
    status: enabled
    state: present
    inventory_mode: disabled
    interfaces:
      - type: 1
        main: 1
        useip: 0
        ip: ""
        dns: "{{ inventory_hostname }}"
        port: 10050
```

##### EXPECTED RESULTS

Add or update host in zabbix
##### ACTUAL RESULTS

```
TASK [common : Add new host in zabbix status=enabled, force=False, login_user={{ zabbix_api_user }}, interfaces=[{u'ip': u'', u'useip': 0, u'dns': u'{{ inventory_hostname }}', u'main': 1, u'type': 1, u'port': 10050}], tls_connect=1, tls_accept=1, server_url=http://hostname, visible_name={{ inventory_hostname }}, state=present, host_name={{ inventory_hostname }}, host_groups=[u' Some Groups'], login_password={{ zabbix_api_password }}, inventory_mode=disabled, link_templates=[u'some_templates']] ***
task path: /***/tasks/main.yml:2
Using module file /usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/ansible/modules/monitoring/zabbix/zabbix_host.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: admin
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-hsfjohurufndsehcqtelkulbsrzjcrnw; /usr/local/Cellar/ansible/2.5.2/libexec/bin/python2.7'"'"' && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_v5lCch/ansible_module_zabbix_host.py", line 861, in <module>
    main()
  File "/tmp/ansible_v5lCch/ansible_module_zabbix_host.py", line 821, in main
    ipmi_authtype, ipmi_privilege, ipmi_username, ipmi_password):
  File "/tmp/ansible_v5lCch/ansible_module_zabbix_host.py", line 518, in check_all_properties
    if int(host['tls_accept']) != tls_accept:
KeyError: 'tls_accept'

fatal: [host -> localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_v5lCch/ansible_module_zabbix_host.py\", line 861, in <module>\n    main()\n  File \"/tmp/ansible_v5lCch/ansible_module_zabbix_host.py\", line 821, in main\n    ipmi_authtype, ipmi_privilege, ipmi_username, ipmi_password):\n  File \"/tmp/ansible_v5lCch/ansible_module_zabbix_host.py\", line 518, in check_all_properties\n    if int(host['tls_accept']) != tls_accept:\nKeyError: 'tls_accept'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```
