### ISSUE TITLE
Cannot decrypt with copy module when remote_src: yes

### ISSUE THREAD

**Issue by akskos** [ansible/ansible#41130]
##### SUMMARY

I'm trying to download vault encrypted files from a server onto my remote machine with get_url and after that decrypt them with copy module. I understood from the documentation that this should be possible. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

copy

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

ANSIBLE_NOCOWS(env: ANSIBLE_NOCOWS) = True

##### OS / ENVIRONMENT

Ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml
- name: Copy private keys into /opt/private-keys
  copy:
    src: "/tmp/ansible-files/private-keys/{{ item.name }}"
    remote_src: yes
    decrypt: yes 
    dest: /opt/private-keys
    owner: "{{ item.owner }}"
  with_items:
    - { name: service1__jwt_priv.key, owner: 40004 }
    - { name: service2__jwt_priv.key, owner: 40003 }
    - { name: service3__jwt_priv.key, owner: 40005 }
  become: yes
```
Before this I have downloaded the encrypted keys to /tmp/ansible-files/private-keys with get_url.

##### EXPECTED RESULTS

I expected the files to be copied to /opt/private-keys and be decrypted with a key that I provide when running ansible-playbook.  This works when I copy the files from local machine (remote_src: no).

##### ACTUAL RESULTS

```
failed: [my_remote_host.com] (item={u'owner': 40005, u'name': u'service3__jwt_priv.key'}) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "decrypt": true, 
            "dest": "/opt/private-keys/", 
            "owner": "40005",
            "remote_src": true, 
            "src": "/tmp/ansible-files/private-keys/service3__jwt_priv.key"
        }
    }, 
    "item": {
        "name": "service3__jwt_priv.key", 
        "owner": 40005
    }, 
    "msg": "Unsupported parameters for (copy) module: decrypt Supported parameters include: attributes, backup, checksum, content, delimiter, dest, directory_mode, follow, force, group, local_follow, mode, original_basename, owner, regexp, remote_src, selevel, serole, setype, seuser, src, unsafe_writes, validate"
}
```

All 3 items produce that same error. If I remove the decrypt parameter no errors are produced and the files are copied but the keys aren't decrypted.
