### ISSUE TITLE
Error running the Ansible snow_record module

### ISSUE THREAD

**Issue by abolduc10** [ansible/ansible#41148]
##### SUMMARY
Receiving an error message when executing the snow_record module on the 2.5.2 version of Ansible.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

snow_record

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /home/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  2 2016, 04:20:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  name: Test connection ServiceNow
  gather_facts: False

  tasks:
    - name: Connection to change_request table in ServiceNow
      snow_record:
        username: #############
        password: #############
        instance: #############
        state: present
        table: change_request
        data:
          short_description: "This is a test change_request created by Ansible"
```

##### EXPECTED RESULTS

I would expect the playbook to complete and create a new change request

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "/usr/lib/python2.7/site-packages/pysnow/client.py:129: DeprecationWarning: `insert` is deprecated and will be removed in a future release. Please use `resource()` instead.\n  \"Please use `resource()` instead.\" % inspect.stack()[1][3], DeprecationWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_1duKz5/ansible_module_snow_record.py\", line 331, in <module>\n    main()\n  File \"/tmp/ansible_1duKz5/ansible_module_snow_record.py\", line 328, in main\n    run_module()\n  File \"/tmp/ansible_1duKz5/ansible_module_snow_record.py\", line 270, in run_module\n    except pysnow.UnexpectedResponse as e:\nAttributeError: 'module' object has no attribute 'UnexpectedResponse'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```
