### ISSUE TITLE
Extend match functionality for iptables module

### ISSUE THREAD

**Issue by EvanDonato** [ansible/ansible#41147]
##### SUMMARY
iptables module only offers a limited set of functionality for the match function of iptables.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

iptables

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/edonato/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### OS / ENVIRONMENT

Source: OSX 10.13.4
Target: CentOS 7

##### STEPS TO REPRODUCE

```yaml
Two options for new command:
- name: Drop long DNS TCP
  iptables:
    chain: INPUT
    protocol: tcp
    source_port: 53
    match: length
    length: 1025
    jump: DROP
  become: yes

OR

- name: Log long DNS TCP
  iptables:
    chain: INPUT
    protocol: tcp
    source_port: 53
    match: length
    match_args: --length 1025
    jump: DROP
  become: yes
```

##### EXPECTED RESULTS

There are two proposed options.  First would follow the current model where sanity checks and the like are done by the iptables module prior to attempting an insert and the second would simplify things in a sense by allowing a user to supply an argument to the match option that would be error handled by iptables itself.

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/iptables.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/iptables.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @LinusU @sebastiendarocha
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by grimlokason** [comment]
Hello,
This feature is still something needed,.

For exemple, actually with something like : 

```yml
- name: configure | Adding iptables rules
  iptables:
    chain: FORWARD
    protocol: tcp 
    destination_port: 15672
    action: insert 
    match: "set ! --match-set AWX3.0 src"
    jump: DROP
    rule_num: 1
```

It's converted to : 

```bash
/sbin/iptables -t filter -I FORWARD 1 -p tcp -m 'set ! --match-set AWX3.0 src' -j DROP --destination-port 15672
```
this give the error : 

```bash
iptables v1.4.21: Couldn't load match `set ! --match-set AWX3.0 src':
```

While it should be  : 
```bash
/sbin/iptables -t filter -I FORWARD 1 -p tcp -m set ! --match-set AWX3.0 src -j DROP --destination-port 15672
```

tested on ansible 2.8
