### ISSUE TITLE
localhost user is not working correctly, always root Playbook 2.5.4

### ISSUE THREAD

**Issue by andersab** [ansible/ansible#41157]
### SUMMARY 
When running playbooks locally, on the localhost, `user_id: {{ lookup('env','USER') }}` is always root instead of the user executing the playbook.

### ISSUE TYPE
Bug Report

### Component Name
ansible-playbook

### VERSION
2.5.4

### REPRODUCE
ansible-playbook -i hosts.yml playbook.yml

### Configuration
Default

### Files

**hosts.yml**

```yaml
all:
  children:
    localmachine:
      hosts:
        localhost
      vars:
        ansible_connection: local
```
**Playbook.yml**

```yaml
---
- hosts: all
  vars:
    user_id: "{{ lookup('env', 'USER') }}"
    roles:
      - javascript
```
**roles/javascript/tasks/main.yml**

```yaml
- name: Download nodejs
  get_url:
    url: https://deb.nodesource.com/setup_10.x
    dest: /home/{{ user_id }}/tools/
    mode: 0755
```

### Error
"Destination" /home/root/rools does not exist

### EXPECTED
the file to download in the <current_user_home>/tools directory
