### ISSUE TITLE
Incorrect authentication_plugin when create mysql_user

### ISSUE THREAD

**Issue by dungdm93** [ansible/ansible#41173]
##### SUMMARY
Incorrect **authentication_plugin** when create **mysql_user**

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
mysql_user

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dungdm93/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Just default

##### OS / ENVIRONMENT
* Control machine: Ubuntu 16.04.4 LTS
* Target machine: Ubuntu 16.04.4 LTS, CentOS 7, Debian 9 (stretch)
* MySQL: 8.0

##### STEPS TO REPRODUCE
* MySQL config:
```sql
mysql> SHOW VARIABLES\G
....
*************************** 53. row ***************************
Variable_name: default_authentication_plugin
        Value: mysql_native_password
....
```
* Ansible task:
```yaml
- name: Create MySQL 'root'@'%' user
  mysql_user:
    name:     "root"
    host:     "%"
    password: "{{ mysql_root_password }}"
    priv:     "*.*:ALL,GRANT"
    login_user:     "root"
    login_password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    check_implicit_admin: true

```

##### ACTUAL RESULTS
```sql
mysql> SELECT user, host, plugin, authentication_string FROM mysql.user;
+------------------+-----------+-----------------------+------------------------------------------------------------------------+
| user             | host      | plugin                | authentication_string                                                  |
+------------------+-----------+-----------------------+------------------------------------------------------------------------+
| root             | %         | caching_sha2_password | $A$005$m+,0
                                                                      qy(]7%ggNQ4OUre0ucO2yIV/J6/b1jdn1D9L9L2Ycixlfq8adKp06 |
| mysql.infoschema | localhost | mysql_native_password | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE                              |
| mysql.session    | localhost | mysql_native_password | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE                              |
| mysql.sys        | localhost | mysql_native_password | *THISISNOTAVALIDPASSWORDTHATCANBEUSEDHERE                              |
| root             | localhost | mysql_native_password | *9B500343BC52E2911172EB52AE5CF4847604C6E5                              |
+------------------+-----------+-----------------------+------------------------------------------------------------------------+
```
