### ISSUE TITLE
yum_repository shouldn't require baseurl/metalink/mirrorlist to disable a repository

### ISSUE THREAD

**Issue by rgarrigue** [ansible/ansible#41178]
##### SUMMARY

With yum on CentOS and most likely RHEL, Fedora, you might want to get rid of OS repositories in favor of local mirror. If you remove them, the OS might re-create them at the next yum update, so personnaly I disable them.

But ansile can't disable (enabled=false) a yum_repository without knowing its baseurl/metalink/mirrorlist. It can just remove it (state=absent). 

I wish enabled=false behave the same way as state=absent, just find the unique [reponame] in the files without caring about baseurl & so on, which might change over time

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

yum_repository

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/packaging/os/yum_repository.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/packaging/os/yum_repository.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
Thanks for opening this issue. I will try to look into it.

**Comment by ansiblejunky** [comment]
Yes, the `yum_repository` module should handle this similarly to how the `rhsm_repository' module handles it.

The `rhsm_repository' module allows for this simple way to disable all repos:
```
- name: Disable all RHSM repositories
  rhsm_repository:
    name: '*'
    state: disabled
```

Therefore, the `yum_repository` module should allow for the following, without user having to know about files or repo ID or anything else really. The user is simply trying to disable all repos managed by Yum.
```
- name: Disable all RHSM repositories
  yum_repository:
    name: '*'
    state: disabled
```

I had a customer recently who wanted to provision their servers to prepare for an Ansible Tower installation. So we wanted to cleanup any defined repos for both Yum managed and RHSM managed.

**Comment by markusdd** [comment]
I strongly want to support this idea, because I just ran across the exact same issue.
I'm currently writing a playbook which pre-configures our nodes for an openshift deployment, where the official instructions want you to disable EPEL from a certain point on.

EPEL is installed on CentOS 7 via epel-release, so I absolutely do not care what the URLs etc are.

I just want:
```
  - name: Deactivate EPEL
    yum_repository:
        name: epel
        state: present
        enabled: no
```

By the way, this would also serve as a sanity check. When you specify state present without any repo info, and the file is not there (because yum install epel-release failed in some strange way), you would correctly error out.

**Comment by ansibot** [comment]
Files identified in the description:
* [`lib/ansible/modules/yum_repository.py`](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/yum_repository.py)

If these files are incorrect, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by MichaelDBA** [comment]
Anyone planning on fixing this issue anytime soon?

**Comment by ansiblejunky** [comment]
Based on the following documentation for the `yum_repository` module in the ansible builtin collection, it seems you can now `disable` a repository as requested. See the example below (pulled from the doc page):
```
# Example removing a repository and cleaning up metadata cache
- name: Remove repository (and clean up left-over metadata)
  yum_repository:
    name: epel
    state: absent
  notify: yum-clean-metadata
  ```
  
  Recommend closing this issue.
