### ISSUE TITLE
Synchronize module never preserves times

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#41182]
##### SUMMARY
In `synchronize` module, no matter the value of `times` parameter, the destination timestamp __always__ gets updated.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

synchronize

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pkara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

(no output)

##### OS / ENVIRONMENT

```
$ uname -a
Linux awx 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

##### STEPS TO REPRODUCE

```yaml
- name: sync_config -> Sync mapping pipelines directory
  synchronize:
    src: "{{ logstash_config_checkout_dir }}/mapping_pipelines/"
    dest: /home/ansible/mapping_pipelines/
    recursive: yes
    owner: no
    group: no
    perms: no
    times: no
  delegate_to: "{{ inventory_hostname }}"
  become: yes
```

##### EXPECTED RESULTS

Owner/group/perms/times should remain unchanged (and perhaps therefore the task should end up as `changed:no` )

##### ACTUAL RESULTS

Files' timestamps __always__ get updated (same when experimenting with `times: yes`)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/files/synchronize.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/files/synchronize.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @tima
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by udondan** [comment]
Same here, task always has changed status, no matter what options are set.

**Comment by udondan** [comment]
Adding `checksum: yes` solved it for me.

```
- name: sync_config -> Sync mapping pipelines directory
  synchronize:
    src: "{{ logstash_config_checkout_dir }}/mapping_pipelines/"
    dest: /home/ansible/mapping_pipelines/
    recursive: yes
    owner: no
    group: no
    perms: no
    times: no
    checksum: yes
  delegate_to: "{{ inventory_hostname }}"
  become: yes
```
