### ISSUE TITLE
get_url is not working

### ISSUE THREAD

**Issue by alenavorozhbieva** [ansible/ansible#41180]
##### SUMMARY

Trying to copy file via ftp using get_url. The result is "Request failed: <urlopen error ftp error: 500 PASS out of sequence" message. 

But I can successfully execute this command on managed machine:
sftp {username}@{some_ip}:/{some_path} /home/centos/{file_name}

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

get_url
##### ANSIBLE VERSION

```
ansible 2.5.4
python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

No changes were done

##### STEPS TO REPRODUCE

```yaml
---
- hosts: {machine_group_name}
become: true
tasks: 
- name: getByFtp
get_url:
url: ftp://{some_ip}/{some_path} 
dest: /home/centos/{file_name}
url_password: {password}
url_username: {username}
```

##### ACTUAL RESULTS

```
"msg": "Request failed: <urlopen error ftp error: 500 PASS out of sequence.>"
```
