### ISSUE TITLE
vmware_host_config_manager long integer error

### ISSUE THREAD

**Issue by LastCaress77** [ansible/ansible#41212]
##### SUMMARY

Changing advanced options that are flagged in vCenter as (long integer) fails. 
##### ISSUE TYPE
 - Bug Report
Changing advanced options that are flagged in vCenter as (long integer) fails. Changing advanced options that are flagged in vCenter as (integer/string) succeed.
Security.AccountUnlockTime (integer) - Success
UserVars.DcuiTimeOut (long integer) - Failure

msg: 'Failed to update option/s as one or more OptionValue contains an invalid value: A specified parameter was not correct:  '
##### COMPONENT NAME

vmware_host_config_manager
##### ANSIBLE VERSION

```
ansible 2.5.2
python version 2.7.13
RHEL 6 airgapped
```

##### CONFIGURATION

airgap
##### OS / ENVIRONMENT

airgap
##### STEPS TO REPRODUCE

run playbook

```yaml
- name: ESXi Advanced Settings
  delegate_to: localhost
  VMware_host_config_manager:
  hostname: vcenter
  username: vcenter admin
  password: ansible_password
  validate_certs: no
  esxi_hostname: '{{ inventory_hostname }}'
  options:
     'Security.AccountUnlockTime': 900   # works (integer)
     'UserVars.DcuiTimeOut': 600             # fails (long integer)
```

##### EXPECTED RESULTS

Value change
##### ACTUAL RESULTS

error

```
msg: 'Failed to update option/s as one or more OptionValue contains an invalid value: A specified parameter was not correct:  '
```
