### ISSUE TITLE
azure_rm_networkinterface should have support to enable accelerated networking  for network interface.

### ISSUE THREAD

**Issue by tsukashusan** [ansible/ansible#41218]
##### SUMMARY

Current module does not have support for following features while a NetworkInterface gets created.

    NetworkInterface
    Accelerated networking flag to enable/disable SR-IOV based networking.

New APIs supporting these features are available in Azure Python SDK.
(e.g. https://docs.microsoft.com/ja-jp/python/api/azure.mgmt.network.v2018_02_01.models.networkinterface?view=azure-python)

NetworkInterface(*, id: str = None, location: str = None, tags=None, virtual_machine=None, network_security_group=None, ip_configurations=None, dns_settings=None, mac_address: str = None, primary: bool = None, **enable_accelerated_networking**: bool = None, enable_ip_forwarding: bool = None, resource_guid: str = None, provisioning_state: str = None, etag: str = None, **kwargs) -> None

There is already a similar issue.
https://github.com/ansible/ansible/issues/34032
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

azure_rm_networkinterface
##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.4
  config file = None
  configured module search path = ['/home/ubuntu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
```

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.5 (Maipo)
##### STEPS TO REPRODUCE

```yaml
- name: Create a network interface with private IP address only (no Public IP)
  azure_rm_networkinterface:
    name: nic001
    resource_group: Testing
    virtual_network_name: vnet001
    subnet_name: subnet001
    enable_accelerated_networking: True
```
