### ISSUE TITLE
vmware_guest module always create disks in a same datastore even configure another datastore

### ISSUE THREAD

**Issue by jenningsloy318** [ansible/ansible#41227]
##### SUMMARY
when I try to clone a new vm from existing vm using following playbook, which configure two disks that are in different datastores, but eventually two disks are created in the same datastore.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 vmware_guest 
##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jenningsl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION
no special conf or changes 
##### OS / ENVIRONMENT
running on a centos 7.4 VM 
##### STEPS TO REPRODUCE

```yaml
 - vmware_guest:
      hostname: 10.36.51.11
      username: xxxx
      password: xxxxx
      validate_certs: no
      datacenter: yuhua
      cluster: App-Cluster
      resource_pool: DevOps Applications
      folder: DevOps Applications
      name: yh-vm-mysql-prod02
      template: centos7_4
      state: poweredon
      force: yes
      disk:
      - size_gb: 60
        datastore: OS
      - size_gb: 40
        datastore: Data
      networks:
      - name: VLAN101
        ip: 10.36.52.167
        netmask: 255.255.255.192
        gateway: 10.36.52.129
        dns_servers:
        - 114.114.114.114
      hardware:
        memory_mb: 4096
        num_cpus: 2
      customization:
        hostname: yh-vm-mysql-prod02
```

##### EXPECTED RESULTS
VM yh-vm-mysql-prod02 has two disks, one is on datastore OS and other one on datastore Data 
##### ACTUAL RESULTS

VM yh-vm-mysql-prod02 has two disks,  both of them are on datastore OS

#### COMMAND OUTPUT
```
 PLAY [Clone template and customize] *********************************************************************************************************************************************************

TASK [Gathering Facts] **********************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [vmware_guest] *************************************************************************************************************************************************************************
changed: [127.0.0.1]

PLAY RECAP **********************************************************************************************************************************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=0

```
