### ISSUE TITLE
[vmware-guest_tools_wait] can't find VM although it definitly exists

### ISSUE THREAD

**Issue by shibumi** [ansible/ansible#41231]
<!---
Verify first that your issue/request is not already reported on GitHub.
THIS FORM WILL BE READ BY A MACHINE, COMPLETE ALL SECTIONS AS DESCRIBED.
Also test if the latest release, and devel branch are affected too.
ALWAYS add information AFTER (OUTSIDE) these html comments.
Otherwise it may end up being automatically closed by our bot. -->

##### SUMMARY
The module **vmware_guest_tools_wait** is unable to find the VMs name via `name` parameter.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
<!--- Insert, BELOW THIS COMMENT, the name of the module, plugin, task or feature.
Do not include extra details here, e.g. "vyos_command" not "the network module vyos_command" or the full path-->

**vmware_guest_tools_wait**

##### ANSIBLE VERSION
<!--- Paste, BELOW THIS COMMENT, verbatim output from "ansible --version" between quotes below -->
```
ansible 2.5.3
  config file = /root/ansible-vxlan/ansible.cfg
  configured module search path = ['/root/ansible-vxlan/library']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]

```

##### CONFIGURATION
<!--- If using Ansible 2.4 or above, paste, BELOW THIS COMMENT, the results of "ansible-config dump --only-changed"
Otherwise, mention any settings you have changed/added/removed in ansible.cfg
(or using the ANSIBLE_* environment variables).-->
```
ANSIBLE_PIPELINING(/root/ansible-vxlan/ansible.cfg) = True
DEFAULT_HOST_LIST(/root/ansible-vxlan/ansible.cfg) = ['/root/ansible-vxlan/hosts']
DEFAULT_MODULE_PATH(/root/ansible-vxlan/ansible.cfg) = ['/root/ansible-vxlan/library']
DEFAULT_ROLES_PATH(/root/ansible-vxlan/ansible.cfg) = ['/root/ansible-vxlan/roles']
DEFAULT_SCP_IF_SSH(/root/ansible-vxlan/ansible.cfg) = True
RETRY_FILES_ENABLED(/root/ansible-vxlan/ansible.cfg) = False
```
##### OS / ENVIRONMENT
<!--- Mention, BELOW THIS COMMENT, the OS you are running Ansible from, and the OS you are
managing, or say "N/A" for anything that is not platform-specific.
Also mention the specific version of what you are trying to control,
e.g. if this is a network bug the version of firmware on the network device.-->

Host Running Ansible: Arch Linux
Target Host: VMWare ESXI Hosts with Ubuntu 18.04 Template
ESXI Version: 6.0.0

##### STEPS TO REPRODUCE
<!--- For bugs, show exactly how to reproduce the problem, using a minimal test-case.
For new features, show how the feature would be used. -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml
- name: clone from VM templates
  vmware_guest:
    hostname: xxx.xxx.xxx.xxx
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_password }}"
    datacenter: TUC-Test
    esxi_hostname: "{{ item.esxi_hostname }}"
    validate_certs: no
    folder: /cre13
    name: "{{ item.name}}"
    state: poweredon
    # Workaround for open-vm-tools bug
    template: ubuntu18.04-template-official
    annotation: "Created via Ansible for VXLAN Test"
    networks:
      - name: "xxx.xxx.xxx.xxx%2f27_vlan1306_vinst6"
        start_connected: True
      - name: "VTEPs"
        start_connected: True
  with_items: "{{ infrastructure }}"
  delegate_to: localhost


- name: Wait for VMWare tools to become available by name
  vmware_guest_tools_wait:
    hostname: xxx.xxx.xxx.xxx
    username: "{{ vsphere_user }}"
    password: "{{ vsphere_password }}"
    folder: /TUC-Test/cre13/
    validate_certs: no
    name: "{{ item.name }}"
  with_items: "{{ infrastructure }}"
  delegate_to: localhost

```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->

**vmware_guest_tools_wait** should find the VM and wait for running guest tools

##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->
The VM has no all specified network devices, but no device is in the State `connected` and I need to attach them manually to the VM.


`ansible-playbook -vvv playbooks/vxlan.yml`
```
TASK [create_vm : clone from VM templates] ************************************************************************************************************************************************************************************************************************************************************************************
task path: /root/ansible-vxlan/roles/create_vm/tasks/main.yml:3
Using module file /usr/lib/python3.6/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
ok: [localhost -> localhost] => (item={'name': 'vvtep1', 'esxi_hostname': 'xxx.xxxx.xxx.xxx', 'ip_address': 'xxx.xxx.xxx.xxx'}) => {
    "changed": false,                                         
    "invocation": {                                          
        "module_args": {          
            "annotation": "Created via Ansible for VXLAN Test",
            "cdrom": {},         
            "cluster": null,                            
            "customization": {},                          
            "customvalues": [],  
            "datacenter": "TUC-Test",
            "disk": [],                 
            "esxi_hostname": "xxx.xxx.xxx.xxx",
            "folder": "/cre13",
            "force": false,
            "guest_id": null,                                     
            "hardware": {},                
            "hostname": "xxx.xxx.xxx.xxx",
            "is_template": false,
            "linked_clone": false,  
            "name": "vvtep1",                                                                  
            "name_match": "first",                      
            "networks": [                                                                                                                        
                {                                             
                    "name": "xxx.xxx.xxx.xxx%2f27_vlan1306_vinst6",
                    "start_connected": true
                },                                             
                {                
                    "name": "VTEPs",                    
                    "start_connected": true
                }              
            ],                       
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,                                     
            "resource_pool": null,
            "snapshot_src": null,
            "state": "poweredon",                        
            "template": "ubuntu18.04-template-official",
            "username": "xxx",                          
            "uuid": null,        
            "validate_certs": false,
            "wait_for_ip_address": false
        }                                                                                                                                                                                                                                                                                                                      
    },                                                          
    "item": {                                                                                             
        "esxi_hostname": "xxx.xxx.xxx.xxx",         
        "ip_address": "xxx.xxx.xxx.xxx",                 
        "name": "vvtep1"                                                                                                                         
    }                
}    

      TASK [create_vm : Wait for VMWare tools to become available by name] *******************************************************************************
task path: /root/ansible-vxlan/roles/create_vm/tasks/main.yml:26
Using module file /usr/lib/python3.6/site-packages/ansible/modules/cloud/vmware/vmware_guest_tools_wait.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root             
<localhost> EXEC /bin/sh -c '/usr/bin/python && sleep 0'      
failed: [localhost -> localhost] (item={'name': 'vvtep1', 'esxi_hostname': xxx.xxx.xxx.xxx', 'ip_address': 'xxx.xxx.xxx.xxx'}) => {
    "changed": false,           
    "invocation": {                 
        "module_args": {                                                                       
            "folder": "TUC-Test/cre13",                 
            "hostname": "xxx.xxx.xxx.xxx",                                                                                       
            "name": "vvtep1",                                 
            "name_match": "first",                       
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,                                       
            "username": "cre13", 
            "uuid": null,                                       
            "validate_certs": false
        }                      
    },                                                                                                                                              
    "item": {                                                                 
        "esxi_hostname": "xxxx.xxx.xxx.xxx",    
        "ip_address": "xxx.xxx.xxx.xxx",
         "name": "vvtep1"                            
    },                                                           
    "msg": "Unable to wait for tools for non-existing VM vvtep1"
}                                                                  

```

As you can see the logs the VM is definitly created unter the Path: `/TUC-Test/cre13/vvtep1`, but the module `vmware_guest_tools_wait` can't find it with settings `folder: "/TUC-Test/cre13` and `name: "vvtep1"`
