### ISSUE TITLE
os_subnet should remove obsolete host_route

### ISSUE THREAD

**Issue by juame** [ansible/ansible#41235]
##### SUMMARY
Ansible Module for OpenStack can't remove host_routes from OpenStack subnets. It would be great to remove static routes from subnets with Ansible.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

os_subnet

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### STEPS TO REPRODUCE

If a host_route is not existing in the dictionary `host_routes` anymore, it should get removed by Ansible. If a host_route state is set to `absent` (explicitly) it should get removed, too.

```yaml
- os_subnet:
    state: present
    network_name: network1
    name: net1subnet
    cidr: 192.168.0.0/24
    dns_nameservers:
       - 8.8.8.7
       - 8.8.8.8
    host_routes:
       - destination: 0.0.0.0/0
         nexthop: 12.34.56.78
       - destination: 192.168.0.0/24
         nexthop: 192.168.0.1
         state: absent
```

##### EXPECTED RESULTS

Ansible should remove the route for `192.168.0.0/24`.

##### ACTUAL RESULTS

If the host_route isn't in the dictionary anymore, it won't get removed by Ansible.
If state is set to absent - it's not a valid dictionary key:

```
 {"changed": false, "msg": "(400) Client Error for url: https://host.example.com:9696/v2.0/subnets/1234-ff85-asdf-asdf-123asdf123.json Invalid input for host_routes. Reason: Validation of dictionary's keys failed. Expected keys: set(['nexthop', 'destination']) Provided keys: set([u'nexthop', u'state', u'destination'])."}
```
