### ISSUE TITLE
Synchronize module is hard-coded to disable connection sharing resulting in network ban

### ISSUE THREAD

**Issue by pneerincx** [ansible/ansible#41262]
##### SUMMARY
synchronize module does not respect ssh option for connection sharing by using hard-coded SSH control path 'none'. Many servers limit the amount of SSH connections that can be made within a certain amount of time (e.g. max 5 connections per minute). When connection sharing is disabled a playbook, that uses synchronize with a list of files/dirs to sync and that worked a first time, may fail when executed a second time. As the data is already in sync, rsync is done quickly resulting in many rsync over ssh connections being made in a short amount of time and a (temporary) network ban. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
synchronize

##### ANSIBLE VERSION
```
ansible 2.4.2.0
```

##### OS / ENVIRONMENT
"N/A"

##### STEPS TO REPRODUCE
In lib/ansible/modules/files/synchronize.py 
```
ssh_cmd = [module.get_bin_path('ssh', required=True), '-S', 'none']
```
should be changed to:
```
ssh_cmd = [module.get_bin_path('ssh', required=True)]
```
in order to be able to synchronize a list of items reliably and reproducible in a playbook like this: 
```yaml
  - name: Synchronize a list of data items.
    synchronize: src="{{ pb_remote_dir }}/data/{{ item.src }}" dest="{{ dir_on_target_host }}/data/" archive='yes' mode='pull' use_ssh_args='yes'
    delegate_to: "{{ inventory_hostname }}"
    with_items:
      - src: "item1"
      - src: "item2"
      - src: "item3"
      - src: "some_other_item"
      - src: "anotherOne"
      - src: "thereIsMoreToSync"
```

##### EXPECTED RESULTS
When SSH connection sharing is configured in a user's .ssh/config file or Ansible config, the synchronize module respects those settings and is not hard-coded to overrule them.
The
```yaml
use_ssh_args='yes'
```
option for the synchronize module works as expected.

##### ACTUAL RESULTS
Running the playbook hangs waiting for a network timeout, because we got a (temporary) ban and cannot create ssh sessions anymore.
