### ISSUE TITLE
Get SQS url as return value

### ISSUE THREAD

**Issue by abhigarg28** [ansible/ansible#41260]
##### SUMMARY
Currently there is no way to get the SQS url of an existing queue or a newly created queue either in ansible 2.5 or 2.6

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
`lib/ansible/modules/cloud/amazon/sqs_queue.py`

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/abhi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
abhi@:~$ ansible-config dump --only-changed
abhi@:~$ 

##### OS / ENVIRONMENT
Running from - ubuntu 18.04
Managing - RHEL 7

##### STEPS TO REPRODUCE
It is pretty simple to reproduce, create a new sqs queue and there is just no way to get the queue_url.

```yaml
- name: Create SQS queue
  aws_sqs_queue:
    aws_access_key: "{{ profile_aws_access_key }}"
    aws_secret_key: "{{ profile_aws_secret_key }}"
    security_token: "{{ profile_security_token }}"
    name: "sqs_queue"
    region: "{{ default_region }}"
    default_visibility_timeout: 300
    state: present
  register: sqs_queue

- debug: var=sqs_queue
```

##### EXPECTED RESULTS
I am expecting to have a queue_url value in the returned parameters.

##### ACTUAL RESULTS

```
ok: [localhost] => {
    "ses_queue": {
        "changed": false, 
        "default_visibility_timeout": "300", 
        "delivery_delay": "0", 
        "failed": false, 
        "maximum_message_size": "262144", 
        "message_retention_period": "345600", 
        "name": "sqs_queue", 
        "policy": null, 
        "queue_arn": ERASED, 
        "receive_message_wait_time": "0", 
        "redrive_policy": null, 
        "region": "us-east-1"
    }
}
```
