### ISSUE TITLE
template module: failed_when ignored if become fails due to lack of user

### ISSUE THREAD

**Issue by jeeb** [ansible/ansible#41285]
##### SUMMARY
If a user on a host is not yet available and the template module is being called with `become: yes` and `become_user: nonexistent_user`, the default sudo module's failure at becoming will cause the task to fail even if in check mode and `failed_when: task_variable is failed and not ansible_check_mode`, which should in theory prevent failures in check mode.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

template

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = None
  configured module search path = [u'/home/jeeb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jeeb/ansible_virtualenv/lib/python2.7/site-packages/ansible
  executable location = /home/jeeb/ansible_virtualenv/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
---

- hosts: localhost
  tasks:
    - name: Template Test Case
      become: yes
      become_user: totally_unavailable_user
      template:
        src: "foo.j2" # create this manually with touch or so
        dest: "/something/blah"
      register: "random_task"
      failed_when: "random_task is failed and not ansible_check_mode"
```

##### EXPECTED RESULTS

In check mode, even if the user `totally_unavailable_user` doesn't exist, the task should not fail.

##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [localhost]

TASK [Template Test Case] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Failed to get information on remote file (/something/blah): sudo: unknown user: totally_unavailable_user\nsudo: unable to initialize policy plugin"}
```
or
```
PLAY [localhost] ***************************************************************************************************************************

TASK [Gathering Facts] *********************************************************************************************************************
ok: [localhost]

TASK [Template Test Case] ******************************************************************************************************************
fatal: [localhost]: FAILED! => {"msg": "Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chown: invalid user: ‘totally_unavailable_user’\n}). For information on working around this, see https://docs.ansible.com/ansible/become.html#becoming-an-unprivileged-user"}
```
