### ISSUE TITLE
ERROR! 'yum' is not a valid attribute for a Play

### ISSUE THREAD

**Issue by brucegogo** [ansible/ansible#41298]
##### SUMMARY
```
[root@ansible tasks]# ansible-playbook  --syntax-check  main.yaml 
ERROR! 'yum' is not a valid attribute for a Play

The error appears to have been in '/etc/ansible/roles/zabbix-server/tasks/main.yaml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Install Mysql-server and zabbix-server
  ^ here

The playbook file as below:
[root@ansible tasks]# cat main.yaml 
---
- name: Install Mysql-server and zabbix-server
  yum: name={{ item }} state=latest
  with_items:
             - mysql-server
             - zabbix-server
             - zabbix-server-mysql
             - zabbix-web-mysql
- name: Init Mysql
  shell: mysql_install_db
- name: Start mysql-server
  service: name=mysqld state=started enabled=yes
- name: Set mysql admin password
  shell: /usr/bin/mysqladmin -u root password 'ansible'
- name: Create zabbix master databases
  shell: mysql -u root -p ansible -e 'create database zabbix_master character set utf8 collate utf8_bin;'
- name: Set zabbix master database grant
  shell: mysql -u root -pansible -e 'grant all privileges on zabbix_master.* to zabbix@localhost identified by "master";'
- name: Import zabbix initial data (schema.sql)
  shell: mysql -u zabbix -pmaster zabbix_master < schema.sql
         chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create
- name: Import zabbix initial data (images.sql)
  shell: mysql -uzabbix -pmaster zabbix_master < images.sql
         chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create
- name: Import zabbix initial data (data.sql)
  shell: mysql -uzabbix -pmaster zabbix_master < data.sql
         chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create
- name: change PHP timezone
  shell: sed -e 's@;date.timezone = .*@date.timezone = Asia/Shanghai@g' /etc/php.ini
- name: Copy /etc/zabbix/zabbix_server.conf files
  template: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=644
- name: Start zabbix-server and httpd
  service: name={{ item }} state=started enabled=yes
  with_items:
         - zabbix-server
         - httpd
```
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
yum command 

##### ANSIBLE VERSION
[root@ansible tasks]# ansible --version
ansible 2.6.0a2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/my_modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.6.0a2-py2.7.egg/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

##### CONFIGURATION
[root@ansible tasks]# ansible-config dump --only-changed
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/my_modules']
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 22
DEFAULT_SUDO_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 10
DEPRECATION_WARNINGS(/etc/ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
[root@ansible tasks]# uname -a
Linux ansible 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
Seems any .yaml file including yum command will result this error.
```
[root@ansible tasks]# cat main.yaml 
---
- name: Install Mysql-server and zabbix-server
  yum: name={{ item }} state=latest
  with_items:
             - mysql-server
             - zabbix-server
             - zabbix-server-mysql
             - zabbix-web-mysql
- name: Init Mysql
  shell: mysql_install_db
- name: Start mysql-server
  service: name=mysqld state=started enabled=yes
- name: Set mysql admin password
  shell: /usr/bin/mysqladmin -u root password 'ansible'
- name: Create zabbix master databases
  shell: mysql -u root -p ansible -e 'create database zabbix_master character set utf8 collate utf8_bin;'
- name: Set zabbix master database grant
  shell: mysql -u root -pansible -e 'grant all privileges on zabbix_master.* to zabbix@localhost identified by "master";'
- name: Import zabbix initial data (schema.sql)
  shell: mysql -u zabbix -pmaster zabbix_master < schema.sql
         chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create
- name: Import zabbix initial data (images.sql)
  shell: mysql -uzabbix -pmaster zabbix_master < images.sql
         chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create
- name: Import zabbix initial data (data.sql)
  shell: mysql -uzabbix -pmaster zabbix_master < data.sql
         chdir=/usr/share/doc/zabbix-server-mysql-2.4.6/create
- name: change PHP timezone
  shell: sed -e 's@;date.timezone = .*@date.timezone = Asia/Shanghai@g' /etc/php.ini
- name: Copy /etc/zabbix/zabbix_server.conf files
  template: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=644
- name: Start zabbix-server and httpd
  service: name={{ item }} state=started enabled=yes
  with_items:
         - zabbix-server
         - httpd
```
##### EXPECTED RESULTS
Hope to pass the check.

##### ACTUAL RESULTS
```
[root@ansible tasks]# ansible-playbook  --syntax-check  main.yaml 
ERROR! 'yum' is not a valid attribute for a Play

The error appears to have been in '/etc/ansible/roles/zabbix-server/tasks/main.yaml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Install Mysql-server and zabbix-server
  ^ here
```
