### ISSUE TITLE
s3 cloudfront_distribution: Expected a list, got a odict_values with value odict_values

### ISSUE THREAD

**Issue by bmamouri** [ansible/ansible#41307]
##### SUMMARY
This issue might be related to this PR: https://github.com/ansible/ansible/pull/37340

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudfront_distribution

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /Users/redacted/deployment/presentation/ansible.cfg
  configured module search path = ['/Users/redacted/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/redacted/.local/share/virtualenvs/deployment-urGlj6Al/lib/python3.6/site-packages/ansible
  executable location = /Users/redacted/.local/share/virtualenvs/deployment-urGlj6Al/bin/ansible
  python version = 3.6.5 (default, Apr 12 2018, 13:43:59) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/Users/redacted/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o ControlPath=/tmp/ansible-ssh-%h-%p
HOST_KEY_CHECKING(/Users/redacted/ansible.cfg) = False

##### STEPS TO REPRODUCE

```yaml
---
- name: Set domain URL
  set_fact:
    domain_name: "admin{{ '-' + env if env in ['dev', 'staging'] else '' }}.{{ route53.hosted_zone }}"

- name:
  debug:
    msg: '{{ domain_name }}'

- name: create Cloudfront distribution
  cloudfront_distribution:
    state: present
    alias: '{{ domain_name }}'
    default_root_object: index.html
    origins:
      - id: 'S3-{{ domain_name }}'
        domain_name: '{{ bucket_name }}.s3.amazonaws.com'
        origin_path: ''
        s3_origin_access_identity_enabled: yes
    default_cache_behavior:
      target_origin_id: 'S3-{{ domain_name }}'
      viewer_protocol_policy: redirect-to-https
      allowed_methods:
        items:
          - GET
          - HEAD
        cached_methods:
          - GET
          - HEAD
      forwarded_values:
        query_string: false
        cookies:
          forward: none
      smooth_streaming: false
      compress: false
    custom_error_responses:
      - error_code: 403
        response_page_path: '/index.html'
        response_code: 200
        error_caching_min_ttl: 300
    logging:
      enabled: true
      include_cookies: false
      bucket: hatch-logs.s3.amazonaws.com
      prefix: 'admin-web-cloudfront/{{ env }}/'
    enabled: true
    price_class: PriceClass_100
    viewer_certificate:
      acm_certificate_arn: arn:aws:acm:us-east-1:966878126306:certificate/XXX
      minimum_protocol_version: TLSv1.1_2016
      ssl_support_method: sni-only
    http_version: http2
    ipv6_enabled: yes
  register: cf
```

##### EXPECTED RESULTS
Not get error

##### ACTUAL RESULTS
```
Using module file /Users/redacted/.local/share/virtualenvs/deployment-urGlj6Al/lib/python3.6/site-packages/ansible/modules/cloud/amazon/cloudfront_distribution.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: redacted
<127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/redacted/.ansible/tmp/ansible-tmp-1528441907.4115431-142370866965291 `" && echo ansible-tmp-1528441907.4115431-142370866965291="` echo /Users/redacted/.ansible/tmp/ansible-tmp-1528441907.4115431-142370866965291 `" ) && sleep 0'
<127.0.0.1> PUT /Users/redacted/.ansible/tmp/ansible-local-38981lx2fpuw3/tmpmr5wa37z TO /Users/redacted/.ansible/tmp/ansible-tmp-1528441907.4115431-142370866965291/cloudfront_distribution.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/redacted/.ansible/tmp/ansible-tmp-1528441907.4115431-142370866965291/ /Users/redacted/.ansible/tmp/ansible-tmp-1528441907.4115431-142370866965291/cloudfront_distribution.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/Users/redacted/.local/share/virtualenvs/deployment-urGlj6Al/bin/python3.6m /Users/redacted/.ansible/tmp/ansible-tmp-1528441907.4115431-142370866965291/cloudfront_distribution.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/redacted/.ansible/tmp/ansible-tmp-1528441907.4115431-142370866965291/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/var/folders/pt/scv7gx297rg5ns2nt1f2w90r0000gn/T/ansible_hph1d47g/ansible_module_cloudfront_distribution.py", line 1414, in validate_origins
    return ansible_list_to_cloudfront_list(all_origins.values())
  File "/var/folders/pt/scv7gx297rg5ns2nt1f2w90r0000gn/T/ansible_hph1d47g/ansible_module_cloudfront_distribution.py", line 1138, in ansible_list_to_cloudfront_list
    raise ValueError('Expected a list, got a {0} with value {1}'.format(type(list_items).__name__, str(list_items)))
ValueError: Expected a list, got a odict_values with value odict_values([{'id': 'S3-admin-dev.redacted.net', 'domain_name': 'admin-dev.redacted.net.s3.amazonaws.com', 'origin_path': '', 'custom_headers': {'quantity': 0}, 's3_origin_config': {'origin_access_identity': 'origin-access-identity/cloudfront/E352DFCNFOKYBB'}}])

fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "alias": "admin-dev.redacted.net",
            "aliases": [
                "admin-dev.redacted.net"
            ],
            "aws_access_key": null,
            "aws_secret_key": null,
            "cache_behaviors": null,
            "caller_reference": null,
            "comment": null,
            "custom_error_responses": [
                {
                    "error_caching_min_ttl": 300,
                    "error_code": 403,
                    "response_code": 200,
                    "response_page_path": "/index.html"
                }
            ],
            "default_cache_behavior": {
                "allowed_methods": {
                    "cached_methods": [
                        "GET",
                        "HEAD"
                    ],
                    "items": [
                        "GET",
                        "HEAD"
                    ]
                },
                "compress": false,
                "forwarded_values": {
                    "cookies": {
                        "forward": "none"
                    },
                    "query_string": false
                },
                "smooth_streaming": false,
                "target_origin_id": "S3-admin-dev.redacted.net",
                "viewer_protocol_policy": "redirect-to-https"
            },
            "default_origin_domain_name": null,
            "default_origin_path": null,
            "default_root_object": "index.html",
            "distribution_id": null,
            "e_tag": null,
            "ec2_url": null,
            "enabled": true,
            "http_version": "http2",
            "ipv6_enabled": true,
            "logging": {
                "bucket": "hatch-logs.s3.amazonaws.com",
                "enabled": true,
                "include_cookies": false,
                "prefix": "admin-web-cloudfront/dev/"
            },
            "origins": [
                {
                    "custom_headers": {
                        "quantity": 0
                    },
                    "domain_name": "admin-dev.redacted.net.s3.amazonaws.com",
                    "id": "S3-admin-dev.redacted.net",
                    "origin_path": "",
                    "s3_origin_config": {
                        "origin_access_identity": "origin-access-identity/cloudfront/E352DFCNFOKYBB"
                    }
                }
            ],
            "price_class": "PriceClass_100",
            "profile": null,
            "purge_aliases": false,
            "purge_cache_behaviors": false,
            "purge_custom_error_responses": false,
            "purge_origins": false,
            "purge_tags": false,
            "region": null,
            "restrictions": null,
            "security_token": null,
            "state": "present",
            "tags": {},
            "validate_certs": true,
            "viewer_certificate": {
                "acm_certificate_arn": "arn:aws:acm:us-east-1:966878126306:certificate/XXX",
                "minimum_protocol_version": "TLSv1.1_2016",
                "ssl_support_method": "sni-only"
            },
            "wait": false,
            "wait_timeout": 1800,
            "web_acl_id": null
        }
    },
    "msg": "Error validating distribution origins: Expected a list, got a odict_values with value odict_values([{'id': 'S3-admin-dev.redacted.net', 'domain_name': 'admin-dev.redacted.net.s3.amazonaws.com', 'origin_path': '', 'custom_headers': {'quantity': 0}, 's3_origin_config': {'origin_access_identity': 'origin-access-identity/cloudfront/E352DFCNFOKYBB'}}])"
```
