### ISSUE TITLE
nxos_l3_interface fails on loopbacks and svi interfaces because of no switchport

### ISSUE THREAD

**Issue by netixx** [ansible/ansible#41310]
##### SUMMARY

When using nxos_l3_interface on loopbacks (loopback1) and SVI (Vlan10), the modules unconditionnaly adds the `no switchport` command which fails on those interfaces.

In `nxos_ip_interface` - the now deprecated module that used to perform this - the `get_interface_type` method was use to conditionnaly insert `no switchport`. This could be ported to `nxos_l3_interface` to solve this issue 

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

nxos_l3_interface

##### ANSIBLE VERSION

```
ansible 2.5.4
python version = 3.5.2
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
- name: Configure IP addr on lo
  nxos_l3_interface:
    name: Loopback0
    ipv4: 10.0.0.1/24

- name: Configure IP on SVI
  nxos_l3_interface:
    name: Vlan10
    ipv4: 10.0.1.1/24
```

##### EXPECTED RESULTS

Configuration on the interface with the correct IP
##### ACTUAL RESULTS

Module failure (crash).

```

```

Thank you
