### ISSUE TITLE
edit snow_record so it can reach unique service-now urls

### ISSUE THREAD

**Issue by jmcleroy** [ansible/ansible#41320]
##### SUMMARY

Need to add host parameter for connection in order to reach unique service-now url. For example dev.service-now.dev.com and the current module only supports the instance parameter.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

snow_record
##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = None
  configured module search path = [u'/Users/jmcleroy/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### OS / ENVIRONMENT

Mac OS to ServiceNow

##### STEPS TO REPRODUCE

```yaml
---
- name: executue sth
  hosts: localhost
  connection: local
  gather_facts: no
  ignore_errors: True
  tasks:

    - name: Attach a file to an incident
      snow_record:
        username: admin
        password: Test1234
        host: dev54916.service-now.com
        state: present
        data:
          short_description: "This is a test incident opened by Ansible"
          severity: 3
          priority: 2
      register: new_incident
```

##### EXPECTED RESULTS

To be able to connect to unique service-now urls
##### ACTUAL RESULTS

It will fail with host is not a parameter avaialble

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (snow_record) module: host Supported parameters include: attachment, data, instance, lookup_field, number, password, state, table, username"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/notification/snow_record.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/notification/snow_record.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @garbled1
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by iamteedoh** [comment]
Hi All,

Wondering if there is any progress on this? I'm looking to implement some automation around this module but definitely need to support the "host" parameter. Out of curiosity, if there is a host such as https://titotest.service-now.com, should adding just titotest as the instance work?

**Comment by varunchopra** [comment]
@oh4 Yes, this works.

@jmcleroy Service Now should've given you an instance name for use at your company. Use that. The syntax is `instance.service-now.com`.

**Comment by n3pjk** [comment]
Use `instance: titotest` and the module will use the correct URL.

**Comment by martbhell** [comment]
@n3pjk I now closed #45553 as some different changes would be needed after the nice refactoring of the snow_record module :) 

Let's say we have an on-premise installation and we have not been given an instance from service-now. I have checked the HTTPS certificate on our on-premise and it does not have an alt name pointing to a service-now.com instance. So I don't see how using instance: would work for us. 

I think we need the host parameter, just like @oh4 .

**Comment by n3pjk** [comment]
I don't see a problem with adding a 'hostname' parameter that would be exclusive of 'instance' and would accept an FQDN. I had been sidetracked on other projects this last month, but I should be able to get back on this very soon.
________________________________

**Comment by Akasurde** [comment]
resolved_by_pr #66184

**Comment by Akasurde** [comment]
@jmcleroy, Could you please check PR #66184 and let us know if it works for you ? <br><br>Please check [How to test a PR](https://docs.ansible.com/ansible/latest/dev_guide/testing.html#how-to-test-a-pr) for more help. <br><br> Thanks. <br><br> needs_info

**Comment by ansibot** [comment]
@jmcleroy This issue is waiting for your response. Please respond or the issue will be closed.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by martbhell** [comment]
I have tested this with a cmdb (so not incident as in the examples). I was able to get a list of servers in our cmdb which is what I wanted. Works for me.

CentOS 7.7. Python2.

The results was not what I expected but that is probably because I didn't spend much time writing a good pysnow query. Took me a while to figure out I wanted to query Name and return name. Why that is the case I don't know. Like, is that a bug in pysnow, this ansible module or our servicenow setup? =)

Setup:

```
$ python2 virtualenv
$ pip install -U wheel setuptools pysnow 
$ cd ansible
$ git add remote pysnow https://github.com/Akasurde/ansible/
$ git checkout i62018
$ cd hacking
$ source env-setup
$ $EDITOR ../lib/ansible/module_utils/service_now.py 
# and disabling CA verification because I couldn't find an easy tool to "mkcabundle https://mycustomservicenow.example.org" - like in https://pysnow.readthedocs.io/en/latest/usage/client.html
```

from ansible --version
```
ansible-playbook 2.10.0.dev0
  config file = None
  configured module search path = [u'/home/myuserhi/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/myuserhi/Git/ansible/lib/ansible
  executable location = /home/myuserhi/Git/ansible/bin/ansible-playbook
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
No config file found; using defaults
```

and creating a playbook:
```
- name: test
  hosts: localhost

  tasks:
  - name: Search for incident using host instead of instance
    snow_record_find:
      username: myusername
      password: mypass
      host: customservicenow.example.org
      table: cmdb_servers
      query:
        AND:
          contains:
            Name: "mysubdomain.example.org"
      return_fields:
        - Name
        - name
```

and it throws this out in debug mode:

```
ok: [localhost] => {
    "changed": false, 
    "host": "customservicenow.example.org", 
    "instance": null, 
    "invocation": {
        "module_args": {
            "client_id": null, 
            "client_secret": null, 
            "host": "customservicenow.example.org", 
            "instance": null, 
            "max_records": 20, 
            "order_by": "-created_on", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "query": {
                "AND": {
                    "contains": {
                        "Name": "mysubdomain.example.org"
                    }
                }
            }, 
            "return_fields": [
                "Name", 
                "name"
            ], 
            "table": "cmdb_servers", 
            "username": "myusername"
        }
    }, 
    "max_records": 20, 
    "query": {
        "AND": {
            "contains": {
                "Name": "mysubdomain.example.org"
            }
        }
    }, 
    "record": [
        {
            "name": " host1.mysubdomain.example.org"
        }, 
        {
            "name": "somethingelse.not.example.com"
        }, 
SNIPSNIP
        {
            "name": "somethingelse.foo.foo"
        }
    ], 
    "return_fields": [
        "Name", 
        "name"
    ], 
    "table": "cmdb_servers"
}
```
