### ISSUE TITLE
first_found (lookup) example from docs not working

### ISSUE THREAD

**Issue by kees-closed** [ansible/ansible#41321]
##### SUMMARY
I want to replace the `with_first_found` with a loop + lookup. Took the example from the [docs](https://docs.ansible.com/ansible/2.5/plugins/lookup/first_found.html), but that one fails.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
lookup

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /home/kjong/git/ansible/ansible.cfg
  configured module search path = [u'/home/kjong/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]

```

##### CONFIGURATION

ANSIBLE_PIPELINING(/home/kjong/git/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/kjong/git/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s
DEFAULT_BECOME(/home/kjong/git/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/home/kjong/git/ansible/ansible.cfg) = True
DEFAULT_BECOME_METHOD(/home/kjong/git/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/home/kjong/git/ansible/ansible.cfg) = root
DEFAULT_FORKS(/home/kjong/git/ansible/ansible.cfg) = 16
DEFAULT_HOST_LIST(/home/kjong/git/ansible/ansible.cfg) = [u'/home/kjong/git/ansible/inventory.ini']
DEFAULT_MANAGED_STR(/home/kjong/git/ansible/ansible.cfg) = # Ansible managed
DEFAULT_REMOTE_PORT(/home/kjong/git/ansible/ansible.cfg) = 4443
DEFAULT_SQUASH_ACTIONS(/home/kjong/git/ansible/ansible.cfg) = ['apk', 'apt', 'dnf', 'homebrew', 'pacman', 'pkgng', 'yum', 'zypper', 'package']
DIFF_CONTEXT(/home/kjong/git/ansible/ansible.cfg) = 3
DISPLAY_SKIPPED_HOSTS(/home/kjong/git/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/kjong/git/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Running Ansible from Fedora 28 on a Fedora 28 machine.

##### STEPS TO REPRODUCE

The task below works with `with_first_found`, but the supposedly equivalent lookup with the first_found filter fails.

```yaml
- block:
  - name: include os environment vars
    include_vars: "{{ item }}"
    with_first_found:
      - "{{ ansible_os_family }}.yml"
      - default.yaml

  - name: read vars from first file found, use 'vars/' relative subdir
    include_vars: "{{lookup('first_found', findme, paths=['vars'])}}"
    vars:
      findme:
       - '{{ansible_os_family}}.yml'
       - default.yml
  tags: ttest
```

##### EXPECTED RESULTS
I expected the same results for both. Is the documentation invalid? Or is this a bug?

##### ACTUAL RESULTS

Ran the task with -vvvv
```
TASK [common : read vars from first file found, use 'vars/' relative subdir] ************************************************************************************************************************************************************************************************************************************************************************************************
task path: /home/kjong/git/ansible/roles/common/tasks/main.yml:10
fatal: [defiant]: FAILED! => {
    "msg": "{{lookup('first_found', findme, paths is not a valid option in debug"
}
```

Also ran the task without verbose output (since it gives an error about debug)
```
TASK [common : read vars from first file found, use 'vars/' relative subdir] ************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [defiant]: FAILED! => {"msg": "{{lookup('first_found', findme, paths is not a valid option in debug"}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/plugins/lookup/__init__.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/__init__.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by mkrizek** [comment]
Thanks for the bug report! Can you try using examples from https://docs.ansible.com/ansible/devel/plugins/lookup/first_found.html? It should be fixed there.

**Comment by mkrizek** [comment]
Note, it was fixed very recently and didn't get backported to `2.5` yet.

**Comment by mkrizek** [comment]
https://github.com/ansible/ansible/pull/40821

**Comment by kees-closed** [comment]
Using the updated example from the docs works just as well as the `with_first_found`, thanks! I think this issue can be closed.

```
  - name: read vars from first file found, use 'vars/' relative subdir
    include_vars: "{{lookup('first_found', params)}}"
    vars:
      params:
        files:
          - '{{ansible_os_family}}.yml'
          - default.yml
        paths:
          - 'vars'
```
