### ISSUE TITLE
asa_command using network_cli causing failures

### ISSUE THREAD

**Issue by dbrouss** [ansible/ansible#41337]
##### SUMMARY
When using the asa_command plugin with network_cli and a bad password, the "registered" variable cannot be accessed without a failure of the playbook.  In fact, access to the variable results in the original command being run again (at least it appears so based on timing and performing a tcpdump).  This was not an issue with the provider method.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

network_cli

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dbrousseau/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)
Cisco Adaptive Security Appliance Software Version 9.9(2)1

##### STEPS TO REPRODUCE

Create a playbook that connects via network_cli instead of the provider model.  Provide the incorrect password for either the ansible_ssh_pass or the ansible_become_pass.  Register the output.  If the connection fails and you try to access the registered value in any way, it will result in a failure of the playbook and it appears to attempt to run the command again on the remote device.

```yaml
- hosts: asa_hosts
  gather_facts: false
  connection: network_cli
  become_method: enable
  become: yes
  remote_user: "{{ ansible_ssh_host }}"

  vars:
    # Cisco required variables
    ansible_user: "orchestration"
    ansible_ssh_pass: "good_password"
    ansible_become_pass: "bad_password"
    ansible_network_os: asa
    ansible_ssh_host: "10.0.0.1"

    # This tells the system to keep the ssh connection open within a task
    #ansible_ssh_pipelining: true

  tasks:
  # Test connectivity and privilege to host
  - name: Test connectivity and privilege to host
    ignore_errors: yes
    retries: 0
    asa_command:
      commands: "show curpriv | grep Current.privilege.level"
    register: test_connectivity

  - name: first debug
    debug:
      msg: "First debug complete"
    when: test_connectivity is defined

  - name: second debug
    debug:
      msg: "First debug complete"
    when: test_connectivity is defined
```

##### EXPECTED RESULTS

This works as expected when both passwords are correct.  When an incorrect password is used, I expect the both the first and second debug to run.  I also performed a tcpdump and see that the debug command results in a lot of packets from the Ansible server to the ASA device, so it appears to re-run the command. 

##### ACTUAL RESULTS

When you attempt to pass an incorrect password, I should be able to  

```
[dbrousseau@ansible CiscoASA]$ ansible-playbook -i asa-inventory test_ncli.py -vvv
ansible-playbook 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dbrousseau/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
Parsed /home/dbrousseau/ansible/playbooks/CiscoASA/asa-inventory inventory source with ini plugin

PLAYBOOK: test_ncli.py ********************************************************************************************************************************************************************************
1 plays in test_ncli.py

PLAY [asa_hosts] **************************************************************************************************************************************************************************************
META: ran handlers

TASK [Test connectivity and privilege to host] ********************************************************************************************************************************************************
task path: /home/dbrousseau/ansible/playbooks/CiscoASA/test_ncli.py:22
The full traceback is:
Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 87, in start
    self.connection._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/network_cli.py", line 326, in _connect
    self._terminal.on_become(passwd=auth_pass)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/terminal/asa.py", line 67, in on_become
    raise AnsibleConnectionFailure('unable to elevate privilege to enable mode')
AnsibleConnectionFailure: unable to elevate privilege to enable mode

fatal: [asa_hosts]: FAILED! => {
    "msg": "unable to elevate privilege to enable mode"
}
...ignoring

TASK [first debug] ************************************************************************************************************************************************************************************
task path: /home/dbrousseau/ansible/playbooks/CiscoASA/test_ncli.py:29
The full traceback is:
Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 87, in start
    self.connection._connect()
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/network_cli.py", line 326, in _connect
    self._terminal.on_become(passwd=auth_pass)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/terminal/asa.py", line 67, in on_become
    raise AnsibleConnectionFailure('unable to elevate privilege to enable mode')
AnsibleConnectionFailure: unable to elevate privilege to enable mode

fatal: [asa_hosts]: FAILED! => {
    "msg": "unable to elevate privilege to enable mode"
}
        to retry, use: --limit @/home/dbrousseau/ansible/playbooks/CiscoASA/test_ncli.retry

PLAY RECAP ********************************************************************************************************************************************************************************************
asa_hosts                  : ok=1    changed=0    unreachable=0    failed=1

```
