### ISSUE TITLE
Add or Expand the gitlab module to include subgroups

### ISSUE THREAD

**Issue by aoyawale** [ansible/ansible#41347]
##### SUMMARY
Currently the gitlab_group module does not create subgroups. Either update this module to do subgroups or create a gitlab_subgroup. Is possible with the `python-gitlab` http://python-gitlab.readthedocs.io/en/stable/gl_objects/groups.html#subgroups

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
gitlab_group

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = None
  configured module search path = [u'/home/jlozadad/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /data/git/roles/lmao/lib/python2.7/site-packages/ansible
  executable location = /data/git/roles/lmao/bin/ansible
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

```

##### OS / ENVIRONMENT
Ansible Controller: Fedora 27
Target: Rhel 7.4
Gitlab 10.8.4-ee f80a528 

##### STEPS TO REPRODUCE
This new or updated module would use the same parameters and add a `subgroup`. This will be required and checks that a group has been created before trying for a subgroup.

```
gitlab_group:
  server_url: http://gitlab.dj-wasabi.local
  validate_certs: False
  login_token: WnUzDsxjy8230-Dy_k
  name: my_first_group
  subgroup: my_subgroup
  state: present
or

gitlab_subgroup:
        server_url: http://gitlab.dj-wasabi.local
        validate_certs: False
        login_token: WnUzDsxjy8230-Dy_k
        name: my_subgroup
        group: my_first_group
        state: present
```

##### EXPECTED RESULTS
Create subgroups after the the top main group has been created.

##### ACTUAL RESULTS
subgroups are not an option to create.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/source_control/gitlab_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/source_control/gitlab_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dj-wasabi
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Lunik** [comment]
Maybe simply add `parent_group` parameters should be enought and prevent code duplication.
```
gitlab_group:
  server_url: http://gitlab.dj-wasabi.local
  validate_certs: False
  login_token: WnUzDsxjy8230-Dy_k
  name: my_first_group
  parent: my_parent_group
  state: present
```

according to the gitlab API and the python module, giving `parent_id` is easier. But is it viable ?
```
gitlab_group:
  server_url: http://gitlab.dj-wasabi.local
  validate_certs: False
  login_token: WnUzDsxjy8230-Dy_k
  name: my_first_group
  parent_id: my_parent_group_id
  state: present
```
