### ISSUE TITLE
asa_comand when used with network_cli fails to "become" unless there is an inventory file

### ISSUE THREAD

**Issue by dbrouss** [ansible/ansible#41341]
##### SUMMARY
When using the asa_command plugin with network_cli and setting the "hosts" to 127.0.0.1, ansible is unable to "become" (run "enable"), and if the command cannot run the playbook will fail.  In combination with https://github.com/ansible/ansible/issues/40611 we can end up in a position where we cannot capture the error and proceed.

Switching to use an inventory file, even if the file contains no details, fixes this issue

This is not an issue when using the old "provider" model of connection.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

network_cli
asa_command

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dbrousseau/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)
Cisco Adaptive Security Appliance Software Version 9.9(2)1

##### STEPS TO REPRODUCE

Create a playbook that connects via network_cli instead of the provider model.  Set the "hosts" line to use 127.0.0.1, and run a command that requires privilege.

```yaml
- hosts: 127.0.0.1
  gather_facts: false
  connection: network_cli
  become_method: enable
  become: yes
  remote_user: "{{ ansible_ssh_host }}"

  vars:
    # Cisco required variables
    ansible_user: "orchestration"
    ansible_ssh_pass: "good_password"
    ansible_become_pass: "good_password"
    ansible_network_os: asa
    ansible_ssh_host: "10.0.0.1"

    # This tells the system to keep the ssh connection open within a task
    #ansible_ssh_pipelining: true

  tasks:
  # Test connectivity and privilege to host
  - name: Test connectivity and privilege to host
    ignore_errors: yes
    retries: 0
    asa_command:
      commands: "clear conn address 10.0.0.10"
    register: test_connectivity

  - name: first debug
    debug:
      msg: "First debug complete"
    when: test_connectivity is defined

  - name: second debug
    debug:
      msg: "First debug complete"
    when: test_connectivity is defined

```

##### EXPECTED RESULTS

I expect to be able to pass all of the necessary connection details in extra-vars, and not use an inventory file.  This worked with the old "provider"method, but only partly works with the new network_cli method.  The system logs in, but not goes to enable mode.

##### ACTUAL RESULTS

When you attempt to pass an incorrect password, I should be able to  

```
@ansible CiscoASA]$ ansible-playbook test_ncli.yml -vvv
ansible-playbook 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dbrousseau/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin

PLAYBOOK: test_ncli.yml *******************************************************************************************************************************************************************************
1 plays in test_ncli.yml

PLAY [127.0.0.1] **************************************************************************************************************************************************************************************
META: ran handlers

TASK [Test connectivity and privilege to host] ********************************************************************************************************************************************************
task path: /home/dbrousseau/ansible/playbooks/CiscoASA/test_ncli.yml:23
<172.19.32.44> using connection plugin network_cli (was local)
Using module file /usr/lib/python2.7/site-packages/ansible/modules/network/asa/asa_command.py
<172.19.32.44> ESTABLISH LOCAL CONNECTION FOR USER: dbrousseau
<172.19.32.44> EXEC /bin/sh -c 'echo ~dbrousseau && sleep 0'
<172.19.32.44> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/dbrousseau/.ansible/tmp/ansible-tmp-1528506003.39-231198548385311 `" && echo ansible-tmp-1528506003.39-231198548385311="` echo /home/dbrousseau/.ansible/tmp/ansible-tmp-1528506003.39-231198548385311 `" ) && sleep 0'
<172.19.32.44> PUT /home/dbrousseau/.ansible/tmp/ansible-local-27151QgGgGk/tmpyYzicW TO /home/dbrousseau/.ansible/tmp/ansible-tmp-1528506003.39-231198548385311/asa_command.py
<172.19.32.44> EXEC /bin/sh -c 'chmod u+x /home/dbrousseau/.ansible/tmp/ansible-tmp-1528506003.39-231198548385311/ /home/dbrousseau/.ansible/tmp/ansible-tmp-1528506003.39-231198548385311/asa_command.py && sleep 0'
<172.19.32.44> EXEC /bin/sh -c '/usr/bin/python2 /home/dbrousseau/.ansible/tmp/ansible-tmp-1528506003.39-231198548385311/asa_command.py && sleep 0'
<172.19.32.44> EXEC /bin/sh -c 'rm -f -r /home/dbrousseau/.ansible/tmp/ansible-tmp-1528506003.39-231198548385311/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_Owji6y/ansible_module_asa_command.py", line 200, in <module>
    main()
  File "/tmp/ansible_Owji6y/ansible_module_asa_command.py", line 170, in main
    responses = run_commands(module, commands)
  File "/tmp/ansible_Owji6y/ansible_modlib.zip/ansible/module_utils/network/asa/asa.py", line 124, in run_commands
  File "/tmp/ansible_Owji6y/ansible_modlib.zip/ansible/module_utils/connection.py", line 149, in __rpc__
ansible.module_utils.connection.ConnectionError: clear conn address 10.0.0.10
                          ^
ERROR: % Invalid input detected at '^' marker.
ERROR: Command authorization failed
test02uspvdfw48>

fatal: [127.0.0.1]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Owji6y/ansible_module_asa_command.py\", line 200, in <module>\n    main()\n  File \"/tmp/ansible_Owji6y/ansible_module_asa_command.py\", line 170, in main\n    responses = run_commands(module, commands)\n  File \"/tmp/ansible_Owji6y/ansible_modlib.zip/ansible/module_utils/network/asa/asa.py\", line 124, in run_commands\n  File \"/tmp/ansible_Owji6y/ansible_modlib.zip/ansible/module_utils/connection.py\", line 149, in __rpc__\nansible.module_utils.connection.ConnectionError: clear conn address 10.0.0.10\r\n                          ^\r\nERROR: % Invalid input detected at '^' marker.\r\nERROR: Command authorization failed\r\n\rtest02uspvdfw48> \n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
...ignoring

TASK [first debug] ************************************************************************************************************************************************************************************
task path: /home/dbrousseau/ansible/playbooks/CiscoASA/test_ncli.yml:30
ok: [127.0.0.1] => {
    "msg": "First debug complete"
}

TASK [second debug] ***********************************************************************************************************************************************************************************
task path: /home/dbrousseau/ansible/playbooks/CiscoASA/test_ncli.yml:35
ok: [127.0.0.1] => {
    "msg": "First debug complete"
}
META: ran handlers
META: ran handlers

PLAY RECAP ********************************************************************************************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0


```
