### ISSUE TITLE
ec2 module does not split list of security group IDs

### ISSUE THREAD

**Issue by shentonfreude** [ansible/ansible#4134]
James Camaratta suggests this is a bug, that the 'ec2' module splits a list of security group names, but not security group IDs.  

https://groups.google.com/d/msg/ansible-project/QKbhPKsaDoA/XfyJ4R3hHTEJ

I'm creating an SG then adding it to a list of existing SGs when creating an  EC2 instance, and working in a VPC which doesn't recognize names, only IDs.

```

---
# Demonstrate possible bug expanding AWS SG in EC2 creation

- name: Create SG, Launch Instance with that SG
  hosts: local
  gather_facts: false
  vars:
    app_name: testing-shentonfreude
    region: us-east-1
    vpc_id: vpc-3bc6375a
    # the sgs must be bracketed to be treated as a list by debug
    existing_sgs: [sg-6e7bba01, sg-9478b9fb]
  tasks:
    - name: Create security group to apply to EC2 instance
      local_action:
        module: ec2_group
        name: shentonfreude-test
        description: new SG to be applied to new EC2
        region: "{{region}}"
        vpc_id: "{{vpc_id}}"
      register: app_sg
    - name: test expansion of list extension
      local_action: debug msg="{{ ','.join(existing_sgs + [app_sg.group_id]) }}"
    - name: Launch instance and apply existing and new Security Groups
      local_action:
        module: ec2
        id: westprime-private-test-sg-dev-20130916-1
        keypair: westprime-cshenton.pem
        region: "{{region}}"
        # This expansion fails at AWS:
        # <Message>Invalid id: "sg-6e7bba01,sg-9478b9fb,sg-ad8020c2"</Message>
        group_id: "{{ ','.join(existing_sgs + [app_sg.group_id]) }}"
        instance_type: m1.small
        image: ami-a25415cb
        vpc_subnet_id: vpc-3bc6375a
        instance_tags: '{"Name": "shenton-test-dev", "site": "test.hq", "op_env": "dev", "Description": "to7sandbox", "Owner": "shentonfreude"}'
```
