### ISSUE TITLE
The path to blkid cannot be resolved by os-prober when using the command module in a playbook to create a new grub.cfg

### ISSUE THREAD

**Issue by mvanderwijst** [ansible/ansible#41342]
##### SUMMARY
If "/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg" is executed through Ansible, it fails to run os-prober. This is the stderr output:
```
        "Generating grub configuration file ...", 
        "Found theme: /boot/grub2/themes/system/theme.txt", 
        "Found linux image: /boot/vmlinuz-4.16.12-300.fc28.x86_64", 
        "Found initrd image: /boot/initramfs-4.16.12-300.fc28.x86_64.img", 
        "Found linux image: /boot/vmlinuz-4.16.3-301.fc28.x86_64", 
        "Found initrd image: /boot/initramfs-4.16.3-301.fc28.x86_64.img", 
        "Found linux image: /boot/vmlinuz-0-rescue-e16e9a0dd466434eae3e21c4b681a172", 
        "Found initrd image: /boot/initramfs-0-rescue-e16e9a0dd466434eae3e21c4b681a172.img", 
        "/usr/bin/os-prober: line 91: blkid: command not found", 
        "/usr/bin/os-prober: line 172: blkid: command not found", 
        "/usr/bin/os-prober: line 172: blkid: command not found", 
        "/usr/bin/os-prober: line 172: blkid: command not found", 
        "/usr/bin/os-prober: line 172: blkid: command not found", 
        "/usr/bin/os-prober: line 172: blkid: command not found", 
        "done"
```

The program blkid is invoked in os-prober without a full path. It lives is /usr/sbin/blkid and should thus be resolved without problems.

The actual result is that other OSes cannot be found when building a new grub.cfg.

Using a direct command works fine.
```bash
ansible hostname -m command -a "/usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg" -b -K -vvvv
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
command / shell

##### ANSIBLE VERSION
```
ansible 2.5.2
```

##### CONFIGURATION
No changes to the configuration.

##### OS / ENVIRONMENT
Fedora 26 and Fedora 28

##### STEPS TO REPRODUCE

```yaml
# Replace hostname by actual hostname below
# Execute playbook: ansible-playbook ./playbook.yml -b -K -vvvv
---
- hosts: hostname
  become: yes
  become_method: su
  gather_facts: False
  tasks:
  - name: Build grub.cfg
    command: /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg
```

##### EXPECTED RESULTS
That the path to blkid is resolved by os-prober when using grub2-mkconfig.

##### ACTUAL RESULTS
The path to blkid cannot be resolved by /usr/bin/os-prober.
As a result additional OSs are not added to Grub2.
