### ISSUE TITLE
New module: freebsd-update

### ISSUE THREAD

**Issue by johnwesley** [ansible/ansible#41367]
##### SUMMARY
There doesn't appear to be an official module for the FreeBSD utility `freebsd-update`.

Would like to draft a module for the `freebsd-update fetch`, `freebsd-update install` and `freebsd-update IDS` commands with options.

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

freebsd-update

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0 (devel 2ecf1d35d3) last updated 2018/06/09 14:43:17 (GMT -400)
  config file = /Users/kwisatz4/.ansible.cfg
  configured module search path = [u'/Users/kwisatz4/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/kwisatz4/Github/ansible/lib/ansible
  executable location = /Users/kwisatz4/Github/ansible/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### CONFIGURATION

No changes.

##### OS / ENVIRONMENT

Host: Unix type (Linux, OSX)
Target: FreeBSD >= 11.1 

##### STEPS TO REPRODUCE

```yaml
- freebsd-update:
       fetch:   true
       install:  true
       IDS: false
       server: 'update.FreeBSD.org'
       basedir: '/'
       workdir: '/var/db/freebsd-update/'
       conffile: '/etc/freebsd-update.conf'
       force: false
       key:  '<my key>'
```

##### EXPECTED RESULTS

All recent updates will be fetched and/or installed without user intervention.

##### ACTUAL RESULTS

```

```
