### ISSUE TITLE
gluster_volume with replicas fail during probe peer

### ISSUE THREAD

**Issue by jpsecher** [ansible/ansible#41366]
##### SUMMARY

gluster_volume fail while probing the remote host that the ansible script is running on.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

gluster_volume

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /Users/jps/repos/ds-infra/ansible/ansible.cfg
  configured module search path = [u'/Users/jps/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun  3 2018, 02:00:07) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

DEFAULT_PRIVATE_KEY_FILE(/Users/jps/repos/ds-infra/ansible/ansible.cfg) = /Users/jps/.ssh/xxx-devops.pem
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False

##### OS / ENVIRONMENT

Running on MacOS 10.13.5, managing Ubuntu 16.04 on Azure.

##### STEPS TO REPRODUCE

```yaml
- name: Create Gluster volume
  gluster_volume:
    name: swarm
    state: present
    host: master.example.com
    bricks: "/var/lib/gluster/brick0"
    cluster: "slave1.example.com,slave2.example.com,master.example.com"
    replicas: 3
    force: true
```

##### EXPECTED RESULTS

I expected the creation of a gluster volume with replicated bricks across all the workers and the master (which is the remote host).

The above playbook has worked during the past three months, but looking at the source code of gluster_volume, I cannot see any changes that should trigger any of this. 

##### ACTUAL RESULTS

```
TASK [gluster/volume-create : Create Gluster volume] ******************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: None
fatal: [master.example.com]: FAILED! => {"changed": false, "msg": "error running gluster (/usr/sbin/gluster --mode=script peer probe master.example.com) command (rc=1): peer probe: failed: master.example.com is either already part of another cluster or having volumes configured\n"}
```

I have made a [longer description](https://gist.github.com/jpsecher/87bda704f147bec7e913316cb969ebd5) which also references an [old bug report](https://github.com/ansible/ansible-modules-extras/issues/659).
