### ISSUE TITLE
Template validation fails in 2.5.4 (nginx)

### ISSUE THREAD

**Issue by danielcompton** [ansible/ansible#41377]
##### SUMMARY

In Ansible 2.4.3.0 I was able to run a playbook which includes

```
- name: ensure nginx conf exists and all config is valid
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: "nginx -t -c %s"
  become: yes
  become_user: root
```

successfully. With Ansible 2.5.4 (building via Packer) I get `nginx: [emerg] open() \"/usr/share/nginx/~myusername/.ansible/tmp/ansible-tmp-1528680702.29-143679332616529/source\" failed (2: No such file or directory)`.

The thing that stands out here is `/usr/share/nginx/~myusername/.ansible`. It looks as if the validate command is passing the path in such a way that nginx is treating it as a relative path, not an absolute one?

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
"template"

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = None
  configured module search path = [u'/Users/daniel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Jan  6 2018, 12:16:16) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

```console
$ ansible-config dump --only-changed
$ # Nothing printed
```

##### OS / ENVIRONMENT

Run from macOS against Ubuntu 16.04.

##### STEPS TO REPRODUCE

```yaml
- name: ensure nginx conf exists and all config is valid
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    validate: "nginx -t -c %s"
  become: yes
  become_user: root
```

##### EXPECTED RESULTS

Configuration would be validated.

##### ACTUAL RESULTS

 (after JSON decoding):

```
 googlecompute: TASK [app : ensure nginx conf exists and all config is valid] ******************
{
  "changed": false,
  "checksum": "0fd5779377acec230fd5fb62e95dea319ed6b560",
  "exit_status": 1,
  "msg": "failed to validate",
  "stderr": "nginx: [emerg] open() \"/usr/share/nginx/~myusername/.ansible/tmp/ansible-tmp-1528680702.29-143679332616529/source\" failed (2: No such file or directory)\nnginx: configuration file /usr/share/nginx/~myusername/.ansible/tmp/ansible-tmp-1528680702.29-143679332616529/source test failed\n",
  "stderr_lines": [
    "nginx: [emerg] open() \"/usr/share/nginx/~myusername/.ansible/tmp/ansible-tmp-1528680702.29-143679332616529/source\" failed (2: No such file or directory)",
    "nginx: configuration file /usr/share/nginx/~myusername/.ansible/tmp/ansible-tmp-1528680702.29-143679332616529/source test failed"
  ],
  "stdout": "",
  "stdout_lines": []
}
```
