### ISSUE TITLE
docker_container port mapping not working

### ISSUE THREAD

**Issue by alcappello** [ansible/ansible#41372]
##### SUMMARY

Port mapping on docker_container module doesn't actually publish any port and doesn't throw any error. Anyway, it seems that all the exposed ports are actually published.

Ansible version 2.5.4 and Docker version 17.12.1-ce, build 7390fc6.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /Codebase/Server/nuk/ansible.cfg
  configured module search path = [u'/Users/alessandro/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

`DEFAULT_HOST_LIST(/Codebase/Server/ansible.cfg) = [u'/Codebase/Server/hosts']`

##### OS / ENVIRONMENT

Managed OS: Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- name: PiHole container
  docker_container:
    name: PiHole
    image: lplab/pihole:latest
    restart_policy: always
    network_mode: host
    ports:
      - "8088:80"
    env:
      ServerIP: "192.168.1.1"
      ADMIN_PASS: "supersecretpassword"
```

##### EXPECTED RESULTS

It should be the equivalent of running:
`docker run -p 8088:80 -d --name PiHole -e ADMIN_PASS="supersecretpassword" -e ServerIP="192.168.1.1" lplab/pihole:latest`

but it's not. 

##### ACTUAL RESULTS

A ´docker ps -a´ shows the container running but with no ports published: 

```
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                  PORTS               NAMES
39509488f451        lplab/pihole:latest         "/tini -- /sbin/entr…"   14 minutes ago      Up 14 minutes                               PiHole
```

Anyway, the ports exposed by the Dockerfile (53 and 80) are actually reachable from the host.
