### ISSUE TITLE
Comma in string inside role condition seems to be parsed in wrong way

### ISSUE THREAD

**Issue by Dmitriusan** [ansible/ansible#41436]
##### SUMMARY

I defined a role condition that checks for string equality. The reference string contains a comma, and from Ansible output I guess that this comma is used to break parts of role definition. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

playbook parser

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /env_setup/deploy/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

HOST_KEY_CHECKING(/env_setup/deploy/ansible.cfg) = False
RETRY_FILES_ENABLED(/env_setup/deploy/ansible.cfg) = False
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

The minimal playbook that contains a reproduce:

```yaml
- name: Set up Digital Ocean or VMware instance
  hosts: all
  user: "{{ bootstrap_user }}"
  roles:
    - { role: vmware_networking_quirks,
        when: ansible_system_vendor == "VMware, Inc." and ansible_default_ipv4.interface != uplink_interface_name }
```

##### EXPECTED RESULTS

Role should be executed conditionally
##### ACTUAL RESULTS

```
FAILED! => {"msg": "The conditional check 'ansible_system_vendor == \"VMware' failed. The error was: template error while templating string: unexpected char u'\"' at 31. String: {% if ansible_system_vendor == \"VMware %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/env_setup/deploy/roles/vmware_networking_quirks/tasks/main.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- fail:\n  ^ here\n"}
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
As a workaround - 

```yaml
- name: Set up Digital Ocean or VMware instance
  hosts: all
  user: "{{ bootstrap_user }}"
  vars:
     vmware_vendor_id: "VMware, Inc."
  roles:
    - { role: vmware_networking_quirks,
        when: ansible_system_vendor == vmware_vendor_id and ansible_default_ipv4.interface != uplink_interface_name }
```
