### ISSUE TITLE
tower_inventory module cannot create smart inventories

### ISSUE THREAD

**Issue by jaevans** [ansible/ansible#41456]
##### SUMMARY

The tower_inventory module cannot create Smart Inventories in Tower.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

tower_inventory

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = None
  configured module search path = [u'/Users/evanjame/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

N/A 
AWX 1.0.6.8

##### STEPS TO REPRODUCE

```yaml
- name: Add Smart Foreman inventory
  tower_inventory:
    name: "Library Inventory"
    description: "All Foreman Hosts in the Library environment"
    organization: "Bar Org"
    kind: smart
    host_filter: groups__name=foreman_lifecycle_environment_Library
    state: present
    tower_config_file: "~/tower_cli.cfg"
```

##### EXPECTED RESULTS

Creates new Smart Inventory named "Library Inventory" with hosts from the Library lifecycle environment. 
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (tower_inventory) module: host_filter, kind Supported parameters include: description, name, organization, state, tower_config_file, tower_host, tower_********, tower_username, tower_verify_ssl, variables"}
```
