### ISSUE TITLE
vmware_guest : disk type not set to eagerzeroedthick when deploying template

### ISSUE THREAD

**Issue by tgoetheyn** [ansible/ansible#41484]
##### SUMMARY

when deploying a template which has a disk type of "thin provisioned", the deployed vm disk type is not set to "thick eagered zeroed" even though the disk type is set to eagerzeroedthick in the playbook
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest
##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/testuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### OS / ENVIRONMENT

vSphere Client version 6.5.0.13000

##### STEPS TO REPRODUCE

```yaml
- name: "PROVISION | Create VM from template - Linux"
    vmware_guest:
      validate_certs: false
      hostname: "{{ vcenter_host }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      datacenter: "{{ datacenter }}"
      cluster: "{{ cluster }}"
      folder: "{{folder}}"
      name: "{{ server_name|upper }}"
      template: "{{ vmtemplate }}"
      state: poweredon
      hardware:
        num_cpus: "{{ cpu }}"
        memory_mb: "{{ mem_mb }}"
      disk:
        - size_gb: 40
          type: eagerzeroedthick
          datastore: "{{ datastore }}"
      networks:
      - name: "{{ vlan }}"
        type: static
        ip: "{{ ip_adres }}"
        netmask: 255.255.255.0
        gateway: "{{ ip_gateway }}"
      customization:
        hostname: "{{ server_name }}"
        domain: "{{ domain }}"
        dns_servers:
        - 10.54.1.2
      wait_for_ip_address: yes
    register: new_vm
```

##### EXPECTED RESULTS

That the VM is created with a disktype set to "thick eager zeroed"

##### ACTUAL RESULTS

TASK [PROVISION | Create VM from template - Linux] *****************************13:50:47
task path: /var/lib/awx/projects/_35__servers_vmware/automation/provisioning.yml:5313:50:47
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: awx
<localhost> EXEC /bin/sh -c 'echo ~awx && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1528890647.56-269796834625625 `" && echo ansible-tmp-1528890647.56-269796834625625="` echo /var/lib/awx/.ansible/tmp/ansible-tmp-1528890647.56-269796834625625 `" ) && sleep 0'
<localhost> PUT /var/lib/awx/.ansible/tmp/ansible-local-3i5vPUb/tmpSAK5b_ TO /var/lib/awx/.ansible/tmp/ansible-tmp-1528890647.56-269796834625625/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /var/lib/awx/.ansible/tmp/ansible-tmp-1528890647.56-269796834625625/ /var/lib/awx/.ansible/tmp/ansible-tmp-1528890647.56-269796834625625/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /var/lib/awx/.ansible/tmp/ansible-tmp-1528890647.56-269796834625625/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1528890647.56-269796834625625/ > /dev/null 2>&1 && sleep 0'

{
    "_ansible_parsed": true,
    "instance": {
        "hw_name": "SRVANSIBLETEST14",
        "hw_power_status": "poweredOn",
        "snapshots": [],
        "guest_question": null,
        "hw_interfaces": [
            "eth0"
        ],
        "hw_guest_id": "centos7_64Guest",
        "current_snapshot": null,
        "hw_folder": "/DIGIPOLIS DG/vm",
        "customvalues": {},
        "hw_files": [
            "[DG_P0_SAS_02] SRVANSIBLETEST14/SRVANSIBLETEST14.vmx",
            "[DG_P0_SAS_02] SRVANSIBLETEST14/SRVANSIBLETEST14.nvram",
            "[DG_P0_SAS_02] SRVANSIBLETEST14/SRVANSIBLETEST14.vmsd",
            "[DG_P0_SAS_02] SRVANSIBLETEST14/SRVANSIBLETEST14_1.vmdk"
        ],
        "ipv4": "10.54.27.222",
        "ipv6": null,
        "hw_product_uuid": "42130a95-3d5c-e1c0-1e04-adb2e400d2fe",
        "hw_is_template": false,
        "module_hw": true,
        "hw_guest_ha_state": true,
        "guest_consolidation_needed": false,
        "hw_guest_full_name": "CentOS 7 (64-bit)",
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "10282",
        "annotation": "",
        "instance_uuid": "5013a216-bb0b-a448-e320-3374ba3a9071",
        "hw_processor_count": 2,
        "hw_memtotal_mb": 4096,
        "hw_datastores": [
            "DG_P0_SAS_02"
        ],
        "hw_esxi_host": "srvesx22.********",
        "hw_cores_per_socket": 1,
        "hw_eth0": {
            "macaddress": "00:50:56:93:9b:4d",
            "addresstype": "assigned",
            "macaddress_dash": "00-50-56-93-9b-4d",
            "summary": "DVSwitch: e1 ea 13 50 16 27 64 7a-f3 78 18 c8 0b c5 cc d5",
            "ipaddresses": [
                "10.54.27.222"
            ],
            "label": "Network adapter 1"
        }
    },
    "changed": true,
    "_ansible_no_log": false,
    "invocation": {
        "module_args": {
            "resource_pool": null,
            "force": false,
            "hardware": {
                "memory_mb": "4096",
                "num_cpus": "2"
            },
            "cluster": "DG_Lx",
            "customization": {
                "domain": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                "dns_servers": [
                    "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                ],
                "hostname": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
            },
            "disk": [
                {
                    "size_gb": 40,
                    "type": "eagerzeroedthick",
                    "datastore": "DG_P0_SAS_02"
                }
            ],
            "networks": [
                {
                    "ip": "10.54.27.222",
                    "netmask": "255.255.255.0",
                    "type": "static",
                    "name": "vDS_VLAN80_L2_Virtual_Servers_DV-QA1",
                    "gateway": "10.54.27.1"
                }
            ],
            "wait_for_ip_address": true,
            "uuid": null,
            "customvalues": [],
            "hostname": "srvvc04.********",
            "port": 443,
            "state": "poweredon",
            "template": "TEMPLATE.CENTOS7.180611",
            "linked_clone": false,
            "folder": "/DIGIPOLIS DG/vm/",
            "username": "GENTGRP\\sys_ansible_vmware",
            "snapshot_src": null,
            "guest_id": null,
            "name_match": "first",
            "cdrom": {},
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "annotation": null,
            "datacenter": "DIGIPOLIS DG",
            "name": "SRVANSIBLETEST14",
            "is_template": false,
            "esxi_hostname": null,
            "validate_certs": false
        }
    }
}

```

```
