### ISSUE TITLE
Ansible 2.5 Junos create user doesn't work

### ISSUE THREAD

**Issue by omershtivi** [ansible/ansible#41482]
##### SUMMARY
When trying to use junos_user receive an error

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
junos_user

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /home/omer.shtivi/Ansible/Ansible/ansible.cfg
  configured module search path = ['/home/omer.shtivi/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/omer.shtivi/Ansible/python/virtualenv_ansible/lib/python3.6/site-packages/ansible
  executable location = /home/omer.shtivi/Ansible/python/virtualenv_ansible/bin/ansible
  python version = 3.6.5 (default, May 29 2018, 10:14:51) [GCC 4.8.4]
```

##### CONFIGURATION

[defaults]
inventory      = ./inventory
host_key_checking = False

##### OS / ENVIRONMENT

uname -r
3.19.0-80-generic
--- JUNOS 12.3R9.4 built 2015-02-12 11:08:08 UTC

##### STEPS TO REPRODUCE

try to do junos_user

```yaml
- name: "Create User"
  hosts: test
  gather_facts: no

  tasks:
    - name: Create User
      junos_user:
         name: boris.avney
         role: super-user
         sshkey: "{{ lookup('file', '/home/omer.shtivi/Ansible/Ansible/boris_public_key.pub') }}"
```

##### EXPECTED RESULTS

User been created

##### ACTUAL RESULTS

The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_FYl46P/ansible_module_junos_user.py", line 344, in <module>
    main()
  File "/tmp/ansible_FYl46P/ansible_module_junos_user.py", line 328, in main
    diff = load_config(module, tostring(ele), warnings, action='merge')
  File "/tmp/ansible_FYl46P/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py", line 207, in load_config
  File "/tmp/ansible_FYl46P/ansible_modlib.zip/ansible/module_utils/network/junos/junos.py", line 126, in load_configuration
  File "/tmp/ansible_FYl46P/ansible_modlib.zip/ansible/module_utils/network/common/netconf.py", line 70, in __rpc__
  File "/tmp/ansible_FYl46P/ansible_modlib.zip/ansible/module_utils/network/common/netconf.py", line 102, in parse_rpc_error
ansible.module_utils.connection.ConnectionError: 'bytes' object has no attribute 'encode'

```

```
