### ISSUE TITLE
Which dependency packages need to be installed on suse to install Ansible

### ISSUE THREAD

**Issue by Guoguo-Sun** [ansible/ansible#41499]
##### SUMMARY

I have created a SLES VM on azure, I have install ansible and some dependecy packages as this link, But when I run playbook ,it will get error, error message: No module named mgmt.network.version

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_resourcegroup
##### ANSIBLE VERSION

```
ansible 2.5.4
```

##### OS / ENVIRONMENT

SLES 12 SP2
##### STEPS TO REPRODUCE

```yaml
  - name: Create Resource Group
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: eastus
```

##### EXPECTED RESULTS

Create resource group succesfully 
##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Do you have azure>=2.0.0 installed? Try `pip install ansible[azure]`- No module named mgmt.network.version"}
```
