### ISSUE TITLE
Allow for ovirt_snapshots to be deleted based on date differences

### ISSUE THREAD

**Issue by Bak3y** [ansible/ansible#41500]
##### SUMMARY

I'd like to be able to easily delete snapshots older than X days using the ovirt_snapshots module.  The ovirt_snapshots_facts module returns a formatted date parameter for each snapshot.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

ovirt_snapshots

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/lib/python2.7/site-packages/ara/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ara/plugins/actions']
DEFAULT_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME(/etc/ansible/ansible.cfg) = True
DEFAULT_BECOME_ASK_PASS(/etc/ansible/ansible.cfg) = False
DEFAULT_BECOME_METHOD(/etc/ansible/ansible.cfg) = sudo
DEFAULT_BECOME_USER(/etc/ansible/ansible.cfg) = root
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ara/plugins/callbacks']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 25
DEFAULT_LOAD_CALLBACK_PLUGINS(/etc/ansible/ansible.cfg) = True
DEFAULT_LOG_PATH(/etc/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/usr/lib/python2.7/site-packages/ara/plugins/modules']
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /root/.ssh/id_rsa
DEFAULT_REMOTE_PORT(/etc/ansible/ansible.cfg) = 9022
DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = yaml
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/ovirt/ovirt_snapshots.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_snapshots.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @machacekondra @mwperina
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by machacekondra** [comment]
We can implement this, but you can workaround with something like:

```yaml
  - name: List snaphosts
    ovirt_snapshots_facts:
      auth: "{{ ovirt_auth }}"
      vm: myvm

  - name: Remove snaphosts older then week
    ovirt_snapshots:
      auth: "{{ ovirt_auth }}"
      state: absent
      vm_name: myvm
      snapshot_id: "{{ item.id }}"
    with_items: "{{ ovirt_snapshots }}"
    when: "{{( ansible_date_time.date|to_datetime('%Y-%m-%d') - item.date[:-6]|to_datetime('%Y-%m-%d %H:%M:%S.%f')).days > 7 }}"

```
