### ISSUE TITLE
docker_container does not update container on tag change

### ISSUE THREAD

**Issue by ljesmin** [ansible/ansible#41509]
##### SUMMARY
When docker.io image name is specified with registry name, existing containers will not be updated when tag changes.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

docker_container

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jesmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### OS / ENVIRONMENT

Ubuntu 18.04 with included docker.io 
docker.io                             17.12.1-0ubuntu1
python-docker                         2.5.1-1
##### STEPS TO REPRODUCE

This playbook works on Fedora/Centos included docker but fails to update container to ubuntu:18.04 with docker-ce or ubuntu default docker.io.

```yaml
---
- hosts: localhost
  become: no
  tasks:
  - name: Start ubuntu 17.04
    docker_container:
      name: ansibletest
      image: "docker.io/ubuntu:17.04"
      ignore_image: false
      command: tail -f /.dockerenv
      detach: true
      restart_policy: unless-stopped
      state: started
      force_kill: true
    register: docker_output

  - name: Output Container image
    debug: var=docker_output.ansible_facts.docker_container.Config.Image

  - name: Start ubuntu 18.04
    docker_container:
      name: ansibletest
      image: "docker.io/ubuntu:18.04"
      ignore_image: false
      command: tail -f /.dockerenv
      detach: true
      restart_policy: unless-stopped
      state: started
      force_kill: true
    register: docker_output

  - name: Output container Image
    debug: var=docker_output.ansible_facts.docker_container.Config.Image
```

##### EXPECTED RESULTS

docker container from image ubuntu:18.04 should be running
##### ACTUAL RESULTS

docker container image ubuntu:17.04 is running

```

```
