### ISSUE TITLE
How add an `option' without specifying a `value' in ini_file module

### ISSUE THREAD

**Issue by tchia04** [ansible/ansible#41511]
##### SUMMARY
Since the ansible inventory file is an ini file, I tried to use the ini_file module to edit the inventory host file.  However to my surprise, I wasn't able to add a hostname without the = and a value.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ini_file

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/NEXTESTATE/tchia/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /home/NEXTESTATE/tchia/.vault_pass

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### STEPS TO REPRODUCE

 

```yaml

  - name: nosql
    ini_file:
      path: "{{ inventory_file }}"
      section: nosql
      option: mongodbhost1
      value: null
      mode: 0600
      backup: yes
    become: true



```

##### EXPECTED RESULTS

I expecte the inventory_file to look like this

[nosql]
mongodbhost1

##### ACTUAL RESULTS

The hostname entry is added under the "nosql" section/group. 
However, "= None" is added as well. 

How can I tweak my task/playbook to omit the "= None" so it is a valid ansible inventory file?

```
inventory_file
[nosql]
mongodbhost1= None

```
