### ISSUE TITLE
allow an option to be commented out for the ini_file module instead of deleted

### ISSUE THREAD

**Issue by tchia04** [ansible/ansible#41513]
##### SUMMARY

Current state attribute in the ini_file module supports present or absent.  I would like to suggest a way to comment out a line instead of deleting .  A similar feature exists in the cron module.  The attribute in the cron module is called disabled

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

ini_file
##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /home/NEXTESTATE/tchia/ansible.cfg
  configured module search path = [u'/home/NEXTESTATE/tchia/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]

```

##### CONFIGURATION

ansible-config dump --only-changed
DEFAULT_ROLES_PATH(/home/NEXTESTATE/tchia/Ansible/ansible.cfg) = [u'/home/NEXTESTATE/tchia/Ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/NEXTESTATE/tchia/Ansible/ansible.cfg) = /home/NEXTESTATE/tchia/.vault_pass

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### STEPS TO REPRODUCE

```yaml

  - name: Ensure "ClientAliveInterval is set to 1 hour" in sshd_config file
    ini_file:
      path: /tmp/sshd_config
      section: null
      option: ClientAliveInterval
      value: 3600
      disable: yes
      mode: 0600
      backup: yes
    become: true

```

##### EXPECTED RESULTS

The sshd_config file should look like this
#ClientAliveInterval 0

##### ACTUAL RESULTS

Without the disabled attribute, the "ClientAliveInterval 0" would be deleted if state=absent

```

```
