### ISSUE TITLE
Aggregates not working on vyos_vlan

### ISSUE THREAD

**Issue by iverona** [ansible/ansible#41528]
##### SUMMARY
Aggregates seem not to be working with vyos_vlan module. Playbook fails with "vlan_id is missing" when defined via aggregate. Works when not using aggregates. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vyos_vlan

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /Users/ignacio/Documents/TowerDemo/playbooks/ansible.cfg
  configured module search path = [u'/Users/ignacio/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION
DEFAULT_STRATEGY(env: ANSIBLE_STRATEGY) = debug
HOST_KEY_CHECKING(/Users/ignacio/Documents/TowerDemo/playbooks/ansible.cfg) = False

##### OS / ENVIRONMENT
macOS 10.13.5

Version:      VyOS 1.1.8
Description:  VyOS 1.1.8 (helium)
Copyright:    2017 VyOS maintainers and contributors
Built by:     maintainers@vyos.net
Built on:     Sat Nov 11 13:44:36 UTC 2017
Build ID:     1711111344-b483efc
System type:  x86 64-bit
Boot via:     disk
Hypervisor:   KVM
HW model:     VirtualBox
HW S/N:       0
HW UUID:      C33111C0-AEB3-4D75-B633-FCF013A505A1
Uptime:       08:46:45 up  1:07,  2 users,  load average: 0.00, 0.01, 0.02

##### STEPS TO REPRODUCE
```yaml
---
- hosts: network
  connection: network_cli
  gather_facts: False
  tasks:  

  - vyos_vlan:     
      aggregate:
        - { vlan_id: 100, name: default, interfaces: "eth0", state: present}
        - { vlan_id: 200, name: mgm, interfaces: "eth0", state: present}
        - { vlan_id: 300, name: voice, interfaces: "eth0", state: present }
        - { vlan_id: 400, name: data, interfaces: "eth0", state: present }
          
```
##### EXPECTED RESULTS
Right VLANs created as per the aggregate listing. 

##### ACTUAL RESULTS

```
fatal: [spine01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "aggregate": [
                {
                    "interfaces": "eth0",
                    "name": "default",
                    "state": "present",
                    "vlan_id": 100
                },
                {
                    "interfaces": "eth0",
                    "name": "mgm",
                    "state": "present",
                    "vlan_id": 200
                },
                {
                    "interfaces": "eth0",
                    "name": "voice",
                    "state": "present",
                    "vlan_id": 300
                },
                {
                    "interfaces": "eth0",
                    "name": "data",
                    "state": "present",
                    "vlan_id": 400
                }
            ],
            "delay": 10,
            "purge": false,
            "state": "present"
        }
    },
    "msg": "missing required arguments: vlan_id"
}
```
