### ISSUE TITLE
directory attributes for file module only set on deepest created directory

### ISSUE THREAD

**Issue by eukaryote** [ansible/ansible#4152]
When creating multiple directories with a single call to the file module (parent directories don't exist yet), ansible only changes attributes such as the owner and group on the deepest created directory, not all the parent directories that were created. For example:

``` myplaybook.yml:

---
- name: test
  hosts: $target
  gather_facts: false
  sudo: true
  tasks:
    - file: path=/opt/a/b/c owner=myuser group=mygroup state=directory
```

If I run that playbook with a $target, then it creates '/opt/a', '/opt/a/b', and '/opt/a/b/c', and changes the owner/group of '/opt/a/b/c' but leaves the other two created directories as owned by root.

**Comment by resmo** [comment]
I guess this might be not a bug:
If we like to set owner and group for all directories in path, we use:

```
- file: path=/opt/a/b/c owner=myuser group=mygroup state=directory recurse=yes
```

See http://www.ansibleworks.com/docs/modules.html#id193

Or did I miss anything?

**Comment by mpdehaan** [comment]
Yep, this is working as designed.

**Comment by eukaryote** [comment]
I didn't follow up on this earlier because I thought mpdehaan's "Yep, this is working as designed" meant that the `recurse` option would do what resmo said, but I finally got around to testing it and wanted to report that the `recurse` option doesn't have any effect, and all the non-leaf directories all still end up with the wrong owner/group.

To be concrete, consider

``` yaml
---
- hosts: laptop
  connection: local
  remote_user: root
  tasks:
  - name: create nested directory with recursive option
    file: path=/opt/a1/b1 owner=myuser group=users state=directory recurse=true
    sudo: true
  - name: create nested directory without recursive option
    file: path=/opt/a2/b2 owner=myuser group=users state=directory
    sudo: true
```

Before running the ansible playbook with `ansible-playbook --ask-sudo-pass playbook.yaml`, I have an `/opt` directory. After running the playbook, I have `/opt/a1` and `/opt/a2`, both of which are owned by `root` and have `root` group. The `recurse` option had no effect in this case. The leaf-node directories do have the correct owner and group in both cases (myuser:users).
