### ISSUE TITLE
vmware_guest_facts and vmware_host_facts not showing facts in output (ansible 2.5.3)

### ISSUE THREAD

**Issue by singha200** [ansible/ansible#41526]
##### SUMMARY

vmware_guest_facts and vmware_host_facts not showing facts in output (execution is completed without any error)
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest_facts
vmware_host_facts

##### ANSIBLE VERSION

```
ansible 2.5.3
```

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)

##### STEPS TO REPRODUCE

```yaml
gather_facts.yml
---
- hosts: 127.0.0.1
  connection: local
  user: root
  become: false
  gather_facts: True
  serial: 1

  tasks:
    - name: Gather facts from standalone ESXi server having datacenter as 'ha-datacenter'
      vmware_guest_facts:
       hostname: **********
       username: ***********
       password: ***********
       datacenter: ***********
       validate_certs: no
       name: ***********
      delegate_to: localhost
      register: facts
    - name: gather facts of vcenter
      vmware_host_facts:
       hostname: ***********
       username: ************
       password: *********
       validate_certs: no
      delegate_to: localhost
      register: host_facts


```

##### EXPECTED RESULTS

The playbook should return facts about virtual machine and vcenter host 
##### ACTUAL RESULTS

```
[root@centos ansible]# ansible-playbook test_facts.yml

PLAY [127.0.0.1] *******************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [127.0.0.1]

TASK [Gather facts from standalone ESXi server having datacenter as 'ha-datacenter'] ***********************************
ok: [127.0.0.1 -> localhost]

TASK [gather facts of vcenter] *****************************************************************************************
ok: [127.0.0.1 -> localhost]

PLAY RECAP *************************************************************************************************************
127.0.0.1                  : ok=3    changed=0    unreachable=0    failed=0
```
