### ISSUE TITLE
tower_credential shows clear text passwords for vault credential creation

### ISSUE THREAD

**Issue by tumbl3w33d** [ansible/ansible#41553]
##### SUMMARY
Creating a vault credential the execution log shows the specified password in clear.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tower_credential

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (devel a4f49ed648) last updated 2018/06/14 10:39:41
```

##### CONFIGURATION
nothing relevant

##### OS / ENVIRONMENT
Debian 4.16.12-1~bpo9+1 (2018-06-03) x86_64 GNU/Linux
Working against API of AWX 1.0.6.15.

##### STEPS TO REPRODUCE
```yaml
- name: create credentials
  tower_credential:
    name: "{{ item.name }}"
    kind: "{{ item.kind }}"
    organization: "{{ item.orga }}"
    vault_password: "{{ item.vault_password | default(omit) }}"
    tower_host: "{{ awx_host }}"
    tower_username: "{{ awx_username }}"
    tower_password: "{{ awx_password }}"
  loop:
    - name: awx_vault_default
      kind: vault
      vault_password: "{{ redacted_default_pw }}"
      orga: redacted
```

##### EXPECTED RESULTS
Expected a credential to be created and I don't want the password to appear in the logs.

##### ACTUAL RESULTS
```
TASK [awx/config/credentials : create credentials] ******************************************************
Thursday 14 June 2018  18:19:30 +0200 (0:00:00.030)       0:00:08.354 ********* 
changed: [awx] => (item={u'kind': u'vault', u'orga': u'redacted', u'name': u'awx_vault_default', u'vault_password': u'HOLYSH**ISHOULDNOTBEHEREx_X'})
```
