### ISSUE TITLE
One or more undefined variables while using vars_prompt

### ISSUE THREAD

**Issue by matheus-caselani** [ansible/ansible#41569]
##### SUMMARY
Hello Guys,
I'm trying to create a new database using ansible and vars_prompt but i got an error

##### ISSUE TYPE

 - One or more undefined variables: 'Client_Username_Database' is undefined

##### COMPONENT NAME

/usr/lib/python2.7/dist-packages/ansible/playbook/task.py

/usr/share/ansible/database/mysql_db

##### ANSIBLE VERSION
```
ansible 1.7.2
```

##### OS / ENVIRONMENT
no changes to /etc/ansible/ansible.cfg

##### STEPS TO REPRODUCE

ansible-playbook dbserver.yml -v

```

##Casel
---
- hosts: caseldbserver
  remote_user: root
  vars:
    MySQL_root_pass: ********

  vars_prompt:

    - name: Client User name/database
      prompt: "Provide Database Name"
      private: no
      register: Client_Username_Database

    - name: MySQL Client Password
      prompt: "Provide client database password"
      private: yes
      confirm: yes
      register: MySQL_client_pass

  tasks:

    - name: Set Mysql root pass
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'

    - name: Confirm Mysql root pass
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'


#Instalando os pacotes do MYSQL
    - name: Database Installation
      apt: name={{item}} state=installed
      with_items:

        - libmariadbd-dev
        - mariadb-client-10.0
        - mariadb-server-10.0
        - phpmyadmin
        - php7.0-mysql
        - python-mysqldb

# Security

    - name: Deletes anonymous MySQL server user for localhost
      mysql_user: user="" state="absent" login_password="{{ MySQL_root_pass }}" login_user=root

    - name: Secure mysql root access
      mysql_user: user="root" password="{{ MySQL_root_pass }}" host="{{ item }}" login_password="{{MySQL_root_pass}}" login_user=root
      with_items:
          - 127.0.0.1
          - localhost
          - ::1
          - "{{ ansible_fqdn }}"

    - name: Removes the MySQL test database
      mysql_db: db=test state=absent login_password="{{ MySQL_root_pass }}" login_user=root

    - name: flush privileges
      action:  command mysql -uroot --password={{ MySQL_root_pass }} -e "FLUSH PRIVILEGES;"

    - name: Create User Database
      mysql_db:
        name: "{{ Client_Username_Database }}"
        state: present
        login_user: "{{ Client_Username_Database }}"
        login_password: "{{ MySQL_client_pass }}"

```

##### EXPECTED RESULTS

Create database

##### ACTUAL RESULTS

```

TASK: [Create User Database] **************************************************
fatal: [187.84.229.115] => One or more undefined variables: 'Client_Username_Database' is undefined

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************


```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/utils/module_docs_fragments/tower.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/utils/module_docs_fragments/tower.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
@matheus-caselani Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/database/mysql/mysql_db.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/mysql/mysql_db.py)
* [lib/ansible/playbook/task.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/task.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/database/mysql/mysql_db.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/database/mysql/mysql_db.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@matheus-caselani Thanks for reporting this issue. I see you are using `register` in `vars_prompt` which is not valid argument for `vars_prompt` 

You may need to modify your playbook as - 

vars_prompt_example.yaml
```yaml
---
- name: Sample Var prompt
  gather_facts: no
  hosts: localhost
  vars_prompt:
    - name: Client_Username_Database
      prompt: "Provide Database Name"
      private: no
    - name: MySQL_client_pass
      prompt: "Provide client database password"
      private: yes
      confirm: yes
  tasks:
    - debug:
        msg: "{{ Client_Username_Database }} {{ MySQL_client_pass }}"
```

Console log - 
```
# ansible-playbook vars_prompt_example.yml -vvv
ansible-playbook 2.7.0.dev0 (devel 00b397cfdb) last updated 2018/06/15 09:02:53 (GMT +550)
  config file = /Users/akasurde/.ansible.cfg
  configured module search path = ['/Users/akasurde/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Volumes/data/src/ansible/lib/ansible
  executable location = /Volumes/data/src/ansible/bin/ansible-playbook
  python version = 3.6.4 (default, Dec 19 2017, 15:24:51) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
Using /Users/akasurde/.ansible.cfg as config file

PLAYBOOK: vars_prompt_example.yml **********************************************************************************************
1 plays in vars_prompt_example.yml
Provide Database Name: db1
Provide client database password:
confirm Provide client database password:

PLAY [Sample Var prompt] *******************************************************************************************************
META: ran handlers

TASK [debug] *******************************************************************************************************************
task path: /Volumes/data/src/ansible/playbooks/vars_prompt_example.yml:14
ok: [localhost] => {
    "msg": "db1 smple"
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=0
```
