### ISSUE TITLE
VMware: vmware_guest: Create from template - network with underscore in name does not work

### ISSUE THREAD

**Issue by m4r10k** [ansible/ansible#41577]
##### SUMMARY

During the creation of an VMWare guest due to the vmware_guest module, setting a network name which has an underscore in its name does not apply the network on this vmware_guest properly. The network on the guest is shown up in the summery in vsphere but it is not attached to the guest in the details (see screenshots).

Playbook:
```
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Clone a VM from Template and customize
      vmware_guest:
        esxi_hostname:xxxxxxxxxxxxxx
        hostname: xxxxxxxxxxx
        username: xxxxxxxxxxxxxx
        password: xxxxxxxxxxxxxxx
        folder: /X/X
        validate_certs: no
        datacenter: X
        name: "{{ vmguestname }}"
        template: WebHosting-Ubuntu-16.04-Kubernetes
        hardware:
          memory_mb: 8192
          num_cpus: 4
        disk:
        - size_gb: 30
          type: thin
          datastore: x-113
        networks:
        - name: SERVER_200
          ip: "{{ vmguestip }}"
          netmask: 255.255.0.0
          gateway: 10.x.x.10
        wait_for_ip_address: yes
      delegate_to: localhost

```
In this example, `SERVER_200` is not correctly applied to the guest and as you can see, the network field in the details is empty and the guest can not communicate on the network:

![15-06-_2018_07-39-34](https://user-images.githubusercontent.com/9364572/41454014-2a0a23bc-7078-11e8-91b9-fd516e6817ba.jpg)

![15-06-_2018_07-41-15](https://user-images.githubusercontent.com/9364572/41454022-32473402-7078-11e8-843f-9b0500ce152c.jpg)

The playbook runs without any errors:

```
PLAY [localhost] ***************************************************************************************************************************

TASK [Clone a VM from Template and customize] **********************************************************************************************
changed: [localhost -> localhost]

PLAY RECAP *********************************************************************************************************************************
localhost                  : ok=1    changed=1    unreachable=0    failed=0  
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609
```

##### CONFIGURATION

ansible-config dump --only-changed

##### OS / ENVIRONMENT

Ansible is installed via Ubuntu packages according to the Ansible documentation.
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.4 LTS
Release:	16.04
Codename:	xenial
```

##### STEPS TO REPRODUCE

Create a port group with an underscore inside the name like `SERVER_200` and the network will not get attached. Rename the port group to `SERVER200` and it works as expected.

```yaml
---
- hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Clone a VM from Template and customize
      vmware_guest:
        esxi_hostname:xxxxxxxxxxxxxx
        hostname: xxxxxxxxxxx
        username: xxxxxxxxxxxxxx
        password: xxxxxxxxxxxxxxx
        folder: /X/X
        validate_certs: no
        datacenter: X
        name: "{{ vmguestname }}"
        template: WebHosting-Ubuntu-16.04-Kubernetes
        hardware:
          memory_mb: 8192
          num_cpus: 4
        disk:
        - size_gb: 30
          type: thin
          datastore: x-113
        networks:
        - name: SERVER_200
          ip: "{{ vmguestip }}"
          netmask: 255.255.0.0
          gateway: 10.x.x.10
        wait_for_ip_address: yes
      delegate_to: localhost
```

##### EXPECTED RESULTS

The network which contains an underscore in the name and which is defined in the `vmware_guest` task should be attached and activated on the vmware guest.

##### ACTUAL RESULTS

The defined vmware_guest network is not properly attached to the vmware guest created due to the playbook run. Not network communication possible.

```
ansible-playbook -vvvv --extra-vars "vmguestname=Xkube462 vmguestip=10.x.x.2" genesis_small.yml 
ansible-playbook 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with yaml plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc

PLAYBOOK: genesis_small.yml ****************************************************************************************************************
1 plays in genesis_small.yml

PLAY [localhost] ***************************************************************************************************************************
META: ran handlers

TASK [Clone a VM from Template and customize] **********************************************************************************************
task path: /var/opt/ansible/awx/projects/kubernetes_master/genesis_small.yml:6
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1529045584.89-229478058985284 `" && echo ansible-tmp-1529045584.89-229478058985284="` echo /root/.ansible/tmp/ansible-tmp-1529045584.89-229478058985284 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-10433_6WYH8/tmprrxerh TO /root/.ansible/tmp/ansible-tmp-1529045584.89-229478058985284/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1529045584.89-229478058985284/ /root/.ansible/tmp/ansible-tmp-1529045584.89-229478058985284/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1529045584.89-229478058985284/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1529045584.89-229478058985284/ > /dev/null 2>&1 && sleep 0'
changed: [localhost -> localhost] => {
    "changed": true, 
    "instance": {
        "annotation": "TPL xxxx3.13 - initial\nV2 - 2018.x.x - add xxx", 
        "current_snapshot": null, 
        "customvalues": {}, 
        "guest_consolidation_needed": false, 
        "guest_question": null, 
        "guest_tools_status": "guestToolsRunning", 
        "guest_tools_version": "10247", 
        "hw_cores_per_socket": 1, 
        "hw_datastores": [
            "x-113"
        ], 
        "hw_esxi_host": "10.x.x.x", 
        "hw_eth0": {
            "addresstype": "assigned", 
            "ipaddresses": [
                "10.x.x.2"
            ], 
            "label": "Network adapter 1", 
            "macaddress": "00:x:x:x:d9:b3", 
            "macaddress_dash": "00-x-x-x-d9-b3", 
            "summary": "SERVER_200"
        }, 
        "hw_files": [
            "[_atspi_linux2_nac2-113] Xkube462/Xkube462.vmx", 
            "[_atspi_linux2_nac2-113] Xkube462/Xkube462.nvram", 
            "[_atspi_linux2_nac2-113] Xkube462/Xkube462.vmsd", 
            "[_atspi_linux2_nac2-113] Xkube462/Xkube462.vmdk"
        ], 
        "hw_folder": "/x/x/x/x/x", 
        "hw_guest_full_name": "Ubuntu Linux (64-bit)", 
        "hw_guest_ha_state": true, 
        "hw_guest_id": "ubuntu64Guest", 
        "hw_interfaces": [
            "eth0"
        ], 
        "hw_is_template": false, 
        "hw_memtotal_mb": 8192, 
        "hw_name": "Xkube462", 
        "hw_power_status": "poweredOn", 
        "hw_processor_count": 4, 
        "hw_product_uuid": "42171f8f-cd71-ada1-eb93-c87dbb9498a3", 
        "instance_uuid": "50176c3b-c8a6-592b-d8c2-aa8cd38b6a72", 
        "ipv4": "10.x.x.2", 
        "ipv6": null, 
        "module_hw": true, 
        "snapshots": []
    }, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {}, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "x", 
            "disk": [
                {
                    "datastore": "x-113", 
                    "size_gb": 30, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": "10.x.x.13", 
            "folder": "/x/x", 
            "force": false, 
            "guest_id": null, 
            "hardware": {
                "memory_mb": 8192, 
                "num_cpus": 4
            }, 
            "hostname": "10.x.x.13", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "Xkube462", 
            "name_match": "first", 
            "networks": [
                {
                    "gateway": "10.x.x.10", 
                    "ip": "10.x.x.2", 
                    "name": "SERVER_200", 
                    "netmask": "255.255.0.0", 
                    "type": "static"
                }
            ], 
            "password": "xxxxxxxxxxxxxxx",
            "port": 443, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "present", 
            "template": "WebHosting-Ubuntu-16.04-Kubernetes", 
            "username": "xxxxx", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": true
        }
    }
}
META: ran handlers
META: ran handlers

PLAY RECAP *********************************************************************************************************************************
localhost
```

```

```
