### ISSUE TITLE
openshift_raw module can't update deploymentconfig

### ISSUE THREAD

**Issue by schue30** [ansible/ansible#41585]
##### SUMMARY

The ansible openshift_raw module cannot update a deploymentconfig that contains ether a liveness_probe or a readiness_probe with the parameter exec. The problem is, that it can't patch the kubernetes/openshift object. The following error is shown:
```
Failed to patch object: Unable to find 'exec' in probe. Valid property names include: tcp_socket, timeout_seconds, failure_threshold, _exec, period_seconds, success_threshold, http_get, initial_delay_seconds
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

openshift_raw

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
```

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Run this example playbook twice. First time it will finish successfully and the second time you will get the error:
```
Failed to patch object: Unable to find 'exec' in probe. Valid property names include: tcp_socket, timeout_seconds, failure_threshold, _exec, period_seconds, success_threshold, http_get, initial_delay_seconds
```

```yaml
---
- hosts: all
  tasks:
    - openshift_raw:
        state: present
        definition:
          apiVersion: v1
          kind: DeploymentConfig
          metadata:
            name: "redis-dc"
            namespace: "example"
          spec:
            replicas: 1
            selector:
              name: "redis"
            strategy:
              type: Recreate
            template:
              metadata:
                labels:
                  name: "redis"
              spec:
                containers:
                - image: "redis:latest"
                  name: "redis"
                  readinessProbe:
                    exec:
                      command: [ "/bin/sh", "-i", "-c", "test \"$(redis-cli -h 127.0.0.1 ping)\" == \"PONG\"" ]
                    initialDelaySeconds: 5
                    timeoutSeconds: 1
                  ports:
                  - containerPort: 6379
                    protocol: TCP
                restartPolicy: Always
```

##### EXPECTED RESULTS

That the second run patches the openshift object and won't crash.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "item": "deployment", "msg": "Failed to patch object: Unable to find 'exec' in probe. Valid property names include: _exec, failure_threshold, http_get, initial_delay_seconds, period_seconds, success_threshold, tcp_socket, timeout_seconds"}
```
