### ISSUE TITLE
ipa_user module overwrites user in IPA even if nothing changes

### ISSUE THREAD

**Issue by mmazek** [ansible/ansible#41582]
##### SUMMARY
ipa_user module overwrites user in IPA even if nothing changes. It resets user's password and adds the step to both OK and changed summary.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
module ipa_user

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = None
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ubuntu/.local/lib/python2.7/site-packages/ansible
  executable location = /home/ubuntu/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
No changes in configuration
No changes in ansible.cfg
##### OS / ENVIRONMENT
Ubuntu 16.04.4 LTS
##### STEPS TO REPRODUCE
Role tasks yml file:
```
---
- name: Groups setup
  ipa_group:
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_prot: "{{ ipa_prot }}"
    ipa_user: "{{ ipa_user }}"
    ipa_pass: "{{ ipa_pass }}"
    cn: "{{ item.name }}"
    name: "{{ item.name }}"
    gidnumber: "{{ item.gidnumber }}"
    state: present
  with_items: "{{ ipa_groups }}"
- name: DE Users setup
  ipa_user:
    ipa_host: "{{ ipa_host }}"
    ipa_port: "{{ ipa_port }}"
    ipa_prot: "{{ ipa_prot }}"
    ipa_user: "{{ ipa_user }}"
    ipa_pass: "{{ ipa_pass }}"
    name: "{{ item.name }}"
    uid: "{{ item.name }}"
    displayname: "{{ item.displayname }}"
    gidnumber: "{{ ipa_groups[1].gidnumber }}"
    givenname: "{{ item.givenname }}"
    loginshell: "{{ item.loginshell }}"
    mail:
      - "{{ item.mail }}"
    sn: "{{ item.sn }}"
    uidnumber: "{{ item.uidnumber }}"
    password: "{{ item.password }}"
    state: present
  with_items: "{{ ipa_users }}"
```

Role vars yml file:
```
ipa_groups:
  - name: admins
    gidnumber: 658600001
  - name: de
    gidnumber: 658600003
ipa_users:
  - name: username
    displayname: username
    givenname: name
    sn: surname
    loginshell: /bin/bash
    mail: username@example.com
    uidnumber: 658700000
    password: bla1234567
```

##### EXPECTED RESULTS
First the role should create 2 IPA groups and 1 IPA user. The next excutions should report no changes.

##### ACTUAL RESULTS
Ansible changes user every time and increments OK and CHANGED recap:
```
PLAY [tag_Name_IPA] *******************************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************************************
ok: [172.16.128.115]

TASK [ipa_mngmt : Groups setup] *******************************************************************************************************
ok: [172.16.128.115] => (item={u'gidnumber': 658600001, u'name': u'admins'})
ok: [172.16.128.115] => (item={u'gidnumber': 658600003, u'name': u'de'})

TASK [ipa_mngmt : DE Users setup] *****************************************************************************************************
changed: [172.16.128.115] => (item={u'password': u'bla1234567', u'displayname': u'username', u'name': u'username', u'loginshell': u'/bin/bash', u'uidnumber': 658700000, u'sn': u'surname', u'mail': u'username@example.com', u'givenname': u'name'})

PLAY RECAP ****************************************************************************************************************************
172.16.128.115             : ok=3    changed=1    unreachable=0    failed=0
```
