### ISSUE TITLE
Nova Compute Module confuses instances with similar names

### ISSUE THREAD

**Issue by ggillies** [ansible/ansible#4158]
Hi,

If I have an inventory file with

```
[nova-instances]
instance1
instance11
```

And then a playbook called on that inventory for all hosts in nova-instances with serial 1, that does

```

---
- name: create openstack instance
  nova_compute:
    name: "{{ inventory_hostname }}"
    auth_url: "{{ openstack_auth_url }}"
    flavor_id: 1
    image_id: "{{ openstack_image_id }}"
    key_name: "{{ openstack_key_name }}"
    login_username: "{{ openstack_login_username }}"
    login_password: "{{ openstack_login_password }}"
    login_tenant_name: "{{ openstack_login_tenant_name }}"
    nics:
      - net-id: 3721f603-3234-4c14-b8c7-e230f592eb15
    region_name: "{{ openstack_region_name }}"
    security_groups: default
    wait_for: 500
```

What happens is if instance11 gets created, and then it returns instance1 as being ok, and not creating the instance, as it thinks it already exists. This is likely because the name instance1 is a substring of the name instance11.

This could be deemed a bug in the code of the openstack libraries itself, or intended functionality on their behalf, I'm not sure. If it's intended, ansible should try to do its own checking to make sure that the name of the instance we get back does indeed match the name in the name field of the task
