### ISSUE TITLE
Dependent Roles run multiple times even though 'run_once: True' is specified

### ISSUE THREAD

**Issue by jsollom** [ansible/ansible#41595]
##### SUMMARY
When a role that another role is dependent upon and the dependency has a run_once: True statement attached to it, that dependency is run more than once.

This may be issue #31751.
https://github.com/ansible/ansible/issues/31751

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
run_once

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = None
  configured module search path = [u'/Users/jasons/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Apr 25 2018, 15:30:04) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### CONFIGURATION

No output.
##### OS / ENVIRONMENT

macOS Sierra 10.12.6
##### STEPS TO REPRODUCE

I created three roles role1, role2, and role3.  I also created two other roles dependency1 and dependency2.  Each of the roles is dependent upon both dependencies.

You can run the test by creating the aforementioned file structure and populating it with the files below.
# Command invocation
export ANSIBLE_HOST_KEY_CHECKING=false
ansible-playbook -vv -i inventory.yml -b test.yml

If you uncomment the commented out section of the role dependency2, then the play will act as expected and the dependency will only be run once.  However, this is a bug, and I do not think this should be required.  This looks like it could be bug 31751 (https://github.com/ansible/ansible/issues/31751).

```yaml

# Command invocation (repeated from above)
export ANSIBLE_HOST_KEY_CHECKING=false
ansible-playbook -vv -i inventory.yml -b test.yml

#Inventory file inventory.yml
---
nodes:
  hosts:
    172.17.8.101:
    172.17.8.102:
    172.17.8.103:

# Top-level play book test.yml
---
- hosts: nodes
  any_errors_fatal: true
  remote_user: root

  roles:
    - role: role1
    - role: role2
    - role: role3

#./roles/role1/tasks/main.yml
- name: Role 1
  debug: msg=role1
#role1/meta/main.yml
dependencies:
  - name: dependency1
  - name: dependency2

#./roles/role2/tasks/main.yml
- name: Role 2
  debug: msg=role2
#role2/meta/main.yml
dependencies:
  - name: dependency1
  - name: dependency2

#./roles/role3/tasks/main.yml
- name: Role 3
  debug: msg=role3
#role3/meta/main.yml
dependencies:
  - name: dependency1
  - name: dependency2

#./roles/dependency1/tasks/main.yml
---
- name: Dependency 1
  file:
    path: /tmp/dependency1
    state: touch

#./roles/dependency2/tasks/main.yml
---
- name: Dependency 2 -- Touching a file /tmp/dependency2
  file:
    path: /tmp/dependency2
    state: touch
  delegate_to: "{{ groups['nodes'][0] }}"
  run_once: true
#- name: Record that dependency2 ran  # Workaround #https://github.com/ansible/ansible/issues/31751
#  set_fact:
#    dependency2_run: True
```

##### EXPECTED RESULTS

I expected dependency2 to be run only once.
ansible-playbook 2.5.4
  config file = None
  configured module search path = [u'/Users/jasons/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Apr 25 2018, 15:30:04) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
No config file found; using defaults

PLAYBOOK: test.yml *****************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [nodes] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/test.yml:3
ok: [172.17.8.102]
ok: [172.17.8.103]
ok: [172.17.8.101]
META: ran handlers

TASK [dependency1 : Dependency 1] **************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/dependency1/tasks/main.yml:2
changed: [172.17.8.102] => {"changed": true, "dest": "/tmp/dependency1", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}
changed: [172.17.8.103] => {"changed": true, "dest": "/tmp/dependency1", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}
changed: [172.17.8.101] => {"changed": true, "dest": "/tmp/dependency1", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}

TASK [dependency2 : Dependency 2 -- Touching a file /tmp/dependency2] **************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/dependency2/tasks/main.yml:2
changed: [172.17.8.101 -> 172.17.8.101] => {"changed": true, "dest": "/tmp/dependency2", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}

TASK [role1 : Role 1] **************************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/role1/tasks/main.yml:1
ok: [172.17.8.101] => {
    "msg": "role1"
}
ok: [172.17.8.103] => {
    "msg": "role1"
}
ok: [172.17.8.102] => {
    "msg": "role1"
}

TASK [role2 : Role 2] **************************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/role2/tasks/main.yml:1
ok: [172.17.8.101] => {
    "msg": "role2"
}
ok: [172.17.8.103] => {
    "msg": "role2"
}
ok: [172.17.8.102] => {
    "msg": "role2"
}

TASK [role3 : Role 3] **************************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/role3/tasks/main.yml:1
ok: [172.17.8.101] => {
    "msg": "role3"
}
ok: [172.17.8.103] => {
    "msg": "role3"
}
ok: [172.17.8.102] => {
    "msg": "role3"
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************
172.17.8.101               : ok=7    changed=2    unreachable=0    failed=0
172.17.8.102               : ok=6    changed=1    unreachable=0    failed=0
172.17.8.103               : ok=6    changed=1    unreachable=0    failed=0

##### ACTUAL RESULTS

```
ansible-playbook 2.5.4
  config file = None
  configured module search path = [u'/Users/jasons/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 2.7.14 (default, Apr 25 2018, 15:30:04) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
No config file found; using defaults

PLAYBOOK: test.yml *****************************************************************************************************************************************************************************
1 plays in test.yml

PLAY [nodes] *******************************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/test.yml:3
ok: [172.17.8.102]
ok: [172.17.8.103]
ok: [172.17.8.101]
META: ran handlers

TASK [dependency1 : Dependency 1] **************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/dependency1/tasks/main.yml:2
changed: [172.17.8.103] => {"changed": true, "dest": "/tmp/dependency1", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}
changed: [172.17.8.102] => {"changed": true, "dest": "/tmp/dependency1", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}
changed: [172.17.8.101] => {"changed": true, "dest": "/tmp/dependency1", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}

TASK [dependency2 : Dependency 2 -- Touching a file /tmp/dependency2] **************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/dependency2/tasks/main.yml:2
changed: [172.17.8.101 -> 172.17.8.101] => {"changed": true, "dest": "/tmp/dependency2", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}

TASK [role1 : Role 1] **************************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/role1/tasks/main.yml:1
ok: [172.17.8.101] => {
    "msg": "role1"
}
ok: [172.17.8.103] => {
    "msg": "role1"
}
ok: [172.17.8.102] => {
    "msg": "role1"
}

TASK [dependency2 : Dependency 2 -- Touching a file /tmp/dependency2] **************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/dependency2/tasks/main.yml:2
changed: [172.17.8.103 -> 172.17.8.101] => {"changed": true, "dest": "/tmp/dependency2", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}

TASK [role2 : Role 2] **************************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/role2/tasks/main.yml:1
ok: [172.17.8.101] => {
    "msg": "role2"
}
ok: [172.17.8.103] => {
    "msg": "role2"
}
ok: [172.17.8.102] => {
    "msg": "role2"
}

TASK [dependency2 : Dependency 2 -- Touching a file /tmp/dependency2] **************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/dependency2/tasks/main.yml:2
changed: [172.17.8.102 -> 172.17.8.101] => {"changed": true, "dest": "/tmp/dependency2", "gid": 0, "group": "root", "mode": "0644", "owner": "root", "size": 0, "state": "file", "uid": 0}

TASK [role3 : Role 3] **************************************************************************************************************************************************************************
task path: /Users/jasons/working/git/cms-base-box/roles/role3/tasks/main.yml:1
ok: [172.17.8.101] => {
    "msg": "role3"
}
ok: [172.17.8.103] => {
    "msg": "role3"
}
ok: [172.17.8.102] => {
    "msg": "role3"
}
META: ran handlers
META: ran handlers

PLAY RECAP *************************************************************************************************************************************************************************************
172.17.8.101               : ok=6    changed=2    unreachable=0    failed=0
172.17.8.102               : ok=6    changed=2    unreachable=0    failed=0
172.17.8.103               : ok=6    changed=2    unreachable=0    failed=0
```
