### ISSUE TITLE
Module service_facts: appears to return unusable dictionary entries containing periods

### ISSUE THREAD

**Issue by rpural** [ansible/ansible#41606]
##### SUMMARY

Module service_facts: appears to return unusable dictionary entries containing periods

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

ansible/lib/ansible/modules/system/service_facts.py

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /home/auto/ts00086/ansible.cfg
  configured module search path = [u'/home/auto/ts00086/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

HOST_KEY_CHECKING(/home/auto/ts00086/ansible.cfg) = False

##### OS / ENVIRONMENT

Red Hat RHEL7.4

##### STEPS TO REPRODUCE

Run playbook with task service_facts:, then 
  - fail:
        msg: "test"
    when: ansible_facts.services.httpd.service is defined

or
    when: ansible_facts.services["httpd.service"] is defined

```yaml
---
- name: Test the result of the service facts module
  hosts: all

  tasks:
      - service_facts:

      - name: Display service facts
        debug:
            var: ansible_facts.services

      - name: Isolate a single service
        debug:
            var: ansible_facts.services.httpd

      - name: Isolate a single service attribute
        debug:
            var: ansible_facts.services.httpd.state

      - name: Test failure if service is already running
        fail:
            msg: "Service httpd is already running"
        when: ansible_distribution_major_version == "6" and ansible_facts.services.httpd is defined

      - name: Test failure if service is already running
        fail:
            msg: "Service httpd is already running"
        when: ansible_distribution_major_version == "7" and ansible_facts.services.["httpd.service"] is defined
...
```

##### EXPECTED RESULTS

I expected some way to find the entry for specific services

##### ACTUAL RESULTS

It always comes back as 'template error while templating string: expected name or number. String: {% if ansible_distribution_major_version == \"7\" and ansible_facts.services.[\"httpd.service\"] is defined %} True {% else %} False {% endif %}'

This works for RHEL6, where the variable is ansible_facts.services.httpd.

```
{
    "msg": "The conditional check 'ansible_distribution_major_version == \"7\" and ansible_facts.services.[\"httpd.service\"] is defined' failed. The error was: template error while templating string: expected name or number. String: {% if ansible_distribution_major_version == \"7\" and ansible_facts.services.[\"httpd.service\"] is defined %} True {% else %} False {% endif %}\n\nThe error appears to have been in '/var/lib/awx/projects/_9__test_git_repository/test_service_facts.yml': line 25, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n      - name: Test failure if service is already running\n        ^ here\n"
}
```
