### ISSUE TITLE
Support `--separate-git-dir` option in Git module

### ISSUE THREAD

**Issue by webknjaz** [ansible/ansible#41611]
##### SUMMARY

This is a follow up for https://github.com/ansible/ansible/pull/38016#pullrequestreview-118799688:
Git module should support `--separate-git-dir`:
* we need to support `separate-git-dir` module argument
* have docs/examples for that
* cover all of that with tests including negative ones

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

git
##### ANSIBLE VERSION

```
devel
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```yaml
git:
  repo: git://...
  dest: /opt/app/web-app-xxx
  separate-git-dir: /var/db/git/web-app-xxx.git
```

##### EXPECTED RESULTS

It would run `git clone --separate-git-dir` under the hood (or a fallback for older Git versions)

##### ACTUAL RESULTS

N/A. It doesn't work now, however if cloned manually subsequent updates work as of #38016.
