### ISSUE TITLE
homebrew cask state upgraded upgrades all - not the one given

### ISSUE THREAD

**Issue by EugenMayer** [ansible/ansible#41639]
# ENV

- ansible 2.5.4 (pip installed)
- MacOS High Sierra

Latest homebrew
```
brew --version
Homebrew 1.6.8
Homebrew/homebrew-core (git revision f593; last commit 2018-06-18)
```

# case
assuming you have 

```
- homebrew_cask:
    name: "{{ java_item }}"
    state: upgraded
    upgrade: true
  with_items:
    - java8
  loop_control:
    loop_var: java_item
```

# Expectation
the expectation would be, that ansible will try to upgrade java8 only. 

# Error
But in fact, it will upgrade all casks instead
