### ISSUE TITLE
to_nice_json indent is NOT working

### ISSUE THREAD

**Issue by dungdm93** [ansible/ansible#41635]
##### SUMMARY
I'd like to customize indentation of json file using `to_nice_json(indent=2)` but it is NOT working. :(

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
to_nice_json

##### ANSIBLE VERSION
```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dungdm93/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
Nothing special. Default only.

##### OS / ENVIRONMENT
Control machine: Ubuntu 16.04.4 LTS
Target machines: Ubuntu 16.04.4 LTS

##### STEPS TO REPRODUCE
```yaml
- name: Configs consul agent
  copy:
    content: "{{ consul_configs | to_nice_json(indent=2) }}"
    dest:    /etc/consul.d/server.json
    force:   yes
```

##### EXPECTED RESULTS
```json
{
  "ui": true, 
  "data_dir": "/var/lib/consul", 
  "server": true
}
```
##### ACTUAL RESULTS
```json
{"ui": true, "data_dir": "/var/lib/consul", "server": true}
```
##### NOTE
When I remove `indent` from `to_nice_json`. It output nice json, but indentation is 4:
```yaml
content: "{{ consul_configs | to_nice_json }}"
```
```json
{
    "data_dir": "/opt/consul", 
    "server": true, 
    "ui": true
}
```
