### ISSUE TITLE
Module jenkins_plugin not python3 compatible when setting a version

### ISSUE THREAD

**Issue by Benoit-DunandLaisin** [ansible/ansible#41643]
##### SUMMARY

When running a jenkins_plugin task with state=present and a version, if managed target is running with python3, then task fails with an exception.

No problem without version or with state=latest.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

jenkins_plugin

##### ANSIBLE VERSION

```
ansible 2.5.4
```

##### OS / ENVIRONMENT

Local OS (running ansible): Ubuntu 16.04
Local python (running ansible): Python 2.7.12
Remote OS: Ubuntu 16.04
ansible_python_interpreter: Python 3.5.2

##### STEPS TO REPRODUCE

```yaml
---
- hosts: "{{ target }}"
  vars:
    jenkins_plugins:
      workflow-api: "2.27"
  tasks:
    - jenkins_plugin:
        name: "{{ item.key }}"
        state: present
        version: "{{ item.value }}"
        url: "http://localhost:80"
        jenkins_home: "{{ jenkins_home }}"
        url_username: "{{ admin_user }}"
        url_password: "{{ admin_password }}"
        owner: "{{ jenkins_owner }}"
        group: "{{ jenkins_owner }}"
      with_dict: "{{ jenkins_plugins }}"

```

##### EXPECTED RESULTS

Expect to work without error.

##### ACTUAL RESULTS

```
failed: [hostname] (item={'value': u'2.27', 'key': u'workflow-api'}) => {"changed": false, "item": {"key": "workflow-api", "value": "2.27"}, "module_stderr": "Shared connection to hostname closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_1v0e2qzm/ansible_module_jenkins_plugin.py\", line 799, in <module>\r\n    main()\r\n  File \"/tmp/ansible_1v0e2qzm/ansible_module_jenkins_plugin.py\", line 782, in main\r\n    changed = jp.install()\r\n  File \"/tmp/ansible_1v0e2qzm/ansible_module_jenkins_plugin.py\", line 491, in install\r\n    self._write_file(plugin_file, data)\r\n  File \"/tmp/ansible_1v0e2qzm/ansible_module_jenkins_plugin.py\", line 630, in _write_file\r\n    os.write(tmp_f_fd, data.read())\r\nAttributeError: 'bytes' object has no attribute 'read'\r\n", "msg": "MODULE FAILURE", "rc": 1}

```
