### ISSUE TITLE
[bigip-profile-client-ssl-module] Ciphers should not have DEFAULT as default-value

### ISSUE THREAD

**Issue by mkrsn** [ansible/ansible#41640]
##### SUMMARY
The Module "bigip-profile-client-ssl-module" has the Parameter "ciphers" which has a default-value (DEFAULT). This is a Problem because if there is no given value, it should use the Value from the Parent-Profile instead of a default-value (as designed by F5).

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

bigip-profile-client-ssl

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = None
  configured module search path = ['/home/mkrsn/.ansible/plugins/modules',,'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib64/python3.5/site-packages/ansible
  executable location = /usr/lib/python-exec/python3.5/ansible
  python version = 3.5.5 (default, Apr 18 2018, 10:25:32) [GCC 6.4.0]
```

##### STEPS TO REPRODUCE

```yaml

loadbalancer_ssl:
  - { state: "present", partition: "Common", crt: "test1.example.local-20180615.crt", key: "test1.example.local-20180615.key", chain: "", ssl_profile_parent: "clientssl" }

- name: Manage Client-SSL-Profiles (with Chain-Cert)
  tags:
    - loadbalancer
    - loadbalancer-ssl-profile
  bigip_profile_client_ssl:
    provider:
      server: "{{ loadbalancer_node }}"
      user: "{{ loadbalancer_user }}"
      password: "{{ loadbalancer_pwd }}"
      validate_certs: no
      transport: rest
    name: "{{ item.crt | regex_replace('\\.[a-zA-z]{3}$', '') }}"
    parent: "/{{ item.partition }}/{{ item.ssl_profile_parent }}"
    partition: "{{ item.partition }}"
    cert_key_chain:
      - cert: "{{ item.crt }}"
        key: "{{ item.key }}"
        chain: "{{ item.chain }}"
    state: "{{ item.state }}"
  with_items:
    - "{{ loadbalancer_ssl }}"
  when:
    - item.chain != ""
```

##### EXPECTED RESULTS
I would expect that when the parameter "ciphers" is not given that the inheritance from the parent-profile would be used

##### ACTUAL RESULTS

The Value from the Parent-Profile isn't used.

![screenshot_20180618_105836](https://user-images.githubusercontent.com/10330231/41527763-6c36257a-72e8-11e8-86a1-08691223b298.png)

```

```
