### ISSUE TITLE
 azure_rm_publicip_facts - no action detected in task

### ISSUE THREAD

**Issue by ghost** [ansible/ansible#41679]
##### SUMMARY

Error in azure_rm_publicip_facts task - no action detected in task.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### STEPS TO REPRODUCE

```yaml
- name: Get facts for one Public IP
  azure_rm_publicip_facts:
    resource_group: "{{ resourceGroupName }}"
    name: "{{ resourceGroupName + '-' + item }}-node-ip"
    subscription_id: "{{ azure_subscription }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant}}"
    secret: "{{ az_secret }}"
  with_items: "{{ nodes }}"
  tags:
    - getInfraFacts
```

##### EXPECTED RESULTS

List of public IP address dicts.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {
    "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\n\nThe error appears to have been in 'ansible/roles/manage_azure/tasks/get_infra_facts.yaml': line 36, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Get facts for one Public IP\n  ^ here\n"
}

```

**Comment by Fred-sun** [comment]
Hi @adamsem ， I have tried your YML, execute successfully , Could you try again , if fail, please tell us your test environment and your YML file(all) .

**Comment by ghost** [comment]
I have tried again and get the same error. I'm adding my task YAML file, also i see that "Get facts for a virtual machine scale set" task works without existing azure resource group.

```yaml
- name: Get instance of SQL Server
  azure_rm_sqlserver_facts:
    resource_group: "{{ resourceGroupName }}"
    server_name: "{{ server_name }}"
    subscription_id: "{{ azure_subscription }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant}}"
    secret: "{{ az_secret }}"
  tags:
    - getInfraFacts

- name: Get facts for a virtual machine scale set
  azure_rm_virtualmachine_scaleset_facts:
    resource_group: "{{ resourceGroupName }}"
    name: "{{ resourceGroupName + '-' + item }}-node"
    #format: curated - available in ansible 2.6
    subscription_id: "{{ azure_subscription }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant}}"
    secret: "{{ az_secret }}"
  with_items: "{{ nodes }}"
  tags:
    - getInfraFacts

- name: Get network interfaces within a resource group
  azure_rm_networkinterface_facts:
    resource_group: "{{ resourceGroupName }}"
    subscription_id: "{{ azure_subscription }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant}}"
    secret: "{{ az_secret }}"
  tags:
    - getInfraFacts

- name: Get facts for one Public IP
  azure_rm_publicip_facts:
    resource_group: "{{ resourceGroupName }}"
    name: "{{ resourceGroupName + '-' + item }}-node-ip"
    subscription_id: "{{ azure_subscription }}"
    client_id: "{{ az_client_id }}"
    tenant: "{{ az_tenant}}"
    secret: "{{ az_secret }}"
  with_items: "{{ nodes }}"
  tags:
    - getInfraFacts


```
