### ISSUE TITLE
add an option for tower_host to merge variables instead of replacing

### ISSUE THREAD

**Issue by orgito** [ansible/ansible#41687]
##### SUMMARY

I want to use the `tower_host` module to add/replace one specific variable of an existing host in tower.  Currently the module will remove all existing variables from the host leaving only the variable specified in the task.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
tower_host

##### ANSIBLE VERSION
```
ansible 2.5.5
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/renato/.ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/renato/.ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60s -o ForwardAgent=yes
ANSIBLE_SSH_CONTROL_PATH(/home/renato/.ansible.cfg) = %(directory)s/ansible-ssh-%%C
CACHE_PLUGIN(/home/renato/.ansible.cfg) = redis
CACHE_PLUGIN_TIMEOUT(/home/renato/.ansible.cfg) = 86100
DEFAULT_FILTER_PLUGIN_PATH(/home/renato/.ansible.cfg) = [u'/home/renato/ansible/plugins/filter_plugins']
DEFAULT_FORKS(/home/renato/.ansible.cfg) = 15
DEFAULT_GATHERING(/home/renato/.ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/renato/.ansible.cfg) = [u'/home/renato/ansible/hosts']
DEFAULT_REMOTE_USER(/home/renato/.ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/renato/.ansible.cfg) = [u'/home/renato/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/renato/.ansible.cfg) = /home/renato/ansible/.vault-passwd.sh
HOST_KEY_CHECKING(/home/renato/.ansible.cfg) = False
```

##### OS / ENVIRONMENT
Ansible Host: Fedora 28 with ansible-tower-cli (3.3.0)
Tower Test Host: Centos 7.5.1804 / AWX 1.0.6.16

##### STEPS TO REPRODUCE
Task to add/replace a variable to an existing tower host. 
```yaml
  - name: Update host in Tower
    tower_host:
      name: "{{ inventory_hostname }}"
      inventory: "Telecom Hosts - Production"
      variables:
        vm_uuid: "{{facts.instance.hw_product_uuid}}"
      tower_verify_ssl: no
    connection: local
```

In order not to change the current behavior, which potentially breaks existing playbooks, maybe there should be a new parameter, like `merge_variable`, to specify that the variable(s) should be added and not completely replace existing variables:

```yaml
  - name: Update host in Tower
    tower_host:
      name: "{{ inventory_hostname }}"
      inventory: "Telecom Hosts - Production"
      merge_variables: yes     
      variables:
        vm_uuid: "{{facts.instance.hw_product_uuid}}"
      tower_verify_ssl: no
    connection: local
```

##### EXPECTED RESULTS
The `vm_uuid` variable should be added to the existing list of variables if it is not already there or changed if already there and different. Any other variables should not be touched

##### ACTUAL RESULTS
The module delete all the existing variables and keep only the variables specified in the task.
