### ISSUE TITLE
bigip_gtm_pool: When entering a string value with a colon for the "virtual_server" parameter, the module does not process the full string but returns the value after the colon.  

### ISSUE THREAD

**Issue by derek-linke** [ansible/ansible#41705]
##### SUMMARY
bigip_gtm_pool: When entering a string value with a colon for the "virtual_server" parameter, the module does not process the full string but returns the value after the colon.  

Example: 
 members:
    - server: "GTM_BIG-IP Server 1"
      virtual_server: "lotoc0216lab:www.mycoolapp-mtl.localhost_https_443_virtual"

The virtual server name returned is www.mycoolapp-mtl.localhost_https_443_virtual instead of returning "lotoc0216lab:www.mycoolapp-mtl.localhost_https_443_virtual".  I have tested without the colon and there are no issues.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
bigip_gtm_pool

##### ANSIBLE VERSION
ansible 2.6.0rc2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

##### CONFIGURATION

No changes.

##### OS / ENVIRONMENT

redhat-release-server-7.3-7.e17.x86_64

##### STEPS TO REPRODUCE

```yaml
- name: Create a GTM pool
  bigip_gtm_pool:
   server: "{{ ansible_host }}"
   user: "{{ http_user }}"
   password: "{{ http_pass }}"
   name: "{{ pool.name }}"
   partition: "{{ pool.partition }}"
   type: a
   preferred_lb_method: "{{ pool.load_balancing_mode }}"
#   alternate_lb_method: ratio
#   fallback_lb_method: round-robin
#   fallback_ip: 10.22.22.111
   members:
    - server: "GTM_BIG-IP Server 1"
      virtual_server: "lotoc0216lab:www.mycoolapp-mtl.localhost_https_443_virtual"
   validate_certs: no
   state: present
  delegate_to: localhost
  with_items: "{{ pool.members }}"
```

##### EXPECTED RESULTS

Pool is created with the associated virtual server.

##### ACTUAL RESULTS

```
"msg": "400 Unexpected Error: Bad Request for uri: https://10.215.250.6:443/mgmt/tm/gtm/pool/a/~Common~www.mycoolapp-mtl.localhost_pool/\nText: u'{\"code\":400,\"message\":\"01070226:3: Pool Member www.mycoolapp-mtl.localhost_https_443_virtual references a nonexistent Virtual Server\",\"errorStack\":[],\"apiError\":3}'"
```
