### ISSUE TITLE
Add aux_address option to docker_network module

### ISSUE THREAD

**Issue by dbolotin** [ansible/ansible#41714]
##### SUMMARY
No way to pass --aux-address option in docker_network module

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
docker_network

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /home/ansible/test/ansible/ansible.cfg
  configured module search path = ['/home/ansible/test/ansible/library']
  ansible python module location = /home/ansible/.local/lib/python3.6/site-packages/ansible
  executable location = /home/ansible/.local/bin/ansible
  python version = 3.6.5 (default, Apr  1 2018, 05:46:30) [GCC 7.3.0]
```

##### CONFIGURATION
```
ANSIBLE_SSH_RETRIES(/home/ansible/test/ansible/ansible.cfg) = 4
DEFAULT_GATHER_SUBSET(/home/ansible/test/ansible/ansible.cfg) = !hardware
DEFAULT_HOST_LIST(/home/ansible/test/ansible/ansible.cfg) = ['/home/ansible/test/ansible/hosts']
DEFAULT_MODULE_PATH(/home/ansible/test/ansible/ansible.cfg) = ['/home/ansible/test/ansible/library']
DEFAULT_STDOUT_CALLBACK(/home/ansible/test/ansible/ansible.cfg) = debug
```

##### OS / ENVIRONMENT
Ubuntu 18.04

##### EXPECTED RESULTS
Having a way to specify `--aux-address` options, e.g.:
```yaml
- name: Creating VPN docker network
  docker_network:
    ...
    aux_addresses:
      DefaultGatewayIPv4: 192.168.0.1
    ...
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/docker/docker_network.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/docker/docker_network.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @keitwb @olsaki
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @felixfontein
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @DBendit
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @akshay196 @danihodovic @dariko @jwitko @kassiansun @tbouvet
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by DBendit** [comment]
This is already supported with the `ipam_options` parameter, being expanded upon and renamed in https://github.com/ansible/ansible/pull/47492.

You should be able to have something like the following:
```yaml
- name: Create a network with custom IPAM config
  docker_network:
    name: network_three
    ipam_options:
      subnet: 172.3.27.0/24
      gateway: 172.3.27.2
      iprange: 172.3.27.0/26
      aux_addresses:
        host1: 172.3.27.3
        host2: 172.3.27.4
```

notabug
