### ISSUE TITLE
win_reboot stuck in loop while executing test_command due to second reboot

### ISSUE THREAD

**Issue by avishefi** [ansible/ansible#41713]
##### SUMMARY

The `win_reboot` action plugin enters to an infinite loop when executing the `test_command` due to unidentified second reboot happening after the `test_command` execution loop begins.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

win_reboot

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
DEFAULT_STDOUT_CALLBACK(/etc/ansible/ansible.cfg) = debug
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT

RHEL 7.5 (Maipo)

##### STEPS TO REPRODUCE

Installing the Desktop-Experience Windows feature on a Windows Server 2012 R2 machine requires multiple reboots that are not handled by `win_reboot`. To alleviate this, the `Get-PendingReboot.ps1` Powershell script is used to test whether the machine is ready to continue work. The script was modified to cope with CBS ExecuteState, here is the version used: https://gist.github.com/avishefi/580273260ceb7228301ad635d93eb815

Inventory:
```yaml
ansible_user: Administrator
ansible_password: <secret>
ansible_port: 5986
ansible_winrm_scheme: https
ansible_winrm_transport: credssp
ansible_winrm_server_cert_validation: ignore
```

Playbook:
```yaml
- hosts: all
  connection: winrm
  become: yes
 
  tasks:
    - name: copy Get-PendingReboot.ps1
      win_copy:
        src: "{{ scripts_source }}/Get-PendingReboot.ps1"
        dest: "{{ common_windows_scripts }}\\"
 
    - name: install desktop experience
      win_feature:
        name:
         - Desktop-Experience
      register: winboot
 
    - name: reboot
      win_reboot:
        test_command: "{{ common_windows_scripts }}\\Get-PendingReboot.ps1"
      when: winboot.reboot_required
```

##### EXPECTED RESULTS

The `win_reboot` action plugin continually attempts to connect to the target machine across reboots and finishes after the second reboot having the `test_command` finish successfully.

##### ACTUAL RESULTS

While executing the test_command, the machine reboots a second time. During the second reboot the `win_reboot` action plugin doesn't create a new WinRM shell with the target machine, therefore reusing the same shellid that was previously used. WinRM shells do not survive reboots, hence the continued connection attempts fail from that point onwards.

`win_reboot` enters into a loop attempting to connect after the second reboot and fails authenticating to the target machine. Once in this state, the `win_reboot` action plugin never attempts to re-create the connection, therefore looping until the `reboot_timeout` is elapsed.

The exception details are not reported on the verbose log together with `ANSIBLE_DEBUG=1`, so I added a log message to the win_reboot.py action plugin on the exception clause inside `do_until_success_or_timeout` - the first line below with `EXCEPTION` is the added message with the exception details.

```
  3009 1529455656.52160: EXCEPTION: Server did not response with a CredSSP token after step Step 5. Delegate Credentials - actual ''
  3009 1529455656.52168: win_reboot: post-reboot test command success fail (expected), retrying in 1 seconds...
```

Turning on the WinRM analytic logs shows the following message for each connection attempt:
```
The request for the Windows Remote Shell with ShellId 24F63F46-72BF-4C16-A786-0A46FF86B8DD failed because the shell was not found on the server. Possible causes are: the specified ShellId is incorrect or the shell no longer exists on the server. Provide the correct ShellId or create a new shell and retry the operation.
```
