### ISSUE TITLE
Boolean Variable defined in Inventory file Not picked up by Ansible 

### ISSUE THREAD

**Issue by osayers** [ansible/ansible#41715]
##### SUMMARY
Boolean variable set in inventory file is not picked up during ansible run ("variable undefined"). The variable was defined and executed perfectly in playbook  in ansible-2.2.1 but ceased working after upgrade to ansible-2.5.3+

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible-playbook run does not parse boolean variable in inventory file

##### ANSIBLE VERSION
 ansible --version
ansible 2.5.5
  config file = /home/osayers/git/ipcenterv3-installer/ansible.cfg
  configured module search path = [u'/home/osayers/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug 18 2016, 11:11:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]
##### OS / ENVIRONMENT

Scientific Linux 7.1

##### STEPS TO REPRODUCE

Inventory file:
```ini
[ovpn]
ovpn01.prod.$FQDN ovpn_role=master
ovpn02.prod$FQDN ovpn_role=secondary

[ovpn-vip]
ovpn-vip.$FQDN

[dns]
util01.prod.$FQDN
util02.prod.$FQDN

[dnscaches]
dnscache-01.prod.$FQDN
dnscache-02.prod.$FQDN

[ntp_servers]
$NTP1_IP
$NTP2_IP

[mailrelay]
util01.prod.$FQDN
util02.prod.$FQDN

[reports_controller]
reports01.prod.$FQDN

[buildsheet]
dnscache-01.prod.brooklyn.ipcenter.com buildsheet_ip=$IP
dnscache-02.prod.brooklyn.ipcenter.com buildsheet_ip=$IP
ovpn01.prod.brooklyn.ipcenter.com buildsheet_ip=$IP
ovpn02.prod.brooklyn.ipcenter.com buildsheet_ip=$IP
ovpn-vip.prod.brooklyn.ipcenter.com buildsheet_ip=$IP
util01.prod.brooklyn.ipcenter.com buildsheet_ip=$IP
util02.prod.brooklyn.ipcenter.com buildsheet_ip=$IP
reports01.prod.brooklyn.ipcenter.com buildsheet_ip=$IP

[all:vars]
**ovpn_ha=true**
client_ldap_nat=$NAT_IP
client_puppet_nat=$NAT_IP
openvpn_network=$OPENVPN_NETWORK
openvpn_network_mask=$MASK
ipcenter_domain=$ipcenter_domain
```

```yaml
- block:
      - name: install Keepalived and Quagga
        yum: name={{ item }} state=installed
        with_items:
          - perl-Data-Dumper
          - perl-Devel-Carp
          - perl-NetAddr-IP
          - perl-Proc-Daemon
          - perl-Proc-ProcessTable
          - lm_sensors-libs
          - net-snmp-libs
          - net-snmp
          - keepalived
          - quagga

      - name: Remove Sample Configs, etc from Keepalived Dir
        shell: rm -rf /etc/keepalived/*

      - name: Remove Sample Configs, etc from Quagga Dir
        shell: rm -rf /etc/quagga/*

      - name: Add Quagga Ownership to OpenVPN Log Dir
        file: path=/var/log/openvpn state=directory owner=root group=quagga mode=775

      - name: Setup Syslogging for Keepalived and Injectroute
        template: src=openvpn-syslog.conf dest=/etc/rsyslog.d/openvpn-syslog.conf owner=root group=root mode=644

      - name: Restart Rsyslog So Changes Take Effect
        service: name=rsyslog state=restarted

    **when: ovpn_ha is defined and ovpn_ha**

  - name: Check if ovpn_ha is defined
    fail: msg="Variable 'ovpn_ha' is not defined"
    when: ovpn_ha not in vars

```

Added "Check if ovpn_ha is defined" step to confirm that variable was not being defined

##### EXPECTED RESULTS
packages installed and all other tasks in block performed. Again, this worked perfectly in ansible-2.2.1 but ceased working after upgrade to ansible-2.5.3 and subsquently, ansible-2.5.5

##### ACTUAL RESULTS

```
TASK [openvpn : Verify OpenVPN Started Successfully] ***************************************************************************************************************************************
task path: /home/osayers/git/ipcenterv3-installer/roles/openvpn/tasks/main.yml:106
skipping: [ovpn02.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}
ok: [ovpn01.prod.brooklyn.ipcenter.com] => {"changed": false, "elapsed": 0, "gid": 0, "group": "root", "mode": "0600", "owner": "root", "path": "/var/log/openvpn/ovpn01.prod.brooklyn.ipcenter.com-443.log", "port": null, "search_regex": "Initialization Sequence Completed", "secontext": "unconfined_u:object_r:openvpn_var_log_t:s0", "size": 3998, "state": "file", "uid": 0}

TASK [openvpn : install Keepalived and Quagga] *********************************************************************************************************************************************
task path: /home/osayers/git/ipcenterv3-installer/roles/openvpn/tasks/main.yml:128
skipping: [ovpn01.prod.brooklyn.ipcenter.com] => (item=[])  => {"changed": false, "item": [], "skip_reason": "Conditional result was False"}
skipping: [ovpn02.prod.brooklyn.ipcenter.com] => (item=[])  => {"changed": false, "item": [], "skip_reason": "Conditional result was False"}

TASK [openvpn : Remove Sample Configs, etc from Keepalived Dir] ****************************************************************************************************************************
task path: /home/osayers/git/ipcenterv3-installer/roles/openvpn/tasks/main.yml:142
skipping: [ovpn01.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [ovpn02.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [openvpn : Remove Sample Configs, etc from Quagga Dir] ********************************************************************************************************************************
task path: /home/osayers/git/ipcenterv3-installer/roles/openvpn/tasks/main.yml:145
skipping: [ovpn01.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [ovpn02.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [openvpn : Add Quagga Ownership to OpenVPN Log Dir] ***********************************************************************************************************************************
task path: /home/osayers/git/ipcenterv3-installer/roles/openvpn/tasks/main.yml:148
skipping: [ovpn01.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [ovpn02.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [openvpn : Setup Syslogging for Keepalived and Injectroute] ***************************************************************************************************************************
task path: /home/osayers/git/ipcenterv3-installer/roles/openvpn/tasks/main.yml:151
skipping: [ovpn01.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [ovpn02.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [openvpn : Restart Rsyslog So Changes Take Effect] ************************************************************************************************************************************
task path: /home/osayers/git/ipcenterv3-installer/roles/openvpn/tasks/main.yml:154
skipping: [ovpn01.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}
skipping: [ovpn02.prod.brooklyn.ipcenter.com] => {"changed": false, "skip_reason": "Conditional result was False"}

TASK [openvpn : Check if ovpn_ha is defined] ***********************************************************************************************************************************************
task path: /home/osayers/git/ipcenterv3-installer/roles/openvpn/tasks/main.yml:160
fatal: [ovpn01.prod.brooklyn.ipcenter.com]: FAILED! => {"changed": false, "msg": "Variable 'ovpn_ha' is not defined"}
fatal: [ovpn02.prod.brooklyn.ipcenter.com]: FAILED! => {"changed": false, "msg": "Variable 'ovpn_ha' is not defined"}
	to retry, use: --limit @/home/osayers/git/ipcenterv3-installer/ovpn_test_playbook.retry

PLAY RECAP *********************************************************************************************************************************************************************************
ovpn01.prod.brooklyn.ipcenter.com : ok=34   changed=10   unreachable=0    failed=1
ovpn02.prod.brooklyn.ipcenter.com : ok=21   changed=2    unreachable=0    failed=1
```
