### ISSUE TITLE
NIC creation does not work with VNet in different resource group - Ansible 2.5.5

### ISSUE THREAD

**Issue by the1bit** [ansible/ansible#41728]
##### SUMMARY
I would like to create VM in Azure with Ansible 2.5.5. According to my playbooks the Virtual Network is in different resource group than the VM. When I start to create the NIC I am facing the following error:
```
fatal: [the1bit-cust-01]: FAILED! => {"changed": false, "msg": "subnet the1bit-subnet-fe is not exist"}
```

The followings also don't work:
Subnet config 1:

``` yaml
      subnet: 
        name: "{{env_id}}-subnet-fe"
        resource_group: "{{env_id}}-rg-{{vnet_rg}}"
```

Subnet config 2:

``` yaml
   subnet: "{{env_id}}-subnet-fe"
```

##### ISSUE TYPE
 - Bug Report
 - Support request

##### COMPONENT NAME
azure_rm_networkinterface

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION
Result of ansible-config dump --only-changed command is empty

##### OS / ENVIRONMENT
centos-release-7-4.1708.el7.centos.x86_64

##### STEPS TO REPRODUCE

``` bash
ansible-playbook -i inventory/ -e mainpath="/data/git/azansible/201_multi_nic_vm" playbooks/azure_network_2subnet.yml -vvvv
```

My playbook for NICs creation
```yaml
- name: Create Network Cards
  hosts: vms
  connection: local
  gather_facts: no
  vars:
    rgName: "{{env_id}}-rg-{{resource_group}}"
    vnet_name: "{{env_id}}-vnet"
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{rgName}}"
      allocation_method: Dynamic
      name: "{{inventory_hostname}}-pip"
  - name: Create virtual network inteface card - FE
    azure_rm_networkinterface:
      resource_group: "{{rgName}}"
      name: "{{inventory_hostname}}-nic-fe"
      virtual_network:
        name: "{{env_id}}-vnet"
        resource_group: "{{env_id}}-rg-{{vnet_rg}}"
      subnet: "{{env_id}}-subnet-fe"
      security_group: "{{env_id}}-nsg-fe"
      ip_configurations:
        - name: ipconfig1
          private_ip_allocation_method: Static
          private_ip_address: "{{ansible_ssh_host}}"
          public_ip_address_name: "{{inventory_hostname}}-pip"
          primary: true
  - name: Create virtual network inteface card - BE
    azure_rm_networkinterface:
      resource_group: "{{rgName}}"
      name: "{{inventory_hostname}}-nic-be"
      virtual_network:
        name: "{{env_id}}-vnet"
        resource_group: "{{env_id}}-rg-{{vnet_rg}}"
      subnet: "{{env_id}}-subnet-be"
      security_group: "{{env_id}}-nsg-be"
      ip_configurations:
        - name: ipconfig1
          private_ip_allocation_method: Static
          private_ip_address: "{{secondary_ip}}"
```

Full solution on git: https://github.com/the1bit/azansible/tree/multi_nic_vm/201_multi_nic_vm

##### EXPECTED RESULTS
Required result: NICs are created

##### ACTUAL RESULTS
```
The full traceback is:
  File "/tmp/ansible__YO0XX/ansible_module_azure_rm_networkinterface.py", line 443, in exec_module
    nic = self.network_client.network_interfaces.get(self.resource_group, self.name)
  File "/usr/lib/python2.7/site-packages/azure/mgmt/network/v2017_06_01/operations/network_interfaces_operations.py", line 171, in get
    raise exp

fatal: [the1bit-cust-01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "ad_user": null,
            "api_profile": "latest",
            "append_tags": true,
            "auth_source": null,
            "cert_validation_mode": null,
            "client_id": null,
            "cloud_environment": null,
            "ip_configurations": [
                {
                    "name": "ipconfig1",
                    "primary": true,
                    "private_ip_address": "79.0.0.11",
                    "private_ip_allocation_method": "Static",
                    "public_ip_address_name": "the1bit-cust-01-pip",
                    "public_ip_allocation_method": "Dynamic"
                }
            ],
            "location": null,
            "name": "the1bit-cust-01-nic-fe",
            "open_ports": null,
            "os_type": "Linux",
            "password": null,
            "private_ip_address": null,
            "private_ip_allocation_method": "Dynamic",
            "profile": null,
            "public_ip": true,
            "public_ip_address_name": null,
            "public_ip_allocation_method": "Dynamic",
            "resource_group": "the1bit-rg-custom",
            "secret": null,
            "security_group": "the1bit-nsg-fe",
            "security_group_name": "the1bit-nsg-fe",
            "state": "present",
            "subnet": "the1bit-subnet-fe",
            "subnet_name": "the1bit-subnet-fe",
            "subscription_id": null,
            "tags": null,
            "tenant": null,
            "virtual_network": {
                "name": "the1bit-vnet",
                "resource_group": "the1bit-rg-shared"
            },
            "virtual_network_name": "{'name': 'the1bit-vnet', 'resource_group': 'the1bit-rg-shared'}"
        }
    },
    "msg": "subnet the1bit-subnet-fe is not exist"
```
