### ISSUE TITLE
use vmware_guest_file_operation module to copy localhost file to VM without network, the copy doesn't work.

### ISSUE THREAD

**Issue by judyQD** [ansible/ansible#41721]
##### SUMMARY

Use vmware_guest_file_operation module to copy localhost file to VM without network, with error: 
initiateFileTransferToGuest : problem during file transfer"
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest_file_operation

##### ANSIBLE VERSION

```
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = root
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Workstation release 6.5 (Santiago)------running ansible from
vSphere vCenter: 6.5
##### STEPS TO REPRODUCE

Want to copy file to vm (judytestvm1) in vsphere vcenter(10.9.242.11). 
There is a local file (/root/judy/judy_vcenter/a.txt) in ansible running host.

```yaml
---
- name: Copy file to VM for network configuration
  hosts: localhost
  tasks:
  - name: copy network config file to VM
    vmware_guest_file_operation:
      hostname: 10.9.242.11
      username: administrator@vsphere.local
      password: passw0rd
      datacenter: Datacenter
      validate_certs: no
      vm_id: judytestvm1
      vm_username: root
      vm_password: r00t
      copy:
        src: "/root/judy/judy_vcenter/a.txt"
        dest: "/root/a.txt"
        overwrite: True
    delegate_to: localhost
    register: facts

```

##### EXPECTED RESULTS

a.txt can be copied to the VM even if there is a file a.txt in VM, the file will be overwritten.
##### ACTUAL RESULTS

```
TASK [copy network config file to VM] ******************************************************************************************************
task path: /root/judy/judy_vcenter/file2vm.yml:5
Using module file /usr/lib/python2.6/site-packages/ansible/modules/cloud/vmware/vmware_guest_file_operation.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~ && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1529489357.52-163968408326333 `" && echo ansible-tmp-1529489357.52-163968408326333="` echo /root/.ansible/tmp/ansible-tmp-1529489357.52-163968408326333 `" ) && sleep 0'
<localhost> PUT /root/.ansible/tmp/ansible-local-1171Qn0_bR/tmp2AWkEb TO /root/.ansible/tmp/ansible-tmp-1529489357.52-163968408326333/vmware_guest_file_operation.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1529489357.52-163968408326333/ /root/.ansible/tmp/ansible-tmp-1529489357.52-163968408326333/vmware_guest_file_operation.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1529489357.52-163968408326333/vmware_guest_file_operation.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1529489357.52-163968408326333/ > /dev/null 2>&1 && sleep 0'
fatal: [127.0.0.1 -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "cluster": null, 
            "copy": {
                "dest": "/root/a.txt", 
                "overwrite": true, 
                "src": "/root/judy/judy_vcenter/a.txt"
            }, 
            "datacenter": "Datacenter", 
            "directory": null, 
            "fetch": null, 
            "folder": null, 
            "hostname": "10.9.242.11", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "username": "administrator@vsphere.local", 
            "validate_certs": false, 
            "vm_id": "judytestvm1", 
            "vm_id_type": "vm_name", 
            "vm_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "vm_username": "root"
        }
    }, 
    "msg": "initiateFileTransferToGuest : problem during file transfer", 
    "uuid": "420f7139-1da5-8618-5506-4f78e55e4a2c"
}
	to retry, use: --limit @/root/judy/judy_vcenter/file2vm.retry

PLAY RECAP *********************************************************************************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1 
```
