### ISSUE TITLE
win_chocolatey doesnt always return documented return attributes

### ISSUE THREAD

**Issue by trondhindenes** [ansible/ansible#41758]
##### SUMMARY
win_chocolatey doesnt always return documented return attributes

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
win_chocolatey

##### ANSIBLE VERSION
```
2.5.2
```

##### OS / ENVIRONMENT
Ubuntu 18.04 control node / Windows 2016 target node

##### STEPS TO REPRODUCE
```yaml
- name: Install netfx-4.7.1-devpack
  win_chocolatey:
    name: netfx-4.7.1-devpack
  notify: restart_build_agent
  register: net471devpack_exit_code
  failed_when: net471devpack_exit_code.rc != 0 and net471devpack_exit_code.rc !=-1073741819

#will fail on second run
- name: Install netfx-4.7.1-devpack
  win_chocolatey:
    name: netfx-4.7.1-devpack
  notify: restart_build_agent
  register: net471devpack_exit_code
  failed_when: net471devpack_exit_code.rc != 0 and net471devpack_exit_code.rc !=-1073741819
```

##### EXPECTED RESULTS
Neither task should fail

##### ACTUAL RESULTS
The second task fails, since the return object doesn't have the (documented) "rc" attribute. It looks like this is only returned if chocolatey made an install. This makes it unnecessarily hard to implement logic for checking exit codes in an idempodent way. Imho I need to be able to trust that the documented output aligns with reality.
