### ISSUE TITLE
Ansible cannot find boto3/botocore python modules even if they are installed

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#41776]
##### SUMMARY
Trying to run `aws_s3` module but keeps failing saying that boto3/botocore are required, while `pip` lists them as installed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
aws_s3

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pkara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

(no output)

##### OS / ENVIRONMENT

```
$ uname -a
Linux awx 4.13.0-43-generic #48~16.04.1-Ubuntu SMP Thu May 17 12:56:46 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

##### STEPS TO REPRODUCE

```yaml
  - name: Fetch dump file from S3
    aws_s3:
      bucket: mybucket
      object: somedump.sql
      dest: /tmp/somedump.sql
      mode: get
    delegate_to: "{{ ec2_instance_ip }}"
```

The target machine is `ubuntu/xenial` so I have also taken care of installing `python-minimal` (given that out of the box the machine only had `python3`)

Therefore, on the target machine:

    $(which python) --version
    Python 2.7.12

I have run the above play with and without appending:

      vars:
        ansible_python_interpreter: /usr/bin/python3

at the end of the task...

##### EXPECTED RESULTS

Fetch file from s3 bucket

##### ACTUAL RESULTS

> fatal: [localhost -> 22.33.111.88]: FAILED! => {"changed": false, "msg": "boto3 and botocore required for this module"}]

__BUT__:

```
 $ ssh ubuntu@22.33.111.88
 
 $ pip freeze
 boto3==1.7.41
 botocore==1.10.41
 
 $ pip3 freeze
 blinker==1.3
 boto3==1.7.41
 botocore==1.10.41
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/aws_s3.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/aws_s3.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @lwade @s-hertel
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by pkaramol** [comment]
The problem goes away if I __explicitly__ run before the above task the following:

```
- name: Ensure boto and boto3 modules are installed
  pip:
    name: "{{ item }}"
  with_items:
    - boto3
    - botocore
  delegate_to: "{{ ec2_instance_ip }}"
```

which __ALWAYS__ comes out __changed__.


Is ansible creating a virtualenv to run the task which is afterwards destroyed so I explicitly need to add my dependencies each time?
