### ISSUE TITLE
[vmware_guest] Connecting the network may fail if portgroup name is not unique in the datacenter

### ISSUE THREAD

**Issue by wouterhummelink** [ansible/ansible#41781]
##### SUMMARY
For a customer I work with a VMware environment where each Datacenter in VCenter has several dvSwitches that each contain portgroups with identical names. From a vwmare perspective that's completely fine. However the vmware_guest module doesn't account for the cluster the VM is being deployed to, and ansible tries to assign the first portgroup found through the api, which in turn results in a disconnected machine since the vSwitch assigned is not connected to the host the vm is on.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
vmware_guest

##### ANSIBLE VERSION

```
ansible 2.6.0rc3
  config file = /home/packer/ansible-vcenter/ansible.cfg
  configured module search path = [u'/home/packer/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/packer/.local/lib/python2.7/site-packages/ansible
  executable location = /home/packer/.local/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### STEPS TO REPRODUCE

1. Have a vmware datacenter that has several vSwitches where whichever one the python api returns first is not connected to the cluster being deployed to. (Order is deterministic)
2. Execute task below
3. Wait for the vm to deploy

```yaml
  - name: create a vm
    vmware_guest:
      datacenter: "{{ vmware_datacenter }}"
      folder: "{{ folder }}"
      cluster: "{{ cluster }}"
      #customization:
        #  hostname: "{{ inventory_hostname }}"
        #dns_servers: ["10.255.254.1","10.255.254.3"]
        #domain: "{{ dns_domain }}"
      disk: "{{ disks }}"
      hardware:
        num_cpus: 1
        memory_mb: 1024
        scsi: paravirtual
      hostname: "{{ vcenter }}"
      linked_clone: yes
      snapshot_src: IMAGE
      name: "{{ inventory_hostname }}"
      networks:
        - name: "{{ network }}"
          macaddress: "{{ mac_address }}"
          type: dhcp
      state: poweredon
      template: "{{ basevm }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      wait_for_ip_address: yes
    delegate_to: localhost

  - name: Gather information from VMware
    vmware_guest_facts:
      name: "{{ inventory_hostname }}"
      datacenter: "{{ vmware_datacenter }}"
      folder: "{{ folder }}"
      username: "{{ vcenter_username }}"
      hostname: "{{ vcenter }}"
      password: "{{ vcenter_password }}"
      validate_certs: false
    register: new_vm
    delegate_to: localhost

  - name: set the ssh ip address
    set_fact:
      ansible_host: "{{ new_vm.instance.ipv4 }}"
    delegate_to: localhost

  - name: gather facts
    setup:
```

##### EXPECTED RESULTS

The setup task for the new VM succeeds after getting the ip address for the host

##### ACTUAL RESULTS

Infrastructure details have been replaced for security.

```
TASK [create a vm] **************************************************************************************************************************************************************************************************************
task path: /home/packer/ansible-vcenter/playbook.yml:36
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: packer
<localhost> EXEC /bin/sh -c 'echo ~packer && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/packer/.ansible/tmp/ansible-tmp-1529570226.23-75173623544667 `" && echo ansible-tmp-1529570226.23-75173623544667="` echo /home/packer/.ansible/tmp/ansible-tmp-1529570226.23-75173623544667 `" ) && sleep 0'
Using module file /home/packer/.local/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest.py
<localhost> PUT /home/packer/.ansible/tmp/ansible-local-1681l8YQEs/tmpxxE_g0 TO /home/packer/.ansible/tmp/ansible-tmp-1529570226.23-75173623544667/vmware_guest.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/packer/.ansible/tmp/ansible-tmp-1529570226.23-75173623544667/ /home/packer/.ansible/tmp/ansible-tmp-1529570226.23-75173623544667/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/packer/.ansible/tmp/ansible-tmp-1529570226.23-75173623544667/vmware_guest.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/packer/.ansible/tmp/ansible-tmp-1529570226.23-75173623544667/ > /dev/null 2>&1 && sleep 0'
changed: [vmwarehost4 -> localhost] => {
    "changed": true,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "10282",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "datastore1"
        ],
        "hw_esxi_host": "exs1.vmware.internal",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": [],
            "label": "Network adapter 1",
            "macaddress": "00:50:56:9a:d1:2b",
            "macaddress_dash": "00-50-56-9a-d1-2b",
            "portgroup_key": null,
            "portgroup_portkey": null,
            "summary": "DVSwitch: 50 1a 0a 86 7f cc fa 27-52 41 44 3c f9 33 e5 7a"
        },
        "hw_files": [
            "[datastore1] vmwarehost4/vmwarehost4.vmx",
            "[datastore1] vmwarehost4/vmwarehost4.nvram",
            "[datastore1] vmwarehost4/vmwarehost4.vmsd",
            "[datastore1] basevm4/basevm4.vmdk",
            "[datastore1] vmwarehost4/vmwarehost4.vmdk"
        ],
        "hw_folder": "/Datacenter-West/vm/Servers",
        "hw_guest_full_name": "Red Hat Enterprise Linux 7 (64-bit)",
        "hw_guest_ha_state": null,
        "hw_guest_id": "rhel7_64Guest",
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 1024,
        "hw_name": "vmwarehost4",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 1,
        "hw_product_uuid": "421a6cce-f7ba-a672-133f-3ce32db9ee48",
        "hw_version": "vmx-10",
        "instance_uuid": "501ac4ad-11dd-ffdb-6343-9d75c4439611",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "annotation": null,
            "cdrom": {},
            "cluster": "cluster1",
            "customization": {},
            "customization_spec": null,
            "customvalues": [],
            "datacenter": "Datacenter-West",
            "disk": [
                {
                    "datastore": "datastore1",
                    "size_gb": 40,
                    "type": "thin"
                }
            ],
            "esxi_hostname": null,
            "folder": "Servers",
            "force": false,
            "guest_id": null,
            "hardware": {
                "memory_mb": 1024,
                "num_cpus": 1,
                "scsi": "paravirtual"
            },
            "hostname": "vcenter1.iaas.internal",
            "is_template": false,
            "linked_clone": true,
            "name": "vmwarehost4",
            "name_match": "first",
            "networks": [
                {
                    "macaddress": null,
                    "name": "vlan-207",
                    "type": "dhcp"
                }
            ],
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "resource_pool": null,
            "snapshot_src": "IMAGE",
            "state": "poweredon",
            "state_change_timeout": 0,
            "template": "basevm4",
            "username": "AD\\deployuser",
            "uuid": null,
            "validate_certs": true,
            "vapp_properties": [],
            "wait_for_ip_address": true
        }
    }
}

TASK [Gather information from VMware] *******************************************************************************************************************************************************************************************
task path: /home/packer/ansible-vcenter/playbook.yml:65
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: packer
<localhost> EXEC /bin/sh -c 'echo ~packer && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/packer/.ansible/tmp/ansible-tmp-1529570887.53-176468566977326 `" && echo ansible-tmp-1529570887.53-176468566977326="` echo /home/packer/.ansible/tmp/ansible-tmp-1529570887.53-176468566977326 `" ) && sleep 0'
Using module file /home/packer/.local/lib/python2.7/site-packages/ansible/modules/cloud/vmware/vmware_guest_facts.py
<localhost> PUT /home/packer/.ansible/tmp/ansible-local-1681l8YQEs/tmpQIkERm TO /home/packer/.ansible/tmp/ansible-tmp-1529570887.53-176468566977326/vmware_guest_facts.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/packer/.ansible/tmp/ansible-tmp-1529570887.53-176468566977326/ /home/packer/.ansible/tmp/ansible-tmp-1529570887.53-176468566977326/vmware_guest_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python2 /home/packer/.ansible/tmp/ansible-tmp-1529570887.53-176468566977326/vmware_guest_facts.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/packer/.ansible/tmp/ansible-tmp-1529570887.53-176468566977326/ > /dev/null 2>&1 && sleep 0'
ok: [vmwarehost4 -> localhost] => {
    "changed": false,
    "instance": {
        "annotation": "",
        "current_snapshot": null,
        "customvalues": {},
        "guest_consolidation_needed": false,
        "guest_question": null,
        "guest_tools_status": "guestToolsRunning",
        "guest_tools_version": "10282",
        "hw_cores_per_socket": 1,
        "hw_datastores": [
            "datastore1"
        ],
        "hw_esxi_host": "exs1.vmware.internal",
        "hw_eth0": {
            "addresstype": "assigned",
            "ipaddresses": [],
            "label": "Network adapter 1",
            "macaddress": "00:50:56:9a:d1:2b",
            "macaddress_dash": "00-50-56-9a-d1-2b",
            "portgroup_key": null,
            "portgroup_portkey": null,
            "summary": "DVSwitch: 50 1a 0a 86 7f cc fa 27-52 41 44 3c f9 33 e5 7a"
        },
        "hw_files": [
            "[datastore1] vmwarehost4/vmwarehost4.vmx",
            "[datastore1] vmwarehost4/vmwarehost4.nvram",
            "[datastore1] vmwarehost4/vmwarehost4.vmsd",
            "[datastore1] basevm4/basevm4.vmdk",
            "[datastore1] vmwarehost4/vmwarehost4.vmdk"
        ],
        "hw_folder": "/Datacenter-West/vm/Servers",
        "hw_guest_full_name": "Red Hat Enterprise Linux 7 (64-bit)",
        "hw_guest_ha_state": null,
        "hw_guest_id": "rhel7_64Guest",
        "hw_interfaces": [
            "eth0"
        ],
        "hw_is_template": false,
        "hw_memtotal_mb": 1024,
        "hw_name": "vmwarehost4",
        "hw_power_status": "poweredOn",
        "hw_processor_count": 1,
        "hw_product_uuid": "421a6cce-f7ba-a672-133f-3ce32db9ee48",
        "hw_version": "vmx-10",
        "instance_uuid": "501ac4ad-11dd-ffdb-6343-9d75c4439611",
        "ipv4": null,
        "ipv6": null,
        "module_hw": true,
        "snapshots": []
    },
    "invocation": {
        "module_args": {
            "datacenter": "Datacenter-West",
            "folder": "Servers",
            "hostname": "vcenter1.iaas.internal",
            "name": "vmwarehost4",
            "name_match": "first",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "username": "AD\\deployuser",
            "uuid": null,
            "validate_certs": false
        }
    }
}

TASK [set the ssh ip address] ***************************************************************************************************************************************************************************************************
task path: /home/packer/ansible-vcenter/playbook.yml:77
ok: [vmwarehost4 -> localhost] => {
    "ansible_facts": {
        "ansible_host": ""
    },
    "changed": false
}

TASK [gather facts] *************************************************************************************************************************************************************************************************************
task path: /home/packer/ansible-vcenter/playbook.yml:82
<vmwarehost4> ESTABLISH SSH CONNECTION FOR USER: packer
<vmwarehost4> SSH: EXEC sshpass -d12 ssh -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o User=packer -o ConnectTimeout=10 -o ControlPath=/home/packer/.ansible/cp/aa3b22f2e6 vmwarehost4 '/bin/sh -c '"'"'echo ~packer && sleep 0'"'"''
<vmwarehost4> (255, '', 'OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket "/home/packer/.ansible/cp/aa3b22f2e6" does not exist\r\ndebug2: resolving "vmwarehost4" port 22\r\nssh: Could not resolve hostname vmwarehost4: Name or service not known\r\n')
fatal: [vmwarehost4]: UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.4p1, OpenSSL 1.0.2k-fips  26 Jan 2017\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 58: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/packer/.ansible/cp/aa3b22f2e6\" does not exist\r\ndebug2: resolving \"vmwarehost4\" port 22\r\nssh: Could not resolve hostname vmwarehost4: Name or service not known\r\n",
    "unreachable": true
}

```
