### ISSUE TITLE
service module doesn't work fully with CentOS 6

### ISSUE THREAD

**Issue by Alucard616** [ansible/ansible#41785]
##### SUMMARY
When using the "service" module on a CentOS 6 System, using the "enabled" Parameter doesn't work properly.
It always shows, that something is changed, even though nothing happened.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
service

##### ANSIBLE VERSION
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pthyen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 15 2018, 15:37:31) [GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]

##### OS / ENVIRONMENT
Ansible installed on Fedora 27

##### STEPS TO REPRODUCE
```
- name: Stoppping & Disabling Firewall Service
    service:
      state: stopped
      enabled: no
      name: ntpd
```

##### EXPECTED RESULTS
ntpd is stopped and disabled

##### ACTUAL RESULTS
ntpd is stopped, but and enabled, but it always says "changed"

```
...
TASK [base_config : Stoppping & Disabling ntpd Service] *******************************************************************************************************************************************************
changed: [x.x.x.x]

PLAY RECAP ********************************************************************************************************************************************************************************************************
x.x.x.x               : ok=2    changed=1    unreachable=0    failed=0
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/service.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/service.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by sivel** [comment]
I cannot duplicate this issue.  My reproducer:

```
- hosts: all
  become: true
  tasks:
    - debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"
    - yum:
        name: ntp
    - service:
        enabled: yes
        name: ntpd
    - service:
        state: stopped
        enabled: no
        name: ntpd
    - service:
        state: stopped
        enabled: no
        name: ntpd
```

This installs ntp, enables it, and then disables it 2 times:

```
TASK [debug] *********************************************************************************************************
ok: [172.16.0.122] => {
    "msg": "CentOS 6.9"
}

TASK [yum] ***********************************************************************************************************
ok: [172.16.0.122] => {"changed": false, "msg": "", "rc": 0, "results": ["ntp-4.2.6p5-12.el6.centos.2.x86_64 providing ntp is already installed"]}

TASK [service] *******************************************************************************************************
ok: [172.16.0.122] => {"changed": false, "enabled": true, "name": "ntpd"}

TASK [service] *******************************************************************************************************
changed: [172.16.0.122] => {"changed": true, "enabled": false, "name": "ntpd", "state": "stopped"}

TASK [service] *******************************************************************************************************
ok: [172.16.0.122] => {"changed": false, "enabled": false, "name": "ntpd", "state": "stopped"}
```

The 2nd task to disable it reports `ok`, and not `changed`.

**Comment by samdoran** [comment]
I am also not able to duplicate this issue.

Playbook:
```yaml

- hosts: "{{ target_hosts | default('lab-centos6') }}"
  become: yes

  tasks:
    - debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }}"

    - debug:
        msg: "{{ ansible_version.full }}"


    # --- Test 1 --- #
    - name: Start and enable ntpd
      service:
        name: ntpd
        state: started
        enabled: yes

    - name: Start and disable ntpd
      service:
        name: ntpd
        state: started
        enabled: no

    - name: Again
      service:
        name: ntpd
        state: started
        enabled: no

    # --- Test2  --- #
    - name: Start and enable ntpd
      service:
        name: ntpd
        state: started
        enabled: yes

    - name: Disable ntpd
      service:
        name: ntpd
        enabled: no

    - name: Again
      service:
        name: ntpd
        enabled: no
```

Output:
```
> ansible-playbook test.yml  -v
Using /Users/sdoran/Projects/Vagrant/Ansible Lab/ansible.cfg as config file

PLAY [lab-centos6] **********************************************************************************

TASK [debug] ****************************************************************************************
ok: [lab-centos6] => {
    "msg": "CentOS 6.9"
}

TASK [debug] ****************************************************************************************
ok: [lab-centos6] => {
    "msg": "2.5.2"
}

TASK [Start and enable ntpd] ************************************************************************
changed: [lab-centos6] => {"changed": true, "enabled": true, "name": "ntpd", "state": "started"}

TASK [Start and disable ntpd] ***********************************************************************
changed: [lab-centos6] => {"changed": true, "enabled": false, "name": "ntpd", "state": "started"}

TASK [Again] ****************************************************************************************
ok: [lab-centos6] => {"changed": false, "enabled": false, "name": "ntpd", "state": "started"}

TASK [Start and enable ntpd] ************************************************************************
changed: [lab-centos6] => {"changed": true, "enabled": true, "name": "ntpd", "state": "started"}

TASK [Disable ntpd] *********************************************************************************
changed: [lab-centos6] => {"changed": true, "enabled": false, "name": "ntpd"}

TASK [Again] ****************************************************************************************
ok: [lab-centos6] => {"changed": false, "enabled": false, "name": "ntpd"}

PLAY RECAP ******************************************************************************************
lab-centos6                : ok=8    changed=4    unreachable=0    failed=0
```

Both "Again" tasks report `ok`.

needs_info
