### ISSUE TITLE
win_uri: fails to return json

### ISSUE THREAD

**Issue by svpudik** [ansible/ansible#41797]
##### SUMMARY
I am using win_uri to call rest API from more sources. I found that when response header contains 
Content-Type →application/json
parse result as json is not problem
but when response header contains 
Content-Type →application/json; charset=utf-8
I cannot use json but only content.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`win_uri.py`

##### ANSIBLE VERSION

```
ansible 2.5.3

```

##### OS / ENVIRONMENT

centOS
##### STEPS TO REPRODUCE

```yaml

- name: get state {{ ansible_host }}
  win_uri:
    url: "http://{{ res_api_name }}:8091/pools/nodes"
    method: GET
    user: "{{ couch_user }}"
    password: "{{ couch_pwd }}"
    force_basic_auth: yes
    status_code: 200,404
    content_type: application/json
    return_content: yes
    timeout: 10
  register: result_rebalance
  when:
    - "'couch' in group_names"
  until: result_rebalance.json.rebalanceStatus == "none"
  retries: 40
  delay: 30
```

##### ACTUAL RESULTS

```

```
