### ISSUE TITLE
win_package parameter "creates_version" checks "product version" and not "file version"

### ISSUE THREAD

**Issue by Yvan-Masson** [ansible/ansible#41799]
##### SUMMARY

win_package documentation states that `creates_version` checks for "file version" but this seems false or incomplete: in the following case, the check is done on "product version" attribute of the file.

##### ISSUE TYPE

 - Documentation Report

##### COMPONENT NAME

win_package

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/yvan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 05:55:50) [GCC 7.3.0]
```

##### OS / ENVIRONMENT

Ansible runs from Debian testing, target is Windows 7 Pro 64 bits.

##### STEPS TO REPRODUCE

Run a simple task that install Firefox ESR: after installation, showing details of the exe shows that `file version` is 60.0.2 and `product version` is 60.0.2.6730.

```yaml
- name: install or update Firefox-ESR 64 bits
  win_package:
    creates_path: "{{ ansible_env.ProgramFiles }}\\Mozilla Firefox\\firefox.exe"
    creates_version: "60.0.2.6730"
    path: "\\\\some\\share\\FirefoxESR\\Firefox Setup 60.0.2esr x64.exe"
    arguments: /S
```

##### EXPECTED RESULTS

Task should run only once.

##### ACTUAL RESULTS

Check is false so task run each time. However, if you check against `product version` (i.e. 60.0.2), the check succeeds. I could not find a fix about this issue in lasts changelog, so I suppose this is an issue in the documentation.

```

```
Best regards,
Yvan
