### ISSUE TITLE
Oynx Network module fail on Aggregate-Interface Speed Set (10G)

### ISSUE THREAD

**Issue by rhastie** [ansible/ansible#41800]
##### SUMMARY
Using Mellanox Oynx 3.6.7936 and Ansible 2.5.0 I get the following error when setting Aggregate/Interface Speed.

Specifically:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: TypeError: expected string or buffer
fatal: [SN2010-0]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_3mUx6f/ansible_module_onyx_interface.py\", line 486, in <module>\n    main()\n  File \"/tmp/ansible_3mUx6f/ansible_module_onyx_interface.py\", line 482, in main\n    OnyxInterfaceModule.main()\n  File \"/tmp/ansible_3mUx6f/ansible_modlib.zip/ansible/module_utils/network/onyx/onyx.py\", line 229, in main\n  File \"/tmp/ansible_3mUx6f/ansible_modlib.zip/ansible/module_utils/network/onyx/onyx.py\", line 207, in run\n  File \"/tmp/ansible_3mUx6f/ansible_module_onyx_interface.py\", line 345, in load_current_config\n    self._current_config[name] = self._create_if_data(name, item)\n  File \"/tmp/ansible_3mUx6f/ansible_module_onyx_interface.py\", line 322, in _create_if_data\n    match = regex.match(name)\nTypeError: expected string or buffer\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
onyx_interface.py

##### ANSIBLE VERSION
2.5.0

##### OS / ENVIRONMENT
Ubuntu

##### STEPS TO REPRODUCE

```yaml
- name: Configure Switch Interfaces to 10G
  onyx_interface:
      aggregate:
        - name: Eth1/1
        - name: Eth1/2
        - name: Eth1/3
        - name: Eth1/4
        - name: Eth1/5
        - name: Eth1/6
        - name: Eth1/7
        - name: Eth1/8
        - name: Eth1/9
        - name: Eth1/10
        - name: Eth1/11
        - name: Eth1/11
        - name: Eth1/12
        - name: Eth1/13
        - name: Eth1/14
        - name: Eth1/15
        - name: Eth1/16
        - name: Eth1/17
        - name: Eth1/18
      description: Module-Test-Interface
      speed: 10G
```

##### ACTUAL RESULTS

```

```
