### ISSUE TITLE
sudo: false at task level does not override sudo: true at play level

### ISSUE THREAD

**Issue by jsdalton** [ansible/ansible#4181]
I have a play which includes some roles etc. and sets sudo to true.

Within that play I have some pre_tasks and post_tasks that delegate to localhost, which I do not want to be executed via sudo. So I set sudo to false there.

When I run the play the tasks delegated to 127.0.0.1 obey the sudo setting of the play, not the task. (I get a sudo error because my local account is not set up with passwordless access). I can't override that setting on a per task basis.

Here's a look at the play where this is happening:

``` yaml
- hosts: py-webservers
  pre_tasks:
    - name: Gathering ec2 facts
      ec2_facts:
      tags:
        - aws
        - elb
    - name: Deregister instance from elb
      ec2_elb_instance: aws_access_key={{ aws.access_key_id }}
                        aws_secret_key={{ aws.secret_access_key }}
                        region={{ aws.region }}
                        instance_id={{ ansible_ec2_instance_id }}
                        ec2_elbs={{ ec2_elbs_name }}
                        state=absent
      delegate_to: 127.0.0.1
      sudo: no
      tags:
        - elb
  roles:
    - common
    - python-webserver
  post_tasks:
    - name: Register instance from elb
      ec2_elb_instance: aws_access_key={{ aws.access_key_id }}
                        aws_secret_key={{ aws.secret_access_key }}
                        region={{ aws.region }}
                        instance_id={{ ansible_ec2_instance_id }}
                        ec2_elbs={{ ec2_elbs_name }}
                        state=present
      delegate_to: 127.0.0.1
      sudo: no
      tags:
        - elb
  sudo: yes
  accelerate: true
```

The [ansible docs](http://www.ansibleworks.com/docs/playbooks.html#hosts-and-users) say "You can also use sudo on a particular task instead of the whole play," so I would assume the inverse would be true -- that you could _not_ use sudo on a particular task (or if that's not yet the case then it's a feature that makes sense to add).

I added the full play in case the funkiness is due to using delegate_to, pre/post_tasks, or some combination thereof.
