### ISSUE TITLE
[Docs] No instructions on how to generate crypted password for user module

### ISSUE THREAD

**Issue by jerrac** [ansible/ansible#4182]
http://www.ansibleworks.com/docs/modules.html#user mentions looking at the example playbook, but I didn't do that at first. I assumed that it meant to copy the password out of /etc/shadow. Not sure that makes sense to me now, but it did back then. 

It'd be better if the docs page told us how we're supposed to generate the crypted password.

**Comment by bcoca** [comment]
I use one of 2 methods,  with: openssl passwd -salt <salt> -1 <pass>
 or: mkpasswd <pass> -salt <salt> -m sha-512

**Comment by jerrac** [comment]
Would modifying the description to look something like:

> Optionally set the user's password to this crypted value.  See the user example in the github examples directory for what this looks like in a playbook. 
> 
> Examples of how to generate a crypted password include:
> $ python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
> $ openssl passwd -salt <salt> -1 <pass>
> $ mkpasswd <pass> -salt <salt> -m sha-512

Be appropriate for the docs?

How would I modify this:
file: library/system/user line: 75-80

``` yaml
    password:
        required: false
        description:
            - Optionally set the user's password to this crypted value.  See
              the user example in the github examples directory for what this looks
              like in a playbook.
```

to include the line breaks?
