### ISSUE TITLE
package: list reverse dependencies in check-mode

### ISSUE THREAD

**Issue by jamessemai** [ansible/ansible#41835]
##### SUMMARY
We'd like the `package` module to return the list of reverse dependencies when run in `check-mode`.

Context:
We have several playbooks where we remove packages using the `package` module, but where we have also built-in a "rollback' functionality to re-install the removed package if things go wrong.

This works well, except when there are reverse dependencies on the removed package (i.e. other packages depend on the removed package). In that case, the reverse dependencies will be removed when removing the package, but these will not be restored when re-installing the removed package.

Ideally, we'd like to be able to run the package removal using the `package` module in `check-mode`, check whether there are any reverse dependencies, and if not, go ahead with the package removal.

Currently the `package` module does not provide this information when run in `check-mode`, forcing us to do this check using raw commands instead.

##### ISSUE TYPE
Have the `package` module return a list of reverse dependencies when run in `check-mode`.

##### COMPONENT NAME
package

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.3
  config file = /home_local/ansible/automation/ansible.cfg
  configured module search path = [u'/home_local/ansible/automation/library']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### EXAMPLE USE CASE

```yaml
    - name: Test package removal
      package:
        name: "package_name"
        state: absent
      check_mode: yes      
      register: package_out

    - name: Remove package if no reverse dependencies
      package:
        name: "package_name"
        state: absent
      when: (package_out.changes.rdependencies | length) == 0
```

##### EXPECTED RESULTS
Package `package_name` is removed only if it has no reverse dependencies.

##### ACTUAL RESULTS
Currently the reverse dependencies information is not passed on in check-mode, so the above will not work.
