### ISSUE TITLE
k8s_raw - TypeError: __init__() got an unexpected keyword argument 'configMapRef'

### ISSUE THREAD

**Issue by willievu** [ansible/ansible#41831]
##### SUMMARY

When deploy for the first time, no errors occur.  However, when the same yaml content is applied again, k8s_raw tries to do comparison of an existing Deployment which has configMapRef, it causes the following error:
```
failed: [control-server] (item=/playbook-root/roles/osm-wls-admin/templates/wls-admin.yml.j2) => {
    "changed": false,
    "item": "/playbook-root/roles/osm-wls-admin/templates/wls-admin.yml.j2",
    "module_stderr": "Shared connection to xxx.xxx.xxx.xxx closed.\r\n",
    "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_uOsmOW/ansible_module_k8s_raw.py\", line 163, in <module>\r\n    main()\r\n  File \"/tmp/ansible_uOsmOW/ansible_module_k8s_raw.py\", line 159, in main\r\n    KubernetesRawModule().execute_module()\r\n  File \"/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 142, in execute_module\r\n  File \"/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py\", line 136, in object_from_params\r\n  File \"/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py\", line 301, in __set_obj_attribute\r\n  File \"/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py\", line 301, in __set_obj_attribute\r\n  File \"/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py\", line 301, in __set_obj_attribute\r\n  File \"/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py\", line 293, in __set_obj_attribute\r\n  File \"/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py\", line 432, in __compare_obj_list\r\n  File \"/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py\", line 483, in __compare_obj_list\r\nTypeError: __init__() got an unexpected keyword argument 'configMapRef'\r\n",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

```
Traceback (most recent call last):
  File "/tmp/ansible_uOsmOW/ansible_module_k8s_raw.py", line 163, in <module>
    main()
  File "/tmp/ansible_uOsmOW/ansible_module_k8s_raw.py", line 159, in main
    KubernetesRawModule().execute_module()
  File "/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/raw.py", line 142, in execute_module
  File "/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py", line 136, in object_from_params
  File "/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py", line 301, in __set_obj_attribute
  File "/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py", line 301, in __set_obj_attribute
  File "/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py", line 301, in __set_obj_attribute
  File "/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py", line 293, in __set_obj_attribute
  File "/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py", line 432, in __compare_obj_list
  File "/tmp/ansible_uOsmOW/ansible_modlib.zip/ansible/module_utils/k8s/helper.py", line 483, in __compare_obj_list
TypeError: __init__() got an unexpected keyword argument 'configMapRef'
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

k8s_raw

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /playbook-root/ansible.cfg
  configured module search path = [u'/home/<user>/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May 29 2017, 20:42:36) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]

```

##### CONFIGURATION

DEFAULT_ROLES_PATH(/playbook-root/ansible.cfg) = [u'/roles-root/
(END)

##### OS / ENVIRONMENT

Oracle Enterprise Linux <hostname> 4.1.12-112.14.15.el7uek.x86_64 #2 SMP Thu Feb 8 09:58:19 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE

```yaml
  - name: Deploy/Start admin server
    k8s_raw:
      definition:
        "{{ lookup('template', '{{ item }}') | from_yaml }}"
      state: present
    with_items:
    - "{{ role_path }}/templates/wls-admin.yml.j2"
```

The actual k8s yaml content:
```yaml
apiVersion: v1 
kind: Deployment 
metadata:
  name: admin-server
  namespace: app-custom-51
spec:
  selector:
    matchLabels:
      app: admin-server # has to match .spec.template.metadata.labels
  replicas: 1
  template:
    metadata:
      labels:
        app: admin-server 
    spec:
      initContainers:
      - name: volume-mount-hack
        image: busybox
        command: ["sh", "-c", '[ "$(ls -A /u01/fmw)" ] && echo "Not empty and ignored" || chown 1000:1000 /u01/fmw' ]
        volumeMounts:
        - name: user-projects-home
          mountPath: "/u01/fmw"
          subPath: "app-custom-51"
      containers:
      - name: admin-server
        image: app-domain:latest
        command: ["sh"]
        args: ["/u01/oracle/startadmin.sh"]
        readinessProbe:
            httpGet:
              path: /weblogic/ready
              port: 8001
            initialDelaySeconds: 15
            timeoutSeconds: 5
        ports:
        - containerPort: 8001
        envFrom:
        - configMapRef:
            name: app-weblogic-config
        - configMapRef:
            name: app-config
        env:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MY_POD_DOMAIN_NAME
          value: "app-custom-51.pod.cluster.local"
        - name: WLUSER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: WLUSER
        - name: WLPASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: WLPASSWORD
        - name: DATABASE_SYS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: DATABASE_SYS_PASSWORD
        - name: RCU_SCHEMA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: RCU_SCHEMA_PASSWORD
        volumeMounts:
        - name: user-projects-home
          mountPath: "/u01/fmw"
          subPath: "app-custom-51"
        - name: wls-bootstrap-domain-config
          mountPath: /u01/wls-bootstrap-domain-config
          readOnly: true
      volumes:
      - name: user-projects-home
        hostPath:
          path: "/mnt/nfs/home/fmw/user-projects"
          type: DirectoryOrCreate
      - name: wls-bootstrap-domain-config
        configMap:
          name: wls-bootstrap-domain-config
      imagePullSecrets:
      - name: ocir-secret
```

##### EXPECTED RESULTS

k8s_raw should recognizes configMapRef and be able to do comparison properly and then decide to apply changes or not.

##### ACTUAL RESULTS

```

```
