### ISSUE TITLE
ipa_dnsrecord: add MX record

### ISSUE THREAD

**Issue by jamescassell** [ansible/ansible#41842]
##### SUMMARY

Would like to add MX records to a minimal DNS set up within an IPA domain.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

ipa_dnsrecord

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

Using default config.

##### OS / ENVIRONMENT

CentOS 7.5

##### STEPS TO REPRODUCE

```yaml
- ipa_dnsrecord:
    name: @
    zone_name: example.com
    record_type: 'MX'
    record_value: 'mx-in.example.com'
    record_priority: 10
    ipa_host: ipa.example.com
    ipa_pass: topsecret
    state: present
```

##### EXPECTED RESULTS

Capability is available

##### ACTUAL RESULTS

Capability is not available.

```

```
