### ISSUE TITLE
AWS Application Load Balancer module (elb_application_lb) update fails for Listener actions that contain anything other than 'forward'

### ISSUE THREAD

**Issue by jeevers** [ansible/ansible#41861]
##### SUMMARY

AWS recently launched a new ALB (Application Load Balancer) featured that allows authentication to be performed by the load balancer using Cognito. This authentication is configured by adding an authentication action to a listener rule. ALB resources with this new authentication feature can be sucessfully created by ansible, however subsequent runs against the resource fail.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

elb_application_lb

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /home/jevers/misc_dev/ansible_alb_test/ansible.cfg
  configured module search path = ['/home/jevers/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jevers/.local/lib/python3.6/site-packages/ansible
  executable location = /home/jevers/.local/bin/ansible
  python version = 3.6.5 (default, Mar 29 2018, 18:20:46) [GCC 8.0.1 20180317 (Red Hat 8.0.1-0.19)]
```

##### CONFIGURATION

ANSIBLE_FORCE_COLOR(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
ANSIBLE_NOCOWS(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
ANSIBLE_PIPELINING(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = -o ForwardAgent=yes -o PreferredAuthentications=keyboard-interactive,gssapi-with-mic,gssapi-keyex,hostbased,pub>
DEFAULT_FORKS(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = 100
DEFAULT_GATHERING(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = smart
DEFAULT_HOST_LIST(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = ['/home/jevers/misc_dev/ansible_alb_test/inventory']
DEFAULT_LOG_PATH(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = /home/jevers/misc_dev/ansible_alb_test/log/ansible.log
DEFAULT_MANAGED_STR(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = Ansible managed: DO NOT EDIT
DEFAULT_MODULE_NAME(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = shell
DEFAULT_REMOTE_USER(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = pi
DEFAULT_SCP_IF_SSH(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
DEFAULT_TIMEOUT(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = 15
DEPRECATION_WARNINGS(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = True
HOST_KEY_CHECKING(/home/jevers/misc_dev/ansible_alb_test/ansible.cfg) = False

##### OS / ENVIRONMENT

Running Ansible on Fedora 28 (Linux) , managing AWS resources

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
      role_account: "{{ACCTID}}"
      role_name: "{{ROLENAME}}"
      resource_state: present
      resource_prefix: alb-auth-test
      vpc_id: "{{VPC}}"
      subnets:
          - "{{SUBNET1}}"
          - "{{SUBNET2}}"
      AuthenticateCognitoConfig: 
          UserPoolArn: "{{USER_POOL_ARN}}"
          UserPoolClientId: "{{USER_POOL_APP_CLIENT_ID}}"
          UserPoolDomain: "{{USER_POOL_DOMAIN}}"
          SessionCookieName: "AWSELBAuthSessionCookie"
          Scope: "openid"
          SessionTimeout: 604800
          OnUnauthenticatedRequest: "authenticate"
  tasks:
      - name: assume role in target account
        sts_assume_role:
            role_arn: "arn:aws:iam::{{role_account}}:role/{{role_name}}"
            role_session_name: "ansible_workstation"
        register: assumed_role

      - name: create alb security group
        ec2_group:
            aws_access_key: "{{assumed_role.sts_creds.access_key}}"
            aws_secret_key: "{{assumed_role.sts_creds.secret_key}}"
            security_token: "{{assumed_role.sts_creds.session_token}}"

            name: "{{resource_prefix}}-sg"
            state: "{{resource_state}}"
            description: "security group for {{resource_prefix}}-alb"
            vpc_id: "{{vpc_id}}"
            rules:
                - proto: tcp
                  from_port: 80
                  to_port: 80
                  cidr_ip: 10.10.3.0/24
                - proto: tcp
                  from_port: 443
                  to_port: 443
                  cidr_ip: 10.10.3.0/24
        register: alb_sg

      - name: create target group
        elb_target_group:
            aws_access_key: "{{assumed_role.sts_creds.access_key}}"
            aws_secret_key: "{{assumed_role.sts_creds.secret_key}}"
            security_token: "{{assumed_role.sts_creds.session_token}}"

            name: "{{resource_prefix}}-tg"
            state: "{{resource_state}}"
            protocol: http
            port: 80
            vpc_id: "{{vpc_id}}"
        register: app_tg
          
      - name: create alb
        elb_application_lb:
            aws_access_key: "{{assumed_role.sts_creds.access_key}}"
            aws_secret_key: "{{assumed_role.sts_creds.secret_key}}"
            security_token: "{{assumed_role.sts_creds.session_token}}"

            name: "{{resource_prefix}}-alb"
            state: present

            security_groups:
                - "{{alb_sg.group_id}}"
            subnets: "{{subnets}}"
            scheme: internal
            listeners:
                - Protocol: HTTPS
                  Port: 443
                  DefaultActions:
                      - Type: forward
                        TargetGroupArn: "{{app_tg.target_group_arn }}"
                  Certificates:
                      - CertificateArn: "{{acm_cert_arn}}"
                  SslPolicy: ELBSecurityPolicy-2016-08
                  Rules:
                      - Conditions:
                          - Field: path-pattern
                            Values:
                                - "*"
                        Priority: '1'
                        Actions:
                            - Type: forward
                              TargetGroupArn: "{{app_tg.target_group_arn }}"
                              Order: 2
                            - Type: authenticate-cognito
                              AuthenticateCognitoConfig: "{{AuthenticateCognitoConfig}}"
                              Order: 1
```

##### EXPECTED RESULTS

1. On the first playbook run, the resource is created
2. the Playbook can be run against the new ALB resource without failure

##### ACTUAL RESULTS

The first Playbook runs sucessfully, and the ALB resource is created.
The playbook is run Again and the 'create alb' task fails with a 'KeyError: 'TargetGroupArn'' Exception

```
TASK [create alb] *********************************************************************************************************************************************************************
task path: /home/jevers/misc_dev/ansible_alb_test/alb.yml:63
Using module file /home/jevers/.local/lib/python3.6/site-packages/ansible/modules/cloud/amazon/elb_application_lb.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: jevers
<localhost> EXEC /bin/sh -c 'python3 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 1028, in <module>
    main()
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 1023, in main
    create_or_update_elb(connection, connection_ec2, module)
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 915, in create_or_update_elb
    listener_changed = create_or_update_elb_listeners(connection, module, elb)
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 762, in create_or_update_elb_listeners
    rules_to_add, rules_to_modify, rules_to_delete = compare_rules(connection, module, current_listeners, listener)
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 693, in compare_rules
    modified_rule = compare_rule(current_rule, new_rule)
  File "/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py", line 600, in compare_rule
    if current_rule['Actions'][0]['TargetGroupArn'] != new_rule['Actions'][0]['TargetGroupArn']:
KeyError: 'TargetGroupArn'

fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 1028, in <module>\n    main()\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 1023, in main\n    create_or_update_elb(connection, connection_ec2, module)\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 915, in create_or_update_elb\n    listener_changed = create_or_update_elb_listeners(connection, module, elb)\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 762, in create_or_update_elb_listeners\n    rules_to_add, rules_to_modify, rules_to_delete = compare_rules(connection, module, current_listeners, listener)\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 693, in compare_rules\n    modified_rule = compare_rule(current_rule, new_rule)\n  File \"/tmp/ansible_7qen__0n/ansible_module_elb_application_lb.py\", line 600, in compare_rule\n    if current_rule['Actions'][0]['TargetGroupArn'] != new_rule['Actions'][0]['TargetGroupArn']:\nKeyError: 'TargetGroupArn'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE",
    "rc": 1
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/elb_application_lb.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/elb_application_lb.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @wimnat
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by wimnat** [comment]
It is not clearly documented but you can see it in the examples:

`# Required. Only 'forward' is accepted at this time`

And in the code... https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/aws/elbv2.py#L661

Obviously that's not true any more but the elbv2 code will need updating to manage the new modes.

**Comment by jeevers** [comment]
If 'forward' actions are currently the only supported action type, shouldn't the rule comparison logic check that the rule is a forward before trying to extract the target group arn from the dictionary? That way a warning message stating that the rule isn't a supported type can be displayed instead of a KeyError exception.

**Comment by wimnat** [comment]
Yeh sounds good. I didn't know AWS were going to bring in new actions when
I wrote it but I'm open to PRs.

**Comment by markuman** [comment]
@jeevers @wimnat Hi all,
I want to tell that I run into the same issu. After applying the patch for elbv2.py from https://github.com/jeevers/ansible/commit/c72d9377a8ee823a617415545844211253a45696 it works for me.

What needs to be done to get this change merged into ansible?

**Comment by ichekaldin** [comment]
@jeevers @wimnat FWIW the same issue happens when a listener or a rule contains a redirect action. For example, when I want the application LB to always redirect from from HTTP to HTTPs. The behavior is the same as what @jeevers originally described: listener is successfully created at first, but the subsequent runs fail.

**Comment by markuman** [comment]
@ichekaldin true. for me https://github.com/jeevers/ansible/commit/c72d9377a8ee823a617415545844211253a45696 fix this issue too.

**Comment by jeevers** [comment]
I haven't really had the time to work on this since the last commit. When I last left it I was working on the integration tests, and was having some trouble getting the last part of the tests to pass. Can someone try to run the tests and see what I might be doing wrong?

**Comment by markuman** [comment]
@ichekaldin @jeevers hm I've misread. Do you have a minimal playbook that reproduce this error?

> when I want the application LB to always redirect from from HTTP to HTTPs. ...
>  listener is successfully created at first, but the subsequent runs fail.

**Comment by ichekaldin** [comment]
@markuman something like this:

```
- elb_application_lb:
    name: my-alb
    scheme: internet-facing
    security_groups:
      - sg-xyz
    subnets:
      - subnet-abc
    state: present
    listeners:
      - Protocol: HTTP
        Port: 80
        DefaultActions:
          - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Host: "#{host}"
              Query: "#{query}"
              Path: "/#{path}"
              Port: "443"
              StatusCode: HTTP_301
      - Protocol: HTTPS
        Port: 443
        SslPolicy: ELBSecurityPolicy-TLS-1-2-Ext-2018-06
        Certificates:
          - CertificateArn: "arn:aws:acm:us-east-1:123412341234:certificate/xyz"
        DefaultActions:
          - Type: forward
            TargetGroupName: my-alb-target-group
```

**Comment by markuman** [comment]
@ichekaldin 
I can confirm that this fails with the current upstream `elbv2.py` from ansible 2.7.8.  
But it works fine with the patched version from @jeevers 

@jeevers 

> Can someone try to run the tests and see what I might be doing wrong?

I try to do it the next days and try to investigate what is wrong or missing.

**Comment by markuman** [comment]
I was able to cherry-pick @jeevers changes in my new fork of ansible and run `bin/ansible-test units -v --python 3.7 --docker default test/units/module_utils/aws/test_aws_module.py`

the result looks good.

```
============================= test session starts ==============================
platform linux -- Python 3.7.2, pytest-4.2.1, py-1.7.0, pluggy-0.8.1 -- /tmp/python-g9on5mto-ansible/python
cachedir: .pytest_cache
rootdir: /root/ansible, inifile: tox.ini
plugins: xdist-1.26.1, mock-1.10.1, forked-1.0.2, f5-sdk-3.0.20
gw0 I / gw1 I / gw2 I / gw3 I / gw4 I / gw5 I / gw6 I / gw7 I
[gw0] linux Python 3.7.2 cwd: /root/ansible
[gw1] linux Python 3.7.2 cwd: /root/ansible
[gw2] linux Python 3.7.2 cwd: /root/ansible
[gw3] linux Python 3.7.2 cwd: /root/ansible
[gw4] linux Python 3.7.2 cwd: /root/ansible
[gw5] linux Python 3.7.2 cwd: /root/ansible
[gw6] linux Python 3.7.2 cwd: /root/ansible
[gw7] linux Python 3.7.2 cwd: /root/ansible
[gw0] Python 3.7.2 (default, Jan 11 2019, 21:31:15)  -- [GCC 5.4.0 20160609]
[gw1] Python 3.7.2 (default, Jan 11 2019, 21:31:15)  -- [GCC 5.4.0 20160609]
[gw2] Python 3.7.2 (default, Jan 11 2019, 21:31:15)  -- [GCC 5.4.0 20160609]
[gw3] Python 3.7.2 (default, Jan 11 2019, 21:31:15)  -- [GCC 5.4.0 20160609]
[gw4] Python 3.7.2 (default, Jan 11 2019, 21:31:15)  -- [GCC 5.4.0 20160609]
[gw5] Python 3.7.2 (default, Jan 11 2019, 21:31:15)  -- [GCC 5.4.0 20160609]
[gw6] Python 3.7.2 (default, Jan 11 2019, 21:31:15)  -- [GCC 5.4.0 20160609]
[gw7] Python 3.7.2 (default, Jan 11 2019, 21:31:15)  -- [GCC 5.4.0 20160609]
gw0 [3] / gw1 [3] / gw2 [3] / gw3 [3] / gw4 [3] / gw5 [3] / gw6 [3] / gw7 [3]

scheduling tests via LoadScheduling
[gw0] [ 33%] PASSED test/units/module_utils/aws/test_aws_module.py::AWSModuleTestCase::test_create_aws_module_should_set_up_params 
[gw2] [ 66%] PASSED test/units/module_utils/aws/test_aws_module.py::ErrorReportingTestcase::test_botocore_exception_without_response_reports_nicely_via_fail_json_aws 
[gw1] [100%] PASSED test/units/module_utils/aws/test_aws_module.py::ErrorReportingTestcase::test_botocore_exception_reports_nicely_via_fail_json_aws 

```

but I'm not sure how to trigger the integration test just for aws. Can you help me @jeevers ?

**Comment by jeevers** [comment]
Had to dust off some documentation:
1. Edit 'test/integration/cloud-config-aws.yml' and add credentials for an AWS account you can run in
2. Then run the integration test against the module
        ```test/runner/ansible-test integration -v unsupported/elb_application_lb --docker```

I'm currently running through the integration test right now, I'll update with what's actually failing.

**Comment by jeevers** [comment]
It fails at the `elb_application_lb_test : test idempotency non-default rule with multiple actions` task:

https://github.com/jeevers/ansible/blob/alb_listener_actions_issue41861/test/integration/targets/elb_application_lb/playbooks/roles/elb_application_lb_test/tasks/test_multiple_actions.yml#L185

```TASK [elb_application_lb_test : test non-default rule with multiple actions] ***
task path: /root/ansible/test/integration/targets/elb_application_lb/playbooks/roles/elb_application_lb_test/tasks/test_multiple_actions.yml:143
changed: [localhost] => {"access_logs_s3_bucket": "", "access_logs_s3_enabled": "false", "access_logs_s3_prefix": "", "availability_zones": [{"subnet_id": "subnet-0150a130f78c2b6d1", "zone_name": "us-east-2a"}, {"subnet_id": "subnet-04ec00699863e254d", "zone_name": "us-east-2b"}], "canonical_hosted_zone_id": "Z3AADJGX6KTTL2", "changed": true, "created_time": "2019-03-21T20:10:53.770000+00:00", "deletion_protection_enabled": "false", "dns_name": "my-alb-30819680-1285882208.us-east-2.elb.amazonaws.com", "idle_timeout_timeout_seconds": "60", "ip_address_type": "ipv4", "listeners": [{"certificates": [{"certificate_arn": "arn:aws:iam::<AWS_ACCT_ID>:server-certificate/my-alb-30819680"}], "default_actions": [{"authenticate_oidc_config": {"authorization_endpoint": "https://www.example.com/auth", "client_id": "eeeeeeeeeeeeeeeeeeeeeeeeee", "issuer": "https://www.example.com/issuer", "on_unauthenticated_request": "authenticate", "scope": "openid", "session_cookie_name": "AWSELBAuthSessionCookie", "session_timeout": 604800, "token_endpoint": "https://www.example.com/token", "user_info_endpoint": "https://www.example.com/userinfo"}, "order": 1, "type": "authenticate-oidc"}, {"order": 2, "target_group_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:targetgroup/my-tg-30819680/08a09dec83ba91a4", "type": "forward"}], "listener_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:listener/app/my-alb-30819680/c9b2d08fdf886eee/c1186071c528c1c4", "load_balancer_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:loadbalancer/app/my-alb-30819680/c9b2d08fdf886eee", "port": 443, "protocol": "HTTPS", "rules": [{"actions": [{"order": 2, "target_group_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:targetgroup/my-tg-30819680/08a09dec83ba91a4", "type": "forward"}, {"authenticate_oidc_config": {"authorization_endpoint": "https://www.example.com/auth", "client_id": "eeeeeeeeeeeeeeeeeeeeeeeeee", "issuer": "https://www.example.com/issuer", "on_unauthenticated_request": "authenticate", "scope": "openid", "session_cookie_name": "AWSELBAuthSessionCookie", "session_timeout": 604800, "token_endpoint": "https://www.example.com/token", "user_info_endpoint": "https://www.example.com/userinfo"}, "order": 1, "type": "authenticate-oidc"}], "conditions": [{"field": "path-pattern", "values": ["*"]}], "is_default": false, "priority": "1", "rule_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:listener-rule/app/my-alb-30819680/c9b2d08fdf886eee/c1186071c528c1c4/0f0a9e7d7318495d"}, {"actions": [{"authenticate_oidc_config": {"authorization_endpoint": "https://www.example.com/auth", "client_id": "eeeeeeeeeeeeeeeeeeeeeeeeee", "issuer": "https://www.example.com/issuer", "on_unauthenticated_request": "authenticate", "scope": "openid", "session_cookie_name": "AWSELBAuthSessionCookie", "session_timeout": 604800, "token_endpoint": "https://www.example.com/token", "user_info_endpoint": "https://www.example.com/userinfo"}, "order": 1, "type": "authenticate-oidc"}, {"order": 2, "target_group_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:targetgroup/my-tg-30819680/08a09dec83ba91a4", "type": "forward"}], "conditions": [], "is_default": true, "priority": "default", "rule_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:listener-rule/app/my-alb-30819680/c9b2d08fdf886eee/c1186071c528c1c4/8d614f7d4c6aede6"}], "ssl_policy": "ELBSecurityPolicy-2016-08"}], "load_balancer_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:loadbalancer/app/my-alb-30819680/c9b2d08fdf886eee", "load_balancer_name": "my-alb-30819680", "routing_http2_enabled": "true", "scheme": "internet-facing", "security_groups": ["sg-04f09be93ea9d2046"], "state": {"code": "provisioning"}, "tags": {}, "type": "application", "vpc_id": "vpc-049ec3c70b19ff2dc"}

TASK [elb_application_lb_test : assert] ****************************************
task path: /root/ansible/test/integration/targets/elb_application_lb/playbooks/roles/elb_application_lb_test/tasks/test_multiple_actions.yml:178
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [elb_application_lb_test : test idempotency non-default rule with multiple actions] ***
task path: /root/ansible/test/integration/targets/elb_application_lb/playbooks/roles/elb_application_lb_test/tasks/test_multiple_actions.yml:185
changed: [localhost] => {"access_logs_s3_bucket": "", "access_logs_s3_enabled": "false", "access_logs_s3_prefix": "", "availability_zones": [{"subnet_id": "subnet-0150a130f78c2b6d1", "zone_name": "us-east-2a"}, {"subnet_id": "subnet-04ec00699863e254d", "zone_name": "us-east-2b"}], "canonical_hosted_zone_id": "Z3AADJGX6KTTL2", "changed": true, "created_time": "2019-03-21T20:10:53.770000+00:00", "deletion_protection_enabled": "false", "dns_name": "my-alb-30819680-1285882208.us-east-2.elb.amazonaws.com", "idle_timeout_timeout_seconds": "60", "ip_address_type": "ipv4", "listeners": [{"certificates": [{"certificate_arn": "arn:aws:iam::<AWS_ACCT_ID>:server-certificate/my-alb-30819680"}], "default_actions": [{"authenticate_oidc_config": {"authorization_endpoint": "https://www.example.com/auth", "client_id": "eeeeeeeeeeeeeeeeeeeeeeeeee", "issuer": "https://www.example.com/issuer", "on_unauthenticated_request": "authenticate", "scope": "openid", "session_cookie_name": "AWSELBAuthSessionCookie", "session_timeout": 604800, "token_endpoint": "https://www.example.com/token", "user_info_endpoint": "https://www.example.com/userinfo"}, "order": 1, "type": "authenticate-oidc"}, {"order": 2, "target_group_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:targetgroup/my-tg-30819680/08a09dec83ba91a4", "type": "forward"}], "listener_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:listener/app/my-alb-30819680/c9b2d08fdf886eee/c1186071c528c1c4", "load_balancer_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:loadbalancer/app/my-alb-30819680/c9b2d08fdf886eee", "port": 443, "protocol": "HTTPS", "rules": [{"actions": [{"authenticate_oidc_config": {"authorization_endpoint": "https://www.example.com/auth", "client_id": "eeeeeeeeeeeeeeeeeeeeeeeeee", "issuer": "https://www.example.com/issuer", "on_unauthenticated_request": "authenticate", "scope": "openid", "session_cookie_name": "AWSELBAuthSessionCookie", "session_timeout": 604800, "token_endpoint": "https://www.example.com/token", "user_info_endpoint": "https://www.example.com/userinfo"}, "order": 1, "type": "authenticate-oidc"}, {"order": 2, "target_group_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:targetgroup/my-tg-30819680/08a09dec83ba91a4", "type": "forward"}], "conditions": [{"field": "path-pattern", "values": ["*"]}], "is_default": false, "priority": "1", "rule_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:listener-rule/app/my-alb-30819680/c9b2d08fdf886eee/c1186071c528c1c4/5dc6923d223ab282"}, {"actions": [{"authenticate_oidc_config": {"authorization_endpoint": "https://www.example.com/auth", "client_id": "eeeeeeeeeeeeeeeeeeeeeeeeee", "issuer": "https://www.example.com/issuer", "on_unauthenticated_request": "authenticate", "scope": "openid", "session_cookie_name": "AWSELBAuthSessionCookie", "session_timeout": 604800, "token_endpoint": "https://www.example.com/token", "user_info_endpoint": "https://www.example.com/userinfo"}, "order": 1, "type": "authenticate-oidc"}, {"order": 2, "target_group_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:targetgroup/my-tg-30819680/08a09dec83ba91a4", "type": "forward"}], "conditions": [], "is_default": true, "priority": "default", "rule_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:listener-rule/app/my-alb-30819680/c9b2d08fdf886eee/c1186071c528c1c4/8d614f7d4c6aede6"}], "ssl_policy": "ELBSecurityPolicy-2016-08"}], "load_balancer_arn": "arn:aws:elasticloadbalancing:us-east-2:<AWS_ACCT_ID>:loadbalancer/app/my-alb-30819680/c9b2d08fdf886eee", "load_balancer_name": "my-alb-30819680", "routing_http2_enabled": "true", "scheme": "internet-facing", "security_groups": ["sg-04f09be93ea9d2046"], "state": {"code": "provisioning"}, "tags": {}, "type": "application", "vpc_id": "vpc-049ec3c70b19ff2dc"}

TASK [elb_application_lb_test : assert] ****************************************
task path: /root/ansible/test/integration/targets/elb_application_lb/playbooks/roles/elb_application_lb_test/tasks/test_multiple_actions.yml:220
fatal: [localhost]: FAILED! => {
    "assertion": "not alb.changed",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}```

**Comment by ichekaldin** [comment]
@markuman and @jeevers any luck on this?

**Comment by pierreant-p** [comment]
+1

**Comment by markuman** [comment]
@jeevers I forked your branch into my fork https://github.com/markuman/ansible/tree/jeevers_alb_listener_actions_issue41861

...but I'm in general not able to run the integration test

```
+ ansible-playbook -i ../../inventory -e @../../integration_config.yml -e @../../cloud-config-aws.yml -v playbooks/multiple_actions_fail.yml -v -e @/root/.ansible/test/tmp/elb_application_lb-e42xs4ht-ÅÑŚÌβŁÈ/test/integration/config-file-dvjabeor.json
ansible-playbook 2.8.0.dev0
  config file = /root/.ansible/test/tmp/elb_application_lb-e42xs4ht-ÅÑŚÌβŁÈ/test/integration/integration.cfg
  configured module search path = ['/dev/null']
  ansible python module location = /root/ansible/lib/ansible
  executable location = /root/ansible/bin/ansible-playbook
  python version = 3.6.8 (default, Dec 24 2018, 19:24:27) [GCC 5.4.0 20160609]
Using /root/.ansible/test/tmp/elb_application_lb-e42xs4ht-ÅÑŚÌβŁÈ/test/integration/integration.cfg as config file
ERROR! Unable to retrieve file contents
Could not find or access '/root/.ansible/test/tmp/elb_application_lb-e42xs4ht-ÅÑŚÌβŁÈ/test/integration/cloud-config-aws.yml' on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
+ rm -rf /tmp/tmp.C3nsRwnTix
NOTICE: To resume at this test target, use the option: --start-at elb_application_lb
ERROR: Command "./runme.sh -v -e '@/root/.ansible/test/tmp/elb_application_lb-e42xs4ht-ÅÑŚÌβŁÈ/test/integration/config-file-dvjabeor.json'" returned exit status 1.
Run command: docker exec b6fc8191dbcec275e3363fe8c4c9133e2a087fc6af1b8a035003b2959245c7d9 tar czf /root/results.tgz -C /root/ansible/test results
Run command: docker exec -i b6fc8191dbcec275e3363fe8c4c9133e2a087fc6af1b8a035003b2959245c7d9 dd if=/root/results.tgz bs=65536
Run command: tar oxzf /tmp/ansible-result-ammu_ho1.tgz -C test
Run command: docker rm -f b6fc8191dbcec275e3363fe8c4c9133e2a087fc6af1b8a035003b2959245c7d9
ERROR: Command "docker exec b6fc8191dbcec275e3363fe8c4c9133e2a087fc6af1b8a035003b2959245c7d9 /usr/bin/env LC_ALL=en_US.UTF-8 /root/ansible/bin/ansible-test integration -v unsupported/elb_application_lb --metadata metadata-beynlg5a.json --truncate 213 --color yes --requirements --allow-destructive" returned exit status 1.
```

I've used the `test/integration/cloud-config-aws.ini` based on the `test/integration/cloud-config-aws.ini.template`.

Any ideas?

**Comment by mjmayer** [comment]
@markuman You will need to make changes to runme.sh for the elb_application_lb targert f51d02bd5c49cda82c143fe88de49580b1dac8fe

**Comment by jeevers** [comment]
@markuman  just pushed the fix to my branch. Now it looks like AWS changed the API for the AuthenticateOidcActionConfig action that i used in the test. I'll look into using a different action

**Comment by markuman** [comment]
@jeevers I've pulled your last changes and found a bug.

```yml
      - Conditions:
          - Field: source-ip
            SourceIpConfig:
              Values:
                - "10.100.1.11/32"
          - Field: host-header
            Values:
              - some.cool.domain
        Actions:
          - TargetGroupName: some-target-group
            Type: forward
```

The initial rollout works fine, but an update failes, because the `Values` key, is in another dictionary level.

```diff
diff --git a/lib/ansible/module_utils/aws/elbv2.py b/lib/ansible/module_utils/aws/elbv2.py
index 8cd2dafd7d..fb8047608f 100644
--- a/lib/ansible/module_utils/aws/elbv2.py
+++ b/lib/ansible/module_utils/aws/elbv2.py
@@ -712,7 +712,11 @@ class ELBListenerRules(object):
         condition_found = False
 
         for current_condition in current_conditions:
-            if current_condition['Field'] == condition['Field'] and current_condition['Values'][0] == condition['Values'][0]:
+            if current_condition.get('SourceIpConfig'):
+                if current_condition['Field'] == condition['Field'] and current_condition['SourceIpConfig']['Values'][0] == condition['SourceIpConfig']['Values'][0]:
+                    condition_found = True
+                    break
+            elif current_condition['Field'] == condition['Field'] and current_condition['Values'][0] == condition['Values'][0]:
                 condition_found = True
                 break
```

See https://github.com/markuman/ansible/commit/d5295231999516acff439a51febce17d5e30c036  
This branch based on your branch.
