### ISSUE TITLE
ios_config replace: block does not support root-level config block diffs

### ISSUE THREAD

**Issue by logan2211** [ansible/ansible#41871]
##### SUMMARY
Root-level config diffs are not supported when using `replace: block` in `ios_config`.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_config

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /home/ubuntu/ansible-lsn-site/playbooks/ansible.cfg
  configured module search path = [u'/home/ubuntu/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
   ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /home/ubuntu/.ansible-venv/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

IOS 12.2(52)SE

##### STEPS TO REPRODUCE

```yaml
- name: Apply the Standard ACL
  ios_config:
    provider: "{{ network_provider }}"
    before:
      - no access-list 1
    lines:
      - access-list 1 permit 1.1.1.1
      - access-list 1 permit 2.2.2.2
    replace: block
    save_when: modified
```

##### EXPECTED RESULTS

In a device where 1.1.1.1 already exists in the access-list, I expect it to send the lines:
```
no access-list 1
access-list 1 permit 1.1.1.1
access-list 1 permit 2.2.2.2
```

##### ACTUAL RESULTS

The lines sent to the device (again when the access-list already contains 1.1.1.1) are:
```
no access-list 1
access-list 1 permit 2.2.2.2
```

##### ADDITIONAL COMMENTS
Based on https://github.com/ansible/ansible/blob/f30e0b833daf25ea10e3fc535adc385a30b3ce04/lib/ansible/module_utils/network/common/config.py#L342-L354 I'm thinking the bug is that `replace: block` only supports replacing blocks of configuration subtrees (ie. configuration blocks that contain `parent`s). At the root level of the tree it appears to consider each line its own block.
