### ISSUE TITLE
letsencrypt.py reporting incorrect "cert_days"

### ISSUE THREAD

**Issue by simbalion** [ansible/ansible#41873]
##### SUMMARY
On June 23rd I got an alert of a certificate set to expire on July 21st, 28 days later. I use a daily renewal cronjob that uses the letsencrypt module with a "remaining_days" of 30, so it should have activated 2 days ago.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
letsencrypt.py

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /home/simba/.ansible/ansible.cfg
  configured module search path = [u'/home/simba/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible-2.5.1-py2.7.egg/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]

```

##### OS / ENVIRONMENT

Debian 9

##### STEPS TO REPRODUCE

```yaml
simba:$ cat wildcards_prepare_challenge.yml 
---
- name: Create lets encrypt directory
  file:
    path: /etc/ssl/le
    state: directory
    owner: root
    group: letsencrypt
    mode: "u=rwx,g=rwx,o="

- name: Create domain directory
  file:
    path: /etc/ssl/le/{{ ssl_domain }}
    state: directory
    owner: root
    group: letsencrypt
    mode: "u=rwx,g=rwx,o="

- name: Create account key
  shell: openssl genrsa 4096 > /etc/ssl/le/{{ ssl_domain }}/account.key
  args:
    creates: /etc/ssl/le/{{ ssl_domain }}/account.key

- name: Create domain key
  shell: openssl genrsa 4096 > /etc/ssl/le/{{ ssl_domain }}/domain.key
  args:
    creates: /etc/ssl/le/{{ ssl_domain }}/domain.key

- name: Create multi-domain CSR
  shell: openssl req -new -sha256 -key /etc/ssl/le/{{ ssl_domain }}/domain.key -subj "/" -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "[SAN]\nsubjectAltName=DNS:{{ ssl_domain}},DNS:*.{{ ssl_domain }}")) > /etc/ssl/le/{{ ssl_domain }}/csr
  args:
    creates: /etc/ssl/le/{{ ssl_domain }}/csr
    executable: /bin/bash

- name: Create challenge
  letsencrypt:
    account_key_src: /etc/ssl/le/{{ ssl_domain }}/account.key
    csr: /etc/ssl/le/{{ ssl_domain }}/csr
    dest: /etc/ssl/le/{{ ssl_domain }}/certificate.crt
    fullchain_dest: /etc/ssl/le/{{ ssl_domain }}/fullchain.crt
    chain_dest: /etc/ssl/le/{{ ssl_domain }}/intermediate.crt
    challenge: dns-01
    acme_directory: https://acme-v02.api.letsencrypt.org/directory
    # acme_directory: https://acme-staging-v02.api.letsencrypt.org/directory
    acme_version: 2
    terms_agreed: True
    remaining_days: 60
  register: ssl_challenge

- debug:
    msg: "{{ ssl_challenge }}"

- name: Prepare challenges
  set_fact:
    challenge_one: "{{ ssl_challenge['challenge_data'].items()[1][1]['dns-01'].resource_value }}"
    challenge_two: "{{ ssl_challenge['challenge_data'].items()[0][1]['dns-01'].resource_value }}"

```

##### EXPECTED RESULTS

As there were only 28 days to expiration, it should have issued 'challenge_data'

##### ACTUAL RESULTS

'challenge_data' was not created because the module returns "cert_days = 56"

```

```
