### ISSUE TITLE
vmware_host_facts only returning one Host when used VCenter IP

### ISSUE THREAD

**Issue by aksharbarot** [ansible/ansible#41890]
##### SUMMARY

Tried to run vmware_host_facts module which is mentioned as either use ESX IP or Vcenter IP. While using VCenter IP, it is returning with random host details. have 30+ hosts in Vcenter but, result is for 1 host.

  

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_host_facts

##### ANSIBLE VERSION

```
ansible 2.5.3
```

##### OS / ENVIRONMENT

CentOS 7.3

##### STEPS TO REPRODUCE

```yaml
---
- name: get host details
  hosts: localhost
  tasks:

        - name: Gather vmware host facts
          vmware_host_facts:
             hostname: Vcenter IP
             username: user
             password: pass
             validate_certs: no
          register: host_facts
          delegate_to: localhost

        - debug:
            var: host_facts

```

##### EXPECTED RESULTS

it should list all hosts which are present in Vcenter

##### ACTUAL RESULTS

```
ok: [localhost -> localhost] => {
    "ansible_facts": {
        "ansible_all_ipv4_addresses": [
            "xx.xx.xx.xx",
            "xx.xx.xx.xx",
            "xx.xx.xx.xx"
        ],
        "ansible_bios_date": "2018-01-22T00:00:00+00:00",
        "ansible_bios_version": "I38",
        "ansible_datastore": [
            {
                "free": "205.81 GB",
                "name": "LocalStorage-ECS017",
                "total": "216.00 GB"
            },
            {
                "free": "6.52 TB",
                "name": "nfs",
                "total": "13.83 TB"
            },
            {
                "free": "3.08 TB",
                "name": "nfs",
                "total": "30.48 TB"
            },
            {
                "free": "1016.53 GB",
                "name": "nfs",
                "total": "1.00 TB"
            },
            {
                "free": "18.88 TB",
                "name": "nfs",
                "total": "33.65 TB"
            },
            {
                "free": "10.64 TB",
                "name": "nfs",
                "total": "38.29 TB"
            },
            {
                "free": "4.83 TB",
                "name": "nfs",
                "total": "51.24 TB"
            },
            {
                "free": "21.90 TB",
                "name": "nfs",
                "total": "59.43 TB"
            }
        ],
        "ansible_distribution": "VMware ESXi",
        "ansible_distribution_build": "7967664",
        "ansible_distribution_version": "6.0.0",
        "ansible_hostname": "hostname",
        "ansible_interfaces": [
            "vmk0",
            "vmk1",
            "vmk2"
        ],
        "ansible_memfree_mb": 165001,
        "ansible_memtotal_mb": 1048317,
        "ansible_os_type": "vmnix-x86",
        "ansible_processor": "Intel(R) Xeon(R) CPU E5-4650 v3 @",
        "ansible_processor_cores": 48,
        "ansible_processor_count": 4,
        "ansible_processor_vcpus": 96,
        "ansible_product_name": "ProLiant BL660c XXX",
        "ansible_product_serial": "Serial",
        "ansible_system_vendor": "Vendor",
        "ansible_vmk0": {
            "device": "vmk0",
            "ipv4": {
                "address": "xx.xx.xx.xx",
                "netmask": "255.255.255.0"
            },
            "macaddress": "xx:xx:xx:xx:xx:xx",
            "mtu": 1500
        },
        "ansible_vmk1": {
            "device": "vmk1",
            "ipv4": {
                "address": "xx.xx.xx.xx",
                "netmask": "255.255.255.0"
            },
            "macaddress": "xx:xx:xx:xx:xx:xx",
            "mtu": 1500
        },
        "ansible_vmk2": {
            "device": "vmk2",
            "ipv4": {
                "address": "xx.xx.xx.xx",
                "netmask": "255.255.255.0"
            },
            "macaddress": "xx:xx:xx:xx:xx:xx",
            "mtu": 1500
        }
    },
    "changed": false,
    "invocation": {
        "module_args": {
            "hostname": "xx.xx.xx.xx",
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "username": "username",
            "validate_certs": false
        }
    }
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_host_facts.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host_facts.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @warthog9 @woshihaoren
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@aksharbarot Thanks for reporting this issue. Currently, it returns the first ESXi hostsystem which it finds from given vCenter - see here [docs](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_host_facts.py#L23)
As workaround, you can use `with_items` and iterate over all ESXi system from given vCenter.

```yaml
       - name: Gather vmware host facts
          vmware_host_facts:
             hostname: "{{ item.esxi_hostname }}"
             username: "{{ item.esxi_user }}"
             password: "{{ item.esxi_pass }}"
             validate_certs: no
          register: host_facts
          delegate_to: localhost
          with_items:
             - {esxi_hostname: hostname_1, esxi_user: username_host_1, esxi_pass: pass_host_1}
             - {esxi_hostname: hostname_2, esxi_user: username_host_2, esxi_pass: pass_host_2}

```
@woshihaoren What do you think ?
