### ISSUE TITLE
cloud:ovirt_vms: Can't create new VM. Python raise Exception("Entity '%s' was not found." % name).

### ISSUE THREAD

**Issue by AlexGluck** [ansible/ansible#41914]
##### SUMMARY
Subject all say. I replaced 7 letters in company name to `company` and 9 letters my system username to `user`.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ovirt_vms

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /home/user/files/git_repos/company/infra.ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION
```
ANSIBLE_PIPELINING(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = True
CACHE_PLUGIN(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = yaml
CACHE_PLUGIN_CONNECTION(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = ~/.ansible/fact_cache
CACHE_PLUGIN_TIMEOUT(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = 86400
DEFAULT_FORKS(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = 25
DEFAULT_HASH_BEHAVIOUR(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = [u'/home/user/files/git_repos/company/infra.ansible/vars/ovirt4.py']
DEFAULT_INTERNAL_POLL_INTERVAL(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = 0.001
DEFAULT_REMOTE_USER(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = root
DEFAULT_ROLES_PATH(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = [u'/home/user/files/git_repos/company/infra.ansible/roles']
DEFAULT_TIMEOUT(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = 50
DISPLAY_SKIPPED_HOSTS(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = 25
PERSISTENT_CONNECT_TIMEOUT(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/home/user/files/git_repos/company/infra.ansible/ansible.cfg) = False
```

##### OS / ENVIRONMENT
Fedora 28 Workstation
```
$ pip2 search ovirt
ovirt (1.2.13)                        - Script to manage ovirt engine
  INSTALLED: 1.2.13 (latest)
ovirt-ansible (0.3.2)                 - oVirt Ansible utility
ovirt-shell (3.6.9.2)                 - A command-line interface to oVirt Virtualization
ovirt-engine-sdk (3.2.0.11-SNAPSHOT)  - A SDK interface to oVirt Virtualization
ovirt-engine-sdk-python (4.2.7)       - Python SDK for oVirt Engine API
  INSTALLED: 4.2.7 (latest)
```

##### STEPS TO REPRODUCE
```
ansible-playbook -vvv -i ./vars/inventory.ini ./playbooks/manage_ovirt_VM.yml -e @runtime_vars.yaml
```

runtime_vars.yaml
```
vms:
  infra_test_ovirt_vm_ansible_managment:
      state: "present"
      description: ""
      comment: ""
      cpu: "1"
      ram: "1GiB"
      hdd: ""
      nics:
        eth0:
          proto: "static"
          ip: "10.0.0.2"
```
manage_ovirt_VM.yml
```
- hosts: "{{ hosts | default('*engine*') }}"
  gather_facts: no
  pre_tasks:
    - name: Obtain SSO token with using username/password credentials
      ovirt_auth:
        url: "{{ ovirt.url | default(default.ovirt.url) }}"
        insecure: "{{ ovirt.check_ssl|default(default.ovirt.check_ssl) }}"
        username: "{{ ovirt.username|default(default.ovirt.username) }}"
        password: "{{ ovirt.password|default(default.ovirt.password) }}"

  tasks:
    - name: Manage Virtual Machines
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: "{{ vm.state|default(default.vm.state) }}"
        name: "{{ vm|replace('_', '-') }}.{{ dns_zone|default(default.dns_zone) }}"
        wait: True
      register: previous
      with_items: "{{ vms }}"
      loop_control:
        loop_var: vm

```
##### EXPECTED RESULTS
I try create a new VM.

##### ACTUAL RESULTS
```
TASK [Manage Virtual Machine] *************************************************************************************************************************************************************************************
task path: /home/username/files/git_repos/company/infra.ansible/playbooks/manage_ovirt_VM.yml:28
Using module file /usr/lib/python2.7/site-packages/ansible/modules/cloud/ovirt/ovirt_vms.py
<ovirt-engine.12.company.local> ESTABLISH SSH CONNECTION FOR USER: root
<ovirt-engine.12.company.local> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=50 -o ControlPath=/home/username/.ansible/cp/5eb47da811 ovirt-engine.12.company.local '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
<ovirt-engine.12.company.local> (1, '\n{"msg": "Entity \'None\' was not found.", "failed": true, "exception": "Traceback (most recent call last):\\n  File \\"/tmp/ansible_CsGd7w/ansible_module_ovirt_vms.py\\", line 1942, in main\\n    sd_id = get_id_by_name(storage_domains_service, module.params[\'storage_domain\'])\\n  File \\"/tmp/ansible_CsGd7w/ansible_modlib.zip/ansible/module_utils/ovirt.py\\", line 301, in get_id_by_name\\n    raise Exception(\\"Entity \'%s\' was not found.\\" % name)\\nException: Entity \'None\' was not found.\\n", "invocation": {"module_args": {"comment": null, "graphical_console": null, "disks": [], "force": false, "cloud_init_nics": [], "placement_policy": null, "boot_menu": null, "xen": null, "usb_support": null, "template_version": null, "cluster": null, "fetch_nested": false, "io_threads": null, "timezone": null, "watchdog": null, "memory_max": null, "id": null, "cpu_sockets": null, "high_availability": null, "storage_domain": null, "domain_mappings": [], "high_availability_priority": null, "nics": [], "custom_properties": null, "boot_devices": null, "disk_format": "cow", "sysprep": null, "cpu_cores": null, "ballooning_enabled": null, "cpu_mode": null, "state": "registered", "cpu_pinning": null, "vmware": null, "template": null, "memory": null, "cd_iso": null, "clone_permissions": false, "type": null, "initrd_path": null, "smartcard_enabled": null, "lease": null, "rng_device": null, "vnic_profile_mappings": [], "stateless": null, "lun_mappings": [], "clone": false, "kvm": null, "serial_console": null, "nested_attributes": [], "sso": null, "role_mappings": [], "serial_policy": null, "cpu_threads": null, "quota_id": null, "soundcard_enabled": null, "affinity_label_mappings": [], "delete_protected": null, "cloud_init_persist": false, "wait": true, "use_latest_template_version": null, "affinity_group_mappings": [], "operating_system": null, "serial_policy_value": null, "name": "infra-test-ovirt-vm-ansible-managment.12.company.local", "kernel_path": null, "cloud_init": null, "memory_guaranteed": null, "poll_interval": 3, "host": null, "instance_type": null, "reassign_bad_macs": null, "timeout": 180, "description": null, "cluster_mappings": [], "kernel_params": null, "allow_partial_import": null, "cpu_shares": null}}}\n', '')
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_CsGd7w/ansible_module_ovirt_vms.py", line 1942, in main
    sd_id = get_id_by_name(storage_domains_service, module.params['storage_domain'])
  File "/tmp/ansible_CsGd7w/ansible_modlib.zip/ansible/module_utils/ovirt.py", line 301, in get_id_by_name
    raise Exception("Entity '%s' was not found." % name)
Exception: Entity 'None' was not found.

failed: [infra-prod-ovirtengine.12.company.local] (item=infra_test_ovirt_vm_ansible_managment) => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "affinity_group_mappings": [], 
            "affinity_label_mappings": [], 
            "allow_partial_import": null, 
            "ballooning_enabled": null, 
            "boot_devices": null, 
            "boot_menu": null, 
            "cd_iso": null, 
            "clone": false, 
            "clone_permissions": false, 
            "cloud_init": null, 
            "cloud_init_nics": [], 
            "cloud_init_persist": false, 
            "cluster": null, 
            "cluster_mappings": [], 
            "comment": null, 
            "cpu_cores": null, 
            "cpu_mode": null, 
            "cpu_pinning": null, 
            "cpu_shares": null, 
            "cpu_sockets": null, 
            "cpu_threads": null, 
            "custom_properties": null, 
            "delete_protected": null, 
            "description": null, 
            "disk_format": "cow", 
            "disks": [], 
            "domain_mappings": [], 
            "fetch_nested": false, 
            "force": false, 
            "graphical_console": null, 
            "high_availability": null, 
            "high_availability_priority": null, 
            "host": null, 
            "id": null, 
            "initrd_path": null, 
            "instance_type": null, 
            "io_threads": null, 
            "kernel_params": null, 
            "kernel_path": null, 
            "kvm": null, 
            "lease": null, 
            "lun_mappings": [], 
            "memory": null, 
            "memory_guaranteed": null, 
            "memory_max": null, 
            "name": "infra-test-ovirt-vm-ansible-managment.12.company.local", 
            "nested_attributes": [], 
            "nics": [], 
            "operating_system": null, 
            "placement_policy": null, 
            "poll_interval": 3, 
            "quota_id": null, 
            "reassign_bad_macs": null, 
            "rng_device": null, 
            "role_mappings": [], 
            "serial_console": null, 
            "serial_policy": null, 
            "serial_policy_value": null, 
            "smartcard_enabled": null, 
            "soundcard_enabled": null, 
            "sso": null, 
            "state": "registered", 
            "stateless": null, 
            "storage_domain": null, 
            "sysprep": null, 
            "template": null, 
            "template_version": null, 
            "timeout": 180, 
            "timezone": null, 
            "type": null, 
            "usb_support": null, 
            "use_latest_template_version": null, 
            "vmware": null, 
            "vnic_profile_mappings": [], 
            "wait": true, 
            "watchdog": null, 
            "xen": null
        }
    }, 
    "msg": "Entity 'None' was not found.", 
    "vm": "infra_test_ovirt_vm_ansible_managment"
}

PLAY RECAP ********************************************************************************************************************************************************************************************************
infra-prod-ovirtengine.12.company.local : ok=5    changed=0    unreachable=0    failed=1   


```

**Comment by AlexGluck** [comment]
Why ansible module args not passed to python module?

**Comment by ansibot** [comment]
cc @machacekondra @mwperina
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by machacekondra** [comment]
You are using following task:

```yaml
    - name: Manage Virtual Machines
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        state: "{{ vm.state|default(default.vm.state) }}"
        name: "{{ vm|replace('_', '-') }}.{{ dns_zone|default(default.dns_zone) }}"
        wait: True
      register: previous
      with_items: "{{ vms }}"
      loop_control:
        loop_var: vm
```

And have defined following variable:

```yaml
vms:
  infra_test_ovirt_vm_ansible_managment:
      state: "present"
      description: ""
      comment: ""
      cpu: "1"
      ram: "1GiB"
      hdd: ""
      nics:
        eth0:
          proto: "static"
          ip: "10.0.0.2"
```

So in `vm` varaible inside the loop in your task if you want to access `state` of the vm, you need to use `vm.infra_test_ovirt_vm_ansible_managment.state`. I would suggest to you to use the `list` instead of `dictinary`, so use for example something like:

```yaml
vms:
  -   name: infra_test_ovirt_vm_ansible_managment
      state: "present"
      description: ""
      comment: ""
      cpu: "1"
      ram: "1GiB"
      hdd: ""
      nics:
        eth0:
          proto: "static"
          ip: "10.0.0.2"
```

Then the `vm.state` should be accesed correctly.

To explain your exception:

```
Exception("Entity '%s' was not found." % name)
```

The default state you have is `registered`, where there is mandatory `storage_domain` parameter. That's why you get the error, because you don't pass any, we can use this issue to track this bug.
@maorlipchuk Can you handle it?

**Comment by AlexGluck** [comment]
I change task, now work fine. But python exception need fix. 
```
     - name: Manage Virtual Machine
      ovirt_vms:
        auth: "{{ ovirt_auth }}"
        name: "{{ vm|replace('_', '-') }}.{{ vms[vm].dns_zone|default(default.dns_zone) }}"
        description: "{{ vms[vm].description|default('') }}"
        comment: "{{ vms[vm].comment|default('') }}"
        cluster: "{{ vms[vm].cluster|default(default.vm.cluster) }}"
        template: "{{ vms[vm].template|default(default.vm.template) }}"
        type: "{{ vms[vm].type|default(default.vm.type) }}"
        cpu_cores: "{{ vms[vm].cpu|default(default.vm.cpu) }}"
        memory: "{{ vms[vm].ram|default(default.vm.ram) }}"
        clone: "{{ vms[vm].clone_template|default(default.vm.clone_template) }}"
        graphical_console:
          headless_mode: false
          protocol: spice
        nics:
          - {profile_name: "{% if vms[vm].nics is defined %}{% if vms[vm].nics[0].network is defined %}{{ vms[vm].nics[0].network }}{% else %}{{ default.vm.nics[0].network }}{% endif %}{% endif %}", name: "{% if vms[vm].nics is defined %}{% if vms[vm].nics[0].name is defined %}{{ vms[vm].nics[0].name }}{% else %}{{ default.vm.nics[0].name }}{% endif %}{% endif %}"}
        wait: True
      register: previous
      with_items: "{{ vms }}"
      loop_control:
        loop_var: vm
```
