### ISSUE TITLE
ERROR! 'name' is not a valid attribute for a Block

### ISSUE THREAD

**Issue by igoratencompass** [ansible/ansible#41939]
##### SUMMARY

Ansible incorrectly complains about `name` used outside the `block` statement

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

block module

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.1.6.0
  config file = /home/ubuntu/configuration-management/ansible.cfg
  configured module search path = ['/usr/share/ansible']
```

##### STEPS TO REPRODUCE

```yaml
- name: add glusterfs ppa and install gluster-client
  block:
    - apt_repository: repo='ppa:gluster/glusterfs-{{ gluster_main_version }}' state=present update_cache=yes
    - apt: pkg={{ item }} state=latest
      with_items: ['glusterfs-client', 'glusterfs-common', 'xfsprogs']
  when: ansible_os_family == "Debian"
```

##### ACTUAL RESULTS

```
ERROR! 'name' is not a valid attribute for a Block

The error appears to have been in 'builder.yml': line 100, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - name: add glusterfs ppa and install gluster-client
      ^ here
```
