### ISSUE TITLE
Zabbix_host: template not found when trying to link a template

### ISSUE THREAD

**Issue by jgoedbloed** [ansible/ansible#41957]
##### SUMMARY
When trying in Zabbix to 

##### ISSUE TYPE
Bug Report

##### COMPONENT NAME
zabbix_host

##### ANSIBLE VERSION
ansible 2.5.5
  config file = /appserver/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

```

##### CONFIGURATION
ANSIBLE_PIPELINING(/appserver/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/appserver/ansible/ansible.cfg) = -F /appserver/ansible/ssh_bastion.cfg
ANSIBLE_SSH_CONTROL_PATH(/appserver/ansible/ansible.cfg) = ~/.ssh/mux-%r@%h:%p
DEFAULT_HOST_LIST(/appserver/ansible/ansible.cfg) = [u'/appserver/ansible/playbooks/environments/Onetrail-MONa
DEFAULT_LOG_PATH(/appserver/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_REMOTE_USER(/appserver/ansible/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/appserver/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']
INVENTORY_ENABLED(/appserver/ansible/ansible.cfg) = ['ini']

##### OS / ENVIRONMENT
OS: Centos7
Zabbix versin: 3.4.8
zabbix-api: 0.5.3

##### STEPS TO REPRODUCE
*Check in Zabbix that the actual template exists and the name corresponds (case sensitive)
*Use the following task in a playbook:

```yaml
    - name: Relate Wilfly template in Zabbix
      local_action:
        module: zabbix_host
        server_url: "{{ zabbix_api_server_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_password }}"
        host_name: "{{ ansible_hostname | lower }}"
        state: present
        link_templates:
          - "Wildfly"
```

##### EXPECTED RESULTS
The template would be linked.
Other actions with zabbix_host module with the same server_url, login_user, login_password and host_name actually work.

##### ACTUAL RESULTS
Error message: 
```fatal: [ACC-CIV-Wildfly-API -> localhost]: FAILED! => {"changed": false, "msg": "Template not found: Wildfly"}```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/monitoring/zabbix/zabbix_host.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/monitoring/zabbix/zabbix_host.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @D3DeFi @cove @eikef @harrisongu
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by D3DeFi** [comment]
Hi, thank you for your report. My possibilities for testing this are a bit limited, but I've managed to setup zabbix 3.4.11 server and test your snippet with ansible 2.5.2. However I was unable to reproduce the error you are receiving (used just default 'Template OS Linux').

Is this something you are able to reproduce with other templates as well? Aren't there any typos or additional spaces in the template name?

If this is a bug somehow then it was present from the beginning as I don't see any modification to template resolving function (get_template_ids) since the module release:
https://github.com/ansible/ansible/blame/devel/lib/ansible/modules/monitoring/zabbix/zabbix_host.py

**Comment by jgoedbloed** [comment]
Hi Dusan,

Thanks for looking after. I have checked, it happens with all templates I'm trying to link.
I have checked for typos but all seems OK. I did an additional test:

```
      local_action:
        module: zabbix_host
        server_url: "{{ zabbix_api_server_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_password }}"
        host_name: "{{ ansible_hostname }}"
        state: present
        link_templates:
          - "test"
```
![selectie_010](https://user-images.githubusercontent.com/1809856/42203935-8f7b913c-7ea0-11e8-895a-2b7303e033d6.png)

Still get this error:

TASK [Relate Wilfly template in Zabbix] **********************************************************************
```
fatal: [TST-CIV-Wildfly -> localhost]: FAILED! => {"changed": false, "msg": "Template not found: test"}
	to retry, use: --limit @/appserver/ansible/playbooks/wildfly_jmx_user.retry
```

**Comment by D3DeFi** [comment]
Hi, so I've tried to better match your environment, but I am probably still missing something:

- installed CentOS 7 as ansible controller
- installed ansible 2.5.5 with python 2.7.5, pip 10.1 and zabbix-api 0.5.3
- still running zabbix-server 3.4.11 (on MySQL 5.7) from previous test
- created new empty host ansible-test01 (nothing linked, no items, no triggers):
![image](https://user-images.githubusercontent.com/9269600/42207055-365f5486-7ea9-11e8-97db-e752704ad615.png)
- created new empty template named "test" and added it to groups "Linux Servers"
- run `ansible-playbook site.yml`:
```yaml
- hosts: ansible-test01
  vars:
    zabbix_api_server_url: "http://10.10.10.1/zabbix"
    zabbix_api_user: Admin
    zabbix_api_password: PASSWORD

  tasks:
    - name: configure host in zabbix
      local_action:
        module: zabbix_host
        server_url: "{{ zabbix_api_server_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_password }}"
        host_name: "{{ ansible_hostname }}"
        state: present
        link_templates:
          - "test"
```

Also, I've scrolled through zabbix-server changelogs for versions 3.4.8 to 3.4.11 and haven't found anything template related at the first glimpse. Btw, do your zabbix-server logs show something when ansible fails? What about the verbose output for ansible-playbook (-vvv)?

**Comment by jgoedbloed** [comment]
Hi,
I have compared your versions with mine:
- All servers are CentOS 7.
- Zabbix server is 3.4.8-1 (from zabbix repository)
- Ansible 2.5.5
- Python 2.7.5

Output from ansible verbose run:
```
Using module file /usr/lib/python2.7/site-packages/ansible/modules/monitoring/zabbix/zabbix_host.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c '/usr/bin/python2 && sleep 0'
fatal: [TST-CIV-Wildfly -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "description": null, 
            "force": true, 
            "host_groups": null, 
            "host_name": "tst-civ-wildfly", 
            "http_login_password": null, 
            "http_login_user": null, 
            "interfaces": null, 
            "inventory_mode": null, 
            "inventory_zabbix": null, 
            "ipmi_authtype": null, 
            "ipmi_password": null, 
            "ipmi_privilege": null, 
            "ipmi_username": null, 
            "link_templates": [
                "test"
            ], 
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "login_user": "ansible", 
            "proxy": null, 
            "server_url": "http://ip_of_zabbix_server/zabbix", 
            "state": "present", 
            "status": "enabled", 
            "timeout": 10, 
            "tls_accept": 1, 
            "tls_connect": 1, 
            "tls_issuer": null, 
            "tls_psk": null, 
            "tls_psk_identity": null, 
            "tls_subject": null, 
            "validate_certs": true, 
            "visible_name": null
        }
    }, 
    "msg": "Template not found: test"
}
	to retry, use: --limit @/appserver/ansible/playbooks/wildfly_jmx_user.retry
```
I have hidden the server_url from the output above.

When running the ansible playbook, I don't see anything odd in the Zabbix server log.

The only thing I noticed, that I when saving a template in Zabbix and open the template afterwards, the Visible Name is empty.

**Comment by D3DeFi** [comment]
I will try to setup zabbix-server with exact version 3.4.8-1 on CentOS 7 later, when I have the time. So far I was running 3.4.11-1 on Ubuntu 16. Maybe it will show me something then :)

P.S. I am getting the same weird behavior with missing Visible name after template creation on 3.4.11-1

**Comment by jgoedbloed** [comment]
Thanks for digging in.
I did a capture of the HTTP traffic between ansible and the zabbix server for this specific task.
I see two post requests: one to log in and the second to retrieve the templates. 

(I've anonymized the IP address and username/password)

First post request:
```
POST /zabbix/api_jsonrpc.php HTTP/1.1
Accept-Encoding: identity
Content-Length: 114
Host: aa.bb.cc.dd
Content-Type: application/json-rpc
Connection: close
User-Agent: python/zabbix_api

{"params": {"password": "secret", "user": "username"}, "jsonrpc": "2.0", "method": "user.login", "id": 0}HTTP/1.1 200 OK
Date: Thu, 05 Jul 2018 11:44:23 GMT
Server: Apache/2.4.6 (CentOS) PHP/5.4.16
X-Powered-By: PHP/5.4.16
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000
Content-Length: 68
Connection: close
Content-Type: application/json

{"jsonrpc":"2.0","result":"6b43b35bebc9075bcd82edac22c9b92f","id":0}
```
Second POST request:
```
POST /zabbix/api_jsonrpc.php HTTP/1.1
Accept-Encoding: identity
Content-Length: 173
Host: aa.bb.cc.dd
Content-Type: application/json-rpc
Connection: close
User-Agent: python/zabbix_api

{"params": {"filter": {"host": "Template JMX Wildfly"}, "output": "extend"}, "jsonrpc": "2.0", "method": "template.get", "auth": "6b43b35bebc9075bcd82edac22c9b92f", "id": 1}HTTP/1.1 200 OK
Date: Thu, 05 Jul 2018 11:44:23 GMT
Server: Apache/2.4.6 (CentOS) PHP/5.4.16
X-Powered-By: PHP/5.4.16
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: POST
Access-Control-Max-Age: 1000
Content-Length: 36
Connection: close
Content-Type: application/json

{"jsonrpc":"2.0","result":[],"id":1}
```
I think in the second post request something goes wrong as the value of the host seems to be the template name?

**Comment by D3DeFi** [comment]
Hi @jurgeng74. I was successful in mirroring your environment, but I still wasn't able to reproduce the error you are receiving:
```CentOS Linux release 7.5.1804 (Core)
Apache/2.4.6 (CentOS) PHP/5.4.16
ansible==2.5.5
zabbix-api==0.5.3
zabbix-server-mysql-3.4.8-1.el7.x86_64
zabbix-web-3.4.8-1.el7.noarch
zabbix-web-mysql-3.4.8-1.el7.noarch
```
This is my playbook:
```yaml
- hosts: all
  vars:
    zabbix_api_server_url: "http://****/zabbix"
    zabbix_api_user: ****
    zabbix_api_password: ****

  tasks:
    - name: configure host in zabbix
      local_action:
        module: zabbix_host
        server_url: "{{ zabbix_api_server_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_password }}"
        host_name: '{{ ansible_hostname }}'
        visible_name: '{{ ansible_hostname }}'
        host_groups:
          - Linux servers
          - Virtual machines
        link_templates:
          - Template OS Linux
        status: enabled
        state: present
        inventory_mode: disabled
        interfaces:
          - type: 1
            main: 1
            useip: 0
            ip: ""
            dns: "{{ ansible_hostname }}"
            port: 10050

    - name: configure host in zabbix
      local_action:
        module: zabbix_host
        server_url: "{{ zabbix_api_server_url }}"
        login_user: "{{ zabbix_api_user }}"
        login_password: "{{ zabbix_api_password }}"
        host_name: "{{ ansible_hostname }}"
        state: present
        link_templates:
          - "test1"
```

And this is output from second task with triple verbose flag (-vvv):
```yaml
changed: [ansible-centos01 -> localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "description": null,
            "force": true,
            "host_groups": null,
            "host_name": "ansible-centos01",
            "http_login_password": null,
            "http_login_user": null,
            "interfaces": null,
            "inventory_mode": null,
            "inventory_zabbix": null,
            "ipmi_authtype": null,
            "ipmi_password": null,
            "ipmi_privilege": null,
            "ipmi_username": null,
            "link_templates": [
                "test1"
            ],
            "login_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "login_user": "****",
            "proxy": null,
            "server_url": "****",
            "state": "present",
            "status": "enabled",
            "timeout": 10,
            "tls_accept": 1,
            "tls_connect": 1,
            "tls_issuer": null,
            "tls_psk": null,
            "tls_psk_identity": null,
            "tls_subject": null,
            "validate_certs": true,
            "visible_name": null
        }
    },
    "result": "Successfully update host ansible-centos01 () and linked with template '['test1']'"
}
```
Do you possibly have a chance to setup new testing zabbix-server and run your playbook against it?

Btw, the API call you've mentioned earlier is actually correct. [See the documentation](https://www.zabbix.com/documentation/3.4/manual/api/reference/template/get)
