### ISSUE TITLE
jinja keyword collision for variable names

### ISSUE THREAD

**Issue by zioproto** [ansible/ansible#41955]
##### SUMMARY

k8s_raw fails using jinja default filter to default undefined variables

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
k8s_raw

##### ANSIBLE VERSION

```
ansible 2.6.0rc4
(python 3)
```

##### STEPS TO REPRODUCE
```
---
- name: K8s
  hosts: localhost
  tasks:
  - name: Create namespace
    k8s:
      name: "{{ namespace | default('horizontesting123', true) }}"
      api_version: v1
      kind: Namespace
      state: present
```
This will fail, because the `name:` does not get the default value.

```
TASK [Create namespace] *****************************************************************************************************************************************************************************************
task path: /Users/proto/SORGENTI/SWITCH-openstack-horizon-k8s-deployment/ansible/test.yaml:7
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: proto
<127.0.0.1> EXEC /bin/sh -c 'echo ~proto && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/proto/.ansible/tmp/ansible-tmp-1530002441.681397-275101092917815 `" && echo ansible-tmp-1530002441.681397-275101092917815="` echo /Users/proto/.ansible/tmp/ansible-tmp-1530002441.681397-275101092917815 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT /Users/proto/.ansible/tmp/ansible-local-308812tchkxm/tmpco_jq671 TO /Users/proto/.ansible/tmp/ansible-tmp-1530002441.681397-275101092917815/k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/proto/.ansible/tmp/ansible-tmp-1530002441.681397-275101092917815/ /Users/proto/.ansible/tmp/ansible-tmp-1530002441.681397-275101092917815/k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python/bin/python3.6 /Users/proto/.ansible/tmp/ansible-tmp-1530002441.681397-275101092917815/k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/proto/.ansible/tmp/ansible-tmp-1530002441.681397-275101092917815/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/10/99r84g5d0_n5ct1248_dmtgh00012p/T/ansible__6rt22sd/ansible_modlib.zip/ansible/module_utils/k8s/raw.py", line 111, in perform_action
    existing = resource.get(name=name, namespace=namespace)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/openshift/dynamic/client.py", line 33, in inner
    raise api_exception(e)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": 400,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "host": null,
            "key_file": null,
            "kubeconfig": null,
            "password": null,
            "ssl_ca_cert": null,
            "username": null,
            "verify_ssl": null
        }
    },
    "msg": "Failed to retrieve requested object: b'400 Bad Request'",
    "reason": "Bad Request",
    "status": 400
}
	to retry, use: --limit @/Users/proto/SORGENTI/SWITCH-openstack-horizon-k8s-deployment/ansible/test.retry
```

I have found that doing:
```
---
- name: K8s
  hosts: localhost
  tasks:
  - name: Create namespace
    k8s:
      name: "horizontesting123"
      api_version: v1
      kind: Namespace
      state: present
```
or 
```
---
- name: K8s
  hosts: localhost
  vars:
     namespace: mytest234
  tasks:
  - name: Create namespace
    k8s:
      name: "{{ namespace }}"
      api_version: v1
      kind: Namespace
      state: present
```
then everything works as expected.

##### EXPECTED RESULTS

It looks like the filter `"{{ namespace | default('horizontesting123', true) }}"` does not work in the `name`. Not sure if this is an ansible bug or a k8s_raw module bug. Is there anything wrong in using the default filter there of an undefined variable ?

I would expect the everything to work when using the jinja filter to default undefined variables.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/_k8s_raw.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/_k8s_raw.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
Does this occur if you use the full definition like so:

```yaml
---
- name: K8s
  hosts: localhost
  tasks:
  - name: Create namespace
    k8s:
      definition:
        metadata:
          name: "{{ namespace | default('horizontesting123', true) }}"
        apiVersion: v1
        kind: Namespace
      state: present
```

**Comment by zioproto** [comment]
Yes the problem occurs also when using the extended `definition`.

Here how to reproduce the problem.

This version works correctly:
```
---
- name: K8s
  hosts: localhost
  tasks:
  - name: Create namespace
    k8s:
      kubeconfig: /Users/proto/.kube/config
      definition:
        metadata:
          name: "horizontesting123"
        kind: Namespace

```

But this version fails:
```
---
- name: K8s
  hosts: localhost
  tasks:
  - name: Create namespace
    k8s:
      kubeconfig: /Users/proto/.kube/config
      definition:
        metadata:
          name: "{{ namespace | default('debugdebug123', true) }}"
        kind: Namespace
```

With the following output:
```
TASK [Create namespace] **********************************************************************************************************************************************************************************************************************************
task path: /Users/proto/SORGENTI/SWITCH-openstack-horizon-k8s-deployment/ansible/test2.yaml:5
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: proto
<127.0.0.1> EXEC /bin/sh -c 'echo ~proto && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/proto/.ansible/tmp/ansible-tmp-1530019222.39-43013695408546 `" && echo ansible-tmp-1530019222.39-43013695408546="` echo /Users/proto/.ansible/tmp/ansible-tmp-1530019222.39-43013695408546 `" ) && sleep 0'
Using module file /usr/local/lib/python2.7/site-packages/ansible/modules/clustering/k8s/k8s.py
<127.0.0.1> PUT /Users/proto/.ansible/tmp/ansible-local-15468mi9F9J/tmp1MncYR TO /Users/proto/.ansible/tmp/ansible-tmp-1530019222.39-43013695408546/k8s.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/proto/.ansible/tmp/ansible-tmp-1530019222.39-43013695408546/ /Users/proto/.ansible/tmp/ansible-tmp-1530019222.39-43013695408546/k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/local/opt/python@2/bin/python2.7 /Users/proto/.ansible/tmp/ansible-tmp-1530019222.39-43013695408546/k8s.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/proto/.ansible/tmp/ansible-tmp-1530019222.39-43013695408546/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/var/folders/10/99r84g5d0_n5ct1248_dmtgh00012p/T/ansible_mivhMq/ansible_modlib.zip/ansible/module_utils/k8s/raw.py", line 111, in perform_action
    existing = resource.get(name=name, namespace=namespace)
  File "/usr/local/lib/python2.7/site-packages/openshift/dynamic/client.py", line 33, in inner
    raise api_exception(e)

fatal: [localhost]: FAILED! => {
    "changed": false,
    "error": 400,
    "invocation": {
        "module_args": {
            "api_key": null,
            "cert_file": null,
            "context": null,
            "host": null,
            "key_file": null,
            "kubeconfig": "/Users/proto/.kube/config",
            "password": null,
            "ssl_ca_cert": null,
            "username": null,
            "verify_ssl": null
        }
    },
    "msg": "Failed to retrieve requested object: 400 Bad Request",
    "reason": "Bad Request",
    "status": 400
}
	to retry, use: --limit @/Users/proto/SORGENTI/SWITCH-openstack-horizon-k8s-deployment/ansible/test2.retry
```
