### ISSUE TITLE
lvol: fails in check mode if VG is not existing

### ISSUE THREAD

**Issue by bigon** [ansible/ansible#41971]
##### SUMMARY

When running the playbook that should create a LVM VG and a LV in check mode, the lvol resource is failing if the VG doesn't exists yet

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

lvol
##### ANSIBLE VERSION

```
ansible-2.5.3 from RHEL7
```

##### OS / ENVIRONMENT

RHEL7
##### STEPS TO REPRODUCE

```yaml
- name: Create the VG docker
  lvg:
    vg: vgdocker
    pvs: /dev/sdc

- name: Create the LV docker
  lvol:
    vg: vgdocker
    lv: lvdocker
    size: 40G
```

##### EXPECTED RESULTS

The run will continue in check mode instead of failing
##### ACTUAL RESULTS

The run fails if the VG is not present

```
fatal: [foo.example.com]: FAILED! => {"changed": false, "err": "  Volume group \"vgdocker\" not found\n  Cannot process volume group vgdocker\n", "msg": "Volume group vgdocker does not exist.", "rc": 5}
```
