### ISSUE TITLE
vmware_guest 

### ISSUE THREAD

**Issue by webstylesInt** [ansible/ansible#41987]
##### SUMMARY

Running the playboog startes and I get the error
SSH password: 

PLAY [tzhqprdvcm01] ***********************************************************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
 [WARNING]: sftp transfer mechanism failed on [IP]. Use ANSIBLE_DEBUG=1 to see detailed information

 [WARNING]: scp transfer mechanism failed on [IP0]. Use ANSIBLE_DEBUG=1 to see detailed information

 [WARNING]: piped transfer mechanism failed on [IP]. Use ANSIBLE_DEBUG=1 to see detailed information

fatal: [HOSTNAME]: FAILED! => {"msg": "failed to transfer file to /home/user/.ansible/tmp/ansible-local-10971ryCQdf/tmpMSEvas Unknown command: `/bin/sh'/setup.py:\n\nTraceback (most recent call last):\n  File \"/usr/lib/applmgmt/base/bin/vherdrunner\", line 8, in <module>\n    vherdrunner.start(vherdrunner.directories)\n  File \"/usr/lib/applmgmt/base/bin/vherdrunner.py\", line 74, in start\n    execfile(sys.argv[0], childGlobals)\n  File \"/usr/lib/applmgmt/linux_cli/bin/main-shell\", line 11, in <module>\n    sys.exit(cli.main(sys.argv, products=('vherd', 'appliance')))\n  File \"/usr/lib/applmgmt/linux_cli/py/vmware/vherd/linux_cli/cli.py\", line 1480, in main\n    args = p.split(parsedArgs.c) + args\nTypeError: unsupported operand type(s) for +: 'NoneType' and 'list'\n"}

##### ISSUE TYPE

 - Bug Report

##### ANSIBLE VERSION

```
"ansible 2.5.5"
```

##### STEPS TO REPRODUCE

failed to transfer file to /home/user/.ansible/tmp/ansible-local-10971ryCQdf/tmpMSEvas Unknown command: `/bin/sh'/setup.py:\n\nTraceback (most recent call last):\n  File \"/usr/lib/applmgmt/base/bin/vherdrunner\", line 8, in <module>\n    vherdrunner.start(vherdrunner.directories)\n  File \"/usr/lib/applmgmt/base/bin/vherdrunner.py\", line 74, in start\n    execfile(sys.argv[0], childGlobals)\n  File \"/usr/lib/applmgmt/linux_cli/bin/main-shell\", line 11, in <module>\n    sys.exit(cli.main(sys.argv, products=('vherd', 'appliance')))\n  File \"/usr/lib/applmgmt/linux_cli/py/vmware/vherd/linux_cli/cli.py\", line 1480, in main\n    args = p.split(parsedArgs.c) + args\nTypeError: unsupported operand type(s) for +: 'NoneType' and 'list'\n"}

```yaml
- name: Add VMware server
    vmware_guest:

      hostname: "{{vCenter_ip}}"
      username: "{{esxi_user}}"
      password: "{{esxi_pass}}"
      validate_certs: False
      esxi_hostname: "{{esxi_host}}"
      datacenter: "{{ datacenter }}"
      cluster: PROD
      folder: "{{ datacenter }}/vm/{{folder}}"
      name: virtualmachine
      state: poweredon
      disk:
        - size_gb: 80
          type: thin
          datastore: datastore02
        - size_gb: 120
          type: thin
          datastore: datastore01
      hardware:
        memory_mb: 8192
        num_cpus: 2
        num_cpu_cores_per_socket: 2
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
      cdrom:
        type: iso
        iso_path: "[Pdatastore03] Windows Server 2012 R2.ISO"
      networks:
      - name: MY_VLAN
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy

```

##### ACTUAL RESULTS

```

```
