### ISSUE TITLE
Flatpak Module Does Not Support Looping Through Lists

### ISSUE THREAD

**Issue by LukeShortCloud** [ansible/ansible#41996]
##### SUMMARY
The new `flatpak` module does not support providing the `name` argument a list of packages to install. This will should to be included by the 2.7 release as per: https://github.com/ansible/ansible/blob/devel/docs/docsite/rst/porting_guides/porting_guide_2.7.rst#using-a-loop-on-a-package-module-via-squash-actions

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
flatpak

##### ANSIBLE VERSION
```
ansible 2.7.0.dev0 (devel 77526a5036) last updated 2018/06/26 20:56:30 (GMT -500)
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/github/ansible/lib/ansible
  executable location = /home/user/github/ansible/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
Fedora 28

##### STEPS TO REPRODUCE
```yaml
---
- hosts: localhost
  vars:
    flatpak_apps:
      - io.atom.Atom
      - org.libreoffice.LibreOffice
  tasks:
    - name: Enable the official Flatpak repository
      command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install a list of Flatpaks from Flathub
      flatpak:
        name: "{{ flatpak_apps }}"
        state: present
```

##### EXPECTED RESULTS
Both the Atom and LibreOffice Flatpaks should be installed.

##### ACTUAL RESULTS
```
TASK [Install a list of Flatpaks from Flathub] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "command": "/usr/bin/flatpak install --system -y flathub ['io.atom.Atom', 'org.libreoffice.LibreOffice']", "msg": "Failed to execute flatpak command", "rc": 1, "stderr": "error: Invalid id ['io.atom.Atom',: Name can't start with [\n", "stderr_lines": ["error: Invalid id ['io.atom.Atom',: Name can't start with ["], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/tmp/site.retry
```
