### ISSUE TITLE
ovirt_host_pm ignores the 'slot' parameter

### ISSUE THREAD

**Issue by frangdlt** [ansible/ansible#42000]
##### SUMMARY

ovirt_host_pm ignores the 'slot' parameter

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ovirt_host_pm
##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/fran/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```yaml
- name: Configure Power Management
  ovirt_host_pm:
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    address: "{{ pm_ucs_manager }}"
    options:
      suborg: "{{ pm_suborg }}"
      ssl_insecure: "1"
    order: "1"
    username: "{{ pm_user }}"
    password: "{{ pm_pass_user }}"
    type: "cisco_ucs"
    slot: "{{ ansible_hostname }}"
  delegate_to: localhost
```

##### EXPECTED RESULTS

The 'slot' parameter should be populated after checking in oVirt/RHVM web ui.

##### ACTUAL RESULTS

The parameter is not populated; although no error is show when running the playbook  It seems the 'slot' parameter is never used within the ovirt_host_pm module and therefore not used when doing the RHV API call.

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/ovirt/ovirt_host_pm.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/ovirt/ovirt_host_pm.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @machacekondra @mwperina
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by gundalow** [comment]
@frangdlt Would you be able to raise a PR against `ansible/ansible` based on https://github.com/frangdlt/ansible/commit/69f57229dbc0072e92aca23c9eb06740d45f4281 ?

Thanks in advance

**Comment by machacekondra** [comment]
@frangdlt Please send PR based on your commit, it looks OK.

**Comment by frangdlt** [comment]
Hi,

Apologies for not merging the PR earlier, I realized that is in fact wrong. The ovirt Agent struct doesn't have a `slot` field but it's rather implemented using an additional option with the format `slot=SLOTNAME` . Therefore the playbook can easily work if modified to specify `slot` as a part of the options section.

```
- name: Configure Power Management
  ovirt_host_pm:
    auth: "{{ ovirt_auth }}"
    name: "{{ inventory_hostname }}"
    address: "{{ pm_ucs_manager }}"
    options:
      suborg: "{{ pm_suborg }}"
      ssl_insecure: "1"
      slot: "{{ ansible_hostname }}"
    order: "1"
    username: "{{ pm_user }}"
    password: "{{ pm_pass_user }}"
    type: "cisco_ucs"
  delegate_to: localhost
```

I'll MR a new fix with updated documentation instead if that's OK with you.
