### ISSUE TITLE
nxos_acl remark issue

### ISSUE THREAD

**Issue by dmurarasu** [ansible/ansible#42012]
##### SUMMARY

When using nxos_acl if you specify the "remark" parameter the acl sequence is configured as remark even if "action" parameter is set to "permit". 
Don't know if this is the wanted result but the documentation says that "remark" is only used if action set to "remark", the actual description for the remark parameter is: "If action is set to remark, this is the description."

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nxos_acl

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT

Ansible Server: CentOS Linux release 7.5.1804
Device: N9K  running NXOS: version 7.0(3)I6(1)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: dcs
  name: Configure switches
  connection: network_cli
  tasks:
    - nxos_acl:
        name: test_acl
        state: present
        action: permit
        seq: 10
        src: 10.10.10.0/24
        dest: 20.20.20.0/24
        remark: This is a test
        proto: tcp

```

##### EXPECTED RESULTS

ansible-playbook  -i hosts_bkup test.yaml -v

PLAY [Configure switches] *************************************************************************************************

TASK [nxos_acl] ***********************************************************************************************************
changed: [nexus01] => {"changed": true, "commands": ["ip access-list test_acl", "10 permit tcp 10.10.10.0/24 20.20.20.0/24"]}

PLAY RECAP ****************************************************************************************************************
nexus01                    : ok=1    changed=1    unreachable=0    failed=0

##### ACTUAL RESULTS

ansible-playbook  -i hosts_bkup test.yaml -v

PLAY [Configure switches] *************************************************************************************************

TASK [nxos_acl] ***********************************************************************************************************
changed: [nexus01] => {"changed": true, "commands": ["ip access-list test_acl", "10 remark This is a test"]}

PLAY RECAP ****************************************************************************************************************
nexus01                    : ok=1    changed=1    unreachable=0    failed=0

```

```
