### ISSUE TITLE
Win_Updates: failed_updates_count not always returned

### ISSUE THREAD

**Issue by TylerKerrACG** [ansible/ansible#42020]
##### SUMMARY

The documentation for win_updates claims that the "failed_updates_count" return value will always be returned, but that is not the case. Other values that are only returned on success are still present when no changes are made.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

win_updates

##### ANSIBLE VERSION

```
ansible 2.5.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/it/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

Nothing changed.

##### OS / ENVIRONMENT

Running from AWX Docker on Linux.
Controlling Windows 10 machines.

##### STEPS TO REPRODUCE

```yaml
    - name: Install all important updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        log_path: c:\_ansible\wu.txt
        state: installed
        become: yes
        become_method: runas
        become_user: SYSTEM
      register: update_result
```

##### EXPECTED RESULTS

return value included "failed_update_count": 0

##### ACTUAL RESULTS

return value "failed_update_count" is undefined

```
{
    "_ansible_parsed": true,
    "_ansible_no_log": false,
    "filtered_updates": {},
    "installed_update_count": 0,
    "changed": false,
    "reboot_required": false,
    "updates": {},
    "found_update_count": 0
}
```
