### ISSUE TITLE
cloudfront_distribution.py - Error validating distribution origins: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by WaKeMaTTa** [ansible/ansible#42037]
##### SUMMARY
This issue might be related to this PR: #37340

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
cloudfront_distribution

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /home/runner/ansible/tests/ansible.cfg
  configured module search path = [u'/home/runner/ansible/library']
  ansible python module location = /home/runner/ansible/myvenv/local/lib/python2.7/site-packages/ansible
  executable location = /home/runner/ansible/myvenv/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

ANSIBLE_PIPELINING(/home/runner/ansible/tests/ansible.cfg) = True
DEFAULT_HOST_LIST(/home/runner/ansible/tests/ansible.cfg) = [u'/home/runner/ansible/tests/inventory']
DEFAULT_MODULE_PATH(/home/runner/ansible/tests/ansible.cfg) = [u'/home/runner/ansible/library']
DEFAULT_ROLES_PATH(/home/runner/ansible/tests/ansible.cfg) = [u'/home/runner/ansible/roles']

##### OS / ENVIRONMENT

Ubuntu 16.04 LTS

##### STEPS TO REPRODUCE

**`setup-env-for-ansible.sh`**
```shell
#!/bin/bash
set -e

# Create and access to virtual environment
virtualenv myvenv
source myvenv/bin/activate

# Install dependences
install-package --update-new python-dev python-pip python-apt python-apt-common python-boto python-boto3 python-botocore

# Install python requirements
pip install --upgrade boto boto3 botocore
pip install -r requirements.txt

# Access tests folder
cd tests

# Check syntaxis
ansible-playbook -i inventory *.yml --syntax-check
ansible-playbook -i inventory playbook.yml --syntax-check

# Run playbook
ansible-playbook -i inventory playbook.yml -vvvv --skip-tags skip_tests
```

By the way, I downloaded this module https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/cloudfront_distribution.py
and put it in my `library/` folder.

```yaml
# role task
- name: Create CloudFront distribution
  delegate_to: localhost
  cloudfront_distribution:
    state: present
    origins:
      - id: "www.example.com"
        domain_name: "www.example.com"
        s3_origin_access_identity_enabled: yes
        custom_origin_config:
          origin_protocol_policy: match-viewer
          origin_ssl_protocols:
            - TLSv1.2
            - TLSv1.1
            - TLSv1
    default_cache_behavior:
      target_origin_id: "www.example.com"
      forwarded_values:
        allowed_methods:
          items:
            - GET
            - HEAD
            - OPTIONS
```

##### EXPECTED RESULTS

I was expecting to create a CloudFront distribution.

##### ACTUAL RESULTS

It failed because `cloudfront_distribution.py` is broken.

```bash
TASK [../roles/setup-amazon-utilities : Create CloudFront distribution] ********
task path: /home/runner/ansible/roles/setup-amazon-utilities/tasks/main.yml:68
Using module file /home/runner/ansible/library/cloudfront_distribution.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: runner
<localhost> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-tmykciykaqwrotrdbjcgcosmqayoojwl; /usr/bin/python'"'"' && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_1qoVsO/ansible_module_cloudfront_distribution.py", line 1407, in validate_origins
    origin = self.validate_origin(client, all_origins.get(origin.get('domain_name'), {}), origin, default_origin_path)
  File "/tmp/ansible_1qoVsO/ansible_module_cloudfront_distribution.py", line 1465, in validate_origin
    if custom_origin_config.get('origin_ssl_protocols', {}).get('items'):
AttributeError: 'list' object has no attribute 'get'

fatal: [localhost -> localhost]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "alias": null, 
            "aliases": [], 
            "aws_access_key": "AAAAAAAAAAAAAAAAAAAAA", 
            "aws_region": "eu-west-1", 
            "aws_secret_key": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "cache_behaviors": null, 
            "caller_reference": null, 
            "comment": null, 
            "custom_error_responses": null, 
            "default_cache_behavior": {
                "forwarded_values": {
                    "allowed_methods": {
                        "items": [
                            "GET", 
                            "HEAD", 
                            "OPTIONS"
                        ]
                    }
                }, 
                "target_origin_id": "www.example.com"
            }, 
            "default_origin_domain_name": null, 
            "default_origin_path": null, 
            "default_root_object": null, 
            "distribution_id": null, 
            "e_tag": null, 
            "ec2_url": null, 
            "enabled": null, 
            "http_version": null, 
            "ipv6_enabled": null, 
            "logging": null, 
            "origins": [
                {
                    "custom_headers": {
                        "quantity": 0
                    }, 
                    "custom_origin_config": {
                        "h_t_t_p_port": 80, 
                        "h_t_t_p_s_port": 443, 
                        "origin_keepalive_timeout": 5, 
                        "origin_protocol_policy": "match-viewer", 
                        "origin_read_timeout": 30, 
                        "origin_ssl_protocols": [
                            "TLSv1.2", 
                            "TLSv1.1", 
                            "TLSv1"
                        ]
                    }, 
                    "domain_name": "www.example.com", 
                    "id": "www.example.com", 
                    "origin_path": "", 
                    "s3_origin_access_identity_enabled": true
                }
            ], 
            "price_class": null, 
            "profile": null, 
            "purge_aliases": false, 
            "purge_cache_behaviors": false, 
            "purge_custom_error_responses": false, 
            "purge_origins": false, 
            "purge_tags": false, 
            "region": "eu-west-1", 
            "restrictions": null, 
            "security_token": null, 
            "state": "present", 
            "tags": {}, 
            "validate_certs": true, 
            "viewer_certificate": null, 
            "wait": false, 
            "wait_timeout": 1800, 
            "web_acl_id": null
        }
    }, 
    "msg": "Error validating distribution origins: 'list' object has no attribute 'get'"
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/cloudfront_distribution.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/cloudfront_distribution.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @willthames @wilvk
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by WaKeMaTTa** [comment]
It effects also to 2.6.x

**Comment by jpmontez** [comment]
@WaKeMaTTa https://github.com/ansible/ansible/blob/25ae4f2b73151eb88981dc80719b8fc1bcc8481a/lib/ansible/modules/cloud/amazon/cloudfront_distribution.py#L976-L993

The `origin_ssl_protocols` dictionary is expecting this structure from your example.

```
    origins:
      - id: "www.example.com"
        domain_name: "www.example.com"
        custom_origin_config:
          origin_ssl_protocols:
            items:
              - TLSv1.2
              - TLSv1.1
              - TLSv1
```
