### ISSUE TITLE
lstrib_blocks setting in jinja templates in not working.

### ISSUE THREAD

**Issue by ishantanu** [ansible/ansible#42032]
##### SUMMARY
Adding `#jinja2: lstrip_blocks: True` to the start of the jinja2 template is not working at all. It is not even detecting it as a special line. Instead after running the playbook, this line gets printed as is without doing anything for indentation.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /root/ansible-celera/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
[defaults]
hostfile = ./inventory
forks = 15
```

##### OS / ENVIRONMENT

NA

##### STEPS TO REPRODUCE

Add `#jinja2: lstrip_blocks: True` on the very first line of jinja2 template. Example format of templates - 
```
config.j2:

#jinja2: lstrip_blocks: True
{# BACKEND CONIGURATION #}
{% include 'backend.cfg.j2' %}
```

```
backend.cfg.j2
#jinja2: lstrip_blocks: True
{... other details ... }
```

##### EXPECTED RESULTS
Indentation issue should be fixed where extra spaces are added while using for and if.

##### ACTUAL RESULTS
Not working at all.

**Comment by bcoca** [comment]
@iamShantanu101 I cannot reproduce with the example give, can you provide a full example with expected/actual results?

Also, this only works for templates read by Ansible, it won't work if you load the file  using a Jinja2 include.

needs_info

**Comment by samdoran** [comment]
@iamShantanu101 I am not able to duplicate this. It seems to be working as intended. You do not need to put the `lstrip_blocks` in the included template. My reproducer:

```yaml
- name: Local testing playbook
  hosts: localhost
  connection: local
  gather_facts: no
  become: no

  vars:
    things:
      - one
      - two
      - three

  tasks:
    - template:
        src: templates/test.j2
        dest: templates/test.txt
```

test.j2:
```
#jinja2: lstrip_blocks: True
{# BACKEND CONIGURATION #}
{% include 'backend.cfg.j2' %}
```

backend.cfg.j2:
```
My list:
    {% for item in things %}
    {{ item }}
    {% endfor %}
```

Rendered output:
```
My list:
    one
    two
    three
```

If I omit `#jinja2: lstrip_blocks: True` from `test.j2`, then the rendered output looks like this:
```
My list:
        one
        two
        three
    

```
