### ISSUE TITLE
synchronize_module rsync:// not working

### ISSUE THREAD

**Issue by ThoTischner** [ansible/ansible#42039]
##### SUMMARY
Ansible synchronize not working with rsync:// dest or src

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
synchronize_module

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /home/tti/nm-ansible/ansible.cfg
  configured module search path = [u'/home/tti/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

##### CONFIGURATION

```
ANSIBLE_SSH_ARGS(/home/tti/nm-ansible/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=60s -o UserKnownHostsFile=/dev/null
DEFAULT_ROLES_PATH(/home/tti/nm-ansible/ansible.cfg) = [u'/home/tti/nm-ansible/roles']
DEFAULT_SCP_IF_SSH(/home/tti/nm-ansible/ansible.cfg) = True
HOST_KEY_CHECKING(/home/tti/nm-ansible/ansible.cfg) = False
```

##### STEPS TO REPRODUCE

```yaml
- hosts: "{{hosts|default('*')}}"
  gather_facts: false
  tasks:
    - name: Rsync files from remote to remote hosts
      synchronize:
        src: /tmp
        dest: 'rsync://bla.blub.com/tmp/'
        rsync_opts: "{{sync_rsync_opts|default(omit)}}"
      delegate_to: "{{inventory_hostname}}"
```

##### EXPECTED RESULTS
working

##### ACTUAL RESULTS
```
fatal: [vmxxx.xxxx.lan -> vmxxxxxxxxx.lan]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --out-format=<<CHANGED>>%i %n%L /tmp/xxx.sql rsync://vmxxx.xxxx.lan/tmp/xxx.sql", "msg": "@ERROR: Unknown module 'tmp'\nrsync error: error starting client-server protocol (code 5) at main.c(1516) [sender=3.0.9]\n", "rc": 5}
```

Issue was already reported and autoclosed: https://github.com/ansible/ansible/issues/25072
