### ISSUE TITLE
VMware: vsandatastore created with size 0

### ISSUE THREAD

**Issue by umrikar** [ansible/ansible#42034]
##### SUMMARY

```
when all disks on ESXI hosts are SSD's we are able to create vsandatastore where none of  the disk are used and vsandastore size is zero
```
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

```
   vmware_vsan_cluster
```
##### ANSIBLE VERSION

```
2.5
```

##### STEPS TO REPRODUCE

```
- name: Configure VMware VSAN Cluster
  hosts: deploy_node
  gather_facts: False
  tags:
    - vsan
  tasks:
    - name: Configure VSAN on first host
      vmware_vsan_cluster:
         hostname: "{{ groups['esxi'][0] }}"
         username: "{{ esxi_username }}"
         password: "{{ site_password }}"
      register: vsan_cluster

    - name: Configure VSAN on remaining hosts
      vmware_vsan_cluster:
         hostname: "{{ item }}"
         username: "{{ esxi_username }}"
         password: "{{ site_password }}"
         cluster_uuid: "{{ vsan_cluster.cluster_uuid }}"
      with_items: "{{ groups['esxi'][1:] }}

```

##### EXPECTED RESULTS

```
We have created vsan using above playbook and ablew to create vsan when one of disk attached to ESXI host is HDD but when we have ESXI hosts where all disks are SSD's that time vsan datastore got created with size0
```
##### ACTUAL RESULTS

```

```
