### ISSUE TITLE
VMware: VM is created but ISO is not mounted, Vsphere 6

### ISSUE THREAD

**Issue by michaelhajjar** [ansible/ansible#42047]
##### SUMMARY
When trying to create a vm with the vmware_guest module (from a template), the VM gets created but the iso is not mounted.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`vmware_guest.py`
##### ANSIBLE VERSION

```
2.5.5-1
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

Running Ansible from Centos 7 against VMWare Vsphere 6

##### STEPS TO REPRODUCE

```
---
- name: Create a VM from a template
  vmware_guest:
    hostname: server
    username: user
    password: pass
    validate_certs: no
    folder: /
    name: testvm
    datacenter: test
    cluster: testcluster
    state: poweredon
    template: centos7_template
    disk:
    - size_gb: 50
      type: thin
      datastore: datastorcluster
    hardware:
      memory_mb: 2048
      num_cpus: 1
      num_cpu_cores_per_socket: 1
      scsi: paravirtual
    cdrom:
      type: iso
      iso_path: "[ISO_SHARE] /iso/path/file.iso"
    networks:
    - name: nic
    wait_for_ip_address: yes
  delegate_to: localhost
  register: deploy

```

##### EXPECTED RESULTS

The VM needs to be created and the ISO needs to be mounted. This is very important because we are using cloud-init iso for the intial configuration of our virtual machines.

##### ACTUAL RESULTS

The VM was created but the ISO was not mounted. We are using Vsphere 6.
