### ISSUE TITLE
cloud_init_persist not work

### ISSUE THREAD

**Issue by peruchi** [ansible/ansible#42053]
##### SUMMARY

When you add the option cloud_init_persist, to persist the information added by the cloud init occore an error, which is not supported by the module, but the documentation: https://docs.ansible.com/ansible/latest/modules/ovirt_vms_module.html says that it's possible.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

Module: ovirt_vms

##### ANSIBLE VERSION

```
2.5.5
```

##### CONFIGURATION

Default

##### OS / ENVIRONMENT

Running Ansible from Centos 7

##### STEPS TO REPRODUCE

```yaml
- name: Run VM with cloud init
  ovirt_vms:
    auth: "{{ OVIRT_AUTH }}"
    name: "{{ OVIRT_NAME_VM }}"
    template: centos75-cloudinit
    cluster: Temporario
    memory: 2GiB
    timezone: America/Sao_Paulo
    high_availability: true
    cpu_cores: 2
    cpu_sockets: 1
    nics:
      - name: eth0
        profile_name: vlan60
    cloud_init:
      nic_boot_protocol: static
      nic_ip_address: 192.168.60.203
      nic_netmask: 255.255.255.0
      nic_gateway: 192.168.60.1
      dns_search: example.com
      dns_servers: 192.168.60.1
      nic_name: eth0
      nic_on_boot: true
      host_name: "{{ OVIRT_NAME_VM }}. example.com"
      user_name: admin
      root_password: 'xxxxx'
    cloud_init_persist: true
```

##### EXPECTED RESULTS

Persist as information added by cloud init

##### ACTUAL RESULTS

```
 "msg": "Unsupported parameters for (ovirt_vms) module: cloud_init_persist. Supported parameters include: auth,boot_devices,cd_iso,clone,clone_permissions,cloud_init,cloud_init_nics,cluster,comment,cpu_cores,cpu_shares,cpu_sockets,delete_protected,description,disks,fetch_nested,force,high_availability,host,id,initrd_path,instance_type,kernel_params,kernel_path,memory,memory_guaranteed,name,nested_attributes,nics,operating_system,poll_interval,serial_policy,serial_policy_value,state,stateless,sysprep,template,template_version,timeout,timezone,type,use_latest_template_version,wait"

```
