### ISSUE TITLE
Kubernetes jobs can't be re-run

### ISSUE THREAD

**Issue by ehelms** [ansible/ansible#42063]
##### SUMMARY

When defining a Kubernetes job and deploying with the k8s module, the job fails to patch correctly and errors out.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

k8s
k8s_raw

##### ANSIBLE VERSION

```
ansible 2.6.0rc5.dev0
  config file = /home/ehelms/workspace/upstream/forklift/containers/ansible.cfg
  configured module search path = ['/home/ehelms/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.2 (default, Sep  1 2017, 12:03:48) [GCC 7.1.1 20170802 (Red Hat 7.1.1-7)]
```

##### STEPS TO REPRODUCE

```yaml
---
apiVersion: batch/v1
kind: Job
metadata:
  name: certificates
  namespace: "{{ project_name }}"
  labels:
    app: foreman
    service: certificates
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: client
    spec:
      containers:
        - name: certificates
          securityContext: {}
          state: present
          volumeMounts:
            - readOnly: false
              mountPath: /var/www/html/pub/
              name: pub-data
          command:
            - ansible-playbook
          args:
            - build.yml
            - deploy.yml
          image: "{{ registry }}/certificates:latest"
          env:
            - name: APPLICATION_HOSTNAME
              value: "{{ application_hostname }}"
      serviceAccount: anyuid
      serviceAccountName: anyuid
      volumes:
        - name: pub-data
          persistentVolumeClaim:
            claimName: pub-data
      restartPolicy: Never
```

##### ACTUAL RESULTS

```
TASK [certificates : certificate jobs] ****************************************************************************************************************************************************************************
task path: /home/ehelms/workspace/upstream/forklift/containers/deploy/certificates/tasks/main.yml:9
File lookup using /home/ehelms/workspace/upstream/forklift/containers/deploy/certificates/templates/certificates.job.yaml as file
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: ehelms
<localhost> EXEC /bin/sh -c 'echo ~ehelms && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/ehelms/.ansible/tmp/ansible-tmp-1530207760.8899233-37915418060210 `" && echo ansible-tmp-1530207760.8899233-37915418060210="` echo /home/ehelms/.ansible/tmp/ansible-tmp-1530207760.8899233-37915418060210 `" ) && sleep 0'
Using module file /usr/local/lib/python3.6/site-packages/ansible/modules/clustering/k8s/_k8s_raw.py
<localhost> PUT /home/ehelms/.ansible/tmp/ansible-local-32178iloctjdd/tmpl0sw4dsr TO /home/ehelms/.ansible/tmp/ansible-tmp-1530207760.8899233-37915418060210/_k8s_raw.py
<localhost> EXEC /bin/sh -c 'chmod u+x /home/ehelms/.ansible/tmp/ansible-tmp-1530207760.8899233-37915418060210/ /home/ehelms/.ansible/tmp/ansible-tmp-1530207760.8899233-37915418060210/_k8s_raw.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /home/ehelms/.ansible/tmp/ansible-tmp-1530207760.8899233-37915418060210/_k8s_raw.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /home/ehelms/.ansible/tmp/ansible-tmp-1530207760.8899233-37915418060210/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_cJNPUZ/ansible_modlib.zip/ansible/module_utils/k8s/raw.py", line 171, in perform_action
    k8s_obj = resource.patch(definition, name=name, namespace=namespace).to_dict()
  File "/usr/lib/python2.7/site-packages/openshift/dynamic/client.py", line 33, in inner
    raise api_exception(e)

failed: [localhost] (item=certificates) => changed=false 
  error: 422
  invocation:
    module_args:
      api_key: null
      cert_file: null
      context: null
      host: null
      key_file: null
      kubeconfig: null
      password: null
      ssl_ca_cert: null
      username: null
      verify_ssl: null
  item: certificates
  msg: |-
    Failed to patch object: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Job.batch \"certificates\" is invalid: spec.template: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"service\":\"client\", \"app\":\"foreman\", \"controller-uid\":\"756221e5-7aef-11e8-b981-5254006454de\", \"job-name\":\"certificates\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:\"pub-data\", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(0xc42af18240), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:\"certificates\", Image:\"quay.io/foreman/certificates:latest\", Command:[]string{\"ansible-playbook\"}, Args:[]string{\"build.yml\", \"deploy.yml\"}, WorkingDir:\"\", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:\"APPLICATION_HOSTNAME\", Value:\"foreman.192.168.42.116.nip.io\", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:\"pub-data\", ReadOnly:false, MountPath:\"/var/www/html/pub/\", SubPath:\"\", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:\"/dev/termination-log\", TerminationMessagePolicy:\"File\", ImagePullPolicy:\"Always\", SecurityContext:(*core.SecurityContext)(0xc4370ee280), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:\"Never\", TerminationGracePeriodSeconds:(*int64)(0xc4340c5088), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:\"ClusterFirst\", NodeSelector:map[string]string(nil), ServiceAccountName:\"anyuid\", AutomountServiceAccountToken:(*bool)(nil), NodeName:\"\", SecurityContext:(*core.PodSecurityContext)(0xc4370ee2c0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:\"\", Subdomain:\"\", Affinity:(*core.Affinity)(nil), SchedulerName:\"default-scheduler\", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:\"\", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil)}}: field is immutable","reason":"Invalid","details":{"name":"certificates","group":"batch","kind":"Job","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:\"\", GenerateName:\"\", Namespace:\"\", SelfLink:\"\", UID:\"\", ResourceVersion:\"\", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{\"job-name\":\"certificates\", \"service\":\"client\", \"app\":\"foreman\", \"controller-uid\":\"756221e5-7aef-11e8-b981-5254006454de\"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:\"\"}, Spec:core.PodSpec{Volumes:[]core.Volume{core.Volume{Name:\"pub-data\", VolumeSource:core.VolumeSource{HostPath:(*core.HostPathVolumeSource)(nil), EmptyDir:(*core.EmptyDirVolumeSource)(nil), GCEPersistentDisk:(*core.GCEPersistentDiskVolumeSource)(nil), AWSElasticBlockStore:(*core.AWSElasticBlockStoreVolumeSource)(nil), GitRepo:(*core.GitRepoVolumeSource)(nil), Secret:(*core.SecretVolumeSource)(nil), NFS:(*core.NFSVolumeSource)(nil), ISCSI:(*core.ISCSIVolumeSource)(nil), Glusterfs:(*core.GlusterfsVolumeSource)(nil), PersistentVolumeClaim:(*core.PersistentVolumeClaimVolumeSource)(0xc42af18240), RBD:(*core.RBDVolumeSource)(nil), Quobyte:(*core.QuobyteVolumeSource)(nil), FlexVolume:(*core.FlexVolumeSource)(nil), Cinder:(*core.CinderVolumeSource)(nil), CephFS:(*core.CephFSVolumeSource)(nil), Flocker:(*core.FlockerVolumeSource)(nil), DownwardAPI:(*core.DownwardAPIVolumeSource)(nil), FC:(*core.FCVolumeSource)(nil), AzureFile:(*core.AzureFileVolumeSource)(nil), ConfigMap:(*core.ConfigMapVolumeSource)(nil), VsphereVolume:(*core.VsphereVirtualDiskVolumeSource)(nil), AzureDisk:(*core.AzureDiskVolumeSource)(nil), PhotonPersistentDisk:(*core.PhotonPersistentDiskVolumeSource)(nil), Projected:(*core.ProjectedVolumeSource)(nil), PortworxVolume:(*core.PortworxVolumeSource)(nil), ScaleIO:(*core.ScaleIOVolumeSource)(nil), StorageOS:(*core.StorageOSVolumeSource)(nil)}}}, InitContainers:[]core.Container(nil), Containers:[]core.Container{core.Container{Name:\"certificates\", Image:\"quay.io/foreman/certificates:latest\", Command:[]string{\"ansible-playbook\"}, Args:[]string{\"build.yml\", \"deploy.yml\"}, WorkingDir:\"\", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar{core.EnvVar{Name:\"APPLICATION_HOSTNAME\", Value:\"foreman.192.168.42.116.nip.io\", ValueFrom:(*core.EnvVarSource)(nil)}}, Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceList(nil)}, VolumeMounts:[]core.VolumeMount{core.VolumeMount{Name:\"pub-data\", ReadOnly:false, MountPath:\"/var/www/html/pub/\", SubPath:\"\", MountPropagation:(*core.MountPropagationMode)(nil)}}, VolumeDevices:[]core.VolumeDevice(nil), LivenessProbe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil), TerminationMessagePath:\"/dev/termination-log\", TerminationMessagePolicy:\"File\", ImagePullPolicy:\"Always\", SecurityContext:(*core.SecurityContext)(0xc4370ee280), Stdin:false, StdinOnce:false, TTY:false}}, RestartPolicy:\"Never\", TerminationGracePeriodSeconds:(*int64)(0xc4340c5088), ActiveDeadlineSeconds:(*int64)(nil), DNSPolicy:\"ClusterFirst\", NodeSelector:map[string]string(nil), ServiceAccountName:\"anyuid\", AutomountServiceAccountToken:(*bool)(nil), NodeName:\"\", SecurityContext:(*core.PodSecurityContext)(0xc4370ee2c0), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:\"\", Subdomain:\"\", Affinity:(*core.Affinity)(nil), SchedulerName:\"default-scheduler\", Tolerations:[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:\"\", Priority:(*int32)(nil), DNSConfig:(*core.PodDNSConfig)(nil)}}: field is immutable","field":"spec.template"}]},"code":422}
  reason: Unprocessable Entity
  status: 422
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/_k8s_raw.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/_k8s_raw.py)
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
@ehelms is this an issue of idempotence (running the task multiple times with the same arguments), or are you changing the job from one definition to another?

**Comment by ehelms** [comment]
@fabianvf Idempotence, I have things broken into roles, I make a change in say a deployment somewhere, want to re-run the whole she-bang and it fails when it encounters a job definition with the above error.

**Comment by fabianvf** [comment]
@ehelms hmm, I was able to run the job twice without error (return ok- no changes the second time), is it possible that the value of `registry` or `application_hostname` is changing across runs?

**Comment by ehelms** [comment]
I hard coded the values like this and still get the same error:

```
---
apiVersion: batch/v1
kind: Job
metadata:
  name: certificates
  namespace: foreman
  labels:
    app: foreman
    service: certificates
spec:
  template:
    metadata:
      labels:
        app: foreman
        service: client
    spec:
      containers:
        - name: certificates
          securityContext: {}
          state: present
          volumeMounts:
            - readOnly: false
              mountPath: /var/www/html/pub/
              name: pub-data
          command:
            - ansible-playbook
          args:
            - build.yml
            - deploy.yml
          image: "quay.io/foreman/certificates:latest"
          env:
            - name: APPLICATION_HOSTNAME
              value: "foreman.192.168.42.116.nip.io"
      serviceAccount: anyuid
      serviceAccountName: anyuid
      volumes:
        - name: pub-data
          persistentVolumeClaim:
            claimName: pub-data
      restartPolicy: Never
```

With the following:

```
ansible-2 2.6.0rc5.dev0
  config file = /home/ehelms/workspace/upstream/forklift/containers/ansible.cfg
  configured module search path = [u'/home/ehelms/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-2
  python version = 2.7.13 (default, Aug 16 2017, 12:56:26) [GCC 7.1.1 20170802 (Red Hat 7.1.1-7)]
```
```
ehelms@war containers (move-deploy-to-roles)$ pip2 freeze | grep openshift
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
openshift==0.6.1
ehelms@war containers (move-deploy-to-roles)$ pip2 freeze | grep kubernetes
You are using pip version 9.0.3, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
kubernetes==6.0.0
```

Here is where and how I call it -- https://github.com/theforeman/forklift/pull/746/files#diff-865b46875b498c51c1498d11b1efbd3dR16

Which calls -- https://github.com/theforeman/forklift/pull/746/files#diff-b20c52421bf39ab434c4d518db0484a1
