### ISSUE TITLE
[vmware_guest] After deploy VM network is disconnected 

### ISSUE THREAD

**Issue by coom** [ansible/ansible#42064]
##### SUMMARY
When deploying a new VM (cloned from template), VM start with disconnected network, and "Connect at power on" is unchecked.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

DEFAULT_REMOTE_USER(/etc/ansible/ansible.cfg) = ansible

##### OS / ENVIRONMENT

Ansible Host: Debian 9.4 (Stretch)
Template: Ubuntu 16.04 with open-vm-tools version 2:10.0.7-3227872-2ubuntu1
VMWare vCenter 6.5.0.13000 with VMware ESXi, 6.5.0, 8294253 

##### STEPS TO REPRODUCE

Deploy a new VM from the playbook below.

```yaml
---
# get date
- set_fact: creationdate="{{lookup('pipe','date "+%Y/%m/%d %H:%M"')}}"

# Create a VM from a template
- name: create the VM
  vmware_guest:
    hostname: '{{ vsphere_host }}'
    username: '{{ vsphere_user }}'
    password: '{{ vsphere_password }}'
    validate_certs: no
    esxi_hostname: '{{ esxi_host }}'
    datacenter: '{{ vsphere_datacenter }}'
    folder: '{{ vsphere_folder }}'
    name: '{{ inventory_hostname }}'
    state: poweredon
    guest_id: '{{ guest_id }}'
    annotation: "{{ notes }} - {{ creationdate }}"
    disk:
    - size_gb: 150
      type: thin
      datastore: '{{ vsphere_datastore }}'
    networks:
    - name: '{{ guest_network }}'
      ip: '{{ guest_custom_ip }}'
      netmask: '{{ guest_netmask }}'
      gateway: '{{ guest_gateway }}'
      dns_servers:
      - '{{ guest_dns_server }}'
      start_connected: yes
    hardware:
      memory_mb: '{{ guest_memory }}'
      num_cpus: '{{ guest_vcpu }}'
      num_cpu_cores_per_socket: 1
      hotadd_cpu: True
      hotremove_cpu: True
    customization:
      dns_servers:
      - '{{ guest_dns_server }}'
      domain : '{{ guest_domain_name }}'
      hostname: '{{ inventory_hostname }}'
    template: '{{ guest_template }}'
    wait_for_ip_address: yes
  delegate_to: localhost
```

##### EXPECTED RESULTS

Deploy new VM with connected network.

##### ACTUAL RESULTS

VM start with network card disconnected. The box "Connected" and "Connect At Power On" are both unchecked.

```

```
