### ISSUE TITLE
vmware_guest "rename a vm" example doesn't work from the documentation

### ISSUE THREAD

**Issue by jacksonp2008** [ansible/ansible#42084]
##### SUMMARY

vmware_guest "rename a vm" example doesn't work from the documentation

See the example here:  https://docs.ansible.com/ansible/latest/modules/vmware_guest_module.html#vmware-guest-module

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ca-spollockmb1:fs-vmw-control spollock$ ansible --version
ansible 2.6.0
  config file = /Users/spollock/ansible/fs-vmw-control/ansible.cfg
  configured module search path = [u'/Users/spollock/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]

```

##### CONFIGURATION

ca-spollockmb1:fs-vmw-control spollock$ ansible-config dump --only-changed
DEFAULT_HOST_LIST(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = [u'/Users/spollock/ansible/fs-
DEFAULT_REMOTE_PORT(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = spollock
DEFAULT_TIMEOUT(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = 30
RETRY_FILES_ENABLED(/Users/spollock/ansible/fs-vmw-control/ansible.cfg) = False
(END)

##### OS / ENVIRONMENT

ca-spollockmb1:fs-vmw-control spollock$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: OS X 10.11.6 (15G20015)
      Kernel Version: Darwin 15.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: ca-spollockmb1
      User Name: Steven Pollock (spollock)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 8:22

vCenter/ESX 6.5

##### STEPS TO REPRODUCE

```yaml

The vars of interest:
vcprepvmname: "moveme-CHKP-VM1"
vcpreptargetname: "1766-chkp-vm1"

- name: grab the machine uuid
  vmware_guest_facts:
    validate_certs: no
    hostname: "{{ vcenterhostname }}"
    username: "{{ vcusername }}"
    password: "{{ vcpassword }}"
    datacenter: "{{ vcdatacenter }}"
    folder: "{{ vcfolder }}"
    name: "{{ vcprepvmname }}"
  delegate_to: localhost
  register: vmfacts
  tags: prep1

- name: rename the VM
  vmware_guest:
    validate_certs: no
    hostname: "{{ vcenterhostname }}"
    username: "{{ vcusername }}"
    password: "{{ vcpassword }}"
    datacenter: "{{ vcdatacenter }}"
    cluster: "{{ vccluster }}"
    folder: "{{ vcfolder }}"
    uuid: "{{ vmfacts.instance.instance_uuid }}"
    name: "{{ vcpreptargetname }}"
    state: present
  delegate_to: localhost
  tags: prep1

```

##### EXPECTED RESULTS

According to the documentation it should simply rename the guest.

##### ACTUAL RESULTS

```
PLAY [Prep Kit Machine] ******************************************************************************

TASK [prepkitvm : grab the machine uuid] *************************************************************
ok: [localhost -> localhost]

TASK [prepkitvm : rename the VM] *********************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "msg": "Unable to find the datastore with given parameters. This could mean, 1766-chkp-vm1 is a non-existent virtual machine and module tried to deploy it as new virtual machine with no disk. Please specify disks parameter or specify template to clone from."}

PLAY RECAP *******************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by Akasurde** [comment]
@jacksonp2008 Thanks for reporting this issue. I see you are using `instance_uuid ` instead of `hw_product_uuid` 

```yaml
---
- name: issue_42084
  gather_facts: no
  vars_files:
    - vcenter_vars.yml
  vars:
    ansible_python_interpreter: "/usr/bin/env python3"
  hosts: localhost
  tasks:
    - set_fact:
        vm_name: "new_u0001"
        new_vm_name: "rename_new_u0001"
        datacenter: "DC1"

    - name: Get VM "{{ vm_name }}" uuid
      vmware_guest_facts:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        folder: "/{{datacenter}}/vm"
        name: "{{ vm_name }}"
      register: vm_facts

    - name: Rename "{{ vm_name }}" to "{{ new_vm_name }}"
      vmware_guest:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        cluster: "DC1_C1"
        uuid: "{{ vm_facts.instance.hw_product_uuid }}"
        name: "{{ new_vm_name }}"
      delegate_to: localhost
      register: facts
```

console log
```
# ansible-playbook rename_vm.yml -v
PLAY [issue_42084] ******************************************************************************************************************

TASK [set_fact] ****************************************************************************************************************
ok: [localhost] => {"ansible_facts": {"datacenter": "DC1", "new_vm_name": "rename_new_u0001", "vm_name": "new_u0001"}, "changed": false}

TASK [Get VM "new_u0001" uuid] *************************************************************************************************
ok: [localhost] => {"changed": false, "instance": {"annotation": "", "current_snapshot": null, "customvalues": {}, "guest_consolidation_needed": false, "guest_question": null, "guest_tools_status": "guestToolsNotRunning", "guest_tools_version": "10247", "hw_cores_per_socket": 1, "hw_datastores": ["ds_204_2"], "hw_esxi_host": "10.76.33.204", "hw_eth0": {"addresstype": "assigned", "ipaddresses": [], "label": "Network adapter 1", "macaddress": "00:50:56:8c:b8:42", "macaddress_dash": "00-50-56-8c-b8-42", "portgroup_key": "dvportgroup-31", "portgroup_portkey": "15", "summary": "DVSwitch: 50 0c 3a 69 df 78 2c 7b-6e 08 0a 89 e3 a6 31 17"}, "hw_files": ["[ds_204_2] u0001/u0001.vmx", "[ds_204_2] u0001/u0001.nvram", "[ds_204_2] u0001/u0001.vmsd", "[ds_204_2] u0001/vmware.log", "[ds_204_2] u0001/u0001.vmdk"], "hw_folder": "/DC1/vm", "hw_guest_full_name": null, "hw_guest_ha_state": null, "hw_guest_id": null, "hw_interfaces": ["eth0"], "hw_is_template": false, "hw_memtotal_mb": 1024, "hw_name": "new_u0001", "hw_power_status": "poweredOff", "hw_processor_count": 1, "hw_product_uuid": "420cbebb-835b-980b-7050-8aea9b7b0a6d", "hw_version": "vmx-13", "instance_uuid": "500c60a6-b7b4-8ae5-970f-054905246a6f", "ipv4": null, "ipv6": null, "module_hw": true, "snapshots": []}}

TASK [Rename "new_u0001" to "rename_new_u0001"] ********************************************************************************
changed: [localhost -> localhost] => {"changed": true, "instance": {"annotation": "", "current_snapshot": null, "customvalues": {}, "guest_consolidation_needed": false, "guest_question": null, "guest_tools_status": "guestToolsNotRunning", "guest_tools_version": "10247", "hw_cores_per_socket": 1, "hw_datastores": ["ds_204_2"], "hw_esxi_host": "10.76.33.204", "hw_eth0": {"addresstype": "assigned", "ipaddresses": [], "label": "Network adapter 1", "macaddress": "00:50:56:8c:b8:42", "macaddress_dash": "00-50-56-8c-b8-42", "portgroup_key": "dvportgroup-31", "portgroup_portkey": "15", "summary": "DVSwitch: 50 0c 3a 69 df 78 2c 7b-6e 08 0a 89 e3 a6 31 17"}, "hw_files": ["[ds_204_2] u0001/u0001.vmx", "[ds_204_2] u0001/u0001.nvram", "[ds_204_2] u0001/u0001.vmsd", "[ds_204_2] u0001/vmware.log", "[ds_204_2] u0001/u0001.vmdk"], "hw_folder": "/DC1/vm", "hw_guest_full_name": null, "hw_guest_ha_state": null, "hw_guest_id": null, "hw_interfaces": ["eth0"], "hw_is_template": false, "hw_memtotal_mb": 1024, "hw_name": "rename_new_u0001", "hw_power_status": "poweredOff", "hw_processor_count": 1, "hw_product_uuid": "420cbebb-835b-980b-7050-8aea9b7b0a6d", "hw_version": "vmx-13", "instance_uuid": "500c60a6-b7b4-8ae5-970f-054905246a6f", "ipv4": null, "ipv6": null, "module_hw": true, "snapshots": []}}

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=3    changed=1    unreachable=0    failed=0
```

needs_info
