### ISSUE TITLE
rabbitmq_user fail to create user

### ISSUE THREAD

**Issue by nocgp** [ansible/ansible#42091]
##### SUMMARY
Rabbitmq_user failed to add user.
Could be related to #41820 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
rabbitmq_user

- rabbitmq_user: user=admin
                 password=[pwd]
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
                 tags=administrator

##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug 18 2016, 15:13:37) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### OS / ENVIRONMENT
Centos 6. py 2.6.6

[defaults]
host_key_checking = False
handler_includes_static = True

##### STEPS TO REPRODUCE

```yaml
- name: Add erlang  repository
  yum_repository:
    name: erlang-solutions
    description: rabbit_mq repo
    baseurl: https://packages.erlang-solutions.com/rpm/centos/$releasever/$basearch
    gpgcheck: yes
    enabled: yes
    gpgkey: https://packages.erlang-solutions.com/rpm/erlang_solutions.asc


- name: Add rabbit  repository
  yum_repository:
    name: rabbitmq_rabbitmq-server
    description: rabbit_mq repo
    baseurl: https://packagecloud.io/rabbitmq/rabbitmq-server/el/{{ ansible_distribution_major_version }}/$basearch
    repo_gpgcheck: yes
    gpgcheck: no
    enabled: yes
    gpgkey: https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey
    sslverify: yes
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt

- rpm_key: state=present key=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc

- name: install rabbitMQ server
  yum: name=rabbitmq-server state=latest

- name: enable plugins
  copy: src=enabled_plugins dest=/etc/rabbitmq/enabled_plugins

- file: path=/var/log/rabbitmq/ mode=0755 state=directory recurse=yes

- name: Start rabbitmq-server service
  service: name=rabbitmq-server state=started enabled=true

- rabbitmq_user: user=admin
                 password=[pwd]
                 vhost=/
                 configure_priv=.*
                 read_priv=.*
                 write_priv=.*
                 state=present
                 tags=administrator
```

##### EXPECTED RESULTS

1. Rabbitmq server started on remote server
2. Rabbitmq user created.
##### ACTUAL RESULTS

1. Rabbitmq server started on remote server
2. Ansible error occurs on rabbitmq_user module
```
FAILED! => {
    "changed": false,
    "cmd": "/usr/sbin/rabbitmqctl -q list_users",
    "invocation": {
        "module_args": {
            "configure_priv": ".*",
            "force": false,
            "node": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "permissions": [
                {
                    "configure_priv": ".*",
                    "read_priv": ".*",
                    "vhost": "/",
                    "write_priv": ".*"
                }
            ],
            "read_priv": ".*",
            "state": "present",
            "tags": "administrator",
            "user": "admin",
            "vhost": "/",
            "write_priv": ".*"
        }
    },
    "msg": "Could not start application logger: Logger.App.start(:normal, []) returned an error: shutdown: failed to start child: Logger.ErrorHandler\n    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started",
    "rc": 1,
    "stderr": "Could not start application logger: Logger.App.start(:normal, []) returned an error: shutdown: failed to start child: Logger.ErrorHandler\n    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started\n",
    "stderr_lines": [
        "Could not start application logger: Logger.App.start(:normal, []) returned an error: shutdown: failed to start child: Logger.ErrorHandler",
        "    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started"
    ],
    "stdout": "=SUPERVISOR REPORT==== 29-Jun-2018::09:47:09.050826 ===\n    supervisor: {local,'Elixir.Logger.Supervisor'}\n    errorContext: start_error\n    reason: noproc\n    offender: [{pid,undefined},\n               {id,'Elixir.Logger.ErrorHandler'},\n               {mfargs,\n                   {'Elixir.Logger.Watcher',start_link,\n                       [{error_logger,'Elixir.Logger.ErrorHandler',\n                            {true,false,500}}]}},\n               {restart_type,permanent},\n               {shutdown,5000},\n               {child_type,worker}]\n=CRASH REPORT==== 29-Jun-2018::09:47:09.054722 ===\n  crasher:\n    initial call: application_master:init/4\n    pid: <0.81.0>\n    registered_name: []\n    exception exit: {{shutdown,\n                         {failed_to_start_child,'Elixir.Logger.ErrorHandler',\n                             noproc}},\n                     {'Elixir.Logger.App',start,[normal,[]]}}\n      in function  application_master:init/4 (application_master.erl, line 138)\n    ancestors: [<0.80.0>]\n    message_queue_len: 1\n    messages: [{'EXIT',<0.82.0>,normal}]\n    links: [<0.80.0>,<0.42.0>]\n    dictionary: []\n    trap_exit: true\n    status: running\n    heap_size: 376\n    stack_size: 27\n    reductions: 192\n  neighbours:\n\n=CRASH REPORT==== 29-Jun-2018::09:47:09.050788 ===\n  crasher:\n
 initial call: Elixir.Logger.Watcher:init/1\n    pid: <0.88.0>\n    registered_name: []\n    exception exit: noproc\n      in function  gen:do_for_proc/2 (gen.erl, line 228)\n      in call from gen_event:rpc/2 (gen_event.erl,
line 239)\n      in call from 'Elixir.Logger.Watcher':init/1 (lib/logger/watcher.ex, line 23)\n      in call from gen_server:init_it/2 (gen_server.erl, line 374)\n      in call from gen_server:init_it/6 (gen_server.erl, line 342)\n    ancestors: ['Elixir.Logger.Supervisor',<0.82.0>]\n    message_queue_len: 0\n    messages: []\n    links: [<0.83.0>]\n    dictionary: []\n    trap_exit: true\n    status: running\n    heap_size: 376\n    stack_size: 27\n    reductions: 254\n  neighbours:\n\n=INFO REPORT==== 29-Jun-2018::09:47:09.056688 ===\n    application: logger\n    exited: {{shutdown,\n                 {failed_to_start_child,'Elixir.Logger.ErrorHandler',noproc}},\n
        {'Elixir.Logger.App',start,[normal,[]]}}\n    type: temporary\n",
    "stdout_lines": [
        "=SUPERVISOR REPORT==== 29-Jun-2018::09:47:09.050826 ===",
        "    supervisor: {local,'Elixir.Logger.Supervisor'}",
        "    errorContext: start_error",
        "    reason: noproc",
        "    offender: [{pid,undefined},",
        "               {id,'Elixir.Logger.ErrorHandler'},",
        "               {mfargs,",
        "                   {'Elixir.Logger.Watcher',start_link,",
        "                       [{error_logger,'Elixir.Logger.ErrorHandler',",
        "                            {true,false,500}}]}},",
        "               {restart_type,permanent},",
        "               {shutdown,5000},",
        "               {child_type,worker}]",
        "=CRASH REPORT==== 29-Jun-2018::09:47:09.054722 ===",
        "  crasher:",
        "    initial call: application_master:init/4",
        "    pid: <0.81.0>",
        "    registered_name: []",
        "    exception exit: {{shutdown,",
        "                         {failed_to_start_child,'Elixir.Logger.ErrorHandler',",
        "                             noproc}},",
        "                     {'Elixir.Logger.App',start,[normal,[]]}}",
        "      in function  application_master:init/4 (application_master.erl, line 138)",
        "    ancestors: [<0.80.0>]",
        "    message_queue_len: 1",
        "    messages: [{'EXIT',<0.82.0>,normal}]",
        "    links: [<0.80.0>,<0.42.0>]",
        "    dictionary: []",
        "    trap_exit: true",
        "    status: running",
        "    heap_size: 376",
        "    stack_size: 27",
        "    reductions: 192",
        "  neighbours:",
        "",
        "=CRASH REPORT==== 29-Jun-2018::09:47:09.050788 ===",
        "  crasher:",
        "    initial call: Elixir.Logger.Watcher:init/1",
        "    pid: <0.88.0>",
        "    registered_name: []",
        "    exception exit: noproc",
        "      in function  gen:do_for_proc/2 (gen.erl, line 228)",
        "      in call from gen_event:rpc/2 (gen_event.erl, line 239)",
        "      in call from 'Elixir.Logger.Watcher':init/1 (lib/logger/watcher.ex, line 23)",
        "      in call from gen_server:init_it/2 (gen_server.erl, line 374)",
        "      in call from gen_server:init_it/6 (gen_server.erl, line 342)",
        "    ancestors: ['Elixir.Logger.Supervisor',<0.82.0>]",
        "    message_queue_len: 0",
        "    messages: []",
        "    links: [<0.83.0>]",
        "    dictionary: []",
        "    trap_exit: true",
        "    status: running",
        "    heap_size: 376",
        "    stack_size: 27",
        "    reductions: 254",
        "  neighbours:",
        "",
        "=INFO REPORT==== 29-Jun-2018::09:47:09.056688 ===",
        "    application: logger",
        "    exited: {{shutdown,",
        "                 {failed_to_start_child,'Elixir.Logger.ErrorHandler',noproc}},",
        "             {'Elixir.Logger.App',start,[normal,[]]}}",
        "    type: temporary"
    ]
}```

```
