### ISSUE TITLE
loop over multiple tasks

### ISSUE THREAD

**Issue by srinivasguttur** [ansible/ansible#42095]
##### SUMMARY
How to loop over multiple tasks in a play or can we loop over the block which has multiple tasks? Instead of wrapper script which involve include_tasks: to loop over main play?

##### ISSUE TYPE
 - Documentation Report

##### COMPONENT NAME

block, loop
##### ANSIBLE VERSION

```
ansible version: 2.5
```

##### CONFIGURATION

CACHE_PLUGIN(/etc/ansible/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/etc/ansible/ansible.cfg) = cachedir
CACHE_PLUGIN_TIMEOUT(/etc/ansible/ansible.cfg) = 180
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

Need a suggestion on block and loop module.

```yaml
---
- name: wrapper script
  vars: 
    items: ['file1','file2']
  
  include_tasks: "empty_files.yml"
  with_items: "{{ items }}"
  loop_control:
    loop_var: item
```

##### EXPECTED RESULTS

NA
##### ACTUAL RESULTS

NA

```
NA
```
