### ISSUE TITLE
Fail flag for `no hosts matched`

### ISSUE THREAD

**Issue by sumkincpp** [ansible/ansible#42107]
##### SUMMARY

This feature was floating around for a while, strangely it isn't currently supported in ansible.

Would be great to have a new flag for playbooks which will show if we should fail on `no hosts matched` condition

Might be implemented with custom action module like the following
```yaml
- name: Check supplied hosts
  connection: local
  gather_facts: no
  hosts: all
  hosts_fail: on_empty
  tasks:
   ...
```
or with a flag.

Very useful within workflows without tricks, like [this](https://stackoverflow.com/questions/48901168/how-to-avoid-a-playbook-to-run-when-no-host-matches).

Relevant to #14693

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
Ansible playbooks
