### ISSUE TITLE
hard coded LANG in yum module breaks zammad rpm installation

### ISSUE THREAD

**Issue by dirks** [ansible/ansible#42114]
##### SUMMARY
hard coded LANG in yum module breaks zammad rpm installation.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
yum

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /home/idivadmin/ansible/ansible.cfg
  configured module search path = [u'/home/idivadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]                     
```

##### CONFIGURATION
default

##### OS / ENVIRONMENT
- Centos 7.5
- Centos 7.5

##### STEPS TO REPRODUCE

```yaml
- name: deploy zammad
  hosts: zammad.example.com
  tasks:
    - name: install elasticsearch yum repo
      yum_repository:
        baseurl: "https://artifacts.elastic.co/packages/5.x/yum"
        gpgcheck: yes
        gpgkey: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
        enabled: yes
        name: "elasticsearch-5.x"
        description: "Elasticsearch repository for 5.x packages"
        skip_if_unavailable: yes
      become: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"

    - name: install zammad yum repo
      yum_repository:
        baseurl: "https://dl.packager.io/srv/rpm/zammad/zammad/stable/el/7/$basearch"
        gpgcheck: no
        repo_gpgcheck: no
        gpgkey: "https://dl.packager.io/srv/zammad/zammad/key"
        enabled: yes
        name: "zammad-stable"
        description: "zammad project repo"
        skip_if_unavailable: yes
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version == "7"
      become: yes

    - name: install zammad
      yum:
        name: "{{ item }}"
      with_items:
        - java
        - elasticsearch
        - zammad
```

##### EXPECTED RESULTS
As `postgresql-setup initdb` runs during yum installation of zammad I would expect it to use the system locales resulting in an /var/lib/pgsql/initdb.log with

```
The database cluster will be initialized with locales
  COLLATE:  en_US.UTF-8
  CTYPE:    en_US.UTF-8
  MESSAGES: en_US.UTF-8
  MONETARY: de_DE.UTF-8
  NUMERIC:  de_DE.UTF-8
  TIME:     de_DE.UTF-8
```
##### ACTUAL RESULTS
Instead /var/lib/pgsql/initdb.log has

```
The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".
```

I guess this is due to f4c9c4596fc33aaef3f5c1e3bdad9ab3ae64775b

Link to zammad documentation https://docs.zammad.org/en/latest/install-centos.html
