### ISSUE TITLE
Module Etcd3 Get Values

### ISSUE THREAD

**Issue by vasartori** [ansible/ansible#42125]
##### SUMMARY
Add capacity to read data on etcd3 module.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

etcd3

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0
  config file = None
  configured module search path = [u'/home/victor/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/victor/.local/lib/python2.7/site-packages/ansible
  executable location = /home/victor/.local/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```yaml
# Get the value of key "foo" on a cluter located "http://localhost:2379"
- etcd3:
    key: "foo"
    host: "localhost"
    port: 2379
  register: foo

- debug:
  msg: "{{ foo.value }}"
```

##### EXPECTED RESULTS

The Value of stored data on etcd.

##### ACTUAL RESULTS

All fields are required, and the module does have support to only read data.

```
$ ansible-playbook etcd.yaml 
 [WARNING]: Unable to parse /etc/ansible/hosts as an inventory source

 [WARNING]: No inventory was parsed, only implicit localhost is available

 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'


PLAY [test] ************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [localhost]

TASK [etcd3] ***********************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "missing required arguments: value, state"}
	to retry, use: --limit @/home/victor/etcd.retry

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1   
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/etcd3.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/etcd3.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @evrardjp
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by evrardjp** [comment]
The idea was to use a lookup for querying data, but I understand why people would want to use this module to see the current content of the data stored. Patches welcome.

**Comment by evrardjp** [comment]
(See also: https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/lookup/etcd.py )

**Comment by vasartori** [comment]
Hi @evrardjp now I got it... the name etcd misleads. I guessed this module is about old etcd servers or version.... 

A thing we need consider: Etcd 3 does not support http (he support grpc and a api v2 emulation) the "etcd" module only support http.... see(https://coreos.com/blog/announcing-etcd-3.3), so what is created on api v3 (using the module etcd3) can't be recovery using etcd module (I could not make it works) .

Take a look on a test playbook...

```yaml
- name: Test
  hosts: localhost
  become: true

  tasks:
   - name: set data on etcd using etcd3 module 
     etcd3:
       key: "foo"
       value: "baz"
       state: "present"

   - name: get data on etcd using etcd3 module
     etcd3:
       key: "foo"
     register: foo

   - name: print data on foo register
     debug:
       msg: "{{ foo.value }}"
   
   - name: print data using lookup etcd
     debug: 
       msg: "{{ lookup('etcd','foo',version='v2',url='http://127.0.0.1:2379') }}"

```
I think it is not better do like consul_kv module? He does all operations in one module (get,set  and delete).

What do you think about? 
We can implement a lookup function on etcd3. I can do this patch...

**Comment by vasartori** [comment]
@evrardjp any news?

**Comment by evrardjp** [comment]
Sorry I missed your ping.
The documentation of the consul_kv module [1] doesnt' seem to propose a simple way to read the value, only one that handles the release/acquisition of locks using state: acquire/release.

I understand the willingness to not go through a lookup, as we have the data here and it's not executed the same way. But I wonder what is the purpose of doing so, vs a lookup plugin. Could you explain it more?

I understand there is a gap here, as you cannot read with the current state and no compatibility api, the information in the cluster. But I wonder where we should fix this. IMO, we should be extending the etcd lookup plugin with a native version 3 support.

Could you tell me more about your use case?

[1]: https://docs.ansible.com/ansible/2.5/modules/consul_kv_module.html#consul-kv-module

**Comment by vasartori** [comment]
Hi @evrardjp, you are 100% correct! 
Looking better today, I understand the place who needs to be changed. Definitely is not on this module. I agree with you, we need to extend the etcd lookup.

My case is: We use ansible to put some configs on etcd and some of thesees configs needs to be changed on templates (by a different automation or different teams, I dont know if I'm being clear).

I think you could deny the PR and close this issue... I can work on this update, what do you think?

**Comment by vasartori** [comment]
Hi @evrardjp Take a look on this test:
I'm looking on consul_kv module.... 
It seems works in ansible 2.6 the way I have talked on start of this thread...
On a old version (2.4), really dont works.
```yaml
- name: Test
  hosts: localhost

  tasks:
   - name: set data on consul_kv
     consul_kv:
       key: test
       value: testing123

   - name: get data on consul_kv and store it on register t
     consul_kv:
       key: test
     register: t

   - name: print data on t register
     debug:
       msg: "{{ t.data.Value }}"
```
Output:
```
PLAY [Test] ************************************************************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************************************************************
ok: [localhost]

TASK [set data on consul_kv] *******************************************************************************************************************************************
ok: [localhost]

TASK [get data on consul_kv and store it on register t] ****************************************************************************************************************
ok: [localhost]

TASK [print data on t register] ****************************************************************************************************************************************
ok: [localhost] => {
    "msg": "testing123"
}

PLAY RECAP *************************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=0   
```
Thats why I say the same behaviour of consul_kv
