### ISSUE TITLE
It seems docker_container is not working at 2.6

### ISSUE THREAD

**Issue by dlibanori** [ansible/ansible#42137]
Everything works fine with Ansible 2.5.4 and now it is not working at 2.6.0

task.yml
```
---
- stat:
    path: env
  register: env

- copy:
    remote_src: true
    src: env
    dest: '{{ env_file }}'
    force: no

- template:
    src: '{{ stack_file }}'
    dest: '{{ stack_dest }}'

- docker_image:
    name: '{{ app_image }}'

- docker_container:
    name: migration-{{ ansible_date_time.epoch }}
    image: '{{ app_image }}'
    working_dir: /tavola
    command: bin/rails db:migrate
    detach: no
    env:
      RAILS_ENV: production
    env_file: '{{ env_file }}'

- command: 'docker stack deploy --with-registry-auth -c {{ stack_dest }} {{ stack_name }}'
```
Running ansible:

```
marie:docker dlibanori$ ansible-playbook -i inventory/sandbox deploy.yml
Version: v1.17.0

PLAY [managers] ******************************************************************************************************************************************************************

TASK [Gathering Facts] ***********************************************************************************************************************************************************
ok: [10.1.0.81]

TASK [update : stat] *************************************************************************************************************************************************************
ok: [10.1.0.81]

TASK [update : copy] *************************************************************************************************************************************************************
ok: [10.1.0.81]

TASK [update : template] *********************************************************************************************************************************************************
ok: [10.1.0.81]

TASK [update : docker_image] *****************************************************************************************************************************************************
ok: [10.1.0.81]

TASK [update : docker_container] *************************************************************************************************************************************************
fatal: [10.1.0.81]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 10.1.0.81 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_t1bVeP/ansible_module_docker_container.py\", line 2081, in <module>\r\n    main()\r\n  File \"/tmp/ansible_t1bVeP/ansible_module_docker_container.py\", line 2076, in main\r\n    cm = ContainerManager(client)\r\n  File \"/tmp/ansible_t1bVeP/ansible_module_docker_container.py\", line 1703, in __init__\r\n    self.present(state)\r\n  File \"/tmp/ansible_t1bVeP/ansible_module_docker_container.py\", line 1723, in present\r\n    new_container = self.container_create(self.parameters.image, self.parameters.create_parameters)\r\n  File \"/tmp/ansible_t1bVeP/ansible_module_docker_container.py\", line 825, in create_parameters\r\n    host_config=self._host_config(),\r\n  File \"/tmp/ansible_t1bVeP/ansible_module_docker_container.py\", line 931, in _host_config\r\n    return self.client.create_host_config(**params)\r\n  File \"/opt/python/lib/python2.7/site-packages/docker/api/container.py\", line 157, in create_host_config\r\n    return utils.create_host_config(*args, **kwargs)\r\nTypeError: create_host_config() got an unexpected keyword argument 'init'\r\n", "msg": "MODULE FAILURE", "rc": 1}

PLAY RECAP ***********************************************************************************************************************************************************************
10.1.0.81                  : ok=5    changed=0    unreachable=0    failed=1
```
