### ISSUE TITLE
RFE: Allow access to all items in a loop list

### ISSUE THREAD

**Issue by opoplawski** [ansible/ansible#42131]
##### SUMMARY
I would like to be able to reference other items in a loop.  I.e., do something like:
```yaml
  - name: "Setup rules"
    pfsense_rule:
      name: "{{ item.name }}"
      action: pass
      interface: opt1
      ipprotocol: inet
      protocol: "{{ item.protocol }}"
      source: "{{ item.source }}"
      destination: "{{ item.destination }}"
      # This would be nice if possible:
      after: "{{ items[idx-1].name if idx > 0 else 'pfB_firehol3 auto.rule' }}"
    loop_control:
      index_var: idx
    loop:
    - { name: "Allow access to internal DNS", protocol: tcp/udp, source: NET:opt1, destination: dns_int:53 }
    - { ... }
```

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
loop

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 13 2018, 04:32:41) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
you have those already, in `idx.results`, just keep in mind it doesn't exist until the first iteration is done

**Comment by opoplawski** [comment]
Are you sure it's idx.results? as I don't see that:
```yaml
---
- hosts: localhost
  gather_facts: no
  tasks:
  - debug: msg="idx={{ idx }}, idx.results={{ idx.results if idx.results is defined else 'none' }}"
    loop:
    - { name: "hi", arg: bah }
    - { name: "ho", arg: beh }
    loop_control:
      index_var: idx
```
```
TASK [debug] **************************************************************************************
Friday 29 June 2018  14:54:18 -0600 (0:00:00.237)       0:00:00.237 ***********
ok: [localhost] => (item={u'name': u'hi', u'arg': u'bah'}) => {
    "idx": 0,
    "msg": "idx=0, idx.results=none"
}
ok: [localhost] => (item={u'name': u'ho', u'arg': u'beh'}) => {
    "idx": 1,
    "msg": "idx=1, idx.results=none"
}
```

**Comment by opoplawski** [comment]
Still the same with ansible 2.7.10

**Comment by Akasurde** [comment]
@opoplawski With `extended` option in loop control (introduced in 2.8) this is possible to address various items in a loop.

```yaml
    - name: a
      debug:
        msg: "{{ ansible_loop.previtem['name'] if idx > 0 else 'pfB_firehol3 auto.rule' }}"
      loop: "{{ data }}"
      loop_control:
        index_var: idx
        extended: yes
```

You can find more details [here](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#extended-loop-variables). 

Let me know if I am missing something here. Thanks.

needs_info
