### ISSUE TITLE
jenkins_plugin - Jenkins home directory doesn't exist

### ISSUE THREAD

**Issue by setevoy2** [ansible/ansible#42148]
##### SUMMARY

Have "_Jenkins home directory doesn't exist._" error if install plugin which is already installed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`jenkins_plugin`

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /home/setevoy/Work/devops/projects/jenkins/ansible.cfg
  configured module search path = ['/home/setevoy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, May 11 2018, 04:00:52) [GCC 8.1.0]
```

##### CONFIGURATION
```[defaults]
remote_user=admin
host_key_checking=False
inventory = hosts.ini
retry_files_enabled = False
```

##### OS / ENVIRONMENT
Running Ansible from: Arch Linux.
The OS you are managing: Debian 9

Jenkins running in Docker container with volume mapped from the host's directory into Jenkins:

```...
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
```

##### STEPS TO REPRODUCE

Install plugin using `jenkins_plugin`.
Re-run playbook using same plugins.

```- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    url_username: "{{ jenkins_ui_admin_user }}"
    url_password: "{{ jenkins_ui_admin_pass }}"
    state: present
  with_items:
    - locale
  when: jenkins_service_status['status'] == 200

```

##### EXPECTED RESULTS
`item` must be skipped.

##### ACTUAL RESULTS

Plugin task fails:

```
TASK [jenkins : Install Jenkins plugins] *****
failed: [dev.ci.domain.world] (item=locale) => {"changed": false, "item": "locale", "msg": "Jenkins home directory doesn't exist."}
```
If delete plugin from Jenkins manually an re-run Ansible task - it works good.

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/web_infrastructure/jenkins_plugin.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/web_infrastructure/jenkins_plugin.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @jtyr
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by jtyr** [comment]
Please could you provide Docker Compose file and Ansible Playbook to demonstrate the issue?

**Comment by setevoy2** [comment]
Compose file, the `jenkins` container:

```services:
  jenkins:
    user: root
    image: jenkins/jenkins:lts
    networks:
      - jenkins
    ports:
      - '8080:8080'
    volumes:
      - {{ data_volume_mount_path }}/{{ jenkins_data_dir }}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    environment:
      - JENKINS_HOME=/var/jenkins_home
    logging:
      driver: "journald"
```
`{{ data_volume_mount_path }}/{{ jenkins_data_dir }}` == `/data/jenkins`.
Ansible playbook, related parts:

```...
- name: Copy Docker Compose file
  template:
    src: templates/jenkins-compose.yml.j2
    dest: "{{ jenkins_opt_dir }}/jenkins-compose.yml"
    owner: "{{ jenkins_user }}"
    group: "{{ jenkins_user }}"
    mode: 0644

- name: Copy systemd service file
  template:
    src: templates/jenkins-service.j2
    dest: "/etc/systemd/system/jenkins.service"
    owner: "root"
    group:  "root"
    mode: 0644

- name: Start Jenkins service
  service:
    name=jenkins
    state=restarted
    enabled=yes

- name: Wait for Jenkins to start up
  uri:
    url: http://localhost:8080
    status_code: 200
    user: "{{ jenkins_ui_admin_user }}"
    password: "{{ jenkins_ui_admin_pass }}"
    timeout: 5
    force_basic_auth: yes
  register: jenkins_service_status
  retries: 10
  delay: 5
  until: >
     'status' in jenkins_service_status and
     jenkins_service_status['status'] == 200

- name: Check Jenkins status
  debug:
    msg: "Jenkins status: {{ jenkins_service_status['status'] }}"

- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    url_username: "{{ jenkins_ui_admin_user }}"
    url_password: "{{ jenkins_ui_admin_pass }}"
    state: present
  with_items:
    - locale
  when: jenkins_service_status['status'] == 200

- name: Restart Jenkins service
  service:
    name=jenkins
    state=restarted
    enabled=yes
```

**Comment by jtyr** [comment]
Please try to set the `jenkins_home` option in the `jenkins_plugin` task.

**Comment by setevoy2** [comment]
@jtyr Oh, I see now... 
Default in plugin is `/var/lib/jenkins`, while container has `JENKINS_HOME=/var/jenkins_home`...
Thanks, will try on Monday and will post result here.
Have a great weekend!

**Comment by setevoy2** [comment]
Hi, @jtyr 
No, unfortunately - didn't help.

First I tried to add the `jenkins_home` variable and the path directly, pointed to `/var/jenkins_home`:

```- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: /var/jenkins_home
    url_username: "{{ jenkins_ui_admin_user }}"
    url_password: "{{ jenkins_ui_admin_pass }}"
    state: present
  with_items:
    - locale
  when: jenkins_service_status['status'] == 200
```

Next I tried to add it via varialbe and point to the plugin's default Jenkin's home `/var/lib/jenkins`:

```jenkins_data_dir: "jenkins"
jenkins_opt_dir: "/opt/jenkins"
jenkins_home: "/var/lib/jenkins"
jenkins_user: "jenkins"
jenkins_uid: "1001"
```
And the unse it in the task:

```- name: Install Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    url_username: "{{ jenkins_ui_admin_user }}"
    url_password: "{{ jenkins_ui_admin_pass }}"
    state: present
  with_items:
    - locale
  when: jenkins_service_status['status'] == 200
```

And in the Compose file:

```    
volumes:
      - {{ data_volume_mount_path }}/{{ jenkins_data_dir }}:{{ jenkins_home }}
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
#      - /usr/lib/x86_64-linux-gnu/libltdl.so.7:/usr/lib/x86_64-linux-gnu/libltdl.so.7
    environment:
      - JENKINS_HOME={{ jenkins_home }}
    logging:
      driver: "journald"
```

Volume mapped correctly:

```
root@jenkins-dev:/opt/jenkins# docker exec -ti jenkins_jenkins_1 ls -l /var/lib/jenkins
total 148
drwxr-xr-x  4 root    root    4096 Jun 30 13:50 caches
-rw-r--r--  1 root    root    3420 Jul  2 07:46 config.xml
-rwxrwxrwx  1 jenkins jenkins 2702 Jul  2 07:39 copy_reference_file.log
-rw-r--r--  1 root    root    6574 Jun 30 15:09 credentials.xml
drwxr-xr-x  7 root    root    4096 Jun 30 15:12 fingerprints
...
```

Both attempts gave me the same result with the "_Jenkins home directory doesn't exist._" error.
Am I'm missing something again?

**Comment by svcngcc** [comment]
I also faced the similar issue. In my case Jenkins was running as docker container but i was trying to configure plugin on parent host. Obviously Jenkins_home is defined inside container. Ansible plugin uses the file system (jenkins_home) to install the plugin. If you set your connection directly to the container, it would work. refer the following help to configure Ansible connectivity with remote docker containers:
https://stackoverflow.com/questions/32878795/run-command-inside-of-docker-container-using-ansible/41626257#41626257

**Comment by vishveshv** [comment]
I also faced the similar issue. In my case Jenkins was running as docker container but i was trying to install plugin on parent node . Ansible plugin uses the jenkins_home location installing the plugin which is inside the container, not on parent node. If you set your connection directly to the container, it would work. refer the following help to configure Ansible connectivity with remote docker containers:
https://stackoverflow.com/questions/32878795/run-command-inside-of-docker-container-using-ansible/41626257#41626257

**Comment by JiElPe-Fr38** [comment]
I just spent few hours because of this problem, with a jenkins instance created inside a docker container, trying to exclusively used an Ansible playbook (no dockerfile) with docker and jenkins related modules.

Reading the code, my understanding is that when the latest plugin version or a specific version is asked for an already installed plugin, the version comparison is made by comparing md5sum of both the installed plugin (1) and the downloaded plugin (2).
(1) Needs the Jenkins home path to be defined.
_And it is on the playbook target, not on the container_
(2) Implies that each plugins is downloaded even if not necessary

I think that this could be enhanced by getting the updates json file from the Jenkins URL and by retrieving each installed plugin version through such an URL : 
`http://<user>:<password>@<jenkin url>:<jenkins port>/pluginManager/api/xml?depth=1&xpath=/*/*/shortName|/*/*/version&wrapper=plugins`

The **_critical point to consider_** here is that the current `jenkins_plugins` module cannot be run against existing plugins on an already installed instance  _within a container not bind to a local volume_. 
**Therefore, a playbook using the `jenkins_plugins` is not idempotent in such an environment.** which does not fit the Ansible philosophy.

**Comment by adam-fu** [comment]
I run into this issue today as well.

I set  in docker-compose.yml 
```
    environment:
      - JENKINS_HOME=/var/jenkins_home
```
and in ansible jeknins_plugin setting value  ``` jenkins_home: /var/jenkins_home/ ```

I run the first installation with ansible 2.8.3, Then upgraded because of CSRF problem to ansible 2.9.9. Then I get the same error, so I deleted the volume, removed the container and run the job again. 

The plugin now is idempotent. So I guess users who first upgrade ansible to a newer version and then run the plugin for the first time will never run into this issue.

**Comment by adam-fu** [comment]
@JiElPe-Fr38 
the idempotent playbook would be to trigger all install jobs as async and catch later the errors and well.. just ignore them. The plug-and-pray script could look like this:

```
- name: install jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    url_username: "{{ jenkins_admin_username }}"
    url_password: "{{ jenkins_admin_password }}"
    jenkins_home: /var/jenkins_home/
    url: http://127.0.0.1:8081/
    state: present
  with_items: "{{ jenkins_plugins }}"
  async: 70
  poll: 0
  register: jenkins_plugins_job

- name: Wait for async installation to end
  async_status:
    jid: "{{ async_result_item.ansible_job_id }}"
  with_items: "{{ jenkins_plugins_job.results }}"
  loop_control:
    loop_var: "async_result_item"
  register: job_result
  # ignore errors due to bug: https://github.com/ansible/ansible/issues/42148
  # and unmerged ticket https://github.com/ansible/ansible/pull/67385
  ignore_errors: True
  until: job_result.finished
  retries: 10
  delay: 7
```
Also I wonder, when the jenkins docker image has a local volume at the host, the installation would be just download the plugins and unpack them to JENKINS_HOME/plugins of the ansible host.
