### ISSUE TITLE
Add "descr" parameter to aci_static_binding_to_epg - Bind static paths to EPGs (fv:RsPathAtt)

### ISSUE THREAD

**Issue by dcweber** [ansible/ansible#42154]
##### SUMMARY

The aci_static_binding_to_epg module does not support the "descr" parameter (fv:RsPathAtt.descr)

##### ISSUE TYPE
 - Feature Idea
Add "descr" as an available parameter to set, change or filter on.

##### COMPONENT NAME

aci_static_binding_to_epg

##### ANSIBLE VERSION

```
~/ansible$ ansible --version
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/dan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/dan/ansible/venv/local/lib/python2.7/site-packages/ansible
  executable location = /home/dan/ansible/venv/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

(venv) dan@bo-tst-ub-srv1:~/ansible$ ansible-config dump --only-changed
(venv) dan@bo-tst-ub-srv1:~/ansible$

q
##### OS / ENVIRONMENT

 Running Ansible From: Ubuntu 16.04.4 LTS
OS Managing: Cisco ACI 2.1.3p

##### STEPS TO REPRODUCE

```yaml

- name: Playbook to create a static path for a physical interface to an EPG
  hosts: lab-apic
  connection: local
  gather_facts: no

  vars:
    vOutputLevel: "debug"
    vTenant: "P4A"
    vAp: "WebApp1"
    vEPG: "Web"
    vEncapId: "1040"
    vDeployImmediacy: "lazy"
    vIntMode: "802.1p"
    vIntType: "switch_port"
    vPodId: "1"
    vLeafs: "101"
    vInterface: "1/8"
    #vDescr: "SERVER-E1"

  tasks:
    - name: Create Static Path (fvRsPathAtt) to EPG (fvAEPg)
      aci_static_binding_to_epg:
        host: "{{ ansible_host }}"
        username: "{{ ansible_user }}"
        private_key: "{{ ansible_private_key }}"
        validate_certs: no
        tenant: "{{vTenant}}"
        ap: "{{vAp}}"
        epg: "{{vEPG}}"
        encap_id: "{{vEncapId}}"
        deploy_immediacy: "{{vDeployImmediacy}}"
        interface_type: "{{vIntType}}"
        interface_mode: "{{vIntMode}}"
        pod_id: "{{vPodId}}"
        leafs: "{{vLeafs}}"
        interface: "{{vInterface}}"
        output_level: "{{ vOutputLevel }}"
        #descr: "{{vDescr}}"
        state: absent
      register: vResponse
    - debug: var=vResponse
```

##### EXPECTED RESULTS

Expected results would be ability to set description and use that field for filtering.

The name can be useful when searching for a physical severs static path EPG bindings. For example, the following would only static bindings where fvRsPathAtt.descr contained TLOINF

# Extract using fvRsPathAtt.descr
moquery -c fvTenant -d uni/tn-TST -o xml -a config -x rsp-subtree=full rsp-subtree-class=fvAp,fvAEPg rsp-subtree-class=fvRsPathAtt rsp-subtree-filter='wcard(fvRsPathAtt.descr,"TLOINF")' rsp-prop-include=config-only

##### ACTUAL RESULTS

Not able to set "descr" parameter

```

```
