### ISSUE TITLE
authorized_key module reports 'ok' status when running without permissions (should fail instead)

### ISSUE THREAD

**Issue by techraf** [ansible/ansible#42166]
##### SUMMARY

`authorized_key` module with `state: absent` does not remove the key but reports `ok` status when running without proper permissions to the `authorized_keys` file.

While it is obvious it has no permission and it cannot perform the action, it should fail instead.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

`authorized_key` module

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/Users/macraf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/macraf/anaconda2/lib/python2.7/site-packages/ansible
  executable location = /Users/macraf/anaconda2/bin/ansible
  python version = 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

Running the following playbook as unprivileged user (for example `vagrant`).

```yaml
- hosts: all
  gather_facts: false

  tasks:
    - name: Ensure myuser exists
      become: true
      user:
        name: myuser

    - name: Ensure myuser has vagrant insecure public key in authorized_keys
      become: true
      authorized_key:
        user: myuser
        key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

    - name: Ensure myuser does not have vagrant insecure public key in authorized_keys
      # no 'become: true' to illustrate the problem
      # this task runs as a non-root user, and not 'myuser'
      authorized_key:
        user: myuser
        key: ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
        state: absent
```

##### EXPECTED RESULTS

Failure at `Ensure myuser does not have vagrant insecure public key in authorized_keys` task, as the end state is not what is declared.

##### ACTUAL RESULTS

```
PLAY [all] *********************************************************************

TASK [Ensure myuser exists] ****************************************************
changed: [myhost]

TASK [Ensure myuser has vagrant insecure public key in authorized_keys] ********
changed: [myhost]

TASK [Ensure myuser does not have vagrant insecure public key in authorized_keys] ***
ok: [myhost]
```
