### ISSUE TITLE
openstack_cloud_from_module AttributeError: 'module' object has no attribute 'version'

### ISSUE THREAD

**Issue by erickeller** [ansible/ansible#42189]
##### SUMMARY

```
os_server:
      state: present
      name: "{{ instance_name }}"
      image: "{{ instance_os }}"
      key_name: devops
      wait: yes
      flavor: "{{ instance_flavor }}"
      auto_floating_ip: yes
      network: net-test
      security_groups: default
      validate_certs: False
      meta:
        hostname: "{{ instance_name }}.foobar.com"
      userdata: |
        #cloud-config
        package_upgrade: false
        package_update: false
```

results in

```
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_mbhpWq/ansible_module_os_server.py", line 733, in <module>
    main()
  File "/tmp/ansible_mbhpWq/ansible_module_os_server.py", line 720, in main
    sdk, cloud = openstack_cloud_from_module(module)
  File "/tmp/ansible_mbhpWq/ansible_modlib.zip/ansible/module_utils/openstack.py", line 121, in openstack_cloud_from_module
AttributeError: 'module' object has no attribute 'version'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mbhpWq/ansible_module_os_server.py\", line 733, in <module>\n    main()\n  File \"/tmp/ansible_mbhpWq/ansible_module_os_server.py\", line 720, in main\n    sdk, cloud = openstack_cloud_from_module(module)\n  File \"/tmp/ansible_mbhpWq/ansible_modlib.zip/ansible/module_utils/openstack.py\", line 121, in openstack_cloud_from_module\nAttributeError: 'module' object has no attribute 'version'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

os_server

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /home/foo/.ansible.cfg
  configured module search path = [u'/home/foo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

```
ANSIBLE_SSH_CONTROL_PATH(/home/foo/.ansible.cfg) = ~/.ssh/%%C
```

##### OS / ENVIRONMENT
```
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
```
uname -a
4.15.0-23-lowlatency #25~16.04.1-Ubuntu SMP PREEMPT Fri May 25 06:15:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost
  tasks:
    - name: Delete server
      os_server:
        name: "{{ instance_name }}"
        state: absent
        validate_certs: False
```
```
ANSIBLE_HOST_KEY_CHECKING=false ansible-playbook --private-key=mykey.pem  --extra-vars 'instance_name=foobar' -vvv teardown.yml --timeout 40
```

##### EXPECTED RESULTS

Instance gets deleted/created without any python stacktrace

##### ACTUAL RESULTS

```
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: foo
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /tmp/ansible-tmp-1530530941.08-144442719733892 `" && echo ansible-tmp-1530530941.08-144442719733892="` echo /tmp/ansible-tmp-1530530941.08-144442719733892 `" ) && sleep 0'
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/openstack/os_server.py
<127.0.0.1> PUT /home/foo/.ansible/tmp/ansible-local-22578i9JQcm/tmpdduCSY TO /tmp/ansible-tmp-1530530941.08-144442719733892/os_server.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /tmp/ansible-tmp-1530530941.08-144442719733892/ /tmp/ansible-tmp-1530530941.08-144442719733892/os_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /tmp/ansible-tmp-1530530941.08-144442719733892/os_server.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /tmp/ansible-tmp-1530530941.08-144442719733892/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_bwbHFx/ansible_module_os_server.py", line 733, in <module>
    main()
  File "/tmp/ansible_bwbHFx/ansible_module_os_server.py", line 720, in main
    sdk, cloud = openstack_cloud_from_module(module)
  File "/tmp/ansible_bwbHFx/ansible_modlib.zip/ansible/module_utils/openstack.py", line 121, in openstack_cloud_from_module
AttributeError: 'module' object has no attribute 'version'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_bwbHFx/ansible_module_os_server.py\", line 733, in <module>\n    main()\n  File \"/tmp/ansible_bwbHFx/ansible_module_os_server.py\", line 720, in main\n    sdk, cloud = openstack_cloud_from_module(module)\n  File \"/tmp/ansible_bwbHFx/ansible_modlib.zip/ansible/module_utils/openstack.py\", line 121, in openstack_cloud_from_module\nAttributeError: 'module' object has no attribute 'version'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}
```
