### ISSUE TITLE
ios_config idempotency problem

### ISSUE THREAD

**Issue by jguirlinger** [ansible/ansible#42181]
##### SUMMARY
Simple playbook using ios_config and lines parameter not idempotent

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_config
##### ANSIBLE VERSION

```
$ansible --version
ansible 2.5.2

```

##### CONFIGURATION

$ansible-config dump --only-changed
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = ['/srv/home/guirlinger_j/Devel/myproject/ansible/inventory']
PARAMIKO_HOST_KEY_AUTO_ADD(/etc/ansible/ansible.cfg) = True
PERSISTENT_COMMAND_TIMEOUT(/etc/ansible/ansible.cfg) = 60
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT

ansible control server :
```
Red Hat Enterprise Linux Server release 7.4 (Maipo)
```

Cisco switch :
```
Cisco IOS Software, IOS-XE Software, Catalyst L3 Switch Software (CAT3K_CAA-UNIVERSALK9-M), Version 03.07.05E RELEASE SOFTWARE (fc1)
```

##### STEPS TO REPRODUCE

This simple playbook always reports change when running several time against the switch.

```yaml
---
- hosts: NAC
  gather_facts: False


  vars_prompt:
    - name: "username"
      prompt: "Username "
      private: no
    - name: "password"
      prompt: "Password "
      private: yes

  vars:
    ansible_user: "{{ username }}"
    ansible_password: "{{ password }}"

  tasks:
    - name: Configure Radius server group
      ios_config:
        lines:
          - server-private 10.177.0.197 key 7 09584B1A0D041901020E082F
          - server-private 10.210.0.223 key 7 09584B1A0D041901020E082F
          - load-balance method least-outstanding ignore-preferred-server
        parents: "aaa group server radius test"

```

##### EXPECTED RESULTS

Running the playbook should configure and report change the first time, but should only report OK then

##### ACTUAL RESULTS

Swtich is well configured but the playbook is not idempotent

```
changed: [WPC-I01A-TEST] => {
    "banners": {},
    "changed": true,
    "commands": [
        "aaa group server radius test",
        "server-private 10.177.0.197 key 7 09584B1A0D041901020E082F",
        "server-private 10.210.0.223 key 7 09584B1A0D041901020E082F",
        "load-balance method least-outstanding ignore-preferred-server"
    ],
    "invocation": {
        "module_args": {
            "after": null,
            "auth_pass": null,
            "authorize": null,
            "backup": false,
            "before": null,
            "defaults": false,
            "diff_against": null,
            "diff_ignore_lines": null,
            "force": false,
            "host": null,
            "intended_config": null,
            "lines": [ 
                "server-private 10.177.0.197 key 7 09584B1A0D041901020E082F",
                "server-private 10.210.0.223 key 7 09584B1A0D041901020E082F",
                "load-balance method least-outstanding ignore-preferred-server"
            ],
            "match": "line",
            "multiline_delimiter": "@",
            "parents": [
                "aaa group server radius test"
            ],
            "password": null,
            "port": null,
            "provider": null,
            "replace": "line",
            "running_config": null,
            "save": false,
            "save_when": "never",
            "src": null,
            "ssh_keyfile": null,
            "timeout": null,
            "username": null
        }
    },
    "updates": [
        "aaa group server radius test",
        "server-private 10.177.0.197 key 7 09584B1A0D041901020E082F",
        "server-private 10.210.0.223 key 7 09584B1A0D041901020E082F",
        "load-balance method least-outstanding ignore-preferred-server"
    ]
}
META: ran handlers
META: ran handlers

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
WPC-I01A-TEST              : ok=1    changed=1    unreachable=0    failed=0

```
