### ISSUE TITLE
Allow variable module arguments 

### ISSUE THREAD

**Issue by basos9** [ansible/ansible#42192]
##### SUMMARY

Do not deprecate the feature to allow module arguments to come from variables. My proposal is to keep the warning, or even disable the feature, but at least keep it as a configuration option (e.g. ANSIBLE_ALLOW_MODULE_TEMPLATES)

Apart from the possible security issue regarding compromised facts, it is up the the playbook developer to use the correct arguments. That said, this feature simplifies a lot code examples like the ones below.

Discussion:

Refering to
https://groups.google.com/forum/#!topic/ansible-project/Qrq76VLIqKg

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

Core

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vgouv/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Sep 23 2017, 22:06:14) [GCC 7.2.0]

```

##### STEPS TO REPRODUCE

```yaml

---

- name: Test
  hosts: all
  vars:
    link_list:
      - src: /etc/hosts
        dest: /tmp/2
        state: link
      - src: /etc/fstab
        dest: /tmp/1
        state: link
      - src: /etc/hostname
        dest: /tmp/3
        state: link
      - src: /etc/resolv.conf
        dest: /tmp/4
        state: link
  tasks:
    - file:
      args: "{{ item }}"
      with_items: "{{ link_list }}"

```

OR 

```yaml
  - name: change some lines 
    lineinfile: "{{ { 'path': '/etc/rsyslog.conf'} | combine(item) }}"
    vars: 
      xtra_args:
        path: "/etc/rsyslog.conf"
        backup: true
    loop:
    - { line: '# exclude something', insertbefore: '^\*\.\*;auth,authpriv\.none' }
...
```

Compare this to the current solution
```yaml
  - name: change some lines 
    lineinfile:
      line: "{{ item.line }}"
      regexp: "{{ item.regexp|default(omit) }}"
      backrefs: "{{ item.backrefs|default(omit) }}"
      insertbefore: "{{ item.insertbefore|default(omit) }}"
      insertafter: "{{ item.insertafter|default(omit) }}"
      state: "{{ item.state|default(omit) }}"
      path: "/etc/rsyslog.conf"
      backup: true
    loop:
    - { line: '# exclude something', insertbefore: '^\*\.\*;auth,authpriv\.none' }
 ...
```

##### ACTUAL RESULTS

```
[DEPRECATION WARNING]: Using variables for task params is unsafe, especially if the variables come from an external source like 
facts. This feature will be removed in version 2.6. Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

```
