### ISSUE TITLE
New option for concatenating list values for same dictionary variables

### ISSUE THREAD

**Issue by zasca** [ansible/ansible#42194]
##### SUMMARY

In my case I found that setting `hash_behaviour=merge` in ansible.cfg very conveniently. This works great, and allows you to minimize duplicate prefixes in variable names.

But there is one case when this not working. When there are list values in vars, and they are replacing, instead of concatenate. And it brings a lot of headache. Also looks like I'm not alone in this: [1](https://groups.google.com/forum/#!topic/ansible-project/bm67pwCnIMQ),[2](https://groups.google.com/forum/#!topic/ansible-project/DHe_XJaY-AA),[3](http://leapfrogonline.io/articles/2017-02-22-explicit-merging-of-ansible-variables/)

So it would be great to add new option `lists_behaviour` with choices `["replace", "join"]`. When it set to `join` list values in vars should be concatenated.

I found [this post](http://y.tsutsumi.io/deepmerge-deep-merge-dictionaries-lists-and-more-in-python.html) when was googling about merging dictionaries with list values in python.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

lib/ansible/utils/vars.py
##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/me/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/me/deploy/ansible.cfg) = True
DEFAULT_HASH_BEHAVIOUR(/home/me/deploy/ansible.cfg) = merge
DEFAULT_HOST_LIST(/home/me/deploy/ansible.cfg) = [u'/home/me/deploy/env/dev']
DEFAULT_ROLES_PATH(/home/me/deploy/ansible.cfg) = [u'/home/me/deploy/roles/in-house', u'/home/me/deploy/roles/3rd-party']
DEFAULT_STDOUT_CALLBACK(/home/me/deploy/ansible.cfg) = debug
DIFF_ALWAYS(/home/me/deploy/ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/home/me/deploy/ansible.cfg) = 30
RETRY_FILES_ENABLED(/home/me/deploy/ansible.cfg) = False
```
##### OS / ENVIRONMENT

Ubuntu 18.04 LTS
##### STEPS TO REPRODUCE

```ini
# ansible.cfg:
hash_behaviour=merge
```
```yaml
# group_vars/all.yml:
foo:
  bar1: foobar
  bar2: [a,b]

# hosts_vars/node1.yml:
foo:
  bar2: [c]

# playbook.yml:
- hosts: node1
  tasks:
    - debug: { msg: "{{ foo }}" }
```
```
ansible-playbook playbook.yml
```

##### EXPECTED RESULTS

```json
{"bar1": "foobar", "bar2": ["a", "b", "c"]}
```
##### ACTUAL RESULTS

```json
{"bar1": "foobar", "bar2": ["c"]}
```
##### UGLY WORKAROUND
What we do in our case:
```yaml
# group_vars/all.yml:
foo:
  bar1: foobar
  bar2:
    shared: [a,b]

# hosts_vars/node1.yml:
foo:
  bar2:
    exclusive: [c]

# playbook.yml:
- hosts: node1
  tasks:
    - debug: { msg: "{{ item }}" }
      with_items: |
    {%- if foo.bar2.exclusive is defined -%}
       {%- if foo.bar2.shared is defined -%}
         {{ foo.bar2.shared + foo.bar2.exclusive }}
       {%- else -%}
         {{ foo.bar2.exclusive }}
       {%- endif -%}
    {%- else -%}
       {{ foo.bar2.shared }}
    {%- endif -%}
      when: (foo.bar2 is defined) and ((foo.bar2.shared is defined) or (foo.bar2.exclusive is defined))
```
