### ISSUE TITLE
VMware: Proxy support for vmware connection

### ISSUE THREAD

**Issue by Im0** [ansible/ansible#42221]
##### SUMMARY
In an environment which requires HTTP/HTTPS proxy access through to a vcenter.  Would like `vmware_resource_pool_facts` to support proxies.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

vmware_resource_pool_facts

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

Default configuration.

##### STEPS TO REPRODUCE

Set environment variables:
```
export HTTPS_PROXY=http://x.x.x.x:8080
export HTTP_PROXY=http://x.x.x.x:8080
```

```yaml
---
- name: Configure VMware
  hosts: labESXI
  vars_files:
    - vars/passwords.yml
  gather_facts: no
  vars:
    timeout: 600
    ansible_timeout: 600
    vcenter_hostname: 1192.168.0.111
    proxy_env:
      http_proxy: http://x.x.x.x:8080
      https_proxy: http://x.x.x.x:8080

  tasks:
    - name: Gather resource pool facts about all resource pools available
      vmware_resource_pool_facts:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: false
      register: rp_facts
```

##### EXPECTED RESULTS

Would have liked to get resource pool facts from the vCenter.

##### ACTUAL RESULTS

```
PLAY [Configure VMware] *****************************************************************************************

TASK [Gather resource pool facts about all resource pools available] ********************************************
fatal: [cdclabvc01 -> localhost]: FAILED! => {"changed": false, "msg": "Unknown error while connecting to vCenter or ESXi API at 192.168.0.111:443 : [Errno 110] Connection timed out"}

```
