### ISSUE TITLE
Failed to create security group in aws

### ISSUE THREAD

**Issue by yanivrefael** [ansible/ansible#42230]
##### SUMMARY
Failed to create security group via ec2_group module 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION
2.6.0

##### CONFIGURATION
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -o ControlMaster=no -o ControlPersist=4h -o ForwardAgent=yes -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
DEFAULT_ACTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/action']
DEFAULT_CACHE_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/cache']
DEFAULT_CALLBACK_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/callback']
DEFAULT_CONNECTION_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/connection']
DEFAULT_FILTER_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/filter']
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 5
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_INVENTORY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/inventory']
DEFAULT_LOOKUP_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/lookup']
DEFAULT_POLL_INTERVAL(/etc/ansible/ansible.cfg) = 15
DEFAULT_PRIVATE_KEY_FILE(/etc/ansible/ansible.cfg) = /home/yaniv/Documents/LABDyadicSecKeyPair.pem
DEFAULT_STRATEGY_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/strategy']
DEFAULT_TERMINAL_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/terminal']
DEFAULT_TEST_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/test']
DEFAULT_VARS_PLUGIN_PATH(/etc/ansible/ansible.cfg) = [u'/usr/share/ansible/plugins/vars']

##### OS / ENVIRONMENT
Ubuntu 18_4

##### STEPS TO REPRODUCE
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Create security group
      ec2_group:
        name: "Security Group for 12345 yaniv"
        description: "A Security Group for 12345 yaniv"
        region: "us-east-1"
        vpc_id: "vpc-XXXXXX"
        rules:
          - proto: all
            from_port: all
            to_port: all
            group_id: "sg-XXXXXX"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall

##### EXPECTED RESULTS
New group created

##### ACTUAL RESULTS
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_vrXzP2/ansible_module_ec2_group.py", line 1021, in <module>
    main()
  File "/tmp/ansible_vrXzP2/ansible_module_ec2_group.py", line 875, in main
    rules = deduplicate_rules_args(rules_expand_sources(rules_expand_ports(module.params['rules'])))
  File "/tmp/ansible_vrXzP2/ansible_module_ec2_group.py", line 607, in rules_expand_ports
    for rule in rule_expand_ports(rule_complex)]
  File "/tmp/ansible_vrXzP2/ansible_module_ec2_group.py", line 584, in rule_expand_ports
    rule['from_port'] = int(rule.get('from_port'))
ValueError: invalid literal for int() with base 10: 'all'

fatal: [localhost]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_vrXzP2/ansible_module_ec2_group.py\", line 1021, in <module>\n    main()\n  File \"/tmp/ansible_vrXzP2/ansible_module_ec2_group.py\", line 875, in main\n    rules = deduplicate_rules_args(rules_expand_sources(rules_expand_ports(module.params['rules'])))\n  File \"/tmp/ansible_vrXzP2/ansible_module_ec2_group.py\", line 607, in rules_expand_ports\n    for rule in rule_expand_ports(rule_complex)]\n  File \"/tmp/ansible_vrXzP2/ansible_module_ec2_group.py\", line 584, in rule_expand_ports\n    rule['from_port'] = int(rule.get('from_port'))\nValueError: invalid literal for int() with base 10: 'all'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE", 
    "rc": 1
}

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @adq
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by s-hertel** [comment]
Hi @yanivrefael. You need to specify the ports as an integer. 'all' has never been a supported module port, as far as I am aware, so that would be a feature request rather than a bug.
Try something like:
```
- name: Create AWS resources
  hosts: localhost
  connection: local
  gather_facts: True
  tasks:
    - name: Create security group
      ec2_group:
        name: "Security Group for 12345 yaniv"
        description: "A Security Group for 12345 yaniv"
        region: "us-east-1"
        vpc_id: "vpc-XXXXXX"
        rules:
          - proto: all
            from_port: 0
            to_port: 65535
            group_id: "sg-XXXXXX"
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
      register: basic_firewall
```
