### ISSUE TITLE
openshift_raw not handling idempotency correctly for ResourceQuota

### ISSUE THREAD

**Issue by pritho** [ansible/ansible#42241]
##### SUMMARY

Module openshift_raw does not handle idempotency correctly for OpensHift Kind  ResourceQuota
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

openshift_raw
##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/adm.z174498/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT

CentOS 7.5
##### STEPS TO REPRODUCE

```yaml
- name: Create and Apply Burst Quota to project
  openshift_raw:
    verify_ssl: "{{ verify_ssl }}"
    state: "{{ desired_state }}"
    namespace: "{{ project_name }}"
    resource_definition:
      apiVersion: "v1"
      kind: "ResourceQuota"
      metadata:
        name: "default-compute-burst-quota"
      spec:
        hard:
          pods: "{{ burst_pod_quota }}"
          requests.cpu: "{{ burst_requests_cpu }}"
          requests.memory: "{{ burst_requests_memory }}"
          limits.cpu: "{{ burst_limits_cpu }}"
          limits.memory: "{{ burst_limits_memory }}"
```

##### EXPECTED RESULTS

on a second run of the task, status should be ok, rather than changed
##### ACTUAL RESULTS

status is reported as changed after every run

```

```
