### ISSUE TITLE
ios_vlan fails to correctly identify vlans starting with number 9

### ISSUE THREAD

**Issue by jmagudo** [ansible/ansible#42242]
##### SUMMARY
The Fix "ios_vlan to correctly identify unmodified config when having long interface names" #40145 introduces one minor bug. The parser in parse_to_logical_rows(out) ignores vlans starting with number 9.

The line 221:
if '0' < l[0] < '9':
Perhaps should read:
if '0' < l[0] <= '9':

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ios_vlan

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jagudo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/jagudo/dev/venvs/ansible-2.6/local/lib/python2.7/site-packages/ansible
  executable location = /home/jagudo/dev/venvs/ansible-2.6/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### OS / ENVIRONMENT

Running ansible on Ubuntu 18.04
Tested against Cisco IOS 12.2 15.2

##### STEPS TO REPRODUCE

```yaml
---
- hosts: ios_devices
  gather_facts: no
  connection: local

  vars:
    vlans:
      - vlan_id: 1
        name: default
      - vlan_id: 10
        name: Servers
      - vlan_id: 920
        name: Test
      - vlan_id: 1002
        name: fddi-default
      - vlan_id: 1003
        name: token-ring-default
      - vlan_id: 1004
        name: fddinet-default
      - vlan_id: 1005
        name: trnet-default

  tasks:
  - name: Config Vlans
    ios_vlan:
      aggregate: "{{ vlans }}"
      provider: "{{ provider }}"
      purge: yes
    when: vlans is defined
```

##### EXPECTED RESULTS

Config Vlans defined (1,10,920,1002,1003,1004,1005)

##### ACTUAL RESULTS

The vlans starting with 9 are configured each time the playbook is run because the parser ignores the output starting with 9. Also are not purged / removed if state dictates it.

```

```
