### ISSUE TITLE
bigip_pool_member module throws "HTTP Error 401: basic auth failed" when using root account

### ISSUE THREAD

**Issue by WRJFontenot** [ansible/ansible#42266]
##### SUMMARY
If {{ ansible_user }} is set to "root", bigip_pool_member module returns "HTTP Error 401: basic auth failed".  If {{ ansible_user }} is set to a local account with admin rights, bigip_pool_member works as expected.  This problem only occurs with the bigip_pool_member module.  All other modules work with root as expected.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

bigip_pool_member

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /home/xxxxxxx/.ansible.cfg
  configured module search path = [u'/home/xxxxxxxx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### CONFIGURATION

DEFAULT_HOST_LIST(/home/xx0000000/.ansible.cfg) = [u'/home/xx0000000/ansible/etc/hosts']
DEFAULT_ROLES_PATH(/home/xx0000000/.ansible.cfg) = [u'/home/xx0000000/ansible/roles']

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)

##### STEPS TO REPRODUCE

Change 

```
---
# set vars
ansible_user: "root"
ansible_ssh_pass: "{{ vault_ansible_ssh_pass }}"
https_port: "443"

f5_env:
  F5_SERVER: "{{ ansible_host }}"
  F5_USER: "{{ ansible_user }}"
  F5_PASSWORD: "{{ ansible_ssh_pass }}"
  F5_SERVER_PORT: "{{ https_port }}"
  F5_VALIDATE_CERTS: "false"
  PYTHONWARNINGS: "ignore:Unverified HTTPS request"
...

---
# Top level playbook.
# devicelist is a group defined in ~/ansible/etc/hosts
- hosts: "{{ devicelist }}"
  connection: "local"
  environment: "{{ f5_env }}"
  gather_facts: "no"

  tasks:
    - include_tasks: "{{ devicelist }}/bigip_ltm_pools.yaml"
...

YAML file bigip_ltm_pools.yaml:
---
- name: Create pool pl_adfstest.example.com_443
  bigip_pool:
    provider: "{{ f5_rest }}"
    name: "pl_adfstest.example.com_443"
    description: "Internal ADFSIN"
    partition: "{{ f5_partition }}"
    monitor_type: "and_list"
    monitors: "mon_adfs.example.com_443"
    reselect_tries: "0"
    service_down_action: "none"
    slow_ramp_time: "10"
    lb_method: "least-connections-member"
    state: "present"
  delegate_to: "localhost"

- include_tasks: "{{ devicelist }}/bigip_ltm_pool_members/pl_adfstest.example.com_443.yaml"
...

YAML file pl_adfstest.example.com_443.yaml:
---
- name: Add/Delete members to pool pl_adfstest.example.com_443
  bigip_pool_member:
    provider: "{{ f5_rest }}"
    pool: "pl_adfstest.example.com_443"
    port: "443"
    description: "Internal ADFSIN"
    host: "{{ item }}"
    connection_limit: "0"
    rate_limit: "0"
    ratio: "1"
    session_state: "enabled"
    monitor_state: "enabled"
    partition: "{{ f5_partition }}"
    preserve_node: "no"
    priority_group: "0"
    state: "present"
  delegate_to: "localhost"
  loop:
    - node-adfsin003
    - node-adfsin002
...

```

##### EXPECTED RESULTS

bigip_pool_member adds nodes to pool

##### ACTUAL RESULTS

bigip_pool_member fails with following error messages:
failed: [my_bigip -> localhost] (item=node-adfsin003) => {"changed": false, "item": "node-adfsin003", "msg": "received exception: HTTP Error 401: basic auth failed"}
failed: [my_bigip -> localhost] (item=node-adfsin002) => {"changed": false, "item": "node-adfsin002", "msg": "received exception: HTTP Error 401: basic auth failed"}

```

```
