### ISSUE TITLE
RDS arguments not working (db_name & security_groups)

### ISSUE THREAD

**Issue by nicolas-g** [ansible/ansible#4226]
running the bellow playbook I can successfully provision a new RDS instance but the db_name is empty and the security group is always the "default" one .

I have check the security group exist.

```
  ansible --version
  ansible 1.4 (devel 0252aac226) last updated 2013/09/23 10:19:38 (GMT +000)
```
# rds.yml  :

```
- hosts: localhost
  connection: local
  user: root
  gather_facts: false 
  vars:
      instance_type: db.m1.small
      instance_name: rdsdb
      db_name: mydb
      username: root
      password: changeme
      security_groups: my-security-group
      size: 15 
      region: us-east-1
  tasks:
    - name: Launch RDS instance
      local_action: rds db_engine=MySQL command=create instance_name={{ instance_name }} size={{ size }} instance_type={{ instance_type }} username={{ username }} password={{ password }} region={{ region }}
```
