### ISSUE TITLE
vmware_guest: can't create VM on single ESXi with the Free License, vsphere_guest creates successfully

### ISSUE THREAD

**Issue by forensicsguy817** [ansible/ansible#42262]
##### SUMMARY
When creating a VM against a single free license ESXi 6.5 hypervisor using **_vmware_guest_**, a licensing error is generated. When creating a VM against a single free license ESXi 6.5 hypervisor using **_vsphere_guest_**, a licensing error is not generated and the VM is created. This is using ha-datcenter for the datcenter parameter.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = ****
  configured module search path = *****
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

DEFAULT_CALLBACK_PLUGIN_PATH(/home/user1/workspace/project1/code/playbooks/ansible.cfg) = [u'/home/user1/.ansible/plugins/callback_plugins', u'/usr/share/ansible_plugins/callback_plugins', u'/home/user1/workspace/project1/code/playbooks/callback_
DEFAULT_FORKS(/home/user1/workspace/project1/code/playbooks/ansible.cfg) = 30
DEFAULT_MODULE_PATH(/home/user1/workspace/project1/code/playbooks/ansible.cfg) = [u'/usr/share/ansible', u'/home/user1/workspace/project1/code/playbooks/library']

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml

With vmware_guest:

tasks: 
  - vmware_guest:    
      hostname: '{{ vsphere_hostname }}'
      esxi_hostname: '{{ esxi_hostname }}'
      username: '{{ vsphere_username }}'
      password: '{{ vsphere_password }}'
      name: '{{ vm_guest }}'
      guest_id: centos64Guest
      validate_certs: False
      folder: /
      hardware:
        memory_mb: '{{ vm_memory }}'
        num_cpus: '{{ vm_cpu }}'
        scsi: paravirtual
        hotadd_cpu: True
        hotremove_cpu: True
        hotadd_memory: True
      disk:
      - size_gb: '{{ vm_disk_gb }}'
        type: thin
        datastore: '{{ vm_datastore }}'
      networks:   
      - name: '{{ vm_network4 }}'
        device_type: vmxnet3
      - name: '{{ vm_network }}'
        device_type: vmxnet3
      - name: '{{ vm_network2 }}'
        device_type: vmxnet3 
      - name: '{{ vm_network3 }}'  
        device_type: vmxnet3 
      - name: '{{ vm_network5 }}'
        device_type: vmxnet3
      - name: '{{ vm_network6 }}'
        device_type: vmxnet3
      - name: '{{ vm_network7 }}'
        device_type: vmxnet3
      cdrom:
        type: "client"

With vsphere_guest:

tasks:
  - vsphere_guest:
      vcenter_hostname: '{{ vsphere_hostname }}'
      username: '{{ vsphere_username }}'
      password: '{{ vsphere_password }}'
      guest: '{{ vm_guest }}'
      vm_extra_config:
        vcpu.hotadd: yes
        mem.hotadd:  yes
        notes: ' {{ vm_guest }}'
      vm_disk:
        disk1:
          size_gb: '{{ vm_disk_gb }}'
          type: thin
          datastore: '{{ vm_datastore }}'
      vm_nic:
        nic1:
          type: vmxnet3
          network: '{{ vm_network4 }}'
          network_type: standard
        nic2:
          type: vmxnet3
          network: '{{ vm_network }}'
          network_type: standard
        nic3:
          type: vmxnet3
          network: '{{ vm_network2 }}'
          network_type: standard
        nic4:
          type: vmxnet3
          network: '{{ vm_network3 }}'
          network_type: standard
        nic5:
          type: vmxnet3
          network: '{{ vm_network5 }}'
          network_type: standard
        nic6:
          type: vmxnet3
          network: '{{ vm_network6 }}'
          network_type: standard
        nic7:
          type: vmxnet3
          network: '{{ vm_network7 }}'
          network_type: standard
      vm_hardware:
        memory_mb: '{{ vm_memory }}'
        num_cpus: '{{ vm_cpu }}'
        osid: '{{ vm_osid }}'
        scsi: paravirtual
        vm_cdrom:
          type: "client"
      esxi:
        datacenter: '{{ esxi_datacenter }}'
        hostname: '{{ esxi_hostname }}'
      validate_certs: no
```

##### EXPECTED RESULTS

VM Creation

##### ACTUAL RESULTS

VMware licensing error message

```
The full traceback is:
  File "/tmp/ansible_Sv24Vz/ansible_module_vmware_guest.py", line 1700, in deploy_vm
    task = destfolder.CreateVM_Task(config=self.configspec, pool=resource_pool)
  File "/usr/lib64/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/usr/lib64/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/usr/lib64/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1366, in InvokeMethod
    raise obj # pylint: disable-msg=E0702

fatal: [vm1]: FAILED! => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "annotation": null, 
            "cdrom": {
                "type": "client"
            }, 
            "cluster": null, 
            "customization": {}, 
            "customvalues": [], 
            "datacenter": "ha-datacenter", 
            "disk": [
                {
                    "datastore": "datastore1", 
                    "size_gb": 50, 
                    "type": "thin"
                }
            ], 
            "esxi_hostname": "dev-esxi", 
            "folder": "/", 
            "force": false, 
            "guest_id": "centos64Guest", 
            "hardware": {
                "hotadd_cpu": true, 
                "hotadd_memory": true, 
                "hotremove_cpu": true, 
                "memory_mb": 4096, 
                "num_cpus": 2, 
                "scsi": "paravirtual"
            }, 
            "hostname": "x.x.x.x", 
            "is_template": false, 
            "linked_clone": false, 
            "name": "vm1", 
            "name_match": "first", 
            "networks": [
                {
                    "device_type": "vmxnet3", 
                    "name": "Network1", 
                    "type": "dhcp"
                }, 
                {
                    "device_type": "vmxnet3", 
                    "name": "Network2", 
                    "type": "dhcp"
                }, 
                {
                    "device_type": "vmxnet3", 
                    "name": "Network3", 
                    "type": "dhcp"
                }, 
                {
                    "device_type": "vmxnet3", 
                    "name": "Network4", 
                    "type": "dhcp"
                }, 
                {
                    "device_type": "vmxnet3", 
                    "name": "Network5", 
                    "type": "dhcp"
                }, 
                {
                    "device_type": "vmxnet3", 
                    "name": "Network6", 
                    "type": "dhcp"
                }, 
                {
                    "device_type": "vmxnet3", 
                    "name": "Network7", 
                    "type": "dhcp"
                }
            ], 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "resource_pool": null, 
            "snapshot_src": null, 
            "state": "present", 
            "template": null, 
            "username": "ansible", 
            "uuid": null, 
            "validate_certs": false, 
            "wait_for_ip_address": false
        }
    }, 
    "msg": "Failed to create virtual machine due to product versioning restrictions: Current license or ESXi version prohibits execution of the requested operation."
}
```
