### ISSUE TITLE
k8s module does not respect environment variables

### ISSUE THREAD

**Issue by pritho** [ansible/ansible#42299]
##### SUMMARY

k8s module does not respect environment variables
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

k8s
##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible26/lib/python2.7/site-packages/ansible
  executable location = /home/ansible26/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

```

##### STEPS TO REPRODUCE

```yaml
- name: Create/Rename project with api_key set
  k8s:
    api_key: "{{ lookup('env','K8S_AUTH_API_KEY') }}"
    verify_ssl: "{{ verify_ssl }}"
    state: "{{ desired_state }}"
    resource_definition:
      apiVersion: v1
      kind: Project
      metadata:
        name: "{{ project_name }}"

- name: Create/Rename project without api_key set
  k8s:
    verify_ssl: "{{ verify_ssl }}"
    state: "{{ desired_state }}"
    resource_definition:
      apiVersion: v1
      kind: Project
      metadata:
        name: "{{ project_name }}"

```

##### EXPECTED RESULTS

both tasks should work fine
##### ACTUAL RESULTS

```
PLAY [localhost] **********************************************************************************************************************

TASK [new_project : Create/Rename project with api_key set] ********************************************************************************************
ok: [localhost]

TASK [new_project : Create/Rename project without api_key set] ********************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'str' object has no attribute 'get'
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_faTahb/ansible_module_k8s.py\", line 165, in <module>\n    main()\n  File \"/tmp/ansible_faTahb/ansible_module_k8s.py\", line 161, in main\n    KubernetesRawModule().execute_module()\n  File \"/tmp/ansible_faTahb/ansible_modlib.zip/ansible/module_utils/k8s/raw.py\", line 70, in execute_module\n  File \"/tmp/ansible_faTahb/ansible_modlib.zip/ansible/module_utils/k8s/common.py\", line 167, in get_api_client\n  File \"/home/ansible26/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 58, in __init__\n    self._load_server_info()\n  File \"/home/ansible26/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 62, in _load_server_info\n    self.__version = {'kubernetes': load_json(self.request('get', '/version'))}\n  File \"/home/ansible26/lib/python2.7/site-packages/openshift/dynamic/client.py\", line 255, in request\n    _return_http_data_only=params.get('_return_http_data_only', True)\n  File \"/home/ansible26/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 321, in call_api\n    _return_http_data_only, collection_formats, _preload_content, _request_timeout)\n  File \"/home/ansible26/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 140, in __call_api\n    self.update_params_for_auth(header_params, query_params, auth_settings)\n  File \"/home/ansible26/lib/python2.7/site-packages/kubernetes/client/api_client.py\", line 499, in update_params_for_auth\n    auth_setting = self.configuration.auth_settings().get(auth)\n  File \"/home/ansible26/lib/python2.7/site-packages/kubernetes/client/configuration.py\", line 228, in auth_settings\n    'value': self.get_api_key_with_prefix('authorization')\n  File \"/home/ansible26/lib/python2.7/site-packages/kubernetes/client/configuration.py\", line 202, in get_api_key_with_prefix\n    if self.api_key.get(identifier) and self.api_key_prefix.get(identifier):\nAttributeError: 'str' object has no attribute 'get'\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/home/openshift-self-services/create_new_oc_project.retry

PLAY RECAP ****************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1


```
