### ISSUE TITLE
Assign AWS Cloudwatch Metric Filter via Ansible

### ISSUE THREAD

**Issue by kellervater** [ansible/ansible#42292]
##### SUMMARY

In Ansible I can create Cloudwatch log groups via the module cloudwatchlogs_log_group.

But I can't figure out if there's any module (or option in the above mentioned module) to create a metric filter.

My use-case is to create a metric filter which creates datapoints for each exception which will rise in my application. 
Furthermore I've created an alarm to get notified if this metric is getting above 0 within a specific time window. It is no problem to do this manually but I want to have this configuration stored within my ansible roles.

If I make an educated guess, I would say this functionality isn't yet implemented, but I wanted to ask you if you can advise here.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

cloudwatchlogs_log_group_metric_filter

##### ANSIBLE VERSION

```
2.5.5
```

##### CONFIGURATION

HOST_KEY_CHECKING(/home/ec2-user/.ansible.cfg) = False

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
cloudwatchlogs_log_group_metric_filter:
  log_group_name: myloggroup
  filter_name: myfilter
  filter_pattern: Pool got destroyed
  metric_value: 1
  default_value: 0
```

##### EXPECTED RESULTS

I would expect that the metric filter would be attached to the specific log group and I can create alarms (with ```ec2_metric_alarm```) to handle exceptions.
##### ACTUAL RESULTS

not implemented yet.

```

```
