### ISSUE TITLE
Passed role variables does get overwritten by role variables

### ISSUE THREAD

**Issue by jmartensson** [ansible/ansible#42293]
##### SUMMARY

Role variables passed in from playbook get overwritten by variables defined in role after execution.
The variable gets overridden and works great in role, but not after

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /usr/users/joma43/ulvs.ansible/ansible.cfg
  configured module search path = [u'/usr/users/joma43/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### OS / ENVIRONMENT

RHEL 7

##### STEPS TO REPRODUCE

playbook.yml
```yaml
---
- name: Testing var
  hosts: localhost
  gather_facts: false
  become: false

  roles:
    - { role: vartest,
          my_var: this is my_var defined in playbook
      }

  tasks:
    - name: Debug my_var outside after role execution
      debug:
        var: my_var
```

roles/vartest/defaults/main.yml
```yaml
---
my_var: this is my_var defined in role vartest
```
roles/vartest/tasks/main.yml
```yaml
---
- name: Debug my_var inside role
  debug:
    var: my_var
```

##### EXPECTED RESULTS

```
TASK [vartest : Debug my_var inside role] ********************************************************************************************************************************
ok: [localhost] => {
    "my_var": "this is my_var defined in playbook"
}

TASK [Debug my_var outside after role execution] *************************************************************************************************************************
ok: [localhost] => {
    "my_var": "this is my_var defined in playbook"
}
```
##### ACTUAL RESULTS

```
TASK [vartest : Debug my_var inside role] ********************************************************************************************************************************
ok: [localhost] => {
    "my_var": "this is my_var defined in playbook"
}

TASK [Debug my_var outside after role execution] *************************************************************************************************************************
ok: [localhost] => {
    "my_var": "this is my_var defined in role vartest"
}
```

```

```

**Comment by jmartensson** [comment]
Possible duplicate of #21890

It works as expected if I add this in the end of the role, roles/vartest/tasks/main.yml
```
- name: Set fact
  set_fact:
    my_var: "{{ my_var }}" 
```

**Comment by sivel** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

In particular, we believe you have said:

   * Vars supplied to a role are not being exposed to the remainder of the playbook.

However, however what is happening is that:

   * supplying `my_var: this is my_var defined in playbook` under `roles` for an individual role only exposes that variable to that specific role.

We would suggest:

   * Supply the var via `vars` such as:

     ```
     roles:
       - role: vartest
         vars:
           my_var: this is my_var defined in playbook
     ```

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!
