### ISSUE TITLE
In k8s module ReplicationControllers are not removed when removing DeploymentConfig

### ISSUE THREAD

**Issue by ruromero** [ansible/ansible#42302]
##### SUMMARY
When using k8s module to deprovision a DeploymentConfig, the associated ReplicationControllers are not removed.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
k8s

##### ANSIBLE VERSION
```
  ansible 2.7.0.dev0
  config file = /opt/apb/ansible.cfg
  configured module search path = [u'/opt/apb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible-2.7.0.dev0-py2.7.egg/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION
```
DEFAULT_HOST_LIST(/opt/apb/ansible.cfg) = [u'/opt/apb/hosts']
DEFAULT_ROLES_PATH(/opt/apb/ansible.cfg) = [u'/etc/ansible/roles', u'/opt/ansible/roles']
RETRY_FILES_ENABLED(/opt/apb/ansible.cfg) = False
```

##### OS / ENVIRONMENT
docker.io/ansibleplaybookbundle/apb-base   canary    d11e0960e7d4

##### STEPS TO REPRODUCE

```yaml
    - name: "[TEST] deploy business central"
      k8s:
        api_version: v1
        state: absent
        name: mysql
        namespace: testns
        kind: DeploymentConfig
```

##### EXPECTED RESULTS
```
$ oc get po,rc,dc -n testns
No resources found.
```

##### ACTUAL RESULTS
DeploymentConfig is removed, however the ReplicationController is not
```
NAME                     READY     STATUS RESTARTS   AGE
po/mysql-1-kh2jx        1/1       Running   0          3m

NAME      DESIRED   CURRENT   READY     AGE
rc/mysql-1    1         1         0         3m
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/clustering/k8s/k8s.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/clustering/k8s/k8s.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @chouseknecht @fabianvf @flaper87 @maxamillion
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by fabianvf** [comment]
Could I see the task for creating the deploymentconfig as well?

**Comment by ruromero** [comment]
Adapted from here: https://github.com/ruromero/rhpam-apb/blob/k8s/roles/deploy-businesscentral/tasks/main.yml#L38

I have tested with the following snippet and having a separate task for provisioning and deprovisioning like the one described before. Both have the same result. Delete the deploymentConfig but not the replicationControllers
  ```
  - name: "[TEST] deploy business central"
      k8s:
        state: '{{ state }}'
        definition: "{{ lookup('template', 'businesscentral-dc.yml.j2') | from_yaml }}"
```

**Comment by ansibot** [comment]
cc @willthames
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by willthames** [comment]
Interesting. This is a tricky one, I'm not sure how the cascading works in kubectl but clearly it does manage to do it.

There is very little logic in the k8s module itself, it mostly just passes everything off to the kubernetes API, and so it would involve special behaviour just for cascading deletion of deployments, unless there's some API flag that we could be setting but aren't.

**Comment by fabianvf** [comment]
There are generic delete options that can be passed with delete, though we probably need changes in the client as well

**Comment by fahanson** [comment]
As I was trying to debug this issue this morning I thought it had been fixed in `openshift-restclient-python` with the Foreground Propagation Policy being set now [1]. Obviously this is not the case. I could work around this by searching for currently active ReplicaSets with a name filter, but that doesn't work either (possibly another bug incoming about k8s Lists not working).

I am dead in the water with this one. Our use case is to let engineers spin up and test branches, and then destroy when done, all using Tower.

1. https://github.com/openshift/openshift-restclient-python/commit/31581bdc9cad334a31e921f52ae72ee53b7db831#diff-93163b9d3a7911b26d817c4c84079df1

**Comment by fabianvf** [comment]
@fahanson Searching for resources should work using the [k8s lookup plugin](https://docs.ansible.com/ansible/latest/plugins/lookup/k8s.html), the k8s module is mostly for interacting with a specific resource. 

As for the propagation policy bug, unfortunately the client was rearchitected and this is a regression to the previous default behavior. I will try to get support for this in the client ASAP, sorry for the trouble.

**Comment by fahanson** [comment]
@fabianvf Thanks for the quick reply, and for pointing me towards the lookup plugin! With this I am at least able to put together a workaround. 

For others in this situation the below snippit will search for your `ReplicaSet` by a label, pull the name, and then delete said ReplicaSet:

```yaml
---
  - name: find replicaset with branch name
    set_fact:
      replicaset: "{{ lookup('k8s', kind='ReplicaSet', namespace='default', label_selector='branch=testing') }}"

  - name: delete the replicaset
    k8s:
      state: absent
      api_version: v1
      kind: ReplicaSet
      namespace: default
      name: "{{ replicaset.metadata.name }}"
```

**Comment by fabianvf** [comment]
Awesome, glad that at least got you unstuck. For my k8s roles I usually toss the lookup into the vars field of the task itself, just to make it clear that I'm not planning on using the variable in a later task/prevent accidental collisions. Not any functional difference though, just letting people know they can do that in case they need to do a lot of deletes and don't want to have a bunch of set_facts tasks.

```yaml
- name: delete the replicaset
  k8s:
    state: absent
    api_version: v1
    kind: ReplicaSet
    namespace: default
    name: "{{ replicaset.metadata.name }}"
  vars:
    replicaset: "{{ lookup('k8s', kind='ReplicaSet', namespace='default', label_selector='branch=testing') }}"
```

**Comment by willthames** [comment]
I can't reproduce this with deleting Deployments (rather than deleting DeploymentController).

Is there a reason for deleting the DeploymentController?

**Comment by fahanson** [comment]
@willthames I'm treating it the same as I would if I was running `kubectl apply -f` or `kubectel delete -f` on the command line. So my deploy and delete task both look like this:

```yaml
  - name: Deploy the app
    k8s:
      state: present
      definition: "{{ lookup('template', 'microbot-app.yml') | from_yaml }}"

  - name: Delete the app
    k8s:
      state: absent
      definition: "{{ lookup('template', 'microbot-app.yml') | from_yaml }}"
```
Doing it this way deletes the deployment, but not the ReplicaSet or the Pods themselves (since they are in the ReplicaSet).

**Comment by willthames** [comment]
@fahanson, sure - I wonder if this is an Openshift issue rather than an ansible module issue.

I tested using the openshift-origin 3.9.0 container, ansible 2.7 (just to get me k8s_facts) and openshift 0.6.0 and kubernetes 6.0.0 (which I suspect is what most people have) - deleting a Deployment does delete the related ReplicaSet.

However, as you say, deleting a DeploymentConfig does not delete the ReplicationController. Since the k8s module does the right thing with Deployments, perhaps Openshift is not respecting propagation on DeploymentConfig deletion (or perhaps it's expected behavior - I have no idea as I only use kubernetes, not openshift)

**Comment by ruromero** [comment]
> However, as you say, deleting a DeploymentConfig does not delete the ReplicationController. Since the k8s module does the right thing with Deployments, perhaps Openshift is not respecting propagation on DeploymentConfig deletion (or perhaps it's expected behavior - I have no idea as I only use kubernetes, not openshift)

This is not the expected behaviour for Openshift. When you manually delete a DeploymentConfig, the associated ReplicationControllers are also deleted. This is not the case for the ansible module.

**Comment by rdonkin** [comment]
I have the same issue with deleting a DaemonSet with Ansible 2.7.10 - the pods are not deleted, so I'm using similar code to @fahanson - thanks for that.

It would be good if the `k8s` module docs state that delete cascade is not implemented, since this is the default for kubectl.

**Comment by willthames** [comment]
Given that there's a test case that works on kubernetes proper, I'm open to investigating the difference further.

Certainly deleting deployments works fine, so I'm not sure what daemonsets do differently.

@rdonkin Could you provide a simple test case that works with kubectl but doesn't work with ansible, for standard kubernetes resources only (i.e. no special openshift resources) and I'll take a look at what's being done differently under the hood.

**Comment by rdonkin** [comment]
@willthames I'm using Kubernetes 1.11 on EKS so you are correct that it's not OpenShift.  Kubectl is 1.12.7.

The code for deleting a DaemonSet including workaround is below - if you remove the 2nd and 4th tasks that should show the issue.  

```
- name:  Force removal of Datadog
  set_fact:
    datadog_agent_state: absent

# k8s module doesn't do delete-cascade from DaemonSet (unlike kubectl default),
# so we must explicitly find and remove any pods. Important to find the pods first,
# before deleting the daemonset, and actually delete the pods afterwards - otherwise
# controller will re-create pods right away.
- name: Find Datadog agent pods to be removed, if required
  set_fact:
    pod_list: "{{ lookup('k8s', kind='Pod', namespace=app_namespace, label_selector='app=datadog-agent') }}"
  when: not enable_datadog

- name: Ensure Datadog agent is deployed in (or removed from) cluster via DaemonSet etc
  k8s:
    state: "{{ datadog_agent_state }}"
    definition: "{{ lookup('template', '../kube/app/cots-datadog-agent.yaml') }}"
    namespace: "{{ app_namespace }}"

- name: Ensure Datadog agent pods are removed, if required
  k8s:
    state: absent
    kind: Pod
    name: "{{ item.metadata.name }}"
    namespace: "{{ app_namespace }}"
    api_version: v1
  loop: "{{ pod_list }}"
  when: not enable_datadog
```

K8s manifest - [gist](https://gist.github.com/rdonkin/b60593c5a5f0cd54db36447290fe9ced)

This should be enough to show the problem. Kubectl does do delete-cascade as expected here, whereas Ansible did not without this workaround.

```
vagrant@vagrant:~/devel/abt-iac/ansible$ kubectl get pod | grep datadog-agent
datadog-agent-d44rn                                           1/1     Running     0          53d
datadog-agent-q4km9                                           1/1     Running     0          53d
datadog-agent-w77xz                                           1/1     Running     0          53d
vagrant@vagrant:~/devel/abt-iac/ansible$ kubectl delete ds datadog-agent
daemonset.extensions "datadog-agent" deleted
vagrant@vagrant:~/devel/abt-iac/ansible$ kubectl get pod | grep datadog-agent
datadog-agent-w77xz                                           0/1     Terminating   0          53d
vagrant@vagrant:~/devel/abt-iac/ansible$ kubectl get pod | grep datadog-agent
datadog-agent-w77xz                                           0/1     Terminating   0          53d
```
