### ISSUE TITLE
Handlers containing a block are not found

### ISSUE THREAD

**Issue by fthommen** [ansible/ansible#42353]
##### SUMMARY

Handlers containing a block are not found when running the playbook

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

block
handlers

##### ANSIBLE VERSION

```
ansible 2.4.2.0
  config file = /CENSORED/ansible.cfg
  configured module search path = [u'/CENSORED/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

##### CONFIGURATION

```
DEFAULT_CALLBACK_PLUGIN_PATH(/CENSORED/ansible.cfg) = [u'/CENSORED/lib/callback_plugins']
DEFAULT_GATHERING(/CENSORED/ansible.cfg) = smart
DEFAULT_GATHER_SUBSET(/CENSORED/ansible.cfg) = min
DEFAULT_HOST_LIST(/CENSORED/ansible.cfg) = [u'/CENSORED/inventory']
DEFAULT_LOG_PATH(/CENSOREDansible.cfg) = /CENSORED/ansible.log
HOST_KEY_CHECKING(/CENSORED/ansible.cfg) = False
```

##### OS / ENVIRONMENT

  * run from: CentOS Linux release 7.4.1708 (Core) 
  * managing: CentOS Linux release 7.2.1511 (Core) 

##### STEPS TO REPRODUCE

Run the following playbook:

```yaml
---
- hosts: all
  name: Testing handlers with block
  tasks:
    - name: Print something
      shell:  "echo HALLO"
      notify: my handler

  handlers:
    - name: my handler
      block:
        - name: my first subhandler
          shell: "echo FIRST SUBHANDLER"

        - name: my second subhandler
          shell: "echo SECOND SUBHANDLER"

```

##### EXPECTED RESULTS

```
$ ansible-playbook ./test_block_in_handler.yml --limit=myhost --user=root
[DEPRECATION WARNING]: default callback, does not support setting 'options',
it will work for now, but this will be required in the future and should be updated,
see the 2.4 porting guide for details.. This feature will be removed in version 2.9.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.

PLAY [Testing handlers with block] **********

TASK [Gathering Facts] **********
ok: [myhost]

TASK [Print something] **********
changed: [myhost]

RUNNING HANDLER [my first subhandler] **********
changed: [myhost]

RUNNING HANDLER [my second subhandler] **********
changed: [myhost]

PLAY RECAP **********
myhost             : ok=4    changed=3    unreachable=0    failed=0
$
```

##### ACTUAL RESULTS

```
$ ansible-playbook ./test_block_in_handler.yml --limit=myhost --user=root
[DEPRECATION WARNING]: default callback, does not support setting 'options',
it will work for now, but this will be required in the future and should be updated,
see the 2.4 porting guide for details.. This feature will be removed in version 2.9.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.

PLAY [Testing handlers with block] **********

TASK [Gathering Facts] **********
ok: [myhost]

TASK [Print something] **********
ERROR! The requested handler 'my handler' was not found in either the main
handlers list nor in the listening handlers list
$

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/block.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/block.py)
* [lib/ansible/playbook/handler.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/handler.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
This is not a bug as [`search_handler_blocks_by_name()`](https://github.com/ansible/ansible/blob/133b70ff4503be52b007d3abe642d7d7f360b686/lib/ansible/plugins/strategy/__init__.py#L369-L369) only looks at task names within a block but not the block name itself. The reason for this is block names inside dynamically included roles are not "inherited up" to the calling task, making it difficult to use the block name to trigger blocks of handlers within dynamically included roles.

In order to fire multiple handlers, add `listen` to each of your handlers.

```yaml
  handlers:
    - name: my first subhandler
      shell: "echo FIRST SUBHANDLER"
      listen: my handler

    - name: my second subhandler
      shell: "echo SECOND SUBHANDLER"
      listen: my handler

```

If you feel this feature would be very useful and `listen` does not meet your needs, please open a new issue as a feature request.
