### ISSUE TITLE
gcp_compute_instance_template ability to use ephemeral external ips / not requiring nat_ip

### ISSUE THREAD

**Issue by hornjason** [ansible/ansible#42358]
##### SUMMARY
gcp_compute_instance_template requires the use of nat_ip which pins the template to one static external address,  if using the template to create multiple instances on ephemeral ext. ips only one will receive an external ip while the others won't be created. 

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

gcp_compute_instance_template

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /vagrant/git/ansible-ocp-gcp/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

ansible-config dump --only-changed
ANSIBLE_NOCOWS(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = True
ANSIBLE_PIPELINING(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s -o UserKnownHostsFile=/dev/nu
ANSIBLE_SSH_CONTROL_PATH(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = %(directory)s/%%h-%%r
CACHE_PLUGIN(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = /root/ansible/facts
CACHE_PLUGIN_TIMEOUT(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = 600
DEFAULT_CALLBACK_WHITELIST(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = 20
DEFAULT_GATHERING(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = smart
DEFAULT_HOST_LIST(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = [u'/vagrant/git/ansible-ocp-gcp/hosts']
DEFAULT_LOG_PATH(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = /vagrant/git/ansible-ocp-gcp/ansible.log
DEFAULT_REMOTE_USER(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = root
DEFAULT_ROLES_PATH(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = [u'/vagrant/git/ansible-ocp-gcp/roles']
HOST_KEY_CHECKING(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = 30
##### OS / ENVIRONMENT

rhel 7.5
##### STEPS TO REPRODUCE

```yaml
    - name: GCP | Template cloud-init
      template:
        src: cloud-init.j2
        dest: files/cloud-init

    - name: GCP | Create a network
      gcp_compute_network:
        name: 'ocp-network'
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: network

    - name: GCP | Create address space
      gcp_compute_address:
        name: 'ocp-address-1'
        region: "{{ cloud_infrastructure.region }}"
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address

    - name: GCP | Manage MASTER instance template
      gcp_compute_instance_template:
        name: "{{ env_id  }}-master-template"
        state: present
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        scopes:
          - https://www.googleapis.com/auth/cloud.useraccounts.readonly
          - https://www.googleapis.com/auth/compute
          - https://www.googleapis.com/auth/devstorage.read_only
          - https://www.googleapis.com/auth/logging.write
          - https://www.googleapis.com/auth/monitoring.write
          - https://www.googleapis.com/auth/service.management.readonly
          - https://www.googleapis.com/auth/servicecontrol
        properties:
          can_ip_forward: no
          disks:
            - auto_delete: true
              index: 0
              boot: true
              device_name: "{{ env_id }}-master-boot"
              initialize_params:
                source_image: "{{ cloud_infrastructure.image_name }}"
                #disk_name: "{{ env_id }}-master-boot"
                #disk_type: "{{ cloud_infrastructure.masters.disk_type }}"
                disk_size_gb: 40
            - auto_delete: true
              index: 1
              boot: false
              device_name: "{{ env_id }}-master-containers"
              initialize_params:
                #disk_name: "{{ env_id }}-master-containers"
                #disk_type: "{{ cloud_infrastructure.masters.disk_type }}"
                disk_size_gb: 20
            - auto_delete: true
              index: 2
              boot: false
              device_name: "{{ env_id }}-master-etcd"
              initialize_params:
                #disk_name: "{{ env_id }}-master-etcd"
                #disk_type: "{{ cloud_infrastructure.masters.disk_type }}"
                disk_size_gb: 50
            - auto_delete: true
              index: 3
              boot: false
              device_name: "{{ env_id }}-master-local"
              initialize_params:
                #disk_name: "{{ env_id }}-master-local"
                #disk_type: "{{ cloud_infrastructure.masters.disk_type }}"
                disk_size_gb: 30
          metadata:
            items:
              - key: startup-script
                value: |
                   {{lookup('file', 'files/master.sh')}}
              - key: user-data
                value: |
                  {{lookup('file', 'files/cloud-init')}}
          machine_type: "{{ cloud_infrastructure.masters.flavor }}"
          network_interfaces:
            - network:  "{{ network }}"
              access_configs:
                - name: external-nat
                  type: 'ONE_TO_ONE_NAT'
                  #nat_ip: "{{ address }}"
          scheduling:
            automatic_restart: true
            on_host_maintenance: migrate
            preemptible: "{{ cloud_infrastructure.masters.preemptible }}"
          tags:
            items:
            - "{{ env_id }}"
            - "{{ env_id }}-master"
            - "{{ env_id }}-node"
      register: master_template
      tags: master

    - name: create master target pool
      gcp_compute_target_pool:
        name: "{{ env_id }}-master-pool"
        region: "{{ cloud_infrastructure.region }}"
        project: "{{ project_id }}"
        service_account_file: "{{ credentials_file }}"
        auth_kind: serviceaccount
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: master_tp

    - name: create a instance group manager
      gcp_compute_instance_group_manager:
        name: "{{ env_id }}-master-igm"
        state: present
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        base_instance_name: "{{ env_id }}-master"
        instance_template: "{{ master_template }}"
        named_ports:
          - name: "{{ env_id }}-web-console"
            port: 443
        target_size: "{{ cloud_infrastructure.masters.count }}"
        target_pools:
          - "{{ master_tp }}"
        zone: 'us-central1-a'
        #- 'us-west1-c'
        #  - 'us-west1-f'
      tags: master

```

##### EXPECTED RESULTS

3 instances should be created with ephemeral external ips.  
##### ACTUAL RESULTS

1 instance is created using the network resource with a static external ip the other 2 fail to provision ips since tied to the address resource.  After making nat_ip required=False things work as expected hence the commented #nat_ip in above play.

```

```
