### ISSUE TITLE
groups not working as expected

### ISSUE THREAD

**Issue by ochurlaud** [ansible/ansible#42360]
##### SUMMARY

The groups do not allow multiple inclusions.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ansible-core

##### ANSIBLE VERSION

```
2.5.4
```

##### OS / ENVIRONMENT

Redhat 7.2 (but I don't think it's platform specific)

##### STEPS TO REPRODUCE

I have an inventory like:
```yaml
all: 
  children: 
    group1:
      children:
         webmail:
           hosts:
             server1:
    group2:
      children:
         webmail:
           hosts:
             server2:
```
And I set common variables in groupvars for group1  (group: 1), group2 (group: 2) and webmail (varwebmail: toto).

now `ansible-inventory --graph` says:

```
@all:
   |--@group1:
   |   |--@webmail:
   |      |--server1
   |      |--server2
   |--@group2
   |   |--@webmail:
   |      |--server1
   |      |--server2
```

and `ansible-inventory -i inv --host serv1` returns 

```
{
  "varwebmail": "toto",
  "group": 2
}
```
whereas group should be 1.

##### EXPECTED RESULTS

`ansible-inventory --graph` says:

```
@all:
   |--@group1:
   |   |--@webmail:
   |      |--serv1
   |--@group2
   |   |--@webmail:
   |      |--serv2
```
##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
None

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
Possible Misunderstanding
=========================

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We believe the ticket you have filed is being somewhat misunderstood, as one thing works a little differently than stated.

Group names are unique, you can repeat it multiple times in an inventory but it is the same group, all hosts and vars will accumulate into it.

In the future, this might be a topic more well suited for the user list, which you can also post here if you'd like some more help with the above.
   
   * https://groups.google.com/forum/#!forum/ansible-project

Thank you once again for this and your interest in Ansible!

**Comment by ochurlaud** [comment]
@bcoca Could you just explain what what I'm expecting is not unique? 

I'm hopping that if I manage two clusters with the same type of machines I can do intersections of groups, like stated in the documentation: "webservers:&phoenix". 
If it is not the case, it seems that it defeats the purpose.

 What is the correct way?

**Comment by bcoca** [comment]
you can still do group intersections, but that is not the same thing as a parent/child relationship.

With this definition, the intersection would not matter as they are all in the same group via parent child, if you define them as 3 separate groups then the intersection works:
```
all: 
  children: 
    group1:
      hosts:
         server1:
    group2:
       hosts:
          server2:
    webmail:
        hosts:
            server1:
            server2:
```
