### ISSUE TITLE
Allow "changed_when" to evaluate a list 

### ISSUE THREAD

**Issue by vincentvdk** [ansible/ansible#4236]
When using the "changed_when" option it would be convenient to pass a list of values that get evaluated ( a bit like with_items) before the action is marked as "changed"

this is an example 

``` yaml
 - name: detect and register current java      
    action: shell update-alternatives --display java | grep currently | awk '{print $5}'
    register: java_alternatives
    changed_when: java_alternatives.stdout != {{ item }}
    with_items:
      - /usr/java/jdk1.6.0_43/bin/java
      - /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java
```

**Comment by vincentvdk** [comment]
After talking to benno on #ansible it came to mind that you can evaluate a list like so

``` yaml
- name: detect and register current java      
   action: shell update-alternatives --display java | grep currently | awk '{print $5}'
   register: java_alternatives
   changed_when: java_alternatives.stdout not in ['/usr/java/jdk1.6.0_43/bin/java', '/usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java']
```
