### ISSUE TITLE
gcp_compute_instance_group_manager doesn't support multi-zone 

### ISSUE THREAD

**Issue by hornjason** [ansible/ansible#42378]
##### SUMMARY

No support for creating a managed instance group in multiple zones.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

gcp_compute_instance_group_manager.py
##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = /vagrant/git/ansible-ocp-gcp/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

ansible-config dump --only-changed
ANSIBLE_NOCOWS(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = True
ANSIBLE_PIPELINING(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = -o ControlMaster=auto -o ControlPersist=600s -o UserKnownHostsFile=/dev/nu
ANSIBLE_SSH_CONTROL_PATH(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = %(directory)s/%%h-%%r
CACHE_PLUGIN(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = jsonfile
CACHE_PLUGIN_CONNECTION(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = /root/ansible/facts
CACHE_PLUGIN_TIMEOUT(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = 600
DEFAULT_CALLBACK_WHITELIST(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = ['profile_tasks']
DEFAULT_FORKS(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = 20
DEFAULT_GATHERING(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = smart
DEFAULT_HOST_LIST(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = [u'/vagrant/git/ansible-ocp-gcp/hosts']
DEFAULT_LOG_PATH(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = /vagrant/git/ansible-ocp-gcp/ansible.log
DEFAULT_REMOTE_USER(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = root
DEFAULT_ROLES_PATH(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = [u'/vagrant/git/ansible-ocp-gcp/roles']
HOST_KEY_CHECKING(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = False
PERSISTENT_CONNECT_TIMEOUT(/vagrant/git/ansible-ocp-gcp/ansible.cfg) = 30
##### OS / ENVIRONMENT

RHEL 7.5
##### STEPS TO REPRODUCE

```yaml
    - name: create a instance group manager
      gcp_compute_instance_group_manager:
        name: "{{ env_id }}-master-igm"
        state: present
        project: "{{ project_id }}"
        auth_kind: serviceaccount
        service_account_file: "{{ credentials_file }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        base_instance_name: "{{ env_id }}-master"
        instance_template: "{{ master_template }}"
        named_ports:
          - name: "{{ env_id }}-web-console"
            port: 443
        target_size: "{{ cloud_infrastructure.masters.count }}"
        target_pools:
          - "{{ master_tp }}"
        zones:
          - 'us-central1-a'
          - 'us-west1-c'
          - 'us-west1
```

##### ACTUAL RESULTS

```

```
