### ISSUE TITLE
No Package matching ... found available, installed or updated when using YUM and with_items 

### ISSUE THREAD

**Issue by davistran86** [ansible/ansible#42404]
##### SUMMARY
I tried to install multiple apps using yum and with_items, it always shows error "No Package matching ... found available, installed or updated"

I tested with just 1 app to install with 2 tasks, 1 without with_items and 1 with with_items.  

As you can see below, first task was ok, but second task was showing error No Package matching... ? even it's the same httpd

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

yum

##### ANSIBLE VERSION
```
ansible 2.5.5
  config file = /root/ansible-ivy/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION
```
[defaults]
inventory = inventory
host_key_checking = False
```
##### STEPS TO REPRODUCE

```yaml
---
- hosts: all
  become: true
  tasks:
    - name: First task install httpd
      yum:
        name: httpd
        state: present
        update_cache: true

    - name: Second task install httpd
      yum:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items:
        - httpd
```

##### EXPECTED RESULTS
Application is installed 

##### ACTUAL RESULTS
It's reporting No Package matching ... found available, installed or updated 
```
PLAY [all] *******************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************
ok: [192.168.73.222]

TASK [First task install httpd] **********************************************************************************************************
ok: [192.168.73.222]

TASK [Second task install httpd] *********************************************************************************************************
failed: [192.168.73.222] (item=[u'httpd']) => {"changed": false, "item": ["httpd"], "msg": "No Package matching '['httpd']' found available, installed or updated", "rc": 0, "results": []}
        to retry, use: --limit @/root/ansible-ivy/test.retry

PLAY RECAP *******************************************************************************************************************************
192.168.73.222             : ok=2    changed=0    unreachable=0    failed=1
```
