### ISSUE TITLE
Allow specifying a section in package.json where to install a package with yarn

### ISSUE THREAD

**Issue by astorije** [ansible/ansible#42434]
##### SUMMARY

At the moment, the `yarn` module, when passed a package (using `name`) installs with `yarn add x`, which means [per the doc](https://yarnpkg.com/lang/en/docs/cli/add/#toc-yarn-add) that the package will be installed in the `dependencies` section. A new optional attribute could specify where to save the package.

This would avoid running `command: yarn add --dev x` directly.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

`yarn`

##### ANSIBLE VERSION

```
ansible 2.6.0
  config file = None
  configured module search path = [u'/Users/astorije/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

`ansible-config dump --only-changed` returned nothing.

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml

- name: Ensure x is installed as in dependencies
  yarn:
    name: x
    path: /my/project

- name: Ensure y is installed in devDependencies
  yarn:
    name: y
    path: /my/project
    type: devDependencies
```

- Not specifying `type` is equivalent to specifying `type: dependencies` (which is the current behavior)
- Possible values are: `dependencies`, `devDependencies`, `optionalDependencies`, `peerDependencies`, and `bundledDependencies`
- This should not be compatible with `global: yes`, as this applies for local installs only
- `type` is obviously just a suggestion, let me know if anyone can think of something better (`section`?)

##### EXPECTED RESULTS

The package is added in the corresponding section in `package.json`.
