### ISSUE TITLE
BigIP F5 Playbook 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by ro8harp** [ansible/ansible#42447]
##### SUMMARY

Simple BigIp Playbook failed with "ansible.errors.AnsibleConnectionFailure: 'NoneType' object has no attribute 'lower'"  Originally had the issue on RedHatl6.9 with Ansible 2.5.5, so created a new virtual env  to test behavior on newer software, see below.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

bigip_command

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

no setting changed default

##### OS / ENVIRONMENT

CentOS Linux release 7.5.1804 (Core)
BIG-IP Version 12.1.3.5

##### STEPS TO REPRODUCE

```yaml
---

#F5 Gathering Show Version
- hosts: dev-f5
  connection: local
  gather_facts: no

  tasks:

    - name: F5 Show Version
      register: F5ShowVersion
      bigip_command:
        user: test
        password: testing
        transport: cli
        commands:
          - "show sys version"
      delegate_to: localhost

    - name: F5 Storing Show Version
      copy:
        content: "{{ F5ShowVersion.stdout[0] }}"
        dest: "/etc/ansible/results/version/{{ inventory_hostname }}-f5showversion.txt"
```

##### EXPECTED RESULTS

n/a
##### ACTUAL RESULTS

dev-f5 : ok=0    changed=0    unreachable=0    failed=1

```
[root@c522c3d822aa ansible]# ansible-playbook f5-show-ver.yml -vvvv
ansible-playbook 2.6.1
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 3.6.5 (default, Apr 10 2018, 17:08:37) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
No config file found; using defaults
setting up inventory plugins
Parsed /etc/ansible/hosts inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python3.6/site-packages/ansible/plugins/callback/default.py

PLAYBOOK: f5-show-ver.yml ***********************************************************************************************************************************************************************************************
1 plays in f5-show-ver.yml

PLAY [dev-f5] *************************************************************************************************************************************************************************************
META: ran handlers

TASK [F5 Show Version] **************************************************************************************************************************************************************************************************
task path: /etc/ansible/f5-show-ver.yml:13
<dev-f5> connection transport is cli
using connection plugin network_cli
starting connection from persistent connection plugin
local domain socket does not exist, starting it
control socket path is /root/.ansible/pc/e165e9bb18

The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 344, in _connect_uncached
    self._play_context.remote_addr.lower(),
AttributeError: 'NoneType' object has no attribute 'lower'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/ansible-connection", line 87, in start
    self.connection._connect()
  File "/usr/lib/python3.6/site-packages/ansible/plugins/connection/network_cli.py", line 298, in _connect
    ssh = self.paramiko_conn._connect()
  File "/usr/lib/python3.6/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 249, in _connect
    self.ssh = SSH_CONNECTION_CACHE[cache_key] = self._connect_uncached()
  File "/usr/lib/python3.6/site-packages/ansible/plugins/connection/paramiko_ssh.py", line 365, in _connect_uncached
    raise AnsibleConnectionFailure(msg)
ansible.errors.AnsibleConnectionFailure: 'NoneType' object has no attribute 'lower'

fatal: [dev-f5]: FAILED! => {
    "msg": "'NoneType' object has no attribute 'lower'"
}
	to retry, use: --limit @/etc/ansible/f5-show-ver.retry

PLAY RECAP **************************************************************************************************************************************************************************************************************
dev-f5 : ok=0    changed=0    unreachable=0    failed=1
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/network/f5/bigip_command.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/network/f5/bigip_command.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @caphrim007
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ro8harp** [comment]
@bcoca 
I saw that you removed needs_triage. Is this a known issue or already being worked? I did search and didn't find any issue like this. Also my first time posting a bug and am not too familiar with why tags get added or removed. 

This was also tested in my mac where the same issues above shows up.

Thanks

**Comment by caphrim007** [comment]
@ro8harp he removed it because he looked at the issue and saw that I was cc'd in it. I'm the maintainer of these

**Comment by caphrim007** [comment]
@ro8harp the following should unblock you


```
#F5 Gathering Show Version
- hosts: "f5-test[0]"
  gather_facts: no

  tasks:

    - name: F5 Show Version
      bigip_command:
        server: "{{ ansible_host }}"
        user: test
        password: testing
        transport: cli
        commands:
          - "show sys version"
      delegate_to: localhost
```

In other words, include the `server` param
