### ISSUE TITLE
s3_bucket error - Module_six_moves_urllib_parse object is not callable.

### ISSUE THREAD

**Issue by benbro** [ansible/ansible#42459]
##### SUMMARY
When trying to create s3_bucket I'm getting an error.
This is a regression. Worked in ansible 2.4.
Might be related to:
https://github.com/ansible/ansible/issues/27566
https://github.com/ansible/ansible/pull/27568

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
s3_bucket

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
I'm using python3:
inventories/production/hosts
```
[all:vars]
ansible_python_interpreter=/usr/bin/python3
```

##### OS / ENVIRONMENT
Ubuntu 18.04.

##### STEPS TO REPRODUCE
```yaml
- name: python3-botocore package
  apt:
    name: python3-botocore
    state: latest

- name: python3-boto package
  apt:
    name: python3-boto
    state: latest

- name: create bucket
  s3_bucket:
    name: mybucket
    state: present
    aws_access_key: "{{key}}"
    aws_secret_key: "{{secret}}"
    s3_url: "{{url}}"
    ceph: true
```

##### EXPECTED RESULTS
No error

##### ACTUAL RESULTS
```
Traceback (most recent call last):
File "/tmp/ansible_546eises/ansible_module_s3_bucket.py", line 558, in <module> main()
File "/tmp/ansible_546eises/ansible_module_s3_bucket.py", line 544, in main
s3_client = get_s3_client(module, aws_connect_kwargs, location, ceph, s3_url)
File "/tmp/ansible_546eises/ansible_module_s3_bucket.py", line 476, in get_s3_client
ceph = urlparse(s3_url)
TypeError: 'Module_six_moves_urllib_parse' object is not callable
```
