### ISSUE TITLE
nmcli bridge-slave returns "Error: invalid or not allowed setting 'bridge-port'"

### ISSUE THREAD

**Issue by gregsheremeta** [ansible/ansible#42460]
##### SUMMARY

nmcli bridge-slave returns "Error: invalid or not allowed setting 'bridge-port'"

Relevant lines of code in nmcli.py:

https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/nmcli.py#L1000

```
        options = {
            'master': self.master,
            'bridge-port.path-cost': self.path_cost,
            'bridge-port.hairpin': self.bool_to_string(self.hairpin),
            'bridge-port.priority': self.slavepriority,
        }
```

To work around, I commented out the 3 'bridge-port' lines in nmcli.py

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

nmcli

##### ANSIBLE VERSION

```
% ansible --version
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/greg/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

From: Fedora 28
Managing: Centos 7

##### STEPS TO REPRODUCE

See: https://groups.google.com/forum/#!topic/ansible-devel/lRizb7grom0

```yaml
- set_fact:
    bridge_slave: "{{ ansible_interfaces | difference(['lo','br0']) | first }}"

- name: setup bridge
  nmcli:
    type: bridge
    conn_name: br0
    state: present

- name: setup bridge slave
  nmcli:
    type: bridge-slave
    conn_name: "{{ bridge_slave }}"
    state: present
    master: br0
```

##### EXPECTED RESULTS

br0 created and the nic slaved to it

##### ACTUAL RESULTS

Error: invalid or not allowed setting 'bridge-port'

```
fatal: [host]: FAILED! => {"changed": false, "msg": "Error: invalid or not allowed setting 'bridge-port': 'bridge-port' not among [connection, 802-3-ethernet (ethernet), 802-1x, dcb, ipv4, ipv6, tc, proxy].\n", "name": "enp0s31f6", "rc": 2}
```
