### ISSUE TITLE
Undefined Variables in a playbook aren't caught if they are set by a role or role dependency

### ISSUE THREAD

**Issue by darkone23** [ansible/ansible#4247]
if I say:

``` yaml
- hosts: local
  connection: local

  roles:
    - foo
    - role: bar
      src: "{{ app_src }}"
```

Even though I have not set `app_src`, if the role `foo` set it I will wind up with their value instead of realizing I forgot to set my own.  Maybe we could instead check for undefined before we do roles & includes instead of at task evaluation time?

Thanks,
Thomas
