### ISSUE TITLE
regression in user module on FreeBSD 11.1 target starting with v2.6.0: always 'changed'

### ISSUE THREAD

**Issue by nusenu** [ansible/ansible#42484]
##### SUMMARY
the user module always returns 'changed' on FreeBSD targets (does not happen on Debian targets)

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
user module

##### ANSIBLE VERSION
```
ansible 2.6.1
   python version = 2.7.15
```

##### CONFIGURATION

```ansible-config dump --only-changed``` is empty

##### OS / ENVIRONMENT
Target: FreeBSD 11.1

##### STEPS TO REPRODUCE

using ansible < 2.6.0:
clone https://github.com/nusenu/ansible-relayor 
(tested with 730a332b02697be1d93cf1b254b4827443fb5e5b)
```
kitchen test t-guard-freebsd-11
```
--> works as expected

do the same with ansible >= 2.6.0 (confirmed with ansible 2.6.0 and 2.6.1) and get failed idempotency tests:
```
idempotency test [Failed]
```

the relevant task failing the idempotency test after upgrading ansible:

```
- name: Ensure per-instance tor users exist
  become: yes
  user:
    name: _tor-{{ item.0.ipv4 }}_{{ item.1.orport }}
    system: yes
    shell: /bin/false
    createhome: no
    home: "{{ tor_DataDir }}/{{ item.0.ipv4 }}_{{ item.1.orport }}"
  with_nested:
   - "{{ tor_ips }}"
   - "{{ tor_ports }}"
```

##### EXPECTED RESULTS
idempotency should not fail as with ansible versions before 2.6.0

##### ACTUAL RESULTS

```
idempotency test [Failed]
        1> {"changed_module_name": "", "changed_msg": "All items completed", "changed_module_args": "", "host": "guard-freebsd-11", "task_name": "Ensure per-instance tor users exist"}
```
