### ISSUE TITLE
DNSimple still uses v1 API (shut down)

### ISSUE THREAD

**Issue by andrenarchy** [ansible/ansible#42495]
##### SUMMARY

Creating a new TXT record fails with `API v1 is no longer available, please upgrade to API v2. See https://blog.dnsimple.com/2018/03/api-v1-shutdown-notice/`.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

dnsimple

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/andre/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

```
Linux baozi 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

##### STEPS TO REPRODUCE

```yaml
---
# create a key + csr like this:
# openssl genrsa -out domain.key 4096
# openssl req -new -key domain.key -out domain.csr
- hosts: 127.0.0.1
  connection: local
  name: Create SSL certificate with letsencrypt
  tasks:
  - letsencrypt:
      acme_directory: https://acme-v01.api.letsencrypt.org/directory
      account_key: files/letsencrypt/account.key
      csr: files/letsencrypt/mail.paperhive.org.csr
      dest: files/letsencrypt/mail.paperhive.org.crt
      challenge: dns-01
      remaining_days: 20
    register: challenge

  - dnsimple:
      account_email: "{{dnsimple_email}}"
      account_api_token: "{{dnsimple_tokens['paperhive.org']}}"
      domain: paperhive.org
      record: "{{item.value['dns-01']['resource']}}.{{item.key | regex_replace('\\.paperhive\\.org$', '')}}"
      solo: true
      type: TXT
      value: "{{item.value['dns-01']['resource_value']}}"
      state: present
      ttl: "{{dnsimple_ttl}}"
    when: challenge|changed
    with_dict: "{{challenge['challenge_data']}}"
```

##### EXPECTED RESULTS

The DNS record gets created

##### ACTUAL RESULTS

The DNS record does not get created and an error is shown, see below.

```
PLAY [Create SSL certificate with letsencrypt] ************************************************************************************************************************************************************************************************************************

TASK [Gathering Facts] ************************************************************************************************************************************************************************************************************************************************
ok: [127.0.0.1]

TASK [letsencrypt] ****************************************************************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: The 'letsencrypt' module is being renamed 'acme_certificate'. This feature will be removed in version 2.1. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
changed: [127.0.0.1]

TASK [dnsimple] *******************************************************************************************************************************************************************************************************************************************************
[DEPRECATION WARNING]: Using tests as filters is deprecated. Instead of using `result|changed` use `result is changed`. This feature will be removed in version 2.9. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [127.0.0.1] (item={'value': {u'http-01': {u'resource_value': u'XXXXX', u'resource': u'.well-known/acme-challenge/XXXXX'}, u'dns-01': {u'resource_value': u'XXXXX', u'resource': u'_acme-challenge', u'record': u'_acme-challenge.mail.paperhive.org'}}, 'key': u'mail.paperhive.org'}) => {"changed": false, "item": {"key": "mail.paperhive.org", "value": {"dns-01": {"record": "_acme-challenge.mail.paperhive.org", "resource": "_acme-challenge", "resource_value": "XXXXX"}, "http-01": {"resource": "XXXXX", "resource_value": "XXXXX"}}}, "msg": "Unable to contact DNSimple: {u'message': u'API v1 is no longer available, please upgrade to API v2. See https://blog.dnsimple.com/2018/03/api-v1-shutdown-notice/'}"}
```
