### ISSUE TITLE
azure_rm_virtualmachine ignores CoreOS version

### ISSUE THREAD

**Issue by IvanovOleg** [ansible/ansible#42497]
##### SUMMARY

The azure_rm_virtualmachine module ignores OS version and install the latest available
##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
2.6.1
```

##### OS / ENVIRONMENT

Centos 7
##### STEPS TO REPRODUCE

```
base_image:
  offer: CoreOS
  publisher: CoreOS
  sku: Alpha
  version: 1814.0.0
```
```
- name: Create a virtual machine
  local_action:
    module: azure_rm_virtualmachine
    resource_group: "{{ resource_group_name }}"
    name: "{{ vm_name }}"
    vm_size: "{{ instance_type }}"
    data_disks: "{{ vm_data_disks | default(omit) }}"
    managed_disk_type: "{{ managed_disk_type }}"
    availability_set: "{{ availability_set_member | ternary(availability_set_name, omit) }}"
    admin_username: "{{ ansible_ssh_user }}"
    ssh_password_enabled: False
    ssh_public_keys: "{{ ssh_keys }}"
    network_interfaces: "{{ network_interface }}"
    image: "{{ base_image }}"
    tags: "{{ instance_tags }}"
```

##### EXPECTED RESULTS

Container Linux by CoreOS alpha (1814.0.0)
##### ACTUAL RESULTS

Container Linux by CoreOS alpha (1828.0.0)

```

```
