### ISSUE TITLE
s3_bucket error with Minio - GetBucketVersioning NotImplemented

### ISSUE THREAD

**Issue by benbro** [ansible/ansible#42501]
##### SUMMARY
When trying to create a [minio](https://minio.io/) bucket with s3_bucket I'm getting an error because minio doesn't support bucket versioning.
This is a regression. Worked in ansible 2.4.
Might be after the migration to boto3:
PR https://github.com/ansible/ansible/pull/37189

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
s3_bucket

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION
I'm using python3:
inventories/production/hosts
```
[all:vars]
ansible_python_interpreter=/usr/bin/python3
```

##### OS / ENVIRONMENT
Ubuntu 18.04.

##### STEPS TO REPRODUCE
PR https://github.com/ansible/ansible/pull/42474 is required to test and prevent issue https://github.com/ansible/ansible/issues/42459

```yaml
- name: python3-botocore package
  apt:
    name: python3-botocore
    state: latest

- name: python3-boto package
  apt:
    name: python3-boto
    state: latest

- name: create bucket
  s3_bucket:
    name: mybucket
    state: present
    aws_access_key: "{{key}}"
    aws_secret_key: "{{secret}}"
    s3_url: "{{url}}"
    ceph: true
```

##### EXPECTED RESULTS
No error

##### ACTUAL RESULTS
```
botocore.exceptions.ClientError: An error occurred (NotImplemented) when calling the GetBucketVersioning operation: A header you provided implies functionality that is not implemented.
```

I think that the module tries to ignore versioning if the option isn't set but fails to do that.
