### ISSUE TITLE
at module should allow direct time-of-day specification

### ISSUE THREAD

**Issue by eric-b-hymowitz** [ansible/ansible#42524]
##### SUMMARY
The `at` module allows users to specify a command to be run a specific number of minutes/hours/days/weeks in the future. However, the underlying `at` command allows (and arguably more often uses) a specific day/date/time to be chosen instead of a time delta in the future.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

at

##### ANSIBLE VERSION

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ehymowitz/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) [GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
```

##### CONFIGURATION

DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 20
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 60

##### OS / ENVIRONMENT

RedHat RHEL6

##### STEPS TO REPRODUCE

```
- name: Schedule a command to execute at 2300 this evening
  at:
    command: ls -d / >/dev/null
    timespec: 2300

- name: Schedule a command to execute at 2300 tomorrow
  at:
    command: ls -d / >/dev/null
    timespec: 2300
    dayspec: tomorrow

- name: Schedule a command to execute at 2300 on the specified date
  at:
    command: ls -d / >/dev/null
    timespec: 201807012300

- name: Schedule a command to execute at 2300 on the specified date
  at:
    command: ls -d / >/dev/null
    timespec: 2018-07-01T23:00
```

##### EXPECTED RESULTS

A command should be scheduled to run at a specific date/time.

##### ACTUAL RESULTS

```
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (at) module: timespec Supported parameters include: command, count, script_file, state, unique, units"}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/system/at.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/system/at.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @risaacson
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by bcoca** [comment]
What we actually want to do is create 'date time' filters to allow passing the data to modules, i.e:

`-  at: timespec='{{"tomorrow"|to_epoch}}'`

**Comment by jerrac** [comment]
Having just needed the opening posts described feature, I'll add my two cents. (And risk bumping an old issue...)

Using filters to set a specific time seems a bit overly complicated to me. I think it makes more sense to directly copy the syntax used by the `at` command. 

```yaml
- at:
    timespec: 4am
    command: echo foobar > /dev/null
```
