### ISSUE TITLE
apt_repository module does not work behind proxy on ubuntu

### ISSUE THREAD

**Issue by hangsu-ma** [ansible/ansible#42534]
##### SUMMARY

apt_repository is calling apt-key when adding new repo source. apt-key does not respect http_proxy env var nor Acquire::http::Proxy specified in apt conf files. However it does support proxy setting passed in from --keyserver-options parameter. Current apt_repository is missing logic to handle keyserver-options.
Therefore apt_repository will not be able to add new repo behind proxy on ubuntu
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

apt_repository
##### ANSIBLE VERSION

```
all
```

##### OS / ENVIRONMENT

target env: ubuntu
##### STEPS TO REPRODUCE

```yaml
- apt_repository:
    repo: 'ppa:git-core/ppa'
    state: absent
    validate_certs: false
    update_cache: yes
  environment:
    http_proxy: http://proxy.example.com:8080
  become: yes
```

##### EXPECTED RESULTS

repo been added
##### ACTUAL RESULTS

```
failing on apt-key command
```
