### ISSUE TITLE
elb_application_lb Unknown parameter in input: "Type"

### ISSUE THREAD

**Issue by ivanbaldo** [ansible/ansible#42540]
##### SUMMARY
elb_application_lb fails with "Unknown parameter in input: "Type", must be one of: Name, Subnets, SecurityGroups, Scheme, Tags

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
elb_application_lb

##### ANSIBLE VERSION
```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ibaldo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
ANSIBLE_PIPELINING(/etc/ansible/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/etc/ansible/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=7200s
COMMAND_WARNINGS(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(env: ANSIBLE_INVENTORY) = [u'/home/ibaldo/XXXXXX/ec2.py']
DEFAULT_SQUASH_ACTIONS(/etc/ansible/ansible.cfg) = ['apk', 'apt', 'dnf', 'homebrew', 'pacman', 'pkgng', 'yum', 'zypper']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 30
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /home/ibaldo/XXXXXX
ERROR_ON_MISSING_HANDLER(/etc/ansible/ansible.cfg) = True
PERSISTENT_CONNECT_TIMEOUT(/etc/ansible/ansible.cfg) = 7200
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Ubuntu 16.04.4 LTS

##### STEPS TO REPRODUCE

```yaml
    - name: Application Load Balancer Web
      elb_application_lb:
        name: XXXXXX
        security_groups:
          - XXXXXX
        subnets:
          - "subnet-XXXXXX"
          - "subnet-XXXXXX"
        listeners:
          - Protocol: HTTP
            Port: 80
            DefaultActions:
              - Type: forward
                TargetGroupName: XXXXXX
          - Protocol: HTTPS
            Port: 443
            DefaultActions:
              - Type: forward
                TargetGroupName: XXXXXX
            Certificates:
              - CertificateArn: "arn:aws:acm:us-east-1:XXXXXX:certificate/XXXXXX"
            SslPolicy: ELBSecurityPolicy-2016-08
        state: present
        tags: {Name: XXXXXX}
        region: "us-east-1"
        access_logs_enabled: yes
        access_logs_s3_bucket: XXXXXX
        access_logs_s3_prefix: XXXXXX
```

##### EXPECTED RESULTS
ALB created.

##### ACTUAL RESULTS
ALB creation failed.
```
TASK [Application Load Balancer Web] ************************************************************************************************************
task path: /home/ibaldo/Dropbox/XXXXXX/dev_create.yml:312
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/amazon/elb_application_lb.py
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: ibaldo
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_h7zeS5/ansible_modlib.zip/ansible/module_utils/aws/elbv2.py", line 256, in create_elb
    self.elb = AWSRetry.jittered_backoff()(self.connection.create_load_balancer)(**params)['LoadBalancers'][0]
  File "/tmp/ansible_h7zeS5/ansible_modlib.zip/ansible/module_utils/cloud.py", line 153, in retry_func
    raise e
ParamValidationError: Parameter validation failed:
Unknown parameter in input: "Type", must be one of: Name, Subnets, SecurityGroups, Scheme, Tags

fatal: [localhost]: FAILED! => {
    "boto3_version": "1.2.2", 
    "botocore_version": "1.4.70", 
    "changed": false, 
    "invocation": {
        "module_args": {
            "access_logs_enabled": true, 
            "access_logs_s3_bucket": "XXXXXX", 
            "access_logs_s3_prefix": "XXXXXX", 
            "aws_access_key": null, 
            "aws_secret_key": null, 
            "deletion_protection": null, 
            "ec2_url": null, 
            "idle_timeout": null, 
            "listeners": [
                {
                    "Certificates": null, 
                    "DefaultActions": [
                        {
                            "TargetGroupName": "XXXXXX", 
                            "Type": "forward"
                        }
                    ], 
                    "Port": 80, 
                    "Protocol": "HTTP", 
                    "Rules": null, 
                    "SslPolicy": null
                }, 
                {
                    "Certificates": [
                        {
                            "CertificateArn": "arn:aws:acm:us-east-1:XXXXXX:certificate/XXXXXX"
                        }
                    ], 
                    "DefaultActions": [
                        {
                            "TargetGroupName": "XXXXXX", 
                            "Type": "forward"
                        }
                    ], 
                    "Port": 443, 
                    "Protocol": "HTTPS", 
                    "Rules": null, 
                    "SslPolicy": "ELBSecurityPolicy-2016-08"
                }
            ], 
            "name": "XXXXXX", 
            "profile": null, 
            "purge_listeners": true, 
            "purge_tags": true, 
            "region": "us-east-1", 
            "scheme": "internet-facing", 
            "security_groups": [
                "XXXXXX"
            ], 
            "security_token": null, 
            "state": "present", 
            "subnets": [
                "subnet-XXXXXX", 
                "subnet-XXXXXX"
            ], 
            "tags": {
                "Name": "XXXXXX"
            }, 
            "validate_certs": true, 
            "wait": false, 
            "wait_timeout": null
        }
    }, 
    "msg": "Parameter validation failed:\nUnknown parameter in input: \"Type\", must be one of: Name, Subnets, SecurityGroups, Scheme, Tags"
}
```
