### ISSUE TITLE
vmware_guest: Unable to set hostname to FQDN

### ISSUE THREAD

**Issue by bjorntj** [ansible/ansible#42551]
I am using ansbile 2.6.1 and trying to create a VM guest based on a template, using the following playbook:

```
- name: Create VM from template
  vmware_guest:
    hostname: vcenter
    username: user
    password: pass
    validate_certs: no
    datacenter: dc
    cluster: C1-DC1
    name: host.domain.no
    template: RHEL-7
    folder: dc/vm/folder
    state: poweredon
    disk: 
      - size_gb: 30
        type: thin
        datastore: C1-DC1-FLASH  
      - size_gb: 40
        type: thin
        datastore: C1-DC1-FLASH
    hardware:
      memory_gb: 4
      num_cpus: 4
    networks:
    - name: VLAN_830
      type: static
      ip: 192.168.245.151
      netmask: 255.255.252.0
      gateway: 192.168.245.1
    customization:      
      dns_servers: 192.168.1.53      
      dns_suffix: domain.no
      hostname: host.domain.no
      domain: domain.no

```
When using this playbook, the hostname for the guest becomes: hostdomainno (i.e. the periods are just removed).
Shouldn't this work or?
