### ISSUE TITLE
Installing packages via apt ignores RUNLEVEL on Ubuntu 18.04

### ISSUE THREAD

**Issue by richard-scott** [ansible/ansible#42560]
##### SUMMARY

When installing new packages and you don't want then to start you used to be able to set an environment variable of RUNLEVEL: 1. This no longer works on Ubuntu 18.04, but works on 16.04
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

apt

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

##### CONFIGURATION

Nothing changed from install.

##### OS / ENVIRONMENT

Ubuntu 18.04

##### STEPS TO REPRODUCE

```yaml
- name: Add 'Docker-CE' GPG Key.
  become: true
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"

- name: "Adding: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
  become: true
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable" update_cache=yes

- name: Install some packages from the 'Docker-CE' repo.
  become: true
  register: apt_install
  environment:
    RUNLEVEL: 1
  apt:
    name: docker-ce
```

##### EXPECTED RESULTS

There should be no docker service running.

##### ACTUAL RESULTS

The docker service is running

```
$ ps -edf | grep dockerd
root     28102     1  0 08:47 ?        00:00:01 /usr/bin/dockerd -H fd://
```
