### ISSUE TITLE
docker_container don't Support docker tag 

### ISSUE THREAD

**Issue by ilanni2460** [ansible/ansible#42565]
SUMMARY
We use docker_container to create a docker container
this docker registry is docker.ga096.cn/cfds/crm:1.0.0.20180503_CRM

ISSUE TYPE
Feature Idea
COMPONENT NAME
docker_container
this ansible playbook：
```yaml
---
- hosts: '{{ host }}'
  remote_user: root
  vars:
    app_name: crm
    docker_image_name: docker.ga096.cn/cfds/crm
    tag_name: 1.0.0.20180503_CRM
    port_name: 8082

  tasks:
    - name: Install docker-py
      pip: name=docker-py

    - name: pull docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ tag_name }}"

    - name: stop and remove a container 
      docker_container: 
        name: "{{ app_name }}"
        state: absent

    - name: start docker container 
      docker_container: 
        name: "{{ app_name }}"
        image: "{{ docker_image_name }}"
        **tag: "{{ tag_name }}"**
        state: started
        published_ports:
          - "{{ port_name }}"
        volumes:
          - /data/logs:/data/logs
          - /data/hosts:/etc/hosts
```

this error is：
```
fatal: [192.168.30.24]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (docker_container) module: tag Supported parameters include: api_version, auto_remove, blkio_weight, cacert_path, capabilities, cert_path, cleanup, command, cpu_period, cpu_quota, cpu_shares, cpuset_cpus, cpuset_mems, debug, detach, devices, dns_opts, dns_search_domains, dns_servers, docker_host, domainname, entrypoint, env, env_file, etc_hosts, exposed_ports, force_kill, groups, hostname, ignore_image, image, init, interactive, ipc_mode, keep_volumes, kernel_memory, key_path, kill_signal, labels, links, log_driver, log_options, mac_address, memory, memory_reservation, memory_swap, memory_swappiness, name, network_mode, networks, oom_killer, oom_score_adj, paused, pid_mode, privileged, published_ports, pull, purge_networks, read_only, recreate, restart, restart_policy, restart_retries, security_opts, shm_size, ssl_version, state, stop_signal, stop_timeout, sysctls, timeout, tls, tls_hostname, tls_verify, tmpfs, trust_image_content, tty, ulimits, user, userns_mode, uts, volume_driver, volumes, volumes_from, working_dir"}
```

**Comment by ansibot** [comment]
@duanzhanling Greetings! Thanks for taking the time to open this issue. In order for the community to handle your issue effectively, we need a bit more information. 

Here are the items we could not find in your description:
- component name

Please set the description of this issue with this template:
https://raw.githubusercontent.com/ansible/ansible/devel/.github/ISSUE_TEMPLATE.md

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ilanni2460** [comment]
```yaml
cat > startContainer.yml << "EOF"
---
- hosts: '{{ host }}'
  remote_user: root
  vars:
    app_name: crm
    docker_image_name: docker.ga096.cn/cfds/crm
    tag_name: 1.0.0.20180503_CRM
    port_name: 8082

  tasks:
    - name: Install docker-py
      pip: name=docker-py

    - name: pull docker image
      docker_image:
        name: "{{ docker_image_name }}"
        tag: "{{ tag_name }}"

    - name: stop and remove a container 
      docker_container: 
        name: "{{ app_name }}"
        state: absent

    - name: start docker container 
      docker_container: 
        name: "{{ app_name }}"
        image: "{{ docker_image_name }}':'{{ tag_name }}"
        state: started
        restart_policy: always
        published_ports:
          - "{{ port_name }}"
        volumes:
          - /data/logs:/data/logs
          - /data/hosts:/etc/hosts
EOF


this is new playbook file,then the error is ：

TASK [start docker container] ******************************************************************************************************************************************************************************
Tuesday 10 July 2018  07:58:33 -0400 (0:00:00.504)       0:00:01.892 **********
fatal: [192.168.30.24]: FAILED! => {"changed": false, "msg": "Error pulling image docker.ga096.cn/cfds/crm\":\"1.0.0.20180503_CRM - 500 Server Error: Internal Server Error (\"{\"message\":\"Error parsing reference: \\\"docker.ga096.cn/cfds/crm\\\\\\\"\\\" is not a valid repository/tag: invalid reference format\"}\")"}
```
