### ISSUE TITLE
nmcli module always sets hairpin mode to 1 for bridge slaves.

### ISSUE THREAD

**Issue by tripledes** [ansible/ansible#42569]
##### SUMMARY
<!--- Explain the problem briefly -->
Using `nmcli` module for creating/managing bridges, always sets `hairpin_mode` to 1, no matter what value is set on the playbook (no, yes, true or false).

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
<!--- Insert, BELOW THIS COMMENT, the name of the module, plugin, task or feature.
Do not include extra details here, e.g. "vyos_command" not "the network module vyos_command" or the full path-->
nmcli

##### ANSIBLE VERSION
<!--- Paste, BELOW THIS COMMENT, verbatim output from "ansible --version" between quotes below -->
```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/sjr/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/sjr/.pyenv/versions/2.7.15/envs/ansible-2.6-py2/lib/python2.7/site-packages/ansible
  executable location = /home/sjr/.pyenv/versions/ansible-2.6-py2/bin/ansible
  python version = 2.7.15 (default, May 13 2018, 21:50:46) [GCC 8.1.0]
```

##### CONFIGURATION
<!--- If using Ansible 2.4 or above, paste, BELOW THIS COMMENT, the results of "ansible-config dump --only-changed"
Otherwise, mention any settings you have changed/added/removed in ansible.cfg
(or using the ANSIBLE_* environment variables).-->
Nothing changed.

##### OS / ENVIRONMENT
<!--- Mention, BELOW THIS COMMENT, the OS you are running Ansible from, and the OS you are
managing, or say "N/A" for anything that is not platform-specific.
Also mention the specific version of what you are trying to control,
e.g. if this is a network bug the version of firmware on the network device.-->
Ansible running on Arch Linux, managed machines are CentOS 7.

##### STEPS TO REPRODUCE
<!--- For bugs, show exactly how to reproduce the problem, using a minimal test-case.
For new features, show how the feature would be used. -->

<!--- Paste example playbooks or commands between quotes below -->
```yaml
- name: Configure bridge slaves                                                                                                                                                                                                                                                  
  nmcli:                                                                                                                                                                                                                                                                         
    state: present                                                                                                                                                                                                                                                               
    type: bridge-slave                                                                                                                                                                                                                                                           
    conn_name: "{{ item.bridge_conn_name }}"                                                                                                                                                                                                                                     
    ifname: "{{ item.ifname }}"                                                                                                                                                                                                                                                  
    autoconnect: yes                                                                                                                                                                                                                                                             
    master: br0                                                                                                                                                                                                                                                                  
    hairpin: no                                                                                                                                                                                                                                                                  
  with_items: "{{ virt_phys_ifnames }}"
```

<!--- You can also paste gist.github.com links for larger files -->

##### EXPECTED RESULTS
<!--- What did you expect to happen when running the steps above? -->
BRIDGING_OPTS=hairpin_mode=0
##### ACTUAL RESULTS
<!--- What actually happened? If possible run with extra verbosity (-vvvv) -->
BRIDGING_OPTS=hairpin_mode=1
<!--- Paste verbatim command output between quotes below -->
