### ISSUE TITLE
aws_batch_job_definition doesn't accept True for privileged option

### ISSUE THREAD

**Issue by backaf** [ansible/ansible#42581]
##### SUMMARY

When using the aws_batch_job_definition module to define `privileged: True` or `privileged: yes` it fails with the following error:

```
TASK [infrastructure-model : define batch job] ************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Invalid type for parameter containerProperties
.privileged, value: 1, type: <type 'str'>, valid types: <type 'bool'>
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error registering job definition: Parameter validation failed:\nInvalid type for para
meter containerProperties.privileged, value: 1, type: <type 'str'>, valid types: <type 'bool'>"} 
```

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

aws_batch_job_definition

##### ANSIBLE VERSION

```
ansible 2.5.2
```

##### OS / ENVIRONMENT

Debian Stretch

##### STEPS TO REPRODUCE

```yaml
  - name: define batch job
    aws_batch_job_definition:
      profile: "{{ cloud_profile }}"
      region: "{{ cloud_region }}"
      job_definition_name: "{{ aws_batch_job_name }}"
      state: present
      type: container
      image: "{{ aws_ecr_info.repository.repositoryUri }}"
      vcpus: "{{ aws_batch_job_vcpus }}"
      memory: "{{ aws_batch_job_memory }}"
      command: "{{ aws_batch_job_command }}"
      attempts: "{{ aws_batch_job_attempts }}"
      privileged: yes
    tags:
      - batch
```

##### EXPECTED RESULTS

Playbook should not fail.

The issue is fixed by adding the type bool to the privileged option:

`privileged=dict(type='bool')`
