### ISSUE TITLE
vmware_guest - VM instantiation with IPv6 errors out

### ISSUE THREAD

**Issue by dhurtakolha** [ansible/ansible#42614]
##### SUMMARY

I am trying to create VMs with IPv6 address assignments using Ansible vmware_guest module. Specifying IPv6 address and IPv6 Gateway address under "network" config option throws the following error after VM creation
Failed to create a virtual machine : A specified parameter was not correct: spec.nicSettingMap.adapter.ip.ipAddress

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vmware_guest

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = ansible.cfg
  configured module search path = [u'/Users/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

DEFAULT_CALLBACK_WHITELIST(...) = ['profile_tasks']

##### OS / ENVIRONMENT

MAC : Darwin  17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

##### STEPS TO REPRODUCE

Creating VM using vmware_guest module using following options:
```yaml
 - name: "Start Static-IPv6 VM"
   vmware_guest:
     hostname: "myhost"
     username: "test"
     password: "test"
     esxi_hostname: "10.1.1.1"
     validate_certs: False
     datacenter: Datacenter
     name: "myhost" 
     template: "vm-template"
     folder: /
     disk:   
       - size_gb: 8
         type: thin
         datastore: "Datastore"
     hardware:
       memory: 32768
       num_cpus: 2
     networks:
     - name: VM Network 
       ip: "2201:430:28f:2032::100"
       netmask: "255.255.255.0"
       gateway: "2201:430:28f:2032::1"
     customization:
       dns_servers: "8.8.8.8"
     wait_for_ip_address: yes 
     state: present 
```

```yaml

 - name: "Start Static-IPv6 VM"
   vmware_guest:
     hostname: "myhost"
     username: "test"
     password: "test"
     esxi_hostname: "10.1.1.1"
     validate_certs: False
     datacenter: Datacenter
     name: "myhost" 
     template: "vm-template"
     folder: /
     disk:   
       - size_gb: 8
         type: thin
         datastore: "Datastore"
     hardware:
       memory: 32768
       num_cpus: 2
     networks:
     - name: VM Network 
       ip: "2201:430:28f:2032::100"
       netmask: "255.255.255.0"
       gateway: "2201:430:28f:2032::10"
     customization:
       dns_servers: "8.8.8.8"
     wait_for_ip_address: yes 
     state: present 

```

##### EXPECTED RESULTS

VM with IPv6 address should get created

##### ACTUAL RESULTS

Script errors out .

```
TASK [Start Static-IP master VMs] ***********************************************************************************************************************************************************************
Tuesday 10 July 2018  23:05:04 -0700 (0:00:00.097)       0:00:01.071 ********** 
failed: [localhost] (item={'changed': False, '_ansible_no_log': False, 'failed': False, '_ansible_item_result': True, 'item': {u'mem_mb': u'32768', u'gwv6': u'2201:430:28f:2032::1, u'name': u'master01', u'disk_gb': u'24', u'num_cpus': u'48', u'mask': u'255.255.255.0', u'user': u'root', u'dns': u'172.23.136.143', u'ipv6': u'2001:420:28f:2032::10c'}, 'ansible_facts': {u'master_vm_ip': u'2201:430:28f:2032::10', u'master_vm_name': u'master01', u'master_vm_gw': u'2201:430:28f:2032::1'}, '_ansible_ignore_errors': None}) => {"changed": false, "item": {"ansible_facts": {"master_vm_gw": "2201:430:28f:2032::1", "master_vm_ip": "2201:430:28f:2032::10", "master_vm_name": "master01"}, "changed": false, "failed": false, "item": {"disk_gb": "24", "dns": "8.8.8.8", "gw": "10.1.1..1", "gwv6": "2201:430:28f:2032::1", "ip": "10.1.80.100", "ipv6": "2201:430:28f:2032::1", "mask": "255.255.255.0", "mem_mb": "32768", "name": "master01", "num_cpus": "4"}}, "msg": "Failed to create a virtual machine : A specified parameter was not correct: d"}
	to retry, use: --limit @/packaging/vsphere-vm-setup.retry

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/vmware/vmware_guest.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/vmware/vmware_guest.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @Akasurde @dav1x @nerzhul @pdellaert @warthog9
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by Akasurde** [comment]
@dhurtakolha Thanks for reporting this issue. I will try to reproduce on my setup.

**Comment by Akasurde** [comment]
@dhurtakolha I am able to reproduce this in my environment. `vmware_guest` does not support IPv6 yet.

**Comment by Akasurde** [comment]
@dhurtakolha Could you please test this branch https://github.com/ansible/ansible/compare/devel...Akasurde:i42614 and let me know if it works for you ?
You need to specify ipv6 with this patch as - 

```yaml
        networks:
          - name: VM Network
            type: static
            ip: 192.168.10.14
            netmask: 255.255.255.0
            gateway: 192.168.10.1
            typev6: static
            ipv6: "2201:430:28f:2032::100"
            netmaskv6: 32
            gatewayv6: "2201:430:28f:2032::1"
```

note that for VMware API, ip is required option for setting ipv6 parameter.

needs_info
