### ISSUE TITLE
IPAClient module_utils cannot perform an empty argument on a _post_json() call

### ISSUE THREAD

**Issue by jparrill** [ansible/ansible#42616]
##### SUMMARY
There is no way to use vaultconfig_show() API because the method **_post_json()** from [module utils](https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/ipa.py)always will use a **name** and an **item**, the problem is that this API doesn't need any argument, then the API answer this:

```
"msg": "response vaultconfig_show: command 'vaultconfig_show' takes no arguments"
```

but when I skip all arguments (except login ones) I get this:

```
"msg": "_post_json() takes at least 3 arguments (3 given)"
```

Then, there is an issue in the module_utils that cannot allow to call API's without arguments.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
IPA Module Utils

##### ANSIBLE VERSION
```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/jparrill/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION
Not any special config

##### OS / ENVIRONMENT
Linux

##### STEPS TO REPRODUCE
I'm creating a new module to add new secrets inside of a KRA vault but I cannot get the transport cert and nonce without get the related API

[Here the code](https://github.com/jparrill/ansible/blob/feature/module_ipa_vault_archive/lib/ansible/modules/identity/ipa/ipa_vault_archive.py)

And here the playbook:

```yaml
- name: '[Test IDM Vault archive/retrieve]'
  hosts: localhost
  connection: local
  become: false
  tasks:
    - name: '[IDM] Test IDM vault archive'
      ipa_vault_archive:
          state: present
          name: 'vault_ansible_021'
          vault_session_key: 'asdasoidjasoidj'
          vault_data: 'TEST01asodijaosdi'
          user: 'client01'
          ipa_host: 'ipa-server.example.com'
          ipa_user: 'admin'
          ipa_pass: 'xxxxxx'
          validate_certs: False
      register: vault

    - name: '[DEBUG] Print IDM Vault'
      debug:
          var: vault
          verbosity: 1
```

##### EXPECTED RESULTS
Receive the transport_cert or nonce to be printed and continue the module development.

##### ACTUAL RESULTS
```
"msg": "response vaultconfig_show: command 'vaultconfig_show' takes no arguments"
```

but when I skip all arguments (except login ones) I get this:

```
"msg": "_post_json() takes at least 3 arguments (3 given)"
```
