### ISSUE TITLE
vcenter_folder creates subfolder in wrong datacenter when multiple datacenters have parent folder

### ISSUE THREAD

**Issue by sonclay** [ansible/ansible#42638]
##### SUMMARY

vcenter_folder creates subfolder in wrong datacenter when multiple datacenters have parent folder
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

vcenter_folder
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansiblectl/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

ANSIBLE_SSH_RETRIES(/etc/ansible/ansible.cfg) = 2
DEFAULT_CALLBACK_WHITELIST(/etc/ansible/ansible.cfg) = ['profile_tasks']
DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/mnt/jenkins/ansible_roles']
##### OS / ENVIRONMENT

RHEL7.4
##### STEPS TO REPRODUCE

use vcenter_folder to create a subfolder named testfolder in parent folder testparent in datacenter2 when testparent exists in both datacenter2 and datacenter1. Subfolder is created in datacenter1 instead of datacenter2 as requested.

```yaml
  vcenter_folder:
    validate_certs: false
    hostname: vcenter
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    datacenter: dc2
    folder_name: testfolder
    folder_type: vm
    parent_folder: testparent
    state: present
  delegate_to: localhost
```

##### EXPECTED RESULTS

testparent/testfolder to be created in dc2
##### ACTUAL RESULTS

testparent/testfolder is created in dc1

```
changed: [testhost -> localhost] => {
    "changed": true, 
    "invocation": {
        "module_args": {
            "datacenter": "dc2", 
            "folder_name": "testfolder", 
            "folder_type": "vm", 
            "hostname": "vcenter", 
            "parent_folder": "testparent", 
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "port": 443, 
            "state": "present", 
            "username": "myuser", 
            "validate_certs": false
        }
    }, 
    "result": "Folder 'testfolder' of type 'vm' created under testparent successfully."
}
```
