### ISSUE TITLE
Restarting EC2 instance causes modification of termination protection and the source_dest check

### ISSUE THREAD

**Issue by mostfunkyduck** [ansible/ansible#42646]
##### SUMMARY
When trying to restart an instance using the ec2 module, I noticed that the source/dest check was getting reset to 'true'.  This is what I was running: 
```    
     - name: restart instance
      local_action:
          module: ec2 
          region: "{{ ansible_ec2_placement_region }}"
          instance_ids: "{{ansible_ec2_instance_id}}"
          state: restarted
```

Looking at the code, I see that at least for the stopstart and restart processes, the code will modify both the source/dest check and termination protection.  This seems like a bug to me - just because I want to restart an instance doesn't mean I want to change its attributes.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2
##### ANSIBLE VERSION

```
ansible 2.5.3
  config file = None
  configured module search path = ['/Users/ykuperman/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/ykuperman/venvs/ansible2/lib/python3.6/site-packages/ansible
  executable location = /Users/ykuperman/venvs/ansible2/bin/ansible
  python version = 3.6.3 (default, Nov 16 2017, 10:24:04) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

##### CONFIGURATION
Nothing changed

##### OS / ENVIRONMENT
Running on MacOS, managing AWS Linux 2

##### STEPS TO REPRODUCE
1. set up an ec2 instance with source/dest check set to false
1. run a minimal restart using the example below

```
     - name: restart instance
      local_action:
          module: ec2 
          region: "{{ ansible_ec2_placement_region }}"
          instance_ids: "{{ansible_ec2_instance_id}}"
          state: restarted
```

##### EXPECTED RESULTS
Instance restarts with no modifications to the attributes

##### ACTUAL RESULTS
Instance restarts, but the source/dest check has changed
