### ISSUE TITLE
vmware_deploy_ovf module - add option for cluster

### ISSUE THREAD

**Issue by robertlupinek** [ansible/ansible#42644]
##### SUMMARY

It would be a huge benefit to have the ability to select a cluster to deploy to when deploying to vCenter.  Many VMware environments have multiple clusters that need to be specifically targeted for deployment.

Also you rule for creating this module!  THANKS!

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

vmware_deploy_ovf module

##### ANSIBLE VERSION

```
ansible 2.7.0.dev0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rlupinek/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### STEPS TO REPRODUCE

```
---
  - hosts: localhost
    tasks:
    - vmware_deploy_ovf:
        hostname: vcenter-hostname.domain.local
        username: user
        password: password
        ovf: /tmp/my.ova
        wait_for_ip_address: false
        datastore: mydatastore
        datacenter: My-DC
        cluster: Cluster-1
        networks: {'Old-Network': 'New-Network'}
        name: my-vm.domain.local
```

##### EXPECTED RESULTS

The expected result of specifying a cluster would be to have the OVA or OVF deployed to that cluster.

##### ACTUAL RESULTS

```
PLAY [localhost] ********************************************************************************************************************************************

TASK [Gathering Facts] **************************************************************************************************************************************
ok: [localhost]

TASK [vmware_deploy_ovf] ************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (vmware_deploy_ovf) module: cluster Supported parameters include: allow_duplicates, datacenter, datastore, deployment_option, disk_provisioning, fail_on_spec_warnings, folder, hostname, name, networks, ovf, password, port, power_on, properties, resource_pool, username, validate_certs, wait, wait_for_ip_address"}
        to retry, use: --limit @/home/rlupinek/v15trunk-test01/ansible/playbooks/ova_deploy/ova_deploy.retry

PLAY RECAP **************************************************************************************************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1

```
