### ISSUE TITLE
azure_rm_storage_account fails on Azure Stack

### ISSUE THREAD

**Issue by caohai** [ansible/ansible#42652]
##### SUMMARY

azure_rm_storage_account fails when I use Ansible to create a storage account in Azure Stack. This error comes from Ansible using api_versions of Azure Python SDK that are not supported by Azure Stack
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_storage_account
azure_rm_common
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/azureuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

1. I'm using Azure Stack Development Kit(1.1805.1.47)
2. I'm running Ansible  on a Ubuntu Server 16.04 LTS Virtual Machine
##### STEPS TO REPRODUCE

1. Log in a Ubuntu server on Azure Stack. (ASDK in this case)
2. Run the playbook below

```yaml
---
- hosts: localhost
  vars:
    location: local
    resource_group: testGroup
    storage_account: tesetsa002
  tasks:
  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storage_account }}"
      account_type: Standard_LRS
      location: "{{ location }}"
```

##### EXPECTED RESULTS

Successfully create a storage account in my resource group.
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Create storage account] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error checking name availability: Azure Error: InvalidResourceType\nMessage: The resource type 'checkNameAvailability' could not be found in the namespace 'Microsoft.Storage' for api version '2017-10-01'. The supported api-versions are '2016-01-01,2015-06-15,2015-05-01-preview'."}
        to retry, use: --limit @/home/azureuser/testPb/storageTest.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```

I noticed that the api versions are hard-coded in azure_rm_common.py and Ansible is using the latest api-versions of Azure Python SDK, some of which are not supported by Azure Stack yet.

I tried to manually change the api version for storage management to '2016-01-01' ([Link](https://github.com/ansible/ansible/blob/a5fc9a17f05066dfbe3b499c6fc3202cc6126e8e/lib/ansible/module_utils/azure_rm_common.py#L981-L993)). Then the playbook above works.
