### ISSUE TITLE
azure_rm_virtualnetwork fails on Azure Stack

### ISSUE THREAD

**Issue by caohai** [ansible/ansible#42658]
##### SUMMARY

azure_rm_virtualnetwork fails when I use Ansible to create a virtual network in Azure Stack. This error comes from Ansible using newer version of Azure Network Management Api that is not supported by Azure Stack.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_virtualnetwork
azure_rm_common
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/azureuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

1. I'm using Azure Stack Development Kit(1.1805.1.47)
2. I'm running Ansible on a Ubuntu Server 16.04 LTS Virtual Machine
##### STEPS TO REPRODUCE

1. Log in a Ubuntu server on Azure Stack. (ASDK in this case)
2. Run the playbook below

```yaml
---
- hosts: localhost
  vars:
    location: local
    resource_group: testGroup
    virtual_network: testvn002
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtual_network }}"
      address_prefixes: "10.10.0.0/16"
```

##### EXPECTED RESULTS

Successfully create a virtual network in my resource group.
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Create virtual network] **************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error creating or updating virtual network testvn002 - Azure Error: NoRegisteredProviderFound\nMessage: No registered resource provider found for location 'local' and API version '2017-11-01' for type 'virtualNetworks'. The supported api-versions are '2015-05-01-preview, 2015-06-15'. The supported locations are 'local'."}
        to retry, use: --limit @/home/azureuser/testPb/vnetTest.retry

PLAY RECAP *********************************************************************
localhost                  : ok=1    changed=0    unreachable=0    failed=1
```
FYI:
1. This error comes from the hard-coded Network Management apiversion [here](https://github.com/ansible/ansible/blob/a5fc9a17f05066dfbe3b499c6fc3202cc6126e8e/lib/ansible/module_utils/azure_rm_common.py#L996-L1007). I manually change the api version to '2015-06-15'. Then the playbook above works.
2. This api version also affects:
   - azure_rm_subnet, 
   - azure_rm_publicipaddress, 
   - azure_rm_securitygroup,
   - azure_rm_networkinterface
(Bascially every module that uses Network Management SDK will fail due to this api version issue.)
3. Manually changing the api version is necessary but not a guarantee to make modules mentioned in 2 work properly.
