### ISSUE TITLE
ec2_group "Ran out of time waiting for sg-xxx IpPermissions" if protocol set to numeric value

### ISSUE THREAD

**Issue by dseeley-sky** [ansible/ansible#42661]
##### SUMMARY
ec2_group takes a long time to complete, and emits warning "Ran out of time waiting for sg-xxx IpPermissions" if the 'protocol' field is set to numeric value.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_group module

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /home/dse09/src/vtp-devops-ansible-template/ansible.cfg
  configured module search path = [u'/home/dse09/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### OS / ENVIRONMENT
CentOS 7

##### STEPS TO REPRODUCE

```yaml
    - name: Create AWS security group
      ec2_group:
        name: "test-sg"
        region: "{{region}}"
        vpc_id: "{{vpc_id}}"
        tags:
          Name: "test-sg"
        rules:
          - proto: 112
            from_port: 0 # this value is needed by the module, but ignored
            to_port: 0   # this value is needed by the module, but ignored
            cidr_ip: 10.0.0.0/8
            rule_desc: "VRRP inbound for VRRP peers"
```

##### EXPECTED RESULTS
security group is created quickly and successfully without warnings.

##### ACTUAL RESULTS
security group is created very slowly (presumably due to timeout), and warning below is emitted (unsure how serious it is):

```
TASK [Create AWS security group] *******************************************************************************************************************************************************************************************************************************************
 [WARNING]: Ran out of time waiting for sg-85539af9 IpPermissions. Current: set([Rule(port_range=(None, None), protocol='112', target='10.0.0.0/8', target_type='ipv4', description='VRRP inbound for VRRP peers')]), Desired: [Rule(port_range=(0, 0), protocol=112,
target='10.0.0.0/8', target_type='ipv4', description='VRRP inbound for VRRP peers')]
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/cloud/amazon/ec2_group.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/cloud/amazon/ec2_group.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @adq
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by harsha-y** [comment]
##### SUMMARY
Bug exists in Ansible 2.6.2 even _without_ any numeric values for `proto`

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible 2.6.2
  config file = /Users/user/git/ansible-aws-manage/ansible.cfg
  configured module search path = [u'/Users/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

**Comment by harsha-y** [comment]
@s-hertel / @ryansb  Its entirely possible we are missing something here, but I don't think #42765 resolves this issue. This is reproducible still in `ansible 2.7.0`

**Comment by ryansb** [comment]
I'm not able to reproduce this on 2.7, here is the playbook that I'm using to try to repro:

```
---
- hosts: localhost
  connection: local
  gather_facts: no
  module_defaults:
    group/aws:
      region: us-east-2
  tasks:
    - name: create vpc
      ec2_vpc_net:
        name: "sg-numeric-test-vpc"
        cidr_block: 30.30.30.0/24
      register: vpc

    - name: Create AWS security group
      ec2_group:
        name: "test-sg"
        description: fooooo
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: 112
            from_port: 0 # this value is needed by the module, but ignored
            to_port: 0   # this value is needed by the module, but ignored
            cidr_ip: 10.0.0.0/8
            rule_desc: "VRRP inbound for VRRP peers"

    - name: Create AWS security group (this will not show `changed=True`)
      ec2_group:
        name: "test-sg"
        description: fooooo
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: 112
            from_port: 0 # this value is needed by the module, but ignored
            to_port: 0   # this value is needed by the module, but ignored
            cidr_ip: 10.0.0.0/8
            rule_desc: "VRRP inbound for VRRP peers"

    - name: Choose continue to tear down test resources
      pause: minutes=5
    - name: Create AWS security group
      ec2_group:
        name: "test-sg"
        state: absent
        description: fooooo
        vpc_id: "{{ vpc.vpc.id }}"
        rules:
          - proto: 112
            from_port: 0 # this value is needed by the module, but ignored
            to_port: 0   # this value is needed by the module, but ignored
            cidr_ip: 10.0.0.0/8
            rule_desc: "VRRP inbound for VRRP peers"
    - name: create vpc
      ec2_vpc_net:
        state: absent
        name: "sg-numeric-test-vpc"
        cidr_block: 30.30.30.0/24
```

And the output:
```
TASK [create vpc] ***************************************************************************************
task path: /home/ryansb/code/ansible-test-plays/2018-10-group-numeric-idempotence.yml:10                
changed: [localhost] => {"changed": true, "vpc": {"cidr_block": "30.30.30.0/24", "cidr_block_association_set": [{"association_id": "vpc-cidr-assoc-025b1210761a16dfb", "cidr_block": "30.30.30.0/24", "cidr_block_state": {"state": "associated"}}], "classic_link_enabled": false, "dhcp_options_id": "dopt-40e50e29", "id": "vpc-0f27895210643e66c", "instance_tenancy": "default", "is_default": false, "state": "available", "tags": {"Name": "sg-numeric-test-vpc"}}}

TASK [Create AWS security group] ************************************************************************
task path: /home/ryansb/code/ansible-test-plays/2018-10-group-numeric-idempotence.yml:16                
changed: [localhost] => {"changed": true, "description": "fooooo", "group_id": "sg-00fa297d4676386cd", "group_name": "test-sg", "ip_permissions": [{"ip_protocol": "112", "ip_ranges": [{"cidr_ip": "10.0.0.0/8", "description": "VRRP inbound for VRRP peers"}], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": []}], "ip_permissions_egress": [{"ip_protocol": "-1", "ip_ranges": [{"cidr_ip": "0.0.0.0/0"}], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": []}], "owner_id": "509803855674", "tags": {}, "vpc_id": "vpc-0f27895210643e66c"}

TASK [Create AWS security group (this will not show `changed=True`)] ************************************
task path: /home/ryansb/code/ansible-test-plays/2018-10-group-numeric-idempotence.yml:28                
ok: [localhost] => {"changed": false, "description": "fooooo", "group_id": "sg-00fa297d4676386cd", "group_name": "test-sg", "ip_permissions": [{"ip_protocol": "112", "ip_ranges": [{"cidr_ip": "10.0.0.0/8", "description": "VRRP inbound for VRRP peers"}], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": []}], "ip_permissions_egress": [{"ip_protocol": "-1", "ip_ranges": [{"cidr_ip": "0.0.0.0/0"}], "ipv6_ranges": [], "prefix_list_ids": [], "user_id_group_pairs": []}], "owner_id": "509803855674", "tags": {}, "vpc_id": "vpc-0f27895210643e66c"}
```
