### ISSUE TITLE
Variable expansion does not work in the consul_kv lookup plugin/set_fact module, but it does for "item"

### ISSUE THREAD

**Issue by walterdolce** [ansible/ansible#42674]
##### SUMMARY
As per title, the following task makes Ansible unhappy and doesn't work:
```
# defaults/main.yml
---
consul_host: "example.com"
consul_port: "80"

# tasks/main.yml
---
- name: "Fetch feature lists from Consul ({{ consul_host }}:{{ consul_port }})"
  set_fact:
    tmp_feature_names_list: "{{ lookup('consul_kv', '{{ item }}', host='{{ consul_host }}', port='{{ consul_port }}') }}"
  loop:
    - foo
    - bar
```
Resulting in the following:
```
fatal: [127.0.0.1]: FAILED! => {"msg": "An unhandled exception occurred while running the lookup plugin 'consul_kv'. Error was a <class 'ansible.errors.AnsibleError'>, original message: Error locating 'foo' in kv store. Error was HTTPConnectionPool(host='%7b%7b%20consul_host%20%7d%7d', port=%7b%7b%20consul_port%20%7d%7d): Max retries exceeded with url: /v1/kv/foo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10ce0b990>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',))"}
```

While the same task passing the host and port directly in the plugin works just fine.

Why is `{{ item }}` being evaluated but `{{ consul_host }}` and `{{ consul_port }}` not?

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
consul_kv

##### ANSIBLE VERSION
```
ansible 2.6.1
  config file = /path/to/ansible.cfg
  configured module search path = [u'/usr/local/ansible/modules/core', u'/usr/local/ansible/modules/extra', u'/usr/share/ansible', u'/path/to/library']
  ansible python module location = /usr/local/Cellar/ansible/2.6.1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION
N/A

##### OS / ENVIRONMENT
N/A

##### STEPS TO REPRODUCE
Use the task above.

##### EXPECTED RESULTS
I expected the task to run as normal, Ansible to expand the injected variables in the same way as it's expanding the `{{ item }}` one coming from the `loop` construct.

##### ACTUAL RESULTS
Ansible did not what I expected. Please see the error reported above.
