### ISSUE TITLE
maven_artifact spinning with 100% CPU on checking md5 with python3

### ISSUE THREAD

**Issue by MichaelSteffens** [ansible/ansible#42677]
##### SUMMARY

When using `ansible_python_interpreter: /usr/bin/python3` maven_artifact hangs on checking the MD5 checksum.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

maven_artifact

##### ANSIBLE VERSION
```
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/michael/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```
Also affected: 2.5.2

##### CONFIGURATION

ANSIBLE_HOST_KEY_CHECKING=False

##### OS / ENVIRONMENT

OS running Ansible from: Ubuntu Server 16.04
Target OS: Ubuntu Server 18.04

##### STEPS TO REPRODUCE

Using variables for `artifactory_base_url`, `artifactory_user`, `artifactory_password`, and `ansible_python_interpreter: /usr/bin/python3`:

```yaml
- name: Download myservlet.war
  maven_artifact: group_id=com.sample artifact_id=myservlet extension=war dest=/var/tmp/myservlet.war repository_url={{ artifactory_base_url }}/maven username={{ artifactory_user }} password={{ artifactory_password }}
  register: downloaded_myservlet
```

##### EXPECTED RESULTS

Module execution completes.

##### ACTUAL RESULTS

Module execution hangs after download, if MD5 checksum is checked, i.e. if file already existed (2.5.2) or if it did not yet exist (2.6). With 2.6 the problem disappears when using `verify_checksum=never`.

```
# ps -fp24825
UID        PID  PPID  C STIME TTY          TIME CMD
root     24825 24824 99 10:14 pts/1    00:01:57 /usr/bin/python3 /tmp/ansible_iet610ng/ansible_module_maven_artifact.py
# strace -p24825 2>&1 | head -20
strace: Process 24825 attached
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
read(8, "", 8192)                       = 0
# lsof -p24825 | grep 8r
python3 24825 root    8r   REG              252,1   151883  783477 /var/tmp/myservlet.war
```
