### ISSUE TITLE
uri status_code still failing task even if status code matches

### ISSUE THREAD

**Issue by RogierSchuring** [ansible/ansible#42671]
##### SUMMARY
uri status_code still failing task even if status code matches

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

uri module

##### ANSIBLE VERSION

```
ansible 2.5.1
  config file = /home/vz98nv/ansible-flame/ansible.cfg
  configured module search path = [u'/home/vz98nv/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

```
DEFAULT_FORKS(/ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/ansible/ansible.cfg) = [u'/ansible/inventory']
DEFAULT_LOG_PATH(/ansible/ansible.cfg) = /var/log/ansible.log
DEFAULT_MANAGED_STR(/ansible/ansible.cfg) = This file is managed by Ansible
DEFAULT_REMOTE_USER(/ansible/ansible.cfg) = root
HOST_KEY_CHECKING(/ansible/ansible.cfg) = False
```
##### OS / ENVIRONMENT

```
Red Hat Enterprise Linux Server release 7.5 (Maipo)
```
##### STEPS TO REPRODUCE

Run below playbook. use as inventory a server with https and auth enabled (force 401 return when no basic auth is provided by uri)

```yaml
- name: Test uri module
  hosts: localhost
  tasks:
  - name: Test uri module.
    uri:
      url: "https://localhost:443/"
      return_content: yes
      status_code: 401
      validate_certs: no
    register: result
    run_once: true
    until: result.failed is undefined
    retries: 100
    delay: 3
```

##### EXPECTED RESULTS

Expected result (ansible 2.4.x and below)
```
ok: [localhost] => {
    "attempts": 1,
    "changed": false,
    "content": "{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}",
    "content_length": "369",
    "content_type": "application/json; charset=UTF-8",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {},
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "401"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "https://localhost:443/",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": false
        }
    },
    "json": {
        "error": {
            "header": {
                "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
            },
            "reason": "missing authentication token for REST request [/]",
            "root_cause": [
                {
                    "header": {
                        "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
                    },
                    "reason": "missing authentication token for REST request [/]",
                    "type": "security_exception"
                }
            ],
            "type": "security_exception"
        },
        "status": 401
    },
    "msg": "HTTP Error 401: Unauthorized",
    "redirected": false,
    "status": 401,
    "url": "https://localhost:443/",
    "www_authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
}
```
##### ACTUAL RESULTS

```
FAILED - RETRYING: Test uri module. (100 retries left).Result was: {
    "attempts": 1,
    "changed": false,
    "content": "{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}}],\"type\":\"security_exception\",\"reason\":\"missing authentication token for REST request [/]\",\"header\":{\"WWW-Authenticate\":\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\"}},\"status\":401}",
    "content_length": "369",
    "content_type": "application/json; charset=UTF-8",
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": null,
            "body": null,
            "body_format": "raw",
            "client_cert": null,
            "client_key": null,
            "content": null,
            "creates": null,
            "delimiter": null,
            "dest": null,
            "directory_mode": null,
            "follow": false,
            "follow_redirects": "safe",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": {},
            "http_agent": "ansible-httpget",
            "method": "GET",
            "mode": null,
            "owner": null,
            "regexp": null,
            "remote_src": null,
            "removes": null,
            "return_content": true,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "src": null,
            "status_code": [
                "401"
            ],
            "timeout": 30,
            "unsafe_writes": null,
            "url": "https://localhost:443/",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": false
        }
    },
    "json": {
        "error": {
            "header": {
                "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
            },
            "reason": "missing authentication token for REST request [/]",
            "root_cause": [
                {
                    "header": {
                        "WWW-Authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
                    },
                    "reason": "missing authentication token for REST request [/]",
                    "type": "security_exception"
                }
            ],
            "type": "security_exception"
        },
        "status": 401
    },
    "msg": "HTTP Error 401: Unauthorized",
    "redirected": false,
    "retries": 101,
    "status": 401,
    "url": "https://localhost:443/",
    "www_authenticate": "Basic realm=\"security\" charset=\"UTF-8\""
}
```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/net_tools/basics/uri.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/net_tools/basics/uri.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @romeotheriault
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by samdoran** [comment]
I do not believe this is a bug in the `uri` module. If I run a single task without `until`, it does not report failure:

```yaml
- name: Test uri module
  hosts: localhost
  connection: local
  become: no

  tasks:
    - block:
        - name: Test uri module.
          uri:
            url: "http://localhost:80/"
            return_content: yes
            status_code: 401
            validate_certs: no
          register: result
      always:
        - debug:
            var: result
```
```
> ansible-playbook testlocal.yml

PLAY [Test uri module] *********************************************************

TASK [Test uri module.] ********************************************************
ok: [localhost]

TASK [debug] *******************************************************************
ok: [localhost] => {
    "result": {
        "attempts": 1,
        "changed": false,
        "connection": "close",
        "content": "<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.15.1</center>\r\n</body>\r\n</html>\r\n",
        "content_length": "195",
        "content_type": "text/html",
        "date": "Thu, 12 Jul 2018 18:06:12 GMT",
        "failed": false,
        "msg": "HTTP Error 401: Unauthorized",
        "redirected": false,
        "server": "nginx/1.15.1",
        "status": 401,
        "url": "http://localhost:80/",
        "www_authenticate": "Basic realm=\"closed site\""
    }
}

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```

I believe the issue is `until: result.failed is undefined`. This never matches since `result.failed` is always defined and is either `true` or `false`.

I am able to get it to work properly by changing the `until` test:

```yaml
- name: Test uri module
  hosts: localhost
  connection: local
  become: no

  tasks:
    - block:
        - name: Test uri module.
          uri:
            url: "http://localhost:80/"
            return_content: yes
            status_code: 401
            validate_certs: no
          register: result
          run_once: true
          until: not result.failed
          retries: 100
          delay: 3
      always:
        - debug:
            var: result
```

```
> ansible-playbook testlocal.yml

PLAY [Test uri module] **************************************************************

TASK [Test uri module.] *************************************************************
ok: [localhost]

TASK [debug] ************************************************************************
ok: [localhost] => {
    "result": {
        "attempts": 1,
        "changed": false,
        "connection": "close",
        "content": "<html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.15.1</center>\r\n</body>\r\n</html>\r\n",
        "content_length": "195",
        "content_type": "text/html",
        "date": "Thu, 12 Jul 2018 18:09:43 GMT",
        "failed": false,
        "msg": "HTTP Error 401: Unauthorized",
        "redirected": false,
        "server": "nginx/1.15.1",
        "status": 401,
        "url": "http://localhost:80/",
        "www_authenticate": "Basic realm=\"closed site\""
    }
}

PLAY RECAP **************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0
```
