### ISSUE TITLE
meraki_admin - Change parameters to accept nested parameters

### ISSUE THREAD

**Issue by kbreit** [ansible/ansible#42687]
##### SUMMARY
`tags` and `networks` parameters are currently setup as a list of dictionaries. This isn't very Ansible-like and should instead use nested parameters. I suggest this.

```
tags:
  - tag: something
    access: read-only
  - tag: somethingelse
    access: full
```

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
meraki_admin

##### ANSIBLE VERSION
```
2.7
```
