### ISSUE TITLE
mysql_db module fails and asks for cnf file

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#42691]
##### SUMMARY
`mysql_db` module keeps seeking for `.cnf` file, although `login_user` and `login_password` are supplied in task

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
msyql_db

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pkara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

No config changes

##### OS / ENVIRONMENT

Ubuntu 16.04.04

##### STEPS TO REPRODUCE

```yaml
- name: Conditionally export mydb
  mysql_db:
    login_user: "someusername"
    login_password: "somepass"
    state: dump
    name: mydb
    login_host: "{{ somehost }}"
    login_port: "{{ someport }}"
    target: "{{ temp_deploy_directory }}/{{ dump_file_name }}"
  when: someconditions
```

##### EXPECTED RESULTS
Produce a dump of the file

##### ACTUAL RESULTS

Ansible fails with

> "msg": "unable to find /home/ansible/.my.cnf. Exception message: (2003, \"Can't connect to MySQL server on...

```

```
