### ISSUE TITLE
dynamic variable in with_items issue

### ISSUE THREAD

**Issue by balpoint** [ansible/ansible#42699]
##### SUMMARY

Trying to pass a variable in the with_items statement to make the administration of the configuration a lot easier.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME
 with_items

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ddenouden/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]
```

##### CONFIGURATION

DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']

##### OS / ENVIRONMENT

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

##### STEPS TO REPRODUCE

playbook:
```yaml
---

- name: Create VIP, pool, pool members and nodes
  hosts: f5-test
  connection: local
  any_errors_fatal: true
  
  vars_files:
    - ./group_vars/f5-test.yaml
    
  tasks:
    - name: Create a pool
      bigip_pool:
        provider: "{{ provider }}"
        lb_method: "{{ item.pool_lb_method }}"
        name: "{{ item.pool_name }}"
        slow_ramp_time: "{{ item.pool_slow_ramp_time }}"
        state: "{{ item.pool_state }}"
      with_items:
        - "{{customername[app_env][app_name]['pool']}}"
        
    - name: Add members to pool
      bigip_pool_member:
        provider: "{{ provider }}"
        description: "webserver {{ item.node_name }}"
        host: "{{ item.node_host }}"
        name: "{{ item.node_name }}"
        pool: "{{ item.node_pool }}"
        port: "{{ item.node_port }}"
        state: "{{ item.node_state }}"
      with_items:
        - "{{customername[app_env][app_name]['node']}}"

    - name: Create a VIP
      bigip_virtual_server:
        provider: "{{ provider }}"
        description: "{{ item.vip_description }}"
        destination: "{{ item.vip_destination }}"
        name: "{{ item.vip_name }}"
        pool: "{{ item.vip_pool }}"
        port: "{{ item.vip_port }}"
        snat: "{{ item.vip_snat }}"
        irules: "{{ item.vip_irules }}" 
        profiles: "{{ item.vip_profiles }}"
        state: "{{ item.vip_state }}"
      with_items:
        - "{{customername[app_env][app_name]['vip']}}"
```
var file:
```yaml
---
provider:
  server: x.xyz.com
  user: admin
  password: <redacted>
  server_port: 443
  validate_certs: no

app_env: prod
app_name:
  - jira
  - cms
customername:
  prod:
    jira:
      pool:
        - pool_name: "pool-1"
          pool_lb_method: "ratio-member"
          pool_slow_ramp_time: "120"
          pool_state: "present"
      node:
        - node_name: node-1
          node_host: 10.10.10.15
          node_pool: pool-1
          node_port: 80
          node_state: present
        - node_name: node-2
          node_host: 10.10.10.25
          node_pool: pool-1
          node_port: 80
          node_state: present
      vip:
        vip_name: vip-1
        vip_description: jira.customername.com
        vip_destination: 172.16.10.109
        vip_pool: pool-1
        vip_port: 80
        vip_snat: Automap
        vip_irules: testHostHeader
        vip_profiles: [ "http", "clientssl", "web20", "web20connection" ]
        vip_state: present
    cms:
      pool:
        - pool_name: "pool-2"
          pool_lb_method: "ratio-member"
          pool_slow_ramp_time: "120"
          pool_state: "present"
      node:
        - node_name: node-1
          node_host: 10.10.10.15
          node_pool: pool-2
          node_port: 443
          node_state: present
        - node_name: node-2
          node_host: 10.10.10.25
          node_pool: pool-2
          node_port: 443
          node_state: present
      vip:
        vip_name: vip-2
        vip_description: cms.customername.com
        vip_destination: 172.16.10.109
        vip_pool: pool-2
        vip_port: 443
        vip_snat: Automap
        vip_irules: testHostHeader
        vip_profiles: [ "http", "clientssl", "web20", "web20connection" ]
        vip_state: present
```

##### EXPECTED RESULTS

That the variable [app_name] would give both application names separatly so the loop would create to F5 vip/pool/node objects

##### ACTUAL RESULTS

```
TASK [Create a pool] ************************************************************************************************
task path: /home/ddenouden/git/f5-networks/f5-ansible/examples/0000-getting-started/playbook.yaml:12
fatal: [x.xyz.com]: FAILED! => {
    "msg": "dict object has no element [u'jira', u'cms']"
}

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/playbook/loop_control.py](https://github.com/ansible/ansible/blob/devel/lib/ansible/playbook/loop_control.py)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by balpoint** [comment]
When making defining the variable app_name  as following

app_name: jira

It works, but then only 1 VIP/Pool/Node object is being created and i don't want to do this manually for each application that needs a load balancing config.

**Comment by samdoran** [comment]
This is best handled using `include_tasks` and a loop.

```yaml
- include_tasks: f5_config.yml
  loop: "{{ app_name }}"
  loop_control:
    loop_var: outer_item
```

```yaml
# f5_config.yml
- name: Create a pool
  debug:
    msg: "{{ item.pool_lb_method }}"
  loop: "{{ customername[app_env][outer_item]['pool'] }}"

- name: Add members to pool
  debug:
    msg: "{{ item.node_name }}"
  loop: "{{ customername[app_env][outer_item]['node'] }}"

- name: Create a VIP
  debug:
    msg: "{{ customername[app_env][outer_item].vip.vip_description }}"

```

For further help with the issue, please reach out on IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net   
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
