### ISSUE TITLE
docker_container module always falsely report 'changed' when 'kernel_memory' attribute is set to "0" or 0

### ISSUE THREAD

**Issue by jainishan** [ansible/ansible#42692]
##### SUMMARY
when using docker_container module, if we specify 'kernel_memory' attribute and try to set it to the default value of 0, Ansible will report the container as changed in all subsequent runs while nothing is actually changed for the container.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
docker_container

##### ANSIBLE VERSION
```
ansible 2.4.3.0
  config file = 
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION
Default ansible.cfg

##### OS / ENVIRONMENT
Red Hat 4.8.5-14

##### STEPS TO REPRODUCE
```yaml
      - name: Start container
        docker_container:
          name: "{{cname}}"
          image: "{{ image }}"
          state: started
          memory:             "{{ mem }}"
          memory_reservation: "{{ memr }}"
          memory_swap:        "{{ mems }}"
          kernel_memory:      0

 OR

      - name: Start container
        docker_container:
          name: "{{cname}}"
          image: "{{ image }}"
          state: started
          memory:             "{{ mem }}"
          memory_reservation: "{{ memr }}"
          memory_swap:        "{{ mems }}"
          kernel_memory:      "0"
```

##### EXPECTED RESULTS
In case when you run the playbook several times without changing anything, everything should be 'OK' in the end. In case you do not specify kernel_memory or give it emptry value (''), everything should be reported as 'OK'.

##### ACTUAL RESULTS
In case when you run the playbook several times without changing anything, Ansible reports 'Changed' every time. In case you do not specify kernel_memory or give it emptry value (''), everything is reported as 'OK'.
