### ISSUE TITLE
mysql_db module fails when selecting "all" as db name to dump

### ISSUE THREAD

**Issue by pkaramol** [ansible/ansible#42693]
##### SUMMARY
when trying to export all databases using `mysql_db` module it fails;

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
`msyql_db.py`

##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/pkara/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```

##### CONFIGURATION

No config changes

##### OS / ENVIRONMENT

Ubuntu 16.04.04

##### STEPS TO REPRODUCE

```yaml
- name: Conditionally export mydb
  mysql_db:
    login_user: "someusername"
    login_password: "somepass"
    state: dump
    name: all
    login_host: "{{ somehost }}"
    login_port: "{{ someport }}"
    target: "{{ temp_deploy_directory }}/{{ dump_file_name }}"
  when: someconditions
```

##### EXPECTED RESULTS
Produce a dump that includes all databases in remote host;

##### ACTUAL RESULTS

Ansible fails with

> fatal: [jenkins]: FAILED! => {"changed": false, "msg": "Cannot dump database mysql - not found"}
