### ISSUE TITLE
Ansible module mount cannot remove specific swap devices/files from /etc/fstab

### ISSUE THREAD

**Issue by stephan2012** [ansible/ansible#42706]
##### SUMMARY

Ansible module `mount` cannot remove specific swap devices from `/etc/fstab`.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

mount

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Nov 24 2017, 17:33:09) [GCC 6.3.0 20170516]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

CentOS 7.5

##### STEPS TO REPRODUCE

The following task removes _all_ swap devices because it just matches `path` (should be `none` for swap devices according to fstab(5))

```yaml
- name: "Remove swap device(s) from /etc/fstab"
  mount:
    src: '{{ item }}'
    path: none
    fstype: swap
    backup: yes
    state: absent
  with_items: '{{ swapdevs.stdout_lines }}'
  when: 'swapdevs.stdout_lines |length > 0'
```

##### EXPECTED RESULTS

Remove specified device only. To achieve that, the `src` device path should be matched instead of `path`.

##### ACTUAL RESULTS

`mount` removes all swap device lines in `/etc/fstab`.

```
changed: [n0107] => {
    "changed": true, 
    "dump": "0", 
    "fstab": "/etc/fstab", 
    "fstype": "swap", 
    "invocation": {
        "module_args": {
            "backup": true, 
            "boot": true, 
            "dump": null, 
            "fstab": null, 
            "fstype": "swap", 
            "opts": null, 
            "passno": null, 
            "path": "none", 
            "src": null, 
            "state": "absent"
        }
    }, 
    "name": "none", 
    "opts": "defaults", 
    "passno": "0"
}
```
