### ISSUE TITLE
elasticache_parameter_group doesn't support group_family redis4.0

### ISSUE THREAD

**Issue by orderedchaosdev** [ansible/ansible#42717]
##### SUMMARY

elasticache_parameter_group doesn't support the group_family redis4.0
I'm not actually sure why the group_family field is restricted at all since as far as I can tell other than passing it as the group_family it isn't used in the module.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

elasticache_parameter_group
##### ANSIBLE VERSION

```
ansible 2.4.4.0
  python version = 2.7.14 (default, Mar 21 2018, 16:45:24) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

##### OS / ENVIRONMENT

N/A
##### STEPS TO REPRODUCE

```yaml
- name: Create Elasticache Parameter Group
  elasticache_parameter_group:
    state: present
    name: 'testing-group'
    group_family: 'redis4.0'
    description: 'testing-group'
```

##### EXPECTED RESULTS

creates a parameter group with group_family redis4.0
##### ACTUAL RESULTS

Throws errror that redis4.0 isn't a valid option

```

```
