### ISSUE TITLE
Facts should be gathered before playbook vars are set AKA why 'ansible_fqdn' is undefined 

### ISSUE THREAD

**Issue by LucidOne** [ansible/ansible#42715]
##### SUMMARY
I'm pretty sure this is a bug because there are more use cases where vars depend on facts than the other way around. Maybe playbook vars need to be handled separately, I haven't read the code yet.

This works.
```
---
- name: Gather facts
  hosts: 127.0.0.1
  connection: local
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    ansible_become_pass: "{{ lookup('pipe', 'pass ' + ansible_fqdn) }}"
```
this does not
```
---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    ansible_become_pass: "{{ lookup('pipe', 'pass ' + ansible_fqdn) }}"
```
and throws the error
```
TASK [Gathering Facts] *********************************************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "The field 'become_pass' has an invalid value, which includes an undefined variable. The error was: 'ansible_fqdn' is undefined"}
```

##### ISSUE TYPE
- ~~Bug  Report~~
- Feature Idea

##### COMPONENT NAME

ansible-playbook

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/.local/lib/python3.5/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

```

##### OS / ENVIRONMENT

n/a

##### STEPS TO REPRODUCE

```yaml
---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    ansible_become_pass: "{{ lookup('pipe', 'pass ' + ansible_fqdn) }}"
```
as noted above.

##### EXPECTED RESULTS

No errors

##### ACTUAL RESULTS

```
TASK [Gathering Facts] *********************************************************************************
fatal: [127.0.0.1]: FAILED! => {"msg": "The field 'become_pass' has an invalid value, which includes an undefined variable. The error was: 'ansible_fqdn' is undefined"}
```
