### ISSUE TITLE
azure_rm_networkinterface fails on Azure Stack

### ISSUE THREAD

**Issue by caohai** [ansible/ansible#42716]
##### SUMMARY

azure_rm_networkinterface fails when I use Ansible to create a network interface in Azure Stack.
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

azure_rm_networkinterface
azure_rm_common
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/azureuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

##### OS / ENVIRONMENT

1. I'm using Azure Stack Development Kit(1.1805.1.47)
2. I'm running Ansible on a Ubuntu Server 16.04 LTS Virtual Machine
##### STEPS TO REPRODUCE

1. Log in a Ubuntu server on Azure Stack. (ASDK in this case)
2. Run the playbook below
3. Deal with api version error as mentioned in #42658 by manually changing the api version to '2015-06-15'
4.  Run the playbook again.

```yaml
---
- hosts: localhost
  vars:
    location: local
    resource_group: user004
    storage_account: tesetsa004
    virtual_network: testvn004
    subnet: subnet004
    publicip: publicip004
    network_interface: testnic004
    security_group: secgroup004
  tasks:
  - name: Create a resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{ location }}"
  - name: Create storage account
    azure_rm_storageaccount:
      resource_group: "{{ resource_group }}"
      name: "{{ storage_account }}"
      account_type: Standard_LRS
      location: "{{ location }}"
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ virtual_network }}"
      address_prefixes: "10.10.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ subnet }}"
      address_prefix: "10.10.0.0/24"
      virtual_network: "{{ virtual_network }}"
  - name: Create public ip
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group }}"
      allocation_method: Static
      name: "{{ publicip }}"
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group }}"
      name: "{{ security_group }}"
      rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
  - name: Create NIC
    azure_rm_networkinterface:
      resource_group: "{{ resource_group }}"
      name: "{{ network_interface }}"
      virtual_network: "{{ virtual_network }}"
      subnet: "{{ subnet }}"
      public_ip_name: "{{ publicip }}"
      security_group: "{{ security_group }}"
```

##### EXPECTED RESULTS

Successfully create a network interface in my resource group.
##### ACTUAL RESULTS

```
PLAY [localhost] ***************************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Create a resource group] *************************************************
ok: [localhost]

TASK [Create storage account] **************************************************
ok: [localhost]

TASK [Create virtual network] **************************************************
ok: [localhost]

TASK [Add subnet] **************************************************************
ok: [localhost]

TASK [Create public ip] ********************************************************
ok: [localhost]

TASK [Create security group that allows SSH] ***********************************
ok: [localhost]

TASK [Create NIC] **************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "No handlers could be found for logger \"msrestazure.azure_active_directory\"
Traceback (most recent call last):
  File \"/tmp/ansible_YZq0_H/ansible_module_azure_rm_networkinterface.py\", line 663, in <module>
    main()
  File \"/tmp/ansible_YZq0_H/ansible_module_azure_rm_networkinterface.py\", line 659, in main
    AzureRMNetworkInterface()
  File \"/tmp/ansible_YZq0_H/ansible_module_azure_rm_networkinterface.py\", line 433, in __init__
    required_if=required_if)
  File \"/tmp/ansible_YZq0_H/ansible_modlib.zip/ansible/module_utils/azure_rm_common.py\", line 384, in __init__
  File \"/tmp/ansible_YZq0_H/ansible_module_azure_rm_networkinterface.py\", line 555, in exec_module
    ) for ip_config in self.ip_configurations
TypeError: __init__() got an unexpected keyword argument 'primary'
", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/home/azureuser/testPb/nicTest.retry

PLAY RECAP *********************************************************************
localhost                  : ok=7    changed=0    unreachable=0    failed=1
```
This error is caused by azure_rm_networkinterface implicitly using class [NetworkInterfaceIPConfiguration](https://github.com/ansible/ansible/blob/d5e9653c9645f615a613a59093243c35271917aa/lib/ansible/modules/cloud/azure/azure_rm_networkinterface.py#L545) of api version 2017-11-01 and many arguments in v2017-11-01 are not available in v2015-06-15, which is the latest version that Azure Stack supports. 

The error message above means NetworkInterfaceIPConfiguration can't take an argument 'primary', which is as expected because NetworkInterfaceIPConfiguration doesn't have parameter 'primary' in v2015-06-15.

##### FYI:

The newer NetworkInterfaceIPConfiguration class takes more arguments:
- api version 2017-11-01
```python
    def __init__(self, id=None, application_gateway_backend_address_pools=None, load_balancer_backend_address_pools=None, load_balancer_inbound_nat_rules=None, private_ip_address=None, private_ip_allocation_method=None, private_ip_address_version=None, subnet=None, primary=None, public_ip_address=None, application_security_groups=None, provisioning_state=None, name=None, etag=None):
```

- api version 2015-06-15
```python
    def __init__(self, id=None, load_balancer_backend_address_pools=None, load_balancer_inbound_nat_rules=None, private_ip_address=None, private_ip_allocation_method=None, subnet=None, public_ip_address=None, provisioning_state=None, name=None, etag=None):
```

A direct temporary fix: copy  network_interface_ip_configuration.py from v2017-11-01 and overwrite network_interface_ip_configuration.py in v2015-06-15. But I don't think this is good practice.
