### ISSUE TITLE
zypper_repository should import keys from iso

### ISSUE THREAD

**Issue by thiller2018** [ansible/ansible#42727]
##### SUMMARY

If the repository is an iso, the gpg key is not imported, rendering this repository unusable.
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

zypper_repository
##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/thiller/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/thiller/.virtualenvs/redfish/lib/python3.6/site-packages/ansible
  executable location = /home/thiller/.virtualenvs/redfish/bin/ansible
  python version = 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]

```

##### STEPS TO REPRODUCE

```yaml
  - name: Add iso repository
    zypper_repository:
      name: hfs-1.2
      repo: 'iso:///?iso=hpe-foundation-1.2-cd1-media-sles15-x86_64.iso&url=nfs://192.28.182.1/isos/hpe/hfs-1.2'
      state: present
      auto_import_keys: yes

```

##### ACTUAL RESULTS

```

```
