### ISSUE TITLE
Fortios returns "Error connecting device" while backup operation

### ISSUE THREAD

**Issue by webstylesInt** [ansible/ansible#42732]
##### SUMMARY
Backup fails with error: "changed": false, "msg": "Error connecting device"

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
fortios_config

##### ANSIBLE VERSION
ansible 2.6.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ansible/library/fortios']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Apr 11 2018, 07:36:10) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]

##### CONFIGURATION
DEFAULT_MODULE_PATH(/etc/ansible/ansible.cfg) = [u'/home/ansible/library/fortios']
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False

##### OS / ENVIRONMENT
Centos 7.4

##### STEPS TO REPRODUCE
```yaml
---

- hosts: fortigate
  gather_facts: true
  connection: local
  name: FortiGate backup playbook

  tasks:

  - name: Backup current config
    connection: local
    fortios_config:
      host: '{{ ansible_host }}'
      username: backup
      password: password
      backup: yes
      backup_filename: '{{ ansible_hostname }}.YYYY-MM-DD@HH:MM:SS'
      backup_path: /home/backup/
```

##### EXPECTED RESULTS
file to be backed up

##### ACTUAL RESULTS
FAILED! => {"changed": false, "msg": "Error connecting device"}
