### ISSUE TITLE
ec2_group is not idempotent for creating AWS security groups, also requires retries (run twice)

### ISSUE THREAD

**Issue by IPvSean** [ansible/ansible#42740]
##### SUMMARY
Two issues->

1. [WARNING]: Ran out of time waiting for sg-aa816de0 IpPermissions

getting warning and not sure why.  Was able to workaround this issue with a retries like this->

```
  register: create_sg
  until: create_sg is not failed
  retries: 5
```

2. When re-running this task over and over it always says CHANGED, I think it has something to do with the line `      Students: "{{student_total}}"` being an integer and the tag updating everytime.  The task also takes awhile to respond but I bet this would fix it.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
ec2_group

##### ANSIBLE VERSION
```
ansible 2.6.0
  config file = /Users/sean/Documents/GitHub/linklight/provisioner/ansible.cfg
  configured module search path = [u'/Users/sean/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

##### CONFIGURATION

```
DEFAULT_CALLBACK_WHITELIST(/Users/sean/Documents/GitHub/linklight/provisioner/ansible.cfg) = ['time']
DEFAULT_FORKS(/Users/sean/Documents/GitHub/linklight/provisioner/ansible.cfg) = 50
DEFAULT_HOST_LIST(/Users/sean/Documents/GitHub/linklight/provisioner/ansible.cfg) = [u'/Users/sean/Documents/GitHub/linklight/provisioner/hosts']
DEFAULT_NO_TARGET_SYSLOG(/Users/sean/Documents/GitHub/linklight/provisioner/ansible.cfg) = False
DEFAULT_SCP_IF_SSH(/Users/sean/Documents/GitHub/linklight/provisioner/ansible.cfg) = True
HOST_KEY_CHECKING(/Users/sean/Documents/GitHub/linklight/provisioner/ansible.cfg) = False
RETRY_FILES_ENABLED(/Users/sean/Documents/GitHub/linklight/provisioner/ansible.cfg) = False
```

##### OS / ENVIRONMENT
MacOS High Sierra 10.13.5

##### STEPS TO REPRODUCE

```yaml
- name: Create EC2 security group for VPC named {{ ec2_name_prefix }}-vpc
  ec2_group:
    name: "{{ ec2_name_prefix }}-insecure_all"
    description: all ports open
    region: "{{ ec2_region }}"
    vpc_id: "{{create_vpc.vpc.id}}"
    tags:
      Username: "{{ linklight_user }}"
      Info: "Username that provisioned this-> {{ linklight_user }}"
      Linklight: "This was provisioned through the linklight provisioner"
      Students: "{{student_total}}"
    rules:
      - proto: 47
        to_port: -1
        from_port: -1
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 443
        from_port: 443
        cidr_ip: 0.0.0.0/0
      - proto: icmp
        to_port: -1
        from_port: -1
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 80
        from_port: 80
        cidr_ip: 0.0.0.0/0
      - proto: tcp
        to_port: 22
        from_port: 22
        cidr_ip: 0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  when: ec2_vpc_id is undefined
  register: create_sg
  until: create_sg is not failed
  retries: 5
```

##### EXPECTED RESULTS

```
ok: [localhost]
```

##### ACTUAL RESULTS
```
TASK [manage_ec2_instances : Create EC2 security group for VPC named F5TEST-vpc] ************************************************************************************************
task path: /Users/sean/Documents/GitHub/linklight/provisioner/roles/manage_ec2_instances/tasks/resources.yml:16
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: sean
<localhost> EXEC /bin/sh -c 'echo ~sean && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/sean/.ansible/tmp/ansible-tmp-1531488678.69-33669336561925 `" && echo ansible-tmp-1531488678.69-33669336561925="` echo /Users/sean/.ansible/tmp/ansible-tmp-1531488678.69-33669336561925 `" ) && sleep 0'
Using module file /Library/Python/2.7/site-packages/ansible/modules/cloud/amazon/ec2_group.py
<localhost> PUT /Users/sean/.ansible/tmp/ansible-local-90016hSmVOf/tmpJSWj6N TO /Users/sean/.ansible/tmp/ansible-tmp-1531488678.69-33669336561925/ec2_group.py
<localhost> EXEC /bin/sh -c 'chmod u+x /Users/sean/.ansible/tmp/ansible-tmp-1531488678.69-33669336561925/ /Users/sean/.ansible/tmp/ansible-tmp-1531488678.69-33669336561925/ec2_group.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /Users/sean/.ansible/tmp/ansible-tmp-1531488678.69-33669336561925/ec2_group.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /Users/sean/.ansible/tmp/ansible-tmp-1531488678.69-33669336561925/ > /dev/null 2>&1 && sleep 0'
 [WARNING]: Ran out of time waiting for sg-aa816de0 IpPermissions. Current: set([Rule(port_range=(-1, -1), protocol='icmp', target='0.0.0.0/0', target_type='ipv4',
description=None), Rule(port_range=(80, 80), protocol='tcp', target='0.0.0.0/0', target_type='ipv4', description=None), Rule(port_range=(443, 443), protocol='tcp',
target='0.0.0.0/0', target_type='ipv4', description=None), Rule(port_range=(None, None), protocol='47', target='0.0.0.0/0', target_type='ipv4', description=None),
Rule(port_range=(22, 22), protocol='tcp', target='0.0.0.0/0', target_type='ipv4', description=None)]), Desired: [Rule(port_range=(22, 22), protocol='tcp', target='0.0.0.0/0',
target_type='ipv4', description=None), Rule(port_range=(-1, -1), protocol=47, target='0.0.0.0/0', target_type='ipv4', description=None), Rule(port_range=(80, 80),
protocol='tcp', target='0.0.0.0/0', target_type='ipv4', description=None), Rule(port_range=(-1, -1), protocol='icmp', target='0.0.0.0/0', target_type='ipv4', description=None),
Rule(port_range=(443, 443), protocol='tcp', target='0.0.0.0/0', target_type='ipv4', description=None)]

changed: [localhost] => {
    "attempts": 1,
    "changed": true,
    "description": "all ports open",
    "group_id": "sg-aa816de0",
    "group_name": "F5TEST-insecure_all",
    "invocation": {
        "module_args": {
            "aws_access_key": null,
            "aws_secret_key": null,
            "description": "all ports open",
            "ec2_url": null,
            "group_id": null,
            "name": "F5TEST-insecure_all",
            "profile": null,
            "purge_rules": true,
            "purge_rules_egress": true,
            "purge_tags": true,
            "region": "us-east-1",
            "rules": [
                {
                    "cidr_ip": "0.0.0.0/0",
                    "from_port": -1,
                    "proto": 47,
                    "to_port": -1
                },
                {
                    "cidr_ip": "0.0.0.0/0",
                    "from_port": 443,
                    "proto": "tcp",
                    "to_port": 443
                },
                {
                    "cidr_ip": "0.0.0.0/0",
                    "from_port": -1,
                    "proto": "icmp",
                    "to_port": -1
                },
                {
                    "cidr_ip": "0.0.0.0/0",
                    "from_port": 80,
                    "proto": "tcp",
                    "to_port": 80
                },
                {
                    "cidr_ip": "0.0.0.0/0",
                    "from_port": 22,
                    "proto": "tcp",
                    "to_port": 22
                }
            ],
            "rules_egress": [
                {
                    "cidr_ip": "0.0.0.0/0",
                    "proto": "all"
                }
            ],
            "security_token": null,
            "state": "present",
            "tags": {
                "Info": "Username that provisioned this-> scavanaugh",
                "Linklight": "This was provisioned through the linklight provisioner",
                "Students": 2,
                "Username": "scavanaugh"
            },
            "validate_certs": true,
            "vpc_id": "vpc-ce3ccfb4"
        }
    },
    "ip_permissions": [
        {
            "from_port": 80,
            "ip_protocol": "tcp",
            "ip_ranges": [
                {
                    "cidr_ip": "0.0.0.0/0"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "to_port": 80,
            "user_id_group_pairs": []
        },
        {
            "from_port": 22,
            "ip_protocol": "tcp",
            "ip_ranges": [
                {
                    "cidr_ip": "0.0.0.0/0"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "to_port": 22,
            "user_id_group_pairs": []
        },
        {
            "ip_protocol": "47",
            "ip_ranges": [
                {
                    "cidr_ip": "0.0.0.0/0"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "user_id_group_pairs": []
        },
        {
            "from_port": 443,
            "ip_protocol": "tcp",
            "ip_ranges": [
                {
                    "cidr_ip": "0.0.0.0/0"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "to_port": 443,
            "user_id_group_pairs": []
        },
        {
            "from_port": -1,
            "ip_protocol": "icmp",
            "ip_ranges": [
                {
                    "cidr_ip": "0.0.0.0/0"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "to_port": -1,
            "user_id_group_pairs": []
        }
    ],
    "ip_permissions_egress": [
        {
            "ip_protocol": "-1",
            "ip_ranges": [
                {
                    "cidr_ip": "0.0.0.0/0"
                }
            ],
            "ipv6_ranges": [],
            "prefix_list_ids": [],
            "user_id_group_pairs": []
        }
    ],
    "owner_id": "324218975267",
    "tags": {
        "Info": "Username that provisioned this-> scavanaugh",
        "Linklight": "This was provisioned through the linklight provisioner",
        "Students": "2",
        "Username": "scavanaugh"
    },
    "vpc_id": "vpc-ce3ccfb4"
}
```
