### ISSUE TITLE
Ansible git module reports success on pull to location with insufficient disk space

### ISSUE THREAD

**Issue by gchaix** [ansible/ansible#42754]
##### SUMMARY

When using the Ansible git module to do a clone/pull to a disk partition with insufficient capacity, the task incorrectly returns success.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

git
##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]
```

##### CONFIGURATION

No config changes from default CentOS 7 RPM install.

##### OS / ENVIRONMENT

CentOS Linux release 7.4.1708 (Core)

##### STEPS TO REPRODUCE

1) Choose a destination partition that has insufficient disk space
2) Run a task that does a git clone/pull

```yaml
---
- hosts: role_web
  any_errors_fatal: true
    - name: "git checkout/pull {{ appname }}/{{ tag }} on web node"
      become_user: deploy
      become: true
      git:
        repo: "{{ git_url }}"
        dest: "/var/git/{{ appname }}/{{ tag }}"
        version: "{{ tag }}"
        accept_hostkey: yes
```

##### EXPECTED RESULTS

The task should fail and not continue per the `any_errors_fatal` setting because the git clone/pull was not able to complete successfully. 

##### ACTUAL RESULTS

Jenkins log for the job shows the following:

```
TASK [git checkout/pull */2.11.3 on web node] ********************************
changed: [prod-web3.*.bak]
changed: [prod-web1.*.bak]
changed: [prod-web2.*.bak]

<snip>

TASK [Drush updb] **************************************************************
fatal: [prod-web1.*.bak]: FAILED! => {"changed": true, "cmd": ["/usr/bin/drush", "updb", "-y", "-r", "/var/www/*/current"], "delta": "0:00:01.654615", "end": "2018-07-13 10:30:08.274559", "msg": "non-zero return code", "rc": 255, "start": "2018-07-13 10:30:06.619944", "stderr": "The following module is missing from the file system: <em              [warning]\nclass=\"placeholder\">autoload</em>.
<snip>
```

`any_errors_fatal` was enabled, and the job continued to run after the git bits.  Further tasks failed because not all the files were present in the local git repository.

This was observed on a production system (ouch!) so I was not able to re-run with debug enabled.  I am spinning up a test environment with insufficient disk space and the newest stable release of Ansible to reproduce.  I will post a follow-up when that is complete.
