### ISSUE TITLE
Action wrappers for win_domain and win_domain_controller

### ISSUE THREAD

**Issue by nitzmahone** [ansible/ansible#42764]
##### SUMMARY

Both the `win_domain` and `win_domain_controller` modules can require reboots, and can cause connectivity issues during or after being run (the most common cause is that the WinRM service is stopped and not restarted). An action wrapper is the only way to "hide" the underlying connection failures that can occur, as well as managing the necessary reboots transparently. 

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

win_domain

##### ANSIBLE VERSION

```
2.7.0
```

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```

```

**Comment by ansibot** [comment]
Files identified in the description:
* [lib/ansible/modules/windows/win_domain.ps1](https://github.com/ansible/ansible/blob/devel/lib/ansible/modules/windows/win_domain.ps1)

If these files are inaccurate, please update the `component name` section of the description or use the `!component` bot command.

[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by ansibot** [comment]
cc @dagwieers @jborean93 @jhawkesworth
[click here for bot help](https://github.com/ansible/ansibullbot/blob/master/ISSUE_HELP.md)

**Comment by dagwieers** [comment]
@nitzmahone I was hoping the WinRM connection plugin could be told to survive this ? Maybe hinted that this is the case as part of the module's capabilities, rather than needing action plugins.

**Comment by jseiser** [comment]
Is this the same issue being shown here, https://github.com/ansible/ansible/issues/39235 ?

```
- name: Verify/Create Domain
  win_domain:
    dns_domain_name: "{{ dns_domain_name }}"
    safe_mode_password: "{{ ansible_password }}"
  register: is_domain

- name: Reboot if Required
  win_reboot:
  when: is_domain.reboot_required
```
```
TASK [internal/qa_env_dc : Reboot if Required] **********************************************************************************************************************************************************************************************************************************************************************
fatal: [10.0.136.5]: FAILED! => {"changed": false, "msg": "credssp: HTTPSConnectionPool(host='10.0.136.5', port=5986): Read timed out. (read timeout=30)", "reboot": false}
```
