### ISSUE TITLE
tower_job_wait reports fatal error on successful job

### ISSUE THREAD

**Issue by Rthur** [ansible/ansible#42784]
##### SUMMARY
tower_job_wait reports fatal error on successful job.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
tower_job_wait  

##### ANSIBLE VERSION
```
ansible-playbook 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
Using /etc/ansible/ansible.cfg as config file
```

##### OS / ENVIRONMENT
Red Hat Enterprise Linux Server release 7.4 (Maipo)  
Ansible Tower 2.5.4  

##### STEPS TO REPRODUCE
```yaml
  - tower_job_launch:
      tower_host: '{{ lookup("env", "TOWER_HOST") }}'
      tower_username: '{{ lookup("env", "TOWER_USERNAME") }}'
      tower_password: '{{ lookup("env", "TOWER_PASSWORD") }}'
      tower_verify_ssl: no
      job_template: the_job
      job_type: run
    register: other_job
  - tower_job_wait:
      tower_host: '{{ lookup("env", "TOWER_HOST") }}'
      tower_username: '{{ lookup("env", "TOWER_USERNAME") }}'
      tower_password: '{{ lookup("env", "TOWER_PASSWORD") }}'
      tower_verify_ssl: no
      job_id: '{{ other_job.id }}'
```

##### EXPECTED RESULTS
success

##### ACTUAL RESULTS
```
 [WARNING]: Module invocation had junk after the JSON data: } META: ran
handlers META: ran handlers  PLAY RECAP
*********************************************************************
<redacted>  : ok=30   changed=15   unreachable=0    failed=0
{"status": "successful", "success": true, "started":
"2018-07-14T17:07:48.435184Z", "elapsed": 201.247, "finished":
"2018-07-14T17:11:09.681815Z", "invocation": {"module_args": {"min_interval":
1.0, "max_interval": 30.0, "job_id": 1499, "timeout": null}}, "id": 1499}

<localhost> EXEC /bin/sh -c 'rm -f -r /var/lib/awx/.ansible/tmp/ansible-tmp-1531588063.93-147286531601978/ > /dev/null 2>&1 && sleep 0'
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "",
    "module_stdout": "Current status: pending\nCurrent status: pending\nCurrent status: running\nansible-playbook 2.6.1\r\n  config file = /etc/ansible/ansible.cfg\r\n  configured module search path = [u'/var/lib/awx/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']\r\n

  ... the entire output of the successful job ...

META: ran handlers\r\nMETA: ran handlers\r\n\r\nPLAY RECAP *********************************************************************\r\<redacted>   : ok=30   changed=15   unreachable=0    failed=0   \r\n\r\n\n{\"status\": \"successful\", \"success\": true, \"started\": \"2018-07-14T17:07:48.435184Z\", \"elapsed\": 201.247, \"finished\": \"2018-07-14T17:11:09.681815Z\", \"invocation\": {\"module_args\": {\"min_interval\": 1.0, \"max_interval\": 30.0, \"job_id\": 1499, \"timeout\": null}}, \"id\": 1499}\n",
    "msg": "MODULE FAILURE",
    "rc": 0
}
```
