### ISSUE TITLE
Issue with using beats template file -

### ISSUE THREAD

**Issue by gisundar** [ansible/ansible#42792]
##### SUMMARY

Trying to install beats (filebeat, metric and packet) using ansible 2.1. Created the template files for each . Getting error as follows:

```
[Ansible_2.1] $ sh -e /apps/jenkins/build/tools/org.jenkinsci.plugins.ansible.AnsibleInstallation/Ansible_2.1/hudson1752773756841256863.sh
ansible-playbook 2.1.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[AnsibleDeploy] $ sshpass ******** /usr/bin/ansible-playbook ansible/playbook/beatsDeploy_5.4.3-1.x86_64.yml -i ansible/inventory/group_vars -u cdadmin -k -e target_server=dev
ERROR! ansible/inventory/group_vars/dev/templates/filebeat.yml.j2:18: Expected key=value host variable assignment, got: type:
FATAL: command execution failed
hudson.AbortException: Ansible playbook execution failed
	at org.jenkinsci.plugins.ansible.AnsiblePlaybookBuilder.perform(AnsiblePlaybookBuilder.java:262)
	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:400)
	at org.jenkinsci.plugins.ansible.workflow.AnsiblePlaybookStep$AnsiblePlaybookExecution.run(AnsiblePlaybookStep.java:321)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1$1.call(AbstractSynchronousNonBlockingStepExecution.java:47)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.AbstractSynchronousNonBlockingStepExecution$1.run(AbstractSynchronousNonBlockingStepExecution.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

2.1
##### OS / ENVIRONMENT

RHEL 

##### STEPS TO REPRODUCE

```yaml

###################### Filebeat Configuration Example #########################

# This file is an example configuration file highlighting only the most common
# options. The filebeat.full.yml file from the same directory contains all the
# supported options with more comments. You can use it as a reference.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html

#=========================== Filebeat prospectors =============================

filebeat.inputs:

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# Below are the prospector specific configurations.

- type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
#    - /var/log/*.log
#    - /var/log/hbase/*.log
#    - /var/log/ambari-agent/*.log
#    - /var/log/ambari-server/*.log
#    - /var/log/hive/*.log
#    - /var/log/hive-hcatalog/*.log
#    - /var/log/kafka/*.log
#    - /var/log/spark/*.log
#    - /var/log/falcon/*.log
#    - /var/log/hue/*.log
#    - /var/log/hadoop-*/*.log
#    - /var/log/hadoop/*/*.log
#    - /var/log/*/*.log
#    - /var/audit/*
#    - /var/falcon/*
#    - /var/log/zookeeper/*
    - /var/log/scb-lily/*test.out

    #- c:\programdata\elasticsearch\logs\*

  # Exclude lines. A list of regular expressions to match. It drops the lines that are
  # matching any regular expression from the list.
  #exclude_lines: ["^DBG"]

  # Include lines. A list of regular expressions to match. It exports the lines that are
  # matching any regular expression from the list.
  #include_lines: ["^ERR", "^WARN"]

  # Exclude files. A list of regular expressions to match. Filebeat drops the files that
  # are matching any regular expression from the list. By default, no files are dropped.
  #exclude_files: [".gz$"]

  # Optional additional fields. These field can be freely picked
  # to add additional information to the crawled log files for filtering
  #fields:
  #  level: debug
  #  review: 1

  ### Multiline options

  # Mutiline can be used for log messages spanning multiple lines. This is common
  # for Java Stack Traces or C-Line Continuation

  # The regexp Pattern that has to be matched. The example pattern matches all lines starting with [
  #multiline.pattern: ^\[

  # Defines if the pattern set under pattern should be negated or not. Default is false.
  #multiline.negate: false

  # Match can be set to "after" or "before". It is used to define if lines should be append to a pattern
  # that was (not) matched before or after or as long as a pattern is not matched based on negate.
  # Note: After is the equivalent to previous and before is the equivalent to to next in Logstash
  #multiline.match: after


#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
#name:

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
#fields:
#  env: staging

registry_file: /var/lib/filebeat/registry
close_older: 5m
close_removed: true
clean_removed: true
close_renamed: true
ignore_older: 2h
force_close_files: true
#================================ Outputs =====================================

# Configure what outputs to use when sending the data collected by the beat.
# Multiple outputs may be used.

#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["{{ elkServerName }}:{{ elkServerPort }}"]

  # Optional protocol and basic auth credentials.
  #protocol: "https"
  username: "kibanauser"
  password: "kibanauser"

#  ssl.certificate_authorities: ["/data/apps/certelastic/ca/ca.crt"]
#  ssl.certificate: /data/apps/certelastic/SIT/SIT.crt
#  ssl.key: /data/apps/certelastic/SIT/SIT.key


#----------------------------- Logstash output --------------------------------
#output.logstash:
  # The Logstash hosts
  #hosts: ["localhost:5044"]

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: critical, error, warning, info, debug
#logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
#logging.selectors: ["*"]
files.rotateeverybytes: 10485760 # = 10MB
```

##### ACTUAL RESULTS

```

```
