### ISSUE TITLE
Ansible service not starting stating the below error when provided condition

### ISSUE THREAD

**Issue by learning-sharing** [ansible/ansible#42791]
##### SUMMARY
Am trying to restart the NetworkManager service in redhat7 only when the service is running and not when it is stopped so i prepared ansible playbook to restart it only when the service is running but its not working as expected and gives the same error

##### ISSUE TYPE
 - Bug Report : Service restart issue

##### ANSIBLE VERSION
```
ansible --version
ansible 2.6.0
  config file = /home/mv/ansible/ansible.cfg
  configured module search path = [u'/home/mv/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May 31 2018, 09:41:32) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```
##### STEPS TO REPRODUCE

 This is the ansible playbook i wrote
```
---
-
 hosts: "{{host}}"
 become: yes
 become_method: sudo
 tasks:
   - name: Check whether Network manager is running
     shell: systemctl status NetworkManager | grep -o "running"
     register: myvalue
   - service:
       name: NetworkManager
       state: restarted
       when: myvalue == "running"
...
```

##### EXPECTED RESULTS

Expected result to start the Network Manager service only when running but it is identifying the server correctly but the service restart is erroring out

##### ACTUAL RESULTS
```
SSH password:

PLAY [redhat,redhat2] *********************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************
ok: [ansibleclient-2]
ok: [ansibleclient-1]

TASK [Check whether Network manager is running] *******************************************************************************
changed: [ansibleclient-2]
fatal: [ansibleclient-1]: FAILED! => {"changed": true, "cmd": "systemctl status NetworkManager | grep -o \"running\"", "delta": "0:00:00.020380", "end": "2018-07-15 08:27:19.095261", "msg": "non-zero return code", "rc": 1, "start": "2018-07-15 08:27:19.074881", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}

TASK [service] ****************************************************************************************************************
fatal: [ansibleclient-2]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (systemd) module: when Supported parameters include: daemon_reload, enabled, force, masked, name, no_block, state, user"}
        to retry, use: --limit @/home/mv/ansible/restartonlywhenrunning.retry

PLAY RECAP ********************************************************************************************************************
ansibleclient-1            : ok=1    changed=0    unreachable=0    failed=1
ansibleclient-2            : ok=2    changed=1    unreachable=0    failed=1
```

**Comment by learning-sharing** [comment]
OS version
Red Hat Enterprise Linux Server release 7.5 (Maipo)

**Comment by sivel** [comment]
You have multiple errors with you playbook:

1. You are not accounting for the scenario where `systemctl status NetworkManager | grep -o "running"` will return a non-zero exit code, and is thus failing for one host at this point.  Instead use the `service_facts` module to assist you in getting the service state
1. The output from the `shell` module will place the output into `myvalue.stdout` instead of just `myvalue` which is a dict/hash
1. You have over indented the `when` line.  It is not an argument to the `systemd` module, instead it is a task argument:

    ```
    - service:
        name: NetworkManager
        state: restarted
      when: myvalue.stdout == "running"
    ```

There may be more issues, but these are the primary concerns.

If you have further questions please stop by IRC or the mailing list:

   * IRC: #ansible on irc.freenode.net
   * mailing list: https://groups.google.com/forum/#!forum/ansible-project
