### ISSUE TITLE
Add NX-OS BFD support

### ISSUE THREAD

**Issue by fenris02** [ansible/ansible#42874]
##### SUMMARY
BFD is a detection protocol designed to provide fast forwarding-path failure detection times for media types, encapsulations, topologies, and routing protocols. You can use BFD to detect forwarding path failures at a uniform rate, rather than the variable rates for different protocol hello mechanisms. BFD makes network profiling and planning easier and reconvergence time consistent and predictable.

BFD provides subsecond failure detection between two adjacent devices and can be less CPU-intensive than protocol hello messages because some of the BFD load can be distributed onto the data plane on supported modules.

BFD support is not a module in Ansible today.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
nxos_bfd
nxos_bfd_ospf
nxos_bfd_pim
nxos_bfd_bgp

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = [u'/Users/dj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 12:46:58) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)]
```

##### CONFIGURATION

no changes to defaults

##### OS / ENVIRONMENT

N/A

##### STEPS TO REPRODUCE

```yaml
---
- name: "Enable features in NX-OS switches: bfd"
  nxos_feature:
    feature: bfd
    state: enabled

- name: "Setup BFD defaults"
  nxos_config:
    lines:
      - bfd interval 50 min_rx 50 multiplier 3
      - bfd slow-timer 2000
      - no bfd echo-interface
      - bfd echo-rx-interval 50
      - bfd ipv4 interval 50 min_rx 50 multiplier 3
      - bfd ipv6 interval 50 min_rx 50 multiplier 3
      - bfd ipv4 slow-timer 2000
      - bfd ipv6 slow-timer 2000
      - bfd ipv4 echo-rx-interval 50
      - bfd ipv6 echo-rx-interval 50
      - bfd startup-timer 5

- name: "Enable BFD for PIM"
  nxos_config:
    lines:
      - ip pim bfd

- name: "Enable BFD for OSPF"
  nxos_config:
    lines:
      - bfd
    parents: router ospf 1

# FIXME!! This is ugly
- name: "Enable BFD for BGP"
  nxos_config:
    lines:
      - router bgp {{ asn }} ; neighbor {{ item.neighbor }} ; bfd
  with_items: "{{ bgp_neighbors }}"
  ignore_errors: true

...
# vim: tabstop=2 shiftwidth=2 expandtab
```

##### EXPECTED RESULTS

```yaml
----
- nxos_bfd:
    interval: 50 
    min_rx: 50 
    multiplier: 3

- nxos_bfd_ospf
    process_id: 1
    state: enabled

- nxos_bfd_pim
    state: enabled

- nxos_bfd_bgp_neighbor
    asn: 65000
    neighbor: 192.168.100.1
    state: enabled

...
# vim: tabstop=2 shiftwidth=2 expandtab
```

##### ACTUAL RESULTS

This can be enabled using the _command modules (as above) but this is not ideal.

```

```

ref/ https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/6-x/interfaces/configuration/guide/b_Cisco_Nexus_9000_Series_NX-OS_Interfaces_Configuration_Guide/b_Cisco_Nexus_9000_Series_NX-OS_Interfaces_Configuration_Guide_chapter_0101.html
