### ISSUE TITLE
$variables substituted in .j2 templates (cfg setting doesn't turn off?)

### ISSUE THREAD

**Issue by jorgenschaefer** [ansible/ansible#4287]
When a variable `foo` is defined, `$foo` in a Jinja2 template is being substituted in addition to `{{ foo }}`. I don't think this is intentional?

**foo.txt.j2**

```
$test = {{test}}
```

**playbook.yml**

```

---
- hosts: server
  sudo: yes
  gather_facts: False
  tasks:
    - template: src=foo.txt.j2
                dest=/root/foo.txt
  vars:
    - test: foo
```

Results in:

**foo.txt**

```
foo = foo
```
