### ISSUE TITLE
Confusing behaviour with -K, --ask-become-pass 

### ISSUE THREAD

**Issue by LucidOne** [ansible/ansible#42875]
##### SUMMARY
This seems like more of a bug than feature request to me but :man_shrugging:

`ansible-playbook -i 'localhost,' -K my_playbook`
Asks for a password, but doesn't actually use it if sudo has credential caching enabled

`ansible-playbook -i 'localhost,' -K my_playbook`
Prompts for a password, but doesn't use it if `ansible_become_pass` is set in the play

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

playbook

##### ANSIBLE VERSION

```
ansible-playbook 2.6.1
  config file = None
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/username/.local/lib/python3.5/site-packages/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

ansible-playbook 2.7.0.dev0
  config file = None
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible-2.7.0.dev0-py3.5.egg/ansible
  executable location = /usr/local/bin/ansible-playbook
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]
```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a

##### STEPS TO REPRODUCE

```yaml
---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: "{{ ansible_fqdn is defined }}"
  vars:
#    ansible_become_pass: "{{ lookup('pipe', 'pass ' + ansible_fqdn|default('')) }}"
  tasks:
    - name: apt-get update/upgrade
      apt:
        update_cache=yes
    - name: apt-get update/upgrade
      apt:
        upgrade=yes
```

##### EXPECTED RESULTS

If the following is executed
```
/usr/local/bin/ansible-playbook -K -i 'localhost,' playbook_00
/usr/local/bin/ansible-playbook -K -i 'localhost,' playbook_01
/usr/local/bin/ansible-playbook -K -i 'localhost,' playbook_02
```
Ansible should either only ask for the sudo password once or should actually check the password each time.

##### ACTUAL RESULTS
CLI password input is not checked if sudo credentials are cached or `ansible_become_pass` is set

It seems to me that either ansible-playbook should run `sudo --reset-timestamp` to drop the current credentials and actually check the password or it should run `sudo -n true 2> /dev/null` and check the return code to see if credential caching is active and not ask for the password if the user has valid credentials.

```

```
