### ISSUE TITLE
Add ability to apply commit labels on iosxr_config module

### ISSUE THREAD

**Issue by jmighion** [ansible/ansible#42873]
##### SUMMARY

Copy of https://github.com/ansible/proposals/issues/117
Currently, the IOSXR_CONFIG module allows for the addition of commit comments, but does not give the ability to add a commit label. Commit labels in many enterprise environments allow quick reference to various commits to allow for quicker rollbacks and less confusion when a rollback is needed.

When IOSXR_CONFIG makes a commit, it does not apply a commit label, leaving no tags for quick rollback. Rollbacks on IOS-XR devices are reference using a machine generated CommitID, but the ability to add a commit label allows the user to set a reference to the commit.

##### Solution proposal
Add an additional parameter to the IOSXR_CONFIG module that allows the addition of a commit label when the module commits a change.

On an IOS-XR device, a commit label is added using the following configuration command
```
!
conf t
! 
commit label <word>
!
```
```
    - iosxr_config
         commands:
         comment: This is the existing parameter that allows the addition of a commit comment
         label: This is the proposed parameter that would allow the addition of a commit label
```
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

iosxr_config

##### ANSIBLE VERSION

```
$ ansible --version
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/james/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

##### OS / ENVIRONMENT

N/A
