### ISSUE TITLE
Incorrect doc for s3 module's dest and expiry option

### ISSUE THREAD

**Issue by blair** [ansible/ansible#4289]
The `dest` option appears to have the wrong documentation as it mentions 600:

```
  dest:    description:
      - The destination file path when downloading an object/key with a GET operation.
    required: false
    default: 600
    aliases: []
    version_added: "1.3"
```

while `expiry` doesn't mention the 600 default:

```
  expiry:
    description:
      - Time limit (in seconds) for the URL generated and returned by S3/Walrus 
when performing a mode=put or mode=geturl operation. 
    required: false
    default: null
    aliases: []
```

It looks like the 600 is for the `expiry` option:

```
        expiry         = dict(default=600, aliases=['expiration']),
```
