### ISSUE TITLE
unarchive execution removes access to OS commands deletes OS on Ubuntu 16.04 

### ISSUE THREAD

**Issue by aflatto** [ansible/ansible#42896]
##### SUMMARY

Extracting a tarball with unarchive removes /disable access to OS commands

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

unarchive

##### ANSIBLE VERSION

```
ansible 2.4.3.0
  config file = /home/assaf/WorkSpace/infrared/ansible.cfg
  configured module search path = [u'/home/assaf/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/assaf/WorkSpace/infrared/.venv/lib/python2.7/site-packages/ansible
  executable location = /home/assaf/WorkSpace/infrared/.venv/bin/ansible
  python version = 2.7.15 (default, May 16 2018, 17:50:09) [GCC 8.1.1 20180502 (Red Hat 8.1.1-1)]
```

##### CONFIGURATION

```
ANSIBLE_PIPELINING(/home/assaf/WorkSpace/infrared/ansible.cfg) = True
ANSIBLE_SSH_ARGS(/home/assaf/WorkSpace/infrared/ansible.cfg) = -C -o ControlMaster=auto -o ControlPersist=60m
ANSIBLE_SSH_CONTROL_PATH(/home/assaf/WorkSpace/infrared/ansible.cfg) = %(directory)s/ansible-ssh-%%h-%%p-%%r
ANSIBLE_SSH_RETRIES(/home/assaf/WorkSpace/infrared/ansible.cfg) = 3
DEFAULT_CALLBACK_PLUGIN_PATH(/home/assaf/WorkSpace/infrared/ansible.cfg) = [u'/home/assaf/WorkSpace/infrared/library/callbacks']
DEFAULT_CALLBACK_WHITELIST(/home/assaf/WorkSpace/infrared/ansible.cfg) = ['timer', 'profile_tasks']
DEFAULT_FILTER_PLUGIN_PATH(/home/assaf/WorkSpace/infrared/ansible.cfg) = [u'/home/assaf/WorkSpace/infrared/library/filters']
DEFAULT_FORKS(/home/assaf/WorkSpace/infrared/ansible.cfg) = 500
DEFAULT_GATHERING(/home/assaf/WorkSpace/infrared/ansible.cfg) = smart
DEFAULT_GATHER_TIMEOUT(/home/assaf/WorkSpace/infrared/ansible.cfg) = 30
DEFAULT_HOST_LIST(/home/assaf/WorkSpace/infrared/ansible.cfg) = [u'/home/assaf/WorkSpace/infrared/hosts']
DEFAULT_STDOUT_CALLBACK(/home/assaf/WorkSpace/infrared/ansible.cfg) = debug
DEFAULT_TIMEOUT(/home/assaf/WorkSpace/infrared/ansible.cfg) = 30
HOST_KEY_CHECKING(/home/assaf/WorkSpace/infrared/ansible.cfg) = False
RETRY_FILES_ENABLED(/home/assaf/WorkSpace/infrared/ansible.cfg) = False
```
##### STEPS TO REPRODUCE

```yaml

# general vars
donwload_path: "/var/tmp"
install_dir: "/usr/local/bin"
exporter_version: "14.0"

- name: Download Node exporter
  get_url:
       url:  "https://github.com/prometheus/node_exporter/releases/download/v0.{{exporter_version}}/node_exporter-0.{{exporter_version}}.linux-amd64.tar.gz"
       dest: "{{ donwload_path }}/node_exporter-0.{{exporter_version}}.linux-amd64.tar.gz"
       mode: "u=rwx,g=rx,o=r"
       owner: root
       group: root
       validate_certs: no
  register: node_download
  until: node_download|success
  retries: 10

- name: Install the node Exporter
  unarchive:
    src: "{{ donwload_path }}/node_exporter-0.{{exporter_version}}.linux-amd64.tar.gz"
    dest: "{{ install_dir }}"
    mode: "u=rwx,g=rx,o=r"
    remote_src: yes
    validate_certs: no
    extra_opts: [--strip-components=1]
  register: node_extract
  when: node_download|success

```

##### EXPECTED RESULTS

The tarball to be extracted and the file node_exporter to be located in the /usr/local/bin directory with executable permission. 

##### ACTUAL RESULTS

the download succeeded, but the extraction failed and no OS command could be run afterwards.  

```
TASK [prometheus : Download Node exporter] *****************************************************************************************************************************
task path: /home/assaf/WorkSpace//infrared/infrared/common/roles/prometheus/tasks/node_exporter.yml:2
Tuesday 17 July 2018  15:51:26 +0300 (0:00:00.481)       0:01:20.232 ********** 
changed: [aio1] => {
    "attempts": 1, 
    "changed": true, 
    "checksum_dest": null, 
    "checksum_src": "7f268a8327a4b1b9137176389f4ee841dae88d2e", 
    "dest": "/var/tmp/node_exporter-0.14.0.linux-amd64.tar.gz", 
    "gid": 0, 
    "group": "root", 
    "md5sum": "ee8761d8233ae5d3f99cc0edc758cd83", 
    "mode": "0754", 
    "owner": "root", 
    "size": 4019675, 
    "src": "/tmp/tmpng0_o4", 
    "state": "file", 
    "status_code": 200, 
    "uid": 0, 
    "url": "https://github.com/prometheus/node_exporter/releases/download/v0.14.0/node_exporter-0.14.0.linux-amd64.tar.gz"
}

MSG:

OK (4019675 bytes)


TASK [prometheus : Install the node Exporter] **************************************************************************************************************************
task path: /home/assaf/WorkSpace/infrared/infrared/common/roles/prometheus/tasks/node_exporter.yml:14
Tuesday 17 July 2018  15:51:29 +0300 (0:00:02.995)       0:01:23.228 ********** 
 [WARNING]: Error deleting remote temporary files (rc: 1, stderr: Could not chdir to home directory /home/ubuntu: Permission denied /bin/bash: Permission denied })

changed: [aio1] => {
    "changed": true, 
    "dest": "/tmp/", 
    "extract_results": {
        "cmd": [
            "/bin/tar", 
            "--extract", 
            "-C", 
            "/tmp/", 
            "-z", 
            "--show-transformed-names", 
            "--strip-components=1", 
            "-f", 
            "/var/tmp/node_exporter-0.14.0.linux-amd64.tar.gz"
        ], 
        "err": "", 
        "out": "", 
        "rc": 0
    }, 
    "gid": 0, 
    "group": "root", 
    "handler": "TgzArchive", 
    "mode": "01777", 
    "owner": "root", 
    "size": 4096, 
    "src": "/var/tmp/node_exporter-0.14.0.linux-amd64.tar.gz", 
    "state": "directory", 
    "uid": 0
}

TASK [prometheus : Add node exporter service file] *********************************************************************************************************************
task path: /home/assaf/WorkSpace/infrared/infrared/common/roles/prometheus/tasks/node_exporter.yml:25
Tuesday 17 July 2018  15:51:32 +0300 (0:00:02.458)       0:01:25.686 ********** 
fatal: [aio1]: UNREACHABLE! => {
    "changed": false, 
    "unreachable": true
}

MSG:

Authentication or permission failure. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote temp path in ansible.cfg to a path rooted in "/tmp". Failed command was: ( umask 77 && mkdir -p "` echo ~/.ansible/tmp/ansible-tmp-1531831892.21-85330574501713 `" && echo ansible-tmp-1531831892.21-85330574501713="` echo ~/.ansible/tmp/ansible-tmp-1531831892.21-85330574501713 `" ), exited with result 1



ubuntu@ip-172-33-222-213:~$ cd
-bash: cd: /home/ubuntu: Permission denied
ubuntu@ip-172-33-222-213:~$ ls
ls: command not found
ubuntu@ip-172-33-222-213:~$ /bin/ls
-bash: /bin/ls: Permission denied
ubuntu@ip-172-33-222-213:~$ sudo su - 
sudo: command not found
ubuntu@ip-172-33-222-213:~$ cat 
cat: command not found
ubuntu@ip-172-33-222-213:~$ ping
ping: command not found
ubuntu@ip-172-33-222-213:~$ /usr
-bash: /usr: Permission denied
ubuntu@ip-172-33-222-213:~$ /bin/bash
-bash: /bin/bash: Permission denied
ubuntu@ip-172-33-222-213:~$ /bin/sh
-bash: /bin/sh: Permission denied
ubuntu@ip-172-33-222-213:~$ /sbin/sh
-bash: /sbin/sh: Permission denied
ubuntu@ip-172-33-222-213:~$ less
less: command not found
ubuntu@ip-172-33-222-213:~$ find
find: command not found
```
