### ISSUE TITLE
Multiple yaml documents in a single playbook file

### ISSUE THREAD

**Issue by LucidOne** [ansible/ansible#42898]
##### SUMMARY
Support concatenating several play books together to run in a single `ansible-playbook` session.

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
playbook

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = None
  configured module search path = ['/home/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

```

##### CONFIGURATION

n/a

##### OS / ENVIRONMENT

n/a

##### STEPS TO REPRODUCE

multi.yml
```yaml
---
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: apt-get update
      apt:
        update_cache=yes
...
---
- name: run more playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: apt-get upgrade
      apt:
        upgrade=yes
...

```

##### EXPECTED RESULTS
Run the first document, then the second document within the context of the same
`ansible-playbook -i'localhost,' -K multi.yml` session
So it only has to ask for the become password once.

##### ACTUAL RESULTS
```
$ ansible-playbook -i'localhost,' -K multi.yml 
SUDO password: 
ERROR! Syntax Error while loading YAML.
  but found another document

The error appears to have been in '/home/username/Ansible/multi.yml': line 11, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

...
---
^ here
```

```

```

**Comment by Akasurde** [comment]
I would recommend you to write a role instead of a single file with multiple plays. You can have multiple play in a single yaml file like this -

```yaml

---
- name: sample1
  hosts: localhost
  gather_facts: no
  tasks:
    - name: sample_task1
      debug:
        msg: "sample 1 task 1"

- name: sample2
  hosts: localhost
  gather_facts: no
  tasks:
    - name: sample_task2
      debug:
        msg: "sample 2 task 2"
```

Console 

```
# ansible-playbook multi.yml

PLAY [sample1] *****************************************************************************************************************

TASK [sample_task1] ************************************************************************************************************
ok: [localhost] => {
    "msg": "sample 1 task 1"
}

PLAY [sample2] *****************************************************************************************************************

TASK [sample_task2] ************************************************************************************************************
ok: [localhost] => {
    "msg": "sample 2 task 2"
}

PLAY RECAP *********************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0

```
