### ISSUE TITLE
Ovirt network missing external_provider option

### ISSUE THREAD

**Issue by gtranche** [ansible/ansible#42895]
##### SUMMARY

There is no option in module ovirt_network to define the external_provider ovn included with ovirt 4.2
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

ovirt_networks
##### ANSIBLE VERSION

```
ansible 2.5.5
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/usr/share/efficientIP_module']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Feb 20 2018, 09:19:12) [GCC 4.8.5 20150623 (Red Hat 4.8.5-28)]
```

##### CONFIGURATION

N/A
##### OS / ENVIRONMENT

Redhat 7.5
##### STEPS TO REPRODUCE

```yaml
# Create network
- ovirt_networks:
    data_center: mydatacenter
    name: mynetwork
    vlan_tag: 1
    vm_network: true
```
may be
```yaml
# Create network
- ovirt_networks:
    data_center: mydatacenter
    name: mynetwork
    vlan_tag: 1
    vm_network: true
    external_provider: ovirt-provider-ovn
```

##### EXPECTED RESULTS

Add "external_provider: ovirt-provider-ovn"
And add network to the external ovn provided with ovirt 4.2
##### ACTUAL RESULTS

Network are added to the old network "database" and the virtual machines doesn't have access to any network when the cluster is configured with ovn.

```

```
