### ISSUE TITLE
os_user_role module fails in multidomain environment

### ISSUE THREAD

**Issue by carstenkoester** [ansible/ansible#42911]
##### SUMMARY
In an OpenStack environment with multiple domains and when using keystone (identity) API v3, os_user_role module fails with HTTP 401 "The request you have made requires authentication"

This is essentially a spin-off off #42901 but for a different module.

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

os_user_role

##### ANSIBLE VERSION

```
ansible 2.6.1
  config file = /workspace/ckoester/180715_192801/0001-02040/ansible.cfg
  configured module search path = [u'/home/ckoester/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ckoester/ansible26/local/lib/python2.7/site-packages/ansible
  executable location = /home/ckoester/ansible26/bin/ansible
  python version = 2.7.12 (default, Nov 20 2017, 18:23:56) [GCC 5.4.0 20160609]
```

##### CONFIGURATION

N/A

##### OS / ENVIRONMENT

On Ansible and control host side, no specific platform dependencies.

In order to reproduce this issue, on the OpenStack side (which the os_user module is utilized against):

 - must be using Identity API v3
 - must be a multidomain environment (ie. multiple domains must actually exist)

(Even then, the issue may be reproducible on one openstack environment but not on another, depending on the specific configuration on that environment.)

##### STEPS TO REPRODUCE

```yaml
---
- hosts: inception
  gather_facts: no
  any_errors_fatal: yes
  tasks:
    - name: For debug and illustration, set cloud config here
      set_fact:
        cloud_config:
          auth:
            auth_url: "https://openstack.api.endpoint.url:5000/v3"
            password: "<existing user password>"
            project_name: "<existing user project>"
            username: "<existing username>"
            user_domain_name: "default"
            project_domain_name: "default"
          identity_api_version: 3
          verify: False

    - name: Make user a project admin
      os_user_role:
        cloud: "{{ cloud_config }}"
        state: present
        user: "testuser"
        domain: "default"
        project: "testproject"
        role: admin
```

##### EXPECTED RESULTS

User role is modified

##### ACTUAL RESULTS

```
TASK [Make user a project admin] ********************************************************************************************************************************************************************************************************************
fatal: [ngena3-inception]: FAILED! => {"changed": false, "extra_data": null, "msg": "HttpException: 401: Client Error for url: https://api-ngena3.client.metacloud.net:5000/v3/users, {\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}"}
```

As described in #42901, the error message is misleading. This is not a simple authentication failure (and the credentials copied in the sample above are not real credentials, naturally). The issue stems from the fact that the user lookup (happening as pre-check for the os_user_role module) does not take into account the domain parameter, and hence fails as per https://bugs.launchpad.net/horizon/+bug/1415588 and similar OpenStack issue reports:

```
   139          if user:
   140              u = cloud.get_user(user)
   141              if u is None:
   142                  module.fail_json(msg="User %s is not valid" % user)
   143              filters['user'] = u['id']
```

Line 140 would need to take the `domain` parameter into account if one has been provided.
