### ISSUE TITLE
Pickle Data was Truncated 

### ISSUE THREAD

**Issue by maughanc** [ansible/ansible#42912]
##### SUMMARY

Upgraded ansible to version 2.6.1 
ran the following: 

```
- name: show int fa4 ip address
  ios_command:
    commands: show run int fa4
  become: yes
  become_method: enable
```

And received the following error:  FAILED! => {"msg": "pickle data was truncated"}

##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME

ios_command
##### ANSIBLE VERSION

```
2.6.1
```

##### OS / ENVIRONMENT

DEFAULT_ASK_VAULT_PASS(/etc/ansible/ansible.cfg) = True
DEFAULT_FORKS(/etc/ansible/ansible.cfg) = 12
DEFAULT_HOST_LIST(/etc/ansible/ansible.cfg) = [u'/etc/ansible/hosts']
DEFAULT_TIMEOUT(/etc/ansible/ansible.cfg) = 15
DEFAULT_VAULT_PASSWORD_FILE(/etc/ansible/ansible.cfg) = /etc/ansible/vault_pass
HOST_KEY_CHECKING(/etc/ansible/ansible.cfg) = False
RETRY_FILES_ENABLED(/etc/ansible/ansible.cfg) = False
##### STEPS TO REPRODUCE

```yaml

- name: show int fa4 ip address
  ios_command:
    commands: show run int fa4
  become: yes
  become_method: enable
```

##### EXPECTED RESULTS

Expected to run without problem 
##### ACTUAL RESULTS

{"msg": "pickle data was truncated"}

```
Too much 
```
